### PR TITLE
LPS-155670 Remove getLibDir method from PropsUtil

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
pushed to clean up ClassUtilTest

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
@vicnate5 Hi Victor, I just noticed Catarine is off today.

**Comment by Kvale1733** [comment]
@julschong 

Regression in com.liferay.portal.kernel.util.ClassUtilTest

`Testcase: testGetPathURIFromURLWithUnknownProtocol(com.liferay.portal.kernel.util.ClassUtilTest):	FAILED
    [junit] expected same:<class com.liferay.portal.kernel.exception.SystemException> was not:<class java.lang.NoSuchMethodException>
    [junit] junit.framework.AssertionFailedError: expected same:<class com.liferay.portal.kernel.exception.SystemException> was not:<class java.lang.NoSuchMethodException>
    [junit] 	at com.liferay.portal.kernel.util.ClassUtilTest.testGetPathURIFromURLWithUnknownProtocol(ClassUtilTest.java:246)
    [junit] 	at com.liferay.portal.kernel.test.rule.CodeCoverageAssertor$1.evaluate(CodeCoverageAssertor.java:81)
    [junit] 
    [junit] 
    [junit] Testcase: testGetPathURIFromURLWithIllegalCharacter(com.liferay.portal.kernel.util.ClassUtilTest):	FAILED
    [junit] expected same:<class com.liferay.portal.kernel.exception.SystemException> was not:<class java.lang.NoSuchMethodException>
    [junit] junit.framework.AssertionFailedError: expected same:<class com.liferay.portal.kernel.exception.SystemException> was not:<class java.lang.NoSuchMethodException>
    [junit] 	at com.liferay.portal.kernel.util.ClassUtilTest.testGetPathURIFromURLWithIllegalCharacter(ClassUtilTest.java:221)
    [junit] 	at com.liferay.portal.kernel.test.rule.CodeCoverageAssertor$1.evaluate(CodeCoverageAssertor.java:81)
    [junit] 
    [junit] 
    [junit] Testcase: testGetPathURIFromURL(com.liferay.portal.kernel.util.ClassUtilTest):	Caused an ERROR
    [junit] No method on null with name _getPathURIFromURL and parameter types [class java.net.URL]
    [junit] java.lang.NoSuchMethodException: No method on null with name _getPathURIFromURL and parameter types [class java.net.URL]
    [junit] 	at com.liferay.portal.kernel.test.ReflectionTestUtil.getMethod(ReflectionTestUtil.java:190)
    [junit] 	at com.liferay.portal.kernel.test.ReflectionTestUtil.invoke(ReflectionTestUtil.java:199)
    [junit] 	at com.liferay.portal.kernel.util.ClassUtilTest._testGetPathURIFromURL(ClassUtilTest.java:368)
    [junit] 	at com.liferay.portal.kernel.util.ClassUtilTest._testGetPathURIFromURL(ClassUtilTest.java:341)
    [junit] 	at com.liferay.portal.kernel.util.ClassUtilTest.testGetPathURIFromURL(ClassUtilTest.java:154)
    [junit] 	at com.liferay.portal.kernel.test.rule.CodeCoverageAssertor$1.evaluate(CodeCoverageAssertor.java:81)`

**Comment by julschong** [comment]
@Kvale1733 Hi Kevin,
Could you please help me check if you scanned the later test result?
I removed the unit test then ran ci test again after here: https://github.com/liferay-core-infra/liferay-portal/pull/1581#issuecomment-1241390483

**Comment by Kvale1733** [comment]
@julschong Yeah you are right. My bad. Let me check again.

**Comment by Kvale1733** [comment]
@julschong Alright looks good then. No regressions.

**Comment by tinatian** [comment]
@julschong Please update the commit message to include the reason you did this.

Thanks.
Tina

**Pull request closed without merging**
