### PR TITLE
LPS-145396 When we delete some types of objects in Liferay, we are not deleting their ResourcePermission records (includes test)

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
When we delete some types of objects in Liferay, we are not deleting their ResourcePermission records, leaving some orphan data in the ResourcePermission table.

I have detected and solved this issue for some objects in previous LPSs, see: LPS-138985 (navigation menus), LPS-144653 (redirect entry urls), LPS-144733 (navigation menus), and LPS-144567 (asset libraries)

In this LPS I am solving the same issue for several objects (_ExpandoColumn, KBFolder, KaleoDefinitionVersion, LayoutBranch, MDRRuleGroup, MicroblogsEntry, OAuth2Application, Role_), but I am also adding a test rule that detects this issue in a deletion of any integration test, so we will detect future failures in new code / services, as soon as an integration test tests its deletion logic.

**Code changes:**
 - **Commits 1st to 3rd:** I am adding a new OrphanDetectionTestRule that tracks all the deleted objects and when the transaction is committed searches for orphan ResourcePermission records.
 - **Commits 5th to 13th and 16th**: I am fixing the deletion of the resource permission records for several objects
 - **Commit 14th:** Replace LocalServiceBaseImpl delete method calls with LocalServiceImpl ones, as the Base ones do not delete all the related objects.

The `OrphanDetectionTestRule` code registers a SessionWrapper and a TransactionLifecycleListener for each integration test executed.
They are registered/unregistered before DeleteAfterTestRunMethodTestRule because it generates some false positives, and before DataGuardTestRule because it deletes everything created during the test, so no Orphan can be checked.

You can see the output of the `OrphanDetectionTestRule` in this PR that only contains the tests without fixing the issues: https://github.com/jorgediaz-lr/liferay-portal/pull/424#issuecomment-1026190375

For example, the test **DLFileEntryLocalServiceTest.testCopyFileEntry** fails:
```
com.liferay.document.library.service.test.DLFileEntryLocalServiceTest.testCopyFileEntry

java.lang.AssertionError: Orphan ResourcePermission after the deletion of com.liferay.expando.kernel.model.ExpandoColumn: {"mvccVersion": 0, "ctCollectionId": 0, "columnId": 72685, "companyId": 20100, "tableId": 72684, "name": "ExpandoAttributeName", "type": 15, "defaultData": "", "typeSettings": ""} with backtraceInfo java.lang.Exception
  at com.liferay.portal.kernel.test.rule.OrphanDetectionTestRule$OrphanDetectionSessionWrapper._record(OrphanDetectionTestRule.java:147)
  at com.liferay.portal.kernel.test.rule.OrphanDetectionTestRule$OrphanDetectionSessionWrapper.delete(OrphanDetectionTestRule.java:122)
  at com.liferay.portlet.expando.service.persistence.impl.ExpandoColumnPersistenceImpl.removeImpl(ExpandoColumnPersistenceImpl.java:1939)
  at com.liferay.portlet.expando.service.persistence.impl.ExpandoColumnPersistenceImpl.removeImpl(ExpandoColumnPersistenceImpl.java:77)
  at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.remove(BasePersistenceImpl.java:666)
  at com.liferay.portlet.expando.service.persistence.impl.ExpandoColumnPersistenceImpl.removeByTableId(ExpandoColumnPersistenceImpl.java:869)
  at com.liferay.portlet.expando.service.impl.ExpandoTableLocalServiceImpl.deleteTable(ExpandoTableLocalServiceImpl.java:98)
```

Let me know if you need more information or if you prefer split this PR, with the test changes in a separated one.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@jorgediaz-lr Code conflicts, please rebase and resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

I have sent it again here: https://github.com/jorgediaz-lr/liferay-portal/pull/431

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

I have rebased and sent it again in https://github.com/liferay-core-infra/liferay-portal/pull/299

**Pull request closed without merging**
