### PR TITLE
[Spring Beans] LPS-200292 Merge IdenticalPhoneNumberFormatImpl into Util and move to portal-impl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(10/31 8/10)

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(11/1 9:03)

**Comment by zhangyan0701** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:stop

**Pull request closed without merging**
