### PR TITLE
LPD-25518 Adapt tests using hard-coded test password in Gogo Shell component

### PR DESCRIPTION
**Pull request by MrJohn1911**
Tested here: https://github.com/MrJohn1911/liferay-portal/pull/84

The tests did't fail / didn't had any unique failure.

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:core-functional

**Comment by MrJohn1911** [comment]
ci:report:2568267420

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
