### PR TITLE
[MessageBus] LPS-195190 Remove MessageBusUtil usages in UserLocalService

### PR DESCRIPTION
**Pull request by haydenzheng314**
Ticket: https://liferay.atlassian.net/browse/LPS-195190
Thanks.

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:users

**Comment by dantewang** [comment]
ci:test:um

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140286

**Pull request closed without merging**
