### PR TITLE
[Urgent][Security Bugs]LPD-34574 follow up to upgrade all the spring dependencies

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,
This is the follow up PR as BChan requested at https://github.com/brianchandotcom/liferay-portal/pull/153595#issuecomment-2308479885.
I upgrade all the spring related dependencies to 5.3.39, including the 3 patched spring dependencies.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:report:72150494

**Comment by jeffwu0724** [comment]
ci:report:72150494

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/153675

**Pull request closed without merging**
