### PR TITLE
[Company WebId Log][LXC] LPS-181446

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, @tinatian, the previous pr is https://github.com/liferay-core-infra/liferay-portal/pull/4655.

I placed the log context register logic to CompanyWebIdConsoleAppender.Builder#build(). Because if placing the logic in the append(), it means CompanyWebIdConsoleAppender is printing log and it has passed once get LogContexts check(Log4jLogContextLogWrapper#_populateThreadContext).

### CODE REVIEW

**Comment by Kvale1733** [comment]
Build service changes detected
```
     [echo] diff --git a/portal-kernel/src/com/liferay/portal/kernel/service/CompanyLocalServiceWrapper.java b/portal-kernel/src/com/liferay/portal/kernel/service/CompanyLocalServiceWrapper.java
     [echo] index 154a67c572131..68e5a039d5249 100644
     [echo] --- a/portal-kernel/src/com/liferay/portal/kernel/service/CompanyLocalServiceWrapper.java
     [echo] +++ b/portal-kernel/src/com/liferay/portal/kernel/service/CompanyLocalServiceWrapper.java
     [echo] @@ -584,7 +584,7 @@ public class CompanyLocalServiceWrapper
     [echo]  	 * @return the company's webId
     [echo]  	 */
     [echo]  	@Override
     [echo] -	public java.lang.String getWebId(long companyId) {
     [echo] +	public String getWebId(long companyId) {
     [echo]  		return _companyLocalService.getWebId(companyId);
     [echo]  	}
     [echo]  
[stopwatch] [run.batch.test.action: 24:14.499 sec]
     [echo] .
     [echo] 
     [echo] Detected build services changes. See above build services log for more
     [echo] information. Make sure to commit in all build services results.
 ```
 [Log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-33/test-portal-acceptance-pullrequest(master)/3704/service-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by yuhai** [comment]
@Kvale1733, I rerun build-service and push the latest change. I will trigger the ci test again. Thanks.

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:stop

**Comment by yuhai** [comment]
@dantewang, @tinatian, I just removed the attribute "enabled". If using our custom appender, it will register log context by default.

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@yuhai No regressions found.

**Comment by tinatian** [comment]
@yuhai Please do not do this https://github.com/liferay-core-infra/liferay-portal/pull/4666/commits/882560888bb4e9b8cb0037ac94b1911e6ec28b0f. By adding a new api only used by one is not good, also you have to suffer all the AOP chain invoking service.

Please move PortalInstances to portal-kernel instead.

**Pull request closed without merging**
