### PR TITLE
[TS] LPS-157252

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-157252

Forwarded from https://github.com/liferay-usm/liferay-portal/pull/628 after initial review from @Drewbrokke

Original message:

> In the scenario where the user is requesting their default language, the portal and user default language is the same, but the current virtualHost's default language is different, then the portal will still provide the URL without any language code.  This is because the portal is not taking into account the virtualHost's default language when (not) setting the i18nPath to the requested language.  Further, having a virtualHost default language works against the `LOCALE_PREPEND_FRIENDLY_URL_STYLE` 3 (which is the default value) because now the specified virtualHost (without languageId in the URL) only points to one language, instead of any available language.
> 
> With my changes, the portal now considers if the virtualHost has a default language, and will include a `i18nPath` value if the requested language is different.
> 
> Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by dantewang** [comment]
@GinsonRen Please run a diff on login. Thanks!

**Comment by GinsonRen** [comment]
@dantewang Here is the diff result:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | a173a7b | 52242 | 268 | -
PR-563 | - | 51934 | 262 | -0.59%

**Comment by catarineaguiar** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
@ChrisKian possible regression:

`UpdateLanguageActionTest`
```
[exec] com.liferay.portal.action.test.UpdateLanguageActionTest > testGetRedirectWithFriendlyURLWithVirtualHost FAILED
     [exec]     org.junit.ComparisonFailure: expected:<http://test.com/[]-/assettarget?queryS...> but was:<http://test.com/[de/]-/assettarget?queryS...>
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:117)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
     [exec]     	at com.liferay.portal.action.test.UpdateLanguageActionTest.testGetRedirectWithFriendlyURLWithVirtualHost(UpdateLanguageActionTest.java:202)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-07/test-1-35/test-portal-acceptance-pullrequest(master)/2012/modules-integration-mysql57-jdk8/3/3/jenkins-console.txt.gz?authuser=0)

**Comment by ChrisKian** [comment]
Hi @catarineaguiar,
The error shown is a true regression, so I've included [an additional commit](https://github.com/liferay-core-infra/liferay-portal/pull/1070/commits/3c487b1591415757463d836847b2f2c41b16ee4e) which should resolve the issue.  Thanks!

**Comment by crodriguezy** [comment]
Hi @ChrisKian , I'm not sure you read my [previous comment](https://github.com/liferay-core-infra/liferay-portal/pull/1070#issuecomment-1181656145). Let me know if I need to create a new LPS with the new reproduction steps.
Thanks

**Comment by ChrisKian** [comment]
Hey @crodriguezy,
Since this pull had a regression (fixed now), it will still take some time for it to be re-tested and reviewed.  Because of this, and because LPS-154862 should be merged soon, I will close this PR, wait for LPS-154862 to be merged, then resolve both scenarios in one new PR.

Please let me know if you have any questions, thanks!

**Comment by ChrisKian** [comment]
Follow-up sent: https://github.com/liferay-core-infra/liferay-portal/pull/1135

**Pull request closed without merging**
