### PR TITLE
[Remove unused @Reference var] LPS-165149

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove the unused @reference variable in the module `headless`. Thanks!

https://issues.liferay.com/browse/LPS-165149

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by catarineaguiar** [comment]
@JanisZhang regression found:

```
   [exec] com.liferay.headless.admin.user.resource.v1_0.test.RoleResourceTest > testClientSerDesToDTO STARTED
[beanshell] 2022-10-11 04:48:17.134 ERROR [fileinstall-directory-watcher][DirectoryWatcher:1176] Unable to start bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.commerce.product.service.jar
[beanshell] org.osgi.framework.BundleException: Could not resolve module: com.liferay.commerce.product.service [925]
[beanshell]   Unresolved requirement: Import-Package: com.liferay.commerce.service.impl
[beanshell] 
[beanshell] 	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundle(DirectoryWatcher.java:1159) [bundleFile:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundles(DirectoryWatcher.java:1192) [bundleFile:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startAllBundles(DirectoryWatcher.java:1133) [bundleFile:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:1044) [bundleFile:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:222) [bundleFile:?]
     [exec] 
     [exec] com.liferay.headless.admin.user.resource.v1_0.test.RoleResourceTest > testClientSerDesToDTO FAILED
     [exec]     java.lang.AssertionError: Thread Thread[fileinstall-directory-watcher,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.file.install.internal.DirectoryWatcher, message=Unable to start bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.commerce.product.service.jar
     [exec]     java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.file.install.internal.DirectoryWatcher, message=Unable to start bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.commerce.product.service.jar
     [exec]     	at com.liferay.portal.test.rule.LogAssertionTestRule$LogAppender.append(LogAssertionTestRule.java:330)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-39/test-portal-acceptance-pullrequest(master)/844/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
Hi @catarineaguiar, I triggered `ci:test:relevant` again, Could you please double-check it?  Thanks.

cc/ @dantewang

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:test:headless

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/124583

cc @shuyangzhou @tinatian

**Pull request closed without merging**
