### PR TITLE
[Components with more than 1 service] LPS-195487 Refactor CompanyModelListener component

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-195487](https://liferay.atlassian.net/browse/LPS-195487)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@RenanUmV No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
