### PR TITLE
LPS-185105 Remove IndexStatusManagerInternalConfiguration

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
pushed to fix sf

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by julschong** [comment]
rebased to resolve conflict in breaking change

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by julschong** [comment]
@vicnate5 Hi Victor, this pull is the one removing suppressIndexReadOnly, Summer found no regression before the rebase. Are there any other tests we should be looking out for?

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by julschong** [comment]
rebase for conflict in breaking change

**Comment by julschong** [comment]
added additional commit message here https://github.com/liferay-core-infra/liferay-portal/pull/4784/commits/c0732742fe76f25760286a9c14179bbdefe02728

**Comment by julschong** [comment]
@vicnate5 could you please help take an extra look on these test results?

**Comment by vicnate5** [comment]
@julschong I double checked the results, and I don't see any issues.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136784

**Pull request closed without merging**
