### PR TITLE
[Remove unused field] LPS-199401 Remove unused reference field in calsses CPDefinitionSpecificationOptionValueInfoItemFormProvider, UpdateCollectionDisplayConfigMVCActionCommand and UpdateItemConfigMVCActionCommand

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(10/24 8:21)

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(10/25 9:56)

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142697

**Pull request closed without merging**
