### PR TITLE
[TS Bug] LPS-159737

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian See https://issues.liferay.com/browse/LPS-159737 comment for detailed background.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 @catarineaguiar Could you please review the test results when they finish? Also trigger any other tests if you think necessary. Thanks!

**Comment by catarineaguiar** [comment]
@dantewang no regressions found.

**Comment by tinatian** [comment]
@dantewang Your comment on the ticket said, we made this change because HeaderFilter may be invoked twice, while you only changed logic when session is NOT new, why we do not need to do the same thing when session is new?

Tina

**Comment by dantewang** [comment]
@tinatian We should only need the fix on the logic when the filter actually tries to set/update the Cache-Control and Expires headers; the new session conditions serve as shortcuts, when they are met, the filter doesn't set/update these headers.

**Comment by dantewang** [comment]
@tinatian Oh, do you mean the `httpServletResponse.addHeader(name, value);` for headers that are not "Cache-Control" or "Expires"?

**Comment by binhtran92** [comment]
Hi @dantewang @tinatian, any update on this PR?

**Comment by dantewang** [comment]
@binhtran92 I think @tinatian will ask in tomorrow's meeting with the PM about whether we can get rid of speed-filter-web.xml at all, so that there will not be 2 `HeaderFilter` invocations in the request processing.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/1425

**Pull request closed without merging**
