### PR TITLE
LPS-183342 resend removing ServiceContextFactory.getInstance(String, UploadPortletRequest)

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

Resend the reverted commit https://github.com/liferay-core-infra/liferay-portal/pull/4434/commits/b2ac8c0415e9586b7cb4bd5bed1376e9839cf7b9.
The regression mentioned in https://liferay.slack.com/archives/CLA7D1CNL/p1684373970567589 is not related to my change. It is only happened while releasing, and not exists in the master. The method I removed will impact **seven modules**, which are 

- document-library-web
- dynamic-data-mapping-form-web
- dynamic-data-mapping-web
- journal-web
- portal-workflow-kaleo-forms-web
- saml-web
- template-web
Therefore, the release team has to republish these modules to make them work. 
Thanks for checking!

cc: @vicnate5 @Kvale1733

### CODE REVIEW

**Comment by jeffwu0724** [comment]
Hey @Kvale1733 

Could you please help me trigger the necessary testes, please?
Thanks!

**Comment by Kvale1733** [comment]
ci:test:saml

**Comment by Kvale1733** [comment]
ci:test:kaleo-forms

**Comment by Kvale1733** [comment]
ci:test:forms

**Comment by Kvale1733** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
ci:test:document

**Comment by Kvale1733** [comment]
ci:test:lima

**Comment by zhangyan0701** [comment]
No regressions found.

**Pull request closed without merging**
