### PR TITLE
Lpd 25508

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:db-partition

**Comment by tinatian** [comment]
ci:test:core-functional

**Comment by tinatian** [comment]
ci:report:31325998

**Comment by tinatian** [comment]
ci:report:31315418

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:db-partition

**Comment by shuyangzhou** [comment]
ci:test:core-functional

**Comment by shuyangzhou** [comment]
ci:report:31532343

**Comment by shuyangzhou** [comment]
ci:report:31533644

**Comment by tinatian** [comment]
ci:report:31572905

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 31572905.
> 
> Job Link: [generate-testray-csv](https://test-1-33.liferay.com/job/generate-testray-csv/288/)
> 
> Testray CSV Link: [testray-results-31572905.csv](https://test-1-33.liferay.com/userContent/jobs/generate-testray-csv/builds/288/testray-results-31572905.csv)

Unique failures in report are not unique to this pull

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 31532343.
> 
> Job Link: [generate-testray-csv](https://test-1-28.liferay.com/job/generate-testray-csv/454/)
> 
> Testray CSV Link: [testray-results-31532343.csv](https://test-1-28.liferay.com/userContent/jobs/generate-testray-csv/builds/454/testray-results-31532343.csv)

Unique failures in report are not unique to this pull

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/154876

**Pull request closed without merging**
