### PR TITLE
[Convert method reference]Lps 163778

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-163778

Resend according to the comment in https://github.com/brianchandotcom/liferay-portal/pull/124198#issuecomment-1270315848

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Comment by catarineaguiar** [comment]
@slnn all functional tests failed on portal startup:

```
 [exec]     LIFERAY_ERROR: bundle com.liferay.marketplace.store.web:7.0.27 (401)[com.liferay.marketplace.store.web.internal.portlet.MarketplacePurchasedPortlet(6852)] : findField: Suitable but non-accessible field _portal in class com.liferay.marketplace.store.web.internal.portlet.MarketplaceStorePortlet, subclass of component class com.liferay.marketplace.store.web.internal.portlet.MarketplacePurchasedPortlet
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-30/test-portal-acceptance-pullrequest(master)/4942/functional-smoke-wildfly180-mariadb104-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
Thanks, @catarineaguiar !

I fixed it and force-pushed it to this pull, could you help to rescan test results when they are finished?

Thanks
Lily

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
@slnn Portal startup failed with error:
```
[beanshell] 2022-10-11 07:33:52.083 ERROR [fileinstall-directory-watcher][DirectoryWatcher:1176] Unable to start bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.commerce.product.service.jar
[beanshell] org.osgi.framework.BundleException: Could not resolve module: com.liferay.commerce.product.service [1087]
[beanshell]   Unresolved requirement: Import-Package: com.liferay.commerce.service.impl
[beanshell] 
[beanshell] 	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundle(DirectoryWatcher.java:1159) [bundleFile:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundles(DirectoryWatcher.java:1192) [bundleFile:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startAllBundles(DirectoryWatcher.java:1133) [bundleFile:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:1044) [bundleFile:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:222) [bundleFile:?]
```

Full console log:
https://testray.liferay.com/reports/production/logs/2022-10/test-1-39/test-portal-acceptance-pullrequest(master)/872/functional-smoke-tomcat90-mysql57-jdk8_stable/0/0/jenkins-console.txt.gz?authuser=0

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
> @slnn Portal startup failed with error:
> 
> ```
> [beanshell] 2022-10-11 07:33:52.083 ERROR [fileinstall-directory-watcher][DirectoryWatcher:1176] Unable to start bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.commerce.product.service.jar
> [beanshell] org.osgi.framework.BundleException: Could not resolve module: com.liferay.commerce.product.service [1087]
> [beanshell]   Unresolved requirement: Import-Package: com.liferay.commerce.service.impl
> [beanshell] 
> [beanshell] 	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
> [beanshell] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428) ~[org.eclipse.osgi.jar:?]
> [beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundle(DirectoryWatcher.java:1159) [bundleFile:?]
> [beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundles(DirectoryWatcher.java:1192) [bundleFile:?]
> [beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startAllBundles(DirectoryWatcher.java:1133) [bundleFile:?]
> [beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:1044) [bundleFile:?]
> [beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:222) [bundleFile:?]
> ```
> 
> Full console log: https://testray.liferay.com/reports/production/logs/2022-10/test-1-39/test-portal-acceptance-pullrequest(master)/872/functional-smoke-tomcat90-mysql57-jdk8_stable/0/0/jenkins-console.txt.gz?authuser=0

Hi @zhangyan0701 

I do not reproduce this issue locally, I just force-pushed to this pull after rebasing the code with today's master, with no logic change.

I rerun the relevant tests, please help to double-check the test results when they are finished.

Thanks
Lily

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@slnn I see you did a lot of changes to remove the `RemoteMVCPortlet`. Could you simplify these changes into

1. Remove any method that is completely hidden by `MarketplaceStorePortlet`'s overriding from `RemoteMVCPortlet`
2. Merge these 2 classes into 1
3. Convert method ref to field ref

**Comment by slnn** [comment]
> @slnn I see you did a lot of changes to remove the `RemoteMVCPortlet`. Could you simplify these changes into
> 
> 1. Remove any method that is completely hidden by `MarketplaceStorePortlet`'s overriding from `RemoteMVCPortlet`
> 2. Merge these 2 classes into 1
> 3. Convert method ref to field ref


Based on this comment, resend in https://github.com/liferay-core-infra/liferay-portal/pull/1999

**Pull request closed without merging**
