### PR TITLE
LPD-41335 Centralize all language override functionality into LanguageResourcesExtender

### PR DESCRIPTION
**Pull request by kevhlee**
__Tickets:__
- <https://liferay.atlassian.net/browse/LPD-35718>
- <https://liferay.atlassian.net/browse/LPD-41335>

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@kevhlee The compile error is real.

**Comment by kevhlee** [comment]
@dantewang, I'm currently working on the compiler error.

**Comment by kevhlee** [comment]
New pull request sent here: <https://github.com/liferay-core-infra/liferay-portal/pull/7749>.

**Pull request closed without merging**
