### PR TITLE
LPS-149331 Remove unused packages in analytics modules

### PR DESCRIPTION
**Pull request by julschong**
@tinatian
Hi Tina,

Below is the list of packagesto remove from Marcellus:
- analytics-api
- analytics-client-osgi-test
- analytics-client-osgi-demo
- analytics-client-osgi
- analytics-client-impl
- analytics-data-binding-impl

I pretested it on my repo https://github.com/julschong/liferay-portal/pull/252

### CODE REVIEW

**Comment by tinatian** [comment]
@julschong I still see `modules/modules.properties:bundle.version[com.liferay.analytics.api]=5.0.5`, please fix.

**Comment by tinatian** [comment]
@julschong Also, please separate the commit for each bundle, for example remove "com.liferay.analytics.api" in one commit, remove "com.liferay.analytics.client.osgi" in another commit. 
This way, when we want something back, we can revert corresponding commit.

Thanks.
Tina.

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
> @julschong Also, please separate the commit for each bundle, for example remove "com.liferay.analytics.api" in one commit, remove "com.liferay.analytics.client.osgi" in another commit. This way, when we want something back, we can revert corresponding commit.
> 
> Thanks. Tina.

I moved modules.properties into each package removal individually

**Comment by julschong** [comment]
@kyle-miho Hi Kyle,
Could you please help me check the test results?
Thank you!

**Comment by kyle-miho** [comment]
@julschong failures are unrelated

**Comment by julschong** [comment]
Hi Tina @tinatian, could you please help review this PR?
Thank you!

**Comment by tinatian** [comment]
@julschong If you search "com.liferay.analytics.api", you would see it is used in artifact.properties, please run `gw -b releng.gradle cleanReleng` in modules to get rid of it.

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
pushed auto cleanReleng

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by kyle-miho** [comment]
@julschong failures are unrelated

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@julschong Code looks good to me, waiting for test result scan.

Tina.

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Tina.

**Comment by kyle-miho** [comment]
@tinatian @julschong pr is good to go

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go. The removed bundles had been confirmed with @marcellustavares.


Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
