### PR TITLE
[Convert method references]Lps 163568

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-163568

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
@slnn possible regression:

```
 [exec] com.liferay.portal.verify.test.VerifyResourcePermissionsTest > testVerify FAILED
     [exec]     java.lang.Exception: Caught an unclosed exception
     [exec]     	at com.liferay.portal.verify.test.util.BaseVerifyProcessTestCase$DataSourceInvocationHandler.invoke(BaseVerifyProcessTestCase.java:120)
     [exec]     	at com.sun.proxy.$Proxy1377.getConnection(Unknown Source)
     [exec]     	at com.liferay.portal.scheduler.quartz.internal.QuartzConnectionProvider.getConnection(QuartzConnectionProvider.java:39)
     [exec]     	at org.quartz.utils.DBConnectionManager.getConnection(DBConnectionManager.java:108)
     [exec]     	at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:764)
     [exec]     	at org.quartz.impl.jdbcjobstore.JobStoreTX.getNonManagedTXConnection(JobStoreTX.java:71)
     [exec]     	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3795)
     [exec]     	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2751)
     [exec]     	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:264)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-39/test-portal-acceptance-pullrequest(master)/895/modules-integration-mysql57-jdk8/0/13/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
> VerifyResourcePermissionsTest

Thank you @catarineaguiar for catching this, but I run the failed test VerifyResourcePermissionsTest locally, but it passed please see the output of the test: https://gist.github.com/slnn/0c1fdf244d5f94aa8cb0414d7721866c

I just rebase the code with the head of master and rerun the test, please help to scan test results when they are finished.

By the way, I got "Internal Server Error
" when I visited the full log https://testray.liferay.com/reports/production/logs/2022-10/test-1-39/test-portal-acceptance-pullrequest(master)/895/modules-integration-mysql57-jdk8/0/13/jenkins-console.txt.gz?authuser=0

Thanks
Lily

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125314

**Pull request closed without merging**
