### PR TITLE
[Method References 2] LPS-176118 Convert method references to serviceTracker in class ThemeContributorTopHeadDynamicInclude

### PR DESCRIPTION
**Pull request by W2jx**
Hi @dantewang , I have resent it.
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3566

### CODE REVIEW

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(3/10 10:13)

**Comment by W2jx** [comment]
no conflicts(3/14 15:20)

**Comment by W2jx** [comment]
no conflicts(3/17 14:36)

**Comment by W2jx** [comment]
no conflicts(3/20 8:52)

**Comment by W2jx** [comment]
no conflicts(3/21 9:45)

**Pull request closed without merging**
