### PR TITLE
remove properties: module.framework.properties.ds.*

### PR DESCRIPTION
**Pull request by W2jx**
@tinatian @dantewang

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
This PR is to check whether we can remove the `module.framework.properties.ds.*` properties which were added for slow machines or CI. We want to know whether removing them can cause CI-only errors.

@zhangyan0701 Could you review the test results? Especially pay attention to errors during portal startup. Thanks!
@catarineaguiar I triggered 2 extra ci-test runs and they may not finish by the end of our day. Could you please review those when they finish? Thanks!

**Comment by catarineaguiar** [comment]
@W2jx @dantewang I didn't find regressions on default runs.

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@W2jx @dantewang We still need this for debug. Please patch org.apache.felix.scr and change the default time out to a large number and remove the property setting here.

Please resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
