### PR TITLE
LPS-144170 Move im4java.jar and monte-cc.jar to modules

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:document

**Comment by rafaprax** [comment]
Hey @vicnate5, Can you help scan the test results? Thanks!

**Comment by guilhermedcamacho** [comment]
Hey @vicnate5 , the error **LocalFile.DMFileEntry#CanReviewDocumentWhenDateIsDisabled** doesn't seem to be related, I reproduced the this error locally with and without our changes.

**Comment by vicnate5** [comment]
@rafaprax @guilhermedcamacho Yea, the test failure is random and not related. I do not have any other failures to check here :)

**Comment by guilhermedcamacho** [comment]
Thank you @vicnate5 :smiley: 

@shuyangzhou , this PR is ready for your review. We appended two smalls commits from the one you [reviewed](https://github.com/liferay-core-infra/liferay-portal/pull/197) yesterday. Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/112363

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
