### PR TITLE
LPS-180411 Adding support for BINARY_DOUBLE in Hibernate (2nd try)

### PR DESCRIPTION
**Pull request by marcogalluzzi**
Hi, I'm resending the previous PR #6329 with the addition of an appropriate test.

About the query in the test: I couldn't simplify it more. It seems that the bug only occurs when referencing a BINARY_DOUBLE value in an inner query.

### CODE REVIEW

**Comment by yuhai** [comment]
Hi @marcogalluzzi, I have a simple test way to cover the fix. Refer to the part of `DB2DialectTest`. 
```
     @Test
	public void testHibernateTypeNameBinaryDoubleExisted() {
		SessionFactory sessionFactory = ReflectionTestUtil.getFieldValue(
			_ratingsEntryPersistence, "_sessionFactory");

		Dialect dialect = ReflectionTestUtil.getFieldValue(
			sessionFactory.getDialect(), "_dialect");

		Assert.assertEquals(
			StandardBasicTypes.DOUBLE.getName(),
			dialect.getHibernateTypeName(101));
	}
```

Please push force the change and let me know if you have further concerns.

Thanks,
Hai

**Comment by marcogalluzzi** [comment]
Hi @yuhai I've rewritten the test as you recommended. Now it's much simpler! Just a littler change: I'm using the User persistence because I think this entity is less prone to changes.

**Review by yuhai — APPROVED** [review]
@dantewang, the pr looks good to me.

**Review by dantewang — APPROVED** [review]

**Comment by yuhai** [comment]
Hi @marcogalluzz, please fix the bnd conflict and push force the change.

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
@marcogalluzzi @yuhai I've rebased and push-force'd

**Comment by marcogalluzzi** [comment]
Hi @tinatian did you have a chance to look into this PR ?

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/147169

**Pull request closed without merging**
