### PR TITLE
[Remove Stream/Optional usage] Phase 1 LPS-172794 remove_stream_in_portal_tools_rest_builder

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Dante,

Resent from:https://github.com/liferay-core-infra/liferay-portal/pull/3977
As "rest-client cannot have any dependencies except Java 8. *-client is meant to be used outside of the portal. To keep things simple, we don't want any dependencies except for Java 8.", I changed back to use for loop instead of TransformUtil.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:headless

**Comment by dantewang** [comment]
@jeffwu0724 Please make sure the code in the ftl files has correct format and resend, thanks!

**Comment by jeffwu0724** [comment]
Hi @dantewang , may I ask about what is the best way to make sure the format in the ftl is correct, please?
What I do is copy the format from the generated java file after SF, and fit the ftl based on the generated format.
Thanks!

**Comment by dantewang** [comment]
@jeffwu0724 The problem is that IntelliJ doesn't keep the original format (indent etc.) when pasting. We don't need to format everything, we just need to make the code follow the basic formatting rules manually.

**Pull request closed without merging**
