### PR TITLE
[Remove Blocking Usages] LPS-196123 Move class DLPreviewableProcessor to modules/app/document-library-preview-api

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5817

Changes:

1. document breaking change on the commit where moved the classes
2. only modify file liferay-hook_7_4_0.dtd
3. rename classes

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:document

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
no conflicts(10/24 8:21)

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(10/25 9:56)

**Comment by lilylcl** [comment]
ci:test:stable

**Comment by lilylcl** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(10/26 8:28)

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5918

**Pull request closed without merging**
