### PR TITLE
remove_deprecated_for_portal_kernel_part_Two

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

I have removed deprecated for portal-kernel, then they are
"portal-kernel/src/com/liferay/layouts/admin/kernel/model/LayoutTypePortletConstants.java",
"portal-kernel/src/com/liferay/portal/kernel/backgroundtask/",
"BeanProperties.java", "BeanPropertiesUtil.java", "BeanPropertiesImpl.java",
"portal-kernel/src/com/liferay/portal/kernel/cache",
"portal-kernel/src/com/liferay/portal/kernel/change/tracking/CTCollectionThreadLocal.java",
"portal-kernel/src/com/liferay/portal/kernel/configuration/Filter.java",
"portal-kernel/src/com/liferay/portal/kernel/dao/db".

Thanks for checking! Also see https://github.com/jeffwu0724/liferay-portal/pull/37.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by tinatian** [comment]
@jeffwu0724 I found this, please remove it and update your pull.

`find-security-bugs-false-positives.txt:com/liferay/portal/kernel/backgroundtask/BackgroundTaskConstants.getStatusCssClass(I)Ljava/lang/String;:SAFE
find-security-bugs-false-positives.txt:com/liferay/portal/kernel/backgroundtask/BackgroundTaskConstants.getStatusLabel(I)Ljava/lang/String;:SAFE
`

Tina

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by kyle-miho** [comment]
failures in previous run were unrelated, waiting for most recent results

**Comment by kyle-miho** [comment]
@jeffwu0724 failures are unrelated

**Comment by tinatian** [comment]
@jeffwu0724 This method should also be removed: https://github.com/liferay-core-infra/liferay-portal/blob/bd0e60c4cee6e54f228521801f98d6dec85ac9b6/portal-impl/src/com/liferay/portal/dao/db/BaseDB.java#L137, as you remove its interface method.

Tina.

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:stop

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@jeffwu0724 Code looks good to me, wait for QA to scan test results.

Thanks.
Tina.

**Comment by kyle-miho** [comment]
@jeffwu0724 
com.liferay.portal.kernel.util                     MAJOR      31.0.0     31.0.0     32.0.0     VERSION INCREASE REQUIRED
     [exec] 	-   class      com.liferay.portal.kernel.util.SimplePojoClp
     Semantic Versioning bump needed for this package, everything else should be unrelated

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@kyle-miho Please help me scan test results.

Thanks.
Tina

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result again, please?

Thanks
Jeff

**Comment by kyle-miho** [comment]
failures are unrelated, CI build crashed for some reason, re-running

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
@jeffwu0724 pr is good to go

**Comment by jeffwu0724** [comment]
Hey @tinatian , PR has been checked by Kyle and is good to go

**Comment by tinatian** [comment]
@shuyangzhou This is good to go.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
