### PR TITLE
LPS-195954 Simplify CacheKeyGenerator logic and move to portal-impl

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
pushed to fix sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
re-running relevant to check possible flaky error

**Comment by zhangyan0701** [comment]
There are some errors that related to CSS when open home page after portal startup:

Examples:
```
2023-09-26 19:29:55.124 ERROR [http-nio-8080-exec-10][DynamicCSSFilter:171] Unable to replace tokens in CSS /o/commerce-frontend-js/styles/main.css
java.io.FileNotFoundException: /opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.80/work/Catalina/localhost/ROOT/css/httphttp___o_classic-theme_css_main.css_o_classic-theme_css_clay.css_o_commerce-frontend-js_styles_main.csshttp__o_frontend-js-loader-modules-extender_loader.jsjsvgl2bMsA_h7Ey6XB35yoUaddap-iBneP7NPOHfK7k_47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU__E_CTYPE (File name too long)
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-09/test-1-32/test-portal-acceptance-pullrequest(master)/2239/functional-smoke-tomcat90-db2115-jdk8/0/0/liferay-log.txt.gz?authuser=0

```
2023-09-26 19:29:47.270 ERROR [http-nio-8080-exec-6][DynamicCSSFilter:171] Unable to replace tokens in CSS /o/analytics-reports-web/css/main.css
java.io.FileNotFoundException: /opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.80/work/Catalina/localhost/ROOT/css/http__o_analytics-reports-web_css_main.csshttp__o_product-navigation-applications-menu-web_css_ApplicationsMenu.csshttp__o_analytics-reports-web_css_analytics-reports-app.css47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU_47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU__E_CTYPE (File name too long)
```
```
2023-09-26 19:33:06.524 ERROR [http-nio-8080-exec-4][DynamicCSSFilter:171] Unable to replace tokens in CSS /o/frontend-editor-ckeditor-web/ckeditor/plugins/codemirror/vendors/vendors.css
java.io.FileNotFoundException: /opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.80/work/Catalina/localhost/ROOT/css/http__o_frontend-editor-ckeditor-web_ckeditor_plugins_codemirror_skins_default.csshttp__o_frontend-editor-ckeditor-web_ckeditor_plugins_codemirror_vendors_vendors.css47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU_47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU__E_CTYPE (File name too long)
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-09/test-1-32/test-portal-acceptance-pullrequest(master)/2239/functional-smoke-tomcat90-hypersonic20-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
