### PR TITLE
LPS-188559 Remove ReferencePolicyOption GREEDY from references since the references have already a target

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-188559

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:document

**Comment by rafaprax** [comment]
ci:stop

**Pull request closed without merging**
