### PR TITLE
[Remove Stream/Optional usage] LPS-170766 dynamic-data-mapping | PART 3

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:forms

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127703

@JanisZhang Since I sent this one first, I used "Part 2" for this (seems the ticket is still Part 2).

**Comment by dantewang** [comment]
@JanisZhang Please remember to update the ticket if we change Part X for a pull, thanks!

**Pull request closed without merging**
