### PR TITLE
[System Properties] LPS-155682 Remove module.framework.properties.ds.*

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I don't add portal PropsValues entries for these properties. The reason we removed these proeprties is to reduce the number of properties that will be moved to system.properties, and I think if we add portal PropsValues entries for these properties, it might increase the complexity of moving the properties to system.properties

details: https://github.com/liferay-core-infra/liferay-portal/pull/1105

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701, Could you please help me scan test results when you free ? Thanks!

**Review by dantewang — APPROVED** [review]
@tinatian Code looks good to me. This PR does not depend on other PRs so it can be sent independently.

**Comment by tinatian** [comment]
@W2jx Code looks good to me, wait for QA to scan test results.

Tina.

**Comment by dantewang** [comment]
ci:test:acceptance

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
