### PR TITLE
[CLDR] LPD-18647 Fix com.liferay.portal.kernel.util.LocaleUtilTest

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:stable

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:report:2558972829

**Comment by julschong** [comment]
@MrJohn1911 Hi Joao, did you test this locally?
Test keeps failing for locally because `@NewEnv` seems to not work for me in portal-kernel.

**Comment by julschong** [comment]
Closing this pull, I will resubmit

**Pull request closed without merging**
