### PR TITLE
[Move Expando]Lps 191596

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-191596

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:blogs:norebase

**Comment by Kvale1733** [comment]
ci:test:comment:norebase

**Comment by Kvale1733** [comment]
ci:test:content-page-review:norebase

**Comment by slnn** [comment]
Rebase and update this pull, no logic change.

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:comments

**Comment by slnn** [comment]
ci:test:content-page-review

**Comment by slnn** [comment]
ci:test:blogs

**Comment by slnn** [comment]
Close this pull and try a new way

cc @dantewang

**Comment by slnn** [comment]
ci:stop

**Pull request closed without merging**
