### PR TITLE
LPS-173655 fix Provision virtual instances via configuration not working

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-173655](https://issues.liferay.com/browse/LPS-173655)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
@rafaprax

**Comment by Kvale1733** [comment]
@RenanUmV Regression found in
PortalInstancesConfigurationFactoryTest
```
 [exec] com.liferay.portal.instances.internal.configuration.test.PortalInstancesConfigurationFactoryTest > test FAILED
     [exec]     java.lang.AssertionError
     [exec]     	at org.junit.Assert.fail(Assert.java:87)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
     [exec]     	at org.junit.Assert.assertNotNull(Assert.java:713)
     [exec]     	at org.junit.Assert.assertNotNull(Assert.java:723)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-26/test-portal-acceptance-pullrequest(master)/7266/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:stable

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:stable

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by catarineaguiar** [comment]
@RenanUmV I tested locally and could reproduce the bug, can you double check if it fixes the issue?

**Comment by RenanUmV** [comment]
Hey @tinatian , can you review this PR?

**Comment by tinatian** [comment]
@RenanUmV As we discussed, please resend.

Thanks.
Tina

**Pull request closed without merging**
