### PR TITLE
[Remove unused field] LPS-200302 Remove unused reference field in calsses RulesEngineImpl, SamlIdpSpSessionLocalServiceImpl and ObjectEntryExtensionProvider

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(11/1 9:03)

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143056

**Pull request closed without merging**
