### PR TITLE
Lpd 41167

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:object

**Comment by shuyangzhou** [comment]
@victorhcunha please rerun the same check, you should see the number is lower than before my changes. Also check CPU -> Database section, a SQL select to ObjectDefinition table is removed.

CC @pedro-oliveira446

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
Here are the new results:

Portal Version CE| Open count of Prepared Statement | Count of Prepared Statement Query
-- | -- | --
Master Baseline c163f5a5 | 148 | 222
Old LPD-41167 v3 https://github.com/liferay-core-infra/liferay-portal/pull/7684 | 134 | 201
LPD-41167 v3 https://github.com/liferay-core-infra/liferay-portal/pull/7695 | 138 | 207
**Current LPD-41167**| **132** | **198**

More details and the file results are available in the [spreadsheet](https://docs.google.com/spreadsheets/d/1WC5NZgLfrZ7UK-M-9WY6Bl2EWG79xfn8T-ybQD3SRAs/edit?gid=227600943#gid=227600943).

**Comment by victorhcunha** [comment]
About the CPU -> Database section

I see one SQL select for the ObjectDefinition table in both PRs (the current one and the https://github.com/liferay-core-infra/liferay-portal/pull/7695):
```
select objectdefi0_.objectDefinitionId as objectde1_1_, objectdefi0_.mvccVersion as mvccvers2_1_, objectdefi0_.uuid_ as uuid_3_1_, objectdefi0_.externalReferenceCode as external4_1_, objectdefi0_.companyId as companyi5_1_, objectdefi0_.userId as userid6_1_, objectdefi0_.userName as username7_1_, objectdefi0_.createDate as createda8_1_, objectdefi0_.modifiedDate as modified9_1_, objectdefi0_.accountERObjectFieldId as account10_1_, objectdefi0_.descriptionObjectFieldId as descrip11_1_, objectdefi0_.objectFolderId as objectf12_1_, objectdefi0_.rootObjectDefinitionId as rootobj13_1_, objectdefi0_.titleObjectFieldId as titleob14_1_, objectdefi0_.accountEntryRestricted as account15_1_, objectdefi0_.active_ as active_16_1_, objectdefi0_.className as classna17_1_, objectdefi0_.dbTableName as dbtable18_1_, objectdefi0_.enableCategorization as enablec19_1_, objectdefi0_.enableComments as enablec20_1_, objectdefi0_.enableIndexSearch as enablei21_1_, objectdefi0_.enableLocalization as enablel22_1_, objectdefi0_.enableObjectEntryDraft as enableo23_1_, objectdefi0_.enableObjectEntryHistory as enableo24_1_, objectdefi0_.label as label25_1_, objectdefi0_.modifiable as modifia26_1_, objectdefi0_.name as name27_1_, objectdefi0_.panelAppOrder as panelap28_1_, objectdefi0_.panelCategoryKey as panelca29_1_, objectdefi0_.pkObjectFieldDBColumnName as pkobjec30_1_, objectdefi0_.pkObjectFieldName as pkobjec31_1_, objectdefi0_.pluralLabel as plurall32_1_, objectdefi0_.portlet as portlet33_1_, objectdefi0_.scope as scope34_1_, objectdefi0_.storageType as storage35_1_, objectdefi0_.system_ as system_36_1_, objectdefi0_.version as version37_1_, objectdefi0_.status as status38_1_ from ObjectDefinition objectdefi0_ where (objectdefi0_.companyId=? )AND(objectdefi0_.status=? ) order by  objectdefi0_.name ASC <Open> 1 1 1
```

And two  SQL select in the PR https://github.com/liferay-core-infra/liferay-portal/pull/7684
```
select objectdefi0_.objectDefinitionId as objectde1_1_, objectdefi0_.mvccVersion as mvccvers2_1_, objectdefi0_.uuid_ as uuid_3_1_, objectdefi0_.externalReferenceCode as external4_1_, objectdefi0_.companyId as companyi5_1_, objectdefi0_.userId as userid6_1_, objectdefi0_.userName as username7_1_, objectdefi0_.createDate as createda8_1_, objectdefi0_.modifiedDate as modified9_1_, objectdefi0_.accountERObjectFieldId as account10_1_, objectdefi0_.descriptionObjectFieldId as descrip11_1_, objectdefi0_.objectFolderId as objectf12_1_, objectdefi0_.rootObjectDefinitionId as rootobj13_1_, objectdefi0_.titleObjectFieldId as titleob14_1_, objectdefi0_.accountEntryRestricted as account15_1_, objectdefi0_.active_ as active_16_1_, objectdefi0_.className as classna17_1_, objectdefi0_.dbTableName as dbtable18_1_, objectdefi0_.enableCategorization as enablec19_1_, objectdefi0_.enableComments as enablec20_1_, objectdefi0_.enableIndexSearch as enablei21_1_, objectdefi0_.enableLocalization as enablel22_1_, objectdefi0_.enableObjectEntryDraft as enableo23_1_, objectdefi0_.enableObjectEntryHistory as enableo24_1_, objectdefi0_.label as label25_1_, objectdefi0_.modifiable as modifia26_1_, objectdefi0_.name as name27_1_, objectdefi0_.panelAppOrder as panelap28_1_, objectdefi0_.panelCategoryKey as panelca29_1_, objectdefi0_.pkObjectFieldDBColumnName as pkobjec30_1_, objectdefi0_.pkObjectFieldName as pkobjec31_1_, objectdefi0_.pluralLabel as plurall32_1_, objectdefi0_.portlet as portlet33_1_, objectdefi0_.scope as scope34_1_, objectdefi0_.storageType as storage35_1_, objectdefi0_.system_ as system_36_1_, objectdefi0_.version as version37_1_, objectdefi0_.status as status38_1_ from ObjectDefinition objectdefi0_ where (objectdefi0_.companyId=? )AND(objectdefi0_.status=? ) order by  objectdefi0_.name ASC <Open>
```
```
select objectdefi0_.objectDefinitionId as objectde1_1_, objectdefi0_.mvccVersion as mvccvers2_1_, objectdefi0_.uuid_ as uuid_3_1_, objectdefi0_.externalReferenceCode as external4_1_, objectdefi0_.companyId as companyi5_1_, objectdefi0_.userId as userid6_1_, objectdefi0_.userName as username7_1_, objectdefi0_.createDate as createda8_1_, objectdefi0_.modifiedDate as modified9_1_, objectdefi0_.accountERObjectFieldId as account10_1_, objectdefi0_.descriptionObjectFieldId as descrip11_1_, objectdefi0_.objectFolderId as objectf12_1_, objectdefi0_.rootObjectDefinitionId as rootobj13_1_, objectdefi0_.titleObjectFieldId as titleob14_1_, objectdefi0_.accountEntryRestricted as account15_1_, objectdefi0_.active_ as active_16_1_, objectdefi0_.className as classna17_1_, objectdefi0_.dbTableName as dbtable18_1_, objectdefi0_.enableCategorization as enablec19_1_, objectdefi0_.enableComments as enablec20_1_, objectdefi0_.enableIndexSearch as enablei21_1_, objectdefi0_.enableLocalization as enablel22_1_, objectdefi0_.enableObjectEntryDraft as enableo23_1_, objectdefi0_.enableObjectEntryHistory as enableo24_1_, objectdefi0_.label as label25_1_, objectdefi0_.modifiable as modifia26_1_, objectdefi0_.name as name27_1_, objectdefi0_.panelAppOrder as panelap28_1_, objectdefi0_.panelCategoryKey as panelca29_1_, objectdefi0_.pkObjectFieldDBColumnName as pkobjec30_1_, objectdefi0_.pkObjectFieldName as pkobjec31_1_, objectdefi0_.pluralLabel as plurall32_1_, objectdefi0_.portlet as portlet33_1_, objectdefi0_.scope as scope34_1_, objectdefi0_.storageType as storage35_1_, objectdefi0_.system_ as system_36_1_, objectdefi0_.version as version37_1_, objectdefi0_.status as status38_1_ from ObjectDefinition objectdefi0_ where (objectdefi0_.companyId=? )AND(objectdefi0_.active_=? )AND(objectdefi0_.status=? ) order by  objectdefi0_.name ASC <Open>
```

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by pedro-oliveira446** [comment]
Hi @shuyangzhou ,

Thank you! The CI is currently experiencing some issues, so I’m waiting for it to normalize before proceeding.

**Comment by pedro-oliveira446** [comment]
The CI results are OK, I sent this manually to Brian here https://github.com/brianchandotcom/liferay-portal/pull/156772

**Pull request closed without merging**
