### PR TITLE
LPS-136334 The widget crashes when changing the filter with "downloads" in DM management toolbar

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:test:sf

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@stsquared99 Conflicts, please rebase and resend.

Thanks.
Tina

**Comment by tinatian** [comment]
ci:close

**Comment by stsquared99** [comment]
Resent: https://github.com/liferay-core-infra/liferay-portal/pull/31

**Pull request closed without merging**
