### PR TITLE
[TS] LPS-142380 7-25

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-142380 Add validation in ExpandoColumnLocalServiceImpl
- LPS-142380 Add test
- LPS-142380 Use proper method to add the attribute with default value to make sure validation is executed before creating the value
- LPS-142380 Show error message on UI
- LPS-142380 buildLang
- LPS-142380 SV
- LPS-142380 SF, inline
- LPS-142380 SF, remove unnecessary try-rethrow
- LPS-142380 Use ReflectionUtil to keep the exception instead of wrapping it in a RuntimeException; in this change's case, the UI won't be able to show the error message if the exception is rethrown as RuntimeException.

### CODE REVIEW

**Comment by dantewang** [comment]
@catarineaguiar Could you review the test results when they finish? Thanks!

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Tina

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121028

**Pull request closed without merging**
