### PR TITLE
Lps 191596 9 21

### PR DESCRIPTION
**Pull request by RenanUmV**
Related pull: https://github.com/brianchandotcom/liferay-portal/pull/141436

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by rafaprax** [comment]
forward to BChan, see https://github.com/brianchandotcom/liferay-portal/pull/141561

/cc @shuyangzhou

**Pull request closed without merging**
