### PR TITLE
[PowerMock] LPS 151637

### PR DESCRIPTION
**Pull request by JanisZhang**

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @tinatian @dantewang,

This pull is to remove PowerMock in modules/apps/dynamic-data-mapping-form-evaluator-impl.

https://issues.liferay.com/browse/LPS-151637

Thanks for checking.

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116290

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
