### PR TITLE
[Component with its own class name as service type] LPS-198392 Refactor components from batch-planner-rest-impl and portal-search-solr8-impl modules

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-198392](https://liferay.atlassian.net/browse/LPS-198392)

Previous Pull: https://github.com/liferay-core-infra/liferay-portal/pull/6158

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
ci:test:data-integration

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by RenanUmV** [comment]
Just removed two commits that were already sent in this [PR](https://github.com/liferay-core-infra/liferay-portal/pull/6162)

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:search

**Comment by RenanUmV** [comment]
ci:test:data-integration

**Comment by catarineaguiar** [comment]
no regressions found

**Review by rafaprax — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

cc @tinatian

**Pull request closed without merging**
