### PR TITLE
LPS-154123

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-154123.
I have update this to 4.0.3 because based on https://github.com/brettwooldridge/HikariCP, for java 8 we can only update up to 4.0.3.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result again, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found

**Comment by tinatian** [comment]
ci:test:help

**Comment by tinatian** [comment]
ci:test:environments

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina.

**Comment by tinatian** [comment]
@kyle-miho I do not think the ci test contains test for HikariCP, could you please test it manually?

Thanks.
Tina.

**Comment by catarineaguiar** [comment]
@tinatian analyzing the results any regressions were found, but ci test environments doesn't contains test for HikariCP.

**Comment by tinatian** [comment]
@zhangyan0701 could you please test HikariCP manually?

Thanks
Tina

**Comment by zhangyan0701** [comment]
Hi @kyle-miho @koor4356

I am not sure how to test HikariCP manually, could any of you help with this?

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

HikariCP is the only connection pull we support and used by default, all the databases we support worked well with the upgraded version based on the ci:test:environment result.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/118621

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
