### PR TITLE
LPD-34356 Fix MonitoringFilter and clean up

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:66441834

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 66441834.
> 
> Job Link: [generate-testray-csv](https://test-1-34.liferay.com/job/generate-testray-csv/163/)
> 
> Testray CSV Link: [testray-results-66441834.csv](https://test-1-34.liferay.com/userContent/jobs/generate-testray-csv/builds/163/testray-results-66441834.csv)

No unique failure after comparing testray history.

**Comment by tinatian** [comment]
ci:test:core-function

**Comment by tinatian** [comment]
@dantewang Code looks good to me, just want to run functional tests to make sure no regression, please forward if this passed functional tests

**Comment by tinatian** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:70692995

**Comment by dantewang** [comment]
ci:forward:force

The functional failures marked unique are happening on other runs.

**Pull request closed without merging**
