### PR TITLE
[Hibernate] LPS-150562 Create module to manage and deploy additonal dependencies for Hibernate 5

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian I went with the same way used by portal-jsp-engine to deploy the jars. I tested it with the Hibernate changes and it worked. In this PR I didn't add the `.lfrbuild-portal` marker file so it won't deploy during ant all; will add it when actually upgrading to Hibernate 5.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
@dantewang the goal for the lib/portal cleanup is not to just empty out lib/portal, it is to cleanup "shielded-container-lib" in order to prepare osgifying the top level jars. So doing this kind of deployment is not helping the lib cleanup.
If you are sure all the jars here are only used by hibernate, then it still has some value to group them like this (but not necessary). If they are possibly used by others, doing this will actually cause some confusion in the later cleanup.

**Comment by tinatian** [comment]
@shuyangzhou Yes, these jars are only used by hibernate 5, we grouped them together to make it easier to move hibernate out later. Some of these jars were in lib/portal, but had been removed, we really do not want to add them back for confusion and another round of clean up.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
