### PR TITLE
[Component with its own class name as service type ] LPS-193506 Refactor Provider components from Message-boards

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**
This pr is linked to [LPS-133506](https://github.com/liferay-core-infra/liferay-portal/pull/5279)

### CODE REVIEW

**Review by rafaprax — CHANGES_REQUESTED** [review]

**Comment by GabrielHenriquedev** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:relevant

**Review by rafaprax — APPROVED** [review]

**Comment by Kvale1733** [comment]
ci:test:message-boards

**Comment by shuyangzhou** [comment]
ci:forward:force

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139856

**Pull request closed without merging**
