### PR TITLE
[Components with more than 1 service] LPS-178221 Refactor UpgradeStepRegistrator components with more than 1 service type

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@MrJohn1911 possible regression:

`UpgradeAssetDisplayPageEntryTest`
```
     [exec] com.liferay.journal.upgrade.v1_1_6.test.UpgradeAssetDisplayPageEntryTest > classMethod FAILED
     [exec]     java.lang.IllegalStateException: Timed out while waiting for service com.liferay.portal.upgrade.registry.UpgradeStepRegistrator (&(objectClass=com.liferay.journal.internal.upgrade.registry.JournalServiceUpgradeStepRegistrator))
     [exec]     	at com.liferay.portal.test.rule.InjectTestBag._getServiceReference(InjectTestBag.java:199)
     [exec]     	at com.liferay.portal.test.rule.InjectTestBag.injectFields(InjectTestBag.java:78)
     [exec]     	at com.liferay.portal.test.rule.InjectTestRule.beforeClass(InjectTestRule.java:49)
     [exec]     	at com.liferay.portal.test.rule.InjectTestRule.beforeClass(InjectTestRule.java:24)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-03/test-1-26/test-portal-acceptance-pullrequest(master)/8178/modules-integration-mysql57-jdk8/0/22/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:startup

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
ci:test:calendar

**Comment by catarineaguiar** [comment]
@MrJohn1911 

failure on startup:
```
[beanshell] 2023-03-15 20:09:59.302 INFO  [main][LoggingTimer:83] Starting com.liferay.commerce.account.internal.verify.CommerceAccountServiceVerifyProcess#verifyAccountRoles
[beanshell] 2023-03-15 20:09:59.320 ERROR [main][BatchingBatch:134] HHH000315: Exception executing batch [java.sql.BatchUpdateException: Deadlock found when trying to get lock; try restarting transaction], SQL: insert into Role_ (mvccVersion, ctCollectionId, uuid_, companyId, userId, userName, createDate, modifiedDate, classNameId, classPK, name, title, description, type_, subtype, roleId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
[beanshell] 2023-03-15 20:09:59.321 ERROR [main][SqlExceptionHelper:142] Deadlock found when trying to get lock; try restarting transaction
[beanshell] 2023-03-15 20:09:59.337 INFO  [main][LoggingTimer:44] Completed com.liferay.commerce.account.internal.verify.CommerceAccountServiceVerifyProcess#verifyAccountRoles in 35 ms
[beanshell] 2023-03-15 20:09:59.337 INFO  [main][VerifyProcess:90] Completed verification process com.liferay.commerce.account.internal.verify.CommerceAccountServiceVerifyProcess in 36 ms
[beanshell] 2023-03-15 20:09:59.337 ERROR [main][VerifyProcessTrackerOSGiCommands:323] null
[beanshell] com.liferay.portal.verify.VerifyException: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.OptimisticLockException: org.hibernate.exception.LockAcquisitionException: could not execute batch
[beanshell] 	at com.liferay.portal.verify.VerifyProcess.verify(VerifyProcess.java:84) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.verify.extender.internal.osgi.commands.VerifyProcessTrackerOSGiCommands._executeVerifyProcess(VerifyProcessTrackerOSGiCommands.java:317) [bundleFile:?]
[beanshell] 	at com.liferay.portal.verify.extender.internal.osgi.commands.VerifyProcessTrackerOSGiCommands.access$200(VerifyProcessTrackerOSGiCommands.java:72) [bundleFile:?]
[beanshell] 	at com.liferay.portal.verify.extender.internal.osgi.commands.VerifyProcessTrackerOSGiCommands$2.addingService(VerifyProcessTrackerOSGiCommands.java:229) [bundleFile:?]
[beanshell] 	at com.liferay.portal.verify.extender.internal.osgi.commands.VerifyProcessTrackerOSGiCommands$2.addingService(VerifyProcessTrackerOSGiCommands.java:205) [bundleFile:?]
[beanshell] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$DefaultEmitter.emit(ServiceTrackerMapImpl.java:209) [com.liferay.osgi.service.tracker.collections.jar:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-03/test-1-37/test-portal-acceptance-pullrequest(master)/9862/functional-smoke-startup-tomcat90-mysql57-jdk8/0/19/jenkins-console.txt.gz?authuser=0)

regression in upgrade integration test:
```
     [exec] com.liferay.dynamic.data.mapping.upgrade.v2_0_3.test.UpgradeDDMFormInstanceSettingsTest > classMethod FAILED
     [exec]     java.lang.IllegalStateException: Timed out while waiting for service com.liferay.portal.upgrade.registry.UpgradeStepRegistrator (&(objectClass=com.liferay.dynamic.data.mapping.internal.upgrade.registry.DDMServiceUpgradeStepRegistrator))
     [exec]     	at com.liferay.portal.test.rule.InjectTestBag._getServiceReference(InjectTestBag.java:199)
     [exec]     	at com.liferay.portal.test.rule.InjectTestBag.injectFields(InjectTestBag.java:78)
     [exec]     	at com.liferay.portal.test.rule.InjectTestRule.beforeClass(InjectTestRule.java:49)
     [exec]     	at com.liferay.portal.test.rule.InjectTestRule.beforeClass(InjectTestRule.java:24)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:54)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-03/test-1-37/test-portal-acceptance-pullrequest(master)/9861/modules-integration-mysql57-jdk8/0/14/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
