### PR TITLE
[TS] LPS-141588

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This is a followup of https://github.com/tinatian/liferay-core-infra/liferay-portal/pull/39 after adressing the latest changes recommended in https://issues.liferay.com/browse/PTR-2723?focusedCommentId=2578713&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2578713. 

Could you please review it?

Thanks in advance,
Daniel

\cc @ericyanLr

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 The `ci:test `failed twice in a row, could you please check if there is anything related to this pull as the code looks good to me

**Comment by vicnate5** [comment]
@tinatian There is a merge conflict with upstream preventing the tests from running.

**Comment by dacousalr** [comment]
Resent in https://github.com/liferay-core-infra/liferay-portal/pull/67

**Pull request closed without merging**
