### PR TITLE
[TS] LPS-148438 Use same ownerid to add preferences on process portlet method

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-148438

Tests passed here: https://github.com/holatuwol/liferay-portal/pull/255

Issue introduced by the fix for [LPS-93992](https://issues.liferay.com/browse/LPS-93992), which hard-coded the `ownerId` parameter to the `groupId` in https://github.com/liferay/liferay-portal/commit/f622bb96ce0c57bdb93a5bf084352eb53a15397e and this fix updates the logic to use the correct value.

Testing the steps provided in LPS-93992 shows that the issue is still fixed with these changes applied.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@holatuwol Code looks good to me. I will trigger ci:test to confirm no side effect caused by this, once QA scanned the test results, it should be good to go.

Thanks.
Tina.

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks
Tina

**Comment by vicnate5** [comment]
@bronsonsoda Can you check this one?

**Comment by bronsonsoda** [comment]
@tinatian 
Unique test failures, passes locally
LocalFile.OAuth2#GrantedAuthorizationsCanBeRevoked
[testray](https://testray.liferay.com/home/-/testray/case_results/1624488510?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1624470042%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

@vicnate5

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@yuhai I believe this should fix https://issues.liferay.com/browse/LPS-88060, could you please verify? If yes, please add your integrations test to it.

Thanks.
Tina.

**Comment by yuhai** [comment]
> @yuhai I believe this should fix https://issues.liferay.com/browse/LPS-88060, could you please verify? If yes, please add your integrations test to it.
> 
> Thanks. Tina.

@tinatian, the fix is not enough for https://issues.liferay.com/browse/LPS-88060, it won't generate the required [data](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/model/impl/LayoutImpl.java#L1124-L1127).

**Comment by tinatian** [comment]
@yuhai It should go into this block https://github.com/liferay/liferay-portal/blob/0de64eb6649bc87190fe93e0ea01d194e31e065e/portal-impl/src/com/liferay/portal/model/impl/LayoutImpl.java#L1130-L1144, which you do not need the data you mentioned.

Tina

**Comment by holatuwol** [comment]
Spoke with @ericyanLr, will double-check the logic tonight to make sure we're fixing the right bug.

**Comment by holatuwol** [comment]
Debugging the issue, it looks like [LPS-88060](https://issues.liferay.com/browse/LPS-88060) happens due to a code execution order issue.

In order to figure out the `ModifiableSettings` to generate the default portlet preferences XML, it initializes a `PortletPreferences` object, but this check always concludes that the portlet preferences not embedded, because the preferences haven't been created yet.

* [TemplateProcessor.java#L180-L181](https://github.com/liferay/liferay-portal/blob/7.4.1-ga2/portal-impl/src/com/liferay/portal/layoutconfiguration/util/velocity/TemplateProcessor.java#L180-L181)
* [PortletPreferencesLocalServiceImpl.java#L366-L367](https://github.com/liferay/liferay-portal/blob/7.4.1-ga2/portal-impl/src/com/liferay/portal/service/impl/PortletPreferencesLocalServiceImpl.java#L366-L367)
* [PortletInstanceSettingsLocator.java#L57-L63](https://github.com/liferay/liferay-portal/blob/7.4.1-ga2/portal-kernel/src/com/liferay/portal/kernel/settings/PortletInstanceSettingsLocator.java#L57-L63)
* [PortletInstanceSettingsLocator.java#L91-L94](https://github.com/liferay/liferay-portal/blob/7.4.1-ga2/portal-kernel/src/com/liferay/portal/kernel/settings/PortletInstanceSettingsLocator.java#L91-L94)

If we then move the code block up and update it to create the embedded portlet preferences (ownerId = groupId, plid = 0), it still fails the embedded check due to a fail-fast that checks to make sure that there is a dummy portlet preference created for the page (all values blank) in addition to the embedded portlet which contains the shared values.

* [TemplateProcessor.java#L220-L223](https://github.com/liferay/liferay-portal/blob/7.4.1-ga2/portal-impl/src/com/liferay/portal/layoutconfiguration/util/velocity/TemplateProcessor.java#L220-L223)
* [LayoutImpl.java#L1066-L1073](https://github.com/liferay/liferay-portal/blob/7.4.1-ga2/portal-impl/src/com/liferay/portal/model/impl/LayoutImpl.java#L1066-L1073)

This means there are two ways to resolve [LPS-88060](https://issues.liferay.com/browse/LPS-88060):

1. Assume that [LPS-148438](https://issues.liferay.com/browse/LPS-148438) is a bug and remove the fail-fast check.
2. Assume that [LPS-148438](https://issues.liferay.com/browse/LPS-148438) is not a bug and create the specific dummy portlet preference checked by Layout.isEmbedded in order to get the check to pass

**Comment by holatuwol** [comment]
@tinatian
Your explanation makes sense to me. I'll go ahead and close this pull request and explain the situation to the TSE on the PTR ticket.

**Pull request closed without merging**
