### PR TITLE
[JDK21]LPD-19640 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:jdk21

**Comment by dantewang** [comment]
ci:report:2546794690

**Comment by dantewang** [comment]
ci:report:2546820322

**Comment by dantewang** [comment]
@tinatian No unique failure in relevant; the `Talend` test failure did not happen in jdk21.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/147878

**Pull request closed without merging**
