### PR TITLE
[TS] LPD-36161 

### PR DESCRIPTION
**Pull request by ericyanLr**
**Ticket:** https://liferay.atlassian.net/browse/LPD-36161
**Previous PR:** https://github.com/liferay-core-infra/liferay-portal/pull/7477

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:28548795

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 28548795.
> 
> Job Link: [generate-testray-csv](https://test-1-27.liferay.com/job/generate-testray-csv/244/)
> 
> Testray CSV Link: [testray-results-28548795.csv](https://test-1-27.liferay.com/userContent/jobs/generate-testray-csv/builds/244/testray-results-28548795.csv)

No unique failure in report

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
