### PR TITLE
[Remove Stream/Optional usage] LPS-175072 Remove usages of Stream for module: oauth2-provider-web

### PR DESCRIPTION
**Pull request by W2jx**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3538

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:oauth2

**Comment by Kvale1733** [comment]
@W2jx No regressions.

**Comment by W2jx** [comment]
no conflicts(2/27 8:29)

**Comment by W2jx** [comment]
no conflicts(2/28 10:42)

**Comment by W2jx** [comment]
no conflicts(3/1 10:45)

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130965

**Pull request closed without merging**
