### PR TITLE
[Remove unused reference] LPS-166254 

### PR DESCRIPTION
**Pull request by JanisZhang**
This PR is to remove unused fields in `headless-commerce-admin-inventory-impl`. Thanks!

All tests passed in https://github.com/JanisZhang/liferay-portal/pull/175#issuecomment-1286461566

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:commerce

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/125347

cc @shuyangzhou @tinatian

**Pull request closed without merging**
