### PR TITLE
[TS] LPS-201892

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
From previous pulls tests have been unified in only one.

/cc @achaparro

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
Test failure not related. @tinatian could you please take a look when you have time?

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/147302

**Pull request closed without merging**
