### PR TITLE
[OrderByComparator] LPD-25985 Clean up and Apply Singleton in module portlet-configuration and site

### PR DESCRIPTION
**Pull request by Valmir-unicap**
- Ticket: https://liferay.atlassian.net/browse/LPD-25985

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:echo

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@Valmir-unicap LGTM, we can forward if no CI failure.

**Comment by Valmir-unicap** [comment]
ci:report:2570569874

**Comment by Valmir-unicap** [comment]
ci:report:2570601287

**Comment by Valmir-unicap** [comment]
No regression found

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/150543

**Pull request closed without merging**
