### PR TITLE
LPS-158836 Object creation with Decimal field fails with input 10000000000 on Oracle 19.3

### PR DESCRIPTION
**Pull request by ces-locpham**
Dear,

Here is the PR for fixing https://issues.liferay.com/browse/LPS-158836
Please help review and leave your comments.

This PR is reviewed: https://github.com/liferay-core-infra/liferay-portal/pull/2821
Thanks.

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:environments

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
@locpham97 No regressions found. Manual testing passed following ticket steps.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128949

**Pull request closed without merging**
