### PR TITLE
LPS-150185 Decouple HttpImpl from test

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by shuyangzhou** [comment]
@tinatian @JanisZhang https://github.com/liferay/liferay-portal/blob/master/modules/apps/content-dashboard/content-dashboard-web/src/main/java/com/liferay/content/dashboard/web/internal/portlet/action/GetContentDashboardItemInfoMVCResourceCommand.java#L472 and https://github.com/liferay/liferay-portal/blob/master/modules/apps/content-dashboard/content-dashboard-web/src/main/java/com/liferay/content/dashboard/web/internal/servlet/taglib/util/ContentDashboardDropdownItemsProvider.java#L177 are not used at all, they should be removed from production code. Make sure to check other fields along the way, since this looks like a common issue within content-dashboard code.

**Comment by tinatian** [comment]
@shuyangzhou Yes, I realized we have this kind of issue, we will do a clean up after we moved out the functions related to those 4 ignored tests, so the plan would be:
1. Move out the functions related to those tests and remove the ignore tag
2. Clean up unused fields
3. Move out other functions not related to http client one by one

FYI @JanisZhang @dantewang

**Comment by shuyangzhou** [comment]
@tinatian I will wait for you guys to finish it as whole, please avoid the ignore tests in the history. Please try to get the whole change ready sometime next week.

**Comment by JanisZhang** [comment]
Noted with thanks.

**Comment by tinatian** [comment]
Close, will resend.

Tina.

**Pull request closed without merging**
