### PR TITLE
[Method References ] LPS-160434 Convert method references to field references in classes extend BasePanelApp

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:commerce

**Comment by W2jx** [comment]
no conflicts(4/11 11:12)

**Comment by zhangyan0701** [comment]
Possible regressions found:
1. Some integration tests failed with error `com.liferay.portal.kernel.exception.NoSuchListTypeException`:[com.liferay.headless.admin.user.resource.v1_0.test.AccountResourceTest](https://testray.liferay.com/home/-/testray/case_results/2263699037)
[com.liferay.headless.admin.user.resource.v1_0.test.RoleResourceTest](https://testray.liferay.com/home/-/testray/case_results/2263699076)
[com.liferay.headless.admin.user.resource.v1_0.factory.test.PhoneResourceFactoryImplTest](https://testray.liferay.com/home/-/testray/case_results/2263699028)
[com.liferay.headless.admin.user.resource.v1_0.test.EmailAddressResourceTest](https://testray.liferay.com/home/-/testray/case_results/2263699054)
[com.liferay.headless.admin.user.resource.v1_0.test.PhoneResourceTest](https://testray.liferay.com/home/-/testray/case_results/2263699065)
[com.liferay.headless.admin.user.resource.v1_0.test.PostalAddressResourceTest](https://testray.liferay.com/home/-/testray/case_results/2263699070)
[com.liferay.organizations.change.tracking.test.OrganizationTableReferenceDefinitionTest](https://testray.liferay.com/home/-/testray/case_results/2263699416)

2. `java.lang.AssertionError` error occurs in some tests:[com.liferay.headless.admin.user.resource.v1_0.test.AccountRoleResourceTest](https://testray.liferay.com/home/-/testray/case_results/2263699048)
[com.liferay.headless.admin.user.resource.v1_0.test.OrganizationResourceTest](https://testray.liferay.com/home/-/testray/case_results/2263699058)
[com.liferay.headless.admin.user.resource.v1_0.test.SegmentResourceTest](https://testray.liferay.com/home/-/testray/case_results/2263699080)

3. `Invalid filter: The pattern must not be null` error occurs in test:
[com.liferay.headless.admin.user.resource.v1_0.test.SegmentUserResourceTest](https://testray.liferay.com/home/-/testray/case_results/2263699090)

**Pull request closed without merging**
