### PR TITLE
LPS-171611 Rewrite actionableQuery to DSLQuery in UserExpandoColumnModelListener

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@GabrielHenriquedev No regressions found.

**Comment by GabrielHenriquedev** [comment]
@shuyangzhou this one is ready to go.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128183

**Pull request closed without merging**
