### PR TITLE
[Remove Blocking usages]LPS-187881 portal-kernel |ImageMagickUtil, ImageToolUtil

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-187881

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:stable

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
