### PR TITLE
[MB Performance tuning] LPS-152453

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, please refer to the test [result](https://github.com/GinsonRen/liferay-portal/pull/605#issuecomment-1111995148)

### CODE REVIEW

**Comment by dantewang** [comment]
@yuhai Could you please change your commit message to say like "Short cut earlier to avoid getting MBGroupServiceSettings in certain conditions"? The current message makes me think it's a hack for our tests, but it's actually a generally good fix.

**Comment by yuhai** [comment]
> @yuhai Could you please change your commit message to say like "Short cut earlier to avoid getting MBGroupServiceSettings in certain conditions"? The current message makes me think it's a hack for our tests, but it's actually a generally good fix.

@dantewang, I changed the commit message as you said. Just push force.

**Comment by dantewang** [comment]
@yuhai Thanks!

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
@vicnate5 will not have time to review this one today

**Comment by vicnate5** [comment]
Due to the new Release, QA will review this on Monday.

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116937

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
