### PR TITLE
LPS-158624 Clean up petra-xml

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
push to fix SF

**Comment by julschong** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@julschong regression found:

```
 [exec] com.liferay.user.groups.admin.uad.exporter.test.UserGroupUADExporterTest > testExportModelWithCDATASyntax FAILED
     [exec]     com.liferay.portal.kernel.exception.SystemException: org.dom4j.DocumentException: Error on line 1 of document  : The character sequence "]]>" must not appear in content unless used to mark the end of a CDATA section.
     [exec]     	at com.liferay.user.associated.data.exporter.DynamicQueryUADExporter.formatXML(DynamicQueryUADExporter.java:128)
     [exec]     	at com.liferay.user.associated.data.exporter.DynamicQueryUADExporter.export(DynamicQueryUADExporter.java:62)
     [exec]     	at com.liferay.user.associated.data.exporter.DynamicQueryUADExporter.export(DynamicQueryUADExporter.java:47)
     [exec]     	at com.liferay.user.groups.admin.uad.exporter.test.UserGroupUADExporterTest.testExportModelWithCDATASyntax(UserGroupUADExporterTest.java:62)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-31/test-portal-acceptance-pullrequest(master)/5001/modules-integration-mysql57-jdk8/3/23/jenkins-console.txt.gz?authuser=0)

```
[echo] diff --git a/modules/apps/document-library/document-library-uad/src/main/java/com/liferay/document/library/uad/exporter/BaseDLFileEntryTypeUADExporter.java b/modules/apps/document-library/document-library-uad/src/main/java/com/liferay/document/library/uad/exporter/BaseDLFileEntryTypeUADExporter.java
     [echo] index 1f57cbcead76..62ec80a30ee4 100644
     [echo] --- a/modules/apps/document-library/document-library-uad/src/main/java/com/liferay/document/library/uad/exporter/BaseDLFileEntryTypeUADExporter.java
     [echo] +++ b/modules/apps/document-library/document-library-uad/src/main/java/com/liferay/document/library/uad/exporter/BaseDLFileEntryTypeUADExporter.java
     [echo] @@ -19,6 +19,7 @@ import com.liferay.document.library.kernel.service.DLFileEntryTypeLocalService;
     [echo]  import com.liferay.document.library.uad.constants.DLUADConstants;
     [echo]  import com.liferay.petra.string.StringBundler;
     [echo]  import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
     [echo] +import com.liferay.portal.kernel.util.StringUtil;
     [echo]  import com.liferay.user.associated.data.exporter.DynamicQueryUADExporter;
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-31/test-portal-acceptance-pullrequest(master)/5001/service-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
I think I fixed it, will run ci tests again

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
pushed to resolve conflict

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by tinatian** [comment]
@julschong This pull is big, please separate it into small pulls.

Thanks.
Tina.

**Pull request closed without merging**
