### PR TITLE
[Remove immediate=true usage core-infrastructure-3 part 1]Lps 169260

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-169260

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
ci:test:dl-store

**Comment by zhangyan0701** [comment]
Possible regression:

[com.liferay.portal.osgi.debug.declarative.service.test.DeclarativeServiceDependencyManagerTest.testDeclarativeServiceDependencyManagerResolvedDependencies](https://testray.liferay.com/home/-/testray/case_results/2075322108) failed with below error:
```
testDeclarativeServiceDependencyManagerResolvedDependencies: org.junit.ComparisonFailure: expected:<[All declarative service components are satisfied]> but was:<[ Bundle {id: 727, name: com.liferay.exportimport.service, version: 8.0.67}  Declarative Service {id: 3103, name: com.liferay.exportimport.lifecycle.SyncExportImportLifecycleMessageListener, unsatisfied references:    {name: _destination, target: (destination.name=liferay/export_import_lifecycle_event_sync)}  }  Declarative Service {id: 3099, name: com.liferay.exportimport.lifecycle.AsyncExportImportLifecycleMessageListener, unsatisfied references:    {name: _destination, target: (destination.name=liferay/export_import_lifecycle_event_async)}  } Bundle {id: 1018, name: com.liferay.segments.simulation.web, version: 3.0.24}  Declarative Service {id: 9433, name: com.liferay.segments.simulation.web.internal.application.list.SegmentsSimulationPanelApp, unsatisfied references:    {name: Portlet, target: (javax.portlet.name=com_liferay_segments_simulation_web_internal_portlet_SegmentsSimulationPortlet)}  }]>  at org.junit.Assert.assertEquals(Assert.java:117)  at org.junit.Assert.assertEquals(Assert.java:146)  at com.liferay.portal.osgi.debug.declarative.service.test.DeclarativeServiceDependencyManagerTest.testDeclarativeServiceDependencyManagerResolvedDependencies(DeclarativeServiceDependencyManagerTest.java:118)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)  at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)  at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)  at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)  at java.lang.Thread.run(Thread.java:745)
```

Full console log:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6524/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0

**Comment by slnn** [comment]
Hi @zhangyan0701 

I reproduced this issue on the master:69823205ae3ba77d6a20db26f450fa97426774ad without my changes in this pull.


> Possible regression:
> 
> [com.liferay.portal.osgi.debug.declarative.service.test.DeclarativeServiceDependencyManagerTest.testDeclarativeServiceDependencyManagerResolvedDependencies](https://testray.liferay.com/home/-/testray/case_results/2075322108) failed with below error:
> 
> ```
> testDeclarativeServiceDependencyManagerResolvedDependencies: org.junit.ComparisonFailure: expected:<[All declarative service components are satisfied]> but was:<[ Bundle {id: 727, name: com.liferay.exportimport.service, version: 8.0.67}  Declarative Service {id: 3103, name: com.liferay.exportimport.lifecycle.SyncExportImportLifecycleMessageListener, unsatisfied references:    {name: _destination, target: (destination.name=liferay/export_import_lifecycle_event_sync)}  }  Declarative Service {id: 3099, name: com.liferay.exportimport.lifecycle.AsyncExportImportLifecycleMessageListener, unsatisfied references:    {name: _destination, target: (destination.name=liferay/export_import_lifecycle_event_async)}  } Bundle {id: 1018, name: com.liferay.segments.simulation.web, version: 3.0.24}  Declarative Service {id: 9433, name: com.liferay.segments.simulation.web.internal.application.list.SegmentsSimulationPanelApp, unsatisfied references:    {name: Portlet, target: (javax.portlet.name=com_liferay_segments_simulation_web_internal_portlet_SegmentsSimulationPortlet)}  }]>  at org.junit.Assert.assertEquals(Assert.java:117)  at org.junit.Assert.assertEquals(Assert.java:146)  at com.liferay.portal.osgi.debug.declarative.service.test.DeclarativeServiceDependencyManagerTest.testDeclarativeServiceDependencyManagerResolvedDependencies(DeclarativeServiceDependencyManagerTest.java:118)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)  at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)  at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)  at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)  at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)  at java.lang.Thread.run(Thread.java:745)
> ```
> 
> Full console log: https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6524/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0

**Pull request closed without merging**
