### PR TITLE
[Remove Blocking usages] LPS-191761 portal-kernel | WorkflowLogManagerUtil

### PR DESCRIPTION
**Pull request by JanisZhang**
previous: https://github.com/liferay-core-infra/liferay-portal/pull/5149

https://liferay.atlassian.net/browse/LPS-191761

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:workflow

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
no regressions found

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:stable

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian This is the same pattern as what we did for `WorkflowComparatorFactoryUtil`.

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
