### PR TITLE
LPS-134898

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
There's no easy way to reproduce it as it's a race condition, but we've delivered the safe check c6bc1b5e4e1d11233e878a5480c3ef2ce6cb1bd1 to several customers and it has fixed their problems.

**Comment by tinatian** [comment]
@marianoalvarosaiz The test you added seems weird, you are adding "value" and in its model listener, adding "another value", I do not think this is a valid use case.

Tina.

**Comment by tinatian** [comment]
@marianoalvarosaiz 
The test should always make sense, or else we won't know if this kind of race condition can happen in real life. There are so many race condition existing in our code base, but there are some we are not going to fix as we know those won't happen in real life as they are protected by other part of code or we have documentation to stop them happen. 

Please try to create a reasonable test and resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by marianoalvarosaiz** [comment]
@tinatian see https://github.com/liferay-core-infra/liferay-portal/pull/875

**Pull request closed without merging**
