### PR TITLE
[Ehcache-Configuration]Lps 205930

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-205930

### CODE REVIEW

**Comment by slnn** [comment]
ci:report:2487322054

**Comment by slnn** [comment]
From the testray csv for the upgrade test suiit, no unique failure appeared

**Comment by slnn** [comment]
ci:report:2488217767

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@tinatian @shuyangzhou This PR applies benchmark's cache configurations to portal; Lily only applied numbers, didn't modify configuration like `eternal=false`.

**Pull request closed without merging**
