### PR TITLE
LPS-167756 | master

### PR DESCRIPTION
**Pull request by ces-sontruong**
Hi team,

This is the fix for the [LPS-167756](https://issues.liferay.com/browse/LPS-167756), the original has passed my review at sontruong#73. Please help me to review and give feedback.

Thanks!
cc: @locpham97

### CODE REVIEW

**Comment by dantewang** [comment]
@zhangyan0701 With the config described in the ticket, could you double check whether other `rebuild-xxx` targets are executed?

**Comment by zhangyan0701** [comment]
@dantewang I only see the target `rebuild-hypersonic` is executed.

I think this is because only `rebuild-hypersonic` is called here https://github.com/liferay/liferay-portal/blob/master/build.xml#L373-L389, and there are files copied to ${liferay.home}/data/hypersonic even if the hypersonic type is not included.

**Comment by locpham97** [comment]
Hi @dantewang,
The rebuild-hypersonic is not executed. The "ant call" statement is called the target rebuild-hypersonic. However, I prevent executed the rebuild-hypersonic with if statement.

**Comment by zhangyan0701** [comment]
Hi @locpham97 @dantewang 

I tested again with the fix here this time. The rebuild-hypersonic target is not executed. And there is no files copied to `/liferay.home/data/hypersonic` folder even though there is a step https://github.com/liferay/liferay-portal/blob/f432b9e8a6df4a1975f64544b8fff8af539e1291/build.xml#L380, files `lportal.properties` and `lportal.script` don't exist in sql folder because I think they are the files that generated by target rebuild-hypersonic. So the result now should be the expected result, right?

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
@sontruongces @locpham97 You only skip hypersonic rebuild when it is not available, what about other types? The behavior is not consistent with other types.

**Comment by locpham97** [comment]
Hi @tinatian ,
I'm so sorry to reply late, but I just returned from a long holiday. 
Follow to the ticket, I think it is not necessary to check and skip tasks for every database type (I see the target is using for ant task). I think this is better to check a condition before this line https://github.com/liferay/liferay-portal/blob/f432b9e8a6df4a1975f64544b8fff8af539e1291/build.xml#L376, and skip the ant call task in here.
Could you verify it ? I will resend the PR.
Thansk,
Loc

**Pull request closed without merging**
