### PR TITLE
[Bug fix] LPS-150847

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @catarineaguiar,
Could you please help me scan the latest test results? thanks!

Regards.
Janis.

**Comment by catarineaguiar** [comment]
ci:test:environments

**Comment by catarineaguiar** [comment]
Running `ci:test:environments` to double check MariaDB failures

**Comment by JanisZhang** [comment]
ci:help

**Comment by dantewang** [comment]
@zhangyan0701 Could you please review the CI result, and also verify it on Windows? Thanks!

**Comment by zhangyan0701** [comment]
@dantewang The issue in LPS-150847 passed on Windows with the changes.

**Comment by dantewang** [comment]
@tinatian Code looks good to me, and tests passed.

**Comment by tinatian** [comment]
@dantewang @JanisZhang This is not the right direction to fix this issue. You are using another method to avoid exception thrown when validating path, it like you avoid an issue by not verifying the value it passed in.

The right direction should be, you keep the validation, but fix the issue by passing in validated value.

Here the issue happens at when you change a file to URI, and this logic currently do not support when file path contains special character, so your direction is to add support for the special character, either you throw exception or provide any kind of fall back.

Also, if your final fix is going to change framework level code, for example ZipWriterImpl, please always add test for it.

Please resend.

Thanks.
Tina.

**Comment by dantewang** [comment]
@tinatian What do you mean by the validation we skip?

The URI API provides 2 methods to get the path: one is decoded, one is not decoded. If we use the path from one URI to construct another URI, we should either:

use getPath and encode the path and then pass it to URI constrcutor,

or

use getRawPath and pass it to the URI constructor.

It's not skipping any validation. The undecoded path (raw path) from ine URI is always legal (validated).

**Comment by dantewang** [comment]
@tinatian Also, the special character is already handled by the file.toURI API, the issue here is that we use the wrong API from URI to get that path.

**Pull request closed without merging**
