### PR TITLE
[Method References 2] LPS-165133 Remove unused reference variable in module search-experiences-rest-impl(dxp)

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I hava made the reference variavle _jsonFactory "used".

Detial: https://github.com/liferay-core-infra/liferay-portal/pull/1942

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sxp

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
Hi @catarineaguiar  , Could you please help me check the test results ? Thanks!

**Comment by zhangyan0701** [comment]
ci:test:sxp

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
