### PR TITLE
LPS-158624 Clean up petra-xml part 1

### PR DESCRIPTION
**Pull request by julschong**
@tinatian 
HI Tina, 
This is resubmitted from #1695 

I split the pull into 2 parts.
Since XMLUtil.formatXML() is the one that will require regenerating service builder classes, I leave that it to part 2 to complete.

Thanks!

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@julschong semver error:

```
  [echo] ##
     [echo] ## /opt/dev/projects/github/liferay-portal/baseline-reports/portal-impl.log
     [echo] ##
     [echo] 
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portlet                                MINOR      8.1.0      8.1.0      8.2.0      VERSION INCREASE REQUIRED
[beanshell] 	+   class      com.liferay.portlet.PreferencesValueUtil
[beanshell] 		+   method     <init>()
[beanshell] 			+   return     void
[beanshell] 		+   method     clone()
[beanshell] 			+   access     protected
[beanshell] 			+   return     java.lang.Object
[beanshell] 		+   method     equals(java.lang.Object)
[beanshell] 			+   return     boolean
[beanshell] 		+   method     finalize()
[beanshell] 			+   access     protected
[beanshell] 			+   return     void
[beanshell] 		+   method     getActualValue(java.lang.String)
[beanshell] 			+   access     static
[beanshell] 			+   return     java.lang.String
[beanshell] 		+   method     getActualValues(java.lang.String[])
[beanshell] 			+   access     static
[beanshell] 			+   return     java.lang.String[]
[beanshell] 		+   method     getXMLSafeValue(java.lang.String)
[beanshell] 			+   access     static
[beanshell] 			+   return     java.lang.String
[beanshell] 		+   method     getXMLSafeValues(java.lang.String[])
[beanshell] 			+   access     static
[beanshell] 			+   return     java.lang.String[]
[beanshell] 		+   method     hashCode()
[beanshell] 			+   return     int
[beanshell] 		+   method     isNull(java.lang.String[])
[beanshell] 			+   access     static
[beanshell] 			+   return     boolean
[beanshell] 		+   method     toCompactSafe(java.lang.String)
[beanshell] 			+   access     static
[beanshell] 			+   return     java.lang.String
[beanshell] 		+   method     toString()
[beanshell] 			+   return     java.lang.String
[beanshell] 
[stopwatch] [run.batch.test.action: 9.512 sec]
     [echo] Semantic versioning is incorrect.
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-37/test-portal-acceptance-pullrequest(master)/5076/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/petra/petra-xml] STARTED
     [exec] 
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/petra/petra-xml] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.petra.xml                              MAJOR      1.0.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	-   class      com.liferay.petra.xml.DocUtil
     [exec]     		-   method     <init>()
     [exec]     			-   return     void
     [exec]     		-   method     add(com.liferay.portal.kernel.xml.Element,com.liferay.portal.kernel.xml.QName)
     [exec]     			-   access     static
     [exec]     			-   return     com.liferay.portal.kernel.xml.Element
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-37/test-portal-acceptance-pullrequest(master)/5076/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
pushed to fix semantic versioning

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123529

**Pull request closed without merging**
