### PR TITLE
LPS-159586 commerce-price-list-service Part 1: Clean Up | 8-16

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian I made this separate clean up PR to refactor some of the code in CommercePriceListLocalServiceImpl. With this, the cache management here should be much cleaner.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:commerce

**Comment by dantewang** [comment]
@catarineaguiar Could you please review the test results when they finish? Thanks!

**Comment by catarineaguiar** [comment]
@dantewang no regressions found.

**Comment by tinatian** [comment]
ci:test:help

**Comment by tinatian** [comment]
@dantewang As we talked, close and please resend.

Tina

**Pull request closed without merging**
