### PR TITLE
[TS] LPS-142380

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
@zhangyan0701 Please help me review the test results, thanks!

**Comment by crodriguezy** [comment]
HI @dantewang , in case you don't see any problem with it, I will deliver the fix to the customer.
Thanks

**Comment by dantewang** [comment]
@crodriguezy Sure!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@crodriguezy Please add test to cover your changes and resend.

Thanks.
Tina.

**Comment by crodriguezy** [comment]
Hi @dantewang , after analyzing what would be the best option for the required test, I was wondering if we should move our change to the [validate method](https://github.com/liferay/liferay-portal/blob/d365f9baded97fa9119cb07f5e0342304bf6c298/portal-impl/src/com/liferay/portlet/expando/service/impl/ExpandoColumnLocalServiceImpl.java#L534-L541) of  ExpandoColumnServiceImple.java, instead of checking the correct values in ExpandoPortlet. 

Let me know your thoughts please.

**Pull request closed without merging**
