### PR TITLE
LPS-143632 Remove LanguageUtil from moduels part 1a

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
@tinatian Hi Tina,
I split this pull smaller now.
test report was previously reviewed and no regression found: https://github.com/liferay-core-infra/liferay-portal/pull/821#issuecomment-1137703270

Thank you!

**Comment by julschong** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@slnn Please take this over.

Thanks.
Tina.

**Comment by slnn** [comment]
OK, got it

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina

**Comment by slnn** [comment]
Hi @tinatian 

I have checked the changes in this pull, and nothing wrong is found.

Lily

**Comment by tinatian** [comment]
@shuyangzhou This pull is ready to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/119220

**Pull request closed without merging**
