### PR TITLE
 [Remove immediate=true usage security part-1]Lps 168433 part 1

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-168433

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:security

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127118

**Pull request closed without merging**
