### PR TITLE
LPD-25512 Adapt tests using hard-coded test password in Clustering component

### PR DESCRIPTION
**Pull request by MrJohn1911**
Tested here: https://github.com/MrJohn1911/liferay-portal/pull/87

The tests did't fail / didn't had any unique failure.

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:core-functional

**Comment by julschong** [comment]
@MrJohn1911 Hi Victor, if you look into relevant, it didn't test anything because all we changed are functional tests.
Please make sure to run our core-functional tests and see if the changed tests are still good

**Comment by dantewang** [comment]
ci:report:2568258595

**Comment by dantewang** [comment]
ci:forward

cc @julschong @tinatian

**Pull request closed without merging**
