### PR TITLE
[Remove Blocking Usages] LPS-202480 Removing Unnecessary Usages of ServiceProxyFactory.newServiceTrackedInstance with blocking set to true in class DLStoreImpl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
no conflicts(11/27 9:10)

**Comment by W2jx** [comment]
no conflicts(11/27 9:10)

**Comment by zhangyan0701** [comment]
ci:test:dl-store

**Comment by W2jx** [comment]
Modify breaking change report to remove unnecessary blank lines.

**Comment by dantewang** [comment]
On hold, asked Jiaxu to double check why `setStore` was there.

**Comment by W2jx** [comment]
see https://github.com/liferay-core-infra/liferay-portal/pull/6310

**Pull request closed without merging**
