### PR TITLE
LPS-158836 Object creation with Decimal field fails with input 10000000000 on Oracle 19.3

### PR DESCRIPTION
**Pull request by thienquach87**
Dear,

Here is the PR for fixing https://issues.liferay.com/browse/LPS-158836
Please help review and leave your comments.

Thanks.
@locpham97

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:objects

**Comment by catarineaguiar** [comment]
ci:test:object

**Comment by chaowang-123** [comment]
@dantewang no regression found.

**Comment by zhangyan0701** [comment]
ci:test:environments

**Comment by zhangyan0701** [comment]
ci:stop

**Comment by zhangyan0701** [comment]
ci:test:environments

**Comment by zhangyan0701** [comment]
ci:test:environments

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@thienquach87 Please add an integration test to expose the issue.

Thanks.
Tina

**Comment by thienquach87** [comment]
> @thienquach87 Please add an integration test to expose the issue.
> 
> Thanks. Tina

@locpham97 Please add test as Tina requested. Thank you!

**Comment by tinatian** [comment]
@locpham97 It has been a week since we comment, I am going to close this pull, please resend.

Thanks.
Tina.

**Comment by locpham97** [comment]
ci:open

**Pull request closed without merging**
