### PR TITLE
[Convert method references]Lps 163035

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-163035

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

For the relevant tests and SF tests that have run in https://github.com/slnn/liferay-portal/pull/636, could you help to check the test results?

Thanks
Lily

**Comment by zhangyan0701** [comment]
ci:test:document

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@shuyangzhou @tinatian Forwarding this one as all tests passed review and changes are direct replacements.

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
