### PR TITLE
LPS-193525 Merge Patcher impl and interface into PatcherValues in kernel

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
fix sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong Compile issue
```
[exec] > Task :apps:server:server-admin-web:generateJSPJava
     [exec] Compiling JSP files of project ':apps:server:server-admin-web' with /opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.75/webapps/ROOT/WEB-INF/shielded-container-lib/util-taglib.jar as dependency in place of 'com.liferay.portal:com.liferay.util.taglib'
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/server/server-admin-web/build/jspc/org/apache/jsp/init_jsp.java:28: error: cannot find symbol
     [exec] import com.liferay.portal.kernel.patcher.PatcherUtil;
     [exec]                                         ^
     [exec]   symbol:   class PatcherUtil
     [exec]   location: package com.liferay.portal.kernel.patcher
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/server/server-admin-web/build/jspc/org/apache/jsp/company_005fmail_jsp.java:28: error: cannot find symbol
     [exec] import com.liferay.portal.kernel.patcher.PatcherUtil;
     [exec]                                         ^
     [exec]   symbol:   class PatcherUtil
     [exec]   location: package com.liferay.portal.kernel.patcher
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/server/server-admin-web/build/jspc/org/apache/jsp/error_jsp.java:28: error: cannot find symbol
     [exec] import com.liferay.portal.kernel.patcher.PatcherUtil;
```
[Log]https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/284805//consoleTextl)

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong Compile issue found
```
    [exec] > Task :apps:server:server-admin-web:generateJSPJava
     [exec] Compiling JSP files of project ':apps:server:server-admin-web' with /opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.75/webapps/ROOT/WEB-INF/shielded-container-lib/util-taglib.jar as dependency in place of 'com.liferay.portal:com.liferay.util.taglib'
     [exec] 
     [exec] > Task :apps:server:server-admin-web:compileJSP FAILED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/server/server-admin-web/build/jspc/org/apache/jsp/resources_jsp.java:256: error: cannot find symbol
     [exec] String[] installedPatches = PatcherValues.getInstalledPatches();
     [exec]                                          ^
     [exec]   symbol:   method getInstalledPatches()
     [exec]   location: class com.liferay.portal.kernel.patcher.PatcherValues
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/server/server-admin-web/build/jspc/org/apache/jsp/add_005flog_005fcategory_jsp.java uses or overrides a deprecated API.
```
[Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-40/test-portal-acceptance-pullrequest(master)/5462/modules-compile-jdk8/0/4/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
ci:forward:force

**Pull request closed without merging**
