### PR TITLE
[SF] LPS-175351 Update `JavaComponentAnnotationsCheck` to check that the `configurationPid` is used

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__ <https://liferay.atlassian.net/browse/LPS-175351>

Previously, `JavaComponentAnnotationsCheck` was checking if the class specified by the `configurationPid` existed but not if it was actually being used. This PR modifies the rule so that it does. Also, we no longer check if the class exists (if it does not exist, it will most likely lead to a compilation issue anyway).

While examining the SF violations, there were some OSGi component classes that I was unable to determine if the `configurationPid` was needed. Thus, I added a new property to the SF rule to allow exclusions. Let me know if some of the excluded classes can be removed from the list: 769826bcda7b18f16bdbf9961573ccf87b0f1fff.

### CODE REVIEW

**Comment by kevhlee** [comment]
cc: @tinatian

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:stop

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found. SF issue is not related.

**Pull request closed without merging**
