### PR TITLE
[Remove Stream/Optional usage] LPS-171138 export-import

### PR DESCRIPTION
**Pull request by JanisZhang**
previous:https://github.com/liferay-core-infra/liferay-portal/pull/2841 . Thanks

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:export-import

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@JanisZhang Please note I did not include https://github.com/liferay-core-infra/liferay-portal/pull/2874/commits/4a960e840535f7b12a773187792de740ab5fa1c1 as it changed the behavior, " _portletLocalService.getPortletById(changesetPortletId)" may also return null.

**Pull request closed without merging**
