### PR TITLE
[Blocker]LPS-184522 revert the removal of getInstance(String, UploadPortletRequest)

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, 

My previous PR https://github.com/liferay-core-infra/liferay-portal/pull/4434/commits/b2ac8c0415e9586b7cb4bd5bed1376e9839cf7b9=caused a regression, please see   https://issues.liferay.com/browse/LPS-184624 and https://issues.liferay.com/browse/LPS-184522, and I would revert what I did for now.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:workflow-metrics

**Comment by jeffwu0724** [comment]
Hi @zhangyan0701 

Could you help me take tare of this PR when the test is ready? 
Thanks!

**Comment by zhangyan0701** [comment]
ci:test:kaleo-forms

**Comment by zhangyan0701** [comment]
Semantic versioning issue:
```
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.kernel.service                  MINOR      22.0.0     22.0.0     22.1.0     VERSION INCREASE REQUIRED
[beanshell] 	<   class      com.liferay.portal.kernel.service.ServiceContextFactory
[beanshell] 		+   method     getInstance(java.lang.String,com.liferay.portal.kernel.upload.UploadPortletRequest)
[beanshell] 			+   access     static
[beanshell] 			+   return     com.liferay.portal.kernel.service.ServiceContext
[beanshell] 
[stopwatch] [run.batch.test.action: 6.585 sec]
     [echo] Semantic versioning is incorrect.
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-05/test-1-33/test-portal-acceptance-pullrequest(master)/3562/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

Other failures are unrelated.

**Comment by gaborlovasdotcom** [comment]
ci:test:saml

**Comment by Kvale1733** [comment]
Looks like this might just require republishing affected components since several of the affected tests are passing on upstream.

Left a comment here: https://liferay.slack.com/archives/CLA7D1CNL/p1684196095639219 to the release team about this.
This revert will likely not be needed.

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
