### PR TITLE
[Static Reference]LPS-170377 Convert method references to field references in module wiki-web

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
Semantic Versioning error:
```
     [exec] > Task :apps:wiki:wiki-api:baseline
     [exec] [Baseline Warning] Bundle Version Change Recommended: 14.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.wiki.api-13.0.1.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.wiki.api/13.0.0/e07dc764653e01e3b9b1fcae60354f8f9c9b8f64/com.liferay.wiki.api-13.0.0.jar
```
Full console log:
https://testray.liferay.com/reports/production/logs/2022-12/test-1-26/test-portal-acceptance-pullrequest(master)/6250/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

Other failures are unrelated.

**Comment by W2jx** [comment]
It's strange. I don't think I have modified the file in module wiki-api. But I will fix it.

**Comment by W2jx** [comment]
Force-Push is just to rebase and fix the Semantic Versioning error.

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
no conflicts(2022/12/8 9:30)

**Comment by W2jx** [comment]
no conflicts(12/9 9:47)

**Pull request closed without merging**
