### PR TITLE
LPS-175778 Inline Mail and Trash service.xml into ServiceBuilder

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from #3558
for comment here: https://github.com/liferay-core-infra/liferay-portal/pull/3558#issuecomment-1438934705

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
@julschong No regressions found. Tested on 7.0-7.3 locally. No additional changes were generated. SF issue is unrelated.

**Comment by tinatian** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
Found this ticket for the SF issue: [LPS-176344](https://issues.liferay.com/browse/LPS-176344). It's not unique to this PR.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130731

**Pull request closed without merging**
