### PR TITLE
[Rename Classes] LPS-166958 Rename classes in modules fragment-api、fragment-impl、fragment-collection-filter-api、fragment-collection-filter-impl

### PR DESCRIPTION
**Pull request by W2jx**
Detail: https://github.com/liferay-core-infra/liferay-portal/pull/2363

### CODE REVIEW

**Comment by W2jx** [comment]
Force-Push is just to resolve the conflict about file modules/apps/fragment/fragment-api/bnd.bnd

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@W2jx semver error:

```
  [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/fragment/fragment-collection-filter-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.fragment.collection.filter             MAJOR      1.3.0      1.2.0      2.0.0      VERSION INCREASE REQUIRED
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-30/test-portal-acceptance-pullrequest(master)/5341/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

possible regression:

```
[exec] com.liferay.headless.delivery.resource.v1_0.test.StructuredContentResourceTest > testGetSiteStructuredContentsPageWithFilterDoubleEquals FAILED
     [exec]     java.lang.AssertionError: expected:<1> but was:<0>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:633)
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.BaseStructuredContentResourceTestCase.assertEquals(BaseStructuredContentResourceTestCase.java:3243)
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.BaseStructuredContentResourceTestCase.testGetSiteStructuredContentsPageWithFilterDoubleEquals(BaseStructuredContentResourceTestCase.java:1462)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-30/test-portal-acceptance-pullrequest(master)/5341/modules-integration-mysql57-jdk8/0/5/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
@W2jx @catarineaguiar The integration test is also failing on master ID 4381b5feed7b396c5b8c3c12cceacbb13b2bda4d, I'm going to send this PR out with rerunning baseline.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126175

**Pull request closed without merging**
