### PR TITLE
LPS-148926 Move istack-commons-runtime.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @koor4356, Can you please scan these test results when they are ready? Thx

**Comment by rafaprax** [comment]
Hey @shuyangzhou,

As we removed the jaxws-rt dependency, now It's safe to move the istack-commons-runtime.

PS: I just resent this pr https://github.com/liferay-core-infra/liferay-portal/pull/437 without changes.

Thx

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
@rafaprax 
This looks good, thanks!

**Comment by rafaprax** [comment]
@shuyangzhou , this PR is ready for your review. Thanks!

**Comment by shuyangzhou** [comment]
@rafaprax I still reference to istack from ```com.sun.istack                           [com.sun.xml.bind.api, com.sun.xml.bind.marshaller, com.sun.xml.bind.v2.runtime.output, com.sun.xml.bind.v2, com.sun.xml.bind.v2.runtime.reflect, com.sun.xml.bind.v2.model.impl, com.sun.xml.bind.v2.runtime, com.sun.xml.bind.v2.runtime.unmarshaller]```
This might be solved by your the other lib removal pull, if so we can recheck this after the other pull, otherwise this would need further pre-cleanup.

**Comment by rafaprax** [comment]
Hey @shuyangzhou, Thanks for catching that. It is a jaxb-runtime.jar dependency. I'll work on the jaxb extraction first.

**Pull request closed without merging**
