### PR TITLE
[Component with its own class name as service type] LPS-195858 Refactor Registry classe from Workflow and Search component

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Related: https://liferay.atlassian.net/browse/LPS-195858

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:search

**Comment by Valmir-unicap** [comment]
ci:test:workflow

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Review by rafaprax — APPROVED** [review]

**Comment by catarineaguiar** [comment]
no regressions found

**Pull request closed without merging**
