### PR TITLE
[Method Reference Static]Lps 183181

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-183181

Apply this pattern: https://github.com/liferay-core-infra/liferay-portal/pull/4488#issuecomment-1542131885

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:data-engine

**Comment by slnn** [comment]
ci:test:security

**Comment by slnn** [comment]
ci:test:comment

**Comment by slnn** [comment]
ci:test:document

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
