### PR TITLE
[Components with more than 1 service] LPS-182982 Refactor TableFDSView components in Commerce part 2

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
Pull previous approved, made the changes requested by Brian in https://github.com/brianchandotcom/liferay-portal/pull/135208

**Comment by catarineaguiar** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
