### PR TITLE
[Method References 3] LPS-179870  journal-web

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-179870

Hi @dantewang, 

I noticed the property `(view=public)` and` (view=private)` is only used by this class. 

Should I remove the properties and directly reference the class  `PublicLayoutsItemSelectorView` and `PrivateLayoutsItemSelectorView`?

### CODE REVIEW

**Comment by dantewang** [comment]
@JanisZhang Could you check why this class needs to reference them? After your change, the field references are actually not used, which is what we want to avoid.

**Comment by Kvale1733** [comment]
ci:test:lima

**Comment by JanisZhang** [comment]
> @JanisZhang Could you check why this class needs to reference them? After your change, the field references are actually not used, which is what we want to avoid.

Hi @dantewang , it seems like this reference is used to declare dependency.  see 1682bb84abcc328bfbaee8ef1c2a42296b5728a7

**Comment by dantewang** [comment]
> > @JanisZhang Could you check why this class needs to reference them? After your change, the field references are actually not used, which is what we want to avoid.
> 
> Hi @dantewang , it seems like this reference is used to declare dependency. see [1682bb8](https://github.com/liferay-core-infra/liferay-portal/commit/1682bb84abcc328bfbaee8ef1c2a42296b5728a7)

@JanisZhang Yes, this should be the case. But why does this class need to depend on those services, when it doesn't use them directly? There should be a call chain which is hidden... Could you try to find it out, so we can see if there's any way to avoid introducing the unused references.

**Comment by zhangyan0701** [comment]
ci:test:echo

**Comment by JanisZhang** [comment]
> > > @JanisZhang Could you check why this class needs to reference them? After your change, the field references are actually not used, which is what we want to avoid.
> > 
> > 
> > Hi @dantewang , it seems like this reference is used to declare dependency. see [1682bb8](https://github.com/liferay-core-infra/liferay-portal/commit/1682bb84abcc328bfbaee8ef1c2a42296b5728a7)
> 
> @JanisZhang Yes, this should be the case. But why does this class need to depend on those services, when it doesn't use them directly? There should be a call chain which is hidden... Could you try to find it out, so we can see if there's any way to avoid introducing the unused references.

Hi @dantewang,

IMHO, the short answer is no hide call chain in this case, the declared dependency is used to verify whether the module `Liferay Layout Item Selector Web` is stopped. 

I looked into the ticket https://issues.liferay.com/browse/LPS-65240 which adds this declared dependency,
it pointed out a bug 
> Liferay Layout Item Selector Web: **Button to select pages** is still shown when this module is stopped.

To avoid the portal getKey from  `JournalDisplayPageFormNavigatorEntry` while the Layout Item Selector Web module has been stopped, the author declared the component LayoutsItemSelectorView. 

In this way, if the module is stopped -> the class cannot get the declared service -> JSP can not get the key "display-page" from `JournalDisplayPageFormNavigatorEntry` -> **Display page** Button won't be shown.

```
public String getKey() {
		return "display-page";
	}
```
Before 
image_480

After stopped the module, no display page button.
image_360

Thanks!

**Comment by dantewang** [comment]
@JanisZhang I see, thanks!

**Comment by dantewang** [comment]
@JanisZhang Why can't `JournalDisplayPageFormNavigatorEntry` just reference this?

```
	@Reference(
		target = "(osgi.web.symbolicname=com.liferay.layout.item.selector.web)"
	)
	private ServletContext _servletContext;
```

**Comment by dantewang** [comment]
@JanisZhang OK it's already referencing the servlet context of its own module, but this doesn't prevent it to depend on the servlet context of another module. Please double check, thanks.

**Comment by JanisZhang** [comment]
Hi @dantewang, I removed the unused field reference and added one extra ServletContext. And it works in my local. Thanks!

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:echo

**Comment by JanisZhang** [comment]
ci:test:lima

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:echo

**Comment by JanisZhang** [comment]
ci:test:lima

**Comment by JanisZhang** [comment]
ci:stop

**Pull request closed without merging**
