### PR TITLE
[Remove Stream/Optional usage] LPS-172109 modules: Layout | Part 2

### PR DESCRIPTION
**Pull request by JanisZhang**
previous: https://github.com/liferay-core-infra/liferay-portal/pull/2918

https://issues.liferay.com/browse/LPS-172109

Hi @dantewang, I will send 2 PRs for easy review. The pr is going big after I split my original commits. Thanks!

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Regression found:

**Error "Content Page Editor is temporarily unavailable" occurs.**
content page editor

Error in portal console:
```
[beanshell] 2023-01-06 09:07:04.999 ERROR [http-nio-8080-exec-1][PortletRequestDispatcherImpl:304] Unable to dispatch request: com.liferay.segments.exception.NoSuchExperienceException: No SegmentsExperience exists with the primary key -1
[beanshell] 2023-01-06 09:07:04.999 ERROR [http-nio-8080-exec-1][PortletServlet:117] null
[beanshell] javax.portlet.PortletException: javax.servlet.ServletException: com.liferay.segments.exception.NoSuchExperienceException: No SegmentsExperience exists with the primary key -1
```

**Pull request closed without merging**
