### PR TITLE
LPS-192103 SegmentsEntryRel reindex process causes a very large number of cache replication events

### PR DESCRIPTION
**Pull request by holatuwol**
## Motivation

We have a customer on an earlier version of 7.4.13 who experiences outages due to their cluster being flooded with with cache replication messages stemming from the `SegmentsEntryReindexMessageListener`.

## Proposed solution

Initially, the idea was to work around the issue by wrapping the `SegmentsEntryReindexMessageListener` code inside of a transaction, thus allowing us to do a single `REMOVE_ALL` in order to suppress the thousands of messages. This is what you see in the first two commits.

However, this alone didn't work on the older version of Liferay; testing showed that there were still a lot of cluster messages, scaling with the number of entities that had been added/deleted by the reindex.

Investigation revealed that the underlying flood of cluster replication messages was due to the cluster replication changes that were added to resolve LPS-122957 (`EntityCacheImpl`) and LPS-131544 (`FinderCacheImpl`).

* https://github.com/liferay/liferay-portal/commit/98beb2d5586cd94cc15ecccb9eef6cdd9d89ba5c
* https://github.com/liferay/liferay-portal/commit/42fd875e94de4d0831556704774a72d81ad2a5f7

The changes to the `EntityCacheImpl` were partially reverted when resolving LPS-181252, and applying those changes substantially reduced the number of cluster replication messages, but there were still more cache replication messages than expected.

* https://github.com/liferay/liferay-portal/commit/8fd0c8d9a7b95991bad4c12254ed61369e3c07f0

Analyzing the code in `FinderCacheImpl`, I realized that it wasn't taking transactional cache into account. After applying a change to account for the transactional cache, we observe that the cache replication messages drop to the level expected.

## Steps to verify

Please see the steps described in https://liferay.atlassian.net/browse/LPS-192103

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
no regressions were found.

The bug is not reproducible with your changes

**Comment by holatuwol** [comment]
Accidentally force pushed to this branch before the last ci:test, will resend later.

**Pull request closed without merging**
