### PR TITLE
[Replace Non-Blocking Usage] LPS-198653 Remove unused deprecated class FormNavigatorEntryUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(10/12 9:54)

**Comment by W2jx** [comment]
Hi @dantewang , this class was directly removed.

**Comment by dantewang** [comment]
@W2jx For breaking changes, we have a new workflow: https://liferay.atlassian.net/wiki/spaces/ENGR/pages/2489483265/Process+to+register+breaking+changes+in+commits

And an example:
https://github.com/liferay/liferay-portal/commit/ea7604f6ad3807435facf2bbfbfa0ef7ba9901e3

cc @JanisZhang @LisztLiszt @slnn @yuhai

**Comment by W2jx** [comment]
Forced push to modify commit message, no logic changes, no need to rerun test.

**Comment by W2jx** [comment]
Hi @dantewang , I resend the code.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Comment by W2jx** [comment]
ci:forward:force

**Pull request closed without merging**
