### PR TITLE
remove_deprecated_for_portal_kernel_part_Nine

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is remove_deprecated_for_portal_kernel_part_Nine.
I split this into two part, one is about changes in "portal-kernel/src/com/liferay/portal/kernel/search", and it was submitted to search team for review, see https://github.com/liferay-search/liferay-portal/pull/416.
can also see https://github.com/liferay-core-infra/liferay-portal/pull/623 for reference. 
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina.

**Comment by catarineaguiar** [comment]
@vicnate5 will not have time to review this one today.

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116424

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
