### PR TITLE
[Remove Spring extender usages] LPS-159289

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang

### CODE REVIEW

**Comment by yuhai** [comment]
@zhangyan0701, please scan the test result after ci test finished. Thanks.

**Comment by dantewang** [comment]
@yuhai The message of you last commit (https://github.com/liferay-core-infra/liferay-portal/pull/1238/commits/db2295f7ee3e5a000b0df11d882e56c93a9b7b10) has a git hash which does not match any other commit in this PR.

Are you referencing https://github.com/liferay-core-infra/liferay-portal/pull/1238/commits/2a32898bfd5bc62393bcb64d461125da873977f6?

**Comment by yuhai** [comment]
> @yuhai The message of you last commit ([db2295f](https://github.com/liferay-core-infra/liferay-portal/commit/db2295f7ee3e5a000b0df11d882e56c93a9b7b10)) has a git hash which does not match any other commit in this PR.
> 
> Are you referencing [2a32898](https://github.com/liferay-core-infra/liferay-portal/commit/2a32898bfd5bc62393bcb64d461125da873977f6)?

@dantewang, yes. Sorry. I will push force it.

**Comment by yuhai** [comment]
@dantewang, just push force it.

**Review by dantewang — APPROVED** [review]
@tinatian Code looks good to me, QA notified.

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@yuhai For this commit https://github.com/liferay-core-infra/liferay-portal/pull/1238/commits/39d04ef49956bd64a1b5ec258371e8da65790133, why service builder remove it?

**Comment by dantewang** [comment]
@tinatian My guess is, since it's referencing other LocalService in the same module, it's possible to cause a circular reference between 2 local services. It's OK when using Spring, but needs fix when using DS. It's hard for Service Builder to know when should it keep the reference and it's hard for developer to break the circular dependency manually if it keeps the reference in the generated class.

**Comment by yuhai** [comment]
> @yuhai For this commit [39d04ef](https://github.com/liferay-core-infra/liferay-portal/commit/39d04ef49956bd64a1b5ec258371e8da65790133), why service builder remove it?

@tinatian, sorry, I don't know the specific reason. It seems the commit(9f2bd5c378d2763fc99732f1ca7c19bda7f135e7) controlled this.

cc @dantewang

**Comment by yuhai** [comment]
> @tinatian My guess is, since it's referencing other LocalService in the same module, it's possible to cause a circular reference between 2 local services. It's OK when using Spring, but needs fix when using DS. It's hard for Service Builder to know when should it keep the reference and it's hard for developer to break the circular dependency manually if it keeps the reference in the generated class.

@tinatian, I just encountered @dantewang mentioned issue, please see CommerceOrderLocalServiceImpl and CommerceOrderItemLocalServiceImpl. They are referring to each other.

**Comment by tinatian** [comment]
@yuhai @dantewang  The last commit is weird. If this is caused by potential circular dependency, then please fix this before changing spring to ds, so that you won't have this weird commit in.

Please resend.

Thanks.
Tina

**Pull request closed without merging**
