### PR TITLE
LPS-180158 Upgrade spring-web version to 5.2.24

### PR DESCRIPTION
**Pull request by ling-alan-huang**
This PR can fix SF issue:

`Library 'org.springframework:spring-web:5.2.22.RELEASE' contains known vulnerabilities(Pivotal Spring Framework contains unsafe Java deserialization methods, https://github.com/advisories/GHSA-4wrc-f8pq-fpqp): /home/alan/liferay_code/master/liferay-portal/modules/dxp/apps/osb/osb-faro/osb-faro-engine-client/build.gradle (SourceCheck:LibraryVulnerabilitiesCheck)`

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
No regressions found.

**Comment by shuyangzhou** [comment]
ci:forward:force

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139857

**Pull request closed without merging**
