### PR TITLE
LPS-197375 Remove ModelResourcePermissionDefinition

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
rerun relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:help

**Comment by julschong** [comment]
ci:test:blogs

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:blogs

**Comment by Kvale1733** [comment]
@julschong No regressions. Just a semver issue for portal-kernel. 
```
  [exec] > Task :baseline
     [exec] [Baseline Warning] Bundle Version Change Recommended: 126.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/125.0.0/49270831149f614840acf47c66b29da350bd9011/com.liferay.portal.kernel-125.0.0.jar
     [exec] Gradle build finished at 2023-09-30 00:47:14.790.
     [exec] 
```
[Log](https://testray.liferay.com/reports/production/logs/2023-09/test-1-25/test-portal-acceptance-pullrequest(master)/3581/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
rebased and reran for semver

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong The semver issue is fixed. No regressions.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141821

**Pull request closed without merging**
