### PR TITLE
Revert "LPS-169259 Remove "immediate = true" from module portal-setti…

### PR DESCRIPTION
**Pull request by slnn**
Hi @tinatian @dantewang 

The commit of [LPS-169259](https://issues.liferay.com/browse/LPS-169259) which removed immediate=true usage from modules/apps/portal-settings caused this issue [LPS-169735](https://issues.liferay.com/browse/LPS-169735
), the ci test results of origin pull of LPS-169259 did not expose this issue because related tests are not included in the relevant test suite.

By the way, this module modules/apps/portal-settings should belong to the security batch, so I move it to security ticket: https://issues.liferay.com/browse/LPS-168433

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:security

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:security

**Comment by JoyceWang08211** [comment]
> ### ❌ ci:test:security - 244 out of 254 jobs passed in 1 hour 44 minutes
> Click here for more details.
> ##### Test bundle downloads:
> * [liferay-portal-bundle-tomcat.tar.gz](https://files.liferay.com/private/bundles/test-1-29/jobs/test-portal-acceptance-pullrequest(master)/builds/5572/liferay-portal-bundle-tomcat.tar.gz) (mirrors: [dlc](http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-29/jobs/test-portal-acceptance-pullrequest(master)/builds/5572/liferay-portal-bundle-tomcat.tar.gz), [lax](http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-29/jobs/test-portal-acceptance-pullrequest(master)/builds/5572/liferay-portal-bundle-tomcat.tar.gz))

The portal settings issues are resolved. It's safe to forward.
cc @slnn and @gaborlovasdotcom

**Comment by JoyceWang08211** [comment]
ci:forward

**Pull request closed without merging**
