### PR TITLE
[Method References 2] LPS-167730 Remove method reference in class PortletRegistryImpl

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4067

### CODE REVIEW

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(4/17 8:08)

**Comment by W2jx** [comment]
no conflicts(4/18 9:28)

**Comment by W2jx** [comment]
no conflicts(4/19 8:03)

**Comment by W2jx** [comment]
no conflicts(4/20 7:56)

**Comment by W2jx** [comment]
no conflicts(4/21 8:22)

**Comment by W2jx** [comment]
no conflicts(4/24 10:47)

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4344

**Pull request closed without merging**
