### PR TITLE
[TS] LPS-144149

### PR DESCRIPTION
**Pull request by rafaprax**
https://liferay.atlassian.net/browse/LPS-144149

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@rafaprax This causes a startup error. All tests failed to run because of it.

```
eanshell] 2023-11-14 20:35:47.871 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:212] Processing speedwell-theme.war
[beanshell] 2023-11-14 20:38:02.730 WARN  [main][PortalInstanceLifecycleListenerManagerImpl:195] Unable to register portal instance {"mvccVersion": 0, "companyId": 6540265148708392327, "userId": 0, "userName": "", "createDate": "Tue Nov 14 20:35:32 GMT 2023", "modifiedDate": "Tue Nov 14 20:35:32 GMT 2023", "webId": "liferay.com", "mx": "liferay.com", "homeURL": "", "logoId": 0, "maxUsers": 0, "active": true, "name": "Liferay", "legalName": "", "legalId": "", "legalType": "", "sicCode": "", "tickerSymbol": "", "industry": "", "type": "", "size": "", "indexNameCurrent": "", "indexNameNext": ""}
[beanshell] com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: java.lang.IllegalArgumentException: org.hibernate.QueryException: in expected: friendlyURLEntryLocalization [SELECT friendlyURLEntryLocalization FROM FriendlyURLEntryLocalization friendlyURLEntryLocalization WHERE friendlyURLEntryLocalization.groupId = ? AND friendlyURLEntryLocalization.classNameId = ? AND friendlyURLEntryLocalization.urlTitle = ? ORDER BY friendlyURLEntryLocalization.friendlyURLEntryLocalizationId ASC]
[beanshell] 	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.processException(BasePersistenceImpl.java:640) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.friendly.url.service.persistence.impl.FriendlyURLEntryLocalizationPersistenceImpl.findByG_C_U(FriendlyURLEntryLocalizationPersistenceImpl.java:1128) ~[?:?]
[beanshell] 	at com.liferay.friendly.url.service.persistence.impl.FriendlyURLEntryLocalizationPersistenceImpl.findByG_C_U(FriendlyURLEntryLocalizationPersistenceImpl.java:988) ~[?:?]
[beanshell] 	at com.liferay.friendly.url.service.persistence.impl.FriendlyURLEntryLocalizationPersistenceImpl.fetchByG_C_U_First(FriendlyURLEntryLocalizationPersistenceImpl.java:1194) ~[?:?]
[beanshell] 	at com.liferay.friendly.url.service.impl.FriendlyURLEntryLocalServiceImpl.fetchFriendlyURLEntry(FriendlyURLEntryLocalServiceImpl.java:306) ~[?:?]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_381]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_381]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_381]
[beanshell] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40) ~[portal-impl.jar:?]
[beanshell] 	at com.sun.proxy.$Proxy1109.fetchFriendlyURLEntry(Unknown Source) ~[?:?]
[beanshell] 	at com.liferay.layout.internal.service.LayoutLocalServiceWrapper._fetchLayoutByFriendlyURL(LayoutLocalServiceWrapper.java:65) ~[?:?]
[beanshell] 	at com.liferay.layout.internal.service.LayoutLocalServiceWrapper.fetchLayoutByFriendlyURL(LayoutLocalServiceWrapper.java:37) ~[?:?]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_381]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_381]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_381]
[beanshell] 	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:57) ~[portal-kernel.jar:?]
[beanshell] 	at com.sun.proxy.$Proxy1120.fetchLayoutByFriendlyURL(Unknown Source) ~[?:?]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_381]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_381]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_381]
[beanshell] 	at com.liferay.staging.internal.service.LayoutLocalServiceStagingAdvice$LayoutLocalServiceStagingInvocationHandler._invoke(LayoutLocalServiceStagingAdvice.java:862) ~[?:?]
[beanshell] 	at com.liferay.staging.internal.service.LayoutLocalServiceStagingAdvice$LayoutLocalServiceStagingInvocationHandler.invoke(LayoutLocalServiceStagingAdvice.java:701) ~[?:?]
[beanshell] 	at com.sun.proxy.$Proxy1155.fetchLayoutByFriendlyURL(Unknown Source) ~[?:?]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
```
[Log](https://testray.liferay.com/reports/production/logs/2023-11/test-1-40/test-portal-acceptance-pullrequest(master)/7407/functional-smoke-startup-tomcat90-mysql57-jdk8/0/7/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Comment by dantewang** [comment]
Rebased and resent to https://github.com/liferay-core-infra/liferay-portal/pull/6355, this should be the valid fix.

**Pull request closed without merging**
