### PR TITLE
LPD-25523 Adapt tests using hard-coded test password in Logging component 

### PR DESCRIPTION
**Pull request by Valmir-unicap**
- Ticket: https://liferay.atlassian.net/browse/LPD-25523

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:core-functional

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:report:2568308888

**Comment by tinatian** [comment]
No unique failures according to test report

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
