### PR TITLE
LPS-194570 Merge ColorSchemeFactory interface and impl into Util in kernel

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@julschong test with unique failure:

```
     [exec] com.liferay.knowledge.base.internal.exportimport.data.handler.test.KBArticleStagedModelDataHandlerTest > testCleanAssetCategoriesAndTags FAILED
     [exec]     java.lang.AssertionError: [{"mvccVersion": 1, "ctCollectionId": 0, "uuid": "89bf704a-097c-5868-98a4-9e4698c9fe20", "tagId": 33630, "groupId": 33590, "companyId": 20096, "userId": 20123, "userName": "Test Test", "createDate": "Sat Aug 26 04:09:02 GMT 2023", "modifiedDate": "Sat Aug 26 04:09:01 GMT 2023", "name": "wh8tywoe", "assetCount": 1, "lastPublishDate": null}]
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
     [exec]     	at com.liferay.exportimport.test.util.lar.BaseStagedModelDataHandlerTestCase.testCleanAssetCategoriesAndTags(BaseStagedModelDataHandlerTestCase.java:193)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-08/test-1-40/test-portal-acceptance-pullrequest(master)/5505/modules-integration-mysql57-jdk8/2/11/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine, the error seems unrelated, I rebased and try ci again. Hopefully it goes away

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relecant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong yeah, it was flaky. 

No regressions found.

**Pull request closed without merging**
