### PR TITLE
[Method Reference Static]Lps 183845

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-183845

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by slnn** [comment]
Hi @dantewang 

The previous pull means this one: https://github.com/liferay-core-infra/liferay-portal/pull/4485, right?

I do not use the same pattern in the current pull to inline the methods of the Util class to different *Tag classes, because we need to change many classes more than two classes if we do that.

Which one do you prefoer?

**Comment by slnn** [comment]
Resend in https://github.com/liferay/liferay-portal/pull/5427

**Pull request closed without merging**
