### PR TITLE
[Fix Test] LPS-200081 Fix the test

### PR DESCRIPTION
**Pull request by W2jx**
The field _authToken in class AuthTokenUtil has been removed in task https://liferay.atlassian.net/browse/LPS-200081, but the test was missed.

Hi @zhangyan0701,  could you please help me check this test, thanks!

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(11/7 9:34)

**Comment by zhangyan0701** [comment]
Hi @W2jx 

I didn't find out the test on upstream neither. I run it in https://github.com/zhangyan0701/liferay-portal/pull/568 and it passed there.

**Comment by W2jx** [comment]
no conflicts(11/8 10:05)

**Comment by dantewang** [comment]
Since it passed, I sent it to BChan: https://github.com/brianchandotcom/liferay-portal/pull/143457

**Pull request closed without merging**
