### PR TITLE
[Component with its own class name as service type] LPS-197867 Refactor components from dynamic-data-mapping modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Previous pull: https://github.com/brianchandotcom/liferay-portal/pull/145864

Ticket: https://liferay.atlassian.net/browse/LPS-197867

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:forms

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
