### PR TITLE
LPS-161307 Remove PatcherUtil from modules

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from #1440

### CODE REVIEW

**Comment by tinatian** [comment]
@julschong What did you change compared to last commit?

Tina

**Comment by tinatian** [comment]
@julschong Never mind, I saw it, you changed private to protected.

Tina

**Comment by tinatian** [comment]
@julschong Code looks good to me, wait for QA to scan test result.
@catarineaguiar Please help me scan test result.

Tina

**Comment by catarineaguiar** [comment]
@julschong this [failure](https://github.com/liferay-core-infra/liferay-portal/pull/1440#issuecomment-1225286870) is still happening:

```
 [junit] Testcase: testScanXMLLog(com.liferay.portal.log.assertor.PortalLogAssertorTest):	FAILED
    [junit] 
    [junit] Portal log assert failure, see above log for more information: 
    [junit] failure in bulk execution:
    [junit] [0]: index [liferay-20097-workflow-metrics-nodes], type [WorkflowMetricsNodeType], id [WorkflowMetricsNodeb56235d6bc70c8195ec484f5fd9c6e6ebda86cd96f9af17eb47830207075c908], message [[liferay-20097-workflow-metrics-nodes/NQrQWHmESDGN9BS0pbyF1g] ElasticsearchException[Elasticsearch exception [type=index_not_found_exception, reason=no such index [liferay-20097-workflow-metrics-nodes]]]]
    [junit] junit.framework.AssertionFailedError: 
    [junit] failure in bulk execution:
    [junit] [0]: index [liferay-20097-workflow-metrics-nodes], type [WorkflowMetricsNodeType], id [WorkflowMetricsNodeb56235d6bc70c8195ec484f5fd9c6e6ebda86cd96f9af17eb47830207075c908], message [[liferay-20097-workflow-metrics-nodes/NQrQWHmESDGN9BS0pbyF1g] ElasticsearchException[Elasticsearch exception [type=index_not_found_exception, reason=no such index [liferay-20097-workflow-metrics-nodes]]]]
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:171)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:86)
    [junit] 
    [junit] 
    [junit] Test com.liferay.portal.log.assertor.PortalLogAssertorTest FAILED
[stopwatch] [test.cmd: 0.919 sec]
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null445827686.properties
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-28/test-portal-acceptance-pullrequest(master)/4080/empty-temp-dir-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
rerunning ci:relevant
The issue of [empty-temp-dir-jdk8/0/0](https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/74563//consoleText) might be ci related

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
Okay, let's wait for the next results.

**Comment by catarineaguiar** [comment]
@julschong looks like the error was flaky. Thanks for checking.
Can you rebase to see if sf passes now?

**Comment by julschong** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@julschong the pulls is good to go.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122249

**Pull request closed without merging**
