### PR TITLE
Lps 150188

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-150118

/cc @dantewang @tinatian

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
