### PR TITLE
[OrderByComparator] LPD-25932 clean up unused OrderByComparator constructors and classes -- part one

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

As talked, this is the part One of removing unused OrderByComparator constructors and classes.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:help

**Comment by jeffwu0724** [comment]
ci:test:backend

**Comment by jeffwu0724** [comment]
ci:test:commerce

**Comment by jeffwu0724** [comment]
ci:report:2568757581

**Comment by jeffwu0724** [comment]
ci:report:2568758552

**Comment by jeffwu0724** [comment]
ci:report:2568804617

**Comment by jeffwu0724** [comment]
ci:report:2568757581

**Comment by jeffwu0724** [comment]
Hi @tinatian ,
By looking at
Testray Build:[[master] ci:test:sf - jeffwu0724 > liferay-core-infra - PR#6985 - 2024-05-14[17:11:35]](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2568682728), there is no result imported in testray.

This is a known issue reported in slack, please see https://liferay.slack.com/archives/C01MVBFRN0K/p1715722912355019

I will come back and analyze the test result when testray is back. I will keep working on part Two for now.

Thanks,
Jeff

**Comment by tinatian** [comment]
ci:test:backend

**Comment by tinatian** [comment]
ci:test:commerce

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:backend

**Comment by jeffwu0724** [comment]
ci:report:2568993784

**Comment by jeffwu0724** [comment]
ci:report:2569014012

**Comment by jeffwu0724** [comment]
ci:report:2569129258

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
commerce test: No unique regression found

**Comment by jeffwu0724** [comment]
ci:report:2569469072

**Comment by jeffwu0724** [comment]
commerce test: No unique regression found
backend:
https://testray.liferay.com/home/-/testray/case_results/2569131444/history -- passed locally
https://testray.liferay.com/home/-/testray/case_results/2569136054/history -- not unique
https://testray.liferay.com/home/-/testray/case_results/2569143191/history -- not unique
relevant test:
https://testray.liferay.com/home/-/testray/case_results/2569477225/history
```
[junit] 2024-05-16 17:34:53.303 INFO  [Arquillian-Connector-Thread][BundleStartStopLogger:68] STARTED 
com.liferay.document.library.web.test_1.0.0 [1571]
    [junit] 2024-05-16 17:35:20.488 WARN  [com.liferay.document.library.web.test-executor-thread][UploadServletRequestImpl:184] Unable to parse upload request: the request doesn't contain a multipart/form-data or multipart/mixed stream, content type header is null
```
This is related to `EditFileEntryMVCActionCommandTest.java`, this warning is happened in master, not unique to this PR

**Comment by jeffwu0724** [comment]
updated the ticket number with the subtask ticket number.
The previous result should be good enough

**Comment by tinatian** [comment]
@jeffwu0724 Close, please see my slack message

**Pull request closed without merging**
