### PR TITLE
[Spring Beans] LPS-200292 Merge IdenticalPhoneNumberFormatImpl into Util and move to portal-impl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(11/15 10:19)

**Comment by W2jx** [comment]
no conflicts(11/20 13:57)

**Comment by W2jx** [comment]
no conflicts(11/21 15:06)

**Comment by W2jx** [comment]
no conflicts(11/22 15:05)

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(11/27 9:10)

**Comment by zhangyan0701** [comment]
Semantic versioning issue:
```
     [exec] 	+   class      com.liferay.portal.util.PhoneNumberFormatUtil
     [exec] 		+   method     clone()
     [exec] 			+   access     protected
     [exec] 			+   return     java.lang.Object
     [exec] 		+   method     equals(java.lang.Object)
     [exec] 			+   return     boolean
     [exec] 		+   method     finalize()
     [exec] 			+   access     protected
     [exec] 			+   return     void
     [exec] 		+   method     format(java.lang.String)
     [exec] 			+   access     static
     [exec] 			+   return     java.lang.String
     [exec] 		+   method     hashCode()
     [exec] 			+   return     int
     [exec] 		+   method     strip(java.lang.String)
     [exec] 			+   access     static
     [exec] 			+   return     java.lang.String
     [exec] 		+   method     toString()
     [exec] 			+   return     java.lang.String
     [exec] 		+   method     validate(java.lang.String)
     [exec] 			+   access     static
     [exec] 			+   return     boolean
     [exec] [Baseline Warning] Bundle Version Change Recommended: 95.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-impl/portal-impl.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.impl/94.0.1/c8c399c96930cf822f3d6a0645522471afbd243c/com.liferay.portal.impl-94.0.1.jar
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-11/test-1-26/test-portal-acceptance-pullrequest(master)/12074/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

Other than this, no regressions found.

**Comment by W2jx** [comment]
will force-push

**Comment by W2jx** [comment]
only do semver, no need to rerun test

**Comment by W2jx** [comment]
no conflicts(11/28 10:07)

**Comment by W2jx** [comment]
Modify breaking chage report to remove unnecessary blank lines.

**Comment by dantewang** [comment]
@W2jx Please rebase packageinfo and forward to BChan, cc me and Tina, thanks!

**Comment by W2jx** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/144973. Thanks.

cc @dantewang  @tinatian

**Pull request closed without merging**
