### PR TITLE
[Remove Blocking usages]LPS-188899 portal-kernel | MimeTypesUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(7/4 14:30)

**Comment by W2jx** [comment]
no conflicts(7/5 13:57)

**Comment by W2jx** [comment]
no conflicts(7/6 8:08)

**Pull request closed without merging**
