### PR TITLE
LPS-147205 Move commons-discovery.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:test:default

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@rafaprax Code looks good to me, wait for QA to scan test results.

Tina.

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113473

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
