### PR TITLE
LPD-8464 remove unused reference _messageBus

### PR DESCRIPTION
**Pull request by titokenzo**

### CODE REVIEW

**Comment by titokenzo** [comment]
ci:test:sturtup

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by titokenzo** [comment]
ci:report:2542179343

**Comment by titokenzo** [comment]
ci:report:2541874811

**Comment by titokenzo** [comment]
ci:test:relevant

**Comment by titokenzo** [comment]
ci:report:2542680600

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/147522

**Pull request closed without merging**
