### PR TITLE
[Bug fix] LPS-143269

### PR DESCRIPTION
**Pull request by dantewang**
https://issues.liferay.com/browse/LPS-143269
@tinatian I'm unable to find the official integrity for Bootstrap﻿ 3.2.0, so I used 3.3.7 as replacement: https://getbootstrap.com/docs/3.3/getting-started/#download-cdn
cc @samuelkong

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:stop

**Comment by tinatian** [comment]
@dantewang Please modify versions.xsl first, and then generate versions.html to show the changes. Also I think 256 should be enough for a hash, any reason you use 384?

Please resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by dantewang** [comment]
@tinatian Got it. The hash is provided by official Bootstrap download page, I just copy & paste.

**Pull request closed without merging**
