### PR TITLE
[Round 4 Method Reference Static]Lps 182296

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-182296

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:help

**Comment by zhangyan0701** [comment]
ci:test:lima

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
@slnn See https://github.com/liferay-core-infra/liferay-portal/pull/4341

**Pull request closed without merging**
