### PR TITLE
Lps 174386

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@AliciaGarciaGarcia Could you please verify if this breaks https://issues.liferay.com/browse/LPS-173353? There are no steps on the ticket.

Thanks.
Tina

**Comment by AliciaGarciaGarcia** [comment]
Hi @tinatian 

I updated the steps of the ticket for knowledge purposes :)  
it seems the configuration works fine.
Thanks for improving the code!

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
Code conflicts with head of master, rebase at https://github.com/liferay-core-infra/liferay-portal/pull/3400.

**Pull request closed without merging**
