### PR TITLE
Lpd 20946 8 29 2

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:75258453

**Comment by tinatian** [comment]
ci:report:75420538

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:startup

**Comment by tinatian** [comment]
ci:test:object

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:5090268

**Comment by dantewang** [comment]
Several unique failures are real. See https://github.com/liferay-core-infra/liferay-portal/pull/7413

Changed from `return` to `continue`.

**Pull request closed without merging**
