### PR TITLE
[Bug fix] LPS-153486

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
https://github.com/zhangyan0701/liferay-portal/pull/362#issuecomment-1148305865

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the CI results? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go
@vicnate5 Could you please add test for this?

Thanks
Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by vicnate5** [comment]
Automation ticket https://issues.liferay.com/browse/LRQA-75578

**Pull request closed without merging**
