### PR TITLE
[Spring Beans] LPS-203968 Merge portal-impl PorletPreferencesModelListener logic to portal-configuration-module-configuration PortletPreferencesModelListener

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:echo

**Comment by julschong** [comment]
semver is not updated upstream. expecting this to fail semver

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/145490

**Pull request closed without merging**
