### PR TITLE
LPS-179573 Remove Stream and Optional usages in content-dashboard-web

### PR DESCRIPTION
**Pull request by dantewang**
Depend: https://github.com/liferay-core-infra/liferay-portal/pull/4036 otherwise there may be conflicts.

### CODE REVIEW

**Comment by Kvale1733** [comment]
@dantewang Regression found

com.liferay.content.dashboard.web.internal.portlet.action.GetContentDashboardItemInfoMVCResourceCommandTest
```
[exec] com.liferay.content.dashboard.web.internal.portlet.action.GetContentDashboardItemInfoMVCResourceCommandTest > testServeResource FAILED
     [exec]     java.lang.AssertionError: expected:<null> but was:<>
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.failNotEquals(Assert.java:834)
     [exec]         at org.junit.Assert.assertEquals(Assert.java:118)
     [exec]         at org.junit.Assert.assertEquals(Assert.java:144)
     [exec]         at com.liferay.content.dashboard.web.internal.portlet.action.GetContentDashboardItemInfoMVCResourceCommandTest.testServeResource(GetContentDashboardItemInfoMVCResourceCommandTest.java:378)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-03/test-1-38/test-portal-acceptance-pullrequest(master)/7089/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
@dantewang No regressions.

**Comment by julschong** [comment]
rebased here: https://github.com/liferay-core-infra/liferay-portal/pull/4049

**Pull request closed without merging**
