### PR TITLE
[Components with more than 1 service] LPS-185248 Refactor Asset components from remaining asset modules

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:auto-tagging

**Comment by GabrielHenriquedev** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:auto-tagging

**Comment by Kvale1733** [comment]
ci:test:auto-tagging

**Comment by Kvale1733** [comment]
ci:test:auto-tagging

**Comment by zhangyan0701** [comment]
Building portal failed with exception:
```
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:asset:asset-auto-tagger-google-cloud-natural-language-api:jar'.
     [exec] > Bundle com.liferay.asset.auto.tagger.google.cloud.natural.language.api-4.0.7.jar has errors
```
Full console log:
https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/6704/consoleFull

**Pull request closed without merging**
