### PR TITLE
LPS-156253 Some improvements for PTR-3109

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
After the analysis done in https://issues.liferay.com/browse/PTR-3109, they concluded that one of the problems is the large number of pages, so a possible solution could be not include in freemarker context the "NavItems" since it is not use at all for clients.

[Link to the PTR](https://issues.liferay.com/browse/PTR-3109)
[Link to the issue](https://issues.liferay.com/browse/LPS-156253)

Proposed Solution
----
Adds new configuration property on System Settings -> Template Engines -> FreeMarker Engine and System Settings -> Template Engines -> Velocity Engine to include or not the "NavItems" on template context.

Please let me know if you have any question.

### CODE REVIEW

**Comment by tinatian** [comment]
@zhangyan0701 Please help me scan test results.

Tina.

**Comment by ealonso** [comment]
Hey @tinatian @zhangyan0701,

Closing this one since we cannot remove the usage of navItems since it is used in all the themes.

Sorry about that.
Eudaldo

**Comment by ealonso** [comment]
Hey @tinatian  @zhangyan0701,

After talking with the client and wit the team, we think it can help some clients, so I'm reopening the pr.

Regards,
Eudaldo

**Comment by zhangyan0701** [comment]
Unit test [com.liferay.portal.tools.ConfigurationEnvBuilderTest](https://testray.liferay.com/home/-/testray/case_results/1882036386) failed with below error, this seems related:
```
    [junit] Testcase: testBuildContent(com.liferay.portal.tools.ConfigurationEnvBuilderTest):	FAILED
    [junit] Run "ant update-portal-osgi-configuration-properties". Missing: [configuration.override.com.liferay.portal.template.freemarker.configuration.FreeMarkerEngineConfiguration_includeNavItemsInTheContext=, configuration.override.com.liferay.portal.template.velocity.configuration.VelocityEngineConfiguration_includeNavItemsInTheContext=]
```
Jenkins Console: https://testray.liferay.com/reports/production/logs/2022-06/test-1-27/test-portal-acceptance-pullrequest(master)/3716/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by ealonso** [comment]
Hey @zhangyan0701,

Thanks you very much for helping with the tests.

@lfbesada Could you please take a look to https://github.com/liferay-core-infra/liferay-portal/pull/976#issuecomment-1162728249?

**Comment by ealonso** [comment]
Hey @zhangyan0701,

Please see c22240d

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
