### PR TITLE
[DL-tuning] LPS-154280

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, please see the test result from https://github.com/GinsonRen/liferay-portal/pull/613

### CODE REVIEW

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
@yuhai @tinatian no regressions were found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/118366

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
