### PR TITLE
[Remove Stream/Optional usage] LPS-175212 Remove usages of Stream for module: oauth2-provider-scope-spi

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:oauth2

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(2/10 9:06)

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130406

**Pull request closed without merging**
