### PR TITLE
[Company xml log] LPS-175340

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, @tinatian

### CODE REVIEW

**Comment by Kvale1733** [comment]
@yuhai No regressions found.

**Comment by yuhai** [comment]
@dantewang, I just pushed force the change in portal-kernel/bnd.bnd since the fix existed conflict. The latest master doesn't generate the version in bnd.bnd during "ant all" or "gradlew baseline".

**Comment by dantewang** [comment]
@yuhai After your change, there will be 2 `CompanyLogRoutingAppender` instances created by Log4J in the system, one for `.log` and the other for `.xml`. However, our logic in `CentralizedConfiguration` was designed based on the fact that there was only one `CompanyLogRoutingAppender` in the system. I believe the current change works, but it might be possible that the admin overrides the configuration so that the 2 `CompanyLogRoutingAppender` instances are pointing to 2 different location, breaking our logic to support `CompanyLogServlet`.

@tinatian What do you think?

**Comment by yuhai** [comment]
> @yuhai After your change, there will be 2 `CompanyLogRoutingAppender` instances created by Log4J in the system, one for `.log` and the other for `.xml`. However, our logic in `CentralizedConfiguration` was designed based on the fact that there was only one `CompanyLogRoutingAppender` in the system. I believe the current change works, but it might be possible that the admin overrides the configuration so that the 2 `CompanyLogRoutingAppender` instances are pointing to 2 different location, breaking our logic to support `CompanyLogServlet`.
> 
> @tinatian What do you think?

@dantewang, yes, the current fix needs to make sure filePattern is the same for CompanyLogRoutingAppender. I thought we may document the limit. If we support different locations for the two appenders, I will do the related changes.

**Comment by dantewang** [comment]
@yuhai I think we should make sure that the two appenders always use the same location. Otherwise, we may need to use only 1 appender and add xml layout support internally...

**Comment by tinatian** [comment]
@yuhai @dantewang Please resend.

Tina

**Pull request closed without merging**
