### PR TITLE
LPS-145927

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Hi @shuyangzhou,
 did you have a time to take a look to this PR?
Kind regards.

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@marianoalvarosaiz Please list detailed reproduced steps you used on the description of the ticket, I do not understand what the root problem is from the current description. You can also add test to expose the issue to show me what the problem is.

Thanks.
Tina.

**Comment by marianoalvarosaiz** [comment]
@tinatian I've updated the steps.

It's not easy to reproduce. 

What needs to be done is to create a _Language_en.properties_ file in a language hook, deploy it and restart the portal. After several restarts you may find that the overridden keys in _Language_en.properties_ aren't applied. 

The reason is because in _com.liferay.portal.deploy.hot.HookHotDeployListener.initLanguageProperties(String, ClassLoader, Element)_ we retrieve the locale based on the file's name (_Language_en.properties_) and we use to do so _LocaleUtil.fromLanguageId(localeKey, true, false)_

This method without any prior invocation determines that _**en**_ is not a valid locale because although it's a super locale, but we only have as enabled locales (_locales.enabled_ property) locales with language and country. So in an ideal environment without any other calls to _LocaleUtil.fromLanguageId_ deploying a hook properties file of a super locale will never work.

What makes it work most of the times is the method com.liferay.portal.language.LanguageResources._getSuperLocale(Locale)_ that calls _LocaleUtil.fromLanguageId_ with the validation parameter turned to false. That cause that successive calls to _LocaleUtil.fromLanguageId_ with that same language do return a Locale instead of null.

So the root problem is that sometimes after a restart a hook that uses superlocale in the file name isn't applied because the language isn't validated, but the root cause isn't the hook deploy listener mechanism, but the _LocaleUtil.fromLanguageId_ method that:

1. Changes its return values based on its previous calls (if those were made without validation).
2. Doesn't consider, without any previous call, _en_ as a valid locale even if we do have _en_US_ as a locale enabled in the property _locales.enabled_

**Comment by marianoalvarosaiz** [comment]
@dantewang

**Comment by dantewang** [comment]
@tinatian Yes, https://issues.liferay.com/browse/LPS-134002
I think we put this one aside after the [first attempt for a quick fix](https://github.com/tinatian/liferay-portal/pull/2424#issuecomment-950015104) and moved to other issues so we didn't continue with it.

Based on @marianoalvarosaiz's description, I think this is the same issue.

**Comment by tinatian** [comment]
@marianoalvarosaiz 
I believe this issue share the same reason as I comment at https://github.com/tinatian/liferay-portal/pull/2424#issuecomment-950015104. That is local cache "_locales" is not using in a right way.

In your fix, you changed it to only contain validated locals which is wrong, because the validation logic depends on current company and the company's locals, while this "_locales" cache is for all companies. This will cause issues when there is more than one company.

This local cache should contains all the locals no matter it is validated or not. Each time you check the "_locales" cache to retrieve a locale by its language id, if null is returned, you create your own locale. 

After you get the locale from languageId, then you do the validation check if required.

Could you please make this change and send it to me?

FYI@dantewang I think this is a little bit different than the other issue. Seems it is not triggering the loop.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by marianoalvarosaiz** [comment]
@tinatian see https://github.com/liferay-core-infra/liferay-portal/pull/324

**Pull request closed without merging**
