### PR TITLE
LPS-164986 Remove immediate from DDM and Forms modules

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
1. Upgrade tests failed due to an error thrown when view document in Document and Media portlet after upgrade:
```
2022-10-20 17:16:28.610 ERROR [http-nio-8080-exec-6][IncludeTag:128] Current URL /web/guest/document?p_p_id=com_liferay_document_library_web_portlet_DLPortlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&_com_liferay_document_library_web_portlet_DLPortlet_mvcRenderCommandName=%2Fdocument_library%2Fview_file_entry&_com_liferay_document_library_web_portlet_DLPortlet_redirect=http%3A%2F%2Flocalhost%3A8080%2Fweb%2Fguest%2Fdocument%3Fp_p_id%3Dcom_liferay_document_library_web_portlet_DLPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26_com_liferay_document_library_web_portlet_DLPortlet_mvcRenderCommandName%3D%252Fdocument_library%252Fview%26_com_liferay_document_library_web_portlet_DLPortlet_displayStyle%3Ddescriptive%26_com_liferay_document_library_web_portlet_DLPortlet_navigation%3Dhome%26_com_liferay_document_library_web_portlet_DLPortlet_folderId%3D0&_com_liferay_document_library_web_portlet_DLPortlet_fileEntryId=10487 generates exception: com.liferay.portal.kernel.exception.PortalException: java.lang.RuntimeException: java.lang.NullPointerException
java.lang.NullPointerException: null
```
Full console log:
https://testray.liferay.com/reports/production/logs/2022-10/test-1-39/test-portal-acceptance-pullrequest(master)/1179/functional-upgrade-tomcat90-mysql57-jdk8/0/0/liferay-log.txt.gz?authuser=0

2. When adding DDL record, error thrown after clicking Plus icon, and all the fields are missing.
```
    [exec] 2022-10-20 14:47:24.973 ERROR [http-nio-8080-exec-15][IncludeTag:128] Current URL /group/guest/~/control_panel/manage?p_p_id=com_liferay_dynamic_data_lists_web_portlet_DDLPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_dynamic_data_lists_web_portlet_DDLPortlet_mvcPath=%2Fedit_record.jsp&_com_liferay_dynamic_data_lists_web_portlet_DDLPortlet_redirect=%2Fgroup%2Fguest%2F%7E%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_dynamic_data_lists_web_portlet_DDLPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_p_mode%3Dview%26_com_liferay_dynamic_data_lists_web_portlet_DDLPortlet_redirect%3Dhttp%253A%252F%252Flocalhost%253A8080%252Fgroup%252Fguest%252F%257E%252Fcontrol_panel%252Fmanage%253Fp_p_id%253Dcom_liferay_dynamic_data_lists_web_portlet_DDLPortlet%2526p_p_lifecycle%253D0%2526p_p_state%253Dmaximized%2526p_p_mode%253Dview%2526_com_liferay_dynamic_data_lists_web_portlet_DDLPortlet_mvcPath%253D%25252Fview.jsp%2526_com_liferay_dynamic_data_lists_web_portlet_DDLPortlet_orderByCol%253Dmodified-date%2526_com_liferay_dynamic_data_lists_web_portlet_DDLPortlet_orderByType%253Dasc%2526_com_liferay_dynamic_data_lists_web_portlet_DDLPortlet_displayStyle%253Dlist%2526_com_liferay_dynamic_data_lists_web_portlet_DDLPortlet_cur%253D1%2526_com_liferay_dynamic_data_lists_web_portlet_DDLPortlet_delta%253D20%2526_com_liferay_dynamic_data_lists_web_portlet_DDLPortlet_description%253D%2526_com_liferay_dynamic_data_lists_web_portlet_DDLPortlet_name%253D%2526p_p_auth%253D837fGT0F%26_com_liferay_dynamic_data_lists_web_portlet_DDLPortlet_displayStyle%3Dlist%26_com_liferay_dynamic_data_lists_web_portlet_DDLPortlet_mvcPath%3D%252Fview_record_set.jsp%26_com_liferay_dynamic_data_lists_web_portlet_DDLPortlet_recordSetId%3D44066%26p_p_auth%3D837fGT0F&_com_liferay_dynamic_data_lists_web_portlet_DDLPortlet_recordSetId=44066&_com_liferay_dynamic_data_lists_web_portlet_DDLPortlet_formDDMTemplateId=0&p_p_auth=837fGT0F generates exception: com.liferay.portal.kernel.exception.PortalException: java.lang.RuntimeException: java.lang.NullPointerException
     [exec] java.lang.NullPointerException: null
```
Full console log:
https://testray.liferay.com/reports/production/logs/2022-10/test-1-38/test-portal-acceptance-pullrequest(master)/4398/functional-tomcat90-mysql57-jdk8/4/4/jenkins-console.txt.gz?authuser=0

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
ci:test:forms

**Comment by rafaprax** [comment]
I just changed the `getEditor` method to private. The test suite results are still valid. Thx

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by rafaprax** [comment]
Hey @shuyangzhou, this pr is ready for your review. Thx

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125137

**Pull request closed without merging**
