### PR TITLE
[MB Performance] LPS-152367 Make edit_message_attachement.jsp jspf

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:message-boards

**Comment by zhangyan0701** [comment]
The test failures are unrelated.

**Comment by GinsonRen** [comment]
@dantewang 

Portal version | Git ID/PR link | Session count | Meantime of Login | Meantime of Add MB Thread | DB CPU Usage (%) | Portal CPU Usage (%) | Session Count Change compare to baseline（%）
-- | -- | -- | -- | -- | -- | -- | --
BaseLine(4-27 master head) | a68e36aa26811402986b78a3cb69295032820417 | 11172 | 151 | 162 | 10,17,68 | 27,28,27 |  
LPS-X-MB-2 | https://github.com/GinsonRen/liferay-portal/pull/604 | 11292 | 16.8 | 55.6 | 8,12,18 | 26,27,27 | 1.07%

**Comment by tinatian** [comment]
@vicnate5 Could you please check with QA of Lima team to confirm we did not bring any regression here?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@austinchiang FYI

@tinatian This should be good, the MB suite passed and @zhangyan0701 checked the other failures.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
