### PR TITLE
[Replace Non-Blocking Usage] LPS-200634 followup

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace non-blocking ServiceProxyFactory usages by using Snapshot in `LayoutLocalServiceHelper`. Thanks.
https://liferay.atlassian.net/browse/LPS-200634

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Review by dantewang — APPROVED** [review]

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
