### PR TITLE
[JDK17] LPD-44991 and LPD-44993 petra unit tests

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
rebuild the test at https://github.com/jeffwu0724/liferay-portal/pull/582

**Comment by tinatian** [comment]
ci:report:96376394

**Comment by tinatian** [comment]
ci:forward:force

**Comment by tinatian** [comment]
@jeffwu0724 Your test failed, as there is no regression for this change and Dante tested it locally with JDK17, I am forwarding this.

**Pull request closed without merging**
