### PR TITLE
[Replace Non-Blocking Usage] LPS-198509 Replace non-blocking ServiceProxyFactory usages in classes AuthenticatedSessionManagerUtil, DeviceDetectionUtil and PhoneNumberFormatUtil

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5810

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
@W2jx semver error:

```
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.security.auth.session    MINOR      1.0.0      1.0.0      1.1.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.portal.kernel.security.auth.session.AuthenticatedSessionManagerUtil
     [exec] 		+   method     <init>()
     [exec] 			+   return     void
     [exec] 		+   method     setAuthenticatedSessionManager(com.liferay.portal.kernel.security.auth.session.AuthenticatedSessionManager)
     [exec] 			+   return     void
     [exec] [Baseline Warning] Bundle Version Change Recommended: 127.1.0
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-30/test-portal-acceptance-pullrequest(master)/8146/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
no conflicts(10/24 8:21)

**Comment by W2jx** [comment]
only do semver, no need to rerun test

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
