### PR TITLE
[Remove Spring extender usages] LPS-159489

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang,

This PR is to remove spring extender usage in commerce-notification-service, thanks!
https://issues.liferay.com/browse/LPS-159489

Previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/1246

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @catarineaguiar , Could you review the test results when they finish? Thank you!

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Review by dantewang — APPROVED** [review]
@tinatian Code looks good to me. CI result checked and no regression found.

**Comment by tinatian** [comment]
@JanisZhang Please see https://github.com/liferay-core-infra/liferay-portal/pull/1292 and resend.

Tina

**Pull request closed without merging**
