### PR TITLE
[OrderByComparator] LPD-26438 Clean up and Apply Singleton in journal module

### PR DESCRIPTION
**Pull request by Valmir-unicap**
- Ticket: https://liferay.atlassian.net/browse/LPD-26438
- Correction of: https://github.com/liferay-core-infra/liferay-portal/pull/7217

CC: @titokenzo

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:report:40302768

**Comment by Valmir-unicap** [comment]
The test `JournalArticleAutogenerateDDMKeyConfigurationUpgradeProcessTest` passed locally. 
screenshot-1721324450

**Comment by Valmir-unicap** [comment]
Review this PR first: https://github.com/liferay-core-infra/liferay-portal/pull/7269

**Review by dantewang — APPROVED** [review]

**Pull request closed without merging**
