### PR TITLE
[JDK17] LPD-45110 Upgrade AspectJ to fix ConfigurableUtilTest

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian ConfigurableUtilTest passed on JDK17 and JDK8 on my local. If removing the AspectJ usage in this case, the code may become hard to read and maintain.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:relevant

**Comment by tinatian** [comment]
ci:report:98752813

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7788

**Pull request closed without merging**
