### PR TITLE
[Remove Stream/Optional usage] LPS-171396 portal-search-api

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
@dantewang fomatting issue:

```
format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/dxp/apps/portal-search-tuning/portal-search-tuning-rankings-web/src/test/java/com/liferay/portal/search/tuning/rankings/web/internal/BaseRankingsWebTestCase.java expected:<....function.Consumer;
     [java] []
     [java] import javax.portle...> but was:<....function.Consumer;
     [java] [import java.util.stream.Stream;
     [java] ]
     [java] import javax.portle...>
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:444)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:286)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-37/test-portal-source-format/4355/source-format-current-branch-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by catarineaguiar** [comment]
No other regression.

**Comment by dantewang** [comment]
Force pushed to rebase and fix SF.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@ling-alan-huang I don't think the SF error is caused by incorrect formatting... Could you take a look?

**Comment by ling-alan-huang** [comment]
@petershin I don't understand the SF failure here, can you help us. Thanks.

**Comment by dantewang** [comment]
@ling-alan-huang @petershin By the way I ran `ant format-source-current-branch` before force pushing this PR this morning and it finished without error.

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
I can't reproduce it with `ant format-source-current-branch`.
Looks like it only happens in ci.

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
I tested rebasing [here](https://github.com/catarineaguiar/liferay-portal/pull/59) but it failed anyway.

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
@dantewang If this's an urgent PR, you can cherry-pick https://github.com/brianchandotcom/liferay-portal/pull/127944/commits/e564fc4d2f57da1d09d11b45caa799db53360582

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Since SF passes locally, sent to https://github.com/brianchandotcom/liferay-portal/pull/127978

**Pull request closed without merging**
