### PR TITLE
LPS-154230 Log4j Servlet

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:stop

**Comment by tinatian** [comment]
ci:test:help

**Comment by tinatian** [comment]
ci:test:backend

**Comment by tinatian** [comment]
Passed ci test at https://github.com/liferay-core-infra/liferay-portal/pull/1185.
Only trigger backend test to cover unit test change.

Tina

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
@tinatian no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121410

**Pull request closed without merging**
