### PR TITLE
[Replace Non-Blocking Usage] LPS-199426 PortletFileRepositoryUtil

### PR DESCRIPTION
**Pull request by JanisZhang**
After replacing ServiceProxyFactory with Snapshot in `PortletFileRepositoryUtil`, NPE happens during startup.

In short, the reason is `WorkflowMetricsPortalInstanceLifecycleListener` using `PortletFileRepositoryUtil` during startup. (see NPE stack https://github.com/liferay-core-infra/liferay-portal/pull/6121 )

In this PR, we postpone this by making `WorkflowMetricsPortalInstanceLifecycleListener` extending `InitialRequestPortalInstanceLifecycleListener`. Thanks.

previous: https://github.com/liferay-core-infra/liferay-portal/pull/6121

https://liferay.atlassian.net/browse/LPS-199426

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:workflow

**Comment by zhangyan0701** [comment]
There are some tests failed due to ElasticsearchStatusException about workflow-metrics during portal startup in upgrade test suite, might be flaky, I couldn't reproduce locally. Will run one more time.

**Comment by zhangyan0701** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
Hi Summer, can I take a look at failed test report? It probably caused by my change.😅 @zhangyan0701

**Comment by zhangyan0701** [comment]
Hi @JanisZhang 

Here is an example:
[LocalFile.AFSStoreUpgrade#ViewAFSStoreArchive621021](https://testray.liferay.com/home/-/testray/case_results/2460931428).
Error:
```
[beanshell] 2023-11-17 09:18:26.496 ERROR [com.liferay.portal.workflow.metrics.internal.petra.executor.WorkflowMetricsPortalExecutor-2][WorkflowMetricsPortalExecutor:63] java.lang.RuntimeException: org.elasticsearch.ElasticsearchStatusException: [liferay-10155-workflow-metrics-nodes/rc-CkcbfRP2e5Bguh-ybGA] ElasticsearchStatusException[Elasticsearch exception [type=index_not_found_exception, reason=no such index [liferay-10155-workflow-metrics-nodes]]]
[beanshell] java.lang.RuntimeException: org.elasticsearch.ElasticsearchStatusException: [liferay-10155-workflow-metrics-nodes/rc-CkcbfRP2e5Bguh-ybGA] ElasticsearchStatusException[Elasticsearch exception [type=index_not_found_exception, reason=no such index [liferay-10155-workflow-metrics-nodes]]]
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-11/test-1-34/test-portal-acceptance-pullrequest(master)/5229/functional-upgrade-tomcat90-sqlserver2017-jdk8/0/0/jenkins-console.txt.gz?authuser=0

But I wasn't able to reproduce it after trying several times. And the error didn't happen in the new upgrade tests.

**Comment by JanisZhang** [comment]
Thanks Summer! will take a look.

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by zhangyan0701** [comment]
No regressions found.

@JanisZhang The error didn't happen in the latest upgrade tests.

**Comment by JanisZhang** [comment]
> No regressions found.
> 
> @JanisZhang The error didn't happen in the latest upgrade tests.

Thanks Summer!   FYI @dantewang .

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/144189

**Pull request closed without merging**
