### PR TITLE
[OrderByComparator] LPD-29234

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPD-29234](https://liferay.atlassian.net/browse/LPD-29234)
- **LPD-29234 Add singleton to commerce-product-api**
- **LPD-29234 Apply commerce-product-api usages**
- **LPD-29234 SemVer**
- **LPD-29234 Add Upgrade case and test**

[LPD-29234]: https://liferay.atlassian.net/browse/LPD-29234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:relevant

**Comment by victorhcunha** [comment]
ci:report:55513596

**Comment by victorhcunha** [comment]
ci:report:55485285

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@victorhcunha Please resolve conflicts and forward, thanks!

**Comment by victorhcunha** [comment]
ci:reopen

**Comment by victorhcunha** [comment]
Thanks @dantewang !

**Comment by victorhcunha** [comment]
ci:forward

**Comment by victorhcunha** [comment]
ci:forward:force

**Comment by victorhcunha** [comment]
The SF issue is no related with the changes.

**Comment by Valmir-unicap** [comment]
ci:report:57424741

**Comment by victorhcunha** [comment]
ci:forward

**Comment by victorhcunha** [comment]
ci:forward:force

**Comment by victorhcunha** [comment]
ci:stop

**Pull request closed without merging**
