### PR TITLE
[Phase 1] LPS-173369 Remove Optional usages for module: portal-search-web-api

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from #3712 due to compile error

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@julschong Do you have part 3 ready? If so, just send all the changes in one PR. I'll try to look into them together. Thanks!

**Pull request closed without merging**
