### PR TITLE
[SF] LPS-198311 Add a new module without unused variables to SF properties.

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by JanisZhang** [comment]
cc @JanisZhang

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(11/1 9:03)

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
