### PR TITLE
[Reflection] LPD-15262 Check for JDK8 instead of !JDK11 in InitUnit

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:report:2529159112

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
rerun relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:reoport:2529633457

**Comment by tinatian** [comment]
ci:report:2529633457

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
