### PR TITLE
LPS-174300 Remove the service property from message listeners and let…

### PR DESCRIPTION
**Pull request by tinatian**
… it be implied as immediate

### CODE REVIEW

**Comment by tinatian** [comment]
@111Anna @GinsonRen This may cause startup regression.

**Comment by 111Anna** [comment]
Hi @tinatian @GinsonRen  I tested the pull on test machine, there seems no recession
Here are test results:

DXP

Portal Version|GitId|Average Startup (ms)|%|Average Shutdown (ms)|%|Open File|Thread Create|Open Prepared Statement|Open SQL
--|--| --|--|--|--|--|--|--|--|
Baseline| fe66b60|25286 |- |3868|-|1989 |115| 552|1097 |
Baseline + LPS-174300| - |25291.3 |-0.02%|3881|-0.3%|1998 |112 |566|1098|
 
 
CE

Portal Version|GitId|Average Startup (ms)|%|Average Shutdown (ms)|%|Open File|Thread Create|Open Prepared Statement|Open SQL
--|--| --|--|--|--|--|--|--|--|
Baseline| fe66b60dfb|23130.3|- |3877.3|-|1833 |102|506|1008 |
Baseline + LPS-174300| - |23118.6|0.05%|3276|18.3%|1833 |101|508 |1009 |

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@tinatian regressions found:

```
     [exec] com.liferay.portal.osgi.debug.declarative.service.test.DeclarativeServiceDependencyManagerTest > testDeclarativeServiceDependencyManagerResolvedDependencies FAILED
     [exec]     org.junit.ComparisonFailure: expected:<[All declarative service components are satisfied]> but was:<[
     [exec]     Bundle {id: 112, name: com.liferay.portal.security.sso.openid.connect.impl, version: 7.0.15}
     [exec]     	Declarative Service {id: 99, name: com.liferay.portal.security.sso.openid.connect.internal.OpenIdConnectAuthenticationHandlerImpl, unsatisfied references: 
     [exec]     		{name: _offlineOpenIdConnectSessionManager, target: null}
     [exec]     	}
     [exec]     	Declarative Service {id: 106, name: com.liferay.portal.security.sso.openid.connect.internal.servlet.filter.auto.login.OpenIdConnectAutoLoginFilter, unsatisfied references: 
     [exec]     		{name: _offlineOpenIdConnectSessionManager, target: null}
     [exec]     		{name: _openIdConnectAuthenticationHandler, target: null}
     [exec]     	}
     [exec]     	Declarative Service {id: 105, name: com.liferay.portal.security.sso.openid.connect.internal.servlet.filter.OpenIdConnectSessionValidationFilter, unsatisfied references: 
     [exec]     		{name: _offlineOpenIdConnectSessionManager, target: null}
     [exec]     	}
     [exec]     Bundle {id: 1250, name: com.liferay.login.authentication.openid.connect.web, version: 6.0.18}
     [exec]     	Declarative Service {id: 10516, name: com.liferay.login.authentication.openid.connect.web.internal.portlet.action.OpenIdConnectLoginRequestMVCActionCommand, unsatisfied references: 
     [exec]     		{name: _openIdConnectAuthenticationHandler, target: null}
     [exec]     	}]>
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:117)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
     [exec]     	at com.liferay.portal.osgi.debug.declarative.service.test.DeclarativeServiceDependencyManagerTest.testDeclarativeServiceDependencyManagerResolvedDependencies(DeclarativeServiceDependencyManagerTest.java:118)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-02/test-1-32/test-portal-acceptance-pullrequest(master)/8082/modules-integration-mysql57-jdk8/1/13/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.calendar.upgrade.v2_0_0.test.UpgradeSchemaTest > testUpgradeCreatesCalendarBookingRecurringId FAILED
     [exec]     java.lang.NullPointerException: A null service reference is not allowed.
     [exec]     	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:622)
     [exec]     	at com.liferay.calendar.test.util.CheckBookingsMessageListenerTestUtil.setUp(CheckBookingsMessageListenerTestUtil.java:42)
     [exec]     	at com.liferay.calendar.upgrade.v2_0_0.test.UpgradeSchemaTest.setUp(UpgradeSchemaTest.java:72)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-02/test-1-32/test-portal-acceptance-pullrequest(master)/8082/modules-integration-mysql57-jdk8/0/7/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.asset.publisher.web.internal.messaging.test.CheckAssetEntryMessageListenerTest > testGetTriggerEmptyCronExpression FAILED
     [exec]     java.lang.IllegalStateException: Timed out while waiting for service com.liferay.portal.kernel.messaging.MessageListener component.name=*.CheckAssetEntryMessageListener
     [exec]     	at com.liferay.portal.test.rule.InjectTestBag._getServiceReference(InjectTestBag.java:199)
     [exec]     	at com.liferay.portal.test.rule.InjectTestBag.injectFields(InjectTestBag.java:78)
     [exec]     	at com.liferay.portal.test.rule.InjectTestRule.beforeMethod(InjectTestRule.java:61)
     [exec]     	at com.liferay.portal.test.rule.InjectTestRule.beforeMethod(InjectTestRule.java:24)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:94)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-02/test-1-32/test-portal-acceptance-pullrequest(master)/8082/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129638

**Pull request closed without merging**
