### PR TITLE
LPS-160408

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results once they are avaiable.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
@tinatian no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121711

**Pull request closed without merging**
