### PR TITLE
LPS-142794 - fix XXE vulnerability by using newTransformerFactory() with attributes set up

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-142794.
Thanks for checking.

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found. Can you rebase, please? Thanks!

**Comment by jeffwu0724** [comment]
fixed the code conflict

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by tinatian** [comment]
@jeffwu0724 As we talked, please resend.

Thanks.
Tina

**Pull request closed without merging**
