### PR TITLE
LPS-171249 upgrade Netty/Codec/HTTP in shared-dependencies-netty

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-171249.
Thanks for checking!

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by jeffwu0724** [comment]
fixed the code conflict in lib/versions-complete.xml by auto generate, the old test result should be good enough

**Comment by tinatian** [comment]
@jeffwu0724 Please rebase

**Comment by jeffwu0724** [comment]
ant build-lib-versions is down now, will rebase and resend later

**Comment by jeffwu0724** [comment]
still had `java.io.IOException: Server returned HTTP response code: 504` while running `ant build-lib-versions` on 1/18/23, 8:21am

**Comment by jeffwu0724** [comment]
fixed the code conflict by rerunning ant build-lib-versions

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129085

**Pull request closed without merging**
