### PR TITLE
[TS] LPS-183708 Load the default Language.properties file along with specific localizations

### PR DESCRIPTION
**Pull request by jonathanmccann**
Prior to this change only language properties files with a locale in the file name were being loaded. Now it will also load the default `Language.properties` file.

Please let me know if there are any questions or changes that need to be made.

### CODE REVIEW

**Comment by tinatian** [comment]
@jonathanmccann I do not think the Language.properties should be loaded. The reason you see the translation is missing most probably caused by corresponding -*.properties do not have that entry which is wrong. All *-.properties should have same entries as Language.properties. Could you please check why it does not have? Also, please always provide a test to cover your changes.

Thanks.
Tina

**Comment by jonathanmccann** [comment]
@tinatian Thank you for the quick reply.

The client brought up this issue in regards to untranslated locales (hence no `language_*.properties` file). They wanted to utilize the default `Language.properties` file to provide a base translation in those cases.

In 7.3 this file was loaded as the client expects so can you explain the reasoning for not wanting to load it any more? If you'd rather discuss the use case over a PTR I can open one instead.

**Comment by tinatian** [comment]
@yuhai Please take this over, it should be related to https://issues.liferay.com/browse/LPS-135504

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by yuhai** [comment]
stating in review :)

**Comment by yuhai** [comment]
Hi @jonathanmccann,

Refer to 7.3.x, portal-impl/..language.properties is loaded in the `LanguageResourcesBundle(Locale locale)` constructor in `LanguageResources `class. And it used `_blankLocale` to  load language.properties values in `_loadLocale()`. I suggest we may use the similar way to fix the issue on master. Please see the below reason:

In `LanguageResourcesExtender`, it uses every languageId as property to register ResourceBundle service(except language.properties). But the below codes actually can read language.properties values for every ResourceBundle with languageId. You may check the method's doc.
```
ResourceBundle.getBundle(baseName, locale, bundleWiring.getClassLoader(),UTF8Control.INSTANCE).
```

So we needn't register the property languageId for blank ResourceBundle service. We may replace _blankLocale with a real locale to get the existed ResourceBundle. The fix may be done in MapHolder constructor. Just like:

in `LanguageResources.MapHolder`.

```
private MapHolder(Locale locale) {
      String languageId = LocaleUtil.toLanguageId(locale);

	if (locale == _blankLocale) {
		locale = LocaleUtil.getDefault();

		languageId = locale.getLanguage();
	}
}
```

Please also add the test for the pr. Please let me know if you have further concerns.

Thanks,
Hai

**Comment by tinatian** [comment]
@jonathanmccann Per @yuhai 's comment, I am going to close this pull, please resend.

Thanks.
Tina

**Pull request closed without merging**
