### PR TITLE
[SF] LPS-160079 Add more modules that we already fixed unused reference variables

### PR DESCRIPTION
**Pull request by JanisZhang**

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
@JanisZhang Just need to fix the sf issue in source.formatter.properties. The dynamic-data modules should go after dispatch modules so it's alphabetical. Otherwise no regressions.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
@Kvale1733 Thank you!

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
Hi @dantewang 
SF failure is not related, manually forward this one, see https://github.com/brianchandotcom/liferay-portal/pull/125841 . Thanks!

**Pull request closed without merging**
