### PR TITLE
[TS] LPD-31257 viewCountIncrementListener should only be called when the view count is actually incremented

### PR DESCRIPTION
**Pull request by ericyanLr**
**Ticket:** https://liferay.atlassian.net/browse/LPD-31257

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:35581766

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 35581766.
> 
> Job Link: [generate-testray-csv](https://test-1-8.liferay.com/job/generate-testray-csv/112/)
> 
> Testray CSV Link: [testray-results-35581766.csv](https://test-1-8.liferay.com/userContent/jobs/generate-testray-csv/builds/112/testray-results-35581766.csv)

Unique failures in report are not related.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/152244

**Pull request closed without merging**
