### PR TITLE
[Remove Stream/Optional usage] LPS-174598 Remove usages of Stream for module: portal-upgrade-impl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(2/7 13:34)

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(2/8 9:04)

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(2/9 9:43)

**Comment by W2jx** [comment]
no conflicts(2/17 10:45)

**Pull request closed without merging**
