### PR TITLE
LPD-25462 Add default property to test.properties so that build-test.xml can reference it

### PR DESCRIPTION
**Pull request by julschong**
@kenjiheigel @vicnate5 @alvarosaugarlr

This is for issue: https://liferay.atlassian.net/browse/LPD-25462

This PR lets Poshi functional test cases get the default.admin.password using Props.get("default.admin.password"). 

Adding additional property and reference it in both `prepare-portal-ext-properties` and `prepare-poshi-runner-properties` targets in `build-test.xml` can keep the values on the testing server and poshi runner in sync.

### CODE REVIEW

**Comment by julschong** [comment]
@kenjiheigel @alvarosaugarlr
if looks good, let me know to forward it.
Once this is merged, we can easily start replacing all the `password = "test"`

**Comment by julschong** [comment]
ci:test:core-functional

**Comment by kenjiheigel** [comment]
@julschong, looks good! I'd suggest to rename the property in test.properties to `test.portal.default.admin.password` though.

**Comment by julschong** [comment]
changed property name and verified locally that testcases can use `PropsUtil.get("default.admin.password");` to retrieve the property. forwarding

**Comment by julschong** [comment]
ci:forward

**Comment by julschong** [comment]
remove sf flagged word from commit meesage

**Comment by julschong** [comment]
ci:forward

**Pull request closed without merging**
