### PR TITLE
[Optional Reference] LPS-185557 Convert the Optional Dynamic Greedy references to static references using Snapshot in class SchedulerEngineHelperImpl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:help

**Comment by zhangyan0701** [comment]
ci:test:clustering

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(5/25 10:06)

**Comment by W2jx** [comment]
no conflicts(5/26 15:09)

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
