### PR TITLE
LPS-147674 After upgrading from 7.3 to 7.4, the Publications User role doesn't have all of it's permissions

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-147674

Tests run in https://github.com/xbrianlee/liferay-portal/pull/707.

### CODE REVIEW

**Comment by tinatian** [comment]
@stsquared99 @xbrianlee Code looks good to me, waiting for test results.

Tina.

**Comment by xbrianlee** [comment]
@tinatian Do we need to re-run any tests besides the `ci:forward` test suites? We ran tests in https://github.com/xbrianlee/liferay-portal/pull/707 already.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

@xbrianlee I do not think so. 

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113985

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
