### PR TITLE
LPS-154230 Company Log Servlet

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 Could you please add functional tests to cover this?

Tina

**Comment by vicnate5** [comment]
@kyle-miho will be testing and automating this.

**Comment by kyle-miho** [comment]
looking through this

**Comment by catarineaguiar** [comment]
@tinatian

semver error:
```
 [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/petra/petra-log4j] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.petra.log4j                            MINOR      1.2.0      1.2.0      1.3.0      VERSION INCREASE REQUIRED
     [exec]     	<   class      com.liferay.petra.log4j.Log4JUtil
     [exec]     		+   method     getCompanyLogDirectory(long)
     [exec]     			+   access     static
     [exec]     			+   return     java.lang.String
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 5.1.0
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-06/test-1-26/test-portal-acceptance-pullrequest(master)/3668/modules-semantic-versioning-jdk8/0/5/jenkins-console.txt.gz?authuser=0)

regression on `Log4jConfigUtilTest` unit test:
```
   [exec] com.liferay.petra.log4j.internal.Log4jConfigUtilTest > classMethod FAILED
     [exec]     java.lang.AssertionError: com.liferay.petra.log4j.internal.Log4jConfigUtil is not fully covered
     [exec]         at com.liferay.whip.agent.InstrumentationAgent._assertClassDataCoverage(InstrumentationAgent.java:343)
     [exec]         at com.liferay.whip.agent.InstrumentationAgent.assertCoverage(InstrumentationAgent.java:66)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-06/test-1-26/test-portal-acceptance-pullrequest(master)/3668/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Comment by kyle-miho** [comment]
@tinatian the behavior of this pull seems good, finalizing functional tests for this to add to the test map, we will prioritize them asap, just need to fix the semVar and code coverage issues stated above. 

Also, this Error thrown in  _downloadLogFile if the log file does not exist is not very helpful, we should probably add a message to the exception that we are throwing ourselves
2022-06-28 21:42:53.957 WARN  [http-nio-8080-exec-5][PortalImpl:6566] null
java.io.FileNotFoundException: null
	at com.liferay.portal.company.log.internal.servlet.CompanyLogServlet._downloadLogFile(CompanyLogServlet.java:158) ~[bundleFile:?]
	at com.liferay.portal.company.log.internal.servlet.CompanyLogServlet.doGet(CompanyLogServlet.java:90) [bundleFile:?]

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/1032

**Pull request closed without merging**
