### PR TITLE
[Move Expando]Lps 190836 10 17

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-190836

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:upgrade

**Comment by slnn** [comment]
ci:test

**Comment by Kvale1733** [comment]
@slnn Regressions found

1) com.liferay.dynamic.data.mapping.internal.upgrade.v5_0_0.PollsToDDMUpgradeProcessTest
```
  [exec] > Task :apps:dynamic-data-mapping:dynamic-data-mapping-test-util:compileJava
[beanshell]      [exec] error: com.liferay.expando.service.ExpandoRowLocalService: class file for com.liferay.expando.service.ExpandoRowLocalService not found
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/dynamic-data-mapping/dynamic-data-mapping-test/src/test/java/com/liferay/dynamic/data/mapping/internal/upgrade/v1_0_0/DynamicDataMappingUpgradeProcessTest.java:56: error: cannot access com.liferay.expando.service.ExpandoRowLocalService
[beanshell]      [exec] public class DynamicDataMappingUpgradeProcessTest extends BaseDDMTestCase {
[beanshell]      [exec]        ^
[beanshell]      [exec]   class file for com.liferay.expando.service.ExpandoRowLocalService not found
[beanshell]      [exec] Note: Some input files use or override a deprecated API.
[beanshell]      [exec] Note: Recompile with -Xlint:deprecation for details.
[beanshell]      [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/dynamic-data-mapping/dynamic-data-mapping-test/src/test/java/com/liferay/dynamic/data/mapping/internal/notification/DDMFormEmailNotificationSenderTest.java uses unchecked or unsafe operations.
[beanshell]      [exec] Note: Recompile with -Xlint:unchecked for details.
```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-27/test-portal-acceptance-pullrequest(master)/10363/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

2) Service builder changes detected
```
delete] Deleting: /opt/dev/projects/github/liferay-portal/build.services.diff.txt
     [echo] diff --git a/modules/apps/commerce/commerce-product-api/bnd.bnd b/modules/apps/commerce/commerce-product-api/bnd.bnd
     [echo] index 57a2826fbb905..2879596938545 100644
     [echo] --- a/modules/apps/commerce/commerce-product-api/bnd.bnd
     [echo] +++ b/modules/apps/commerce/commerce-product-api/bnd.bnd
     [echo] @@ -1,6 +1,6 @@
     [echo]  Bundle-Name: Liferay Commerce Product API
     [echo]  Bundle-SymbolicName: com.liferay.commerce.product.api
     [echo] -Bundle-Version: 76.0.1
     [echo] +Bundle-Version: 76.1.0
     [echo]  Export-Package:\
     [echo]  	com.liferay.commerce.product.availability,\
     [echo]  	com.liferay.commerce.product.catalog,\
     [echo] diff --git a/modules/apps/expando/expando-api/src/main/java/com/liferay/expando/service/persistence/ExpandoColumnPersistence.java b/modules/apps/expando/expando-api/src/main/java/com/liferay/expando/service/persistence/ExpandoColumnPersistence.java
     [echo] index c89b481c0ff5e..faf953e29a67c 100644
     [echo] --- a/modules/apps/expando/expando-api/src/main/java/com/liferay/expando/service/persistence/ExpandoColumnPersistence.java
     [echo] +++ b/modules/apps/expando/expando-api/src/main/java/com/liferay/expando/service/persistence/ExpandoColumnPersistence.java
     [echo] @@ -161,6 +161,62 @@ public interface ExpandoColumnPersistence
     [echo]  				orderByComparator)
     [echo]  		throws NoSuchColumnException;
     [echo]  
  ```
  [Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-35/test-portal-acceptance-pullrequest(master)/4703/service-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0)
  
  3) Unable to register portal instance error after upgrade
  Steps to reproduce:
  1. Import this db dump
  2. Upgrade db with upgrade tool
  3. Start portal
  
  Results:
  ```
  successfully
[beanshell] 2023-10-17 09:41:08.899 WARN  [SystemExecutorServiceUtil-6-com.liferay.portal.spring.extender.internal.configuration.ServiceConfigurationInitializer-com.liferay.change.tracking.service][PortalInstanceLifecycleListenerManagerImpl:195] Unable to register portal instance {"mvccVersion": 1, "companyId": 20097, "userId": 0, "userName": "", "createDate": "Thu Jul 22 00:00:00 GMT 2021", "modifiedDate": "Thu Jul 22 00:00:00 GMT 2021", "webId": "liferay.com", "mx": "liferay.com", "homeURL": "", "logoId": 0, "maxUsers": 0, "active": true, "name": "Liferay DXP", "legalName": "", "legalId": "", "legalType": "", "sicCode": "", "tickerSymbol": "", "industry": "", "type": "", "size": "", "indexNameCurrent": "", "indexNameNext": ""}
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.expando.service.ExpandoColumnLocalServiceUtil.getDefaultTableColumns(ExpandoColumnLocalServiceUtil.java:382) ~[?:?]
[beanshell] 	at com.liferay.expando.internal.ExpandoBridgeImpl.getAttributeColumns(ExpandoBridgeImpl.java:641) ~[?:?]
[beanshell] 	at com.liferay.expando.internal.ExpandoBridgeImpl.getAttributes(ExpandoBridgeImpl.java:280) ~[?:?]
[beanshell] 	at com.liferay.expando.kernel.util.ExpandoBridgeUtil.setExpandoBridgeAttributes(ExpandoBridgeUtil.java:33) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portlet.documentlibrary.service.impl.DLFileEntryLocalSe
  ```
  [Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-27/test-portal-acceptance-pullrequest(master)/10363/functional-upgrade-tomcat90-mariadb102-jdk8/1/3/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Comment by Kvale1733** [comment]
@slnn Another thing I missed. This seems to cause a startup race condition. 

```
  [junit] 2023-10-17 09:32:59.502 WARN  [main][PortalInstanceLifecycleListenerManagerImpl:195] Unable to register portal instance {"mvccVersion": 0, "companyId": 20091, "userId": 0, "userName": "", "createDate": "Tue Oct 17 09:32:28 GMT 2023", "modifiedDate": "Tue Oct 17 09:32:28 GMT 2023", "webId": "liferay.com", "mx": "liferay.com", "homeURL": "", "logoId": 0, "maxUsers": 0, "active": true, "name": "Liferay", "legalName": "", "legalId": "", "legalType": "", "sicCode": "", "tickerSymbol": "", "industry": "", "type": "", "size": "", "indexNameCurrent": "", "indexNameNext": ""}
    [junit] java.lang.NullPointerException: null
    [junit] 	at com.liferay.expando.service.ExpandoColumnLocalServiceUtil.getDefaultTableColumns(ExpandoColumnLocalServiceUtil.java:382) ~[?:?]
    [junit] 	at com.liferay.expando.internal.ExpandoBridgeImpl.getAttributeColumns(ExpandoBridgeImpl.java:641) ~[?:?]
    [junit] 	at com.liferay.expando.internal.ExpandoBridgeImpl.getAttributes(ExpandoBridgeImpl.java:280) ~[?:?]
    [junit] 	at com.liferay.expando.kernel.util.ExpandoBridgeUtil.setExpandoBridgeAttributes(ExpandoBridgeUtil.java:33) ~[portal-kernel.jar:?]
    [junit] 	at com.liferay.portlet.documentlibrary.service.impl.DLFileEntryLocalServiceImpl._addFileVersion(DLFileEntryLocalServiceImpl.java:2146) ~[portal-impl.jar:?]
    [junit] 	at com.liferay.portlet.documentlibrary.service.impl.DLFileEntryLocalServiceImpl.addFileEntry(DLFileEntryLocalServiceImpl.java:301) ~[portal-impl.jar:?]
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
    [junit] 	at sun.reflect.NativeMethodAcces
```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-27/test-portal-acceptance-pullrequest(master)/10364/functional-smoke-startup-tomcat90-mysql57-jdk8/1/18/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
