### PR TITLE
LPS-145927

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
re-running the acceptance because most tests were aborted.

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@marianoalvarosaiz Code conflicts, please rebase.

Thanks.
Tina.

**Comment by marianoalvarosaiz** [comment]
@tinatian see https://github.com/liferay-core-infra/liferay-portal/pull/1021

**Pull request closed without merging**
