### PR TITLE
LPS-145050

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina, Shuyang
@tinatian, @shuyangzhou
this is the resend for [tinatian #2478](https://github.com/tinatian/liferay-portal/pull/2478)
[LPS-145050](https://issues.liferay.com/browse/LPS-145050)

1. Made sure to not have logic changes when I made buildClassPath method inline
2. Changed the wording to "Modify" and check and throw IllegalStateException when file array is empty
3. Last commit only contains filter logic changes

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@vicnate5 Hi Victor, could you please help me check this one as well?
Thank you!

**Comment by vicnate5** [comment]
@Hijky can you check this one?

**Comment by Hijky** [comment]
None of the failed cases are relevant

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/251

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
