### PR TITLE
[System Properties]LPS-154373 Move some properties that ModuleFramework need when start

### PR DESCRIPTION
**Pull request by W2jx**
HI @tinatian @dantewang , I have moved some properties that ModuleFramework need when start.

Dependency: https://github.com/liferay-core-infra/liferay-portal/pull/1934

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
No regressions found.

**Pull request closed without merging**
