### PR TITLE
[Method References] LPS-162389 Convert method references to field references in class entends BaseTemplateManager

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I convert method references to field references in class entends BaseTemplateManager.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results when they finish ? Thanks!

**Comment by zhangyan0701** [comment]
Hi @W2jx 

Please fix the conflict in portal-impl/bnd.bnd.

**Comment by W2jx** [comment]
force-push just to resolve the conflict in portal-impl/bnd.bnd.

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
The test failures are not related. But there is still a conflict in portal-impl/bnd.bnd.

**Comment by W2jx** [comment]
no conflicts(10:55 AM)

**Comment by dantewang** [comment]
@shuyangzhou @tinatian Forwarding this one as all tests passed review and changes are applying a previously used pattern.

**Comment by dantewang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/123079

**Pull request closed without merging**
