### PR TITLE
LPS-177624 Remove Stream usages in module: headless-commerce-admin-account-impl

### PR DESCRIPTION
**Pull request by julschong**
@dantewang Hi Dante,
Jeff is working on RESTBuilder. 
But I think this addition of transformToLongArray to base_resource_impl is probably not included in his pull.

### CODE REVIEW

**Comment by dantewang** [comment]
@julschong @jeffwu0724 Does this ftl generate classes for a different type of modules (e.g. not the rest client modules)?

**Comment by jeffwu0724** [comment]
Hi @dantewang , my [PR](https://github.com/liferay-core-infra/liferay-portal/pull/4009) here did not make changes to base_resource_impl.ftl, and did not add `transformToLongArray` to this file. And yes, this ftl generates classes for Base*ResourceImpl.java, and they are not in the rest client modules.

**Comment by Kvale1733** [comment]
ci:test:account

**Comment by Kvale1733** [comment]
@julschong No regressions.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
ci:forward:force

**Comment by julschong** [comment]
ci:forward

**Comment by julschong** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/132500

**Pull request closed without merging**
