### PR TITLE
LPS-202308 Remove ValidatorFactory and GeneratorFactory from security-spring

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@julschong Are these leftovers or?

**Comment by julschong** [comment]
@dantewang 
I think these were recently refactored to use snapshot. But I just noticed that they are not used by references. I'm not sure why they didn't get removed in spring beans, so I removed them.

**Comment by JanisZhang** [comment]
> @dantewang I think these were recently refactored to use snapshot. But I just noticed that they are not used by references. I'm not sure why they didn't get removed in spring beans, so I removed them.

Just fyi.  I did the same thing in this commit https://github.com/brianchandotcom/liferay-portal/pull/142132/commits/12f6d1af14c3ded83bb6f8e6ef714d2c49fc40f4. 

I think these class doesn't need to be a bean in the first place, as the default one like `DefaultEmailAddressGenerator` is already a bean that can be tracked by `ServiceProxyFactory`.

**Pull request closed without merging**
