### PR TITLE
[Remove Unused Reference] LPS-166034 Remove unused @Reference variable in module user-associated-data-web

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have removed unused reference variable in module user-associated-data-web.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @Kvale1733 , Could you please help me check the test results ? Thanks!

**Comment by dantewang** [comment]
@W2jx Since this removes _portal field, please double check.

**Comment by W2jx** [comment]
Hi @dantewang , I have double checked them, and I think _portal in them can safely be removed.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
