### PR TITLE
[Remove unused reference] LPS-166429

### PR DESCRIPTION
**Pull request by JanisZhang**
This PR is to remove unused fields in `commerce-product-type-grouped-web` Thanks!

https://issues.liferay.com/browse/LPS-166429

### CODE REVIEW

**Comment by jaydawu** [comment]
All tests passed.

cc/ @zhangyan0701

**Comment by JanisZhang** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by dantewang** [comment]
@JanisZhang Please record this one:
`GroupedCPTypeJSPDynamicInclude` -> `/dynamic_include/grouped_product_type.jsp` -> `/init.jsp` -> `PortalUtil`

Let's revisit it to decide whether it's safe in second round.

**Pull request closed without merging**
