### PR TITLE
[Method References] LPS-160434 Convert method references to field references in class extends BasePanelApp

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I just rebase the code.

Detial: https://github.com/liferay-core-infra/liferay-portal/pull/1855

### CODE REVIEW

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by dantewang** [comment]
@W2jx Please rebase

**Comment by W2jx** [comment]
Hi @dantewang , I have rebased the code.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
Force-Push is just to resolve the conflicts in file DepotSettingsPanelApp.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@W2jx Please rebase

**Comment by W2jx** [comment]
Force-Push is just to resolve the conflicts in file TranslationPanelApp

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125101

**Pull request closed without merging**
