### PR TITLE
[Component with its own class name as service type] LPS-198933 Refactor DTOConverter from headless-commerce-admin-catalog-impl and headless-delivery-impl components

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-198933](https://liferay.atlassian.net/browse/LPS-198933)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
@RenanUmV https://github.com/liferay-core-infra/liferay-portal/pull/5834/commits/265e7d13ffd891125309a29005073e034c87a9a8 can not be right, the dto.class.name can not be the component class name itself.

I think it should be the first generic type of the DTOConverter, but I don't know anything about DTOConverter, @rafaprax please check this and fix all existing bad usages.

**Pull request closed without merging**
