### PR TITLE
[Remove unused @Reference var] LPS-165145

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to use serviceTrackerMap instead of the method reference in `users-admin`. Thanks!

All tests passed in https://github.com/JanisZhang/liferay-portal/pull/138

https://issues.liferay.com/browse/LPS-165145

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@JanisZhang functional tests failed due to:

```
 [exec]     LIFERAY_ERROR: Unable to start bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.commerce.service.jar
     [exec]     LIFERAY_ERROR: Declarative Service Unsatisfied Component Checker check result: 
     [exec]     Bundle {id: 369, name: com.liferay.commerce.product.type.virtual.web, version: 4.0.31}
     [exec]     	Declarative Service {id: 6630, name: com.liferay.commerce.product.type.virtual.web.internal.portlet.action.EditCommerceVirtualOrderItemMVCActionCommand, unsatisfied references: 
     [exec]     		{name: _commerceVirtualOrderItemService, target: null}
     [exec]     	}
     [exec]     	Declarative Service {id: 6628, name: com.liferay.commerce.product.type.virtual.web.internal.frontend.taglib.servlet.taglib.CommerceOrderItemVirtualSettingsScreenNavigationCategory, unsatisfied references: 
     [exec]     		{name: _commerceOrderItemService, target: null}
     [exec]     		{name: _commerceOrderService, target: null}
     [exec]     		{name: _commerceVirtualOrderItemLocalService, target: null}
     [exec]     	}
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-39/test-portal-acceptance-pullrequest(master)/841/functional-smoke-wildfly180-mariadb106-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions.

**Pull request closed without merging**
