### PR TITLE
LPS-120011 

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, I updated the expected behavior in LPS-120011 [comment](https://issues.liferay.com/browse/LPS-120011?focusedCommentId=2568462&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2568462). After the [comment](https://issues.liferay.com/browse/LPS-120011?focusedCommentId=2236024&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2236024), LPS-128817 added the related logic in GroupLocalServiceImpl.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
@yuhai Could you explain in detail why the expected behavior needs to be changed?

**Comment by yuhai** [comment]
@dantewang, 

> Could you explain in detail why the expected behavior needs to be changed? And what's the behavior of the steps in the tickets description after your fix?

After the fix, the user can't use search field (search field is disabled) because asset library A is not viewable for the user (**the description only created one asset library A**). If the user can view another asset library, the search field is not disabled and the expected behavior will be same with the ticket's description. 

In the latest master without the fix, if we didn't create any asset library, only assign the view asset library permission for the user to access Asset Library, the search field is also disabled because no asset library existed. You may check the logic from the [comment](https://issues.liferay.com/browse/LPS-120011?focusedCommentId=2568462&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2568462)

**Comment by dantewang** [comment]
@yuhai OK, so even without your fix, the user can't get to see the wrong count at all, right?

**Comment by yuhai** [comment]
@dantewang, no, without the fix, the user can see the wrong count because the total return 1.

**Comment by dantewang** [comment]
@yuhai But without your fix, can the user do search after following the ticket description? If not, then the steps should be updated.

**Comment by yuhai** [comment]
> @yuhai OK, so After your fix, the behavior will be
> 
> * following the steps in the ticket, the user can't even do search
> * with another asset that the user can see, the user will be able to search, and
>   
>   * when searching "A", 0 result
>   * when searching the new one, 1 result
> 
> So this actually fixes the search count, right?

yes

**Comment by yuhai** [comment]
> 

yes, without the fix, the user can search. I just updated the description in the tikcet

**Comment by dantewang** [comment]
@yuhai OK, thanks.

@zhangyan0701 Could you review the test results? Thanks!

@tinatian The change looks good to me.

**Comment by zhangyan0701** [comment]
No related failures found.

**Comment by tinatian** [comment]
@dantewang @yuhai I am confused, with this comment https://issues.liferay.com/browse/LPS-120011?focusedCommentId=2236024&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2236024, it seems the problem is GroupServiceImpl#search and GroupServiceImpl#searchCount are not consistent, one with filter logic, one without.

**Comment by yuhai** [comment]
@tinatian, at the comment https://issues.liferay.com/browse/LPS-120011?focusedCommentId=2236024&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2236024. LPS-128817 was not merged to master. LPS-128817 added the filter in local service and can let searchCount return the right result. So the fix applied the LPS-128817 fix.

**Comment by dantewang** [comment]
@yuhai You mean someone already added logic to make searchCount support the filter as https://github.com/brianchandotcom/liferay-portal/pull/99954/files#diff-809c64f8ed9e550f63935bdd9fc3d34e1780651d80004c804c6a7ea4806c185b, and you just add the filter param into the relevant place, right? @tinatian

**Comment by yuhai** [comment]
> @yuhai You mean someone already added logic to make searchCount support the filter as https://github.com/brianchandotcom/liferay-portal/pull/99954/files#diff-809c64f8ed9e550f63935bdd9fc3d34e1780651d80004c804c6a7ea4806c185b, and you just add the filter param into the relevant place, right? @tinatian

yes.

**Comment by tinatian** [comment]
@dantewang @yuhai I am still confused. Why there is another ticket involved? Could you please explain in more details what happend?

**Comment by dantewang** [comment]
@tinatian I believe what Hai meant is, LPS-128817 already added filtering logic to group service, so to fix the specific issue in this ticket, we just need to add proper filter parameter.

**Comment by yuhai** [comment]
> @tinatian I believe what Hai meant is, LPS-128817 already added filtering logic to group service, so to fix the specific issue in this ticket, we just need to add proper filter parameter.

@tinatian, yes.

**Pull request closed without merging**
