### PR TITLE
[Equinox] LPS-184766 Part 2 Inline Activator related logic | 8-31

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:smoke

**Comment by dantewang** [comment]
ci:test:licensing

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140197

**Pull request closed without merging**
