### PR TITLE
[TS] LPS-141588

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This is a followup of https://github.com/tinatian/liferay-portal/pull/2443 after adressing the changes recommended by @tinatian.

Could you please review it?

Thanks in advance,
Daniel

\cc @ericyanLr

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:tes:sf

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:reevaluate:1297401_744

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by ericyanLr** [comment]
Hi @dacousalr @tinatian ,

I noticed for the new third-party module and artifact id, we are using: **com.sun.el.javax.el**

Should it instead be **jakarta.el**?

**Comment by ericyanLr** [comment]
Hi @dacousalr @tinatian ,

Also, please see my latest comment on PTR-2723, there is now another factor to consider.

**Comment by tinatian** [comment]
Hi @ericyanLr ,

> I noticed for the new third-party module and artifact id, we are using: com.sun.el.javax.el

> Should it instead be jakarta.el?

**Comment by ericyanLr** [comment]
ah I see, thanks for the clarification.

**Comment by tinatian** [comment]
Close, please resend based on https://issues.liferay.com/browse/PTR-2723?focusedCommentId=2578713&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2578713

Tina

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
