### PR TITLE
LPS-156153 Output all files with missing entries in unit test LibraryReferenceTest.testIntelliJLibPreModules

### PR DESCRIPTION
**Pull request by julschong**
@tinatian 
Hi Tina,
[LPS-156153](https://issues.liferay.com/browse/LPS-156153)

Resubmitted from #965 

Issue was found in https://github.com/julschong/liferay-portal/pull/334#issuecomment-1155484998

Currently,

LibraryReferenceTest.testIntelliJLibPreModules unit test will only output the first file with missing entries encountered.

Then, it stops checking the rest.

Example output below:

> [junit] Testcase: testIntelliJLibPreModules(com.liferay.portal.library.LibraryReferenceTest): FAILED
> [junit] util-slf4j/util-slf4j.iml is missing orderEntry elements for modules [portal-log4j]
> [junit] junit.framework.AssertionFailedError: util-slf4j/util-slf4j.iml is missing orderEntry elements for modules [portal-log4j]
> [junit] at com.liferay.portal.library.LibraryReferenceTest.testIntelliJLibPreModules(LibraryReferenceTest.java:126)
> However, test actually fails with multiple files with missing entries.

It would be better to finish checking all files and output all files with missing entries like below:

> [junit] Testcase: testIntelliJLibPreModules(com.liferay.portal.library.LibraryReferenceTest):      FAILED
> [junit] portal-test/portal-test.iml is missing orderEntry elements for modules [portal-log4j]
> [junit] util-java/util-java.iml is missing orderEntry elements for modules [portal-log4j]
> [junit] portal-web/portal-web.iml is missing orderEntry elements for modules [portal-log4j]
> [junit] util-taglib/util-taglib.iml is missing orderEntry elements for modules [portal-log4j]
> [junit]
> [junit] junit.framework.AssertionFailedError: portal-test/portal-test.iml is missing orderEntry elements for modules [portal-log4j]
> [junit] util-java/util-java.iml is missing orderEntry elements for modules [portal-log4j]
> [junit] portal-web/portal-web.iml is missing orderEntry elements for modules [portal-log4j]
> [junit] util-taglib/util-taglib.iml is missing orderEntry elements for modules [portal-log4j]
> [junit]
> [junit]    at com.liferay.portal.library.LibraryReferenceTest.testIntelliJLibPreModules(LibraryReferenceTest.java:146)
> 

CC. @kyle-miho

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:acceptance

**Comment by julschong** [comment]
@catarineaguiar
Hi Catarine,
Welcome back! 
Kyle helped scanned the last result here: https://github.com/liferay-core-infra/liferay-portal/pull/965#issuecomment-1158114032

The issue should be resolved now. Please help me scan again just in case I broke something else on the new change.

Thank you!

@kyle-miho

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Pull request closed without merging**
