### PR TITLE
[Replace Non-Blocking Usage] LPS-199566 Replace non-blocking ServiceProxyFactory usages in package staging

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts（10/26 8:42）

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(10/27 8:50)

**Comment by W2jx** [comment]
no conflicts(10/30 7:57)

**Comment by W2jx** [comment]
no conflicts(10/31 7:55)

**Comment by W2jx** [comment]
no conflicts(11/1 9:03)

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143065

cc @shuyangzhou

**Pull request closed without merging**
