### PR TITLE
[TS] LPS-157843

### PR DESCRIPTION
**Pull request by yuhai**
@tinatian, @dantewang, the previous pr is https://github.com/liferay-core-infra/liferay-portal/pull/3876. I removed test codes, please see the below explanation.

Refer to https://github.com/ricardocousolr/liferay-portal/blob/LPS-157843/definitions/liferay-service-builder_7_4_0.dtd#L563-L566, the function only takes effect for **specific databases** (I also check related hibernate Dialect, that is true, the api is `supportsSequences()`). Since the test requires api and service modules deployed successfully. Due to the database limitation, when deploy service module to execute the sql from **sequences.sql**, portal will print ERROR log `java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'sequence id_sequence' at line 1 ` in the MySql. So I think it may be hard to let the test run in the specific database. Instead of adding test, using the hibernate link to explain the issue in the commit message.

cc @ricardocousolr

### CODE REVIEW

**Comment by dantewang** [comment]
@yuhai For database specific test, you can use `assume` to make certain test only run on specific database.

On the other hand, If you change ServiceBuilder, please regen.

**Comment by yuhai** [comment]
> @yuhai For database specific test, you can use `assume` to make certain test only run on specific database.
> 
> On the other hand, If you change ServiceBuilder, please regen.

@dantewang, it won't work. Since the test requires service module deployed. When deploy service module, it will throw the error because the function doesn't support on MySql Database. That is to say, before test run, portal will throw error.

**Comment by dantewang** [comment]
@yuhai I see. Maybe create a new test module and only run it in environment tester? @vicnate5 Is it possible to only deploy and run a set of integration test modules on certain database?

**Comment by yuhai** [comment]
@vicnate5, I want to explain the requirement in detail. The case needs to create api,service and test modules. And the test depends on api and service deployed. Just like portal-tools-service-builder-test-api, portal-tools-service-builder-test-service and portal-tools-service-builder-test-test modules. The test only be executed on certain database.

**Comment by tinatian** [comment]
@yuhai You should be able to enable corresponding test service at runtime, as we are using DS now.

Tina.

**Comment by dantewang** [comment]
@yuhai Another way is to completely control the test process using another thing. Maybe `external-data-source-test-controller-test` is a good example.

**Pull request closed without merging**
