### PR TITLE
LPS-143555 Implement relationships UX design

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:test:sf

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@koor4356 Please help me scan test results.

Thanks.
Tina.

**Comment by tinatian** [comment]
Code looks good to me, waiting on QA to scan test results.

**Comment by tinatian** [comment]
@zhangyan0701 Please help me scan the test results.

Thanks.
Tina.

**Comment by koor4356** [comment]
@tinatian, I am re-running the ci test because most are incomplete. Thanks!

**Comment by koor4356** [comment]
ci:test

**Comment by zhangyan0701** [comment]
Have checked the tests results, no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by stsquared99** [comment]
@tinatian @shuyangzhou Sorry, I just remember I need to double check with my test lead to see if any functional tests break. Let me do that asap before you forward this. Thanks!

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
The Publications test suite results look good, however @suilin and I are working on exploratory testing for this ticket before we give the green light.

**Comment by xbrianlee** [comment]
@shuyangzhou This PR looks good from our end. Can we forward this?
cc/ @stsquared99

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
