### PR TITLE
[Components with more than 1 service] LPS-185474 Refactor components from layout module

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://issues.liferay.com/browse/LPS-185474

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
no regressions found.

**Review by rafaprax — CHANGES_REQUESTED** [review]

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:echo

**Review by rafaprax — APPROVED** [review]

**Comment by Kvale1733** [comment]
@MrJohn1911 Regressions found

1) com.liferay.site.initializer.extender.internal.test.BundleSiteInitializerTest
```
 [exec] com.liferay.site.initializer.extender.internal.test.BundleSiteInitializerTest > testInitializeFromBundle FAILED
     [exec]     com.liferay.site.exception.InitializationException: com.liferay.site.navigation.exception.InvalidSiteNavigationMenuItemTypeException: com.liferay.object.model.ObjectDefinition#55867
     [exec]     	at com.liferay.site.initializer.extender.internal.BundleSiteInitializer.initialize(BundleSiteInitializer.java:603)
     [exec]     	at com.liferay.site.initializer.extender.internal.test.BundleSiteInitializerTest._test1(BundleSiteInitializerTest.java:2920)
     [exec]     	at com.liferay.site.initializer.extender.internal.test.BundleSiteInitializerTest.testInitializeFromBundle(BundleSiteInitializerTest.java:325)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:35
```
[Log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-32/test-portal-acceptance-pullrequest(master)/9711/modules-integration-mysql57-jdk8/0/18/jenkins-console.txt.gz?authuser=0)

2) Semver issue
```
[exec] 
     [exec] > Task :apps:layout:layout-page-template-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.layout.page.template.info.item.capability CHANGED    1.1.0      1.1.0      1.1.1      VERSION INCREASE REQUIRED
     [exec] 	~   interface  com.liferay.layout.page.template.info.item.capability.DisplayPageInfoItemCapability
     [exec] 		~   field      KEY
     [exec] 			+   constant   com.liferay.layout.page.template.info.item.capability.DisplayPageInfoItemCapability
     [exec] 	~   interface  com.liferay.layout.page.template.info.item.capability.EditPageInfoItemCapability
     [exec] 		~   field      KEY
     [exec] 			+   constant   com.liferay.layout.page.template.info.item.capability.EditPageInfoItemCapability
     [exec] [Baseline Report] Mode: diff (persisted)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-39/test-portal-acceptance-pullrequest(master)/4889/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
