### PR TITLE
[Optional References]Lps 186379

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-186379

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
ci:test:friendly-url

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian 

These are made optional to keep the servlet working when the redirect services go away. It's normal usage of optional ref, so we can just replace.

**Pull request closed without merging**
