### PR TITLE
[Urgent][Security Bugs]LPD-1558 add properties to control captcha on or off for ci

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

Resend: https://github.com/liferay-core-infra/liferay-portal/pull/6877
In this PR, 
1. I add a new properties captcha.enforce.disabled to disable enforcing captcha in ci test
2. change setMaxChallenges() to enforceCaptcha()
3. restructure the commits
Thanks for chekcing

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance-functional

**Comment by jeffwu0724** [comment]
ci:test:backend

**Comment by jeffwu0724** [comment]
ci:report:2560989586

**Comment by jeffwu0724** [comment]
ci:report:2560999810

**Comment by jeffwu0724** [comment]
ci:report:2561013491

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/149269

**Pull request closed without merging**
