### PR TITLE
LPD-36436 Fix SmokeWithRewriteBatchedStatements

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:smoke

**Comment by tinatian** [comment]
ci:report:11158689

**Comment by tinatian** [comment]
> **Jenkins Build:**[test-portal-acceptance-pullrequest(master)#11246](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/11246/)
> **Jenkins Report:**[jenkins-report.html](https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11246/jenkins-report.html)
> **Jenkins Suite:**smoke
> **Pull Request:**[liferay-core-infra#7428](https://github.com/liferay-core-infra/liferay-portal/pull/7428)
> **Testray Routine:**[EE Pull Request](https://testray.liferay.com/#/project/35392/routines/45357)
> **Testray Build:**[[master] ci:test:smoke - dantewang > liferay-core-infra - PR#7428 - 2024-09-13[02:26:54]](https://testray.liferay.com/#/project/35392/routines/45357/build/11158689)
> **Testray Build ID:**11158689
> **Testray Importer:**[publish-testray-report#24210](https://test-1-39.liferay.com/job/publish-testray-report/24210/)

SmokeWithRewriteBatchedStatements passed and unique failures are not unique to this pull

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/154221

**Pull request closed without merging**
