### PR TITLE
[Remove Blocking usages]LPS-187880 portal-kernel | SettingsFactoryUtil

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang , previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/5047

Changes in this pull request:
- **Rearranged and updated** the commits for better organization and clarity.
- **Inlined** the BundleContext **in** SettingsFactoryUtil.
- **Renamed** SettingsFactoryUtil **to** SettingsProviderUtil to better reflect its role, as it now contains only the `getSettings` method.
- Additionally, I removed some unused reference fields in the changed file, eliminating unnecessary code.

Please review the changes, and let me know if any further improvements or adjustments are needed. Thank you!

Ticket: https://issues.liferay.com/browse/LPS-187880

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
@JanisZhang semver error:

```
     [exec] > Task :apps:message-boards:message-boards-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.message.boards.settings                MAJOR      2.0.0      2.0.0      3.0.0      VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.message.boards.settings.MBGroupServiceSettings
     [exec] 		-   field      ALL_KEYS
     [exec] 			-   access     final
     [exec] 			-   access     static
     [exec] 			-   return     java.lang.String[]
     [exec] [Baseline Warning] Bundle Version Change Recommended: 22.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.message.boards.api-21.2.1.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.message.boards.api/21.2.0/d0481f4d1d8ee4640b0e9472e5578c4eb232e3b7/com.liferay.message.boards.api-21.2.0.jar
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-07/test-1-39/test-portal-acceptance-pullrequest(master)/6167/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by catarineaguiar** [comment]
please, re-run relevant when fix the semver error.

Thanks!

**Comment by JanisZhang** [comment]
@catarineaguiar  Thanks！

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Pull request closed without merging**
