### PR TITLE
LPS-171358

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
Hi @david-truong @ctang3, could you please check if this is a bug as the list is always empty https://github.com/liferay-core-infra/liferay-portal/pull/2908/commits/45e4136cd4c7859a1afba497a5681e76b787f754

**Comment by catarineaguiar** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
@tinatian regression found:

```
     [exec] com.liferay.change.tracking.internal.conflict.test.CTColumnResolutionMaxTest > testUnresolvedModificationConflictMax FAILED
     [exec]     java.lang.AssertionError: {} expected:<1> but was:<0>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at com.liferay.change.tracking.internal.conflict.test.CTColumnResolutionMaxTest.testUnresolvedModificationConflictMax(CTColumnResolutionMaxTest.java:152)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-37/test-portal-acceptance-pullrequest(master)/7677/modules-integration-mysql57-jdk8_stable/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
@catarineaguiar I tested it locally, CTColumnResolutionMaxTest passed, could you please check it again?

Tina

**Comment by catarineaguiar** [comment]
@tinatian I double-checked and it passed here too. The pull is good to go.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128448

**Pull request closed without merging**
