### PR TITLE
[Remove Stream/Optional usage] LPS-173754 module: item-selector/item-selector-taglib

### PR DESCRIPTION
**Pull request by JanisZhang**
previous: https://github.com/liferay-core-infra/liferay-portal/pull/3167
Ticket: https://issues.liferay.com/browse/LPS-173754
Thanks!

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@JanisZhang Please make sure that after your change, the field, like `_groups`, is always assigned. This is to make it consistent with the original logic. Your change doesn't assign the field if the method is to return `Collections.emptyList()`.

**Comment by dantewang** [comment]
ci:stop

**Pull request closed without merging**
