### PR TITLE
[Performance]LPS-152440 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results when finished.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
@tinatian no regressions found.

**Comment by dantewang** [comment]
@slnn Could you rebase and resend?

**Comment by slnn** [comment]
Rebase and resend in https://github.com/liferay-core-infra/liferay-portal/pull/967

**Pull request closed without merging**
