### PR TITLE
[System Properties]LPS-165265 Move some properties that moduleFramework needs during init | part 2

### PR DESCRIPTION
**Pull request by W2jx**
default.liferay.home、resource.repositories.root、liferay.home

Dependency : https://github.com/liferay-core-infra/liferay-portal/pull/2175

### CODE REVIEW

**Comment by W2jx** [comment]
ci:help

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
@W2jx no regressions found.

**Comment by tinatian** [comment]
@W2jx "This pr is only for code review, so version conflicts will not be handled." What does this mean? Should I review this code or not?

**Pull request closed without merging**
