### PR TITLE
[Regression bug] LPS-153996

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian https://issues.liferay.com/browse/LPS-153996

This is a bug caused by https://github.com/liferay-core-infra/liferay-portal/pull/704, please see the ticket description and comment for the details.

My proposed fix in this PR is to add a new util to handle feature flag. It holds a cached JSON value to avoid impacting the performance, and updates the value when feature flag is set using it.

A drawback for this is the need to update document and communicate with anyone who use feature flags to use this util.

If we don't want a new class I can modify `PropsUtil` and `PropsValues` instead.

cc @vicnate5

@GinsonRen Please run a login diff on this PR. Thanks!

### CODE REVIEW

**Comment by GinsonRen** [comment]
@dantewang Here is the login diff result:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine(5-25 master head) | efc53b8 | 50656 | 294 | -
dantewang:LPS-153996-5-24 | https://github.com/liferay-core-infra/liferay-portal/pull/824 | 51794 | 299 | 2.25%

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 Could you check the test results? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/884

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
