### PR TITLE
[TS] LPD-21727

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__
<https://liferay.atlassian.net/browse/LPD-21727>

__Prev. Pull Request:__
<https://github.com/liferay-core-infra/liferay-portal/pull/6955>

As requested in <https://github.com/liferay-core-infra/liferay-portal/pull/6955>, I inlined Jalopy in `InstanceWrapperBuilder.java` so that we can remove the Jalopy dependency from Service Builder.

Let me know if there is anything missing from this PR.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:report:2569265509

**Comment by tinatian** [comment]
@kevhlee This pull can not be right. Please make sure you tested it locally.

You removed Jalopy logic in ToolsUtil, but service builder is using an old version of ToolsUtil from https://github.com/liferay-core-infra/liferay-portal/blob/6cb31200eda5752c4d276424f64abf0dbb2fe7a1/modules/util/portal-tools-service-builder/build.gradle#L45.

Also the first commit is hard to review as it is hard tell what you "simplify". Please see my examples how to show the changes clearly at https://github.com/kevhlee/liferay-portal/pull/136, please follow this pattern in your future pull for similar tasks.

Please resend.
Thanks.
Tina

**Pull request closed without merging**
