### PR TITLE
[Method References 2] LPS-171023 Convert method reference to ServiceTrackerMap in class IndexResourceImpl(module portal-workflow-metrics-rest-impl) 

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:workflow-metrics

**Comment by W2jx** [comment]
no conflicts(12/29 9:21)

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(1/3 8:56)

**Comment by W2jx** [comment]
no conflicts(1/4 9:03)

**Comment by W2jx** [comment]
no conflicts(1/5 8:59)

**Comment by tinatian** [comment]
@W2jx Please my last comment https://github.com/liferay-core-infra/liferay-portal/pull/2808#discussion_r1058021071, where is the enum class?

**Comment by tinatian** [comment]
@W2jx Without the enum class, your changes added so many hardcoded parameter which is hard to maintain.

**Comment by W2jx** [comment]
Sorry @tinatian , I think I was overcomplicating my thinking earlier. I'll fix it.

**Pull request closed without merging**
