### PR TITLE
LPS-145396 When we delete some types of objects in Liferay, we are not deleting their ResourcePermission records (includes test)

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
@tinatian Rebased from previous https://github.com/liferay-core-infra/liferay-portal/pull/281

When we delete some types of objects in Liferay, we are not deleting their ResourcePermission records, leaving some orphan data in the ResourcePermission table.

I have detected and solved this issue for some objects in previous LPSs, see: LPS-138985 (navigation menus), LPS-144653 (redirect entry urls), LPS-144733 (navigation menus), and LPS-144567 (asset libraries)

In this LPS I am solving the same issue for several objects (_ExpandoColumn, KBFolder, KaleoDefinitionVersion, LayoutBranch, MDRRuleGroup, MicroblogsEntry, OAuth2Application, Role_), but I am also adding a test rule that detects this issue in a deletion of any integration test, so we will detect future failures in new code / services, as soon as an integration test tests its deletion logic.

**Code changes:**
 - **Commits 1st to 3rd:** I am adding a new OrphanDetectionTestRule that tracks all the deleted objects and when the transaction is committed searches for orphan ResourcePermission records.
 - **Commits 5th to 13th and 16th**: I am fixing the deletion of the resource permission records for several objects
 - **Commit 14th:** Replace LocalServiceBaseImpl delete method calls with LocalServiceImpl ones, as the Base ones do not delete all the related objects.

The `OrphanDetectionTestRule` code registers a SessionWrapper and a TransactionLifecycleListener for each integration test executed.
They are registered/unregistered before DeleteAfterTestRunMethodTestRule because it generates some false positives, and before DataGuardTestRule because it deletes everything created during the test, so no Orphan can be checked.

You can see the output of the `OrphanDetectionTestRule` in this PR that only contains the tests without fixing the issues: https://github.com/jorgediaz-lr/liferay-portal/pull/424#issuecomment-1026190375

For example, the test **DLFileEntryLocalServiceTest.testCopyFileEntry** fails:
```
com.liferay.document.library.service.test.DLFileEntryLocalServiceTest.testCopyFileEntry

java.lang.AssertionError: Orphan ResourcePermission after the deletion of com.liferay.expando.kernel.model.ExpandoColumn: {"mvccVersion": 0, "ctCollectionId": 0, "columnId": 72685, "companyId": 20100, "tableId": 72684, "name": "ExpandoAttributeName", "type": 15, "defaultData": "", "typeSettings": ""} with backtraceInfo java.lang.Exception
  at com.liferay.portal.kernel.test.rule.OrphanDetectionTestRule$OrphanDetectionSessionWrapper._record(OrphanDetectionTestRule.java:147)
  at com.liferay.portal.kernel.test.rule.OrphanDetectionTestRule$OrphanDetectionSessionWrapper.delete(OrphanDetectionTestRule.java:122)
  at com.liferay.portlet.expando.service.persistence.impl.ExpandoColumnPersistenceImpl.removeImpl(ExpandoColumnPersistenceImpl.java:1939)
  at com.liferay.portlet.expando.service.persistence.impl.ExpandoColumnPersistenceImpl.removeImpl(ExpandoColumnPersistenceImpl.java:77)
  at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.remove(BasePersistenceImpl.java:666)
  at com.liferay.portlet.expando.service.persistence.impl.ExpandoColumnPersistenceImpl.removeByTableId(ExpandoColumnPersistenceImpl.java:869)
  at com.liferay.portlet.expando.service.impl.ExpandoTableLocalServiceImpl.deleteTable(ExpandoTableLocalServiceImpl.java:98)
```

Let me know if you need more information or if you prefer split this PR, with the test changes in a separated one.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relenvant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@jorgediaz-lr 
Thanks for making all these effort, I really like this idea!

I have some suggestions:
1. Instead of adding a test rule, it is possible that we add a separate integration test to detect this issue? If not, can we generate local service test for each model to detect this? 
    I am asking these questions because adding test rule may cause performance regression, and you may get similar detection result on different tests which is a waste of time, considering the slowness of ci test, I would like to seek for other solutions to detect this issue.
2. Yes, please try to split the pull into small pieces, which is easier for me to review and lower risk you get code conflicts.

Thanks.
Tina.

**Comment by tinatian** [comment]
@jorgediaz-lr I am going to close this pull as it has code conflicts, please resend based on my comment above.

Thanks.
Tina.

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

About your comment:

> Instead of adding a test rule, it is possible that we add a separate integration test to detect this issue? If not, can we generate local service test for each model to detect this?
> I am asking these questions because adding test rule may cause performance regression, and you may get similar detection result on different tests which is a waste of time, considering the slowness of ci test, I would like to seek for other solutions to detect this issue.

The idea of creating a test rule is to detect new orphan ResourcePermission records has two advantages:
  - It will catch the same issue in any new code that could be added in the future to the product.
  - It is easy to implement and it covers every code that deletes anything from Liferay.

It is true that the drawback is it could add some delay to all integration tests

My major concern is if we add a local service test for each current existing model that creates ResourcePermissions, the drawback is we won't catch this problem in new services that will be implemented in the future.

I was thinking that perhaps we could create a test that gets all the PersistedModelLocalServiceRegistry and create and destroy the entry in the database and after that, it checks the orphan record, but the major issue is we don't have a generic method to create the entry, every service has a different method to create it, with a different number of parameters and name.
_(The delete methods perhaps could be done in the same way it is done in the DataGuard code https://github.com/liferay/liferay-portal/blob/b0752d6239040f4c389b3fa8a9edb57628b51102/portal-test/src/com/liferay/portal/kernel/test/rule/DataGuardTestRuleUtil.java#L525-L548 )_

 - Do you have any other ideas?
 - Is it possible to measure in an easy way the execution time of all integration tests and compare the delay added by this code?
 - Should we discard the generic approach and go to the classic one of manually adding tests to every service?

Thank you,
Jorge

**Comment by tinatian** [comment]
Hi @jorgediaz-lr ,
Yes, I agree with you about the difficulty to create an independent integration test to detect this.

While, the current test rule solution is not only slow, but also it may cause duplicated warnings for same module on different tests which is hard to read.

Maybe we can add this for all the *LocalServiceTest:
`@DataGuard(autoDelete = false, scope = DataGuard.Scope.METHOD)`
You added this for CompanyLocalServiceTest to fix similar issues. We can add a SF rule to make sure all *LocalServiceTest having this to protect future code.

What do you think?

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

I like your idea of adding a annotation to activate the test and also add a SF rule to force using it.

This approach also allow us to add it gradually with smaller PRs.

I am going to analyze it and I will send a new PR.

Thank you,
Jorge

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

I have resent this code in four separated pull requests for an easier review, see: https://github.com/liferay-core-infra/liferay-portal/pull/365, https://github.com/liferay-core-infra/liferay-portal/pull/366, https://github.com/liferay-core-infra/liferay-portal/pull/367, and https://github.com/liferay-core-infra/liferay-portal/pull/368

Last PR https://github.com/liferay-core-infra/liferay-portal/pull/368 contains the changes in the tests, so it cannot be forwarded until the other ones are merged

**Pull request closed without merging**
