### PR TITLE
LPS-159166 Skip validations for Country and Region when populate them during company initialization

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:acceptance

**Comment by guilhermedcamacho** [comment]
@catarineaguiar please help me check the results, thanks!

**Comment by catarineaguiar** [comment]
@guilhermedcamacho no regressions found.

**Comment by guilhermedcamacho** [comment]
@shuyangzhou , this PR is ready for your review.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121084

**Pull request closed without merging**
