### PR TITLE
[TS] LPS-152595 The locale variation name is not written in the language selector

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by tinatian** [comment]
@jorgediaz-lr Code looks good to me, wait for QA to scan test results.

Tina.

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
@jorgediaz-lr please add some unit tests for this.

**Comment by jorgediaz-lr** [comment]
Hi @shuyangzhou 

I have added commit https://github.com/liferay-core-infra/liferay-portal/pull/706/commits/00338c4412e3a07d74af2d30a219a20e0315e797 with some unit tests

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
No regressions in new test results.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/117163

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
