### PR TITLE
[Urgent][Security Bugs]LPD-1558 Add captcha to avoid insufficient CSRF protection 

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This PR is for ticket https://liferay.atlassian.net/browse/LPD-1558.
In this PR, I added two new methods to accept the value from portlet and set them in the attributes, and use this value to override the maxchallenges for the current portlet.

Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:report:2557495040

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/jeffwu0724/liferay-portal/pull/462

**Pull request closed without merging**
