### PR TITLE
[TS] LPS-194611

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by yuhai** [comment]
@marianoalvarosaiz, please send it to liferay-commerce team to review.

**Comment by marianoalvarosaiz** [comment]
See https://github.com/liferay-commerce/liferay-portal/pull/4199

**Pull request closed without merging**
