### PR TITLE
[Remove unused reference] LPS-165292

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove unused fields in `headless-commerce-admin-channel-impl` . Thanks!

All tests passed in https://github.com/JanisZhang/liferay-portal/pull/148

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by dantewang** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/124754

cc @shuyangzhou @tinatian

**Pull request closed without merging**
