### PR TITLE
Lpd 22758 6 4 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:jdk21-unit

**Comment by julschong** [comment]
ci:report:10534803

**Comment by julschong** [comment]
ci:report:10466477

**Comment by julschong** [comment]
relevant no regression so this is good to go.

jdk21-unit has regression on some tests but these are excepted and we will fix:
com.liferay.portal.bootstrap.FrameworkRestartTest -> will need to fix test bacause it is using deprecated SecurityManager
com.liferay.portal.kernel.util.LocaleUtilTest -> CLDR
com.liferay.portal.search.web.internal.result.display.context.builder.SearchResultSummaryDisplayContextBuilderTest
com.liferay.portal.security.xml.SecureXMLFactoryProviderImplTest -> increase memory #7030
com.liferay.dynamic.data.mapping.form.field.type.internal.date.DateDDMFormFieldValueRendererTest -> CLDR
com.liferay.portal.search.elasticsearch7.internal.mappings.MaxExpansionsTest and other search tests -> sidecar option need add-open: `--add-opens=java.base/java.lang=ALL-UNNAMED`

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/151045

**Pull request closed without merging**
