### PR TITLE
[Blocker] LPS-204384 Use the PortletFileRepository service instead of the PortletFileRepositoryUtil class to avoid NPE

### PR DESCRIPTION
**Pull request by rafaprax**
https://liferay.atlassian.net/browse/LPS-204384

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
Hi @rafaprax ,

FYI, I haven't got a chance to check upgrade test results, below are CI relevant and startup test results.


`ci:test:relevant`

For these 2 failures:
1. https://testray.liferay.com/home/-/testray/case_results/2477459368
 the error also occurs in below git hash, so i think it's not related.
https://testray.liferay.com/home/-/testray/case_results/2476637638

    **Plus**, I rebuild to generate the csv file with first time relevant test build ID, it shows **no unique failure**.

2. https://testray.liferay.com/home/-/testray/case_results/2477460173 (Rafael confirmed not related.)

---

`ci:test:startup`

1. https://testray.liferay.com/home/-/testray/case_results/2477688352/history  
    Confirmed with QA, it doesn't reproduced during startup, should be unrelated.

2. https://testray.liferay.com/home/-/testray/case_results/2477688752/history 
    I ran poshi tested locally, and it passed. should be unrelated.

Below failures should be not releated, occurs on mutiple hash ID:
https://testray.liferay.com/home/-/testray/case_results/2477688443/history 
https://testray.liferay.com/home/-/testray/case_results/2477688689/history 
https://testray.liferay.com/home/-/testray/case_results/2477688402/history 
https://testray.liferay.com/home/-/testray/case_results/2477688629/history 
https://testray.liferay.com/home/-/testray/case_results/2477688562/history
https://testray.liferay.com/home/-/testray/case_results/2477688554/history
https://testray.liferay.com/home/-/testray/case_results/2477688644/history
https://testray.liferay.com/home/-/testray/case_results/2477688565/history
https://testray.liferay.com/home/-/testray/case_results/2477688568/history
https://testray.liferay.com/home/-/testray/case_results/2477688617/history
https://testray.liferay.com/home/-/testray/case_results/2477688670/history
https://testray.liferay.com/home/-/testray/case_results/2477688584/history
https://testray.liferay.com/home/-/testray/case_results/2477688673/history
https://testray.liferay.com/home/-/testray/case_results/2477688637/history
https://testray.liferay.com/home/-/testray/case_results/2477688600/history
https://testray.liferay.com/home/-/testray/case_results/2477688578/history
https://testray.liferay.com/home/-/testray/case_results/2477688591/history
https://testray.liferay.com/home/-/testray/case_results/2477688624/history
https://testray.liferay.com/home/-/testray/case_results/2477688601/history
https://testray.liferay.com/home/-/testray/case_results/2477688457/history
https://testray.liferay.com/home/-/testray/case_results/2477688522/history
https://testray.liferay.com/home/-/testray/case_results/2477688765/history
https://testray.liferay.com/home/-/testray/case_results/2477688682/history
https://testray.liferay.com/home/-/testray/case_results/2477688395/history
https://testray.liferay.com/home/-/testray/case_results/2477688366/history
https://testray.liferay.com/home/-/testray/case_results/2477688609/history
https://testray.liferay.com/home/-/testray/case_results/2477688628/history
https://testray.liferay.com/home/-/testray/case_results/2477688620/history
https://testray.liferay.com/home/-/testray/case_results/2477688665/history
https://testray.liferay.com/home/-/testray/case_results/2477688668/history
https://testray.liferay.com/home/-/testray/case_results/2477688552/history
https://testray.liferay.com/home/-/testray/case_results/2477688559/history
https://testray.liferay.com/home/-/testray/case_results/2477688564/history
https://testray.liferay.com/home/-/testray/case_results/2477688585/history
https://testray.liferay.com/home/-/testray/case_results/2477688557/history
https://testray.liferay.com/home/-/testray/case_results/2477688555/history
https://testray.liferay.com/home/-/testray/case_results/2477688570/history

**Comment by rafaprax** [comment]
Hi all, I checked the `ci:test:upgrade` results and they are unrelated to these changes. Below is the analysis for https://test-1-1.liferay.com/job/generate-testray-csv/7458/ report:

1. https://testray.liferay.com/home/-/testray/case_results/2477811241  | 🟢  not related
2. https://testray.liferay.com/home/-/testray/case_results/2477810717  | 🟡  propably related to LPS-199958
3. https://testray.liferay.com/home/-/testray/case_results/2477811146  | 🟡   propably related to LPS-199958
4. https://testray.liferay.com/home/-/testray/case_results/2477810475 | 🟢 not related
5. https://testray.liferay.com/home/-/testray/case_results/2477811198  | 🟢 not related
6. https://testray.liferay.com/home/-/testray/case_results/2477810841  | 🟡  propably related to LPS-199958
7. https://testray.liferay.com/home/-/testray/case_results/2477810746  | 🟢 not related
8. https://testray.liferay.com/home/-/testray/case_results/2477811181   | 🟢 not related

Thanks

**Comment by rafaprax** [comment]
Hey @shuyangzhou, this blocker is ready to go. Thanks

**Comment by rafaprax** [comment]
ci:forward:force

/cc @shuyangzhou @tinatian

**Pull request closed without merging**
