### PR TITLE
[Remove Stream/Optional usage] LPS-175075 modules: data-engine-rest-impl, configuration-admin-web

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend, previous: https://github.com/liferay-core-infra/liferay-portal/pull/3391
Thanks!
https://issues.liferay.com/browse/LPS-175075

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:ata-engine

**Comment by zhangyan0701** [comment]
ci:test:data-engine

**Comment by zhangyan0701** [comment]
ci:test:usm

**Comment by Kvale1733** [comment]
@JanisZhang No regressions.

**Pull request closed without merging**
