### PR TITLE
LPS-152300 Remove petra-salesforce-client

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,

Main Task: [LPS-147928 Remove petra jar from modules/apps](https://issues.liferay.com/browse/LPS-147928)
Sub Task: [LPS-152300 Remove petra-salesforce-client](https://issues.liferay.com/browse/LPS-152300)

Previously testing in my repo here: https://github.com/julschong/liferay-portal/pull/335

Thank you!

### CODE REVIEW

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina.

**Comment by julschong** [comment]
ci:test:acceptance

**Comment by julschong** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@julschong no regressions related to your changes were found. I wasn't able to understand the SF error, and I believe the semver error is not related to the PR.

```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/product-navigation/product-navigation-product-menu-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.product.navigation.product.menu.constants MAJOR      1.1.0      1.1.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	-   class      com.liferay.product.navigation.product.menu.constants.ProductNavigationProductMenuWebKeys
     [exec]     		-   field      PRODUCT_NAVIGATION_PRODUCT_MENU_STATE
     [exec]     			-   access     final
     [exec]     			-   access     static
     [exec]     			-   constant   com.liferay.product.navigation.product.menu.web_productMenuState
     [exec]     			-   return     java.lang.String
     [exec]     		-   method     <init>()
     [exec]     			-   return     void
     [exec]     		-   method     clone()
     [exec]     			-   access     protected
     [exec]     			-   return     java.lang.Object
     [exec]     		-   method     equals(java.lang.Object)
     [exec]     			-   return     boolean
     [exec]     		-   method     finalize()
     [exec]     			-   access     protected
     [exec]     			-   return     void
     [exec]     		-   method     hashCode()
     [exec]     			-   return     int
     [exec]     		-   method     toString()
     [exec]     			-   return     java.lang.String
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 5.0.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertFalse(Assert.java:64)
     [exec]         at com.liferay.semantic.versioning.SemanticVersioningTest.testSemanticVersioning(SemanticVersioningTest.java:82)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-27/test-portal-acceptance-pullrequest(master)/3232/modules-semantic-versioning-jdk8/0/6/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine, 
I think the sf error is unrelated since I didn't change that part of the code.

**Comment by catarineaguiar** [comment]
Yes @julschong, did you rebase your branch? Maybe it would be fixed already.

**Comment by julschong** [comment]
Will do now

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine, ya seems unrelated

**Comment by catarineaguiar** [comment]
Yes, its unrelated. @julschong

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/117356

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
