### PR TITLE
LPS-145235 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Regression here with log context.

#### 1. Functional test failure with xRequestId
Steps to Reproduce:
1. Add config file `com.liferay.portal.security.audit.wiring.internal.configuration.AuditLogContextConfiguration.config`
```
enabled="true"
useIncomingXRequestId="true"
```
2. Start Portal
3. Execute curl `curl -X GET -H 'X-Request-Id:oYTPuXlcVmKgVLk0mhK3SH0d7RDbKn3ULmN8xaNn' http://localhost:8080/api/jsonws/user/get-user-by-email-address/company-id/email-address`

Expected Result: Returns ERROR with context and matching xRequestId 
```
ERROR [http-nio-8080-exec-2][JSONWebServiceServiceAction:126] {AuditLogContext{"clientIP":"127.0.0.1","companyId":"20099","emailAddress":"","serverName":"localhost","sessionId":"+jOV/7D/0AYVaOXzRrlMc3Vk59XtI1s85WhwQmtYdvI=","userId":"","virtualHostName":"localhost","xRequestId":"oYTPuXlcVmKgVLk0mhK3SH0d7RDbKn3ULmN8xaNn"}}No JSON web service action with path /user/get-user-by-email-address and method GET for null
```

Actual Result: Returns ERROR **without** context
```
ERROR [http-nio-8080-exec-2][JSONWebServiceServiceAction:126] No JSON web service action with path /user/get-user-by-email-address and method GET for null
```
CI Result: https://testray.liferay.com/home/-/testray/case_results/1610840272

#### 2. Integration test failure: PortalLog4jTest
Steps to Reproduce:
1. Start Portal
2. Navigate to modules/apps/portal/portal-log4j-test
3. Execute `gw testIntegration`

Result: 
```
com.liferay.portal.log4j.test.PortalLog4jTest > testLogOutputWithLogContext FAILED
    org.junit.ComparisonFailure: expected:<[{TestLogContext{"test.key.1":"test.value.1","test.key.2":"test.value.2"}}]DEBUG message> but was:<[]DEBUG message>
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at com.liferay.portal.log4j.test.PortalLog4jTest._assertTextLog(PortalLog4jTest.java:304)
        at com.liferay.portal.log4j.test.PortalLog4jTest._testLogOutput(PortalLog4jTest.java:551)
        at com.liferay.portal.log4j.test.PortalLog4jTest._testLogOutput(PortalLog4jTest.java:523)
        at com.liferay.portal.log4j.test.PortalLog4jTest.testLogOutputWithLogContext(PortalLog4jTest.java:194)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
        at java.lang.Thread.run(Thread.java:748)
```
CI result: https://testray.liferay.com/home/-/testray/case_results/1610845331

**Comment by tinatian** [comment]
@jkappler Could you please take a look at the test failures? Are those still expected behaviors? 

Thanks.
Tina

**Comment by jkappler** [comment]
Hi @tinatian, will take a look

**Comment by jkappler** [comment]
Hi @tinatian, I was checking this today, and it's the expected behavior (the integration test that's failing) with the current configuration. It should work if the Appender is changed in portal-log4j.xml from

```
<Appender name="CONSOLE" type="Console">
    <Layout pattern="%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%t][%c{1}:%L] %m%n" type="PatternLayout" />
</Appender> 
```

to

```
<Appender name="CONSOLE" type="Console">
    <Layout pattern="%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%t][%c{1}:%L] %m%n %X" type="PatternLayout" />
</Appender> 
```

so as to add the ThreadContext map to the log.

This would produce something like this

```
2022-02-15 15:32:30.326 DEBUG [com.liferay.portal.log4j.test-executor-thread][PortalLog4jTest:455] DEBUG message
 {TestLogContext.test.key.1=test.value.1, TestLogContext.test.key.2=test.value.2}
```

I wanted to change the integration test to take it into account, but didn't manage to do it. From what I know, portal-log4j.xml is read when portal starts. If you could guide me into how to change it so that it can be taken into account I can make the changes. I'll also take a look at the first issue.

What I find weird is that the test didn't fail when Eduardo send you the PR, so maybe something has changed since then.

Thanks again for reviewing the PR and helping us out with this!

**Comment by jkappler** [comment]
Also, same will happen with the first issue, because of how logs are configured. 

After checking this, I'm now unsure if we would be breaking clients code (if they check for logs), since before, we would always show the context, now we don't, only if it's configured to do so.

Please let me know what you think @tinatian

**Comment by tinatian** [comment]
@jkappler 
So to make the behavior consistent with before, when AuditLogContextConfiguration is set to enabled and "%X" is not set ,two options:
1)  use the old way (adding context to log message by ourselves) to log out the context info, for this option, when "%X" is set, you should disable the old way.
2)  set up "%X" programmingly at runtime. When AuditLogContextConfiguration is set to enabled, you should check if "%X" is configured, if not, configure it programmingly at runtime.

Another option is to change the behavior, you can only enable AuditLogContextConfiguration when you set "%X", this is going to affect customers, but I am not sure how big the effect would be, it depends on how many users using this feature, also we need to get approval from your product manager and document this change.

I am going to close this pull and please resend a pull when you made a decision which way to go.

Tina.

**Comment by jkappler** [comment]
Hi @tinatian, resent here. Mentioned in the description the approach that we followed at the end

https://github.com/liferay-core-infra/liferay-portal/pull/351

**Pull request closed without merging**
