### PR TITLE
LPS-175235 "fields" query parameter does not work when it is executedover a System Object

### PR DESCRIPTION
**Pull request by ces-locpham**
Hi team,
Please help me review this ticket.
This PR is for ticket https://issues.liferay.com/browse/LPS-175235 . 
Thanks,
Loc
cc:@taiphamlr

### CODE REVIEW

**Comment by TaiPhamLR** [comment]
Motivation
=======

This work solves the problem reported in the ticket https://issues.liferay.com/browse/LPS-175235 .

Proposed Solution
========

Cause:
   When we perform any request GET (by id) any objects are considered a System Object, the entry will be put in to an ExtendedEntity instance (see EntityExtensionWriterInterceptor#_extendEntity).
as field  `entity`. If we perform request Get with `filter` (ex: ?filter=externalReferenceCode), the VulcanPropertyFilter#serializeAsField would ignore `entity` property and cound not "see" `externalReferenceCode`
The result would be empty json: `{}`

What we did to solve this problem:
At class EntityExtensionWriterInterceptor, we get Fields Query Param and Restrict Fields Query Param from the context and pass them to ExtendedEntity.
And we process them, then put field name and field value of the entity to `_extendedProperties`

Steps to Verify
========

- Perform the following request (replace the id 20124 with an existing one): 
`curl -X GET -u 'test@liferay.com:test' http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/20124`
- The response should be something like:
<details>
<summary>
Json string:
</summary>
<p>
```yaml
{
  "accountBriefs" : [ ],
  "actions" : {
    "get-user-account-by-external-reference-code" : {
      "method" : "GET",
      "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/by-external-reference-code/20124"
    },
    "put-user-account" : {
      "method" : "PUT",
      "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/20124"
    },
    "delete-user-account" : {
      "method" : "DELETE",
      "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/20124"
    },
    "get-user-account" : {
      "method" : "GET",
      "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/20124"
    },
    "delete-user-account-by-external-reference-code" : {
      "method" : "DELETE",
      "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/by-external-reference-code/20124"
    },
    "put-user-account-by-external-reference-code" : {
      "method" : "PUT",
      "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/by-external-reference-code/20124"
    },
    "get-my-user-account" : {
      "method" : "GET",
      "href" : "http://localhost:8080/o/headless-admin-user/v1.0/my-user-account"
    },
    "patch-user-account" : {
      "method" : "PATCH",
      "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/20124"
    }
  },
  "additionalName" : "",
  "alternateName" : "test",
  "birthDate" : "1970-01-01T00:00:00Z",
  "customFields" : [ ],
  "dashboardURL" : "/user/test",
  "dateCreated" : "2023-02-08T10:01:13Z",
  "dateModified" : "2023-02-09T08:22:45Z",
  "emailAddress" : "test@liferay.com",
  "externalReferenceCode" : "8b8b59b0-0362-70e1-3b2d-98fd3454ed84",
  "familyName" : "Test",
  "givenName" : "Test",
  "id" : 20124,
  "jobTitle" : "",
  "keywords" : [ ],
  "lastLoginDate" : "2023-02-08T16:08:12Z",
  "name" : "Test Test",
  "organizationBriefs" : [ ],
  "profileURL" : "/web/test",
  "roleBriefs" : [ {
    "id" : 20102,
    "name" : "Administrator"
  }, {
    "id" : 20106,
    "name" : "Power User"
  }, {
    "id" : 20108,
    "name" : "User"
  } ],
  "siteBriefs" : [ {
    "descriptiveName" : "Global",
    "id" : 20122,
    "name" : "Global"
  }, {
    "descriptiveName" : "Liferay DXP",
    "id" : 20120,
    "name" : "Guest"
  } ],
  "userAccountContactInformation" : {
    "emailAddresses" : [ ],
    "facebook" : "",
    "jabber" : "",
    "postalAddresses" : [ ],
    "skype" : "",
    "sms" : "",
    "telephones" : [ ],
    "twitter" : "",
    "webUrls" : [ ]
  },
  "userGroupBriefs" : [ ]
}
```
</p>
</details>

- Perform the following request including the `fields` query parameter with an existing field:
`curl -X GET -u 'test@liferay.com:test' http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/20124?fields=externalReferenceCode`

*Expected behaviour:
- The response should contain only the `externalReferenceCode` field:
`{
  "externalReferenceCode" : "8b8b59b0-0362-70e1-3b2d-98fd3454ed84"
}`

*Current behaviour:

- The response is an empty JSON:
`{ }`

**Comment by catarineaguiar** [comment]
ci:test:headless

**Comment by Kvale1733** [comment]
@locpham97 Regression found in 
com.liferay.portal.vulcan.internal.jaxrs.writer.interceptor.EntityExtensionWriterInterceptorTest
```
 [exec] com.liferay.portal.vulcan.internal.jaxrs.writer.interceptor.EntityExtensionWriterInterceptorTest > testAroundWriteWithNoExtendedProperties FAILED
     [exec]     java.io.IOException: java.lang.NullPointerException
     [exec]         at com.liferay.portal.vulcan.internal.jaxrs.writer.interceptor.EntityExtensionWriterInterceptor._extendEntity(EntityExtensionWriterInterceptor.java:94)
     [exec]         at com.liferay.portal.vulcan.internal.jaxrs.writer.interceptor.EntityExtensionWriterInterceptor.aroundWriteTo(EntityExtensionWriterInterceptor.java:56)
     [exec]         at com.liferay.portal.vulcan.internal.jaxrs.writer.interceptor.EntityExtensionWriterInterceptorTest.testAroundWriteWithNoExtendedProperties(EntityExtensionWriterInterceptorTest.java:217)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-02/test-1-36/test-portal-acceptance-pullrequest(master)/3041/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by TaiPhamLR** [comment]
Thanks for your review @Kvale1733. I've fixed the unit test at EntityExtensionWriterInterceptorTest. I'm looking forward to your next review.

**Comment by ccorreagg** [comment]
Hi @TaiPhamLR , 

I think this PR should be reviewed by headless team. (liferay-headless)

cc @4lejandrito

**Pull request closed without merging**
