### PR TITLE
LPD-25362

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:34722559

**Comment by tinatian** [comment]
ci:report:34958162

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 34958162.
> 
> Job Link: [generate-testray-csv](https://test-1-2.liferay.com/job/generate-testray-csv/75/)
> 
> Testray CSV Link: [testray-results-34958162.csv](https://test-1-2.liferay.com/userContent/jobs/generate-testray-csv/builds/75/testray-results-34958162.csv)

Unique failures in report are not unique to this pull

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/152238

**Pull request closed without merging**
