### PR TITLE
[TS] LPD-29738

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian The race condition explanation is in https://liferay.atlassian.net/browse/LPD-29738, I wonder if there's any better way (e.g. not using synchronized). @JerryAdrianoo please run a startup comparison, thanks.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:27338456

**Comment by JerryAdrianoo** [comment]
Hey @dantewang  for more details from this test, see: [spreadsheet](https://docs.google.com/spreadsheets/d/1vcbkovxSSEqhL0w2ZpmpUaXTg5KAz2Zfjdby1hSODu4/edit?usp=sharing) 
Branch| Startup Time (ms)(without  default HSQL data)  Cold start | Percent of Average Startup Time Cold Start | Startup Time (ms)(without  default HSQL data) Hot start | Average Startup Time (ms)(without default HSQL data)  Hot start | Percent of Average Startup Time Hot Start | Shutdown Time (ms)(without default HSQL data)   Cold start | Shutdown Time (ms)(without default HSQL data)  Hot start | Average Shutdown Time (ms)(without default HSQL data)  Hot start
-- | -- | -- | -- | -- | -- | -- | -- | --
Before LPD-29738 | **42,103** | | 16,916 | | | **2,705** | 1,946
|  | | | 16,908 | | | | 1,993
|  | | | 16,744 | | | | 1,962
 | | | | 16,893 | | | | 2,082
 | | | | 16,137 |**16,848** | | | 2,006 | **1,987**
-- | -- | -- | -- | -- | -- | -- | --
After LPD-29738 | **41,744** | | 16,050 | | | **2,763** | 1,985
|  | | | 16,789 | | | | 1,939
|  | | | 16,566 | | | | 1,997
|  | | | 16,542 | | | | 2,093
| | |  -0.85% | 16,689 |**16,599** |  **-1.48**% | | 1,978 | **1,987**

Please let me know if you need something else.

**Comment by dantewang** [comment]
@JerryAdrianoo Thanks!

**Comment by dantewang** [comment]
ci:report:27384721

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 27338456.
> 
> Job Link: [generate-testray-csv](https://test-1-9.liferay.com/job/generate-testray-csv/143/)
> 
> Testray CSV Link: [testray-results-27338456.csv](https://test-1-9.liferay.com/userContent/jobs/generate-testray-csv/builds/143/testray-results-27338456.csv)

- `LocalFile.OSGIConfiguration#OSGIConfigFileUpdatesExistingConfigInDatabase`: not unique, happened more than 20 days ago
- `LocalFile.OSGIConfiguration#RecreateDefaultFactoryConfig`: not unique, happened more than 20 days ago
- `LocalFile.ClusteringScheduler#PersistentAndMemoryJobs`: error happened with other jobs

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:27910934

**Comment by tinatian** [comment]
@dantewang Let's do this, create an internal class to address all the caches in PortletLocalService.

**Pull request closed without merging**
