### PR TITLE
[Remove Blocking usages]LPS-189701 bean-portlet | CDIBeanPortletExtension, SpringBeanPortletExtension

### PR DESCRIPTION
**Pull request by W2jx**
Resend

Changes:

1. Make BeanPortletRegistrarBag immutable
2. Remove BeanPortletRegistrar api and have a service tracker in class BeanPortletRegistrarBagRegistry to track the BeanPortletRegistrarBag and do the register directly

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4929

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:portlet-deployment

**Comment by W2jx** [comment]
ci:test

**Comment by W2jx** [comment]
ci:test:jsf

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(7/27 8:21)

**Comment by W2jx** [comment]
no conflicts(7/28 9:24)

**Comment by W2jx** [comment]
no conflicts(7/31 11:22)

**Comment by dantewang** [comment]
@W2jx 
1. Please don't include the commits about https://github.com/liferay-core-infra/liferay-portal/pull/5096/commits/87172d69e0651c81c7e0dd12cfb4ff07859d9b1f, they seem irrelevant with what you want to do.
2. I think it's better to directly add the service tracker to `BeanPortletRegistrar` and maybe rename that class in place. This way we can see the full history of it in the future.

**Comment by dantewang** [comment]
@W2jx Please resend, thanks!

**Pull request closed without merging**
