### PR TITLE
LPS-160250 & LPS-173444 Refactor verifiers and store bundleSymbolicName in the Release

### PR DESCRIPTION
**Pull request by achaparro**
The passed in the uniform repo:
https://github.com/liferay-uniform/liferay-portal/pull/943

@shuyangzhou Finally I did not need an upgrade process to upgrade the release record in some cases because the only verifiers whose name was different than the symbolic name were refactor in this pull to upgrade processes.

@111Anna would you mind to execute the startup tests again? We reduced the number of queries on startup.

Thanks!

From the latest pull:
As we agreed, I have added the possibility to choose if the developer want a verify process to run on every upgrade, by default is false. So the logic is:

-   InitialDeployment verifiers run the first time the module is deployed (default false)
-   RunonPortalUpgrade verifiers run anytime an upgrade is executed (default false)
-   All verifiers run anytime their module is upgraded

Additionally, I have modified the framework so non-service module verifiers work in the same way as service module verifiers.

cc/ @vicnate5 @susanchen3

### CODE REVIEW

**Comment by 111Anna** [comment]
Hi @achaparro, I ran the startup test again, here are the test results:

CE
Portal Version|GitId|Average Startup (ms)|%|Average Shutdown (ms)|%|Open File|Thread Create|Open Prepared Statement|Open SQL
--|--| --|--|--|--|--|--|--|--|
Baseline| faf682e| 23130 |- |3256.3|-| 1833 | 102 | 508| 1008 |
Baseline + PR-3311| - | 23161 |-0.1%| 3260.3|-0.1%| 1834 | 101 | 506 | 1011 |


DXP
Portal Version|GitId|Average Startup (ms)|%|Average Shutdown (ms)|%|Open File|Thread Create|Open Prepared Statement|Open SQL
--|--| --|--|--|--|--|--|--|--|
Baseline| faf682e| 25192 |- |4008|-| 1989 | 114| 554| 1098 |
Baseline + PR-3311| - |  25279.3 |-0.3%| 3927.3|2.0%| 1990 | 114 | 564 | 1101 |

**Comment by achaparro** [comment]
Thank you @111Anna!

These are better numbers :-) Let see what @shuyangzhou thinks.

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by shuyangzhou** [comment]
Resent at https://github.com/liferay-core-infra/liferay-portal/pull/3316
@111Anna please recheck, thanks!

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
