### PR TITLE
[Static reference] LPS-182294 Remove method reference by using snapshot in module dynamic-data-mapping-form-web

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:help

**Comment by zhangyan0701** [comment]
ci:test:forms

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(4/21 8:22)

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
