### PR TITLE
LPD-17766 Upgrade Jboss Weld to work with JDK21

### PR DESCRIPTION
**Pull request by julschong**
@tinatian @dantewang 
This PR just upgrade weld to 3.1.1.Final and has same result as when we patched.
Tested locally and passed.
CI tested passed both jdk8 and jdk21 here: https://github.com/julschong/liferay-portal/pull/1153#issuecomment-1960648035

This should be good to go.

Side note, 
I found out why locally sometimes the funtional test would fail locally.
It was because if I test it the 2nd time, the sample-bean-portlet war is already deployed there so on startup it already displays the message that the portlet is ready to use. But later on, when the functional test actually redeploys and processes the war. Functional test does not wait for it to be done processing because the portlet ready to use message is already there. Then, it fails. 
What a trip...

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:report:2542401726

**Comment by julschong** [comment]
no unique failure on relecant

**Comment by tinatian** [comment]
@julschong Nice job! Please see https://github.com/brianchandotcom/liferay-portal/pull/147506

**Pull request closed without merging**
