### PR TITLE
[TS] LPS-201076

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by Kvale1733** [comment]
@marianoalvarosaiz No regressions found. Found the cause of https://liferay.atlassian.net/browse/LPS-201589 and reverted it to test this. There was no issues.

**Comment by yuhai** [comment]
@marianoalvarosaiz, the current sf will hint the errors. You can see the error by running "gradlew formatSource" from marketplace-api module. Could you please check this?

In addition, I find `SystemBundleUtil.getBundleContext()` is used in the test classes of modules for the most cases. In module, the normal way `bundle.getBundleContext()` is used.  I suggest we follow with the normal way, just like:

```
private static final BundleContext _bundleContext;

	static {
		Bundle bundle = FrameworkUtil.getBundle(BundleManagerUtil.class);

		BundleContext bundleContext = bundle.getBundleContext();

		_bundleContext = bundleContext;
	}
```

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
@yuhai done!

**Review by yuhai — APPROVED** [review]
@dantewang, the pr is good to me.

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
