### PR TITLE
[TS] LPS-157843 | Getting Exception when inserting records in database with sequence id after 7.4.3.31 GA31 update

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @liferay-core-infra team,

This is a solution for the issue [LPS-157843](https://issues.liferay.com/browse/LPS-157843) that started happening after the change of Hibernate version in [LPS-128873](https://issues.liferay.com/browse/LPS-128873). 

Although it wasn't well documented, in Hibernate 5.0 the value used for the generator parameter name when `class="sequence"` in `module-hbm.xml` changed from `"sequence"` to `"sequence_name"`. It seems this wasn't well documented and I've only found [this thread in the Hibernate community forum](https://forum.hibernate.org/viewtopic.php?p=2488475) and [this comment in a Hibernate ticket](https://hibernate.atlassian.net/browse/HHH-11649?focusedCommentId=93250).

Since the change [LPS-128873](https://issues.liferay.com/browse/LPS-128873) is only in 7.4 and hasn't been backported yet, the solution check the version to be at least 7.4. We should really be checking if it's at least the Update 21, which is when [LPS-128873](https://issues.liferay.com/browse/LPS-128873) was introduced, but I don't think we can be so discriminating. This means that users building their services for a Liferay DXP under Update 21 should use a Service Builder without this pr solution and those above Update 21 should. 

Please let me know if you have any questions. 

Thanks!

### CODE REVIEW

**Comment by tinatian** [comment]
@ricardocousolr Please add an integration test to expose this issue inside portal-tools-service-builder-test-test

**Comment by tinatian** [comment]
@yuhai Please verify the fix

**Comment by yuhai** [comment]
@ricardocousolr, the fix is good to me.  I resend it to https://github.com/liferay-core-infra/liferay-portal/pull/3909, except the test codes.

**Comment by tinatian** [comment]
@yuhai It is because we do not have test, we missed this when upgrade, let's add the test, I do not want to see it fail another time.

**Pull request closed without merging**
