### PR TITLE
LPS-168749 change compileInclude to compileOnly for org.apache.httpcomponents

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Listed all the packages to export rather than using *
As Tina mentioned [here](https://github.com/liferay-core-infra/liferay-portal/pull/2537#issuecomment-1332672814). I will not add httpclient-cache to shared-dependencies for now since there is only one usage.
Resent: For the discussion https://github.com/liferay-core-infra/liferay-portal/pull/2477#issuecomment-1322552202, I tried to delete it and run the test, and it will throw error https://github.com/jeffwu0724/liferay-portal/pull/184#issuecomment-1325659433. It is because group: "net.shibboleth.utilities", name: "java-support" has a compiled dependencies on httpclient-cache. Please see [commit](https://github.com/liferay/liferay-portal/commit/7988b387a961dba7ac26ae2b6c9eac9c8c9f778e).
Therefore, in order to keep org.apache.httpcomponents consistent, I will keep httpclient-cache in shared-dependencies at this moment.

This is for ticket https://issues.liferay.com/browse/LPS-168749.
I tried to change compileInclude to compileOnly for org.apache.httpcomponents,because org.apache.httpcomponents has been added to shared-dependencies before.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
fixed the code conflict in versions.html by auto-generate, the old test result should be still good

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by tinatian** [comment]
@jeffwu0724 Code looks good to me, code conflicts with BChan's upstream, please rebase after related changes merged in.

Thanks.
Tina

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127999

**Pull request closed without merging**
