### PR TITLE
remove_deprecated_part_6

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

I remove deprecated for
"portal-impl/src/com/liferay/portlet/documentlibrary/service/impl" - DLApp
"portal-impl/src/com/liferay/portlet/documentlibrary/service/impl" - DLFolder
"portal-impl/src/com/liferay/portlet/documentlibrary/service/impl" - DLFileEntry
"portal-impl/src/com/liferay/portlet/documentlibrary/service/permission"
"portal-impl/src/com/liferay/portlet/documentlibrary/store"
"portal-impl/src/com/liferay/portlet/documentlibrary/util"
"portal-impl/src/com/liferay/portlet/social/service/impl/SocialActivityLocalServiceImpl.java"
Thanks for checking. Also see https://github.com/jeffwu0724/liferay-portal/pull/32

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by tinatian** [comment]
@jeffwu0724 Search "DLFileEntryLockListener" in portal.properties, you will see the class you removed is still referenced, please remove it and update this pull.

**Comment by tinatian** [comment]
ci:help

**Comment by tinatian** [comment]
ci:test:help

**Comment by tinatian** [comment]
ci:test:dl-store

**Comment by tinatian** [comment]
ci:test:document

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:dl-store

**Comment by jeffwu0724** [comment]
ci:test:document

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by kyle-miho** [comment]
Im analyzing this right now @tinatian @vicnate5

**Comment by kyle-miho** [comment]
@jeffwu0724 
 [exec] > Task :apps:document-library:document-library-preview-audio-test:compileTestIntegrationJava FAILED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/document-library/document-library-preview-audio-test/src/testIntegration/java/com/liferay/document/library/preview/audio/test/DLAudioFFMPEGAudioConverterTest.java:137: error: incompatible types: byte[] cannot be converted to File
     [exec] 			FileUtil.getBytes(getClass(), fileName), _serviceContext);
 
 A compile error happened on this pull, by looking on the test history, it seems to only happen here but it seems to be unrelated, did you make any changes to integration test files or to FileUtil?

**Comment by kyle-miho** [comment]
ci:test:document
Ill rerun to be sure

**Comment by jeffwu0724** [comment]
> 

Hey Kyle, thanks for checking! I don't think I made any changes to integration test files or to FileUtil though.

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:document

**Comment by jeffwu0724** [comment]
Hey @[kyle-miho](https://github.com/kyle-miho), I found the bug and fix this compile error. Thanks for helping me! I gonna rerun the test now, and please help me scan again when it is ready.

Best,
Jeff

**Comment by kyle-miho** [comment]
@jeffwu0724 :apps:document-library:document-library-test also encountered this, i didnt find it anywhere else if you found the issue with order modules already, other than that this pr should be good to go

**Comment by jeffwu0724** [comment]
> @jeffwu0724 :apps:document-library:document-library-test also encountered this, i didnt find it anywhere else if you found the issue with order modules already, other than that this pr should be good to go

Thank you Kyle. Yes I have fixed the bug based on the error log you gave, and I rerun it and did not find other other at this moment.

**Comment by tinatian** [comment]
ci:test:document

**Comment by tinatian** [comment]
ci:test:dl-store

**Comment by kyle-miho** [comment]
pr should be good to go

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114345

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
