### PR TITLE
LPS-168934 Clean up Dom4jUtil toString usages

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
classMethod in some document.library integration tests failed:

[com.liferay.document.library.webdav.test.WebDAVLitmusCopyMoveTest](https://testray.liferay.com/home/-/testray/case_results/2061589988)
[com.liferay.document.library.webdav.test.WebDAVOSXTest](https://testray.liferay.com/home/-/testray/case_results/2061590048)
`java.lang.ClassNotFoundException: com.liferay.portal.webdav.methods.LockMethodImpl`

Full console:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-39/test-portal-acceptance-pullrequest(master)/1739/modules-integration-mysql57-jdk8/1/14/jenkins-console.txt.gz?authuser=0

[com.liferay.document.library.webdav.test.WebDAVLitmusBasicTest](https://testray.liferay.com/home/-/testray/case_results/2061589985)
`java.lang.NoClassDefFoundError: Could not initialize class com.liferay.portal.webdav.methods.MethodFactoryImpl$MethodHolder`

Full console:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-39/test-portal-acceptance-pullrequest(master)/1739/modules-integration-mysql57-jdk8/1/13/jenkins-console.txt.gz?authuser=0

**Comment by julschong** [comment]
no longer removing LockMethodImpl and PropfindMethodImpl

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong 
Only found Semver error. Not sure if it's related. No regressions found in all other test.
```
[sync-dir] 0 files synchronized in 999ms
     [echo] Executing Gradle task: baseline
     [exec] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
     [exec] > Task :classes UP-TO-DATE
     [exec] > Task :jar SKIPPED
     [exec] 
     [exec] > Task :baseline
     [exec] [Baseline Warning] Bundle Version Change Recommended: 61.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-impl/portal-impl.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.impl/60.0.0/bee47ecf681e146e05a63583641aa08677f47890/com.liferay.portal.impl-60.0.0.jar
     [exec] Gradle build finished at 2022-11-18 20:28:01.075. 
```
[Log](https://testray.liferay.com/reports/production/logs/2022-11/test-1-33/test-portal-acceptance-pullrequest(master)/2455/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
pushed to fix semver

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by julschong** [comment]
rebased for conflict in semver

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by julschong** [comment]
@tinatian closing this per our discussion

**Comment by catarineaguiar** [comment]
ci:stop:relevant

**Pull request closed without merging**
