### PR TITLE
LPS-167148 Remove "immediate = true" from Journal modules

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-167148

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:echo

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by rafaprax** [comment]
Hey @tinatian it is ready for your review. Thx

**Comment by tinatian** [comment]
ci:forward

FYI @shuyangzhou

**Pull request closed without merging**
