### PR TITLE
LPS-155715 Cache clean up part2

### PR DESCRIPTION
**Pull request by tinatian**
This pull is based on https://github.com/liferay-core-infra/liferay-portal/pull/1145

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian No regressions found, this does not have the new tests specifically for partitioning cache.

**Comment by tinatian** [comment]
FYI @achaparro

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go. This is part 2 of db partition cache support, it is based on part 1 https://github.com/liferay-core-infra/liferay-portal/pull/1145, the whole pull is at https://github.com/liferay-core-infra/liferay-portal/pull/1147

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go, rebase and force push.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121025

**Pull request closed without merging**
