### PR TITLE
[Components with more than 1 service] LPS-180956 Refactor ScreenNavigationCategory components from Commerce modules part 8

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
no regressions found.

Only semver error:
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/commerce/commerce-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.commerce.constants                     MINOR      12.6.0     13.0.0     13.1.0     VERSION INCREASE REQUIRED
     [exec]     	<   class      com.liferay.commerce.constants.CommerceTaxScreenNavigationConstants
     [exec]     		+   field      CATEGORY_KEY_COMMERCE_AVALARA_TAX_RATES
     [exec]     			+   access     final
     [exec]     			+   access     static
     [exec]     			+   constant   avalara-tax-rates
     [exec]     			+   return     java.lang.String
     [exec]     		+   field      CATEGORY_KEY_COMMERCE_SETTINGS
     [exec]     			+   access     final
     [exec]     			+   access     static
     [exec]     			+   constant   settings
     [exec]     			+   return     java.lang.String
     [exec]     	+   version    12.6.0
     [exec]     	-   version    13.0.0
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-04/test-1-34/test-portal-acceptance-pullrequest(master)/3962/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@daiazius Please fix sem ver.

**Comment by dantewang** [comment]
@daiazius Please fix sem ver and rebase, thanks!

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
