### PR TITLE
[Method References 2] LPS-167730 Convert method reference to ServiceTracker in class PortletRegistryImpl

### PR DESCRIPTION
**Pull request by W2jx**
I have removed the registration of PortletAliasRegistration as per the [comment](https://github.com/liferay-core-infra/liferay-portal/pull/2503#discussion_r1035127691).

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/2503

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:help

**Comment by Kvale1733** [comment]
ci:test:fragment

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3622

**Pull request closed without merging**
