### PR TITLE
LPS-185647 Flush the session before changing the partition

### PR DESCRIPTION
**Pull request by mbowerman**
When updating ResourcePermissions during a ResourceAction deletion, we need to flush the session every time we finish running the ActionableDynamicQuery to ensure that we do not try to flush it after the partition has changed (in which case we would be trying to commit the query against the wrong partition)

Could you please take a look and let me know if this is the right fix? Thanks!

Ticket: [LPS-185647](https://issues.liferay.com/browse/LPS-185647)

### CODE REVIEW

**Comment by Kvale1733** [comment]
@mbowerman No regressions found. Testing passed following the ticket steps.

**Comment by tinatian** [comment]
@achaparro Could you please take a look at this issue? This seems to be a general issue and we might need a general solution for it.

Thanks.
Tina

**Comment by achaparro** [comment]
Hey @tinatian, I agree, I will proceed to review it with @mbowerman and resend.

Cheers!

**Comment by achaparro** [comment]
ci:close

**Pull request closed without merging**
