### PR TITLE
LPS-148926 Move jaxb-runtime and istack-commons-runtime to portal-tika

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @catarineaguiar, can you please help me scan these test results?

Thx

**Comment by catarineaguiar** [comment]
@rafaprax semver error:

```
[exec] [Baseline Warning] Bundle Version Change Recommended: 39.1.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-impl/portal-impl.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.impl/39.0.0/8015da1c52d7f2295e04d20e93465980444c7c6c/com.liferay.portal.impl-39.0.0.jar
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-38/test-portal-acceptance-pullrequest(master)/445/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by rafaprax** [comment]
Hey @catarineaguiar, It's not related to my changes and the portal-impl is already on 39.1.0 version on upstream, see https://github.com/liferay/liferay-portal/blob/master/portal-impl/bnd.bnd.

So, did you find any other issues here?

Thx

**Comment by catarineaguiar** [comment]
@rafaprax okay!! Any other issue was found.

**Comment by rafaprax** [comment]
Hey @shuyangzhou, thia pr is ready for your review. Thx

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/117680

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
