### PR TITLE
[Method References 2] LPS-177276 Convert method reference to ServiceTrackerList in class CompanyIndexFactory

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian , I have modified the code as per the [comment](https://github.com/liferay-core-infra/liferay-portal/pull/3658#issuecomment-1454344398).

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3658

### CODE REVIEW

**Comment by Kvale1733** [comment]
@W2jx There are several failing integration tests. Seem to be caused by the same root issue. Example)

com.liferay.portal.search.elasticsearch7.internal.background.task.ReindexSingleIndexerBackgroundTaskExecutorTest
```
  [exec] 
     [exec] com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngineBackupTest > classMethod FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.index.CompanyIndexFactory.activate(CompanyIndexFactory.java:176)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-03/test-1-37/test-portal-acceptance-pullrequest(master)/9713/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
Thank you @Kvale1733 !

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
@W2jx regressions found:

```
     [exec] com.liferay.portal.search.elasticsearch7.internal.index.CompanyIndexFactoryTest > testIndexSettingsContributor FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.index.CompanyIndexFactory._processContributions(CompanyIndexFactory.java:399)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.index.CompanyIndexFactory.access$000(CompanyIndexFactory.java:65)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.index.CompanyIndexFactory$1.addingService(CompanyIndexFactory.java:150)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.index.CompanyIndexFactory$1.addingService(CompanyIndexFactory.java:140)
     [exec]         at com.liferay.osgi.service.tracker.collections.internal.list.ServiceTrackerListImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerListImpl.java:164)
     [exec]         at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
     [exec]         at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
```
```
     [exec] com.liferay.portal.search.elasticsearch7.internal.index.CompanyIndexFactoryTest > testIndexConfigurations FAILED
     [exec]     org.junit.ComparisonFailure: expected:<[1]> but was:<[2]>
     [exec]         at org.junit.Assert.assertEquals(Assert.java:115)
     [exec]         at org.junit.Assert.assertEquals(Assert.java:144)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.index.CompanyIndexFactoryTest.testIndexConfigurations(CompanyIndexFactoryTest.java:249)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-03/test-1-25/test-portal-acceptance-pullrequest(master)/26/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

Due to this failure in CompanyIndexFactory upgrade tests with elasticsearch enabled failed while reindexing:
```
[beanshell] 2023-03-13 08:33:58.402 INFO  [liferay/background_task-2][ReindexPortalBackgroundTaskExecutor:57] Start reindexing company 0
[beanshell] 2023-03-13 08:33:58.404 INFO  [liferay/background_task-2][SearchEngineInitializer:105] Reindexing started
[beanshell] 2023-03-13 08:33:58.500 INFO  [liferay/background_task-2][CompanyIndexFactory:51] 
[beanshell] 2023-03-13 08:33:58.662 ERROR [liferay/background_task-2][SearchEngineInitializer:199] Error encountered while reindexing
[beanshell] org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=mapper_parsing_exception, reason=Failed to parse mapping [_doc]: analyzer [text_whitespace_lowercase] has not been configured in mappings]
[beanshell] 	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:178) ~[?:?]
[beanshell] 	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2484) ~[?:?]
[beanshell] 	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2461) ~[?:?]
[beanshell] 	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2184) ~[?:?]
[beanshell] 	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2154) ~[?:?]
[beanshell] 	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2118) ~[?:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-03/test-1-25/test-portal-acceptance-pullrequest(master)/26/functional-upgrade-tomcat90-mysql57-jdk8/1/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
