### PR TITLE
[Method References 2] LPS-171023 Convert method reference to field reference in class IndexResourceImpl

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian , I have changed the name of the constant class to WorkflowMetricsIndexEntityNameConstants.

Previous: https://github.com/brianchandotcom/liferay-portal/pull/136024

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:workflow-metrics

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(6/12 9:25)

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136149

**Pull request closed without merging**
