### PR TITLE
LPS-173369 Remove Optional from module: portal-search-web-api part 1 (SearchSettings and SearchResponse)

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
added baseline

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
reorganized commits and added additional removal

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@julschong Compile issue 
```
 [exec] /opt/dev/projects/github/liferay-portal/modules/apps/depot/depot-test/src/testIntegration/java/com/liferay/depot/web/internal/search/bar/portlet/shared/search/test/DepotSearchBarPortletSharedSearchContributorTest.java:264: error: <anonymous com.liferay.depot.web.internal.search.bar.portlet.shared.search.test.DepotSearchBarPortletSharedSearchContributorTest$1> is not abstract and does not override abstract method getScopeParameterName() in com.liferay.portal.search.web.search.request.SearchSettings
     [exec] 		return new PortletSharedSearchSettings() {
     [exec] 		                                         ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/depot/depot-test/src/testIntegration/java/com/liferay/depot/web/internal/search/bar/portlet/shared/search/test/DepotSearchBarPortletSharedSearchContributorTest.java:359: error: getScopeParameterName() in <anonymous com.liferay.depot.web.internal.search.bar.portlet.shared.search.test.DepotSearchBarPortletSharedSearchContributorTest$1> cannot implement getScopeParameterName() in com.liferay.portal.search.web.search.request.SearchSettings
     [exec] 			public Optional<String> getScopeParameterName() {
     [exec] 			                        ^
     [exec]   return type java.util.Optional<java.lang.String> is not compatible with java.lang.String
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/depot/depot-test/src/testIntegration/java/com/liferay/depot/web/internal/search/bar/portlet/shared/search/test/DepotSearchBarPortletSharedSearchContributorTest.java:354: error: getScope() in <anonymous com.liferay.depot.web.internal.search.bar.portlet.shared.search.test.DepotSearchBarPortletSharedSearchContributorTest$1> cannot implement getScope() in com.liferay.portal.search.web.search.request.SearchSettings
     [exec] 			public Optional<String> getScope() {
     [exec] 			                        ^
     [exec]   return type java.util.Optional<java.lang.String> is not compatible with java.lang.String
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/depot/depot-test/src/testIntegration/java/com/liferay/depot/web/internal/search/bar/portlet/shared/search/test/DepotSearchBarPortletSharedSearchContributorTest.java:302: error: getPaginationStartParameterName() in <anonymous com.liferay.depot.web.internal.search.bar.portlet.shared.search.test.DepotSearchBarPortletSharedSearchContributorTest$1> cannot implement getPaginationStartParameterName() in com.liferay.portal.search.web.search.request.SearchSettings
     [exec] 			public Optional<String> getPaginationStartParameterName() {
     [exec] 			                        ^
     [exec]   return type java.util.Optional<java.lang.String> is not compatible with java.lang.String
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/depot/depot-test/src/testIntegration/java/com/liferay/depot/web/internal/search/bar/portlet/shared/search/test/DepotSearchBarPortletSharedSearchContributorTest.java:297: error: getPaginationStart() in <anonymous com.liferay.depot.web.internal.search.bar.portlet.shared.search.test.DepotSearchBarPortletSharedSearchContributorTest$1> cannot implement getPaginationStart() in com.liferay.portal.search.web.search.request.SearchSettings
     [exec] 			public Optional<Integer> getPaginationStart() {
     [exec] 			                         ^
     [exec]   return type java.util.Optional<java.lang.Integer> is not compatible with java.lang.Integer
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/depot/depot-test/src/testIntegration/java/com/liferay/depot/web/internal/search/bar/portlet/shared/search/test/DepotSearchBarPortletSharedSearchContributorTest.java:296: error: method does not override or implement a method from a supertype
     [exec] 			@Override
     [exec] 			^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/depot/depot-test/src/testIntegration/java/com/liferay/depot/web/internal/search/bar/portlet/shared/search/test/DepotSearchBarPortletSharedSearchContributorTest.java:301: error: method does not override or implement a method from a supertype
     [exec] 			@Override
     [exec] 			^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/depot/depot-test/src/testIntegration/java/com/liferay/depot/web/internal/search/bar/portlet/shared/search/test/DepotSearchBarPortletSharedSearchContributorTest.java:353: error: method does not override or implement a method from a supertype
     [exec] 			@Override
     [exec] 			^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/depot/depot-test/src/testIntegration/java/com/liferay/depot/web/internal/search/bar/portlet/shared/search/test/DepotSearchBarPortletSharedSearchContributorTest.java:358: error: method does not override or implement a method from a supertype
     [exec] 			@Override
     [exec] 			^
     [exec] 9 errors
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-37/test-portal-acceptance-pullrequest(master)/8408/modules-integration-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
see #3195

**Pull request closed without merging**
