### PR TITLE
[LPS-167246 MessageBus] LPS-193720 Remove unused destination DOCUMENT_LIBRARY_SYNC_EVENT_PROCESSOR

### PR DESCRIPTION
**Pull request by W2jx**
Hi @dantewang , this is the task we discussed yesterday about `DOCUMENT_LIBRARY_SYNC_EVENT_PROCESSOR`

Issue: https://liferay.atlassian.net/browse/LPS-193720

### CODE REVIEW

**Comment by W2jx** [comment]
ci:stop

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:help

**Comment by W2jx** [comment]
ci:test:document

**Comment by W2jx** [comment]
ci:test:lima

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(8/21 8:48)

**Review by dantewang — APPROVED** [review]

**Comment by adolfopa** [comment]
@dantewang @W2jx  Changes look good to me.

**Comment by dantewang** [comment]
@adolfopa Thank you!

**Comment by W2jx** [comment]
no conflicts(8/22 13:15)

**Comment by dantewang** [comment]
ci:forward:force

@tinatian This removes leftover destination code related to Liferay Sync which is already removed. Forwarding as it's approved by Lima team.

**Comment by W2jx** [comment]
ci:forward:force

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
