### PR TITLE
LPS-161686 Fix the issue about SystemProperties in StringBundlerTest

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang, I fix the issue about SystemProperties in StringBundlerTest.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results when they finish ? Thanks!

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@tinatian This one is urgent as it blocks some other teams' forwarding procedure.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122449

FYI @shuyangzhou

**Pull request closed without merging**
