### PR TITLE
[Components with more than 1 service] LPS-178898 Refactor ScreenNavigationCategory components from Data Integration

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@MrJohn1911 @daiazius @RenanUmV @rafaprax See https://github.com/liferay-core-infra/liferay-portal/pull/4141/commits/b8193eafd8682ee47b8c78f6ccf3efc9c256910a

**Comment by dantewang** [comment]
@MrJohn1911 @daiazius @RenanUmV Please add this bnd instruction to the module when you make a component extend any class that has `@Reference`.

**Comment by dantewang** [comment]
ci:test:data-integration

**Comment by dantewang** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
