### PR TITLE
LPS-169043 move_commons-collections4_to_shared-dependencies

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Fixed the bug mentioned [here](https://github.com/liferay-core-infra/liferay-portal/pull/2584#issuecomment-1341093610)
Change the commit order as well as the commit message to make it clear, based on https://github.com/liferay-core-infra/liferay-portal/pull/2511
I am trying to move commons-collections4 to shared-dependencies because we already have a shared-dependencies for org.apache.commons.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
fixed the typo in commit message

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@jeffwu0724 Regressions found. They are some of the same ones I found in https://github.com/liferay-core-infra/liferay-portal/pull/2595

1) .doc document does not appear in document results

Steps to reproduce
     I. Go to Documents and Media and add the following [document] 
   (https://docs.google.com/document/d/12gowFPcfdGbw1dHBZkm_cOSC3QIn0TH-/edit? 
   usp=sharing&ouid=117807970786966236933&rtpof=true&sd=true)
    (Can also be found in portal-web/test/functional/com/liferay/portalweb/dependencies)
    II. Click on the ellipses for the tree.png image and click edit
    III. Go down to related assets and click select > basic document

Expected Results: Can select the added document
Actual Results: The added document does not appear.

*Note: This is just one way to reproduce the issue. You can also try searching for the document by title in the home page and you will also see it doesn't come up in the search results. You can also add an Asset Publisher widget to a page and you will see the document does not appear. I think these issues are related.

2) com.liferay.batch.engine.internal.test.BatchEngineExportTaskExecutorTest
```
 [exec] com.liferay.batch.engine.internal.test.BatchEngineExportTaskExecutorTest > testExportBlogPostingsToXLSFileWithFieldNames FAILED
     [exec]     java.lang.NoClassDefFoundError: org/apache/commons/collections4/ListValuedMap
     [exec]     	at com.liferay.batch.engine.internal.test.BatchEngineExportTaskExecutorTest._testExportBlogPostingsToXLSFile(BatchEngineExportTaskExecutorTest.java:583)
     [exec]     	at com.liferay.batch.engine.internal.test.BatchEngineExportTaskExecutorTest.testExportBlogPostingsToXLSFileWithFieldNames(BatchEngineExportTaskExecutorTest.java:260)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
[Log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-29/test-portal-acceptance-pullrequest(master)/5686/modules-integration-mysql57-jdk8/0/9/jenkins-console.txt.gz?authuser=0)

3) com.liferay.portal.tika.test.TextExtractorTest
```
java.lang.NoClassDefFoundError: org/apache/commons/collections4/bidimap/TreeBidiMap
		at org.apache.poi.hpsf.Section.<init>(Section.java:181)
		at org.apache.poi.hpsf.PropertySet.init(PropertySet.java:493)
		at org.apache.poi.hpsf.PropertySet.<init>(PropertySet.java:194)
		at org.apache.tika.parser.microsoft.SummaryExtractor.parseSummaryEntryIfExists(SummaryExtractor.java:85)
```
[Log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-33/test-portal-acceptance-pullrequest(master)/2540/modules-integration-mysql57-jdk8/3/10/com.liferay.portal.tika.test.TextExtractorTest.txt.gz?authuser=0)

**Pull request closed without merging**
