### PR TITLE
[Move Expando: cleanup Portal, PortalImpl and PortalUtil]Lps 191477

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-191477

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:license

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian This one is previously approved, we just resend to rebase sem ver.

**Comment by dantewang** [comment]
Passed QA and Approved in https://github.com/liferay-core-infra/liferay-portal/pull/5181

**Comment by catarineaguiar** [comment]
no regressions found

**Pull request closed without merging**
