### PR TITLE
[TS] LPD-33337 Remember write data source in request scope

### PR DESCRIPTION
**Pull request by dantewang**
cc @shuyangzhou @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
@vicnate5 Is is possible to run an integration test with R/W split enabled? If possible I can add tests to service-builder-test.

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@shuyangzhou Thanks! I wasn't aware of the `ThreadLocalFilter`. I'll try this option.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@dantewang now the DynamicDataSourceThreadLocal class is no longer needed, you can just keep the CentralizedThreadLocal as a private field inside DynamicDataSource. If later we need to extend this to across multiple requests, we may need to pull it out like this, but at least for now, it is not needed.

**Comment by dantewang** [comment]
@shuyangzhou Got it. Will wait for the current run to finish and then force push.

**Comment by dantewang** [comment]
ci:report:56078970

**Comment by dantewang** [comment]
ci:report:56078970

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by shuyangzhou** [comment]
@dantewang you can omit the shortLived = true parameter here https://github.com/liferay-core-infra/liferay-portal/pull/7323/commits/4bcfee3d9369ba3bc8b826acabdf1c54fe03355c#diff-9ec82cb452d83cda3a40deb4d37b0b8b7c8a423fafaa3de7035506a52fc4ef67R134, it is the default value.

**Comment by dantewang** [comment]
ci:report:56139036

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 56139036.
> 
> Job Link: [generate-testray-csv](https://test-1-34.liferay.com/job/generate-testray-csv/152/)
> 
> Testray CSV Link: [testray-results-56139036.csv](https://test-1-34.liferay.com/userContent/jobs/generate-testray-csv/builds/152/testray-results-56139036.csv)

All these tests marked unique also fail in other runs with exactly same errors.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:57212949

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/153231

**Pull request closed without merging**
