### PR TITLE
[Remove Blocking usages]LPS-189564 portal-kernel | WorkflowComparatorFactoryUtil

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend, move the creation of [My]WorkflowInstanceEditDisplayContext from jsp to Java class, and pass the WorkflowComparatorFactory into the display context. Thanks!

previous:https://github.com/liferay-core-infra/liferay-portal/pull/4923
https://liferay.atlassian.net/browse/LPS-189564

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:workflow

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
The modules-compile should be unrelated.

**Comment by liuxingye** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
@JanisZhang regressions found:

steps to reproduce:
1. Start portal
2. login and click in user avatar
3. go to My Submissions

Expected results:
The page opens without errors.

Actual result:
An error is shown on the page `My Submissions is temporarily unavailable.`
Error in the logs
```
2023-07-06 16:35:49.140 ERROR [http-nio-8080-exec-10][IncludeTag:128] Current URL /web/guest/manage?p_p_id=com_liferay_portal_workflow_web_internal_portlet_UserWorkflowPortlet&p_p_lifecycle=0&_com_liferay_portal_workflow_web_internal_portlet_UserWorkflowPortlet_backURL=%2Fweb%2Fguest%2Fhome generates exception: java.lang.NullPointerException
java.lang.NullPointerException: null
	at com.liferay.portal.workflow.web.internal.util.WorkflowInstancePortletUtil.getWorkflowInstanceOrderByComparator(WorkflowInstancePortletUtil.java:81) ~[bundleFile:?]
	at com.liferay.portal.workflow.web.internal.search.WorkflowInstanceSearch.<init>(WorkflowInstanceSearch.java:66) ~[bundleFile:?]
	at com.liferay.portal.workflow.web.internal.display.context.WorkflowInstanceViewDisplayContext.getSearchContainer(WorkflowInstanceViewDisplayContext.java:272) ~[bundleFile:?]
	at com.liferay.portal.workflow.web.internal.display.context.WorkflowInstanceViewDisplayContext.getTotalItems(WorkflowInstanceViewDisplayContext.java:343) ~[bundleFile:?]
	at org.apache.jsp.instance.toolbar_jsp._jspService(toolbar_jsp:244) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111) ~[jasper.jar:9.0.75]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[servlet-api.jar:4.0.FR]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411) ~[jasper.jar:9.0.75]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473) ~[jasper.jar:9.0.75]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377) ~[jasper.jar:9.0.75]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[servlet-api.jar:4.0.FR]
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:328) ~[bundleFile:?]
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:340) ~[bundleFile:?]
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:63) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
	at com.liferay.portal.servlet.DirectServletPathRegisterDispatcher.include(DirectServletPathRegisterDispatcher.java:66) ~[portal-impl.jar:?]
	at com.liferay.portal.servlet.DirectRequestDispatcherFactoryImpl$IndirectRequestDispatcher.include(DirectRequestDispatcherFactoryImpl.java:190) ~[portal-impl.jar:?]
	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:79) ~[portal-impl.jar:?]
2023-07-06 16:35:49.155 ERROR [http-nio-8080-exec-10][MyWorkflowInstancePortletTab:49] Unable to include JSP /instance/view.jsp
org.apache.jasper.JasperException: java.lang.NullPointerException
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:440) ~[jasper.jar:9.0.75]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473) ~[jasper.jar:9.0.75]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-07/test-1-37/test-portal-acceptance-pullrequest(master)/12944/functional-tomcat90-mysql57-jdk8/1/23/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
