### PR TITLE
[Optional Reference] LPS-185410 Convert the Optional Dynamic Greedy references to static references using Snapshot in class SPATopHeadJSPDynamicInclude

### PR DESCRIPTION
**Pull request by haydenzheng314**
Ticket: https://issues.liferay.com/browse/LPS-185410
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by LisztLiszt** [comment]
ci:help

**Comment by LisztLiszt** [comment]
ci:test:frontend

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
