### PR TITLE
[Bgu Fix]LPS-178297 When we have multiple Java based action executors in the Workflow Extensions project, we cannot get the desired one correctly

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have added test to make sure the new added fix is working.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3840

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(3/17 8:15)

**Comment by W2jx** [comment]
no conflicts(3/20 8:52)

**Comment by W2jx** [comment]
Hi @dantewang, I have resent it.

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@W2jx Please resend as we talked.

**Pull request closed without merging**
