### PR TITLE
LPS-144892

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This PR is to fix https://issues.liferay.com/browse/LPS-144892
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result again, please?

Thanks
Jeff

**Comment by tinatian** [comment]
Hi @jeffwu0724 Could you please modify the commit message about the reason you changed it to "PUBLIC"? For example, what does "PUBLIC" mean? Any official doc link about this changes between old version and new version? Generally it is to help people to understand your change is reasonable.

Thanks.
Tina.

**Comment by tinatian** [comment]
@jeffwu0724 Code conflicts, please modify the commit message, rebase and resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
