### PR TITLE
LPS-194092 Remove ZipReaderFactoryUtil and ZipWriterFactoryUtil

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:tes:echo

**Comment by Kvale1733** [comment]
ci:test:staging

**Comment by Kvale1733** [comment]
ci:test:document

**Comment by Kvale1733** [comment]
ci:test:users

**Comment by Kvale1733** [comment]
@julschong Regressions found

1)
 ```
      [exec] > Task :apps:asset:asset-publisher-web:generateJSPJava
     [exec] Compiling JSP files of project ':apps:asset:asset-publisher-web' with /opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.75/webapps/ROOT/WEB-INF/shielded-container-lib/util-taglib.jar as dependency in place of 'com.liferay.portal:com.liferay.util.taglib'
     [exec] 
     [exec] > Task :apps:batch-engine:batch-engine-test:compileTestIntegrationJava
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/batch-engine/batch-engine-test/src/testIntegration/java/com/liferay/batch/engine/internal/test/BatchEngineBundleTrackerTest.java:21: error: cannot find symbol
     [exec] import com.liferay.portal.kernel.zip.ZipWriterFactoryUtil;
     [exec]                                     ^
     [exec]   symbol:   class ZipWriterFactoryUtil
     [exec]   location: package com.liferay.portal.kernel.zip
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/batch-engine/batch-engine-test/src/testIntegration/java/com/liferay/batch/engine/internal/test/BatchEngineBundleTrackerTest.java:153: error: cannot find symbol
     [exec] 		ZipWriter zipWriter = ZipWriterFactoryUtil.getZipWriter();
     [exec] 		                      ^
     [exec]   symbol:   variable ZipWriterFactoryUtil
     [exec]   location: class com.liferay.batch.engine.internal.test.BatchEngineBundleTrackerTest
     [exec] 
     [exec] > Task :apps:batch-engine:batch-engine-test:compileTestIntegrationJava FAILED
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/batch-engine/batch-engine-test/src/testIntegration/java/com/liferay/batch/engine/internal/test/BaseBatchEngineTaskExecutorTest.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
 ```
 [Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-40/test-portal-acceptance-pullrequest(master)/5344/modules-compile-jdk8/0/0/jenkins-console.txt.gz?authuser=0)
 
 2) com.liferay.dynamic.data.mapping.exportimport.data.handler.test.DDMFormInstanceStagedModelDataHandlerTest
  ```
   [exec] com.liferay.dynamic.data.mapping.exportimport.data.handler.test.DDMFormInstanceStagedModelDataHandlerTest > testCleanStagedModelDataHandler FAILED
     [exec]     java.lang.NullPointerException
     [exec]     	at com.liferay.exportimport.test.util.lar.BaseStagedModelDataHandlerTestCase.initExport(BaseStagedModelDataHandlerTestCase.java:696)
     [exec]     	at com.liferay.exportimport.test.util.lar.BaseStagedModelDataHandlerTestCase.initExport(BaseStagedModelDataHandlerTestCase.java:692)
     [exec]     	at com.liferay.exportimport.test.util.lar.BaseStagedModelDataHandlerTestCase.testCleanStagedModelDataHandler(BaseStagedModelDataHandlerTestCase.java:206)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:228)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:307)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:86)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
 ```
   [Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-40/test-portal-acceptance-pullrequest(master)/5344/modules-integration-mysql57-jdk8/1/19/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
fixed integration test by adding test rule and added missed Util change

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:echo

**Comment by julschong** [comment]
ci:test:document

**Comment by julschong** [comment]
ci:test:users

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by tinatian** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/139707

**Pull request closed without merging**
