### PR TITLE
[Component with its own class name as service type ] LPS-194013 Refactor Registry classes from Dynamic Data Mapping module

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-194013

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:forms

**Comment by MrJohn1911** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
Last push fixes conflicts in bnd.bnd

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@MrJohn1911 regression found:

```
     [exec] com.liferay.journal.search.test.JournalArticleDDMStructureIndexerTest > testDisableJournalArticleIndexer STARTED
[beanshell] 2023-09-09 00:36:18.268 ERROR [com.liferay.journal.test-executor-thread][SynchronousDestinationTestRule$TestSynchronousDestination:406] Unable to process message {destinationName=liferay/ddm_structure_reindex, response=null, responseDestinationName=null, responseId=null, payload=null, values={defaultLocale=en_US, companyId=20095, groupId=0, structureId=33866, principalName=20122, permissionChecker=com.liferay.portal.kernel.util.TransientValue@3b4f2368, siteDefaultLocale=ja_JP}}
[beanshell] com.liferay.portal.kernel.messaging.MessageListenerException: java.lang.NullPointerException
[beanshell] 	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:32) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:65) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.SynchronousDestinationTestRule$TestSynchronousDestination.send(SynchronousDestinationTestRule.java:403) [bundleFile:?]
[beanshell] 	at com.liferay.portal.messaging.internal.DefaultMessageBus.sendMessage(DefaultMessageBus.java:111) [bundleFile:?]
[beanshell] 	at com.liferay.journal.search.test.JournalArticleDDMStructureIndexerTest.testDisableJournalArticleIndexer(JournalArticleDDMStructureIndexerTest.java:97) [bundleFile:?]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-09/test-1-30/test-portal-acceptance-pullrequest(master)/7764/modules-integration-mysql57-jdk8/0/13/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:forms

**Comment by MrJohn1911** [comment]
ci:test:data-engine

**Comment by catarineaguiar** [comment]
@MrJohn1911 this [failure](https://github.com/liferay-core-infra/liferay-portal/pull/5516#issuecomment-1716102909) is still happening

other regression found:

```
     [exec] com.liferay.journal.internal.upgrade.v5_2_1.test.JournalArticleLayoutClassedModelUsageUpgradeProcessTest > testUpgradeProcessExistingLayoutClassedModelUsagesByPlid STARTED
[beanshell] 2023-09-12 20:14:50.732 ERROR [com.liferay.journal.test-executor-thread][LoggerExportImportLifecycleListener:310] Portlet publication failed for portlet com_liferay_exportimport_web_portlet_ChangesetPortlet
[beanshell] 2023-09-12 20:14:50,733 com.liferay.journal.test-executor-thread ERROR An exception occurred processing Appender KF7wyN4n org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.exportimport.internal.lifecycle.LoggerExportImportLifecycleListener, message=Portlet publication failed for portlet com_liferay_exportimport_web_portlet_ChangesetPortlet
[beanshell] 	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:165)
[beanshell] 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
[beanshell] 	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
[beanshell] 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
[beanshell] 	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-09/test-1-29/test-portal-acceptance-pullrequest(master)/8155/modules-integration-mysql57-jdk8/0/13/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
