### PR TITLE
[Component with its own class name as service type] LPD-8529 Refactor Builder and helper class form asset module

### PR DESCRIPTION
**Pull request by MrJohn1911**
Previous pull: https://github.com/MrJohn1911/liferay-portal/pull/72

Ticket: https://liferay.atlassian.net/browse/LPD-8529

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:startup

**Comment by tinatian** [comment]
ci:forward

**Comment by MrJohn1911** [comment]
ci:foward

CC: @tinatian

**Comment by MrJohn1911** [comment]
ci:forward

CC: @tinatian

**Pull request closed without merging**
