### PR TITLE
[OrderByComparator] LPD-25932 clean up unused OrderByComparator constructors and classes -- part one

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

Resent: https://github.com/liferay-core-infra/liferay-portal/pull/6985
As talked, I includes all the removing unused classes in one single commit, remove their reference by global text search, and add a breaking change in the commit messges. 

Thanks for checking

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@jeffwu0724 Code looks good to me, please forward to BChan once ci is clear, also please cc me and commerce developer lead.

Thanks.
Tina

**Comment by jeffwu0724** [comment]
ci:report:2569917583

**Comment by jeffwu0724** [comment]
ci:forward

**Comment by titokenzo** [comment]
@jeffwu0724  please check my messages on Slack

**Comment by jeffwu0724** [comment]
Hi @titokenzo ,

Thanks for catching this. 
I have included the baseline commit, and also include the breaking change in the commits that we remove the public constructor, as this will also cause major version bump.

As I only edit the commit message, and inlucde the baseline commit, the previous test result should be still good enough.

**Comment by jeffwu0724** [comment]
fixing the code conflict..

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Pull request closed without merging**
