### PR TITLE
[Method References 2] LPS-169905 Convert method reference to ServiceTracker in class AccountRoleRequestHelper

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian , I have separated the last PR into two parts.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3189

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:roles

**Comment by W2jx** [comment]
ci:test:account

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
