### PR TITLE
[Convert method references]Lps 162719

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-162719

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Review by dantewang — CHANGES_REQUESTED** [review]
@slnn Since commerce-product-service is already enabled with DS annotation inherit, could you try to just add `@Reference` to the proected fields, and remove the setter methods from sub-class?

I'd like to limit the `getXXX` pattern only to the situation where sub-classes need to provide different instances of the service to the parent. For example, a pattern we have applied to multiple places is, each -web module has a `ServletContext` published as OSGi service. Sub classes reference them using different servlet context name and provide them to parent by implementing `getServletContext()` method.

**Comment by slnn** [comment]
> @slnn Since commerce-product-service is already enabled with DS annotation inherit, could you try to just add `@Reference` to the proected fields, and remove the setter methods from sub-class?
> 
> I'd like to limit the `getXXX` pattern only to the situation where sub-classes need to provide different instances of the service to the parent. For example, a pattern we have applied to multiple places is, each -web module has a `ServletContext` published as OSGi service. Sub classes reference them using different servlet context name and provide them to parent by implementing `getServletContext()` method.

Hi @dantewang 

Do you want to do the convert on commerce-product-service after this change https://github.com/liferay-core-infra/liferay-portal/pull/1621?

**Comment by dantewang** [comment]
Are they conflicting?

**Comment by slnn** [comment]
> Are they conflicting?

No, I have applied the change https://github.com/liferay-core-infra/liferay-portal/pull/1621 and added the reference on the protected method and remove these setter methods from sub-class.

Forced push to this pull.

**Comment by slnn** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@slnn If the change in this pull is not conflicting with any change in your spring-extender removal pull, please don't include commit from that pull. If they do conflict, send that one first, that one is with higher priority.

**Pull request closed without merging**
