### PR TITLE
[Components with more than 1 service] LPS-189642 Refactor components from portal-workflow module

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
I only moved a class to another place, no need to run all the related test suites.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@dantewang Regression found. The following test gets stuck and times out


com.liferay.portal.workflow.kaleo.internal.runtime.node.test.TaskNodeExecutorTest
```
  [exec] com.liferay.portal.workflow.kaleo.internal.runtime.node.test.TaskNodeExecutorTest > testExecuteTimerNotifications STARTED
[beanshell] Waiting for service (no type) component.name=com.liferay.portal.workflow.kaleo.runtime.internal.node.TimerExecutor for field com.liferay.portal.workflow.kaleo.internal.runtime.node.test.TaskNodeExecutorTest._timerExecutor
[beanshell] Waiting for service (no type) component.name=com.liferay.portal.workflow.kaleo.runtime.internal.node.TimerExecutor for field com.liferay.portal.workflow.kaleo.internal.runtime.node.test.TaskNodeExecutorTest._timerExecutor
[beanshell] Waiting for service (no type) component.name=com.liferay.portal.workflow.kaleo.runtime.internal.node.TimerExecutor for field com.liferay.portal.workflow.kaleo.internal.runtime.node.test.TaskNodeExecutorTest._timerExecutor
[beanshell] Waiting for service (no type) component.name=com.liferay.portal.workflow.kaleo.runtime.internal.node.TimerExecutor for field com.liferay.portal.workflow.kaleo.internal.runtime.node.test.TaskNodeExecutorTest._timerExecutor
[beanshell] Waiting for service (no type) component.name=com.liferay.portal.workflow.kaleo.runtime.internal.node.TimerExecutor for field com.liferay.portal.workflow.kaleo.internal.runtime.node.test.TaskNodeExecutorTest._timerExecutor
[beanshell] Waiting for service (no type) component.name=com.liferay.portal.workflow.kaleo.runtime.internal.node.TimerExecutor for field com.liferay.portal.workflow.kaleo.internal.runtime.node.test.TaskNodeExecutorTest._timerExecutor
[beanshell] Waiting for service (no type) component.name=com.liferay.portal.workflow.kaleo.runtime.internal.node.TimerExecutor for field com.liferay.portal.workflow.kaleo.internal.runtime.node.test.TaskNodeExecutorTest._timerExecutor
[beanshell] Waiting for service (no type) component.name=com.liferay.portal.workflow.kaleo.runtime.internal.node.TimerExecutor for field com.liferay.portal.workflow.kaleo.internal.runtime.node.test.TaskNodeExecutorTest._timerExecutor
```
[Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-39/test-portal-acceptance-pullrequest(master)/6860/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:workflow

**Comment by zhangyan0701** [comment]
Issue found:
**User is logged out after approve a wiki page.**
Steps:
1. Assign Single Approver to Wiki page.
2. Add a new Wiki node and edit the FrontPage.
3. Assert FrontPage is in pending status.
4. Go to My Workflow Tasks.
5. Approve the FrontPage.
6. Click anywhere in the page.
7. User is logged out and Page not found displays.

https://github.com/liferay-core-infra/liferay-portal/assets/25576873/309f84b2-2402-4f3c-8cc4-3405ca12e502

**Comment by dantewang** [comment]
@zhangyan0701 Thanks! I'll look into it.

**Comment by dantewang** [comment]
@zhangyan0701 I am able to reproduce this at master git id 7f2c19002f7bb46b6f3b86c707487414e1619074, could you double check?

**Comment by dantewang** [comment]
Rebased and resent to https://github.com/liferay-core-infra/liferay-portal/pull/5379

**Pull request closed without merging**
