### PR TITLE
[Method References 2] LPS-165735 Convert method reference to ServiceTrackerMap in modules commerce-discount-service and commerce-service

### PR DESCRIPTION
**Pull request by W2jx**
Hi @dantewang , I have reordered all commits.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/2898

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(1/16 8:58)

**Comment by W2jx** [comment]
no conflicts(1/16 9:07)

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
