### PR TITLE
Lps 158311 refactor2 10 19

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:workflow-metrics

**Comment by tinatian** [comment]
ci:test:onedrive

**Comment by tinatian** [comment]
ci:test:export-import

**Comment by Kvale1733** [comment]
ci:test:export-import

**Comment by Kvale1733** [comment]
@tinatian 

Semver error
```
 [exec] > Task :baseline
     [exec] [Baseline Warning] Bundle Version Change Recommended: 84.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/83.0.0/bd7aee8da65bf743e0676b8015e21b59621ae17a/com.liferay.portal.kernel-83.0.0.jar
     [exec] Gradle build finished at 2022-10-28 20:46:18.563.
```
[Log](https://testray.liferay.com/reports/production/logs/2022-10/test-1-37/test-portal-acceptance-pullrequest(master)/6017/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
@dantewang Please rebase.

Thanks.
Tina

**Pull request closed without merging**
