### PR TITLE
LPS-189621

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
Hi @marianoalvarosaiz when I followed the bug steps I got an error, I'm not sure if I did it correctly.

error when I created more than 2100 user using the Dummy Factory
```
Starting to create 2101 users
Creating...0% done
2023-09-05 20:23:27.640 ERROR [liferay/monitoring-3][ParallelDestination:50] Unable to process message {destinationName=liferay/monitoring, response=null, responseDestinationName=null, responseId=null, payload=[{displayName=Dummy Factory, portletId=com_liferay_support_tools_portlet_LiferayDummyFactoryPortlet, requestType=ACTION, {attributes=null, companyId=20095, groupId=20113, description=null, duration=0, name=com_liferay_support_tools_portlet_LiferayDummyFactoryPortlet, namespace=com.liferay.monitoring.Portlet, requestStatus=null, stopWatch=0:00:00.626, timeout=0, user=20122}}, {referer=http://localhost:8080/group/control_panel/client, remoteAddr=127.0.0.1, requestURL=, statusCode=0, userAgent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36, {attributes=null, companyId=20095, groupId=20113, description=null, duration=629, name=/c/portal/layout, namespace=com.liferay.monitoring.Portal, requestStatus=ERROR, stopWatch=0:00:00.629, timeout=-1, user=20122}}, {referer=http://localhost:8080/group/control_panel/client, remoteAddr=127.0.0.1, requestURL=, statusCode=0, userAgent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36, {attributes=null, companyId=20095, groupId=0, description=null, duration=632, name=/group/control_panel/manage, namespace=com.liferay.monitoring.Portal, requestStatus=ERROR, stopWatch=0:00:00.632, timeout=-1, user=null}}], values={defaultLocale=en_US, companyId=20095, groupId=0, principalName=20122, permissionChecker=com.liferay.portal.kernel.util.TransientValue@4b22afc6, siteDefaultLocale=en_US, themeDisplayLocale=en_US}}
com.liferay.portal.kernel.messaging.MessageListenerException: java.lang.NullPointerException
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:32) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:65) ~[portal-kernel.jar:?]
	at com.liferay.portal.messaging.internal.ParallelDestination$1.run(ParallelDestination.java:47) [bundleFile:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.NullPointerException
	at com.liferay.portal.monitoring.internal.statistics.portlet.PortletStatistics.processDataSample(PortletStatistics.java:103) ~[?:?]
	at com.liferay.portal.monitoring.internal.statistics.portlet.CompanyStatistics.processDataSample(CompanyStatistics.java:200) ~[?:?]
	at com.liferay.portal.monitoring.internal.statistics.portlet.data.sample.processor.PortletRequestDataSampleProcessor.processDataSample(PortletRequestDataSampleProcessor.java:53) ~[?:?]
	at com.liferay.portal.monitoring.internal.statistics.portlet.data.sample.processor.PortletRequestDataSampleProcessor.processDataSample(PortletRequestDataSampleProcessor.java:22) ~[?:?]
	at com.liferay.portal.monitoring.internal.messaging.MonitoringMessageListener.processDataSample(MonitoringMessageListener.java:64) ~[?:?]
	at com.liferay.portal.monitoring.internal.messaging.MonitoringMessageListener.doReceive(MonitoringMessageListener.java:104) ~[?:?]
	at com.liferay.portal.kernel.messaging.BaseMessageListener.doReceive(BaseMessageListener.java:39) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:25) ~[portal-kernel.jar:?]
	... 5 more
2023-09-05 20:23:27.641 WARN  [http-nio-8080-exec-3][code_jsp:161] {code="500", msg="", uri=/group/control_panel/manage}
javax.servlet.ServletException: Servlet execution threw an exception
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:216) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-websocket.jar:9.0.75]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:115) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:138) ~[portal-kernel.jar:?]
```

**Comment by marianoalvarosaiz** [comment]
Hi @catarineaguiar ,
 I've changed the reproduction steps to use a groovy file instead of the jar file. The script, by default, creates 2500 users that is more than the SQL Server parameter limitation (2100). Feel free to modify the value in the loop and add more if needed (it will take some time).

**Comment by Kvale1733** [comment]
ci:test:environments

**Comment by Kvale1733** [comment]
ci:test:um

**Comment by Kvale1733** [comment]
@marianoalvarosaiz No regressions found. Testing passed following the ticket steps.

**Comment by yuhai** [comment]
@marianoalvarosaiz, the current pr can't fix the issue completely. The `RestrictionsFactoryUtil.in()` usages still exist the issue. I don't find the good way to fix it. I will let you know with my progress.

**Comment by marianoalvarosaiz** [comment]
@yuhai yes, you're wright, but there is no way to fix at `RestrictionsFactoryUtil.in()`. You can limit a specific `in`, but as soon as other parameters are involved in the statement it will fail.

I mean if you have `where id in (1,2...2100) and companyId = ?` the `in` parameter restriction will be satisfied (with less than or equal to 2100 parameters), but the total amount will not be satisfied.

So, honestly I don't find a good way to fix it for every use case. We will had to parse each composed statement to count the parameters total and if it exceeds rebuild the query. That's too overkill IMHO. I think that a paginated findBy method might be useful (is used in more than one place) and try to follow a reactive approach. If it has only happened once with SQL Server we can try to fix each case that appears instead of rebuilding the framework. Besides adding to a where clause more that 2100 is not always a good design, so hopefully not many cases should appear.

**Comment by yuhai** [comment]
@shuyangzhou, I don't find a good way to fix the issue from the framework level.

The root issue is that the the SQL statement with more than 2100 parameters can't execute successful in the SQLSERVER database.

The issue can be exposed by using DynamicQuery. When adding `RestrictionsFactoryUtil.in(String, Collection)` to DynamicQuery and the Collection size more than 2100,  in the `RestrictionsFactoryImpl#in()`, the current logic may split the sql from an IN() clause to `propertyName in (?..) or propertyName in (?..)`, this works for Oracle(Please see the [link](https://www.ibm.com/support/pages/ora-01795-maximum-number-expressions-list-1000-0)). But SQLSERVER detects the total params in the SQL statement. So the current logic `database.in.max.parameters` can't work for SQLSERVER. 

I checked hibernate codes and didn't find hibernate may detect the limitation and handle it.

Reference:
https://cloudblogs.microsoft.com/dynamics365/no-audience/2009/09/01/how-to-fix-sql-error-too-many-parameters-were-provided-in-this-rpc-request/
https://learn.microsoft.com/en-us/sql/sql-server/maximum-capacity-specifications-for-sql-server?view=sql-server-ver15
https://forum.hibernate.org/viewtopic.php?p=2369318

How do we fix the issue? Could you please provide some guidance?

cc @dantewang, @marianoalvarosaiz 

Thanks,
Hai

**Comment by shuyangzhou** [comment]
There is no real way to fix it since it is the db limitation.
But the issue is triggered from search, it should be solved at search level rather than dynamic query level.
Don't touch dynamic query code, just break this large batch into pieces at the search indexer level, with respect to the same database.in.max.parameters property settings. Let search indexer to do multiple smaller batch db queries.

**Pull request closed without merging**
