### PR TITLE
[TS] LPD-21945

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team,

**Ticket:** https://liferay.atlassian.net/browse/LPD-21945
**Previous PR:** https://github.com/liferay-core-infra/liferay-portal/pull/6852

This PR includes the following changes:
- Patch third-party library to apply performance optimization for El Expression evaluation
    - Inspired by Tomcat's optimization:
        - Bug ticket: https://bz.apache.org/bugzilla/show_bug.cgi?id=57583
        - Commit: https://github.com/apache/tomcat/commit/887780699806b5e72f601fc222e4b9c720e61d92
    - We decided to implement this optimization with a different approach: by introducing a wrapper for the ClassLoader to throw the ClassNotFoundException earlier.

**Note:** The optimization is only applied for El Expressions that are not scoped (e.g. ${myExpression} ) and would not be applied to El Expressions that are scoped (e.g. ${scope.myExpression} )

This is to be expected, as the optimization was intended for only the non-scoped case.
- Reference: https://github.com/apache/tomcat/commit/887780699806b5e72f601fc222e4b9c720e61d92#diff-9967205f7459ab41b5ae1a6267e909602c9e963b13d32658a6483a936f1e0c6aR81-R87

I'll also leave a sample of my test results from my manual testing below.

Please let me know if you have any questions.
Thanks!

----

**Test Results - Manual Testing**
Looking at the test results from my manual testing, we can see that **testElExpressionWithUndefinedVariablesJsp** is much faster with our fix and **testElExpressionWithUndefinedScopedVariablesJsp** remains the same.

**Before Fix:**
- Completed com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest#testElExpressionWithUndefinedScopedVariablesJsp in **3129 ms**
- Completed com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest#testElExpressionWithUndefinedVariablesJsp in **3111 ms**
- Completed com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest#testJsp in **200 ms**

**After Fix:**
- Completed com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest#testElExpressionWithUndefinedScopedVariablesJsp in **3543 ms**
- Completed com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest#testElExpressionWithUndefinedVariablesJsp in **246 ms**
- Completed com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest#testJsp in **122 ms**

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:2559918891

**Comment by ericyanLr** [comment]
**ci:report Results**
No unique failures and no did not run failures reported.

Marking this as QA Passed and Ready to Review (no regression)

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
**Update**
Sorry for the last minute changes, I noticed in the test class that we need to surround the serviceTracker portion with a try/finally block:
```
serviceTracker.open();

try {
	Assert.assertNotNull(serviceTracker.waitForService(2000));
}
finally {
	serviceTracker.close();
}
```

Since an assertion failure would result in the serviceTracker not being closed.

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:2559993288

**Comment by ericyanLr** [comment]
**ci:report Results**
No unique failures.

Marking this as QA Passed and Ready to Review (no regression)

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/149182

**Pull request closed without merging**
