### PR TITLE
Lpd 31842 7 24

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:search

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:report:44776891

**Comment by dantewang** [comment]
ci:report:44686498

**Comment by dantewang** [comment]
ci:report:44686410

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:45191819

**Comment by dantewang** [comment]
@tinatian No unique failure marked in search and upgrade; the unique failures in the 2 relevant runs are different, and due to being aborted.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/152668

**Pull request closed without merging**
