### PR TITLE
[TS] LPS-180849 Permission issue with shareable iframe fragments

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
The Guest user cannot see the contents of a shareable iframe, if it is put in a fragment.
The cause of the issue is that the Widget URL is pointing to the Draft Layout instead of the Published Layout.

Proposed Solution
========
Appending the Published Layout's friendly URL instead of the draft's URL, so that the shared iframe contains the right URL that can be seen by guest users too.

Steps to Verify
========

1. Start the bundle and log in as admin
2. At Content & Data > Web content, create a new web content
3. Add View permission for Guest user on the Web content (set by default)
4. On Home page, go to Edit mode, add a Web content display, and configure it to display the above-created web content
5. From the Sharing tab of the configuration, copy the code for sharing. Please note that at this point the URL in the snipped is generated by `PortalImpl.getWidgetURL()` and in turn `PortalImpl.getServletURL()`. The result can be seen in the screenshot below.
6. Toggle "Allow users to add Web Content Display to any website." to true and save the changes
7. Publish the Home page
8. At Design > Fragments, create a new fragment set and a fragment
9. Place the above-copied code into the fragment and save it. Please note that because the fragment and its encompassed URL are saved, the URL will be accessed at step 11.
10. Create a new public page and add the fragment to it, then publish it
11. Log out and visit the page as Guest user

 *Expected result:* Guest users can see the web content which is shared on the page by the shareable iframe 
 *Actual result:* the access is forbidden, the Guest user cannot see it, works correctly with the admin user

Screenshot 2023-03-27 at 14 51 09

The test case that covers this scenario is the following.

The comments point out which code line corresponds to which reproduction step. Please note that not all steps have to have a corresponding part in the test because they are not necessary to reproduce the issue. For example, no Web Content is created as checking the access to the Web Content Display portlet is sufficient. Also, the Fragment with its containing `widgetURL` is omitted as the bug affects the `widgetURL` so we will check it individually and directly. The new public page from Step 10 is not needed either.

```
	@Test
	public void testWidgetURLResponse() throws Exception {
		Layout draftLayout = _layout.fetchDraftLayout(); // 4.

		ThemeDisplay themeDisplay = ContentLayoutTestUtil.getThemeDisplay(
			_company, _group, draftLayout);  // 4.

		themeDisplay.setPortalURL(_company.getPortalURL(_group.getGroupId())); // 4.

		String portletId = LayoutTestUtil.addPortletToLayout(
			draftLayout, JournalContentPortletKeys.JOURNAL_CONTENT);  // 5.

		Portlet portlet = PortletLocalServiceUtil.getPortletById(
			_company.getCompanyId(), portletId);   // 5.

		URL widgetURL = new URL(_portal.getWidgetURL(portlet, themeDisplay));  // 5.

		ContentLayoutTestUtil.publishLayout(draftLayout, _layout);   // 7.

		HttpURLConnection connection =
			(HttpURLConnection)widgetURL.openConnection();   // 11.

		connection.setRequestMethod("GET");   // 11.

		connection.connect();  // 11.

		Assert.assertEquals(
			HttpURLConnection.HTTP_OK, connection.getResponseCode());
	}
```

The test uncovers the root cause of the failure of the scenario in the reproductions steps. Both in the reproduction steps and in the test the `widgetURL` is created from the draft layout and in both cases they are stored for the Guest user to access later.

Thank you and best regards,
István

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found. The bug is not reproducible with the changes.

**Comment by yuhai** [comment]
@IstvanD, @evibudai,

For the current fix, it will cause the issue if Web Content Display portlet only existed in the draft page, when you create fragment by using its Sharing code, you will see the error **You do not have the roles required to access this portlet** display in the UI because its published layout doesn't exist Web Content Display portlet. 

For example,
1.In the content page(edit it), add new Web Content Display portlet to the draft page, copy its sharing code.
The fix will use published layout's friendlyURL.
2. Create fragment with the sharing code. You will see the above mentioned error.

Actually, if we enable the logger **com.liferay.portal.util.PortalImpl** for debug, when guest user access, debug log will output **[PortalImpl:6750] User 20099 must have UPDATE permission for com.liferay.portal.kernel.model.Layout 4**. That's because  `ContentLayoutTypeController#includeLayoutContent()` check layout's update permission and throw the PrincipalException. So this is  admin and guest user's difference because admin user own Update permission and can't reproduce the issue.

We need to further check the root issue.

**Comment by yuhai** [comment]
@IstvanD, @evibudai,

I have two suggestions for the case.
1. Confirm if the use case(copy portlet's sharing code url in the draft layout) is reasonable. I think it is reasonable.
2. If 1 answer is reasonable. I have a way to fix it. Move the [codes ](https://github.com/IstvanD/liferay-portal/blob/LPS-180849/modules/apps/layout/layout-type-controller/layout-type-controller-content/src/main/java/com/liferay/layout/type/controller/content/internal/layout/type/controller/ContentLayoutTypeController.java#L103-L119) to the block `if (layoutMode.equals(Constants.EDIT))`. The fix looks like
```
if (layoutMode.equals(Constants.EDIT)) {
        if (layout.isDraftLayout()) {
	      ....
	}

	if (hasUpdatePermissions == null) {
		hasUpdatePermissions = _hasUpdatePermissions(
			themeDisplay.getPermissionChecker(), layout);
	}
}
```
If the fix way is good for you, please send it to liferay-echo user.

I am going to close the pr. Please let me know if you have other concerns.

**Comment by IstvanD** [comment]
Hi @yuhai 

Thank you for your excellent analysis and the solution!

I'll send the pull request to the Echo Team.

Best regards,
István

**Pull request closed without merging**
