### PR TITLE
remove_unused_properties_part5

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

I have removed six unused properties "Dl.", which included "dl.folder.icon.check.count", "Dl.file.entry.open.in.ms.office.manual.check.in.required", "dl.file.entry.version.policy", "dl.file.entry.preview.document.depth", "dl.file.entry.thumbnail.video.frame.percentage", "dl.file.entry.preview.auto.create.on.upgrade".

Dl.folder.icon.check.count: It was finally deleted on commit https://github.com/tinatian/liferay-portal/commit/67de38000200cdb8283fe6f5f5a66a9d9b8d5622, see LPS-68221
Dl.file.entry.open.in.ms.office.manual.check.in.required: Its usage was deleted in commit https://github.com/tinatian/liferay-portal/commit/1baca9f2ef306194bdda40807d3c941729d89a0e, see LPS-49982.
Dl.file.entry.version.policy: It was removed the usage in commit https://github.com/tinatian/liferay-portal/commit/fa24f805f05b500e3721c852caf05f377bff1a28, see LPS-57406
Dl.file.entry.thumbnail.video.frame.percentage: The usage was finally deleted in commit https://github.com/tinatian/liferay-portal/commit/cbbef2d22277d9f326c39e79f914d680278d750f, see LPS-117661
Dl.file.entry.preview.document.depth: Its usage was deleted based on commit https://github.com/tinatian/liferay-portal/commit/7108c446d697d90ed6072bbb315ae6bdfad9a3d9, see LPS-27518.
Dl.file.entry.preview.auto.create.on.upgrade: It was finally deleted in commit https://github.com/tinatian/liferay-portal/commit/5efe3478d41f068b0ff69ac2956c5a79bc5a183d, see LPS-76929.

Thanks for checking . Also see https://github.com/tinatian/liferay-portal/pull/2493 and https://github.com/jeffwu0724/liferay-portal/pull/34

Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@kyle-miho Hey Kyle, could you please help me to scan the test result?

Thanks,
Jeff

**Comment by kyle-miho** [comment]
@jeffwu0724 pr looks good to go, failing results on default ci test are random failures, relevant full passed

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
