### PR TITLE
LPS-171496 Remove "immediate = true" from Core Infrastructure part 5

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:lpkg

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by chaowang-123** [comment]
@dantewang The failures are not related, and no regression was found.

**Comment by catarineaguiar** [comment]
@chaowang-123 thanks!!

**Comment by RenanUmV** [comment]
Hey @shuyangzhou , this one is ready to go!

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2831

**Pull request closed without merging**
