### PR TITLE
[System Properties][Part Four] LPS-153430 Move some properties that moduleFramework needs during init

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I moved some properties that moduleFramework needs during init

depends on LPS-158209(https://github.com/liferay-core-infra/liferay-portal/pull/1438)

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results when they finish ? Thanks!

**Comment by W2jx** [comment]
Hi @catarineaguiar , Could you please help me check the test results when they finish ? Thanks!

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
@W2jx possible regression:

```
 [exec] com.liferay.portal.lpkg.deployer.controller.LPKGControllerTest > testLPKGControllerDeploy FAILED
     [exec]     java.nio.file.NoSuchFileException: /opt/dev/projects/github/liferay-portal/modules/apps/static/portal-lpkg-deployer/portal-lpkg-deployer-test/liferay/osgi/marketplace/Liferay Controller Test.lpkg
     [exec]         at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
     [exec]         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
     [exec]         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
     [exec]         at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
     [exec]         at java.nio.file.Files.newByteChannel(Files.java:361)
     [exec]         at java.nio.file.Files.createFile(Files.java:632)
     [exec]         at com.liferay.portal.lpkg.deployer.controller.LPKGControllerTest.testLPKGControllerDeploy(LPKGControllerTest.java:50)
```
```
  [exec] com.liferay.portal.lpkg.deployer.controller.test.LPKGControllerVerifyTest > testLPKGController FAILED
     [exec]     java.lang.AssertionError: No JAR bundle found
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
     [exec]     	at org.junit.Assert.assertNotNull(Assert.java:713)
     [exec]     	at com.liferay.portal.lpkg.deployer.controller.test.LPKGControllerVerifyTest.testLPKGController(LPKGControllerVerifyTest.java:77)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-35/test-portal-acceptance-pullrequest(master)/2375/lpkg-controller-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
@catarineaguiar Thank you.

**Comment by W2jx** [comment]
Hi @catarineaguiar @dantewang ,These errors maybe exist on the master branch. Because I run these two tests on my local master branch, they get the same results as these two

**Comment by W2jx** [comment]
Push code just to resolve conflicts.

**Comment by catarineaguiar** [comment]
@W2jx ok, so this pull is good to go.

**Comment by tinatian** [comment]
@W2jx There is no pull about LPS-158209

**Comment by tinatian** [comment]
@W2jx Please link the pulls you depend on.

**Comment by W2jx** [comment]
@tinatian sorry, I closed that pr yesterday, and I will resend it today.

**Comment by W2jx** [comment]
Hi @tinatian @dantewang ,I have resent the dependent pr LPS-158209(https://github.com/liferay-core-infra/liferay-portal/pull/1438)

**Comment by W2jx** [comment]
no conflicts(11:08 PM)

**Comment by W2jx** [comment]
no conflicts(6:50 AM)

**Comment by W2jx** [comment]
no conflicts(7:09 PM)

**Comment by W2jx** [comment]
Force push just to resolve the conflict about portal-kernel/bnd.bnd

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
force-push just to resolve conflict about files packageinfo and bnd.bnd(3:47 PM)

**Comment by W2jx** [comment]
no conflicts(6:16 PM)

**Comment by catarineaguiar** [comment]
@W2jx on lpkg-controller-test [history](https://testray.liferay.com/home/-/testray/case_results/1957122767/history?tab=result&hideFilterPin=true) there is only this failure in your branch. It seems to be related to your changes.

```
  [exec] com.liferay.portal.lpkg.deployer.controller.LPKGControllerTest > testLPKGControllerDeploy FAILED
     [exec]     java.nio.file.NoSuchFileException: /opt/dev/projects/github/liferay-portal/modules/apps/static/portal-lpkg-deployer/portal-lpkg-deployer-test/liferay/osgi/marketplace/Liferay Controller Test.lpkg
     [exec]         at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
     [exec]         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
     [exec]         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
     [exec]         at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
     [exec]         at java.nio.file.Files.newByteChannel(Files.java:361)
     [exec]         at java.nio.file.Files.createFile(Files.java:632)
     [exec]         at com.liferay.portal.lpkg.deployer.controller.LPKGControllerTest.testLPKGControllerDeploy(LPKGControllerTest.java:50)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-36/test-portal-acceptance-pullrequest(master)/1902/lpkg-controller-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
OK Thank you@catarineaguiar, I will check it.

**Pull request closed without merging**
