### PR TITLE
[Remove Stream/Optional usage] LPS-171708 test_remove_usage_of_stream_on_object_rest_impl

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Resend https://github.com/liferay-core-infra/liferay-portal/pull/2883
This is for ticket https://issues.liferay.com/browse/LPS-171708.
Thanks for checking!

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:objects

**Comment by catarineaguiar** [comment]
ci:test:object

**Comment by catarineaguiar** [comment]
ci:test:headless

**Comment by Kvale1733** [comment]
@jeffwu0724 Regression found

Relationships not shown in object curl response

Steps to reproduce:
       i. Go to Control Panel > Objects
       ii. Add new Object with label "University" and plural label "Universities"
       iii. Click on the newly created University Object and go to Fields tab
       iv. Add new field called Name of type Long Text
       v. Publish the University Object
       vi. Add new object with label "Subject" and plural label "Subjects"
       vii. Click on newly created Subect Object and go to Fields Tab
       viii. Add  new field called Name of Type Long Text
       IX. Publish the Subjects object
       X. Go back to Objects admin and click on University Object
       Xi. Go to relationships tab
       Xii. Add new relationship with label "universitiesSubjects" of type Many To Many. For Object select Subject and save.
       Xiii. Create a University object entry with
       ```
       curl -X POST -u 'test@liferay.com:test' -H 'Content-Type: application/json' -d '{"name": "Liferay First University"}' http://localhost:8080/o/c/universities
      ```
      Remember the ID for the entry (last Id value in the curl response)
      XIV. Create a Subject object entry with 
      ```
      curl -X POST -u 'test@liferay.com:test' -H 'Content-Type: application/json' -d '{"name": "Liferay Foundation"}' http://localhost:8080/o/c/subjects
      ```
      Remember the ID for the entry (last Id value in the curl response)
      XV. Relate the subject entry and the university entry with
      ```
      curl -X PUT -u 'test@liferay.com:test' http://localhost:8080/o/c/universities/${universityID}/universitiesSubjects/${subjectID}
      ```
      XVI. View the Subject entries with 
      ```
      curl -X GET -u 'test@liferay.com:test' http://localhost:8080/o/c/subjects?nestedFields=universitiesSubjects
      ```

Expected Results: The curls response includes all linked university objects
```
"name" : "Liferay Foundations",
     [exec]         "universitiesSubjects" : [ {
     [exec]           "creator" : {
     [exec]             "additionalName" : "",
     [exec]             "contentType" : "UserAccount",
     [exec]             "familyName" : "Test",
     [exec]             "givenName" : "Test",
     [exec]             "id" : 51283,
     [exec]             "name" : "Test Test"
     [exec]           },
     [exec]           "dateCreated" : "2023-01-05T19:41:28Z",
     [exec]           "dateModified" : "2023-01-05T19:41:28Z",
     [exec]           "externalReferenceCode" : "c9b3d34e-51e0-e84d-09b1-81b99db7b398",
     [exec]           "id" : 53716,
     [exec]           "status" : {
     [exec]             "code" : 0,
     [exec]             "label" : "approved",
     [exec]             "label_i18n" : "Approved"
     [exec]           },
     [exec]           "name" : "Liferay First University"
     [exec]         }, {
     [exec]           "creator" : {
     [exec]             "additionalName" : "",
     [exec]             "contentType" : "UserAccount",
     [exec]             "familyName" : "Tes...
```

Actual Results: The curl response does not include the link University entry
```
 "creator" : {
     [exec]           "additionalName" : "",
     [exec]           "contentType" : "UserAccount",
     [exec]           "familyName" : "Test",
     [exec]           "givenName" : "Test",
     [exec]           "id" : 61728,
     [exec]           "name" : "Test Test"
     [exec]         },
     [exec]         "dateCreated" : "2023-01-05T19:09:14Z",
     [exec]         "dateModified" : "2023-01-05T19:09:14Z",
     [exec]         "externalReferenceCode" : "2e6f7338-97b0-0c4d-8f3e-acf97d33590c",
     [exec]         "id" : 64165,
     [exec]         "status" : {
     [exec]           "code" : 0,
     [exec]           "label" : "approved",
     [exec]           "label_i18n" : "Approved"
     [exec]         },
     [exec]         "name" : "Liferay Foundations"
     [exec]       } ],
     [exec]       "lastPage" : 1,
     [exec]       "page" : 1,
     [exec]       "pageSize" : 20,
     [exec]       "totalCount" : 1
     [exec]     }Finished executing commands.
```

**Pull request closed without merging**
