### PR TITLE
LPS-185849 Remove multiple configuration from JournalPortlet

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from #4905

### CODE REVIEW

**Comment by julschong** [comment]
@GinsonRen Hi Ginson,
JournalPortlet with this pull no longer cache 4 configurations. Instead, they are fetched using configuration provider each time on render() and serveResource()
Could you please help us run performance test on: web content and  login?
we'd like to see the impact of this change to evaluate.
Thanks!

**Comment by chaowang-123** [comment]
ci:test:echo

**Comment by GinsonRen** [comment]
@julschong Here are the test results:
Login
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | b284fab | 47703 | 262 | -
PR-4950 | - | 48104 | 269 | 0.84%

WC

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | b284fab | 63521 | 480 | -
PR-4950 | - | 62436 | 498 | -1.71%

**Comment by julschong** [comment]
@tinatian what do you think?

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
