### PR TITLE
LPS-165735 Rename commerceDiscountApplicationStrategy to commerceDiscountApplicationStrategyKey

### PR DESCRIPTION
**Pull request by W2jx**
Previous: https://github.com/brianchandotcom/liferay-portal/pull/128800

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
commerce tests were untested due to a frontend failure, it is not related to the PR changes.

**Comment by dantewang** [comment]
@yuhai Does this kind of change require a config upgrade process?

**Comment by yuhai** [comment]
> @yuhai Does this kind of change require a config upgrade process?

@dantewang yes.

@W2jx, if we saved the previous configuration, the data will be saved to configuration_ table. If we changed the property name, we need to write upgrade process to correct the previous data(the previous property was **commerceDiscountApplicationStrategy**="chain", the current property is **commerceDiscountApplicationStrategyKey**="chain"). Please refer to KBGroupServiceConfigurationUpgradeProcess class. You may search the similar cases by using keyword "_configurationAdmin.listConfigurations" in the *UpgradeProcess.java. Please add the upgrade process.

**Comment by dantewang** [comment]
@W2jx Closing this pull, please resend with upgrade process, thanks!

**Pull request closed without merging**
