### PR TITLE
Lpd 20946 9 23

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
ci:test:object

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:core-functional

**Comment by tinatian** [comment]
@JerryAdrianoo Please help me verify startup performance. Thanks!

**Comment by tinatian** [comment]
ci:report:19440914

**Comment by JerryAdrianoo** [comment]
Hey @tinatian  for more details, see: [spreadsheet](https://docs.google.com/spreadsheets/d/14QzRyLB0pCrLzc-gxmJKC2CWvNXzH9XqXp0HYQBCdNE/edit?usp=sharing) 

Branch| Startup Time (ms)(without  default HSQL data)  Cold start | Percent of Average Startup Time Cold Start | Startup Time (ms)(without  default HSQL data) Hot start | Average Startup Time (ms)(without default HSQL data)  Hot start | Percent of Average Startup Time Hot Start | Shutdown Time (ms)(without default HSQL data)   Cold start | Shutdown Time (ms)(without default HSQL data)  Hot start | Average Shutdown Time (ms)(without default HSQL data)  Hot start
-- | -- | -- | -- | -- | -- | -- | -- | --
Before LPD-20946 | **43,385** | | 16,341 | | | **2,576** | 1,946
|  | | | 16,090 | | | | 1,998
|  | | | 16,419 | | | | 1,959
 | | | | 15,820 | | | | 1,911
 | | | | 16,808 |**16,283** | | | 1,995 | **1,967**
-- | -- | -- | -- | -- | -- | -- | --
After LPD-20946 | **43,783** | | 16,561 | | | **2,573** | 1,995
|  | | | 16,519 | | | | 1,872
|  | | | 16,609 | | | | 2,011
|  | | | 16,088 | | | | 1,940
| | |  0.92% | 16,397 |**16,409** |  **0.77**% | | 2,045 | **1,982**

**Open Count of SQL** decreased by 261 points. Other than this, no other improvements were noticed.

**Comment by tinatian** [comment]
ci:report:19559207

**Comment by tinatian** [comment]
ci:report:19556574

**Comment by tinatian** [comment]
ci:report:19440914

**Comment by tinatian** [comment]
ci:report:19477662

**Comment by dantewang** [comment]
ci:test:relevant

The following failures are not unique:
```
PortalLogAssertorTest-modules-integration-mysql57-jdk8/2/1
PortalLogAssertorTest-modules-integration-mysql57-jdk8/0/20
```

The following tests failed to run on CI, re-trigger to see if it's a CI issue.
```
com.liferay.portal.uad.exporter.test.RepositoryUADExporterTest
com.liferay.portal.uad.exporter.test.SystemEventUADExporterTest
com.liferay.portal.upgrade.test.AutoUpgradeProcessTest
com.liferay.portal.upgrade.test.BasePortletPreferencesUpgradeProcessTest
com.liferay.portal.upgrade.test.BaseUpgradeCallableTest
com.liferay.portal.upgrade.test.BaseUpgradePortletIdTest
com.liferay.portal.upgrade.test.DBUpgraderTest
com.liferay.portal.upgrade.test.GuestUnsupportedResourcePermissionsUpgradeProcessTest
com.liferay.portal.upgrade.test.LiveUpgradeExecutorTest
com.liferay.portal.upgrade.test.LiveUpgradeSchemaDiffTest
com.liferay.portal.upgrade.test.ModuleBuildAutoUpgradeTest
com.liferay.portal.upgrade.test.PortalUpgradeProcessTest
com.liferay.portal.upgrade.test.Pre7UpgradeProcessTest
com.liferay.portal.upgrade.test.ReleaseManagerTest
com.liferay.portal.upgrade.test.ReleasePublisherTest
com.liferay.portal.upgrade.test.UpgradeCTModelTest
com.liferay.portal.upgrade.test.UpgradeCompanyIdTest
com.liferay.portal.upgrade.test.UpgradeLogAppenderUpgradeClientTest
com.liferay.portal.upgrade.test.UpgradeLogAppenderUpgradeOnStartupTest
com.liferay.portal.upgrade.test.UpgradeManagerTest
```

> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 19559207.
> 
> Job Link: [generate-testray-csv](https://test-1-2.liferay.com/job/generate-testray-csv/113/)
> 
> Testray CSV Link: [testray-results-19559207.csv](https://test-1-2.liferay.com/userContent/jobs/generate-testray-csv/builds/113/testray-results-19559207.csv)

**Comment by tinatian** [comment]
ci:report:21133420

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 19440914.
> 
> Job Link: [generate-testray-csv](https://test-1-29.liferay.com/job/generate-testray-csv/204/)
> 
> Testray CSV Link: [testray-results-19440914.csv](https://test-1-29.liferay.com/userContent/jobs/generate-testray-csv/builds/204/testray-results-19440914.csv)

Unique failures in report are not unique to this pull

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 21133420.
> 
> Job Link: [generate-testray-csv](https://test-1-32.liferay.com/job/generate-testray-csv/236/)
> 
> Testray CSV Link: [testray-results-21133420.csv](https://test-1-32.liferay.com/userContent/jobs/generate-testray-csv/builds/236/testray-results-21133420.csv)

NO unique failure in report

**Comment by tinatian** [comment]
ci:forward:force

**Comment by tinatian** [comment]
ci:report:21773315

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 21773315.
> 
> Job Link: [generate-testray-csv](https://test-1-39.liferay.com/job/generate-testray-csv/428/)
> 
> Testray CSV Link: [testray-results-21773315.csv](https://test-1-39.liferay.com/userContent/jobs/generate-testray-csv/builds/428/testray-results-21773315.csv)

No unique failure in report

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
