### PR TITLE
LPS-165250 Tags in ftl that had uppercase first letter in attributes break

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:reevaluate:1387401_4244

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Unit tests [com.liferay.portal.tools.sample.sql.builder.io.CharPipeTest](https://testray.liferay.com/home/-/testray/case_results/2006309546) and [com.liferay.fragment.internal.validator.FragmentEntryValidatorImplTest](https://testray.liferay.com/home/-/testray/case_results/2006309519) failed with compile error
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-freemarker/src/test/java/com/liferay/portal/template/freemarker/internal/RestrictedLiferayObjectWrapperTest.java:605: error: method does not override or implement a method from a supertype
     [exec] 		@Override
```

Full console log:
https://testray.liferay.com/reports/production/logs/2022-10/test-1-37/test-portal-acceptance-pullrequest(master)/5630/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
