### PR TITLE
[Blocker] LPS-199163 

### PR DESCRIPTION
**Pull request by JanisZhang**
@shuyangzhou Hi Shuyang,
Resent: https://github.com/liferay-core-infra/liferay-portal/pull/5803
I moved the `DefaultFullNameGenerator` bean to /META-INF/infrastructure-spring.xml. Verified OK on my local env.
Thanks for checking.
cc @dantewang @yuhai 
Ticket: https://liferay.atlassian.net/browse/LPS-199163

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by zhangyan0701** [comment]
No regressions found.

The upgrade tests from 6130 passed.

**Comment by JanisZhang** [comment]
@zhangyan0701 Thanks Summer!

**Comment by brunofalc** [comment]
Hey @shuyangzhou if you can please prioritize this Pull

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142606

**Pull request closed without merging**
