### PR TITLE
[Hibernate] LPS-128873 Upgrade to Hibernate 5.6.7.Final

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
@vicnate5 @zhangyan0701 Please help with reviewing the results when they finish, thanks!

**Comment by vicnate5** [comment]
Analysis triggered https://test-1-1.liferay.com/job/generate-testray-csv/98/

**Comment by vicnate5** [comment]
@catarineaguiar can you check this one? See the link above.

**Comment by vicnate5** [comment]
@dantewang @tinatian No regressions found.

**Comment by dantewang** [comment]
@tinatian The `INSTANCE` constants should be added because I saw same thing in the Hibernate default implementations, but it turns out that they are explicitly used, so these in our classes will not help. I removed them.
I also removed the property.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115927
Very good guys!

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
