### PR TITLE
LPD-36671

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team,

**Ticket:** https://liferay.atlassian.net/browse/LPD-36671

Here's the proposed fix for handling the test failure: 
[Investigate test failures in DatabasePartitioning#CanAddCompanyWithPortalInstancesAdminUI and Clustering#CanCreateVirtualInstanceWithClusterDBPartitioningAndLOLProperties](https://liferay.atlassian.net/browse/LPD-36395)

This change is inspired by this commit:
https://github.com/liferay/liferay-portal/commit/e0d4e64486f26fcfac927b69409f6a0306a915a0

**Note:** I haven't tested this by running the actual test

@julschong , can you help verify if this resolves the issue?

Please let me know if you have any questions.
Thanks!

/cc @tinatian

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:help

**Comment by julschong** [comment]
looks like pr tester is down right now. important tests to trigger and review are clustering and database partition shown here: https://testray.liferay.com/#/testflow/10109043/subtasks/10109097

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:clustering

**Comment by julschong** [comment]
ci:test:db-partition

**Comment by ericyanLr** [comment]
**Update**
Looking at the results from: `ci:test:relevant`, it looks like this change results in a test failure.

<h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1032309//consoleText">modules-integration-mysql57-jdk8/0/1</a><ol><li><details><summary><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1032309/testReport/com.liferay.layout.content.page.editor.web.internal.portlet.action.test/AddFragmentEntryLinksMVCActionCommandTest">com.liferay.layout.content.page.editor.web.internal.portlet.action.test.AddFragmentEntryLinksMVCActionCommandTest</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/12678665/history">Failed 0 of last 18</a></summary><div><ol><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1032309//testReport/com.liferay.layout.content.page.editor.web.internal.portlet.action.test/AddFragmentEntryLinksMVCActionCommandTest/testAddDropZoneFragmentEntryLinks">testAddDropZoneFragmentEntryLinks</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1032309//testReport/com.liferay.layout.content.page.editor.web.internal.portlet.action.test/AddFragmentEntryLinksMVCActionCommandTest/testAddFragmentEntryLinks">testAddFragmentEntryLinks</a></li></ol></div></details></li></ol></div></li></ol>

**Comment by julschong** [comment]
passed cluster test https://testray.liferay.com/#/project/35392/routines/45357/build/13602269/case-result/13605740
passed db partition tests https://testray.liferay.com/#/project/35392/routines/45357/build/13643909

ready to be reviewed

**Comment by julschong** [comment]
ci:report:13643909

**Comment by julschong** [comment]
ci:report:13602269

**Comment by julschong** [comment]
Hi @ericyanLr please check out this test that failed from relevant
https://testray.liferay.com/#/project/35392/routines/45357/build/13606931/case-result/13613247

**Comment by julschong** [comment]
unique failure from https://github.com/liferay-core-infra/liferay-portal/pull/7433#issuecomment-2357014502
seems unrelated

**Comment by tinatian** [comment]
@ericyanLr @julschong Please see slack message, I am going to close this pull and hand this over to site tantalizer team

**Pull request closed without merging**
