### PR TITLE
[Method References] LPS-162511 Convert method references to field references in modules portal-scheduler*

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I convert method references to field references in modules portal-scheduler*.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results when they finish ? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by julschong** [comment]
ci:forward

**Comment by julschong** [comment]
ci:close

**Comment by julschong** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/122969

**Pull request closed without merging**
