### PR TITLE
[TS]LPS-152875 - Upgrade org.json:json to 20220320 to resolve DoS vulerability

### PR DESCRIPTION
**Pull request by javalosjr96**
Ticket:
https://issues.liferay.com/browse/LPS-152875

Previous PR:
https://github.com/liferay-core-infra/liferay-portal/pull/829

Description:
In order to be able to update org.json, changes needed to be made in two areas:

The current jabsorb needed to be modified to allow the usage of BigDecimal.
Added the positive character to the list operators to the json parser account for positive scientific notation.

Notes from @mbowerman:

> The reason that we updated jabsorb was because with the latest json library, decimal numbers are now being parsed as BigDecimal by default instead of as doubles. Therefore, we need to have a serializer that can unmarshall a BigDecimal field to a double. Please see the discussion on https://github.com/mbowerman/liferay-portal/pull/122 surrounding this.

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
@javalosjr96 The SF failure has nothing to do with your changes. Looks like Brian Chan messed up the SF again: https://github.com/liferay/liferay-portal/commit/fb60a828272f1545870ff05cc99ce19fd29de929#diff-ed8699bd42fe0430b4624dfa7c8b0b4f9f93c3528edf2a0cb8339af2b27f85a5R72

**Comment by mbowerman** [comment]
I sent a pull request to fix the SF errors here: https://github.com/brianchandotcom/liferay-portal/pull/118383

**Comment by mbowerman** [comment]
SF should be fixed now. You could try rebasing to latest master and force-pushing.

**Comment by javalosjr96** [comment]
@mbowerman 
Alright

**Comment by javalosjr96** [comment]
@mbowerman It's currently only on bchan's master so it'll drag all his unmerged commits.

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
Looks like the latest SF error was caused by https://github.com/liferay/liferay-portal/commit/20909188cfd72aed5c7033cd62a6845241a2fcc7 and should probably be fixed with Brian Chan's latest commit here: https://github.com/brianchandotcom/liferay-portal/commit/fc05772aaba56744e4876b7d51d90aededce38f2. But we still have to wait for it to be merged into upstream.

**Pull request closed without merging**
