### PR TITLE
[TS] LPS-195754

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:environments

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found. Manual test passed with the ticket steps.

**Comment by yuhai** [comment]
@marianoalvarosaiz, after my investigation, I find the ticket's description is not right.
1. `name like '%_%' escape ''` will always return all roles.  So using this script can't reproduce the issue.
2. The issue happened in the all databases. Because the root issue is that **ESCAPE** character was deleted in the generated sql.  And ticket's description statement the issue happened on the Oracle. 

Please firstly changes the ticket's description as the below.
1. Create one role. title: 50%.
2. Go to Control Panel -> Server Administration -> Groovy, run the script:
`dynamicQuery.add(RestrictionsFactoryUtil.sqlRestriction("name like '%50@%%' escape '@'"));`

**Expected behavior:**
The role 50% is returned.

**Actual behavior:**
The role isn't returned.

**Back to the fix:**
The pr patched the third party to fix the issue. But it seems weird instanceof subClassObject in the parentClass. In the fix code fragment `BinaryExpression#toString()`, if we change LeftExpression and rightExpression order, the issue should be resolved. I mean change the [codes](https://github.com/marianoalvarosaiz/liferay-portal/blob/LPS-195754/modules/apps/static/portal/portal-change-tracking/src/main/java/com/liferay/portal/change/tracking/internal/CTSQLTransformerImpl.java#L1201-L1202) from `new AndExpression(whereExpression, ctExpression)` to `new AndExpression(ctExpression, whereExpression);`

In addition, please add one test to expose issue in the DynamicQueryTest.

Please resend it and let me know if you have further concerns.

Thanks,
Hai

**Comment by marianoalvarosaiz** [comment]
@yuhai 

>I find the ticket's description is not right

My mistake copying the customer script. You're right. I change the where clause in the description. The translation is database agnostic, but the syntax is proper from Oracle and not MySQL for example.


>Back to the fix:
The pr patched the third party to fix the issue. But it seems weird instanceof subClassObject in the parentClass. In the fix code fragment BinaryExpression#toString(), if we change LeftExpression and rightExpression order, the issue should be resolved. I mean change the [codes](https://github.com/marianoalvarosaiz/liferay-portal/blob/LPS-195754/modules/apps/static/portal/portal-change-tracking/src/main/java/com/liferay/portal/change/tracking/internal/CTSQLTransformerImpl.java#L1201-L1202) from new AndExpression(whereExpression, ctExpression) to new AndExpression(ctExpression, whereExpression);

It does fix it, but only if `whereExpression` is a simple expression. If it is composed from 1+ BinaryExpression (`name like '%test@%%' escape '@' and companyId != 0"`) the problem will be the same. The order of the like expression matters and in the moment that is not the last appearing expression in the where clause it will fail.

The need to refer to the subclass is that although LikeExpression is a BinaryExpression by design in the _jsqlparser_ library, in its implementation really it isn't from the point of view that `LikeExpression#leftExpression()#toString() + LikeExpression#geStringExpression() + LikeExpression#getRightExpression()#toString() != LikeExpression#toString()`

**Comment by marianoalvarosaiz** [comment]
@yuhai see added test: https://github.com/liferay-core-infra/liferay-portal/pull/5576

**Pull request closed without merging**
