### PR TITLE
LPS-178903 remove deprecated usage of vulcan.util.TransformUtil in base_resource_impl.ftl

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This is for ticket https://issues.liferay.com/browse/LPS-178903.
I tired to remove the deprecated com.liferay.portal.vulcan.util.TransformUtil, and changed to use com.liferay.petra.function.transform.TransformUtil
Thanks for checking!

### CODE REVIEW

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by tinatian** [comment]
@jeffwu0724 Please remove the deprecated TransformUtil.

Thanks.
Tina

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
fixed the code conflict

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
fix the code conflict by "gw buildREST", the previous test should be good enough

**Comment by dantewang** [comment]
@jeffwu0724 As a recent merged PR which introduces usage to a new method in petra TransformUtil broke 7.3 because there's no petra TransformUtil on 7.3.

BChan made a quick fix, we may take that as a reference, to generate different content for 7.3 vs 7.4.

@tinatian

**Pull request closed without merging**
