### PR TITLE
[TS] LPD-15247

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__ <https://liferay.atlassian.net/browse/LPD-15247>

This PR fixes the behavior of portal property `locale.prepend.friendly.url.style` when `locale.default.request=true`. Specifically, the issue is that the preferred locales from the servlet request (i.e. the `Accept-Language` request header) were never considered when `locale.prepend.friendly.url.style` was `1` or `3`. I've updated the tests to expose this issue.

At the moment, this is the order of precedence when it comes to where `I18nFilter` gets the locale:

1. Session
2. User
3. Cookie
4. Virtual Host

In regards to the behavior of `locale.default.request=true`, it is unclear where in the list the `Accept-Language` header fits. For now, I placed the `Accept-Language` header last as this fixes the issue while not affecting the current tests. With this PR, the order of precedence is now the following:

1. Session
2. User
3. Cookie
4. Virtual Host
5. `Accept-Language`

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:2555846619

**Comment by tinatian** [comment]
@kevhlee One unique failure from report, please take a look at it.

Thanks.
Tina

**Comment by kevhlee** [comment]
@tinatian, taking a look.

**Comment by kevhlee** [comment]
Hi @tinatian, I checked the unique failure. It passed locally when I ran the test on my machine. I'm not sure what is happening to make that test fail. Do we need to re-run the relevant tests?

**Comment by kevhlee** [comment]
Re-running tests.

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:2556251362

**Comment by tinatian** [comment]
@kevhlee Same test failed again.

**Comment by kevhlee** [comment]
Hi @tinatian, thank you for the heads-up. That is odd but I will take a closer look to see what is happening.

**Comment by tinatian** [comment]
@kevhlee Close this pull, please resend.

Thanks.
Tina

**Pull request closed without merging**
