### PR TITLE
LPS-190994

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**
https://liferay.atlassian.net/browse/LPS-190994

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found

Bug is not reproducible

**Comment by tinatian** [comment]
@marianoalvarosaiz 
For https://github.com/liferay-core-infra/liferay-portal/pull/5051/commits/f55d4ba210458b1d063ae7697a05e19a8ae27086, Zero value is useful to disable jobs. When it is Zero, you should not even start the scheduler job rather than make trigger to disable it

For https://github.com/liferay-core-infra/liferay-portal/pull/5051/commits/d858da257bb31cbb15ede1b5106cd7b01963033c, you can not remove this not all scheduler jobs are triggered by scheduler job configuration.

Please always try your best to add test to cover your changes.

Thanks.
Tina.

**Comment by marianoalvarosaiz** [comment]
@tinatian 

> For https://github.com/liferay-core-infra/liferay-portal/commit/f55d4ba210458b1d063ae7697a05e19a8ae27086, Zero value is useful to disable jobs. When it is Zero, you should not even start the scheduler job rather than make trigger to disable it

OK, but that is how it has always worked, with former MessageListener we also created the trigger.

**Comment by tinatian** [comment]
@marianoalvarosaiz In core infra, we always pursue the best solution as possible as we can rather than keep the original behavior, a bug fix is not only a bug fix usually, it will provide us a hint where we can improve, just like this one.

I would expect a fix not only fix the current issue, but also can make our code more robust, efficient, easy to maintain.

Tina.

**Comment by marianoalvarosaiz** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5140

**Pull request closed without merging**
