### PR TITLE
[Method References] LPS-163567 Convert method references to field references in module portal-search-elasticsearch7-impl | part 4

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have made BaseSearchEngine abstract.

Detial: https://github.com/liferay-core-infra/liferay-portal/pull/1836

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @catarineaguiar  , Could you please help me check the test results ? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by dantewang** [comment]
@W2jx Conflicts. Shuyang made a lot of changes recently to search engine, please rebase your changes and resend.

**Comment by shuyangzhou** [comment]
There is another major one on the way, please hold until this is over https://github.com/shuyangzhou/liferay-portal/pull/10809

**Pull request closed without merging**
