### PR TITLE
[Remove Stream/Optional usage] LPS-172290 remove_optional_in_translation_api

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Resend: https://github.com/liferay-core-infra/liferay-portal/pull/2955
This is for ticket https://issues.liferay.com/browse/LPS-172290.
Thanks for checking!

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:translation

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
