### PR TITLE
[DL Performance] LPS-153313 Remove obsolete display context creation

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:help

**Comment by tinatian** [comment]
ci:test:document

**Comment by tinatian** [comment]
FYI @adolfopa

**Comment by tinatian** [comment]
@vicnate5 Please forget my last message, the test is triggered now. Not sure why it is not triggered the first time I comment it.

Tina.

**Comment by vicnate5** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/118105

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
