### PR TITLE
LPS-143629

### PR DESCRIPTION
**Pull request by julschong**
Hi Shuyang, Tina,

This is the 3rd task on removing **Utils from modules
[Story#LPS-143403](https://issues.liferay.com/browse/LPS-143403)
[Subtask: LPS-143629](https://issues.liferay.com/browse/LPS-143629)

This includes removing ImageToolUtil and UnicodeLanguageUtil

Thank you !

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@vicnate5 
Hi Victor, could you please help me scan the result for this one?
Thank you!

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@vicnate5 Hi Victor, could you please help me check the test results on this pull?
Thank you!

**Comment by vicnate5** [comment]
@julschong Looks good, no regressions found.

**Comment by julschong** [comment]
@tinatian, @shuyangzhou
Hi Shuyang, Tina,
Please help me check if this pull is ready to go.
Thank you!

**Comment by tinatian** [comment]
@julschong As we are going to see more SF failures on 7.3 and earlier with more pulls like this merged in, I would like that we fix the source formatter tool first, then go back to this.

Tina.

**Comment by julschong** [comment]
will resend

**Pull request closed without merging**
