### PR TITLE
LPS-168726 Remove TemplateManagerUtil manual lifecycle methods and use Component lifecycle methods instead

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from #2466

Changes:
- Move ClassLoaderResourceParser to modules to fix https://github.com/liferay-core-infra/liferay-portal/pull/2466#issuecomment-1318367271 instead of removing immediate=true from VelocityManager
- Remove default constructor for TemplateManagerUtil

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@julschong rebase, please. Thanks

**Comment by julschong** [comment]
rebased for conflict in semver

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by julschong** [comment]
@tinatian closing this per our discussion

**Comment by julschong** [comment]
ci:stop

**Pull request closed without merging**
