### PR TITLE
[Components with more than 1 service] LPS-189644 Refactor Portal Cache components from remaining Portal Cache modules

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**
QA PASSED: [https://github.com/liferay-core-infra/liferay-portal/pull/5075](https://github.com/liferay-core-infra/liferay-portal/pull/5075)

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:clustering

**Comment by GabrielHenriquedev** [comment]
ci:test:clustering

**Review by rafaprax — APPROVED** [review]

**Comment by Kvale1733** [comment]
ci:test:document

**Comment by Kvale1733** [comment]
@GabrielHenriquedev No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @tinatian

**Pull request closed without merging**
