### PR TITLE
[LPS-167246 MessageBus] LPS-192572 Clean up use of method Destination.register(MessageListener)

### PR DESCRIPTION
**Pull request by dantewang**
This PR rebases on top of https://github.com/liferay-core-infra/liferay-portal/pull/5182 as both are modifying the same part in some class.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:backend

**Comment by catarineaguiar** [comment]
relevant ran enough tests to analyze, so on backend suite I only did a quick check.

no regressions found.

**Comment by tinatian** [comment]
@dantewang @W2jx Currently no message listener is registered to DestinationNames.HOT_DEPLOY, let's create a ticket and remove related code, and add breaking change.

After that, we won't need DestinationAwaitClassTestRule any more as it is only used by DestinationNames.HOT_DEPLOY.

Please resend.

Thanks.
Tina.

**Comment by dantewang** [comment]
Will do it in https://liferay.atlassian.net/browse/LPS-192680

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5194

**Pull request closed without merging**
