### PR TITLE
[Static reference] LPS-182671 Remove method reference by using snapshot in module portal-workflow-kaleo-forms-web, search-experiences-web

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:search

**Comment by W2jx** [comment]
ci:test:commerce

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by zhangyan0701** [comment]
ci:test:message-boards

**Comment by Kvale1733** [comment]
@W2jx No regressions.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
