### PR TITLE
LPS-184639, LPS-184641, LPS-190570 Add a new table to map each folder id with its propagation settings

### PR DESCRIPTION
**Pull request by ces-totrinh**
Hi @shuyangzhou,
According to Brian Chan's feedback, I updated the code, including column name changes and usage.
Also, the permission propagation entity is created to map each folder to its propagation settings. The propagation value is added when creating a folder (see 33a97586fac6cfe094951460c027f88503098e4c). This is why we add this to the core instead of a module.

Please help review this PR and give your feedback.

cc: @hhtank @locpham97 @ces-quanhuynh  @ces-luannguyen
Previous PR: https://github.com/brianchandotcom/liferay-portal/pull/141496

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by tototrinh** [comment]
Could we have some updates on this, please? Many Thanks.

**Comment by tototrinh** [comment]
ci:test:sf

**Comment by tototrinh** [comment]
I updated the PR to solve the conflict. Thanks.

**Comment by tototrinh** [comment]
ci:test:sf

**Comment by tototrinh** [comment]
Hi @shuyangzhou, I updated the code, please help take a look. Thanks

**Comment by tototrinh** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142550

**Pull request closed without merging**
