### PR TITLE
[Equinox] LPS-184766 Part 1 Create modules and make Equinox internal

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou @tinatian The main goal of this PR is to avoid exposing any Equinox API and keep Equinox usage internal in the -impl module. From next PR I'll start to inline Equinox code.

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@dantewang Looks like there are startup issues when starting up with Java 11:

```
16-Aug-2023 14:37:09.079 SEVERE [SystemExecutorServiceUtil-3] org.apache.catalina.core.ApplicationContext.log javax.servlet.descriptor.JspConfigDescriptor referenced from a method is not visible from class loader
	java.lang.IllegalArgumentException: javax.servlet.descriptor.JspConfigDescriptor referenced from a method is not visible from class loader
		at java.base/java.lang.reflect.Proxy$ProxyBuilder.ensureVisible(Proxy.java:858)
		at java.base/java.lang.reflect.Proxy$ProxyBuilder.validateProxyInterfaces(Proxy.java:700)
		at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:627)
		at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:635)
		at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$0(Proxy.java:415)
		at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
		at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
```
```
2023-08-16 14:38:15.564 ERROR [SystemExecutorServiceUtil-16-com.liferay.portal.osgi.web.wab.extender.internal.WabFactory-BundleTrackerOpener][WabBundleProcessor:235] Catastrophic initialization failure! Shutting down null WAB due to: null
java.lang.NullPointerException: null
	at com.liferay.portal.osgi.web.wab.extender.internal.WabBundleProcessor._initContext(WabBundleProcessor.java:454) ~[?:?]
	at com.liferay.portal.osgi.web.wab.extender.internal.WabBundleProcessor.init(WabBundleProcessor.java:131) ~[?:?]
	at com.liferay.portal.osgi.web.wab.extender.internal.WebBundleDeployer._initWabBundle(WebBundleDeployer.java:129) ~[?:?]
	at com.liferay.portal.osgi.web.wab.extender.internal.WebBundleDeployer.doStart(WebBundleDeployer.java:61) ~[?:?]
	at com.liferay.portal.osgi.web.wab.extender.internal.WabFactory$WABExtension.start(WabFactory.java:104) ~[?:?]
	at com.liferay.portal.osgi.web.wab.extender.internal.WabFactory.addingBundle(WabFactory.java:57) ~[?:?]
	at com.liferay.portal.osgi.web.wab.extender.internal.WabFactory.addingBundle(WabFactory.java:40) ~[?:?]
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:475) ~[org.eclipse.osgi.jar:?]
```
Smoke test for jdk11 didn't run on CI, so I got this error locally.

**Comment by dantewang** [comment]
@catarineaguiar Thanks!

**Pull request closed without merging**
