### PR TITLE
LPS-198792 Remove Html interface and impl into Util in kernel

### PR DESCRIPTION
**Pull request by julschong**
usage in kernel, Util staying in kernel.
release repo does use this but since Util location is not change, release repo does not need update

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong Regression found in 

com.liferay.portal.kernel.util.HtmlUtilTest
```
    [junit] Testcase: com.liferay.portal.kernel.util.HtmlUtilTest:	Caused an ERROR
    [junit] com.liferay.portal.util.PropsImpl
    [junit] java.lang.ClassNotFoundException: com.liferay.portal.util.PropsImpl
    [junit] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
    [junit] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    [junit] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
    [junit] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    [junit] 	at com.liferay.portal.test.rule.InitializeKernelUtilTestRule._setUpPropsUtil(InitializeKernelUtilTestRule.java:164)
    [junit] 	at com.liferay.portal.test.rule.InitializeKernelUtilTestRule.beforeClass(InitializeKernelUtilTestRule.java:72)
    [junit] 	at com.liferay.portal.test.rule.InitializeKernelUtilTestRule.beforeClass(InitializeKernelUtilTestRule.java:31)
    [junit] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:45)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-38/test-portal-acceptance-pullrequest(master)/9275/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Comment by julschong** [comment]
pushed test fix, removed unit test rule

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142337

**Pull request closed without merging**
