### PR TITLE
LPS-184639, LPS-184641, LPS-190570 Add a new table to map each folder id with its propagation settings

### PR DESCRIPTION
**Pull request by ces-totrinh**
Hi team,
Please help review this PR and give your feedback.
cc: @hhtank @locpham97 @ces-quanhuynh @ces-luannguyen
Previous PR: https://github.com/liferay-lima/liferay-portal/pull/4651
# Motivation
[LPS-184639](https://liferay.atlassian.net/browse/LPS-184639) _Add a new table to map each folder id with its propagation settings_
[LPS-184641](https://liferay.atlassian.net/browse/LPS-184641) _Upgrade process_
[LPS-190570](https://liferay.atlassian.net/browse/LPS-190570) _Make it work with publications_
These tickets are subtasks of [LPS-154515](https://liferay.atlassian.net/browse/LPS-154515) _As a documents manager I want to set permissions from folders to folders at creation time_
Each folder will have a permissions propagation setting, and its value will affect how the permissions of newly created subfolders are determined
# Solution
- Create a new entity `PermissionPropagationEntry` to map each _folderId_ with its propagation settings that are defined in `portal-impl/src/com/liferay/portal/service.xml` with these columns - `companyId`, `groupId`, `classNameId`, `classPK`, and `propagation`. 
`classNameId` identifies the kind of thing (see ClassNameLocalService) and `classPK` would be its primkey (e.g. folderId, ...).

- Publication: Enable change-tracking-enabled to true for `PermissionPropagationEntry` and create two new classes to integrate Liferay Publication Framework - `PermissionPropagationCTDisplayRenderer` and `PermissionPropagationEntryTableReferenceDefinition`

Regards,

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:environments

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by tototrinh** [comment]
Hi @Kvale1733, I checked and found that the semantic versioning issue isn't related to our changes.
Thanks.

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by tototrinh** [comment]
ci:test:sf

**Comment by tototrinh** [comment]
ci:test:relevant

**Comment by tototrinh** [comment]
Hi team, might I ask if there are any updates on this yet?

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141015

**Pull request closed without merging**
