### PR TITLE
[Method References] LPS-160434 Replace method setPortlet with field _portlet in class extends BasePanelApp

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have replaced method setPortlet with field _portlet in this pr

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results when they finish ? Thanks!

**Comment by dantewang** [comment]
@W2jx You missed a subclass in `modules/apps/application-list/application-list-test` so there's a compile error, please fix.

**Comment by zhangyan0701** [comment]
**Some compile errors:**

1. 
 ```
[exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/portal-search-tuning/portal-search-tuning-rankings-web/src/test/java/com/liferay/portal/search/tuning/rankings/web/internal/application/list/ResultRankingsPanelAppTest.java:87: error: cannot find symbol
     [exec] 		_resultRankingsPanelApp.setPortlet(portlet);
     [exec] 		                       ^
     [exec]   symbol:   method setPortlet(Portlet)
     [exec]   location: variable _resultRankingsPanelApp of type ResultRankingsPanelApp
```
2.
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/portal-search-tuning/portal-search-tuning-synonyms-web/src/test/java/com/liferay/portal/search/tuning/synonyms/web/internal/application/list/SynonymsPanelAppTest.java:78: error: cannot find symbol
     [exec] 		_synonymsPanelApp.setPortlet(portlet);
     [exec] 		                 ^
     [exec]   symbol:   method setPortlet(Portlet)
     [exec]   location: variable _synonymsPanelApp of type SynonymsPanelApp
```
Full console:
https://testray.liferay.com/reports/production/logs/2022-08/test-1-27/test-portal-acceptance-pullrequest(master)/4508/modules-unit-jdk8/0/2/jenkins-console.txt.gz?authuser=0

3.
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/application-list/application-list-test/src/testIntegration/java/com/liferay/application/list/my/account/permissions/test/PanelAppMyAccountPermissionsTest.java:196: error: PanelAppMyAccountPermissionsTest.TestPanelApp is not abstract and does not override abstract method getPortlet() in PanelApp
     [exec] 	private class TestPanelApp extends BasePanelApp {
     [exec] 	        ^
```
Full console;
https://testray.liferay.com/reports/production/logs/2022-08/test-1-27/test-portal-acceptance-pullrequest(master)/4508/modules-integration-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0

4.
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/archived/portal-security-wedeploy-auth-web/src/main/java/com/liferay/portal/security/wedeploy/auth/web/internal/application/list/WeDeployAuthAdminPanel.java:37: error: WeDeployAuthAdminPanel is not abstract and does not override abstract method getPortlet() in PanelApp
     [exec] public class WeDeployAuthAdminPanel extends BasePanelApp {
     [exec]        ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/archived/portal-security-wedeploy-auth-web/src/main/java/com/liferay/portal/security/wedeploy/auth/web/internal/application/list/WeDeployAuthAdminPanel.java:44: error: method does not override or implement a method from a supertype
     [exec] 	@Override
     [exec] 	^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/archived/portal-security-wedeploy-auth-web/src/main/java/com/liferay/portal/security/wedeploy/auth/web/internal/application/list/WeDeployAuthAdminPanel.java:50: error: cannot find symbol
     [exec] 		super.setPortlet(portlet);
     [exec] 		     ^
     [exec]   symbol: method setPortlet(Portlet)
     [exec] 3 errors
```
Full console:
https://testray.liferay.com/reports/production/logs/2022-08/test-1-27/test-portal-acceptance-pullrequest(master)/4508/modules-compile-jdk8/0/1/jenkins-console.txt.gz?authuser=0

**semantic versioning error:**
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/application-list/application-list-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.application.list                       MAJOR      2.1.0      2.1.0      3.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.application.list.BaseJSPPanelApp
     [exec]     		>   method     getPortlet()
     [exec]     			+   access     abstract
     [exec]     		-   method     setPortlet(com.liferay.portal.kernel.model.Portlet)
     [exec]     			-   return     void
     [exec]     	>   class      com.liferay.application.list.BasePanelApp
     [exec]     		>   method     getPortlet()
     [exec]     			+   access     abstract
     [exec]     		-   method     setPortlet(com.liferay.portal.kernel.model.Portlet)
     [exec]     			-   return     void
     [exec]     	+   class      com.liferay.application.list.BasePortletPanelApp
```
Full console:
https://testray.liferay.com/reports/production/logs/2022-08/test-1-27/test-portal-acceptance-pullrequest(master)/4508/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by tinatian** [comment]
@W2jx Please run test first in your local repo if you are not sure this is good enough.

Tina.

**Pull request closed without merging**
