### PR TITLE
Revert "LPS-168633 Remove "immediate = true" from module portal-compo…

### PR DESCRIPTION
**Pull request by slnn**
Revert since it caused regression

### CODE REVIEW

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian This commit causes a regression, forwarding the revert.

**Comment by dantewang** [comment]
Hi QA, the build is aborted in 2 relevant runs, is there a real failure?

**Comment by Kvale1733** [comment]
@dantewang No doesn't look like a real failure

**Comment by vicnate5** [comment]
@Kvale1733 Please confirm this resolves the issue and then manually forward

**Comment by Kvale1733** [comment]
See: https://github.com/brianchandotcom/liferay-portal/pull/127320

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
