### PR TITLE
[Remove Blocking usages]LPS-188272 portal-kernel | PasswordEncryptorUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(6/23 14.49)

**Comment by W2jx** [comment]
no conflicts(6/26 15:25)

**Comment by W2jx** [comment]
no conflicts(6/27 8:52)

**Comment by W2jx** [comment]
no conflicts(7/4 14:30)

**Comment by W2jx** [comment]
no conflicts(7/5 13:57)

**Pull request closed without merging**
