### PR TITLE
[Optional Reference] LPS-185553 Convert the Optional Dynamic Greedy references to static references using Snapshot in class ContentDashboardFileExtensionItemSelectorView

### PR DESCRIPTION
**Pull request by haydenzheng314**
Ticket: https://issues.liferay.com/browse/LPS-185553
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by LisztLiszt** [comment]
ci:help

**Comment by LisztLiszt** [comment]
ci:stop

**Comment by LisztLiszt** [comment]
ci:stop:stable

**Comment by LisztLiszt** [comment]
ci:reopen

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:sf

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
