### PR TITLE
LPS-185030

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, @tinatian.

I create a new ticket to resolve the test error from https://github.com/liferay-core-infra/liferay-portal/pull/4540#issuecomment-1553572937. I think we should add `PortalInstances.initCompany() `logic to `CompanyLocalServiceImpl#addCompany()`, this will keep consistent with `CompanyLocalServiceImpl#deleteCompany()` because `CompanyLocalServiceImpl#deleteCompany()` invokes `PortalInstances.removeCompany() logic`. By using the fix, we can make sure webId is put to PortalInstances#_webIds field even though only invoking `CompanyLocalServiceImpl#addCompany()`

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by yuhai** [comment]
> @yuhai Did you do [a5ee8ad](https://github.com/liferay-core-infra/liferay-portal/commit/a5ee8ad5f069d1a5f1be1299a60014d19dfd324b) because you saw any error?

@dantewang, yes. `CompanyLocalServiceTest#testDeleteCompanyDeletesDefaultPasswordPolicy() `didn't be passed. 

```
	public void testDeleteCompanyDeletesDefaultPasswordPolicy()
		throws Exception {

		Company company = _addCompany();

		_deleteCompany(company);

		_passwordPolicyLocalService.getDefaultPasswordPolicy(
			company.getCompanyId());
	}
```

Due to the issue, CompanyThreadLocal.getCompanyId() returned just deleted companyId after `_deleteCompany(company) `when executed `_passwordPolicyLocalService.getDefaultPasswordPolicy()`. The issue was exposed when the [previous pr executed ci test](https://github.com/liferay-core-infra/liferay-portal/pull/4540#issuecomment-1553572937).

**Comment by dantewang** [comment]
@yuhai Please change the commit message, making it clear that it fixes a test error, and explain the cause as short as possible.

**Comment by yuhai** [comment]
@tinatian, @dantewang, it is not related with the webId support for now.

**Pull request closed without merging**
