### PR TITLE
LPD-15969 Revert removal of "final" modifiers from class fields 

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__ <https://liferay.atlassian.net/browse/LPD-15969>

This undoes all "unfinal" changes done for the JDK 21 runtime support.

### CODE REVIEW

**Comment by kevhlee** [comment]
@tinatian, I have manually tested all the impacted tests on JDK 21 and most of them ran successfully. There were two tests that threw errors but they seem unrelated. I also tested with and without my changes for the ones that produced errors:

__com.liferay.counter.test.CounterLocalServiceTest__:

```java
com.liferay.counter.test.CounterLocalServiceTest > testConcurrentIncrement FAILED
    java.util.concurrent.ExecutionException: com.liferay.petra.process.ProcessException: java.lang.RuntimeException: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'liferayDataSource' available
```

__com.liferay.segments.odata.retriever.test.UserODataRetrieverTest__:

```java
org.osgi.framework.BundleException: Error occurred installing a bundle.
        at org.eclipse.osgi.storage.Storage.install(Storage.java:688)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.installBundle(BundleContextImpl.java:146)
        at com.liferay.arquillian.extension.junit.bridge.connector.FrameworkCommand.lambda$installBundle$51953164$1(FrameworkCommand.java:25)
        at com.liferay.arquillian.extension.junit.bridge.connector.ArquillianConnectorThread.run(ArquillianConnectorThread.java:73)

        Caused by:
        java.util.zip.ZipException: Exception in opening zip file: /home/Repos/liferay/bundles/LPD-15969-jdk21/osgi/state/org.eclipse.osgi/1547/0/bundleFile
```

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/146834

**Comment by tinatian** [comment]
@kevhlee Missing one, resent at https://github.com/brianchandotcom/liferay-portal/pull/146843

**Pull request closed without merging**
