### PR TITLE
[Remove Stream/Optional usage] LPS-174907 Remove usages of Stream for module: portal-workflow-kaleo-test

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(2/8 8:58)

**Comment by W2jx** [comment]
no conflicts(2/9 10:25)

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3519

**Pull request closed without merging**
