### PR TITLE
[Components with more than 1 service] LPS-189642 Refactor components from portal-workflow module

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:workflow

**Comment by zhangyan0701** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
@dantewang No regressions found.

**Comment by dantewang** [comment]
ci:forward:force


cc @tinatian

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
