### PR TITLE
[Remove Blocking Usages] LPS-188582  AutoBatchPreparedStatementUtil |portal-kernel

### PR DESCRIPTION
**Pull request by JanisZhang**
https://liferay.atlassian.net/browse/LPS-188582

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
Thanks Cat. @catarineaguiar

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
Run an additional ci-test-upgrade test, as the changed class is only used there.

**Comment by dantewang** [comment]
@zhangyan0701 It seems the last ci-test-upgrade run didn't generate a report... Is it possible to still review the result?

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
