### PR TITLE
LPS-183594 move portal-upload to modules part 3

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Shuyang,

Resent: https://github.com/liferay-core-infra/liferay-portal/pull/5656
In this PR, I am trying to move all the portal-upload usage from portal-impl to modules.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:object

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @Kvale1733 ,

I am not sure if the test successfully genereate the report or not. Could you please help me review it once the test is ready?
Thanks!

**Comment by Kvale1733** [comment]
@jeffwu0724 Looks like it didn't generate correctly. I will ask CI to generate it again.

**Comment by jeffwu0724** [comment]
Thanks @Kvale1733 !

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by jeffwu0724** [comment]
fixed the code conflicti in `portal-kernel/src/com/liferay/portal/kernel/security/permission/packageinfo,`  the previous test result should be good enough

**Pull request closed without merging**
