### PR TITLE
LPD-18462 sync versions.html and versions-complete.xml as they are not updated in master

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This is for ticket https://liferay.atlassian.net/browse/LPD-18462.
As there are lots of unupdated jar info in versions.html and versions-complete.xml, I do this sync to make sure everything is up to date
Thanks for checking

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:report:2542112371

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
ci:forward:force

**Comment by jeffwu0724** [comment]
manuall sent to BChan: https://github.com/brianchandotcom/liferay-portal/pull/147565 as `ci forward force` is not working
Gonna close this PR now.

**Comment by jeffwu0724** [comment]
ci:close

**Pull request closed without merging**
