### PR TITLE
LPS-196101 Merge PortletPermission interface and impl into Util in kernel

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found. SF issue is not related

**Comment by julschong** [comment]
rename varaible back to original in TemplateContextHelper

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
rebased

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
@shuyangzhou not moving this one

Following build.gradles do not contain portal-impl dependencies: 
        ./modules/apps/on-demand-admin/on-demand-admin-web/build.gradle
        ./modules/apps/mentions/mentions-web/build.gradle
        ./modules/apps/mentions/mentions-service/build.gradle
        ./modules/apps/layout/layout-type-controller/layout-type-controller-control-panel/build.gradle
        ./modules/apps/commerce/commerce-product-options-web/build.gradle
        ./modules/apps/commerce/commerce-pricing-web/build.gradle

Used in portal-kernel

**Comment by julschong** [comment]
closed per our discussion

**Pull request closed without merging**
