### PR TITLE
[Remove Stream/Optional usage] LPS-174291 Remove_usages_of_Stream_usages_for_portal_store_gcs

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

Resend: https://github.com/liferay-core-infra/liferay-portal/pull/3242
As discussed, used forEach() without the Spliterator
This is for ticket https://issues.liferay.com/browse/LPS-174291.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:dl-store

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130837

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130838

**Pull request closed without merging**
