### PR TITLE
[Method References] LPS-161155 Remove method setServletContext in classes extend BaseJSPSettingsConfigurationAction

### PR DESCRIPTION
**Pull request by W2jx**
Resend, only do semver, and the CI test has been passed in the original [PR](https://github.com/liferay-core-infra/liferay-portal/pull/4007) 

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4007

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:security:norebase

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
only do semver, no need to rerun test

**Comment by W2jx** [comment]
no conflicts(4/10 8:33)

**Comment by W2jx** [comment]
no conflicts(4/11 9:50)

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133162

**Pull request closed without merging**
