### PR TITLE
[TECHNICAL-SUPPORT] LPS-171968 Error popup shows when loading a page with an image for which the user does not have view permission

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by dantewang** [comment]
@IstvanD The LPP ticket says it started to happen after the customer upgraded from U36 to U46, so it sounds like a regression bug. Do you know which change causes this issue?

If not, @zhangyan0701 could you try to find the cause?

**Comment by zhangyan0701** [comment]
@dantewang I tested the issue locally, and I could even reproduce on U36. But looks like the customer didn't see it on U36.

From my testing, the issue started to happen between U30 and U31. The [root cause range](https://github.com/liferay/liferay-portal/compare/93372588d949db0daf3bc9a60e86d46f59197d16...480a69da477632c008df9df3b662ad566a1ea68c) is too huge and there is no test to cover it, so it's gonna take a longer time to find the cause.

**Comment by dantewang** [comment]
@zhangyan0701 Thank you!

**Comment by IstvanD** [comment]
Hi @dantewang, @zhangyan0701 I could not yet find the root cause of the regression, but I suspect that it is frontend related. It is the same that causes [LPS-164298](https://issues.liferay.com/browse/LPS-164298).

**Comment by tinatian** [comment]
@IstvanD 
Could you please check with echo team about how to fix this issue as it is caused by https://issues.liferay.com/browse/LPS-156404 based on Summer's comment.

I do not like the current fix as it filtered out an exception without a reasonable reason, if you still want to go with this solution, at least you need to provide a fully integration test to show why you made this change. The reason should not be related to the specific case you are fixing, but from API point of view, why you need to filter out a specific exception as the method you modified is going to be invoke by a lot of other cases.

I am going to close this pull, please reopen if needed.

Thanks.
Tina.

**Pull request closed without merging**
