### PR TITLE
LPD-20503 patched spring-web 4.3.30 to exclude UriComponentsBuilder for 7.2.x

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

As discussed, this is the patch for 7.2.x only, and I exclude all the UriComponentsBuilder related class in this patch. 
I have run a quick test in 7.2.x, and it passed the ci test. Please see https://github.com/jeffwu0724/liferay-portal-ee/pull/216#issuecomment-2045552265.

Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:report:2559623118

**Comment by jeffwu0724** [comment]
After analyzing the [failing test in 7.2.x](https://github.com/jeffwu0724/liferay-portal-ee/pull/216#issuecomment-2048019229), they are either failing in lots of other PRs, or passed the test locally. 

For the SF failure: sent a request here and asking SF team to fix https://liferay.slack.com/archives/C1SJ64S9X/p1712781989640569?thread_ts=1712781981.176559&cid=C1SJ64S9X
As the relevant test in this PR is passing, I would consider this 4.3.30 patch is safe for 7.2.x

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/149183

**Pull request closed without merging**
