### PR TITLE
[Disable auto-import-default-references]LPS-164192

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to disable auto-import-default-references in `portal-workflow-kaleo-forms-service`. Thanks!
https://issues.liferay.com/browse/LPS-164192

### CODE REVIEW

**Comment by zhangyan0701** [comment]
Test failure [LocalFile.WorkflowMetrics#ViewReports](https://testray.liferay.com/home/-/testray/case_results/1992558676) seems related:

Steps:
1. Enable Single Approval for Blogs.
2. Create two Blog entries.
3. Go to Application menu > Workflow > Metrics.
4. Single Approval didn't display.
before0

**Comment by JanisZhang** [comment]
Hi @zhangyan0701,

I just generated the bundles with this PR and followed the above steps.  It seems Single Approval for the blog entries works well on my side.

That's weird if the failures are related as I didn't change any logic, etc.  I just imported the needed reference.   

Could you please help to double-check it?  Thanks.          cc/ @dantewang 

image

**Comment by JanisZhang** [comment]
Hi @zhangyan0701,

I just generated the bundles with this PR and followed the above steps.  It seems Single Approval for the blog entries works well on my side.

That's weird if the failures are related as I didn't change any logic, etc.  I just imported the needed reference.   

Could you please help to double-check it?  Thanks.          cc/ @dantewang 

image

**Comment by JanisZhang** [comment]
liferay/ci:test:relevant

**Comment by dantewang** [comment]
@zhangyan0701 Is there any portal error during the failed test?

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
@JanisZhang I saw the same problem locally when running the test yesterday. I will try to figure out more detailed manual steps.

@dantewang There is no portal error.

**Comment by dantewang** [comment]
@zhangyan0701 Seems CI passes this time. I'll wait for your double check, thanks!

**Comment by zhangyan0701** [comment]
The workflow test passed in the new test result, and I wasn't able to reproduce it today, looks like it was a falky even though it is a little weird, but I am going to add QA Passed label.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
