### PR TITLE
Lps 191404 4

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by GinsonRen** [comment]
@111Anna Please startup test on this pull. https://github.com/liferay-core-infra/liferay-portal/pull/5185#issuecomment-1664349581
/cc @tinatian

**Comment by 111Anna** [comment]
Hi @tinatian @GinsonRen, I ran this PR on CE and DXP, the test results are  normal.
/cc @shuyangzhou @dantewang 

Here are test results:

CE:

Portal Version |GitId | Average Startup (ms) | % | Average Shutdown (ms) | % | Open File |Thread Create |Open Prepared Statement |Open SQL|Open service tracker|Open bundle tracker
-- | -- | -- | -- | -- | -- | -- | -- | -- | --|--|--
Baseline | 8cd8a57f |18998.3 | - | 2592.3 | - | 1479 | 93 | 120 | 856|5528|32
Baseline + PR-5188 | - | 18965 | 0.18% | 2591 | 0.05% | 1479 | 93 |120 | 856|5527 |32


DXP:

Portal Version | GitId | Average Startup (ms) | % | Average Shutdown (ms) | % | Open File |Thread Create |Open Prepared Statement |Open SQL|Open service tracker|Open bundle tracker
-- | -- | -- | -- | -- | -- | -- | -- | -- | --|--|--
Baseline | 8cd8a57f |20260| - | 3065.3| - | 1603 | 93 | 126 | 933|5972|33
Baseline + PR-5188 | - | 20256.3 | 0.02% | 3101 |-1.2%  | 1603 |95 | 126 |934 |5972|33

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
