### PR TITLE
LPS-166837 Remove "immediate = true" from USM

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:usm

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by catarineaguiar** [comment]
@MrJohn1911 no regressions found.

**Comment by MrJohn1911** [comment]
@shuyangzhou Can you review this? thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125398

**Pull request closed without merging**
