### PR TITLE
LPS-156831 Use _portal.getPathContext() instead of ServletContextClassLoaderPool.getServletContextName(PortalClassLoaderUtil.getClassLoader()) to get the portal contextPath

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:environments

**Comment by rafaprax** [comment]
@catarineaguiar,  Can you help me to scan these test results? It's a fix for a release blocker.

Thx

**Comment by catarineaguiar** [comment]
@rafaprax the [regression](https://issues.liferay.com/browse/LPS-156831) was fixed and any other regressions were found.

**Comment by brianchandotcom** [comment]
@rafaprax thanks! merged to temp branch

**Comment by rafaprax** [comment]
Hey @shuyangzhou, this pr is ready for your review. Thx

**Comment by shuyangzhou** [comment]
This is in master already.

**Pull request closed without merging**
