### PR TITLE
LPS-150754 Spring 5.2.20

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou @tinatian @zhangyan0701

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Tina.

**Comment by vicnate5** [comment]
@tinatian The only unique failure here is in a Theme functional test that deploys some themes. `Task :apps:static:osgi:osgi-util:compileJava FAILED` while trying to deploy `frontend-css-cadmin-web`. However, I compiled this branch locally with a clean repo and cannot reproduce. This module deploys fine and I can run `gw :apps:static:osgi:osgi-util:compileJava` successfully.

Full log https://testray.liferay.com/reports/production/logs/2022-03/test-1-29/test-portal-acceptance-pullrequest(master)/2309/functional-tomcat90-mysql57-jdk8/7/8/jenkins-console.txt.gz?authuser=0

I think we can move this forward since I cannot reproduce, noting this in case this means anything to you or we see it again.

Otherwise, no regressions found.

**Comment by tinatian** [comment]
FYI @shuyangzhou

**Comment by vicnate5** [comment]
ci:test:jsf

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115606

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
