### PR TITLE
[TS] LPS-19090 Always check the portal session to ensure it hasn't been invalidated

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-19090

## Problem overview

The issue was re-discovered while investigating an issue in `SanitizedServletResponse` that only manifests in 7.3 and earlier, but that is no longer reproducible in 7.4. This is a Groovy script that reproduces the issue under investigation in 7.3.x and earlier.

```groovy
import com.liferay.portal.kernel.service.ServiceContextThreadLocal
import com.liferay.portal.kernel.servlet.SanitizedServletResponse

def serviceContext = ServiceContextThreadLocal.getServiceContext()

serviceContext.getRequest().getSession().invalidate()

SanitizedServletResponse.getSanitizedServletResponse(serviceContext.getRequest(), serviceContext.getResponse())
```

When running the above script in 7.3.x and earlier, we get a warning about invalidated sessions in Tomcat, and a stack trace in JBoss. Investigating the issue further reveals that the problematic code was removed in [LPS-134188](https://issues.liferay.com/browse/LPS-134188), where we removed the code that tries to call `getAttribute` on an invalidated session returned by `SharedSessionServletRequest`.

Since the backport requests for LPS-134188 were all closed as won't fix (due to changing a system default value without good reason), this ticket instead addresses the root cause: the invalidated session returned by `SharedSessionServletRequest`.

## Steps to reproduce the root cause

To replicate the root cause in master, run the following Groovy script in Server Administration and check the output in the application server console.

```groovy
import com.liferay.portal.kernel.service.ServiceContextThreadLocal
import com.liferay.portal.kernel.servlet.SanitizedServletResponse

def serviceContext = ServiceContextThreadLocal.getServiceContext()

System.out.println("session before invalidation: " + serviceContext.getRequest().getSession(false))

serviceContext.getRequest().getSession().invalidate()

System.out.println("session after invalidation: " + serviceContext.getRequest().getSession(false))
```

The expected behavior is that the session returned after invalidation is null, as described in [HttpSession.getSession(boolean)](https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getSession%28boolean%29). The actual behavior is that the already-invalidated session is returned.

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@holatuwol semver error:

```
     [exec] > Task :baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.servlet                         MINOR      10.0.0     10.0.0     10.1.0     VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.portal.servlet.SharedSessionServletRequest
     [exec] 		+   method     checkPortalSession(boolean)
     [exec] 			+   access     protected
     [exec] 			+   return     void
     [exec] [Baseline Warning] Bundle Version Change Recommended: 68.1.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-impl/portal-impl.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.impl/68.0.0/134b52e99c36f09d50efacea0bc4414e6a2a5402/com.liferay.portal.impl-68.0.0.jar
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-02/test-1-25/test-portal-acceptance-pullrequest(master)/6244/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
@holatuwol Please add test.

Thanks.
Tina.

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by tinatian** [comment]
FYI@holatuwol In core infra, we need to remove "QA Passed" flag to trigger a new round of test result scanning.

**Comment by Kvale1733** [comment]
@holatuwol No regressions found. Integration test passes.

**Comment by tinatian** [comment]
@holatuwol If you add "Assert.assertNotNull(sharedSessionServletRequest.getSession(true));" to your test, it will fail. Please see my fix at https://github.com/liferay-core-infra/liferay-portal/pull/3592.

Thanks.
Tina

**Pull request closed without merging**
