### PR TITLE
 [TS] LPS-201574 Rely on servlet request to provide the proper host name, to better support HTTP/2 (h2)

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team,

Previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/6120

**Cause of Test Failures in previous PR**
The cause of the test failures in the previous PR was due to the removal of our existing logic that added extra handling to strip square brackets from an IPv6 address.

**Changes since previous PR**
I have revised the fix to no longer remove our existing logic to handle IPv6 addresses, specifically this portion: [PortalImpl.java#L2369-L2385](https://github.com/liferay/liferay-portal/blob/7.4.3.104-ga104/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L2369-L2385)
```
if (host != null) {
	host = StringUtil.toLowerCase(host.trim());

	// See RFC-3986 (section 3.2.2).

	int pos = host.indexOf(']');

	if ((pos > 0) && host.startsWith("[")) {
		return host.substring(1, pos);
	}

	pos = host.indexOf(':');

	if (pos >= 0) {
		host = host.substring(0, pos);
	}
}
```

**Reasons**
- Since the issue we are trying to fix does not involve IPv6, this new proposed fix would be the minimal fix. 
- Also, retaining our original logic would reduce the chances of introducing a breaking change. 
  - Looking at the usages of this method, there are parts of Liferay, such as hostname for Virtual Host, that may break due to this change of no long stripping the square brackets.
    - Part of this is due to the usage of `Inet6Address`, which does not include the brackets.
- But, if we do decide we would like to to further evaluate our handling of IPv6 addresses, we can create a separate ticket to investigate this.

I will leave additional context of the fix below.

Please let me know if you have any questions.
Thanks!

/cc @dantewang 

---

Ticket: [LPS-201574](https://liferay.atlassian.net/browse/LPS-201574)

**Context**
Currently, calling `_portal.getHost` does not provide the proper **Host name**, when Tomcat is configured to use HTTP/2.

From my investigation, the current logic to only rely on the **Host header value** to retrieve the **Host name**, was added a long time ago. 

The proposed fix would be to instead rely on the servlet request to provide the proper host name (see commit message for additional details).

**Additional Thoughts**
If we proceed with this solution, maybe we should also test on all our other supported Application Servers.

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
no regressions failed

**Comment by tinatian** [comment]
ci:test:environments

**Comment by tinatian** [comment]
@vicnate5 I triggered environment test based on @ericyanLr 's comment, could you please trigger more tests if it is not enough

> If we proceed with this solution, maybe we should also test on all our other supported Application Servers.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@zhangyan0701 Can you review this since you [manually tested previously](https://github.com/liferay-core-infra/liferay-portal/pull/6120#issuecomment-1824331279)?

**Comment by zhangyan0701** [comment]
No regressions found.

Manual testing following the steps in https://liferay.atlassian.net/browse/LPS-201574 passed on Tomcat/Jboss/Weblogic.

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
