### PR TITLE
[Replace Non-Blocking Usage] LPS-199955

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace non-blocking ServiceProxyFactory usages in class `LayoutSEOLinkManagerUtil`, `MinifierUtil`, `FinderCacheUtil`, and  `EntityCacheUtil`. Thanks.
https://liferay.atlassian.net/browse/LPS-199955

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by lilylcl** [comment]
ci:test:stable

**Comment by lilylcl** [comment]
ci:test:relevant

**Comment by lilylcl** [comment]
ci:test:startup

**Comment by lilylcl** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
@JanisZhang regression found:

```
    [junit] Testcase: testDeleteRightPrimaryKeyTableMappings(com.liferay.portal.kernel.internal.service.persistence.TableMapperTest):	Caused an ERROR
    [junit] null
    [junit] java.lang.NullPointerException
    [junit] 	at com.liferay.portal.kernel.dao.orm.FinderCacheUtil.clearDSLQueryCache(FinderCacheUtil.java:31)
    [junit] 	at com.liferay.portal.kernel.internal.service.persistence.TableMapperImpl.deleteRightPrimaryKeyTableMappings(TableMapperImpl.java:206)
    [junit] 	at com.liferay.portal.kernel.internal.service.persistence.TableMapperTest.testDeleteRightPrimaryKeyTableMappings(TableMapperTest.java:653)
    [junit] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    [junit] 	at com.liferay.portal.kernel.test.rule.CodeCoverageAssertor$1.evaluate(CodeCoverageAssertor.java:72)
    [junit] 
    [junit] 
    [junit] Testcase: testDeleteLeftPrimaryKeyTableMappings(com.liferay.portal.kernel.internal.service.persistence.TableMapperTest):	Caused an ERROR
    [junit] null
    [junit] java.lang.NullPointerException
    [junit] 	at com.liferay.portal.kernel.dao.orm.FinderCacheUtil.clearDSLQueryCache(FinderCacheUtil.java:31)
    [junit] 	at com.liferay.portal.kernel.internal.service.persistence.TableMapperImpl.deleteLeftPrimaryKeyTableMappings(TableMapperImpl.java:192)
    [junit] 	at com.liferay.portal.kernel.internal.service.persistence.TableMapperTest.testDeleteLeftPrimaryKeyTableMappings(TableMapperTest.java:488)
    [junit] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    [junit] 	at com.liferay.portal.kernel.test.rule.CodeCoverageAssertor$1.evaluate(CodeCoverageAssertor.java:72)
    [junit] 
    [junit] 
    [junit] Testcase: testDeleteTableMapping(com.liferay.portal.kernel.internal.service.persistence.TableMapperTest):	Caused an ERROR
    [junit] null
    [junit] java.lang.NullPointerException
    [junit] 	at com.liferay.portal.kernel.dao.orm.FinderCacheUtil.clearDSLQueryCache(FinderCacheUtil.java:31)
    [junit] 	at com.liferay.portal.kernel.internal.service.persistence.TableMapperImpl.deleteTableMapping(TableMapperImpl.java:223)
    [junit] 	at com.liferay.portal.kernel.internal.service.persistence.TableMapperTest.testDeleteTableMapping(TableMapperTest.java:823)
    [junit] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    [junit] 	at com.liferay.portal.kernel.test.rule.CodeCoverageAssertor$1.evaluate(CodeCoverageAssertor.java:72)
    [junit] 
    [junit] 
    [junit] Testcase: testAddTableMapping(com.liferay.portal.kernel.internal.service.persistence.TableMapperTest):	Caused an ERROR
    [junit] null
    [junit] java.lang.NullPointerException
    [junit] 	at com.liferay.portal.kernel.dao.orm.FinderCacheUtil.clearDSLQueryCache(FinderCacheUtil.java:31)
    [junit] 	at com.liferay.portal.kernel.internal.service.persistence.TableMapperImpl.addTableMapping(TableMapperImpl.java:110)
    [junit] 	at com.liferay.portal.kernel.internal.service.persistence.TableMapperTest.testAddTableMapping(TableMapperTest.java:146)
    [junit] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    [junit] 	at com.liferay.portal.kernel.test.rule.CodeCoverageAssertor$1.evaluate(CodeCoverageAssertor.java:72)
    [junit] 
    [junit] 
    [junit] Testcase: testDeleteTableMappings(com.liferay.portal.kernel.internal.service.persistence.TableMapperTest):	Caused an ERROR
    [junit] null
    [junit] java.lang.NullPointerException
    [junit] 	at com.liferay.portal.kernel.dao.orm.FinderCacheUtil.clearDSLQueryCache(FinderCacheUtil.java:31)
    [junit] 	at com.liferay.portal.kernel.internal.service.persistence.TableMapperImpl.addTableMapping(TableMapperImpl.java:110)
    [junit] 	at com.liferay.portal.kernel.internal.service.persistence.TableMapperTest.testDeleteTableMappings(TableMapperTest.java:962)
    [junit] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    [junit] 	at com.liferay.portal.kernel.test.rule.CodeCoverageAssertor$1.evaluate(CodeCoverageAssertor.java:72)
    [junit] 
    [junit] 
    [junit] Testcase: testAddTableMappings(com.liferay.portal.kernel.internal.service.persistence.TableMapperTest):	Caused an ERROR
    [junit] null
    [junit] java.lang.NullPointerException
    [junit] 	at com.liferay.portal.kernel.dao.orm.FinderCacheUtil.clearDSLQueryCache(FinderCacheUtil.java:31)
    [junit] 	at com.liferay.portal.kernel.internal.service.persistence.TableMapperImpl.addTableMappings(TableMapperImpl.java:141)
    [junit] 	at com.liferay.portal.kernel.internal.service.persistence.TableMapperTest.testAddTableMappings(TableMapperTest.java:273)
    [junit] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    [junit] 	at com.liferay.portal.kernel.test.rule.CodeCoverageAssertor$1.evaluate(CodeCoverageAssertor.java:72)
    [junit] 
    [junit] 
    [junit] Testcase: com.liferay.portal.kernel.internal.service.persistence.TableMapperTest:	FAILED
    [junit] com.liferay.portal.kernel.internal.service.persistence.TableMapperImpl is not fully covered
    [junit] junit.framework.AssertionFailedError: com.liferay.portal.kernel.internal.service.persistence.TableMapperImpl is not fully covered
    [junit] 	at com.liferay.whip.agent.InstrumentationAgent._assertClassDataCoverage(InstrumentationAgent.java:343)
    [junit] 	at com.liferay.whip.agent.InstrumentationAgent.assertCoverage(InstrumentationAgent.java:66)
    [junit] 	at com.liferay.portal.kernel.test.rule.CodeCoverageAssertor.afterClass(CodeCoverageAssertor.java:110)
    [junit] 	at com.liferay.portal.kernel.test.rule.CodeCoverageAssertor$1.evaluate(CodeCoverageAssertor.java:75)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-40/test-portal-acceptance-pullrequest(master)/6898/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
