### PR TITLE
[TS] LPD-29412

### PR DESCRIPTION
**Pull request by kevhlee**
<https://liferay.atlassian.net/browse/LPD-29412>

Previous pull request: <https://github.com/liferay-core-infra/liferay-portal/pull/7188>.

@tinatian, as discussed previously, I made the changes we discussed. Let me know if there was something I missed.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:report:30008838

**Comment by kevhlee** [comment]
Test failures are unrelated. All of them either passed locally on my machine or were flaky.

**Comment by tinatian** [comment]
@JerryAdrianoo Please help me verify startup performance

**Comment by tinatian** [comment]
@victorhcunha Please help me verify login test

**Comment by tinatian** [comment]
FYI @slnn

**Comment by JerryAdrianoo** [comment]
Hey @tinatian  for more details from this test, see: [spreadsheet](https://docs.google.com/spreadsheets/d/1l0PkRKyZiGVeByLyuawDB8AYaIvflbfCitsWsUO-cQU/edit?gid=1036350692#gid=1036350692) 

Branch| Startup Time (ms)(without  default HSQL data)  Cold start | Percent of Average Startup Time Cold Start | Startup Time (ms)(without  default HSQL data) Hot start | Average Startup Time (ms)(without default HSQL data)  Hot start | Percent of Average Startup Time Hot Start | Shutdown Time (ms)(without default HSQL data)   Cold start | Shutdown Time (ms)(without default HSQL data)  Hot start | Average Shutdown Time (ms)(without default HSQL data)  Hot start
-- | -- | -- | -- | -- | -- | -- | -- | --
Before LPD-29412 | **42,920** | | 16,846 | | | **2,532** | 1,960
|  | | | 16,005 | | | | 1,970
|  | | | 16,324 | | | | 1,962
 | | | | 16,292 | | | | 1,989
 | | | | 16,149 |**16,255** | | | 1,947 | **1,960**
-- | -- | -- | -- | -- | -- | -- | --
After LPD-29412 | **42,062** | | 16,674 | | | **2,472** | 1,948
|  | | | 16,725 | | | | 1,887
|  | | | 16,434 | | | | 1,975
|  | | | 16,063 | | | | 2,033
| | |  -2.00% | 16,053 |**16,390** |  **0.83**% | | 1,964 | **1,962**

Everything looks ok, I didn't see any regression with these changes.
Please let me know if you need something else.

**Comment by victorhcunha** [comment]
Hi @tinatian !
Here are the results for login test case:
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
Master Baseline | f87fa5d | 10397 | - | 285 | 3,4,2 | 94,93,94
PR | - | 10723 | 3.135519861 | 276 | 2,2,2 | 93,92,94

From the results, no regression was detected. More details you can see in this [spreadsheet](https://docs.google.com/spreadsheets/d/1JqJn5vxyGRHejAWejEVAtSDpVdbemYdqCDQGLBLzpGg/edit?gid=0#gid=0) 
 Do you want the other test cases to run?

**Comment by tinatian** [comment]
@victorhcunha The result does not make sense to me, this change actually removed a cache, I did not expect it improves the performance, please recheck if you did anything wrong.

**Comment by victorhcunha** [comment]
Hi @tinatian ! The result does not actually necessarily show an improvement in performance. The difference in the values ​​is in our expected variation, as you can see in our [Stability Tests for Login testcase](https://docs.google.com/spreadsheets/d/15ctM1hv9Jedxnmpncrb0hl_i0x5GJ2_kPnNYzCX0hp0/edit?gid=0#gid=0) (the test variance ended up reaching 3.8% even though the test was run on the same hash baseline). 

Here are new results with an updated baseline:

Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
Master Baseline | 39a2324 | 10477 | - | 273 | 3,2,3 | 94,93,93
PR | - | 10700 | 2.128471891 | 280 | 3,3,4 | 92,91,94

We can see once again the test in PR having a result with higher session count but this time with a smaller difference.


To focus on the time value, I repeated the test in a new round, this time disabling the auto adjust and leaving a fixed value for the session count. We see that in the PR for a similar session count value an average time of almost 2.5% longer. Here are the results:

Portal Version | Git Id | Fixed Session Count | Mean Time of Login | Mean Time Change (%) | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
Master Baseline | 39a2324 | 4500 | 36.6 | - | 2,2,2 | 36,35,33
PR | - | 4500 | 37.5 | 2.459016393 | 2,2,2 | 34,34,35

More details you can see in our [spreadsheet](https://docs.google.com/spreadsheets/d/1JqJn5vxyGRHejAWejEVAtSDpVdbemYdqCDQGLBLzpGg/edit?gid=0#gid=0). 
If you wish, I can do another series of rounds to obtain the mean and standard deviation of the results.

cc: @tinatian

**Comment by slnn** [comment]
Hi @victorhcunha 

Your test results show an improvement in the DB CPU usage of Login, the pr decreased the DB CPU usage,  the db usage of Login should be stable, could you check your daily monitor test results to see if the db CPU usage is stable ?

> Hi @tinatian ! Here are the results for login test case:
> 
> Portal Version	Git Id	Session Count	Session Count Change (%)	Mean Time of Login	DB CPU Usage (%)	Portal CPU Usage (%)
> Master Baseline	[f87fa5d](https://github.com/liferay-core-infra/liferay-portal/commit/f87fa5dd559e0c59e48bd53e9f6f0209e7c6e043)	10397	-	285	3,4,2	94,93,94
> PR	-	10723	3.135519861	276	2,2,2	93,92,94
> From the results, no regression was detected. More details you can see in this [spreadsheet](https://docs.google.com/spreadsheets/d/1JqJn5vxyGRHejAWejEVAtSDpVdbemYdqCDQGLBLzpGg/edit?gid=0#gid=0) Do you want the other test cases to run?

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7225

**Comment by tinatian** [comment]
@kevhlee After a second thought, I would like to fix this issue in a deep layer LanguageResources as similar issue may happen in other usages invoking LanguageResources.getResourceBundle besides PortletConfigImpl.

This is caused by https://liferay.atlassian.net/browse/LPS-186188, I need your help to verify again if my pull https://github.com/liferay-core-infra/liferay-portal/pull/7225 cause any regression.

Thanks.
Tina

**Comment by victorhcunha** [comment]
Hi @slnn !
In recent daily monitoring, DB usage has typically been between 2-3%, in some samples it has been as high as 4%, but never higher. The baseline used in this test comes from daily monitoring.

**Pull request closed without merging**
