### PR TITLE
LPS-171228 move joda-time to shared-dependencies

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

In this PR, I am trying to move joda-time and joda-convert to shared-dependencies.
Thanks for checking!

### CODE REVIEW

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by jeffwu0724** [comment]
fixed the code conflicts in versions-complete.xml and versions.html by auto generate, the previous test result should be still good

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@jeffwu0724 can you rebase and re-run the tests, please? 

Thanks,
Cat

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@jeffwu0724 rebase, please.

no regressions found.

**Comment by jeffwu0724** [comment]
rebase and fixed the code conflict in versions.html by auto-generate, the previous test result should be good enough

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128311

**Pull request closed without merging**
