### PR TITLE
[Static reference] LPS-181674 Remove method reference by using snapshot in modules expando-taglib, export-import-changeset-taglib, flags-taglib, fragment-taglib

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by Kvale1733** [comment]
ci:test:export-import

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:export-import

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by W2jx** [comment]
no conflicts(4/17 8:08)

**Comment by W2jx** [comment]
no conflicts(4/18 9:28)

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@W2jx Regresssion found. "Filter ended abruptly: (osgi.web.symbolicname=com.liferay.flags.taglib" error

Steps to reproduce:
1. Go to Content and Data > Message Boards
2. Add a new Thread

Expected Results: Can add message board thread without issue
Actual Results: The following error appears in the console

```
[beanshell] 2023-04-14 22:20:18.142 ERROR [http-nio-8080-exec-3][IncludeTag:128] Current URL /web/site-name/test-page/-/blogs/blogs-entry-title?_com_liferay_blogs_web_portlet_BlogsPortlet_redirect=http%3A%2F%2Ftest-1-34-46.lax.liferay.com%3A8080%2Fweb%2Fsite-name%2Ftest-page%3Fp_p_id%3Dcom_liferay_blogs_web_portlet_BlogsPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview generates exception: org.osgi.framework.InvalidSyntaxException: Filter ended abruptly: (osgi.web.symbolicname=com.liferay.flags.taglib
[beanshell] java.lang.ArrayIndexOutOfBoundsException: 47
```

Can also be reproduced with these steps. Probably the same issue but a slightly different error is shown.

Steps to reproduce
1. Add a widget page
2. Add an Asset Publisher to the Page
3. Go to the Asset Publisher Configuration (Click on top right ellipses > configuration)
4. Scroll down and enables Flags
5. Click save

Expected Results: Can enable flags for the Asset Publisher without error
Actual Results: The following error appears in the console
```
[exec] 2023-04-14 21:50:36.826 ERROR [http-nio-8080-exec-3][view_asset_entries_abstract_jsp:1268] Filter ended abruptly: (osgi.web.symbolicname=com.liferay.flags.taglib
     [exec]     LIFERAY_ERROR: Filter ended abruptly: (osgi.web.symbolicname=com.liferay.flags.taglib
     [exec] 2023-04-14 21:50:37.572 ERROR [http-nio-8080-exec-10][view_asset_entries_abstract_jsp:1268] Filter ended abruptly: (osgi.web.symbolicname=com.liferay.flags.taglib
```

**Pull request closed without merging**
