### PR TITLE
LPS-145769

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian, @shuyangzhou ,

I have removed unused properties "browser.compatibility.ie.versions", and updated to propskeys.java, propsvalues.java and verifyproperties.java.
"BROWSER_COMPATIBILITY_IE_VERSIONS" was added in commit 920f4526da7db6845b3d5f18d3c3abc577883ffd, see LPS-32757, and it was used in "top_meta.jspf". 
Its usage was deleted based on commit 21b3463e0d51f65cd7c9fe9aef5869db7a9dd7aa, see LPS-121725
Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.
@jeffwu0724 Code looks good to me, wait for QA to scan test results.

Tina.

**Comment by vicnate5** [comment]
@jeffwu0724 Semver failure is real https://testray.liferay.com/reports/production/logs/2022-01/test-1-26/test-portal-acceptance-pullrequest(master)/1446/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz

No regressions found.

**Pull request closed without merging**
