### PR TITLE
[Remove Stream/Optional usages on methods return value for module: adaptive-media/adaptive-media-api]Lps 172854

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-172854

This one aims to remove the Stream/Optional usages on the interface AMRequestHandler which is under adaptive-media/adaptive-media-api.

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@slnn regression found:

```
     [exec] com.liferay.adaptive.media.image.internal.configuration.test.AMImageDisableConfigurationTest > testDisableNonexistantConfigurationEntry FAILED
     [exec]     java.lang.AssertionError
     [exec]     	at org.junit.Assert.fail(Assert.java:87)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
     [exec]     	at org.junit.Assert.assertNotNull(Assert.java:713)
     [exec]     	at org.junit.Assert.assertNotNull(Assert.java:723)
     [exec]     	at com.liferay.adaptive.media.image.internal.configuration.test.AMImageDisableConfigurationTest.testDisableNonexistantConfigurationEntry(AMImageDisableConfigurationTest.java:194)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-26/test-portal-acceptance-pullrequest(master)/7003/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
> @slnn regression found:
> 
> ```
>      [exec] com.liferay.adaptive.media.image.internal.configuration.test.AMImageDisableConfigurationTest > testDisableNonexistantConfigurationEntry FAILED
>      [exec]     java.lang.AssertionError
>      [exec]     	at org.junit.Assert.fail(Assert.java:87)
>      [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
>      [exec]     	at org.junit.Assert.assertNotNull(Assert.java:713)
>      [exec]     	at org.junit.Assert.assertNotNull(Assert.java:723)
>      [exec]     	at com.liferay.adaptive.media.image.internal.configuration.test.AMImageDisableConfigurationTest.testDisableNonexistantConfigurationEntry(AMImageDisableConfigurationTest.java:194)
>      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>      [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-26/test-portal-acceptance-pullrequest(master)/7003/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

Thank @catarineaguiar for catching this!  I  forced push with the fix and rerun tests.

**Comment by dantewang** [comment]
@slnn Conflicts, please resend.

**Comment by slnn** [comment]
Resend in https://github.com/liferay-core-infra/liferay-portal/pull/3115

**Pull request closed without merging**
