### PR TITLE
LPS-142278 Remove portal lib dir | Rebased 12-16 US

### PR DESCRIPTION
**Pull request by vicnate5**
@dantewang

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian No regressions found

**Comment by tinatian** [comment]
@shuyangzhou This is good to go

**Comment by koor4356** [comment]
@tinatian @vicnate5,
This looks good. No unique failures.

**Comment by dantewang** [comment]
ci:close

**Pull request closed without merging**
