### PR TITLE
LPS-188014 Add sync with SCR component actor thread to make sure all …

### PR DESCRIPTION
**Pull request by tinatian**
…components activated in SCR component actor thread finished after DependencyManagerSync#sync. It is done by registering a gatekeeper task to org.apache.felix.scr.impl.ComponentActorThread#tasks as the last task and wait for the last task finished.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:startup

**Comment by dantewang** [comment]
cc @yuhai

**Comment by tinatian** [comment]
@yuhai Could you please check if this works?

Thanks.
Tina

**Comment by yuhai** [comment]
@tinatian, @dantewang, the current pr can't fix the issue. It lacks the commit https://github.com/liferay-core-infra/liferay-portal/pull/5087/commits/f4041efd00e9f713dc64d55e7341b322b3364ccf. I resend it to https://github.com/liferay-core-infra/liferay-portal/pull/5087

**Pull request closed without merging**
