### PR TITLE
LPD-28759

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:51727151

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:53155837

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dantewang This should be rebased on https://github.com/brianchandotcom/liferay-portal/pull/153230. 

Also I saw only test are using the addCompany without "boolean createDefaultAdmin" parameter, we should remove that api method.

**Pull request closed without merging**
