### PR TITLE
[Optional Reference]LPS-185671 module: portal-scheduler

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-185671

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:clustering

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
Draft it for now, will revisit it after others are done.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5008

**Pull request closed without merging**
