### PR TITLE
LPS-155682 Remove module.framework.properties.ds.*

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have removed the properties and hardcoded them into ModuleFrameworkImpl

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:acceptance

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me scan test results when you free ? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
@zhangyan0701 Thank you.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Pull request closed without merging**
