### PR TITLE
[Remove Stream/Optional usage] LPS-172262 portal-search-tuning-rankings-web

### PR DESCRIPTION
**Pull request by haydenzheng314**
Ticket: https://issues.liferay.com/browse/LPS-172262

### CODE REVIEW

**Comment by catarineaguiar** [comment]
Waiting for https://github.com/brianchandotcom/liferay-portal/pull/128770 merge to be safe with the tests results.

**Comment by LisztLiszt** [comment]
ci:test:sf

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
can you rebase and re-run relevant, please?

Thanks, Cat.

**Pull request closed without merging**
