### PR TITLE
Lpd 37064 10 22

### PR DESCRIPTION
**Pull request by slnn**
The original pull https://github.com/liferay-core-infra/liferay-portal/pull/7560

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Hi @smottall

Please double-check if my changes break anything.


Thanks
Lily

**Comment by smottal** [comment]
ci:report:49013728

**Comment by tinatian** [comment]
@smottal To make this pull move, could you please take a look at my comment at https://github.com/liferay-core-infra/liferay-portal/pull/7560#issuecomment-2422922431

**Comment by smottal** [comment]
hey @tinatian , just to inform you the PR has been merged this morning including the changes of @slnn (thank you very much for your work!).
I saw your comment: we did some local tests and we saw dramatic improvement of that specific query. We will wait to propagate the usage of it until we make an official performance test. The reason of why there are two methods is because there are situation where you need either one or the other for instance in a PR I'm working on now.

Thank you very much for your support!

**Comment by smottal** [comment]
ci:close

**Pull request closed without merging**
