### PR TITLE
Lps 178726 4 6

### PR DESCRIPTION
**Pull request by slnn**
Resend since rebase error https://github.com/brianchandotcom/liferay-portal/pull/133058#event-8961776652

Tests have passed in https://github.com/liferay-core-infra/liferay-portal/pull/4133

cc @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
ci:forward:force

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@zhangyan0701 The `HeadlessBuilderTest` in https://github.com/liferay-core-infra/liferay-portal/pull/4133 and this pull failed and CI shows "0 of last 25", could you double check it?

**Comment by zhangyan0701** [comment]
No regressions found.

@dantewang "0 of last 25" means that on upstream tester the test didn't fail in the most recently 25 results. But it seems a flaky that also happens in some other PRs. I re-ran the test in https://github.com/zhangyan0701/liferay-portal/pull/480, and it passed.

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
