### PR TITLE
[Static reference] LPS-182671 Remove method reference by using snapshot in modules /blogs-web, portal-workflow-kaleo-forms-service, commerce-product-content-web

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:blogs

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
@W2jx no regressions found.

rebase please, thanks

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:blogs

**Comment by W2jx** [comment]
ci:test:commerce

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
@W2jx No regressions.

**Comment by W2jx** [comment]
no conflicts(5/2 10:54)

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/134300

**Pull request closed without merging**
