### PR TITLE
[Remove Blocking usages]LPS-187880 portal-kernel | SettingsFactoryUtil

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi Dante, this is the remaining part of the original pull request https://github.com/liferay-core-infra/liferay-portal/pull/5082 .

Thanks!

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Compile error:
```
     [exec] > Task :dxp:apps:analytics:analytics-reports-test:compileTestIntegrationJava FAILED
     [exec] Gradle build finished at 2023-07-27 11:43:48.297.
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/analytics/analytics-reports-test/src/testIntegration/java/com/liferay/analytics/reports/web/internal/product/navigation/control/menu/test/AnalyticsReportsProductNavigationControlMenuEntryTest.java:21: error: cannot find symbol
     [exec] import com.liferay.portal.kernel.settings.SettingsFactoryUtil;
     [exec]                                          ^
     [exec]   symbol:   class SettingsFactoryUtil
     [exec]   location: package com.liferay.portal.kernel.settings
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/analytics/analytics-reports-test/src/testIntegration/java/com/liferay/analytics/reports/web/internal/product/navigation/control/menu/test/AnalyticsReportsProductNavigationControlMenuEntryTest.java:153: error: cannot find symbol
     [exec] 						SettingsFactoryUtil.getSettingsFactory())) {
     [exec] 						^
     [exec]   symbol:   variable SettingsFactoryUtil
     [exec]   location: class com.liferay.analytics.reports.web.internal.product.navigation.control.menu.test.AnalyticsReportsProductNavigationControlMenuEntryTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/analytics/analytics-reports-test/src/testIntegration/java/com/liferay/analytics/reports/web/internal/product/navigation/control/menu/test/AnalyticsReportsProductNavigationControlMenuEntryTest.java:190: error: cannot find symbol
     [exec] 						SettingsFactoryUtil.getSettingsFactory())) {
     [exec] 						^
     [exec]   symbol:   variable SettingsFactoryUtil
     [exec]   location: class com.liferay.analytics.reports.web.internal.product.navigation.control.menu.test.AnalyticsReportsProductNavigationControlMenuEntryTest
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 3 errors
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-07/test-1-34/test-portal-acceptance-pullrequest(master)/4473/modules-compile-jdk8/0/5/jenkins-console.txt.gz?authuser=0

**Pull request closed without merging**
