### PR TITLE
LPS-155543 Move com.liferay.portal.jsonwebservice package and related tests to a module

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:acceptance

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:environments

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by rafaprax** [comment]
Hey @shuyangzhou, this pr is ready for your review. Thx

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-core-infra/liferay-portal/pull/987

**Pull request closed without merging**
