### PR TITLE
LPS-188781 Use hard reference in SearchAdminPortlet

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-188781

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@slnn No regressions found, but rebase is needed.

**Comment by dantewang** [comment]
@slnn Please fix conflicts.

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:search

**Comment by tinatian** [comment]
@slnn Please provide more context why you made this change in your commit message. The same thing happened at https://github.com/liferay-core-infra/liferay-portal/pull/4786#issuecomment-1593828607, I do not want to see it happen another time.

**Comment by slnn** [comment]
Hi @tinatian 

Sorry for this, I have added the context in the commit message and forced push to this branch, it will not affect the test result since I only change the commit message.

Lily

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137114

**Comment by slnn** [comment]
This change is reverted on the head of master since it caused a regression, please see: 
https://liferay.atlassian.net/browse/LPS-189803

Hi @Kvale1733 

Could you please check if we missing any tests for this pull?

Lily

**Comment by Kvale1733** [comment]
@slnn We can run the search-solr and that probably would have caught this but based on the changes I didn't see a reason to. We ran the search suite and that had no issue.

**Comment by dantewang** [comment]
@Kvale1733 
Sometimes we modify Liferay's search framework code (like this `SearchAdminPortlet`), not the integration code of specific search engine (ES, Solr), and we should run tests for both engines just in case. So it could be a problem that `ci-test-search` doesn't run Solr tests. By this name, we expect it to run all search related tests...

**Comment by Kvale1733** [comment]
@dantewang Hmm I see that the search test suite specifically excludes solr8 integration tests so seems intentional but I will ask to clarify

**Pull request closed without merging**
