### PR TITLE
LPS-170144 Remove TemplateResourceLoaderUtil usage in ThemeUtil

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by julschong** [comment]
Added [8b336a7](https://github.com/liferay-core-infra/liferay-portal/pull/2597/commits/8b336a7b7f98b297a16f5ea438a08e70898d8869)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:stop

**Pull request closed without merging**
