### PR TITLE
LPS-176787 upgrade Apache Commons FileUpload to 1.5

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This is for ticket https://issues.liferay.com/browse/LPS-176787.
Thanks for checking!

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
no regressions found.

SF issue doesn't seem a real issue, since the LPS exists.
```
[java] Commit message is pointing to non-existing JIRA issue: LPS-176787
     [java]   at com.liferay.source.formatter.util.JIRAUtil.validateJIRATicketIds(JIRAUtil.java:100)
     [java]   at com.liferay.source.formatter.SourceFormatter._validateCommitMessages(SourceFormatter.java:1306)
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:335)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:299)
[stopwatch] [run.batch.test.action: 3:41.561 sec]
```

**Comment by jeffwu0724** [comment]
fixed the code conflict in lib/versions-complete.xml, the previous test result should be good

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136658

**Pull request closed without merging**
