### PR TITLE
[TS] LPD-29738 | 3

### PR DESCRIPTION
**Pull request by dantewang**
@JerryAdrianoo Please run both runtime and startup comparison for this PR, thanks.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:30091855

**Comment by JerryAdrianoo** [comment]
Hey @dantewang  for more details from this test, see: [spreadsheet](https://docs.google.com/spreadsheets/d/1tNwy1g9I16aTFl8LdXPI53ii7hm5ea986vCZYpRTl3o/edit?usp=sharing) 

Branch| Startup Time (ms)(without  default HSQL data)  Cold start | Percent of Average Startup Time Cold Start | Startup Time (ms)(without  default HSQL data) Hot start | Average Startup Time (ms)(without default HSQL data)  Hot start | Percent of Average Startup Time Hot Start | Shutdown Time (ms)(without default HSQL data)   Cold start | Shutdown Time (ms)(without default HSQL data)  Hot start | Average Shutdown Time (ms)(without default HSQL data)  Hot start
-- | -- | -- | -- | -- | -- | -- | -- | --
Before LPD-29738 | **42,826** | | 16,684 | | | **2,536** | 2,059
|  | | | 15,902 | | | | 2,024
|  | | | 16,608 | | | | 1,964
 | | | | 16,404 | | | | 2,003
 | | | | 16,761 |**16,565** | | | 1,883 | **1,997**
-- | -- | -- | -- | -- | -- | -- | --
After LPD-29738 | **43,134** | | 15,847 | | | **2,710** | 1,971
|  | | | 16,556 | | | | 1,932
|  | | | 16,541 | | | | 2,002
|  | | | 16,502 | | | | 1,966
| | |  -0.91% | 16,566 |**16,533** |  **-0.19**% | | 1,981 | **1,973**

Everything looks ok, I didn't see any regression with these changes.

-------------------------------------------------------------------------------------------------------------------------------------------------------------------

I put the benchmark test results in the same spreadsheet above. Since finishing all these tests takes a long time, only the Asset Publisher test is missing. Tomorrow I can finish it.

Please let me know if you need something else.

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 30091855.
> 
> Job Link: [generate-testray-csv](https://test-1-7.liferay.com/job/generate-testray-csv/72/)
> 
> Testray CSV Link: [testray-results-30091855.csv](https://test-1-7.liferay.com/userContent/jobs/generate-testray-csv/builds/72/testray-results-30091855.csv)

No unique in relevant, [this case](https://testray.liferay.com/#/project/34754/routines/34756/build/30091855/case-result/30092261/history) also failed once upstream.

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:30889115

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 30889115.
> 
> Job Link: [generate-testray-csv](https://test-1-30.liferay.com/job/generate-testray-csv/165/)
> 
> Testray CSV Link: [testray-results-30889115.csv](https://test-1-30.liferay.com/userContent/jobs/generate-testray-csv/builds/165/testray-results-30889115.csv)

None of the unique failures are actually relevant. They all happen frequently on other runs.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7218

**Pull request closed without merging**
