### PR TITLE
[Rename Classes] LPS-166958 Rename classes in modules fragment-api、fragment-impl、fragment-collection-filter-api、fragment-collection-filter-impl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
Semantic Versioning error:
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/fragment/fragment-collection-filter-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.fragment.collection.filter             MAJOR      1.3.0      1.2.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	+   interface  com.liferay.fragment.collection.filter.FragmentCollectionFilterRegistry
     [exec]     		+   access     abstract
     [exec]     		+   method     getFragmentCollectionFilter(java.lang.String)
     [exec]     			+   access     abstract
     [exec]     			+   return     com.liferay.fragment.collection.filter.FragmentCollectionFilter
     [exec]     		+   method     getFragmentCollectionFilters()
     [exec]     			+   access     abstract
     [exec]     			+   return     java.util.List
     [exec]     		+   annotated  aQute.bnd.annotation.ProviderType
     [exec]     	-   interface  com.liferay.fragment.collection.filter.FragmentCollectionFilterTracker
     [exec]     		-   access     abstract
     [exec]     		-   method     getFragmentCollectionFilter(java.lang.String)
     [exec]     			-   access     abstract
     [exec]     			-   return     com.liferay.fragment.collection.filter.FragmentCollectionFilter
     [exec]     		-   method     getFragmentCollectionFilters()
     [exec]     			-   access     abstract
     [exec]     			-   return     java.util.List
     [exec]     		-   annotated  aQute.bnd.annotation.ProviderType
     [exec]     	-   version    1.2.0
     [exec]     	+   version    1.3.0
```
Full console log:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-39/test-portal-acceptance-pullrequest(master)/1470/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

Other failures are unrelated.

**Comment by dantewang** [comment]
@W2jx Please fix the sem ver error, thanks!

**Comment by W2jx** [comment]
Hi @dantewang @zhangyan0701, I execute command `..\..\..\..\gradlew baseline` under path `modules\apps\fragment\fragment-collection-filter-api` multiple times, but no additional version files are modified. Could you please help me check it? Thank you!

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Semantic Versioning failed in the most recently relevant result:
```
     [exec] > Task :apps:fragment:fragment-collection-filter-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.fragment.collection.filter             MAJOR      1.3.0      1.2.0      2.0.0      VERSION INCREASE REQUIRED
     [exec] 	+   interface  com.liferay.fragment.collection.filter.FragmentCollectionFilterRegistry
     [exec] 		+   access     abstract
     [exec] 		+   method     getFragmentCollectionFilter(java.lang.String)
     [exec] 			+   access     abstract
     [exec] 			+   return     com.liferay.fragment.collection.filter.FragmentCollectionFilter
     [exec] 		+   method     getFragmentCollectionFilters()
     [exec] 			+   access     abstract
     [exec] 			+   return     java.util.List
     [exec] 		+   annotated  aQute.bnd.annotation.ProviderType
     [exec] 	-   interface  com.liferay.fragment.collection.filter.FragmentCollectionFilterTracker
     [exec] 		-   access     abstract
     [exec] 		-   method     getFragmentCollectionFilter(java.lang.String)
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.fragment.collection.filter.FragmentCollectionFilter
     [exec] 		-   method     getFragmentCollectionFilters()
     [exec] 			-   access     abstract
     [exec] 			-   return     java.util.List
     [exec] 		-   annotated  aQute.bnd.annotation.ProviderType
     [exec] 	-   version    1.2.0
     [exec] 	+   version    1.3.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.fragment.collection.filter.api-2.0.0.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.fragment.collection.filter.api/1.2.3/9307bcdcc7b39de61df0720fbe4a77cae0cb7d18/com.liferay.fragment.collection.filter.api-1.2.3.jar
```
Full console:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6221/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

The recommended version is 2.0.0 according to the error message.

**Comment by W2jx** [comment]
I will try to modify it manually. Thanks @zhangyan0701!

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Pull request closed without merging**
