### PR TITLE
[Destination] LPD-29543

### PR DESCRIPTION
**Pull request by dantewang**
LPD-29543/LPD-29544

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:54143758

**Comment by dantewang** [comment]
@tinatian I only added breaking change message and sem ver commit, as this class is surprisingly in a public package; no other failure in relevant, so no need to re-run.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/153232

**Pull request closed without merging**
