### PR TITLE
[Method References 2] LPS-171023 Convert method reference to field reference in class IndexResourceImpl

### PR DESCRIPTION
**Pull request by W2jx**
resend, I have modified the calss WorkflowMetricsIndexEntityNameConstant and removed WorkflowMetricsIndexNameBuilder and its impl

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4423

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:workflow-metrics

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(6/1 16:10)

**Comment by W2jx** [comment]
no conflicts(6/2 8:25)

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:workflow-metrics

**Comment by catarineaguiar** [comment]
@W2jx please resolve conflicts and re-run test suites.

thanks

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:workflow-metrics

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(6/7 8:27)

**Comment by W2jx** [comment]
no conflicts(6/8 8:29)

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136024

**Pull request closed without merging**
