### PR TITLE
[Remove Stream/Optional usage] LPS-175361 modules: journal-article-dynamic-data-mapping-form-field-type,  journal-content-web,  journal-web

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-175361

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Pull request closed without merging**
