### PR TITLE
[TS] LPS-189621 Get users one by one instead of all at once because of argument number limitation

### PR DESCRIPTION
**Pull request by alvarosaugarlr**
[LPS-189621](https://liferay.atlassian.net/browse/LPS-189621)

We received this ticket from Support team with a solution of the exception (number of parameters problem with SQL Server): 
`ERROR [http-nio-8080-exec-7][SqlExceptionHelper:142] The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.`

We believe the best solution would be to apply the property to SQL Server 
`database.in.max.parameters[sqlserver]=1000`

We have followed the steps described in the ticket with both Oracle (works correctly) and SQL Server (exception is still thrown). 

I add the [original pr](https://github.com/liferay-appsec/liferay-portal/pull/1219) sent and the comment:

> Hi Team,
> 
> https://liferay.atlassian.net/browse/LPS-189621
> 
> Environment:
> SQL Server 2017
> 
> Issue:
> If a site got deactivated with more than 2100 users, then the console would show an error telling us that it can only handle 2100 arguments. This happened because in the reindex method, the query got a list of ids that went beyond 2100 in length.
> 
> Solution:
> Saw lots of similar issues and I went with the same approach. Get the users that need to be reindexed one by one. Tried DSLQuery but the same error came up.
> 
> Testing:
> Tested it locally. The solution works. In regards of performance, well it took 26 seconds to reindex 2100 users. Tested it with the original code and 2070 users and the time was the same. Tested it with oracle server as well and took the same amount of time .
> I used cloud db for the database.
> 
> Please review my PR!
> 
> Best regards,
> Dani

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:user

**Comment by Kvale1733** [comment]
ci:test:users

**Comment by Kvale1733** [comment]
@alvarosaugarlr Regressions found in 2 integration tests

1) com.liferay.users.admin.search.test.UserGroupCascadeReindexUsersTest
```
  [exec] com.liferay.users.admin.search.test.UserGroupCascadeReindexUsersTest > testPerformanceOfMultiSiteLargeUserGroup FAILED
     [exec]     org.junit.ComparisonFailure: {"from":0,"size":10000,"query":{"bool":{"must":[{"bool":{"must":[{"term":{"groupId":{"value":64441}}}],"must_not":[{"term":{"userId":{"value":20123}}}]}},{"bool":{"filter":[{"bool":{"must":[{"bool":{"should":[{"bool":{"must":[{"term":{"entryClassName":{"value":"com.liferay.portal.kernel.model.User"}}},{"term":{"status":{"value":"0"}}},{"term":{"status":{"value":"0"}}},{"terms":{"type":["1"]}},{"terms":{"type":["1"]}},{"bool":{"must":[{"bool":{"must_not":[{"exists":{"field":"ctCollectionId"}}]}}]}},{"bool":{"must":[{"bool":{"must_not":[{"exists":{"field":"ctCollectionId"}}]}}]}}],"must_not":[{"term":{"type":{"value":"0"}}},{"term":{"type":{"value":"0"}}},{"prefix":{"screenName":{"value":"on_demand_admin"}}},{"prefix":{"screenName":{"value":"on_demand_admin"}}}]}}]}}]}}]}}]}},"explain":false,"stored_fields":"groupId","track_scores":true,"track_total_hits":2147483647}->->[] expected:<[[[64441, 64444], [64441, 64444], [64441, 64444]]]> but was:<[[]]>
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:117)
     [exec]     	at com.liferay.portal.search.test.util.DocumentsAssert.assertValues(DocumentsAssert.java:67)
     [exec]     	at com.liferay.users.admin.search.test.UserGroupCascadeReindexUsersTest.testPerformanceOfMultiSiteLargeUserGroup(UserGroupCascadeReindexUsersTest.java:155)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
```
[](https://testray.liferay.com/reports/production/logs/2023-07/test-1-32/test-portal-acceptance-pullrequest(master)/1049/modules-integration-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

2) com.liferay.users.admin.search.test.UserReindexerPerformanceOfLargeUserGroupInManySitesTest
```
  [exec] com.liferay.users.admin.search.test.UserReindexerPerformanceOfLargeUserGroupInManySitesTest > testBulkSynchronous FAILED
     [exec]     org.junit.ComparisonFailure: {"from":0,"size":10000,"query":{"bool":{"must":[{"bool":{"must":[{"term":{"groupId":{"value":64731}}},{"term":{"groupId":{"value":64734}}}],"must_not":[{"term":{"userId":{"value":20123}}}]}},{"bool":{"filter":[{"bool":{"must":[{"bool":{"should":[{"bool":{"must":[{"term":{"entryClassName":{"value":"com.liferay.portal.kernel.model.User"}}},{"term":{"status":{"value":"0"}}},{"term":{"status":{"value":"0"}}},{"terms":{"type":["1"]}},{"terms":{"type":["1"]}},{"bool":{"must":[{"bool":{"must_not":[{"exists":{"field":"ctCollectionId"}}]}}]}},{"bool":{"must":[{"bool":{"must_not":[{"exists":{"field":"ctCollectionId"}}]}}]}}],"must_not":[{"term":{"type":{"value":"0"}}},{"term":{"type":{"value":"0"}}},{"prefix":{"screenName":{"value":"on_demand_admin"}}},{"prefix":{"screenName":{"value":"on_demand_admin"}}}]}}]}}]}}]}}]}},"explain":false,"stored_fields":"userId","track_scores":true,"track_total_hits":2147483647}->->[] expected:<[[64702, 64711, 64720]]> but was:<[[]]>
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:117)
     [exec]     	at com.liferay.portal.search.test.util.DocumentsAssert.assertValuesIgnoreRelevance(DocumentsAssert.java:91)
     [exec]     	at com.liferay.users.admin.search.test.UserReindexerPerformanceOfLargeUserGroupInManySitesTest.doTestTiming(UserReindexerPerformanceOfLargeUserGroupInManySitesTest.java:247)
     [exec]     	at com.liferay.users.admin.search.test.UserReindexerPerformanceOfLargeUserGroupInManySitesTest.lambda$doTest$0(UserReindexerPerformanceOfLargeUserGroupInManySitesTest.java:198)
     [exec]     	at com.liferay.users.admin.search.test.UserReindexerPerformanceOfLargeUserGroupInManySitesTest.measure(UserReindexerPerformanceOfLargeUserGroupInManySitesTest.java:277)
     [exec]     	at com.liferay.users.admin.search.test.UserReindexerPerformanceOfLargeUserGroupInManySitesTest.doTest(UserReindexerPerformanceOfLargeUserGroupInManySitesTest.java:198)
     [exec]     	at com.liferay.users.admin.search.test.UserReindexerPerformanceOfLargeUserGroupInManySitesTest.doTest(UserReindexerPerformanceOfLargeUserGroupInManySitesTest.java:211)
     [exec]     	at com.liferay.users.admin.search.test.UserReindexerPerformanceOfLargeUserGroupInManySitesTest.testBulkSynchronous(UserReindexerPerformanceOfLargeUserGroupInManySitesTest.java:130)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
[](https://testray.liferay.com/reports/production/logs/2023-07/test-1-32/test-portal-acceptance-pullrequest(master)/1049/modules-integration-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

**Comment by alvarosaugarlr** [comment]
Hello @Kvale1733 , 

 This is the pr that has been sent from Support team to us. As we indicated in the ticket, there are tests that fail with this solution. We believe that it is not the right solution, but as it is your component we believe that the decision is yours and that is why we are sending you the pr without changes. 

All the information we have found, is added to the ticket. 

Thanks!

**Comment by Kvale1733** [comment]
@tinatian See the above comment.

**Comment by yuhai** [comment]
Hi @alvarosaugarlr,

The current solution seems to be not right. Because the root issue belongs to the common issue, this solution changed its usage to avoid the issue. Other usages use RestrictionsFactory#in() also existed the issue.

I checked LPS's comment, you mentioned the solution seems to be right **database.in.max.parameters[sqlserver]=1000**. Please follow this way to check why it didn't work. If you need some help for the issue, you may create PRT ticket to ask for some help or escalate LPS.

By the way, could you please provide a database dump to the LPS so that we can reproduce the issue easily? For example, We may directly execute **Deactivate the site** to reproduce the issue.

Please let me know if you have other concerns.

Thanks,
Hai

**Comment by dantewang** [comment]
@alvarosaugarlr A more preferred way is to add some integration or unit tests that abstract and replicate the customer issue. I'm going to close this PR for now, please send the tests or the dump, thanks!

**Pull request closed without merging**
