### PR TITLE
[Component with its own class name as service type ] LPS-194418 Refactor Registry classes from objects module

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:objects

**Comment by catarineaguiar** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
ci:test:object

**Review by rafaprax — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139966

**Pull request closed without merging**
