### PR TITLE
[Static reference] LPS-170718 Remove method reference by using snapshot in module friendly-url-taglib

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:friendly-url

**Comment by Kvale1733** [comment]
@W2jx No regressions.

**Comment by W2jx** [comment]
no conflicts(4/11 11:12)

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
