### PR TITLE
LPS-172916 Remove "immediate = true" from SDK modules

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:gradle-plugins

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:stop:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@MrJohn1911 can you rebase and re-run the tests suites, please?

Thanks, Cat.

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:gradle-plugins

**Comment by MrJohn1911** [comment]
@rafaprax can you review this pull? thanks in advance!

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions.

**Comment by MrJohn1911** [comment]
Hey @tinatian this one is ready to go!

**Comment by rafaprax** [comment]
> @rafaprax can you review this pull? thanks in advance!

LGTM

**Comment by MrJohn1911** [comment]
Hey @tinatian this one is ready to go!

**Comment by tinatian** [comment]
@MrJohn1911 I believe you need to upload fake grade cache to make sure your changes are applied, please check with Peter Shin for how to do that.

Tina.

**Comment by MrJohn1911** [comment]
Hi @tinatian, I talked with Greg Amerson and he said that this changes should not have any impact, so this pr is good to go.

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
