### PR TITLE
[Components with more than 1 service] LPS-181810 Refactor ServiceVerifyProcess components from Security and Commerce modules

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-181810](https://issues.liferay.com/browse/LPS-181810)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:security

**Comment by RenanUmV** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
no regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/134176

**Pull request closed without merging**
