### PR TITLE
[TS] LPS-165900 portal-cache-impl compileTestJava failed in unit tests

### PR DESCRIPTION
**Pull request by TaiPhamLR**
Hi team,
This fix for ticket [LPS-165900](https://issues.liferay.com/browse/LPS-165900) was passed my review. Please help me to review it and give your comments.
Thanks,
Tai.
@sontruongces

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
cc @julschong

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
@TaiPhamLR Hi Tai,
Thanks for sending the fix, it looks good.

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@shuyangzhou @tinatian @julschong @TaiPhamLR I sent this to https://github.com/brianchandotcom/liferay-portal/pull/125330 as it's a straight-forward test fix, reviewed by QA, and affecting CI.

**Pull request closed without merging**
