### PR TITLE
[Bug fix] LPS-88060

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian https://issues.liferay.com/browse/LPS-88060

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by yuhai** [comment]
@tinatian, TemplateProcessor#processPortlet() seems to be a deprecated api for master or above 7.2. We documented it in the old documents. Please refer to the [link ](https://help.liferay.com/hc/en-us/articles/360018180991-Embedding-Portlets-in-a-Layout-Template). 
```
To embed a portlet, you must specify the following things:

Add a $processor.processPortlet(...) directive within the column in which to embed the portlet.

Pass in the portlet’s Fully Qualified Portlet ID (FQPI) as the string parameter to the $processor.processPortlet(...) directive.
```

Refer to the [comment ](https://issues.liferay.com/browse/LPS-88060?focusedCommentId=1708044&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1708044), 7.1 has documented it, but I didn't find the link.

If we drag a portlet to one page on master, the api won't be invoked.

**Comment by tinatian** [comment]
@yuhai @dantewang Let's try to dig more about the embedded portlet feature and have a talk about it. The fix looks weird to me.

Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
