### PR TITLE
[Bug Fix] LPS-146037 Use ConcurrentSkipListSet to store company IDs

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@dantewang Please see https://github.com/liferay-core-infra/liferay-portal/pull/317.

After a second thought, I chose CopyOnWriteArrayList rather than ConcurrentSkipListSet. Reason is ConcurrentSkipListSet is going to store the elements in natural order which is not the case here. In this case, we would like to store the element based on the order it addes.

Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
