### PR TITLE
LPS-145927

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by dantewang** [comment]
@marianoalvarosaiz Is there any big change between this and the previous reviewed PR, or is this just rebase, etc.?

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results when they are out? Thanks!

**Comment by marianoalvarosaiz** [comment]
@dantewang it isn't a significant change, it's just a rebase of the missing commits changing Matchers.eq for Mockito.eq to resolve conflicts with LPS-153088.

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
Hi @catarineaguiar Could you please take a look at test results? Thanks!

**Comment by catarineaguiar** [comment]
@marianoalvarosaiz @zhangyan0701 no regression found on relevant.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121405

**Pull request closed without merging**
