### PR TITLE
[Components with more than 1 service] LPS-175886 Refactor DTO Converter components with more than 1 service type from headless-admin-user-impl module

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://issues.liferay.com/browse/LPS-175886
Change request: https://github.com/brianchandotcom/liferay-portal/pull/135564#issuecomment-1567870000

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:users

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Review by rafaprax — CHANGES_REQUESTED** [review]

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:headless

**Comment by MrJohn1911** [comment]
ci:test:users

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:headless

**Comment by MrJohn1911** [comment]
ci:test:users

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by rafaprax** [comment]
ci:forward:force

**Pull request closed without merging**
