### PR TITLE
[Hibernate-sqlserver] LPS-151508

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, please check this after ci test result is no problem.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:backend

**Comment by yuhai** [comment]
@zhangyan0701, please help check if com.liferay.view.count.service.impl.test.ViewCountEntryLocalServiceTest can be passed on the different database.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/119443

**Pull request closed without merging**
