### PR TITLE
[TS] LPS-201892

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by yuhai** [comment]
@marianoalvarosaiz, the methods `_testUpdateMailPortletPreferences(long)` and `testUpdateMailSystemPortletPreferences()` Exception declaration are unnecessary, please push force the changes. And then I will forward it to Dante to review.

**Comment by marianoalvarosaiz** [comment]
Done @yuhai

**Review by yuhai — APPROVED** [review]
@dantewang, the pr is good to me. When accessing these two jsp, `ServerAdminControlPanelEntry#hasAccessPermission()` and `InstanceSettingsControlPanelEntry#hasAccessPermission()` will firstly check the accessing persmission. After passing them, then render mail.jsp and company_mail.jsp.

For the current solution, Tina provided the fix way "separate system and instance configuration" in previous pull. Please see https://github.com/liferay-core-infra/liferay-portal/pull/6176

**Review by dantewang — APPROVED** [review]

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
Test failure is unrelated and will be solved here: https://liferay.atlassian.net/browse/LPS-205216

**Comment by marianoalvarosaiz** [comment]
Hi @tinatian , do you have any updates about this issue?

**Comment by tinatian** [comment]
@marianoalvarosaiz `company_mail.jsp` and `mail.jsp` have similar code, could you please extract them out

Thanks.
Tina.

**Comment by marianoalvarosaiz** [comment]
@tinatian see https://github.com/liferay-core-infra/liferay-portal/pull/6486

**Pull request closed without merging**
