### PR TITLE
LPD-36036 Use Tomcat Jasper for Runtime

### PR DESCRIPTION
**Pull request by dantewang**
ci-test-app-servers passed at https://github.com/dantewang/liferay-portal/pull/2402#issuecomment-2434037738

ci-test-relevant is still running at https://github.com/dantewang/liferay-portal/pull/2402, but the previously failed unique tests pass on my local.

Also running CI without jsp.precompile at https://github.com/liferay-core-infra/liferay-portal/pull/7582

### CODE REVIEW

**Comment by dantewang** [comment]
No unique failure in ci-test-relevant in https://github.com/dantewang/liferay-portal/pull/2402#issuecomment-2436638578.

**Comment by tinatian** [comment]
ci:help

**Comment by tinatian** [comment]
ci:test:frontend

**Comment by tinatian** [comment]
ci:report:53380659

**Comment by dantewang** [comment]
ci:report:53380659

**Comment by dantewang** [comment]
ci:test:frontend

Rerun to confirm `LocalFile.WalkthroughSiteLevel#CanRenderWhenStepIsBelowFold`.

**Comment by dantewang** [comment]
`LocalFile.WalkthroughSiteLevel#CanRenderWhenStepIsBelowFold` Passed.

**Comment by dantewang** [comment]
Close in favor of https://github.com/liferay-core-infra/liferay-portal/pull/7587

**Pull request closed without merging**
