### PR TITLE
LPS-189313 Failing virtual instance creation leaves behind orphaned workflow metrics indices

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Dear Team,

Could you please review this pull request?

## Motivations

[Failing virtual instance creation leaves behind orphaned workflow metrics indexes](https://liferay.atlassian.net/browse/LPS-189313)

## Proposed Solution

Providing a method that will be called on failing company creation, 

this way we can make sure that when a company was not registered so we will be able to revert the changes applied by `portalInstancePreRegistered` method ([see](https://github.com/liferay/liferay-portal/blob/1f9c3cc0c0024a8e12b7643afa953e86a2da082c/portal-impl/src/com/liferay/portal/service/impl/CompanyLocalServiceImpl.java#L1981)).

Another suggested approach is to use the `portalInstanceRegistered` method, as it will be called after the transaction ([see](https://github.com/liferay/liferay-portal/blob/1f9c3cc0c0024a8e12b7643afa953e86a2da082c/portal-impl/src/com/liferay/portal/service/impl/CompanyLocalServiceImpl.java#L2080-L2085)), 

but for Workflow Metrics I believe we can't do this because it will cause intermittent errors on [reindex](https://github.com/liferay/liferay-portal/blob/bd7145551c94c4e768c7f070cfbe243293169865/modules/dxp/apps/portal-workflow/portal-workflow-metrics-service/src/main/java/com/liferay/portal/workflow/metrics/internal/search/index/creation/instance/lifecycle/WorkflowMetricsIndexPortalInstanceLifecycleListener.java#L44) like:

`ElasticsearchStatusException[Elasticsearch exception [type=index_not_found_exception, reason=no such index […]]]`

Thank you,
Feliphe Marinho

### CODE REVIEW

**Comment by lipusz** [comment]
@BryanEngler fyi :eyes:

**Comment by Kvale1733** [comment]
ci:test:workflow-metrics

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by tinatian** [comment]
@MarinhoFeliphe 
1. Any reason you have to create a new API method rather than use portalInstanceUnregistered? I really do not see any reason you have to expose a new API method.
2.
>  
> Another suggested approach is to use the portalInstanceRegistered method, as it will be called after the transaction (see),
> but for Workflow Metrics I believe we can't do this because it will cause intermittent errors on reindex like:
> 

Why this happen? Please make sure you fully understand the reason you are seeing this issue before you modifying framework level API, as it might be a bug exposed by your change which should be fixed.

Please reconsider your solution and resend.

Thanks.
Tina.

**Comment by MarinhoFeliphe** [comment]
@tinatian thanks for your review,

> Any reason you have to create a new API method rather than use portalInstanceUnregistered? I really do not see any reason you have to expose a new API method.

`portalInstanceUnregistered` is called when a registered company is deleted.

`portalInstanceNotRegistered` would be called when a company was preRegistered but was not registered (created) due to errors that can happen [between preRegister and register](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/CompanyLocalServiceImpl.java#L1969-L2064).

I opted to provide a new method because besides they do the same think from Workflow Metrics side they are two different triggers, one when a company is deleted and the another one when a company is not registered due to errors.

> Why this happen?

When the Workflow Metrics indexes creation is moved to WorkflowMetricsIndexPortalInstanceLifecycleListener.portalInstanceRegistered [this way](https://github.com/liferay-workflow/liferay-portal/pull/958/files#diff-d01c47549608444abdaa5e2917fe5c507dc59164c95da662433cb1192bcb7eb3R34) for 
example,

any other place that needs to get those information from Workflow Metrics indexes will break if the WorkflowMetricsIndexPortalInstanceLifecycleListener.portalInstanceRegistered was not called before,

for example, this class AddMBModerationWorkflowDefinitionPortalInstanceLifecycleListener is calling WorkflowDefinitionManager to deploy a workflow definition, under the hood it will reach workflow metrics indexes but they were not created by WorkflowMetricsIndexPortalInstanceLifecycleListener.portalInstanceRegistered yet.

here it is a [log](https://testray.liferay.com/reports/production/logs/2023-07/test-1-39/test-portal-acceptance-pullrequest(master)/5899/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0) that traced this examples above.

Best Regards,
Feliphe Marinho

**Comment by MarinhoFeliphe** [comment]
@tinatian 

> the current company model should be deleted. It does not make sense to have a unfinished company stay in the system as no one can use it.

the unfinished company is not persisted, when an exception is thrown [at](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/CompanyLocalServiceImpl.java#L1969-L2064) the company is not created probably it is being rollbacked.

> Why you made this change?

Just to easily demonstrate the reason why I must not do this from Workflow Metrics side, because this approach was suggested by others.

**Pull request closed without merging**
