### PR TITLE
LPS-84865

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on the [requirement](https://github.com/liferay-core-infra/liferay-portal/pull/10)

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
