### PR TITLE
LPS-189359 Unsatisfied reference at com.liferay.portal.monitoring on Wildfly, Websphere, and JBoss

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-189359

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:environments

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found. This fixes the issue.

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
