### PR TITLE
[Rename classes in module: dynamic-data-mapping]Lps 167105

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-167105

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
@slnn 

Semver error
```
 [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/data-engine/data-engine-rest-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.data.engine.rest.dto.v2_0.util         MAJOR      1.0.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.data.engine.rest.dto.v2_0.util.DataDefinitionDDMFormUtil
     [exec]     		+   method     toDDMForm(com.liferay.data.engine.rest.dto.v2_0.DataDefinition,com.liferay.dynamic.data.mapping.form.field.type.DDMFormFieldTypeServicesRegistry)
     [exec]     			+   access     static
     [exec]     			+   return     com.liferay.dynamic.data.mapping.model.DDMForm
     [exec]     		-   method     toDDMForm(com.liferay.data.engine.rest.dto.v2_0.DataDefinition,com.liferay.dynamic.data.mapping.form.field.type.DDMFormFieldTypeServicesTracker)
     [exec]     			-   access     static
     [exec]     			-   return     com.liferay.dynamic.data.mapping.model.DDMForm
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 30.0.0
```
[Log](https://testray.liferay.com/reports/production/logs/2022-11/test-1-32/test-portal-acceptance-pullrequest(master)/6649/modules-semantic-versioning-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
Thank @Kvale1733 for catching this!

Forced push to fix the issue and conflicts for bnd and packageinfo files, no logic changes.

**Comment by dantewang** [comment]
@slnn Conflicts, please resend.

**Comment by slnn** [comment]
Resend in https://github.com/liferay-core-infra/liferay-portal/pull/2359

**Pull request closed without merging**
