### PR TITLE
[Remove immediate=true usage core-infrastructure-3 part 1]Lps 169260

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-169260

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:dl-store

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Comment by dantewang** [comment]
@slnn I have `initial.system.check.enabled=true` in my portal-ext.properties, but didn't see any check running during startup. Could you double check?

I'm going to close this one, please either resend or reopen, thanks.

**Pull request closed without merging**
