### PR TITLE
LPS-188561 Fix SXPBlueprintOptionsPortletPreferencesUtil with null check

### PR DESCRIPTION
**Pull request by julschong**
@tinatian @Kvale1733 
This bug is reported here: https://liferay.atlassian.net/browse/LPS-188561
It's caused by my last portal-search-web-api remove stream and optional pull because I missed a null check in SXPBlueprintOptionsPortletPreferencesUtil.
To test, please help manual follow the steps in the ticket.
Thanks!

### CODE REVIEW

**Comment by julschong** [comment]
@vicnate5 Hi Victor, I added [LPS-188720 Remove workaround added in LPS-188719](https://github.com/liferay-core-infra/liferay-portal/pull/4859/commits/0e000f764fd4754de9134bd25d533db4f06ae4ae) to revert the workaround put in to deal with the failed functional test. Please add some ci command to test the functional test after you find it. Thanks!

**Comment by vicnate5** [comment]
ci:test:search

**Comment by vicnate5** [comment]
FYI @brookedalton @joshchong fix for the Blueprints regression

**Comment by joshchong** [comment]
@vicnate5 I just analyzed the `ci:test:search` results and they look good.

**Comment by vicnate5** [comment]
No regressions found. Issue is fixed per the automation.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136936

**Pull request closed without merging**
