### PR TITLE
LPD-38920

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:4301812

**Comment by ericyanLr** [comment]
ci:report:43018125

**Comment by ericyanLr** [comment]
**ci:report analysis**
Reported unique failures can be ignored, these failures have also been observed in other recent PRs.

Our specific test is passing: **com.liferay.portal.service.ServiceContextAdviceTest**
- Jenkins: https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/437420/testReport/com.liferay.portal.service/ServiceContextAdviceTest/
- Testray: https://testray.liferay.com/#/project/35392/routines/45357/build/43018125/case-result/43022844

Marking this as **QA Passed** and **Ready to Review (no regression)**

**Comment by dantewang** [comment]
ci:forward:force

Forwarding as this is an already-reviewed change and tests passed.

**Pull request closed without merging**
