### PR TITLE
LPS-176215 Make Elasticsearch connection pool settings configurable

### PR DESCRIPTION
**Pull request by dantewang**
@111Anna Please run AP test on this PR again, thanks!

### CODE REVIEW

**Comment by 111Anna** [comment]
@dantewang  I ran the PR  on main2 env, the result looks good.

 AP:
Portal Version|GitId|Session Count |Mean Time of Login|Session Count Change (%)|
--|--| --|--|--|
LPS-174821| c151fd33| 28520 | 390 |-|
LPS-174821 + PR-3596| - | 30035 |397 |5.3% |

**Comment by dantewang** [comment]
@111Anna The result should be of the same effect with the local workaround, right?

**Comment by 111Anna** [comment]
> @111Anna The result should be of the same effect with the local workaround, right?

Yes, it has almost the same effect，This is the test result of  local resolvent

AP:

Portal Version|GitId|Session Count |Mean Time of Login|Session Count Change (%)|
--|--| --|--|--|
LPS-174821| c151fd33| 28520 | 390 |-|
LPS-174821 + Change-connection-pool-size| - | 30424 |418 |6.6% |

**Comment by dantewang** [comment]
@111Anna OK thanks!

**Comment by dantewang** [comment]
@tinatian Search team asks to review the change, if this looks good to you, I'll forward to search team.

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by gustavolimav — APPROVED** [review]
LGTM!

**Comment by gustavolimav** [comment]
@dantewang Reviewed from here don't need to forward to @liferay-search

**Comment by lipusz** [comment]
@tinatian @dantewang Can you guys share more on the reasons why it is not only about exposing these, but also changing (increasing) the values from https://github.com/elastic/elasticsearch/blob/v7.16.3/client/rest/src/main/java/org/elasticsearch/client/RestClientBuilder.java#L53-L54 to `75/75`?

/cc @gustavolimav

**Comment by lipusz** [comment]
I was trying to get more context, though after navigating back-and-cross the linked tickets, I ended up in a dead-lock: "performance drop" after https://issues.liferay.com/browse/LPS-175666, but that ticket points to https://github.com/liferay-core-infra/liferay-portal/pull/3580, which, pretty much the same as this PR. :confused: :thinking:

**Comment by lipusz** [comment]
>The max connection config affects the performance after a recent change that makes RestHighLevelClientFactory to use the async http client and disable compression.

Where does this change come from? We have not bumped the client (it's still 7.16.3) so it must be in our code I assume, though I don't remember pushing anything to that from our side.

**Comment by lipusz** [comment]
Hello @shuyangzhou 

Could you give me and Gustavo more information about liferay@0dab85c0907cb109b8b70933c80b6e8de5ade457 and how it helps with the goal of the Core Infra Epic _Optimize startup time for both cold and warm cases._ this ticket belongs to? 

I'd feel more comfortable with the proposed changes if I had more context so to make sure it's not going to cause issues in production and existing env just to improve the "startup time".

Thanks a lot!

**Comment by lipusz** [comment]
Thanks @shuyangzhou :+1:

**Comment by lipusz** [comment]
I'll note this change on the ticket.

**Comment by lipusz** [comment]
Since Gustavo has already approved it, :+1: LGTM too.

**Comment by lipusz** [comment]
@shuyangzhou When it comes to Elasticsearch and infra stuff, I prefer to keep parity across the versions. Would you guys be up for making these changes to 7.3.x, too, once it's done and the results are also good?

**Comment by shuyangzhou** [comment]
@dantewang please have someone backport this, thanks!

**Comment by dantewang** [comment]
@lipusz 75 comes from the max-threads config in Tomcat used by Liferay benchmark. The ES http client conn pool must be equal or larger than the Tomcat max-threads.

**Comment by dantewang** [comment]
ci:forward

@tinatian Forwarding since this passes search team review and it's a simple configuration additon.

**Pull request closed without merging**
