### PR TITLE
LRQA-75659 Remove duplicate dependency since it is already covered by compileOnly

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-75659

### CODE REVIEW

**Comment by kyle-miho** [comment]
This fixes failure in com.liferay.portal.modules.ModulesStructureTest

**Comment by kyle-miho** [comment]
ci:test:sf

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
Hey @tinatian, this pr looks good to me. Thx

**Comment by tinatian** [comment]
@shuyangzhou This is good to go.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
