### PR TITLE
[TS] LPS-194611

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Requested by Tina [here](https://github.com/liferay-core-infra/liferay-portal/pull/5356#issuecomment-1692609462).

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by yuhai** [comment]
@marianoalvarosaiz, the files conflicts, please resolve them.

**Comment by marianoalvarosaiz** [comment]
@yuhai see https://github.com/liferay-core-infra/liferay-portal/pull/5456

**Pull request closed without merging**
