### PR TITLE
[Upgrade Mockito framework] LPS-153088

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR updates Mockito to major version 4 and removes the dependency on PowerMock. Thanks! (https://issues.liferay.com/browse/LPS-153088)

PowerMock appears to be abandoned and Mockito v4 adds support for static method mocking and constructor mocking which we previously needed to use PowerMock to get. We currently add mockito-core and mockito-inline to lib.(_However, Mockito-inline may be abolished when the inline mock-making feature is integrated into the default mock maker in the future. Eventually, it will be mockito-core only._ )

LPS-153088 Update to Mockito 4.5.1 and remove PowerMock in `lib`
LPS-153088 Update Mockito and remove PowerMock from `gitignore`
LPS-153088 Update Mockito and remove PowerMock in` IDE Files`
LPS-153088 **Build lib versions**
LPS-153088 Add Byte Buddy in `lib`
LPS-153088 Add Byte Buddy in .`gitignore`
LPS-153088 Add Byte Buddy in `IDE files`
LPS-153088 byte buddy **build-lib-versions**
LPS-153088 Update `test default compile gradle plugin` to Mockito 4.5.1, remove powermock plugins
LPS-153088 Change com.liferay.gradle.plugins.defaults version to 7.0.329 in  modules/build-buildscript.gradle
LPS-153088 Change com.liferay.gradle.plugins.defaults version to 7.0.329 in portal-web/build-test.gradle
LPS-153088 Remove unnecessary mockito dependencies in build.Gradle
LPS-153088 Remove **deprecated** mockito method, use **replacement** in `xxxxTest`
...
LPS-153088 Use Mockito only in `xxxxTest`  (change PowerMock.mockStatic to Mockito.mockStatic)
...
LPS-153088 Fix unit tests
LPS-153088 Fix compile error

### CODE REVIEW

**Comment by dantewang** [comment]
Hi @petershin, in this task we're working on upgrading Mockito to 4.x and removing PowerMock/PowerMockito. To apply the upgrade Janis modified the Gradle plugin in https://github.com/liferay-core-infra/liferay-portal/pull/837/commits/353a510f79857dc886c8ef98628f6320619ff651. However, we're not sure how to keep this change only for master. Could you take a look? Thanks!

**Comment by JanisZhang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/838.
add portal version check in LiferayOSGiDefaultsPlugin.java

```
if (PortalTools.PORTAL_VERSION_7_0_X.equals(portalVersion) ||
			PortalTools.PORTAL_VERSION_7_1_X.equals(portalVersion) ||
			PortalTools.PORTAL_VERSION_7_2_X.equals(portalVersion) ||
			PortalTools.PORTAL_VERSION_7_3_X.equals(portalVersion)) {
			GradleUtil.addDependency(
				project, JavaPlugin.TEST_COMPILE_CONFIGURATION_NAME,
				"org.mockito", "mockito-core", "1.10.8");

			ModuleDependency moduleDependency =
				(ModuleDependency)GradleUtil.addDependency(
					project, JavaPlugin.TEST_COMPILE_CONFIGURATION_NAME,
					"org.powermock", "powermock-api-mockito", "1.6.1");

			Map<String, String> excludeArgs = new HashMap<>();

			excludeArgs.put("group", "org.mockito");
			excludeArgs.put("module", "mockito-all");

			moduleDependency.exclude(excludeArgs);

			GradleUtil.addDependency(
				project, JavaPlugin.TEST_COMPILE_CONFIGURATION_NAME,
				"org.powermock", "powermock-module-junit4", "1.6.1");
		}
		else {
			GradleUtil.addDependency(
				project, JavaPlugin.TEST_COMPILE_CONFIGURATION_NAME,
				"org.mockito", "mockito-core", "4.5.1");

			GradleUtil.addDependency(
				project, JavaPlugin.TEST_COMPILE_CONFIGURATION_NAME,
				"org.mockito", "mockito-inline", "4.5.1");
		}
```

**Comment by dantewang** [comment]
@petershin We found a way, see https://github.com/liferay-core-infra/liferay-portal/pull/837#issuecomment-1137017297, please let us know if this is not enough, thanks!

**Comment by dantewang** [comment]
ci:close

**Pull request closed without merging**
