### PR TITLE
[TS] LPP-46001 > LPS-158806 When sending an invalid redirect query parameter during password reset, the password is included in the response

### PR DESCRIPTION
**Pull request by ces-sontruong**
Hi team,
This is resent based on the closed PR #1157
Ticket: [LPS- 158806](https://issues.liferay.com/browse/LPS-158806).

cc:@TaiPhamLR

### CODE REVIEW

**Comment by tinatian** [comment]
@sontruongces In your commit message, you said "**When sending an invalid redirect query parameter during password reset**", but your test did not show anything about valid/invalid, I am confused.

Tina.

**Comment by tinatian** [comment]
@sontruongces Please either reword your commit message to give me more information about your change, or refine your test show me why you made the change.

Tina.

**Comment by sontruongces** [comment]
@tinatian, thanks for your feedback. I updated the commit message.

**Comment by tinatian** [comment]
@sontruongces You changed your commit message, but the description of your ticket still talking about valid/invalid, this is still confusing, please make sure you describe your issues correctly and everything is consistent.

I am still confused when and why you need to remove these parameters.


Tina.

**Comment by TaiPhamLR** [comment]
Hi @tinatian, thanks for your comments. I'm in charge of this fix. 
The invalid redirect query parameter is just a condition to backend call [PortalImpl#copyRequestParameters](https://github.com/liferay-core-infra/liferay-portal/blob/c2bfedae1222de622f893372b9cee2bd70ebea23/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L848) 
I think for any cases password1 and password2 should not be sent back from the backend to UI cause of security reasons. I created only unit test cases to test for that method. So I ignored the valid/invalid redirect query parameter. Is that make sense? Please give me your comments. Thanks,
Tai.

**Comment by TaiPhamLR** [comment]
Hi @tinatian, thanks for your feedback.
The method  [PortalImpl#copyRequestParameters](https://github.com/liferay-core-infra/liferay-portal/blob/c2bfedae1222de622f893372b9cee2bd70ebea23/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L848) of source code is using deprecated `getParameterNames`, `getParameterValues` ([here](https://github.com/liferay-core-infra/liferay-portal/blob/c2bfedae1222de622f893372b9cee2bd70ebea23/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L877-L886)). My test cases are just using the Mockito function to mock these methods. I can not avoid using deprecated methods in this case. Could you help me check again? Thanks,
Tai.

**Comment by tinatian** [comment]
@julschong Please take this over. 

Thanks.
Tina.

**Comment by julschong** [comment]
ci:reopen

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/1362

**Pull request closed without merging**
