### PR TITLE
[Remove unused field] LPS-199019 commerce-inventory-service

### PR DESCRIPTION
**Pull request by JanisZhang**
Remove unused reference fields in class `CommerceInventoryServiceUpgradeStepRegistrator`
https://liferay.atlassian.net/browse/LPS-199019

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by JanisZhang** [comment]
Thanks @Kvale1733 !

**Comment by dantewang** [comment]
@JanisZhang Can you double check SF? It's the same file you modified.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
Ah.. I just noticed. force-pushed, I only execute formatsource, no need to rerun the test. thanks @dantewang !

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142187

cc @shuyangzhou

**Pull request closed without merging**
