### PR TITLE
[Portal service extender] LPS-170709

### PR DESCRIPTION
**Pull request by vicnate5**
From https://github.com/liferay-core-infra/liferay-portal/pull/2729#issue-1494049633

@yuhai @zhangyan0701 @kyle-miho

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:service-builder

**Comment by vicnate5** [comment]
ci:test:backend

**Comment by zhangyan0701** [comment]
There is a failure looks related:
Below error occurs in DBPartition integration tests:
```
     [exec] com.liferay.portal.db.partition.test.DBPartitionUtilTest > testAddDBPartition STARTED
[beanshell] 2022-12-15 03:48:31.894 ERROR [com.liferay.portal.db.partition.test-executor-thread][DBPartitionUtil:544] Unable to get session character set encoding
[beanshell] java.sql.SQLSyntaxErrorException: Table 'performance_schema.session_variables' doesn't exist
```

Full console:
https://testray.liferay.com/reports/production/logs/2022-12/test-1-27/test-portal-acceptance-pullrequest(master)/6234/modules-integration-service-builder-jdk8/3/9/jenkins-console.txt.gz?authuser=0

@yuhai Could you please take a look at this error? Thanks!

**Comment by zhangyan0701** [comment]
But the are some issues of the service builder tests:
1. All service builder integration failed due to error:
`org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.tools.service.builder.test.test [1505]   Unresolved requirement: Import-Package: com.liferay.portal.tools.service.builder.test.exception`
Looks like the service builder test modules are needed.

2. I noticed that the service builder integration tests were not running in ci:test:relevant modules-integration-service-builder-jdk8 test batch.

I made some additional updated and resend in https://github.com/liferay-core-infra/liferay-portal/pull/2762.

**Pull request closed without merging**
