### PR TITLE
LPS-144001 Remove jfreechats and jcommon

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by rafaprax** [comment]
Hey @vicnate5, 

Can you please check the test results?
 
Thx

**Comment by vicnate5** [comment]
@koor4356 can you check this one?

**Comment by koor4356** [comment]
Okay, I will check after LPS-142278. Thanks!

**Comment by koor4356** [comment]
@guilhermedcamacho, @tinatian, @rafaprax, @vicnate5 
These tests are uniquely failing on this PR.
Logs and testray links are listed below:

-  https://testray.liferay.com/home/-/testray/case_results/1591808775?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1591806577%26testrayRunId%3D1591806628%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc
- https://testray.liferay.com/reports/production/logs/2021-12/test-1-26/test-portal-acceptance-pullrequest(master)/1101/functional-upgrade-tomcat90-mysql57-jdk8/0/11/jenkins-console.txt.gz
- `ERROR [main][MainServlet:264] java.util.ConcurrentModificationException
 [parallel] java.util.ConcurrentModificationException: null
 [parallel] 	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1211) ~[?:1.8.0_121]
 [parallel] 	at java.util.TreeMap$KeyIterator.next(TreeMap.java:1265) ~[?:1.8.0_121]
 [parallel] 	at java.util.AbstractCollection.toArray(AbstractCollection.java:141) ~[?:1.8.0_121]
 [parallel] 	at java.util.ArrayList.addAll(ArrayList.java:577) ~[?:1.8.0_121]
 [parallel] 	at com.liferay.portal.kernel.util.ListUtil.fromCollection(ListUtil.java:281) ~[portal-kernel.jar:?]
 [parallel] 	at com.liferay.portal.model.BaseModelHintsImpl.getModels(BaseModelHintsImpl.java:183) ~[portal-impl.jar:?]
 [parallel] 	at com.liferay.portal.kernel.model.ModelHintsUtil.getModels(ModelHintsUtil.java:54) ~[portal-kernel.jar:?]
 [parallel] 	at com.liferay.portal.service.impl.ClassNameLocalServiceImpl.checkClassNames(ClassNameLocalServiceImpl.java:65) ~[portal-impl.jar:?]
 [parallel] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
 [parallel] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
 [parallel] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
 [parallel] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
 [parallel] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
 [parallel] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69) ~[portal-impl.jar:?]
 [parallel] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
 [parallel] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
 [parallel] 	at com.sun.proxy.$Proxy47.checkClassNames(Unknown Source) ~[?:?]`



These tests fail UI assertion. This could be actually a bug or the path locator has changed.

- https://testray.liferay.com/home/-/testray/case_results/1591807248?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1591806577%26testrayRunId%3D1591806628%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc

- https://testray.liferay.com/home/-/testray/case_results/1591807253?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1591806577%26testrayRunId%3D1591806628%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@koor4356 Can you verify these issues locally?

If they are reproducible locally, please provide manual steps to reproduce.

I triggered a bundle build here.

**Comment by koor4356** [comment]
I am not able to start up bundle. So I am able not to confirm the above issues locally.

`ERROR [main][ModuleFrameworkImpl:1336] Missing /Users/malei/dev/project/github/bundles/tomcat-9.0.56/webapps/ROOT/WEB-INF/shielded-container-lib/com.liferay.portal.osgi.web.jasper.plugins.taglib.jar
2021-12-17 20:50:32.902 ERROR [Portal Spring Init Thread][ContextLoader:225] Context initialization failed
java.lang.NoClassDefFoundError: com/liferay/osgi/service/tracker/collections/list/ServiceTrackerListFactory
	at com.liferay.portal.dao.orm.hibernate.SessionFactoryImpl.<init>(SessionFactoryImpl.java:156) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopConfigurableApplicationContextConfigurator$AopBeanFactoryPostProcessor._getPlatformTransactionManager(AopConfigurableApplicationContextConfigurator.java:222) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopConfigurableApplicationContextConfigurator$AopBeanFactoryPostProcessor.postProcessBeanFactory(AopConfigurableApplicationContextConfigurator.java:123) ~[portal-impl.jar:?]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:291) ~[spring-context.jar:5.2.10.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:132) ~[spring-context.jar:5.2.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:707) ~[spring-context.jar:5.2.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:533) ~[spring-context.jar:5.2.10.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401) ~[spring-web.jar:5.2.10.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292) ~[spring-web.jar:5.2.10.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103) ~[spring-web.jar:5.2.10.RELEASE]
	at com.liferay.portal.spring.context.PortalContextLoaderListener.lambda$contextInitialized$1(PortalContextLoaderListener.java:287) ~[portal-impl.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.liferay.osgi.service.tracker.collections.list.ServiceTrackerListFactory
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1407) ~[catalina.jar:9.0.56]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1215) ~[catalina.jar:9.0.56]
	at com.liferay.shielded.container.internal.ShieldedContainerClassLoader.findClass(ShieldedContainerClassLoader.java:79) ~[com.liferay.shielded.container.impl.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 13 more`

**Comment by vicnate5** [comment]
@koor4356 If you cannot use the bundle included, just fetch the branch and compile locally.

**Comment by koor4356** [comment]
@vicnate5 @tinatian 
I have fetched and compiled this PR. I was not able to reproduce any of those issues locally. I believe the PR is good to go.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/111353

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
