### PR TITLE
LPS-154577 Remove jaxrs-api.jar and jersey-common.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:jdk11

**Comment by rafaprax** [comment]
I'm fixing test compile issue

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:acceptance

**Comment by vicnate5** [comment]
ci:help

**Comment by vicnate5** [comment]
ci:test:jdk11

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:jdk11

**Comment by rafaprax** [comment]
Hey @catarineaguiar, can you please help me scan these test results?

Thx

**Comment by rafaprax** [comment]
Hey @catarineaguiar, I just rewrote the last commit message. So, the results are still valid. Thx

**Comment by catarineaguiar** [comment]
@rafaprax the bundle worked well on JDK11 and no regressions were found.

**Comment by rafaprax** [comment]
Hey @shuyangzhou, this pr is ready for your review. Thx

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/118292

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
