### PR TITLE
LPS-166374 Remove immediate from Echo's team modules part 1

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@rafaprax formatting issues:

```
     [java] java.lang.Exception: Found 27 formatting issues:
     [java] 1: ./modules/apps/layout/layout-admin-web-test/src/testIntegration/java/com/liferay/layout/admin/web/internal/portlet/LayoutAdminWebTestPortlet.java expected:<...so
     [java]  */
     [java] @Component(
     [java]   []property = \{
     [java]     "com....> but was:<...so
     [java]  */
     [java] @Component(
     [java]   [
     [java]   ]property = \{
     [java]     "com....>
     [java] 2: ./modules/apps/layout/layout-content-page-editor-web-test/src/testIntegration/java/com/liferay/layout/content/page/editor/web/internal/portlet/LayoutContentPageEditorWebTestPortlet.java expected:<...da
     [java]  */
     [java] @Component(
     [java]   []property = \{
     [java]     "com....> but was:<...da
     [java]  */
     [java] @Component(
     [java]   [
     [java]   ]property = \{
     [java]     "com....>
     [java] 3: ./modules/apps/layout/layout-test/src/testIntegration/java/com/liferay/layout/test/LayoutTestPortlet.java expected:<...er
     [java]  */
     [java] @Component(
     [java]   []property = \{
     [java]     "com....> but was:<...er
     [java]  */
     [java] @Component(
     [java]   [
     [java]   ]property = \{
     [java]     "com....>
     [java] 4: ./modules/apps/layout/layout-type-controller/layout-type-controller-collection/src/main/java/com/liferay/layout/type/controller/collection/internal/model/CollectionLayoutTypeAccessPolicy.java expected:<...er
     [java]  */
     [java] @Component(
     [java]   []property = "layout.t...> but was:<...er
     [java]  */
     [java] @Component(
     [java]   [
     [java]   ]property = "layout.t...>
     [java] 5: ./modules/apps/layout/layout-type-controller/layout-type-controller-collection/src/main/java/com/liferay/layout/type/controller/collection/internal/layout/type/controller/CollectionPageLayoutTypeController.java expected:<...er
     [java]  */
     [java] @Component(
     [java]   []property = "layout.t...> but was:<...er
     [java]  */
     [java] @Component(
     [java]   [
     [java]   ]property = "layout.t...>
     [java] 6: ./modules/apps/layout/layout-type-controller/layout-type-controller-collection/src/main/java/com/liferay/layout/type/controller/collection/internal/portlet/action/AddCollectionItemMVCActionCommand.java expected:<...??n
     [java]  */
     [java] @Component(
     [java]   []property = \{
     [java]     "java...> but was:<...??n
     [java]  */
     [java] @Component(
     [java]   [
     [java]   ]property = \{
```

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
@rafaprax no regressions found.

**Comment by rafaprax** [comment]
Hey @shuyangzhou, this pr is ready for your review. Thx

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
