### PR TITLE
[TS] LPS-200940 Add option to skip unwrapping the request

### PR DESCRIPTION
**Pull request by balazssk**
Previously reviewed by echo: https://github.com/liferay-echo/liferay-portal/pull/14323

Motivation
=======
During Content Page indexing, [RuntimeTag](https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/portletext/RuntimeTag.java#L187) unwraps the `companyHttpServletRequest` created in [LayoutServiceContextHelperImpl#_getHttpServletRequest](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/util/LayoutServiceContextHelperImpl.java#L691) removing all the request overrides set up for index rendering.
This unwrapping was introduced as part of https://liferay.atlassian.net/browse/LPSA-39344
[LPS-200940](https://liferay.atlassian.net/browse/LPS-200940)

Proposed Solution
========
By adding the option to skip this request unwrapping we should be able render widgets sufficiently to create a search document from them.

Steps to Verify
========
1. Go to Content & Data > Web Content
2. Click the blue + to add a new Web Content
3. Add an easily recognisable text to its content, like “unique” and press Publish
4. Create a content page
5. Add a Web Content Display widget
6. Select the “unique” Web Content to be displayed in the widget
7. Press Publish
8. Use the page’s search bar to look for “unique”
9. 2 results should appear: the web content and the page
11. Go To Control Panel > Search
12. Switch to the Index actions tab
13. Looks for “Page (com.liferay.portal.kernel.model.Layout)”
14. Press the Reindex button next to it, accept the prompt
15. Return to the page and use the search bar to look for “unique”

**Expected behavior:** 2 results should appear: the web content and the page
**Actual behavior:** Only the web content appears

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by zhangyan0701** [comment]
Many automation tests failed due to regression bug on upstream: https://liferay.atlassian.net/browse/LPS-201614. Manual testing  is also blocked by it. It's better to re-run tests once it got fixed.

**Comment by Kvale1733** [comment]
Fix is merged. Rerunning tests.

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
@balazssk No regressions found. Testing passed following the manual steps.

**Comment by tinatian** [comment]
@balazssk The fix does not sound right to me. 

It is an issue about content page indexing, but you are modifying framework level (RuntimeTag) to provide backdoor for this special case, this is not a right way to fix the issue.

Could you please try to fix this issue in content page scope? Basically the problem is a parameter passing, you need to pass some parameters about index by request, I believe there should be other ways to pass the parameters to the place you are using it.

Please resend.

Thanks.
Tina.

**Pull request closed without merging**
