### PR TITLE
LPD-38015 Modify custom fields infrastructure to support hide model from the user interface

### PR DESCRIPTION
**Pull request by Mikellorza**
Hi @tinatian ,

I am moving test from portlet-test to portal-kernel-test, you can see it in the last commit because of https://github.com/brianchandotcom/liferay-portal/pull/155159#issuecomment-2412408697.

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-38015

Hi team,

Working on deprecating wiki from the portal, we have the need to hide wiki from custom field creation. So, this PR include all necessary changes to support disable CustomAttributesDisplay's in order to do not show a model from the custom field creation.

We are only hiding wiki behind a feature flag and for that I need the component enabled always. The use case is that some customers that we are using wiki, they can normally use wiki knowing that they should change wiki to objects because someday will disappear.

# How am I fixing it?

 Hiding CustomAttributesDisplay from getCustomAttributesDisplays List if it has a feature flag and this feature flag is not enabled

# How can you verify that it works?

Run included tests.

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:forward:force

**Comment by tinatian** [comment]
ci:report:42796877

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/155203

**Pull request closed without merging**
