### PR TITLE
[Bug Fix]LPS-150966 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test result once it is finished.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
@tinatian no regressions found.

**Comment by drewbrokke** [comment]
@tinatian any update on this one? Is it ready to forward or does it need additional work?

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
