### PR TITLE
[Bug Fix]LPS-139889 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
FYI @ericyanLr

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@kyle-miho can you check this one?

**Comment by kyle-miho** [comment]
@tinatian the only failures seems to be that jdk11 is failing to start portal with this pr, no other unique failures. If you think that this pr cant break jdk11 then it should be fine to go, im going to rerun the tests to be safe

**Comment by kyle-miho** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
@kyle-miho JDK11 smoke passed in the Relevant results, this is good to go @tinatian

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10484

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
