### PR TITLE
Lps 151272 4 12 1

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by vicnate5** [comment]
@zhangyan0701 can you check this one?
https://test-1-1.liferay.com/job/generate-testray-csv/141/
https://test-1-1.liferay.com/job/generate-testray-csv/142/

**Comment by zhangyan0701** [comment]
The failures are unrelated.

**Comment by vicnate5** [comment]
@shuyangzhou Can this one be prioritized since it is FP5?

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116143

**Pull request closed without merging**
