### PR TITLE
LPS-165845 Remove "immediate = true" from Headless

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Errors occur during portal startup:
```
[beanshell] 2022-10-18 08:21:36.851 ERROR [main][ROOT:56] bundle org.apache.felix.scr:2.1.14.LIFERAY-PATCHED-5 (72)Circular reference detected trying to get service {com.liferay.portal.vulcan.resource.OpenAPIResource}={component.id=1097, component.name=com.liferay.portal.vulcan.internal.resource.OpenAPIResourceImpl, service.id=5031, service.scope=bundle, service.bundleid=343}
[beanshell]  stack of references: ServiceReference: {com.liferay.portal.osgi.debug.internal.osgi.commands.SystemCheckOSGiCommands}={osgi.command.function=check, component.id=809, component.name=com.liferay.portal.osgi.debug.internal.osgi.commands.SystemCheckOSGiCommands, service.id=13451, osgi.command.scope=system, _moduleServiceLifecycle.target=(module.service.lifecycle=system.check), service.scope=bundle, service.bundleid=283}
[beanshell] ServiceReference: {com.liferay.portal.vulcan.resource.OpenAPIResource}={component.id=1097, component.name=com.liferay.portal.vulcan.internal.resource.OpenAPIResourceImpl, service.id=5031, service.scope=bundle, service.bundleid=343}
[beanshell] ServiceReference: {com.liferay.portal.vulcan.jaxrs.JaxRsResourceRegistry}={component.id=1095, component.name=com.liferay.portal.vulcan.internal.jaxrs.JaxRsResourceRegistryImpl, service.id=826, service.scope=bundle, service.bundleid=343}
[beanshell] ServiceReference: {com.liferay.headless.admin.user.internal.resource.v1_0.OpenAPIResourceImpl}={api.version=v1.0, osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Headless.Admin.User), component.id=1278, component.name=com.liferay.headless.admin.user.internal.resource.v1_0.OpenAPIResourceImpl, service.id=5032, service.scope=bundle, osgi.jaxrs.resource=true, service.bundleid=397}
[beanshell] 
[beanshell] java.lang.Exception: stack trace
```

Full console log:
https://testray.liferay.com/reports/production/logs/2022-10/test-1-29/test-portal-acceptance-pullrequest(master)/5083/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
Hey @shuyangzhou, this pull is ready to go!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/124877

**Pull request closed without merging**
