### PR TITLE
LPS-161850

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:reevaluate:1357401_2786

**Comment by rotty3000** [comment]
I have to fix semantic version change. will do that shortly.

**Comment by zhangyan0701** [comment]
Semantic Versioning issue in portal-instances-api:
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/portal-instances/portal-instances-api] FAILED
     [exec]     java.lang.AssertionError: [Baseline Warning] Bundle Version Change Recommended: 7.2.0
```

Full console log:
https://testray.liferay.com/reports/production/logs/2022-10/test-1-35/test-portal-acceptance-pullrequest(master)/2786/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@rotty3000 No regressions found.

**Comment by rotty3000** [comment]
ci:forward

**Pull request closed without merging**
