### PR TITLE
Lps 190899 8 24

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:data-integration

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
@dantewang Please, resolve conflicts.

regression found:
```
     [exec] > Task :apps:portal-scheduler:portal-scheduler-quartz:processTestResources NO-SOURCE
     [exec] Gradle build finished at 2023-08-25 05:36:39.515.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-scheduler/portal-scheduler-quartz/src/test/java/com/liferay/portal/scheduler/quartz/internal/QuartzSchedulerEngineTest.java:531: error: cannot find symbol
     [exec] 					new Tuple(jobDetail, null, TriggerState.UNSCHEDULED));
     [exec] 					                                       ^
     [exec]   symbol:   variable UNSCHEDULED
     [exec]   location: class com.liferay.portal.kernel.scheduler.TriggerState
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-08/test-1-32/test-portal-acceptance-pullrequest(master)/1714/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
