### PR TITLE
[Remove Blocking usages]LPS-192590 portal-search | ReindexSingleIndexerBackgroundTaskExecutor

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:help

**Comment by W2jx** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(8/7 8:38)

**Comment by W2jx** [comment]
no conflicts(8/9 17:17)

**Comment by W2jx** [comment]
no conflicts(8/10 17:08)

**Comment by dantewang** [comment]
ci:test:stable

**Comment by W2jx** [comment]
ci:test:stable

**Comment by tinatian** [comment]
@W2jx Pleas remember to remove QA passed flag to trigger the scan of new test results.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
no regressions

**Comment by W2jx** [comment]
see https://github.com/liferay-core-infra/liferay-portal/pull/5288

**Pull request closed without merging**
