### PR TITLE
LPS-144892

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This PR is to fix https://issues.liferay.com/browse/LPS-144892
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result again, please?

Thanks
Jeff

**Comment by tinatian** [comment]
@jeffwu0724 For your comment "set schemaPattern to "PUBLIC", which is the default pattern for the tables created. We need to narrow down the range of the tables due to the update in "h2database/h2database@875feae" since h2 version 2.0.202."

Why "h2database/h2database@875feae" caused the difference?

Tina

**Comment by jeffwu0724** [comment]
> @jeffwu0724 For your comment "set schemaPattern to "PUBLIC", which is the default pattern for the tables created. We need to narrow down the range of the tables due to the update in "h2database/h2database@875feae" since h2 version 2.0.202."
> 
> Why "h2database/h2database@875feae" caused the difference?
> 
> Tina

Hi Tina,
This is based on what I saw from the source codes of versions 2.0.202 and 1.4.193. 
**2.0.202**
In https://github.com/h2database/h2database/commit/875feaed3b338c7cd77c91db6ff4e252ff728f78, we can see line 438 in getTables() in DatabseMetaLocal.java. When we input a null schemaPattern as parameter for getSchemasForPattern(), it will trigger getAllSchemas(), and during the initial, it will add both "INFORMATION_SCHEMA" and "PUBLIC" as the schema type. Therefore, when we get the results for the database, it will return both "USERS - INFORMATION_SCHEMA" and "USER_ - PUBLIC". 
**1.4.193**
However, before this version, it handles this situation in "getSchemaPattern()". If we input a null schemaPattern, it will only add "PUBLIC" as the schemaPattern. 
Please correct me if I make any mistakes here. Thanks!

**Comment by tinatian** [comment]
@jeffwu0724 In this case, please modify your commit message to

 "set schemaPattern to "PUBLIC" to make sure the behavior is same as before, null schemaPattern was translated to "PUBLIC" at 1.4.193, but it is translated to "INFORMATION_SCHEMA" and "PUBLIC" at 2.0.202 due to "h2database/h2database@875feae" "

**Comment by catarineaguiar** [comment]
@jeffwu0724 will you re-run the ci to analyze the new changes?

**Comment by jeffwu0724** [comment]
@catarineaguiar I think it should be ok, I just changed the commit message, and did not touch any of the code. Thanks for asking!

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions were found.

**Comment by tinatian** [comment]
@jeffwu0724 Code conflicts, please rebase.

Tina

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result again, please?

Thanks
Jeff

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/117678

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
