### PR TITLE
Lps 176754 3 2 4

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
SF failure is real, waiting for the removal of stream to be merged first

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Could you please prioritize the scan of this pull?

Thanks.
Tina

**Comment by vicnate5** [comment]
Missing the testray import here, so this is going to be difficult to analyze. Asked CI team for help.

**Comment by vicnate5** [comment]
@tinatian Regressions here. and a rebase is needed.

**New tests added in this PR that failed:**
1. https://testray.liferay.com/home/-/testray/case_results/2221776333
2. https://testray.liferay.com/home/-/testray/case_results/2221774128
3. https://testray.liferay.com/home/-/testray/case_results/2221776328

**Existing integration tests that failed here:**
1. https://testray.liferay.com/home/-/testray/case_results/2221774291
2. https://testray.liferay.com/home/-/testray/case_results/2221774265

[Clustering test portlet automation failure](https://testray.liferay.com/home/-/testray/case_results/2221765116) - steps to reproduce
1. Start 2 node cluster
2. Login to first node
3. Go to Control Panel > Server Admin > Log Levels
4. Add new log category `com.liferay.portal.cluster.multiple.sample.web.internal` - DEBUG
5. Deploy cluster sample web `modules/apps/portal/portal-cluster-multiple-sample-web` to first node

**Expected Result:**
```
DEBUG [liferay/scheduler_dispatch-12][ClusterSampleMessageListener:63] Received message at 1677752716678
```

**Actual Result::**
No debug message for message recieved. 

There is also a failure in the DB partition clustering test. I can still reproduce without DB partition, but I cannot reproduce manually (only with the automation). I can spend more time on this if needed, but I suspect that resolving the other cluster test issues might resolve this one. https://testray.liferay.com/home/-/testray/case_results/2221765187

CC @Kvale1733

**Pull request closed without merging**
