### PR TITLE
[Phase 1][Remove Stream/Optional usage] LPS-173075 remove_stream_and_optional_in_segments-service

### PR DESCRIPTION
**Pull request by dantewang**
@jeffwu0724

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:tango

**Comment by dantewang** [comment]
@zhangyan0701 Could you prioritize this PR? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
