### PR TITLE
LPS-168821

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by Kvale1733** [comment]
@marianoalvarosaiz No regressions found.

**Comment by dantewang** [comment]
@zhangyan0701 Should this be forwarded to dev tools team?

**Comment by zhangyan0701** [comment]
ci:test:acceptance

**Comment by dantewang** [comment]
@petershin

**Comment by zhangyan0701** [comment]
The test failures are unrelated.

@dantewang I am not completely sure, but it may belong to Dev Tools > Cradle plugin component.

**Comment by petershin** [comment]
See https://github.com/petershin/liferay-portal/pull/1852

**Comment by petershin** [comment]
ci:close

**Pull request closed without merging**
