### PR TITLE
LPS-165622 update Jackson Databind to 2.13.4.2

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-165622.
Thanks for checking!

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
fixed code conflict

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@jeffwu0724 Please rebase

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
fixed the code conflict

**Comment by zhangyan0701** [comment]
Hi @jeffwu0724 Please resolve the conflict and rebase.

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
fixed code conflict

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126679

**Pull request closed without merging**
