### PR TITLE
[Optional References]LPS-186277 Convert the Optional references to static references using…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-186277

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
Sorry, forget to trigger the test for startup

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
