### PR TITLE
LPS-170848 Use Dom4jDocUtil toString instead of Dom4jUtil toString for JavadocFormatter

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by vicnate5** [comment]
@kyle-miho can you check if we have a test for this?

**Comment by kyle-miho** [comment]
There is just SF and javadoc-jdk8 from searching. Javajoc-jdk8 batch is in only in acceptance as of now, I will cherry-pick this pr and try to run that batch to test in a seperate pr @julschong @vicnate5

**Comment by kyle-miho** [comment]
https://github.com/kyle-miho/liferay-portal/pull/601

**Comment by kyle-miho** [comment]
https://testray.liferay.com/home/-/testray/case_results/2125178937?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseTypeId%3D556778857%26testrayBuildId%3D2125178764%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc

**Comment by kyle-miho** [comment]
Javadoc JDK8 batch passed, It just runs ant compile and ant doc, not sure how thorough java doc changes need to be tested, but this is all we have as of now and it passed on CI

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
I re-ran relevant to prove the semVar fix works

**Comment by julschong** [comment]
Tested local again, failed gw formatJavadoc because `ClassNotFound error for petra.io.unsync.UnsyncByteArrayOutputStream
`
Resolved the issue and pushed again

My testing step is:
1. ant all first to update util-java
2. cd to `modules/util/javadoc-formatterr` -> `gw installCache`
3. temporarily add a build gradle dep to account-api: `javadocFormatter group: "com.liferay", name: "com.liferay.javadoc.formatter", version: "1.0.38"` so that it will grab the new version we put in gradle cache
4.

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@julschong Please do all the three usages of Dom4jUtil in one pull, this way, it is not going to be copy, but a move. Just doing copy does not make sense.

Tina.

**Pull request closed without merging**
