### PR TITLE
LPS-183594 move portal-upload to modules part 3

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Shuyang,

Resent: https://github.com/liferay-core-infra/liferay-portal/pull/5635
In this PR, I am trying to move all the portal-upload usage from portal-impl to modules.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@jeffwu0724 please, resolve conflicts and re-run relevant and sf.

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:object

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:stop

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:object

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@jeffwu0724 

1) These 3 tests seem to have the same issue
com.liferay.saml.opensaml.integration.internal.servlet.profile.XMLSecurityTest
com.liferay.saml.opensaml.integration.internal.servlet.profile.WebSsoProfileIntegrationTest
com.liferay.saml.opensaml.integration.internal.servlet.profile.SingleLogoutProfileIntegrationTest

```
[exec] com.liferay.saml.opensaml.integration.internal.servlet.profile.XMLSecurityTest > testXMLBombQuadraticBlowup FAILED
[beanshell]      [exec]     java.lang.Exception: Unexpected exception, expected<org.opensaml.messaging.decoder.MessageDecodingException> but was<java.lang.NoClassDefFoundError>
[beanshell]      [exec]         at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
[beanshell]      [exec]         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[beanshell]      [exec]         at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[beanshell]      [exec]         at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]         at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[beanshell]      [exec]         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
```

```
  Caused by:
[beanshell]      [exec]         java.lang.NoClassDefFoundError: Could not initialize class com.liferay.saml.opensaml.integration.internal.velocity.VelocityEngineFactory
[beanshell]      [exec]             at com.liferay.saml.opensaml.integration.internal.binding.SamlBindingProvider._createSamlBindings(SamlBindingProvider.java:49)
[beanshell]      [exec]             at com.liferay.petra.concurrent.DCLSingleton.getSingleton(DCLSingleton.java:39)
[beanshell]      [exec]             at com.liferay.saml.opensaml.integration.internal.binding.SamlBindingProvider.getSamlBinding(SamlBindingProvider.java:33)
[beanshell]      [exec]             at com.liferay.saml.opensaml.integration.internal.servlet.profile.BaseProfile.sendSamlMessage(BaseProfile.java:425)
[beanshell]      [exec]             at com.liferay.saml.opensaml.integration.internal.servlet.profile.WebSsoProfileImpl.doSendAuthnRequest(WebSsoProfileImpl.java:598)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-36/test-portal-acceptance-pullrequest(master)/4242/modules-unit-jdk8/0/7/jenkins-console.txt.gz?authuser=0)

2) Semver issues
```
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.util                            MAJOR      55.0.0     55.0.0     56.0.0     VERSION INCREASE REQUIRED
[beanshell] 	>   class      com.liferay.portal.util.PortalImpl
[beanshell] 		-   method     getUploadPortletRequest(javax.portlet.PortletRequest)
[beanshell] 			-   return     com.liferay.portal.kernel.upload.UploadPortletRequest
[beanshell] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest)
[beanshell] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
[beanshell] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest,int,java.lang.String)
[beanshell] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
[beanshell] 
     [echo] 
     [echo] ##
     [echo] ## /opt/dev/projects/github/liferay-portal/baseline-reports/portal-kernel.log
     [echo] ##
     [echo] 
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.kernel.util                     MAJOR      66.0.0     66.0.0     67.0.0     VERSION INCREASE REQUIRED
[beanshell] 	>   class      com.liferay.portal.kernel.util.PortalUtil
[beanshell] 		-   method     getUploadPortletRequest(javax.portlet.PortletRequest)
[beanshell] 			-   access     static
[beanshell] 			-   return     com.liferay.portal.kernel.upload.UploadPortletRequest
[beanshell] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest)
[beanshell] 			-   access     static
[beanshell] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
[beanshell] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest,int,java.lang.String)
[beanshell] 			-   access     static
[beanshell] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
[beanshell] 	>   interface  com.liferay.portal.kernel.util.Portal
[beanshell] 		-   method     getUploadPortletRequest(javax.portlet.PortletRequest)
[beanshell] 			-   access     abstract
[beanshell] 			-   return     com.liferay.portal.kernel.upload.UploadPortletRequest
[beanshell] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest)
[beanshell] 			-   access     abstract
[beanshell] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
[beanshell] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest,int,java.lang.String)
[beanshell] 			-   access     abstract
[beanshell] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-35/test-portal-acceptance-pullrequest(master)/4645/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
