### PR TITLE
LPS-157255 Remove web portal dir property

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina, @tinatian

this is resubmitted from #1047
Fixed the unit test CusomJspBagRegistryUtilTest

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar
Hi Catarine,
This is resubmitted to fix this issue: https://github.com/liferay-core-infra/liferay-portal/pull/1047#issuecomment-1176702308
could you please help me scan the result again?
Thank you!

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by julschong** [comment]
@tinatian Hi Tina, 
Could you please help me review this pull please?
Thank you!

**Comment by tinatian** [comment]
@julschong Please refine the test logic.

Thanks
Tina

**Pull request closed without merging**
