### PR TITLE
[SampleSQLBuilder]LPS-160327

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-160327

### CODE REVIEW

**Comment by slnn** [comment]
Hi @catarineaguiar 

Could you help to scan test results when the tests are finished?

Thanks
Lily

**Review by dantewang — APPROVED** [review]
@tinatian This change is made as per BChan's request and following the pattern he provided.

**Comment by catarineaguiar** [comment]
@slnn no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121708

**Pull request closed without merging**
