### PR TITLE
LPS-159031 R/W data source 2-9

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:smoke

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by Kvale1733** [comment]
Running the functional tests here: https://github.com/Kvale1733/liferay-portal/pull/270

**Comment by Kvale1733** [comment]
All functional tests also pass.

**Comment by dantewang** [comment]
ci:test:smoke

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Removing QA Passed since I force-pushed some minor changes.

**Comment by dantewang** [comment]
The sem ver error can be ignored, since it's due to upstream, and I dropped the temp fix commit.

**Comment by Kvale1733** [comment]
Running functional tests here: https://github.com/Kvale1733/liferay-portal/pull/272

**Comment by Kvale1733** [comment]
@dantewang No regressions. Functional tests pass. Just need to rebase and it should be good to go.

**Comment by tinatian** [comment]
@zhangyan0701 Could you please rebase ?

Thanks.
Tina

**Comment by dantewang** [comment]
Closing this one as there's conflict in function test case; @zhangyan0701 please just resend after rebased. Thanks.

**Comment by zhangyan0701** [comment]
@tinatian @dantewang 

Resent here: https://github.com/liferay-core-infra/liferay-portal/pull/3471.

**Pull request closed without merging**
