### PR TITLE
[PortalInstances-initCompany()]Lps 200558 12 6

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-200558

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
Forced push to resolve conflicts

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@slnn The format of breaking change report in https://github.com/liferay-core-infra/liferay-portal/pull/6275/commits/9dbb338c84b0743f5343e056749fa7d21fc1f5b0 needs to be updated.

**Comment by dantewang** [comment]
@slnn Please trigger any test that QA ran in your previous PRs. Thanks!

**Comment by slnn** [comment]
> @slnn The format of breaking change report in [9dbb338](https://github.com/liferay-core-infra/liferay-portal/commit/9dbb338c84b0743f5343e056749fa7d21fc1f5b0) needs to be updated.

Done

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:clustering

**Comment by slnn** [comment]
ci:test:sf

**Review by dantewang — APPROVED** [review]

**Comment by slnn** [comment]
No regression found.

**Pull request closed without merging**
