### PR TITLE
[Remove unused field] LPS-200575 Remove unused reference field in calsses LayoutReportsProductNavigationControlMenuEntry, DisplayPageLayoutTypeController and LayoutUtilityPageEntryLocalServiceImpl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(11/2 8:14)

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(11/3 8:52)

**Comment by W2jx** [comment]
Hi @dantewang , I also double checked this PR, and the file `source-formatter.properties` will not conflict with https://github.com/liferay-core-infra/liferay-portal/pull/5936 and https://github.com/liferay-core-infra/liferay-portal/pull/5934.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143180

cc @shuyangzhou

**Pull request closed without merging**
