### PR TITLE
LPS-160434

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by dantewang** [comment]
@GinsonRen @111Anna Could you run a login diff on this PR? Thanks!

**Comment by GinsonRen** [comment]
@dantewang Here is diff result of login:

**Comment by Kvale1733** [comment]
@tinatian Regressions found. Simulation mode does not work.

Steps to reprodue
1. Login to portal and go to default site
2. Click on the simulation button (top right)

Expected results: The user can select different devices to simulate viewing the page in those devices.
Actual results: A blank white side panel appears that cannot be interacted with.

Expected:

Expected

**Comment by tinatian** [comment]
@dantewang Please help me take a look at this.

Thanks.
Tina

**Comment by dantewang** [comment]
@tinatian The root cause is the mismatching of servlet contexts.

- `ProductNavigationSimulationPortlet` is in `product-navigation-simulation-web`
- `DevicePreviewPanelApp`, which is applied with the new pattern in this PR, is in `product-navigation-simulation-device`

With the change in this PR, `DevicePreviewPanelApp` gets the servlet context of the -web module, making it unable to include its own jsps in the -device module.

So, it's unreliable to get the servlet context of the `PanelApp`'s module from the portlet the `PanelApp` associates with.

**Pull request closed without merging**
