### PR TITLE
LPS-158865

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is to fix the error caused by changes made in web.proxy.web in  [LPS-154824](https://github.com/liferay-core-infra/liferay-portal/pull/997/commits/bbb19fda01f389e94eb05206c6ad43d56e1fae51).

```
[exec] > Task :apps:archived:portal-security-wedeploy-auth-test:testIntegrationClasses
     [exec] 2022-07-12 08:20:24.003 ERROR [fileinstall-directory-watcher][DirectoryWatcher:1173] Unable to start bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.web.proxy.web.jar
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.web.proxy.web [966]
     [exec]   Unresolved requirement: Import-Package: org.apache.commons.httpclient
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428) ~[org.eclipse.osgi.jar:?]
     [exec] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundle(DirectoryWatcher.java:1156) [bundleFile:?]
     [exec] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundles(DirectoryWatcher.java:1189) [bundleFile:?]
     [exec] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startAllBundles(DirectoryWatcher.java:1130) [bundleFile:?]
     [exec] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:1041) [bundleFile:?]
     [exec] 	at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:221) [bundleFile:?]
```
Thanks for checking!
For more info, please see https://issues.liferay.com/browse/LPS-158865.

cc:@kyle-miho

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result again, please?

Thanks
Jeff

**Comment by tinatian** [comment]
@jeffwu0724 Your commit message said "LPS-158865 - updated the Import-Package for web.proxy.web to **build** successfully", while I did not see any build issue when I build it locally.

**Comment by tinatian** [comment]
@jeffwu0724 Based on the error log your attached, this does not seem to be a build issue, it can only happen on runtime. Please update your commit message and the ticket description, also, please add the link of the commit causing this issue.

Tina.

**Comment by jeffwu0724** [comment]
updated commit message and [ticket description](https://issues.liferay.com/browse/LPS-158865) with more details.

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by tinatian** [comment]
@kyle-miho Please trigger corresponding test if it is not triggered by default.

**Comment by kyle-miho** [comment]
@tinatian @jeffwu0724 this should be visible in acceptance, ill re-run it

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
issues with test report generating, i'll try one more time and ask ci if it still doesnt generate

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
Looks like CI node crashed this run, re-running

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
Hey @tinatian @jeffwu0724, this commit solves the unresolved requirement issue with web.proxy.web on deployment. There is [another error](https://gist.github.com/kyle-miho/537bf3396901a2e0a6e2b0a980c44bbd) in archived-modules-test, but it should be from a different module and unrelated, so we should be good with this pr

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121400

**Pull request closed without merging**
