### PR TITLE
[Method Reference2] LPS-165277 Convert method reference to ServiceTracker in dynamic-data-mapping-service

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @tinatian @dantewang ,

Forwarded from: https://github.com/liferay-forms/liferay-portal/pull/2108
Follow-up: https://github.com/liferay-core-infra/liferay-portal/pull/2607

Thanks @carolmariaabb from the forms team help to review this pull !

### CODE REVIEW

**Comment by JanisZhang** [comment]
re-trigger ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
Numerous instances of builds failing due to network connection timeouts. will re-trigger after the problem solved.

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:data-engine

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by JanisZhang** [comment]
Thanks cat! @catarineaguiar

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128961

**Pull request closed without merging**
