### PR TITLE
[TS] LPS-141588 Downgrade library to a more stable version

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team,

For additional details, please see the ticket: [LPS-141588](https://issues.liferay.com/browse/LPS-141588)

Feel free to let us know if you have any questions.
Thanks!

/cc @dacousalr

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test

**Comment by tinatian** [comment]
@dacousalr @ericyanLr 
Does the latest version (https://mvnrepository.com/artifact/org.glassfish/javax.el/3.0.1-b12) include the fix for WLS bug 26801105. 
Compared to downgrade, I prefer to upgrade to the latest version.

Tina.

**Comment by ericyanLr** [comment]
Hi @tinatian ,

We'll work on the changes as discussed and will resend afterwards. 
Closing out this PR.

**Pull request closed without merging**
