### PR TITLE
LPS-184766 Inline Equinox Http | 6-5

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:smoke

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
The SF failure is irrelevant with this pull.

**Comment by dantewang** [comment]
ci:test:smoke

**Comment by vicnate5** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
Unique failure in license compile test
```
check-license:
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:7016: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:7050: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:12661: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/build-common.xml:1072: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/build-common.xml:444: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/build-common.xml:452: File does not contain enterprise copyright information: /opt/dev/projects/github/liferay-portal/modules/apps/static/portal-osgi-web/portal-osgi-web-http-servlet/src/main/java/com/liferay/portal/osgi/web/http/servlet/ExtendedHttpService.java
```
Full log https://testray.liferay.com/reports/production/logs/2023-06/test-1-37/test-portal-acceptance-pullrequest(master)/12068/portal-license-smoke-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0

Only need to re-run `stable` to retest

**Comment by dantewang** [comment]
Hi @vicnate5, it's on purpose that the files do not contain the copyright information as required by the legal team. Is there any way to bypass this check for these files in license compile test?

**Comment by vicnate5** [comment]
FYI the license test is part of stable, so the test needs to be passing.

**Comment by dantewang** [comment]
Resend: https://github.com/liferay-core-infra/liferay-portal/pull/4761

**Pull request closed without merging**
