### PR TITLE
LPS-193525 Merge Patcher impl and interface into Util class in kernel

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@julschong no regressions were found.

Only a SF issue:
```
format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Use portal service reference instead of 'com.liferay.portal.kernel.patcher.PatcherUtil' in modules, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/java_osgi_reference_check.markdown: /opt/dev/projects/github/liferay-portal/modules/apps/marketplace/marketplace-store-web/src/main/java/com/liferay/marketplace/store/web/internal/portlet/MarketplaceStorePortlet.java (SourceCheck:JavaOSGiReferenceCheck)
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:457)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:290)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-08/test-1-36/test-portal-source-format/2086/source-format-current-branch-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
fix sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
need to verify if patcher tool team is ok

**Comment by julschong** [comment]
https://liferay.atlassian.net/browse/PTR-4222

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
pushed to remove unused method in Patch api

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by julschong** [comment]
need to simplify and rename class

**Pull request closed without merging**
