### PR TITLE
[Remove Stream/Optional usage] LPS-171888 headless PART 3

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-171888

### CODE REVIEW

**Comment by JanisZhang** [comment]
Force-pushed.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:headless

**Comment by JanisZhang** [comment]
ci:help

**Comment by JanisZhang** [comment]
ci:test:headless

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@JanisZhang many unit tests failed due to:

```
    [exec] com.liferay.headless.admin.content.resource.v1_0.test.StructuredContentResourceTest > testGraphQLGetSiteStructuredContentsPage FAILED
     [exec]     java.lang.IllegalArgumentException: Expected starts with '[', but found '{' in '{"siteId":62005,"priority":0.7159571829771115,"title":"sbpyrg0k"}'
     [exec]     	at com.liferay.headless.admin.content.client.json.BaseJSONParser._assertStartsWithAndEndsWith(BaseJSONParser.java:258)
     [exec]     	at com.liferay.headless.admin.content.client.json.BaseJSONParser.parseToDTOs(BaseJSONParser.java:105)
     [exec]     	at com.liferay.headless.admin.content.client.json.BaseJSONParser.parseToDTOs(BaseJSONParser.java:128)
```

full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-29/test-portal-acceptance-pullrequest(master)/6101/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
