### PR TITLE
LPS-172305 Implement SF check to check usage of `*ResourcePermissionFactory.getInstance()` in modules

### PR DESCRIPTION
**Pull request by kevhlee**
Previous pull request: <https://github.com/liferay-core-infra/liferay-portal/pull/2993>.

I am resending this pull request as it needed to be retested and rebased to `master`.

This SF rule checks and prevents the usage of `*ResourcePermissionFactory.getInstance()` in modules apps (see <https://github.com/brianchandotcom/liferay-portal/pull/128420>).

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
SF issue is unrelated.

**Comment by tinatian** [comment]
@kevhlee Please merge the last two commits into one. Please do not fix your own mistakes in a separate commit, fix it directly in the commit you made the mistakes.

Thanks.
Tina.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129174

**Pull request closed without merging**
