### PR TITLE
[Convert method references] LPS-162708 Convert method references to field references in module co…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-162708

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@shuyangzhou @tinatian All tests passed and changes are direct replacements. Asked Commerce team for a final check

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by tinatian** [comment]
@victoroscuro Please help me scan test results.

Thanks.
Tina

**Comment by victoroscuro** [comment]
@tinatian Checks are fine. Please check slack thread. Thanks

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123243

**Pull request closed without merging**
