### PR TITLE
[Component with its own class name as service type] LPS-195840 Refactor Registry classes from Asset, Headless and Saml module

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Related: https://liferay.atlassian.net/browse/LPS-195840

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Valmir-unicap** [comment]
ci:test:saml

**Comment by Valmir-unicap** [comment]
ci:test:headless

**Comment by Valmir-unicap** [comment]
ci:test:echo-3

**Comment by Valmir-unicap** [comment]
ci:test:echo

**Comment by vicnate5** [comment]
No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141446

@Valmir-unicap @rafaprax for https://github.com/liferay-core-infra/liferay-portal/pull/5631/commits/fbc63400cfbf7ca3c894a8acf5b5b61fbab5eb56 , send me a follow up to remove https://github.com/liferay/liferay-portal/blob/master/modules/apps/headless/headless-delivery/headless-delivery-impl/src/main/java/com/liferay/headless/delivery/internal/dto/v1_0/mapper/LayoutStructureItemMapper.java#L16 And make all impls of LayoutStructureItemMapper carry this service property, and make the ServiceTrackerMap mapping on that property.

**Pull request closed without merging**
