### PR TITLE
LPS-143635 Avoid using OrganizationPermissionUtil, PasswordPolicyPermissionUtil, PortalPermissionUtil directly in modules

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,
@tinatian
Main Task: [LPS-143403](https://issues.liferay.com/browse/LPS-143403)
Sub Task 8: [LPS-143635](https://issues.liferay.com/browse/LPS-143635)
Avoid using OrganizationPermissionUtil, PasswordPolicyPermissionUtil, PortalPermissionUtil directly in modules

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@kyle-miho Hi Kyle, 
Could you please help me check the test for this pull?
Thank you!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Thanks.
Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113819

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
