### PR TITLE
[Replace Non-Blocking Usage] LPS-199954

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace non-blocking ServiceProxyFactory usages in class `OpenSSOUtil`, `PwdToolkitUtil`, and `OrganizationMembershipPolicyFactoryImpl`. Thanks.
https://liferay.atlassian.net/browse/LPS-199954

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by dantewang** [comment]
@JanisZhang Are all of these services are from Spring beans?

**Comment by JanisZhang** [comment]
Hi @dantewang, I just noticed that the class `OrganizationMembershipPolicyFactoryImpl` (will be eliminated by https://github.com/liferay-core-infra/liferay-portal/pull/5889) and `PasswordPolicyToolkit`(impl of PwdToolkit) are from spring beans. I will resent. Thanks!

**Pull request closed without merging**
