### PR TITLE
LPD-41167 Pre-populate some data related to object definition to avoid extra SQL calls on portal startup

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
Related issues : [LPD-41167](https://liferay.atlassian.net/browse/LPD-41167) [LPD-41346](https://liferay.atlassian.net/browse/LPD-41346)

CI and review : https://github.com/liferay-bpm/liferay-portal/pull/3856

Old review : https://github.com/liferay-core-infra/liferay-portal/pull/7623#issuecomment-2469372794

**Motivation:**

In this PR, we are storing the object actions and object layouts directly within the object definition to reduce the need for additional SQL calls.

cc @JerryAdrianoo

[LPD-41167]: https://liferay.atlassian.net/browse/LPD-41167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LPD-41346]: https://liferay.atlassian.net/browse/LPD-41346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tinatian** [comment]
@JerryAdrianoo Please verify startup performance. Thanks!

**Comment by tinatian** [comment]
@pedro-oliveira446 

You do not have to expose the method to api https://github.com/liferay-core-infra/liferay-portal/pull/7640/commits/1add9c1529a2b34944807ba11d3b317358cd14bb, as you know which impl you are using here https://github.com/liferay/liferay-portal/blob/8167e7875f59773e7737b7853a7dbf9c6ddeb406/modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectDefinitionLocalServiceImpl.java#L977

**Comment by pedro-oliveira446** [comment]
@JerryAdrianoo I will check, thank you

**Comment by pedro-oliveira446** [comment]
Hi @tinatian ,

Regarding your request, I’m currently working on another [pull request](https://github.com/liferay-bpm/liferay-portal/pull/3858/commits/ab93ac66dd562f45252149f3e40bb5cfcc59e5b6), which should follow after this one is approved. In that PR, I’ll need to implement the deployActiveObjectDefinitions in a different deployer.

**Comment by pedro-oliveira446** [comment]
I was able to resolve the startup error with a small change in the code. I’m now passing the objectDefinitionLocalService as a parameter [here](https://github.com/liferay-core-infra/liferay-portal/blob/5e9c13052526f12ed4ef13ebe74ee51cb37c57ba/modules/apps/object/object-api/src/main/java/com/liferay/object/deployer/ObjectDefinitionDeployer.java#L30).

@JerryAdrianoo @tinatian

**Comment by JerryAdrianoo** [comment]
Hey all, this PR decreased some queries, as is shown below. No other improvement or regression was noticed.
| Baseline | Open count of Prepared Statement | Count of Prepared Statement Query | Open Count of SQL |
|--------|--------|--------|--------|
7a1a6c1 | 148 | 222 | 843 |
LPD-41167 | 138 | 207 | 839 | 


For more details, please see: [Spreadsheet](https://docs.google.com/spreadsheets/d/1ufybJPpiPbsfhXi4k3udDftGjTxQrT8RaMNXSKmm4Dg/edit?usp=sharing)

**Comment by tinatian** [comment]
@pedro-oliveira446 From design point of view, deployActiveObjectDefinitions should always come with undeployActiveObjectDefinitions.

Also the current API (ObjectDefinitionDeployer) becomes weird with your new added method, you are adding a new method deploying active object definition, then how about those inactivate ones?

When should I use deploy(), when to use deployActiveObjectDefinitions()?

This is really bad design and would cause lots of confusions later.

Please try to figure out another way to do this.

**Pull request closed without merging**
