### PR TITLE
[Replace Non-Blocking Usage] LPS-199983

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace non-blocking ServiceProxyFactory usages by using dynamic Snapshot in `PortletImpl` as ServiceProxyFactory was added to track the latest ControlPanelEntry instance. See a8383a0d68646342bc08aecde79b64b8cf6cbb4d. 
Thanks for checking.
https://liferay.atlassian.net/browse/LPS-199983

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142896

cc @shuyangzhou

**Pull request closed without merging**
