### PR TITLE
[TS] LPS-157252

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-157252

Resent from https://github.com/liferay-core-infra/liferay-portal/pull/1135

Split up main logic changes from SF changes, and added logic to make sure only control panel pages could set language from session's locale.

Original message:

> This new solution includes an edge case fix where the control panel cannot have it's language translated.  By reading in the session locale, we can now adjust the locale of the given page if needed.

> In the scenario where the user is requesting their default language, the portal and user default language is the same, but the current virtualHost's default language is different, then the portal will still provide the URL without any language code.  This is because the portal is not taking into account the virtualHost's default language when (not) setting the i18nPath to the requested language.  Further, having a virtualHost default language works against the `LOCALE_PREPEND_FRIENDLY_URL_STYLE` 3 (which is the default value) because now the specified virtualHost (without languageId in the URL) only points to one language, instead of any available language.
> 
> With my changes, the portal now considers if the virtualHost has a default language, and will include a `i18nPath` value if the requested language is different.
> 
> Please let me know if you have any questions, thanks!

CC @crodriguezy

### CODE REVIEW

**Review by dantewang — CHANGES_REQUESTED** [review]
@ChrisKian Thanks for the update! And sorry I forget to mention tests in the last PR. Could you try to add tests for the logic you added? And explain it if it's not possible. Thanks!

**Comment by tinatian** [comment]
@ChrisKian Please add test to cover your change and resend.

Thanks.
Tina

**Comment by crodriguezy** [comment]
HI @ChrisKian , were you able to keep working on this? I also left you a comment via slack about an incorrect behaviour:

The language switch is not working in Control panel general options (not the site's one). It was the customer who reported this, I was only focused on the Site's options during the tests 😞 

This is the result when I test through a Virtual Host:
Sitios Web - Liferay DXP (1)


And this is the result when I test through localhost:

meca - mecalux - Liferay DXP (2)

Maybe if we use a more global check like:

```
	@Override
	public boolean isControlPanelPath(String path) {
		if (Validator.isNull(path)) {
			return false;
		}

		return path.contains(
			GroupConstants.CONTROL_PANEL_FRIENDLY_URL);
	}
```
instead of checking the group's control panel path (with the ~ separator), it will cover both cases. But I'm not sure if this is going to break any other thing

**Comment by ChrisKian** [comment]
Hi @crodriguezy,
I've been swamped with other support tickets, so I'll try to get to this test tomorrow or Monday.  Thanks!

**Comment by crodriguezy** [comment]
Ok @ChrisKian !
Thank you!

**Comment by ChrisKian** [comment]
Resent here: https://github.com/liferay-core-infra/liferay-portal/pull/1406

**Pull request closed without merging**
