### PR TITLE
LPD-26718 Fix Company Log cannot be downloaded if liferay.home is not set to normalized Path

### PR DESCRIPTION
**Pull request by julschong**
@tinatian Hi Tina,
This issue came up when I was investigating for one of the release found test failures.
My local environment was failing for a different reason from the ci results.

Ticket: https://liferay.atlassian.net/browse/LPD-26718

I found that since my liferay.home is usually set to a non-normalized path from build: `liferay.home=/home/me/dev/projects/liferay-portal/../../bundles/master`
I cannot download company log at all and always resulted in 403 not autherized response even when I was logged in as Test admin user

For cause and solution, please refer to the ticket

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:core-functional

**Comment by julschong** [comment]
need to write unit test

**Comment by tinatian** [comment]
@julschong The test should be together with the change if this is not urgent, please add the test.

**Pull request closed without merging**
