### PR TITLE
LPS-166009 Move template files to modules

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina, @tinatian 
resubmitted from https://github.com/brianchandotcom/liferay-portal/pull/125998
Rebase error mentioned by Brian came from https://github.com/brianchandotcom/liferay-portal/pull/125958
Waiting fro ci test to finish to be safe

### CODE REVIEW

**Comment by julschong** [comment]
rebased for conflict in semantic versioning

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Semantic versioning error:
```
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.template                        MAJOR      7.0.0      7.0.0      8.0.0      VERSION INCREASE REQUIRED
[beanshell] 	-   class      com.liferay.portal.template.BaseTemplate
```

Full console log:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-29/test-portal-acceptance-pullrequest(master)/5400/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

Other failures are unrelated.

**Comment by julschong** [comment]
rebased to resolve semver issue

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126297

**Pull request closed without merging**
