### PR TITLE
LPS-176754 3 9

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
ci:test:message-boards

**Comment by zhangyan0701** [comment]
Semantic versioning issue:

```
     [exec] > Task :baseline
     [exec] [Baseline Warning] Bundle Version Change Recommended: 100.1.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/100.0.0/b4c169e4f56958decd83d831d98417766fe87ba8/com.liferay.portal.kernel-100.0.0.jar
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-03/test-1-37/test-portal-acceptance-pullrequest(master)/9703/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

Other failures are unrelated.

**Comment by tinatian** [comment]
Rebase and fix baseline and force push, no need to trigger tests.

Tina

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131503

**Pull request closed without merging**
