### PR TITLE
[Remove Spring extender usages] LPS-161574 Break circular dependency between CommerceAddressLocalServiceImpl and CommerceOrderLocalServiceImpl

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, @tinatian.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:commerce

**Comment by yuhai** [comment]
@@zhangyan0701, please help scan the test result after ci test finish.

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@yuhai I have a question with your change. You moved logic from various methods from one local service to methods in another local service, but I only see `CartResourceImpl` modified to use one of your new methods. Don't the usages of other methods in `CommerceAddressLocalServiceImpl` you modified need to be updated?

**Comment by yuhai** [comment]
> @yuhai I have a question with your change. You moved logic from various methods from one local service to methods in another local service, but I only see `CartResourceImpl` modified to use one of your new methods. Don't the usages of other methods in `CommerceAddressLocalServiceImpl` you modified need to be updated?

@dantewang，In CommerceAddressLocalServiceImpl, I modified the two methods delete and update. Don't let CommerceAddressLocalServiceImpl send actions to CommerceOrderLocalServiceImpl. Other methods of CommerceAddressLocalServiceImpl needn't be updated.

**Comment by dantewang** [comment]
@yuhai This is one of the things we talked about. The method API keeps unchanged, but the method behavior is changed. The callers of the delete or update method in `CommerceAddressLocalServiceImpl` may have logic depending on the cascade logic before your change, and their logic may break after your change. I'm not sure whether it is acceptable for customers, but we at least need to keep callers in Liferay code working normally.

**Comment by yuhai** [comment]
> @yuhai This is one of the things we talked about. The method API keeps unchanged, but the method behavior is changed. The callers of the delete or update method in `CommerceAddressLocalServiceImpl` may have logic depending on the cascade logic before your change, and their logic may break after your change. I'm not sure whether it is acceptable for customers, but we at least need to keep callers in Liferay code working normally.

@dantewang, Yes, the current changes want to make sure Liferay code working normally.

**Comment by yuhai** [comment]
@dantewang, I will resend it. Thanks.

**Pull request closed without merging**
