### PR TITLE
LPS-146089 Move usages of liferay-icu4j.jar to a new module

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by guilhermedcamacho** [comment]
@vicnate5 please help me check the results, thanks!

ps. I ran relevant suite with the same code [here](https://github.com/guilhermedcamacho/liferay-portal/pull/55#issuecomment-1037231753), getting just one unique failure (not related), so probably the ones that failed in relevant are not related.

**Comment by vicnate5** [comment]
@koor4356 can you check this one?

**Comment by koor4356** [comment]
okay, thanks

**Comment by tinatian** [comment]
@guilhermedcamacho Code looks good to me, waiting for QA to scan test results.

**Comment by koor4356** [comment]
@guilhermedcamacho @tinatian 
No unque failures. Thanks!

**Comment by guilhermedcamacho** [comment]
@shuyangzhou , this PR is ready for your review. Thanks!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10549

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
