### PR TITLE
LPS-149099 Move commons-collections4.jar to portal-tika

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
Hey @vicnate5, Can you help me to scan this test results? Thx

**Comment by vicnate5** [comment]
@rafaprax Multiple backend test failures here

1. [com.liferay.wiki.editor.configuration.internal.WikiAttachmentImageHTMLEditorConfigContributorTest](https://testray.liferay.com/home/-/testray/case_results/1637359152)
```
com.liferay.wiki.editor.configuration.internal.WikiAttachmentImageHTMLEditorConfigContributorTest > testItemSelectorURLWhenAllowBrowseAndValidWikiPage FAILED
    java.util.ServiceConfigurationError: com.liferay.portal.kernel.module.util.SystemBundleProvider: Provider com.liferay.portal.test.osgi.TestSystemBundleProvider could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at com.liferay.portal.kernel.module.util.SystemBundleUtil.<clinit>(SystemBundleUtil.java:118)
        at com.liferay.portal.kernel.module.util.ServiceTrackerFieldUpdaterCustomizer.<init>(ServiceTrackerFieldUpdaterCustomizer.java:165)
        at com.liferay.portal.kernel.util.ServiceProxyFactory._newServiceTrackedInstance(ServiceProxyFactory.java:169)
        at com.liferay.portal.kernel.util.ServiceProxyFactory.newServiceTrackedInstance(ServiceProxyFactory.java:88)
        at com.liferay.portal.kernel.util.ServiceProxyFactory.newServiceTrackedInstance(ServiceProxyFactory.java:53)
        at com.liferay.portal.kernel.upload.UploadServletRequestConfigurationHelperUtil.<clinit>(UploadServletRequestConfigurationHelperUtil.java:38)
        at com.liferay.item.selector.criteria.upload.criterion.UploadItemSelectorCriterion.<init>(UploadItemSelectorCriterion.java:33)
        at com.liferay.wiki.editor.configuration.internal.BaseWikiAttachmentImageEditorConfigContributor.getUploadItemSelectorCriterion(BaseWikiAttachmentImageEditorConfigContributor.java:148)
        at com.liferay.wiki.editor.configuration.internal.WikiAttachmentImageHTMLEditorConfigContributor.getItemSelectorURL(WikiAttachmentImageHTMLEditorConfigContributor.java:83)
        at com.liferay.wiki.editor.configuration.internal.BaseWikiAttachmentImageEditorConfigContributor.populateConfigJSONObject(BaseWikiAttachmentImageEditorConfigContributor.java:103)        at com.liferay.wiki.editor.configuration.internal.WikiAttachmentImageHTMLEditorConfigContributorTest.testItemSelectorURLWhenAllowBrowseAndValidWikiPage(WikiAttachmentImageHTMLEditorConfigContributorTest.java:186)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        java.lang.NoClassDefFoundError: org/apache/commons/collections4/BidiMap
            at org.apache.sling.testing.mock.osgi.MapMergeUtil.propertiesMergeWithOsgiMetadata(MapMergeUtil.java:73)
            at org.apache.sling.testing.mock.osgi.MapMergeUtil.propertiesMergeWithOsgiMetadata(MapMergeUtil.java:55)
            at org.apache.sling.testing.mock.osgi.MockBundleContext.registerService(MockBundleContext.java:124)
            at org.apache.sling.testing.mock.osgi.MockBundleContext.registerService(MockBundleContext.java:112)
            at org.apache.sling.testing.mock.osgi.MockBundleContext.<init>(MockBundleContext.java:85)
            at org.apache.sling.testing.mock.osgi.MockOsgi.newBundleContext(MockOsgi.java:52)
            at com.liferay.portal.test.osgi.TestSystemBundleProvider.<clinit>(TestSystemBundleProvider.java:44)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at java.lang.Class.newInstance(Class.java:442)
            at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
            ... 66 more

            Caused by:
            java.lang.ClassNotFoundException: org.apache.commons.collections4.BidiMap
                at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
                ... 79 more
```
2. [com.liferay.portal.workflow.task.web.internal.notifications.WorkflowTaskUserNotificationHandlerTest](https://testray.liferay.com/home/-/testray/case_results/1637358383)
3. [com.liferay.portal.search.elasticsearch7.internal.expando.ExpandoTest](https://testray.liferay.com/home/-/testray/case_results/1637358596)
4. [com.liferay.portal.cache.internal.dao.orm.EntityCacheImplTest](https://testray.liferay.com/home/-/testray/case_results/1637359394)
5. [com.liferay.journal.search.SearchResultUtilJournalArticleTest](https://testray.liferay.com/home/-/testray/case_results/1637358665)
6. [com.liferay.frontend.taglib.servlet.taglib.ComponentTagTest](https://testray.liferay.com/home/-/testray/case_results/1637358386)
7. Integration [com.liferay.counter.test.CounterLocalServiceTest](https://testray.liferay.com/home/-/testray/case_results/1637354941)

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @koor4356, Can you please scan these new test results? Thx

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
@rafaprax 
This looks good. thanks!

**Comment by rafaprax** [comment]
Hey @tinatian, It's ready for your review. Thx

**Comment by rafaprax** [comment]
Hey @shuyangzhou,

It is a required dependency of the sling-testing-osgi-mock-core lib that is reached when the `TestSystemBundleProvider` class is loaded, see [here](https://github.com/liferay/liferay-portal/blob/master/portal-test/src/com/liferay/portal/test/osgi/TestSystemBundleProvider.java#L43-L44). So, without the https://github.com/liferay-core-infra/liferay-portal/commit/0deb423eeeed91d2bec34bb703c6349320f3e1b7 all tests that use the  `SystemBundleUtil.getBundleContext` will brake with a `NoClassDefFoundError` at runtime. 

In the first version of this fix, I didn't add this to portal-test.jar and @vicnate5 caught some unit and integration tests failures, please see his comment above https://github.com/liferay-core-infra/liferay-portal/pull/479#issuecomment-1071830764

Thx

**Comment by shuyangzhou** [comment]
@rafaprax I am taking it in as it is. Otherwise we would be forced to declare the dependencies in each module's test dependencies in case they use ServiceProxyFactory, that's too ugly. This is a valid solution.

See https://github.com/brianchandotcom/liferay-portal/pull/115034

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
