### PR TITLE
LPD-16395 stop deploying io.swagger to osgi/portal

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, 

In this PR, I try to export package for io.swagger, instead of deploying it to osgi/portal
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:report:2533749668

**Comment by jeffwu0724** [comment]
No regression found

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
