### PR TITLE
LPS-145577 Remove HtmlUtil usages in modules part 1

### PR DESCRIPTION
**Pull request by julschong**
@tinatian 
Hi Tina, 
no need to wait for #2482
I separated them by modules
Thank you!

### CODE REVIEW

**Comment by zhangyan0701** [comment]
Portal startup error:
```
[beanshell] 2022-11-18 04:35:29.234 ERROR [Portal Spring Init Thread][ContextLoader:225] Context initialization failed
[beanshell] org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.portal.kernel.util.HtmlUtil' defined in class path resource [META-INF/util-spring.xml]: Cannot resolve reference to bean 'com.liferay.portal.util.HtmlImpl' while setting bean property 'html'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'com.liferay.portal.util.HtmlImpl' available
[beanshell] 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1702) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at com.liferay.portal.spring.bean.LiferayBeanFactory.populateBean(LiferayBeanFactory.java:152) ~[portal-impl.jar:?]
[beanshell] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401) ~[spring-web.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292) ~[spring-web.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103) ~[spring-web.jar:5.2.22.RELEASE]
[beanshell] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.lambda$contextInitialized$1(PortalContextLoaderListener.java:273) ~[portal-impl.jar:?]
[beanshell] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
[beanshell] 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[beanshell] Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'com.liferay.portal.util.HtmlImpl' available
[beanshell] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:816) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1288) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:277) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springf
```

Full console:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-26/test-portal-acceptance-pullrequest(master)/6004/functional-tomcat90-mysql57-jdk8/12/17/jenkins-console.txt.gz?authuser=0

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
pushed to fix bean reference

**Comment by tinatian** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/126695

**Pull request closed without merging**
