### PR TITLE
[Method Reference Static]Lps 183181

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-183181

For ServletContextUtil under dynamic-data-mapping-taglib, this pull just remove all its usages in none generated classes by using Snapshot, the util still was leftover here because it was used in these generated classes under dynamic-data-mapping-taglib :
BaseTemplateRendererTag
BaseHTMLFieldTag
BaseHTMLTag
BaseTemplateSelectorTag

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:data-engin

**Comment by Kvale1733** [comment]
ci:test:security

**Comment by Kvale1733** [comment]
ci:test:comment

**Comment by Kvale1733** [comment]
ci:test:document

**Comment by slnn** [comment]
ci:stop

**Pull request closed without merging**
