### PR TITLE
[OrderByComparator] LPD-26373 Clean up and Apply Singleton in module data-engine and dynamic-data-lists

### PR DESCRIPTION
**Pull request by Valmir-unicap**
- Ticket: https://liferay.atlassian.net/browse/LPD-26373

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@Valmir-unicap There are usages of the changed comparator in jsp. Please apply to fix compile and resend. Thanks.

cc @tinatian

**Comment by dantewang** [comment]
@Valmir-unicap Sorry commented on the wrong PR.

**Comment by dantewang** [comment]
ci:report:2570852927

**Comment by dantewang** [comment]
@Valmir-unicap There is indeed a compile error:

```
     [exec] > Task :apps:dynamic-data-lists:dynamic-data-lists-web:compileJSP
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/dynamic-data-lists/dynamic-data-lists-web/build/jspc/org/apache/jsp/configuration_jsp.java:113: error: DDLRecordSetCreateDateComparator(boolean) has private access in com.liferay.dynamic.data.lists.util.comparator.DDLRecordSetCreateDateComparator
     [exec] 		orderByComparator = new DDLRecordSetCreateDateComparator(orderByAsc);
     [exec] 		                    ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/dynamic-data-lists/dynamic-data-lists-web/build/jspc/org/apache/jsp/configuration_jsp.java:119: error: DDLRecordSetNameComparator(boolean) has private access in com.liferay.dynamic.data.lists.util.comparator.DDLRecordSetNameComparator
     [exec] 		orderByComparator = new DDLRecordSetNameComparator(orderByAsc);
     [exec] 		                    ^
```

Please apply the change to the JSP file.

**Pull request closed without merging**
