### PR TITLE
[Equinox Http] LPS-195887

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou Fixing startup error caused by lazy ServiceTrackerList.

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test

**Comment by zhangyan0701** [comment]
The failure in test [build-lib-versions-jdk8](https://testray.liferay.com/home/-/testray/case_results/2428408020) seems related. Below message in console log:
```
     [echo] diff --git a/lib/versions-complete.xml b/lib/versions-complete.xml
     [echo] index b8ef36071c42..019d16221963 100644
     [echo] --- a/lib/versions-complete.xml
     [echo] +++ b/lib/versions-complete.xml
     [echo] @@ -2513,7 +2513,7 @@
     [echo]  			</library>
     [echo]  			<library>
     [echo]  				<file-name>com.liferay.portal.osgi.web.http.servlet.impl.jar!org.eclipse.equinox.http.servlet.jar</file-name>
     [echo] -				<version>1.2.2.v20211118-0920.LIFERAY-PATCHED-1</version>
     [echo] +				<version>1.2.2.v20211118-0920.LIFERAY-PATCHED-2</version>
     [echo]  				<project-name>com.liferay:org.eclipse.equinox.http.servlet</project-name>
     [echo]  				<licenses>
     [echo]  					<license>
     [echo] diff --git a/lib/versions.html b/lib/versions.html
     [echo] index 71637c98b885..1069ed967281 100644
     [echo] --- a/lib/versions.html
     [echo] +++ b/lib/versions.html
     [echo] @@ -1328,7 +1328,7 @@
     [echo]  </tr>
     [echo]  			
     [echo]  <tr>
     [echo] -<td nowrap="nowrap">com.liferay.portal.osgi.web.http.servlet.impl.jar!org.eclipse.equinox.http.servlet.jar</td><td nowrap="nowrap">1.2.2.v20211118-0920.LIFERAY-PATCHED-1</td><td nowrap="nowrap">com.liferay:org.eclipse.equinox.http.servlet</td><td nowrap><a href="http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt">LGPL 2.1</a>
     [echo] +<td nowrap="nowrap">com.liferay.portal.osgi.web.http.servlet.impl.jar!org.eclipse.equinox.http.servlet.jar</td><td nowrap="nowrap">1.2.2.v20211118-0920.LIFERAY-PATCHED-2</td><td nowrap="nowrap">com.liferay:org.eclipse.equinox.http.servlet</td><td nowrap><a href="http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt">LGPL 2.1</a>
     [echo]  <br>
     [echo]  </td><td></td>
     [echo]  </tr>
[stopwatch] [run.batch.test.action: 2:10.448 sec]
     [echo] .
     [echo] 
     [echo] Detected build-lib-versions changes. See above build-lib-versions log for more
```
Full console:
https://testray.liferay.com/reports/production/logs/2023-09/test-1-31/test-portal-acceptance-pullrequest(master)/9481/build-lib-versions-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by dantewang** [comment]
@zhangyan0701 Force pushed. This failure should be fixed by https://github.com/liferay-core-infra/liferay-portal/pull/5589/commits/80f54780ebcfdfda99d7806cd3c1972d612267de. Does the build-lib-versions-jdk8 only included in ci-test?

**Comment by catarineaguiar** [comment]
> @zhangyan0701 Force pushed. This failure should be fixed by [80f5478](https://github.com/liferay-core-infra/liferay-portal/commit/80f54780ebcfdfda99d7806cd3c1972d612267de). Does the build-lib-versions-jdk8 only included in ci-test?

@dantewang yea, it's only included in ci-test

@vicnate5 Should we include it to relevant?

**Comment by vicnate5** [comment]
@catarineaguiar Check how fast that test batch is normally? You can look at the Jenkins report to check the runtime. Here it took 9 mins, but it also failed. How fast is it when passes? If it is under 20 minutes normally, we can add to acceptance (or maybe we even consider `stable` if it is fast).

**Comment by Kvale1733** [comment]
@vicnate5 I believe we originally did not add it to relevant since sometimes the command for that had some sort of issue where it would occasionally fail out due to some connection issue when checking the version. So did only add it to acceptance to prevent this affecting relevant/stable. This happened locally too. I'll check how it's doing now but for now I'll just test this locally.

**Comment by Kvale1733** [comment]
@dantewang Ran that build-lib-version batch locally on this branch and it passed. No regressions found.

**Comment by dantewang** [comment]
@shuyangzhou I'll clean up the `HttpServiceRuntime` thing in a later PR.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141181

**Pull request closed without merging**
