### PR TITLE
Add guest user role to guest user and add FriendlyURL for mbCategoryModel under SampleSQLBuilder

### PR DESCRIPTION
**Pull request by GinsonRen**
https://github.com/liferay/liferay-portal/commit/04ece488dd06ff56d75ecdd5eda979cf5325127c
https://github.com/liferay/liferay-portal/commit/48913b7764aa0f69db8f0f932db2f7034556732e

### CODE REVIEW

**Comment by GinsonRen** [comment]
ci:test:sf

**Comment by GinsonRen** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
No regressions found.

**Comment by slnn** [comment]
Please see https://github.com/liferay-core-infra/liferay-portal/pull/5497

**Pull request closed without merging**
