### PR TITLE
LPS-143632 Remove LanguageUtil from moduels part 2a commerce

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
could you please help me scan this result?
Thank you!

**Comment by catarineaguiar** [comment]
I will analyze it on Monday.

**Comment by catarineaguiar** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by julschong** [comment]
@slnn 
Hi Lily,
could you please help me review this pull?
Thank you!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/120372

**Pull request closed without merging**
