### PR TITLE
LPS-157938

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-157938, which is the preparation for ticket https://issues.liferay.com/browse/LPS-149258.
I need to use org.apache.tika version 1.28.4 in portal-tika, and there is a limitation in using 1.26.0 in source-formatter, and that's why I will have to update this in master first.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by tinatian** [comment]
@jeffwu0724 Code looks good to me, wait for QA to scan test results.


Tina.

**Comment by catarineaguiar** [comment]
@jeffwu0724 regressions found:

this error message appears in the logs when I try to add a `.docx` file on Documents & media, and the document was not present on Content Dashboard either.
```
Exception in thread "liferay/document_library_raw_metadata_processor-6" java.lang.NoSuchFieldError: WORKBOOK_DIR_ENTRY_NAMES
	at org.apache.tika.parser.microsoft.POIFSContainerDetector.detect(POIFSContainerDetector.java:214)
	at org.apache.tika.parser.microsoft.POIFSContainerDetector.detect(POIFSContainerDetector.java:489)
	at org.apache.tika.detect.CompositeDetector.detect(CompositeDetector.java:84)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:116)
	at com.liferay.portal.tika.internal.metadata.TikaRawMetadataProcessor$ExtractMetadataProcessCallable._extractMetadata(TikaRawMetadataProcessor.java:342)
	at com.liferay.portal.tika.internal.metadata.TikaRawMetadataProcessor$ExtractMetadataProcessCallable.access$100(TikaRawMetadataProcessor.java:309)
	at com.liferay.portal.tika.internal.metadata.TikaRawMetadataProcessor._extractMetadata(TikaRawMetadataProcessor.java:250)
	at com.liferay.portal.tika.internal.metadata.TikaRawMetadataProcessor.getRawMetadataMap(TikaRawMetadataProcessor.java:104)
	at com.liferay.portal.kernel.metadata.RawMetadataProcessorUtil.getRawMetadataMap(RawMetadataProcessorUtil.java:39)
	at com.liferay.portlet.documentlibrary.util.RawMetadataProcessorImpl.saveMetadata(RawMetadataProcessorImpl.java:133)
	at com.liferay.document.library.kernel.util.RawMetadataProcessorUtil.saveMetadata(RawMetadataProcessorUtil.java:106)
	at com.liferay.portlet.documentlibrary.messaging.RawMetadataProcessorMessageListener.doReceive(RawMetadataProcessorMessageListener.java:34)
	at com.liferay.portal.kernel.messaging.BaseMessageListener.doReceive(BaseMessageListener.java:48)
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:34)
	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)
	at com.liferay.portal.messaging.internal.SerialDestination$1.run(SerialDestination.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

`WikiActivityInterpreterTest`, `WikiPageLocalServiceTest`, `WikiNodeLocalServiceTest`, `WikiPageSearchTest`, `WebDAVOSXTest`, `TextExtractorTest`, `MBAttachmentsTest`, `WikiAttachmentsTest`, `WikiPageStagedModelDataHandlerTest`, `DocumentLibraryConvertProcessTest`, `DLFileEntrySearchLegacyDDMIndexFieldsTest`, `MBMessageSearchTest`, 
```
[exec] com.liferay.wiki.service.test.WikiPageLocalServiceTest > testCopyPage FAILED
     [exec]     java.lang.IncompatibleClassChangeError: Implementing class
     [exec]     	at java.lang.ClassLoader.defineClass1(Native Method)
     [exec]     	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
     [exec]     	at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:276)
     [exec]     	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:634)
     [exec]     	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:555)
     [exec]     	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:514)
     [exec]     	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:501)
     [exec]     	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:324)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-07/test-1-29/test-portal-acceptance-pullrequest(master)/3612/modules-integration-mysql57-jdk8/3/24/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
@jeffwu0724 Please fix regression and resend.

Tina.

**Pull request closed without merging**
