### PR TITLE
LPS-153710

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-153710.
Thanks for checking.

### CODE REVIEW

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@jeffwu0724 Unit test failure here

Steps I used to reproduce
1. checkout this branch
1. ant compile
1. cd portal-impl
1. ant test-class -Dtest.class=JSONFactoryTest

**Comment by tinatian** [comment]
@jeffwu0724 I am going to close this pull, please fix failures and resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
