### PR TITLE
LPS-143632 Remove LanguageUtil isValidLanguageKey method

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
Could you please help me scan the test result?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

The reason we remove the LanguageUtil#isValidLanguageKey is we do not have corresponding method on Language interface, we would like to make it consistent to help replace ***Util by filed reference.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by julschong** [comment]
ci:forward

**Comment by julschong** [comment]
rebased to resolve conflict

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:forward

**Pull request closed without merging**
