### PR TITLE
[Components with more than 1 service] LPS-187086 Refactor components from portal-workflow-kaleo-runtime-impl and oauth2-provider-scope-impl modules

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-187086](https://liferay.atlassian.net/browse/LPS-187086)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:stable

**Comment by RenanUmV** [comment]
ci:test:workflow

**Comment by RenanUmV** [comment]
ci:test:oauth2

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
@RenanUmV See https://github.com/liferay-core-infra/liferay-portal/pull/5020

**Pull request closed without merging**
