### PR TITLE
[Convert method references]Lps 163778

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-163778

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Comment by slnn** [comment]
ci:stop

**Comment by dantewang** [comment]
RemoteMVCPortlet.render needs to be merged into MarketplaceStorePortlet.render, please resend.

**Comment by dantewang** [comment]
ci:stop

**Comment by slnn** [comment]
Resend in https://github.com/liferay-core-infra/liferay-portal/pull/2000

**Pull request closed without merging**
