### PR TITLE
LPD-25555 changed to check hidden param "captcha.enabled" to trigger captcha

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian 

This is the new solution for fixing https://liferay.atlassian.net/browse/LPD-25555

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:upstream-functional

**Comment by jeffwu0724** [comment]
no regression found in relevant test.
However, report did not get generated for upstream-functional, seems like there is some issue in testray

**Comment by jeffwu0724** [comment]
FYI, I have attached a screen record about testling this locally

https://github.com/liferay-core-infra/liferay-portal/assets/32234574/87e89073-bd4d-46c2-80ca-c0198f53e972

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7047

**Pull request closed without merging**
