### PR TITLE
LPS-199200 upgrade JSON-java to 20231013

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Shuyang, 

This is for https://liferay.atlassian.net/browse/LPS-199200.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Review by dantewang — CHANGES_REQUESTED** [review]
@jeffwu0724 Looks good to me, but could you send out a PR to run build-lib-versions on master to make the files in sync, and then rebase this PR, so that the build-lib-versions commit in this PR only contains json-java related changes?

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142566

**Pull request closed without merging**
