### PR TITLE
[System Properties]LPS-154373 Move some properties that ModuleFramework need when start

### PR DESCRIPTION
**Pull request by W2jx**
Move some properties that ModuleFramework need when start.

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
rebase

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
No regressions found.

cc/ @zhangyan0701

**Comment by tinatian** [comment]
@W2jx  See https://github.com/liferay-core-infra/liferay-portal/pull/2254, please note I did not include https://github.com/liferay-core-infra/liferay-portal/pull/2175/commits/fbc62b3aade46179d5c1e322cb29b4e610d18c1e, two reasons:
1. It is a complex commit, please separate into small pieces
2. It adds a new SystemProps class

**Comment by W2jx** [comment]
@tinatian I will resend it.

**Pull request closed without merging**
