### PR TITLE
[Remove Blocking Usages] LPS-196123 Move class DLPreviewableProcessor to modules/app/document-library-preview-api

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:document

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by W2jx** [comment]
no conflicts(10/20 8:52)

**Comment by dantewang** [comment]
@W2jx Only did a quick look on this PR. Please fix the following issues and resend:

1. Please document breaking change on the commit where you moved the classes - document it for the class that actually triggered the version bump
2. This change should only affect 7.4, so should `dl.file.entry.processors` be removed from the dtd files for 7.3 and earlier?
3. Please rename classes, `DLPreviewableProcessor` is a `DLProcessor` and an abstract class, so maybe it should be called `BasePreviewableDLProcessor`; and its sub-classes should be called `XXXPreviewableDLProcessor` or `XXXDLProcessor`.

**Pull request closed without merging**
