### PR TITLE
LPS-176754 3 7 2

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:clustering

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@Kvale1733 The SF failure is real, will be fixed by https://github.com/brianchandotcom/liferay-portal/pull/131290

**Comment by Kvale1733** [comment]
@tinatian Regressions found

1 ) com.liferay.calendar.upgrade.v2_0_0.test.UpgradeSchemaTest
```
[exec] com.liferay.calendar.upgrade.v2_0_0.test.UpgradeSchemaTest > testUpgradeCreatesCalendarBookingRecurringId FAILED
     [exec]     java.lang.NullPointerException: A null service reference is not allowed.
     [exec]     	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:622)
     [exec]     	at com.liferay.calendar.test.util.CheckBookingsMessageListenerTestUtil.setUp(CheckBookingsMessageListenerTestUtil.java:42)
     [exec]     	at com.liferay.calendar.upgrade.v2_0_0.test.UpgradeSchemaTest.setUp(UpgradeSchemaTest.java:72)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-02/test-1-38/test-portal-acceptance-pullrequest(master)/6616/modules-integration-mysql57-jdk8/0/15/jenkins-console.txt.gz?authuser=0)

2 ) com.liferay.calendar.service.test.CalendarBookingLocalServiceTest
```
 [exec] com.liferay.calendar.service.test.CalendarBookingLocalServiceTest > testAddAllDayCalendarBooking FAILED
     [exec]     java.lang.NullPointerException: A null service reference is not allowed.
     [exec]     	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:622)
     [exec]     	at com.liferay.calendar.test.util.CheckBookingsMessageListenerTestUtil.setUp(CheckBookingsMessageListenerTestUtil.java:42)
     [exec]     	at com.liferay.calendar.service.test.CalendarBookingLocalServiceTest.setUp(Cal
```
[Log](https://testray.liferay.com/reports/production/logs/2023-02/test-1-29/test-portal-acceptance-pullrequest(master)/6495/modules-integration-mysql57-jdk8/0/14/jenkins-console.txt.gz?authuser=0)

3 ) com.liferay.analytics.settings.rest.internal.manager.test.AnalyticsSettingsManagerTest
```
exec] 
     [exec] com.liferay.analytics.settings.rest.internal.manager.test.AnalyticsSettingsManagerTest > testGetCommerceChannelIds FAILED
     [exec]     java.util.ConcurrentModificationException
     [exec]     	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
     [exec]     	at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:747)
     [exec]     	at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
     [exec]     	at java.util.ArrayList.addAll(ArrayList.java:577)
     [exec]     	at com.liferay.portal.kernel.util.ListUtil.fromCollection(ListUtil.java:282)
     [exec]     	at 
```
[Log](https://testray.liferay.com/reports/production/logs/2023-03/test-1-37/test-portal-acceptance-pullrequest(master)/9603/modules-integration-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

4 ) Semver issue
```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/calendar/calendar-test-util] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.calendar.test.util                     MAJOR      3.0.0      3.0.0      4.0.0      VERSION INCREASE REQUIRED
     [exec]     	-   class      com.liferay.calendar.test.util.CheckBookingsMessageListenerTestUtil
     [exec]     		-   method     <init>()
     [exec]     			-   return     void
     [exec]     		-   method     clone()
     [exec]     			-   access     protected
     [exec]     			-   return     java.lang.Object
     [exec]     		-   method     equals(java.lang.Object)
     [exec]     			-   return     boolean
     [exec]     		-   method     finalize()
     [exec]     			-   access     protected
     [exec]     			-   return     void
     [exec]     		-   method     hashCode()
     [exec]     			-   return     int
```
[Log](https://testray.liferay.com/reports/production/logs/2023-03/test-1-37/test-portal-acceptance-pullrequest(master)/9603/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
