### PR TITLE
LPS-165597 Include emitter

### PR DESCRIPTION
**Pull request by JanisZhang**
@dantewang
This is a follow-up pull, I forgot to include the emitter in the previous reference removal task.
https://github.com/brianchandotcom/liferay-portal/pull/124663/commits/c7d07fd7b4b18696af3892362c948c6624f23416

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@JanisZhang Is there any more of this?

**Comment by JanisZhang** [comment]
@dantewang three pulls I sent have this problem, two of them are reviewed by Core, one is reported by @rafaprax (reviewed by Brain), it caused https://issues.liferay.com/browse/LPS-165953.

**Comment by zhangyan0701** [comment]
ci:test:object

**Comment by zhangyan0701** [comment]
> @JanisZhang @zhangyan0701 How didn't the original PR show any error about this... We didn't cover it in the tests?

I checked the linked tests in https://issues.liferay.com/browse/LPS-165953, they were not included in the relevant test.

**Comment by zhangyan0701** [comment]
The relevant test failures are unrelated. Will check the ci:test:objects results to make sure there is no other issues.

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found in ci:test:objects either.

**Comment by dantewang** [comment]
@JanisZhang Looks like this one is already in master?

**Comment by dantewang** [comment]
Already fixed by 2c002fa5942cc82d3f602129508a079e2a416e79

**Pull request closed without merging**
