### PR TITLE
LPS-171823 Remove Optionals usages in content-dashboard-api

### PR DESCRIPTION
**Pull request by julschong**
resubmmited from #2868

corrected incorrect caching logic in [ContentDashboardAdminDisplayContext](https://github.com/liferay-core-infra/liferay-portal/pull/2956/commits/ce6d74d7346f4d263c6f121d960e8bbaaab8366a)

### CODE REVIEW

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by tinatian** [comment]
@julschong Please rebase

**Comment by julschong** [comment]
@tinatian
only semver conflict, no new Stream/Optional usage added

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3139

**Pull request closed without merging**
