### PR TITLE
[Method References] LPS-162392 Convert method references to field references in modules portal-settings*

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I convert method references to field references in modules portal-settings*.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results when they finish ? Thanks!

**Comment by zhangyan0701** [comment]
ci:test:security

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@W2jx Please keep the proected servlet context field and directly add reference to it, and add the ds annotation inherit instruction to bnd.bnd, because all of its subclasses are referencing the same servlet context. To reduce the number of open PRs I'm going to close this one, please resend, thanks!

**Pull request closed without merging**
