### PR TITLE
[Components with more than 1 service] LPS-192202 Refactor export-import components

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:stop

**Review by rafaprax — APPROVED** [review]

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:export-import

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:export-import

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
@GabrielHenriquedev ExportImportControllerRegistryUtil is only used inside ExportImportLocalServiceImpl, the util should be inlined.

And is there a reason PortletExportController is referenced as ExportController, PortletImportController is referenced as ImportController?

If you can just reference those controllers by their own immediate interface type, you won't need to add the weird "export.controller=true" / "import.controller=true" properties for filtering.

Please make these changes and resend.

**Pull request closed without merging**
