### PR TITLE
LPS-178913 CompanyId was populated automatically to fix background ta…

### PR DESCRIPTION
**Pull request by tinatian**
…sk running when db partition is enabled by LPS-122323(77d2d5279d2ef790c0a47629fd5a21ee2003d298), remove the auto population and populate companyId manually where it is needed to decouple Message initialization from company thread local.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:acceptance-functional-db-partition

**Comment by tinatian** [comment]
FYI @achaparro

**Comment by zhangyan0701** [comment]
ci:test:acceptance-functional-db-partition

**Comment by Kvale1733** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132132

**Pull request closed without merging**
