### PR TITLE
[Method References] LPS-161455 Convert method references to field references in module portal-search-similar-results-web

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I Convert method references to field references in module portal-search-similar-results-web.

(Compared to the previous pr https://github.com/liferay-core-infra/liferay-portal/pull/1499, I rebase the code and remove the extra blank line between the two assignment logic in the test class)

Detial: https://github.com/liferay-core-infra/liferay-portal/pull/1499, https://github.com/brianchandotcom/liferay-portal/pull/122468

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results when they finish ? Thanks!

**Comment by zhangyan0701** [comment]
ci:test:search

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by tinatian** [comment]
@W2jx Next time, if it is a SF change required by Brian, just add a new commit to your original pull, do the things he required and send the pull to him directly, cc me and shuyang, no need to go the normal review process.

Thanks.
Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
