### PR TITLE
[Convert method references]Lps 163776

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-163776

Convert method references to field references in module:portal-cache-ehcache-impl with get method pattern 

https://github.com/liferay-core-infra/liferay-portal/pull/1792#issuecomment-1261573686

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Hi @Kvale1733

Thank you for catching this!

I have updated this pull by fixing the semantic version issue, could you help to rescan test results when they are finished?


For the error about FinderCacheImplTest.java:312, I do not think it caused this change, because it can be reproduced on the master:1dcf56d8a945ed677d6db6110a7f54c822adc852 which does not contain this change.



> @slnn
> 
> 1. Several modules unit tests such as **com.liferay.portal.upgrade.internal.registry.UpgradeStepRegistryTest** are failing prior to running with
> 
> ```
>  [exec] com.liferay.portal.cache.ehcache.internal.EhcachePortalCacheTest STANDARD_OUT
>      [exec]     [Whip] com.liferay.portal.cache.ehcache.internal.EhcachePortalCache is fully covered.
>      [exec]     [Whip] com.liferay.portal.cache.ehcache.internal.BaseEhcachePortalCache is fully covered.
>      [exec] Note: Some input files use unchecked or unsafe operations.
>      [exec] Note: Recompile with -Xlint:unchecked for details.
>      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-cache/portal-cache-impl/src/test/java/com/liferay/portal/cache/internal/dao/orm/FinderCacheImplTest.java:312: error: method does not override or implement a method from a supertype
>      [exec] 		@Override
>      [exec] 		^
>      [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/portal-cache/portal-cache-impl/src/test/java/com/liferay/portal/cache/internal/dao/orm/FinderCacheImplTest.java uses or overrides a deprecated API.
>      [exec] Note: Recompile with -Xlint:deprecation for details.
>      [exec] 1 error
> ```
> 
> [Example log](https://testray.liferay.com/reports/production/logs/2022-10/test-1-37/test-portal-acceptance-pullrequest(master)/5602/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)
> 
> 2. Semver errors
> 
> ```
>  [exec] > Task :apps:portal-cache:portal-cache-test-util:baseline
>      [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
>      [exec] = ================================================== ========== ========== ========== ========== ==========
>      [exec] * com.liferay.portal.cache.test.util                 MINOR      5.0.0      5.0.0      5.1.0      VERSION INCREASE REQUIRED
>      [exec] 	<   class      com.liferay.portal.cache.test.util.TestPortalCacheManager
>      [exec] 		+   method     getPortalCacheListenerFactory()
>      [exec] 			+   access     protected
>      [exec] 			+   return     com.liferay.portal.cache.PortalCacheListenerFactory
>      [exec] 		+   method     getPortalCacheManagerListenerFactory()
>      [exec] 			+   access     protected
>      [exec] 			+   return     com.liferay.portal.cache.PortalCacheManagerListenerFactory
>      [exec] [Baseline Warning] Bundle Version Change Recommended: 8.1.0
> ```
> 
> ```
>  [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/portal-cache/portal-cache-api] FAILED
>      [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
>      [exec]     = ================================================== ========== ========== ========== ========== ==========
>      [exec]     * com.liferay.portal.cache                           MAJOR      9.0.0      9.0.0      10.0.0     VERSION INCREASE REQUIRED
>      [exec]     	>   class      com.liferay.portal.cache.BasePortalCacheManager
>      [exec]     		-   field      portalCacheListenerFactory
>      [exec]     			-   access     protected
>      [exec]     			-   return     com.liferay.portal.cache.PortalCacheListenerFactory
>      [exec]     		-   field      portalCacheManagerListenerFactory
>      [exec]     			-   access     protected
>      [exec]     			-   return     com.liferay.portal.cache.PortalCacheManagerListenerFactory
>      [exec]     		+   method     getPortalCacheListenerFactory()
>      [exec]     			+   access     abstract
>      [exec]     			+   access     protected
>      [exec]     			+   return     com.liferay.portal.cache.PortalCacheListenerFactory
>      [exec]     		+   method     getPortalCacheManagerListenerFactory()
>      [exec]     			+   access     abstract
>      [exec]     			+   access     protected
>      [exec]     			+   return     com.liferay.portal.cache.PortalCacheManagerListenerFactory
>      [exec]     [Baseline Warning] Bundle Version Change Recommended: 11.0.0
> ```
> 
> [Logs](https://testray.liferay.com/reports/production/logs/2022-10/test-1-37/test-portal-acceptance-pullrequest(master)/5602/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
@slnn Please try to merge related commits into one, for example, add get*** method , apply it, remove set*** and related attribute, all these can be merged into one. 

Tina

**Comment by slnn** [comment]
Hi @tinatian 

I have merged the commits and forced push to this pull, no need rerun tests since no logic changes.

Thanks
Lily

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125741

**Comment by tinatian** [comment]
@slnn The pull sent to Brian is closed, I will need to have a talk with you.

FYI @dantewang .

Tina

**Pull request closed without merging**
