### PR TITLE
LPS-178732 LPS-176550 cause about -3.18% performance regression 6-20

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@zhangyan0701 It seems https://liferay.atlassian.net/browse/LRQA-81076 is not done yet. Could you manually verify the feature flag functionality on cluster like in previous PRs? Thanks!

**Comment by zhangyan0701** [comment]
ci:test:peds-sm

**Comment by zhangyan0701** [comment]
No regressions found.

@dantewang The manual testing also passed on Cluster + Feature Flags.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4831

**Pull request closed without merging**
