### PR TITLE
[Remove Blocking usages]LPS-200478 

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace blocking ServiceProxyFactory with Snapshot in class `WorkflowInstanceManagerUtil`.Thanks.
https://liferay.atlassian.net/browse/LPS-200478

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
Reviewing...

**Comment by melodywu** [comment]
The [relevant](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2450951319) and [startup](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2450259360) results are look good to me.

cc @zhangyan0701

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
