### PR TITLE
LPS-171052 | LPS-171053 | LPS-171054 As a power user, I want to have dedicated permissions generated for my standalone actions

### PR DESCRIPTION
**Pull request by marcelabc**
https://issues.liferay.com/browse/LPS-171054
https://issues.liferay.com/browse/LPS-171053
https://issues.liferay.com/browse/LPS-171052

cc: @carolmariaabb

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@marcelabc Why you have to add the resource actions at runtime rather than at deploy time? https://github.com/liferay-core-infra/liferay-portal/pull/2852/commits/36941a87677bec1272d3b2b92800b76fd3607b99

**Comment by tinatian** [comment]
@marcelabc Also, I do not think LPS-171054 is related to others, please ask your team to review and forward it.

Tina.

**Comment by marcelabc** [comment]
Hi @tinatian :smile: 
Sorry for not describing the details! This story implementation is related to creating dedicated permissions when the user creates standalone actions (https://issues.liferay.com/browse/LPS-169994). There are 2 moments that we have to check if exists the standalone actions, so we will have to create the dedicated permissions: 

1. When publishing an Object
2. When the user creates a standalone action after the object is published

**Comment by marcelabc** [comment]
> Also, I do not think LPS-171054 is related to others, please ask your team to review and forward it.

The team decided to send all the work together and we have already reviewed it. After the core-infra review, we will forward it to Brian :+1:

**Comment by tinatian** [comment]
@marcelabc 
1. Generally you should not remove resource action, that's why we do not have a api to remove. Every resource action has a bitwiseValue, and it is used to calculate the actionIds in ResourcePermission. So if you really want to remove, please make sure you remove all the resource permissions calculated from the resource actions you want to remove, I did not see this part of logic in your code.
2. If you decided not to do remove, then for the add action, you can achieve the goal using ResourceActions.populate*** method, this way, you won't need to modify ResourceActions api.

Tina

**Comment by tinatian** [comment]
@marcelabc As we talked, I am going to close this pull, please resend.

Thanks.
Tina.

**Pull request closed without merging**
