### PR TITLE
Lps 150076 4 7

### PR DESCRIPTION
**Pull request by slnn**
@tinatian @dantewang

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by tinatian** [comment]
FYI @BryanEngler This is going to improve the performance of login test case by 7%, the core of this change is at https://github.com/liferay-core-infra/liferay-portal/pull/573/commits/2b1d8a106a7a2775997d34498ff148bcaf814532.

Tina.

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
