### PR TITLE
LPS-142278 deprecate portal lib dir | rebased

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou @tinatian rebased

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@tinatian This should be good to go.

Documenting that there are 2 unique failures, but they are not reproducible locally.
https://testray.liferay.com/home/-/testray/case_results/1588796117
https://testray.liferay.com/home/-/testray/case_results/1588797695

**Comment by shuyangzhou** [comment]
@dantewang please remove all the newly deprecated methods. Since 7.4, we don't need to deprecate backend api, free to kill.

**Comment by dantewang** [comment]
ci:close

see https://github.com/liferay-core-infra/liferay-portal/pull/66

**Pull request closed without merging**
