### PR TITLE
Lps 194989 9 1

### PR DESCRIPTION
**Pull request by slnn**
Resend according to https://github.com/brianchandotcom/liferay-portal/pull/140063#issuecomment-1701915517

1>Rename the test to AddUsersByAPIPerformanceTest
2>Embed the JSON template by using  JSONUtil.put()

/cc @dantewang @shuyangzhou

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:help

**Comment by catarineaguiar** [comment]
ci:test:headless

**Comment by dantewang** [comment]
@catarineaguiar This integration test won't run on CI, so only source code checks can be related, like source-formatter.

**Comment by catarineaguiar** [comment]
hey @dantewang, the test passed on relevant. [see](https://testray.liferay.com/home/-/testray/case_results/2417423301?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2417421503%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) 

no regressions were found

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140291

**Pull request closed without merging**
