### PR TITLE
[SampleSQLBuilder-Object]Lpd 37967 12 17

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:relevant

**Review by dantewang — DISMISSED** [review]

**Comment by dantewang** [comment]
@slnn Web Content has 6 pages, each with a display portlet pointing to a unique journal article in the DB. With this change, does the object pages do the same?

**Comment by slnn** [comment]
Hi @dantewang 

No, Object page will have 6 content pages, each page showing the same 10 object entries, it means that the total object entry count is 10 ,instead of 6*10 = 60

**Comment by slnn** [comment]
Update junit test

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:95684140

**Comment by dantewang** [comment]
@slnn The SampleSQLBuilderTest failed.

**Comment by slnn** [comment]
Fix in https://github.com/liferay-core-infra/liferay-portal/pull/7790

**Pull request closed without merging**
