### PR TITLE
[Bug fix] LPS-163456 Failure in com.liferay.vldap.server.internal.portal.security.auth.SambaAuthTest

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have fixed the bug about SambaAuthTest.

Detial: https://issues.liferay.com/browse/LPS-163456

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@zhangyan0701 Could you double check why this is not caught in the original PR's CI tests?

**Comment by W2jx** [comment]
Hi @zhangyan0701 , this is the original [PR](https://github.com/liferay-core-infra/liferay-portal/pull/1603).

**Comment by zhangyan0701** [comment]
> @zhangyan0701 Could you double check why this is not caught in the original PR's CI tests?

I double checked the result, the test actually failed in the original PR, but the relevant results showed successfully somehow https://github.com/liferay-core-infra/liferay-portal/pull/1603#issuecomment-1240620790. I haven't seen this kind of problem, but we will need to be more careful. If this happens again, will need CI team to take a look.

**Comment by zhangyan0701** [comment]
Test com.liferay.vldap.server.internal.portal.security.auth.SambaAuthTest passed:
https://testray.liferay.com/home/-/testray/case_results/1985167753

**Comment by dantewang** [comment]
@tinatian @shuyangzhou Forwarding this because it's a simple test fix for a regression caused by a previous method reference to field reference pull request.

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
