### PR TITLE
LPD-8475 Remove unused reference from ConfigurationSynchronousConfigurationListener

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by dantewang** [comment]
Putting this on hold because we have plan to completely remove the message bus usage in this class, see https://github.com/liferay-core-infra/liferay-portal/pull/6676

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6737

**Pull request closed without merging**
