### PR TITLE
LPD-20946 Resource actions

### PR DESCRIPTION
**Pull request by dantewang**
Resend to rebase and run CI.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:report:2563568158

**Comment by dantewang** [comment]
upgrade result csv shows no unique error.

**Comment by dantewang** [comment]
ci:report:2563587715

**Comment by dantewang** [comment]
ci:report:2563589358

**Comment by dantewang** [comment]
@tinatian 

3 unique failures in relevant:

```
com.liferay.object.rest.internal.resource.v1_0.test.OpenAPIResourceTest
com.liferay.object.service.test.ObjectFolderLocalServiceTest
com.liferay.object.admin.rest.resource.v1_0.test.ObjectDefinitionVulcanBatchEngineTaskItemDelegateTest
```

There are many places in the object integration tests where the code call `ObjectDefinitionLocalService.deleteObjectDefinition(ObjectDefinition)`. If I replace all those calls with the version of method that takes the `objectDefinitionId`, I can get `ObjectFolderLocalServiceTest` to pass. The reason is in the commit message of https://github.com/liferay-core-infra/liferay-portal/pull/6918/commits/62c6897bdf1db339de7f3cbe64e746631e103e75.

And last time I had trouble figuring out what's the cause of `OpenAPIResourceTest`. It fails when running all tests in that test module, but passes when being run alone.

I pushed an experiment commit to verify this idea.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:2563877600

**Comment by dantewang** [comment]
ci:report:2563877600

**Comment by dantewang** [comment]
@tinatian Update: the experiment commit eliminates the previous unique failures in relevant.

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:report:2563899660

**Comment by dantewang** [comment]
ci:report:2563899660

**Comment by dantewang** [comment]
ci:report:2563899660

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6946

**Pull request closed without merging**
