### PR TITLE
[Defaul Password] LPD-25521 Adapt tests using hard-coded test password in Liferay Faces component

### PR DESCRIPTION
**Pull request by julschong**
https://liferay.atlassian.net/browse/LPD-25521

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:report:2570742273

**Comment by julschong** [comment]
@tinatian No unique regression. The faces test fails the same way as before https://testray.liferay.com/home/-/testray/case_results/2570770348?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2570742273%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc

This is ready to go

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
