### PR TITLE
LPS-172965 SF, optimize in LDAPConfigurationListener

### PR DESCRIPTION
**Pull request by JanisZhang**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by JanisZhang** [comment]
ci:forward

**Comment by JanisZhang** [comment]
Thanks @zhangyan0701 !

**Comment by dantewang** [comment]
ci:forward

**Comment by JanisZhang** [comment]
Hi @dantewang, network issues caused CI failures, and numerous instances of builds failed. 
Forwarded this to https://github.com/brianchandotcom/liferay-portal/pull/128893
Thanks!

**Comment by dantewang** [comment]
@JanisZhang Thanks!

**Pull request closed without merging**
