### PR TITLE
[Components with more than 1 service] LPS-192993 Refactor ManagedServiceFactory from oauth2-provider-rest, document-library-service, document-library-preview-pdf and portal-security-sso-openid-connect-impl modules

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-192993](https://liferay.atlassian.net/browse/LPS-192993)

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:security

**Comment by Kvale1733** [comment]
ci:test:document

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
@RenanUmV  possible regressions:

```
     [exec] com.liferay.document.library.trash.test.DLFolderTrashHandlerTest > testMoveBaseModelToTrash FAILED
     [exec]     java.lang.AssertionError: expected:<0> but was:<1>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:633)
     [exec]     	at com.liferay.trash.test.util.BaseTrashHandlerTestCase.testMoveBaseModelToTrash(BaseTrashHandlerTestCase.java:121)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-08/test-1-32/test-portal-acceptance-pullrequest(master)/1688/modules-integration-mysql57-jdk8/0/5/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.document.library.webdav.test.WebDAVLitmusCopyMoveTest > test04CopyShallow FAILED
     [exec]     java.lang.AssertionError: expected:<201> but was:<405>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:633)
     [exec]     	at com.liferay.document.library.webdav.test.BaseWebDAVTestCase.assertCode(BaseWebDAVTestCase.java:46)
     [exec]     	at com.liferay.document.library.webdav.test.WebDAVLitmusCopyMoveTest.test04CopyShallow(WebDAVLitmusCopyMoveTest.java:131)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-08/test-1-32/test-portal-acceptance-pullrequest(master)/1688/modules-integration-mysql57-jdk8/0/5/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.document.library.trash.test.DLFolderTrashHandlerTest > testMoveBaseModelToTrash FAILED
     [exec]     java.lang.AssertionError: expected:<0> but was:<1>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:633)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-08/test-1-32/test-portal-acceptance-pullrequest(master)/1688/modules-integration-mysql57-jdk8/0/5/jenkins-console.txt.gz?authuser=0)

**Comment by RenanUmV** [comment]
Hi @catarineaguiar, I ran the tests locally and they passed:

`com.liferay.document.library.trash.test.DLFolderTrashHandlerTest > testMoveBaseModelToTrash STARTED

com.liferay.document.library.trash.test.DLFolderTrashHandlerTest > testMoveBaseModelToTrash PASSED`

`com.liferay.document.library.webdav.test.WebDAVLitmusCopyMoveTest > test04CopyShallow STARTED

com.liferay.document.library.webdav.test.WebDAVLitmusCopyMoveTest > test04CopyShallow PASSED`

**Comment by RenanUmV** [comment]
ci:test:document

**Comment by Kvale1733** [comment]
@RenanUmV Regression found. This is failing consistently with these changes. Reproduced locally also.

This test times out waiting for a service

com.liferay.document.library.internal.configuration.admin.service.test.DLSizeLimitManagedServiceFactoryTest
```
 [exec] 
     [exec] com.liferay.document.library.internal.configuration.admin.service.test.DLSizeLimitManagedServiceFactoryTest > testGetCompanyMimeTypeSizeLimitSpecificValue STARTED
[beanshell] Waiting for service org.osgi.service.cm.ManagedServiceFactory component.name=com.liferay.document.library.internal.configuration.admin.service.DLSizeLimitManagedServiceFactory for field com.liferay.document.library.internal.configuration.admin.service.test.DLSizeLimitManagedServiceFactoryTest._managedServiceFactory
[beanshell] Waiting for service org.osgi.service.cm.ManagedServiceFactory component.name=com.liferay.document.library.internal.configuration.admin.service.DLSizeLimitManagedServiceFactory for field com.liferay.document.library.internal.configuration.admin.service.test.DLSizeLimitManagedServiceFactoryTest._managedServiceFactory
[beanshell] Waiting for service org.osgi.service.cm.ManagedServiceFactory component.name=com.liferay.document.library.internal.configuration.admin.service.DLSizeLimitManagedServiceFactory for field com.liferay.document.library.internal.configuration.admin.service.test.DLSizeLimitManagedServiceFactoryTest._managedServiceFactory
[beanshell] Waiting for service org.osgi.service.cm.ManagedServiceFactory component.name=com.liferay.document.library.internal.configuration.admin.service.DLSizeLimitManagedServiceFactory for field com.liferay.document.library.internal.configuration.admin.service.test.DLSizeLimitManagedServiceFactoryTest._managedServiceFactory
[beanshell] Waiting for service org.osgi.service.cm.ManagedServiceFactory component.name=com.liferay.document.library.internal.configuration.admin.service.DLSizeLimitManagedServiceFactory for field com.liferay.document.library.internal.configuration.admin.service.test.DLSizeLimitManagedServiceFactoryTest._managedServiceFactory
[beanshell] 1 hour 49 minutes until timeout.
[beanshell] Waiting for service org.osgi.service.cm.ManagedServiceFactory component.name=com.liferay.document.library.internal.configuration.admin.service.DLSizeLimitManagedServiceFactory for field com.liferay.document.library.internal.configuration.admin.service.test.DLSizeLimitManagedServiceFactoryTest._managedServiceFactory
[beanshell] Waiting for service org.osgi.service.cm.ManagedServiceFactory component.name=com.liferay.document.library.internal.configuration.admin.service.DLSizeLimitManagedServiceFactory for field com.liferay.document.library.internal.configuration.admin.service.test.DLSizeLimitManagedServiceFactoryTest._managedServiceFactory
```
[Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-32/test-portal-acceptance-pullrequest(master)/1727/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
@RenanUmV The failure is either due to wrong inject target in the integration test, or the outer component is lazy so it's not activated when the integration test starts. Please fix the failure and resend, thanks.

**Pull request closed without merging**
