### PR TITLE
[Bug fix] LPS-147596

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@zhangyan0701 Could you please review the test results when they finish? Thanks!

**Comment by zhangyan0701** [comment]
Hi @catarineaguiar Could you check the results when the tests finish? Especially the com.liferay.external.data.source.test.controller.test that linked in [LPS-147596](https://issues.liferay.com/browse/LPS-147596). I also run them in https://github.com/zhangyan0701/liferay-portal/pull/403 just in case.

**Comment by catarineaguiar** [comment]
@dantewang no regressions.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
