### PR TITLE
LPS-145600

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian, @shuyangzhou ,

Resend. Fixed the SF failture that had a properties that is too long in verifyproperties.java.
I have removed unused properties "multi.value.map.", which included
"multi.value.map.com.liferay.portal.convert.ConvertPermissionAlgorithm.convertResourcePermission" and "multi.value.map.com.liferay.portal.convert.ConvertPermissionAlgorithm.convertRoles", and updated to propskeys.java, propsvalues.java and verifyproperties.java.

It was added as a comment in commit 679a007, see LPS-16204.
Renamed to the current name in commit 438c68b, see LPS-16204.
It was used by the prefix "MULTI_VALUE_MAP" by "multi.value.map." in commit 679a007, see LPS-16204.
It was finally deleted the use in "ConvertPermissionAlgorithm.java" based on commit d7c844a, see LPS-26306
Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@jeffwu0724 Please merge the three commits into one and resend. You actually made the changes in the first commit and the second and third commit are actually fixing the SF failure. In this case, the commit message for second and third commit are not accurate.

Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
