### PR TITLE
[TS] LPD-1721

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:2544120652

**Comment by ericyanLr** [comment]
**ci:report analysis**
No unique failures

Marking this PR as **QA Passed** and **Ready to Review (no regression)**

/cc @tinatian

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6702

**Pull request closed without merging**
