### PR TITLE
Lps 153305 move verifyProperties and some properties that moduleFramework need when init

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:lpkg

**Comment by W2jx** [comment]
@zhangyan0701  Could you review the test results? Thanks!

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:acceptance

**Comment by W2jx** [comment]
Hi @dantewang , This is my latest test result after adding the missing properties module.framework.state.dir and module.framework.services.ignored.interfaces(it is needed during module framework register context). And now the env properties has not been added automatically.

**Comment by zhangyan0701** [comment]
There are some failures look related:

1: Error when start release bundle after preparing system properties:
```
[beanshell] 2022-05-25 10:45:05.471 INFO  [main][ModuleFrameworkImpl:1245] Starting initial bundles
[beanshell] 2022-05-25 10:45:05.664 ERROR [main][PortalContextLoaderListener:79] null
[beanshell] java.lang.NullPointerException: null
```
Failed tests: 
[portal-second-startup-space-in-path-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1859923713)
[release-osgi-state-lpkg-change-directory-test-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1859923632)

Example full console:
https://testray.liferay.com/reports/production/logs/2022-05/test-1-35/test-portal-acceptance-pullrequest(master)/1645/release-osgi-state-lpkg-change-directory-test-jdk8/0/0/jenkins-console.txt.gz?authuser=0

2: Some errors in LPKG related tests:
Examples:
```
     [exec] com.liferay.portal.lpkg.deployer.LPKGVersionChangeLogAssertorTest STANDARD_OUT
     [exec]     Loading jar:file:/opt/dev/projects/github/liferay-portal/.m2/com/liferay/portal/com.liferay.portal.impl/40.0.0-SNAPSHOT/com.liferay.portal.impl-40.0.0-SNAPSHOT.jar!/system.properties
     [exec]     Loading jar:file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.56/webapps/ROOT/WEB-INF/shielded-container-lib/portal-impl.jar!/system.properties
     [exec]     Loading file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.56/webapps/ROOT/WEB-INF/classes/system-ext.properties
     [exec]     Loading jar:file:/opt/dev/projects/github/liferay-portal/.m2/com/liferay/portal/com.liferay.portal.impl/40.0.0-SNAPSHOT/com.liferay.portal.impl-40.0.0-SNAPSHOT.jar!/portal.properties
     [exec]     Loading file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.56/webapps/ROOT/WEB-INF/classes/portal-ext.properties
     [exec] 
     [exec] com.liferay.portal.lpkg.deployer.LPKGVersionChangeLogAssertorTest > testUpgradeLog STARTED
     [exec] 
     [exec] com.liferay.portal.lpkg.deployer.LPKGVersionChangeLogAssertorTest > testUpgradeLog FAILED
     [exec]     java.nio.file.NoSuchFileException: /opt/dev/projects/github/liferay-portal/modules/apps/static/portal-lpkg-deployer/portal-lpkg-deployer-test/liferay/osgi/marketplace
```

```
     [exec] com.liferay.portal.lpkg.deployer.persistence.test.LPKGPersistenceVerifyUpgradeTest STANDARD_OUT
     [exec]     Loading jar:file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.56/webapps/ROOT/WEB-INF/shielded-container-lib/portal-impl.jar!/system.properties
     [exec]     Loading jar:file:/opt/dev/projects/github/liferay-portal/.m2/com/liferay/portal/com.liferay.portal.impl/40.0.0-SNAPSHOT/com.liferay.portal.impl-40.0.0-SNAPSHOT.jar!/system.properties
     [exec]     Loading file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.56/webapps/ROOT/WEB-INF/classes/system-ext.properties
     [exec] 
     [exec] com.liferay.portal.lpkg.deployer.persistence.test.LPKGPersistenceVerifyUpgradeTest > testVerifyBundleUpgradePersistence STARTED
     [exec] 
     [exec] com.liferay.portal.lpkg.deployer.persistence.test.LPKGPersistenceVerifyUpgradeTest > testVerifyBundleUpgradePersistence FAILED
     [exec]     java.lang.AssertionError
```
```
     [exec] com.liferay.portal.lpkg.deployer.container.test.LPKGContainerVerifyTest STANDARD_OUT
     [exec]     Loading jar:file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.56/webapps/ROOT/WEB-INF/shielded-container-lib/portal-impl.jar!/system.properties
     [exec]     Loading jar:file:/opt/dev/projects/github/liferay-portal/.m2/com/liferay/portal/com.liferay.portal.impl/40.0.0-SNAPSHOT/com.liferay.portal.impl-40.0.0-SNAPSHOT.jar!/system.properties
     [exec]     Loading file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.56/webapps/ROOT/WEB-INF/classes/system-ext.properties
     [exec] 2022-05-25 10:28:16.475 INFO  [Arquillian-Connector-Thread][BundleStartStopLogger:46] STARTED com.liferay.portal.lpkg.deployer.test_1.0.0 [1462]
     [exec] 2022-05-25 10:28:16.554 INFO  [Arquillian-Connector-Thread][BundleStartStopLogger:49] STOPPED com.liferay.portal.lpkg.deployer.test_1.0.0 [1462]
     [exec] 
     [exec] 1 test completed, 1 failed
     [exec] 
     [exec] com.liferay.portal.lpkg.deployer.container.test.LPKGContainerVerifyTest > testLPKGController STARTED
     [exec] 
     [exec] com.liferay.portal.lpkg.deployer.container.test.LPKGContainerVerifyTest > testLPKGController FAILED
     [exec]     java.lang.AssertionError: Inner LPKG bundle not installed
```

Failed tests: 
[lpkg-startup-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1859919919)
[lpkg-persistence-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1832353431)
[lpkg-override-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1859919925)
[lpkg-controller-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1859919881)
[lpkg-container-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1859919840)

Example full consoles:
https://testray.liferay.com/reports/production/logs/2022-05/test-1-38/test-portal-acceptance-pullrequest(master)/399/lpkg-persistence-jdk8/0/0/jenkins-console.txt.gz?authuser=0
https://testray.liferay.com/reports/production/logs/2022-05/test-1-35/test-portal-acceptance-pullrequest(master)/1645/lpkg-container-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Pull request closed without merging**
