### PR TITLE
Lpd 29628 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:core-functional

**Comment by ericyanLr** [comment]
Hey @tinatian, 

Confirmed, the changes in this PR does not cause a regression for the previous ticket: [LPS-201574/LPD-2121](https://liferay.atlassian.net/browse/LPD-2121)
- Tested using the steps to reproduce in the previous ticket

**Comment by dantewang** [comment]
ci:report:27110588

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:27130961

**Comment by dantewang** [comment]
ci:report:27166996

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:27274284

**Comment by dantewang** [comment]
ci:report:27274284

**Comment by dantewang** [comment]
@tinatian No unique failure in ci-test-relevant. core-functional marked several unique failures, looking into them.

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 27166996.
> 
> Job Link: [generate-testray-csv](https://test-1-36.liferay.com/job/generate-testray-csv/271/)
> 
> Testray CSV Link: [testray-results-27166996.csv](https://test-1-36.liferay.com/userContent/jobs/generate-testray-csv/builds/271/testray-results-27166996.csv)

- `LocalFile.CompanyLogging#*`: not unique, same errors happening in other CI routines
- `LocalFile.ModuleFrameworkServlet#ServletMultipartConfigInShieldedContainer`: marked as unique, but it's a `curl` execution error, will cross check on other PR result
- `LocalFile.GogoShell#SiteAdminCannotAccessGogoShellPortlet`: execution error, will cross check
- `LocalFile.OSGIConfiguration#CanCreatePartitionedVirtualInstanceViaConfig`: not unique, same errors happening in other CI routines
- `LocalFile.ClusteringCache#CanSessionReplicateBetweenNodes`: will cross check

**Comment by dantewang** [comment]
Cross checked the results in another PR, the above-mentioned unique failures are marked as common ones with the same errors. https://github.com/liferay-core-infra/liferay-portal/pull/7195#issuecomment-2194350076

So, no unique failure.

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
