### PR TITLE
LPS-168539 Use BundleUtil.getBundle method instead of repeating its code again and again

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
After implementing the test for [LPS-166969](https://issues.liferay.com/browse/LPS-166969) (see https://github.com/liferay-search/liferay-portal/pull/626) I have realized that we are repeating the BundleUtil.getBundle method code everywhere.

In this PR I am replacing all the repeated code with a direct call to BundleUtil.getBundle

### CODE REVIEW

**Comment by Kvale1733** [comment]
@jorgediaz-lr No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

Do you have any updates about this PR?

Thank you

**Comment by tinatian** [comment]
@jorgediaz-lr 
Sorry about the late response.

I do not want this to be applied to everywhere as this BundleUtil comes from portal-impl, if it is a general tool for both modules and portal-impl, it should be moved to portal-kernel. If it is only used by modules, then it should be in a static module rather than portal-impl.

Either way, the current pull does not make sense to me, it is not your changes, it is about the BundleUtil added earlier. We need a central place to put this and apply. I currently do not have time to work on this and provide more suggestions.

As there is code conflict, I am going to close this pull and if you still want to centralize the usages, please send a new one, but you should move BundleUtil to a reasonable place first.

Thnaks.
Tina

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

Thanks for your comment. I will review the code and think in an alternative.

**Comment by jorgediaz-lr** [comment]
Resent here: https://github.com/jorgediaz-lr/liferay-portal/pull/512

**Pull request closed without merging**
