### PR TITLE
[Static reference] LPS-181673 Remove method reference by using snapshot in modules frontend-data-set, frontend-taglib

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Review by dantewang — CHANGES_REQUESTED** [review]
@W2jx Similar here. Please clean up unused methods first, and then do the rename, etc., and then apply Snapshot.

**Comment by W2jx** [comment]
Hi @dantewang , I have update them.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:frontend

**Comment by W2jx** [comment]
no conflicts(4/17 8:08)

**Comment by W2jx** [comment]
no conflicts(4/18 9:28)

**Comment by catarineaguiar** [comment]
@W2jx failure when deploying frontend-data-set/frontend-data-set-sample-web

```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/frontend-data-set/frontend-data-set-sample-web/src/main/java/com/liferay/frontend/data/set/sample/web/internal/fdsviewserializer/util/FDSViewSerializerUtil.java:18: error: package com.liferay.osgi.util.service does not exist
     [exec] import com.liferay.osgi.util.service.Snapshot;
     [exec]                                     ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/frontend-data-set/frontend-data-set-sample-web/src/main/java/com/liferay/frontend/data/set/sample/web/internal/fdsviewserializer/util/FDSViewSerializerUtil.java:29: error: cannot find symbol
     [exec] 	private static final Snapshot<FDSViewSerializer>
     [exec] 	                     ^
     [exec]   symbol:   class Snapshot
     [exec]   location: class com.liferay.frontend.data.set.sample.web.internal.fdsviewserializer.util.FDSViewSerializerUtil
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/frontend-data-set/frontend-data-set-sample-web/src/main/java/com/liferay/frontend/data/set/sample/web/internal/fdsviewserializer/util/FDSViewSerializerUtil.java:30: error: cannot find symbol
     [exec] 		_fdsViewSerializerSnapshot = new Snapshot<>(
     [exec] 		                                 ^
     [exec]   symbol:   class Snapshot
     [exec]   location: class com.liferay.frontend.data.set.sample.web.internal.fdsviewserializer.util.FDSViewSerializerUtil
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/frontend-data-set/frontend-data-set-sample-web/src/main/java/com/liferay/frontend/data/set/sample/web/internal/view/CustomizedTableFDSView.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 3 errors
     [exec] 180 actionable tasks: 138 executed, 42 up-to-date
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10651/modules-compile-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
