### PR TITLE
[TS] LPP-46038 > LPS-158795 Trimming the url before testing

### PR DESCRIPTION
**Pull request by ces-totrinh**
Hi @tinatian @dantewang,
@hongvo2308 updated the code based on your comments, please help take a look again. Thanks.

The previous requests:
https://github.com/liferay-core-infra/liferay-portal/pull/1152
https://github.com/liferay-core-infra/liferay-portal/pull/1164

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
@tototrinh Code looks good to me, wait for QA to scan test results.
@catarineaguiar Please help me scan test results.

Thanks.
Tina.

**Comment by catarineaguiar** [comment]
@tototrinh @tinatian no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
