### PR TITLE
[TS] LPS-188642

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the previous pr is https://github.com/liferay-core-infra/liferay-portal/pull/5180.

I tried to delegate the -Djava.util.logging.config.file to the new process. But it existed ClassNotFound issue due to some custom configuration in the tomcatHome/conf/logging.properties, for example, `.handlers = 1catalina.org.apache.juli.AsyncFileHandler`. Tomcat uses [JULI ](https://tomcat.apache.org/tomcat-9.0-doc/logging.html)as logging framework. LogManager is [ClassLoaderLogManager](https://github.com/apache/tomcat/blob/9.0.x/java/org/apache/juli/ClassLoaderLogManager.java#L49).

So I only change the default logging.properties to fix the output.

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@yuhai No regressions found. Testing passed following the ticket steps.
[Gist](https://gist.github.com/Kvale1733/ffa87d8497103c9358d1c5810f0fd9fe)

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
@yuhai @dantewang What is the root cause? Why change jdk log properties works?

**Comment by yuhai** [comment]
> @yuhai @dantewang What is the root cause? Why change jdk log properties works?

@tinatian, the root issue is that we use JDK log to output log in the new process and logging.properties will be loaded as JDK config file. We didn't define handlers for the other loggers. The handlers `org.apache.catalina.core.ContainerBase.[Catalina].handlers=java.util.logging.ConsoleHandler` only is for the specific logger(org.apache.catalina.core.ContainerBase.[Catalina]). For the other loggers, any level logs(error, warn..) can't output.

**Comment by tinatian** [comment]
@yuhai As talked with Dante, please resend.

Thanks.
Tina.

**Pull request closed without merging**
