### PR TITLE
[Components with more than 1 service] LPS-195086 Refactor DLSizeLimitManagedServiceFactory component

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-195086](https://liferay.atlassian.net/browse/LPS-195086)

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:lima

**Comment by RenanUmV** [comment]
ci:test:document

**Review by rafaprax — APPROVED** [review]

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@RenanUmV No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140421

**Pull request closed without merging**
