### PR TITLE
LPS-191310 Call runSQL method that takes a connection reference. Because the method without it would not complete the query

### PR DESCRIPTION
**Pull request by devpedrotavares**
Hi team,

Related bug: [LPS-191310](https://liferay.atlassian.net/browse/LPS-191310)

## Purpose
Call the `runSQL` method that receives the `Connection` reference.

## Motivation
**Bug overview:** It is not possible to delete one-to-many object relationships when using **SQLServer**.

Prior to this change, the [_dropDefaultConstraint](https://github.com/liferay/liferay-portal/blob/6ce0b9eb049e99a50285a324a3bd4afd76d340ab/modules/dxp/apps/portal/portal-dao-db/src/main/java/com/liferay/portal/dao/db/SQLServerDB.java#L460) method would not complete its execution. This is why, as described in the mentioned ticket, when attempting to delete the `ObjectRelationship`, nothing happens on the UI and there are no logs in Tomcat. 

Thank you in advance!

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:environments

**Comment by Kvale1733** [comment]
@devpedrotavares No regressions found. Testing passed following the ticket steps on sqlserver 2019.

**Comment by murilostodolni** [comment]
@zhangyan0701 @Kvale1733 can we forward this change? Thank you in advanced.

**Comment by zhangyan0701** [comment]
> @zhangyan0701 @Kvale1733 can we forward this change? Thank you in advanced.

Hi @murilostodolni After QA Passed label added, devs in the team will review the changes, if they approve, we can forward.

**Comment by marcelabc** [comment]
Hi @liferay-core-infra,
Do you have any updates in the review of this PR?
Thank you.

**Comment by marcelabc** [comment]
Hi @tinatian,
This PR is related to [LPS-191310](https://liferay.atlassian.net/browse/LPS-191310). This ticket is a regression from [LPS-170496](https://liferay.atlassian.net/browse/LPS-170496). This PR is just improving the code from LPS-170496 by adding the "**connection**" parameter in the runSQL() method. Look that [LPS-170496 PR](https://github.com/liferay-core-infra/liferay-portal/pull/2647) has been reviewed and approved  (and received a compliment from Brian [here](https://github.com/liferay-core-infra/liferay-portal/pull/2647#issuecomment-1340110477)) before without tests.

Could you review the code, please? Or do you need any specific information? :smile:

**Pull request closed without merging**
