### PR TITLE
[Equinox] LPS-184766 Part 2 Inline Activator related logic

### PR DESCRIPTION
**Pull request by dantewang**
including https://github.com/liferay-core-infra/liferay-portal/pull/5306

### CODE REVIEW

**Comment by Kvale1733** [comment]
@dantewang No regressions found.

**Comment by shuyangzhou** [comment]
@dantewang please rebase against upstream once https://github.com/liferay-core-infra/liferay-portal/pull/5401 is in

**Comment by dantewang** [comment]
@shuyangzhou Got it.

**Comment by dantewang** [comment]
Close, will resend.

**Pull request closed without merging**
