### PR TITLE
[Method References 2] LPS-164204 Remove unused reference variable in module segments-experiment-web(dxp)

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang, I Remove unused reference variable in module segments-experiment-web(dxp)

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @catarineaguiar , Could you please help me check the test results ? Thanks!

**Comment by W2jx** [comment]
Force-Push is just to rebase the code.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@W2jx Conflicts, please rebase.

**Comment by W2jx** [comment]
Hi @dantewang , I have rebased the code.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
