### PR TITLE
LPS-155670 Remove getLibDir method from PropsUtil

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@julschong regressions found:

```
 [junit] Testcase: testGetPortletRenderPartsWithFastLoad(com.liferay.portal.kernel.portlet.render.PortletRenderUtilTest):	FAILED
    [junit] Actual string /combo?minifierType=css&themeId=theme_id&com.liferay.portlet.1:/o/portlet-web/header-portlet.css&/header-portal.css&t=8
    [junit] junit.framework.AssertionFailedError: Actual string /combo?minifierType=css&themeId=theme_id&com.liferay.portlet.1:/o/portlet-web/header-portlet.css&/header-portal.css&t=8
    [junit] 	at com.liferay.portal.kernel.portlet.render.PortletRenderUtilTest._assertEquals(PortletRenderUtilTest.java:279)
    [junit] 	at com.liferay.portal.kernel.portlet.render.PortletRenderUtilTest.testGetPortletRenderPartsWithFastLoad(PortletRenderUtilTest.java:224)
    [junit] 
```
```
 [junit] Testcase: testGetPathURIFromURLWithUnknownProtocol(com.liferay.portal.kernel.util.ClassUtilTest):	FAILED
    [junit] expected same:<class com.liferay.portal.kernel.exception.SystemException> was not:<class java.lang.NoSuchMethodException>
    [junit] junit.framework.AssertionFailedError: expected same:<class com.liferay.portal.kernel.exception.SystemException> was not:<class java.lang.NoSuchMethodException>
    [junit] 	at com.liferay.portal.kernel.util.ClassUtilTest.testGetPathURIFromURLWithUnknownProtocol(ClassUtilTest.java:246)
    [junit] 	at com.liferay.portal.kernel.test.rule.CodeCoverageAssertor$1.evaluate(CodeCoverageAssertor.java:81)
```
```
[junit] Testcase: testGetPathURIFromURL(com.liferay.portal.kernel.util.ClassUtilTest):	Caused an ERROR
    [junit] No method on null with name _getPathURIFromURL and parameter types [class java.net.URL]
    [junit] java.lang.NoSuchMethodException: No method on null with name _getPathURIFromURL and parameter types [class java.net.URL]
    [junit] 	at com.liferay.portal.kernel.test.ReflectionTestUtil.getMethod(ReflectionTestUtil.java:190)
    [junit] 	at com.liferay.portal.kernel.test.ReflectionTestUtil.invoke(ReflectionTestUtil.java:199)
    [junit] 	at com.liferay.portal.kernel.util.ClassUtilTest._testGetPathURIFromURL(ClassUtilTest.java:368)
    [junit] 	at com.liferay.portal.kernel.util.ClassUtilTest._testGetPathURIFromURL(ClassUtilTest.java:341)
    [junit] 	at com.liferay.portal.kernel.util.ClassUtilTest.testGetPathURIFromURL(ClassUtilTest.java:154)
    [junit] 	at com.liferay.portal.kernel.test.rule.CodeCoverageAssertor$1.evaluate(CodeCoverageAssertor.java:81)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-31/test-portal-acceptance-pullrequest(master)/4999/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
I removed testGetPathURIFromURL and testGetPathURIFromURLWithUnknownProtocol already. They should not have these failures. I'm gonna rebase and run ci test again. Please help check again.
Thank you!

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
pushed to resolve conflict

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123370

**Pull request closed without merging**
