### PR TITLE
LPS-193390 Merge DirectServletRegistry logic into Util class in kernel

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci was reset yesterday. Need to rerun tests.

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139842

**Pull request closed without merging**
