### PR TITLE
[Components with more than 1 service] LPS-192202 Refactor export-import components

### PR DESCRIPTION
**Pull request by rafaprax**
**Author:** @MrJohn1911
**Issue:** https://liferay.atlassian.net/browse/LPS-192202
**Forwarded from:** https://github.com/rafaprax/liferay-portal/pull/1374
**Original comment:**
Ticket: https://liferay.atlassian.net/browse/LPS-192202

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:staging

**Comment by MrJohn1911** [comment]
In the last push, I just fixed a conflict in the bnd.bnd file

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:staging

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:staging

**Pull request closed without merging**
