### PR TITLE
[OrderByComparator] LPD-25933 Clean up unused OrderByComparator constructors and classes - Part II

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:forms

**Comment by MrJohn1911** [comment]
ci:test:echo

**Comment by MrJohn1911** [comment]
ci:test:content-management

**Comment by MrJohn1911** [comment]
ci:test:objects

**Comment by MrJohn1911** [comment]
ci:test:headless-staging

**Comment by MrJohn1911** [comment]
ci:test:object

**Comment by MrJohn1911** [comment]
ci:report:2569482012

**Comment by tinatian** [comment]
ci:report:2569591639

**Comment by tinatian** [comment]
@MrJohn1911 Please see my message on slack.

**Pull request closed without merging**
