### PR TITLE
[Remove Stream/Optional usage] LPS-176506 dynamic-data-mapping-test-util

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend, thanks!
previous: https://github.com/liferay-core-infra/liferay-portal/pull/3626
https://issues.liferay.com/browse/LPS-176506

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:data-engine

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:forward

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130968

**Pull request closed without merging**
