### PR TITLE
LPS-168709 Remove "immediate = true" from Commerce IV

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
@MrJohn1911 startup tests failed due:

```
[beanshell] 2022-11-21 22:02:22.122 ERROR [default-14][BatchingBatch:134] HHH000315: Exception executing batch [java.sql.BatchUpdateException: Duplicate entry '20097-com.liferay.commerce.pricing.model.CommercePricingClass-4-' for key 'IX_A9FF4B2C'], SQL: insert into ResourcePermission (mvccVersion, ctCollectionId, companyId, name, scope, primKey, primKeyId, roleId, ownerId, actionIds, viewActionId, resourcePermissionId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
[beanshell] 2022-11-21 22:02:22.123 ERROR [default-14][SqlExceptionHelper:142] Duplicate entry '20097-com.liferay.commerce.pricing.model.CommercePricingClass-4-' for key 'IX_A9FF4B2C'
[beanshell] 2022-11-21 22:02:22.131 ERROR [com.liferay.portal.osgi.web.portlet.tracker.internal.PortletTracker-ServiceTrackerOpener][PortletTracker:458] Portlet com_liferay_commerce_pricing_web_internal_portlet_CommercePricingClassesPortlet from com.liferay.commerce.pricing.web_4.0.60 [393] failed to initialize
[beanshell] com.liferay.portal.kernel.exception.PortalException: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute batch
[beanshell] 	at com.liferay.portal.osgi.web.portlet.tracker.internal.PortletTracker._deployPortlet(PortletTracker.java:1367) ~[?:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/4930/functional-smoke-startup-tomcat90-mysql57-jdk8/0/4/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by MrJohn1911** [comment]
@tinatian can you review this pull? thanks.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126907

**Pull request closed without merging**
