### PR TITLE
[Components with more than 1 service] LPS-190028

### PR DESCRIPTION
**Pull request by dantewang**
https://github.com/liferay-core-infra/liferay-portal/pull/4990

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:test:echo

**Comment by dantewang** [comment]
ci:test:stable

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Comment by dantewang** [comment]
ci:stable

**Comment by dantewang** [comment]
ci:test:stable

**Comment by dantewang** [comment]
ci:test:stable

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Comment by rafaprax** [comment]
ci:forward:force

@tinatian @dantewang

**Comment by tinatian** [comment]
@dantewang @rafaprax @regiCesar21 Please move cookie related logic into a cookie util rather than exposing the constant, the constant is actually part of the implementation details, we should always hide this as possible as we can.

Please resend.

Thanks.
Tina.

**Pull request closed without merging**
