### PR TITLE
LPS-167819 clean up redundant variable

### PR DESCRIPTION
**Pull request by chileces**
Dear Team,
This PR is to fix the issue reported in https://issues.liferay.com/browse/LPS-167819
Please help to review it,
Thank you,
CC: @Vy-ces

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@chileces no regressions found.

**Review by dantewang — CHANGES_REQUESTED** [review]
@chileces @Vy-CES The bug fix itself looks good, but this class overall looks weird.

```
	protected CalendarFactory calendarFactory;
	protected DateFormatFactory dateFormatFactory;
```

These fields doesn't have any setter either, and the corresponding `_getXXX` methods are using `XXXUtil` to get them; in fact, now we can directly reference them because these Spring beans are also published as OSGi services.

Also, I don't see any reason for them, as well as

```
	@Reference
	protected ModifiedFacetFactory modifiedFacetFactory;
```

to be `protected` as `ModifiedSearchFacet` doesn't have sublcass.

Could you also clean these up? Thanks! cc @julschong

**Comment by chileces** [comment]
ci:test:sf

**Comment by Vy-CES** [comment]
Hi @dantewang, thank you very much for the comment. I have removed all variables that are being used as xxxFactoryUtil and changed to use its Reference.

**Comment by Vy-CES** [comment]
There are several places, where the variable is not necessary such as: [ModifiedFacetPortletSharedSearchContributor.java#L66](https://github.com/liferay-core-infra/liferay-portal/blob/master/modules/apps/portal-search/portal-search-web/src/main/java/com/liferay/portal/search/web/internal/modified/facet/portlet/shared/search/ModifiedFacetPortletSharedSearchContributor.java#L66). Do you want to clean them up as well?

**Comment by dantewang** [comment]
@Vy-CES I think you can send another pull using a new ticket for them, since this ticket is a bug ticket, it's OK to clean up the affected class itself, but I don't want to expand it to other classes here.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126228

**Comment by Vy-CES** [comment]
Thanks @dantewang , I have created a new task under this ticket: https://issues.liferay.com/browse/LPS-168522

**Pull request closed without merging**
