### PR TITLE
LPS-190839 upgrade okio to 3.4.0

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

Resent from https://github.com/liferay-core-infra/liferay-portal/pull/5048
This is for ticket https://liferay.atlassian.net/browse/LPS-190839
In this Pr, I will upgrade okio to 3.4.0 for the security bug.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:notifications

**Comment by jeffwu0724** [comment]
ci:test:online-editing

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:notifications

**Comment by jeffwu0724** [comment]
ci:test:online-editing

**Comment by jeffwu0724** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found. There is no issue adding word documents with OneDrive.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138861

**Pull request closed without merging**
