### PR TITLE
[Remove Stream/Optional usage] LPS-173781 module  template-web

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-173781

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:stop:sf

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:echo-acceptance

**Comment by JanisZhang** [comment]
Thanks @catarineaguiar !

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
