### PR TITLE
LPS-161091 Use ActionURLBuilder and RenderURLBuilder instead when portlet 3.0 is opted in

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
@vicnate5
Hi Victor, I just noticed Catarine is off today.
could you please help me with some of my pulls?
Thanks!

**Comment by vicnate5** [comment]
@Kvale1733 can you check this one?

**Comment by Kvale1733** [comment]
@julschong  Regressions found

1. Functional failure in CountriesManagament tests: The Countries Management Portlet is Inaccessible  
Steps to Reproduce
    i. Open the Control Panel
    ii. Click on Countries Management under Configuration
    
    Expected Result:
    The Countries Management Portlet is available

   Actual Result
   "Countries Management is temporarily unavailable" message appears
   
2. Segment service configuration unavailable for Instance Settings
Steps to Reproduce
    i. Go to Instance Settings
    ii. Go to Segments
    iii.Go to Segment Service
    
    Expected Result:
    Segment Service configuration page opens

   Actual Result
   "Segments is temporarily unavailable." message appears
   
 3. Cannot Import Lar Files
Steps to Reproduce
    i. Open the Product Menu and got to Export under Publishing
    ii. Click the Plus Button
    iii.Click Export
    iv. Download the LAR FIle
    v. Open the Product Menut and go to Import Under Publishing
    vi.Click the Plush button and Import the downloaded Lar
    
    Expected Result:
    The LAR file is imported and the Import can be seen under processes 

   Actual Result
   The LAR file is not imported. No process is shown under Import processes.
   
 4. Cannot login with Multi Factor authentication enabled
 Steps to Reproduce
    i. Go to Instance Settings
    ii. Go to Multi Factor Authentication Settings
    iii.Enable Multi Factor Authentication
    iv. Logout and login
    
    Expected Result:
    The user can log back in

   Actual Result
   The user cannot log in anymore
   
 5.com.liferay.segments.web.internal.portlet.action.test.EditSegmentsEntryMVCRenderCommandTest
    com.liferay.segments.web.internal.portlet.action.test.PreviewSegmentsEntryUsersMVCRenderCommandTest
    com.liferay.content.dashboard.web.internal.portlet.test.ContentDashboardAdminPortletTest
    `java.lang.ClassCastException: com.liferay.portal.kernel.test.portlet.MockLiferayPortletURL cannot be cast to javax.portlet.RenderURL
`
 
 6.com.liferay.segments.display.context.test.SegmentsCompanyConfigurationDisplayContextTest
` java.lang.NullPointerException
     [exec]     	at com.liferay.portal.kernel.portlet.url.builder.ActionURLBuilder$ActionURLStep._setParameter(ActionURLBuilder.java:501)
     [exec]     	at com.liferay.portal.kernel.portlet.url.builder.ActionURLBuilder$ActionURLStep.setActionName(ActionURLBuilder.java:133)
     
 7.com.liferay.portal.search.tuning.synonyms.web.internal.portlet.SynonymsPortletTest
   com.liferay.portal.search.tuning.synonyms.web.internal.display.context.SynonymsDisplayBuilderTest
 `java.lang.NullPointerException
     [exec]         at com.liferay.portal.kernel.portlet.url.builder.RenderURLBuilder$RenderURLStep._setParameter(RenderURLBuilder.java:436)`
     
 8.com.liferay.portal.search.tuning.rankings.web.internal.portlet.ResultRankingsPortletTest
    com.liferay.portal.search.tuning.rankings.web.internal.display.context.RankingPortletDisplayBuilderTest
    com.liferay.portal.search.tuning.rankings.web.internal.portlet.action.EditRankingMVCActionCommandTest
 `java.lang.ClassCastException: org.mockito.codegen.PortletURL$MockitoMock$ayc2nzVr cannot be cast to javax.portlet.RenderURL
     [exec]         at com.liferay.portal.kernel.portlet.url.builder.RenderURLBuilder.createRenderURL(RenderURLBuilder.java:76)
`
9.com.liferay.analytics.reports.web.internal.portlet.action.test.GetDataMVCResourceCommandTest
`java.lang.NullPointerException: null`

**Pull request closed without merging**
