### PR TITLE
[Component with its own class name as service type] LPS-199599 Refactor Components from Commerce modules

### PR DESCRIPTION
**Pull request by dantewang**
@MrJohn1911 @rafaprax

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@MrJohn1911 @rafaprax Please see https://github.com/liferay-core-infra/liferay-portal/pull/6193/commits/0d7b115859178f54b444efd2d67760a80616a267

**Comment by catarineaguiar** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
Issue found:

**Steps to reproduce:**

- Add a Minium Site
- Go to the Minium Site
- Click on Search Icon (top left)
- Type "U-Joint" in the search bar

Actual Results: The search bar just keeps loading. Searching just doesn't work at all in the Minium site catalog.
And error thrown in portal console:
```
2023-11-23 04:45:06.237 ERROR [http-nio-8080-exec-5][CommerceSearchResource:141] null
java.lang.NullPointerException: null
	at com.liferay.commerce.frontend.internal.search.CommerceSearchResource.get(CommerceSearchResource.java:101) [bundleFile:?]
```
Example failed test: [LocalFile.CommerceSearch#GlobalSearchSearchEntryInAllContent](https://testray.liferay.com/home/-/testray/case_results/2463630916)
Full console: https://testray.liferay.com/reports/production/logs/2023-11/test-1-32/test-portal-acceptance-pullrequest(master)/2908/functional-tomcat90-mysql57-jdk8/0/8/jenkins-console.txt.gz?authuser=0

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:commerce

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@zhangyan0701 Force pushed, please help me watch the test result, thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:test:stable

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/144339

**Pull request closed without merging**
