### PR TITLE
[httpImpl] LPS 150185

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @tinatian, 
resolved conflicts with upstream, tiny change. thanks.
also see https://github.com/liferay-core-infra/liferay-portal/pull/597

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116078

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
