### PR TITLE
[Urgent] LPD-6609 Use PortalInstancePool as central point to get companyIds

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:license

**Comment by achaparro** [comment]
Sf errors are unrelated

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:report:2537180161

**Comment by achaparro** [comment]
ci:test:license

**Comment by achaparro** [comment]
- SF errors are unrelated
- Stable passed
- Relevant errors seem not related (404 with setupwizard)

cc/ @tinatian

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:stop

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @tinatian,

CI is broken and most of the tests do not complete. But these are the main results:
- ci:test:stable passed [here](https://github.com/liferay-core-infra/liferay-portal/pull/6612#issuecomment-1936547915)
- ci:test_license passed
- ci:test:relevant errors are not related (see the [report](https://github.com/liferay-core-infra/liferay-portal/pull/6612#issuecomment-1936904900)) since they failed due to a 404 error
- ci:test:sf failed due to an unrelated error

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6629

**Comment by tinatian** [comment]
ci:report:2538038722

**Pull request closed without merging**
