### PR TITLE
LPS-191594 module: adaptive-media-image-impl, analytics-reports-test, message-boards-api

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang, 

This pull request is extracted from the original PR(https://github.com/liferay-core-infra/liferay-portal/pull/5082) and focuses on cleaning up unused referenced/injected fields. I will send it separately. Thanks!
https://liferay.atlassian.net/browse/LPS-191594

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Review by dantewang — APPROVED** [review]
LGTM, wait for CI results.

**Comment by zhangyan0701** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
ci:test:message-boards

**Comment by Kvale1733** [comment]
ci:test:analytics-cloud-acceptance

**Comment by Kvale1733** [comment]
ci:test:analytics-cloud-acceptance

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:analytics-cloud-acceptance

**Comment by dantewang** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found. The analytics clouds tests are failing upstream too so not unique to this pr.

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
