### PR TITLE
[Remove Stream/Optional usage] LPS-175656 module headless-form-impl

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend, thanks!

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3483
https://issues.liferay.com/browse/LPS-175656

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:headless

**Comment by JanisZhang** [comment]
force-pushed

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:headless

**Comment by catarineaguiar** [comment]
no regressions.

**Comment by dantewang** [comment]
@JanisZhang See https://github.com/brianchandotcom/liferay-portal/pull/130916/commits/08023f7212d7cb3ccb0a682830badd826ec1ed82

**Pull request closed without merging**
