### PR TITLE
[Replace Non-Blocking Usage] LPS-202093 AggregateFilter

### PR DESCRIPTION
**Pull request by haydenzheng314**
Tickcet: https://liferay.atlassian.net/browse/LPS-202093
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by LisztLiszt** [comment]
ci:test:upgrade

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
