### PR TITLE
LPS-145595

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian, @shuyangzhou ,

I have removed unused properties "index.dump.compression.enabled", and updated to propskeys.java, propsvalues.java and verifyproperties.java.

1. It was renamed to "INDEX_DUMP_COMPRESSION_ENABLED" in commit 5f1564611979ad1cda67fb83d4f0b3f7bf21bc23, see LPS-16189, and it was used in "IndexCommitSerializationUtil.java".
2. It was moved to "modules/portal/portal-search-lucene/src/com/liferay/portal/search/lucene/internal/dump/IndexCommitSerializationUtil.java" based on commit 60db4fa7ea592c6f02854b4fac4f56baa74e4889, see LPS-54860.
3. It was finally deleted the usage in commit af7cbb5709399e4104440a35534cce8b725e35c3, see LPS-54860

Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.
@jeffwu0724 The code looks good to me, wait for QA to scan test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@jeffwu0724 Requires SemVer update https://testray.liferay.com/reports/production/logs/2022-01/test-1-26/test-portal-acceptance-pullrequest(master)/1399/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz

No regressions found.

**Pull request closed without merging**
