### PR TITLE
[Bug Fix] LPS-88060

### PR DESCRIPTION
**Pull request by yuhai**
cc @dantewang

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
@yuhai There were commits to fix this issue in the past. Could you explain why they are not working, and confirm whether we should revert/clean up them?

**Comment by dantewang** [comment]
@yuhai Also you say you refer to `RuntimeTag` logic for the fix in the commit message of https://github.com/liferay-core-infra/liferay-portal/pull/32/commits/4426c17249bfd1e5d608a506b58ab5c2a19be47f. Based on [this comment](https://issues.liferay.com/browse/LPS-88060?focusedCommentId=1708741&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1708741) in the ticket, could you point out which part in RuntimeTag do you refer to, and see if it's possible to avoid duplication of code?

**Comment by yuhai** [comment]
@dantewang,

>  There were commits to fix this issue in the past. Could you explain why they are not working, and confirm whether we should revert/clean up them?

Because the the original LPS-88060 fix didn't match the [data ](https://github.com/yuhai/liferay-portal/blob/LPS-88060/portal-impl/src/com/liferay/portal/model/impl/LayoutImpl.java#L1085-L1088) of LayoutImpl.isPortletEmbedded(). After LPS-93992 fix, the data [code1 ](https://github.com/yuhai/liferay-portal/blob/LPS-88060/portal-impl/src/com/liferay/portal/model/impl/LayoutImpl.java#L1085-L1088) and [code2 ](https://github.com/yuhai/liferay-portal/blob/LPS-88060/portal-impl/src/com/liferay/portal/model/impl/LayoutImpl.java#L1094-L1097)of of LayoutImpl.isPortletEmbedded() are not matched.

> Also you say you refer to RuntimeTag logic for the fix in the commit message of 4426c17. Based on this comment in the ticket, could you point out which part in RuntimeTag do you refer to, and see if it's possible to avoid duplication of code?

I refer to the [code1 ](https://github.com/yuhai/liferay-portal/blob/LPS-88060/util-taglib/src/com/liferay/taglib/portletext/RuntimeTag.java#L298-L302) and [code2](https://github.com/yuhai/liferay-portal/blob/LPS-88060/util-taglib/src/com/liferay/taglib/portletext/RuntimeTag.java#L307-L324) of RuntimeTag.doTag(). They can match with LayoutImpl.isPortletEmbedded() logic.

**Comment by dantewang** [comment]
@yuhai Then you did duplicate code from RuntimeTag into the TemplateProcessor. Could you check whether Preston's comment is true, that RuntimeTag depends on TemplateProcessor? And see if you can avoid duplication anyway.

**Comment by yuhai** [comment]
> @yuhai Then you did duplicate code from RuntimeTag into the TemplateProcessor. Could you check whether Preston's comment is true, that RuntimeTag depends on TemplateProcessor? And see if you can avoid duplication anyway.

@dantewang, for Preston's [comment](https://issues.liferay.com/browse/LPS-88060?focusedCommentId=1708741&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1708741), I think it is false. RuntimeTag didn't depends on TemplateProcessor.  After his this comment, he sent one fix and the fix didn't use he said logic.

For my [commit ](https://github.com/liferay-core-infra/liferay-portal/pull/32/commits/4426c17249bfd1e5d608a506b58ab5c2a19be47f), the code is duplicated code with the part of RuntimeTag. Should I extract them to one common method in PortletPreferencesFactoryUtil? I think it is not good way to do this because this is FactoryUtil.

**Comment by dantewang** [comment]
@yuhai I wonder how different the portlet embedding logic of `RuntimeTag` and the one of `TemplateProcessor` are. Is it possible to extract the portlet embedding logic to a common place (maybe in portal-kernel) that both classes can delegate to? Please take a look and let me know.

On the other hand, since the original fix didn't really fix this issue, could you check whether the logic added by the original fix is necessary? Try to do a clean up if possible.

**Comment by yuhai** [comment]
> @yuhai I wonder how different the portlet embedding logic of `RuntimeTag` and the one of `TemplateProcessor` are. Is it possible to extract the portlet embedding logic to a common place (maybe in portal-kernel) that both classes can delegate to? Please take a look and let me know.


> 
> On the other hand, since the original fix didn't really fix this issue, could you check whether the logic added by the original fix is necessary? Try to do a clean up if possible.

@dantewang, I will let you know after I check.

**Pull request closed without merging**
