### PR TITLE
[Remove immediate=true usage core-infrastructure-3] LPS-169260

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the previous pr is https://github.com/liferay-core-infra/liferay-portal/pull/2728.

I merged some changes to lily's commits and added commit messages in portal-instances, portal-osgi-debug and portal-configuration to explain the reasons. It can resolve the error https://github.com/liferay-core-infra/liferay-portal/pull/2728#issuecomment-1349950937 PortalInstancesConfigurationFactoryTest caused and [PortalInstancesConfigurationFactoryTest](https://github.com/liferay-core-infra/liferay-portal/pull/2728#issuecomment-1350908692). Except  **3 Some integration tests failed due to below error in portal startup:**, since that error link can't access.

cc @slnn

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test

**Comment by catarineaguiar** [comment]
running default tests to do an effective analysis.

**Comment by Kvale1733** [comment]
ci:test

**Comment by Kvale1733** [comment]
@yuhai Regression found.System check is disabled at startup with these changes.

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
> @yuhai Regression found.System check is disabled at startup with these changes.

@Kvale1733, thanks, I appended the last commit to solve the issue.

cc @dantewang.

**Comment by yuhai** [comment]
ci:test

**Comment by slnn** [comment]
Please see https://github.com/liferay-core-infra/liferay-portal/pull/2837

**Pull request closed without merging**
