### PR TITLE
LPS-165626

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by chaowang-123** [comment]
HI @tinatian
this pr caused regression issue [com.liferay.journal.subscriptions.test.JournalSubscriptionLocalizedContentTest](https://testray.liferay.com/home/-/testray/case_results/2136758367?redirect=https%3A%2F%2Ftestray.liferay.com%2Fzh%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2136754669%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
```
exec] com.liferay.journal.service.test.JournalArticleDDMFormConverterTest > testUpdateDataDefinitionMoveFieldFromRootToNestedField FAILED
     [exec]     com.liferay.journal.exception.ArticleContentException: Content is null
     [exec]     	at com.liferay.journal.internal.validation.JournalArticleModelValidator.validateContent(JournalArticleModelValidator.java:266)
     [exec]     	at com.liferay.journal.internal.validation.JournalArticleModelValidator.validate(JournalArticleModelValidator.java:158)
     [exec]     	at com.liferay.journal.service.impl.JournalArticleLocalServiceImpl.validate(JournalArticleLocalServiceImpl.java:8365)
```
RCA: https://test-1-1.liferay.com/userContent/jobs/root-cause-analysis-tool/builds/8122/jenkins-report.html

/cc @dantewang

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@tinatian regressions found:

```
     [exec] com.liferay.journal.subscriptions.test.JournalSubscriptionContainerModelTest > testSubscriptionContainerModelWhenUpdatingBaseModelInContainerModel FAILED
     [exec]     com.liferay.journal.exception.ArticleContentException: Content is null
     [exec]     	at com.liferay.journal.internal.validation.JournalArticleModelValidator.validateContent(JournalArticleModelValidator.java:266)
     [exec]     	at com.liferay.journal.internal.validation.JournalArticleModelValidator.validate(JournalArticleModelValidator.java:158)
     [exec]     	at com.liferay.journal.service.impl.JournalArticleLocalServiceImpl.validate(JournalArticleLocalServiceImpl.java:8365)
     [exec]     	at com.liferay.journal.service.impl.JournalArticleLocalServiceImpl.updateArticle(JournalArticleLocalServiceImpl.java:5745)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
```
     [exec] com.liferay.journal.service.test.JournalArticleLocalServiceTest > testArticleFriendlyURLValidationCompanyGroupStagingEnabled STARTED
[beanshell] 2022-12-28 01:15:53.135 ERROR [com.liferay.journal.test-executor-thread][LoggerExportImportLifecycleListener:359] Staged model {class: com.liferay.journal.model.JournalArticle, groupId: 20124, uuid: 9e0c3c20-1ed2-cef2-f9d2-beed9def8465} export failed
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.portal.kernel.io.unsync.UnsyncStringReader.<init>(UnsyncStringReader.java:34) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.util.xml.XMLSafeReader.<init>(XMLSafeReader.java:26) ~[util-java.jar:?]
[beanshell] 	at com.liferay.portal.xml.SAXReaderImpl.read(SAXReaderImpl.java:420) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.xml.SAXReaderUtil.read(SAXReaderUtil.java:161) ~[portal-kernel.jar:?]
```
```
[beanshell] 2022-12-28 01:15:53.244 ERROR [com.liferay.journal.test-executor-thread][LoggerExportImportLifecycleListener:156] Layout publication failed for group 20124
[beanshell] com.liferay.exportimport.kernel.lar.PortletDataException: null
[beanshell] 	at com.liferay.exportimport.kernel.lar.BaseStagedModelDataHandler.exportStagedModel(BaseStagedModelDataHandler.java:149) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.exportimport.data.handler.base.BaseStagedModelDataHandler.exportStagedModel(BaseStagedModelDataHandler.java:80) ~[?:?]
[beanshell] 	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.exportStagedModel(StagedModelDataHandlerUtil.java:178) ~[portal-kernel.jar:?]
```
```
     [exec] com.liferay.journal.service.test.JournalArticleLocalServiceTest > testArticleFriendlyURLValidationCompanyGroupStagingEnabled FAILED
     [exec]     java.lang.Exception: Unexpected exception, expected<com.liferay.journal.exception.ArticleFriendlyURLException> but was<com.liferay.portal.kernel.exception.NoSuchGroupException>
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._processExpectedException(TestExecutorRunnable.java:416)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.access$400(TestExecutorRunnable.java:66)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-26/test-portal-acceptance-pullrequest(master)/6595/modules-integration-mysql57-jdk8/0/5/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@tinatian regression found:

```
     [exec] com.liferay.journal.transformer.test.JournalTransformerTest > testFTLTransformation FAILED
     [exec]     java.lang.NoSuchMethodException: No method on null with name transform and parameter types [interface com.liferay.journal.model.JournalArticle, interface com.liferay.dynamic.data.mapping.model.DDMTemplate, interface com.liferay.journal.util.JournalHelper, class java.lang.String, interface com.liferay.layout.display.page.LayoutDisplayPageProviderRegistry, class com.liferay.portal.kernel.portlet.PortletRequestModel, boolean, class java.lang.String, class com.liferay.portal.kernel.theme.ThemeDisplay, class java.lang.String]
     [exec]     	at com.liferay.portal.kernel.test.ReflectionTestUtil.getMethod(ReflectionTestUtil.java:190)
     [exec]     	at com.liferay.journal.test.util.JournalTestUtil.getJournalUtilTransformMethod(JournalTestUtil.java:949)
     [exec]     	at com.liferay.journal.transformer.test.JournalTransformerTest.setUp(JournalTransformerTest.java:73)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-26/test-portal-acceptance-pullrequest(master)/6631/modules-integration-mysql57-jdk8/0/6/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:forward

FYI @shuyangzhou

**Pull request closed without merging**
