### PR TITLE
[Remove Stream/Optional usage: portal-workflow-metrics-rest-impl]Lps 178425

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-178425

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:workflow

**Comment by zhangyan0701** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:workflow

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@slnn possible regressions found:

Steps:

1. Navigate to applications menu > Applications > Workflow > Metrics

Actual result: Metrics page doens't open correctly and a failure appears on logs:
```
2023-03-17 16:44:58.813 ERROR [http-nio-8080-exec-9][ExceptionMapper:68] null
java.lang.ArrayStoreException: java.lang.Long
	at java.util.AbstractCollection.toArray(AbstractCollection.java:196) ~[?:1.8.0_221]
	at com.liferay.portal.search.internal.query.TermsQueryImpl.getValues(TermsQueryImpl.java:56) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.query.TermsQueryTranslatorImpl.translate(TermsQueryTranslatorImpl.java:33) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.query.ElasticsearchQueryTranslator.visit(ElasticsearchQueryTranslator.java:243) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.query.ElasticsearchQueryTranslator.visit(ElasticsearchQueryTranslator.java:64) ~[?:?]
	at com.liferay.portal.search.internal.query.TermsQueryImpl.accept(TermsQueryImpl.java:36) ~[?:?]
	at com.liferay.portal.search.elasticsearch7.internal.query.BooleanQueryTranslatorImpl._processQueryClause(BooleanQueryTranslatorImpl.java:83) ~[?:?]
```
Expected result:
Metrics page opens without errors

Integration tests failures:
```
     [exec] 
     [exec] com.liferay.portal.workflow.metrics.rest.resource.v1_0.test.TaskResourceTest > testPostTasksPage STARTED
     [exec] 2023-03-17 11:28:10.132 ERROR [http-nio-8080-exec-6][ExceptionMapper:68] null
     [exec] java.lang.ArrayStoreException: java.lang.Long
     [exec] 	at java.util.AbstractCollection.toArray(AbstractCollection.java:196) ~[?:1.8.0_121]
     [exec] 	at com.liferay.portal.search.internal.query.TermsQueryImpl.getValues(TermsQueryImpl.java:56) ~[?:?]
     [exec] 	at com.liferay.portal.search.elasticsearch7.internal.query.TermsQueryTranslatorImpl.translate(TermsQueryTranslatorImpl.java:33) ~[?:?]
     [exec] 	at com.liferay.portal.search.elasticsearch7.internal.query.ElasticsearchQueryTranslator.visit(ElasticsearchQueryTranslator.java:243) ~[?:?]
     [exec] 	at com.liferay.portal.search.elasticsearch7.internal.query.ElasticsearchQueryTranslator.visit(ElasticsearchQueryTranslator.java:64) ~[?:?]
     [exec] 	at com.liferay.portal.search.internal.query.TermsQueryImpl.accept(TermsQueryImpl.java:36) ~[?:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-03/test-1-25/test-portal-acceptance-pullrequest(master)/129/modules-integration-mysql57-jdk8/0/5/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.portal.workflow.metrics.rest.resource.v1_0.test.InstanceResourceTest > testGetProcessInstancesPageWithSortString STARTED
[beanshell] 2023-03-17 11:17:33.943 ERROR [http-nio-8080-exec-6][ExceptionMapper:68] null
[beanshell] java.lang.ArrayStoreException: java.util.LinkedHashMap$LinkedKeySet
[beanshell] 	at java.util.AbstractCollection.toArray(AbstractCollection.java:196) ~[?:1.8.0_121]
[beanshell] 	at com.liferay.portal.search.internal.query.TermsQueryImpl.getValues(TermsQueryImpl.java:56) ~[?:?]
[beanshell] 	at com.liferay.portal.search.elasticsearch7.internal.query.TermsQueryTranslatorImpl.translate(TermsQueryTranslatorImpl.java:33) ~[?:?]
[beanshell] 	at com.liferay.portal.search.elasticsearch7.internal.query.ElasticsearchQueryTranslator.visit(ElasticsearchQueryTranslator.java:243) ~[?:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-03/test-1-25/test-portal-acceptance-pullrequest(master)/129/modules-integration-mysql57-jdk8/0/4/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.portal.workflow.metrics.rest.resource.v1_0.test.ProcessMetricResourceTest > testGetProcessMetric FAILED
     [exec]     java.lang.AssertionError: Thread Thread[http-nio-8080-exec-7,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.vulcan.internal.jaxrs.exception.mapper.ExceptionMapper, message=null
     [exec]     java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.vulcan.internal.jaxrs.exception.mapper.ExceptionMapper, message=null
     [exec]     	at com.liferay.portal.test.rule.LogAssertionTestRule$LogAppender.append(LogAssertionTestRule.java:330)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-03/test-1-25/test-portal-acceptance-pullrequest(master)/129/modules-integration-mysql57-jdk8/0/4/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
Thank @catarineaguiar  for catching this! Will fix and resend.

> @slnn possible regressions found:
> 
> Steps:
> 
> 1. Navigate to applications menu > Applications > Workflow > Metrics
> 
> Actual result: Metrics page doens't open correctly and a failure appears on logs:
> 
> ```
> 2023-03-17 16:44:58.813 ERROR [http-nio-8080-exec-9][ExceptionMapper:68] null
> java.lang.ArrayStoreException: java.lang.Long
> 	at java.util.AbstractCollection.toArray(AbstractCollection.java:196) ~[?:1.8.0_221]
> 	at com.liferay.portal.search.internal.query.TermsQueryImpl.getValues(TermsQueryImpl.java:56) ~[?:?]
> 	at com.liferay.portal.search.elasticsearch7.internal.query.TermsQueryTranslatorImpl.translate(TermsQueryTranslatorImpl.java:33) ~[?:?]
> 	at com.liferay.portal.search.elasticsearch7.internal.query.ElasticsearchQueryTranslator.visit(ElasticsearchQueryTranslator.java:243) ~[?:?]
> 	at com.liferay.portal.search.elasticsearch7.internal.query.ElasticsearchQueryTranslator.visit(ElasticsearchQueryTranslator.java:64) ~[?:?]
> 	at com.liferay.portal.search.internal.query.TermsQueryImpl.accept(TermsQueryImpl.java:36) ~[?:?]
> 	at com.liferay.portal.search.elasticsearch7.internal.query.BooleanQueryTranslatorImpl._processQueryClause(BooleanQueryTranslatorImpl.java:83) ~[?:?]
> ```
> 
> Expected result: Metrics page opens without errors
> 
> Integration tests failures:
> 
> ```
>      [exec] 
>      [exec] com.liferay.portal.workflow.metrics.rest.resource.v1_0.test.TaskResourceTest > testPostTasksPage STARTED
>      [exec] 2023-03-17 11:28:10.132 ERROR [http-nio-8080-exec-6][ExceptionMapper:68] null
>      [exec] java.lang.ArrayStoreException: java.lang.Long
>      [exec] 	at java.util.AbstractCollection.toArray(AbstractCollection.java:196) ~[?:1.8.0_121]
>      [exec] 	at com.liferay.portal.search.internal.query.TermsQueryImpl.getValues(TermsQueryImpl.java:56) ~[?:?]
>      [exec] 	at com.liferay.portal.search.elasticsearch7.internal.query.TermsQueryTranslatorImpl.translate(TermsQueryTranslatorImpl.java:33) ~[?:?]
>      [exec] 	at com.liferay.portal.search.elasticsearch7.internal.query.ElasticsearchQueryTranslator.visit(ElasticsearchQueryTranslator.java:243) ~[?:?]
>      [exec] 	at com.liferay.portal.search.elasticsearch7.internal.query.ElasticsearchQueryTranslator.visit(ElasticsearchQueryTranslator.java:64) ~[?:?]
>      [exec] 	at com.liferay.portal.search.internal.query.TermsQueryImpl.accept(TermsQueryImpl.java:36) ~[?:?]
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2023-03/test-1-25/test-portal-acceptance-pullrequest(master)/129/modules-integration-mysql57-jdk8/0/5/jenkins-console.txt.gz?authuser=0)
> 
> ```
>      [exec] com.liferay.portal.workflow.metrics.rest.resource.v1_0.test.InstanceResourceTest > testGetProcessInstancesPageWithSortString STARTED
> [beanshell] 2023-03-17 11:17:33.943 ERROR [http-nio-8080-exec-6][ExceptionMapper:68] null
> [beanshell] java.lang.ArrayStoreException: java.util.LinkedHashMap$LinkedKeySet
> [beanshell] 	at java.util.AbstractCollection.toArray(AbstractCollection.java:196) ~[?:1.8.0_121]
> [beanshell] 	at com.liferay.portal.search.internal.query.TermsQueryImpl.getValues(TermsQueryImpl.java:56) ~[?:?]
> [beanshell] 	at com.liferay.portal.search.elasticsearch7.internal.query.TermsQueryTranslatorImpl.translate(TermsQueryTranslatorImpl.java:33) ~[?:?]
> [beanshell] 	at com.liferay.portal.search.elasticsearch7.internal.query.ElasticsearchQueryTranslator.visit(ElasticsearchQueryTranslator.java:243) ~[?:?]
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2023-03/test-1-25/test-portal-acceptance-pullrequest(master)/129/modules-integration-mysql57-jdk8/0/4/jenkins-console.txt.gz?authuser=0)
> 
> ```
>      [exec] com.liferay.portal.workflow.metrics.rest.resource.v1_0.test.ProcessMetricResourceTest > testGetProcessMetric FAILED
>      [exec]     java.lang.AssertionError: Thread Thread[http-nio-8080-exec-7,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.vulcan.internal.jaxrs.exception.mapper.ExceptionMapper, message=null
>      [exec]     java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.vulcan.internal.jaxrs.exception.mapper.ExceptionMapper, message=null
>      [exec]     	at com.liferay.portal.test.rule.LogAssertionTestRule$LogAppender.append(LogAssertionTestRule.java:330)
>      [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
>      [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
>      [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
>      [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2023-03/test-1-25/test-portal-acceptance-pullrequest(master)/129/modules-integration-mysql57-jdk8/0/4/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
Fix and resend in https://github.com/liferay-core-infra/liferay-portal/pull/4006

**Pull request closed without merging**
