### PR TITLE
[Reference cleanup]LPS-162937

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

Resend.
This PR is to convert method references to field references Misc. Thanks!
https://issues.liferay.com/browse/LPS-162937

previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/1755

### CODE REVIEW

**Review by dantewang — APPROVED** [review]
Code looks good, wait for QA review.

**Comment by catarineaguiar** [comment]
no regressions.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
