### PR TITLE
LPS-142279 Refactor ClassUtil & PortalClassPathUtil to reuse common logic

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina @tinatian,
This is resubmitted from #432  after our discussion

Here are some notes on this pull from our discussion:

1. Remove PortalClassPathUtil#create****
2. Remove ShieldedContainerInitializer's parent dir path from PortalClassPathUtil, test it on ci to see if it works well
3. If 1 failed, add a new property to PropsUtil
4. Decouple PortalClassPathUtil from the logic of getting parent dir
5. Move logic of getting parent path from ClassUtil to PropsUtil, PropsUtil is the only usage of it. Inline the only usage.
6. Add unit test for PropsUtil

### CODE REVIEW

**Comment by julschong** [comment]
pushed to resolve conflict

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
pushed to fix SF in package.info

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@kyle-miho
Hi Kyle,
Could you please help me scan the test results?
Thank you

**Comment by kyle-miho** [comment]
Failures unrelated @julschong

**Comment by julschong** [comment]
@tinatian
Hi Tina, 
Could you please review this pull?
Thank you!

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
Hi Tina, @tinatian
I changed 3 things from our discussion:
1. PropsUtil getLibDir changed back from public to private
2. Use PropsValue instead of PropsUtil.get
3. documented in commit message on why we are removing shieldedContainerInitializer from initializeClassPaths method

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@kyle-miho Hi Kyle, Could you please help review this pull again?
I only made 3 changes since last time you checked it:
1. PropsUtil getLibDir changed back from public to private
2. Use PropsValue instead of PropsUtil (also then its unit test needed to use Reflection instead)
3. documented in commit message on why we are removing shieldedContainerInitializer from initializeClassPaths method
Shouldn't be too different from before, but just in case.

Thank you!

**Comment by julschong** [comment]
@kyle-miho 
Hi Kyle, changes have been made after Tina reviewed it with me first.
I'm gonna rerun ci tests.

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by kyle-miho** [comment]
failures are unrelated, semantic versioning batch failed on CI due to CI randomly crashing, re-running to be safe

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
@julschong pr should be good

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
will resubmit, trying to figure out a different way to get the lib dirs

**Pull request closed without merging**
