### PR TITLE
LPS-147710

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

I update the version for Json-smart to version 2.4.5. See https://issues.liferay.com/browse/LPS-147710.
Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by tinatian** [comment]
@jeffwu0724 As we talked, please update the pull.

Tina.

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by kyle-miho** [comment]
relevant results are fine, waiting for acceptance results

**Comment by tinatian** [comment]
@jeffwu0724 Code looks good to me, wait for QA to scan test results.

Tina

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by kyle-miho** [comment]
semvar batch crashed for some reason, rerunning

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
no unique failures @jeffwu0724

**Comment by jeffwu0724** [comment]
Hey @tinatian , PR has been checked by Kyle and is good to go

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Pull request closed without merging**
