### PR TITLE
LPS-191027 Remove AsahSearchKeyWordsWebCacheItem

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
@julschong possible regression:

```
     [exec] com.liferay.search.experiences.internal.blueprint.test.SXPBlueprintSearchResultTest > testBoostContentsInACategoryForAUserSegment FAILED
     [exec]     org.junit.ComparisonFailure: 
     [exec]     " Score: 11.897636Title: "Article
     [exec]     " Score: 9.163527Title: "Article With Category
     [exec]     {"from":0,"size":10000,"query":{"bool":{"must":[{"bool":{"must":[{"bool":{"should":[{"bool":{"must":[{"match":{"comments":{"query":"Article"}}}],"should":[{"match_phrase":{"comments":{"query":"Article","slop":50}}},{"match_phrase":{"comments":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"content":{"query":"Article"}}}],"should":[{"match_phrase":{"content":{"query":"Article","slop":50}}},{"match_phrase":{"content":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description":{"query":"Article"}}}],"should":[{"match_phrase":{"description":{"query":"Article","slop":50}}},{"match_phrase":{"description":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title":{"query":"Article"}}},{"match_phrase_prefix":{"title":{"query":"Article"}}}]}}],"should":[{"match_phrase":{"title":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"url":{"query":"Article"}}}],"should":[{"match_phrase":{"url":{"query":"Article","slop":50}}},{"match_phrase":{"url":{"query":"Article","boost":2.0}}}]}},{"bool":{"should":[{"match_phrase_prefix":{"userName.text":{"query":"Article"}}}]}},{"bool":{"must":[{"match":{"assetCategoryTitles_en_US":{"query":"Article"}}}],"should":[{"match_phrase":{"assetCategoryTitles_en_US":{"query":"Article","slop":50}}},{"match_phrase":{"assetCategoryTitles_en_US":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"assetTagNames_en_US":{"query":"Article"}}},{"match_phrase_prefix":{"assetTagNames_en_US":{"query":"Article"}}}]}}],"should":[{"match_phrase":{"assetTagNames_en_US":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"articleId":{"query":"Article"}}}],"should":[{"match_phrase":{"articleId":{"query":"Article","slop":50}}},{"match_phrase":{"articleId":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"classPK":{"query":"Article"}}}],"should":[{"match_phrase":{"classPK":{"query":"Article","slop":50}}},{"match_phrase":{"classPK":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"content_zh_CN":{"query":"Article"}}}],"should":[{"match_phrase":{"content_zh_CN":{"query":"Article","slop":50}}},{"match_phrase":{"content_zh_CN":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"content_fi_FI":{"query":"Article"}}}],"should":[{"match_phrase":{"content_fi_FI":{"query":"Article","slop":50}}},{"match_phrase":{"content_fi_FI":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"content_ca_ES":{"query":"Article"}}}],"should":[{"match_phrase":{"content_ca_ES":{"query":"Article","slop":50}}},{"match_phrase":{"content_ca_ES":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"content_de_DE":{"query":"Article"}}}],"should":[{"match_phrase":{"content_de_DE":{"query":"Article","slop":50}}},{"match_phrase":{"content_de_DE":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"content_hu_HU":{"query":"Article"}}}],"should":[{"match_phrase":{"content_hu_HU":{"query":"Article","slop":50}}},{"match_phrase":{"content_hu_HU":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"content_pt_BR":{"query":"Article"}}}],"should":[{"match_phrase":{"content_pt_BR":{"query":"Article","slop":50}}},{"match_phrase":{"content_pt_BR":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"content_es_ES":{"query":"Article"}}}],"should":[{"match_phrase":{"content_es_ES":{"query":"Article","slop":50}}},{"match_phrase":{"content_es_ES":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"content_ar_SA":{"query":"Article"}}}],"should":[{"match_phrase":{"content_ar_SA":{"query":"Article","slop":50}}},{"match_phrase":{"content_ar_SA":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"content_sv_SE":{"query":"Article"}}}],"should":[{"match_phrase":{"content_sv_SE":{"query":"Article","slop":50}}},{"match_phrase":{"content_sv_SE":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"content_nl_NL":{"query":"Article"}}}],"should":[{"match_phrase":{"content_nl_NL":{"query":"Article","slop":50}}},{"match_phrase":{"content_nl_NL":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"content_fr_FR":{"query":"Article"}}}],"should":[{"match_phrase":{"content_fr_FR":{"query":"Article","slop":50}}},{"match_phrase":{"content_fr_FR":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"content_ja_JP":{"query":"Article"}}}],"should":[{"match_phrase":{"content_ja_JP":{"query":"Article","slop":50}}},{"match_phrase":{"content_ja_JP":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"content_en_US":{"query":"Article"}}}],"should":[{"match_phrase":{"content_en_US":{"query":"Article","slop":50}}},{"match_phrase":{"content_en_US":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description_ja_JP":{"query":"Article"}}}],"should":[{"match_phrase":{"description_ja_JP":{"query":"Article","slop":50}}},{"match_phrase":{"description_ja_JP":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description_fr_FR":{"query":"Article"}}}],"should":[{"match_phrase":{"description_fr_FR":{"query":"Article","slop":50}}},{"match_phrase":{"description_fr_FR":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description_fi_FI":{"query":"Article"}}}],"should":[{"match_phrase":{"description_fi_FI":{"query":"Article","slop":50}}},{"match_phrase":{"description_fi_FI":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description_ca_ES":{"query":"Article"}}}],"should":[{"match_phrase":{"description_ca_ES":{"query":"Article","slop":50}}},{"match_phrase":{"description_ca_ES":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description_de_DE":{"query":"Article"}}}],"should":[{"match_phrase":{"description_de_DE":{"query":"Article","slop":50}}},{"match_phrase":{"description_de_DE":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description_hu_HU":{"query":"Article"}}}],"should":[{"match_phrase":{"description_hu_HU":{"query":"Article","slop":50}}},{"match_phrase":{"description_hu_HU":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description_ar_SA":{"query":"Article"}}}],"should":[{"match_phrase":{"description_ar_SA":{"query":"Article","slop":50}}},{"match_phrase":{"description_ar_SA":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description_pt_BR":{"query":"Article"}}}],"should":[{"match_phrase":{"description_pt_BR":{"query":"Article","slop":50}}},{"match_phrase":{"description_pt_BR":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description_zh_CN":{"query":"Article"}}}],"should":[{"match_phrase":{"description_zh_CN":{"query":"Article","slop":50}}},{"match_phrase":{"description_zh_CN":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description_es_ES":{"query":"Article"}}}],"should":[{"match_phrase":{"description_es_ES":{"query":"Article","slop":50}}},{"match_phrase":{"description_es_ES":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description_en_US":{"query":"Article"}}}],"should":[{"match_phrase":{"description_en_US":{"query":"Article","slop":50}}},{"match_phrase":{"description_en_US":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description_nl_NL":{"query":"Article"}}}],"should":[{"match_phrase":{"description_nl_NL":{"query":"Article","slop":50}}},{"match_phrase":{"description_nl_NL":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description_sv_SE":{"query":"Article"}}}],"should":[{"match_phrase":{"description_sv_SE":{"query":"Article","slop":50}}},{"match_phrase":{"description_sv_SE":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"wildcard":{"entryClassPK":{"wildcard":"Article*"}}}],"should":[{"term":{"entryClassPK":{"value":"Article"}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title_es_ES":{"query":"Article"}}},{"match_phrase_prefix":{"title_es_ES":{"query":"Article"}}}]}}],"should":[{"match_phrase":{"title_es_ES":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title_ar_SA":{"query":"Article"}}},{"match_phrase_prefix":{"title_ar_SA":{"query":"Article"}}}]}}],"should":[{"match_phrase":{"title_ar_SA":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title_nl_NL":{"query":"Article"}}},{"match_phrase_prefix":{"title_nl_NL":{"query":"Article"}}}]}}],"should":[{"match_phrase":{"title_nl_NL":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title_zh_CN":{"query":"Article"}}},{"match_phrase_prefix":{"title_zh_CN":{"query":"Article"}}}]}}],"should":[{"match_phrase":{"title_zh_CN":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title_ja_JP":{"query":"Article"}}},{"match_phrase_prefix":{"title_ja_JP":{"query":"Article"}}}]}}],"should":[{"match_phrase":{"title_ja_JP":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title_pt_BR":{"query":"Article"}}},{"match_phrase_prefix":{"title_pt_BR":{"query":"Article"}}}]}}],"should":[{"match_phrase":{"title_pt_BR":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title_sv_SE":{"query":"Article"}}},{"match_phrase_prefix":{"title_sv_SE":{"query":"Article"}}}]}}],"should":[{"match_phrase":{"title_sv_SE":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title_fi_FI":{"query":"Article"}}},{"match_phrase_prefix":{"title_fi_FI":{"query":"Article"}}}]}}],"should":[{"match_phrase":{"title_fi_FI":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title_en_US":{"query":"Article"}}},{"match_phrase_prefix":{"title_en_US":{"query":"Article"}}}]}}],"should":[{"match_phrase":{"title_en_US":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title_ca_ES":{"query":"Article"}}},{"match_phrase_prefix":{"title_ca_ES":{"query":"Article"}}}]}}],"should":[{"match_phrase":{"title_ca_ES":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title_de_DE":{"query":"Article"}}},{"match_phrase_prefix":{"title_de_DE":{"query":"Article"}}}]}}],"should":[{"match_phrase":{"title_de_DE":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title_hu_HU":{"query":"Article"}}},{"match_phrase_prefix":{"title_hu_HU":{"query":"Article"}}}]}}],"should":[{"match_phrase":{"title_hu_HU":{"query":"Article","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title_fr_FR":{"query":"Article"}}},{"match_phrase_prefix":{"title_fr_FR":{"query":"Article"}}}]}}],"should":[{"match_phrase":{"title_fr_FR":{"query":"Article","boost":2.0}}}]}},{"bool":{"should":[{"match_phrase_prefix":{"userName.text":{"query":"Article"}}}]}}]}}]}}],"filter":[{"bool":{"must":[{"bool":{"should":[{"bool":{"must":[{"term":{"entryClassName":{"value":"com.liferay.journal.model.JournalArticle"}}},{"term":{"head":{"value":"true"}}},{"term":{"head":{"value":"true"}}},{"terms":{"status":["0"]}},{"terms":{"status":["0"]}},{"bool":{"must":[{"bool":{"must_not":[{"exists":{"field":"ctCollectionId"}}]}}]}},{"bool":{"must":[{"bool":{"must_not":[{"exists":{"field":"ctCollectionId"}}]}}]}}]}}]}}]}}],"should":[{"term":{"assetCategoryIds":{"value":"55258","boost":1000.0}}}]}},"explain":false,"stored_fields":["content_zh_CN","entryClassPK","groupId","description_ca_ES","description_hu_HU","description_ar_SA","description_pt_BR","title_ja_JP","content_sv_SE","scopeGroupId","description_es_ES","content_fr_FR","modified","title_fi_FI","description_nl_NL","content_en_US","content_de_DE","defaultLanguageId","content_es_ES","content_ar_SA","version","companyId","content_nl_NL","title_sv_SE","description_en_US","description_sv_SE","title_en_US","title_de_DE","title_es_ES","description_ja_JP","content_fi_FI","description_fr_FR","description","description_de_DE","title_ar_SA","title","title_nl_NL","content","uid","title_pt_BR","assetTagNames","title_ca_ES","entryClassName","content_ca_ES","content_hu_HU","articleId","description_fi_FI","content_pt_BR","title_zh_CN","description_zh_CN","content_ja_JP","title_hu_HU","title_fr_FR"],"track_scores":true,"track_total_hits":2147483647}->{uid=com.liferay.journal.model.JournalArticle_PORTLET_55237, entryClassPK=55238, companyId=20096, entryClassName=com.liferay.journal.model.JournalArticle, scopeGroupId=55223, groupId=55223, articleId=55236, modified=20230720235435, defaultLanguageId=en_US, title_en_US=Article, version=1.0},{uid=com.liferay.journal.model.JournalArticle_PORTLET_55271, entryClassPK=55272, companyId=20096, entryClassName=com.liferay.journal.model.JournalArticle, scopeGroupId=55223, groupId=55223, articleId=55270, modified=20230720235436, defaultLanguageId=en_US, title_en_US=Article With Category, version=1.0}->[Article, Article With Category] expected:<[Article[ With Category, Article]]> but was:<[Article[, Article With Category]]>
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:117)
     [exec]     	at com.liferay.portal.search.test.util.DocumentsAssert.assertValues(DocumentsAssert.java:76)
     [exec]     	at com.liferay.search.experiences.internal.blueprint.test.SXPBlueprintSearchResultTest._assertSearch(SXPBlueprintSearchResultTest.java:2227)
     [exec]     	at com.liferay.search.experiences.internal.blueprint.test.SXPBlueprintSearchResultTest.testBoostContentsInACategoryForAUserSegment(SXPBlueprintSearchResultTest.java:426)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-07/test-1-38/test-portal-acceptance-pullrequest(master)/8316/modules-integration-mysql57-jdk8/0/11/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.asset.search.test.AssetSearcherTest > testSearchAllAssetCategoryIdsIncludingInternalAssetCategories FAILED
     [exec]     java.lang.AssertionError: {docs={}, length=0, query=null] expected:<1> but was:<0>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at com.liferay.asset.search.test.AssetSearcherTest.testSearchAllAssetCategoryIdsIncludingInternalAssetCategories(AssetSearcherTest.java:137)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-07/test-1-38/test-portal-acceptance-pullrequest(master)/8316/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
     [exec] 
     [exec] com.liferay.asset.publisher.exportimport.test.AssetPublisherExportImportTest > testDynamicExportImportAssetCategoryFiltering FAILED
     [exec]     java.lang.AssertionError: [] expected:<2> but was:<0>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at com.liferay.asset.publisher.exportimport.test.AssetPublisherExportImportTest.assertAssetEntries(AssetPublisherExportImportTest.java:938)
     [exec]     	at com.liferay.asset.publisher.exportimport.test.AssetPublisherExportImportTest.testDynamicExportImport(AssetPublisherExportImportTest.java:1104)
     [exec]     	at com.liferay.asset.publisher.exportimport.test.AssetPublisherExportImportTest.testDynamicExportImportAssetCategoryFiltering(AssetPublisherExportImportTest.java:316)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-07/test-1-38/test-portal-acceptance-pullrequest(master)/8316/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:search

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:search

**Pull request closed without merging**
