### PR TITLE
[Remove Stream/Optional usage] LPS-173307 remove_stream_and_optional_in_talend_common

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang, 

This is for ticket https://issues.liferay.com/browse/LPS-173307.
Thanks for chekcing.

### CODE REVIEW

**Comment by Kvale1733** [comment]
That's odd. No test ran but relevant still passed. Rerunning.

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
