### PR TITLE
[Publication]LPS-143554

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5, please help me scan the test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@koor4356 can you check this one?

**Comment by koor4356** [comment]
Okay, thanks!

**Comment by koor4356** [comment]
@tinatian @vicnate5,
No unique failures. It looks good.

**Comment by tinatian** [comment]
@shuyangzhou This is good to go.

Tina.

**Comment by shuyangzhou** [comment]
see https://github.com/shuyangzhou/liferay-portal/pull/10483

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
