### PR TITLE
[Component with its own class name as service type ] LPS-193663 Refactor Registry classes from search module

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by shuyangzhou** [comment]
ci:forward:force

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139854

**Pull request closed without merging**
