### PR TITLE
[commons-lang] LPD-19869 Add petra-time and Remove org.apache.commons.lang.time.StopWatch usages

### PR DESCRIPTION
**Pull request by julschong**
@tinatian 
resubmitted from #6781

keeping start() and stop() for now

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:report:2554137685

**Comment by julschong** [comment]
rerun relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:upgrade

**Comment by julschong** [comment]
ci:report:2554619543

**Comment by julschong** [comment]
ci:report:2554702108

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
rerun relevant

**Comment by julschong** [comment]
ci:report:2555170307

**Comment by julschong** [comment]
no unique failure

**Comment by tinatian** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/148580

**Pull request closed without merging**
