### PR TITLE
[Remove Stream/Optional usage] LPS-174598 Remove usages of Stream for module: portal-upgrade-impl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(2/20 14:47)

**Comment by W2jx** [comment]
no conflicts(2/21 13:50)

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3644

**Comment by dantewang** [comment]
@W2jx Please always use the return value of `ListUtil.sort`.

**Pull request closed without merging**
