### PR TITLE
LPS-193534 Remove log4j1 package from Import-Package by upgrading jericho-html.

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:lima

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:lima

**Comment by catarineaguiar** [comment]
ci:test:lima

**Comment by catarineaguiar** [comment]
no regressions were found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139386

**Pull request closed without merging**
