### PR TITLE
[Circular dependency]Lps 186384 6 27

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-186384

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:object

**Comment by tinatian** [comment]
@slnn @dantewang Why you are doing this? What blocks you?

**Comment by slnn** [comment]
Hi @tinatian 

There is an Optional reference in ObjectRelationshipLocalServiceImpl which aims to break the circular dependency between ObjectRelationshipLocalServiceImpl and ObjectDefinitionLocalServiceImpl, this pull aims to break the circular dependency in another way in order to remove the Optional reference usage instead of replacing with Snapshot.

The blocker is this pull has a bad design that declares a ServiceTracker in the new helper class but opens it by another class, we are finding a new way to break the circular dependency.


Lily

**Comment by slnn** [comment]
Close and will resend with a new solution

**Comment by slnn** [comment]
The new solution please see https://github.com/liferay-core-infra/liferay-portal/pull/4911

**Pull request closed without merging**
