### PR TITLE
LPS-197317  Align model.class.name value in Workflow**ModelResourcePermission

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @shuyangzhou,

This PR is to align `model.class.name` value in class `WorkflowTaskModelResourcePermission`, `WorkflowDefinitionModelResourcePermission`, and `WorkflowInstanceModelResourcePermission`. These three classes were added to [use the Workflow* entities and keep the Workflow permission API independent of the Liferay Workflow implementation (Kaleo)](https://github.com/brianchandotcom/liferay-portal/pull/125719). 

And please note that I disabled the permission checks in [commit 3](https://github.com/liferay-core-infra/liferay-portal/commit/dd4ee5d0db1262d4950a87c583d1f2d22d6aced1) and [commit 5](https://github.com/liferay-core-infra/liferay-portal/commit/911caf0c6bdf2bd9931b6c84e57bfec29340bac7), based on [ticket](https://liferay.atlassian.net/browse/LPS-191707), to maintain consistent behavior with the previous state. Without these changes, the Hits would return null.

https://liferay.atlassian.net/browse/LPS-197317

Thanks!

### CODE REVIEW

**Comment by JanisZhang** [comment]
SF failure should be not related.

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by catarineaguiar** [comment]
SF issue is not related

**Comment by JanisZhang** [comment]
Waiting for the product team's response... https://liferay.atlassian.net/browse/PTR-4367

**Comment by shuyangzhou** [comment]
@rafaprax can you review this pull? It changes workflow stuff which I am not familiar with.

**Comment by rafaprax** [comment]
Sure. I'll take over this PR.

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-core-infra/liferay-portal/pull/5693

**Comment by JanisZhang** [comment]
Thanks @rafaprax

**Pull request closed without merging**
