### PR TITLE
[Method References 2] LPS-169774 Convert method reference to ServiceTrackerMap in module portal-search-admin-web

### PR DESCRIPTION
**Pull request by W2jx**
Combining the requirements in https://github.com/brianchandotcom/liferay-portal/pull/129727 and https://github.com/liferay-core-infra/liferay-portal/pull/3414, I did not create an interface for new class IndexReindexerRegistry, but put it under package reindexer.

Previous: https://github.com/brianchandotcom/liferay-portal/pull/129727 and https://github.com/liferay-core-infra/liferay-portal/pull/3414

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(2/21 13:50)

**Review by dantewang — APPROVED** [review]
@tinatian This PR is a re-send. The registry class was added to the same package of the portlet. Brian asked to put it in a package in portal-search-spi, but since this registry is only used by internal classes in portal-search-admin-web, we put it in a new package in the same module.

**Comment by W2jx** [comment]
no conflicts(2/27 8:30)

**Comment by W2jx** [comment]
no conflicts(2/28 9:42)

**Comment by W2jx** [comment]
no conflicts(3/1 10:45)

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian 

Forwarding since the change has been reviewed and the resend is upon BChan's request.

**Pull request closed without merging**
