### PR TITLE
[Static reference] LPS-182671 Remove static references in class MBDiscussionPermission | part 2

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5094

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:lima

**Comment by W2jx** [comment]
ci:test:comment

**Comment by W2jx** [comment]
ci:test:message-boards

**Comment by W2jx** [comment]
ci:test:questions

**Comment by catarineaguiar** [comment]
no regressions found. SF is not related.

**Comment by W2jx** [comment]
only do semver, no need to rerun test

**Comment by W2jx** [comment]
no conflicts(8/3 9:27)

**Comment by W2jx** [comment]
only do semver, no need to rerun test

**Comment by W2jx** [comment]
no conflicts(8/7 8:38)

**Comment by W2jx** [comment]
no conflicts(8/10 17:08)

**Review by dantewang — APPROVED** [review]

**Comment by W2jx** [comment]
no conflicts(8/11 16:01)

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5256

**Pull request closed without merging**
