### PR TITLE
[Components with more than 1 service] LPS-201728 Remove ReindexSingleIndexerBackgroundTaskExecutor from BackgroundTaskConfigurator initialization

### PR DESCRIPTION
**Pull request by rafaprax**
**Author:** @rcsdnj
**Issue:** https://liferay.atlassian.net/browse/LPS-201728
**Forwarded from:** https://github.com/rafaprax/liferay-portal/pull/1348
**Original comment:**
ReindexSingleIndexerBackgroundTaskExecutor had two services (ReindexSingleIndexerBackgroundTaskExecutor itself), and the only reason for this is because BackgroundTaskConfigurator was registering it manually. We removed this manual registration and consequently the need for being registered as more than 1 service. 

This change was suggested by @dantewang, in [the previous PR](https://github.com/liferay-core-infra/liferay-portal/pull/6185) refering to this task.

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@rafaprax Regression found in ElasticSearch7#ReindexWithConcurrentExecutionMode. indexNameNext database field for Company table is not populated after concurrent reindex. The test is a use case for https://liferay.atlassian.net/browse/LPS-177665 so maybe that provides more context.

Steps to reproduce:
1. Go to Control Panel > Search > Index Options
2. Select Reindex Mode as Concurrent (left hand side)
3. Select Reindex Scope as Selected Instances and check liferay.com
4. Click Reindex on All Search Indexes (right hand side)
5. After the reindex is done, execute MySQL query "SELECT indexNameNext FROM lportal.Company;"

Expected Results: The query result shows an entry in field indexNameNext for liferay-{default company ID here} (i.e liferay-4979351567294132231).
Actual Results: The query returns a null value for indexNameNext field

**Comment by Kvale1733** [comment]
ci:close

**Comment by rcsdnj** [comment]
@Kvale1733 , I've followed the steps you've indicated and I got the same results (null field in SQL query) on the current master branch (ee2717f38bb6f171e594caaa0bcc70a934330ded). Also, I did a shallow look into the code and it seems to me that the class in question (ReindexSingleIndexerBackgroundTaskExecutor) is not related to this specific execution flow. I've talked to @rafaprax about this issue and he suggested me to open the PR to the search team, which can make a deeper analyses.

**Pull request closed without merging**
