### PR TITLE
[Convert method references]Lps 162756

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-162756

/cc @dantewang @tinatian

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

For relevant tests and sf test has run in https://github.com/slnn/liferay-portal/pull/635, could you help to scan test results?

Thanks
Lily

**Comment by zhangyan0701** [comment]
Hi @catarineaguiar Could you check the results when the tests finish?

**Comment by catarineaguiar** [comment]
@slnn no regressions found.

**Comment by dantewang** [comment]
@shuyangzhou @tinatian Forwarding this one as all tests passed review and changes are direct replacements.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123468

**Pull request closed without merging**
