### PR TITLE
[TS] LPS-142380

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
New commit added, as requested in https://github.com/brianchandotcom/liferay-portal/pull/121028

**Comment by dantewang** [comment]
@crodriguezy Could you merge https://github.com/liferay-core-infra/liferay-portal/pull/1278/commits/b13d59f511e9f7de7e9f71b1edaccc71fd6d246a into the original commit to make it look like you added the separate exception class from the beginning? Thanks!

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@crodriguezy regression found:

```
 [exec] /opt/dev/projects/github/liferay-portal/modules/apps/expando/expando-test/src/testIntegration/java/com/liferay/expando/service/test/ExpandoValueLocalServiceTest.java:172: error: cannot find symbol
     [exec] 				_log.debug(valueDataException);
     [exec] 				           ^
     [exec]   symbol:   variable valueDataException
     [exec]   location: class ExpandoValueLocalServiceTest
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 1 error
     [exec] 
     [exec] > Task :apps:expando:expando-test:compileTestIntegrationJava FAILED
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-27/test-portal-acceptance-pullrequest(master)/4391/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Comment by crodriguezy** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@zhangyan0701 Could you please check the latest relevant run when it finishes, and if there's no regression, assign this to Tina? Thanks!

**Comment by zhangyan0701** [comment]
The relevant tests passed. No regressions found.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
