### PR TITLE
LPS-165690 Remove immediate from Analytics modules

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:analytics-cloud

**Comment by zhangyan0701** [comment]
ci:test:analytics-cloud

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by rafaprax** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
@rafaprax can you stop these runs, so we can run `ci:test:analytics-cloud-acceptance` to check if there are failures

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:stop:ci:test:analytics-cloud

**Comment by catarineaguiar** [comment]
@rafaprax possible regression on:
[KnownIndividualsProfileDetails#OrderIndividualDetails](https://testray.liferay.com/home/-/testray/case_results/2008820654?tab=history)
[AnalyticsCloudConnectionTest#CanSyncAllContactsFromDXPToAC](https://testray.liferay.com/home/-/testray/case_results/2008815668?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1539767257%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1539767257%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc)

```
[beanshell] 2022-10-18 00:00:23.400 INFO  [CM Configuration Updater (Update: pid=com.liferay.analytics.settings.configuration.AnalyticsConfiguration.scoped~69d9b79d-c3c4-4026-9cc5-8e29c1167602)][AnalyticsConfigurationTrackerImpl:539] Queueing send analytics messages message
[beanshell] 2022-10-18 00:00:23.414 ERROR [liferay/analytics_messages_processor-2][SendAnalyticsMessagesMessageListener:136] Unable to send analytics messages for company 43554
[beanshell] com.liferay.portal.kernel.json.JSONException: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
[beanshell] 	at com.liferay.portal.json.JSONObjectImpl.<init>(JSONObjectImpl.java:84) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.json.JSONFactoryImpl.createJSONObject(JSONFactoryImpl.java:179) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.json.JSONFactoryUtil.createJSONObject(JSONFactoryUtil.java:80) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.analytics.message.sender.internal.AnalyticsMessageSenderClientImpl._execute(AnalyticsMessageSenderClientImpl.java:225) ~[bundleFile:?]
[beanshell] 	at com.liferay.analytics.message.sender.internal.AnalyticsMessageSenderClientImpl.send(AnalyticsMessageSenderClientImpl.java:85) ~[bundleFile:?]
[beanshell] 	at com.liferay.analytics.message.sender.internal.messaging.SendAnalyticsMessagesMessageListener._process(SendAnalyticsMessagesMessageListener.java:127) [bundleFile:?]
[beanshell] 	at com.liferay.analytics.message.sender.internal.messaging.SendAnalyticsMessagesMessageListener.doReceive(SendAnalyticsMessagesMessageListener.java:97) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:34) [portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74) [portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.messaging.internal.SerialDestination$1.run(SerialDestination.java:59) [bundleFile:?]
[beanshell] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
[beanshell] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
[beanshell] 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[beanshell] Caused by: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
[beanshell] 	at org.json.JSONTokener.syntaxError(JSONTokener.java:521) ~[json-java.jar:?]
[beanshell] 	at org.json.JSONObject.<init>(JSONObject.java:225) ~[json-java.jar:?]
[beanshell] 	at org.json.JSONObject.<init>(JSONObject.java:421) ~[json-java.jar:?]
[beanshell] 	at com.liferay.portal.json.JSONObjectImpl.<init>(JSONObjectImpl.java:81) ~[portal-impl.jar:?]
[beanshell] 	... 12 more
[beanshell] 2022-10-18 00:00:23.421 INFO  [liferay/analytics_messages_processor-2][SendAnalyticsMessagesMessageListener:146] Deleted 5 analytics messages
[beanshell] 2022-10-18 00:00:23.422 INFO  [liferay/analytics_messages_processor-2][SendAnalyticsMessagesMessageListener:108] Finished processing analytics messages
     [exec]     LIFERAY_ERROR: Unable to send analytics messages for company 43554
     [exec]     Executing commands: curl -X GET -u 'test@liferay.com:test' 'http://test-1-32-19:8080/api/jsonws/company/get-company-by-virtual-host/virtual-host/test-1-32-19'
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-32/test-portal-acceptance-pullrequest(master)/6239/functional-tomcat90-mysql57-jdk8/3/0/jenkins-console.txt.gz?authuser=0)

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:analytics-cloud-acceptance

**Comment by Kvale1733** [comment]
analytics cloud acceptance doesn't really run many tests. The issues Catarine found were in the other analytics suite. Rerunning.

**Comment by Kvale1733** [comment]
ci:test:analytics-cloud

**Comment by Kvale1733** [comment]
@rafaprax No regressions found.

**Comment by rafaprax** [comment]
Hey @shuyangzhou, this pr is ready for your review. Thx

**Comment by shuyangzhou** [comment]
@rafaprax in this case, https://github.com/liferay-core-infra/liferay-portal/pull/2055/commits/1b9f8c9cef063ce1f45b9f7dc995f0c3d72c6d4d should really just remove the service properties to make it `@Component(service = {})`

Now thinking about the morning example again, https://github.com/liferay-core-infra/liferay-portal/commit/dd4033d7d6831d6cc1656bef3e9f61b6d8c31900 . What's the point of `service = MessageListener.class` ? DefaultMessageBus is unable to collect it anyway. And it is self re-registering on activation. We should just make it `@Component(service = {})` too.

**Comment by rafaprax** [comment]
@shuyangzhou I forgot to apply the implied immediate approach on this case. I'll fix that. Thanks for catch that. Thx

**Comment by rafaprax** [comment]
ci:test:analytics-cloud

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:analytics-cloud

**Comment by jaydawu** [comment]
ci:test:analytics-cloud

**Comment by pyoo47** [comment]
ci:test:analytics-cloud (retesting due to many aborts caused by internal github-dev issue)

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
Possible regression. 
Declarative Service Unsatisfied Component Checker WARN during portal start:
```
    [junit] 2022-10-26 03:25:59.284 WARN  [main][SystemCheckOSGiCommands:134] Declarative Service Unsatisfied Component Checker check result: 
    [junit] Bundle {id: 363, name: com.liferay.segments.service, version: 3.0.61}
    [junit] 	Declarative Service {id: 1202, name: com.liferay.segments.internal.criteria.contributor.UserSegmentsCriteriaContributor, unsatisfied references: 
    [junit] 		{name: _entityModel, target: (entity.model.name=User)}
    [junit] 	}
    [junit] 	Declarative Service {id: 1226, name: com.liferay.segments.internal.odata.retriever.UserODataRetriever, unsatisfied references: 
    [junit] 		{name: EntityModel, target: (entity.model.name=User)}
    [junit] 		{name: FilterParser, target: (entity.model.name=User)}
    [junit] 	}
    [junit] 	Declarative Service {id: 1201, name: com.liferay.segments.internal.criteria.contributor.UserOrganizationSegmentsCriteriaContributor, unsatisfied references: 
    [junit] 		{name: _entityModel, target: (entity.model.name=Organization)}
    [junit] 		{name: _oDataRetriever, target: (model.class.name=com.liferay.portal.kernel.model.Organization)}
    [junit] 	}
    [junit] 	Declarative Service {id: 1198, name: com.liferay.segments.internal.criteria.contributor.OrganizationSegmentsCriteriaContributor, unsatisfied references: 
    [junit] 		{name: _entityModel, target: (entity.model.name=Organization)}
    [junit] 	}
    [junit] 	Declarative Service {id: 1225, name: com.liferay.segments.internal.odata.retriever.OrganizationODataRetriever, unsatisfied references: 
    [junit] 		{name: _entityModel, target: (entity.model.name=Organization)}
    [junit] 		{name: _filterParser, target: (entity.model.name=Organization)}
    [junit] 	}
    [junit] Bundle {id: 1389, name: com.liferay.segments.content.targeting.upgrade, version: 3.0.13}
    [junit] 	Declarative Service {id: 5981, name: com.liferay.segments.content.targeting.upgrade.internal.upgrade.v1_0_0.util.SiteMemberRuleConverter, unsatisfied references: 
    [junit] 		{name: _userSegmentsCriteriaContributor, target: (segments.criteria.contributor.key=user)}
    [junit] 	}
    [junit] 	Declarative Service {id: 5977, name: com.liferay.segments.content.targeting.upgrade.internal.upgrade.v1_0_0.util.OrganizationMemberRuleConverter, unsatisfied references: 
    [junit] 		{name: _userOrganizationSegmentsCriteriaContributor, target: (segments.criteria.contributor.key=user-organization)}
    [junit] 	}
    [junit] 	Declarative Service {id: 5973, name: com.liferay.segments.content.targeting.upgrade.internal.upgrade.v1_0_0.util.CustomFieldRuleConverter, unsatisfied references: 
    [junit] 		{name: _userSegmentsCriteriaContributor, target: (segments.criteria.contributor.key=user)}
    [junit] 	}
    [junit] 	Declarative Service {id: 5979, name: com.liferay.segments.content.targeting.upgrade.internal.upgrade.v1_0_0.util.RegularRoleRuleConverter, unsatisfied references: 
    [junit] 		{name: _userSegmentsCriteriaContributor, target: (segments.criteria.contributor.key=user)}
    [junit] 	}
    [junit] 	Declarative Service {id: 5982, name: com.liferay.segments.content.targeting.upgrade.internal.upgrade.v1_0_0.util.UserGroupMemberRuleConverter, unsatisfied references: 
    [junit] 		{name: _userSegmentsCriteriaContributor, target: (segments.criteria.contributor.key=user)}
```
Full console:
https://testray.liferay.com/reports/production/logs/2022-10/test-1-30/test-portal-acceptance-pullrequest(master)/5196/functional-smoke-startup-tomcat90-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0

**Comment by rafaprax** [comment]
Hey @zhangyan0701, those errors are not related to these changes here. It's a known blocker introduced by a previous pr. Thx

**Comment by catarineaguiar** [comment]
@rafaprax @zhangyan0701 yes, it was caused by this blocker https://issues.liferay.com/browse/LPS-166717

**Comment by rafaprax** [comment]
Hey @shuyangzhou, this pr is ready for your review. Thx

**Pull request closed without merging**
