### PR TITLE
[Method References] LPS-162265 Convert method references to field references in class extends BaseJSPProductNavigationControlMenuEntry

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have made the method to be getServletContext in class BaseJSPProductNavigationControlMenuEntry.

Detial: https://github.com/liferay-core-infra/liferay-portal/pull/1570

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results when they finish ? Thanks!

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@catarineaguiar Could you review the test results of this PR? If all are clear, please forward, thank!

**Comment by dantewang** [comment]
@tinatian @shuyangzhou Requested QA review and forwarding if review passes.

**Comment by dantewang** [comment]
@catarineaguiar Never mind, I'm going to forward it.

@shuyangzhou @tinatian Forwarding this one as the result is green (safe to forward as QA stated) and changes are direct replacements.

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
