### PR TITLE
[Hibernate-patch] LPS-155688

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, please refer to the ticket's description.

### CODE REVIEW

**Comment by dantewang** [comment]
@yuhai Could you test this patched version on .x branches? For example, you can install cache on your local, and copy the jar and pom file into the same path in .m2-tmp in 7.3.x, apply the patched version, and run CI with that jar.

**Comment by dantewang** [comment]
@yuhai I think you can just commitCache on liferay-portal-ee/master, and cherry-pick to 7.3.x, etc.

**Comment by yuhai** [comment]
@dantewang, no regressions found. Please refer to 7.3.x test result from https://github.com/yuhai/liferay-portal-ee/pull/57

**Comment by dantewang** [comment]
@yuhai Thanks, please also run 7.2.x, 7.1.x and 7.0.x...

**Comment by yuhai** [comment]
@dantewang, no regressions found. Please refer to the test results from [7.0.x](https://github.com/yuhai/liferay-portal-ee/pull/60), [7.1.x](https://github.com/yuhai/liferay-portal-ee/pull/59), [7.2.x](https://github.com/yuhai/liferay-portal-ee/pull/58) .

**Comment by dantewang** [comment]
@tinatian The fix is from Hibernate's official changes, and the patched version passed tests on 7.0.x ~ 7.3.x. This pull is ready to move forward.

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
@yuhai Please add more details about the fix you used to the commit message.

**Comment by yuhai** [comment]
@tinatian, @dantewang, rebased it and changed the commit message.

**Comment by tinatian** [comment]
@yuhai Please add the details to the second commit, your first commit is just to do inital checkin, it should not change anything, thus you should not add commit message about the fix to it.

**Comment by yuhai** [comment]
@tinatian, rebased it and changed the commit message. Thanks.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
