### PR TITLE
[Remove Unused Reference] LPS-166033 Remove unused @Reference variable in module analytics-reports-document-library-impl

### PR DESCRIPTION
**Pull request by W2jx**
resend, without _portal

Detial: https://github.com/liferay-core-infra/liferay-portal/pull/2125

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:analytics-cloud-acceptance

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/125178

cc @shuyangzhou @tinatian

**Pull request closed without merging**
