### PR TITLE
LPS-185849 Remove multiple configurations from JournalPortlet

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from https://github.com/liferay-core-infra/liferay-portal/pull/4738
- added breaking change notice
- removed integration test for upgrade
- fix upgrade where listConfiguration is using "*", no need since FFJournalAutoSaveDraftConfiguration is not a factory configuration

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:data-engine

**Comment by julschong** [comment]
Added update portal config properties commit and fix sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:data-engine

**Comment by zhangyan0701** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by julschong** [comment]
resolve conflict in breaking change

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
rebase for conflict in breaking change

**Comment by julschong** [comment]
rebase to resolve conflict in breaking change

**Comment by julschong** [comment]
need a solution to not remove FeatureFlag using configuration

**Pull request closed without merging**
