### PR TITLE
[TS] LPS-189621

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
@yuhai force pushed the property description.

**Comment by marianoalvarosaiz** [comment]
@yuhai force pushed the property description.

**Review by yuhai — APPROVED** [review]
@shuyangzhou, @dantewang, the pr is good to me.

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@marianoalvarosaiz I'm not able to create the users using the script attached in the ticket and even with the dummy from the LPP ticket.

**Comment by catarineaguiar** [comment]
no regressions were found on test results.

**Comment by marianoalvarosaiz** [comment]
@catarineaguiar the dummy from the LPP is not working in master, but I have just executed the script over master (HEAD 82972a0781a732ae63c5df85046444950c1d9f2c) and it's working for me. I can see on the console how it's progressing:

```
Added 100 users so far
Added 200 users so far
Added 300 users so far
Added 400 users so far
Added 500 users so far
Added 600 users so far
Added 700 users so far
Added 800 users so far
Added 900 users so far
Added 1000 users so far
Added 1100 users so far
Added 1200 users so far
Added 1300 users so far
Added 1400 users so far
Added 1500 users so far
Added 1600 users so far
Added 1700 users so far
Added 1800 users so far
Added 1900 users so far
Added 2000 users so far
Added 2100 users so far
Added 2200 users so far
Added 2300 users so far
Added 2400 users so far
Added 2500 users so far
The script finished
```

**Comment by catarineaguiar** [comment]
@marianoalvarosaiz did you try executing the script with your changes?

I'm getting this error with your changes:
```
2023-09-29 19:03:16.668 ERROR [http-nio-8080-exec-7][EditServerMVCActionCommand:629] {groupId=33956}
Line 1: import com.liferay.petra.string.StringPool;
Line 2: import com.liferay.portal.kernel.model.GroupConstants;
Line 3: import com.liferay.portal.kernel.service.GroupLocalServiceUtil;
Line 4: import com.liferay.portal.kernel.service.ServiceContext;
Line 5: import com.liferay.portal.kernel.service.ServiceContextThreadLocal;
Line 6: import com.liferay.portal.kernel.util.LocalizationUtil;
Line 7: import com.liferay.portal.kernel.model.Group;
Line 8: import com.liferay.portal.kernel.model.User;
Line 9: import com.liferay.portal.kernel.service.ServiceContextFactory;
Line 10: import com.liferay.portal.kernel.service.UserLocalServiceUtil;
Line 11: import com.liferay.portal.kernel.model.UserConstants;
Line 12: 
Line 13: import java.util.Map;
Line 14: 
Line 15: final String baseSiteName = "Test Site";
Line 16: 
Line 17: ServiceContext serviceContext = ServiceContextFactory.getInstance(
Line 18: 	actionRequest);
Line 19: 
Line 20: long creatorUserId = serviceContext.getUserId();
Line 21: 
Line 22: User creatorUser = UserLocalServiceUtil.getUser(creatorUserId);
Line 23: 
Line 24: long companyId = creatorUser.getCompanyId();
Line 25: Locale locale = creatorUser.getLocale();
Line 26: 
Line 27: Map<Locale, String> descriptionMap = LocalizationUtil.getLocalizationMap("");
Line 28: 
Line 29: Map<Locale, String> nameMap = LocalizationUtil.getLocalizationMap(baseSiteName);
Line 30: 
Line 31: Group group = GroupLocalServiceUtil.addGroup(
Line 32: 		creatorUserId, GroupConstants.DEFAULT_PARENT_GROUP_ID, null, 0,
Line 33: 		GroupConstants.DEFAULT_LIVE_GROUP_ID, nameMap, descriptionMap,
Line 34: 		GroupConstants.TYPE_SITE_OPEN, true, 0, StringPool.BLANK, true, false,
Line 35: 		true, serviceContext);
Line 36: 		
Line 37: 		
Line 38: String password = "test";
Line 39: String screenNameBase = "User";
Line 40: String emailBase = "@liferay.com";
Line 41: 
Line 42: long[] groupIds = [group.getGroupId()];
Line 43: 
Line 44: for (int i = 1; i <= 2500; i++) {
Line 45: 	String screenName = screenNameBase + i;
Line 46: 
Line 47: 	int birthYear = i % 100 + 1910
Line 48: 
Line 49:   UserLocalServiceUtil.addUserWithWorkflow(
Line 50:         creatorUserId, companyId, false, password, password, false, screenName,
Line 51:         screenName + emailBase, locale, screenName, StringPool.BLANK, "User", 0, 0,
Line 52:         true, i % 12, i % 28 + 1, birthYear, StringPool.BLANK, UserConstants.TYPE_REGULAR, 
Line 53:         groupIds, null, null, null, false, serviceContext);
Line 54: 
Line 55: 	if (birthYear == 1910) {
Line 56: 		System.out.println("Added " + i + " users so far");
Line 57: 	}
Line 58: }
Line 59: System.out.println("The script finished");
```

**Comment by marianoalvarosaiz** [comment]
@catarineaguiar does the portal already has the Test Site on it? If so you need a clean environment. If it's a clean environment, could you please attach the image (you can send it through Slack) of the Server Admin failure?

**Comment by catarineaguiar** [comment]
@marianoalvarosaiz oh, it was my mistake. It worked now!!
Thanks.

**Comment by marianoalvarosaiz** [comment]
Great @catarineaguiar !

**Comment by shuyangzhou** [comment]
We now have 3 this kind of properties.
[database.max.parameters[sqlserver]](https://github.com/liferay-core-infra/liferay-portal/blob/32d251473cf3c364acb4ff9e9b18e00235ddb632/portal-impl/src/portal.properties#L1406)
[database.in.max.parameters[oracle]](https://github.com/liferay-core-infra/liferay-portal/blob/32d251473cf3c364acb4ff9e9b18e00235ddb632/portal-impl/src/portal.properties#L1413C5-L1413C39)
[sql.data.max.parameters](https://github.com/liferay-core-infra/liferay-portal/blob/32d251473cf3c364acb4ff9e9b18e00235ddb632/portal-impl/src/portal.properties#L1786C5-L1786C28)

I highly doubt they are all needed, even somehow they are, the names for sure will need some adjustment to make things easier to understand.

Please resend.

**Comment by marianoalvarosaiz** [comment]
@shuyangzhou see https://github.com/liferay-core-infra/liferay-portal/pull/5691

**Pull request closed without merging**
