### PR TITLE
[Static reference] LPS-182294 Remove method reference by using snapshot in module dynamic-data-mapping-form-web

### PR DESCRIPTION
**Pull request by W2jx**
Code conflict, resend.

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:forms

**Review by dantewang — CHANGES_REQUESTED** [review]

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:forms

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(4/25 8:02)

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
