### PR TITLE
LPS-178022 portal-search-web Part 1 | Rebase on BChan/master

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@julschong There's a conflict with BChan's master on `modules/apps/portal-search/portal-search-web/src/main/java/com/liferay/portal/search/web/internal/sort/portlet/shared/search/SortPortletSharedSearchContributor.java`, since the upstream change also removed the stream usage, I skipped your change.

**Comment by dantewang** [comment]
SF error can be ignored.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by julschong** [comment]
@dantewang I rebased again on upstream master. I think the additional commits are causing ci tests to not run
https://github.com/liferay-core-infra/liferay-portal/pull/4066

**Pull request closed without merging**
