### PR TITLE
[Replace Non-Blocking Usage] LPS-200090

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace non-blocking ServiceProxyFactory usages in class `FullNameValidatorFactory`. Thanks.
https://liferay.atlassian.net/browse/LPS-200090

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142898

cc @shuyangzhou

**Pull request closed without merging**
