### PR TITLE
[Phase 1] LPS-178022 Remove Stream and Optional usages for module: portal-search-web final

### PR DESCRIPTION
**Pull request by julschong**
@tinatian Hi Tina,
per Brian's request, I just the methods backs to returning value or null.
The usages that needed default Blank are changed to use GetterUtil and getValue instead
https://github.com/brianchandotcom/liferay-portal/pull/133508#issuecomment-1513005934

I added a little more removal at the end so that we dont need to do another part for this module.
After this one is done, I can move on to removing Optional from portal-search-web-api.

Thank you

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:search

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
