### PR TITLE
[TS] LPD-43062

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__
<https://liferay.atlassian.net/browse/LPD-43062>

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:core-functional

**Comment by kevhlee** [comment]
ci:stop

**Comment by kevhlee** [comment]
Going to re-run the tests since the errors above seem to indicate that an error occurred with CI itself.

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:test:core-functional

**Comment by tinatian** [comment]
@kevhlee Please review this pull by yourself again based on our talk about rules of commit. Also, please consider these questions:

1. Where should the set be added? Can you avoid unnecessary transformation from different type of collections?
2. Why left and right are using different type of collections? Should they be consistent by using same?

Please resend.

Thanks.
Tina

**Pull request closed without merging**
