### PR TITLE
[System Properties] LPS-158153 Add new functionality to SystemProperties: get property with default value, and get array（These functions are needed when moving module framwork properties）

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , This PR includes two new methods and unit tests.

### CODE REVIEW

**Comment by dantewang** [comment]
@W2jx Code looks good to me, but we usually do this for commits:

- LPS-XXX Add new API 1
- LPS-XXX Apply
- LPS-XXX Add new API 2
- LPS-XXX Apply

Please reorder them and modify the commit message of your "usage" commits.

**Review by dantewang — CHANGES_REQUESTED** [review]
@W2jx Please see my comment and update, thanks!

**Comment by W2jx** [comment]
ci:test:acceptance

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me scan test results when you free ? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]
@W2jx Code looks good to me, but there's still an issue with your commit message. You put `SystemProperties: ` in all your code change commits except `Apply`. Why? Please make them consistent. Thanks!

@tinatian The PR has passed QA review, and I ask only a change to commit messages, so there's no need to rerun tests after force push.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121082

**Pull request closed without merging**
