### PR TITLE
[Components with more than 1 service] LPS-192654 Refactor SXPParameterDataCreator component

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-192654](https://liferay.atlassian.net/browse/LPS-192654)

Hey @shuyangzhou , you asked me to make an inline [here](https://github.com/liferay-core-infra/liferay-portal/pull/5374#issuecomment-1696494740), I tried to do it, but these classes are in an internal package and are linked to other classes that are also this internal package, so to make the inline I would have to move a lot of classes to the other module

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:search

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@RenanUmV tests didn't run due to:

```
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/search-experiences/search-experiences-service/src/main/java/com/liferay/search/experiences/internal/blueprint/parameter/contributor/SXPParameterContributorProvider.java:13: error: cannot find symbol
     [exec] import com.liferay.portal.kernel.module.configuration.ConfigurationProvider;
     [exec]                                                      ^
     [exec]   symbol:   class ConfigurationProvider
     [exec]   location: package com.liferay.portal.kernel.module.configuration
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/search-experiences/search-experiences-service/src/main/java/com/liferay/search/experiences/internal/blueprint/parameter/contributor/SXPParameterContributorProvider.java:64: error: cannot find symbol
     [exec] 	private ConfigurationProvider _configurationProvider;
     [exec] 	        ^
     [exec]   symbol:   class ConfigurationProvider
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-09/test-1-31/test-portal-acceptance-pullrequest(master)/9373/jenkins-console.txt.gz?authuser=0)

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Pull request closed without merging**
