### PR TITLE
[Components with more than 1 service] Refactor Saml components from saml modules

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**
[LPS-185512](https://liferay.atlassian.net/browse/LPS-185512)

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:security

**Comment by GabrielHenriquedev** [comment]
ci:test:saml

**Comment by GabrielHenriquedev** [comment]
ci:test:security

**Comment by GabrielHenriquedev** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@GabrielHenriquedev Looks like there are startup issues caused by these changes
```
[beanshell] 2023-06-23 16:21:50.191 INFO  [SystemExecutorServiceUtil-3][BundleSiteInitializer:635] Initialized com.liferay.site.initializer.welcome for group 20119 in 4885 ms
[beanshell] 2023-06-23 16:21:52.466 INFO  [main][SystemCheckOSGiCommands:77] Running system check
[beanshell] 2023-06-23 16:21:52.467 INFO  [main][SystemCheckOSGiCommands:115] Available checkers :[Spring Extender Unavailable Component Checker, Declarative Service Soft Circular Dependency Checker, Declarative Service Unsatisfied Component Checker, Missing Component Scanner]
[beanshell] 2023-06-23 16:21:52.468 INFO  [main][SystemCheckOSGiCommands:131] Running "Spring Extender Unavailable Component Checker". You can run this by itself with command "dm na" in gogo shell.
[beanshell] 2023-06-23 16:21:52.470 INFO  [main][SystemCheckOSGiCommands:143] Spring Extender Unavailable Component Checker check result: No issues were found.
[beanshell] 2023-06-23 16:21:52.471 INFO  [main][SystemCheckOSGiCommands:131] Running "Declarative Service Soft Circular Dependency Checker". You can run this by itself with command "ds:softCircularDependency" in gogo shell.
[beanshell] 2023-06-23 16:21:56.286 ERROR [main][ROOT:56] bundle org.apache.felix.scr:2.1.14.LIFERAY-PATCHED-8 (72)Circular reference detected trying to get service {org.opensaml.security.credential.CredentialResolver}={component.id=2792, component.name=com.liferay.saml.opensaml.integration.internal.credential.KeyStoreCredentialResolver, KeyStoreManager.target=(default=true), service.id=12367, service.scope=bundle, service.bundleid=711}
[beanshell]  stack of references: ServiceReference: {org.opensaml.security.credential.CredentialResolver}={component.id=2792, component.name=com.liferay.saml.opensaml.integration.internal.credential.KeyStoreCredentialResolver, KeyStoreManager.target=(default=true), service.id=12367, service.scope=bundle, service.bundleid=711}
[beanshell] ServiceReference: {javax.servlet.Filter}={servlet-context-name=, component.id=1208, url-pattern=/c/portal/logout, component.name=com.liferay.saml.internal.servlet.filter.IdpSsoSamlPortalFilter, after-filter=Virtual Host Filter, service.id=21469, service.scope=bundle, servlet-filter-name=IDP SSO SAML Portal Filter, dispatcher=[FORWARD,REQUEST], service.bundleid=377}
[beanshell] ServiceReference: {com.liferay.saml.util.SamlHttpRequestUtil}={component.id=2804, component.name=com.liferay.saml.opensaml.integration.internal.metadata.SamlHttpRequestUtilImpl, service.id=21462, service.scope=bundle, service.bundleid=711}
[beanshell] ServiceReference: {com.liferay.saml.opensaml.integration.internal.metadata.MetadataManager}={component.id=2803, component.name=com.liferay.saml.opensaml.integration.internal.metadata.MetadataManagerImpl, service.id=21461, service.scope=bundle, service.bundleid=711}
[beanshell] 
[beanshell] java.lang.Exception: stack trace
[beanshell] 	at org.apache.felix.scr.impl.ComponentRegistry.enterCreate(ComponentRegistry.java:485) [bundleFile:?]
[beanshell] 	at org.apache.felix.scr.impl.BundleComponentActivator.enterCreate(BundleComponentActivator.java:728) [bundleFile:?]
[beanshell] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:882) [bundleFile:?]
[beanshell] 	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212) [org.eclipse.osgi.jar:?]
```
[Log](https://testray.liferay.com/reports/production/logs/2023-06/test-1-29/test-portal-acceptance-pullrequest(master)/7530/functional-smoke-tomcat90-hypersonic20-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
