### PR TITLE
[Remove Blocking usages]LPS-188270 portal-kernel | ConfigurationProviderUtil 

### PR DESCRIPTION
**Pull request by W2jx**
Fix tests.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5378

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@W2jx Regression found

com.liferay.journal.web.internal.display.context.JournalEditArticleDisplayContextTest
```
     [exec] com.liferay.journal.web.internal.display.context.JournalEditArticleDisplayContextTest > testIsShowSelectFolderAddActionFalseParamValue STARTED
     [exec] 
     [exec] com.liferay.journal.web.internal.display.context.JournalEditArticleDisplayContextTest > testIsShowSelectFolderAddActionFalseParamValue FAILED
     [exec]     java.lang.NoSuchFieldException: No field on null with name _configurationProvider
     [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.getField(ReflectionTestUtil.java:126)
     [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.setFieldValue(ReflectionTestUtil.java:324)
     [exec]         at com.liferay.journal.web.internal.display.context.JournalEditArticleDisplayContextTest.setUp(JournalEditArticleDisplayContextTest.java:62)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

```
[Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-33/test-portal-acceptance-pullrequest(master)/4309/modules-unit-jdk8/0/5/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
no conflicts(8/31 8:55)

**Comment by W2jx** [comment]
Forced push to resolve the conflict about build.gradle file, no logic changes.

**Comment by dantewang** [comment]
@W2jx Sorry, conflicts again. Please rebase and resend, thanks!

**Pull request closed without merging**
