### PR TITLE
LPS-151745 Add LIFERAY_SHARED_ prefix to attribute name in order to propagate the check access allowed to the portlet until the PortletFragmentEntryProcessor 

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-151745

Previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/959

See comment: https://github.com/liferay-core-infra/liferay-portal/pull/959#issuecomment-1169017911

@dantewang @tinatian

The changes since the previous PR are:
* I have removed the first commit that introduced a constant.
* I replaced the constant use in subsequent commits with the hardcoded literal.

Could you please review this pull request?

Thanks

Regards

### CODE REVIEW

**Comment by dantewang** [comment]
@catarineaguiar Could you please review the CI results? Thanks!

@tinatian The change looks good according to your comment https://github.com/liferay-core-infra/liferay-portal/pull/959#issuecomment-1169017911.

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
@lfbesada @dantewang no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/119924

**Pull request closed without merging**
