### PR TITLE
LPS-170715 Remove the class SettingsContributor and its only impl UnicastSettingsContributor

### PR DESCRIPTION
**Pull request by W2jx**
This PR is a preparatory task for [task Convert method reference to ServiceTrackerList in module portal-search-elasticsearch7-impl](https://issues.liferay.com/browse/LPS-165165).

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/2425

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:help

**Comment by zhangyan0701** [comment]
Below test failures seem related:
1. [com.liferay.portal.search.elasticsearch7.internal.cluster.ReplicasManagerImplTest](https://testray.liferay.com/home/-/testray/case_results/2110430124):
`testSystemCompanyIndexIsReplicatedAndMigrated: java.lang.RuntimeException: java.net.SocketTimeoutException: 120,000 milliseconds timeout on connection http-outgoing-16 [ACTIVE]`
Full console log:
https://testray.liferay.com/reports/production/logs/2022-12/test-1-31/test-portal-acceptance-pullrequest(master)/6298/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0
2. [com.liferay.portal.search.elasticsearch7.internal.cluster.ClusterUnicastTest](https://testray.liferay.com/home/-/testray/case_results/2110430102):
`testSplitBrainPreventedEvenIfMasterLeaves: java.lang.RuntimeException: java.net.SocketTimeoutException: 120,000 milliseconds timeout on connection http-outgoing-18 [ACTIVE]`
Full console log:
https://testray.liferay.com/reports/production/logs/2022-12/test-1-31/test-portal-acceptance-pullrequest(master)/6298/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0
3. [com.liferay.portal.search.elasticsearch7.internal.cluster.ClusterSettingsTest](https://testray.liferay.com/home/-/testray/case_results/2110430095):
`testClusterSettings: org.junit.ComparisonFailure: expected:<[60]0s> but was:<[3]0s>`
Full console log:
https://testray.liferay.com/reports/production/logs/2022-12/test-1-31/test-portal-acceptance-pullrequest(master)/6298/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0
4. [com.liferay.portal.search.elasticsearch7.internal.cluster.Cluster2InstancesTest](https://testray.liferay.com/home/-/testray/case_results/2110430091):
`Failed tests: test2Nodes1PrimaryShard, testExpandAndShrink`
Full console log:
https://testray.liferay.com/reports/production/logs/2022-12/test-1-31/test-portal-acceptance-pullrequest(master)/6298/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by W2jx** [comment]
I will check them.

**Comment by dantewang** [comment]
Close it for now. Please resend.

**Pull request closed without merging**
