### PR TITLE
[Remove Blocking Usages] LPS-197527 Removing Unnecessary Usages of ServiceProxyFactory.newServiceTrackedInstance with blocking set to true in class LiferayFileEntry

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141589

**Pull request closed without merging**
