### PR TITLE
[LPS-167246 MessageBus] LPS-192680 Remove unused destination liferay/hot_deploy

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:forward:force

FYI  @david-truong @ericyanLr, this pull includes a breaking change at https://github.com/liferay-core-infra/liferay-portal/pull/5284/commits/a6cde4fab0680197d01a5ccbeb4e674e356dfecc

FYI @shuyangzhou

**Comment by tinatian** [comment]
@dantewang This pull has code conflicts with Brian's upstream, please wait for upstream updated and rebase.

Thanks.
Tina

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
