### PR TITLE
[Unused Reference]  LPD-8469 | LPD-8470 Remove unused @Reference variables in PortletTracker.java I and II 

### PR DESCRIPTION
**Pull request by Valmir-unicap**
- Ticket: https://liferay.atlassian.net/browse/LPD-8469 and https://liferay.atlassian.net/browse/LPD-8470

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:report:2551531123

**Comment by Valmir-unicap** [comment]
ci:report:2551035960

**Comment by Valmir-unicap** [comment]
ci:report:2551035960

**Comment by Valmir-unicap** [comment]
No regression found!

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
ci:test:stable

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
