### PR TITLE
[Components with more than 1 service] LPS-189884 Refactor ReleaseManagerImpl component

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-189884

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by chaowang-123** [comment]
ci:help

**Comment by chaowang-123** [comment]
ci:test:clustering

**Comment by chaowang-123** [comment]
Hi @MrJohn1911 
Found a regression issue: [com.liferay.portal.cluster.multiple.internal.ClusterMasterExecutorImplTest](https://testray.liferay.com/home/-/testray/case_results/2373210639?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3Fstatuses%3D3%26testrayBuildId%3D2373208913%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26status%3D3)
```
[exec] com.liferay.portal.cluster.multiple.internal.ClusterMasterExecutorImplTest > testGetMasterClusterNodeId FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.portal.cluster.multiple.internal.ClusterMasterExecutorImplTest._getMockClusterExecutor(ClusterMasterExecutorImplTest.java:787)
     [exec]         at com.liferay.portal.cluster.multiple.internal.ClusterMasterExecutorImplTest.testGetMasterClusterNodeId(ClusterMasterExecutorImplTest.java:379)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
     [exec]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
     [exec]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
     [exec]         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
     [exec]         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]         at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]         at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]         at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
     [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
     [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
     [exec]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
     [exec]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
     [exec]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
```
whole [log](https://testray.liferay.com/reports/production/logs/2023-07/test-1-31/test-portal-acceptance-pullrequest(master)/8627/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by chaowang-123** [comment]
@slnn  could you help to add QA Failed label?

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:clustering

**Comment by dantewang** [comment]
@MrJohn1911 If the util in this PR is also extracted due to the integration test, please see if you can apply the solution I sent, thanks!

**Pull request closed without merging**
