### PR TITLE
[Performance Tuning] LPS-150076 Optimize SearchBarPortlet display context creation

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian @slnn

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@slnn As we talked, please resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
