### PR TITLE
LPS-171295 upgrade PostgreSQL-JDBC to 42.4.3

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-171295.
Thanks for checking.

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:environments

**Comment by jaydawu** [comment]
Hello @dantewang, no regression found. Can be passed. Thanks.

**Comment by jeffwu0724** [comment]
fixed the code conflict in versions.html by auto generate. The previous test should be good enough

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128178

**Pull request closed without merging**
