### PR TITLE
LPS-171214 Remove "immediate = true" from Security components part 2

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@GabrielHenriquedev No regressions found.

**Comment by GabrielHenriquedev** [comment]
@shuyangzhou  this one is ready to go.

**Comment by tinatian** [comment]
ci:forward

FYI @shuyangzhou

**Pull request closed without merging**
