### PR TITLE
LPS-150134 - Widget scopes not correctly applied when staging

### PR DESCRIPTION
**Pull request by DaniSzimko**
[LPS-150134](https://liferay.atlassian.net/browse/LPS-150134) - When checkStagingGroup is true and the portletScopeGroup is a staging group, set the scopeGroupId to the portletScopeGroupId + modify the relevant test class to run the Blog portlet tests

Hello team,
I would like to request a review of this PR, as it changes the **getScopeGroupId** method in the **PortalImpl** class
to align the behavior of the portlet's groupId with the approach outlined in the **StagingGetScopeGroupIdTest** class's **_getExpectedGroup** method.

Your review and feedback are highly appreciated, thank you.

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:staging

**Comment by catarineaguiar** [comment]
no regressions found.

[com.liferay.staging.test.StagingGetScopeGroupIdTest](https://testray.liferay.com/home/-/testray/case_results/2402990161?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2402988901%26testrayRunId%3D2402989477%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) passed.

**Comment by dantewang** [comment]
@brunofalc The ticket was originated from customer request, but not customer driven now, as a hotfix has been provided. I think we still should mark it "TS".

**Comment by tinatian** [comment]
@DaniSzimko Could you please restructure the changes you made? Add the test to expose the issues first, then fix the code.

Please resend.

Thanks.
Tina.

**Pull request closed without merging**
