### PR TITLE
LPS-199026 Remove legacy destination name check

### PR DESCRIPTION
**Pull request by holatuwol**
https://liferay.atlassian.net/browse/PTR-4041
https://liferay.atlassian.net/browse/LPS-199026

## Background information

This fix came about from a discussion on PTR-4041, linked above. Based on the guidance provided there:

> if you want your job to be run in a separate thread pool, you can provide your own destination in SchedulerJobDefintion

We had the customer add a new message bus destination and register their scheduled jobs to that destination. However, they then experienced an issue where, due to having two scheduled jobs, both of the jobs registered to that new destination would always fire whenever one of them was scheduled to fire.

With that in mind, I created 10 scheduled jobs that ran every minute, registered to a custom destination, and essentially all scheduled jobs ran 10 times every minute.

## Solution notes

The original commit e1bb386019a39241e2ee37b7491664ba595bfa62 has the following commit message:

>  LPS-7397 Fix bug in [rev-65328](https://github.com/liferay/liferay-portal/commit/ba09de65066407bfd046b6567571bfe53a78e641), skip check of key for those not using SCHEDULER_DISPATCH as destination.

I understand the first part of the commit message that mentions fixing a bug (essentially, it's the same problem that we see in LPS-199026, where every listener is fired for every scheduled job registered to the destination).

However, it is not clear why we explicitly skip the check for other message bus destinations and only add this check for a `SchedulerJobConfigurationMessageListener` that uses the default message bus destination, since other scheduled job listeners experience the same problem.

Since this check introduces what appears to be a defect, I felt it makes sense to simply remove that check.

## Additional notes

Please let me know if this check is intended to serve some other purpose, and if people are actually not supposed to reuse custom message bus destinations when they have multiple scheduled jobs that they do not want blocked by any potentially misconfigured scheduled job registered to the regular `SCHEDULER_DISPATCH` destination.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:clustering

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@holatuwol No regressions. Testing passed following ticket steps.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142355

**Pull request closed without merging**
