### PR TITLE
[TS] LPD-19938

### PR DESCRIPTION
**Pull request by kevhlee**
__Tickets:__
<https://liferay.atlassian.net/browse/LPD-19938>
<https://liferay.atlassian.net/browse/LPP-53015>

This PR changes the Log4j logger so that `null` is not logged in the first line of the exception. This is to make logs more readable, specifically for Liferay SaaS. See [LPP-53015](https://liferay.atlassian.net/browse/LPP-53015) for context.

Before:

```log
2024-02-27 17:09:39.493 ERROR [liferay/background_task-6][AdvancedPermissionChecker:1276] null
com.liferay.portal.kernel.exception.NoSuchUserException: No User exists with the primary key 212533
	at com.liferay.portal.service.persistence.impl.UserPersistenceImpl.findByPrimaryKey(UserPersistenceImpl.java:9010) ~[portal-impl.jar:?]
	at com.liferay.portal.service.persistence.impl.UserPersistenceImpl.findByPrimaryKey(UserPersistenceImpl.java:9026) ~[portal-impl.jar:?]
	at com.liferay.portal.service.impl.UserGroupRoleLocalServiceImpl.hasUserGroupRole(UserGroupRoleLocalServiceImpl.java:309) ~[portal-impl.jar:?]
```

After:

```log
2024-02-27 17:09:39.493 ERROR [liferay/background_task-6][AdvancedPermissionChecker:1276] No User exists with the primary key 212533
com.liferay.portal.kernel.exception.NoSuchUserException: No User exists with the primary key 212533
	at com.liferay.portal.service.persistence.impl.UserPersistenceImpl.findByPrimaryKey(UserPersistenceImpl.java:9010) ~[portal-impl.jar:?]
	at com.liferay.portal.service.persistence.impl.UserPersistenceImpl.findByPrimaryKey(UserPersistenceImpl.java:9026) ~[portal-impl.jar:?]
	at com.liferay.portal.service.impl.UserGroupRoleLocalServiceImpl.hasUserGroupRole(UserGroupRoleLocalServiceImpl.java:309) ~[portal-impl.jar:?]
```

Not sure if this is the right way to approach this, so please let me know if this is not. Let me know if you have any questions/thoughts/concerns.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:2547827252

**Comment by tinatian** [comment]
@kevhlee Please check the unique failures from report.

**Comment by kevhlee** [comment]
Ok @tinatian. I will take a look at the unique failures.

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:stop

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:report:2548828994

**Comment by kevhlee** [comment]
Test failures are unrelated.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/148138

**Pull request closed without merging**
