### PR TITLE
[Remove Stream/Optional usage] LPS-175366 module export-import-test-util

### PR DESCRIPTION
**Pull request by JanisZhang**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3433
https://issues.liferay.com/browse/LPS-175366

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:export-import

**Comment by JanisZhang** [comment]
force-pushed. I only change the variable name,  append 1 SF commit. No need to re-trigger test.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Pull request closed without merging**
