### PR TITLE
LPS-147424 Remove hessian.jar

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by guilhermedcamacho** [comment]
@koor4356 please help me check the results, thanks!

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
@guilhermedcamacho 
This looks good except upgrade error below. It may be a fluke but take a look at it. If it is not related to this PR, then the PR is good. Thanks!

`INFO  [Portal Dependency Manager Component Executor--2][UpgradeProcess:134] Failed upgrade process com.liferay.layout.internal.upgrade.v1_1_0.UpgradeCompanyId in 27 ms
     [java] 2022-02-16 02:09:26.401 ERROR [Portal Dependency Manager Component Executor--2][UpgradeStepRegistratorTracker:221] Failed upgrade process for module com.liferay.layout.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.LAYOUTCLASSEDMODELUSAGE, DRIVER=4.24.92
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:128) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:146) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor$UpgradeInfosRunnable.run(UpgradeExecutor.java:230) ~[?:?]
     [java] 	at com.liferay.portal.output.stream.container.internal.OutputStreamContainerFactoryTrackerImpl.runWithSwappedLog(OutputStreamContainerFactoryTrackerImpl.java:134) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.SwappedLogExecutor.execute(SwappedLogExecutor.java:51) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.executeUpgradeInfos(UpgradeExecutor.java:158) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.execute(UpgradeExecutor.java:118) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.registry.UpgradeStepRegistratorTracker$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeStepRegistratorTracker.java:214) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.registry.UpgradeStepRegistratorTracker$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeStepRegistratorTracker.java:147) ~[?:?]
     [java] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943) ~[org.eclipse.osgi.jar:?]`

https://testray.liferay.com/reports/production/logs/2022-02/test-1-32/test-portal-acceptance-pullrequest(master)/2513/functional-tomcat90-db2111-jdk8/1/14/jenkins-console.txt.gz?authuser=0

https://testray.liferay.com/home/-/testray/case_results/1612057886

**Comment by guilhermedcamacho** [comment]
Thanks @koor4356 , I will take a look

**Comment by guilhermedcamacho** [comment]
ci:test:upgrade

**Comment by guilhermedcamacho** [comment]
Hey @koor4356 , can you help me check the results? thanks!

**Comment by koor4356** [comment]
@guilhermedcamacho, 
The upgrade looks good. The issue listed above did not reoccur. thanks!

**Comment by guilhermedcamacho** [comment]
@tinatian, this PR is ready for your review. Thanks!

**Comment by tinatian** [comment]
@guilhermedcamacho Code conflicts, please rebase.

Thanks.
Tina

**Comment by guilhermedcamacho** [comment]
Hey @tinatian , conflict fixed, thanks!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113898

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
