### PR TITLE
[Replace Non-Blocking Usage] LPS-199976 kernel/search

### PR DESCRIPTION
**Pull request by haydenzheng314**
Ticket: https://liferay.atlassian.net/browse/LPS-199976
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@LisztLiszt There is a startup issue affecting all tests

```
eanshell] 2023-10-26 03:44:40.692 INFO  [main][LoggingTimer:35] Completed com.liferay.portal.events.StartupHelperUtil#initResourceActions in 262 ms
[beanshell] 2023-10-26 03:44:41.287 INFO  [main][AutoDeployDir:152] Auto deploy scanner started for /opt/dev/projects/github/liferay-portal/bundles/deploy
[beanshell] 2023-10-26 03:44:42.461 ERROR [main][MainServlet:373] null
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.portal.kernel.search.IndexWriterHelperUtil.updatePermissionFields(IndexWriterHelperUtil.java:254) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.service.impl.ResourcePermissionLocalServiceImpl._updateResourcePermission(ResourcePermissionLocalServiceImpl.java:2288) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.service.impl.ResourcePermissionLocalServiceImpl.updateResourcePermission(ResourcePermissionLocalServiceImpl.java:1745) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.service.impl.ResourcePermissionLocalServiceImpl.addResourcePermission(ResourcePermissionLocalServiceImpl.java:311) ~[portal-impl.jar:?]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_381]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_381]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_381]
[beanshell] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41) ~[portal-impl
```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-29/test-portal-acceptance-pullrequest(master)/8489/functional-smoke-startup-tomcat90-mysql57-jdk8/0/17/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
