### PR TITLE
[Components with more than 1 service] LPS-188896 XLIFFInfoFormTranslationImporter

### PR DESCRIPTION
**Pull request by dantewang**
https://github.com/liferay-core-infra/liferay-portal/pull/4991

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:translation

**Comment by dantewang** [comment]
ci:test:security

**Comment by dantewang** [comment]
cc @Valmir-unicap

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by Valmir-unicap** [comment]
ci:test:lima

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137983

**Pull request closed without merging**
