### PR TITLE
LPS-175209

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 This pull needs to verify https://issues.liferay.com/browse/LPS-98420, I am not sure if it is already covered by ci test, if not, please test manually.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@zhangyan0701 Can you test today?

**Comment by vicnate5** [comment]
CC @gaborlovasdotcom

**Comment by zhangyan0701** [comment]
@tinatian @vicnate5 

I manually tested https://issues.liferay.com/browse/LPS-98420 and it is NOT reproducible with the changes here.

But the script that can help reproduce the issue in the ticket is old, I made a little changes when testing:
```
import com.liferay.portal.kernel.scheduler.messaging.SchedulerResponse;
import com.liferay.portal.kernel.scheduler.SchedulerEngineHelperUtil;
import com.liferay.portal.kernel.scheduler.StorageType;
import com.liferay.portal.kernel.messaging.Message;
import com.liferay.portal.kernel.util.PrefsPropsUtil;
import java.util.List;
import com.liferay.portal.kernel.scheduler.Trigger;

try {
boolean enable = PrefsPropsUtil.getBoolean("scheduler.enabled");
out.println("scheduler.enabled:" + enable);

String groupName = "com.liferay.portal.security.ldap.internal.configuration.persistence.listener.UserImportConfigurationModelListener";

    List<SchedulerResponse> schedulerResponses = SchedulerEngineHelperUtil.getScheduledJobs(groupName, StorageType.MEMORY_CLUSTERED);

    if (schedulerResponses.isEmpty()) {
     out.println("there is not scheduler executed for this listener");
    }

    for (SchedulerResponse schedulerResponse : schedulerResponses) {
     Trigger trigger = schedulerResponse.getTrigger();
     Message message = schedulerResponse.getMessage();
     out.println(message.toString());
 
    }
}
catch (Exception e) {
    throw e;
}
```

**Comment by Kvale1733** [comment]
ci:test:ldap

**Comment by vicnate5** [comment]
@gaborlovasdotcom Can this LDAP scenario be automated?

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130015

**Comment by gaborlovasdotcom** [comment]
> @gaborlovasdotcom Can this LDAP scenario be automated? See script update in [#3402 (comment)](https://github.com/liferay-core-infra/liferay-portal/pull/3402#issuecomment-1424177076)

Filed a new ticket for it [LRQA-79487](https://issues.liferay.com/browse/LRQA-79487)

**Pull request closed without merging**
