### PR TITLE
[Rename classes in module: content-dashboard]Lps 167329

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-167329

### CODE REVIEW

**Comment by slnn** [comment]
Forced push according to the comment https://github.com/liferay-core-infra/liferay-portal/pull/2313#issuecomment-1299929107  fix the lacked space in commit message, no logic changes.

**Comment by zhangyan0701** [comment]
ci:test:tango

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Comment by slnn** [comment]
Force push to fix the conflicts for bnd and packageinfo files

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Comment by zhangyan0701** [comment]
Semantic versioning error in the new relevant result:
```
     [exec] > Task :apps:content-dashboard:content-dashboard-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.content.dashboard.item.action          MAJOR      1.7.0      1.7.0      2.0.0      VERSION INCREASE REQUIRED
     [exec] 	+   interface  com.liferay.content.dashboard.item.action.ContentDashboardItemActionProviderRegistry
     [exec] 		+   access     abstract
     [exec] 		+   method     getContentDashboardItemActionProviderOptional(java.lang.String,com.liferay.content.dashboard.item.action.ContentDashboardItemAction$Type)
     [exec] 			+   access     abstract
     [exec] 			+   return     java.util.Optional
     [exec] 		+   method     getContentDashboardItemActionProviders(java.lang.String,com.liferay.content.dashboard.item.action.ContentDashboardItemAction$Type[])
     [exec] 			+   access     abstract
     [exec] 			+   return     java.util.List
     [exec] 	-   interface  com.liferay.content.dashboard.item.action.ContentDashboardItemActionProviderTracker
     [exec] 		-   access     abstract
     [exec] 		-   method     getContentDashboardItemActionProviderOptional(java.lang.String,com.liferay.content.dashboard.item.action.ContentDashboardItemAction$Type)
     [exec] 			-   access     abstract
     [exec] 			-   return     java.util.Optional
     [exec] 		-   method     getContentDashboardItemActionProviders(java.lang.String,com.liferay.content.dashboard.item.action.ContentDashboardItemAction$Type[])
     [exec] 			-   access     abstract
     [exec] 			-   return     java.util.List
     [exec] 	+   interface  com.liferay.content.dashboard.item.action.ContentDashboardItemVersionActionProviderRegistry
     [exec] 		+   access     abstract
     [exec] 		+   method     getContentDashboardItemVersionActionProviders(java.lang.String)
     [exec] 			+   access     abstract
     [exec] 			+   return     java.util.List
     [exec] 	-   interface  com.liferay.content.dashboard.item.action.ContentDashboardItemVersionActionProviderTracker
     [exec] 		-   access     abstract
     [exec] 		-   method     getContentDashboardItemVersionActionProviders(java.lang.String)
     [exec] 			-   access     abstract
     [exec] 			-   return     java.util.List
     [exec] * com.liferay.content.dashboard.item.type            MAJOR      1.3.0      1.2.0      2.0.0      VERSION INCREASE REQUIRED
     [exec] 	+   interface  com.liferay.content.dashboard.item.type.ContentDashboardItemSubtypeFactoryRegistry
     [exec] 		+   access     abstract
     [exec] 		+   method     getClassNames()
     [exec] 			+   access     abstract
     [exec] 			+   return     java.util.Collection
     [exec] 		+   method     getContentDashboardItemSubtypeFactoryOptional(java.lang.String)
     [exec] 			+   access     abstract
     [exec] 			+   return     java.util.Optional
     [exec] 	-   interface  com.liferay.content.dashboard.item.type.ContentDashboardItemSubtypeFactoryTracker
     [exec] 		-   access     abstract
     [exec] 		-   method     getClassNames()
     [exec] 			-   access     abstract
     [exec] 			-   return     java.util.Collection
     [exec] 		-   method     getContentDashboardItemSubtypeFactoryOptional(java.lang.String)
     [exec] 			-   access     abstract
     [exec] 			-   return     java.util.Optional
     [exec] 	-   version    1.2.0
     [exec] 	+   version    1.3.0
     [exec] [Baseline Warning] Bundle Version Change Recommended: 5.0.0
```
Full console log:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-33/test-portal-acceptance-pullrequest(master)/2371/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by dantewang** [comment]
@slnn Please fix sem ver and resend.

**Comment by slnn** [comment]
Fix and resend in https://github.com/liferay-core-infra/liferay-portal/pull/2360

**Pull request closed without merging**
