### PR TITLE
[Remove unused reference] LPS-166029

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove unused fields in `layout-page-template-admin-web`. Thanks!
https://issues.liferay.com/browse/LPS-166029

### CODE REVIEW

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
@JanisZhang Conflicts, please update.

**Comment by JanisZhang** [comment]
@dantewang  Force-pushed. Thanks!

**Comment by JanisZhang** [comment]
Hi @dantewang  Forced-pushed again as I just found a hidden usage of `_portal`, through ` JSONPortletResponseUtil.writeJSON -> ``PortalUtil.getHttpServletResponse` in `AddLayoutPrototypeMVCActionCommand`. Thanks!

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
No regressions found.

cc/ @zhangyan0701

**Comment by tinatian** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/125472

**Pull request closed without merging**
