### PR TITLE
LPS-202452 LPS-202453 patch opensearch to make it java 8 compatible

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

Resent: https://github.com/liferay-core-infra/liferay-portal/pull/6245, based on Petteri's request, also apply https://github.com/peerkar/opensearch-java/commit/e224321fb32cab94258cb84192592f63b6794fa3 to the pathed jar
This is for ticket https://liferay.atlassian.net/browse/LPS-202425
I am helping @peerkar to make the patch for opensearch-java-client and opensearch-rest-client to make them java 8 compatible.

cc: @lipusz @brunofalc 
Thanks for checking

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@jeffwu0724 As we talked, I will close this pull.

Thanks.
Tina

**Pull request closed without merging**
