### PR TITLE
LPD-20946 | 5-30

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
Hi @JerryAdrianoo, please run a startup comparison for this PR. We need data with
- master head
- commit https://github.com/liferay-core-infra/liferay-portal/pull/7090/commits/385d752fc044931daecb8902b21c8c65f1af54bc
- this whole PR

Please run on both DXP and CE, and compare all metrics, thanks!

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by JerryAdrianoo** [comment]
Hey @dantewang, it looks like the regressions have been fixed. I put the results in this[ Spreadsheet](https://docs.google.com/spreadsheets/d/1Ox1PV9BUQxBQghTookJheqqxoxxODx6d-boUuUjoF1E/edit#gid=0).
Feel free to let me know if you need anything else.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:report:2574058624

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 2574058624.
> 
> Job Link: [generate-testray-csv](https://test-1-10.liferay.com/job/generate-testray-csv/67/)
> 
> Testray CSV Link: [testray-results-2574058624.csv](https://test-1-10.liferay.com/userContent/jobs/generate-testray-csv/builds/67/testray-results-2574058624.csv)

No unique failure in https://github.com/liferay-core-infra/liferay-portal/pull/7090#issuecomment-2141494686

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:8913611

**Comment by dantewang** [comment]
ci:report:8913611

**Comment by dantewang** [comment]
ci:report:8905931

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7136

**Pull request closed without merging**
