### PR TITLE
LPS-150808 Move petra-http-invoker to Inline in site-initializer-testray

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,

Main Task: [LPS-147928 Remove petra jar from modules/apps](https://issues.liferay.com/browse/LPS-147928)
Sub Task: [LPS-150808 Move petra-http-invoker to Inline in site-initializer-testray](https://issues.liferay.com/browse/LPS-150808)

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
@bronsonsoda @kyle-miho
Hi Bronson, Kyle,
Could you please help me scan this test result?
Thank you!

**Comment by bronsonsoda** [comment]
@julschong no regressions found

@kyle-miho @vicnate5

**Comment by julschong** [comment]
@tinatian
Hi Tina, could you please help me review this PR?
Thank you!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115695

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
