### PR TITLE
LPS-144726 remove the usage of curvesapi

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-144726.
Seems like curvesapi is not necessary dependency when we compile poi. Therefore I am going to clean them away.
Thanks for checking.

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:reports

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by jeffwu0724** [comment]
rebased and fixed the code conflict in versions.html by auto generate, the old test result should be good enough

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128154

**Comment by jeffwu0724** [comment]
ci:reopen

**Pull request closed without merging**
