### PR TITLE
LPD-30974 Fix CounterLocalServiceProcessTest

### PR DESCRIPTION
**Pull request by dantewang**
Hi @tinatian For the first commit, please see the message. Due to that, I consider it as a production code bug caught by the test, not a test bug, so I modified the production code. Let me know if you think it's better to fix on the test side.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
cc @achaparro

**Comment by achaparro** [comment]
Hey @dantewang,

I have a question regarding this, how have you detected this? Are you running the test with db partition enabled in any suite or internal tests? I would like to take that into account since, we are going to ask teams to fix the test issues with DB Partitioning enabled soon.

Thanks.

**Comment by dantewang** [comment]
@achaparro It's from the CI failure history of integration tests owned by Core Infra. We thought it was flaky at first, but when I reviewed the Jenkins console of the failed runs and the stack trace, I noticed that all the failed runs were with DB partition enabled.

**Comment by achaparro** [comment]
@dantewang it is fine since we need this fix sooner or later but the integration tests should not run with db partition enabled in the CI yet. Maybe the failures are related to the executions we launched to verify other test failures.

**Comment by dantewang** [comment]
ci:report:35103056

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:upstream-dxp

**Comment by dantewang** [comment]
@achaparro Looking at the testray history, all the failures are in the batches like `modules-integration-db-partition-mysql57-jdk8` and these batches are included in the `upstream-dxp` which is executed routinely. We saw the failures from there.

Does the changes in this PR look good to you?

**Comment by dantewang** [comment]
ci:test:db-partition

**Comment by dantewang** [comment]
ci:report:36313140

**Comment by dantewang** [comment]
@achaparro I sent this PR to database-infra's repo since it involves changes to DB partition code.

cc @brunofalc @tinatian

**Pull request closed without merging**
