### PR TITLE
[Remove Stream/Optional usage] LPS-170586 Remove stream usages in DDMDataProviderPortletUtil

### PR DESCRIPTION
**Pull request by JanisZhang**
Remove leftover stream usage in the module `dynamic-data-mapping-data-provider-web`

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by liuxingye** [comment]
Reviewing test suits ...

**Comment by lilylcl** [comment]
The relevant and forms failures are not related to current PR, could you help to add QA Passed label? Thanks!
cc @dantewang

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
