### PR TITLE
[Components with more than 1 service] LPS-177193, LPS-177207

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132071

**Pull request closed without merging**
