### PR TITLE
[Remove Blocking Usages] LPS-201284 Removing Unnecessary Usages of ServiceProxyFactory.newServiceTrackedInstance with blocking set to true in class ImageLocalServiceImpl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(11/13 9:20)

**Comment by W2jx** [comment]
no conflicts(11/14 15:49)

**Comment by W2jx** [comment]
no conflicts(11/15 10:19)

**Comment by W2jx** [comment]
no conflicts(11/17 8:18)

**Comment by W2jx** [comment]
no conflicts(11/20 13:57)

**Comment by W2jx** [comment]
no conflicts(11/21 15:06)

**Comment by W2jx** [comment]
no conflicts(11/22 15:05)

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/144340

cc @shuyangzhou

**Pull request closed without merging**
