### PR TITLE
LPS-145906

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian, @shuyangzhou ,

I have removed unused properties "Rss.publish.to.live.by.default", and updated to propskeys.java, propsvalues.java and verifyproperties.java.
It was added as "RSS_PUBLISH_TO_LIVE_BY_DEFAULT" in commit 2ab2852ca6f67753b23774adfac6b7644b42a5f7, see LPS-38573, and it was used in "RSSPortletDataHandler.java".
It is deleted in commit 32bbf208d72a870375e5727b02626900ec6844cd, see LPS-LPS-46984.
Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.
@jeffwu0724 Code looks good to me, wait for QA to scan test results.

Tina.

**Comment by vicnate5** [comment]
@Hijky Can you check the results here?

**Comment by Hijky** [comment]
None of the failed cases are relevant

**Pull request closed without merging**
