### PR TITLE
LPS-143632 Remove LanguageUtil from site module

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by julschong** [comment]
@tinatian Hi Tina,
Could you please help me review this pull?
Thank you!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
@shuyangzhou Hi Shouyang,

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121407

**Pull request closed without merging**
