### PR TITLE
[Non-blocking ServiceProxyFactory] [Spring beans] LPS-200639 Move PasswordPolicyToolkit to module

### PR DESCRIPTION
**Pull request by JanisZhang**
Move `PasswordPolicyToolkit` to module and make it a component. Thanks.
https://liferay.atlassian.net/browse/LPS-200639

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
@JanisZhang I just notice that you removed a method from `PwdToolkitUtil` but there's no major version bump, as the package is not exported so doesn't have packageinfo. However there's a component using this util, which is weird. Could you double check it?

**Comment by JanisZhang** [comment]
> @JanisZhang I just notice that you removed a method from `PwdToolkitUtil` but there's no major version bump, as the package is not exported so doesn't have packageinfo. However there's a component using this util, which is weird. Could you double check it?

Hi @dantewang, I'm a bit confused. Would you explain more about why this seems weird? thanks!

**Comment by dantewang** [comment]
@JanisZhang 
- A package must be exported from one module (usually as defined in bnd.bnd) for other modules to import and use.
- An exported package should have a version.
- A breaking change (e.g. API method removal) should cause a major version bump of the exported package.

Here,
- The package `PwdToolkitUtil` is not exported, as there's no entry in bnd and no version file;
- But it's used in module.

This is weird. I wonder whether the user in module can actually work...

**Comment by JanisZhang** [comment]
Hi @dantewang, 

Here are some findings. I added the below code in that component.
```
Class<?> clazz = Class.forName("com.liferay.portal.security.pwd.PwdToolkitUtil");
```
Initially, it retrieves the current class loader (`EquinoxClassLoader`) and then proceeds to BundleLoader. Within BundleLoader, it executes `findSource()` followed by `org.eclipse.osgi.internal.loader.BundleLoader#getImportedSources` to get the source.

However, I can't tell the definition of `ExportPackageSource`. I believe Shuyang has insights.

FYI.
image (4)

**Comment by dantewang** [comment]
@JanisZhang OK, thanks!

**Comment by dantewang** [comment]
ci:test:stable

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
