### PR TITLE
[Rename Classes]Lps 166981

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-166981

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@slnn semver error:

```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/commerce/commerce-product-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.commerce.product.type                  MAJOR      2.1.0      2.1.0      3.0.0      VERSION INCREASE REQUIRED
```

other regressions:

```
 [exec] com.liferay.content.dashboard.web.internal.portlet.action.GetContentDashboardItemInfoMVCResourceCommandTest > testServeResourceWithoutSharingButtonAction FAILED
     [exec]     java.lang.NoSuchFieldException: No field on null with name _contentDashboardItemFactoryTracker
     [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.getField(ReflectionTestUtil.java:135)
     [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.setFieldValue(ReflectionTestUtil.java:346)
     [exec]         at com.liferay.content.dashboard.web.internal.portlet.action.GetContentDashboardItemInfoMVCResourceCommandTest._initGetContentDashboardItemInfoMVCResourceCommand(GetContentDashboardItemInfoMVCResourceCommandTest.java:590)
     [exec]         at com.liferay.content.dashboard.web.internal.portlet.action.GetContentDashboardItemInfoMVCResourceCommandTest.testServeResourceWithoutSharingButtonAction(GetContentDashboardItemInfoMVCResourceCommandTest.java:402)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-38/test-portal-acceptance-pullrequest(master)/4586/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
[exec] com.liferay.content.dashboard.web.internal.item.filter.test.ContentDashboardItemFilterProviderRegistryTest > testGetContentDashboardItemFilterProviders FAILED
     [exec]     java.lang.NullPointerException: A null service reference is not allowed.
     [exec]     	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:622)
     [exec]     	at com.liferay.content.dashboard.web.internal.item.filter.test.ContentDashboardItemFilterProviderRegistryTest.setUp(ContentDashboardItemFilterProviderRegistryTest.java:58)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-38/test-portal-acceptance-pullrequest(master)/4586/modules-integration-mysql57-jdk8/0/13/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
Thank @catarineaguiar for catching this!

I have updated and forced push to this pull with a fix.

**Comment by slnn** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@slnn Please rearrange the commits. It turns out that the changes are not clear by mixing renaming and applying in the same commit, so let's do this:

- Rename X and XImpl
- Apply
- Rename Y and YImpl
- Apply
- ......
- One semantic versioning commit for all of your PR

cc @JanisZhang @W2jx Please resend all of your renaming PRs if needed. Thank you!

**Comment by slnn** [comment]
Resend in https://github.com/liferay-core-infra/liferay-portal/pull/2312

**Pull request closed without merging**
