### PR TITLE
[Reference cleanup]LPS-162290

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to convert method references to field references in `export-import-service`| Part 2.
Thanks!

https://issues.liferay.com/browse/LPS-162290

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @zhangyan0701, Could you please help to scan the test result? Thank you.

**Review by dantewang — APPROVED** [review]

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found

**Comment by dantewang** [comment]
ci:forward

**Comment by dantewang** [comment]
@tinatian @shuyangzhou Tiggered forward as it contains only simple replacements, and passed CI.

**Pull request closed without merging**
