### PR TITLE
[TS] LPS-155431

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr fixed the test [error](https://github.com/liferay-core-infra/liferay-portal/pull/980#issuecomment-1160327016). I only added the code **themeDisplay.setRealUser(TestPropsValues.getUser())** back(in the [commit](https://github.com/liferay-core-infra/liferay-portal/commit/ea765ac35608bca5ea2ed70e250f491f09e99f32)). The test can be passed in my local.

cc [jorgediaz-lr](https://github.com/jorgediaz-lr)

### CODE REVIEW

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by jorgediaz-lr** [comment]
Hi @yuhai @dantewang 

Do you have any update about this PR?

According to @zhangyan0701 there were no regressions, so can we forward it?

Thank you

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@tinatian This PR has commits of the fix properly arranged as suggested in previous PRs. It also adds an integration test for cover the logic. I think it can move on.

Thanks

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

We have to send a hotfix of this issue to a 7.2.x customer and I would prefer to have this merged into master before sending it.

Please let me know if the PR can be forwarded or additional changes are necessary.

Thank you

Regards,
Jorge

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
