### PR TITLE
LPS-96118 Proxy replacement, portal-kernel

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian https://issues.liferay.com/browse/LPS-96118

After reviewing the usages we found more to replace, so we'll send more pull requests. This one is for usages we decide to replace in portal-kernel.

We skip 
1. wrappers that can be replaced by ASM;
2. proxies obviously created only once (in static final field or component activate method); 
3. individual unit/integration tests;
4. proxies created with different interfaces each time.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
