### PR TITLE
[Components with more than 1 service] LPS-178124 Refactor DDMFormFieldValueAccessor components from Dynamic Data Mapping module

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-178124](https://issues.liferay.com/browse/LPS-178124)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:data-engine

**Comment by RenanUmV** [comment]
ci:test:forms

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/135563

cc @shuyangzhou @tinatian

**Pull request closed without merging**
