### PR TITLE
[CLDR] LPD-31593 Switch all java.locale.provider to use CLDR

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:acceptance-functional

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
ci:test:acceptance-functional

**Comment by julschong** [comment]
ci:report:43618117

**Comment by julschong** [comment]
https://testray.liferay.com/#/project/34754/routines/34756/build/43618117/case-result/43658112/history this is related, need to fix

**Comment by julschong** [comment]
ci:test:acceptance-functional

**Comment by julschong** [comment]
ci:report:44116292

**Comment by julschong** [comment]
unique regressions are not related

**Comment by julschong** [comment]
ci:test:core-functional

**Comment by julschong** [comment]
ci:report:44706013

**Comment by julschong** [comment]
ci:test:clustering

**Comment by julschong** [comment]
ci:test:core-functional

**Comment by julschong** [comment]
core-functional test failed to import on Testray, rerunning

**Comment by julschong** [comment]
ci:report:44901456

**Comment by julschong** [comment]
[Locale#LanguageWithVariantDoesNotCauseInfiniteRedirectLoop](https://testray.liferay.com/#/project/34754/routines/34756/build/44901456/case-result/44909092) passed. ready for review

@tinatian

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/152678

**Pull request closed without merging**
