### PR TITLE
[Upgrade Mockito Framework] LPS-153088

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,
This PR updates Mockito to major version 4 and removes the dependency on PowerMock. Thanks! 
[LPS-153088](https://issues.liferay.com/browse/LPS-153088)

### CODE REVIEW

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by JanisZhang** [comment]
Code conflicts. rebased.

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:acceptance

**Comment by JanisZhang** [comment]
code conflicts, rebased.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:acceptance

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
Code conflicts, rebased.

**Comment by JanisZhang** [comment]
code conflicts, rebased.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:acceptance

**Comment by tinatian** [comment]
@JanisZhang Code conflicts, please rebase. 

Thanks.
Tina

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:acceptance

**Comment by JanisZhang** [comment]
Hi @catarineaguiar, Could you please help scan the test result?  Thanks!

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
@JanisZhang please rebase, thanks!

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:acceptance

**Comment by JanisZhang** [comment]
Rebased.

Hi @catarineaguiar, Could you please help scan the test results again? thanks!

cc @tinatian @shuyangzhou

**Comment by JanisZhang** [comment]
test failed. will resend

**Pull request closed without merging**
