### PR TITLE
Lps 153305 move verifyProperties and some properties that moduleFramework need when init

### PR DESCRIPTION
**Pull request by W2jx**
@dantewang the logic that we moved verifyProperties may affect the database， I'll check it 。

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:acceptance

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@W2jx I made some changes on your first push and sent back to you: https://github.com/W2jx/liferay-portal/pull/6

**Comment by dantewang** [comment]
ci:close

**Pull request closed without merging**
