### PR TITLE
[OrderByComparator] LPD-28067 Apply Singleton in module commerce-price-list-api

### PR DESCRIPTION
**Pull request by Valmir-unicap**
- Ticket: https://liferay.atlassian.net/browse/LPD-28067
- Correction of: https://github.com/liferay-core-infra/liferay-portal/pull/7210

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
locally SF PASSED

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:report:30667052

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
