### PR TITLE
[Method References 2] LPS-170883 Convert method reference to ServiceTrackerList in module portal-security-audit-router

### PR DESCRIPTION
**Pull request by W2jx**
Hi @dantewang , I have modified the code we talked about.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3200

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:security

**Comment by W2jx** [comment]
no conflicts(2/1 10:05)

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(2/2 8:34)

**Comment by tinatian** [comment]
Hi @W2jx I do not understand https://github.com/liferay-core-infra/liferay-portal/pull/3228/commits/de0da6fdd0327c782054d7a95bef7d578b178b51. Both impl are doing the same thing, then why you have the API method in the first place?

Tina

**Comment by dantewang** [comment]
@W2jx The plan is to check with the product team in charge of Audit first. If they do want to keep these extension point, let's extract the method to a common place, e.g. a default method in the interface.

**Pull request closed without merging**
