### PR TITLE
LPD-1901 Dyanmically pass the Alias javaType based on the output formula object field setting

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
## Related tickets

- https://liferay.atlassian.net/browse/LPD-1901

## Motivation

A decimal number is expected in the following use case but it always set the output type as the expression1 [here](https://github.com/liferay/liferay-portal/blob/bb9d7a1d3cecde95457c46f7c75c2d7d4090ecf6/portal-kernel/src/com/liferay/portal/kernel/service/persistence/impl/BasePersistenceImpl.java#L1148),

**Given:** a division DSLFunction expression like this `expression1 / expression2` where the expression1 is a non-decimal column.

**When:** this expression is evaluated as an alias with the following operands 3 and 2 (e.g.: `3 / 2 as foo`)

**Then:** the result is 1 instead of 1.5 that is the expected due to [this](https://github.com/liferay/liferay-portal/blob/bb9d7a1d3cecde95457c46f7c75c2d7d4090ecf6/portal-kernel/src/com/liferay/portal/kernel/service/persistence/impl/BasePersistenceImpl.java#L1148)

## Proposed Solution

Dynamically pass the Alias javaType based on the business rule needs (e.g.: formula output object field setting)

### CODE REVIEW

**Comment by tinatian** [comment]
@MarinhoFeliphe Could you please add a test in modules/util/portal-tools-service-builder-test-test/src/testIntegration/java/com/liferay/portal/tools/service/builder/test/service/persistence/impl/test/DSLQueryEntryPersistenceImplTest.java to expose the issue? Core infra can take it over from there.

Thanks.
Tina.

**Comment by MarinhoFeliphe** [comment]
Hi @tinatian the test you are looking for is [here](https://github.com/liferay-core-infra/liferay-portal/pull/7287/commits/ecfd98e7256c4fc00bb71b14f8254af180cb1997).

Best Regards,
Feliphe Marinho

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by tinatian** [comment]
@MarinhoFeliphe 

> the test you are looking for is here https://github.com/liferay-core-infra/liferay-portal/commit/ecfd98e7256c4fc00bb71b14f8254af180cb1997.

No, this is not the test I am looking for, in the test you are using the new API you added. I want a test that does not use anything you added and anything from object.

**Comment by MarinhoFeliphe** [comment]
got it, I'll provide.

Thanks!

**Pull request closed without merging**
