### PR TITLE
[Method References 2] LPS-167598 Convert method reference to ServiceTrackerMap in class NotificationSenderFactory

### PR DESCRIPTION
**Pull request by W2jx**
Interface NotificationSender and its Tracker are kept because the calendar team thinks there are clients that will implement it. see https://issues.liferay.com/browse/PTR-3524

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/2550

### CODE REVIEW

**Comment by W2jx** [comment]
ci:help

**Comment by W2jx** [comment]
ci:test:calendar

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by zhangyan0701** [comment]
Semantic versioning issue:
```
     [exec] > Task :apps:calendar:calendar-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.calendar.notification                  MAJOR      1.3.0      1.3.0      2.0.0      VERSION INCREASE REQUIRED
     [exec] 	>   interface  com.liferay.calendar.notification.NotificationSender
     [exec] 		+   method     getNotificationType()
     [exec] 			+   access     abstract
     [exec] 			+   return     com.liferay.calendar.notification.NotificationType
     [exec] [Baseline Warning] Bundle Version Change Recommended: 12.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.calendar.api-11.0.1.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.calendar.api/11.0.0/df05f7a0ea51a265c09a932f667a961a5466a014/com.liferay.calendar.api-11.0.0.jar
```
Full console: https://testray.liferay.com/reports/production/logs/2023-01/test-1-31/test-portal-acceptance-pullrequest(master)/6646/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by W2jx** [comment]
I only rebase the code and baseline，no need to retrigger the test.

**Comment by dantewang** [comment]
@W2jx The result looks good, please re-order your commits like https://github.com/liferay-core-infra/liferay-portal/pull/3040 and resend.

If you have other pulls like this, please also re-order them and resend.

**Pull request closed without merging**
