### PR TITLE
LPS-190918 Merge WebCachePool interface and impl into Util in kernel

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
updated semver

**Comment by tinatian** [comment]
@julschong Please remember to remove QA Passed flag to trigger the scan of new test results.

Thanks.
Tina

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139305

**Pull request closed without merging**
