### PR TITLE
[Method References 2] LPS-170783 Convert method reference to ServiceTracker in class DispatchTaskExecutorRegistryImpl(module dispatch-service)

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:data-integration

**Comment by W2jx** [comment]
no conflicts(12/12 9:49)

**Comment by W2jx** [comment]
no conflicts(12/13 9:53)

**Comment by W2jx** [comment]
no conflicts(2022/12/14 9:32)

**Comment by W2jx** [comment]
no conflicts(12/15 9:21)

**Comment by W2jx** [comment]
no conflicts(2022/12/16 8:57)

**Comment by W2jx** [comment]
no conflicts(12/19 9:52)

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2790

**Pull request closed without merging**
