### PR TITLE
LPD-25898

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team,

**Ticket:** https://liferay.atlassian.net/browse/LPD-25898

As discussed, I have included a functional test to expose this issue: `PortalLogging#HibernateSQLQueriesViewableWithDebugLogLevel`

I also ran `ci:test:app-servers` in my repo to observe the test results:
- PR (with test only): https://github.com/ericyanLr/liferay-portal/pull/316
- PR (with test + fix): https://github.com/ericyanLr/liferay-portal/pull/317

From the test results, we can see the issue is **reproduced on JBoss 7.4, Wildfly 23.0 and Wildfly 26.1**. 

And with our fix, the issue is no longer reproduced.

**Note:** We are adding this functional test as a Poshi test, since CI does not support running playwright tests for testing different application servers (`ci:test:app-servers`).

Please let me know if you have any questions.
Thanks!

---

/cc @vicnate5

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:2571292196

**Comment by ericyanLr** [comment]
**ci:report - analysis**
There are no unique failures. 

Also, test results in ticket description for: `ci:test:app-servers` have positive results.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/151002

**Pull request closed without merging**
