### PR TITLE
[Login Performance]LPS-150112

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:acceptance

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by slnn** [comment]
Rebase and solve the conflict in https://github.com/liferay-core-infra/liferay-portal/pull/598

**Pull request closed without merging**
