### PR TITLE
[Remove Stream/Optional usage] LPS-174909 Remove usages of Stream for module: portal-workflow-kaleo-definition-impl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:help

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(2/8 9:03)

**Comment by W2jx** [comment]
no conflicts(2/9 10:25)

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(2/13 13:11)

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3522

**Pull request closed without merging**
