### PR TITLE
[System Properties] LPS-165265 Move some properties that moduleFramework needs during init | part 2

### PR DESCRIPTION
**Pull request by W2jx**
Hi @dantewang , I have put LIFERAY_HOME constant in SystemProperties directly.

Detail: https://github.com/liferay-core-infra/liferay-portal/pull/2474

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
Force-Push is just to increase the use of the petra.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
@W2jx possible regression:

```
  [exec] 
     [exec] com.liferay.portal.lpkg.deployer.controller.LPKGControllerTest > testLPKGControllerDeploy FAILED
     [exec]     java.nio.file.NoSuchFileException: /opt/dev/projects/github/liferay-portal/modules/apps/static/portal-lpkg-deployer/portal-lpkg-deployer-test/liferay/osgi/marketplace/Liferay Controller Test.lpkg
     [exec]         at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
     [exec]         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
```

```
 [exec] com.liferay.portal.lpkg.deployer.controller.test.LPKGControllerVerifyTest > testLPKGController FAILED
     [exec]     java.lang.AssertionError: No JAR bundle found
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
     [exec]     	at org.junit.Assert.assertNotNull(Assert.java:713)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-34/test-portal-acceptance-pullrequest(master)/3225/lpkg-controller-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
