### PR TITLE
LPS-146037 Fix race condition when adding companies concurrently

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,
This is a bug found when generating sample data for multiple companies. 

I did not add test as it is going to take a lot of effort to show it on test and it is very obvious that the current logic is not thread safe.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@tinatian Thanks! `addIfAbsent` is a nice one to know.

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@kyle-miho can you check this one?

**Comment by tinatian** [comment]
@vicnate5 Please help me scan this pull.

Tina.

**Comment by vicnate5** [comment]
@tinatian No regressions found. Sorry for the delay, I forgot Kyle was on PTO on Friday.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
