### PR TITLE
[Remove unused @Reference var] LPS-164886

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove the unused @reference variable in the module `object-web`. Thanks!

https://issues.liferay.com/browse/LPS-164886

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@Kvale1733 Triggered relevant twice to reduce chances of uncaught random failure.

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@dantewang No regressions found in the new relevant run.

**Comment by dantewang** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/124486

@shuyangzhou @tinatian

**Pull request closed without merging**
