### PR TITLE
[TS] LPS-202860

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the previous pr is https://github.com/liferay-core-infra/liferay-portal/pull/6287.

cc @marianoalvarosaiz

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Hi @yuhai ,
 do we have any updates?
Kind regards.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@marianoalvarosaiz @yuhai LGTM, requested review from Tina.

**Comment by dantewang** [comment]
@marianoalvarosaiz If this one is urgent (customer waiting) please ping Tina on Slack.

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
