### PR TITLE
[Remove Stream usage: CSSBuilder]Lps 176219

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-176219

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Rerun ci tests since forced push

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
