### PR TITLE
[Method References 2] LPS-176118 Convert method references to serviceTracker in class ThemeContributorTopHeadDynamicInclude

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:frontend

**Comment by W2jx** [comment]
no conflicts(2/21 13:50)

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(2/22 8:22)

**Review by dantewang — APPROVED** [review]

**Comment by W2jx** [comment]
no conflicts(2/27 8:30)

**Comment by W2jx** [comment]
no conflicts(2/28 9:42)

**Comment by W2jx** [comment]
no conflicts(3/1 10:45)

**Comment by tinatian** [comment]
@W2jx @dantewang I need a talk with you guys about this pull, please slack me when you are available.

Basically, I want the calculation to be lazy, it will help startup performance.

**Pull request closed without merging**
