### PR TITLE
[Round 3 Method Reference]Lps 180691 2

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-180691

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:search-solr

**Comment by slnn** [comment]
ci:test:search

**Comment by slnn** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
1. The dynamic reference is properly listened;
2. `@Modified` usage.

**Comment by slnn** [comment]
Please see https://github.com/liferay-core-infra/liferay-portal/pull/4538

**Pull request closed without merging**
