### PR TITLE
LPS-159031 Fix R/W data source | 1-19

### PR DESCRIPTION
**Pull request by dantewang**
Tested here https://github.com/dantewang/liferay-portal/pull/2280, this pull just reordered commit.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3223

**Pull request closed without merging**
