### PR TITLE
[Remove Stream/Optional usage] LPS-176389 dynamic-data-mapping-form-builder

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-176389

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
@JanisZhang No regressions.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:data-engine

**Pull request closed without merging**
