### PR TITLE
LPS-169398

### PR DESCRIPTION
**Pull request by leilanyaragao**
**Jira Issue:** https://liferay.atlassian.net/browse/LPS-169398
**Context:**
In one of objects upgrades from old versions of the portal to master we needed populate potlets and to get them we used the `portletLocalService.getPortletById` which before the correction returned null.
Investigating, we discovered an error in the `loadGetPortletsMap` method of the `PortletLocalServiceImpl` class, which when loading the portlets through `portletPersistence.findByCompanyId` was not saving or returning to the `portletsMap`, so the `portletMap` returned null.
In this correction, when loading the potlets through the `Persistence.findBy CompanyId`, they will be added to the `portletMap` and at the end the method will return them.

@marcelabc

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@leilanyaragao Regression found. All upgrades now fail at some document.library module.

Steps to reproduce
1)Import the following7.4.13 database dump: https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.4.13/data-archive/data-archive-portal-mysql.zip
2) Run the upgrade tool

Expected Results: Upgrade completes without issue
Actual Results: The upgrade fails due to 
```
[java] 2023-07-28 20:06:19.091 INFO  [main][UpgradeProcess:136] Failed upgrade process com.liferay.document.library.google.docs.internal.upgrade.v1_0_0.PortletPreferencesUpgradeProcess in 1707 ms
     [java] 2023-07-28 20:06:19.096 ERROR [main][UpgradeStepRegistratorTracker:178] Failed upgrade process for module com.liferay.document.library.google.docs
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: java.lang.NullPointerException
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:127) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor._executeUpgradeInfos(UpgradeExecutor.java:189) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.executeUpgradeInfos(UpgradeExecutor.java:135) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.execute(UpgradeExecutor.java:107) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.registry.UpgradeStepRegistratorTracker$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeStepRegistratorTracker.java:175) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.registry.UpgradeStepRegistratorTracker$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeStepRegistrator
```
[Log](https://testray.liferay.com/reports/production/logs/2023-07/test-1-37/test-portal-acceptance-pullrequest(master)/13468/functional-upgrade-tomcat90-mysql57-jdk8/0/4/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
@leilanyaragao Could you please resend with
- adding a test to expose the issue, and
- fixing the CI failure

Thanks!

**Pull request closed without merging**
