### PR TITLE
Lps 193711

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by Kvale1733** [comment]
No regressions found.

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139572

**Comment by shuyangzhou** [comment]
ci:stop

**Comment by Kvale1733** [comment]
@shuyangzhou So ci:forward only forwards if both relevant and stable pass. Otherwise it reruns both. ci:forward:force only forwards if relevant finished running and stable passed. 

But in this case stable didn't pass so running that would rerun just stable and if it passed, then it would forward.

Otherwise sometimes we just resort to manual forward it if qa passed and review passed to forward it quicker.

**Comment by Kvale1733** [comment]
There's no command that just forwards without any validation.

**Comment by Kvale1733** [comment]
ci:stop

**Pull request closed without merging**
