### PR TITLE
[Remove immediate=true usage core-infrastructure-3]Lps 169260

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-169260

### CODE REVIEW

**Comment by slnn** [comment]
ci:test

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@slnn Regressions found

1) com.liferay.portal.instances.internal.configuration.test.PortalInstancesConfigurationFactoryTest
```
 [exec] com.liferay.portal.instances.internal.configuration.test.PortalInstancesConfigurationFactoryTest > test FAILED
     [exec]     java.lang.AssertionError
     [exec]     	at org.junit.Assert.fail(Assert.java:87)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
```
[Log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-25/test-portal-acceptance-pullrequest(master)/5717/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

2) com.liferay.json.storage.upgrade.test.JSONStorageUpgradeStepFactoryTest
```
[beanshell] Waiting for service com.liferay.json.storage.upgrade.JSONStorageUpgradeStepFactory  for field com.liferay.json.storage.upgrade.test.JSONStorageUpgradeStepFactoryTest._jsonStorageUpgradeStepFactory
[beanshell] Waiting for service com.liferay.json.storage.upgrade.JSONStorageUpgradeStepFactory  for field com.liferay.json.storage.upgrade.test.JSONStorageUpgradeStepFactoryTest._jsonStorageUpgradeStepFactory
[beanshell] Waiting for service com.liferay.json.storage.upgrade.JSONStorageUpgradeStepFactory  for field com.liferay.json.storage.upgrade.test.JSONStorageUpgradeStepFactoryTest._jsonStorageUpgradeStepFactory
[beanshell] Waiting for service com.liferay.json.storage.upgrade.JSONStorageUpgradeStepFactory  for field com.liferay.json.storage.upgrade.test.JSONStorageUpgradeStepFactoryTest._jsonStorageUpgradeStepFactory
[beanshell] 2022-12-13 15:00:58.679 INFO  [Arquillian-Connector-Thread][BundleStartStopLogger:80] STOPPED com.liferay.json.storage.test_1.0.0 [1510]
     [exec] 
     [exec] com.liferay.json.storage.upgrade.test.JSONStorageUpgradeStepFactoryTest > classMethod STARTED
     [exec] 
     [exec] com.liferay.json.storage.upgrade.test.JSONStorageUpgradeStepFactoryTest > classMethod FAILED
     [exec]     java.lang.IllegalStateException: Timed out while waiting for service com.liferay.json.storage.upgrade.JSONStorageUpgradeStepFactory 
     [exec]     	at com.liferay.portal.test.rule.InjectTestBag._getServiceReference(InjectTestBag.java:199)
     [exec]     	at com.liferay.portal.test.rule.InjectTestBag.injectFields(InjectTestBag.java:78)
     [exec]     	at com.liferay.portal.test.rule.InjectTestRule.beforeClass(InjectTestRule.java:49)
```
[Log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-25/test-portal-acceptance-pullrequest(master)/5718/modules-integration-mysql57-jdk8/2/6/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
ci:test

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
Below failures seem related:
1. Upgrade tests failed with error:
```
[java] 2022-12-14 05:49:44.094 ERROR [main][UpgradeStepRegistratorTracker:185] Failed upgrade process for module com.liferay.knowledge.base.web
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: java.lang.NullPointerException
```
Full log:
https://testray.liferay.com/reports/production/logs/2022-12/test-1-32/test-portal-acceptance-pullrequest(master)/7384/functional-upgrade-tomcat90-mysql57-jdk8/0/11/jenkins-console.txt.gz?authuser=0

2. `Command not found` error occurs w
after0
hen execute `system:check` in Gogo Shell:

3. Some integration tests failed due to below error in portal startup:
```
[beanshell] 2022-12-14 05:51:05.230 ERROR [Start Level: Equinox Container: 152950b1-e519-4524-b138-8d66cecab082][DataGuardConnector:56] Encountered a problem while using 127.0.0.1:42763. Shutting down now.
[beanshell] java.net.BindException: Address already in use (Bind failed)
```
Full console log:
https://testray.liferay.com/reports/production/logs/2022-12/test-1-32/test-portal-acceptance-pullrequest(master)/7384/modules-integration-mysql57-jdk8/4/6/jenkins-console.txt.gz?authuser=0

**Comment by dantewang** [comment]
@yuhai Lily will be off for the next days, could you take this over? Thanks!

**Comment by yuhai** [comment]
> @yuhai Lily will be off for the next days, could you take this over? Thanks!

@dantewang，yes.

**Pull request closed without merging**
