### PR TITLE
[TS] LPD-23711

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__
<https://liferay.atlassian.net/browse/LPD-23711>

__Previous PR:__
<https://github.com/liferay-core-infra/liferay-portal/pull/6919>

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
@tinatian, I believe I covered everything I can with the integration tests. However, there is one particular situation that I am somewhat worried about. Specifically, Service Builder generates different code for the `filterFindBy` methods when we are in Liferay 7.2 or lower. This is one example:

- <https://github.com/liferay/liferay-portal/blob/7.4.3.119-ga119/modules/util/portal-tools-service-builder/src/main/resources/com/liferay/portal/tools/service/builder/dependencies/persistence_impl_finder_find.ftl#L707-L730>
- <https://github.com/liferay/liferay-portal/blob/7.4.3.119-ga119/modules/util/portal-tools-service-builder/src/main/java/com/liferay/portal/tools/service/builder/Entity.java#L1140-L1148>

I checked the code and I am pretty sure I have not broken anything for this case. I can also manually test to make sure my changes will be okay for 7.2 and lower. But it would be great if we can write tests for this case.

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:report:2565711178

**Comment by kevhlee** [comment]
I have checked the errors in this PR. I believe they are unrelated. Going to rebase the commits and re-run tests.

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:report:2566299069

**Comment by kevhlee** [comment]
No unique failures detected.

**Comment by kevhlee** [comment]
Hi @tinatian, any chance you will be able to review this PR soon?

**Comment by tinatian** [comment]
@kevhlee  Closed, please see my message on slack.

**Pull request closed without merging**
