### PR TITLE
[Remove Stream/Optional  usages dxp module: analytics return value part]Lps 171993

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-171993

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:tango-acceptance

**Comment by catarineaguiar** [comment]
ci:test:analytics-cloud-acceptance

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
