### PR TITLE
Lpd 20566 3 19 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:report:2552346589

**Comment by tinatian** [comment]
ci:report:2552384675

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
No logic change, just squash two commits.

Tina.

**Comment by tinatian** [comment]
No regression found based on ci test report.

**Comment by shuyangzhou** [comment]
ci:forward:force

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/148406

**Pull request closed without merging**
