### PR TITLE
LPS-177178 Remove leftovers "immediate = true" from Segments Asah

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-177178

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:analytics-cloud-acceptance

**Comment by catarineaguiar** [comment]
@rafaprax regressions found:

```
     [exec] com.liferay.segments.asah.connector.internal.criteria.contributor.test.EventSegmentsCriteriaContributorTest > testGetCriteriaJSONObject FAILED
     [exec]     java.lang.NullPointerException
     [exec]     	at com.liferay.segments.asah.connector.internal.criteria.contributor.test.EventSegmentsCriteriaContributorTest.testGetCriteriaJSONObject(EventSegmentsCriteriaContributorTest.java:90)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
```
```
     [exec] com.liferay.segments.experiment.web.internal.portlet.action.test.GetDataMVCResourceCommandTest > testGetProps STARTED
[beanshell] 2023-03-13 14:50:25.019 ERROR [com.liferay.segments.experiment.test-executor-thread][PortletURLImpl:976] null
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.portal.util.PortalImpl.getLayoutFriendlyURL(PortalImpl.java:3075) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.util.PortalImpl.getLayoutFriendlyURL(PortalImpl.java:2991) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.util.PortalUtil.getLayoutFriendlyURL(PortalUtil.java:1038) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portlet.internal.PortletURLImpl.generateToString(PortletURLImpl.java:965) [portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.PortletURLImpl.toString(PortletURLImpl.java:881) [portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.portlet.url.builder.PortletURLBuilder$PortletURLStep.buildString(PortletURLBuilder.java:226) [portal-kernel.jar:?]
[beanshell] 	at com.liferay.segments.experiment.web.internal.portlet.action.GetDataMVCResourceCommand._getSegmentsExperimentActionURL(GetDataMVCResourceCommand.java:433) [bundleFile:?]
[beanshell] 	at com.liferay.segments.experiment.web.internal.portlet.action.GetDataMVCResourceCommand._getContextJSONObject(GetDataMVCResourceCommand.java:162) [bundleFile:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-03/test-1-40/test-portal-acceptance-pullrequest(master)/596/modules-integration-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:analytics-cloud-acceptance

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Upgrade failed with error:
```
     [java] 2023-03-21 04:37:07.202 ERROR [Start Level: Equinox Container: 2cc5d1ee-1b3b-4a39-b2a4-154c52d94d75][ModulePortalProfile:56] bundle com.liferay.segments.asah.connector:3.0.39 (761)[com.liferay.segments.asah.connector.internal.portal.profile.ModulePortalProfile(8705)] : The activate method has thrown an exception
     [java] java.lang.ExceptionInInitializerError: null
```
Example failed test:
[LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive7413](https://testray.liferay.com/home/-/testray/case_results/2238113958)
Full console log:
https://testray.liferay.com/reports/production/logs/2023-03/test-1-25/test-portal-acceptance-pullrequest(master)/175/functional-upgrade-tomcat90-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:analytics-cloud-acceptance

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by rafaprax** [comment]
Hi all, as you can see [here](https://github.com/liferay-core-infra/liferay-portal/compare/9dc94925c6bb81b458354baf9651238c3b5939d5..bd329358ec59fc00930c6473b599f77d0d081b62), I just merged two commits and inlined the `bundleContext` variable in the test class. So, the previous test results are still valid. Thx

**Comment by zhangyan0701** [comment]
ci:test:analytics-cloud-acceptance

**Pull request closed without merging**
