### PR TITLE
[Remove Stream/Optional usage] Phase 1 LPS-172794 remove_stream_in_portal_tools_rest_builder

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Dante,

work on the format on ftl files. Try to follow the same format as the generated java files.
Resent from:https://github.com/liferay-core-infra/liferay-portal/pull/3988
As "rest-client cannot have any dependencies except Java 8. *-client is meant to be used outside of the portal. To keep things simple, we don't want any dependencies except for Java 8.", I changed back to use for loop instead of TransformUtil.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:headless

**Comment by dantewang** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:test:force

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
Manually sent to https://github.com/brianchandotcom/liferay-portal/pull/132363

**Pull request closed without merging**
