### PR TITLE
[Method References 2] LPS-164452 Convert method reference to ServiceTrackerMap in module dynamic-data-lists-service

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang ,I have removed the unused method.

Detail: https://github.com/liferay-core-infra/liferay-portal/pull/1893

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @catarineaguiar , Could you please help me check the test results ? Thanks!

**Comment by W2jx** [comment]
Force-Push is just to rebase the code.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@W2jx 

Semver error
```
 [exec] > Task :test:semantic-versioning-test:test
     [exec] 
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/dynamic-data-lists/dynamic-data-lists-api] STARTED
     [exec] 
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/dynamic-data-lists/dynamic-data-lists-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.dynamic.data.lists.exporter            MAJOR      2.0.0      2.0.0      3.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   interface  com.liferay.dynamic.data.lists.exporter.DDLExporterFactory
     [exec]     		-   method     getAvailableFormats()
     [exec]     			-   access     abstract
     [exec]     			-   return     java.util.Set
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 8.0.0
```
[Logs](https://testray.liferay.com/reports/production/logs/2022-10/test-1-25/test-portal-acceptance-pullrequest(master)/4895/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
