### PR TITLE
LPS-171288 Remove "immediate = true" from Remaining modules

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
ci:test:account

**Comment by RenanUmV** [comment]
ci:test:forms

**Comment by RenanUmV** [comment]
ci:test:clustering

**Comment by RenanUmV** [comment]
ci:test:analytics-cloud-acceptance

**Comment by catarineaguiar** [comment]
@RenanUmV possible regression:

```
     [exec] com.liferay.portal.verify.test.VerifyResourcePermissionsTest > testVerify FAILED
     [exec]     java.lang.Exception: Caught an unclosed exception
     [exec]     	at com.liferay.portal.verify.test.util.BaseVerifyProcessTestCase$DataSourceInvocationHandler.invoke(BaseVerifyProcessTestCase.java:120)
     [exec]     	at com.sun.proxy.$Proxy1492.getConnection(Unknown Source)
     [exec]     	at com.liferay.portal.scheduler.quartz.internal.QuartzConnectionProvider.getConnection(QuartzConnectionProvider.java:39)
     [exec]     	at org.quartz.utils.DBConnectionManager.getConnection(DBConnectionManager.java:108)
     [exec]     	at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:764)
     [exec]     	at org.quartz.impl.jdbcjobstore.JobStoreTX.getNonManagedTXConnection(JobStoreTX.java:71)
     [exec]     	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3156)
     [exec]     	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3934)
     [exec]     	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:3955)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-25/test-portal-acceptance-pullrequest(master)/5785/modules-integration-mysql57-jdk8/0/16/jenkins-console.txt.gz?authuser=0)

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@RenanUmV no regressions found.

**Comment by RenanUmV** [comment]
Hey @shuyangzhou , this one is ready to go!

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128156

**Pull request closed without merging**
