### PR TITLE
[Components with more than 1 service] LPS-192541 Refactor ImportLayoutsMVCActionCommand component

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-192541](https://liferay.atlassian.net/browse/LPS-192541)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:export-import

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:export-import

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:export-import

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
cc @tinatian

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
