### PR TITLE
[TS] LPS-180299 (Pending integration test)

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This is a PR that aims to add a requested integration test by Brian.

Could you please review it? If further clarifications are needed for this review, please, let me know.

Thanks!

https://liferay.atlassian.net/browse/LPS-180299

\cc @marianoalvarosaiz

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dacousalr I am confused about the test logic and its name `testUpdateCompanyLocalesWithLayoutSetPrototype`, how doyou update company locales by LayoutSetPrototype?

**Comment by dacousalr** [comment]
Hi @tinatian,

> Then why you need to update timezone by :

> TimeZone timeZone = company.getTimeZone();
>
> _companyLocalService.updateDisplay(company.getCompanyId(), languageId, timeZone.getID());

This update is not strictly needed. However, it is also used in test "testUpdateCompanyLocales", although, again, this existing test only makes assertions on company locales and not in company time zones.

Should I remove the update from this test as well?

> I see... please add a compare test "testUpdateCompanyLocalesWithoutLayoutSetPrototype", and extract common logic into a private method, then it would be clear that what the tests target at.

That method already exists, but it is named as just "testUpdateCompanyLocales". Should I rename it to "testUpdateCompanyLocalesWithoutLayoutSetPrototype"?

Thanks!

**Comment by tinatian** [comment]
ci:report:2496681673

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/146909

**Pull request closed without merging**
