### PR TITLE
[Remove Blocking usages]LPS-187880 portal-kernel | SettingsFactoryUtil

### PR DESCRIPTION
**Pull request by JanisZhang**
previous： https://github.com/liferay-core-infra/liferay-portal/pull/5144

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:relevant

**Pull request closed without merging**
