### PR TITLE
[BLOCKER] LPD-17572

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
@tinatian could you please take a look since it was caused by https://github.com/brianchandotcom/liferay-portal/commit/0bad7926737a3a172e8540a45980b5995cba7818

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6624

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6627

**Pull request closed without merging**
