### PR TITLE
[Remove unused reference] LPS-165881

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend.

This PR is to remove unused fields in `data-engine-rest-imp`. Thanks!

previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/2086

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:data-engine

**Comment by catarineaguiar** [comment]
ci:stop:data-engine

**Comment by catarineaguiar** [comment]
ci:test:data-engine

**Comment by catarineaguiar** [comment]
ci:test:data-engine

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
