### PR TITLE
LPD-25528 Adapt tests using hard-coded test password in Server Administration component

### PR DESCRIPTION
**Pull request by Valmir-unicap**
- Ticket: https://liferay.atlassian.net/browse/LPD-25528

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:core-functional

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:report:2568308933

**Comment by tinatian** [comment]
No unique failure according to test report

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
