### PR TITLE
[Remove immediate=true usage core-infrastructure-4 part-1]Lps 168633 part 1

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-168633

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
@slnn no regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127113

**Pull request closed without merging**
