### PR TITLE
LPD-28265 add back log4j-1.2-api to lib/development to make sure "ant build-iw" work

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This is for ticket https://liferay.atlassian.net/browse/LPD-28265.
I have added back log4j-1.2-api to lib/development as talked, and checked locally, "ant build-iw" can run without error
Screenshot_20240612_081751

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:report:15272251

**Comment by jeffwu0724** [comment]
https://testray.liferay.com/#/project/34754/routines/34756/build/15272251/case-result/15291137/history did not run, and it is related to build-iw-jdk8/0/0
gonna rerun the test to make sure this failing is not related

**Comment by jeffwu0724** [comment]
ci:report:16019828

**Comment by jeffwu0724** [comment]
No unique error found in the report, but there is a "**Did not run Failures**" seems related
```
Failures unique to this pull:
[build-iw-jdk8/0/0](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1128998//consoleText)
     [echo] diff --git a/portal-kernel/src/com/liferay/portal/kernel/util/StringUtil_IW.java b/portal-kernel/src/com/liferay/portal/kernel/util/StringUtil_IW.java
     [echo] index 5222216a70151..304178a0f86be 100644
     [echo] --- a/portal-kernel/src/com/liferay/portal/kernel/util/StringUtil_IW.java
     [echo] +++ b/portal-kernel/src/com/liferay/portal/kernel/util/StringUtil_IW.java
     [echo] @@ -248,13 +248,13 @@ public class StringUtil_IW \{
     [echo]      return StringUtil.merge(array, delimiter);
     [echo]    \}
     [echo]  
     [echo] -  public java.lang.String merge(java.util.Collection<?> col) \{
     [echo] -    return StringUtil.merge(col);
     [echo] +  public java.lang.String merge(java.util.Collection<?> collection) \{
     [echo] +    return StringUtil.merge(collection);
     [echo]    \}
     [echo]  
     [echo] -  public java.lang.String merge(java.util.Collection<?> col,
     [echo] +  public java.lang.String merge(java.util.Collection<?> collection,
     [echo]      java.lang.String delimiter) \{
     [echo] -    return StringUtil.merge(col, delimiter);
     [echo] +    return StringUtil.merge(collection, delimiter);
     [echo]    \}
     [echo]  
     [echo]    public java.lang.String merge(double[] array) \{
     [echo] @@ -432,6 +432,11 @@ public class StringUtil_IW \{
     [echo]      return StringUtil.replace(s, begin, end, values);
     [echo]    \}
     [echo]  
     [echo] +  public java.lang.String replace(java.lang.String s,
     [echo] +    java.lang.String[] oldSubs, java.lang.Object[] newSubs) \{
     [echo] +    return StringUtil.replace(s, oldSubs, newSubs);
     [echo] +  \}
     [echo] +
     [echo]    public java.lang.String replace(java.lang.String s,
     [echo]      java.lang.String[] oldSubs, java.lang.String[] newSubs) \{
     [echo]      return StringUtil.replace(s, oldSubs, newSubs);
[stopwatch] [run.batch.test.action: 2.245 sec]
     [echo] .
     [echo] 
     [echo] Detected build-iw changes. See above build-iw log for more
     [echo] information. Make sure to commit in all build-iw results.
      [get] Getting: \$\{dependencies.url\}/archive/test-1-37/test-portal-acceptance-pullrequest-downstream(master)/1128998consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20240612091118316.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20240612091118316.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null975454855.properties
```
After I run "ant build-iw" locally, I can see this change pop up in the working tree change log, but I am not sure if we should include this change, as this seem to be a left-over regen.

**Comment by tinatian** [comment]
See   https://github.com/brianchandotcom/liferay-portal/pull/151329

**Pull request closed without merging**
