### PR TITLE
LPS-150808 Move petra-http-invoker to portal-http-invoker

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,

Main Task: [LPS-147928](https://issues.liferay.com/browse/LPS-147928)
SubTask: [LPS-150808](https://issues.liferay.com/browse/LPS-150808)

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
could you please help me scan the test result?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by julschong** [comment]
force pushed to resolve conflict in modules.properties. nothing else is different

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
force pushed to resolve conflict in modules.properties. nothing else is different

**Comment by julschong** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@julschong @tinatian this one should be moved to core/petra. The goal for this round of apps/petra cleanup is to make sure "petra" really has no dependencies other than jdk and other petra modules. This http-invoker one is clean enough to be promoted to core/petra. The only other clean "apps/petra" is "apps/petra/petra-content", but it only has an useless "ContentUtil" in it. For the petra-content just remove all of its usage to avoid using the content cache, most usage won't be really re-reading the content anyway. If some usages really do frequently re-reading the content, it should hold the content internally rather than relying on blindly cached pool.

**Comment by tinatian** [comment]
@shuyangzhou Sure, we will. For the content util usages, there are some related to template reading, we can remove them all and check the performance, if there is any regression, I will add it back to a local cache.

Tina.

**Pull request closed without merging**
