### PR TITLE
[Remove Blocking Usage] LPS-194491 AggregateFilter

### PR DESCRIPTION
**Pull request by haydenzheng314**
Ticket: https://liferay.atlassian.net/browse/LPS-194491
Thanks.

### CODE REVIEW

**Comment by liuxingye** [comment]
Reviewing...

**Comment by liuxingye** [comment]
Hi @slnn

No regressions were found after analyzing the test [results](https://testray.liferay.com/home/-/testray/runs?tab=results&testrayBuildId=2427145454) for the relevant suite, could you help to add QA Pass label? 

Thanks.

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
@liuxingye Running an extra suite, could you please also take a look when it's done? Thanks!

**Comment by Kvale1733** [comment]
@LisztLiszt No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
