### PR TITLE
[Bug Fix]LPS-143418

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please trigger any functional tests related to fragment bundle if not covered?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Regressions here with integration tests.

#### 1. Seems that most tests are throwing console error when test bundle is added to portal.
```
ERROR [Framework Event Dispatcher: Equinox Container: 73f98743-a4b2-4a37-afd6-4dc69cc5ef81][Framework:93] FrameworkEvent ERROR
java.lang.NullPointerException: null
        at com.liferay.portal.fragment.bundle.watcher.internal.PortalFragmentBundleWatcher._isFragment(PortalFragmentBundleWatcher.java:175) ~[?:?]
        at com.liferay.portal.fragment.bundle.watcher.internal.PortalFragmentBundleWatcher.lambda$activate$1(PortalFragmentBundleWatcher.java:77) ~[?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908) [org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi.jar:?]
```
This should be reproducible by running any integration test. See the Liferay portal log (not the test log)

#### 2. Then some tests are actually failing:

[com.liferay.portal.bundle.blacklist.test.BundleBlacklistTest](https://testray.liferay.com/home/-/testray/case_results/1587527898)
Steps used to reproduce locally:
1. `cd modules/apps/static/portal-bundle-blacklist/portal-bundle-blacklist-test`
2. `gw testIntegration --tests BundleBlacklistTest`

Other unique failures (seem to all be related to the same issue):
https://testray.liferay.com/home/-/testray/case_results/1587527984
https://testray.liferay.com/home/-/testray/case_results/1587528437
https://testray.liferay.com/home/-/testray/case_results/1587528424
https://testray.liferay.com/home/-/testray/case_results/1587528411
https://testray.liferay.com/home/-/testray/case_results/1587527930
https://testray.liferay.com/home/-/testray/case_results/1587527969

**Pull request closed without merging**
