### PR TITLE
Lps 143631 5 4 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
@julschong @tinatian this test failed:
ListObjectFieldFilterParserTest

```
com.liferay.object.internal.field.filter.parser.ListObjectFieldFilterParserTest > testValidate FAILED
    java.lang.NullPointerException
        at com.liferay.object.internal.field.filter.parser.ListObjectFieldFilterParser.validate(ListObjectFieldFilterParser.java:103)
        at com.liferay.object.internal.field.filter.parser.ListObjectFieldFilterParserTest.testValidate(ListObjectFieldFilterParserTest.java:58)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-37/test-portal-acceptance-pullrequest(master)/2293/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
see #804

**Comment by julschong** [comment]
ci:close

**Pull request closed without merging**
