### PR TITLE
LPS-188134  moving guava to shared-dependenceis

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

Resent https://github.com/liferay-core-infra/liferay-portal/pull/4896 and https://github.com/liferay-core-infra/liferay-portal/pull/5179.
As in the PR above, it caused a blocker(had been reverted) by using shared-dependencies. In this PR, I would like to change back to compileInclude and see how it will go. https://liferay.atlassian.net/browse/LPS-191330

This is for ticket https://liferay.atlassian.net/browse/LPS-188134.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:online-editing

**Comment by jeffwu0724** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:security

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:security

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found. Ran our Google Cloud Store test locally and it passed.

**Comment by Kvale1733** [comment]
@jeffwu0724 Yes saw no regressions in the tests.

**Comment by jeffwu0724** [comment]
only fix the code conflict in `modules/test/jenkins-results-parser/build.gradle`, @Kvale1733 do you think we should retrigger any test, or the previous test result is good enough?

**Comment by Kvale1733** [comment]
@jeffwu0724 Let's just check relevant.

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139221

**Pull request closed without merging**
