### PR TITLE
LPS-145771

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian, @shuyangzhou ,

I have removed unused properties "Portlet.url.generate.by.path.enabled", and updated to propskeys.java, propsvalues.java and verifyproperties.java.
It was used in "PortletURLAction.java" based on commit 840345d17238ab44b1fcb306d00e3688831acd23, see LPS-34098. 
It was finally deleted based on commit 9769ac720de0150f556f4977aeb483060b10f4a7, see LPS-60861
Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.
@jeffwu0724 Code looks good to me, wait for QA to scan test results.

Tina.

**Comment by vicnate5** [comment]
@Hijky Can you check the results here?

**Comment by Hijky** [comment]
None of the failed cases are relevant

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/112753

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
