### PR TITLE
LPS-185647 Fix transaction-related bug when deleting ResourceActions in a partitioned environment

### PR DESCRIPTION
**Pull request by mbowerman**
Set a TransactionConfig in the ActionableDynamicQuery to force the transaction to be committed after all the performAction calls finish running. This will ensure that we commit the transaction before switching over to the next partition (which would cause the transaction commit to fail if it were to happen).

Since we are calling this inside of `_forEachCompanyId`, we need to make sure that the Transaction is committed before we move on to the next partition. To accomplish this, I set a TransactionConfig in the actionableDynamicQuery object, which causes the ActionableDynamicQuery framework to commit the Transaction upon completing each `doPerformActions` call (see [here](https://github.com/liferay/liferay-portal/blob/71397801f3b041fa54fe6d25cbe2a9830daea102/portal-kernel/src/com/liferay/portal/kernel/dao/orm/DefaultActionableDynamicQuery.java#L322-L33)).

Could you please take a look and let me know if this is the right fix? Thanks!

Ticket: [LPS-185647](https://issues.liferay.com/browse/LPS-185647)

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:objects

**Comment by Kvale1733** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
ci:test:db-partition

**Comment by zhangyan0701** [comment]
Possible regressions:
1. Some integration tests failed with error:
`com.liferay.portal.kernel.exception.SystemException: org.springframework.dao.PessimisticLockingFailureException: could not execute batch; SQL [update ResourcePermission set mvccVersion=?, actionIds=?, viewActionId=? where resourcePermissionId=? and mvccVersion=?];`
Example:
[com.liferay.object.service.test.ObjectFieldLocalServiceTest](https://testray.liferay.com/home/-/testray/case_results/2319059981).
Full console log: https://testray.liferay.com/reports/production/logs/2023-05/test-1-38/test-portal-acceptance-pullrequest(master)/7732/modules-integration-mysql57-jdk8/3/1/jenkins-console.txt.gz?authuser=0
2. BatchUpdateException occurred when delete object definition via object api.
Example command:
`curl -X DELETE -u 'test@liferay.com:test' http://test-1-29-64.lax.liferay.com:8080/o/object-admin/v1.0/object-definitions/46305`
```
[beanshell] 2023-05-25 00:17:05.120 ERROR [http-nio-8080-exec-6][BatchingBatch:134] HHH000315: Exception executing batch [java.sql.BatchUpdateException: Lock wait timeout exceeded; try restarting transaction], SQL: update ResourcePermission set mvccVersion=?, actionIds=?, viewActionId=? where resourcePermissionId=? and mvccVersion=?
[beanshell] 2023-05-25 00:17:05.121 ERROR [http-nio-8080-exec-6][SqlExceptionHelper:142] Lock wait timeout exceeded; try restarting transaction
[beanshell] 2023-05-25 00:17:05.142 ERROR [http-nio-8080-exec-6][ExceptionMapper:68] null
[beanshell] com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
```
Full console log: https://testray.liferay.com/reports/production/logs/2023-05/test-1-31/test-portal-acceptance-pullrequest(master)/8134/functional-tomcat90-mysql57-jdk8/3/12/jenkins-console.txt.gz?authuser=0

**Comment by mbowerman** [comment]
Hello @zhangyan0701,

Thank you very much for reviewing and detecting the regression. I have sent a new pull request that should fix the regression here: https://github.com/liferay-core-infra/liferay-portal/pull/4643

**Pull request closed without merging**
