### PR TITLE
LPS-197617 - Refactor interface LayoutStructureItemMapper

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Related comment: https://github.com/liferay-core-infra/liferay-portal/pull/5631#issuecomment-1738236334
Ticket: https://liferay.atlassian.net/browse/LPS-197617
Correction of: https://github.com/liferay-core-infra/liferay-portal/pull/5798

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:tesf:sf

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found

**Review by rafaprax — APPROVED** [review]

**Comment by tinatian** [comment]
ci:forward:force

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
