### PR TITLE
[Spring Beans] LPS-200563 Merge UserGroupMembershipPolicyFactoryImpl into Util and move to portal-impl.

### PR DESCRIPTION
**Pull request by JanisZhang**
resent:https://github.com/liferay-core-infra/liferay-portal/pull/5990
https://liferay.atlassian.net/browse/LPS-200563

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
Sorry missed the label I'll stop the CI runs.

**Comment by Kvale1733** [comment]
ci:stop

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:upgrade

**Comment by zhangyan0701** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
ci:stop

**Comment by JanisZhang** [comment]
code conflicts, modules/apps/server/server-admin-web/src/main/java/com/liferay/server/admin/web/internal/portlet/action/EditServerMVCActionCommand.java

**Pull request closed without merging**
