### PR TITLE
[Round 3 static method reference]Lps 180567

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-180567

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
@slnn failure on startup:

```
[beanshell] 2023-04-03 11:57:41.670 INFO  [main][ModuleFrameworkImpl:281] Navigate to Control Panel > System > Gogo Shell and enter "lb" to see all bundles
[beanshell] 2023-04-03 11:57:41.892 ERROR [main][EntityCacheImpl:56] bundle com.liferay.portal.cache.impl:4.0.19 (191)[com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl(404)] :  Error during instantiation of the implementation object
[beanshell] java.lang.NoClassDefFoundError: Could not initialize class com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl
[beanshell] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
[beanshell] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
[beanshell] 	at org.apache.felix.scr.impl.inject.ComponentConstructor.newInstance(ComponentConstructor.java:308) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:278) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:983) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:956) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:901) ~[?:?]
[beanshell] 	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
[beanshell] 	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111) ~[org.eclipse.osgi.jar:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10340/functional-smoke-tomcat90-postgresql144-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by catarineaguiar** [comment]
ci:stop:relevant

**Comment by slnn** [comment]
Thank @catarineaguiar for catching this! Will fix and resend!

> ```
> 
> ```
> 
> 
>     
> 
>   
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10340/functional-smoke-tomcat90-postgresql144-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
Resend in https://github.com/liferay-core-infra/liferay-portal/pull/4102

**Pull request closed without merging**
