### PR TITLE
[Login-performance-tuning] LPS-148968

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, @tinatian

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@tinatian Looks good to me.

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by tinatian** [comment]
@yuhai Code looks good to me, wait for QA scan test results.

Tina

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Pull request closed without merging**
