### PR TITLE
[Round 3 static method reference]LPS-180567 Convert the method reference to instance field reference b…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-180567

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:clustering

**Comment by Kvale1733** [comment]
@slnn Regression found. Cannot update log levels for all nodes from master node.

Steps to reproduce
1. Setup 2 node cluster
2. On master 8080 node go to Control Panel >Server Administration > Log Levels
3. Add debug log for com.liferay.portal.cluster
4. Logout and login to 9080 node

Expected Results: "Send multicast message {destinationName=liferay/cache_replication, response=null, responseDestinationName=null, responseId=null, payload=[....." appears in both node logs.

Actual Results: The above logging message only appears in the 8080 node.

**Comment by slnn** [comment]
> @slnn Regression found. Cannot update log levels for all nodes from master node.
> 
> Steps to reproduce
> 
> 1. Setup 2 node cluster
> 2. On master 8080 node go to Control Panel >Server Administration > Log Levels
> 3. Add debug log for com.liferay.portal.cluster
> 4. Logout and login to 9080 node
> 
> Expected Results: "Send multicast message {destinationName=liferay/cache_replication, response=null, responseDestinationName=null, responseId=null, payload=[....." appears in both node logs.
> 
> Actual Results: The above logging message only appears in the 8080 node.

Thank @Kvale1733 for catching this ! Will find and resend.

Lily

**Comment by slnn** [comment]
Hi @Kvale1733 

I do not reproduce this issue with the steps

```
Steps to reproduce

Setup 2 node cluster
On master 8080 node go to Control Panel >Server Administration > Log Levels
Add debug log for com.liferay.portal.cluster
Logout and login to 9080 node
```

From the log of node1 (8080), I can see this :

```
2023-04-11 06:36:23.715 DEBUG [default-9][JGroupsClusterChannel:185] Send multicast message {destinationName=liferay/cache_replication, response=null, responseDestinationName=null, responseId=null, payload=[B@4f20ec17, values={}}
2023-04-11 06:36:23.716 DEBUG [default-43][JGroupsClusterChannel:185] Send multicast message {destinationName=liferay/cache_replication, response=null, responseDestinationName=null, responseId=null, payload=[B@659a946, values={}}
```

From the log of node 2 (9080), I can see this:
```
2023-04-11 06:38:19.627 DEBUG [default-46][JGroupsClusterChannel:185] Send multicast message {destinationName=liferay/cache_replication, response=null, responseDestinationName=null, responseId=null, payload=[B@287559c1, values={}}
2023-04-11 06:38:19.627 DEBUG [default-51][JGroupsClusterChannel:185] Send multicast message {destinationName=liferay/cache_replication, response=null, responseDestinationName=null, responseId=null, payload=[B@519e2586, values={}}
```

**Comment by Kvale1733** [comment]
Hey @slnn. Sorry I mixed up the steps. The issue is actually with updating the log level from slave node. I updated the steps.

**Pull request closed without merging**
