### PR TITLE
[Replace Non-Blocking Usage] LPS-200073  Replace non-blocking ServiceProxyFactory in AssetEntriesFacet, FacetedSearcherManagerUtil, FieldQueryFactoryUtil, ReindexStatusMessageSenderUtil 

### PR DESCRIPTION
**Pull request by haydenzheng314**
Ticket: https://liferay.atlassian.net/browse/LPS-200073
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@LisztLiszt No regressions found.

**Comment by dantewang** [comment]
@LisztLiszt https://github.com/liferay-core-infra/liferay-portal/pull/5920/commits/6528ab7ecb56111322a8b004223679572b6343ca has been deprecated since 7.1.x, please resend a PR without it, and investigate whether we can remove this class; if we can, send another PR to remove it.

**Pull request closed without merging**
