### PR TITLE
[Remove unused @Reference var] LPS-164058

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove the unused @reference variable in `asset-categories-admin-web`. Thanks!
CI test passed in https://github.com/JanisZhang/liferay-portal/pull/120

https://issues.liferay.com/browse/LPS-164058

### CODE REVIEW

**Comment by Kvale1733** [comment]
@JanisZhang Lots of test were aborted due to a startup issue. I was able to reproduce the issue locally too.

`2022-09-27 21:38:21.368 ERROR [Framework Event Dispatcher: Equinox Container: 827650be-468d-4983-bf83-dca2a69daf3e][Framework:56] FrameworkEvent ERROR
org.osgi.framework.BundleException: Could not resolve module: com.liferay.commerce.service [537]
  Unresolved requirement: Import-Package: com.liferay.commerce.product.service.impl

	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi.jar:?]
2022-09-27 21:38:31.293 INFO  [main][ModuleFrameworkImpl:1655] Started dynamic bundles
2022-09-27 21:38:31.293 INFO  [main][ModuleFrameworkImpl:1662] Starting web bundles
2022-09-27 21:38:35.090 ERROR [main][DirectoryWatcher:1176] Unable to start bundle: file:/home/kevin/Downloads/bundles/osgi/modules/com.liferay.commerce.service.jar
org.osgi.framework.BundleException: Could not resolve module: com.liferay.commerce.service [537]
  Unresolved requirement: Import-Package: com.liferay.commerce.product.service.impl
`[Example Log](https://testray.liferay.com/reports/production/logs/2022-09/test-1-36/test-portal-acceptance-pullrequest(master)/2113/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0l)

**Comment by Kvale1733** [comment]
@JanisZhang But I'm seeing the same issue on other runs like this one: https://testray.liferay.com/home/-/testray/case_results/1991575740 so maybe it's unrelated. Could you rebase with master and we can rerun relevant.

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@zhangyan0701 No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123992

**Pull request closed without merging**
