### PR TITLE
Lpd 41899 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:core-functional

**Comment by tinatian** [comment]
@victorhcunha Please run a diff on login test, this is urgent as it is fix for fire LPPs, please prioritize this

**Comment by victorhcunha** [comment]
Hi @tinatian!
I said the pull is closed. Do you still need a login check or should I wait for a new pull?

**Pull request closed without merging**
