### PR TITLE
[Bug fix] LPS-142300

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@koor4356 Please check this one.

**Comment by koor4356** [comment]
okay, thanks

**Comment by koor4356** [comment]
@dantewang 
No unique failure. Thanks!

**Comment by koor4356** [comment]
@dantewang @tinatian 
No unique failure. Thanks!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
