### PR TITLE
[Remove Stream/Optional usage] LPS-174912 Remove usages of Optional for module: portal-security-ldap-impl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:security

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(2/8 9:02)

**Comment by W2jx** [comment]
ci:test:help

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
