### PR TITLE
[TS][Test Branch] LPD-29738 | 2

### PR DESCRIPTION
**Pull request by dantewang**
@JerryAdrianoo Please run both runtime and startup comparison for this PR, thanks.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:29290114

**Comment by JerryAdrianoo** [comment]
Hey @dantewang  for more details from this test, see: [spreadsheet](https://docs.google.com/spreadsheets/d/1f17Xogj6NWEEVnll2WVrgiWFyCTGwoavAU0AF-ijTQc/edit?usp=sharing) 
Branch| Startup Time (ms)(without  default HSQL data)  Cold start | Percent of Average Startup Time Cold Start | Startup Time (ms)(without  default HSQL data) Hot start | Average Startup Time (ms)(without default HSQL data)  Hot start | Percent of Average Startup Time Hot Start | Shutdown Time (ms)(without default HSQL data)   Cold start | Shutdown Time (ms)(without default HSQL data)  Hot start | Average Shutdown Time (ms)(without default HSQL data)  Hot start
-- | -- | -- | -- | -- | -- | -- | -- | --
Before LPD-29738 | **42,583** | | 16,260 | | | **2,663** | 1,933
|  | | | 16,903 | | | | 1,949
|  | | | 16,274 | | | | 2,040
 | | | | 16,738 | | | | 1,914
 | | | | 16,529 |**16,514** | | | 1,950 | **1,944**
-- | -- | -- | -- | -- | -- | -- | --
After LPD-29738 | **42,196** | | 16,208 | | | **2,666** | 2,045
|  | | | 16,950 | | | | 1,937
|  | | | 16,556 | | | | 2,014
|  | | | 16,280 | | | | 1,975
| | |  -0.91% | 16,775 |**16,537** |  **0.14**% | | 1,984 | **1,991**

Everything looks ok, I didn't see any regression with these changes.
Please let me know if you need something else. 

I am running the benchmark test. When I finish it, I'll put it here.

**Comment by dantewang** [comment]
@JerryAdrianoo Thanks!

@tinatian This approach does affect runtime performance. I'll try to extract the maps into a separate class to manage.

**Pull request closed without merging**
