### PR TITLE
LPS-135290 Allowed classes should not be check as restricted ones

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:acceptance

**Comment by robertoDiaz** [comment]
Yes. 

In fact I misunderstood the issue (so is not the same case)

The problem we have now is that in some cases we should be able to see elements of different company, but it is not possible because they are processed as  RestrictedLiferayObjectWrapper.java instead of LiferayObjectWrapper.java.

**Comment by robertoDiaz** [comment]
Hi, any update??

I'd like to know if this logic makes sense to you (do not resctrict the configured AllowedClasses)

**Comment by robertoDiaz** [comment]
Hi @tinatian 

Any update related with this??

A customer is waiting for a fix, and I'd like to know (at least) if this approach makes sense to you.

Once you confirm this to me I could spend more time fixing the bugs if necessary.

**Comment by tinatian** [comment]
@robertoDiaz 

> The problem we have now is that in some cases we should be able to see elements of different company
Why you want this?

Tina

**Comment by tinatian** [comment]
@robertoDiaz If all you need is to get "dlFileEntryTypeLocalService.getFileEntryType(0)", please check with the document library team to make the file entry type have a copy for each company rather than having one for system company.

Tina.

**Comment by tinatian** [comment]
@robertoDiaz The description of https://issues.liferay.com/browse/LPS-135290 did not show what you want, if your issue focusing on seeing elements of other company, please create a new ticket for it or modify the description of current ticket.

Tina.

**Comment by tinatian** [comment]
@robertoDiaz I am going to close this pull, please resend or reopen if needed.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
