### PR TITLE
[Remove unused references]LPS-166417 Remove reference field _assetCategoryLocalService from App…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-166417

CI tests have been run in https://github.com/slnn/liferay-portal/pull/657

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@slnn no regressions found.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
