### PR TITLE
[Remove Stream/Optional usage] LPS-178729 module headless-commerce-admin-catalog-impl part 2

### PR DESCRIPTION
**Pull request by JanisZhang**
previous: https://github.com/liferay-core-infra/liferay-portal/pull/4060

Changes in this pull:
- drop commit which used transformToLongArray to simplify 
- resend SF commit

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
@JanisZhang No regressions.

**Comment by dantewang** [comment]
@JanisZhang Sorry, the transformToLongArray change was not reverted; Brian just add a fix to avoid the issue on 7.3. Could you bring back the commit to this pull?

**Comment by JanisZhang** [comment]
> @JanisZhang Sorry, the transformToLongArray change was not reverted; Brian just add a fix to avoid the issue on 7.3. Could you bring back the commit to this pull?

@dantewang Sure, thanks!

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:headless

**Comment by JanisZhang** [comment]
ci:test:commerce

**Review by dantewang — APPROVED** [review]

**Comment by Kvale1733** [comment]
@JanisZhang No regressions.

**Comment by JanisZhang** [comment]
ci:forward

**Comment by JanisZhang** [comment]
forwarding this pull as it's approved and passed QA reviewed. cc @dantewang @tinatian @shuyangzhou

**Pull request closed without merging**
