### PR TITLE
[Remove Stream/Optional usage] LPS-172223 Remove usages of Stream and Optional on Method Return Value for module: segments-experiment-web

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-172223.
Thanks for checking.

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:tango

**Review by dantewang — APPROVED** [review]
@jeffwu0724 Looks good, waiting for QA to check.

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128728

**Pull request closed without merging**
