### PR TITLE
LPS-196054 Merge RolePermission interface and impl into Util

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Shuyang,

This is for ticket https://liferay.atlassian.net/browse/LPS-196054.
Thanks for checking

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@jeffwu0724 regression found:

```
     [echo] diff --git a/portal-impl/bnd.bnd b/portal-impl/bnd.bnd
     [echo] index f111910dfcff..c6fd8b761baa 100644
     [echo] --- a/portal-impl/bnd.bnd
     [echo] +++ b/portal-impl/bnd.bnd
     [echo] @@ -1,6 +1,6 @@
     [echo]  Bundle-Name: ${manifest.bundle.name}
     [echo]  Bundle-SymbolicName: ${manifest.bundle.symbolic.name}
     [echo] -Bundle-Version: 88.0.1
     [echo] +Bundle-Version: 89.0.0
     [echo]  Export-Package:\
     [echo]  	com.liferay.portal.bean,\
     [echo]  	com.liferay.portal.dao.orm.hibernate,\
     [echo] diff --git a/portal-kernel/src/com/liferay/portal/kernel/service/permission/RolePermissionUtil_IW.java b/portal-kernel/src/com/liferay/portal/kernel/service/permission/RolePermissionUtil_IW.java
     [echo] index b2dd4cdd5704..c9192c34bbfe 100644
     [echo] --- a/portal-kernel/src/com/liferay/portal/kernel/service/permission/RolePermissionUtil_IW.java
     [echo] +++ b/portal-kernel/src/com/liferay/portal/kernel/service/permission/RolePermissionUtil_IW.java
     [echo] @@ -5,9 +5,6 @@
     [echo]  
     [echo]  package com.liferay.portal.kernel.service.permission;
     [echo]  
     [echo] -import com.liferay.portal.kernel.security.auth.PrincipalException;
     [echo] -import com.liferay.portal.kernel.security.permission.PermissionChecker;
     [echo] -
     [echo]  /**
     [echo]   * @author Brian Wing Shun Chan
     [echo]   */
     [echo] @@ -16,28 +13,28 @@ public class RolePermissionUtil_IW {
     [echo]  		return _instance;
     [echo]  	}
     [echo]  
     [echo] -	public static void check(
     [echo] -		PermissionChecker permissionChecker, long roleId, String actionId)
     [echo] -		throws PrincipalException {
     [echo] -		RolePermissionUtil.check(permissionChecker, roleId,
     [echo] -			actionId);
     [echo] +	public void check(
     [echo] +		com.liferay.portal.kernel.security.permission.PermissionChecker permissionChecker,
     [echo] +		long roleId, java.lang.String actionId)
     [echo] +		throws com.liferay.portal.kernel.security.auth.PrincipalException {
     [echo] +		RolePermissionUtil.check(permissionChecker, roleId, actionId);
     [echo]  	}
     [echo]  
     [echo] -	public static boolean contains(
     [echo] -		PermissionChecker permissionChecker, long groupId, long roleId,
     [echo] -		String actionId) {
     [echo] -		return RolePermissionUtil.contains(permissionChecker,
     [echo] -			groupId, roleId, actionId);
     [echo] +	public boolean contains(
     [echo] +		com.liferay.portal.kernel.security.permission.PermissionChecker permissionChecker,
     [echo] +		long groupId, long roleId, java.lang.String actionId) {
     [echo] +		return RolePermissionUtil.contains(permissionChecker, groupId, roleId,
     [echo] +			actionId);
     [echo]  	}
     [echo]  
     [echo] -	public static boolean contains(
     [echo] -		PermissionChecker permissionChecker, long roleId, String actionId) {
     [echo] -		return RolePermissionUtil.contains(permissionChecker, 0, roleId, actionId);
     [echo] +	public boolean contains(
     [echo] +		com.liferay.portal.kernel.security.permission.PermissionChecker permissionChecker,
     [echo] +		long roleId, java.lang.String actionId) {
     [echo] +		return RolePermissionUtil.contains(permissionChecker, roleId, actionId);
     [echo]  	}
     [echo]  
     [echo]  	private RolePermissionUtil_IW() {
     [echo]  	}
     [echo]  
     [echo]  	private static RolePermissionUtil_IW _instance = new RolePermissionUtil_IW();
     [echo] -
     [echo] -}
     [echo] +}
     [echo] \ No newline at end of file
[stopwatch] [run.batch.test.action: 1.935 sec]
     [echo] .
     [echo] 
     [echo] Detected build-iw changes. See above build-iw log for more
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-09/test-1-29/test-portal-acceptance-pullrequest(master)/8172/build-iw-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

semver error:
```
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.service.permission              MAJOR      5.0.0      5.0.0      6.0.0      VERSION INCREASE REQUIRED
[beanshell] 	-   class      com.liferay.portal.service.permission.RolePermissionImpl
[beanshell] 		-   implements com.liferay.portal.kernel.service.permission.RolePermission
[beanshell] 		-   method     <init>()
[beanshell] 			-   return     void
[beanshell] 		-   method     check(com.liferay.portal.kernel.security.permission.PermissionChecker,long,java.lang.String)
[beanshell] 			-   return     void
[beanshell] 		-   method     clone()
[beanshell] 			-   access     protected
[beanshell] 			-   return     java.lang.Object
[beanshell] 		-   method     contains(com.liferay.portal.kernel.security.permission.PermissionChecker,long,java.lang.String)
[beanshell] 			-   return     boolean
[beanshell] 		-   method     contains(com.liferay.portal.kernel.security.permission.PermissionChecker,long,long,java.lang.String)
[beanshell] 			-   return     boolean
[beanshell] 		-   method     equals(java.lang.Object)
[beanshell] 			-   return     boolean
[beanshell] 		-   method     finalize()
[beanshell] 			-   access     protected
[beanshell] 			-   return     void
[beanshell] 		-   method     hashCode()
[beanshell] 			-   return     int
[beanshell] 		-   method     toString()
[beanshell] 			-   return     java.lang.String
[beanshell] [Baseline Warning] Bundle Version Change Recommended: 89.0.0
[beanshell] 
     [echo] 
     [echo] ##
     [echo] ## /opt/dev/projects/github/liferay-portal/baseline-reports/portal-kernel.log
     [echo] ##
     [echo] 
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.kernel.service.permission       MAJOR      6.0.0      6.0.0      7.0.0      VERSION INCREASE REQUIRED
[beanshell] 	>   class      com.liferay.portal.kernel.service.permission.RolePermissionUtil
[beanshell] 		-   method     getRolePermission()
[beanshell] 			-   access     static
[beanshell] 			-   return     com.liferay.portal.kernel.service.permission.RolePermission
[beanshell] 		-   method     setRolePermission(com.liferay.portal.kernel.service.permission.RolePermission)
[beanshell] 			-   return     void
[beanshell] 	+   class      com.liferay.portal.kernel.service.permission.RolePermissionUtil_IW
[beanshell] 		+   method     check(com.liferay.portal.kernel.security.permission.PermissionChecker,long,java.lang.String)
[beanshell] 			+   access     static
[beanshell] 			+   return     void
[beanshell] 		+   method     clone()
[beanshell] 			+   access     protected
[beanshell] 			+   return     java.lang.Object
[beanshell] 		+   method     contains(com.liferay.portal.kernel.security.permission.PermissionChecker,long,java.lang.String)
[beanshell] 			+   access     static
[beanshell] 			+   return     boolean
[beanshell] 		+   method     contains(com.liferay.portal.kernel.security.permission.PermissionChecker,long,long,java.lang.String)
[beanshell] 			+   access     static
[beanshell] 			+   return     boolean
[beanshell] 		+   method     equals(java.lang.Object)
[beanshell] 			+   return     boolean
[beanshell] 		+   method     finalize()
[beanshell] 			+   access     protected
[beanshell] 			+   return     void
[beanshell] 		+   method     getInstance()
[beanshell] 			+   access     static
[beanshell] 			+   return     com.liferay.portal.kernel.service.permission.RolePermissionUtil_IW
[beanshell] 		+   method     hashCode()
[beanshell] 			+   return     int
[beanshell] 		+   method     toString()
[beanshell] 			+   return     java.lang.String
[beanshell] 	-   interface  com.liferay.portal.kernel.service.permission.RolePermission
[beanshell] 		-   access     abstract
[beanshell] 		-   method     check(com.liferay.portal.kernel.security.permission.PermissionChecker,long,java.lang.String)
[beanshell] 			-   access     abstract
[beanshell] 			-   return     void
[beanshell] 		-   method     contains(com.liferay.portal.kernel.security.permission.PermissionChecker,long,java.lang.String)
[beanshell] 			-   access     abstract
[beanshell] 			-   return     boolean
[beanshell] 		-   method     contains(com.liferay.portal.kernel.security.permission.PermissionChecker,long,long,java.lang.String)
[beanshell] 			-   access     abstract
[beanshell] 			-   return     boolean
[beanshell] 
[stopwatch] [run.batch.test.action: 5.105 sec]
     [echo] Semantic versioning is incorrect.
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-09/test-1-29/test-portal-acceptance-pullrequest(master)/8172/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by jeffwu0724** [comment]
changed back to use `rolePermission` instead of `rolePermissionUtil`
`velocityContext.put("rolePermission", RolePermissionUtil_IW.getInstance());`
The previous test result should be good enough

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141226

**Pull request closed without merging**
