### PR TITLE
[TS] LPS-178114 The same PipingServletResponse workaround that we use for WebLogic needs to be applied to WebSphere too

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-178114](https://issues.liferay.com/browse/LPS-178114)

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:environments

**Review by dantewang — APPROVED** [review]
@yuhai The code change looks simple and good to me, please verify if it's valid, thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by yuhai** [comment]
@dantewang, @mbowerman, I understand the case and resend it to https://github.com/liferay-echo/liferay-portal/pull/11388 to review. Please see the commit message to check the root issue. I am going to close the pr.

**Pull request closed without merging**
