### PR TITLE
LPS-173546 1 24 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by Kvale1733** [comment]
@tinatian Compile failure in portal-scheduler-quartz
```
 [exec] > Task :apps:portal-scheduler:portal-scheduler-quartz:compileTestJava FAILED
     [exec] 
     [exec] > Task :apps:portal-scheduler:portal-scheduler-quartz:processTestResources NO-SOURCE
     [exec] > Task :apps:static:portal:portal-upgrade-api:autoUpdateXml SKIPPED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-scheduler/portal-scheduler-quartz/src/test/java/com/liferay/portal/scheduler/quartz/internal/QuartzSchedulerEngineTest.java:413: error: incompatible types: java.lang.String cannot be converted to org.quartz.Scheduler
     [exec] 			_MEMORY_TEST_GROUP_NAME, StorageType.MEMORY);
     [exec] 			^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-scheduler/portal-scheduler-quartz/src/test/java/com/liferay/portal/scheduler/quartz/internal/QuartzSchedulerEngineTest.java:432: error: incompatible types: java.lang.String cannot be converted to org.quartz.Scheduler
     [exec] 			_PERSISTED_TEST_GROUP_NAME, StorageType.PERSISTED);
     [exec] 			^
 ```
 [Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-39/test-portal-acceptance-pullrequest(master)/2501/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:clustering

**Comment by Kvale1733** [comment]
@tinatian No regressions.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129256

**Pull request closed without merging**
