### PR TITLE
LPS-173597 Cleanup in DLProcessorRegistryImpl

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:dl-store

**Comment by rafaprax** [comment]
@MrJohn1911 Looks good to me.

**Comment by catarineaguiar** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:lpkg

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
Hey @tinatian can you review this pull? thanks!

**Comment by tinatian** [comment]
@MrJohn1911 @rafaprax This pull is not completed, why we still have " dl.file.entry.processors=\
        com.liferay.portlet.documentlibrary.util.RawMetadataProcessorImpl" ? Can you also move RawMetadataProcessorImpl out?

Also why need to define two types of service "service = {AudioProcessor.class, DLProcessor.class}"? The old logic only publish as DLProcessor.

Please resend.

Thanks.
Tina.

**Pull request closed without merging**
