### PR TITLE
[Components with more than 1 service] LPS-183224 Refactor PortletProvider API part 1

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-183224

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
@rafaprax `AssetPublisherAddPortletProvider` still declares 2 services, will it be handled in the next PR?

**Comment by rafaprax** [comment]
Yeah @dantewang sorry for not explaining this before(I was DM'ing with @tinatian about this one). 

So, this pr is just a clean-up pr and the goal for this one is just to:

1. Making the `AddPortletProvider` interface one marker interface, like the others `*PortletProvider`, so that we can remove all those `*PortletProvider` interfaces in the next pr;
2. Removing some weird cases that can be done before the removal of the marker interfaces.

The next pr will apply a new pattern for all `PortletProvider` implementations and remove those marker interfaces.

Thanks

PS: I'm preparing the second pr here, https://github.com/rafaprax/liferay-portal/pull/1240

**Comment by rafaprax** [comment]
fixed conflicts

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by catarineaguiar** [comment]
ci:stop:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:test:message-boards

**Comment by rafaprax** [comment]
ci:test:wiki

**Comment by rafaprax** [comment]
ci:test:forms

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Semantic versioning issue:
```
     [exec] > Task :apps:layout:layout-api:baseline
     [exec] [Baseline Warning] Bundle Version Change Recommended: 34.1.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.layout.api-34.0.1.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.layout.api/34.0.0/85a46f478a673f09c76a541ef87a76c63bf98f4f/com.liferay.layout.api-34.0.0.jar
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-06/test-1-25/test-portal-acceptance-pullrequest(master)/1448/modules-semantic-versioning-jdk8/0/2/jenkins-console.txt.gz?authuser=0

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136661

**Pull request closed without merging**
