### PR TITLE
LPS-206190 remove io.appium from lib/development/dependencies.properties

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Dante, 

This is for ticket https://liferay.atlassian.net/browse/LPS-206190
I removed io.appium as I cannot find any real usage of it.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:report:2503554930

**Comment by jeffwu0724** [comment]
no regression found

**Comment by dantewang** [comment]
@jeffwu0724 LGTM. It seems to be for Poshi (saw it in some Poshi changelogs), could you get someone from ci or qa-ci-infrastructure to take a look?

**Comment by jeffwu0724** [comment]
asked a question in qa-ci-infrastructure channel, waiting for their response

**Comment by jeffwu0724** [comment]
get confirmed by ci team, io.appium is not needed anymore
FYI, https://liferay.slack.com/archives/CL3TWSMHQ/p1705971327578559?thread_ts=1705939505.565199&cid=CL3TWSMHQ

**Comment by dantewang** [comment]
ci:forward

cc @tinatian

**Pull request closed without merging**
