### PR TITLE
[Component with its own class name as service type ] LPS-194013 Refactor Registry classes from Dynamic Data Mapping module

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-194013

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:kaleo-forms

**Comment by zhangyan0701** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
@MrJohn1911 Regression found. I was able to reproduce locally. 

com.liferay.document.library.search.test.DLFileEntryMetadataDDMStructureIndexerTest
```
 [exec] com.liferay.document.library.search.test.DLFileEntryMetadataDDMStructureIndexerTest > testReindexDLFileEntry FAILED
     [exec]     java.lang.AssertionError: [] expected:<1> but was:<0>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at com.liferay.portal.search.test.util.HitsAssert.assertOnlyOne(HitsAssert.java:31)
     [exec]     	at com.liferay.document.library.search.test.DLSearchFixture.searchOnlyOne(DLSearchFixture.java:60)
     [exec]     	at com.liferay.document.library.search.test.DLFileEntryMetadataDDMStructureIndexerTe
```
[Log](https://testray.liferay.com/reports/production/logs/2023-09/test-1-27/test-portal-acceptance-pullrequest(master)/9918/modules-integration-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
