### PR TITLE
[Bug fix] LPS-161435 | 9-20

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian @shuyangzhou Resend as per https://github.com/liferay-core-infra/liferay-portal/pull/1701#issuecomment-1251637332 and confirmed with Shuyang that we can only apply one usage for now.

### CODE REVIEW

**Comment by zhangyan0701** [comment]
[modules-semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1983555439) failed with error:
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/portal-vulcan/portal-vulcan-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.portal.vulcan.util                     MINOR      3.5.0      3.5.0      3.6.0      VERSION INCREASE REQUIRED
     [exec]     	<   class      com.liferay.portal.vulcan.util.SearchUtil
     [exec]     		+   method     search(java.util.Map,com.liferay.petra.function.UnsafeConsumer,com.liferay.portal.kernel.search.filter.Filter,com.liferay.portal.kernel.search.Indexer,java.lang.String,com.liferay.portal.vulcan.pagination.Pagination,com.liferay.petra.function.UnsafeConsumer,com.liferay.petra.function.UnsafeConsumer,com.liferay.portal.kernel.search.Sort[],com.liferay.petra.function.UnsafeFunction)
     [exec]     			+   access     static
     [exec]     			+   return     com.liferay.portal.vulcan.pagination.Page
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 15.2.0
```

Full console:
https://testray.liferay.com/reports/production/logs/2022-09/test-1-38/test-portal-acceptance-pullrequest(master)/3782/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by dantewang** [comment]
@zhangyan0701 Is this the only unique error?

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dantewang After you made this change, I am wondering why we still need the method passing in indexerClassName, we should always pass in the indexer, as same issue may happen to other usages too.

Could you please do:
1. add the method to pass in indexer
2. apply this to all current usages

Thanks.
Tina.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123976

**Pull request closed without merging**
