### PR TITLE
LPS-151632 Move petra-portlet-url-builder to apps/portal

### PR DESCRIPTION
**Pull request by julschong**
LPS-151632 Move petra-portlet-url-builder to apps/portal

### CODE REVIEW

**Comment by julschong** [comment]
rebased to resolve conflict in:

> modules/apps/object/object-web/src/main/java/com/liferay/object/web/internal/object/definitions/display/context/ObjectDefinitionsViewsDisplayContext.java

**Comment by julschong** [comment]
ci:test:acceptance

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
Could you please help me review this test result?
Thank you!

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@julschong This commit  (https://github.com/liferay-core-infra/liferay-portal/pull/1227/commits/a827e7e6e8eca4bb7482e3bfc75e3339a0406634) is too big, it is really hard to review the changes, please separate into several commits for easy tracking.

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Pull request closed without merging**
