### PR TITLE
[Remove Stream/Optional usage] LPS-175072 Remove usages of Stream for module: oauth2-provider-web

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:oauth2

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(2/9 9:43)

**Comment by W2jx** [comment]
no conflicts(2/17 12:47)

**Pull request closed without merging**
