### PR TITLE
LPS-145583 Avoid using PortalUUIDUtil directly in modules

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina, Shuyang

Main Task: [LPS-143403](https://issues.liferay.com/browse/LPS-143403)
Sub Task: [LPS-145583](https://issues.liferay.com/browse/LPS-145583)

Thank you!

### CODE REVIEW

**Comment by tinatian** [comment]
@julschong Please regenerate service for all including modules and portal-impl by running "ant build-services", as your change affects not only modules, but the generated class in portal-impl.

Tina.

**Comment by julschong** [comment]
@tinatian Hi Tina,
it should not have affected portal-impl. But because I missed the osgiModule condition in ftl, it was adding @ServiceReference to what's inside portal-impl. Thanks

**Comment by julschong** [comment]
pushed to add osgiModule condition to ftl

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
@zhangyan0701 Hi Summer,
Coudl you please help me scan this test result?
Thank you!

**Comment by zhangyan0701** [comment]
ci:test:acceptance

**Comment by zhangyan0701** [comment]
Hi @julschong 

No regression found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116149

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
