### PR TITLE
[Remove Stream/Optional usage] LPS-175215 oauth2-provider-jsonws

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-175215

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:help

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by JanisZhang** [comment]
Thanks @zhangyan0701 !

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:oauth2

**Comment by catarineaguiar** [comment]
ci:test:oauth2

**Comment by catarineaguiar** [comment]
ci:stop:oauth2

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
