### PR TITLE
[ httpImpl ] LPS 150185-4-11

### PR DESCRIPTION
**Pull request by JanisZhang**

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @tinatian @dantewang,

Fixed compile failures and removed unused HTTP fields.

And I added one unit test `RankingResultUnitTest`  in 19afb59a0fca06ad165190745458d6343fe7d5b2 to resolve conflict, not sure whether it's ok or not. 

Also, no regressions were found in https://github.com/JanisZhang/liferay-portal/pull/3 

Thanks for checking

**Comment by dantewang** [comment]
@JanisZhang Do you mean `RankingResultUtilTest`?

**Comment by JanisZhang** [comment]
Yes..it was typo

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/597

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
