### PR TITLE
Lps 172272 stream

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-172272

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:tango

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@slnn Please see https://github.com/slnn/liferay-portal/pull/707 and resend.

**Comment by slnn** [comment]
> @slnn Please see [slnn#707](https://github.com/slnn/liferay-portal/pull/707) and resend.

Resend in https://github.com/liferay-core-infra/liferay-portal/pull/3380

**Pull request closed without merging**
