### PR TITLE
LPS-143631 Remove JSONFactoryUtil usages in modules and use service reference instead final

### PR DESCRIPTION
**Pull request by julschong**
resend from #2442 
added last commit for SF

### CODE REVIEW

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by julschong** [comment]
rebased again to run ci to make sure no more JSONFactoryUtil is added

**Comment by julschong** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
Sf Issues are unrelated.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126435

**Pull request closed without merging**
