### PR TITLE
LPD-26781 enable captcha in cancel shutdown

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

As we found this bug in https://liferay.atlassian.net/browse/LPD-26781,
I made a quick fix to enbale captcha in cancel shutdown

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:core-functional

**Comment by jeffwu0724** [comment]
ci:report:2571849294

**Comment by jeffwu0724** [comment]
ci:report:2571849294

**Comment by jeffwu0724** [comment]
ci:report:2571850371

**Comment by jeffwu0724** [comment]
ci:report:2571850371

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
