### PR TITLE
[Spring Beans] LPS-203461

### PR DESCRIPTION
**Pull request by JanisZhang**
previous: https://github.com/liferay-core-infra/liferay-portal/pull/6286

Hi @dantewang, after giving it some thought, I've decided to place the `LiveUsersMessageListener` in the `user-admin-web` module as it handles events related to users. And I've moved `ClusterBridgeMessageListener` to module since it only used for the live_users destination. 

https://liferay.atlassian.net/browse/LPS-203461

Thanks for reviewing,

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
cc @tinatian

**Pull request closed without merging**
