### PR TITLE
LPS-160230 Patch Freemarker to not use Introspector

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:acceptance

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Hey @catarineaguiar , I checked this unique failures pointed out by relevant suite and realized that they aren't. So I decided to rebase with upstream and run again, as many tests failed prior to running test.
Regarding acceptance suite, we didn't get the result with Jenkins and Testray information, how can we proceed with this situation?

**Comment by guilhermedcamacho** [comment]
@catarineaguiar please help me check the results, thanks!

**Comment by catarineaguiar** [comment]
@guilhermedcamacho regression found:

```
     [exec]     COMMERCE-6371. As a buyer, I want to be able to select an option value(SKU contributor) and I want to see product details updating(Price, SKU and Availability)
[beanshell] 2022-08-16 06:22:48.402 ERROR [http-nio-8080-exec-10][runtime:59] Error executing FreeMarker template
[beanshell] freemarker.template.TemplateModelException: Unknown property "id" on instance of com.liferay.commerce.frontend.taglib.servlet.taglib.SearchBarTag
[beanshell] 
[beanshell] ----
[beanshell] FTL stack trace ("~" means nesting-related):
[beanshell] 	- Failed at: @liferay_commerce_ui["search-bar"] id...  [in template "minium-theme_SERVLET_CONTEXT_/templates/topbar.ftl" at line 54, column 25]
[beanshell] 	- Reached through: #include "${full_templates_path}/topb...  [in template "minium-theme_SERVLET_CONTEXT_/templates/portal_normal.ftl" at line 50, column 41]
[beanshell] ----
[beanshell] 	at freemarker.ext.jsp.JspTagModelBase.setupTag(JspTagModelBase.java:109) ~[bundleFile:?]
[beanshell] 	at freemarker.ext.jsp.TagTransformModel.getWriter(TagTransformModel.java:69) ~[bundleFile:?]
[beanshell] 	at freemarker.core.Environment.visitAndTransform(Environment.java:485) ~[bundleFile:?]
[beanshell] 	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:103) ~[bundleFile:?]
[beanshell] 	at freemarker.core.Environment.visit(Environment.java:331) ~[bundleFile:?]
[beanshell] 	at freemarker.core.Environment.visit(Environment.java:337) ~[bundleFile:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-25/test-portal-acceptance-pullrequest(master)/4114/functional-tomcat90-mysql57-jdk8/9/6/jenkins-console.txt.gz?authuser=0)

**Comment by guilhermedcamacho** [comment]
See #1365

**Pull request closed without merging**
