### PR TITLE
LPS-161303 Fix builde.gradle dependencies from ModuleStructuresTest Failure

### PR DESCRIPTION
**Pull request by julschong**
@kyle-miho 
Hi Kyle, 
ModuleStructuresTest pass now

Thanks

### CODE REVIEW

**Comment by kyle-miho** [comment]
@julschong I see it, it passes on CI now, the PR should be good to go

**Comment by kyle-miho** [comment]
@tinatian I assigned this to you to review, PR looks good from qa side

**Comment by tinatian** [comment]
@julschong Please update your commit message and add more info about why you made this change.

Tina.

**Comment by julschong** [comment]
@tinatian Hi Tina,
commit message has been updated to add the reason why it needed to be fixed

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122246

**Pull request closed without merging**
