### PR TITLE
LPS-154714 Clean up unnecessary Mockito testCompile dependencies

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian

Main Task: LPS-153088  Upgrade Mockito to major version 4 and removes the dependency on PowerMock
Sub Task : LPS-154714 Clean up unnecessary Mockito testCompile dependencies

https://issues.liferay.com/browse/LPS-154714

Clean up unnecessary Mockito testCompile dependencies as mockito-core has been defined in Gradle default plugins. 

Thanks!

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian This is extracted from the main PR for Mockito upgrade. The main PR will be pretty big so we want to extract even if it's tiny.

**Comment by tinatian** [comment]
@zhangyan0701 Please help me scan test results.

Thanks.
Tina

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Pull request closed without merging**
