### PR TITLE
LPS-174904 Remove Stream usages for module: commerce-address-web

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
Rerunning Commere suite here since there is an unrelated path issue causing mass failures: https://github.com/Kvale1733/liferay-portal/pull/273

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by julschong** [comment]
problem with mixed up module name, closing

**Pull request closed without merging**
