### PR TITLE
[Remove Stream/Optional usage] Phase 1 LPS-172794 remove_stream_in_portal_tools_rest_builder

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@dantewang No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Comment by jeffwu0724** [comment]
ci:forward

**Comment by jeffwu0724** [comment]
ci:forward

**Comment by jeffwu0724** [comment]
ci:forward:force

**Pull request closed without merging**
