### PR TITLE
[Remove Immediate] LPS-192312 Remove immediate property from ComponentBlacklistImpl

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://liferay.atlassian.net/browse/LPS-192312

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
ci:test:echo

**Comment by zhangyan0701** [comment]
ci:stop

**Comment by zhangyan0701** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
ci:test:echo

**Comment by dantewang** [comment]
@rafaprax For https://github.com/liferay-core-infra/liferay-portal/pull/5200/commits/ba10b72ae431d95d27f5d41fbd4cedc4e839f491 commit message, I think you want to say "there is **no** need to have public api"?

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by rafaprax** [comment]
Hi all, I just fixed the commit message, see the empty diff here https://github.com/liferay-core-infra/liferay-portal/compare/1a7739be23a32328238d55646cd432a1d869e29c..a98542d494536bf6cd536e91f4f07805e8da1e7a

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139222

**Pull request closed without merging**
