### PR TITLE
Remove toXmlString() from model impl

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong Regression found. Several integration tests (mostly change.tracking) are failing before running with

```
[exec] > Task :apps:portal-background-task:portal-background-task-api:autoUpdateXml SKIPPED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/change-tracking/change-tracking-test/src/testIntegration/java/com/liferay/change/tracking/internal/closure/test/CTClosureFactoryImplTest.java:922: error: method does not override or implement a method from a supertype
     [exec] 		@Override
     [exec] 		^
     [exec] 
     [exec] > Task :apps:change-tracking:change-tracking-test:compileTestIntegrationJava
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/change-tracking/change-tracking-test/src/testIntegration/java/com/liferay/change/tracking/internal/reference/test/MissingTableReferenceDefinitionTest.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
```
[Example Testray](https://testray.liferay.com/home/-/testray/case_results/1996949805?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1996938354%26testrayRunId%3D1996941923%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@julschong As we talked, please resend.

Thanks.
Tina

**Pull request closed without merging**
