### PR TITLE
LPS-191325 Remove web cache usage in search-experience-service

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from https://github.com/liferay-core-infra/liferay-portal/pull/5110
use singleVMPool

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
Possible regression:
Test [SXPBlueprintSearchRequestContributorTest](https://testray.liferay.com/home/-/testray/case_results/2397665883) failed.
```
##
## com.liferay.search.experiences.internal.blueprint.search.spi.searcher.test.SXPBlueprintSearchRequestContributorTest > testIPStackConfiguration
##

	java.lang.RuntimeException
		at com.liferay.search.experiences.internal.blueprint.search.spi.searcher.SXPBlueprintSearchRequestContributor._enhance(SXPBlueprintSearchRequestContributor.java:117)
		at com.liferay.search.experiences.internal.blueprint.search.spi.searcher.SXPBlueprintSearchRequestContributor._contributeSXPBlueprintId(SXPBlueprintSearchRequestContributor.java:62)
		at com.liferay.search.experiences.internal.blueprint.search.spi.searcher.SXPBlueprintSearchRequestContributor.contribute(SXPBlueprintSearchRequestContributor.java:42)
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-07/test-1-28/test-portal-acceptance-pullrequest(master)/7144/modules-integration-mysql57-jdk8/0/6/jenkins-console.txt.gz?authuser=0

**Comment by julschong** [comment]
pushed to fix integration test failure https://github.com/liferay-core-infra/liferay-portal/pull/5157#issuecomment-1660042846

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
no regressions found

**Pull request closed without merging**
