### PR TITLE
[Static reference] LPS-181530 Remove method reference by using snapshot in modules staging-taglib, template-taglib, trash-taglib

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:staging

**Comment by zhangyan0701** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
no conflicts（4/14 11:18）

**Comment by zhangyan0701** [comment]
No regressions found.

**Pull request closed without merging**
