### PR TITLE
LPS-199470 Merge SiteMembershipPolicyFactoryUtil into SiteMembershipPolicyUtil

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Shuyang,

Resent: https://github.com/liferay-core-infra/liferay-portal/pull/5890 and https://github.com/liferay-core-infra/liferay-portal/pull/6066
This is for ticket https://liferay.atlassian.net/browse/LPS-199470.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@jeffwu0724 semver error:

```
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.kernel.security.membershippolicy MAJOR      2.0.0      2.0.0      3.0.0      VERSION INCREASE REQUIRED
[beanshell] 	-   class      com.liferay.portal.kernel.security.membershippolicy.SiteMembershipPolicyFactoryUtil
[beanshell] 		-   method     <init>()
[beanshell] 			-   return     void
[beanshell] 		-   method     clone()
[beanshell] 			-   access     protected
[beanshell] 			-   return     java.lang.Object
[beanshell] 		-   method     equals(java.lang.Object)
[beanshell] 			-   return     boolean
[beanshell] 		-   method     finalize()
[beanshell] 			-   access     protected
[beanshell] 			-   return     void
[beanshell] 		-   method     getSiteMembershipPolicy()
[beanshell] 			-   access     static
[beanshell] 			-   return     com.liferay.portal.kernel.security.membershippolicy.SiteMembershipPolicy
[beanshell] 		-   method     getSiteMembershipPolicyFactory()
[beanshell] 			-   access     static
[beanshell] 			-   return     com.liferay.portal.kernel.security.membershippolicy.SiteMembershipPolicyFactory
[beanshell] 		-   method     hashCode()
[beanshell] 			-   return     int
[beanshell] 		-   method     setSiteMembershipPolicyFactory(com.liferay.portal.kernel.security.membershippolicy.SiteMembershipPolicyFactory)
[beanshell] 			-   return     void
[beanshell] 		-   method     toString()
[beanshell] 			-   return     java.lang.String
[beanshell] 	-   class      com.liferay.portal.kernel.security.membershippolicy.SiteMembershipPolicyUtil
[beanshell] 		-   method     <init>()
[beanshell] 			-   return     void
[beanshell] 		-   method     checkMembership(long[],long[],long[])
[beanshell] 			-   access     static
[beanshell] 			-   return     void
[beanshell] 		-   method     checkRoles(java.util.List,java.util.List)
[beanshell] 			-   access     static
[beanshell] 			-   return     void
[beanshell] 		-   method     clone()
[beanshell] 			-   access     protected
[beanshell] 			-   return     java.lang.Object
[beanshell] 		-   method     equals(java.lang.Object)
[beanshell] 			-   return     boolean
[beanshell] 		-   method     finalize()
[beanshell] 			-   access     protected
[beanshell] 			-   return     void
[beanshell] 		-   method     hashCode()
[beanshell] 			-   return     int
[beanshell] 		-   method     isMembershipAllowed(long,long)
[beanshell] 			-   access     static
[beanshell] 			-   return     boolean
[beanshell] 		-   method     isMembershipProtected(com.liferay.portal.kernel.security.permission.PermissionChecker,long,long)
[beanshell] 			-   access     static
[beanshell] 			-   return     boolean
[beanshell] 		-   method     isMembershipRequired(long,long)
[beanshell] 			-   access     static
[beanshell] 			-   return     boolean
[beanshell] 		-   method     isRoleAllowed(long,long,long)
[beanshell] 			-   access     static
[beanshell] 			-   return     boolean
[beanshell] 		-   method     isRoleProtected(com.liferay.portal.kernel.security.permission.PermissionChecker,long,long,long)
[beanshell] 			-   access     static
[beanshell] 			-   return     boolean
[beanshell] 		-   method     isRoleRequired(long,long,long)
[beanshell] 			-   access     static
[beanshell] 			-   return     boolean
[beanshell] 		-   method     propagateMembership(long[],long[],long[])
[beanshell] 			-   access     static
[beanshell] 			-   return     void
[beanshell] 		-   method     propagateRoles(java.util.List,java.util.List)
[beanshell] 			-   access     static
[beanshell] 			-   return     void
[beanshell] 		-   method     toString()
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   method     verifyPolicy()
[beanshell] 			-   access     static
[beanshell] 			-   return     void
[beanshell] 		-   method     verifyPolicy(com.liferay.portal.kernel.model.Group)
[beanshell] 			-   access     static
[beanshell] 			-   return     void
[beanshell] 		-   method     verifyPolicy(com.liferay.portal.kernel.model.Group,com.liferay.portal.kernel.model.Group,java.util.List,java.util.List,java.util.Map,com.liferay.portal.kernel.util.UnicodeProperties)
[beanshell] 			-   access     static
[beanshell] 			-   return     void
[beanshell] 		-   method     verifyPolicy(com.liferay.portal.kernel.model.Role)
[beanshell] 			-   access     static
[beanshell] 			-   return     void
[beanshell] 		-   method     verifyPolicy(com.liferay.portal.kernel.model.Role,com.liferay.portal.kernel.model.Role,java.util.Map)
[beanshell] 			-   access     static
[beanshell] 			-   return     void
[beanshell] 	-   interface  com.liferay.portal.kernel.security.membershippolicy.SiteMembershipPolicyFactory
[beanshell] 		-   access     abstract
[beanshell] 		-   method     getSiteMembershipPolicy()
[beanshell] 			-   access     abstract
[beanshell] 			-   return     com.liferay.portal.kernel.security.membershippolicy.SiteMembershipPolicy
[beanshell] 
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-30/test-portal-acceptance-pullrequest(master)/8317/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/9/23 9:26am

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/13/23 8:04am

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/144255

cc @shuyangzhou

**Pull request closed without merging**
