### PR TITLE
[Convert method references Round 2]LPS-164445

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to use serviceTrackerMap instead of the method reference in `headless-delivery`.  Thanks!

https://issues.liferay.com/browse/LPS-164445

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @zhangyan0701, 
Could you please help to take a look at the CI results?
It seems the above ci test error occurs in several pulls. (also https://github.com/liferay-core-infra/liferay-portal/pull/1859)  :thinking:

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
@zhangyan0701  Got the reply from Peter Yoo, will retrigger the CI test. Thanks.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123999

**Pull request closed without merging**
