### PR TITLE
[Components with more than 1 service] LPS-179353 Refactor ScreenNavigationCategory components from Commerce modules part 3

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://issues.liferay.com/browse/LPS-179353

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
@MrJohn1911 Regression found when adding widget page

Steps to reproduce: 
1. Add a new test site
2. Add a widget page to the site

Expected Results: Can add the widget page without error
Actual Results: The following error appears in the console

```
2023-04-07 17:24:06.022 ERROR [http-nio-8080-exec-4][CommerceInventoryWarehouseDetailsScreenNavigationEntry:56] bundle com.liferay.commerce.warehouse.web:4.0.43 (668)[com.liferay.commerce.warehouse.web.internal.frontend.taglib.servlet.taglib.CommerceInventoryWarehouseDetailsScreenNavigationEntry(8109)] : findField: Suitable but non-accessible field _commerceChannelService in class com.liferay.commerce.warehouse.web.internal.frontend.taglib.servlet.taglib.CommerceInventoryWarehouseDetailsScreenNavigationCategory, subclass of component class com.liferay.commerce.warehouse.web.internal.frontend.taglib.servlet.taglib.CommerceInventoryWarehouseDetailsScreenNavigationEntry
2023-04-07 17:24:06.025 ERROR [http-nio-8080-exec-4][CommerceInventoryWarehouseDetailsScreenNavigationEntry:56] bundle com.liferay.commerce.warehouse.web:4.0.43 (668)[com.liferay.commerce.warehouse.web.internal.frontend.taglib.servlet.taglib.CommerceInventoryWarehouseDetailsScreenNavigationEntry(8109)] : findField: Suitable but non-accessible field _commerceCountryManager in class com.liferay.commerce.warehouse.web.internal.frontend.taglib.servlet.taglib.CommerceInventoryWarehouseDetailsScreenNavigationCategory, subclass of component class com.liferay.commerce.warehouse.web.internal.frontend.taglib.servlet.taglib.CommerceInventoryWarehouseDetailsScreenNavigationEntry
2023-04-07 17:24:06.027 ERROR [http-nio-8080-exec-4][CommerceInventoryWarehouseDetailsScreenNavigationEntry:56] bundle com.liferay.commerce.warehouse.web:4.0.43 (668)[com.liferay.commerce.warehouse.web.internal.frontend.taglib.servlet.taglib.CommerceInventoryWarehouseDetailsScreenNavigationEntry(8109)] : findField: Suitable but non-accessible field _countryService in class com.liferay.commerce.warehouse.web.internal.frontend.taglib.servlet.taglib.CommerceInventoryWarehouseDetailsScreenNavigationCategory, subclass of component class com.liferay.commerce.warehouse.web.internal.frontend.taglib.servlet.taglib.CommerceInventoryWarehouseDetailsScreenNavigationEntry
2023-04-07 17:24:06.029 ERROR [http-nio-8080-exec-4][CommerceInventoryWarehouseDetailsScreenNavigationEntry:56] bundle com.liferay.commerce.warehouse.web:4.0.43 (668)[com.liferay.commerce.warehouse.web.internal.frontend.taglib.servlet.taglib.CommerceInventoryWarehouseDetailsScreenNavigationEntry(8109)] : findField: Suitable but non-accessible field _regionService in class com.liferay.commerce.warehouse.web.internal.frontend.taglib.servlet.taglib.CommerceInventoryWarehouseDetailsScreenNavigationCategory, subclass of component class com.liferay.commerce.warehouse.web.internal.frontend.taglib.servlet.taglib.CommerceInventoryWarehouseDetailsScreenNavigationEntry
2023-04-07 17:24:06.031 ERROR [http-nio-8080-exec-4][CommerceInventoryWarehouseQualifiersScreenNavigationEntry:56] bundle com.liferay.commerce.warehouse.web:4.0.43 (668)[com.liferay.commerce.warehouse.web.internal.frontend.taglib.servlet.taglib.CommerceInventoryWarehouseQualifiersScreenNavigationEntry(8111)] : findField: Suitable but non-accessible field _commerceChannelService in class com.liferay.commerce.warehouse.web.internal.frontend.taglib.servlet.taglib.CommerceInventoryWarehouseQualifiersScreenNavigationCategory, subclass of component class com.liferay.commerce.warehouse.web.internal.frontend.taglib.servlet.taglib.CommerceInventoryWarehouseQualifiersScreenNavigationEntry
2023-04-07 17:24:06.032 ERROR [http-nio-8080-exec-4][CommerceInventoryWarehouseQualifiersScreenNavigationEntry:56] bundle com.liferay.commerce.warehouse.web:4.0.43 (668)[com.liferay.commerce.warehouse.web.internal.frontend.taglib.servlet.taglib.CommerceInventoryWarehouseQualifiersScreenNavigationEntry(8111)] : findField: Suitable but non-accessible field _commerceCountryManager in class com.liferay.commerce.warehouse.web.internal.frontend.taglib.servlet.taglib.CommerceInventoryWarehouseQualifiersScreenNavigationCategory, subclass of component class com.liferay.commerce.warehouse.web.internal.frontend.taglib.servlet.taglib.CommerceInventoryWarehouseQualifiersScreenNavigationEntry

```

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Comment by MrJohn1911** [comment]
In this push, I added the commit [70ae9b8](https://github.com/liferay-core-infra/liferay-portal/pull/4146/commits/70ae9b876451dd01c8293e8bdadeb00d88dd7aea) to replace the usage of a ENTRY_KEY for a CATEGORY_KEY.

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian @rafaprax

**Pull request closed without merging**
