### PR TITLE
LPS-136334 The widget crashes when changing the filter with "downloads" in DM management toolbar

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
@tinatian How do these methods look? Thanks

**Comment by stsquared99** [comment]
ci:test:sf

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@stsquared99 
After a second thought, I think it would be better to only expose `getViewCountEntryTable` from `ViewCountManager`, and move all other logic you currently added into `DLFileEntryFinderImpl`.  In `DLFileEntryFinderImpl` you can use `getColumn()` to get the Column you needed to build your expression.

As only `DLFileEntryFinderImpl` uses the logic you added in `ViewCountManager`, it would be better to inline the logic into its usages rather than exposing in `ViewCountManager`. Later, if we have similar usage, we can extract common method into `ViewCountManager` to avoid duplicated code.



Tina.

**Comment by stsquared99** [comment]
Resent: https://github.com/liferay-core-infra/liferay-portal/pull/26

**Pull request closed without merging**
