### PR TITLE
[Remove Stream/Optional usage] LPS-176207 module: commerce-product-definitions-web

### PR DESCRIPTION
**Pull request by haydenzheng314**
Ticket: https://issues.liferay.com/browse/LPS-176207
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:commerce

**Comment by dantewang** [comment]
@LisztLiszt Is this module from "Usages on Method Return Value" page?

**Comment by LisztLiszt** [comment]
> @LisztLiszt Is this module from "Usages on Method Return Value" page?

I mixed up, just changed it

**Review by dantewang — APPROVED** [review]

**Comment by Kvale1733** [comment]
@LisztLiszt No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130679

**Pull request closed without merging**
