### PR TITLE
[Remove Blocking usages]LPS-192257 portal-kernel |FullNameGeneratorFactory

### PR DESCRIPTION
**Pull request by JanisZhang**
I will change to Snapshot in the second round after [fixing the Snapshot bug](https://github.com/liferay-core-infra/liferay-portal/pull/5714). Thanks!

https://liferay.atlassian.net/browse/LPS-192257

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by JanisZhang** [comment]
Thanks. @Kvale1733

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
