### PR TITLE
[Jasper] LPD-36036 Use Tomcat Jasper in Runtime | 11-6

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:app-servers

**Comment by dantewang** [comment]
ci:test:frontend

**Comment by dantewang** [comment]
SF failure due to I forgot to include `/* @generated */` in the patched file after removing the other 2 patch commits. I'll leave it for now since it's not the final version and the patch may be removed as well.

**Comment by tinatian** [comment]
ci:report:61106062

**Comment by tinatian** [comment]
ci:report:61099992

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7620

**Pull request closed without merging**
