### PR TITLE
[PowerMock] LPS 151525

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @tinatian @dantewang,

This pull is to remove PowerMock in modules/apps/dynamic-data-mapping-form-field-type part three.

https://issues.liferay.com/browse/LPS-151525

Thanks for checking.

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @tinatian @dantewang,

This pull is to remove PowerMock in modules/apps/dynamic-data-mapping-form-field-type part three.

https://issues.liferay.com/browse/LPS-151525 

Thanks for checking.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116287

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
