### PR TITLE
[Reflection] LPD-15644 unfinal VerifyProperties fields and avoid using SecurityManager since it is deprecated in java 17 for VerifyPropertiesTest

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
fix sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/146678

**Pull request closed without merging**
