### PR TITLE
[Convert method references ]LPS-162736 Convert method references to field references in module co…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-162736

/cc @dantewang @tinatian

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished ?

Thanks
Lily

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Hi @zhangyan0701 

I fix the origin issue and rerun tests, please help to double check test results when they are finished.

Thanks
Lily

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:commerce

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@Kvale1733 Could you review the test results when they finish? Thanks!

**Comment by Kvale1733** [comment]
@slnn @dantewang No regressions found.

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@victoroscuro Please help me scan test results.

Thanks.
Tina

**Comment by victoroscuro** [comment]
@tinatian Checks are fine. Thanks

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123252

**Pull request closed without merging**
