### PR TITLE
[Decouple Http] LPS 150185 

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @tinatian @dantewang,

This pull is to move the methods related to `org.apache.http` in httpimpl to the new HttpClient class. 
https://issues.liferay.com/browse/LPS-150185
Thanks for Checking!

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @zhangyan0701, 

Could you please help to look at the test result, thanks!

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@JanisZhang As we talked, please resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
