### PR TITLE
[Method References 2] LPS-169774 Convert method reference to ServiceTrackerMap in module portal-search-admin-web

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/brianchandotcom/liferay-portal/pull/129727

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@W2jx No regressions.

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(2/10 9:06)

**Comment by tinatian** [comment]
@W2jx @dantewang You do not need to expose IndexReindexerRegistry as an API as the two usages are in the same module, please make it a internal class directly. 

Thanks.
Tina.

**Pull request closed without merging**
