### PR TITLE
[Replace Non-Blocking Usage] LPS-200634

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace non-blocking ServiceProxyFactory usages in class `GroupLocalServiceImpl`, `IndexableActionableDynamicQuery`, `UserGroupLocalServiceImpl`. thanks.
https://liferay.atlassian.net/browse/LPS-200634

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by Sharryxue** [comment]
There is no related issue found in [ci:test:relevant](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2451357712), [ci:test:upgrade](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2451254934) and [ci:test:startup ](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2451236734) suites, could you help with adding the QA Passed label @zhangyan0701, thanks in advance.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143283

@JanisZhang I excluded https://github.com/liferay-core-infra/liferay-portal/pull/6011/commits/f9f80bb3cc8729122e933552c312391589a16bfd since it's handled by https://github.com/brianchandotcom/liferay-portal/pull/143274

cc @shuyangzhou

**Pull request closed without merging**
