### PR TITLE
[Remove Stream/Optional usage] LPS-176511 module: dynamic-data-mapping-test

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-176511

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:help

**Comment by JanisZhang** [comment]
ci:test:ddm

**Comment by catarineaguiar** [comment]
ci:test:data-engine

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131629

**Pull request closed without merging**
