### PR TITLE
LPS-172713 Revert Remove Dom4jUtil usages in portal-tools-wsdd-builder

### PR DESCRIPTION
**Pull request by julschong**
@tinatian @vicnate5 @zhangyan0701 @brianchandotcom
Hi Tina, Victor, Summer, Brian,

My PR for ticket [LPS-172713](https://issues.liferay.com/browse/LPS-172713) caused some errors below 
in 7.0.x running ant all
in 7.3.0 gw buildWSDD in gw buildWSDD in segments-service
              ant build-wsdds in portal-impl

This is very strange because before we sent the PR off to brian, I tested with ant build-wsdds in portal-impl in 7.3.0
https://github.com/liferay-core-infra/liferay-portal/pull/3154

This PR is to revert all the commits from my PR so that this can be investigated further.
Please help us test this on 7.0.x and 7.3.x to make sure it no longer cause these issues.

I think that the way I tested this may not be right since it's still failing after I reverted all the commits on this PR locally. 
Please let me know if you have a better way for testing.

My test procedures:
- cd `modules/util/portal-tools-wsdd-builder` then `gw clean deploy`
- go to where the jar is built in master -> `tools/sdk/dependencies/com.liferay.portal.wsdd.builder/lib/`
- copy the wsdd jar into 7.3.x -> `tools/sdk/dependencies/com.liferay.portal.wsdd.builder/lib/`
- cd into `7.3.x/portal-impl`, run `ant build-wsdds`

New Testing update at 5:42pm PST:
on master without reverting the commits, if we remove all jars inside 7.3.x tools lib, then copy only the wsdd jar in, 
ant build-wsdds passes

I think that there may be some package or class name conflicts causing this.

Thank you!

```
> Task :apps:segments:segments-service:buildWSDD FAILED
Feb 07, 2023 9:47:46 AM com.liferay.portal.kernel.log.Jdk14LogImpl warn
WARNING: XSD validation is disabled because unrecognized feature http://apache.org/xml/features/validation/schema-full-checking
Feb 07, 2023 9:47:46 AM com.liferay.portal.kernel.log.Jdk14LogImpl warn
WARNING: XSD validation is disabled because unrecognized feature http://apache.org/xml/features/validation/schema-full-checking
Exception in thread "main" org.dom4j.DocumentException: Error on line 2 of document file:///home/me/dev/projects/liferay-portal-7.3.x/modules/apps/segments/segments-service/service.xml : parsing initialization error: org.gjt.xpp.XmlPullParserException: <![DOCTYPE declarations not supported at line 2 and column 141 seen ...//www.liferay.com/dtd/liferay-service-builder_7_3_0.dtd"... (parser state UNKNONW_EVENT (-1))
        at org.dom4j.io.SAXReader.read(SAXReader.java:511)
        at org.dom4j.io.SAXReader.read(SAXReader.java:325)
        at com.liferay.portal.tools.ToolsUtil._getContentDocument(ToolsUtil.java:469)
        at com.liferay.portal.tools.ToolsUtil.getContent(ToolsUtil.java:72)
        at com.liferay.portal.tools.wsdd.builder.WSDDBuilder.build(WSDDBuilder.java:86)
        at com.liferay.portal.tools.wsdd.builder.WSDDBuilder.main(WSDDBuilder.java:62)
Caused by: org.xml.sax.SAXParseException; systemId: file:///home/me/dev/projects/liferay-portal-7.3.x/modules/apps/segments/segments-service/service.xml; lineNumber: 2; columnNumber: 141; parsing initialization error: org.gjt.xpp.XmlPullParserException: <![DOCTYPE declarations not supported at line 2 and column 141 seen ...//www.liferay.com/dtd/liferay-service-builder_7_3_0.dtd"... (parser state UNKNONW_EVENT (-1))
        at org.gjt.xpp.sax2.Driver.parse(Driver.java:304)
        at org.dom4j.io.SAXReader.read(SAXReader.java:494)
        ... 5 more
Caused by: org.gjt.xpp.XmlPullParserException: <![DOCTYPE declarations not supported at line 2 and column 141 seen ...//www.liferay.com/dtd/liferay-service-builder_7_3_0.dtd"... (parser state UNKNONW_EVENT (-1))
        at org.gjt.xpp.impl.pullparser.PullParser.next(PullParser.java:742)
        at org.gjt.xpp.sax2.Driver.parse(Driver.java:294)
        ... 6 more
```

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian @julschong A quick update:

## Classpath issue

It seems the `SAXReader` created and used by `WSDDBuilder -> ToolsUtil` is using an unexpected `XMLReader` implementation `org.gjt.xpp.sax2.Driver` from `pull-parser.jar`. This jar is an optional dependency of both Dom4J 1.x and 2.x.

A quick proof is to remove this `pull-parser.jar` from `tools/sdk/dependencies/com.liferay.portal.wsdd.builder/lib/`, and run `ant build-wsdd-portal` in portal-impl. If not removed, this task fails with exactly the same error; if removed, this task finishes successfully.

However, removing it from the lib dir doesn't help with `WSDDBuilder` called from Gradle, because the Gradle plugin uses its own resolved classpath.

## Why validation is not disabled

It seems the unexpected `org.gjt.xpp.sax2.Driver` does not support this feature `"http://apache.org/xml/features/validation/schema-full-checking"` which is set by our `SAXReaderFactory`. So an exception is thrown during the `SAXReader` creation, and our factory falls back to creating the `SAXReader` without any feature being set.

**Comment by dantewang** [comment]
@julschong @tinatian By the way,

> New Testing update at 5:42pm PST:
> on master without reverting the commits, if we remove all jars inside 7.3.x tools lib, then copy only the wsdd jar in,
> ant build-wsdds passes

This might not be true. I tried the same thing, and ran `build-wsdds`. Only the builds executed by Ant passed; the Gradle task still fails (because it resolves the class path from its cache).

## Possible solutions I can think of

1. Enforce the `WSDDBuilder` to use `SAXParserFactory` from the JDK or `xercesImpl`.
2. Disable transitive dependency resolution in the `WSDDBuilderPlugin` (see `com.liferay.gradle.plugins.wsdd.builder.WSDDBuilderPlugin#addDependenciesWSDDBuilder`); instead, add only necessary dependencies one by one.

**Comment by dantewang** [comment]
@tinatian A quick fix is at https://github.com/liferay-core-infra/liferay-portal/pull/3389

**Comment by julschong** [comment]
closing this PR, per Brian, he reverted my original commits first. Will send in with the quick fix at #3389 again

**Pull request closed without merging**
