### PR TITLE
LPS-199486 Merge OrganizationMembershipPolicyFactoryUtil into OrganizationMembershipPolicyUtil

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Shuyang,

This is for ticket https://liferay.atlassian.net/browse/LPS-199486.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Review by dantewang — CHANGES_REQUESTED** [review]
@jeffwu0724 Please document breaking change.

**Comment by jeffwu0724** [comment]
upgraded the commit message with breaking change info

**Comment by catarineaguiar** [comment]
@jeffwu0724 semver error:

```
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.security.membershippolicy MAJOR      1.0.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
     [exec] 	-   class      com.liferay.portal.kernel.security.membershippolicy.OrganizationMembershipPolicyFactoryUtil
     [exec] 		-   method     <init>()
     [exec] 			-   return     void
     [exec] 		-   method     clone()
     [exec] 			-   access     protected
     [exec] 			-   return     java.lang.Object
     [exec] 		-   method     equals(java.lang.Object)
     [exec] 			-   return     boolean
     [exec] 		-   method     finalize()
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     getOrganizationMembershipPolicy()
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.security.membershippolicy.OrganizationMembershipPolicy
     [exec] 		-   method     getOrganizationMembershipPolicyFactory()
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.security.membershippolicy.OrganizationMembershipPolicyFactory
     [exec] 		-   method     hashCode()
     [exec] 			-   return     int
     [exec] 		-   method     setOrganizationMembershipPolicyFactory(com.liferay.portal.kernel.security.membershippolicy.OrganizationMembershipPolicyFactory)
     [exec] 			-   return     void
     [exec] 		-   method     toString()
     [exec] 			-   return     java.lang.String
     [exec] 	-   class      com.liferay.portal.kernel.security.membershippolicy.OrganizationMembershipPolicyUtil
     [exec] 		-   method     <init>()
     [exec] 			-   return     void
     [exec] 		-   method     checkMembership(long[],long[],long[])
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 		-   method     checkRoles(java.util.List,java.util.List)
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 		-   method     clone()
     [exec] 			-   access     protected
     [exec] 			-   return     java.lang.Object
     [exec] 		-   method     equals(java.lang.Object)
     [exec] 			-   return     boolean
     [exec] 		-   method     finalize()
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     hashCode()
     [exec] 			-   return     int
     [exec] 		-   method     isMembershipAllowed(long,long)
     [exec] 			-   access     static
     [exec] 			-   return     boolean
     [exec] 		-   method     isMembershipProtected(com.liferay.portal.kernel.security.permission.PermissionChecker,long,long)
     [exec] 			-   access     static
     [exec] 			-   return     boolean
     [exec] 		-   method     isMembershipRequired(long,long)
     [exec] 			-   access     static
     [exec] 			-   return     boolean
     [exec] 		-   method     isRoleAllowed(long,long,long)
     [exec] 			-   access     static
     [exec] 			-   return     boolean
     [exec] 		-   method     isRoleProtected(com.liferay.portal.kernel.security.permission.PermissionChecker,long,long,long)
     [exec] 			-   access     static
     [exec] 			-   return     boolean
     [exec] 		-   method     isRoleRequired(long,long,long)
     [exec] 			-   access     static
     [exec] 			-   return     boolean
     [exec] 		-   method     propagateMembership(long[],long[],long[])
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 		-   method     propagateRoles(java.util.List,java.util.List)
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 		-   method     toString()
     [exec] 			-   return     java.lang.String
     [exec] 		-   method     verifyPolicy()
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 		-   method     verifyPolicy(com.liferay.portal.kernel.model.Organization)
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 		-   method     verifyPolicy(com.liferay.portal.kernel.model.Organization,com.liferay.portal.kernel.model.Organization,java.util.List,java.util.List,java.util.Map)
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 		-   method     verifyPolicy(com.liferay.portal.kernel.model.Role)
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 		-   method     verifyPolicy(com.liferay.portal.kernel.model.Role,com.liferay.portal.kernel.model.Role,java.util.Map)
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 	-   interface  com.liferay.portal.kernel.security.membershippolicy.OrganizationMembershipPolicyFactory
     [exec] 		-   access     abstract
     [exec] 		-   method     getOrganizationMembershipPolicy()
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.portal.kernel.security.membershippolicy.OrganizationMembershipPolicy
     [exec] [Baseline Report] Mode: diff (persisted)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-28/test-portal-acceptance-pullrequest(master)/7958/functional-smoke-tomcat90-postgresql153-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by catarineaguiar** [comment]
@jeffwu0724 please, resolve conflicts after review and re-run tests.

**Pull request closed without merging**
