### PR TITLE
LPS 151094 Remove _getProxyProviderFunction in model_impl for 7.2.0 and later versions

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @tinatian @dantewang,

This pull is to remove `_getProxyProviderFunction` support in 7.2 and later versions. We have  `ProxyUtil.getProxyProviderFunction() `since 7.2.0 release f498da072006bee598b304f85ce235c4b803b0c6. thanks

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@JanisZhang Service builder is making changes when run on this PR: https://testray.liferay.com/reports/production/logs/2022-04/test-1-29/test-portal-acceptance-pullrequest(master)/2393/service-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0

@tinatian No other regressions found.

**Comment by tinatian** [comment]
@JanisZhang Please run "ant setup-profile-dxp" to set up dxp environment, then build your service builder and regenerate the service.



Tina.

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test

**Comment by vicnate5** [comment]
@tinatian No regressions found in new results.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115928

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
