### PR TITLE
[Spring Beans] LPS-201150 Merge LayoutBranchPermission and LayoutBranchPermissionImpl into LayoutBranchPermissionUtil and move it into portal-impl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(11/13 9:20)

**Comment by W2jx** [comment]
no conflicts(11/14 15:49)

**Comment by W2jx** [comment]
no conflicts(11/15 10:19)

**Comment by W2jx** [comment]
no conflicts(11/17 8:18)

**Comment by W2jx** [comment]
no conflicts(11/20 13:57)

**Comment by W2jx** [comment]
no conflicts(11/21 15:06)

**Comment by W2jx** [comment]
no conflicts(11/22 15:05)

**Comment by dantewang** [comment]
@W2jx This one also uses local service, could you check if it's possible to move to module? Thanks!

**Pull request closed without merging**
