### PR TITLE
LPS-145905

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian, @shuyangzhou ,

I have removed unused properties "Pop.server.notifications.interval", and updated to propskeys.java, propsvalues.java and verifyproperties.java.
It was added the usage in commit 1c81a651dc0824537295fc579f2076550b8cc6e2, see LPS-8841.
It was deleted in commit 39f257932857b5b5e80b693661ef4abab541ef4b, see LPS-56173
Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.
@jeffwu0724 Code looks good to me, wait for QA to scan test results.

Tina.

**Comment by vicnate5** [comment]
@Hijky Can you check the results here?

**Comment by Hijky** [comment]
None of the failed cases are relevant

**Pull request closed without merging**
