### PR TITLE
LPS-160230 Patch Freemarker to not use Introspector when filling propertySetters map

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:reevaluate:1317401_4777

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@guilhermedcamacho no regressions found.

**Comment by guilhermedcamacho** [comment]
@shuyangzhou , this PR is ready for your review. Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122465

**Pull request closed without merging**
