### PR TITLE
[LPS-167246 MessageBus] LPS-192568 Clean up use of method destination.destroy()

### PR DESCRIPTION
**Pull request by W2jx**
Hi @dantewang , I have sent the pr about method destination.destroy().

Issue : https://liferay.atlassian.net/browse/LPS-192568

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:help

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(8/4 14:56)

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5205

**Pull request closed without merging**
