### PR TITLE
LPS-167051 fix cannot auto generate versions.html by running "ant build-lib-versions"

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, shuyang,

This PR is to fix the bug that when we run "ant build-lib-versions", versions.html cannot be generated probably.
When we run
`TransformerFactory transformerFactory = SecureXMLFactoryProviderUtil.newTransformerFactory();`
it will throw NPE because we didn't call setSecureXMLFactoryProvider in ahead.
It is caused by https://issues.liferay.com/browse/LPS-167051
Thanks for checking!

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by jeffwu0724** [comment]
Hey @Kvale1733 ,
Could you please help me to add a test to check if this fix can make sure we can generate and update both **versions.html** and **versions-complete.xml** when we run `ant build-lib-versions`, please?

When we run `ant build-lib-versions`
Actual Result: Only **versions-complete.xml** get updated
Expect Result: Both **versions.html** and **versions-complete.xml** get updated
Thanks a lot!

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125994

**Pull request closed without merging**
