### PR TITLE
LPS-172441 upgrade snakeyaml to 2.0

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

Resent: https://github.com/liferay-core-infra/liferay-portal/pull/4207
In this solution, since when we compileIncldue vulcan-api in portal-tools-rest-builder, it will expand the jar from vulcan-api to the root of portal-tools-rest-builder. Therefore, we can exclude [META-INF/versions/9/module-info.class] from snakeYAML 2.0 in vulcan-api by using "includeresource", and when we use snakeYAML in portal-tools-rest-builder, [META-INF/versions/9/module-info.class] has been excluded.

This is for ticket https://issues.liferay.com/browse/LPS-172441.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
Hi Team,

could you please make sure the regression mentioned here https://liferay.slack.com/archives/C02S77ZG8HY/p1680858190865439?thread_ts=1680798217.762509&cid=C02S77ZG8HY is not showing again, please?
Thanks!

**Comment by catarineaguiar** [comment]
@jeffwu0724 I think the channel is private, could you please send the message, so I can test it here?
Thanks

**Comment by jeffwu0724** [comment]
Hi @catarineaguiar ,

Sorry for the inconvenience. Below is the text:

Can't read [/opt/dev/projects/github/liferay-portal-ee/.gradle/caches/modules-2/files-2.1/com.liferay(;;;;;!**org.glassfish.jaxb.runtime**;!**javax**)] (Can't process class [META-INF/versions/9/module-info.class] (Unsupported class version number [53.0] (maximum 52.0, Java 1.8)))

**Comment by Kvale1733** [comment]
@jeffwu0724 Regressions found

1) com.liferay.portal.vulcan.internal.batch.engine.test.VulcanBatchEngineTaskItemDelegateRegistryTest
```
 [exec] com.liferay.portal.vulcan.internal.batch.engine.test.VulcanBatchEngineTaskItemDelegateRegistryTest > testRegistryAndOpenAPIUtilToGetEntityMetadata FAILED
     [exec]     java.lang.NoClassDefFoundError: org/yaml/snakeyaml/events/Event
     [exec]     	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createGenerator(YAMLFactory.java:445)
     [exec]     	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createGenerator(YAMLFactory.java:395)
     [exec]     	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createGenerator(YAMLFactory.java:14)
     [exec]     	at com.fasterxml.jackson.databind.ObjectWriter.createGenerator(ObjectWriter.java:704)
     [exec]     	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1086)
     [exec]     	at io.swagger.v3.core.util.Yaml.pretty(Yaml.java:23)
     [exec]     	at com.liferay.portal.vulcan.internal.resource.OpenAPIResourceImpl._toResponse(OpenAPIResourceImpl.java:1337)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10699/modules-integration-mysql57-jdk8/3/9/jenkins-console.txt.gz?authuser=0)

2) com.liferay.batch.planner.rest.resource.v1_0.test.PlanResourceTest
```
 [exec] com.liferay.batch.planner.rest.resource.v1_0.test.PlanResourceTest > testGetPlanTemplate FAILED
     [exec]     java.lang.AssertionError: Thread Thread[http-nio-8080-exec-7,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.servlet.filters.authverifier.AuthVerifierFilter, message=org.apache.cxf.interceptor.Fault: org/yaml/snakeyaml/events/Event
     [exec]     java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.servlet.filters.authverifier.AuthVerifierFilter, message=org.apache.cxf.interceptor.Fault: org/yaml/snakeyaml/events/Event
     [exec]     	at com.liferay.portal.test.rule.LogAssertionTestRule$LogAppender.append(LogAssertionTestRule.java:330)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
```

```
Caused by: org.apache.cxf.interceptor.Fault: org/yaml/snakeyaml/events/Event
     [exec]     	at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:162)
     [exec]     	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:128)
     [exec]     	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10699/modules-integration-mysql57-jdk8/0/9/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
