### PR TITLE
LPS-158437

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-158437.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
@jeffwu0724 regressions found:

```
 [exec] > Task :apps:object:object-service:processTestResources NO-SOURCE
     [exec] > Task :apps:portal-security-audit:portal-security-audit-event-generators-api:autoUpdateXml SKIPPED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/object/object-service/src/test/java/com/liferay/object/internal/field/filter/parser/ListObjectFieldFilterParserTest.java:52: error: cannot find symbol
     [exec] 			objectViewFilterColumn.getJson()
     [exec] 			                      ^
     [exec]   symbol:   method getJson()
     [exec]   location: variable objectViewFilterColumn of type ObjectViewFilterColumn
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/object/object-service/src/test/java/com/liferay/object/internal/field/filter/parser/ListObjectFieldFilterParserTest.java:71: error: cannot find symbol
     [exec] 			objectViewFilterColumn.getJson()
     [exec] 			                      ^
     [exec]   symbol:   method getJson()
     [exec]   location: variable objectViewFilterColumn of type ObjectViewFilterColumn
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/object/object-service/src/test/java/com/liferay/object/internal/field/filter/parser/ListObjectFieldFilterParserTest.java:96: error: cannot find symbol
     [exec] 			objectViewFilterColumn.getJson()
     [exec] 			                      ^
     [exec]   symbol:   method getJson()
     [exec]   location: variable objectViewFilterColumn of type ObjectViewFilterColumn
     [exec] 3 errors
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-07/test-1-38/test-portal-acceptance-pullrequest(master)/2426/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

`cd modules`
`gw :apps:cookies:cookies-test:compileTestJava`
```
  [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:cookies:cookies-test:compileTestJava'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:208)
     [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:206)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:187)
     [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
     [exec] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-07/test-1-28/test-portal-acceptance-pullrequest(master)/3676/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by catarineaguiar** [comment]
`:apps:portal-remote:portal-remote-json-web-service-web:compileJava` and `:apps:object:object-service:compileTestJava`
```
 [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-remote/portal-remote-json-web-service-web/src/test/java/com/liferay/portal/remote/json/web/service/web/internal/servlet/JSONWebServiceServletTest.java:30: error: cannot find symbol
     [exec] import org.mockito.Matchers;
     [exec]                   ^
     [exec]   symbol:   class Matchers
     [exec]   location: package org.mockito
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-remote/portal-remote-json-web-service-web/src/test/java/com/liferay/portal/remote/json/web/service/web/internal/servlet/JSONWebServiceServletTest.java:90: error: cannot find symbol
     [exec] 			_portal.getCurrentURL(Matchers.any(HttpServletRequest.class))
     [exec] 			                      ^
     [exec]   symbol:   variable Matchers
     [exec]   location: class JSONWebServiceServletTest
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 2 errors
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-07/test-1-28/test-portal-acceptance-pullrequest(master)/3676/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by tinatian** [comment]
@vicnate5 Do we have test for portal-store-s3? If not, could you please verify this manually?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian We have automation and some it of the tests already ran and passed in Relevant, but I am going to trigger the rest here.

@catarineaguiar Could you also check this branch against the new S3 automation you are currently writing?

**Comment by vicnate5** [comment]
ci:test:dl-store

**Comment by catarineaguiar** [comment]
The test I'm working on ran without problems, and the test suite (dl-store) passed.

**Comment by vicnate5** [comment]
@tinatian This is good to go

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/120823

**Pull request closed without merging**
