### PR TITLE
[Remove unused field] LPS-200304 Remove unused reference field in calsses ObjectRelationshipExtensionProvider, OrganizationItemSelectorView, BackgroundTaskManagerImpl and DLFileEntryTypeDLRelationshipResource

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
no conflicts(11/3 9:19)

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
No related issue found in [ci:test:relevant](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2451237696) and [ci:test:startup](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2451205000) suites, wait for the sf result.

**Comment by W2jx** [comment]
no conflicts(11/6 9:12)

**Comment by dantewang** [comment]
ci:test:upgrade

As Shuyang requested, run upgrade test as well for unused reference removal.

cc @W2jx @JanisZhang @zhangyan0701

**Comment by zhangyan0701** [comment]
No regressions found in upgrade tests.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
