### PR TITLE
[Remove Stream/Optional usage] LPS-176635  dynamic-data-mapping-form-web

### PR DESCRIPTION
**Pull request by haydenzheng314**
Ticket: https://issues.liferay.com/browse/LPS-176635
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3703
SF in https://github.com/liferay-core-infra/liferay-portal/pull/3703/commits/f7d2f90055f9b0ee8d16edc2b27d6b9e35544698
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:stop

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
@LisztLiszt No regressions just a Semver issue
```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/dynamic-data-mapping/dynamic-data-mapping-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.dynamic.data.mapping.form.builder.context MAJOR      1.0.1      1.0.1      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.dynamic.data.mapping.form.builder.context.DDMFormBuilderContextRequest
     [exec]     		+   method     with(com.liferay.dynamic.data.mapping.model.DDMStructure,javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse,java.util.Locale,boolean)
     [exec]     			+   access     static
     [exec]     			+   return     com.liferay.dynamic.data.mapping.form.builder.context.DDMFormBuilderContextRequest
     [exec]     		-   method     with(java.util.Optional,javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse,java.util.Locale,boolean)
     [exec]     			-   access     static
     [exec]     			-   return     com.liferay.dynamic.data.mapping.form.builder.context.DDMFormBuilderContextRequest
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 21.0.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertFalse(Assert.java:64)
     [exec]         at com.liferay.semantic.versioning.SemanticVersioningTest.testSemanticVersioning(SemanticVersioningTest.java:82)
     [exec]         at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
 ```
 [Log](https://testray.liferay.com/reports/production/logs/2023-03/test-1-40/test-portal-acceptance-pullrequest(master)/93/modules-semantic-versioning-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
