### PR TITLE
[Remove unused reference] LPS-165470

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove unused fields in `document-library` (MISC). Thanks!

All tests look good in https://github.com/JanisZhang/liferay-portal/pull/153

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by dantewang** [comment]
ci:forward

**Comment by dantewang** [comment]
FYI @shuyangzhou @tinatian

**Comment by JanisZhang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/124749

**Pull request closed without merging**
