### PR TITLE
[Components with more than 1 service] LPS-175886 Refactor DTO Converter components with more than 1 service type from Analytics Cloud and Headless modules

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:headless

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud

**Comment by rafaprax** [comment]
ci:stop

**Pull request closed without merging**
