### PR TITLE
[Phase 1] LPS-178022 Remove Stream and Optional usages for module: portal-search-web part 2

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from https://github.com/liferay-core-infra/liferay-portal/pull/4170
I redid this task and focused only on PortletPreferenceHelper changes instead to reduce the scope
Hopefully, this one works...

regression previously found: https://github.com/liferay-core-infra/liferay-portal/pull/4157#issuecomment-1500183160

@Kvale1733 @zhangyan0701

### CODE REVIEW

**Comment by julschong** [comment]
pushed to rearrange commit [LPS-178022 Remove unused method from SearchStringUtil](https://github.com/liferay-core-infra/liferay-portal/pull/4170/commits/b74471b8329ed8e0592e5c9b5da504ae8f7ad299)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by julschong** [comment]
resubmitted to https://github.com/liferay-core-infra/liferay-portal/pull/4206

**Comment by julschong** [comment]
reopened following Brian's comment: https://github.com/brianchandotcom/liferay-portal/pull/133508#issuecomment-1513005934

rebased and retest ci

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by julschong** [comment]
resubmitted to https://github.com/liferay-core-infra/liferay-portal/pull/4285
added method removal in SearchOptionalUtil

**Pull request closed without merging**
