### PR TITLE
LPS-186928

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:ldap

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
@marianoalvarosaiz No regressions found.

**Comment by tinatian** [comment]
@marianoalvarosaiz Please make CheckArticleSchedulerComponentFactory a LDAPImportConfigurationModelListener directly, I do not understand why you have to have a wrapper to manage LDAPImportConfigurationModelListener.

**Comment by tinatian** [comment]
@marianoalvarosaiz Also, the ticket only mentioned UserImportSchedulerJobConfiguration, why you modify CheckArticleSchedulerJobConfiguration?

**Comment by marianoalvarosaiz** [comment]
@tinatian See https://github.com/liferay-core-infra/liferay-portal/pull/4918, I wrapped it because if not there is a need to use immediate in the component.

Regarding CheckArticleSchedulerJobConfiguration the problem is that the activate method isn't call when the configuration changes, but I will open a new LPS for it.

**Pull request closed without merging**
