### PR TITLE
LPD-8430 Remove unused @Reference variables in QuestionsPortlet.java

### PR DESCRIPTION
**Pull request by Valmir-unicap**
- Ticket: https://liferay.atlassian.net/browse/LPD-8430

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Valmir-unicap** [comment]
ci:report:2544272377

**Comment by dantewang** [comment]
Change looks OK to me, will wait for ci review result.

**Comment by Valmir-unicap** [comment]
No regression found!

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
