### PR TITLE
[Urgent] LPS-65857 Add Auth and Encryption to JGroup cluster configuration

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:clustering

**Comment by dantewang** [comment]
@julschong A lot of clustering tests failed. If the "secure" cluster needs some configuration which can not be provided out-of-box, the tests need to be updated.

@zhangyan0701 Could you take a look and see if these failures are caused by pro-active rejecting?

cc @vicnate5

**Comment by zhangyan0701** [comment]
1. Some WARN messages in portal log should be related:
```
2023-12-12 04:10:45.238 WARN  [SCR Component Actor][JGroupsClusterChannelFactory:224] Clustering authentication is using MD5 default implementation. Please note that this implementation is not secure enough to be used in production. Refer to the documentation for details on configuring secure JGroups connections.
2023-12-12 04:10:45.254 WARN  [SCR Component Actor][JGroupsClusterChannelFactory:271] Clustering authentication is using default cluster link authentication secret. Please configure "cluster.link.auth.secret" property in portal-ext.properties.
```
Example full console log:
https://testray.liferay.com/reports/production/logs/2023-12/test-1-40/test-portal-acceptance-pullrequest(master)/7925/functional-tomcat90-mysql57-jdk8/0/13/jenkins-console.txt.gz?authuser=0

2. The SF failure should also be related:
`[java] The commit message contains the word 'secret', which could reveal potential security vulnerablities. Please see the vulnerability keywords that are specified in source-formatter.properties in the liferay-portal repository.`

Jenkins console:
https://test-1-2.liferay.com/job/test-portal-source-format/1972/console

**Comment by julschong** [comment]
removed any "secret" from portal.properties and commit messages

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:clustering

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:clustering

**Comment by zhangyan0701** [comment]
There are two test failures seem related.

1. Some errors thrown in portal console when restarting nodes.

Reproduce steps:
- Setup a two-node cluster.
- Start both nodes.
- Restart node1. Assert console of node2.
- Restart node2. Assert console of node1.
- Repeat step3 and step4 several times.

Result:
Below error in console:
```
2023-12-13 06:41:49.981 ERROR [jgroups-14,liferay-channel-transport-0,transport-channel-logic-name][ASYM_ENCRYPT:99] transport-channel-logic-name: rejected decryption of unicast message from non-member transport-channel-logic-name-1
2023-12-13 06:44:51.101 ERROR [jgroups-14,liferay-channel-control,control-channel-logic-name-1][ASYM_ENCRYPT:99] control-channel-logic-name-1: rejected decryption of unicast message from non-member control-channel-logic-name
```
Note: The two errors may not occur at the same time, in one restart, there might only one of them show in console.

Affected test:
[LocalFile.Clustering#ShutdownAndStartupNodes](https://testray.liferay.com/home/-/testray/case_results/2473727031)
Full console: https://testray.liferay.com/reports/production/logs/2023-12/test-1-29/test-portal-acceptance-pullrequest(master)/8914/functional-tomcat90-mysql57-jdk8/0/14/jenkins-console.txt.gz?authuser=0

2. There is no console output for property `cluster.link.autodetect.address`.

Reproduce steps:

- No need to prepare two nodes, one bundle is enough to reproduce the issue.
- Add property `cluster.link.enabled=true` in portal-ext.properties.
- Start portal.

Expect Result:
There should be a message in console `Autodetecting JGroups outgoing IP address and interface for www.google.com:80` as www.google.com:80 is the default of property `cluster.link.autodetect.address`.

Actual Result:
No output.

Affected test:
[LocalFile.ClusteringLink#CustomTransportChannelPropertiesFile](https://testray.liferay.com/home/-/testray/case_results/2473753648)
Full console: https://testray.liferay.com/reports/production/logs/2023-12/test-1-29/test-portal-acceptance-pullrequest(master)/8913/functional-tomcat90-mysql57-chrome100-jdk8/2/0/jenkins-console.txt.gz?authuser=0

**Comment by julschong** [comment]
@dantewang @zhangyan0701 
1. Some errors thrown in portal console when restarting nodes.
I tried testing this locally, it seems that it happens when a node 1 is shutting down and it still tries to send data after jgroup channel already closed. When the other node 2 receives this, it thinks node 1 is rogue because it is no longer in the view, so it will drop the message instead of decrypting it.
I'll most likely need some help to solve this case.

2. There is no console output for property cluster.link.autodetect.address.
[1bef981](https://github.com/liferay-core-infra/liferay-portal/pull/6308/commits/1bef981b69b5a7a61552d1ed47f384a6fbc094f5), I just removed this testcase looking for the console output of `Autodetecting JGroups outgoing IP address and interface for www.google.com:80` because I changed the log level of `JGroupsClusterChannelFactory` to ERROR to suppress the default warning message

**Comment by dantewang** [comment]
ci:test:clustering

**Comment by zhangyan0701** [comment]
@julschong 

Portal failed to startup with `cluster.link.enabled=true`:
```
2023-12-14 05:49:07.043 ERROR [main][MainServlet:293] null
java.lang.NullPointerException: null
	at com.liferay.portal.kernel.cluster.ClusterExecutorUtil.execute(ClusterExecutorUtil.java:23) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.cluster.ClusterableInvokerUtil.invokeOnCluster(ClusterableInvokerUtil.java:77) ~[portal-kernel.jar:?]
	at com.liferay.portal.internal.cluster.ClusterableAdvice.afterReturning(ClusterableAdvice.java:45) ~[portal-impl.jar:?]
```
Example full console log:
https://testray.liferay.com/reports/production/logs/2023-12/test-1-27/test-portal-acceptance-pullrequest(master)/10992/functional-tomcat90-mysql57-jdk8/2/3/jenkins-console.txt.gz?authuser=0

BTW, the message `Autodetecting JGroups outgoing IP address and interface for www.google.com:80` showed in console as INFO when I tested locally with the bundle https://github.com/liferay-core-infra/liferay-portal/pull/6308#issuecomment-1855149918 here.

**Comment by julschong** [comment]
@zhangyan0701 Hi Summer,
right, I added the log level in `build-test.xml : prepare-log4j-ext-xml` so the warning messages and the autodetect info message should still show up in normal startup.

The last commit [5c6027b](https://github.com/liferay-core-infra/liferay-portal/pull/6308/commits/5c6027b7fae0f10c6d4b0aff0b05d9ed13a321c6) did not work to fix the issue of  (it only made the build fail...). I think I will need some help from @dantewang or @tinatian to solve this one.

> 1. Some errors thrown in portal console when restarting nodes.
I tried testing this locally, it seems that it happens when a master node 1 is shutting down and it sends data before shutdown. When the other node 2 receives this, it thinks it received a bad message because node 1 is now shut down and not in the view, so it will drop the message instead of decrypting it.
I'll most likely need some help to solve this case.

**Comment by julschong** [comment]
I will close this pull for now

**Comment by dantewang** [comment]
@julschong Found a bug report in a redhat project: https://issues.redhat.com/browse/JBEAP-26125

So this seems to be a normal behavior when using `ASYM_ENCRYPT`.

But http://www.jgroups.org/javadoc/org/jgroups/protocols/ASYM_ENCRYPT.html mentions a "key-server", how did you setup that in this PR?

**Comment by dantewang** [comment]
@zhangyan0701 

> Portal failed to startup with cluster.link.enabled=true

The error message looks like a startup race condition, where `ClusterExecutorUtil` is called even before a `ClusterExecutor` service is available from OSGi.

Does it only happen with this PR?

**Comment by julschong** [comment]
> @julschong Found a bug report in a redhat project: https://issues.redhat.com/browse/JBEAP-26125
> 
> So this seems to be a normal behavior when using `ASYM_ENCRYPT`.
> 
> But http://www.jgroups.org/javadoc/org/jgroups/protocols/ASYM_ENCRYPT.html mentions a "key-server", how did you setup that in this PR?

Thanks Dante!!!
That bug report looks reallysimilar to our issue.


ASYM_ENCRYPT setup doesn't need a key server.
From JGroups Manual here: http://www.jgroups.org/manual4/index.html#ASYM_ENCRYPT
> ASYM_ENCRYPT
Contrary to SYM_ENCRYPT, the secret key is not fetched from a shared keystore, but from the current coordinator C. After new member P joins the cluster, it sends a request to get the secret key (including P’s public key).
C then sends the secret key back to P, encrypted with P’s public key, and P decrypts it with its private key and installs it. From then on, P encrypts and decrypts messages using the secret key.
When a member leaves, C can optionally (based on change_key_on_leave) create a new secret key, and every cluster member needs to fetch it again, using the public/private key exchange described above.

**Comment by dantewang** [comment]
@julschong I guess the error message has something to do with `change_key_on_coord_leave` and `change_key_on_leave`; It seems `change_key_on_coord_leave` is `true` by default.

See the http://www.jgroups.org/manual4/index.html#ENCRYPT ASYM_ENCRYPT part.

**Comment by julschong** [comment]
@dantewang sounds like it. from the bug ticket:
> I am afraid this is standard behavior of ASYN_ENCRYPT that it relies on retransmission when the key changes. I remember this was improved in the past and I think I we may have even written upstream test for this behavior, I ll have a look.

I will change those to false and test again tomorrow. Hopefully, it'll work. 
But would not changing key when member leaves have any security implication?

**Comment by dantewang** [comment]
@julschong In a cluster, there must be 1 node which is the coordinator. With `change_key_on_coord_leave` enabled, when this node leaves, a new coordinator will be elected, and a new key will be generated. Then I guess, according to the above bug report, ff during this process, the node is decrypting a message received before the new key generation, then this message will be rejected.

And yes, of course, disabling these things will make the cluster less secure. If we want max security, we should even enable `change_key_on_leave`, which will result with more error logs.

I think this is a limitation with the current JGroups we're using. We can't know what the "improved" mentioned in the JBEAP ticket is, we can only try to workaround it or document it. But maybe filing a bug report to JGroups (JGRP) can help -- belaban is pretty active and responsive.

**Comment by zhangyan0701** [comment]
> @zhangyan0701
> 
> > Portal failed to startup with cluster.link.enabled=true
> 
> The error message looks like a startup race condition, where `ClusterExecutorUtil` is called even before a `ClusterExecutor` service is available from OSGi.
> 
> Does it only happen with this PR?

Yes, I only see the error in this PR, and all clustering functional tests failed due to it.

**Pull request closed without merging**
