### PR TITLE
[Remove Blocking usages]LPS-193319 portal-kernel | WorkflowDefinitionManagerUtil 

### PR DESCRIPTION
**Pull request by JanisZhang**
rebase and fixed regression. thanks!

previous:https://github.com/liferay-core-infra/liferay-portal/pull/5242

https://liferay.atlassian.net/browse/LPS-193319

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:workflow

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
no regressions found

**Pull request closed without merging**
