### PR TITLE
[TS]LPS-164385 Template engine should not have hard dependency on portal …

### PR DESCRIPTION
**Pull request by tinatian**
…cache as it is going to work without cache, use PortalCacheHelperUtil which use DynamicPortalCache to make sure the dependency is optional and when portal cache is ready, we can still use it.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
@yuhai Please verify if this fix works.

Thanks
Tina.

**Comment by yuhai** [comment]
> …cache as it is going to work without cache, use PortalCacheHelperUtil which use DynamicPortalCache to make sure the dependency is optional and when portal cache is ready, we can still use it.

@tinatian, passed by manual test. Thanks.

**Comment by Kvale1733** [comment]
@tinatian 

No regressions. Only a semver issue.
```
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.template                        MAJOR      8.0.0      8.0.0      9.0.0      VERSION INCREASE REQUIRED
[beanshell] 	>   class      com.liferay.portal.template.BaseTemplateResourceCache
[beanshell] 		-   method     init(long,com.liferay.portal.kernel.cache.MultiVMPool,com.liferay.portal.kernel.cache.SingleVMPool,java.lang.String,java.lang.String)
[beanshell] 			-   access     protected
[beanshell] 			-   return     void
[beanshell] 		+   method     init(long,java.lang.String,java.lang.String)
[beanshell] 			+   access     protected
[beanshell] 			+   return     void
[beanshell] 
```
[Log](https://testray.liferay.com/reports/production/logs/2023-02/test-1-27/test-portal-acceptance-pullrequest(master)/6861/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130014

**Pull request closed without merging**
