### PR TITLE
LPS-183594  move portal-upload to modules part 3

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Shuyang,

Resent: https://github.com/liferay-core-infra/liferay-portal/pull/5702
In this PR, I am trying to move all the portal-upload usage from portal-impl to modules, and also update the release entry remapping as said in https://github.com/liferay-core-infra/liferay-portal/pull/5702#issuecomment-1759817518
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:object

**Comment by jeffwu0724** [comment]
ci:test:upgrade

**Comment by jeffwu0724** [comment]
ci:test:object

**Comment by jeffwu0724** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found. Just semver issues.
```
  [echo] ## /opt/dev/projects/github/liferay-portal/baseline-reports/portal-impl.log
     [echo] ##
     [echo] 
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.util                            MAJOR      56.1.0     56.0.0     57.0.0     VERSION INCREASE REQUIRED
[beanshell] 	>   class      com.liferay.portal.util.PortalImpl
[beanshell] 		-   method     getUploadPortletRequest(javax.portlet.PortletRequest)
[beanshell] 			-   return     com.liferay.portal.kernel.upload.UploadPortletRequest
[beanshell] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest)
[beanshell] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
[beanshell] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest,int,java.lang.String)
[beanshell] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
[beanshell] 	<   class      com.liferay.portal.util.PropsValues
[beanshell] 		+   field      UPGRADE_REPORT_DIR
[beanshell] 			+   access     final
[beanshell] 			+   access     static
[beanshell] 			+   return     java.lang.String
[beanshell] 	-   version    56.0.0
[beanshell] 	+   version    56.1.0
[beanshell] [Baseline Warning] Bundle Version Change Recommended: 92.0.0
[beanshell] 
     [echo] 
     [echo] ##
     [echo] ## /opt/dev/projects/github/liferay-portal/baseline-reports/portal-kernel.log
     [echo] ##
     [echo] 
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.kernel.util                     MAJOR      67.1.0     67.0.0     68.0.0     VERSION INCREASE REQUIRED
[beanshell] 	>   class      com.liferay.portal.kernel.util.PortalUtil
[beanshell] 		-   method     getUploadPortletRequest(javax.portlet.PortletRequest)
[beanshell] 			-   access     static
[beanshell] 			-   return     com.liferay.portal.kernel.upload.UploadPortletRequest
[beanshell] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest)
[beanshell] 			-   access     static
[beanshell] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
[beanshell] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest,int,java.lang.String)
[beanshell] 			-   access     static
[beanshell] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
[beanshell] 	>   interface  com.liferay.portal.kernel.util.Portal
[beanshell] 		-   method     getUploadPortletRequest(javax.portlet.PortletRequest)
[beanshell] 			-   access     abstract
[beanshell] 			-   return     com.liferay.portal.kernel.upload.UploadPortletRequest
[beanshell] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest)
[beanshell] 			-   access     abstract
[beanshell] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
[beanshell] 		-   method     getUploadServletRequest(javax.servlet.http.HttpServletRequest,int,java.lang.String)
[beanshell] 			-   access     abstract
[beanshell] 			-   return     com.liferay.portal.kernel.upload.UploadServletRequest
[beanshell] 	<   interface  com.liferay.portal.kernel.util.PropsKeys
[beanshell] 		+   field      UPGRADE_REPORT_DIR
[beanshell] 			+   access     final
[beanshell] 			+   access     static
[beanshell] 			+   constant   upgrade.report.dir
[beanshell] 			+   return     java.lang.String
[beanshell] 	-   version    67.0.0
[beanshell] 	+   version    67.1.0
[beanshell] 
[stopwatch] [run.batch.test.action: 4.366 sec]
     [echo] Semantic versioning is incorrect.
      [get] Getting: http://test-1-36/job/test-
```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-33/test-portal-acceptance-pullrequest(master)/4499/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
@jeffwu0724 Oh I posted just as you closed.

**Comment by jeffwu0724** [comment]
oops, thanks @Kvale1733  for checking! I thought I find out weird change in my PR but it happened I was wrong.
I am going to reopen it now.
Thanks for chekcing!

**Review by dantewang — CHANGES_REQUESTED** [review]
@jeffwu0724 Please document breaking changes in messages of corresponding commits that cause the major version bump.

**Comment by jeffwu0724** [comment]
upgraded the commit message with breaking change info

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
I did not review the whole thing, but at least https://github.com/liferay-core-infra/liferay-portal/pull/5786/commits/870ce5d0237a5cd7918b461f36329479fb7120c5 can not be right.
`LiferayInputStream` `LiferayServletRequest` and `ServletFileUpload` has no reason to be inside portal-upload-api, they are not consumed by any production module other than testing modules.

Also the pull is too big, try to break it into smaller pieces to make it easier to pass through review.

**Pull request closed without merging**
