### PR TITLE
LPS-171056 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 Please help me to add functional test. @IstvanD Please verify if my change fixes your issue.

Thanks.
Tina

**Comment by IstvanD** [comment]
> @vicnate5 Please help me to add functional test. @IstvanD Please verify if my change fixes your issue.
> 
> Thanks. Tina

Hi @tinatian unfortunately, these changes didn't solve the issue.

**Comment by vicnate5** [comment]
@Kvale1733 Can you add a functional test for this? Even if this isn't the solution yet, would be good to get the test in.

**Comment by IstvanD** [comment]
Hello,

A working solution can be found in this [pull request](https://github.com/liferay-core-infra/liferay-portal/pull/2862).
I think that once the functional test is ready, it can be applied to that fix.

**Comment by Kvale1733** [comment]
@tinatian Resent with functional test.

See: https://github.com/liferay/liferay-portal/pull/5189

**Comment by Kvale1733** [comment]
ci:close

**Comment by Kvale1733** [comment]
@tinatian Resent with functional test. 

See: https://github.com/liferay-core-infra/liferay-portal/pull/2958

**Pull request closed without merging**
