### PR TITLE
LPS-165978 Remove "immediate = true" from Data Integration

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:data-integration

**Comment by Kvale1733** [comment]
@RenanUmV No regressions found.

**Comment by RenanUmV** [comment]
@Kvale1733  I talked to @rafaprax and and I've had to undo some changes, because they could create problems and possibly not be covered by tests.

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:data-integration

**Comment by Kvale1733** [comment]
@RenanUmV No regressions found.

**Comment by shuyangzhou** [comment]
@RenanUmV @rafaprax this https://github.com/liferay-core-infra/liferay-portal/pull/2105/commits/dd4033d7d6831d6cc1656bef3e9f61b6d8c31900 should not be needed. https://github.com/liferay/liferay-portal/blob/56a2d5abf578c80e81ddc78dada6ea6e1abe43e8/modules/apps/portal/portal-messaging/src/main/java/com/liferay/portal/messaging/internal/DefaultMessageBus.java#L347 should have brought up all the message listener service already. The previous broken case is all about the component does not declare message listener as service type.

Please confirm.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125089

**Pull request closed without merging**
