### PR TITLE
[TS] LPS-145396 - TESTS

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Hi @dantewang

TESTS of https://issues.liferay.com/browse/LPS-145396 - When we delete some types of objects in Liferay, we are not deleting their ResourcePermission records, leaving some orphan data in the ResourcePermission table.

Continuation of previous pull request https://github.com/liferay-core-infra/liferay-portal/pull/1020

I have followed the guidelines of your Slack message:

**First change:**

> _Instead of ruling out every false positive, is it possible to think of stricter rules for real positives, even if the rules may miss something? We think this can make the code safer, simpler and cleaner._

Now the code is only testing the entries with scope = SCOPE_INDIVIDUAL, primary key = 0 and name is a className in the persistedModelLocalServices map. We are leaving out some cases but this is simpler.
For more information see https://github.com/liferay-core-infra/liferay-portal/blob/da1acb25e19d504d448c20f630c036ae2af6a0d8/portal-test/src/com/liferay/portal/kernel/test/rule/DataGuardTestRuleUtil.java#L377-L384

**Second change:**

> _For your addition of ResourcePermissionTestUtil.deleteResourcePermissions to the test rules, could you see if it can be avoided with the stricter rules? If not, then could you see if it can be reduced only to the fallback delete method invocation_

I have moved the `ResourcePermissionTestUtil.deleteResourcePermissions` call to the fallback code in the `catch (Throwable throwable1) {` section. After doing this change, I had to fix some false positives in these PRs: https://github.com/liferay-lima/liferay-portal/pull/3417, https://github.com/liferay-appsec/liferay-portal/pull/821 and https://github.com/liferay-commerce/liferay-portal/pull/2981

**Third change:**

I have also changed the `DeleteAfterTestRunMethodTestRule` code, to reuse the smartDelete logic from `DataGuardTestRuleUtil`, see https://github.com/liferay-core-infra/liferay-portal/commit/f3cbbbfbd5c5a55a89e9513761087faac6dc20de

Let me know if you have any question.

Regards,
Jorge

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
Rebased to latest master to avoid a conflict in `portal-test/bnd.bnd`

**Comment by jorgediaz-lr** [comment]
Hi @dantewang do you have any update about this PR?

**Comment by jorgediaz-lr** [comment]
Rebased to latest master to avoid a conflict in `portal-test/bnd.bnd`

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@jorgediaz-lr semver error:

```
 [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.json                     MAJOR      10.1.0     10.1.0     11.0.0     VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.portal.kernel.json.JSONUtil
     [exec] 		+   method     toJSONArray(java.util.Collection,com.liferay.petra.function.UnsafeFunction)
     [exec] 			+   access     static
     [exec] 			+   return     com.liferay.portal.kernel.json.JSONArray
     [exec] 		+   method     toJSONArray(java.util.Collection,com.liferay.petra.function.UnsafeFunction,com.liferay.portal.kernel.log.Log)
     [exec] 			+   access     static
     [exec] 			+   return     com.liferay.portal.kernel.json.JSONArray
     [exec] 		+   method     toJSONArray(java.util.Collection,com.liferay.petra.function.UnsafeFunction,java.util.function.Consumer)
     [exec] 			+   access     static
     [exec] 			+   return     com.liferay.portal.kernel.json.JSONArray
     [exec] 		-   method     toJSONArray(java.util.List,com.liferay.petra.function.UnsafeFunction)
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.json.JSONArray
     [exec] 		-   method     toJSONArray(java.util.List,com.liferay.petra.function.UnsafeFunction,com.liferay.portal.kernel.log.Log)
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.json.JSONArray
     [exec] 		-   method     toJSONArray(java.util.List,com.liferay.petra.function.UnsafeFunction,java.util.function.Consumer)
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.json.JSONArray
     [exec] 		-   method     toJSONArray(java.util.Set,com.liferay.petra.function.UnsafeFunction)
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.json.JSONArray
     [exec] 		-   method     toJSONArray(java.util.Set,com.liferay.petra.function.UnsafeFunction,com.liferay.portal.kernel.log.Log)
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.json.JSONArray
     [exec] 		-   method     toJSONArray(java.util.Set,com.liferay.petra.function.UnsafeFunction,java.util.function.Consumer)
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.json.JSONArray
     [exec] [Baseline Warning] Bundle Version Change Recommended: 77.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/76.0.0/b09a9388ef89da49db51e667b16705f857ec2ce8/com.liferay.portal.kernel-76.0.0.jar
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-30/test-portal-acceptance-pullrequest(master)/4714/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jorgediaz-lr** [comment]
Hi @catarineaguiar 

I didn't change any file in the `com.liferay.portal.kernel.json` package that is located in **portal-kernel/src/com/liferay/portal/kernel/json** 

The files that I have changed are:

- modules/apps/change-tracking/change-tracking-test/src/testIntegration/java/com/liferay/change/tracking/internal/closure/test/CTClosureFactoryImplTest.java
- portal-test/src/com/liferay/portal/kernel/test/rule/DataGuardTestRuleUtil.java
- portal-test/src/com/liferay/portal/kernel/test/rule/DeleteAfterTestRunMethodTestRule.java
- portal-test/src/com/liferay/portal/kernel/test/util/ResourcePermissionTestUtil.java

So that semver error cannot be caused by this PR.

Regards,
Jorge

**Review by dantewang — APPROVED** [review]
@jorgediaz-lr Sorry for the delay, didn't get time to look into your changes until now. This looks good to me, requesting review from Tina.

**Comment by jorgediaz-lr** [comment]
@dantewang 

Thank you!

**Comment by jorgediaz-lr** [comment]
Hi @dantewang @tinatian 

I have rebased the PR to latest master to avoid a conflict in `portal-test/bnd.bnd`

**Comment by jorgediaz-lr** [comment]
Hi @dantewang @tinatian 

I have rebased the PR to latest master to avoid a conflict in `portal-test/bnd.bnd`

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by jorgediaz-lr** [comment]
I have rebased the PR to latest master to avoid a conflict in `portal-test/bnd.bnd`

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/124402

**Pull request closed without merging**
