### PR TITLE
[Remove Stream/Optional usage] LPS-179116 Fragment

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-179116

Remove leftover usages in module Fragment

### CODE REVIEW

**Comment by chaowang-123** [comment]
Hi @@dantewang
No related suite need to run, could you help to label this as QA Passed when you get a chance? Thanks.

**Comment by chaowang-123** [comment]
ci:test:echo

**Review by dantewang — APPROVED** [review]

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
