### PR TITLE
LPS-196525 escape redirect to an external site

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Shuyang, 

Resent: https://github.com/liferay-core-infra/liferay-portal/pull/5800#discussion_r1370875268
This is for ticket https://liferay.atlassian.net/browse/LPS-196525.
I am trying to escape redirect while accessing external site in control panel.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relavant

**Comment by jeffwu0724** [comment]
Hi team,

There is a steps to check this in https://liferay.atlassian.net/browse/LPS-196525.
I have tested locally, and they seems to not showing the location, and no OPTIONS request and a GET request to example.com.

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
no regressions found.
 
let's wait sf results

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/1/23 10:26am

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/3/23 8:57am

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143218

**Pull request closed without merging**
