### PR TITLE
[Component with its own class name as service type] LPS-197867 Refactor components from dynamic-data-mapping, portal and antivirus modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-197867

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@MrJohn1911 regression found:

```
[beanshell]      [exec] com.liferay.portal.upgrade.test.UpgradeLogAppenderUpgradeClientTest > classMethod FAILED
[beanshell]      [exec]     java.lang.IllegalStateException: Timed out while waiting for service (no type) component.name=com.liferay.portal.upgrade.internal.recorder.UpgradeRecorder
[beanshell]      [exec]     	at com.liferay.portal.test.rule.InjectTestBag._getServiceReference(InjectTestBag.java:190)
[beanshell]      [exec]     	at com.liferay.portal.test.rule.InjectTestBag.injectFields(InjectTestBag.java:69)
[beanshell]      [exec]     	at com.liferay.portal.test.rule.InjectTestRule.beforeClass(InjectTestRule.java:40)
[beanshell]      [exec]     	at com.liferay.portal.test.rule.InjectTestRule.beforeClass(InjectTestRule.java:15)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:45)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-39/test-portal-acceptance-pullrequest(master)/7797/modules-integration-mysql57-jdk8/0/18/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@MrJohn1911 this [failure](https://github.com/liferay-core-infra/liferay-portal/pull/5735#issuecomment-1758202400) is still reproducible. Did you test it locally?

**Comment by catarineaguiar** [comment]
`com.liferay.portal.upgrade.test.UpgradeManagerTest` failed with this same failure

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@MrJohn1911 Regression found for upgrades

Steps to reproduce
1. Import db dump like[ this one](https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.4.13/data-archive/data-archive-portal-mysql.zip)
2. Run upgrade tool

Results: 
```
     [java] 2023-10-16 17:28:26.620 ERROR [main][DBUpgrader:70] null
     [java] java.lang.IllegalStateException: Missing default Store
     [java] 	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:178) [portal-impl.jar:?]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_381]
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_381]
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_381]
     [java] 	at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:45) [com.liferay.portal.tools.db.upgrade.client.jar:?]
     [java] 2023-10-16 17:28:26.628 INFO  [main][Upgra
```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-37/test-portal-acceptance-pullrequest(master)/15015/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
