### PR TITLE
master qa 79796

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-73894

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:stop

**Comment by kyle-miho** [comment]
c

**Comment by kyle-miho** [comment]
Finder should be properly indented, visual bug

**Comment by kyle-miho** [comment]
follow up of https://github.com/liferay-core-infra/liferay-portal/pull/1453

**Review by rafaprax — APPROVED** [review]

**Comment by kyle-miho** [comment]
@tinatian fyi This PR only adds a new entity to portal-tools-service-builder-test-service and then creates a supplementary Poshi testcase for it, so the failures reported are unrelated

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122464

**Pull request closed without merging**
