### PR TITLE
LPS-152502 Remove petra-apache-http-components and use shared-dependencies-apache-http instead

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:acceptance

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
Could you please help me scan the test result?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
@julschong please rename it to shared-dependencies-apache-http-components to match the group name.

**Pull request closed without merging**
