### PR TITLE
[Remove Stream/Optional usage] LPS-173791 module: object-web

### PR DESCRIPTION
**Pull request by JanisZhang**
Ticket: https://issues.liferay.com/browse/LPS-173791
previous: https://github.com/liferay-core-infra/liferay-portal/pull/3220

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
@JanisZhang Regression found

Cannot view Object fields in custom layout

Steps to reproduce:
     1) Go to Control Panel > Objects
     2) Add new object "MyObject" with plural label "MyObjects"
     3) Click on created object MyObject
     4) Go to fields tab
     5) Add new field "Name" of type Text and save
     6) Go to Layouts tab
     7) Add new layout named "Custom Layout"
     8) Click on Custom Layout entry
     9) Check Mark as Default
     10) Go to Layout Tab
     11) Click Add Tab
     12) Name the tab "Test Tab" and save.
     13) On Test Tab click Add Block
     14) Name the block Test Block and save
     15) On Test Block click Add Field
     16) Select Name field and save
     17) Save the Layout
     18) Click on Details Tab
     19) Select Control Panel > Object for Panel Category Key
     20) Publish the object MyObject
     21) Go to Control Panel > Object > MyObjects
     22) Click the Plus button to add new MyObjects Entry
     
  Expected Results: The layout for MyObject entry is shown (The name field appears and users can fill it and save the object)
  Actual Results: The layout is empty and users cannot create a MyObjects entry.
     
Screenshot from 2023-02-07 15-06-46

**Comment by JanisZhang** [comment]
Hi @Kvale1733 ,

By following the steps, it seems like I cannot reproduce it. Could you please help to double-check it? Thanks!

image

cc @dantewang

**Comment by Kvale1733** [comment]
@JanisZhang I have attached a video of the steps. I can still reproduce.
https://user-images.githubusercontent.com/90647688/217606512-8fb9c9a0-fb76-41a7-8379-a5ffb5d0b8fc.mp4

**Comment by JanisZhang** [comment]
Thanks @Kvale1733! I can reproduce it now

**Pull request closed without merging**
