### PR TITLE
[Round 4 Method references Static]Lps 181665

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-181665

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:security

**Comment by zhangyan0701** [comment]
Regression found:

**Captcha image doesn't display when create new account.**
Steps:

1. Open localhost:8080.
2. Click Sign In button.
3. In Login portlet, click Create Account.
4. Scroll page to bottom.

Result: Captcha image doesn't display under VERIFICATION.
Error in portal console:
```
2023-04-18 11:23:19.934 ERROR [http-nio-8080-exec-6][IncludeTag:128] Current URL /web/guest/home?p_p_id=com_liferay_login_web_portlet_LoginPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_login_web_portlet_LoginPortlet_mvcRenderCommandName=%2Flogin%2Fcreate_account&saveLastPath=false generates exception: java.lang.NullPointerException
java.lang.NullPointerException: null
	at com.liferay.captcha.util.CaptchaUtil.isEnabled(CaptchaUtil.java:68) ~[bundleFile:?]
	at org.apache.jsp.captcha.page_jsp._jspService(page_jsp:140) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111) ~[jasper.jar:9.0.73]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:596) ~[servlet-api.jar:4.0.FR]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411) ~[jasper.jar:9.0.73]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473) ~[jasper.jar:9.0.73]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377) ~[jasper.jar:9.0.73]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:596) ~[servlet-api.jar:4.0.FR]
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:328) ~[bundleFile:?]
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:340) ~[bundleFile:?]
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:63) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
	at com.liferay.portal.servlet.DirectServletPathRegisterDispatcher.include(DirectServletPathRegisterDispatcher.java:67) ~[portal-impl.jar:?]
	at com.liferay.portal.servlet.DirectRequestDispatcherFactoryImpl$IndirectRequestDispatcher.include(DirectRequestDispatcherFactoryImpl.java:190) ~[portal-impl.jar:?]
	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:79) ~[portal-impl.jar:?]
	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.include(ClassLoaderRequestDispatcherWrapper.java:53) ~[portal-impl.jar:?]
	at com.liferay.taglib.util.IncludeTag.includePage(IncludeTag.java:409) ~[bundleFile:?]
	at com.liferay.taglib.util.IncludeTag.include(IncludeTag.java:384) ~[bundleFile:?]
```

**Comment by slnn** [comment]
Thank @zhangyan0701 for catching this, will fix and resend.


> Regression found:
> 
> **Captcha image doesn't display when create new account.** Steps:
> 
> 1. Open localhost:8080.
> 2. Click Sign In button.
> 3. In Login portlet, click Create Account.
> 4. Scroll page to bottom.
> 
> Result: Captcha image doesn't display under VERIFICATION. Error in portal console:
> 
> ```
> 2023-04-18 11:23:19.934 ERROR [http-nio-8080-exec-6][IncludeTag:128] Current URL /web/guest/home?p_p_id=com_liferay_login_web_portlet_LoginPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_login_web_portlet_LoginPortlet_mvcRenderCommandName=%2Flogin%2Fcreate_account&saveLastPath=false generates exception: java.lang.NullPointerException
> java.lang.NullPointerException: null
> 	at com.liferay.captcha.util.CaptchaUtil.isEnabled(CaptchaUtil.java:68) ~[bundleFile:?]
> 	at org.apache.jsp.captcha.page_jsp._jspService(page_jsp:140) ~[?:?]
> 	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111) ~[jasper.jar:9.0.73]
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:596) ~[servlet-api.jar:4.0.FR]
> 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411) ~[jasper.jar:9.0.73]
> 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473) ~[jasper.jar:9.0.73]
> 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377) ~[jasper.jar:9.0.73]
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:596) ~[servlet-api.jar:4.0.FR]
> 	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:328) ~[bundleFile:?]
> 	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:340) ~[bundleFile:?]
> 	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
> 	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:63) ~[?:?]
> 	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
> 	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
> 	at com.liferay.portal.servlet.DirectServletPathRegisterDispatcher.include(DirectServletPathRegisterDispatcher.java:67) ~[portal-impl.jar:?]
> 	at com.liferay.portal.servlet.DirectRequestDispatcherFactoryImpl$IndirectRequestDispatcher.include(DirectRequestDispatcherFactoryImpl.java:190) ~[portal-impl.jar:?]
> 	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:79) ~[portal-impl.jar:?]
> 	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.include(ClassLoaderRequestDispatcherWrapper.java:53) ~[portal-impl.jar:?]
> 	at com.liferay.taglib.util.IncludeTag.includePage(IncludeTag.java:409) ~[bundleFile:?]
> 	at com.liferay.taglib.util.IncludeTag.include(IncludeTag.java:384) ~[bundleFile:?]
> ```

**Comment by slnn** [comment]
Please see https://github.com/liferay-core-infra/liferay-portal/pull/4298

**Pull request closed without merging**
