### PR TITLE
LPS-199389 Merge RoleMembershipPolicyFactoryUtil into RoleMembershipPolicyUtil

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong regressions found:

```
[beanshell]      [exec] com.liferay.user.service.persistence.test.UserFinderTest > testCountByKeywordsWithInheritedRoles FAILED
[beanshell]      [exec]     com.liferay.portal.kernel.exception.ModelListenerException: com.liferay.portal.kernel.security.auth.PrincipalException: PermissionChecker not initialized
[beanshell]      [exec]     	at com.liferay.portal.security.audit.event.generators.internal.model.listener.RoleModelListener._auditOnAddOrRemoveAssociation(RoleModelListener.java:189)
[beanshell]      [exec]     	at com.liferay.portal.security.audit.event.generators.internal.model.listener.RoleModelListener.onBeforeAddAssociation(RoleModelListener.java:48)
[beanshell]      [exec]     	at com.liferay.portal.kernel.internal.service.persistence.TableMapperImpl._addTableMapping(TableMapperImpl.java:624)
[beanshell]      [exec]     	at com.liferay.portal.kernel.internal.service.persistence.TableMapperImpl.addTableMapping(TableMapperImpl.java:112)
```
```
[beanshell]      [exec] com.liferay.user.service.test.UserLocalServiceTest > testAuthenticateByEmailAddress FAILED
[beanshell]      [exec]     java.lang.AssertionError: expected:<2> but was:<0>
[beanshell]      [exec]     	at org.junit.Assert.fail(Assert.java:89)
[beanshell]      [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
[beanshell]      [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
[beanshell]      [exec]     	at org.junit.Assert.assertEquals(Assert.java:633)
[beanshell]      [exec]     	at com.liferay.user.service.test.UserLocalServiceTest.testAuthenticateByEmailAddress(UserLocalServiceTest.java:162)
```
```
[beanshell]      [exec] com.liferay.user.service.test.UserLocalServiceTest > testLockout FAILED
[beanshell]      [exec]     com.liferay.portal.kernel.exception.PasswordExpiredException
[beanshell]      [exec]     	at com.liferay.portal.service.impl.UserLocalServiceImpl.doCheckPasswordExpired(UserLocalServiceImpl.java:6010)
[beanshell]      [exec]     	at com.liferay.portal.service.impl.UserLocalServiceImpl._checkPasswordPolicy(UserLocalServiceImpl.java:7051)
[beanshell]      [exec]     	at com.liferay.portal.service.impl.UserLocalServiceImpl.authenticate(UserLocalServiceImpl.java:5820)
[beanshell]      [exec]     	at com.liferay.portal.service.impl.UserLocalServiceImpl.authenticateByEmailAddress(UserLocalServiceImpl.java:1516)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-34/test-portal-acceptance-pullrequest(master)/4833/modules-integration-mysql57-jdk8/4/12/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine, could you see if this is the cause of the regression?

**Comment by catarineaguiar** [comment]
@julschong the first failure seems similar, I will update the comment. Thanks!

**Comment by julschong** [comment]
@catarineaguiar it passes locally when testing indivudually, I'm testing with this test group right now to try
```
TEST_CLASS_GROUP_0=\
		com/liferay/portal/search/elasticsearch7/internal/search/engine/adapter/index/GetMappingIndexRequestExecutorTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/search/engine/adapter/index/IndicesExistsIndexRequestExecutorTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/search/engine/adapter/index/OpenIndexRequestExecutorTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/search/engine/adapter/index/PutMappingIndexRequestExecutorTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/search/engine/adapter/index/RefreshIndexRequestExecutorTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/search/engine/adapter/index/StatsIndexRequestExecutorTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/search/engine/adapter/index/UpdateIndexSettingsIndexRequestExecutorTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/search/engine/adapter/search/CommonSearchSourceBuilderAssemblerImplTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/search/engine/adapter/snapshot/CreateSnapshotRepositoryRequestExecutorImplTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/search/engine/adapter/snapshot/CreateSnapshotRequestExecutorImplTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/search/engine/adapter/snapshot/DeleteSnapshotRequestExecutorImplTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/search/engine/adapter/snapshot/GetSnapshotRepositoriesRequestExecutorImplTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/search/engine/adapter/snapshot/GetSnapshotsRequestExecutorImplTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/search/engine/adapter/snapshot/RestoreSnapshotRequestExecutorImplTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/sidecar/PathUtilTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/sidecar/UncompressUtilTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/sort/ElasticsearchDocumentSortTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/sort/ElasticsearchMultiLanguageSortTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/sort/ElasticsearchSortFieldTranslatorTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/sort/ElasticsearchSortTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/sort/ElasticsearchSortUnmappedFieldsTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/sort/NestedFieldsSortTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/spellcheck/ElasticsearchSpellCheckTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/stats/StatisticsTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/suggest/ElasticsearchSuggestTest.class,\
		com/liferay/portal/search/elasticsearch7/internal/synonym/SynonymFiltersTest.class,\
		com/liferay/portal/search/solr8/internal/count/SolrCountTest.class,\
		com/liferay/portal/search/solr8/internal/count/SolrDocumentCountTest.class,\
		com/liferay/portal/search/solr8/internal/expando/ExpandoTest.class,\
		com/liferay/portal/search/solr8/internal/facet/AggregationFilteringTest.class,\
		com/liferay/portal/search/solr8/internal/facet/AssetTagNamesFacetTest.class,\
		com/liferay/portal/search/solr8/internal/facet/ClassicModifiedFacetTest.class,\
		com/liferay/portal/search/solr8/internal/facet/FacetCollectorTest.class,\
		com/liferay/portal/search/solr8/internal/facet/ModifiedFacetTest.class,\
		com/liferay/portal/search/solr8/internal/facet/MultiValueFacetTest.class,\
		com/liferay/portal/search/solr8/internal/facet/SimpleFacetTest.class,\
		com/liferay/portal/search/solr8/internal/filter/BooleanFilterTranslatorTest.class,\
		com/liferay/portal/search/solr8/internal/filter/GroupIdQueryPreFilterContributorTest.class,\
		com/liferay/portal/search/solr8/internal/filter/SolrDateRangeFilterTest.class,\
		com/liferay/portal/search/solr8/internal/filter/TermFilterTest.class,\
		com/liferay/portal/search/solr8/internal/filter/TermsFilterTest.class,\
		com/liferay/portal/search/solr8/internal/filter/tags/AssetTagNamesQueryPreFilterContributorTest.class,\
		com/liferay/portal/search/solr8/internal/groupby/GroupByTest.class,\
		com/liferay/portal/search/solr8/internal/highlight/SolrHighlightTest.class,\
		com/liferay/portal/search/solr8/internal/legacy/query/StringQueryTest.class,\
		com/liferay/portal/search/solr8/internal/logging/SolrIndexSearcherExceptionsTest.class
```

**Comment by julschong** [comment]
@catarineaguiar I ran locally with ci command below and passed both of these tests


```
Running: ant -Dtest.name="--tests PhoneTableReferenceDefinitionTest --tests UserJobTitleTableReferenceDefinitionTest --tests UserRatingsTest --tests UserPermissionTest --tests UserFinderTest --tests UserLocalServiceTest --tests UserServiceOrganizationAdminUnsetsUsersForNonSiteOrganizationTest --tests UserServiceOrganizationAdminUnsetsUsersForSiteOrganizationTest --tests UserServiceOrganizationOwnerUnsetsUsersForNonSiteOrganizationTest --tests UserServiceOrganizationOwnerUnsetsUsersForSiteOrganizationTest --tests UserServiceWhenAddingDefaultGroupTest --tests UserServiceWhenAddingOrRemovingPasswordPolicyUsersTest --tests UserServiceWhenAddingUserAcrossCompaniesTest --tests UserServiceWhenAddingUserWithDefaultRolesTest" -Dtest.task=":apps:user:user-test:testIntegration" -Ddir="modules" -f build-common.xml gradle-execute-modules


     [exec] com.liferay.user.service.test.UserLocalServiceTest > testAuthenticateByEmailAddress STARTED
     [exec] 
     [exec] com.liferay.user.service.test.UserLocalServiceTest > testAuthenticateByEmailAddress PASSED

     [exec] com.liferay.user.service.test.UserLocalServiceTest > testLockout STARTED
     [exec] 
     [exec] com.liferay.user.service.test.UserLocalServiceTest > testLockout PASSED


```

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by julschong** [comment]
added breaking change commit messages

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142570

**Pull request closed without merging**
