### PR TITLE
[Startup time optimization] LPS-160884

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to disable auto-import-default-references in calendar-service. Thanks!
https://issues.liferay.com/browse/LPS-160884

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @catarineaguiar , Could you please help to scan the test results? Thanks!

**Comment by catarineaguiar** [comment]
ci:help

**Comment by catarineaguiar** [comment]
ci:test:jdk11

**Comment by catarineaguiar** [comment]
Running jdk11 test suite to verify if the error on relevant was flaky.

**Comment by tinatian** [comment]
@JanisZhang Code looks good to me, wait for QA to scan test results.

Tina

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:jdk11

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
I'm waiting for the testray results.

**Comment by catarineaguiar** [comment]
@tinatian no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.


Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121960

**Pull request closed without merging**
