### PR TITLE
[Remove Spring extender usages] LPS-159168

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

Resend. refer to https://github.com/liferay-core-infra/liferay-portal/pull/1292

This PR is to remove spring extender usage in commerce-currency-service, thanks!
https://issues.liferay.com/browse/LPS-159168

last commit based on: https://github.com/liferay-core-infra/liferay-portal/pull/1222#issuecomment-1204293715

Previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/1222

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:commerce

**Comment by dantewang** [comment]
@JanisZhang Please try to explain a bit more about why we need to override the `setAopProxy` in the message of your last commit. Thanks!

**Comment by JanisZhang** [comment]
Hi @zhangyan0701, I only change the commit message in the force-pushed commit. Could you plz help to scan the test results? thx.  cc @dantewang

**Review by dantewang — APPROVED** [review]
@JanisZhang Approving this PR, but I want you to update the last commit's message again. Please focus on explaining why you need to override `setAopProxy` instead of just doing so in `activate`.

@tinatian Code looks good to me.

**Comment by zhangyan0701** [comment]
No regressions found.

**Pull request closed without merging**
