### PR TITLE
LPD-39874 Revamp environments test suite around recent environment testing changes

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:environments

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:environments

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:environments

**Comment by julschong** [comment]
rebased and retest

**Comment by julschong** [comment]
ci:report:51608088

**Comment by tinatian** [comment]
@julschong Is this waiting for @vicnate5 's review?

**Comment by julschong** [comment]
@tinatian Hi Tina, I just reviewed this PR and it still has some issue with using jdk17_zulu.

**Comment by julschong** [comment]
use jdk17_open instead

**Comment by julschong** [comment]
ci:test:environments

**Comment by julschong** [comment]
looks like the issue is unrelated to whether we use jdk17_open or jdk17_zulu
just that Testray is not importing these correctly. will notify ci, and we can proceed with this pull after switching back to use jdk17_zulu

**Comment by julschong** [comment]
ci side still has issue with using jdk17_zulu. I will notify them on it. for now I will remove jdk11 test batches but not add jdk17 test batch.

will push the change soon

**Comment by julschong** [comment]
ready to go

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:environments

**Comment by julschong** [comment]
good to go

**Comment by julschong** [comment]
ci:forward

**Pull request closed without merging**
