### PR TITLE
[Reference cleanup]LPS-162160

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to convert method references to field references in `dynamic-data-mapping-web`. Thanks!
https://issues.liferay.com/browse/LPS-162160

Previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/1546

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @zhangyan0701, Could you please help to scan the test result? Thank you.

**Comment by JanisZhang** [comment]
Hi @Kvale1733,  Could you please help to scan the test results? Thank you

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by julschong** [comment]
@JanisZhang Hi Janis,
I didnt find any issues with the changes. 

But I still see some method references in `dynamic-data-mapping-web`
Do you need to include them as well?

image

**Comment by julschong** [comment]
Per Tina, it is ok to move on following the google doc list
I will foward this

**Comment by julschong** [comment]
ci:close

**Comment by julschong** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/122926

**Pull request closed without merging**
