### PR TITLE
[Remove Stream/Optional usage] LPS-176378 dynamic-data-mapping-api

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-176378

previous: https://github.com/liferay-core-infra/liferay-portal/pull/3600

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:data-engine

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:data-engine

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by JanisZhang** [comment]
rebase and force-pushed. 
Code conflicts in `bnd` file, it shouldn't affect the test results.

**Pull request closed without merging**
