### PR TITLE
[Method References 2] LPS-166976 LDAPConfigurationListener

### PR DESCRIPTION
**Pull request by JanisZhang**
previous: https://github.com/liferay-core-infra/liferay-portal/pull/3885
https://issues.liferay.com/browse/LPS-166976

code conflicts. resend. Thanks!

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:ldap

**Comment by dantewang** [comment]
@JanisZhang After a second thought, the current solution doesn't seem optimal.

The `ConfigurationProvider` in LDAP was added in Oct 2015, and they are there mainly because we need the configurations to be company-scoped, which is not natively supported by OSGi ConfigAdmin specification.

However, we have a framework to support such scoped configurations. We can obtain a scoped configuration object via a reference to the service of `ConfigurationProvider` in portal-kernel since Feb 2016, just 4 months later.

Please investigate whether we can replace the LDAP `ConfigurationProvider` with the portal settings framework ``ConfigurationProvider`. Let me know if you face any problem in this process.

Thanks!

**Comment by JanisZhang** [comment]
Hi @dantewang, 
I have tried to replace the LDAP `ConfigurationProvider` with the portal settings framework `ConfigurationProvider`.

For these four LDAP configurations
- LDAPAuthConfiguration
- LDAPExportConfiguration
- LDAPImportConfiguration
- SystemLDAPConfiguration

it should be feasible to replace their usage using 
- `_configurationProvider.get/delete/saveCompanyConfiguration`
- get and update properties via `SettingsLocator`
- ...etc.

But for `LDAPServerConfiguration`, it doesn't `extends CompanyScopedConfiguration`.

Since we can add multiple LDAP servers on `Instance Settings > LDAP > Servers`, some logic in `LDAPServerConfigurationProviderImpl` is much more complicated, including some sort operations and extra maps to collect `pidServerConfigurations` ..etc.  I don't know how to replace it with the portal settings framework ``ConfigurationProvider`.  What do you think :)

Thanks!

**Comment by dantewang** [comment]
@JanisZhang Let's have a discussion at office tomorrow.

**Pull request closed without merging**
