### PR TITLE
[Remove Stream/Optional usage] LPS-172109

### PR DESCRIPTION
**Pull request by dantewang**
Remove leftover usages in module layout-impl

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by zhangyan0701** [comment]
Upgrade from 62 failed with connection timeout error:
```
      [java] 2023-03-23 22:02:06.760 ERROR [ForkJoinPool-17-worker-9][SqlExceptionHelper:142] HikariPool-1 - Connection is not available, request timed out after 600000ms.
     [java] 2023-03-23 22:02:06.753 ERROR [ForkJoinPool-15-worker-15][VerifyResourcePermissions:208] Unable to add resource for {20155, com.liferay.portal.kernel.model.Role, 4, 20168, 20164}
     [java] com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: could not prepare statement
```
Example failed test:
[LocalFile.WebContentUpgrade#PublishDraftWebContentAfterUpgrade625](https://testray.liferay.com/home/-/testray/case_results/2243588557)
Full console log:
https://testray.liferay.com/reports/production/logs/2023-03/test-1-30/test-portal-acceptance-pullrequest(master)/6076/functional-tomcat90-mysql57-jdk8/17/15/jenkins-console.txt.gz?authuser=0

**Comment by dantewang** [comment]
@zhangyan0701 Could you double check? The failure seems to be with Upgrade when calling something not touched by this PR.

**Comment by dantewang** [comment]
The failed tests are reported in https://issues.liferay.com/browse/LPS-179949, which is related to LPS-176210.

**Comment by dantewang** [comment]
ci:forward:force

Changed to QA Passed as the failure is caused by other changes.

cc @shuyangzhou @tinatian

**Pull request closed without merging**
