### PR TITLE
LPS-145582 Avoid using ThemeFactoryUtil directly in modules

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina, Shuyang

Main Task: [LPS-143403](https://issues.liferay.com/browse/LPS-143403)
Sub Task: [LPS-145582](https://issues.liferay.com/browse/LPS-145582)

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
@kyle-miho Hi Kyle,
Could you please help me send this pull?
Thank you!

**Comment by kyle-miho** [comment]
@bronsonsoda can you look at this?
Relevant CSV: https://test-1-1.liferay.com/job/generate-testray-csv/63/
Acceptance CSV: https://test-1-1.liferay.com/job/generate-testray-csv/64/
cc: @vicnate5

**Comment by bronsonsoda** [comment]
@julschong unique functional failures:
[NotificationsUpgrade#ViewNotifications72104](https://testray.liferay.com/home/-/testray/case_results/1651916770/history)
[NotificationsUpgrade#ViewNotifications621021](https://testray.liferay.com/home/-/testray/case_results/1651907783/history)
[NotificationsUpgrade#ViewNotifications71105](https://testray.liferay.com/home/-/testray/case_results/1651907792/history)

Failed locally 

@kyle-miho @vicnate5

**Comment by julschong** [comment]
@bronsonsoda I just rebased and pushed again

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@bronsonsoda
Hi Bronson,
Could you please help me scan again?
Thank you!

cc: @kyle-miho

**Comment by bronsonsoda** [comment]
@julschong no regressions found

 JBoss 7.3, JBoss 7.4, WildFly 23.0, and WildFly 18.0 didn't run due to a blocker upstream
 
 @kyle-miho @vicnate5

**Comment by julschong** [comment]
@tinatian Hi Tina,
Could you please help me review this pull?
Thank you!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115872

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
