### PR TITLE
LPS-161427 Remove stream usage in DDMFormLayoutValidatorImpl

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @catarineaguiar, Can you help me scan these test results? Thx

**Comment by catarineaguiar** [comment]
ci:test:forms

**Comment by catarineaguiar** [comment]
ci:help

**Comment by catarineaguiar** [comment]
@rafaprax no regressions found.

**Comment by rafaprax** [comment]
Hey @shuyangzhou, this pr is ready for your review. Thx

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122446

**Pull request closed without merging**
