### PR TITLE
LPS-145367 Remove htmlparser.jar

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by guilhermedcamacho** [comment]
Hey @vicnate5 , please help me scan test results. Thanks!

**Comment by vicnate5** [comment]
@koor4356 Can you check this?

**Comment by koor4356** [comment]
Okay, thanks!

**Comment by koor4356** [comment]
ci:bundles

**Comment by koor4356** [comment]
ci:bundle

**Comment by koor4356** [comment]
ci:test:bundle

**Comment by koor4356** [comment]
@guilhermedcamacho 
This looks good. Thanks!

**Comment by guilhermedcamacho** [comment]
Hey @shuyangzhou , this PR is ok for your review. Thanks!

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
