### PR TITLE
Lps x finder 3

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:help

**Comment by tinatian** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
ci:test:object

**Comment by catarineaguiar** [comment]
@tinatian regressions found:

```
     [exec] com.liferay.object.service.test.ObjectEntryLocalServiceTest > testGetExtensionDynamicObjectDefinitionTableValues FAILED
     [exec]     java.lang.AssertionError: 
     [exec]     Expected: a string containing "select count(*) COUNT_VALUE from User_x_20096"
     [exec]          but: was null
     [exec]     	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
     [exec]     	at org.junit.Assert.assertThat(Assert.java:964)
     [exec]     	at org.junit.Assert.assertThat(Assert.java:930)
     [exec]     	at com.liferay.object.service.test.ObjectEntryLocalServiceTest._assertCacheKeyPrefixes(ObjectEntryLocalServiceTest.java:2275)
     [exec]     	at com.liferay.object.service.test.ObjectEntryLocalServiceTest.testGetExtensionDynamicObjectDefinitionTableValues(ObjectEntryLocalServiceTest.java:1229)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-04/test-1-40/test-portal-acceptance-pullrequest(master)/1349/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.object.rest.internal.vulcan.extension.v1_0.test.ObjectEntryExtensionProviderTest > testIsApplicableExtension FAILED
     [exec]     java.lang.NullPointerException
     [exec]     	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
     [exec]     	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl.getService(ServiceTrackerMapImpl.java:95)
     [exec]     	at com.liferay.portal.vulcan.internal.dto.converter.DTOMapperImpl.toInternalDTOClassName(DTOMapperImpl.java:40)
     [exec]     	at com.liferay.object.rest.internal.vulcan.extension.v1_0.BaseObjectExtensionProvider.fetchObjectDefinition(BaseObjectExtensionProvider.java:59)
     [exec]     	at com.liferay.object.rest.internal.vulcan.extension.v1_0.BaseObjectExtensionProvider.isApplicableExtension(BaseObjectExtensionProvider.java:44)
     [exec]     	at com.liferay.object.rest.internal.vulcan.extension.v1_0.test.ObjectEntryExtensionProviderTest.testIsApplicableExtension(ObjectEntryExtensionProviderTest.java:118)
```
```
     [exec] com.liferay.object.rest.internal.resource.v1_0.test.RelatedObjectEntryResourceTest > testDeleteManyToManySystemObjectRelatedObjectEntry FAILED
     [exec]     java.lang.AssertionError: expected:<0> but was:<1>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:633)
     [exec]     	at com.liferay.object.rest.internal.resource.v1_0.test.RelatedObjectEntryResourceTest.testDeleteManyToManySystemObjectRelatedObjectEntry(RelatedObjectEntryResourceTest.java:182)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
```
     [exec] com.liferay.object.rest.internal.resource.v1_0.test.ObjectEntryRelatedObjectsResourceTest > testDeleteCustomObjectDefinition1WithCustomObjectDefinition2 FAILED
     [exec]     java.lang.AssertionError: expected:<0> but was:<1>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:633)
     [exec]     	at com.liferay.object.rest.internal.resource.v1_0.test.ObjectEntryRelatedObjectsResourceTest._testDeleteCustomObjectDefinition1WithCustomObjectDefinition2(ObjectEntryRelatedObjectsResourceTest.java:743)
     [exec]     	at com.liferay.object.rest.internal.resource.v1_0.test.ObjectEntryRelatedObjectsResourceTest.testDeleteCustomObjectDefinition1WithCustomObjectDefinition2(ObjectEntryRelatedObjectsResourceTest.java:135)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
```
```
     [exec] com.liferay.object.rest.internal.manager.v1_0.test.DefaultObjectEntryManagerImplTest > testAddObjectEntryAccountEntryRestriction FAILED
     [exec]     com.liferay.portal.kernel.exception.NoSuchListTypeException
     [exec]     	at com.liferay.portal.service.impl.ListTypeLocalServiceImpl.validate(ListTypeLocalServiceImpl.java:84)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
     [exec]     	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
     [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-04/test-1-40/test-portal-acceptance-pullrequest(master)/1349/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
    [exec] com.liferay.object.graphql.test.ObjectDefinitionGraphQLTest > testGetListObjectEntry FAILED
     [exec]     org.junit.ComparisonFailure: expected:<[peter@liferay.com]> but was:<[null]>
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:117)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
     [exec]     	at com.liferay.object.graphql.test.ObjectDefinitionGraphQLTest.testGetListObjectEntry(ObjectDefinitionGraphQLTest.java:223)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
```
     [exec] com.liferay.object.related.models.test.ObjectRelatedModelsProviderTest > testObjectEntryMtoMObjectRelatedModelsProviderImpl FAILED
     [exec]     java.lang.AssertionError: [] expected:<1> but was:<0>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at com.liferay.object.related.models.test.ObjectRelatedModelsProviderTest._testObjectEntryMtoMRelatedModelsProviderImpl(ObjectRelatedModelsProviderTest.java:621)
     [exec]     	at com.liferay.object.related.models.test.ObjectRelatedModelsProviderTest.testObjectEntryMtoMObjectRelatedModelsProviderImpl(ObjectRelatedModelsProviderTest.java:532)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-04/test-1-40/test-portal-acceptance-pullrequest(master)/1349/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.portal.cache.internal.dao.orm.EntityCacheImplTest > testNotifyPortalCacheRemovedPortalCacheName FAILED
     [exec]     java.lang.NoSuchFieldException: No field on null with name _clusterExecutor
     [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.getField(ReflectionTestUtil.java:135)
     [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.setFieldValue(ReflectionTestUtil.java:346)
     [exec]         at com.liferay.portal.cache.internal.dao.orm.EntityCacheImplTest.testNotifyPortalCacheRemovedPortalCacheName(EntityCacheImplTest.java:76)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10459/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4188

**Pull request closed without merging**
