### PR TITLE
[Method References 2] LPS-165133 Remove unused reference variable in module search-experiences-rest-impl(dxp)

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have removed unused reference variable in module search-experiences-rest-impl(dxp).

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by zhangyan0701** [comment]
ci:test:sxp

**Comment by zhangyan0701** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
ci:stop:sxp

**Comment by zhangyan0701** [comment]
ci:test:sxp

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@tinatian The test result passed review, but `FieldMappingInfoResourceImpl` does have a hidden dependency to `JSONFactoryUtil` via `FieldMappingsWebCacheItem.get -> WebCachePoolUtil/Impl.get -> FieldMappingsWebCacheItem.convert -> JSONFactoryUtil`. I think it's safe for now because this `FieldMappingInfoResourceImpl` is not invoked during startup, and `JSONFactory` is a Spring bean which is published early.

Do you think we need to make this reference "used" instead of removing it?

**Comment by tinatian** [comment]
@dantewang Yes, please modify the code to show that the reference is being used.

Tina.

**Pull request closed without merging**
