### PR TITLE
[2/2] LPS-145396 - TESTS

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Hi @tinatian

Same PR than https://github.com/liferay-core-infra/liferay-portal/pull/458 but rebased to latest master code

For more information about my code, review the comments on previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/458#issue-1168655677 and https://github.com/liferay-core-infra/liferay-portal/pull/458#issuecomment-1072589250

Let me know if you have any question.

### CODE REVIEW

**Comment by tinatian** [comment]
@jorgediaz-lr Can you do this?
In _autoDeleteLeftovers(), you delete all the modules expect ResourcePermission, then after you delete all others, check if you still have ResourcePermission left, if yes, then those leftover ones should be the orphan ones you want to detect, print them out and then delete them.

Tina.

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

When you say:

> In _autoDeleteLeftovers(), you delete all the modules expect ResourcePermission, then after you delete all others_

If I have understood correctly, your idea is in `_autoDeleteLeftovers()` only delete the ResourcePermission objects that aren't orphan and, after that, handle all the leftover ResourcePermission orphans, so in case there are any orphan I can delete them and throw the error.

Is this correct?

I think this will work, I can implement it next week.

**Comment by tinatian** [comment]
@jorgediaz-lr Correct. When you remove all the models except ResourcePermission, if all the delete logic is correct, you should have no ResourcePermission model left, if you do, which means there are orphans, then we can print them out. But still, we need to delete them after printing out. 
Or, you can store those orphans into some collection, delete them together after deleting other models, then print out.

Tina.

**Comment by tinatian** [comment]
@jorgediaz-lr I am going to close this pull, please resend if needed.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
