### PR TITLE
[Method References 2] LPS-167592 Convert method reference to ServiceTrackerMap in module portal-workflow-kaleo-runtime-impl |part 2

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
Hi @tinatian , We will modify it in other tasks. It has similar logic to other classes (for example: `CompositeKaleoTaskAssignmentSelector.java 、ActionExecutorManagerImpl.java 、NotificationMessageGeneratorFactory.java` ), so they may be modified together.

**Comment by tinatian** [comment]
@W2jx Please modify TaskAssignmentSelector related stuff in the same pull. It is weird to me why you did not change "assignee.class.name" to be a property, then I realized that not all the service has this property. Please modify all of them together to show people that the structure of TaskAssignmentSelector.

Thanks.
Tina.

**Pull request closed without merging**
