### PR TITLE
[Remove Stream/Optional usage] LPS-174116 module: object-service

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend, thanks!
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3517
https://issues.liferay.com/browse/LPS-174116

Changes in this pull:  
• Add some SF changes in https://github.com/liferay-core-infra/liferay-portal/commit/751ec19930f506b5ea980146471cd67d39f11922 as per talk.

### CODE REVIEW

**Comment by JanisZhang** [comment]
force-pushed

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:object

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131469

**Pull request closed without merging**
