### PR TITLE
LPD-40213 Add performance testing for multiple finders and indexes

### PR DESCRIPTION
**Pull request by ericyanLr**

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:55176539

**Comment by ericyanLr** [comment]
ci:report:54644192

**Comment by ericyanLr** [comment]
**ci:report:analysis**
- Our added unit test: **IndexEntryTest** successfully passes
- Reported unique failures appear to be irrelevant.

Marking this ticket as **QA Passed** and **Ready to Review (no regression)**

**Comment by tinatian** [comment]
@dantewang Please take this over.

Thanks!

**Comment by dantewang** [comment]
@ericyanLr I made some SF changes, see https://github.com/liferay-core-infra/liferay-portal/pull/7605

However, the test seems a bit strange. The ticket title says "add performance testing", but the unit test is only asserting the generated index. It looks more like a gatekeeper test to avoid people from messing with the index optimization algorithm.

Could you clarify the motivation of the ticket and the test?

**Comment by ericyanLr** [comment]
Hi @dantewang ,

Thanks for reviewing and making the changes.

**Regarding:**
> However, the test seems a bit strange. The ticket title says "add performance testing", but the unit test is only asserting the generated index. It looks more like a gatekeeper test to avoid people from messing with the index optimization algorithm.
> 
> Could you clarify the motivation of the ticket and the test?

Ya, I agree that does make it sound strange. The main task ticket ([LPD-33642](https://liferay.atlassian.net/browse/LPD-33642)) has some more context.

Here is my understanding of the ticket:
1. [LPD-16955 - Optimize ServiceBuilder generated database indexes](https://liferay.atlassian.net/browse/LPD-16955), introduced a performance regression that affected many users
    - This is the ticket that introduced the index optimization algorithm, which led to many missing indexes and resulted in users experiencing performance issues
2. [LPD-24730 - Properly handle tied index columns frequency when optimizing BTree indexes](https://liferay.atlassian.net/browse/LPD-24730), resolved this issue
3. The goal would be to create a test to account for the changes made by [LPD-16955](https://liferay.atlassian.net/browse/LPD-16955), to help avoid this type of performance regression in the future.

And so, the approach I took was to simply create a test entry with multiple finders to observe the index changes and to confirm the created indexes are the expected optimized results.

**Questions**
1. Can you help confirm if my understanding of the ticket and approach is correct? 
2. And if the goal/purpose of the test is still unclear, we can reach out to Victor or Tina to confirm.

**Comment by dantewang** [comment]
@ericyanLr Actually yes, it's very hard to properly assert the "performance" here. And the key point is, when we execute the corresponding finders, we can really use the index --- but it's also very hard to test, because 1) it's hard to know DB's execution details unless we directly send the SQL to explain; 2) it's hard to determine because whether an index is used, at least in MySQL, is affected by the actual data and the optimizer's decision.

I mentioned this to Tina and we didn't come up with a good way yet. 

cc @tinatian

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7605

**Pull request closed without merging**
