### PR TITLE
LPS-149147 Remove petra-content

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,

Main task: [LPS-147982](https://issues.liferay.com/browse/LPS-147928)
Sub task: [LPS-149147](https://github.com/julschong/liferay-portal/pull/333)

This pull was previously tested on my repo here: https://github.com/julschong/liferay-portal/pull/333

Thank you

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine, Could you please help me scan the test result?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong no regressions found

**Comment by julschong** [comment]
@tinatian Hi Tina,
Could you please help me review this pull?
Thank you!

**Comment by tinatian** [comment]
@GinsonRen Do you have result for rerun DL and AP?

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by GinsonRen** [comment]
@tinatian 
DL:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine(5-17 master head) | f889bc48d4fdcc92a81dc205db0fa0e4780039f6 | 29442 | 503 | -
julschong:LPS-149147-4-25-1 | https://github.com/liferay-core-infra/liferay-portal/pull/776 | 29765 | 532 | 1.10%

AP:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine(5-17 master head) | f889bc48d4fdcc92a81dc205db0fa0e4780039f6 | 26289 | 400 | -
julschong:LPS-149147-4-25-1 | https://github.com/liferay-core-infra/liferay-portal/pull/776 | 25854 | 385 | -1.65%

**Comment by julschong** [comment]
rebase and resolve conflict for: 
> modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/display/context/LayoutsAdminDisplayContext.java

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
pushed to undo changes to:
modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/JSPModuleIllegalImportsCheck.java
modules/util/source-formatter/src/main/resources/documentation/check/jsp_module_illegal_imports_check.markdown

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by julschong** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Thanks.
Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/118107

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
