### PR TITLE
[Remove Stream usage in method body part: analytics]Lps 172272 stream

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-172272

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:analytics-cloud

**Comment by catarineaguiar** [comment]
@slnn regressions found:

```
     [exec] 
     [exec] com.liferay.analytics.reports.web.internal.model.TrafficSourceTest > testToJSONObjectWithCountrySearchKeywords FAILED
     [exec]     java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ArrayStoreException
     [exec]         at com.liferay.petra.function.transform.TransformUtil.transformToArray(TransformUtil.java:60)
     [exec]         at com.liferay.analytics.reports.web.internal.model.TrafficSource._getCountryKeywordsJSONArray(TrafficSource.java:170)
     [exec]         at com.liferay.analytics.reports.web.internal.model.TrafficSource.toJSONObject(TrafficSource.java:134)
     [exec]         at com.liferay.analytics.reports.web.internal.model.TrafficSourceTest.testToJSONObjectWithCountrySearchKeywords(TrafficSourceTest.java:175)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-32/test-portal-acceptance-pullrequest(master)/7797/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.analytics.reports.web.internal.portlet.action.test.GetReferralTrafficSourcesMVCResourceCommandTest > testGetReferralTrafficSources FAILED
     [exec]     java.lang.NullPointerException
     [exec]     	at com.liferay.analytics.reports.web.internal.portlet.action.test.GetReferralTrafficSourcesMVCResourceCommandTest.lambda$testGetReferralTrafficSources$4(GetReferralTrafficSourcesMVCResourceCommandTest.java:161)
     [exec]     	at com.liferay.analytics.reports.test.util.MockContextUtil.testWithMockContext(MockContextUtil.java:104)
     [exec]     	at com.liferay.analytics.reports.web.internal.portlet.action.test.GetReferralTrafficSourcesMVCResourceCommandTest.testGetReferralTrafficSources(GetReferralTrafficSourcesMVCResourceCommandTest.java:127)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-32/test-portal-acceptance-pullrequest(master)/7797/modules-integration-mysql57-jdk8/0/7/jenkins-console.txt.gz?authuser=0)

```
    [exec] com.liferay.analytics.reports.web.internal.portlet.action.test.GetDataMVCResourceCommandTest > testGetViewURLs FAILED
     [exec]     javax.portlet.PortletException: java.lang.NullPointerException
     [exec]     	at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCResourceCommand.serveResource(BaseMVCResourceCommand.java:49)
     [exec]     	at com.liferay.analytics.reports.web.internal.portlet.action.test.GetDataMVCResourceCommandTest.lambda$testGetViewURLs$4(GetDataMVCResourceCommandTest.java:402)
     [exec]     	at com.liferay.analytics.reports.test.util.MockContextUtil.testWithMockContext(MockContextUtil.java:104)
     [exec]     	at com.liferay.analytics.reports.web.internal.portlet.action.test.GetDataMVCResourceCommandTest.testGetViewURLs(GetDataMVCResourceCommandTest.java:395)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-32/test-portal-acceptance-pullrequest(master)/7797/modules-integration-mysql57-jdk8/0/7/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
Thank @catarineaguiar for catching this!  Will fix it and resend it later.

**Comment by slnn** [comment]
Fix and resend in https://github.com/liferay-core-infra/liferay-portal/pull/3087

**Pull request closed without merging**
