### PR TITLE
[blocker] LPS-177524 fix "Documents aren't deleted on Azure when they are removed from the portal"

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, 

This is for ticket https://issues.liferay.com/browse/LPS-177524.
I added a n need "!" in the code, which cause the regression.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@tinatian updated the commit message with correct commit id "e7936e8917564d03a3c64b5c917fefdea02ec254" that caused this issue

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131195

**Pull request closed without merging**
