### PR TITLE
LPS-154695 Remove petra-doulos from apps/petra

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,

Per your discussion with Brian, petra-doulos can be removed entirely.
[LPS-154695
](https://issues.liferay.com/browse/LPS-154695)

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine, could you please help me scan this test result? looks pretty good again!
Thank you!

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by julschong** [comment]
@tinatian Hi Tina,
Could you please help me review this pull?
Thank you!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
