### PR TITLE
[Method References 2] LPS-167249 Convert method reference to ServiceTrackerList in class SearchFacetRegistry(module portal-search-web)

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by W2jx** [comment]
no conflicts(1/16 8:39)

**Comment by W2jx** [comment]
no conflicts(1/17 17:00)

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128960

**Pull request closed without merging**
