### PR TITLE
[Method References] LPS-161155 Replace method setServletContext with field _servletContext in classes extend BaseJSPSettingsConfigurationAction

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:stop

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
no conflicts(3/21 10:29)

**Review by dantewang — APPROVED** [review]

**Comment by Kvale1733** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(3/22 11:09)

**Comment by W2jx** [comment]
Force-Push is just to resolve the conflict in file portal-kernel/bnd.bnd, only do semver, no need to rerun test

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4007

**Pull request closed without merging**
