### PR TITLE
LPS-164015 Remove immediate from workflow components

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:acceptance

**Comment by zhangyan0701** [comment]
Possible regressions:

1. In Reports Admin, report file was not generated:
https://testray.liferay.com/home/-/testray/case_results/1992275337

2. Integration test [com.liferay.calendar.service.test.CalendarBookingLocalServiceTest](https://testray.liferay.com/home/-/testray/case_results/1992284433) fail.
Full console: https://testray.liferay.com/reports/production/logs/2022-09/test-1-29/test-portal-acceptance-pullrequest(master)/4777/modules-integration-mysql57-jdk8/0/14/jenkins-console.txt.gz?authuser=0

**Comment by rafaprax** [comment]
Thanks, @zhangyan0701. I'll take a look at this.

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
@rafaprax No regressions found.

**Comment by rafaprax** [comment]
ci:test:workflow-metrics

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
I just did a rebase/push force and add a commit to fix the `LocalFile.WorkflowMetricsSLA#BlockedSLACanBeFixed`.

**Comment by rafaprax** [comment]
ci:test:workflow-metrics

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@rafaprax No regressions found. The failing tests in workflow-metrics are also failing in upstream.

**Comment by rafaprax** [comment]
Hey @shuyangzhou, This pr is ready for your review.

**Comment by shuyangzhou** [comment]
@rafaprax what is this for https://github.com/liferay-core-infra/liferay-portal/pull/1822/commits/3fb78ae6a731f102c92a6aa98bd012bcc8754f97 ? Who needs those listeners and destination?

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/124200

**Pull request closed without merging**
