### PR TITLE
LPS-199846 upgrade xmlsec to 3.0.3

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Shuyang,

This is for ticket https://liferay.atlassian.net/browse/LPS-199846.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:stop

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:help

**Comment by catarineaguiar** [comment]
ci:test:saml

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/1/23 10:26am

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/3/23 8:57am

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/6/23 8:26am

**Pull request closed without merging**
