### PR TITLE
[Components with more than 1 service] LPS-180113 Refactor ScreenNavigationCategory components from Commerce modules part 7

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions.

**Comment by MrJohn1911** [comment]
@rafaprax Can you review this? thanks!

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Pull request closed without merging**
