### PR TITLE
LPS-164866 Remove_commerce_enterprise_support_in_product

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:commerce

**Comment by jeffwu0724** [comment]
fixed the code conflict

**Comment by jeffwu0724** [comment]
ci:test:commerce

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Test failures are unrelated. Please resolve the conflicts.

**Comment by jeffwu0724** [comment]
fixed the code conflict and forced pushed

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/124838

**Pull request closed without merging**
