### PR TITLE
[SF] LPS-160079 Fix SF issue

### PR DESCRIPTION
**Pull request by JanisZhang**
It's a time issue.

see
https://github.com/liferay/liferay-portal/commit/73f2a3f414#diff-967a46bafa2036c78c2d3c5c2ad04e624b891d7821d882f38564650ca3131f98R346 https://github.com/liferay/liferay-portal/commit/924b3d471e56d962b60486defb2ba81d09928618#diff-9339a9b15ec5242c9f0236bc00e01638651d37b471ce252960ffb713d6fd9e06L97

They go on the same day. I will add it back after removing the unused field.

### CODE REVIEW

**Comment by dantewang** [comment]
@JanisZhang Which was merged first in master? Our SF update or the info-collection-provider-item-selector-web change?

**Comment by JanisZhang** [comment]
@dantewang the info-collection-provider-item-selector-web change first

**Comment by JanisZhang** [comment]
ci:forward

**Comment by JanisZhang** [comment]
Forward this one.

cc/ @dantewang @ling-alan-huang

**Pull request closed without merging**
