### PR TITLE
[Component with its own class name as service type] LPS-195477 Refctor Registry classes from Data Engine, Mentios and Analytics module

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Related: https://liferay.atlassian.net/browse/LPS-195477

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Valmir-unicap** [comment]
ci:test:data-engine

**Comment by Valmir-unicap** [comment]
ci:test:lima

**Comment by Valmir-unicap** [comment]
ci:test:analytics-cloud

**Comment by Valmir-unicap** [comment]
analytics-cloud-acceptance

**Comment by Valmir-unicap** [comment]
ci:test:analytics-cloud-acceptance

**Comment by Valmir-unicap** [comment]
ci:test:analytics-cloud

**Comment by catarineaguiar** [comment]
@Valmir-unicap possible regression:

```
     [exec] com.liferay.content.dashboard.blogs.internal.item.action.provider.test.PreviewImageBlogsEntryContentDashboardItemActionProviderTest > testIsShowWithoutPermissions PASSED
[beanshell] 2023-09-11 21:51:22.355 WARN  [com.liferay.company.test-executor-thread][AMMessageListener:79] null
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.dynamic.data.mapping.service.impl.DDMFieldLocalServiceImpl$DDMFieldInfo.access$200(DDMFieldLocalServiceImpl.java:956) ~[?:?]
[beanshell] 	at com.liferay.dynamic.data.mapping.service.impl.DDMFieldLocalServiceImpl._getDDMFormValues(DDMFieldLocalServiceImpl.java:782) ~[?:?]
[beanshell] 	at com.liferay.dynamic.data.mapping.service.impl.DDMFieldLocalServiceImpl.getDDMFormValues(DDMFieldLocalServiceImpl.java:156) ~[?:?]
[beanshell] 	at sun.reflect.GeneratedMethodAccessor4069.invoke(Unknown Source) ~[?:?]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
[beanshell] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41) ~[portal-impl.jar:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-09/test-1-31/test-portal-acceptance-pullrequest(master)/9377/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
