### PR TITLE
LPS-157454 Publication Performance

### PR DESCRIPTION
**Pull request by tinatian**
Rebased from https://github.com/liferay-core-infra/liferay-portal/pull/1064

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:publications

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results? Thanks!

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go. Please prioritize this one as it is for the publication performance issue.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
