### PR TITLE
[Method References 2] LPS-171024 Convert method reference to ServiceTrackerMap in class BulkReindexersRegistryImpl (module portal-search)

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(12/15 9:17)

**Comment by W2jx** [comment]
no conflicts(2022/12/16 8:47)

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127838

**Pull request closed without merging**
