### PR TITLE
[Optional Reference]LPS-185555 module:dynamic-data-mapping

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-185555

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
@JanisZhang failure on PortalLogAssertorTest-functional-smoke-startup:

```
    [junit] 2023-05-24 08:20:15.467 INFO  [http-nio-8080-exec-7][BundleSiteInitializer:607] Initialized com.liferay.site.initializer.welcome for group 55359 in 2343 ms
    [junit] 2023-05-24 08:21:20.645 INFO  [http-nio-8080-exec-4][CompanyIndexFactory:51] 
    [junit] 2023-05-24 08:21:20.854 ERROR [liferay/scheduler_dispatch-2][ParallelDestination:59] Unable to process message {destinationName=liferay/scheduler_dispatch, response=null, responseDestinationName=null, responseId=null, payload=null, values={GROUP_NAME=com.liferay.portal.workflow.metrics.internal.scheduler.WorkflowMetricsSLADefinitionTransformerSchedulerJobConfiguration, companyId=0, groupId=0, DESTINATION_NAME=liferay/scheduler_dispatch, JOB_STATE=com.liferay.portal.kernel.scheduler.JobState@37aa8d65, STORAGE_TYPE=MEMORY_CLUSTERED, JOB_NAME=com.liferay.portal.workflow.metrics.internal.scheduler.WorkflowMetricsSLADefinitionTransformerSchedulerJobConfiguration}}
    [junit] com.liferay.portal.kernel.messaging.MessageListenerException: java.lang.RuntimeException: org.elasticsearch.ElasticsearchStatusException: ElasticsearchStatusException[Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]]
    [junit] 	at com.liferay.portal.scheduler.internal.SchedulerEngineHelperImpl$SchedulerJobConfigurationMessageListener.receive(SchedulerEngineHelperImpl.java:536) ~[?:?]
    [junit] 	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74) ~[portal-kernel.jar:?]
    [junit] 	at com.liferay.portal.messaging.internal.ParallelDestination$1.run(ParallelDestination.java:56) [bundleFile:?]
    [junit] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
    [junit] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
    [junit] 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
    [junit] Caused by: java.lang.RuntimeException: org.elasticsearch.ElasticsearchStatusException: ElasticsearchStatusException[Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]]
    [junit] 	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:178) ~[?:?]
    [junit] 	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2484) ~[?:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-05/test-1-36/test-portal-acceptance-pullrequest(master)/3648/functional-smoke-startup-tomcat90-mysql57-jdk8/0/5/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
