### PR TITLE
LPS-160793 Do not fill default language value if it's empty

### PR DESCRIPTION
**Pull request by crodriguezy**
Hello team,

This is an attempt to fix together https://issues.liferay.com/browse/LPS-160793 and https://issues.liferay.com/browse/LPS-142380

According to the expected result of LPS-160793, its fix needs the changes made in LPS-142380. Let me know if the expected beahviour is correct (a value for the expando default locale should also be defined while uploading documents) or if we could fix both issues separately.

Thank you.

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@crodriguezy can you rebase and run relevant again, please? 

Thanks.

**Comment by jgarcialr** [comment]
hi @catarineaguiar ,

Cristina is OOO, I've resend the PR.
see #1539

**Pull request closed without merging**
