### PR TITLE
[Round 4 Method Reference Static]Lps 182411

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-182411

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@slnn No need to convert the util to component in this case. Just use multiple Snapshots to replace the references in the util. For `Portal`, you can keep using `PortalUtil`.

**Comment by slnn** [comment]
Please see https://github.com/liferay-core-infra/liferay-portal/pull/4361

**Pull request closed without merging**
