### PR TITLE
[Remove Immediate] LPS-188559 Remove immediate property from DLProcessorRegistryImpl

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://liferay.atlassian.net/browse/LPS-188559

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:document

**Comment by catarineaguiar** [comment]
no regressions found.

@rafaprax please, resolve conflicts and re-run relevant and sf only.

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
@rafaprax SF issue:

```
     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: Truncated message :
     [java] /opt/dev/projects/github/liferay-portal/modules/apps/layout/layout-page-template-admin-web/src/main/resources/META-INF/resources/init.jsp expected:<..."com.liferay.layout.[page.template.admin.constants.LayoutPageTemplateAdminPortletKeys" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.constants.LayoutPageTemplateAdminWebKeys" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.dao.search.LayoutPageTemplateResultRowSplitter" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.AssetDisplayPageUsagesDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.AssetDisplayPageUsagesManagementToolbarDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.DisplayPageDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.DisplayPageManagementToolbarDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.ImportDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.LayoutPageTemplateCollectionsDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.LayoutPageTemplateCollectionsManagementToolbarDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.LayoutPageTemplateDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.LayoutPageTemplateManagementToolbarDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.LayoutPageTemplatesAdminDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.LayoutPrototypeDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.LayoutPrototypeManagementToolbarDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.MasterLayoutDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.MasterLayoutManagementToolbarDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.SelectDisplayPageMasterLayoutDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.frontend.taglib.clay.servlet.taglib.DisplayPageTemplateCollectionHorizontalCard" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.frontend.taglib.clay.servlet.taglib.DisplayPageVerticalCard" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.frontend.taglib.clay.servlet.taglib.LayoutPageTemplateEntryVerticalCard" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.frontend.taglib.clay.servlet.taglib.LayoutPrototypeVerticalCard" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.frontend.taglib.clay.servlet.taglib.MasterLayoutVerticalCard" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.frontend.taglib.clay.servlet.taglib.SelectDisplayPageMasterLayoutVerticalCard" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.frontend.taglib.clay.servlet.taglib.SelectLayoutPageTemplateEntryMasterLayoutVerticalCard" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.servlet.taglib.util.LayoutPageTemplateCollectionActionDropdownItem" %><%@
     [java] page import="com.liferay.layout.page.template.constants.LayoutPageTemplateActionKeys" %><%@
     [java] page import="com.liferay.layout.page.template.constants.LayoutPageTemplateEntryTypeConstants" %><%@
     [java] page import="com.liferay.layout.page.template.exception.DuplicateLayoutPageTemplateCollectionException" %><%@
     [java] page import="com.liferay.layout.page.template.exception.LayoutPageTemplateCollectionNameException" %><%@
     [java] page import="com.liferay.layout.page.template.exception.LayoutPageTemplateEntryNameException" %><%@
     [java] page import="com.liferay.layout.page.template.exception.RequiredLayoutPageTemplateEntryException" %><%@
     [java] page import="com.liferay.layout.page.template.model.LayoutPageTemplateCollection" %><%@
     [java] page import="com.liferay.layout.page.template.model.LayoutPageTemplateEntry" %><%@
     [java] page import="com.liferay.layout.page.template.service.LayoutPageTemplateCollectionLocalServiceUtil" %><%@
     [java] page import="com.liferay.layout.page.template.service.LayoutPageTemplateEntryLocalServiceUtil" %><%@
     [java] page import="com.liferay.layout.page.template.service.LayoutPageTemplateEntryServiceUtil" %><%@
     [java] page import="com.liferay.portal.kernel.dao.orm.QueryUtil" %><%@
     [java] page import="com.liferay.portal.kernel.exception.PortalException" %><%@
     [java] page import="com.liferay.portal.kernel.exception.RequiredLayoutPrototypeException" %><%@
     [java] page import="com.liferay.portal.kernel.feature.flag.FeatureFlagManagerUtil" %><%@
     [java] page import="com.liferay.portal.kernel.language.LanguageUtil" %><%@
     [java] page import="com.liferay.portal.kernel.model.Group" %><%@
     [java] page import="com.liferay.portal.kernel.model.LayoutPrototype" %><%@
     [java] page import="com.liferay.portal.kernel.model.ModelHintsUtil" %><%@
     [java] page import="com.liferay.portal.kernel.portlet.LiferayWindowState" %><%@
     [java] page import="com.liferay.portal.kernel.portlet.url.builder.PortletURLBuilder" %><%@
     [java] page import="com.liferay.portal.kernel.service.LayoutPrototypeServiceUtil" %><%@
     [java] page import="com.liferay.portal.kernel.servlet.MultiSessionMessages" %><%@
     [java] page import="com.liferay.portal.kernel.util.GetterUtil" %><%@
     [java] page import="com.liferay.portal.kernel.util.HashMapBuilder" %><%@
     [java] page import="com.liferay.portal.kernel.util.HtmlUtil" %><%@
     [java] page import="com.liferay.portal.kernel.util.ListUtil" %><%@
     [java] page import="com.liferay.portal.kernel.util.ParamUtil" %><%@
     [java] page import="com.liferay.portal.kernel.util.PortalUtil" %><%@
     [java] page import="com.liferay.portal.kernel.util.Validator" %><%@
     [java] page import="com.liferay.portal.kernel.workflow.WorkflowConstants" %><%@
     [java] page import="com.liferay.portal.model.impl.LayoutPrototypeImpl" %><%@
     [java] page import="com.liferay.portal.util.PropsValues" %>
     [java] 
     [java] <%@ page import="java.util.ArrayList" %><%@
     [java] page import="java.util.List]" %><%@
     [java] page import=...> but was:<..."com.liferay.layout.[importer.LayoutsImporterResultEntry" %><%@
     [java] page import="com.liferay.layout.page.template.admin.constants.LayoutPageTemplateAdminPortletKeys" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.constants.LayoutPageTemplateAdminWebKeys" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.dao.search.LayoutPageTemplateResultRowSplitter" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.AssetDisplayPageUsagesDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.AssetDisplayPageUsagesManagementToolbarDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.DisplayPageDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.DisplayPageManagementToolbarDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.ImportDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.LayoutPageTemplateCollectionsDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.LayoutPageTemplateCollectionsManagementToolbarDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.LayoutPageTemplateDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.LayoutPageTemplateManagementToolbarDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.LayoutPageTemplatesAdminDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.LayoutPrototypeDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.LayoutPrototypeManagementToolbarDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.MasterLayoutDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.MasterLayoutManagementToolbarDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.display.context.SelectDisplayPageMasterLayoutDisplayContext" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.frontend.taglib.clay.servlet.taglib.DisplayPageTemplateCollectionHorizontalCard" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.frontend.taglib.clay.servlet.taglib.DisplayPageVerticalCard" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.frontend.taglib.clay.servlet.taglib.LayoutPageTemplateEntryVerticalCard" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.frontend.taglib.clay.servlet.taglib.LayoutPrototypeVerticalCard" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.frontend.taglib.clay.servlet.taglib.MasterLayoutVerticalCard" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.frontend.taglib.clay.servlet.taglib.SelectDisplayPageMasterLayoutVerticalCard" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.frontend.taglib.clay.servlet.taglib.SelectLayoutPageTemplateEntryMasterLayoutVerticalCard" %><%@
     [java] page import="com.liferay.layout.page.template.admin.web.internal.servlet.taglib.util.LayoutPageTemplateCollectionActionDropdownItem" %><%@
     [java] page import="com.liferay.layout.page.template.constants.LayoutPageTemplateActionKeys" %><%@
     [java] page import="com.liferay.layout.page.template.constants.LayoutPageTemplateEntryTypeConstants" %><%@
     [java] page import="com.liferay.layout.page.template.exception.DuplicateLayoutPageTemplateCollectio
     [java] 2: /opt/dev/projects/github/liferay-portal/modules/apps/staging/staging-bar-web/src/main/resources/META-INF/resources/view_layout_revisions.jsp expected:<...onse.getNamespace() [%>layoutRevisionsSearchContainer_<%=] i %>"
     [java] 						total="...> but was:<...onse.getNamespace() [+ "layoutRevisionsSearchContainer_" +] i %>"
     [java] 						total="...>
     [java] 3: /opt/dev/projects/github/liferay-portal/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/messaging/DDMStructureReindexMessageListener.java expected:<...Indexer)message.get([]"ddmStructureIndexer...> but was:<...Indexer)message.get([
     [java] 				]"ddmStructureIndexer...>
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:457)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:290)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-09/test-1-17/test-portal-source-format/6514/source-format-current-branch-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Pull request closed without merging**
