### PR TITLE
[Remove Stream/Optional usages: headless/headless-admin-content]Lps 178726

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-178726

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:headless

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Comment by dantewang** [comment]
@slnn Conflicts again..

**Comment by slnn** [comment]
Hi @dantewang 

I will resend after this pull https://github.com/liferay-core-infra/liferay-portal/pull/3984 merged since my changes included that one and it caused the confilicts

**Comment by slnn** [comment]
Resend in https://github.com/liferay-core-infra/liferay-portal/pull/4034

**Pull request closed without merging**
