### PR TITLE
[Reference cleanup]LPS-162833 9 21

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @tinatian @dantewang, 

This PR is to convert method references to field references in module `portal-search-elasticsearch7-impl`. 

Since this one is very tiny, I used existed task number created by @W2jx.
https://issues.liferay.com/browse/LPS-162833 
(_Convert method references to field references in module portal-search-elasticsearch7-impl | part 3_ )

Thanks!

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @catarineaguiar, 

Could you please help to scan the test results when they are finished?  

Thanks
Janis

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by vicnate5** [comment]
@vicnate5 testing

**Comment by vicnate5** [comment]
testing

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123526

**Pull request closed without merging**
