### PR TITLE
[TS] LPS-161481 StaleObjectStateException is caused by Hibernate auto-flush behaviour

### PR DESCRIPTION
**Pull request by istvansajtos**
Hi @yuhai ,

I've added the changes you requested on https://github.com/liferay-core-infra/liferay-portal/pull/4220. Please let me know if any further improvement is required.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
I've fixed SF error in the last commit and force pushed it. No other changes were made.

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@istvansajtos The test you added at https://github.com/liferay-core-infra/liferay-portal/pull/4276/commits/d7459de0781946c0bf91589a965b39b61cbeed27 can not expose the issue, it is not a valid test for this issue.

Please see https://github.com/liferay-core-infra/liferay-portal/pull/4316, I changed your solution and please verify my fix works.

Thanks.
Tina

**Comment by istvansajtos** [comment]
> @istvansajtos The test you added at [d7459de](https://github.com/liferay-core-infra/liferay-portal/commit/d7459de0781946c0bf91589a965b39b61cbeed27) can not expose the issue, it is not a valid test for this issue.
> 
> Please see #4321, I changed your solution and please verify my fix works.
> 
> Thanks. Tina

Thanks @tinatian, I am going to test your changes! 

I'm aware that the test is not valid on master. Actually, the issue itself is not reproducible on master. In my earlier PR I mentioned this ([here](https://github.com/liferay-core-infra/liferay-portal-ee/pull/15#issue-1649205002)), but I was requested to send the changes to master. Based on this, I'm going to test your changes on 7.3.x.

**Pull request closed without merging**
