### PR TITLE
LPD-33942 Do proper session wrapper fallback.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
Hi @shuyangzhou, I manually tested this pull request. The issue no longer occurs.

**Comment by tinatian** [comment]
ci:report:64422262

**Comment by tinatian** [comment]
ci:test:help

**Comment by tinatian** [comment]
ci:test:commerce-functional

**Comment by tinatian** [comment]
ci:test:commerce-integration

**Comment by dantewang** [comment]
ci:report:65876295

**Comment by dantewang** [comment]
ci:report:65907775

**Comment by dantewang** [comment]
> # Build started.
> Jenkins is currently running `generate testray csv` for testrayBuildID: 65907775.
> 
> Job Link: [generate-testray-csv](https://test-1-31.liferay.com/job/generate-testray-csv/124/)

No unique failure in https://github.com/liferay-core-infra/liferay-portal/pull/7357#issuecomment-2297827092

**Comment by dantewang** [comment]
ci:test:commerce-functional

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 65876295.
> 
> Job Link: [generate-testray-csv](https://test-1-31.liferay.com/job/generate-testray-csv/123/)
> 
> Testray CSV Link: [testray-results-65876295.csv](https://test-1-31.liferay.com/userContent/jobs/generate-testray-csv/builds/123/testray-results-65876295.csv)

The tests marked unique has failures in other runs with same messages, except
- LocalFile.CommerceAccountSelector#SearchForAnOrderAndSelectItAsActive

Should check this one in the re-run result.

**Comment by dantewang** [comment]
ci:report:66392229

**Comment by dantewang** [comment]
ci:forward:force

@shuyangzhou No unique failure found. The test mentioned in the ticket passed in both commerce-functional runs.

**Pull request closed without merging**
