### PR TITLE
LPS-167317 fix the timezone issue when generating versions-complete.xml

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This PR is trying to fix the timezone bugs (caused by https://issues.liferay.com/browse/LPS-149983) mentioned [here](https://github.com/liferay-core-infra/liferay-portal/pull/2106/commits/c4a4cc226d3270e7c4378fff76209faa1d9d3d73#r1003443819).
I set up the default timezone of dataFormat to "UTC" to make sure when generating versions-complete.xml, current-version-publish-date and latest-version-publish-date will not keep changing because of different timezone.
Thanks for checking!

### CODE REVIEW

**Comment by tinatian** [comment]
@jeffwu0724 You need to run build-lib-versions to make sure current xml is generated using your hard-coded timezone.

Tina

**Comment by jeffwu0724** [comment]
Hi @tinatian ,
I have run this command locally, and it will update the time to "UTC". I will update this PR by including the updated versions-complete.xml, if it is needed

**Comment by jeffwu0724** [comment]
ci:stop

**Comment by jeffwu0724** [comment]
added the updated versions-complete.xml, which is generated in UTC

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Pull request closed without merging**
