### PR TITLE
[Remove Blocking usages]LPS-188563 portal-kernel | UserBagFactoryUtil , merge UserBagFactory interface and impl into util

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4975

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:security

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(7/17 8:16)

**Comment by W2jx** [comment]
no conflicts(7/18 10:20)

**Review by dantewang — APPROVED** [review]

**Comment by W2jx** [comment]
Hi @tinatian ,  This task is to remove blocking usages, but we used the scheme of merging portal-impl and portal-kernel to    
 handle it.

**Comment by W2jx** [comment]
no conflicts(7/20 8:54)

**Comment by tinatian** [comment]
@W2jx @dantewang UserBagFactoryImpl is initialized in spring rather than modules, so we should use spring to populate the instance rather than ServiceProxyFactory in UserBagFactoryUtil.

UserBag is actually a cache for some user related data, we probably need to populate it in themedisplay or a general place like themedisplay rather than letting everyone invoke it directly at runtime. But this is not urgent, we can leave it for now and come back to it later. This is why I do not like your solution to keep UserBagFactory for people to use manually.

Please resend.

Thanks.
Tina.

**Pull request closed without merging**
