### PR TITLE
LPS-168749 change compileInclude to compileOnly for org.apache.httpcomponents

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-168749.
I tried to change compileInclude to compileOnly for org.apache.httpcomponents,because org.apache.httpcomponents has been added to shared-dependencies before.
Thanks for checking!

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@jeffwu0724 Is this really needed? "org.apache.httpcomponents", name: "httpclient-cache", could you please try to remove it and see if breaks anything?

Thanks.
Tina

**Comment by jeffwu0724** [comment]
will send a new PR later about this

**Pull request closed without merging**
