### PR TITLE
LPS-181252

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:object

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by Kvale1733** [comment]
@tinatian Regressions found

**1 ) Custom Object validation does not work**

Steps to reproduce:
1. Go to Control Panel > Objects
2. Create a new custom object called MyObject with plural label MyObjects
3. Click on created object entry
4. Select Control Panel > Object for Panel Category Key and save.
5. Go to Fields Tab
6. Add a new field called Name of type text and Save
7. Go to validations tab
8. Add a new Custom Validation of type Groovy
9. Click on created validation entry
10. Toggle "Active Validation"
11. Go to Conditions tab
12. Insert "invalidFields = (name == externalReferenceCode)" in the groovy textbox
13. Scroll down to error message and type "This entry is not possible."
14. Click Save
15. Go to Details Tab and Publish the Object entry
16. Go to Views tab
17. Add a new Custom View entry
18. Click on created view entry
19. Check "Mark as Default"
20. Go to View Builder tab.
21. Click Add Column
22. Select External Reference Code and the Name field created in step 6
23. Click Save
24. Go to Control Panel > MyObjects
25. Add a new entry name Test Entry and go back to the list of MyObjects entries
26. Copy the external reference code for Test Entry
27. Click on Test Entry erc
28. Paste the copied erc into the Name field
29. Click Save

Expected Results: Cannot save the Test Entry as since it fails the custom validation. "This entry is not possible." error appears.
Actual Results: The test entry can be saved and no error appears.

**2 ) Cannot update log levels for all nodes from slave**

Steps to reproduce: 
1. Setup 3 node cluster
2. Login to second node at localhost:9080
3. Go to Control Panel >Server Administration > Log Levels
4. Add debug log for com.liferay.portal.cluster
5. Logout from 9080 node and login to localhost:8080
6. Assert all node logs have the "Send multicast message..." message

Expected Results: The log level was updated for all nodes and the above message is shown on all node logs.
Actual Results: The log level was updated only for the master node and the log message is only printed on the 8080 node.

**3 ) com.liferay.object.graphql.test.ObjectDefinitionGraphQLTest**
```
exec] com.liferay.object.graphql.test.ObjectDefinitionGraphQLTest > testUpdateObjectEntry FAILED
     [exec]     org.junit.ComparisonFailure: expected:<[lp5etc54]> but was:<[OFY4aHko]>
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:117)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
     [exec]     	at com.liferay.object.graphql.test.ObjectDefinitionGraphQLTest.testUpdateObjectEntry(ObjectDe
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-40/test-portal-acceptance-pullrequest(master)/1416/modules-integration-mysql57-jdk8/2/23/jenkins-console.txt.gz?authuser=0)

**4 ) com.liferay.object.rest.internal.resource.v1_0.test.ObjectEntryResourceTest > testPatchSiteScopedObject**
```
 [exec] com.liferay.object.rest.internal.resource.v1_0.test.ObjectEntryResourceTest > testPatchSiteScopedObject FAILED
     [exec]     org.junit.ComparisonFailure: expected:<[1448606477]> but was:<[2dcTEodV]>
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:117)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
     [exec]     	at com.liferay.object.rest.internal.resource.v1_0.test.ObjectEntryResourceTest.testPatchSiteScopedObject(ObjectEntryResourceTest.java:3888)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-40/test-portal-acceptance-pullrequest(master)/1416/modules-integration-mysql57-jdk8/2/23/jenkins-console.txt.gz?authuser=0)

5 ) com.liferay.headless.delivery.resource.v1_0.test.KnowledgeBaseArticleResourceTest
```
[exec] com.liferay.headless.delivery.resource.v1_0.test.KnowledgeBaseArticleResourceTest > testPatchKnowledgeBaseArticle FAILED
     [exec]     com.liferay.headless.delivery.client.problem.Problem$ProblemException: No AssetEntry exists with the key {classNameId=42511, classPK=49064}
     [exec]     	at com.liferay.headless.delivery.client.resource.v1_0.KnowledgeBaseArticleResource$KnowledgeBaseArticleResourceImpl.patchKnowledgeBaseArticle(KnowledgeBaseArticleResource.java:710)
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.BaseKnowledgeBaseArticleResourceTestCase.testPatchKnowledgeBaseArticle(BaseKnowledgeBaseArticleResourceTestCase.java:376)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-40/test-portal-acceptance-pullrequest(master)/1416/modules-integration-mysql57-jdk8/2/2/jenkins-console.txt.gz?authuser=0)

**6 ) com.liferay.headless.delivery.resource.v1_0.test.WikiPageResourceTest**
```
 [exec] com.liferay.headless.delivery.resource.v1_0.test.WikiPageResourceTest > testGetWikiPagePermissionsPage FAILED
     [exec]     com.liferay.headless.delivery.client.problem.Problem$ProblemException: No WikiPage exists with the key {nodeId=65354, title=6jg4rtxl, head=true}
     [exec]     	at com.liferay.headless.delivery.client.resource.v1_0.WikiPageResource$WikiPageResourceImpl.postWikiPageWikiPage(WikiPageResource.java:1020)
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.BaseWikiPageResourceTestCase.testPostWikiPageWikiPage_addWikiPage(BaseWikiPageResourceTestCase.java:898)
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.BaseWikiPageResourceTestCase.testGetWikiPagePermissionsPage_addWikiPage(BaseWikiPageResourceTestCase.java:1056)
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.BaseWikiPageResourceTestCase.testGetWikiPagePermissionsPage(BaseWikiPageResourceTestCase.java:1045)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-40/test-portal-acceptance-pullrequest(master)/1416/modules-integration-mysql57-jdk8/2/3/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4225

**Pull request closed without merging**
