### PR TITLE
[Components with more than 1 service] LPS-180879 Refactor ScreenNavigationCategory components from USM modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://issues.liferay.com/browse/LPS-180879

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:usm

**Comment by Kvale1733** [comment]
@MrJohn1911 Regression found. Cannot add country region

Steps to reproduce:
1. Go to Control Panel > Countries Management 
2. Click on a country

Expected Results. Details are shown in the details tab. Regions can be view and added in the regions tab. 
Actual Results: Both the Details and Regions tabs are empty and cannot be interacted with.

**Comment by dantewang** [comment]
@MrJohn1911 If there's NPE on getLabel, please see Please see https://github.com/liferay-core-infra/liferay-portal/pull/4141, fix the issue and resend.

**Pull request closed without merging**
