### PR TITLE
[TS] LPS-159623 upgrade woodstox

### PR DESCRIPTION
**Pull request by markgulacsy**
Hi team,

could you review these changes? I upgraded the woodstox-core dependency in the portal.
Ticket: [LPS-159623](https://issues.liferay.com/browse/LPS-159623)

Thanks in advance!

### CODE REVIEW

**Comment by markgulacsy** [comment]
ci:test:sf

**Comment by markgulacsy** [comment]
ci:test:relevant

**Comment by markgulacsy** [comment]
ci:test:stable

**Comment by tinatian** [comment]
@jeffwu0724 Please help me review this pull.

Thanks.
Tina

**Comment by pyoo47** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by jeffwu0724** [comment]
code looks good to me

- added woodstox-core to modules/source-formatter.properties, then auto sf all the usages to 6.2.6, and auto-generate the versions file at the end
- run mygrep "woodstox-core" locally, and all of the woodstox-core has been updated to 6.2.6

**Comment by tinatian** [comment]
@jeffwu0724 

> also checked locally, all these compileOnly has a reference from com.fasterxml.woodstox.woodstox-core_6.2.6 [312], whose address is master/osgi/state/org.eclipse.osgi/312/0/bundleFile

If this is the case, then we should change all the compileInclude to compileOnly, why some of them are using compileInclude?

**Comment by jeffwu0724** [comment]
Hi @tinatian ,

This is what I am still trying to figure out. I found out the jar is in **master/osgi/state/org.eclipse.osgi/312/0/bundleFile**, but I cannot confirm if it is imported by compileInclude, or it is imported from somewhere else. I am still trying to see what the code below does do in modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/build.gradle. Seems like it also deploy the woodstox-core jar somewhere.
`deployDependencies {
	from configurations.compileOnly
	include "stax2-api-*.jar"
	include "woodstox-core-*jar"
	rename(/stax2-api-(.+)\.jar/, "org.codehaus.stax2" + renameSuffix)
	rename(/woodstox-core-(.+)\.jar/, "com.ctc.wstx" + renameSuffix)
}`

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/1327

**Comment by tinatian** [comment]
@jeffwu0724 woodstox-core jar was deployed to portal/com.ctc.wstx.jar by the code you mentioned above, please create a separate ticket to move woodstox-core to shared dependecies.

**Pull request closed without merging**
