### PR TITLE
[Replace Non-Blocking Usage] LPS-196811 Replace the usage of ServiceProxyFactory with hard reference

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:help

**Review by dantewang — APPROVED** [review]

**Comment by vicnate5** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(9/26 8:50)

**Comment by W2jx** [comment]
no conflicts(9/27 10:58)

**Comment by shuyangzhou** [comment]
ci:forward:force

**Pull request closed without merging**
