### PR TITLE
[Spring Beans] LPS-202077 Move TemplateResourceParsers to modules

### PR DESCRIPTION
**Pull request by julschong**
@tinatian Hi Tina,

TemplateResourceParser was one of targets to refactor some time ago but never got a chance to.
I only just moved ClassLoaderResourceParser and ThemeResourceParser to modules this time and didn't refactor anything else to keep it simple.

Thanks!

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
fix compile error and retest

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong regression found:

```
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-velocity/src/test/java/com/liferay/portal/template/velocity/internal/VelocityTemplateTest.java:21: error: cannot find symbol
[beanshell]      [exec] import com.liferay.portal.template.ClassLoaderResourceParser;
[beanshell]      [exec]                                   ^
[beanshell]      [exec]   symbol:   class ClassLoaderResourceParser
[beanshell]      [exec]   location: package com.liferay.portal.template
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-velocity/src/test/java/com/liferay/portal/template/velocity/internal/VelocityTemplateTest.java:89: error: cannot find symbol
[beanshell]      [exec] 				TemplateResourceParser.class, new ClassLoaderResourceParser(),
[beanshell]      [exec] 				                                  ^
[beanshell]      [exec]   symbol:   class ClassLoaderResourceParser
[beanshell]      [exec]   location: class com.liferay.portal.template.velocity.internal.VelocityTemplateTest
[beanshell]      [exec] 2 errors
[beanshell]      [exec] 
[beanshell]      [exec] > Task :apps:portal-template:portal-template-velocity:compileTestJava FAILED
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-31/test-portal-acceptance-pullrequest(master)/9964/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
pushed [b25e42d](https://github.com/liferay-core-infra/liferay-portal/pull/6163/commits/b25e42d9d810a2aef2e618a28f3218edc1211b3e) to fix VelocityTemplateTest

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by julschong** [comment]
rebased to resolve conflict in `portal-impl/src/META-INF/util-spring.xml`

**Comment by julschong** [comment]
ci:test:sf

**Pull request closed without merging**
