### PR TITLE
[Method References 2] LPS-171146 Convert method reference to ServiceTrackerMap in module portal-workflow-kaleo-runtime-impl | part 1

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(12/19 9:50)

**Comment by W2jx** [comment]
no conflicts(12/21 17:05)

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2812

**Pull request closed without merging**
