### PR TITLE
[TS] LPS-175783

### PR DESCRIPTION
**Pull request by ChrisKian**
When `locale.prepend.friendly.url.style` is set to `2`, non-ignored virtual hostnames can have their locale code removed from the URL, which should not be possible.

This issue occurs when we set the [I18N_LANGUAGE_ID attribute in PortalInstances._setAttributes()](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/util/PortalInstances.java#L602-L603).  Once this attribute is set, [we end up skipping the I18nFilter](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/servlet/filters/i18n/I18nFilter.java#L74-L87) because the isForwardedByI18nServlet method returns true due to [the I18N_LANGUAGE_ID attribute being not null](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/servlet/filters/i18n/I18nFilter.java#L290-L291).

This doesn't occur with the default `localhost` virtual host (or any host name defined in `virtual.hosts.ignore.hosts`) because these hosts result in [an early return](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/util/PortalInstances.java#L538-L540), thus never calling the `_setAttributes` method and never setting the `I18N_LANGUAGE_ID` attribute.

Regardless of the `locale.prepend.friendly.url.style` value, I believe we still need to call the _setAttributes method, so I felt the area I placed the fix is the most accurate and will have the least impact.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@ChrisKian Could you please add test?

Thanks.
Tina

**Comment by ChrisKian** [comment]
Hi @tinatian,
I'm not sure how to test my code changes in a meaningful way.  Testing the `isForwardedByI18nServlet` or `isFilterEnabled` methods individually seems useless.  I'd like to functionally test changing the URL to not include a locale code, then make sure the redirect is correct.

Any ideas on where to find similar tests I can use as a foundation?

**Comment by tinatian** [comment]
@yuhai Please take this over

**Comment by yuhai** [comment]
Hi @ChrisKian,

The fix seems to be fragile. Please see the below example.

1. Startup portal with using the default setting locale.prepend.friendly.url.style=3.
2. Go to liferay site -> Configuration -> Site Settings -> Site Configuration -> Site URL add "liferay.local" as virtual host and choose **Chinese** for "liferay.local" to save.
3. Open "liferay.local:8080" and use Test user login.

**Actual behavior**, the page displays **Chinese**.
**Expected behavior:**  the page display **English** (Test user's language).

In my opinion, the root issue is https://github.com/ChrisKian/liferay-portal/blob/LPS-175783/portal-impl/src/com/liferay/portal/util/PortalInstances.java#L590-L625.  `httpServletRequest.setAttribute(WebKeys.I18N_LANGUAGE_ID, languageId);` 

You may compare the behavior by using localhost.
1. Go to liferay site -> Configuration -> Site Settings -> Localization, change default Language for Chinese.
2. Access to localhost:8080, and use Test user login.

**Expected behavior**: the page displays user language (English) after login.

In addition, for the method naming **isForwardedByI18nServlet**, I think I18N_LANGUAGE_ID and I18N_PATH may only be set by I18nServlet. Checking our code, there are only two places to set the attributes, I18nServlet and PortalInstances. It may be wrong usages in PortalInstances since it will skip I18nFilter. 

If we remove the usages from PortalInstances, the issue shouldn't happen. I noticed one usage was added by https://issues.liferay.com/browse/LPS-157252. In the LPS-157252's description, after the step 
_"5. Log in with Test user in test.example.com:8080. Navigate to the widget page created in the previous step."_
Actually, it should display test user's langauge (English). The sixth step shouldn't happen. Please let me know if my understanding is wrong.

For the issue, I am thinking that we may try to remove ttps://github.com/ChrisKian/liferay-portal/blob/LPS-175783/portal-impl/src/com/liferay/portal/util/PortalInstances.java#L590-L625 and to see if it will cause other issues. 

Thanks,
Hai

**Comment by tinatian** [comment]
@ChrisKian I am going to close this pull based on what Hai said, please resend.

Thanks.
Tina.

**Comment by ChrisKian** [comment]
Resent here: https://github.com/liferay-core-infra/liferay-portal/pull/3618

**Pull request closed without merging**
