### PR TITLE
[Remove Blocking usages]LPS-193174 PortletResourcePermissionFactory and ModelResourcePermissionFactory

### PR DESCRIPTION
**Pull request by haydenzheng314**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5984
Ticket: https://liferay.atlassian.net/browse/LPS-193174
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by LisztLiszt** [comment]
ci:test:upgrade

**Comment by zhangyan0701** [comment]
Below errors occur in portal console when visit 8080 after upgrading:
```
2023-11-07 06:37:18.233 ERROR [http-nio-8080-exec-7][StatusDisplayContext:83] Error: null
2023-11-07 06:37:23.332 WARN  [http-nio-8080-exec-1][PortalImpl:6136] null
java.lang.NullPointerException: null
	at com.liferay.portlet.documentlibrary.service.impl.DLFileEntryServiceImpl.getFileEntryByUuidAndGroupId(DLFileEntryServiceImpl.java:584) ~[portal-impl.jar:?]
```
Steps to reproduce:
1. Import mysql dump: https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.3.10/data-archive/data-archive-portal-mysql.zip.
2. Run upgrade client tool to upgrade the database.
3. After the upgrade completes, start portal.
4. Open http://localhost:8080.

Example failed test:
[LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive7310](https://testray.liferay.com/home/-/testray/case_results/2453971402)
Full Jenkins log:
https://testray.liferay.com/reports/production/logs/2023-11/test-1-40/test-portal-acceptance-pullrequest(master)/7195/functional-upgrade-tomcat90-mysql57-jdk8/0/7/jenkins-console.txt.gz?authuser=0

**Comment by zhangyan0701** [comment]
ci:close

**Pull request closed without merging**
