### PR TITLE
LPS-146435

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina, Shuyang
This is PR is to move reference checks from XML into root/source-formatter.properties

This is because adding more Util Classes also affects older ee versions as well which causes lots of SF errors for them.
I will add to each ee portal versions to add corresponding service reference util names once this one is approved and good to go.

Main task: https://issues.liferay.com/browse/LPS-146041
Sub task 1(Master): https://issues.liferay.com/browse/LPS-146435
Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by ling-alan-huang** [comment]
@julschong SF failure is not related to this pull, but we can make ci happy if you also cherry-pick other 3 commits [here](https://github.com/julschong/liferay-portal/pull/127).

**Comment by julschong** [comment]
@ling-alan-huang I added the other 3 commits as well

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@vicnate5 Hi Victor, could you please help us scan this result?
Thank you!

**Comment by vicnate5** [comment]
@julschong No regressions found.

**Comment by julschong** [comment]
@shuyangzhou
Hi Shuyang,
Would you please help review this PR?

This is to modify service reference check to use source-formatter.properties so that we could have differnet Util classes to check for different portal versions. 
Currently, the Util classes I removed and added to SF check is causing SF problems in older versions. So, after this is approved, I will send couple more PR to modify the portal ee versions's properties.

Thank you!

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
