### PR TITLE
LPD 8462 master

### PR DESCRIPTION
**Pull request by titokenzo**
- LPD-8462 remove unused reference _destination
- LPD-8462 move destination registration logic to listener activation. Property configurationPid has no used and was removed

### CODE REVIEW

**Comment by titokenzo** [comment]
ci:test:startup

**Comment by titokenzo** [comment]
ci:report:2541845132

**Comment by titokenzo** [comment]
ci:test:sf
ci:test:relevant
ci:test:startup

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:forward

cc @tinatian

**Pull request closed without merging**
