### PR TITLE
[Unused Reference] LPD-8481 Remove unused reference from ModulePortalProfile

### PR DESCRIPTION
**Pull request by MrJohn1911**
Previous pull: https://github.com/liferay-core-infra/liferay-portal/pull/6696

Hey @dantewang, about this pull, I've mentioned that this reference is related to a bug that was occurring previously in the portal, but now it doesn't reproduce anymore. The bug in question is this one: https://liferay.atlassian.net/browse/LPSA-58483

Basically, this bug was reproduced just adding the property `dl.store.impl=com.liferay.portal.store.db.DBStore` to the portal-ext.properties and start the portal. When I do that without the reference, the portal starts normally. I couldn't found any tests related to this bug, but I've ran all the portal-store tests and all of them passed.

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:report:2555116896

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by MrJohn1911** [comment]
@dantewang actually some tests are failing due to this change, I will take a look at  it.

CC: @tinatian

**Pull request closed without merging**
