### PR TITLE
[TS] LPD-2110

### PR DESCRIPTION
**Pull request by ericyanLr**
**Ticket:** https://liferay.atlassian.net/browse/LPD-2110
**Previous PR**: https://github.com/liferay-core-infra/liferay-portal/pull/6600

Hi Team,

This PR fixes an issue with the friendlyURL, where the FriendlyURLServlet prepares a redirect URL incorrectly. 

This issue has actually been around for awhile and has repeatedly came up a few times:
- LPS-79002 ([LPSA-54344](https://liferay.atlassian.net/browse/LPSA-54344))
- LPS-81758 ([LPSA-50092](https://liferay.atlassian.net/browse/LPSA-50092))
- [LPS-131068](https://liferay.atlassian.net/browse/LPS-131068)

**Proposed Changes**
Here is an overview of the changes being made on this PR:
1. Revert commits from past tickets, to help reduce any confusion from the previous changes, in case someone else has to work on this logic in the future
2. The new fix is to simply not include the groupFriendlyURL in the redirect URL, if the original request does not include the groupFriendlyURL
3. The method where this fix takes place, will be moved from PortalImpl to FriendlyURLServlet
    - The method **getLocalizedFriendlyURL** was originally introduced by **FriendlyURLServlet** and is still only being used by **FriendlyURLServlet**
4. Add test cases

The fix for the bug is basically the combination of these commits:
- [LPD-2110 Revert "LPS-131068 Using originalHttpServletRequest when the request does not contains /web."](https://github.com/liferay-core-infra/liferay-portal/pull/6634/commits/22d1a47a2b33575835314dc313ca3af73cb21d8d)
- [LPD-2110 Revert "LPS-81758 Only use the requestURI from the original request when we are using a virtual hosts which has a null path info"](https://github.com/liferay-core-infra/liferay-portal/pull/6634/commits/bdafa8cd401f14587ab47a5931af42e5242d18ad)
- [LPD-2110 Revert "LPS-79002 Get the requestURI from the original request"](https://github.com/liferay-core-infra/liferay-portal/pull/6634/commits/d9b786262a4d7b3af543284aea9ad8ee6f315269)
- [LPD-2110 Extract method: getLocalizedFriendlyURL from PortalImpl into friendly-url-service](https://github.com/liferay-core-infra/liferay-portal/pull/6634/commits/7f7c1b2b7374193e8fb6b3ce12af1af7e9acd380)
- [LPD-2110 SF, extract logic to method in preparation for the next commit](https://github.com/liferay-core-infra/liferay-portal/pull/6634/commits/f9fb111436d7ad4989e8c1fef6525f381ba353e5)
- [LPD-2110 Do not include the groupFriendlyURL, if the original requestURI does not contain the groupFriendlyURL](https://github.com/liferay-core-infra/liferay-portal/pull/6634/commits/f7edc617c951ff5d20d6e8231177a6d97b2efb67)

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:2539122803

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:2539440559

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:report

**Comment by ericyanLr** [comment]
ci:report:2539516524

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:2539868740

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:2541455503

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:stop

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:stop

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:2542106401

**Comment by ericyanLr** [comment]
**ci:test:report analysis**
No unique failures.

Marking this as QA Passed and Ready to Review (no regression)

/cc @tinatian

**Comment by tinatian** [comment]
@ericyanLr Please see https://github.com/liferay-core-infra/liferay-portal/pull/6664, please note I did not include this commit https://github.com/liferay-core-infra/liferay-portal/pull/6634/commits/9240398db6f13e91232bfe5ad464711101282de9.

The reason is generally we should not change production code to support test logic unless there is any edge case we need to deal with, if that happens, I will let you know.

Also, did you test covered all the issues whose fixes you reverted?

**Pull request closed without merging**
