### PR TITLE
LPS-167128 Remove "immediate = true" from Commerce I

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
@MrJohn1911 Most Commerce tests failed due to the following regressions

1) Portlet not available error when viewing Commerce entry

**Steps to reproduce**
     i. Create a Minium site
     ii. Go to any Commerce portlet (Ex: Go to the products page)
     iii. Click on any antry (Ex. Click on a produce on the products page)
     
**Expected Results**: The Commerce entry can be viewed

**Actual Results**: Portlet not available error appears. This happens for every Commerce portlet like Products, Channels, Catalogs, etc.

2) Cannot view Minium

**Steps to reproduce**
     i. Create a Minium Site
     ii. Go to the Minium site from the control panel
     
**Expected Results**: The Minium site opens. The products are shown, the mini cart is show on the top right, etc.

**Actual Results**: The Minium page doesn't fully load. Only the message "You are signed in as Test Test" is shown.

**Comment by MrJohn1911** [comment]
> @MrJohn1911 should we re-run the tests suites?

No, I just found new regressions...

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
@MrJohn1911 no regressions found.

**Comment by catarineaguiar** [comment]
@MrJohn1911 as we talked, there are some functional tests failling:

`WebContentStructures#PredefineExpirationDateInDefaultStructure`
```
  [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.WebContentStructures#PredefineExpirationDateInCustomStructure] STANDARD_ERROR
     [exec]     java.lang.Exception: 
     [exec]     ##
     [exec]     ## 1 Liferay Exception was thrown
     [exec]     ##
     [exec] 
     [exec]     LIFERAY_ERROR: java.lang.RuntimeException: org.elasticsearch.ElasticsearchStatusException: [liferay-20097-workflow-metrics-nodes/GkOmaj71SIqwnxJ-qUS6VA] ElasticsearchStatusException[Elasticsearch exception [type=index_not_found_exception, reason=no such index [liferay-20097-workflow-metrics-nodes]]]
     [exec] 
     [exec] 
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/structure/WebContentStructures.testcase[PredefineExpirationDateInCustomStructure]:273
     [exec]     	at com.liferay.poshi.runner.selenium.LiferaySeleniumUtil.assertNoPoshiWarnings(LiferaySeleniumUtil.java:221)
     [exec]     	at com.liferay.poshi.runner.PoshiRunner.test(PoshiRunner.java:271)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-29/test-portal-acceptance-pullrequest(master)/5371/functional-smoke-startup-tomcat90-mysql57-jdk8/1/16/jenkins-console.txt.gz?authuser=0)

`CPCommercePriceLists#ViewPriceNotAffectedByExpiredPriceEntities`
```
[exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.CPCommercePriceLists#ViewPriceNotAffectedByExpiredPriceEntities] STANDARD_ERROR
     [exec]     java.lang.Exception: Expected text "$ 24.00" does not match actual text (case insensitive) "$ 30.00" at "//p[@title='U-Joint']/..//span[@class='price-value']"
     [exec]     /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommercePriceLists.testcase[ViewPriceNotAffectedByExpiredPriceEntities]:2511
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$20.assertTrue(BaseWebDriverImpl.java:4165)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$Condition.waitFor(BaseWebDriverImpl.java:4590)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-39/test-portal-acceptance-pullrequest(master)/1543/functional-tomcat90-mysql57-jdk8/3/24/jenkins-console.txt.gz?authuser=0)

`CPCommercePriceLists#ViewExpiredPriceEntry]`
```
[exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.CPCommercePriceLists#ViewExpiredPriceEntry] STANDARD_ERROR
     [exec]     java.lang.Exception: Element is not present at "//*[not(self::div)][contains(@class,'btn')][normalize-space()='Select'][not(contains(@class,'navbar'))]"
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/Button.macro[clickSelect]:120
     [exec]     /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-product-test/src/testFunctional/tests/CPCommercePriceLists.testcase[ViewExpiredPriceEntry]:2056
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.getWebElement(BaseWebDriverImpl.java:4325)
     [exec]     	at com.liferay.poshi.runner.selenium.ChromeWebDriverImpl.getWebElement(ChromeWebDriverImpl.java:131)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.getWebElement(BaseWebDriverImpl.java:4315)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-39/test-portal-acceptance-pullrequest(master)/1543/functional-tomcat90-mysql57-jdk8/3/22/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Comment by MrJohn1911** [comment]
No need to rerun the tests, because this push was just to organize some changes.

@shuyangzhou can you take a look on this? thanks.

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126459

**Pull request closed without merging**
