### PR TITLE
LPS-150171 Move CalendarFactoryImpl logic into CalendarFactoryUtil

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:calendar

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by tinatian** [comment]
@julschong This had been sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/128073, why did not resend a pull?

**Comment by julschong** [comment]
@tinatian Hi Tina,
I wanted to make sure so I tested ci again after rebasing with this pull

**Pull request closed without merging**
