### PR TITLE
[Reflection] LPD-15176 Remove ReflectionUtil usages in CentralizedConfigruation

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:report:2525223306

**Comment by julschong** [comment]
no regression found

**Comment by tinatian** [comment]
ci:forward:force

**Comment by dantewang** [comment]
ci:forward:force

Hmmm why it uses reflection here....

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
