### PR TITLE
[Remove Stream/Optional usage] LPS-171132 module data-engine

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-171132

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:help

**Comment by JanisZhang** [comment]
ci:test:data-engine

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3202

**Pull request closed without merging**
