### PR TITLE
LPS-171293 upgrad Apache CXF to 3.4.10

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-171293.
Thanks for checking!

### CODE REVIEW

**Comment by chaowang-123** [comment]
@dantewang The failures not related.

**Comment by catarineaguiar** [comment]
@chaowang-123 thanks!

**Comment by jeffwu0724** [comment]
fixed the code conflict in lib/versions-complete.xml by running auto-generate, the previous result should be still good

**Comment by jeffwu0724** [comment]
fixed the code conflict in lib/versions-complete.xml by running auto-generate, the previous result should be still good

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by jeffwu0724** [comment]
fixed the code conflict in lib/versions-complete.xml by running auto-generate, the previous result should be still good

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128775

**Pull request closed without merging**
