### PR TITLE
[Remove unused references]LPS-167340 Remove reference field _companyService from CommercePricin…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-167340

/cc @riccardo-alberti

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Comment by riccardo-alberti** [comment]
@slnn all good commerce side. You can forward! Thanks

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
