### PR TITLE
[Replace Non-Blocking Usage] LPS-198700 FullNameGeneratorFactory

### PR DESCRIPTION
**Pull request by JanisZhang**
Confirmed consistent behavior before and after my change. thanks!
https://liferay.atlassian.net/browse/LPS-198700

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by JanisZhang** [comment]
ci:forward:force
cc @dantewang @shuyangzhou

**Pull request closed without merging**
