### PR TITLE
LPS-149454 Move petra-mail-template to modules/app directly

### PR DESCRIPTION
**Pull request by julschong**
@tinatian Hi Tina,

Main Task: [LPS-147928](https://issues.liferay.com/browse/LPS-147928)
Sub Task: [LPS-149454](https://issues.liferay.com/browse/LPS-149454)

This pull move everything in petra-mail-template into mail/mail-template-impl package

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
relevant and stable test didnt complete. retesting...

**Comment by tinatian** [comment]
@julschong Please check this document for steps to add a new app. You are missing app.bnd here, after code is merged, you need to create a LRQA ticket to add app.properties.

https://liferay.atlassian.net/wiki/spaces/TEAMRM/pages/1662878423/How+to+add+a+new+app+to+the+release+bundle

Tina.

**Comment by julschong** [comment]
retest after adding app bundle files

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
used ant format-source-bnd to update bundle version

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by kyle-miho** [comment]
failures are unrelated

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115088

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
