### PR TITLE
[Blocker] LPS-199163 Use PortalBeanLocatorUtil.locate() when getting FullNameGenerator instance return NULL

### PR DESCRIPTION
**Pull request by JanisZhang**
previous: https://github.com/liferay-core-infra/liferay-portal/pull/5790

https://liferay.atlassian.net/browse/LPS-199163. Thanks.

cc @yuhai @dantewang

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by zhangyan0701** [comment]
No regressions found.

And the upgrade tests from 6130 passed.

**Comment by JanisZhang** [comment]
Thanks summer. @zhangyan0701

**Comment by JanisZhang** [comment]
Will fixed by https://github.com/shuyangzhou/liferay-portal/pull/11273

**Comment by yuhai** [comment]
@dantewang, the fix looks good to me.

**Review by dantewang — APPROVED** [review]

**Comment by shuyangzhou** [comment]
@JanisZhang Move `<bean class="com.liferay.portal.kernel.security.auth.DefaultFullNameGenerator" id="com.liferay.portal.kernel.security.auth.DefaultFullNameGenerator" />` to https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/META-INF/infrastructure-spring.xml should fix the problem without the code level bean lookup.

We already started the shrink process of spring xmls. Soon we will get to this and find a formal solution to handle all similar cases like this. For now, if things can be fixed within spring scope, keep it that way, so that we won't create troubles for ourselves.

Please resend.

**Pull request closed without merging**
