### PR TITLE
LPD-8476 Remove unused @Reference variables in ConfigurationMessageListener.java

### PR DESCRIPTION
**Pull request by Valmir-unicap**
- Ticket: https://liferay.atlassian.net/browse/LPD-8476

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Valmir-unicap** [comment]
ci:report:2544224001

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Valmir-unicap** [comment]
ci:report:2544270627

**Comment by dantewang** [comment]
This PR will not be needed if https://github.com/liferay-core-infra/liferay-portal/pull/6676 passes review and gets merged. Put this PR on hold for now.

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6737

**Pull request closed without merging**
