### PR TITLE
LPS-145571

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian, @shuyangzhou  ,

I have removed unused properties "Index.with.thread", and updated to propskeys.java, propsvalues.java and verifyproperties.java.

1. "INDEX_WITH_THREAD" was added in commit 8f6217eacd81fbd3342b81871c10cf404b8e09f2, see LPS-16139, and it was used in "LuceneHelperImpl.java".
2. It was moved to "modules/portal/portal-search-lucene/src/com/liferay/portal/search/lucene/internal/LuceneIndexSearcher.java" in commit 60db4fa7ea592c6f02854b4fac4f56baa74e4889, see LPS-54860.
3. It was finally moved the usage in commit f125dd5235b3546a84735a18e17e19aace0a2085, see LPS-56180.

Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by tinatian** [comment]
@jeffwu0724  The code looks good to me, wait for QA to scan test results.

Tina.

**Comment by vicnate5** [comment]
@jeffwu0724 Requires SemVer update https://testray.liferay.com/reports/production/logs/2022-01/test-1-30/test-portal-acceptance-pullrequest(master)/1667/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz

No regressions found.

**Comment by shuyangzhou** [comment]
Conflict with Brian's master, please rebase against that, or wait until upstream is synced.

**Comment by tinatian** [comment]
@jeffwu0724 Please rebase and resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
