### PR TITLE
[Method References 2] LPS-166968 Convert method reference to ServiceTrackerMap in module data-engine-taglib and data-engine-rest-impl

### PR DESCRIPTION
**Pull request by W2jx**
I have modified the code as per the [comments](https://github.com/liferay-core-infra/liferay-portal/pull/3786#issuecomment-1477380248).

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3786

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:data-engine

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(4/7 16:38)

**Comment by W2jx** [comment]
no conflicts(4/10 8:33)

**Comment by W2jx** [comment]
will resend, Same reason as https://github.com/liferay-core-infra/liferay-portal/pull/4068.

**Pull request closed without merging**
