### PR TITLE
[Convert method references]Lps 163055

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-163055

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
Waiting for @zhangyan0701 to check results.

**Comment by zhangyan0701** [comment]
Compile error in apps:portal:portal-messaging, this caused some integration tests fail:
```
     [exec] > Task :apps:portal:portal-messaging:compileTestJava FAILED
     [exec] 
     [exec] > Task :apps:portal:portal-messaging:processTestResources NO-SOURCE
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal/portal-messaging/src/test/java/com/liferay/portal/messaging/internal/jmx/MessageBusManagerTest.java:48: error: cannot find symbol
     [exec] 		messageBusManager.setMessageBus(
     [exec] 		                 ^
     [exec]   symbol:   method setMessageBus(com.liferay.portal.kernel.messaging.MessageBus)
     [exec]   location: variable messageBusManager of type com.liferay.portal.messaging.internal.jmx.MessageBusManager
     [exec] 1 error
```

Full console log:
https://testray.liferay.com/reports/production/logs/2022-09/test-1-29/test-portal-acceptance-pullrequest(master)/4706/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
Hi @zhangyan0701 

I fix the issue and forced push to the branch, please help to rescan test results when they are finished.

Thanks
Lily

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@shuyangzhou @tinatian Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/123730 as it's simple change and passes QA review.

**Pull request closed without merging**
