### PR TITLE
[Spring Beans] LPS-200292 Merge IdenticalPhoneNumberFormatImpl into Util and move to portal-impl

### PR DESCRIPTION
**Pull request by W2jx**
resend, fix the test

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/6004

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(11/7 9:34)

**Comment by W2jx** [comment]
no conflicts(11/8 10:05)

**Comment by Kvale1733** [comment]
ci:test:relevant:norebase

**Comment by Kvale1733** [comment]
ci:test:startup:norebase

**Comment by W2jx** [comment]
ci:stop

**Pull request closed without merging**
