### PR TITLE
LPS-180672 Remove HyperSonic prebuilding

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou @tinatian @vicnate5

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:backend-hypersonic

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:backend-hypersonic

**Comment by catarineaguiar** [comment]
no regressions found.

SF issue is unrelated.

**Comment by dantewang** [comment]
Closing, will resend.

**Comment by vicnate5** [comment]
@tinatian No issues found in the setup wizard tests.

We are already starting with empty HSQL on CI.

```
INFO  [main][DialectDetector:153] Using dialect com.liferay.portal.dao.orm.hibernate.HSQLDialect for HSQL Database Engine 2.7
INFO  [main][DBInitUtil:142] Create tables and populate with default data
```

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4208

**Pull request closed without merging**
