### PR TITLE
LPS-164441 Remove toXmlString() from model impl

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by julschong** [comment]
resolve conflict in semantic versioning

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/124441

**Pull request closed without merging**
