### PR TITLE
LPS-188080 Avoiding NPE by verifying if user has a group

### PR DESCRIPTION
**Pull request by rijema**
Hi team! I faced a problem in the customer's database where a change made by a customer in the control panel was not persisting. Debugging, I found that given the customer data, we faced a problem in our code due to a different role configuration. So I added more specific handling with validating the groups associated with a user when checked by the changed listener. According to the customer, it solved his problem.

Cause:

When the configuration changes tried to be committed, an error in the server log appeared and consequently the changes did not propagate.

`build-267 liferay[liferay-64cd75ddfc-mblw9] [dxp] ERROR [http-nio2-8080-exec-38][PortletServlet:118] Unable to process portlet com_liferay_configuration_admin_web_portlet_InstanceSettingsPortlet: com.liferay.portal.kernel.exception.ModelListenerException: java .lang.NullPointerException`

The client also informed that the changes are not saved, even after restarting the environment or clearing the cache, what was supposed to be recorded does not display as marked, which affects precisely another functionality which depends on updating the authentication configuration.

A part of the ticket was worked on the link below.

_https://liferay.atlassian.net/browse/LPP-49289_

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:calendar

**Comment by Kvale1733** [comment]
No regressions found.

**Comment by rijema** [comment]
Thank you for working on this @Kvale1733 !

**Comment by tinatian** [comment]
@rijema This should not be a core-infra issue, please modify lima team. Please also modify your ticket scope.

FYI @brunofalc 

Thanks.
Tina

**Pull request closed without merging**
