### PR TITLE
LPS-171636 Remove "immediate = true" from Commerce part V

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:commerce

**Comment by RenanUmV** [comment]
ci:test:commerce-database

**Comment by RenanUmV** [comment]
ci:test:commerce-es7-remote

**Comment by RenanUmV** [comment]
ci:test:commerce-functional

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
@RenanUmV semver error:

```
    [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/commerce/commerce-payment-test-util] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.commerce.payment.test.util             CHANGED    1.0.2      1.0.2      1.0.3      VERSION INCREASE REQUIRED
     [exec]     	~   class      com.liferay.commerce.payment.test.util.TestCommercePaymentMethod
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   immediate=true
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
```
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/commerce/commerce-test-util] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.commerce.test.util.context             CHANGED    2.0.0      2.0.0      2.0.1      VERSION INCREASE REQUIRED
     [exec]     	~   class      com.liferay.commerce.test.util.context.TestCustomCommerceContextFactory
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   immediate=true
     [exec]     * com.liferay.commerce.test.util.order.status        CHANGED    1.0.1      1.0.1      1.0.2      VERSION INCREASE REQUIRED
     [exec]     	~   class      com.liferay.commerce.test.util.order.status.Test1CommerceOrderStatusImpl
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   immediate=true
     [exec]     	~   class      com.liferay.commerce.test.util.order.status.Test2CommerceOrderStatusImpl
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   immediate=true
     [exec]     	~   class      com.liferay.commerce.test.util.order.status.Test3CommerceOrderStatusImpl
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   immediate=true
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-25/test-portal-acceptance-pullrequest(master)/5866/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
Hey @tinatian , this one is ready to go!

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128884

**Pull request closed without merging**
