### PR TITLE
[Method References 2] LPS-165165 Convert method reference to ServiceTrackerList in module portal-search-elasticsearch7-impl | part 1

### PR DESCRIPTION
**Pull request by W2jx**
Resend, keep the logic of Sidecar direct reference to _settingsContributors in class SidecarManager.

Detial: https://github.com/liferay-core-infra/liferay-portal/pull/2321

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
@W2jx could you rebase and re-run tests if necessary, please? Thanks!

**Comment by W2jx** [comment]
Force-Push is just to rebase and resolve conflict.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
Integration test [com.liferay.portal.search.elasticsearch7.internal.index.instant.InstantIndexesTest](https://testray.liferay.com/home/-/testray/case_results/2042226924) failed.
[com.liferay.portal.search.elasticsearch7.internal.index.instant.InstantIndexesTest](https://testray.liferay.com/home/-/testray/case_results/2042226924)

Failed tests: testStartTwiceIndexCreation, testAutomaticIndexCreation, testRuntimeIndexCreation
`java.lang.NoSuchFieldException: No field on null with name _indexDefinitionsHolder`

Full console:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-37/test-portal-acceptance-pullrequest(master)/6219/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@W2jx no regressions found.

**Comment by tinatian** [comment]
@W2jx There is only one real impl of SettingsContributor, all others come from tests, please try to remove it.

Tina.

**Pull request closed without merging**
