### PR TITLE
remove_unused_properties_part3

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian , @shuyangzhou,

I have removed five groups of unused properties, and they are "scripting.jruby.compile.mode", "Cluster.link.node.bootup.response.timeout", "rtl.css.excluded.paths.regexp", "browser.compatibility.ie.versions", "Users.list.views".

scripting.jruby.compile.mode - https://github.com/tinatian/liferay-portal/pull/2491
Cluster.link.node.bootup.response.timeout - https://github.com/tinatian/liferay-portal/pull/2495
rtl.css.excluded.paths.regexp - https://github.com/liferay-core-infra/liferay-portal/pull/237
browser.compatibility.ie.versions - https://github.com/liferay-core-infra/liferay-portal/pull/225
Users.list.views - https://github.com/liferay-core-infra/liferay-portal/pull/226
Thanks for checking. can also see https://github.com/jeffwu0724/liferay-portal/pull/23

Thanks,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@kyle-miho Hey Kyle, could you please help me to scan the test result?

Thanks,
Jeff

**Comment by tinatian** [comment]
@jeffwu0724 "scripting.jruby.compile.threshold" should also be removed. Please remove it with other jruby properties in one commit.

Please also see my comments above and resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
