### PR TITLE
[OrderByComparator] LPD-26512 Clean up and Apply Singleton in module portal-background-task-service

### PR DESCRIPTION
**Pull request by rubenssoares-br**
Ticket: https://liferay.atlassian.net/browse/LPD-26512

### CODE REVIEW

**Comment by rubenssoares-br** [comment]
ci:test:core-functional

**Comment by rubenssoares-br** [comment]
ci:report:2571881360

**Comment by rubenssoares-br** [comment]
ci:test:sf

**Comment by rubenssoares-br** [comment]
ci:test:relevant

**Comment by rubenssoares-br** [comment]
ci:test:core-functional

**Comment by Valmir-unicap** [comment]
ci:stop

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
Reevaluating!
CC: @titokenzo

**Pull request closed without merging**
