### PR TITLE
[Bug fix] LPS-141792 Duplicate entry in class path

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Added integration test. I found other bugs when looking into the `ClassUtil` usages, so I created a parent ticket with sub tasks, see https://issues.liferay.com/browse/LPS-142276. This bug is converted to a sub ticket under LPS-142276.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dantewang Please see https://github.com/liferay-core-infra/liferay-portal/pull/6.
Please note I did not include the test logic for "WEB-INF/lib entries", using "2" or "3" explicitly is hard to read and maintain later.

Tina

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
