### PR TITLE
[Remove unused @Reference var] LPS-164051

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove the unused @Reference variable in `account-service`. Thanks!
CI test passed in https://github.com/dantewang/liferay-portal/pull/2260

https://issues.liferay.com/browse/LPS-164051

cc/ @ling-alan-huang

### CODE REVIEW

**Comment by JanisZhang** [comment]
I just changed the commit message, it shouldn't affect the test results. thx @catarineaguiar

**Review by dantewang — APPROVED** [review]
Code change approved.

**Comment by JanisZhang** [comment]
HI @catarineaguiar, Could you please help to scan the test results? thx

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123982

**Pull request closed without merging**
