### PR TITLE
[Method References 2] LPS-173124 Convert method reference to ServiceTrackerMap in module segments-service

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:tango

**Comment by Kvale1733** [comment]
@W2jx No regressions.

**Comment by W2jx** [comment]
no conflicts(1/27 13:28)

**Comment by W2jx** [comment]
Force-Push is just to resolve conflicts.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:tango

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(2/1 10:06)

**Pull request closed without merging**
