### PR TITLE
LPS-142794 - fix XXE vulnerability by using newTransformerFactory() with attributes set up

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

As discussed, try to avoid adding dependencies on portal-impl in diff-impl
This is for ticket https://issues.liferay.com/browse/LPS-142794.
Thanks for checking.

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by tinatian** [comment]
@jeffwu0724 Code looks good to me, please rebase.

Thanks.
Tina

**Comment by jeffwu0724** [comment]
force push to fix the conflict in portal-kernel/bnd.bnd

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123380

**Pull request closed without merging**
