### PR TITLE
LPS-143632 Remove LanguageUtil from moduels part 3a mixed

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar 
Hi Catarine,
Could you please help me review this test result?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong no regressions on relevant

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
trigger relevant to make sure this is still good with updated upstream

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
