### PR TITLE
Lps 173546 2 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@tinatian regression found:

```
     [exec] > Task :apps:portal-scheduler:portal-scheduler-quartz:compileTestJava FAILED
     [exec] 
     [exec] > Task :apps:portal-scheduler:portal-scheduler-quartz:processTestResources NO-SOURCE
     [exec] Gradle build finished at 2023-02-01 18:27:45.605.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-scheduler/portal-scheduler-quartz/src/test/java/com/liferay/portal/scheduler/quartz/internal/QuartzSchedulerEngineTest.java:482: error: method update in class com.liferay.portal.scheduler.quartz.internal.QuartzSchedulerEngine cannot be applied to given types;
     [exec] 		_quartzSchedulerEngine.update(newTrigger, StorageType.MEMORY);
     [exec] 		                      ^
     [exec]   required: org.quartz.Scheduler,com.liferay.portal.kernel.scheduler.Trigger,com.liferay.portal.kernel.scheduler.StorageType
     [exec]   found: com.liferay.portal.kernel.scheduler.Trigger,com.liferay.portal.kernel.scheduler.StorageType
     [exec]   reason: actual and formal argument lists differ in length
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-scheduler/portal-scheduler-quartz/src/test/java/com/liferay/portal/scheduler/quartz/internal/QuartzSchedulerEngineTest.java:516: error: method update in class com.liferay.portal.scheduler.quartz.internal.QuartzSchedulerEngine cannot be applied to given types;
     [exec] 		_quartzSchedulerEngine.update(newTrigger, StorageType.MEMORY);
     [exec] 		                      ^
     [exec]   required: org.quartz.Scheduler,com.liferay.portal.kernel.scheduler.Trigger,com.liferay.portal.kernel.scheduler.StorageType
     [exec]   found: com.liferay.portal.kernel.scheduler.Trigger,com.liferay.portal.kernel.scheduler.StorageType
     [exec]   reason: actual and formal argument lists differ in length
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-scheduler/portal-scheduler-quartz/src/test/java/com/liferay/portal/scheduler/quartz/internal/QuartzSchedulerEngineTest.java:548: error: method update in class com.liferay.portal.scheduler.quartz.internal.QuartzSchedulerEngine cannot be applied to given types;
     [exec] 		_quartzSchedulerEngine.update(trigger, StorageType.MEMORY);
     [exec] 		                      ^
     [exec]   required: org.quartz.Scheduler,com.liferay.portal.kernel.scheduler.Trigger,com.liferay.portal.kernel.scheduler.StorageType
     [exec]   found: com.liferay.portal.kernel.scheduler.Trigger,com.liferay.portal.kernel.scheduler.StorageType
     [exec]   reason: actual and formal argument lists differ in length
     [exec] 3 errors
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-02/test-1-27/test-portal-acceptance-pullrequest(master)/6748/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129864

**Pull request closed without merging**
