### PR TITLE
[JDK17] LPD-17121 Fix ConcurrentModificationException accessing BasePermissionChecker#_permissionChecksMap by using ConcurrentHashMap instead of HashMap

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@julschong Did you test it locally?

**Comment by tinatian** [comment]
@julschong Can you add more details why ConcurrentModificationException happen here?

**Comment by julschong** [comment]
@tinatian added more detailed info on commit message
Yes I tested `ExportImport#EditExportTemplate` locally both manually and running functional test, both passed

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/147043

**Pull request closed without merging**
