### PR TITLE
[JDK17] LPD-43607

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@jeffwu0724 Could you trigger a JDK17 run for upstream-dxp? I modified it to run only weblogic tests to verify the last 2 commits.

**Comment by jeffwu0724** [comment]
Hi @dantewang , I have triggered the test

**Comment by dantewang** [comment]
WebLogic smoke passed.

A JVM error showed up during shutting down WebLogic, but it didn't break the whole process.

```
[beanshell] #
[beanshell] # A fatal error has been detected by the Java Runtime Environment:
[beanshell] #
[beanshell] #  SIGSEGV (0xb) at pc=0x00007ff5432d5b24, pid=237397, tid=237470
[beanshell] #
[beanshell] # JRE version: OpenJDK Runtime Environment Zulu17.44+17-CRaC-CA (17.0.8+7) (build 17.0.8+7-LTS)
[beanshell] # Java VM: OpenJDK 64-Bit Server VM Zulu17.44+17-CRaC-CA (17.0.8+7-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
[beanshell] # Problematic frame:
[beanshell] # V  [libjvm.so+0xa3db24]  LinkResolver::resolve_invoke(CallInfo&, Handle, constantPoolHandle const&, int, Bytecodes::Code, JavaThread*)+0x244
[beanshell] #
[beanshell] # Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /opt/dev/projects/github/liferay-portal/bundles/weblogic-14.1.1/domains/liferay/core.237397)
[beanshell] #
[beanshell] # JFR recording file will be written. Location: /opt/dev/projects/github/liferay-portal/bundles/weblogic-14.1.1/domains/liferay/hs_err_pid237397.jfr
[beanshell] #
[beanshell] # An error report file with more information is saved as:
[beanshell] # /opt/dev/projects/github/liferay-portal/bundles/weblogic-14.1.1/domains/liferay/hs_err_pid237397.log
[beanshell] #
[beanshell] # If you would like to submit a bug report, please visit:
[beanshell] #   http://www.azul.com/support/
[beanshell] #
```

**Comment by tinatian** [comment]
ci:report:100287905

**Comment by jeffwu0724** [comment]
Hi @dantewang ,

There is a ticket related to weblogic https://liferay.atlassian.net/browse/LPD-45206
We may need to modify the commit message

**Pull request closed without merging**
