### PR TITLE
LPS-169043 move_commons-collections4_to_shared-dependencies

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Change the commit order as well as the commit message to make it clear, based on https://github.com/liferay-core-infra/liferay-portal/pull/2511
I am trying to move commons-collections4 to shared-dependencies because we already have a shared-dependencies for org.apache.commons.
Thanks for checking!

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
rebase, fixed code conflicts, and rerun the tests

**Comment by catarineaguiar** [comment]
@jeffwu0724 possible regression:

```
     [exec] com.liferay.portal.workflow.kaleo.internal.runtime.integration.test.WorkflowTaskManagerImplTest > testSearchWorkflowTasksOrderByModifiedDate FAILED
     [exec]     java.lang.AssertionError: 50694 does not equal 50686 expected:<50694> but was:<50686>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at com.liferay.portal.workflow.kaleo.internal.runtime.integration.test.WorkflowTaskManagerImplTest._assertEquals(WorkflowTaskManagerImplTest.java:1434)
     [exec]     	at com.liferay.portal.workflow.kaleo.internal.runtime.integration.test.WorkflowTaskManagerImplTest.testSearchWorkflowTasksOrderByModifiedDate(WorkflowTaskManagerImplTest.java:1163)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-39/test-portal-acceptance-pullrequest(master)/2142/modules-integration-mysql57-jdk8/3/6/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
