### PR TITLE
[Components with more than 1 service] LPS-188519 Refactor components from analytics, product-navigation, portal-workflow and journal modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-188519

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:data-engine

**Comment by MrJohn1911** [comment]
ci:test:lima

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:data-engine

**Comment by MrJohn1911** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:analytics-cloud-acceptance

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by dantewang** [comment]
Conflicts, please update.

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud-acceptance

**Comment by MrJohn1911** [comment]
ci:test:echo

**Comment by MrJohn1911** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137106

**Pull request closed without merging**
