### PR TITLE
[Remove Stream/Optional usage] LPS-175362 modules: item-selector-web , item-selector-test

### PR DESCRIPTION
**Pull request by JanisZhang**
previous: https://github.com/liferay-core-infra/liferay-portal/pull/3432#discussion_r1118740191
https://issues.liferay.com/browse/LPS-175362

Changes in this pull:  
• ~~I use the normal for-loop instead of using `ListUtil.count(...));` in https://github.com/liferay-core-infra/liferay-portal/commit/296c8fb038c11e5eaa205df213136b99b1d74bfe. In this way, the method calls less than 1 iteration. Thanks!~~

force-pushed
• I use `ListUtil.exists(...));`  instead of using `ListUtil.count(...));`

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:item-selector

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by JanisZhang** [comment]
force-pushed. I only change the variable name, append 1 SF commit. No need to re-trigger test.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131209

**Pull request closed without merging**
