### PR TITLE
LPS-142761

### PR DESCRIPTION
**Pull request by mbowerman**
Re-sent from https://github.com/liferay-core-infra/liferay-portal/pull/35

https://issues.liferay.com/browse/LPS-142761

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Thanks.
Tina.

**Comment by vendeltoreki** [comment]
Hi @tinatian , @mbowerman ,

I've checked this latest fix and it seems like the memory limit is missing from this one. It's very common that users export/publish large amounts of data, which will most likely result in an `OutOfMemoryError`.
I managed to produce this error just by uploading 5 files with, 1 GB each, and then trying to export the entire site.

Do we plan to implement this limit in a separate ticket?

Thanks,
Vendel

**Comment by vicnate5** [comment]
@tinatian While no regressions found in the automation results, I was able to reproduce the issue mentioned by @vendeltoreki.

Steps to Reproduce:
1. Go to System Settings > Platform > Infrastructure > Upload Servlet Request
2. Set "Overall Maximum Upload Request Size" to  `2147483648` (2 GB) and Save
3. Navigate to Liferay site > Content & Data > Documents and Media
4. Add new Multiple Files Upload and upload 5 image files that are 1 GB each
_Created test images on linux with_ `fallocate -l 1G test1.jpg`
5. Navigate to Liferay site > Publishing > Export
6. Attempt to Export the site
```
ERROR [liferay/background_task-4][LoggerExportImportLifecycleListener:359] Staged model {class: com.liferay.document.library.kernel.model.DLFileEntry, groupId: 20123, uuid: 0d6ffa62-3b93-287b-7ce5-1c84ba34443d} export failed
java.lang.OutOfMemoryError: Java heap space
        at com.liferay.petra.io.unsync.UnsyncByteArrayOutputStream.<init>(UnsyncByteArrayOutputStream.java:37) ~[com.liferay.petra.io.jar:?]
        at com.liferay.petra.io.StreamUtil.toByteArray(StreamUtil.java:75) ~[com.liferay.petra.io.jar:?]
        at com.liferay.portal.zip.ZipWriterImpl.addEntry(ZipWriterImpl.java:124) ~[portal-impl.jar:?]
        at com.liferay.exportimport.internal.lar.PortletDataContextImpl.addZipEntry(PortletDataContextImpl.java:492) ~[?:?]
        at com.liferay.document.library.internal.exportimport.data.handler.FileEntryStagedModelDataHandler.doExportStagedModel(FileEntryStagedModelDataHandler.java:319) ~[?:?]
        at com.liferay.document.library.internal.exportimport.data.handler.FileEntryStagedModelDataHandler.doExportStagedModel(FileEntryStagedModelDataHandler.java:114) ~[?:?]
        at com.liferay.exportimport.kernel.lar.BaseStagedModelDataHandler.exportStagedModel(BaseStagedModelDataHandler.java:102) ~[portal-kernel.jar:?]
        at com.liferay.exportimport.data.handler.base.BaseStagedModelDataHandler.exportStagedModel(BaseStagedModelDataHandler.java:80) ~[?:?]
        at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.exportStagedModel(StagedModelDataHandlerUtil.java:170) ~[portal-kernel.jar:?]
        at com.liferay.document.library.internal.exportimport.staged.model.repository.FileEntryStagedModelRepository.lambda$getExportActionableDynamicQuery$1(FileEntryStagedModelRepository.java:188) ~[?:?]
        at com.liferay.document.library.internal.exportimport.staged.model.repository.FileEntryStagedModelRepository$$Lambda$15000/324958783.performAction(Unknown Source) ~[?:?]
```
This issue is Not reproducible at head so I would consider it a regression from this change.

**Comment by tinatian** [comment]
@mbowerman Could you please resend this pull with the property used for out of memory issue? 
I thought there would be some kind of threshold from export/import we can use, it seems not based on the discussion on slack, so we have to add a new property for this. 
Also, could you please name the property as "zip.file.writer.export.buffer.size"?

I am going to close this pull, please resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by mbowerman** [comment]
@tinatian Thanks for the feedback. I re-sent it at https://github.com/liferay-core-infra/liferay-portal/pull/58.

**Pull request closed without merging**
