### PR TITLE
LPS-147929 Move petra-json-validator to modules/app directly

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,

Main Task: [LPS-147928 Remove petra jar from modules/apps](https://issues.liferay.com/browse/LPS-147928)
Sub Task: [LPS-147929 Move petra-json-validator to modules/app directly](https://issues.liferay.com/browse/LPS-147929)

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
@kyle-miho
Hi Kyle,
Could you please help me scan this test result?
Thank you

**Comment by kyle-miho** [comment]
@julschong failures should be unrelated, pr should be good to go

**Comment by julschong** [comment]
@tinatian Hi Tina, 
Could you please help me review this PR?
Thankyou!

**Comment by tinatian** [comment]
@julschong Code looks good to me, but this pull is going to conflict with another pull you sent to add portal-utilities, please wait for that one merged in, rebase and resend this one.

Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
