### PR TITLE
LPD-38763 Pre flush and clear the session. This is to prevent the any…

### PR DESCRIPTION
**Pull request by shuyangzhou**
… prevous deletion caused buffered ResourcePermission deletion leaked to the end. In the case, it is the previous ObjectAction removal caused it. The proper fix should have been a bulk delete support for ObjectAction deletion too, however without a proper test case I would not want to change the design blindly. Using the pre flush/clear to bypass the problem instead.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:42473590

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Hi @shuyangzhou , @tinatian , do you have any updates about this?

**Comment by shuyangzhou** [comment]
@tinatian why is this pull still waiting here?

**Comment by tinatian** [comment]
@shuyangzhou Sorry, I have not got time checked the latest test result as the original report has some falky ones not sure if unique.

Checking it now.

**Comment by tinatian** [comment]
ci:test:report:48355067

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 56724131.
> 
> Job Link: [generate-testray-csv](https://test-1-35.liferay.com/job/generate-testray-csv/123/)
> 
> Testray CSV Link: [testray-results-56724131.csv](https://test-1-35.liferay.com/userContent/jobs/generate-testray-csv/builds/123/testray-results-56724131.csv)

No unique failures in report

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
