### PR TITLE
LPS-171090 Remove "immediate = true" from Solutions' components part 2

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@GabrielHenriquedev No regressions found.

**Comment by GabrielHenriquedev** [comment]
@shuyangzhou  this one is ready to go.

**Comment by tinatian** [comment]
ci:forward

FYI @shuyangzhou

**Pull request closed without merging**
