### PR TITLE
[Spring Beans] LPS-200538 Remove VerifiableModels from util-spring

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:upgrade

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:upgrade

**Comment by julschong** [comment]
@tinatian I combined both VerifiableResourceModels and VerifiableAuditedModels in the commits, should be more clear on how many I removed

**Comment by tinatian** [comment]
ci:forward:force

**Comment by julschong** [comment]
@tinatian 2 commits are merged

**Comment by julschong** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
