### PR TITLE
[Rename Classes] LPS-166956 Rename classes in modules dynamic-data-mapping-api、dynamic-data-mapping-service

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Semantic version error:
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/dynamic-data-mapping/dynamic-data-mapping-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.dynamic.data.mapping.io                MAJOR      2.3.0      2.2.0      3.0.0      VERSION INCREASE REQUIRED
     [exec]     	+   interface  com.liferay.dynamic.data.mapping.io.DDMFormLayoutDeserializerRegistry
     [exec]     		+   access     abstract
     [exec]     		+   method     getDDMFormLayoutDeserializer(java.lang.String)
     [exec]     			+   access     abstract
     [exec]     			+   return     com.liferay.dynamic.data.mapping.io.DDMFormLayoutDeserializer
     [exec]     		+   annotated  org.osgi.annotation.versioning.ProviderType
     [exec]     	-   interface  com.liferay.dynamic.data.mapping.io.DDMFormLayoutDeserializerTracker
     [exec]     		-   access     abstract
     [exec]     		-   method     getDDMFormLayoutDeserializer(java.lang.String)
     [exec]     			-   access     abstract
     [exec]     			-   return     com.liferay.dynamic.data.mapping.io.DDMFormLayoutDeserializer
     [exec]     		-   annotated  org.osgi.annotation.versioning.ProviderType
     [exec]     	+   interface  com.liferay.dynamic.data.mapping.io.DDMFormLayoutSerializerRegistry
     [exec]     		+   access     abstract
     [exec]     		+   method     getDDMFormLayoutSerializer(java.lang.String)
     [exec]     			+   access     abstract
     [exec]     			+   return     com.liferay.dynamic.data.mapping.io.DDMFormLayoutSerializer
     [exec]     		+   annotated  org.osgi.annotation.versioning.ProviderType
     [exec]     	-   interface  com.liferay.dynamic.data.mapping.io.DDMFormLayoutSerializerTracker
     [exec]     		-   access     abstract
     [exec]     		-   method     getDDMFormLayoutSerializer(java.lang.String)
     [exec]     			-   access     abstract
     [exec]     			-   return     com.liferay.dynamic.data.mapping.io.DDMFormLayoutSerializer
     [exec]     		-   annotated  org.osgi.annotation.versioning.ProviderType
     [exec]     	-   version    2.2.0
     [exec]     	+   version    2.3.0
     [exec]     * com.liferay.dynamic.data.mapping.io.exporter       MAJOR      2.1.0      2.0.0      3.0.0      VERSION INCREASE REQUIRED
     [exec]     	+   interface  com.liferay.dynamic.data.mapping.io.exporter.DDMFormInstanceRecordWriterRegistry
     [exec]     		+   access     abstract
     [exec]     		+   method     getDDMFormInstanceRecordWriter(java.lang.String)
     [exec]     			+   access     abstract
     [exec]     			+   return     com.liferay.dynamic.data.mapping.io.exporter.DDMFormInstanceRecordWriter
     [exec]     		+   method     getDDMFormInstanceRecordWriterExtensions()
     [exec]     			+   access     abstract
     [exec]     			+   return     java.util.Map
     [exec]     		+   annotated  org.osgi.annotation.versioning.ProviderType
     [exec]     	-   interface  com.liferay.dynamic.data.mapping.io.exporter.DDMFormInstanceRecordWriterTracker
     [exec]     		-   access     abstract
     [exec]     		-   method     getDDMFormInstanceRecordWriter(java.lang.String)
     [exec]     			-   access     abstract
     [exec]     			-   return     com.liferay.dynamic.data.mapping.io.exporter.DDMFormInstanceRecordWriter
     [exec]     		-   method     getDDMFormInstanceRecordWriterExtensions()
     [exec]     			-   access     abstract
     [exec]     			-   return     java.util.Map
     [exec]     		-   annotated  org.osgi.annotation.versioning.ProviderType
     [exec]     	-   version    2.0.0
     [exec]     	+   version    2.1.0
     [exec]     * com.liferay.dynamic.data.mapping.storage           MAJOR      1.10.0     1.9.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	+   interface  com.liferay.dynamic.data.mapping.storage.DDMStorageAdapterRegistry
     [exec]     		+   access     abstract
     [exec]     		+   method     getDDMStorageAdapter(java.lang.String)
     [exec]     			+   access     abstract
     [exec]     			+   return     com.liferay.dynamic.data.mapping.storage.DDMStorageAdapter
     [exec]     		+   method     getDDMStorageAdapterTypes()
     [exec]     			+   access     abstract
     [exec]     			+   return     java.util.Set
     [exec]     		+   annotated  org.osgi.annotation.versioning.ProviderType
     [exec]     	-   interface  com.liferay.dynamic.data.mapping.storage.DDMStorageAdapterTracker
     [exec]     		-   access     abstract
     [exec]     		-   method     getDDMStorageAdapter(java.lang.String)
     [exec]     			-   access     abstract
     [exec]     			-   return     com.liferay.dynamic.data.mapping.storage.DDMStorageAdapter
     [exec]     		-   method     getDDMStorageAdapterTypes()
     [exec]     			-   access     abstract
     [exec]     			-   return     java.util.Set
     [exec]     		-   annotated  org.osgi.annotation.versioning.ProviderType
     [exec]     	+   version    1.10.0
     [exec]     	-   version    1.9.0
```
Full console log:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-32/test-portal-acceptance-pullrequest(master)/6547/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by W2jx** [comment]
Force-Push is just to rebase and fix the semantic version error.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by dantewang** [comment]
@W2jx Sem Ver conflicts, please resend.

**Pull request closed without merging**
