### PR TITLE
[TS] LPS-204765

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPS-204765

See [this slack thread](https://liferay.slack.com/archives/C03LW8NUK/p1700169493139589) for additional context.

When connecting to LDAPS through JAXRS endpoint, the contextClassLoader is incorrectly set, which results in the following error: `Caused by: java.lang.ClassNotFoundException: javax.net.ssl.SSLSocketFactory cannot be found by org.apache.aries.jax.rs.whiteboard_2.0.0`

Since whiteboard should not have the contextClassLoader, we must set it to the `SafeLDAPContextImpl`, and apply the same fix found in [LPS-64800](https://liferay.atlassian.net/browse/LPS-64800), which is to include the missing package.

Please let me know if you have any questions, thanks!

CC @rotty3000

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@yuhai Code looks good to me, please help me verify test results. Please check if any more test need to be triggered.

Thanks.
Tina

**Comment by yuhai** [comment]
@tinatian, no regression bug from ci relevant test. I will run ci:test:ldap, the test's functional test will be more than relevant.

**Comment by yuhai** [comment]
ci:test:ldap

**Comment by yuhai** [comment]
@ChrisKian, please see  ci:test:ldap generated [testray-results.csv](https://test-1-1.liferay.com/job/generate-testray-csv/7682/). There are two "Unique Failures" and one "Did not run Failures".

**Unique Failures**
`LDAP#DeactivatedUserStayDeactivatedAfterLDAPImport` might be **related** with the pr, since only the pr existed the error in the history. Please see https://testray.liferay.com/home/-/testray/case_results/2484871356/history

`LDAPUserExporterImplTest` failed. It might be **unrelated** since `relevant` test should run it and its caused by `java.net.ConnectException: Connection refused (Connection refused)`, please see https://testray.liferay.com/home/-/testray/case_results/2484871420/history and its [console output](https://testray.liferay.com/reports/production/logs/2024-01/test-1-32/test-portal-acceptance-pullrequest(master)/3301/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Did not run Failures**
Please see https://testray.liferay.com/home/-/testray/case_results/2484871617/history, it might be not **related** with the pr. It existed in the history. But I don't know the cause by. 

I will run ci:test:ldap again. You may compare the latest result with the current.

cc @tinatian 

Thanks,
Hai

**Comment by yuhai** [comment]
ci:test:ldap

**Comment by yuhai** [comment]
@tinatian, @ChrisKian, no regression found. 

In three test runs(1 relevant and 2 ldap tests), `LDAPUserExporterImplTest` still was passed. But the portal log existed related WARN log, so that `PortalLogAssertorTest#testScanXMLLog` can't be passed. Compare the test with other prs, they also existed the same issue. So we can ignore it.

```
2024-01-09 09:04:01.837 WARN  [com.liferay.portal.security.ldap.test-executor-thread][SafePortalLDAPImpl:470] Unable to bind to the LDAP server
[beanshell] javax.naming.CommunicationException: localhost:10389
[beanshell] 	at com.sun.jndi.ldap.Connection.<init>(Connection.java:235) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.LdapClientFactory.createPooledConnection(LdapClientFactory.java:71) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.pool.Connections.createConnection(Connections.java:187) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.pool.Connections.getAvailableConnection(Connections.java:152) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.pool.Pool.getOrCreatePooledConnection(Pool.java:188) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.pool.Pool.getPooledConnection(Pool.java:148) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.LdapPoolManager.getLdapClient(LdapPoolManager.java:340) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1607) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2847) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:348) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:225) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:189) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:243) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84) ~[?:1.8.0_381]
[beanshell] 	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:694) ~[?:1.8.0_381]
[beanshell] 	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313) ~[?:1.8.0_381]
[beanshell] 	at javax.naming.InitialContext.init(InitialContext.java:244) ~[?:1.8.0_381]
[beanshell] 	at javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154) ~[?:1.8.0_381]
[beanshell] 	at com.liferay.portal.security.ldap.internal.SafePortalLDAPImpl.getSafeLdapContext(SafePortalLDAPImpl.java:465) [bundleFile:?]
[beanshell] 	at com.liferay.portal.security.ldap.internal.SafePortalLDAPImpl.getSafeLdapContext(SafePortalLDAPImpl.java:410) [bundleFile:?]
[beanshell] 	at com.liferay.portal.security.ldap.internal.exportimport.LDAPUserImporterImpl.importUser(LDAPUserImporterImpl.java:215) [bundleFile:?]
[beanshell] 	at com.liferay.portal.security.ldap.internal.exportimport.LDAPUserImporterImpl.importUser(LDAPUserImporterImpl.java:335) [bundleFile:?]
[beanshell] 	at com.liferay.portal.security.ldap.internal.exportimport.test.LDAPUserExporterImplTest.testAnonymousUserExport(LDAPUserExporterImplTest.java:44) [bundleFile:?]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_381]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_381]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_381]
[beanshell] 	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90) [bundleFile:?]
[beanshell] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [bundleFile:?]
[beanshell] 	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:228) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50) [bundleFile:?]
[beanshell] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [bundleFile:?]
[beanshell] 	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:307) [bundleFile:?]
[beanshell] 	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:86) [bundleFile:?]
[beanshell] 	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_381]
[beanshell] Caused by: java.net.ConnectException: Connection refused (Connection refused)
[beanshell] 	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_381]
[beanshell] 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476) ~[?:1.8.0_381]
[beanshell] 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218) ~[?:1.8.0_381]
[beanshell] 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200) ~[?:1.8.0_381]
[beanshell] 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394) ~[?:1.8.0_381]
[beanshell] 	at java.net.Socket.connect(Socket.java:606) ~[?:1.8.0_381]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_381]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_381]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.Connection.createSocket(Connection.java:369) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.Connection.<init>(Connection.java:222) ~[?:1.8.0_381]
[beanshell] 	... 52 more
```

**Comment by tinatian** [comment]
ci:forward:force

**Comment by yuhai** [comment]
ci:test:stable

**Comment by zhangyan0701** [comment]
ci:test:stable

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/146305

**Pull request closed without merging**
