### PR TITLE
[TS] LPS-182850 Excessive stacktrace on Fragment Editor Freemarker errors

### PR DESCRIPTION
**Pull request by Mikellorza**
https://liferay.atlassian.net/browse/LPS-182850

Description
-----
Add configuration to the product to not log the exception trace to the log. So, for that I added a new configuration to do that in the freemarker engine configurations and with that we can hide the exception stack trace in the log.

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:echo

**Comment by chaowang-123** [comment]
The failure is not related to this pr, @slnn could you help to add QA Passed label?

**Comment by tinatian** [comment]
Hi @Mikellorza I do not understand why you set it "true" by default. "true" is already the default value. The recommended setting is "false", please see https://freemarker.apache.org/docs/versions_2_3_22.html

> New configuration setting: log_template_exceptions (Configuration.setLogTemplateExceptions(boolean)). This specifies if TemplateException-s thrown by template processing are logged by FreeMarker or not. The default is true for backward compatibility, but that results in logging the exception twice in properly written applications, because there the TemplateException thrown by the public FreeMarker API is also logged by the caller (even if only as the cause exception of a higher level exception). Hence, in modern applications it should be set to false. (Note that this setting has no effect on the logging of exceptions caught by #attempt/#recover; those are always logged.)

**Comment by Mikellorza** [comment]
> Hi @Mikellorza I do not understand why you set it "true" by default. "true" is already the default value. The recommended setting is "false", please see https://freemarker.apache.org/docs/versions_2_3_22.html
> 
> > New configuration setting: log_template_exceptions (Configuration.setLogTemplateExceptions(boolean)). This specifies if TemplateException-s thrown by template processing are logged by FreeMarker or not. The default is true for backward compatibility, but that results in logging the exception twice in properly written applications, because there the TemplateException thrown by the public FreeMarker API is also logged by the caller (even if only as the cause exception of a higher level exception). Hence, in modern applications it should be set to false. (Note that this setting has no effect on the logging of exceptions caught by #attempt/#recover; those are always logged.)

Hi @tinatian, I added "true" as default value because now we are showing the stacktrace in the log and the client maybe may be using it to understand freemarker errors, but if you think that it is better to set it to "false" please change it and move forward. 


thanks for your notice.

**Comment by tinatian** [comment]
@Mikellorza Please make the default false, and describe the change in commit message. As the ticket is complaining excessive stack trace, with "true" as default, you actually did not fix the issue.

There is also code conflict, please rebase.

Please resend.

Thanks.
Tina

**Pull request closed without merging**
