### PR TITLE
LPS-151632 Move petra-portlet-url-builder to apps/portal

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@julschong Are you able to reopen this? I only know how to access the pending test runs if this is open

**Comment by julschong** [comment]
@vicnate5 
oof i cannot open this now, I'll make sure to leave it open next time

**Comment by vicnate5** [comment]
ci:stop

**Pull request closed without merging**
