### PR TITLE
LPD-19263 Fix DateDDMFormFieldValueRendererTest

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @MrJohn1911, remove the https://github.com/liferay-core-infra/liferay-portal/pull/6710/commits/8d39f43952b3b1ca83ab95f525da9bd736c92880. We can't do that until we fix the broken tests.

**Comment by rafaprax** [comment]
ci:stop

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@MrJohn1911 This should not be fixed on test, should be also fixed on production code.
The expected returned value when changed to CLDR seems not easy to read by human.

Tina

**Pull request closed without merging**
