### PR TITLE
LPS-200581 Clean up log4j1 package from the module com.liferay.translation.translator.aws

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@yuhai You are modifying 2 modules at the same time. If you are just moving some dependencies from the translator.aws module to the netty module, then it's fine. But you also added 2 extra dependencies to "fix" the netty module itself. This makes the PR to look weird. Does the issue you want to fix (you said about "install successfully") only reproducible after moving the dependencies?

**Comment by yuhai** [comment]
@dantewang, actually, adding extra jars "netty-codec-dns" and "netty-codec-socks" is not related with the pr. Because the pr need to let shared-dependencies-netty did the real Import-Package. I need to add the extra jars. 

For the original shared-dependencies-netty, it didn't import any packages due to the [code](https://github.com/yuhai/liferay-portal/blob/f30bc8578087c7515826bb2e120a19b9c72626ae/modules/apps/shared-dependencies/shared-dependencies-netty/bnd.bnd#L4), I may separate this to the new pr to modify shared-dependencies-netty Import-Package.  Should I firstly do this?

**Comment by dantewang** [comment]
@yuhai Yes... There's also an issue with the "real import-package" part. Everything from import-package of the aws module is moved to the netty module. And they are "not importing", with a fallback to import everything else, `*`. Are you sure that all the "not importing" ones are for Netty? What does the netty module really need to have?

**Comment by yuhai** [comment]
@dantewang, yes, I am sure those not importing for Netty. I did the test.

Removing Import-Package part from shared-dependencies-netty, and then deploy it to check generated MANIFEST.MF. It will include all necessary imported packages. After compare these with aws, I can know Netty needed. And then remove these from aws and deploy aws to check aws's MANIFEST.MF. Make sure removed not imported packages were not generated in the aws's MANIFEST.MF. You may the [rest](https://github.com/liferay-core-infra/liferay-portal/blob/a423416603d22213fb9a28a18027a0f2a073e95c/modules/apps/translation/translation-translator-aws/bnd.bnd) is aws owned.

I will resend it. Thanks.

**Pull request closed without merging**
