### PR TITLE
[Remove spring extender usage]LPS-159505

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-159505

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan the test results?


Thanks
Lily

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
Test [service-builder-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1940523983) failed with some info in log:
```
     [echo] diff --git a/modules/apps/commerce/commerce-account-api/src/main/java/com/liferay/commerce/account/service/CommerceAccountGroupLocalService.java b/modules/apps/commerce/commerce-account-api/src/main/java/com/liferay/commerce/account/service/CommerceAccountGroupLocalService.java
     [echo] index 7f4033d2ab40..0353650307d4 100644
     [echo] --- a/modules/apps/commerce/commerce-account-api/src/main/java/com/liferay/commerce/account/service/CommerceAccountGroupLocalService.java
     [echo] +++ b/modules/apps/commerce/commerce-account-api/src/main/java/com/liferay/commerce/account/service/CommerceAccountGroupLocalService.java
     [echo] @@ -121,8 +121,8 @@ public interface CommerceAccountGroupLocalService extends BaseLocalService {
     [echo]  		throws PortalException;
     [echo]  
     [echo]  	@Transactional(propagation = Propagation.SUPPORTS, readOnly = true)
     [echo] -	public int searchCommerceAccountsGroupCount(long companyId, String keywords)
     [echo] -		throws PortalException;
     ......
     [echo] .
     [echo] 
     [echo] Detected build services changes. See above build services log for more
     [echo] information. Make sure to commit in all build services results.
```
Full log: https://testray.liferay.com/reports/production/logs/2022-08/test-1-27/test-portal-acceptance-pullrequest(master)/4402/service-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:commerce

**Comment by slnn** [comment]
Hi @dantewang

I fix the issue that @zhangyan0701 pointed out in the comment and forced push this branch.

@zhangyan0701  I have triggered tests on this pull please help to scan the test results when they are finished, thanks! 

Lily

**Comment by dantewang** [comment]
@slnn In the force push the only difference is that you add the last commit, right?

**Comment by zhangyan0701** [comment]
Hi @catarineaguiar Could you check the test results when they finish? Thanks!

**Comment by catarineaguiar** [comment]
@slnn no regressions found

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121706

**Pull request closed without merging**
