### PR TITLE
[Bug Fix]FACES-3625

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by yuhai** [comment]
@tinatian, @dantewang, the fix can solve the issue.

**Comment by tinatian** [comment]
@koor4356 Please help me scan the test results.

Thanks.
Tina.

**Comment by koor4356** [comment]
Okay, thanks! but sf is failed.

**Comment by koor4356** [comment]
@tinatian 
It looks good except that most tests failed before they run.

**Comment by tinatian** [comment]
@koor4356 Is it good to go or I need to rerun the test?

Tina

**Comment by koor4356** [comment]
@tinatian, I suggest we should re-run if it is not urgently needed to emerge. Also, sf is failed. Did you look at it?

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by koor4356** [comment]
ci:test

**Comment by koor4356** [comment]
ci:relevant

**Comment by koor4356** [comment]
ci:stable

**Comment by koor4356** [comment]
ci:test:relevant

**Comment by koor4356** [comment]
ci:test:stable

**Comment by koor4356** [comment]
@tinatian 
It looks good. No unique failures.

**Comment by tinatian** [comment]
@shuyangzhou This is good to go.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
