### PR TITLE
[Remove Stream/Optional usage] LPS-172250 remove_stream_and_optional_in_portal_search_solr8_impl

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Resend: https://github.com/liferay-core-infra/liferay-portal/pull/2944
This is for ticket https://issues.liferay.com/browse/LPS-172250.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:search-solr

**Comment by jeffwu0724** [comment]
fixed the code conflict and rerun the test

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128649

**Pull request closed without merging**
