### PR TITLE
LPS-169887 Remove TemplateReource usages from RuntimePage

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by julschong** [comment]
rebased to test ci again

**Comment by julschong** [comment]
pushed to test ci again
removed some ts files

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong all tests are failling due to:

```
 [exec] /opt/dev/projects/github/liferay-portal/modules/apps/layout/layout-taglib/src/main/java/com/liferay/layout/taglib/servlet/taglib/RenderLayoutStructureTag.java:733: error: incompatible types: com.liferay.portal.kernel.template.StringTemplateResource cannot be converted to java.lang.String
     [exec] 					new StringTemplateResource(templateId, templateContent),
     [exec] 					^
     [exec] 
     [exec] > Task :apps:layout:layout-taglib:compileJava
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
     [exec] 1 error
     [exec] 
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-28/test-portal-acceptance-pullrequest(master)/5287/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
test after changing StringTemplateResource usage in RenderLayoutStructureTag

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@julschong Please also remove RuntimeLogic and its implementations, they are only used in the method you removed, after the removal, no one is using them.

Tina.

**Pull request closed without merging**
