### PR TITLE
[Method Ref 2] LPS-164448 12-2

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:reports

**Comment by dantewang** [comment]
@JanisZhang Looks like I missed some integration tests to apply. Could you please take a look and fix them? Thanks!

**Comment by JanisZhang** [comment]
@dantewang, sure, thanks!

**Pull request closed without merging**
