### PR TITLE
[TS] LPS-168194

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-168194](https://issues.liferay.com/browse/LPS-168194)

Dear Team,

Please review my changes. The patched JDom 1 library will be applied on 7.2.x and below where bumping to JDom 2 (as done by [LPS-137136](https://issues.liferay.com/browse/LPS-137136)) is not possible because of a caused major version change. 

Basically I applied the same changes that Dante made on master to patch JDom 2 and based on [his confirmation](https://github.com/dantewang/liferay-portal-ee/pull/128#issuecomment-1297921417) it should be fine.

Thank you,
Istvan

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
@istvansajtos Please include the details in the commit message why you made this change. Just looking at the commit, I did not know if you created the fix or you copied the fix from somewhere.

Thanks.
Tina

**Comment by istvansajtos** [comment]
@tinatian I gave some some explanation to my changes in commit message: https://github.com/liferay-core-infra/liferay-portal/pull/2401/commits/fd2112899ccbe11ae0580d292646e9f5fa43f487

I also replaced incorrect LPS ids in commit message and patch file name.

Thank you!

**Comment by istvansajtos** [comment]
I closed the ticket by accident, please ignore it. :)

**Comment by tinatian** [comment]
ci:forward

FYI @shuyangzhou

**Pull request closed without merging**
