### PR TITLE
[OrderByComparator] LPD-26917 Clean up and Apply Singleton in module portal-workflow - Part II

### PR DESCRIPTION
**Pull request by jpcchaves**
LPD-26917 Clean up and Apply Singleton in module portal-workflow - Part II

### CODE REVIEW

**Comment by jpcchaves** [comment]
ci:test:relevant

**Comment by jpcchaves** [comment]
ci:report:2573210343

**Comment by jpcchaves** [comment]
ci:test:relevant

**Comment by jpcchaves** [comment]
ci:test:sf

**Comment by jpcchaves** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
Problems found in these SF changes!

I'll fix it and send it back!

**Pull request closed without merging**
