### PR TITLE
LPS-170144 Remove TemplateResourceLoaderUtil usage in ThemeUtil

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong Semver error only. No regressions found in all other tests.
```
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.taglib.util                            MAJOR      14.0.0     14.0.0     15.0.0     VERSION INCREASE REQUIRED
[beanshell] 	-   class      com.liferay.taglib.util.ThemeUtil
[beanshell] 		-   method     <init>()
[beanshell] 			-   return     void
[beanshell] 		-   method     clone()
[beanshell] 			-   access     protected
[beanshell] 			-   return     java.lang.Object
[beanshell] 		-   method     doIncludeFTL(javax.servlet.ServletContext,javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse,java.lang.String,com.liferay.portal.kernel.model.Theme,boolean,boolean)
[beanshell] 			-   access     protected
[beanshell] 			-   access     static
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   method     equals(java.lang.Object)
[beanshell] 			-   return     boolean
[beanshell] 		-   method     finalize()
[beanshell] 			-   access     protected
[beanshell] 			-   return     void
[beanshell] 		-   method     getPortletId(javax.servlet.http.HttpServletRequest)
[beanshell] 			-   access     static
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   method     hashCode()
[beanshell] 			-   return     int
[beanshell] 		-   method     include(javax.servlet.ServletContext,javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse,java.lang.String,com.liferay.portal.kernel.model.Theme)
[beanshell] 			-   access     static
[beanshell] 			-   return     void
[beanshell] 		-   method     include(javax.servlet.ServletContext,javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse,java.lang.String,com.liferay.portal.kernel.model.Theme,boolean)
[beanshell] 			-   access     static
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   method     toString()
[beanshell] 			-   return     java.lang.String
```
[Log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-27/test-portal-acceptance-pullrequest(master)/6040/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
force pushed for semantic versioning

**Comment by julschong** [comment]
ci:test:relevant

**Pull request closed without merging**
