### PR TITLE
[Bug fix] LPS-83930

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on https://github.com/liferay-core-infra/liferay-portal/pull/30. In order to let you review clearly. I keep the [commit](https://github.com/liferay-core-infra/liferay-portal/commit/848b625132868fd3fb55388882111dd97e8e1461) as one commit. After you review, I will merge it to the previous commit.

For the removed [commit](https://github.com/liferay-core-infra/liferay-portal/pull/30/commits/4e6dfd53c9c9afe0b2f4c14f747e3903773d129b), it will be treated as the different issue. I will check why httpServletRequest is different from pageContext.getRequest() it.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Reviewing

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/45
I just did SF and merged the commit you mentioned so the logic remain same with this one.

@zhangyan0701 could you please review the test result? Thanks!

**Comment by zhangyan0701** [comment]
No related failure found.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/45

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
