### PR TITLE
[Urgent][Security Bugs]LPD-18681 upgrade commons-compress to 1.26.0

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

Resent: https://github.com/liferay-core-infra/liferay-portal/pull/6766
This PR is for https://liferay.atlassian.net/browse/LPD-18681.
In this PR, I changed to use compileOnly for all commons-io, move commons-io and commons-fileupload(because fileupload need commons-io to compile, and we should move them together) to shared-dependencies, upgrade commons-compress and upgrade commons-io.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:report:2549937628

**Comment by jeffwu0724** [comment]
ci:report:2549884383

**Comment by jeffwu0724** [comment]
The failing test are not related

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
@tinatian I will double check the relevant result once the test are ready.

**Comment by jeffwu0724** [comment]
closed this PR as it had been sent to BChan

**Comment by jeffwu0724** [comment]
ci:close

**Pull request closed without merging**
