### PR TITLE
[Method References 2] LPS-170790 Convert method reference to ServiceTracker in class ActionExecutorManagerImpl(portal-workflow-kaleo-runtime-impl)

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(1/19 14:54)

**Comment by W2jx** [comment]
Force-Push is just to resolve conflicts.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
@W2jx As we discussed, please resend. Thanks!

**Pull request closed without merging**
