### PR TITLE
[Components with more than 1 service] LPS-179214 Refactor ScreenNavigationCategory components from account-admin-web module

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://issues.liferay.com/browse/LPS-179214

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:usm

**Comment by catarineaguiar** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
ci:stop:startup

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@MrJohn1911 @daiazius @RenanUmV  https://github.com/brianchandotcom/liferay-portal/pull/133052#issuecomment-1501415498

Could you double check all the existing PRs?

**Comment by MrJohn1911** [comment]
Hi @dantewang, this pull follows the pattern that we'v discussed about, since I have removed the ENTRY_KEYs that weren't used when applying the `getCategoryKey() -> getEntryKey()`

**Comment by MrJohn1911** [comment]
In this last push, I reordered and merged some commits, so the commits sequence makes more sense.

CC: @rafaprax

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:usm

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian @rafaprax

**Pull request closed without merging**
