### PR TITLE
LPS-173280 Remove Stream and Optional usages for module: depot-test

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong regression found:

```
     [exec] com.liferay.depot.web.internal.portlet.action.test.UpdateMembershipsMVCActionCommandTest > testProcessActionWithAddGroupDepotIds FAILED
     [exec]     javax.portlet.PortletException: java.lang.ArrayIndexOutOfBoundsException: 0
     [exec]     	at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCActionCommand.processAction(BaseMVCActionCommand.java:65)
     [exec]     	at com.liferay.depot.web.internal.portlet.action.test.UpdateMembershipsMVCActionCommandTest.testProcessActionWithAddGroupDepotIds(UpdateMembershipsMVCActionCommandTest.java:99)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-26/test-portal-acceptance-pullrequest(master)/7116/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
fixed and test ci again

> @julschong regression found:
> 
> ```
>      [exec] com.liferay.depot.web.internal.portlet.action.test.UpdateMembershipsMVCActionCommandTest > testProcessActionWithAddGroupDepotIds FAILED
>      [exec]     javax.portlet.PortletException: java.lang.ArrayIndexOutOfBoundsException: 0
>      [exec]     	at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCActionCommand.processAction(BaseMVCActionCommand.java:65)
>      [exec]     	at com.liferay.depot.web.internal.portlet.action.test.UpdateMembershipsMVCActionCommandTest.testProcessActionWithAddGroupDepotIds(UpdateMembershipsMVCActionCommandTest.java:99)
>      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-26/test-portal-acceptance-pullrequest(master)/7116/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:depot

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
