### PR TITLE
[Hibernate][For review only] LPS-128873 Upgrade to Hibernate 5

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Sending this for early review. This PR includes https://github.com/liferay-core-infra/liferay-portal/pull/467 since it's not merged yet; we will also send a separate PR for the Websphere upgrade fix but it's also included in this PR for now.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
@GinsonRen Rebased on top of master Git ID 6f8578c445a12e8539c3c26030f0f5961ba6048f and force pushed. You can run tests with it.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by GinsonRen** [comment]
@tinatian @dantewang Here is the diff result for login, it seems no big regression here. Other cases are still running, I will update the results later.

Login |   |   |   |  
-- | -- | -- | -- | --
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
BaseLine | 6f8578c4 | 44505 | 269 | -
PR-482 | - | 44378 | 265 | -0.29%

**Comment by tinatian** [comment]
@GinsonRen Login looks good. Please move on to get a result for all other test cases.

Thanks.
Tina

**Comment by GinsonRen** [comment]
@tinatian @dantewang Here are results for other cases:

WC
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 6f8578c4 | 59156 | 530 | -
PR-482 | - | 58254 | 482 | -1.52%

MB
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 6f8578c4 | 11240 | 180 | -
PR-482 | - | 11110 | 100 | -1.16%

Blog
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 6f8578c4 | 5711 | 72.3 | -
PR-482 | - | 5695 | 283 | -0.28%

DL
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 6f8578c4 | 19341 | 595 | -
PR-482 | - | 19206 | 894 | -0.70%

Wiki
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 6f8578c4 | 12889 | 786 | -
PR-482 | - | 13604 | 179 | 5.55%

AP
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 6f8578c4 | 22605 | 405 | -
PR-482 | - | 23533 | 384 | 4.11%

@111Anna Please check startup performance.

**Comment by 111Anna** [comment]
@tinatian @dantewang  Here are results for startup:

Startup

Portal Version | Git Id | First Startup | Second Startup | Third Startup | Fourth Startup |  Fifth Startup | Average Startup
-- | -- | -- | -- | -- | -- | -- | -- | 
BaseLine | 6f8578c | 20545 | 20804 | 20373 | 20048 | 20377 | 20429.4ms |
PR-482 | - | 22573 | 21942 | 21248 | 22443 | 21351 | 21911.4ms |

**Comment by 111Anna** [comment]
Here are results for startup:
Startup
Portal Version | Git Id | First Startup | Second Startup | Third Startup | Fourth Startup |  Fifth Startup | Average Startup | Session Count Change （%）
-- | -- | -- | -- | -- | -- | -- | -- | -- |
BaseLine | 6f8578c | 20545 | 20804 | 20373 | 20048 | 20377 | 20429.4ms | -  |
PR-482 | - | 22573 | 21942 | 21248 | 22443 | 21351 | 21911.4ms | 7.3% |

**Comment by 111Anna** [comment]
@tinatian @dantewang Here are results for startup:
Startup
Portal Version | Git Id | First Startup | Second Startup | Third Startup | Fourth Startup |  Fifth Startup | Average Startup | Session Count Change （%）
-- | -- | -- | -- | -- | -- | -- | -- | -- |
BaseLine | 6f8578c | 20545 | 20804 | 20373 | 20048 | 20377 | 20429.4ms | - |
PR-482 | - | 22573 | 21942 | 21248 | 22443 | 21351 | 21911.4ms | 7.3% |

**Comment by tinatian** [comment]
@dantewang @111Anna This is a big regression for startup, please gather profiles for it.

Thanks.
Tina.

**Comment by 111Anna** [comment]
@tinatian @dantewang  I have uploaded the startup profiles to Amazon cloud.

**Comment by dantewang** [comment]
@tinatian Will look into it.

**Comment by dantewang** [comment]
@111Anna Thanks!

**Comment by tinatian** [comment]
Close, as we talked, please resend with separate pulls.

Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
