### PR TITLE
[Component with its own class name as service type] LPS-197370 Refactor components from lima modules part 2

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-197370](https://liferay.atlassian.net/browse/LPS-197370)

Previous Pull: https://github.com/liferay-core-infra/liferay-portal/pull/5875

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
@RenanUmV No regressions found.

**Comment by rafaprax** [comment]
Hey @RenanUmV, keep the inline method changes in a separate commit. Thx

**Comment by RenanUmV** [comment]
resent here: https://github.com/liferay-core-infra/liferay-portal/pull/6234

**Pull request closed without merging**
