### PR TITLE
LPS-147006 Remove closure-compiler.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
Hey @vicnate5, Can you help me to scan these test results? Thx

**Comment by vicnate5** [comment]
@rafaprax No regressions found.

**Comment by rafaprax** [comment]
Hi @tinatian, this pr is ready for your review. Thx

**Comment by rafaprax** [comment]
The conflicts were fixed.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
