### PR TITLE
[Components with more than 1 service] LPS-179235 Refactor DTOConverter components with more than 1 service type from headless-commerce-admin-pricing-impl part 2

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-179235](https://issues.liferay.com/browse/LPS-179235)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:commerce

**Review by rafaprax — CHANGES_REQUESTED** [review]
@RenanUmV break commits by DTO version since they are indeed distinct components/classes. Thx

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:commerce

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
