### PR TITLE
[Remove Deprecation]LPS-147023

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
ci:test:sharepoint

**Comment by vicnate5** [comment]
There is one unique failure that happened here and I am unable to run the test locally. Re-running just the Sharepoint suite here to make sure we are OK.

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113474

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
