### PR TITLE
remove_deprecated_part_7

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

I have removed deprecated methods or classes for "portal-impl/src/com/liferay/portlet/trash/util",
"portal-impl/src/com/liferay/portlet", "portal-impl/src/com/liferay/portlet/StrutsPortlet.java", "portal-impl/src/com/liferay/portlet/SecurityPortletContainerWrapper.java", "portal-impl/src/com/liferay/portal/template".
Thanks for checking. see https://github.com/jeffwu0724/liferay-portal/pull/33

Thanks,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by kyle-miho** [comment]
@jeffwu0724 failures unrelated

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
