### PR TITLE
[TS] LPS-205139

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @marianoalvarosaiz ,

It looks like there are some relevant test failures, such as:
- Semver for certain packages
- Rest builder test failures

Can you take a look?

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @marianoalvarosaiz ,

It looks like there's still an issue regarding rest-builder: 
```
[exec] > Task :util:portal-tools-rest-builder:jar UP-TO-DATE
[exec] > Task :util:portal-tools-rest-builder:autoUpdateXml SKIPPED
[exec] > Task :util:portal-tools-rest-builder:deploy UP-TO-DATE
[exec] > Task :util:portal-tools-rest-builder:deployDependencies
[exec] > Task :util:portal-tools-rest-builder:deployConfigs NO-SOURCE
[exec] Exception in thread "main" java.lang.NoSuchMethodError: com.liferay.portal.tools.ToolsUtil.getPackagePath(Ljava/io/File;)Ljava/lang/String;
[exec] 	at com.liferay.portal.tools.java.parser.JavaParser._parse(JavaParser.java:1000)
[exec] 	at com.liferay.portal.tools.java.parser.JavaParser._parse(JavaParser.java:994)
[exec] 	at com.liferay.portal.tools.java.parser.JavaParser.parse(JavaParser.java:82)
[exec] 	at com.liferay.portal.tools.java.parser.JavaParser.parse(JavaParser.java:69)
[exec] 	at com.liferay.portal.tools.java.parser.JavaParser.parse(JavaParser.java:63)
[exec] 	at com.liferay.portal.tools.rest.builder.internal.util.FileUtil._format(FileUtil.java:149)
[exec] 	at com.liferay.portal.tools.rest.builder.internal.util.FileUtil.write(FileUtil.java:142)
[exec] 	at com.liferay.portal.tools.rest.builder.RESTBuilder._createOpenAPIResourceFile(RESTBuilder.java:1015)
[exec] 	at com.liferay.portal.tools.rest.builder.RESTBuilder.build(RESTBuilder.java:261)
[exec] 	at com.liferay.portal.tools.rest.builder.RESTBuilder.main(RESTBuilder.java:108)
[exec] 
[exec] > Task :apps:analytics:analytics-dxp-entity-rest-impl:buildREST FAILED
```
- Reference: (unit-jdk8) 
https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/338587/console

**Additional Notes**
If we search in the source code for: `"com.liferay.portal.tools.java.parser"`, we see the following files:
- modules/util/portal-tools-service-builder/build.gradle
- modules/util/portal-tools-rest-builder/build.gradle
- modules/util/source-formatter/build.gradle

And so, it looks like the `source-formatter` module may also need to be updated, if it has logic that eventually calls `ToolsUtil.getPackagePath`

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
Hi @ericyanLr ,
 the SF failure has been fixed, see https://github.com/brianchandotcom/liferay-portal/commit/d87f460f11a4fdc9240d0d43ebb6a171a720d128. Once Brian's master is merged I will rebase it and resend.
Kind regards.

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:2534244051

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6584

**Pull request closed without merging**
