### PR TITLE
LPS-143634 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@koor4356 Can you check this one?

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
@tinatian,
Can you look into this error? it is causing more tests to fail and it looks like it is related to this PR. Thanks!

`ERROR [http-nio-8080-exec-9][IncludeTag:128] Current URL /group/site-name/~/control_panel/manage?p_p_id=com_liferay_product_navigation_product_menu_web_portlet_ProductMenuPortlet&p_p_lifecycle=0&p_p_state=exclusive&_com_liferay_product_navigation_product_menu_web_portlet_ProductMenuPortlet_mvcPath=%2Fportlet%2Fproduct_menu.jsp&_com_liferay_product_navigation_product_menu_web_portlet_ProductMenuPortlet_selPpid=com_liferay_style_book_web_internal_portlet_StyleBookPortlet generates exception: java.lang.NullPointerException
java.lang.NullPointerException: null
	at com.liferay.exportimport.web.internal.portlet.ExportImportControlPanelEntry.hasAccessPermissionExplicitlyGranted(ExportImportControlPanelEntry.java:58) ~[?:?]
	at com.liferay.portal.kernel.portlet.BaseControlPanelEntry.hasAccessPermission(BaseControlPanelEntry.java:44) ~[portal-kernel.jar:?]
	at com.liferay.application.list.BasePanelApp.isShow(BasePanelApp.java:160) ~[bundleFile:?]
	at com.liferay.depot.web.internal.application.list.DepotPanelAppController$PanelAppWrapper.isShow(DepotPanelAppController.java:232) ~[?:?]
	at com.liferay.application.list.PanelAppRegistry.lambda$getPanelApps$0(PanelAppRegistry.java:122) ~[bundleFile:?]
	at com.liferay.portal.kernel.util.ListUtil.filter(ListUtil.java:149) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.util.ListUtil.filter(ListUtil.java:160) ~[portal-kernel.jar:?]
	at com.liferay.application.list.PanelAppRegistry.getPanelApps(PanelAppRegistry.java:118) ~[bundleFile:?]
	at com.liferay.application.list.PanelAppRegistry.getPanelApps(PanelAppRegistry.java:93) ~[bundleFile:?]
	at com.liferay.application.list.taglib.servlet.taglib.PanelCategoryTag.setAttributes(PanelCategoryTag.java:157) ~[bundleFile:?]
	at com.liferay.taglib.util.IncludeTag.callSetAttributes(IncludeTag.java:181) ~[bundleFile:?]
	at com.liferay.taglib.util.IncludeTag.doStartTag(IncludeTag.java:105) ~[bundleFile:?]
	at org.apache.jsp.panel_005fcategory_005fcontent.page_jsp._jspService(page_jsp:130) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111) ~[jasper.jar:9.0.56]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411) ~[jasper.jar:9.0.56]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473) ~[jasper.jar:9.0.56]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377) ~[jasper.jar:9.0.56]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:364) ~[bundleFile:?]`

https://testray.liferay.com/reports/production/logs/2022-02/test-1-30/test-portal-acceptance-pullrequest(master)/2033/functional-smoke-tomcat90-mysql57-jdk8/0/0/liferay-log.txt.gz?authuser=0

https://testray.liferay.com/home/-/testray/case_results/1610186014

**Comment by tinatian** [comment]
@koor4356 Do you have steps to reproduce this?
@julschong Please take a look at this issue.

Tina.

**Comment by koor4356** [comment]
**Step to reproduce**
1. Start up Liferay portal
2. Navigate to style book

You should see the error below or similar to error above.
`com.liferay.exportimport.web.internal.portlet.ExportImportControlPanelEntry.hasAccessPermissionExplicitlyGranted(ExportImportControlPanelEntry.java:58) ~[?:?]
	at com.liferay.portal.kernel.portlet.BaseControlPanelEntry.hasAccessPermission(BaseControlPanelEntry.java:44) ~[portal-kernel.jar:?]
	at com.liferay.application.list.BasePanelApp.isShow(BasePanelApp.java:160) ~[bundleFile:?]
	at com.liferay.depot.web.internal.application.list.DepotPanelAppController$PanelAppWrapper.isShow(DepotPanelAppController.java:232) ~[?:?]
	at com.liferay.application.list.PanelAppRegistry.lambda$getPanelApps$0(PanelAppRegistry.java:122) ~[bundleFile:?]
	at com.liferay.portal.kernel.util.ListUtil.filter(ListUtil.java:149) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.util.ListUtil.filter(ListUtil.java:160) ~[portal-kernel.jar:?]
	at com.liferay.application.list.PanelAppRegistry.getPanelApps(PanelAppRegistry.java:118) ~[bundleFile:?]
	at com.liferay.application.list.PanelAppRegistry.getPanelApps(PanelAppRegistry.java:93) ~[bundleFile:?]
	at com.liferay.application.list.taglib.servlet.taglib.PanelCategoryTag.setAttributes(PanelCategoryTag.java:157) ~[bundleFile:?]
	at com.liferay.taglib.util.IncludeTag.callSetAttributes(IncludeTag.java:181) ~[bundleFile:?]
	at com.liferay.taglib.util.IncludeTag.doStartTag(IncludeTag.java:105) ~[bundleFile:?]
	at org.apache.jsp.panel_005fcategory_005fcontent.page_jsp._jspService(page_jsp:130) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111) ~[jasper.jar:9.0.56]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411) ~[jasper.jar:9.0.56]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473) ~[jasper.jar:9.0.56]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377) ~[jasper.jar:9.0.56]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:364) ~[bundleFile:?]`

**Pull request closed without merging**
