### PR TITLE
LPS-158624 Cleanup petra-xml

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
Many unit tests failed by an issue which will be fixed here https://github.com/liferay-core-infra/liferay-portal/pull/2049. It would be better to rerun relevant when that is merged.

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Possible regressions:
1. Integration test [UserGroupUADExporterTest](https://testray.liferay.com/home/-/testray/case_results/2008445492) failed:
```
   [exec] com.liferay.user.groups.admin.uad.exporter.test.UserGroupUADExporterTest > testExportModelWithCDATASyntax FAILED
     [exec]     com.liferay.portal.kernel.exception.SystemException: org.dom4j.DocumentException: Error on line 1 of document  : The character sequence "]]>" must not appear in content unless used to mark the end of a CDATA section.
```

Full console:
https://testray.liferay.com/reports/production/logs/2022-10/test-1-27/test-portal-acceptance-pullrequest(master)/5390/modules-integration-mysql57-jdk8/3/24/jenkins-console.txt.gz?authuser=0

2. [service-builder-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2008445399) failed with errors like below:
```
     [echo] diff --git a/modules/apps/document-library/document-library-uad/src/main/java/com/liferay/document/library/uad/exporter/BaseDLFileEntryTypeUADExporter.java b/modules/apps/document-library/document-library-uad/src/main/java/com/liferay/document/library/uad/exporter/BaseDLFileEntryTypeUADExporter.java
... ...
     [echo] diff --git a/modules/apps/document-library/document-library-uad/src/main/java/com/liferay/document/library/uad/exporter/BaseDLFileEntryUADExporter.java b/modules/apps/document-library/document-library-uad/src/main/java/com/liferay/document/library/uad/exporter/BaseDLFileEntryUADExporter.java
... ...
     [echo] diff --git a/modules/apps/users-admin/users-admin-uad/src/main/java/com/liferay/users/admin/uad/exporter/BaseUserTrackerUADExporter.java b/modules/apps/users-admin/users-admin-uad/src/main/java/com/liferay/users/admin/uad/exporter/BaseUserTrackerUADExporter.java
```
Full console:
https://testray.liferay.com/reports/production/logs/2022-10/test-1-27/test-portal-acceptance-pullrequest(master)/5390/service-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0

3. [semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2008445520) failed:
`     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/81.0.0/d41e7e4f834a08a646b56b93009307ae57488ab4/com.liferay.portal.kernel-81.0.0.jar`

Full console:
https://testray.liferay.com/reports/production/logs/2022-10/test-1-27/test-portal-acceptance-pullrequest(master)/5390/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by julschong** [comment]
ci:reopen

**Pull request closed without merging**
