### PR TITLE
LPS-155715 DB partition Cache

### PR DESCRIPTION
**Pull request by tinatian**
This pull is based on https://github.com/liferay-core-infra/liferay-portal/pull/1146

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian No regressions found, the new automation is passing.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by tinatian** [comment]
FYI @achaparro

**Comment by tinatian** [comment]
Rebase to fix baseline conflicts

**Comment by tinatian** [comment]
Rebase and force push.

Tina

**Comment by vicnate5** [comment]
Rebased and Added company removal functional testing
https://github.com/liferay-core-infra/liferay-portal/pull/1179

**Pull request closed without merging**
