### PR TITLE
LPD-5302 5-21 Benchmark Unit Test

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou @tinatian This is the benchmark unit test.

The integration test to ensure correctness passes on my local on vanilla portal.

For the unit test, the steps are:

1. Create a new company in portal;
2. Run the test, use `-Dbenchmark.test.key=value` to provide properties; see https://liferay.atlassian.net/browse/LPD-5302 for available properties.

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian Actually https://github.com/dantewang/liferay-portal/pull/2377/commits/14ca201522381d427f5f8896125391f091d36fe1 is not needed as you've set https://github.com/liferay-core-infra/liferay-portal/pull/7014/commits/f677c1583f9168c8c779c52e739ed1a6d99dfef2, I missed that before.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
