### PR TITLE
[TS]LPD-2110

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:2542241959

**Comment by ericyanLr** [comment]
**ci:report:analysis**
No unique failures

Marking this as **QA Passed** and **Ready to Review (no regression)**

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/147447
Please also note that I merged your two commits into this https://github.com/liferay-core-infra/liferay-portal/pull/6664/commits/0361efefdb151bd25607d07a476641451c424f86.

The goal is to make it clear that where the logic is moved from.

Thanks.
Tina.

**Pull request closed without merging**
