### PR TITLE
LPS-178022 Remove Stream and Optional usages in portal-search-web final

### PR DESCRIPTION
**Pull request by julschong**
@tinatian Hi Tina,

This PR is built on top of your PR currently in review with Brian: https://github.com/brianchandotcom/liferay-portal/pull/134142

This would be the final clean up for portal-search-web module.

After this, we can move on to portal-search-web-api which I also finished and testing here: https://github.com/julschong/liferay-portal/pull/845

Thank you!

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
ci:test:search

**Comment by julschong** [comment]
@tinatian https://github.com/brianchandotcom/liferay-portal/pull/134142 is merged in with no change from Brian

**Comment by catarineaguiar** [comment]
no regressions found.

**Pull request closed without merging**
