### PR TITLE
[Method References 3] LPS-179399 Convert method reference to field reference in classes FullPageApplicationLayoutTypeController, FacebookConnectNavigationPreJSPDynamicInclude, LoremIpsumMBMessageDemoDataCreatorImpl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(3/24 13:30)

**Comment by W2jx** [comment]
no conflicts(3/27 9:41)

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
