### PR TITLE
[Remove Unused Reference] LPS-164336 Remove unused reference variable in module saml-web(dxp)

### PR DESCRIPTION
**Pull request by W2jx**
Hi  @tinatian @dantewang , I hve removed unused reference variable in module saml-web(dxp).

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @catarineaguiar , Could you please help me check the test results ? Thanks!

**Comment by zhangyan0701** [comment]
ci:test:saml

**Comment by catarineaguiar** [comment]
@W2jx no regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
