### PR TITLE
[Remove unused field] LPS-199002 Remove unused reference field _sites

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(10/13 8:28)

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142190

cc @shuyangzhou

**Pull request closed without merging**
