### PR TITLE
[Optional Reference]Lps 185415 5 29

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-185415

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by slnn** [comment]
The fix for the tests in this pull also fixed these tests in https://github.com/liferay-core-infra/liferay-portal/pull/4623, so I will send them together.

**Comment by slnn** [comment]
The fix for the tests in this pull also fixed these tests in https://github.com/liferay-core-infra/liferay-portal/pull/4623, so I will send them together.

**Pull request closed without merging**
