### PR TITLE
LPS-178288 Remove apps/petra checking logic in PortalClassPathUtil

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by Kvale1733** [comment]
@julschong No regressions found, but looks like sf wants you to remove this import since it's no longer used.

`import` java.io.IOException;``

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
rerun sf

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133042

**Pull request closed without merging**
