### PR TITLE
[Method References 2] LPS-164374 Remove unused reference variable in module portal-workflow-metrics-rest-impl(dxp)

### PR DESCRIPTION
**Pull request by W2jx**
Hi  @tinatian @dantewang , I have removed unused reference variable in module portal-workflow-metrics-rest-impl(dxp).

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @catarineaguiar , Could you please help me check the test results ? Thanks!

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
@W2jx @dantewang No regressions found.

**Comment by dantewang** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/124586

cc @shuyangzhou @tinatian

**Pull request closed without merging**
