### PR TITLE
[URGENT][TS] LPS-192684

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by brunofalc** [comment]
added to Urgent, because it's related to a customer

**Comment by catarineaguiar** [comment]
ci:test:clustering

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by tinatian** [comment]
@marianoalvarosaiz 

I do not understand why this is a problem, what is the issue you see on LXC? 

When a company is added/removed with db partition enabled, its corresponding sharded cache in ehcache manager will be added/removed when needed, but this add and remove action should not affect other sharded caches for other companies. Thus, notifyPortalCacheRemoved in both EntityCache and FinderCache should NOT response to a sharded ehcache removal from cache manager.

The changes in this pull does not make any sense to me, I am going to close this pull.

Thanks.
Tina.

**Pull request closed without merging**
