### PR TITLE
[LogContext]LPS-145235

### PR DESCRIPTION
**Pull request by vicnate5**
@jkappler

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:acceptance-upstream

**Comment by vicnate5** [comment]
ci:test:acceptance-functional

**Comment by jkappler** [comment]
thanks again @vicnate5!

**Comment by vicnate5** [comment]
@tinatian This is now ready to go, tests are passing.

**Comment by tinatian** [comment]
@shuyangzhou This is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114102

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
