### PR TITLE
[TS] LPS-183708 - language.properties should be used if no key exists for a given locale

### PR DESCRIPTION
**Pull request by wanderlast**
Resend of https://github.com/liferay-core-infra/liferay-portal/pull/5267 with requested changes.

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:friendly-url

**Comment by Kvale1733** [comment]
No regressions found. Testing passed following the ticket steps.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5327

**Pull request closed without merging**
