### PR TITLE
[System Properties] LPS-158208 Add new functionality to SystemProperties: resolve property references

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I add a new method and unit test in this pr.
LPS-158208 depends on LPS-158206

Detail: https://github.com/liferay-core-infra/liferay-portal/pull/1220

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @catarineaguiar , Could you please help me check the test results when they finish ? Thanks!

**Comment by catarineaguiar** [comment]
@W2jx no regressions found.

**Comment by W2jx** [comment]
push code for conflict resolution

**Comment by tinatian** [comment]
@W2jx Please simplify your unit test by avoid using variables, use literal string directly to make it more readable.

Thanks.
Tina.

**Comment by W2jx** [comment]
Hi @tinatian , I have updated the code.

**Comment by W2jx** [comment]
Hi @tinatian , I have updated the code.

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@tinatian this pull is good to go

**Pull request closed without merging**
