### PR TITLE
[Spring Beans] LPS-203946 Remove RepositoryFactoryImpl , RepositoryFactoryUtil, RepositoryClassDefinitionCatalogImpl, RepositoryClassDefinitionCatalogUtil from repository-spring.xml

### PR DESCRIPTION
**Pull request by haydenzheng314**
Ticket: https://liferay.atlassian.net/browse/LPS-203946
Based on the [comment](https://github.com/liferay-core-infra/liferay-portal/pull/5987#issuecomment-1813129320)
Thanks

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:upgrade

**Comment by LisztLiszt** [comment]
ci:report:2543821639

**Pull request closed without merging**
