### PR TITLE
[Scheduler]LPS-169028

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@tinatian semver error:

```
     [echo] 
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.kernel.scheduler                MAJOR      11.0.0     11.0.0     12.0.0     VERSION INCREASE REQUIRED
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-26/test-portal-acceptance-pullrequest(master)/6012/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
code conflicts with Brian's upstream, wait for changes to be merged in and rebase

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126699

**Pull request closed without merging**
