### PR TITLE
LPS-182384 move portal-upload to modules part One

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This is part One of moving portal-upload to modules. As we talked, in this part we only trying to avoid using uploadservletrequestimpl directly by using factory; and avoid directly using uploadportletrequestimpl by using test-util.
There is still a usage of uploadportletrequestimpl in JSONWebServiceServiceActionTest that I am not sure how to remove yet. 
Thanks for checking

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
@jeffwu0724 Regressions found.

1. Compile issue
```
  [exec] > Task :apps:portal:portal-upload-impl:compileTestJava FAILED
     [exec] 
     [exec] > Task :apps:portal:portal-upload-impl:processTestResources
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal/portal-upload-impl/src/test/java/com/liferay/portal/upload/internal/UploadServletRequestImplTest.java:23: error: package com.liferay.portal.upload.test.util does not exist
     [exec] import com.liferay.portal.upload.test.util.UploadTestUtil;
     [exec]                                           ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal/portal-upload-impl/src/test/java/com/liferay/portal/upload/internal/UploadServletRequestImplTest.java:65: error: cannot find symbol
     [exec] 			UploadTestUtil.createUploadServletRequest(
     [exec] 			^
     [exec]   symbol:   variable UploadTestUtil
     [exec]   location: class com.liferay.portal.upload.internal.UploadServletRequestImplTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal/portal-upload-impl/src/test/java/com/liferay/portal/upload/internal/UploadServletRequestImplTest.java:92: error: cannot find symbol
     [exec] 			UploadTestUtil.createUploadServletRequest(
     [exec] 			^
     [exec]   symbol:   variable UploadTestUtil
     [exec]   location: class com.liferay.portal.upload.internal.UploadServletRequestImplTest
```
[Log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-40/test-portal-acceptance-pullrequest(master)/2141/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

2) com.liferay.info.request.struts.test.AddInfoItemStrutsActionTest
```
c] com.liferay.info.request.struts.test.AddInfoItemStrutsActionTest > testAddInfoItemInvalidBigDecimalTooBig FAILED
     [exec]     com.liferay.portal.kernel.events.ActionException: java.lang.NullPointerException
     [exec]     	at com.liferay.portal.events.ServicePreAction.run(ServicePreAction.java:160)
     [exec]     	at com.liferay.portal.kernel.events.Action.processLifecycleEvent(Action.java:34)
     [exec]     	at com.liferay.portal.events.EventsProcessorUtil.process(EventsProcessorUtil.java:80)
     [exec]     	at com.liferay.portal.events.EventsProcessorUtil.process(EventsProcessorUtil.java:52)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-40/test-portal-acceptance-pullrequest(master)/2162/modules-integration-mysql57-jdk8/0/7/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
Thanks @Kvale1733 for chekcing!
May I ask the regression about `com.liferay.portal.kernel.events.ActionException: java.lang.NullPointerException` only exist in `com.liferay.info.request.struts.test.AddInfoItemStrutsActionTest`?

**Comment by Kvale1733** [comment]
@jeffwu0724 Yes I only saw it in that test.

**Pull request closed without merging**
