### PR TITLE
LPS-167717 Manually triggering scheduled jobs invokes all jobs

### PR DESCRIPTION
**Pull request by matthiasblaesing**
The web interface triggers the job invocation through SchedulerResponseManagerImpl#run. The method uses a call to SchedulerEngineHelper#getScheduledJob to fetch the SchedulerResponse, which is used to access the message, that is then send over the liferay MessageBus.

The message is received by SchedulerEventMessageListenerWrapper, which uses the message parts DESTINATION_NAME, JOB_NAME and GROUP_NAME to find the right scheduled job to invoke.

If DESTINATION_NAME is missing, the complete check will be skipped and all jobs will be triggered by this message. If JOB_NAME or GROUP_NAME are missing a NullPointerException could be raised.

To fix this described parts need to be added to the message in QuartzSchedulerEngine#getScheduledJob.

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@matthiasblaesing most tests failed due to connection issues. Could you rebase and re-run relevant, please? Thanks!

**Comment by matthiasblaesing** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@matthiasblaesing no regressions found.

**Comment by matthiasblaesing** [comment]
@catarineaguiar thanks for checking. Is there some more action from my side needed?

**Comment by catarineaguiar** [comment]
@matthiasblaesing you only need to wait for devs review now.

**Comment by tinatian** [comment]
@matthiasblaesing I am going to close this pull as :
1. The way the ticket is using Scheduler most probably is not valid any more.
2. There is no test covered the changes you made.

I have left a message on the ticket for our QA to verify if this is really a bug need to fix.

Thanks.
Tina.

**Comment by matthiasblaesing** [comment]
@tinatian 

>     2. There is no test covered the changes you made.

I assume you mean, that you are missing Unittest(s)? Because this short reply implies I did not test the change and this is not the case. The steps to reproduce in the referenced issue contain both the actually seen result and the expected result. I verified that before this change I saw the broken result and after this fix I saw only the expected result.

For the unittests: Would it be the right approach for you to register a job, query the `SchedulerRespone` (via  `getScheduledJob(String jobName, String groupName, StorageType storageType)`, query the `Message` (via `getMessage`) and then verify that the attributes expected by the `SchedulerEventMessageListenerWrapper` are there?

**Pull request closed without merging**
