### PR TITLE
LPD-20946 5-21 Resource Actions

### PR DESCRIPTION
**Pull request by dantewang**
Send here and wait for CI

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:object

**Comment by tinatian** [comment]
ci:report:2570580399

**Comment by tinatian** [comment]
ci:report:2570567493

**Comment by tinatian** [comment]
ci:report:2570563603

**Comment by tinatian** [comment]
ci:test:core-functional

**Comment by tinatian** [comment]
@dantewang The test results seem good to me, please verify if you see same failure as before.
I also triggered core functional test to verify. Please wait for the test results.
If everything is fine, please cc me and shuyang and forward.

Tina

**Comment by dantewang** [comment]
ci:report:2570918793

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian @shuyangzhou

**Comment by dantewang** [comment]
@tinatian Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/150559

**Pull request closed without merging**
