### PR TITLE
[Remove Spring extender usages]  LPS-161875 Disable auto-import-default-references

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang

### CODE REVIEW

**Comment by yuhai** [comment]
@@zhangyan0701, please help scan the test result after ci test finish. Thanks.

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
waiting for testray results.

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
