### PR TITLE
LPD-25981 no error message show in gogo shell with wrong captcha

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

These are the other bugs we found about captcha. 
1. When we are using captcha in gogoshell, it will not show succesfuf and error message. 
2. After the first bug is fixed, we will have antoher issue that, no matter we enter a correct/wrong captcha, the captcha input will not clean up in the ui

I include more details in the ticket. https://liferay.atlassian.net/browse/LPD-25981

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:core-functional

**Comment by jeffwu0724** [comment]
ci:report:12924552

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
