### PR TITLE
[Component with its own class name as service type] LPS-199599 Refactor Components from Commerce modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-199599

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by tinatian** [comment]
@MrJohn1911 @rafaprax 
1. For CommerceMLSearchEngineHelper, please also rename the package to make it consistent with its new class name
2. Please add a BaseCommerceMLIndexer and move the helper logic into it. This way you do not have to define the dependencies on each impl of CommerceMLIndexer.

Please resend.

Thanks.
Tina

**Pull request closed without merging**
