### PR TITLE
LPS-183457 [Components with more than 1 service] Refactor ImporterCapability components from Lima modules

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-183457](https://issues.liferay.com/browse/LPS-183457)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:help

**Comment by RenanUmV** [comment]
ci:test:wiki

**Comment by RenanUmV** [comment]
ci:test:message-boards

**Comment by RenanUmV** [comment]
ci:test:dl-store

**Comment by catarineaguiar** [comment]
no regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
