### PR TITLE
LPS-161567 Break the circular dependency between CProductLocalService…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-161567

Hi @tinatian @dantewang

This pull breaks the circular dependency between CProductLocalService and CPDefinitionLinkLocalService by using the persistence class directly.

Lily

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701

Could you help to scan test results when they are finished?

Thanks
Lily

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by slnn** [comment]
Hi @dantewang

Since the change for disabling auto import ([LPS-161869](https://issues.liferay.com/browse/LPS-161869)) has merged into master, I rebase this branch with the master and forced push on this pull.

Lily

**Comment by slnn** [comment]
With the forced push change, the ci tests has been ran in:https://github.com/slnn/liferay-portal/pull/629

**Comment by tinatian** [comment]
Waiting review from commerce team

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
FYI @shuyangzhou

**Comment by tinatian** [comment]
ci:stop

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122768

**Pull request closed without merging**
