### PR TITLE
LPS-155543 Remove jodd-proxetta.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:environments

**Comment by rafaprax** [comment]
Hey @catarineaguiar, Can you please help me to scan these test results? Thx

**Comment by catarineaguiar** [comment]
@rafaprax no regressions found.

**Comment by rafaprax** [comment]
Hey @shuyangzhou, this pr is ready for your review. Thx

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/119535

**Pull request closed without merging**
