### PR TITLE
[Remove "immediate = true" usage]Lps 168633

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-168633

This one will remove "immediate = true" from these static modules of core-infrastructure:

modules/apps/static/portal-bundle-blacklist
modules/apps/static/portal-component-blacklist
modules/apps/static/portal-configuration
modules/apps/static/portal-k8s-agent
modules/apps/static/portal-lpkg-deployer
modules/apps/static/portal-osgi-web
modules/apps/static/portal-startup-monitor

Note: exclude the PortletTracker from modules/apps/static/portal-osgi-web since removing immediate=true from it may cause it never to be started since no one will reference it, but portal needs it to be started at the first.

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@slnn Regressions found

1 lpkg-controller-jdk8/0/0
```
[beanshell] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.osgi.debug.missing.component [91]
[beanshell]   Unresolved requirement: Import-Package: com.liferay.portal.osgi.debug; version="1.0.0"
[beanshell] 
[beanshell] 	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi.jar:?]
[beanshell] 2022-11-16 20:27:04.759 ERROR [Framework Event Dispatcher: Equinox Container: 2235c4ec-47ff-41e5-ac79-5d89f93eed66][Framework:56] FrameworkEvent ERROR
[beanshell] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.model.relationship.document.library.impl [93]
```
[Log](https://testray.liferay.com/reports/production/logs/2022-11/test-1-31/test-portal-acceptance-pullrequest(master)/5922/lpkg-controller-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

Can run with: ant -f buiild-test-batch.xml lpkg-controller-jdk8

2) portal-license-smoke-jdk8/0/0
```
[exec] 2022-11-16 19:19:02.448 INFO  [main][ModuleFrameworkImpl:279] Navigate to Control Panel > System > Gogo Shell and enter "lb" to see all bundles
     [exec] 2022-11-16 19:19:07.667 ERROR [main][MainServlet:266] null
     [exec] java.lang.ClassNotFoundException: null
     [exec] 	at com.liferay.portal.ee.license.a.a.loadClass(Unknown Source) ~[portal-impl.jar:?]
     [exec] 	at com.liferay.portal.ee.license.LCSLicenseManager.getStartupAction(Unknown Source) ~[portal-impl.jar:?]
     [exec] 	at com.liferay.portal.internal.servlet.MainServlet.init(MainServlet.java:261) [portal-impl.jar:?]
     [exec] 	at javax.servlet.GenericServlet.init(GenericServlet.java:158) [servlet-api.jar:4.0.FR]
```
[Log](https://testray.liferay.com/reports/production/logs/2022-11/test-1-31/test-portal-acceptance-pullrequest(master)/5922/portal-license-smoke-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

Can run with: ant -f buiild-test-batch.xml portal-license-smoke-jdk8
But I can't run it locally since it requires setting release.tool.dir to use the release tool from liferay-release-tool-ee which I don't have access to. It failed twice on CI so it does look like a regression.

**Comment by slnn** [comment]
Thank @Kvale1733 for catching this! I will dig into it,

**Pull request closed without merging**
