### PR TITLE
[Eliminate unused reference]LPS-200301  layout-page-template-admin-web

### PR DESCRIPTION
**Pull request by JanisZhang**
Remove unused reference fields in module `layout-page-template-admin-web`. Thanks!
https://liferay.atlassian.net/browse/LPS-200301

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143064

cc @shuyangzhou

**Pull request closed without merging**
