### PR TITLE
[Components with more than 1 service] LPS-175886 Refactor DTO Converter components with more than 1 service type from Analytics Cloud

### PR DESCRIPTION
**Pull request by MrJohn1911**
Related pull: https://github.com/liferay-core-infra/liferay-portal/pull/3530

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:analytics-cloud-acceptance

**Comment by MrJohn1911** [comment]
Hey @tinatian, I resend the related pull changing the "dto.class.name" for the "component.name" and removing DXPEntityDTOConverterImpl from this pull, because I will send it in another pull with other changes.

cc: @rafaprax

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud

**Comment by catarineaguiar** [comment]
looks like only [IdentityEvents#CheckLogoutContinuesToTrackUserWithSameUserId](https://testray.liferay.com/home/-/testray/case_results/2205588505?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2205585581%26testrayRunId%3D2205587589%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) had unique failures.

@christianstokes Would your team be able to look at these?

Thanks in advance.

**Comment by joshitagaki** [comment]
@MrJohn1911 
No issues found with Analytics Cloud. We are using the analytics-cloud-acceptance CI run for dev validation.
Thanks for checking with us!
cc: @catarineaguiar

**Comment by catarineaguiar** [comment]
no regressions

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:analytics-cloud

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Comment by MrJohn1911** [comment]
Hi @tinatian, can you review this? Thanks.

**Pull request closed without merging**
