### PR TITLE
LPS-184766 Inline Equinox Http | 6-13

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:smoke

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@dantewang No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136362

**Pull request closed without merging**
