### PR TITLE
[Remove unused reference] LPS-166018 

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend.
This PR is to remove unused fields in `journal-service`. Thanks!
Previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/2113

https://issues.liferay.com/browse/LPS-166018

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
No regressions found.

cc/ @zhangyan0701

**Comment by dantewang** [comment]
5c4d84dda5515888bc9d55571c8f5a4b0120b2bc: 
```
com.liferay.journal.internal.asset.util.JournalArticleLayoutClassedModelUsageRecorder#_getAssetEntry
->
com.liferay.journal.web.internal.asset.model.JournalArticleAssetRendererFactory / com.liferay.asset.kernel.model.BaseAssetRendererFactory#getAssetEntry(long)
->
com.liferay.asset.kernel.service.AssetEntryLocalServiceUtil#getEntry(long)
```

**Comment by dantewang** [comment]
0b3880c1ee4b2e7cc89505b48a7e6ee2dd653d1d:
```
com.liferay.journal.service.impl.JournalFolderLocalServiceImpl#_getJournalFolderModelValidator
->
com.liferay.portal.validation.ModelValidatorRegistryUtil#getModelValidator(java.lang.Class<T>)
->
existence of com.liferay.journal.internal.validation.JournalFolderModelValidator
```

**Comment by dantewang** [comment]
@JanisZhang See https://github.com/liferay-core-infra/liferay-portal/pull/2275

I removed 2 commits. Please see my comments above and record them.

**Pull request closed without merging**
