### PR TITLE
[Portal service extender] LPS-170709

### PR DESCRIPTION
**Pull request by vicnate5**
From https://github.com/liferay-core-infra/liferay-portal/pull/2762 @yuhai @zhangyan0701

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:backend

**Comment by vicnate5** [comment]
@tinatian @yuhai This is now working on CI, we are running tests that depend on spring extender in their own batch.

These test classes depend on Spring Extender:
```
modules/apps/portal/portal-upgrade-test/src/testIntegration/java/com/liferay/portal/upgrade/test/ModuleBuildAutoUpgradeTest.java,\
modules/apps/portal-osgi-debug/portal-osgi-debug-spring-extender-test/**/*Test.java,\
modules/test/external-data-source-test-controller-test/**/*Test.java,\
modules/util/portal-tools-service-builder-test-test/**/*Test.java
```

FYI @shuyangzhou

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128022

**Pull request closed without merging**
