### PR TITLE
[TS] LPS-180708

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the previous pr is https://github.com/liferay-core-infra/liferay-portal/pull/4400. For the [codes block ](https://github.com/yuhai/liferay-portal/blob/f2e3d5b786a963fa70dc939de6bb37378e225883/modules/apps/expando/expando-taglib/src/main/resources/META-INF/resources/custom_attribute/page.jsp#L652-L683). It will include the cases: ExpandoColumnConstants.DOUBLE, FLOAT, INTEGER, LONG, NUMBER, SHORT and STRING. For the kind of cases, the `value` has included default value. Please see one case [code](https://github.com/yuhai/liferay-portal/blob/LPS-180708-v2/portal-impl/src/com/liferay/portlet/expando/service/impl/ExpandoValueLocalServiceImpl.java#L1783).

For page.jsp. it should miss the case ExpandoColumnConstants.STRING_ARRAY_LOCALIZED logic. The related logic may be similar with the [codes](https://github.com/yuhai/liferay-portal/blob/f2e3d5b786a963fa70dc939de6bb37378e225883/modules/apps/expando/expando-taglib/src/main/resources/META-INF/resources/custom_attribute/page.jsp#L626-L648) and we should create one case for it. We don't handle this in the pr because  this is different issue. Actually, I can't find the case to create related STRING_ARRAY_LOCALIZED custom field in the UI.

cc @IstvanD

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@yuhai No regressions. Testing passed following ticket steps.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@IstvanD Tina is busy and may not notice the review request from Github in time. If this ticket is urgent, please post in t-dxp-core-infrastructure to let the team know.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/135018

**Pull request closed without merging**
