### PR TITLE
[Components with more than 1 service] LPS-199532 Refactor NPMJavaScriptAwarePortalWebResources component

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-199532

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:frontend

**Comment by Kvale1733** [comment]
@MrJohn1911 Just found a semver issue

```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/frontend-js/frontend-js-loader-modules-extender-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.frontend.js.loader.modules.extender.npm MAJOR      7.0.0      7.0.0      8.0.0      VERSION INCREASE REQUIRED
     [exec]     	+   class      com.liferay.frontend.js.loader.modules.extender.npm.NPMJavaScriptLastModifiedUtil
     [exec]     		+   method     <init>()
     [exec]     			+   return     void
     [exec]     		+   method     clone()
     [exec]     			+   access     protected
     [exec]     			+   return     java.lang.Object
     [exec]     		+   method     equals(java.lang.Object)
     [exec]     			+   return     boolean
     [exec]     		+   method     finalize()
     [exec]     			+   access     protected
     [exec]     			+   return     void
     [exec]     		+   method     getLastModified()
     [exec]     			+   access     static
     [exec]     			+   return     long
     [exec]     		+   method     hashCode()
     [exec]     			+   return     int
     [exec]     		+   method     setLastModified(long)
     [exec]     			+   access     static
     [exec]     			+   return     void
     [exec]     		+   method     toString()
     [exec]     			+   return     java.lang.String
     [exec]     		+   method     updateLastModified(long)
     [exec]     			+   access     static
     [exec]     			+   return     void
     [exec]     	-   interface  com.liferay.frontend.js.loader.modules.extender.npm.JavaScriptAwarePortalWebResources
     [exec]     		-   access     abstract
     [exec]     		-   implements com.liferay.portal.kernel.servlet.PortalWebResources
     [exec]     		-   method     clone()
     [exec]     			-   access     protected
     [exec]     			-   return     java.lang.Object
     [exec]     		-   method     equals(java.lang.Object)
     [exec]     			-   return     boolean
     [exec]     		-   method     finalize()
     [exec]     			-   access     protected
     [exec]     			-   return     void
     [exec]     		-   method     hashCode()
     [exec]     			-   return     int
     [exec]     		-   method     toString()
     [exec]     			-   return     java.lang.String
     [exec]     		-   method     updateLastModifed(long)
     [exec]     			-   access     abstract
     [exec]     			-   return     void
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 10.0.0
```
[Log](https://testray.liferay.com/reports/production/logs/2023-11/test-1-40/test-portal-acceptance-pullrequest(master)/7074/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
last push fixes semver issue.

**Review by rafaprax — CHANGES_REQUESTED** [review]
Hey @MrJohn1911, put the interface removal in a separate commit and also explain the reason why you are exchanging the approach using "trackers" by a util class. Thx

**Pull request closed without merging**
