### PR TITLE
[Remove Stream/Optional usage] LPS-170768 dynamic-data-mapping | PART 3

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
@dantewang No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127578

@JanisZhang I named this pull as part 1 when sending to Brian. Please rename other pulls for ddm as part2 & part3, thanks!

**Pull request closed without merging**
