### PR TITLE
[Test Fix] LPD-31519

### PR DESCRIPTION
**Pull request by dantewang**
https://liferay.atlassian.net/browse/LPD-31519

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:38349026

**Comment by dantewang** [comment]
CompanyLogging#AssertCompanyLogsIsolated passed.

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
