### PR TITLE
[Remove Stream/Optional usage] Phase 1 LPS-172794 remove_stream_in_portal_tools_rest_builder

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Dante,
Resent: https://github.com/liferay-core-infra/liferay-portal/pull/3834
Thanks for checking!

### CODE REVIEW

**Comment by zhangyan0701** [comment]
1. Test [rest-builder-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2231146110) failed with messages:
```
     [echo] diff --git a/modules/apps/headless/headless-site/headless-site-client/src/main/java/com/liferay/headless/site/client/json/BaseJSONParser.java b/modules/apps/headless/headless-site/headless-site-client/src/main/java/com/liferay/headless/site/client/json/BaseJSONParser.java
     [echo] index dbdec1beb521..2e6eb754762a 100644
     [echo] --- a/modules/apps/headless/headless-site/headless-site-client/src/main/java/com/liferay/headless/site/client/json/BaseJSONParser.java
     [echo] +++ b/modules/apps/headless/headless-site/headless-site-client/src/main/java/com/liferay/headless/site/client/json/BaseJSONParser.java
... ...
     [echo] diff --git a/modules/apps/headless/headless-site/headless-site-client/src/main/java/com/liferay/headless/site/client/pagination/Page.java b/modules/apps/headless/headless-site/headless-site-client/src/main/java/com/liferay/headless/site/client/pagination/Page.java
     [echo] index 83b760b2b3c3..70824401213b 100644
     [echo] --- a/modules/apps/headless/headless-site/headless-site-client/src/main/java/com/liferay/headless/site/client/pagination/Page.java
     [echo] +++ b/modules/apps/headless/headless-site/headless-site-client/src/main/java/com/liferay/headless/site/client/pagination/Page.java
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-03/test-1-35/test-portal-acceptance-pullrequest(master)/3827/rest-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0

2. Some integration tests failed with error `java.lang.IllegalArgumentException: Unsupported field name actions`.
Example failed tests:

[com.liferay.portal.workflow.metrics.rest.resource.v1_0.test.AssigneeResourceTest](https://testray.liferay.com/home/-/testray/case_results/2231146252):
`testPostProcessAssigneesPage: java.lang.IllegalArgumentException: Unsupported field name actions  at com.liferay.portal.workflow.metrics.rest.client.problem.Problem$ProblemJSONParser.setField(Problem.java:178)`
Full console log:
https://testray.liferay.com/reports/production/logs/2023-03/test-1-35/test-portal-acceptance-pullrequest(master)/3827/modules-integration-mysql57-jdk8/1/7/jenkins-console.txt.gz?authuser=0

[com.liferay.headless.commerce.delivery.order.resource.v1_0.test.PlacedOrderItemResourceTest](https://testray.liferay.com/home/-/testray/case_results/2231145787):
`testGetPlacedOrderPlacedOrderItemsPage: java.lang.IllegalArgumentException: Unsupported field name actions  at com.liferay.headless.commerce.delivery.order.client.problem.Problem$ProblemJSONParser.setField(Problem.java:178)`
Full console log:
https://testray.liferay.com/reports/production/logs/2023-03/test-1-35/test-portal-acceptance-pullrequest(master)/3827/modules-integration-mysql57-jdk8/0/14/jenkins-console.txt.gz?authuser=0

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:bundle

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:bundle

**Comment by jeffwu0724** [comment]
ci:test:sf

**Pull request closed without merging**
