### PR TITLE
Lps 135298 1 26

### PR DESCRIPTION
**Pull request by slnn**
Change all "instance" to "company" in these property names and var names.

/cc @dantewang @tinatian

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@tinatian See https://github.com/brianchandotcom/liferay-portal/pull/112608#issuecomment-1021743506

Please note that other properties/variable names/method names containing "instance" are either related to Commerce product instance or Portlet instance, which should not be changed.

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
FYI @shuyangzhou, no logic change in this pull, only rename some variables.

**Pull request closed without merging**
