### PR TITLE
[Move Expando: cleanup Portal, PortalImpl and PortalUtil]Lps 191477

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-191477

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:license

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@slnn Conflict again...

**Comment by slnn** [comment]
Please see https://github.com/liferay-core-infra/liferay-portal/pull/5272

**Pull request closed without merging**
