### PR TITLE
[Remove Spring extender usages] LPS-159499

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

Resend. refer to [#1292](https://github.com/liferay-core-infra/liferay-portal/pull/1292)

This PR is to remove spring extender usage in commerce-discount-service, thanks!
https://issues.liferay.com/browse/LPS-159499
Previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/1258

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @catarineaguiar, Could you review the test results when it finishes? Thanks!

**Comment by JanisZhang** [comment]
ci:test:commerce

**Comment by dantewang** [comment]
@JanisZhang It seems a version change is missing (should be included in the 2nd Auto Generated commit)

**Comment by dantewang** [comment]
@catarineaguiar No need to check this one for now, thanks!

**Pull request closed without merging**
