### PR TITLE
[TS]LPS-161481

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by Kvale1733** [comment]
@tinatian No regressions found. Testing passed following ticket steps.

**Comment by tinatian** [comment]
ci:test:help

**Comment by tinatian** [comment]
ci:test:users

**Comment by tinatian** [comment]
ci:test:usm

**Comment by tinatian** [comment]
ci:test:usm-db-partition

**Comment by tinatian** [comment]
ci:test:usm-environments

**Comment by tinatian** [comment]
ci:test:usm-upgrade

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133914

**Pull request closed without merging**
