### PR TITLE
LPD-28758 Add default admin user configuration to company creation

### PR DESCRIPTION
**Pull request by devopsmystic**
https://liferay.atlassian.net/browse/LPD-28758

### CODE REVIEW

**Comment by devopsmystic** [comment]
ci:test:relevant

**Comment by devopsmystic** [comment]
Hi @tinatian , @dantewang 
Thanks for your time on this.
I have added more scenarios to the current test, please add inline review comments, if any.

Regards
Madhu

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by devopsmystic** [comment]
ci:test:sf

**Comment by devopsmystic** [comment]
ci:test:sf

**Comment by devopsmystic** [comment]
ci:test:sf

**Comment by devopsmystic** [comment]
ci:test:sf

**Pull request closed without merging**
