### PR TITLE
LPS-143634

### PR DESCRIPTION
**Pull request by julschong**
@tinatian
Hi Tina,

Resubmitting for #315 
I think the issue is because ExportImportControlPanelEntry is extended by ImportControlPanelEntry. But, GroupPermission service reference was set to be private. I changed it to protected here: [f49b596](https://github.com/liferay-core-infra/liferay-portal/pull/330/commits/f49b596076f8a11a557d3b1b5b4d58e9d0f57863)

Hope this will fix the failure

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@koor4356
Hi Koor,
Could you please help me check if this fixed the issue in #315 ?

**Comment by koor4356** [comment]
okay, I will do that. Thanks!

**Comment by koor4356** [comment]
@julschong 
This looks good, Thanks!

**Comment by julschong** [comment]
@tinatian 
Hi Tina,
Could you please help me review this pull?
Thank you!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113576

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
