### PR TITLE
remove_deprecated_for_portal_kernel_part_One

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Shuyang, Tina,

I removed deprecated for portal kernel, and below are what I have removed:
portal-kernel/src/com/liferay/asset/kernel/model/,
portal-kernel/src/com/liferay/document/library/kernel/,
portal-kernel/src/com/liferay/dynamic/data/mapping/kernel/,
portal-kernel/src/com/liferay/expando/kernel/util/,
portal-kernel/src/com/liferay/exportimport/kernel/configuration/.

Thanks for checking!

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by kyle-miho** [comment]
@jeffwu0724 PR looks good to go

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114876

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
