### PR TITLE
[Static reference] LPS-181117 sharing-taglib

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-181117

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:Stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:sharing

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Comment by JanisZhang** [comment]
ci:forward:force

**Pull request closed without merging**
