### PR TITLE
[Remove Blocking usages]LPS-187880 portal-kernel | SettingsFactoryUtil

### PR DESCRIPTION
**Pull request by JanisZhang**
Fixed regression. thanks!

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5264

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@JanisZhang regressions found:

semver error:
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/portal/portal-verify-test-util] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.portal.verify.test.util                MAJOR      2.0.0      2.0.0      3.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.portal.verify.test.util.BaseCompanySettingsVerifyProcessTestCase
     [exec]     		-   field      settingsFactory
     [exec]     			-   access     protected
     [exec]     			-   annotated  com.liferay.portal.test.rule.Inject
     [exec]     			-   return     com.liferay.portal.kernel.settings.SettingsFactory
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 5.0.0
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-08/test-1-37/test-portal-acceptance-pullrequest(master)/13854/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-test/src/testIntegration/java/com/liferay/content/dashboard/web/internal/portlet/action/test/GetContentDashboardItemInfoMVCResourceCommandTest.java:257: error: cannot find symbol
     [exec] 						FallbackKeysSettingsUtil.getSettingsFactory())) {
     [exec] 						                        ^
     [exec]   symbol:   method getSettingsFactory()
     [exec]   location: class com.liferay.portal.kernel.settings.FallbackKeysSettingsUtil
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-test/src/testIntegration/java/com/liferay/content/dashboard/web/internal/portlet/action/test/GetContentDashboardItemInfoMVCResourceCommandTest.java:281: error: cannot find symbol
     [exec] 						FallbackKeysSettingsUtil.getSettingsFactory())) {
     [exec] 						                        ^
     [exec]   symbol:   method getSettingsFactory()
     [exec]   location: class com.liferay.portal.kernel.settings.FallbackKeysSettingsUtil
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 2 errors
     [exec] 
     [exec] > Task :apps:content-dashboard:content-dashboard-test:compileTestIntegrationJava FAILED
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-08/test-1-37/test-portal-acceptance-pullrequest(master)/13854/modules-compile-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
