### PR TITLE
[TS] LPS-202625 Obfuscate Client Secret for Outlook Auth Connector even if it's only available to admins

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @liferay-core-infra,

This is a solution for [LPS-202625](https://liferay.atlassian.net/browse/LPS-202625) about obfuscating the Client Secret in the System Settings for Outlook Auth Connector. 

See [PTR-4531](https://liferay.atlassian.net/browse/PTR-4531) for more information on why to do this even when only admins can reach this configuration.

The approach to the solution is to use the standard value `Meta.Type.Password` for the attribute `type` in the configuration interface.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by ricardocousolr** [comment]
@dantewang I've updated the commit message to conform to source formatting guidelines

**Comment by ricardocousolr** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
