### PR TITLE
[Components with more than 1 service] LPS-187067 Refactor components from frontend-js and frontend-theme modules

### PR DESCRIPTION
**Pull request by dantewang**
Previous pull: https://github.com/liferay-core-infra/liferay-portal/pull/5245

### CODE REVIEW

**Comment by dantewang** [comment]
CI has passed in previous PR, just moved a class in this PR.

**Comment by Kvale1733** [comment]
ci:test:frontend

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:frontend

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@dantewang No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian @rafaprax

**Pull request closed without merging**
