### PR TITLE
LPS-172798 Remove "immediate = true" from remaining Data Engine modules

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:data-engine

**Comment by daiazius** [comment]
@rafaprax

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found.

**Review by rafaprax — CHANGES_REQUESTED** [review]

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
Hi @tinatian, can you review this PR? Thanks

**Comment by ling-alan-huang** [comment]
Hi @rafaprax 
We will add a new [SF rule](https://issues.liferay.com/browse/LPS-171325) for it when https://issues.liferay.com/browse/LPS-163833 is done.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129124

**Pull request closed without merging**
