### PR TITLE
LPS-174386

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:startup

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130023

**Comment by tinatian** [comment]
Code conflicts with head of master, rebase at https://github.com/liferay-core-infra/liferay-portal/pull/3637.

**Pull request closed without merging**
