### PR TITLE
[Static reference] LPS-180679 frontend-taglib, frontend-data-set

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-180679

previous: https://github.com/liferay-core-infra/liferay-portal/pull/4178

changes in this pull:

- fix regressions

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:frontend-data-set

**Comment by zhangyan0701** [comment]
ci:test:frontend

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4198

**Comment by dantewang** [comment]
ci:stop

**Pull request closed without merging**
