### PR TITLE
[Unused Reference] LPD-8466 Remove unused @Reference variables in LPKGArtifactInstaller.java

### PR DESCRIPTION
**Pull request by Valmir-unicap**
- Ticket: https://liferay.atlassian.net/browse/LPD-8466

- @dantewang  about this feedback: https://github.com/liferay-core-infra/liferay-portal/pull/6691#issuecomment-2006268852

The bug: https://liferay.atlassian.net/browse/LPSA-49625  is no longer reproduced because the feature no longer exists, it was turned off in December 2021. No test covers this bug case. More information: https://help.liferay.com/hc/en-us/articles/360018183431-Using-LCS

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:relevant

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by dantewang** [comment]
@Valmir-unicap By "this feature no longer exists" do you mean LCS portlet?

**Comment by dantewang** [comment]
@Valmir-unicap If there's no unique failure, I think we can forward it. cc @tinatian

**Comment by regiCesar21** [comment]
ci:report:2557380116

**Comment by dantewang** [comment]
@regiCesar21 I think we can forward. Thanks!

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
