### PR TITLE
[Remove unused references]LPS-166266 Remove the reference field _cookiesConsentConfiguration fr…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-166266

ci tests have been run in https://github.com/slnn/liferay-portal/pull/649, no unique failures appeared.

### CODE REVIEW

**Comment by dantewang** [comment]
@slnn This is a new thing to both me and Tina -- referencing an osgi configuration. Usually we don't need to explicitly declare dependency on a osgi configuration because the configuration, defined by an interface, has default values. Even if we do, we usually use `configurationPolicy` in `@Component` annotation. If it's pure osgi configuration (the object is just obtained using `ConfigurableUtil.createConfigurable`), we can safely remove the reference.

However, in this PR's case, the configuration object is per-group, obtained using `GroupSettingsLocator`. This may involve additional logic compared to pure osgi configuration. So I need to look into the `ConfigurationProvider` logic to see whether this reference is really needed.

**Comment by tinatian** [comment]
@slnn @dantewang I am going to close this pull for now, please resend if needed.

Thanks.
Tina

**Comment by dantewang** [comment]
@slnn Hai looked into the `ConfigurationProvider` infra and didn't think the field is needed. Please resend this PR and I'll forward.

cc @tinatian

**Comment by slnn** [comment]
Resend in https://github.com/liferay-core-infra/liferay-portal/pull/2266

**Pull request closed without merging**
