### PR TITLE
[Remove Optional usage from method body: analytics]Lps 172264 part 1 optional

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:analytics-cloud

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:stop

**Comment by ViniLopes20** [comment]
ci:stop:analytics-cloud-acceptance

**Comment by catarineaguiar** [comment]
ci:stop:analytics-cloud-acceptance

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by catarineaguiar** [comment]
no need to wait for analytics-cloud-acceptance results.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128645

**Pull request closed without merging**
