### PR TITLE
Lps 185138 7 21

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
ci:test:start

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
hey @tinatian, this regression is still reproducible https://github.com/liferay-core-infra/liferay-portal/pull/5042#issuecomment-1644633415

**Comment by tinatian** [comment]
@LisztLiszt Please help me check why this failed.

Thanks.
Tina

**Pull request closed without merging**
