### PR TITLE
LPS-143630 Avoid using TransferHeadersHelperUtil, ColorSchemeFactoryUtil directly in modules

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina, Shuyang

Main Task: [LPS-143403](https://issues.liferay.com/browse/LPS-143403)
Sub Task: [LPS-143630](https://issues.liferay.com/browse/LPS-143630)

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
pushed additional changes to remove new merged in CalendarFactoryUtil usage causing SF errors

**Comment by julschong** [comment]
pushed change to fix 1 access modifier from private to protected in ContactsCenterPortlet

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
@kyle-miho
Hi Kyle,
Could you please help me scan the results?
Thank you

**Comment by kyle-miho** [comment]
failures are unrelated

**Comment by julschong** [comment]
@tinatian Hi Tina,
Could you please check if this is ready to go?
Thank you

**Comment by julschong** [comment]
**** Removed CalendarFactoryUtil ****
CalendarFactoryUtil will be moved into petra-util instead

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115191

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
