### PR TITLE
[TS] LPS-187433 - add optional property for ISO-3166 compliance

### PR DESCRIPTION
**Pull request by wanderlast**
Hi! I'm sending this to you guys because you're the ones who helped handle the PTR ([PTR-4005](https://issues.liferay.com/browse/PTR-4005)), but if you feel this should go to a different team like AppSec, please let me know.

Per our discussion on PTR-4005, I've added a portal property and also refactored the related OSGI commands to account for this portal property. The two countries in question themselves were added to a separate JSON for easier tracking. I was somewhat unsure of how to name the property, so please let me know if you have any suggestions on wordsmithing or anything else. Thanks!

This is a resend of https://github.com/liferay-core-infra/liferay-portal/pull/4785 and https://github.com/liferay-core-infra/liferay-portal/pull/4796. Auto SF was removing certain feature flag properties, so those changes were manually undone. As well, semver and a rebase to align with Master was required.

### CODE REVIEW

**Comment by catarineaguiar** [comment]
we are facing some CI issues, so let's wait for the fix to be merged to re-run test suites.

Thanks

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
Hi @catarineaguiar,

Thanks for looking at this! I've realized the reproduction steps on the ticket are pretty unclear so I've attempted to refine them and just wanted to make sure we're using the same steps before I investigate this failure.

1. The issue is controlled by a new portal property "iso.countries.enabled" that is set by default to false. This is intentional due to the potentially controversial nature of the inclusion of these, but I know it's rather hidden in the commits. Was this taken into account?
2. Was this tested on a completely new instance with the portal property set before initial startup? Countries are populated in a company/portal instance at creation and are not ever checked again unless manually retriggered. This can be worked around by testing using a new virtual instance after enabling the property (since that'll create a new company) or using address:repopulateCompanyCountries <companyId> in gogoshell.

Thanks!

**Comment by Kvale1733** [comment]
ci:test:stable:norebase

**Comment by Kvale1733** [comment]
@wanderlast So I tested with the property you mentioned and this does fix the issue. Can you rebase and rerun relevant?

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
No regressions found.

**Comment by tinatian** [comment]
@wanderlast It should be a configuration property rather than a portal property, you should add a property to the configuration class in address-impl module if existed, or create a new configuration class with the property you want to add. The property should not be added to portal.properties.

Please resend.

Thanks.
Tina.

**Pull request closed without merging**
