### PR TITLE
LPS-135170 - Add tests.

### PR DESCRIPTION
**Pull request by ethib137**

### CODE REVIEW

**Comment by ethib137** [comment]
Hey @dantewang, I've added the tests here. Let me know if I should send this somewhere else, or if there is any different process I should go through for getting these tests reviewed? Thanks.

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:acceptance

**Comment by ethib137** [comment]
cc: @ealonso @lfbesada
I've added a test util for deleting portlets from content pages. Does this look alright?

**Comment by lfbesada** [comment]
> cc: @ealonso @lfbesada I've added a test util for deleting portlets from content pages. Does this look alright?

@ethib137 That's great, thanks!!! I also added a few days ago a method to add a fragmentEntrylink to a layout. Let's see if little by little we can make it easy to test these things.

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:acceptance

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:forward

**Comment by ethib137** [comment]
Reopened here: https://github.com/liferay-core-infra/liferay-portal/pull/957

**Pull request closed without merging**
