### PR TITLE
LPS-200689 Move com.liferay.portal.security.* to modules to avoid using spring-beans

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This PR is for https://liferay.atlassian.net/browse/LPS-200689.
I am trying to remove spring-beans, and moved them to modules to use component instead
```
 <bean class="com.liferay.portal.security.permission.GroupModelListener" id="com.liferay.portal.security.permission.GroupModelListener" />
	<bean class="com.liferay.portal.security.permission.ResourcePermissionModelListener" id="com.liferay.portal.security.permission.ResourcePermissionModelListener" />
	<bean class="com.liferay.portal.security.permission.TeamModelListener" id="com.liferay.portal.security.permission.TeamModelListener" />
	<bean class="com.liferay.portal.security.permission.UserGroupGroupRoleModelListener" id="com.liferay.portal.security.permission.UserGroupGroupRoleModelListener" />
	<bean class="com.liferay.portal.security.permission.UserGroupRoleModelListener" id="com.liferay.portal.security.permission.UserGroupRoleModelListener" />
	<bean class="com.liferay.portal.security.permission.UserModelListener" id="com.liferay.portal.security.permission.UserModelListener" />
```
Thanks for checking

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:security

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/6/23 8:26am

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/9/23 9:26am

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/13/23 8:04am

**Comment by tinatian** [comment]
@jeffwu0724 All the model listener in this pull is to clean up PermissionCacheUtil except UserGroupRoleModelListener. UserGroupRoleModelListener is also doing reindex of user which is not related to any permission logic. This is caused by af79da809b5ae790c2cbe091e1278a8dcccb0811. The reindex should not be added into this model listener.

Let's do this:
1. For https://github.com/liferay-core-infra/liferay-portal/pull/6014/commits/4df80cec27de2d4aa03aee329956c5391cf92325, create a new UserGroupRoleModelListener in permission module and only do the permission cache related clean up.
2. For the reindex logic of UserGroupRoleModelListener, move it to UserGroupRoleLocalServiceImpl, manually reindex user when there is a add/delete/update


Thanks.
Tina.

**Pull request closed without merging**
