### PR TITLE
[TEST CI] ISSD-3843 Test CI

### PR DESCRIPTION
**Pull request by ericyanLr**

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:license

**Comment by ericyanLr** [comment]
ci:test:license

**Comment by ericyanLr** [comment]
ci:test:license

**Comment by vicnate5** [comment]
ci:test:license

**Comment by ericyanLr** [comment]
ci:test:license

**Comment by ericyanLr** [comment]
Latest PR:
https://github.com/liferay-core-infra/liferay-portal/pull/6844

**Pull request closed without merging**
