### PR TITLE
[System Properties]LPS-154373 Move some properties that ModuleFramework need when start

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian , I have rebased and fixed the Semver error.

Detial: https://github.com/liferay-core-infra/liferay-portal/pull/2254

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
Force-Push is just to resolve the conflict about file portal-impl/bnd.bnd.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@W2jx You can leave the QA passed just need to solve the conflict and it's good to go.

**Comment by W2jx** [comment]
Force-Push is just to rebase and resolve the conflict about file portal-impl/bnd.bnd.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@W2jx No regressions.

**Comment by tinatian** [comment]
@W2jx Please rebase

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
Hi @tinatian , I have rebased.

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
Force-Push is just to rebase and resolve the version conflict.

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126288

**Pull request closed without merging**
