### PR TITLE
[BLOCKERS] LPS-199574 | LPS-199570

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**
This pull request resolves [LPS-199574](https://liferay.atlassian.net/browse/LPS-199574) [LPS-199570](https://liferay.atlassian.net/browse/LPS-199570)

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:relevant

**Comment by GabrielHenriquedev** [comment]
ci:test:users-admin

**Comment by catarineaguiar** [comment]
ci:test:um

**Comment by catarineaguiar** [comment]
when USM test suite finish, check if these tests pass:
`AccountUsers#CanFilterAccountUserInTheUsersAdminPortlet`
`Account#ServiceAccountsSmoke`

**Comment by catarineaguiar** [comment]
tested locally and both bugs were fixed with these changes

**Comment by Kvale1733** [comment]
@GabrielHenriquedev No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142619

**Pull request closed without merging**
