### PR TITLE
[TS] LPS-199001

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the previous pr is https://github.com/liferay-core-infra/liferay-portal/pull/5792

cc @wanderlast

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:friendly-url

**Comment by catarineaguiar** [comment]
no regressions found. Bug not reproducible when following LPP steps.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142882

**Pull request closed without merging**
