### PR TITLE
[Method References 3] LPS-179401 Convert method reference to serviceTrackerList in classes FreeMarkerTemplateResourceLoader, VelocityTemplateResourceLoader

### PR DESCRIPTION
**Pull request by W2jx**
Resend, ServiceTrackerList is used directly in the parent class BaseTemplateResourceLoader.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3998

### CODE REVIEW

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
only do semver, no need to rerun test

**Comment by W2jx** [comment]
no conflicts(4/4 10:27)

**Review by dantewang — APPROVED** [review]

**Comment by W2jx** [comment]
only do semver, no need to rerun test

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133046

**Pull request closed without merging**
