### PR TITLE
[Cleanup registry-like classes:dynamic-data-mapping]Lps 167909

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-167909

### CODE REVIEW

**Comment by dantewang** [comment]
@slnn Commit message typo, please update

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
> @slnn Commit message typo, please update

Done

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125981

**Pull request closed without merging**
