### PR TITLE
LPS-149082 Move commons-beanutils.jar to shared-dependencies-apache-commons

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by tinatian** [comment]
@guilhermedcamacho I believe this commons-beanutils is only used by integration tests which are generated or extending the generated code from rest builder. We should not move this to shared-dependecies, please move it to a test-util module which is only be deployed when an integration test is running, this way, our production code won't have it.

Thanks.
Tina.

**Comment by guilhermedcamacho** [comment]
> @guilhermedcamacho I believe this commons-beanutils is only used by integration tests which are generated or extending the generated code from rest builder. We should not move this to shared-dependecies, please move it to a test-util module which is only be deployed when an integration test is running, this way, our production code won't have it.
> 
> Thanks. Tina.

Makes sense, I will do that, thanks!

**Comment by guilhermedcamacho** [comment]
ci:close

**Pull request closed without merging**
