### PR TITLE
LPS-196082 Merge GroupPermission interface and impl into Util

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Shuyang,

Resent https://github.com/liferay-core-infra/liferay-portal/pull/5556

This is for ticket https://liferay.atlassian.net/browse/LPS-196082
Thanks for checking

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@jeffwu0724 regen needed:

```
     [echo] diff --git a/portal-kernel/src/com/liferay/portal/kernel/service/permission/GroupPermissionUtil_IW.java b/portal-kernel/src/com/liferay/portal/kernel/service/permission/GroupPermissionUtil_IW.java
     [echo] index 007cfffe9330b..bd4a7df9d0295 100644
     [echo] --- a/portal-kernel/src/com/liferay/portal/kernel/service/permission/GroupPermissionUtil_IW.java
     [echo] +++ b/portal-kernel/src/com/liferay/portal/kernel/service/permission/GroupPermissionUtil_IW.java
     [echo] @@ -5,23 +5,6 @@
     [echo]  
     [echo]  package com.liferay.portal.kernel.service.permission;
     [echo]  
     [echo] -import com.liferay.petra.lang.HashUtil;
     [echo] -import com.liferay.portal.kernel.exception.PortalException;
     [echo] -import com.liferay.portal.kernel.model.Group;
     [echo] -import com.liferay.portal.kernel.model.GroupConstants;
     [echo] -import com.liferay.portal.kernel.model.User;
     [echo] -import com.liferay.portal.kernel.security.auth.PrincipalException;
     [echo] -import com.liferay.portal.kernel.security.permission.ActionKeys;
     [echo] -import com.liferay.portal.kernel.security.permission.PermissionChecker;
     [echo] -import com.liferay.portal.kernel.service.GroupLocalServiceUtil;
     [echo] -import com.liferay.portal.kernel.service.UserLocalServiceUtil;
     [echo] -import com.liferay.portal.kernel.util.GetterUtil;
     [echo] -import com.liferay.portal.kernel.util.PropsKeys;
     [echo] -import com.liferay.portal.kernel.util.PropsUtil;
     [echo] -
     [echo] -import java.util.Map;
     [echo] -import java.util.Objects;
     [echo] -
     [echo]  /**
     [echo]   * @author Brian Wing Shun Chan
     [echo]   */
     [echo] @@ -30,52 +13,49 @@ public class GroupPermissionUtil_IW {
     [echo]  		return _instance;
     [echo]  	}
     [echo]  
     [echo] -	public static void check(
     [echo] -		PermissionChecker permissionChecker, Group group, String actionId)
     [echo] -		throws PortalException {
     [echo] -
     [echo] +	public void check(
     [echo] +		com.liferay.portal.kernel.security.permission.PermissionChecker permissionChecker,
     [echo] +		com.liferay.portal.kernel.model.Group group, java.lang.String actionId)
     [echo] +		throws com.liferay.portal.kernel.exception.PortalException {
     [echo]  		GroupPermissionUtil.check(permissionChecker, group, actionId);
     [echo]  	}
     [echo]  
     [echo] -	public static void check(
     [echo] -		PermissionChecker permissionChecker, long groupId, String actionId)
     [echo] -		throws PortalException {
     [echo] -
     [echo] +	public void check(
     [echo] +		com.liferay.portal.kernel.security.permission.PermissionChecker permissionChecker,
     [echo] +		long groupId, java.lang.String actionId)
     [echo] +		throws com.liferay.portal.kernel.exception.PortalException {
     [echo]  		GroupPermissionUtil.check(permissionChecker, groupId, actionId);
     [echo]  	}
     [echo]  
     [echo] -	public static void check(
     [echo] -		PermissionChecker permissionChecker, String actionId)
     [echo] -		throws PortalException {
     [echo] -
     [echo] +	public void check(
     [echo] +		com.liferay.portal.kernel.security.permission.PermissionChecker permissionChecker,
     [echo] +		java.lang.String actionId)
     [echo] +		throws com.liferay.portal.kernel.exception.PortalException {
     [echo]  		GroupPermissionUtil.check(permissionChecker, actionId);
     [echo]  	}
     [echo]  
     [echo] -	public static boolean contains(
     [echo] -		PermissionChecker permissionChecker, Group group, String actionId)
     [echo] -		throws PortalException {
     [echo] -
     [echo] +	public boolean contains(
     [echo] +		com.liferay.portal.kernel.security.permission.PermissionChecker permissionChecker,
     [echo] +		com.liferay.portal.kernel.model.Group group, java.lang.String actionId)
     [echo] +		throws com.liferay.portal.kernel.exception.PortalException {
     [echo]  		return GroupPermissionUtil.contains(permissionChecker, group, actionId);
     [echo]  	}
     [echo]  
     [echo] -	public static boolean contains(
     [echo] -		PermissionChecker permissionChecker, long groupId, String actionId)
     [echo] -		throws PortalException {
     [echo] -
     [echo] +	public boolean contains(
     [echo] +		com.liferay.portal.kernel.security.permission.PermissionChecker permissionChecker,
     [echo] +		long groupId, java.lang.String actionId)
     [echo] +		throws com.liferay.portal.kernel.exception.PortalException {
     [echo]  		return GroupPermissionUtil.contains(permissionChecker, groupId, actionId);
     [echo]  	}
     [echo]  
     [echo] -	public static boolean contains(
     [echo] -		PermissionChecker permissionChecker, String actionId) {
     [echo] -
     [echo] +	public boolean contains(
     [echo] +		com.liferay.portal.kernel.security.permission.PermissionChecker permissionChecker,
     [echo] +		java.lang.String actionId) {
     [echo]  		return GroupPermissionUtil.contains(permissionChecker, actionId);
     [echo]  	}
     [echo]  
     [echo] -
     [echo] -
     [echo] -
     [echo]  	private GroupPermissionUtil_IW() {
     [echo]  	}
     [echo]  
     [echo]  	private static GroupPermissionUtil_IW _instance = new GroupPermissionUtil_IW();
     [echo] -}
     [echo] +}
     [echo] \ No newline at end of file
[stopwatch] [run.batch.test.action: 2.633 sec]
     [echo] .
     [echo] 
     [echo] Detected build-iw changes. See above build-iw log for more
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-09/test-1-31/test-portal-acceptance-pullrequest(master)/9437/build-iw-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
changed back to use groupPermission instead of groupPermissionUtil
velocityContext.put("groupPermission", GroupPermissionUtil_IW.getInstance());

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found. SF is unrelated.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141274

**Pull request closed without merging**
