### PR TITLE
[Components with more than 1 service] LPS-178898 Refactor ScreenNavigationCategory components from Data Integration

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://issues.liferay.com/browse/LPS-178898

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
Last push fixes SF problems

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:data-integration

**Comment by vicnate5** [comment]
@MrJohn1911 Regression found here:

Steps to Reproduce:
1. Go to Control Panel > Configuration > Job Scheduler
2.  Click Plus Icon and select any trigger

Expected Result:
Page renders trigger configuration

Actual Result:
Page fails to render with error in liferay log
```
ERROR [http-nio-8080-exec-9][IncludeTag:128] Current URL /group/control_panel/manage?p_p_id=com_liferay_dispatch_web_internal_portlet_DispatchPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_dispatch_web_internal_portlet_DispatchPortlet_mvcRenderCommandName=%2Fdispatch%2Fedit_dispatch_trigger&_com_liferay_dispatch_web_internal_portlet_DispatchPortlet_cmd=add&_com_liferay_dispatch_web_internal_portlet_DispatchPortlet_redirect=http%3A%2F%2F192.168.254.13%3A8080%2Fgroup%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_dispatch_web_internal_portlet_DispatchPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_p_mode%3Dview%26p_p_auth%3DLsMsbgsP&_com_liferay_dispatch_web_internal_portlet_DispatchPortlet_dispatchTaskExecutorType=export-analytics-delete-message-analytics-dxp-entities&p_p_auth=LsMsbgsP generates exception: java.lang.NullPointerException
java.lang.NullPointerException: null
        at com.liferay.dispatch.web.internal.frontend.taglib.servlet.taglib.DispatchDetailsScreenNavigationCategory.getLabel(DispatchDetailsScreenNavigationCategory.java:50) ~[bundleFile:?]
        at org.apache.jsp.screen_005fnavigation.page_jsp._jspService(page_jsp:405) ~[?:?]
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111) ~[jasper.jar:9.0.73]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:596) ~[servlet-api.jar:4.0.FR]
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411) ~[jasper.jar:9.0.73]
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473) ~[jasper.jar:9.0.73]
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377) ~[jasper.jar:9.0.73]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:596) ~[servlet-api.jar:4.0.FR]
        at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:328) ~[bundleFile:?]
        at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:340) ~[bundleFile:?]
        at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
        at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:63) ~[?:?]
        at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
        at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
        at com.liferay.portal.servlet.DirectServletPathRegisterDispatcher.include(DirectServletPathRegisterDispatcher.java:67) ~[portal-impl.jar:?]
        at com.liferay.portal.servlet.DirectRequestDispatcherFactoryImpl$IndirectRequestDispatcher.include(DirectRequestDispatcherFactoryImpl.java:190) ~[portal-impl.jar:?]
        at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:79) ~[portal-impl.jar:?]
        at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.include(ClassLoaderRequestDispatcherWrapper.java:53) ~[portal-impl.jar:?]
        at com.liferay.taglib.util.IncludeTag.includePage(IncludeTag.java:409) ~[bundleFile:?]
        at com.liferay.taglib.util.IncludeTag.include(IncludeTag.java:384) ~[bundleFile:?]
```

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4141

**Pull request closed without merging**
