### PR TITLE
LPS-147678

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for https://issues.liferay.com/browse/LPS-147678
I have update update com.azure:azure-sdk-bom version to 1.0.4, which will use azure-identity 1.3.6, which will include json-smart 4.5.7.
Thanks for checking. Also see https://github.com/jeffwu0724/liferay-portal/pull/49

### CODE REVIEW

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar can you help me check this pr, please?
cc: @vicnate5

**Comment by catarineaguiar** [comment]
@jeffwu0724 No regressions found!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
@catarineaguiar @vicnate5 did the tests cover portal-store-azure? Do we need to run some special store batches?

**Comment by vicnate5** [comment]
@shuyangzhou We need to do manual testing on this. We do not have automation for Azure file store.

**Comment by vicnate5** [comment]
@jeffwu0724 Found a possible regression when I connected Portal to the Azure Blob Storage.

**Steps to Reproduce:**
1. Start Portal
2. Navigate to Global Menu > Control Panel > System Settings > File Storage > Azure Blob Storage
3. Input Connection String and Container Name (I will DM you the creds). Enable HTTP Logging.
4. Save (you might already see the error)
5. Shutdown portal
6. Add to portal-ext.properties `dl.store.impl=com.liferay.portal.store.azure.AzureStore`
7. Start Portal again

**Expected Result:**
No ClassNotFoundException on step 4 and 7.

**Actual Result:**
```
2022-04-12 22:33:12.742 [parallel-1] [INFO] com.azure.storage.blob.implementation.ContainersImpl$ContainersService.getProperties - --> GET https://blobstoragesmoketest.blob.core.windows.net/containername?restype=containerTry count: 1Date:Tue, 12 Apr 2022 22:33:12 GMTAuthorization:REDACTEDContent-Length:0x-ms-version:2020-10-02x-ms-client-request-id:dffcdc73-d71e-4850-9d7c-b04bef3a6840Accept:application/xmlUser-Agent:azsdk-java-azure-storage-blob/12.14.0 (1.8.0_265; Linux; 5.4.0-42-generic)(empty body)--> END GET
2022-04-12 22:33:12.849 INFO  [parallel-1][ReferenceCountedOpenSslContext:427] BoringSSL doesn't allow to enable or disable TLSv1.3 ciphers explicitly. Provided TLSv1.3 ciphers: 'TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384',
default TLSv1.3 ciphers that will be used: 'TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256'.
2022-04-12 22:33:13.213 [reactor-http-epoll-1] [INFO] com.azure.storage.blob.implementation.ContainersImpl$ContainersService.getProperties - <-- 200 https://blobstoragesmoketest.blob.core.windows.net/containername?restype=container (470 ms, 0-byte body)Last-Modified:Tue, 12 Apr 2022 22:19:56 GMTServer:Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0x-ms-request-id:f517fe6a-a01e-0069-01bd-4e479c000000x-ms-client-request-id:dffcdc73-d71e-4850-9d7c-b04bef3a6840x-ms-version:2020-10-02x-ms-lease-status:unlockedx-ms-lease-state:availablex-ms-has-immutability-policy:falsex-ms-has-legal-hold:falsex-ms-immutable-storage-with-versioning-enabled:REDACTEDx-ms-default-encryption-scope:$account-encryption-keyx-ms-deny-encryption-scope-override:falseDate:Tue, 12 Apr 2022 22:33:13 GMTcontent-length:0eTag:0x8DA1CD293681694(body content not logged)<-- END HTTP
2022-04-12 22:33:13.215 [reactor-http-epoll-1] [DEBUG] com.azure.core.implementation.ReflectionUtils - Failed to retrieve MethodHandles used to check module information. If the application is not using Java 9+ runtime behavior
will work as expected.
java.lang.ClassNotFoundException: java.lang.Module
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1407)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1215)
        at com.liferay.shielded.container.internal.ShieldedContainerClassLoader.findClass(ShieldedContainerClassLoader.java:79)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:418)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:411)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:151)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.azure.core.implementation.ReflectionUtils.<clinit>(ReflectionUtils.java:39)
        at com.azure.core.http.rest.ResponseConstructorsCache.locateResponseConstructor(ResponseConstructorsCache.java:69)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at com.azure.core.http.rest.ResponseConstructorsCache.get(ResponseConstructorsCache.java:45)
        at com.azure.core.http.rest.RestProxy.createResponse(RestProxy.java:468)
        at com.azure.core.http.rest.RestProxy.handleRestResponseReturnType(RestProxy.java:440)
        at com.azure.core.http.rest.RestProxy.lambda$handleRestReturnType$13(RestProxy.java:539)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
        at reactor.core.publisher.FluxDoOnEach$DoOnEachSubscriber.onNext(FluxDoOnEach.java:173)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
        at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionMainSubscriber.onNext(FluxDelaySubscription.java:189)
        at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
        at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:180)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
        at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:284)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)
        at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
        at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
        at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:174)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
        at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2664)
        at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:180)
        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2400)
        at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribeInner(MonoFlatMapMany.java:150)
        at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:189)
        at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
        at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:174)
        at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:160)
        at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:414)
        at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:654)
        at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onStateChange(DefaultPooledConnectionProvider.java:201)
        at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onStateChange(DefaultPooledConnectionProvider.java:457)
        at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:628)
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
        at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1247)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1287)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
2022-04-12 22:33:13.284 [reactor-http-epoll-1] [DEBUG] com.azure.core.util.serializer.JacksonAdapter - Using MethodHandle for setter setXMsMeta on class ContainersGetPropertiesHeaders.
2022-04-12 22:33:13.286 [reactor-http-epoll-1] [DEBUG] com.azure.core.util.serializer.JacksonAdapter - Set header collection xMsMeta on class ContainersGetPropertiesHeaders using MethodHandle.
```
Maybe `If the application is not using Java 9+ runtime behavior
will work as expected` means we can ignore this? I did not have a chance to test with JDK11 runtime (tested with JDK8 runtime)

There was no functionality loss found. I can still upload a new image and it appears in the cloud storage folder on Azure's website.


**Note**
This ClassNotFoundException does not occur when I tested with master upstream. However on master, this error is thrown after restart:
```
ERROR [http-nio-8080-exec-6][ImageImpl:87] Unable to read image 40441
com.liferay.document.library.kernel.exception.NoSuchFileException: {companyId=0, repositoryId=0, fileName=40441.png}
        at com.liferay.portal.store.azure.AzureStore._getFirstFileVersion(AzureStore.java:436) ~[?:?]
```
I suspect this error is due to changing the file store after first startup.

**Comment by tinatian** [comment]
@jeffwu0724 I am going to close this pull for now, please resend once you fixed the issue.

Tina.

**Pull request closed without merging**
