### PR TITLE
LPS-198458 Merge Digester interface and impl into Util in kernel

### PR DESCRIPTION
**Pull request by julschong**
@shuyangzhou
usage in kernel, no moving to portal-impl

@zsoltbalogh
This PR does contain breaking change to release repo since getDigester and setDigester have been removed even though Util is not moved to portal-impl.

The following is used in release repo:
```
ext/7.0.x/ext-modules/core/portal-app-license-impl/src/main/java/com/liferay/portal/app/license/impl/MarketplaceAppLicenseVerifier.java:           
if (DigesterUtil.getDigester() == null) {

ext/7.1.x/ext-modules/core/portal-app-license-impl/src/main/java/com/liferay/portal/app/license/impl/MarketplaceAppLicenseVerifier.java:           
if (DigesterUtil.getDigester() == null) {

ext/7.2.x/ext-modules/core/portal-app-license-impl/src/main/java/com/liferay/portal/app/license/impl/MarketplaceAppLicenseVerifier.java:           
if (DigesterUtil.getDigester() == null) {

ext/7.3.x/ext-modules/core/portal-app-license-impl/src/main/java/com/liferay/portal/app/license/impl/MarketplaceAppLicenseVerifier.java:           
if (DigesterUtil.getDigester() == null) {

ext/7.4.x/ext-modules/core/portal-app-license-impl/src/main/java/com/liferay/portal/app/license/impl/MarketplaceAppLicenseVerifier.java:           
if (DigesterUtil.getDigester() == null) {

```

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
Issues found:

1. Test [com.liferay.saml.opensaml.integration.internal.resolver.DefaultUserResolverTest](https://testray.liferay.com/home/-/testray/case_results/2438079178) failed with errors:
```
## com.liferay.saml.opensaml.integration.internal.resolver.DefaultUserResolverTest > testMatchingUserWithScreenNameAttribute
##

	org.mockito.exceptions.base.MockitoException: Cannot instrument class com.liferay.portal.kernel.util.DigesterUtil because it or one of its supertypes could not be initialized
```
```
## com.liferay.saml.opensaml.integration.internal.resolver.DefaultUserResolverTest > testMatchingUserWithSAMLNameIDValue
##

	org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
	Misplaced or misused argument matcher detected here:
	
	-> at com.liferay.saml.opensaml.integration.internal.resolver.DefaultUserResolverTest.lambda$_mockDigesterUtil$1(DefaultUserResolverTest.java:777)
	
	You cannot use argument matchers outside of verification or stubbing.
	Examples of correct usage of argument matchers:
	    when(mock.get(anyInt())).thenReturn(null);
	    doThrow(new RuntimeException()).when(mock).someVoidMethod(any());
	    verify(mock).someMethod(contains("foo"))
	
	This message may appear after an NullPointerException if the last matcher is returning an object 
	like any() but the stubbed method signature expect a primitive argument, in this case,
	use primitive alternatives.
	    when(mock.get(any())); // bad use, will raise NPE
	    when(mock.get(anyInt())); // correct usage use
	
	Also, this error might show up because you use argument matchers with methods that cannot be mocked.
	Following methods *cannot* be stubbed/verified: final/private/equals()/hashCode().
	Mocking methods declared on non-public parent classes is not supported.
```
Full console:
https://testray.liferay.com/reports/production/logs/2023-10/test-1-25/test-portal-acceptance-pullrequest(master)/3695/modules-unit-jdk8/0/7/jenkins-console.txt.gz?authuser=0

2. Test [com.liferay.portal.search.elasticsearch7.internal.spellcheck.ElasticsearchSpellCheckTest](https://testray.liferay.com/home/-/testray/case_results/2438066086) failed with errors:
```
## com.liferay.portal.search.elasticsearch7.internal.spellcheck.ElasticsearchSpellCheckTest > testSpellCheckMap
##

	java.lang.ExceptionInInitializerError
```
```
## com.liferay.portal.search.elasticsearch7.internal.spellcheck.ElasticsearchSpellCheckTest > testWhitespace
##

	java.lang.NoClassDefFoundError: Could not initialize class com.liferay.portal.kernel.util.DigesterUtil
```
Full console:
https://testray.liferay.com/reports/production/logs/2023-10/test-1-30/test-portal-acceptance-pullrequest(master)/8033/modules-unit-jdk8/0/3/jenkins-console.txt.gz?authuser=0

3. portal-app-license-impl compile failed:
```
    [exec] /opt/dev/projects/github/liferay-portal/modules/core/portal-app-license-impl/src/main/java/com/liferay/portal/app/license/impl/MarketplaceAppLicenseVerifier.java:24: error: cannot find symbol
     [exec] import com.liferay.portal.util.DigesterImpl;
     [exec]                               ^
     [exec]   symbol:   class DigesterImpl
     [exec]   location: package com.liferay.portal.util
     [exec] /opt/dev/projects/github/liferay-portal/modules/core/portal-app-license-impl/src/main/java/com/liferay/portal/app/license/impl/MarketplaceAppLicenseVerifier.java:111: error: cannot find symbol
     [exec] 			digesterUtil.setDigester(new DigesterImpl());
     [exec] 			                             ^
     [exec]   symbol:   class DigesterImpl
     [exec]   location: class com.liferay.portal.app.license.impl.MarketplaceAppLicenseVerifier
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/core/portal-app-license-impl/src/main/java/com/liferay/portal/app/license/internal/AppBundleTracker.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 2 errors
```
Full console:
https://testray.liferay.com/reports/production/logs/2023-10/test-1-25/test-portal-acceptance-pullrequest(master)/3695/portal-license-smoke-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0

4. Semantic versioning issue:
```
     [exec] > Task :apps:portal-search:portal-search-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.search.suggest                  MAJOR      2.0.0      2.0.0      3.0.0      VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.portal.search.suggest.BaseGenericSpellCheckIndexWriter
     [exec] 		-   field      digester
     [exec] 			-   access     protected
     [exec] 			-   return     com.liferay.portal.kernel.util.Digester
     [exec] 		-   method     getDigester()
     [exec] 			-   access     protected
     [exec] 			-   return     com.liferay.portal.kernel.util.Digester
     [exec] 	>   class      com.liferay.portal.search.suggest.BaseSpellCheckIndexWriter
     [exec] 		-   field      digester
     [exec] 			-   access     protected
     [exec] 			-   return     com.liferay.portal.kernel.util.Digester
     [exec] 		-   method     getDigester()
     [exec] 			-   access     protected
     [exec] 			-   return     com.liferay.portal.kernel.util.Digester
     [exec] [Baseline Warning] Bundle Version Change Recommended: 15.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.portal.search.api-14.1.0.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.portal.search.api/14.0.0/7d4e4f2ac78c82d1d81877568163a90aa17b7605/com.liferay.portal.search.api-14.0.0.jar
```
Full console:
https://testray.liferay.com/reports/production/logs/2023-10/test-1-25/test-portal-acceptance-pullrequest(master)/3695/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by julschong** [comment]
added commits for release pull and baseline.

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
still figuring out how to fix search tests

**Comment by julschong** [comment]
rebase and force push

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
Hi @julschong 

The error `java.lang.NoClassDefFoundError: Could not initialize class com.liferay.portal.kernel.util.DigesterUtil` still occurs in the two search tests.

The latest resuls:
[com.liferay.portal.search.elasticsearch7.internal.spellcheck.ElasticsearchSpellCheckTest](https://testray.liferay.com/home/-/testray/case_results/2440220287)
[com.liferay.portal.search.elasticsearch7.internal.suggest.ElasticsearchSuggestTest](https://testray.liferay.com/home/-/testray/case_results/2440220305)

**Comment by julschong** [comment]
@vicnate5 Hi Victor,
I'm really stuck on this issue for a while now. Not really quite sure how but if we test ElasticsearchSpellCheckTest individually, it passes.

I'm able to get that regression when I run with `gw test --tests ElasticsearchMultiLanguageSortTest.testSpanish --tests ElasticsearchSpellCheckTest --tests ElasticsearchSuggestTest`

The error shows up when some test goes before the spell check test. Note that `ElasticsearchMultiLanguageSortTest.testSpanish` is just so unrelated tests get done faster. This also applys to other unrelated tests such as ElasticsearchDocumentSortTest

really out of ideas now because all I did was to move same logic from impl to kernel. And now it just forgot where kernel is ... lol

```
com.liferay.portal.search.elasticsearch7.internal.suggest.ElasticsearchSuggestTest > testNothingToSuggest FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.liferay.portal.kernel.util.DigesterUtil
        at com.liferay.portal.search.suggest.BaseSpellCheckIndexWriter.getUID(BaseSpellCheckIndexWriter.java:223)
        at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSpellCheckIndexWriter.createDocument(ElasticsearchSpellCheckIndexWriter.java:135)
        at com.liferay.portal.search.suggest.BaseGenericSpellCheckIndexWriter.indexKeyword(BaseGenericSpellCheckIndexWriter.java:122)
        at com.liferay.portal.search.suggest.BaseSpellCheckIndexWriter.indexKeyword(BaseSpellCheckIndexWriter.java:77)
        at com.liferay.portal.kernel.search.BaseIndexWriter.indexKeyword(BaseIndexWriter.java:79)
        at com.liferay.portal.search.test.util.suggest.BaseSuggestTestCase.indexSuccessfulQuery(BaseSuggestTestCase.java:77)
        at com.liferay.portal.search.elasticsearch7.internal.suggest.ElasticsearchSuggestTest.testNothingToSuggest(ElasticsearchSuggestTest.java:71)

```

**Comment by vicnate5** [comment]
@julschong This the most recent failure, here is the group of tests that are running together
https://gist.githubusercontent.com/vicnate5/3fbf9d8a9d46f1c22886be538530b9ff/raw/99b1144a868f033cc3de681a177f67d86db5bb89/gistfile1.txt
I think they run in the order listed here.

I suspect one of previously running tests is causing the issue.

So can you try with
```
gw test --tests GetMappingIndexRequestExecutorTest --tests IndicesExistsIndexRequestExecutorTest --tests OpenIndexRequestExecutorTest --tests PutMappingIndexRequestExecutorTest --tests RefreshIndexRequestExecutorTest --tests StatsIndexRequestExecutorTest --tests UpdateIndexSettingsIndexRequestExecutorTest --tests CommonSearchSourceBuilderAssemblerImplTest --tests CreateSnapshotRepositoryRequestExecutorImplTest --tests CreateSnapshotRequestExecutorImplTest --tests DeleteSnapshotRequestExecutorImplTest --tests GetSnapshotRepositoriesRequestExecutorImplTest --tests GetSnapshotsRequestExecutorImplTest --tests RestoreSnapshotRequestExecutorImplTest --tests PathUtilTest --tests UncompressUtilTest --tests ElasticsearchDocumentSortTest --tests ElasticsearchMultiLanguageSortTest --tests ElasticsearchSortFieldTranslatorTest --tests ElasticsearchSortTest --tests ElasticsearchSortUnmappedFieldsTest --tests NestedFieldsSortTest --tests ElasticsearchSpellCheckTest --tests StatisticsTest --tests ElasticsearchSuggestTest --tests SynonymFiltersTest
```

**Comment by vicnate5** [comment]
Re-reading your comment, looks like you already narrowed it down to the test breaking it? Maybe that one has a bad cleanup/deactivate? 

For now maybe we can `@Ignore` that test. I would be happy to take the blame for that and talk to Search team about fixing it.

**Comment by julschong** [comment]
@vicnate5  Okay, I'll add a `@Ignore` for now

**Pull request closed without merging**
