### PR TITLE
LPS-156153 Output all files with missing entries in unit test LibraryReferenceTest.testIntelliJLibPreModules

### PR DESCRIPTION
**Pull request by julschong**
@tinatian Hi Tina,
[LPS-156153](https://issues.liferay.com/browse/LPS-156153)

Issue was found in https://github.com/julschong/liferay-portal/pull/334#issuecomment-1155484998

Currently,

LibraryReferenceTest.testIntelliJLibPreModules unit test will only output the first file with missing entries encountered.

Then, it stops checking the rest.

Example output below:

> [junit] Testcase: testIntelliJLibPreModules(com.liferay.portal.library.LibraryReferenceTest): FAILED
> [junit] util-slf4j/util-slf4j.iml is missing orderEntry elements for modules [portal-log4j]
> [junit] junit.framework.AssertionFailedError: util-slf4j/util-slf4j.iml is missing orderEntry elements for modules [portal-log4j]
> [junit] at com.liferay.portal.library.LibraryReferenceTest.testIntelliJLibPreModules(LibraryReferenceTest.java:126)
> However, test actually fails with multiple files with missing entries.

It would be better to finish checking all files and output all files with missing entries like below:

> [junit] Testcase: testIntelliJLibPreModules(com.liferay.portal.library.LibraryReferenceTest):      FAILED
> [junit] portal-test/portal-test.iml is missing orderEntry elements for modules [portal-log4j]
> [junit] util-java/util-java.iml is missing orderEntry elements for modules [portal-log4j]
> [junit] portal-web/portal-web.iml is missing orderEntry elements for modules [portal-log4j]
> [junit] util-taglib/util-taglib.iml is missing orderEntry elements for modules [portal-log4j]
> [junit]
> [junit] junit.framework.AssertionFailedError: portal-test/portal-test.iml is missing orderEntry elements for modules [portal-log4j]
> [junit] util-java/util-java.iml is missing orderEntry elements for modules [portal-log4j]
> [junit] portal-web/portal-web.iml is missing orderEntry elements for modules [portal-log4j]
> [junit] util-taglib/util-taglib.iml is missing orderEntry elements for modules [portal-log4j]
> [junit]
> [junit]    at com.liferay.portal.library.LibraryReferenceTest.testIntelliJLibPreModules(LibraryReferenceTest.java:146)
>

### CODE REVIEW

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:acceptance

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
Could you please help me scan this test result when its completed?
Thank you!

**Comment by vicnate5** [comment]
@kylo-miho can you check this one?

**Comment by kyle-miho** [comment]
Hey @julschong looks like theres a test design issue
UILD FAILED

/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:14732: The following error occurred while executing this line:

/opt/dev/projects/github/liferay-portal/build-test-batch.xml:6804: 1 PMD violation(s) were found.


PMD VIOLATION: /opt/dev/projects/github/liferay-portal/portal-kernel/test/unit/com/liferay/portal/library/LibraryReferenceTest.java:141 > Do not call Assert#fail improperly. (PMD Rule: AssertFailJUnitRule)

**Comment by julschong** [comment]
@kyle-miho I see, I'll think of something other than Assert.fail(),  btw what's PMD?

**Comment by julschong** [comment]
see #974

**Pull request closed without merging**
