### PR TITLE
[Remove Stream/Optional usage] LPS-171834 headless PART 2 | 1-4

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:headless

**Comment by catarineaguiar** [comment]
@dantewang @JanisZhang possible regressions:

```
     [exec] com.liferay.headless.delivery.resource.v1_0.test.StructuredContentResourceTest > testDeleteAssetLibraryStructuredContentByExternalReferenceCode STARTED
[beanshell] 2023-01-04 07:31:59.961 ERROR [http-nio-8080-exec-3][ExceptionMapper:68] null
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.headless.delivery.dto.v1_0.util.DDMFormValuesUtil._toContentFieldsMap(DDMFormValuesUtil.java:170) ~[?:?]
[beanshell] 	at com.liferay.headless.delivery.dto.v1_0.util.DDMFormValuesUtil._toDDMFormFieldValue(DDMFormValuesUtil.java:189) ~[?:?]
[beanshell] 	at com.liferay.headless.delivery.dto.v1_0.util.DDMFormValuesUtil.lambda$_toDDMFormFieldValues$1(DDMFormValuesUtil.java:230) ~[?:?]
[beanshell] 	at com.liferay.petra.function.transform.TransformUtil.unsafeTransform(TransformUtil.java:86) ~[com.liferay.petra.function.jar:?]
[beanshell] 	at com.liferay.petra.function.transform.TransformUtil.transform(TransformUtil.java:34) ~[com.liferay.petra.function.jar:?]
```
```
     [exec] com.liferay.headless.delivery.resource.v1_0.test.StructuredContentResourceTest > testGraphQLPostSiteStructuredContent FAILED
     [exec]     java.lang.NullPointerException
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.BaseStructuredContentResourceTestCase.equals(BaseStructuredContentResourceTestCase.java:3769)
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.BaseStructuredContentResourceTestCase.testGraphQLPostSiteStructuredContent(BaseStructuredContentResourceTestCase.java:1798)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
```
     [exec] com.liferay.headless.admin.content.resource.v1_0.test.StructuredContentResourceTest > testDeleteStructuredContentByVersion FAILED
     [exec]     java.lang.AssertionError: Thread Thread[http-nio-8080-exec-6,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.vulcan.internal.jaxrs.exception.mapper.ExceptionMapper, message=null
     [exec]     java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.vulcan.internal.jaxrs.exception.mapper.ExceptionMapper, message=null
     [exec]     	at com.liferay.portal.test.rule.LogAssertionTestRule$LogAppender.append(LogAssertionTestRule.java:330)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
     [exec]     	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-26/test-portal-acceptance-pullrequest(master)/6750/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
@JanisZhang It could be caused by my change to remove the null checks. If you are sure some of them can be null at runtime (which means the conditions the test constructed are valid), just remove my related commits.

**Comment by dantewang** [comment]
@JanisZhang Hmmm it seems there should be a null check in `com.liferay.headless.delivery.dto.v1_0.util.DDMFormValuesUtil#_toContentFieldsMap` for the array...

**Pull request closed without merging**
