### PR TITLE
Lps 178732 6 21 2

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:peds-sm

**Comment by catarineaguiar** [comment]
I followed the steps outlined by Summer [here](https://github.com/liferay-core-infra/liferay-portal/pull/4718#issuecomment-1587512464), and the test passed.

According to Kevin [here](https://github.com/liferay-core-infra/liferay-portal/pull/4795#issuecomment-1595336806), the step two has the expected result.

**Comment by tinatian** [comment]
ci:test:peds-sm

**Comment by catarineaguiar** [comment]
no unique failures.

**Pull request closed without merging**
