### PR TITLE
[TS] LPS-162706

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on https://github.com/liferay-core-infra/liferay-portal/pull/1772

cc @ericyanLr

### CODE REVIEW

**Comment by yuhai** [comment]
@zhangyan0701, please help check the test result. Thanks.

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@yuhai @ericyanLr 

It is hard to tell the difference of the methods used to get a correct file name, we may have similar issues later. As this is going to deal with symblic link, could you please try to use Files.isSymbolicLink() to make it more readable?
Also, the problem is we need to deal with symblic link, two possible inputs : 1 ) datebase storing the configuration file name 2) fileinstall.
I would like to do this:
1. For database, add upgrade process to make sure we check the symblic link and always store the correct file name, this way, we do not need to do the checking each time after portal is upgraded.
2. For fileinstall, just skip installation of symblic link.

Thanks.
Tina.

**Comment by ericyanLr** [comment]
@yuhai  @dantewang ,

Can you share your thoughts on how we should proceed with Tina's comments?

Thanks!

**Comment by ericyanLr** [comment]
Hi @tinatian ,

Can you help to elaborate more on how we should approach this? I could not fully understand your suggestions.

**Regarding:**
> It is hard to tell the difference of the methods used to get a correct file name, we may have similar issues later. As this is going to deal with symblic link, could you please try to use Files.isSymbolicLink() to make it more readable?

Is this in regards to this type of pattern: https://github.com/liferay-core-infra/liferay-portal/pull/1819/commits/a705827409fd9b72ac88b6b424c765f0a4c05ee4#diff-cc447657fc25de1c4a1ddb7520f2ddc5c50e138a3b7c589c38975107684092d5R412-R420
- Where we call configsDirPath.**toRealPath()**?

I'm just not sure how we would like to apply the mentioned **Files.isSymbolicLink()** in making it more readable.

Note: I think one thing to mention is we are mainly calling **toRealPath()** for the related **directories** and not the actual file itself.

**Regarding:**
> 1. For database, add upgrade process to make sure we check the symblic link and always store the correct file name, this way, we do not need to do the checking each time after portal is upgraded.

For this, is this to clean-up the extra configurations entries that are generated due to the symbolic link being used?

**Regarding:**
> 2. For fileinstall, just skip installation of symblic link.

I'm not exactly sure what this means, shouldn't we still want to process .config files in osgi/configs, even though they are symlinked?

**Pull request closed without merging**
