### PR TITLE
[Static Reference]LPS-170377 Convert method references to field references in module wiki-navigation-web

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(2022/12/7 9:36)

**Review by dantewang — APPROVED** [review]
@tinatian Looks good to me, but do you think the component should be called `xxxHelper`?

**Comment by W2jx** [comment]
no conflicts(2022/12/8 9:29)

**Comment by W2jx** [comment]
no conflicts(12/9 9:47)

**Pull request closed without merging**
