### PR TITLE
LPS-167880 Remove "immediate = true" from Echo componentes part 3

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
ci:test:echo

**Comment by zhangyan0701** [comment]
Possible regressions:
1. **Recycle Bin scheduler doesn't work.**
Steps:
    1). Add below two properties into portal-ext.properties file: trash.entry.check.interval=1, trash.entries.max.age=1
    2). Add a Blog entry.
    3). Move Blog entry to Recycle Bin.
    4). Wait for 2 minutes.
    5). Assert the Blog entry still displays in Recycle Bin.

Failed case: [LocalFile.RecycleBin#RecycleBinScheduledCleanup](https://testray.liferay.com/home/-/testray/case_results/2041403222)

**2. Warning message thrown in console when save Web Content configuration in System Settings.**
Steps:
    1). Go to System Settings > Web Content > VIRTUAL INSTANCE SCOPE > Web Content.
    2). Click Save button.
    3). Assert below WARN message in console:
```
2022-11-09 10:12:15.103 WARN  [http-nio-8080-exec-5][QuartzSchedulerEngine:727] Scheduler job com.liferay.journal.web.internal.messaging.CheckArticleMessageListener.com.liferay.journal.web.internal.messaging.CheckArticleMessageListener already exists
org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'com.liferay.journal.web.internal.messaging.CheckArticleMessageListener.com.liferay.journal.web.internal.messaging.CheckArticleMessageListener', because one already exists with this identification.
```
Failed case: [LocalFile.WebContentWithPermissions#AddWebContentRemoveGuestViewPermission](https://testray.liferay.com/home/-/testray/case_results/2041343889)

**Comment by tinatian** [comment]
@RenanUmV I am going to close this pull, please resend.

Thanks.
Tina

**Pull request closed without merging**
