### PR TITLE
LPS-143632 Remove LanguageUtil from moduels part 3a mixed

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:acceptance

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina.

**Comment by tinatian** [comment]
@julschong Please review your last commit (6410614b2bfbdb586971f43090745defcb40b059) one more time, let's have a talk tomorrow and see what you can found.

Tina.

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
issues found, close and resending

**Pull request closed without merging**
