### PR TITLE
[Method References 2] LPS-169774 Convert method reference to ServiceTrackerMap in module portal-search-admin-web

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
Waiting for https://github.com/brianchandotcom/liferay-portal/pull/128770 merge to be safe with the tests results.

**Comment by zhangyan0701** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
@W2jx possible regression:

```
     [exec] com.liferay.journal.search.test.JournalFolderSearchTest > testSearchBaseModelWithTrash FAILED
     [exec]     java.lang.AssertionError: {"from":0,"size":10000,"query":{"bool":{"must":[{"bool":{"must":[{"bool":{"should":[{"bool":{"must":[{"match":{"comments":{"query":"Title"}}}],"should":[{"match_phrase":{"comments":{"query":"Title","slop":50}}},{"match_phrase":{"comments":{"query":"Title","boost":2.0}}}]}},{"bool":{"must":[{"match":{"content":{"query":"Title"}}}],"should":[{"match_phrase":{"content":{"query":"Title","slop":50}}},{"match_phrase":{"content":{"query":"Title","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description":{"query":"Title"}}}],"should":[{"match_phrase":{"description":{"query":"Title","slop":50}}},{"match_phrase":{"description":{"query":"Title","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title":{"query":"Title"}}},{"match_phrase_prefix":{"title":{"query":"Title"}}}]}}],"should":[{"match_phrase":{"title":{"query":"Title","boost":2.0}}}]}},{"bool":{"must":[{"match":{"url":{"query":"Title"}}}],"should":[{"match_phrase":{"url":{"query":"Title","slop":50}}},{"match_phrase":{"url":{"query":"Title","boost":2.0}}}]}},{"bool":{"should":[{"match_phrase_prefix":{"userName.text":{"query":"Title"}}}]}},{"bool":{"must":[{"match":{"assetCategoryTitles_en_US":{"query":"Title"}}}],"should":[{"match_phrase":{"assetCategoryTitles_en_US":{"query":"Title","slop":50}}},{"match_phrase":{"assetCategoryTitles_en_US":{"query":"Title","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"assetTagNames_en_US":{"query":"Title"}}},{"match_phrase_prefix":{"assetTagNames_en_US":{"query":"Title"}}}]}}],"should":[{"match_phrase":{"assetTagNames_en_US":{"query":"Title","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description_en_US":{"query":"Title"}}}],"should":[{"match_phrase":{"description_en_US":{"query":"Title","slop":50}}},{"match_phrase":{"description_en_US":{"query":"Title","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description":{"query":"Title"}}}],"should":[{"match_phrase":{"description":{"query":"Title","slop":50}}},{"match_phrase":{"description":{"query":"Title","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title_en_US":{"query":"Title"}}},{"match_phrase_prefix":{"title_en_US":{"query":"Title"}}}]}}],"should":[{"match_phrase":{"title_en_US":{"query":"Title","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title":{"query":"Title"}}},{"match_phrase_prefix":{"title":{"query":"Title"}}}]}}],"should":[{"match_phrase":{"title":{"query":"Title","boost":2.0}}}]}}]}}]}}],"filter":[{"bool":{"must":[{"bool":{"must":[{"terms":{"groupId":["45481"]}},{"terms":{"scopeGroupId":["45481"]}}]}},{"bool":{"should":[{"bool":{"must":[{"term":{"entryClassName":{"value":"com.liferay.journal.model.JournalFolder"}}},{"terms":{"status":["0"]}},{"terms":{"status":["0"]}},{"bool":{"must":[{"bool":{"must_not":[{"exists":{"field":"ctCollectionId"}}]}}]}},{"bool":{"must":[{"bool":{"must_not":[{"exists":{"field":"ctCollectionId"}}]}}]}}]}}]}}]}}]}},"explain":false,"stored_fields":["title_es_ES","entryClassPK","description_ja_JP","description_fr_FR","description","description_ca_ES","description_de_DE","description_hu_HU","title_ar_SA","description_ar_SA","title","title_nl_NL","description_pt_BR","uid","title_ja_JP","description_es_ES","title_pt_BR","title_fi_FI","description_nl_NL","title_ca_ES","entryClassName","description_fi_FI","title_zh_CN","companyId","description_zh_CN","title_sv_SE","description_en_US","description_sv_SE","title_en_US","title_de_DE","title_hu_HU","title_fr_FR"],"track_scores":true,"track_total_hits":2147483647}->[{title_es_ES=[Title], entryClassPK=[45486], description_ja_JP=[This is a test folder.], description_fr_FR=[This is a test folder.], description_ca_ES=[This is a test folder.], description_hu_HU=[This is a test folder.], title_ar_SA=[Title], description_de_DE=[This is a test folder.], description_ar_SA=[This is a test folder.], title_nl_NL=[Title], description_pt_BR=[This is a test folder.], title_ja_JP=[Title], uid=[com.liferay.journal.model.JournalFolder_PORTLET_45486], description_es_ES=[This is a test folder.], title_pt_BR=[Title], title_fi_FI=[Title], description_nl_NL=[This is a test folder.], title_ca_ES=[Title], entryClassName=[com.liferay.journal.model.JournalFolder], description_fi_FI=[This is a test folder.], title_zh_CN=[Title], companyId=[20098], description_zh_CN=[This is a test folder.], title_sv_SE=[Title], description_en_US=[This is a test folder.], description_sv_SE=[This is a test folder.], title_en_US=[Title], title_de_DE=[Title], title_hu_HU=[Title], title_fr_FR=[Title]}, {title_es_ES=[TItljxiD], entryClassPK=[45484], description_ja_JP=[This is a test folder.], description_fr_FR=[This is a test folder.], description_ca_ES=[This is a test folder.], description_hu_HU=[This is a test folder.], title_ar_SA=[TItljxiD], description_de_DE=[This is a test folder.], description_ar_SA=[This is a test folder.], title_nl_NL=[TItljxiD], description_pt_BR=[This is a test folder.], title_ja_JP=[TItljxiD], uid=[com.liferay.journal.model.JournalFolder_PORTLET_45484], description_es_ES=[This is a test folder.], title_pt_BR=[TItljxiD], title_fi_FI=[TItljxiD], description_nl_NL=[This is a test folder.], title_ca_ES=[TItljxiD], entryClassName=[com.liferay.journal.model.JournalFolder], description_fi_FI=[This is a test folder.], title_zh_CN=[TItljxiD], companyId=[20098], description_zh_CN=[This is a test folder.], title_sv_SE=[TItljxiD], description_en_US=[This is a test folder.], description_sv_SE=[This is a test folder.], title_en_US=[TItljxiD], title_de_DE=[TItljxiD], title_hu_HU=[TItljxiD], title_fr_FR=[TItljxiD]}}, length=2, query=null] expected:<1> but was:<2>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at com.liferay.portal.search.test.util.BaseSearchTestCase.assertBaseModelsCount(BaseSearchTestCase.java:266)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-37/test-portal-acceptance-pullrequest(master)/8087/modules-integration-mysql57-jdk8/0/4/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
just rebase

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(1/26 10:21)

**Comment by tinatian** [comment]
@W2jx As both of the usages of IndexReindexerRegistry from the same module, so you do not need to create an interface and export, please do it in portal-search-admin-web directly.

Tina.

**Pull request closed without merging**
