### PR TITLE
[Remove Stream/Optional usages in methods body: adaptive-media part 2]Lps 172202

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-172202

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@slnn semver error:

```
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.kernel.util                     MINOR      52.0.0     52.0.0     52.1.0     VERSION INCREASE REQUIRED
[beanshell] 	<   class      com.liferay.portal.kernel.util.ListUtil
[beanshell] 		+   method     filter(java.util.Collection,java.util.List,java.util.function.Predicate)
[beanshell] 			+   access     static
[beanshell] 			+   return     java.util.Collection
[beanshell] 		+   method     filter(java.util.Collection,java.util.function.Predicate)
[beanshell] 			+   access     static
[beanshell] 			+   return     java.util.Collection
[beanshell] [Baseline Warning] Bundle Version Change Recommended: 93.1.0
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-35/test-portal-acceptance-pullrequest(master)/3313/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
> @slnn semver error:
> 
> ```
> [beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
> [beanshell] = ================================================== ========== ========== ========== ========== ==========
> [beanshell] * com.liferay.portal.kernel.util                     MINOR      52.0.0     52.0.0     52.1.0     VERSION INCREASE REQUIRED
> [beanshell] 	<   class      com.liferay.portal.kernel.util.ListUtil
> [beanshell] 		+   method     filter(java.util.Collection,java.util.List,java.util.function.Predicate)
> [beanshell] 			+   access     static
> [beanshell] 			+   return     java.util.Collection
> [beanshell] 		+   method     filter(java.util.Collection,java.util.function.Predicate)
> [beanshell] 			+   access     static
> [beanshell] 			+   return     java.util.Collection
> [beanshell] [Baseline Warning] Bundle Version Change Recommended: 93.1.0
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-35/test-portal-acceptance-pullrequest(master)/3313/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

Thank @catarineaguiar for catching this, forced push with the fix and rerun tests

**Comment by dantewang** [comment]
@slnn Modified your solution in https://github.com/liferay-core-infra/liferay-portal/pull/3129/commits/1fae488b32843d645547ff918094d5f5f8926834

**Pull request closed without merging**
