### PR TITLE
[Optional Reference] LPS-185539 Convert the Optional Dynamic Greedy references to static references using Snapshot in class SLAInstanceResultWorkflowMetricsReindexer

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(5/25 10:06)

**Comment by W2jx** [comment]
no conflicts(5/26 15:09)

**Comment by W2jx** [comment]
no conflicts(5/29 10:46)

**Comment by dantewang** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@zhangyan0701 Could you double check the latest ci-test-relevant result? Thanks!

**Comment by W2jx** [comment]
no conflicts(5/31 9:42)

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by W2jx** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@W2jx No regressions.

**Comment by W2jx** [comment]
no conflicts(6/2 8:25)

**Comment by W2jx** [comment]
no conflicts(6/5 7:43)

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
