### PR TITLE
LPS-144549

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
The code looks good to me, waiting for QA scan test results.

Tina.

**Comment by guilhermedcamacho** [comment]
ci:reevaluate:1337401_787

**Comment by guilhermedcamacho** [comment]
@zhangyan0701 Please help us scan test results. Thanks!

**Comment by zhangyan0701** [comment]
Just start reviewing.

**Comment by zhangyan0701** [comment]
Have checked the results, no regressions found.

**Comment by guilhermedcamacho** [comment]
@shuyangzhou This pull is good to go. Thanks!

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
