### PR TITLE
[Method References 2] LPS-166968 Convert method reference to ServiceTrackerMap in module data-engine-taglib and data-engine-rest-impl 

### PR DESCRIPTION
**Pull request by W2jx**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3575

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
@W2jx Build rest changes detected
```
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/build.rest.output.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/build.rest.diff.txt
     [echo] diff --git a/modules/apps/data-engine/data-engine-rest-test/src/testIntegration/java/com/liferay/data/engine/rest/resource/v2_0/test/BaseDataDefinitionFieldLinkResourceTestCase.java b/modules/apps/data-engine/data-engine-rest-test/src/testIntegration/java/com/liferay/data/engine/rest/resource/v2_0/test/BaseDataDefinitionFieldLinkResourceTestCase.java
     [echo] index 1fa883703075..d7cbebb97b00 100644
     [echo] --- a/modules/apps/data-engine/data-engine-rest-test/src/testIntegration/java/com/liferay/data/engine/rest/resource/v2_0/test/BaseDataDefinitionFieldLinkResourceTestCase.java
     [echo] +++ b/modules/apps/data-engine/data-engine-rest-test/src/testIntegration/java/com/liferay/data/engine/rest/resource/v2_0/test/BaseDataDefinitionFieldLinkResourceTestCase.java
     [echo] @@ -27,7 +27,6 @@ import com.liferay.data.engine.rest.client.http.HttpInvoker;
     [echo]  import com.liferay.data.engine.rest.client.pagination.Page;
     [echo]  import com.liferay.data.engine.rest.client.resource.v2_0.DataDefinitionFieldLinkResource;
     [echo]  import com.liferay.data.engine.rest.client.serdes.v2_0.DataDefinitionFieldLinkSerDes;
     [echo] -import com.liferay.data.engine.rest.resource.v2_0.test.util.content.type.ModelResourceActionTestUtil;
     [echo]  import com.liferay.petra.reflect.ReflectionUtil;
     [echo]  import com.liferay.petra.string.StringBundler;
     [echo]  import com.liferay.portal.kernel.json.JSONFactoryUtil;
     [echo] @@ -36,9 +35,7 @@ import com.liferay.portal.kernel.json.JSONUtil;
     [echo]  import com.liferay.portal.kernel.log.LogFactoryUtil;
     [echo]  import com.liferay.portal.kernel.model.Company;
     [echo]  import com.liferay.portal.kernel.model.Group;
     [echo] -import com.liferay.portal.kernel.security.permission.ResourceActions;
     [echo]  import com.liferay.portal.kernel.service.CompanyLocalServiceUtil;
     [echo] -import com.liferay.portal.kernel.service.ResourceActionLocalService;
     [echo]  import com.liferay.portal.kernel.test.util.GroupTestUtil;
     [echo]  import com.liferay.portal.kernel.test.util.RandomTestUtil;
     [echo]  import com.liferay.portal.kernel.util.ArrayUtil;
     [echo] @@ -73,14 +70,12 @@ import javax.annotation.Generated;
     [echo]  import javax.ws.rs.core.MultivaluedHashMap;
     [echo]  
     [echo]  import org.junit.After;
     [echo] -import org.junit.AfterClass;
     [echo]  import org.junit.Assert;
     [echo]  import org.junit.Before;
```
[Log](https://testray.liferay.com/reports/production/logs/2023-03/test-1-26/test-portal-acceptance-pullrequest(master)/8092/rest-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(3/14 15:20)

**Comment by W2jx** [comment]
no conflicts(3/17 14:36)

**Comment by W2jx** [comment]
Force-push is just to resolve conflicts about files ```
modules/apps/data-engine/data-engine-api/bnd.bnd
modules/apps/data-engine/data-engine-taglib/src/main/java/com/liferay/data/engine/taglib/internal/servlet/taglib/util/DataLayoutTaglibUtil.java
```

**Comment by W2jx** [comment]
ci:test:data-engine

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(3/21 9:45)

**Comment by dantewang** [comment]
@W2jx The overall change looks good to me, just some details:

1. It's better to completely finish the conversion of `DataDefinitionContentTypeRegistry` first, and then apply it to the util. Please rearrange your changes in git commits.
2. `DataDefinitionContentType` is converted to use method, but `DataLayoutBuilderDefinition` is still using OSGi property, why is that? Actually, the `DefaultDataLayoutBuilderDefinition` doesn't have any implementation detail, I don't think a separate service is needed.

**Pull request closed without merging**
