### PR TITLE
[Replace Non-Blocking Usage] LPS-198892 Replace non-blocking ServiceProxyFactory usages in document/library/

### PR DESCRIPTION
**Pull request by haydenzheng314**
Ticket: https://liferay.atlassian.net/browse/LPS-198892
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by LisztLiszt** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:upgrade:norebase

**Comment by Kvale1733** [comment]
@LisztLiszt No regressions found. Just need to rebase.

**Comment by LisztLiszt** [comment]
Hi @Kvale1733 , this branch has rebased to master

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143603

cc @shuyangzhou @tinatian

**Pull request closed without merging**
