### PR TITLE
[Startup time optimization] LPS-160782

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to disable auto-import-default-references in microblogs-service. Thanks!
https://issues.liferay.com/browse/LPS-160782

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @catarineaguiar , Could you please help to scan the test results? Thank you!

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions.

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
