### PR TITLE
remove_deprecated_propsvalues_and_its_properties

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,
**update2:** I separated the removed deprecated into four commits to improve the review experience.
**update1:** After discussion, I add "portal.jaas.impl" and "verify.process.concurrency.threshold". For "LIVE_USERS_ENABLED" and "PORTAL_JAAS.", I talked with the team and they are still not safe to remove, so I will keep it for now.

I removed the deprecated PropsValue and PropsKey, also updated the portal.properties as well as verifyProperties. This PR is based on PR Remove deprecated part 4 redo.
Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by kyle-miho** [comment]
@jeffwu0724 failures are unrelated

**Comment by tinatian** [comment]
@jeffwu0724 Can you separate the changes into different pulls? For example, for those only need to remove from PropsKeys and PropsValues, send it in one pull. For those need to remove from portal.properties, PropsKeys and PropsValues, also modify VerifyProperties in another pull.

With your current pull, everything mixed together, I have to check every property manually, and there are a lot of properties remove in this one commit, which makes it is harder to review.

Thanks.
Tina.

**Comment by jeffwu0724** [comment]
> @jeffwu0724 Can you separate the changes into different pulls? For example, for those only need to remove from PropsKeys and PropsValues, send it in one pull. For those need to remove from portal.properties, PropsKeys and PropsValues, also modify VerifyProperties in another pull.
> 
> With your current pull, everything mixed together, I have to check every property manually, and there are a lot of properties remove in this one commit, which makes it is harder to review.
> 
> Thanks. Tina.

Got it Tina, I will fix it and submit these new PRs today. Thanks for pointing out

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by kyle-miho** [comment]
@jeffwu0724  com.liferay.portal.kernel.util needs a version bump, see https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=10/401694//consoleText
everything else seems to be good

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result again, please? Not sure if they are the unrelated failures.

Thanks
Jeff

**Comment by tinatian** [comment]
@jeffwu0724 Code conflicts, please rebase.

Thanks.
Tina.

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by kyle-miho** [comment]
@jeffwu0724 pr looks good to go

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114874

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
