### PR TITLE
[Remove Blocking usages]LPS-188582 portal-kernel |HttpUtil

### PR DESCRIPTION
**Pull request by JanisZhang**
https://liferay.atlassian.net/browse/LPS-188582

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by JanisZhang** [comment]
Force-pushed. I only changed the commit message. It shouldn't affect the test results. Thanks!

**Comment by JanisZhang** [comment]
Force-pushed. I only changed the commit message. It shouldn't affect the test results. Thanks!

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
