### PR TITLE
LPS-166596 Fix service builder backward compatibility in older 7.4 portal version

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from #2209

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
rebased for conflict in modules/apps/wiki/wiki-api/bnd.bnd

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@julschong Please return null rather than "return StringPool.BLANK;"

**Comment by catarineaguiar** [comment]
@julschong semver errors on:

[Log 1](https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/4743/modules-semantic-versioning-jdk8/0/2/jenkins-console.txt.gz?authuser=0)
[Log 2](https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/4743/modules-semantic-versioning-jdk8/0/1/jenkins-console.txt.gz?authuser=0)
[Log 3](https://testray.liferay.com/reports/production/logs/2022-11/test-1-38/test-portal-acceptance-pullrequest(master)/4743/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

please, search for `testSemanticVersioning` in these logs to find the errors, thanks!

**Comment by tinatian** [comment]
@julschong I am going to close this, please resend.

Thanks.
Tina

**Pull request closed without merging**
