### PR TITLE
[OrderByComparator] LPD-26342 Clean up and Apply Singleton in module segments and portal-kernel

### PR DESCRIPTION
**Pull request by Valmir-unicap**
- Ticket: https://liferay.atlassian.net/browse/LPD-26342

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:2570488979

**Comment by Valmir-unicap** [comment]
Hey @dantewang, about 2 failures unique from CI, it's a flake, because locally the test passed.

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:2570868558

**Comment by dantewang** [comment]
PanelAppMyAccountPermissionsTest passed locally.

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
