### PR TITLE
[Optional Reference] Lps 185569

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-185569

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
