### PR TITLE
[Upgrade Mockito] LPS-153088

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,
This PR updates Mockito to major version 4 and removes the dependency on PowerMock. Thanks! (https://issues.liferay.com/browse/LPS-153088)

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @catarineaguiar,
Could you please help me scan the test results? thanks!

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:acceptance

**Comment by JanisZhang** [comment]
ci:close

**Pull request closed without merging**
