### PR TITLE
[Component with its own class name as service type] LPS-196226 Refactor Registry classes from multiple modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-196226

Related pull: https://github.com/rafaprax/liferay-portal/pull/1299

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:frontend

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud-acceptance

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:frontend

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud-acceptance

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
No regressions found. Going to run a few more suites to make sure.

**Comment by Kvale1733** [comment]
ci:test:um

**Comment by Kvale1733** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
ci:test:depot

**Comment by Kvale1733** [comment]
ci:test:site-template

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by tinatian** [comment]
@MrJohn1911 Please rebase.

Thanks.
Tina

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:frontend

**Comment by catarineaguiar** [comment]
no regressions found

**Review by rafaprax — APPROVED** [review]

**Comment by tinatian** [comment]
@MrJohn1911 @rafaprax Why you are doing https://github.com/liferay-core-infra/liferay-portal/pull/5910/commits/838b3c581cd886e9e5930a2ee530bfc1fae468e8.

The method you removed is the only usage of service tracker, once you removed it, no one is going to use the new service tracker map you changed to. Then why bother to change it to a service tracker map? if no one is using it, is it possible to remove?

Please resend.

Thanks.
Tina

**Pull request closed without merging**
