### PR TITLE
LPS-172424 Remove Stream usages in portal-search-elasticsearch7-impl part 1

### PR DESCRIPTION
**Pull request by julschong**
@tinatian Hi Tina,
Resubmitted from #3028 and https://github.com/julschong/liferay-portal/pull/726
- Use TransformUtil.transformToArray
- Clean up variable not needed

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@julschong Regression in
com.liferay.portal.search.elasticsearch7.internal.document.DefaultElasticsearchDocumentFactoryTest
```
 [exec] com.liferay.portal.search.elasticsearch7.internal.document.DefaultElasticsearchDocumentFactoryTest > testNullValues FAILED
     [exec]     org.junit.ComparisonFailure: expected:<{"field":[[null,null]]}> but was:<{"field":[[]]}>
     [exec]         at org.junit.Assert.assertEquals(Assert.java:115)
     [exec]         at org.junit.Assert.assertEquals(Assert.java:144)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.document.DefaultElasticsearchDocumentFactoryTest._assertDocument(DefaultElasticsearchDocumentFactoryTest.java:273)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.document.DefaultElasticsearchDocumentFactoryTest.testNullValues(DefaultElasticsearchDocumentFactoryTest.java:220)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-37/test-portal-acceptance-pullrequest(master)/8337/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@julschong No regressions.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129373
specifically https://github.com/brianchandotcom/liferay-portal/pull/129373/commits/b2588a66de94557286735c3f136e200560f794d2

**Pull request closed without merging**
