### PR TITLE
[Move Expando]Lps 190836 11 1

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-190836

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:upgrade

**Comment by slnn** [comment]
ci:test

**Comment by slnn** [comment]
By the way, this pull aims to move the Expando from core to modules and Expando is used so widely in portal that's why the pull is so big. Now we can only rely on CI tests to see if this pull breaks anything of portal.

I have sent this pull many times to run CI tests, I really appreciate our QAs @Kvale1733 and @catarineaguiar for helping me to find the regressions, however, each time, I fix the regression and retrigger the CI tests then we can see new tests are failed which did not caused by my fix. I need QA help to provide a list that contains all the regressions this pull caused then we can reduce the CI load. Thanks in advance!


/cc@dantewang @vicnate5 


Thanks
Lily

**Comment by Kvale1733** [comment]
Hey @slnn. I'll make sure to catch all the issue for this pull. I've look at the history to try to understand what happened.

For the first pull I see there was an issue that caused massed failures: https://github.com/liferay-core-infra/liferay-portal/pull/5381#issuecomment-1692503621

Then for the next pull there was an issue deleting virtual instances that was affecting all tests:
https://github.com/liferay-core-infra/liferay-portal/pull/5753#issuecomment-1760011970

After that there was an compile issue with several upgrade integration tests that prevented them from running
https://github.com/liferay-core-infra/liferay-portal/pull/5802#issuecomment-1769220394

The integration test regressions in the next PR: https://github.com/liferay-core-infra/liferay-portal/pull/5886, didn't fail in the one prior. But the functional failure there and the two other integratio test failures after that in the next PR should have been caught earlier. That's my bad.

The first couple issues were hidden due to the previous issue but we could have had one less pull still. I'll be more careful.

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by slnn** [comment]
> Hey @slnn. I'll make sure to catch all the issue for this pull. I've look at the history to try to understand what happened.
> 
> For the first pull I see there was an issue that caused massed failures: [#5381 (comment)](https://github.com/liferay-core-infra/liferay-portal/pull/5381#issuecomment-1692503621)
> 
> Then for the next pull there was an issue deleting virtual instances that was affecting all tests: [#5753 (comment)](https://github.com/liferay-core-infra/liferay-portal/pull/5753#issuecomment-1760011970)
> 
> After that there was an compile issue with several upgrade integration tests that prevented them from running [#5802 (comment)](https://github.com/liferay-core-infra/liferay-portal/pull/5802#issuecomment-1769220394)
> 
> The integration test regressions in the next PR: #5886, didn't fail in the one prior. But the functional failure there and the two other integratio test failures after that in the next PR should have been caught earlier. That's my bad.
> 
> The first couple issues were hidden due to the previous issues but we could have had one less pull still. I'll be more careful.

Thanks very much!

**Comment by Kvale1733** [comment]
@slnn Regressions found

1) com.liferay.portal.split.packages.SplitPackagesTest

```   
 [junit] Testcase: testSplitPackage(com.liferay.portal.split.packages.SplitPackagesTest):	FAILED
    [junit] Detected split packages in modules/apps/expando/expando-impl and modules/apps/expando/expando-service: [com.liferay.expando.internal]
    [junit] junit.framework.AssertionFailedError: Detected split packages in modules/apps/expando/expando-impl and modules/apps/expando/expando-service: [com.liferay.expando.internal]
    [junit] 	at com.liferay.portal.split.packages.SplitPackagesTest._checkSplitPackages(SplitPackagesTest.java:128)
    [junit] 	at com.liferay.portal.split.packages.SplitPackagesTest.access$000(SplitPackagesTest.java:34)
    [junit] 	at com.liferay.portal.split.packages.SplitPackagesTest$1.preVisitDirectory(SplitPackagesTest.java:86)
    [junit] 	at com.liferay.portal.split.packages.SplitPackagesTest$1.preVisitDirectory(SplitPackagesTest.java:55)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2677)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.split.packages.SplitPackagesTest.testSplitPackage(SplitPackagesTest.java:53)
    ```  
[Log](https://testray.liferay.com/reports/production/logs/2023-11/test-1-32/test-portal-acceptance-pullrequest(master)/2626/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
FYI for the upgrade regressions, this issue is affecting a lot of upgrade tests: https://liferay.atlassian.net/browse/LPS-200623

So you might run into that frequently when testing upgrades. But there were still CI runs that showed the regression I mentioned in number 4, which don't seem to appear anywhere else besides this PR. And I was able to reproduce locally when I first tested.

**Comment by Kvale1733** [comment]
ci:close

**Comment by slnn** [comment]
Fix and resend in https://github.com/liferay-core-infra/liferay-portal/pull/6041

I tested the new pull based on master:f63d698232b7b620536bb32f854286b132fcc07a locally, here are the results:

1.  It fixed com.liferay.portal.split.packages.SplitPackagesTest: https://gist.github.com/slnn/f46cd973c99a8717a2253008b3953171
2.  It fixed com.liferay.portal.search.elasticsearch7.internal.expando.ExpandoTest: https://gist.github.com/slnn/be916afbcec54222b3044b72b86801d8  com.liferay.portal.search.solr8.internal.expando.ExpandoTest: https://gist.github.com/slnn/1fef8d70fe3fc039b991686ea5f8dd54
3.   It fixed the compile issue about headless integration tests, I just tested com.liferay.headless.delivery.resource.v1_0.test.SitePageResourceTest, the compile passed but test failed, however, the test also failed with the master without this pull.
with this pull: https://gist.github.com/slnn/d9c487299b0449824d039fa365752236
master: https://gist.github.com/slnn/e89569e424d4471d0185b1fdb2f9424c
4. For this regressions [[Move Expando]Lps 190836 10 23 #5886 (comment)](https://github.com/liferay-core-infra/liferay-portal/pull/5886#issuecomment-1777977797), I did not reproduce them locally: upgrade: with the steps, I got two sql dumps, one named as upgraded-lportal.sql
[upgraded-lportal.sql.zip](https://github.com/liferay-core-infra/liferay-portal/files/13264217/upgraded-lportal.sql.zip), another named as fresh-lportal.sql [fresh-lportal.sql.zip](https://github.com/liferay-core-infra/liferay-portal/files/13264227/fresh-lportal.sql.zip)
 then I run **ant -f build-test.xml validate-db-upgrade-schemas -Dfresh.db.schema=lportal -Dupgraded.db.schema=lportal** to compare them, then I got this "Database schemas match" from lportal-lportal-validate-db-schemas.txt [lportal-lportal-validate-db-schemas.txt](https://github.com/liferay-core-infra/liferay-portal/files/13264206/lportal-lportal-validate-db-schemas.txt); 
for com.liferay.document.library.internal.upgrade.v3_2_6.test.DeleteStalePWCVersionsUpgradeProcessTest: https://gist.github.com/slnn/3857623b77908f18ac4258aa51fd732f
5. It fixed Semver issues for apps:portal-search:portal-search-api and apps:headless:headless-common-spihttps://gist.github.com/slnn/0f54414c6a7180b9f0a53487ada2cfbb
https://gist.github.com/slnn/746872a253dcfc3e3e802d32538de5e3





> @slnn Regressions found
> 
> 1. com.liferay.portal.split.packages.SplitPackagesTest
> 
> ```
>  [junit] Testcase: testSplitPackage(com.liferay.portal.split.packages.SplitPackagesTest):	FAILED
>     [junit] Detected split packages in modules/apps/expando/expando-impl and modules/apps/expando/expando-service: [com.liferay.expando.internal]
>     [junit] junit.framework.AssertionFailedError: Detected split packages in modules/apps/expando/expando-impl and modules/apps/expando/expando-service: [com.liferay.expando.internal]
>     [junit] 	at com.liferay.portal.split.packages.SplitPackagesTest._checkSplitPackages(SplitPackagesTest.java:128)
>     [junit] 	at com.liferay.portal.split.packages.SplitPackagesTest.access$000(SplitPackagesTest.java:34)
>     [junit] 	at com.liferay.portal.split.packages.SplitPackagesTest$1.preVisitDirectory(SplitPackagesTest.java:86)
>     [junit] 	at com.liferay.portal.split.packages.SplitPackagesTest$1.preVisitDirectory(SplitPackagesTest.java:55)
>     [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2677)
>     [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
>     [junit] 	at com.liferay.portal.split.packages.SplitPackagesTest.testSplitPackage(SplitPackagesTest.java:53)
> ```
> 
> [Log](https://testray.liferay.com/reports/production/logs/2023-11/test-1-32/test-portal-acceptance-pullrequest(master)/2626/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)
> 
> 
> com.liferay.portal.search.elasticsearch7.internal.expando.ExpandoTest com.liferay.portal.search.solr8.internal.expando.ExpandoTest
> 
> ```
>  [exec] com.liferay.portal.search.elasticsearch7.internal.expando.ExpandoTest > initializationError FAILED
> [beanshell]      [exec]     java.lang.NoClassDefFoundError: com/liferay/expando/model/ExpandoColumn
> [beanshell]      [exec]         at java.lang.Class.getDeclaredMethods0(Native Method)
> [beanshell]      [exec]         at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
> [beanshell]      [exec]         at java.lang.Class.getDeclaredMethods(Class.java:1975)
> [beanshell]      [exec]         at org.junit.internal.MethodSorter.getDeclaredMethods(MethodSorter.java:54)
> ```
> 
> [Log](https://testray.liferay.com/reports/production/logs/2023-11/test-1-32/test-portal-acceptance-pullrequest(master)/2626/modules-unit-jdk8/0/10/jenkins-console.txt.gz?authuser=0)
> 
> 3. Compile issue stopped several headless integration tests from running
> 
> ```
> [exec] > Task :apps:iframe:iframe-web:autoUpdateXml SKIPPED
>      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/headless/headless-delivery/headless-delivery-test/src/testIntegration/java/com/liferay/headless/delivery/resource/v1_0/test/SitePageResourceTest.java:1966: error: variable _expandoTableLocalService is already defined in class com.liferay.headless.delivery.resource.v1_0.test.SitePageResourceTest
>      [exec] 	private ExpandoTableLocalService _expandoTableLocalService;
>      [exec] 	                                 ^
>      [exec] 
>      [exec] > Task :apps:headless:headless-delivery:headless-delivery-test:compileTestIntegrationJava
>      [exec] 
>      [exec] > Task :apps:iframe:iframe-web:generateJSPJava
>      [exec] Compiling JSP files of project ':apps:iframe:iframe-web' with /opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.82/webapps/ROOT/WEB-INF/shielded-container-lib/util-taglib.jar as dependency in place of 'com.liferay.portal:com.liferay.util.taglib'
> ```
> 
> [Log](https://testray.liferay.com/reports/production/logs/2023-11/test-1-38/test-portal-acceptance-pullrequest(master)/9529/modules-compile-jdk8/0/1/jenkins-console.txt.gz?authuser=0)
> 
> 4. This regressions [[Move Expando]Lps 190836 10 23 #5886 (comment)](https://github.com/liferay-core-infra/liferay-portal/pull/5886#issuecomment-1777977797) is still present
> 5. Semver issues
>    ```
>    [exec] > Task :apps:portal-search:portal-search-api:baseline
>    [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS
>    [exec] = ================================================== ========== ========== ========== ========== ==========
>    [exec] * com.liferay.portal.search.expando                  MAJOR      1.0.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
>    [exec] 	>   interface  com.liferay.portal.search.expando.ExpandoBridgeIndexer
>    [exec] 		-   method     encodeFieldName(com.liferay.expando.kernel.model.ExpandoColumn)
>    [exec] 			-   access     abstract
>    [exec] 			-   return     java.lang.String
>    [exec] 		+   method     encodeFieldName(com.liferay.expando.model.ExpandoColumn)
>    [exec] 			+   access     abstract
>    [exec] 			+   return     java.lang.String
>    [exec] [Baseline Warning] Bundle Version Change Recommended: 15.0.0
>    [exec] [Baseline Report] Mode: diff (persisted)
>    [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.portal.search.api-14.1.1.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.portal.search.api/14.1.0/2d3ea0772d5adeb769999f7cd9311d24908661ca/com.liferay.portal.search.api-14.1.0.jar
>    [exec]
> 
> ```
> 
> ```
> 
> ```
>    [exec] > Task :apps:headless:headless-common-spi:baseline
>  [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
>  [exec] = ================================================== ========== ========== ========== ========== ==========
>  [exec] * com.liferay.headless.common.spi.odata.entity       MAJOR      1.1.0      1.1.0      2.0.0      VERSION INCREASE REQUIRED
>  [exec] 	>   class      com.liferay.headless.common.spi.odata.entity.EntityFieldsUtil
>  [exec] 		-   method     getEntityFields(long,long,com.liferay.portal.search.expando.ExpandoBridgeIndexer,com.liferay.expando.kernel.service.ExpandoColumnLocalService,com.liferay.expando.kernel.service.ExpandoTableLocalService)
>  [exec] 			-   access     static
>  [exec] 			-   return     java.util.List
>  [exec] 		+   method     getEntityFields(long,long,com.liferay.portal.search.expando.ExpandoBridgeIndexer,com.liferay.expando.service.ExpandoColumnLocalService,com.liferay.expando.service.ExpandoTableLocalService)
>  [exec] 			+   access     static
>  [exec] 			+   return     java.util.List
>  [exec] [Baseline Warning] Bundle Version Change Recommended: 10.0.0
>  [exec] [Baseline Report] Mode: diff (persisted)
>  [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.headless.common.spi-9.0.1.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.headless.common.spi/9.0.0/24c545cc9c8eba98bf16a9712c4841ad835108d5/com.liferay.headless.common.spi-9.0.0.jar  
> ```

**Pull request closed without merging**
