### PR TITLE
[Replace Non-Blocking Usage] LPS-199715

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace non-blocking ServiceProxyFactory usages in class `ExportImportHelperUtil`, `ExportImportProcessCallbackRegistryUtil`, `PortletDataContextFactoryUtil`, and `PortletDataHandlerStatusMessageSenderUtil`. Thanks.
https://liferay.atlassian.net/browse/LPS-199715

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
@JanisZhang tests failed on startup due to:

```
     [exec]       [waitfor] 2023-10-24 19:41:20.435 ERROR [main][MainServlet:373] null
     [exec]       [waitfor] java.lang.NullPointerException: null
     [exec]       [waitfor] 	at com.liferay.exportimport.kernel.lar.PortletDataContextFactoryUtil.createPreparePortletDataContext(PortletDataContextFactoryUtil.java:62) ~[portal-kernel.jar:?]
     [exec]       [waitfor] 	at com.liferay.portal.service.impl.GroupLocalServiceImpl.addPortletDefaultData(GroupLocalServiceImpl.java:4109) ~[portal-impl.jar:?]
     [exec]       [waitfor] 	at com.liferay.portal.service.impl.GroupLocalServiceImpl.addGroup(GroupLocalServiceImpl.java:528) ~[portal-impl.jar:?]
     [exec]       [waitfor] 	at com.liferay.portal.service.impl.GroupLocalServiceImpl.addGroup(GroupLocalServiceImpl.java:543) ~[portal-impl.jar:?]
     [exec]       [waitfor] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
     [exec]       [waitfor] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
     [exec]       [waitfor] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
     [exec]       [waitfor] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-27/test-portal-acceptance-pullrequest(master)/10471/functional-upgrade-tomcat90-mysql57-jdk8/1/24/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
