### PR TITLE
LPS-168208 Remove "immediate = true" from Commerce III

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
**Many Commerce functional tests failed due to the portlets are not available in Minium Site > Catalog page.**

fail

And below error in portal log:
```
2022-11-10 17:46:18.048 ERROR [http-nio-8080-exec-7][PortletRequestDispatcherImpl:304] Unable to dispatch request: java.lang.NullPointerException
2022-11-10 17:46:18.049 ERROR [http-nio-8080-exec-7][PortletServlet:117] null
javax.portlet.PortletException: org.apache.jasper.JasperException: java.lang.NullPointerException
```
Example console log:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-31/test-portal-acceptance-pullrequest(master)/5832/functional-tomcat90-mysql57-jdk8/2/13/jenkins-console.txt.gz?authuser=0

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by MrJohn1911** [comment]
Hey @shuyangzhou this one is good to go.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126460

**Pull request closed without merging**
