### PR TITLE
LPD-16069 Fix com.liferay.portal.test.rule.callback.InjectTestRuleTest

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://liferay.atlassian.net/browse/LPD-16069

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
@tinatian I tested locally on jkd8 and jdk21.

I just triggered the relevant here to be sure that I did not break the `@Inject` feature used on integration tests.

Thx

**Comment by rafaprax** [comment]
Hey @tinatian,

As we talked, I reverted the https://github.com/liferay/liferay-portal/commit/042b6f8af6515c768dfeadb8cd05650762102588 . I did not run the `CounterLocalServiceTest.java` locally but this `@Inject` use case is covered by the `InjectTestRuleTest` test.

Thx

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/146858

**Pull request closed without merging**
