### PR TITLE
LPS-162507

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Two components registering upgrade steps for the same module can deal to race condition and enab

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
@Kvale1733 Could you review the test results when they finish? Thanks!

**Review by dantewang — APPROVED** [review]
@marianoalvarosaiz Code looks good to me, if it passes tests I'll pass it to Tina.

**Comment by Kvale1733** [comment]
@dantewang @marianoalvarosaiz No regressions found. The failing upgrades tests pass locally.

**Comment by tinatian** [comment]
@achaparro Could you please review this pull? This is related the bug you fixed at https://issues.liferay.com/browse/LPS-154017

**Comment by achaparro** [comment]
Hi @tinatian,

@marianoalvarosaiz contacted me before sending the pull. This is a rare case because the module had a different name before and we use the _initialDeploymentUpgradeStep_ to rename it. It is quite tricky because we have to cover multiple cases depending on from what version the customer upgrades (both registrators must be enabled so we also upgrade customers that are in newer schema versions and do not execute the initialDeploymentUpgrade)

In conclusion, the changes are good and cover all use cases. The only issue is that we are not following the pattern that uses a specific Registrator for initialUpgradeDeployment. Another option that came to my mind is to create a specific registrator for initialDeploymentUpgrade and enable _ClientExtensionUpgradeStepRegistrator_ if the release has already the value _com.liferay.client.extension.service_, this must be done outside the initialUpgradeDeployment upgrade.

Anyway, as I said, if the code looks good to you, we can make an exception and commit these changes since cover all use cases.

Cheers!

**Comment by tinatian** [comment]
@achaparro How many cases we need to deal with? Could you please list it? 
@vicnate5 Do you know if we have tests cover this kind of issue?

**Comment by vicnate5** [comment]
@tinatian We have some tests failing upstream that are now passing due this change. This fixes some blockers have right now. Based on our testing, changes in https://issues.liferay.com/browse/LPS-159772 revealed the effects of this upgrade process issue.

In my testing this PR fixes
https://issues.liferay.com/browse/LPS-163463 
https://issues.liferay.com/browse/LPS-163271

This is an edge case because we do not normally rename released modules in 7.4.

CC @LuisOrtiz89  @lucasperj @susanchen3 @Kvale1733

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123392

**Pull request closed without merging**
