### PR TITLE
[Optional Reference]LPS-185538 module: layout

### PR DESCRIPTION
**Pull request by JanisZhang**
resend, previous:https://github.com/liferay-core-infra/liferay-portal/pull/4604
https://issues.liferay.com/browse/LPS-185538
Thanks!

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:echo

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@JanisZhang Code change looks good, please update the message of the first commit to include a brief explanation.

**Comment by JanisZhang** [comment]
force-pushed. I only changed the commit message, it shouldn't affect the test results. thanks! cc @dantewang @zhangyan0701

**Comment by dantewang** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/135812

**Pull request closed without merging**
