### PR TITLE
Lps 180672 hypersonic 4 4

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:backend-hypersonic

**Comment by dantewang** [comment]
@tinatian @vicnate5 It seems none of the "rebuild-*" targets in `sql/build-parent.xml` are called by any code inside the portal codebase. `build-test.xml` has its own logic to pre-import the sqls to corresponding databases.

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@tinatian 
Looks like there is a regression in the portal-license-smoke batch. It failed twice on this pr with the same error. I checked the previous pr and it looks like this batch failed for the same reason also, but it was missed. So it does look caused by these changes.

```
reset-license-key-validation:
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:6846: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:6880: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:12459: Cannot perform operation from directory to file.
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-26/test-portal-acceptance-pullrequest(master)/8724/portal-license-smoke-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

@vicnate5 Looks like it fails at the prepare-release-bundle target in build-test.xml. But I can't reproduce locally since I don't have access to the release too. Not sure how these changes cause this issue.

**Comment by vicnate5** [comment]
The failure looks like it is due to tomcat not starting, I will reproduce locally and take a closer look.

**Comment by Kvale1733** [comment]
@vicnate5 Resent here with the suggested fix: https://github.com/liferay-core-infra/liferay-portal/pull/4227

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
