### PR TITLE
[Optional Reference]LPS-185556 module: journal-web

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-185556

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by JanisZhang** [comment]
ci:forward:force

**Comment by JanisZhang** [comment]
manually forward to https://github.com/brianchandotcom/liferay-portal/pull/135625

**Pull request closed without merging**
