### PR TITLE
[OrderByComparator] LPD-25934 Clean up and Apply Singleton in fragment module

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:echo

**Comment by tinatian** [comment]
ci:report:2570841826

**Comment by dantewang** [comment]
ci:test:echo

**Comment by dantewang** [comment]
Code looks good, retrigger echo tests to confirm.

**Comment by MrJohn1911** [comment]
ci:report:2571048208

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:echo

**Comment by MrJohn1911** [comment]
My last changes were just to modify the name of the method from "get" to "getInstance"

**Comment by MrJohn1911** [comment]
ci:report:2571281956

**Pull request closed without merging**
