### PR TITLE
[Test Fix] LPD-39547 Fix NullConvertibleEntryTest, remove testGetNullConvertibleEntries and add null string conversion test

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:core-functional

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:core-functional

**Comment by julschong** [comment]
test passed
@tinatian this PR's last commit is for test only. let me know if this solution with teardown is good and I will take off the last commit

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:core-functional

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:core-functional

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
fix sf and removed ci test commit

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:environments

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
