### PR TITLE
[Method References 2] LPS-171384 Convert method reference to ServiceTrackerMap in class DispatchTriggerMetadataProviderImpl(module dispatch-service)

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@W2jx no regressions found.

**Comment by W2jx** [comment]
no conflicts（12/20 10:07）

**Comment by W2jx** [comment]
Force-Push is just to remove the logic to validate osgi property value.

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
no conflicts(12/21 17:05)

**Comment by tinatian** [comment]
ci:forward

FYI @shuyangzhou

**Pull request closed without merging**
