### PR TITLE
[SF] LPS-200631 Add module path to checkUnusedReferenceVariableDirNames.

### PR DESCRIPTION
**Pull request by JanisZhang**
https://liferay.atlassian.net/browse/LPS-200631

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
SF failure is not related.

**Comment by JanisZhang** [comment]
ci:forward:force
CC @dantewang @shuyangzhou

**Pull request closed without merging**
