### PR TITLE
LPS-158624 Cleanup petra-xml

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from #2057

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong Seems relevant is failing to run tests due to

```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/internal/content/compatibility/converter/JournalContentCompatibilityConverterImpl.java:23: error: cannot find symbol
     [exec] import com.liferay.petra.xml.XMLUtil;
     [exec]                             ^
     [exec]   symbol:   class XMLUtil
     [exec]   location: package com.liferay.petra.xml
```

**Comment by julschong** [comment]
@Kvale1733 Hi Kevin, this is interesting.
I

**Comment by julschong** [comment]
will resend

**Pull request closed without merging**
