### PR TITLE
LPS-174536 Remove "immediate = true" from remaining BundleBlacklist components

### PR DESCRIPTION
**Pull request by daiazius**
This pull is related to this ticket: https://issues.liferay.com/browse/LPS-170283

Please make sure to reproduce the steps to assert that the regression is not reproducing.

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
@daiazius failure on startup:

```
[beanshell] 2023-02-02 20:53:32.430 WARN  [main][SystemCheckOSGiCommands:154] Missing Component Scanner check result: @@@@Name: com.liferay.portal.bundle.blacklist.internal.BundleBlacklistManagerImpl
[beanshell] @@Instances:
[beanshell] id: 21
[beanshell] State: 2
[beanshell]  Satisfied references: 
[beanshell] 	Name: _configurationAdmin
[beanshell] Unsatisfied references: 
[beanshell] 	Name: _bundleBlacklist
[beanshell] 2023-02-02 20:53:32.430 INFO  [main][SystemCheckOSGiCommands:131] Running "Declarative Service Soft Circular Dependency Checker". You can run this by itself with command "ds:softCircularDependency" in gogo shell.
[beanshell] 2023-02-02 20:53:35.015 INFO  [main][SystemCheckOSGiCommands:143] Declarative Service Soft Circular Dependency Checker check result: No issues were found.
[beanshell] 2023-02-02 20:53:35.015 INFO  [main][SystemCheckOSGiCommands:131] Running "Declarative Service Unsatisfied Component Checker". You can run this by itself with command "ds:unsatisfied" in gogo shell.
[beanshell] 2023-02-02 20:53:47.783 WARN  [main][SystemCheckOSGiCommands:154] Declarative Service Unsatisfied Component Checker check result: 
[beanshell] Bundle {id: 7, name: com.liferay.portal.bundle.blacklist.impl, version: 4.0.19}
[beanshell] 	Declarative Service {id: 21, name: com.liferay.portal.bundle.blacklist.internal.BundleBlacklistManagerImpl, unsatisfied references: 
[beanshell] 		{name: _bundleBlacklist, target: null}
[beanshell] 	}
[beanshell] Bundle {id: 1046, name: com.liferay.marketplace.app.manager.web, version: 5.0.37}
[beanshell] 	Declarative Service {id: 9471, name: com.liferay.marketplace.app.manager.web.internal.portlet.MarketplaceAppManagerPortlet, unsatisfied references: 
[beanshell] 		{name: _bundleBlacklistManager, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 9469, name: com.liferay.marketplace.app.manager.web.internal.application.list.MarketplaceAppManagerPanelApp, unsatisfied references: 
[beanshell] 		{name: Portlet, target: (javax.portlet.name=com_liferay_marketplace_app_manager_web_portlet_MarketplaceAppManagerPortlet)}
[beanshell] 	}
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-02/test-1-28/test-portal-acceptance-pullrequest(master)/5684/functional-smoke-startup-tomcat90-mysql57-jdk8/0/6/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found.

The tests with unique failures passed locally.

**Comment by tinatian** [comment]
@daiazius Please fix the commit message of https://github.com/liferay-core-infra/liferay-portal/pull/3288/commits/d04dbe7f6139bc59a0e585831737c5ec7aadd6c6

**Comment by catarineaguiar** [comment]
@daiazius @MrJohn1911 this [bug](https://issues.liferay.com/browse/LPS-170283) is not reproducible with your changes, but a warn appeared on startup using Liferay Online properties:

```
2023-02-07 16:55:41.807 WARN  [main][SystemCheckOSGiCommands:154] Declarative Service Unsatisfied Component Checker check result: 
Bundle {id: 1187, name: com.liferay.object.scripting.impl, version: 1.0.6}
	Declarative Service {id: 5626, name: com.liferay.object.scripting.internal.executor.GroovyObjectScriptingExecutor, unsatisfied references: 
		{name: _scriptingExecutor, target: (scripting.language=groovy)}
	}
Bundle {id: 1188, name: com.liferay.object.service, version: 1.0.134}
	Declarative Service {id: 5732, name: com.liferay.object.internal.validation.rule.GroovyObjectValidationRuleEngineImpl, unsatisfied references: 
		{name: _objectScriptingExecutor, target: (scripting.language=groovy)}
	}
	Declarative Service {id: 5630, name: com.liferay.object.internal.action.executor.GroovyObjectActionExecutorImpl, unsatisfied references: 
		{name: _objectScriptingExecutor, target: (scripting.language=groovy)}
	}
```

**Comment by tinatian** [comment]
@MrJohn1911 @rafaprax This is really weird, why we need it? https://github.com/liferay-core-infra/liferay-portal/pull/3288/commits/cfe3bde3803403bb785048d1afc9ae37e6b94d86

**Comment by MrJohn1911** [comment]
> @MrJohn1911 @rafaprax This is really weird, why we need it? [cfe3bde](https://github.com/liferay-core-infra/liferay-portal/commit/cfe3bde3803403bb785048d1afc9ae37e6b94d86)

Hi @tinatian, I used this based on this [pull](https://github.com/brianchandotcom/liferay-portal/pull/129399/commits/b0bfa0682cf33e7ea8cf15e2a9dc2d27d1e1333c) from Shuyang, because I removed the service property and the references for BundleBlacklist where unsatisfied, so with this solution, the component is being implied as immediate and the service is still being registered.

**Comment by tinatian** [comment]
@MrJohn1911 This is not the right direction to fix the issue, please resend.

Thanks.
Tina

**Pull request closed without merging**
