### PR TITLE
[Move Expando:circluar dependency in local service]Lps 191596 9 13

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-191596

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@slnn regression found:

```
     [exec] com.liferay.users.admin.internal.portlet.action.test.ExportUsersMVCResourceCommandTest > testGetUserCSVWithExpando FAILED
     [exec]     com.liferay.expando.kernel.exception.NoSuchTableException: No ExpandoTable exists with the key {companyId=52474, classNameId=20070, name=CUSTOM_FIELDS}
     [exec]     	at com.liferay.portlet.expando.service.persistence.impl.ExpandoTablePersistenceImpl.findByC_C_N(ExpandoTablePersistenceImpl.java:677)
     [exec]     	at com.liferay.portlet.expando.service.impl.ExpandoValueLocalServiceImpl.getData(ExpandoValueLocalServiceImpl.java:1303)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41)
     [exec]     	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-09/test-1-25/test-portal-acceptance-pullrequest(master)/3277/modules-integration-mysql57-jdk8/4/12/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
> @slnn regression found:
> 
> ```
>      [exec] com.liferay.users.admin.internal.portlet.action.test.ExportUsersMVCResourceCommandTest > testGetUserCSVWithExpando FAILED
>      [exec]     com.liferay.expando.kernel.exception.NoSuchTableException: No ExpandoTable exists with the key {companyId=52474, classNameId=20070, name=CUSTOM_FIELDS}
>      [exec]     	at com.liferay.portlet.expando.service.persistence.impl.ExpandoTablePersistenceImpl.findByC_C_N(ExpandoTablePersistenceImpl.java:677)
>      [exec]     	at com.liferay.portlet.expando.service.impl.ExpandoValueLocalServiceImpl.getData(ExpandoValueLocalServiceImpl.java:1303)
>      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>      [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>      [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
>      [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41)
>      [exec]     	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60)
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2023-09/test-1-25/test-portal-acceptance-pullrequest(master)/3277/modules-integration-mysql57-jdk8/4/12/jenkins-console.txt.gz?authuser=0)

Thank @catarineaguiar for catching this! I have fixed it  and rerun ci tests

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@slnn There are too many repeated exception throwing logic in this PR, although you replaced some of them with `findBy`.

And for `com.liferay.portlet.expando.service.impl.ExpandoColumnLocalServiceImpl#getColumn(long, long, java.lang.String, java.lang.String)`, you can't simply throw `NoSuchColumn...` upon null return value, because if the table is not found, it also returns null.

The fact of this mess may be that we don't strictly distinguish `fetch` & `get` in local services. I think a cleaner way is to rename the current `getColumn` that use `fetchBy` internally to `fetchColumn`, and add new `getColumn` to use `findBy`. Then you can apply these methods accordingly.

Please resend, thanks!

cc @shuyangzhou

**Pull request closed without merging**
