### PR TITLE
[TS] LPS-157252,LPS-161024

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-157252

https://issues.liferay.com/browse/LPS-161024

I'm sending these PRs together since they are related and the tests for LPS-157252 won't pass without the fix for LPS-161024.

Resent from https://github.com/liferay-core-infra/liferay-portal/pull/1175

Original message:

> Split up main logic changes from SF changes, and added logic to make sure only control panel pages could set language from session's locale.

> This new solution includes an edge case fix where the control panel cannot have it's language translated.  By reading in the session locale, we can now adjust the locale of the given page if needed.

> In the scenario where the user is requesting their default language, the portal and user default language is the same, but the current virtualHost's default language is different, then the portal will still provide the URL without any language code.  This is because the portal is not taking into account the virtualHost's default language when (not) setting the i18nPath to the requested language.  Further, having a virtualHost default language works against the `LOCALE_PREPEND_FRIENDLY_URL_STYLE` 3 (which is the default value) because now the specified virtualHost (without languageId in the URL) only points to one language, instead of any available language.
> 
> With my changes, the portal now considers if the virtualHost has a default language, and will include a `i18nPath` value if the requested language is different.
> 
> Please let me know if you have any questions, thanks!

CC @crodriguezy

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@ChrisKian Could you send LPS-161024 to USM team for review, and resend LPS-157252 once LPS-161024 is merged?

**Comment by crodriguezy** [comment]
Manually forwarded to Brian https://github.com/brianchandotcom/liferay-portal/pull/121982

**Comment by ChrisKian** [comment]
LPS-161024 sent here: https://github.com/liferay-usm/liferay-portal/pull/701

**Comment by crodriguezy** [comment]
Hi @ChrisKian .  https://github.com/brianchandotcom/liferay-portal/pull/122732 is already merged, so I guess you can resend LPS-157252 changes? Let me know if you need any help.
Thanks!

**Comment by ChrisKian** [comment]
Resent here: https://github.com/liferay-core-infra/liferay-portal/pull/1803

**Pull request closed without merging**
