### PR TITLE
[Remove unused @Reference var] LPS-164874

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove the unused @reference variable in module `asset` (MISC). Thanks!

https://issues.liferay.com/browse/LPS-164874

### CODE REVIEW

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
@JanisZhang I think it's safe to remove the reference in https://github.com/liferay-core-infra/liferay-portal/pull/1882/commits/cb160f246554fdc29cc194d089cc9e2b8d6e8b0c because the jsps it renders doesn't use LayoutLocalServiceUtil at all; even if they use, it should be safe because JSPs should only be rendered after portal startup finishes.

But for https://github.com/liferay-core-infra/liferay-portal/pull/1882/commits/55a08b3aa5c1820b53a8d1a102a139656747ef37, could you double check whether there's hidden usage? If not I'll send this PR to Brian.

**Comment by JanisZhang** [comment]
@dantewang, I think it doesn't have hidden usages.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/124457

cc @shuyangzhou @tinatian

**Pull request closed without merging**
