### PR TITLE
[TS] LPS-190994

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:clustering

**Comment by catarineaguiar** [comment]
ci:test:clustering

**Comment by catarineaguiar** [comment]
@marianoalvarosaiz I'm not sure what is stucking tests on CI, so can you resend the PR to check if it can be resolved?

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by zhangyan0701** [comment]
ci:test:clustering

**Comment by catarineaguiar** [comment]
no regressions found. Bug not reproducible

**Comment by shuyangzhou** [comment]
@marianoalvarosaiz this is going to the completely wrong direction. Rather than accepting 0 interval as disabling the job, the 0 interval should result to not register SchedulerJobConfiguration as service at all.

If the goal of the ticket is to provide a way to disable certain builtin scheduler job via portal properties, you should do it in a straight forward way by not registering anything for the job on seeing it being disabled.

Please talk to @dantewang to clarify your requirement and goal.

**Pull request closed without merging**
