### PR TITLE
LPS-199600 sync versions.html and versions-complete.xml as they are not updated in master

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Dante, 

As you said in https://github.com/liferay-core-infra/liferay-portal/pull/5796#pullrequestreview-1689448321, I have "sent out a PR to run build-lib-versions on master to make the files in sync", and rebase https://github.com/liferay-core-infra/liferay-portal/pull/5796.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

**Comment by jeffwu0724** [comment]
ci:forward:force

**Comment by jeffwu0724** [comment]
ci:forward:force

**Pull request closed without merging**
