### PR TITLE
[Remove unused @Reference var] LPS-164887 

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove the unused @reference variable in the module `portal- search`. Thanks!

All tests passed in https://github.com/JanisZhang/liferay-portal/pull/136

https://issues.liferay.com/browse/LPS-164887

### CODE REVIEW

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@Kvale1733 I triggered the relevant suite for 2 additional runs because this PR removes references added but never used, just to reduce the possibility of random failure. Could you please check the addtional results when they finish? Thanks!

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:forward

@shuyangzhou @tinatian

**Pull request closed without merging**
