### PR TITLE
LPS-174369 Remove module life cycle dependencies from message listene…

### PR DESCRIPTION
**Pull request by tinatian**
…r which used to register scheduler

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3394

**Pull request closed without merging**
