### PR TITLE
LPS-199287 Merge File interface and impl into Util in kernel


### PR DESCRIPTION
**Pull request by julschong**
resubmitted from https://github.com/liferay-core-infra/liferay-portal/pull/5801

Added https://github.com/liferay-core-infra/liferay-portal/pull/5852/commits/e1414665844304986b82cf2bebc21246e386a7e0
And
https://github.com/liferay-core-infra/liferay-portal/pull/5852/commits/861b68f23fdd0aad350ba530a7d23bead0685b1b

@Kvale1733
Hi Kevin, this is my attempt to fix https://github.com/liferay-core-infra/liferay-portal/pull/5801#issuecomment-1773085767

Regressions:

1. This shouldve been fix by apply the release PR url https://github.com/liferay-core-infra/liferay-portal/pull/5852/commits/f1362e92e31febccad1578bf60a51e6261f5934e so I didnt do anything extra. Please let me know if issue persists.

2. `private com.liferay.portal.kernel.util.File _file;` Corrected

3. `Could not initialize class com.liferay.portal.kernel.util.FileUtil` Corrected in https://github.com/liferay-core-infra/liferay-portal/pull/5852/commits/1f926cafebbec8db99ce19db86153f911f7f891f

4. `IllegalArgumentException: Cannot coerce 0() to any of []` - https://github.com/liferay-core-infra/liferay-portal/pull/5852/commits/861b68f23fdd0aad350ba530a7d23bead0685b1b

This one needs your help to test. I tried locally but cannot get the command to run correctly.
It keeps trying to use telnet localhost 11312 to connect but fails. I'm guessing some property need to be set in `portal-ext.properties` to open that port. 
But I was able to telnet localhost 11311 and ran the gogo-command.sh to get the correct output
image

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
@julschong There are some conflicts, please resolve them first, thanks!

**Comment by julschong** [comment]
rebased and reordered some commits

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@julschong So the regression with the scripts does seem to be fixed. At least for our uses, there is no issue. 

Only one compile issue now. 

```
     [exec] import com.liferay.portal.util.FileImpl;
     [exec]                               ^
     [exec]   symbol:   class FileImpl
     [exec]   location: package com.liferay.portal.util
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/core/portal-app-license-impl/src/main/java/com/liferay/portal/app/license/internal/AppBundleTracker.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 1 error
     [exec] 
     [exec] > Task :core:portal-app-license-impl:compileJava FAILED
     [exec] 
 ```
 [Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-37/test-portal-acceptance-pullrequest(master)/15148/portal-license-smoke-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
The above issue was caught by stable license batch btw so it would be enough to just rerun stable.

**Comment by julschong** [comment]
updated release repo change, retesting

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by julschong** [comment]
changed breaking change commit format https://github.com/liferay-core-infra/liferay-portal/pull/5852/commits/1672c15dfcbff3ff86dc3044dccffebc55ba2530

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong Regression found in com.liferay.portal.upload.LiferayInputStreamTest. I was able to reproduce locally.

```
 [junit] Testcase: com.liferay.portal.upload.LiferayInputStreamTest:	Caused an ERROR
    [junit] 
    [junit] Unfinished stubbing detected here:
    [junit] -> at com.liferay.portal.upload.LiferayInputStreamTest.setUpClass(LiferayInputStreamTest.java:39)
    [junit] 
    [junit] E.g. thenReturn() may be missing.
    [junit] Examples of correct stubbing:
    [junit]     when(mock.isOk()).thenReturn(true);
    [junit]     when(mock.isOk()).thenThrow(exception);
    [junit]     doThrow(exception).when(mock).someVoidMethod();
    [junit] Hints:
    [junit]  1. missing thenReturn()
    [junit]  2. you are trying to stub a final method, which is not supported
    [junit]  3. you are stubbing the behaviour of another mock inside before 'thenReturn' instruction is completed
    [junit] 
    [junit] org.mockito.exceptions.misusing.UnfinishedStubbingException: 
    [junit] Unfinished stubbing detected here:
    [junit] -> at com.liferay.portal.upload.LiferayInputStreamTest.setUpClass(LiferayInputStreamTest.java:39)
    [junit] 
    [junit] E.g. thenReturn() may be missing.
    [junit] Examples of correct stubbing:
    [junit]     when(mock.isOk()).thenReturn(true);
    [junit]     when(mock.isOk()).thenThrow(exception);
    [junit]     doThrow(exception).when(mock).someVoidMethod();
    [junit] Hints:
    [junit]  1. missing thenReturn()
    [junit]  2. you are trying to stub a final method, which is not supported
    [junit]  3. you are stubbing the behaviour of another mock inside before 'thenReturn' instruction is completed
    [junit] 
    [junit] 	at com.liferay.portal.kernel.util.FileUtil.createTempFile(FileUtil.java:181)
    [junit] 	at com.liferay.portal.upload.LiferayInputStreamTest.setUpClass(LiferayInputStreamTest.java:42)
    [junit] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    [junit] 
    [junit] 
    [junit] Test com.liferay.portal.upload.LiferayInputStreamTest FAILED
    [junit] Running com.liferay.portal.util.JarUtilTest
    [junit] Testsuite: com.liferay.portal.util.JarUtilTest
  ```
  [Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-27/test-portal-acceptance-pullrequest(master)/10544/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
