### PR TITLE
[Rename Classes]Lps 166967

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-166967

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@slnn regressions found:

```
  [exec] com.liferay.adaptive.media.image.internal.processor.AMImageProcessorImplTest > testProcessConfigurationWhenFileEntryIsCheckedOut FAILED
     [exec]     java.lang.NoSuchFieldException: No field on null with name _amImageScalerTracker
     [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.getField(ReflectionTestUtil.java:135)
     [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.setFieldValue(ReflectionTestUtil.java:346)
     [exec]         at com.liferay.adaptive.media.image.internal.processor.AMImageProcessorImplTest.setUp(AMImageProcessorImplTest.java:68)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-35/test-portal-acceptance-pullrequest(master)/2950/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
[exec] com.liferay.adaptive.media.image.internal.scaler.test.AMImageScalerRegistryImplTest > testAMImageScalerTrackerLogsWhenThereIsNoDefaultAMImageScaler FAILED
     [exec]     java.lang.AssertionError: [] expected:<1> but was:<0>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at com.liferay.adaptive.media.image.internal.scaler.test.AMImageScalerRegistryImplTest.testAMImageScalerTrackerLogsWhenThereIsNoDefaultAMImageScaler(AMImageScalerRegistryImplTest.java:77)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-35/test-portal-acceptance-pullrequest(master)/2950/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/adaptive-media/adaptive-media-image-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.adaptive.media.image.scaler            MAJOR      1.1.0      1.1.0      2.0.0      VERSION INCREASE REQUIRED
```
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/analytics/analytics-batch-export-import-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.analytics.batch.exportimport.model.listener MAJOR      1.1.0      1.1.0      2.0.0      VERSION INCREASE REQUIRED
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-35/test-portal-acceptance-pullrequest(master)/2950/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
Thank @catarineaguiar for catching this!

I have updated and forced push to this pull.

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
Resend in https://github.com/liferay-core-infra/liferay-portal/pull/2299 according to the comment https://github.com/liferay-core-infra/liferay-portal/pull/2249#issuecomment-1298180178

**Pull request closed without merging**
