### PR TITLE
[Remove unused reference] LPS-166421

### PR DESCRIPTION
**Pull request by JanisZhang**
This PR is to remove unused fields in `headless-commerce-admin-order-impl`. Thanks!

https://issues.liferay.com/browse/LPS-166421

### CODE REVIEW

**Comment by jaydawu** [comment]
No regressions found.

cc/ @zhangyan0701

**Comment by JanisZhang** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by dantewang** [comment]
@JanisZhang Hidden chain found:

`com.liferay.headless.commerce.admin.order.internal.dto.v1_0.converter.OrderRuleAccountDTOConverter#toDTO`
->
`com.liferay.commerce.order.rule.model.impl.COREntryRelImpl#getCOREntry`
->
`COREntryLocalServiceUtil.getCOREntry`

Please record this one.

**Pull request closed without merging**
