### PR TITLE
LPS-154814

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Updated as we discussed in https://github.com/liferay-core-infra/liferay-portal/pull/863#discussion_r888616346.
This is for ticket https://issues.liferay.com/browse/LPS-154814.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result again, please?

Thanks
Jeff

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result again, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by tinatian** [comment]
@jeffwu0724 Code looks good to me, please rebase.

Tina.

**Comment by jeffwu0724** [comment]
@tinatian Seems like other team already worked on this and get merged. Please see https://github.com/liferay-lima/liferay-portal/pull/3123. I will close this PR for now

**Pull request closed without merging**
