### PR TITLE
[Optional Reference] LPS-187417 SolrIndexingFixture

### PR DESCRIPTION
**Pull request by haydenzheng314**
Ticket: https://liferay.atlassian.net/browse/LPS-187417
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by LisztLiszt** [comment]
ci:test:search-solr

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
ci:test:stable

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
