### PR TITLE
LPD-32135 10 31

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:58341218

**Comment by dantewang** [comment]
ci:report:58343005

**Comment by dantewang** [comment]
No unique failure.

The failure in relevant is often failing in other PRs.

The failure in upgrade is flaky with low frequency. [Filtering](https://testray.liferay.com/#/project/35392/routines/45357/build/58343005/case-result/58345336/history?filter=%7B%22error%22%3A%22Element+is+checked%22%7D&filterSchema=buildResultsHistory&page=1) with `Element is checked` shows it's failing on upstream runs and other PRs.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
The SF failure is not relevant to this PR.

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
