### PR TITLE
LPS-158273

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is the preparation for ticket https://issues.liferay.com/browse/LPS-154811. In order to get rid of using too much fixup message, I will remove gson from lib, and then move it to share-dependencies first, and then upgrade the version for gson.
Thanks for checking.

cc: @antonio91dev

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
@jeffwu0724 I only see you are removing gson from lib/development, not adding it back.
But why this is here https://github.com/liferay-core-infra/liferay-portal/pull/1136/commits/e647c07d9ccb6dedc3016709c49ee372193ef98d#diff-180d8c8c4f29c992afdbf5ace714f3b3171727286ffe8f978b1ec6a74aa3061eR6912-R6925

Also if you can just remove it from lib/development without causing any issue, that means no one is using it, why do you need to add it back?

**Comment by jeffwu0724** [comment]
Hi @shuyangzhou , 

1. I used to have the commit that add a shared-dependencies for gson in this PR before, but now I moved that commit to https://github.com/liferay-core-infra/liferay-portal/pull/1143/commits/9370a3503a542c55088fea5b2717e25c48234aee. I missed updating the auto generate part after I removed this commit, and I will fix it now. Sorry for the mistakes.

2. No one is using gson in portal-impl and portal-kernel now, but still people use it in modules. Therefore, I would like to remove gson from lib first, then add gson as a shared-dependencies for the usages in modules.

Jeff

**Comment by jeffwu0724** [comment]
regenerate "ant build-lib-versions", make sure it is up to date and didn't include the shared-dependencies-gson that I used to have in this PR.

**Comment by shuyangzhou** [comment]
@jeffwu0724 the one you removed here is in lib/development, modules can not be using it, since it does not even get deployed.
Do you mean currently modules have it embedded and you want to centralize it?

**Comment by shuyangzhou** [comment]
Ok, I see your follow up pull at https://github.com/liferay-core-infra/liferay-portal/pull/1143 now

**Comment by jeffwu0724** [comment]
@shuyangzhou , yes, this is what I want to do now. Currently only modules are using gson by compileInclude, I would like to centralize it and add it to shared-dependencies, so that everyone can use it by doing compileOnly. You can also have a look at this PR https://github.com/liferay-core-infra/liferay-portal/pull/1143/commits.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/120828

**Pull request closed without merging**
