### PR TITLE
[Hibernate] LPS-148431 Remove Hibernate class usage from export-import-test-util

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian This is extracted from the big Hibernate PR.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
