### PR TITLE
[LPS-167246 MessageBus] LPS-192568 Clean up more usages from tests and osb-faro

### PR DESCRIPTION
**Pull request by dantewang**
@W2jx We missed these usages in the last PR.

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by tinatian** [comment]
ci:forward:force

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
