### PR TITLE
LPS-144081 Remove ecs

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Hey @vicnate5 , can you please help me to analyse the **ci:test** results?
I added a new commit related to wiki-service module, should I run it again?

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
will use relevant for the wiki change

**Comment by vicnate5** [comment]
@guilhermedcamacho This looks good. No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This is good to go.

Tina.

**Comment by guilhermedcamacho** [comment]
> @guilhermedcamacho This looks good. No regressions found.

Thank you for your prompt reply :+1:

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/111346

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
