### PR TITLE
[Component with its own class name as service type] LPS-194841 Refactor Interpreter component

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Related: https://liferay.atlassian.net/browse/LPS-194841

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Valmir-unicap** [comment]
ci:test:lima

**Comment by Valmir-unicap** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
@Valmir-unicap there is no reason to inline those Interpreters. Just remove the Component annotation, keep them as standalone classes.

Please resend.

**Pull request closed without merging**
