### PR TITLE
[Bug fix] LPS-190077 TikaConfigurationHelper should update the configuration object after validating the configuration value

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:document

**Comment by dantewang** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
