### PR TITLE
[TS] LPS-172099

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team,

Can you help review this PR? I decided to send this to Core Infra, since I noticed a difference in how Async destinations handled populating the CompanyThreadLocal vs the Synchronous destination.

**Notes from @noornajj:**
> https://issues.liferay.com/browse/LPS-172099
> 
> The issue here is that the CTCollection is not retrieved when a publication is scheduled to publish and there are multiple databases. Therefore, the CTCollection's status does not get updated and the publication is not published.
> 
> To fix this issue, I set the CompanyThreadLocal before retrieving the CTCollection so that the query is run on the correct database.

**Additional Findings: SynchronousDestination**
I noticed that [SynchronousDestination.java](https://github.com/liferay/liferay-portal/blob/7.4.3.57-ga57/modules/apps/portal/portal-messaging/src/main/java/com/liferay/portal/messaging/internal/SynchronousDestination.java#L45-L47) does not handle populating the CompanyThreadLocal; however, this is handled for the Async destinations:
- [ParallelDestination.java#L51-L54](https://github.com/liferay/liferay-portal/blob/7.4.3.57-ga57/modules/apps/portal/portal-messaging/src/main/java/com/liferay/portal/messaging/internal/ParallelDestination.java#L51-L54)
- [SerialDestination.java#L54-L55](https://github.com/liferay/liferay-portal/blob/7.4.3.57-ga57/modules/apps/portal/portal-messaging/src/main/java/com/liferay/portal/messaging/internal/SerialDestination.java#L54-L55)

Looking at the history, it looks like it has been this way for a long time and so I'm not sure if there is a specific reason why we don't need this for SynchronousDestination.

**Note:** I noticed there are a few other message listeners that also utilize the SynchronousDestination. 

Please let us know if you would like us to make any changes or have any questions.
Thanks!

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:liferay-online

**Comment by catarineaguiar** [comment]
ci:test:publications

**Comment by catarineaguiar** [comment]
@ericyanLr semver error:

```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/object/object-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.object.service                         MINOR      36.1.0     36.1.0     36.2.0     VERSION INCREASE REQUIRED
     [exec]     	<   class      com.liferay.object.service.ObjectRelationshipLocalServiceUtil
     [exec]     		+   method     getAllObjectRelationships(long)
     [exec]     			+   access     static
     [exec]     			+   return     java.util.List
     [exec]     	<   class      com.liferay.object.service.ObjectRelationshipLocalServiceWrapper
     [exec]     		+   method     getAllObjectRelationships(long)
     [exec]     			+   return     java.util.List
     [exec]     	<   interface  com.liferay.object.service.ObjectRelationshipLocalService
     [exec]     		+   method     getAllObjectRelationships(long)
     [exec]     			+   access     abstract
     [exec]     			+   annotated  com.liferay.portal.kernel.transaction.Transactional
     [exec]     				+   property   propagation='SUPPORTS'
     [exec]     				+   property   readOnly=true
     [exec]     			+   return     java.util.List
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 53.0.0
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-37/test-portal-acceptance-pullrequest(master)/7740/modules-semantic-versioning-jdk8/0/5/jenkins-console.txt.gz?authuser=0)

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@ericyanLr 
SynchronousDestination does not populate the threadlocals as it is going to run on the same thread as SynchronousDestination is invoked. 

Here the "companyId" in message is populated from current thread's CompanyThreadLocal (see https://github.com/liferay/liferay-portal/blob/b9491b54d517900c55acb6a75fc62266350e31fa/modules/apps/portal/portal-messaging/src/main/java/com/liferay/portal/messaging/internal/DefaultMessageBus.java#L91), based on this, the fix does not make sense to me, could you please take a deep look at why this the company thread local when the listener is invoked is not what you want?

Tina

**Comment by ericyanLr** [comment]
Hi @tinatian ,

**Regarding:**
> could you please take a deep look at why this the company thread local when the listener is invoked is not what you want?

From my understanding, this is because the listener is being invoked via a scheduled job:
[PublishScheduler.java#L191-L197](https://github.com/liferay/liferay-portal/blob/7.4.3.57-ga57/modules/apps/change-tracking/change-tracking-web/src/main/java/com/liferay/change/tracking/web/internal/scheduler/PublishScheduler.java#L191-L197)

**Comment by ericyanLr** [comment]
Hi @tinatian ,

**Regarding:**
> Here the "companyId" in message is populated from current thread's CompanyThreadLocal (see https://github.com/liferay/liferay-portal/blob/b9491b54d517900c55acb6a75fc62266350e31fa/modules/apps/portal/portal-messaging/src/main/java/com/liferay/portal/messaging/internal/DefaultMessageBus.java#L91), based on this, the fix does not make sense to me

That's a good point.. I took closer look and found out that the Message constructor actually sets the companyId:
[Message.java#L47](https://github.com/liferay/liferay-portal/blob/7.4.3.57-ga57/portal-kernel/src/com/liferay/portal/kernel/messaging/Message.java#L47)

And so, the companyId is provided in the Message when the object first gets created:
[PublishScheduler.java#L186](https://github.com/liferay/liferay-portal/blob/7.4.3.57-ga57/modules/apps/change-tracking/change-tracking-web/src/main/java/com/liferay/change/tracking/web/internal/scheduler/PublishScheduler.java#L186)

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2978

**Pull request closed without merging**
