### PR TITLE
[Remove unused field] LPS-199422

### PR DESCRIPTION
**Pull request by JanisZhang**
Remove unused reference fields in class `EditAccountEntryMVCActionCommand`, `AMJournalArticleExportImportContentProcessor`, `AMImageConfigurationHelperImpl`, and `AnalyticsDXPEntityBatchExporterResourceImpl`. Thanks
https://liferay.atlassian.net/browse/LPS-199422

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@JanisZhang 
Regression found in 

com.liferay.adaptive.media.journal.web.internal.exportimport.content.processor.AMJournalArticleExportImportContentProcessorTest
```
 [exec] com.liferay.adaptive.media.journal.web.internal.exportimport.content.processor.AMJournalArticleExportImportContentProcessorTest > testImportCallsBothExportImportContentProcessors FAILED
[beanshell]      [exec]     java.lang.NoSuchFieldException: No field on null with name _portal
[beanshell]      [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.getField(ReflectionTestUtil.java:126)
[beanshell]      [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.setFieldValue(ReflectionTestUtil.java:337)
[beanshell]      [exec]         at com.liferay.adaptive.media.journal.web.internal.exportimport.content.processor.AMJournalArticleExportImportContentProcessorTest.setUp(AMJournalArticleExportImportContentProcessorTest.java:53)
[beanshell]      [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell]      [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[beanshell]      [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell]      [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell]      [exec]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[beanshell]      [exec]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[beanshell]      [exec]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[beanshell]      [exec]         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
[beanshell]      [exec]         at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]         at org.junit.rules.RunRules.evaluate(RunRules.java:20)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-27/test-portal-acceptance-pullrequest(master)/10388/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
