### PR TITLE
[Component with its own class name as service type] LPS-198805 Refactor Controller components part I

### PR DESCRIPTION
**Pull request by MrJohn1911**
Previous pull: https://github.com/liferay-core-infra/liferay-portal/pull/5998

Ticket: https://liferay.atlassian.net/browse/LPS-198805

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud-acceptance

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud-acceptance

**Comment by Kvale1733** [comment]
@ViniLopes20 can you help look at these analytics results. Thanks.

**Comment by ViniLopes20** [comment]
Hey @MrJohn1911, Our tests are not working because of a modification made by another team in the master branch that affected us. I downloaded your PR to check if the modifications were affecting AC and noticed this:

I found an error here that is the same one I put in your PR last time when we ran the tests. When I build the AC here and access the AC, after logging in there is a 404 error in the UI which must be caused by this error there. Here's the error in Faro:

`2023-11-14 18:26:34.939 ERROR [Portal Dependency Manager Component Executor--1][LogService:56] [Portal Dependency Manager Component Executor--1] Invocation of 'addService' failed.
org.apache.cxf.service.factory.ServiceConstructionException: null
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:220) ~[?:?]
	at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator._registerApplication(CXFJaxRsServiceRegistrator.java:126) ~[?:?]
	at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator._registerApplications(CXFJaxRsServiceRegistrator.java:136) ~[?:?]
	at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator._rewire(CXFJaxRsServiceRegistrator.java:188) ~[?:?]
	at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator._addService(CXFJaxRsServiceRegistrator.java:96) ~[?:?]
	at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator._swapClassLoader(CXFJaxRsServiceRegistrator.java:213) ~[?:?]
	at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator.addService(CXFJaxRsServiceRegistrator.java:54) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.felix.dm.impl.InvocationUtil.invokeMethod(InvocationUtil.java:230) ~[bundleFile:?]
	at org.apache.felix.dm.impl.InvocationUtil.invokeCallbackMethod(InvocationUtil.java:181) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.invokeCallback(ComponentImpl.java:665) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ServiceDependencyImpl.invoke(ServiceDependencyImpl.java:517) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ServiceDependencyImpl.invokeCallback(ServiceDependencyImpl.java:327) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.invokeCallback(ComponentImpl.java:1734) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.invokeAddOptionalDependencies(ComponentImpl.java:1671) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.performTransition(ComponentImpl.java:1234) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.handleChange(ComponentImpl.java:1166) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.lambda$start$2(ComponentImpl.java:502) ~[bundleFile:?]
	at org.apache.felix.dm.impl.DispatchExecutor.runTask(DispatchExecutor.java:182) [bundleFile:?]
	at org.apache.felix.dm.impl.DispatchExecutor.run(DispatchExecutor.java:165) [bundleFile:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.apache.cxf.service.factory.ServiceConstructionException: No resource classes found
	at org.apache.cxf.jaxrs.AbstractJAXRSFactoryBean.checkResources(AbstractJAXRSFactoryBean.java:318) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:156) ~[?:?]`

**Pull request closed without merging**
