### PR TITLE
[Component with its own class name as service type] LPS-193512 Refactor Cache classes from portal-template module

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-193512

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:stop

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Comment by shuyangzhou** [comment]
@MrJohn1911 Please inline XYZTemplateResourceCache creation into their XYZManager.

**Pull request closed without merging**
