### PR TITLE
[Components with more than 1 service] LPS-193378 Refactor *ResourceImpl components with NestedFieldSupport service

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-193378

### CODE REVIEW

**Comment by MrJohn1911** [comment]
Hi @GinsonRen, could you run the performance tests in this pull? I need to know if my changes causes any decrease in the portal startup. 

Thanks in advance!

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by GinsonRen** [comment]
@111Anna Please run startup diff on this pr. Thanks.

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by 111Anna** [comment]
Hi @MrJohn1911 @GinsonRen , I ran the PR on CE and DXP,  the test results are normal.

CE:
Portal Version |GitId | Average Startup (ms) | % | Average Shutdown (ms) | % | Open File |Thread Create |Open Prepared Statement |Open SQL|Open service tracker|Open bundle tracker
-- | -- | -- | -- | -- | -- | -- | -- | -- | --|--|--
Baseline | 9c4968c53 |19164.6 | - | 2592.6 | - | 1480 | 95 | 120 | 855|5518|32
Baseline + PR-5263 | - | 19060.3 | 0.03% | 2614.3 | -0.07% |  1480|  97| 120 | 855|5518|33

DXP:
Portal Version | GitId | Average Startup (ms) | % | Average Shutdown (ms) | % | Open File |Thread Create |Open Prepared Statement |Open SQL|Open service tracker|Open bundle tracker
-- | -- | -- | -- | -- | -- | -- | -- | -- | --|--|--
Baseline | 9c4968c53 |20531.6| - | 3087.3| - | 1604 | 96 | 126 | 931|5962|33
Baseline + PR-5263 | - | 20483.6 | 0.23% | 3021.6| 2.12% | 1604|96 | 126 |931 |5962|33

**Comment by rafaprax** [comment]
Hey @tinatian, this pr is ready for your review. Thx

//cc @shuyangzhou

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139385

**Pull request closed without merging**
