### PR TITLE
LPD-43937 Remove tc Server support

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:environments

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:environments

**Comment by dantewang** [comment]
ci:test:environments

**Comment by dantewang** [comment]
ci:report:89007593

**Comment by dantewang** [comment]
ci:test:environments

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:89926684

**Comment by dantewang** [comment]
ci:test:environments

**Comment by dantewang** [comment]
ci:report:90121321

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/156970

**Pull request closed without merging**
