### PR TITLE
LPS-149460 Move petra-model-adapter to apps/portal-utilities

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,

Main Task: [LPS-147928 Remove petra jar from modules/apps](https://issues.liferay.com/browse/LPS-147928)
Sub Task: [LPS-149460 Move petra-model-adapter to apps/portal-utilities](https://issues.liferay.com/browse/LPS-149460)

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
changed to use SF BNDExportsCheck prop to allow export

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by kyle-miho** [comment]
@julschong failure shoudl be unrelated

**Comment by julschong** [comment]
changing package name to remove the .util package at the end. will resend

**Pull request closed without merging**
