### PR TITLE
[Method References 2] LPS-169905 Convert method reference to ServiceTrackerMap in classes AccountRoleRequestHelper

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(2/10 9:06)

**Comment by tinatian** [comment]
@W2jx  1. This is not a "Rename" https://github.com/liferay-core-infra/liferay-portal/pull/3411/commits/f36bd831846bbad8889ed50528340d24f504fdf7, rename usually means you do not change anything, just rename. Please make sure your changes and commit message consistent and describe the changes you made.
2. You can not just use sorted map in the impl of getPersonalMenuEntries(), as not everyone needs it to be sorted, only RolesAdminPortlet requires the order. You are going to slow down everyone just for one person, this is not acceptable.
3. Currently only one usage of getGroupedPersonalMenuEntries(), does it need to be an API? usually do not expect you have a strong reason to do.

FYI @dantewang 

Tina.

**Comment by dantewang** [comment]
@tinatian Discussed the situation for this with Jiaxu.

For 2, it's weird that one place in this doesn't need a sorted list but another place needs a sorted list, and both can be displayed on the same JSP. For this, I asked Jiaxu to contact Pei-Jung Lan to confirm.

**Pull request closed without merging**
