### PR TITLE
LPS-145541 Remove xmpcore.jar

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by guilhermedcamacho** [comment]
Hey @vicnate5 , please help me scan test results. Thanks!

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
This PR looks good, Thanks!

**Comment by guilhermedcamacho** [comment]
Hey @shuyangzhou, this PR is ready for your review. Thanks!

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
