### PR TITLE
[TS] LPS-205900 getLocalizedFriendlyURL method was generating an invalid URL that contained multiple language IDs in it in some cases

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-205900](https://liferay.atlassian.net/browse/LPS-205900)

### CODE REVIEW

**Comment by ericyanLr** [comment]
Hi @mbowerman ,

I took a closer look at the issue and was able to narrow down that this is actually a regression bug that was introduced by: [LPS-131068](https://liferay.atlassian.net/browse/LPS-131068)

Can you help look into this further, in case it leads to a different solution?

I'll close out this PR for now, feel free to re-open if needed.

**Comment by mbowerman** [comment]
Hello @ericyanLr,

Thanks for tracking down the ticket that caused the regression. My fix on this ticket effectively modifies the second `if` condition that was added in https://github.com/brianchandotcom/liferay-portal/commit/385cd2f7c0e37c958b6509c3238f539e54f135a8..

In https://github.com/brianchandotcom/liferay-portal/commit/385cd2f7c0e37c958b6509c3238f539e54f135a8, we switched to using the URI of the original request (before the language ID was stripped from it) in some cases. So, we added that `if` condition at the bottom to handle the case where the original request already contained the language ID that we decided to use.

The problem is, that this `if` condition was too broad. We were only checking if the URI didn't contain the specific language ID that we would use to render the page. However, it's possible that the original URI could have contained a different language ID in it. My fix can simply be thought of as changing this line (added by https://github.com/brianchandotcom/liferay-portal/commit/385cd2f7c0e37c958b6509c3238f539e54f135a8):

```
if (!requestURI.contains(i18nPath)) {
```

to this:

```
if (!requestURI.contains(i18nPath) && !requestURI.contains(anyOtherLanguageId)) {
```
So, to me it makes sense that this would be an appropriate solution, because it adjusts the solution provided in [LPS-131068](https://liferay.atlassian.net/browse/LPS-131068) by modifying an `if` condition that it added to handle an unconsidered case.

Of course, the `!requestURI.contains(anyOtherLanguageId)` is "pseudocode", and the reality is that it can't easily be one-lined like that, hence why it looks a bit more complicated.

Let me know if I misunderstood your comments.

**Comment by mbowerman** [comment]
ci:reopen

**Comment by ericyanLr** [comment]
Hi @mbowerman ,

The challenging part for me is trying to rationalize whether the mentioned change in: https://github.com/brianchandotcom/liferay-portal/commit/385cd2f7c0e37c958b6509c3238f539e54f135a8 is the correct change or not.

Looking at the commit history, I noticed the commit that originally introduced this method, provides this commit mesage:

> LPS-35438 getRedirect must specify whether we need to send redirect or doing set forward is enough. There are some cases where we need to force the send redirect because we need to redirect the user to the right layout friendly url in case the locale of the request and the locale of the friendly url don't match.
> 
> The code of PortalImpl.getLocalizedFriendlyURL() is derived from the one of I18nFilter, but we couldn't find a way to reuse it due to the differences.
- Reference: https://github.com/liferay/liferay-portal/commit/c6946a0fa9a4bf06b9106b0f03453285bbcee01c

The part that caught my attention is the mention that: 
> **The code of PortalImpl.getLocalizedFriendlyURL() is derived from the one of I18nFilter.**

And if we take a look at I18nFilter, it looks like it contains logic that handles this use-case, but approaches it differently
- Instead of utilizing the original request's URI, it continues to use the current request URI
- The approach it takes instead, is to simply strip out the group friendly URL from the request URI.
- Reference: https://github.com/liferay/liferay-portal/blob/7.4.3.110-ga110/modules/apps/portal/portal-i18n-filter/src/main/java/com/liferay/portal/i18n/filter/internal/I18nFilter.java#L159-L203

**Question**
Would applying the approach from I18nFilter to modify the request URI by removing the group friendly URL, be a better approach then the change introduced by: https://github.com/brianchandotcom/liferay-portal/commit/385cd2f7c0e37c958b6509c3238f539e54f135a8?

From my understanding, this should still handle the use-case for https://liferay.atlassian.net/browse/LPS-136518 and as a result, avoid introducing the behavior described in this regression bug ticket.

Can you help take a look to see if my concerns make sense or if I'm missing something?

Thanks!

**Comment by tinatian** [comment]
@mbowerman Please see @ericyanLr 's comment and add test to cover your change. I am going to close this pull, and please reopen or resend.

Thanks.
Tina.

**Comment by mbowerman** [comment]
Hello @ericyanLr,

> Would applying the approach from I18nFilter to modify the request URI by removing the group friendly URL, be a better approach then the change introduced by: https://github.com/brianchandotcom/liferay-portal/commit/385cd2f7c0e37c958b6509c3238f539e54f135a8?

This seems like a worse approach to me. Always removing the group friendly URL no matter what would prevent us from being able to preserve the URL format. For example, this approach would cause a URL of the form `http://localhost:8080/web/guest/home` to redirect to `http://localhost:8080/home`, which might be considered an unexpected behavior.

I wasn't able to find out why we strip the group friendly URL from the `I18nFilter`, as the code to do so was added so long ago that it is from [the commit](https://github.com/liferay/liferay-portal/commit/6787514ed866631270605cc497718a56810bda8b) where we initially added the `I18Filter` class. I also wasn't able to figure out what the `I18nFilter` was even meant to be doing, because the breakpoint wasn't even reached when I added a breakpoint to the `processFilter` method and tried to visit some pages. Do we even have the `I18nFilter` configured to be part of the filter chain by default anymore?

Regardless, I think that it would be best to be careful to preserve the existing behavior as closely as possible in cases where it appears to make sense or be correct, because otherwise, we risk giving customers a nasty surprise if they were dependent on the existing behavior of preserving the URL format. So for that reason, I would like to continue taking the original request URI into consideration when running the method, so that we can preserve the URL format with regards to whether `/[servletMapping]/[friendlyURL]` is included in the request or not.

**Comment by mbowerman** [comment]
Hello @ericyanLr and @tinatian,

Please see my response above. I do not believe that we should simply ignore the original request URI in this method. We need to use it in order to be able to preserve the URL format accurately.

I have also added an integration test for this. Please take a look.

**Comment by mbowerman** [comment]
ci:reopen

**Comment by mbowerman** [comment]
I've forwarded the pull request to https://github.com/liferay-core-infra/liferay-portal/pull/6600 since it seems that it cannot be reopened.

**Pull request closed without merging**
