### PR TITLE
LPS-149982 org.jboss.modules.ModuleNotFoundException: com.liferay.portal error if you configure Liferay on JBoss or Wildfly using the official Liferay documentation

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
If you follow the official Liferay documentation to install Liferay on JBoss or Wildfly:
   - https://learn.liferay.com/dxp/latest/en/installation-and-upgrades/installing-liferay/installing-liferay-on-an-application-server/installing-on-wildfly.html
   - https://learn.liferay.com/dxp/latest/en/installation-and-upgrades/installing-liferay/installing-liferay-on-an-application-server/installing-on-jboss-eap.html

You will get the error:
```
09:33:39,718 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-3) MSC000001: Failed to start service jboss.module.service."deployment.ROOT.war".main: org.jboss.msc.service.StartException in service jboss.module.service."deployment.ROOT.war".main: WFLYSRV0179: Failed to load module: deployment.ROOT.war
        at org.jboss.as.server@15.0.6.Final-redhat-00003//org.jboss.as.server.moduleservice.ModuleLoadService.start(ModuleLoadService.java:116)
        at org.jboss.msc@1.4.12.Final-redhat-00001//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
        at org.jboss.msc@1.4.12.Final-redhat-00001//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
        at org.jboss.msc@1.4.12.Final-redhat-00001//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
        at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.4.0.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.jboss.modules.ModuleNotFoundException: com.liferay.portal
        at org.jboss.modules.Module.addPaths(Module.java:1288)
        at org.jboss.modules.Module.link(Module.java:1644)
        at org.jboss.modules.Module.relinkIfNecessary(Module.java:1672)
        at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:303)
        at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:287)
        at org.jboss.as.server@15.0.6.Final-redhat-00003//org.jboss.as.server.moduleservice.ModuleLoadService.start(ModuleLoadService.java:93)
        ... 8 more
```

This error is caused because the out-of-the-box Liferay `WEB-INF/jboss-deployment-structure.xml` file has a dependency with the "com.liferay.portal" module that is not longer necessary as of DXP 7.4

The error is not reproduced in the CI tests because our tests are setting an empty "com.liferay.portal" module when configuring the test application server.

To avoid this, I am removing the com.liferay.portal dependency from the WEB-INF/jboss-deployment-structure.xml.

I am also removing the module.xml file and all its references in the ant build files as the module is not longer necessary anymore

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
Hi all, 
About the CI error related to **portal-license-smoke-jdk8/0**:
```
/opt/dev/projects/github/liferay-release-tool-ee/ext/7.4.x/build-release-license.xml:327: Replace: source file /opt/dev/projects/github/liferay-portal/tools/servers/jboss/modules/module.xml doesn't exist
 ```
Is caused because there is a external reference to the removed `module.xml` file in the **liferay-release-tool-ee** repository

I have no access to that github repository, so I cannot send a PR to fix it.

But I was able to check the code connecting to the LAX mirror using diamond bar VPN: http://mirrors.lax.liferay.com/github.com/liferay/liferay-release-tool-ee/ext/7.4.x/

After reviewing the **build-release-license.xml** file we have just to remove for 7.4 version only this fragment:
```
				<replace encoding="UTF-8" file="${portal.dir}/tools/servers/jboss/modules/module.xml">
					<replacetoken><![CDATA[<resource-root path="mysql.jar" />]]></replacetoken>
					<replacevalue></replacevalue>
				</replace>
```
This code is trying to remove the reference to the mysql.jar file inside the module.xml, but:
  - the code that adds this mysql.jar reference is already removed in this pull request see commit https://github.com/liferay-core-infra/liferay-portal/pull/491/commits/e6c148c87a54787f3976b2cde2b005af5b444d4a
  - the file module.xml is removed in this other commit https://github.com/liferay-core-infra/liferay-portal/pull/491/commits/cda872ce12db8a129cb0aff9e57d0667bdc9fa16

so this code fragment of build-release-license.xml is not longer necessary.

Can anybody from the core team send this change to that github repository? Is it possible to request access to that repository?

Thank you,
Jorge

**Comment by vicnate5** [comment]
ci:test:app-servers

**Comment by jorgediaz-lr** [comment]
Hi all,

Do you have any update about this PR?

Thank you

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian Only regressions found is the one identified in https://github.com/liferay-core-infra/liferay-portal/pull/491#issuecomment-1076113073. 

Resent with fix: https://github.com/liferay-core-infra/liferay-portal/pull/516

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
