### PR TITLE
[Method References 2] LPS-170888 Remove method reference in class InfoItemFieldReaderRegistryImpl(module info-impl)

### PR DESCRIPTION
**Pull request by W2jx**
I have reordered commits.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/2709

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(12/21 17:05)

**Comment by W2jx** [comment]
Force-Push is just to rebase and resolve the conflict about file `modules/apps/info/info-api/bnd.bnd`

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Semantic versioning issue:
```
     [exec] > Task :apps:info:info-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.info.item.field.reader                 MAJOR      3.0.0      3.0.0      4.0.0      VERSION INCREASE REQUIRED
     [exec] 	-   interface  com.liferay.info.item.field.reader.InfoItemFieldReaderRegistry
     [exec] 		-   access     abstract
     [exec] 		-   method     getInfoItemFieldReaders(java.lang.String)
     [exec] 			-   access     abstract
     [exec] 			-   return     java.util.List
     [exec] 		-   annotated  org.osgi.annotation.versioning.ProviderType
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.info.api-26.0.0.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.info.api/25.0.0/91dd3648203f25d5bd8faff504d873fdaf01f4d0/com.liferay.info.api-25.0.0.jar
```
Full console: https://testray.liferay.com/reports/production/logs/2022-12/test-1-29/test-portal-acceptance-pullrequest(master)/5919/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by tinatian** [comment]
@W2jx For this commit https://github.com/liferay-core-infra/liferay-portal/pull/2799/commits/a9745aec8a4c37e193e4f5f1b2fdee00b7ff9881, it was added on purpose, please see [bfc5bfbeefdcf07abdf11308f562e87cc92a07d0](https://github.com/liferay-core-infra/liferay-portal/commit/bfc5bfbeefdcf07abdf11308f562e87cc92a07d0)

**Pull request closed without merging**
