### PR TITLE
[Remove immediate=true usgae core-infrastructure-3 part 2]Lps 169260 12 26

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-169260

My previous pull didn't include `PortalInstancesConfigurationFactory` and `JSONStorageUpgradeStepFactoryImpl`, since I didn't see any usages except tests, I prepare do it later. However, we can remove immdiate=true simply in this pull (@yuhai  has dit it on `PortalInstancesConfigurationFactory` in https://github.com/liferay-core-infra/liferay-portal/pull/2793 )and then revisit them later to see if they are still needed.

### CODE REVIEW

**Comment by slnn** [comment]
ci:test

**Comment by slnn** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by yuhai — APPROVED** [review]

**Comment by yuhai** [comment]
@tinatian, @dantewang, the codes look good to me.

**Comment by tinatian** [comment]
@slnn For this commit message "LPS-169260 Remove "immediate = true" from module portal-instances. For PortalInstancesConfigurationFactory, we can't let the service property for empty to imply as immediate. Since PortalInstancesConfigurationFactoryTest needs to get the service by component name."

You should NEVER make any decision on production code because of a test did not work. Please do what you need to do on production code, then figure out a way to fix the text.

Please resend.

Tina

**Comment by slnn** [comment]
Hi @tinatian 

For the change of `PortalInstancesConfigurationFactory` has been merged in https://issues.liferay.com/browse/LPS-171288, I rebase and resend the left part of this pull in https://github.com/liferay-core-infra/liferay-portal/pull/2876

**Pull request closed without merging**
