### PR TITLE
[Remove Blocking usages]LPS-187901 portal-kernel | WorkflowEngineManagerUtil 

### PR DESCRIPTION
**Pull request by JanisZhang**
previous: https://github.com/liferay-core-infra/liferay-portal/pull/5109

Hi Dante, this PR is to remove the WorkflowEngineManager interface and its impl and util, as this interface has no purpose in the current workflow application. please see https://liferay.atlassian.net/browse/PTR-4161

Thanks!

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by JanisZhang** [comment]
The stable failure will be fixed by https://github.com/brianchandotcom/liferay-portal/pull/138872. I will re-run the test until the fix is merged into master.

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
For the SF failure tied to the latest UI libraries, I'll forward this PR to the workflow team for resolution as I lack knowledge of this part to know which is the appropriate solution. @dantewang

**Comment by JanisZhang** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by JanisZhang** [comment]
See https://github.com/liferay-workflow/liferay-portal/pull/976.

**Pull request closed without merging**
