### PR TITLE
LPS-146894 Move jazzy.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@koor4356 can you check this one?

**Comment by koor4356** [comment]
Okay, thanks!

**Comment by koor4356** [comment]
@rafaprax 
This looks good.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
