### PR TITLE
LPS-171146 partial revert

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 I believe the reverted changes will cause issue, but it passed ci test at https://github.com/liferay-core-infra/liferay-portal/pull/2812, could you please check if we have test covered this part of logic?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian What is the regression?

**Comment by vicnate5** [comment]
ci:test:workflow

**Comment by vicnate5** [comment]
No regressions identified in relevant or workflow suites.

**Comment by tinatian** [comment]
@vicnate5 I figured this out by code analyzing, I guess there is no test covered this part, thus you won't see a regression with/without this change.

**Pull request closed without merging**
