### PR TITLE
LPS-145600

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian, @shuyangzhou ,

Resend. Combine three commit into one with the correct commit message. See (https://github.com/liferay-core-infra/liferay-portal/pull/214).

I have removed unused properties "multi.value.map.", which included
"multi.value.map.com.liferay.portal.convert.ConvertPermissionAlgorithm.convertResourcePermission" and "multi.value.map.com.liferay.portal.convert.ConvertPermissionAlgorithm.convertRoles", and updated to propskeys.java, propsvalues.java and verifyproperties.java.

It was added as a comment in commit 679a007, see LPS-16204.
Renamed to the current name in commit 438c68b, see LPS-16204.
It was used by the prefix "MULTI_VALUE_MAP" by "multi.value.map." in commit 679a007, see LPS-16204.
It was finally deleted the use in "ConvertPermissionAlgorithm.java" based on commit d7c844a, see LPS-26306
Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:stable

**Comment by tinatian** [comment]
@jeffwu0724 Code looks good to me, please put this into your list. I am going to close this pull for now.

Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
