### PR TITLE
[OrderByComparator] LPD-26157 dxp new pattern

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:report:19939035

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@titokenzo I'm re-running relevant, but it seems one of the unique failures reported in https://github.com/liferay-core-infra/liferay-portal/pull/7173#issuecomment-2180156543 is related to this PR's change?

**Comment by dantewang** [comment]
ci:report:23063139

**Comment by titokenzo** [comment]
resent with corrections to https://github.com/liferay-core-infra/liferay-portal/pull/7192

**Pull request closed without merging**
