### PR TITLE
[Company xml log] LPS-175340 

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the previous pr is https://github.com/liferay-core-infra/liferay-portal/pull/3437.

Follow with your provided way from https://github.com/liferay-core-infra/liferay-portal/pull/3437#issuecomment-1427335112. I added xml layout support internally.

In addition, one appender only have a layout. In the PluginElementVisitor, the code `this.conversionType.isArray()` is from when building appender, inject the field org.apache.logging.log4j.core.appender.AbstractAppender$Builder.layout, it firstly get the field type and set it to conversionType(**PluginBuilder#injectFields()** {`setConversionType(field.getType()))`, and then invoke `visit(configuration, node, event, log)` it will invoke **PluginElementVisitor#visit()**}, and then use this to judge if conversionType isArray. Layout.class type is not array.

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@yuhai rebase please.

regression found:
```
   [exec] com.liferay.portal.log4j.internal.Log4jConfigUtilTest > testGetCompanyLogDirectoryWithCompanyLogDisabled FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.portal.log4j.internal.CompanyLogRoutingAppender.getCompanyLogDirectory(CompanyLogRoutingAppender.java:85)
     [exec]         at com.liferay.portal.log4j.internal.CentralizedConfiguration.getCompanyLogDirectory(CentralizedConfiguration.java:79)
     [exec]         at com.liferay.portal.log4j.internal.Log4jConfigUtil.getCompanyLogDirectory(Log4jConfigUtil.java:151)
     [exec]         at com.liferay.portal.log4j.internal.Log4jConfigUtilTest._testGetCompanyLogDirectory(Log4jConfigUtilTest.java:603)
     [exec]         at com.liferay.portal.log4j.internal.Log4jConfigUtilTest.testGetCompanyLogDirectoryWithCompanyLogDisabled(Log4jConfigUtilTest.java:271)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-02/test-1-29/test-portal-acceptance-pullrequest(master)/6389/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
@da

> [catarineaguiar](/catarineaguiar)

@catarineaguiar, I just fixed the test error and rebase issue. Run ci test again. Thanks.

**Comment by dantewang** [comment]
@yuhai You say that the `Layout` is not an array, so we can't make it support 2 layout definitions in one appender. However, as you said, it checks `conversionType.isArray()`. The `conversionType` is a `Class<?>`, so if we modify the `Layout` to `Layout[]`, the `conversionType` should be array, right?

Currently our `Builder` extends `AbstractAppender.Builder`, and I'm not sure whether we can override the `Layout` field; but could you try it?

**Comment by yuhai** [comment]
> @yuhai You say that the `Layout` is not an array, so we can't make it support 2 layout definitions in one appender. However, as you said, it checks `conversionType.isArray()`. The `conversionType` is a `Class<?>`, so if we modify the `Layout` to `Layout[]`, the `conversionType` should be array, right?
> 
> Currently our `Builder` extends `AbstractAppender.Builder`, and I'm not sure whether we can override the `Layout` field; but could you try it?

@dantewang, If define the below field in CompanyLogRoutingAppender.Builder class,` _layouts` can get two layouts. If doing this, `AbstractAppender.Builder#getLayout()` will be null. 
```
@PluginElement("Layout")
private Layout[] _layouts;
```

Do you want me to use this way to initialize layouts? And then when create Appenders for one company, use _layouts[0] as COMPANY_LOG_ROUTING_TEXT_FILE appender layout, use _layouts[1] as COMPANY_LOG_ROUTING_XML_FILE appender layout.
If using this way, we can't use one property to control the XML output, it will depend on definition in portal-log4j.xml. Or in the property description to statement the requirement. 

Do I understand right?

**Comment by dantewang** [comment]
@yuhai Yes, with this, we don't need to add a new portal property.

On the other hand, you should only determine the file extension based on the layout type; so you shouldn't assume that layouts[0] is the pattern layout and layout[1] is the xml layout. Is there any way to expand the attribute in the layout definition in the xml file? If not, let's determine the extension based on type for now.

**Comment by dantewang** [comment]
@yuhai Closing this pull, please resend, thanks!

cc @tinatian

**Pull request closed without merging**
