### PR TITLE
[Reference cleanup]LPS-162160

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to convert method references to field references in dynamic-data-mapping-web. Thanks!
https://issues.liferay.com/browse/LPS-162160

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @catarineaguiar, Could you please help to scan the test results after their finished? Thank you.

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:reevaluate:1387401_3433

**Comment by dantewang** [comment]
ci:test:relevant

**Pull request closed without merging**
