### PR TITLE
LPD-25522 Adapt tests using hard-coded test password in Locale component

### PR DESCRIPTION
**Pull request by MrJohn1911**
Tested here: https://github.com/MrJohn1911/liferay-portal/pull/86

The tests did't fail / didn't had any unique failure.

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:2568265455

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
