### PR TITLE
[Disable auto import default references]LPS 161869

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-161869

/cc @dantewang @tinatian

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan the test results when they are finished?

Thanks
Lily

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Review by dantewang — APPROVED** [review]
@tinatian I asked Lily and Hai to send this part first so that it's clearer when we look into circular references.

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122528

**Pull request closed without merging**
