### PR TITLE
[Remove Stream/Optional usage] LPS-178725 modules: headless-commerce-admin-shipment-impl, headless-commerce-admin-site-setting-impl, headless-commerce-delivery-cart-impl, headless-commerce-delivery-catalog-impl

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-178725

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
ci:test:commerce

**Comment by JanisZhang** [comment]
ci:test:commerce

**Comment by JanisZhang** [comment]
ci:test:headless

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@JanisZhang Not sure why, but I got rebase conflict on my local...

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:headless

**Comment by JanisZhang** [comment]
ci:test:commerce

**Comment by JanisZhang** [comment]
force-pushed.

**Comment by dantewang** [comment]
@JanisZhang The Stream changes look good to me. However, the last commit looks a bit weird, and since it has something to do with Commerce business logic, please send it to Commerce team for extra review, thanks!

**Comment by dantewang** [comment]
@JanisZhang You can wait for CI to finish and QA to check the results before sending to Commerce.

**Comment by JanisZhang** [comment]
@dantewang sure, thanks!

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by JanisZhang** [comment]
sent to the commerce team https://github.com/liferay-commerce/liferay-portal/pull/3555 for extra review. cc @dantewang

**Pull request closed without merging**
