### PR TITLE
[Replace Non-Blocking Usage] LPS-199020 Replace non-blocking ServiceProxyFactory usages in MailTemplateFactoryUtil 

### PR DESCRIPTION
**Pull request by haydenzheng314**
Ticket: https://liferay.atlassian.net/browse/LPS-199020
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@LisztLiszt No regressions found.

**Pull request closed without merging**
