### PR TITLE
LPD-42809 It's not possible to start the portal with a clean environment using HSQLDB

### PR DESCRIPTION
**Pull request by izaera**
(comes from https://github.com/liferay-frontend/liferay-portal/pull/4619)

Hi team :wave: 

This is the continuation of https://github.com/liferay-core-infra/liferay-portal/pull/7725.

I've added 5 more commits that totally rework the `JSImportMapsCache` following the recommendations at https://github.com/liferay-core-infra/liferay-portal/pull/7725#issuecomment-2537248970.

We've basically got rid of the need to use `synchronized` code (we now use concurrency) and the need to invalidate the cache explicitly (it's now garbage collected).

From the 5 new commits there's one that I wasn't unsure whether it made sense to keep it or we prefer to remove it (the last one). The description of the commit explains what are our alternatives. Please pay special attention to the synchronization in case we leave that commit because I'm using `synchronized` for writes and concurrency for reads. I couldn't think of a better way to do it and I have to admit that I have made so many changes to this PR that is difficult for me to reason about it aseptically (meaning a review from outsiders may suggest better ideas).

Once again, thanks for the review :raised_hands:

### CODE REVIEW

**Comment by tinatian** [comment]
@izaera 
For the last commit, I do not think it is necessary as you are actually eagerly putting into an empty map when you read, doing this eager clean up will make you keep adding and removing:
_scopedImportMapsValuesMap.putIfAbsent(
				companyId, new ConcurrentHashMap<>());
				
Also, about how to clean up the map inside a map, please use compute rather than synchronized.

As you have removed the company model listener usage, the original issue should be fixed and we will verify that. Once the verification passed, core infra is fine, you can go through your normal review process for the details.

@victorhcunha Please verify startup test result.

**Comment by slnn** [comment]
Hi @tinatian 

Run startup test on this pull based on master: https://github.com/liferay/liferay-portal/commit/1d1009bc5a1f8b027c53e140f147d9a272f71af8, everything works well, portal can startup after removing the data folder of bundle.

Upload test result in 
[startup-normal-LPD-42809-pr-7752-8b69ac5e44777283a1fafae5f069ed717614d1c8-2024-12-19-12-40-34.zip](https://github.com/user-attachments/files/18192754/startup-normal-LPD-42809-pr-7752-8b69ac5e44777283a1fafae5f069ed717614d1c8-2024-12-19-12-40-34.zip)

**Comment by izaera** [comment]
> Also, about how to clean up the map inside a map, please use compute rather than synchronized.

Ah, true. Forgot that existed... :+1: 

> As you have removed the company model listener usage, the original issue should be fixed and we will verify that. Once the verification passed, core infra is fine, you can go through your normal review process for the details.

As per https://github.com/liferay-core-infra/liferay-portal/pull/7752#issuecomment-2552796012 I will close this PR and continue the PR forward in our `liferay-frontend` user.

Thx

**Comment by izaera** [comment]
continues at https://github.com/liferay-frontend/liferay-portal/pull/4627

**Pull request closed without merging**
