### PR TITLE
[Components with more than 1 service] LPS-204722 Refactor PLOEntryModelListener component

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://liferay.atlassian.net/browse/LPS-204722

Original Comment:
ticket: https://liferay.atlassian.net/browse/LPS-204722
test made using same case as: https://liferay.atlassian.net/browse/LPS-185988

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by regiCesar21** [comment]
ci:test:stable

**Comment by regiCesar21** [comment]
ci:test:relevant

**Comment by regiCesar21** [comment]
ci:test:clustering

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
ci:report:2488064466

**Comment by tinatian** [comment]
ci:report:2488070295

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6727

**Comment by tinatian** [comment]
@regiCesar21 Why you marked this as QA passed when the report of ci:test:clustering having unique failures?

**Comment by regiCesar21** [comment]
The CSV report on Jan 15th was  showing that all of them were common failures. Maybe it is a unique failure and I missed it because it was in the common one.
[testray-results (12).csv](https://github.com/liferay-core-infra/liferay-portal/files/14500019/testray-results.12.csv)

**Pull request closed without merging**
