### PR TITLE
[Method References 2] LPS-165165 Convert method reference to ServiceTrackerList in module portal-search-elasticsearch7-impl | part 1

### PR DESCRIPTION
**Pull request by W2jx**
Resend, re-modified class SidecarManager based on [comment](https://github.com/liferay-core-infra/liferay-portal/pull/2376),

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@W2jx all integration and fuctional tests failed on startup due to:

```
[beanshell] 2022-11-11 10:33:20.478 ERROR [main][ElasticsearchSearchEngine:56] bundle com.liferay.portal.search.elasticsearch7.impl:6.0.62 (121)[com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngine(105)] : The activate method has thrown an exception
[beanshell] com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionNotInitializedException: Elasticsearch connection not found. Production Mode Enabled: false, Connection ID: null, Prefer Local Cluster: true, Cross-Cluster Replication Enabled: false. Enable INFO logs on class com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionManager for more information
[beanshell] 	at com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionManager.getRestHighLevelClient(ElasticsearchConnectionManager.java:193) ~[?:?]
[beanshell] 	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.index.GetIndexIndexRequestExecutorImpl._getGetIndexResponse(GetIndexIndexRequestExecutorImpl.java:157) ~[?:?]
[beanshell] 	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.index.GetIndexIndexRequestExecutorImpl.execute(GetIndexIndexRequestExecutorImpl.java:56) ~[?:?]
[beanshell] 	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.index.ElasticsearchIndexRequestExecutor.executeIndexRequest(ElasticsearchIndexRequestExecutor.java:104) ~[?:?]
[beanshell] 	at com.liferay.portal.search.engine.adapter.index.GetIndexIndexRequest.accept(GetIndexIndexRequest.java:35) ~[?:?]
[beanshell] 	at com.liferay.portal.search.engine.adapter.index.GetIndexIndexRequest.accept(GetIndexIndexRequest.java:22) ~[?:?]
[beanshell] 	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.ElasticsearchSearchEngineAdapterImpl.execute(ElasticsearchSearchEngineAdapterImpl.java:91) ~[?:?]
[beanshell] 	at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngine._getIndexedCompanyIds(ElasticsearchSearchEngine.java:312) ~[?:?]
[beanshell] 	at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngine.activate(ElasticsearchSearchEngine.java:228) ~[?:?]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-29/test-portal-acceptance-pullrequest(master)/5388/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
Force-Push is just to fix the startup error.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@vicnate5 Could you help us confirm whether `embedded` mode is still existing?

@W2jx @tinatian If the above answer is no, the only real impl for `SettingsContributor` can be removed, because it's for `embedded` mode, not for `sidecar` mode. On the other hand, if this only impl is removed, do you want `SettingsContributor` to be remvoed, regardless of possibility of devs outside Liferay using it?

**Comment by vicnate5** [comment]
@xbrianlee From my memory, we only have sidecar and remote support now. Is there still any "embedded" mode?

**Comment by dantewang** [comment]
Asked search team lead on Slack about whether the `SettingsContributor` can be removed.

**Comment by xbrianlee** [comment]
@vicnate5 That's right, embedded mode doesn't exist in master anymore

**Comment by dantewang** [comment]
@W2jx Now that the embedded mode is no longer existing, let's go ahead and remove the `SettingsContributor` and its only impl. Let's see whether the search team can accept this. Please resend the removal in a separate PR, and then resend the method reference conversion if there's still any.

**Pull request closed without merging**
