### PR TITLE
LPS-143480 Separate ModelListener from ReleasePublisher to prevent po…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…tential circular reference on startup

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
CC @slnn

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/110924

@slnn please update ticket description for this issue.

**Comment by shuyangzhou** [comment]
ci:close

**Comment by slnn** [comment]
> See [brianchandotcom#110924](https://github.com/brianchandotcom/liferay-portal/pull/110924)
> 
> @slnn please update ticket description for this issue.

Done, please see https://issues.liferay.com/browse/LPS-143480

**Pull request closed without merging**
