### PR TITLE
LPS-196524 move class Snapshot to portal-kernel and remove unused dependency

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend. Thanks!
https://liferay.atlassian.net/browse/LPS-196524

Changes in this PR:
- resolve code conflicts in file `PanelAppRegistry`
- Baseline
- move and fix `SnapshotTest`
- previous pr
https://github.com/liferay-core-infra/liferay-portal/pull/5588

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
SF failure is not related.

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Pull request closed without merging**
