### PR TITLE
LPS-157036 && LPS-157039

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-157036 and https://issues.liferay.com/browse/LPS-157039.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by jeffwu0724** [comment]
rebased and fixed the code conflict in "lib/versions-complete.xml" by auto generate again.

**Comment by jeffwu0724** [comment]
rebased and fixed the code conflict in "lib/development/dependencies.properties"

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
updated the BREAKING_CHANGES.markdown @tinatian @vicnate5

**Comment by jeffwu0724** [comment]
updated the BREAKING_CHANGES.markdown

**Comment by tinatian** [comment]
@jeffwu0724 Please modify this "DXP UXX" to the real value

**Comment by jeffwu0724** [comment]
updated BREAKING_CHANGES.markdown and changed DXP UXX to DXP U37

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/1204

**Pull request closed without merging**
