### PR TITLE
LPD-33593 remove wstx.jar

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This is for https://liferay.atlassian.net/browse/LPD-33593.
I remove wstx and try to fix the unit test.
Thanks,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:help

**Comment by jeffwu0724** [comment]
ci:test:acceptance-functional

**Comment by jeffwu0724** [comment]
ci:report:79976515

**Comment by jeffwu0724** [comment]
ci:report:79992771

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:headless

**Comment by jeffwu0724** [comment]
ci:report:81482192

**Comment by jeffwu0724** [comment]
ci:report:81482192

**Comment by jeffwu0724** [comment]
ci:report:81542069

**Comment by jeffwu0724** [comment]
relevant test: 
https://testray.liferay.com/#/project/34754/routines/34756/build/81542069/case-result/81777957/history -- passed locally
https://testray.liferay.com/#/project/34754/routines/34756/build/81542069/case-result/81777965/history -- passed locally
https://testray.liferay.com/#/project/34754/routines/34756/build/81542069/case-result/81777971/history -- passed locally
https://testray.liferay.com/#/project/34754/routines/34756/build/81542069/case-result/81777977/history -- passed locally
https://testray.liferay.com/#/project/34754/routines/34756/build/81542069/case-result/81777983/history -- passed locally
https://testray.liferay.com/#/project/34754/routines/34756/build/81542069/case-result/81777989/history -- passed locally
https://testray.liferay.com/#/project/34754/routines/34756/build/81542069/case-result/81777997/history -- passed locally

fucntional  test:
https://testray.liferay.com/#/project/34754/routines/34756/build/79976515/case-result/80042697/history  -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/79976515/case-result/80044977/history  -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/79976515/case-result/80045177/history  -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/79976515/case-result/80052554/history  -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/79976515/case-result/80053378/history  -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/79976515/case-result/80055914/history  -- not unique

No unique regression found

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:report:82289243

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
fixed the typo in the commit message, and force pushed

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:report:5063395

**Comment by jeffwu0724** [comment]
No unique regression found based on the laster relevant test report

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/154018

**Pull request closed without merging**
