### PR TITLE
LPS-146796 User unable to login after resetting password if last in Publication

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:test:sf

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by stsquared99** [comment]
ci:test

**Comment by stsquared99** [comment]
@xbrianlee Can you check these results? Thanks!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113676

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
