### PR TITLE
[Components with more than 1 service] LPS-185366 Refactor ModelRepository components

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://issues.liferay.com/browse/LPS-185366

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by rafaprax** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:test:staging

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Comment by Kvale1733** [comment]
ci:test:stable

**Review by rafaprax — APPROVED** [review]

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Comment by dantewang** [comment]
ci:test:export-import

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/135992

**Pull request closed without merging**
