### PR TITLE
LPS-195602 Fix model.class.name property in CommerceChannelAccountEntryRelModelResourcePermission

### PR DESCRIPTION
**Pull request by JanisZhang**
I'm sending this PR to align the property value with the actual model class name in the class `CommerceChannelAccountEntryRelModelResourcePermission`. See https://github.com/liferay-core-infra/liferay-portal/pull/5501. Thanks!

Ticket: https://liferay.atlassian.net/browse/LPS-195602

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:commerce

**Comment by dantewang** [comment]
@JanisZhang Will the other 3 be very complicated? If not, let's just send them all together.

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by JanisZhang** [comment]
Hi @dantewang, the rest is added by https://github.com/brianchandotcom/liferay-portal/pull/125719, I'm still looking into it. thanks.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:workflow

**Comment by JanisZhang** [comment]
ci:test:headless

**Comment by JanisZhang** [comment]
ci:test:commerce

**Review by dantewang — APPROVED** [review]

**Pull request closed without merging**
