### PR TITLE
LPD-41899 11-18

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:70847169

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 70847169.
> 
> Job Link: [generate-testray-csv](https://test-1-39.liferay.com/job/generate-testray-csv/498/)
> 
> Testray CSV Link: [testray-results-70847169.csv](https://test-1-39.liferay.com/userContent/jobs/generate-testray-csv/builds/498/testray-results-70847169.csv)

@tinatian This run only has a bunch of "failed to run" integration tests, and they seem to "fail" because the batch timed out. None of these failed-to-run tests appear in any kind of failure in the previous relevant runs. So I think this relevant run is clean.

**Comment by dantewang** [comment]
FYI @matyaswollner for https://github.com/liferay-core-infra/liferay-portal/pull/7647/commits/eed00f43907a60dde3466bde5e362c873b2913fc and https://github.com/liferay-core-infra/liferay-portal/pull/7647/commits/577b0257848fa3ecd37f15f0bca3fb71cc647da7

**Comment by tinatian** [comment]
ci:forward:force

FYI @shuyangzhou

**Pull request closed without merging**
