### PR TITLE
LPS-167572

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@tinatian error on startup:

```
[beanshell] 2022-12-28 22:16:21.888 DEBUG [Start Level: Equinox Container: 254904ea-e046-449e-8e30-0c61ed7dc5f8][BundleStartStopLogger:86] STARTED com.liferay.commerce.taglib_5.0.20 [1495]
[beanshell] 2022-12-28 22:16:22.048 INFO  [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration)][Sidecar:132] Stopping sidecar Elasticsearch
[beanshell] 2022-12-28 22:16:22.050 DEBUG [main][BundleStartStopLogger:86] STARTED com.liferay.portal.file.install.impl_4.0.23 [20]
[beanshell] 2022-12-28 22:16:22.050 INFO  [main][ModuleFrameworkImpl:1582] Started web bundles
[beanshell] 2022-12-28 22:16:22.050 INFO  [main][ModuleFrameworkImpl:272] Navigate to Control Panel > System > Gogo Shell and enter "lb" to see all bundles
[beanshell] 2022-12-28 22:16:29.072 ERROR [main][ElasticsearchSearchEngine:56] bundle com.liferay.portal.search.elasticsearch7.impl:6.0.66 (105)[com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngine(36)] : The activate method has thrown an exception
[beanshell] java.lang.RuntimeException: org.elasticsearch.ElasticsearchException: ElasticsearchException[java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused]; nested: ExecutionException[java.net.ConnectException: Connection refused]; nested: ConnectException[Connection refused];
[beanshell] 	at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2695) ~[?:?]
[beanshell] 	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2171) ~[?:?]
[beanshell] 	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137) ~[?:?]
[beanshell] 	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105) ~[?:?]
[beanshell] 	at org.elasticsearch.client.IndicesClient.get(IndicesClient.java:1112) ~[?:?]
[beanshell] 	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.index.GetIndexIndexRequestExecutorImpl._getGetIndexResponse(GetIndexIndexRequestExecutorImpl.java:164) ~[?:?]
[beanshell] 	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.index.GetIndexIndexRequestExecutorImpl.execute(GetIndexIndexRequestExecutorImpl.java:56) ~[?:?]
[beanshell] 	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.index.ElasticsearchIndexRequestExecutor.executeIndexRequest(ElasticsearchIndexRequestExecutor.java:104) ~[?:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-32/test-portal-acceptance-pullrequest(master)/7640/modules-integration-mysql57-jdk8/3/8/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@catarineaguiar I can not reproduce the issue you mentioned locally, rebase and retrigger the test. If there is still unique failure, please try to reproduce it locally and then provide me steps to reproduce it.

Thanks.
Tina

**Comment by zhangyan0701** [comment]
The issue that @catarineaguiar mentioned above occurred as well in the mostly recently relevant tests. 

I could reproduce with the bundle that generated here: https://github.com/liferay-core-infra/liferay-portal/pull/2854#issuecomment-1367721141. Sidecar started first but then it stopped, and error thrown in console:
```
[beanshell] 2022-12-30 02:42:46.229 ERROR [main][ElasticsearchSearchEngine:56] bundle com.liferay.portal.search.elasticsearch7.impl:6.0.66 (265)[com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngine(768)] : The activate method has thrown an exception
[beanshell] java.lang.RuntimeException: org.elasticsearch.ElasticsearchException: ElasticsearchException[java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused]; nested: ExecutionException[java.net.ConnectException: Connection refused]; nested: ConnectException[Connection refused];
```

The bundle was built with config file `com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.config` in osgi/configs that includes below configurations:
```
additionalConfigurations="http.host:\ _local_,_site_"
logExceptionsOnly=B"false"
sidecarShutdownTimeout=L"20000"
sidecarJVMOptions=["-Xms256m","-Xmx512m"]
```
If I removed the config file, the issue was **NOT** reproducible, sidecar was not stopped. But when I added the file again, sidecar stopped.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Regression found:

**The config file in /osgi/configs cannot be loaded.**

Add a config file to /osgi/configs, such as `com.liferay.portal.security.sso.token.configuration.TokenConfiguration.config` with content:
```
enabled="true"
tokenLocation="REQUEST"
```
Then check table Configuration_.

Result: Configurations are not added into database.

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128382

**Pull request closed without merging**
