### PR TITLE
LPS-159984 Update service builder to take into account Arrays and Versioned entities on javadoc

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
In order to fix some javadoc warning we should update the service builder to take some cases into account, those cases are:

* Versioned Entities
* Array parameters

[Link to the issue](https://issues.liferay.com/browse/LPS-159984)

Proposed Solution
----
Update javadoc:

* Versioned Entities
Take into account if is **entity.versionEntity** to append draft to parameter name

* Array parameters
Take into account if is **entityColumn.hasArrayableOperator()** to use the plural parameter name

How to test it
---
Step-by-Step:

1. Execute ../../../../gradlew javadoc on fragment-api module

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@ealonso regression found:

```
[echo] diff --git a/modules/dxp/apps/commerce/commerce-machine-learning-forecast-alert-api/src/main/java/com/liferay/commerce/machine/learning/forecast/alert/service/persistence/CommerceMLForecastAlertEntryPersistence.java b/modules/dxp/apps/commerce/commerce-machine-learning-forecast-alert-api/src/main/java/com/liferay/commerce/machine/learning/forecast/alert/service/persistence/CommerceMLForecastAlertEntryPersistence.java
     [echo] index 264a1592756f..08cf69f6726e 100644
     [echo] --- a/modules/dxp/apps/commerce/commerce-machine-learning-forecast-alert-api/src/main/java/com/liferay/commerce/machine/learning/forecast/alert/service/persistence/CommerceMLForecastAlertEntryPersistence.java
     [echo] +++ b/modules/dxp/apps/commerce/commerce-machine-learning-forecast-alert-api/src/main/java/com/liferay/commerce/machine/learning/forecast/alert/service/persistence/CommerceMLForecastAlertEntryPersistence.java
     [echo] @@ -611,7 +611,7 @@ public interface CommerceMLForecastAlertEntryPersistence
     [echo]  	 * </p>
     [echo]  	 *
     [echo]  	 * @param companyId the company ID
     [echo] -	 * @param commerceAccountId the commerce account ID
     [echo] +	 * @param commerceAccountIds the commerce account IDs
     [echo]  	 * @param status the status
     [echo]  	 * @param start the lower bound of the range of commerce ml forecast alert entries
     [echo]  	 * @param end the upper bound of the range of commerce ml forecast alert entries (not inclusive)
     [echo] @@ -888,7 +888,7 @@ public interface CommerceMLForecastAlertEntryPersistence
     [echo]  	 * </p>
     [echo]  	 *
     [echo]  	 * @param companyId the company ID
     [echo] -	 * @param commerceAccountId the commerce account ID
     [echo] +	 * @param commerceAccountIds the commerce account IDs
     [echo]  	 * @param relativeChange the relative change
     [echo]  	 * @param status the status
     [echo]  	 * @param start the lower bound of the range of commerce ml forecast alert entries
     [echo] @@ -1173,7 +1173,7 @@ public interface CommerceMLForecastAlertEntryPersistence
     [echo]  	 * </p>
     [echo]  	 *
     [echo]  	 * @param companyId the company ID
     [echo] -	 * @param commerceAccountId the commerce account ID
     [echo] +	 * @param commerceAccountIds the commerce account IDs
     [echo]  	 * @param relativeChange the relative change
     [echo]  	 * @param status the status
     [echo]  	 * @param start the lower bound of the range of commerce ml forecast alert entries
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-30/test-portal-acceptance-pullrequest(master)/4087/service-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@ealonso no regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121700

**Pull request closed without merging**
