### PR TITLE
[Convert method references]LPS-162474 Convert method references to field references in module co…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-162474

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?


Thanks
Lily

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
@catarineaguiar Could you take a look at the Commerce test when they finish?

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@shuyangzhou @tinatian All tests passed and changes are direct replacements. Asked Commerce team for a final check and forward.

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by tinatian** [comment]
@victoroscuro Please help me scan test results, please note we already triggered ci:test:commerce, is there any reason you trigger it again?

Thanks.
Tina

**Comment by victoroscuro** [comment]
@tinatian Checks are fine. Please check slack thread. Thanks

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
