### PR TITLE
[Components with more than 1 service] LPS-199532 Refactor NPMJavaScriptAwarePortalWebResources component

### PR DESCRIPTION
**Pull request by MrJohn1911**
Previous pull: https://github.com/liferay-core-infra/liferay-portal/pull/5973

Ticket: https://liferay.atlassian.net/browse/LPS-199532

This pull does not contains any code changes compared with the previous one, just changes in the commit organization and messages.

CC: @rafaprax

### CODE REVIEW

**Comment by MrJohn1911** [comment]
This pull does not contains any code changes compared with the previous one, just changes in the commit organization and messages.

CC: @rafaprax

**Review by rafaprax — APPROVED** [review]

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:frontend

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@MrJohn1911 @rafaprax It seems the `JavaScriptAwarePortalWebResources` interface is designed as a extension point, as it's tracked by a `ServiceTrackerList`. The PR change looks good to me, but if we didn't confirm with frontend team, please send to them for final review.

There's a conflict in bnd.bnd, I'm going to close this PR, please forward to [frontend infra](https://github.com/liferay-frontend), thanks!

**Pull request closed without merging**
