### PR TITLE
[Remove Stream/Optional usage] LPS-170769 fragment

### PR DESCRIPTION
**Pull request by JanisZhang**
previous:https://github.com/liferay-core-infra/liferay-portal/pull/2772

Code conflicts, resend. Thanks!

### CODE REVIEW

**Comment by dantewang** [comment]
@JanisZhang Was the conflict in java code or sem ver files?

**Comment by dantewang** [comment]
ci:test:echo

**Comment by JanisZhang** [comment]
> @JanisZhang Was the conflict in java code or sem ver files?

Hi @dantewang, the Bnd file conflict, and previous pr have non-related sf failure, so I resend.

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
