### PR TITLE
LPS-191929 Fix not (Predicate.not) operator to have a correct generated SQL

### PR DESCRIPTION
**Pull request by ccorreagg**
Related bug: https://liferay.atlassian.net/browse/LPS-191929

See https://github.com/liferay-core-infra/liferay-portal/pull/5119

---

The purpose of this PR is to fix the `Predicate.not` operator. Before this PR, the `not` method of the `Predicate` interface received one argument, but it does not make sense as the `not` operator must negate the current predicate.

In the `DefaultPredicate.not()` method implemented uses the new `EmptyExpression` as left expression. That causes that the Consumer<String> that contributes to the SQL String is not invoked with the left part, avoiding to include text with invalid SQL syntax.

---

Example:

Given a Predicate (for example, a predicate whose SQL String value would be `O_20096_Student.studentName_ = 'value'`), if we negate the predicate:

**Before the PR**

The SQL String value would be: `O_20096_Student.studentName_ = 'value' not (O_20096_Student.studentName_ = 'value'))` and that causes the following error:

```
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(O_20096_Student.studentName_ = 'value')  limit 20' at line 1
```

**After the PR**

The SQL String value would be: `not (O_20096_Student.studentName_ = 'value'))`

### CODE REVIEW

**Comment by ccorreagg** [comment]
cc/ @tinatian: I have moved the integration tests of our functionality to the [first commit](https://github.com/liferay-core-infra/liferay-portal/pull/5147/commits/94f80eaebfdd6a35e2139da686dd8085de8ee60c).

You just need to execute the integration test `ObjectEntryResourceTest.testFilterByLogicalOperatorsObjectEntries` from the `modules/apps/object/object-rest-test` module:

`gw tI --tests ObjectEntryResourceTest.testFilterByLogicalOperatorsObjectEntries`

I got the error:

```
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(O_20096_AVbCNTTTB.xQ1onz6ZV_ = '559647700')  limit 20' at line 1
    	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
    	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
    	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
    	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
    	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
    	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
    	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
    	at org.hibernate.loader.Loader.getResultSet(Loader.java:2322)
    	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2075)
    	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037)
    	at org.hibernate.loader.Loader.doQuery(Loader.java:956)
    	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:357)
    	at org.hibernate.loader.Loader.doList(Loader.java:2868)
    	at org.hibernate.loader.Loader.doList(Loader.java:2850)
    	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2682)
    	at org.hibernate.loader.Loader.list(Loader.java:2677)
    	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:338)
    	at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:2186)
    	at org.hibernate.internal.AbstractSharedSessionContract.list(AbstractSharedSessionContract.java:1204)
    	at org.hibernate.query.internal.NativeQueryImpl.doList(NativeQueryImpl.java:177)
    	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617)
    	at com.liferay.portal.dao.orm.hibernate.SQLQueryImpl.list(SQLQueryImpl.java:167)
    	at com.liferay.portal.dao.orm.hibernate.SQLQueryImpl.list(SQLQueryImpl.java:159)
    	at com.liferay.portal.kernel.dao.orm.QueryUtil.list(QueryUtil.java:75)
    	at com.liferay.portal.kernel.dao.orm.QueryUtil.list(QueryUtil.java:44)
    	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.dslQuery(BasePersistenceImpl.java:296)
    	at com.liferay.object.service.impl.ObjectEntryLocalServiceImpl._list(ObjectEntryLocalServiceImpl.java:3248)
    	at com.liferay.object.service.impl.ObjectEntryLocalServiceImpl.getValuesList(ObjectEntryLocalServiceImpl.java:1077)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41)
    	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60)
    	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48)
    	at com.liferay.change.tracking.internal.aop.CTTransactionAdvice.invoke(CTTransactionAdvice.java:70)
    	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48)
    	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40)
    	at com.sun.proxy.$Proxy1106.getValuesList(Unknown Source)
    	at com.liferay.object.rest.internal.manager.v1_0.DefaultObjectEntryManagerImpl.getObjectEntries(DefaultObjectEntryManagerImpl.java:548)
    	at com.liferay.object.rest.internal.resource.v1_0.ObjectEntryResourceImpl.getObjectEntriesPage(ObjectEntryResourceImpl.java:221)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
    	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
    	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
    	... 99 more

```

**Comment by catarineaguiar** [comment]
no regressions were found and the bug is no reproducible anymore.

@ccorreagg please, resolve conflicts.
Thanks!

**Comment by ccorreagg** [comment]
Rebased with upstream/master.

Please @catarineaguiar feel free to forward to Brian

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@ccorreagg You are modifying dsl api, please add test for dsl without any object context. I am not familiar with object framework, it is hard for me to tell if your integration test is valid and if this is really a dsl framework issue. If you have a dsl only integration test and it failed, it would be easy for me to see the issue.

FYI @brunofalc This is an example that modifying framework level code, but did not provide corresponding test to expose the issue.

Please resend.

Thanks.
Tina

**Comment by ccorreagg** [comment]
@tinatian  We have been performed this collaboration to speed up the time for the bug to be fixed, but with our current workload we don't have more time to keep working on the pull request. I have not included any extra integration tests, I modified the already existing tests. Probably the test should exist beforehand with the previous code of the module, the method already existed.

In [this commit](https://github.com/liferay-core-infra/liferay-portal/pull/5147/commits/0aa98e404d8dda7eb8f80620d8734b96b542c34a) I consider the error is being properly exposed, from a wrong expected value to the right expected value.

We will reassign the bug to Core Infra team and will be fixed by following the standard resolution flow based on priorities.

**Comment by tinatian** [comment]
@ccorreagg Before you reassign the issue to core infra, please update your ticket with reproduce steps without any object related context, or only send the test you think can expose the issue to liferay-core-infra. Please help us to isolate the issue from object context so that this issue can be addressed fast or it may be waited on the list for a long time based on our current work load.

By the way, I did not understand why you changed the expected value at https://github.com/liferay-core-infra/liferay-portal/pull/5147/commits/0aa98e404d8dda7eb8f80620d8734b96b542c34a, please add more details why you think the original expected value is wrong.

FYI @brunofalc 

Thanks.
Tina.

**Comment by ccorreagg** [comment]
> @ccorreagg Before you reassign the issue to core infra, please update your ticket with reproduce steps without any object related context, or only send the test you think can expose the issue to liferay-core-infra. Please help us to isolate the issue from object context so that this issue can be addressed fast or it may be waited on the list for a long time based on our current work load.
> 
> By the way, I did not understand why you changed the expected value at [0aa98e4](https://github.com/liferay-core-infra/liferay-portal/commit/0aa98e404d8dda7eb8f80620d8734b96b542c34a), please add more details why you think the original expected value is wrong.
> 
> FYI @brunofalc
> 
> Thanks. Tina.

@tinatian There is no other way to reproduce the issue without Object's related context, because the only module in Liferay Portal that uses the `not` operator (that is, that calls the `Predicate.not` method) is the `object-rest-impl` module.

Based on the [SQL documentation](https://www.w3schools.com/sql/sql_and_or.asp) about the `not` operator, the syntax is the following:

```
SELECT column1, column2, ...
FROM table_name
WHERE NOT condition;
```

That is why the expected value at [0aa98e4](https://github.com/liferay-core-infra/liferay-portal/commit/0aa98e404d8dda7eb8f80620d8734b96b542c34a) didn't make any sense with the NOT operator, as the condition (the predicate) was included twice, before and after the `not` operator.

**Comment by tinatian** [comment]
@ccorreagg What do you mean by including twice? This is the original expected value, nothing is included twice .`"MainExample.mainExampleId >= ? or MainExample.mainExampleId <= " +
				"? not MainExample.flag = ?",`

**Comment by tinatian** [comment]
@ccorreagg Could you please do not modify original test, add another test to show me what the "twice" you mean? This should be good enough to separate this issue from object context.

My only concern is that if object use NOT operator in a wrong way.

**Comment by ccorreagg** [comment]
@tinatian I meant including two predicates with the not operator. For example, given a predicate, if you want to negate the predicate, you don't need an extra argument. See please the description of the bug.

In the following use case:
Predicate: `MainExample.mainExampleId >= ? or MainExample.mainExampleId <= ?`

If you want to negate the predicate in SQL, the result should be "not" + the predicate. However, with the master's solution, the not method receives an extra predicate, and then it concatenates the first predicate + not + the second predicate, that is why the "expected" value is:

`MainExample.mainExampleId >= ? or MainExample.mainExampleId <= ? not MainExample.flag = ?`

**Comment by tinatian** [comment]
@ccorreagg Thanks! I finally understand what the issue is, please see https://github.com/liferay-core-infra/liferay-portal/pull/5203. The root cause is the original implementation is totally wrong, thus the test is wrong.

Basically when I asked for a test to expose your issue in your original pull https://github.com/liferay-core-infra/liferay-portal/pull/5119, you can just move the test you modified to the first commit and explain why the expected value is wrong in the commit message like what you did https://github.com/liferay-core-infra/liferay-portal/pull/5147#issuecomment-1665110668, then it would be clear to me. 

In core infra, we prefer you explain the reason in your commit message instead of a comment in the pull, as the commit message can be easily found while tracking back, while the comment on the pull is not. Here is the guidelines for the pull question of core infra https://liferay.atlassian.net/wiki/spaces/ENGCOREINFRA/pages/2051376221/Pull+Requests+-+Guidelines. Hopefully our communication will be easier next time.

Thanks.
Tina.

**Pull request closed without merging**
