### PR TITLE
LPS-191027 Remove AsahSearchKeyWordsWebCacheItem

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from https://github.com/liferay-core-infra/liferay-portal/pull/5079
- Use singleVMPool instead
- Added last 3 SF commits

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:search

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
pushed only commit message change, no need for addtional ci tests

**Comment by tinatian** [comment]
@julschong As we talked, please resend.

Tina

**Pull request closed without merging**
