### PR TITLE
[Method References 2] LPS-165169 Convert method reference in module portal-search (class SearchPermissionFilterContributorsRegistryImpl )

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(2022/12/7 9:36)

**Comment by W2jx** [comment]
no conflicts(2022/12/8 9:18)

**Comment by W2jx** [comment]
no conflicts(12/9 9:50)

**Comment by W2jx** [comment]
no conflicts(12/12 10:09)

**Comment by W2jx** [comment]
no conflicts(12/13 9:55)

**Comment by W2jx** [comment]
no conflicts(12/15 9:25)

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
