### PR TITLE
[System Properties] LPS-154947 Replace method System.getProperty() with method SystemProperties.get()

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I replace method System.getProperty() with method SystemProperties.get() in this pr.

Detail: https://github.com/liferay-core-infra/liferay-portal/pull/1267

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @catarineaguiar  , Could you please help me check the test results when you free ? Thanks!

**Comment by catarineaguiar** [comment]
@W2jx no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/121707

**Pull request closed without merging**
