### PR TITLE
[Remove unused reference] LPS-166255 

### PR DESCRIPTION
**Pull request by JanisZhang**
This PR is to remove unused fields in `commerce-product-asset-catagories-web`. Thanks!
https://issues.liferay.com/browse/LPS-166255

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
No regressions found.

cc/ @zhangyan0701

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by dantewang** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/125342

cc @shuyangzhou @tinatian

**Pull request closed without merging**
