### PR TITLE
[Method References 2] LPS-171231 Convert method reference to ServiceTrackerMap in class MultiLanguageKaleoTaskAssignmentSelector

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3842

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by W2jx** [comment]
no conflicts(4/4 10:27)

**Comment by W2jx** [comment]
only do semver, no need to rerun test

**Comment by W2jx** [comment]
no conflicts(4/10 8:33)

**Comment by tinatian** [comment]
@W2jx @dantewang Same reason as https://github.com/liferay-core-infra/liferay-portal/pull/4068.

@W2jx Please check your other pulls if they share same reason as this one.

Please resend.
Thanks.
Tina

**Pull request closed without merging**
