### PR TITLE
[Remove Stream/Optional usage] LPS-176378 dynamic-data-mapping-api

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-176378

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found. Only a semver issue

  ```
 [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/dynamic-data-mapping/dynamic-data-mapping-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.dynamic.data.mapping.expression        MAJOR      4.2.0      4.1.0      5.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.dynamic.data.mapping.expression.ExecuteActionRequest
     [exec]     		+   method     getParameter(java.lang.String)
     [exec]     			+   return     java.lang.Object
     [exec]     		-   method     getParameterOptional(java.lang.String)
     [exec]     			-   return     java.util.Optional
     [exec]     	>   class      com.liferay.dynamic.data.mapping.expression.ExecuteActionResponse
     [exec]     		+   method     getOutput(java.lang.String)
     [exec]     			+   return     java.lang.Object
     [exec]     		-   method     getOutputOptional(java.lang.String)
     [exec]     			-   return     java.util.Optional
     [exec]     	>   class      com.liferay.dynamic.data.mapping.expression.UpdateFieldPropertyRequest
     [exec]     		+   method     getProperty(java.lang.String)
     [exec]     			+   return     java.lang.Object
     [exec]     		-   method     getPropertyOptional(java.lang.String)
     [exec]     			-   return     java.util.Optional
     [exec]     	<   interface  com.liferay.dynamic.data.mapping.expression.DDMExpression
     [exec]     		+   method     getDSLExpression()
     [exec]     			+   access     abstract
     [exec]     			+   return     com.liferay.petra.sql.dsl.expression.Expression
     [exec]     	-   version    4.1.0
     [exec]     	+   version    4.2.0
     [exec]     * com.liferay.dynamic.data.mapping.form.builder.context MAJOR      1.0.1      1.0.1      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.dynamic.data.mapping.form.builder.context.DDMFormBuilderContextRequest
     [exec]     		+   method     with(com.liferay.dynamic.data.mapping.model.DDMStructure,javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse,java.util.Locale,boolean)
     [exec]     			+   access     static
     [exec]     			+   return     com.liferay.dynamic.data.mapping.form.builder.context.DDMFormBuilderContextRequest
     [exec]     		-   method     with(java.util.Optional,javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse,java.util.Locale,boolean)
     [exec]     			-   access     static
     [exec]     			-   return     com.liferay.dynamic.data.mapping.form.builder.context.DDMFormBuilderContextRequest
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 21.0.0
  ```
  [Log](https://testray.liferay.com/reports/production/logs/2023-02/test-1-26/test-portal-acceptance-pullrequest(master)/7866/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by JanisZhang** [comment]
force-pushed and I only add baseline commit

**Comment by JanisZhang** [comment]
force-pushed. code conflicts in `modules/apps/dynamic-data-mapping/dynamic-data-mapping-api/bnd.bnd`
It shouldn't affect the test result!

**Comment by JanisZhang** [comment]
force-pushed. add 1 SF commit.

**Pull request closed without merging**
