### PR TITLE
[Spring Beans] LPS-200292 Merge IdenticalPhoneNumberFormatImpl into Util and move to portal-impl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(11/3 9:19)

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@W2jx Compile issue found
```
 [exec] /opt/dev/projects/github/liferay-portal/modules/test/integration-point-test/src/testIntegration/java/com/liferay/integration/point/test/IntegrationPointTest.java:13: error: cannot find symbol
     [exec] import com.liferay.portal.kernel.format.PhoneNumberFormatUtil;
     [exec]                                        ^
     [exec]   symbol:   class PhoneNumberFormatUtil
     [exec]   location: package com.liferay.portal.kernel.format
     [exec] 
     [exec] > Task :test:integration-point-test:compileTestIntegrationJava
     [exec] /opt/dev/projects/github/liferay-portal/modules/test/integration-point-test/src/testIntegration/java/com/liferay/integration/point/test/IntegrationPointTest.java:99: error: cannot find symbol
     [exec] 			phoneNumberFormat, PhoneNumberFormatUtil.getPhoneNumberFormat());
     [exec] 			                   ^
     [exec]   symbol:   variable PhoneNumberFormatUtil
     [exec]   location: class com.liferay.integration.point.test.IntegrationPointTest
     [exec] 2 errors
     [exec] 
     [exec] > Task :test:integration-point-test:compileTestIntegrationJava FAILED
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/test/jenkins-plugin-events/src/main/java/com/liferay/jenkins/plugin/events/listener/JMSMessageListener.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 
```
[Log](https://testray.liferay.com/reports/production/logs/2023-11/test-1-34/test-portal-acceptance-pullrequest(master)/5023/modules-compile-jdk8/0/10/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
