### PR TITLE
[Remove unused @Reference var] LPS-164224 change tracking service

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove the unused @reference variable in ` change-tracking-service`. Thanks!

CI test passed in https://github.com/JanisZhang/liferay-portal/pull/128

https://issues.liferay.com/browse/LPS-164224

### CODE REVIEW

**Comment by JanisZhang** [comment]
Add QA passed label as all test passed.

**Comment by tinatian** [comment]
ci:test:help

**Comment by tinatian** [comment]
ci:test:publications

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results once it is finished.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123998

**Pull request closed without merging**
