### PR TITLE
[Method References 2] LPS-165748 Convert method reference to ServiceTrackerList in module module portal-search

### PR DESCRIPTION
**Pull request by W2jx**
Convert method reference to ServiceTrackerList in module module portal-search.

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by dantewang** [comment]
@W2jx After looking at the real-world commits, I think it's better to directly replace the `HashSet` field with a `ServiceTrackerList`. No need to change it to a `List` first and then `ServiceTrackerList`.

Could you please update such PRs? Thanks!

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by tinatian** [comment]
@W2jx The two classes you changed here have similar logic and same name, I doubt we need both of them, please try to do a clean up first, then remove the setMethods

**Pull request closed without merging**
