### PR TITLE
LPS-162804

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
@tinatian possible regression:

```
     [exec] com.liferay.portal.cache.internal.dao.orm.FinderCacheImplTest > testThreshold FAILED
     [exec]     java.lang.NoSuchFieldException: No field on null with name _basePersistenceServiceTrackerMap
     [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.getField(ReflectionTestUtil.java:135)
     [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.setFieldValue(ReflectionTestUtil.java:346)
     [exec]         at com.liferay.portal.cache.internal.dao.orm.FinderCacheImplTest.testThreshold(FinderCacheImplTest.java:184)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-32/test-portal-acceptance-pullrequest(master)/5801/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@tinatian no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123394

**Pull request closed without merging**
