### PR TITLE
LPS-149460 Move petra-model-adapter to apps/portal

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,

Resubmitted from #555
Note: move to app/portal instead of portal-utilities

Main Task: [LPS-147928 Remove petra jar from modules/apps](https://issues.liferay.com/browse/LPS-147928)
Sub Task: [LPS-149460 Move petra-model-adapter to apps/portal](https://issues.liferay.com/browse/LPS-149460)

Thank you!

### CODE REVIEW

**Comment by tinatian** [comment]
@julschong Code looks good to me, wait for QA to scan test results.

Tina.

**Comment by julschong** [comment]
@vicnate5 
Hi Victor,
Could you please help me scan the test result?
Thank you!

**Comment by vicnate5** [comment]
@catarineaguiar Can you check this one?

**Comment by catarineaguiar** [comment]
@julschong @tinatian no regressions were found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115926

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
