### PR TITLE
LPS-173858 Update SQL type for OracleDB setting

### PR DESCRIPTION
**Pull request by Vy-Bui17**
Hi team, this fix has passed our internal review for the regression bug here: https://issues.liferay.com/browse/LPS-173858.

Steps to reproduce (All operations have to be done under the connection to the Oracle Database):
`Start Liferay portal`
`cd modules/apps/portal/portal-dao-test`
`blade gw testIntegration --tests com.liferay.portal.dao.db.test.DBInspectorTest.testHasColumnTypeDouble`

CC: @locpham97

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:environments

**Comment by Kvale1733** [comment]
@Vy-CES No regressions found. Verified both affected tests pass. Also verified [LPS-158836](https://issues.liferay.com/browse/LPS-158836) still passes.

**Comment by tinatian** [comment]
@Vy-CES Please add test

**Comment by locpham97** [comment]
Hi @tinatian ,
Thanks for reviewing. However, I would like to ask what exact test you would like to add. In the previous LPS-158836, I added the test integrations, for this LPS, I fix the test relate to DBInspector test. 
I am looking forward to hearing your response.
Thanks,
Loc

**Comment by yuhai** [comment]
Hi @locpham97 and @Vy-CES,

Sorry for the delay. 

The fix looks good to me. Could please change the commit message? For example: 
_Fix DBInspectorTest#testHasColumnTypeDouble fails on Oracle. The issue was caused by LPS-158836 commit(fbcc8bab1bd4b324c5bb45ce9b0988ba00cfb67c).  Oracle database returns DATA_TYPE=101 in BINARY_DOUBLE column, please see https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Data-Types.html#GUID-7B72E154-677A-4342-A1EA-C74C1EA928E6_ 

After changing the commit message, I will approve the pr. 

If possible, please also update LPS ticket's type.

Thanks,
Hai

**Comment by locpham97** [comment]
Hi @yuhai ,
I updated the commit. Could you recheck it ?
Thanks,
Loc

**Review by yuhai — APPROVED** [review]
@dantewang, the fix looks good to me.

**Comment by dantewang** [comment]
@tinatian This pull is to fix a failure caught by an existing test, so no new test needed.

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
