### PR TITLE
Lps 144013

### PR DESCRIPTION
**Pull request by slnn**
/cc @dantewang @tinatian

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevnt

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Fetched.

**Comment by tinatian** [comment]
@slnn Please merge these two commits into one and resend, the logic looks good to me, please trigger ci tests and verify the test results.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by dantewang** [comment]
@slnn There's another usage of DataAccess.getConnection in _wrapStatement. Is that also possible to also trigger this issue? To me I would prefer to change both. And please verify with CI test results.

cc @tinatian

**Comment by slnn** [comment]
> @slnn There's another usage of DataAccess.getConnection in _wrapStatement. Is that also possible to also trigger this issue? To me I would prefer to change both. And please verify with CI test results.
> 
> cc @tinatian

OK, got it

**Comment by slnn** [comment]
Merged the two commits into and also changed another DataAccess.getConnection usage in _wrapStatement
Resend in https://github.com/liferay-core-infra/liferay-portal/pull/84

**Pull request closed without merging**
