### PR TITLE
[Replace Non-Blocking Usage] LPS-199424

### PR DESCRIPTION
**Pull request by JanisZhang**
resent:https://github.com/liferay-core-infra/liferay-portal/pull/5818

Replace non-blocking ServiceProxyFactory usages in class InlineSQLHelperUtil, RepositorySearchQueryBuilderUtil and CommentManagerUtil. Thanks.
https://liferay.atlassian.net/browse/LPS-199424

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
Run additional startup test

**Comment by catarineaguiar** [comment]
no regressions

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
