### PR TITLE
[Remove Stream/Optional usage] LPS-175060 Remove usages of Stream for module: portal-language-override-web

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:usm

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(2/10 9:06)

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130059

**Pull request closed without merging**
