### PR TITLE
[Remove Blocking usages]LPS-187897 portal-kernel| DefaultActionableDynamicQuery

### PR DESCRIPTION
**Pull request by JanisZhang**
https://liferay.atlassian.net/browse/LPS-187897

### CODE REVIEW

**Comment by Kvale1733** [comment]
Many test failed to run. Rerunning.

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@GinsonRen Please run a performance diff. Run database-heavy tests first, thanks!

**Comment by GinsonRen** [comment]
@dantewang Here are dl/blog/mb results:
MB:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 9b9c8fb | 10673 | 393 | -
PR-5223 | - | 10992 | 21.6 | 2.99%

Blog:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 9b9c8fb | 17023 | 46 | -
PR-5223 | - | 16978 | 55.5 | -0.26%

DL:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 9b9c8fb | 33808 | 204 | -
PR-5223 | - | 32615 | 377 | -3.53%

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
Took a look at the profiles, neither `PortalExecutorManager` nor any `ActionableDynamicQuery` is called at all during the DL test, so the DL result should just be a deviation.

**Comment by tinatian** [comment]
ci:forward:force

**Comment by tinatian** [comment]
@GinsonRen Please also check startup performance.

Thanks.
Tina.

**Comment by 111Anna** [comment]
Hi @tinatian @GinsonRen, I ran this PR on test machine, the test results are normal.

Here are test results:

CE:
Portal Version |GitId | Average Startup (ms) | % | Average Shutdown (ms) | % | Open File |Thread Create |Open Prepared Statement |Open SQL|Open service tracker|Open bundle tracker
-- | -- | -- | -- | -- | -- | -- | -- | -- | --|--|--
Baseline | 9b9c8fb |19066.3 | - | 2612.6 | - | 1480 | 97 | 120 | 855|5517|32
Baseline + PR-5223 | - | 19060.3 | 0.03% | 2614.3 | -0.07% |  1480|  97| 120 | 855|5518|33

DXP:
Portal Version | GitId | Average Startup (ms) | % | Average Shutdown (ms) | % | Open File |Thread Create |Open Prepared Statement |Open SQL|Open service tracker|Open bundle tracker
-- | -- | -- | -- | -- | -- | -- | -- | -- | --|--|--
Baseline | 9b9c8fb |20384| - | 3044.3| - | 1604 | 94 | 126 | 931|5962|33
Baseline + PR-5223 | - | 20569 | -0.91% |  3082| -1.24% | 1604|95 | 126 |932 |5962|33

**Pull request closed without merging**
