### PR TITLE
[TS] LPP-46544 > LPS-163257 XSS in DLFolder > description

### PR DESCRIPTION
**Pull request by TaiPhamLR**
Dear team,
Please help review this PR and leave your comments. Thanks.
Ticket: https://issues.liferay.com/browse/LPS-163257
Solution:
   Escape model Folder instance with method `toEscapedModel`
cc @sontruongces

### CODE REVIEW

**Comment by TaiPhamLR** [comment]
Previous internal PR: TaiPhamLR#6

**Comment by dantewang** [comment]
@TaiPhamLR The ticket's component is "Application Security", based on that, I think the [App-Sec](https://github.com/liferay-appsec) team should review this fix. Could you double check?

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
FYI @shuyangzhou

**Comment by TaiPhamLR** [comment]
> @TaiPhamLR The ticket's component is "Application Security", based on that, I think the [App-Sec](https://github.com/liferay-appsec) team should review this fix. Could you double check?

Thanks for your review. I'll double-check

**Pull request closed without merging**
