### PR TITLE
[Method Reference Static]Lps 183181

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-183181

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:data-engin

**Comment by slnn** [comment]
ci:test:data-engine

**Comment by slnn** [comment]
ci:test:security

**Comment by slnn** [comment]
ci:test:comment

**Comment by slnn** [comment]
ci:test:document

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@slnn No regressions. SF issue is unrelated.

**Comment by dantewang** [comment]
@slnn Conflict on source-formatter.properties.

**Review by dantewang — APPROVED** [review]

**Comment by slnn** [comment]
Force pushed to resolve the conflicts on SF properties

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@slnn Please see https://github.com/liferay-core-infra/liferay-portal/pull/4488#issuecomment-1542131885 and resend, thanks.

**Comment by slnn** [comment]
Please see https://github.com/liferay-core-infra/liferay-portal/pull/4513

**Pull request closed without merging**
