### PR TITLE
[Spring Beans] LPS-203588 Exclude DefaultFullNameGenerator as a Spring bean and offer an INSTANCE for both upgrade and regular usage

### PR DESCRIPTION
**Pull request by JanisZhang**
Ticket:https://liferay.atlassian.net/browse/LPS-203588

related to:https://github.com/liferay-core-infra/liferay-portal/pull/5803

Thanks for reviewing.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@JanisZhang No regressions just a semver issue

```
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.security.auth            MINOR      8.1.0      8.1.0      8.2.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.portal.kernel.security.auth.DefaultFullNameGenerator
     [exec] 		+   field      INSTANCE
     [exec] 			+   access     final
     [exec] 			+   access     static
     [exec] 			+   return     com.liferay.portal.kernel.security.auth.DefaultFullNameGenerator
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checki
```
[Log](https://testray.liferay.com/reports/production/logs/2023-12/test-1-29/test-portal-acceptance-pullrequest(master)/8895/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by JanisZhang** [comment]
Force-pushed. I only do Sem Ver. thx.

cc @Kvale1733

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/145242

**Pull request closed without merging**
