### PR TITLE
LPS-178022 Cleanup CustomFilter for optional removal

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@julschong Regressions found. Similar issues to the CustomFacet pr. 

**1 ) Compile issue**
```
[exec] > Task :apps:portal-search:portal-search-web:compileJSP FAILED
     [exec] 
     [exec] > Task :apps:portal-workflow:portal-workflow-instance-tracker-web:packageRunBuild
     [exec] Minification summary:
     [exec]   Files processed:   373
     [exec]   Files with errors: 167
     [exec]   Before size:       2769297
     [exec]   After size:        1874018
     [exec]   Delta:             895279
     [exec]   Elapsed:           6.52
     [exec] BUILD SASS: Built build/node/packageRunBuild/resources/.sass-cache/css/main.css
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-search/portal-search-web/build/jspc/org/apache/jsp/custom/filter/configuration_jsp.java:178: error: incompatible types: no instance(s) of type variable(s) T exist so that java.util.Optional<T> conforms to javax.portlet.PortletPreferences
     [exec] CustomFilterPortletPreferences customFilterPortletPreferences = new CustomFilterPortletPreferencesImpl(java.util.Optional.of(portletPreferences));
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-32/test-portal-acceptance-pullrequest(master)/9182/portal-license-smoke-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**2 ) Cannot configure custom facet widget. Looks related to the first issue as it throws similar errors.**

Steps to reproduce
1. Add a custom filter widget to a page
2. Hover over the widget, click on the blue ellipses on the far right of it, and click configuration

Expected Results: Can configure the custom facet widget in the Setup tab
Actual Results: The setup tab is selected but there is nothing to configure, just blank space. The following also appears in the console

```
   [exec] 
[beanshell] 1 hour 59 minutes until timeout.
     [exec] 2023-04-20 19:49:00.239 ERROR [http-nio-8080-exec-8][BaseJSPSettingsConfigurationAction:86] Unable to include JSP /custom/filter/configuration.jsp
     [exec] org.apache.jasper.JasperException: PWC6033: Error in Javac compilation for JSP
     [exec] 
     [exec] PWC6197: An error occurred at line: 47 in the jsp file: /custom/filter/configuration.jsp
     [exec] PWC6199: Generated servlet error:
     [exec] incompatible types: no instance(s) of type variable(s) T exist so that java.util.Optional<T> conforms to javax.portlet.PortletPreferences
     [exec] 
     [exec] PWC6199: Generated servlet error:
     [exec] Some messages have been simplified; recompile with -Xdiags:verbose to get full output
     [exec] 
     [exec] 
     [exec] 	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:129) ~[javax.servlet.jsp-2.3.3-b02.LIFERAY-PATCHED-9.jar:9.0.73]
     [exec] 	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:299) ~[javax.servlet.jsp-2.3.3-b02.LIFERAY-PATCHED-9.jar:9.0.73]
     [exec] 	at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:392) ~[javax.servlet.jsp-2.3.3-b02.LIFERAY-PATCHED-9.jar:9.0.73]
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-40/test-portal-acceptance-pullrequest(master)/1745/functional-tomcat90-mysql57-jdk8/2/14/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
@julschong formatting issue:

```
Do not use java.util.Optional, see LPS-170503: ./modules/apps/portal-search/portal-search-web/src/main/java/com/liferay/portal/search/web/internal/custom/filter/portlet/CustomFilterPortlet.java
```

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@julschong Regressions found. Portlet is temporarily unavailable error when adding custom filter widget via json

Steps to reproduce:
1. Add a widget page called "Test Page"
2. Add a Custom Filter widget to the page via json with the following curl. The groupID might be different. This id can be seen in the url when you go to Control Panel > Site > Liferay DXP (or whatever the default site is for you). The admin user and password might also not be test@liferay.com and test for you so you might have to modify that too (test@liferay.com:test)
```
curl -X POST -u 'test@liferay.com:test' -d 'groupId=20119' -d 'privateLayout=false' -d 'layoutId=4' -d 'typeSettings=layout-template-id=2_columns_ii%0Acolumn-1=com_liferay_portal_search_web_internal_custom_filter_portlet_CustomFilterPortlet_INSTANCE_' http://localhost:8080/api/jsonws/layout/update-layout
```

Expected Results: The custom filter widget is added to the page without issue

Actual Results: The widget is added but it is unavailable. Portlet is temporarily unavailable error is shown on the widget. This also happens for the Search Bar widget on the top right. Any search widget on this page will encounter this issue.The following error also appears in the console

```
java.lang.IllegalArgumentException: PortletPreferences is not present
	at com.liferay.portal.search.web.internal.custom.filter.portlet.CustomFilterPortletPreferencesImpl.lambda$new$0(CustomFilterPortletPreferencesImpl.java:36) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_362]
	at com.liferay.portal.search.web.internal.custom.filter.portlet.CustomFilterPortletPreferencesImpl.<init>(CustomFilterPortletPreferencesImpl.java:35) ~[?:?]
	at com.liferay.portal.search.web.internal.custom.filter.portlet.shared.search.CustomFilterPortletSharedSearchContributor.contribute(CustomFilterPortletSharedSearchContributor.java:49) ~[?:?]
	at com.liferay.portal.search.web.internal.portlet.shared.search.PortletSharedSearchRequestImpl.lambda$_getSearchSettingsContributor$3(PortletSharedSearchRequestImpl.java:248) ~[?:?]
	at com.liferay.portal.search.web.internal.search.request.SearchRequestImpl.lambda$_buildSettings$1(SearchRequestImpl.java:121) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_362]
	at com.liferay.portal.search.web.internal.search.request.SearchRequestImpl._buildSettings(SearchRequestImpl.java:120) ~[?:?]
```

Actual

**Pull request closed without merging**
