### PR TITLE
[Fix test] LPS-201113 Snapshot in IndexerRegistryUtil caused NPE in unit test

### PR DESCRIPTION
**Pull request by haydenzheng314**
Casued by: https://github.com/liferay-core-infra/liferay-portal/pull/6025
Ticket: https://liferay.atlassian.net/browse/LPS-201113
thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:stop

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
@zhangyan0701 Hi, could you please help to check this test? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

The test passed here.

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
