### PR TITLE
[Method References 2] LPS-171460 Convert method reference to ServiceTracker in class PortalInstanceLifecycleListenerManagerImpl(module portal-instance-lifecycle-impl)

### PR DESCRIPTION
**Pull request by W2jx**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/2846

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(1/3 8:56)

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(1/4 8:20)

**Comment by W2jx** [comment]
no conflicts(1/5 8:59)

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128465

**Pull request closed without merging**
