### PR TITLE
LPS-179797 | master

### PR DESCRIPTION
**Pull request by Kvale1733**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:friendly-url

**Comment by Kvale1733** [comment]
@tinatian No regressions found. The timezone issue is fixed. The issue in LPS-179797 also does not return.

**Comment by tinatian** [comment]
Rebase at https://github.com/liferay-core-infra/liferay-portal/pull/4185.

@yuhai the test you added can not expose the issue, please add a new test.

Thanks.
Tina

**Pull request closed without merging**
