### PR TITLE
[Remove Blocking Usages] LPS-187888 Removing Unnecessary Usages of ServiceProxyFactory.newServiceTrackedInstance with blocking set to true in class ViewCountManagerUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
no conflicts(10/26 9:11)

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(10/27 8:50)

**Comment by liuxingye** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(10/30 7:57)

**Comment by W2jx** [comment]
Hi @dantewang , this is a blocking one.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142971

cc @shuyangzhou

**Pull request closed without merging**
