### PR TITLE
[Replace Non-Blocking Usage] LPS-202330 Replace non-blocking ServiceProxyFactory usages in class StagingUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
