### PR TITLE
LPS-193246 Merge PortletDecoratorFactory logic into Util class in kernel

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
@julschong There is a conflict in portal-kernel/src/com/liferay/portal/kernel/model/packageinfo. Please resolve it and rerun relevant test.

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by julschong** [comment]
updated semver

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139843

**Pull request closed without merging**
