### PR TITLE
LPS-165867 Remove immediate from Solutions' modules

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by rafaprax** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:test:digital-signature

**Comment by rafaprax** [comment]
ci:test:click-to-chat

**Comment by rafaprax** [comment]
ci:test:site-initializer-raylife-d2c

**Comment by rafaprax** [comment]
ci:test:questions

**Comment by rafaprax** [comment]
ci:test:digital-signatue

**Comment by rafaprax** [comment]
ci:test:digital-signature

**Comment by Kvale1733** [comment]
ci:test:questions

**Comment by Kvale1733** [comment]
ci:test:site-initializer-raylife-d2c

**Comment by rafaprax** [comment]
Hey @shuyangzhou , this pr is ready for your review. Thx

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125071

**Pull request closed without merging**
