### PR TITLE
LPS-148923 Auto trigger ci tests for liferay-core-infra

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
FYI @vicnate5

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114473

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
