### PR TITLE
LPS-145500 Remove jakarta-regexp.jar

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by guilhermedcamacho** [comment]
Hey @vicnate5 , please help me scan test results. Thanks!

**Comment by vicnate5** [comment]
waiting on the test results to fully import into testray so I can do analysis

**Comment by vicnate5** [comment]
@guilhermedcamacho We don't have the full test results, CI team is trying to debug the issue

**Comment by vicnate5** [comment]
@guilhermedcamacho Test Results look good, this does need a rebase to resolve conflicts.

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Hey @shuyangzhou , this PR is ok for your review. Thanks!

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
