### PR TITLE
[Remove Stream/Optional usage] LPS-174298 Remove usages of Stream for module: portal-workflow-metrics-rest-spi

### PR DESCRIPTION
**Pull request by W2jx**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3250

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(2/17 10:32)

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130484

**Pull request closed without merging**
