### PR TITLE
LPS-185138 UpgradeRecorder

### PR DESCRIPTION
**Pull request by haydenzheng314**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4581
Ticket: https://issues.liferay.com/browse/LPS-185138
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by LisztLiszt** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@LisztLiszt No regressions found.

**Comment by dantewang** [comment]
@LisztLiszt Closing it here, please send to liferay-uniform for extra review.

**Comment by LisztLiszt** [comment]
See https://github.com/liferay-uniform/liferay-portal/pull/1212

**Pull request closed without merging**
