### PR TITLE
[Urgent][Security Bugs]LPD-19182 repatch freemarker 2.3.30 for 7.2/7.3 and patch freemarker 2.3.32 for master

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

As discussed, I basically doing two things in this PR:

1. since in 7.2/7.3, we are still using log4j1. therefore we need to remove the patch LPS-194731(replace log4j1 with log4j2) from freemarker patch 2.3.30, and make this for 7.3/7.2 uses only. Along I will also removed patch LPS-165250 and LPS-160230 as they are only needed in master
2.  For master, we bump the version to 2.3.32, which will keep all the necessary patch.

test to start up with the new patch in 7.2 and 7.3, and can successfully start up

Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:report:2545086213

**Comment by jeffwu0724** [comment]
https://testray.liferay.com/home/-/testray/case_results/2545092558/history

**Comment by jeffwu0724** [comment]
Fixed the commit messages, and didn't touch the code.
The previous test result is still valid.

**Comment by tinatian** [comment]
@jeffwu0724 Please see https://github.com/brianchandotcom/liferay-portal/pull/147721. Please note I merged these two commits https://github.com/liferay-core-infra/liferay-portal/pull/6708/commits/ce9d0a990901f820dbdfcdc724ec0386cb4ebaea and https://github.com/liferay-core-infra/liferay-portal/pull/6708/commits/768113e4be151d64cbcc10af669ba02fe21f921e

**Pull request closed without merging**
