### PR TITLE
[Remove Stream/Optional usage] LPS-175075 modules: data-engine-rest-impl, configuration-admin-web

### PR DESCRIPTION
**Pull request by JanisZhang**
previous: https://github.com/liferay-core-infra/liferay-portal/pull/3503
https://issues.liferay.com/browse/LPS-175075

Changes in this pull:  
• Use a for-loop instead of TransformUtil for better performance in https://github.com/liferay-core-infra/liferay-portal/commit/9b3dfbca6f084fef4d06fbfdc1bd58df907453a7
• Append 1 simplify commit, refer to https://github.com/brianchandotcom/liferay-portal/commit/2fb9a3f8eefa24ab7d98bb0b0be00ff071523c15

Thanks!

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:data-engine

**Comment by JanisZhang** [comment]
ci:test:usm

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@JanisZhang Regressions found. Repeatable nested fields are duplicated.

Steps to Reproduce
1. Go to Web Content > Structures
2. Click to Add structure
3. Add a text field
4. Add a numeric field nested into the text field
5. Add a date field nested into the numeric field
6. Click on the Field Group title and toggle repeatable
7. Save the Web Content Structure
8. Go to Web Content
9. Go to add Web Content using the created structure
10. Observe that all fields (text, numeric, date) are now duplicated (They should not be)
11. Duplicate the Field Group and Save
12. Click on the Web Content again and remove the duplicated field and save
13. Click on the Web Content again
14. Observe that additional fields have now been added

Expected Results: Fields aren't duplicated and duplicated field groups can be removed
Actual Results: Fields groups are duplicated and adding/removing duplicated field groups creates extra fields

I know it's hard to understand these steps so I added expected and actual videos so you can see what's going on

https://user-images.githubusercontent.com/90647688/223287620-c4ba8da5-0ee5-4746-9804-d8f73dfb36cb.mp4


https://user-images.githubusercontent.com/90647688/223287641-49d89ec3-8a7e-4980-868b-7dc7e695a1c3.mp4

**Comment by JanisZhang** [comment]
Thank you @Kvale1733, it's very clear!

**Pull request closed without merging**
