### PR TITLE
LPS-148634 - Poshi Automation for Bug | Legacy Repo

### PR DESCRIPTION
**Pull request by ozysouza**
https://issues.liferay.com/browse/LPS-148044

Hi @vicnate5, Would mind having a look in this PR? I'm creating the new legacy version for 7.1.0 GA1 to automate the bug on [LPS-148634](https://issues.liferay.com/browse/LPS-148044) that you requested to David.

cc @david-gutierrez-mesa 
cc @Tim-Cao 

Rebased from [#7441](https://github.com/liferay-echo/liferay-portal/pull/7441)

### CODE REVIEW

**Comment by Tim-Cao** [comment]
Hi @ozysouza, the commit message is still werid.

> LPS-148634 Updade build-test.xml file for new CE 7.1.0 GA1 legacy-ee version

Would you mind modifing?

**Comment by Tim-Cao** [comment]
ci:close

**Comment by ozysouza** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
Good job @ozysouza

**Comment by tinatian** [comment]
@vicnate5 Is this good go to?

Tina

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
