### PR TITLE
[Remove unused field] LPS-199177 Remove unused reference field in class ClientExtensionFDSFilterContextContributor

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:frontend-data-set

**Comment by W2jx** [comment]
no conflicts(10/17 8:23)

**Comment by W2jx** [comment]
no conflicts(10/20 8:52)

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
