### PR TITLE
LPS-144476 Remove jrcs-diff.jar

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by guilhermedcamacho** [comment]
Hey @koor4356 , can you also help me with the test results for this PR?

**Comment by koor4356** [comment]
ci:test

**Comment by koor4356** [comment]
@guilhermedcamacho,
We may need to rerun the ci test for this pr because results are missing. Also, I will be out tomorrow. Thanks!

**Comment by guilhermedcamacho** [comment]
> @guilhermedcamacho, We may need to rerun the ci test for this pr because results are missing. Also, I will be out tomorrow. Thanks!

Ok @koor4356 , thanks for your help.

Hey @zhangyan0701 , can you also help me with the test results for this PR (when it finished)? I will run ci:test again as Koor Gai suggested.

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by zhangyan0701** [comment]
Hi @guilhermedcamacho 

I have checked the test results, and there are no related failures.

**Comment by guilhermedcamacho** [comment]
> Hi @guilhermedcamacho
> 
> I have checked the test results, and there are no related failures.

Thanks for the prompt reply! :+1:

**Comment by tinatian** [comment]
@shuyangzhou This is good to go.

Thanks.
Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
