### PR TITLE
[Blocker]LPS-204659

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
Hi @tinatian , no unique failure found in upgrade test. thanks for taking over this.
https://test-1-1.liferay.com/job/generate-testray-csv/7511/

**Comment by JoyceWang08211** [comment]
ci:forward

**Pull request closed without merging**
