### PR TITLE
Lps 164886 10 6 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by Kvale1733** [comment]
@tinatian 

Semver error:
```
  [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/commerce/commerce-test-util] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.commerce.test.util.order.status        CHANGED    1.0.0      1.0.0      1.0.1      VERSION INCREASE REQUIRED
     [exec]     	~   class      com.liferay.commerce.test.util.order.status.Test1CommerceOrderStatusImpl
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   enabled=false
     [exec]     	~   class      com.liferay.commerce.test.util.order.status.Test2CommerceOrderStatusImpl
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   enabled=false
     [exec]     	~   class      com.liferay.commerce.test.util.order.status.Test3CommerceOrderStatusImpl
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   enabled=false
``` [Logs](https://testray.liferay.com/reports/production/logs/2022-10/test-1-39/test-portal-acceptance-pullrequest(master)/604/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0l)


modules-semantic-versioning-jdk8/0/0
```
 [echo] diff --git a/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-account-impl/src/main/java/com/liferay/headless/commerce/admin/account/internal/graphql/servlet/v1_0/ServletDataImpl.java b/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-account-impl/src/main/java/com/liferay/headless/commerce/admin/account/internal/graphql/servlet/v1_0/ServletDataImpl.java
     [echo] index eb9a8863d651..28d1d1d16c9c 100644
     [echo] --- a/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-account-impl/src/main/java/com/liferay/headless/commerce/admin/account/internal/graphql/servlet/v1_0/ServletDataImpl.java
     [echo] +++ b/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-account-impl/src/main/java/com/liferay/headless/commerce/admin/account/internal/graphql/servlet/v1_0/ServletDataImpl.java
     [echo] @@ -37,7 +37,7 @@ import org.osgi.service.component.annotations.ReferenceScope;
     [echo]   * @author Alessio Antonio Rendina
     [echo]   * @generated
     [echo]   */
     [echo] -@Component( immediate = true, service = ServletData.class)
     [echo] +@Component(immediate = true, service = ServletData.class)
     [echo]  @Generated("")
     [echo]  public class ServletDataImpl implements ServletData {
```[Logs](https://testray.liferay.com/reports/production/logs/2022-10/test-1-39/test-portal-acceptance-pullrequest(master)/605/rest-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@tinatian can you rebase, please? Thanks

**Pull request closed without merging**
