### PR TITLE
LPS-143632 Remove LanguageUtil from modules mixed 2

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@julschong all tests passed.

**Comment by catarineaguiar** [comment]
@julschong no regression found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121714

**Pull request closed without merging**
