### PR TITLE
[PowerMock] LPS 151993

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove powermock usages (Misc) part three.

After this PR, the portal will contain several (10+) powermock usages, which look hard to replace with the current Mockito version.  I have updated them in google docs.

https://issues.liferay.com/browse/LPS-151993

Thanks for checking.

### CODE REVIEW

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina.

**Comment by catarineaguiar** [comment]
@JanisZhang @tinatian no regressions found.

**Comment by JanisZhang** [comment]
Close. will resend, as conflicts with another pull.

**Comment by JanisZhang** [comment]
ci:close

**Pull request closed without merging**
