### PR TITLE
[Bug fix] LPS-145028 2022-1-12

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian I changed the unit test to focus on expose this exact issue.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@vicnate5 please help me checking the results, thanks!

**Comment by vicnate5** [comment]
@kyle-miho can you check this one?

**Comment by kyle-miho** [comment]
@shuyangzhou pr is good, failures are unrelated

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
