### PR TITLE
[Remove Stream/Optional usage] LPS-174911 Remove usages of Stream for module: portal-settings-authentication-ldap-web

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:security

**Comment by W2jx** [comment]
no conflicts(2/8 8:58)

**Comment by Kvale1733** [comment]
I know these are complicated steps but if you want you can run the test with
ant -f build-test.xml run-selenium-test -Dtest.class=SAML#CreateAndSyncUserAfterSAMLSetupMatchingemailAddressNameIDWithscreenNameAttribute

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(2/9 9:43)

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:security

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(2/13 13:10)

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3518

**Pull request closed without merging**
