### PR TITLE
[System Properties]LPS-158209 Replace method get all properties with method get all properties' key name

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I replace method get all properties with method get all properties' key name, in order to avoid getting unresolved property values.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@W2jx possible regression:

```
     [exec] com.liferay.asset.info.list.renderer.test.AssetInfoListRendererTest > testAssetInfoListRendererFullContent STARTED
[beanshell] 2022-10-11 12:29:59.587 ERROR [com.liferay.asset.test-executor-thread][BaseJSPAssetRenderer:75] Unable to include JSP /asset/full_content.jsp
[beanshell] org.apache.jasper.JasperException: java.lang.NullPointerException
[beanshell] 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:440) ~[jasper.jar:9.0.65]
[beanshell] 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473) ~[jasper.jar:9.0.65]
[beanshell] 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377) ~[jasper.jar:9.0.65]
[beanshell] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
[beanshell] 	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:328) ~[bundleFile:?]
[beanshell] 	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:340) ~[bundleFile:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-39/test-portal-acceptance-pullrequest(master)/905/modules-integration-mysql57-jdk8/0/6/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@W2jx That issue that catarine mentioned was passed in the most recent relevant run so it's not a regression. No regressions in this PR then.

**Review by dantewang — APPROVED** [review]

**Comment by W2jx** [comment]
Force-Push is just to resolve conflicts about semantic version.

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
Hi @catarineaguiar  , Could you please help me check the test results ? Thanks!

**Comment by tinatian** [comment]
@W2jx Please remove the "QA passed" tag so that your pull is going to be rescaned.

Tina

**Comment by tinatian** [comment]
@W2jx Please rebase.

Tina

**Comment by W2jx** [comment]
Force-Push is just to resolve conflicts about semantic version.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
rebase

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
No regressions found.

cc/ @zhangyan0701

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125362

**Pull request closed without merging**
