### PR TITLE
LPS-188903 upgrade Netty to 4.1.94

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This is for ticket https://liferay.atlassian.net/browse/LPS-188903.
Thanks for checking

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found. SF issue is unrelated.

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
