### PR TITLE
[Remove Stream/Optional usage] LPS-171453 modules Info

### PR DESCRIPTION
**Pull request by JanisZhang**
Remove usages of Stream on Method Return Value for module: `Info`.

https://issues.liferay.com/browse/LPS-171453

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found but sf is failing the same way https://github.com/liferay-core-infra/liferay-portal/pull/2785 is.

**Pull request closed without merging**
