### PR TITLE
LPS-154767 Remove jackson-databind.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:jdk11

**Comment by rafaprax** [comment]
Hey @catarineaguiar, can you please help me to scan these test results? Thx

**Comment by catarineaguiar** [comment]
Hi @rafaprax some regressions were found:

`SearchResponseResourceImplTest`, `FieldTest`, `ElementInstanceTest`, `SXPBlueprintSearchRequestEnhancerImplTest`, `SXPConditionEvaluatorTest`
```
com.liferay.search.experiences.rest.internal.resource.v1_0.SearchResponseResourceImplTest > testToSearchResponse FAILED
    java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
        at com.liferay.search.experiences.rest.dto.v1_0.SearchResponse.unsafeToDTO(SearchResponse.java:59)
        at com.liferay.search.experiences.rest.internal.resource.v1_0.SearchResponseResourceImpl.toSearchResponse(SearchResponseResourceImpl.java:169)
        at com.liferay.search.experiences.rest.internal.resource.v1_0.SearchResponseResourceImplTest.testToSearchResponse(SearchResponseResourceImplTest.java:361)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-26/test-portal-acceptance-pullrequest(master)/3269/modules-unit-jdk8/0/4/jenkins-console.txt.gz?authuser=0)

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:acceptance

**Comment by rafaprax** [comment]
ci:test:jdk11

**Comment by rafaprax** [comment]
Hey @catarineaguiar, can you please help me to scan these new test results? Thanks in advance

**Comment by rafaprax** [comment]
Hey @shuyangzhou, this pr is ready for your review. Thx

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/118291

**Pull request closed without merging**
