### PR TITLE
LPS-178022 Cleanup CustomFacet for optional removal

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:search

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@julschong Regressions found. 

1 ) Compile issue
```
 [exec] > Task :apps:portal-search:portal-search-web:generateJSPJava
     [exec] Compiling JSP files of project ':apps:portal-search:portal-search-web' with /opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.73/webapps/ROOT/WEB-INF/shielded-container-lib/util-taglib.jar as dependency in place of 'com.liferay.portal:com.liferay.util.taglib'
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-search/portal-search-web/build/jspc/org/apache/jsp/custom/facet/configuration_jsp.java:175: error: incompatible types: no instance(s) of type variable(s) T exist so that java.util.Optional<T> conforms to javax.portlet.PortletPreferences
     [exec] CustomFacetPortletPreferences customFacetPortletPreferences = new CustomFacetPortletPreferencesImpl(java.util.Optional.of(portletPreferences));
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-39/test-portal-acceptance-pullrequest(master)/4343/modules-compile-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

2 ) Cannot configure custom facet widget. Looks related to the first issue as it throws similar errors.

Steps to reproduce
1. Add a custom facet widget to a page
2. Hover over the widget, click on the blue ellipses on the far right of it, and click configuration

Expected Results: Can configure the custom facet widget in the Setup tab
Actual Results: The setup tab is selected but there is nothing to configure, just blank space. The following also appears in the console

```
    [exec] 
[beanshell] 2023-04-20 19:42:42.558 ERROR [http-nio-8080-exec-5][BaseJSPSettingsConfigurationAction:86] Unable to include JSP /custom/facet/configuration.jsp
[beanshell] org.apache.jasper.JasperException: PWC6033: Error in Javac compilation for JSP
[beanshell] 
[beanshell] PWC6197: An error occurred at line: 41 in the jsp file: /custom/facet/configuration.jsp
[beanshell] PWC6199: Generated servlet error:
[beanshell] incompatible types: no instance(s) of type variable(s) T exist so that java.util.Optional<T> conforms to javax.portlet.PortletPreferences
[beanshell] 
[beanshell] PWC6199: Generated servlet error:
[beanshell] Some messages have been simplified; recompile with -Xdiags:verbose to get full output
[beanshell] 
[beanshell] 
[beanshell] 	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:129) ~[javax.servlet.jsp-2.3.3-b02.LIFERAY-PATCHED-9.jar:9.0.73]
[beanshell] 	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:299) ~[javax.servlet.jsp-2.3.3-b02.LIFERAY-PATCHED-9.jar:9.0.73]
[beanshell] 	at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:392) ~[javax.servlet.jsp-2.3.3-b02.LIFERAY-PATCHED-9.jar:9.0.73]
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-25/test-portal-acceptance-pullrequest(master)/580/functional-tomcat90-mysql57-jdk8/2/4/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4325

**Pull request closed without merging**
