### PR TITLE
[JDK17] LPD-44071 Fix release tool

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:license

**Comment by dantewang** [comment]
We need to also trigger a JDK17 run like https://github.com/jeffwu0724/liferay-portal/pull/584. cc @vicnate5

**Comment by jeffwu0724** [comment]
Hi @dantewang ,
I have trigger the test on JDK 17, please see https://github.com/jeffwu0724/liferay-portal/pull/586#issuecomment-2559914378
cc: @tinatian

**Comment by jeffwu0724** [comment]
Hi @dantewang , @tinatian 
The test on jdk 17 compile has passed the test, please see https://github.com/jeffwu0724/liferay-portal/pull/586

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-release-tool-ee/pull/90

**Pull request closed without merging**
