### PR TITLE
LPS-149460 Move petra-model-adapter to apps/portal-utilities

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,

Resubmitted from #534 after removing .util from the package name

Main Task: [LPS-147928 Remove petra jar from modules/apps](https://issues.liferay.com/browse/LPS-147928)
Sub Task: [LPS-149460 Move petra-model-adapter to apps/portal-utilities](https://issues.liferay.com/browse/LPS-149460)

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
@kyle-miho 
Hi Kyle, 
Could you please help me scan this test result?
Thank you

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
rerunning tests @julschong i suspect these failures were a fluke

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Pull request closed without merging**
