### PR TITLE
LPS-168539 Use BundleUtil.getBundle method instead of repeating its code again and again

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-168539

@dantewang @tinatian previous PR https://github.com/liferay-core-infra/liferay-portal/pull/3332

After implementing the test for [LPS-166969](https://issues.liferay.com/browse/LPS-166969) (see https://github.com/liferay-search/liferay-portal/pull/626) I have realized that we are repeating the BundleUtil.getBundle method code everywhere.

This PR is similar to previous one, but I am avoiding removing the existing tests Assert.assertNotNull and the IllegalStateException throwing logic.

In my previous PR I removed that code, because the `BundleUtil.getBundle` method was throwing an IllegalStateException instead of a null pointer when the bundle didn't exist.

To maintain previous code unmodified, I have extracted the IllegalStateException code from BundleUtil.getBundle so the caller can check the return value and throw the exception there if necessary. See commit e67ca5e265ccea0d2e5b05c4fc648d39eee40327

Let me know if you have any question

### CODE REVIEW

**Comment by Kvale1733** [comment]
@jorgediaz-lr Regression found. There is a compile issue in BundleBlacklistTest.java
```
[exec] /opt/dev/projects/github/liferay-portal/modules/apps/static/portal-bundle-blacklist/portal-bundle-blacklist-test/src/testIntegration/java/com/liferay/portal/bundle/blacklist/test/BundleBlacklistTest.java:348: error: unreachable statement
     [exec] 		throw new IllegalArgumentException(
     [exec] 		^
     [exec] 1 error
     [exec] > Task :apps:static:portal-lpkg-deployer:portal-lpkg-deployer-test-util:jar
     [exec] 
     [exec] > Task :apps:static:portal-bundle-blacklist:portal-bundle-blacklist-test:compileTestIntegrationJava FAILED
     [exec] 
     [exec] > Task :apps:static:portal-bundle-blacklist:portal-bundle-blacklist-test:processTestIntegrationResources NO-SOURCE
     [exec] > Task :apps:static:portal-lpkg-deployer:portal-lpkg-deployer-test-util:autoUpdateXml SKIPPED
```
[Log](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/326754//consoleText)

**Comment by jorgediaz-lr** [comment]
Hi @Kvale1733 

I have fixed the  problem in the `BundleBlacklistTest` class.

I have also rebased the code changes to avoid a code conflict in `KBArticleMarkdownConverterTest`.

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @Kvale1733 @dantewang @tinatian  

I have rebased this pull request to avoid some conflicts with 

- modules/apps/portal/portal-spring-extender-impl/src/main/java/com/liferay/portal/spring/extender/internal/configuration/PortletConfigurationExtender.java
- portal-impl/bnd.bnd
- portal-kernel/bnd.bnd

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/135848

**Pull request closed without merging**
