### PR TITLE
LPD-30984 fix clustering functional test that using 8080 in User.loginPG

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

Resent: https://github.com/liferay-core-infra/liferay-portal/pull/7267
The failures mentioned in https://liferay.atlassian.net/browse/LPD-32320 last time is becuase we create the creatorEmailAddress with a non-admin userEmailAddress, which led lots of JSON API failed because this userEmailAddress cannot access the JSON API.
In my last commit, I changed to enforce to use "[test@XXX.com](mailto:test@XXX.com)" to make sure we are using the admin credential for the JSON API.

Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:acceptance-functional

**Comment by jeffwu0724** [comment]
ci:test:clustering

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hi @vicnate5 ,

The previous PR caused issue like https://liferay.atlassian.net/browse/LPD-32320.
May I ask beside `ci:test:acceptance-functional` and `ci:test:clustering`, do we need to run more test to make sure it is safe?

Thanks,
Jeff

**Comment by vicnate5** [comment]
@jeffwu0724 based on the links in the ticket, `acceptance-functional` and `analytics-cloud-acceptance` will cover you.

**Comment by jeffwu0724** [comment]
Thanks! @vicnate5

**Comment by jeffwu0724** [comment]
ci:test:analytics-cloud-acceptance

**Comment by jeffwu0724** [comment]
ci:test:analytics-cloud-acceptance

**Comment by jeffwu0724** [comment]
ci:report:52268758

**Comment by jeffwu0724** [comment]
ci:report:52462387

**Comment by jeffwu0724** [comment]
ci:report:53548834

**Comment by jeffwu0724** [comment]
[analytics-cloud-acceptance](https://github.com/liferay-core-infra/liferay-portal/pull/7313#issuecomment-2269641941)
no unique regression found
[acceptance-functional](https://github.com/liferay-core-infra/liferay-portal/pull/7313#issuecomment-2269336811)
https://testray.liferay.com/#/project/34754/routines/34756/build/52462387/case-result/52473136/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/52462387/case-result/52483489/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/52462387/case-result/52485646/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/52462387/case-result/52496691/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/52462387/case-result/52502874/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/52462387/case-result/52505459/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/52462387/case-result/52505659/history -- not unique

https://testray.liferay.com/#/project/34754/routines/34756/build/52462387/case-result/52479157/history 
https://testray.liferay.com/#/project/34754/routines/34756/build/52462387/case-result/52491262/history

[clustering](https://github.com/liferay-core-infra/liferay-portal/pull/7313#issuecomment-2266228909)
No unique regression found, but doubt https://testray.liferay.com/#/project/34754/routines/34756/build/52268758/case-result/52277795/history

**Comment by jeffwu0724** [comment]
ci:test:acceptance-functional

**Comment by jeffwu0724** [comment]
ci:report:53877795

**Pull request closed without merging**
