### PR TITLE
[Replace Non-Blocking Usage] LPS-202552 Replace non-blocking ServiceProxyFactory usages in class OrganizationMembershipPolicyFactoryImpl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
no conflicts(11/27 9:10)

**Comment by zhangyan0701** [comment]
ci:test:startup

**Comment by W2jx** [comment]
no conflicts(11/28 10:07)

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/144555

cc @tinatian

**Pull request closed without merging**
