### PR TITLE
LPS-145946 Remove xalan.jar

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This is good to go.

Tina

**Comment by shuyangzhou** [comment]
@dantewang @tinatian rebase conflict, please resend.

**Comment by tinatian** [comment]
@shuyangzhou Rebased, good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113225

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
