### PR TITLE
[Rename Classes] LPS-166960 Rename classes in modules info-api、info-impl、layout-content-page-editor-web、layout-admin-web、layout-content-page-editor-web、layout-taglib

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@W2jx 

Semver error:
```
[exec] > Task :apps:asset:asset-display-page-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.asset.display.page.portlet             MAJOR      4.3.0      4.3.0      5.0.0      VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.asset.display.page.portlet.BaseAssetDisplayPageFriendlyURLResolver
     [exec] 		+   field      infoItemServiceRegistry
     [exec] 			+   access     protected
     [exec] 			+   annotated  org.osgi.service.component.annotations.Reference
     [exec] 			+   return     com.liferay.info.item.InfoItemServiceRegistry
     [exec] 		-   field      infoItemServiceTracker
     [exec] 			-   access     protected
     [exec] 			-   annotated  org.osgi.service.component.annotations.Reference
     [exec] 			-   return     com.liferay.info.item.InfoItemServiceTracker
     [exec] 		+   field      infoSearchClassMapperRegistry
     [exec] 			+   access     protected
     [exec] 			+   annotated  org.osgi.service.component.annotations.Reference
     [exec] 			+   return     com.liferay.info.search.InfoSearchClassMapperRegistry
     [exec] 		-   field      infoSearchClassMapperTracker
     [exec] 			-   access     protected
     [exec] 			-   annotated  org.osgi.service.component.annotations.Reference
     [exec] 			-   return     com.liferay.info.search.InfoSearchClassMapperTracker
     [exec] [Baseline Warning] Bundle Version Change Recommended: 10.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
  ```
  [Logs](https://testray.liferay.com/reports/production/logs/2022-11/test-1-32/test-portal-acceptance-pullrequest(master)/6401/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
Force-Push is just to fix the Semver error.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
will fix conflicts and resend

**Pull request closed without merging**
