### PR TITLE
[TS]LPS-19090

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 Please verify if https://issues.liferay.com/browse/LPS-19981 if fixed with this pull.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@zhangyan0701 can you test this one? Not sure if https://issues.liferay.com/browse/LPS-19090 and https://issues.liferay.com/browse/LPS-19981 are the same.

**Comment by zhangyan0701** [comment]
@tinatian @vicnate5 

I tested https://issues.liferay.com/browse/LPS-19090 and https://issues.liferay.com/browse/LPS-19981. Both are fixed with this pull.

**Comment by vicnate5** [comment]
No regressions in test results

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130648

**Pull request closed without merging**
