### PR TITLE
LPS-143631 Avoid using JSONFactoryUtil directly in modules

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina, Shuyang

Resent from #731

Main Task: [LPS-143403](https://issues.liferay.com/browse/LPS-143403)
Sub Task: [LPS-143631](https://issues.liferay.com/browse/LPS-143631)

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
updated ValidateRankingMVCResourceCommandTest to use dummy _jsonFactory

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:acceptance

**Comment by julschong** [comment]
force pushed changes to publish `AssetEntriesSearchFacet` so that service reference can be found

**Comment by julschong** [comment]
forced push SF

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@catarineaguiar Hi Caterine, could you please help me review this PR?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong most tests were aborted, so I need to re-run the ci:test:default to analyze your PR

**Comment by catarineaguiar** [comment]
ci:test:default

**Comment by catarineaguiar** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by julschong** [comment]
@tinatian Hi Tina, Could you please help see if this PR is ready to go again?
Thank you!

**Comment by julschong** [comment]
forced pushed to avoid adding impl test dependency

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine, I changed something minor, but could you please help me scan again just in case?
Thank you!

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/793

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
