### PR TITLE
[Component with its own class name as service type] LPS-200169 Refactor Components from Faro module

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-200169

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud-acceptance

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by vicnate5** [comment]
ci:test:analytics-cloud-acceptance

**Comment by vicnate5** [comment]
@christianstokes how can we run the AC tests here?

**Comment by catarineaguiar** [comment]
Hey @ViniLopes20, could you take a look at this pull when you have time, please?

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Pull request closed without merging**
