### PR TITLE
LPD-29412 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:core-functional

**Comment by tinatian** [comment]
@JerryAdrianoo Please help me verify startup performance

**Comment by JerryAdrianoo** [comment]
Hey @tinatian see the result below

Branch| Startup Time (ms)(without  default HSQL data)  Cold start | Percent of Average Startup Time Cold Start | Startup Time (ms)(without  default HSQL data) Hot start | Average Startup Time (ms)(without default HSQL data)  Hot start | Percent of Average Startup Time Hot Start | Shutdown Time (ms)(without default HSQL data)   Cold start | Shutdown Time (ms)(without default HSQL data)  Hot start | Average Shutdown Time (ms)(without default HSQL data)  Hot start
-- | -- | -- | -- | -- | -- | -- | -- | --
Before LPD-29412 | **41,769** | | 16,111 | | | **2,654** | 1,918
|  | | | 16,526 | | | | 1,972
|  | | | 15,976 | | | | 1,994
 | | | | 16,762 | | | | 2,051
 | | | | 16,638 |**16,425** | | | 2,042 | **2,003**
-- | -- | -- | -- | -- | -- | -- | --
After LPD-29412 | **42,365** | | 17,138 | | | **2,521** | 1,941
|  | | | 16,092 | | | | 1,954
|  | | | 16,552 | | | | 2,006
|  | | | 16,111 | | | | 1,961
| | |  1.43% | 16,538 |**16,400** |  **-0.15**% | | 1,894 | **1,952**

Everything looks ok, I didn't see any regression with these changes. The variation shown on the test is expected.

**Comment by victorhcunha** [comment]
Hi @tinatian !
Here are the results for login test case:

Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
Master Baseline | 105f946 | 10918 | - | 264 | 2,2,2 | 95,93,95
PR | - | 11146 | 2.088294559 | 281 | 2,2,2 | 95,92,95

No regression detected. More details you can see in our [spreadsheet](https://docs.google.com/spreadsheets/d/1JqJn5vxyGRHejAWejEVAtSDpVdbemYdqCDQGLBLzpGg/edit?gid=1337639341#gid=1337639341). If you want more rounds of testing, please let me know.

**Comment by kevhlee** [comment]
Hi @tinatian! Unfortunately, I am seeing some issues after manually testing the changes from this PR. I am still able to reproduce the bug in [LPD-29412](https://liferay.atlassian.net/browse/LPD-29412). Additionally, the portal no longer uses the language translations from the custom module (i.e. the `Language.properties` files) and the default language translation is shown no what language is selected.

Please see the clip below (note that the custom module is supposed to have language translations for `fr_FR`).

https://github.com/liferay-core-infra/liferay-portal/assets/21070577/0007df23-f0c1-40db-87d8-e5c00bb4b8f5

**Pull request closed without merging**
