### PR TITLE
LPS-163832 Custom fields are not being returned when creating a system object from the API

### PR DESCRIPTION
**Pull request by ccorreagg**
The details in the jira ticket: https://issues.liferay.com/browse/LPS-163832

### CODE REVIEW

**Comment by ccorreagg** [comment]
cc/ @rafaprax

**Comment by dantewang** [comment]
@ccorreagg Thanks for sending the PR! We may need to be very careful on this because `FinderCache` is widely used, but here a method only used by Objects for now is added to it.

I'd like to get some clarification about:

1. The first commit says "cache based on the class name (there are some caches that are not classes)", could you give an example? Basically `EntityCache` and `FinderCache` are associated with database entities.
2. Could you provide an integration test to expose this issue?

cc @rafaprax @tinatian

**Comment by ccorreagg** [comment]
Hi @dantewang ,

Maybe someone from Objects team could provide more info about the first point, but for every object in the portal, a db table is created for the many to many relationships and for the system objects fields, see the example please for the AccountEntry system object:

image

for that case, even though there is a database entity called AccountEntry (and there is a DTO class name), there is no class for the new table, and that cache should be clear in some cases

**Comment by gabrielwas** [comment]
you're right @ccorreagg. These "side tables" don't have any call or entity associated with them.

cc @guilhermedcamacho

**Comment by dantewang** [comment]
@ccorreagg By the way, could you update the ticket with precise steps to reproduce? Currently is unclear to us how to "Create a field in a system object, for example, the field "textField" into Account system object". I tried to enable the feature flag, add a custom field, but the command returns "unknown property" error.

This is why we prefer an integration test though.

**Comment by gabrielwas** [comment]
@dantewang just did it

**Comment by ccorreagg** [comment]
> @dantewang just did it

Thanks @gabrielwas for updating the issue, sorry for not incuding all the steps clearly

**Comment by tinatian** [comment]
@ccorreagg @gabrielwas 
As you are modifying cache framework which is going to affected by all the usages, please provide detailed reason for "[LPS-163832 Clear cache instead of only DSL Query cache]".

Please add integration test to show the issue.

Thanks.
Tina.

**Pull request closed without merging**
