### PR TITLE
[Replace Non-Blocking Usage] LPS-200634 followup

### PR DESCRIPTION
**Pull request by JanisZhang**
https://liferay.atlassian.net/browse/LPS-200634

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
@JanisZhang possible regression:

```
[beanshell]      [exec] com.liferay.journal.service.test.JournalArticleLocalServiceTest > testArticleFriendlyURLValidationCompanyGroup FAILED
[beanshell]      [exec]     java.lang.IllegalStateException: No portlet bag for {"mvccVersion": 0, "id": 0, "companyId": 20095, "portletId": "com_liferay_commerce_subscription_web_internal_portlet_CommerceSubscriptionEntryPortlet", "roles": "", "active": true}
[beanshell]      [exec]     	at com.liferay.portal.model.impl.PortletImpl.getPortletDataHandlerInstance(PortletImpl.java:1376)
[beanshell]      [exec]     	at com.liferay.portal.service.impl.GroupLocalServiceImpl.getPortletDataHandlers(GroupLocalServiceImpl.java:4506)
[beanshell]      [exec]     	at com.liferay.portal.service.impl.GroupLocalServiceImpl.addPortletDefaultData(GroupLocalServiceImpl.java:4112)
[beanshell]      [exec]     	at com.liferay.portal.service.impl.GroupLocalServiceImpl.addGroup(GroupLocalServiceImpl.java:528)
[beanshell]      [exec]     	at com.liferay.portal.service.impl.GroupLocalServiceImpl.addGroup(GroupLocalServiceImpl.java:543)
[beanshell]      [exec]     	at sun.reflect.GeneratedMethodAccessor3971.invoke(Unknown Source)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-26/test-portal-acceptance-pullrequest(master)/11835/modules-integration-mysql57-jdk8/2/11/jenkins-console.txt.gz?authuser=0)

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
Hi @catarineaguiar , I didn't reproduce this regression, and I rerun the tests, would you help to double-check it? thx.

**Comment by catarineaguiar** [comment]
hey @JanisZhang, it doesn't look related indeed. But there's a regression when try to add a new page.

steps to reproduce:

1. start portal
2. go to product menu > site builder > pages
3. Click to add a blank page > put a name > add

Actual result
The page is not created and it get stuck. No log errors.

Expected result
The new page is created with no errors and a success alert is shown

**Comment by JanisZhang** [comment]
@catarineaguiar Thanks, Cat.  I'll double-check it.

**Pull request closed without merging**
