### PR TITLE
[Remove immedaite=true usage from all these ServletContextUtil ]Lps 170188

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-170188

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:tes:startup

**Comment by slnn** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Comment by Kvale1733** [comment]
@slnn Sorry that was a mistake.

**Comment by dantewang** [comment]
@slnn Since we are going to convert method references in util classes and make the utils non-component, I'm going to close this PR.

**Pull request closed without merging**
