### PR TITLE
[Static reference] LPS-170377 Remove method reference by using snapshot in modules headless-builder-impl, knowledge-base

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:lima

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(4/7 16:38)

**Comment by W2jx** [comment]
no conflicts(4/10 8:33)

**Comment by W2jx** [comment]
no conflicts(4/11 9:50)

**Comment by W2jx** [comment]
will resend, as https://liferay.slack.com/archives/C0421NBHFKP/p1681181395336159

**Pull request closed without merging**
