### PR TITLE
[Remove blocking usages] LPS-196123 Move DLPreviewableProcessor

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5951

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:echo

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
Hi @zhangyan0701 , I have fixed the errors in my code. But it seems that the test class also has issues on the master

**Comment by W2jx** [comment]
no conflicts(11/3 9:19)

**Comment by zhangyan0701** [comment]
No regressions found.

The test in https://github.com/liferay-core-infra/liferay-portal/pull/5951#issuecomment-1788490463 passed here.

**Comment by W2jx** [comment]
Forced push to resolve the conflict about bnd file, no logic changes.

**Review by dantewang — APPROVED** [review]

**Comment by W2jx** [comment]
no conflicts(11/7 9:34)

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143422

**Pull request closed without merging**
