### PR TITLE
LPS-182384 move portal-upload to modules part One

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This is part One of moving portal-upload to modules. As we talked, in this part we only trying to avoid using uploadservletrequestimpl and uploadportletrequestimpl directly by using factory.
Thanks for checking

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:stable

**Comment by jeffwu0724** [comment]
ci:stop

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @liuxingye ,
Thanks for taking care of this PR for me. I found some regression in this PR, and I have forced push and retrigger the test.
Thanks for checking it for me later!

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:sf

**Pull request closed without merging**
