### PR TITLE
remove_deprecated_for_portal_kernel_part_Eight

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

I have removed the deprecated for
"setMailSession()" and its usage
"ListUtil.java"
"MapUtil.java"
"OSDetector.java"
"ResourceBundleLoader.java"
"ServerDetector.java"
"SubscriptionSender.java"
"WebKeys.java"
"DefaultWorkflowInstance.java"
"getURLEditWorkflowTask()"
"ClassResourceBundleLoader.java"
and eight deprecated classes
Thanks for checking. Also see https://github.com/jeffwu0724/liferay-portal/pull/47

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by kyle-miho** [comment]
@jeffwu0724 @tinatian can you guys rebase the core-infra branch? I can't tell if the failures are unique since there are are extra commits in this that could be causing the failures

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test

**Comment by kyle-miho** [comment]
@catarineaguiar can you take a look at this pr?
cc: @vicnate5

**Comment by tinatian** [comment]
@jeffwu0724 Please remove the reference of **com.liferay.portal.kernel.util.ResourceBundleLoader** here
`modules/util/source-formatter/documentation/resource_bundle.markdown:`com.liferay.portal.kernel.util.ResourceBundleLoader.loadResourceBundle`.
modules/util/source-formatter/src/main/resources/documentation/check/resource_bundle_check.markdown:`com.liferay.portal.kernel.util.ResourceBundleLoader.loadResourceBundle`.
`

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by vicnate5** [comment]
@catarineaguiar Can you check this one?

**Comment by tinatian** [comment]
@jeffwu0724 Code conflicts, please rebase.

Tina.

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar can you help me check this pr, please?
cc: @vicnate5

**Comment by catarineaguiar** [comment]
Hi @jeffwu0724, did you fix the formatting issues?

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions were found.

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar , it passed the SF test now, but seems like this SF failure does not come from my code though.

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115997

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
