### PR TITLE
LPS-195588 Merge CommonPermission interface and impl into Util in kernel

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from https://github.com/liferay-core-infra/liferay-portal/pull/5504

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:headless

**Comment by julschong** [comment]
ci:test:headless

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
No regressions found. SF issue is not related.

Let's wait for stable results.

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
changes removed from TemplateContextHelper variable name

**Comment by julschong** [comment]
rebased

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
@shuyangzhou this one is moved to portal-impl

**Comment by julschong** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@julschong Only issue here is semver
```
     [echo] ##
     [echo] ## /opt/dev/projects/github/liferay-portal/baseline-reports/portal-impl.log
     [echo] ##
     [echo] 
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.service.permission              MAJOR      6.0.0      6.0.0      7.0.0      VERSION INCREASE REQUIRED
...
     [echo] 
     [echo] ##
     [echo] ## /opt/dev/projects/github/liferay-portal/baseline-reports/portal-kernel.log
     [echo] ##
     [echo] 
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.kernel.service.permission       MAJOR      7.0.0      7.0.0      8.0.0      VERSION INCREASE REQUIRED
```

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
No regressions found, not sure what is going on with the SF, since those changes aren't related.

**Comment by shuyangzhou** [comment]
@julschong please rebase.

**Pull request closed without merging**
