### PR TITLE
LRQA-81055 Same as LPS-138761, solves a race condition that Data Guard detects as orphan data that should not be considered orphan data

### PR DESCRIPTION
**Pull request by kyle-miho**
https://liferay.atlassian.net/browse/LRQA-81055

### CODE REVIEW

**Comment by kyle-miho** [comment]
No need to analyze results, this cannot cause regressions as it is just a test fix for a race condition on CI.

**Comment by kyle-miho** [comment]
@rafaprax do you mind taking a look at this?

**Comment by kyle-miho** [comment]
I confirmed with Jorge with this, and he approved of this method

**Comment by tinatian** [comment]
ci:forward:force

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137568

**Pull request closed without merging**
