### PR TITLE
LPS-151745 Add LIFERAY_SHARED_ prefix to attribute name in order to propagate the check access allowed to the portlet until the PortletFragmentEntryProcessor

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-151745

Previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/891

Hi @tinatian

Thanks for your feedback!

Could you please review this pull request?

Thank you very much ❤️

### CODE REVIEW

**Comment by dantewang** [comment]
@lfbesada Although Github does not show a code conflict, please rebase and rebuild to make sure the packageinfo and bnd.bnd files are up-to-date. When I rebase I see your last commit (https://github.com/liferay-core-infra/liferay-portal/pull/937/commits/b5dc7b28ba01a3b515bd1c5c0154080da8e5efb3) being dropped because the content is identical with master.

**Comment by dantewang** [comment]
@tinatian Based on your previous comments, this PR looks good to me.

**Comment by dantewang** [comment]
@lfbesada I'll close this one, please resend a rebased PR, thanks!

**Comment by dantewang** [comment]
ci:close

**Comment by lfbesada** [comment]
Hi @dantewang,
For me, the commit has also been deleted when rebasing. I have built the branch several times, both rebasing using the Liferay repo and Brian's repo and it does not generate any change.
I can send this pull request again, but it will be exactly the same as this one.
What should you do?
Thank you very much, regards

**Comment by dantewang** [comment]
@lfbesada Thanks! I will reopen this one.

**Comment by dantewang** [comment]
ci:reopen

**Comment by lfbesada** [comment]
Resent : https://github.com/liferay-core-infra/liferay-portal/pull/958

**Comment by lfbesada** [comment]
Thanks, @dantewang I closed the other pull request

**Comment by lfbesada** [comment]
Hi @dantewang 
I am sorry because of my confusion. I have sent a pull request using a new branch.
Please see https://github.com/liferay-core-infra/liferay-portal/pull/959
Thanks, regards

**Pull request closed without merging**
