### PR TITLE
LPS-172054 Remove "immediate = true" from Staging part 2

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:staging

**Comment by catarineaguiar** [comment]
ci:test:staging

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
@RenanUmV semver error:

```
  [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/export-import/export-import-test-util] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.exportimport.test.util.exportimport.data.handler CHANGED    3.0.0      3.0.0      3.0.1      VERSION INCREASE REQUIRED
     [exec]     	~   class      com.liferay.exportimport.test.util.exportimport.data.handler.DummyFolderPortletDataHandler
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   immediate=true
     [exec]     	~   class      com.liferay.exportimport.test.util.exportimport.data.handler.DummyFolderStagedModelDataHandler
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   immediate=true
     [exec]     	~   class      com.liferay.exportimport.test.util.exportimport.data.handler.DummyFolderWithMissingDummyPortletDataHandler
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   immediate=true
     [exec]     	~   class      com.liferay.exportimport.test.util.exportimport.data.handler.DummyFolderWithMissingLayoutPortletDataHandler
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   immediate=true
     [exec]     	~   class      com.liferay.exportimport.test.util.exportimport.data.handler.DummyReferenceStagedModelDataHandler
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   immediate=true
     [exec]     	~   class      com.liferay.exportimport.test.util.exportimport.data.handler.DummyStagedModelDataHandler
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   immediate=true
     [exec]         at org.junit.Assert.fail(Assert.java:88)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-26/test-portal-acceptance-pullrequest(master)/6723/modules-semantic-versioning-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
Hey @tinatian , this one is ready to go!

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128885

**Pull request closed without merging**
