### PR TITLE
[Optional Reference] LPS-185137 Convert the Optional Dynamic Greedy references to hard reference in module dynamic-data-lists-web

### PR DESCRIPTION
**Pull request by W2jx**
resend, use hard reference

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4585

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
@W2jx No regressions.

**Comment by W2jx** [comment]
no conflicts(5/31 9:42)

**Comment by W2jx** [comment]
no conflicts(6/2 8:25)

**Comment by W2jx** [comment]
no conflicts(6/5 7:43)

**Review by dantewang — APPROVED** [review]

**Pull request closed without merging**
