### PR TITLE
[SampleSQLBuilder-update-searchbar]Lps 203324

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-203324

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
@slnn Change to QA passed. It should be a flaky.

**Comment by dantewang** [comment]
ci:forward

cc @tinatian

**Pull request closed without merging**
