### PR TITLE
LPS-168539 Apply BundleUtil.getBundle usage (Additional commit)

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-168539

Additional commit to already merged pull request: https://github.com/brianchandotcom/liferay-portal/pull/135848

In previous PR https://github.com/brianchandotcom/liferay-portal/pull/135848 I applied `BundleUtil.getBundle` method everywhere in the portal, to avoid repeating the same code.

I have detected that the same code could be replaced by BundleUtil.getBundle in two more java classes: HeadlessDiscoveryAPIApplication.java and MissingComponentUtil.java.

This PR is just applying same change that previous PR in these two java classes

Thank you,
Jorge

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@jorgediaz-lr No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian Forwarding as this is additional change to a previously merged pull.

**Pull request closed without merging**
