### PR TITLE
LPD-36137 move portal-encryptor to static

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This is for https://liferay.atlassian.net/browse/LPP-55525.
I can reproduce this issue with the [latest release bundle 2024.q2.12](https://files.liferay.com/private/ee/portal/2024.q2.12/liferay-dxp-tomcat-2024.q2.12-1725282088.tar.gz) by following the reproduce step in the ticket.

How I check if the fix works:
1. In my local 2024.q2.12 branch, set `app.server.parent.dir=/home/jeffwu/Downloads/liferay-dxp-tomcat-2024.q2.12-1725282088/liferay-dxp/`, run `ant all` with my changes
2. In a clean `liferay-dxp-tomcat-2024.q2.12-1725282088/liferay-dxp`, make sure we have `com.liferay.portal.encryptor` in `osgi/static` instead of `osgi/portal`
3. Startup bundle of `liferay-dxp-tomcat-2024.q2.12-1725282088/liferay-dxp`
4. Deploy attached license
5. Deploy attached Liferay Commerce Connector to PunchOut2Go lpkg
6. Confirm license & lpkg deployed successfully
7. Restart server (do not clear any files or make any changes) & observe there are no errors
8. Shutdown the server & clear osgi/state
9. Restart server, also no error found

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:help

**Comment by jeffwu0724** [comment]
ci:test:startup

**Comment by jeffwu0724** [comment]
ci:report:9604941

**Comment by jeffwu0724** [comment]
ci:report:9816092

**Comment by jeffwu0724** [comment]
[startup](https://github.com/liferay-core-infra/liferay-portal/pull/7420#issuecomment-2346599157):
https://testray.liferay.com/#/project/35392/routines/45357/build/9816092/case-result/9816941/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/9816092/case-result/9817033/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/9816092/case-result/9817206/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/9816092/case-result/9817770/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/9816092/case-result/9817972/history -- flaky

relevant:
https://testray.liferay.com/#/project/35392/routines/45357/build/9604941/case-result/9631303/history -- need to dive deeper
https://testray.liferay.com/#/project/35392/routines/45357/build/9604941/case-result/9630707/history -- need to dive deeper
https://testray.liferay.com/#/project/35392/routines/45357/build/9604941/case-result/9632323/history -- need to dive deeper

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:report:10438015

**Comment by jeffwu0724** [comment]
no unique regresssion found at the second run

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
