### PR TITLE
[TS] LPS-201632

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@marianoalvarosaiz No regressions found. Testing passed using the modified test service.

**Comment by tinatian** [comment]
@marianoalvarosaiz 
1. Can you fix the issue on current code rather than revert? You can just return a registration from the customizer when addingBundle, unregister it when removedBundle
2. Please also add portlet.properties to Liferay Portal Tools Service Builder Spring Sample Service to make sure it also cover a bundle using spring.

Please resend.

Thanks.
Tina

**Comment by marianoalvarosaiz** [comment]
@tinatian see https://github.com/liferay-core-infra/liferay-portal/pull/6172

**Pull request closed without merging**
