### PR TITLE
[Remove unused references]LPS-167240 Remove reference field _portal from AuthorizeNetCommercePa…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-167240

CI tests have been run in https://github.com/slnn/liferay-portal/pull/677

### CODE REVIEW

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125843

**Pull request closed without merging**
