### PR TITLE
[Urgent][Security Bugs]LPD-1558 Add captcha to avoid insufficient CSRF protection

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This PR is for ticket https://liferay.atlassian.net/browse/LPD-1558.
In this PR, I added two new methods to accept the value from portlet and set them in the attributes, and use this value to override the maxchallenges for the current portlet.

Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:report:2558092662

**Comment by jeffwu0724** [comment]
No unique regression found

**Comment by jeffwu0724** [comment]
Hi @vicnate5 
I have a quick question:
Is it a problem that the input field for the CAPTCHA appears too long? 
image
image

Thanks,
Jeff

**Comment by vicnate5** [comment]
@jeffwu0724 you are just implementing the `liferay-captcha` taglib? Is it even configurable? 

The gogo shell page is consistent enough with the page view as it is. 
The one on the Resources page could be changed to the width of the image to improve it. Do you know how to do this?

**Comment by vicnate5** [comment]
@jeffwu0724 The captcha at the top of the Resources page makes sense. Next to the button would not look good.

The user should be required to re-input the captcha before each "Execute" button is clicked. So once they click Execute, regen the captcha and re-enable the check (if a page refresh already happens, it might do this for you).

For the design, we can send as it is. This is intended to be a temporary solution for pending security issue.

**Comment by jeffwu0724** [comment]
Hi @tinatian 

After disccussed with Victor, this PR is good to go at the design side as this is a short-term solution.

- Concern about length of the captcha input filed
- - we can skip it as "it is not a problem"
- The one on the Resources page could be changed to the width of the image to improve it. 
- - we can skip it as " it doesn't look much better shortened"
- Should we make captacha sitting besides the button?
- - we can skip it as "Next to the button would not look good."

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6847

**Pull request closed without merging**
