### PR TITLE
[Component with its own class name as service type] LPS-197489 Refactor class DomainValidatorFactory and FieldPredicateProviderTracker component

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Ticket: https://liferay.atlassian.net/browse/LPS-197489
Correction of: https://github.com/liferay-core-infra/liferay-portal/pull/5780

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:account

**Comment by Kvale1733** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
@Valmir-unicap No regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
It's ready to review. Thx

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
