### PR TITLE
LPS-149258

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Fixed bugs found in https://github.com/liferay-core-infra/liferay-portal/pull/883
Updated based on discussion in https://github.com/liferay-core-infra/liferay-portal/pull/803
This is for ticket https://issues.liferay.com/browse/LPS-149258.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by tinatian** [comment]
@yuhai please take this over.

Thanks.
Tina

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
Failures looks like they can be unique, rerunning relevant to confirm

**Comment by kyle-miho** [comment]
@jeffwu0724 this failures looks like its unique
2022-06-13 17:14:36.769 WARN  [default-10][IndexerWriterImpl:197] Error reindexing all com.liferay.document.library.kernel.model.DLFileEntry for company: 20116
com.liferay.portal.kernel.exception.SystemException: java.lang.NoSuchFieldError: WORKBOOK_DIR_ENTRY_NAMES
	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.doPerformActions(DefaultActionableDynamicQuery.java:340) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery.doPerformActions(IndexableActionableDynamicQuery.java:107) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.performActions(DefaultActionableDynamicQuery.java:86) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery.performActions(IndexableActionableDynamicQuery.java:65) ~[portal-kernel.jar:?]
	at com.liferay.portal.search.internal.batch.DynamicQueryBatchIndexingActionableAdapter.performActions(DynamicQueryBatchIndexingActionableAdapter.java:50) ~[bundleFile:?]
	at com.liferay.portal.search.internal.indexer.IndexerWriterImpl.reindex(IndexerWriterImpl.java:193) [bundleFile:?]
	at com.liferay.portal.search.internal.indexer.DefaultIndexer.reindex(DefaultIndexer.java:267) [bundleFile:?]
	at com.liferay.portal.search.internal.SearchEngineInitializer.reindex(SearchEngineInitializer.java:93) [bundleFile:?]
	at com.liferay.portal.search.internal.SearchEngineInitializer$1.call(SearchEngineInitializer.java:169) [bundleFile:?]
	at com.liferay.portal.search.internal.SearchEngineInitializer$1.call(SearchEngineInitializer.java:160) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoSuchFieldError: WORKBOOK_DIR_ENTRY_NAMES
	at org.apache.tika.parser.microsoft.POIFSContainerDetector.detect(POIFSContainerDetector.java:214) ~[?:?]
	at org.apache.tika.parser.microsoft.POIFSContainerDetector.detect(POIFSContainerDetector.java:489) ~[?:?]
	at org.apache.tika.detect.CompositeDetector.detect(CompositeDetector.java:84) ~[?:?]
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:116) ~[?:?]
	at com.liferay.portal.tika.internal.extract.TextExtractorImpl._parseToString(TextExtractorImpl.java:189) ~[?:?]
	at com.liferay.portal.tika.internal.extract.TextExtractorImpl.extractText(TextExtractorImpl.java:111) ~[?:?]
	at com.liferay.portal.util.FileImpl.extractText(FileImpl.java:380) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.util.FileUtil.extractText(FileUtil.java:165) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.search.DocumentImpl.addFile(DocumentImpl.java:158) ~[portal-kernel.jar:?]
	at com.liferay.document.library.internal.search.spi.model.index.contributor.DLFileEntryModelDocumentContributor.contribute(DLFileEntryModelDocumentContributor.java:114) ~[?:?]
	at com.liferay.document.library.internal.search.spi.model.index.contributor.DLFileEntryModelDocumentContributor.contribute(DLFileEntryModelDocumentContributor.java:61) ~[?:?]
	at com.liferay.portal.search.internal.indexer.IndexerDocumentBuilderImpl.lambda$getDocument$1(IndexerDocumentBuilderImpl.java:60) ~[bundleFile:?]
	at com.liferay.osgi.service.tracker.collections.internal.list.ServiceTrackerListImpl.lambda$forEach$0(ServiceTrackerListImpl.java:70) ~[com.liferay.osgi.service.tracker.collections.jar:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890) ~[?:1.8.0_121]
	at com.liferay.osgi.service.tracker.collections.internal.list.ServiceTrackerListImpl.forEach(ServiceTrackerListImpl.java:69) ~[com.liferay.osgi.service.tracker.collections.jar:?]
	at com.liferay.portal.search.internal.indexer.IndexerDocumentBuilderImpl.getDocument(IndexerDocumentBuilderImpl.java:58) ~[bundleFile:?]
	at com.liferay.portal.search.internal.index.contributor.helper.ModelIndexerWriterDocumentHelperImpl.getDocument(ModelIndexerWriterDocumentHelperImpl.java:41) ~[bundleFile:?]
	at com.liferay.document.library.internal.search.spi.model.index.contributor.DLFileEntryModelIndexerWriterContributor.lambda$customize$0(DLFileEntryModelIndexerWriterContributor.java:51) ~[?:?]
	at com.liferay.portal.search.internal.batch.DynamicQueryBatchIndexingActionableAdapter.lambda$setPerformActionMethod$0(DynamicQueryBatchIndexingActionableAdapter.java:75) ~[bundleFile:?]
	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.performAction(DefaultActionableDynamicQuery.java:394) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery$1.call(DefaultActionableDynamicQuery.java:306) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery$1.call(DefaultActionableDynamicQuery.java:268) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.doPerformActions(DefaultActionableDynamicQuery.java:326) ~[portal-kernel.jar:?]
	... 15 more

**Comment by jeffwu0724** [comment]
> @jeffwu0724 this failures looks like its unique, which happens when uppgrading an older database to the master database, does this failure make sense to you? I can try to reproduce it locally if you need help with that. If its a quick fix or likely unrelated (happened twice uniquely on CI so unlikely), then thats fine as well! 2022-06-13 17:14:36.769 WARN [default-10][IndexerWriterImpl:197] Error reindexing all com.liferay.document.library.kernel.model.DLFileEntry for company: 20116 com.liferay.portal.kernel.exception.SystemException: java.lang.NoSuchFieldError: WORKBOOK_DIR_ENTRY_NAMES at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.doPerformActions(DefaultActionableDynamicQuery.java:340) ~[portal-kernel.jar:?] at com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery.doPerformActions(IndexableActionableDynamicQuery.java:107) ~[portal-kernel.jar:?] at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.performActions(DefaultActionableDynamicQuery.java:86) ~[portal-kernel.jar:?] at com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery.performActions(IndexableActionableDynamicQuery.java:65) ~[portal-kernel.jar:?] at com.liferay.portal.search.internal.batch.DynamicQueryBatchIndexingActionableAdapter.performActions(DynamicQueryBatchIndexingActionableAdapter.java:50) ~[bundleFile:?] at com.liferay.portal.search.internal.indexer.IndexerWriterImpl.reindex(IndexerWriterImpl.java:193) [bundleFile:?] at com.liferay.portal.search.internal.indexer.DefaultIndexer.reindex(DefaultIndexer.java:267) [bundleFile:?] at com.liferay.portal.search.internal.SearchEngineInitializer.reindex(SearchEngineInitializer.java:93) [bundleFile:?] at com.liferay.portal.search.internal.SearchEngineInitializer$1.call(SearchEngineInitializer.java:169) [bundleFile:?] at com.liferay.portal.search.internal.SearchEngineInitializer$1.call(SearchEngineInitializer.java:160) [bundleFile:?] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121] Caused by: java.lang.NoSuchFieldError: WORKBOOK_DIR_ENTRY_NAMES at org.apache.tika.parser.microsoft.POIFSContainerDetector.detect(POIFSContainerDetector.java:214) ~[?:?] at org.apache.tika.parser.microsoft.POIFSContainerDetector.detect(POIFSContainerDetector.java:489) ~[?:?] at org.apache.tika.detect.CompositeDetector.detect(CompositeDetector.java:84) ~[?:?] at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:116) ~[?:?] at com.liferay.portal.tika.internal.extract.TextExtractorImpl._parseToString(TextExtractorImpl.java:189) ~[?:?] at com.liferay.portal.tika.internal.extract.TextExtractorImpl.extractText(TextExtractorImpl.java:111) ~[?:?] at com.liferay.portal.util.FileImpl.extractText(FileImpl.java:380) ~[portal-impl.jar:?] at com.liferay.portal.kernel.util.FileUtil.extractText(FileUtil.java:165) ~[portal-kernel.jar:?] at com.liferay.portal.kernel.search.DocumentImpl.addFile(DocumentImpl.java:158) ~[portal-kernel.jar:?] at com.liferay.document.library.internal.search.spi.model.index.contributor.DLFileEntryModelDocumentContributor.contribute(DLFileEntryModelDocumentContributor.java:114) ~[?:?] at com.liferay.document.library.internal.search.spi.model.index.contributor.DLFileEntryModelDocumentContributor.contribute(DLFileEntryModelDocumentContributor.java:61) ~[?:?] at com.liferay.portal.search.internal.indexer.IndexerDocumentBuilderImpl.lambda$getDocument$1(IndexerDocumentBuilderImpl.java:60) ~[bundleFile:?] at com.liferay.osgi.service.tracker.collections.internal.list.ServiceTrackerListImpl.lambda$forEach$0(ServiceTrackerListImpl.java:70) ~[com.liferay.osgi.service.tracker.collections.jar:?] at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890) ~[?:1.8.0_121] at com.liferay.osgi.service.tracker.collections.internal.list.ServiceTrackerListImpl.forEach(ServiceTrackerListImpl.java:69) ~[com.liferay.osgi.service.tracker.collections.jar:?] at com.liferay.portal.search.internal.indexer.IndexerDocumentBuilderImpl.getDocument(IndexerDocumentBuilderImpl.java:58) ~[bundleFile:?] at com.liferay.portal.search.internal.index.contributor.helper.ModelIndexerWriterDocumentHelperImpl.getDocument(ModelIndexerWriterDocumentHelperImpl.java:41) ~[bundleFile:?] at com.liferay.document.library.internal.search.spi.model.index.contributor.DLFileEntryModelIndexerWriterContributor.lambda$customize$0(DLFileEntryModelIndexerWriterContributor.java:51) ~[?:?] at com.liferay.portal.search.internal.batch.DynamicQueryBatchIndexingActionableAdapter.lambda$setPerformActionMethod$0(DynamicQueryBatchIndexingActionableAdapter.java:75) ~[bundleFile:?] at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.performAction(DefaultActionableDynamicQuery.java:394) ~[portal-kernel.jar:?] at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery$1.call(DefaultActionableDynamicQuery.java:306) ~[portal-kernel.jar:?] at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery$1.call(DefaultActionableDynamicQuery.java:268) ~[portal-kernel.jar:?] at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.doPerformActions(DefaultActionableDynamicQuery.java:326) ~[portal-kernel.jar:?] ... 15 more

Thanks Kyle for letting me know! I think this is related to my change, becasue I saw "WORKBOOK_DIR_ENTRY_NAMES" before in this PR. Could you please tell me what kind of test I can run to get this error, please? Or any step to reproduce this error locally, please? 
Appreciate your help! :)

**Pull request closed without merging**
