### PR TITLE
[TS] LPS-201892

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@marianoalvarosaiz I do not understand, why you have to add "reset" feature?

**Comment by yuhai** [comment]
@marianoalvarosaiz, from my understanding, only the changes of `EditServerMVCActionCommand `from the [commit](https://github.com/liferay-core-infra/liferay-portal/pull/6341/commits/7dd4b6e5a4abd35d2963e2ad403d75397eb50a91) is enough for the issue. Is it right? If so, we may only submit the change for the issue in this pr.

For the other commits, you added reset default values function and might solve the permission issue. These seems be unrelated with the current issue, we may separate them to new tickets.

In addition, please add the related test to EditServerMVCActionCommandTest.

Thanks,
Hai

**Comment by marianoalvarosaiz** [comment]
@tinatian I added the reset to simplify the use:

- For system settings it simplifies the way to get back to original portal-ext configuration. Without the button is difficult to know which fields were manually introduced in the GUI and which weren't if you want to reset the modified ones.
- For instance settings there is no special reason besides to make it somehow consistent with the system settings since someone can find the button helpful and ask for it later.

**Comment by marianoalvarosaiz** [comment]
@yuhai both 7dd4b6e5a4abd35d2963e2ad403d75397eb50a91 and d3b172b2ba6ed094631cda14dcc452c8c281d737 are needed. Due to comments with Tina in previous pulls the idea to fix was to separate system and instance configuration.

I will create a test.

**Comment by tinatian** [comment]
@marianoalvarosaiz Please do not add reset feature, this should be consistent with other configurations, we do not have reset for other configurations, please mimic what other configuration does to achieve the same goal here.

Thanks.
Tina.

**Comment by marianoalvarosaiz** [comment]
@tinatian see https://github.com/liferay-core-infra/liferay-portal/pull/6389

**Pull request closed without merging**
