### PR TITLE
Lps 191404 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by Kvale1733** [comment]
@tinatian 

1) SF and stable are showing the integration test has no copyright. 
According to this slack thread there is a new format: https://liferay.slack.com/archives/CLCD3DQLF/p1690173697592229?thread_ts=1689943517.393139&cid=CLCD3DQLF

Should look like

```
/**
 * SPDX-FileCopyrightText: © 2000 Liferay, Inc. <https://liferay.com/>
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */
```

2) Regression in modules-unit test (I was able to reproduce locally on this branch, not reproducible on master)
com.liferay.osgi.util.service.SnapshotTest 
```
  [exec] com.liferay.osgi.util.service.SnapshotTest STANDARD_OUT
     [exec]     [Whip] com.liferay.osgi.util.service.Snapshot is fully covered.
     [exec] 
     [exec]     [Whip] com.liferay.osgi.util.service.Snapshot$DCLSingletonBundleListener is not fully covered.
     [exec]     [Whip]Branch coverage rate : 0.25, line coverage rate : 0.42.
     [exec]     [Whip] com.liferay.osgi.util.service.Snapshot$DCLSingletonBundleListener line 218 is not covered 
     [exec]     [Whip] com.liferay.osgi.util.service.Snapshot$DCLSingletonBundleListener line 219 is not covered 
     [exec]     [Whip] com.liferay.osgi.util.service.Snapshot$DCLSingletonBundleListener line 222 is not covered 
     [exec]     [Whip] com.liferay.osgi.util.service.Snapshot$DCLSingletonBundleListener line 224 is not covered 
```
[Log](https://testray.liferay.com/reports/production/logs/2023-07/test-1-30/test-portal-acceptance-pullrequest(master)/7326/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@tinatian 

1) com.liferay.osgi.util.service.SnapshotTest still fails only with these changes
```
 [exec] com.liferay.osgi.util.service.SnapshotTest > classMethod FAILED
     [exec]     java.lang.AssertionError: com.liferay.osgi.util.service.Snapshot$DCLSingletonBundleListener is not fully covered
     [exec]         at com.liferay.whip.agent.InstrumentationAgent._assertClassDataCoverage(InstrumentationAgent.java:343)
     [exec]         at com.liferay.whip.agent.InstrumentationAgent.assertCoverage(InstrumentationAgent.java:86)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at com.liferay.portal.kernel.test.rule.CodeCoverageAssertor.afterClass(CodeCoverageAssertor.java:110)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-07/test-1-25/test-portal-acceptance-pullrequest(master)/2208/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

2) SF failed because the copyright year should be 2023 instead of 2000 on the integration test.
```
format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/static/osgi/osgi-util-test/src/testIntegration/java/com/liferay/osgi/util/test/SnapshotIntegrationTest.java expected:<...opyrightText: (c) 20[23] Liferay, Inc. https...> but was:<...opyrightText: (c) 20[00] Liferay, Inc. https...>
```

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5158

**Pull request closed without merging**
