### PR TITLE
[System properties] LPS-153305 5-23

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@catarineaguiar Could you review the test results? Thanks!

**Comment by catarineaguiar** [comment]
ci:test:lpkg

**Comment by catarineaguiar** [comment]
@dantewang code conflicts, rebase please.

SF failure:
```
 [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: Portal property 'module.framework.properties.initial.system.check.enabled' was migrated to 'system.properties'. See 'portal-impl/src/com/liferay/portal/verify/VerifyProperties#_MIGRATED_PORTAL_KEYS'.: ./portal-impl/src/portal-developer.properties (SourceCheck:PropertiesVerifyPropertiesCheck)
     [java] 2: Portal property 'module.framework.properties.osgi.console' was migrated to 'system.properties'. See 'portal-impl/src/com/liferay/portal/verify/VerifyProperties#_MIGRATED_PORTAL_KEYS'.: ./portal-impl/src/portal-developer.properties (SourceCheck:PropertiesVerifyPropertiesCheck)
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:439)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:283)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-31/test-portal-acceptance-pullrequest(master)/3542/source-format-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
https://github.com/liferay-core-infra/liferay-portal/pull/823

**Pull request closed without merging**
