### PR TITLE
LPS-171867

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:headless

**Comment by tinatian** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
failure on startup:

```
2023-02-02 21:35:46.999 ERROR [main][OpenAPIResourceImpl:56] bundle com.liferay.portal.vulcan.impl:5.0.72 (291)[com.liferay.portal.vulcan.internal.resource.OpenAPIResourceImpl(782)] : The activate method has thrown an exception
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:1.8.0_221]
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:1.8.0_221]
	at com.liferay.portal.vulcan.internal.resource.OpenAPIResourceImpl$JaxRsResourceTrackerCustomizer.addingService(OpenAPIResourceImpl.java:1425) ~[?:?]
	at com.liferay.portal.vulcan.internal.resource.OpenAPIResourceImpl$JaxRsResourceTrackerCustomizer.addingService(OpenAPIResourceImpl.java:1417) ~[?:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943) ~[org.eclipse.osgi.jar:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1) ~[org.eclipse.osgi.jar:?]
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[org.eclipse.osgi.jar:?]
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183) ~[org.eclipse.osgi.jar:?]
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:321) ~[org.eclipse.osgi.jar:?]
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:264) ~[org.eclipse.osgi.jar:?]
	at com.liferay.portal.vulcan.internal.resource.OpenAPIResourceImpl.activate(OpenAPIResourceImpl.java:377) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-02/test-1-35/test-portal-acceptance-pullrequest(master)/3506/functional-smoke-startup-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz)

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found.

PS: the tests with unique failures passed locally with your changes.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129700

**Pull request closed without merging**
