### PR TITLE
[Bug Fix]LPS-39804

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
@tinatian I created a test for scenario in https://github.com/liferay-core-infra/liferay-portal/pull/164#issuecomment-1006159347

However the test is failing for me locally. The slave node changes is not updating the master node or other slave node.
[Master node log](https://gist.github.com/vicnate5/0fb29680e9336958f5f410231a4beb0c)
[Slave node 1 log (logging change applied)](https://gist.github.com/vicnate5/fe35c74de1fcbbbf46d436fd0cf7c15e)
[Slave node 2 log](https://gist.github.com/vicnate5/a22e1f65fabd8899590e329b4dbe54af)

I set `com.liferay.portal.cluster` to `DEBUG`

**Comment by tinatian** [comment]
@vicnate5 Fixed it and resend at https://github.com/liferay-core-infra/liferay-portal/pull/168.

Tina

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
