### PR TITLE
LPS-155991

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-155991.
Thanks for checking

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
ci:test:acceptance

**Comment by tinatian** [comment]
@jeffwu0724 Code looks good to me, wait for QA to scan test results.

Tina.

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
no regressions on relevant. Waiting for acceptance results.

**Comment by catarineaguiar** [comment]
no regressions on relevant. Waiting for acceptance results.

**Comment by catarineaguiar** [comment]
not possible to analyze acceptance results, because most tests were aborted. But according to relevant results no regression was found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Minor version upgrade, and all upgraded jar are compile included, passed ci:test:relevant, this seems enough to me, do not retrigger ci:test due to high load on ci.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121149

**Pull request closed without merging**
