### PR TITLE
[Method References 2] LPS-164288 Convert method reference to ServiceTrackerMap in module portal-search

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I convert method reference to ServiceTrackerMap in module portal-search.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @catarineaguiar  , Could you please help me check the test results ? Thanks!

**Comment by catarineaguiar** [comment]
@W2jx regression found:

```
[exec] com.liferay.portal.search.internal.result.SearchResultUtilTest > testBlankDocument FAILED
     [exec]     java.lang.AssertionError: [] expected:<1> but was:<0>
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.failNotEquals(Assert.java:834)
     [exec]         at org.junit.Assert.assertEquals(Assert.java:645)
     [exec]         at com.liferay.portal.search.test.util.BaseSearchResultUtilTestCase.assertOneSearchResult(BaseSearchResultUtilTestCase.java:83)
     [exec]         at com.liferay.portal.search.internal.result.SearchResultUtilTest.testBlankDocument(SearchResultUtilTest.java:60)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-31/test-portal-acceptance-pullrequest(master)/5235/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
Force-Push is just to rebase and fix the problem mentioned in comment.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
Hi @zhangyan0701  , Could you please help me check the test results ? Thanks!

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Test [central-requirements-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1994601921) failed with error:
```
    [junit] Testcase: testScanGradleFiles(com.liferay.portal.modules.ModulesStructureTest):	FAILED
    [junit] Incorrect configuration of dependency {compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"} in modules/apps/portal-search/portal-search-test/build.gradle, use one of these instead: "testCompile", "testIntegrationCompile", "testIntegrationRuntime", "testRuntime"
    [junit] junit.framework.AssertionFailedError: Incorrect configuration of dependency {compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"} in modules/apps/portal-search/portal-search-test/build.gradle, use one of these instead: "testCompile", "testIntegrationCompile", "testIntegrationRuntime", "testRuntime"
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest._testGradleFile(ModulesStructureTest.java:1512)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest.access$800(ModulesStructureTest.java:68)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest$4.visitFile(ModulesStructureTest.java:402)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest$4.visitFile(ModulesStructureTest.java:376)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest.testScanGradleFiles(ModulesStructureTest.java:374)
    [junit] 
    [junit] 
```

Full console:
https://testray.liferay.com/reports/production/logs/2022-09/test-1-27/test-portal-acceptance-pullrequest(master)/5222/central-requirements-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Pull request closed without merging**
