### PR TITLE
[Remove Unused Reference] LPS-165036 Remove unused reference variable in module upload-web

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have removed unused reference variable in module upload-web.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by zhangyan0701** [comment]
ci:test:item-selector

**Comment by catarineaguiar** [comment]
@W2jx no regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
