### PR TITLE
[TS] LPS-190994

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@marianoalvarosaiz regression found:

```
    [junit] Testcase: testScanXMLLog(com.liferay.portal.log.assertor.PortalLogAssertorTest):	FAILED
    [junit] 
    [junit] Portal log assert failure, see above log for more information: 
    [junit] Unable to execute job
    [junit] java.lang.IllegalStateException: Destination liferay/scheduler_dispatch is shutdown and cannot receive more messages
    [junit] 	at com.liferay.portal.messaging.internal.BaseAsyncDestination.send(BaseAsyncDestination.java:153)
    [junit] 	at com.liferay.portal.messaging.internal.DefaultMessageBus.sendMessage(DefaultMessageBus.java:101)
    [junit] 	at com.liferay.portal.scheduler.quartz.internal.job.MessageSenderJob._execute(MessageSenderJob.java:81)
    [junit] 	at com.liferay.portal.scheduler.quartz.internal.job.MessageSenderJob.execute(MessageSenderJob.java:34)
    [junit] 	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
    [junit] 	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
```
semver error:
```
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.util                     MAJOR      64.0.0     64.0.0     65.0.0     VERSION INCREASE REQUIRED
     [exec] 	>   interface  com.liferay.portal.kernel.util.PropsKeys
     [exec] 		-   field      MESSAGE_BOARDS_EXPIRE_BAN_JOB_INTERVAL
     [exec] 			-   access     final
     [exec] 			-   access     static
     [exec] 			-   constant   message.boards.expire.ban.job.interval
     [exec] 			-   return     java.lang.String
     [exec] [Baseline Warning] Bundle Version Change Recommended: 124.0.0
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-09/test-1-38/test-portal-acceptance-pullrequest(master)/8951/modules-integration-mysql57-jdk8/3/8/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
@marianoalvarosaiz This error caught by QA should be the one I mentioned?

**Comment by marianoalvarosaiz** [comment]
Good catch @catarineaguiar !

**Comment by marianoalvarosaiz** [comment]
@dantewang yes,it was the same one. It was only reproducible leaving the tomcat up after the test and waiting for a job to get executed. 

The problem was with the not needed SynchronousDestinationTestRule and its inner class TestSynchronousDestination that has an empty close method, so that when stop/starting the scheduler module the destroy of the DestinationNames.SCHEDULER_DISPATCH leaves a shut down NoticeableThreadPoolExecutor.

I've sent a new one, see https://github.com/liferay-core-infra/liferay-portal/pull/5563

**Pull request closed without merging**
