### PR TITLE
[Bug Fix] LPS-144437

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, actually, the pr is prepared for the [requirement](https://github.com/liferay-core-infra/liferay-portal/pull/32#issuecomment-981404118). After the current pr, it will be convenient for me to extract the code to the common place.

**History**:
LPS-62334 added the attribute persistSettings. Due to LPS-62334 test steps need to place itself navigation portlet to layout in the first step. At that time, the related navigation portlet portletPreference data was added to database (this will cause count >=1). So I guess LPS-62334 fix missed the case that <liferay-portlet:preview> portletName invokes another portlet (not itself).

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
@yuhai Please see my SF to the integration test: https://github.com/yuhai/liferay-portal/pull/276

Also, I wonder why you embrace the logic in `if (!layout.isPortletEmbedded(..., ...)) {}` first. The commit message is pretty hard to understand. Is this necessary for the fix of this ticket, which I think should be addressing the `persisteSettings` issue? If not, it means you are just doing it to make it possible to merge the two `if` blocks, right?

What looks better to me would be: you make the logic aware of `persistSettings` first, and then you add that `if` condition as an SF with clear reason in the commit message afterwards, and in the end you merge the two `if` blocks into one.

Please update the PR and resend. Thanks!

**Comment by dantewang** [comment]
ci:close

**Pull request closed without merging**
