### PR TITLE
[Method References 2] LPS-165449 Convert method reference to ServiceTrackerList in module users-admin-web

### PR DESCRIPTION
**Pull request by W2jx**
Convert method reference to ServiceTrackerList in module users-admin-web.

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:usm

**Comment by Kvale1733** [comment]
ci:test:usm

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126022

**Pull request closed without merging**
