### PR TITLE
LPS-172251 Remove Stream and Optional usages in portal-workflow-kaleo-runtime-integration-impl

### PR DESCRIPTION
**Pull request by dantewang**
@julschong

### CODE REVIEW

**Comment by dantewang** [comment]
@julschong Could you double check https://github.com/liferay-core-infra/liferay-portal/pull/3020/commits/985d6416809be41a1733ae33b19945c64f704e73? This should be a typo?

**Comment by dantewang** [comment]
The SF failure should be irelevant.

**Comment by zhangyan0701** [comment]
Hi @dantewang Could you rebase the branch and resend? Cause there are too many tests running in relevant and too many failures, it's difficult to determine which are related.

**Comment by julschong** [comment]
> Collaborator

@dantewang Hi Danete,
Sorry about the mistake, yes this was a typo

**Comment by julschong** [comment]
will resubmitted to rebase

**Pull request closed without merging**
