### PR TITLE
LPS-163426: Allow same page and sites with same name, function properly in a virtual host

### PR DESCRIPTION
**Pull request by kristofloneck**

### CODE REVIEW

**Comment by Kvale1733** [comment]
Rerunning relevant. Lots of aborted tests due to unrelated errors.

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@kristofloneck failures don't seem related.

**Comment by kristofloneck** [comment]
SF failed, sending a new one

**Pull request closed without merging**
