### PR TITLE
[Remove Spring extender usages] LPS-159491

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang

### CODE REVIEW

**Comment by yuhai** [comment]
@catarineaguiar, please scan the test result after ci test finished. Thanks.

**Comment by yuhai** [comment]
ci:test:commerce

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
@yuhai no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
