### PR TITLE
LPS-196524 move class Snapshot to portal-kernel and remove unused dependency

### PR DESCRIPTION
**Pull request by JanisZhang**
https://liferay.atlassian.net/browse/LPS-196524

This PR is to move class Snapshot to portal-kernel and remove unused dependencies. Thanks! cc @dantewang @W2jx

### CODE REVIEW

**Comment by dantewang** [comment]
@JanisZhang @W2jx Thanks!

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
cc @shuyangzhou

**Comment by JanisZhang** [comment]
SF failure should be not related.

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
Reviewing...

**Comment by liuxingye** [comment]
Hi @JanisZhang 

I found the following issue semantic versioning issue when analyzing the test [modules-semantic-versioning-jdk8](https://testray.liferay.com/home/-/testray/case_results/2427791770) from the relevant suite, it looks like only appears on the PR. Could you take a look when you get a chance? Thanks.
```
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.osgi.util.service                      MAJOR      3.1.0      3.1.0      4.0.0      VERSION INCREASE REQUIRED
     [exec]     	-   class      com.liferay.osgi.util.service.Snapshot
     [exec]     		-   method     <init>(java.lang.Class,java.lang.Class)
     [exec]     			-   return     void
     [exec]     		-   method     <init>(java.lang.Class,java.lang.Class,java.lang.String)
     [exec]     			-   return     void
     [exec]     		-   method     <init>(java.lang.Class,java.lang.Class,java.lang.String,boolean)
     [exec]     			-   return     void
     [exec]     		-   method     cast(java.lang.Class)
     [exec]     			-   access     static
     [exec]     			-   return     java.lang.Class
     [exec]     		-   method     clone()
     [exec]     			-   access     protected
     [exec]     			-   return     java.lang.Object
     [exec]     		-   method     equals(java.lang.Object)
     [exec]     			-   return     boolean
     [exec]     		-   method     finalize()
     [exec]     			-   access     protected
     [exec]     			-   return     void
     [exec]     		-   method     get()
     [exec]     			-   return     java.lang.Object
     [exec]     		-   method     hashCode()
     [exec]     			-   return     int
     [exec]     		-   method     toString()
     [exec]     			-   return     java.lang.String
```
Whole [log](https://testray.liferay.com/reports/production/logs/2023-09/test-1-27/test-portal-acceptance-pullrequest(master)/10053/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0).

**Comment by dantewang** [comment]
@liuxingye Is this sem ver error the only unique one?

**Comment by JanisZhang** [comment]
Thanks @liuxingye !
code conflicts, see https://github.com/liferay-core-infra/liferay-portal/pull/5602. thx.

**Comment by liuxingye** [comment]
Found another issue for [com.liferay.osgi.util.service.SnapshotTest](https://testray.liferay.com/home/-/testray/case_results/2427792590) test, pinged @JanisZhang for taking look into it. Thanks.

```
     [exec] 1 test completed, 1 failed
     [exec] 
     [exec] 
     [exec] > Task :apps:static:osgi:osgi-util:test
     [exec] 
     [exec] com.liferay.osgi.util.service.SnapshotTest > classMethod STARTED
     [exec] 
     [exec] com.liferay.osgi.util.service.SnapshotTest > classMethod FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
     [exec]         at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
     [exec]         at com.liferay.whip.agent.InstrumentationAgent.dynamicallyInstrument(InstrumentationAgent.java:212)
```

**Pull request closed without merging**
