### PR TITLE
Lps 183809

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:help

**Comment by tinatian** [comment]
ci:test:security

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@tinatian Regressions found

1 ) Unsatisfied reference on startup
```
[beanshell] 2023-05-05 23:58:16.171 WARN  [main][SystemCheckOSGiCommands:154] Declarative Service Unsatisfied Component Checker check result: 
[beanshell] Bundle {id: 1114, name: com.liferay.antivirus.async.store, version: 1.0.13}
[beanshell] 	Declarative Service {id: 4950, name: com.liferay.antivirus.async.store.internal.scheduler.RetrySchedulerJobConfiguration, unsatisfied references: 
[beanshell] 		{name: _antivirusAsyncRetryScheduler, target: null}
[beanshell] 	}
[beanshell] 2023-05-05 23:58:16.171 INFO  [main][SystemCheckOSGiCommands:131] Running "Missing Component Scanner". You can run this by itself with command "ds:missing" in gogo shell.
```
[Log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-35/test-portal-acceptance-pullrequest(master)/4119/functional-smoke-tomcat90-mysql57-jdk11_open/0/0/jenkins-console.txt.gz?authuser=0)

2 ) Semver issue
```
exec] > Task :dxp:apps:antivirus:antivirus-async-store:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.antivirus.async.store.constants        MAJOR      1.0.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.antivirus.async.store.constants.AntivirusAsyncConstants
     [exec] 		-   field      SCHEDULER_GROUP_NAME_ANTIVIRUS
     [exec] 			-   access     final
     [exec] 			-   access     static
     [exec] 			-   constant   Antivirus
     [exec] 			-   return     java.lang.String
     [exec] 		-   field      SCHEDULER_GROUP_NAME_ANTIVIRUS_BATCH
     [exec] 			-   access     final
     [exec] 			-   access     static
     [exec] 			-   constant   Antivirus Batch
     [exec] 			-   return     java.lang.String
     [exec] * com.liferay.antivirus.async.store.retry            MAJOR      1.0.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
     [exec] 	>   interface  com.liferay.antivirus.async.store.retry.AntivirusAsyncRetryScheduler
     [exec] 		+   method     getPendingMessageCount()
     [exec] 			+   access     abstract
     [exec] 			+   return     int
     [exec] 		+   method     getScheduledMessage()
     [exec] 			+   access     abstract
     [exec] 			+   return     com.liferay.portal.kernel.messaging.Message
     [exec] [Baseline Warning] Bundle Version Change Recommended: 2.0.0
```
[Log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-34/test-portal-acceptance-pullrequest(master)/4006/modules-semantic-versioning-jdk8/0/6/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
