### PR TITLE
[Static reference] LPS-166968 Replace field reference with snapshot in class DataLayoutTaglibUtil

### PR DESCRIPTION
**Pull request by W2jx**
Resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4448

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:document

**Comment by Kvale1733** [comment]
ci:test:cookies

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@W2jx Several integration tests are failing with similar errors

com.liferay.data.engine.rest.resource.v2_0.test.DataDefinitionResourceTest
com.liferay.data.engine.rest.resource.v2_0.test.DataRecordResourceTest
com.liferay.data.engine.rest.resource.v2_0.test.DataListViewResourceTest
com.liferay.data.engine.rest.resource.v2_0.test.DataRecordCollectionResourceTest
com.liferay.data.engine.rest.resource.v2_0.test.DataDefinitionFieldLinkResourceTest
com.liferay.data.engine.rest.resource.v2_0.test.DataDefinitionFieldLinkResourceTest

```
 [exec] com.liferay.data.engine.rest.resource.v2_0.test.DataDefinitionResourceTest > testGetDataDefinition FAILED
     [exec]     com.liferay.data.engine.rest.client.problem.Problem$ProblemException: com.liferay.data.engine.rest.resource.v2_0.test.util.content.type.TestDataDefinitionContentType-com.liferay.dynamic.data.mapping.model.DDMStructure#PERMISSIONS
     [exec]     	at com.liferay.data.engine.rest.client.resource.v2_0.DataDefinitionResource$DataDefinitionResourceImpl.postSiteDataDefinitionByContentType(DataDefinitionResource.java:1702)
     [exec]     	at com.liferay.data.engine.rest.resource.v2_0.test.DataDefinitionResourceTest.testGetDataDefinition_addDataDefinition(DataDefinitionResourceTest.java:675)
     [exec]     	at com.liferay.data.engine.rest.resource.v2_0.test.BaseDataDefinitionResourceTestCase.testGetDataDefinition(BaseDataDefinitionResourceTestCase.java:604)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-32/test-portal-acceptance-pullrequest(master)/9431/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:data-engine

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(5/12 10:36)

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4520

**Pull request closed without merging**
