### PR TITLE
LPS-178639: Not clearing Local cache making dslQueryCount method fail

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Set `clearLocalCache` function in `clearDSLQueryCache` method because when we try to update the same System Object Definition table, the `dslQueryCount` method will return the value that has been saved in the Local Cache, so this means that after adding a new record in the System Object Definition table, it will add again a new record with the same Primary key, the correct way is to update the record that has been inserted previously.
- Create a test case that simulates what I have explained above.

**JIRA TICKET**
https://issues.liferay.com/browse/LPS-178639

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@sergiojimcos You are modifying FinderCacheImpl, so please add a test to cover the changes in FinderCacheImpl, the test should have nothing to do with any real usage of FinderCacheImpl, for example, in this case, the test should not be in Object scope.

As this is a bug for framework code (FinderCacheImpl is the important part of the cache framework), please do this:
1. Add a test to expose the issue of FinderCacheImpl
2. Fix the FinderCacheImpl

I am going to close this pull, please resend.

Thanks.
Tina.

**Comment by 4lejandrito** [comment]
Hey @tinatian, 

We're not experts on how caching works. We tried our best to expose the bug and write the test so that you guys can do the right fix.

Please don't close this PR and send the right fix on top.

Thanks!

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by tinatian** [comment]
@4lejandrito 
I need a test not related to any real application to know what's wrong with the caching framework, with your current test, it is hard for me to know if this is a bad usage from your team or a bug on framework.

Please send another pull to show this is really a framework bug. Based on the fix, it seems easy, if you still feel this is difficult, please create a bug ticket and assign to core infra and we will take care of it.

Thanks for bringing this up, but I need to close this pull as we can not start working from here, it involves too much object related logic which is going to take us a lot of efforts to understand and fix, please help us to isolate this issue from object and we will be very happy to start working from there, you do not even to provide a fix, just a test to expose the issue is also fine.

Thanks.
Tina.

**Comment by 4lejandrito** [comment]
Hey @tinatian,

That's exactly what we did. We created a bug and assigned it to core infra ([LPS-178639](https://issues.liferay.com/browse/LPS-178639)). And to make your life easier we used what we learnt during our investigation to create a failing test and a naive fix to save you some time. 

The test is super simple and we isolated it as much as we could given our knowledge. I am sure in a few minutes of debugging you would know how to properly fix it. 

To be honest with you, next time we won't make the effort and just report the bug and push for you guys to fix it. In my humble opinion this attitude does not foster collaboration.

Please help us fix the bug because it is blocking one of our stories.

**Comment by tinatian** [comment]
@yuhai Please take care of this.

Thanks.
Tina.

**Comment by tinatian** [comment]
@yuhai No need to work on this, this is not something we should fix, the object team will take care of it.

**Pull request closed without merging**
