### PR TITLE
LPS-178732 LPS-176550 cause about -3.18% performance regression

### PR DESCRIPTION
**Pull request by dantewang**
For QA, please manually test the feature flag setting on cluster.

### CODE REVIEW

**Comment by drewbrokke** [comment]
@dantewang is it no longer required that the class also be an `IdentifiableOSGiService`?

**Comment by dantewang** [comment]
@drewbrokke `IdentifiableOSGiService` has its benefit, as the util can find the exact service instance and call it. But since we don't want to publish more than 1 service in a component, I switched to the static method/field way.

**Comment by catarineaguiar** [comment]
@dantewang no regressions were found on relevant, should we ask for performance QA to test the fix?

**Comment by dantewang** [comment]
@catarineaguiar The fix has already been tested with performance tests, the later changes are just like SF.

@zhangyan0701 Could you verify if feature flag setting works on the cluster?

**Comment by zhangyan0701** [comment]
Hi @dantewang 

I manually tested Feature Flag on cluster refer to the steps in ticket [LPS-178901](https://issues.liferay.com/browse/LPS-178901). Testing with feature COMMERCE-10890 as an example.

Found below two scenarios may have wrong behaviors:

**Scenario one: The feature that enabled on node1 is still disabled on node2.**
1. Setup a cluster with two nodes.
2. Add property `feature.flag.ui.visible[dev]=true` in portal-ext.properties of both nodes.
3. Start both node.
4. On node1, go to Control Panel > Instance Settings > Platform > Feature Flags.
5. Under developer scope, enable feature `COMMERCE-10890` (The feature is to enable Account with type Supplier).
6. On node2. check if the feature is enabled.
7. Create a Supplier Account on node1.
8. On node2, check the new account.

Results:
The feature is still disabled on node2, the Supplier Account that created on node1 cannot be seen on node2 and it won't display even though enable the feature on node2 then.

**Scenario two: The feature is actually enabled on node2 after disabling it if the feature was enabled on both nodes.**
1. Setup a cluster with two nodes.
2. Add property `feature.flag.ui.visible[dev]=true` in portal-ext.properties of both nodes.
3. Start both node.
4. Enable feature `COMMERCE-10890` on both nodes.
5. Create a Supplier Account on node1.
6. On node2, assert the new account displays.
7. On node2, disable the feature now.
8. Try to create a new Supplier Account on node2.

Results:
Supplier Account can be created on node2 even though the feature is disabled on node2.

Could you help with confirming if they are real issues on cluster? Thanks!

**Comment by dantewang** [comment]
@zhangyan0701 Thanks! I'll look into it.

**Pull request closed without merging**
