### PR TITLE
[Remove Stream/Optional usage] LPS-172199 Remove usage of Stream in module segments-web | part 3

### PR DESCRIPTION
**Pull request by W2jx**
This pr is the last pr in task [LPS-172199](https://issues.liferay.com/browse/LPS-172199). The reason why I submit it separately is that I have been waiting for the [new sf function](https://github.com/brianchandotcom/liferay-portal/pull/128533) to be merged.

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:sf

**Review by dantewang — APPROVED** [review]

**Comment by W2jx** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
@W2jx No related failures in relevant tests, but the SF failure should be related.

**Comment by W2jx** [comment]
Hi @zhangyan0701 ，I re-run the SF test.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128733

**Pull request closed without merging**
