### PR TITLE
LPS-195499 Merge EditorConfigurationFactory interface and impl into Util in kernel

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
fix sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:frontend

**Comment by Kvale1733** [comment]
@julschong. No regressions found. SF issue is unrelated.

**Pull request closed without merging**
