### PR TITLE
[Component with its own class name as service type] LPS-200169 Refactor Components from Faro module

### PR DESCRIPTION
**Pull request by MrJohn1911**
Previous pull: https://github.com/liferay-core-infra/liferay-portal/pull/5996

Ticket: https://liferay.atlassian.net/browse/LPS-200169

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @MrJohn1911, Our tests are not working because of a modification made by another team in the master branch that affected us. I downloaded your PR to check if the modifications were affecting AC and noticed this:

I don't see any errors in the Faro log or in the other containers, but when we build the AC, a demo workspace is generated that we use. With the modifications to your PR, I noticed that this workspace is not being generated, I had to create one manually.
As the Faro log cannot create the demo workspace, the log does not show that the data was generated successfully, which must be what is causing the error in the CI two weeks ago when we ran the tests in this same PR. Your changes were exactly in this part of the Demo, so you need to see this so as not to break us here

**Pull request closed without merging**
