### PR TITLE
[TS] LPD-18073

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @marianoalvarosaiz ,

**I had a few thoughts regarding this PR:**
1. I think we should add the test case to the **view-count-test** module, instead of **view-count-service**
    - We might be able to re-use the existing **ViewCountEntryFinderTest** class
2. From your testing, would you happen to have verified whether the entity cache clear would be cleared based on the configured BufferedIncrement?
    - I'm just trying to determine whether the original design intentionally did not want to notify all nodes in the cluster
        - e.g. in case it would create too many packets for the network to handle
    - If the entity cache clear is not buffered, then I think we may need to re-evaluate this change.
        - e.g. could this risk generating too many packets for a common clustered environment?
            - if so, would this change be viable, only if a proper BufferedIncrement is configured
            - if so, maybe we would need to make this change configurable, so a portal admin would need to enable this at their own discretion

Can you help check whether this change may be risky for a common clustered environment? For example, if we have a busy page with many guest users visiting, would this generate too many cluster messages?

**Comment by ericyanLr** [comment]
Hi @marianoalvarosaiz ,

Thanks for the response!

**Regarding:**

> I added it in the service because I wanted to add a unit test only, just to check that the correct EntityCache method is called.
> If I add it in ViewCountEntryFinderTest, what would you like me to test? I first considered adding it there, but I wasn't able to imagine what to check. But I'm open for new ideas.

I see, I didn't realize the *-test modules did not contain the unit tests. After looking over the issue some more, I think the test makes sense. 

**Regarding:**
> (The topic regarding BufferedIncrement + making it configurable)

After looking over the issue some more, I think the change is actually valid, since we can see that the view count is not synchronized with a clean Liferay setup.

I also did additional testing and can confirm that if BufferedIncrement is configured, the call to update the entity cache is only called for the buffered increment is processed. And so I think the current options we have should be sufficient; if a customer really does run into a network bottleneck issue due to enabling this, then our suggestion could be to fine tune the buffered increment configuration.

**Next Steps**
I'll provide a follow-up comment and pass the review to Tina.

**Comment by ericyanLr** [comment]
**Test Results: Passed**
`ci:test:sf` and `ci:test:relevant` have passed successfully.

Marking as **QA Passed** and **Ready to Review (No Regression)**


@tinatian , 

Ticket: https://liferay.atlassian.net/browse/LPD-18073

From my testing, before the fix, the view count is not consistent between the nodes in a cluster. And after the fix, the view count is now consistent. (I'll leave steps to reproduce below without groovy script below, in case it's helpful)

The only concern I can think of is the increase in network traffic for the cluster communication. 

But from what I remember, for network performance issues related to view count, we provide the options to:
- Disable View Count
- Fine-tune the Buffered Increment 

And so, I'm thinking if this new change does introduce some additional traffic that may be too much for some specific environment to handle, the admin would still look into one of those mentioned options.

Feel free to let us know if you have any questions.
Thanks!

----

**Steps to Reproduce (Without Groovy Script)**
1. Startup Liferay Cluster with 2 nodes (NodeA + Node B)
2. On Node A:
    1. Create Web Content: abc
    2. Add Asset Publisher to a page with the following configuration:
        - Asset Selection:
            - Asset Selection: **Dynamic**
            - Source: **Web Content Article** | **Basic Web Content**
        - Display Settings:
            - Set and Enable: **View Count Increment** (checked)
            - Metadata: **View Count** (Current)
        - Click Save
    3. Navigate to the page
        - Notice the View Count is shown for the article
    4. Click on the title of the article
        - Notice the view count is incremented
3. Open a new tab for Node B:
   1. Navigate to the page
        - Notice the View Count is correctly shown for the article
4. Switch back to Node A
    1. Refresh the page
        - Notice the view count is incremented, as expected
6. Switch back to Node B and refresh the page

**Actual Result:** The view count in Node B has a different value than the view count in Node A
**Expected Result:** The view count in Node B should have the same value as the view count Node A

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/147410

@marianoalvarosaiz @ericyanLr Please note I did not include the test. The test itself did not make any sense, it is just checking if you are invoking a specific method, everything is mocked, this kind of test did not protect anything, and each time I change the impl inside the finder, I may be forced to update the test as a lot of mocking inside it.

I forwarded the fix without a test as the usage of entity cache should follow the rule I mentioned in the commit message. 

Thanks.
Tina.

**Pull request closed without merging**
