### PR TITLE
[TS] LPS-201076

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the previous pr is https://github.com/liferay-core-infra/liferay-portal/pull/6179. The issue was caused by the commit (3f13710044df3ae2b844e6b04c1c12b5b07c02df)

cc @marianoalvarosaiz

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@marianoalvarosaiz @yuhai Only the first 2 commits are for the bug fix, right?

**Comment by dantewang** [comment]
@marianoalvarosaiz @yuhai The easiest fix is to correct the `Snapshot` usage, and cast the `BundleManager` object into `BundleManagerImpl` object in the util in `-service` module. Everything else is SF.

Regarding SF, I wonder if we really need to keep the `BundleManagerImpl` as a component. It doesn't depend on any other OSGi service, and it's referenced by either static Snapshot or 1:1 reference.

Looking at the git history, it was originally a util using JMX API, and then changed into component to use OSGi API. But the `BundleContext` can actually be easily obtained in a util. On the other hand, the logic is pretty procedural and stateless.

So I don't see necessity for `BundleManagerImpl` to exist as a component. Instead of modifying the interface, which is already a breaking change, just move the logic into the `BundleManagerUtil` and make it API.

**Comment by yuhai** [comment]
@dantewang, I want to confirm the fix way and I might not understand yet.

We will move `BundleManagerImpl `logic to `BundleManagerUtil`, then delete `BundleManagerImpl `class and move `BundleManagerUtil` to api module. After that, the inferface `BundleManager` also is not necessary(deleted). All places will use BundleManagerUtil. Is my understanding right?

**Comment by dantewang** [comment]
@yuhai Yes, we can do that

**Comment by yuhai** [comment]
@dantewang, thanks, we will resend it.

 cc @marianoalvarosaiz.

**Pull request closed without merging**
