### PR TITLE
LPS-143631 Remove JSONFactoryUtil usages in modules part 3

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
rebased to solve conflict

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test;sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/124836

**Comment by vicnate5** [comment]
Fix at https://github.com/liferay-echo/liferay-portal/pull/9979

**Comment by ozysouza** [comment]
@zhangyan0701 @julschong @vicnate5, as written on this thread on [slack](https://liferay.slack.com/archives/CLA7D1CNL/p1666189616007169) we are finding other issues on page editor, also relared to missing reference annotation. We think the best way for now would be revert whole PR to be sure we didn't miss any case.

**Pull request closed without merging**
