### PR TITLE
[Component with its own class name as service type] LPS-196947 Refactor components from echo modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Previous pull: https://github.com/rafaprax/liferay-portal/pull/1313

Ticket: https://liferay.atlassian.net/browse/LPS-196947

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Review by rafaprax — COMMENTED** [review]
Hey @MrJohn1911, just update the log messages to reflect the changes.  Thx

**Comment by MrJohn1911** [comment]
In the last push, I only changed some commit messages.

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
In the last push, I only solved a conflict with a file that was deleted in this pull, so any logic was changed

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-core-infra/liferay-portal/pull/6145

**Pull request closed without merging**
