### PR TITLE
[Components with more than 1 service] LPS-189642 Refactor components from export-import module

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-189642

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:staging

**Comment by lilylcl** [comment]
Hello @MrJohn1911,
`testExportImport FAILED` is found in [com.liferay.dynamic.data.mapping.exportimport.test.DDMFormDisplayExportImportTest](https://testray.liferay.com/zh/home/-/testray/case_results/2370845353) and [com.liferay.dynamic.data.lists.internal.exportimport.test.DDLDisplayExportImportTest](https://testray.liferay.com/zh/home/-/testray/case_results/2370845339). Could you take a look when you get a chance? Thanks.
```
    [exec] com.liferay.dynamic.data.lists.internal.exportimport.test.DDLDisplayExportImportTest > testExportImport STARTED
     [exec] 
     [exec] com.liferay.dynamic.data.lists.internal.exportimport.test.DDLDisplayExportImportTest > testExportImport FAILED
     [exec]     com.liferay.exportimport.kernel.exception.ExportImportRuntimeException
     [exec]     	at com.liferay.portlet.exportimport.service.impl.ExportImportLocalServiceImpl.exportPortletInfoAsFile(ExportImportLocalServiceImpl.java:137)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
     [exec]     	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
     [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
     [exec]     	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
     [exec]     	at com.sun.proxy.$Proxy129.exportPortletInfoAsFile(Unknown Source)
     [exec]     	at com.liferay.exportimport.kernel.service.ExportImportLocalServiceUtil.exportPortletInfoAsFile(ExportImportLocalServiceUtil.java:71)
     [exec]     	at com.liferay.exportimport.test.util.lar.BasePortletExportImportTestCase.exportImportPortlet(BasePortletExportImportTestCase.java:427)
     [exec]     	at com.liferay.exportimport.test.util.lar.BasePortletExportImportTestCase.exportImportPortlet(BasePortletExportImportTestCase.java:367)
     [exec]     	at com.liferay.exportimport.test.util.lar.BasePortletExportImportTestCase.getImportedPortletPreferences(BasePortletExportImportTestCase.java:484)
     [exec]     	at com.liferay.dynamic.data.lists.internal.exportimport.test.DDLDisplayExportImportTest.testExportImport(DDLDisplayExportImportTest.java:86)
```
[Whole log](https://testray.liferay.com/reports/production/logs/2023-07/test-1-37/test-portal-acceptance-pullrequest(master)/12932/modules-integration-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

**Comment by lilylcl** [comment]
@slnn Could you help to add QA Failed Label? Thanks.

**Pull request closed without merging**
