### PR TITLE
[Method References] LPS-161441 Replace method setServletContext with variable servletContext in class extends BaseJSPPortletConfigurationIcon

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang ,I replace method setServletContext with variable servletContext in classes extend BaseJSPPortletConfigurationIcon

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results when they finish ? Thanks!

**Review by dantewang — APPROVED** [review]
Code looks good, waiting for QA.

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122526

**Pull request closed without merging**
