### PR TITLE
[FileInstall] LPS-144496 Part 3

### PR DESCRIPTION
**Pull request by dantewang**
Migrate other properties that are previously passed via bundle context to direct portal properties for File Install.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
Force pushed to rebase.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@dantewang Code conflicts, please resend.

Thanks.
Tina

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
