### PR TITLE
[Static reference] LPS-181671 Remove method reference by using snapshot in modules item-selector-taglib, journal-taglib, rss-taglib, ratings-taglib

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:item-selector

**Comment by W2jx** [comment]
ci:test:lima

**Comment by W2jx** [comment]
ci:test:echo

**Comment by W2jx** [comment]
ci:test:lima

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
