### PR TITLE
LPS-154852 remove properties: module.framework.properties.lpkg.deployer.dir

### PR DESCRIPTION
**Pull request by W2jx**
@tinatian @dantewang

I have removed  properties module.framework.properties.lpkg.deployer.dir and replaced the use of it with module.framework.marketplace.dir

### CODE REVIEW

**Comment by tinatian** [comment]
@zhangyan0701 Please help me scan test results.

Thanks.
Tina.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/118622

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
