### PR TITLE
[Remove unused reference] LPS-165890

### PR DESCRIPTION
**Pull request by JanisZhang**
This PR is to remove unused fields (MISC). Thanks!
https://issues.liferay.com/browse/LPS-165890

Previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/2112

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@JanisZhang Please exclude and record https://github.com/liferay-core-infra/liferay-portal/pull/2179/commits/bd161d9dbeaa650661545f40ee9651476b65578d and https://github.com/liferay-core-infra/liferay-portal/pull/2179/commits/562a09d56d7606986665117c79297a5d1aac8c71, and resend. Also, the class yo u modified in https://github.com/liferay-core-infra/liferay-portal/pull/2179/commits/6532827682aa6437ba4f3c0d71e0f861cf209955 has been removed, just skip it when rebasing.

**Pull request closed without merging**
