### PR TITLE
[Remove usage of Stream/Optional on Method Return Value from the interface AdaptiveMedia]Lps 172879 adaptive media

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-172879

This pull aims to remove the Option usage in this method of interface `AMImageAttributeMapping`

`getValueOptional(AMAttribute<AMImageProcessor, V> amAttribute)`

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:lima

**Comment by slnn** [comment]
Forced push with updating semantic version

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:lima

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
Code conflict, please resend.

**Comment by slnn** [comment]
Rebase and resend in https://github.com/liferay-core-infra/liferay-portal/pull/3544

**Pull request closed without merging**
