### PR TITLE
[Remove immediate=true usage core-infrastructure-4 part-2]Lps 168633 part 2

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-168633

### CODE REVIEW

**Comment by slnn** [comment]
ci:test

**Comment by slnn** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@slnn Some of your changes had been merged by LPS-171496, please rebase to master and resend

**Comment by slnn** [comment]
Resend in https://github.com/liferay-core-infra/liferay-portal/pull/2872

**Pull request closed without merging**
