### PR TITLE
[Remove Stream/Optional usages: portal-workflow-metrics-rest-impl]Lps 178425 3 30

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-178425

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:workflow

**Comment by slnn** [comment]
ci:test:workflow-metrics

**Comment by Kvale1733** [comment]
@slnn No regressions.

**Comment by dantewang** [comment]
See https://github.com/slnn/liferay-portal/pull/717

**Pull request closed without merging**
