### PR TITLE
LPS-83930

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, I wrote the explanation in LPS-83930 [comment](https://issues.liferay.com/browse/LPS-83930?focusedCommentId=2566898&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2566898).

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
@tinatian Please see Hai's comment in the ticket for the cause. This fix is based on the assumption that it's a valid use case that the portlet uses runtime tag to embed another portlet -- even if it's a different instance of the same portlet. In this case, it's hard or impossible to know whether different instances of the same portlet are real, or just caused by the ticket's kind of usage. So we choose to add a limit for how many levels the runtime tag can embed portlets in the same render chain.

If the above assumption is wrong, which is to say, we want to disallow different instances of the same portlet to embed each other, then we can just check the portlet's root id. That will be much easier, without the need to add new property, but changes the current behavior of runtime tag.

**Comment by dantewang** [comment]
@yuhai There are conflicts, please resend or force push, thanks!

**Comment by tinatian** [comment]
@yuhai @dantewang Could you please modify the logic to avoid embedding an portlet of the same type? For example instace_1 of PortletA can not embed instance_2 of Portlet_A. This kind of embedding does not make sense to me.

Close, please resend.

Thanks.
Tina

**Pull request closed without merging**
