### PR TITLE
[Remove unused reference field]LPS-166158 Remove reference field _companyService from PortalInstance…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-166158

ci:test:relevant has been run in https://github.com/slnn/liferay-portal/pull/653 all tests are passed.

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
Wait for test result and QA review.

**Comment by zhangyan0701** [comment]
ci:test:system

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
