### PR TITLE
[Remove unused field] LPS-198885 Remove unused reference field in class EditLayoutModeProductNavigationControlMenuEntry

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(10/12 9:54)

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
cc @shuyangzhou

**Pull request closed without merging**
