### PR TITLE
Lps 152440 6 6

### PR DESCRIPTION
**Pull request by slnn**
/cc @dantewang @tinatian

### CODE REVIEW

**Comment by slnn** [comment]
ci:stop

**Comment by slnn** [comment]
ci:test:acceptance

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/941

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
