### PR TITLE
[Bug Fix]LPS-148969 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina.

**Comment by tinatian** [comment]
@ericyanLr is there a ci test covering this? 

Tina

**Comment by ericyanLr** [comment]
Hi @tinatian ,

I don't think so, I did not find any test classes under `modules/apps/bean-portlet`

**Comment by ericyanLr** [comment]
Hi @tinatian ,

I don't think so, I did not find any test classes under `modules/apps/bean-portlet`

**Comment by catarineaguiar** [comment]
@tinatian I'll reproduce the bug locally with your changes and analyse the Acceptance failures. Thats all I can do.

**Comment by catarineaguiar** [comment]
@tinatian the bug validation passed, but this message is appearing in the logs:

```
16:06:45,898 DEBUG [DebugPhaseListener:69] BEFORE phaseId=[RESTORE_VIEW 1] viewId=[null]
16:06:45,930 DEBUG [DebugPhaseListener:53] AFTER phaseId=[RESTORE_VIEW 1] viewId=[/WEB-INF/views/view.xhtml]
16:06:45,932 DEBUG [DebugPhaseListener:69] BEFORE phaseId=[RENDER_RESPONSE 6] viewId=[/WEB-INF/views/view.xhtml]
16:06:46,030 DEBUG [DebugPhaseListener:53] AFTER phaseId=[RENDER_RESPONSE 6] viewId=[/WEB-INF/views/view.xhtml]
```

And there is a semver error, but I don't know if it is related:

```
   [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/object/object-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.object.constants                       MINOR      2.6.0      2.6.0      2.7.0      VERSION INCREASE REQUIRED
     [exec]     	<   class      com.liferay.object.constants.ObjectViewFilterColumnConstants
     [exec]     		+   field      FILTER_TYPE_DATE_RANGE
     [exec]     			+   access     final
     [exec]     			+   access     static
     [exec]     			+   constant   date_range
     [exec]     			+   return     java.lang.String
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 20.1.0
```
```
 [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/object/object-admin-rest-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.object.admin.rest.dto.v1_0             MINOR      3.6.0      3.6.0      3.7.0      VERSION INCREASE REQUIRED
     [exec]     	<   class      com.liferay.object.admin.rest.dto.v1_0.ObjectViewFilterColumn
     [exec]     		+   field      valueSummary
     [exec]     			+   access     protected
     [exec]     			+   annotated  com.fasterxml.jackson.annotation.JsonProperty
     [exec]     				+   property   access='READ_ONLY'
     [exec]     			+   annotated  com.liferay.portal.vulcan.graphql.annotation.GraphQLField
     [exec]     			+   annotated  com.liferay.portal.vulcan.graphql.annotation.GraphQLField
     [exec]     			+   return     java.lang.String
     [exec]     		+   method     getValueSummary()
     [exec]     			+   annotated  io.swagger.v3.oas.annotations.media.Schema
     [exec]     			+   return     java.lang.String
     [exec]     		+   method     setValueSummary(com.liferay.petra.function.UnsafeSupplier)
     [exec]     			+   annotated  com.fasterxml.jackson.annotation.JsonIgnore
     [exec]     			+   return     void
     [exec]     		+   method     setValueSummary(java.lang.String)
     [exec]     			+   return     void
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 5.7.0
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-38/test-portal-acceptance-pullrequest(master)/378/modules-semantic-versioning-jdk8/0/4/jenkins-console.txt.gz?authuser=0)

**Comment by vicnate5** [comment]
@tinatian This is good to go, the bug scenario was tested by @catarineaguiar which covers a bean portlet. This doesn't cause any other portlet deployment regressions for the other JSF sample portlets.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
