### PR TITLE
[Component with its own class name as service type] LPS-201312 Refactor Resource components from Commerce module

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-201312

In the last push, I only change the methods from public to protected in BaseCommerceResource.

comparison link: https://github.com/liferay-core-infra/liferay-portal/compare/58437c60d7826987853d506a34d7d01cce163bce..b75c56aeba3372229e735f0f937f9c06712c2c39

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by rafaprax** [comment]
Hey @MrJohn1911, make the methods into the base class `protected` instead of public. Thx

**Comment by MrJohn1911** [comment]
ci:test:sf

**Review by rafaprax — APPROVED** [review]

**Comment by dantewang** [comment]
@111Anna Please run a startup comparison for this.

**Comment by 111Anna** [comment]
@dantewang I ran the PR on CE and DXP, the test results seems normal.

Here are test results:

**CE:**

Portal Version |GitId | Average Startup (ms) | % | Average Shutdown (ms) | % | Open File |Thread Create |Open Prepared Statement |Open Query|Open SQL|Open service tracker|Open bundle tracker |ACTIVE | SATISFIED|Objects | shallow size (MB) |retained size (MB)
-- | -- | -- | -- | -- | -- | -- | -- | -- | --|--|--|--|--|--|--|--|--
Baseline| 820f09a0e |12111.3| - | 2327.3 | - | 1408 | 76 | 64 | 96|771|5006|33| 2825|8337| 6974895 |339 |339
LPS-201312|-| 12102 | 0.08% | 2337 | -0.42% |  1408| 77| 64 |96| 772|5009|33|2825|8336|7032169  |347|347



**DXP:**

Portal Version | GitId | Average Startup (ms) | % | Average Shutdown (ms) | % | Open File |Thread Create |Open Prepared Statement |Open Query|Open SQL|Open service tracker|Open bundle tracker |ACTIVE | SATISFIED|Objects | shallow size (MB) |retained size (MB)
-- | -- | -- | -- | -- | -- | -- | -- | -- | --|--|--|--|--|--|--|--|--
Baseline | 820f09a0e |12571| - | 2665.3| - | 1530 | 77 | 64 | 96|839|5426|33|3054|8948| 7324951 |349|349
LPS-201312 | - | 12612 | -0.33% |  2708.6| -1.62% | 1530 |78 | 64 |96|838 |5427|33|3054|8947| 7274915 |342|342

**Comment by dantewang** [comment]
@MrJohn1911 Conflicts, please resend.

**Pull request closed without merging**
