### PR TITLE
[Component with its own class name as service type] LPS-193631 Refactor ModelResourcePermission components

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-193631

Hey @shuyangzhou, I could not apply the changes that you requested [here](https://github.com/liferay-core-infra/liferay-portal/pull/5293#issuecomment-1696546146) in the last two commits because these components have multiple usages in other components. Also, I had to change their properties because they were not unique, so if I had not change, the right component might not be referenced.

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:data-engine

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
The "model.class.name" value should match the generic type value. Otherwise it is just too weird, we won't have control over what value could be used as the value. If you need a special tag for it, you can add a new one, but don't use the model.class.name for this purpose.

@kevhlee can you add a SF check to make sure for any class that implements com.liferay.portal.kernel.security.permission.resource.ModelResourcePermission, its "model.class.name" property value must match the generic type from the ModelResourcePermission<?>. If we have usages that already not following this rule, we will need a round of clean up, please give the list to @dantewang

**Pull request closed without merging**
