### PR TITLE
[Remove Stream/Optional: Phase 4] LPS-182656 Remove Stream and optional usages for class: DDMRESTDataProvider

### PR DESCRIPTION
**Pull request by W2jx**
Resend,

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4459

Changes:

- Use directly `if (!entires.isEmpty())`

- Optimize the use of Map.

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:forms

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(5/10 7:50)

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/134591

**Pull request closed without merging**
