### PR TITLE
[Jasper] LPD-37379 Apply Tomcat Jasper in gradle plugin | 12-5

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:frontend

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:84224193

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 84224193.
> 
> Job Link: [generate-testray-csv](https://test-1-10.liferay.com/job/generate-testray-csv/150/)
> 
> Testray CSV Link: [testray-results-84224193.csv](https://test-1-10.liferay.com/userContent/jobs/generate-testray-csv/builds/150/testray-results-84224193.csv)

No unique failure in frontend.

**Comment by dantewang** [comment]
ci:report:84240742

**Comment by dantewang** [comment]
ci:report:84220247

relevant

**Comment by dantewang** [comment]
No unique failure in relevant.

**Comment by dantewang** [comment]
ci:test:core-functional

Only need to check LocalFile.Locale#UseDefaultPortetTitleWithoutTranslation.

**Comment by dantewang** [comment]
ci:test:app-servers

**Comment by dantewang** [comment]
ci:report:84313835

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 84313835.
> 
> Job Link: [generate-testray-csv](https://test-1-8.liferay.com/job/generate-testray-csv/223/)
> 
> Testray CSV Link: [testray-results-84313835.csv](https://test-1-8.liferay.com/userContent/jobs/generate-testray-csv/builds/223/testray-results-84313835.csv)

LocalFile.Locale#UseDefaultPortetTitleWithoutTranslation passed this time. No unique failure in core-functional.

**Comment by dantewang** [comment]
ci:report:84313840

**Comment by dantewang** [comment]
ci:test:app-servers

Only need to double check LocalFile.OSGIConfiguration#RecreateDefaultFactoryConfig.

**Comment by dantewang** [comment]
ci:test:app-servers

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
> ### ❌ ci:test:app-servers - 3 out of 182 jobs passed in 1 hour 37 minutes
> Click here for more details.
> ##### Test bundle downloads:
> * [liferay-portal-bundle-tomcat.tar.gz](https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10544/bundles/liferay-portal-bundle-tomcat.tar.gz)

Checking Testray, `RecreateDefaultFactoryConfig` actually passed on JBoss 7.4 in this run.

**Comment by shuyangzhou** [comment]
ci:forward:force

Thanks @dantewang !

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/156694

**Comment by shuyangzhou** [comment]
ci:stop

**Pull request closed without merging**
