### PR TITLE
 LPD-28758 Add default admin user configuration to company creation

### PR DESCRIPTION
**Pull request by devopsmystic**

### CODE REVIEW

**Comment by devopsmystic** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@devopsmystic Could you please add test to cover your changes?

Thanks.
Tina

**Comment by devopsmystic** [comment]
Hi @tinatian  
cc @dantewang 
this the commit for the integration test https://github.com/liferay-core-infra/liferay-portal/pull/7289/commits/73e4ff035262851c8cc8ee92ad5bf2b2099c8a1d

Regards,
Madhu

**Comment by devopsmystic** [comment]
Thanks for the detailed comments @dantewang , I will open a new PR with the updated Junit tests

**Pull request closed without merging**
