### PR TITLE
[OrderByComparator] LPD-26703 Clean up and Apply Singleton in layout module part I

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:echo

**Comment by MrJohn1911** [comment]
ci:report:2571623746

**Comment by MrJohn1911** [comment]
ci:report:2571648741

**Comment by MrJohn1911** [comment]
ci:test:echo

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:echo

**Comment by MrJohn1911** [comment]
ci:report:2571907432

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
New changes are needed! I'll fix it and send it back. THX
CC: @titokenzo

**Pull request closed without merging**
