### PR TITLE
LPS-144201 Move usages of java-diff.jar and daisydiff.jar to a new module

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by guilhermedcamacho** [comment]
Hey @vicnate5, can you help me to analyze these tests results?

**Comment by vicnate5** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
@guilhermedcamacho This is causing some dependency issues in multiple modules
```
2021-12-23 15:58:46.546 ERROR [Framework Event Dispatcher: Equinox Container: 87f6b39f-09ee-4dca-ad78-f16bcb2b3b38][Framework:93] FrameworkEvent ERROR 
org.osgi.framework.BundleException: Could not resolve module: com.liferay.ratings.page.ratings.web [117]
  Unresolved requirement: Require-Capability: osgi.extender; filter:="(&(osgi.extender=jsp.taglib)(uri=http://liferay.com/tld/ratings))"
    -> Provide-Capability: osgi.extender; osgi.extender="jsp.taglib"; version:Version="3.0.14"; uri="http://liferay.com/tld/ratings"
       com.liferay.ratings.taglib [1031]
         Unresolved requirement: Require-Capability: osgi.extender; filter:="(&(osgi.extender=jsp.taglib)(uri=http://liferay.com/tld/frontend))"
           -> Provide-Capability: osgi.extender; osgi.extender="jsp.taglib"; version:Version="7.0.0"; uri="http://liferay.com/tld/frontend"
              com.liferay.frontend.taglib [579]
                Unresolved requirement: Import-Package: com.liferay.diff; version="1.0.0"

	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi.jar:?]
2021-12-23 15:58:46.554 DEBUG [Start Level: Equinox Container: 87f6b39f-09ee-4dca-ad78-f16bcb2b3b38][BundleStartStopLogger:55] STARTED com.liferay.knowledge.base.item.selector.api_5.0.6 [121]
2021-12-23 15:58:46.555 ERROR [Framework Event Dispatcher: Equinox Container: 87f6b39f-09ee-4dca-ad78-f16bcb2b3b38][Framework:93] FrameworkEvent ERROR 
org.osgi.framework.BundleException: Could not resolve module: com.liferay.knowledge.base.api [120]
  Unresolved requirement: Import-Package: com.liferay.diff; version="1.0.0"

	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi.jar:?]
```
See additional errors at https://testray.liferay.com/reports/production/logs/2021-12/test-1-32/test-portal-acceptance-pullrequest(master)/1726/lpkg-release-jdk8/0/0/jenkins-console.txt.gz

The issue is caught when we build portal modules into LPKGs.
You can do this locally by running `ant build-app-lpkg-release` from the modules directory.

**Comment by guilhermedcamacho** [comment]
> @guilhermedcamacho This is causing some dependency issues in multiple modules
> 
> ```
> 2021-12-23 15:58:46.546 ERROR [Framework Event Dispatcher: Equinox Container: 87f6b39f-09ee-4dca-ad78-f16bcb2b3b38][Framework:93] FrameworkEvent ERROR 
> org.osgi.framework.BundleException: Could not resolve module: com.liferay.ratings.page.ratings.web [117]
>   Unresolved requirement: Require-Capability: osgi.extender; filter:="(&(osgi.extender=jsp.taglib)(uri=http://liferay.com/tld/ratings))"
>     -> Provide-Capability: osgi.extender; osgi.extender="jsp.taglib"; version:Version="3.0.14"; uri="http://liferay.com/tld/ratings"
>        com.liferay.ratings.taglib [1031]
>          Unresolved requirement: Require-Capability: osgi.extender; filter:="(&(osgi.extender=jsp.taglib)(uri=http://liferay.com/tld/frontend))"
>            -> Provide-Capability: osgi.extender; osgi.extender="jsp.taglib"; version:Version="7.0.0"; uri="http://liferay.com/tld/frontend"
>               com.liferay.frontend.taglib [579]
>                 Unresolved requirement: Import-Package: com.liferay.diff; version="1.0.0"
> 
> 	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682) ~[org.eclipse.osgi.jar:?]
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662) ~[org.eclipse.osgi.jar:?]
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624) ~[org.eclipse.osgi.jar:?]
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555) ~[org.eclipse.osgi.jar:?]
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi.jar:?]
> 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi.jar:?]
> 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi.jar:?]
> 2021-12-23 15:58:46.554 DEBUG [Start Level: Equinox Container: 87f6b39f-09ee-4dca-ad78-f16bcb2b3b38][BundleStartStopLogger:55] STARTED com.liferay.knowledge.base.item.selector.api_5.0.6 [121]
> 2021-12-23 15:58:46.555 ERROR [Framework Event Dispatcher: Equinox Container: 87f6b39f-09ee-4dca-ad78-f16bcb2b3b38][Framework:93] FrameworkEvent ERROR 
> org.osgi.framework.BundleException: Could not resolve module: com.liferay.knowledge.base.api [120]
>   Unresolved requirement: Import-Package: com.liferay.diff; version="1.0.0"
> 
> 	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682) ~[org.eclipse.osgi.jar:?]
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662) ~[org.eclipse.osgi.jar:?]
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624) ~[org.eclipse.osgi.jar:?]
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555) ~[org.eclipse.osgi.jar:?]
> 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi.jar:?]
> 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi.jar:?]
> 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi.jar:?]
> ```
> 
> See additional errors at https://testray.liferay.com/reports/production/logs/2021-12/test-1-32/test-portal-acceptance-pullrequest(master)/1726/lpkg-release-jdk8/0/0/jenkins-console.txt.gz
> 
> The issue is caught when we build portal modules into LPKGs. You can do this locally by running `ant build-app-lpkg-release` from the modules directory (note this will make changes your tomcat bundle you won't be easily able to reverse - since it packages up all the module jars)

I added the **app.bnd** file and force-pushed now, Thanks @vicnate5 :+1:

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by guilhermedcamacho** [comment]
Hey @vicnate5 , is it possible to analyze the results by Testray Build link? I think some error happened with the generated report for Github integration.

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
> Hey @vicnate5 , is it possible to analyze the ci:test results by Testray Build link? I think some error happened with the generated report for Github integration. Thanks!

Hey @koor4356 , can you help me with these results?

**Comment by guilhermedcamacho** [comment]
Hey @zhangyan0701 , can you help me to analyse ci:test results? today was a day off for the guys in USA. Thanks!

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
Hi @guilhermedcamacho 

There are still some Unresolved requirement errors in some lpkg tests:
```
 [parallel] 2021-12-24 02:45:36.909 ERROR [Framework Event Dispatcher: Equinox Container: 613e0446-78f9-42b3-8bed-d79e29de3836][Framework:93] FrameworkEvent ERROR 
 [parallel] org.osgi.framework.BundleException: Could not resolve module: com.liferay.configuration.admin.web [122]
 [parallel]   Unresolved requirement: Require-Capability: osgi.extender; filter:="(&(osgi.extender=jsp.taglib)(uri=http://liferay.com/tld/frontend))"
 [parallel]     -> Provide-Capability: osgi.extender; osgi.extender="jsp.taglib"; version:Version="7.0.0"; uri="http://liferay.com/tld/frontend"
 [parallel]        com.liferay.frontend.taglib [669]
 [parallel]          Unresolved requirement: Import-Package: com.liferay.diff; version="1.0.0"
 [parallel] 
 [parallel] 	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi.jar:?]
```

Failed tests:
[lpkg-base-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1594064090)
[lpkg-hot-deployment-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1594064149)
[lpkg-independence-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1594064128)

Full console log:
https://testray.liferay.com/reports/production/logs/2021-12/test-1-27/test-portal-acceptance-pullrequest(master)/1231/lpkg-base-jdk8/0/0/jenkins-console.txt.gz

These tests all execute `build-app-lpkg-base` from the modules directory.

**Comment by koor4356** [comment]
Thanks @guilhermedcamacho, I am looking at the result.

**Comment by koor4356** [comment]
@guilhermedcamacho, There are still errors that are causing some dependency issues in multiple modules.
` ERROR [Framework Event Dispatcher: Equinox Container: 1e04c044-2457-4a2b-a6a0-6f57f75b8f52][Framework:93] FrameworkEvent ERROR 
 [parallel] org.osgi.framework.BundleException: Could not resolve module: com.liferay.wiki.editor.link.browse.web [364]
 [parallel]   Unresolved requirement: Require-Capability: alloyeditor.link.browse; filter:="(alloyeditor.link.browse=default)"
 [parallel]     -> Provide-Capability: alloyeditor.link.browse; alloyeditor.link.browse="default"
 [parallel]        com.liferay.frontend.editor.alloyeditor.web [291]
 [parallel]          Unresolved requirement: Require-Capability: osgi.extender; filter:="(&(osgi.extender=jsp.taglib)(uri=http://liferay.com/tld/frontend))"
 [parallel]            -> Provide-Capability: osgi.extender; osgi.extender="jsp.taglib"; version:Version="7.0.0"; uri="http://liferay.com/tld/frontend"
 [parallel]               com.liferay.frontend.taglib [1343]
 [parallel]                 Unresolved requirement: Import-Package: com.liferay.diff; version="1.0.0"
 [parallel] 
 [parallel] 	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi.jar:?]
 [parallel] 2021-12-28 07:48:41.755 DEBUG [Start Level: Equinox Container: 1e04c044-2457-4a2b-a6a0-6f57f75b8f52][BundleStartStopLogger:55] STARTED com.liferay.wiki.uad_6.0.11 [372]
 [parallel] 2021-12-28 07:48:41.755 ERROR [Framework Event Dispatcher: Equinox Container: 1e04c044-2457-4a2b-a6a0-6f57f75b8f52][Framework:93] FrameworkEvent ERROR 
 [parallel] org.osgi.framework.BundleException: Could not resolve module: com.liferay.wiki.service [371]
 [parallel]   Unresolved requirement: Import-Package: com.liferay.diff; version="1.0.0"
 [parallel] 
 [parallel] 	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi.jar:?]`

https://testray.liferay.com/reports/production/logs/2021-12/test-1-28/test-portal-acceptance-pullrequest(master)/1360/lpkg-base-jdk8/0/0/jenkins-console.txt.gz

Thanks!

**Comment by guilhermedcamacho** [comment]
I will take a look. Thank you! @zhangyan0701 @koor4356

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Hi @zhangyan0701 , I've checked the result of [lpkg-base-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1594670449?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1594669899%26cur%3D1%26delta%3D200%26tab%3Dresults%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) and there is no more dependency problems related to the module I've created `Unresolved requirement: Import-Package: com.liferay.diff; version="1.0.0"` , so I'm going to run the ci:test now, please help me to analyze these new results when finished. Thank you!

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by zhangyan0701** [comment]
Hi @guilhermedcamacho 

Error `Unresolved requirement: Import-Package: com.liferay.diff; version="1.0.0"` no longer happens. And no other related failures found.

**Comment by tinatian** [comment]
Hi @guilhermedcamacho  ,

The code looks good to me, here are something I would like you to do:
1. Rerun ant build-lib-versions and update this pull, I rerun it locally and see versions-complete.xml is changed, and the change is related to your code.
2. I see we have usages like this, it is related to diff utils too, could you please check if we can use the new diff util module you created? I would like it to be consistent.
testCompile group: "com.googlecode.java-diff-utils", name: "diffutils", version: "1.3.0"
3. You added a new app diff in this pull, please check the steps here and make sure you follow the rules https://liferay.atlassian.net/wiki/spaces/TEAMRM/pages/1662878423/How+to+add+a+new+app+to+the+release+bundle.


Thanks.
Tina.

**Comment by tinatian** [comment]
@guilhermedcamacho Code conflicts, please rebase and resend.

Thanks.

**Comment by tinatian** [comment]
ci:close

**Comment by guilhermedcamacho** [comment]
See #182

**Pull request closed without merging**
