### PR TITLE
[TS] LPS-173770 check if companyId matchs portlet's companyId in order to avoid creating Resource Permissions for non current company

### PR DESCRIPTION
**Pull request by jgarcialr**
This PR aims to solve [LPS-173770](https://issues.liferay.com/browse/LPS-173770): Adding a relationship between a company object and site object generates Duplicate entry for key 'IX_A9FF4B2C'

In the UserPersonalSitePermissions we iterate over every company and perform initPermissions even if the current companyId is not the same as the one of the portlet we are initializing.

This generates some inconsistencies while using data partitioning, per example when generating relationships between objects in a secondary virtual instance.

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:objects

**Comment by Kvale1733** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
@jgarcialr No regressions. Testing passed following ticket steps.

**Comment by yuhai** [comment]
@jgarcialr, your fix change is in the application-list module, please send the pr to the user liferay-echo to review. 

Thanks,
Hai

**Pull request closed without merging**
