### PR TITLE
Lpd 20946

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
ci:test:startup

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:core-functional

**Comment by tinatian** [comment]
ci:report:76371203

**Comment by tinatian** [comment]
ci:report:76371194

**Comment by tinatian** [comment]
ci:report:76371236

**Comment by tinatian** [comment]
ci:report:76371236

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:startup

**Comment by tinatian** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:76371465

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 76371508.
> 
> Job Link: [generate-testray-csv](https://test-1-1.liferay.com/job/generate-testray-csv/8151/)
> 
> Testray CSV Link: [testray-results-76371508.csv](https://test-1-1.liferay.com/userContent/jobs/generate-testray-csv/builds/8151/testray-results-76371508.csv)

com.liferay.on.demand.admin.internal.events.test.LogoutPostActionTest is unique. Will look into it.

Possibly due to something missing from this commit https://github.com/liferay-core-infra/liferay-portal/pull/7394/commits/93709e79384e63a2aef1868fd96cde9b6626f437.

@tinatian This commit was rejected by BChan. Can we just delegate the method taking the object to the method taking the ID? I was unable to think of a better way.

**Comment by tinatian** [comment]
@dantewang 
Can we just delegate the method taking the object to the method taking the ID?

No, we should not, as we are modifying production code to fix test.

Let's just mention it in the commit message and make it a temp workaround for the failed test

**Comment by dantewang** [comment]
Running CI at https://github.com/liferay-core-infra/liferay-portal/pull/7397

**Pull request closed without merging**
