### PR TITLE
[TS] LPS-187433 - add optional property for ISO-3166 compliance

### PR DESCRIPTION
**Pull request by wanderlast**
Hi! I'm sending this to you guys because you're the ones who helped handle the PTR ([PTR-4005](https://issues.liferay.com/browse/PTR-4005)), but if you feel this should go to a different team like AppSec, please let me know.

Per our discussion on PTR-4005, I've added a portal property and also refactored the related OSGI commands to account for this portal property. The two countries in question themselves were added to a separate JSON for easier tracking. I was somewhat unsure of how to name the property, so please let me know if you have any suggestions on wordsmithing or anything else. Thanks!

This is a resend of https://github.com/liferay-core-infra/liferay-portal/pull/4785. Auto SF was removing certain feature flag properties, so those changes were manually undone.

### CODE REVIEW

**Comment by Kvale1733** [comment]
@wanderlast All tests failed to run due to the following compile issue

```
[exec] > Task :apps:adaptive-media:adaptive-media-image-js-web:deployDependencies NO-SOURCE
     [exec] > Task :apps:adaptive-media:adaptive-media-image-js-web:deployConfigs NO-SOURCE
     [exec] > Task :apps:friendly-url:friendly-url-api:autoUpdateXml SKIPPED
     [exec] > Task :apps:portal-background-task:portal-background-task-api:autoUpdateXml SKIPPED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/address/address-impl/src/main/java/com/liferay/address/internal/osgi/commands/PortalAddressOSGiCommands.java:35: error: package com.liferay.portal.util does not exist
     [exec] import com.liferay.portal.util.PropsValues;
     [exec]                               ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/address/address-impl/src/main/java/com/liferay/address/internal/osgi/commands/PortalAddressOSGiCommands.java:92: error: cannot find symbol
     [exec] 		if (PropsValues.ISO_COUNTRIES_ENABLED) {
     [exec] 		    ^
     [exec]   symbol:   variable PropsValues
     [exec]   location: class com.liferay.address.internal.osgi.commands.PortalAddressOSGiCommands
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/address/address-impl/src/main/java/com/liferay/address/internal/osgi/commands/PortalAddressOSGiCommands.java:92: error: illegal start of type
     [exec] 		if (PropsValues.ISO_COUNTRIES_ENABLED) {
     [exec] 		   ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/address/address-impl/src/main/java/com/liferay/address/internal/osgi/commands/PortalAddressOSGiCommands.java:119: error: cannot find symbol
     [exec] 		if (PropsValues.ISO_COUNTRIES_ENABLED) {
     [exec] 		    ^
     [exec]   symbol:   variable PropsValues
     [exec]   location: class com.liferay.address.internal.osgi.commands.PortalAddressOSGiCommands
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/address/address-impl/src/main/java/com/liferay/address/internal/osgi/commands/PortalAddressOSGiCommands.java:119: error: illegal start of type
     [exec] 		if (PropsValues.ISO_COUNTRIES_ENABLED) {
     [exec] 		   ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/address/address-impl/src/main/java/com/liferay/address/internal/osgi/commands/PortalAddressOSGiCommands.java:127: error: cannot access com.liferay.petra.function.UnsafeSupplier
     [exec] 				countriesJSONArray.put(countryJSONObject);
     [exec] 				                  ^
     [exec]   class file for com.liferay.petra.function.UnsafeSupplier not found
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/address/address-impl/src/main/java/com/liferay/address/internal/search/spi/model/query/contributor/AddressModelPreFilterContributor.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 6 errors
     [exec] 
     [exec] > Task :apps:address:address-impl:compileJava FAILED

```
[Log](https://testray.liferay.com/reports/production/logs/2023-06/test-1-37/test-portal-acceptance-pullrequest(master)/12415/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:stop

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Pull request closed without merging**
