### PR TITLE
LPD-20946 9-10

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:test:object

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:6269651

startup

**Comment by dantewang** [comment]
ci:report:6257805

upgrade

**Comment by dantewang** [comment]
ci:report:6276498

**Comment by dantewang** [comment]
ci:report:6247292

object

**Comment by dantewang** [comment]
ci:report:6156037

**Comment by dantewang** [comment]
ci:test:object

> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 6247292.
> 
> Job Link: [generate-testray-csv](https://test-1-31.liferay.com/job/generate-testray-csv/161/)
> 
> Testray CSV Link: [testray-results-6247292.csv](https://test-1-31.liferay.com/userContent/jobs/generate-testray-csv/builds/161/testray-results-6247292.csv)

Suspicious failures in the previous ci-test-object run:

- LocalFile.Picklist#CanEditObjectWithState
- LocalFile.CreateObject#CanUpdateFieldLabelBeforePublished
- LocalFile.ObjectRootModel#CannotDeleteRelationshipWithChild

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 6276498.
> 
> Job Link: [generate-testray-csv](https://test-1-25.liferay.com/job/generate-testray-csv/151/)
> 
> Testray CSV Link: [testray-results-6276498.csv](https://test-1-25.liferay.com/userContent/jobs/generate-testray-csv/builds/151/testray-results-6276498.csv)

Some of the unique failures in the relevant run are 

> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 6276498.
> 
> Job Link: [generate-testray-csv](https://test-1-25.liferay.com/job/generate-testray-csv/151/)
> 
> Testray CSV Link: [testray-results-6276498.csv](https://test-1-25.liferay.com/userContent/jobs/generate-testray-csv/builds/151/testray-results-6276498.csv)

The failed integration tests either passed in the ci-test-object run (`SalesforceObjectEntryManagerImplTest`, `SugarCRMObjectEntryManagerImplTest`, `PublicationUserNotificationHandlerTest`), passed in my local (other object ones), or also failed in other PR or upstream runs.

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:test:startup

**Comment by tinatian** [comment]
ci:report:6590511

**Comment by tinatian** [comment]
ci:report:6570308

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 6439214.
> 
> Job Link: [generate-testray-csv](https://test-1-39.liferay.com/job/generate-testray-csv/421/)
> 
> Testray CSV Link: [testray-results-6439214.csv](https://test-1-39.liferay.com/userContent/jobs/generate-testray-csv/builds/421/testray-results-6439214.csv)

LocalFile.ObjectActions#CanReactivateAction
LocalFile.Object#CanDeleteRelationshipFromNativeObject
LocalFile.CreateObject#CanDeleteRelationOnRelationshipTab

Not sure if the 3 above is unique

**Comment by tinatian** [comment]
> 6276498

No unique failures in report.

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 6590511.
> 
> Job Link: [generate-testray-csv](https://test-1-30.liferay.com/job/generate-testray-csv/275/)
> 
> Testray CSV Link: [testray-results-6590511.csv](https://test-1-30.liferay.com/userContent/jobs/generate-testray-csv/builds/275/testray-results-6590511.csv)

No unique failures in report

**Comment by tinatian** [comment]
ci:test:core-functional

**Comment by tinatian** [comment]
> **Jenkins Build:**[test-portal-acceptance-pullrequest(master)#4954](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/4954/)
> **Jenkins Report:**[jenkins-report.html](https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4954/jenkins-report.html)
> **Jenkins Suite:**startup
> **Pull Request:**[liferay-core-infra#7417](https://github.com/liferay-core-infra/liferay-portal/pull/7417)
> **Testray Routine:**[EE Pull Request](https://testray.liferay.com/#/project/35392/routines/45357)
> **Testray Build:**[[master] ci:test:startup - dantewang > liferay-core-infra - PR#7417 - 2024-09-10[04:01:48]](https://testray.liferay.com/#/project/35392/routines/45357/build/6570308)
> **Testray Build ID:**6570308
> **Testray Importer:**[publish-testray-report#33790](https://test-1-32.liferay.com/job/publish-testray-report/33790/)

The "did not run " failures are unique to this pull

**Pull request closed without merging**
