### PR TITLE
LPS-165013 Cleanup StringTemplateResource usages

### PR DESCRIPTION
**Pull request by julschong**
@tinatian Hi Tina,
This pull converts most of new StringTemplateResourceUtil usages to use the new TemplateManagerUtil.getTemplate() method.
There are still some usages I wasn't sure how to remove in journal-service

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong 

Relevant is failing out due to
```
 [exec] Execution failed for task ':apps:fragment:fragment-entry-processor:fragment-entry-processor-freemarker:jar'.
     [exec] > Bundle com.liferay.fragment.entry.processor.freemarker-3.0.29.jar has errors
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:fragment:fragment-entry-processor:fragment-entry-processor-freemarker:jar'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$3(ExecuteActionsTaskExecuter.java:186)
```

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:stop

**Pull request closed without merging**
