### PR TITLE
[Equinox] LPS-184766 Part 1 Create modules and make Equinox internal

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou @tinatian The main goal of this PR is to avoid exposing any Equinox API and keep Equinox usage internal in the -impl module. From next PR I'll start to inline Equinox code.

### CODE REVIEW

**Comment by dantewang** [comment]
Resend here to fix the JDK 11 startup issue in https://github.com/liferay-core-infra/liferay-portal/pull/5271#issuecomment-1680758673

cc @catarineaguiar

**Comment by dantewang** [comment]
ci:test:smoke

**Comment by dantewang** [comment]
ci:test:jdk11

**Comment by Kvale1733** [comment]
ci:test:jdk11

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

jdk 11 smoke test passed o relevant.

**Comment by shuyangzhou** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5401

**Pull request closed without merging**
