### PR TITLE
[Circular dependency]Lps 186384 8 7

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-186384

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:object

**Comment by slnn** [comment]
ci:test:frontend-data-set

**Comment by catarineaguiar** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:object

**Comment by catarineaguiar** [comment]
ci:test:frontend-data-set

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:frontend-data-set

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
ci:test:frontend-data-set

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by dantewang** [comment]
@slnn Conflicts, please resend. Also, you put the logic in a Util, which has to call `*LocalServiceUtil`. Any reason not providing a component?

**Comment by tinatian** [comment]
@slnn See https://github.com/liferay-core-infra/liferay-portal/pull/5252

**Pull request closed without merging**
