### PR TITLE
[TS] LPS-159031

### PR DESCRIPTION
**Pull request by jcampoy**
https://issues.liferay.com/browse/LPS-159031

### CODE REVIEW

**Comment by jcampoy** [comment]
Hi @shuyangzhou , could you take a look to this fix?

btw the error was caused by https://github.com/brianchandotcom/liferay-portal/pull/74833/commits/627a77ea47c1d5ae6d1fedde9b76d8478f7873c9 

thank you

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by vicnate5** [comment]
@zhangyan0701 can you find out why our read/write database test doesn't catch this issue and update it?

**Comment by zhangyan0701** [comment]
> @zhangyan0701 can you find out why our read/write database test doesn't catch this issue and update it?

Refer to the steps, the issue needs to enable the log for category com.liferay.portal.dao.jdbc.aop.DefaultDynamicDataSourceTargetSource and check the log. I will update the test to cover it in [LRQA-76285](https://issues.liferay.com/browse/LRQA-76285).

**Comment by tinatian** [comment]
@vicnate5 @zhangyan0701 How's going on with the test?

Tina.

**Comment by tinatian** [comment]
@zhangyan0701  Could you please prioritize the fix for test? It is blocking the merge of this fix.

FYI @vicnate5 
Tina.

**Comment by zhangyan0701** [comment]
> @zhangyan0701 Could you please prioritize the fix for test? It is blocking the merge of this fix.
> 
> FYI @vicnate5 Tina.

Hi @tinatian Sorry for the delay! I am working on it now.

**Comment by zhangyan0701** [comment]
Hi @jcampoy 

When I test the fix, I saw below errors during portal startup after configuring r/w databases:
```
2022-08-03 14:55:21.111 ERROR [main][SqlExceptionHelper:142] Table 'master0803.ClassName_' doesn't exist
2022-08-03 14:55:21.117 ERROR [main][MainServlet:266] null
com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
```
I was testing with bundle that download from here: https://github.com/liferay-core-infra/liferay-portal/pull/1165#issuecomment-1195831083

The full portal log: [liferay.2022-08-03.log](https://github.com/liferay-core-infra/liferay-portal/files/9252672/liferay.2022-08-03.log)

Could you take a look on this error? Thanks!

**Comment by jcampoy** [comment]
Hi @zhangyan0701 ,

the bundle is not available https://github.com/liferay-core-infra/liferay-portal/pull/1165#issuecomment-1195831083  :  

```
Not Found
The requested URL /private/bundles/test-1-32/jobs/test-portal-acceptance-pullrequest(master)/builds/4933/liferay-portal-bundle-tomcat.tar.gz was not found on this server.
Apache Server at files.liferay.com Port 443
```

I am going to test building a new bundle from this pull-request, anyway I think the issue you found is not related with the changes in this PR because I was able to test the solution and it worked, what I know is that I tested with a PostgreSQL database, anyway I will try with hypersonic.

I will let you know the results of my new tests.

BR

**Comment by jcampoy** [comment]
@zhangyan0701 , @tinatian 
My tests worked fine and without issues in the first startup.

This was my config in portal-ext.properties:

```
admin.email.from.address=test@liferay.com
module.framework.properties.osgi.console=localhost:11311

mail.send.blacklist=\
        noreply@liferay.com,\
        noreply@domain.invalid,\
        test@domain.invalid

jdbc.default.driverClassName=org.hsqldb.jdbc.JDBCDriver
jdbc.default.url=jdbc:hsqldb:${liferay.home}/data/hypersonic/lportal;hsqldb.lock_file=false,hsqldb.write_delay=false
jdbc.default.username=sa
jdbc.default.password=

jdbc.read.driverClassName=org.hsqldb.jdbc.JDBCDriver
jdbc.read.url=jdbc:hsqldb:${liferay.home}/data/hypersonic/lportal;hsqldb.lock_file=false,hsqldb.write_delay=false
jdbc.read.username=sa
jdbc.read.password=

jdbc.write.driverClassName=org.hsqldb.jdbc.JDBCDriver
jdbc.write.url=jdbc:hsqldb:${liferay.home}/data/hypersonic/lportal;hsqldb.lock_file=false,hsqldb.write_delay=false
jdbc.write.username=sa
jdbc.write.password=

jdbc.counter.driverClassName=org.hsqldb.jdbc.JDBCDriver
jdbc.counter.url=jdbc:hsqldb:${liferay.home}/data/hypersonic/lportal;hsqldb.lock_file=false,hsqldb.write_delay=false
jdbc.counter.username=sa
jdbc.counter.password=

counter.jdbc.prefix=jdbc.counter.

    spring.infrastructure.configs=\
        /META-INF/infrastructure-spring.xml,\
        \
        /META-INF/counter-infrastructure-spring.xml,\
        /META-INF/dynamic-data-source-infrastructure-spring.xml,\
        /META-INF/hibernate-spring.xml
```

Could you try with a clean bundle? 

my logs:
[liferay.2022-08-04.log](https://github.com/liferay-core-infra/liferay-portal/files/9259575/liferay.2022-08-04.log)


Best regards,
Jose

**Comment by jcampoy** [comment]
cc @vicnate5

**Comment by zhangyan0701** [comment]
Hi @jcampoy 

Have you tried with two different database schema? I didn't see this error neither if the schema for read and write database are the same one.

Here is my portal-ext: 

```
liferay.home=/home/liferay/summer/bundles/testpr1165

jdbc.read.jndi.name=

jdbc.read.driverClassName=com.mysql.jdbc.Driver
jdbc.read.url=jdbc:mysql://localhost/master0803?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false&serverTimezone=GMT%2B8
jdbc.read.username=root
jdbc.read.password=root

jdbc.write.jndi.name=

jdbc.write.driverClassName=com.mysql.jdbc.Driver
jdbc.write.url=jdbc:mysql://localhost/master0803_1?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false&serverTimezone=GMT%2B8
jdbc.write.username=root
jdbc.write.password=root

setup.wizard.enabled=false
terms.of.use.required=false

tunneling.servlet.shared.secret=F0E1D2C3B4A5968778695A4B3C2D1E0F
tunneling.servlet.shared.secret.hex=true

browser.launcher.url=

company.security.strangers.verify=false

jsonws.web.service.paths.excludes=

enterprise.product.notification.enabled=false

passwords.default.policy.change.required=false

auth.token.check.enabled=false

counter.jdbc.prefix=jdbc.write.

spring.infrastructure.configs=\
    /META-INF/infrastructure-spring.xml,\
    \
    /META-INF/counter-infrastructure-spring.xml,\
    /META-INF/dynamic-data-source-infrastructure-spring.xml,\
    /META-INF/hibernate-spring.xml
```

The error also thrown in the automation test for r/w database configuration:
https://testray.liferay.com/home/-/testray/case_results/1935779838
Full console: https://testray.liferay.com/reports/production/logs/2022-08/test-1-32/test-portal-acceptance-pullrequest(master)/5074/functional-smoke-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by jcampoy** [comment]
Hi @zhangyan0701 .
 It does not make sense to have two different schemas if you do not configure data replication 
among them at database level. Have you done that?
Anyway, I think for testing this issue it is not necessary to have a full configuration and it can be simulated only having one schema, because at Liferay level the only thing you have to check is that a couple of data sources is created and they are used properly for read or write operations, with PostgreSQL I checked that having a couple of users to connect to the same database, one with only read permissions and other one with read/write permissions (and even I tested a third for the counter's data source pool), but as I said, I think all this staff is more complex to configure and it is not necessary for this simple test.
What do you think @tinatian  ?
BR

**Comment by vicnate5** [comment]
@zhangyan0701 I agree with @jcampoy that we should just test this with 1 schema to avoid needing full replication configured. I suspect our test passed previously because of this bug in the ticket. For MySQL, you should be able to add a new user [with read only privileges](https://stackoverflow.com/a/56057116) and use that user to access the DB for `jdbc.read.username`.

**Comment by zhangyan0701** [comment]
Thanks @jcampoy and @vicnate5 for the explanation! I will try with a user with read only permission and one database.

**Comment by zhangyan0701** [comment]
Hi @jcampoy @vicnate5 

I tried using a user with read only privileges to connect to database for `jdbc.read.username`.
Here are the commands that I created the user in MySQL:
```
CREATE USER 'lportal_readonly'@'localhost' IDENTIFIED BY 'Read_only123';
GRANT SELECT, SHOW VIEW ON *.* TO 'lportal_readonly'@'localhost';
flush privileges;
```
And here is my jdbc connection properties in portal-ext:
```
jdbc.write.jndi.name=

jdbc.write.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.write.url=jdbc:mysql://localhost/lportal?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false&serverTimezone=GMT
jdbc.write.username=root
jdbc.write.password=root

jdbc.read.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.read.url=jdbc:mysql://localhost/lportal?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false&serverTimezone=GMT
jdbc.read.username=lportal_readonly
jdbc.read.password=Read_only123
```
But I got many errors like below in portal startup:
```
2022-08-05 07:15:59.770 ERROR [main][SqlExceptionHelper:142] INSERT command denied to user 'lportal_readonly'@'localhost' for table 'Layout'
...
2022-08-05 07:16:14.536 ERROR [main][SqlExceptionHelper:142] INSERT command denied to user 'lportal_readonly'@'localhost' for table 'Country'
...
```
Looks like the read only user was trying to insert into tables, but it only have select permission.
And portal was not accessible.

**Comment by zhangyan0701** [comment]
Hi @jcampoy 

Could you take a look at the errors in my previous comment when you have time? Thanks in advance!

**Comment by jcampoy** [comment]
@zhangyan0701  i will try to take a look tomorrow

**Comment by jcampoy** [comment]
today I did not have time to test the issue with a read-only user, I will try the next week.
Anyway, if there is an error regarding the read data source we should think to handle it in a different ticket because the purpose of this ticket was only to add the fix for enabling it .

Also, I am nor really sure if the read data-source needs an user with write permissions as well, @tinatian , @shuyangzhou , what do you think about this?

**Comment by tinatian** [comment]
@jcampoy You have to fix the the error regarding the read data source first, then this issue, if not, there is no way to test if your fix here is valid or not.

> if the read data-source needs an user with write permissions as well
I am not sure about this either, but generally it does not make sense that you need write permission when you are read-only.

Please resend.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@zhangyan0701 Please fix the test and merge it failing to upstream, then we will know when the issue is fully resolved.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2691

**Pull request closed without merging**
