### PR TITLE
LPS-144496 File-install Properties | 12-27

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-144496 SF, inline, prepare for next
- LPS-144496 Directly use MODULE_FRAMEWORK_PORTAL_DIR and MODULE_FRAMEWORK_AUTO_DEPLOY_DIR in DirectoryWatcher
- LPS-144496 Directly use MODULE_FRAMEWORK_AUTO_DEPLOY_INTERVAL in DirectoryWatcher; since this property is only used by file install, move its default value (2000) to PropsValues.
- LPS-144496 Directly use MODULE_FRAMEWORK_DYNAMIC_INSTALL_START_LEVEL and MODULE_FRAMEWORK_WEB_START_LEVEL in DirectoryWatcher
- LPS-144496 SF, inline fields to directly use constants
- LPS-144496 Remove directly, this is not read by any component
- LPS-144496 Remove unused keys from FrameworkPropsKeys
- LPS-144496 Remove indirect properties that are not read by our implementation
- LPS-144496 Move "FILENAME" to ConfigurationFileInstaller because it's only related to configuration handling (not used in DirectoryWatcher)
- LPS-144496 Create explicit portal properties for arbitrary override properties (module.framework.properties) of file-install in portal.properties
- LPS-144496 Apply to DirectoryWatcher
- LPS-144496 SF, inline fields
- LPS-144496 SF, better portal property name
- LPS-144496 Create explicit portal properties for other properties defined and read from BundleContext in DirectoryWatcher
- LPS-144496 Apply usages
- LPS-144496 SF, inline fields
- LPS-144496 SF, simplify with identical check using Validator
- LPS-144496 Add renamed properties to VerifyProperties
- LPS-144496 Apply to functional test
- LPS-144496 Semantic versioning

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@dantewang Code conflicts, please rebase and resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
