### PR TITLE
[Replace Non-Blocking Usage] LPS-199715

### PR DESCRIPTION
**Pull request by JanisZhang**
resent:https://github.com/liferay-core-infra/liferay-portal/pull/5865
https://liferay.atlassian.net/browse/LPS-199715

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143176

cc @shuyangzhou

**Pull request closed without merging**
