### PR TITLE
LPD-21621 Only create ResourceActionsBag when populating or getting portlet supported actions

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:report:2555455515

**Comment by dantewang** [comment]
ci:report:2555465851

**Comment by dantewang** [comment]
ci:report:2555540585

**Comment by dantewang** [comment]
No unique failure in `relevant`.

`LocalFile.VirtualInstancesUpgrade#ViewVirtualInstancesArchive7310` from `ci-test-upgrade` is marked as unique. From the Poshi report, the failure is because of Poshi trying to click "Reindex" button when a reindex is in progress. And from the 2 pictures, the progress % increases BEFORE vs AFTER. This should be a timing issue, not caused by this change.

`PortalLogAssertorTest-functional-smoke-startup-cold-tomcat90-mysql57-jdk8/0/16` fails due to NPE at the very early stage of startup, during database connection pool initialization. This should not have anything to do with resource action, but I will retrigger the startup suite.

```
[beanshell] 2024-03-27 14:55:41.479 ERROR [main][PortalContextLoaderListener:70] java.lang.NullPointerException
[beanshell] java.util.concurrent.ExecutionException: java.lang.NullPointerException
[beanshell] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_381]
[beanshell] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_381]
[beanshell] 	at com.liferay.portal.spring.context.PortalContextLoaderListener._contextInitialized(PortalContextLoaderListener.java:404) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:213) [portal-impl.jar:?]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_381]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_381]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_381]
[beanshell] 	at com.liferay.shielded.container.internal.proxy.ContextClassLoaderInvocationHandler.invoke(ContextClassLoaderInvocationHandler.java:34) [com.liferay.shielded.container.impl.jar:?]
[beanshell] 	at com.liferay.shielded.container.internal.proxy.EventListenerInvocationHandler.invoke(EventListenerInvocationHandler.java:55) [com.liferay.shielded.container.impl.jar:?]
[beanshell] 	at com.sun.proxy.$Proxy6.contextInitialized(Unknown Source) [?:?]
[beanshell] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4460) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4914) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:683) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:658) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:661) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:689) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1888) [catalina.jar:9.0.83]
[beanshell] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_381]
[beanshell] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_381]
[beanshell] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.83]
[beanshell] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112) [?:1.8.0_381]
[beanshell] 	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:582) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:472) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1617) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:318) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:114) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:345) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:893) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:794) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322) [catalina.jar:9.0.83]
[beanshell] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_381]
[beanshell] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.83]
[beanshell] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [?:1.8.0_381]
[beanshell] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:248) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:433) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:921) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:9.0.83]
[beanshell] 	at org.apache.catalina.startup.Catalina.start(Catalina.java:772) [catalina.jar:9.0.83]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_381]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_381]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_381]
[beanshell] 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347) [bootstrap.jar:9.0.83]
[beanshell] 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478) [bootstrap.jar:9.0.83]
[beanshell] Caused by: java.lang.NullPointerException
[beanshell] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:461) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:479) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:986) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at com.liferay.portal.dao.jdbc.DataSourceFactoryImpl.registerConnectionPoolMetrics(DataSourceFactoryImpl.java:271) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.dao.jdbc.DataSourceFactoryImpl.initDataSourceHikariCP(DataSourceFactoryImpl.java:252) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.dao.jdbc.DataSourceFactoryImpl.initDataSource(DataSourceFactoryImpl.java:163) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.dao.jdbc.DataSourceFactoryUtil.initDataSource(DataSourceFactoryUtil.java:30) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.dao.init.DBInitUtil._initDataSource(DBInitUtil.java:198) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.dao.init.DBInitUtil.init(DBInitUtil.java:57) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.lambda$_contextInitialized$1(PortalContextLoaderListener.java:371) ~[portal-impl.jar:?]
[beanshell] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_381]
[beanshell] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_381]
[beanshell] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_381]
[beanshell] 	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_381]
```

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:report:2555839734

**Comment by dantewang** [comment]
The unique failure in https://github.com/liferay-core-infra/liferay-portal/pull/6815#issuecomment-2024445070 did not fail in the last run, it should be a flaky one.

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/148672

**Pull request closed without merging**
