### PR TITLE
[Remove Stream/Optional usage] LPS-174414 Remove usages of Stream for module: site-navigation-admin-web

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(2/3 8:16)

**Comment by W2jx** [comment]
no conflicts(2/7 14:08)

**Comment by W2jx** [comment]
no conflicts(2/8 9:05)

**Comment by W2jx** [comment]
no conflicts(2/9 10:25)

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
@W2jx No regressions.

**Comment by W2jx** [comment]
no conflicts(2/13 13:11)

**Comment by dantewang** [comment]
@W2jx Code conflict, please resend.

**Pull request closed without merging**
