### PR TITLE
[Remove Blocking Usages] LPS-196836 Removing Unnecessary Usages of ServiceProxyFactory.newServiceTrackedInstance with blocking set to true in classes RepositoryProviderImpl, LiferayFileShortcut and LiferayFolder

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(9/26 8:50)

**Comment by W2jx** [comment]
no conflicts(9/27 10:58)

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141439

**Pull request closed without merging**
