### PR TITLE
LPD-27658 Cleaning up cache for ResourceAction, ClassName and Counter when removing a company

### PR DESCRIPTION
**Pull request by achaparro**
Hi @tinatian,

This is the pending PR we had regarding the invalidation of caches when removing a company. We discussed it with @LuisOrtiz89 a few months ago, this was your latest assesment:

> Hi,
> 
> After a deep look at the pull, I have a concern about cluster.
> 
> As the CacheRegistry framework is NOT cluster aware. This is an existing bug, not caused by your changes.
> But here you are adding dependency on it, which may cause issue on cluster later.
> 
> My suggestion to achieve the goal you want to do here is:
> 
> 1- Mimic what we did for UserLocalServiceImpl's local cache _guestUsers at [https://github.com/liferay/liferay-portal/blob/960d4d480911c50e095b6e9afd0ffe29be0[…]l/src/com/liferay/portal/service/impl/UserLocalServiceImpl.java](https://github.com/liferay/liferay-portal/blob/960d4d480911c50e095b6e9afd0ffe29be0c6841/portal-impl/src/com/liferay/portal/service/impl/UserLocalServiceImpl.java#L7662)
> 2- Remove all the cache for a specific company by PortalCacheHelperUtil#removePortalCaches(String portalCacheManagerName, long companyId) Which you already did.
> 

Thanks!

### CODE REVIEW

**Comment by tinatian** [comment]
@achaparro I just took a quick look, this commit seems not consistent with the suggestion, it is still using CacheRegistryItem

https://github.com/liferay-core-infra/liferay-portal/pull/7657/commits/871d16b037ed34329b1ef39f37ad17e7aecbed9a

Also, did this pull pass ci?

**Comment by achaparro** [comment]
Hey @tinatian,

I did not have the chance to meet with @marianoalvarosaiz and @LuisOrtiz89 today but will do it tomorrow and come back to you for an explanation.

Regarding tests, yes they passed here:
https://github.com/liferay-database-infra/liferay-portal/pull/2409#issuecomment-2473787758

Cheers!

**Comment by marianoalvarosaiz** [comment]
Hi @tinatian,
 
 you're right but to overcome the cluster aware sync problem your advice was followed in: https://github.com/liferay-core-infra/liferay-portal/commit/871d16b037ed34329b1ef39f37ad17e7aecbed9a, https://github.com/liferay-core-infra/liferay-portal/pull/7657/commits/5afff76f9e2f47b25ea47a1da87f151d8962ef50, https://github.com/liferay-core-infra/liferay-portal/pull/7657/commits/c2598ec0f575ac1cc034e521a4be70c41e7bead1, https://github.com/liferay-core-infra/liferay-portal/pull/7657/commits/de28a2158fc07fc54e9c8993568ef80b0fbaf0b6 as it was done in `UserLocalServiceImpl`.

**Comment by tinatian** [comment]
@achaparro @marianoalvarosaiz I still do not understand why this is needed https://github.com/liferay-core-infra/liferay-portal/commit/871d16b037ed34329b1ef39f37ad17e7aecbed9a.

**Comment by marianoalvarosaiz** [comment]
@tinatian 

The scope of the LPD is to clean several objects/classes cached content: `ResourceAction`, `ClassName`, `Counter`.
All of the related classes, with cached content, implement `CacheRegistryItem`:

- `CounterFinderImpl`
- `RepositoryClassDefinitionCatalogImpl`
- `ClassNameLocalServiceImpl`

But not `ResourceActionLocalServiceImpl`

Since we are invoking the cleanup from a common point (`CompanyLocalServiceImpl`) we considered that instead of referencing each class individually in the listener cleanup code, which could imply having to add more and more classes in the future, we could make `ResourceActionLocalServiceImpl` implement `CacheRegistryItem` and invoke the `CacheRegistryUtil` class that cleans all the Item classes.

**Comment by achaparro** [comment]
Hi @tinatian,

To provide you more context, we mentioned making the ResourceActionImpl implement _CacheRegistryItem_ in our [conversation](https://liferay.slack.com/archives/C04KUSMCL7K/p1718870693847399) to follow the same pattern as the rest of the classes and make the code easier to maintain.

it is true that you [mentioned](https://liferay.slack.com/archives/C04KUSMCL7K/p1719445513805419) later that the CacheRegistry was not cluster aware but these changes made it clusterable

**Comment by achaparro** [comment]
Hi @tinatian,

I just want to add to Mariano's answer that, since [you also consider it a feasible idea initially](https://liferay.slack.com/archives/C04KUSMCL7K/p1718899989871439) and we solved the issue with the cluster in this PR, we thought is would be clearer to follow the _CacheRegistryItem_ approach to make it extensible and easier to maintain. 

Best regards.

**Comment by vicnate5** [comment]
@tinatian can this move forward with the answers provided here?

**Comment by tinatian** [comment]
@achaparro  As we talked, I am closing this pull, please resend.

**Pull request closed without merging**
