### PR TITLE
LPS-146089 Move liferay-icu4j.jar to module friendly-url-service

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
Regarding the commit [32dde63fcdd5234ff80086c2a923d1dd0fc8ecd0](https://github.com/liferay-core-infra/liferay-portal/pull/303/commits/32dde63fcdd5234ff80086c2a923d1dd0fc8ecd0), I confirmed the expected behavior with 
Drew Brokke from U&SM team. I also got the information in this [discussion](https://github.com/drewbrokke/liferay-portal/pull/272/commits/c2af07fb4e88095c704d4f5b24b975752a4fd9db#r96785855) on this commit to realize that. Finnaly I also tested with some languages and put the evidences [here](https://docs.google.com/document/d/1VvBGukAyVoCuING8SdAJz8svbnH03axDZJTbXjY_tDU/edit)

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by guilhermedcamacho** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@zhangyan0701 Can you check this one and see the potential problems in the base comment? Do we have test coverage for this? If not please add to test map and add NAT.

**Comment by zhangyan0701** [comment]
Hi @guilhermedcamacho 

Below errors thrown in test com.liferay.portal.tools.sample.sql.builder.SampleSQLBuilderTest.testGenerateAndInsertSampleSQL:
```
     [exec]     21:19:18,496 ERROR [ServiceProxyFactory:278] Service "com.liferay.portal.kernel.util.FriendlyURLNormalizer" is unavailable in 300000 milliseconds while setting field "_friendlyURLNormalizer" for class "com.liferay.portal.kernel.util.FriendlyURLNormalizerUtil", will retry...
     [exec]     21:24:18,505 ERROR [ServiceProxyFactory:278] Service "com.liferay.portal.kernel.util.FriendlyURLNormalizer" is unavailable in 300000 milliseconds while setting field "_friendlyURLNormalizer" for class "com.liferay.portal.kernel.util.FriendlyURLNormalizerUtil", will retry...
```
Full Jenkins Console:
https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=4/239610/consoleFull

This caused [an amount of modules unit tests](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1608644562&testrayComponentId=1310733899&testrayRunId=1608678786&statuses=3) were aborted.

Could you take a look at this?

@vicnate5 We don't have test coverage for this, I created ticket https://issues.liferay.com/browse/LRQA-73126 and will work on it.

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:backend-hypersonic

**Comment by vicnate5** [comment]
@zhangyan0701 Can you check the fresh results here?

**Comment by zhangyan0701** [comment]
The previous unit test failure was fixed. No other issue found.

**Comment by guilhermedcamacho** [comment]
@tinatian , this PR is ready for your review. Thanks!

**Comment by guilhermedcamacho** [comment]
@tinatian rebase done :+1:

**Comment by tinatian** [comment]
@guilhermedcamacho 
With this pull, both rss-impl and friendly-url-server have a class named `Normalizer`, and both classes have similar logic, and both modules are compileIncluded "com.ibm.icu4j" jar. 

We should move the logic of `Normalizer` into a separate module, and make rss-impl and friendly-url-server as clients of the new module.

Please resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by guilhermedcamacho** [comment]
See #328

**Pull request closed without merging**
