### PR TITLE
[Test Fix] LPD-38914 Fix external data source tests

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian 1) the first commit fixes an issue always happening when I run the test locally; 2) the second commit is based on the Slack discussion with Alberto.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@julschong I see you also mentioned that the upgrade process did not run; did you see that from any CI result or when you tried to run the tests locally? The CI result linked in the ticket only showed the issue that the upgrade process can't find the table.

**Comment by dantewang** [comment]
@tinatian The "caused by" linked in https://liferay.atlassian.net/browse/LPD-38914 is only the cause of the issue fixed in https://github.com/liferay-core-infra/liferay-portal/pull/7526/commits/cc283855b8e3df046b4ae2758be14a1a17bf9b32.

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
