### PR TITLE
[TS] LPD-23711

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__ <https://liferay.atlassian.net/browse/LPD-23711>

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:report:2562031290

**Comment by tinatian** [comment]
Hi @kevhlee 
This fix is in wrong direction.
We know "ORDER_BY_JPQL" has issue for sure, and with your changes, "ORDER_BY_JPQL" is still used to build sql which for sure will cause issue, even though it passed your test.
For your test, you just invoked some methods without any asserting the return value, this is really a confusing test.

```
_badColumnNameEntryPersistence.filterFindByType(
				_badColumnNameEntry.getType());

			_badColumnNameEntryPersistence.filterFindByType_PrevAndNext(
				_badColumnNameEntry.getBadColumnNameEntryId(),
				_badColumnNameEntry.getType(), null);
```

**Pull request closed without merging**
