### PR TITLE
[TS] LPS-149990

### PR DESCRIPTION
**Pull request by jcampoy**
https://issues.liferay.com/browse/LPS-149990

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@bronsonsoda can you check this one?
Acceptance failures https://test-1-1.liferay.com/job/generate-testray-csv/56/
Check relevant manually.

**Comment by bronsonsoda** [comment]
@tinatian no regressions found

@vicnate5

**Comment by jcampoy** [comment]
@tinatian could we move forward with this PR ?

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115785

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
