### PR TITLE
[commons-lang] LPD-19869 Remove org.apache.commons.lang.time.StopWatch usages

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:2549316718

**Comment by tinatian** [comment]
ci:report:2549289355

**Comment by julschong** [comment]
no unique failure

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/148137

**Pull request closed without merging**
