### PR TITLE
[Method References 2] LPS-164456 Convert method reference to ServiceTrackerMap in module commerce-product-service

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I convert method reference to ServiceTrackerMap in module commerce-product-service.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @catarineaguiar , Could you please help me check the test results ? Thanks!

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@W2jx No regressions.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
