### PR TITLE
[Remove Stream/Optional usage] LPS-176129 portal-impl

### PR DESCRIPTION
**Pull request by dantewang**
@slnn

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
