### PR TITLE
LPS-190920 Remove DSAccessTokenWebCacheItem

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:digital-signature

**Comment by julschong** [comment]
ci:test:digital-signature

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by julschong** [comment]
ci:test:digital-signature

**Comment by tinatian** [comment]
As we talked, please resend.

**Pull request closed without merging**
