### PR TITLE
[System Properties] LPS-156838 Move some properties required by module framework, and they only use simple method(systemProperties.get)

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I moved some properties required by module framework, and they only use simple method(systemProperties.get) in this pr.

Detial: https://github.com/liferay-core-infra/liferay-portal/pull/1018

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @catarineaguiar , Could you please help me check the test results ? Thanks!

**Comment by catarineaguiar** [comment]
@W2jx no regressions found. Can you rebase, please?

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
@tinatian this is a bit over engineered. All props are just for module framework, right? It should just be a ModuleFrameworkPropsValues, not even a keys class is needed. Don't make it a general system properties thing. And we are never re-reading it at runtime. Just sample them once and hold as static fields in the ModuleFrameworkPropsValues is fine.

**Pull request closed without merging**
