### PR TITLE
[Components with more than 1 service] LPS-187673 Refactor ManagedServiceFactory components from redirect-service, fragment-web and document-library-web modules

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-187673](https://liferay.atlassian.net/browse/LPS-187673)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:security

**Comment by Kvale1733** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
@RenanUmV No regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by shuyangzhou** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5409

**Pull request closed without merging**
