### PR TITLE
[Replace Non-Blocking Usage] LPS-199716 Replace non-blocking ServiceProxyFactory usages in classes DLFileShortcutLocalServiceImpl, DLFolderLocalServiceImpl, DLImpl and PortletRequestImpl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:stop:relevant

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(10/25 9:56)

**Comment by liuxingye** [comment]
Reviewing...

**Comment by liuxingye** [comment]
The [relevant](https://testray.liferay.com/home/-/testray/runs?tab=results&testrayBuildId=2446478281), [startup](https://testray.liferay.com/home/-/testray/runs?tab=results&testrayBuildId=2446446336) and [upgrade](https://testray.liferay.com/home/-/testray/runs?tab=results&testrayBuildId=2446467243) results are look good to me.

cc @zhangyan0701

**Comment by W2jx** [comment]
no conflicts(10/26 8:28)

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
