### PR TITLE
LPS-151745 Add LIFERAY_SHARED_ prefix to the attribute name to propagate the check access allowed to the portlet until the PortletFragmentEntryProcessor

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-151745

Hi Team,
I fixed the related bug by reading the attribute that DefaultLayoutTypeAccessPolicyImpl adds to the request to determine if the permissions check has failed. 
It was fixed OK in master but today we noticed that the fix is failing. Debugging in my local I can see that now the request is encapsulated and it causes the attribute is not present.
To fix it I have added the LIFERAY_SHARED_ prefix to the attribute name to achieve its propagation.
Could you please review it?
Thanks!
Regards

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@lfbesada I am confused. Why add a prefix fix your issue if "the request is encapsulated and it causes the attribute is not present"?

**Comment by lfbesada** [comment]
Hi @tinatian 

I am sorry, I misexplained myself.
I wanted to explain the reason because I didn't need to change the attribute name before, and now I am doing it. Although this explanation is not relevant I am going to try it again. 

What I tried to say before is that the fix was working OK a few days ago when [this](https://github.com/brianchandotcom/liferay-portal/pull/117066) pull request was merged.
I checked the solution in my local and also the QA Team double-checked it in the master branch.
But something has changed in the last few days in master that didn't happen before, and the fix doesn't work properly anymore.
By debugging I can see that the request that is used to call RuntimeTag.doTag doesn't have this attribute when the method returns. I wasn't able to determine what have changed the behavior.

So I have fixed it by adding this prefix to the attribute name. And with this prefix, the attribute is properly propagated to the processor. I think this is the only relevant point, I am sorry because of the misexplanation.

Thanks!
Regards

**Comment by tinatian** [comment]
@lfbesada I can not take this fix, we need to understand the root reason, or else, there might be other properties related issue covered. 
Please try to dig more to understand why this happens. What you can do is to monitor when your properties are set, and when your properties are read, there must be something happen between these two point, go to the call stack and check at different point between set and read, you should be able to find when the values are remove/covered.

Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by lfbesada** [comment]
Hi @tinatian 
Thanks for your feedback.
I think that the previous tests were bad. Trying to dig into the reason, I started a fresh installation pointed to master right after this PR was merged and repeated the test but this time failed. So my tests were badly executed before and it seems that the fix never worked in master.
Adding this commit the fix works properly, so this commit is needed to solve the bug.
How should I proceed? Should I send another pull request?
Thanks a lot and sorry for the inconvenience
Regards

**Pull request closed without merging**
