### PR TITLE
LPS-145918 Remove jodconverter.jar.jar and it's dependencies (juh.jar, jurt.jar, ridl.jar and unoil.jar)

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by guilhermedcamacho** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by guilhermedcamacho** [comment]
Hey @koor4356 , can you help me check the results? I think Victor is out today. Thanks!

**Comment by koor4356** [comment]
Got it, thanks!

**Comment by koor4356** [comment]
ci:test:default

**Comment by koor4356** [comment]
ci:test

**Comment by koor4356** [comment]
@guilhermedcamacho,
I am going to rerun ci:test because all db2 fails before they run. Also, wildfly failed to download upstream. I will do the analysis first in the morning tomorrow.

**Comment by koor4356** [comment]
@guilhermedcamacho 
Look goods.  Failures with wildfly and DB2 11.5 have nothing to do with this PR. 

Only this test below is failing. I believe it is a fluke because it passed when you run ci:test, but failed when I rerun the ci:test. You can review it.
`com.liferay.exportimport.test.LayoutSetPrototypePropagationTest > testPortletDataPropagationWithLinkEnabled FAILED
     [exec]     java.lang.NullPointerException
     [exec]     	at com.liferay.journal.internal.util.JournalContentImpl.getDisplay(JournalContentImpl.java:201)
     [exec]     	at com.liferay.journal.internal.util.JournalContentImpl.getDisplay(JournalContentImpl.java:350)
     [exec]     	at com.liferay.journal.internal.util.JournalContentImpl.getContent(JournalContentImpl.java:161)
     [exec]     	at com.liferay.journal.internal.util.JournalContentImpl.getContent(JournalContentImpl.java:130)
     [exec]     	at com.liferay.exportimport.test.LayoutSetPrototypePropagationTest.doTestPortletDataPropagation(LayoutSetPrototypePropagationTest.java:806)
     [exec]     	at com.liferay.exportimport.test.LayoutSetPrototypePropagationTest.testPortletDataPropagationWithLinkEnabled(LayoutSetPrototypePropagationTest.java:332)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.lang.Thread.run(Thread.java:745)`


https://testray.liferay.com/reports/production/logs/2022-01/test-1-31/test-portal-acceptance-pullrequest(master)/1866/modules-integration-mysql57-jdk8/0/22/jenkins-console.txt.gz

https://testray.liferay.com/home/-/testray/case_results/1603616136

Thanks!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go. 
Those libraries are not used after corresponding code moved to module in https://issues.liferay.com/browse/LPS-71382.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
