### PR TITLE
[Eliminate unused reference]LPS-200297 module: fragment-web, friendly-url-service

### PR DESCRIPTION
**Pull request by JanisZhang**
Remove unused reference fields in class `FragmentPortlet`, `ViewImportMVCRenderCommand`, `ImportMVCResourceCommand` and `FriendlyURLEntryLocalServiceImpl`. Thanks.
https://liferay.atlassian.net/browse/LPS-200297

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:friendly-url

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by melodywu** [comment]
ci:test:friendly-url

**Comment by melodywu** [comment]
Reviewing...

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by melodywu** [comment]
The [relevant](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2448936740), [startup](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2448992415), [friendly-url](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2449830673) and [echo](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2449706744) results are look good to me.

cc @zhangyan0701

**Comment by JanisZhang** [comment]
Thanks, Melody. @melodywu

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
