### PR TITLE
[Component with its own class name as service type] LPS-196226 Refactor Registry classes from multiple modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Related pull: https://github.com/liferay-core-infra/liferay-portal/pull/6173

Ticket: https://liferay.atlassian.net/browse/LPS-196226

This pull contains changes related only to frontend modules since the last edit

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:frontend

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:echo

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@MrJohn1911 Please update the format of breaking change, thanks!

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:frontend

**Comment by MrJohn1911** [comment]
ci:test:frontend

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:lima

**Comment by MrJohn1911** [comment]
ci:stop

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:lima

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:lima

**Comment by MrJohn1911** [comment]
ci:report:2488931259

**Comment by MrJohn1911** [comment]
ci:report:2488969036

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Comment by MrJohn1911** [comment]
ci:forward:force

**Comment by MrJohn1911** [comment]
ci:forward:force

**Pull request closed without merging**
