### PR TITLE
[TS] LPS-176517

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang

### CODE REVIEW

**Comment by dantewang** [comment]
@yuhai Do all of these packages need to be imported? Also, Spring-Extender doesn't have code dependency on these packages, right?

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@yuhai As it only has those dependencies, why you need to map other xsd in spring.schemas?

**Comment by catarineaguiar** [comment]
Tested locally and the issue is not reproducible with these changes.

Actual result:
```
2023-02-27 16:39:40.383 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:238] Processing com.liferay.blade.samples.jndiservicebuilder.service.jar
2023-02-27 16:39:46.321 ERROR [fileinstall-directory-watcher][DataSourceFactoryImpl:141] Unable to lookup jdbc/externalDataSource
javax.naming.NameNotFoundException: Name [java:comp/env/jdbc/externalDataSource] is not bound in this Context. Unable to find [java:comp].
	at org.apache.naming.NamingContext.lookup(NamingContext.java:840) ~[catalina.jar:9.0.71]
	at org.apache.naming.NamingContext.lookup(NamingContext.java:172) ~[catalina.jar:9.0.71]
	at javax.naming.InitialContext.lookup(InitialContext.java:417) ~[?:1.8.0_221]
	at com.liferay.portal.kernel.jndi.JNDIUtil._lookup(JNDIUtil.java:203) ~[portal-kernel.jar:?]
```

**Comment by yuhai** [comment]
> Do all of these packages need to be imported? Also, Spring-Extender doesn't have code dependency on these packages, right?

@dantewang, yes, Spring Extender doesn't have code dependency on these packages. The first commit can solve the issue. For the second commit, It should be necessary if map other schema. 

> As it only has those dependencies, why you need to map other xsd in spring.schemas?

@tinatian, actually, if removing spring.schemas and config packages from import-package in bnd.bnd. This will can work when network isn't down. When network is down, these mapping are necessary. Please see the below explanations:

spring.schemas is used in [PluggableSchemaResolver.java#L88]( https://github.com/spring-projects/spring-framework/blob/v5.2.22.RELEASE/spring-beans/src/main/java/org/springframework/beans/factory/xml/PluggableSchemaResolver.java#L88). When parse the schema, it will firstly invoke [PluggableSchemaResolver#resolveEntity](https://github.com/spring-projects/spring-framework/blob/v5.2.22.RELEASE/spring-beans/src/main/java/org/springframework/beans/factory/xml/PluggableSchemaResolver.java#L116) and resourceLocation will be mapped for **org/springframework/beans/factory/xml/spring-beans.xsd**. When network is down, this method will enter the [exception](https://github.com/spring-projects/spring-framework/blob/v5.2.22.RELEASE/spring-beans/src/main/java/org/springframework/beans/factory/xml/PluggableSchemaResolver.java#L132-L135) and return null. And then [ResourceEntityResolver#resolveEntity](https://github.com/spring-projects/spring-framework/blob/v5.2.22.RELEASE/spring-beans/src/main/java/org/springframework/beans/factory/xml/ResourceEntityResolver.java#L75-L132) will enter the [exception](https://github.com/spring-projects/spring-framework/blob/v5.2.22.RELEASE/spring-beans/src/main/java/org/springframework/beans/factory/xml/ResourceEntityResolver.java#L122-L127) and return null. This will cause the current issue.

Just talked with @dantewang, I will remove the second commit and add other defined schema config packages. And resend the pr.

**Pull request closed without merging**
