### PR TITLE
[Spring Beans] LPS-201446 module: subscription-service

### PR DESCRIPTION
**Pull request by JanisZhang**
Remove `CleanUpSubscriptionMessageListener` and corresponding destination registration as no one using it. Thanks.
https://liferay.atlassian.net/browse/LPS-201446

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Comment by JanisZhang** [comment]
ci:forward:force

**Pull request closed without merging**
