### PR TITLE
[Equinox Http] LPS-196987 ProxyContext & LPS-196986 Avoid actually using HttpServiceRuntime

### PR DESCRIPTION
**Pull request by dantewang**
This PR includes https://github.com/liferay-core-infra/liferay-portal/pull/5589

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by zhangyan0701** [comment]
ci:stop

**Comment by zhangyan0701** [comment]
There are some conflicts. Please resolve them and re-run tests.

**Comment by catarineaguiar** [comment]
please, remove qa-ignore label when rebase and re-run tests

**Comment by dantewang** [comment]
Resend with 2 PRs.

PR1: https://github.com/liferay-core-infra/liferay-portal/pull/5730

**Comment by dantewang** [comment]
PR2: https://github.com/liferay-core-infra/liferay-portal/pull/5731

**Pull request closed without merging**
