### PR TITLE
LPS-173655 fix Provision virtual instances via configuration not working

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-173655](https://issues.liferay.com/browse/LPS-173655)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@RenanUmV @rafaprax Please answer my questions on slack.

**Comment by tinatian** [comment]
Please see https://github.com/liferay-core-infra/liferay-portal/pull/3398

**Pull request closed without merging**
