### PR TITLE
LPS-145584 Avoid using WebServerServletTokenUtil, WorkflowPermissionUtil, XmlRpcUtil directly in modules

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina, Shuyang

Main Task: [LPS-143403](https://issues.liferay.com/browse/LPS-143403)
Sub Task: [LPS-145584](https://issues.liferay.com/browse/LPS-145584)

Thank you!

### CODE REVIEW

**Comment by tinatian** [comment]
@julschong Code looks good to me, wait for QA to scan test results.
@catarineaguiar Please help me scan test results.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
@julschong @tinatian no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116253

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
