### PR TITLE
[Remove Blocking usages]LPS-187718 portal-kernel | AssetSearcherFactoryUtil

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-187718

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by JanisZhang** [comment]
Force-pushed. I only changed the commit message. It shouldn't affect the test results. Thanks!

**Comment by JanisZhang** [comment]
Force-pushed. I only changed the commit message. It shouldn't affect the test results. Thanks!

**Pull request closed without merging**
