### PR TITLE
[Method References] LPS-162723 Convert method references to field references in modules journal-*

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I convert method references to field references in modules journal-*.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @catarineaguiar , Could you please help me check the test results ? Thanks!

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by dantewang** [comment]
@shuyangzhou @tinatian Forwarding this one as all tests passed review and changes are direct replacements.

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
