### PR TITLE
LPS-161428 Remove stream usage in EntityFieldConfigurationFieldOptionsProvider

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:reevaluate:1357401_2425

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
CI errors not related.
@shuyangzhou , this PR is ready for your review. Thanks!

**Comment by catarineaguiar** [comment]
ci:test:tango-acceptance

**Comment by guilhermedcamacho** [comment]
I talked with @catarineaguiar and we decided to run tango-acceptance suite, just in case.

**Comment by catarineaguiar** [comment]
ci:test:tango

**Comment by catarineaguiar** [comment]
@guilhermedcamacho no regressions found.

**Comment by guilhermedcamacho** [comment]
@shuyangzhou , this PR is ready for your review. Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122447

**Pull request closed without merging**
