### PR TITLE
[Convert method references]LPS-162487 Covert method references to field references in module com…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-162487

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Comment by slnn** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
@catarineaguiar Could you take a look at the tests when they finish?

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@shuyangzhou @tinatian All tests passed and changes are direct replacements. Asked Commerce team for a final check

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by tinatian** [comment]
@victoroscuro Please help me scan test results. Any reason you want to re-trigger the tests?


Tina

**Comment by victoroscuro** [comment]
@tinatian Checks are fine. Please check slack thread. Thanks

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123236

**Pull request closed without merging**
