### PR TITLE
[Method References 2] LPS-170790 Convert method reference to ServiceTracker in class ActionExecutorManagerImpl(portal-workflow-kaleo-runtime-impl)

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:help

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
@W2jx no regressions, you only need to resolve the conflicts.
Thanks

**Comment by W2jx** [comment]
Force-Push is just to resolve conflict about file `modules/apps/portal-workflow/portal-workflow-kaleo-runtime-api/bnd.bnd`

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(2022/12/14 9:27)

**Comment by W2jx** [comment]
no conflicts(12/15 9:21)

**Comment by W2jx** [comment]
no conflicts(2022/12/16 8:57)

**Comment by W2jx** [comment]
no conflicts(12/19 9:52)

**Comment by W2jx** [comment]
no conflicts（12/20 12:05）

**Pull request closed without merging**
