### PR TITLE
remove_deprecated_for_portal_kernel_part_Five

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

I have removed depreacted for:
"ModelValidatorUtil.java"
"SchedulerLifecycle.java"
"AggregateSuggester.java"
"getOperatingClassloader()"
"IndexableThreadLocal.java"
"PluginSearchEngineConfigurator.java"
"portal-kernel/src/com/liferay/portal/kernel/security/auth"
"portal-kernel/src/com/liferay/portal/kernel/security/jaas"
"LDAPSettings.java"

Thanks for checking. Also see https://github.com/jeffwu0724/liferay-portal/pull/41

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by kyle-miho** [comment]
failures are unrelated, pr should be good @jeffwu0724

**Comment by jeffwu0724** [comment]
Hey @tinatian , PR has been checked  by Kyle and is good to go

**Comment by tinatian** [comment]
@jeffwu0724 Please recheck the classes you removed in this commit https://github.com/liferay-core-infra/liferay-portal/pull/510/commits/f25d72e0402b9cc17aef2d46835b2fbc993d8ae4. There are still usages should be removed.

Tina.

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by vicnate5** [comment]
@bronsonsoda Once this job finishes, download the CSV here to reduce how much you need to analyze https://test-1-1.liferay.com/job/generate-testray-csv/44/

This can be imported into a spreadsheet

**Comment by bronsonsoda** [comment]
@jeffwu0724 no regressions found

@vicnate5

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115448

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
