### PR TITLE
[TS] LPS-178252 Add link for apple custom favicon

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-178252

Hello, I added a link to provide custom favicons for ios and safari browsers.
Please let me know if this should be sent else where or if there are any questions or comments about this.

Thank you!

### CODE REVIEW

**Comment by dantewang** [comment]
@brunofalc Does this belong to us?

**Comment by dantewang** [comment]
@fortunatomaldonado For TS tickets, please include `[TS]` in the PR title, as we often filter the PR list with certain keywords when reviewing.

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@fortunatomaldonado Please send this to front end core infra team.

Thanks.
Tina.

**Pull request closed without merging**
