### PR TITLE
[Eliminate unused reference]LPS-200625 module: notification,object, product-navigation

### PR DESCRIPTION
**Pull request by JanisZhang**
Remove unused reference fields in class `EmailNotificationType`, `NotificationQueueEntryLocalServiceImpl`, `ObjectViewDTOConverter` and `ControlPanelCategory`. thanks.
https://liferay.atlassian.net/browse/LPS-200625

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:object

**Comment by zhangyan0701** [comment]
ci:test:notifications

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
no regressions on upgrade suite

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143456

**Pull request closed without merging**
