### PR TITLE
LPD-8466 remove unused reference _urlStreamHandlerService

### PR DESCRIPTION
**Pull request by titokenzo**

### CODE REVIEW

**Comment by titokenzo** [comment]
ci:test:relevant

**Comment by titokenzo** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
@tinatian The reference was added by https://liferay.atlassian.net/browse/LPSA-49625 to declare a dependency (and start order) to resolve a bug. Usually we should verify whether the bug still exists if we remove this now. But I'm not sure about the current state of LPKG. Is this whole feature planned to be removed?

cc @vicnate5

**Comment by vicnate5** [comment]
@dantewang The plan to remove LPKGs from Marketplace usage is not finalized. We will need to continue to support them for now.

**Comment by dantewang** [comment]
@titokenzo We need to make sure that https://liferay.atlassian.net/browse/LPSA-49625 still passes with this change. If there's a test for the ticket, then we just need to verify that the test passes; if not, please try to manually test. Thanks!

**Comment by tinatian** [comment]
@titokenzo Close, please resend if needed.

Thanks.
Tina

**Pull request closed without merging**
