### PR TITLE
Jasper cleanup rebased

### PR DESCRIPTION
**Pull request by shuyangzhou**
@dantewang please rerun all the jasper related tests. If anything breaks, try to exclude the last commit, it should be the only risky commit in the pull.

@vicnate5 any updates on the jsp fragment bundle support usage? If we can get rid of that feature, we could clean up quite a lot more on top of this.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:test:frontend

**Comment by slnn** [comment]
ci:report:78682739

**Comment by slnn** [comment]
ci:report:78682751

**Comment by slnn** [comment]
ci:report:78683657

**Comment by slnn** [comment]
ci:report:78682739

**Comment by dantewang** [comment]
ci:report:78730136

**Comment by slnn** [comment]
ci:test:upgrade

**Comment by slnn** [comment]
CI Test results summary:

1. For core-functional: no unique failures, 45 Did not run Failures, from the history in testray, all of these tests have never been run.
2. For frontend , no unique failures and no  Did not run Failures
3. For upgrade,  no uniques faileres, two Did not run failures, from the Jenkins Console, it seems that these Did not run failures are caused by a time out of the upgrade process, I retrigger the upgrade test to double check.
4. For relevant, 11 unique failures( PortalLogAssertorTest-modules-integration-mysql57* 9,
com.liferay.headless.commerce.delivery.cart.resource.v1_0.test.CartItemResourceTest*1
com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspPrecompileTest*1), no Did not run failures.

The new pr without the last commit please see: https://github.com/liferay-core-infra/liferay-portal/pull/7681

/cc @dantewang

**Comment by shuyangzhou** [comment]
@slnn @dantewang if you find real failure caused by last commit, I will need manual reproduce steps.

**Comment by dantewang** [comment]
@shuyangzhou I believe the only unique failure is `com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspPrecompileTest#testRuntimeCompiledJsp`, and it's not caused by your last commit because it also failed in the PR Lily sent: https://testray.liferay.com/#/project/35392/routines/45357/build/78926929/case-result/78948167.

**Comment by shuyangzhou** [comment]
@dantewang can you track down what caused it to fail? Maybe it is a test issue.

**Comment by dantewang** [comment]
@shuyangzhou Sure

**Comment by dantewang** [comment]
@shuyangzhou It's a test issue, please see https://github.com/liferay-core-infra/liferay-portal/pull/7687

**Comment by shuyangzhou** [comment]
Thanks @dantewang !

**Pull request closed without merging**
