### PR TITLE
[Replace Non-Blocking Usage] LPS-199976 kernel/search

### PR DESCRIPTION
**Pull request by haydenzheng314**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5915
Ticket: https://liferay.atlassian.net/browse/LPS-199976
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by LisztLiszt** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@LisztLiszt Regression found in unit test


com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQueryTest
```
[junit] Testcase: testAddDocumentsWithinInterval(com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQueryTest):	Caused an ERROR
    [junit] No field on null with name _indexerRegistry
    [junit] java.lang.NoSuchFieldException: No field on null with name _indexerRegistry
    [junit] 	at com.liferay.portal.kernel.test.ReflectionTestUtil.getField(ReflectionTestUtil.java:126)
    [junit] 	at com.liferay.portal.kernel.test.ReflectionTestUtil.setFieldValue(ReflectionTestUtil.java:324)
    [junit] 	at com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQueryTest.setUp(IndexableActionableDynamicQueryTest.java:53)
    [junit] 
    [junit] 
    [junit] Testcase: testAddDocuments(com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQueryTest):	Caused an ERROR
    [junit] No field on null with name _indexerRegistry
    [junit] java.lang.NoSuchFieldException: No field on null with name _indexerRegistry
    [junit] 	at com.liferay.portal.kernel.test.ReflectionTestUtil.getField(ReflectionTestUtil.java:126)
    [junit] 	at com.liferay.portal.kernel.test.ReflectionTestUtil.setFieldValue(ReflectionTestUtil.java:324)
    [junit] 	at com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQueryTest.setUp(IndexableActionableDynamicQueryTest.java:53)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-32/test-portal-acceptance-pullrequest(master)/2607/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
