### PR TITLE
LPS-155715 DB partition cache

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
@tinatian possible regression:

`CleanServiceBuilderTaskTest`
```
[exec] com.liferay.portal.tools.db.support.ant.CleanServiceBuilderTaskTest > testCleanServiceBuilderMissingTable[MySQL] FAILED
     [exec]     /opt/dev/projects/github/liferay-portal/modules/util/portal-tools-db-support/test-classes/unit/com/liferay/portal/tools/db/support/ant/dependencies/build.xml:12: java.io.IOException: Server returned HTTP response code: 524 for URL: http://www.liferay.com/dtd/liferay-service-builder_7_0_0.dtd
     [exec]         at com.liferay.portal.tools.db.support.ant.CleanServiceBuilderTask.execute(CleanServiceBuilderTask.java:34)
     [exec]         at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
     [exec]         at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-07/test-1-31/test-portal-acceptance-pullrequest(master)/4120/modules-unit-jdk8/0/4/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/1090

**Pull request closed without merging**
