### PR TITLE
[PowerMock] LPS-152436 Remove powermock usages (Misc) part 4

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @tinatian,
I exclude  `AMImageHTMLExportImportContentProcessorTest` from https://github.com/liferay-core-infra/liferay-portal/pull/723.
I will rework this one after upgrading to Mockito 4. 

Thanks!
Janis

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @catarineaguiar,
Could you please help me scan test results. Thx!

Regards.
Janis.

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/117385

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
