### PR TITLE
[Remove unused reference] LPS-166167

### PR DESCRIPTION
**Pull request by JanisZhang**
This PR is to remove unused fields in `commerce-tax-web`. Thanks!
https://issues.liferay.com/browse/LPS-166167

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
No regressions found.

cc/ @zhangyan0701

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by dantewang** [comment]
@JanisZhang See https://github.com/liferay-core-infra/liferay-portal/pull/2214

**Pull request closed without merging**
