### PR TITLE
[System Properties] LPS-158206 New Feature 1: get properties by prefix

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian @W2jx

### CODE REVIEW

**Comment by dantewang** [comment]
@catarineaguiar Could you review the test results when they finish? Thanks!

**Comment by catarineaguiar** [comment]
@dantewang no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by W2jx** [comment]
no conflicts(6:17 PM)

**Comment by W2jx** [comment]
no conflicts(6:16 PM)

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122248

**Pull request closed without merging**
