### PR TITLE
[Components with more than 1 service] LPS-182629 Refactor FacetFactoryImpl components

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@daiazius There are unsatisfied references on startup
```
[beanshell] 2023-04-25 17:56:03.644 INFO  [main][SystemCheckOSGiCommands:131] Running "Declarative Service Unsatisfied Component Checker". You can run this by itself with command "ds:unsatisfied" in gogo shell.
[beanshell] 2023-04-25 17:56:19.125 WARN  [main][SystemCheckOSGiCommands:154] Declarative Service Unsatisfied Component Checker check result: 
[beanshell] Bundle {id: 130, name: com.liferay.portal.search, version: 8.0.68}
[beanshell] 	Declarative Service {id: 191, name: com.liferay.portal.search.internal.facet.folder.FolderFacetSearchContributorImpl, unsatisfied references: 
[beanshell] 		{name: _folderFacetFactory, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 202, name: com.liferay.portal.search.internal.facet.user.UserFacetSearchContributorImpl, unsatisfied references: 
[beanshell] 		{name: _userFacetFactory, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 196, name: com.liferay.portal.search.internal.facet.site.SiteFacetSearchContributorImpl, unsatisfied references: 
[beanshell] 		{name: _siteFacetFactory, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 194, name: com.liferay.portal.search.internal.facet.nested.NestedFacetSearchContributorImpl, unsatisfied references: 
[beanshell] 		{name: nestedFacetFactory, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 200, name: com.liferay.portal.search.internal.facet.type.TypeFacetSearchContributorImpl, unsatisfied references: 
[beanshell] 		{name: _assetEntriesFacetFactory, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 198, name: com.liferay.portal.search.internal.facet.tag.TagFacetSearchContributorImpl, unsatisfied references: 
[beanshell] 		{name: _assetTagNamesFacetFactory, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 187, name: com.liferay.portal.search.internal.facet.custom.CustomFacetSearchContributorImpl, unsatisfied references: 
[beanshell] 		{name: _customFacetFactory, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 185, name: com.liferay.portal.search.internal.facet.category.CategoryFacetSearchContributorImpl, unsatisfied references: 
[beanshell] 		{name: _categoryFacetFactory, target: null}
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-38/test-portal-acceptance-pullrequest(master)/7429/functional-smoke-tomcat90-oracle193-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/134178

**Pull request closed without merging**
