### PR TITLE
[Remove Stream/Optional usage] LPS-172601 remove_optional_in_translation_service

### PR DESCRIPTION
**Pull request by dantewang**
@jeffwu0724

### CODE REVIEW

**Comment by zhangyan0701** [comment]
Test [com.liferay.translation.exporter.test.XLIFF12TranslationInfoItemFieldValuesExporterTest](https://testray.liferay.com/home/-/testray/case_results/2159004628) failed with error:
```
	org.junit.ComparisonFailure: expected:<...ng="en-US"><![CDATA[[]]]></source>
					<ta...> but was:<...ng="en-US"><![CDATA[[, ]]]></source>
					<ta...>
```
Full console:
https://testray.liferay.com/reports/production/logs/2023-01/test-1-27/test-portal-acceptance-pullrequest(master)/6480/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0

And the SF failure should be related.

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:translation

**Comment by jeffwu0724** [comment]
ci:stop

**Comment by jeffwu0724** [comment]
ci:stop

**Pull request closed without merging**
