### PR TITLE
[Method References] LPS-161455 Convert method references to field references in module portal-search-similar-results-web

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I convert method references to field references in module portal-search-similar-results-web

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @catarineaguiar , Could you please help me check the test results when they finish ? Thanks!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by catarineaguiar** [comment]
@W2jx no regressions.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
