### PR TITLE
[Startup time optimization] LPS-160881

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to disable auto-import-default-references in portal-security-sso-openid-connect-persistence-service. Thanks!
https://issues.liferay.com/browse/LPS-160881

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @catarineaguiar , Could you please help to scan the test results? Thanks!

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121837

**Pull request closed without merging**
