### PR TITLE
[Method References 2] LPS-167249 Convert method reference to ServiceTrackerList in class SearchResultsPortlet

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(2/27 8:30)

**Comment by W2jx** [comment]
no conflicts(2/28 9:45)

**Comment by W2jx** [comment]
no conflicts(3/1 10:45)

**Comment by tinatian** [comment]
@W2jx For https://github.com/liferay-core-infra/liferay-portal/pull/3604/commits/d7e6a6bc6b9f9e25cbfd3d64e2e2566404deabf6, I do not understand what this is for "(interface SearchResultImageContributor was added as a consumer type in commit f67e5d88b23a3568c1e9ae2a022fb21c86c1dbbc)"

**Comment by W2jx** [comment]
Hi @tinatian , We did not provide an implementation for interface `SearchResultImageContributor`, but according to this [commit](https://github.com/liferay-core-infra/liferay-portal/commit/f67e5d88b23a3568c1e9ae2a022fb21c86c1dbbc#:~:text=%40ConsumerType,%7D), it should be provided for customers, so I did not remove it.

**Comment by W2jx** [comment]
no conflicts(3/7 9:02)

**Comment by W2jx** [comment]
no conflicts(3/8 15:25)

**Pull request closed without merging**
