### PR TITLE
[Remove Blocking Usages] LPS-202480 Removing Unnecessary Usages of ServiceProxyFactory.newServiceTrackedInstance with blocking set to true in class DLStoreImpl

### PR DESCRIPTION
**Pull request by W2jx**
Hi @dantewang , based on document https://help.liferay.com/hc/en-us/articles/360029131691-Server-Administration (part :Data Migration),
Screenshot_2023-12-12_14-20-28
 I think that the migrate documents from one repository to another function(https://github.com/liferay/liferay-portal/blob/0ba87639a5de2cfcbb4f3af2951d5009d3aa37f8/modules/apps/document-library/document-library-service/src/main/java/com/liferay/document/library/internal/convert/document/library/DocumentLibraryConvertProcess.java#L112-L126) we provide can still be used, so there is a change about PropsValues.DL_STORE_IMPL. Therefore, I have kept the original logic and only replaced ServiceProxyFactory.

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:dl-store

**Comment by dantewang** [comment]
ci:test:document

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
