### PR TITLE
LPD-38234: send password reset mail if adminPassword isn't set

### PR DESCRIPTION
**Pull request by devopsmystic**
this PR is to address the SaaS Automation requirement where [adminPassword](https://github.com/liferay-core-infra/liferay-portal/blob/master/modules/apps/portal-instances/portal-instances-service/src/main/java/com/liferay/portal/instances/internal/configuration/PortalInstancesConfigurationFactory.java#L69) wont be set in the osgi file (as these files will be versioned in github) and a welcome email with password reset link need to be sent.

### CODE REVIEW

**Comment by devopsmystic** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@devopsmystic This should not be done in CompanyLocalServiceImpl, it should be done when you create your company based on configuration.

Please resend.
Thanks.

**Comment by devopsmystic** [comment]
thanks for your response @tinatian , below are my observations

1. Currently the sendEmail flag is overridden here https://github.com/liferay-core-infra/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/UserLocalServiceImpl.java#L308 
2. Also due to this [code](https://github.com/liferay-core-infra/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/CompanyLocalServiceImpl.java#L290)  the password is always set and this if [statement](https://github.com/liferay-core-infra/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/UserLocalServiceImpl.java#L264) will never be executed and hence password reset email is not sent

**Comment by tinatian** [comment]
@devopsmystic so then you need a feature to allow not setting password to default, then use it. This is a new feature as current feature is set to default if no set.

**Pull request closed without merging**
