### PR TITLE
LPS-158169 Remove KaleoActivator since it is overlapping the KaleoPortalInstanceLifecycleListener. This will avoid to execute the _portalKaleoManager.deployKaleoDefaults() on every server/bundle restart twice

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:workflow

**Comment by rafaprax** [comment]
Hey @catarineaguiar, Can you help me scan these test results? Thx

**Comment by catarineaguiar** [comment]
ci:test:help

**Comment by catarineaguiar** [comment]
@rafaprax possible regression:

`CategoryFacetTest`
```
  [exec] com.liferay.portal.search.facet.faceted.searcher.test.CategoryFacetTest > testAggregation FAILED
     [exec]     org.junit.ComparisonFailure: {"from":0,"size":10000,"query":{"bool":{"must":[{"bool":{"must":[{"bool":{"should":[{"bool":{"must":[{"match":{"comments":{"query":"Sv9cXYgc"}}}],"should":[{"match_phrase":{"comments":{"query":"Sv9cXYgc","slop":50}}},{"match_phrase":{"comments":{"query":"Sv9cXYgc","boost":2.0}}}]}},{"bool":{"must":[{"match":{"content":{"query":"Sv9cXYgc"}}}],"should":[{"match_phrase":{"content":{"query":"Sv9cXYgc","slop":50}}},{"match_phrase":{"content":{"query":"Sv9cXYgc","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description":{"query":"Sv9cXYgc"}}}],"should":[{"match_phrase":{"description":{"query":"Sv9cXYgc","slop":50}}},{"match_phrase":{"description":{"query":"Sv9cXYgc","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title":{"query":"Sv9cXYgc"}}},{"match_phrase_prefix":{"title":{"query":"Sv9cXYgc"}}}]}}],"should":[{"match_phrase":{"title":{"query":"Sv9cXYgc","boost":2.0}}}]}},{"bool":{"must":[{"match":{"url":{"query":"Sv9cXYgc"}}}],"should":[{"match_phrase":{"url":{"query":"Sv9cXYgc","slop":50}}},{"match_phrase":{"url":{"query":"Sv9cXYgc","boost":2.0}}}]}},{"bool":{"should":[{"match_phrase_prefix":{"userName.text":{"query":"Sv9cXYgc"}}}]}},{"bool":{"must":[{"match":{"assetCategoryTitles_en_US":{"query":"Sv9cXYgc"}}}],"should":[{"match_phrase":{"assetCategoryTitles_en_US":{"query":"Sv9cXYgc","slop":50}}},{"match_phrase":{"assetCategoryTitles_en_US":{"query":"Sv9cXYgc","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"assetTagNames_en_US":{"query":"Sv9cXYgc"}}},{"match_phrase_prefix":{"assetTagNames_en_US":{"query":"Sv9cXYgc"}}}]}}],"should":[{"match_phrase":{"assetTagNames_en_US":{"query":"Sv9cXYgc","boost":2.0}}}]}},{"bool":{"must":[{"match":{"content":{"query":"Sv9cXYgc"}}}],"should":[{"match_phrase":{"content":
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-07/test-1-38/test-portal-acceptance-pullrequest(master)/2259/modules-integration-mysql57-jdk8/2/21/jenkins-console.txt.gz?authuser=0)

**Comment by rafaprax** [comment]
Hey @catarineaguiar, The changes I made didn't affect this part of the code but I still tried to reproduce it locally and I couldn't. So, we can consider this flaky. 

Thx

**Comment by rafaprax** [comment]
Hey @shuyangzhou, this pr is ready for your review. Thx

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
