### PR TITLE
[Remove immediate=true usgae core-infrastructure-3 part 2]Lps 169260 12 29

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-169260

### CODE REVIEW

**Comment by slnn** [comment]
ci:test

**Comment by slnn** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Comment by tinatian** [comment]
@slnn I do not think it is safe to remove immediate=true for the listeners in this commit https://github.com/liferay-core-infra/liferay-portal/pull/2876/commits/f266419ed043f000bbd37fa463328cf1563de079, I discard those changes, please see https://github.com/liferay-core-infra/liferay-portal/pull/3052

**Pull request closed without merging**
