### PR TITLE
LPS-172439 upgrade jettison to 1.15.3 

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-172439.
Thanks for checking!

### CODE REVIEW

**Comment by tinatian** [comment]
@jeffwu0724 Please rebase.

Tina

**Comment by jeffwu0724** [comment]
ant build-lib-versions is down again  at 1/25 - 9:43 am

```
Caused by: java.io.IOException: Server returned HTTP response code: 504 for URL: https://search.maven.org/solrsearch/select?q=g:org.jparsec+AND+a:jparsec&core=gav&rows=200&wt=json
```

**Comment by jeffwu0724** [comment]
fixed the code conflict by running auto generate, the previous tet result should be good

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
