### PR TITLE
[Components with more than 1 service] LPS-190147 Refactor DLOpenerGoogleDriveManager component

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-190147

In this pull, the module document-library-opener-google-drive-api was completed removed since Dante realized that the classes inside it were deprecated or have no usages and Adolfo Perez authored it, please see this [thread](https://liferay.slack.com/archives/CLD39UKM5/p1689344027372969).

CC: @tinatian @dantewang @rafaprax

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:lima

**Comment by MrJohn1911** [comment]
ci:test:online-editing

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:online-editing

**Comment by catarineaguiar** [comment]
@MrJohn1911 regression found:

```
     [exec] > Task :dxp:apps:document-library-opener:document-library-opener-onedrive-web:jar FAILED
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/dxp/apps/multi-factor-authentication/multi-factor-authentication-timebased-otp-service/src/main/java/com/liferay/multi/factor/authentication/timebased/otp/service/persistence/impl/MFATimeBasedOTPEntryPersistenceImpl.java uses or overrides a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 
     [exec] > Task :dxp:apps:multi-factor-authentication:multi-factor-authentication-timebased-otp-service:compileJava
     [exec] Problem in daemon expiration check
     [exec] org.gradle.api.UncheckedIOException: java.io.IOException: Cannot allocate memory
     [exec] 	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-08/test-1-29/test-portal-acceptance-pullrequest(master)/7815/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by rafaprax** [comment]
Hey @MrJohn1911, apply the changes we discussed on Slack and resend. Thx

**Pull request closed without merging**
