### PR TITLE
remove_deprecated_for_portal_kernel_part_Nine

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is remove_deprecated_for_portal_kernel_part_Nine. 
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar , Can you help me check this pr again when it is ready, please?

**Comment by tinatian** [comment]
@jeffwu0724 Code conflicts, please rebase.

Thanks.
Tina.

**Comment by catarineaguiar** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
Hi @jeffwu0724 I need the testray build to analyze your PR, that's why I re-run acceptance.

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
@jeffwu0724 this pr should be good, i checked the semvar error, it was something else upstream

**Pull request closed without merging**
