### PR TITLE
LPS-201024 Not import log4j1 package from the module com.liferay.translation.translator.google.cloud

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
@yuhai No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/144181

cc @tinatian

**Pull request closed without merging**
