### PR TITLE
LPS-170267 Remove "immediate = true" from Portal III

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**
Talking to @rafaprax, we noticed that for the tests in UpgradeReportLogAppenderTest.java not to fail, this class UpgradeReportLogAppender.java that belongs to batch portal, needs to be immediate because it is not referenced by other classes.

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:startup

**Comment by GabrielHenriquedev** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
no regressions found.

the unique failures on startup suite passed locally.

**Comment by GabrielHenriquedev** [comment]
@tinatian  this one is ready to go.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129126

**Pull request closed without merging**
