### PR TITLE
[Remove Spring extender usages] LPS-159403

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

Resend. refer to https://github.com/liferay-core-infra/liferay-portal/pull/1292

This PR is to remove spring extender usage in commerce-wish-list-service, thanks!
https://issues.liferay.com/browse/LPS-159403

Previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/1248

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @catarineaguiar, Could you review the test results when it finishes? Thanks!

**Comment by JanisZhang** [comment]
ci:test:commerce

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@catarineaguiar Could you please review the test results? Thanks!

**Comment by catarineaguiar** [comment]
@JanisZhang @dantewang no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
