### PR TITLE
LPD-21711 Revert 'LPD-15176 Remove ReflectionUtil usages in CentralizedConfiguration' and add unit test coverage

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:2555841991

**Comment by julschong** [comment]
no unique failure

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6826

**Pull request closed without merging**
