### PR TITLE
[Remove Blocking usages]LPS-200474

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace blocking ServiceProxyFactory with Snapshot in class `CTSQLInterceptor`.
 https://liferay.atlassian.net/browse/LPS-200474

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by Kvale1733** [comment]
Let's just check upgrade results

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
