### PR TITLE
LPD-34014

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by tinatian** [comment]
@jeffwu0724 Please take this over!

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hi @marianoalvarosaiz ,

I saw you have added another `commons-collections:commons-collections` in `source.check.GradleDependencyArtifactsCheck.allowedArtifactsFileNames` in source-formatter.properties
FYI, https://github.com/liferay-core-infra/liferay-portal/pull/7351/commits/60ee6253885e828c10e750ef96e1602ca39159de

I found that this SF restrition has been added in https://liferay.atlassian.net/browse/LPS-194212, but I do not have the permission to see why we have to restrct `commons-collections`. I have reach out to Alan Huang and see what is the main reason that cannot use `commons-collections`

Thanks,
Jeff

**Comment by marianoalvarosaiz** [comment]
Thanks @jeffwu0724. I also tried to access the Slack link, but I can't.

**Comment by jeffwu0724** [comment]
Hi @marianoalvarosaiz ,

By reproducing the error in https://github.com/liferay-appsec/liferay-portal/pull/1894, I think that we are not using 'org.apache.commons.collections' during runtime. 
We saw this 'Unresolved requirement: Import-Package: org.apache.commons.collections_' because it is the compiled dependencies of commons-beautiful and commons-validation, if we don't exclude them, then it will complain while starting up, even though we do not use them.
I have sent a [testing PR](https://github.com/jeffwu0724/liferay-portal/pull/525) to see if trying to exclude it from bnd.bnd will work.

Thanks,
Jeff

**Comment by marianoalvarosaiz** [comment]
Hi @jeffwu0724 ,

 OK, if it is used at runtime in any test, then looks good.

Kind regards.

**Comment by jeffwu0724** [comment]
Hi @marianoalvarosaiz , @jgarcialr

> if it is used at runtime in any test, then looks good.
I am not too sure if I understand this correctly. Seems like `org.apache.commons.collections` is not being used at runtime, at least the test we have triggered so far did not catch the error that `Unresolved requirement: Import-Package: org.apache.commons.collections_`

By looking at the test result of https://github.com/jeffwu0724/liferay-portal/pull/525, the failing test are not related to the changes. Seems like this alternative does make https://github.com/liferay-appsec/liferay-portal/pull/1894 work.
Please feel free to trigger more tests to make sure we did not miss anything.

Thanks,
Jeff

**Comment by jeffwu0724** [comment]
close this PR for now as we have provide a workaround

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:security

**Comment by jeffwu0724** [comment]
Hi @marianoalvarosaiz , @jgarcialr

After discussing with Tina, we dicided to reopen this PR  as a prerequisite of upgrading cxf to 3.5.9, as excluding  `org.apache.commons.collections` may cause some potential regression.
I will look at the test result later, once it passed, we will move forward with this PR.

Thanks,
Jeff

**Comment by jeffwu0724** [comment]
ci:report:65618813

**Comment by jeffwu0724** [comment]
ci:report:65618813

**Comment by jeffwu0724** [comment]
[relevant test:](https://github.com/liferay-core-infra/liferay-portal/pull/7351#issuecomment-2297633846)
https://testray.liferay.com/#/project/34754/routines/34756/build/65621339/case-result/65622562/history -- passed in another run 

[security test:](https://github.com/liferay-core-infra/liferay-portal/pull/7351#issuecomment-2297466261)
https://testray.liferay.com/#/project/34754/routines/34756/build/65618813/case-result/65619402/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/65618813/case-result/65619454/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/65618813/case-result/65620536/history -- not unique

No unique regression found

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/153537

**Pull request closed without merging**
