### PR TITLE
[Static Reference]LPS-170595 Convert method references to field references in module site-navigation-taglib (class NavItemClassNameIdUtil )

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(2022/12/8 9:32)

**Comment by W2jx** [comment]
no conflicts(12/9 9:43)

**Comment by W2jx** [comment]
no conflicts(12/13 9:55)

**Review by dantewang — APPROVED** [review]

**Comment by W2jx** [comment]
no conflicts(2022/12/14 9:39)

**Comment by W2jx** [comment]
no conflicts(12/15 9:25)

**Pull request closed without merging**
