### PR TITLE
LPS-165126

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by marianoalvarosaiz** [comment]
@dantewang do you have any updates about this PR?

**Comment by dantewang** [comment]
@marianoalvarosaiz I'll also have a discussion about this in our meeting.

**Comment by dantewang** [comment]
@marianoalvarosaiz As I explained on Slack, I'm going to close this one for now.

**Pull request closed without merging**
