### PR TITLE
[SampleSQLBuilder-homepage-part3]LPD-27455 6-17

### PR DESCRIPTION
**Pull request by dantewang**
@slnn Please verify, thanks.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:18899683

**Comment by dantewang** [comment]
ci:test:stable

**Comment by slnn** [comment]
Hi @dantewang 

Please see https://github.com/liferay/liferay-portal/pull/5969, I add continue to skip the loop when the layout is not a hidden layout, as the originalFragmentEntryLink corresponds with the hidden layout


```
for (LayoutModel layoutModel : layoutModels) {
			if (!layoutModel.isHidden()) {
				nonhiddenLayout = layoutModel;

				continue;
			}

			originalFragmentEntryLinkModels.add(
				newFragmentEntryLinkModel(
					layoutModel, 0, segmentsExperienceId,
					_readFile(
						_getFragmentComponentInputStream("paragraph", "css")),
					_readFile(
						_getFragmentComponentInputStream("paragraph", "html")),
					StringPool.BLANK,
					_readFile(
						"fragment_component" +
							"/fragment_component_paragraph_title_editValue." +
								"json"),
					paragraphRenderNamespace, 0,
					_FRAGMENT_COMPONENT_RENDER_KEY_PARAGRAPH));
			originalFragmentEntryLinkModels.add(
				newFragmentEntryLinkModel(
					layoutModel, 0, segmentsExperienceId,
					_readFile(
						_getFragmentComponentInputStream("paragraph", "css")),
					_readFile(
						_getFragmentComponentInputStream("paragraph", "html")),
					StringPool.BLANK,
					_readFile(
						"fragment_component" +
							"/fragment_component_paragraph_content_editValue." +
								"json"),
					paragraphRenderNamespace, 1,
					_FRAGMENT_COMPONENT_RENDER_KEY_PARAGRAPH));
			originalFragmentEntryLinkModels.add(
				newFragmentEntryLinkModel(
					layoutModel, 0, segmentsExperienceId, "",
					_readFile(
						_getFragmentComponentInputStream("image", "html")),
					_readFile(
						"fragment_component" +
							"/fragment_component_image_configuration.json"),
					_readFile(
						"fragment_component" +
							"/fragment_component_image_editValue.json"),
					imageRenderNamespace, 0,
					_FRAGMENT_COMPONENT_RENDER_KEY_IMAGE));
		}
```
Regards
Lily

**Comment by dantewang** [comment]
@slnn Ah I forgot to add it. Thanks! You sent to a wrong place, please resend.

**Comment by slnn** [comment]
Yes, I have resent and update the link in previous comment

**Pull request closed without merging**
