### PR TITLE
LPS-158489 Clean up petra-mail by inlining to usages

### PR DESCRIPTION
**Pull request by julschong**
@tinatian @catarineaguiar 
Hi Tina, Catarine,
This is resubmitted from #1255 

This pull fixed the MailEngineTest integration test by loading the inner class into the reloadURLClassloader

Thank you!

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong semver error:

```
  [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/petra/petra-mail] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.petra.mail                             MAJOR      2.0.0      2.0.0      3.0.0      VERSION INCREASE REQUIRED
     [exec]     	-   class      com.liferay.petra.mail.InternetAddressUtil
     [exec]     		-   method     <init>()
     [exec]     			-   return     void
     [exec]     		-   method     clone()
     [exec]     			-   access     protected
     [exec]     			-   return     java.lang.Object
     [exec]     		-   method     contains(javax.mail.internet.InternetAddress[],java.lang.String)
     [exec]     			-   access     static
     [exec]     			-   return     boolean
     [exec]     		-   method     equals(java.lang.Object)
     [exec]     			-   return     boolean
     [exec]     		-   method     finalize()
     [exec]     			-   access     protected
     [exec]     			-   return     void
     [exec]     		-   method     hashCode()
     [exec]     			-   return     int
     [exec]     		-   method     isValid(java.lang.String)
     [exec]     			-   access     static
     [exec]     			-   return     boolean
     [exec]     		-   method     removeEntry(javax.mail.Address[],java.lang.String)
     [exec]     			-   access     static
     [exec]     			-   return     javax.mail.internet.InternetAddress[]
     [exec]     		-   method     toString()
     [exec]     			-   return     java.lang.String
     [exec]     		-   method     toString(javax.mail.Address)
     [exec]     			-   access     static
     [exec]     			-   return     java.lang.String
     [exec]     		-   method     toString(javax.mail.Address[])
     [exec]     			-   access     static
     [exec]     			-   return     java.lang.String
     [exec]     		-   method     validateAddress(javax.mail.Address)
     [exec]     			-   access     static
     [exec]     			-   return     void
     [exec]     		-   method     validateAddresses(javax.mail.Address[])
     [exec]     			-   access     static
     [exec]     			-   return     void
     [exec]     	-   class      com.liferay.petra.mail.JavaMailUtil
     [exec]     		-   method     <init>()
     [exec]     			-   return     void
     [exec]     		-   method     clone()
     [exec]     			-   access     protected
     [exec]     			-   return     java.lang.Object
     [exec]     		-   method     equals(java.lang.Object)
     [exec]     			-   return     boolean
     [exec]     		-   method     finalize()
     [exec]     			-   access     protected
     [exec]     			-   return     void
     [exec]     		-   method     getBytes(javax.mail.Part)
     [exec]     			-   access     static
     [exec]     			-   return     byte[]
     [exec]     		-   method     hashCode()
     [exec]     			-   return     int
     [exec]     		-   method     toString()
     [exec]     			-   return     java.lang.String
     [exec]     		-   method     toUnicodeString(javax.mail.Address[])
     [exec]     			-   access     static
     [exec]     			-   return     java.lang.String
     [exec]     		-   method     toUnicodeString(javax.mail.internet.InternetAddress[])
     [exec]     			-   access     static
     [exec]     			-   return     java.lang.String
     [exec]     	-   class      com.liferay.petra.mail.LiferayMimeMessage
     [exec]     		-   extends    javax.mail.internet.MimeMessage
     [exec]     		-   method     <init>(javax.mail.Session)
     [exec]     			-   return     void
     [exec]     		-   method     clone()
     [exec]     			-   access     protected
     [exec]     			-   return     java.lang.Object
     [exec]     		-   method     equals(java.lang.Object)
     [exec]     			-   return     boolean
     [exec]     		-   method     finalize()
     [exec]     			-   access     protected
     [exec]     			-   return     void
     [exec]     		-   method     hashCode()
     [exec]     			-   return     int
     [exec]     		-   method     toString()
     [exec]     			-   return     java.lang.String
     [exec]     		-   method     updateMessageID()
     [exec]     			-   access     protected
     [exec]     			-   return     void
     [exec]     	-   class      com.liferay.petra.mail.MailEngineException
     [exec]     		-   extends    com.liferay.portal.kernel.exception.NestableException
     [exec]     		-   method     <init>()
     [exec]     			-   return     void
     [exec]     		-   method     <init>(java.lang.String)
     [exec]     			-   return     void
     [exec]     		-   method     <init>(java.lang.String,java.lang.Throwable)
     [exec]     			-   return     void
     [exec]     		-   method     <init>(java.lang.Throwable)
     [exec]     			-   return     void
     [exec]     		-   method     clone()
     [exec]     			-   access     protected
     [exec]     			-   return     java.lang.Object
     [exec]     		-   method     equals(java.lang.Object)
     [exec]     			-   return     boolean
     [exec]     		-   method     finalize()
     [exec]     			-   access     protected
     [exec]     			-   return     void
     [exec]     		-   method     hashCode()
     [exec]     			-   return     int
     [exec]     		-   method     toString()
     [exec]     			-   return     java.lang.String
     [exec]     	-   class      com.liferay.petra.mail.MailServerException
     [exec]     		-   extends    com.liferay.portal.kernel.exception.NestableException
     [exec]     		-   method     <init>()
     [exec]     			-   return     void
     [exec]     		-   method     <init>(java.lang.String)
     [exec]     			-   return     void
     [exec]     		-   method     <init>(java.lang.String,java.lang.Throwable)
     [exec]     			-   return     void
     [exec]     		-   method     <init>(java.lang.Throwable)
     [exec]     			-   return     void
     [exec]     		-   method     clone()
     [exec]     			-   access     protected
     [exec]     			-   return     java.lang.Object
     [exec]     		-   method     equals(java.lang.Object)
     [exec]     			-   return     boolean
     [exec]     		-   method     finalize()
     [exec]     			-   access     protected
     [exec]     			-   return     void
     [exec]     		-   method     hashCode()
     [exec]     			-   return     int
     [exec]     		-   method     toString()
     [exec]     			-   return     java.lang.String
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 7.0.0
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-28/test-portal-acceptance-pullrequest(master)/3849/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
@catarineaguiar I tried to auto update it using ant all and gw baseline but it won't update :(
So I manually changed it on the last commit

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong possible regression:

```
[exec] > Task :yarnInstall FAILED
     [exec] Using registry http://mirrors.lax.liferay.com:4873
     [exec] /opt/dev/projects/github/liferay-portal/build/node/lib/node_modules/yarn/yarn-1.13.0.js:46403
     [exec]   enumerable: 
     [exec]               
     [exec] 
     [exec] SyntaxError: Unexpected end of input
     [exec]     at Object.compileFunction (node:vm:352:18)
     [exec]     at wrapSafe (node:internal/modules/cjs/loader:1031:15)
     [exec]     at Module._compile (node:internal/modules/cjs/loader:1065:27)
     [exec]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
     [exec]     at Module.load (node:internal/modules/cjs/loader:981:32)
     [exec]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
     [exec]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
     [exec]     at node:internal/main/run_main_module:17:47
     [exec] Gradle build finished at 2022-08-05 16:39:15.201.
     [exec] 2 actionable tasks: 1 executed, 1 up-to-date
     [exec] 
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/build/reports/profile/profile-2022-08-05-09-39-13.html
     [exec] A fine-grained performance profile is available: use the --scan option.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':yarnInstall'.
     [exec] > Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':yarnInstall'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:208)
     [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:206)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:187)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-37/test-portal-acceptance-pullrequest(master)/3970/modules-compile-jdk8/0/6/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
I'm not sure how to fix that yarnInstall failure. But I did fine a integration test failure here: https://testray.liferay.com/home/-/testray/case_results/1937999554?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseTypeId%3D60250099%26testrayBuildId%3D1937994942%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@julschong Code looks good to me, wait for QA to scan test results.

Tina

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
could you please help me scan this test result again?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong yes, this failure on `MailEngineTest` is still happening:

```
[exec] com.liferay.portal.util.mail.test.MailEngineTest > testSendMailWithLimit FAILED
     [exec]     org.junit.ComparisonFailure: expected:<[]Unable to exceed max...> but was:<[com.liferay.portal.kernel.exception.PortalException: ]Unable to exceed max...>
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:117)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
     [exec]     	at com.liferay.portal.util.mail.test.MailEngineTest.testSendMailWithLimit(MailEngineTest.java:121)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-31/test-portal-acceptance-pullrequest(master)/4509/modules-integration-mysql57-jdk8/0/15/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121572

**Pull request closed without merging**
