### PR TITLE
[Method References 2] LPS-177276 Convert method reference to ServiceTrackerList in class CompanyIndexFactory

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:search

**Comment by W2jx** [comment]
ci:stop

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:search

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3960

**Pull request closed without merging**
