### PR TITLE
LPS-184249 Background Task clean up | 5-12

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian The implementation is a bit different with what we talked:

In our talk, we want to record the "in execution" state after marking the background task "IN_PROGRESS"; but in this implementation, I did it before the status change.

The reason is:

1) I think it's enough to use background task ID as it should be unique in the database;
2) If we record the state after marking the task `IN_PROGRESS`, it's possible that the scheduler job gets this `IN_PROGRESS` task but the recording hasn't happened yet. I think it's better to record the state before changing the task status, and remove the state changing the task status after execution.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:clustering

**Comment by Kvale1733** [comment]
@dantewang No regressions found.

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
FYI @shuyangzhou

**Pull request closed without merging**
