### PR TITLE
[Remove Stream/Optional usage] LPS-175655 info-collection-provider-item-selector-web

### PR DESCRIPTION
**Pull request by dantewang**
@JanisZhang

### CODE REVIEW

**Comment by dantewang** [comment]
@JanisZhang Please help me double check that the extract logic are indeed duplicate, thanks!

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:item-selector

**Comment by JanisZhang** [comment]
> @JanisZhang Please help me double check that the extract logic are indeed duplicate, thanks!

Hi @dantewang, Yes, they are duplicates and I don't see any problem with that change.

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:item-selector

**Comment by Kvale1733** [comment]
@dantewang No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
