### PR TITLE
[Method References 2] LPS-173124 Convert method reference to field reference in module segments-service

### PR DESCRIPTION
**Pull request by W2jx**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3278

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:tango

**Comment by W2jx** [comment]
no conflicts(2/8 9:05)

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
