### PR TITLE
[Components with more than 1 service] LPS-205650 Refactor ScreenNavigationCategory components from USM modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
This pull was already merged https://github.com/brianchandotcom/liferay-portal/pull/133189, but it was reverted by mistake.

Ticket: https://liferay.atlassian.net/browse/LPS-205650

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:usm

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
