### PR TITLE
[Component with its own class name as service type] LPS-195481 Refactor UploadFileEntryHandler and UploadResponseHandler components from saml and object modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-195481

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:security

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
Last push fixes sf problems

**Comment by catarineaguiar** [comment]
no regressions found

**Review by rafaprax — APPROVED** [review]

**Comment by MrJohn1911** [comment]
Last push just changed the commit message.

**Comment by shuyangzhou** [comment]
@MrJohn1911 don't mix the object and saml change together. They are not related, they deserve two separate pulls.
Also I don't really understand this commit's message https://github.com/liferay-core-infra/liferay-portal/pull/5528/commits/e1392a65a35b925fd9539312d507584ef3ad11e2 `since the service tracker that is in ObjectDefinitionDeployerImpl tracks all the PortletResourcePermission services, but is only used to get the PortletResourcePermission services from ObjectDefinitions, apply to usages and prepare for next`

It sounds like you are saying PortletResourcePermission from ObjectDefinitions are always having `com.liferay.object=true` which piece of code is ensuring that? I know very little about Objects, not saying your statement is wrong. But you need to provide evidences to support your statement in the commit message, otherwise I won't be able to know if it is right.

Also run `git grep "com.liferay.object=true"` you will see:
`modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectEntryServiceImpl.java:                           "(&(com.liferay.object=true)(resource.name=*))",` has this too, your change should take care of this usage too.

Please resend.

**Pull request closed without merging**
