### PR TITLE
LPS-153856 Move xmlsec.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
I fixed the SF issue without any logic chance. So. the test results are still valid.

**Comment by rafaprax** [comment]
Hey @catarineaguiar, can you please help me scan these test results?

Thx

**Comment by catarineaguiar** [comment]
@vicnate5 will not have time to review this one today

**Comment by vicnate5** [comment]
@koor4356 can you check this one?

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
@rafaprax 
This pr looks good. No regression, thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/117682

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
