### PR TITLE
[Static reference] LPS-182671 Remove static references in class MBDiscussionPermission | part 2

### PR DESCRIPTION
**Pull request by W2jx**
Hi @yuhai , I have modified classes PermissionServiceImpl and BaseModelPermissionCheckerUtil as we discussed.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5044

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:lima

**Comment by W2jx** [comment]
ci:test:comment

**Comment by W2jx** [comment]
ci:test:message-boards

**Comment by W2jx** [comment]
ci:test:questions

**Comment by yuhai** [comment]
ci:stop

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Pull request closed without merging**
