### PR TITLE
[License]LPS-165666

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
ci:test:license-cluster

**Comment by catarineaguiar** [comment]
@tinatian regressions found on relevant:

semver erro
```
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/79.0.1/5bc11dfd17e10a63fb58d251f3c0020c851dd5c8/com.liferay.portal.kernel-79.0.1.jar
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-36/test-portal-acceptance-pullrequest(master)/2216/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
  [javac] Compiling 2393 source files to /opt/dev/projects/github/liferay-portal/portal-impl/classes
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/ee/license/LCSLicenseManager.java:830: error: cannot find symbol
    [javac] 	private static Set<HttpSession> _httpSessions = new HashSet<>();
    [javac] 	               ^
    [javac]   symbol:   class Set
    [javac]   location: class LCSLicenseManager
    [javac] 1 error
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-36/test-portal-acceptance-pullrequest(master)/2216/portal-license-smoke-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
ci:test:license-cluster

**Comment by Kvale1733** [comment]
@tinatian The only regressions are the ones Catarine mentioned for relevant.

**Comment by vicnate5** [comment]
@tinatian The semver is the only remaining issue. Stable and license tests passing clears the LCSLicenseManager compile issue in relevant. CC @Kvale1733

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@tinatian no regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125317

**Pull request closed without merging**
