### PR TITLE
[Method References 2] LPS-165748 Convert method reference to ServiceTrackerSet in module module portal-search

### PR DESCRIPTION
**Pull request by W2jx**
I add ServiceTrackerSet and convert method reference to ServiceTrackerSet in module module portal-search.

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@W2jx regression found:

```
[echo] PMD VIOLATION: /opt/dev/projects/github/liferay-portal/modules/core/osgi-service-tracker-collections-test/src/testIntegration/java/com/liferay/osgi/service/tracker/collections/set/test/ServiceTrackerSetTest.java:136 > Avoid unused local variables such as 'trackedOne'. (PMD Rule: UnusedLocalVariable)
     [echo] For more information, please see https://pmd.github.io/pmd-6.8.0/pmd_rules_java_bestpractices.html#unusedlocalvariable.
     [echo] 
     [echo] PMD VIOLATION: /opt/dev/projects/github/liferay-portal/modules/core/osgi-service-tracker-collections-test/src/testIntegration/java/com/liferay/osgi/service/tracker/collections/set/test/ServiceTrackerSetTest.java:148 > Avoid unused local variables such as 'trackedOne'. (PMD Rule: UnusedLocalVariable)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-39/test-portal-acceptance-pullrequest(master)/1293/pmd-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
Force-Push is just to fix the bug.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
No regressions found.

**Pull request closed without merging**
