### PR TITLE
[Test Fix] LPD-38921 InstanceSettings#ViewInstanceMailSettingsValueIsInheritedFromServerLevel

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:44275149

**Comment by dantewang** [comment]
ci:report:44307203

**Comment by dantewang** [comment]
ci:report:44275149

**Comment by dantewang** [comment]
ci:report:44307203

**Comment by dantewang** [comment]
Hi @marianoalvarosaiz, could you take a look? This test case, as a coverage for LPS-156105, failed due to your change in LPD-1655, which removed the "systemPortletPreferences" part.

**Comment by dantewang** [comment]
ci:test:stable

**Comment by tinatian** [comment]
@dantewang This should be fixed in test rather than production code.
Reason is when accessing instances setting, it should only shows the configured values on instance layer, allowing to set empty to clear the setting at instance layer.

Backend, when a property is not set, respect system configuration and portal properties setting.

**Pull request closed without merging**
