### PR TITLE
[Remove immediate=true usage core-infrastructure-3 part 2]Lps 169260 part 2

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-169260

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
@slnn no regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127111

**Pull request closed without merging**
