### PR TITLE
[Remove unused field] LPS-199959 Remove unused reference field in calsses ScopeFormNavigatorEntry, LayoutScopesItemSelectorView, BatchEngineUnitProcessorImpl and DefaultCommerceCheckoutStepHttpHelper

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(10/26 9:11)

**Comment by W2jx** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
no conflicts(10/27 8:50)

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(10/30 7:57)

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142980

cc @shuyangzhou

**Pull request closed without merging**
