### PR TITLE
[Component with its own class name as service type ] LPS-198079 Refactor Registry classes from mutiple modules

### PR DESCRIPTION
**Pull request by rafaprax**
https://liferay.atlassian.net/browse/LPS-198079

### CODE REVIEW

**Comment by rafaprax** [comment]
Hi QA team, this commit is part of the https://github.com/liferay-core-infra/liferay-portal/pull/5909 pr and there we didn't have any tests broken. So, I think you don't need to rerun the tests but feel free to do that if you think it is required.

Thx

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No unique failures.

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
