### PR TITLE
[TS] LPD-42520

### PR DESCRIPTION
**Pull request by ericyanLr**

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:tests:relevant

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:75406090

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 75406090.
> 
> Job Link: [generate-testray-csv](https://test-1-40.liferay.com/job/generate-testray-csv/683/)
> 
> Testray CSV Link: [testray-results-75406090.csv](https://test-1-40.liferay.com/userContent/jobs/generate-testray-csv/builds/683/testray-results-75406090.csv)

No unique failure in report

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
