### PR TITLE
[Method References 2] LPS-167246 Convert method reference to ServiceTracker in module portal-messaging

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have replaced _messageBusEventListenerServiceTracker with serviceTrackerList and reordered commits.

### CODE REVIEW

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
Force-Push is just to rebase and resolve conflict about file 
`portal-kernel/src/com/liferay/portal/kernel/messaging/packageinfo`

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
no conflicts(2022/12/5 13:30)

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
@W2jx no regressions found.

**Comment by W2jx** [comment]
no conflicts(2022/12/6 14:11)

**Comment by W2jx** [comment]
no conflicts(2022/12/7 9:39)

**Comment by W2jx** [comment]
no conflicts(2022/12/8 9:11)

**Comment by W2jx** [comment]
no conflicts(12/9 9:53)

**Comment by W2jx** [comment]
Force-Push is just to rebase and resolve conflict about file `portal-kernel/bnd.bnd`

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(12/13 9:49)

**Comment by W2jx** [comment]
no conflicts(2022/12/14 9:41)

**Comment by W2jx** [comment]
no conflicts(12/15 9:25)

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2768. Please resend once https://github.com/liferay-core-infra/liferay-portal/pull/2768 is merged.

Thanks.
Tina

**Pull request closed without merging**
