### PR TITLE
[Static reference] LPS-182671 Remove static references in class MBDiscussionPermission | part 2

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian , I have separated https://github.com/liferay-core-infra/liferay-portal/pull/5094 into two small pr, and this is one of them.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5094

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:lima

**Comment by W2jx** [comment]
ci:test:comment

**Comment by W2jx** [comment]
ci:test:questions

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
no regressions found.

SF issue is not related

**Comment by W2jx** [comment]
no conflicts(8/1 8:44)

**Pull request closed without merging**
