### PR TITLE
[Components with more than 1 service] LPS-193899 Refactor commerce components

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-193899

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:search

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Review by rafaprax — APPROVED** [review]

**Comment by Kvale1733** [comment]
@MrJohn1911 Regression found. To reproduce just startup and shutdown. There should be a log file in /osgi/state with the following error

```
[junit] !ENTRY com.liferay.portal.search 4 0 2023-08-18 09:35:37.096
    [junit] !MESSAGE bundle com.liferay.portal.search:8.0.80 (233)[com.liferay.portal.search.internal.background.task.BackgroundTaskExecutorConfigurator(470)] : The deactivate method has thrown an exception
    [junit] !STACK 0
    [junit] java.lang.IllegalStateException: The service has been unregistered
    [junit] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:204)
    [junit] 	at com.liferay.portal.search.internal.background.task.BackgroundTaskExecutorConfigurator.deactivate(BackgroundTaskExecutorConfigurator.java:50)
    [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    [junit] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228)
    [junit] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
    [junit] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664)
    [junit] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510)
    [junit] 	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:310)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-31/test-portal-acceptance-pullrequest(master)/9154/functional-smoke-tomcat90-mysql57-jdk11_open/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
