### PR TITLE
[Components with more than 1 service] LPS-183224 Refactor PortetProvider components from Commerce modules part I

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://issues.liferay.com/browse/LPS-183224

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
@MrJohn1911 failure on startup:

```
    [junit] 2023-05-02 21:25:57.068 INFO  [main][AutoDeployDir:161] Auto deploy scanner started for /opt/dev/projects/github/liferay-portal/bundles/deploy
    [junit] 2023-05-02 21:25:57.607 INFO  [main][CompanyIndexFactory:51] liferay-20096
    [junit] 2023-05-02 21:25:58.082 ERROR [main][CommerceCheckoutViewPortletProvider:56] bundle com.liferay.commerce.checkout.web:5.0.67 (590)[com.liferay.commerce.checkout.web.internal.portlet.CommerceCheckoutViewPortletProvider(7867)] : findField: Suitable but non-accessible field _portal in class com.liferay.commerce.checkout.web.internal.portlet.BaseCommerceCheckoutPortletProvider, subclass of component class com.liferay.commerce.checkout.web.internal.portlet.CommerceCheckoutViewPortletProvider
    [junit] 2023-05-02 21:26:10.068 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:221] Processing speedwell-theme.war
    [junit] 2023-05-02 21:26:10.069 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:221] Processing minium-theme.war
    [junit] 2023-05-02 21:26:10.069 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:221] Processing dialect-theme.war
    [junit] 2023-05-02 21:26:10.069 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:221] Processing admin-theme.war
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-05/test-1-26/test-portal-acceptance-pullrequest(master)/8965/functional-smoke-tomcat90-oracle193-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
In this push, I changed [this](https://github.com/liferay-core-infra/liferay-portal/blob/971c4a07d9e5b73ef76831b8de3ca369eddf3517/modules/apps/commerce/commerce-checkout-web/src/main/java/com/liferay/commerce/checkout/web/internal/portlet/BaseCommerceCheckoutPortletProvider.java#L66) from private to protected.

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
no regressions found.

**Review by rafaprax — APPROVED** [review]

**Pull request closed without merging**
