### PR TITLE
[Bug fix]LPS-168264

### PR DESCRIPTION
**Pull request by JanisZhang**
This P/R is to fix the unset method. Thanks
https://issues.liferay.com/browse/LPS-168264

### CODE REVIEW

**Review by dantewang — APPROVED** [review]
@JanisZhang Are they there for a long time?

**Comment by JanisZhang** [comment]
@dantewang yes, they have been there since the class was created in fcb5a8c8d06202b09dd04dc60c913973662ce1de

**Comment by dantewang** [comment]
ci:stop

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126188

**Pull request closed without merging**
