### PR TITLE
LPD-26430 Fix ConfigurationImplTest

### PR DESCRIPTION
**Pull request by kevhlee**

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:report:74084456

**Comment by kevhlee** [comment]
ci:report:74084456

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:report:75117024

**Comment by kevhlee** [comment]
ci:report:75117024

**Comment by tinatian** [comment]
@kevhlee I figured out a better way to fix it, please see https://github.com/liferay-core-infra/liferay-portal/pull/7395

**Pull request closed without merging**
