### PR TITLE
[Remove Stream/Optional usage] LPS-170586 dynamic-data-mapping | PART 1 

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend. Thanks!

previous:https://github.com/liferay-core-infra/liferay-portal/pull/2682

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
force-pushed. Thanks! @dantewang

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — CHANGES_REQUESTED** [review]
@JanisZhang See my comment and resend. When you resend, please exclude the first 2 commits because this ticket aims at modifying dynamic-data-mapping. The stream or optional usages you modified in the second commit are the result of implementing an interface in search-api, so we should modify it when modifying search.

**Pull request closed without merging**
