### PR TITLE
LPS-195954 Merge CacheKeyGenerator implementations into portal-kernel

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@julschong no regressions found. Please, resolve conflicts.

SF issue:

```
format-source-files:
     [java] java.lang.Exception: Found 5 formatting issues:
     [java] 1: /opt/dev/projects/github/liferay-portal/portal-kernel/src/com/liferay/portal/kernel/cache/key/BaseCacheKeyGenerator.java expected:<...ring.StringBundler;
     [java] []
     [java] import java.io.Seri...> but was:<...ring.StringBundler;
     [java] [import com.liferay.portal.kernel.cache.key.CacheKeyGenerator;
     [java] ]
     [java] import java.io.Seri...>
     [java] 2: /opt/dev/projects/github/liferay-portal/modules/apps/portal-cache/portal-cache-impl/src/test/java/com/liferay/portal/cache/internal/dao/orm/FinderCacheImplTest.java expected:<...portal.kernel.cache.[MultiVMPool;
     [java] import com.liferay.portal.kernel.cache.PortalCache;
     [java] import com.liferay.portal.kernel.cache.key.CacheKeyGenerator;
     [java] import com.liferay.portal.kernel.cache.key.CacheKeyGeneratorUtil;
     [java] import com.liferay.portal.kernel.cache.key.HashCodeHexStringCacheKeyGenerator];
     [java] import com.liferay...> but was:<...portal.kernel.cache.[key.HashCodeHexStringCacheKeyGenerator;
     [java] import com.liferay.portal.kernel.cache.MultiVMPool;
     [java] import com.liferay.portal.kernel.cache.PortalCache;
     [java] import com.liferay.portal.kernel.cache.key.CacheKeyGenerator;
     [java] import com.liferay.portal.kernel.cache.key.CacheKeyGeneratorUtil];
     [java] import com.liferay...>
     [java] 3: /opt/dev/projects/github/liferay-portal/portal-impl/test/unit/com/liferay/portal/servlet/filters/strip/StripFilterTest.java expected:<...al.kernel.cache.key.[CacheKeyGeneratorUtil;
     [java] import com.liferay.portal.kernel.cache.key.HashCodeHexStringCacheKeyGenerator];
     [java] import com.liferay...> but was:<...al.kernel.cache.key.[HashCodeHexStringCacheKeyGenerator;
     [java] import com.liferay.portal.kernel.cache.key.CacheKeyGeneratorUtil];
     [java] import com.liferay...>
     [java] 4: /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/tools/ToolDependencies.java expected:<... com.liferay.portal.[json.JSONFactoryImpl;
     [java] import com.liferay.portal.kernel.cache.MultiVMPool;
     [java] import com.liferay.portal.kernel.cache.PortalCache;
     [java] import com.liferay.portal.kernel.cache.PortalCacheException;
     [java] import com.liferay.portal.kernel.cache.PortalCacheListener;
     [java] import com.liferay.portal.kernel.cache.PortalCacheListenerScope;
     [java] import com.liferay.portal.kernel.cache.PortalCacheManager;
     [java] import com.liferay.portal.kernel.cache.PortalCacheManagerListener;
     [java] import com.liferay.portal.kernel.cache.PortalCacheManagerNames;
     [java] import com.liferay.portal.kernel.cache.PortalCacheManagerProvider;
     [java] import com.liferay.portal.kernel.cache.SingleVMPool;
     [java] import com.liferay.portal.kernel.cache.key.CacheKeyGeneratorUtil;
     [java] import com.liferay.portal.kernel.cache.key.SimpleCacheKeyGenerator];
     [java] import com.liferay...> but was:<... com.liferay.portal.[kernel.cache.key.SimpleCacheKeyGenerator;
     [java] import com.liferay.portal.json.JSONFactoryImpl;
     [java] import com.liferay.portal.kernel.cache.MultiVMPool;
     [java] import com.liferay.portal.kernel.cache.PortalCache;
     [java] import com.liferay.portal.kernel.cache.PortalCacheException;
     [java] import com.liferay.portal.kernel.cache.PortalCacheListener;
     [java] import com.liferay.portal.kernel.cache.PortalCacheListenerScope;
     [java] import com.liferay.portal.kernel.cache.PortalCacheManager;
     [java] import com.liferay.portal.kernel.cache.PortalCacheManagerListener;
     [java] import com.liferay.portal.kernel.cache.PortalCacheManagerNames;
     [java] import com.liferay.portal.kernel.cache.PortalCacheManagerProvider;
     [java] import com.liferay.portal.kernel.cache.SingleVMPool;
     [java] import com.liferay.portal.kernel.cache.key.CacheKeyGeneratorUtil];
     [java] import com.liferay...>
     [java] 5: /opt/dev/projects/github/liferay-portal/portal-kernel/test/unit/com/liferay/portal/kernel/cache/key/BaseCacheKeyGeneratorTestCase.java expected:<...ring.StringBundler;
     [java] []
     [java] import java.io.Seri...> but was:<...ring.StringBundler;
     [java] [import com.liferay.portal.kernel.cache.key.CacheKeyGenerator;
     [java] ]
     [java] import java.io.Seri...>
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:457)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:290)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-09/test-1-39/test-portal-source-format/3995/source-format-current-branch-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
@julschong this design needs to be changed. In CacheKeyGenerator interface, add the following constants.
"HASH_CODE", "DIGEST", "SIMPLE".
In CacheKeyGeneratorUtil, make the getCacheKeyGenerator(String type) looking up by type, throw IllegalArgumentException on unknown type. And in its static block populate the 3 above ones into its lookup map. And a "setCacheKeyGenerator(String type, CacheKeyGenerator cacheKeyGenerator)" method to allow outside registering of new type of CacheKeyGenerator.
Change all CacheKeyGeneratorUtil usage to lookup by their current used type.

**Pull request closed without merging**
