### PR TITLE
[Remove Stream/Optional usage] LPS-175899 module: commerce-term-web

### PR DESCRIPTION
**Pull request by dantewang**
#3568

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
@dantewang No regressions found.

**Comment by dantewang** [comment]
ci:forward

@shuyangzhou @tinatian

**Comment by dantewang** [comment]
@LisztLiszt Please double check whether the `*Util` usages can be simplified in your future pulls.

**Pull request closed without merging**
