### PR TITLE
LPS-173597 DLProcessor clean up

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-173597

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:document

**Comment by rafaprax** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:test:dl-store

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:document

**Comment by rafaprax** [comment]
ci:test:dl-store

**Comment by Kvale1733** [comment]
ci:test:dl-store

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@rafaprax What's commit for https://github.com/liferay-core-infra/liferay-portal/pull/4836/commits/60edba9c43e2327b01aaf931fb2de1ae7b728221? I do not understand the commit message "With this change, the trackers will keep working with the specialized services(AudioProcessor, VideoProcessor) and with some other provided by the "dl.file.entry.processors" property"

If there is anything not working without this change, please deal with those special cases first.

**Comment by tinatian** [comment]
@rafaprax I do not understand the commit message of this commit either https://github.com/liferay-core-infra/liferay-portal/pull/4836/commits/d77c4f10e1a602ffd2c48953ac4d8456e9ec79be

**Comment by tinatian** [comment]
@rafaprax As we discussed, please resend.

Thanks.
Tina

**Pull request closed without merging**
