### PR TITLE
[Remove Blocking usages]LPS-188900 portal-kernel | HtmlParserUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:stop

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
Hi @dantewang , The reason why we move the `HtmlParserImpl` logic to a component in the module is to complete task https://liferay.atlassian.net/browse/LPS-147656 (Remove jericho-html.jar), Class `HtmlParserImpl` will be registered when method `ModuleFrameworkImpl._registerApplicationContext` is called, before class `HtmlParserUtil` is used. So I think we can directly use unblocking `ServiceProxyFactory` in class `HtmlParserUtil`.

**Comment by W2jx** [comment]
no conflicts(7/4 14:30)

**Comment by W2jx** [comment]
no conflicts(7/5 13:57)

**Comment by W2jx** [comment]
no conflicts(7/6 8:08)

**Pull request closed without merging**
