### PR TITLE
[Eliminate unused reference]LPS-200629 module:data-engine, saml-impl

### PR DESCRIPTION
**Pull request by JanisZhang**
Remove unused reference fields in class `SpSessionTerminationSamlPortalFilter`, `DataLayoutRendererImpl` and `DataDefinitionResourceImpl`. Thanks.
https://liferay.atlassian.net/browse/LPS-200629

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:data-engine

**Comment by zhangyan0701** [comment]
ci:test:saml

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
run additional upgrade test

**Comment by zhangyan0701** [comment]
No regressions found from the upgrade tests.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143284

**Pull request closed without merging**
