### PR TITLE
[Remove Stream/Optional usage] LPS-171834 headless PART|2

### PR DESCRIPTION
**Pull request by JanisZhang**
Remove usages of Stream on Method Return Value for module: headless PART 2.

https://issues.liferay.com/browse/LPS-171834

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/2871

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
@JanisZhang See https://github.com/liferay-core-infra/liferay-portal/pull/2913

**Pull request closed without merging**
