### PR TITLE
[Convert method references]LPS-162482 Covert method references to field references in module com…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-162482

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Comment by slnn** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
@catarineaguiar Could you take a look at the Commerce tests when they finish?

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by julschong** [comment]
ci:forward

**Pull request closed without merging**
