### PR TITLE
[Remove Spring extender usages]  LPS-159491

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang

### CODE REVIEW

**Comment by yuhai** [comment]
@zhangyan0701, please scan the test result after ci test finished. Thanks.

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]
@tinatian Code looks good and CI passed.

**Comment by tinatian** [comment]
@yuhai Please see https://github.com/liferay-core-infra/liferay-portal/pull/1292 and resend.

**Pull request closed without merging**
