### PR TITLE
[Method References 2] LPS-170790 Convert method reference to ServiceTracker in class ActionExecutorManagerImpl(portal-workflow-kaleo-runtime-impl)

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by catarineaguiar** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
ci:test:workflow-metrics

**Comment by Kvale1733** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
ci:test:workflow-metrics

**Comment by W2jx** [comment]
no conflicts(12/21 17:05)

**Comment by jaydawu** [comment]
Hello @dantewang, no regression found. Can be passed. Thanks.

**Comment by catarineaguiar** [comment]
Thanks @jaydawu!

**Comment by W2jx** [comment]
no conflicts(12/26 10:01)

**Comment by W2jx** [comment]
no conflicts(12/27 9:31)

**Comment by yuhai** [comment]
@W2jx, for the commit https://github.com/liferay-core-infra/liferay-portal/pull/2794/commits/7dfa40de72c93016f5f600b416521270a9b74f9a inline change, if no one let you to do the inline, please remove the commit. Since the developer may refer ActionExecutorManager in their custom code.

**Pull request closed without merging**
