### PR TITLE
LPS-148757 Move sparse-bit-set.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
Hey, @koor4356 Can you please help me check the test results here? Thx

**Comment by koor4356** [comment]
@rafaprax 
This looks good, thanks!

**Comment by rafaprax** [comment]
Hey @tinatian, this pr is ready for your review. Thx

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.
@rafaprax Please add this to compileInclude list as there are more than module including this one.

Tina

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.
@rafaprax Please add this to compileInclude list as there are more than module including this one.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114472

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
