### PR TITLE
LPS-172168 Remove "immediate = true" from Portal IV

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:help

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by RenanUmV** [comment]
Hey @tinatian  , this one is ready to go!

**Comment by rafaprax** [comment]
ci:test:db-partition

**Comment by rafaprax** [comment]
Hey @catarineaguiar @RenanUmV, I triggered the db-partition suite to make that we won't cause any breaking change there. Let's wait for the results. 

Thx

**Comment by catarineaguiar** [comment]
no regressions on db-partition suite.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128886

**Pull request closed without merging**
