### PR TITLE
[Remove unused reference] LPS-166428

### PR DESCRIPTION
**Pull request by JanisZhang**
This PR is to remove unused fields in `headless-commerce-delivery-order-imp`. Thanks!

https://issues.liferay.com/browse/LPS-166428

### CODE REVIEW

**Comment by jaydawu** [comment]
No regressions found.

cc/ @zhangyan0701

**Comment by JanisZhang** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by dantewang** [comment]
@JanisZhang  See https://github.com/liferay-core-infra/liferay-portal/pull/2212

**Pull request closed without merging**
