### PR TITLE
Lps 181252 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:object

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by Kvale1733** [comment]
@tinatian As discussed. This is not a regression. I checked manually via UI and the log level is set for all other nodes when they are set on the slave node on 9080. It's just that these changes don't guarantee the specific log message appears immediately as it did before, which the functional test was asserting. But the message still appears on all nodes eventually, further showing that the log level was in fact set on all nodes.

I will fix the test logic separately. There are no other regressions so this PR is good to forward if there are no other changes.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133329

**Pull request closed without merging**
