### PR TITLE
[commons-lang] Remove commons-lang StringEscapeUtils usages

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:report:2549308902

**Comment by julschong** [comment]
1 unique failure, investigating
```
com.liferay.headless.delivery.resource.v1_0.test.StructuredContentResourceTest	https://testray.liferay.com/home/-/testray/case_results/2549309366/history	Unique
```

**Comment by julschong** [comment]
could not reproduce the integration test failure locally

**Comment by julschong** [comment]
looks like flaky failure

**Comment by tinatian** [comment]
@julschong Closed as we talked, please resend.

Thanks.
Tina

**Pull request closed without merging**
