### PR TITLE
LPS-149258

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-149258.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result again, please?

Thanks
Jeff

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
@jeffwu0724 some upgrade tests failed with this same error:

```
 [exec]     BUILD FAILED: 
     [exec]     ##
     [exec]     ## 1 Liferay Exception was thrown
     [exec]     ##
     [exec] 
     [exec]     LIFERAY_ERROR: Error reindexing all com.liferay.document.library.kernel.model.DLFileEntry for company: 20116
     [exec] 
     [exec] 
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/upgrades/PortalSmokeUpgrade.testcase[ViewPortalSmokeArchive70106]:127
     [exec] 
     [exec] 
     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive70106] STANDARD_ERROR
     [exec]     java.lang.Exception: 
     [exec]     ##
     [exec]     ## 1 Liferay Exception was thrown
     [exec]     ##
     [exec] 
     [exec]     LIFERAY_ERROR: Error reindexing all com.liferay.document.library.kernel.model.DLFileEntry for company: 20116
     [exec] 
     [exec] 
     [exec]     	at com.liferay.poshi.runner.selenium.LiferaySeleniumUtil.assertNoPoshiWarnings(LiferaySeleniumUtil.java:298)
     [exec]     	at com.liferay.poshi.runner.PoshiRunner.test(PoshiRunner.java:258)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-38/test-portal-acceptance-pullrequest(master)/429/functional-upgrade-tomcat90-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

* I was able to reproduce locally doing the upgrade to 7.0.10.6. I don't know if it is related to your changes, but it only failed in your PR

**Comment by jeffwu0724** [comment]
> @jeffwu0724 some upgrade tests failed with this same error:
> 
> ```
>  [exec]     BUILD FAILED: 
>      [exec]     ##
>      [exec]     ## 1 Liferay Exception was thrown
>      [exec]     ##
>      [exec] 
>      [exec]     LIFERAY_ERROR: Error reindexing all com.liferay.document.library.kernel.model.DLFileEntry for company: 20116
>      [exec] 
>      [exec] 
>      [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/upgrades/PortalSmokeUpgrade.testcase[ViewPortalSmokeArchive70106]:127
>      [exec] 
>      [exec] 
>      [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive70106] STANDARD_ERROR
>      [exec]     java.lang.Exception: 
>      [exec]     ##
>      [exec]     ## 1 Liferay Exception was thrown
>      [exec]     ##
>      [exec] 
>      [exec]     LIFERAY_ERROR: Error reindexing all com.liferay.document.library.kernel.model.DLFileEntry for company: 20116
>      [exec] 
>      [exec] 
>      [exec]     	at com.liferay.poshi.runner.selenium.LiferaySeleniumUtil.assertNoPoshiWarnings(LiferaySeleniumUtil.java:298)
>      [exec]     	at com.liferay.poshi.runner.PoshiRunner.test(PoshiRunner.java:258)
>      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>      [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-38/test-portal-acceptance-pullrequest(master)/429/functional-upgrade-tomcat90-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)
> 
> * I was able to reproduce locally doing the upgrade to 7.0.10.6. I don't know if it is related to your changes, but it only failed in your PR

Hey @catarineaguiar ,

Would you mind giving me some details about how to reproduce it locally, please? I will try to work on it and see if I can fix it, thanks!

Jeff

**Pull request closed without merging**
