### PR TITLE
[Remove Immediate] LPS-188559 Remove immediate property from DLProcessorRegistryImpl

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://liferay.atlassian.net/browse/LPS-188559

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:document

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by rafaprax** [comment]
Hey @tinatian, this pr is ready for your review.

**Comment by tinatian** [comment]
@rafaprax I do not want to see the duplicate logic in https://github.com/liferay-core-infra/liferay-portal/pull/5125/commits/caf9d210ba9f2f605dbd2ff64279a612d0d10495 about registering DLProcessor.

Please remove the DLProcessor support from HookHotDeployListener first and then add breaking change, then check with Lima team if they are OK to remove. 

Please resend.

Thanks.
Tina

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-core-infra/liferay-portal/pull/5218

**Pull request closed without merging**
