### PR TITLE
[Component with its own class name as service type] LPS-193631 Refactor ModelResourcePermission components

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-193631

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
@MrJohn1911 Regression found.
Steps to reproduce:
1. Add a and login to a virtual instance
2. Go to Content & Data > Dynamic Data Lists
3. Click on the ellipses on the top right and then go to "Manage Data Definitions"
4. Add a new Data Definition with any field (example: Link to Page).
5. Add a widget page
6. Add a Dynamic Data List Display widget to the page
7. Click Add List on the widget
8. Create new list with. Select the created Data Definition.
9. Refresh the page 

Expected Results: Widget is still accessible and shows "There are no records"
Actual Results: "You do not have the required permissions" errors is shown on the widget.

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
