### PR TITLE
[Method References 2] LPS-165285 Convert method reference to ServiceTrackerMap in class CompositeFacetProcessor(module portal-search-elasticsearch7-impl)

### PR DESCRIPTION
**Pull request by W2jx**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3058

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@W2jx Regressions in 

com.liferay.portal.search.elasticsearch7.internal.facet.ClassicModifiedFacetTest
```
java.lang.AssertionError: [{frequency=1, term=17760704000000}, {frequency=1, term=27760704000000}] expected:<5> but was:<2>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotEquals(Assert.java:834)
		at org.junit.Assert.assertEquals(Assert.java:645)
		at com.liferay.portal.search.test.util.facet.BaseClassicModifiedFacetTestCase.lambda$testBuiltInNamedRanges$0(BaseClassicModifiedFacetTestCase.java:74)
		at com.liferay.portal.search.test.util.facet.BaseFacetTestCase.lambda$assertSearchFacet$0(BaseFacetTestCase.java:55)
		at com.liferay.portal.search.test.util.indexing.BaseIndexingTestCase.lambda$assertSearch$0(BaseIndexingTestCase.java:203)
		at com.liferay.portal.search.test.util.IdempotentRetryAssert.lambda$retryAssert$0(IdempotentRetryAssert.java:62)
		at com.liferay.portal.search.test.util.IdempotentRetryAssert.retryAssert(IdempotentRetryAssert.java:43)
		at com.liferay.portal.search.test.util.IdempotentRetryAssert.retryAssert(IdempotentRetryAssert.java:59)
		at com.liferay.portal.search.test.util.indexing.BaseIndexingTestCase.assertSearch(BaseIndexingTestCas
```
[Log](https://testray.liferay.com/reports/production/logs/2023-02/test-1-26/test-portal-acceptance-pullrequest(master)/7867/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:search

**Pull request closed without merging**
