### PR TITLE
LPS-151308 Remove stax.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @koor4356, Can you please scan these test results? Thx

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
@rafaprax 
This looks good, thanks!

**Comment by rafaprax** [comment]
Hey @shuyangzhou, This pr is ready for your review. Thx

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
