### PR TITLE
LPS-136334 The widget crashes when changing the filter with "downloads" in DM management toolbar

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:test:sf

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.


Thanks.
Tina

**Comment by vicnate5** [comment]
@zhangyan0701 can you scan this one?

**Comment by zhangyan0701** [comment]
service-builder-jdk8/0/0 test failed with below message in console, this seems related:
```
     [exec] > Task :apps:view-count:view-count-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.view.count.service                     MINOR      1.4.0      1.4.0      1.5.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.view.count.service.ViewCountEntryLocalServiceUtil
     [exec] 		+   method     getViewCountEntryTable()
     [exec] 			+   access     static
     [exec] 			+   return     com.liferay.petra.sql.dsl.Table
     [exec] 	<   class      com.liferay.view.count.service.ViewCountEntryLocalServiceWrapper
     [exec] 		+   method     getViewCountEntryTable()
     [exec] 			+   return     com.liferay.petra.sql.dsl.Table
     [exec] 	<   interface  com.liferay.view.count.service.ViewCountEntryLocalService
     [exec] 		+   method     getViewCountEntryTable()
     [exec] 			+   access     abstract
     [exec] 			+   annotated  com.liferay.portal.kernel.transaction.Transactional
     [exec] 				+   property   propagation='SUPPORTS'
     [exec] 				+   property   readOnly=true
     [exec] 			+   return     com.liferay.petra.sql.dsl.Table
     [exec] [Baseline Warning] Bundle Version Change Recommended: 2.3.0
```

Testray result: https://testray.liferay.com/home/-/testray/case_results/1585485114
Full console: https://testray.liferay.com/reports/production/logs/2021-11/test-1-32/test-portal-acceptance-pullrequest(master)/1303/service-builder-jdk8/0/0/jenkins-console.txt.gz

**Comment by tinatian** [comment]
@stsquared99 Please see @zhangyan0701 's comment. I am going to close this pull, please resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by stsquared99** [comment]
Resent: https://github.com/liferay-core-infra/liferay-portal/pull/43

**Pull request closed without merging**
