### PR TITLE
[Components with more than 1 service] LPS-185512 Refactor Saml components from saml modules

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:saml

**Comment by GabrielHenriquedev** [comment]
ci:test:security

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found. Let's wait for stable results

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
