### PR TITLE
[TS] LPD-20238

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team,

**Ticket:** https://liferay.atlassian.net/browse/LPD-20238
**Previous PRs:** 
- https://github.com/liferay-core-infra/liferay-portal/pull/6878
- https://github.com/liferay-core-infra/liferay-portal/pull/6799

**Context**
Looking through the logic, the classes involved may actually be more related to the **Info Framework**. However, since some of these classes now reside within the expando module, this became a Core-Infra issue.
- I guess we could see this as Expando being used to contribute to the Info Framework

**Issue**
The issue appears to be a case of not providing a locale when retrieving a value.

**Proposed Solution**
As discussed, the new proposed fix will be to return a value using InfoLocalizedValue, which we can expect would provide us with the proper locale to be used instead of simply using the default locale, when retrieving a localized expando value.

**Addtional Notes - Changing class Interface**
Looking at the code, only **ExpandoInfoItemFieldReader** utilized the interface: **LocalizedInfoItemFieldReader**

The proposed fix changes the class to switch from using the **LocalizedInfoItemFieldReader** interface, to using the commonly used **InfoItemFieldReader** interface. 
- This would mean that **LocalizedInfoItemFieldReader** is no longer used by any other Liferay class. 
- However, this API is provided by the **info-api** module, which belongs to the Info Framework (which belongs to echo from my understanding).

Just wanted to mention this, in case we decide to do additional clean-up or would like to share this.

**Additional Note - Separate Issue discovered while testing**
I discovered an actual Expando issue while working on this ticket and have created a separate ticket: 
https://liferay.atlassian.net/browse/LPD-23171

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:2560960685

**Comment by ericyanLr** [comment]
**ci:report analysis**
No unique failures. Semver issues unrelated.

Marking as **QA Passed** and **Ready to Review (no regression)**.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6896

**Pull request closed without merging**
