### PR TITLE
LPS-149099 Move commons-collections4.jar to portal-tika

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hi, @koor4356. Can you help me with this pr? I don't know the reason why the test suites are not working. Thx

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
ci:retest:acceptance

**Comment by koor4356** [comment]
ci:retest:relevant

**Comment by vicnate5** [comment]
ci:retest:relevant

**Comment by koor4356** [comment]
@rafaprax 
Can you look into this error? Did you change anything in the class below?
`[beanshell] Created cache file in /tmp/jenkins-cached-files/1489562007.txt

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:13890: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:13907: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-portal-acceptance-pullrequest.xml:668: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-portal-acceptance-pullrequest.xml:452: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test-batch.xml:3773: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test-batch.xml:1013: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-dist.xml:271: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build.xml:375: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/sql/build-parent.xml:44: java.util.ServiceConfigurationError: com.liferay.portal.kernel.module.util.SystemBundleProvider: Provider com.liferay.portal.test.osgi.TestSystemBundleProvider could not be instantiated
`

**Comment by koor4356** [comment]
@rafaprax 
I have fetched your branch so that I can compile it locally. Here is what I did to reproduce the error. I have run "ant all" after git clean. So the error is unique to this PR. It is not happening upstream or it is not affecting other pull requests. Please take a look, thanks!

https://gist.github.com/koor4356/8f759bd0eada8f70d02405b2914c508a

**Comment by rafaprax** [comment]
Thanks a lot @koor4356. I'll try this.

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Pull request closed without merging**
