### PR TITLE
[Component with its own class name as service type] LPS-200508 refactor components from vulcan-api-impl with its own class name as service type

### PR DESCRIPTION
**Pull request by rcsdnj**
Removed from OSGi the GraphQLDTOContributorDataFetchingProcessor and LiferayMethodDataFetchingProcessor components and moved their initialization to the proper places

Also checked with Rafael Praxedes in https://github.com/rafaprax/liferay-portal/pull/1326

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Review by rafaprax — APPROVED** [review]

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6192

**Pull request closed without merging**
