### PR TITLE
LPD-16305 Company creation integration test

### PR DESCRIPTION
**Pull request by dantewang**
- LPD-16305 Add an integration test to measure the performance of creating company
- LPD-16305 Auto SF

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:2540997141

**Comment by tinatian** [comment]
@dantewang Please make this configurable, for example, how many companies created and how many threads using.
Also, please include the statistic result instead of LoggingTimer.

Thanks.
Tina

**Pull request closed without merging**
