### PR TITLE
[Components with more than 1 service] LPS-187067 Refactor components from frontend-js and frontend-theme module

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-187067](https://liferay.atlassian.net/browse/LPS-187067)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
ci:test:frontend

**Comment by Kvale1733** [comment]
Hey @RenanUmV @MrJohn1911 

It looks like the issue Summer described here still happens: https://github.com/liferay-core-infra/liferay-portal/pull/4744#issuecomment-1596820933

**Comment by dantewang** [comment]
It seems this PR is doing the same thing of https://github.com/liferay-core-infra/liferay-portal/pull/4971, closing this one in favor of the newer one.

**Pull request closed without merging**
