### PR TITLE
[Replace Non-Blocking Usage] LPS-197545 Replace the usage of non-blocking ServiceProxyFactory with class ModelResourcePermissionRegistryUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141590

**Pull request closed without merging**
