### PR TITLE
LPS-150410 Remove jaxws-rt.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @koor4356, Can you please scan these test results? Thx

**Comment by koor4356** [comment]
@rafaprax 
This looks good, thanks!

**Comment by rafaprax** [comment]
@shuyangzhou It's ready for your review. Thx

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115453
@rafaprax I dropped your last commit for the sake of older branches.

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
