### PR TITLE
[Optional Reference]Lps 185415 6 14

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-185415

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:search

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
