### PR TITLE
[TS] LPS-201076

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@marianoalvarosaiz I found no regressions. But this seems to be untestable right now due to https://liferay.atlassian.net/browse/LPS-201589

**Comment by yuhai** [comment]
@marianoalvarosaiz, I noticed the issue is a regression bug. I think it should be caused by 3f13710044df3ae2b844e6b04c1c12b5b07c02df. Please link the LPS-186808 to the ticket as Caused by. I have two suggestions for the fix.

1. For the commit(dd89e34eb6942b5fa745de8deefe7108a0a9a277) message, I think it is not right. Without the fix, BundleManagerImpl also is published as BundleManager service. I think the commit is for the next commit. You may edit it for "Add methods to BundleManager inferface, prepare for next"

2. As you mentioned the commit message (7be4def016ed70191f314f98c4f89fc89ca5ccf0), there are two `BundleManagerUtil `classes in the different modules `marketplace-service` and `marketplace-app-manager-web`. Let's move them to `marketplace-api`. The reason is that after the current fix, `BundleManagerUtil `of `marketplace-app-manager-web` won't include other new created methods in the interface, it seems a little weird. In addition, it also can avoid the duplicated classes.

Optional: We may replace `BundleManagerUtil `with `@Reference BundleManager` in the AppLocalServiceImpl. 
 
Refer to https://liferay.atlassian.net/wiki/spaces/ENGUSM/overview, the component might belong to AppSec team. Please resend it to AppSec team.

I am going to close the pr. Please let me know if you have further concerns.

Thanks,
Hai

**Comment by marianoalvarosaiz** [comment]
@yuhai I'll take a look to your comments, but before only one thing:

I know the component belongs to the AppSec team, but it was caused by a refractor in LPS-186808 that our team did. Is it OK then to send it to the AppSec team?

Kid regards.

**Comment by yuhai** [comment]
@marianoalvarosaiz, I think LPS-186808 didn't belongs to refactor. It removed publishing itself as service. The current fix belongs to refactor. We will add new methods to interface and then avoid duplicated classes using. 

I agree with you because the regression bug was caused by our team did, please firstly send it to our team :).

**Comment by marianoalvarosaiz** [comment]
@yuhai see https://github.com/liferay-core-infra/liferay-portal/pull/6179

**Pull request closed without merging**
