### PR TITLE
LPS-143628

### PR DESCRIPTION
**Pull request by julschong**
Hi Shuyang, Tina,
This is the 2nd subtask for removing the Utils in modules 
[LPS-143628](https://issues.liferay.com/browse/LPS-143628)
it removes CurrentConnectionUtil, EditorConfigurationFactoryUtil, and GhostscriptUtil

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by vicnate5** [comment]
@julschong No unique failures found here. Are you rebasing your branch to upstream before you send the PR? Doing this should help prevent the unrelated SF failures.

**Comment by julschong** [comment]
@vicnate5 I think I did, but I will try again

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@shuyangzhou @tinatian
Hi Shuyang, Tina,
Please help me review if this is good to go.
Thank you!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/112469

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
