### PR TITLE
LPS-161447 Commerce Product - remove deprecated

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:commerce

**Comment by dantewang** [comment]
@zhangyan0701 Could you please review the test results when they finish? Thanks!

**Comment by zhangyan0701** [comment]
Integration test com.liferay.commerce.product.service.test.CPDefinitionLocalServiceTest failed with error:
`com.liferay.commerce.product.service.test.CPDefinitionLocalServiceTest.testAddCPDefinitionWithDefaultInstance: java.lang.AssertionError:  [ SCENARIO Add product definition GIVEN I add a product definition WHEN ignoreSKUCombinations is false  AND hasDefaultInstance is true THEN product definition should be APPROVED  AND default product instance should be INACTIVE ] [ Message: [] expected:<1> but was:<0> ]`

Full console:
https://testray.liferay.com/reports/production/logs/2022-08/test-1-29/test-portal-acceptance-pullrequest(master)/4283/modules-integration-mysql57-jdk8/0/5/jenkins-console.txt.gz?authuser=0

**Comment by tinatian** [comment]
ci:test:commerce

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@zhangyan0701 Please help me scan test results.

Thanks.
Tina

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by tinatian** [comment]
Rebased at Aug.30

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122461

**Pull request closed without merging**
