### PR TITLE
[OrderByComparator] LPD-25933 Clean up and Apply Singleton in dynamic-data-mapping module part I

### PR DESCRIPTION
**Pull request by MrJohn1911**
This pull already passed in the ci [here](https://github.com/liferay-core-infra/liferay-portal/pull/7017), I just resend it modifying the name of the method from "get" to "getInstance".

CC: @tinatian @dantewang

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@MrJohn1911 Please separate the build.gradle change into a different commit and highlight the reason you found.

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:forms

**Comment by MrJohn1911** [comment]
ci:report:2571512500

**Comment by MrJohn1911** [comment]
ci:report:2571497925

**Comment by MrJohn1911** [comment]
ci:test:stable

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/150650

@MrJohn1911 Please note that I modified some commit messages.

cc @tinatian

**Pull request closed without merging**
