### PR TITLE
[TS] LPD-20262

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team,

**Context**
When using the poi / tika libraries, the following exception is currently being logged as WARN message in the Liferay logs:
```
org.xml.sax.SAXNotRecognizedException: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
```
- This started to occur after modularizing libraries to: **shared-dependencies-poi**

We had existing tests that resulted in the same WARN messages being logged, however, this was eventually resolved by swallowing these WARN messages.

A customer started noticing these messages in their logs as well.

----

For additional details, please see the commit messages.

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:2549808027

**Comment by tinatian** [comment]
ci:help

**Comment by tinatian** [comment]
ci:test:help

**Comment by tinatian** [comment]
ci:test:document

**Comment by tinatian** [comment]
ci:test:message-boards

**Comment by tinatian** [comment]
ci:test:wiki

**Comment by tinatian** [comment]
@ericyanLr Nice catch! 

FYI @AliciaGarciaGarcia @robertoDiaz This is a real bug covered by your fix for https://liferay.atlassian.net/browse/LPS-177568, so we reverted your fix at https://github.com/liferay-core-infra/liferay-portal/pull/6768/commits/14ba99e29a3e296476f30e78ef8d0365d8ab0858

FYI @jeffwu0724

**Comment by tinatian** [comment]
ci:report:2549933757

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/148183

**Pull request closed without merging**
