### PR TITLE
LPS-162898 - remove use of "portal_impl" in portal-lpkg-deployer-impl

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is the sub-task of https://issues.liferay.com/browse/LPS-149354.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hi @catarineaguiar , could you please double-check for me if my PR causes this regression? I try to reproduce locally but I can't see this regression.
Thanks!

**Comment by catarineaguiar** [comment]
@jeffwu0724 the failure is not related to your changes.

**Comment by tinatian** [comment]
@jeffwu0724 No, this is not I want. What's in LPKGNeededProps is duplicated with PropsValues. Please use Props instance like _props.get() instead of using PropsUtil. 
For example: https://github.com/liferay-core-infra/liferay-portal/blob/dea6d68e54edb40fcfaad6631eb45fda041f0b47/modules/apps/oauth2-provider/oauth2-provider-rest/src/main/java/com/liferay/oauth2/provider/rest/internal/endpoint/authorize/message/body/OAuthAuthorizationDataMessageBodyWriter.java#L76

**Pull request closed without merging**
