### PR TITLE
LPS-203425  move cxf and geronimo to shared-dependency

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Dante,

Resent: https://github.com/liferay-core-infra/liferay-portal/pull/6383
As in geronimo-jaxrs_2.1_spec-1.1.jar/META-INF/MANIFEST.MF, there's Require-Capability header declaring requirement for service loader support of [javax.ws.rs](http://javax.ws.rs/).ext.RuntimeDelegate, added this in shared-dependencies-geromino to make sure serviceloader can find the right RuntimeDelegateImpl.
In this PR, I am moving cxf and geronimo from portal-remote-jaxrs-whiteboard to shared-dependencies, so that we do not need to deploy them for other to use.
The reason why I also move geronimo out is: both com.liferay.portal.remote.jaxrs.whiteboard and shared-dependencies-cxf are using geronimo-jaxrs_2.1_spec, and com.liferay.portal.remote.jaxrs.whiteboard is also using shared-dependencies-cxf, which caused some LinkageError.

Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
unique failure:
https://testray.liferay.com/home/-/testray/case_results/2487296475
https://testray.liferay.com/home/-/testray/case_results/2487296207
https://testray.liferay.com/home/-/testray/case_results/2487268995

**Review by dantewang — APPROVED** [review]

**Comment by jeffwu0724** [comment]
no code conflict: 1/16/2024 - 8:55am

**Comment by jeffwu0724** [comment]
ci:close

**Pull request closed without merging**
