### PR TITLE
LPD-1901 Dyanmically pass the Alias javaType based on the output formula object field setting

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
## Related tickets

- https://liferay.atlassian.net/browse/LPD-1901

## Motivation

A decimal number is expected in the following use case but it always set the output type as the expression1 [here](https://github.com/liferay/liferay-portal/blob/bb9d7a1d3cecde95457c46f7c75c2d7d4090ecf6/portal-kernel/src/com/liferay/portal/kernel/service/persistence/impl/BasePersistenceImpl.java#L1148),

**Given:** a division DSLFunction expression like this `expression1 / expression2` where the expression1 is a non-decimal column.

**When:** this expression is evaluated as an alias with the following operands 3 and 2 (e.g.: `3 / 2 as foo`)

**Then:** the result is 1 instead of 1.5 that is the expected due to [this](https://github.com/liferay/liferay-portal/blob/bb9d7a1d3cecde95457c46f7c75c2d7d4090ecf6/portal-kernel/src/com/liferay/portal/kernel/service/persistence/impl/BasePersistenceImpl.java#L1148)

## Proposed Solution

Dynamically pass the Alias javaType based on the business rule needs (e.g.: formula output object field setting)

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@MarinhoFeliphe 

Please see https://github.com/liferay-core-infra/liferay-portal/pull/7300

Please note I did NOT include the changes for object related code.

In my opinion this is more like a new feature rather than a bug fix, it would be hard to backport this as it has major version bump.

@vicnate5 what do you think?

**Comment by MarinhoFeliphe** [comment]
Thanks @tinatian! I'll work on top of it.

**Comment by vicnate5** [comment]
@tinatian I agree that separating the Objects changes and DSL changes makes sense. But the major version bump is coming from the DSL change, so we still have a "new feature" and breaking change. Your new commit https://github.com/liferay-core-infra/liferay-portal/pull/7300/commits/00300f7263b0c9166f69ff1cbfbf34ce0131fcb5 is missing the breaking change description from https://github.com/liferay-core-infra/liferay-portal/pull/7294/commits/6873ea80452c797ce7722cc13ef59b8f2d9872ea

**Pull request closed without merging**
