### PR TITLE
[PowerMock] LPS 151993 

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove powermock usages (Misc) part three.

https://issues.liferay.com/browse/LPS-151993

Thanks
Janis.

### CODE REVIEW

**Review by dantewang — APPROVED** [review]
@tinatian

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina.

**Comment by catarineaguiar** [comment]
@tinatian @JanisZhang sorry the delay. No regressions were found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/117022

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
