### PR TITLE
[TS] LPS-146970 BackgroundTaskManager initialization

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @liferay-core-infra Team,

I'm resending https://github.com/liferay-core-infra/liferay-portal/pull/411 , I made some changes based on comments on https://github.com/yuhai/liferay-portal/pull/281 .

Please review my changes.

Thanks,
Vendel

cc: @tinatian, @yuhai

### CODE REVIEW

**Comment by tinatian** [comment]
@vendeltoreki There is circular dependency about messaging related component started. It seems complex as it needs to refactor the background logic a lot. I am wondering how urgent is this?

Tina.

**Comment by vendeltoreki** [comment]
Hi @tinatian ,

Thanks for reviewing the changes. I wouldn't consider this issue urgent, as we already have a workaround solution, and the issue itself is also quite hard to reproduce. It only came up once in one specific environment.

As for the circular dependency, I think this solution avoids it by initializing the `MessageListener`s outside `BackgroundTaskManager` and `BackgroundTaskMessagingConfigurator`.
So the initialization order looks like this:
* `BackgroundTaskMessagingConfigurator` (registers the destinations, does not depend on any of the `MessageListener`s)
* `BackgroundTaskManager` (depends on the Configurator)
* `MessageListener`s (depend on `BackgroundTaskManager`, attach themselves to the already registered destinations)

At least that's my theory, but I might be wrong. When I tested the solution, I could start up the portal without errors, and the `doReceive(..)` methods of the listeners were called as expected.

**Comment by vendeltoreki** [comment]
Hi @tinatian ,

Did you manage to schedule some time to work on this? I was wondering how we should proceed with this issue: should support or PT do the refactor?

Thanks,
Vendel

**Comment by tinatian** [comment]
@rafaprax Please take this over.

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
Hey @tinatian,

The @vendeltoreki's changes look good to me. I just caught/noticed some small SF issues.

Thx

**Comment by tinatian** [comment]
@rafaprax Without the changes in this pull, in BackgroundTaskManager's activate method, it will wire up the destinations and listeners, then trigger cleanUpBackgroundTasks() which requires the destination and listeners.

After the changes in this pull, when cleanUpBackgroundTasks() happens, it is possible that the listeners is not ready yet which means a message may be missed before the listener is ready.

I do not have a solution for this yet, but this kind of relation does not look right. Could you please take a look at it and see if you have any suggestions? We can have a talk about it for further discussion.

Tina.

**Comment by rafaprax** [comment]
@tinatian got it. I'll check this behavior and try to find out a solution. I will discuss my findings with you.

Thanks for bringing this up.

**Comment by rafaprax** [comment]
Hey @tinatian, I took a look and found a way to deal with the concern about missing messages when Listeners are not ready yet.  

I sent the changes here https://github.com/liferay-core-infra/liferay-portal/pull/606.

Thx

**Pull request closed without merging**
