### PR TITLE
[MB Performance] LPS-152914 Avoid repeatedly creating MBGroupServiceSettings and CaptchaConfiguration in a request's scope

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Results see https://issues.liferay.com/browse/LPS-152914

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:messageboards

**Comment by dantewang** [comment]
ci:test:message-boards

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina.

**Comment by tinatian** [comment]
@dantewang Please remove the method you replaced, for example MBGroupServiceSettings#getInstance()

**Comment by dantewang** [comment]
@tinatian I only replaced `MBGroupServiceSettings#getInstance` usages in the web module, however it's also used by `message-boards-service` or `headless-delivery-impl`, where it can't be cached in the request. Since the creation of the `MBGroupServiceSettings` involves database operations, it may not be cached globally either.

**Comment by catarineaguiar** [comment]
@dantewang @tinatian no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
