### PR TITLE
LPS-144640 Remove concurrent.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by tinatian** [comment]
@koor4356 Please help me scan test results.

Thanks.
Tina.

**Comment by guilhermedcamacho** [comment]
As @koor4356 was out today, I don't know if he will work tomorrow. 
Hey @zhangyan0701 please help us to scan test results. Thanks!

**Comment by zhangyan0701** [comment]
Just started reviewing.

**Comment by zhangyan0701** [comment]
Hi @rafaprax 

Have checked the results, no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
