### PR TITLE
 [Components with more than 1 service] LPS-176076 Refactor DTOConverter components with more than 1 service type from headless-commerce-machine-learning-impl module

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by daiazius** [comment]
Hi @tinatian, can you check this PR please? Thank you

**Pull request closed without merging**
