### PR TITLE
[OrderByComparator] LPD-28569 Clean up and Apply Singleton in kernel comparator part I

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPD-28569](https://liferay.atlassian.net/browse/LPD-28569)
- **LPD-28569 Add singleton to GroupFriendlyURLComparator and apply**
- **LPD-28569 Add singleton to GroupIdComparator and apply**
- **LPD-28569 Add singleton to GroupTypeComparator and apply**

[LPD-28569]: https://liferay.atlassian.net/browse/LPD-28569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:report:29057362

**Comment by Valmir-unicap** [comment]
Reevaluating!
CC: @titokenzo

**Pull request closed without merging**
