### PR TITLE
LPS-170267 Remove "immediate = true" from Portal III 

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**
Talking to @rafaprax , we noticed that for the tests in the UpgradeReportLogAppenderTest.java file not to fail, this class needs to be immediate because it is not referenced by other classes.

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:startup

**Comment by GabrielHenriquedev** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by GabrielHenriquedev** [comment]
@tinatian this one is ready to go.

**Comment by tinatian** [comment]
@GabrielHenriquedev Please do not modify the same class twice in different commit especially when you want to highlight some changes. Here you remove "immediate = true" and later add it back, this is really confusing.

Please resend.

Tina

**Pull request closed without merging**
