### PR TITLE
[Remove Blocking usages]LPS-189701 bean-portlet | CDIBeanPortletExtension, SpringBeanPortletExtension

### PR DESCRIPTION
**Pull request by W2jx**
Resend, move `BeanPorltetRegistrarUtil` to the correct package.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5414

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:portlet-deployment

**Comment by W2jx** [comment]
ci:test

**Comment by W2jx** [comment]
ci:test:jsf

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(9/4 9:02)

**Review by dantewang — APPROVED** [review]

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140183

**Pull request closed without merging**
