### PR TITLE
LPS-142278 Remove portal lib dir property 12-21

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@koor4356 can you scan this one?

**Comment by koor4356** [comment]
okay

**Comment by koor4356** [comment]
@tinatian  @vicnate5 
It looks good. No unique failure.

**Comment by tinatian** [comment]
@shuyangzhou This is good to go. Please prioritize this, this is easy to have code conflicts with the clean-lib changes.

Thanks.
Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/111451

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
