### PR TITLE
LPS-162507

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
I'm sending this to core instead of the uniform team because I'm modifying a bit the logic Shuyang followed to fix the regression caused in b72cf6769dad8e741dd5ea2e8af169f80bf9ffb0 with 4c526af8664e7c48c9dfae8440ad18308de82e3f so I'll need the approval.

The solution is an approach to allow engineers continue registering upgrade steps in the normal step registrator knowing that they will be executed not matter if it's an installation from zero or an update.

**Comment by dantewang** [comment]
cc @achaparro

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results when they finish?

**Comment by zhangyan0701** [comment]
Upgrade failed with below error:
```
     [java] 2022-09-08 07:37:03.287 ERROR [main][UpgradeStepRegistratorTracker:221] Failed upgrade process for module com.liferay.client.extension.service
     [java] java.lang.IllegalStateException: Unable to upgrade com.liferay.client.extension.service to 3.4.0 from 3.2.0
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.execute(UpgradeExecutor.java:134) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.registry.UpgradeStepRegistratorTracker$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeStepRegistratorTracker.java:214) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.registry.UpgradeStepRegistratorTracker$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeStepRegistratorTracker.java:147) ~[?:?]
     [java] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:891) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:487) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:1004) ~[org.eclipse.osgi.jar:?]
     [java] 	at com.liferay.client.extension.internal.upgrade.registry.ClientExtensionServiceInitialDeploymentUpgradeStepRegistrator$1.doUpgrade(ClientExtensionServiceInitialDeploymentUpgradeStepRegistrator.java:66) ~[?:?]
```

Example failed test:
https://testray.liferay.com/home/-/testray/case_results/1970172800
Full console log:
https://testray.liferay.com/reports/production/logs/2022-09/test-1-25/test-portal-acceptance-pullrequest(master)/4493/functional-upgrade-tomcat90-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0

**Comment by achaparro** [comment]
Hi @dantewang,

I think it is fine because the _initialDeploymentUpgradeSteps_ are intended to be executed after the initial upgrade step (creation of the tables). I guess there are other options but I don't see any problem so far with this. @shuyangzhou added this logic by the way. 

Anyways, @marianoalvarosaiz is going to review the changes to changes to solve the test failure.

**Comment by marianoalvarosaiz** [comment]
Sure @achaparro,
 the problem with the test is that right now there's no way to ensure that if we have two components executing upgrade steps from same module they will be executed in order according to their schema version transitions.
I'll think a different solution and send you a new pull.

**Comment by marianoalvarosaiz** [comment]
@dantewang see [LPS-162507](https://github.com/liferay-core-infra/liferay-portal/pull/1671)

**Pull request closed without merging**
