### PR TITLE
[Components with more than 1 service] LPS-183518 Refactor PortletProvider implementations part II

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-183518

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:lima

**Comment by rafaprax** [comment]
ci:test:commerce

**Comment by rafaprax** [comment]
ci:test:echo

**Comment by rafaprax** [comment]
ci:test:data-engine

**Comment by rafaprax** [comment]
ci:test:lima

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by rafaprax** [comment]
Hey @tinatian, I just made a SF change on the second commit. I was using a static block to initialize the service tracker which in that case is not required. So, I just changed to init in the declaration statement as before. See the diff here https://github.com/liferay-core-infra/liferay-portal/compare/08e85bbeb415093bcf2abe376fe835d0d2f99efc..46e6a307584aa637ba0072792392479d6ba6acb9

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci: forward:force

**Comment by rafaprax** [comment]
ci:forward:force

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
@tinatian @rafaprax Manually sent to https://github.com/brianchandotcom/liferay-portal/pull/137157

**Pull request closed without merging**
