### PR TITLE
[Replace Non-Blocking Usage] LPS-199962

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace non-blocking ServiceProxyFactory usages in class `WebServerServlet` and `OrganizationLocalServiceImpl`. Thanks.
https://liferay.atlassian.net/browse/LPS-199962

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
No regressions found. Just going to rerun stable to make sure that compile batch passes.

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142894

cc @shuyangzhou

**Pull request closed without merging**
