### PR TITLE
LPS-167148 Remove "immediate = true" from Journal Content Asset Addon components

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-167148

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by jaydawu** [comment]
@dantewang, no regression found. Thanks!

**Comment by rafaprax** [comment]
@tinatian this pr is ready for your review. Thx

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128066

**Pull request closed without merging**
