### PR TITLE
[OrderByComparator] LPD-26935 Cleanup and Apply Singleton in knowledge-base module part I

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:content-management

**Comment by MrJohn1911** [comment]
ci:report:2572488215

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:content-management

**Comment by MrJohn1911** [comment]
ci:report:2572998683

**Comment by MrJohn1911** [comment]
ci:report:2572998683

**Comment by MrJohn1911** [comment]
ci:report:2572984684

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
Reevaluating!
CC: @titokenzo

**Pull request closed without merging**
