### PR TITLE
[Bug Fix] LPS-176122  Remove duplicated stream usages

### PR DESCRIPTION
**Pull request by JanisZhang**
I found this problem when removing the stream usage in _SegmentsContextVocabularyConfigurationModelListener.java_ and _SegmentsContextVocabularyCompanyConfigurationModelListener.java._

In c7d2c0bf54eda6be22fdbebd767cd137aac028e1, the `companyConfigurationStream` was added to `SegmentsContextVocabularyConfigurationModelListener.java`  to listen to the company configuration. 

After the author added the company configuration itself listener `SegmentsContextVocabularyCompanyConfigurationModelListener.java` in 98cd2b1fba02f74ef520dacd76833da379f45407. I think `companyConfigurationStream` is no longer needed.

The same problem occurs in `SegmentsContextVocabularyCompanyConfigurationModelListener.java`.

Please correct me if I got wrong. Thanks!

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:tango

**Comment by zhangyan0701** [comment]
Many segmentation tests failed due to a blocker which will be fixed in https://github.com/brianchandotcom/liferay-portal/pull/130567. It's better to re-trigger the tests when the fix got merged.

**Comment by JanisZhang** [comment]
Gotcha! Thanks @zhangyan0701 !

**Comment by Kvale1733** [comment]
Fix is still not in upstream. Will re trigger tests when it's in upstream.

**Comment by Kvale1733** [comment]
ci:test:tango

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
Closing, since it's sent to Tango for review.

**Pull request closed without merging**
