### PR TITLE
[Static Reference] LPS-182296 UploadImageUtil

### PR DESCRIPTION
**Pull request by dantewang**
@slnn

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
ci:test:lima

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133872, I dropped my last commit as it may end up in database thus changing it requires a DB upgrade.

**Pull request closed without merging**
