### PR TITLE
[Remove Blocking usages]LPS-187901 portal-kernel | WorkflowEngineManagerUtil

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi Dante,

In this pull request, I removed the `isDeployed()` method from `WorkflowEngineManager` and its implementation. Instead, I modified the implementation to check the existence of the `WorkflowEngineManager` service using `WorkflowEngineManagerUtil`. This change provides a more accurate module deployment state representation and avoids blocking in ServiceProxyFactory.

Thanks!
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4884

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:workflow

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:workflow

**Review by dantewang — APPROVED** [review]

**Review by dantewang — CHANGES_REQUESTED** [review]
@JanisZhang It seems `WorkflowEngineManager` is not used by any one, and the values returned by `WorkflowEngineManagerImpl` doesn't match the reality (version 6.0.0). This interface should be from the old days when the workflow is just a WAR plugin deployed to app server.

I wonder if we can just remove all of them - the interface, the impl, and the util, just pretending that the workflow engine is always there. Could you ask the Workflow team about whether this `WorkflowEngineManager` still means anything?

**Comment by JanisZhang** [comment]
Waiting for the product team's response. https://liferay.atlassian.net/browse/PTR-4161

**Comment by dantewang** [comment]
Closing this one for now, please resend once the PTR is answered.

**Pull request closed without merging**
