### PR TITLE
LPD-2571 - Widget scopes not correctly applied when staging

### PR DESCRIPTION
**Pull request by ericyanLr**
**Previous PR:** https://github.com/liferay-core-infra/liferay-portal/pull/6440

Hi Team,

**Noteable Changes**
- In the previous PR: 
    - Suggestions from yuhai we're applied: [#6440 (review)](https://github.com/liferay-core-infra/liferay-portal/pull/6440#pullrequestreview-1831866845)
    - Tests have been added as requested: [#6440 (comment)](https://github.com/liferay-core-infra/liferay-portal/pull/6440#issuecomment-1939815642)
- Changes from this PR:
    - Changed commit ticket names from LPS-150134 to LPD-2571
    - Added additional commit to avoid NPE and to simplify else block

Please let me know if you have any questions.
Thanks!

/cc @MirnaGama

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:2543715318

**Comment by ericyanLr** [comment]
**ci:report analysis**
No unique failures

Marking this PR as QA Passed and Ready to Review (no regression)

/cc @tinatian

**Comment by tinatian** [comment]
@ericyanLr Closed as we talked.

Tina.

**Comment by ericyanLr** [comment]
Hi @MirnaGama ,

**Update**
I'll be reviewing the PR again.

Please let me know if you have any questions.

**Pull request closed without merging**
