### PR TITLE
[Method References 2] LPS-165748 Convert method reference to ServiceTrackerList in module portal-search

### PR DESCRIPTION
**Pull request by W2jx**
As [discussed](https://liferay.slack.com/archives/CKY6GP7BL/p1676960702922889), I just converted method references to serviceTrackerList

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:help

**Comment by W2jx** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by W2jx** [comment]
no conflicts(2/24 9:48)

**Comment by W2jx** [comment]
no conflicts(2/27 8:30)

**Comment by W2jx** [comment]
no conflicts(2/28 9:45)

**Comment by W2jx** [comment]
no conflicts(3/1 10:45)

**Comment by tinatian** [comment]
@W2jx After you made variables private, you should also made `protected FieldQueryBuilder getQueryBuilder(String fieldName) ` private.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:search

**Comment by W2jx** [comment]
Hi @tinatian , I have made protected FieldQueryBuilder getQueryBuilder(String fieldName)  private.

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(3/7 9:02)

**Comment by W2jx** [comment]
no conflicts(3/8 15:25)

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131448

**Pull request closed without merging**
