### PR TITLE
[TS] LPS-155431 If you embed a portlet in a layout templates using 'processor.processPortlet' it doesn't follow the render weight order. This causes problems to embedded breadcrumb portlets.

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
If you embed a portlet in a layout templates using 'processor.processPortlet' it doesn't follow the render weight order.

This causes problems to embedded breadcrumb portlets:

- The breadcrumb portlet must be rendered after the Asset Publisher because this portlet modifies the breadcrumb path, adding the selected webcontent.
- If it is rendered before the Asset Publisher, it won't show the "selected element" fragment of the breadcrumb path

See the steps to reproduce in https://issues.liferay.com/browse/LPS-155431 description

To solve this I am changing the `_processPortlet` method to use the same logic than `_processColumn`. In this method, the portlets are stored in the portletRenderersMap according to their render weight value and after that they are retrieved and rendered in the RuntimePageImpl class using the correct order:

1. **Commit https://github.com/liferay-core-infra/liferay-portal/commit/08a0aef742a58b96e7c9f473029ac7eecbf1548:** I have extracted the existing code from `_processColumn` that handles their portlets to a new `_renderPortlet` method
2. **Commit https://github.com/liferay-core-infra/liferay-portal/commit/8a931bb99217bb9d3b9defeb6b15857b450ab77c:** Use the new `_renderPortlet` method in the `_processPortlet` method that handles the **processor.processPortlet** to render the embedded portlets
3. **Commit https://github.com/liferay-core-infra/liferay-portal/commit/45dd0301d100327df790b9c7eac8c86aa7ef10d0:** Set/remove the RENDER_PORTLET_RESOURCE attribute  in the same way it was done in the old processPortlet code, this attribute was added to solve LPS-10349

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
Hi @liferay-core-infra 

Do you have any update about this pull request?

Thank you

**Comment by tinatian** [comment]
@jorgediaz-lr Please see my comment and resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

I don't see any comment, can you explain me what do I have to change?

Thank you

**Pull request closed without merging**
