### PR TITLE
[Remove Stream usages on method body:anayltic]Lps 172272 stream

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-172272

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:analytics-cloud

**Comment by zhangyan0701** [comment]
ci:test:analytics-cloud

**Comment by catarineaguiar** [comment]
some functional tests from analytics cloud suite had unique failures, but let's wait for this fix to check if they are related.

**Comment by dantewang** [comment]
@slnn Conflicts, please resend, and fix the errors.

**Comment by slnn** [comment]
Fix the err




> @slnn regression found:
> 
> ```
>      [exec] com.liferay.analytics.reports.web.internal.portlet.action.test.GetTrafficSourcesMVCResourceCommandTest > testGetTrafficSources FAILED
>      [exec]     java.lang.NullPointerException
>      [exec]     	at com.liferay.analytics.reports.web.internal.portlet.action.test.GetTrafficSourcesMVCResourceCommandTest.lambda$testGetTrafficSources$3(GetTrafficSourcesMVCResourceCommandTest.java:156)
>      [exec]     	at com.liferay.analytics.reports.test.util.MockContextUtil.testWithMockContext(MockContextUtil.java:104)
>      [exec]     	at com.liferay.analytics.reports.web.internal.portlet.action.test.GetTrafficSourcesMVCResourceCommandTest.testGetTrafficSources(GetTrafficSourcesMVCResourceCommandTest.java:123)
>      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>      [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>      [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
>      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-26/test-portal-acceptance-pullrequest(master)/7066/modules-integration-mysql57-jdk8/0/7/jenkins-console.txt.gz?authuser=0)

Fix the error and resend in https://github.com/liferay-core-infra/liferay-portal/pull/3337

**Pull request closed without merging**
