### PR TITLE
[Components with more than 1 service] LPS-196872 Refactor PDFProcessorImpl and AMImageEntryProcessor components

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-196872](https://liferay.atlassian.net/browse/LPS-196872)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:document

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:document

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141441

**Pull request closed without merging**
