### PR TITLE
LPD-38234 send password reset email when adminPassword is not set

### PR DESCRIPTION
**Pull request by devopsmystic**
## [LPD-38234](https://liferay.atlassian.net/browse/LPD-38234)

WIP, please don't merge.

2nd Approach : Based on the adminPassword, I am setting the sendEmail flag in company service and then using that flag to send the password reset email in user service. 
24oct: there was a regression issue wherein an admin isn't able to login in a fresh instance, it was due to autoPassword=true and default password wasn't picked up. but then again the password reset email is not working, I opened a thread for it here https://liferay.slack.com/archives/C4SAM7Q9Z/p1729758437660709?thread_ts=1729757708.823769&cid=C4SAM7Q9Z

1st Approach : Setting adminPassword as blank in company service and setting sendEmail flag in user service https://github.com/liferay-core-infra/liferay-portal/pull/7501

[LPD-38234]: https://liferay.atlassian.net/browse/LPD-38234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by devopsmystic** [comment]
ci:test:relevant

**Comment by devopsmystic** [comment]
ci:test:relevant

**Comment by devopsmystic** [comment]
ci:test:stable

**Comment by devopsmystic** [comment]
ci:test:relevant

**Comment by devopsmystic** [comment]
ci:test:stable

**Comment by tinatian** [comment]
@devopsmystic This pull does not seem right too, please see the discussion at https://liferay.slack.com/archives/C0A1Z5FJL/p1729835317153569, I am going to close this pull.

**Pull request closed without merging**
