### PR TITLE
[Remove unused reference] LPS-165883

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove unused fields in `dispatch`. Thanks!

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:data-integration

**Comment by zhangyan0701** [comment]
ci:test:data-integration

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
