### PR TITLE
LPS-200170 Move TunnelAuthenticationManagerImpl into modules

### PR DESCRIPTION
**Pull request by julschong**
@tinatian @dantewang 
Hi Tina, Dante,

This is resubmitted from #6067 following recommendation in https://github.com/liferay-core-infra/liferay-portal/pull/5987#issuecomment-1813129320
Instead of merging into portal-impl Util, I moved the impl into modules since UserLocalService is used.

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Review by dantewang — CHANGES_REQUESTED** [review]
@julschong Since there's major version bump, could you add a breaking change report? Thanks!

**Comment by dantewang** [comment]
ci:test:sf

**Pull request closed without merging**
