### PR TITLE
[Method References 2] LPS-166968 Convert method reference to ServiceTrackerMap in module data-engine-taglib and data-engine-rest-impl

### PR DESCRIPTION
**Pull request by W2jx**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/2915 and https://github.com/liferay-core-infra/liferay-portal/pull/2553

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:data-engine

**Comment by catarineaguiar** [comment]
@W2jx regressionas found:

```
 [echo] diff --git a/modules/apps/data-engine/data-engine-rest-test/src/testIntegration/java/com/liferay/data/engine/rest/resource/v2_0/test/BaseDataRecordResourceTestCase.java b/modules/apps/data-engine/data-engine-rest-test/src/testIntegration/java/com/liferay/data/engine/rest/resource/v2_0/test/BaseDataRecordResourceTestCase.java
     [echo] index 11ec9e558eb5..68422ce2a94b 100644
     [echo] --- a/modules/apps/data-engine/data-engine-rest-test/src/testIntegration/java/com/liferay/data/engine/rest/resource/v2_0/test/BaseDataRecordResourceTestCase.java
     [echo] +++ b/modules/apps/data-engine/data-engine-rest-test/src/testIntegration/java/com/liferay/data/engine/rest/resource/v2_0/test/BaseDataRecordResourceTestCase.java
     [echo] @@ -22,14 +22,12 @@ import com.fasterxml.jackson.databind.ObjectMapper;
     [echo]  import com.fasterxml.jackson.databind.SerializationFeature;
     [echo]  import com.fasterxml.jackson.databind.util.ISO8601DateFormat;
     [echo]  
     [echo] -import com.liferay.data.engine.content.type.DataDefinitionContentType;
     [echo]  import com.liferay.data.engine.rest.client.dto.v2_0.DataRecord;
     [echo]  import com.liferay.data.engine.rest.client.http.HttpInvoker;
     [echo]  import com.liferay.data.engine.rest.client.pagination.Page;
     [echo]  import com.liferay.data.engine.rest.client.pagination.Pagination;
     [echo]  import com.liferay.data.engine.rest.client.resource.v2_0.DataRecordResource;
     [echo]  import com.liferay.data.engine.rest.client.serdes.v2_0.DataRecordSerDes;
     [echo] -import com.liferay.data.engine.rest.resource.v2_0.test.util.content.type.TestDataDefinitionContentType;
     [echo]  import com.liferay.petra.function.UnsafeTriConsumer;
     [echo]  import com.liferay.petra.reflect.ReflectionUtil;
     [echo]  import com.liferay.petra.string.StringBundler;
     [echo] @@ -1558,9 +1556,4 @@ public abstract class BaseDataRecordResourceTestCase {
     [echo]  	private com.liferay.data.engine.rest.resource.v2_0.DataRecordResource
     [echo]  		_dataRecordResource;
     [echo]  
     [echo] -	@Inject(
     [echo] -		filter = "component.name=com.liferay.data.engine.rest.resource.v2_0.test.util.content.type.TestDataDefinitionContentType"
     [echo] -	)
     [echo] -	private DataDefinitionContentType _DataDefinitionContentType;
     [echo] -
     [echo]  }
     [echo] \ No newline at end of file
[stopwatch] [run.batch.test.action: 14:26.038 sec]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-02/test-1-39/test-portal-acceptance-pullrequest(master)/2996/rest-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.data.engine.rest.resource.v2_0.test.DataDefinitionResourceTest > testGetDataDefinitionByContentTypeContentTypePageWithPagination FAILED
     [exec]     com.liferay.data.engine.rest.client.problem.Problem$ProblemException: com.liferay.data.engine.rest.resource.v2_0.test.util.content.type.TestDataDefinitionContentType-com.liferay.dynamic.data.mapping.model.DDMStructure#PERMISSIONS
     [exec]     	at com.liferay.data.engine.rest.client.resource.v2_0.DataDefinitionResource$DataDefinitionResourceImpl.postDataDefinitionByContentType(DataDefinitionResource.java:373)
     [exec]     	at com.liferay.data.engine.rest.resource.v2_0.test.DataDefinitionResourceTest.testGetDataDefinitionByContentTypeContentTypePage_addDataDefinition(DataDefinitionResourceTest.java:668)
     [exec]     	at com.liferay.data.engine.rest.resource.v2_0.test.BaseDataDefinitionResourceTestCase.testGetDataDefinitionByContentTypeContentTypePageWithPagination(BaseDataDefinitionResourceTestCase.java:276)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-02/test-1-39/test-portal-acceptance-pullrequest(master)/2996/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:data-engine

**Comment by catarineaguiar** [comment]
@W2jx this issue is still happening:

```
     [exec] com.liferay.data.engine.rest.resource.v2_0.test.DataRecordCollectionResourceTest > testPutDataRecordCollection FAILED
     [exec]     com.liferay.data.engine.rest.client.problem.Problem$ProblemException: com.liferay.data.engine.rest.resource.v2_0.test.util.content.type.TestDataDefinitionContentType-com.liferay.dynamic.data.lists.model.DDLRecordSet#PERMISSIONS
     [exec]     	at com.liferay.data.engine.rest.client.resource.v2_0.DataRecordCollectionResource$DataRecordCollectionResourceImpl.postDataDefinitionDataRecordCollection(DataRecordCollectionResource.java:445)
     [exec]     	at com.liferay.data.engine.rest.resource.v2_0.test.DataRecordCollectionResourceTest.testPutDataRecordCollection_addDataRecordCollection(DataRecordCollectionResourceTest.java:316)
     [exec]     	at com.liferay.data.engine.rest.resource.v2_0.test.BaseDataRecordCollectionResourceTestCase.testPutDataRecordCollection(BaseDataRecordCollectionResourceTestCase.java:602)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-02/test-1-26/test-portal-acceptance-pullrequest(master)/7689/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
@W2jx Please resend as there are failures.

**Pull request closed without merging**
