### PR TITLE
[TS] LPS-134898 Expando issue

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian I wasn't able to clean up the logic completely to put handling of ExpandoValue first, ExpandoRow second, because rowId is needed when creating ExpandoValue. Then I came up with this way, hopefully it can be clearer.

### CODE REVIEW

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@dantewang As we talked, please debug and resend.

Thanks.
Tina

**Comment by marianoalvarosaiz** [comment]
@dantewang, @tinatian do we have any updates?

**Comment by dantewang** [comment]
@marianoalvarosaiz We planned to dig deeper into it, but was interrupted by some other high priority tasks. Will revisit it soon.

**Comment by marianoalvarosaiz** [comment]
@dantewang are there any updates? Is there something I can do to help?

**Comment by dantewang** [comment]
@marianoalvarosaiz Sorry I didn't get time to dig into it yet.

What we want to dig into is: when the transaction is flushed in process of the 3rd `addValue` in your test, is the `ExpandoRow` entity in the database have the same mvcc version & modified date with what is in memory? If so, then why the next update to this `ExpandoRow` is considered a violation of the optimistic lock? If not, then why they are different?

We want to make sure that our infrastructural code doesn't mess anything here.

**Comment by dantewang** [comment]
@marianoalvarosaiz I digged into it today, will have a discussion with Tina on her Monday next week.

**Comment by marianoalvarosaiz** [comment]
@dantewang thanks a lot!

**Pull request closed without merging**
