### PR TITLE
[Convert method references Round 2] LPS-165273

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to use serviceTrackerMap instead of the method reference in `portal-security-audit`. Thanks!

https://issues.liferay.com/browse/LPS-165273

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:reevaluate:1327401_6135

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@JanisZhang The `PropertyKeyServiceReferenceMapper` doesn't call the `Emitter` which is responsible to call your customizer when the property doesn't exist.

As we talked, please resend.

**Pull request closed without merging**
