### PR TITLE
[Log4j]LPS-154229

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@zhangyan0701 Please help me scan test results when they are ready.

Thanks.
Tina.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by tinatian** [comment]
@GinsonRen Please run a diff on startup.

Thanks.
Tina.

**Comment by 111Anna** [comment]
@tinatian @GinsonRen  Here are results for startup:

Startup:

Portal Version | Git Id | First Startup | Second Startup | Third Startup | Fourth Startup | Fifth Startup | Average Startup | Percent（%）| First Shutdown | Second Shutdown | Third Shutdown | Fourth Shutdown | Fifth Shutdown |Average Shutdown | Percent (%)
-- | -- | -- | -- | -- | -- | -- | -- | -- |-- | -- | -- | -- | -- | -- | --
BaseLine | 3720f69f | 23373 | 23675 | 23564 | 23251 | 23346 | 23441.8ms | - | 28436 | 26235 | 26143 | 28368 | 25704 | 26977.2ms | -
PR-900 | - | 23755 | 23449 | 23510 | 23525 | 23708 | 23589.4ms | 0.62% | 26081 | 27582 | 28181 | 25134 | 25487 | 26493ms | -1.7%

**Pull request closed without merging**
