### PR TITLE
[TS] LPD-24741 Scheduler

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:clustering

**Comment by dantewang** [comment]
ci:report:2566782695

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:sf

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/150103

**Pull request closed without merging**
