### PR TITLE
LPD-23834 Clear cache when removing companies when database partition is enabled

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @LuisOrtiz89

### CODE REVIEW

**Comment by tinatian** [comment]
@victorhcunha Please run diff for login test first, if you see regression, then report. If you did not see regression, please move on to test others.

FYI @slnn

**Comment by victorhcunha** [comment]
Hi @tinatian ! Do you need any special config or can the diff be based on our default tests?

**Comment by achaparro** [comment]
Hi @victorhcunha, I guess it should be the default tests

cc/ @tinatian

**Comment by tinatian** [comment]
@victorhcunha Yes, the diff can be based on default test

**Comment by slnn** [comment]
Here are the test results on Login, no regression appeared, test results for other test cases are on the way

Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
Baseline | 374e19d | 10887 | - | 265 | 2,2,2 | 92,91,93
PR | - | 10973 | 0.7899329476 | 295 | 2,2,2 | 94,92,92

/cc @victorhcunha @tinatian

**Comment by victorhcunha** [comment]
Hi @tinatian ! 
We got lower results when testing the document library in this PR. You can see a decrease in Session Count and a slight increase in database usage. These are the results of a second round with the rebuilt database:

Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | Mean Time of Add DL File | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Baseline | 374e19d | 8255 | - | 279 | 486 | 7,7,7 | 91,89,92
PR | - | 7993 | -3.17383404 | 266 | 463 | 7,8,8 | 91,88,92


I will do a new round to get the async profiler and sql-log
cc @slnn

**Comment by victorhcunha** [comment]
Hi @tinatian !
Here are the new results for Document Library test case. This time the test was run to generate the Async CPU Sampling Profile and the SQL LOG, so in this case it is expected that the result would be lower. Even so, we continued to see a decrease in the PR Session Count and a small increase in the PR DB usage.

Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | Mean Time of Add DL File | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Baseline | 374e19d | 7240 | - | 265 | 504 | 7,7,7 | 88,87,88
PR | - | 7130 | -1.519337017 | 253 | 487 | 7,8,8 | 88,90.87

Would this result be acceptable?
Here are the profile and SQL-LOG files from the tests:

Master Baseline | PR
-- | --
[Async CPU Sampling Profile](https://drive.google.com/file/d/1aLjz3aDKhZ-IqMxp-oKx3tmeNsuQP0rX/view?usp=sharing)| [Async CPU Sampling Profile](https://drive.google.com/file/d/1qjaO4fni5djOCH1UgdZYefv8iH8stxpZ/view?usp=sharing)
[SQL LOG](https://drive.google.com/file/d/1_lV4kx5_bB8B69KpK77SGq56xUArV5ZR/view?usp=sharing)| [SQL LOG](https://drive.google.com/file/d/1tlIOZKJAKJqBspu8OkZIyB56odjTpJpt/view?usp=sharing)

More details in this [spreadsheet](https://docs.google.com/spreadsheets/d/1F5FR4s28zNUM6Xy2qZba2TA4sSxsXetelY2R4Cxhmio/edit?gid=0#gid=0)
cc @tinatian

**Comment by slnn** [comment]
Hi @tinatian 

We run two rounds for test case DL, we rebuild db for the second run,  but we can see stable drop on this pr on session count, but the way, the test results with the Async CPU Sampling can not see the noticeable change between session count because portal is attached with the yjp agent during the test.

First run:
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | Mean Time of Add DL File | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Baseline | 374e19d | 8070 | - | 268 | 478 | 6,7,7 | 92,88,89
PR | - | 7884 | -2.304832714 | 237 | 441 | 8,8,8 | 87,86,85

Second run:
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | Mean Time of Add DL File | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Baseline | 374e19d | 8255 | - | 279 | 486 | 7,7,7 | 91,89,92
PR | - | 7993 | -3.17383404 | 266 | 463 | 7,8,8 | 91,88,92

**Comment by victorhcunha** [comment]
I did another round, this time using a updated baseline for the portal. Even though the test result in PR continues to be lower, I see a smaller difference than in the other rounds

Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | Mean Time of Add DL File | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Baseline | 7e41859 | 8090 | - | 228 | 426 | 8,7,8 | 91,89,89
PR | - | 7999 | -1.124845488 | 234 | 438 | 7,7,7 | 91,89,90


I also generated new profiles and sql-log

Master Baseline |	PR
-- | --
[CPU Tracing](https://drive.google.com/file/d/1hDt0ekw9k1XGh0bLorgLzpJNH3Syryah/view?usp=sharing) | [CPU Tracing](https://drive.google.com/file/d/1SNiVzM1p_YqR6EH4wX4DN27fNZ6hdlaF/view?usp=drive_link)
[SQL LOG](https://drive.google.com/file/d/10gm9RWC3hWob4M8rDBnebwbVQtng4jCI/view?usp=sharing) |  [SQL LOG](https://drive.google.com/file/d/1NQlUDil75Z69e2zz5xh8YQ7aGS9V2waN/view?usp=drive_link)
[Test Result Zip](https://drive.google.com/file/d/1aUaBEMbvMt325k1OREcOBZOtvlPKdLn-/view?usp=sharing) | [Test Result Zip](https://drive.google.com/file/d/1wKtc8MJIzMDdv2xuf2-GHZwUScrCT1qw/view?usp=drive_link)

I updated the [spreadsheet](https://docs.google.com/spreadsheets/d/1F5FR4s28zNUM6Xy2qZba2TA4sSxsXetelY2R4Cxhmio/edit?gid=0#gid=0) with the results.

**Comment by tinatian** [comment]
Closed as we discussed in slack

**Pull request closed without merging**
