### PR TITLE
[Remove Stream/Optional usage] LPS 170599 blogs-web

### PR DESCRIPTION
**Pull request by haydenzheng314**
Remove the usages of Optional<> and Stream<> in module blogs-web.

### CODE REVIEW

**Comment by dantewang** [comment]
@LisztLiszt The final result is good, but the commit order can be further optimized.

Consider https://github.com/liferay-core-infra/liferay-portal/pull/2687/commits/2b49293e8261112d44e67aae9ef270579d634d44, you modify the method to not return an `Optional`, so you also have to make a change in the usage. However, when you just remove the

```
				).filter(
					Optional::isPresent
				).map(
					Optional::get
```

part from the `Stream<>`, the logic becomes incomplete -- the null check is missing. And this is only fixed after you turn the `Stream<>` into the for-loop, with an additional commit, leaving a middle state of wrong code in the git history.

Let's do this: convert this `Stream<>` to the for-loop first, so you still have an if-check in your loop:

```
for (XX xx : xxx) {
    Optional<YYY> yyy = _doSomething();
    if (!yyy.isPresent()) {
        continue;
    }

    list.add(yyy);
}
```

and when you remove the `Optional<>` usage later, you can smoothly turn this into `if (yyy == null) continue`.

**Comment by dantewang** [comment]
@LisztLiszt Please see my comment and resend, thanks!

**Comment by dantewang** [comment]
@W2jx @JanisZhang @slnn Also take a look at this comment and be cautious with your order of changes. Thanks!

**Comment by LisztLiszt** [comment]
@dantewang Get it. Thank you

**Pull request closed without merging**
