### PR TITLE
LPS-157934

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-157934, which is the preparation for ticket https://issues.liferay.com/browse/LPS-149258.
I need to use commos-io version 2.11.0 in portal-tika, and there is a limitation in using 2.8.0 in source-formatter, and that's why I will have to update this in master first.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by tinatian** [comment]
@jeffwu0724 Code looks good to me, wait for QA to scan test results.

Tina

**Comment by catarineaguiar** [comment]
@jeffwu0724 a regression was found:

```
 [exec] > Task :apps:analytics:analytics-dxp-entity-rest-impl:buildREST FAILED
     [exec] Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/io/file/PathFilter
     [exec] 	at com.liferay.portal.tools.java.parser.util.FileUtil.read(FileUtil.java:35)
     [exec] 	at com.liferay.portal.tools.java.parser.JavaParser.parse(JavaParser.java:69)
     [exec] 	at com.liferay.portal.tools.java.parser.JavaParser.parse(JavaParser.java:63)
     [exec] 	at com.liferay.portal.tools.rest.builder.internal.util.FileUtil._format(FileUtil.java:158)
     [exec] 	at com.liferay.portal.tools.rest.builder.internal.util.FileUtil.write(FileUtil.java:151)
     [exec] 	at com.liferay.portal.tools.rest.builder.RESTBuilder._createOpenAPIResourceFile(RESTBuilder.java:907)
     [exec] 	at com.liferay.portal.tools.rest.builder.RESTBuilder.build(RESTBuilder.java:269)
     [exec] 	at com.liferay.portal.tools.rest.builder.RESTBuilder.main(RESTBuilder.java:116)
     [exec] Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.file.PathFilter
     [exec] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [exec] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [exec] 	... 8 more
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-07/test-1-36/test-portal-acceptance-pullrequest(master)/1556/rest-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

Steps to reproduce:

1. `cd modules`
2. `gw :apps:analytics:analytics-dxp-entity-rest-impl:buildREST`

**Pull request closed without merging**
