### PR TITLE
[Remove unused reference] LPS-166419

### PR DESCRIPTION
**Pull request by JanisZhang**
This PR is to remove unused fields in `headless-commerce-delivery-cart-impl`. Thanks!

https://issues.liferay.com/browse/LPS-166419

### CODE REVIEW

**Comment by jaydawu** [comment]
No regressions found.

cc/ @zhangyan0701

**Comment by JanisZhang** [comment]
ci:test:commerce

**Review by dantewang — COMMENTED** [review]
@JanisZhang Any specific reason to not remove https://github.com/liferay-core-infra/liferay-portal/pull/2197/files#diff-0ef7e1be9d19f21427781ca7a9b2cd1f392ec189b01f965722f31ac8a6d162c7R813 ?

**Comment by JanisZhang** [comment]
Hi @dantewang,  Force-pushed. After double-checking,  I cannot find `commerceChannelService` (hidden) usage.

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/125438

cc @shuyangzhou @tinatian

**Pull request closed without merging**
