### PR TITLE
[Remove Spring extender usages] LPS-159586 commerce-price-list-service | 8-11

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Changed to another way to keep the ability to be index-aware. I see some other custom classes being AopService so I went with this.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:commerce

**Comment by dantewang** [comment]
@catarineaguiar Could you review the test results when they finish? Thanks!

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@dantewang semver error:

```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/commerce/commerce-price-list-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]       com.liferay.commerce.price.list.helper             ADDED      15.0.0     0.0.0      1.0.0      PACKAGE ADDED, MISSING PACKAGEINFO
     [exec]     	+   interface  com.liferay.commerce.price.list.helper.CommercePriceEntryHelper
     [exec]     		+   access     abstract
     [exec]     		+   method     setHasTierPrice(long,boolean)
     [exec]     			+   access     abstract
     [exec]     			+   return     com.liferay.commerce.price.list.model.CommercePriceEntry
     [exec]     		+   method     setHasTierPrice(long,boolean,boolean)
     [exec]     			+   access     abstract
     [exec]     			+   return     com.liferay.commerce.price.list.model.CommercePriceEntry
     [exec]     	+   version    15.0.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertFalse(Assert.java:64)
     [exec]         at com.liferay.semantic.versioning.SemanticVersioningTest.testSemanticVersioning(SemanticVersioningTest.java:82)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-30/test-portal-acceptance-pullrequest(master)/4142/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
@catarineaguiar Just force pushed and triggered a new run. Thanks!

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
pull good to go!

**Comment by dantewang** [comment]
ci:test:commerce

**Comment by dantewang** [comment]
@zhangyan0701 Could you take a look at the commerce test results? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@dantewang As we talked, please resend.

Thanks.
Tina

**Pull request closed without merging**
