### PR TITLE
LPS-158624 Cleanup petra-xml

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from #2255

moved special char handling conditions into Dom4jUtil.toString()

### CODE REVIEW

**Comment by zhangyan0701** [comment]
Possible related:
Semantic versioning error:
```
     [exec] [Baseline Warning] Bundle Version Change Recommended: 86.1.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/86.0.0/5bf9e20b92dc20fb7f09c794088d44fc1ef3f85c/com.liferay.portal.kernel-86.0.0.jar
```
Full console log:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-26/test-portal-acceptance-pullrequest(master)/5912/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
rebased to resolve semver issue

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126384

**Pull request closed without merging**
