### PR TITLE
[Method References 2] LPS-176632 Convert method reference to ServiceTrackerMap in class CompositeFacetProcessor(module portal-search-solr8-impl)

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3976

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:search-solr

**Comment by Kvale1733** [comment]
@W2jx No regressions.

**Comment by W2jx** [comment]
no conflicts(4/3 9:13)

**Comment by W2jx** [comment]
no conflicts(4/4 10:27)

**Review by dantewang — APPROVED** [review]

**Comment by W2jx** [comment]
no conflicts(4/7 16:16)

**Comment by tinatian** [comment]
@W2jx @dantewang Same reason as https://github.com/liferay-core-infra/liferay-portal/pull/4068.

Please resend.
Thanks.
Tina

**Pull request closed without merging**
