### PR TITLE
LPS-portal-service 11-16

### PR DESCRIPTION
**Pull request by yuhai**
@tinatian, @dantewang.

I did the pr on August and this is I've done. I just rebased it. I will revisit this after finishing "remove immediate=true".

### CODE REVIEW

**Comment by dantewang** [comment]
@yuhai What's the progress (percent) for this pull in the whole task?

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
> @yuhai What's the progress (percent) for this pull in the whole task?

@dantewang, the pr moved non-completed for spring module classes to portal service module. In the portal-spring-extender-impl module, it is only for spring module. I'd like to say 100%.

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@yuhai One thing to verify is to remove the spring-extender module from the built bundle and run all tests that don't deploy spring-base service modules. If all those tests pass, then at least liferay-service-extender part is OK.

**Comment by tinatian** [comment]
@yuhai Please merge these two methods ConfigurationFactory#getConfiguration and ConfigurationFactory#hasConfiguration. For all the usages using hasConfiguration, make it invoke getConfiguration instead, then do a null check

**Comment by tinatian** [comment]
@yuhai I am going to close this pull, please resend.

Thanks.
Tina

**Pull request closed without merging**
