### PR TITLE
LPS-186796 Remove Optional from PortletSharedSearchSettings.getParameter method in portal-search-api

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
@tinatian 
this is resubmitted from https://github.com/liferay-core-infra/liferay-portal/pull/4702 to change ticket number per search team request

**Comment by julschong** [comment]
ci already tested, no need to review again

**Comment by julschong** [comment]
ci:stop

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4726

**Pull request closed without merging**
