### PR TITLE
Lpd 20946 5 3 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
ci:test:object

**Comment by dantewang** [comment]
ci:report:2565681930

**Comment by dantewang** [comment]
ci:report:2565682045

**Comment by dantewang** [comment]
ci:report:2565686815

**Comment by dantewang** [comment]
@tinatian There are some upgrade test failures, which I believe to be caused by missing https://github.com/liferay-core-infra/liferay-portal/pull/6918/commits/81a1c067bb4a09937561424b586a55b57fae8db2. I'll try it.

**Comment by dantewang** [comment]
Applying 2 more commits at https://github.com/liferay-core-infra/liferay-portal/pull/6951

**Pull request closed without merging**
