### PR TITLE
LPS-157759 Check serviceContext.isIndexingEnabled before index the content

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by guilhermedcamacho** [comment]
@catarineaguiar please help me check the results, thanks!

**Comment by catarineaguiar** [comment]
I will analyze it on Monday

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@guilhermedcamacho sorry the delay. Regression found:

`FileEntryRemoteStagedModelDataHandlerTest`, `FileEntryStagedModelDataHandlerTest`
```
[exec] com.liferay.document.library.internal.exportimport.data.handler.test.FileEntryRemoteStagedModelDataHandlerTest > testStagedModelDataHandler FAILED
     [exec]     java.lang.AssertionError: [] expected:<2> but was:<0>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at com.liferay.exportimport.test.util.lar.BaseStagedModelDataHandlerTestCase.validateAssets(BaseStagedModelDataHandlerTestCase.java:882)
     [exec]     	at com.liferay.exportimport.test.util.lar.BaseStagedModelDataHandlerTestCase.validateImport(BaseStagedModelDataHandlerTestCase.java:1065)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-07/test-1-34/test-portal-acceptance-pullrequest(master)/2290/modules-integration-mysql57-jdk8/1/7/jenkins-console.txt.gz?authuser=0)

**Comment by guilhermedcamacho** [comment]
Thanks @catarineaguiar , I will check it.

**Comment by guilhermedcamacho** [comment]
See #1084

**Comment by guilhermedcamacho** [comment]
See #1096

**Comment by guilhermedcamacho** [comment]
See #1099

**Pull request closed without merging**
