### PR TITLE
[Method Reference Static]Lps 183845

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-183845

Apply this pattern https://github.com/liferay-core-infra/liferay-portal/pull/4488#issuecomment-1542131885

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by slnn** [comment]
Forced push to resolve conflicts about SF properties, no logic change

**Comment by slnn** [comment]
ci:test:sf

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@zhangyan0701 The SF issue seems to be unrelated, could you priority this pull? Thanks!

**Comment by zhangyan0701** [comment]
@dantewang Yes, the SF failure should be unrelated.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
