### PR TITLE
[TS] [Urgent] LPD-1721

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
@shuyangzhou could you please review this version, we believe it is important that the fix is included in the Q release.

From [previous](https://github.com/liferay-core-infra/liferay-portal/pull/6586) it differs that nulling the value is not enough. We need to remove it so that the initial value is executed when needed.

/cc @achaparro

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:report:2539596145

**Comment by marianoalvarosaiz** [comment]
Unique failures are unrelated and are currently under analysis:

- https://liferay.atlassian.net/browse/LRQA-82765
- https://liferay.atlassian.net/browse/LPD-6044

**Comment by shuyangzhou** [comment]
@marianoalvarosaiz leave out the change to CentralizedThreadLocal, this should not be provided at this layer. Each individual XYZThreadLocal could provide it as needed. Please resend

**Comment by marianoalvarosaiz** [comment]
@shuyangzhou the problem with leaving it outside the CentralizedThreadLocal is that it makes it difficult to continue with the lazy initial value. The only way to know the current value is to invoke the `get` method, but that method creates the initial value if not present.

I can only think of two alternatives:

- Option1, see https://github.com/marianoalvarosaiz/liferay-portal/pull/1149, which keeps in a ThreadLocal the information about whether the value has been initialized or not.
- Option 2, see https://github.com/marianoalvarosaiz/liferay-portal/pull/1150, which makes getThreadLocalMap and related data visible to check if there is already a value or not.

**Comment by shuyangzhou** [comment]
For the XYZThreadLocal, expose setWithSafeCloseable() from its underneath CentralizedThreadLocal.

When needs the behavior you described, in your case the LocaleThreadLocal/TimeZoneThreadLocal usages inside CompanyThreadLocal,

You can just do:
```
SafeCloseable safeCloseable = XYZThreadLocal.setWithSafeCloseable(null);

XYZThreadLocal.removeXYZ();
```
Then you can use the safeCloseable in the same way as you do now.

Isn't this enough for your case? If so, please resend in this way, otherwise please describe the issue clearly as failing tests to be tested (without any fix), and give it @tinatian .
I just can not see a reason this needs any change to CentralizedThreadLocal.

**Comment by marianoalvarosaiz** [comment]
@shuyangzhou that will not work because CentralizedThreadLocal#setWithSafeCloseable returns a SafeCloseable that updates the value of the entry:

```
public SafeCloseable setWithSafeCloseable(T value) {
	ThreadLocalMap threadLocalMap = _getThreadLocalMap();

	Entry entry = threadLocalMap.getEntry(this);

	if (entry == null) {
		threadLocalMap.putEntry(this, value);

		return () -> threadLocalMap.removeEntry(this);
	}

	Object originalValue = entry._value;

	entry._value = value;

	return () -> entry._value = originalValue;
}
```

But that only makes sense if the entry is part of the `ThreadLocalMap`. However, if we remove it is no longer part, so assigning the old value will affect the `entry._value`, but not the ThreadLocalMap since that entry is no longer part of the ThreadLocalMap (it has been removed in):

```
public void remove() {
	ThreadLocalMap threadLocalMap = _getThreadLocalMap();

	threadLocalMap.removeEntry(this);
}
```

@tinatian as Shuyang requested I'm giving this issue to you. To reproduce it you can use `com.liferay.portal.kernel.security.auth.CompanyThreadLocalTest.testUserThreadLocalsWithSetWithSafeCloseable()` that hasn't been reverted from master and it's currently failing. 

The idea is:

1. When invoking `CompanyThreadLocal.setWithSafeCloseable` and close over the returned SafeCloseable the values of `LocaleThreadLocal.setDefaultLocale` and `TimeZoneThreadLocal.setDefaultTimeZone` should return to their previous value and not the default ones.
2. When fixing it we should maintain the lazy initialization of thread locals implemented https://liferay.atlassian.net/browse/LPS-194715.

I can't find an straightforward solution for this second point because each time I invoke `CentralizedThreadLocal#get` I'm forcing the calculation of the initial value if there is no previous value. I could only think of the two options mentioned here, https://github.com/liferay-core-infra/liferay-portal/pull/6638#issuecomment-1957773625

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/11432
This means you found a bug, the CentralizedThreadLocal.setWithSafeCloseable() needs to be able to restore the captured value, even the ThreadLocal has been removed when under the SafeCloseable scope.

When fixing issues, it is very important to stay focus on the root cause. In this case, you want to rely on CentralizedThreadLocal.setWithSafeCloseable() to fulfill the behavior. On seeing it failed to do so, you need to find out why? Is that really expected, or it is a bug. The last thing to do is to just leave it alone and create a new api to do the logic you want. This kind of approach will inflate our api and leave the bug unfixed which will just surprise someone later.

@tinatian please still re-evaluate the issue from business logic point of view just to make sure nothing is weird. If the issue is what we think it is, you can use my fix to do the proposed solution at https://github.com/liferay-core-infra/liferay-portal/pull/6638#issuecomment-1962668343

**Comment by marianoalvarosaiz** [comment]
@tinatian hope this helps: https://github.com/liferay-core-infra/liferay-portal/pull/6686

Uses Shuyang fix for CentralizedThreadLocal and applies his recommendations, see https://github.com/liferay-core-infra/liferay-portal/pull/6638#issuecomment-1962668343

I've checked that it fixes the two current broken tests, CompanyThreadLocalTest and SXPBlueprintSearchResultTest

**Pull request closed without merging**
