### PR TITLE
 [Remove Spring extender usages] LPS-159499

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

Resend. refer to https://github.com/liferay-core-infra/liferay-portal/pull/1292

This PR is to remove spring extender usage in commerce-discount-service, thanks!
https://issues.liferay.com/browse/LPS-159499
Previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/1299

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @zhangyan0701 , Could you review the test results when it finishes? Thanks!

**Comment by JanisZhang** [comment]
ci:test:commerce

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
