### PR TITLE
[Disable auto-import-default-references]LPS-164201

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to disable auto-import-default-references in commerce-tax-service. Thanks!
https://issues.liferay.com/browse/LPS-164201

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @catarineaguiar, Could you please help to scan the test results? thanks!

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
Hi @catarineaguiar , re-triggered CI test, all test passed. 

cc/ @dantewang

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

@shuyangzhou @tinatian

**Pull request closed without merging**
