### PR TITLE
LPS-195966 Merge OrganizationPermission interface and impl into Util in kernel

### PR DESCRIPTION
**Pull request by julschong**
@shuyangzhou 
There are other usages in kernel. 
I tried to move them all to impl but there are lots of usages of those classes as well making the pull too big, so I decided not to move this to impl

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found. SF issue is not related

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141598

**Pull request closed without merging**
