### PR TITLE
LPD-37552 clean up removed spring jars in source-formatter

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, 
This is for ticket https://liferay.atlassian.net/browse/LPD-37552.
We are not using spring-webmvc in master, and it has been removed in https://liferay.atlassian.net/browse/LPS-151777
In the security bug ticket, it detect the usgea of webmvc in source-formatter only, and I am cleaning up the source-formatter in this PR so that we won't have this issue next time
Thanks for checking

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
This SF issue is in `./portal-kernel/src/com/liferay/portal/kernel/upgrade/recorder/UpgradeSQLRecorder.java`, which is not related to my change

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
