### PR TITLE
LPS-206195 upgrade Jackson Databind to 2.16.1

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Dante, 

This is for ticket https://liferay.atlassian.net/browse/LPS-206195
I upgrade jackson Databind to 2.16.1
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:report:2503973121

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:2505991986

**Comment by dantewang** [comment]
@jeffwu0724 If we search for `jackson-` we'll see some extra jackson dependencies which are still on older versions, like `jackson-dataformat-yaml` and `jackson-jaxrs-json-provider`. At least the 2 I mentioned are also at 2.16.1 as the latest version. Could you double check them?

**Comment by pyoo47** [comment]
ci:report:2505991986

**Comment by jeffwu0724** [comment]
Hi @dantewang 

besides com.fasterxml.jackson.core.* that are deployed in required-dependencies, we also have these com.fasterxml.jackson dependencies. 
```
com.fasterxml.jackson.core:jackson-annotations:2.16.1,\
com.fasterxml.jackson.core:jackson-core:2.16.1,\
com.fasterxml.jackson.core:jackson-databind:2.16.1,\
com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.16.1,\
com.fasterxml.jackson.dataformat:jackson-dataformat-smile:2.16.1,\
com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.16.1,\
com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.16.1,\
com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.16.1,\
com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.16.1,\
com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:2.16.1,\
com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:2.16.1,\
com.fasterxml.jackson.jaxrs:jackson-jaxrs-xml-provider:2.16.1,\
com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.16.1,\
```
I tired to also upgrade them to 2.16.1, but seems like they will have` error  : Classes found in the wrong directory: {META-INF/versions/9/module-info.class=module-info}`
My plan is, moved these jars(except com.fasterxml.jackson.core) to shared-dependencies so that we only need one -fixupmessage to hadle this error

**Comment by jeffwu0724** [comment]
Hi @dantewang,

As moving these `com.fasterxml.jackson.* jars` to shared-dependencies will be a big PR, do you think it is ok to move forward this PR (FYI, we once upgrade com.fasterxml.jackson.core.* and other com.fasterxml.jackson.* seperately at https://liferay.atlassian.net/browse/LPS-165622), and I will create a new ticket to handle other `com.fasterxml.jackson.* jars`
Thanks!

**Comment by jeffwu0724** [comment]
ci:report:2505991986

**Comment by jeffwu0724** [comment]
no unique regression found

**Comment by jeffwu0724** [comment]
no code conflict: 1/29/2024 - 11:08am

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
