### PR TITLE
LPS-176210 Remove counterDataSource | 3-15

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-176210 Remove counter data source
- LPS-176210 Remove counter session factory, it's not allowed for multiple session factories on the same data source if it's in Hibernate managed mode
- LPS-176210 Clean up, we no longer need to set configuration resources via a setter. Just keep the getter for sub class to extend and customize.
- LPS-176210 Clean up, we no longer set whether mvcc is enabled since we use only 1 session factory now
- LPS-176210 Fix CounterLocalServiceTest by loading counter-hbm.xml only; otherwise, CTSQLInterceptor will be enabled and the test will be stuck because CTSQLInterceptor waits for an OSGi service, which is not available in the processes started by the test.

### CODE REVIEW

**Comment by tinatian** [comment]
@GinsonRen Please run all daily performance test to verify no regression.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
@tinatian Performance has been tested in https://github.com/dantewang/liferay-portal/pull/2286, this pull has only cleaned up  unused methods and fixed the test, no other change. Asked @GinsonRen to take an extra look at the portal logs in those tests.

**Comment by GinsonRen** [comment]
@tinatian @dantewang I double checked the results before and rerun the blog, no new errors on portal log.

**Comment by tinatian** [comment]
ci:test:help

**Comment by tinatian** [comment]
ci:test:environments

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3918

**Pull request closed without merging**
