### PR TITLE
[Replace Non-Blocking Usage] LPS-199426 PortletFileRepositoryUtil

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace non-blocking ServiceProxyFactory with Snapshot and retain the original dummy proxy logic to prevent startup NPE. 

Note that the removal of service Bean registration in `util-spring.xml` (commit 6b29eb779cf5b47cbf982fb9598849b20500c60d) led to `PortletFileRepositoryUtil` obtaining a dummy service when retrieving portletFileRepository. 

https://liferay.atlassian.net/browse/LPS-199426

previous: https://github.com/liferay-core-infra/liferay-portal/pull/5885#issuecomment-1780005318

Thanks!

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
Hi @dantewang , should we apply this pattern to leftover usages if possible?

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by JanisZhang** [comment]
Thanks Summer! @zhangyan0701

**Comment by dantewang** [comment]
@JanisZhang After a second thought, could you check the NPE stack there? Who is using this during startup?

**Comment by JanisZhang** [comment]
@dantewang 
Hi Dante, I did some debugging on this. In short, `WorkflowMetricsPortalInstanceLifecycleListener`,  a subclass of `PortalInstanceLifecycleListener` is using PortletFileRepositoryUtil during startup. 

At first, It triggers the `_workflowMetricsIndexCreator.reindex(company)` method when registerCompany. During this process, a background task is added and triggered. Subsequently, upon receiving a message, the `BackgroundTaskStatusMessageListener` executes the `_deleteBackgroundTask` method. Inside the `BackgroundTaskLocalServiceImpl#deleteBackgroundTask` method, the `BackgroundTaskImpl#getAttachmentsFolderId` method is invoked, eventually leading to the execution of `PortletFileRepositoryUtil.fetchPortletRepository`.

Additionally, I've identified two refactorings related to this context: 16f18891c28c57a3cac4c6a50172e908ba8cd507 and b96c8345ef398b064aa538379315076a746737ea. However, I believe these changes won't affect the sequence of PortletFileRepositoryUtil being called. Thanks.

**Comment by dantewang** [comment]
@JanisZhang Could you try to postpone this by making it extending `InitialRequestPortalInstanceLifecycleListener`?

**Comment by JanisZhang** [comment]
@dantewang After having the class WorkflowMetricsPortalInstanceLifecycleListener extend InitialRequestPortalInstanceLifecycleListener, I no longer encountered a NullPointerException during startup, as the reindex method now returns NULL.

**Comment by dantewang** [comment]
@JanisZhang Could you resend the PR with that change, so that we don't need to add a dummy proxy for the Snapshot? Let's run tests to see if it causes any issue.

**Pull request closed without merging**
