### PR TITLE
LPS-145579 Remove LocalizationUtil usages in modules part 3

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by catarineaguiar** [comment]
@julschong code conflicts, can you resolve, please? Thanks

**Comment by julschong** [comment]
@catarineaguiar rebased

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123980

**Pull request closed without merging**
