### PR TITLE
[LPS-167246 MessageBus] LPS-194337 Decouple MessageListener management from Destination

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
This PR contains LPS-192572. Sent here for CI tests. There will be 1 more PR to finish the whole task.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:backend-hypersonic

**Comment by Kvale1733** [comment]
@dantewang Regression found.

Steps to reproduce:
1. Import the following 7.4.13 db dump: https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.4.13/data-archive/data-archive-portal-mysql.zip
2. Run the upgrade tool to upgrade the database
3. Startup

Results: There are unsatisfied references
```
[beanshell] 2023-08-24 12:25:28.460 INFO  [main][DependencyManagerSyncUtil:36] Available checkers: [Declarative Service Unsatisfied Component Checker, Missing Component Scanner, Spring Extender Unavailable Component Checker, Declarative Service Soft Circular Dependency Checker]
[beanshell] 2023-08-24 12:25:28.461 INFO  [main][DependencyManagerSyncUtil:62] Running "Declarative Service Unsatisfied Component Checker". You can run this by itself with command "ds:unsatisfied" in gogo shell.
[beanshell] 2023-08-24 12:25:44.579 WARN  [main][DependencyManagerSyncUtil:73] Declarative Service Unsatisfied Component Checker check result: 
[beanshell] Bundle {id: 94, name: com.liferay.portal.monitoring, version: 9.0.25}
[beanshell] 	Declarative Service {id: 41, name: com.liferay.portal.monitoring.internal.jmx.MonitoringConfigurationManager, unsatisfied references: 
[beanshell] 		{name: _monitoringControl, target: null}
[beanshell] 	}
```
[Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-38/test-portal-acceptance-pullrequest(master)/8726/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
@Kvale1733 Thanks!

**Comment by dantewang** [comment]
@Kvale1733 We was not able to reproduce this.

My Steps:

- Import the database SQL and copy over the data folder
- Run upgrade client
  - on my side, upgrade process results in "failure", and automatically enters gogo shell, but I only saw some exceptions related to Elasticsearch
- Stop upgrade gogo shell, and start portal
- Run `system:check` in gogo shell

I didn't see any unsatisfied dependency.

**Comment by dantewang** [comment]
cc @zhangyan0701

**Comment by dantewang** [comment]
I re-applied this change on top of Tina's change and sent at https://github.com/liferay-core-infra/liferay-portal/pull/5402, please let me know if the error still occurs.

**Pull request closed without merging**
