### PR TITLE
LPS-148461 Move xz.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
Hey, @koor4356 Can you help me check the test results when they are ready? Thx

**Comment by koor4356** [comment]
Okay, thanks!

**Comment by koor4356** [comment]
@rafaprax 
This looks good, thanks!

**Comment by rafaprax** [comment]
Hey @tinatian, It is ready for review. Thx

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
@rafaprax packages `org.apache.commons.compress.compressors.lzma, org.apache.commons.compress.compressors.xz, org.apache.commons.compress.archivers.sevenz` from commons-compress.jar still uses org.tukaani.xz. Are you sure this is safe to relocate xz.jar?

I think if we use commons-compress to handle certain types of files will need to use xz.jar

**Comment by rafaprax** [comment]
I'm gonna check this. Thx for bring it up @shuyangzhou

**Comment by tinatian** [comment]
@shuyangzhou I did not check the internal dependencies as the tests passed, I thought it is covered by tests. If not, is it possible we add some? It seems we have a bunch of jars like this.

Tina

**Comment by shuyangzhou** [comment]
@tinatian this has to be related to certain types of compressed file processing. We don't have a very thorough coverage on all kinds of compression types. I have been checking at the import-export packages level in addition to the tests coverage to be safe. If the moved out jar does not have packages reference from core, and tests are passing, it should be almost certain to be safe. Only tests passing may not be good enough in some cases.

**Pull request closed without merging**
