### PR TITLE
[Method References 2] LPS-175789 Convert method reference to ServiceTrackerList in class ClusterExecutorImpl

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3542

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:clustering

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(5/11 10:11)

**Comment by W2jx** [comment]
no conflicts(5/12 10:36)

**Comment by W2jx** [comment]
no conflicts(5/15 9:43)

**Comment by dantewang** [comment]
See https://github.com/W2jx/liferay-portal/pull/178, please resend,

**Pull request closed without merging**
