### PR TITLE
LPD-2612 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://liferay.atlassian.net/browse/LPD-2612

### CODE REVIEW

**Comment by victorhcunha** [comment]
Here are the new results for Document Library test case with this PR:

Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
Baseline | 0b71fc5 | 7897 | - | 294 | 7,7,8 | 86,86,87
PR | - | 7996 | 1.253640623 | 327 | 8,8,8 | 89,89,89

More details in the [spreadsheet](https://docs.google.com/spreadsheets/d/1rJDtJH0iBDdhHNA8jdhZNpVrNhRrWiwBs-FICgZuwo4/edit#gid=0)

cc @dantewang  @shuyangzhou

**Comment by brunofalc** [comment]
Hey @dantewang do we have updates about this PR?

**Comment by dantewang** [comment]
@brunofalc @marcosapmf  The performance test result looks good. I think this PR can move on.

cc @shuyangzhou

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by liferay-search** [comment]
@tinatian it should be ready to go based on Dante's review https://github.com/liferay-core-infra/liferay-portal/pull/7122#issuecomment-2164206264

**Comment by brunofalc** [comment]
Hey @tinatian, it looks it's fine after [Dante's comment](https://github.com/liferay-core-infra/liferay-portal/pull/7122#issuecomment-2164206264)

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
