### PR TITLE
LPD-25981 no error message show in gogo shell with wrong captcha

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

Resend https://github.com/liferay-core-infra/liferay-portal/pull/7126.
The previous PR has the issue that, after I enter the wrong captcha, it will extend the executecommand to the URL. In this case, if I enter a correct catptcha again, it will run the executecommand twice. The first time it will pass the captcha check and will show the successful message, but the second time, it will run the captcha check again with another actionRequest, which do not contain the captchaText, and will throw error. This is why we will see both successful message and error message at the same time.
As `getCurrentURL(HttpServletRequest)` is not always giving us the original gogo shell url, I changed to use `<portlet:renderURL var="redirect" />` to generte a plain gogoshell url

Thanks,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:core-functional

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:core-functional

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
SF failture is not realted, and it has been fix by https://liferay.slack.com/archives/C1SJ64S9X/p1718777498330239

**Comment by jeffwu0724** [comment]
ci:report:20858446

**Comment by jeffwu0724** [comment]
the relevant test failure is not related
functional test:
https://testray.liferay.com/#/project/34754/routines/34756/build/20858446/case-result/20859745/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/20858446/case-result/20859801/history -- not related, also reproduce on a clean master locally
https://testray.liferay.com/#/project/34754/routines/34756/build/20858446/case-result/20860145/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/20858446/case-result/20860217/history -- flaky, passed locally
https://testray.liferay.com/#/project/34754/routines/34756/build/20858446/case-result/20860495/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/20858446/case-result/20860515/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/20858446/case-result/20860583/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/20858446/case-result/20860587/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/20858446/case-result/20860627/history -- not unique


no unique regression found

**Comment by jeffwu0724** [comment]
dicussed with Victor, and the current behavior after the fix in the gogoshell is expected.
[The tests from "Bundle Blacklist" ](https://testray.liferay.com/#/project/34754/routines/34756/build/20858446?filter=%7B%22componentToCaseResult%2Fid%22%3A%5B178423%5D%7D&filterSchema=buildResults&page=1) are passing, many of these use gogo shell UI
Also checked locally with these properties set up in portal-ext.proerpties to disable captcha
```
captcha.enforce.disabled=true
configuration.override.com.liferay.captcha.configuration.CaptchaConfiguration_maxChallenges=I"-1"
```
and gogo shell works as expected

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/151577

**Pull request closed without merging**
