### PR TITLE
[Method References 2] LPS-171023 Replace the trackers in classes IndexResourceImpl and WorkflowMetricsReindexBackgroundTaskExecutor with WorkflowMetricsReindexerRegistry

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:workflow-metrics

**Comment by catarineaguiar** [comment]
ci:test:workflow-metrics

**Comment by Kvale1733** [comment]
@W2jx No regrssions found.

**Comment by W2jx** [comment]
no conflicts(4/19 8:03)

**Comment by W2jx** [comment]
no conflicts(4/20 7:56)

**Comment by W2jx** [comment]
no conflicts(4/21 8:22)

**Comment by W2jx** [comment]
no conflicts(4/24 11:16)

**Comment by W2jx** [comment]
no conflicts(4/25 8:02)

**Comment by W2jx** [comment]
no conflicts(4/26 7:48)

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
