### PR TITLE
LPD-26430 debug

### PR DESCRIPTION
**Pull request by kevhlee**

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:37065469

**Comment by kevhlee** [comment]
Hi @tinatian, using this PR, I verified that CI has Liferay environment variables that are set prior to the `ConfigurationImplTest#testLoadEmptyProperties` test and cause it to fail.

To explain what I've done with this PR, I printed out the following when the test fails:

- The system environment variables (i.e. `System.getenv()`) that start with `LIFERAY_`.
- The output properties from `ConfigurationImpl.getProperties()`.

This is what the result looks (after some formatting):

```log
===== Properties ==== 
docker_network_name: cloud-10-0-19-39 
docker_sock_volume: /mnt/docker-run-volume 
docker_enabled: true 
releases_mirrors: http://mirrors.lax.liferay.com/releases.liferay.com 
docker_image: liferay/liferay-ci:jenkins-slave_1.0.49

==== System env ====
LIFERAY_DOCKER_NETWORK_NAME: cloud-10-0-19-39
LIFERAY_DOCKER_SOCK_VOLUME: /mnt/docker-run-volume
LIFERAY_DOCKER_ENABLED: true
LIFERAY_RELEASES_MIRRORS: http://mirrors.lax.liferay.com/releases.liferay.com
LIFERAY_DOCKER_IMAGE: liferay/liferay-ci:jenkins-slave_1.0.49
```

Notice that the count between `Properties` and `System env` is the same and has corresponding names.

**Pull request closed without merging**
