### PR TITLE
LPS-144001 Remove jfreechats and jcommon

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@koor4356 can you check these results?

**Comment by vicnate5** [comment]
@koor4356 I am re-running since LPS-144012 blocked most of the functional results. Please check when we get the new results.

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@rafaprax Can you rebase this branch?

**Comment by rafaprax** [comment]
@vicnate5 rebased

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by guilhermedcamacho** [comment]
Fixed rebase error and resent on #83

Waiting results of ci:test to close this PR

**Comment by rafaprax** [comment]
ci:stop

**Pull request closed without merging**
