### PR TITLE
[Spring Beans] LPS-200453 Make PortletToolbar an util

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(11/1 9:03)

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(11/2 8:14)

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:commerce

Run an extra test to verify.

**Comment by Kvale1733** [comment]
No regressions in Commerce suite.

**Comment by W2jx** [comment]
no conflicts(11/3 8:52)

**Comment by W2jx** [comment]
no conflicts(11/3 9:19)

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
ci:stop

**Comment by shuyangzhou** [comment]
@W2jx @dantewang this is not right, first of all "_IW" is not hand coded, it is generated, see https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/tools/instance_wrappers.xml

Also in this case, there is no reason for IW usage. To keep things simple, keep PortletToolbar.getPortletTitleMenus() non-static. Just remove PortletToolbar from spring, and create a static INSTANCE field inside PortletToolbar to replace existing usages.

**Pull request closed without merging**
