### PR TITLE
[Bug Fix]LPS-39804

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
@koor4356 Please help me scan the test results.

Thanks.
Tina.

**Comment by koor4356** [comment]
Okay, thanks!

**Comment by koor4356** [comment]
@tinatian 
This looks good. No unique failure.

**Comment by tinatian** [comment]
Hi @koor4356,
As Victor mentioned that it failed on manual test at https://github.com/liferay-core-infra/liferay-portal/pull/167#issuecomment-1006229483, could you please also confirm it locally?

Thanks.
Tina.

**Comment by koor4356** [comment]
@tinatian 
I want more information on to test this locally. Where do we set this "com.liferay.portal.cluster to debug"? Do we set this on all 3 portal servers during runtime? What is the expected behavior/change after setting the properties?

**Comment by tinatian** [comment]
@koor4356 It will be at Control Panel > Server Administration, I believe you can find the detailed path in the function test logic Victor added. During runtime, you only change the log level on slave node, and the expected result is you can see the same change in other nodes.

**Comment by marianoalvarosaiz** [comment]
@tinatian do we have any updates about this PR?

**Comment by shuyangzhou** [comment]
@koor4356 what's the status on the testing?

**Comment by koor4356** [comment]
Sorry guys, I missed Tina's comment so I have not worked on it. I will try to get this today. Thanks!

**Comment by shuyangzhou** [comment]
No worries, let me know how it goes, thanks @koor4356 !

**Comment by koor4356** [comment]
ci:test:bundle

**Comment by koor4356** [comment]
ci:test:bundle

**Comment by koor4356** [comment]
@tinatian @marianoalvarosaiz  @vicnate5 
The link to the ci bundle above is not accessible and there are conflicts with the branch. Can someone fix it so I can be able to fetch this PR?

**Comment by vicnate5** [comment]
@marianoalvarosaiz Would you able to do the rebase and resend?

@koor4356 No need to test manually, the needed coverage is all automated, just need to re-run the clustering test suite and confirm the new tests add in the commits here are passing.

**Comment by marianoalvarosaiz** [comment]
@vicnate5, @koor4356 see https://github.com/liferay-core-infra/liferay-portal/pull/235

**Pull request closed without merging**
