### PR TITLE
[Components with more than 1 service] LPS-195490 Refactor EditServerMVCActionCommand component

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-195490](https://liferay.atlassian.net/browse/LPS-195490)

Previous Pull: https://github.com/rafaprax/liferay-portal/pull/1322

Applied in the EditServerMVCActionCommand class the pattern that was applied in this [commit](https://github.com/liferay-core-infra/liferay-portal/pull/4718/commits/4fded4a90a29f6e7b7aab446185156bab565b7b5) to avoid the implementation of IdentifiableOSGiService

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found

**Review by rafaprax — APPROVED** [review]

**Comment by dantewang** [comment]
@RenanUmV @rafaprax AFAIK, `@Reference` on static field won't work. That's why we had a lot of instance method references setting static fields as a workaround in the past (which is also forbidden now).

Please try to test it manually in a cluster, or debug it to see if the fields are correctly injected. If not, maybe we need to manually get the service using bundle context or turn the fields into snapshots.

Please double check and resend, thanks.

**Pull request closed without merging**
