### PR TITLE
LPS-143420

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@julschong Unique unit test failures on this branch:
[com.liferay.saml.opensaml.integration.internal.resolver.DefaultAttributeResolverTest](https://testray.liferay.com/home/-/testray/case_results/1593688377)
[com.liferay.saml.opensaml.integration.internal.resolver.DefaultNameIdResolverTest](https://testray.liferay.com/home/-/testray/case_results/1593688386)
[com.liferay.dynamic.data.mapping.validator.internal.DDMFormValidatorTest](https://testray.liferay.com/home/-/testray/case_results/1593688645)
I was able to reproduce the failures locally on my machine.|

No other regressions found.

**Pull request closed without merging**
