### PR TITLE
[Remove Stream/Optional usage] LPS-176389 dynamic-data-mapping-form-builder

### PR DESCRIPTION
**Pull request by JanisZhang**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3805
https://issues.liferay.com/browse/LPS-176389

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
ci:test:forms

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by JanisZhang** [comment]
ci:forward:force

**Comment by JanisZhang** [comment]
forward this as it's approved and passed QA review. 
cc @dantewang @tinatian @shuyangzhou

**Pull request closed without merging**
