### PR TITLE
LPP-46001 > LPS-158806 When sending an invalid redirect query parameter during password reset, the password is included in the response

### PR DESCRIPTION
**Pull request by julschong**
resubmit from #1452

@shuyangzhou Hi Shuyang,
Thanks for the reminder about this.
This pull removed 2 commits that caused issue before: 

> 
> [LPS-158806 Change PortalImpl to not use deprecated ActionRequest methods](https://github.com/brianchandotcom/liferay-portal/commit/0bd57ab9a0d060a81200e1f338248aa303bec0b9)
> 
> [LPS-158806 Remove deprecated usage in unit test](https://github.com/brianchandotcom/liferay-portal/commit/ffc2c6c8501a398d3258fff497b2fdda411414eb)

I added the changes by hand since these 2 commits were removed from: https://github.com/brianchandotcom/liferay-portal/compare/0c0d01a9b4...f8729bad69

Thanks!

cc. @TaiPhamLR

### CODE REVIEW

**Comment by julschong** [comment]
@shuyangzhou Hi Shuyang,
Thanks for the reminder about this.
This pull removed 2 commits that caused issue before: 

> 
> [LPS-158806 Change PortalImpl to not use deprecated ActionRequest methods](https://github.com/brianchandotcom/liferay-portal/commit/0bd57ab9a0d060a81200e1f338248aa303bec0b9)
> 
> [LPS-158806 Remove deprecated usage in unit test](https://github.com/brianchandotcom/liferay-portal/commit/ffc2c6c8501a398d3258fff497b2fdda411414eb)

I added the changes by hand since these 2 commits were removed from: https://github.com/brianchandotcom/liferay-portal/compare/0c0d01a9b4...f8729bad69

Thanks!

cc. @TaiPhamLR

**Comment by catarineaguiar** [comment]
@julschong semver error:

```
[exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-impl/portal-impl.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.impl/52.0.0/3d4302e5a87d9685a9f069792b04ad05faa558ee/com.liferay.portal.impl-52.0.0.jar
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-25/test-portal-acceptance-pullrequest(master)/4401/modules-compile-jdk8/0/8/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine, 
I rebased and ran ant all again. no update in semver in portal-impl. will test ci again

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122876

**Pull request closed without merging**
