### PR TITLE
LPS-178022 Cleanup CustomFilter for optional removal

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@julschong As we talked, please resend.

Thanks.
Tina

**Comment by julschong** [comment]
see https://github.com/liferay-core-infra/liferay-portal/pull/4355

**Pull request closed without merging**
