### PR TITLE
[TS] LPS-199442

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found. The bug is not reproducible.

Let's wait stable results.

**Comment by catarineaguiar** [comment]
failure on stable is not related

**Comment by yuhai** [comment]
@marianoalvarosaiz, the fix is good to me. But we need to do some SF for the test class. Please see https://github.com/marianoalvarosaiz/liferay-portal/pull/1037

Please merge my commits to yours and then adjust the commits. In addition, could you please also add one test method `testCleanUpOrphanedPortletPreferencesWithProperedPortletPreferences`? Just like `testCleanUpLayoutRevisionPortletPreferencesWithProperedPortletPreferences` to Assert.assertNotNull(PortletPreferences).

I am going to close the pr and please resend it.

Thanks,
Hai

**Pull request closed without merging**
