### PR TITLE
[PowerMock] LPS-151823 modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian From https://github.com/liferay-core-infra/liferay-portal/pull/695

### CODE REVIEW

**Comment by catarineaguiar** [comment]
Hi @dantewang @tinatian, sorry the delay. No regressions were found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116938

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
