### PR TITLE
[Method References 2] LPS-171886 Convert method reference to ServiceTrackerMap in class MonitoringMessageListener(module portal-monitoring)

### PR DESCRIPTION
**Pull request by W2jx**
I have removed the dependency on Destination.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/2875

### CODE REVIEW

**Comment by Kvale1733** [comment]
@W2jx No regressions.

**Comment by W2jx** [comment]
no conflicts(1/11 16:10)

**Comment by W2jx** [comment]
no conflicts(1/16 9:14)

**Comment by W2jx** [comment]
no conflicts(1/17 17:00)

**Pull request closed without merging**
