### PR TITLE
[OrderByComparator] LPD-26679 Clean up and Apply Singleton in dynamic-data-mapping module part II

### PR DESCRIPTION
**Pull request by MrJohn1911**
@dantewang this pull already passed in ci [here](https://github.com/liferay-core-infra/liferay-portal/pull/7039), my last change was to just modify the name of the "_ASCENDING" and "_DESCENDING" constants to "_INSTANCE_ASCENDING" and "_INSTANCE_DESCENDING". Also I put break changes in the commits of SF and in the ones that I transform the class in a singleton.

CC: @titokenzo

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
Reevaluating!
CC: @titokenzo

**Pull request closed without merging**
