### PR TITLE
[TS] LPD-30790 Increase priority to forceable AuthVerifiers

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
fyi @tinatian 

/cc @achaparro, @stian-sigvartsen

**Comment by tinatian** [comment]
@JerryAdrianoo Please verify startup. Thanks!

**Comment by JerryAdrianoo** [comment]
Hi @tinatian and @marianoalvarosaiz  for more details, see: [results](https://docs.google.com/spreadsheets/d/1jIJF1InyWClm418VUO56zzUl0zCC-hWKwlV4KZAI21o/edit?usp=sharing) 

Branch| Startup Time (ms)(without  default HSQL data)  Cold start | Percent of Average Startup Time Cold Start | Startup Time (ms)(without  default HSQL data) Hot start | Average Startup Time (ms)(without default HSQL data)  Hot start | Percent of Average Startup Time Hot Start | Shutdown Time (ms)(without default HSQL data)   Cold start | Shutdown Time (ms)(without default HSQL data)  Hot start | Average Shutdown Time (ms)(without default HSQL data)  Hot start
-- | -- | -- | -- | -- | -- | -- | -- | --
Before LPD-30790 | **48,750** | | 18,044 | | | **2,540** | 2,742
|  | | | 17,073 | | | | 1,958
|  | | | 16,076 | | | | 1,999
 | | | | 16,304 | | | | 1,954
 | | | | 16,293|**16,557** | | | 2,008 | **1,988**
-- | -- | -- | -- | -- | -- | -- | --
After LPD-30790 | **49,149** | | 17,496 | | | **2,628** | 2,000
|  | | | 18,051 | | | | 2,076
|  | | | 16,392 | | | | 2,057
|  | | | 16,058 | | | | 1,951
| | |  0.82% | 16,760 |**16.883** |  **1.97%** | | 1,962 | **2,006**

The variation in the startup is within the expected normality. Other than that, the other metrics appear normal and are unaffected by these changes.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/155117

**Pull request closed without merging**
