### PR TITLE
Lps 161569 break circular dependency between CPDefinitionOptionValueRelLocalService and CPDefinitionOptionRelLocalService

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-161569

Hi @tinatian @dantewang

This pull breaks the circular dependency between CPDefinitionOptionValueRelLocalService and CPDefinitionOptionRelLocalService by using the persistence class directly.

Lily

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701

Could you help to scan test results when they are finished?

Thanks
Lily

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by slnn** [comment]
Hi @dantewang

Since the change for disabling auto import ([LPS-161869](https://issues.liferay.com/browse/LPS-161869)) has merged into master, I rebase this branch with the master and forced push on this pull.

Lily

**Comment by slnn** [comment]
With the forced push change, the ci tests has been ran in:https://github.com/slnn/liferay-portal/pull/630

**Comment by tinatian** [comment]
@slnn Please remove hasCPDefinitionRequiredCPDefinitionOptionRels as no one is using it.

Tina

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:commerce

**Comment by slnn** [comment]
Hi @tinatian 

I have removed the unused method hasCPDefinitionRequiredCPDefinitionOptionRels and forced push to this pull.

Lily

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when finished?

Thanks
Lily

**Comment by tinatian** [comment]
@slnn Code looks good to me, wait for QA to scan test results.

Tina

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by slnn** [comment]
No need this one, the change has been done in https://github.com/liferay-core-infra/liferay-portal/pull/1621

**Pull request closed without merging**
