### PR TITLE
[Components with more than 1 service] LPS-176900 Refactor DTOConverter components with more than 1 service type from headless-commerce-admin-account-impl module

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:commerce

**Comment by daiazius** [comment]
ci:stop

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
no regressions found.

**Pull request closed without merging**
