### PR TITLE
[Components with more than 1 service] LPS-183006, LPS-183634 Refactor BulkSelectionFactory components

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-183006](https://issues.liferay.com/browse/LPS-183006),
[LPS-183634](https://issues.liferay.com/browse/LPS-183634)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:dl-store

**Comment by catarineaguiar** [comment]
ci:test:document

**Comment by catarineaguiar** [comment]
no regressions found.

**Pull request closed without merging**
