### PR TITLE
[Bug Fix] LPS-158702 Fix test failure caused by SF

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-158702 After the commit(a0a34dd649657fc3ecaae547aaf256e5bc4e2964), need to reset _mockHttpServletResponse.
- LPS-158702 SF, change field to local variable so that there's no need to reset
- LPS-158702 SF, rename

### CODE REVIEW

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results when tests finish? Thanks!

**Comment by dantewang** [comment]
@zhangyan0701 Actually this should only affect `ServletResponseUtilContentLengthTest` -- so as long as unit-jdk8 passes it's good.

**Comment by zhangyan0701** [comment]
Unit test ServletResponseUtilContentLengthTest passed here:
https://testray.liferay.com/home/-/testray/case_results/1932763876

No other issues found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
