### PR TITLE
[Components with more than 1 service] LPS-176579 Refactor DTO Converter components with more than 1 service type from DXPEntityDTOConverterImpl

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud-acceptance

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud

**Comment by Kvale1733** [comment]
ci:test:analytics-cloud

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Comment by MrJohn1911** [comment]
Hi @tinatian, can you review this? Thanks.

**Pull request closed without merging**
