### PR TITLE
[Components with more than 1 service] LPS-175891, LPS-176008, LPS-176076

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:object

**Comment by daiazius** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
@daiazius No regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132524

**Pull request closed without merging**
