### PR TITLE
LPS-148669 Remove petra-mail

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from #1382

### CODE REVIEW

**Comment by tinatian** [comment]
@julschong Please rebase, also what did you change compared to the last pull? 

Tina

**Comment by julschong** [comment]
@tinatian I added this commit [LPS-148669 Remove petra-mail from IDE files](https://github.com/liferay-core-infra/liferay-portal/pull/1384/commits/3e458807320f35de5f30c2fca069a6f0a84d997a) from the last pull

**Comment by tinatian** [comment]
@julschong Code looks good to me, wait for QA to scan test result.
@catarineaguiar Please help me scan test results.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
@julschong @tinatian no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121996

**Pull request closed without merging**
