### PR TITLE
[Remove unused references]LPS-165617 Remove unused reference field _portal from GogoShellPortlet

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-16561

/cc @tinatian @dantewang 

ci relevant tests have been running and passed in this https://github.com/slnn/liferay-portal/pull/645

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Comment by dantewang** [comment]
@slnn Please update your commit message to show that whether the usage was used before but not any more after some previous change, or was there from the beginning of the class, or was added without any reason... Basically, show why you think this can be safely removed.

**Comment by slnn** [comment]
> @slnn Please update your commit message to show that whether the usage was used before but not any more after some previous change, or was there from the beginning of the class, or was added without any reason... Basically, show why you think this can be safely removed.

Done and force pushed

**Comment by dantewang** [comment]
ci:forward

**Comment by dantewang** [comment]
cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:forward

**Comment by dantewang** [comment]
ci:reevaluate:1277401_5402

**Comment by dantewang** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/124768

cc @shuyangzhou @tinatian

**Pull request closed without merging**
