### PR TITLE
LPS-183716 Make ServletContextUtil non-component

### PR DESCRIPTION
**Pull request by JanisZhang**

### CODE REVIEW

**Comment by dantewang** [comment]
@JanisZhang Any context? Have all other changes been already merged?

**Comment by JanisZhang** [comment]
Hi @dantewang, this is a follow-up of https://github.com/brianchandotcom/liferay-portal/pull/134458.

In this pr, I removed an unused class and related usages (regarding https://github.com/liferay-core-infra/liferay-portal/pull/4396#issuecomment-1533419342), including method reference usage in ServletContextUtil. 

After removing reference usage, this class can be a real util.  thanks!

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
