### PR TITLE
[Method References 2] LPS-176946 Convert method reference to ServiceTrackerList in class OAuth2JSONWSAuthVerifier and SAPEntryScopeDescriptorFinderRegistrator

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3907

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:oauth2

**Comment by Kvale1733** [comment]
@W2jx Regressions found.

1) com.liferay.oauth2.provider.client.test.JsonWebServiceTest
```
com.liferay.oauth2.provider.client.test.JsonWebServiceTest > test FAILED
     [exec]     org.junit.ComparisonFailure: expected:<[testcompany]> but was:<[]>
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:117)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-40/test-portal-acceptance-pullrequest(master)/2146/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

2) Cannot get portal version from SAP entry

Steps to reproduce:
1. Go to Control Panel > Server Access Policy
2. Click to add  new policy 
3. Add name "OAUTH2_read.portalversion" and title "read Portal version"
4. Add Server Class "com.liferay.portal.kernel.service.PortalService" and Method Name "getVersion"
5. Check Enabled and Save
7. Go to Control Panel > OAuth 2 Administration 
8. Click add button
9. Add "OAuth Application" as Name
10. Uncheck Authorization Code checkbox and Save
11. Save client ID and client secret for later use
12. Go back to OAuth2 Administration
13. Click ellipses on OAuth Application and click Edit
14. Go to Scopes tab
15. Under Portal Services check Read Portal Version and Save
16. Get access token with the following curl and save it. Substitute your key and id from step 11
```
curl -X POST -d 'client_id=id-f99e72a2-be8a-24cb-c162-23e9bcf7ed' -d 'client_secret=secret-2cd6253d-7382-a3e8-1ea3-4afaeb5fa23' -d 'grant_type=client_credentials' http://localhost:8080/o/oauth2/token
```
17 Execute the following curl to get the portal version. Substitute in access token
```
curl -X POST -H 'Authorization: Bearer [your access token here]' http://localhost:8080/api/jsonws/portal/get-version

```

Expected Results: The curl returns 7.4.13
Actual Results: 
```
{"exception":"Access denied to com.liferay.portal.kernel.service.PortalService#getVersion","throwable":"java.lang.SecurityException: Access denied to com.liferay.portal.kernel.service.PortalService#getVersion","error":{"message":"Access denied to com.liferay.portal.kernel.service.PortalService#getVersion","type":"java.lang.SecurityException"}}
```
[Log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-38/test-portal-acceptance-pullrequest(master)/7582/functional-tomcat90-mysql57-jdk8/1/12/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:oauth2

**Comment by W2jx** [comment]
no conflicts(5/12 10:36)

**Comment by W2jx** [comment]
no conflicts(5/15 9:43)

**Comment by W2jx** [comment]
no conflicts(5/17 8:18)

**Comment by W2jx** [comment]
no conflicts(5/18 9:50)

**Comment by W2jx** [comment]
no conflicts(5/22 8:55)

**Comment by W2jx** [comment]
no conflicts(5/23 8:20)

**Comment by W2jx** [comment]
no conflicts(5/24 13:44)

**Comment by W2jx** [comment]
no conflicts(5/25 10:06)

**Comment by W2jx** [comment]
no conflicts(5/26 15:09)

**Comment by W2jx** [comment]
no conflicts(5/29 10:30)

**Comment by W2jx** [comment]
no conflicts(5/31 9:42)

**Comment by W2jx** [comment]
no conflicts(6/1 9:06)

**Comment by W2jx** [comment]
no conflicts(6/2 8:25)

**Comment by W2jx** [comment]
no conflicts(6/5 7:43)

**Comment by tinatian** [comment]
@W2jx Please merge the ScopeFinder service tracker into one. Two usages are in different classes of same bundle, you should provide a service register for it to use it in two places.

Thanks.
Tina.

**Pull request closed without merging**
