### PR TITLE
LPS-173369 Remove Optional from PortletSharedSearchResponse.getParameter method in portal-search-api

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:search

**Comment by vicnate5** [comment]
ci:test:search

**Comment by vicnate5** [comment]
Re-running search suite since upstream issue caused mass failures.

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
