### PR TITLE
[Remove Stream/Optional usage] LPS-170484 document-library

### PR DESCRIPTION
**Pull request by JanisZhang**
This is a follow-up pull to clean left-over optional usages in module  `document-library-api`. 
I have verified that these **deprecated** methods have no usage, so I removed them.
Thanks!

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:help

**Comment by JanisZhang** [comment]
ci:test:document

**Comment by JanisZhang** [comment]
ci:test:document

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
