### PR TITLE
[Static references] LPS-181778 Remove static references in module adaptive-media, asset-taglib

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:media

**Comment by Kvale1733** [comment]
@GabrielHenriquedev Regression found

Steps to reproduce:
1. Go to Control Panel > Adaptive Media
2. Click the plus button
3. Add name "Low Resolution" Set max width to 320 and max height to 480
4. Click Save
5. Go to Content and Data > Documents and Media
6. Upload Document_1.png and Document_2.png (found in portal-web/test/functional/com/liferay/portalweb/dependencies)
7. Go back to Control Panel > Adaptive Media
8. Click on the ellipses for Low Resolution entry and click Adapt Remaining

Expected Results: Status is successful for Low Resolution under Adapted Images
Actual Results: "Error: 5 images failed to process." appears and the following error appears in console
```
[beanshell] 2023-04-20 20:09:21.731 ERROR [liferay/background_task-4][BackgroundTaskMessageListener:167] Unable to execute background task
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.adaptive.media.web.internal.background.task.OptimizeImagesStatusMessageSenderUtil.sendStatusMessage(OptimizeImagesStatusMessageSenderUtil.java:32) ~[?:?]
[beanshell] 	at com.liferay.adaptive.media.web.internal.background.task.OptimizeImagesSingleConfigurationBackgroundTaskExecutor.optimizeImages(OptimizeImagesSingleConfigurationBackgroundTaskExecutor.java:36) ~[?:?]
[beanshell] 	at com.liferay.adaptive.media.web.internal.background.task.BaseOptimizeImagesBackgroundTaskExecutor.execute(BaseOptimizeImagesBackgroundTaskExecutor.java:55) ~[?:?]
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-40/test-portal-acceptance-pullrequest(master)/1744/functional-tomcat90-mysql57-jdk8/5/4/jenkins-console.txt.gz?authuser=0)

**Comment by GabrielHenriquedev** [comment]
ci:test:sf

**Comment by GabrielHenriquedev** [comment]
ci:test:lima

**Comment by zhangyan0701** [comment]
ci:test:lima

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
