### PR TITLE
LPD-20723 Clay link is translating asset titles/names by default in vertical card

### PR DESCRIPTION
**Pull request by Mikellorza**
bug: https://liferay.atlassian.net/browse/LPD-20723

Description
----------
Add isTranslating method in order to decide if we want translate clay card content or not. For the moment, it is only implemented for the title as we have for the vertical card.

### CODE REVIEW

**Comment by dantewang** [comment]
Hi @Mikellorza, this seems to be a front end change. Do you want to get performance testing verification?

**Comment by Mikellorza** [comment]
Hi @dantewang ,

IMHO that performance testing verification does not needed here, because by default is like it was, and, when translate is false we are not translating the title, so, the cost is lower. 

Thanks

**Comment by dantewang** [comment]
@Mikellorza In this regarding, I think Front-end Infra team should be reviewing this one, since it's code in their component. Could you forward the PR?

cc @tinatian @brunofalc

**Comment by Mikellorza** [comment]
@dantewang sorry for the confusion , see : https://github.com/liferay-frontend/liferay-portal/pull/4075

**Comment by Mikellorza** [comment]
ci:close

**Pull request closed without merging**
