### PR TITLE
[Fix test] LRQA-73259

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian https://issues.liferay.com/browse/LRQA-73259

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@tinatian @vicnate5

**Comment by vicnate5** [comment]
Failures here are unrelated. Fixed test passed https://testray.liferay.com/home/-/testray/case_results/1612136400

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Pull request closed without merging**
