### PR TITLE
[Remove Blocking usages]LPS-193174 PortletResourcePermissionFactory and ModelResourcePermissionFactory

### PR DESCRIPTION
**Pull request by haydenzheng314**
Resend, use ModelResourcePermissionRegistryUtil instead of Snapshot in portal-impl
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/6054
Ticket: https://liferay.atlassian.net/browse/LPS-193174
Thanks.

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by LisztLiszt** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@LisztLiszt No regressions found.

**Comment by dantewang** [comment]
@LisztLiszt Conflicts, please rebase.

**Comment by LisztLiszt** [comment]
@dantewang Rebase to fix conflict in DLTrashServiceImpl

**Comment by dantewang** [comment]
@LisztLiszt As we talked, please resend.

**Pull request closed without merging**
