### PR TITLE
LPS-171867 Remove leftovers "immediate = true" from vulcan

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-171867

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:headless

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
@rafaprax possible regression:

```
     [exec] com.liferay.change.tracking.internal.conflict.test.CTColumnResolutionMaxTest > testUnresolvedModificationConflictMax FAILED
     [exec]     java.lang.AssertionError: {} expected:<1> but was:<0>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at com.liferay.change.tracking.internal.conflict.test.CTColumnResolutionMaxTest.testUnresolvedModificationConflictMax(CTColumnResolutionMaxTest.java:152)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-28/test-portal-acceptance-pullrequest(master)/5659/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3286

**Pull request closed without merging**
