### PR TITLE
LPS-175778 Inline trash service-xml into ServiceBuilder

### PR DESCRIPTION
**Pull request by julschong**
@vicnate5 @tinatian 
Hi Victor, Tina,

Please see the issue: https://issues.liferay.com/browse/LPS-172623 and https://issues.liferay.com/browse/PTR-3686 for the details on the issue and steps to reproduce it

I tested this locally with 7.2.x by:
1. `cd modules/utils/portal-tools-service-builder`   then  `gw deploy`
2. Copy `tools/sdk/dependencies/com.portal.tools.service.builder/lib/com.portal.tools.service.builder.jar`  
and replace and rename into 
`7.2.x/.gradle/caches/modules-2/files-2.1/com.liferay.portal.tools.service.builder/1.0.446/647f756fde84d3fac50ef83968f208742b10f83b/com.liferay.portal.tools.service.builder-1.0.446.jar`
3. Verify that error does not come up anymore by running `gw buildService` in `modules/apps/journal/journal-service`

I couldn't get the fake gradle cache to work for the longest time so instead I just use the newly built jar to paste over the old one in 7.2.x

Thank you!

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by julschong** [comment]
@ericyanLr I haven't tested 7.0.x yet. I can test it today

**Comment by catarineaguiar** [comment]
no regressions found. 
SF issue is not related.

**Comment by julschong** [comment]
@catarineaguiar I'm taking the QA Passed tag off for now, still need to run in 7.0.x to test

**Comment by julschong** [comment]
> Hey @julschong ,
> 
> Just wanted to double check, do you know if this fix also fixes the issue for 70x?
> 
> * The original commit: [liferay@bfb7226](https://github.com/liferay/liferay-portal/commit/bfb722653beaa8f40823c5631651babea6d92fed)
>   
>   * Removed both **trash/service.xml** and **mail/service.xml**
> * In 70x, the journal-service has a service.xml that also has a reference entity to Mail
> 
> ```
> <reference entity="Mail" package-path="com.liferay.mail" />
> ```
> 
> * Reference: https://github.com/liferay/liferay-portal/blob/7.0.6-ga7/modules/apps/web-experience/journal/journal-service/service.xml#L214
> 
> Thanks!

@ericyanLr confirmed 7.0.x failed because of Mail will add on

**Comment by julschong** [comment]
pushed to add mail/service.xml into SB

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong No regressions found. Testing passed on 7.0-7.3

**Comment by Kvale1733** [comment]
SF issue is unrelated.

**Comment by tinatian** [comment]
ci:forward

**Comment by julschong** [comment]
Closing, found issue with the service.xml will resend

**Pull request closed without merging**
