### PR TITLE
[Optional Reference]LPS-185548 module:site-api

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-185548

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
