### PR TITLE
remove_deprecated_part_3_redo

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian , @shuyangzhou,

I separated the generated code from manually modified code, see https://github.com/liferay-core-infra/liferay-portal/pull/336.
I have removed deprecated methods or classes for "portal-impl/src/com/liferay/portal/service/impl", "portal-impl/src/com/liferay/portal/servlet", and "portal-impl/src/com/liferay/portal/tools".
Thanks for checking.

Thanks,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@kyle-miho Hey Kyle, could you please help me to scan the test result?

Thanks,
Jeff

**Comment by tinatian** [comment]
@jeffwu0724 Code looks good to me, waiting for QA to verify test results.

Tina.

**Comment by kyle-miho** [comment]
@jeffwu0724 could you double check the semantic versioning bumps? CI got a semvar error on this PR
java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS
= ================================================== ========== ========== ========== ========== ==========



com.liferay.portal.cache                           MAJOR      3.0.1      3.0.1      4.0.0      VERSION INCREASE REQUIRED
>   class      com.liferay.portal.cache.BasePortalCache

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:test

**Comment by kyle-miho** [comment]
pr looks good @jeffwu0724

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113897

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
