### PR TITLE
LPS-191325 Remove web cache usage in search-experience-service

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
The SF failure should be related.

**Comment by julschong** [comment]
pushed for sf issue

**Comment by julschong** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
@julschong Compile issue found causing search-experience integration tests not to run
```
     [exec] > Task :apps:users-admin:users-admin-test-util:autoUpdateXml SKIPPED
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/search-experiences/search-experiences-service/src/test/java/com/liferay/search/experiences/internal/blueprint/parameter/contributor/IpstackSXPParameterContributorTest.java:48: error: constructor IpstackSXPParameterContributor in class com.liferay.search.experiences.internal.blueprint.parameter.contributor.IpstackSXPParameterContributor cannot be applied to given types;
     [exec] 		_ipstackSXPParameterContributor = new IpstackSXPParameterContributor(
     [exec] 		                                  ^
     [exec]   required: com.liferay.portal.kernel.module.configuration.ConfigurationProvider,com.liferay.search.experiences.internal.cache.IpstackCache
     [exec]   found: com.liferay.portal.kernel.module.configuration.ConfigurationProvider
     [exec]   reason: actual and formal argument lists differ in length
```
[Log](https://testray.liferay.com/reports/production/logs/2023-07/test-1-40/test-portal-acceptance-pullrequest(master)/4537/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
pushed unit test fix

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:stable

**Pull request closed without merging**
