### PR TITLE
[Optional Reference]LPS-198646 module: dynamic-data-mapping-service 

### PR DESCRIPTION
**Pull request by JanisZhang**
Convert the Optional references to Snapshot in class `DDMStructureLocalServiceImpl`
https://liferay.atlassian.net/browse/LPS-198646

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:data-engine

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
