### PR TITLE
LPS-195671 Merge UsersAdmin interface and impl into Util and move to portal-impl

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from https://github.com/liferay-core-infra/liferay-portal/pull/5558

This PR does not contain change to instance wrapper

### CODE REVIEW

**Comment by julschong** [comment]
fix compile error

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
No regressions found.

**Comment by vicnate5** [comment]
ci:test:sf

**Comment by julschong** [comment]
rebased and retest

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found. The SF failures should not be related.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141442

**Pull request closed without merging**
