### PR TITLE
LPS-159031 Fix RW data source

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian This pull is to test the fix. By making `DynamicDataSourceAdvice` always the first in the advice array, the buffered increment issue can be resolved. If the tests passes, I'll try to hardcode `DynamicDataSourceAdvice` in `AopInvocationHandler` like what we do for `TransactionInterceptor`.

By the way, merging `DynamicDataSourceAdvice` into `TransactionInterceptor` doesn't seem to be necessary if this pull works, and it will make `TransactionInterceptor` look complicated and a bit messy as I tried.

@vicnate5 Do we have tests on CI covering RW data source?

### CODE REVIEW

**Comment by Kvale1733** [comment]
@dantewang Yes there are two tests that cover this. I tried running them locally but had issues. Running them on CI here: https://github.com/Kvale1733/liferay-portal/pull/252

**Comment by Kvale1733** [comment]
@dantewang So the tests steps actually pass and there are traces of the read and write data sources. But the tests are still failing due to an error appearing several times in the logs.
```
 LIFERAY_ERROR: INSERT command denied to user 'read_only_user'@'172.31.0.2' for table 'LayoutPageTemplateEntry'
 ```
 [Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-27/test-portal-acceptance-pullrequest(master)/6466/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)
 
 But I think that's expected since the read only user only has read permissions. Looks like this only appears now since the fix now shows the traces for the read data source that weren't appearing before. If that's the case then it's just the test that needs to be updated so it doesn't fail on this error.

**Comment by dantewang** [comment]
Hi @Kvale1733 @zhangyan0701, could you let me know the steps of the failed test due to the error above? If it's a functional test then we need to fix the Liferay error. An important goal of this pull is to make sure any possible write operation won't use the read-only data source.

**Comment by zhangyan0701** [comment]
@dantewang

We have two tests to cover RW data source, one is for JDBC and the other one is for JNDI.
The steps are:

1. Create a read only user in database:
```
create user 'read_only_user'@'%' identified BY 'password';
grant select ON *.* TO 'read_only_user'@'%';
flush privileges;
```
2. 

2.1 JDBC:
Add below properties in portal-ext.properties:
```
jdbc.read.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.read.url=jdbc:mysql://localhost/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true
jdbc.read.username=read_only_user
jdbc.read.password=password

jdbc.write.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.write.url=jdbc:mysql://localhost/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true
jdbc.write.username=root
jdbc.write.password=

counter.jdbc.prefix=jdbc.write.
 
   spring.infrastructure.configs=\
       /META-INF/infrastructure-spring.xml,\
       \
       /META-INF/counter-infrastructure-spring.xml,\
       /META-INF/dynamic-data-source-infrastructure-spring.xml,\
       /META-INF/hibernate-spring.xml
```

2.2 JNDI:

- Update tomcat/conf/context file, add 
```
<ResourceLink name="jdbc/LiferayPool" global="jdbc/LiferayPool" type="javax.sql.DataSource" />
<ResourceLink name="jdbc/LiferayReadPool" global="jdbc/LiferayReadPool" type="javax.sql.DataSource" />
```
into `<context>` tab.

- Update tomcat/conf/server.xml, add
```
<Resource
	auth="Container"
	description="Global Address Database"
	driverClassName="com.mysql.cj.jdbc.Driver"
	maxActive="40"
	maxIdle="20"
	maxWait="1000"
	name="jdbc/LiferayPool"
	password=""
	type="javax.sql.DataSource"
	url="jdbc:mysql://localhost/lportal?useUnicode=true&amp;characterEncoding=UTF-8&amp;useFastDateParsing=false&amp;serverTimezone=GMT&amp;dontTrackOpenResources=true&amp;holdResultsOpenOverStatementClose=true"
	username="root"
/>
<Resource
	auth="Container"
	description="Global Address Database"
	driverClassName="com.mysql.cj.jdbc.Driver"
	maxActive="40"
	maxIdle="20"
	maxWait="1000"
	name="jdbc/LiferayReadPool"
	password="password"
	type="javax.sql.DataSource"
	url="jdbc:mysql://localhost/lportal?useUnicode=true&amp;characterEncoding=UTF-8&amp;useFastDateParsing=false&amp;serverTimezone=GMT&amp;dontTrackOpenResources=true&amp;holdResultsOpenOverStatementClose=true"
	username="read_only_user"
/>
```
into `<GlobalNamingResources>` tab.

- Add below properties in portal-ext.properties:
```
jdbc.write.jndi.name=jdbc/LiferayPool
jdbc.read.jndi.name=jdbc/LiferayReadPool

counter.jdbc.prefix=jdbc.write.
 
   spring.infrastructure.configs=\
       /META-INF/infrastructure-spring.xml,\
       \
       /META-INF/counter-infrastructure-spring.xml,\
       /META-INF/dynamic-data-source-infrastructure-spring.xml,\
       /META-INF/hibernate-spring.xml
```
3. Start portal.

The errors that occurred in the JDBC test in https://github.com/Kvale1733/liferay-portal/pull/252 are below:
```
INSERT command denied to user 'read_only_user'@'172.31.1.3' for table 'LayoutPageTemplateEntry'
... ...
```
Full console: https://testray.liferay.com/reports/production/logs/2023-01/test-1-27/test-portal-acceptance-pullrequest(master)/6466/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0

All the errors are about table `LayoutPageTemplateEntry`.

But in JNDI test, there are some other errors:
```
INSERT command denied to user 'read_only_user'@'172.31.0.2' for table 'Release_'
... ...
Spring Extender Unavailable Component Checker check result: 
Bundle {id: 240, name: com.liferay.portal.tools.service.builder.test.service, version: 1.0.0}.
... ...
```
Full console: https://testray.liferay.com/reports/production/logs/2023-01/test-1-27/test-portal-acceptance-pullrequest(master)/6466/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0

**Comment by dantewang** [comment]
@zhangyan0701 From the console log, it seems that, for the JDBC test, portal starts successfully, but the errors occur when operating the portal using headless API?

**Comment by Kvale1733** [comment]
@dantewang So the tests first set  the log level in Server Administration for com.liferay.portal.dao.jdbc.aop.DefaultDynamicDataSourceTargetSource to ALL as the ticket suggests. Based on the tests, it looks like this error appears just from 
1. Creating a site
2. Adding a page to the site
3. Adding a widget to the site.

I got the tests to work locally by creating the read only user with a blank password (and leaving the password blank in portal-ext
```
create user 'read_only_user'@'%' identified BY '';
```

And the JDBC test passed twice without issue. It also passed the first time I ran it on CI so this might be an issue on CI only. Looks like both tests are running on the same batch so maybe this is an issue. I'm going to modify the tests so they run on a separate instance and see if they pass.

**Comment by Kvale1733** [comment]
@dantewang So I was finally able to reproduce locally. Here are the steps for the JDBC test simplified. 

1. Create a read only user in database:
```
create user 'read_only_user'@'localhost' identified BY 'password';
grant select ON *.* TO 'read_only_user'@'localhost';
flush privileges;
```

2. Add below properties in portal-ext.properties:
```
jdbc.read.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.read.url=jdbc:mysql://localhost/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true
jdbc.read.username=read_only_user
jdbc.read.password=password

jdbc.write.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.write.url=jdbc:mysql://localhost/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true
jdbc.write.username=root
jdbc.write.password=

counter.jdbc.prefix=jdbc.write.
 
   spring.infrastructure.configs=\
       /META-INF/infrastructure-spring.xml,\
       \
       /META-INF/counter-infrastructure-spring.xml,\
       /META-INF/dynamic-data-source-infrastructure-spring.xml,\
       /META-INF/hibernate-spring.xml
```
3. Start portal
4. Go to Control Panel > Server Administration > Log Levels
5. Add the following log category with log level ALL
```
com.liferay.portal.dao.jdbc.aop.DefaultDynamicDataSourceTargetSource
```
6. Create a new content page
7. Try adding a Button Fragment to the page 

Expected Results: Can add the button fragment to the page without issue
Actual Results: Cannot add the button fragment to the page. "An unexpected error occurred" message appears in the portal. In the console the following appears
```
INSERT command denied to user 'read_only_user'@'localhost' for table 'FragmentEntryLink'
```

This occurs with other widgets and fragments. Some don't have this issue however like the Asset Publisher.

**Comment by dantewang** [comment]
@Kvale1733 Thank you Kevin! I'll look into these.

**Pull request closed without merging**
