### PR TITLE
[Remove unused field] LPS-199196 Remove unused reference field in classes EditCTCollectionTemplateMVCActionCommand and MoveChangesMVCActionCommand

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(10/19 8:19)

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142433

cc @shuyangzhou

**Pull request closed without merging**
