### PR TITLE
[Spring Extender]LPS-167595 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:commerce

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Could you please verify if the failed tests related to this pull?

**Comment by vicnate5** [comment]
The failure is related to this PR. I cannot reproduce on master upstream and the errors are not showing anywhere else in the test history.

Steps to Reproduce:
1. [Download 7.3 database dump](https://github.com/liferay/liferay-qa-portal-legacy-ee/raw/master/7.3.10/data-archive/data-archive-commerce-mysql.zip)
2. Import dump into MySQL
3. Set properties in portal-ext
```
upgrade.database.auto.run=true
initial.system.check.enabled=true
```
4. Start tomcat against this database. Upgrade will run on startup.

Result: System check fails on commerce modules

**Comment by tinatian** [comment]
ci:reopen

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@tinatian This PR is closed, so the test are not going to run. Can you send a new PR?

**Pull request closed without merging**
