### PR TITLE
LPS-163307 Clean up TemplateManager

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@julschong many integration tests failed with this message:

```
[beanshell] 2022-09-20 23:59:54.622 ERROR [http-nio-8080-exec-1][runtime:59] Error executing FreeMarker template
[beanshell] freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
[beanshell] ==> htmlUtil  [in template "com.liferay.portal.template.freemarker_7.0.28_CLASS_LOADER_CONTEXT_FTL_liferay.ftl" at line 23, column 33]
[beanshell] 
[beanshell] ----
[beanshell] Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
[beanshell] ----
[beanshell] 
[beanshell] ----
[beanshell] FTL stack trace ("~" means nesting-related):
[beanshell] 	- Failed at: css_main_file = htmlUtil.escape(theme...  [in template "com.liferay.portal.template.freemarker_7.0.28_CLASS_LOADER_CONTEXT_FTL_liferay.ftl" at line 23, column 17]
[beanshell] ----
[beanshell] 	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134) ~[bundleFile:?]
[beanshell] 	at freemarker.core.UnexpectedTypeException.newDescriptionBuilder(UnexpectedTypeException.java:85) ~[bundleFile:?]
[beanshell] 	at freemarker.core.UnexpectedTypeException.<init>(UnexpectedTypeException.java:48) ~[bundleFile:?]
[beanshell] 	at freemarker.core.NonHashException.<init>(NonHashException.java:49) ~[bundleFile:?]
[beanshell] 	at freemarker.core.Dot._eval(Dot.java:48) ~[bundleFile:?]
[beanshell] 	at freemarker.core.Expression.eval(Expression.java:101) ~[bundleFile:?]
[beanshell] 	at freemarker.core.MethodCall._eval(MethodCall.java:55) ~[bundleFile:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-31/test-portal-acceptance-pullrequest(master)/5112/modules-integration-mysql57-jdk8/4/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
corrected helperUtilites calculation logic in TempalteContextHelper

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
yup looks much better than before

**Comment by catarineaguiar** [comment]
results look ok now @julschong

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

This classloader support was added by LPS-27741 https://github.com/liferay/liferay-portal/commit/ee9dae93c7e878fefc6bbe2ae69153ebc7e58210, it was used to support PACL which we do not need any more.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123532

**Pull request closed without merging**
