### PR TITLE
LPS-140576 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@kyle-miho Can you check this one?

**Comment by kyle-miho** [comment]
one unique failure: com.liferay.portal.workflow.kaleo.internal.runtime.integration.test.WorkflowInstanceManagerImplTest > testUpdateActive FAILED
but I think its unrelated / minor impact if this does cause the fail, i'll re-run ci:test to confirm

**Comment by kyle-miho** [comment]
ci:test

**Comment by tinatian** [comment]
@kyle-mih Could you please scan the results?

Thanks.
Tina

**Comment by vicnate5** [comment]
@kyle-miho

**Comment by kyle-miho** [comment]
@tinatian pr should be good, failures are unrelated

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/111445

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
