### PR TITLE
[Remove Blocking usages]LPS-188770 portal-kernel |DLStoreUtil

### PR DESCRIPTION
**Pull request by JanisZhang**
https://liferay.atlassian.net/browse/LPS-188770

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
Force-pushed. I only changed the commit message. It shouldn't affect the test results. Thanks!

**Comment by zhangyan0701** [comment]
ci:test:dl-store

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by JanisZhang** [comment]
Hi @dantewang, since DLStoreUtil is currently receiving the DLStoreImpl bean directly from the Spring container through dependency injection, it should be able to avoid using blocking calls.

**Comment by tinatian** [comment]
@JanisZhang Please see https://github.com/brianchandotcom/liferay-portal/pull/138556.
Please note I modified your commit message, please always include the reason you made a change in the commit message rather than extra comments on the pull request.

Thanks.
Tina.

**Pull request closed without merging**
