### PR TITLE
[Phase 1] LPS-174289 Remove Stream for module: portal-search-test-util part 2

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from #3715 due to compile error
added [60e6e32](https://github.com/liferay-core-infra/liferay-portal/pull/3745/commits/60e6e3246d4581c85f241f9df345ad8df490521e)

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@julschong Compile issue found
```
[exec] > Task :apps:wiki:wiki-test-util:jar
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/wiki/wiki-test/src/testIntegration/java/com/liferay/wiki/search/test/WikiPageTitleSearcherTest.java:149: error: no suitable method found for assertValuesIgnoreRelevance(java.lang.String,com.liferay.portal.kernel.search.Document[],java.lang.String,java.util.Collection<java.lang.String>)
     [exec] 		DocumentsAssert.assertValuesIgnoreRelevance(
     [exec] 		               ^
     [exec]     method com.liferay.portal.search.test.util.DocumentsAssert.assertValuesIgnoreRelevance(java.lang.String,com.liferay.portal.kernel.search.Document[],java.lang.String,java.util.List<java.lang.String>) is not applicable
     [exec]       (argument mismatch; java.util.Collection<java.lang.String> cannot be converted to java.util.List<java.lang.String>)
     [exec]     method com.liferay.portal.search.test.util.DocumentsAssert.assertValuesIgnoreRelevance(java.lang.String,java.util.List<com.liferay.portal.search.document.Document>,java.lang.String,java.util.List<java.lang.String>) is not applicable
     [exec]       (argument mismatch; com.liferay.portal.kernel.search.Document[] cannot be converted to java.util.List<com.liferay.portal.search.document.Document>)
     [exec]     method com.liferay.portal.search.test.util.DocumentsAssert.assertValuesIgnoreRelevance(java.lang.String,java.util.List<com.liferay.portal.search.document.Document>,java.lang.String,java.lang.String) is not applicable
     [exec]       (argument mismatch; com.liferay.portal.kernel.search.Document[] cannot be converted to java.util.List<com.liferay.portal.search.document.Document>)
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/wiki/wiki-test/src/testIntegration/java/com/liferay/wiki/internal/exportimport/data/handler/test/WikiPageStagedModelDataHandlerTest.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 1 error
     [exec] 
     [exec] > Task :apps:wiki:wiki-test:compileTestIntegrationJava FAILED
```
[Log](https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/456942//consoleText)

**Comment by Kvale1733** [comment]
Also failure in 

com.liferay.portal.search.elasticsearch7.internal.query.MatchAllQueryTest

```
 [exec] com.liferay.portal.search.elasticsearch7.internal.query.MatchAllQueryTest > testMatchAllQuery FAILED
     [exec]     org.junit.ComparisonFailure: {"from":0,"size":30,"query":{"bool":{"must":[{"bool":{"must":[{"term":{"entryClassName":{"value":"matchallquerytest.testmatchallquery"}}},{"term":{"companyId":{"value":"8352764135482745176"}}}]}}],"filter":[{"match_all":{"boost":1.0}}]}},"explain":false,"stored_fields":"*","sort":[{"priority":{"order":"asc","unmapped_type":"keyword"}}],"track_total_hits":2147483647}->{uid=matchallquerytest.testmatchallquery_PORTLET_7847003652036299650, companyId=8352764135482745176, entryClassPK=7847003652036299650, entryClassName=matchallquerytest.testmatchallquery, groupId=609360789961445315, priority=1.0},{uid=matchallquerytest.testmatchallquery_PORTLET_8466605864113757412, companyId=8352764135482745176, entryClassPK=8466605864113757412, entryClassName=matchallquerytest.testmatchallquery, groupId=609360789961445315, priority=2.0},{uid=matchallquerytest.testmatchallquery_PORTLET_7802105158182498337, companyId=8352764135482745176, entryClassPK=7802105158182498337, entryClassName=matchallquerytest.testmatchallquery, groupId=609360789961445315, priority=3.0},{uid=matchallquerytest.testmatchallquery_PORTLET_8561328132116272818, companyId=8352764135482745176, entryClassPK=8561328132116272818, entryClassName=matchallquerytest.testmatchallquery, groupId=609360789961445315, priority=4.0},{uid=matchallquerytest.testmatchallquery_PORTLET_6477241481703223106, companyId=8352764135482745176, entryClassPK=6477241481703223106, entryClassName=matchallquerytest.testmatchallquery,  
```
[Log](https://testray.liferay.com/reports/production/logs/2023-03/test-1-28/test-portal-acceptance-pullrequest(master)/5927/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
@julschong Please resend, thanks!

**Pull request closed without merging**
