### PR TITLE
[Bug fix] LPS-161435 | 9-23

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Force pushed just to SF.

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results? This pull changes a lot of files in different modules, please trigger any other suites needed.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@111Anna Please run a startup test for this PR, thanks!

**Comment by 111Anna** [comment]
@dantewang @tinatian @GinsonRen   I ran a startup diff, here are results.
Portal Version |GitId |Cold Startup (with HSQL) |Cold Startup (without HSQL) |Average Startup (without HSQL) | % |Cold Shutdown (with HSQL) |Cold Shutdown (without HSQL) |Average Shutdown (without HSQL) | %
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine |8b6306 |48627 |52154 |31281ms |- |7153 |6882 |6741ms | -
PR-1789 |- |54560 |51754 |31027.3ms |0.81% |6635 |6746 |6931.3ms | -2.82%

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@tinatian Force pushed to rebase and resolve conflict on portal-vulcan-api/bnd.bnd.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
Closing this one as we talked, I've reopened and rebased https://github.com/liferay-core-infra/liferay-portal/pull/1748 @tinatian

**Pull request closed without merging**
