### PR TITLE
LPS-186545

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
@tinatian most tests didn't run due to:

```
     [exec] > Task :apps:portal-search-elasticsearch7:portal-search-elasticsearch7-impl:compileTestJava FAILED
     [exec] 
     [exec] > Task :apps:portal-search-elasticsearch7:portal-search-elasticsearch7-impl:processTestResources
     [exec] > Task :apps:portal-search-elasticsearch7:portal-search-elasticsearch7-spi:autoUpdateXml SKIPPED
     [exec] > Task :core:petra:petra-process:autoUpdateXml SKIPPED
     [exec] Gradle build finished at 2023-07-15 03:03:34.511.
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/test/java/com/liferay/portal/search/elasticsearch7/internal/filter/ElasticsearchFilterTranslatorFixture.java:44: error: constructor QueryFilterTranslatorImpl in class com.liferay.portal.search.elasticsearch7.internal.filter.QueryFilterTranslatorImpl cannot be applied to given types;
     [exec] 				queryFilterTranslator = new QueryFilterTranslatorImpl(
     [exec] 				                        ^
     [exec]   required: no arguments
     [exec]   found: com.liferay.portal.kernel.search.query.QueryTranslator<org.elasticsearch.index.query.QueryBuilder>
     [exec]   reason: actual and formal argument lists differ in length
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/test/java/com/liferay/portal/search/elasticsearch7/internal/legacy/query/ElasticsearchQueryTranslatorFixture.java:33: error: cannot find symbol
     [exec] 						filterTranslator =
     [exec] 						^
     [exec]   symbol: variable filterTranslator
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 2 errors
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-07/test-1-37/test-portal-acceptance-pullrequest(master)/13171/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
ci:test:search

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5015

**Comment by zhangyan0701** [comment]
There is an error occurred in test [LocalFile.Elasticsearch7#SearchAfterRedeployingElasticsearchConnector](https://testray.liferay.com/home/-/testray/case_results/2385213977):

`2023-07-17 20:06:18.186 ERROR [http-nio-8080-exec-8][BooleanQueryTranslatorImpl:79] Unable to translate boolean filter {MUST({MUST({(companyId=20096), (cached=null, executionOption=null)})}, {MUST({MUST({MUST({(groupId=[20119]), ... ... (cached=null, executionOption=null)} as filter translator is null`

Steps:
1. Start portal with Remote Elasticsearch.
2. Go to Gogo Shell, run command "stop com.liferay.portal.search.elasticsearch7.impl".
3. After module stopped, start it again by command "start com.liferay.portal.search.elasticsearch7.impl".
4. Go to Control Panel > Search and execute reindex.
5. Go to Home page, search for "test".

The error thrown in liferay log.

**Comment by tinatian** [comment]
@vicnate5 The issue @zhangyan0701 mentioned seems like not stable test based on https://liferay.atlassian.net/browse/LPS-168748, could you please take a look at?

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian The test is stable upstream now [per history](https://testray.liferay.com/home/-/testray/cases/2046686687). It failed 3 times for the error Summer mentioned, but all 3 times are from this change here.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5063

**Pull request closed without merging**
