### PR TITLE
[SF] LPS-197878 Implement SF rules to check usages of `*OSGiCommands`

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__ <https://liferay.atlassian.net/browse/LPS-197878>

This PR creates a new SF check for `*OSGiCommands` classes. It does the following:

1. Check that the names of OSGi component classes that implement OSGi commands end in "OSGiCommands".
2. Check to make sure no OSGi references are made to `*OSGiCommands` classes.
3. Check that each `osgi.command.function` specified in the `property` attribute has a corresponding method for it.

There is one weird case that I added a SF suppression for, which is a SchedulerJobConfiguration that implements OSGi commands: `AntivirusAsyncFileStoreSchedulerJobConfiguration.java`.

cc: @shuyangzhou, @rafaprax

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @kevhlee,

I already talked to the guys here in Brazil to take care of this case as soon as possible.

Thanks for catching that

//cc @MrJohn1911

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142325

**Pull request closed without merging**
