### PR TITLE
[Replace Non-Blocking Usage] LPS-198877 Remove unused class OpenIdUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(10/19 8:19)

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou This one has breaking change documented.

**Pull request closed without merging**
