### PR TITLE
[Replace Non-Blocking Usage] LPS-199499

### PR DESCRIPTION
**Pull request by JanisZhang**
previous:https://github.com/liferay-core-infra/liferay-portal/pull/5831

https://liferay.atlassian.net/browse/LPS-199499

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:clustering

**Comment by dantewang** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
