### PR TITLE
[Startup time optimization] LPS-160875

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to disable auto-import-default-references in portal-workflow-kaleo-service. Thanks!
https://issues.liferay.com/browse/LPS-160875

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @zhangyan0701, Could you please help to scan the test results? Thanks!

**Comment by JanisZhang** [comment]
Hi @zhangyan0701, Could you please help to scan the test results? Thanks!

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
@JanisZhang Code looks good to me, wait for QA to scan test results.
@catarineaguiar Please help me scan test results.

Tina

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121835

**Pull request closed without merging**
