### PR TITLE
[Remove Stream/Optional usage] LPS-172262 Remove Stream<> in portal-search-tuning-rankings-web PART2

### PR DESCRIPTION
**Pull request by dantewang**
FYI @LisztLiszt

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
ci:reevaluate:1377401_8597

**Comment by yuhai** [comment]
Resend it to https://github.com/liferay-search/liferay-portal/pull/769 to review.

**Pull request closed without merging**
