### PR TITLE
[TS] LPD-29981

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by tinatian** [comment]
@dantewang We can not just remove escape as it might cause xss

**Comment by dantewang** [comment]
@tinatian Please see the linked ticket in the LPD, `<option>` escapes internally and that's what causes the problem.

**Pull request closed without merging**
