### PR TITLE
[Reference cleanup]LPS-162018

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

Resend, fixed unit test.

This PR is to convert method references to field references in document-library. Thanks!
https://issues.liferay.com/browse/LPS-162018

precious PR: https://github.com/liferay-core-infra/liferay-portal/pull/1527

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @zhangyan0701, Could you please help to scan the test results? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122879

**Pull request closed without merging**
