### PR TITLE
LPD-17248 Fix com.liferay.portal.kernel.util.HtmlUtilTest on JDK21

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://liferay.atlassian.net/browse/LPD-17248

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @tinatian, I tested it locally with jdk8 and jdk21. Thx

**Comment by rafaprax** [comment]
just changed the commit message

**Comment by tinatian** [comment]
@rafaprax the script engine logic was added to cover a bug at https://github.com/liferay-core-infra/liferay-portal/commit/16cb87a7cd1011b29939b1a5afe45e27735ac334, please check if there is other way to achieve the same goal as before.

Please resend.

Thanks.
Tina.

**Comment by rafaprax** [comment]
sent here https://github.com/liferay-core-infra/liferay-portal/pull/6605

**Pull request closed without merging**
