### PR TITLE
[Method References 2] LPS-177112 Convert method reference to ServiceTracker in classes IndexDefinitionsRegistryImpl, IndexSynchronizationPortalInitializedListener

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3720

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
@W2jx semver error:

```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/portal-search/portal-search-spi] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.portal.search.spi.index                MAJOR      1.0.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   interface  com.liferay.portal.search.spi.index.IndexDefinition
     [exec]     		-   field      PROPERTY_KEY_INDEX_NAME
     [exec]     			-   access     final
     [exec]     			-   access     static
     [exec]     			-   constant   index.name
     [exec]     			-   return     java.lang.String
     [exec]     		-   field      PROPERTY_KEY_INDEX_SETTINGS_RESOURCE_NAME
     [exec]     			-   access     final
     [exec]     			-   access     static
     [exec]     			-   constant   index.settings.resource.name
     [exec]     			-   return     java.lang.String
     [exec]     		+   method     getIndexName()
     [exec]     			+   access     abstract
     [exec]     			+   return     java.lang.String
     [exec]     		+   method     getIndexSettingsResourceName()
     [exec]     			+   access     abstract
     [exec]     			+   return     java.lang.String
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 8.0.0
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-03/test-1-37/test-portal-acceptance-pullrequest(master)/9804/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
only do semver, no need to rerun test

**Comment by W2jx** [comment]
no conflicts(3/17 14:36)

**Comment by W2jx** [comment]
no conflicts(3/20 8:52)

**Comment by W2jx** [comment]
no conflicts(3/21 10:29)

**Comment by W2jx** [comment]
no conflicts(2/23 15:51)

**Comment by tinatian** [comment]
@W2jx Please send a new pull to remove.

Thanks.
Tina

**Comment by tinatian** [comment]
@W2jx Please add this to breaking change

**Pull request closed without merging**
