### PR TITLE
LPS-162111

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by dantewang** [comment]
@marianoalvarosaiz Did you only observe this issue when the exception is being put into `SessionError`?

**Comment by marianoalvarosaiz** [comment]
@dantewang not in the moment that is put, but in the moment that needs to be retrieved in the script.jsp file. So, the problem appears after https://issues.liferay.com/browse/LPS-106785, but the LPS really didn't cause the issue.

**Comment by dantewang** [comment]
@marianoalvarosaiz Could you modify `EditServerMVCActionCommand`, where the exception is put into `SessionErrors`, to only put the exception message, and see if this can fix the issue?

```
		catch (ScriptingException scriptingException) {
			SessionErrors.add(
				actionRequest, ScriptingException.class.getName(),
				scriptingException); // here, line 601

			Log log = SanitizerLogWrapper.allowCRLF(_log);

			log.error(scriptingException.getMessage());
		}
```

This way the full stack can still be shown if the script engine is called elsewhere (e.g. from Scheduler).

**Comment by dantewang** [comment]
@marianoalvarosaiz BTW if my suggestion works, please send to USM team for review, thanks!

**Comment by dantewang** [comment]
@marianoalvarosaiz If a developer decides to call the script executor directly, then the developer should handle all the issues during serialization/deserialization. After all we're just calling Groovy to run the script, and the exception is thrown by Groovy. It should be out of our scope.

The `SessionErrors` case, on the other hand, is one of the custom development made by us, and is accessible via our UI, so we need to fix it.

cc @tinatian

**Comment by marianoalvarosaiz** [comment]
Sorry, but I've to disagree.

1. Even if the exception is thrown by Groovy, it's a third party library that is part of our product. It's our responsibility to maintain the possible errors that a third party library has. That's why we patch third party libraries. 
2. If we fix the _MVCActionCommand_ next day a new bug can be opened with reproduction steps:
- Call groovy executor from a custom module
- Catch the thrown exception.
- Perform an ```instanceof Serializable``` over the thrown exception and if true perform a serialize/deserialize.
3. It's poor code quality that an own module can throw an exception that adheres to the Serializable contract but can't be deserialized, with the aggravating that the error won't be detected until runtime.

Please reconsider it.

/cc @tinatian

**Comment by dantewang** [comment]
@marianoalvarosaiz

I still don't think it should be done at the script executor level. When talking about custom development which we don't have control on, what if a developer doesn't want to serialize the exception, but rather wants to  get that dynamic class from the exception to do some custom processing? Any trimming of the information from the exception may cause inconvenience for custom development.

The serializable contract is there by the JDK (Throwable is a Serializable), but it's Groovy who violates the contract. I wonder if they just do this carelessly, or do have a reason. A bug ticket should be issued to Groovy's issue tracker.

On Liferay side, a middle way is, provide a custom exception in Liferay which is/has all the information from Groovy's exception (like a wrapper), but implement customized serialization/deserialization logic (writeObject and readObject methods).

cc @tinatian

**Review by dantewang — COMMENTED** [review]
@marianoalvarosaiz After another discussion I'm going to approve the current solution. The way I suggested may be a bit overkill here. Anyway, we don't know who's going to directly call the script executor API.

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results?

**Comment by marianoalvarosaiz** [comment]
@dantewang thanks a lot, see https://github.com/liferay-core-infra/liferay-portal/pull/1616

**Pull request closed without merging**
