### PR TITLE
LPS-191424 fix: Suitable but non-accessible field error in class RoleNotificationRecipientBuilder

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-191424](https://liferay.atlassian.net/browse/LPS-191424)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:workflow

**Comment by zhangyan0701** [comment]
No regressions found. And the warning in the ticket didn't happen.

**Comment by dantewang** [comment]
ci:test:stable

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138294

**Pull request closed without merging**
