### PR TITLE
LPS-176210

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@GinsonRen Please run start up and daily tests to verify no performance regressions.

FYI @dantewang 

Thanks.
Tina

**Comment by GinsonRen** [comment]
@111Anna Please run a startup diff, thanks.

**Comment by 111Anna** [comment]
Hi @tinatian @dantewang @GinsonRen , I ran the PR on test machine, there is no regression.
Here are test results:

CE

Portal Version|GitId|Average   Startup (ms)|%|Average   Shutdown (ms)|%|Open File|Thread   Create|Open Prepared Statement|Open SQL|Open Service Tracker
--|--| --|--|--|--|--|--|--|--|--|
Baseline| 947f3b02| 21723.3 |- |2978|-| 1839 | 89 | 368| 997 |489|
Baseline + PR-3918| - |  21647 |0.35%| 3051.3|-2.40%| 1839 | 85 | 368 | 985 |453|

DXP
Portal Version|GitId|Average   Startup (ms)|%|Average   Shutdown (ms)|%|Open File|Thread   Create|Open Prepared Statement|Open SQL|Open Service Tracker
--|--| --|--|--|--|--|--|--|--|--|
Baseline| 947f3b02| 23693.3 |- |3447|-| 2003 | 100| 396| 1085 |500|
Baseline + PR-3918| - |  23516.6 | 0.75%| 3496.6|-1.44%| 2003 | 98 | 396 | 1073|502 |

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
ci:test:environments

**Comment by dantewang** [comment]
ci:test:environments

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132000

**Pull request closed without merging**
