### PR TITLE
LPS-145585 Avoid using ZipReaderFactoryUtil, ZipWriterFactoryUtil, SitesUtil directly in modules

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina, Shuyang

Main Task: [LPS-143403](https://issues.liferay.com/browse/LPS-143403)
Sub Task: [LPS-145585](https://issues.liferay.com/browse/LPS-145585)

Note: I cause a mistake I made to the SF properties from resolving conflict. Fix is on the last commit.

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
could you please help me scan the test result?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by julschong** [comment]
@tinatian Hi Tina,
could you please help me remove this pr?
thank you!

**Comment by julschong** [comment]
Close for now, need to fix SF issue first

**Pull request closed without merging**
