### PR TITLE
LPS-150839 Move petra-apache-http-components to inline into translation-api

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,

Main Task: [LPS-147928 Remove petra jar from modules/apps](https://issues.liferay.com/browse/LPS-147928)
Sub Task: [LPS-150839 Move petra-apache-http-components to inline into translation-api](https://issues.liferay.com/browse/LPS-150839)

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@kyle-miho
Hi Kyle,
Could you please help me scan this test result?
Thank you!

**Comment by julschong** [comment]
@kyle-miho I'll need to fix this one.

**Comment by julschong** [comment]
pushed again after adding .lfrbuild-packageinfo

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by tinatian** [comment]
@julschong I did not notice that we have some many CompanyInclude for URIBuilder. I am wondering if we can replace URIBuilder with HttpUtil. Let's have a talk about it tomorrow.

Tina.

**Comment by tinatian** [comment]
@julschong As we talked, please resend, I am going to close this pull.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
