### PR TITLE
 LPS-189816 move_net_minidev_to_shared-dependencies

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,
In this PR, I would like to make a quick typo fix of net.minidev in source-formatter, and also move net.minidev.* to shared-dependencies
Thanks for checking!

### CODE REVIEW

**Comment by lilylcl** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
Hi @lilylcl ,

I run "ant format-source-current-branch" locally and it passed. Also, I didn't change anything in that file.
This SF issue seems unrelated. 

Hey @Kvale1733 , could you please help me check again this PR, please?

Thanks!

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found. SF issue is unrelated.

**Comment by tinatian** [comment]
@jeffwu0724 As we talked, please resend.

**Comment by jeffwu0724** [comment]
upgrade the commit message and change the order of the commit to make more sense. 
The previous test result should be still good

**Comment by tinatian** [comment]
ci:forward:force

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137569

**Pull request closed without merging**
