### PR TITLE
LPS-175443 Remove immediate from ComponentBlacklistImplUpgradeStepRegistrator component

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions.

**Comment by MrJohn1911** [comment]
@tinatian can you review this? thanks!

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130651

**Pull request closed without merging**
