### PR TITLE
[TS] LPS-184974 | Alphabetical order of portlet class names impact in a module with two portlets using different values of javax.portlet.version

### PR DESCRIPTION
**Pull request by ricardocousolr**
(Continuation of https://github.com/liferay-core-infra/liferay-portal/pull/4667)

New pr implemented the alternative approached suggested in https://github.com/liferay-core-infra/liferay-portal/pull/4667#issuecomment-1578306071.

The new solution works with the module attached in [LPS-184974](https://issues.liferay.com/browse/LPS-184974) as well as with a module with a single portlet "without property "javax.portlet.version=3.0"." (cf https://github.com/liferay-core-infra/liferay-portal/pull/4667#issuecomment-1578306071). 

/cc @yuhai

### CODE REVIEW

**Review by yuhai — APPROVED** [review]
@dantewang, the fix refers to **Permission** and **Configuration templates** button generated url way, using `PortletURLImpl(HttpServletRequest , Portlet , Layout ,String , Copy)` to fix the issue. Otherwise, it will go to `PortletRequestImpl#getRenderParameters()` check and throw `UnsupportedOperationException("Requires 3.0 opt-in")`.

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@tinatian This fix follows the same pattern that other buttons use as [Hai's comment](https://github.com/liferay-core-infra/liferay-portal/pull/4719#pullrequestreview-1466515577) showed.

On the other hand, the use case mentioned in @ricardocousolr's previous pull should be wrong. As per portlet specification, the portlet API version is specified at the portlet application (`PortletApp`) level. When we use OSGi, we don't have portlet.xml so we put this info in each portlet, but all the portlets in the same portlet application (e.g. an OSGi bundle) should be of the same version. We should not implement any logic to be compatible with multi-version use case, but should either add a check to forbid such use case, or keep it as is just in case it breaks a lot of customer code.

**Comment by yuhai** [comment]
> @tinatian This fix follows the same pattern that other buttons use as [Hai's comment](https://github.com/liferay-core-infra/liferay-portal/pull/4719#pullrequestreview-1466515577) showed. So I approved the fix.
> 
> On the other hand, the use case mentioned in @ricardocousolr's previous pull should be wrong. As per [portlet specification](https://download.oracle.com/otndocs/jcp/portlet-3-final-spec/) 28.1.1, the portlet API version is specified at the portlet application (`PortletApp`) level. When we use OSGi, we don't have portlet.xml so we put this info in each portlet, but all the portlets in the same portlet application (e.g. an OSGi bundle) should be of the same version. We should not implement any logic to be compatible with multi-version use case, but should either add a check to forbid such use case, or keep it as is just in case it breaks a lot of customer code.

cc @ricardocousolr

**Comment by ricardocousolr** [comment]
Hi @dantewang, @yuhai,

Thanks for your review. About allowing multi-version portlets in the same OSGi module, it was asked in [PTR-3914](https://issues.liferay.com/browse/PTR-3914). Should we restart the discussion there?

**Comment by dantewang** [comment]
@ricardocousolr I think so. Although Liferay doesn't have any restriction on it, it doesn't have any mechanism to remember the portlet API version per portlet. So in fact one portlet application can have only one version.

**Pull request closed without merging**
