### PR TITLE
LPS-150565 Add configuration values

### PR DESCRIPTION
**Pull request by vendeltoreki**
Resending https://github.com/liferay-core-infra/liferay-portal/pull/2521 after rebase (conflict with: https://github.com/liferay/liferay-portal/commit/649d454b95182dbc857ce2fa6a1b69dbf7a06206).

@tinatian , @dantewang , @yuhai

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by vendeltoreki** [comment]
force-pushed buildLang commit to resolve conflict

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128002

**Pull request closed without merging**
