### PR TITLE
[Components with more than 1 service] LPS-192612 Refactor ModelListener components part II

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-192612

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud-acceptance

**Comment by vicnate5** [comment]
No regressions found.

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@MrJohn1911 SF issue:

```
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: /opt/dev/projects/github/liferay-portal/modules/apps/analytics/analytics-settings-impl/src/main/java/com/liferay/analytics/settings/internal/util/AnalyticsEntityModelRegistry.java expected:<...opyrightText: (c) 20[23] Liferay, Inc. https...> but was:<...opyrightText: (c) 20[00] Liferay, Inc. https...>
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:457)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:290)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-09/test-1-21/test-portal-source-format/7259/source-format-current-branch-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141448

**Pull request closed without merging**
