### PR TITLE
[Method References] LPS-162547 Convert method references to field references in module portal-cache*

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I convert method references to field references in module portal-cache*.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @catarineaguiar , Could you please help me check the test results ? Thanks!

**Comment by catarineaguiar** [comment]
@W2jx no regressions found.

**Comment by dantewang** [comment]
@shuyangzhou @tinatian Forwarding this one as all tests passed review and changes are direct replacements.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123211

**Pull request closed without merging**
