### PR TITLE
LPS-158153 Add new functionality to SystemProperties: get property with default value, and get array（These functions are needed when moving module framwork properties）

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , This PR includes two new methods and unit tests.

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:acceptance

**Comment by W2jx** [comment]
ci:test:acceptance

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Tina

**Comment by tinatian** [comment]
@W2jx Code looks good to me, wait for QA to scan test results.

Tina

**Comment by catarineaguiar** [comment]
@W2jx @tinatian no regressions found.

**Comment by dantewang** [comment]
@tinatian Just force pushed to resolve conflicts on sem ver.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by W2jx** [comment]
Hi @tinatian @dantewang , I'm very sorry, I want to add two new commits, which is the use of the new method in LPS-158153.

see #1190

**Pull request closed without merging**
