### PR TITLE
[Remove Stream/Optional usage] LPS-172105 modules: Layout Part 1 | 1-5

### PR DESCRIPTION
**Pull request by JanisZhang**
previous: https://github.com/liferay-core-infra/liferay-portal/pull/2931

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by JanisZhang** [comment]
Thanks @catarineaguiar !

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128438

**Pull request closed without merging**
