### PR TITLE
[Spring Beans] LPS-190557 Merge CustomJspBagRegistry interface and impl into Util in kernel

### PR DESCRIPTION
**Pull request by julschong**
CustomJSPRegistryUtil is used in util-taglib. Need to stay in kernel

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

@julschong Please, resolve conflicts.
Thanks!!

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
rebased and added breaking change message [8e748d8](https://github.com/liferay-core-infra/liferay-portal/pull/6189/commits/8e748d80181422bbfa7e5bd67f2a837847034978)

**Comment by julschong** [comment]
rebased

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
rebased to resolve conflict in portal-impl/test/unit/com/liferay/portal/deploy/hot/CustomJspBagRegistryUtilTest.java

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
no regression found

**Pull request closed without merging**
