### PR TITLE
LPS-147542 Remove scribe.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:acceptance-release

**Comment by tinatian** [comment]
@rafaprax Code looks good to me, waiting for QA to scan test results. 
Removing the whole package from portal-impl and portal-kernel is really nice and clean! Nice work!

Thanks.
Tina.

**Comment by koor4356** [comment]
Okay, thanks!

**Comment by koor4356** [comment]
@rafaprax 
This looks good, Thanks!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Thanks.
Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113818

**Comment by shuyangzhou** [comment]
Hmm, there is a conflict with Brian's upstream, please rebase.

**Comment by rafaprax** [comment]
already merged on master, see https://github.com/brianchandotcom/liferay-portal/pull/113818#issuecomment-1049181264

**Pull request closed without merging**
