### PR TITLE
LPS-188134 upgrade Guava to version to 32.0.1-jre

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

**After I dive deeper, if we want to keep using shared-dependencies, we would need to upgrade `group: "com.microsoft.graph", name: "microsoft-graph", version: "1.5.0"` to version 5.62.0 to make sure it can work in document-library-opener-onedrive-web. But doing in this way, since there is a huge version bump, we will have around 70 microsoft-graph needed to be change.**

Resent https://github.com/liferay-core-infra/liferay-portal/pull/4896.
As in the PR above, it caused a blocker(had been reverted) by using shared-dependencies. In this PR, I would like to change back to compileInclude and see how it will go.  https://liferay.atlassian.net/browse/LPS-191330

This is for ticket https://liferay.atlassian.net/browse/LPS-188134.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:online-editing

**Comment by kyle-miho** [comment]
No unique failures found

**Comment by jeffwu0724** [comment]
ci:test:online-editing

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
Some onedrive tests failed due to what looks like flakey issues: Rerunning here with these changes included since some tests will fail otherwise: https://github.com/brianchandotcom/liferay-portal/pull/138359#event-9917326061

**Comment by tinatian** [comment]
@jeffwu0724 Please rebase.

Thanks.
Tina

**Comment by jeffwu0724** [comment]
fixed code conflict in modules/test/jenkins-results-parser/build.gradle

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:online-editing

**Comment by catarineaguiar** [comment]
ci:test:lima

**Review by kmk142789 — APPROVED** [review]

**Pull request closed without merging**
