### PR TITLE
[FileInstall] LPS-144496 Part 2

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@tinatian The next PR will make other module.framework.properties.* to portal properties.

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
ci:test:app-servers

**Comment by vicnate5** [comment]
Test results look good so far, but I want to also run all the File Install tests on the app servers

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
