### PR TITLE
LPD-36033 Inline Jsr199JavaCompiler

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:jdk21-functional

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:8056949

**Comment by dantewang** [comment]
ci:test:environments

**Comment by dantewang** [comment]
ci:test:smoke

**Comment by dantewang** [comment]
ci:test:smoke

**Comment by dantewang** [comment]
ci:report:10032172

**Comment by dantewang** [comment]
ci:report:https://github.com/liferay-core-infra/liferay-portal/commit/9871253e80e2a8cc76037d5b127ec0efd6b07752

**Comment by dantewang** [comment]
ci:report:9871253

**Comment by dantewang** [comment]
> ### ❌ ci:test:smoke - 5 out of 8 jobs passed in 3 hours 20 minutes
> Click here for more details.
> ##### Test bundle downloads:
> * [liferay-portal-bundle-tomcat.tar.gz](https://files.liferay.com/private/bundles/test-1-38/jobs/test-portal-acceptance-pullrequest(master)/builds/11166/liferay-portal-bundle-tomcat.tar.gz) (mirrors: [dlc](http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-38/jobs/test-portal-acceptance-pullrequest(master)/builds/11166/liferay-portal-bundle-tomcat.tar.gz), [lax](http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-38/jobs/test-portal-acceptance-pullrequest(master)/builds/11166/liferay-portal-bundle-tomcat.tar.gz))

No unique in smoke.

**Comment by dantewang** [comment]
ci:test:environments

> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: [9871253](https://github.com/liferay-core-infra/liferay-portal/commit/9871253e80e2a8cc76037d5b127ec0efd6b07752).
> 
> Job Link: [generate-testray-csv](https://test-1-6.liferay.com/job/generate-testray-csv/143/)
> 
> Testray CSV Link: [testray-results-9871253.csv](https://test-1-6.liferay.com/userContent/jobs/generate-testray-csv/builds/143/testray-results-9871253.csv)

No unique failure in the environment run, the failures in the unique category are all flaky, which also fail upstream.

Re-running to examine the following "did not run" tests:

```
LocalFile.BlogsAdmin#CanAddEntryInAdmin
LocalFile.Permissions#CannotConfigureBlogsPortletAsGuestPG
LocalFile.StagingUsecaseWithVersioning#StagingPublishLast
LocalFile.SAML#SPInitiatedSSOSyncsUserAttributesFromIdPToSPDefaultMapping
LocalFile.CommerceAccelerators#InitializeNewMiniumSite
LocalFile.CommerceAccelerators#InitializeNewSpeedwellSite
LocalFile.SAML#SPInitiatedSSOSyncsUserAttributesFromIdPToSPDefaultMapping
LocalFile.MultiFactorAuthentication#LoginWithOTPEnabledByCompanyId
```

**Comment by dantewang** [comment]
ci:test:jdk21-functional

Examine the following tests:

```
LocalFile.CreateGETEndpointThatRetrieveSingleEntry#CanCreateEndpointWithAddedCurlyBraces
LocalFile.SFCommerceOrders#ViewListOfShipmentsInPlacedOrdersDetailsPage
LocalFile.DMFileEntry#CanDownloadWithSpecialCharactersInTitle
```

And the did not run tests.

**Comment by dantewang** [comment]
ci:report:11158699

**Comment by dantewang** [comment]
ci:report:11223237

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 11158699.
> 
> Job Link: [generate-testray-csv](https://test-1-28.liferay.com/job/generate-testray-csv/435/)
> 
> Testray CSV Link: [testray-results-11158699.csv](https://test-1-28.liferay.com/userContent/jobs/generate-testray-csv/builds/435/testray-results-11158699.csv)

No unique in environment tests.

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 11223237.
> 
> Job Link: [generate-testray-csv](https://test-1-31.liferay.com/job/generate-testray-csv/173/)
> 
> Testray CSV Link: [testray-results-11223237.csv](https://test-1-31.liferay.com/userContent/jobs/generate-testray-csv/builds/173/testray-results-11223237.csv)

The previous failed cases did not fail in the new run.

**Comment by tinatian** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/154554

**Pull request closed without merging**
