### PR TITLE
[Optional Reference] LPS-185393 Convert the Optional Dynamic Greedy references to static references using Snapshot in module portal-search-elasticsearch7-impl

### PR DESCRIPTION
**Pull request by W2jx**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4601

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(6/5 7:43)

**Comment by dantewang** [comment]
@W2jx Looks good to me, please send to search team for an extra review, thanks!

**Comment by W2jx** [comment]
> @W2jx Looks good to me, please send to search team for an extra review, thanks!

Ok, I will send it to the search team.

**Comment by lipusz** [comment]
https://github.com/liferay-search/liferay-portal/pull/946

**Pull request closed without merging**
