### PR TITLE
[Remove "immediate = true"  usage core-infrastructure-1]Lps 168390

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-168390

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
ci:forward

FYI @shuyangzhou

**Pull request closed without merging**
