### PR TITLE
LPD-39678 Performance issues deleting object entries

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
Hello,
the issue outlined in the [LPP](https://liferay.atlassian.net/browse/LPP-56254) is a performance bottleneck when deleting an object entry with many related entries set for cascade deletion. This problem also occurs in the master branch. Prior to my changes, deleting an entry with approximately 90,000 related entries in cascade was taking 3-4 hours. With the improvements, it now completes in about 7 minutes.

Here are the steps to reproduce:
1- Build and deploy workspaces/liferay-testray-workspace/client-extensions/liferay-testray-site-initializer
2- Build and deploy workspaces/liferay-testray-workspace/modules/testray-rest-api and workspaces/liferay-testray-workspace/modules/testray-rest-impl
3- Go to Control Panel -> Job Scheduler.
4- Add a new Job scheduler selecting the type: testray-import-results
5- Add a name and put this https://share.1password.com/s#cpK2FPatDwikkLV-Os0h06DSCR9Ox3bpj0bOkyBdjvs in the properties section
6- Save and click on Run Now button
7- Wait till the job scheduller change it status to Success
8- Perform the following query and get the ID from response body
curl -X 'GET' -u [test@liferay.com](mailto:test@liferay.com):test
'http://localhost:8080/o/c/builds/?fields=id'

9- Perform the following query replacing the PLACEHOLDER with the id obtained in the previous step
curl -X 'DELETE' -u [test@liferay.com](mailto:test@liferay.com):test
'http://localhost:8080/o/c/builds/batch'
-H 'accept: application/json'
-H 'Content-Type: application/json'
-d '[{"id":"PLACEHOLDER"}]'
10- Repeat the 8th step until it no longer returns an id (it takes up to 3~4 hours)

### CODE REVIEW

**Comment by vicnate5** [comment]
@pedro-oliveira446 Please add the [requested integration test](https://github.com/brianchandotcom/liferay-portal/pull/155833#issuecomment-2455472731) and resend.

**Comment by pedro-oliveira446** [comment]
Hey @vicnate5 ,

since this is a performance issue that only reproduces with over 30,000 entries, do I still need to create an integration test for it? Do we already have examples in the portal that cover similar cases?

**Comment by vicnate5** [comment]
@pedro-oliveira446 A test could be configured for more or less users right? We should still have the test to still see the full use case with smaller entry count, even if the performance issue will not be clear on small count.

Core Infra is building a new method to run integration tests with high load on our performance servers, that is where we could run it with the 30k entry load.

So my suggestion
1. Create the test with a smaller load that can be executed locally so we can verify the code logic
2. After, we can run the test on our performance servers with the entry count increased.

**Comment by pedro-oliveira446** [comment]
Ok @vicnate5,
I got it. Thank you!

**Pull request closed without merging**
