### PR TITLE
[Method References 2] LPS-176632 Convert method reference to ServiceTrackerMap in class CompositeFacetProcessor(module portal-search-solr8-impl)

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:search-solr

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(3/16 9:01)

**Comment by W2jx** [comment]
no conflicts(3/17 14:36)

**Comment by W2jx** [comment]
no conflicts(3/20 8:52)

**Comment by W2jx** [comment]
no conflicts(3/21 10:29)

**Comment by dantewang** [comment]
Same with the one of ES7.

**Pull request closed without merging**
