### PR TITLE
[Replace Non-Blocking Usage] LPS-199709

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace non-blocking ServiceProxyFactory usages in class `RawMetadataProcessorUtil`, `ExportImportLifecycleManagerUtil`, `ExportImportLifecycleListenerFactoryUtil`, `ExportImportLifecycleEventFactoryUtil` . Thanks.
https://liferay.atlassian.net/browse/LPS-199709

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142729

cc @shuyangzhou

**Pull request closed without merging**
