### PR TITLE
[Replace Non-Blocking Usage] LPS-199010 portal-kernel

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang, There's no need to set `Snapshot` as dynamic here because each of these classes has only one implementation. Thanks!
https://liferay.atlassian.net/browse/LPS-199010

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142345

**Pull request closed without merging**
