### PR TITLE
[Method References] LPS-160434 Replace method setPortlet with field _portlet in class extends BasePanelApp

### PR DESCRIPTION
**Pull request by dantewang**
cc @W2jx

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@dantewang no regressions found.

**Comment by tinatian** [comment]
@dantewang @W2jx I do not understand what the third and later commits do, it seems we do not need setPortlet, you should remove it directly, why you move it to a abstract class?

Tina

**Comment by dantewang** [comment]
@W2jx I think we can do this: completely remove `setPortlet` method. For `PanelAppWrapper`, no need to implement this method any more; for the other 2 classes, make them provide the portlet by using `PortletLocalService` with the portlet id, so they don't need `setPortlet` either.

**Comment by W2jx** [comment]
Hi @tinatian , the reason why we move setPortlet to a abstract class is that there are three subclasses that are not marked by '@Component', and can only assign values ​​to _portlet using the method setPortlet.

**Comment by W2jx** [comment]
@dantewang I will fix them.

**Pull request closed without merging**
