### PR TITLE
LPS-184766 Inline Equinox Http Servlet, Part 1

### PR DESCRIPTION
**Pull request by dantewang**
Inline and make SF happy only.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:smoke

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/505651//consoleText should be unique. Will look into it.

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:jdk11

**Comment by zhangyan0701** [comment]
Hi @dantewang There are some failures that seems unique in the ci:test:default, I tried some tests locally (including functional tests and integration tests), but none of them were reproducible. I am going to re-trigger ci test and will check the new results.

**Comment by zhangyan0701** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:jdk11

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 Could you check the test results? Thanks!

**Comment by dantewang** [comment]
@zhangyan0701 Thanks!

**Comment by dantewang** [comment]
ci:test:smoke

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@dantewang the copyright part needs to be changed according to the discussion with legal team

**Comment by dantewang** [comment]
@tinatian Yeah, I'll change that, clean up the commits, and resend.

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4708

**Pull request closed without merging**
