### PR TITLE
LPS-180401 Fix Fix hsql jdbc connection url

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
pushed semver

**Comment by tinatian** [comment]
@julschong Can you add a test?

Thanks.
Tina

**Comment by Kvale1733** [comment]
@julschong No regressions.

**Comment by tinatian** [comment]
@julschong Please add a test and resend.

Thanks.
Tina

**Pull request closed without merging**
