### PR TITLE
[Session Replication] Add liferay's tomcat session replication implementation and add functional test

### PR DESCRIPTION
**Pull request by julschong**
@tinatian 
This PR does not enable session replication by default.

It modifies `build-test.xml#cluster-session-replication` on functional tests to use our implementation.
`cluster-session-replication` task is only ran when testcase specifies:
```
cluster.session.replicated = "true"
```

and session replication is turned on on the server side when this property is set in portal-ext.properties

```
portlet.session.replicate.enabled=true
```

Note that https://github.com/liferay-core-infra/liferay-portal/pull/7235/commits/3130fc8ef362072838ffc5d07453a84769bb804a is a separate test fix. Basically, ClusterSamplePortlet is still referencing a removed css file causing it to throw some error message

## Functional test steps go like this:
- Deploy clustering sample module to both nodes

On Node 1, log in as default test user with localhost:8080:
- Add a widget page named "Session Replication Test"
- Add the CusterSampleSessionReplication Portlet
- Create new user test1@liferay.com

On Node 2, log into Test1 user on www.able.com:9080:
- Go to Node 2 widget page with url: `http://www.able.com:9080/web/guest/session-replication-test`

On Node 1, logged in as default test user on localhost:8080:
- Go to the widget page on `http://localhost:8080/web/guest/session-replication-test` and refresh the page so that portlet session information is updated on the page
- Copy the session ID and attribuite information on the portlet as `var sessionData` to be compared to later

On Node2, logged in as Test1 on www.able.com:9080:
- Go to widget page on `http://www.able.com:9080/web/guest/session-replication-test`
- Assert that portlet is showing the same session ID and attribute as our `sessionData` copied on Node1

Shutdown Node2
- Go to widget page on Node 1 using: `http://www.able.com:8080/web/guest/session-replication-test`
- Check that session data remains the same and that user is still logged in

Startup Node2
- Go to widget page on Node 2 using: `http://www.able.com:9080/web/guest/session-replication-test`
- Check that session data remains the same and that user is still logged in

cc. @vicnate5

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
@julschong 

1) For both of these steps "Check that session data remains the same and that user is still logged in", this is the test1 user? So test1 is logged in on both nodes? Just confirming since the steps only specifically state that the default admin is used on Node 1 ("On Node 1, logged in as default test user on localhost:8080")
1) What scenario is the old test `CanSessionReplicateBetweenNodes` covering that is different from the new test?

**Comment by julschong** [comment]
@vicnate5 thanks for reviewing

1. > For both of these steps "Check that session data remains the same and that user is still logged in", this is the test1 user? So test1 is logged in on both nodes? Just confirming since the steps only specifically state that the default admin is used on Node 1 ("On Node 1, logged in as default test user on localhost:8080")

localhost only logs in as default test user
able.com only logs in as new test1 user
The difference of enabling session replication is that we are now able to logging stay logged in even if we go on a different node from the node we logged in with.

so the restart part of this test is to make sure that:
- When node 2 shuts down, we are still logged in as test1 on node 1.
- When node 2 restarts, we are still logged in as test1 on node 2.

> What scenario is the old test CanSessionReplicateBetweenNodes covering that is different from the new test?

from looking at the old test, it generates a session with some data in the portlet on node 1 and check that it shows up on the other node.
it doesn't compare session ID or attributes. it also does not to restart test

**Comment by vicnate5** [comment]
@julschong Can we delete the original test? I do not see how it is testing something that isn't covered by the new one.

**Comment by julschong** [comment]
@vicnate5 I think before we merge this in, we need to evaluate the [acceptance-functional test result](https://github.com/julschong/liferay-portal/pull/1291#issuecomment-2221858946) here to make sure this has not broken anything. hard to tell unless I go in each test and follow the steps to see where went wrong.

**Comment by julschong** [comment]
removed old test [5469fcb](https://github.com/liferay-core-infra/liferay-portal/pull/7235/commits/5469fcb72eaf8dbeefefc571dbd5279262b7912d)

**Comment by julschong** [comment]
resubmitted https://github.com/liferay-core-infra/liferay-portal/pull/7254

**Pull request closed without merging**
