### PR TITLE
[Optional Reference] LPS-185138 Convert the Optional Dynamic Greedy references to ServiceTracker in class UpgradeRecorder

### PR DESCRIPTION
**Pull request by haydenzheng314**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4904
Ticket: https://liferay.atlassian.net/browse/LPS-185138

@tinatian @dantewang 
Use ServiceTracker as we talked.
Thanks.

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:upgrade

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by tinatian** [comment]
@LisztLiszt @dantewang Please see https://github.com/liferay-core-infra/liferay-portal/pull/5278. 

The service tracker should not be static as the creation of service tracker based on bundlecontext, bundlecontext will be changed when bundle stop and restart, but classloader won't change which means the loaded class and its static attributes won't change, this is the same thing as https://liferay.atlassian.net/browse/LPS-191404.

**Pull request closed without merging**
