### PR TITLE
LPS-160039 Optimize method findClass of class FreeMarkerBundleClassloader

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:acceptance

**Comment by guilhermedcamacho** [comment]
@catarineaguiar please help me check the results when available, thanks!

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
@catarineaguiar do we need to rerun acceptance, or CI team can still gather results from previous run?

**Comment by catarineaguiar** [comment]
@guilhermedcamacho I'm analyzing relevant results and if necessary I re-run acceptance.

**Comment by catarineaguiar** [comment]
ci:test:acceptance

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by guilhermedcamacho** [comment]
@shuyangzhou , this PR is ready for your review. Thanks!

**Comment by shuyangzhou** [comment]
@guilhermedcamacho there is some logic issue here.
For the bundle key, they are package name, make sure you create keys with a "." ending so that we won't do meaningless partial package matching.
This assert https://github.com/liferay-core-infra/liferay-portal/pull/1414/commits/3fdf98665ed9783bcf05f7584336efd9f83a9615#diff-36114b4ebde2965ae204dca34f758bbc0bfe52270f8e87ebd02476add05722d2R114 is wrong. Your TestClass.class.getName() matching should fail the last 3 bundle's package name, leading it to the first bundle, therefore this "findClass" call should throw exception. The production code is not doing right logic, and the test is asserting it in a wrong way.

**Pull request closed without merging**
