### PR TITLE
[Remove Stream/Optional usage] LPS-177345 Remove_Stream_usages_for_module_segments_test

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Dante,

Resent: https://github.com/liferay-core-infra/liferay-portal/pull/3896
This is for ticket https://issues.liferay.com/browse/LPS-177345.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:tango

**Comment by jeffwu0724** [comment]
ci:test:tango

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
