### PR TITLE
Commerce 4996 6 26

### PR DESCRIPTION
**Pull request by slnn**
Rename and sort according to BChan's comments

https://github.com/brianchandotcom/liferay-portal/pull/136735#issuecomment-1601962134
https://github.com/brianchandotcom/liferay-portal/pull/136790#issuecomment-1603687668

/cc @dsitu

### CODE REVIEW

**Comment by slnn** [comment]
ci:forward:force

**Comment by slnn** [comment]
ci:stop

**Comment by slnn** [comment]
This change is only about SampleSQLBuilder,  for the tests, we can just focus on the JUnit test SampleSQLBuilderTest and the SF tests.

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
