### PR TITLE
LPS-154855 remove properties: module.framework.resolver.revision.batch.size

### PR DESCRIPTION
**Pull request by W2jx**
@tinatian @dantewang

@GinsonRen Could you please help me test the startup test? Thanks!

### CODE REVIEW

**Comment by GinsonRen** [comment]
@111Anna Could you please take care of this?

**Comment by 111Anna** [comment]
@tinatian @dantewang @GinsonRen @W2jx 

I tested the startup testing on my laptop, here are results
startup:
Portal Version | Git Id | Average Startup Time | Percentage（%）
-- | -- | -- | --
BaseLine | b86626c | 23746.2ms | -
PR-852 | - | 23411.8ms | 1.4%

**Comment by dantewang** [comment]
@W2jx Please create a sub task and update this PR.

**Comment by W2jx** [comment]
The LPS ID has been updated.

**Comment by tinatian** [comment]
@W2jx Code conflicts, please rebase. Also, please add the reason you removed this property in the commit message.

Please resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
