### PR TITLE
[TS] LPS-194611

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Requested by Tina [here](https://github.com/liferay-core-infra/liferay-portal/pull/5356#issuecomment-1692609462).

**Comment by catarineaguiar** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:sf

**Pull request closed without merging**
