### PR TITLE
LPS-145050 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian @julschong Regression found in Document PDF Processor. It is only occurring on this PR.

Steps used to reproduce locally:
1. Go to Product Menu > Content & Data > Documents and Media
2. Go to Plus icon > File Upload
3. Select File
4. Upload this PDF file https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/dependencies/large_file.pdf
5. Publish
6. Click on card to open the uploaded PDF

**Expected Result:**
File preview is rendered

**Actual Result:**
File shows "No Preview Available" and WARN thrown in liferay console
```
2022-01-27 18:27:16.093 WARN  [liferay/document_library_pdf_processor-2][PDFProcessorImpl:819] Unable to process 42546 large_file
2022-01-27 18:27:16.094 WARN  [liferay/document_library_pdf_processor-2][BaseProcessorMessageListener:40] Unable to process file version 42546
```
Automation test: https://testray.liferay.com/home/-/testray/case_results/1604064502

**Pull request closed without merging**
