### PR TITLE
LPS-164640 more SnakeYAML to shared-dependencies

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-164640.
I am trying to move snakeYAML to shared-dependencies, so that we can get rid of too many use of compileInclude.

### CODE REVIEW

**Comment by Kvale1733** [comment]
@jeffwu0724 Regression in

rest-builder-jdk8/0/0
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/yaml/snakeyaml/error/MarkedYAMLException
     [exec] 	at com.liferay.portal.tools.rest.builder.RESTBuilder.<init>(RESTBuilder.java:145)
     [exec] 	at com.liferay.portal.tools.rest.builder.RESTBuilder.<init>(RESTBuilder.java:165)
     [exec] 	at com.liferay.portal.tools.rest.builder.RESTBuilder.main(RESTBuilder.java:114)
     [exec] Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.error.MarkedYAMLException
     [exec] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [exec] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [exec] 	... 3 more
     [exec] 
     [exec] > Task :apps:analytics:analytics-dxp-entity-rest-impl:buildREST FAILED
```
[Log](https://testray.liferay.com/reports/production/logs/2022-10/test-1-35/test-portal-acceptance-pullrequest(master)/2739/rest-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
Hey @Kvale1733 ,

May I ask how can I reproduce this locally, please?
Thanks!

**Comment by Kvale1733** [comment]
I'll take a look on how to reproduce this locally.

**Comment by jeffwu0724** [comment]
Thanks @Kvale1733 , I guess I have figured out how to fix this, I will send a new PR later. 
Really appreciate your help!

**Pull request closed without merging**
