### PR TITLE
[Urgent][Security Bugs]LPD-1948 patch freemarker wtih 2.3.30

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

Resend: https://github.com/liferay-core-infra/liferay-portal/pull/6639
This is for ticket https://liferay.atlassian.net/browse/LPD-1948.
cc: @RenanUmV

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:report:2539852227

**Comment by jeffwu0724** [comment]
no unique regression found

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/147301

**Pull request closed without merging**
