### PR TITLE
[Component with its own class name as service type] LPS-197867 Refactor components from dynamic-data-mapping modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-197867

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:forms

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Review by rafaprax — CHANGES_REQUESTED** [review]
@MrJohn1911, the last two commits should be merged into only one.

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
In the last push, I just merged two commits into one.

CC: @dantewang @tinatian

**Review by rafaprax — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
