### PR TITLE
[PowerMock] LPS 151992

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove powermock usages related to `BaseVLDAPTestCase` present in ` modules/dxp...vldap-server-test`. 

https://issues.liferay.com/browse/LPS-151992 

Thanks
Janis.

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @zhangyan0701 , Could you please help me to scan the test result?  Thx

**Comment by zhangyan0701** [comment]
Hi @JanisZhang 

All failures are unrelated. They should be fluke.

**Comment by JanisZhang** [comment]
Thanks! @zhangyan0701

**Review by dantewang — APPROVED** [review]
@tinatian

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116936

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
