### PR TITLE
LPS-177347 Fix "[SqlExceptionHelper:142] Table 'lportal.User_x_57882' doesn't exist" error priotitizing the company deletion in the DataGuard deletion process

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-177347

Hi @tinatian, 

It is a fix for a weird issue on the master that just happens in the test context. After some investigation, I found out that tests that create Company, and let the DataGuard strategy delete the leftovers, are generating an error in the log because the system groups are being deleted before the company causing the company deletion to stop abruptly in this line, [here](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/CompanyLocalServiceImpl.java#L1270).

As company deletion is a complex process and some entities must exist at this moment (like system groups and default user), in this fix, I'm prioritizing the Company deletion over other entities in the deletion leftovers process of the DataGuard Rule.

Another solution would be to change the delete Company process to handle this situation but I didn't take that approach as it would change production code because of a situation that only occurs in testing.

Thanks in advance

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:workflow

**Comment by rafaprax** [comment]
ci:test:commerce

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:workflow

**Comment by rafaprax** [comment]
Hi all, I'm just for the test to finish to change the LPS in the commits. It should the LPS-177347 instead

**Comment by Kvale1733** [comment]
@rafaprax No regressions found.

**Comment by rafaprax** [comment]
Hi all, I just fixed the LPS in the commits. No logic changes. Thx

**Comment by tinatian** [comment]
@rafaprax Could you please fix the failed tests to make sure them delete company manually? Dataguard is just the last resort to protect the data, if you create a company in a test, you should also manually delete it.

I do not want to make Dataguard that smart to deal with things like this, as tables are always related to each other, we can not deal all the cases in Dataguard, or else Dataguard will be too complex to maintain.

Please resend.

Thanks.
Tina.

**Pull request closed without merging**
