### PR TITLE
Lpd 28467 6 19

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:help

**Comment by tinatian** [comment]
ci:test:core-functional

**Comment by tinatian** [comment]
ci:test:startup

**Comment by tinatian** [comment]
@JerryAdrianoo Please run a diff on startup.

FYI @slnn 
Thanks!

**Comment by JerryAdrianoo** [comment]
Hey @tinatian see the results below. I also put the other data in this [spreadsheet](https://docs.google.com/spreadsheets/d/1UblPPPyNLae2rMSY5dhu54PrfgKvSQO8GPxJ622CNBo/edit?usp=sharing) for a better visualization.
Branch| Startup Time (ms)(without  default HSQL data)  Cold start | Startup Time (ms)(without  default HSQL data) Hot start | Average Startup Time (ms)(without default HSQL data)  Hot start | Percent of  Average Startup Time | Shutdown Time (ms)(without default HSQL data)   Cold start | Shutdown Time (ms)(without default HSQL data)  Hot start | AverageShutdownTime (ms)(without default HSQL data)  Hot start
-- | -- | -- | -- | -- | -- | -- | --
Before LPD-28467 | **40,922** | 16,667 | | | **2,693** | 1,917
|  | | 16,690 | | | | 1,978
|  | | 16,551 | | | | 2,055
 | | | 16,743 | | | | 1,976
 | | | 16,845 |**16,700** | | | 1,986 | **1,980**
-- | -- | -- | -- | -- | -- | -- | --
After LPD-28467 | **42,443** | 16,569 | | | **2693** | 2053
|  | | 16,761 | | | | 2,058
|  | | 16,236 | | | | 1,967
|  | | 16,702 | | | | 1,921
| | |  15,915 |**16,502** |  **-1.19**% | | 1,947 | **1989**


Everything looks fine, I didn't notice any change with your changes.

**Comment by tinatian** [comment]
ci:test:startup

**Comment by tinatian** [comment]
ci:report:22035683

**Comment by tinatian** [comment]
ci:report:22039489

**Comment by JerryAdrianoo** [comment]
Hey @tinatian for more details from this test, see: [spreadsheet](https://docs.google.com/spreadsheets/d/1UblPPPyNLae2rMSY5dhu54PrfgKvSQO8GPxJ622CNBo/edit?usp=sharing) 
Branch| Startup Time (ms)(without  default HSQL data)  Cold start | Startup Time (ms)(without  default HSQL data) Hot start | Average Startup Time (ms)(without default HSQL data)  Hot start | Percent of Average Startup Time | Shutdown Time (ms)(without default HSQL data)   Cold start | Shutdown Time (ms)(without default HSQL data)  Hot start | Average Shutdown Time (ms)(without default HSQL data)  Hot start
-- | -- | -- | -- | -- | -- | -- | --
Before LPD-28467 | **43,152** | 16,776 | | | **2,677** | 1,987
|  | | 16,235 | | | | 1,909
|  | | 16,166 | | | | 1,985
 | | | 16,899 | | | | 1,992
 | | | 16,876 |**16,629** | | | 1,990 | **1,987**
-- | -- | -- | -- | -- | -- | -- | --
After LPD-28467 | **41,330** | 15,940 | | | **2,737** | 1,978
|  | | 15,947 | | | | 2,001
|  | | 16,734 | | | | 1,909
|  | | 16,861 | | | | 1,950
| | |  16,617 |**16,433** |  **-1.19**% | | 1,932 | **1,953**

The results seem the same as before. Please let me know if you need something else.

**Comment by tinatian** [comment]
ci:report:22730867

**Comment by tinatian** [comment]
No unique failure from the report

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/151675

**Pull request closed without merging**
