### PR TITLE
[Equinox Http] LPS-196986 Avoid actually using HttpServiceRuntime

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
No unique failures in relevant tests. Will run ci:test to make sure there is no regressions.

**Comment by zhangyan0701** [comment]
ci:test

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:forward:force

**Comment by dantewang** [comment]
@shuyangzhou Manually rebased and sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/141982

**Pull request closed without merging**
