### PR TITLE
[TS] LPD-15247

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__ <https://liferay.atlassian.net/browse/LPD-15247>

See previous pull request: <https://github.com/liferay-core-infra/liferay-portal/pull/6823>. I found the cause of the test failure, which was that `locale.default.request` needed to be set in `I18nFilterTest`. The tests now enable this portal property if a `defaultLocale` argument is provided (which `I18nFilter` only ever considers when `locale.default.request=true`).

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:2557572334

**Comment by tinatian** [comment]
@kevhlee Still unique failure reported.

Please check.

Thanks.
Tina.

**Comment by kevhlee** [comment]
Hi @tinatian, I believe the unique test failure is unrelated. Also, this seems to be a failure that occurs in other PRs as well:

- <https://testray.liferay.com/home/-/testray/case_results/2555588142>
- <https://testray.liferay.com/home/-/testray/case_results/2555532754>

**Comment by tinatian** [comment]
@kevhlee As we talked, please resend.

Tina.

**Pull request closed without merging**
