### PR TITLE
[Remove Stream/Optional usage] LPS-171708 test_remove_usage_of_stream_on_object_rest_impl

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

fixed the bugs mentioned in https://github.com/liferay-core-infra/liferay-portal/pull/2924#issuecomment-1376128419
Resend https://github.com/liferay-core-infra/liferay-portal/pull/2924
This is for ticket https://issues.liferay.com/browse/LPS-171708.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:object

**Comment by jeffwu0724** [comment]
ci:test:headless

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found. Only a semver issue
```
 [exec] > Task :apps:object:object-rest-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.object.rest.dto.v1_0.util              MAJOR      1.0.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.object.rest.dto.v1_0.util.CreatorUtil
     [exec] 		-   method     toCreator(com.liferay.portal.kernel.util.Portal,java.util.Optional,com.liferay.portal.kernel.model.User)
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.headless.delivery.dto.v1_0.Creator
     [exec] 		+   method     toCreator(com.liferay.portal.kernel.util.Portal,javax.ws.rs.core.UriInfo,com.liferay.portal.kernel.model.User)
     [exec] 			+   access     static
     [exec] 			+   return     com.liferay.headless.delivery.dto.v1_0.Creator
     [exec] [Baseline Warning] Bundle Version Change Recommended: 12.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-39/test-portal-acceptance-pullrequest(master)/2282/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
force push to fix semantic version issue, the test result should be good enough

**Comment by dantewang** [comment]
SF, see https://github.com/liferay-core-infra/liferay-portal/pull/3041

**Pull request closed without merging**
