### PR TITLE
[Component with its own class name as service type] LPS-199636 Refactor components from commerce, frontend and workflow modules

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-199636](https://liferay.atlassian.net/browse/LPS-199636)

Previous Pull: https://github.com/rafaprax/liferay-portal/pull/1310

cc: @MarinhoFeliphe

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:workflow

**Comment by RenanUmV** [comment]
ci:test:commerce

**Comment by RenanUmV** [comment]
ci:test:frontend-data-set

**Comment by catarineaguiar** [comment]
no regressions found

**Review by rafaprax — APPROVED** [review]

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@RenanUmV @rafaprax Code looks good to me. Just one thing, https://github.com/liferay-core-infra/liferay-portal/pull/6064/commits/6d3e72b15d6af17b3340d7601eaa932574276c09 this class is in an exported package, so it should affect the version and be recorded as breaking change. Or maybe get confirmation from Commerce team. Please update the commit if we can remove it.

**Comment by dantewang** [comment]
@RenanUmV I'll close this for now. Please resend. If the new PR only contains commit message change, no need to trigger tests, we can just review and forward it.

**Comment by RenanUmV** [comment]
resent here: https://github.com/liferay-core-infra/liferay-portal/pull/6255

**Pull request closed without merging**
