### PR TITLE
[JDK on Release Test] LPD-32407 Use jdk21_zulu instead of jdk8 and jdk17_open instead of jdk11_open on portal-release modules-integration-*-jdk test batches

### PR DESCRIPTION
**Pull request by julschong**
Ticket: https://liferay.atlassian.net/browse/LPD-32407
Status: Job summary generated: https://test-1-1.liferay.com/userContent/jobs/test-portal-release/builds/4452/job-summary/index.html

Thank you @brittneyq for helping us generate the job summary!

### CODE REVIEW

**Comment by vicnate5** [comment]
@julschong Need to fix `modules-integration-bundle-sqlserver*-jdk8`

Just remove the jdk8 part `modules-integration-bundle-sqlserver*`

**Comment by julschong** [comment]
> 968cf83

@vicnate5 see [968cf83](https://github.com/liferay-core-infra/liferay-portal/pull/7293/commits/968cf83943d32b7f583d6e788665580c2c36be1b)

**Comment by julschong** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
Looks good @tinatian

**Comment by julschong** [comment]
rebased to brian's master

**Comment by julschong** [comment]
this is ready to go. job summary generated is good https://test-1-1.liferay.com/userContent/jobs/test-portal-release/builds/4452/job-summary/index.html

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/152714

**Pull request closed without merging**
