### PR TITLE
[Bug Fix]LPS-127157

### PR DESCRIPTION
**Pull request by tinatian**
This is a resend of https://github.com/shuyangzhou/liferay-portal/pull/10395

Tina

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
ci:test:echo

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test result.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/109868

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
