### PR TITLE
[Test Fix] LPD-40710 Explicitly filter using database.types and app.server.typoes on upstream-dxp

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:upstream-dxp:dryrun

**Comment by julschong** [comment]
change is successful in job summary

**Comment by julschong** [comment]
@tinatian forwarding this. this will fix the SetupWizard mismatch environment issue

**Comment by julschong** [comment]
ci:forward

**Comment by julschong** [comment]
canceled forward, pending review

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
