### PR TITLE
[System Properties] LPS-165265 Move some properties that moduleFramework needs during init | part 2

### PR DESCRIPTION
**Pull request by W2jx**
Detail: https://github.com/liferay-core-infra/liferay-portal/pull/2505

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@W2jx semver error:

```
  [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/static/portal-configuration/portal-configuration-persistence-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.portal.configuration.persistence       MINOR      1.1.0      1.1.0      1.2.0      VERSION INCREASE REQUIRED
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-26/test-portal-acceptance-pullrequest(master)/6085/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

regression found:

```
     [exec] com.liferay.portal.lpkg.deployer.controller.LPKGControllerTest > testLPKGControllerDeploy FAILED
     [exec]     java.nio.file.NoSuchFileException: /opt/dev/projects/github/liferay-portal/modules/apps/static/portal-lpkg-deployer/portal-lpkg-deployer-test/liferay/osgi/marketplace/Liferay Controller Test.lpkg
     [exec]         at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
     [exec]         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
     [exec]         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-26/test-portal-acceptance-pullrequest(master)/6085/lpkg-controller-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
Force-Push is just to resolve the conflict about files ```
portal-impl/bnd.bnd
portal-impl/src/com/liferay/portal/util/packageinfo
portal-kernel/src/com/liferay/portal/kernel/util/packageinfo
```

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:help

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
Hi @catarineaguiar , I ran test `com.liferay.portal.lpkg.deployer.controller.LPKGControllerTest > testLPKGControllerDeploy` on the mster branch, and the same error occurred. Could you please help me check it? Thanks!

**Comment by catarineaguiar** [comment]
@W2jx the test is failling on master. It's flaky. Thanks for checking.

no regressions found

**Comment by W2jx** [comment]
Force-Push is just to rebase and resolve conflicts about files `portal-impl/bnd.bnd、portal-kernel/bnd.bnd` .

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(2022/12/5 13:18)

**Comment by catarineaguiar** [comment]
@W2jx possible regression:

```
[exec] com.liferay.portal.lpkg.deployer.controller.test.LPKGControllerVerifyTest > testLPKGController FAILED
     [exec]     java.lang.AssertionError: No JAR bundle found
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
     [exec]     	at org.junit.Assert.assertNotNull(Assert.java:713)
     [exec]     	at com.liferay.portal.lpkg.deployer.controller.test.LPKGControllerVerifyTest.testLPKGController(LPKGControllerVerifyTest.java:77)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
     [exec] There were failing tests. See the report at: file:///opt/dev/projects/github/liferay-portal/modules/apps/static/portal-lpkg-deployer/portal-lpkg-deployer-test/build/reports/tests/testIntegration/index.html
     [exec] 
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-29/test-portal-acceptance-pullrequest(master)/5638/lpkg-controller-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
Thank you, I will test it locally.

**Comment by catarineaguiar** [comment]
@W2jx confirmed, the error is happening on master. Thanks for checking.

**Comment by W2jx** [comment]
Thank you @catarineaguiar .

**Comment by W2jx** [comment]
no conflicts(12/9 9:53)

**Comment by W2jx** [comment]
Force-Push is just to resolve conflicts and rebase.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2706

**Pull request closed without merging**
