### PR TITLE
LPS-186374 Move PortalInstances from portal-impl to portal-kernel.

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, @tinatian, the pr is based on the requirement from https://github.com/liferay-core-infra/liferay-portal/pull/4666#issuecomment-1572928101

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@yuhai semver error:

```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/portal/portal-db-partition-test-util] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.portal.db.partition.test.util          MINOR      1.0.0      1.0.0      1.1.0      VERSION INCREASE REQUIRED
     [exec]     	<   class      com.liferay.portal.db.partition.test.util.BaseDBPartitionTestCase
     [exec]     		+   method     removeDBPartitions(long[],boolean)
     [exec]     			+   access     protected
     [exec]     			+   access     static
     [exec]     			+   return     void
     [exec]         at org.junit.Assert.fail(Assert.java:88)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-06/test-1-36/test-portal-acceptance-pullrequest(master)/3709/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by yuhai** [comment]
@catarineaguiar, I noticed you add QA Passed label. Yes, the current [semver error](https://github.com/liferay-core-infra/liferay-portal/pull/4707#issuecomment-1577354698) is not related with the pr.

**Comment by catarineaguiar** [comment]
@yuhai as the semver error is not related, please resolve conflicts and it will be okay.

**Comment by tinatian** [comment]
@yuhai If you run ci:test:license, you will get a compile failure as we have code there referencing PortalInstances. We can not modify the code in release repo as it may case hot fix build failed, we have similar issue before, Julius will add a support to release repo and once that merged in, I will let you know how to use it.

Close this for now.

Tina.

**Pull request closed without merging**
