### PR TITLE
LPS-166684 Remove "immediate = true" from Portal IV

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@MrJohn1911 all startup tests failed due to:

```
     [exec] com.liferay.portal.osgi.debug.declarative.service.test.DeclarativeServiceDependencyManagerTest > testDeclarativeServiceDependencyManagerResolvedDependencies STARTED
[beanshell] 2022-11-29 19:49:29.698 INFO  [com.liferay.portal.osgi.debug.declarative.service.test-executor-thread][BundleStartStopLogger:77] STARTED com.liferay.portal.osgi.debug.declarative.service.test.bundle_1.0.0 [1513]
     [exec] 
     [exec] com.liferay.portal.osgi.debug.declarative.service.test.DeclarativeServiceDependencyManagerTest > testDeclarativeServiceDependencyManagerResolvedDependencies FAILED
     [exec]     org.junit.ComparisonFailure: expected:<[All declarative service components are satisfied]> but was:<[
     [exec]     Bundle {id: 226, name: com.liferay.portal.monitoring, version: 9.0.17}
     [exec]     	Declarative Service {id: 633, name: com.liferay.portal.monitoring.internal.messaging.MonitoringMessageListener, unsatisfied references: 
     [exec]     		{name: Destination, target: (destination.name=liferay/monitoring)}
     [exec]     	}
     [exec]     	Declarative Service {id: 632, name: com.liferay.portal.monitoring.internal.jmx.MonitoringConfigurationManager, unsatisfied references: 
     [exec]     		{name: _monitoringControl, target: null}
     [exec]     	}]>
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:117)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
     [exec]     	at com.liferay.portal.osgi.debug.declarative.service.test.DeclarativeServiceDependencyManagerTest.testDeclarativeServiceDependencyManagerResolvedDependencies(DeclarativeServiceDependencyManagerTest.java:118)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-29/test-portal-acceptance-pullrequest(master)/5592/modules-integration-mysql57-jdk8/0/8/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:export-import

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Comment by MrJohn1911** [comment]
Hey @shuyangzhou can you review this pull? thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127384

**Pull request closed without merging**
