### PR TITLE
[Components with more than 1 service] LPS-183527 Refactor ImporterCapability components from Echo and Staging modules

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-183527](https://issues.liferay.com/browse/LPS-183527)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:stop

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:staging

**Comment by RenanUmV** [comment]
ci:test:echo

**Comment by chaowang-123** [comment]
Hi @slnn, the failure is not related to this PR, please add QA Passed label.

**Review by rafaprax — APPROVED** [review]

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/134377

**Pull request closed without merging**
