### PR TITLE
[Method References] LPS-162552 Convert method references to field references in modules portal-background-task-service、portal-rules-engine-wiring、portal-lock-service

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I convert method references to field references in modules portal-background-task-service、portal-rules-engine-wiring、portal-lock-service.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @catarineaguiar , Could you please help me check the test results ? Thanks!

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
@shuyangzhou @tinatian Forwarding this one as all tests passed and changes are direct replacements.
cc @catarineaguiar

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
