### PR TITLE
[System Properties][Part Two] LPS-158208 Add new functionality to SystemProperties: resolve property references

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I resend this task,  I add a new method and unit test in this pr.
depends on LPS-158206(https://github.com/liferay-core-infra/liferay-portal/pull/1387)

Detail: https://github.com/liferay-core-infra/liferay-portal/pull/1263

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(10:41 PM)

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results when they finish ? Thanks!

**Comment by W2jx** [comment]
no conflicts(6:50 AM)

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
@zhangyan0701 Thank you.

**Comment by W2jx** [comment]
no conflicts(7:10 PM)

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/1448

**Pull request closed without merging**
