### PR TITLE
LPS-184249 Background Task clean up 

### PR DESCRIPTION
**Pull request by dantewang**
Note: I kept BackgroundTaskClusterMasterTokenTransitionListener untouched, but I think we can also remove it, if we accept that the stale background task is not cleaned up immediately when master node transition happens.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:clustering

**Comment by dantewang** [comment]
@tinatian This pull is based on the idea of giving threads unique names so that we can record the thread name in background task context map and compare it with existing threads to identify whether an IN_PROGRESS task is stale.

Some notes:
- I modified some destination APIs to make it possible for caller to append a suffix to the thread name: https://github.com/liferay-core-infra/liferay-portal/pull/4514/commits/94205b2131358a69b9c2b0ccfb2878a9dbcedf1d
- I kept the code to get the thread list for every IN_PROGRESS background task for concerns of possible race condition, but I'm not 100% sure for now: https://github.com/liferay-core-infra/liferay-portal/pull/4514/commits/8a68a55706779eb2a8fc7dd90f8f32cf4f51f56c
- I kept BackgroundTaskClusterMasterTokenTransitionListener untouched, but I think we can also remove it, if we accept that the stale background task is not cleaned up immediately when master node transition happens.

**Comment by tinatian** [comment]
@dantewang Please slack me when you are available, I need to have a talk with you about this.

Thanks.
Tina

**Comment by Kvale1733** [comment]
@dantewang Unable to execute background task error appears in several tests such as 


1)

com.liferay.wiki.internal.exportimport.test.WikiExportImportTest
```
[exec] com.liferay.wiki.internal.exportimport.test.WikiExportImportTest > testUpdateLastPublishDate STARTED
[beanshell] 2023-05-11 08:41:25.968 ERROR [com.liferay.wiki.test-executor-thread][BackgroundTaskMessageListener:176] Unable to execute background task
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.exportimport.internal.background.task.PortletStagingBackgroundTaskExecutor.execute(PortletStagingBackgroundTaskExecutor.java:117) ~[?:?]
[beanshell] 	at com.liferay.portal.background.task.internal.SerialBackgroundTaskExecutor.execute(SerialBackgroundTaskExecutor.java:63) ~[?:?]
[beanshell] 	at com.liferay.portal.kernel.backgroundtask.DelegatingBackgroundTaskExecutor.execute(DelegatingBackgroundTaskExecutor.java:41) ~[portal-kernel.jar:?]
```
[Log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-25/test-portal-acceptance-pullrequest(master)/941/modules-integration-mysql57-jdk8/4/9/jenkins-console.txt.gz?authuser=0)

This is also affecting staging tests.

Steps to reproduce 
1. Go to Publishing > Staging
2. Select Local Live
3. Click Select All for Staged Content
4. Click Save

Expected Results: Current content is published in a successful staging process
Actual Results: The process fails and the following appears in the console
```
2023-05-11 16:19:46.642 ERROR [liferay/background_task-4-3abf0f44-e000-a6c1-4fc2-b2f726075172][BackgroundTaskMessageListener:176] Unable to execute background task
java.lang.NullPointerException: null
	at com.liferay.exportimport.internal.background.task.LayoutStagingBackgroundTaskExecutor.execute(LayoutStagingBackgroundTaskExecutor.java:84) ~[?:?]
	at com.liferay.portal.background.task.internal.SerialBackgroundTaskExecutor.execute(SerialBackgroundTaskExecutor.java:63) ~[?:?]
	at com.liferay.portal.kernel.backgroundtask.DelegatingBackgroundTaskExecutor.execute(DelegatingBackgroundTaskExecutor.java:41) ~[portal-kernel.jar:?]
```

2 ) Semver issue
```
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.kernel.backgroundtask.constants MINOR      1.1.0      1.1.0      1.2.0      VERSION INCREASE REQUIRED
[beanshell] 	<   class      com.liferay.portal.kernel.backgroundtask.constants.BackgroundTaskConstants
[beanshell] 		+   field      BACKGROUND_TASK_THREAD_NAME
[beanshell] 			+   access     final
[beanshell] 			+   access     static
[beanshell] 			+   constant   backgroundTaskThreadName
[beanshell] 			+   return     java.lang.String
[beanshell] * com.liferay.portal.kernel.messaging                MINOR      15.0.0     15.0.0     15.1.0     VERSION INCREASE REQUIRED
[beanshell] 	<   class      com.liferay.portal.kernel.messaging.DestinationConfiguration
[beanshell] 		+   method     getThreadNameSuffixSupplier()
[beanshell] 			+   return     java.util.function.Supplier
[beanshell] 		+   method     setThreadNameSuffixSupplier(java.util.function.Supplier)
[beanshell] 			+   return     void
[beanshell] 
[stopwatch] [run.batch.test.action: 7.143 sec]
```
[Log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-25/test-portal-acceptance-pullrequest(master)/941/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
