### PR TITLE
LPS-161510 Remove stream usage in DDMFormValidatorImpl

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:forms

**Comment by rafaprax** [comment]
Hey @catarineaguiar, can you please help to scan the test results when they are ready? Thx

**Comment by catarineaguiar** [comment]
@rafaprax no regressions found.

**Comment by rafaprax** [comment]
Hey @shuyangzhou, this pr is ready for your review. Thx

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122459

**Pull request closed without merging**
