### PR TITLE
LPS-161944 Fix false positives in ServicePreActionTest test due to the usage of removeResourcePermissions and addResourcePermissions methods of ResourcePermissionLocalService - LPS-145396 Subtask

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
This PR fixes false positives in ServicePreActionTest test detected in the DataGuardTestRule test that I am implementing in [LPS-145396](https://issues.liferay.com/browse/LPS-145396)

The false positives were detected in https://github.com/liferay-core-infra/liferay-portal/pull/1020, for more information see this comment https://github.com/liferay-core-infra/liferay-portal/pull/1020#issuecomment-1171982668

Once this PR is merged I will resend a new PR of [LPS-145396](https://issues.liferay.com/browse/LPS-145396) with the updated ResourcePermission deletion tests in DataGuardTestRule.

To solve the false positives:

- I am creating a new company to execute all the ServicePreActionTest tests there and deleting once all the tests are executed. The `_resourcePermissionLocalService.removeResourcePermissions` will update the ResourcePermission entries of the company we have created, so we will avoid modifying ResourcePermissions unrelated to this test. (see https://github.com/liferay-core-infra/liferay-portal/commit/245b5062bdb133f5f98a73cdbeca1930c9155b94 )
- I am avoiding using `_resourcePermissionLocalService.addResourcePermissions` because it affects all the companies, I am updating the ResourcePermissions of all Layouts of the company instead. (see https://github.com/liferay-core-infra/liferay-portal/commit/d51d1774dfeabf4df45e10696ffd3eea9a041379)

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@jorgediaz-lr possible regression, can you check, please?

```
[exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':dxp:apps:search-experiences:search-experiences-web:packageRunTest'.
     [exec] > Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dxp:apps:search-experiences:search-experiences-web:packageRunTest'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$3(ExecuteActionsTaskExecuter.java:186)
     [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:268)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)
     [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-31/test-portal-acceptance-pullrequest(master)/4826/js-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jorgediaz-lr** [comment]
Hi @catarineaguiar 

The failing error is unrelated, I am only changing the backend test ServicePreActionTest and the error: **org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dxp:apps:search-experiences:search-experiences-web:packageRunTest'.** is a frontend issue:

```
 [exec] > Task :dxp:apps:search-experiences:search-experiences-web:packageRunTest FAILED
     [exec] FAIL test/js/edit_sxp_blueprint/EditSXPBlueprintForm.js (23.545s)
     [exec]   ??? EditSXPBlueprintForm ??? renders the edit blueprint form without errors
     [exec] 
     [exec]     : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:
     [exec] 
     [exec]       78 | 	global.URL.createObjectURL = jest.fn();
     [exec]       79 | 
     [exec]     > 80 | 	it('renders the edit blueprint form without errors', async () => {
     [exec]          | 	^
     [exec]       81 | 		const {findByText} = renderEditSXPBlueprintForm();
     [exec]       82 | 
     [exec]       83 | 		const titleElement = await findByText('Test Title');
     [exec] 
     [exec]       at new Spec (../../../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
     [exec]       at Suite.<anonymous> (test/js/edit_sxp_blueprint/EditSXPBlueprintForm.js:80:2)
     [exec]       at Object.<anonymous> (test/js/edit_sxp_blueprint/EditSXPBlueprintForm.js:77:1)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec]   ??? EditSXPBlueprintForm ??? adds additional query element from sidebar
     [exec] 
     [exec]     Unable to fire a "mouseover" event - please provide a DOM element.
     [exec] 
     [exec]       124 | 			});
     [exec]       125 | 
     [exec]     > 126 | 		fireEvent.mouseOver(queryAllByLabelText('add')[0]);
     [exec]           | 		          ^
     [exec]       127 | 
     [exec]       128 | 		fireEvent.click(queryAllByLabelText('add')[0]);
     [exec]       129 | 
```

**Comment by catarineaguiar** [comment]
@jorgediaz-lr okay, thanks for checking!

**Comment by catarineaguiar** [comment]
no regressions found.

**Review by dantewang — CHANGES_REQUESTED** [review]
@jorgediaz-lr Could you split your change into multiple commits to explain why the change is needed in commit message? Like why do you need to modify the `*TestUtil`. This way other people can know the motivation clearly when looking at git history. Thanks!

**Review by dantewang — APPROVED** [review]
@jorgediaz-lr Never mind, the github web page confused me...

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122850

**Pull request closed without merging**
