### PR TITLE
[Remove Stream/Optional usage] LPS-175214 oauth2-provider-rest

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend, thanks!

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3481

https://issues.liferay.com/browse/LPS-175214

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:oauth2

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:oauth2

**Comment by catarineaguiar** [comment]
no regressions.

**Pull request closed without merging**
