### PR TITLE
 [OrderByComparator] LPD-25955

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPD-25955](https://liferay.atlassian.net/browse/LPD-25955)

[LPD-25955]: https://liferay.atlassian.net/browse/LPD-25955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:relevant

**Comment by victorhcunha** [comment]
ci:report:63907898

**Comment by victorhcunha** [comment]
ci:report:63971958

**Comment by victorhcunha** [comment]
ci:report:63907898

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:relevant

**Comment by victorhcunha** [comment]
ci:test:upgrade

**Comment by victorhcunha** [comment]
ci:test:upgrade

**Comment by victorhcunha** [comment]
ci:report:67108332

**Comment by victorhcunha** [comment]
ci:report:66888827

**Comment by victorhcunha** [comment]
ci:test:relevant

**Comment by victorhcunha** [comment]
ci:report:68283575

**Comment by victorhcunha** [comment]
ci:test:sf

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
