### PR TITLE
[Remove Blocking usages]LPS-189564 portal-kernel | WorkflowComparatorFactoryUtil 

### PR DESCRIPTION
**Pull request by JanisZhang**
Fixed the regression. Thanks!

previous:https://github.com/liferay-core-infra/liferay-portal/pull/4928

changes in this pr:
- The previous regression is caused due to the inaccessibility of a private field in [WorkflowInstancePortletTab.java](https://github.com/liferay-core-infra/liferay-portal/commit/69c17179b52afb3175ce37a7a2dca1f83f71c9b6#diff-2823cafb1f1edceb0d5860c8b8c4249771631f747213c2b34a0031de1ecb1ac0). change the access modifier from private to protected.

https://liferay.atlassian.net/browse/LPS-189564

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by JanisZhang** [comment]
Thanks @Kvale1733 !

**Review by dantewang — CHANGES_REQUESTED** [review]
@JanisZhang Please also move the comparators together with the factory. Thanks!

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:workflow

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:workflow

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
Semantic versioning issue:
```
     [exec] > Task :apps:portal-workflow:portal-workflow-api:baseline
     [exec] [Baseline Warning] Bundle Version Change Recommended: 8.2.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.portal.workflow.api-8.1.1.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.portal.workflow.api/8.1.0/e8967ee3b32132e85092c0f55e3aa52c996630e7/com.liferay.portal.workflow.api-8.1.0.jar
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-07/test-1-26/test-portal-acceptance-pullrequest(master)/10509/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by JanisZhang** [comment]
force-pushed. I just add 1 semantic versioning commit, it shouldn't affect the test results. thanks cc @zhangyan0701 @dantewang

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137958

**Pull request closed without merging**
