### PR TITLE
[Move Expando]Lps 190836 10 23

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-190836

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:upgrade

**Comment by slnn** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@slnn Regressions found

1) PortalDatabaseValidationUpgrade#CompareUpgradedAndFreshDatabaseSchemas7210
Seems this test compares the databse schema for an upgraded db and one that uses a fresh db schema after startup

Steps to reproduce:
1. Import this 7.2.0 db dump: https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.2.0/data-archive/data-archive-portal-mysql.zip
2. Upgrade the database with the upgrade tool and startup
3. Shutdown
4. Run "ant -f build-test.xml export-database-schema -Ddatabase.file.prefix=upgraded -Ddatabase.schema.name=lportal". This will export the database into a file called upgrades-lportal.sql. It will be inside of the poshi directory in the bundle. This assumes your scheme name is lportal
5. Run "ant -f build-test.xml rebuild-database -Ddatabase.type=mysql -Dsql.dir=sql/create-bare/ -Dsql.file=create-bare-mysql.sql" to rebuild a bare database
6. Startup and shutdown
7. Run "ant -f build-test.xml export-database-schema -Ddatabase.file.prefix=fresh -Ddatabase.schema.name=lportal" to export the database to fresh-lportal.sql.
8. Compare the two sql files. The two should be exactly the same. You can do this manually or run
"ant -f build-test.xml validate-db-upgrade-schemas -Dfresh.db.schema=lportal -Dupgraded.db.schema=lportal". This will create a file in the poshi folder names lportal-lportal-validate-db-schemas.txt. If the two are the same the file should have text saying they match. Otherwise, it shows what the difference is. This is the result

[lportal-lportal-validate-db-schemas.txt](https://github.com/liferay-core-infra/liferay-portal/files/13127014/lportal-lportal-validate-db-schemas.txt)

It also printed in the [log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-31/test-portal-acceptance-pullrequest(master)/9706/functional-upgrade-tomcat90-mysql57-jdk8/2/2/jenkins-console.txt.gz?authuser=0)

2) com.liferay.document.library.internal.upgrade.v3_2_6.test.DeleteStalePWCVersionsUpgradeProcessTest
```
[beanshell]      [exec] com.liferay.document.library.internal.upgrade.v3_2_6.test.DeleteStalePWCVersionsUpgradeProcessTest > testDeletePWCVersionsPreservesCheckedOutDocuments FAILED
[beanshell]      [exec]     java.lang.NullPointerException
[beanshell]      [exec]     	at com.liferay.expando.internal.ExpandoTableImpl.getTableId(ExpandoTableImpl.java:23)
[beanshell]      [exec]     	at com.liferay.portlet.documentlibrary.service.impl.DLFileEntryLocalServiceImpl._copyExpandoRowModifiedDate(DLFileEntryLocalServiceImpl.java:2491)
[beanshell]      [exec]     	at com.liferay.portlet.documentlibrary.service.impl.DLFileEntryLocalServiceImpl._checkOutDLFileEntryModel(DLFileEntryLocalServiceImpl.java:2353)
[beanshell]      [exec]     	at com.liferay.portlet.documentlibrary.service.impl.DLFileEntryLocalServiceImpl.checkOutFileEntry(DLFileEntryLocalServiceImpl.java:503)
[beanshell]      [exec]     	at com.liferay.portlet.documentlibrary.service.impl.DLFileEntryLocalServiceImpl.checkOutFileEntry(DLFileEntryLocalServiceImpl.java:537)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[beanshell]      [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell]      [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell]      [exec]     	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:57)
[beanshell]      [exec]     	at com.sun.proxy.$Proxy990.checkOutFileEntry(Unknown Source)
[beanshell]      [exec]     	at com.liferay.document.library.kernel.service.DLFileEntryLocalServiceWrapper.checkOutFileEntry(DLFileEntryLocalServiceWrapper.java:148)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-31/test-portal-acceptance-pullrequest(master)/9706/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Comment by slnn** [comment]
Thank @Kvale1733 for catching this!

Fix and resend in https://github.com/liferay-core-infra/liferay-portal/pull/5905

**Pull request closed without merging**
