### PR TITLE
[Static references] LPS-182621 Remove static references in module document-library

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:document

**Comment by GabrielHenriquedev** [comment]
ci:test:dl-store

**Comment by Kvale1733** [comment]
@GabrielHenriquedev No regressions.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
