### PR TITLE
kyle miho LPS 162706 10 27 3

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-162706

### CODE REVIEW

**Comment by Kvale1733** [comment]
No regressions found.

**Comment by tinatian** [comment]
@kyle-miho Why we still have those integration test related commits? Could you please remove those?

Thanks
Tina

**Comment by kyle-miho** [comment]
@tinatian updated with only functional test

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127270

**Pull request closed without merging**
