### PR TITLE
[Remove unused field] LPS-199960 Remove unused reference field in calsses EditCommerceNotificationTemplateMVCActionCommand, CommerceOpenOrderContentPortlet and EditCommerceOrderMVCActionCommand

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:commerce

**Comment by W2jx** [comment]
no conflicts(10/30 7:57)

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by W2jx** [comment]
no conflicts(10/30 7:57)

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@W2jx No regressions found. SF is unrelated.

**Comment by W2jx** [comment]
no conflicts(11/1 9:03)

**Comment by W2jx** [comment]
no conflicts(11/2 8:14)

**Comment by W2jx** [comment]
no conflicts(11/3 8:52)

**Comment by dantewang** [comment]
@W2jx Can you double check whether this will conflict with https://github.com/liferay-core-infra/liferay-portal/pull/5936? If not I'll just forward it.

**Comment by W2jx** [comment]
Hi @dantewang ， I have double checked and there will be no conflicts in file `source-formatter.properties`.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143178

cc @shuyangzhou

**Pull request closed without merging**
