### PR TITLE
LPS-200166 Remove MethodFactoryRegistry and simplify MethodFactory usage

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
@julschong 

https://github.com/liferay-core-infra/liferay-portal/pull/6035/commits/4cdf2c97823fcd016a3007f2d01dddbcd8e41ae1

Should we include the path before or after moving in the "What" title?

**Comment by dantewang** [comment]
@julschong The commit message of https://github.com/liferay-core-infra/liferay-portal/pull/6035/commits/b69b22cb26399c9befffeffe6b80ebdf3d8a1d7c should say "WebDAVServlet`.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
Approved. Just commit message issues.

**Comment by julschong** [comment]
fixed commit message [bac1212](https://github.com/liferay-core-infra/liferay-portal/pull/6035/commits/bac1212517bf6a0469d2e60cfb97ffc6451b9591)

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
