### PR TITLE
LPS-170100 Remove "immediate = true" from Portal I

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:help

**Comment by RenanUmV** [comment]
ci:test:clustering

**Comment by Kvale1733** [comment]
@RenanUmV There is an unsatisfied reference when enabling clustering.
```
[beanshell] 2022-11-30 19:59:57.026 WARN  [main][SystemCheckOSGiCommands:134] Declarative Service Unsatisfied Component Checker check result: 
[beanshell] Bundle {id: 294, name: com.liferay.portal.cache.multiple, version: 5.0.21}
[beanshell] 	Declarative Service {id: 1153, name: com.liferay.portal.cache.multiple.internal.cluster.link.messaging.ClusterLinkPortalCacheClusterListener, unsatisfied references: 
[beanshell] 		{name: _destination, target: (destination.name=liferay/cache_replication)}
[beanshell] 	}
[beanshell] 2022-11-30 19:59:57.027 INFO  [main][SystemCheckOSGiCommands:111] Running "Spring Extender Unavailable Component Checker". You can run this by itself with command "dm na" in gogo shell.
```
[Log](https://testray.liferay.com/reports/production/logs/2022-11/test-1-35/test-portal-acceptance-pullrequest(master)/3155/functional-tomcat90-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

**Comment by RenanUmV** [comment]
ci:test:clustering

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
@Kvale1733 Could you please verify if this test ScheduleJobOnClusterNode1 passed?

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2714

**Pull request closed without merging**
