### PR TITLE
LPS-148191 Move commons-digester and commons-validator

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:acceptance-release

**Comment by rafaprax** [comment]
Hey, @koor4356 Can you help me check the test results when they are ready? Thx

**Comment by koor4356** [comment]
Okay, thanks!

**Comment by koor4356** [comment]
@rafaprax,
This looks good, Thanks!

**Comment by rafaprax** [comment]
Hey @shuyangzhou, It's ready for your review. Thx

**Comment by shuyangzhou** [comment]
@rafaprax I see only https://github.com/liferay-core-infra/liferay-portal/pull/386/commits/bd0e29e34ac8992936ca50f7f434913dc24518eb#diff-8ef0d12e913030771d04979c52713644b4b24b42b5eb5fc90d587c0c03375f5aL207 is removed from system bundle export, that means current modules only need that package, right?
If so, we should still compileInclude the 2 jars and export that package only, otherwise we would be exporting a lot of unnecessary packages.

**Comment by rafaprax** [comment]
@shuyangzhou got it. I'm on it. Thx

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @shuyangzhou, I made the requested change. So, the pr is ready for review again. Thx

/cc @tinatian

**Comment by shuyangzhou** [comment]
@rafaprax a few things to change:

1. Move apps/url-validator to apps/portal/portal-url-validator, this should not be an app by itself, it is part of portal. Based on its usage, in the end once we pull out portal service.xml, this module can be removed completely.
2. No need to create URLValidatorUtil, do the ServiceProxyFactory injection directly inside WebsiteLocalServiceImpl.
3. As a followup change(once we start the service.xml extraction), WebsiteLocalServiceImpl can be pulled out into module, currently it is mainly used by other modules. With 2 exceptions, ```portal-impl/src/com/liferay/portal/service/impl/ContactLocalServiceImpl.java``` and ```portal-impl/src/com/liferay/portal/service/impl/OrganizationLocalServiceImpl.java```. They can be easily changed to ModelListener based deletion cleanup.

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @shuyangzhou, I made the changes you requested. I just trigger the test:relevant again to make sure that I don't break anything. Thx

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10581

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
