### PR TITLE
LPS-166009 Move portal-impl template files to portal-template-engine-api

### PR DESCRIPTION
**Pull request by julschong**
resubmit from #2171

Removed commits to move UtilLocator and ServiceLocator

### CODE REVIEW

**Comment by julschong** [comment]
rebased for conflict in bnd.bnd

**Comment by julschong** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by julschong** [comment]
rebased for conflict in kernel bnd.bnd

**Comment by julschong** [comment]
pushed for conflict in kernel bnd.bnd

**Comment by julschong** [comment]
rebased for conflict in portal-kernel/bnd.bnd

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125998

**Pull request closed without merging**
