### PR TITLE
LPS-173290 Remove Stream usages in module: mulesoft

### PR DESCRIPTION
**Pull request by julschong**
@tinatian @vicnate5 @Kvale1733 
Hi Tina, Victor, Kevin,

This pull was previously tested in my repo https://github.com/julschong/liferay-portal/pull/716

ci relevant still cannot run successfully, but I was able to run the unit tests by going into the module and run `mvn test`

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
Running stable to get baseline coverage, since relevant won't run.

**Comment by julschong** [comment]
rebased to resolve conflict

**Comment by julschong** [comment]
ci:test:stable

**Comment by julschong** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
