### PR TITLE
LPS-164986 Remove immediate from DDM and Forms modules

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@rafaprax semver error:

```
 [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/dynamic-data-mapping/dynamic-data-mapping-api] STARTED
     [exec] 
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/dynamic-data-mapping/dynamic-data-mapping-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.dynamic.data.mapping.data.provider     CHANGED    3.1.0      3.1.0      3.1.1      VERSION INCREASE REQUIRED
     [exec]     	~   class      com.liferay.dynamic.data.mapping.data.provider.DDMDataProviderTracker
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   immediate=true
     [exec]     * com.liferay.dynamic.data.mapping.util              CHANGED    4.0.0      4.0.0      4.0.1      VERSION INCREASE REQUIRED
     [exec]     	~   class      com.liferay.dynamic.data.mapping.util.DDMDisplayRegistry
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   immediate=true
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-31/test-portal-acceptance-pullrequest(master)/5369/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

after reindexing on Upgrade functional tests, this failure happens:
```
     [exec]     Finished reindexing after 30 seconds.
[beanshell] 2022-10-10 14:30:58.308 ERROR [http-nio-8080-exec-8][IncludeTag:128] Current URL /web/guest/document?p_p_id=com_liferay_document_library_web_portlet_DLPortlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&_com_liferay_document_library_web_portlet_DLPortlet_mvcRenderCommandName=%2Fdocument_library%2Fview_file_entry&_com_liferay_document_library_web_portlet_DLPortlet_redirect=http%3A%2F%2Flocalhost%3A8080%2Fweb%2Fguest%2Fdocument%3Fp_p_id%3Dcom_liferay_document_library_web_portlet_DLPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26_com_liferay_document_library_web_portlet_DLPortlet_mvcRenderCommandName%3D%252Fdocument_library%252Fview%26_com_liferay_document_library_web_portlet_DLPortlet_displayStyle%3Ddescriptive%26_com_liferay_document_library_web_portlet_DLPortlet_navigation%3Dhome%26_com_liferay_document_library_web_portlet_DLPortlet_folderId%3D0&_com_liferay_document_library_web_portlet_DLPortlet_fileEntryId=10487 generates exception: java.lang.NullPointerException
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.dynamic.data.mapping.render.DDMFormFieldRendererRegistryUtil.getDDMFormFieldRenderer(DDMFormFieldRendererRegistryUtil.java:25) ~[bundleFile:?]
[beanshell] 	at com.liferay.dynamic.data.mapping.render.DDMFormRendererUtil.render(DDMFormRendererUtil.java:62) ~[bundleFile:?]
[beanshell] 	at org.apache.jsp.html.start_jsp._jspService(start_jsp:452) ~[?:?]
[beanshell] 	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111) ~[jasper.jar:9.0.65]
[beanshell] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-31/test-portal-acceptance-pullrequest(master)/5369/functional-upgrade-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Circular reference detected. I'm on it.

**Pull request closed without merging**
