### PR TITLE
[Remove Stream/Optional usage] LPS-176635 ddm-form-web

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:data-engine

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:forms

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
