### PR TITLE
[System Properties][Part Three] LPS-158209 replace method get all properties with method get all properties' key name

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang ,  I resend this task , I replaced method get all properties in this PR.

depends on LPS-158208(https://github.com/liferay-core-infra/liferay-portal/pull/1437)

Detail: https://github.com/liferay-core-infra/liferay-portal/pull/1264

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results when they finish ? Thanks!

**Comment by W2jx** [comment]
no conflicts(6:50 AM)

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
@zhangyan0701 Thank you.

**Comment by W2jx** [comment]
no conflicts(7:10 PM)

**Comment by W2jx** [comment]
no conflicts(6:17 PM)

**Comment by W2jx** [comment]
force-push just to resolve conflict about file packageinfo

**Comment by W2jx** [comment]
no conflicts(6:16 PM)

**Pull request closed without merging**
