### PR TITLE
LPS-145853

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian, @shuyangzhou ,

I have removed unused properties "Control.panel.navigation.max.sites", and updated to propskeys.java, propsvalues.java and verifyproperties.java.
Other properties were renamed to "CONTROL_PANEL_NAVIGATION_MAX_SITES", and used in "view.jsp" in commit 8f521c2dc81f84745bc46eaf7c5c0cd932a88c7e, see LPS-17384.
It was finally deleted the usage in commit b0f03b60bacc915f8b891a325eb422bc818519d9, see LPS-35251.
Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.
@jeffwu0724 Code looks good to me, wait for QA to scan test results. Please send me a pull to remove "control.panel.navigation.max.organizations".

Thanks.
Tina.

**Comment by vicnate5** [comment]
@Hijky Can you check the results here?

**Comment by Hijky** [comment]
None of the failed cases are relevant

**Pull request closed without merging**
