### PR TITLE
[Static reference] LPS-170377 Remove method reference by using snapshot in class KBServiceConfigurationProviderUtil

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4343

Changes:

1. Inline KBArticleViewDisplayContext

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:knowledge-base

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
