### PR TITLE
[Replace Non-Blocking Usage] LPS-197550 Replace non-blocking ServiceProxyFactory usages in class MainServlet

### PR DESCRIPTION
**Pull request by haydenzheng314**
Ticket: https://liferay.atlassian.net/browse/LPS-197550
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@LisztLiszt Regression found in 

com.liferay.portal.upgrade.test.ReleasePublisherTest
```
 [exec] com.liferay.portal.upgrade.test.ReleasePublisherTest > testPublishUpgrade FAILED
[beanshell]      [exec]     java.lang.AssertionError: expected:<1> but was:<0>
[beanshell]      [exec]     	at org.junit.Assert.fail(Assert.java:89)
[beanshell]      [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
[beanshell]      [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
[beanshell]      [exec]     	at org.junit.Assert.assertEquals(Assert.java:633)
[beanshell]      [exec]     	at com.liferay.portal.upgrade.test.ReleasePublisherTest.testPublishUpgrade(ReleasePublisherTest.java:97)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[beanshell]      [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell]      [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)
[beanshell]      [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[beanshell]      [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-25/test-portal-acceptance-pullrequest(master)/3746/modules-integration-mysql57-jdk8/3/19/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
