### PR TITLE
LPS-142380 Use ReflectionUtil to keep the exception instead of wrapping it in a RuntimeException; in this change's case, the UI won't be able to show the error message if the exception is rethrown as RuntimeException.

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
As requested in https://github.com/brianchandotcom/liferay-portal/pull/121573
Please let me know if the new exception name is a proper one or I need to change in a different way

**Comment by dantewang** [comment]
@crodriguezy Thanks! If the new change only contains renaming the class, I think you can send it directly to Brian for review, as we may not know exactly whether the class name is correct.

**Comment by catarineaguiar** [comment]
@crodriguezy semver error:

```
 [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/67.0.0/2218369777020497917c0d3eddb79ceeec75e535/com.liferay.portal.kernel-67.0.0.jar
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-25/test-portal-acceptance-pullrequest(master)/4124/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by crodriguezy** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by crodriguezy** [comment]
Hi, this is not going forward. Could it be because of the change in the .bnd?
Thanks

**Comment by dantewang** [comment]
@crodriguezy There's a conflict on bnd.bnd, I think you can just rebase and retry ci-forward.

**Comment by crodriguezy** [comment]
ci:forward

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by crodriguezy** [comment]
Manually forwarded to Brian https://github.com/brianchandotcom/liferay-portal/pull/121982

**Pull request closed without merging**
