### PR TITLE
LPS-171291

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@tinatian regressions found:

```
   [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:portal:portal-messaging-test:compileTestIntegrationJava'.
     [exec] > Compilation failed; see the compiler error output for details.
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:portal:portal-messaging-test:compileTestIntegrationJava'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$3(ExecuteActionsTaskExecuter.java:186)
     [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:268)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)
     [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
     [exec] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-37/test-portal-acceptance-pullrequest(master)/7163/modules-integration-mysql57-jdk8/3/9/jenkins-console.txt.gz?authuser=0)

```
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:document-library:document-library-test:compileTestIntegrationJava'.
     [exec] > Compilation failed; see the compiler error output for details.
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:document-library:document-library-test:compileTestIntegrationJava'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$3(ExecuteActionsTaskExecuter.java:186)
     [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:268)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)
     [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
     [exec] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-37/test-portal-acceptance-pullrequest(master)/7163/modules-compile-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

```
     [exec] > Task :apps:address:address-web:jarJSP
     [exec] > Task :apps:address:address-web:assemble
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-image-impl-test/src/testIntegration/java/com/liferay/adaptive/media/image/internal/configuration/test/BaseAMImageConfigurationTestCase.java:80: error: cannot find symbol
     [exec] 		_messageBus.registerMessageListener(
     [exec] 		           ^
     [exec]   symbol:   method registerMessageListener(java.lang.String,com.liferay.portal.kernel.messaging.MessageListener)
     [exec]   location: variable _messageBus of type com.liferay.portal.kernel.messaging.MessageBus
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-image-impl-test/src/testIntegration/java/com/liferay/adaptive/media/image/internal/configuration/test/BaseAMImageConfigurationTestCase.java:88: error: cannot find symbol
     [exec] 			_messageBus.unregisterMessageListener(
     [exec] 			           ^
     [exec]   symbol:   method unregisterMessageListener(java.lang.String,com.liferay.portal.kernel.messaging.MessageListener)
     [exec]   location: variable _messageBus of type com.liferay.portal.kernel.messaging.MessageBus
     [exec] 2 errors
     [exec] 
     [exec] > Task :apps:adaptive-media:adaptive-media-image-impl-test:compileTestIntegrationJava FAILED
     [exec] 
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-37/test-portal-acceptance-pullrequest(master)/7163/modules-compile-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@tinatian regressions found:

```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal/portal-messaging-test/src/testIntegration/java/com/liferay/portal/messaging/test/DefaultMessagingConfiguratorTest.java:85: error: method does not override or implement a method from a supertype
     [exec] 			@Override
     [exec] 			^
     [exec] 1 error
     [exec] 
     [exec] > Task :apps:portal:portal-messaging-test:compileTestIntegrationJava FAILED
     [exec] 
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-37/test-portal-acceptance-pullrequest(master)/7463/modules-integration-mysql57-jdk8/3/9/jenkins-console.txt.gz?authuser=0)

```
     [exec] > Task :apps:object:object-test:startTestableTomcat SKIPPED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/service/test/ObjectDefinitionLocalServiceTest.java:892: error: cannot find symbol
     [exec] 			_messageBus.hasDestination(objectDefinition.getDestinationName()));
     [exec] 			           ^
     [exec]   symbol:   method hasDestination(java.lang.String)
     [exec]   location: variable _messageBus of type com.liferay.portal.kernel.messaging.MessageBus
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/service/test/ObjectDefinitionLocalServiceTest.java:984: error: cannot find symbol
     [exec] 			_messageBus.hasDestination(objectDefinition.getDestinationName()));
     [exec] 			           ^
     [exec]   symbol:   method hasDestination(java.lang.String)
     [exec]   location: variable _messageBus of type com.liferay.portal.kernel.messaging.MessageBus
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 2 errors
     [exec] 
     [exec] > Task :apps:object:object-test:compileTestIntegrationJava FAILED
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-37/test-portal-acceptance-pullrequest(master)/7463/modules-integration-mysql57-jdk8/2/20/jenkins-console.txt.gz?authuser=0)

```
[exec] > Task :baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.messaging                MAJOR      14.0.0     14.0.0     15.0.0     VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.portal.kernel.messaging.BaseDestination
     [exec] 		-   method     afterPropertiesSet()
     [exec] 			-   return     void
     [exec] 	>   class      com.liferay.portal.kernel.messaging.MessageBusUtil
     [exec] 		-   method     hasMessageListener(java.lang.String)
     [exec] 			-   access     static
     [exec] 			-   return     boolean
     [exec] 		-   method     registerMessageListener(java.lang.String,com.liferay.portal.kernel.messaging.MessageListener)
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 		-   method     unregisterMessageListener(java.lang.String,com.liferay.portal.kernel.messaging.MessageListener)
     [exec] 			-   access     static
     [exec] 			-   return     boolean
     [exec] 	>   interface  com.liferay.portal.kernel.messaging.MessageBus
     [exec] 		-   method     addMessageBusEventListener(com.liferay.portal.kernel.messaging.MessageBusEventListener)
     [exec] 			-   access     abstract
     [exec] 			-   return     boolean
     [exec] 		-   method     getDestinationCount()
     [exec] 			-   access     abstract
     [exec] 			-   return     int
     [exec] 		-   method     getDestinationNames()
     [exec] 			-   access     abstract
     [exec] 			-   return     java.util.Collection
     [exec] 		-   method     getDestinations()
     [exec] 			-   access     abstract
     [exec] 			-   return     java.util.Collection
     [exec] 		-   method     hasDestination(java.lang.String)
     [exec] 			-   access     abstract
     [exec] 			-   return     boolean
     [exec] 		-   method     hasMessageListener(java.lang.String)
     [exec] 			-   access     abstract
     [exec] 			-   return     boolean
     [exec] 		-   method     registerMessageListener(java.lang.String,com.liferay.portal.kernel.messaging.MessageListener)
     [exec] 			-   access     abstract
     [exec] 			-   return     boolean
     [exec] 		-   method     removeMessageBusEventListener(com.liferay.portal.kernel.messaging.MessageBusEventListener)
     [exec] 			-   access     abstract
     [exec] 			-   return     boolean
     [exec] 		-   method     unregisterMessageListener(java.lang.String,com.liferay.portal.kernel.messaging.MessageListener)
     [exec] 			-   access     abstract
     [exec] 			-   return     boolean
     [exec] * com.liferay.portal.kernel.messaging.config         MAJOR      10.0.0     10.0.0     11.0.0     VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.portal.kernel.messaging.config.DefaultMessagingConfigurator
     [exec] 		-   method     connect()
     [exec] 			-   return     void
     [exec] 		-   method     disconnect()
     [exec] 			-   return     void
     [exec] 		-   method     getOperatingClassLoader()
     [exec] 			-   access     protected
     [exec] 			-   return     java.lang.ClassLoader
     [exec] 	-   class      com.liferay.portal.kernel.messaging.config.MessagingConfiguratorRegistry
     [exec] 		-   method     <init>()
     [exec] 			-   return     void
     [exec] 		-   method     clone()
     [exec] 			-   access     protected
     [exec] 			-   return     java.lang.Object
     [exec] 		-   method     equals(java.lang.Object)
     [exec] 			-   return     boolean
     [exec] 		-   method     finalize()
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     getMessagingConfigurators(java.lang.String)
     [exec] 			-   access     static
     [exec] 			-   return     java.util.List
     [exec] 		-   method     hashCode()
     [exec] 			-   return     int
     [exec] 		-   method     registerMessagingConfigurator(java.lang.String,com.liferay.portal.kernel.messaging.config.MessagingConfigurator)
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 		-   method     toString()
     [exec] 			-   return     java.lang.String
     [exec] 		-   method     unregisterMessagingConfigurator(java.lang.String,com.liferay.portal.kernel.messaging.config.MessagingConfigurator)
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 	>   interface  com.liferay.portal.kernel.messaging.config.MessagingConfigurator
     [exec] 		-   method     connect()
     [exec] 			-   access     abstract
     [exec] 			-   return     void
     [exec] 		-   method     disconnect()
     [exec] 			-   access     abstract
     [exec] 			-   return     void
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/92.1.0/5c259f2baa76ae23d9ba57d24cb1df5ebbf99479/com.liferay.portal.kernel-92.1.0.jar
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-37/test-portal-acceptance-pullrequest(master)/7463/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Regression found:
Integration test [com.liferay.portal.messaging.test.DefaultMessagingConfiguratorTest](https://testray.liferay.com/home/-/testray/case_results/2147171085) failed with error:
```
     [exec] com.liferay.portal.messaging.test.DefaultMessagingConfiguratorTest > testCustomClassLoaderDestinationConfiguration FAILED
     [exec]     java.lang.AssertionError: expected:<com.liferay.portal.messaging.test.DefaultMessagingConfiguratorTest$1@6b5c78a2> but was:<org.eclipse.osgi.internal.framework.ContextFinder@2b6ba3cb>
```
Full console:
https://testray.liferay.com/reports/production/logs/2022-12/test-1-37/test-portal-acceptance-pullrequest(master)/7560/modules-integration-mysql57-jdk8/3/9/jenkins-console.txt.gz?authuser=0

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128354

**Pull request closed without merging**
