### PR TITLE
[Eliminate unused reference]LPS-200628 module:analytics,portal-scripting,content-dashboard

### PR DESCRIPTION
**Pull request by JanisZhang**
Remove unused reference fields in class `BlogsEntryAnalyticsReportsInfoItem`, `FileEntryAnalyticsReportsInfoItem`, `GetContentDashboardItemsXlsMVCResourceCommand` and `ScriptingExecutorMessagingConfigurator`. Thanks.
https://liferay.atlassian.net/browse/LPS-200628

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Sharryxue** [comment]
No related issue found in [ci:test:startup](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2451235894) and [ci:test:relevant](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2451204960) suites, could you please add the QA Passed label for it @zhangyan0701, thanks in advance.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
