### PR TITLE
[Optional Reference]LPS-185565 oauth2-provider-scope-impl 

### PR DESCRIPTION
**Pull request by JanisZhang**
resend, previous: https://github.com/liferay-core-infra/liferay-portal/pull/4617
https://issues.liferay.com/browse/LPS-185565

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:oauth2

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
