### PR TITLE
[[Remove Stream/Optional usage] LPS-172112 portal-search-similar-results-web

### PR DESCRIPTION
**Pull request by dantewang**
@slnn

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:search

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@dantewang No regressions found.

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
