### PR TITLE
[Remove Stream/Optional usage] LPS-170733 | 1-4

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128440

**Pull request closed without merging**
