### PR TITLE
[Component with its own class name as service type] LPS-200284 Remove own class as service for some commerce-product-content-web classes

### PR DESCRIPTION
**Pull request by rcsdnj**
CPDefinitionLinkInfoItemRenderer, PriceInfoItemRenderer.java and ProductCardInfoItemRenderer were referring to their own class as an implemented service, as [pointed in the corresponding spreadsheet.](https://docs.google.com/spreadsheets/d/1y-4j4IYr7LDKDVXoOFIFvqyYgTb5t0w-iDxyyEw5OJw/edit?usp=sharing) This is a refactor to avoid this

This PR was checked by Rafael Praxedes on https://github.com/rafaprax/liferay-portal/pull/1320

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
re-runing relevant suite due to some tests didn't run

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
