### PR TITLE
[Method References 2] LPS-172192 Change the value of property cardinality from ReferenceCardinality.AT_LEAST_ONE to ReferenceCardinality.MULTIPLE | part 3

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:help

**Comment by W2jx** [comment]
ci:test:search-solr

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(1/6 8:59)

**Pull request closed without merging**
