### PR TITLE
[Convert optional references to hard referebces]Lps 187486

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-187486

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by marcosapmf** [comment]
LGTM :tada: 
Thanks for the pull request  @slnn :smile:

**Comment by Kvale1733** [comment]
@slnn No regression found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
