### PR TITLE
LPD-31417 Update org.tukaani.xz to 1.9

### PR DESCRIPTION
**Pull request by balazssk**
Hey Team,
https://liferay.atlassian.net/browse/LPD-31417

Because of 
```compileInclude group: "org.apache.commons", name: "commons-compress", version: "1.26.0"```
 has a [dependency](https://mvnrepository.com/artifact/org.apache.commons/commons-compress/1.26.0) on
```org.tukaani.xz to 1.9```
lets update this.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hi @tinatian ,

A quick check of this PR. Code looks good to me.

1. This upgrade of `org.tukaani.xz` is needed because in https://liferay.atlassian.net/browse/LPP-54830, when we are uploading and indexing 7z files, there will be `Caused by: java.lang.NoSuchMethodError: 'void org.tukaani.xz.LZMAInputStream.enableRelaxedEndCondition()'`. This `LZMAInputStream.enableRelaxedEndCondition()` is added in version 1.9 for handling 7z files, please see https://github.com/tukaani-project/xz-java/blob/master/NEWS.
2. In our codebase, we only have two `build.gradle` that use `org.tukaani`, and they have been upgraded in this PR.
3. Waiting for the relevant testresult to double check...

**Comment by tinatian** [comment]
@jeffwu0724 Code looks good to me, once it passed on ci please forward to BChan and cc me.

Thanks!

**Comment by jeffwu0724** [comment]
sent to BChan: https://github.com/brianchandotcom/liferay-portal/pull/152311

**Pull request closed without merging**
