### PR TITLE
LPS-192819 there's no Settings implementation extending FallbackKeys,…

### PR DESCRIPTION
**Pull request by JanisZhang**
… it should be FallbackSettings.

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by JanisZhang** [comment]
The stable failure will be fixed by https://github.com/brianchandotcom/liferay-portal/pull/138872. I will re-run the test until the fix is merged into master.

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
