### PR TITLE
[Static reference] LPS-180991 Remove method reference by using snapshot in module portal-settings 

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:ldap

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(4/7 16:38)

**Comment by W2jx** [comment]
no conflicts(4/10 8:33)

**Comment by W2jx** [comment]
no conflicts(4/11 9:50)

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
