### PR TITLE
[System Properties] LPS-156838 Move some properties required by module framework, and they only use simple method(systemProperties.get)

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian  @dantewang , I moved some properties that only use SystemProperties.get, to simplify the task of moving module framework properties(LPS-151639)

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me scan test results when you free ? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@W2jx Conflicts, please rebase.

**Comment by dantewang** [comment]
@GinsonRen @111Anna Please run a startup diff once @W2jx resolves the conflicts. Thanks!

**Comment by 111Anna** [comment]
OK, I have update

**Comment by W2jx** [comment]
no conflicts(6:18 PM)

**Comment by W2jx** [comment]
no conflicts(6:50 AM)

**Comment by W2jx** [comment]
no conflicts(6:24 PM)

**Comment by W2jx** [comment]
force-push just to resolve conflict about files packageinfo

**Pull request closed without merging**
