### PR TITLE
LPS-143632 Remove LanguageUtil usages in portlet module

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
Could you please help me review this test result?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
