### PR TITLE
LPS-145344

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian , @shuyangzhou ,

**Resend. It was checked before by Tina, see https://github.com/liferay-core-infra/liferay-portal/pull/252.**

I remove unused properties "look.and.feel.modifiable".
It was created in commit c90a3a0, see LEP-4549, and It was used in "edit_pages.jsp”.
“edit_pages.jsp” was renamed from portal-web/docroot/html/portlet/communities/edit_pages.jsp to portal-web/docroot/html/portlet/layouts_admin/edit_pages.jsp based on commit c9e38b0, see LPS-15140.
Then, it was used in portal-web/docroot/html/portlet/layouts_admin/view.jsp, based on 5106ccb, see LPS-15178.
It was finally deleted in commit bf6bd99, see LPS-14453.
Thanks for checking!

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@jeffwu0724 Please rebase and resend, you should not have a commit with message like "[Merge branch 'master' into LPS-145344-2](https://github.com/liferay-core-infra/liferay-portal/pull/277/commits/2ef956742fd9977a8ab13445b9948f7fabd44431)"

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
