### PR TITLE
LPS-184385 reset the default value of virtual.hosts.valid.hosts

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

Reset the default value of "virtual.hosts.valid.hosts", and fix the unit test.
Thanks for checking

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by jeffwu0724** [comment]
fixed the code conflict in readme/BREAKING_CHANGES.markdown, no need to retrigger the test

**Comment by tinatian** [comment]
@jeffwu0724 Please rebase

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
fixed the code conflict in readme/BREAKING_CHANGES.markdown, no need to retrigger the test

**Comment by tinatian** [comment]
@jeffwu0724 Please rebase

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
fixed the code conflict in readme/BREAKING_CHANGES.markdown, no need to retrigger the test

**Pull request closed without merging**
