### PR TITLE
[Log4j Companies]LPS-154229

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results? Thanks!

**Comment by yuhai** [comment]
@tinatian, @dantewang, I added one commit for this. Please see https://github.com/liferay-core-infra/liferay-portal/pull/815/commits/c7ccb62ba8d19ce49a91846e270bf8f670ca72dd

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by vicnate5** [comment]
@tinatian Is this the full implementation of https://issues.liferay.com/browse/LPS-154228? I would like to do some exploratory testing on this new story.

**Comment by tinatian** [comment]
@vicnate5 No, it is not. This is only the first part of it.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by tinatian** [comment]
@yuhai I do not understand https://github.com/liferay-core-infra/liferay-portal/commit/c7ccb62ba8d19ce49a91846e270bf8f670ca72dd. It should always overwrite.

**Pull request closed without merging**
