### PR TITLE
LPS-177182 Remove leftovers "immediate = true" from asset-categories-service

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-177182

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:lima

**Comment by catarineaguiar** [comment]
ci:stop:lima

**Comment by catarineaguiar** [comment]
ci:test:depto

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by zhangyan0701** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@rafaprax No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131619

**Pull request closed without merging**
