### PR TITLE
LPS-196204 Merge PortalUUID interface and impl into Util

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Shuyang,

Resent: https://github.com/liferay-core-infra/liferay-portal/pull/5582
This is for ticket https://liferay.atlassian.net/browse/LPS-196204
Thanks for checking

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 

1) Regression found in 
ListAPIApplicationSchemas#CanSeeAvailableFieldsAndActions

Steps to reproduce:
1. Execute the following curl
```
curl -X POST -u 'test@liferay.com:test' -H 'Content-Type: application/json' -d '{"applicationStatus": {"key": "unpublished","name": "unpublished"},"baseURL": "my-app","title": "My-app"}' http://localhost:8080/o/headless-builder/applications
```

Expected Results: The response includes the object items. Something like

```
     [exec]     {
     [exec]       "actions" : {
     [exec]         "permissions" : {
     [exec]           "method" : "GET",
     [exec]           "href" : "http://localhost:8080/o/headless-builder/applications/34626/permissions"
     [exec]         },
     [exec]         "get" : {
     [exec]           "method" : "GET",
     [exec]           "href" : "http://localhost:8080/o/headless-builder/applications/34626"
     [exec]         },
     [exec]         "replace" : {
     [exec]           "method" : "PUT",
     [exec]           "href" : "http://localhost:8080/o/headless-builder/applications/34626"
     [exec]         },
     [exec]         "update" : {
     [exec]           "method" : "PATCH",
     [exec]           "href" : "http://localhost:8080/o/headless-builder/applications/34626"
     [exec]         },
     [exec]         "delete" : {
     [exec]           "method" : "DELETE",
     [exec]           "href" : "http://localhost:8080/o/headless-builder/applications/34626"
     [exec]         }
     [exec]       },
     [exec]       "creator" : {
     [exec]         "additionalName" : "",
     [exec]         "contentType" : "UserAccount",
     [exec]         "familyName" : "Test",
     [exec]         "givenName" : "Test",
     [exec]         "id" : 20123,
     [exec]         "name" : "Test Test"
     [exec]       },
     [exec]       "dateCreated" : "2023-10-03T14:41:01Z",
     [exec]       "dateModified" : "2023-10-03T14:41:01Z",
     [exec]       "externalReferenceCode" : "e5ca467f-5dc8-9959-5be8-1c984c6cfdfb",
     [exec]       "id" : 34626,
     [exec]       "keywords" : [ ],
     [exec]       "status" : {
     [exec]         "code" : 0,
     [exec]         "label" : "approved",
     [exec]         "label_i18n" : "Approved"
     [exec]       },
     [exec]       "taxonomyCategoryBriefs" : [ ],
     [exec]       "baseURL" : "my-app",
     [exec]       "applicationStatus" : {
     [exec]         "key" : "unpublished",
     [exec]         "name" : "unpublished"
     [exec]       },`
```

Actual Results: The response is the following string
```
     [exec]     <html>
     [exec] 
     [exec]     			<head>
     [exec]     				<title></title>
     [exec] 
     [exec]     				<meta content="1; url=http://localhost:8080/web/guest" http-equiv="refresh" />
     [exec]     			</head>
     [exec] 
     [exec]     			<body onload="javascript:location.replace('http\x3a\x2f\x2flocalhost\x3a8080\x2fweb\x2fguest');">
     [exec] 
     [exec]     				<!--
     [exec]     				The numbers below are used to fill up space so that this works properly in IE.
     [exec]     				See http://support.microsoft.com/default.aspx?scid=kb;en-us;Q294807 for more
     [exec]     				information on why this is necessary.
     [exec] 
     [exec]     				12345678901234567890123456789012345678901234567890123456789012345678901234567890
     [exec]     				12345678901234567890123456789012345678901234567890123456789012345678901234567890
     [exec]     				12345678901234567890123456789012345678901234567890123456789012345678901234567890
     [exec]     				-->
     [exec]     			</body>
     [exec]     		</html>
     [exec]     	Finished executing commands.
     [exec] 
     [exec]     Executing commands: curl -X GET -u 'test@liferay.com:test' -H 'Content-Type: application/json' http://localhost:8080/o/headless-builder/applications
     [exec]     <html>
     [exec] 
     [exec]     			<head>
     [exec]     				<title></title>
     [exec] 
     [exec]     				<meta content="1; url=http://localhost:8080/web/guest" http-equiv="refresh" />
     [exec]     			</head>
     [exec] 
     [exec]     			<body onload="javascript:location.replace('http\x3a\x2f\x2flocalhost\x3a8080\x2fweb\x2fguest');">
     [exec] 
     [exec]     				<!--
     [exec]     				The numbers below are used to fill up space so that this works properly in IE.
     [exec]     				See http://support.microsoft.com/default.aspx?scid=kb;en-us;Q294807 for more
     [exec]     				information on why this is necessary.
     [exec] 
     [exec]     				12345678901234567890123456789012345678901234567890123456789012345678901234567890
     [exec]     				12345678901234567890123456789012345678901234567890123456789012345678901234567890
     [exec]     				12345678901234567890123456789012345678901234567890123456789012345678901234567890
     [exec]     				-->
     [exec]     			</body>
     [exec]     		</html>
     [exec]     	Finished executing commands.
```
[Log](https://testray.liferay.com/reports/production/logs/2023-09/test-1-26/test-portal-acceptance-pullrequest(master)/11261/functional-tomcat90-mysql57-chrome100-jdk8/31/21/jenkins-console.txt.gz?authuser=0)

[Log of passing run](https://testray.liferay.com/reports/production/logs/2023-10/test-1-25/test-portal-acceptance-pullrequest(master)/3621/functional-tomcat90-mysql57-chrome100-jdk8/6/4/jenkins-console.txt.gz?authuser=0)

2) Semver issues
```
     [exec] > Task :baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.uuid                     MAJOR      6.2.0      6.2.0      7.0.0      VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.portal.kernel.uuid.PortalUUIDUtil
     [exec] 		-   method     getPortalUUID()
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.uuid.PortalUUID
     [exec] 		-   method     setPortalUUID(com.liferay.portal.kernel.uuid.PortalUUID)
     [exec] 			-   return     void
     [exec] 	-   interface  com.liferay.portal.kernel.uuid.PortalUUID
     [exec] 		-   access     abstract
     [exec] 		-   method     fromJsSafeUuid(java.lang.String)
     [exec] 			-   access     abstract
     [exec] 			-   return     java.lang.String
     [exec] 		-   method     generate()
     [exec] 			-   access     abstract
     [exec] 			-   return     java.lang.String
     [exec] 		-   method     generate(byte[])
     [exec] 			-   access     abstract
     [exec] 			-   return     java.lang.String
     [exec] 		-   method     toJsSafeUuid(java.lang.String)
     [exec] 			-   access     abstract
     [exec] 			-   return     java.lang.String
     [exec] [Baseline Warning] Bundle Version Change Recommended: 126.0.0
```
[Log](https://testray.liferay.com/reports/production/logs/2023-09/test-1-26/test-portal-acceptance-pullrequest(master)/11261/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Comment by Kvale1733** [comment]
@jeffwu0724 Reopening this. Seems consistent for me locally but now I see it popping up on other PR's. It's not related. No regressions found.

**Comment by Kvale1733** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@kyle-miho Do we have the Service Builder backport tester up yet?

**Comment by vicnate5** [comment]
@catarineaguiar we don't have the automation for testing SB backports yet.  Can you test this manually? Need to check each 7.x version back to 7.0.x. Will send you the manual steps.

**Comment by catarineaguiar** [comment]
I'll finish this check tomorrow

**Comment by catarineaguiar** [comment]
Checked a few modules in each 7.x and it passed in all of them.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142167

**Pull request closed without merging**
