### PR TITLE
[Component with its own class name as service type] LPS-196245 Refactor ConfigurationActivator components from dynamic-data-list and dynamic-data-mapping modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-196245

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:data-engine

**Comment by catarineaguiar** [comment]
no regressions found

**Review by rafaprax — APPROVED** [review]

**Comment by MrJohn1911** [comment]
Last push fixes conflicts with master.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141352

**Pull request closed without merging**
