### PR TITLE
[Bug Fix] LPS-151272

### PR DESCRIPTION
**Pull request by dantewang**
Spring extender issue revealed by upgrading Hibernate. https://issues.liferay.com/browse/LPS-151272

### CODE REVIEW

**Comment by dantewang** [comment]
@vicnate5 @zhangyan0701 @Sharryxue @liuxingye Please trigger other tests you think necessary. Thanks!

@tinatian

**Comment by Sharryxue** [comment]
Will trigger the app-servers suite to run the tests in APP Manager components by waiting the [commit](https://github.com/brianchandotcom/liferay-portal/pull/116002) that added the related test to acceptance.

**Comment by dantewang** [comment]
@vicnate5 @zhangyan0701 Could you please review the test results? Thanks!

**Comment by vicnate5** [comment]
@tinatian No regressions found. Functional test that was previously failing from this issue is now passing.

**Comment by tinatian** [comment]
Thanks @vicnate5 , could you please also check https://github.com/liferay-core-infra/liferay-portal/pull/607, I move the logic to another place.

Tina.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/607

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
