### PR TITLE
LPD-29409 Fix DCLSingleton#getSingleton logic to return local snapshot singleton instead of _singleton to resolve concurrency issue

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:core-functional

**Comment by julschong** [comment]
ci:report:23951401

**Comment by julschong** [comment]
ci:report:23943698

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:24519112

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/151692

**Pull request closed without merging**
