### PR TITLE
[Remove Stream/Optional usage] LPS-173313  module:  talend-runtime

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-173313

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:sf

**Pull request closed without merging**
