### PR TITLE
[Method References 2] LPS-169774 Convert method reference to ServiceTrackerMap in module portal-search-admin-web

### PR DESCRIPTION
**Pull request by W2jx**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3080

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@W2jx No regressions.

**Comment by W2jx** [comment]
no conflicts(1/30 9:58)

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
Double check with QA.

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(2/1 10:06)

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129727

**Pull request closed without merging**
