### PR TITLE
[Method References 2] LPS-173984 Convert method reference to ServiceTrackerMap in class WorkflowMetricsSLACalendarRegistryImpl (module portal-workflow-metrics-service)

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:workflow-metrics

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(1/31 9:45)

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:workflow-metrics

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(2/7 14:08)

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:workflow-metrics

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(2/8 8:58)

**Comment by W2jx** [comment]
no conflicts(2/9 10:25)

**Comment by W2jx** [comment]
no conflicts(2/10 9:06)

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3454

**Pull request closed without merging**
