### PR TITLE
[Bug Fix] Faces-3625

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on the [requirement](https://github.com/liferay-core-infra/liferay-portal/pull/90#issuecomment-998524922). I found one example use unescaped portletName(portlet.getPortletName()) [example](https://github.com/yuhai/liferay-portal/blob/FACES-3625-pr2/portal-impl/src/com/liferay/portlet/PortletBagFactory.java#L202) as [filterString](https://github.com/yuhai/liferay-portal/blob/FACES-3625-pr2/portal-impl/src/com/liferay/portlet/internal/PortletBagImpl.java#L89).

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
Looks good to me. I think we can ignore the SF failure as "FACES" is not in SF's recognized ticket list.

**Comment by dantewang** [comment]
@zhangyan0701 Could you check the result of this pull? Thanks!

**Comment by zhangyan0701** [comment]
No related failures found.

**Comment by tinatian** [comment]
Hi @dantewang @yuhai ,
After checking portlet 3.0 spec, I believe it would be better to keep the portlet name unescaped in portlet config to make it consistent with the portlet name read from xml or annotation.

Please see my fix at https://github.com/liferay-core-infra/liferay-portal/pull/134, @yuhai please verify if this fixes the issue.

Thanks.
Tina

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
