### PR TITLE
[TS] LPS-177132 The theme of 404 page is broken

### PR DESCRIPTION
**Pull request by ces-totrinh**
Hi Team,
Please help review this PR and leave your comments. Thanks.
Ticket: https://issues.liferay.com/browse/LPS-177132

Explanation:
In addition to getting NullPointerException when accessing with /p/, we also get RuntimeException when accessing with other URL separators (Ex /b/, /k/).
The idea is to catch NullPointerException and RuntimeException instead of PortalExpception only.
cc @ces-huynguyen

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@tototrinh No regressions found and testing passed following ticket steps.

**Comment by tinatian** [comment]
@tototrinh You can not do this, you are swallowing exceptions which may tell people what is wrong. Please fix the NPE directly rather than swallowing.

Also, please add test to cover your changes.

Thanks.
Tina.

**Comment by ces-huynguyen** [comment]
@tinatian for the case of RuntimeException throws by https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/layout/display/page/JournalArticleLayoutDisplayPageProvider.java#L105 when URL is /web/guest/b/ and IndexOutOfBoundsException when URL is /web/guest/k/ . Can I swallow RuntimeException ?

**Pull request closed without merging**
