### PR TITLE
[Remove unused @Reference var] LPS-164057 

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove the unused @reference variable in `application-list-api`. Thanks!
CI test passed in https://github.com/JanisZhang/liferay-portal/pull/121

https://issues.liferay.com/browse/LPS-164057

### CODE REVIEW

**Comment by JanisZhang** [comment]
HI @catarineaguiar, Could you please help to scan the test results? thx

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by dantewang** [comment]
@JanisZhang Please update the commit message or split the commit, as you removed 4 references but only mentioned 2 in the message.

**Comment by JanisZhang** [comment]
@dantewang force-pushed. Thanks!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123986

**Pull request closed without merging**
