### PR TITLE
LPS-71164 Check loggers in `*-log4j.xml` files

### PR DESCRIPTION
**Pull request by kevhlee**
This pull request implements a SF rule that checks each logger defined in a `*-log4j.xml` file. Specifically, it checks if the class/package that the logger is defined for exists. For a portal module or module app (i.e. `modules/apps`, `modules/dxp/apps`), the SF rule will check the current module and its sibling modules. For example, for a logger defined in `journal/journal-service`, the SF rule will check in `journal/journal-api`, `journal/journal-web`, etc. For any other modules, the SF rule will only check the current module.

Let me know if this should be the intended behavior and/or if I need to change anything.

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
[Smoke test](https://testray.liferay.com/home/-/testray/case_results/2162922511) failed with error:
`java.lang.Exception: "Starting dynamic bundles" is not present in console /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/portalsmoke/PortalSmoke.testcase[Smoke]:53`

I checked the whole log, below INFO messages from `ModuleFrameworkImpl` didn't show up in portal log:
```
INFO  [main][ModuleFrameworkImpl:1287] Starting initial bundles
INFO  [main][ModuleFrameworkImpl:1586] Started initial bundles
INFO  [main][ModuleFrameworkImpl:1630] Starting dynamic bundles
INFO  [main][ModuleFrameworkImpl:1653] Started dynamic bundles
INFO  [main][ModuleFrameworkImpl:1660] Starting web bundles
INFO  [main][ModuleFrameworkImpl:1714] Started web bundles
INFO  [main][ModuleFrameworkImpl:281] Navigate to Control Panel > System > Gogo Shell and enter "lb" to see all bundles
```

Full console:
https://testray.liferay.com/reports/production/logs/2023-01/test-1-38/test-portal-acceptance-pullrequest(master)/5762/functional-tomcat90-mysql57-chrome100-jdk8/12/24/jenkins-console.txt.gz?authuser=0

**Comment by kevhlee** [comment]
Thanks @zhangyan0701!

The smoke test failure was definitely caused by my changes: <https://github.com/liferay-core-infra/liferay-portal/pull/3053/commits/36d51a597f5dc78590fab10996f140dbac48fd5c#diff-9b2b437a0860d5f9f2564a0f399e85b33741bf731e7316e29aa0a028970c0cb0L50>. I will need to re-work my pull request.

**Comment by kevhlee** [comment]
Resending pull request.

**Pull request closed without merging**
