### PR TITLE
LPS-146536

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@marianoalvarosaiz The test you added should not be integration tests, please move them to PortalImplUtilTest. I am going to close this pull, please resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by tinatian** [comment]
ci:reopen

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by tinatian** [comment]
@shuyangzhou This is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113612

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
