### PR TITLE
LPS-167572

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@kyle-miho Please help me add test for this, this also needs to test when the folder is a symbolic link.

Thanks.
Tina

**Comment by zhangyan0701** [comment]
Portal failed to startup, errors in console:
```
[beanshell] 2022-12-09 03:23:02.971 ERROR [Portal Spring Init Thread][ContextLoader:225] Context initialization failed
[beanshell] org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.portal.image.ImageToolImpl' defined in class path resource [META-INF/util-spring.xml]: Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError
[beanshell] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1323) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1218) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401) ~[spring-web.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292) ~[spring-web.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103) ~[spring-web.jar:5.2.22.RELEASE]
[beanshell] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.lambda$contextInitialized$1(PortalContextLoaderListener.java:273) ~[portal-impl.jar:?]
[beanshell] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
[beanshell] 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[beanshell] Caused by: java.lang.ExceptionInInitializerError
[beanshell] 	at com.liferay.portal.image.ImageToolImpl.<init>(ImageToolImpl.java:883) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.image.ImageToolImpl.<clinit>(ImageToolImpl.java:888) ~[portal-impl.jar:?]
[beanshell] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
[beanshell] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
[beanshell] 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:207) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1315) ~[spring-beans.jar:5.2.22.RELEASE]
[beanshell] 	... 16 more
[beanshell] Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [META-INF/services/javax.imageio.spi.ImageTranscoderSpi]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
```
Full console log:
https://testray.liferay.com/reports/production/logs/2022-12/test-1-30/test-portal-acceptance-pullrequest(master)/5695/functional-smoke-tomcat90-mysql57-jdk8_stable/0/0/jenkins-console.txt.gz?authuser=0

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@tinatian Errors appear on startup

```
    [junit] org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.portal.image.ImageToolImpl' defined in class path resource [META-INF/util-spring.xml]: Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError
    [junit] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1323) ~[spring-beans.jar:5.2.22.RELEASE]
    [junit] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1218) ~[spring-beans.jar:5.2.22.RELEASE]
    [junit] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556) ~[spring-beans.jar:5.2.22.RELEASE]
    [junit] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans.jar:5.2.22.RELEASE]
    [junit] 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans.jar:5.2.22.RELEASE]
    [junit] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans.jar:5.2.22.RELEASE]
    [junit] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans.jar:5.2.22.RELEASE]
    [junit] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans.jar:5.2.22.RELEASE]
    [junit] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans.jar:5.2.22.RELEASE]
    [junit] 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context.jar:5.2.22.RELEASE]
    [junit] 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context.jar:5.2.22.RELEASE]
    [junit] 	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401) ~[spring-web.jar:5.2.22.RELEASE]
    [junit] 	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292) ~[spring-web.jar:5.2.22.RELEASE]
    [junit] 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103) ~[spring-web.jar:5.2.22.RELEASE]
    [junit] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.lambda$contextInitialized$1(PortalContextLoaderListener.java:273) ~[portal-impl.jar:?]
    [junit] 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
    [junit] 	at java.lang.Thread.run(Thread.java:834) [?:?]
    [junit] Caused by: java.lang.ExceptionInInitializerError
    [junit] 	at com.liferay.portal.image.ImageToolImpl.<init>(ImageToolImpl.java:883) ~[portal-impl.jar:?]
    [junit] 	at com.liferay.portal.image.ImageToolImpl.<clinit>(ImageToolImpl.java:888) ~[portal-impl.jar:?]

```

[Log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-28/test-portal-acceptance-pullrequest(master)/5370/functional-smoke-tomcat90-mysql57-jdk11_open/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@tinatian Regressions found

Configs added to osgi/config are not applied. Works with any osgi config but you can test with this component blacklist config: https://drive.google.com/file/d/1WhpZj2lfcgOKOgTJpZ8Gf8wYWg1VSgqO/view?usp=sharing

Steps to reproduce
      i. Add a config file to osgi/configs
      ii. Check the config was applied in the portal (For the config I shared go to System Settings > Module Container > 
        Component Blaclist, and assert "com.liferay.portal.security.ldap.internal.authenticator.LDAPAuth" was added to Blacklist 
        Component Names)

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2854

**Pull request closed without merging**
