### PR TITLE
LPS-153305 Verify Properties

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks
Tina.

**Comment by tinatian** [comment]
@zhangyan0701 Please help me scan test results.

Thanks.
Tina

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by vicnate5** [comment]
@zhangyan0701 Can you add some testing scenarios to the test map for this change?

**Comment by shuyangzhou** [comment]
@tinatian for https://github.com/liferay-core-infra/liferay-portal/pull/760/commits/72582029fe1cd20a94803df9dae84c6d1cf6a112 , use SwappableSecurityManager to intercept the System.exit() call to assert the behavior, rather than not testing it.
Please change and resend.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/818

**Pull request closed without merging**
