### PR TITLE
LPS-145577 Avoid using HtmlUtil directly in modules

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina, Shuyang

Main Task: [LPS-143403](https://issues.liferay.com/browse/LPS-143403)
Sub Task: [LPS-145577](https://issues.liferay.com/browse/LPS-145577)

Thank you!

### CODE REVIEW

**Comment by tinatian** [comment]
@julschong Code conflicts, please rebase.

Thanks.
Tina.

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@tinatian pushed to resolve conflict.
Some methods from Html was extracted to HtmlParser

**Comment by julschong** [comment]
@tinatian the error from SF is unrelated but relevant and default failed to run. I will rebase and send again.
Closing this now.

**Pull request closed without merging**
