### PR TITLE
[Remove Stream/Optional usage] LPS-175366 module export-import-test-util

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-175366

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:export-import

**Comment by catarineaguiar** [comment]
ci:test:export-import

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by tinatian** [comment]
@JanisZhang Please try to simplify the logic in this method:
`@Override
	public DummyFolder fetchStagedModelByUuidAndGroupId(
		String uuid, long groupId) {

		List<DummyFolder> dummyFolders = ListUtil.filter(
			_dummyFolders,
			dummyFolder ->
				Objects.equals(dummyFolder.getUuid(), uuid) &&
				(dummyFolder.getGroupId() == groupId));

		if (dummyFolders.isEmpty()) {
			return null;
		}

		return dummyFolders.get(0);
	}`

**Comment by tinatian** [comment]
@JanisZhang Please review your other code logic and see if you can simplify.


Thanks.
Tina

**Pull request closed without merging**
