### PR TITLE
LPS-155682 Remove module.framework.properties.ds.*

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian , I have updated the code.

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results? Thanks!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
@tinatian why do we have to patch it to just change the default value?

**Comment by tinatian** [comment]
@shuyangzhou Just want to remove the properties from portal.properties. 
I could not think up a case that anyone wants to change this, if it is not going to be changed, why it is a property?

**Comment by shuyangzhou** [comment]
We should not create the patch just to change the default values which are already configurable. We did not create the properties in the first place, the scr did it. We should just keep config it using their properties.

**Comment by tinatian** [comment]
@shuyangzhou OK, then I would like to hard code these properties in ModuleFrameworkImpl rather than setting it in portal.properties, what do you think?

Tina

**Comment by shuyangzhou** [comment]
ok, still better than patching.

**Comment by tinatian** [comment]
@W2jx Please hard code the properties in ModuleFrameworkImpl and resend.

Thanks.
Tina.

**Comment by W2jx** [comment]
@tinatian I'll fix it.

**Pull request closed without merging**
