### PR TITLE
LPD-38384 patching org.eclipse.equinox.metatype to 1.4.400

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,
This is for https://liferay.atlassian.net/browse/LPP-56017.
I am trying to patching org.eclipse.equinox.metatype to 1.4.400 to include the fix https://git.eclipse.org/r/c/equinox/rt.equinox.bundles/+/121973/
Thanks for chekcing.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:core-functional

**Comment by jeffwu0724** [comment]
ci:report:34647885

**Comment by jeffwu0724** [comment]
core-functional:
https://testray.liferay.com/#/project/35392/routines/45357/build/34647885/case-result/34648444/history -- falky, passed in another run
https://testray.liferay.com/#/project/35392/routines/45357/build/34647885/case-result/34648536/history -- falky, passed in another run
https://testray.liferay.com/#/project/35392/routines/45357/build/34647885/case-result/34648540/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/34647885/case-result/34648848/history -- not related
https://testray.liferay.com/#/project/35392/routines/45357/build/34647885/case-result/34649112/history -- not related

**Comment by jeffwu0724** [comment]
ci:test:core-functional

**Comment by jeffwu0724** [comment]
ci:report:35727960

**Comment by jeffwu0724** [comment]
no unique regression found

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
