### PR TITLE
LPS-190302 Restructure AssetRendererFactoryRegistry - move interface into portal-kernel, move logic from Util to Impl

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
Some integration tests failed with error:
`java.lang.NoSuchFieldException: No field on null with name _classNameAssetRenderFactoriesServiceTrackerMap`

Failed tests:
com.liferay.portal.search.internal.result.SearchResultUtilTest
com.liferay.portal.search.internal.suggestions.spi.BasicSuggestionsContributorTest
com.liferay.search.experiences.internal.suggestions.spi.SXPBlueprintSuggestionsContributorTest

Full Jenkins log:
https://testray.liferay.com/reports/production/logs/2023-07/test-1-30/test-portal-acceptance-pullrequest(master)/7139/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0

**Comment by julschong** [comment]
pushed unit test fixes

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by julschong** [comment]
pushed to fix SF

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No regressions found. Only a semantic versioning issue:
```
     [exec] > Task :baseline
     [exec] [Baseline Warning] Bundle Version Change Recommended: 116.1.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/116.0.0/b4166ffdcb4f6857df2fd3a8f020d903a7c2cb9a/com.liferay.portal.kernel-116.0.0.jar
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-07/test-1-40/test-portal-acceptance-pullrequest(master)/4177/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by tinatian** [comment]
@julschong Why you have to set the ***Util? modules should use service reference directly https://github.com/liferay-core-infra/liferay-portal/pull/4973/commits/f6d22557fb75cb137c7919fcf09687cec04de961.

**Comment by julschong** [comment]
@tinatian **Util usages has 245 usages, I wanted to do seperate pulls to convert them to use @Reference

**Comment by tinatian** [comment]
@julschong Please do them together in one pull.

Thanks.
Tina

**Pull request closed without merging**
