### PR TITLE
[TS]LPD-19928-dxp-master

### PR DESCRIPTION
**Pull request by titokenzo**
I kept the InfrastructureUtil.getMailSession() method for (retro)compatibility purposes.
The new geNewMailSession() method is intended to work with different Virtual Instances.

### CODE REVIEW

**Comment by titokenzo** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @titokenzo ,

I took a quick look and had some thoughts:
- Since the methods involving **mailSession** in **InfrastructureUtil** are only being used by **MailServiceImpl**, I think we should instead extract those methods from **InfrastructureUtil** and place them into **MailServiceImpl**
    - This should help us simplify the logic in both **InfrastructureUtil** and **MailServiceImpl**
- Can you also provide a test for this issue?

Please let me know what you think and if you have any questions.
Thanks!

**Comment by ericyanLr** [comment]
Hi @titokenzo ,

Regarding my previous comment, I had an additional thought that the logic may not be best to be kept within the **ServiceImpl** class. However, I now realize these classes haven't been modularized and still reside within portal-kernel and portal-impl.

If this were modularized, I was thinking the mail sessions could be managed via a separate dedicated component. 

However, since this isn't modularized, I'm thinking the same as my previous comment:
1. Since the methods involving **mailSession** in **InfrastructureUtil** are only being used by **MailServiceImpl**, I think we should instead extract those methods from **InfrastructureUtil** and place them into **MailServiceImpl**
    - This should help us simplify the logic in both **InfrastructureUtil** and **MailServiceImpl**
2. Can you also provide a test for this issue?

Please let me know what you think and if you have any questions.
Thanks!

**Comment by titokenzo** [comment]
Hi @ericyanLr 

I also considered moving the logic to **MailServiceImpl**, but abandoned the idea due to compatibility issues. I don't know if there is a customer consuming this method and if I remove it, it will break their code.
About the test, you can follow the LPD description case: https://liferay.atlassian.net/browse/LPD-19928

**Comment by ericyanLr** [comment]
Hi @titokenzo ,

I think in 7.4, we are able to remove the API. I'll ping Tina to help us come up with a game plan.

As for the test, I'm not sure if you're referring to the steps to reproduce. But, normally we try to provide a unit or integration test for the issue, along with the fix.

@tinatian , can you help take a look and provide guidance on next steps? We're unsure what would be the best way to refactor the code and handle the API changes.

**Comment by tinatian** [comment]
@titokenzo I had a talk with @ericyanLr , he will send out a new pull.

Thanks.
Tina.

**Pull request closed without merging**
