### PR TITLE
LPS-161429 Remove stream usage in AddDefaultAssetVocabulariesPortalInstanceLifecycleListener

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:tango

**Comment by guilhermedcamacho** [comment]
@catarineaguiar please help me check the results when available, thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by guilhermedcamacho** [comment]
@shuyangzhou , this PR is ready for your review. Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122889

@guilhermedcamacho please cleanup stream/optional usages in InfoSearchClassMapperTrackerImpl too.

**Pull request closed without merging**
