### PR TITLE
[Replace Non-Blocking Usage] LPS-199954 

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace non-blocking ServiceProxyFactory usages in class `OpenSSOUtil`. Thanks.
https://liferay.atlassian.net/browse/LPS-199954
resent: https://github.com/liferay-core-infra/liferay-portal/pull/5895

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
No regressions found in startup or upgrades suite. Lots of aborted tests in relevant. Rerunning that.

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
Reviewing...

**Comment by melodywu** [comment]
The [relevant](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2452047576) and [startup](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2450304277) and [upgrade](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2451305330) results are look good to me.

cc @zhangyan0701

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
