### PR TITLE
[Method References 2] LPS-170715 Remove the class SettingsContributor and its only impl UnicastSettingsContributor

### PR DESCRIPTION
**Pull request by W2jx**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/2425

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(2/28 9:41)

**Comment by W2jx** [comment]
no conflicts(3/1 10:52)

**Review by dantewang — APPROVED** [review]
@W2jx Looks good to me, please send to Search team for extra review, as they may have different idea with the tests.

cc @tinatian

**Comment by W2jx** [comment]
see https://github.com/liferay-search/liferay-portal/pull/818

**Pull request closed without merging**
