### PR TITLE
[Company log servlet] LPS-154230

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on https://github.com/brianchandotcom/liferay-portal/pull/125109#issuecomment-1317023757
I only added the last commit. The fix doesn't merge to liferay/master branch. I fetched the fixes from BChan's master branch.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:stop

**Comment by yuhai** [comment]
ci:stop

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@yuhai No regressions found.

**Comment by yuhai** [comment]
@dantewang, I just rebased it based on the latest master. No changes, no need to trigger ci test.

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2502

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2502

**Pull request closed without merging**
