### PR TITLE
[Method References ] LPS-160434 Convert method references to field references in classes extend BasePanelApp

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian , I have resend it because the original [PR](https://github.com/liferay-core-infra/liferay-portal/pull/4229) code conflicts.  And all the tests passed.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4338

Changes:

1. Resolve code conflicts for class __className__SimulationPanelApp in this [commit](https://github.com/liferay-core-infra/liferay-portal/pull/4357/commits/e0d7264058c9a7d1cdfabc54ebc4badff545ff65)

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:object

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133905

**Pull request closed without merging**
