### PR TITLE
LPS-185768 Remove deprecated AMImageConfigration.imageMaxSize and AMImageSizeProviderImpl

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:lima

**Comment by zhangyan0701** [comment]
Semantic versioning issue:
```
     [exec] > Task :apps:adaptive-media:adaptive-media-image-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec]   com.liferay.adaptive.media.image.size              REMOVED    1.0.0      1.0.0      -          PACKAGE REMOVED, UNNECESSARY PACKAGEINFO
     [exec] [Baseline Warning] Bundle Version Change Recommended: 12.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.adaptive.media.image.api-11.3.1.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.adaptive.media.image.api/11.3.0/beac953e5df96476f8e449bcbf5e6e5e3b853f5d/com.liferay.adaptive.media.image.api-11.3.0.jar
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-06/test-1-35/test-portal-acceptance-pullrequest(master)/4225/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by julschong** [comment]
pushed baseline commit

**Comment by julschong** [comment]
pushed to correct testConfiguration typo

**Pull request closed without merging**
