### PR TITLE
[PowerMock] LPS-150074 Remove PowerMock, apps/wiki

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian @JanisZhang

### CODE REVIEW

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go. All the changes are about unit test and unit test batch passed.


Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115201

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
