### PR TITLE
[TS] LPD-31092 Upgrade ConfigAdmin to 1.9.26

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:configuration-framework

**Comment by dantewang** [comment]
ci:report:34623379

**Comment by dantewang** [comment]
ci:report:34611069

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 34611069.
> 
> Job Link: [generate-testray-csv](https://test-1-37.liferay.com/job/generate-testray-csv/237/)
> 
> Testray CSV Link: [testray-results-34611069.csv](https://test-1-37.liferay.com/userContent/jobs/generate-testray-csv/builds/237/testray-results-34611069.csv)

No unique failure in core-functional.

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 34623379.
> 
> Job Link: [generate-testray-csv](https://test-1-3.liferay.com/job/generate-testray-csv/100/)
> 
> Testray CSV Link: [testray-results-34623379.csv](https://test-1-3.liferay.com/userContent/jobs/generate-testray-csv/builds/100/testray-results-34623379.csv)

No unique failure in the integration tests marked as unique.

Re-run to verify PortalLogAssertorTest failures.

**Comment by tinatian** [comment]
ci:report:34854790

**Comment by tinatian** [comment]
@dantewang The unique failure is real, I sent a debug pull at https://github.com/liferay-core-infra/liferay-portal/pull/7236

**Pull request closed without merging**
