### PR TITLE
LPS-172505 Remove "immediate = true" from remaining Data Integration modules

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:data-integration

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions.

**Comment by MrJohn1911** [comment]
Hey @tinatian, can you review this pull? Thaks in advance.

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
