### PR TITLE
LPS-139179 move_SparseBitSet_to_share_dependencies

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-139179.
I am trying to move SparseBitSet to shared-dependencies.
Thanks for checking!

### CODE REVIEW

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
fixed the code conflict

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by tinatian** [comment]
@jeffwu0724 Please rebase.

Tina.

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
fixed code conflict

**Comment by zhangyan0701** [comment]
No regressions found.

**Pull request closed without merging**
