### PR TITLE
[PerformanceIntegrationTest-JspServletPerformanceTest] LPD-37148

### PR DESCRIPTION
**Pull request by ericyanLr**
**Ticket:** https://liferay.atlassian.net/browse/LPD-37148
**Previous PR:** https://github.com/liferay-core-infra/liferay-portal/pull/7534

Hi @tinatian ,

I wasn't sure if we wanted to add the Assume Test Rule in this PR. I'm assuming we would add it when our performance servers are ready to track these performance tests. Feel free to let me know if you would like me to include the additional commit.

Also, the additional commit regarding the JSP Servlet is to fix test failures that may occur if the tests are ran before the JSP Servlet is ready, which would result in a FileNotFoundException.

Please let me know if you have any questions.
Thanks!

/cc @slnn

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
**ci:report analysis**
The 2 reported unique failures are unrelated to our test class changes. 

Our test class test cases completed successfully, **with logged performance times**:
```
2024-10-23 04:34:53.399 INFO  [com.liferay.portal.osgi.web.servlet.jsp.compiler.test-executor-thread][BundleStartStopLogger:68] STARTED com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest_1.0.0 [1583]
2024-10-23 04:34:53.583 INFO  [com.liferay.portal.osgi.web.servlet.jsp.compiler.test-executor-thread][PerformanceTimer:131] Starting com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest#testElExpressionWithUndefinedScopedVariablesJsp
2024-10-23 04:34:53.822 INFO  [com.liferay.portal.osgi.web.servlet.jsp.compiler.test-executor-thread][PerformanceTimer:131] Completed com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest#testElExpressionWithUndefinedScopedVariablesJsp in 239 ms
2024-10-23 04:34:53.887 INFO  [com.liferay.portal.osgi.web.servlet.jsp.compiler.test-executor-thread][PerformanceTimer:131] Starting com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest#testElExpressionWithUndefinedVariablesJsp
2024-10-23 04:34:54.062 INFO  [com.liferay.portal.osgi.web.servlet.jsp.compiler.test-executor-thread][PerformanceTimer:131] Completed com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest#testElExpressionWithUndefinedVariablesJsp in 175 ms
2024-10-23 04:34:54.094 INFO  [com.liferay.portal.osgi.web.servlet.jsp.compiler.test-executor-thread][PerformanceTimer:131] Starting com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest#testJsp
2024-10-23 04:34:54.265 INFO  [com.liferay.portal.osgi.web.servlet.jsp.compiler.test-executor-thread][PerformanceTimer:131] Completed com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest#testJsp in 170 ms
2024-10-23 04:34:54.369 INFO  [com.liferay.portal.osgi.web.servlet.jsp.compiler.test-executor-thread][BundleStartStopLogger:71] STOPPED com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest_1.0.0 [1583]
```

Marking this as **QA Passed** and **Ready to Review (no regression)**

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/155605

**Pull request closed without merging**
