### PR TITLE
[Convert method references]LPS-162745 Convert method references to field references in module ex…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-162745

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Comment by dantewang** [comment]
@shuyangzhou @tinatian Forwarding this one as all tests passed review and changes are direct replacements.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123204

**Pull request closed without merging**
