### PR TITLE
[TS] LPS-169318 Overloading getPermissionWherePredicate with userIdColumn to be able to call the method with an explicitly given userIdColumn

### PR DESCRIPTION
**Pull request by evibudai**
Hi Team,

https://issues.liferay.com/browse/LPS-169318

Previous PR caused regression:https://github.com/liferay-core-infra/liferay-portal/pull/2697

**Solution:**
On [PTR-3540](https://issues.liferay.com/browse/PTR-3540?focusedCommentId=2819004&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2819004) I was advised to either change the failing test, or update InlineSQLHelper and create a new variation of getPermissionWherePredicate which accepts a specified userIdColumn. 
I chose this approach because this way I can fix a specific issue without changing the current behavior.

I tested in my local environment, and it worked like it is intended, the old query is called when we add null as userIdColumn.

Best regards,
Évi

### CODE REVIEW

**Comment by evibudai** [comment]
ci:test:sf

**Comment by evibudai** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by yuhai** [comment]
Hi @evibudai, 

If only applied one usage and added new methods to fix, it looks a little weird to me.  Without the fix, the request generated sql is as the follwoings:
```
select DLFileEntry.* from (select distinct DLFileEntry.fileEntryId from DLFileEntry inner join DLFileVersion on DLFileEntry.fileEntryId = DLFileVersion.fileEntryId where DLFileEntry.groupId = ? and DLFileVersion.status = ? and (DLFileEntry.folderId = ?) and DLFileVersion.fileEntryId in (select distinct ResourcePermission.primKeyId from ResourcePermission where ResourcePermission.companyId = ? and ResourcePermission.name = ? and ResourcePermission.scope = ? and ResourcePermission.viewActionId = ? and (ResourcePermission.roleId in (?, ?) or DLFileVersion.userId = ?))) tempDLFileEntry inner join DLFileEntry on tempDLFileEntry.fileEntryId = DLFileEntry.fileEntryId order by DLFileEntry.title asc
```
**DLFileVersion.userId = ?**  looks wired since the sub sql statement is selecting from ResourcePermission table. For the current getPermissionWherePredicate() usages, I checked their table all owned userId column (for example, JournalArticle table, the usage is in JournalArticleFinderImpl class). So the performance issue may happen in the other places.

I think userIdColumn check is not necessary in InlineSQLHelperImpl class. It should still be **ResourcePermissionTable.INSTANCE.ownerId**.  If the fix way is good to you, could you please do the fix in the new pr? And then we check if the fix can be passed by ci test.

Thanks,
Hai

**Comment by tinatian** [comment]
@evibudai Please see @yuhai 's comment, I am going to close it, please resend.

Thanks
Tina

**Comment by evibudai** [comment]
Hi @yuhai,

If I understand correctly, you're saying that the query before my fix looks weird because it uses DLFileVersion.userId = ? instead of ResourcePermissionTable.INSTANCE.ownerId, since this code 

			Expression<Long> ownerIdExpression =
				ResourcePermissionTable.INSTANCE.ownerId;

			if (userIdColumn != null) {
				ownerIdExpression = userIdColumn;
			}

will always replace the ResourcePermissionTable.INSTANCE.ownerId with the given userIdColumn, since all the tables have it, and it is not right.

If yes, I agree, that is why in my first fix I solved the issue like this:
[[TS] LPS-169318](https://github.com/liferay-core-infra/liferay-portal/pull/2798)
But it caused regression, and that is when I asked for help on PTR, and one of the advises was to override the method to be able to call it both the "old way", and with explicit userIdColumn, to not completely change the old behavior.

If my previous fix looks better, I have to make changes in the test case that failed.
Is it okay that way?

Best regards,
Évi

**Comment by yuhai** [comment]
Hi @evibudai,

Your first fix https://github.com/liferay-core-infra/liferay-portal/pull/2697 looks good to me. Please firstly try to fix the test. Please let me know if the test is hard to fix.

Best regards,
Hai

**Pull request closed without merging**
