### PR TITLE
LPS-199470 Merge SiteMembershipPolicyFactoryUtil into SiteMembershipPolicyUtil

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Shuyang,

This is for ticket https://liferay.atlassian.net/browse/LPS-199470.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hi team, 

The SF issue mentioned here https://github.com/liferay-core-infra/liferay-portal/pull/5824#issuecomment-1775578582 is not caused by my PR.

**Comment by jeffwu0724** [comment]
ci:stop

**Comment by jeffwu0724** [comment]
ci:test:relavant

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

SF issue not related

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/1/23 10:26am

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/3/23 8:57am

**Comment by shuyangzhou** [comment]
@jeffwu0724 please add breaking change report.

**Comment by jeffwu0724** [comment]
added back the breaking changes

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/6/23 8:26am

**Comment by jeffwu0724** [comment]
upgrade the commit message, didn't touch the logic. the previous test result should be good enough

**Comment by shuyangzhou** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6066

**Pull request closed without merging**
