### PR TITLE
[Scheduler]LPS-169890

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@tinatian 
com.liferay.portal.kernel.scheduler.CronTextUtilTest
```
[junit] Testcase: testYearlyRecurrenceByFirstDay(com.liferay.portal.kernel.scheduler.CronTextUtilTest):	Caused an ERROR
    [junit] null
    [junit] java.lang.NullPointerException
    [junit] 	at com.liferay.portal.kernel.test.ReflectionTestUtil.invoke(ReflectionTestUtil.java:202)
    [junit] 	at com.liferay.portal.kernel.scheduler.CronTextUtilTest._toCronText(CronTextUtilTest.java:248)
    [junit] 	at com.liferay.portal.kernel.scheduler.CronTextUtilTest.testYearlyRecurrenceByFirstDay(CronTextUtilTest.java:205)
    [junit] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    [junit] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
```
[Log](https://testray.liferay.com/reports/production/logs/2022-11/test-1-39/test-portal-acceptance-pullrequest(master)/1992/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)


central-requirements-jdk8/0/0
```
 [junit] Testcase: testScanGradleFiles(com.liferay.portal.modules.ModulesStructureTest):	FAILED
    [junit] Please delete the unused testCompile dependencies in modules/dxp/apps/portal-reports-engine-console/portal-reports-engine-console-web/build.gradle
    [junit] junit.framework.AssertionFailedError: Please delete the unused testCompile dependencies in modules/dxp/apps/portal-reports-engine-console/portal-reports-engine-console-web/build.gradle
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest._testGradleFile(ModulesStructureTest.java:1512)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest.access$800(ModulesStructureTest.java:68)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest$4.visitFile(ModulesStructureTest.java:402)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest$4.visitFile(ModulesStructureTest.java:376)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest.testScanGradleFiles(ModulesStructureTest.java:374)

```
[Log](https://testray.liferay.com/reports/production/logs/2022-11/test-1-39/test-portal-acceptance-pullrequest(master)/1962/central-requirements-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127203

**Pull request closed without merging**
