### PR TITLE
[Remove Stream/Optional usage] LPS-173753 module: segments-context-vocabulary part 1

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend, thanks!
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3227
https://issues.liferay.com/browse/LPS-173753

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:tango

**Comment by zhangyan0701** [comment]
ci:test:tango

**Comment by zhangyan0701** [comment]
Many segmentation tests failed due to a blocker which will be fixed in https://github.com/brianchandotcom/liferay-portal/pull/130567. It's better to re-trigger the tests when the fix got merged.

**Comment by Kvale1733** [comment]
ci:test:tango

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
