### PR TITLE
[TS] LPS-182850

### PR DESCRIPTION
**Pull request by Mikellorza**
https://liferay.atlassian.net/browse/LPS-182850

Description
-----
Add configuration to the product to not log the exception trace to the log in freemarker code. So, for that I added a new configuration to do that in the freemarker engine configurations and with that we can hide the exception stack trace in the log.

### CODE REVIEW

**Comment by Mikellorza** [comment]
Hi @tinatian ,

Please, look at this PR if it fits for you.

Thanks for your comments

**Comment by catarineaguiar** [comment]
@Mikellorza no regressions were found.

formatting issue:

```
format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/portal-template/portal-template-freemarker/src/main/java/com/liferay/portal/template/freemarker/configuration/FreeMarkerEngineConfiguration.java expected:<...ables();
     [java] 
     [java] 	@Meta.AD([
     [java] 		deflt = "false", name = "log-template-exceptions", required = false
     [java] 	])
     [java] 	public boolean lo...> but was:<...ables();
     [java] 
     [java] 	@Meta.AD([deflt = "false", name = "log-template-exceptions", required = false])
     [java] 	public boolean lo...>
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:466)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:299)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-07/test-1-7/test-portal-source-format/5285/source-format-current-branch-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by catarineaguiar** [comment]
@Mikellorza I got this message in the logs and in the preview panel:
please, can you confirm if its the expected behaviour?

```
2023-07-18 17:40:30.866 ERROR [http-nio-8080-exec-4][FragmentRendererControllerImpl:122] Unable to render content of fragment entry 1:com.liferay.fragment.exception.FragmentEntryContentException: FreeMarker syntax is invalid.

The following has evaluated to null or missing:
==> test  [in template "template_id" at line 2, column 11]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${test}  [in template "template_id" at line 2, column 9]
----, FreeMarker syntax is invalid.

The following has evaluated to null or missing:
==> test  [in template "template_id" at line 2, column 11]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${test}  [in template "template_id" at line 2, column 9]
----
2023-07-18 17:40:37.998 ERROR [http-nio-8080-exec-7][FragmentRendererControllerImpl:122] Unable to render content of fragment entry 1:com.liferay.fragment.exception.FragmentEntryContentException: FreeMarker syntax is invalid.

The following has evaluated to null or missing:
==> test  [in template "template_id" at line 2, column 11]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${test}  [in template "template_id" at line 2, column 9]
----, FreeMarker syntax is invalid.

The following has evaluated to null or missing:
==> test  [in template "template_id" at line 2, column 11]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${test}  [in template "template_id" at line 2, column 9]
----
```

image

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
Hey @catarineaguiar ,

Yes, it is the expected behavior, is the log of the application and is not the error stacktrace of the freemarker template processor .

Thanks

**Comment by catarineaguiar** [comment]
@Mikellorza so no regressions were found.

Thanks!

**Comment by tinatian** [comment]
@Mikellorza Please see https://github.com/brianchandotcom/liferay-portal/pull/138203, please note that I merged the first two commits and provide the reason why the default value is false.

Thanks.
Tina.

**Pull request closed without merging**
