### PR TITLE
LPD-41153 Pre-populate some data related to object definition to avoid extra SQL calls on portal startup

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
Related issue : [LPD-41153](https://liferay.atlassian.net/browse/LPD-41153)

CI and review : https://github.com/liferay-bpm/liferay-portal/pull/3904

Old review : https://github.com/liferay-core-infra/liferay-portal/pull/7640#issuecomment-2487470018

Motivation:
 
 Reduce the need for additional SQL calls on startup.
 

[LPD-41153]: https://liferay.atlassian.net/browse/LPD-41153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by liferay-search** [comment]
@JerryAdrianoo could you please test it?
fyi @shuyangzhou

**Comment by brunofalc** [comment]
@JerryAdrianoo could you please test it?
fyi @shuyangzhou

**Comment by JerryAdrianoo** [comment]
Hi, see the results below:

Branch| Startup Time (ms)(without  default HSQL data)  Cold start | Percent of Average Startup Time Cold Start | Startup Time (ms)(without  default HSQL data) Hot start | Average Startup Time (ms)(without default HSQL data)  Hot start | Percent of Average Startup Time Hot Start | Shutdown Time (ms)(without default HSQL data)   Cold start | Shutdown Time (ms)(without default HSQL data)  Hot start | Average Shutdown Time (ms)(without default HSQL data)  Hot start
-- | -- | -- | -- | -- | -- | -- | -- | --
Before LPD-41167 | **41,234** | | 16,535 | | | **2,416** | 1,923
|  | | | 16,031 | | | | 1,933
|  | | | 16,421 | | | | 1,911
 | | | | 16,059 | | | | 1,925
 | | | | 16,121|**16,200** | | | 1,965 | **1,927**
-- | -- | -- | -- | -- | -- | -- | --
After LPD-41167 | **42,030** | | 16,095 | | | **2,435** | 1,945
|  | | | 16,199 | | | | 1,975
|  | | | 16,606 | | | | 1,903
|  | | | 15,570 | | | | 1,953
| | |  4.93% | 15,955 |**16,083** |  **-0.72%** | | 1,946 | **1,948**

For more results, please take a look at the [spreadsheet](https://docs.google.com/spreadsheets/d/1fSPujeTJX0vxSz1YPf5V8h8vq_ilBU0VY9gEVox2DHA/edit?usp=sharing). 
No regression occurred in the startup time, but the same improvement as the previous PR is also in this one. See:

| Baseline | Open count of Prepared Statement | Count of Prepared Statement Query | Open Count of SQL |
|--------|--------|--------|--------|
78652fda | 148 | 222 | 846 |
LPD-41167 | 134 | 201 | 843 | 

Apart from that, no improvement or regression happened.

**Comment by gabrielwas** [comment]
Hi @JerryAdrianoo! 
Thanks for the analysis.

As expected, improving the startup time is not our main focus right now. The focus is taking the count of prepared statements down. That way, the more system objects we have, the count of prepared statements should remain the same (or, at least, almost the same).

**Comment by JerryAdrianoo** [comment]
Thanks @gabrielwas and @pedro-oliveira446 for working on it.

Digging deeper, I analyzed which queries were modified. See:

```
3 fewer queries - select objectrela0_.objectRelationshipId as objectre1_13_,..."

all excess queries were removed (3) - select objectlayo0_.objectLayoutId as objectla1_8_,..."

all excess queries were removed (3) - "select objectacti0_.objectActionId as objectac1_0_..."

1 additional query added (1) - select objectfiel0_.objectFieldId as objectfi1_3_,..."

1 additional query added (1) - select objectdefi0_.objectDefinitionId as objectde1_1_..."
```
In summary: we had 9 queries reduced, but another 2 prepared statement queries increased.

cc @shuyangzhou @tinatian

**Comment by shuyangzhou** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7695

**Pull request closed without merging**
