### PR TITLE
[Remove Blocking Usages] LPS-188565 Removing Unnecessary Usages of ServiceProxyFactory.newServiceTrackedInstance with blocking set to true in class FriendlyURLNormalizerUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
no conflicts(11/1 9:03)

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(11/2 8:14)

**Comment by W2jx** [comment]
no conflicts(11/3 8:52)

**Comment by W2jx** [comment]
no conflicts(11/6 8:35)

**Comment by W2jx** [comment]
no conflicts(11/7 9:34)

**Comment by W2jx** [comment]
no conflicts(11/8 10:05)

**Comment by W2jx** [comment]
no conflicts(11/9 9:58)

**Comment by dantewang** [comment]
@W2jx `ToolDependencies.wireBasic()` already has

```
		BundleContext bundleContext = SystemBundleUtil.getBundleContext();

		bundleContext.registerService(
			FullNameGenerator.class, new DefaultFullNameGenerator(), null);
```

I believe you can also do it for `FriendlyURLNormalizer`.

Please double check and resend, thanks!

**Pull request closed without merging**
