### PR TITLE
LPS-150781 Remove streambuffer.jar, mimepull.jar, saaj-api.jar and saaj-impl.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @koor4356, Can you please scan these test results? Thx

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
@rafaprax 
This looks good, thanks!

**Comment by shuyangzhou** [comment]
@rafaprax if @vicnate5 can confirm jdk11 is not an issue here, you can leave out stax.jar from this pull to deal with it separately.

**Comment by vicnate5** [comment]
ci:test:jdk11

**Comment by vicnate5** [comment]
We just ran a smoke test on JDK11 so far, I triggered more testing. 

If portal starting is enough, this can move forward, but if not we can look at the JDK11 results when they come in.

**Comment by vicnate5** [comment]
ci:test:jdk11

**Comment by vicnate5** [comment]
ci:test:jdk11

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-core-infra/liferay-portal/pull/568

**Pull request closed without merging**
