### PR TITLE
[Static reference] LPS-182671 Remove method reference by using snapshot in module commerce-product-type-virtual-order-content-web and message-boards-api

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
ci:test:message-boards

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by W2jx** [comment]
no conflicts(4/27 11:15)

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(4/28 10:42)

**Comment by dantewang** [comment]
@W2jx 
1. Please send the commerce one separately;
2. Please see if you can remove the `MBDiscussionPermissionChecker` completely. The interface is deprecated and its util now uses `ModelResourcePermission` and `PortletResourcePermission` first.

**Pull request closed without merging**
