### PR TITLE
remove_unused_properties_part2

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian , @shuyangzhou ,

I have removed five groups of unused properties, and they are "**auto.deploy.websphere.wsadmin.app.manager.**", "**control.panel.navigation.max.organizations**", "**control.panel.navigation.max.sites**", "**Index.with.thread**", "**index.dump.compression.enabled**",

"**auto.deploy.websphere.wsadmin.app.manager.**"- https://github.com/tinatian/liferay-portal/pull/2485
"**control.panel.navigation.max.organizations**"- https://github.com/tinatian/liferay-portal/pull/2494
"**control.panel.navigation.max.sites**"- https://github.com/liferay-core-infra/liferay-portal/pull/227
"**Index.with.thread**"- https://github.com/liferay-core-infra/liferay-portal/pull/261
"**index.dump.compression.enabled**"- https://github.com/liferay-core-infra/liferay-portal/pull/211

Thanks for checking!

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@jeffwu0724 Please update this commit message
`LPS-145171 - remove file "wsadmin.py", based on commit e930ab6f2b44e116a95a6390366a6c88d83d127e, see LPS-61201, and removed unused properties "auto.deploy.websphere.wsadmin.app.manager."
`

Both wsadmin.py and the property usages are not removed by commit e930ab6f2b44e116a95a6390366a6c88d83d127e, this commit just extract the logic into different classes, no logic changed. The actual removal happened at 0329a4c1b9dfc0a89c300f2aa9a4a82d5fe86739 (LPS-61201).

You can just modify the commit message locally and do a force push.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test:app-servers

**Comment by pyoo47** [comment]
ci:stop

Stopping and restarting due to ci-infrastructure bug

**Comment by pyoo47** [comment]
ci:test:app-servers

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by vicnate5** [comment]
@shuyangzhou Failure here is a random startup error on a partitioned database. It is not likely related to this PR as it passed on previous test runs here.
https://testray.liferay.com/reports/production/logs/2022-02/test-1-34/test-portal-acceptance-pullrequest(master)/897/functional-upgrade-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:stable

**Comment by jeffwu0724** [comment]
@shuyangzhou @vicnate5 , It showed some formatting issues on "./portal-impl/src/com/liferay/portal/verify/VerifyProperties.java" based on the ci:test:sf report. I have fixed it and make a new commit. Hope this with fix the SF test failure. Thanks you guys for checking!

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113583

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
