### PR TITLE
[Components with more than 1 service] LPS-179353 Refactor ScreenNavigationCategory components from Commerce modules part 3

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions. Only a semver issue
```
[exec] 
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/commerce/commerce-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.commerce.constants                     MINOR      12.5.0     12.5.0     12.6.0     VERSION INCREASE REQUIRED
     [exec]     	<   class      com.liferay.commerce.constants.CommerceTaxScreenNavigationConstants
     [exec]     		+   field      CATEGORY_KEY_REMOTE_CONFIGURATION
     [exec]     			+   access     final
     [exec]     			+   access     static
     [exec]     			+   constant   remote-configuration
     [exec]     			+   return     java.lang.String
     [exec]     		+   field      CATEGORY_KEY_TAX_RATES
     [exec]     			+   access     final
     [exec]     			+   access     static
     [exec]     			+   constant   tax-rates
     [exec]     			+   return     java.lang.String
     [exec]     		+   field      CATEGORY_KEY_TAX_RATING_SETTINGS
     [exec]     			+   access     final
     [exec]     			+   access     static
     [exec]     			+   constant   tax-rate-settings
     [exec]     			+   return     java.lang.String
     [exec]     		+   field      ENTRY_KEY_REMOTE_CONFIGURATION
     [exec]     			+   access     final
     [exec]     			+   access     static
     [exec]     			+   constant   remote-configuration
     [exec]     			+   return     java.lang.String
     [exec]     		+   field      ENTRY_KEY_TAX_RATES
     [exec]     			+   access     final
     [exec]     			+   access     static
     [exec]     			+   constant   tax-rates
     [exec]     			+   return     java.lang.String
     [exec]     		+   field      ENTRY_KEY_TAX_RATING_SETTINGS
     [exec]     			+   access     final
     [exec]     			+   access     static
     [exec]     			+   constant   tax-rate-settings
     [exec]     			+   return     java.lang.String
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 60.1.0
```
[Logs](https://testray.liferay.com/reports/production/logs/2023-03/test-1-35/test-portal-acceptance-pullrequest(master)/3969/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Review by rafaprax — CHANGES_REQUESTED** [review]

**Comment by MrJohn1911** [comment]
@rafaprax I just changed the constants name and applied the baseline.

**Comment by rafaprax** [comment]
Hey @MrJohn1911, let's just run the ci:test:relevant one.

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions. Only a semver issue.
```
java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
= ================================================== ========== ========== ========== ========== ==========
* com.liferay.commerce.product.servlet.taglib.ui.constants MINOR      1.1.0      1.1.0      1.2.0      VERSION INCREASE REQUIRED
	<   class      com.liferay.commerce.product.servlet.taglib.ui.constants.CPInstanceScreenNavigationConstants
		+   field      CATEGORY_KEY_INVENTORY
			+   access     final
			+   access     static
			+   constant   inventory
			+   return     java.lang.String

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at com.liferay.semantic.versioning.SemanticVersioningTest.testSemanticVersioning(SemanticVersioningTest.java:82)
```
[Log](https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/186009/testReport/com.liferay.semantic.versioning/SemanticVersioningTest/testSemanticVersioning__apps_commerce_commerce_product_api_/)

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Review by rafaprax — APPROVED** [review]

**Comment by zhangyan0701** [comment]
Semantic versioning issue:
```
     [exec] > Task :apps:commerce:commerce-product-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.commerce.product.servlet.taglib.ui.constants MINOR      1.1.0      1.1.0      1.2.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.commerce.product.servlet.taglib.ui.constants.CPInstanceScreenNavigationConstants
     [exec] 		+   field      CATEGORY_KEY_INVENTORY
     [exec] 			+   access     final
     [exec] 			+   access     static
     [exec] 			+   constant   inventory
     [exec] 			+   return     java.lang.String
     [exec] [Baseline Warning] Bundle Version Change Recommended: 62.2.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.commerce.product.api-62.1.1.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.commerce/com.liferay.commerce.product.api/62.1.0/63d13b6d9dea3fe5435c8bf6e3e7151ea4b38c01/com.liferay.commerce.product.api-62.1.0.jar
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-03/test-1-37/test-portal-acceptance-pullrequest(master)/10261/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by MrJohn1911** [comment]
This push is related to the baseline.

**Comment by MrJohn1911** [comment]
ci:test:sf

**Pull request closed without merging**
