### PR TITLE
[Components with more than 1 service] LPS-185248 Refactor Asset components from remaining asset modules

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**
Hello reviewer, PR removes the interface _GCloudNaturalLanguageDocumentAssetAutoTagger_ , OpenNLPDocumentAssetAutoTagger  because it was deprecated, in this Pull request => [https://github.com/brianchandotcom/liferay-portal/pull/74856](https://github.com/brianchandotcom/liferay-portal/pull/74856)

This ticket => [https://issues.liferay.com/browse/LPS-97123](https://issues.liferay.com/browse/LPS-97123)

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:auto-tagging

**Comment by GabrielHenriquedev** [comment]
ci:test:auto-tagging

**Comment by GabrielHenriquedev** [comment]
ci:test:relevant

**Comment by GabrielHenriquedev** [comment]
ci:test:auto-tagging

**Comment by Kvale1733** [comment]
@GabrielHenriquedev No regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:auto-tagging

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@GabrielHenriquedev @rafaprax Code looks good to me, but https://github.com/liferay-core-infra/liferay-portal/pull/4699/commits/b1f864217cd254848ca7a10ff180089e64552b23 and https://github.com/liferay-core-infra/liferay-portal/pull/4699/commits/a62bfcfbb5e6acdfb3d04b11caece0c9bdbcc169 say "because it's deleted", shouldn't it be "because it's deprecated"?

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136077

@GabrielHenriquedev I went ahead and modified the commit message to "deprecated".

**Pull request closed without merging**
