### PR TITLE
[TECHNICAL SUPPORT] LPS-152166 UserPortraitTag does not setAttributes for jsp override

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

I resent due to conflict
Previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/724

### CODE REVIEW

**Comment by NemethNorbert** [comment]
> @NemethNorbert I am wondering if you tested your code. Based on the code, it seems the property you set is not read.
> 
> Base on my knowledge about frontend, you have to bring back the init.jsp and page.jsp to read those properties which means trigger a jsp page render.
> 
> I can accept this pull if you are sure this works well functionally as the performance test result looks good to me. Please rebase to fix code conflicts.
> 
> Thanks. Tina

Hey @tinatian ,

We inlined the jsp and my modification does not change our current usage of userPortraitTag, However when a customer customise the init and page.jsp, they will be able to access these attributes.
 I resolved the conflict and force pushed the branch.
 
 Thanks,

**Comment by tinatian** [comment]
@NemethNorbert This is really weird. As the developer of framework, you added something to the code just for one customer's using. Basically it is just some attribute setting, why we can not initialize the attribute inside the customer's init.jsp?

**Comment by tinatian** [comment]
@NemethNorbert Any update?

**Comment by tinatian** [comment]
@NemethNorbert 

> We were not able to initialise these attributes, as we were missing the attributes from the request object. 
What is missing? How complex is it to initialize it by customer code?

Let's try our best to provide this customer a solution as this is the only customer complains about this. I really do not want to add some attributes to the code what everyone can see and but only few people know what it is for, even if you know what it is for now, you may also forget it after a while, this is going to make the framework code hard to understand and maintain. People may clean up your code when they found that no one is using it in our code base, and your customer code would fail another time.

Tina.

**Comment by NemethNorbert** [comment]
> @NemethNorbert
> 
> > We were not able to initialise these attributes, as we were missing the attributes from the request object.
> 
> What is missing? How complex is it to initialize it by customer code?
> 
> Let's try our best to provide this customer a solution as this is the only customer complains about this. I really do not want to add some attributes to the code what everyone can see and but only few people know what it is for, even if you know what it is for now, you may also forget it after a while, this is going to make the framework code hard to understand and maintain. People may clean up your code when they found that no one is using it in our code base, and your customer code would fail another time.
> 
> Tina.

Hey @tinatian ,

The attributes were missing from the request object, this is what I provided with my changes. I did not find any way to customise the portraitTag without these attributes in the request. While we did inline the jsp files and we no longer need the attributes in our codebase, it does make sense to provide them for customisation purposes. For example a customer who customised the taglib for 7.0 and still wishes to maintain their customisation on 7.3

If you know a way how to customise the taglib without these attributes in the request, please share it.

Thanks,

**Comment by tinatian** [comment]
@NemethNorbert If that's the case, try to move initialization of those attributes to the init.jsp of customer's customization. 

As a framework, we can not make every people happy as there are many different requirements especially you are trying to customize Liferay's code. 

Before, we recommend people to customize and flexibility is one of the selling point. Now, all different kinds of customization are becoming more and more heavy as we keep releasing new versions. The pain we have with upgrading is more and more serious. 

As Brian explained in this meeting about customer bundle compatibility, we have to make several customers not that satisfied to bring more valuable features to all other customers see https://drive.google.com/file/d/1qBlQv-nsVmaZPdc2IY7GOzRQJOvZD_us/view 
 and https://liferay.dev/blogs/-/blogs/7-4-custom-bundle-compatibility.

So you only have one customer want to do this customization, then solution should be done in the customer side and it can be done in the customer side based on the requirement. If you have more then 10 customers having same issue, we may consider a general solution for them, but for now, there is only one, yes, it is possible we have more, but let's talk about them when we met.

I am going to close this pull, please try to move the initialization to an init.jsp page for that customer, please feel free to let me know if you have any blockers.

Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
