### PR TITLE
[Remove Spring extender usages] LPS-159581

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, @tinatian, It is the final pr for commerce-service module. The last commit is using LocalServiceUtil to break the circular dependency.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:commerce

**Comment by yuhai** [comment]
@catarineaguiar, could you please check the test result? Thanks.

**Comment by catarineaguiar** [comment]
@yuhai no regressions found.

**Comment by dantewang** [comment]
@yuhai As we talked in the last discussion, BChan may not like the persistence way. Could you also update them to use Util and send another PR?
cc @tinatian

**Comment by tinatian** [comment]
@yuhai Per @dantewang 's comment, I am going to close this pull, please resend.

Thanks.
Tina

**Pull request closed without merging**
