### PR TITLE
LPS-156316 Removing blocking from PortalCacheManager

### PR DESCRIPTION
**Pull request by julschong**
@tinatian 
Hi Tina,
[LPS-156316 Remove blocking cache from PortalCacheManger API](https://issues.liferay.com/browse/LPS-156316)

resubmitted from #1002 

I ended up running `gw :apps:portal-cache:portal-cache-api:baseline` to manually update it

Thank you!

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by julschong** [comment]
rebased to resolve conflict in [LPS-156316 Auto semantic versioning](https://github.com/liferay-core-infra/liferay-portal/pull/1015/commits/3e63a6f5674861d918c1a89e030397011dafa539)

**Comment by julschong** [comment]
resolve conflict in 

> portal-kernel/bnd.bnd

**Comment by julschong** [comment]
rebased to resolve conflict in [LPS-156316 Auto semantic versioning](https://github.com/liferay-core-infra/liferay-portal/pull/1015/commits/bec78a4ce94e8f295ded9e5b95747182cbed02e3)

**Pull request closed without merging**
