### PR TITLE
[Convert method references]Lps 162719

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-162719

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Comment by slnn** [comment]
ci:test:commerce

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
@catarineaguiar Could you check the test results? Thanks!

**Comment by catarineaguiar** [comment]
@slnn no regressions found.

**Comment by dantewang** [comment]
@shuyangzhou @tinatian Forwarding this one as all tests passed review and changes are simple.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123671

**Pull request closed without merging**
