### PR TITLE
LPS-185105 Remove Multiple Configurations for IndexStatusManagerImpl

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
Some integration tests failed with NPE error.
[com.liferay.portal.search.internal.index.IndexStatusManagerImplRequireIndexReadWriteTest](https://testray.liferay.com/home/-/testray/case_results/2317780061).
Full console log:
https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8309/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by julschong** [comment]
pushed unit test fix

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No regressions found.

**Pull request closed without merging**
