### PR TITLE
[Reference cleanup]LPS-162298

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to convert method references to field references in frontend-*. Thanks!

https://issues.liferay.com/browse/LPS-162298

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @Kvale1733,  Could you please help to scan the test results? Thank you

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

**Comment by dantewang** [comment]
@tinatian @shuyangzhou Triggered forward as it contains simple replacements and passed CI.

**Pull request closed without merging**
