### PR TITLE
[TS] LPS-171056

### PR DESCRIPTION
**Pull request by yuhai**
@tinatian, @dantewang 

The previous pr is https://github.com/liferay-core-infra/liferay-portal/pull/2958

@IstvanD, I tested the issue and it worked on Windows. Could you please test it again? Thanks.

cc @Kvale1733

### CODE REVIEW

**Comment by IstvanD** [comment]
Hi @yuhai I tested your solution on Windows and it worked splendidly. Thank you!

**Comment by dantewang** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by Kvale1733** [comment]
@yuhai No regressions. The functional test I created also passes.

**Comment by IstvanD** [comment]
Dear Team,

Please let me know if there are any updates on the review.

Thank you and best regards,
István

**Pull request closed without merging**
