### PR TITLE
[Method References ] LPS-160434 Convert method references to field references in classes extend BasePanelApp

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts（4/14 11:18）

**Comment by W2jx** [comment]
no conflicts(4/17 8:08)

**Comment by W2jx** [comment]
no conflicts(4/18 9:28)

**Comment by W2jx** [comment]
no conflicts(4/19 8:03)

**Comment by W2jx** [comment]
no conflicts(4/20 7:56)

**Comment by W2jx** [comment]
no conflicts(4/21 8:22)

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4338

**Pull request closed without merging**
