### PR TITLE
[ServiceProxyFactory] LPS-188272 Inline CompositePasswordEncryptor into PasswordEncryptorUtil | 10-9

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
Relevant executed in https://github.com/liferay-core-infra/liferay-portal/pull/5613, this PR fixes the issue QA found in the last run.

**Comment by dantewang** [comment]
ci:test:stable

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
@shuyangzhou QA passed.

**Comment by shuyangzhou** [comment]
ci:forward:force

**Pull request closed without merging**
