### PR TITLE
LPS-154947 System properties

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
ci:test:stop

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
ci:abort

**Comment by catarineaguiar** [comment]
ci:test:abort

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
all the PR analysis on CI were aborted according to this [message](https://liferay.slack.com/archives/C19PWQ74J/p1659633528796189) 

when this runs finish, will need to re-run relevant.

**Comment by catarineaguiar** [comment]
@tinatian regression found:

```
   [exec] /opt/dev/projects/github/liferay-portal/modules/apps/static/portal-lpkg-deployer/portal-lpkg-deployer-test/src/test/java/com/liferay/portal/lpkg/deployer/LPKGVersionChangeLogAssertorTest.java:48: error: cannot find symbol
     [exec] 		String liferayHome = SystemProperties.get("liferay.home");
     [exec] 		                     ^
     [exec]   symbol:   variable SystemProperties
     [exec]   location: class LPKGVersionChangeLogAssertorTest
     [exec] 1 error
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:static:portal-lpkg-deployer:portal-lpkg-deployer-test:compileTestJava'.
     [exec] > Compilation failed; see the compiler error output for details.
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:static:portal-lpkg-deployer:portal-lpkg-deployer-test:compileTestJava'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:208)
     [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:206)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:187)
     [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
     [exec] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-26/test-portal-acceptance-pullrequest(master)/4309/lpkg-controller-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Tina

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Tina

**Comment by tinatian** [comment]
@W2jx Please always keep an eye on your pull.

Tina.

**Comment by catarineaguiar** [comment]
@tinatian @W2jx sorry the delay. Possible regression:

`DefaultMessagingConfiguratorTest`
```
 [exec] com.liferay.portal.messaging.test.DefaultMessagingConfiguratorTest > testPortalClassLoaderDestinationConfiguration FAILED
     [exec]     java.lang.AssertionError: Thread Thread[liferay/portaltest2-1-dispatcher,5,] caught concurrent failure: java.lang.AssertionError: Uncaught exception in Thread[liferay/portaltest2-1-dispatcher,5,main], java.lang.NullPointerException
     [exec]     java.lang.AssertionError: Uncaught exception in Thread[liferay/portaltest2-1-dispatcher,5,main], java.lang.NullPointerException
     [exec]     	at com.liferay.portal.test.rule.LogAssertionUncaughtExceptionHandler.uncaughtException(LogAssertionUncaughtExceptionHandler.java:40)
     [exec]     	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
     [exec]     	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
     [exec]     	at java.lang.Thread.dispatchUncaughtException(Thread.java:1956)
     [exec]     	Suppressed: java.lang.AssertionError: Uncaught exception in Thread[liferay/portaltest2-1-dispatcher,5,main], java.lang.NullPointerException
     [exec]     		at com.liferay.portal.test.rule.LogAssertionUncaughtExceptionHandler.uncaughtException(LogAssertionUncaughtExceptionHandler.java:40)
     [exec]     		at com.liferay.portal.test.rule.LogAssertionUncaughtExceptionHandler.uncaughtException(LogAssertionUncaughtExceptionHandler.java:35)
     [exec]     		... 3 more
     [exec]     		Suppressed: java.lang.AssertionError: Uncaught exception in Thread[liferay/portaltest2-1-dispatcher,5,main], java.lang.NullPointerException
     [exec]     			at com.liferay.portal.test.rule.LogAssertionUncaughtExceptionHandler.uncaughtException(LogAssertionUncaughtExceptionHandler.java:40)
     [exec]     			at com.liferay.portal.test.rule.LogAssertionUncaughtExceptionHandler.uncaughtException(LogAssertionUncaughtExceptionHandler.java:35)
     [exec]     			... 4 more
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-25/test-portal-acceptance-pullrequest(master)/3985/modules-integration-mysql57-jdk8/0/9/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
