### PR TITLE
[Static reference] LPS-170593 Remove method reference by using snapshot in modules object-web, portal-search-web

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
@W2jx No regressions.

**Comment by W2jx** [comment]
no conflicts(4/11 10:49)

**Comment by W2jx** [comment]
will resend, as https://liferay.slack.com/archives/C0421NBHFKP/p1681181395336159

**Pull request closed without merging**
