### PR TITLE
LPS-202065 Move LanguageImpl into kernel and remove its direct usages

### PR DESCRIPTION
**Pull request by julschong**
@tinatian Hi Tina,

Since Language has many usages, my plan is to split up the tasks into these parts:
1. Remove LanguageImpl usages
2. Remove LanguageUtil setLangauge() and getLanguage() usages)
3. Merge LanguageImpl into Util and remove from util-spring then replace Language usages with Util

This pull is the first part
Note that:
- LanguageImpl is still in util-spring, now it points to kernel since LanguageImpl is moved to kernel. This is needed because Language service reference usages still need it.

Edit 11/22:
- I used new LanguageImpl in LanguageUtil as a default LanguageImpl when needed (this should take care of many setLangauges used in tests). And when Spring registers util-spring, it should still replace the instance in Util with the instance that references use and registered in OSGi.

Thanks!

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong failure on statup:

```
[beanshell] 2023-11-17 21:38:28.557 WARN  [main][DependencyManagerSyncUtil:81] Declarative Service Unsatisfied Component System Checker check result: 
[beanshell] Bundle {id: 1467, name: com.liferay.commerce.service, version: 11.0.156}
[beanshell] 	Declarative Service {id: 6798, name: com.liferay.commerce.internal.stock.activity.CommerceLowStockActivityImpl, unsatisfied references: 
[beanshell] 		{name: _languageUtil, target: null}
[beanshell] 	}
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-28/test-portal-acceptance-pullrequest(master)/8309/functional-smoke-tomcat90-mysql57-jdk11_open/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
> @julschong failure on statup:
> 
> ```
> [beanshell] 2023-11-17 21:38:28.557 WARN  [main][DependencyManagerSyncUtil:81] Declarative Service Unsatisfied Component System Checker check result: 
> [beanshell] Bundle {id: 1467, name: com.liferay.commerce.service, version: 11.0.156}
> [beanshell] 	Declarative Service {id: 6798, name: com.liferay.commerce.internal.stock.activity.CommerceLowStockActivityImpl, unsatisfied references: 
> [beanshell] 		{name: _languageUtil, target: null}
> [beanshell] 	}
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-28/test-portal-acceptance-pullrequest(master)/8309/functional-smoke-tomcat90-mysql57-jdk11_open/0/0/jenkins-console.txt.gz?authuser=0)

pushed [80d5f7e](https://github.com/liferay-core-infra/liferay-portal/pull/6159/commits/80d5f7e1ca5a2ac9a137869ff4d807fba651230d) to fix this error

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong regression found:

```
[beanshell]      [exec] com.liferay.portal.servlet.test.I18nServletTest > testDefaultGroupI18nData FAILED
[beanshell]      [exec]     java.lang.AssertionError: expected:<fr_CA> but was:<fr_FR>
[beanshell]      [exec]     	at org.junit.Assert.fail(Assert.java:89)
[beanshell]      [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
[beanshell]      [exec]     	at org.junit.Assert.assertEquals(Assert.java:120)
[beanshell]      [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
[beanshell]      [exec]     	at com.liferay.portal.servlet.test.I18nServletTest._testIsFirstLocale(I18nServletTest.java:543)
[beanshell]      [exec]     	at com.liferay.portal.servlet.test.I18nServletTest.testDefaultGroupI18nData(I18nServletTest.java:143)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-38/test-portal-acceptance-pullrequest(master)/9776/modules-integration-mysql57-jdk8/3/21/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
closing for now, need time to fix

**Pull request closed without merging**
