### PR TITLE
LPS-170846 use_compileOnly_for_commons-codec and commons-digester

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

In this PR, I am trying to

use compileOnly for commons-codec
export commons-digester in shared-dependencies-commons, and change to use compileOnly for its usage.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
fixed the code conflict in versions.html by auto-generate, the old test result should be still good

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by jeffwu0724** [comment]
rebased and fixed the codes conflict in versions.html. The previous test result should be still good

**Comment by Kvale1733** [comment]
@jeffwu0724 Looks like there are still conflicts..

**Comment by jeffwu0724** [comment]
@Kvale1733 yes Kevin, I haven't force push it yet. Thanks for checking!

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
Hey @Kvale1733 , would you mind helping me to check if these failures are related to me, please?
Thanks

**Pull request closed without merging**
