### PR TITLE
LPD-38086 Sharded transactional cache

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian The coverage now passes.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:report:93748390

**Comment by tinatian** [comment]
@dantewang Please see https://github.com/liferay-core-infra/liferay-portal/pull/7757.

I talked with shuyang and figured out the reason we still a line not covered is because the branch when safeclosable=null is not covered. 

The way to address issue like this is to see the decompiled java class and check what is the generated code for try with source (it could be different on different jdk version), then see if any branch is missed.

**Pull request closed without merging**
