### PR TITLE
[Reflection] LPD-15270 Build uri and check if host exists instead of using Reflection to check for _host in UriInfoUtil

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:report:2529092196

**Comment by julschong** [comment]
rerun relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
rerun relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@julschong No longer need this as this reflection is not setting final field value.

I am going to close this.

Thanks.
Tina.

**Pull request closed without merging**
