### PR TITLE
LPD-38919 PortalPreferenceValuePersistenceTest

### PR DESCRIPTION
**Pull request by dantewang**
Try an alternative way.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:41592860

**Comment by dantewang** [comment]
ci:test:backend

**Comment by dantewang** [comment]
It seems the test did not run in the relevant batch. Running backend for full integration tests.

**Comment by dantewang** [comment]
ci:test:backend

**Comment by dantewang** [comment]
ci:report:43103271

**Comment by dantewang** [comment]
@tinatian There's no failure of any `*Preference*PersistenceTest` in the backend results.

Since this change only affects whether to keep the model listener when running persistence tests, and the model listener is for `PortalPreferenceValue`, I believe that the other test failures shown in the backend results are irrelevant to this change. I'm marking QA Passed.

cc @shuyangzhou Was there a specific reason to keep this listener for persistence tests?

**Comment by shuyangzhou** [comment]
This was for some non-*PersistenceTest.java integration test that uses PersistenceTestRule.INSTANCE. This test rule is mainly used for generated PersistenceTest, but there are still a handful manual written normal integration tests using it.

I don't remember exactly which ones were causing the cache to be out of date.

But we have made quite a few other fixes/improvements for PortalPreference and PortalPreferenceValue about lazy and bulk fetching. It could be that the original issue was also fixed by a higher level usages change.

So as long as you are sure **all tests using PersistenceTestRule.INSTANCE (not just generated PersistenceTest) are passing**, you can remove the property.

**Comment by dantewang** [comment]
ci:test:backend-hypersonic

> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 43103271.
> 
> Job Link: [generate-testray-csv](https://test-1-8.liferay.com/job/generate-testray-csv/200/)
> 
> Testray CSV Link: [testray-results-43103271.csv](https://test-1-8.liferay.com/userContent/jobs/generate-testray-csv/builds/200/testray-results-43103271.csv)

I checked this results csv and found no failure of the non-persistent tests using `PersistenceTestRule`. The failed persistence tests in this results csv are either common or due to group timeout. Re-running the hypersonic suite to cross-check.

**Comment by dantewang** [comment]
The list of manually written tests using the rule:

```
AssetListEntryAssetEntryRelServiceTest
AssetListEntrySegmentsEntryRelServiceTest
CPDefinitionVirtualTest
FragmentCompositionExportImportTest
FragmentPanelAppTest
FragmentCollectionImplTest
FragmentEntryProcessorRegistryTest
FragmentCompositionLocalServiceTest
FragmentEntryServicePermissionTest
FragmentEntryServiceTest
LayoutPageTemplatesPanelAppTest
LayoutPageTemplateEntryServiceTest
SiteNavigationMenuItemLocalServiceTest
SiteNavigationMenuItemServiceTest
BigDecimalEntryTest
```

**Comment by dantewang** [comment]
ci:report:45705095

**Comment by dantewang** [comment]
Still no failure of the above tests. Marking as passed.

**Comment by tinatian** [comment]
ci:forward:force

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
