### PR TITLE
[Draft] LPS-159031 2-1

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Basically the changes made in this PR passed CI at https://github.com/dantewang/liferay-portal/pull/2282#issuecomment-1411941456

I sent the `@MasterDataSource` removal change together here for convenience of reviewing and additional testing.

Currently the smoke tests related to R/W data source may not cover any `Lock` logic, maybe we should try to test it using `BackgroundTask` with isolation?

cc @vicnate5

### CODE REVIEW

**Comment by vicnate5** [comment]
@zhangyan0701 Please review what we might need to test for R/W databases. Let me know what you find.

**Comment by zhangyan0701** [comment]
@vicnate5 For my understanding, the `Lock` service can be tested with Documents and Message Boards, we can add one test to lock and unlock them and check the records in table Lock_ with R/W configured, also the expiration of lock. Please correct me if I am wrong. @dantewang 

And I think we can also test R/W databases with clustering enabled. I found that there were issues before, but looks like it hasn't been tested for a while.

**Comment by zhangyan0701** [comment]
Created https://issues.liferay.com/browse/LRQA-79367 for the new automation tests. @dantewang I will remove the spring properties that no longer needed from test in this ticket too.

**Comment by dantewang** [comment]
@zhangyan0701 Thanks!

**Comment by zhangyan0701** [comment]
Sent the tests to @vicnate5 to review and tested the new tests in https://github.com/zhangyan0701/liferay-portal/pull/450.

But found one issue that should be related to the changes here. 

Steps:

1. Configure R/W data source in portal-ext.properties:
```
jdbc.write.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.write.url=jdbc:mysql://localhost/lportal?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false&serverTimezone=GMT
jdbc.write.username=root
jdbc.write.password=

jdbc.read.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.read.url=jdbc:mysql://localhost/lportal?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false&serverTimezone=GMT
jdbc.read.username=read_only_user
jdbc.read.password=

counter.jdbc.prefix=jdbc.write.
```
2. Add property `lock.expiration.time.com.liferay.document.library.kernel.model.DLFileEntry=5000` to portal-ext.properties.
3. Start portal.
4. In Documents and Media portlet, upload a file.
5. Checkout the file, assert there is a record inserted in table Lock_.
6. Wait for 5 seconds so the lock should be expired. 
7. Reload page.

Results:
The DM portlet becomes empty. Error in log:
```
2023-02-08 13:45:38.206 ERROR [http-nio-8080-exec-9][IncludeTag:128] Current URL /group/guest/~/control_panel/manage?p_p_id=com_liferay_document_library_web_portlet_DLAdminPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&p_p_auth=GLDENYBi generates exception: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not execute batch
java.sql.SQLSyntaxErrorException: DELETE command denied to user 'read_only_user'@'localhost' for table 'Lock_'
```
The record is not removed from table when the lock expired but got removed after refreshing the page.

Failed test:
[PortalReadWriteDatabaseConfiguration#LockUnlockDMFileEntryAndMBTread](https://testray.liferay.com/home/-/testray/case_results/2189308677)

**Comment by dantewang** [comment]
@zhangyan0701 Thanks Summer! This is why I'd like to have `lock` tested/covered. On the `LockLocalService`, some methods with names like `getXXX` and marked with `Transactional(readOnly=true)` actually does modifications (expiring).

cc @tinatian

**Comment by dantewang** [comment]
Closing this one, I'll provide a fix and resend.

**Pull request closed without merging**
