### PR TITLE
LPS-185099 Remove Multiple Configurations in SearchBarPortletInstanceConfigurationRenderer

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:system

**Comment by zhangyan0701** [comment]
ci:test:search

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@julschong No regressions found. Only a semver issue
```
  [exec] > Task :apps:configuration-admin:configuration-admin-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.configuration.admin.display            MAJOR      1.2.0      1.2.0      2.0.0      VERSION INCREASE REQUIRED
     [exec] 	>   interface  com.liferay.configuration.admin.display.ConfigurationFormRenderer
     [exec] 		-   method     render(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
     [exec] 			-   access     abstract
     [exec] 			-   return     void
     [exec] 		+   method     render(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse,com.liferay.portal.configuration.metatype.annotations.ExtendedObjectClassDefinition$Scope)
     [exec] 			+   access     abstract
     [exec] 			+   return     void
     [exec] [Baseline Warning] Bundle Version Change Recommended: 5.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-40/test-portal-acceptance-pullrequest(master)/2653/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
@Kvale1733 I'll rebase and run ci again. but this semver is weird because I didnt change com.liferay.configuration.admin at all

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Pull request closed without merging**
