### PR TITLE
[Component with its own class name as service type] LPS-197075 Refactor UploadFileEntryHandler and UploadResponseHandler components from object modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-197075

Hey @shuyangzhou, about this [commit](https://github.com/liferay-core-infra/liferay-portal/pull/5634/commits/4499411cf4323b7d48415aef2c6f92639ebf161d), I reached this conclusion because of the usages of the serviceTracker in the `ObjectDefinitionDeployerImpl` class. The usages are [here](https://github.com/liferay-core-infra/liferay-portal/blob/43e089ef7669067b9776c6035a0916e263ef28c7/modules/apps/object/object-web/src/main/java/com/liferay/object/web/internal/deployer/ObjectDefinitionDeployerImpl.java#L182) and [here](https://github.com/liferay-core-infra/liferay-portal/blob/43e089ef7669067b9776c6035a0916e263ef28c7/modules/apps/object/object-web/src/main/java/com/liferay/object/web/internal/deployer/ObjectDefinitionDeployerImpl.java#L727).

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:object

**Comment by catarineaguiar** [comment]
@MrJohn1911 semver error:

```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/object/object-api] FAILED
     [exec]     java.lang.AssertionError: [Baseline Warning] Bundle Version Change Recommended: 76.1.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertFalse(Assert.java:64)
     [exec]         at com.liferay.semantic.versioning.SemanticVersioningTest.testSemanticVersioning(SemanticVersioningTest.java:73)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-09/test-1-38/test-portal-acceptance-pullrequest(master)/9101/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
Last push fixes SemVer error.

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
@MrJohn1911 please rebase.

**Pull request closed without merging**
