### PR TITLE
[Test Cache Replication portlet] LPS-158705

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian ,
This PR is to make Cache Groovy scripts a portlet in portal-cluster-multiple-sample-web. Thanks for checking!

### CODE REVIEW

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina

**Comment by tinatian** [comment]
@JanisZhang @dantewang I did not see you remove the groovy scripts.

Tina

**Comment by JanisZhang** [comment]
> @JanisZhang @dantewang I did not see you remove the groovy scripts.
> 
> Tina

Hi @tinatian, We have another one testcase(`ClusteringMissingPlugins.testcase`) using cache-groovy scripts. Thanks!

**Comment by vicnate5** [comment]
@tinatian Relevant ran the clustering automation and the tests that failed are passing locally for me. No regressions found.

@JanisZhang Is this ready to update the tests to stop using groovy scripts and use the module triggers? I do not see any changes to the functional tests 
e.g. [ClusteringCache.testcase](https://github.com/liferay/liferay-portal/blob/dd0e48c908ff0aa80c1b3911421d2972d50f2220/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/clustering/clusteringframework/ClusteringCache.testcase#L146-L403)

**Comment by dantewang** [comment]
@vicnate5 We do want to avoid using groovy scripts in these functional tests. Tina suggests that we can implement gogo shell commands instead of portlet. We'll try that.

**Comment by dantewang** [comment]
@tinatian @vicnate5 I'm going to close this one.

@JanisZhang Let's have a discussion about a simpler way to migrate the groovy scripts tomorrow.

**Pull request closed without merging**
