### PR TITLE
LPS-188134  move Guava to shared-dependencies, and upgrade version to 32.0.1-jre

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

Resent: https://github.com/liferay-core-infra/liferay-portal/pull/4837
As discussed, I do this ticket in the order:  upgrade version ->add guava to shared-dependencies -> change to compileOnly guava from shared-dependencies -> remove unnecessary dependencies
This is for ticket https://liferay.atlassian.net/browse/LPS-188134.
Thanks for checking

### CODE REVIEW

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found but a rebase is needed.

**Comment by jeffwu0724** [comment]
rebase and fix the conflict in LPS-188134_upgrade_guava_new. Gonna retrigger the test

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@jeffwu0724 There is another conflic.

**Comment by jeffwu0724** [comment]
Fix the code conflict in lib/versions-complete.xml by auto-generate. 
@Kvale1733 , do you think we should retrigger the test for your review, please?

Thanks!

**Comment by Kvale1733** [comment]
@jeffwu0724 No since it was just to update the versions. I'll analyze the current results.

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found. SF issue is unrelated.

**Comment by jeffwu0724** [comment]
fix the code conflict, need to retrigger the test.

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found. SF issue is unrelated.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137835

**Comment by jeffwu0724** [comment]
Hey @Kvale1733 ,

This PR caused blocker https://liferay.atlassian.net/browse/LPS-191330. 
May I ask if the relevant test caught it, please?
Thanks!

**Comment by Kvale1733** [comment]
@jeffwu0724 No, it was not. I should have run ci:test:online-editing also. My bad.

**Comment by jeffwu0724** [comment]
Thanks @Kvale1733 for diving deeper. 
I will also trigger this ci:test:online-editing when I resent

**Pull request closed without merging**
