### PR TITLE
[Components with more than 1 service] LPS-198967 Refactor LDAPUserImporterImpl component

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-198967

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:ldap

**Comment by catarineaguiar** [comment]
@MrJohn1911 regression found:

```
[beanshell]      [exec] com.liferay.portal.security.ldap.internal.exportimport.test.LDAPUserExporterImplTest > testAnonymousUserExport STARTED
[beanshell] 2023-10-13 18:13:14.828 WARN  [com.liferay.portal.security.ldap.test-executor-thread][SafePortalLDAPImpl:466] Unable to bind to the LDAP server
[beanshell] javax.naming.CommunicationException: localhost:10389
[beanshell] 	at com.sun.jndi.ldap.Connection.<init>(Connection.java:235) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.LdapClientFactory.createPooledConnection(LdapClientFactory.java:71) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.pool.Connections.createConnection(Connections.java:187) ~[?:1.8.0_381]
[beanshell] 	at com.sun.jndi.ldap.pool.Connections.getAvailableConnection(Connections.java:152) ~[?:1.8.0_381]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-40/test-portal-acceptance-pullrequest(master)/6669/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
[beanshell]      [exec] com.liferay.saml.opensaml.integration.internal.resolver.DefaultAttributeResolverTest > testResolveUserGroupRolesAttributes FAILED
[beanshell]      [exec]     java.lang.IllegalArgumentException: Can not set com.liferay.saml.runtime.metadata.LocalEntityManager field com.liferay.saml.opensaml.integration.internal.metadata.MetadataManagerImpl._localEntityManager to null value
[beanshell]      [exec]         at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[beanshell]      [exec]         at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[beanshell]      [exec]         at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
[beanshell]      [exec]         at java.lang.reflect.Field.set(Field.java:764)
[beanshell]      [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.setFieldValue(ReflectionTestUtil.java:340)
[beanshell]      [exec]         at com.liferay.saml.opensaml.integration.internal.BaseSamlTestCase._setupMetadata(BaseSamlTestCase.java:633)
[beanshell]      [exec]         at com.liferay.saml.opensaml.integration.internal.BaseSamlTestCase.setUp(BaseSamlTestCase.java:110)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-27/test-portal-acceptance-pullrequest(master)/10333/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:ldap

**Comment by MrJohn1911** [comment]
> @MrJohn1911 regression found:
> 
> ```
> [beanshell]      [exec] com.liferay.portal.security.ldap.internal.exportimport.test.LDAPUserExporterImplTest > testAnonymousUserExport STARTED
> [beanshell] 2023-10-13 18:13:14.828 WARN  [com.liferay.portal.security.ldap.test-executor-thread][SafePortalLDAPImpl:466] Unable to bind to the LDAP server
> [beanshell] javax.naming.CommunicationException: localhost:10389
> [beanshell] 	at com.sun.jndi.ldap.Connection.<init>(Connection.java:235) ~[?:1.8.0_381]
> [beanshell] 	at com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137) ~[?:1.8.0_381]
> [beanshell] 	at com.sun.jndi.ldap.LdapClientFactory.createPooledConnection(LdapClientFactory.java:71) ~[?:1.8.0_381]
> [beanshell] 	at com.sun.jndi.ldap.pool.Connections.createConnection(Connections.java:187) ~[?:1.8.0_381]
> [beanshell] 	at com.sun.jndi.ldap.pool.Connections.getAvailableConnection(Connections.java:152) ~[?:1.8.0_381]
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-40/test-portal-acceptance-pullrequest(master)/6669/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)
> 
> ```
> [beanshell]      [exec] com.liferay.saml.opensaml.integration.internal.resolver.DefaultAttributeResolverTest > testResolveUserGroupRolesAttributes FAILED
> [beanshell]      [exec]     java.lang.IllegalArgumentException: Can not set com.liferay.saml.runtime.metadata.LocalEntityManager field com.liferay.saml.opensaml.integration.internal.metadata.MetadataManagerImpl._localEntityManager to null value
> [beanshell]      [exec]         at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
> [beanshell]      [exec]         at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
> [beanshell]      [exec]         at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
> [beanshell]      [exec]         at java.lang.reflect.Field.set(Field.java:764)
> [beanshell]      [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.setFieldValue(ReflectionTestUtil.java:340)
> [beanshell]      [exec]         at com.liferay.saml.opensaml.integration.internal.BaseSamlTestCase._setupMetadata(BaseSamlTestCase.java:633)
> [beanshell]      [exec]         at com.liferay.saml.opensaml.integration.internal.BaseSamlTestCase.setUp(BaseSamlTestCase.java:110)
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-27/test-portal-acceptance-pullrequest(master)/10333/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

Hey @catarineaguiar this first test is also failing at master

**Comment by shuyangzhou** [comment]
See LDAPPortalInstanceLifecycleListener

**Pull request closed without merging**
