### PR TITLE
master qa 76996

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-76996

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @tinatian, this pr looks good to me. Thx

**Review by rafaprax — APPROVED** [review]

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123186

**Pull request closed without merging**
