### PR TITLE
LPD-38015 Modify custom fields infrastructure to support hide model from the user interface

### PR DESCRIPTION
**Pull request by Mikellorza**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-38015

Hi team,

Working on deprecating wiki from the portal, we have the need to hide wiki from custom field creation. So, this PR include all necessary changes to support disable CustomAttributesDisplay's in order to do not show a model from the custom field creation.

We are only hiding wiki behind a feature flag and for that I need the component enabled always. The use case is that some customers that we are using wiki, they can normally use wiki knowing that they should change wiki to objects because someday will disappear.

# How am I fixing it?

Adding isEnabled method to CustomAttributesDisplay interface and use it in PortletLocalServiceImpl.getCustomAttributesDisplays method in order to do not show some models in the custom field user interface.

# How can you verify that it works?

Run included tests.

# Change list

- LPD-38015 Add ability to enable or disable CustomAttributesDisplay implementations in order to do not show them in expando/custom field user interface
- LPD-38015 Show custom attribute display if it is enabled. Like this way, we can hide custom field creation for a model.
- LPD-38015 SF
- LPD-38015 Add tests

### CODE REVIEW

**Comment by tinatian** [comment]
@Mikellorza  You do not need this, you can simply remove the CustomAttributesDisplay component you disabled, for example removing WikiPageCustomAttributesDisplay class will achieve the same goal

**Comment by Mikellorza** [comment]
Hi @tinatian ,

I can not remove the component because I need it for the customers that have the feature flag enabled. We are only hiding wiki behind a feature flag and for that I need the component enabled always. The use case is that some customers that we are using wiki, they can normally use wiki knowing that they should change wiki to objects because someday will disappear.

**Comment by Mikellorza** [comment]
ci:reopen

**Comment by tinatian** [comment]
@Mikellorza Also please pay attention to your feature flag usages, please check this https://liferay.atlassian.net/browse/LPD-37984.

**Comment by Mikellorza** [comment]
> @Mikellorza
> 
> > I can not remove the component because I need it for the customers that have the feature flag enabled.
> 
> Then what you should do is only activate that component when feature flag enabled.

@tinatian ,

As you can see in the story related to this PR we need this use case: for new customers we will disable wiki from them but we still enable wiki for others customers, that means, we need the use case that  in same installation we will have a company with wiki enabled and other company with wiki disabled. So, I can not neither disable CustomAttributesDisplay component. 

Please, can you reconsider the use case that we have for story https://liferay.atlassian.net/browse/LPD-36851?. If you don't like our purpose, Can you provide a way to have wiki page integration disabled for one company and not for another in the same installation? 

thanks!

**Comment by Mikellorza** [comment]
ci:reopen

**Comment by tinatian** [comment]
@Mikellorza Osgi component can be enabled/disabled programmingly, please search "componentContext.enableComponent" in the code base, you would see plenty of examples, this means that you can based your condition to enable/disable any component which is what you are trying to do here.

Please slack me if you still do not know how to do, I can provide detailed code examples.

**Comment by tinatian** [comment]
@Mikellorza 

> we need the use case that in same installation we will have a company with wiki enabled and other company with wiki disabled
I really doubt this can not be done by your current support as current CustomAttributesDisplay framework is not company-aware.

Please provide more details how you are going to use the api you exposed here.

**Comment by tinatian** [comment]
@Mikellorza I checked your test, I did not see it shows your goal that to enable/disable at company layer, you are enable/disable at portlet layer, meaning that for the same portlet, you are going to share the same feature, either enabled or disabled. 
Thus what you are doing in your test can be achieved by:
1. To enable: register a service
2. To disable: do not register or unregister existing service

You are doing the same thing by always publishing a service with different parameter, this is totally useless based on your test.

Please provide more details how you are going to apply to the wiki case.

**Comment by Mikellorza** [comment]
@tinatian ,

I think I got you your point.

This is the use that we want to do to the isEnabled() method: [commit](https://github.com/Mikellorza/liferay-portal/pull/91/commits/cabd21f510d3a79f8e227bc613748b662161946c). So, in the commit we are using CompanyThreadLocal.getCompanyId() to get the companyId. 

The thing is,  we have to get the companyId using CompanyThreadLocal.getCompanyId() [in the implementation of wiki](https://github.com/Mikellorza/liferay-portal/pull/91/commits/cabd21f510d3a79f8e227bc613748b662161946c) or [in the method getCustomAttributesDisplays](https://github.com/liferay-core-infra/liferay-portal/pull/7491/commits/522901d79f7d55abed78a7430eb1a28de0041835). Also, we can create another method of getCustomAttributesDisplays  in [PortletLocalServiceImpl.java](https://github.com/liferay-core-infra/liferay-portal/pull/7491/commits/522901d79f7d55abed78a7430eb1a28de0041835#diff-b616dab9f6e1810a2fa02b1f41c0783a708546810989fc34973a5c6491728fe5) passing the companyId or getting from CompanyThread if we don't have the companyId. What do you think?

The thing is we need the use case that in same installation we will have a company with wiki enabled and other company with wiki disabled. So, we need to disable/ enable [WikiPageCustomAttributesDisplay.java](https://github.com/Mikellorza/liferay-portal/pull/91/commits/cabd21f510d3a79f8e227bc613748b662161946c#diff-7f2d112dc6639c25d7a04656c24369c9ffb67f0a8d6f2b05c9e32f6015ef4ece) by company.


I hope I have explained well.

Would you think about what is the best solution that fit for you?

thanks in advance!

**Comment by tinatian** [comment]
@Mikellorza Please do this:
1. Add a new method getFeatureFlagKey() in CustomAttributesDisplay, by default return null.
2. In PortletLocalServiceImpl#getCustomAttributesDisplays, use that feature flag key and your current context's companyId to return the right list
3. In your wiki case, return the right feature flag key.

The differences between my suggestion and your current pull:
1. CustomAttributesDisplay is not company-aware by looking at it is registered based on "javax.portlet.name". My solution is not going to change it, while current solution make it company aware as same instance is going to return different value on different company context
2. My solution is centralizing the logic in PortletLocalServiceImpl#getCustomAttributesDisplays to show people that the result is company sensitive, while current solution did not show which may cause issue when people adding a new cache layer.

Please resend.

Thanks.

**Pull request closed without merging**
