### PR TITLE
[Optional Reference] LPS-185138 Convert the Optional Dynamic Greedy references to static references using Snapshot in class UpgradeRecorder

### PR DESCRIPTION
**Pull request by haydenzheng314**
Ticket: https://issues.liferay.com/browse/LPS-185138
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:startup

**Review by dantewang — APPROVED** [review]

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:stop

**Comment by Kvale1733** [comment]
@LisztLiszt Regression found. All upgrades fail with "missing default store" error. 

Steps to reproduce:
1. Import the following 7.4.13 mysql database dump:https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.4.13/data-archive/data-archive-portal-mysql.zip
2. Run the database upgrade tool

Expected Results: Can upgrade without issue
Actual Results:
```
[java] java.lang.IllegalStateException: Missing default Store
     [java] 	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:163) [portal-impl.jar:?]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
     [java] 	at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:54) [com.liferay.portal.tools.db.upgrade.client.jar:?]
     [java] 2023-05-24 07:10:59.227 INFO  [main][UpgradeRecorder:159] Major upgrade finished with result failure
```
[log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-40/test-portal-acceptance-pullrequest(master)/2594/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
