### PR TITLE
LPS-173386 Check loggers in `*-log4j.xml` files

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__ <https://issues.liferay.com/browse/LPS-173386>

This pull request creates a SF rule that checks each defined logger in a `*-log4j.xml` file to make sure that point to a class/package that exists. Specifically, it checks if the class/package that the logger is defined for exists.

### CODE REVIEW

**Comment by tinatian** [comment]
@kevhlee After this https://github.com/liferay-core-infra/liferay-portal/pull/3136/commits/c812a8cd2e2a02f3b4545c2ed8e121fb61970b07, some of the log4j.xml is actually empty, you should remove.

But before remove, please check the logic and see if you need to rename rather than deleting them from log4j.xml.

**Comment by kevhlee** [comment]
ci:reopen

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
SF failure is unrelated.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3210

**Pull request closed without merging**
