### PR TITLE
[Replace Non-Blocking Usage] LPS-200073 AssetEntriesFacet

### PR DESCRIPTION
**Pull request by haydenzheng314**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5920
Ticket: https://liferay.atlassian.net/browse/LPS-200073
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by LisztLiszt** [comment]
ci:test:upgrade

**Comment by LisztLiszt** [comment]
ci:test:drools

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found. But a semantic versioning issue:
```
     [exec] > Task :baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.search.facet             MAJOR      9.0.0      9.0.0      10.0.0     VERSION INCREASE REQUIRED
     [exec] 	-   class      com.liferay.portal.kernel.search.facet.AssetEntriesFacet
     [exec] 		-   extends    com.liferay.portal.kernel.search.facet.BaseFacet
     [exec] 		-   extends    com.liferay.portal.kernel.search.facet.MultiValueFacet
     [exec] 		-   implements com.liferay.portal.kernel.search.facet.Facet
     [exec] 		-   method     <init>(com.liferay.portal.kernel.search.SearchContext)
     [exec] 			-   return     void
     [exec] 		-   method     clone()
     [exec] 			-   access     protected
     [exec] 			-   return     java.lang.Object
     [exec] 		-   method     doGetFacetClause()
     [exec] 			-   access     protected
     [exec] 			-   return     com.liferay.portal.kernel.search.BooleanClause
     [exec] 		-   method     doGetFacetFilterBooleanClause()
     [exec] 			-   access     protected
     [exec] 			-   return     com.liferay.portal.kernel.search.BooleanClause
     [exec] 		-   method     doSetValues(com.liferay.portal.kernel.json.JSONArray)
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     equals(java.lang.Object)
     [exec] 			-   return     boolean
     [exec] 		-   method     finalize()
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     getFacetClause()
     [exec] 			-   return     com.liferay.portal.kernel.search.BooleanClause
     [exec] 		-   method     getFacetCollector()
     [exec] 			-   return     com.liferay.portal.kernel.search.facet.collector.FacetCollector
     [exec] 		-   method     getFacetConfiguration()
     [exec] 			-   return     com.liferay.portal.kernel.search.facet.config.FacetConfiguration
     [exec] 		-   method     getFacetFilterBooleanClause()
     [exec] 			-   return     com.liferay.portal.kernel.search.BooleanClause
     [exec] 		-   method     getFacetValueValidator()
     [exec] 			-   return     com.liferay.portal.kernel.search.facet.util.FacetValueValidator
     [exec] 		-   method     getFieldId()
     [exec] 			-   return     java.lang.String
     [exec] 		-   method     getFieldName()
     [exec] 			-   return     java.lang.String
     [exec] 		-   method     getSearchContext()
     [exec] 			-   return     com.liferay.portal.kernel.search.SearchContext
     [exec] 		-   method     hashCode()
     [exec] 			-   return     int
     [exec] 		-   method     initFacetClause()
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     isStatic()
     [exec] 			-   return     boolean
     [exec] 		-   method     postProcessContextQuery(com.liferay.portal.kernel.search.filter.BooleanFilter,com.liferay.portal.kernel.search.SearchContext,com.liferay.portal.kernel.search.Indexer)
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     setFacetCollector(com.liferay.portal.kernel.search.facet.collector.FacetCollector)
     [exec] 			-   return     void
     [exec] 		-   method     setFacetConfiguration(com.liferay.portal.kernel.search.facet.config.FacetConfiguration)
     [exec] 			-   return     void
     [exec] 		-   method     setFacetValueValidator(com.liferay.portal.kernel.search.facet.util.FacetValueValidator)
     [exec] 			-   return     void
     [exec] 		-   method     setFieldName(java.lang.String)
     [exec] 			-   return     void
     [exec] 		-   method     setStatic(boolean)
     [exec] 			-   return     void
     [exec] 		-   method     setValues(boolean[])
     [exec] 			-   return     void
     [exec] 		-   method     setValues(com.liferay.portal.kernel.json.JSONArray)
     [exec] 			-   return     void
     [exec] 		-   method     setValues(com.liferay.portal.kernel.json.JSONObject[])
     [exec] 			-   return     void
     [exec] 		-   method     setValues(double[])
     [exec] 			-   return     void
     [exec] 		-   method     setValues(int[])
     [exec] 			-   return     void
     [exec] 		-   method     setValues(java.lang.String[])
     [exec] 			-   return     void
     [exec] 		-   method     setValues(long[])
     [exec] 			-   return     void
     [exec] 		-   method     toString()
     [exec] 			-   return     java.lang.String
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/128.0.1/b943da48c218d637e514b38a0391f5f0cab97ac3/com.liferay.portal.kernel-128.0.1.jar
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-11/test-1-39/test-portal-acceptance-pullrequest(master)/8313/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by dantewang** [comment]
@LisztLiszt Please fix sem ver and force push, no need to retrigger CI.

**Comment by LisztLiszt** [comment]
Force pushed to to fix semantice version, no logic change

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143845

cc @shuyangzhou @tinatian

**Pull request closed without merging**
