### PR TITLE
LPS-159095 Create Xalan patch

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by tinatian** [comment]
@dantewang The ticket number of this commit https://github.com/liferay-core-infra/liferay-portal/pull/1434/commits/cd0a37a9bf46c9f93d81fb655fcafbb8a902f623 is wrong, also, please update the commit message and add more info about where the fixes come from.

Tina.

**Comment by dantewang** [comment]
@tinatian Rebased, force pushed with corrected ticket number and the origin of the patch, see https://github.com/liferay-core-infra/liferay-portal/pull/1434/commits/691c9833d5bf582964f45aa92df657adc70426f2

There's no code change.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
Please rebase and forward directly.

**Pull request closed without merging**
