### PR TITLE
master qa 72287

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-72287

### CODE REVIEW

**Comment by kyle-miho** [comment]
Already tested and passed on ci here: https://github.com/kyle-miho/liferay-portal/pull/493
Also tested locally

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
@kyle-miho can you explain a bit for what this test is about? I am quite confused with the code, not sure what's the goal.

**Comment by kyle-miho** [comment]
Hey @shuyangzhou the goal of this test is to test upgrading an older Service Builder module that used the old Spring Dependency Injection to upgrade to the new Declarative Services and be able to run on Portal succesfully still

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121571

**Pull request closed without merging**
