### PR TITLE
LPD-20946 Resource actions | 5-7

### PR DESCRIPTION
**Pull request by dantewang**
Resend to rebase and run CI.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:test:objects

**Comment by dantewang** [comment]
ci:test:object

**Comment by dantewang** [comment]
ci:report:2566306834

**Comment by dantewang** [comment]
ci:report:2566317347

**Comment by dantewang** [comment]
ci:report:2566305190

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
@tinatian Only 1 unique failure in the reports, which doesn't look like being caused by resource action/permission. Retriggered "upgrade" to verify.

**Comment by dantewang** [comment]
ci:report:2566780670

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:report:2566826019

**Comment by dantewang** [comment]
@vicnate5 I kept getting different unique failures in the upgrade runs here. For example in https://testray.liferay.com/home/-/testray/case_results/2566826933?tab=history I see a connection error and then query errors saying the DB is missing columns. Could you take a look to see whether this is a CI issue or not?

**Comment by vicnate5** [comment]
@dantewang I can only find 3 examples of the issue and they are all from your PR https://testray.liferay.com/home/-/testray/cases/2306222571/view?p_p_state=normal&orderByCol=createDate_sortable&orderByType=desc&statuses=3&errors=resource

But most of the test runs for this test are passing https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2566826019&testrayCaseName=+LocalFile.VirtualInstancesUpgrade

It is possible this introduces some instability.

**Comment by dantewang** [comment]
@vicnate5 Thank you!
@tinatian I don't understand why this change could cause errors like missing columns... Could you take a look?

**Pull request closed without merging**
