### PR TITLE
[Remove Blocking usages]LPS-186855 dynamic-data-mapping-api

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-186855

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
ci:test:forms

**Comment by catarineaguiar** [comment]
no regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@JanisZhang Let's wait a bit for the experiment result.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
