### PR TITLE
LPS-145579 Remove LocalizationUtil from modules part 1

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@julschong possible regression:

```
 [exec] > Task :dxp:apps:osb:osb-site-initializer:osb-site-initializer-partner-portal:yarnBuildGroup FAILED
     [exec] yarn run v1.22.5
     [exec] $ yo liferay-fragments:build
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] warning package.json: No license field
     [exec] warning ../../../../../../package.json: No license field
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/node_modules/write-file-atomic/index.js:236
     [exec]     throw err
     [exec]     ^
     [exec] 
     [exec] Error: EACCES: permission denied, open '/root/.config/insight-nodejs/insight-yo.json.2341921568'
     [exec]     at Object.openSync (node:fs:585:3)
     [exec]     at Function.writeFileSync [as sync] (/opt/dev/projects/github/liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/node_modules/write-file-atomic/index.js:212:13)
     [exec]     at Conf.set store [as store] (/opt/dev/projects/github/liferay-portal/modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-partner-portal/src/main/resources/site-initializer/fragments/group/node_modules/conf/index.js:142:19)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-27/test-portal-acceptance-pullrequest(master)/5097/modules-compile-jdk8/0/8/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine, the changes are not related to osb modules. let's rebase and test to see if it goes away

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong no regressions.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
