### PR TITLE
[Components with more than 1 service] LPS-181728 Refactor InfoItemRenderer components from Commerce

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://issues.liferay.com/browse/LPS-181728

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:startup

**Review by rafaprax — APPROVED** [review]

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
