### PR TITLE
LPS-152594 Disable concurrent upgrade

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@tinatian Acceptance results still coming, but the rest of the results are good, the DB partition upgrade tests runs are passing. We can probably forward this since it is urgent.

**Comment by brianchandotcom** [comment]
@tinatian @vicnate5 I merged this, but made changes in 32c6e4a3 and 696442e3

@tinatian I believe your changes should have broken the test DatabasePartitionUpgradeProcessTest

My attempt to fix it is 696442e3

**Comment by vicnate5** [comment]
@LuisOrtiz89

**Pull request closed without merging**
