### PR TITLE
LPS-148093 Expose methods in PortletPreferencesService to get and update Preferences

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-148093

Hi @tinatian,
 
Echo QAs need to adapt the tests to the current scenario after: https://issues.liferay.com/browse/LPS-131407.
In order to do it, they need to be able to get and update PortletPreferences using JSONWS.

That's the reason why we need to expose those methods. 

As javax.portlet.PortletPreferences is not Serializable, if we need to use it via JSONWS, we can't expose directly any getPreferences existing method in the local service. Because of that, we have added a method that provides for preferences XML.

Could you please review it?

Thanks!

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @lfbesada 

A general rule is that we should never change your production code just because you need to test it. 

I am wondering if there is anything other way to test it? like reflection or check from the database directly?

Tina

**Comment by lfbesada** [comment]
Hi @tinatian 
Thanks for the feedback!
The affected tests are not integration tests but POSHI tests. I think that the alternative to using JSONWS is to run it as POSHI test steps and that there are many tests involved. It implies that it would considerably increase the execution time.
@Tim-Cao, I'm sure you can explain the need better than I can.  Could you please explain it a bit more?
Thank you very much!
Regards

**Comment by Tim-Cao** [comment]
Hi @tinatian, this story will change the default behavior of Asset Publisher when added to page. The users have to select a collection to display assets. The old behavior is dynamic selection that can display all assets automatically.
The Asset Publisher is a quite popular widget. There are hundreds of usages in our Poshi cases from multiple product teams. We still want to keep testing the old behavior in those cases so that there will be additional steps required to update the portletPreferences of Asset Publisher to dynamic.
For saving running time, most cases invoke JSONWS to add Asset Publisher to page.
If add additionally UI steps to those cases, it will increase the running time by 30 sec ~ 1 min depending on page resource loading.
Additionally, Poshi cases cannot call local service methods.
If we could expose the related remote service methods, it only increase the running time by less than 3 sec.
The related Poshi updates could be seen in https://github.com/liferay-echo/liferay-portal/pull/7356
Could you consider this request? Thanks!

**Comment by tinatian** [comment]
Hi @Tim-Cao ,

**Comment by tinatian** [comment]
Hi @Tim-Cao ,
I understand the performance is important as it affects a lot of poshi tests which runs daily on ci, but modifying production code to fix the performance issue of running test is for sure not the right direction. 
Not only it does not make sense from the view of development, but also it may introduce unnecessary issues especially security issues. Is it safe to expose this method so that customer can do same thing as your test logic?
I believe there must be other solutions for the performance issues you have. @vicnate5 could you please check the performance issue here and see if you can help?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@victorg1991 @lfbesada @Tim-Cao Using the UI to change the default each time will definitely be a performance issue for Poshi. Is there any reason the default source for AP cannot just be a config set in System Settings/Instance Setting? If that was the case, it would be easy for the poshi test to just modify the default with a `.config` file and not have any performance issues. This still exposes the option to the client, but so does the solution here.

**Comment by Tim-Cao** [comment]
Thanks for @vicnate5, Unfortunately, there is no config set for portletPreference in portal.

**Comment by Tim-Cao** [comment]
Your concern is right @tinatian, I have a thought to hide the remote service to client.
Add both remote service under [jsonws.web.service.paths.excludes=](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/portal.properties#L7079) in portal.properties like /user/update-password did.
Then add **jsonws.web.service.paths.excludes=** in [build-test.xml](https://github.com/liferay/liferay-portal/blob/master/build-test.xml#L8770) for test bundle.
What do you think of this option?

**Comment by tinatian** [comment]
@Tim-Cao I do not like this option either as it is actually same as before. Please try to explore more about this, if you still do not have a solution, let's have a talk.

Tina.

**Comment by Tim-Cao** [comment]
The last option our dev provide is to add a test module with above two remote service, then deploy the test module on test bundle. The cons is for QAs they might meet semantic versioning conflict without ant all for a while. @tinatian

**Comment by tinatian** [comment]
@dantewang please help @Tim-Cao to see if there is a better solution for this issue.

**Comment by dantewang** [comment]
@tinatian @Tim-Cao Got it.

**Comment by tinatian** [comment]
@lfbesada @Tim-Cao I am going to close this pull, please resend if it is needed.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
