### PR TITLE
LPS-176632 simplify, using JSONUtil

### PR DESCRIPTION
**Pull request by W2jx**
Simplify the code according to Brian's [comment](https://github.com/brianchandotcom/liferay-portal/pull/133969#issuecomment-1523197101).

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:help

**Comment by W2jx** [comment]
ci:test:search-solr

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
no conflicts(4/28 10:43)

**Comment by zhangyan0701** [comment]
ci:test:search-solr

**Comment by catarineaguiar** [comment]
@W2jx regressions found:

```
     [exec] com.liferay.portal.search.solr8.internal.highlight.SolrHighlightTest > testEllipsisSolr FAILED
     [exec]     java.lang.NoSuchFieldException: No field on null with name _jsonFactory
     [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.getField(ReflectionTestUtil.java:135)
     [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.setFieldValue(ReflectionTestUtil.java:346)
     [exec]         at com.liferay.portal.search.solr8.internal.search.engine.adapter.search.SearchRequestExecutorFixture.createBaseSolrQueryAssembler(SearchRequestExecutorFixture.java:97)
     [exec]         at com.liferay.portal.search.solr8.internal.search.engine.adapter.search.SearchRequestExecutorFixture.setUp(SearchRequestExecutorFixture.java:66)
     [exec]         at com.liferay.portal.search.solr8.internal.search.engine.adapter.SolrSearchEngineAdapterFixture.createSearchEngineAdapter(SolrSearchEngineAdapterFixture.java:92)
```
```
     [exec] com.liferay.portal.search.solr8.internal.logging.SolrIndexWriterLoggingTest > testBulkDocumentRequestExecutorLogs FAILED
     [exec]     java.lang.AssertionError: 
     [exec]     Expected: log output with message a string containing "response={responseHeader={status=0"
     [exec]          but: log output was ""
     [exec]         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
     [exec]         at org.junit.Assert.assertThat(Assert.java:956)
     [exec]         at org.junit.Assert.assertThat(Assert.java:923)
     [exec]         at com.liferay.portal.search.test.util.logging.ExpectedLogMethodTestRule.verify(ExpectedLogMethodTestRule.java:50)
     [exec]         at com.liferay.portal.search.test.util.logging.ExpectedLogMethodTestRule.afterMethod(ExpectedLogMethodTestRule.java:64)
```
```
     [exec] com.liferay.portal.search.solr8.internal.logging.SolrSearchEngineAdapterLoggingTest > testSearchSearchRequestWithPortalSearchQuery FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.portal.search.solr8.internal.logging.SolrSearchEngineAdapterLoggingTest.testSearchSearchRequestWithPortalSearchQuery(SolrSearchEngineAdapterLoggingTest.java:117)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
     [exec]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-04/test-1-28/test-portal-acceptance-pullrequest(master)/6372/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.redirect.search.test.RedirectNotFoundEntrySearchTest > testSearchByAbsoluteSourceURL FAILED
     [exec]     java.lang.AssertionError: [] expected:<1> but was:<0>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at com.liferay.redirect.search.test.RedirectNotFoundEntrySearchTest.testSearchByAbsoluteSourceURL(RedirectNotFoundEntrySearchTest.java:110)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-04/test-1-28/test-portal-acceptance-pullrequest(master)/6372/modules-integration-mysql57-jdk8/0/8/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.redirect.search.test.RedirectEntrySearchTest > testSearchByDestinationURL STARTED
[beanshell] 2023-04-28 14:15:07.164 ERROR [com.liferay.redirect.test-executor-thread][SolrIndexWriter:370] Update failed
[beanshell] 2023-04-28 14:15:07,165 com.liferay.redirect.test-executor-thread ERROR An exception occurred processing Appender wjqaoegv org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.search.solr8.internal.SolrIndexWriter, message=Update failed
[beanshell] 	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:165)
[beanshell] 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
[beanshell] 	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
[beanshell] 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
[beanshell] 	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
[beanshell] 	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-04/test-1-28/test-portal-acceptance-pullrequest(master)/6372/modules-integration-mysql57-jdk8/0/8/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
resend https://github.com/liferay-core-infra/liferay-portal/pull/4422

**Pull request closed without merging**
