### PR TITLE
[Components with more than 1 service] LPS-206157 Refactor GCSStore component

### PR DESCRIPTION
**Pull request by MrJohn1911**
Previous pull: https://github.com/rafaprax/liferay-portal/pull/1404

Ticket: https://liferay.atlassian.net/browse/LPS-206157

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:dl-store

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
Wait for dl-store test results.

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:report:2488619462

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
The failure marked as unique in ci-test-upgrade also happened at https://testray.liferay.com/home/-/testray/case_results/2486831813.

No unique failure then.

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
