### PR TITLE
LPS-174101 Remove Stream usages for module: account-admin-web

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:account

**Comment by Kvale1733** [comment]
@julschong No regressions.

**Comment by dantewang** [comment]
ci:forward

**Comment by dantewang** [comment]
cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129740

**Pull request closed without merging**
