### PR TITLE
LPS-185768 Remove deprecated AMImageConfiguration.imageMaxSize and AMImageSizeProviderImpl

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
ci:test:lima:norebase

**Comment by Kvale1733** [comment]
ci:test:relevant:norebase

**Comment by julschong** [comment]
rebased breaking change

**Comment by julschong** [comment]
added commit message to https://github.com/liferay-core-infra/liferay-portal/pull/4819/commits/33da3f29a830b938ace2401ad144be185e129ad7

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:lima

**Comment by catarineaguiar** [comment]
@julschong regression found:

```
    [junit] 
    [junit] Testcase: testSplitPackage(com.liferay.portal.split.packages.SplitPackagesTest):	FAILED
    [junit] Detected split packages in modules/apps/adaptive-media/adaptive-media-image-service and modules/apps/adaptive-media/adaptive-media-image-impl: [com.liferay.adaptive.media.image.internal.upgrade.registry]
    [junit] junit.framework.AssertionFailedError: Detected split packages in modules/apps/adaptive-media/adaptive-media-image-service and modules/apps/adaptive-media/adaptive-media-image-impl: [com.liferay.adaptive.media.image.internal.upgrade.registry]
    [junit] 	at com.liferay.portal.split.packages.SplitPackagesTest._checkSplitPackages(SplitPackagesTest.java:137)
    [junit] 	at com.liferay.portal.split.packages.SplitPackagesTest.access$000(SplitPackagesTest.java:43)
    [junit] 	at com.liferay.portal.split.packages.SplitPackagesTest$1.preVisitDirectory(SplitPackagesTest.java:95)
    [junit] 	at com.liferay.portal.split.packages.SplitPackagesTest$1.preVisitDirectory(SplitPackagesTest.java:64)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2677)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.split.packages.SplitPackagesTest.testSplitPackage(SplitPackagesTest.java:62)
    [junit] 
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-06/test-1-29/test-portal-acceptance-pullrequest(master)/7519/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
need to fix SplitPackageTest

**Pull request closed without merging**
