### PR TITLE
LPS-165606 update Google Protocol Buffers to 3.21.7

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-165606.
Thanks for checking!

### CODE REVIEW

**Comment by zhangyan0701** [comment]
Many unit tests failed by an issue which will be fixed here https://github.com/liferay-core-infra/liferay-portal/pull/2049. It would be better to rerun relevant when that is merged.

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@jeffwu0724 can you rebase and re-run relevant, please?

thanks

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
The test failures should be unrelated. But there is another issue [LPS-165900](https://issues.liferay.com/browse/LPS-165900) caused many unit tests fail. It's better to wait for it get fixed then re-run relevant test.

**Comment by jeffwu0724** [comment]
fixed the code conflict

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by jeffwu0724** [comment]
fixed code conflict

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@jeffwu0724 Please rebase.

Tina

**Comment by jeffwu0724** [comment]
fixed the code conflict

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
fixed code conflict and resend

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126104

**Pull request closed without merging**
