### PR TITLE
[Replace Non-Blocking Usage] LPS-198509 Replace non-blocking ServiceProxyFactory usages in classes AuthenticatedSessionManagerUtil, DeviceDetectionUtil and PhoneNumberFormatUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(10/19 8:19)

**Comment by W2jx** [comment]
no conflicts(10/20 8:52)

**Comment by shuyangzhou** [comment]
@W2jx same thing here, AuthenticatedSessionManager and PhoneNumberFormat should be wired by spring.

**Pull request closed without merging**
