### PR TITLE
[Remove Stream/Optional usage] LPS-173791 module: object-web

### PR DESCRIPTION
**Pull request by JanisZhang**
Ticket: https://issues.liferay.com/browse/LPS-173791

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:objects

**Comment by Kvale1733** [comment]
ci:test:object

**Comment by zhangyan0701** [comment]
Found two issues:

**1. Object fields don't display in custom object layout.**
Steps:
- Go to Control Panel > Objects. Add an object.
- Click into the object, in Fields tab, add a Text type of field.
- In Layouts tab, add a layout, click into the layout, in the left side panel, check Mark as Default in Info tab, in Layout tab, Add Tab > Add Block > Add Field, select the created field in step2. Save.
- Back to Details tab, under Panel Category Key, select Control Panel > Object. Publish object.
- Go to Control Panel > Object > new object. Click plus icon to add new object entry.
- Assert the Text field doesn't display. And error in portal console:
```
2023-02-01 08:18:22.523 ERROR [http-nio-8080-exec-2][IncludeTag:128] Current URL /group/control_panel/manage?p_p_id=com_liferay_object_web_internal_object_definitions_portlet_ObjectDefinitionsPortlet_44178&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_object_web_internal_object_definitions_portlet_ObjectDefinitionsPortlet_44178_objectDefinitionId=44178&_com_liferay_object_web_internal_object_definitions_portlet_ObjectDefinitionsPortlet_44178_mvcRenderCommandName=%2Fobject_entries%2Fedit_object_entry generates exception: java.lang.NullPointerException
java.lang.NullPointerException: null
```

**2. Object entry of Boolean type of field doesn't display in content page.**
Steps:
- Go to Control Panel > Objects. Add an object.
- Click into the object, in Fields tab, add a Boolean type of field.
- Back to Details tab, under Panel Category Key, select Control Panel > Object. Publish object.
- Go to Control Panel > Object > new object. Add some entries.
- Go to Site Builder > Pages, add a content page.
- In page edit mode, add Collection Display fragment to the page, click it, in the left side panel, click Select Collection, under Collection Providers, select the object.
- Assert the entries don't display in the fragment. And error in portal console:
```
2023-02-01 08:15:07.720 ERROR [http-nio-8080-exec-5][IncludeTag:128] Current URL /web/guest/d2f08c25-c519-526b-cf2c-2579bdc99368?p_p_id=com_liferay_layout_content_page_editor_web_internal_portlet_ContentPageEditorPortlet&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_resource_id=%2Flayout_content_page_editor%2Fget_collection_field&p_p_cacheability=cacheLevelPage&p_l_mode=edit generates exception: java.lang.RuntimeException: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
```

**Pull request closed without merging**
