### PR TITLE
[Remove Stream/Optional usage] LPS-178728 headless-commerce-admin-order-impl 

### PR DESCRIPTION
**Pull request by JanisZhang**
Code conflict. Rebase and resend!
previous: https://github.com/liferay-core-infra/liferay-portal/pull/3948
https://issues.liferay.com/browse/LPS-178728

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:headless

**Comment by JanisZhang** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
@JanisZhang No regressions.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
