### PR TITLE
LPS-148460 Move metadata-extractor and xmpcore to portal-tika module

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by guilhermedcamacho** [comment]
@koor4356 please help me check the results, thanks!

**Comment by koor4356** [comment]
Okay, thanks!

**Comment by koor4356** [comment]
@guilhermedcamacho 
This looks good, thanks!

**Comment by guilhermedcamacho** [comment]
@tinatian , this PR is ready for your review. Thanks!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by guilhermedcamacho** [comment]
@tinatian, fixed. thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114346

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
