### PR TITLE
[TS] LPS-184974 | Alphabetical order of portlet class names impact in a module with two portlets using different values of javax.portlet.version

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @liferay-core-infra team!

This is a solution for the issue [LPS-184974](https://issues.liferay.com/browse/LPS-184974). 

The detailed reproducing steps are in the JIRA ticket. In short, portlets with different versions of `"javax.portlet.version"` in the same module might work incorrectly (Look and Feel Configuration modal won't show) depending on the relative alphabetical order of the portlet classes.

The problems seems to come from the Spec Version that is stored for the `portletApp` associated to both portlets. As the portlets are loaded the Spec Version is overwritten so that the last to be loaded will have the last word. If this last one uses version `2.0` there will be a problem when requiring version `3.0`. If the last one uses `3.0` there will be no issue.

The approach to the solution is to overwrite the Spec Version only when it's a more recent version.

Please let me know if you have any questions.

Thanks!

Note: Tests might be affected by the issue [LPS-186035](https://issues.liferay.com/browse/LPS-186035).

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@ricardocousolr No regressions found. Testing passed following ticket steps.

**Comment by ricardocousolr** [comment]
Hi @liferay-core-infra,

please let me know if you need further information about the pr.

Thanks!

**Comment by tinatian** [comment]
@yuhai Please take this over, we need to know why it happens

**Comment by yuhai** [comment]
@ricardocousolr, the current pr will miss the case if the module PortletsWithDifferentVersions only includes ThisPortlet without property "javax.portlet.version=3.0".

The issue is "Look and Feel Configuration"'s url is empty. The reason is ThisPortlet's portletSpecMajorVersion(2) < 3. If we enabled the log **com.liferay.portlet.configuration.css.web.internal.portlet.configuration.icon.PortletConfigurationCSSPortletConfigurationIcon** for Debug, we can see the below exception output when load the page
```
 DEBUG [http-nio-8080-exec-2][PortletConfigurationCSSPortletConfigurationIcon:81] null
java.lang.UnsupportedOperationException: Requires 3.0 opt-in
        at com.liferay.portlet.internal.PortletRequestImpl.getRenderParameters(PortletRequestImpl.java:523) ~[portal-impl.jar:?]
```
I am thinking the below questions:

1.  PortletTracker set the value for 2 when no property **javax.portlet.version** defined. This means this is backward-compatible. Please see https://issues.liferay.com/browse/LPS-81525. Because all build-in portlets have set javax.portlet.version=3.0 in @Component. The customer is using @Component way, so the customer may use wrong way. That's to say, they should set javax.portlet.version=3.0. Please see https://help.liferay.com/hc/en-us/articles/360044149512-Portlet-3-0-API-Opt-In

2. Do we support portlet 2.0 backward-compatible? If no, we need to change backward-compatible codes in PortletTracker.

I need to take some time to check this.

**Comment by yuhai** [comment]
@ricardocousolr, we have some places existed backward-compatible logic. It may be necessary.

I just find we may refer to **Permission** button (com.liferay.portlet.configuration.web.internal.portlet.configuration.icon.PermissionsPortletConfigurationIcon) and **Configuration** templates button and its url isn't empty, we may try to change the below code in the PortletConfigurationCSSPortletConfigurationIcon class.

From 
```
PortletURLFactoryUtil.create(
					portletRequest,
					PortletConfigurationCSSPortletKeys.
						PORTLET_CONFIGURATION_CSS,
					PortletRequest.RENDER_PHASE)
```
to 
```
PortletURLFactoryUtil.create(
					PortalUtil.getHttpServletRequest(portletRequest),
					PortletConfigurationCSSPortletKeys.
						PORTLET_CONFIGURATION_CSS,
					PortletRequest.RENDER_PHASE)
```

This way should avoid the case. Please test it. If works, please use this way to fix it.

**Comment by ricardocousolr** [comment]
Thanks for your review @yuhai.

I've tested the suggestion and it works. New pr here: https://github.com/liferay-core-infra/liferay-portal/pull/4719. Closing this one.

**Pull request closed without merging**
