### PR TITLE
[Spring Beans] LPS-196625 Move TableMapper, MappingSqlQuery, and SqlUpdate into portal-impl

### PR DESCRIPTION
**Pull request by julschong**
@tinatian Hi Tina,
This PR is first part of `Merging CurrentConnection interface and impl into Util and move to portal-impl`
`CurrentConnectionUtil` is used by `ConnectionUtil`
So in order to move `CurrentConnectionUtil` to impl, I need to move `ConnectionUtil` to impl as well.

`TableMapper, MappingSqlQuery, and SqlUpdate` are using `ConnectionUtil` so this PR is to move them first.

Thank you

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:help

**Comment by julschong** [comment]
ci:test:db-partition

**Comment by zhangyan0701** [comment]
ci:test:db-partition

**Comment by Kvale1733** [comment]
ci:test:enviornments

**Comment by Kvale1733** [comment]
ci:test:environments

**Comment by Kvale1733** [comment]
ci:test:environments

**Comment by julschong** [comment]
rebased

**Comment by julschong** [comment]
ci:test:environments

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Pull request closed without merging**
