### PR TITLE
[Remove Stream/Optional usage] LPS-178611 module: data-engine-api

### PR DESCRIPTION
**Pull request by JanisZhang**
previous: https://github.com/liferay-core-infra/liferay-portal/pull/3906

Hi @dantewang, I dropped the SF commit https://github.com/liferay-core-infra/liferay-portal/pull/3906/commits/9ea35a1243c68205ac9fa2370c1abe8ae520304a, which caused _LocalizedValueUtilTest_ to fail.

The `LocalizedValueUtilTest.testToLocalizedValuesMapWithStringValues()` method conveys the string value to the method.

_Before_ the SF change, the `JSONFactoryUtil.looseDeserialize` fails to parse "not valid" JSON, and the operation after the `If` block will put the string value to the map, 

_After_ the SF change, as the passed parameter are not _NULL_ and looseDeserialize failed, the string value will not be added to the map. That is the difference.

Thanks!

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:data-engine

**Comment by dantewang** [comment]
@JanisZhang Could you keep my SF and fix it by adding an extra put in the `catch` block and check if it works?

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by JanisZhang** [comment]
ci:test:data-engine

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by JanisZhang** [comment]
forward this one as it's approved and passed QA review. cc @dantewang @tinatian @shuyangzhou

**Comment by JanisZhang** [comment]
ci:forward

**Pull request closed without merging**
