### PR TITLE
LPS-158153 Add new functionality to SystemProperties: get property with default value, and get array

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian @W2jx

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:acceptance

**Comment by W2jx** [comment]
ci:test:acceptance

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me scan test results when you free ? Thanks!

**Comment by zhangyan0701** [comment]
Test [semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1909354502) failed with error:

```
     [exec] > Task :baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.util                     MINOR      38.3.0     38.3.0     38.4.0     VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.portal.kernel.util.SystemProperties
     [exec] 		+   method     get(java.lang.String,java.lang.String)
     [exec] 			+   access     static
     [exec] 			+   return     java.lang.String
     [exec] 		+   method     getArray(java.lang.String)
     [exec] 			+   access     static
     [exec] 			+   return     java.lang.String[]
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/62.0.0/88e62675798171ca92e07530c4ab7a46e4e17200/com.liferay.portal.kernel-62.0.0.jar
```

**Comment by W2jx** [comment]
@zhangyan0701 Thank you

**Comment by W2jx** [comment]
ci:close

**Pull request closed without merging**
