### PR TITLE
[Remove unused field] LPS-199961 Remove unused reference field in calsses AccountChannelShippingOptionDTOConverter, AccountOrganizationResourceImpl and ProductOptionValueDTOConverter

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:commerce

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
no conflicts(10/30 7:57)

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by W2jx** [comment]
no conflicts(10/30 7:57)

**Comment by Kvale1733** [comment]
No regressions found so far. Just going to rerun upgrade suite to verify some failures.

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(11/1 9:03)

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143058

**Pull request closed without merging**
