### PR TITLE
[Bug Fix] FACES-3625 

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, I added one [comment ](https://issues.liferay.com/browse/FACES-3625?focusedCommentId=2586300&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2586300) in FACES-3625 to explain the current fix.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
@yuhai @tinatian Although I approve this change, I think more changes should be needed.

**Background:**

In Liferay, we have "portlet name" and "root portlet id" for each portlet. The root portlet id is processed from the portlet name. `com.liferay.portal.kernel.model.Portlet` provides getters for both.

However, from the very beginning of the git history, `PortletConfigImpl.getPortletName()` is returning the root portlet id. We have many usages in our code where the return value of `PortletConfigImpl.getPortletName()` is used in portlet URL or passed to a method who wants a portlet id.  This was valid usage until the return value of `PortletConfigImpl.getPortletName()` was changed by LPS-140788 (https://github.com/yuhai/liferay-portal/commit/953e9509dfeca36bd000d5973717c1e804f53508). After that change, it returns a pure portlet name, not the root portlet id. 

**Concerns**

Since `PortletConfigImpl.getPortletName()` is changed from returning root portlet id to pure portlet name, the usages of this method should be reviewed and updated if necessary.

For example, for this issue, I accept that the portlet name should not be escaped, but then we should neither use it to create servlet paths, nor use `PortletConfigImpl.getPortletName()` in the request path matching in `InvokerPortletImpl`.

**Next**

I asked Hai to look into the Hibernate pull first, and then revisit this one. I'll keep this pull open in case anyone wants a temp fix.

**Comment by tinatian** [comment]
@dantewang @yuhai Is it possible that we fix LPS-140788 in another way?

Tina

**Comment by yuhai** [comment]
> @dantewang @yuhai Is it possible that we fix LPS-140788 in another way?
> 
> Tina

@tinatian, I will check the way.

**Comment by dantewang** [comment]
ci:close

**Pull request closed without merging**
