### PR TITLE
[TS] LPD-29628

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:26435655

**Comment by dantewang** [comment]
ci:report:26435655

**Comment by dantewang** [comment]
ci:report:26453713

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 26435655.
> 
> Job Link: [generate-testray-csv](https://test-1-39.liferay.com/job/generate-testray-csv/294/)
> 
> Testray CSV Link: [testray-results-26435655.csv](https://test-1-39.liferay.com/userContent/jobs/generate-testray-csv/builds/294/testray-results-26435655.csv)

**core-functional**:
- `LocalFile.Locale#RestrictInstanceAvailableTimeZones` not unique
- `LocalFile.CompanyLogging#GetCompanyAdminLogsFromDifferentCompany` not unique
- `LocalFile.Locale#ViewDefaultAvailableTimeZonesForInstancesAndUsers` not unique

- `LocalFile.SetupWizard#ConfigureNonLiferayDomain` not happened in this case's history, but `transaction rollback: serialization failure` happened in other test cases in the history, e.g. https://liferay.atlassian.net/issues/LPS-205627

**relevant**:
- No unique failure

cc @tinatian

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7194

**Pull request closed without merging**
