### PR TITLE
LPS-143632 Remove LanguageUtil from moduels part 1e

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar
Hi Catarine,
could you please help me scan the test result?
Thank you!

**Comment by julschong** [comment]
@slnn 
Hi Lily,
Could you please help me review this pull first?
Thank you!
CC. @tinatian

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Hi @tinatian

I have checked the changes in this pull, and nothing wrong is found.

Lily

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Pull request closed without merging**
