### PR TITLE
[Bug Fix] LPS-201015 Fix tests

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
ci:test:blogs

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found. 

The tests passed here.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
