### PR TITLE
[Bug Fix]LPS-141792

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.


Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Failures not related

Thanks for the tests!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/109867

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
