### PR TITLE
[Method Reference]Lps 180567 2

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-180567

### CODE REVIEW

**Comment by dantewang** [comment]
@slnn This is a hard reference, why do you convert it to Snapshot?

**Comment by dantewang** [comment]
I see, it's a static field...

**Comment by zhangyan0701** [comment]
ci:test:clustering

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
