### PR TITLE
[Test Fix] Fix NewEnvJVMTestRuleTest, deserializing value should not be trimmed

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
@tinatian per we discussed, use String.split for both usages to be consistent

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
passed [com.liferay.portal.kernel.test.rule.NewEnvJVMTestRuleTest](https://testray.liferay.com/home/-/testray/case_results/2565005992?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2565003244%26cur%3D3%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26resetCur%3Dfalse)

**Comment by julschong** [comment]
SF to inline _fromString() to the tests that actually need it.

Remove null checking in _fromString()

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
test passed here: https://testray.liferay.com/home/-/testray/case_results/2565318220?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2565311944%26cur%3D3%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26resetCur%3Dfalse

**Comment by julschong** [comment]
ready to go

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/149934

**Pull request closed without merging**
