### PR TITLE
LPS-167730 Change the value of property "cardinality" to "ReferenceCardinality.MULTIPLE"

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:help

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts（12/20 9:45）

**Comment by Kvale1733** [comment]
ci:test:export-import

**Comment by catarineaguiar** [comment]
Analyzing this [result](https://github.com/liferay-core-infra/liferay-portal/pull/2782#issuecomment-1359971120), no regressions were found, so I'm passing the pull.

Thanks, Cat

**Comment by W2jx** [comment]
no conflicts(12/21 17:05)

**Pull request closed without merging**
