### PR TITLE
LPS-166694 Remove immediate from search components

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-166694

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
ci:stop:search

**Comment by rafaprax** [comment]
ci:stop:search

**Comment by rafaprax** [comment]
ci:stop:ci:test:search

**Comment by catarineaguiar** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by rafaprax** [comment]
Hey @zhangyan0701, I forgot to run the `ci:test:startup` suite. Sorry for that.

**Comment by catarineaguiar** [comment]
@rafaprax no regressions

**Comment by rafaprax** [comment]
Hey @shuyangzhou, this pr is ready for your review. Thx

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126908

**Pull request closed without merging**
