### PR TITLE
LPS-152502 Remove petra-apache-http-components and use shared-dependencies-apache-http-components instead

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from https://github.com/liferay-core-infra/liferay-portal/pull/1230
Changed module name to shared-dependencies-apache-http-components

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by julschong** [comment]
@tinatian Hi Tina,
This was reviewed here before: https://github.com/liferay-core-infra/liferay-portal/pull/1230#issuecomment-1203497517
Just changed the module name per Shuyang's instruction
Could you please help me review this again?

Thank you!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121406

**Pull request closed without merging**
