### PR TITLE
LPS-143632 Remove LanguageUtil usages in portal module

### PR DESCRIPTION
**Pull request by julschong**
LPS-143632 Remove LanguageUtil usages in portal module

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:acceptance

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
could you please help me review this pull?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong possible regression:

`WorkflowTaskUserNotificationHandlerTest`
```
[exec] com.liferay.portal.workflow.task.web.internal.notifications.WorkflowTaskUserNotificationHandlerTest > testInterpret FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.portal.workflow.task.web.internal.notifications.WorkflowTaskUserNotificationHandler.interpret(WorkflowTaskUserNotificationHandler.java:86)
     [exec]         at com.liferay.portal.workflow.task.web.internal.notifications.WorkflowTaskUserNotificationHandlerTest.testInterpret(WorkflowTaskUserNotificationHandlerTest.java:107)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-29/test-portal-acceptance-pullrequest(master)/3903/modules-unit-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
resending

**Pull request closed without merging**
