### PR TITLE
[Method References 3] LPS-180444 portal-osgi-web

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-180444

previous: https://github.com/liferay-core-infra/liferay-portal/pull/4085

### CODE REVIEW

**Comment by JanisZhang** [comment]
Force-pushed. 
I only changed the commit message. 
It shouldn't affect the test results. 

Thanks!

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@dantewang @JanisZhang _portalIsReady was added to fix random failure on ci by 5ae9766e2aa08394a427c5c2a1fb2c0514790a60. Are you sure we are safe to remove?

Tina

**Comment by dantewang** [comment]
@JanisZhang Please restructure your commits and modify the messages to emphasize that "you make the reference a hard reference so that the atomic boolean is no longer needed".

**Comment by tinatian** [comment]
@JanisZhang @dantewang Please see https://github.com/liferay-core-infra/liferay-portal/pull/4267. Please note I modified the commit message of the first commit, there was a reason we can not use hard reference.

Thanks.
Tina.

**Pull request closed without merging**
