### PR TITLE
[Remove Stream/Optional usage] LPS-175220 module layout-taglib

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend, thanks!
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3435
https://issues.liferay.com/browse/LPS-175220

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
ci:stop:echo

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130969

**Pull request closed without merging**
