### PR TITLE
[Remove Immediate] LPS-188559 Remove immediate property from DLProcessorRegistryImpl

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-188559

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:document

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:document

**Comment by catarineaguiar** [comment]
@MrJohn1911 regression found:

```
[beanshell]      [exec] com.liferay.adaptive.media.image.content.transformer.test.AMImageContentTransformerTest > testTransformASingleImage FAILED
[beanshell]      [exec]     java.lang.AssertionError
[beanshell]      [exec]     	at org.junit.Assert.fail(Assert.java:87)
[beanshell]      [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
[beanshell]      [exec]     	at org.junit.Assert.assertTrue(Assert.java:53)
[beanshell]      [exec]     	at com.liferay.adaptive.media.image.content.transformer.test.AMImageContentTransformerTest.testTransformASingleImage(AMImageContentTransformerTest.java:97)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
```
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:21: error: cannot find symbol
[beanshell]      [exec] import com.liferay.document.library.kernel.util.DLProcessorRegistry;
[beanshell]      [exec]                                                ^
[beanshell]      [exec]   symbol:   class DLProcessorRegistry
[beanshell]      [exec]   location: package com.liferay.document.library.kernel.util
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:434: error: cannot find symbol
[beanshell]      [exec] 	private static DLProcessorRegistry _dlProcessorRegistry;
[beanshell]      [exec] 	               ^
[beanshell]      [exec]   symbol:   class DLProcessorRegistry
[beanshell]      [exec]   location: class com.liferay.adaptive.media.document.library.thumbnails.internal.osgi.commands.test.AMThumbnailsOSGiCommandsTest
[beanshell]      [exec] 2 errors
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-33/test-portal-acceptance-pullrequest(master)/4652/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
