### PR TITLE
LPS-150565 

### PR DESCRIPTION
**Pull request by vendeltoreki**
Resending, as discussed in https://github.com/dantewang/liferay-portal/pull/2263 and https://github.com/liferay-core-infra/liferay-portal/pull/1930 .

Please review my changes.

cc: @dantewang 

Thanks,
Vendel

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@vendeltoreki formatting issues:

```
 [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: Missing language key 'import-task-isolation': ./modules/apps/layout/layout-set-prototype-api/src/main/java/com/liferay/layout/set/prototype/configuration/LayoutSetPrototypeSystemConfiguration.java (SourceCheck:LanguageKeysCheck)
     [java] 2: Missing language key 'import-task-isolation-help': ./modules/apps/layout/layout-set-prototype-api/src/main/java/com/liferay/layout/set/prototype/configuration/LayoutSetPrototypeSystemConfiguration.java (SourceCheck:LanguageKeysCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:442)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:284)
```

**Comment by vendeltoreki** [comment]
Force pushed commits:
* fix baseline: https://github.com/liferay-core-infra/liferay-portal/pull/2189/commits/48595f325c2420a18f0a0dc97826a83be9e27958
* add missing language keys: https://github.com/liferay-core-infra/liferay-portal/pull/2189/commits/6d97f2f43ed67c6b2f86f814198aa069e8d160ca

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Module semantic versioning issue:
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/layout/layout-set-prototype-api] FAILED
     [exec]     java.lang.AssertionError: [Baseline Warning] Bundle Version Change Recommended: 6.1.0
```
Full console:
https://testray.liferay.com/reports/production/logs/2022-10/test-1-35/test-portal-acceptance-pullrequest(master)/2904/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Pull request closed without merging**
