### PR TITLE
LPS-164331 Move soy-renderer from portal-template to frontend-taglib-soy

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
No related failures.

**Comment by tinatian** [comment]
@julschong I will hold on this until we get feedback from front end team

**Comment by julschong** [comment]
per our discussion, we can continue with the move since we have the code already.
Frontend team will remove TemplateRendererTag altogether: https://issues.liferay.com/browse/LPS-164551

**Comment by tinatian** [comment]
@julschong As we talked, please resend.

Thanks.
Tina

**Pull request closed without merging**
