### PR TITLE
[Reflection] Patch org.hibernate-core to unfinal SessionFactoryImpl metamodel field

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:2529633529

**Comment by tinatian** [comment]
ci:forward:force

**Comment by tinatian** [comment]
ci:stop

**Comment by tinatian** [comment]
No regression found on CI

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/146575

**Pull request closed without merging**
