### PR TITLE
LPS-172077 Set Timezone and Locale in ModifiedFacetPortletConfigurationAction

### PR DESCRIPTION
**Pull request by julschong**
@tinatian @kyle-miho @BryanEngler
Hi Tina, Kyle, Bryan, 
This is the pull to fix https://issues.liferay.com/browse/LPS-172077

Moving forward after this fix is in, we will make the CalendarFactoryUtil API intentionally throw NPE exception so that we can easily see where the issue comes from next time

### CODE REVIEW

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by catarineaguiar** [comment]
[Search#AssertModifiedFacetTermsWithDifferentDisplayTemplates](https://testray.liferay.com/home/-/testray/cases/2128151379) passed locally with the pull changes.

**Comment by BryanEngler** [comment]
This looks good to me. thanks @julschong

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128355

**Pull request closed without merging**
