### PR TITLE
[Method References 2] LPS-165445 Convert method reference to ServiceTrackerMap in module portal-search | part 2

### PR DESCRIPTION
**Pull request by W2jx**
resend

Detial: https://github.com/liferay-core-infra/liferay-portal/pull/1993

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
rebase

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
All tests passed.

cc/ @zhangyan0701

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2242

**Pull request closed without merging**
