### PR TITLE
[Method References 2] LPS-175789 Convert method reference to ServiceTrackerList in class ClusterExecutorImpl

### PR DESCRIPTION
**Pull request by W2jx**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3521

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:clustering

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(2/20 14:47)

**Comment by W2jx** [comment]
no conflicts(2/21 13:50)

**Comment by W2jx** [comment]
no conflicts(2/27 8:30)

**Comment by W2jx** [comment]
no conflicts(2/28 9:42)

**Comment by W2jx** [comment]
no conflicts(3/1 10:45)

**Comment by tinatian** [comment]
@W2jx Please make the three ClusterEventListener components rather than registering them manually inside another component at https://github.com/liferay-core-infra/liferay-portal/pull/3542/commits/33582c8b3a1a64220c13bbeb1a076180d863616b

FYI @dantewang 

Please resend.

Thanks.
Tina

**Pull request closed without merging**
