### PR TITLE
LPS-135276 revert

### PR DESCRIPTION
**Pull request by tinatian**
Revert changes made for LPS-135276. Without the changes, the original issue is still unable to reproduce.

FYI @achaparro @vicnate5

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:liferay-online

**Comment by vicnate5** [comment]
ci:test:db-partition

**Comment by vicnate5** [comment]
@kyle-miho Can you prioritize reviewing this on Monday since I will be out? The db-partition tests are failing, but there is also a big UI change that went in for the Portal Instances admin (https://issues.liferay.com/browse/LPS-161071). I wasn't able to reproduce an error when I tested this PR manually with DB partition enabled, but the error is also different here from the test issue upstream.

Coordinate with USM for the UI test fix.

**Comment by achaparro** [comment]
Hi @tinatian,

Which is the issue caused by the changes that need to be reverted?

Thanks.

**Comment by tinatian** [comment]
@achaparro Without it, the original issue can not be reproduced either, this means we do not need this at all. Do you have any other reason we need this expect fixing the issue described in the ticket?

**Comment by kyle-miho** [comment]
Hi @vicnate5 @tinatian @achaparro I'm not sure on what this PR is supposed to do. The Liferay Online tests that are failing are already failing upstream, and they seem to not be using the correct macros to add a Virtual Instance online. I created a ticket to fix them, but I dont know how they are related to this pr

**Comment by vicnate5** [comment]
ci:test:db-partition

**Comment by vicnate5** [comment]
ci:test:liferay-online

**Comment by vicnate5** [comment]
re running since we have the test fixes in upstream

**Comment by achaparro** [comment]
Hi @tinatian,

I was checking the code and the LPS and the root problem before the changes was that, when we reached the affected code, the _companyThreadLocal_ was not set with the current company (the new partition) so, we always got the data from the default database and we did not find anything (probably in this [point](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/model/impl/CompanyImpl.java#L414) for the company associated to the new partition.

Taking that into account, the code is not wrong, I guess this is not happening because we don't reach it now due to:
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/persistence/impl/CompanyPersistenceImpl.java#L803

Is that correct?

I remember that the issue was straightforward to reproduce when the ticket was created so, I think the code can prevent future issues and does not hurt but it is up to you.

Thank you.

cc/ @vicnate5 @kyle-miho

**Comment by vicnate5** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122463

**Pull request closed without merging**
