### PR TITLE
remove_deprecated_for_portal_kernel_part_Six

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

I have removed deprecated for
"ModelResourcePermissionHelper.java"
"ThreadLocalCompanyProvider" and "CompanyProviderWrapper"
"InvokerFilter.java"
"portal-kernel/src/com/liferay/portal/kernel/servlet/taglib/aui"
"SocialActivityManagerUtil.java"
"portal-kernel/src/com/liferay/portal/kernel/template"
"ThemeDisplay.java"
"renderActions()"
"isImageDefaultUseInitials()"
Thanks for checking. Also see https://github.com/jeffwu0724/liferay-portal/pull/44

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by kyle-miho** [comment]
@bronsonsoda can you check this?
Relevant Results unique failures: https://test-1-1.liferay.com/job/generate-testray-csv/52/
Acceptance Results unique failures: https://test-1-1.liferay.com/job/generate-testray-csv/53/
cc: @vicnate5

**Comment by bronsonsoda** [comment]
@jeffwu0724 no regressions found 

@kyle-miho @vicnate5

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by vicnate5** [comment]
@catarineaguiar Can you check this one?

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
