### PR TITLE
LPS-195671 Merge UsersAdmin interface and impl into Util in kernel

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@julschong possible regression:

```
     [exec] com.liferay.journal.exportimport.data.handler.test.JournalExportImportTest > testVersioningDeleteFirst FAILED
     [exec]     java.lang.AssertionError: expected:<0> but was:<7>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:633)
     [exec]     	at com.liferay.journal.exportimport.data.handler.test.JournalExportImportTest.validateImportedStagedModel(JournalExportImportTest.java:624)
     [exec]     	at com.liferay.journal.exportimport.data.handler.test.JournalExportImportTest.validateVersions(JournalExportImportTest.java:655)
     [exec]     	at com.liferay.exportimport.test.util.lar.BasePortletExportImportTestCase.testVersioningDeleteFirst(BasePortletExportImportTestCase.java:296)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-09/test-1-34/test-portal-acceptance-pullrequest(master)/4720/modules-integration-mysql57-jdk8/2/7/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
retesting

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
Hi @slnn could you help to add _QA Failed_ to this PR because of the SF issue? Thanks.

```
     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: /opt/dev/projects/github/liferay-portal/portal-web/docroot/html/common/init.jsp expected:<...eray.portal.kernel.c[onfiguration.Filter" %><%@
```
Whole [log](https://testray.liferay.com/reports/production/logs/2023-09/test-1-39/test-portal-source-format/4060/source-format-current-branch-jdk8/0/0/jenkins-console.txt.gz?authuser=0).

**Comment by dantewang** [comment]
@liuxingye I saw this SF error in another PR, so it doesn't seem to be unique to this pull?

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
Hi @dantewang 

According to the [results](https://github.com/liferay-core-infra/liferay-portal/pull/5558#issuecomment-1725413537), there are 3 SF issues. The 2nd and 3rd are not related to the PR, but for the 1st one, I noticed the init.jsp file under` portal-web/docroot/html/common` is involved in the pull. So that's why I think it is related to the pull, correct me if I am wrong. Thanks.
```
     [java] 1: /opt/dev/projects/github/liferay-portal/portal-web/docroot/html/common/init.jsp expected:<...eray.portal.kernel.c[onfiguration.Filter" %><%@
```
```
     [java] 2: /opt/dev/projects/github/liferay-portal/modules/apps/change-tracking/change-tracking-web/src/main/java/com/liferay/change/tracking/web/internal/model/listener/CTCollectionModelListener.java expected:<...			CTCollection() {
```
```
     [java] 3: /opt/dev/projects/github/liferay-portal/modules/apps/portal-security/portal-security-content-security-policy/src/main/java/com/liferay/portal/security/content/security/policy/internal/ContentSecurityPolicyNonceProviderImpl.java expected:<...olicyNonceProvider;
```
Whole [log](https://testray.liferay.com/reports/production/logs/2023-09/test-1-2/test-portal-source-format/1791/source-format-current-branch-jdk8/0/0/jenkins-console.txt.gz?authuser=0).

**Comment by julschong** [comment]
rebase and retest

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
SF [issues](https://github.com/liferay-core-infra/liferay-portal/pull/5558#issuecomment-1726291077) should be not related.

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by julschong** [comment]
rebased

**Comment by julschong** [comment]
@shuyangzhou no moving this to portal-impl
Following build.gradles do not contain portal-impl dependencies: 
        ./modules/apps/user/user-taglib/build.gradle
        ./modules/apps/organizations/organizations-api/build.gradle
        ./modules/apps/frontend-data-set/frontend-data-set-sample-web/build.gradle

**Comment by julschong** [comment]
closed per our discussion

**Pull request closed without merging**
