### PR TITLE
[Hibernate] LPS-149268 Inline StringClobType

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian https://issues.liferay.com/browse/LPS-149268

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test result.

Thanks.
Tina

**Comment by vicnate5** [comment]
@zhangyan0701 can you check this one?

**Comment by vicnate5** [comment]
@zhangyan0701 I am running our new analysis tool against the acceptance results here.

Should give a CSV at this URL that will only contain the failures that might be unique
https://test-1-1.liferay.com/job/generate-testray-csv/2/

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@tinatian Force pushed to rebase only (bnd.bnd).

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114880

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
