### PR TITLE
LPS-190096 Make sure that long values are serialized as string

### PR DESCRIPTION
**Pull request by victorg1991**
Only the last commit needs review: https://github.com/liferay-core-infra/liferay-portal/pull/4969/commits/9a56e0a98eb0112615aca2167979681452b58d60

Not all java long numbers can be represented in javascript this is why here we force to use the overloaded method that serialized the longs to string:

```java
@Override
	public JSONObject put(String key, long value) {
		try {
			_jsonObject.put(key, String.valueOf(value));
		}
		catch (Exception exception) {
			if (_log.isWarnEnabled()) {
				_log.warn(exception);
			}
		}

		return this;
	}
 
```

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
ci:test:echo

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@tinatian Background: https://issues-archive.liferay.com/browse/LPS-58586

**Comment by Kvale1733** [comment]
@victorg1991 This fixes this issue. However, it causes the following regression

Steps to reproduce:
1. Go to Content & Data > Web Content
2. Add Basic Web Content with title "WC Title" and publish
3. Add a Heading fragment to a page
4. Click on the Heading fragment
5. Select element-text (left side drop down)
6. On the item selector selected the created web content
7. Under Field select Title and Publish
8. Go to the Content & Data > Web Content
9. Edit the title to "WC Title Edit" and Publish
10. Go back to the page with the heading fragment in edit mode
11. Click on the Heading fragment again and select element-test

Expected Results: The item selector shows "WC Title Edit" is selected
Actual Results: The item selector still show "WC Title"

**Comment by dantewang** [comment]
@victorg1991 Please fix the issue and resend, thanks!

**Comment by dantewang** [comment]
@victorg1991 Specifically, could you send the `JSONFactory` change separately to us? This way we can focus on what's in our scope and don't need to check which change causes that regression.

**Comment by victorg1991** [comment]
@dantewang I will :) I cannot reproduce the issue that kevin mentioned though

**Pull request closed without merging**
