### PR TITLE
LPS-164317 Move the adjustment of the log level for Log4JLogCapture into the constructor so we can properly store the old log level to reset to after we finish capturing the log

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-164317

### CODE REVIEW

**Comment by kyle-miho** [comment]
This can only affect integration tests, not unit tests so no need to check those for unique failures

**Comment by kyle-miho** [comment]
ci:test:backend

**Comment by kyle-miho** [comment]
@yuhai I adjusted the logic since _level was getting set to the new log level since ConfigureLog4JLogger currently changes the log level before we set _level, therefore when it gets autoclosed, it will not reset itself to the original log level.

**Comment by Kvale1733** [comment]
@kyle-miho No regressions found.

**Review by yuhai — APPROVED** [review]

**Comment by yuhai** [comment]
@kyle-miho, thanks for catching this.

@dantewang, the fix is good for me.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

cc @tinatian This is a test fix to fix an obvious logic issue.

**Pull request closed without merging**
