### PR TITLE
[Bug Fix] LPS-151447

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on the [requirement](https://github.com/liferay-core-infra/liferay-portal/pull/613)

### CODE REVIEW

**Comment by yuhai** [comment]
Hi @catarineaguiar,

Please help scan the test result.

Thanks

**Comment by catarineaguiar** [comment]
Hi @yuhai, no regressions were found.

**Comment by tinatian** [comment]
@shuyangzhou This is good to go. This is going to fix the warning message on startup caused by hibernate upgrade.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116151

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
