### PR TITLE
[Components with more than 1 service] LPS-183508 Refactor PortetProvider components from Commerce modules part IV

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://issues.liferay.com/browse/LPS-183508

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
ci:test:startup

**Comment by chaowang-123** [comment]
Hi @slnn, the failure is not related to this PR, could you help add QA Passed label when you have the chance?

**Review by rafaprax — APPROVED** [review]

**Review by rafaprax — APPROVED** [review]

**Pull request closed without merging**
