### PR TITLE
[commons-lang] LPD-19868 Remove org.apache.commons.lang.ArrayUtils usages

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:report:2547433686

**Comment by tinatian** [comment]
No unique failures from the report

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
changed to use assertArrayEqual [16da4b6](https://github.com/liferay-core-infra/liferay-portal/pull/6735/commits/16da4b62a232e9eaa74bed746f09832d9951036a)

**Comment by julschong** [comment]
ci:report:2547924386

**Comment by julschong** [comment]
no unique failure from [relevant](https://github.com/liferay-core-infra/liferay-portal/pull/6735#issuecomment-1986355851)

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6749

**Pull request closed without merging**
