### PR TITLE
[TS] LPS-175783

### PR DESCRIPTION
**Pull request by ChrisKian**
Resent from https://github.com/liferay-core-infra/liferay-portal/pull/3618

I've resolved test issues based on in--line comments and [this comment](https://github.com/liferay-core-infra/liferay-portal/pull/3618#issuecomment-1447937227) as well.

CC @yuhai

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@ChrisKian No regressions found. Testing passed following ticket steps.

**Comment by yuhai** [comment]
@ChrisKian, please see the changes from https://github.com/liferay-core-infra/liferay-portal/pull/3775. I merged your first and second commit as the first commit. I think this seems more clear.

**Pull request closed without merging**
