### PR TITLE
[Equinox Http LPS-184766] LPS-195887 Inline HttpServiceRuntimeImpl

### PR DESCRIPTION
**Pull request by dantewang**
cc @shuyangzhou

### CODE REVIEW

**Comment by dantewang** [comment]
@zhangyan0701 Let's trigger ci-test if there's no unique failure in relevant.

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5585

**Pull request closed without merging**
