### PR TITLE
[Bug Fix] LPS-144437

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on the [requirement](https://github.com/liferay-core-infra/liferay-portal/pull/102#issuecomment-1001522470)

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@tinatian Looks good to me.

**Comment by tinatian** [comment]
@dantewang @yuhai Please see https://github.com/liferay-core-infra/liferay-portal/pull/139. 
Please note I did not include this commit https://github.com/liferay-core-infra/liferay-portal/pull/120/commits/ef0410a6168337d473c739c7090ebd897a59ddbe. The reason is it is really hard to figure out the logic as it depends on the detail logic inside a method you invoked. When you trace back the change log later, the reason may be invalid if someone modified the logic in the method you invoked. It is risky to me to do this.

Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
