### PR TITLE
[Remove unused field] LPS-199064 Remove unused reference field in class AntivirusAsyncFileStoreSchedulerJobConfiguration

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(10/16 8:59)

**Comment by W2jx** [comment]
no conflicts(10/17 8:23)

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142350

**Pull request closed without merging**
