### PR TITLE
LPD-41335 Centralize all language override functionality into LanguageResourcesExtender

### PR DESCRIPTION
**Pull request by kevhlee**
__Tickets:__
- <https://liferay.atlassian.net/browse/LPD-35718>
- <https://liferay.atlassian.net/browse/LPD-41335>

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:core-functional

**Comment by tinatian** [comment]
ci:report:76929586

**Comment by tinatian** [comment]
ci:report:76973674

**Comment by kevhlee** [comment]
@tinatian The test failures are unrelated and/or not reproducible.

**Comment by tinatian** [comment]
@kevhlee As we talked, I am going to close this pull, please resend.

Thanks.
Tina

**Pull request closed without merging**
