### PR TITLE
[System Properties] LPS-156838 Move some properties required by module framework

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , Based on the comments in https://github.com/liferay-core-infra/liferay-portal/pull/1715, I modified the usage of properties.

Detial: https://github.com/liferay-core-infra/liferay-portal/pull/1715

### CODE REVIEW

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@tinatian This change is based on Shuyang's comment in https://github.com/liferay-core-infra/liferay-portal/pull/1715. Code looks good, just one thing I'm not sure -- is it suitable to put the `ModuleFrameworkPropsValues` in portal-kernel?

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123535

**Pull request closed without merging**
