### PR TITLE
[Static reference] LPS-182671 Remove static references in class MBDiscussionPermission | part 2

### PR DESCRIPTION
**Pull request by W2jx**
resend

previous: https://github.com/liferay-core-infra/liferay-portal/pull/5031

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:lima

**Comment by W2jx** [comment]
ci:test:comment

**Comment by W2jx** [comment]
ci:test:message-boards

**Review by yuhai — APPROVED** [review]
@W2jx, for the commit(https://github.com/liferay-core-infra/liferay-portal/pull/5044/commits/2e70baee50e662f0af3fa12e26417d5b9f219f73), you do the two things, one is "Simplify logic in the hasPermission()", another is "Remove unnecessary Exception signature". Even though they are easy to review/read, but I think we may separate two commits or edit the commit message for "Simplify logic, 1.Because all the Comment we use in code are subclasses of MBCommentImpl. 2. Remove unnecessary Exception signature". This is just suggestion, the current way is also ok to me.

@dantewang, the pr is good to me. Actually, in the MBDiscussionPermissionImpl class, method params Comment and commentId equals to MBMessage and messageId, but we can't change them. Because its interface `Comment `can't import `MBMessage`(MBMessage is in the module-api).

**Comment by dantewang** [comment]
@W2jx Will review after updating as what Hai commented.

**Comment by Kvale1733** [comment]
ci:test:questions

**Comment by W2jx** [comment]
Hi @dantewang , I have updated the commits.

**Comment by W2jx** [comment]
only split commit, no need to rerun test

**Comment by dantewang** [comment]
@W2jx @yuhai Closing, please resend as discussed, thanks!

**Pull request closed without merging**
