### PR TITLE
LPS-142278 Deprecate global lib dir

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian I go ahead with deprecating the global lib dir, because the pull request of the previous task (fixing web dir) always fails a lot of things on CI even before starting portal. I've asked QA guys for help.
https://issues.liferay.com/browse/LPS-142278

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results once the tests are done? Thanks!

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@kyle-miho can you check the results?

**Comment by kyle-miho** [comment]
checking

**Comment by kyle-miho** [comment]
Failures are unrelated

**Comment by tinatian** [comment]
@shuyangzhou This pull is ready to go. 

Please note we are going to have following pulls to clean up other lib related constants later, this pull only focuses on "LIFERAY_LIB_GLOBAL_DIR"

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/110211

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
