### PR TITLE
[TS] LPS-170849

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-170849

Forwarded from https://github.com/liferay-echo/liferay-portal/pull/10559 after passing Echo review.  Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by Kvale1733** [comment]
@ChrisKian No regressions found.

**Comment by ChrisKian** [comment]
Hi @yuhai,
I understand the first page will attempt to be rendered, then the next page in which the user can view and isn't hidden will be displayed instead.  Is this the intended behavior, or should the next visible page be shown instead?

**Comment by yuhai** [comment]
> Hi @yuhai, I understand the first page will attempt to be rendered, then the next page in which the user can view and isn't hidden will be displayed instead. Is this the intended behavior, or should the next visible page be shown instead?

Hi @ChrisKian, 

I think the expected behavior is that when the first page is rendered. If the user has view page permission, it should be displayed. If the user doesn't have the view page permission, next page with not hidden and viewable should be displayed. ServicePreAction class is good for the case. 

Since the first page request was sent by FriendlyURLServlet, and actually it caught LayoutPermissionException, I think we may return one viewable page as redirect. I send one [pr](https://github.com/ChrisKian/liferay-portal/pull/319) to you. If the [pr](https://github.com/ChrisKian/liferay-portal/pull/319) is good to you,  please send it to liferay-lima team to review. If possible, please also add one integration test for the case. If the [pr](https://github.com/ChrisKian/liferay-portal/pull/319) is not good to you, I will ask this with my team leader to confirm.

**Comment by ChrisKian** [comment]
Forwarded to https://github.com/liferay-lima/liferay-portal/pull/3856

**Pull request closed without merging**
