### PR TITLE
LPS 162706 10 27 3

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-162706

### CODE REVIEW

**Comment by kyle-miho** [comment]
This PR is to solve the issue of Symbolic Link OSGi Configurations getting duplicated when updated the configuration. It seems that using the OSGi/configs folder itself as a symbolic link does not work, unless if my test is wrong (but it likely is not supported), however the issue mentioned in the original bug ticket is solved cc:@ericLYan

**Comment by kyle-miho** [comment]
@rafaprax Can you check my integration tests, especially the formatting with feedback? I was not used to writing these types of integration tests and although they work and cleanup, I'm not sure if they were written in the best way possible

**Comment by catarineaguiar** [comment]
@kyle-miho regressions found:

```
 [exec] com.liferay.portal.file.install.deploy.test.FileInstallSymLinkTest > testConfigurationWithDanglingSymbolicLink FAILED
     [exec]     java.nio.file.DirectoryNotEmptyException: /opt/dev/projects/github/liferay-portal/bundles/osgi/configs
     [exec]     	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:242)
     [exec]     	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
     [exec]     	at java.nio.file.Files.deleteIfExists(Files.java:1165)
     [exec]     	at com.liferay.portal.file.install.deploy.test.FileInstallSymLinkTest._deleteOSGiConfigFolder(FileInstallSymLinkTest.java:305)
     [exec]     	at com.liferay.portal.file.install.deploy.test.FileInstallSymLinkTest.tearDown(FileInstallSymLinkTest.java:83)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-39/test-portal-acceptance-pullrequest(master)/1461/modules-integration-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

not sure if this failure is related:
```
[exec] com.liferay.portal.configuration.persistence.upgrade.test.ConfigurationUpgradeStepFactoryTest > testUpgradeConfigWithDBAndFile FAILED
     [exec]     java.lang.AssertionError: [Lorg.osgi.service.cm.Configuration;@18d86a2b expected:<1> but was:<2>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at com.liferay.portal.configuration.persistence.upgrade.test.ConfigurationUpgradeStepFactoryTest._assert(ConfigurationUpgradeStepFactoryTest.java:186)
     [exec]     	at com.liferay.portal.configuration.persistence.upgrade.test.ConfigurationUpgradeStepFactoryTest._testUpgradeConfig(ConfigurationUpgradeStepFactoryTest.java:293)
     [exec]     	at com.liferay.portal.configuration.persistence.upgrade.test.ConfigurationUpgradeStepFactoryTest.testUpgradeConfigWithDBAndFile(ConfigurationUpgradeStepFactoryTest.java:92)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-39/test-portal-acceptance-pullrequest(master)/1461/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@kyle-miho this failure is still happening and it is unique:

```
 [exec] com.liferay.portal.configuration.persistence.upgrade.test.ConfigurationUpgradeStepFactoryTest > testUpgradeConfigWithDBAndFile FAILED
     [exec]     java.lang.AssertionError: [Lorg.osgi.service.cm.Configuration;@8f1ced5 expected:<1> but was:<2>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at com.liferay.portal.configuration.persistence.upgrade.test.ConfigurationUpgradeStepFactoryTest._assert(ConfigurationUpgradeStepFactoryTest.java:186)
     [exec]     	at com.liferay.portal.configuration.persistence.upgrade.test.ConfigurationUpgradeStepFactoryTest._testUpgradeConfig(ConfigurationUpgradeStepFactoryTest.java:293)
     [exec]     	at com.liferay.portal.configuration.persistence.upgrade.test.ConfigurationUpgradeStepFactoryTest.testUpgradeConfigWithDBAndFile(ConfigurationUpgradeStepFactoryTest.java:92)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-32/test-portal-acceptance-pullrequest(master)/6819/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

**Comment by kyle-miho** [comment]
Thanks @catarineaguiar! @tinatian I'll look into this for you I think it might be an issue with the code change

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@kyle-miho thanks for checking. No regressions were found.

**Comment by rafaprax** [comment]
Hi @kyle-miho, I made some small adjustments, resent here see https://github.com/liferay-core-infra/liferay-portal/pull/2439.

Sorry for the delay

**Pull request closed without merging**
