### PR TITLE
[Optional Reference] LPS-185552 Convert the Optional Dynamic Greedy references to static references using Snapshot in class ThreadLocalScopeContextScopeChecker

### PR DESCRIPTION
**Pull request by haydenzheng314**
Resend as talked.
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4646
Ticket: https://issues.liferay.com/browse/LPS-185552
Thanks.

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by LisztLiszt** [comment]
ci:test:oauth2

**Comment by Kvale1733** [comment]
@LisztLiszt No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
