### PR TITLE
[Remove Stream/Optional usage] LPS-172199 Remove usages of Stream/Optional on Method Return Value for module: segments-web | part 2

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
ci:test:tango

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(1/6 8:59)

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128436

**Pull request closed without merging**
