### PR TITLE
[TS] LPS-183229

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
ci:test:frontend

**Comment by yuhai** [comment]
@catarineaguiar, before you tested the issue, I had changed the ticket's description and used build-in taglib **liferay_ratings** can reproduce the issue. But checking your error, it seems you didn't use the latest steps. You used **@edelweiss_ui["ratings"]** to test and it also is different from the customer used. The custom taglib is **@test_ui["ratings"]**.

@zhangyan0701, could you please help test the fix on your local?

**Comment by zhangyan0701** [comment]
Hi @yuhai I didn't reproduce the issue with your fix locally following the steps in the ticket's description. No error in the Assert Publisher portal.

And the failures in automation tests are unrelated.

**Comment by tinatian** [comment]
@yuhai Before you change, the bundles map is managed by FreeMarkerBundleClassloader, after your change, it is managed by FreeMarkerManager, the time you populate and remove bundles is same as before, I am confused why this can fix this issue?
Let's have a talk.

Tina.

**Comment by yuhai** [comment]
> @yuhai Before you change, the bundles map is managed by FreeMarkerBundleClassloader, after your change, it is managed by FreeMarkerManager, the time you populate and remove bundles is same as before, I am confused why this can fix this issue? Let's have a talk.
> 
> Tina.

@tinatian, I want to firstly explain why the fix can solve the issue before we have a talk. The issue happened when get tagClass during rendering the template. The tagClass is from the first deployed module's classLoader. When redeploy the module again, it is also from the first/old module's classLoader. Please see the below invoke process.

``
`FreeMarkerManager#TaglibFactoryWrapper#get() _taglibFactory.get(uri) -> freemarker.ext.jsp.TaglibFactory.TldParserForTaglibBuilding#resoveClassFromTLD() ->freemarker.template.utility.ClassUtil.forName()
``

in freemarker.template.utility.ClassUtil.forName(), it uses the codes

```
 ClassLoader ctcl = Thread.currentThread().getContextClassLoader();
            if (ctcl != null) {  // not null: we don't want to fall back to the bootstrap class loader
                return Class.forName(className, true, ctcl);
            }

```

The root issue is Class.forName(className, true, ctcl) wiil return the first loaded value. Please see the explanation from the [comment](https://issues.liferay.com/browse/LPS-183229?focusedCommentId=2912622&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2912622). 

Before the fix, **ctcl** always is the same FreeMarkerBundleClassloader no matter how many times we redeploy the taglib module, so the tagClass will be always using the first loaded value, and the issue will happen.

After the fix,  **ctcl/FreeMarkerBundleClassloader** will always be different in the every request. So it can solve the issue.

**Comment by dantewang** [comment]
@tinatian TLDR: FreeMarker uses `Class.forName(..., ClassLoader)` to load class, which causes the loaded class to be cached in the `FreeMarkerBundleClassLoader`, which is not expected by us -- we want it to be always delegating to bundles.

**Comment by yuhai** [comment]
resend it to https://github.com/liferay-core-infra/liferay-portal/pull/4593

**Pull request closed without merging**
