### PR TITLE
[Components with more than 1 service] LPS-206064 Refactor OAuth2AuthorizationExpandoPortalInstanceLifecycleListener component

### PR DESCRIPTION
**Pull request by rafaprax**
**Author:** @MrJohn1911
**Issue:** https://liferay.atlassian.net/browse/LPS-206064
**Forwarded from:** https://github.com/rafaprax/liferay-portal/pull/1402
**Original comment:**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud-acceptance

**Comment by MrJohn1911** [comment]
ci:report:2487558226

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:stable

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
