### PR TITLE
LPS-142279 Refactor ClassUtil & PortalClassPathUtil to reuse common logic

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina @tinatian,
This is resubmitted from #417 after our discussion

Here are some notes on this pull from our discussion:
1. getParentDir should have one parameter of class (easier to use)
2. use Function instead of Mapper to account for special case processing
3. "!/" commit need explanation
4. PortalClassPathUtilTest testCreateProcessConfig() doesnt need LayoutTestUtil, should avoid using other classes unless necessary

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by tinatian** [comment]
@julschong As we talked, I am going to close this pull, please resend. 


Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
