### PR TITLE
LPS-149097 Move commons-exec.jar to portal-tika

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by tinatian** [comment]
@rafaprax Code looks good to me, wait for QA to scan test results.

Tina

**Comment by rafaprax** [comment]
Hey, @koor4356 Can you help me check the test results? Thx

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
@rafaprax 
This looks good, thanks!

**Comment by rafaprax** [comment]
Hey @shuyangzhou It is ready for your review. Thx

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114746

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
