### PR TITLE
LPS-148135 replace proxy creation, modules

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian This is the last pr for proxy replacement.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test result.


Tina.

**Comment by tinatian** [comment]
@JanisZhang  Code looks good to me, wait for QA to scan test results.

Tina

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114272

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
