### PR TITLE
LPS-188256 Improve memory handling

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-188256](https://liferay.atlassian.net/browse/LPS-188256)
Dear Team,

This is the continuation of https://github.com/liferay-core-infra/liferay-portal/pull/4827, using the same approach as [LPS-183838](https://liferay.atlassian.net/browse/LPS-183838) as suggested by @tinatian .

**Testing notes:** I could test only with the followings.
- CTSQLTransformerTest completed successfully
- In heap dump I see that DynamicPortalCache instances are used instead of LRUMap.

Please let me know if you have any questions or concerns.

Thank you,
István

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
@istvansajtos No regressions found. Only semver issues. Testing passed on the ticket.
```
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.kernel.util                     MAJOR      60.1.0     60.0.0     61.0.0     VERSION INCREASE REQUIRED
[beanshell] 	>   interface  com.liferay.portal.kernel.util.PropsKeys
[beanshell] 		-   field      CHANGE_TRACKING_SQL_TRANSFORMER_CACHE_SIZE
[beanshell] 			-   access     final
[beanshell] 			-   access     static
[beanshell] 			-   constant   change.tracking.sql.transformer.cache.size
[beanshell] 			-   return     java.lang.String
[beanshell] 		+   field      LAYOUT_USER_ACCESS_VIA_PLID_ENABLED
[beanshell] 			+   access     final
[beanshell] 			+   access     static
[beanshell] 			+   constant   layout.user.access.via.plid.enabled
[beanshell] 			+   return     java.lang.String
[beanshell] 	-   version    60.0.0
[beanshell] 	+   version    60.1.0
[beanshell] 
[stopwatch] [run.batch.test.action: 4.517 sec]
```

```
 [exec] > Task :baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.util                            MAJOR      49.1.0     49.0.0     50.0.0     VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.portal.util.PropsValues
     [exec] 		-   field      CHANGE_TRACKING_SQL_TRANSFORMER_CACHE_SIZE
     [exec] 			-   access     static
     [exec] 			-   return     int
     [exec] 		+   field      LAYOUT_USER_ACCESS_VIA_PLID_ENABLED
     [exec] 			+   access     static
     [exec] 			+   return     boolean
     [exec] 	-   version    49.0.0
     [exec] 	+   version    49.1.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] 
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-impl/portal-impl.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.impl/80.0.1/8aed1c1cd13777a944355d19638721387848bf7a/com.liferay.portal.impl-80.0.1.jar
```
[Log](https://testray.liferay.com/reports/production/logs/2023-06/test-1-40/test-portal-acceptance-pullrequest(master)/3620/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by istvansajtos** [comment]
Thank you @Kvale1733! I added new commit with the semver changes. Nothing else was changed.

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
Semver issue is fixed.

**Review by dantewang — CHANGES_REQUESTED** [review]
Mark as "Request Changes" as per Tina's comment

**Comment by Kvale1733** [comment]
@istvansajtos Adding qa-ignore label for now. Please remove when the requested changes are made so QA can scan ci results.

**Comment by istvansajtos** [comment]
@tinatian, @dantewang, @Kvale1733 I've added the requested change to [LPS-188256 Remove unused property](https://github.com/liferay-core-infra/liferay-portal/pull/4853/commits/4706fdbe3125ba0753347fd1cf3f0742352706fd). 

Please let me know if any other change is required. Thank you!

**Comment by Kvale1733** [comment]
@istvansajtos No regressions found. Verified this fixes the issue.

**Comment by tinatian** [comment]
ci:forward:force

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
