### PR TITLE
[LPD-28518 Destination] LPD-28519 Clean up references to Destination

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:help

**Comment by tinatian** [comment]
ci:report:17661376

**Comment by tinatian** [comment]
No unique failure found in report.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/151426

**Pull request closed without merging**
