### PR TITLE
[Bug Fix]LPS-181669 class ClusterExecutorImpl cannot re register DebuggingClusterEventListenerImpl When configuration "debug-enabled" is changed multiple times

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4260

Changes:

1. Assert empty instead of size.
2. Extract duplicate logic as a private method.

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:clustering

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
no conflicts(4/25 8:02)

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(4/26 7:48)

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4377

**Pull request closed without merging**
