### PR TITLE
[Method References 2] LPS-164448

### PR DESCRIPTION
**Pull request by JanisZhang**
This PR is to use serviceTrackerMap instead of the method reference in portal-reports-engine-console-jasper. Thanks!
https://issues.liferay.com/browse/LPS-164448

Previous P/R: https://github.com/liferay-core-infra/liferay-portal/pull/2358

### CODE REVIEW

**Comment by dantewang** [comment]
@JanisZhang @W2jx For public APIs we want to remove, let's do this:

- If it's in our component, remove it because we have control on it.
- If it's in other team's component, like `SettingsContributor` in the pull Jiaxu modified, let's ask the product team whether we can remove it.

For internal APIs, feel free to remove them.

@JanisZhang So, in this PR, I'd like to ask about https://github.com/liferay-core-infra/liferay-portal/pull/2447/commits/8c953d43bffad40ada0e876fcc70f8d7450e4136.

**Comment by dantewang** [comment]
@JanisZhang Please modify your commit message, don't use "remove" although you are removing it. This is because it's weird to see someone modify a class and then remove it.

Just use `inline`, so you make it clear that you are not removing it completely, but moving the logic to another place where the only usage is.

**Comment by JanisZhang** [comment]
Hi @dantewang, Force-pushed. Thanks!

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2478

**Pull request closed without merging**
