### PR TITLE
[TECHNICAL SUPPORT] LPS-171056 sendRedirect won't work with custom context

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
`DirectServletRegistryImpl` does not account for the `contextPath` when populating the `_servletInfos` map: https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/servlet/DirectServletRegistryImpl.java#L84-L103

Specifically, the getFileLastModified method: https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/servlet/DirectServletRegistryImpl.java#L113

The `path` here, includes the `contextPath`, which is incorrect and ends up pointing to a non-existent file.
As a result, the `_servletInfos` map is not populated and also leads to sendRedirect having no effect.

Thanks to @ericyanLr for finding the root cause and offering an in-depth explanation.

Other issues have been pointed out [here](https://github.com/liferay-core-infra/liferay-portal/pull/2730#issuecomment-1352671099) so I have adjusted the solution.

https://issues.liferay.com/browse/LPS-171056

Proposed Solution
========
Removing the `contextPath` from the `path` results in a valid file and the redirect will work.

Steps to Verify
========
Please consult the linked LPS.

Thank you and best regards,
István

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
No regressions found and manual testing passed following ticket steps.

**Review by dantewang — APPROVED** [review]

**Comment by IstvanD** [comment]
Dear Team,

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by tinatian** [comment]
@IstvanD Can you add integration test?

Tina

**Comment by tinatian** [comment]
@IstvanD The solution does not seem right. The put and get should be consistent, meaning that if you skip some prefix when putting, you should do same thing when you get.

For this "DirectServletRegistryImpl does not account for the contextPath when populating the _servletInfos map", it was added to fix a bug (https://issues.liferay.com/browse/LPS-108204), I am not sure if this is right, at least it makes the put and get inconsistent after that.

Please also try to add test to make the expected behavior clear.

Thanks.
Tina.

**Comment by IstvanD** [comment]
Hi @tinatian 

Thank you for the feedback. I have added the requested changes and created an integration test. See https://github.com/liferay-core-infra/liferay-portal/pull/2826

**Pull request closed without merging**
