### PR TITLE
[Components with more than 1 service] LPS-192993 Refactor ManagedServiceFactory from oauth2-provider-rest, document-library-preview-pdf and portal-security-sso-openid-connect-impl modules

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-192993](https://liferay.atlassian.net/browse/LPS-192993)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:document

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5440

**Pull request closed without merging**
