### PR TITLE
LPS-138375 move jericho-html to shared-dependencies

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Resend: Rename the bundle name to : Liferay Shared Dependencies **Jericho Html**
This is for ticket https://issues.liferay.com/browse/LPS-138375.
I am trying to move jericho-html to shared-dependencies.
Thanks for checking

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
No regressions found from the relevant tests.

The SF failure seems unrelated.

**Comment by jeffwu0724** [comment]
fixed the code conflict

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126747

**Pull request closed without merging**
