### PR TITLE
Lps 176881

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
BuildLang to fix code conflicts, no need to retrigger tests.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131012

**Pull request closed without merging**
