### PR TITLE
LPS-193392 patch hsql with jdk 8 and enable debug information

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian ,

Resent https://github.com/liferay-core-infra/liferay-portal/pull/5254
I patched hsql with jdk8 and enable debug information. 
Comapred to before, hsql only show  `Unknown Source`
```
[9:09 AM] Caused by: java.sql.BatchUpdateException: transaction rollback: serialization failure
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeBatch(Unknown Source) ~[hsql.jar:2.7.1]
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127) ~[hikaricp.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[hikaricp.jar:?]
	at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:125) ~[hibernate-core.jar:5.6.7.Final]
```
Now the class name and line number will also show
```
  at org.hsqldb.jdbc.JDBCUtil.sqlException(JDBCUtil.java:271) ~[hsql.jar:2.7.1]
  at org.hsqldb.jdbc.JDBCUtil.sqlException(JDBCUtil.java:157) ~[hsql.jar:2.7.1]
  at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(JDBCPreparedStatement.java:4048) ~[hsql.jar:2.7.1]
  at org.hsqldb.jdbc.JDBCConnection.prepareStatement(JDBCConnection.java:589) ~[hsql.jar:2.7.1]
  at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337) ~[hikaricp.jar:?]
  at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[hikaricp.jar:?]
```
Thanks for checknig!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:environments

**Comment by jeffwu0724** [comment]
Hey team, could you please help me do one extra checking at your end, please?

1. With the code in this PR, we also make a small changes here https://github.com/jeffwu0724/liferay-portal/pull/368/commits/8c44b5c67c373e859e41a7c990337838269e0fbe. run `ant all`
2. start up portal, it should has lots of warning about database. Wait till the end, then we can search "org.hsqldb.jdbc" in the console log, and check if the class name and line number shown, instead of showing `Unknown Source` for hsql

Expected:
```
at org.hsqldb.jdbc.JDBCUtil.sqlException(JDBCUtil.java:271) ~[hsql.jar:2.7.1]
at org.hsqldb.jdbc.JDBCUtil.sqlException(JDBCUtil.java:157) ~[hsql.jar:2.7.1]
```
Not Expected:
```
at org.hsqldb.jdbc.JDBCPreparedStatement.executeBatch(Unknown Source) ~[hsql.jar:2.7.1]
```
Thanks for checking!

**Comment by jeffwu0724** [comment]
Please also make sure the regressions here are gone. https://github.com/liferay-core-infra/liferay-portal/pull/5254#issuecomment-1682427328

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 Found no regressions. Got the expected message

```
at org.hsqldb.jdbc.JDBCUtil.sqlException(JDBCUtil.java:271) ~[hsql.jar:2.7.1]
at org.hsqldb.jdbc.JDBCUtil.sqlException(JDBCUtil.java:157) ~[hsql.jar:2.7.1]
```

**Pull request closed without merging**
