### PR TITLE
[Reference cleanup]LPS-160968

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to replace method setServletContext with field _servletContext in class extends BaseDynamicInclude. Thanks!
https://issues.liferay.com/browse/LPS-160968

Previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/1393

### CODE REVIEW

**Comment by tinatian** [comment]
@JanisZhang Code looks good to me, wait for QA to scan test results.
@zhangyan0701 Please help me scan test results.

Tina

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by dantewang** [comment]
@JanisZhang Conflict on bnd.bnd

**Comment by JanisZhang** [comment]
Hi @dantewang @tinatian, force-pushed, bnd conflicts. 

cc @zhangyan0701

**Comment by shuyangzhou** [comment]
@JanisZhang please rebase.

**Pull request closed without merging**
