### PR TITLE
LPS-171208 Remove "immediate = true" from remaining USM modules

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:usm

**Comment by Kvale1733** [comment]
@daiazius No regressions.

**Comment by daiazius** [comment]
Hey @shuyangzhou, can you review this PR please? thank you

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128021

**Pull request closed without merging**
