### PR TITLE
LPS-158311 Part 2: merge listeners | 10-19

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
[Semantic version](https://testray.liferay.com/home/-/testray/case_results/2010157166) issue:
```
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.backgroundtask           MAJOR      9.0.0      9.0.0      10.0.0     VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.portal.kernel.backgroundtask.BackgroundTaskStatusRegistryUtil
     [exec] 		-   method     registerBackgroundTaskStatus(long)
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.backgroundtask.BackgroundTaskStatus
     [exec] 		+   method     registerBackgroundTaskStatus(long,com.liferay.portal.kernel.backgroundtask.BackgroundTaskStatusMessageTranslator)
     [exec] 			+   access     static
     [exec] 			+   return     com.liferay.portal.kernel.backgroundtask.BackgroundTaskStatus
     [exec] 	>   interface  com.liferay.portal.kernel.backgroundtask.BackgroundTaskStatusRegistry
     [exec] 		+   method     getBackgroundTaskStatusMessageTranslator(long)
     [exec] 			+   access     abstract
     [exec] 			+   return     com.liferay.portal.kernel.backgroundtask.BackgroundTaskStatusMessageTranslator
     [exec] 		-   method     registerBackgroundTaskStatus(long)
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.portal.kernel.backgroundtask.BackgroundTaskStatus
     [exec] 		+   method     registerBackgroundTaskStatus(long,com.liferay.portal.kernel.backgroundtask.BackgroundTaskStatusMessageTranslator)
     [exec] 			+   access     abstract
     [exec] 			+   return     com.liferay.portal.kernel.backgroundtask.BackgroundTaskStatus
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/81.0.0/d41e7e4f834a08a646b56b93009307ae57488ab4/com.liferay.portal.kernel-81.0.0.jar
```
Full console:
https://testray.liferay.com/reports/production/logs/2022-10/test-1-37/test-portal-acceptance-pullrequest(master)/5753/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@catarineaguiar Could you help me recheck the new results? The sem-ver error should be fixed by https://github.com/liferay-core-infra/liferay-portal/pull/2124/commits/c392276b63d8df198743037e17e997fa570ff9da.

**Comment by Kvale1733** [comment]
@dantewang There is no semver error on the most recent relevant run. No regressions found.

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:workflow-metrics

**Comment by dantewang** [comment]
ci:test:onedrive

**Comment by dantewang** [comment]
ci:test:export-import

**Comment by dantewang** [comment]
Running some additional tests in components that implements `BackgroundTaskStatusMessageTranslator`.

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2252

**Pull request closed without merging**
