### PR TITLE
LPS-177178 Remove leftovers "immediate = true" from Segments Asah

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-177178

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:analytics-cloud-acceptance

**Comment by catarineaguiar** [comment]
no regressions found.

AC tests failure is not related.

**Comment by tinatian** [comment]
@rafaprax EventSegmentsCriteriaContributor is registered as service twice, one is by @Component, the other is inside its own activate method, please make it only register once.

Please resend.

Thanks.
Tina

**Pull request closed without merging**
