### PR TITLE
LPS-176215 ES connection pool | 2-27

### PR DESCRIPTION
**Pull request by dantewang**
Resend as per https://github.com/brianchandotcom/liferay-portal/pull/130826#issuecomment-1445724007

### CODE REVIEW

**Comment by dantewang** [comment]
cc @lipusz @gustavolimav @shuyangzhou @tinatian 

This resend just contains renaming requested by BChan.

**Comment by lipusz** [comment]
@liferay/qa-search

**Comment by catarineaguiar** [comment]
Tests seem to fail on CI, not related to this pull.

**Comment by catarineaguiar** [comment]
ci:test:search

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian @lipusz

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
