### PR TITLE
[Method References 2] LPS-171231 Convert method reference to ServiceTrackerMap in class MultiLanguageKaleoTaskAssignmentSelector

### PR DESCRIPTION
**Pull request by W2jx**
Hi @dantewang , I have cleaned up the Script language and simplified the tracking logic

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4734

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:workflow

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
@W2jx regression found:

```
     [exec] com.liferay.portal.workflow.kaleo.definition.ScriptingLanguageTest > testParseScriptingLanguages FAILED
     [exec]     com.liferay.portal.workflow.kaleo.definition.exception.KaleoDefinitionValidationException$InvalidScriptLanguage: Invalid script language beanshell
     [exec]         at com.liferay.portal.workflow.kaleo.definition.ScriptLanguage.parse(ScriptLanguage.java:58)
     [exec]         at com.liferay.portal.workflow.kaleo.definition.ScriptingLanguageTest.testParseScriptingLanguages(ScriptingLanguageTest.java:43)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-06/test-1-33/test-portal-acceptance-pullrequest(master)/3796/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
Force-Push is just to fix the test.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
@W2jx Regression found. Cannot edit single approver workflow

Steps to Reproduce:
1. Go to Content & Data > Kaleo Forms Admin
2. Click the blue plus button to add new process
3. Add any name and click next
4. Click Ellipses Next to "To Do" and click "Choose"
5. Click Next
6. Click Ellipses next to Single Approver and click Edit
7. Change the title to any title
8. Click Source Tab
9. Import the following file as source 
[Test.txt](https://github.com/liferay-core-infra/liferay-portal/files/11725767/Test.txt)
10. Click Update
11. Close the Workflow Modal
12. Assert the changes were updated

Expected Results: The Single Approver Workflow is edited successfully
Actual Results: The edit is not saved

https://github.com/liferay-core-infra/liferay-portal/assets/90647688/7090bb6d-d721-42d6-a5b6-66f51854a77c

**Comment by W2jx** [comment]
I will resend this after pr https://github.com/liferay-core-infra/liferay-portal/pull/4774 is merged.

**Pull request closed without merging**
