### PR TITLE
LPS-142048

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr drops the related changes about bcprov & bcmail.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@yuhai Do we really need https://github.com/liferay-core-infra/liferay-portal/pull/2/commits/eda2a83ea006f6caf2bf30640d97903ed2e9fdcd if we exclude bcprov and bcmail?

**Comment by dantewang** [comment]
@simonjhy Does the last commit look good to you?

**Comment by yuhai** [comment]
> @yuhai Do we really need [eda2a83](https://github.com/liferay-core-infra/liferay-portal/commit/eda2a83ea006f6caf2bf30640d97903ed2e9fdcd) if we exclude bcprov and bcmail?

@dantewang, yes, the commit can solve the below errors:
`error  : Classes found in the wrong directory: {META-INF/versions/9/org/apache/logging/log4j/core/util/SystemClock.class=org.apache.logging.log4j.core.util.SystemClock, META-INF/versions/9/javax/xml/bind/ModuleUtil.class=javax.xml.bind.ModuleUtil, META-INF/versions/9/org/apache/logging/log4j/util/StackLocator.class=org.apache.logging.log4j.util.StackLocator, META-INF/versions/9/module-info.class=module-info, META-INF/versions/9/org/apache/logging/log4j/util/internal/DefaultObjectInputFilter.class=org.apache.logging.log4j.util.internal.DefaultObjectInputFilter, META-INF/versions/9/org/apache/logging/log4j/util/Base64Util.class=org.apache.logging.log4j.util.Base64Util, META-INF/versions/9/org/apache/logging/log4j/util/ProcessIdUtil.class=org.apache.logging.log4j.util.ProcessIdUtil}`

cc @tinatian

**Comment by dantewang** [comment]
@yuhai When posting logs please use 3 back-ticks "```" instead of inline syntax highlighting using single back-tick:

```
error : Classes found in the wrong directory: {META-INF/versions/9/org/apache/logging/log4j/core/util/SystemClock.class=org.apache.logging.log4j.core.util.SystemClock, META-INF/versions/9/javax/xml/bind/ModuleUtil.class=javax.xml.bind.ModuleUtil, META-INF/versions/9/org/apache/logging/log4j/util/StackLocator.class=org.apache.logging.log4j.util.StackLocator, META-INF/versions/9/module-info.class=module-info, META-INF/versions/9/org/apache/logging/log4j/util/internal/DefaultObjectInputFilter.class=org.apache.logging.log4j.util.internal.DefaultObjectInputFilter, META-INF/versions/9/org/apache/logging/log4j/util/Base64Util.class=org.apache.logging.log4j.util.Base64Util, META-INF/versions/9/org/apache/logging/log4j/util/ProcessIdUtil.class=org.apache.logging.log4j.util.ProcessIdUtil}
```

@tinatian My bad, I mixed this with some previous discussions with Hai.

Actually only libs that are exported in system.packages.extra.bnd need this instruction. So in this pull, bouncy castle does not need it. Instead, Log4J needs it.

In this case I think we can add back the bouncy castle change (although others may remove the jars later -- I asked Arthur to try it when he starts to work on it).

**Comment by yuhai** [comment]
@dantewang, got it. I will use 3 back-ticks "```" when posting logs.

@tinatian, if add back the bouncy castle change, we may use the [pr](https://github.com/tinatian/liferay-portal/pull/2437). If necessary, I will resend it.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
