### PR TITLE
[Bug Fix]LPS-140601 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by vicnate5** [comment]
@koor4356 Can you check this one? See the bug ticket for the manual testing steps too.

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
Looks good. 

Screen Shot 2022-02-15 at 9 01 00 AM

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
