### PR TITLE
[OrderByComparator] LPD 26859 Clean up and Apply Singleton in module message-boards part II

### PR DESCRIPTION
**Pull request by rubenssoares-br**
Ticket: https://liferay.atlassian.net/browse/LPD-26859

### CODE REVIEW

**Comment by rubenssoares-br** [comment]
ci:test:content-management

**Comment by rubenssoares-br** [comment]
ci:test:sf

**Comment by rubenssoares-br** [comment]
ci:test:relevant

**Comment by rubenssoares-br** [comment]
ci:test:content-management

**Comment by Valmir-unicap** [comment]
ci:stop

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:report:11992031

**Comment by Valmir-unicap** [comment]
ci:report:9258098

**Review by Valmir-unicap — APPROVED** [review]

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
Reevaluating!
CC: @titokenzo

**Pull request closed without merging**
