### PR TITLE
[Remove Stream/Optional usage] LPS-175357 modules: layout-page-template-admin-web, layout-page-template-service, layout-page-template-test, layout-portlets-web, layout-reports-web, layout-seo-web-test

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend, thanks!
Previous:  https://github.com/liferay-core-infra/liferay-portal/pull/3537
https://issues.liferay.com/browse/LPS-175357

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Pull request closed without merging**
