### PR TITLE
LPD-25535 Adapt tests using hard-coded test password in User Tracker component

### PR DESCRIPTION
**Pull request by MrJohn1911**
Tested here: https://github.com/MrJohn1911/liferay-portal/pull/83

The tests did't fail / didn't had any unique failure.

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:core-functional

**Comment by MrJohn1911** [comment]
ci:report:2568262993

**Comment by MrJohn1911** [comment]
ci:test:core-functional

**Comment by tinatian** [comment]
ci:report:2568458151

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
