### PR TITLE
LPS-147929 Move petra-json-validator to modules/app directly

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,

Main Task: [LPS-147928 Remove petra jar from modules/apps](https://issues.liferay.com/browse/LPS-147928)
Sub Task: [LPS-147929 Move petra-json-validator to modules/app directly](https://issues.liferay.com/browse/LPS-147929)

Thank you!

### CODE REVIEW

**Comment by tinatian** [comment]
@julschong Code looks good to me, code conflicts, please rebase.

Thanks.
Tina.

**Comment by julschong** [comment]
@tinatian pushed and rebased. reran the 3 auto generated commands at the end

**Comment by tinatian** [comment]
@zhangyan0701 please help me scan test results.

Thanks.
Tina.

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
No related failures.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116150

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
