### PR TITLE
[Eliminate unused reference]LPS-200293

### PR DESCRIPTION
**Pull request by JanisZhang**
Remove unused reference fields in class `SubscriptionDLAppHelperLocalServiceWrapper`, `CheckoutCTCollectionMVCActionCommand`, `GetTemplateCollaboratorsMVCResourceCommand`, and `UpdateGlobalPublicationsConfigurationMVCActionCommand`. Thanks.
https://liferay.atlassian.net/browse/LPS-200293

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:document

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
No regressions found. Lets just wait for the stable results to see if the license batch passes.

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
