### PR TITLE
[TS] LPS-188294 Fix duplicated web contents when filtering with Recent and Status

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
The used sql id is [com.liferay.journal.service.persistence.JournalArticleFinder.findByG_U_F_C](https://github.com/liferay/liferay-portal/blob/b7f74f00058aa4d7252db6e241f8ca9bf7bbddc9/modules/apps/journal/journal-service/src/main/resources/META-INF/custom-sql/default.xml#L173)

Is replacing `([$OWNER_USER_ID$] [$OWNER_USER_ID_AND_OR_CONNECTOR$] [$STATUS$])` with `AND  ((JournalArticle.userId = ? AND JournalArticle.status != ?)  OR  JournalArticle.status != ?)`  

The last OR creates problems as it returns all the statuses and not just the one we are interested in, so we see duplicates.

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
> HEAD 'https://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.gradle.plugins.maven.plugin.builder/2.0.0/com.liferay.gradle.plugins.maven.plugin.builder-2.0.0.pom'.
>      [exec]             > repository-cdn.liferay.

I don't get this on local:
image

**Comment by catarineaguiar** [comment]
Hey @georgel-pop-lr the bug is not reproducible with your changes (there are no duplicates when using filtering by Recent and With Approved Version)

but a regression was found when upgrading with a smoke dump:

Steps to reproduce with MySQL locally:

1. unzip [data-archive-portal-mysql.zip](https://github.com/liferay-core-infra/liferay-portal/files/11850648/data-archive-portal-mysql.zip)
2. into this directory, run `mysql -u root lportal<mysql.sql` 
3. move the data folder to your bundle
4. go to bundles/tools/portal-tools-db-upgrade-client > run ./db_upgrade.sh run
5. click enter for all questions, except when it asks for you db username and password
6. wait for the upgrade to be done
7. start portal

Actual result: 
each page shows their respective contents, except the message boards page (it doesn't have the Message Boards Subject)

Expected result:
All pages have their respective content

**Comment by georgel-pop-lr** [comment]
> Hey @georgel-pop-lr the bug is not reproducible with your changes (there are no duplicates when using filtering by Recent and With Approved Version) and SF issue is not related
> 
> but a regression was found when upgrading with a smoke dump:
> 
> Steps to reproduce with MySQL locally:
> 
> 1. unzip [data-archive-portal-mysql.zip](https://github.com/liferay-core-infra/liferay-portal/files/11850648/data-archive-portal-mysql.zip)
> 2. into this directory, run `mysql -u root lportal<mysql.sql`
> 3. move the data folder to your bundle
> 4. go to bundles/tools/portal-tools-db-upgrade-client > run ./db_upgrade.sh run
> 5. click enter for all questions, except when it asks for you db username and password
> 6. wait for the upgrade to be done
> 7. start portal
> 
> Actual result: each page shows their respective contents, except the message boards page (it doesn't have the Message Boards Subject)
> 
> Expected result: All pages have their respective content

Hi,

What exactly are you migrating, from a specific version?

What about the failed tests, are they related to my change?

Regards.

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
> > Hey @georgel-pop-lr the bug is not reproducible with your changes (there are no duplicates when using filtering by Recent and With Approved Version) and SF issue is not related
> > but a regression was found when upgrading with a smoke dump:
> > Steps to reproduce with MySQL locally:
> > 
> > 1. unzip [data-archive-portal-mysql.zip](https://github.com/liferay-core-infra/liferay-portal/files/11850648/data-archive-portal-mysql.zip)
> > 2. into this directory, run `mysql -u root lportal<mysql.sql`
> > 3. move the data folder to your bundle
> > 4. go to bundles/tools/portal-tools-db-upgrade-client > run ./db_upgrade.sh run
> > 5. click enter for all questions, except when it asks for you db username and password
> > 6. wait for the upgrade to be done
> > 7. start portal
> > 
> > Actual result: each page shows their respective contents, except the message boards page (it doesn't have the Message Boards Subject)
> > Expected result: All pages have their respective content
> 
> Hi,
> 
> What exactly are you migrating, from a specific version?
> 
> What about the failed tests, are they related to my change?
> 
> Regards.

Hi, 

Could I ask if is possible to be reviewed by someone from core team, as I'm not sure if this is the best solution for this issue?

This code has not been changed for years, and I would like to be reviewed from someone with more experience on this part.

Also is possible that we have to change the sql in default.xml https://github.com/liferay/liferay-portal/blob/b7f74f00058aa4d7252db6e241f8ca9bf7bbddc9/modules/apps/journal/journal-service/src/main/resources/META-INF/custom-sql/default.xml#L173

Any opinion would be good.

Regards.

**Comment by catarineaguiar** [comment]
Hi @georgel-pop-lr, sorry the delay. 

I re-analyzed relevant results and the failure is still happening on:
[PortalSmokeUpgrade#ViewPortalSmokeArchive7413](https://testray.liferay.com/home/-/testray/case_results/2369400752?tab=history)
[PortalSmokeUpgrade#ViewPortalSmokeArchive7413](https://testray.liferay.com/home/-/testray/case_results/2369400724?tab=history)
[PortalSmokeUpgrade#ViewPortalSmokeArchive7310](https://testray.liferay.com/home/-/testray/case_results/2369400694?tab=history)
[PortalSmokeUpgrade#ViewPortalSmokeArchive70106](https://testray.liferay.com/home/-/testray/case_results/2369400696?tab=history)
[PortalSmokeUpgrade#ViewPortalSmokeArchive621021](https://testray.liferay.com/home/-/testray/case_results/2369400741?tab=history)

The dump has a web content, a document, message boards subject, wiki and blogs (is exactly the dump I sent in the above message)

FYI when I reproduced locally, after reindexing the message board subject was shown, but the failure keeps happening on functional tests, so something might be wrong.

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr, sorry the delay.
> 
> I re-analyzed relevant results and the failure is still happening on: [PortalSmokeUpgrade#ViewPortalSmokeArchive7413](https://testray.liferay.com/home/-/testray/case_results/2369400752?tab=history) [PortalSmokeUpgrade#ViewPortalSmokeArchive7413](https://testray.liferay.com/home/-/testray/case_results/2369400724?tab=history) [PortalSmokeUpgrade#ViewPortalSmokeArchive7310](https://testray.liferay.com/home/-/testray/case_results/2369400694?tab=history) [PortalSmokeUpgrade#ViewPortalSmokeArchive70106](https://testray.liferay.com/home/-/testray/case_results/2369400696?tab=history) [PortalSmokeUpgrade#ViewPortalSmokeArchive621021](https://testray.liferay.com/home/-/testray/case_results/2369400741?tab=history)
> 
> The dump has a web content, a document, message boards subject, wiki and blogs (is exactly the dump I sent in the above message)
> 
> FYI when I reproduced locally, after reindexing the message board subject was shown, but the failure keeps happening on functional tests, so something might be wrong.

Hi again,

Thanks for having a look at failing tests.

Can I ask for a review from core team, before trying to solve the failing tests?

I'm asking this as maybe this is not the correct solution, as I said here https://github.com/liferay-core-infra/liferay-portal/pull/4851#issuecomment-1617751865 this code is unchanged from a very long time, and I'm not sure if this is the way to solve it.

Regards.

**Comment by catarineaguiar** [comment]
@yuhai do you mind taking a look?

**Comment by catarineaguiar** [comment]
@georgel-pop-lr I believe the failure seems to be caused by a reindex performance issue, when the test run reindex it's taking more time than expected.

**Comment by yuhai** [comment]
Hi @georgel-pop-lr,

The solution is not right. Please see the below explanation.

When queryDefinition.isIncludeOwner() is true, the sql is 
**((JournalArticle.userId = ? AND JournalArticle.status != ?)  OR  JournalArticle.status = ?)**
When queryDefinition.isIncludeOwner() is false, the sql is
**(JournalArticle.userId = ?  AND  JournalArticle.status = ?)**

In your fix, when queryDefinition.isIncludeOwner() is true, the sql is 
**((JournalArticle.userId = ? AND JournalArticle.status != ?)  AND JournalArticle.status = ?)**
Actually, it equals to the sql when queryDefinition.isIncludeOwner() is false. The checker includeOwner will be meaningless.

I suggest you may try to check web content logic to fix the issue. I think you may check JournalDisplayContext. The issue doesn't happen when filter by Mine due to https://github.com/georgel-pop-lr/liferay-portal/blob/LPS-188294/modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/display/context/JournalDisplayContext.java#L1136-L1140.

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by yuhai** [comment]
Hi @georgel-pop-lr,

Because the current fix is in web content. Please send the fix to liferay-echo to review.

I am going to close the pr.

Thanks,
Hai

**Pull request closed without merging**
