### PR TITLE
[Method References] LPS-163770 Convert method references to field references in module portal-search-elasticsearch7-impl | part 7

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I convert method references to field references in module portal-search-elasticsearch7-impl.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by dantewang** [comment]
Waiting for @zhangyan0701 to check result.

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@shuyangzhou @tinatian See https://github.com/brianchandotcom/liferay-portal/pull/123603

**Pull request closed without merging**
