### PR TITLE
Lps 135298 1 21

### PR DESCRIPTION
**Pull request by slnn**
No logic change, just do rename follow the comment:
https://github.com/brianchandotcom/liferay-portal/pull/112269#issuecomment-1015861766

/cc @dantewang @tinatian

Lily

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@slnn The message of the last commit: **LPT**-135298. You can change it and force push.

**Comment by slnn** [comment]
OK, got it.
Sorry, I did not notice that..

**Comment by slnn** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
FYI @shuyangzhou Code was reviewed, logic is not changed but rename as requested by the comment:
brianchandotcom#112269 (comment)

**Pull request closed without merging**
