### PR TITLE
Lpd 41167 v3

### PR DESCRIPTION
**Pull request by shuyangzhou**
@pedro-oliveira446 please rerun necessary CI tests.

As a general api design rule, when you have to add some complexity and you have the options of either adding it through interface or impl only, always keep interface clean, do it at impl level. And when you do have to add some thing through interface, try to do as much as you can internally rather letting the invoker to do more post-procesing.

@JerryAdrianoo @victorhcunha please rerun the startup check, this should not make any difference comparing to your previous check.

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
I'm using the same baseline as the previous check to have comparable results.
And I saw that this current version has higher values ​​than the previous one for Prepared Statement, see:

Portal Version CE| Open count of Prepared Statement | Count of Prepared Statement Query
-- | -- | --
Master Baseline 4980b7eb | 148 | 222
Old LPD-41266 v3 https://github.com/liferay-core-infra/liferay-portal/pull/7684 | 134 | 201
Current LPD-41266 v3 | 138 | 207


More details can be found [here](https://docs.google.com/spreadsheets/d/1WC5NZgLfrZ7UK-M-9WY6Bl2EWG79xfn8T-ybQD3SRAs/edit?gid=750444333#gid=750444333).

**Comment by shuyangzhou** [comment]
@victorhcunha I only see one profile attachment, please upload them all

**Comment by victorhcunha** [comment]
@shuyangzhou 
Sure! I was looking for the files in the directory.
The spreadsheet is updated with the other profiles.

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:object

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
I uploaded the [spreadsheet](https://docs.google.com/spreadsheets/d/1WC5NZgLfrZ7UK-M-9WY6Bl2EWG79xfn8T-ybQD3SRAs/edit?gid=227600943#gid=227600943) with new results using an updated baseline.

Here are the comparisons:

Portal Version CE| Open count of Prepared Statement | Count of Prepared Statement Query
-- | -- | --
Master Baseline c163f5a5 | 148 | 222
Old LPD-41266 v3 https://github.com/liferay-core-infra/liferay-portal/pull/7684 | 134 | 201
Current LPD-41266 v3 | 138 | 207

The profile files are also available.

**Comment by shuyangzhou** [comment]
Resent at  https://github.com/liferay-core-infra/liferay-portal/pull/7702

**Pull request closed without merging**
