### PR TITLE
[Login Performance]LPS-150699

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results when it is finished.

Thanks.
Tina.

**Comment by catarineaguiar** [comment]
@vicnate5 will not have time to review this one today

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by drewbrokke** [comment]
Thank you @tinatian and @dantewang!

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
