### PR TITLE
[TS] LPD-35758

### PR DESCRIPTION
**Pull request by rijema**
Cross-evaluation started here: https://github.com/liferay-objects/liferay-portal/pull/3655

Hi team. Customer wants through the FTL Template on Notifications to access its custom service.  We are trying to insert the context objects on the template we are using on Notification.

### CODE REVIEW

**Comment by ericyanLr** [comment]
Hi @rijema ,

**Regarding the commit:** 
[LPD-35758 Insert data from a custom service outside from the HTTP context on current template](https://github.com/liferay-core-infra/liferay-portal/pull/7423/commits/eb69da8ed8d1f18dddb41e7edbae00d1d1257c3b)

Is there a reason why in [EmailNotificationType.java](https://github.com/liferay-core-infra/liferay-portal/pull/7423/commits/eb69da8ed8d1f18dddb41e7edbae00d1d1257c3b#diff-990f2bd3e5ae2761d30af9c10c8971911b750c33ecd881f5d4c12721e93f6073), we have to pass in `null` for the `HttpServletRequest`?
```
template.prepare(null);
```

**Comment by rijema** [comment]
Hi @ericyanLr , with that we can solve the scenario we have today on Notifications side. Once we submit the action without the http template, your [ContextHelper](https://github.com/liferay-core-infra/liferay-portal/blob/eb69da8ed8d1f18dddb41e7edbae00d1d1257c3b/modules/apps/portal-template/portal-template-freemarker/src/main/java/com/liferay/portal/template/freemarker/internal/helper/FreeMarkerTemplateContextHelper.java#L59) will insert the contextObjects from the custom service and return, without letting the code access variables that we don't have in the httpRequest provided from our side.

**Comment by ericyanLr** [comment]
Hi @rijema ,

Sorry, I don't think I fully understand the reason, can you help clarify?

From trying to understand what you described, is the reason you want to pass in `null` for the `HttpServletRequest` because: `you don't want to give a custom notification template access to certain variables, which would be provided by the HttpServletRequest`?

**Comment by rijema** [comment]
Hi @ericyanLr . 

> From trying to understand what you described, is the reason you want to pass in null for the HttpServletRequest because: you don't want to give a custom notification template access to certain variables, which would be provided by the HttpServletRequest?

Not necessarily.

Let me try to give an alternative explanation: 

I modified FreeMarkerTemplateContextHelper to [return at this point](https://github.com/liferay-core-infra/liferay-portal/pull/7423/files#diff-fc8f35548f2da78617f34f4acded261b1a6a9611761893d841438f5ee6faeb30R58-R63) before trying to access values that the object doesn't have and avoid NPE errors.

In our case, retrieving the httpRequest from ObjectActionLocalService.getHttpRequest() and sending it, it wouldn't contain all the variables the Core class checks (per example: [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-template/portal-template-engine-api/src/main/java/com/liferay/portal/template/engine/TemplateContextHelper.java#L346).

We followed [this approach of setting null](https://github.com/liferay-core-infra/liferay-portal/pull/7423/files#diff-990f2bd3e5ae2761d30af9c10c8971911b750c33ecd881f5d4c12721e93f6073R539) to avoid populating unnecessary variables (in our case, we don't use the template for nothing else). 

Please let me know if it helps,

Thank you!

**Comment by tinatian** [comment]
@rijema This is a wrong direction to fix your issue.

In your case, you want to populate some context to render your own freemarker template, while the api provided is not meeting your requirements. In this case, you should not modify the api, you should populate all you needed to freemarker template manually by yourself.

**Comment by ericyanLr** [comment]
Hi @rijema ,

Also, if the reason is to simply avoid the NPE that is being thrown here: [prepareTiles(contextObjects, httpServletRequest)](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-template/portal-template-engine-api/src/main/java/com/liferay/portal/template/engine/TemplateContextHelper.java#L346)

I think that the NPE is likely due to a bug in that particular method, the `ThemeDisplay` portion of that logic should have handling for when `themeDisplay` is `null`.

**Comment by rijema** [comment]
Thank you for your inputs, @tinatian and @ericyanLr

**Pull request closed without merging**
