### PR TITLE
LPS-193396 Move Ghostscript into image module

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:document

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:document

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:document

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:document

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong There are startup issues

```
beanshell] 2023-08-17 19:09:41.362 ERROR [fileinstall-directory-watcher][DirectoryWatcher:1164] Unable to start bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.image.impl.jar
[beanshell] org.osgi.framework.BundleException: Could not resolve module: com.liferay.image.impl [890]
[beanshell]   Unresolved requirement: Import-Package: com.liferay.image
[beanshell] 
[beanshell] 	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundle(DirectoryWatcher.java:1147) [bundleFile:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundles(DirectoryWatcher.java:1180) [bundleFile:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startAllBundles(DirectoryWatcher.java:1121) [bundleFile:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:1032) [bundleFile:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:238) [bundleFile:?]
[beanshell] 2023-08-17 19:09:41.366 ERROR [fileinstall-directory-watcher][DirectoryWatcher:1164] Unable to start bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.document.library.preview.pdf.jar
[beanshell] org.osgi.framework.BundleException: Could not resolve module: com.liferay.document.library.preview.pdf [630]
```

```
[beanshell] Bundle {id: 362, name: com.liferay.adaptive.media.image.impl, version: 5.0.49}
[beanshell] 	Declarative Service {id: 1219, name: com.liferay.adaptive.media.image.internal.scaler.AMImageMagickImageScaler, unsatisfied references: 
[beanshell] 		{name: _imageMagick, target: null}
[beanshell] 	}
[beanshell] Bundle {id: 882, name: com.liferay.document.library.web, version: 6.0.161}
[beanshell] 	Declarative Service {id: 9192, name: com.liferay.document.library.web.internal.change.tracking.spi.display.DLFileVersionCTDisplayRenderer, unsatisfied references: 
[beanshell] 		{name: _pdfProcessor, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 9189, name: com.liferay.document.library.web.internal.change.tracking.spi.display.DLFileEntryCTDisplayRenderer, unsatisfied references: 
[beanshell] 		{name: _pdfProcessor, target: null}
[beanshell] 	}
[beanshell] 2023-08-17 19:09:57.933 INFO  [main][DependencyManagerSyncUtil:62] Running "Declarative Service Soft Circular Dependency Checker". You can run this by itself with command "ds:softCircularDependency" in gogo shell.
[beanshell] 2023-08-17 19:10:07.126 INFO  [main][DependencyManagerSyncUtil:69] Declarative Service Soft Circular Dependency Checker check result: No issues were found.
     [echo] Waiting for http://localhost:8080/web/guest to load
  [waitfor] 2023-08-17 19:10:11.670 INFO  [http-nio-8080-exec-1][BundleSiteInitializer:441] Initializing com.liferay.site.initializer.welcome for group 20119
  [waitfor] 2023-08-17 19:10:11.685 INFO  [http-nio-8080-exec-1][BundleSiteInitializer:4794] Invoking line 469 took 2 ms
```
[Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-37/test-portal-acceptance-pullrequest(master)/13853/functional-smoke-tomcat90-mysql57-jdk11_open/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
fixed startup issue

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:document

**Comment by tinatian** [comment]
@julschong Please remember to remove QA Failed flag.

Thanks.
Tina

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139706

**Pull request closed without merging**
