### PR TITLE
[Method References] LPS-160434 Replace method setPortlet with field _portlet in class extends BasePanelApp

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have replaced method setPortlet with field _portlet and removed method setUserNotificationEventLocalService in this pr
(And I hava removed method getPortlet from BasePanelApp.java)
Detail: https://github.com/liferay-core-infra/liferay-portal/pull/1418

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @catarineaguiar , Could you please help me check the test results when they finish ? Thanks!

**Comment by W2jx** [comment]
no conflicts(6:17 PM)

**Review by dantewang — APPROVED** [review]

**Comment by W2jx** [comment]
no conflicts(6:50 AM)

**Comment by tinatian** [comment]
@W2jx In this commit, you did two things, I am confused why you put these things together into one commit, are they related?
For the BasePanelApp change, please verify first if this is a bug, please check if we should setUserNotificationEventLocalService somewhere but did not, if that's the case, the fix should be add setUserNotificationEventLocalService somewhere instead of removing it. 
I know with this change, you did not change anything, but after you change it, please read the whole class and think about it, dose it make sense?

Tina

**Comment by W2jx** [comment]
@tinatian Thank you

**Comment by W2jx** [comment]
Hi @tinatian ,Can I do something about the  replace method setPortlet in this task , and push the thing about the remove method setUserNotificationEventLocalService to a new task?

**Pull request closed without merging**
