### PR TITLE
[TS] LPD-22268 Remove Jalopy dependency

### PR DESCRIPTION
**Pull request by kevhlee**
__Tickets:__
- <https://liferay.atlassian.net/browse/LPD-22268>

As requested [here](https://github.com/liferay-core-infra/liferay-portal/pull/6834), I have removed Jalopy from the portal.

Let me know if I need to make any changes.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
@tinatian, I am taking a look.

**Comment by kevhlee** [comment]
ci:report:2558447229

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:report:2558718632

**Comment by kevhlee** [comment]
Going to resend.

**Pull request closed without merging**
