### PR TITLE
LPS-172157 Remove "immediate = true" from Security components part 3

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:security

**Comment by Kvale1733** [comment]
@GabrielHenriquedev No regressions found.

**Comment by GabrielHenriquedev** [comment]
@tinatian this one is ready to go.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129206

**Pull request closed without merging**
