### PR TITLE
LPD-28759 Control whether to create the default admin when creating company

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:59837292

**Comment by tinatian** [comment]
ci:report:59822730

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 59822730.
> 
> Job Link: [generate-testray-csv](https://test-1-39.liferay.com/job/generate-testray-csv/355/)
> 
> Testray CSV Link: [testray-results-59822730.csv](https://test-1-39.liferay.com/userContent/jobs/generate-testray-csv/builds/355/testray-results-59822730.csv)

Unique failures in report are not real

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 59837292.
> 
> Job Link: [generate-testray-csv](https://test-1-31.liferay.com/job/generate-testray-csv/113/)
> 
> Testray CSV Link: [testray-results-59837292.csv](https://test-1-31.liferay.com/userContent/jobs/generate-testray-csv/builds/113/testray-results-59837292.csv)

No unique failures in report

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/153262

**Pull request closed without merging**
