### PR TITLE
[Test fix]Lps 164042

### PR DESCRIPTION
**Pull request by slnn**
One commit of [LPS-163054](https://issues.liferay.com/browse/LPS-163054): caused the issue: https://issues.liferay.com/browse/LPS-164042, fix the test in this pull.

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by dantewang** [comment]
@shuyangzhou @tinatian Forwarding this one as it fixes a regression caused by previous PR, and it's a simple fix.

@zhangyan0701 It seems to be the second time when a regression is found after the PR is merged. Did the test Lily fixed in this PR run in the original PR?

**Comment by dantewang** [comment]
ci:forward

**Comment by slnn** [comment]
Hi @dantewang 

I think the origin pull ran the test that was fixed in this pull, and the test is passed, master has this issue because BC's new commit https://github.com/liferay/liferay-portal/commit/338c90cebcf03961985f08b70fae7168be63a575 which is not included in the origin pull.

Lily

**Comment by zhangyan0701** [comment]
> @zhangyan0701 It seems to be the second time when a regression is found after the PR is merged. Did the test Lily fixed in this PR run in the original PR?

Like Lily said, the saml tests passed in the original pull.

**Pull request closed without merging**
