### PR TITLE
[TS] LPS-145396 - TESTS - Commit back to master

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-145396

This PR has the same changes than https://github.com/brianchandotcom/liferay-portal/pull/124402 but removing https://github.com/liferay/liferay-portal/commit/0b2fe7b41123dccc65cd3c05e3ef6374ffbe28e7 commit to avoid an OOM error.

These LPS-145396 test changes were merged in master (see https://github.com/brianchandotcom/liferay-portal/pull/124402) but they were reverted here https://github.com/brianchandotcom/liferay-portal/pull/124484 because it caused an OOM error (see [LPS-165442](https://issues.liferay.com/browse/LPS-165442) and https://github.com/brianchandotcom/liferay-portal/pull/124484#issuecomment-1277935879). The OOM error was caused by this commit https://github.com/liferay/liferay-portal/commit/0b2fe7b41123dccc65cd3c05e3ef6374ffbe28e7

After some testing, I have detected that that commit is not necessary, It was originally added in one of my initial pull requests but after several PRs and some code rewrites it is no longer necessary with the last code version.

Let me know if you have any additional question.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by jorgediaz-lr** [comment]
Hi @dantewang @tinatian 

I have rebased the PR commits to latest master to avoid a conflict in `portal-test/bnd.bnd`

**Comment by jorgediaz-lr** [comment]
I have rebased again the PR commits to latest master to avoid a conflict in `portal-test/bnd.bnd`

**Comment by tinatian** [comment]
@jorgediaz-lr Please rebase.
@vicnate5 This pull caused regressions after merged into master, any other test we should trigger to make sure it is safe this time?

Tina.

**Comment by vicnate5** [comment]
ci:test:backend-hypersonic:norebase

**Comment by vicnate5** [comment]
@tinatian The regression was OOM in the integration test batches https://issues.liferay.com/browse/LPS-165442, running them here to clear this.

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

I have rebased the PR commits to latest master to avoid the conflict in `portal-test/bnd.bnd`

**Comment by vicnate5** [comment]
ci:test:backend-hypersonic:

**Comment by vicnate5** [comment]
build is still running

**Comment by vicnate5** [comment]
@tinatian This is good to go

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125868

**Pull request closed without merging**
