### PR TITLE
[Remove Stream/Optional usage] LPS-175370 module export-import-test

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend, thanks!
https://issues.liferay.com/browse/LPS-175370
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3434

Changes in this pull:  
• Use `ListUtil.exists` to simplify Assert... method

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:export-import

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by JanisZhang** [comment]
force-pushed, I only re-arranged the commit, no code change.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:export-import

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:export-import

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
