### PR TITLE
[TS] LPS-201574 Rely on servlet request to provide the proper host name, to better support HTTP/2 (h2)

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team,

Ticket: [LPS-201574](https://liferay.atlassian.net/browse/LPS-201574)

**Context**
Currently, calling `_portal.getHost` does not provide the proper **Host name**, when Tomcat is configured to use HTTP/2.

From my investigation, the current logic to only rely on the **Host header value** to retrieve the **Host name**, was added a long time ago. 

The proposed fix would be to instead rely on the servlet request to provide the proper host name (see commit message for additional details).

**Additional Thoughts**
If we proceed with this solution, maybe we should also test on all our other supported Application Servers.

Feel free to let me know if you have any questions.
Thanks!

### CODE REVIEW

**Review by dantewang — APPROVED** [review]
@tinatian The change looks reasonable, but we need to ensure this works for all app servers.

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
Testing on all app servers

**Comment by catarineaguiar** [comment]
ci:test:environment

**Comment by catarineaguiar** [comment]
ci:test:environments

**Comment by zhangyan0701** [comment]
Manual testing passed following the steps in ticket https://liferay.atlassian.net/browse/LPS-201574.

Tested with Tomcat, JBoss EAP 7.3 and Weblogic 14c.

Here are the testing results:

- I could **ONLY** reproduce the bug on Tomcat, and the fix worked.
- I could **NOT** reproduce the bug on JBoss and Weblogic. And with the changes here, they still work as expected.

**Comment by catarineaguiar** [comment]
@ericyanLr regression on `com.liferay.portal.util.PortalImplUnitTest`:

```
    [junit] Testcase: testGetHost(com.liferay.portal.util.PortalImplUnitTest):	FAILED
    [junit] expected:<[0:0:0:0:0:0:0:1]> but was:<[[0:0:0:0:0:0:0:1]]>
    [junit] junit.framework.AssertionFailedError: expected:<[0:0:0:0:0:0:0:1]> but was:<[[0:0:0:0:0:0:0:1]]>
    [junit] 	at com.liferay.portal.util.PortalImplUnitTest._assertGetHost(PortalImplUnitTest.java:783)
    [junit] 	at com.liferay.portal.util.PortalImplUnitTest.testGetHost(PortalImplUnitTest.java:339)
    [junit] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    [junit] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    [junit] 
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-39/test-portal-acceptance-pullrequest(master)/8466/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
