### PR TITLE
[Method References 2] LPS-165445 Convert method reference to ServiceTrackerMap in module portal-search | part 2

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang ,I've modified it as we discussed.

Detial: https://github.com/liferay-core-infra/liferay-portal/pull/2242

### CODE REVIEW

**Comment by zhangyan0701** [comment]
Possible regression:
Two unit tests failed with NPE.
1. [com.liferay.portal.search.internal.sort.SortFieldBuilderImplTest](https://testray.liferay.com/home/-/testray/case_results/2042833154)
`testGetSortFieldWithSortFieldTranslator: java.lang.NullPointerException`

Full console:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-32/test-portal-acceptance-pullrequest(master)/6826/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

2. [com.liferay.portal.search.internal.buffer.IndexerRequestBufferHandlerTest](https://testray.liferay.com/home/-/testray/case_results/2042833113)
`testDeepReindexMustNotOverflow: java.lang.NullPointerException`

Full console:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-32/test-portal-acceptance-pullrequest(master)/6826/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by W2jx** [comment]
Force-Push is just to rebase and fix errors.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Pull request closed without merging**
