### PR TITLE
LPS-172424 Remove Stream and Optional for module: portal-search-slasticsearch7-impl part 2

### PR DESCRIPTION
**Pull request by julschong**
#2997 

split into 2 parts, this is part 2

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@julschong Same I mentioned in the part 1 pr. Lots of search tests are failing due to an unrelated search unit test issue so these results aren't very useful. I've notified the search team.

**Comment by catarineaguiar** [comment]
Waiting for https://github.com/brianchandotcom/liferay-portal/pull/128770 to be merged.

**Comment by catarineaguiar** [comment]
@julschong can you rebase and re-run tests suites, please?

Thanks, Cat.

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
simplified ElasticsearchShapeTranslator, clean up redundant variables

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong No regressions.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129374

**Pull request closed without merging**
