### PR TITLE
[Bug Fix] LPS-107347

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, please refer to the previous talk from https://github.com/liferay-core-infra/liferay-portal/pull/158 and slack [talk](https://liferay.slack.com/archives/CNUCYF7EW/p1641437137000100) from user management team.

LPS-87327 let **setup.wizard.add.sample.data** check available in the setup wizard page when changing the database. But the **setup.wizard.add.sample.data** may exist lonely. Please see the portal explanation:
```
    # Set this property to true to automatically add sample data to a new
    # database on startup. This will happen even if the Setup Wizard is
    # disabled.
    setup.wizard.add.sample.data=false
```

At this pr, I keep updating the default admin user logic in SetupWizardSampleDataUtil and extract resetPassword logic from SetupWizardSampleDataUtil to SetupWizardUtil.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by tinatian** [comment]
@yuhai Please slack me when you are up, I need to have a talk with you about this.

Thanks.
Tina.

**Comment by tinatian** [comment]
Talked with @yuhai, please resend if needed.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
