### PR TITLE
[Rename classes in module: dynamic-data-mapping]Lps 167105

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-167105

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
Hi @dantewang 

The SF tests failed at this class `AddSalesforceConnectorPortalInstanceLifecycleListener`, but my changes did not include it.

I did not reproduce this issue by running ant format-source-current-branch locally.
Lily

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
Forced push to rebase master and retrigger ci tests

**Comment by dantewang** [comment]
@slnn Let's do this, if the classes are deprecated and there's already no usage to them, remove them directly using another PR. Please resend, thank you.

**Comment by dantewang** [comment]
@slnn When you resend, could you also remove the deprecated ones in https://github.com/liferay-core-infra/liferay-portal/pull/2364? They seems to be all belong to DDM.

**Comment by slnn** [comment]
Remove all these deprecated registry-like classes for DDM in https://github.com/liferay-core-infra/liferay-portal/pull/2380, also include these deprecated classes in https://github.com/liferay-core-infra/liferay-portal/pull/2364.

I will resend the rename changes in LPS-167105 later as potential semantic version conflicts

**Comment by slnn** [comment]
Resend in https://github.com/liferay-core-infra/liferay-portal/pull/2416 since this one https://github.com/liferay-core-infra/liferay-portal/pull/2380 has been merged

**Pull request closed without merging**
