### PR TITLE
[Bug Fix] LPS-151508

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the issue was caused by upgrading Hibernate.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
ci:test:environments:norebase

**Comment by vicnate5** [comment]
ci:test:relevant:norebase

**Comment by vicnate5** [comment]
ci:test:upgrade:norebase

**Comment by vicnate5** [comment]
ci:test:backend:norebase

**Comment by tinatian** [comment]
@yuhai Why hibernate 3 is not using SQLServer2008Dialect? No matter which hibernate version we are using, the SQL Server installed on ci should be same, they should finally fall into the same SQLServer Dialect as the SQL Server version is same.

Tina.

**Comment by yuhai** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
@kyle-miho Can you check this one?

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina

**Comment by tinatian** [comment]
@catarineaguiar No need to scan. The fix is in wrong direction.

Tina.

**Comment by tinatian** [comment]
@yuhai The behavior is right, please fix this issue in ViewCountEntryLocalServiceTest, please create two separate threads to run incrementViewCount rather than in current thread and a separate thread.

I am going to close this pull, please resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
