### PR TITLE
[Replace Non-Blocking Usage] LPS-199560 

### PR DESCRIPTION
**Pull request by JanisZhang**
previous:https://github.com/liferay-core-infra/liferay-portal/pull/5839
https://liferay.atlassian.net/browse/LPS-199560

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:clustering

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
@JanisZhang This commit https://github.com/liferay-core-infra/liferay-portal/pull/5842/commits/7133e170fd6e24369d2ba403c51745f5f5987391 creates a major version bump at my local due to removal of a public constant. If you want to remove, make sure to document it.

**Pull request closed without merging**
