### PR TITLE
LPS-143634 Avoid using SanitizerUtil, CommonPermissionUtil, GroupPermissionUtil directly in modules

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,

Main Task: [LPS-143403](https://issues.liferay.com/browse/LPS-143403)
Sub Task 7: [LPS-143634](https://issues.liferay.com/browse/LPS-143634)
Removes SanitizerUtil, CommonPermissionUtil, GroupPermissionUtil from modules components

Note: from sub task 6 and onwards, tasks no longer depend on previous tasks.

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
