### PR TITLE
[Bug fix] LPS-161433 Portlet TCK failure caused by removing deprecated methods

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:tck

**Comment by dantewang** [comment]
cc @jeffwu0724

**Comment by dantewang** [comment]
@vicnate5 Could you please review the test results when they finish? Thanks!

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:tck

**Comment by tinatian** [comment]
@dantewang Code looks good to me, wait for QA to scan test result.

Tina

**Comment by vicnate5** [comment]
@catarineaguiar for the TCK results, can you check for which tests failed in the logs? You can search for the string `Failed tests:`

**Comment by catarineaguiar** [comment]
only this one failed:

```
 [exec] test[V2EnvironmentTests_PortletContext_ApiRender_getMimeType4](javax.portlet.tck.driver.TCKLiferayTestDriver)  Time elapsed: 0.003 sec  <<< FAILURE!
     [exec] java.lang.AssertionError: Test case V2EnvironmentTests_PortletContext_ApiRender_getMimeType4: Details: Method getMimeType(String): Returns null if the MIME type cannot be determined. Failed because MIME type is not null but application/octet-stream
     [exec] 	at org.junit.Assert.fail(Assert.java:88)
     [exec] 	at org.junit.Assert.assertTrue(Assert.java:41)
     [exec] 	at javax.portlet.tck.driver.TCKTestDriver.checkResults(TCKTestDriver.java:302)
     [exec] 	at javax.portlet.tck.driver.TCKLiferayTestDriver.test(TCKLiferayTestDriver.java:169)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-30/test-portal-acceptance-pullrequest(master)/4406/tck-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
@vicnate5 It seems the `getMimeType4` error is not related to the removal of deprecated methods, but related to LPS-147179. Could you try to look into the history of this failure? If it's caused by LPS-147179, could you create a separate ticket, link it to LPS-147179, and assign it to me? Thanks!

@tinatian I think if the leftover failure is caused by LPS-147179, we should send this PR up and deal with that in a different ticket.

**Comment by vicnate5** [comment]
@catarineaguiar Can you make a new ticket for the remaining issue as explained above?

**Comment by catarineaguiar** [comment]
@dantewang FYI https://issues.liferay.com/browse/LPS-161990

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122525

**Pull request closed without merging**
