### PR TITLE
LPS-143632 Remove LanguageUtil usages in portal module

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
Could you please help me review this test result?
Thank you!

**Comment by catarineaguiar** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
Re-running CI because any test ran.

**Pull request closed without merging**
