### PR TITLE
LPS-199486 Merge OrganizationMembershipPolicyFactoryUtil into OrganizationMembershipPolicyUtil

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://liferay.atlassian.net/browse/LPS-199486
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/6/23 8:26am

**Comment by catarineaguiar** [comment]
no regressions found. SF issue is not related

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/9/23 9:26am

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/13/23 8:04am

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/14/23 8:37am

**Comment by tinatian** [comment]
@jeffwu0724 
The MembershiPolicy is a framework added by https://liferay.atlassian.net/browse/LPSA-65999, here you only change orgnaization, there are role, site and user MembershiPolicy. In our code base, there are only some dummy impls of those MembershiPolicy expect SiteMembershipPolicy. Please check with WCM team if this MembershiPolicy framework is still using by customers first, then we need to find a general solution to all of the MembershiPolicy.

Also please do not use OrganizationMembershipPolicyUtil in modules, reference OrganizationMembershipPolicy directly.

Thanks.
Tina

**Pull request closed without merging**
