### PR TITLE
[Spring Beans] LPS-200485 Move class ZipReaderFactoryImpl and ZipWriterFactoryImpl into module

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(11/15 10:19)

**Comment by W2jx** [comment]
no conflicts(11/17 8:18)

**Comment by W2jx** [comment]
no conflicts(11/20 13:57)

**Comment by W2jx** [comment]
no conflicts(11/21 15:06)

**Comment by W2jx** [comment]
no conflicts(11/22 15:05)

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(11/27 9:10)

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results of this PR? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
