### PR TITLE
LPS-150671 Cannot finish setup wizard

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by tinatian** [comment]
@rafaprax What is the root cause of this issue?

**Comment by vicnate5** [comment]
@rafaprax I did not find any regressions here and the setup wizard tests are passing.

@tinatian This is a blocker for 7.4

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
FYI @shuyangzhou

**Pull request closed without merging**
