### PR TITLE
[Component with its own class name as service type] LPS-196947 Refactor components from echo modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-196947

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:echo

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found from the automation tests. But the SF failure should be related.
```
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: /opt/dev/projects/github/liferay-portal/modules/apps/fragment/fragment-web/src/main/resources/META-INF/resources/init.jsp expected:<...opyrightText: (c) 20[00] Liferay, Inc. https...> but was:<...opyrightText: (c) 20[23] Liferay, Inc. https...>
```

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
In the last push, I just fixed this sf problem: https://github.com/liferay-core-infra/liferay-portal/compare/cf65e96432552201be38ae830b9ff65f3ca4d32f..f3ae7774fe3e2fa2e71dc4b15760f51f566c93ee

**Comment by rafaprax** [comment]
ci:forward:force

/cc @dantewang @tinatian

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
