### PR TITLE
[Remove Stream/Optional usage] LPS-175075 modules: data-engine-rest-impl, configuration-admin-web

### PR DESCRIPTION
**Pull request by JanisZhang**
resend fixed regression. Thanks!
previous: https://github.com/liferay-core-infra/liferay-portal/pull/3750
https://issues.liferay.com/browse/LPS-175075

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:data-engine

**Comment by JanisZhang** [comment]
ci:test:usm

**Comment by Kvale1733** [comment]
@JanisZhang No regressions.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131386

**Pull request closed without merging**
