### PR TITLE
[Static method reference] LPS-181106 layout-taglib

### PR DESCRIPTION
**Pull request by JanisZhang**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@JanisZhang There is no impl of LayoutClassedModelUsageRecorder, the only usage was removed by https://issues.liferay.com/browse/LPS-174322, please check with the echo team if we can remove it.

**Comment by JanisZhang** [comment]
Hi @tinatian ,
I have checked with the echo team, LayoutClassedModelUsageRecorder can, and should, be removed.
brianchandotcom#134458 has been forwarded to Brian by the echo team.
thanks! cc @dantewang

**Pull request closed without merging**
