### PR TITLE
LPS-154695 Disable petra-doulos from build

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine, Could you please help me scan the test result?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong sorry the delay. No regressions found.

**Comment by julschong** [comment]
@tinatian Hi Tina,
could you please help me review this pull?
Thank you!

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
