### PR TITLE
[Components with more than 1 service] LPS-175886 Refactor DTO Converter components with more than 1 service type from Analytics Cloud

### PR DESCRIPTION
**Pull request by MrJohn1911**
Related pulls: https://github.com/liferay-core-infra/liferay-portal/pull/3636, https://github.com/liferay-core-infra/liferay-portal/pull/3631

Those pulls had no regressions found, so I think that this one is good to go, because I just reorganized the commits.

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
Hey @tinatian, this pr is ready for your review. Thx

**Comment by zhangyan0701** [comment]
No regressions found.

**Pull request closed without merging**
