### PR TITLE
[JDK21] LPD-19640 Allow SecurityManager usage in Talend

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian I created a new ticket other than LPD-6113 because the test case that LPD-6113 refers to has already been removed.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:jdk21

**Comment by dantewang** [comment]
ci:help

**Comment by tinatian** [comment]
ci:report:2546598349

**Comment by tinatian** [comment]
ci:report:2546694712

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6728

**Pull request closed without merging**
