### PR TITLE
[Remove Spring extender usages] LPS-159405

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang

### CODE REVIEW

**Comment by yuhai** [comment]
@zhangyan0701, please scan the test result after ci test finished. Thanks.

**Review by dantewang — APPROVED** [review]
Code looks good, wait for QA scan.

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@yuhai @dantewang is it possible to fix the removed reference issue before you replacing spring with ds?

**Comment by dantewang** [comment]
> @yuhai @dantewang is it possible to fix the removed reference issue before you replacing spring with ds?

It's possible, but hard.

Circular reference is legal in Spring, so to reveal the issue, we must first turn the module to use DS to know whether there is such issue and which classes have such issue. Then we fix compile, and then fix circular ref dependencies. We need to do this first because it's pretty hard to find out such issues by eyes.

Then we go back to the state before converting to DS, do the fix according the info we gathered from the previous step.

And it's more weird if we fix circular refs when they are legal.

**Comment by dantewang** [comment]
@tinatian Forgot to mention you in https://github.com/liferay-core-infra/liferay-portal/pull/1245#issuecomment-1204666397

Also, I think the more service classes a module has, the harder it would be for us to fix these first. `commerce-product-service` has a lot of service classes, it's already hard with the current procedure.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/1292

**Pull request closed without merging**
