### PR TITLE
LPS-149460 Move petra-model-adapter to core/petra

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,

Main Task: [LPS-147928](https://issues.liferay.com/browse/LPS-147928)
Sub Task: [LPS-149460](https://issues.liferay.com/browse/LPS-149460)

Note: 
- Moved ProxyUtil to petra-reflect
- Remove kernel deps from ModelAdapterUtil
- Move ModelAdapterUtil and rename to AdapterUtil in core/petra/petra-util

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
pushed to correct commit message typo

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
pushed again with rewritten unit test with A B interfaces

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
rebased and fixed semantic versioning

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by kyle-miho** [comment]
@julschong sf issue, other tests are still running too waiting for those

**Comment by kyle-miho** [comment]
@julschong could you recheck some of the usages of ProxyUtil? Some test classes in integration tests are failing to import the class now since you moved the package, for example
    [exec] > Task :util:portal-tools-service-builder-test-test:compileTestIntegrationJava
     [exec] /opt/dev/projects/github/liferay-portal/modules/util/portal-tools-service-builder-test-test/src/testIntegration/java/com/liferay/portal/tools/service/builder/test/PersistenceNestedSetsTreeManagerTest.java:80: error: cannot find symbol
     [exec] 			ProxyUtil.newProxyInstance(
     [exec] 			^
     [exec]   symbol:   variable ProxyUtil
     [exec]   location: class PersistenceNestedSetsTreeManagerTest
     [exec] 1 error
     [exec] 
     [exec] > Task :util:portal-tools-service-builder-test-test:compileTestIntegrationJava FAILED

**Comment by kyle-miho** [comment]
Should happen in these test classes at minimum, possibly more
apps:portal:portal-aop-test
apps:portal-security:portal-security-auth-test
apps:portlet:portlet-test

**Comment by julschong** [comment]
due to innerClass in ModelAdapterUtil being tied to the logic of ModelWrapper, we cannot separate and put in petra anymore.
Change of plan: move to apps/portal-utilities/model-adaptor-util

**Pull request closed without merging**
