### PR TITLE
LPD-29780 Schedule/unschedule for SINGLE_NODE_MEMORY_CLUSTERED and SINGLE_NODE_PERSISTED if the node is master

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPD-29780

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
FYI @tinatian @JerryAdrianoo

**Comment by JerryAdrianoo** [comment]
Hey @tinatian it seems that the regression has been fixed. See the results below.
  
  | Branch | Open count of Prepared Statement | Count of Prepared Statement Query | Open Count of SQL |
  |--------|--------|--------|--------|
  | Master 752cd7 | 64 | 96 | 1050 |
  | PR + 752cd7| 64 | 96 | 1050 |
  
  For more details, see this [spreadsheet](https://docs.google.com/spreadsheets/d/1z5D-BYaKMQZgtw6xQYlfmAY8Xo1wODH0qL0Yk0rkcc8/edit?gid=915596619#gid=915596619) with the results.

**Comment by tinatian** [comment]
@ccorreagg Thanks for the pull! Regression is fixed, good to go!

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
