### PR TITLE
[Components with more than 1 service] LPS-183224 Refactor PortletProvider implementations part 2

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-183224

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-core-infra/liferay-portal/pull/4842

**Pull request closed without merging**
