### PR TITLE
[Remove Immediate] LPS-192723 Remove immediate property from BundleBlacklistManagerImpl

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://liferay.atlassian.net/browse/LPS-192723

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @shuyangzhou,

I tested the upgrade change https://github.com/liferay-core-infra/liferay-portal/pull/5677/commits/6d2b225383a40088b1f1fd4c84f495f4e74c7a69#diff-2dcc99720e17d5f58e397e2a435f245f1f1c7cb86574285567ca2808ecba560aR26-R31 against an old db that contained the old symbolicName and against a fresh db and everything worked as expected in these tests.

Thanks

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141595

**Pull request closed without merging**
