### PR TITLE
[Spring Beans] LPS-200563 Merge UserGroupMembershipPolicyFactoryImpl into Util and move to portal-impl.

### PR DESCRIPTION
**Pull request by JanisZhang**
https://liferay.atlassian.net/browse/LPS-200563

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
SF failure should be not related.

**Comment by Kvale1733** [comment]
@JanisZhang Regressions found

`1) Several security integration tests failed to run due to the following compile issue
```
test/src/testIntegration/java/com/liferay/portal/security/membership/policy/usergroup/test/UserGroupMembershipPolicyBasicTest.java:9: error: cannot find symbol
     [exec] import com.liferay.portal.kernel.security.membershippolicy.UserGroupMembershipPolicyUtil;
     [exec]                                                           ^
     [exec]   symbol:   class UserGroupMembershipPolicyUtil
     [exec]   location: package com.liferay.portal.kernel.security.membershippolicy
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-security/portal-security-membership-policy-test/src/testIntegration/java/com/liferay/portal/security/membership/policy/usergroup/test/UserGroupMembershipPolicyBasicTest.java:38: error: cannot find symbol
     [exec] 			UserGroupMembershipPolicyUtil.isMembershipAllowed(
     [exec] 			^
     [exec]   symbol:   variable UserGroupMembershipPolicyUtil
     [exec]   location: class com.liferay.portal.security.membership.policy.usergroup.test.UserGroupMembershipPolicyBasicTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-security/portal-security-membership-policy-test/src/testIntegration/java/com/liferay/portal/security/membership/policy/usergroup/test/UserGroupMembershipPolicyBasicTest.java:48: error: cannot find symbol
     [exec] 			UserGroupMembershipPolicyUtil.isMembershipAllowed(
     [exec] 			^
     [exec]   symbol:   variable UserGroupMembershipPolicyUtil
     [exec]   location: class com.liferay.portal.security.membership.policy.usergroup.test.UserGroupMembershipPolicyBasicTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-security/portal-security-membership-policy-test/src/testIntegration/java/com/liferay/portal/security/membership/policy/usergroup/test/UserGroupMembershipPolicyBasicTest.java:58: error: cannot find symbol
     [exec] 			UserGroupMembershipPolicyUtil.isMembershipRequired(
     [exec] 			^
     [exec]   symbol:   variable UserGroupMembershipPolicyUtil
     [exec]   location: class com.liferay.portal.security.membership.policy.usergroup.test.UserGroupMembershipPolicyBasicTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-security/portal-security-membership-policy-test/src/testIntegration/java/com/liferay/portal/security/membership/policy/usergroup/test/UserGroupMembershipPolicyBasicTest.java:68: error: cannot find symbol
     [exec] 			UserGroupMembershipPolicyUtil.isMembershipRequired(
     [exec] 			^
     [exec]   symbol:   variable UserGroupMembershipPolicyUtil
     [exec]   location: class com.liferay.portal.security.membership.policy.usergroup.test.UserGroupMembershipPolicyBasicTest
     [exec] 5 errors
     [exec] > Task :apps:portal-security:portal-security-auto-login-test:compileTestIntegrationJava
     [exec] > Task :apps:portal-security:portal-security-ldap-api:javadoc
 ```
 [Log](https://testray.liferay.com/reports/production/logs/2023-11/test-1-31/test-portal-acceptance-pullrequest(master)/9793/modules-compile-jdk8/0/3/jenkins-console.txt.gz?authuser=0)
 
 2) Several upgrade (6.2, 6.1, 7.2) faile
 Steps to reproduce:
 1. Import this 7.0.10.6 db: https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.0.10.6/data-archive/data-archive-portal-mysql.zip
 2. Upgrade the db with the upgrade tool
 
 Results: Upgrade fails with 
 ```
  [java] 2023-11-01 10:32:53.564 INFO  [main][UpgradeProcess:118] Upgrading com.liferay.portal.kernel.upgrade.ViewCountUpgradeProcess
     [java] 2023-11-01 10:32:53.567 INFO  [main][UpgradeProcess:136] Failed upgrade process com.liferay.portal.kernel.upgrade.ViewCountUpgradeProcess in 2 ms
     [java] 2023-11-01 10:32:53.570 ERROR [main][UpgradeExecutor:333] Failed upgrade process for module com.liferay.document.library.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Table 'lportal.ViewCountEntry' doesn't exist
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:127) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.upgrade.internal.registry.UpgradeStepRegistry.lambda$register$1(UpgradeStepRegistry.java:92) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor._executeUpgradeInfos(UpgradeExecutor.java:202) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.executeUpgradeInfos(UpgradeExecutor.java:124) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.execute(UpgradeExecutor.java:85) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeExecutor.java:330) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeExecutor.java:290) ~[?:
    ```
    [Log](https://testray.liferay.com/reports/production/logs/2023-11/test-1-31/test-portal-acceptance-pullrequest(master)/9793/functional-upgrade-tomcat90-mysql57-jdk8/0/6/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
Ignore the second issue. That looks like it's on master too.

**Pull request closed without merging**
