### PR TITLE
[Components with more than 1 service] LPS-193055 Reactor JSBundleConfigServlet component

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:frontend

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:frontend

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by tinatian** [comment]
See   https://github.com/brianchandotcom/liferay-portal/pull/139223

**Pull request closed without merging**
