### PR TITLE
LPS-158022 Avoid recreating workflow indexes on startup if they already exist

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:workflow-metrics

**Comment by rafaprax** [comment]
Hey @catarineaguiar, Can you please help scan these test results? Thx

**Comment by catarineaguiar** [comment]
@rafaprax no regressions found.

**Comment by rafaprax** [comment]
Hey all, I just reword a commit message without code changes.

**Comment by rafaprax** [comment]
Hey @shuyangzhou, this pr is ready for your review. Thx

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121712

**Pull request closed without merging**
