### PR TITLE
[Remove Blocking usages]LPS-188270 portal-kernel | ConfigurationProviderUtil

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5412

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found. Let's wait for stable results

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:test:sf

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
no regressions found. SF issue is not related

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140198

**Pull request closed without merging**
