### PR TITLE
LPS-193711 Avoid loading ArgumentsResolver services during shutdown

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@tinatian regression found:

```
     [exec] com.liferay.portal.cache.internal.dao.orm.EntityCacheImplTest > testNotifyPortalCacheRemovedPortalCacheName FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.portal.cache.internal.dao.orm.FinderCacheImpl.removeCacheByEntityCache(FinderCacheImpl.java:384)
     [exec]         at com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl._notify(EntityCacheImpl.java:339)
     [exec]         at com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl._notifyFinderCache(EntityCacheImpl.java:356)
     [exec]         at com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl.notifyPortalCacheRemoved(EntityCacheImpl.java:217)
     [exec]         at com.liferay.portal.cache.internal.dao.orm.EntityCacheImplTest.testNotifyPortalCacheRemovedPortalCacheName(EntityCacheImplTest.java:129)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-08/test-1-30/test-portal-acceptance-pullrequest(master)/7522/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5344

**Pull request closed without merging**
