### PR TITLE
LPS-153806

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by vicnate5** [comment]
Running specific testing https://github.com/vicnate5/liferay-portal/pull/2046

**Comment by tinatian** [comment]
@vicnate5 Is this pull good to go?

Tina

**Comment by vicnate5** [comment]
@tinatian This is good to go.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/118108

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
