### PR TITLE
[Round 3 Method Reference Static]Lps 181271

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-181271

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:data-engine

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
@slnn Actually, after your change, the method `internalDeserialize` is no longer needed, please inline it into `deserialize`. So you don't need to cast the service to `DDMFormJSONDeserializer`.

On the other hand, you need to add a filter for the `Snapshot` to get the `DDMFormDeserializer` for json, otherwise it's possible to get the one for xsd.

**Comment by slnn** [comment]
Done, please see https://github.com/liferay-core-infra/liferay-portal/pull/4283

> @slnn Actually, after your change, the method `internalDeserialize` is no longer needed, please inline it into `deserialize`. So you don't need to cast the service to `DDMFormJSONDeserializer`.
> 
> On the other hand, you need to add a filter for the `Snapshot` to get the `DDMFormDeserializer` for json, otherwise it's possible to get the one for xsd.

**Pull request closed without merging**
