### PR TITLE
[Remove Stream and Optional usage:content-dashboard-document-library-impl]Lps 179646 3 31

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-179646

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:echo

**Comment by dantewang** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
@slnn No regressions.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132762

**Pull request closed without merging**
