### PR TITLE
LPS-165108 Remove immediate from Data Engine modules

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@rafaprax regressions found:

```
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.data.engine.rest.api-29.0.0.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.data.engine.rest.api/28.0.0/bd96b4d7ae6cadf3ddf4c07c6f8ab9440dc8d05/com.liferay.data.engine.rest.api-28.0.0.jar
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-38/test-portal-acceptance-pullrequest(master)/4277/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

Functional tests failed trying to add a new structure:
e.g. `WebContentSmokeTests#ViewAndDeleteContentWithTitleAndAllFields`, `LocalizedSimpleFieldsetsStructure#TranslateStructureWithFieldsetAndNested`, `ImageField#UploadImageFromDocumentsAndMedia`, `DEBooleanField#HelpTextCanBeAdded`, `DESingleSelectionField#ViewSingleSelectionFieldDetails`, `DEDateField#ViewDateFieldDetails`
```
 [exec] 2022-10-14 19:09:51.711 ERROR [http-nio-8080-exec-7][PortletRequestDispatcherImpl:304] Unable to dispatch request: java.lang.NullPointerException
     [exec] 2022-10-14 19:09:51.714 ERROR [http-nio-8080-exec-7][PortletServlet:117] null
     [exec] javax.portlet.PortletException: javax.servlet.ServletException: java.lang.NullPointerException
     [exec] 	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.dispatch(PortletRequestDispatcherImpl.java:307) ~[portal-impl.jar:?]
     [exec] 	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:123) ~[portal-impl.jar:?]
     [exec] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:620) ~[portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:636) ~[portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:506) ~[portal-kernel.jar:?]
     [exec] 	at com.liferay.journal.web.internal.portlet.JournalPortlet.doDispatch(JournalPortlet.java:276) ~[bundleFile:?]
     [exec] 	at javax.portlet.GenericPortlet.render(GenericPortlet.java:291) ~[portlet.jar:3.0.1]
     [exec] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:309) ~[portal-kernel.jar:?]
     [exec] 	at com.liferay.journal.web.internal.portlet.JournalPortlet.render(JournalPortlet.java:189) ~[bundleFile:?]
     [exec] 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:127) ~[portal-impl.jar:?]
     [exec] 	at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:58) ~[portal-impl.jar:?]
     [exec] 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124) ~[portal-impl.jar:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-38/test-portal-acceptance-pullrequest(master)/4277/functional-tomcat90-mysql57-jdk8/0/6/jenkins-console.txt.gz?authuser=0)

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:test:data-engine

**Comment by catarineaguiar** [comment]
@rafaprax no regressions found.

**Comment by rafaprax** [comment]
Hey @shuyangzhou, this pr is ready for your review. Thx

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/124744

**Pull request closed without merging**
