### PR TITLE
[OrderByComparator] LPD-26342 Clean up and Apply Singleton in module Segments and Sharing

### PR DESCRIPTION
**Pull request by Valmir-unicap**
- Ticket: https://liferay.atlassian.net/browse/LPD-26342
- Correction of: https://github.com/liferay-core-infra/liferay-portal/pull/7012

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Review by dantewang — CHANGES_REQUESTED** [review]
@Valmir-unicap Code change looks good to me, but could you re-arrange your commits:
1. follow the same order: remove unused constructor -> add and apply singleton -> SF
2. do not say "prepare for next" in "add and apply singleton" and "SF" commits

cc @tinatian

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:echo-analytics-cloud

**Comment by dantewang** [comment]
ci:test:sharing

**Comment by dantewang** [comment]
ci:forward

cc @tinatian

**Pull request closed without merging**
