### PR TITLE
[Component with its own class name as service type ] LPS-193655 Refactor ResourceBundleLoaderProvider componet

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**
This pr is linked to [LPS-193655](https://github.com/liferay-core-infra/liferay-portal/pull/5324)

### CODE REVIEW

**Review by rafaprax — APPROVED** [review]

**Review by rafaprax — APPROVED** [review]

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
No need to rerun relevant. The failures I saw are actually an unrelated blocker. I'll analyse the current results.

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
@GabrielHenriquedev Regression found. I was able to reproduce locally by running the test. This was present in the previous PR to by the way. Seems it still passes but throws an error afterwards
com.liferay.message.boards.search.test.MBCategoryIndexerTest
```
exec] com.liferay.message.boards.search.test.MBCategoryIndexerTest > testReindexGroupContainingMBCategories PASSED
     [exec] 2023-08-17 21:48:50.074 ERROR [com.liferay.message.boards.test-executor-thread][GroupLocalServiceImpl:4156] Unable to delete data for portlet null in group 40657
     [exec] com.liferay.exportimport.kernel.lar.PortletDataException: No Company exists with the primary key 38003
     [exec] 	at com.liferay.exportimport.kernel.lar.BasePortletDataHandler._handleException(BasePortletDataHandler.java:801) ~[portal-kernel.jar:?]
     [exec] 	at com.liferay.exportimport.kernel.lar.BasePortletDataHandler.deleteData(BasePortletDataHandler.java:91) ~[portal-kernel.jar:?]
     [exec] 	at com.liferay.message.boards.web.internal.exportimport.data.handler.MBPortletDataHandler.deleteData(MBPortletDataHandler.java:47) ~[?:?]
     [exec] 	at com.liferay.portal.service.impl.GroupLocalServiceImpl.deletePortletData(GroupLocalServiceImpl.java:4151) [port

```
[Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-34/test-portal-acceptance-pullrequest(master)/4601/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Comment by GabrielHenriquedev** [comment]
@Kvale1733 Hello kevin, I believe that this regression is not linked to my pr, my modification should not affect this test, I tested it on the master and found the same error, can you `re-evaluate? Log master
`2023-08-23 16:05:31.680 ERROR [com.liferay.message.boards.test-executor-thread][GroupLocalServiceImpl:4150] Unable to delete data for portlet null in group 36552
com.liferay.exportimport.kernel.lar.PortletDataException: No Company exists with the primary key 33741
	at com.liferay.exportimport.kernel.lar.BasePortletDataHandler._handleException(BasePortletDataHandler.java:801) ~[portal-kernel.jar:?]
	at com.liferay.exportimport.kernel.lar.BasePortletDataHandler.deleteData(BasePortletDataHandler.java:91) ~[portal-kernel.jar:?]
	at com.liferay.message.boards.web.internal.exportimport.data.handler.MBPortletDataHandler.deleteData(MBPortletDataHandler.java:47) ~[?:?]
	at com.liferay.portal.service.impl.GroupLocalServiceImpl.deletePortletData(GroupLocalServiceImpl.java:4145) [portal-impl.jar:?]
	at com.liferay.portal.service.impl.GroupLocalServiceImpl.deleteGroup(GroupLocalServiceImpl.java:1054) [portal-impl.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]`

**Comment by catarineaguiar** [comment]
ci:test:message-boards

**Comment by catarineaguiar** [comment]
@GabrielHenriquedev no regressions were found.

**Comment by shuyangzhou** [comment]
ci:forward:force

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139855

**Pull request closed without merging**
