### PR TITLE
[Static reference] LPS-166968 Replace field reference with snapshot in class DataLayoutTaglibUtil | part 1

### PR DESCRIPTION
**Pull request by W2jx**
Because there are too many variables in class DataLayoutTaglibUtil, I simplified it first and will replace the remaining variables in the following pr.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4272

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
only do semver, no need to rerun test

**Comment by W2jx** [comment]
no conflicts(5/8 15:34)

**Comment by dantewang** [comment]
As we talked, please resend, thanks!

**Pull request closed without merging**
