### PR TITLE
LRQA-79872

### PR DESCRIPTION
**Pull request by yuhai**
@Kvale1733, please check if it worked.

### CODE REVIEW

**Comment by dantewang** [comment]
@yuhai Will a portlet go through bean-portlet deployment as long as the war file contains a `beans.xml`? We want it to go through bean-portlet deployment process, not just through `PortletLocalServiceImpl`. Or, can this war work if you remove `beans.xml`? If so, it's not right.

**Review by dantewang — CHANGES_REQUESTED** [review]
/

**Comment by yuhai** [comment]
@dantewang, 

> Will a portlet go through bean-portlet deployment as long as the war file contains a beans.xml? We want it to go through bean-portlet deployment process, not just through PortletLocalServiceImpl.
> 
> Or, let's say, does bean-portlet-cdi-extension actually do anything when deploying this portlet?

Yes, when including beans.xml. It will go through `CDIBeanPortletExtension#step1BeforeBeanDiscovery..step4ApplicationScopedInitializedAsync` during deployment. If excluding beans.xml. It will go through PortletLocalServiceImpl#initWAR()

The sample portlet was created by referring to the attachment portlet of LPS-148969.

When deploy the pr war, the below log will output:
```
2023-09-08 08:09:29.596 INFO  [com.liferay.portal.kernel.deploy.auto.AutoDeployScanner][AutoDeployDir:212] Processing sample-bean-portlet-1.0.0.war
2023-09-08 08:09:39.436 INFO  [fileinstall-directory-watcher][BaseAutoDeployListener:34] Copying portlets for E:\master-bundles\tomcat-9.0.75\temp\20230908080939415NZVTTZVQ\sample-bean-portlet.war
2023-09-08 08:09:39.533 INFO  [fileinstall-directory-watcher][BaseAutoDeployListener:41] Portlets for E:\master-bundles\tomcat-9.0.75\temp\20230908080939415NZVTTZVQ\sample-bean-portlet.war copied successfully
2023-09-08 08:09:40.307 INFO  [fileinstall-directory-watcher][BundleStartStopLogger:68] STARTED sample-bean-portlet_1.0.0 [1480]
2023-09-08 08:09:40.369 INFO  [fileinstall-directory-watcher][Version:148] WELD-000900: 3.0.5 (Final)
2023-09-08 08:09:40.436 INFO  [fileinstall-directory-watcher][Bootstrap:225] WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
2023-09-08 08:09:40.469 WARN  [fileinstall-directory-watcher][Interceptor:46] WELD-001700: Interceptor annotation class javax.ejb.PostActivate not found, interception based on it is not enabled
2023-09-08 08:09:40.470 WARN  [fileinstall-directory-watcher][Interceptor:46] WELD-001700: Interceptor annotation class javax.ejb.PrePassivate not found, interception based on it is not enabled
2023-09-08 08:09:40.535 INFO  [fileinstall-directory-watcher][Event:86] WELD-000411: Observer method [BackedAnnotatedMethod] org.apache.aries.cdi.container.internal.container.DiscoveryExtension.processAnnotatedType(@Observes ProcessAnnotatedType<X>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2023-09-08 08:09:40.793 INFO  [Aries CCR Thread][Bootstrap:225] WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
2023-09-08 08:09:40.810 INFO  [Aries CCR Thread][Event:86] WELD-000411: Observer method [BackedAnnotatedMethod] public com.liferay.bean.portlet.cdi.extension.internal.CDIBeanPortletExtension.step2ProcessAnnotatedType(@Observes ProcessAnnotatedType<T>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2023-09-08 08:09:40.858 WARN  [Aries CCR Thread][Bootstrap:118] WELD-000146: BeforeBeanDiscovery.addAnnotatedType(AnnotatedType<?>) used for class com.sun.faces.flow.FlowDiscoveryCDIHelper is deprecated from CDI 1.1!
2023-09-08 08:09:40.870 WARN  [Aries CCR Thread][CDIBeanPortletExtension:202] Automatically added @ApplicationScoped to class com.liferay.bean.portlet.cdi.extension.sample.test.portlet.HelloWorldFacesPortlet
2023-09-08 08:09:41.091 INFO  [weld-worker-7][BeanPortletRegistrarUtil:290] Registered 1 bean portlets and 0 bean filters for sample-bean-portlet
```

**Comment by dantewang** [comment]
@yuhai OK then, LGTM.

**Review by dantewang — APPROVED** [review]

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
