### PR TITLE
[Method References] LPS-162587 Convert method references to field references in modules mentions-service、mentions-web、layout-admin-web

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I convert method references to field references in modules mentions-service、mentions-web、layout-admin-web.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by zhangyan0701** [comment]
Relevant tests passed.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@shuyangzhou @tinatian Forwarding this one as all tests passed review and changes are direct replacements.

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
