### PR TITLE
[TS]LPS-134550

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:2533685744

**Comment by tinatian** [comment]
Retrigger test to verify unique

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:2533980211

**Comment by tinatian** [comment]
ci:report:2533685744

**Comment by tinatian** [comment]
The unique failures reported in two runs are not consistent, thus I think the unique failures are flaky.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/146908

**Pull request closed without merging**
