### PR TITLE
[Bug Fix] [Blocker] LPS-164225 

### PR DESCRIPTION
**Pull request by JanisZhang**
@dantewang @zhangyan0701 

https://issues.liferay.com/browse/LPS-164225

Verified OK on my side.

### CODE REVIEW

**Comment by JanisZhang** [comment]
HI @zhangyan0701 , Could you please take a look? thanks.

**Comment by catarineaguiar** [comment]
ci:help

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found

**Comment by JanisZhang** [comment]
ci:forward

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:stop

**Pull request closed without merging**
