### PR TITLE
Lps 195887 p2 9 14 1

### PR DESCRIPTION
**Pull request by shuyangzhou**
@dantewang for https://github.com/liferay-core-infra/liferay-portal/pull/5585/commits/0ad3feeca968c72257779ff770991c54e8386522#diff-b4cdc5d278408140bdf2c749724c07a28f94d472b625e34408d31d31f95f7486R191 is it only ever used by HttpServiceRuntimeOSGiCommands ? If so, check with QA to see whether we really use that command for anything, if not, just stop registering it.

### CODE REVIEW

**Comment by dantewang** [comment]
@shuyangzhou We have several components referencing the `HttpServiceRuntime` as an indicator of the Equinox Http Servlet being ready, but only that gogo shell command really calls method on it.

**Comment by shuyangzhou** [comment]
Yeah, I saw those unused references. Can they be changed to wait on something they really use? If the osgi command is not really used. I'd rather to see this weird service removed.

**Comment by dantewang** [comment]
@shuyangzhou I think they are rather depending on the "state" of Equinox being ready than really using any functionality from the referenced service. If I don't register `HttpServiceRuntime` then they can depend on the `HttpServletEndpointServlet` I registered; but for now I don't have any idea to make them *use* any of these.

**Comment by shuyangzhou** [comment]
Ok, then for now just focus to see if the osgi command can be removed. If it can, you can just register a dummy service to notify those waiters. That way when we want to sort out dependencies later, at least we will know this is only a staged "service" with no real logic.

**Comment by dantewang** [comment]
@shuyangzhou Sure, I've queried QA and support about this command.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@shuyangzhou Based on the current findings there seems no one using this command. However this command was added for providing debug information, I wonder if we should provide an alternative way for it.

**Comment by dantewang** [comment]
@shuyangzhou Please see https://github.com/liferay-core-infra/liferay-portal/pull/5589

**Comment by shuyangzhou** [comment]
Sure, if you can provide the info using a lower level API, that's also fine. My goal is mainly trying to eliminate the HttpServiceRuntime service.

**Pull request closed without merging**
