### PR TITLE
LPS-163305 Cleanup unused class and methods in portal-kernel/template

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong sf issue:

```
format-source-files:
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-kernel/src/com/liferay/portal/kernel/template/TemplateManagerUtil.java expected:<...feray.portal.kernel.[log.Log;
     [java] import com.liferay.portal.kernel.log.LogFactoryUtil;
     [java] import com.liferay.portal.kernel.module.util.SystemBundleUtil;
     [java] 
     [java] import java.util.Collections];
     [java] import java.util.M...> but was:<...feray.portal.kernel.[configuration.Filter;
     [java] import com.liferay.portal.kernel.log.Log;
     [java] import com.liferay.portal.kernel.log.LogFactoryUtil;
     [java] import com.liferay.portal.kernel.module.util.SystemBundleUtil;
     [java] import com.liferay.portal.kernel.util.PropsUtil;
     [java] import com.liferay.portal.kernel.util.Validator;
     [java] 
     [java] import java.util.Collections;
     [java] import java.util.HashSet];
     [java] import java.util.M...>
     [java] 
```

**Comment by catarineaguiar** [comment]
no other regression found.

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:stop

**Pull request closed without merging**
