### PR TITLE
[Remove Blocking usages]LPS-188902 portal-kernel | OmniadminUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
ci:test:data-integration

**Comment by zhangyan0701** [comment]
ci:test:ldap

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
