### PR TITLE
LPD-39549 fix start up warning in freemarker with java 21 

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, 

As found in https://liferay.slack.com/archives/GLCFMMZQW/p1729017280301029
with jdk 8, if we start up with freemarker 2.3.33, then we will have require-capability issue
with jdk 21, it will have warning that `Seems that the Java 9 support class (freemarker.core._Java9Impl) wasn't included in the build in portal log`
As talked, I revert the code that modify the 2.3.33 freemarker, and use `-noee` to exclude osgi-ee requirement from the modules that compileInlcude freemarker
By testing locally, both jdk 8 and java 21 can start up without error / warning
Thanks for checking

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:core-functional

**Comment by jeffwu0724** [comment]
ci:test:core-functional

**Comment by jeffwu0724** [comment]
ci:report:44996612

**Comment by jeffwu0724** [comment]
https://testray.liferay.com/#/project/35392/routines/45357/build/44996612/case-result/45008023/history -- not unique
No unique regression found

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/155362

**Pull request closed without merging**
