### PR TITLE
[Eliminate Spring Beans] LPS-200219 

### PR DESCRIPTION
**Pull request by JanisZhang**
Move class `BrowserIdCacheFileNameContributor`, `LanguageIdCacheFileNameContributor`, `MinifierTypeCacheFileNameContributor`, and `ThemeIdCacheFileNameContributor` into module portal-cache-impl. 
Thanks for checking.
https://liferay.atlassian.net/browse/LPS-200219

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:clustering

**Comment by zhangyan0701** [comment]
No regressions found.

**Pull request closed without merging**
