### PR TITLE
[Bug Fix] LPS-198162 When using Snapshot in portal-kernel, it may cause NullPointerException

### PR DESCRIPTION
**Pull request by W2jx**
Issue: https://liferay.atlassian.net/browse/LPS-198162

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5724

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:stop

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by W2jx** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/141897

**Pull request closed without merging**
