### PR TITLE
[SampleSQLBuilder]Lpd 37967

### PR DESCRIPTION
**Pull request by slnn**
Original pull:https://github.com/liferay-core-infra/liferay-portal/pull/7610

### CODE REVIEW

**Comment by slnn** [comment]
Hi @devpedrotavares 

Please check if my commits which just SF and simplify break anything, thanks!

Lily

**Comment by slnn** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
> Hi @devpedrotavares
> 
> Please check if my commits which just SF and simplify break anything, thanks!
> 
> Lily

It's all working fine. Thank you!

**Comment by tinatian** [comment]
@slnn The SF failure seems real, could you please take a look at it?

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
The forces push just SF changes, no logic changes

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
