### PR TITLE
[Method References 2] LPS-171236 Convert method reference to ServiceTrackerMap in class ItemSelectorImpl(module item-selector-web)

### PR DESCRIPTION
**Pull request by W2jx**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/2774

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
CI is having issues with SF. So this pull should be good to go.

**Comment by W2jx** [comment]
no conflicts(12/21 17:05)

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2830

**Pull request closed without merging**
