### PR TITLE
LPS-178022 Cleanup TypeFacet for optional removal

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test;search

**Comment by julschong** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4375

**Pull request closed without merging**
