### PR TITLE
[Method References 2] LPS-165167 Convert method reference to ServiceTrackerList in module portal-search-similar-results-web(dxp)

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-165167 Inline SimilarResultsContributorsHolder into SimilarResultsContributorsRegistryImpl as it's only used there, no logic change
- LPS-165167 Convert method reference to ServiceTrackerList
- LPS-165167 Add dependencies
- LPS-165167 Fix the test

### CODE REVIEW

**Comment by dantewang** [comment]
This unique failure shown in https://github.com/liferay-core-infra/liferay-portal/pull/2228#issuecomment-1293120479 shouldn't be related with my change.

**Comment by dantewang** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/125421

cc @shuyangzhou @tinatian

**Pull request closed without merging**
