### PR TITLE
[Move Expando]Lps 190836 10 10

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-190836

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:upgrade

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
This is a big one and will take more time to review; at the same time, QA please check the results and trigger any other test if needed, thanks!

**Comment by catarineaguiar** [comment]
ci:test

**Comment by Kvale1733** [comment]
ci:close

**Comment by slnn** [comment]
> Regression found. Cannot delete a virtual instance. CI does this often for cleanup so it's affecting a lot of the tests.
> 
> Steps to reproduce:
> 
> 1. Create a virtual instance (i.e. [www.able.com](http://www.able.com))
> 2. Try deleting the virtual instance
> 
> Results: If you try deleting the virtual instance via UI, you get a success message although it is not deleted. No error is thrown in the console. However, if you try deleting via JSON with
> 
> ```
> curl -X DELETE -u 'test@liferay.com:test' -H 'Content-Type: application/json' http://localhost:8080/o/headless-portal-instances/v1.0/portal-instances/www.able.com
> ```
> 
> Then you get this error. The instance is also not deleted.
> 
> ```
>  [exec]     Executing commands: curl -X DELETE -u 'test@liferay.com:test' -H 'Content-Type: application/json' http://localhost:8080/o/headless-portal-instances/v1.0/portal-instances/cloud-10-0-16-144.lax.liferay.com
>      [exec] 2023-10-11 04:44:39.636 ERROR [http-nio-8080-exec-6][ExceptionMapper:59] null
>      [exec] java.lang.ClassCastException: com.liferay.expando.model.impl.ExpandoColumnImpl cannot be cast to com.liferay.expando.kernel.model.ExpandoColumn
>      [exec] 	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.performAction(DefaultActionableDynamicQuery.java:378) ~[portal-kernel.jar:?]
>      [exec] 	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.lambda$doPerformActions$1(DefaultActionableDynamicQuery.java:292) ~[portal-kernel.jar:?]
>      [exec] 	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.doPerformActions(DefaultActionableDynamicQuery.java:310) ~[portal-kernel.jar:?]
>      [exec] 	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.performActions(DefaultActionableDynamicQuery.java:77) ~[portal-kernel.jar:?]
>      [exec] 	at com.liferay.portal.service.impl.CompanyLocalServiceImpl$DeleteExpandoColumnActionableDynamicQuery.performActions(CompanyLocalServiceImpl.java:1629) ~[portal-impl.jar:?]
>      [exec] 	at com.liferay.portal.service.impl.CompanyLocalServiceImpl.doDeleteCompany(CompanyLocalServiceImpl.java:1263) ~[portal-impl.jar:?]
>      [exec] 	at com.liferay.portal.service.impl.CompanyLocalServiceImpl.deleteCompany(CompanyLocalServiceImpl.java:379) ~[portal-impl.jar:?]
>      [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
>      [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_381]
>      [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_381]
>      [exec] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_381]
>      [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41) ~[portal-impl.jar:?]
>      [exec] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60) ~[portal-impl.jar:?]
> ```

Thank @Kvale1733 for catching this! Will fix it and resend it.

**Comment by slnn** [comment]
Please see https://github.com/liferay-core-infra/liferay-portal/pull/5802

**Pull request closed without merging**
