### PR TITLE
LPS-145575 Remove FileUtil usages in modules part 1

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
Errors thrown during portal startup:
```
[beanshell] 2022-11-18 00:37:53.471 ERROR [Portal Dependency Manager Component Executor--1][MembersPortlet:56] bundle com.liferay.contacts.web:5.0.44 (1308)[com.liferay.contacts.web.internal.portlet.MembersPortlet(10595)] : findField: Suitable but non-accessible field _file in class com.liferay.contacts.web.internal.portlet.ContactsCenterPortlet, subclass of component class com.liferay.contacts.web.internal.portlet.MembersPortlet
[beanshell] 2022-11-18 00:37:53.496 ERROR [Portal Dependency Manager Component Executor--1][MyContactsPortlet:56] bundle com.liferay.contacts.web:5.0.44 (1308)[com.liferay.contacts.web.internal.portlet.MyContactsPortlet(10596)] : findField: Suitable but non-accessible field _file in class com.liferay.contacts.web.internal.portlet.ContactsCenterPortlet, subclass of component class com.liferay.contacts.web.internal.portlet.MyContactsPortlet
[beanshell] 2022-11-18 00:37:53.532 ERROR [Portal Dependency Manager Component Executor--1][ProfilePortlet:56] bundle com.liferay.contacts.web:5.0.44 (1308)[com.liferay.contacts.web.internal.portlet.ProfilePortlet(10597)] : findField: Suitable but non-accessible field _file in class com.liferay.contacts.web.internal.portlet.ContactsCenterPortlet, subclass of component class com.liferay.contacts.web.internal.portlet.ProfilePortlet
```

Full console log:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-30/test-portal-acceptance-pullrequest(master)/5415/functional-smoke-tomcat90-mysql57-jdk8_stable/0/0/jenkins-console.txt.gz?authuser=0

**Comment by julschong** [comment]
pushed to fix field access issue in ContactsCenterPortlet.java

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126694

**Pull request closed without merging**
