### PR TITLE
[Method References 2] LPS-165445 Convert method reference to ServiceTrackerMap in class SortFieldBuilderImpl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
Force-Push is just to fix the bug and make fields indexerRegistry and props private.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:forward

FYI @shuyangzhou

**Pull request closed without merging**
