### PR TITLE
[Remove Stream/Optional usage] LPS-172794 remove_stream_and_optional_in_portal_tools_rest_builder - part 2

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Resend from https://github.com/liferay-core-infra/liferay-portal/pull/3125
In part 2, I am focusing on the ftl files.
This is for ticket https://issues.liferay.com/browse/LPS-172794.
Thanks for checking

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:headless

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by jeffwu0724** [comment]
ci:test:headless

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
did some sf fix in the code, retrigger the test again

**Comment by Kvale1733** [comment]
@jeffwu0724 Rest builder failure
rest-builder-jdk8/0/0

```
[echo] --- a/modules/apps/headless/headless-user-notification/headless-user-notification-client/src/main/java/com/liferay/headless/user/notification/client/json/BaseJSONParser.java
     [echo] +++ b/modules/apps/headless/headless-user-notification/headless-user-notification-client/src/main/java/com/liferay/headless/user/notification/client/json/BaseJSONParser.java
     [echo] @@ -24,7 +24,6 @@ import java.util.List;
     [echo]  import java.util.Map;
     [echo]  import java.util.Stack;
     [echo]  import java.util.TreeMap;
     [echo] -import java.util.stream.Stream;
     [echo]  
     [echo]  import javax.annotation.Generated;
     [echo]  
     [echo] @@ -123,13 +122,13 @@ public abstract class BaseJSONParser<T> {
     [echo]  
     [echo]  		Object[] objects = (Object[])_readValue();
     [echo]  
     [echo] -		return Stream.of(
     [echo] -			objects
     [echo] -		).map(
     [echo] -			object -> parseToDTO((String)object)
     [echo] -		).toArray(
     [echo] -			size -> createDTOArray(size)
     [echo] -		);
     [echo] +		T[] dtos = createDTOArray(objects.length);
     [echo] +
     [echo] +		for (int i = 0; i < dtos.length; i++) {
     [echo] +			dtos[i] = parseToDTO((String)objects[i]);
     [echo] +		}
     [echo] +
     [echo] +		return dtos;
     [echo]  	}
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-31/test-portal-acceptance-pullrequest(master)/6776/rest-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
