### PR TITLE
[Components with more than 1 service] LPS-188507 Refactor components from portal-messaging, portal-search-solr8 and search-experience modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-188507

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:search

**Comment by MrJohn1911** [comment]
ci:test:search-solr

**Comment by MrJohn1911** [comment]
In this [commit](https://github.com/liferay-core-infra/liferay-portal/pull/4880/commits/0aa83e936a3ac06d2d276ac6ccb6b1dffb4c2055) I followed the rule that @shuyangzhou created [here](https://github.com/brianchandotcom/liferay-portal/pull/89601/commits/35edeeaaa9f634d554b55a34f9e9a13a3a3b6363). 

CC: @rafaprax @dantewang

**Comment by catarineaguiar** [comment]
ci:test:search-solr

**Comment by catarineaguiar** [comment]
no regressions found.

wait for search-solr results

**Comment by Kvale1733** [comment]
ci:test:search-solr

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions.

**Review by rafaprax — APPROVED** [review]

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian @shuyangzhou

**Pull request closed without merging**
