### PR TITLE
[Performance Tuning]LPS-151058

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@GinsonRen Please run a diff on Login for this pull.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test:echo

**Comment by tinatian** [comment]
ci:test:echo-acceptance

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina

**Comment by GinsonRen** [comment]
@tinatian @dantewang Here is the diff result:

Portal version | Git ID/PR link | Session count | Meantime of Login | Session Count Change compare to baseline（%）
-- | -- | -- | -- | --
BaseLine | 653eafc | 49957 | 303 | -
LPS-151058 | https://github.com/liferay-core-infra/liferay-portal/pull/624 | 51060 | 269 | 2.21%

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina.

**Comment by catarineaguiar** [comment]
@tinatian no regressions found.

**Comment by tinatian** [comment]
@xbrianlee This is going to fix part of the performance issue of publication, could you please verify how much improvement we get from this change? Then we can decided if we are going to do more or not.

Thanks.
Tina.

**Comment by tinatian** [comment]
FYI @ealonso

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116252

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
