### PR TITLE
LPD-28003 Replace usages of google cache

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:saml

**Comment by dantewang** [comment]
ci:test:analytics-cloud

**Comment by dantewang** [comment]
ci:report:12246961

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:saml

**Comment by dantewang** [comment]
ci:report:12359630

**Comment by dantewang** [comment]
ci:report:12364834

**Comment by dantewang** [comment]
ci:report:12360157

**Comment by dantewang** [comment]
relevant: 1 unique, but also failed on a Commerce team PR, so it should be upstream issue;
saml: no unique;
AC: several unique failures, need to check.

**Comment by dantewang** [comment]
ci:test:analytics-cloud

**Comment by dantewang** [comment]
ci:report:14579272

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 14579272.
> 
> Job Link: [generate-testray-csv](https://test-1-34.liferay.com/job/generate-testray-csv/121/)
> 
> Testray CSV Link: [testray-results-14579272.csv](https://test-1-34.liferay.com/userContent/jobs/generate-testray-csv/builds/121/testray-results-14579272.csv)

Report marked 4 unique failures.
- 3 unique failures also fail on upstream;
- 1 unique failure passed in last run.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/151359

**Pull request closed without merging**
