### PR TITLE
[Convert method references]LPS-162480 Covert simple method references to filed references in mod…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-162480

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Review by dantewang — APPROVED** [review]
@slnn Please force push to fix the typo in your commit message.

**Comment by slnn** [comment]
> @slnn Please force push to fix the typo in your commit message.

Done

**Comment by slnn** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
@catarineaguiar Could you take a look at the tests when they finish?

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@shuyangzhou @tinatian All tests passed and changes are direct replacements. Asked Commerce team for a final check

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
