### PR TITLE
remove_deprecated_propsvalues_and_its_properties

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

I removed the deprecated PropsValue and PropsKey, also updated the portal.properties as well as verifyProperties. This PR is based on "Remove deprecated part 4 redo". see https://github.com/liferay-core-infra/liferay-portal/pull/379#event-6174995719
Thanks for checking. Also see https://github.com/jeffwu0724/liferay-portal/pull/31

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by kyle-miho** [comment]
failures are unrelated @jeffwu0724

**Comment by tinatian** [comment]
@jeffwu0724 There are still deprecated constants not removed in PropsKeys and PropsValues. Why you did not remove those together with this pull?

Tina

**Comment by jeffwu0724** [comment]
> @jeffwu0724 There are still deprecated constants not removed in PropsKeys and PropsValues. Why you did not remove those together with this pull?
> 
> Tina

for the reason not removing some deprecated constants in PropsKeys and PropsValues. Some of them are still using by others, and for some deprecated constants, if I removed them, it will cause errors. Therefore, I only keep these safe-to-remove deprecated constants

**Comment by tinatian** [comment]
@jeffwu0724 I am going to close this pull as we are going to have a talk about this.

Tina

**Pull request closed without merging**
