### PR TITLE
LPS-164112 Remove immediate from rest builder

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @catarineaguiar, Can you please scan these test results when they are ready? Thx

**Comment by rafaprax** [comment]
ci:test:acceptance-functional

**Comment by catarineaguiar** [comment]
@rafaprax regression found:

```
  [exec] com.liferay.headless.admin.user.resource.v1_0.factory.test.PhoneResourceFactoryImplTest > testCheckPermissionsWithCompanyAdminUser FAILED
     [exec]     java.lang.NullPointerException
     [exec]     	at com.liferay.headless.admin.user.resource.v1_0.PhoneResource.builder(PhoneResource.java:56)
     [exec]     	at com.liferay.headless.admin.user.resource.v1_0.factory.test.PhoneResourceFactoryImplTest.testCheckPermissionsWithCompanyAdminUser(PhoneResourceFactoryImplTest.java:77)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
```
```
     [exec] com.liferay.headless.admin.user.resource.v1_0.factory.test.PhoneResourceFactoryImplTest > testCheckPermissionsWithUser2 FAILED
     [exec]     java.lang.Exception: Unexpected exception, expected<com.liferay.portal.kernel.security.auth.PrincipalException$MustHavePermission> but was<java.lang.NullPointerException>
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._processExpectedException(TestExecutorRunnable.java:416)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.access$400(TestExecutorRunnable.java:66)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:380)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-32/test-portal-acceptance-pullrequest(master)/6011/modules-integration-mysql57-jdk8/0/18/jenkins-console.txt.gz?authuser=0)

**Comment by catarineaguiar** [comment]
no regressions on acceptance-functional results. Please, check this [comment](https://github.com/liferay-core-infra/liferay-portal/pull/1823#issuecomment-1261380198)

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:acceptance-functional

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:acceptance-functional

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:acceptance-functional

**Comment by Kvale1733** [comment]
@rafaprax 

Semver error

```
  [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/data-engine/data-engine-rest-test-util] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.data.engine.rest.test.util             MAJOR      1.0.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.data.engine.rest.test.util.DataDefinitionTestUtil
     [exec]     		+   method     addDataDefinition(java.lang.String,com.liferay.data.engine.rest.resource.v2_0.DataDefinitionResource$Factory,long,java.lang.String,com.liferay.portal.kernel.model.User)
     [exec]     			+   access     static
     [exec]     			+   return     com.liferay.data.engine.rest.dto.v2_0.DataDefinition
     [exec]     		-   method     addDataDefinition(java.lang.String,long,java.lang.String,com.liferay.portal.kernel.model.User)
     [exec]     			-   access     static
     [exec]     			-   return     com.liferay.data.engine.rest.dto.v2_0.DataDefinition
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 2.0.0
```
[Logs](https://testray.liferay.com/reports/production/logs/2022-10/test-1-29/test-portal-acceptance-pullrequest(master)/4926/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:test:acceptance-functional

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:acceptance-functional

**Comment by rafaprax** [comment]
Hi all, I just update a commit message. The test results are still valid. Thx

//cc @Kvale1733

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:acceptance-functional

**Comment by catarineaguiar** [comment]
@rafaprax semver error:

```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/headless/headless-admin-user/headless-admin-user-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.headless.admin.user.resource.v1_0      MAJOR      8.0.0      8.0.0      9.0.0      VERSION INCREASE REQUIRED
     [exec]     	-   class      com.liferay.headless.admin.user.resource.v1_0.AccountResource$FactoryHolder
```
```
 [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/headless/headless-delivery/headless-delivery-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.headless.delivery.resource.v1_0        MAJOR      15.7.0     15.7.0     16.0.0     VERSION INCREASE REQUIRED
     [exec]     	-   class      com.liferay.headless.delivery.resource.v1_0.BlogPostingImageResource$FactoryHolder
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-26/test-portal-acceptance-pullrequest(master)/5397/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
semver issue fixed

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by rafaprax** [comment]
Hey @shuyangzhou , this pr is ready for your review. Thx

**Pull request closed without merging**
