### PR TITLE
Lps 161581 break6

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-161581

Hi @dantewang @tinatian 

This pull removes the reference CPDefinitionOptionRelLocalService from CPInstanceLocalServiceImp to break the circular dependency:CPInstanceLocalService -> CPDefintionOptionRelLocalService -> CPDefinitionLocalService -> CPInstanceLocalService

Lily

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:commerce

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan the test results when finished?

Thanks
Lily

**Comment by catarineaguiar** [comment]
Hi @slnn, all tests from Commerce failed...

these are some examples:
```
LIFERAY_ERROR: Declarative Service Unsatisfied Component Checker check result: 
Bundle {id: 373, name: com.liferay.commerce.theme.minium.site.initializer, version: 5.0.25}
	Declarative Service {id: 6827, name: com.liferay.commerce.theme.minium.site.initializer.internal.MiniumSiteInitializer, unsatisfied references: 
		{name: _assetCategoriesImporter, target: null}
		{name: _commerceAccountsImporter, target: null}
		{name: _commerceCatalogLocalService, target: null}
		{name: _commerceChannelLocalService, target: null}
		{name: _commerceDiscountsImporter, target: null}
		{name: _commerceInventoryWarehousesImporter, target: null}
		{name: _commercePriceEntriesImporter, target: null}
		{name: _commercePriceListsImporter, target: null}
		{name: _commerceShippingFixedOptionLocalService, target: null}
		{name: _commerceShippingMethodLocalService, target: null}
		{name: _cpDefinitionLinkLocalService, target: null}
		{name: _cpDefinitionLocalService, target: null}
		{name: _cpDefinitionsImporter, target: null}
		{name: _cpMeasurementUnitLocalService, target: null}
		{name: _cpOptionCategoriesImporter, target: null}
		{name: _cpOptionsImporter, target: null}
		{name: _cpSpecificationOptionsImporter, target: null}
	}
```
```
 [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.CPCommerceProducts#TranslateProductName] STANDARD_OUT
     [exec]     Executing commands: curl -X GET -u 'test@liferay.com:test' -H 'accept: application/json' http://test-1-32-59.lax.liferay.com:8080/o/headless-commerce-admin-order/v1.0/orders
[beanshell] 2022-09-05 12:16:22.617 ERROR [http-nio-8080-exec-2][WebApplicationExceptionMapper:38] null
[beanshell] javax.ws.rs.ClientErrorException: HTTP 404 Not Found
[beanshell] 	at org.apache.cxf.jaxrs.utils.SpecExceptions.toHttpException(SpecExceptions.java:117) ~[bundleFile:3.4.4]
[beanshell] 	at org.apache.cxf.jaxrs.utils.ExceptionUtils.toHttpException(ExceptionUtils.java:168) [bundleFile:3.4.4]
[beanshell] 	at org.apache.cxf.jaxrs.utils.JAXRSUtils.findTargetMethod(JAXRSUtils.java:516) [bundleFile:3.4.4]
[beanshell] 	at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.processRequest(JAXRSInInterceptor.java:182) [bundleFile:3.4.4]
[beanshell] 	at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.handleMessage(JAXRSInInterceptor.java:79) [bundleFile:3.4.4]
[beanshell] 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [bundleFile:3.4.4]
[beanshell] 	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [bundleFile:3.4.4]
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-27/test-portal-acceptance-pullrequest(master)/4821/functional-tomcat90-mysql57-jdk8/1/18/jenkins-console.txt.gz?authuser=0)

```
 [exec] com.liferay.commerce.machine.learning.recommendation.info.collection.provider.test.FrequentPatternCommerceMLRecommendationRelatedInfoItemCollectionProviderTest > testGetRelatedItemsInfoPage FAILED
     [exec]     java.lang.IllegalStateException: Timed out while waiting for service com.liferay.commerce.product.service.CPDefinitionLocalService 
     [exec]     	at com.liferay.portal.test.rule.InjectTestBag._getServiceReference(InjectTestBag.java:199)
     [exec]     	at com.liferay.portal.test.rule.InjectTestBag.injectFields(InjectTestBag.java:78)
     [exec]     	at com.liferay.portal.test.rule.InjectTestRule.beforeMethod(InjectTestRule.java:61)
     [exec]     	at com.liferay.portal.test.rule.InjectTestRule.beforeMethod(InjectTestRule.java:24)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:94)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-27/test-portal-acceptance-pullrequest(master)/4821/modules-integration-mysql57-jdk8/0/11/jenkins-console.txt.gz?authuser=0)

```
[exec] com.liferay.commerce.discount.service.persistence.test.CommerceDiscountPersistenceTest > testActionableDynamicQuery STARTED
     [exec] 
     [exec] com.liferay.commerce.discount.service.persistence.test.CommerceDiscountPersistenceTest > testActionableDynamicQuery FAILED
     [exec]     java.lang.NullPointerException
     [exec]     	at com.liferay.commerce.discount.service.CommerceDiscountLocalServiceUtil.getActionableDynamicQuery(CommerceDiscountLocalServiceUtil.java:704)
     [exec]     	at com.liferay.commerce.discount.service.persistence.test.CommerceDiscountPersistenceTest.testActionableDynamicQuery(CommerceDiscountPersistenceTest.java:546)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
```
```
 [exec] com.liferay.commerce.inventory.service.mvcc.test.CommerceInventoryMVCCTest > testReplenishmentItemMVCC FAILED
     [exec]     java.lang.Exception: Unexpected exception, expected<com.liferay.commerce.inventory.exception.MVCCException> but was<java.lang.NullPointerException>
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._processExpectedException(TestExecutorRunnable.java:416)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.access$400(TestExecutorRunnable.java:66)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:380)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-27/test-portal-acceptance-pullrequest(master)/4821/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
> Bundle {id: 373, name: com.liferay.commerce.theme.minium.site.initializer, version: 5.0.25}

Thanks @catarineaguiar , I will double check my changes.

**Comment by slnn** [comment]
ci:test:commerce

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Hi @catarineaguiar 

I fix the origin issue and forced push to this pull, could you help to scan test results when they are finished?

Thanks
Lily

**Comment by Kvale1733** [comment]
@slnn I've checked the results of relevant and commerce, no regressions found.

**Pull request closed without merging**
