### PR TITLE
[Components with more than 1 service] LPS-179094 Refactor ScreenNavigationCategory components from Objects modules

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-179094](https://issues.liferay.com/browse/LPS-179094)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:objects

**Comment by RenanUmV** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
@RenanUmV No regressions.

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:object

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:object

**Comment by zhangyan0701** [comment]
Many Objects tests failed because the Objects portlet is empty:
Objects

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:object

**Comment by catarineaguiar** [comment]
@RenanUmV regression found when adding a new page:

```
ERROR [http-nio-8080-exec-9][ObjectDefinitionsObjectsScreenNavigationEntry:56] bundle com.liferay.object.web:1.0.158 (461)[com.liferay.object.web.internal.object.definitions.frontend.taglib.servlet.taglib.ObjectDefinitionsObjectsScreenNavigationEntry(7575)] : findField: Suitable but non-accessible field _language in class com.liferay.object.web.internal.object.definitions.frontend.taglib.servlet.taglib.ObjectDefinitionsObjectsScreenNavigationCategory, subclass of component class com.liferay.object.web.internal.object.definitions.frontend.taglib.servlet.taglib.ObjectDefinitionsObjectsScreenNavigationEntry
     [exec]     LIFERAY_ERROR: bundle com.liferay.object.web:1.0.158 (461)[com.liferay.object.web.internal.object.definitions.frontend.taglib.servlet.taglib.ObjectDefinitionsObjectsScreenNavigationEntry(7575)] : findField: Suitable but non-accessible field _language in class com.liferay.object.web.internal.object.definitions.frontend.taglib.servlet.taglib.ObjectDefinitionsObjectsScreenNavigationCategory, subclass of component class com.liferay.object.web.internal.object.definitions.frontend.taglib.servlet.taglib.ObjectDefinitionsObjectsScreenNavigationEntry
```
Full log [here](https://testray.liferay.com/reports/production/logs/2023-03/test-1-29/test-portal-acceptance-pullrequest(master)/6877/functional-smoke-tomcat90-mysql57-jdk11_open/0/0/jenkins-console.txt.gz?authuser=0)
Testcase [PortalSmoke#Smoke](https://testray.liferay.com/home/-/testray/case_results/2254152372?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2254133086%26testrayRunId%3D2254151475%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Pull request closed without merging**
