### PR TITLE
[Remove Blocking usages]LPS-200476 

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace blocking ServiceProxyFactory with Snapshot in class `WorkflowTaskManagerUtil`. Thanks for checking.
https://liferay.atlassian.net/browse/LPS-200476

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
