### PR TITLE
LPS-173597 Cleanup in DLProcessorRegistryImpl

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:dl-store

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
@rafaprax can you review this? thanks.

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@MrJohn1911 Regressions found

1) Compile issue 
```
[exec] > Task :apps:document-library:document-library-preview-audio-test:compileTestIntegrationJava FAILED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/document-library/document-library-preview-audio-test/src/testIntegration/java/com/liferay/document/library/preview/audio/test/DLAudioFFMPEGAudioConverterTest.java:40: error: cannot find symbol
     [exec] import com.liferay.portlet.documentlibrary.util.AudioProcessorImpl;
     [exec]                                                ^
     [exec]   symbol:   class AudioProcessorImpl
     [exec]   location: package com.liferay.portlet.documentlibrary.util
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/document-library/document-library-preview-audio-test/src/testIntegration/java/com/liferay/document/library/preview/audio/test/DLAudioFFMPEGAudioConverterTest.java:98: error: cannot find symbol
     [exec] 		level = "ERROR", loggerClass = AudioProcessorImpl.class
     [exec] 		                               ^
     [exec]   symbol:   class AudioProcessorImpl
     [exec]   location: class com.liferay.document.library.preview.audio.test.DLAudioFFMPEGAudioConverterTest
     [exec] 2 errors
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-36/test-portal-acceptance-pullrequest(master)/2868/modules-integration-mysql57-jdk8/1/8/jenkins-console.txt.gz?authuser=0)

2) Compile issue
```
   [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:56: error: cannot find symbol
     [exec] import com.liferay.portlet.documentlibrary.util.ImageProcessorImpl;
     [exec]                                                ^
     [exec]   symbol:   class ImageProcessorImpl
     [exec]   location: package com.liferay.portlet.documentlibrary.util
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:254: error: cannot find symbol
     [exec] 			new ImageProcessorImpl(),
     [exec] 			    ^
     [exec]   symbol:   class ImageProcessorImpl
     [exec]   location: class com.liferay.adaptive.media.document.library.thumbnails.internal.osgi.commands.test.AMThumbnailsOSGiCommandsTest
     [exec] 2 errors
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-36/test-portal-acceptance-pullrequest(master)/2868/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

3)Compile issue
```
   [exec] /opt/dev/projects/github/liferay-portal/modules/apps/document-library/document-library-video-test/src/testIntegration/java/com/liferay/document/library/video/converter/test/DLVideoFFMPEGVideoConverterTest.java:21: error: package com.liferay.document.library.preview.video.internal does not exist
     [exec] import com.liferay.document.library.preview.video.internal.VideoProcessorImpl;
     [exec]                                                           ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/document-library/document-library-video-test/src/testIntegration/java/com/liferay/document/library/video/converter/test/DLVideoFFMPEGVideoConverterTest.java:98: error: cannot find symbol
     [exec] 		level = "ERROR", loggerClass = VideoProcessorImpl.class
     [exec] 		                               ^
     [exec]   symbol:   class VideoProcessorImpl
     [exec]   location: class com.liferay.document.library.video.converter.test.DLVideoFFMPEGVideoConverterTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/document-library/document-library-video-test/src/testIntegration/java/com/liferay/document/library/video/converter/test/DLVideoFFMPEGVideoConverterTest.java:173: error: cannot find symbol
     [exec] 		level = "ERROR", loggerClass = VideoProcessorImpl.class
     [exec] 		                               ^
     [exec]   symbol:   class VideoProcessorImpl
     [exec]   location: class com.liferay.document.library.video.converter.test.DLVideoFFMPEGVideoConverterTest
     [exec] 3 errors
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-36/test-portal-acceptance-pullrequest(master)/2868/modules-compile-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

4)

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:dl-store

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:dl-store

**Pull request closed without merging**
