### PR TITLE
LPS-179574 Clean up ExportImportContentProcessorRegistryUtil

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-179574

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:test:export-import

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:export-import

**Comment by kyle-miho** [comment]
@rafaprax this causes a regression in the integration test, no other unique failures were found
```
com.liferay.adaptive.media.journal.internal.exportimport.data.handler.test.AMJournalArticleStagedModelDataHandlerTest > testExportSucceedsWithInvalidReferences FAILED
    com.liferay.portal.kernel.exception.PortalException: com.liferay.document.library.kernel.exception.NoSuchFileEntryException: No FileEntry exists with the key {fileEntryId=9999999}
```

**Comment by rafaprax** [comment]
waiting for this fix here https://issues.liferay.com/browse/LPS-180242

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:export-import

**Comment by rafaprax** [comment]
Note: Fix for the  https://issues.liferay.com/browse/LPS-180242 has been merged

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@rafaprax Please make JournalArticleModelValidator to reference the ExportImportContentProcessor by compnoent.name direclty, so that you will not need ExportImportContentProcessorRegistryUtil. As I can see, JournalArticleModelValidator is the only usage. This way, you can remove ExportImportContentProcessorRegistryUtil.

Please resend.

Thanks.
Tina.

**Pull request closed without merging**
