### PR TITLE
[Replace Non-Blocking Usage] LPS-198485 Replace non-blocking ServiceProxyFactory usages in classes DDMStructureManagerUtil, BBCodeTranslatorUtil and CTCollectionThreadLocal

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
no conflicts(10/11 9:04)

**Comment by W2jx** [comment]
no conflicts(10/12 9:54)

**Comment by W2jx** [comment]
Hi @dantewang , this PR has been checked.

**Comment by W2jx** [comment]
no conflicts(10/16 8:59)

**Comment by W2jx** [comment]
no conflicts(10/17 8:23)

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142335

**Pull request closed without merging**
