### PR TITLE
LPD 26157 dxp master new pattern

### PR DESCRIPTION
**Pull request by titokenzo**
- **LPD-26157 Make internal class AssetCategoryTreePathComparator's attributes private**
- **LPD-26157 Make StructureStructureKeyComparator class attributes private**
- **LPD-26157 Add singleton to AssetTagCountComparator and apply**
- **LPD-26157 Add singleton to AssetEntryAssetCategoryRelAssetCategoryIdComparator and apply**
- **LPD-26157 Add singleton to AssetListEntryCreateDateComparator and apply**
- **LPD-26157 Update tests that uses AssetListEntryCreateDateComparator**
- **LPD-26157 SemVer**
- **LPD-26157 Add Upgrade case and test**

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:sf

**Comment by titokenzo** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
