### PR TITLE
[Static reference] LPS-181674 Remove method reference by using snapshot in modules expando-taglib, export-import-changeset-taglib, flags-taglib, fragment-taglib

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:export-import

**Comment by W2jx** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(4/20 7:56)

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
