### PR TITLE
[Remove Stream/Optional usage] LPS-175357 modules: layout-page-template-admin-web, layout-page-template-service, layout-page-template-test, layout-portlets-web, layout-reports-web, layout-seo-web-test 

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend, thanks!
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3562
https://issues.liferay.com/browse/LPS-175357

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
@JanisZhang Compile issue found in com.liferay.layout.reports.web.internal.model.LayoutReportsIssueTest
```
  [exec] > Task :apps:layout:layout-reports-web:compileTestJava FAILED
     [exec] 
     [exec] > Task :apps:layout:layout-reports-web:processTestResources NO-SOURCE
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/layout/layout-reports-web/src/test/java/com/liferay/layout/reports/web/internal/model/LayoutReportsIssueTest.java:174: error: unreported exception java.lang.Exception; must be caught or declared to be thrown
     [exec] 		JSONObject jsonObject = layoutReportsIssue.toJSONObject(
     [exec] 		                                                       ^
     [exec] 1 error
     [exec] 
     [exec] > Task :apps:layout:layout-seo-web:compileJava
     [exec] 
```
[Log](https://testray.liferay.com/reports/production/logs/2023-03/test-1-40/test-portal-acceptance-pullrequest(master)/488/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
