### PR TITLE
[Convert method references ]LPS-162720 Convert method references to field references in module co…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-162720

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by slnn** [comment]
Close this pull, since it's changing a util, it will be done in the second round.

**Pull request closed without merging**
