### PR TITLE
[Components with more than 1 service] LPS-190147 Refactor DLOpenerGoogleDriveManager component

### PR DESCRIPTION
**Pull request by MrJohn1911**
In this pull, the module document-library-opener-google-drive-api was completed removed since Dante realized that the classes inside it were deprecated or have no usages and Adolfo Perez authored it, please see this [thread](https://liferay.slack.com/archives/CLD39UKM5/p1689344027372969).

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:online-editing

**Comment by Kvale1733** [comment]
ci:test:online-editing

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Comment by MrJohn1911** [comment]
In the last push, I just reorganized the commits.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@rafaprax Looks good to me

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
ci:forward:force

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
