### PR TITLE
[Remove Blocking usages]LPS-189564 portal-kernel | WorkflowComparatorFactoryUtil

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
@dantewang Semver error

```
   [exec] > Task :apps:portal-workflow:portal-workflow-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.workflow.constants              MINOR      1.4.0      1.4.0      1.5.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.portal.workflow.constants.WorkflowWebKeys
     [exec] 		+   field      WORKFLOW_INSTANCE_EDIT_DISPLAY_CONTEXT
     [exec] 			+   access     final
     [exec] 			+   access     static
     [exec] 			+   constant   WORKFLOW_INSTANCE_EDIT_DISPLAY_CONTEXT
     [exec] 			+   return     java.lang.String
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.portal.workfl
```
[Log](https://testray.liferay.com/reports/production/logs/2023-07/test-1-32/test-portal-acceptance-pullrequest(master)/1000/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by JanisZhang** [comment]
@dantewang file conflicts and server error. I will resend it. Thanks ！

**Pull request closed without merging**
