### PR TITLE
LPS-145913 Inviter Publications role is missing publish permission, Publisher role shouldn't have invite permissions

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-145913

Additional tests run in https://github.com/xbrianlee/liferay-portal/pull/691:
- [❌ ci:test:publications - 7 out of 9 jobs passed](https://github.com/xbrianlee/liferay-portal/pull/691#issuecomment-1026451678) - Semver failure is unrelated to the changes in this PR
- [❌ ci:test:publications-environments - 16 out of 34 jobs passed ](https://github.com/xbrianlee/liferay-portal/pull/691#issuecomment-1026102738) - No environment-specific failures related to these changes

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
cc/ @stsquared99

**Comment by xbrianlee** [comment]
cc/ @stsquared99 @tinatian

**Comment by stsquared99** [comment]
ci:test

**Comment by stsquared99** [comment]
@xbrianlee Do these last errors look valid? Thanks

**Comment by xbrianlee** [comment]
@stsquared99 I didn't find any new failures caused by the changes in this PR

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.
@stsquared99 I noticed that several methods in PublicationRoleConstants are only used in one place, for example `getModelResourceActions` is only used `InviteUsersMVCResourceCommand`. 
Please send a following pull to clean up usages like this, if a method has only one usage, then you should at least make it private method inside the same class rather than define it in another class as static class.

Thanks.
Tina.

**Pull request closed without merging**
