### PR TITLE
LPS-199846  upgrade xmlsec to 3.0.3

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang

Resend: https://github.com/liferay-core-infra/liferay-portal/pull/5911
Make -exportcontents with detailed classes
This is for ticket https://liferay.atlassian.net/browse/LPS-199846.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/9/23 9:26am

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/13/23 8:04am

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/14/23 8:37am

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/16/23 8:26am

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
