### PR TITLE
[TS Bug fix] LPS-154127 StripFilter & test

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian I renamed methods, and modified the assertions for better readability. On the other hand, I noticed another issue in the input tag handling, see my last 2 commits. I wonder whether we need to fix it, since although it's legal, it's useless for real world.

### CODE REVIEW

**Comment by dantewang** [comment]
@catarineaguiar Could you review the test results once they finish? Thanks!

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by rolandpakai** [comment]
Hi @catarineaguiar 

could you please push this forward?

Thanks, Roland

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by rolandpakai** [comment]
Hi @shuyangzhou 

could you please move this PR forward?

Thanks, Roland

**Comment by shuyangzhou** [comment]
See  https://github.com/brianchandotcom/liferay-portal/pull/119523

**Pull request closed without merging**
