### PR TITLE
LPS-172806 Remove "immediate = true" from remaining Front End modules

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:frontend

**Comment by catarineaguiar** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
@MrJohn1911 can you check this failure, please?

[LocalFile.WebContentSearch#SearchWebContentTag](https://testray.liferay.com/home/-/testray/case_results/2162971604?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2162971080%26testrayRunId%3D2162971146%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

```
     [exec]     LIFERAY_ERROR: java.lang.RuntimeException: org.elasticsearch.ElasticsearchStatusException: [liferay-20097-workflow-metrics-processes] ElasticsearchStatusException[Elasticsearch exception [type=index_not_found_exception, reason=no such index [liferay-20097-workflow-metrics-processes]]]
```

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by MrJohn1911** [comment]
Hey @tinatian this one is ready to go!

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129125

**Pull request closed without merging**
