### PR TITLE
[Jasper] LPD-36036 Tomcat Jasper in runtime | enable page context pool

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou @tinatian This PR enables the Tomcat's page context pool.

PR disabling precomile: https://github.com/liferay-core-infra/liferay-portal/pull/7588

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:app-servers

**Comment by dantewang** [comment]
ci:test:frontend

**Comment by dantewang** [comment]
ci:report:53570991

**Comment by dantewang** [comment]
ci:report:53571571

**Comment by dantewang** [comment]
ci:test:frontend

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 53570991.
> 
> Job Link: [generate-testray-csv](https://test-1-37.liferay.com/job/generate-testray-csv/422/)
> 
> Testray CSV Link: [testray-results-53570991.csv](https://test-1-37.liferay.com/userContent/jobs/generate-testray-csv/builds/422/testray-results-53570991.csv)

NO unique failure in app-servers.

**Comment by dantewang** [comment]
ci:report:53587230

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 53587230.
> 
> Job Link: [generate-testray-csv](https://test-1-40.liferay.com/job/generate-testray-csv/632/)
> 
> Testray CSV Link: [testray-results-53587230.csv](https://test-1-40.liferay.com/userContent/jobs/generate-testray-csv/builds/632/testray-results-53587230.csv)

No unique in relevant

**Comment by dantewang** [comment]
ci:report:53587169

**Comment by dantewang** [comment]
ci:test:frontend

**Comment by dantewang** [comment]
Looking into FrontendDataSetTable#HeadersCanBeLocalized

**Comment by dantewang** [comment]
Looking into `LocalFile.FrontendDataSetTable#HeadersCanBeLocalized`.

**Comment by dantewang** [comment]
> Looking into `LocalFile.FrontendDataSetTable#HeadersCanBeLocalized`.

This test always fails in the frontend suite on this PR. However, manually executing the steps locally, everything works.

The failure on CI is because of the table in the Frontend Data Set Sample portlet is loading, so Selenium can't see the element. The table loads fine on my local, and the contents match exactly what the test case wants.

Besides this one, there's no unique failure found on this PR. @tinatian

**Comment by dantewang** [comment]
ci:test:frontend

**Comment by dantewang** [comment]
> ### ❌ ci:test:frontend - 41 out of 45 jobs passed in 6 hours 11 minutes
> Click here for more details.
> 
> This pull is eligible for [reevaluation](https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands). When this [upstream build](https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/957) has completed, using the following CI command will compare this pull request result against a more recent upstream result:
> 
> ci:reevaluate:1347401_6871
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)Branch GIT ID: [f2d3fe5c3f6698a4bbb458e01d01bb43686d4246](https://github.com/liferay/liferay-portal/commit/f2d3fe5c3f6698a4bbb458e01d01bb43686d4246)
> 
> #### Upstream Comparison:
> Branch GIT ID: [6e080c87235ae146e2d7a53d8a3a5fa12d52ae6d](https://github.com/liferay/liferay-portal/commit/6e080c87235ae146e2d7a53d8a3a5fa12d52ae6d)Jenkins Build URL: [EE Development Acceptance (master) - 956 - 2024-10-28[16:41:35]](https://testray.liferay.com/#/project/35392/routines/590307/build/54471532)
> 
> **ci:test:frontend - 41 out of 45 jobs PASSED**
> ##### For more details click [here](https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6871/jenkins-report.html).
> #### Failures unique to this pull:
> 1. [functional-tomcat90-mysql57/0/0](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/708082//consoleText)1. [LocalFile.RightToLeftInfrastructure#RTLDirectionStyleAppliedToTextField](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/708082//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_RightToLeftInfrastructure_RTLDirectionStyleAppliedToTextField_) - [Poshi Report](https://storage.cloud.google.com/testray-results/2024-10/test-1-34/test-portal-acceptance-pullrequest(master)/6871/functional-tomcat90-mysql57/0/0/LocalFile.RightToLeftInfrastructure_RTLDirectionStyleAppliedToTextField/index.html.gz) - [Poshi Summary](https://storage.cloud.google.com/testray-results/2024-10/test-1-34/test-portal-acceptance-pullrequest(master)/6871/functional-tomcat90-mysql57/0/0/LocalFile.RightToLeftInfrastructure_RTLDirectionStyleAppliedToTextField/summary.html.gz) - [Console Output](https://storage.cloud.google.com/testray-results/2024-10/test-1-34/test-portal-acceptance-pullrequest(master)/6871/functional-tomcat90-mysql57/0/0/jenkins-console.txt.gz) - [Liferay Log](https://storage.cloud.google.com/testray-results/2024-10/test-1-34/test-portal-acceptance-pullrequest(master)/6871/functional-tomcat90-mysql57/0/0/LocalFile.RightToLeftInfrastructure_RTLDirectionStyleAppliedToTextField/liferay-log.txt.gz)
> 2. [functional-tomcat90-mysql57/0/6](https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/387549//consoleText)1. [LocalFile.Cadmin#CssCanBeOverridden](https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/387549//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Cadmin_CssCanBeOverridden_) - [Poshi Report](https://storage.cloud.google.com/testray-results/2024-10/test-1-34/test-portal-acceptance-pullrequest(master)/6871/functional-tomcat90-mysql57/0/6/LocalFile.Cadmin_CssCanBeOverridden/index.html.gz) - [Poshi Summary](https://storage.cloud.google.com/testray-results/2024-10/test-1-34/test-portal-acceptance-pullrequest(master)/6871/functional-tomcat90-mysql57/0/6/LocalFile.Cadmin_CssCanBeOverridden/summary.html.gz) - [Console Output](https://storage.cloud.google.com/testray-results/2024-10/test-1-34/test-portal-acceptance-pullrequest(master)/6871/functional-tomcat90-mysql57/0/6/jenkins-console.txt.gz) - [Liferay Log](https://storage.cloud.google.com/testray-results/2024-10/test-1-34/test-portal-acceptance-pullrequest(master)/6871/functional-tomcat90-mysql57/0/6/LocalFile.Cadmin_CssCanBeOverridden/liferay-log.txt.gz)
> 3. [functional-tomcat90-mysql57/0/18](https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/387551//consoleText)1. [LocalFile.ClientExtensionJSImportMap#CanChangeLanguage](https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/387551//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ClientExtensionJSImportMap_CanChangeLanguage_) - [Poshi Report](https://storage.cloud.google.com/testray-results/2024-10/test-1-34/test-portal-acceptance-pullrequest(master)/6871/functional-tomcat90-mysql57/0/18/LocalFile.ClientExtensionJSImportMap_CanChangeLanguage/index.html.gz) - [Poshi Summary](https://storage.cloud.google.com/testray-results/2024-10/test-1-34/test-portal-acceptance-pullrequest(master)/6871/functional-tomcat90-mysql57/0/18/LocalFile.ClientExtensionJSImportMap_CanChangeLanguage/summary.html.gz) - [Console Output](https://storage.cloud.google.com/testray-results/2024-10/test-1-34/test-portal-acceptance-pullrequest(master)/6871/functional-tomcat90-mysql57/0/18/jenkins-console.txt.gz) - [Liferay Log](https://storage.cloud.google.com/testray-results/2024-10/test-1-34/test-portal-acceptance-pullrequest(master)/6871/functional-tomcat90-mysql57/0/18/LocalFile.ClientExtensionJSImportMap_CanChangeLanguage/liferay-log.txt.gz)
> 
> #### For upstream results, click [here](https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)).
> ##### Test bundle downloads:
> * [liferay-portal-bundle-tomcat.tar.gz](https://test-1-34.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6871/bundles/liferay-portal-bundle-tomcat.tar.gz)

`LocalFile.FrontendDataSetTable#HeadersCanBeLocalized` passed in this run. Marking QA Passed.

**Comment by dantewang** [comment]
No-precompile also passed: https://github.com/liferay-core-infra/liferay-portal/pull/7588

**Comment by dantewang** [comment]
@JerryAdrianoo Could you run a performance comparison for this PR? Both startup and runtime tests, thanks!

cc @slnn @tinatian

**Comment by dantewang** [comment]
Force pushed to drop an unnecessary commit.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:app-servers

**Comment by dantewang** [comment]
ci:test:frontend

**Comment by JerryAdrianoo** [comment]
Hi, Dante!
The results are in this [spreadsheet](https://docs.google.com/spreadsheets/d/1sLyZaKMbOQdT2OHpMyT3rGtXmxARBTA4SgHhOSjFPsI/edit?gid=271218313#gid=271218313).
I ran the startup about 8 times, but Startup Hot seems a little longer than before (about 250~300 ms), but now I can't give you a consistent answer as the baseline after switching to the new version of the YJP and JDK21 has not yet been established.
But looking into the daily spreadsheet for startup, the increase looks true.

**Comment by tinatian** [comment]
ci:report:56861163

**Comment by dantewang** [comment]
ci:report:56859038

**Comment by dantewang** [comment]
ci:test:app-servers

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:57451463

**Comment by dantewang** [comment]
ci:report:57467901

**Comment by dantewang** [comment]
ci:report:57467901

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 57451463.
> 
> Job Link: [generate-testray-csv](https://test-1-40.liferay.com/job/generate-testray-csv/641/)
> 
> Testray CSV Link: [testray-results-57451463.csv](https://test-1-40.liferay.com/userContent/jobs/generate-testray-csv/builds/641/testray-results-57451463.csv)

No regression in app-servers.

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 57467901.
> 
> Job Link: [generate-testray-csv](https://test-1-9.liferay.com/job/generate-testray-csv/242/)
> 
> Testray CSV Link: [testray-results-57467901.csv](https://test-1-9.liferay.com/userContent/jobs/generate-testray-csv/builds/242/testray-results-57467901.csv)

Comparing the 2 relevant runs, this with https://github.com/liferay-core-infra/liferay-portal/pull/7587#issuecomment-2450985337, I believe there's no unique failure.

**Comment by dantewang** [comment]
The 3 test cases of `JspServletPerformanceTest` passed locally with logged time less than 150ms.

**Pull request closed without merging**
