### PR TITLE
LPS-142048

### PR DESCRIPTION
**Pull request by tinatian**
We do not need to use the patched version third party libs to exclude jdk9 class to fix the startup issue on JBoss and Wildfly like https://issues.liferay.com/browse/LPS-89886, as we added shield container which loaded third party jars in shield container class loader instead of app server's class loader.

We can not remove the third party patched jar now as they are using by 7.3 and earlier.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@zhangyan0701 Can you check the new results here when they come in?

**Comment by zhangyan0701** [comment]
All the failures are unrelated.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
Shouldn't we remove those third party modules for the patched lib? Any reason to continue keeping them?

**Comment by tinatian** [comment]
@shuyangzhou I thought it would be needed for 7.3 and earlier which we do not backport shield container changes to. If not, please let me know. I will remove those modules

**Comment by shuyangzhou** [comment]
@tinatian those third-party modules exist in older branches, right? If so, we can wipe them from master once master does not reference them any more. In case we need to change them for re-publication, that can be done from older branches directly.

**Comment by tinatian** [comment]
@shuyangzhou No, I believe we only have one copy of third party libraries in master.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/110008

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
