### PR TITLE
[Method References] LPS-161443 Convert method references to field references in classes extends BasePortletConfigurationIcon

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang ,I convert method references to field references in classes extends BasePortletConfigurationIcon

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results when they finish ? Thanks!

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
@W2jx Code looks good to me, wait for QA to scan test results.

Tina

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122527

**Pull request closed without merging**
