### PR TITLE
[Spring Beans] LPS-200292 Merge IdenticalPhoneNumberFormatImpl into Util and move to portal-impl 

### PR DESCRIPTION
**Pull request by W2jx**
According to https://github.com/brianchandotcom/liferay-portal/pull/144973#issuecomment-1845270550， resend and modify the package from `com.liferay.portal.util` to `com.liferay.portal.format.util` in commit 33506db8516990994a398bf5498eda470ec759f2.

cc @dantewang

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(12/12 14:24)

**Comment by dantewang** [comment]
@W2jx The package adjust is the only change right?

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Comment by W2jx** [comment]
> @W2jx The package adjust is the only change right?

Hi, @dantewang , yes, it is the only change.

**Comment by W2jx** [comment]
ci:forward:force

**Pull request closed without merging**
