### PR TITLE
[Replace Non-Blocking Usage] LPS-199566 Replace non-blocking ServiceProxyFactory usages in package staging

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
@W2jx failure on startup:

```
[beanshell] 2023-10-24 03:31:53.573 WARN  [main][PortalInstanceLifecycleListenerManagerImpl:195] Unable to register portal instance {"mvccVersion": 0, "companyId": 10253, "userId": 0, "userName": "", "createDate": "Thu Jun 15 00:00:00 GMT 2017", "modifiedDate": "Thu Jun 15 00:00:00 GMT 2017", "webId": "liferay.com", "mx": "liferay.com", "homeURL": "", "logoId": 0, "maxUsers": 0, "active": true, "name": "Liferay", "legalName": "", "legalId": "", "legalType": "", "sicCode": "", "tickerSymbol": "", "industry": "", "type": "", "size": "", "indexNameCurrent": "", "indexNameNext": ""}
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.exportimport.kernel.staging.StagingUtil.getLiveGroupId(StagingUtil.java:175) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.service.impl.WorkflowDefinitionLinkLocalServiceImpl.hasWorkflowDefinitionLink(WorkflowDefinitionLinkLocalServiceImpl.java:235) ~[portal-impl.jar:?]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
[beanshell] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41) ~[portal-impl.jar:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-27/test-portal-acceptance-pullrequest(master)/10457/functional-upgrade-tomcat90-mariadb102-jdk8/0/16/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
