### PR TITLE
[Remove Blocking usages]LPS-187880 portal-kernel | SettingsFactoryUtil

### PR DESCRIPTION
**Pull request by JanisZhang**
previous：https://github.com/liferay-core-infra/liferay-portal/pull/5285

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139528

**Pull request closed without merging**
