### PR TITLE
[TS] LPS-190994

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found.

the bug is not reproducible with your changes.

**Comment by tinatian** [comment]
@marianoalvarosaiz Please mark your pull with [TS] if it is an issue from customer, so that we will prioritize the review.

@brunofalc A pull not marked with [TS].

Thanks.
Tina.

**Comment by tinatian** [comment]
@marianoalvarosaiz I do not understand why you did https://github.com/liferay-core-infra/liferay-portal/pull/5140/commits/d365ec083e077ff7a369bd4958d308cbf880b98a. 

You will add logic to catch the IllegalArgumentException anyway in SchedulerEngineHelperImpl, why bother to make it return null when interval=0?

Tina

**Comment by tinatian** [comment]
@marianoalvarosaiz Interval 0 is NOT a valid value in our context.

Interval 0 is a valid value based on quartz document (http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/tutorial-lesson-05.html)
> The repeat interval property must be zero, or a positive long value, and represents a number of milliseconds. Note that a repeat interval of zero will cause ‘repeat count’ firings of the trigger to happen concurrently (or as close to concurrently as the scheduler can manage).

While, in our context, the ‘repeat count’ is always 0, which means Interval 0 will not trigger any job, it should not be a valid value if you can not trigger a job.

**Comment by marianoalvarosaiz** [comment]
@tinatian 
> While, in our context, the ‘repeat count’ is always 0, which means Interval 0 will not trigger any job, it should not be a valid value if you can not trigger a job.

And it will not trigger any job. What I meant with valid is that users used 0 to disable the job execution. If they still do that and see an exception (if traces are activated) they will open support tickets asking why the code is now throwing an exception.

I wanted to differentiate between negative values, null time unit and cron expressions that are something that we should warn the customer against and zero value that is an alternative for users to avoid jobs execution.

Do you think we should warn 0 interval? Do you want me to trace 0 with a different level (INFO)?

**Comment by tinatian** [comment]
@marianoalvarosaiz So if zero value that is an alternative for users to avoid jobs execution for those using simple trigger, you will also need to define a value to disable job execution for corn trigger, or else they are not consistent.

Also, you need to modify the descriptions for each configuration to show people the information that 0 is to disable or the corn value to disable.

My question is : is there really a customer want to do that?

**Comment by marianoalvarosaiz** [comment]
@tinatian 

> My question is : is there really a customer want to do that?

They want to disable jobs like the ones that Liferay provides Out of the Box,like:

```
staging.system.event.check.interval=24
announcements.entry.check.interval=15
trash.entry.check.interval=60
```

Or others configurable through system settings.

So,their concern is that right now they cannot disable Liferay provided jobs (besides blacklisting the component). And all these configurable jobs are interval ones, so as far as I know no customer has expressed concerns with cron triggers, since if the want to disable them forever is enough if they don't deploy their own component.

You're right that it should be documented. Right now is a de facto standard to use 0 to disable (it's even documented,https://help.liferay.com/hc/es/articles/360059333911-Stopping-scheduled-tasks-in-Liferay), but it doesn't appear explicitly in the properties for example.

Do you want me to document it as part of this pull? Or do you want me to document it in another LPS?

**Comment by tinatian** [comment]
@marianoalvarosaiz 

> Right now is a de facto standard to use 0 to disable (it's even documented,https://help.liferay.com/hc/es/articles/360059333911-Stopping-scheduled-tasks-in-Liferay), but it doesn't appear explicitly in the properties for example.

The linked document is not in English, I can not understand it. It does not seem like our official document. So I guess using 0 to disable a scheduled task is a suggested solution to the issue the document described, not that we already have a document saying setting 0 will disable, right?

Tina

**Comment by tinatian** [comment]
@marianoalvarosaiz Please resend according to https://github.com/liferay-core-infra/liferay-portal/pull/5296#issuecomment-1684497084

Thanks
Tina.

**Pull request closed without merging**
