### PR TITLE
[TS] LPS-157252

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-157252

Follow-up from https://github.com/liferay-core-infra/liferay-portal/pull/1070.

This new solution includes an edge case fix where the control panel cannot have it's language translated.  By reading in the session locale, we can now adjust the locale of the given page if needed.

Original message:

> In the scenario where the user is requesting their default language, the portal and user default language is the same, but the current virtualHost's default language is different, then the portal will still provide the URL without any language code.  This is because the portal is not taking into account the virtualHost's default language when (not) setting the i18nPath to the requested language.  Further, having a virtualHost default language works against the `LOCALE_PREPEND_FRIENDLY_URL_STYLE` 3 (which is the default value) because now the specified virtualHost (without languageId in the URL) only points to one language, instead of any available language.
> 
> With my changes, the portal now considers if the virtualHost has a default language, and will include a `i18nPath` value if the requested language is different.
> 
> Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
re-running acceptance because many tests were aborted.

**Comment by dantewang** [comment]
@ChrisKian The logic is modified and moved to a new method in one commit. This makes it hard for us to identify what is changed. Could you split the commits to separate the fix and the SF (extracting to new method)? Also, please add a unit/integration test case for the issue if it's possible.

**Review by dantewang — CHANGES_REQUESTED** [review]
Please see my comment and update, thanks!

**Comment by crodriguezy** [comment]
Hey @ChrisKian , thanks for this follow-up.
I've been doing some tests and found an incorrect behaviour using the virtual host (I didn't reproduce it accessing directly by localhost):

1. Go to test.example.com (the site is in Spanish)
2. Go to Site Builder -> Pages. Change to English through the info message: the language is changed (ok).
3. Add a new content page 'test'
4. From Site Builder -> Pages, click on 'test' edit option -> A Not Found error is thrown.

Do you think it might be caused by these changes?

Thank you.

**Comment by ChrisKian** [comment]
Hey @crodriguezy,
This issue you mention isn't _**caused**_ by my changes, but rather **_uncovered_** by them.

Prior to my changes, step 2 of your steps wouldn't be possible whatsoever.

With my changes, we now allow the session locale to be set to English.  Once set to English, the portal will attempt to retrieve English pages when possible.  When you reach step 4, the user is redirected to `test.example.com/en/test`, which is invalid because `/en/` is not a valid locale code to use on the test site's **_pages_** (it's only valid for the control panel).  If you click on `test` in the navigation bar, the page is redirected to `test.example.com/test`, which works fine.

I'll see if I can easily fix this new issue and include it in the new PR.

**Comment by crodriguezy** [comment]
Ok @ChrisKian , thanks for clarifying! :)

**Comment by ChrisKian** [comment]
Thanks @crodriguezy, that works!

I've modified the branch and resent the PR here: https://github.com/liferay-core-infra/liferay-portal/pull/1175

**Pull request closed without merging**
