### PR TITLE
[TS] LPD-31842 | 7-23

### PR DESCRIPTION
**Pull request by dantewang**
https://liferay.atlassian.net/browse/LPD-31842

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:search

**Comment by dantewang** [comment]
ci:test:search

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:search

**Comment by tinatian** [comment]
ci:report:43496750

**Comment by tinatian** [comment]
ci:report:43511536

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 43496750.
> 
> Job Link: [generate-testray-csv](https://test-1-35.liferay.com/job/generate-testray-csv/96/)
> 
> Testray CSV Link: [testray-results-43496750.csv](https://test-1-35.liferay.com/userContent/jobs/generate-testray-csv/builds/96/testray-results-43496750.csv)

No unique failure reported

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 43511536.
> 
> Job Link: [generate-testray-csv](https://test-1-35.liferay.com/job/generate-testray-csv/97/)
> 
> Testray CSV Link: [testray-results-43511536.csv](https://test-1-35.liferay.com/userContent/jobs/generate-testray-csv/builds/97/testray-results-43511536.csv)

No unique failure reported

**Comment by dantewang** [comment]
ci:report:43897546

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 43897546.
> 
> Job Link: [generate-testray-csv](https://test-1-6.liferay.com/job/generate-testray-csv/117/)
> 
> Testray CSV Link: [testray-results-43897546.csv](https://test-1-6.liferay.com/userContent/jobs/generate-testray-csv/builds/117/testray-results-43897546.csv)

The unique ones seem to be flaky. Re-trigger.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:44150870

**Comment by dantewang** [comment]
@tinatian None of the unique ones in the second relevant run appeared in the unique section of the first run. I think they are just unstable test results.

@JerryAdrianoo @victorhcunha Could you run a startup comparison, and a comparison with the Login and DL test cases? Thanks!

**Comment by JerryAdrianoo** [comment]
Hey @dantewang  for more details from this test, see: [spreadsheet](https://docs.google.com/spreadsheets/d/1N4ltjlHphpwy03ep3agaryEUTdSHmPbN3LhvOkNUEd8/edit?gid=142122455#gid=142122455) 

Branch| Startup Time (ms)(without  default HSQL data)  Cold start | Percent of Average Startup Time Cold Start | Startup Time (ms)(without  default HSQL data) Hot start | Average Startup Time (ms)(without default HSQL data)  Hot start | Percent of Average Startup Time Hot Start | Shutdown Time (ms)(without default HSQL data)   Cold start | Shutdown Time (ms)(without default HSQL data)  Hot start | Average Shutdown Time (ms)(without default HSQL data)  Hot start
-- | -- | -- | -- | -- | -- | -- | -- | --
Before LPD-31842 | **41,994** | | 16,127 | | | **2,511** | 2,033
|  | | | 16,603 | | | | 1,984
|  | | | 16,028 | | | | 1,993
 | | | | 16,490 | | | | 2,000
 | | | | 16,645 |**16,407** | | | 2,042 | **2,009**
-- | -- | -- | -- | -- | -- | -- | --
After LPD-31842 | **42,871** | | 16,015 | | | **2,495** | 2,042
|  | | | 15,964 | | | | 1,906
|  | | | 15,952 | | | | 1,931
|  | | | 16,806 | | | | 1,995
| | |  2.09% | 15,974 |**15,984** |  **-2.58**% | | 1,907 | **1,944**

Everything looks ok, I didn't see any regression with these changes as well; **this variation is expected.**

-------------------------------------------------------------------------------------------------------------------------------------------------------------------

I put the benchmark test results in the same spreadsheet above because it would make the comment unreadable since there are a lot of numbers.
Please let me know if you need something else.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7286

**Pull request closed without merging**
