### PR TITLE
LPS-142278 Remove portal lib dir | 12-15

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
cc @tinatian @vicnate5

**Comment by vicnate5** [comment]
Failures not related.

**Comment by tinatian** [comment]
@dantewang Sorry Dante, you need to rebase one more time.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
