### PR TITLE
[Spring Beans] LPS-204730 Move DummyUserGroupMembershipPolicy to module: portal-security-membership-policy-impl

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:security

**Comment by julschong** [comment]
relevant no unique failure

**Comment by JanisZhang** [comment]
Hey Julius, just want to let you know this class will be eliminated by https://github.com/liferay-core-infra/liferay-portal/pull/6414, based on:https://github.com/liferay-core-infra/liferay-portal/pull/6124#issuecomment-1874427016

**Pull request closed without merging**
