### PR TITLE
[Remove Stream/Optional usage] LPS-177385 module: portal-workflow-metrics-service

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend, thanks!

previous: https://github.com/liferay-core-infra/liferay-portal/pull/3740

https://issues.liferay.com/browse/LPS-177385

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:workflow-metrics

**Comment by JanisZhang** [comment]
force-pushed. I only change the variable name, append 1 SF commit. No need to re-trigger test.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131290

**Pull request closed without merging**
