### PR TITLE
[Method References 2] LPS-165165 Convert method reference to ServiceTrackerList in class IndexSynchronizerImpl (module portal-search-elasticsearch7-impl)

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by Kvale1733** [comment]
Will rerun relevant along with the search suite after https://github.com/brianchandotcom/liferay-portal/pull/128770 is in upstream as that issue is causing a lot of failures.

**Comment by W2jx** [comment]
Thank you @Kvale1733 , after it is merged, I will re-trigger CI tests.

**Comment by W2jx** [comment]
no conflicts(1/17 17:00)

**Comment by catarineaguiar** [comment]
@W2jx can you rebase and re-run tests suites, please?

Thanks, Cat.

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:search

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
