### PR TITLE
[Component with its own class name as service type] LPS-198622 Cleanup DDMDisplay and DDMDataProviderDisplay interfaces

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-198622

This pull is related to this [changes](https://github.com/liferay-core-infra/liferay-portal/pull/5555#issuecomment-1733919569)

CC: @shuyangzhou

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@MrJohn1911 semver error:

```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/dynamic-data-mapping/dynamic-data-mapping-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.dynamic.data.mapping.util              MAJOR      9.0.0      9.0.0      10.0.0     VERSION INCREASE REQUIRED
     [exec]     	>   interface  com.liferay.dynamic.data.mapping.util.DDMDisplay
     [exec]     		-   method     getPortletId()
     [exec]     			-   access     abstract
     [exec]     			-   return     java.lang.String
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 27.0.0
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-26/test-portal-acceptance-pullrequest(master)/11480/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Review by rafaprax — APPROVED** [review]

**Comment by MrJohn1911** [comment]
Last push fixes SemVer errors

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142334

**Pull request closed without merging**
