### PR TITLE
[TS] LPP-46997 > LPS-166736 upgrade jackson-databind

### PR DESCRIPTION
**Pull request by ces-hongvo**
Hi @dantewang 
This is the update for the PR https://github.com/liferay-core-infra/liferay-portal/pull/2273. Because @Vy-CES is having PTO so I am helping to update this.
I have run ant format-source in portal-imp but there is no update from them.
Could you please review this PR and leave your comments?
Thank you.
CC: @Vy-CES.

### CODE REVIEW

**Comment by dantewang** [comment]
Hi @hongvo2308, thanks for resend. The order of these 2 commits still needs to be adjusted (flipped).

Basically when we upgrade a lib which is used by a lot of modules, we add/update the lib version to `modules/source-formatter.properties`, and run `ant format-source-current-branch` so that SF takes care of the rest.

So the commit to modify `source-formatter.properties` should come first, and the commit for the SFed build.gradle files follows.

**Comment by hongvo2308** [comment]
Hi @dantewang 
Thank you so much for your instructions. I have followed the steps and updated this PR. Please take a look at it.
Thank you.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@yuhai Could you take a look? Should we also update the other 2 jackson libs (jackson-core, jackson-annotations) to 2.13.4 to match jackson-databind?

**Review by dantewang — APPROVED** [review]

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@hongvo2308 No regressions found.

**Comment by yuhai** [comment]
@hongvo2308, resend it to https://github.com/liferay-core-infra/liferay-portal/pull/2331.

**Pull request closed without merging**
