### PR TITLE
LPS-197376 Merge HttpAuthManager interface and impl into Util and move to portal-impl

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong semver error:

```
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.security.auth.http       MAJOR      1.1.0      1.1.0      2.0.0      VERSION INCREASE REQUIRED
     [exec] 	-   class      com.liferay.portal.kernel.security.auth.http.HttpAuthManagerUtil
     [exec] 		-   method     clone()
     [exec] 			-   access     protected
     [exec] 			-   return     java.lang.Object
     [exec] 		-   method     equals(java.lang.Object)
     [exec] 			-   return     boolean
     [exec] 		-   method     finalize()
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     generateChallenge(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse,com.liferay.portal.kernel.security.auth.http.HttpAuthorizationHeader)
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 		-   method     getBasicUserId(javax.servlet.http.HttpServletRequest)
     [exec] 			-   access     static
     [exec] 			-   return     long
     [exec] 		-   method     getDigestUserId(javax.servlet.http.HttpServletRequest)
     [exec] 			-   access     static
     [exec] 			-   return     long
     [exec] 		-   method     getUserId(javax.servlet.http.HttpServletRequest,com.liferay.portal.kernel.security.auth.http.HttpAuthorizationHeader)
     [exec] 			-   access     static
     [exec] 			-   return     long
     [exec] 		-   method     hashCode()
     [exec] 			-   return     int
     [exec] 		-   method     parse(javax.servlet.http.HttpServletRequest)
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.security.auth.http.HttpAuthorizationHeader
     [exec] 		-   method     toString()
     [exec] 			-   return     java.lang.String
     [exec] 	-   interface  com.liferay.portal.kernel.security.auth.http.HttpAuthManager
     [exec] 		-   access     abstract
     [exec] 		-   method     generateChallenge(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse,com.liferay.portal.kernel.security.auth.http.HttpAuthorizationHeader)
     [exec] 			-   access     abstract
     [exec] 			-   return     void
     [exec] 		-   method     getBasicUserId(javax.servlet.http.HttpServletRequest)
     [exec] 			-   access     abstract
     [exec] 			-   return     long
     [exec] 		-   method     getDigestUserId(javax.servlet.http.HttpServletRequest)
     [exec] 			-   access     abstract
     [exec] 			-   return     long
     [exec] 		-   method     getUserId(javax.servlet.http.HttpServletRequest,com.liferay.portal.kernel.security.auth.http.HttpAuthorizationHeader)
     [exec] 			-   access     abstract
     [exec] 			-   return     long
     [exec] 		-   method     parse(javax.servlet.http.HttpServletRequest)
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.portal.kernel.security.auth.http.HttpAuthorizationHeader
     [exec] [Baseline Warning] Bundle Version Change Recommended: 127.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-40/test-portal-acceptance-pullrequest(master)/6619/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
updated for semver

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by shuyangzhou** [comment]
@julschong please rebase, thanks!

**Comment by julschong** [comment]
rebased, rerunning test

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by julschong** [comment]
added breaking change messages

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142559

**Pull request closed without merging**
