### PR TITLE
LPS-185138 Convert the Optional Dynamic Greedy references to ServiceT…

### PR DESCRIPTION
**Pull request by tinatian**
…racker in class UpgradeRecorder. We can not use Snapshot here as it will make ReleaseManagerImpl activation happen when the service is retrieved which is too late and finally cause "missing default store error" while running upgrade client tool.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:startup

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
