### PR TITLE
LPS-172441 upgrade snakeyaml to 2.0

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This is for ticket https://issues.liferay.com/browse/LPS-172441.
Thanks for checking!

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 Found a compile issue in rest-builder
```
[exec] /opt/dev/projects/github/liferay-portal/modules/util/portal-tools-rest-builder/src/main/java/com/liferay/portal/tools/rest/builder/internal/yaml/YAMLUtil.java:74: error: constructor Representer in class org.yaml.snakeyaml.representer.Representer cannot be applied to given types;
     [exec] 		Representer representer = new Representer();
     [exec] 		                          ^
     [exec]   required: org.yaml.snakeyaml.DumperOptions
     [exec]   found: no arguments
     [exec]   reason: actual and formal argument lists differ in length
     [exec] /opt/dev/projects/github/liferay-portal/modules/util/portal-tools-rest-builder/src/main/java/com/liferay/portal/tools/rest/builder/internal/yaml/YAMLUtil.java:80: error: incompatible types: java.lang.Class<com.liferay.portal.tools.rest.builder.internal.yaml.config.ConfigYAML> cannot be converted to org.yaml.snakeyaml.LoaderOptions
     [exec] 		Constructor configYAMLConstructor = new Constructor(ConfigYAML.class);
     [exec] 		                                                              ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/util/portal-tools-rest-builder/src/main/java/com/liferay/portal/tools/rest/builder/internal/yaml/YAMLUtil.java:98: error: incompatible types: java.lang.Class<com.liferay.portal.tools.rest.builder.internal.yaml.openapi.OpenAPIYAML> cannot be converted to org.yaml.snakeyaml.LoaderOptions
     [exec] 		Constructor openAPIYAMLConstructor = new Constructor(OpenAPIYAML.class);
     [exec] 		                                                                ^
     [exec] Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
     [exec] 3 errors
     [exec] 
     [exec] > Task :util:portal-tools-rest-builder:compileJava FAILED
 ```
 [Log](https://testray.liferay.com/reports/production/logs/2023-03/test-1-27/test-portal-acceptance-pullrequest(master)/7159/modules-compile-jdk8/0/13/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
