### PR TITLE
[Component with its own class name as service type ] LPS-193663 Refactor Registry classes from search module

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Review by rafaprax — APPROVED** [review]

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by GabrielHenriquedev** [comment]
ci:test:sf

**Comment by GabrielHenriquedev** [comment]
ci:test:sf

**Comment by GabrielHenriquedev** [comment]
ci:test:sf

**Pull request closed without merging**
