### PR TITLE
[Replace Non-Blocking Usage] LPS-199402

### PR DESCRIPTION
**Pull request by JanisZhang**
Fixed regression and resend. Thanks.
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5814
https://liferay.atlassian.net/browse/LPS-199402

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142485

cc @shuyangzhou

**Pull request closed without merging**
