### PR TITLE
LPS-175643 Remove Stream usages for module: commerce-discount-service

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from #3476

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:stop

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131250

**Pull request closed without merging**
