### PR TITLE
[Reflection] LPD-15275 Use StagedLayoutSet#getLayoutSet instead 
of reflection in LayoutSetModelAdapterBuilder

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:report:2528480319

**Comment by julschong** [comment]
ci:report:2529167429

**Comment by julschong** [comment]
rerun relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:report:2529361893

**Comment by julschong** [comment]
no regression found

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
