### PR TITLE
[Bug Fix]LPS-39084

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by tinatian** [comment]
@koor4356 Please help me scan test results.

Thanks.
Tina.

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
@tinatian, this looks good. 
But no enough results from Microsoft SQL Server 2019 and Oracle Database 19.3 tests run. I wonder if we should re-run this.

**Comment by koor4356** [comment]
@tinatian 
I am going to re-running this. I just want to make sure no bug gets in. Thanks!

**Comment by koor4356** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@koor4356 Please check the new results

**Comment by koor4356** [comment]
@tinatian 
Everything looks good except this error from the stable test, can you a look? A batch that is failing "portal-license-smoke-jdk8/0". I am not sure if it is related to this PR, but I am not seeing this from the upstream either. 

`[parallel] com.liferay.portal.kernel.repository.UndeployedExternalRepositoryException: Unable to load external repository class com.liferay.portal.repository.liferayrepository.LiferayRepository because its plugin is not deployed
 [parallel] 	at com.liferay.portal.repository.RepositoryFactoryImpl.getRepositoryFactory(RepositoryFactoryImpl.java:72) ~[portal-impl.jar:?]
 [parallel] 	at com.liferay.portal.repository.RepositoryFactoryImpl.createLocalRepository(RepositoryFactoryImpl.java:39) ~[portal-impl.jar:?]
 [parallel] 	at com.liferay.portal.repository.RepositoryProviderImpl.getLocalRepository(RepositoryProviderImpl.java:268) ~[portal-impl.jar:?]
 [parallel] 	at com.liferay.portlet.documentlibrary.service.impl.DLAppLocalServiceImpl.getLocalRepository(DLAppLocalServiceImpl.java:1769) ~[portal-impl.jar:?]
 [parallel] 	at com.liferay.portlet.documentlibrary.service.impl.DLAppLocalServiceImpl.fetchFileEntryByExternalReferenceCode(DLAppLocalServiceImpl.java:691) ~[portal-impl.jar:?]
 [parallel] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
 [parallel] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
 [parallel] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
 [parallel] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
 [parallel] 	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:66) ~[portal-kernel.jar:?]
 [parallel] 	at com.sun.proxy.$Proxy737.fetchFileEntryByExternalReferenceCode(Unknown Source) ~[?:?]
 [parallel] 	at com.liferay.document.library.kernel.service.DLAppLocalServiceWrapper.fetchFileEntryByExternalReferenceCode(DLAppLocalServiceWrapper.java:542) ~[portal-kernel.jar:?]
 [parallel] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
 [parallel] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
 [parallel] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
 [parallel] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
 [parallel] 	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:66) ~[portal-kernel.jar:?]
 [parallel] 	at com.sun.proxy.$Proxy738.fetchFileEntryByExternalReferenceCode(Unknown Source) ~[?:?]
 [parallel] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
 [parallel] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
 [parallel] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
 [parallel] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
 [parallel] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
 [parallel] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69) ~[portal-impl.jar:?]
 [parallel] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
 [parallel] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
 [parallel] 	at com.sun.proxy.$Proxy123.fetchFileEntryByExternalReferenceCode(Unknown Source) ~[?:?]
 [parallel] 	at com.liferay.commerce.product.internal.model.listener.PortalInstanceLifecycleListenerImpl.portalInstanceRegistered(PortalInstanceLifecycleListenerImpl.java:90) ~[?:?]
 [parallel] 	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl.registerCompany(PortalInstanceLifecycleListenerManagerImpl.java:158) ~[?:?]
 [parallel] 	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl.lambda$addPortalInstanceLifecycleListener$0(PortalInstanceLifecycleListenerManagerImpl.java:105) ~[?:?]
 [parallel] 	at com.liferay.portal.service.impl.CompanyLocalServiceImpl.forEachCompany(CompanyLocalServiceImpl.java:510) ~[portal-impl.jar:?]
 [parallel] 	at sun.reflect.GeneratedMethodAccessor284.invoke(Unknown Source) ~[?:?]
 [parallel] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
 [parallel] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
 [parallel] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
 [parallel] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
 [parallel] 	at com.sun.proxy.$Proxy47.forEachCompany(Unknown Source) ~[?:?]
 [parallel] 	at `

https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/21087/AXIS_VARIABLE=0/consoleText

**Comment by koor4356** [comment]
@tinatian 
This PR is good to go. Thanks!

**Comment by vicnate5** [comment]
We identified that the failure could not be related to this PR.

**Comment by tinatian** [comment]
@shuyangzhou This is good to go.

Tina

**Comment by shuyangzhou** [comment]
Update on slave node will trigger NPE on master node, due to the cluster methods are not static and using non-static fields.
@tinatian will redo the impl to use identifiable service.

**Comment by shuyangzhou** [comment]
ci:close

**Comment by tinatian** [comment]
Resend at https://github.com/liferay-core-infra/liferay-portal/pull/164

**Pull request closed without merging**
