### PR TITLE
[TS] LPS-190994

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:clustering

**Comment by Kvale1733** [comment]
@marianoalvarosaiz No regressions found. Testing passed following the ticket steps.

Only found a semver issue
```
  [exec] > Task :apps:blogs:blogs-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.blogs.configuration                    CHANGED    1.3.1      1.3.1      1.3.2      VERSION INCREASE REQUIRED
     [exec] 	~   interface  com.liferay.blogs.configuration.BlogsConfiguration
     [exec] 		~   method     entryCheckInterval()
     [exec] 			~   annotated  aQute.bnd.annotation.metatype.Meta$AD
     [exec] 				+   property   description='entry-check-interval-description'
     [exec] 		~   method     linkbackJobInterval()
     [exec] 			~   annotated  aQute.bnd.annotation.metatype.Meta$AD
     [exec] 				+   property   description='linkback-job-interval-description'
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.blogs.api-16.2.2.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.blogs.api/16.2.1/a0f6dee1a287b64100f0b62b7119b639fd5ae0be/com.liferay.blogs.api-16.2.1.jar
```

```
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.commerce.term.configuration            CHANGED    1.0.0      1.0.0      1.0.1      VERSION INCREASE REQUIRED
     [exec] 	~   interface  com.liferay.commerce.term.configuration.CommerceTermEntryConfiguration
     [exec] 		~   method     checkInterval()
     [exec] 			~   annotated  aQute.bnd.annotation.metatype.Meta$AD
     [exec] 				+   property   description='check-interval-in-minutes-description'
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.commerce.term.api-6.2.2.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.commerce/com.liferay.commerce.term.api/6.2.1/47e1d27d94a55e368e5efa453f65d461fd1d1fad/com.liferay.commerce.term.api-6.2.1.jar

Etc.. for every modified configuration

[Full Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-37/test-portal-acceptance-pullrequest(master)/13855/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
@marianoalvarosaiz 
1. For https://github.com/liferay-core-infra/liferay-portal/pull/5296/commits/7a906cb45b7910728b04ba83f9c4aad7d7c18a84, please add unit test rule, and make it 100% covered by adding CodeCoverageAssertor.
2. For https://github.com/liferay-core-infra/liferay-portal/pull/5296/commits/6fe73fdb5ac8839940416b4aefefb30aa6029c55, this is not consistent with what you want "zero interval is valid". If 0 is valid, you should create a TriggerConfiguration from it rather than a null. Please move the checking logic in https://github.com/liferay-core-infra/liferay-portal/pull/5296/commits/6fe73fdb5ac8839940416b4aefefb30aa6029c55 and https://github.com/liferay-core-infra/liferay-portal/pull/5296/commits/03f91c125a29d157619d47fe55a840958ab492de to SchedulerEngineHelperImpl.
3. I only see you updated the document for interval=0, but not anything for corn trigger, please also update doc for corn trigger.

Please resend.

Thanks.
Tina.

**Comment by marianoalvarosaiz** [comment]
see https://github.com/liferay-core-infra/liferay-portal/pull/5356

**Pull request closed without merging**
