### PR TITLE
[Static reference] LPS-181530 Remove method reference by using snapshot in modules staging-taglib, template-taglib, trash-taglib

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:staging

**Comment by W2jx** [comment]
ci:test:echo

**Comment by W2jx** [comment]
no conflicts(4/18 9:28)

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(4/19 8:03)

**Comment by W2jx** [comment]
no conflicts(4/20 7:56)

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
