### PR TITLE
LPS-138411

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Updated as discussed in https://github.com/liferay-core-infra/liferay-portal/pull/918 and  https://github.com/liferay-core-infra/liferay-portal/pull/1003.
After discussionin https://github.com/liferay-core-infra/liferay-portal/pull/845#discussion_r888422958, Kyle has helped me to check the bugs in https://issues.liferay.com/browse/LPS-81724 with the unpatched updated version, and the bugs cannot be reproduce.
This is for ticket https://issues.liferay.com/browse/LPS-138411.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
No regressions found. Only formatting issue.

**Comment by jeffwu0724** [comment]
> No regressions found. Only formatting issue.

@catarineaguiar thanks for checking! May I ask if this formatting issue related to my PR, please?🤔

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@jeffwu0724 Hi Jeff, is not related.

**Comment by jeffwu0724** [comment]
update the commit messages only, didn't make changes to the code

**Comment by jeffwu0724** [comment]
Hey @tinatian , 

I have updated the commit message to "LPS-138411 - update jsoup to version 1.15.1, and avoid using patch 1.10.2.LIFERAY-PATCHED-3. All three versions of this patch is to fix the same ticket https://issues.liferay.com/browse/LPS-81724, and this issue has been fixed in version 1.15.1, and cannot reproduce with the new version 1.15.1."
Please let me know if there is anything else I can improve.
Thanks for checking.

Jeff

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by jeffwu0724** [comment]
rebased and fixed the code conflict in "lib/versions-complete.xml" by auto generate again.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/120556

**Pull request closed without merging**
