### PR TITLE
[Component with its own class name as service type] LPS-198452 Refactor DeepPaginationConfigurationWrapper component

### PR DESCRIPTION
**Pull request by Valmir-unicap**
- Ticket: https://liferay.atlassian.net/browse/LPD-8521

- Result of performance test from AssetPublisher: https://github.com/Valmir-unicap/liferay-portal/pull/84 (No regression found)

- Correction of: https://github.com/liferay-core-infra/liferay-portal/pull/6184

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:search

**Review by dantewang — APPROVED** [review]

**Comment by Valmir-unicap** [comment]
ci:report:2543261594

**Comment by Valmir-unicap** [comment]
No regression found!

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
