### PR TITLE
[Remove Stream/Optional usage] LPS-178046 portal-workflow-rest-test

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-178046

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:help

**Comment by JanisZhang** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131470

**Pull request closed without merging**
