### PR TITLE
[FileInstall]LPS-144496

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou Just rebased to fix baseline issue, this pull is good to go.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113127

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
