### PR TITLE
Lpd 20946 9 8 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
ci:test:object

**Comment by tinatian** [comment]
ci:test:startup

**Comment by tinatian** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:https://github.com/liferay-core-infra/liferay-portal/commit/5106488d8cbc5acc32317c841397b3199b218688

**Comment by dantewang** [comment]
ci:report:5106488

**Comment by dantewang** [comment]
ci:report:5092902

object

**Comment by dantewang** [comment]
ci:report:5087619

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 5092902.
> 
> Job Link: [generate-testray-csv](https://test-1-3.liferay.com/job/generate-testray-csv/128/)
> 
> Testray CSV Link: [testray-results-5092902.csv](https://test-1-3.liferay.com/userContent/jobs/generate-testray-csv/builds/128/testray-results-5092902.csv)

- `LocalFile.ObjectSalesforce#AssertCRUDWithCreatedStandardObject`: **Failing on other PR or upstream runs, with exact same portal side error, and functional test error with only different timestamps/session IDs, etc.**
- `LocalFile.ObjectExportImport#CanImportSameObjectMoreThanOnce`: **Failing on other PR or upstream runs**
- `LocalFile.ObjectPersonalData#CanAnonymizeObjectEntries` & `LocalFile.ObjectPersonalData#CanDeleteObjectEntries`: **Failing on other PRs or upstream runs from Sep 4**
-

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: [5087619](https://github.com/liferay-core-infra/liferay-portal/commit/50876191ef6d7a468a0412d898740ffcaace7f76).
> 
> Job Link: [generate-testray-csv](https://test-1-34.liferay.com/job/generate-testray-csv/177/)
> 
> Testray CSV Link: [testray-results-5087619.csv](https://test-1-34.liferay.com/userContent/jobs/generate-testray-csv/builds/177/testray-results-5087619.csv)

@tinatian We still get some upgrade errors like https://testray.liferay.com/#/project/35392/routines/45357/build/5087619/case-result/5087782/history, all the recorded failures are from this PR. There is `NoSuchResourceActionException` in the log.

**Comment by tinatian** [comment]
ci:report:5086213

**Comment by tinatian** [comment]
ci:report:5082387

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7414

**Pull request closed without merging**
