### PR TITLE
[PortalInstances-initCompany()]Lps 200558 11 14

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-200558

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:clustering

**Comment by Kvale1733** [comment]
@slnn Many objects integration tests failed due to the following such as com.liferay.object.service.test.ObjectFieldLocalServiceTest

```
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/service/test/ObjectFolderLocalServiceTest.java:153: error: method initCompany in class com.liferay.portal.util.PortalInstances cannot be applied to given types;
[beanshell]      [exec] 		PortalInstances.initCompany(company);
[beanshell]      [exec] 		               ^
[beanshell]      [exec]   required: com.liferay.portal.kernel.model.Company,boolean
[beanshell]      [exec]   found: com.liferay.portal.kernel.model.Company
[beanshell]      [exec]   reason: actual and formal argument lists differ in length
[beanshell]      [exec] 
[beanshell]      [exec] > Task :apps:object:object-test:compileTestIntegrationJava
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/object/object-test/src/testIntegration/java/com/liferay/object/service/test/ObjectDefinitionLocalServiceTest.java:1322: error: method initCompany in class com.liferay.portal.util.PortalInstances cannot be applied to given types;
[beanshell]      [exec] 		PortalInstances.initCompany(company);
[beanshell]      [exec] 		               ^
[beanshell]      [exec]   required: com.liferay.portal.kernel.model.Company,boolean
[beanshell]      [exec]   found: com.liferay.portal.kernel.model.Company
[beanshell]      [exec]   reason: actual and formal argument lists differ in length
[beanshell]      [exec] Note: Some input files use unchecked or unsafe operations.
[beanshell]      [exec] Note: Recompile with -Xlint:unchecked for details.
[beanshell]      [exec] 2 errors
[beanshell]      [exec] 
```
[Log](https://testray.liferay.com/reports/production/logs/2023-11/test-1-34/test-portal-acceptance-pullrequest(master)/5202/modules-integration-mysql57-jdk8/3/6/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Comment by slnn** [comment]
> ObjectFolderLocalServiceTest

Sorry, my bad,  the usage in ObjectFolderLocalServiceTest was added by LPS-194293:dbd19490ec8497f865a13dee3bbbb9efec06dcb3, I did not notice it when I rebase the recent master head.

**Comment by slnn** [comment]
Please see https://github.com/liferay-core-infra/liferay-portal/pull/6153

**Pull request closed without merging**
