### PR TITLE
LPS-168539 Use BundleUtil.getBundle method instead of repeating its code again and again

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-168539

After implementing the test for [LPS-166969](https://issues.liferay.com/browse/LPS-166969) (see https://github.com/liferay-search/liferay-portal/pull/626) I have realized that we are repeating the BundleUtil.getBundle method code everywhere.

In this PR I am replacing all the repeated code with a direct call to BundleUtil.getBundle

I am also moving the existing BundleUtil class from portal-impl to portal-kernel as @tinatian requested here: https://github.com/liferay-core-infra/liferay-portal/pull/2451#issuecomment-1398751798

This BundleUtil is used from both portal-impl classes and OSGI modules code so I think the best option is to move there.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jorgediaz-lr No regressions found.

**Comment by dantewang** [comment]
Conflicts, please resend.

**Comment by jorgediaz-lr** [comment]
Hi @dantewang 

I have resent here: https://github.com/liferay-core-infra/liferay-portal/pull/3332

**Pull request closed without merging**
