### PR TITLE
[Method References 2] LPS-171231 Convert method reference to ServiceTrackerMap in class MultiLanguageKaleoTaskAssignmentSelector

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4806

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by W2jx** [comment]
Hi @dantewang , I have extracted a common util .

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
no regression found

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136774

**Pull request closed without merging**
