### PR TITLE
LPS-200603 Move GroupModelListener and RoleModelListener to modules

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This ticket is for https://liferay.atlassian.net/browse/LPS-200603.
In this PR, I ove GroupModelListener and RoleModelListener to modules so that we can get rid of the spring-bean
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/6/23 8:26am

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/9/23 9:26am

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/13/23 8:04am

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/14/23 8:37am

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
