### PR TITLE
[Optional Reference] LPS-185533 module portal-search-solr8-impl

### PR DESCRIPTION
**Pull request by haydenzheng314**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4696
Ticket: https://issues.liferay.com/browse/LPS-185533
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by LisztLiszt** [comment]
ci:test:search-solr

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
