### PR TITLE
LPS-143636 Avoid using RolePermissionUtil, UserGroupPermissionUtil directly in modules

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina, Shuyang

Main Task: [LPS-143403](https://issues.liferay.com/browse/LPS-143403)
Sub Task 9: [LPS-143636](https://issues.liferay.com/browse/LPS-143636)
Avoid using RolePermissionUtil, UserGroupPermissionUtil directly in modules

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@kyle-miho Hi Kyle, could you please help me scan the test result?

**Comment by kyle-miho** [comment]
@julschong failures are unrelated

**Comment by julschong** [comment]
@tinatian @shuyangzhou
Hi Tina, Shuyang,
Please help review this pull when you get a chance. no related issue is found.
Thank you!
Julius

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
