### PR TITLE
[Optional Reference] LPS-185576 BaseConfigurationFactory

### PR DESCRIPTION
**Pull request by haydenzheng314**
Use dynamic snapshot as talked.
Ticket: https://issues.liferay.com/browse/LPS-185576
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by LisztLiszt** [comment]
ci:test:oauth2

**Comment by Kvale1733** [comment]
@LisztLiszt No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
