### PR TITLE
[Circular dependency]Lps 186384 v2 7 3

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-186384

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:object

**Comment by catarineaguiar** [comment]
@slnn startup error:

```
[beanshell] 2023-07-03 06:04:19.830 INFO  [SystemExecutorServiceUtil-7][BundleSiteInitializer:4709] Invoking line 625 took 1 ms
[beanshell] 2023-07-03 06:04:19.831 INFO  [SystemExecutorServiceUtil-7][BundleSiteInitializer:4709] Invoking line 627 took 0 ms
[beanshell] 2023-07-03 06:04:19.832 INFO  [SystemExecutorServiceUtil-7][BundleSiteInitializer:636] Initialized com.liferay.site.initializer.welcome for group 20119 in 4203 ms
[beanshell] 2023-07-03 06:04:21.334 ERROR [main][BasePersistenceImpl:643] Caught unexpected exception
[beanshell] java.lang.IllegalStateException: No current transaction executor
[beanshell] 	at com.liferay.portal.dao.orm.hibernate.VerifySessionFactoryWrapper._verify(VerifySessionFactoryWrapper.java:136) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.dao.orm.hibernate.VerifySessionFactoryWrapper.openSession(VerifySessionFactoryWrapper.java:101) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.openSession(BasePersistenceImpl.java:637) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.object.service.persistence.impl.ObjectDefinitionPersistenceImpl.findByC_A_S(ObjectDefinitionPersistenceImpl.java:5498) ~[?:?]
[beanshell] 	at com.liferay.object.service.persistence.impl.ObjectDefinitionPersistenceImpl.findByC_A_S(ObjectDefinitionPersistenceImpl.java:5402) ~[?:?]
[beanshell] 	at com.liferay.object.service.persistence.impl.ObjectDefinitionPersistenceImpl.findByC_A_S(ObjectDefinitionPersistenceImpl.java:5356) ~[?:?]
[beanshell] 	at com.liferay.object.service.impl.ObjectRelationshipLocalServiceImpl.lambda$_getObjectDefinitions$2(ObjectRelationshipLocalServiceImpl.java:1116) ~[?:?]
[beanshell] 	at com.liferay.portal.service.impl.CompanyLocalServiceImpl.forEachCompanyId(CompanyLocalServiceImpl.java:519) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.service.impl.CompanyLocalServiceImpl.forEachCompanyId(CompanyLocalServiceImpl.java:500) ~[portal-impl.jar:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-07/test-1-26/test-portal-acceptance-pullrequest(master)/10263/functional-tomcat90-mysql57-jdk8/9/9/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
> @slnn startup error:
> 
> ```
> [beanshell] 2023-07-03 06:04:19.830 INFO  [SystemExecutorServiceUtil-7][BundleSiteInitializer:4709] Invoking line 625 took 1 ms
> [beanshell] 2023-07-03 06:04:19.831 INFO  [SystemExecutorServiceUtil-7][BundleSiteInitializer:4709] Invoking line 627 took 0 ms
> [beanshell] 2023-07-03 06:04:19.832 INFO  [SystemExecutorServiceUtil-7][BundleSiteInitializer:636] Initialized com.liferay.site.initializer.welcome for group 20119 in 4203 ms
> [beanshell] 2023-07-03 06:04:21.334 ERROR [main][BasePersistenceImpl:643] Caught unexpected exception
> [beanshell] java.lang.IllegalStateException: No current transaction executor
> [beanshell] 	at com.liferay.portal.dao.orm.hibernate.VerifySessionFactoryWrapper._verify(VerifySessionFactoryWrapper.java:136) ~[portal-impl.jar:?]
> [beanshell] 	at com.liferay.portal.dao.orm.hibernate.VerifySessionFactoryWrapper.openSession(VerifySessionFactoryWrapper.java:101) ~[portal-impl.jar:?]
> [beanshell] 	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.openSession(BasePersistenceImpl.java:637) ~[portal-kernel.jar:?]
> [beanshell] 	at com.liferay.object.service.persistence.impl.ObjectDefinitionPersistenceImpl.findByC_A_S(ObjectDefinitionPersistenceImpl.java:5498) ~[?:?]
> [beanshell] 	at com.liferay.object.service.persistence.impl.ObjectDefinitionPersistenceImpl.findByC_A_S(ObjectDefinitionPersistenceImpl.java:5402) ~[?:?]
> [beanshell] 	at com.liferay.object.service.persistence.impl.ObjectDefinitionPersistenceImpl.findByC_A_S(ObjectDefinitionPersistenceImpl.java:5356) ~[?:?]
> [beanshell] 	at com.liferay.object.service.impl.ObjectRelationshipLocalServiceImpl.lambda$_getObjectDefinitions$2(ObjectRelationshipLocalServiceImpl.java:1116) ~[?:?]
> [beanshell] 	at com.liferay.portal.service.impl.CompanyLocalServiceImpl.forEachCompanyId(CompanyLocalServiceImpl.java:519) ~[portal-impl.jar:?]
> [beanshell] 	at com.liferay.portal.service.impl.CompanyLocalServiceImpl.forEachCompanyId(CompanyLocalServiceImpl.java:500) ~[portal-impl.jar:?]
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2023-07/test-1-26/test-portal-acceptance-pullrequest(master)/10263/functional-tomcat90-mysql57-jdk8/9/9/jenkins-console.txt.gz?authuser=0)

Thank @catarineaguiar for catching this!  Will fix and resend.

**Pull request closed without merging**
