### PR TITLE
Lpd 17343 performance fix

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@pei-jung Could you please trigger any ci test needed for this pull?

Thanks.
Tina.

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
Thanks for the review @tinatian!

**Comment by pei-jung** [comment]
ci:stop

**Comment by pei-jung** [comment]
Fixed compile error and resent as https://github.com/liferay-core-infra/liferay-portal/pull/6754

**Comment by pei-jung** [comment]
ci:close

**Pull request closed without merging**
