### PR TITLE
[TS] LPS-141588

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This is a followup of https://github.com/liferay-core-infra/liferay-portal/pull/67 after adressing the latest changes recommended in https://issues.liferay.com/browse/PTR-2723?focusedCommentId=2578713&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2578713.

Could you please review it?

Thanks in advance, Daniel

\cc @ericyanLr

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@dacousalr Why you have to send two separate pull for a same ticket LPS-141488? Could you please merge them into one?

Thanks.
Tina

**Comment by dacousalr** [comment]
Hi @tinatian,

Sorry for the possible confusion. I have not split this PR. I have only resend #67 in order to relaunch the ci:test:sf task.

I have also closed #67, which I forgot to do yesterday.

Best,
Daniel

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@koor4356 Can you check these results?

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
@dacousalr @tinatian @vicnate5,
Everything looks good except the error below. I am not sure if it is related to this PR. Can you take a look? It is only occurring on Tomcat 9.0 + IBM DB2 11.1.
` create unique index IX_943E0A56 on CommerceSubscriptionEntry (uuid_[$COLUMN_LENGTH:75$], groupId);
 [parallel] 	at com.liferay.portal.spring.extender.internal.upgrade.InitialUpgradeExtender$InitialUpgradeStep.upgrade(InitialUpgradeExtender.java:240) ~[?:?]
 [parallel] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor$UpgradeInfosRunnable.run(UpgradeExecutor.java:230) ~[?:?]
 [parallel] 	at com.liferay.portal.output.stream.container.internal.OutputStreamContainerFactoryTrackerImpl.runWithSwappedLog(OutputStreamContainerFactoryTrackerImpl.java:134) ~[?:?]
 [parallel] 	at com.liferay.portal.upgrade.internal.executor.SwappedLogExecutor.execute(SwappedLogExecutor.java:51) ~[?:?]
 [parallel] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.executeUpgradeInfos(UpgradeExecutor.java:158) ~[?:?]
 [parallel] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.execute(UpgradeExecutor.java:118) ~[?:?]
 [parallel] 	at com.liferay.portal.upgrade.internal.release.ReleaseManagerImpl$UpgradeInfoServiceTrackerMapListener.keyEmitted(ReleaseManagerImpl.java:364) ~[?:?]
 [parallel] 	at com.liferay.portal.upgrade.internal.release.ReleaseManagerImpl$UpgradeInfoServiceTrackerMapListener.keyEmitted(ReleaseManagerImpl.java:350) ~[?:?]
 [parallel] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$DefaultEmitter.emit(ServiceTrackerMapImpl.java:209) ~[com.liferay.osgi.service.tracker.collections.jar:?]
 [parallel] 	at com.liferay.osgi.service.tracker.collections.map.PropertyServiceReferenceMapper.map(PropertyServiceReferenceMapper.java:50) ~[com.liferay.osgi.service.tracker.collections.jar:?]
 [parallel] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerMapImpl.java:241) ~[com.liferay.osgi.service.tracker.collections.jar:?]
 [parallel] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerMapImpl.java:229) ~[com.liferay.osgi.service.tracker.collections.jar:?]
 [parallel] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:891) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:487) ~[org.eclipse.osgi.jar:?]
 [parallel] 	at org.apache.felix.dm.impl.ComponentImpl.registerService(ComponentImpl.java:1566) ~[?:?]
 [parallel] 	at org.apache.felix.dm.impl.ComponentImpl.performTransition(ComponentImpl.java:1235) ~[?:?]
 [parallel] 	at org.apache.felix.dm.impl.ComponentImpl.handleChange(ComponentImpl.java:1166) ~[?:?]
 [parallel] 	at org.apache.felix.dm.impl.ComponentImpl.handleAdded(ComponentImpl.java:1337) ~[?:?]
 [parallel] 	at org.apache.felix.dm.impl.ComponentImpl.lambda$handleEvent$6(ComponentImpl.java:565) ~[?:?]
 [parallel] 	at org.apache.felix.dm.impl.DispatchExecutor.runTask(DispatchExecutor.java:182) ~[?:?]
 [parallel] 	at org.apache.felix.dm.impl.DispatchExecutor.run(DispatchExecutor.java:165) ~[?:?]
 [parallel] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_121]
 [parallel] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_121]
 [parallel] 	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_121]
 [parallel] Caused by: com.liferay.portal.kernel.upgrade.UpgradeException: Bundle com.liferay.commerce.service_11.0.42 [689] has invalid content in indexes.sql:`

https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1590954142&testrayRunId=1590956623

**Comment by vicnate5** [comment]
This is a random error I have seen before on DB2, not related to this change. @tinatian

**Comment by koor4356** [comment]
Thanks @vicnate5.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/111250

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
