### PR TITLE
[SF] LPS-160079 Add more modules that we already fixed unused reference variables

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This is a follow-up pull to keep maintaining SF properties.

### CODE REVIEW

**Comment by dantewang** [comment]
@JanisZhang Should be good to go as long as SF passes.

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by JanisZhang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
