### PR TITLE
LRQA-78691 Reduce timeout waiting for a Service to improve CI resources since its unlikely the Service will ever get resolved if we wait for a long duration

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-78691

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:stop

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
@Kvale1733 I will analyze the results for this

**Comment by kyle-miho** [comment]
This will improve the timeout time of tests with unresolvable services injected from 17 minutes to 5 minutes

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127492

**Pull request closed without merging**
