### PR TITLE
LPS-148013 Move petra-json-web-service-client to portal-json-web-service-client

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,

Main Task: [Remove apps/petra jars](https://issues.liferay.com/browse/LPS-147928)
Sub Task: [Move petra-json-web-service-client to portal-json-web-service-client](https://issues.liferay.com/browse/LPS-148013)

Thank you!

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by julschong** [comment]
Hi Tina, @tinatian
Could you pelase help me review this pull?
Thank you!

**Comment by tinatian** [comment]
@dantewang Please take this over.

Thanks.
Tina

**Comment by dantewang** [comment]
@tinatian The change is clean. Most of the code are just moved, with a bit of package name update and SF.

Looks good to me.

**Comment by julschong** [comment]
rebased to resolve conflict for:

> lib/versions-complete.xml
> lib/versions.html
> source-formatter.properties

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
rebased to resolve conflict in [f98876d](https://github.com/liferay-core-infra/liferay-portal/pull/879/commits/f98876d7d6cce837173b27fd3e328c8921313e64)

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/119154

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
