### PR TITLE
LPS-160434

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 This pull got reverted before as it caused a blocker https://issues.liferay.com/browse/LPS-167822, could you please trigger any test to make sure it got covered?

Thanks.
Tina

**Comment by tinatian** [comment]
ci:test:help

**Comment by tinatian** [comment]
ci:test:object

**Comment by vicnate5** [comment]
@tinatian I tested the scenario in the ticket by manually upgrading from U74 to this PR. The Object persists, so testing Passed. No regressions found in test results.

**Comment by W2jx** [comment]
see https://github.com/liferay-core-infra/liferay-portal/pull/4357

**Pull request closed without merging**
