### PR TITLE
[Blocker] LPS-199163  Bring back the initial spring wiring for FullNameGeneratorFactory

### PR DESCRIPTION
**Pull request by JanisZhang**
Hello @zhangyan0701,

Would you please review the test results once the test is finished? It has caused an issue https://liferay.atlassian.net/browse/LPS-199163. Thanks.

Verified ok on my local env.

cc @dantewang

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
no regressions found and all 6.1 upgrade tests passed.

**Comment by JanisZhang** [comment]
Thanks! @catarineaguiar

**Comment by dantewang** [comment]
@yuhai Could you take this over? I'm busy with something else and have no time to dig into it. My concern is why this class  can not be obtained during upgrade via `Snapshot`.

**Comment by yuhai** [comment]
@JanisZhang, based on our talk, you will resend it. I am going to close it.

**Comment by dantewang** [comment]
@yuhai What's the root cause?

**Comment by yuhai** [comment]
@dantewang, due to the commit LPS-63698  (720f1e4da10d869695d1a4c8ea9a7680b2237bf8), when DBUpgrader.upgradePortal() executed, the beans of the property [spring.configs](https://github.com/JanisZhang/liferay-portal/blob/LPS-199163/portal-impl/src/com/liferay/portal/tools/DBUpgrader.java#L161) didn't been registerred as osgi services, so the issue happened.

After Janis and I investigation, we want to refer to `MailServiceUtil` and use `PortalBeanLocatorUtil.locate()` when `_fullNameGeneratorSnapshot.get() == null` to fix the issue.

**Pull request closed without merging**
