### PR TITLE
LPS-185138

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou The goal of this pull is to remove the optional reference in UpgradeRecorder, but simply changing it to Snapshot will cause some of the service trackers not started in time, so I did some refactor. Not sure if this is going to affect the changes you made to upgrade, could you please take a look?

Thanks.
Tina

**Comment by LisztLiszt** [comment]
Please see https://github.com/liferay-core-infra/liferay-portal/pull/5268

**Pull request closed without merging**
