### PR TITLE
[Remove Stream/Optional usages: headless/headless-admin-content]Lps 178726

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-178726

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
@slnn resolve conflict and re-run sf, please.

Thanks,
Cat

**Comment by slnn** [comment]
Thank @catarineaguiar ! Will resend.

> @slnn resolve conflict and re-run sf, please.
> 
> Thanks, Cat

**Comment by slnn** [comment]
Resend in https://github.com/liferay-core-infra/liferay-portal/pull/3939

**Pull request closed without merging**
