### PR TITLE
[Disable auto-import-default-references]Lps 164213

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-164213

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Comment by catarineaguiar** [comment]
@slnn all functional tests failed:

```
 LIFERAY_ERROR: Unable to start bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.commerce.service.jar
     [exec]     LIFERAY_ERROR: Declarative Service Unsatisfied Component Checker check result: 
     [exec]     Bundle {id: 354, name: com.liferay.commerce.shipping.origin.locator, version: 4.0.10}
     [exec]     	Declarative Service {id: 1138, name: com.liferay.commerce.shipping.origin.locator.internal.CommerceShippingOriginLocatorImpl, unsatisfied references: 
     [exec]     		{name: _commerceAddressLocalService, target: null}
     [exec]     	}
     [exec]     Bundle {id: 387, name: com.liferay.commerce.product.type.virtual.order.content.web, version: 4.0.25}
     [exec]     	Declarative Service {id: 6728, name: com.liferay.commerce.product.type.virtual.order.content.web.internal.security.resource.permission.CommerceVirtualOrderItemPermission, unsatisfied references: 
     [exec]     		{name: ModelResourcePermission, target: (model.class.name=com.liferay.commerce.product.type.virtual.order.model.CommerceVirtualOrderItem)}
     [exec]     	}
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-30/test-portal-acceptance-pullrequest(master)/4943/functional-smoke-wildfly180-mariadb104-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

all integration tests failed:
e.g. `CTStoreTest`, `ChannelResourceTest`, `CSDiagramSettingTableReferenceDefinitionTest`, etc
```
[beanshell] Waiting for destination (&(destination.name=liferay/commerce_base_price_list)(objectClass=com.liferay.portal.kernel.messaging.Destination))
[beanshell] Waiting for destination (&(destination.name=liferay/commerce_base_price_list)(objectClass=com.liferay.portal.kernel.messaging.Destination))
[beanshell] 2022-10-10 12:28:11.532 ERROR [fileinstall-directory-watcher][DirectoryWatcher:1176] Unable to start bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.commerce.service.jar
[beanshell] org.osgi.framework.BundleException: Could not resolve module: com.liferay.commerce.service [1405]
[beanshell]   Unresolved requirement: Import-Package: com.liferay.commerce.product.service.impl
[beanshell] 
[beanshell] 	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundle(DirectoryWatcher.java:1159) [bundleFile:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundles(DirectoryWatcher.java:1192) [bundleFile:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._startAllBundles(DirectoryWatcher.java:1133) [bundleFile:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:1044) [bundleFile:?]
[beanshell] 	at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:222) [bundleFile:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-30/test-portal-acceptance-pullrequest(master)/4943/modules-integration-mysql57-jdk8_stable/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
PR sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/124448

cc @shuyangzhou @tinatian

**Pull request closed without merging**
