### PR TITLE
[Portal service extender] LPS-170182 clean up

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
Possible regression:
Some integration tests failed with below messages:
```
[beanshell] Waiting for service com.liferay.notification.type.NotificationType notification.type.key=userNotification for field com.liferay.notification.internal.type.test.UserNotificationTypeTest._notificationType
[beanshell] Waiting for service com.liferay.notification.type.NotificationType notification.type.key=userNotification for field com.liferay.notification.internal.type.test.UserNotificationTypeTest._notificationType
[beanshell] Waiting for service com.liferay.notification.type.NotificationType notification.type.key=userNotification for field com.liferay.notification.internal.type.test.UserNotificationTypeTest._notificationType
```

Full console log:
https://testray.liferay.com/reports/production/logs/2022-12/test-1-37/test-portal-acceptance-pullrequest(master)/6720/modules-integration-mysql57-jdk8/2/17/jenkins-console.txt.gz?authuser=0

**Comment by yuhai** [comment]
@zhangyan0701, the test error looks unrelated. I will trigger ci test again.

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@yuhai no regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127254

**Pull request closed without merging**
