### PR TITLE
Lps 188014 7 25

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@yuhai Please verify if this works.

Thanks.

**Comment by tinatian** [comment]
ci:test:start

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by yuhai** [comment]
@tinatian, I noticed the module didn't include **.lfrbuild-portal**, so it wasn't deployed during ant all. After deploying it, the pr can fix the issue.

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@tinatian Just an SF issue. No regressions found.


```
format-source-files:
     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: ./modules/apps/static/portal-startup/portal-startup-service-component-actor-sync/src/main/java/com/liferay/portal/startup/service/component/actor/sync/internal/ServiceComponentActorGateKeeper.java expected:<...opyrightText: (c) 20[23] Liferay, Inc. https...> but was:<...opyrightText: (c) 20[00] Liferay, Inc. https...>
     [java] 2: ./modules/apps/static/portal-startup/portal-startup-service-component-actor-sync/src/main/java/com/liferay/portal/startup/service/component/actor/sync/internal/ServiceComponentActorSync.java expected:<...opyrightText: (c) 20[23] Liferay, Inc. https...> but was:<...opyrightText: (c) 20[00] Liferay, Inc. https...>
     [java] 3: ./modules/apps/static/portal-startup/portal-startup-monitor/src/main/java/com/liferay/portal/startup/monitor/internal/PortalStartupMonitor.java expected:<...opyrightText: (c) 20[23] Liferay, Inc. https...> but was:<...opyrightText: (c) 20[00] Liferay, Inc. https...>
     [java] 
 ```
 [Log](https://testray.liferay.com/reports/production/logs/2023-07/test-1-37/test-portal-source-format/7724/source-format-current-branch-jdk8/0/0/jenkins-console.txt.gz?authuser=0)
 
 2) Scheduled staging publish doesn't trigger in cluster
 
 Steps to reproduce:
 1. Setup 2 node cluster (Can use "ant -f build-test-local.xml setup-portal-cluster")
 2. Startup node 1 and node 2
 3. On Master node, go to Publishing > Staging
 4. Enable Local Live staging
 5. Go to Site Builder > Pages, add and publish new test page
 6. Go to Publishing > Staging
 7. Click plus button to add new publishing process
 8. Schedule the process for 5 minutes from now
 9. Wait for the scheduled time

**Comment by yuhai** [comment]
@tinatian, resend it to https://github.com/liferay-core-infra/liferay-portal/pull/5112

**Pull request closed without merging**
