### PR TITLE
[Method References 2] LPS-171023 Convert method reference to ServiceTrackerMap in class IndexResourceImpl(module portal-workflow-metrics-rest-impl)

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian , I re-added the enum class.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/2861

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:workflow-metrics

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(1/9 15:54)

**Comment by W2jx** [comment]
no conflicts(1/11 16:12)

**Comment by dantewang** [comment]
@W2jx Please resend with the following changes:

1. This pull is to convert method reference, so please don't convert `Stream` or `Optional` usages here. Keep them, and just modify the logic to apply your new class.
2. Please see if it's possible to further simplify your `enum` class. Is there any way to avoid creating them with values different with the enum constants?

**Pull request closed without merging**
