### PR TITLE
[Remove Blocking usages]LPS-188563 portal-kernel | UserBagFactoryUtil

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian , I have injected UserBagFactoryImpl through spring according to the [comment](https://github.com/liferay-core-infra/liferay-portal/pull/4995#issuecomment-1646361885)

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4995

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:security

**Comment by W2jx** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:security

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
