### PR TITLE
[Remove Stream/Optional usage] LPS-175076 Remove usages of Stream for module: oauth2-provider-service

### PR DESCRIPTION
**Pull request by W2jx**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3404

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:oauth2

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(2/21 13:50)

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130693

**Pull request closed without merging**
