### PR TITLE
LPS-166009 test move TemplateResourceParser

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
put QA Failed first, no need to scan yet

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong I checked quickly and found this issue (just in case you need help to find the error):

```
[exec] > Task :apps:portal-template:portal-template-engine-api:deployDependencies NO-SOURCE
     [exec] > Task :apps:portal-template:portal-template-engine-api:deployConfigs NO-SOURCE
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-engine-impl/src/main/java/com/liferay/portal/template/engine/internal/resource/parser/ClassLoaderResourceParser.java:21: error: package com.liferay.portal.template.engine.resource.parser does not exist
     [exec] import com.liferay.portal.template.engine.resource.parser.TemplateResourceParser;
     [exec]                                                          ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-engine-impl/src/main/java/com/liferay/portal/template/engine/internal/resource/parser/ClassLoaderResourceParser.java:22: error: package com.liferay.portal.template.engine.resource.parser does not exist
     [exec] import com.liferay.portal.template.engine.resource.parser.URLResourceParser;
     [exec]                                                          ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-engine-impl/src/main/java/com/liferay/portal/template/engine/internal/resource/parser/ClassLoaderResourceParser.java:39: error: cannot find symbol
     [exec] public class ClassLoaderResourceParser extends URLResourceParser {
     [exec]                                                ^
     [exec]   symbol: class URLResourceParser
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-engine-impl/src/main/java/com/liferay/portal/template/engine/internal/resource/parser/ThemeResourceParser.java:21: error: package com.liferay.portal.template.engine.resource.parser does not exist
     [exec] import com.liferay.portal.template.engine.resource.parser.TemplateResourceParser;
     [exec]                                                          ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-engine-impl/src/main/java/com/liferay/portal/template/engine/internal/resource/parser/ThemeResourceParser.java:22: error: package com.liferay.portal.template.engine.resource.parser does not exist
     [exec] import com.liferay.portal.template.engine.resource.parser.URLResourceParser;
     [exec]                                                          ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-engine-impl/src/main/java/com/liferay/portal/template/engine/internal/resource/parser/ThemeResourceParser.java:41: error: cannot find symbol
     [exec] public class ThemeResourceParser extends URLResourceParser {
     [exec]                                          ^
     [exec]   symbol: class URLResourceParser
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-engine-impl/src/main/java/com/liferay/portal/template/engine/internal/resource/parser/DDMTemplateResourceParser.java:33: error: package com.liferay.portal.template.engine.resource.parser does not exist
     [exec] import com.liferay.portal.template.engine.resource.parser.TemplateResourceParser;
     [exec]                                                          ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-engine-impl/src/main/java/com/liferay/portal/template/engine/internal/resource/parser/DDMTemplateResourceParser.java:49: error: cannot find symbol
     [exec] public class DDMTemplateResourceParser implements TemplateResourceParser {
     [exec]                                                   ^
     [exec]   symbol: class TemplateResourceParser
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-engine-impl/src/main/java/com/liferay/portal/template/engine/internal/resource/parser/ClassLoaderResourceParser.java:37: error: cannot find symbol
     [exec] 	service = TemplateResourceParser.class
     [exec] 	          ^
     [exec]   symbol: class TemplateResourceParser
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-engine-impl/src/main/java/com/liferay/portal/template/engine/internal/resource/parser/ThemeResourceParser.java:39: error: cannot find symbol
     [exec] 	service = TemplateResourceParser.class
     [exec] 	          ^
     [exec]   symbol: class TemplateResourceParser
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-engine-impl/src/main/java/com/liferay/portal/template/engine/internal/resource/parser/DDMTemplateResourceParser.java:47: error: cannot find symbol
     [exec] 	service = TemplateResourceParser.class
     [exec] 	          ^
     [exec]   symbol: class TemplateResourceParser
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-engine-impl/src/main/java/com/liferay/portal/template/engine/internal/resource/parser/ClassLoaderResourceParser.java:42: error: cannot find symbol
     [exec] 		Class<?> clazz = getClass();
     [exec] 		                 ^
     [exec]   symbol:   method getClass()
     [exec]   location: class com.liferay.portal.template.engine.internal.resource.parser.ClassLoaderResourceParser
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-engine-impl/src/main/java/com/liferay/portal/template/engine/internal/resource/parser/ClassLoaderResourceParser.java:42: error: incompatible types: com.liferay.portal.template.engine.internal.resource.parser.ClassLoaderResourceParser.getClass cannot be converted to java.lang.Class<?>
     [exec] 		Class<?> clazz = getClass();
     [exec] 		                         ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-engine-impl/src/main/java/com/liferay/portal/template/engine/internal/resource/parser/ClassLoaderResourceParser.java:47: error: method does not override or implement a method from a supertype
     [exec] 	@Override
     [exec] 	^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-engine-impl/src/main/java/com/liferay/portal/template/engine/internal/resource/parser/ThemeResourceParser.java:43: error: method does not override or implement a method from a supertype
     [exec] 	@Override
     [exec] 	^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-engine-impl/src/main/java/com/liferay/portal/template/engine/internal/resource/parser/DDMTemplateResourceParser.java:51: error: method does not override or implement a method from a supertype
     [exec] 	@Override
     [exec] 	^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-engine-impl/src/main/java/com/liferay/portal/template/engine/internal/resource/parser/DDMTemplateResourceParser.java:122: error: method does not override or implement a method from a supertype
     [exec] 	@Override
     [exec] 	^
     [exec] 17 errors
     [exec] 
     [exec] > Task :apps:portal-template:portal-template-engine-impl:compileJava FAILED
```

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
There are compile errors in unit tests should be related:
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-velocity/src/test/java/com/liferay/portal/template/velocity/internal/VelocityTemplateTest.java:27: error: cannot find symbol
     [exec] import com.liferay.portal.template.ClassLoaderResourceParser;
     [exec]                                   ^
     [exec]   symbol:   class ClassLoaderResourceParser
     [exec]   location: package com.liferay.portal.template
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-velocity/src/test/java/com/liferay/portal/template/velocity/internal/VelocityTemplateTest.java:83: error: cannot find symbol
     [exec] 			new ClassLoaderResourceParser());
     [exec] 			    ^
     [exec]   symbol:   class ClassLoaderResourceParser
     [exec]   location: class com.liferay.portal.template.velocity.internal.VelocityTemplateTest
     [exec] 2 errors
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/portal-url-builder/portal-url-builder-impl/src/main/java/com/liferay/portal/url/builder/internal/BaseBundleResourceAbsolutePortalURLBuilderImpl.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 
     [exec] > Task :apps:portal-template:portal-template-velocity:compileTestJava FAILED
```

Full console log；
https://testray.liferay.com/reports/production/logs/2022-10/test-1-33/test-portal-acceptance-pullrequest(master)/2352/modules-unit-jdk8/0/2/jenkins-console.txt.gz?authuser=0

**Comment by tinatian** [comment]
@julschong I am going to close this pull, next time, if you want to test, please send it to your own repo.

Thanks.
Tina

**Pull request closed without merging**
