### PR TITLE
LPS-197267 Move PermissionConverter to modules

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong compile issue:

```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-security/portal-security-permission-test/src/testIntegration/java/com/liferay/portal/security/permission/test/PermissionConverterTest.java:22: error: cannot find symbol
     [exec] import com.liferay.portal.security.permission.converter.PermissionConverterUtil;
     [exec]                                                        ^
     [exec]   symbol:   class PermissionConverterUtil
     [exec]   location: package com.liferay.portal.security.permission.converter
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-security/portal-security-permission-test/src/testIntegration/java/com/liferay/portal/security/permission/test/PermissionConverterTest.java:62: error: cannot find symbol
     [exec] 				PermissionConverterUtil.convertPermissions(role);
     [exec] 				^
     [exec]   symbol:   variable PermissionConverterUtil
     [exec]   location: class com.liferay.portal.security.permission.test.PermissionConverterTest
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 2 errors
     [exec] 
     [exec] > Task :apps:portal-security:portal-security-permission-test:compileTestIntegrationJava FAILED
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-09/test-1-40/test-portal-acceptance-pullrequest(master)/6427/modules-compile-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@julschong No regressions found. But it seems SF expects the value here

modules/apps/portal-security/portal-security-permission-api/src/main/resources/com/liferay/portal/security/permission/contributor/packageinfo

to be null. Maybe it needs to be deleted?

**Comment by Kvale1733** [comment]
ci:close

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong The SF issue is gone. No regressions.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141703

**Pull request closed without merging**
