### PR TITLE
[OrderByComparator] LPD 26671 Clean up and Apply Singleton in module message-boards part I

### PR DESCRIPTION
**Pull request by rubenssoares-br**
Ticket: https://liferay.atlassian.net/browse/LPD-26671

### CODE REVIEW

**Comment by rubenssoares-br** [comment]
ci:test:sf

**Comment by rubenssoares-br** [comment]
ci:report:2572756757

**Comment by rubenssoares-br** [comment]
ci:test:content-management

**Comment by rubenssoares-br** [comment]
ci:report:2572974768

**Comment by rubenssoares-br** [comment]
ci:test:content-management

**Comment by rubenssoares-br** [comment]
ci:report:2573251651

**Comment by rubenssoares-br** [comment]
ci:test:sf

**Comment by rubenssoares-br** [comment]
ci:test:relevant

**Comment by rubenssoares-br** [comment]
ci:test:content-management

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
Reevaluating!
CC: @titokenzo

**Pull request closed without merging**
