### PR TITLE
[Convert method references]LPS-162748 Convert method references to field references in module flags

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-162748

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Review by dantewang — APPROVED** [review]
@shuyangzhou @tinatian Forwarding this one as all tests passed and changes are direct replacements.

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
