### PR TITLE
LPS-154857 rename properties: module.framework.properties.dependency.* , module.framework.properties.initial.system.check.enabled

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang ,  I have modified the order of the properties in secondary files as suggested by @ling-alan-huang

Details of test results : https://github.com/liferay-core-infra/liferay-portal/pull/944

Details of the properties out-of-order error : https://github.com/brianchandotcom/liferay-portal/pull/119915

### CODE REVIEW

**Comment by W2jx** [comment]
ci:stop

**Comment by W2jx** [comment]
ci:test:acceptance

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:stop

**Comment by W2jx** [comment]
ci:stop

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:acceptance

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me scan test results when you free ? Thanks!

**Comment by W2jx** [comment]
ci:test:acceptance

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me scan test results when you free ? Thanks!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/120371

**Pull request closed without merging**
