### PR TITLE
LPS-172616

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@4lejandrito @adolfopa Could you please review this change and trigger any tests you want to cover?

Thanks.
Tina

**Comment by adolfopa** [comment]
ci:help

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@tinatian Changes look good.

**Comment by zhangyan0701** [comment]
1. All modules unit tests failed with a compile error:
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-journal-web/src/test/java/com/liferay/adaptive/media/journal/web/internal/messaging/AMJournalImageConfigurationMessageListenerTest.java:57: error: cannot find symbol
     [exec] 	private final AMJournalImageConfigurationMessageListener
     [exec] 	              ^
     [exec]   symbol:   class AMJournalImageConfigurationMessageListener
     [exec]   location: class com.liferay.adaptive.media.journal.web.internal.messaging.AMJournalImageConfigurationMessageListenerTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-journal-web/src/test/java/com/liferay/adaptive/media/journal/web/internal/messaging/AMJournalImageConfigurationMessageListenerTest.java:59: error: cannot find symbol
     [exec] 			new AMJournalImageConfigurationMessageListener();
     [exec] 			    ^
     [exec]   symbol:   class AMJournalImageConfigurationMessageListener
     [exec]   location: class com.liferay.adaptive.media.journal.web.internal.messaging.AMJournalImageConfigurationMessageListenerTest
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-01/test-1-37/test-portal-acceptance-pullrequest(master)/7916/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

2. Semantic versioning error:
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/adaptive-media/adaptive-media-image-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]       com.liferay.adaptive.media.image.constants         REMOVED    1.0.0      1.0.0      -          PACKAGE REMOVED, UNNECESSARY PACKAGEINFO
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 9.0.0
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-01/test-1-37/test-portal-acceptance-pullrequest(master)/7916/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Semantic versioning error:
```
     [exec] > Task :apps:adaptive-media:adaptive-media-image-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec]   com.liferay.adaptive.media.image.constants         REMOVED    1.0.0      1.0.0      -          PACKAGE REMOVED, UNNECESSARY PACKAGEINFO
     [exec] [Baseline Warning] Bundle Version Change Recommended: 9.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.adaptive.media.image.api-8.1.1.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.adaptive.media.image.api/8.1.0/afd5098238bea83124a33433eb6e2073d98c933c/com.liferay.adaptive.media.image.api-8.1.0.jar
```
Full console:
https://testray.liferay.com/reports/production/logs/2023-01/test-1-38/test-portal-acceptance-pullrequest(master)/5713/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128880

**Pull request closed without merging**
