### PR TITLE
[Method References 2] LPS-168155 WikiImporter

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang ,

Since the `WikiNodeLocalServiceTest > testMediaLinks` test failed in the previous PR( https://github.com/liferay-core-infra/liferay-portal/pull/3082), I checked with the author who add this test and got the reply 
> MediaWikiToCreoleTranslator  is still used when I'm importing a MediaWiki page

So basically I kept what I did in https://github.com/liferay-core-infra/liferay-portal/pull/2575 except for the constants reorganization and deleted class WikiCreoleConvertProcess  (I discussed that with Summer/Lima and we cannot find any usages of it).

Thanks!

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:wiki

**Comment by zhangyan0701** [comment]
@JanisZhang Please fix the conflict in file modules/apps/wiki/wiki-api/bnd.bnd.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@JanisZhang Please just rebase the bnd, thanks!

**Comment by JanisZhang** [comment]
force-pushed. I only changed the bnd file. No need to rerun the test. Thanks! cc @dantewang @zhangyan0701

**Comment by tinatian** [comment]
@JanisZhang @dantewang Is it safe to do this https://github.com/liferay-core-infra/liferay-portal/pull/4062/commits/b9fc507567be59b86ee0bf8305466492fcdedf50? The interface is in api module and published

**Comment by dantewang** [comment]
@tinatian I believe @JanisZhang asked Wiki team?

**Comment by JanisZhang** [comment]
Hi @dantewang @tinatian ,

WikiImporter currently only supports importing MediaWiki, i have asked the Lima team, and they don't think it would be a problem to get rid of this extension point.

https://liferay.slack.com/archives/CLD39UKM5/p1668734757184489

**Comment by tinatian** [comment]
@JanisZhang Please rebase and update the commit message about it is safe to remove it.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:wiki

**Comment by zhangyan0701** [comment]
No regressions found.

**Pull request closed without merging**
