### PR TITLE
LPS-154857 rename properties: module.framework.properties.dependency.* , module.framework.properties.initial.system.check.enabled

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian, I've removed constants that no one else uses

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 We rename some properties may used by ci, we modified the usage we found on master code, is there any usage we need to update for ci?

Thanks.
Tina.

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Tina.

**Comment by catarineaguiar** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
@W2jx semver error:

```
  [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/59.0.0/dd8c972f323c8af21cf1928b7313cf6da5419ece/com.liferay.portal.kernel-59.0.0.jar
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-06/test-1-34/test-portal-acceptance-pullrequest(master)/2177/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by vicnate5** [comment]
@zhangyan0701 can you look into what we might need to update on CI for this?

**Comment by W2jx** [comment]
ci:test:acceptance

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions on CI results

**Comment by vicnate5** [comment]
We will still need to do a check on Monday for the module.framework properties

**Comment by zhangyan0701** [comment]
@vicnate5 @tinatian We don't need to do additional updates on ci properties. The usage on ci test has been updated in https://github.com/liferay-core-infra/liferay-portal/pull/944/commits/96c14b4ad87f81232c83e694c8aef8e280a6d6cf, and I didn't find out other usage.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Pull request closed without merging**
