### PR TITLE
[Remove Blocking usages]LPS-187897 portal-kernel/impl | DefaultActionableDynamicQuery,AutoBatchPreparedStatementUtil,GlobalShutdownAction

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-187897

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by JanisZhang** [comment]
Force-pushed. I only changed the commit message. It shouldn't affect the test results. Thanks!

**Comment by JanisZhang** [comment]
Force-pushed. I only changed the commit message. It shouldn't affect the test results. Thanks!

**Pull request closed without merging**
