### PR TITLE
[Service Builder Soap]LPS-145347

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:stable

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Gradle is calling `buildWSDD` for lots of different modules
https://testray.liferay.com/reports/production/logs/2022-02/test-1-27/test-portal-acceptance-pullrequest(master)/1673/modules-compile-jdk8/0/9/jenkins-console.txt.gz
https://testray.liferay.com/reports/production/logs/2022-02/test-1-27/test-portal-acceptance-pullrequest(master)/1673/modules-compile-jdk8/0/7/jenkins-console.txt.gz
https://testray.liferay.com/reports/production/logs/2022-02/test-1-27/test-portal-acceptance-pullrequest(master)/1673/modules-compile-jdk8/0/5/jenkins-console.txt.gz

I think it needs to be fixed to not be used for master on the tooling side.

**Comment by tinatian** [comment]
Thanks @vicnate5 ! I asked Peter for help to avoid running it.

**Comment by tinatian** [comment]
ci:test:stable

**Comment by tinatian** [comment]
@vicnate5 I updated the pull and disabled buildWsdd related gradle tasks. I triggerred ci:test:stable, please trigger more tests if it is not enought.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian This is good to go now, no additional testing needed. I confirmed there is no other regressions in the previous test results.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
@tinatian please rebase and forward, I have reviewed it already.

**Pull request closed without merging**
