### PR TITLE
LPS-144496 Rebase 12-31

### PR DESCRIPTION
**Pull request by dantewang**
Rebased. The conflict was caused by semantic version files.. @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
The conflict is semantic versioning only.

**Comment by tinatian** [comment]
@dantewang Please see https://github.com/liferay-core-infra/liferay-portal/pull/172. I only include part of your changes in this pull, please resend them after the first part is merged.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
