### PR TITLE
[Component with its own class name as service type] LPS-197370 Refactor components from lima modules part 2

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-197370](https://liferay.atlassian.net/browse/LPS-197370)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@RenanUmV This introduces a new startup race. I was only able to reproduce locally once in about 6 tries just by starting up. On CI it showed up a couple times.

```
[beanshell] 2023-10-13 21:05:09.887 ERROR [main][ServiceWrapperRegistry:63] Unable to get service bag for class com.liferay.sharing.notifications.internal.service.NotificationsSharingEntryLocalServiceWrapper
[beanshell] java.lang.NullPointerException: A null service reference is not allowed.
[beanshell] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:622) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at com.liferay.portal.deploy.hot.ServiceWrapperRegistry$ServiceWrapperServiceTrackerCustomizer._getServiceBag(ServiceWrapperRegistry.java:119) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.deploy.hot.ServiceWrapperRegistry$ServiceWrapperServiceTrackerCustomizer.addingService(ServiceWrapperRegistry.java:60) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.deploy.hot.ServiceWrapperRegistry$ServiceWrapperServiceTrackerCustomizer.addingService(ServiceWrapperRegistry.java:49) ~[portal-impl.jar:?]
[beanshell] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:321) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:264) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at com.liferay.portal.deploy.hot.ServiceWrapperRegistry.<init>(ServiceWrapperRegistry.java:34) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.lambda$contextInitialized$0(PortalContextLoaderListener.java:275) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.module.util.ServiceLatch$CapturingServiceTrackerCustomizer.addingService(ServiceLatch.java:114) [portal-kernel.jar:?]
[beanshell] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) [org.eclipse.osgi.jar:?]
```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-40/test-portal-acceptance-pullrequest(master)/6671/functional-upgrade-tomcat90-mysql57-jdk8/1/2/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Comment by RenanUmV** [comment]
resent here: https://github.com/liferay-core-infra/liferay-portal/pull/5875

**Pull request closed without merging**
