### PR TITLE
[Component with its own class name as service type ] LPS-196226 Refactor Registry classes from multiple modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-196226

Previous pull: https://github.com/liferay-core-infra/liferay-portal/pull/5575

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
@MrJohn1911 There is a conflict, please resolve it first and re-run relevant test.

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@MrJohn1911 There is a startup issue

```
[beanshell] Unable to display JSP extract. Probably due to an XML parser bug (see Tomcat bug 48498 for details).
[beanshell] 
[beanshell] Stacktrace:
[beanshell] org.osgi.framework.InvalidSyntaxException: Missing attr at "(&(objectClass=javax.servlet.ServletContext)(osgi.web.contextpath=*))=*)(objectClass=javax.servlet.ServletContext))": (&((&(objectClass=javax.servlet.ServletContext)(osgi.web.contextpath=*))=*)(objectClass=javax.servlet.ServletContext))
[beanshell] 	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_attr(FilterImpl.java:1666) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_item(FilterImpl.java:1595) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_filtercomp(FilterImpl.java:1539) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_filter(FilterImpl.java:1505) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_and(FilterImpl.java:1554) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_filtercomp(FilterImpl.java:1528) ~[org.eclipse.osgi.jar:?]
```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-34/test-portal-acceptance-pullrequest(master)/4781/functional-smoke-tomcat90-hypersonic20-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
