### PR TITLE
[Remove Stream/Optional: Phase 4] LPS-182656 Remove Stream and optional usages for modules: dynamic-data-mapping-data-provider-impl、dynamic-data-mapping-form-renderer

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4398

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:forms

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(5/2 10:54)

**Comment by tinatian** [comment]
@W2jx For DDMRESTDataProvider, it is actually transform a map into KeyValuePair and later on use KeyValuePair, this really does not make sense, please remove the transformation to KeyValuePair to avoid creating unnecessary instance, other commits looks good to me and  please see https://github.com/liferay-core-infra/liferay-portal/pull/4444.

Tina

**Pull request closed without merging**
