### PR TITLE
[Components with more than 1 service] LPS-189681 Refactor HttpMethodScopeLogic component

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Related: https://liferay.atlassian.net/browse/LPS-189681

Correction Of: https://github.com/liferay-core-infra/liferay-portal/pull/5221

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Valmir-unicap** [comment]
ci:test:security

**Comment by Valmir-unicap** [comment]
ci:test:oauth2

**Review by rafaprax — APPROVED** [review]

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:startup

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Valmir-unicap** [comment]
ci:test:security

**Comment by Valmir-unicap** [comment]
ci:test:oauth2

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:oauth2

**Comment by Kvale1733** [comment]
ci:test:security

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
Hi, please resend, thanks!

**Pull request closed without merging**
