### PR TITLE
[Components with more than 1 service] LPS-192993 Refactor ManagedServiceFactory from oauth2-provider-rest, document-library-service, document-library-preview-pdf and portal-security-sso-openid-connect-impl modules

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-192993](https://liferay.atlassian.net/browse/LPS-192993)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:security

**Comment by RenanUmV** [comment]
ci:test:document

**Comment by Kvale1733** [comment]
ci was reset yesterday. Need to rerun tests.

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:document

**Comment by Kvale1733** [comment]
ci:test:security

**Review by rafaprax — CHANGES_REQUESTED** [review]

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:document

**Comment by RenanUmV** [comment]
ci:test:security

**Comment by Kvale1733** [comment]
@RenanUmV Regressions found

1) 
```
com.liferay.oauth2.provider.token.endpoint.test.JWTAssertAuthorizationGrantTest
    [exec] com.liferay.oauth2.provider.token.endpoint.test.JWTAssertAuthorizationGrantTest > testClientAuthentication1 STARTED
[beanshell] 2023-08-17 03:57:32.858 WARN  [http-nio-8080-exec-4][LiferayJWTBearerGrantHandler:329] null
[beanshell] java.lang.IllegalArgumentException: No JWS signature keys for issuer: test_client_id_1, in company: 20096
[beanshell] 	at com.liferay.oauth2.provider.rest.internal.endpoint.access.token.grant.handler.LiferayJWTBearerGrantHandler._getJWSSignatureVerifier(LiferayJWTBearerGrantHandler.java:170) ~[bundleFile:?]
[beanshell] 	at com.liferay.oauth2.provider.rest.internal.endpoint.access.token.grant.handler.LiferayJWTBearerGrantHandler.access$400(LiferayJWTBearerGrantHandler.java:67) ~[bundleFile:?]
[beanshell] 	at com.liferay.oauth2.provider.rest.internal.endpoint.access.token.grant.handler.LiferayJWTBearerGrantHandler$CustomJWTBearerGrantHandler._initGrantHandler(LiferayJWTBearerGrantHandler.java:324) [bundleFile:?]
[beanshell] 	at com.liferay.oauth2.provider.rest.internal.endpoint.access.token.grant.handler.LiferayJWTBearerGrantHandler$CustomJWTBearerGrantHandler.createAccessToken(LiferayJWTBearerGrantHandler.java:258) [bundleFile:?]
[beanshell] 	at com.liferay.oauth2.provider.rest.internal.endpoint.access.token.grant.handler.LiferayJWTBearerGrantHandler.doCreateAccessToken(LiferayJWTBearerGrantHandler.java:105) [bundleF
```
```
     [exec] com.liferay.oauth2.provider.token.endpoint.test.JWTAssertAuthorizationGrantTest > testClientAuthentication1 FAILED
     [exec]     java.lang.AssertionError
     [exec]     	at org.junit.Assert.fail(Assert.java:87)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:53)
     [exec]     	at com.liferay.oauth2.provider.token.endpoint.test.BaseAuthorizationGrantTestCase.testClientAuthentication1(BaseAuthorizationGrantTestCase.java:25)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Meth
 ```
 [Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-36/test-portal-acceptance-pullrequest(master)/4067/modules-integration-mysql57-jdk8/0/10/jenkins-console.txt.gz?authuser=0)
 
 2) com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest
 ```
    [exec]     java.lang.NoSuchFieldException: No field on null with name _pdfPreviewManagedServiceFactoryHelper
     [exec]     	at com.liferay.portal.kernel.test.ReflectionTestUtil.getField(ReflectionTestUtil.java:126)
     [exec]     	at com.liferay.portal.kernel.test.ReflectionTestUtil.getFieldValue(ReflectionTestUtil.java:142)
     [exec]     	at com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest._getMaxNumberOfPages(PDFPreviewManagedServiceFactoryTest.java:250)
     [exec]     	at com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest.lambda$null$0(PDFPreviewManagedServiceFactoryTest.java:69)
     [exec]     	at com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest._withGroupConfiguration(PDFPreviewManagedServiceFactoryTest.java:299)
     [exec]     	at com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest.lambda$testGetCompanyGroupAndSystemMaxNumberOfPages$1(PDFPreviewManagedServiceFactoryTest.java:62)
     [exec]     	at com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest._withCompanyConfiguration(PDFPreviewManagedServiceFactoryTest.java:277)
     [exec]     	at com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest.testGetCompanyGroupAndSystemMaxNumberOfPages(PDFPreviewManagedServiceFactoryTest.java:58)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  ```
  [Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-28/test-portal-acceptance-pullrequest(master)/7296/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:document

**Comment by RenanUmV** [comment]
ci:test:security

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:document

**Comment by RenanUmV** [comment]
ci:test:security

**Pull request closed without merging**
