### PR TITLE
remove_deprecated_part_9_portal_impl

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is remove deprecated methods for portal-impl part nine.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result again, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
Hi @jeffwu0724 some integration tests failed and I reproduced locally:

`AddressTextLocalizerUtilTest`

```
[exec] /opt/dev/projects/github/liferay-portal/modules/apps/text-localizer/text-localizer-taglib-test/src/testIntegration/java/com/liferay/text/localizer/taglib/internal/address/util/test/AddressTextLocalizerUtilTest.java:152: error: no suitable method found for addAddress(long,String,long,String,String,String,String,String,long,long,long,boolean,boolean,ServiceContext)
     [exec] 		return AddressLocalServiceUtil.addAddress(
     [exec] 		                              ^
     [exec]     method AddressLocalServiceUtil.addAddress(Address) is not applicable
     [exec]       (actual and formal argument lists differ in length)
     [exec]     method AddressLocalServiceUtil.addAddress(String,long,String,long,String,String,String,String,String,String,String,long,long,long,boolean,boolean,String,ServiceContext) is not applicable
     [exec]       (actual and formal argument lists differ in length)
     [exec] 1 error
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-29/test-portal-acceptance-pullrequest(master)/2947/modules-integration-mysql57-jdk8/3/17/jenkins-console.txt.gz?authuser=0)

`StagingImplTest`

```
[exec] /opt/dev/projects/github/liferay-portal/modules/apps/staging/staging-test/src/testIntegration/java/com/liferay/staging/test/StagingImplTest.java:295: error: no suitable method found for addCategory(long,long,int,Map<Locale,String>,Map<Locale,String>,long,String[],ServiceContext)
     [exec] 		return AssetCategoryLocalServiceUtil.addCategory(
     [exec] 		                                    ^
     [exec]     method AssetCategoryLocalServiceUtil.addCategory(long,long,String,long,ServiceContext) is not applicable
     [exec]       (actual and formal argument lists differ in length)
     [exec]     method AssetCategoryLocalServiceUtil.addCategory(String,long,long,long,Map<Locale,String>,Map<Locale,String>,long,String[],ServiceContext) is not applicable
     [exec]       (actual and formal argument lists differ in length)
     [exec] 1 error
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-29/test-portal-acceptance-pullrequest(master)/2947/modules-integration-mysql57-jdk8/3/13/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
@jeffwu0724 Please fix and resend.

Thanks.
Tina

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
