### PR TITLE
LPS-157255 Remove web portal dir property

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:acceptance

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@julschong Please discard the changes in VerifyProperties and update this pull. Other changes looks good to me.

@catarineaguiar Please help to scan test results. The changes required above won't affect test result.

**Comment by julschong** [comment]
pushed to resolve conflict in [LPS-155670 Auto, semantic versioning](https://github.com/liferay-core-infra/liferay-portal/pull/1091/commits/bb291d20932f61c7354f11ba7f89b724abdf7d15)
also discarded change in VerifyProperties

**Comment by catarineaguiar** [comment]
@julschong regressions found:

`PortalImplTest`, `PortalDirTest`, and others.
```
[exec] com.liferay.portal.util.test.PortalImplLocalizedFriendlyURLTest > classMethod FAILED
     [exec]     org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.util.test [1475]
     [exec]       Unresolved requirement: Import-Package: com.liferay.portal.spring.context
     [exec]         at org.eclipse.osgi.container.Module.start(Module.java:444)
     [exec]         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
     [exec]         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:447)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.connector.FrameworkCommand.lambda$startBundle$37e16ea2$1(FrameworkCommand.java:46)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.connector.ArquillianConnectorThread.run(ArquillianConnectorThread.java:82)
```
```
 [exec] com.liferay.portal.util.test.PortalImplLocaleTest > classMethod FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.arquillian.extension.junit.bridge.client.SocketState.writeUTF(SocketState.java:123)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.client.ClientState$1.execute(ClientState.java:127)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.junit.Arquillian.run(Arquillian.java:123)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
     [exec]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-07/test-1-25/test-portal-acceptance-pullrequest(master)/3655/modules-integration-mysql57-jdk8/3/8/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
close, need to find where the issue is

**Pull request closed without merging**
