### PR TITLE
LPS-199287 Merge File interface and impl into Util in kernel

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from #5852

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by julschong** [comment]
rebased, need to retest

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found, only a semantic versioning issue:
```
     [exec] > Task :apps:export-import:export-import-api:baseline
     [exec] [Baseline Warning] Bundle Version Change Recommended: 8.1.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.exportimport.api-8.0.1.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.exportimport.api/8.0.0/a648c1cf504f7fd70e6c5a2bd8680413be0b15a1/com.liferay.exportimport.api-8.0.0.jar
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-11/test-1-40/test-portal-acceptance-pullrequest(master)/7093/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by julschong** [comment]
added baseline commit

**Comment by julschong** [comment]
rebased

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong regression found:

```
     [exec] > Task :core:portal-app-license-impl:compileJava
     [exec] /opt/dev/projects/github/liferay-portal/modules/core/portal-app-license-impl/src/main/java/com/liferay/portal/app/license/impl/MarketplaceAppLicenseVerifier.java:25: error: cannot find symbol
     [exec] import com.liferay.portal.util.FileImpl;
     [exec]                               ^
     [exec]   symbol:   class FileImpl
     [exec]   location: package com.liferay.portal.util
     [exec] /opt/dev/projects/github/liferay-portal/modules/core/portal-app-license-impl/src/main/java/com/liferay/portal/app/license/impl/MarketplaceAppLicenseVerifier.java:117: error: cannot find symbol
     [exec] 			fileUtil.setFile(new FileImpl());
     [exec] 			                     ^
     [exec]   symbol:   class FileImpl
     [exec]   location: class com.liferay.portal.app.license.impl.MarketplaceAppLicenseVerifier
     [exec] 
     [exec] > Task :core:portal-app-license-impl:compileJava FAILED
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-35/test-portal-acceptance-pullrequest(master)/4849/portal-license-smoke-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
added release url, retesting

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by tinatian** [comment]
@julschong This is a big pull and easy to have code conflicts, let's separate it into small pieces:
1. Remove usages of FileImpl
2. Remove File usages
3. Merge FileImpl into FileUtil

**Pull request closed without merging**
