### PR TITLE
LPS-197317 Align model.class.name value in Workflow**ModelResourcePermission

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://liferay.atlassian.net/browse/LPS-197317

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by rafaprax** [comment]
ci:forward:force

/cc @shuyangzhou

**Pull request closed without merging**
