### PR TITLE
[CLDR] LPD-18471 Fix Functional Test: Locale#LanguageWithVariantDoesNotCauseInfiniteRedirectLoop with CLDR locale provider

### PR DESCRIPTION
**Pull request by julschong**
@tinatian 

CLDR clay link: српски (србија, latin)
JRE/COMPAT clay link: српски (serbia, latin)

this PR just change the test to be able to match both cases
tested passed with CLDR here: https://github.com/julschong/liferay-portal/pull/1151

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@julschong the SF failure seems real, please take a look at it.

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
@tinatian ready to go

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
