### PR TITLE
[TS] LPD-31601

### PR DESCRIPTION
**Pull request by dantewang**
https://liferay.atlassian.net/browse/LPD-31601

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:38390085

**Comment by dantewang** [comment]
ci:help

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/152412

**Pull request closed without merging**
