### PR TITLE
LPD-2571

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team,

**Ticket:** https://liferay.atlassian.net/browse/LPD-2571

As discussed, I took some time to see if we could potentially refactor the code in `PortalImpl::getScopeGroupId` by moving the logic to the proper team's component. From what I can tell, this would be challenging, since the logic involves interactions between multiple components: Layout, Portlet, Staging.

**Note**
We will need to decide whether we would like other Product Teams to also review this change. 
- The changes in this PR only affect environments where Staging is enabled. 
    - However, the logic change involves understanding of Layouts (Widget Page and Content Page) and Layout scope. 
- And so, I'm not sure if we also want the Staging Team and/or Echo Team to also review this change.

As for the test case, I tried to modify it to emulate the current behavior as closely as possible.

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:12107591

**Comment by ericyanLr** [comment]
**ci:report analysis**
No unique failures

**Comment by tinatian** [comment]
ci:test:staging

**Comment by tinatian** [comment]
ci:test:headless-staging

**Comment by ericyanLr** [comment]
Hi @tinatian ,

As discussed, I have created a new PR to only include the test changes and have sent to Headless/Staging Team.

Closing out this PR.

**Pull request closed without merging**
