### PR TITLE
[Equinox Http] LPS-196987 Inline ProxyContext

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No unique failures in relevant tests. Will run ci:test to make sure there is no regressions.

**Comment by zhangyan0701** [comment]
ci:test

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@shuyangzhou This one passed QA.

**Comment by dantewang** [comment]
@shuyangzhou Closing, I'll do a more complete replacement by injecting an interface.

**Pull request closed without merging**
