### PR TITLE
[Reference cleanup]LPS-162549

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to convert method references to field references in class extends BaseJSPAssetAddonEntry. Thanks!

https://issues.liferay.com/browse/LPS-162549

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @zhangyan0701, Could you pleas help to scan the test results? Thank you.

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@shuyangzhou @tinatian Forwarding this one as all tests passed review and changes are applying known pattern.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123084

**Pull request closed without merging**
