### PR TITLE
[Component with its own class name as service type] LPS-197625 Refactor components server-admin-web, push-notifications-sender-apple, portal-search components

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-197625](https://liferay.atlassian.net/browse/LPS-197625)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
ci:test:startup

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143215

**Review by rafaprax — APPROVED** [review]

**Pull request closed without merging**
