### PR TITLE
[TS] LPD-34438

### PR DESCRIPTION
**Pull request by dantewang**
https://liferay.atlassian.net/browse/LPD-34438

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:68734964

**Comment by shuyangzhou** [comment]
Looks fine, thanks @dantewang !

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
