### PR TITLE
Lpd 33643 12 2 test batch

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:glowroot-integration

**Comment by slnn** [comment]
ci:test:stop

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:glowroot-integration

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:report:81501693

**Comment by slnn** [comment]
ci:report:81501724

**Comment by dantewang** [comment]
@slnn Your `test-util` module needs to have a `.lfrbuild-portal` marker file in its directory (same level with its `build.gradle`), and have the below part in `build.gradle`:
```
liferay {
	deployDir = file("${liferayHome}/osgi/test")
}
```

**Comment by slnn** [comment]
ci:test:glowroot-integration

**Comment by slnn** [comment]
ci:report:8150473

**Comment by slnn** [comment]
Close this pull as the discussion in the sync meeting

**Comment by slnn** [comment]
ci:test:portal-context-path

**Pull request closed without merging**
