### PR TITLE
[Remove Stream/Optional usage] LPS-172193 Remove usages of Optional in module reading-time-taglib

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:lima

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(1/6 8:59)

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128437

**Pull request closed without merging**
