### PR TITLE
LPD-8461 Remove unused reference _messageBus

### PR DESCRIPTION
**Pull request by titokenzo**

### CODE REVIEW

**Comment by dantewang** [comment]
@titokenzo Please include the ticket number in the commit message.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:report:2540993290

**Comment by titokenzo** [comment]
ci:test:startup

**Comment by tinatian** [comment]
@titokenzo I added ticket number to commit message for you, see https://github.com/brianchandotcom/liferay-portal/pull/147523

**Comment by tinatian** [comment]
@titokenzo The ci:test:sf failure is real here, it is caused by missing ticket number.

`The commit message is missing a reference to a required JIRA project: BLADE, CLDSVCS, COMMERCE, FACES, IDE, ISSD, ISSITES, LCD, LHC, LOOP, LPD, LPS, LRAC, LRCI, LRDOCS, LRIS, LRQA, OAUTH2, POSHI, RELEASE, SYNC, TR. Please verify that the JIRA project keys are specifiedin source-formatter.properties in the liferay-portal repository.
     [java] 	at com.liferay.source.formatter.util.JIRAUtil.validateJIRAProjectNames(JIRAUtil.java:61)
     [java] 	at com.liferay.source.formatter.SourceFormatter._validateCommitMessages(SourceFormatter.java:1293)
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:327)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:291)`

**Pull request closed without merging**
