### PR TITLE
[Optional Reference]LPS-185415 Convert the Optional Dynamic Greedy references to static r…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-185415

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
@slnn regressions found:

```
     [exec] com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngineReconnectTest > classMethod FAILED
     [exec]     java.lang.ExceptionInInitializerError
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.suggest.ElasticsearchSuggesterTranslatorFixture.<init>(ElasticsearchSuggesterTranslatorFixture.java:28)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.search.SearchRequestExecutorFixture._createSuggestSearchRequestExecutor(SearchRequestExecutorFixture.java:499)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.search.SearchRequestExecutorFixture._createSearchRequestExecutor(SearchRequestExecutorFixture.java:364)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.search.SearchRequestExecutorFixture.setUp(SearchRequestExecutorFixture.java:101)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.ElasticsearchEngineAdapterFixture.createSearchEngineAdapter(ElasticsearchEngineAdapterFixture.java:95)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.ElasticsearchEngineAdapterFixture.setUp(ElasticsearchEngineAdapterFixture.java:41)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngineFixture._createSearchEngineAdapter(ElasticsearchSearchEngineFixture.java:212)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngineFixture._createElasticsearchSearchEngine(ElasticsearchSearchEngineFixture.java:178)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngineFixture.setUp(ElasticsearchSearchEngineFixture.java:81)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngineReconnectTest.setUpClass(ElasticsearchSearchEngineReconnectTest.java:52)
```
```
     [exec] com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngineBackupTest > classMethod FAILED
     [exec]     java.lang.NoClassDefFoundError: Could not initialize class com.liferay.portal.search.elasticsearch7.internal.suggest.PhraseSuggesterTranslatorImpl
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.suggest.ElasticsearchSuggesterTranslatorFixture.<init>(ElasticsearchSuggesterTranslatorFixture.java:28)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.search.SearchRequestExecutorFixture._createSuggestSearchRequestExecutor(SearchRequestExecutorFixture.java:499)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.search.SearchRequestExecutorFixture._createSearchRequestExecutor(SearchRequestExecutorFixture.java:364)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.search.SearchRequestExecutorFixture.setUp(SearchRequestExecutorFixture.java:101)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.ElasticsearchEngineAdapterFixture.createSearchEngineAdapter(ElasticsearchEngineAdapterFixture.java:95)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.ElasticsearchEngineAdapterFixture.setUp(ElasticsearchEngineAdapterFixture.java:41)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngineFixture._createSearchEngineAdapter(ElasticsearchSearchEngineFixture.java:212)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-05/test-1-32/test-portal-acceptance-pullrequest(master)/9669/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
> ```
>      [exec] com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngineBackupTest > classMethod FAILED
>      [exec]     java.lang.NoClassDefFoundError: Could not initialize class com.liferay.portal.search.elasticsearch7.internal.suggest.PhraseSuggesterTranslatorImpl
>      [exec]         at com.liferay.portal.search.elasticsearch7.internal.suggest.ElasticsearchSuggesterTranslatorFixture.<init>(ElasticsearchSuggesterTranslatorFixture.java:28)
>      [exec]         at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.search.SearchRequestExecutorFixture._createSuggestSearchRequestExecutor(SearchRequestExecutorFixture.java:499)
>      [exec]         at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.search.SearchRequestExecutorFixture._createSearchRequestExecutor(SearchRequestExecutorFixture.java:364)
>      [exec]         at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.search.SearchRequestExecutorFixture.setUp(SearchRequestExecutorFixture.java:101)
>      [exec]         at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.ElasticsearchEngineAdapterFixture.createSearchEngineAdapter(ElasticsearchEngineAdapterFixture.java:95)
>      [exec]         at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.ElasticsearchEngineAdapterFixture.setUp(ElasticsearchEngineAdapterFixture.java:41)
>      [exec]         at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchSearchEngineFixture._createSearchEngineAdapter(ElasticsearchSearchEngineFixture.java:212)
> ```

Thank @catarineaguiar for catching this! Forced push with the fix.

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
@slnn the failures mentioned [before](https://github.com/liferay-core-infra/liferay-portal/pull/4591#issuecomment-1560236851) are still happening

```
     [exec] com.liferay.portal.search.elasticsearch7.internal.pagination.ElasticsearchPermissionFilteredPaginationTest > testAccurateCountThresholdNegativeOne FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.portal.search.test.util.indexing.BaseIndexingTestCase.addDocument(BaseIndexingTestCase.java:152)
     [exec]         at com.liferay.portal.search.test.util.indexing.BaseIndexingTestCase.addDocument(BaseIndexingTestCase.java:174)
     [exec]         at com.liferay.portal.search.test.util.pagination.BasePermissionFilteredPaginationTestCase.indexEntries(BasePermissionFilteredPaginationTestCase.java:436)
     [exec]         at com.liferay.portal.search.test.util.pagination.BasePermissionFilteredPaginationTestCase.index(BasePermissionFilteredPaginationTestCase.java:422)
     [exec]         at com.liferay.portal.search.test.util.pagination.BasePermissionFilteredPaginationTestCase.testAccurateCountThresholdNegativeOne(BasePermissionFilteredPaginationTestCase.java:105)
```
```
     [exec] com.liferay.portal.search.elasticsearch7.internal.logging.ElasticsearchIndexWriterLogExceptionsOnlyTest > testPartiallyUpdateDocuments FAILED
     [exec]     java.lang.AssertionError: 
     [exec]     Expected: log output with message a string containing "Bulk partial update failed"
     [exec]          but: log output was ""
     [exec]         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
     [exec]         at org.junit.Assert.assertThat(Assert.java:956)
     [exec]         at org.junit.Assert.assertThat(Assert.java:923)
```
```
     [exec] com.liferay.portal.search.elasticsearch7.internal.logging.ElasticsearchIndexWriterLogExceptionsOnlyTest > testDeleteDocument FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.logging.ElasticsearchIndexWriterLogExceptionsOnlyTest.testDeleteDocument(ElasticsearchIndexWriterLogExceptionsOnlyTest.java:155)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
```
     [exec] com.liferay.portal.search.elasticsearch7.internal.logging.ElasticsearchIndexWriterExceptionsTest > testPartiallyUpdateDocuments FAILED
     [exec]     java.lang.AssertionError: 
     [exec]     Expected: (an instance of java.lang.RuntimeException and exception with message a string containing "Bulk partial update failed")
     [exec]          but: an instance of java.lang.RuntimeException <org.junit.internal.runners.model.MultipleFailureException: There were 2 errors:
     [exec]       java.lang.NullPointerException(null)
     [exec]       java.lang.NullPointerException(null)> is a org.junit.internal.runners.model.MultipleFailureException
     [exec]     Stacktrace was: org.junit.internal.runners.model.MultipleFailureException: There were 2 errors:
     [exec]       java.lang.NullPointerException(null)
     [exec]       java.lang.NullPointerException(null)
     [exec]     	at org.junit.runners.model.MultipleFailureException.assertEmpty(MultipleFailureException.java:67)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:39)
```
```
     [exec] com.liferay.portal.search.elasticsearch7.internal.index.CompanyIndexFactoryTest > testIndexSettingsContributor FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.index.CompanyIndexFactory._processContributions(CompanyIndexFactory.java:559)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.index.CompanyIndexFactory.access$000(CompanyIndexFactory.java:78)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.index.CompanyIndexFactory$1.addingService(CompanyIndexFactory.java:276)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.index.CompanyIndexFactory$1.addingService(CompanyIndexFactory.java:266)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-05/test-1-39/test-portal-acceptance-pullrequest(master)/4880/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
Thanks for cathing this! Will fix and resend

**Comment by slnn** [comment]
Fix and resend in https://github.com/liferay-core-infra/liferay-portal/pull/4656

**Pull request closed without merging**
