### PR TITLE
[Components with more than 1 service] LPS-183005 Refactor BulkSelectionFactory components from Document Library module

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-183005](https://issues.liferay.com/browse/LPS-183006)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:help

**Comment by RenanUmV** [comment]
ci:test:dl-store

**Comment by rafaprax** [comment]
Hey @RenanUmV, please exclude the `asm-commons.jar` from your changes. Thx

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:document

**Comment by Kvale1733** [comment]
ci:test:dl-store

**Comment by Kvale1733** [comment]
@RenanUmV Regression found. Category not saved when editing document category.

Steps to reproduce:
1. Go to Categorization > Categories
2. Add Vocabulary "Topic" (Top left plus)
3. Add Category "Category"
4. Go to Content and Data > Documents and Media
5. Add any Document and publish
6. Click on the checkbox on the top left of the document to select it
7. On the top right click "Edit Categories"
8. Select created "Category" and save
9. Go to edit the document

Expected Results: Can view Category under Topic vocabulary
Actual Results: Selected category did not save


Here's how it should work

https://user-images.githubusercontent.com/90647688/235485881-991708d8-302a-472a-bc29-b86cd33306ef.mp4

**Pull request closed without merging**
