### PR TITLE
[TS] LPS-201892

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**
# Motivation

Right now there is no way to clean mail fields since the blank value is consider an obfuscated value and no action is performed over the PortletPreferences.

**Steps to Reproduce:**

1. Access Instance Settings > Email >Mail Settings and change Outgoing port to 123
2. Access again Instance Settings > Email > Mail Settings and try to leave that field blank.

**Expected Results:**
The field can be saved with a blank value

**Current Results:**
The value 123 doesn’t get deleted.

# Proposed Solution
Right now blank is the default value when the properties need to be obfuscated. The reason to do this is to avoid providing specific configuration details, specially for LXC environments, see [LPS-163793](https://liferay.atlassian.net/browse/LPS-163793)

So the idea is to reset preferences at the backend when a null/empty value is received.

A blank value can mean two things:
 * The user hasn't changed the "obfuscated" value, so the preferences can be reset because that means that the default (system setting or portal.properties) will be used.
 * The user introduced previously a value, saved it, and know wants to remove it to use the default value. In this case the property must be reset to reflect this change.

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Reviewed also and approved by the Platform Expierence team here: https://github.com/liferay-platform-experience/liferay-portal/pull/370

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found. Test following bug steps passed.

**Comment by tinatian** [comment]
@marianoalvarosaiz 
This issue is caused by fix of https://liferay.atlassian.net/browse/LPS-163793.

The fix of LPS-163793 is actually not very good. There is already a solution introduced to deal with obfuscated values, for example MAIL_SESSION_MAIL_POP3_PASSWORD by using Portal.TEMP_OBFUSCATION_VALUE, and the fix of LPS-163793 introduced a new way and the new way causing the issue you have now.

Your fix is based on the bad fix of LPS-163793 which has to introduce the reset to make sure the functions work, and this is causing the code is more inconsistent when dealing with obfuscated values.

I would like the obfuscated values can be addressed in the same way. Either the way introduced in LPS-163793 or Portal.TEMP_OBFUSCATION_VALUE.

Could you please resend?

Thanks.
Tina.

**Comment by marianoalvarosaiz** [comment]
Hi @tinatian ,

 the problem of using Portal.TEMP_OBFUSCATION_VALUE is that the value will be somehow obfuscated and its true value won't appear, but visually, in the UI it will appear the literal TEMP_OBFUSCATION_VALUE because the type of the fields isn't password, so the browser will display the value normally.

So when I created the solution I thought of two alternatives:

- Change the type of the input fields to password. From a usability point of view this seemed weird to me.
- Create a new css class with the style `-webkit-text-security: disc` and apply it to these fields. I talked with the frontend infra team and they aren't using this in the portal.

Do you have any other idea to use the obfuscation literal, but don't display it?

Kind regards.

**Comment by tinatian** [comment]
@marianoalvarosaiz For the issue https://liferay.atlassian.net/browse/LPS-163793, if you do not allow a non-admin user to see some fields, it does not make sense to let non-admin user to modify those fields, right?

If that's the case, we do not need to do https://github.com/liferay/liferay-portal/commit/72d4e74bceb2e5661ef10197a70d5dd7564ce25e.

Thus, my suggestion would be 
1. Revert fix for LPS-163793
2. Refix LPS-163793 by not allowing non-admin user to see those fields 

What do you think?

Tina

**Comment by marianoalvarosaiz** [comment]
@tinatian the problem with that approach is the special situation in LXC

They do the following:
- They set through portal properties a default SMTP server for all customers.

They need:

- They don't want those properties to be visible for each instance admin because they consider displaying that information as a leak.
- The omniadmin should be able to see those properties.
- Each instance admin should be able to modify those properties because they may want to use a specific SMTP configuration.

So they don't display the properties even for instance admins probably because it is the simplest way to solve it. If not they should:

- Check if the displayed property value is the same as the one set in the portal properties.
    - If not it means that it is not the default SMTP LXC server provided by Liferay, so it can be visible and there would be not Liferay internal SMTP server information leak.
    - If it is the same (what we are displaying is the portal properties config) it shouldn't be displayed because it will mean that we are displaying Liferay internal SMTP.

**Comment by marianoalvarosaiz** [comment]
@tinatian see https://github.com/liferay-core-infra/liferay-portal/pull/6341. I've created a new pull separating system/company configuration.

**Pull request closed without merging**
