### PR TITLE
[Replace Non-Blocking Usage] LPS-198502 Replace non-blocking ServiceProxyFactory usages in classes PermissionCheckerFactoryUtil, ServiceAccessPolicyManagerUtil and TunnelAuthenticationManagerUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(10/19 8:19)

**Comment by W2jx** [comment]
no conflicts(10/20 8:52)

**Comment by shuyangzhou** [comment]
@W2jx PermissionCheckerFactoryImpl and TunnelAuthenticationManagerImpl are in portal-impl, the wiring should be done by spring, they should not use ServiceProxyFactory or Snapshot.

**Pull request closed without merging**
