### PR TITLE
[Remove immediate=true usage security part-2]Lps 168433 part 2

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-168433

Resend the changes with the fix which be reverted in https://issues.liferay.com/browse/LPS-169735

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
@slnn no regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
