### PR TITLE
[TS] LPS-155624

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on https://github.com/liferay-core-infra/liferay-portal/pull/948. I only added two SF commits. No change fix logic.

By the way, JournalArticlePersistenceTest is generated by service builder. So I did wrong in https://github.com/liferay-core-infra/liferay-portal/pull/999

cc @ricardocousolr

### CODE REVIEW

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results? Thanks!

**Comment by zhangyan0701** [comment]
Two many tests are aborted in the acceptance job, will trigger again.

**Comment by zhangyan0701** [comment]
ci:test:acceptance

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@yuhai Close as we talked, please resend.

Tina

**Pull request closed without merging**
