### PR TITLE
[update Mockito framework] LPS-153088

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,
This PR updates Mockito to major version 4 and removes the dependency on PowerMock. Thanks!
[LPS-153088](https://issues.liferay.com/browse/LPS-153088)

### CODE REVIEW

**Comment by dantewang** [comment]
@JanisZhang Could you point out the Java code change difference in this PR compared to the last PR? Just let us know which file in which commit, thanks!

cc @tinatian

**Comment by JanisZhang** [comment]
> @JanisZhang Could you point out the Java code change difference in this PR compared to the last PR? Just let us know which file in which commit, thanks!
> 
> cc @tinatian

Hi @dantewang,

Changed files:

1. LPS-153088 Change com.liferay.gradle.plugins.defaults version to 7.0358 in modules/build-buildscript.gradle
 [modules/build-buildscript.gradle](https://github.com/liferay-core-infra/liferay-portal/pull/1087/commits/03d210c2b0bf158a2a0e1a407670114f40d8c392#diff-1e0f7f7171666c5f1201def2304386bbaecc6c8b555779537da645001b6f682c)
 
 2. LPS-153088 Change com.liferay.gradle.plugins.defaults version to 7.0358 in portal-web/build-test.gradle
 [portal-web/build-test.gradle](https://github.com/liferay-core-infra/liferay-portal/pull/1087/commits/759813bdfdfe78e90b9da354a01d67682e01117e#diff-704e92c30715be73c796db7611afff762f2d6af5d835527cc143b6e7d8bb0929)
 
 3.  LPS-153088 Migrate Mockito API to latest in dynamic-data-mapping [`DDMFormDisplayContextTest.java`]
[...ray/dynamic/data/mapping/form/web/internal/display/context/DDMFormDisplayContextTest.java](https://github.com/liferay-core-infra/liferay-portal/pull/1087/commits/969d9777dfa54c1d3daafd17a678122f245d8793#diff-17c17e23c69f94f4df9577730a62dad270c33a31593abff04f900e062d978b00)
 
 4. LPS-153088 Migrate Mockito API to the latest (Misc) [`CookiesPreActionTest.java`]
 [.../cookies-test/src/test/java/com/liferay/cookies/internal/events/CookiesPreActionTest.java](https://github.com/liferay-core-infra/liferay-portal/pull/1087/commits/9d4846ea1e7eaeef2a262b220c3377a7011de523#diff-a4626e8853eb98edc8ede6789e1bd151a7021586d247a903a53b2df2d0f69e9a)

**Comment by JanisZhang** [comment]
@zhangyan0701
Hi Summer, Could you please help to scan the test results? thanks!

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by JanisZhang** [comment]
Hi @dantewang @tinatian ,

Changed files:

1. LPS-153088 Migrate Mockito API to latest in portal-search [SearchBarPortletDisplayContextFactoryTest]
[...search/bar/portlet/display/context/factory/SearchBarPortletDisplayContextFactoryTest.java](https://github.com/liferay-core-infra/liferay-portal/pull/1087/commits/a77ee5e10c5c2ad46311b284d6688b9c81f665b4#diff-3678a8ce628d36b2f6e6d3d1907b76c365834a02a4cf7d6dcf1c1f16ad2c4724)

Thanks for the review.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:acceptance

**Comment by JanisZhang** [comment]
Hi @catarineaguiar , Could you please help me scan the test results? Thanks!

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

Rebase please.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:acceptance

**Comment by JanisZhang** [comment]
Hi @dantewang @tinatian ,

Rebased and changed files:

LPS-153088 Change com.liferay.gradle.plugins.defaults version to 8.0.1 in modules/build-buildscript.gradle
[modules/build-buildscript.gradle](https://github.com/liferay-core-infra/liferay-portal/pull/1087/commits/60086a459ded7c05698799b1cabefbaab0a0f213#diff-1e0f7f7171666c5f1201def2304386bbaecc6c8b555779537da645001b6f682c)

LPS-153088 Change com.liferay.gradle.plugins.defaults version to 8.0.1 in portal-web/build-test.gradle
[portal-web/build-test.gradle](https://github.com/liferay-core-infra/liferay-portal/pull/1087/commits/2b9edfdad3c9c70e7aecf537a2b365335ecbbc78#diff-704e92c30715be73c796db7611afff762f2d6af5d835527cc143b6e7d8bb0929)

Thanks!

**Comment by JanisZhang** [comment]
Hi @zhangyan0701, Could you please help me scan the test results? Thank you.

**Comment by tinatian** [comment]
@shuyangzhou Could you please prioritize this pull? As we upgrade Mockito, API got changed, and we keep getting code conflicts caused by adding/modifying current unit tests.

Thanks.
Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/120555

**Pull request closed without merging**
