### PR TITLE
LPS-148705 Set ExternalReferenceCode with primary key value according…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-148705

/cc @dantewang @tinatian

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@tinatian The change corresponds to https://github.com/brianchandotcom/liferay-portal/pull/114138/commits/8aab03220705a7f41a5a010890440ed41159ad71#diff-eadf898a4db8132dd30bf827fcf5172fdd933835b39e75127e8e6e79855363e6 (use the primary key if not explicitly set).

**Comment by jpince** [comment]
@dantewang @tinatian @slnn please hold this change, Brian just reverted [LPS-143575](https://issues.liferay.com/browse/LPS-143575) https://github.com/brianchandotcom/liferay-portal/compare/4e71c166621a1693b663dab154736e6201859e40...e6b9ee0e895e5134a42eb189853fabf302b5adbb

We will resend the changes for LPS-143575 once the bugs are resolved. If you want this change to be sent with LPS-143575, please forward this PR to @amosfong.

**Comment by tinatian** [comment]
@slnn Based on Jason's comment, I am going to close this pull, please resend if needed.

Thanks.
Tina

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
