### PR TITLE
LPD-28758 Add default admin user configuration to company creation

### PR DESCRIPTION
**Pull request by devopsmystic**

### CODE REVIEW

**Comment by devopsmystic** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@devopsmystic 
1. Please rename variable "String tld = ".foo.bar";"
2. Please simplify test logic, extract common logic into private method.

Please resend.
Thanks.

**Comment by devopsmystic** [comment]
Hi @tinatian 
Thanks for the comments, I will fix these and comeback tommorow.
Btw, should we use this same PR or send a new PR? If its the same PR, its easy to track review comments and progress.

Regards,
Madhu

**Comment by tinatian** [comment]
@devopsmystic Please create a new pull request.

Thanks!

**Pull request closed without merging**
