### PR TITLE
LPS-146536

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by tinatian** [comment]
@marianoalvarosaiz This line may also cause NPE https://github.com/liferay/liferay-portal/blob/f2aab337f7764fc67d34d71ddc3e34ffa28f6c64/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L8675. Please fix this by moving this line (https://github.com/liferay/liferay-portal/blob/f2aab337f7764fc67d34d71ddc3e34ffa28f6c64/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L4591) to a else block of "if (portletConfig == null) {".

Please add corresponding test for it.

Thanks.
Tina.

**Comment by tinatian** [comment]
@marianoalvarosaiz I am going to close this pull,  please resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by marianoalvarosaiz** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/300

**Pull request closed without merging**
