### PR TITLE
LPS-190641 Revert "LPS-181252 Simplify logic, notify the clean up of …

### PR DESCRIPTION
**Pull request by tinatian**
…dsl query to cluster is enough as portal cache changes will be broadcasted to cluster automatically."  Only depending on the auto-broad-cast of portal cache is not enough, we have to trigger the invocation on FinderCacheImpl for each node as each FinderCacheImpl has its own record of finder paths used and dsl query cache names which are going to used to clean up corresponding portal caches.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by catarineaguiar** [comment]
@tinatian regression found:

```
     [exec] com.liferay.portal.cache.internal.dao.orm.EntityCacheImplTest > testNotifyPortalCacheRemovedPortalCacheName FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl._notifyFinderCache(EntityCacheImpl.java:362)
     [exec]         at com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl.notifyPortalCacheRemoved(EntityCacheImpl.java:225)
     [exec]         at com.liferay.portal.cache.internal.dao.orm.EntityCacheImplTest.testNotifyPortalCacheRemovedPortalCacheName(EntityCacheImplTest.java:133)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-07/test-1-30/test-portal-acceptance-pullrequest(master)/7171/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138015

**Pull request closed without merging**
