### PR TITLE
remove_deprecated_for_portal_kernel_part_Three

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

I have removed deprecated for
"SerializationConstants.java",
"FinderPath" and "FinderCache",
"EntityCache.java", "ClassLoaderSession.java",
"JSONUtil.java",
"BaseRequest" and "BaseStructsRequest"
"portal-kernel/src/com/liferay/portal/kernel/exception",
"LanguageConstants.java",
"LockListenerRegistryUtil.java".
Thanks for checking, also see https://github.com/jeffwu0724/liferay-portal/pull/39.

Thanks,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by tinatian** [comment]
@jeffwu0724 Why you did not remove the deprecated EntityCache#putResult? Any real usage of it?

Tina

**Comment by jeffwu0724** [comment]
> @jeffwu0724 Why you did not remove the deprecated EntityCache#putResult? Any real usage of it?
> 
> Tina

Hey Tina, I double checked and I cannot find the real usage of putResult and removeResult. I already removed them and sent this PR again. Thanks for checking!

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@jeffwu0724 
Please remove the usage for LanguageConstants at 
`modules/util/lang-builder/bnd.bnd:	@com.liferay.portal.kernel-*.jar!/com/liferay/portal/kernel/language/LanguageConstants.class,\`

A homework for you : what does "-includeresource:" mean in bnd.bnd, when you want to use it?

Tina.

**Comment by kyle-miho** [comment]
failures are unrelated, clustering license tests are already failing

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@jeffwu0724 code looks good to me, wait for QA to scan test results.

Tina

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Tina.

**Comment by kyle-miho** [comment]
@tinatian @jeffwu0724 failures should be unrelated

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by jeffwu0724** [comment]
Hey @tinatian , Kyle has helped to scan the result

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115199

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115199

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
