### PR TITLE
Lps 190836

### PR DESCRIPTION
**Pull request by slnn**
Hi @dantewang 

This one includes all the changes that moves out expando and the one that removes all these unused methods from Portal interface.

Lily

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:help

**Comment by slnn** [comment]
ci:test:license

**Comment by slnn** [comment]
ci:test:upgrade

**Comment by slnn** [comment]
ci:test:upgrade-all

**Comment by dantewang** [comment]
@slnn Could you exclude LPS-193189 changes? Will there be conflicts if you don't include them?

**Comment by slnn** [comment]
yes, there will be a conflict as this commit https://github.com/liferay-core-infra/liferay-portal/pull/5381/commits/79ebe95055527fa965c03e89d57d599c9c2abefc  also changed the Portal interface

**Comment by Kvale1733** [comment]
@slnn Lots of tests failed due to this compile issue
```
[parallel] /opt/dev/projects/github/liferay-portal/portal-impl/test/unit/com/liferay/portlet/expando/ExpandoValueConversionTest.java:1085: error: cannot find symbol
 [parallel] 	private static class Converter extends ExpandoValueLocalServiceImpl {
 [parallel] 	                                       ^
 [parallel]   symbol:   class ExpandoValueLocalServiceImpl
 [parallel]   location: class ExpandoValueConversionTest
 [parallel] 2 errors
[beanshell] 4099 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 29 minutes.
```
[Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-39/test-portal-acceptance-pullrequest(master)/6925/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
> @slnn Lots of tests failed due to this compile issue
> 
> ```
> [parallel] /opt/dev/projects/github/liferay-portal/portal-impl/test/unit/com/liferay/portlet/expando/ExpandoValueConversionTest.java:1085: error: cannot find symbol
>  [parallel] 	private static class Converter extends ExpandoValueLocalServiceImpl {
>  [parallel] 	                                       ^
>  [parallel]   symbol:   class ExpandoValueLocalServiceImpl
>  [parallel]   location: class ExpandoValueConversionTest
>  [parallel] 2 errors
> [beanshell] 4099 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 29 minutes.
> ```
> 
> [Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-39/test-portal-acceptance-pullrequest(master)/6925/jenkins-console.txt.gz?authuser=0)

Thank @Kvale1733 for catching this! I will fix and update.

**Pull request closed without merging**
