### PR TITLE
[Remove Blocking usages]LPS-187003 portal-kernel | WordsUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(6/19 13:46)

**Comment by W2jx** [comment]
no conflicts(6/20 8:56)

**Comment by dantewang** [comment]
ci:test:stable

**Review by dantewang — APPROVED** [review]

**Comment by W2jx** [comment]
no conflicts(6/23 14.49)

**Comment by W2jx** [comment]
no conflicts(6/26 15:25)

**Comment by W2jx** [comment]
no conflicts(6/27 8:52)

**Comment by W2jx** [comment]
Hi @dantewang  , The reason why we move the class `WordsImpl` to the module is to complete task https://liferay.atlassian.net/browse/LPS-146894 (Portal libs cleanup Part I --- Move jazzy.jar). And class WordsUtil will not be called during startup. So I think we can directly use unblocking ServiceProxyFactory in class WordsUtil.

**Comment by W2jx** [comment]
no conflicts(7/4 14:30)

**Comment by W2jx** [comment]
no conflicts(7/5 13:57)

**Comment by W2jx** [comment]
no conflicts(7/6 8:08)

**Comment by W2jx** [comment]
no conflicts(7/11 13:11)

**Comment by W2jx** [comment]
no conflicts(7/12 8:04)

**Comment by W2jx** [comment]
no conflicts(7/13 15:32)

**Pull request closed without merging**
