### PR TITLE
LPS-158021 Change the way workflow metrics indexes are created on portal startup

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:workflow-metrics

**Comment by catarineaguiar** [comment]
@rafaprax no regressions found.

**Comment by rafaprax** [comment]
Hey @shuyangzhou, this pr is ready for your review. Thx

**Comment by rafaprax** [comment]
Hey, @catarineaguiar and @shuyangzhou, I just fixed a log message and force pushed the branch. So, the test reports are still valid. Thx

Here is the message changed:
https://github.com/liferay-core-infra/liferay-portal/blob/2e303502622e2a435e1c03889beaae12a9887f11/modules/apps/portal/portal-instance-lifecycle-impl/src/main/java/com/liferay/portal/instance/lifecycle/internal/PortalInstanceLifecycleListenerManagerImpl.java#L171

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121569

**Pull request closed without merging**
