### PR TITLE
LPS-183594 move portal-upload to modules part 3

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Shuyang,

In this PR, I am trying to move all the portal-upload usage from portal-impl to modules.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:object

**Comment by zhangyan0701** [comment]
There are some conflicts. Please resolve them first.

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:object

**Pull request closed without merging**
