### PR TITLE
[TS]LPS-152875 - Upgrade org.json:json to 20220320 to resolve DoS vulerability

### PR DESCRIPTION
**Pull request by javalosjr96**
Ticket:
https://issues.liferay.com/browse/LPS-152875

Previous PR:
https://github.com/liferay-core-infra/liferay-portal/pull/829

Description:
In order to be able to update org.json, changes needed to be made in two areas:

The current jabsorb needed to be modified to allow the usage of BigDecimal.
Added the positive character to the list operators to the json parser account for positive scientific notation.

Notes from @mbowerman:

> The reason that we updated jabsorb was because with the latest json library, decimal numbers are now being parsed as BigDecimal by default instead of as doubles. Therefore, we need to have a serializer that can unmarshall a BigDecimal field to a double. Please see the discussion on https://github.com/mbowerman/liferay-portal/pull/122 surrounding this.

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
More SF breakages caused by Brian Chan.

https://github.com/liferay/liferay-portal/commit/6c9e4dd457ac8f20f05ea99f2bdfbd4e0ecb9e4d
https://github.com/liferay/liferay-portal/commit/d775bd4197ff8d8a3524035066aff9aafb0350e0

**Comment by mbowerman** [comment]
I sent him a pull request here: https://github.com/brianchandotcom/liferay-portal/pull/118409

**Comment by mbowerman** [comment]
Looks like there is a PR in review to fix the latest SF error: https://github.com/brianchandotcom/liferay-portal/pull/118479

TBF this one isn't really anyone's fault, because the SF did run on the [pull request that caused the breakage](https://github.com/brianchandotcom/liferay-portal/pull/118434), but it failed to catch the error because the SF's MethodCallsOrderCheck was broken (see [LPS-155254](https://issues.liferay.com/browse/LPS-155254)). Looks like [LPS-155254](https://issues.liferay.com/browse/LPS-155254) was fixed about the same time that the [SF-breaking pull request](https://github.com/brianchandotcom/liferay-portal/pull/118434) was merged

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
finally

**Pull request closed without merging**
