### PR TITLE
Lps 161155 3 23 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Do you know if we have test for auditing scheduler jobs? This change is related to that feature.

Tina

**Comment by vicnate5** [comment]
ci:test:security

**Comment by vicnate5** [comment]
ci:test:security:norebase

**Comment by W2jx** [comment]
see https://github.com/liferay-core-infra/liferay-portal/pull/4099

**Pull request closed without merging**
