### PR TITLE
[TS] LPD-36161

### PR DESCRIPTION
**Pull request by ericyanLr**
**Ticket:** https://liferay.atlassian.net/browse/LPD-36161

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:16275842

**Comment by ericyanLr** [comment]
**ci:report analysis**
Report listed 1 unique failure; but looking through Testray, I found other PRs that experience the exact same test failure. 

Marking this as **QA Passed** and **Ready to Review (no regression)**.

**Comment by tinatian** [comment]
@ericyanLr Please add test logic to PermissionCheckerTest and resend.

Thanks.
Tina

**Pull request closed without merging**
