### PR TITLE
[Remove Stream/Optional usage] LPS-174116 module: object-service

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend, thanks!
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3224
https://issues.liferay.com/browse/LPS-174116

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:object

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by JanisZhang** [comment]
Thanks. @zhangyan0701

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:object

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
@JanisZhang Please resend as talked, thanks!

**Pull request closed without merging**
