### PR TITLE
master qa 72287

### PR DESCRIPTION
**Pull request by kyle-miho**
- LRQA-72287 Add dedicated spring test service builder module to use for testing
- LRQA-72287 buildService
- LRQA-72287 Add service builder component for testray
- LRQA-72287 Add ant tasks needed for automation
- LRQA-72287 Add testcase for testing upgrading the dependency injector from spring to declarative services
- LRQA-72287 Add aop dependency to testcase
- LRQA-72287 Adjust testcase to use new ant command that will make all needed ds code changes
- LRQA-72287 SF

### CODE REVIEW

**Comment by kyle-miho** [comment]
Followed the steps here: https://issues.liferay.com/browse/LPS-89637
Test passes on CI

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@kyle-miho Please help me scan test results.

Tina.

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
@tinatian no unique failures

**Comment by vicnate5** [comment]
@kyle-miho Move the modules to `modules/util/portal-tools-service-builder-spring-sample-api`/`-service`. Rename the testcase to `ServiceBuilderDependencyInjection.testcase`. The component name is fine.

**Comment by tinatian** [comment]
@kyle-miho I am going to close this pull, please resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
