### PR TITLE
[TS] LPS-153713 Use the common pattern in filters to avoid NPE

### PR DESCRIPTION
**Pull request by attilabakay**
hi Team,
Could you review this?

https://issues.liferay.com/browse/LPS-153713

Best,
Attila

----

When this property is turned on I found that there is a second request in the use case explained on the LPS that will be stuck resulting in the following not returning a servletContext.

`ServletContext servletContext  = (ServletContext)httpServletRequest.getAttribute(WebKeys.CTX);`

because the current request will not contain the servletContext. After checking other Filters I found that the usual pattern to get the servletContext in filters is to get it through the filterConfig. I tested the use case and after using the common pattern the issue is resolved.

### CODE REVIEW

**Comment by tinatian** [comment]
@zhangyan0701 Please help me scan test results.

Thanks.
Tina.

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by bakayattila** [comment]
Hi @tinatian @zhangyan0701,
I was wondering if you had the opportunity to progress on this pull request?

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/118382

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
