### PR TITLE
[Remove Spring Extender Usage] LPS-159586 commerce-price-list-service part 2 | 8-24

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:commerce

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results when they finish? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by tinatian** [comment]
@dantewang Close, let's have a talk about this when you are up.

Tina

**Comment by dantewang** [comment]
@shuyangzhou @tinatian Rebased and force pushed. No code change, just a packageinfo change which wasn't generated yesterday when I ran `gw baseline`.

**Comment by shuyangzhou** [comment]
@dantewang please rebase.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122531

**Pull request closed without merging**
