### PR TITLE
[Remove Blocking usages]LPS-189701 bean-portlet | CDIBeanPortletExtension, SpringBeanPortletExtension

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:help

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(7/6 8:08)

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:portlet-deployment

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@catarineaguiar Invoking some more tests, because I'm not sure whether relevant can cover CDI & Spring MVC portlets.

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
@W2jx prossible regression:

```
     [exec] com.liferay.layout.content.page.editor.web.internal.portlet.action.test.GetCollectionFieldMVCResourceCommandTest > testGetCollectionFieldFromDynamicCollectionWithSize FAILED
     [exec]     org.junit.ComparisonFailure: expected:<[gK2sjrV]O> but was:<[ebPdWRC]O>
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:117)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
     [exec]     	at com.liferay.layout.content.page.editor.web.internal.portlet.action.test.GetCollectionFieldMVCResourceCommandTest.testGetCollectionFieldFromDynamicCollectionWithSize(GetCollectionFieldMVCResourceCommandTest.java:342)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-07/test-1-33/test-portal-acceptance-pullrequest(master)/4007/modules-integration-mysql57-jdk8/2/12/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
rebase the code

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:portlet-deployment

**Comment by W2jx** [comment]
ci:test

**Comment by Kvale1733** [comment]
ci:test:jsf

**Comment by W2jx** [comment]
no conflicts(7/11 13:11)

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(7/12 8:04)

**Comment by W2jx** [comment]
no conflicts(7/13 15:32)

**Comment by W2jx** [comment]
no conflicts(7/18 10:20)

**Comment by W2jx** [comment]
no conflicts(7/19 9:37)

**Comment by W2jx** [comment]
no conflicts(7/20 8:54)

**Comment by tinatian** [comment]
@W2jx 
1. Please make ***Bag immutable, it should be only seen as a container about all the parameters needed to use for register
2. Remove BeanPortletRegistrar api and have a service tracker to track the ***Bag and do the register directly

Before, it is exposing register/unregister for people to invoke.
After, register a service and we have a service tracker to do the register/unregister automatically.

Please resend.

Thanks.
Tina.

**Pull request closed without merging**
