### PR TITLE
[Static references] LPS-182283 Remove static references in module change-tracking-web, configuration-admin-web

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:publications

**Comment by dantewang** [comment]
ci:test:usm

**Comment by zhangyan0701** [comment]
ci:test:system

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
