### PR TITLE
[Spring Beans] LPS-201430 Move AsyncMessageListener to module portal-async-advice

### PR DESCRIPTION
**Pull request by JanisZhang**
https://liferay.atlassian.net/browse/LPS-201430

### CODE REVIEW

**Review by dantewang — CHANGES_REQUESTED** [review]
https://github.com/liferay-core-infra/liferay-portal/pull/6110#pullrequestreview-1726576330

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
