### PR TITLE
LPS-164866 Remove_commerce_enterprise_support_part 4

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by tinatian** [comment]
ci:test:commerce

**Comment by jeffwu0724** [comment]
fixed the code conflict and forced pushed

**Comment by jeffwu0724** [comment]
ci:test:commerce

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
Hi @zhangyan0701 , could you please help me to scan the result?
Thanks!

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:stop

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:commerce

**Comment by jeffwu0724** [comment]
fixed the semantic version error

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:commerce

**Comment by jeffwu0724** [comment]
Hi @zhangyan0701 , could you please help me to scan the result again when it is ready?
Thanks!

**Comment by zhangyan0701** [comment]
Some issues seem related:
1. Application menu icon is not clickable in Control Panel > Accounts > Edit account page > Channel Defaults tab.

https://user-images.githubusercontent.com/25576873/196962222-6d9c4824-db10-49f7-b661-cdfed3db0e8b.mp4


2.  Control Panel > Accounts > Edit account page > Channel Defaults tab > CHANNEL ACCOUNT MANAGERS section is empty.
sectionisempty

Expected is:
expected

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
fixed the [bug](https://github.com/liferay-core-infra/liferay-portal/pull/2012#issuecomment-1285546352) and forced pushed.
This bug cannot be reproduced locally now.

**Comment by jeffwu0724** [comment]
Hi @Kvale1733 , could you please help me to scan the result again when it is ready?
Thanks!

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
fixed the code conflict

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Pull request closed without merging**
