### PR TITLE
[TS] LPS-182255 NoSuchLayoutException error when 'Clean Up Orphaned Theme Portlet Preferences'

### PR DESCRIPTION
**Pull request by dcarrillolf**
Ticket: https://liferay.atlassian.net/browse/LPS-182255 (reopened)

- This was reopened because it seems it can occur after upgrading from DXP 7.0 to 7.4.
- In this PR, preferences for missing layouts are kept by default, but 'removing orphaned theme portlet preferences' action can continue successfully.

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
Running upgrade suite to trigger the data cleanup tests

**Comment by vicnate5** [comment]
No regressions found.

**Comment by yuhai** [comment]
Hi @dcarrillolf, the ticket's description seems be different from your [mentioned steps](https://github.com/liferay-core-infra/liferay-portal/pull/5624#issue-1908325685). Could you please update ticket's description and provide the detail reproduction steps?

Thanks,
Hai

**Comment by dcarrillolf** [comment]
Hello @yuhai , please check now.
 
The big problem is that we have not found a way to reproduce it without updating the database. Nevertheless, since it affects to Liferay's Control Panel portlets, it is very likely that it is an upgrade bug.

**Comment by yuhai** [comment]
Hi @dcarrillolf,

Thanks for updating the ticket's description. As your mentioned from the ticket's description.

> the database had wrong portlet preferences since (ownerId=0, ownerType=3, plid=0), and Layout with plid=0 for Control Panel Portlets is not found (usually 1).

I think the fix mainly want to fix the kind of data `ownerId=0, ownerType=3, plid=0`. But the pr seems unreasonable. Please see the below reasons:
1. The kind of data should belong to orphan/dirty data, but the fix didn't delete them. Just skip it. 
2. The action called **Clean up orphaned theme portlet preferences**. This is not right place when we don't know which actions caused the kind of data.

When we don't make sure if the kind of data were caused by our product functions. I think we shouldn't fix it from the product side. For example, if the customer executed one wrong sql to directly update the table and make the dirty data, we shouldn't handle this from our codes. If we can't reproduce the issue or don't know the reason which caused it, for the kind of data, we may suggest the customer to use script to handle/delete them.

Please let me know if you have further concerns.

Thanks,
Hai

**Pull request closed without merging**
