### PR TITLE
[TS] LPS-164385 Do not depend on cluster link. Because of this dependency,…

### PR DESCRIPTION
**Pull request by tinatian**
… VelocityManager and FreeMarkerManager are unavailable when cluster link failed to initialize.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
@yuhai Please verify if this fix works.

Thanks.
Tina

**Comment by yuhai** [comment]
> @yuhai Please verify if this fix works.
> 
> Thanks. Tina

@tinatian,  I tested the same fix before, it didn't work. I will attach the error log.

**Comment by Kvale1733** [comment]
No regressions found.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3399

**Pull request closed without merging**
