### PR TITLE
[commons-lang] LPD-19869 Remove org.apache.commons.lang.time.StopWatch usages

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
rebased due to conflict of a file being removed. no need to retest

**Comment by julschong** [comment]
ci:report:2547848291

**Comment by julschong** [comment]
ci:report:2547813569

**Comment by julschong** [comment]
From update test
```
LocalFile.DBStoreUpgrade#ViewDBStoreArchive621021	https://testray.liferay.com/home/-/testray/case_results/2547814308/history	Unique	java.lang.Exception:  ## ## 1 Liferay Exception was thrown ##  LIFERAY_ERROR: FrameworkEvent ERROR
```

**Comment by julschong** [comment]
ci:test:upgrade

**Comment by julschong** [comment]
ci:report:2547917214

**Comment by julschong** [comment]
@tinatian I think unique failure is unrelated
```
LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive621021	https://testray.liferay.com/home/-/testray/case_results/2547917483/history	Unique	java.lang.Exception:  ## ## 2 Liferay Exceptions were thrown ##  LIFERAY_ERROR: [jcc][t4][102][10040][4.24.92] Batch failure.  The batch was submitted. but at least one exception occurred on an individual member of the batch. Use getNextException() to retrieve the exceptions for specific batched elements. ERRORCODE=-4229. SQLSTATE=null LIFERAY_ERROR: Error for batch element #1: DB2 SQL Error: SQLCODE=-803. SQLSTATE=23505. SQLERRMC=2
```

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6755

**Pull request closed without merging**
