### PR TITLE
LPS-162802 Remove stream/optional usages in InfoSearchClassMapperTrackerImpl

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:tango

**Comment by vicnate5** [comment]
QA please check tango results

**Comment by vicnate5** [comment]
@CarlosBrichete Can you check the Tango results here? I see some unique failures but not sure if they are related.

**Comment by vicnate5** [comment]
@guilhermedcamacho I can confirm now the errors are not related as they are occurring upstream now. So no issues found.

**Comment by guilhermedcamacho** [comment]
Thanks @vicnate5 :+1: 
@shuyangzhou , this PR is ready for your review.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123576

**Pull request closed without merging**
