### PR TITLE
[Spring Beans] LPS-200559 Make AuthVerifierRegistry not a spring bean

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(11/2 8:14)

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(11/3 8:52)

**Comment by W2jx** [comment]
no conflicts(11/6 8:35)

**Comment by W2jx** [comment]
no conflicts(11/7 9:34)

**Comment by W2jx** [comment]
no conflicts(11/8 10:05)

**Comment by W2jx** [comment]
no conflicts(11/9 9:58)

**Comment by W2jx** [comment]
no conflicts（11/13 9:31）

**Comment by W2jx** [comment]
no conflicts(11/14 15:32)

**Comment by tinatian** [comment]
@W2jx Please make this change together with the removal of spring bean "com.liferay.portal.security.access.control.AccessControlImpl", let's move both "com.liferay.portal.security.access.control.AccessControlImpl" and "com.liferay.portal.security.auth.registry.AuthVerifierRegistry" into modules.

1. Inline AuthVerifierPipeline#verifyRequest into AccessControlImpl as it is the only usage
2. Move both "com.liferay.portal.security.access.control.AccessControlImpl" and "com.liferay.portal.security.auth.registry.AuthVerifierRegistry" into modules.

Tina.

**Pull request closed without merging**
