### PR TITLE
[Method References 2] LPS-165445 Directly reference class IndexerRequestBufferExecutor

### PR DESCRIPTION
**Pull request by W2jx**
I remove the deprecated class IndexerRequestBufferExecutor in [this pr](https://github.com/liferay-core-infra/liferay-portal/pull/2663).

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/2544

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:search

**Comment by W2jx** [comment]
no conflicts(12/9 9:42)

**Comment by W2jx** [comment]
Force-Push is just to rebase and resolve conflict about `modules/apps/portal-search/portal-search-api/bnd.bnd`

**Comment by W2jx** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by W2jx** [comment]
no conflicts(12/13  9:49)

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(2022/12/14 9:27)

**Comment by W2jx** [comment]
no conflicts(12/15 9:25)

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127832

**Pull request closed without merging**
