### PR TITLE
LPS-171752

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@catarineaguiar Could you please trigger extra tests to cover the case?

**Comment by catarineaguiar** [comment]
ci:test:data-integration

**Comment by catarineaguiar** [comment]
the suite triggered cover the case the ticket mentioned

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128310

**Pull request closed without merging**
