### PR TITLE
[Method References 3] LPS-179400

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-179400

Convert method reference to field reference in `WikiWebComponentProvider`, `NPMResolverProvider`

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by JanisZhang** [comment]
forwarding this one as it's approved and passed QA review. cc @dantewang @shuyangzhou @tinatian

**Comment by JanisZhang** [comment]
ci:forward

**Comment by JanisZhang** [comment]
ci:forward:force

**Pull request closed without merging**
