### PR TITLE
LPS-165622 update Jackson Databind to 2.13.4.2

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-165622.
Thanks for checking!

### CODE REVIEW

**Comment by zhangyan0701** [comment]
There are some failures in relevant seems flaky. Will re-run test just to make sure they are unrelated.

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found. All the flakey tests from the previous build pass in the latest relevant.

**Comment by dantewang** [comment]
Hi @jeffwu0724, we notice that the `jackson.core` dependencies in `portal-k8s-agent-impl` are `compileInclude`, while we can actually `compileOnly` them because they are deployed as shared dependencies. See https://github.com/liferay-core-infra/liferay-portal/pull/2331/commits/b8c1f8301ed312e551a15a33c17facba225d8e11

On the other hand, I wonder if `jackson.dataformat` and `jackson.datatype` there should also be in-sync with the `jackson.core` versions.


It seems we also have a bug when running `ant build-lib-versions`. All timestamps in versions-complete.xml are updated which is clearly wrong. In the duplicate PR, Hai manually removed `jackson.core` items because they are no longer included: https://github.com/liferay-core-infra/liferay-portal/pull/2331/commits/32eb351fc5787363cfea177c82daf374051eb403

**Comment by jeffwu0724** [comment]
Hi @dantewang ,
Thanks for reaching out. I have updated my PR that
1. use compileOnly instead for `portal-k8s-agent-impl`
2. For `jackson.dataformat` and `jackson.datatype`, I will try to also upgrade them to 2.13.4 for now
3. For `ant build-lib-versions`, there are two bugs that exist, which are cannot generate versions.html, and the timezone issue when generating versions-complete.xml. I have sent two PRs to fix them. Please see [LPS-167051](https://github.com/liferay-core-infra/liferay-portal/pull/2285#issuecomment-1300766400) and [LPS-167371](https://github.com/liferay-core-infra/liferay-portal/pull/2369#issuecomment-1306458162). 
I am wondering if it will be better to send this PR after the fixes are merged.

Thanks,
Jeff

**Pull request closed without merging**
