### PR TITLE
[TS] LPS-190994

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@marianoalvarosaiz there are some conflicts, please resolve them. Thanks

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
@catarineaguiar conflicts fixed

**Comment by zhangyan0701** [comment]
Issue found:
NPE error in test [com.liferay.asset.publisher.web.internal.scheduler.CheckAssetEntrySchedulerJobConfigurationTest](https://testray.liferay.com/home/-/testray/case_results/2443689172):
```
##
## com.liferay.asset.publisher.web.internal.scheduler.CheckAssetEntrySchedulerJobConfigurationTest > testGetTriggerInvalidCronExpression
##

	java.lang.NullPointerException
```
```
##
## com.liferay.asset.publisher.web.internal.scheduler.CheckAssetEntrySchedulerJobConfigurationTest > testGetTriggerEmptyCronExpression
##

	java.lang.NullPointerException
```
```
##
## com.liferay.asset.publisher.web.internal.scheduler.CheckAssetEntrySchedulerJobConfigurationTest > testGetTriggerValidCronExpression
##

	java.lang.NullPointerException
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-10/test-1-29/test-portal-acceptance-pullrequest(master)/8431/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

Manual testing for LPS-190994 passed.

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142567

**Pull request closed without merging**
