### PR TITLE
[Optional Reference]LPS-185685 Convert the Optional references to static references using…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-185685

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:saml

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
