### PR TITLE
[Method References 2] LPS-164455 Convert method reference to ServiceTrackerMap in module asset-publisher-web

### PR DESCRIPTION
**Pull request by W2jx**
Hi  @tinatian @dantewang , I convert method reference to ServiceTrackerMap in module asset-publisher-web.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @catarineaguiar , Could you please help me check the test results ? Thanks!

**Comment by Kvale1733** [comment]
@W2jx No regressions.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
