### PR TITLE
[Optional Reference] LPS-185138 Convert the Optional Dynamic Greedy references to ServiceTracker in class UpgradeRecorder

### PR DESCRIPTION
**Pull request by haydenzheng314**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4825
Ticket: https://liferay.atlassian.net/browse/LPS-185138

@dantewang  Conveting this reference to ServiceTracker because it can't be neither a a snapshot nor a hard reference.

If `ReleaseManager` is a dynamic snapshot means it's lazy, it will start at the time the service is get. But the service needs to start early than that. Otherwise it's reference `ReleasePublisher` won't be activated on time and register service `Release`. This causes chaining null references and finally get the "missing default store" error.

If `ReleaseManager` is a hard reference, the reference `ModuleServiceLifecycle` in `ReleasePublisher` has `target = ModuleServiceLifecycle.PORTAL_INITIALIZED` which is registered in upgrade module phase. While the initial schema version needs to be set before upgrading, using hard reference makes `serviceLatch` can't get `appender` until upgrading module. At that time schema version has already upgraded to the latest so it set a final schema version as an initial one.

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by LisztLiszt** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@LisztLiszt No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@tinatian Please see Hayden's comment.

Basically during upgrade, `UpgradeRecorder` needs to start before upgrading core, while `ReleaseManager` & `ReleasePublisher` start after that and before upgrading modules. Both `Snapshot` and hard reference changes that order, leading to different kinds of errors.

Currently we don't have a better idea for this, so we changed the optional ref to an eager service tracker. Or maybe just keep this one?

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5042

**Pull request closed without merging**
