### PR TITLE
[Optional References]LPS-185571 Convert the Optional Dynamic Greedy references to static r…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-185571

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@slnn Regressions found

1) Many integration tests failing due to the following issue. Such as
com.liferay.portal.search.elasticsearch7.internal.query.WrapperQueryTest
```
[exec] com.liferay.portal.search.elasticsearch7.internal.aggregation.metrics.WeightedAvgAggregationTest > testWeightedAverage FAILED
     [exec]     java.lang.NoClassDefFoundError: Could not initialize class com.liferay.portal.search.elasticsearch7.internal.ElasticsearchIndexingFixture$4
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchIndexingFixture._createElasticsearchSpellCheckIndexWriter(ElasticsearchIndexingFixture.java:200)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchIndexingFixture._createIndexWriter(ElasticsearchIndexingFixture.java:286)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchIndexingFixture.setUp(ElasticsearchIndexingFixture.java:115)
     [exec]         at com.liferay.portal.search.test.util.indexing.BaseIndexingTestCase.setUpIndexingFixture(BaseIndexingTestCase.java:323)
     [exec]         at com.liferay.portal.search.test.util.indexing.BaseIndexingTestCase.setUp(BaseIndexingTestCase.java:120)
     [exec]         at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-40/test-portal-acceptance-pullrequest(master)/2615/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

2)Semver issue
```
[exec] > Task :apps:portal-search:portal-search-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.search.suggest                  MAJOR      1.1.0      1.1.0      2.0.0      VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.portal.search.suggest.BaseGenericSpellCheckIndexWriter
     [exec] 		-   field      nGramHolderBuilder
     [exec] 			-   access     protected
     [exec] 			-   annotated  org.osgi.service.component.annotations.Reference
     [exec] 				-   property   cardinality='OPTIONAL'
     [exec] 				-   property   policy='DYNAMIC'
     [exec] 				-   property   policyOption='GREEDY'
     [exec] 			-   return     com.liferay.portal.kernel.search.suggest.NGramHolderBuilder
     [exec] [Baseline Warning] Bundle Version Change Recommended: 12.0.0
```
[Log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-28/test-portal-acceptance-pullrequest(master)/6524/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
@slnn Please fix the failures and resend.

**Comment by slnn** [comment]
Please see https://github.com/liferay-core-infra/liferay-portal/pull/4680

**Pull request closed without merging**
