### PR TITLE
[Remove Blocking Usages] LPS-188899 Removing Unnecessary Usages of ServiceProxyFactory.newServiceTrackedInstance with blocking set to true in class MimeTypesUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
@W2jx regressions found:

```
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal/portal-upload/src/test/java/com/liferay/portal/upload/internal/LiferayFileItemTest.java:37: error: package org.osgi.framework does not exist
[beanshell]      [exec] import org.osgi.framework.BundleContext;
[beanshell]      [exec]                          ^
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal/portal-upload/src/test/java/com/liferay/portal/upload/internal/LiferayFileItemTest.java:38: error: package org.osgi.framework does not exist
[beanshell]      [exec] import org.osgi.framework.FrameworkUtil;
[beanshell]      [exec]                          ^
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal/portal-upload/src/test/java/com/liferay/portal/upload/internal/LiferayFileItemTest.java:39: error: package org.osgi.framework does not exist
[beanshell]      [exec] import org.osgi.framework.ServiceRegistration;
[beanshell]      [exec]                          ^
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal/portal-upload/src/test/java/com/liferay/portal/upload/internal/LiferayFileItemTest.java:221: error: cannot find symbol
[beanshell]      [exec] 	private static final BundleContext _bundleContext =
[beanshell]      [exec] 	                     ^
[beanshell]      [exec]   symbol:   class BundleContext
[beanshell]      [exec]   location: class com.liferay.portal.upload.internal.LiferayFileItemTest
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal/portal-upload/src/test/java/com/liferay/portal/upload/internal/LiferayFileItemTest.java:223: error: cannot find symbol
[beanshell]      [exec] 	private static final MockedStatic<FrameworkUtil>
[beanshell]      [exec] 	                                  ^
[beanshell]      [exec]   symbol:   class FrameworkUtil
[beanshell]      [exec]   location: class com.liferay.portal.upload.internal.LiferayFileItemTest
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal/portal-upload/src/test/java/com/liferay/portal/upload/internal/LiferayFileItemTest.java:226: error: cannot find symbol
[beanshell]      [exec] 	private static ServiceRegistration<MimeTypes> _mimeTypesServiceRegistration;
[beanshell]      [exec] 	               ^
[beanshell]      [exec]   symbol:   class ServiceRegistration
[beanshell]      [exec]   location: class com.liferay.portal.upload.internal.LiferayFileItemTest
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal/portal-upload/src/test/java/com/liferay/portal/upload/internal/LiferayFileItemTest.java:53: error: cannot find symbol
[beanshell]      [exec] 			FrameworkUtil.getBundle(Mockito.any())
[beanshell]      [exec] 			^
[beanshell]      [exec]   symbol:   variable FrameworkUtil
[beanshell]      [exec]   location: class com.liferay.portal.upload.internal.LiferayFileItemTest
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal/portal-upload/src/test/java/com/liferay/portal/upload/internal/LiferayFileItemTest.java:224: error: cannot find symbol
[beanshell]      [exec] 		_frameworkUtilMockedStatic = Mockito.mockStatic(FrameworkUtil.class);
[beanshell]      [exec] 		                                                ^
[beanshell]      [exec]   symbol:   class FrameworkUtil
[beanshell]      [exec]   location: class com.liferay.portal.upload.internal.LiferayFileItemTest
[beanshell]      [exec] 8 errors
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-40/test-portal-acceptance-pullrequest(master)/6599/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(10/12 9:54)

**Comment by W2jx** [comment]
Hi @dantewang , this PR has been checked.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Comment by dantewang** [comment]
ci:forward:force

**Comment by W2jx** [comment]
ci:forward:force

**Comment by W2jx** [comment]
ci:forward:force

**Comment by W2jx** [comment]
ci:forward:force

**Comment by W2jx** [comment]
no conflicts(10/16 8:59)

**Comment by W2jx** [comment]
no conflicts(10/17 8:23)

**Comment by W2jx** [comment]
ci:forward:force

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142294

cc @shuyangzhou

**Pull request closed without merging**
