### PR TITLE
[Component with its own class name as service type] LPS-195066 Refactor ContextProvider components from frontend and message-board modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-195066

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:lima

**Comment by MrJohn1911** [comment]
ci:test:frontend

**Comment by catarineaguiar** [comment]
@MrJohn1911 failure on startup:

```
[beanshell] 2023-09-04 09:47:16.264 WARN  [main][DependencyManagerSyncUtil:73] Declarative Service Unsatisfied Component Checker check result: 
[beanshell] Bundle {id: 836, name: com.liferay.frontend.data.set.taglib, version: 1.0.35}
[beanshell] 	Declarative Service {id: 9603, name: com.liferay.frontend.data.set.taglib.internal.jaxrs.application.FDSApplication, unsatisfied references: 
[beanshell] 		{name: _themeDisplayContextProvider, target: null}
[beanshell] 	}
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-09/test-1-25/test-portal-acceptance-pullrequest(master)/3086/functional-smoke-tomcat90-hypersonic20-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Comment by shuyangzhou** [comment]
ci:forward:force

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140551

**Pull request closed without merging**
