### PR TITLE
[Blocker]LPS-201589 add property to allow redirecting to marketplace

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

Resent: https://github.com/liferay-core-infra/liferay-portal/pull/6251
This is for ticket https://liferay.atlassian.net/browse/LPS-201589.
I add a new property "redirectAllowed" in the actionresponse, and see if it is "true" when we try to escape.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hi @Kvale1733 ,

Could you please help me check if this is still be able to reproduce? https://liferay.atlassian.net/browse/LPS-196525 and https://liferay.atlassian.net/browse/LPS-201589.
I have tested locally, and they passed.
Thanks!

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
@jeffwu0724 The bug is not reproducible with your changes, but there is a possible regression:

```
[beanshell]      [exec] com.liferay.portal.util.test.PortalImplLocalizedFriendlyURLTest > testWronglyLocalizedSiteLayoutPublicFriendlyURLWithParams1 FAILED
[beanshell]      [exec]     org.junit.ComparisonFailure: expected:</[en/]web/en3azztf/home?pa...> but was:</[]web/en3azztf/home?pa...>
[beanshell]      [exec]     	at org.junit.Assert.assertEquals(Assert.java:117)
[beanshell]      [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
[beanshell]      [exec]     	at com.liferay.portal.util.test.PortalImplLocalizedFriendlyURLTest._assertLocalizedSiteLayoutFriendlyURL(PortalImplLocalizedFriendlyURLTest.java:649)
[beanshell]      [exec]     	at com.liferay.portal.util.test.PortalImplLocalizedFriendlyURLTest._testWronglyLocalizedSiteLayoutFriendlyURL(PortalImplLocalizedFriendlyURLTest.java:831)
[beanshell]      [exec]     	at com.liferay.portal.util.test.PortalImplLocalizedFriendlyURLTest.testWronglyLocalizedSiteLayoutPublicFriendlyURLWithParams1(PortalImplLocalizedFriendlyURLTest.java:459)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-12/test-1-39/test-portal-acceptance-pullrequest(master)/8634/modules-integration-mysql57-jdk8/4/0/jenkins-console.txt.gz?authuser=0)

**Comment by catarineaguiar** [comment]
hey @jeffwu0724 as it passed for you, no regressions were found.

Thanks for checking.

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
