### PR TITLE
LPS-155715 DB partition Cache

### PR DESCRIPTION
**Pull request by vicnate5**
This pull is based on https://github.com/liferay-core-infra/liferay-portal/pull/1146 and https://github.com/liferay-core-infra/liferay-portal/pull/1147

@tinatian

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
Killed the acceptance run since it has already passed on previous PR.

**Comment by vicnate5** [comment]
Rebased and force pushed.

**Comment by vicnate5** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Tina

**Comment by vicnate5** [comment]
@tinatian This is good to go, just needs rebase due to version bump.

**Comment by tinatian** [comment]
@vicnate5 Could you please rebase this pull, there is no real code conflicts, just packageInfo and bnd, this way we won't need to create a pull and trigger ci tests.

Thanks.
Tina

**Comment by vicnate5** [comment]
rebased and force pushed

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121144

**Pull request closed without merging**
