### PR TITLE
LPS-173279 Remove "immediate = true" from core-infrastructure-1 components

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@daiazius No regressions found.

**Comment by daiazius** [comment]
Hey @tinatian, can you review this pull? Thanks

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129205

**Pull request closed without merging**
