### PR TITLE
LPS-194731 Patch freemarker.org 2.3.29 to replace log4j1 with log4j2

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, please see the ticket's description. https://liferay.atlassian.net/browse/LPS-194731

### CODE REVIEW

**Comment by yuhai** [comment]
ci:stop

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
@dantewang, I just resolved file conflicts and trigger ci test.

**Comment by catarineaguiar** [comment]
ci:test:sf

**Review by dantewang — APPROVED** [review]

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140178

**Pull request closed without merging**
