### PR TITLE
[Reference cleanup]LPS-162729

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to convert method references to field references in portal-security (Misc). Thanks!
https://issues.liferay.com/browse/LPS-162729

Previous PR:https://github.com/liferay-core-infra/liferay-portal/pull/1651

### CODE REVIEW

**Comment by dantewang** [comment]
@JanisZhang Final code looks good, please adjust your commits: first make all referenced `setXXX` methods a simple setter (only containing `_xxx = xxx` logic), so that `_yyy = _xxx.getYYY()` should be put in `activate` methods, and then convert all method references to field references.

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
Hi @dantewang, force pushed and test passed. Thanks!

**Comment by dantewang** [comment]
@shuyangzhou @tinatian Forwarding this one as tests passed and changes are direct replacements.

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
