### PR TITLE
[Clean up CacheManager API]Lps 168275

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-168275

This pull is a dependency of https://issues.liferay.com/browse/LPS-163776 since we decide to refactor the CacheManager's API first and then convert method references to field references.

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
Semantic Versioning error:
```
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.kernel.cache                    MAJOR      13.0.0     13.0.0     14.0.0     VERSION INCREASE REQUIRED
[beanshell] 	>   class      com.liferay.portal.kernel.cache.DynamicPortalCacheManager
[beanshell] 		-   method     isClusterAware()
[beanshell] 			-   return     boolean
[beanshell] 	>   interface  com.liferay.portal.kernel.cache.PortalCacheManager
[beanshell] 		-   field      PORTAL_CACHE_MANAGER_TYPE
[beanshell] 			-   access     final
[beanshell] 			-   access     static
[beanshell] 			-   constant   portal.cache.manager.type
[beanshell] 			-   return     java.lang.String
[beanshell] 		-   method     isClusterAware()
[beanshell] 			-   access     abstract
[beanshell] 			-   return     boolean
[beanshell] [Baseline Warning] Bundle Version Change Recommended: 87.0.0
```

Full console log:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-36/test-portal-acceptance-pullrequest(master)/2437/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Forced push to update semantic version, no logic change

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126387

**Pull request closed without merging**
