### PR TITLE
[TS] LPD-23182

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian https://liferay.atlassian.net/browse/LPD-23182

### CODE REVIEW

**Comment by dantewang** [comment]
See https://liferay.atlassian.net/browse/LPD-23182?focusedCommentId=2629903

**Comment by dantewang** [comment]
@tinatian The SF error is irrelevant to this change.

@jeffwu0724 I tried to add this dependency to the SF property to auto enforce the updated version, but SF also modified a lot of other files, updating versions for e.g. Spring. Do you have any idea about why?

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:report:2561099714

**Comment by dantewang** [comment]
No unique failure in ci-test-startup.

**Comment by dantewang** [comment]
ci:report:2561103500

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:2561154241

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 2561154241.
> 
> Job Link: [generate-testray-csv](https://test-1-19.liferay.com/job/generate-testray-csv/43/)
> 
> Testray CSV Link: [testray-results-2561154241.csv](https://test-1-19.liferay.com/userContent/jobs/generate-testray-csv/builds/43/testray-results-2561154241.csv)

The only unique integration test passes locally.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/149265

**Comment by holatuwol** [comment]
In our testing, the outermost exception was raised by https://github.com/liferay/liferay-portal/blob/7.4.3.47-ga47/modules/apps/portlet-configuration/portlet-configuration-web/src/main/java/com/liferay/portlet/configuration/web/internal/portlet/PortletConfigurationPortlet.java#L622

```
java.lang.IllegalStateException: BundleContext is no longer valid
	at org.eclipse.osgi.internal.framework.BundleContextImpl.checkValid(BundleContextImpl.java:989)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:620)
	at com.liferay.portlet.configuration.web.internal.portlet.PortletConfigurationPortlet.lambda$activate$1(PortletConfigurationPortlet.java:622)
	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerMapImpl.java:246)
	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerMapImpl.java:234)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:891)
```

**Comment by dantewang** [comment]
@shuyangzhou Also see https://github.com/liferay-core-infra/liferay-portal/pull/6889#issuecomment-2060635250

portlet-configuration-web is also a module that is restarted due to customer's fragment modules.

**Comment by tinatian** [comment]
@dantewang @holatuwol Please see https://github.com/liferay-core-infra/liferay-portal/pull/6898.

@holatuwol Could you please verify if https://github.com/liferay-core-infra/liferay-portal/pull/6898 fixes the issue of customer?

**Comment by holatuwol** [comment]
ci:reopen

**Comment by holatuwol** [comment]
Hi @tinatian 

From our previous testing, the issue arises due to a race condition, so even if we are unable to reproduce the issue after 5-10 restarts, we still can't be certain the issue is fixed.

Even if it your suggested changes do fix the issue, wouldn't it be better to still have the changes we're recommending in this pull request in case code gets added in the future which also has this problem? It's a very time-consuming problem to track down due to all of the related logging being disabled by default.

**Comment by tinatian** [comment]
@holatuwol Yes, I will consider adding the logging proposed by the original fix.

Thanks.
Tina.

**Pull request closed without merging**
