### PR TITLE
[Bug Fix] LPS-83930

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on the requirement from https://github.com/liferay-core-infra/liferay-portal/pull/24

For the [question](https://github.com/liferay-core-infra/liferay-portal/pull/24#discussion_r754757034)

> Is there any way to fix that?

I think it is no way to fix. For the current case, asset publisher displays the article, and the article return the content is right and the content includes errorMessages (as portal-web\docroot\html\taglib\portlet\runtime\error.jsp). But when display the content in UI, it will invoke HtmlUtil.stripHtml() to remove html tag (please see [code](https://github.com/yuhai/liferay-portal/blob/LPS-83930-pr3/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/asset/abstract.jsp#L36)).

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
@dantewang, sorry, I forgot to change log level. I just push force the change about making log level for Error.

**Comment by dantewang** [comment]
@yuhai See https://github.com/liferay-core-infra/liferay-portal/pull/30
1. I removed your change to the value of the language key, I think it's enough for UI.
2. I didn't change log level to "error" as after a second thought I think the thing is still under control and warning is enough. But I moved the logging to the beginning of the if-block and changed the message.

**Comment by dantewang** [comment]
ci:close

**Comment by dantewang** [comment]
ci:stop

**Pull request closed without merging**
