### PR TITLE
[Method References 2] LPS-164448

### PR DESCRIPTION
**Pull request by JanisZhang**
Previous P/R: https://github.com/liferay-core-infra/liferay-portal/pull/2496

Hi @tinatian , 
Below shows the main changes in UI after we refactored the `reportFormat`.

1. The selection UI is changed.  
I think it's a UI improvement because it makes the selection UI consistent and easier to read. 
IMG_7306

2. The generated file's suffix is uppercase now, whereas previous is lowercase. 
IMG_7309
To avoid this, I added https://github.com/liferay-core-infra/liferay-portal/pull/2543/commits/d19cbd2e456dc581bb70655df749699bd89b1249 to make the capitalization of the report format value consistent with the previous. 
Previously it uses `reportFormat#getValue()` method to set the format value to lowercase in JSP, and the value is used to generate the file name.

cc  @Kvale1733

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
Hi @dantewang, force-pushed. Thanks!

**Comment by zhangyan0701** [comment]
Possible regression:

[com.liferay.portal.reports.engine.console.service.test.EntryServiceTest](https://testray.liferay.com/home/-/testray/case_results/2081500740) failed with error:
`java.lang.IllegalArgumentException: No enum constant com.liferay.portal.reports.engine.ReportFormat.txt`

Full console log:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-32/test-portal-acceptance-pullrequest(master)/7116/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0

**Pull request closed without merging**
