### PR TITLE
[Move Expando]LPS-194340 Centralize Expando related methods in PortalUtil, Portal a…

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-194340

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
@slnn By the way, why do you want to move these methods to a new util? To move it to module?

**Comment by slnn** [comment]
> @slnn By the way, why do you want to move these methods to a new util? To move it to module? This PR itself is lacking some contexts.

Hi @dantewang 

During our last discussion when cleaning the PortalUtil and Portal interface, you advised to centralize these Expand-related methods from PortalUtil to one place since most of the Expando will be extracted from core to modules.


Lily

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140288

**Pull request closed without merging**
