### PR TITLE
[Remove Stream usage: document-library-service and document-library-item-selector-web]Lps 176228

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-176228

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
@slnn Please keep your extracted method `_getParameters`, and still use `HashMapBuilder` whenever you need to put more things. It's OK to use `HashMapBuilder.putAll` in tests because we prefer readability over performance in test code. Also, after these changes, inline `parameters` wherever possible.

**Comment by dantewang** [comment]
Reopen, commented on the wrong PR.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
