### PR TITLE
LPS-154811

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi,

This is for ticket https://issues.liferay.com/browse/LPS-154811.
Thanks for checking

cc: @antonio91dev

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by tinatian** [comment]
@jeffwu0724 Code looks good to me, wait for QA to scan test results.

Tina.

**Comment by catarineaguiar** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
@jeffwu0724 regression found:

`DSEnvelopeManagerTest`
```
com.liferay.digital.signature.manager.test.DSEnvelopeManagerTest > classMethod FAILED
    java.lang.IllegalArgumentException: Value must not be null
    	at org.apache.felix.cm.impl.CaseInsensitiveDictionary.checkValue(CaseInsensitiveDictionary.java:286)
    	at org.apache.felix.cm.impl.CaseInsensitiveDictionary.<init>(CaseInsensitiveDictionary.java:83)
    	at org.apache.felix.cm.impl.ConfigurationImpl.update(ConfigurationImpl.java:452)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-07/test-1-31/test-portal-acceptance-pullrequest(master)/4314/modules-integration-mysql57-jdk8/1/5/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
Hi @catarineaguiar , would you mind double check for me if this error is related to my PR, please?

**Comment by catarineaguiar** [comment]
@jeffwu0724 I double checked and it is not related.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/120829

**Pull request closed without merging**
