### PR TITLE
[Method References 2] LPS-171231 Convert method reference to ServiceTrackerMap in class MultiLanguageKaleoTaskAssignmentSelector

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
no regressions

**Comment by tinatian** [comment]
@dantewang @W2jx Please slack me when you are available, I would like to have a talk with you about this pull.

**Comment by W2jx** [comment]
see https://github.com/liferay-core-infra/liferay-portal/pull/4688

**Pull request closed without merging**
