### PR TITLE
LPS-143510

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr rebased on [LPS-83930 fix](https://github.com/liferay-core-infra/liferay-portal/pull/52). 

[LPS-33201](https://issues.liferay.com/browse/LPS-33201) caused this and added error messages displayed in UI, but it never worked. I guess [LPS-33201](https://issues.liferay.com/browse/LPS-33201) expected behavior didn't include the UI assert, so we missed the test.

For the fix, I added one new test method **testRenderItselfEmbeddedAndRuntimePortlets** to expose the issue. Actually, we may add response's body assert in _testRenderInfiniteRecursionEmbeddedAndRuntimePortlets_ because _testRenderInfiniteRecursionEmbeddedAndRuntimePortlets_ and **testRenderItselfEmbeddedAndRuntimePortlets** pointed out same [code fragment](https://github.com/yuhai/liferay-portal/blob/LPS-143510/util-taglib/src/com/liferay/taglib/portletext/RuntimeTag.java#L260-L278) test. If you think we should add response's body assert in _testRenderInfiniteRecursionEmbeddedAndRuntimePortlets_(remove **testRenderItselfEmbeddedAndRuntimePortlets** method), I will resend it.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
@dantewang,  LPS-83930 fix was merged to master. I just rebased it on master. No logic changed.

**Comment by dantewang** [comment]
@yuhai So in `RuntimeTag` line 236:

```
		httpServletRequest = DynamicServletRequest.addQueryString(
			restrictPortletServletRequest, parameterMap, queryString, false);
```

The original variable is assigned a new value, which is possibly a dynamic servlet request wrapping the `restrictPortletServletRequest`.

I'm curious that which was added first, this variable assignment, or the error page including?

Anyway, I think this is a bad example of re-assigning variable.

Whoever made this change should **EITHER** re-assign return value to `restrictPortletServletRequest` (as it's the one that may be wrapped):

```
restrictPortletServletRequest = DynamicServletRequest.addQueryString(
	restrictPortletServletRequest, parameterMap, queryString, false);
```

which may not be possible here because the return value type mismatch;

**OR** just use a new variable, for example:

```
HttpServletRequest dynamicHttpServletRequest = DynamicServletRequest.addQueryString(
	restrictPortletServletRequest, parameterMap, queryString, false);
```

so the error page including can still use `httpServletRequest` while other places use `dynamicHttpServletRequest`.

I know that setting attribute using `pageContext` is a common practice in tags in portal, but in this particular class there's another usage of `httpServletRequest.setAttribute` which should work.

Also, when the `httpServletRequest` is assigned with a wrong object, will

```
				String errorMessage = LanguageUtil.get(
					httpServletRequest,
					"the-application-cannot-include-itself");
```
still work?

To conclude my idea: I'd like to see this being fixed by not re-assigning `httpServletRequest`.

cc @tinatian what do you think?

**Comment by dantewang** [comment]
@yuhai For the thing you mentioned in pull request description, yes, please merge it to testRenderInfiniteRecursionEmbeddedAndRuntimePortlets.

**Comment by dantewang** [comment]
ci:close

**Pull request closed without merging**
