### PR TITLE
LPS-182384 move portal-upload to modules Part 1

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
The SF failure seems related:
`1: Library 'org.springframework:spring-web:5.2.24.RELEASE' contains known vulnerabilities(Pivotal Spring Framework contains unsafe Java deserialization methods, https://github.com/advisories/GHSA-4wrc-f8pq-fpqp): ./modules/apps/static/portal-osgi-web/portal-osgi-web-portlet-container-test/build.gradle (SourceCheck:LibraryVulnerabilitiesCheck)`

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Pull request closed without merging**
