### PR TITLE
[LPS-167246 MessageBus] LPS-192680 Remove unused destination liferay/hot_deploy

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@dantewang semver error:

```
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.test.rule                       MAJOR      4.0.0      4.0.0      5.0.0      VERSION INCREASE REQUIRED
[beanshell] 	-   class      com.liferay.portal.test.rule.DestinationAwaitClassTestRule
[beanshell] 		-   extends    com.liferay.portal.kernel.test.rule.AbstractTestRule
[beanshell] 		-   extends    com.liferay.portal.kernel.test.rule.ClassTestRule
[beanshell] 		-   implements org.junit.rules.TestRule
[beanshell] 		-   field      INSTANCE
[beanshell] 			-   access     final
[beanshell] 			-   access     static
[beanshell] 			-   return     com.liferay.portal.test.rule.DestinationAwaitClassTestRule
[beanshell] 		-   method     <init>(java.lang.String[])
[beanshell] 			-   return     void
[beanshell] 		-   method     afterClass(org.junit.runner.Description,java.lang.Object)
[beanshell] 			-   access     abstract
[beanshell] 			-   access     protected
[beanshell] 			-   return     void
[beanshell] 		-   method     afterClass(org.junit.runner.Description,java.util.Set)
[beanshell] 			-   return     void
[beanshell] 		-   method     afterMethod(org.junit.runner.Description,java.lang.Object,java.lang.Object)
[beanshell] 			-   access     abstract
[beanshell] 			-   access     protected
[beanshell] 			-   return     void
[beanshell] 		-   method     afterMethod(org.junit.runner.Description,java.lang.Void,java.lang.Object)
[beanshell] 			-   access     protected
[beanshell] 			-   return     void
[beanshell] 		-   method     apply(org.junit.runners.model.Statement,org.junit.runner.Description)
[beanshell] 			-   return     org.junit.runners.model.Statement
[beanshell] 		-   method     beforeClass(org.junit.runner.Description)
[beanshell] 			-   return     java.util.Set
[beanshell] 		-   method     beforeMethod(org.junit.runner.Description,java.lang.Object)
[beanshell] 			-   access     protected
[beanshell] 			-   return     java.lang.Void
[beanshell] 		-   method     clone()
[beanshell] 			-   access     protected
[beanshell] 			-   return     java.lang.Object
[beanshell] 		-   method     createClassStatement(org.junit.runners.model.Statement,org.junit.runner.Description)
[beanshell] 			-   access     protected
[beanshell] 			-   return     org.junit.runners.model.Statement
[beanshell] 		-   method     createMethodStatement(org.junit.runners.model.Statement,org.junit.runner.Description)
[beanshell] 			-   access     protected
[beanshell] 			-   return     org.junit.runners.model.Statement
[beanshell] 		-   method     equals(java.lang.Object)
[beanshell] 			-   return     boolean
[beanshell] 		-   method     finalize()
[beanshell] 			-   access     protected
[beanshell] 			-   return     void
[beanshell] 		-   method     hashCode()
[beanshell] 			-   return     int
[beanshell] 		-   method     toString()
[beanshell] 			-   return     java.lang.String
[beanshell] [Baseline Warning] Bundle Version Change Recommended: 21.0.0
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-08/test-1-34/test-portal-acceptance-pullrequest(master)/4523/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
Force pushed to resolve sem ver.

ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
CI issue is fixed. Rerunning.

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@dantewang No regressions found.

**Comment by tinatian** [comment]
ci:forward:force

FYI @shuyangzhou

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:stable

**Comment by zhangyan0701** [comment]
@dantewang 

No related failures in the most recent result of stable tests.

**Comment by dantewang** [comment]
It's conflicting with Brian's master, will resend.

**Pull request closed without merging**
