### PR TITLE
LPS-158208

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@zhangyan0701 Please help me scan test results.

Thanks.
Tina

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
@tinatian is this feature really necessary? Where is it going to be used?

**Comment by dantewang** [comment]
@shuyangzhou When moving module framework properties to system.properties, this will be needed.

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
