### PR TITLE
[Remove unused field] LPS-199422

### PR DESCRIPTION
**Pull request by JanisZhang**
Fixed test and resend, thanks.
previous: https://github.com/liferay-core-infra/liferay-portal/pull/5816
https://liferay.atlassian.net/browse/LPS-199422

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142487
cc @shuyangzhou

**Pull request closed without merging**
