### PR TITLE
LPS-143632 Adding LanguageUtil to SF JavaOSGiReferenceCheck

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
@tinatian Hi Tina,
Finally finished with LanguageUtil!
This is on top of the last pull: https://github.com/liferay-core-infra/liferay-portal/pull/1381
Will need to wait for that to merge in

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
could you please help me review the test result?
Thanks!

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121999

**Pull request closed without merging**
