### PR TITLE
LPS-159999 - upgrade PostgreSQL JDBC Driver to version 42.4.1

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-159999.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:environments

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found. Rebase please :)

**Comment by jeffwu0724** [comment]
fix the code conflict for versions-complete.xml and versions.html, which are generated by "ant build-lib-versions", and didn't make changes to other codes

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121580

**Pull request closed without merging**
