### PR TITLE
LPD-31092 Upgrade ConfigAdmin to 1.9.26

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:test:configuration-framework

**Comment by dantewang** [comment]
ci:report:36411296

**Comment by dantewang** [comment]
ci:report:36425233

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 36425233.
> 
> Job Link: [generate-testray-csv](https://test-1-30.liferay.com/job/generate-testray-csv/187/)
> 
> Testray CSV Link: [testray-results-36425233.csv](https://test-1-30.liferay.com/userContent/jobs/generate-testray-csv/builds/187/testray-results-36425233.csv)

**ci-test-relevant**

```
com.liferay.company.change.tracking.test.VirtualHostTableReferenceDefinitionTest
com.liferay.company.service.test.CompanyInfoLocalServiceTest
com.liferay.company.service.test.CompanyLocalServiceDBPartitionTest
com.liferay.company.service.test.CompanyLocalServiceTest
```

These tests often "Failed to run test on CI", and the Jenkins console shows Gradle/CI error. I don't think they are unique.

**ci-test-core-functional**

> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 36411296.
> 
> Job Link: [generate-testray-csv](https://test-1-37.liferay.com/job/generate-testray-csv/244/)
> 
> Testray CSV Link: [testray-results-36411296.csv](https://test-1-37.liferay.com/userContent/jobs/generate-testray-csv/builds/244/testray-results-36411296.csv)

No unique failure shown.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/152307

**Pull request closed without merging**
