### PR TITLE
[Method References 2] LPS-164069

### PR DESCRIPTION
**Pull request by JanisZhang**
This PR is to use serviceTrackerMap instead of the method reference in `layout` . Thanks!
https://issues.liferay.com/browse/LPS-164069

Previous P/R:https://github.com/liferay-core-infra/liferay-portal/pull/2390

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by dantewang** [comment]
@JanisZhang Is this PR modifying the same classes as https://github.com/liferay-core-infra/liferay-portal/pull/2414?

**Comment by JanisZhang** [comment]
@dantewang yes, I will resend this one after that merged.

**Comment by dantewang** [comment]
@JanisZhang An issue with this PR is that you added the service tracker dependencies, but didn't remove them after inlining the classes.

**Comment by JanisZhang** [comment]
Hi @dantewang, I didn't remove the service tracker dependencies in module  `layout-page-template-admin-web` as [PortletConfigurationImporterHelper](https://github.com/liferay-core-infra/liferay-portal/pull/2418/commits/b220f9d29c74eb037e8ec78781750518c6b2bb7c#diff-ad996d6f0130db256f32d22c1ee2222b0bc2329bd9d7ee9d566c40e6fecd5b01) need it.

**Pull request closed without merging**
