### PR TITLE
[Rename Classes] LPS-167604 in portal-search-elasticsearch7, translation

### PR DESCRIPTION
**Pull request by JanisZhang**
This PR is to rename classes in the module `portal-search-elasticsearch7`, `translation`. Thanks!

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
ci:test:translation

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by JanisZhang** [comment]
@Kvale1733 Thanks!

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2361

**Pull request closed without merging**
