### PR TITLE
[Method References 2] LPS-167730 Convert method reference to ServiceTracker in class PortletRegistryImpl

### PR DESCRIPTION
**Pull request by W2jx**
Hi @dantewang , I have resent it.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3622

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
Force-Push is just to resolve the conflict about file `modules/apps/fragment/fragment-api/bnd.bnd`

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:echo

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
@W2jx semver error:

```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/fragment/fragment-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.fragment.contributor                   MAJOR      5.0.0      5.0.0      6.0.0      VERSION INCREASE REQUIRED
     [exec]     	-   interface  com.liferay.fragment.contributor.PortletAliasRegistration
     [exec]     		-   access     abstract
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertFalse(Assert.java:64)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-02/test-1-35/test-portal-acceptance-pullrequest(master)/3732/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
only do semver, no need to rerun test

**Comment by tinatian** [comment]
@W2jx @dantewang This is wrong. https://github.com/liferay-core-infra/liferay-portal/pull/3641/commits/7797ca6854bb96bed7229f5d185907c47244fc42.

After your change, both `NavigationBarsFragmentCollectionContributor` and `PortletRegistryImpl` are waiting for `javax.portlet.Portlet`, every reference is implemented by a service tracker back end, you do not know which one runs first which one not. 

Actually this is the root reason why they have to register a service of a marker interface type (PortletAliasRegistration) .


Tina.

**Comment by dantewang** [comment]
@tinatian Thanks for pointing out!

**Pull request closed without merging**
