### PR TITLE
LPD-8462 remove unused reference _redirectEntryLocalService

### PR DESCRIPTION
**Pull request by titokenzo**

### CODE REVIEW

**Comment by titokenzo** [comment]
ci:test:relevant

**Comment by titokenzo** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:startup

**Comment by titokenzo** [comment]
ci:report:2545342861

**Comment by titokenzo** [comment]
ci:test:relevant

**Comment by titokenzo** [comment]
WebContentDisplay#AddWebContent local test passed

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
