### PR TITLE
[Components with more than 1 service] LPS-188518 Refactor components from adaptative-media and portal-security-sso

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-188518](https://liferay.atlassian.net/browse/LPS-188518)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:help

**Comment by RenanUmV** [comment]
ci:test:security

**Comment by RenanUmV** [comment]
ci:test:lima

**Comment by RenanUmV** [comment]
ci:test:security

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
