### PR TITLE
[Remove Blocking usages] LPS-193174 PortletResourcePermissionFactory and ModelResourcePermissionFactory

### PR DESCRIPTION
**Pull request by haydenzheng314**
Resend as the comment: https://github.com/brianchandotcom/liferay-portal/pull/145046#issuecomment-1847831283
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/6285
Ticket: https://liferay.atlassian.net/browse/LPS-193174
Thanks.

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by LisztLiszt** [comment]
ci:test:upgrade

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
