### PR TITLE
[TS] LPS-176295

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the previous pr is https://github.com/liferay-core-infra/liferay-portal/pull/3684.

cc @javalosjr96

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found. 

PS: Azure test is having issues to run on CI, so the failure is not related to this pull.

**Comment by javalosjr96** [comment]
@yuhai 
Thank you for making those changes.

**Review by dantewang — APPROVED** [review]
@tinatian Besides updating the third-party lib, we also did a clean-up to the import-package exclusions. Hai's commit removed packages that will no longer be calculated to be auto-imported by BND.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131107

**Comment by tinatian** [comment]
@vicnate5 Do we need to test this manually? I remember we did manual test for it last time at https://github.com/liferay-core-infra/liferay-portal/pull/929

**Comment by tinatian** [comment]
ci:test:acceptance

**Comment by vicnate5** [comment]
@catarineaguiar Did you test Azure manually since it wasn't running on CI? If not, can you test?

**Comment by Kvale1733** [comment]
@tinatian @vicnate5 I tested this using the following steps

1. Create a testing container on Azure
2. Setup portal connection to the container
3. Add a document in Documents & Media
4. Assert the document was added to the container on Azure
5. Delete the document from Documents & Media and also remove it from the recycle bin
6. Verify the Document was removed from the Azure container

Expected Results: Documents added/removed from the portal are also added/removed from the container
Actual Results: Documents added to the portal are added to the Azure container. But when the are removed from the portal they remain in the container. Also several "Unable to read image" errors appeared as described in [LPP-47515](https://issues.liferay.com/browse/LPP-47515), which is see is what this is trying to fix.

I tested on a Master bundle to verify and the issue about documents not being removed from the container are present there too so that's not unique to this PR. Though that wasn't in the earlier the initial PR's. Also, with this bundle I got more "Unable to read image" errors and they appeared right after starting the portal. While on Master I got fewer which only appeared after I added and removed a document on the portal.

**Comment by catarineaguiar** [comment]
@Kvale1733 thanks for testing locally.

According to this [comment](https://issues.liferay.com/browse/LPS-151902#:~:text=Jiefeng%20Wu%2C-,After%20talked,-the%20issue%20with) from @yuhai the "Unable to read image" errors are the expected results. Since it needs a Data Migration after enabling Azure Store. 
About the deletion error, does it look like this issue https://issues.liferay.com/browse/LPS-160953?

**Comment by Kvale1733** [comment]
@catarineaguiar Doesn't look like the same issue since I could delete the file but it just wasn't deleted in the container. I'll retest with the migration to verify.

**Comment by javalosjr96** [comment]
@catarineaguiar Thanks for join me on this.

Also just going through the customers migration process, so far so good.

**Comment by javalosjr96** [comment]
@catarineaguiar 
How are you deleting the file?

**Comment by javalosjr96** [comment]
@Kvale1733 @catarineaguiar 

Everything is working,  the document was added and removed.

When you delete the document, also remove it from the recycle bin.
Please re-test and confirm.  

Thank you

**Comment by javalosjr96** [comment]
@catarineaguiar @Kvale1733 
I am encountering this issue:
```
2023-03-03 19:28:44.277 WARN  [liferay/adaptive_media_processor-3][AMMessageListener:88] null
com.liferay.portal.kernel.log.LogSanitizerException: com.azure.storage.blob.models.BlobStorageException: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>_<Error>_  <Code>InvalidOperation</Code>_  <Message>Invalid storage account._RequestId:21da7567-8577-46fb-ae1a-67bd0d445b22_Time:2023-03-03T19:28:44.169Z</Message>_</Error>__ [Sanitized]
```

I'm looking into it, but can you see if you get this error thrown after deleting the image from the recycle bin.

**Comment by javalosjr96** [comment]
It looks to be related to my Azurite Docker Container.

**Comment by Kvale1733** [comment]
@javalosjr96 @catarineaguiar I"m still having the same issues even with the migration. I can delete the file and remove it from recycle bin but it stays in the container. And I still git one initial to read image error. Cat can you test this too and see if you're getting the same issues?

**Comment by catarineaguiar** [comment]
@javalosjr96 I'll re-test it here.

**Comment by catarineaguiar** [comment]
I had the same issue to delete document from the container that Kevin had.

Steps:
`az storage container create -n <container_name> --public-access container --account-name <account_name> --connection-string $AZURE_STORAGE_CONNECTION_STRING`
to create the container

1. Start portal
2. Go to System Settings > File Storage > Azure Blob Storage
3. Fill out connection string and container name
4. Shutdown portal
5. Set the Azure property in portal-ext
6. Start Portal
7. Add a new document
8. check if the document is in the container `az storage blob list --container-name <container_name> --account-name <account_name> --connection-string $AZURE_STORAGE_CONNECTION_STRING`
9. Move document to recycle bin > empty recycle bin
10. check if the document still in the container `az storage blob list --container-name <container_name> --account-name <account_name> --connection-string $AZURE_STORAGE_CONNECTION_STRING`

**Comment by Kvale1733** [comment]
The observed issues are actually caused by: LPS-174240. I will open a ticket for that regression. I reverted that issue locally and deployed to this bundle and testing passed without issue. There are no regressions caused by this PR.

**Comment by Kvale1733** [comment]
Opened a ticket here for the unrelated regression: [LPS-177524](https://issues.liferay.com/browse/LPS-177524)

**Comment by jeffwu0724** [comment]
a fixed for this issue [LPS-177524](https://issues.liferay.com/browse/LPS-177524) has been sent, please see https://github.com/liferay-core-infra/liferay-portal/pull/3748
cc: @javalosjr96 @Kvale1733 @catarineaguiar

**Comment by dantewang** [comment]
@tinatian Since this passed QA, I reopened the PR that was sent to Brian (https://github.com/brianchandotcom/liferay-portal/pull/131107).

**Pull request closed without merging**
