### PR TITLE
[Bug Fix]LPS-165465 Fix the wrong use of the remove method

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have fixed the  bug caused by replacing the Stream API with the Normal loop of Collection.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @catarineaguiar  , Could you please help me check the test results ? Thanks!

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@W2jx Please update the commit message to include the causing commit git id. Thanks!

**Comment by W2jx** [comment]
Hi @dantewang , I have updated the commit message.

**Comment by W2jx** [comment]
Force-Push is just to update the commit message.

**Comment by dantewang** [comment]
@shuyangzhou @tinatian Sent this to Brian: https://github.com/brianchandotcom/liferay-portal/pull/124587 as it's a straight forward fix. Jiaxu has also checked other commits in LPS-150112 and doesn't find more of this issue.

cc @slnn

**Comment by dantewang** [comment]
We found this when reviewing PRs replacing method references to service tracker map/list, etc.

**Pull request closed without merging**
