### PR TITLE
LPS-166231 Remove immediate from frontend components

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-166231

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:frontend

**Comment by catarineaguiar** [comment]
@rafaprax @RenanUmV no regressions found.

**Comment by rafaprax** [comment]
Hey @tinatian, this PR is ready for your review. Thx

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127069

**Pull request closed without merging**
