### PR TITLE
LPS-194731 Patch freemarker.org 2.3.29 to replace log4j1 with log4j2 

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the previous pr is https://github.com/liferay-core-infra/liferay-portal/pull/5442. I found I did one wrong place in the previous pr and closed the pr https://github.com/brianchandotcom/liferay-portal/pull/140178. Please check the wrong place from the commit message https://github.com/liferay-core-infra/liferay-portal/commit/6109a6c56dfceb2d2a5a1de0a228c4b7ccc336f0. The previous issue was LineNumber of the logger infos displayed wrong. Sorry for this.

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found. SF issue is not related

**Comment by dantewang** [comment]
ci:test:sf

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140420

**Pull request closed without merging**
