### PR TITLE
[Bug fix] LPS-107347

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-107347 SF, rename. The logic checks whether database configuration set on the setup wizard page is different with the properties files, but the variable/method name is confusing.
- LPS-107437 Add a portal property for setup wizard to make sure the admin user password is required to be reset, as it needs a portal restart for the configuration to take effect when switching to another database on setup wizard page.
- LPS-107347 Semantic Versioning
- LPS-107347 SF, use alternative API to simplify
- LPS-107347 Avoid setting password reset on the admin user twice when SETUP_WIZARD_ADD_SAMPLE_DATA is enabled

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@dantewang @yuhai Code conflicts, please rebase and resend

Thanks.
Tina

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
