### PR TITLE
[Replace Non-Blocking Usage] LPS-200073 Correct breaking change for commit

### PR DESCRIPTION
**Pull request by haydenzheng314**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/6096
Commit: https://github.com/liferay/liferay-portal/commit/258a63398ddedbdba27e1b193c83c30031509725
The file path should be in the same line as '## What' and follow the new wording according to the documentation.
Thanks.

### CODE REVIEW

**Comment by LisztLiszt** [comment]
no need to trigger ci test

**Comment by dantewang** [comment]
ci:forward

cc @tinatian

**Comment by dantewang** [comment]
ci:forward

**Comment by dantewang** [comment]
@LisztLiszt Conflicts, please rebase.

**Comment by LisztLiszt** [comment]
@dantewang Rebased to fix conflicts

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/144554

**Pull request closed without merging**
