### PR TITLE
LPS-166249 Switch doCount/FindByGroupRoleAndTeamRole to DSLQuery since the InlineSQLHelper isn't designed to work with complex SQL

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: https://issues.liferay.com/browse/LPS-166249

Switched this to a DSLQuery per discussion on https://github.com/liferay-core-infra/liferay-portal/pull/2233

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@mbowerman looks much cleaner! Can you add an integration test for it? I will need to have a debugable test to drive the review.

**Comment by mbowerman** [comment]
@shuyangzhou I've pushed a new commit which adds an integration test.

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions again.

**Comment by shuyangzhou** [comment]
Code looks good now.

@GinsonRen please verify is any performance test case using this query? If so, run a regression test, otherwise this pull is good to go.

**Comment by GinsonRen** [comment]
@shuyangzhou I just ran a round of test, everything looks good, here are the results:
Login:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 7791ecb | 49734 | 263 | -
LPS-166249 | - | 49647 | 268 | -0.17%

WC:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 7791ecb | 64558 | 500 | -
LPS-166249 | - | 64340 | 522 | -0.34%

MB:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 7791ecb | 10033 | 16.6 | -
LPS-166249 | - | 10009 | 16.7 | -0.24%

Blog:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 7791ecb | 16690 | 100 | -
LPS-166249 | - | 16739 | 90.7 | 0.29%

DL:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 7791ecb | 32662 | 365 | -
LPS-166249 | - | 32157 | 324 | -1.55%

AP:
Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 7791ecb | 28769 | 423 | -
LPS-166249 | - | 29296 | 415 | 1.83%

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125807

**Pull request closed without merging**
