### PR TITLE
[Remove Stream/Optional usage] LPS- 174711 asset-service, asset-list-service

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-174711

### CODE REVIEW

**Comment by catarineaguiar** [comment]
echo-acceptance

**Comment by catarineaguiar** [comment]
ci:test:echo-acceptance

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3361

**Pull request closed without merging**
