### PR TITLE
[Components with more than 1 service] LPS-184314 Refactor Miscellaneous components from portal-search-elasticsearch7 module

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://issues.liferay.com/browse/LPS-184314

This pull does not contain the class ElasticsearchConnectionManager because it required a lot of changes, so I will send it in another pull.

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
@MrJohn1911 failure on startup

```
    [junit] Portal log assert failure, see above log for more information: 
    [junit] bundle com.liferay.portal.search.elasticsearch7.impl:6.0.84 (351)[com.liferay.portal.search.elasticsearch7.internal.index.CompanyConcurrentReindexManager(1001)] : findField: Suitable but non-accessible field _searchEngineAdapter in class com.liferay.portal.search.elasticsearch7.internal.index.CompanyIndexFactory, subclass of component class com.liferay.portal.search.elasticsearch7.internal.index.CompanyConcurrentReindexManager
    [junit] junit.framework.AssertionFailedError: 
    [junit] bundle com.liferay.portal.search.elasticsearch7.impl:6.0.84 (351)[com.liferay.portal.search.elasticsearch7.internal.index.CompanyConcurrentReindexManager(1001)] : findField: Suitable but non-accessible field _searchEngineAdapter in class com.liferay.portal.search.elasticsearch7.internal.index.CompanyIndexFactory, subclass of component class com.liferay.portal.search.elasticsearch7.internal.index.CompanyConcurrentReindexManager
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:171)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:86)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8215/functional-smoke-tomcat90-mysql57-jdk11_open/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:search

**Comment by MrJohn1911** [comment]
ci:stop

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
@xbrianlee could you help us to reproduce the unique failure found on [Elasticsearch7#SwitchSidecarToRemote](https://testray.liferay.com/home/-/testray/case_results/2308952890?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1311656491%2Fview%3FtestrayCaseId%3D1311656491%26cur%3D1%26delta%3D200%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc%26resetCur%3Dfalse)?

Thanks in advance.

**Comment by xbrianlee** [comment]
@catarineaguiar I was able to reproduce the issue with the steps in the test. These changes make it longer for Portal to switch from sidecar to remote.

Without these changes, this switch happens in a second:
```
2023-05-19 22:29:06.775 INFO  [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration)][Sidecar:128] Stopping sidecar Elasticsearch
2023-05-19 22:29:07.292 INFO  [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration)][ElasticsearchConnectionManager:306] Connection requested for ID: null
2023-05-19 22:29:07.292 INFO  [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration)][ElasticsearchConnectionManager:351] Getting remote cluster connection with ID: __REMOTE__
```

With these changes, this switch happens in over a minute:
```
2023-05-20 00:25:26.353 INFO  [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration)][Sidecar:128] Stopping sidecar Elasticsearch
2023-05-20 00:26:34.062 INFO  [http-nio-8080-exec-5][ElasticsearchConnectionManager:306] Connection requested for ID: null
2023-05-20 00:26:34.063 INFO  [http-nio-8080-exec-5][ElasticsearchConnectionManager:351] Getting remote cluster connection with ID: __REMOTE__
```

**Comment by catarineaguiar** [comment]
@xbrianlee thanks for checking.

@MrJohn1911 so, the issue is that when switching Portal from sidecar to remote it is taking longer than expected.

Steps to reproduce:

1. Start portal
2. Go to content and data > Web Content > Add a new basic web content
3. Go to Control Panel > Server Admin > Log levels
4. Add a new log level INFO named `com.liferay.portal.search.elasticsearch7.internal.connection` > save
5. On terminal, into liferay-portal directory, run `ant -f build-test-elasticsearch7.xml start-elasticsearch`
6. In liferay logs wait for the message: Returning connection with ID: __REMOTE__

Actual result:
The message in liferay logs is taking longer to appear than expected (minutes)

Expected result:
The message appears in seconds

**Comment by catarineaguiar** [comment]
@xbrianlee do you think it's a real regression or just a future test fix?

**Comment by xbrianlee** [comment]
@catarineaguiar I would say that this is a regression. We're connecting an empty ES instance in this test. Connecting a populated ES instance might take longer which may be perceived as a defect by customers.

**Pull request closed without merging**
