### PR TITLE
LPS-179573 Remove Stream and Optional usages in content-dashboard-web


### PR DESCRIPTION
**Pull request by julschong**
Depend: https://github.com/liferay-core-infra/liferay-portal/pull/4036 otherwise there may be conflicts.

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
@julschong No regressions.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
