### PR TITLE
LPS-185099 Remove Multiple Configurations in SearchBarPortletInstanceConfigurationRenderer

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from https://github.com/liferay-core-infra/liferay-portal/pull/4676

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/135907

**Pull request closed without merging**
