### PR TITLE
LPS-171867 Remove leftovers "immediate = true" from vulcan

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-171867

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by rafaprax** [comment]
follow up of https://github.com/liferay-core-infra/liferay-portal/pull/3144

**Comment by Kvale1733** [comment]
@rafaprax Regression found in

com.liferay.portal.vulcan.internal.jaxrs.JaxRsResourceRegistryImplTest
```
exec] com.liferay.portal.vulcan.internal.jaxrs.JaxRsResourceRegistryImplTest > testGetPropertyValueUnknownClassName FAILED
     [exec]     java.lang.NoSuchFieldException: No field on null with name _jaxRsResourceProperties
     [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.getField(ReflectionTestUtil.java:135)
     [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.setFieldValue(ReflectionTestUtil.java:346)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-25/test-portal-acceptance-pullrequest(master)/6015/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by rafaprax** [comment]
ci:test:headless

**Comment by Kvale1733** [comment]
@rafaprax No regressions found.

**Comment by rafaprax** [comment]
Hey @tinatian, this PR is ready for your review. Thx

**Comment by tinatian** [comment]
@rafaprax As we talked, please resend.

Thanks.
Tina

**Pull request closed without merging**
