### PR TITLE
LPS-148013 Move petra-json-web-service-client to modules/app directly

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,

Main Task: [LPS-147928](https://issues.liferay.com/browse/LPS-147928)
Sub-task 2: [LPS-148013](https://issues.liferay.com/browse/LPS-148013)

TODOs:
- Need to check with team who is in charge of analytics-client-impl to see if it can be removed
- Need to submit a ticket to add json module

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
