### PR TITLE
[Components with more than 1 service] LPS-177336 Refactor ObjectFieldBusinessType components with more than 1 service type from object-service module

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
@daiazius No regressions found.

**Comment by daiazius** [comment]
@rafaprax

**Comment by rafaprax** [comment]
Hey @tinatian, this pr is ready for your review. It is an easy win we found by scanning the file list we have. Thx

**Review by rafaprax — APPROVED** [review]

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131901

**Pull request closed without merging**
