### PR TITLE
LPS-144726  remove the usage of curvesapi

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-144726.
Seems like curvesapi is not necessary dependency when we compile poi. Therefore I am going to clean them away.
Thanks for checking.

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@jeffwu0724 can you resolve the conflict, please? thanks

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
rebase, fixed code conflicts, and rerun the tests

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
rebase, fixed code conflicts in build.gradle and versions.html, and rerun the tests

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by tinatian** [comment]
@jeffwu0724 Please confirm that the reason you remove it because we upgraded to 5 and update the commit message.

Thanks
Tina

**Pull request closed without merging**
