### PR TITLE
[Bug Fix] LPS-107347

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the root issue is that we set the default admin user password reset for **true** when [setup wizard](https://github.com/yuhai/liferay-portal/blob/LPS-107347/portal-impl/src/com/liferay/portal/setup/SetupWizardUtil.java#L374). We use the code [user.isPasswordReset()](https://github.com/yuhai/liferay-portal/blob/LPS-107347/portal-impl/src/com/liferay/portal/struts/PortalRequestProcessor.java#L646) to return the path(password reset) after login. When setup wizard, the admin user's data won't be saved to new MYSQL if the database changes from HSQL to MYSQL because the current portal is connecting with HSQL. Restart portal with MYSQL, user.isPasswordReset() will be false (passwordReset default value is false), so the issue happens.

I also want to explain that the fix will take one change, but I think it is reasonable. The change is that the default admin user will be required to update password when logging into different company instances after creating company instances. That is because the property **default.admin.password.reset.enabled=true** is set in portal-setup-wizard.properties. This is the same behavior with default admin user login to default instance(liferay.com).

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
@yuhai Since the issue is about restarting portal after changing database in setup wizard, could the following condition in `MainServlet.init()` be fulfilled?

```
		if (StartupHelperUtil.isDBNew() &&
			PropsValues.SETUP_WIZARD_ADD_SAMPLE_DATA) {

			try {
				SetupWizardSampleDataUtil.addSampleData(
					PortalInstances.getDefaultCompanyId());
			}
			catch (Exception exception) {
				_log.error(exception, exception);
			}
		}
```

Even if not, I think you can add logic to require the password reset here, instead of changing `UserLocalServiceImpl`. I do want the "reset" to only happen on "new DB" which is consistent with the behavior before your change.

**Comment by dantewang** [comment]
ci:close

Close, please resend, thanks!

**Pull request closed without merging**
