### PR TITLE
LPS-171436 fix Menu Display widget intermittently disappears

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-171436](https://issues.liferay.com/browse/LPS-171436)

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:stop:echo

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by RenanUmV** [comment]
Hey @tinatian , can you review this PR?

**Comment by lucasperj** [comment]
Hi @RenanUmV , sorry to disturb, since dev review not started yet, in the range of this PR commits we (Uniform team) had a bug that could be hiding the unexpected failures in this ticket, do you mind doing the rabase with the most recent Master and running `ci:test:upgrade` again? I'll be watching the results. Thanks!

**Comment by RenanUmV** [comment]
ci:test:upgrade

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
Thats good, thanks again @RenanUmV :rocket:. @catarineaguiar if you have nothing else to add, can you please label it again? Thanks.

**Comment by catarineaguiar** [comment]
sure @lucasperj, thanks for checking.

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
No regressions.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131618

**Pull request closed without merging**
