### PR TITLE
LPD-24485 Fix JSONWebServiceActionsManager concurrent issue exposed by JDK21

### PR DESCRIPTION
**Pull request by julschong**
@tinatian resubmitted from https://github.com/liferay-core-infra/liferay-portal/pull/6924
For issue: https://liferay.atlassian.net/browse/LPD-24485

Testing isolated KBUpgrade test here: https://github.com/julschong/liferay-portal/pull/1229

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
pushed update to flip the initail value of _ensureOpenTreadLocal to True. 
More correct in terms of flow

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
fix threadlocal name

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@julschong This does not seem like a right fix, it might be a workaround. Let's have a talk tomorrow about this

**Pull request closed without merging**
