### PR TITLE
remove_deprecated_part_4_redo

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang ,

I have fixed the errors in https://github.com/liferay-core-infra/liferay-portal/pull/369. I will send another PR with removing the deprecated properties after this PR get merged, see https://github.com/jeffwu0724/liferay-portal/pull/31.
I have removed deprecated methods or classes for "portal-impl/src/com/liferay/portal/upgrade", "portal-impl/src/com/liferay/portal/upload", "portal-impl/src/com/liferay/portal/util", "portal-impl/src/com/liferay/portlet/admin/util", "portal-impl/src/com/liferay/portal/verify", "portal-impl/src/com/liferay/portlet/asset/service/permission"
Thanks for checking. see https://github.com/jeffwu0724/liferay-portal/pull/27.

Thanks,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@kyle-miho Hey Kyle, could you please help me to scan the test result?

Thanks,
Jeff

**Comment by kyle-miho** [comment]
Hey @jeffwu0724 im fairly certain this pr breaks portal-verify-test from compiling, could you take a look at this?
 /opt/dev/projects/github/liferay-portal/modules/apps/portal/portal-verify-test/src/testIntegration/java/com/liferay/portal/verify/test/VerifyUUIDTest.java:216: error: method does not override or implement a method from a supertype

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:stop

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
report failed to generate for the default ci test, rerunning

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by kyle-miho** [comment]
@jeffwu0724 failures unrelated, mainly CI errors

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114100

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
