### PR TITLE
[Bug fix] LPS-136307

### PR DESCRIPTION
**Pull request by dantewang**
https://issues.liferay.com/browse/LPS-136307

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@zhangyan0701 can you check this one?

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/liferay/liferay-portal/pull/4618

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
