### PR TITLE
[Components with more than 1 service] LPS-189113 Refactor PLOLanguageOverrideProvider component 

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://liferay.atlassian.net/browse/LPS-189113

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:peds-sm

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by rafaprax** [comment]
I've just applied some SF modifications that I forgot.

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions

**Comment by dantewang** [comment]
@rafaprax @regiCesar21 See https://github.com/liferay-core-infra/liferay-portal/pull/5195, just minor SF and rename

**Pull request closed without merging**
