### PR TITLE
[Remove Stream usages] LPS-173745 client_base_json_parser.ftl. 

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-173745

Based on previously comment: https://github.com/liferay-core-infra/liferay-portal/pull/3018#issuecomment-1399158553, SF the ftl file.

### CODE REVIEW

**Comment by JanisZhang** [comment]
@Kvale1733 Thanks

**Comment by JanisZhang** [comment]
force-pushed. code conflicts in modules/apps/object/object-rest-api/bnd.bnd.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
Closed this as it has been sent in https://github.com/liferay-core-infra/liferay-portal/pull/3152 cc@dantewang

**Pull request closed without merging**
