### PR TITLE
[LPD-28518 Destination] LPD-28526 Remove DestinationWrapper

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:17725583

**Comment by tinatian** [comment]
Unique failure reported also happen in other pulls, not unique to this pull

**Comment by tinatian** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/151428

**Pull request closed without merging**
