### PR TITLE
[Phase 1] LPS-178022 Remove Stream and Optional usages in portal-search-web part 1

### PR DESCRIPTION
**Pull request by dantewang**
Part 1

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:search

**Comment by kyle-miho** [comment]
relevant aborted, need to rerun

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:search

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@dantewang No regressions.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
