### PR TITLE
[Equinox Http] LPS-199568 Inline ContextController | Part 1

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou This is part 1 which patches the jar for clean-up and injecting interface. Will inline code in Part 2.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142626

**Pull request closed without merging**
