### PR TITLE
LPD-16568 Fix NoticeableThreadPoolExecutorTest test

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPD-16568

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:report:2535043453

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@MrJohn1911 this is a test issue, no need to touch production code.

See https://github.com/brianchandotcom/liferay-portal/pull/146989

**Pull request closed without merging**
