### PR TITLE
LPS-148666 Move juniversalchardet.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
Hey, @koor4356 Can you please help me check the test results when they are ready? Thx

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
@rafaprax 
This looks good, thanks!

**Comment by rafaprax** [comment]
Hey @tinatian, it is ready for your review. Thx

**Comment by tinatian** [comment]
@rafaprax Code looks good to me, please rebase.

Tina.

**Comment by tinatian** [comment]
@rafaprax Code looks good to me, please rebase.

Tina.

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
@tinatian rebased.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114471

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
