### PR TITLE
LPD-X Disable commit immediately

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian @slnn

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:search

**Comment by dantewang** [comment]
ci:report:2554703734

**Comment by dantewang** [comment]
ci:report:2554714277

**Comment by dantewang** [comment]
@tinatian There are 4 unique failures (all about Blueprint) in ci-test-search. I guess this is due to the index update being async now.

**Comment by lipusz** [comment]
cc @BryanEngler

**Comment by lipusz** [comment]
Hey Guys,

We have a spike to see the effect of removing this property or disabling it by default: https://liferay.atlassian.net/browse/LPD-19883

Can you please sync with Bryan before merging to master?

Thanks!

**Comment by dantewang** [comment]
@lipusz We're going to leave this one to Search Team, as @vicnate5 plans. I'll close this one.

By the way, the motivation behind this is that we see in our benchmark performance tests heavy performance penalty due to ES sync refreshing.

**Pull request closed without merging**
