### PR TITLE
[Round 3 Method Reference Static]Lps 181271

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-181271

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:data-engine

**Comment by zhangyan0701** [comment]
Unique failures:

1. [com.liferay.dynamic.data.mapping.form.web.internal.display.context.util.DDMFormGuestUploadFieldUtilTest](https://testray.liferay.com/home/-/testray/case_results/2269015438)
Full console log:
https://testray.liferay.com/reports/production/logs/2023-04/test-1-40/test-portal-acceptance-pullrequest(master)/1519/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

2. [com.liferay.dynamic.data.mapping.form.taglib.internal.servlet.taglib.util.DDMFormTaglibUtilTest](https://testray.liferay.com/home/-/testray/case_results/2269015418)
Full console log:
https://testray.liferay.com/reports/production/logs/2023-04/test-1-40/test-portal-acceptance-pullrequest(master)/1519/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

3. [com.liferay.dynamic.data.mapping.internal.util.DDMIndexerImplTest](https://testray.liferay.com/home/-/testray/case_results/2269015524)
Full console log:
https://testray.liferay.com/reports/production/logs/2023-04/test-1-40/test-portal-acceptance-pullrequest(master)/1519/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by slnn** [comment]
> Unique failures:
> 
> 1. [com.liferay.dynamic.data.mapping.form.web.internal.display.context.util.DDMFormGuestUploadFieldUtilTest](https://testray.liferay.com/home/-/testray/case_results/2269015438)
>    Full console log:
>    https://testray.liferay.com/reports/production/logs/2023-04/test-1-40/test-portal-acceptance-pullrequest(master)/1519/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0
> 2. [com.liferay.dynamic.data.mapping.form.taglib.internal.servlet.taglib.util.DDMFormTaglibUtilTest](https://testray.liferay.com/home/-/testray/case_results/2269015418)
>    Full console log:
>    https://testray.liferay.com/reports/production/logs/2023-04/test-1-40/test-portal-acceptance-pullrequest(master)/1519/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0
> 3. [com.liferay.dynamic.data.mapping.internal.util.DDMIndexerImplTest](https://testray.liferay.com/home/-/testray/case_results/2269015524)
>    Full console log:
>    https://testray.liferay.com/reports/production/logs/2023-04/test-1-40/test-portal-acceptance-pullrequest(master)/1519/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

Thank @zhangyan0701 for catching this, will fix and resend!

Lily

**Comment by slnn** [comment]
Fix and resend in https://github.com/liferay-core-infra/liferay-portal/pull/4273

**Pull request closed without merging**
