### PR TITLE
[Remove Spring extender usages] LPS-159168

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian ,

This PR is to remove spring extender usage in commerce-currency-service, thanks!
https://issues.liferay.com/browse/LPS-159168

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
Hi @catarineaguiar, The code works fine in my local, but the first time  `ci:test:relevant` failed.  After I re-trigger it, all tests passed. Could you please help to take a look? THX

cc/ @dantewang

**Comment by tinatian** [comment]
ci:test:commerce

**Comment by tinatian** [comment]
@JanisZhang Code looks good to me, wait for QA to scan test results.

Tina

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by ling-alan-huang** [comment]
@ling-alan-huang When it gets merged, we need a whitelist to skip SF check for `commerce-service` and `commerce-product-service`, see https://issues.liferay.com/browse/LPS-160078

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by JanisZhang** [comment]
@ling-alan-huang FYI. :)

**Pull request closed without merging**
