### PR TITLE
[Remove Stream/Optional usage: return value part]Lps 170479 part 1

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-170479

 Sub modules of adaptive-media:
modules/apps/adaptive-media/adaptive-media-document-library-thumbnails

modules/apps/adaptive-media/adaptive-media-image-web

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:headless

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2965

**Pull request closed without merging**
