### PR TITLE
[Component with its own class name as service type] LPS-197867 Refactor components from dynamic-data-mapping, commerce and antivirus modules 

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-197867

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:document-antivirus

**Comment by zhangyan0701** [comment]
Issue found:

1. Document with virus can be uploaded.

Reproduce steps:
- Enable antivirus scanning following the doc:
https://liferay.atlassian.net/wiki/spaces/QA/pages/2365752629/How+to+enable+antivirus+scanning+with+DXP
- Go to Documents and Media, upload file with virus: https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/antivirus/antivirus-clamd-scanner-test/testFunctional/tests/dependencies/eicar.com

Result: the file is uploaded successfully.

2. The SF failure should be related:
```
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: No need to register 'AntivirusScannerHelper' in @Component 'service' attribute: /opt/dev/projects/github/liferay-portal/modules/dxp/apps/antivirus/antivirus-async-store/src/main/java/com/liferay/antivirus/async/store/AntivirusScannerHelper.java (SourceCheck:JavaComponentAnnotationsCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:458)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:291)
```

**Pull request closed without merging**
