### PR TITLE
LPS-143632 Remove LanguageUtil from moduels part 3c mixed

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
could you please help me review this test result?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by julschong** [comment]
@slnn Hi Liliy,
Could you please help me review this pull?
Thanks!
CC. @tinatian

**Comment by tinatian** [comment]
@julschong Code looks good to me, please rebase to fix code conflicts.

Thanks.
Tina

**Comment by julschong** [comment]
rebased to resolve conflict (files were removed)

> modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/internal/data/set/filter/RadioClayDataSetFilterContextContributor.java
> modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/internal/data/set/view/table/TableClayDataSetContentRendererContextContributor.java

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/120824

**Pull request closed without merging**
