### PR TITLE
[TS] LPD-24268 

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian https://liferay.atlassian.net/browse/LPD-24268

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
The SF issue is irrelevant.

**Comment by dantewang** [comment]
ci:report:2563544295

**Comment by dantewang** [comment]
ci:report:2563542252

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/149684

**Pull request closed without merging**
