### PR TITLE
[TS]LPS-152875 - Upgrade org.json:json to 20220320 to resolve DoS vulerability

### PR DESCRIPTION
**Pull request by javalosjr96**
Ticket:
https://issues.liferay.com/browse/LPS-152875

Previous PR:
https://github.com/liferay-core-infra/liferay-portal/pull/899

Description:
In order to be able to update org.json, changes needed to be made in two areas:

The current jabsorb needed to be modified to allow the usage of BigDecimal.
Added the positive character to the list operators to the json parser account for positive scientific notation.

Notes from @mbowerman:

> The reason that we updated jabsorb was because with the latest json library, decimal numbers are now being parsed as BigDecimal by default instead of as doubles. Therefore, we need to have a serializer that can unmarshall a BigDecimal field to a double. Please see the discussion on https://github.com/mbowerman/liferay-portal/pull/122 surrounding this.

### CODE REVIEW

**Comment by javalosjr96** [comment]
@shuyangzhou
I ran the SF test on my branch and it failed due to unrelated changes.

Feel free to directly ping me on slack if any changes are necessary.

**Comment by tinatian** [comment]
@dantewang please take this over!

Thanks.
Tina.

**Comment by tinatian** [comment]
@zhangyan0701 please help me scan test results.

Thanks.
Tina

**Comment by dantewang** [comment]
@tinatian The changes looks good to me. The issues Shuyang pointed out in the last PR are fixed.

**Comment by javalosjr96** [comment]
@dantewang Thanks

**Comment by javalosjr96** [comment]
@tinatian 
Rebased to latest master to resolve conflict.

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/118907

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
