### PR TITLE
[Components with more than 1 service] LPS-201728 Remove ReindexSingleIndexerBackgroundTaskExecutor from BackgroundTaskConfigurator initialization

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://liferay.atlassian.net/browse/LPS-201728

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:search

**Comment by rafaprax** [comment]
ci:test:search

**Comment by rafaprax** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@rafaprax Change looks good to me, please check test results, thanks!

**Comment by rafaprax** [comment]
ci:test:search

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
no regression found, https://test-1-1.liferay.com/job/generate-testray-csv/7952/ and https://test-1-1.liferay.com/job/generate-testray-csv/7951/

**Comment by dantewang** [comment]
ci:forward

cc @tinatian

**Pull request closed without merging**
