### PR TITLE
[TS] LPS-134550 Cookies do not follow custom context paths

### PR DESCRIPTION
**Pull request by mbowerman**
This is a follow-up to https://github.com/liferay-core-infra/liferay-portal/pull/6311, implementing @yuhai's recommendations [here](https://github.com/liferay-core-infra/liferay-portal/pull/6311#issuecomment-1855580301).

See original comment below:
> Hi Team,
> 
> https://liferay.atlassian.net/browse/LPS-134550
> 
> Issue:
> Cookies do not follow custom context paths. Setting the context path (for example) to "myportal" resulted in the cookies still end with "/" instead of "/myportal"
> 
> Solution:
> Concat the custom context path to the cookie.
> 
> Testing:
> Tested it locally following the ticket steps on a vanilla version. Clearing all the cookies, reloading the site, shutting down the server and restarting it all worked.
> 
> Please review my PR!
> 
> Best regards,
> Dani

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:2532969238

**Comment by ericyanLr** [comment]
**ci:report analysis**
Looking at the report, the listed unique failures were also found in previous test results. 

Marking this as **Ready to Review (no regression)**

/cc @tinatian

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6558

**Pull request closed without merging**
