### PR TITLE
LPS-180411 Adding support for BINARY_DOUBLE in Hibernate

### PR DESCRIPTION
**Pull request by marcogalluzzi**
After investigation of tests errors of [LPS-180411](https://liferay.atlassian.net/browse/LPS-180411) I've found that the problem appears when returning the result of an AVG() aggregation function in SQL on Oracle 19: by default Oracle returns a value with the BINARY_DOUBLE data type, which is unknown to Hibernate.

I could fix the problem by just adding a cast to the AVG() function in the Blogs tests queries, but I preferred to propose a general solution that could solve the same problem with other queries that uses AVG or other similar aggregation functions.

The general solution is based on the idea of this [document](https://www.goul.co.uk/2008/07/oracle-10g-doubles-and-hibernate.html), although more research and testing has been carried out.

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@marcogalluzzi LGTM, requested Tina review. Could you link the Oracle Document, or quote it in the ticket as a reference? Thanks!

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
For the recent ci-test-relevant, the Testray Analysis Tool reports a unique failure of `com.liferay.headless.admin.user.resource.v1_0.test.UserAccountResourcePerformanceTest`, and I don't see the same failure in the history. But this PR has this test executed twice (2 ci-test-relevant runs), so I think this should be a random failure. @zhangyan0701 Could you verify if my assumption is valid? The analysis tool build number for the recent relevant run is 7383.

**Comment by dantewang** [comment]
@marcogalluzzi I forgot one thing. Could you find an appropriate place to add an integration test case to cover this function? This test case should come in the first commit ("Add test to reveal the issue ..."), pass on all DBs but Oracle without your fix, and pass on all DBs with your fix. Thanks!

**Review by dantewang — CHANGES_REQUESTED** [review]
Change status

**Comment by dantewang** [comment]
@marcogalluzzi Since this PR is not updated for 2 weeks, I'm going to close it for now. Please feel free to resend with a test to cover the functionality. Thanks!

**Pull request closed without merging**
