### PR TITLE
[BLOCKER] LPS-196816 - Script Console

### PR DESCRIPTION
**Pull request by ericyanLr**
Ticket: https://liferay.atlassian.net/browse/LPS-196816

Feel free to let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@ericyanLr No regressions found. Testing passed following the ticket steps.

**Comment by yuhai** [comment]
Hi @ericyanLr,

I talked the fix with Dante. We prefer to using `actionRequest.getMethod().equals(HttpMethods.POST)`, instead of using adding `enctype="multipart/form-data"` to the <form> way.

In addition, please keep the `add_log_category.jsp `changes, except `enctype="multipart/form-data"`. Because the description

> It should not be possible to specify a script using the the GET parameter: _com_liferay_server_admin_web_portlet_ServerAdminPortlet_script

We think the param shouldn't be added to the action's URL. When submitting the form, the param shouldn't display in the URL. It should belongs to the form's data.

Please let me know if you have further concerns.

Thanks,
Hai

**Comment by marianoalvarosaiz** [comment]
see https://github.com/liferay-core-infra/liferay-portal/pull/5785

**Pull request closed without merging**
