### PR TITLE
[Components with more than 1 service] LPS-175994 Refactor DTO Converter components with more than 1 service type from Headless modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Related pull: https://github.com/liferay-core-infra/liferay-portal/pull/3932
Ticket: https://issues.liferay.com/browse/LPS-175994

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:headless

**Comment by Kvale1733** [comment]
@MrJohn1911 Regression found in

com.liferay.headless.builder.test.HeadlessBuilderTest
```
 [exec] com.liferay.headless.builder.test.HeadlessBuilderTest > testHeadlessBuilderApplication FAILED
     [exec]     java.lang.AssertionError: Thread Thread[http-nio-8080-exec-4,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=osgi.logging.com.liferay.headless.batch.engine.internal.resource.v1_0.ImportTaskResourceImpl, message=bundle com.liferay.headless.batch.engine.impl:4.0.40 (522)[com.liferay.headless.batch.engine.internal.resource.v1_0.ImportTaskResourceImpl(1933)] : The activate method has thrown an exception
     [exec]     java.lang.AssertionError: {level=ERROR, loggerName=osgi.logging.com.liferay.headless.batch.engine.internal.resource.v1_0.ImportTaskResourceImpl, message=bundle com.liferay.headless.batch.engine.impl:4.0.40 (522)[com.liferay.headless.batch.engine.internal.resource.v1_0.ImportTaskResourceImpl(1933)] : The activate method has thrown an exception
     [exec]     	at com.liferay.portal.test.rule.LogAssertionTestRule$LogAppender.append(LogAssertionTestRule.java:330)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
     [exec]     	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
     [exec]     	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-32/test-portal-acceptance-pullrequest(master)/8915/modules-integration-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
Hi @Kvale1733, could you please take a look if the HeadlessBuilderTest.testHeadlessBuilderApplication test also fails in master? thanks!

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions.

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
