### PR TITLE
[TS] LPS-191780 Use portal class loader to load in test-portal-ext.properties

### PR DESCRIPTION
**Pull request by DaneszLR**
Hi Team!

Original PR: https://github.com/liferay-core-infra/liferay-portal/pull/5309
The PR which changes this PR contains: https://github.com/liferay-core-infra/liferay-portal/pull/5566

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant:norebase

**Comment by Kvale1733** [comment]
@DaneszLR No regressions found. Testing passed following the ticket steps. Just need to rebase.

**Comment by DaneszLR** [comment]
Hi @Kvale1733 
Conflict has been resolved. Thank you for testing it.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141694

**Pull request closed without merging**
