### PR TITLE
[Components with more than 1 service] LPS-183239 Refactor PortetProvider components from Commerce modules part II

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://issues.liferay.com/browse/LPS-183239

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by lilylcl** [comment]
ci:test:commerce

**Comment by lilylcl** [comment]
ci:test:commerce

**Comment by lilylcl** [comment]
ci:test:relevant

**Comment by lilylcl** [comment]
ci:test:startup

**Comment by lilylcl** [comment]
ci:test:stable

**Comment by lilylcl** [comment]
Hello @MrJohn1911,
There is a [relevant issue](https://testray.liferay.com/home/-/testray/case_results/2289595330)([consoleText](https://testray.liferay.com/reports/production/logs/2023-05/test-1-28/test-portal-acceptance-pullrequest(master)/6397/modules-integration-mysql57-jdk8/0/12/jenkins-console.txt.gz?authuser=0)) related to commerce, would you take a look at it when you get a chance? Thanks in advance!
```
     [exec] com.liferay.headless.commerce.admin.site.setting.resource.v1_0.test.MeasurementUnitResourceTest > testPostMeasurementUnit PASSED
[beanshell] 2023-05-04 09:27:18.838 INFO  [Arquillian-Connector-Thread][BundleStartStopLogger:80] STOPPED com.liferay.headless.commerce.admin.site.setting.test_1.0.0 [1523]
     [exec] 
     [exec] 
     [exec] > Task :apps:commerce:headless:headless-commerce:headless-commerce-admin-site-setting-test:stopTestableTomcat
     [exec] Gradle build finished at 2023-05-04 09:27:18.867.
     [exec] 
     [exec] BUILD SUCCESSFUL in 25m 22s
     [exec] 406 actionable tasks: 108 executed, 298 up-to-date
     [exec] 
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/build/reports/profile/profile-2023-05-04-02-02-00.html
     [exec] A fine-grained performance profile is available: use the --scan option.
[stopwatch] [test.execution.duration: 25:22.439 sec]
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null109965092.properties

stop-app-server:
     [echo] stop.app.server.0.start.timestamp: 05-04-2023 02:27:19:238 PDT
[beanshell] 2023-05-04 09:27:21.202 ERROR [MemoryQuartzSchedulerEngineInstance_Worker-1][ErrorLogger:2361] Unable to notify TriggerListener(s) while firing trigger (Trigger and Job will NOT be fired!). trigger= com.liferay.commerce.price.list.internal.scheduler.CheckCommercePriceModifierSchedulerJobConfiguration.com.liferay.commerce.price.list.internal.scheduler.CheckCommercePriceModifierSchedulerJobConfiguration job= com.liferay.commerce.price.list.internal.scheduler.CheckCommercePriceModifierSchedulerJobConfiguration.com.liferay.commerce.price.list.internal.scheduler.CheckCommercePriceModifierSchedulerJobConfiguration
[beanshell] org.quartz.SchedulerException: TriggerListener 'com.liferay.portal.scheduler.quartz.internal.QuartzSchedulerEngine$TriggerListenerSupportImpl' threw exception: null
[beanshell] 	at org.quartz.core.QuartzScheduler.notifyTriggerListenersFired(QuartzScheduler.java:1836) [bundleFile:?]
[beanshell] 	at org.quartz.core.JobRunShell.notifyListenersBeginning(JobRunShell.java:317) [bundleFile:?]
[beanshell] 	at org.quartz.core.JobRunShell.run(JobRunShell.java:180) [bundleFile:?]
[beanshell] 	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [bundleFile:?]
[beanshell] Caused by: java.lang.NullPointerException
[beanshell] 	at com.liferay.portal.scheduler.quartz.internal.QuartzSchedulerEngine$TriggerListenerSupportImpl.triggerFired(QuartzSchedulerEngine.java:954) ~[?:?]
[beanshell] 	at org.quartz.core.QuartzScheduler.notifyTriggerListenersFired(QuartzScheduler.java:1830) ~[?:?]
[beanshell] 	... 3 more
[beanshell] 2023-05-04 09:27:35.492 INFO  [main][ThemeHotDeployListener:171] 1 theme for classic-theme was unregistered
[beanshell] 2023-05-04 09:27:35.900 INFO  [main][ThemeHotDeployListener:171] 1 theme for minium-theme was unregistered
[beanshell] 2023-05-04 09:27:36.271 INFO  [main][ThemeHotDeployListener:171] 1 theme for dialect-theme was unregistered
[beanshell] 2023-05-04 09:27:36.899 INFO  [main][ThemeHotDeployListener:171] 1 theme for admin-theme was unregistered
[beanshell] 2023-05-04 09:27:37.252 INFO  [main][ThemeHotDeployListener:171] 1 theme for speedwell-theme was unregistered
```

**Comment by MrJohn1911** [comment]
> Hello @MrJohn1911, There is a [relevant issue](https://testray.liferay.com/home/-/testray/case_results/2289595330)([consoleText](https://testray.liferay.com/reports/production/logs/2023-05/test-1-28/test-portal-acceptance-pullrequest(master)/6397/modules-integration-mysql57-jdk8/0/12/jenkins-console.txt.gz?authuser=0)) related to commerce, would you take a look at it when you get a chance? Thanks in advance!
> 
> ```
>      [exec] com.liferay.headless.commerce.admin.site.setting.resource.v1_0.test.MeasurementUnitResourceTest > testPostMeasurementUnit PASSED
> [beanshell] 2023-05-04 09:27:18.838 INFO  [Arquillian-Connector-Thread][BundleStartStopLogger:80] STOPPED com.liferay.headless.commerce.admin.site.setting.test_1.0.0 [1523]
>      [exec] 
>      [exec] 
>      [exec] > Task :apps:commerce:headless:headless-commerce:headless-commerce-admin-site-setting-test:stopTestableTomcat
>      [exec] Gradle build finished at 2023-05-04 09:27:18.867.
>      [exec] 
>      [exec] BUILD SUCCESSFUL in 25m 22s
>      [exec] 406 actionable tasks: 108 executed, 298 up-to-date
>      [exec] 
>      [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/build/reports/profile/profile-2023-05-04-02-02-00.html
>      [exec] A fine-grained performance profile is available: use the --scan option.
> [stopwatch] [test.execution.duration: 25:22.439 sec]
>    [delete] Deleting: /opt/dev/projects/github/liferay-portal/null109965092.properties
> 
> stop-app-server:
>      [echo] stop.app.server.0.start.timestamp: 05-04-2023 02:27:19:238 PDT
> [beanshell] 2023-05-04 09:27:21.202 ERROR [MemoryQuartzSchedulerEngineInstance_Worker-1][ErrorLogger:2361] Unable to notify TriggerListener(s) while firing trigger (Trigger and Job will NOT be fired!). trigger= com.liferay.commerce.price.list.internal.scheduler.CheckCommercePriceModifierSchedulerJobConfiguration.com.liferay.commerce.price.list.internal.scheduler.CheckCommercePriceModifierSchedulerJobConfiguration job= com.liferay.commerce.price.list.internal.scheduler.CheckCommercePriceModifierSchedulerJobConfiguration.com.liferay.commerce.price.list.internal.scheduler.CheckCommercePriceModifierSchedulerJobConfiguration
> [beanshell] org.quartz.SchedulerException: TriggerListener 'com.liferay.portal.scheduler.quartz.internal.QuartzSchedulerEngine$TriggerListenerSupportImpl' threw exception: null
> [beanshell] 	at org.quartz.core.QuartzScheduler.notifyTriggerListenersFired(QuartzScheduler.java:1836) [bundleFile:?]
> [beanshell] 	at org.quartz.core.JobRunShell.notifyListenersBeginning(JobRunShell.java:317) [bundleFile:?]
> [beanshell] 	at org.quartz.core.JobRunShell.run(JobRunShell.java:180) [bundleFile:?]
> [beanshell] 	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) [bundleFile:?]
> [beanshell] Caused by: java.lang.NullPointerException
> [beanshell] 	at com.liferay.portal.scheduler.quartz.internal.QuartzSchedulerEngine$TriggerListenerSupportImpl.triggerFired(QuartzSchedulerEngine.java:954) ~[?:?]
> [beanshell] 	at org.quartz.core.QuartzScheduler.notifyTriggerListenersFired(QuartzScheduler.java:1830) ~[?:?]
> [beanshell] 	... 3 more
> [beanshell] 2023-05-04 09:27:35.492 INFO  [main][ThemeHotDeployListener:171] 1 theme for classic-theme was unregistered
> [beanshell] 2023-05-04 09:27:35.900 INFO  [main][ThemeHotDeployListener:171] 1 theme for minium-theme was unregistered
> [beanshell] 2023-05-04 09:27:36.271 INFO  [main][ThemeHotDeployListener:171] 1 theme for dialect-theme was unregistered
> [beanshell] 2023-05-04 09:27:36.899 INFO  [main][ThemeHotDeployListener:171] 1 theme for admin-theme was unregistered
> [beanshell] 2023-05-04 09:27:37.252 INFO  [main][ThemeHotDeployListener:171] 1 theme for speedwell-theme was unregistered
> ```

Hi @lilylcl, apparently this test is falling in other pull requests too, so I think this is not related to my pull. Thanks for the observation!

**Comment by catarineaguiar** [comment]
Check this similar issue on master https://issues.liferay.com/browse/LRQA-80452

no regressions found.

**Review by rafaprax — APPROVED** [review]

**Pull request closed without merging**
