### PR TITLE
LPD-30459 Show corresponding portal error page rather than redirecting to home page for 404

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:core-functional

**Comment by julschong** [comment]
fix sf in https://github.com/liferay-core-infra/liferay-portal/pull/7509/commits/465df36fef7b8be41c24849fc7d6c34741781db8

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:35008610

**Comment by tinatian** [comment]
ci:report:34805528

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 35008610.
> 
> Job Link: [generate-testray-csv](https://test-1-39.liferay.com/job/generate-testray-csv/448/)
> 
> Testray CSV Link: [testray-results-35008610.csv](https://test-1-39.liferay.com/userContent/jobs/generate-testray-csv/builds/448/testray-results-35008610.csv)

Unique failures in report are not unique to this pull

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 35008610.
> 
> Job Link: [generate-testray-csv](https://test-1-39.liferay.com/job/generate-testray-csv/448/)
> 
> Testray CSV Link: [testray-results-35008610.csv](https://test-1-39.liferay.com/userContent/jobs/generate-testray-csv/builds/448/testray-results-35008610.csv)

Unique failures in report are not unique to this pull

**Comment by tinatian** [comment]
ci:forward:force

FYI @vicnate5 @shuyangzhou I would like to bring this to your attention as I thought this change may cause regression in other teams if anyone depends on the old redirection logic we changed here, like our own test logic we fixed for PortalProxyPath#ProxyPathRedirect. 

We test relevant and core-infra functional here and everything passed, thus I am going to forward it.

FYI @BryanEngler please see changes for search code at https://github.com/liferay-core-infra/liferay-portal/pull/7509/commits/465df36fef7b8be41c24849fc7d6c34741781db8

**Pull request closed without merging**
