### PR TITLE
LPS-166249

### PR DESCRIPTION
**Pull request by noraszel**
Please check the original PR comment here: https://github.com/liferay-appsec/liferay-portal/pull/879#issue-1421595917

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@mbowerman how many custom sqls this issue is affecting? InlineSQLHelper has always been painful and weak for complex sqls. And the fact is, as sql can be crazily complex, InlineSQLHelper will always fail one way or another. Pushing it to cover more cases is not a good choice. It is designed to cover only typical cases. For other wild cases, the right way is to simplify the custom sql to make it working with InlineSQLHelper. That will reduce complexity and also improve overall performance.

In the example from the ticket, the Team subquery really should be taken out to run it as a plain persistence finder, then feed the result back to custom sql as a in list for team ids. This way InlineSQLHelper won't see the extra where cause.

As long as there are not too many custom sqls triggering this issue, we are supposed to simplify the custom sqls. And we are pushing to do more SQL DSL rather than custom sqls, so this kind of issue will be less and less in the future.

**Comment by mbowerman** [comment]
Hello @shuyangzhou,

Is there documentation somewhere stating that the InlineSQLHelper is not intended for use with complex SQL queries? This would have saved me a lot of time if I had known from the start that it was only intended for simple SQL queries and not complex ones. Moreover, since the InlineSQLHelper interface exposed to customization (it is not in an internal subpackage), I really think that this ought to be documented so that customers aren't asking why it's not working correctly if they try to use it with their own custom SQL queries.

> how many custom sqls this issue is affecting?

I don't know how many custom SQLs this issue is affecting. The only one I am aware of is the one mentioned in the ticket, the RoleFinder.findByGroupRoleAndTeamRole.

Previously, the [JournalArticleFinder.findByC_G_F_C_A_V_T_D_C_S_T_D_R](https://github.com/liferay/liferay-portal/blob/ded0e9390637985231e962e4ad4cfa4639eabb26/modules/apps/journal/journal-service/src/main/resources/META-INF/custom-sql/default.xml#L434-L481) query was also affected. [LPS-122276](https://issues.liferay.com/browse/LPS-122276) was created to solve that issue. The solution implemented for [LPS-122276](https://issues.liferay.com/browse/LPS-122276) was to append the resource permission SQL to the final WHERE in the query rather than append it to the first WHERE in the query. However, this solution caused this issue with the RoleFinder.findByGroupRoleAndTeamRole query, since that query needs the permissions SQL to be appended to the first WHERE.

If InlineSQLHelper is indeed not intended for use with complex SQLs, then didn't [LPS-122276](https://issues.liferay.com/browse/LPS-122276) have the wrong solution? We should have simplified/broken up the [JournalArticleFinder.findByC_G_F_C_A_V_T_D_C_S_T_D_R](https://github.com/liferay/liferay-portal/blob/ded0e9390637985231e962e4ad4cfa4639eabb26/modules/apps/journal/journal-service/src/main/resources/META-INF/custom-sql/default.xml#L434-L481) query rather than modifying the InlineSQLHelper.

> In the example from the ticket, the Team subquery really should be taken out to run it as a plain persistence finder, then feed the result back to custom sql as a in list for team ids. This way InlineSQLHelper won't see the extra where cause.

I can do this, but wouldn't it risk reducing the performance in the case that they have a large number of Teams in the Group? Assuming that keywords is null, it would have to fetch all the Teams for that groupId into a List, then insert all those Teams into a large subquery. In fact, if there are more than 2100 Teams that were fetched, this will break SQLServer, because SQLServer has a 2100 parameter limit for its queries.

**Comment by shuyangzhou** [comment]
@mbowerman I don't think there is any documentation for that, but I am not sure.

InlineSQLHelper and LPS-122276 were either before SQL DSL time, or SQL DSL was not mature enough back then.

We are against plain string sql manipulations now, it is too complex and fragile.

As for the pre-running subquery for in list usage, yes, if the subquery result is too large, that SQLServer issue could happen, we have seen that a few times in the past.
If that is really going to be a problem in this case, depending on the business logic, we may paginate them (if possible at all), or try to rewrite that subquery to be table joins, or we would still push for a pure DSL version of inline permission injection.

Just extending InlineSQLHelperImpl to do more complex string sql modification is not an option here, it is really not maintainable overtime.

**Comment by mbowerman** [comment]
ci:close

**Comment by mbowerman** [comment]
Sent new pull request here: https://github.com/liferay-core-infra/liferay-portal/pull/2323

**Pull request closed without merging**
