### PR TITLE
LPS-149982

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Same PR than https://github.com/liferay-core-infra/liferay-portal/pull/516 but rebased to latest master

/cc @shuyangzhou @tinatian @vicnate5

### CODE REVIEW

**Comment by vicnate5** [comment]
@catarineaguiar can you check this one? Should be low risk for regressions since we already tested before the rebase, but look for anything obvious.

**Comment by catarineaguiar** [comment]
@jorgediaz-lr @vicnate5 no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115996

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
