### PR TITLE
LPS-203425 move cxf and geronimo to shared-dependency

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

In this PR, I am moving cxf and geronimo from **portal-remote-jaxrs-whiteboard** to shared-dependencies, so that we do not need to deploy them for other to use. 
The reason why I also move geronimo out is: both **com.liferay.portal.remote.jaxrs.whiteboard** and **shared-dependencies-cxf** are using geronimo-jaxrs_2.1_spec, and **com.liferay.portal.remote.jaxrs.whiteboard** is also using **shared-dependencies-cxf**, which caused some LinkageError.

Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@jeffwu0724 I took a quick look at the test failure of `JaxRsComponentRegistrationTest`. The test can not execute because the JAX RS component registration failed due to 

```
2024-01-02 13:53:39.691 ERROR [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.portal.remote.rest.extender.configuration.RestExtenderConfiguration~f320c73b-3387-483f-a7ae-82e5abe096a8)][LogService:47] [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.portal.remote.rest.extender.configuration.RestExtenderConfiguration~f320c73b-3387-483f-a7ae-82e5abe096a8)] Invocation of 'addApplication' failed.
java.lang.RuntimeException: java.lang.ClassNotFoundException
        at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:64) ~[?:?]
        at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:48) ~[?:?]
        at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator._registerApplication(CXFJaxRsServiceRegistrator.java:95) ~[?:?]
        at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator._registerApplications(CXFJaxRsServiceRegistrator.java:131) ~[?:?]
        at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator._rewire(CXFJaxRsServiceRegistrator.java:183) ~[?:?]
        at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator._addApplication(CXFJaxRsServiceRegistrator.java:71) ~[?:?]
        at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator._swapClassLoader(CXFJaxRsServiceRegistrator.java:204) ~[?:?]
        at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator.addApplication(CXFJaxRsServiceRegistrator.java:37) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_342]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_342]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_342]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_342]
        at org.apache.felix.dm.impl.InvocationUtil.invokeMethod(InvocationUtil.java:230) ~[bundleFile:?]
        at org.apache.felix.dm.impl.InvocationUtil.invokeCallbackMethod(InvocationUtil.java:181) ~[bundleFile:?]
        at org.apache.felix.dm.impl.ComponentImpl.invokeCallback(ComponentImpl.java:665) ~[bundleFile:?]
        at org.apache.felix.dm.impl.ServiceDependencyImpl.invoke(ServiceDependencyImpl.java:517) ~[bundleFile:?]
        at org.apache.felix.dm.impl.ServiceDependencyImpl.invokeCallback(ServiceDependencyImpl.java:327) ~[bundleFile:?]
        at org.apache.felix.dm.impl.ComponentImpl.invokeCallback(ComponentImpl.java:1734) ~[bundleFile:?]
        at org.apache.felix.dm.impl.ComponentImpl.invokeAddOptionalDependencies(ComponentImpl.java:1671) ~[bundleFile:?]
        at org.apache.felix.dm.impl.ComponentImpl.performTransition(ComponentImpl.java:1234) ~[bundleFile:?]
        at org.apache.felix.dm.impl.ComponentImpl.handleChange(ComponentImpl.java:1166) ~[bundleFile:?]
        at org.apache.felix.dm.impl.ComponentImpl.lambda$start$2(ComponentImpl.java:502) ~[bundleFile:?]
        at org.apache.felix.dm.impl.SerialExecutor.runTask(SerialExecutor.java:138) [bundleFile:?]
        at org.apache.felix.dm.impl.SerialExecutor.runTasks(SerialExecutor.java:120) [bundleFile:?]
        at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:86) [bundleFile:?]
        at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:105) [bundleFile:?]
        at org.apache.felix.dm.impl.ComponentImpl.start(ComponentImpl.java:500) [bundleFile:?]
        at org.apache.felix.dm.impl.ComponentScheduler.add(ComponentScheduler.java:69) [bundleFile:?]
        at org.apache.felix.dm.DependencyManager.add(DependencyManager.java:141) [bundleFile:?]
        at com.liferay.portal.remote.rest.extender.internal.RESTExtender.activate(RESTExtender.java:62) [bundleFile:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_342]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_342]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_342]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_342]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228) [bundleFile:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) [bundleFile:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664) [bundleFile:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510) [bundleFile:?]
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:310) [bundleFile:?]
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:300) [bundleFile:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:341) [bundleFile:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114) [bundleFile:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:983) [bundleFile:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:956) [bundleFile:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:765) [bundleFile:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:666) [bundleFile:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:432) [bundleFile:?]
        at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.configurationUpdated(ConfigurableComponentHolder.java:440) [bundleFile:?]
        at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.configurationEvent(RegionConfigurationSupport.java:325) [bundleFile:?]
        at org.apache.felix.scr.impl.manager.RegionConfigurationSupport$2.configurationEvent(RegionConfigurationSupport.java:119) [bundleFile:?]
        at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.sendEvent(ConfigurationManager.java:1689) [bundleFile:?]
        at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.run(ConfigurationManager.java:1640) [bundleFile:?]
        at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:138) [bundleFile:?]
        at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:105) [bundleFile:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_342]
Caused by: java.lang.ClassNotFoundException
        at javax.ws.rs.ext.RuntimeDelegateFinder.newInstance(RuntimeDelegateFinder.java:118) ~[?:?]
        at javax.ws.rs.ext.RuntimeDelegateFinder.find(RuntimeDelegateFinder.java:94) ~[?:?]
        at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:58) ~[?:?]
        ... 54 more
Caused by: java.lang.InstantiationException
        at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48) ~[?:1.8.0_342]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_342]
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_342]
        at javax.ws.rs.ext.RuntimeDelegateFinder.newInstance(RuntimeDelegateFinder.java:114) ~[?:?]
        at javax.ws.rs.ext.RuntimeDelegateFinder.find(RuntimeDelegateFinder.java:94) ~[?:?]
        at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:58) ~[?:?]
        ... 54 more
```

By looking at the code, I guess that the `RuntimeDelegateFinder.newInstance` should not be called; instead, the call should return at `RuntimeDelegateFinder.find#46` where a service providing `javax.ws.rs.ext.RuntimeDelegate` is found. This service is provided by `org.apache.cxf:cxf-rt-frontend-jaxrs:3.4.10`, see its `META-INF/services/javax.ws.rs.ext.RuntimeDelegate` file.

Please verify my guess by debugging `RuntimeDelegateFinder.find` during this integration test on master; if my guess is true, please find a way to make the service loading work. Thanks!

By the way, just with a few clicks I see 3 CXF jars providing such Java services. We may need a universal way...

cc @tinatian

**Comment by dantewang** [comment]
@shuyangzhou Will SPIFly help in such cases?

**Comment by shuyangzhou** [comment]
Since the caller is directly from our codebase. Try to just swap context classloader. SPIFly also just does some context classloader swapping, manual swap should work in the same way, but much cheaper.

**Pull request closed without merging**
