### PR TITLE
LPS-158624 Cleanup petra-xml part2

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
Seems related failure:
[service-builder-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1991354239):

```
     [echo] diff --git a/modules/apps/commerce/commerce-inventory-service/src/main/java/com/liferay/commerce/inventory/model/impl/CommerceInventoryWarehouseRelModelImpl.java b/modules/apps/commerce/commerce-inventory-service/src/main/java/com/liferay/commerce/inventory/model/impl/CommerceInventoryWarehouseRelModelImpl.java
     [echo] index 608b1a6e3072..b3cdb56e4458 100644
     [echo] --- a/modules/apps/commerce/commerce-inventory-service/src/main/java/com/liferay/commerce/inventory/model/impl/CommerceInventoryWarehouseRelModelImpl.java
     [echo] +++ b/modules/apps/commerce/commerce-inventory-service/src/main/java/com/liferay/commerce/inventory/model/impl/CommerceInventoryWarehouseRelModelImpl.java
     [echo] @@ -863,9 +863,19 @@ public class CommerceInventoryWarehouseRelModelImpl
     [echo]  			sb.append("<column><column-name>");
     [echo]  			sb.append(attributeName);
     [echo]  			sb.append("</column-name><column-value><![CDATA[");
     [echo] -			sb.append(
     [echo] +
     [echo] +			String attribute = String.valueOf(
     [echo]  				attributeGetterFunction.apply(
     [echo]  					(CommerceInventoryWarehouseRel)this));
     [echo] +
     [echo] +			attribute = StringUtil.replace(
     [echo] +				attribute, "]]><", "[$SPECIAL_CHARACTER$]");
     [echo] +			attribute = StringUtil.replace(attribute, "]]>", "]]]]><![CDATA[>");
     [echo] +			attribute = StringUtil.replace(
     [echo] +				attribute, "[$SPECIAL_CHARACTER$]", "]]><");
     [echo] +
     [echo] +			sb.append(attribute);
     [echo] +
     [echo]  			sb.append("]]></column-value></column>");
     [echo]  		}
     [echo]  
     [echo] diff --git a/modules/apps/layout/layout-utility-page-service/src/main/java/com/liferay/layout/utility/page/model/impl/LayoutUtilityPageEntryModelImpl.java b/modules/apps/layout/layout-utility-page-service/src/main/java/com/liferay/layout/utility/page/model/impl/LayoutUtilityPageEntryModelImpl.java
     [echo] index 8b9e24f86266..509f5c45f858 100644
     [echo] --- a/modules/apps/layout/layout-utility-page-service/src/main/java/com/liferay/layout/utility/page/model/impl/LayoutUtilityPageEntryModelImpl.java
     [echo] +++ b/modules/apps/layout/layout-utility-page-service/src/main/java/com/liferay/layout/utility/page/model/impl/LayoutUtilityPageEntryModelImpl.java
     [echo] @@ -1097,8 +1097,18 @@ public class LayoutUtilityPageEntryModelImpl
     [echo]  			sb.append("<column><column-name>");
     [echo]  			sb.append(attributeName);
     [echo]  			sb.append("</column-name><column-value><![CDATA[");
     [echo] -			sb.append(
     [echo] +
     [echo] +			String attribute = String.valueOf(
     [echo]  				attributeGetterFunction.apply((LayoutUtilityPageEntry)this));
     [echo] +
     [echo] +			attribute = StringUtil.replace(
     [echo] +				attribute, "]]><", "[$SPECIAL_CHARACTER$]");
     [echo] +			attribute = StringUtil.replace(attribute, "]]>", "]]]]><![CDATA[>");
     [echo] +			attribute = StringUtil.replace(
     [echo] +				attribute, "[$SPECIAL_CHARACTER$]", "]]><");
     [echo] +
     [echo] +			sb.append(attribute);
     [echo] +
     [echo]  			sb.append("]]></column-value></column>");
     [echo]  		}
```

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@julschong 
1. Why UADExporter have similar logic as model impl, can we make one of them delegate to another one? This way we do not have duplicated code
2. Look at the generated code, you actually do not need to do this filter for a ID, as ID comes from Long, it can not have the character you want to deal.
		String statusByUserId = String.valueOf(blogsEntry.getStatusByUserId());

		statusByUserId = StringUtil.replace(
			statusByUserId, "]]><", "[$SPECIAL_CHARACTER$]");
		statusByUserId = StringUtil.replace(
			statusByUserId, "]]>", "]]]]><![CDATA[>");
		statusByUserId = StringUtil.replace(
			statusByUserId, "[$SPECIAL_CHARACTER$]", "]]><");

Please resend.

Thanks.
Tina

**Pull request closed without merging**
