### PR TITLE
[Components with more than 1 service] Refactor Saml components from saml modules

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:security

**Comment by GabrielHenriquedev** [comment]
ci:test:saml

**Comment by chaowang-123** [comment]
The failure is not related to this pr, @slnn could you help to add QA Passed label?

**Review by MrJohn1911 — APPROVED** [review]

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
