### PR TITLE
[Blocker] LPS-190154

### PR DESCRIPTION
**Pull request by yuhai**
@tinatian, @dantewang

If set -Dliferay.home from DBUpgradeClient, the issue can't be resolved. When **new ClassLoaderAggregateProperties**(...), the property default.lifewray.home and liferay.home get from the configurations https://github.com/yuhai/liferay-portal/blob/LPS-190154/portal-impl/src/com/liferay/portal/configuration/ClassLoaderAggregateProperties.java#L231-L234. `tempCompositeConfiguration.getStringArray("include-and-override")` won't invoke https://github.com/yuhai/liferay-portal/blob/LPS-190154/portal-impl/src/com/liferay/portal/configuration/ClassLoaderAggregateProperties.java#L92.

### CODE REVIEW

**Comment by vicnate5** [comment]
FYI @achaparro

**Comment by achaparro** [comment]
Hi @yuhai, @tinatian, @dantewang,

please check my comment here:
https://liferay.atlassian.net/browse/LPS-190154?focusedCommentId=2174273

the intended behavior is to copy the properties before the upgrade.

In case you still have something to change regarding the upgrade, please, send the pull to the liferay-uniform repo before moving it to Brian.

Thanks.

cc/ @vicnate5

**Comment by catarineaguiar** [comment]
In case you want to continue with this fix, I tested and got the ticket's expected result.

No regressions were found.

**Comment by tinatian** [comment]
@achaparro Do you mean that we do not need to deal with this issue as the upgrade client is not setup correctly (not including the right properties)

Tina

**Comment by dantewang** [comment]
Closing as per @achaparro comments in the ticket.

**Comment by achaparro** [comment]
@tinatian, yes, they need to set the properties explicitly

**Pull request closed without merging**
