### PR TITLE
[Convert method references] LPS-162479 Covert method references to field references in module com…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-162479

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@slnn Code approved, please force push to correct the typo in your commit message.

**Comment by slnn** [comment]
> @slnn Code approved, please force push to correct the typo in your commit message.

Done

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@shuyangzhou @tinatian All tests passed and changes are direct replacements. Asked Commerce team for a final check and forward.

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
