### PR TITLE
[Optional Reference] LPS-187417 SearchException in SolrSpellCheckTest and SolrSuggestTest

### PR DESCRIPTION
**Pull request by haydenzheng314**
Ticket: https://liferay.atlassian.net/browse/LPS-187417
Thanks.

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by LisztLiszt** [comment]
ci:test:search-solr

**Comment by Kvale1733** [comment]
Running the search suite on it's own as solr changes have caused regressions that were caught only by the search suite.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:stop

**Comment by lipusz** [comment]
@brookedalton  fyi

**Comment by dantewang** [comment]
ci:test:search

**Comment by brookedalton** [comment]
ci:test:search-solr

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
