### PR TITLE
LPS-176640 Remove S3FileCache

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:dl-store

**Comment by dantewang** [comment]
@vicnate5 It seems the functional test cases related to S3Store are ignored due to credential change. Could you take a look and try to get the updated AWSStore.testcase tested?

Also, could you share the necessary info/steps to manually setup and test S3Store? I'd like to debug something locally. Thanks!

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/135676

**Pull request closed without merging**
