### PR TITLE
LPD-41662 Add JDK17 batches and portal-license-smoke-mysql57 to upstream-dxp and remove jdk11 test suite

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:upstream-dxp:dryrun

**Comment by julschong** [comment]
ci:test:upstream-dxp:dryrun

**Comment by julschong** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@julschong Please also remove functional-smoke-tomcat90-mysql57-jdk11_open

Please remove ServiceBuilderJDK11.testcase, add new branch to test service builder on jdk17.

Thanks!

**Pull request closed without merging**
