### PR TITLE
[Bug fix][Urgent] LPS-143663

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou @tinatian This is FP5.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
cc @samuelkong

**Comment by arthurchan35** [comment]
Hey @dantewang 
If I am not mistaken, this vulnerability is only fixed in 2.15.1 RC1

**Comment by brianchandotcom** [comment]
@dantewang I merged this manually.

**Comment by tinatian** [comment]
ci:close

**Comment by vicnate5** [comment]
Test results are good for this

**Pull request closed without merging**
