### PR TITLE
LPS-143939 Remove Xuggler support

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:document

**Comment by guilhermedcamacho** [comment]
ci:test:document

**Comment by guilhermedcamacho** [comment]
It seems that CI is unstable, all tests are failing due to error `java.lang.Exception: No results for path: $['companyId']`
Also happening with other PRs like [this](https://github.com/liferay-core-infra/liferay-portal/pull/72)
@vicnate5 , can you help me, please?

**Comment by vicnate5** [comment]
@guilhermedcamacho There was a regression at head https://issues.liferay.com/browse/LPS-144012

Will re-run this once I know this is fixed at head.

**Comment by vicnate5** [comment]
ci:test:document

**Comment by vicnate5** [comment]
@guilhermedcamacho The blocking issue is fixed at head, but this branch no longer can be rebased. Can you rebase and force push?

**Comment by guilhermedcamacho** [comment]
> @guilhermedcamacho The blocking issue is fixed at head, but this branch no longer can be rebased. Can you rebase and force push?

Sure! thanks a lot :+1:

**Comment by guilhermedcamacho** [comment]
ci:test:document

**Comment by guilhermedcamacho** [comment]
ci:test:document

**Comment by vicnate5** [comment]
@guilhermedcamacho test results for Documents look good

**Comment by tinatian** [comment]
@shuyangzhoug This is good to go.

Tina

**Comment by guilhermedcamacho** [comment]
@shuyangzhou

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/111345

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
