### PR TITLE
[Component with its own class name as service type] LPS-199148 Refactor BatchEngineImportStrategyFactory and ResourceBundleLoaderProvider component 

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Ticket: https://liferay.atlassian.net/browse/LPS-199148

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:data-integration

**Comment by Kvale1733** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
No regressions found. Just going to rerun stable to verify some likely fluke failures.

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@Valmir-unicap No regressions found.

**Comment by rafaprax** [comment]
Hey @Valmir-unicap, these changes are ok but could you please break the third commit into tree ones? It will look like:
1 - Reuse logic from `com.liferay.portal.kernel.resource.bundle.ResourceBundleLoaderUtil` instead of create a serviceTracker
2 - Rename ...
3 - Remove unused constant `RESOURCE_BUNDLE_LOADER_PROVIDER`

Fix and resend

**Pull request closed without merging**
