### PR TITLE
[FileInstall] LPS-144496 part 3 | 2022-1-27

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Rebased and resolved conflicts (in semantic versioning files)

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/271

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
