### PR TITLE
[Remove Stream/Optional usage] LPS-171132 data-engine-taglib

### PR DESCRIPTION
**Pull request by JanisZhang**
previous: https://github.com/liferay-core-infra/liferay-portal/pull/3844

change in this pull:
- use `ListUtil.exists` in https://github.com/liferay-core-infra/liferay-portal/commit/e2e32e108710f5b0751d9a56e3c0cee4be1faa27
- use `list.add` in https://github.com/liferay-core-infra/liferay-portal/commit/b24638a01f271827c05e63689e21acd02629ac50
- use the enhanced for loop in https://github.com/liferay-core-infra/liferay-portal/commit/dfe4ad26c3d5c7ba8cbcc51d25cd2efba1b7c2a6

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:data-engine

**Comment by JanisZhang** [comment]
Hi @catarineaguiar, I  cannot reproduce this error locally. Could you please help to double-check it? Thanks!
```
com.liferay.data.engine.rest.resource.v2_0.test.DataLayoutResourceTest > testGetDataDefinitionDataLayoutsPageWithSortDateTime STARTED

com.liferay.data.engine.rest.resource.v2_0.test.DataLayoutResourceTest > testGetDataDefinitionDataLayoutsPageWithSortDateTime PASSED
```

**Comment by catarineaguiar** [comment]
@JanisZhang thanks for checking. Everything looks good for me.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Comment by JanisZhang** [comment]
the test running for over 18 hours...

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:forward

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
