### PR TITLE
LPD-37620 patch freemarker to 2.3.33

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

resent https://github.com/liferay-core-infra/liferay-portal/pull/7482
This PR is to patch freemarker to 2.3.33.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:report:29799824

**Comment by jeffwu0724** [comment]
core-functional:
https://testray.liferay.com/#/project/35392/routines/45357/build/29799824/case-result/29809959/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/29799824/case-result/29810260/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/29799824/case-result/29810445/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/29799824/case-result/29810579/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/29799824/case-result/29811865/history -- not unique

**Comment by jeffwu0724** [comment]
ci:report:29974002

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
