### PR TITLE
[Disable auto-import-default-references]LPS-164191

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to disable auto-import-default-references in `portal-reports-engine-console`. Thanks!
https://issues.liferay.com/browse/LPS-164191

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

**Comment by dantewang** [comment]
@shuyangzhou @tinatian Forwarded this one.

**Pull request closed without merging**
