### PR TITLE
[Components with more than 1 service] LPS-198978 Refactor KeyStoreCredentialResolver component

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-198978

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:saml

**Comment by Kvale1733** [comment]
@MrJohn1911 Several unit tests failing with the same error

com.liferay.saml.opensaml.integration.internal.servlet.profile.WebSsoProfileTest
com.liferay.saml.opensaml.integration.internal.resolver.DefaultUserResolverTest
com.liferay.saml.opensaml.integration.internal.resolver.DefaultAttributeResolverTest
com.liferay.saml.opensaml.integration.internal.credential.CredentialResolverTest
com.liferay.saml.opensaml.integration.internal.resolver.DefaultNameIdResolverTest
com.liferay.saml.opensaml.integration.internal.metadata.MetadataGeneratorTest
com.liferay.saml.opensaml.integration.internal.metadata.SamlHttpRequestHelperImplTest
com.liferay.saml.opensaml.integration.internal.metadata.SamlHttpRequestHelperImplTest
com.liferay.saml.opensaml.integration.internal.util.SamlUtilTest

```
[exec] com.liferay.saml.opensaml.integration.internal.util.SamlUtilTest > testGetAttributesMapWithMapping FAILED
[beanshell]      [exec]     java.lang.IllegalArgumentException: Can not set com.liferay.saml.runtime.metadata.LocalEntityManager field com.liferay.saml.opensaml.integration.internal.metadata.MetadataManagerImpl._localEntityManager to com.liferay.saml.opensaml.integration.internal.credential.KeyStoreCredentialResolver
[beanshell]      [exec]         at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[beanshell]      [exec]         at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[beanshell]      [exec]         at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
[beanshell]      [exec]         at java.lang.reflect.Field.set(Field.java:764)
[beanshell]      [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.setFieldValue(ReflectionTestUtil.java:340)
[beanshell]      [exec]         at com.liferay.saml.opensaml.integration.internal.BaseSamlTestCase._setupMetadata(BaseSamlTestCase.java:633)
```
[Log]([exec] com.liferay.saml.opensaml.integration.internal.util.SamlUtilTest > testGetAttributesMapWithMapping FAILED
[beanshell]      [exec]     java.lang.IllegalArgumentException: Can not set com.liferay.saml.runtime.metadata.LocalEntityManager field com.liferay.saml.opensaml.integration.internal.metadata.MetadataManagerImpl._localEntityManager to com.liferay.saml.opensaml.integration.internal.credential.KeyStoreCredentialResolver
[beanshell]      [exec]         at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[beanshell]      [exec]         at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[beanshell]      [exec]         at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
[beanshell]      [exec]         at java.lang.reflect.Field.set(Field.java:764)
[beanshell]      [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.setFieldValue(ReflectionTestUtil.java:340)
[beanshell]      [exec]         at com.liferay.saml.opensaml.integration.internal.BaseSamlTestCase._setupMetadata(BaseSamlTestCase.java:633))

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
