### PR TITLE
LPS-188134 moving guava to shared-dependenceis

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

Resent https://github.com/liferay-core-infra/liferay-portal/pull/4896 and https://github.com/liferay-core-infra/liferay-portal/pull/5179.
As in the PR above, it caused a blocker(had been reverted) by using shared-dependencies. In this PR, I would like to change back to compileInclude and see how it will go. https://liferay.atlassian.net/browse/LPS-191330

This is for ticket https://liferay.atlassian.net/browse/LPS-188134.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:online-editing

**Comment by jeffwu0724** [comment]
ci:test:lima

**Comment by jeffwu0724** [comment]
Hi @Kvale1733 , @catarineaguiar 

Could you please help me to confirm both` One Drive` and the `Google Clouds Storage store` works fine, please?
https://liferay.atlassian.net/browse/LPS-191330?focusedCommentId=2183137

Thanks!
Jeff

**Comment by Kvale1733** [comment]
@jeffwu0724 

1) Found regression with OneDrive. Can be reproduced by adding a word document with OneDrive

Steps to reproduce
1. Go to Instance Settings > Documents & Media > One Drive and add OneDrive credentials (Same ones I shared with you)
2. Add a new page and place a DM widget
3. Hover over the widget and click the ellipses on the top right of it
4. Go to  Configuration > Show actions and you can now add documents in the widget
5. Add a word Document with OneDrive using the widget (should redirect to a word page where you can add the document)
6. Go back to the widget page
7. Click on the title of the created document

Expected Results: Can view the document
Actual Results: Redirected to page with "Internal Server Error" and the following appears in the console
```
[beanshell] 2023-08-04 20:19:07.552 WARN  [http-nio-8080-exec-5][PortalImpl:6752] null
[beanshell] javax.servlet.ServletException: com.liferay.portal.kernel.portlet.PortletContainerException: javax.servlet.ServletException: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.copyOf([Ljava/lang/Object;)Lcom/google/common/collect/ImmutableList;
[beanshell] 	at org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:950) ~[org.apache.tomcat-jasper.jar:9.0.75]
[beanshell] 	at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:885) ~[org.apache.tomcat-jasper.jar:9.0.75]
[beanshell] 	at com.liferay.taglib.servlet.PageContextWrapper.handlePageException(PageContextWrapper.java:164) ~[util-taglib.jar:?]
[beanshell] 	at org.apache.jsp.layout.view.portlet_jsp._jspService(portlet_jsp:245) ~[?:?]
[beanshell] 	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111) ~[jasper.jar:9.0.75]
[beanshell] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[servlet-api.jar:4.0.FR]
```
[Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-31/test-portal-acceptance-pullrequest(master)/8948/functional-tomcat90-mysql57-jdk8/1/16/jenkins-console.txt.gz?authuser=0)

2) Google Cloud Store doesn't work either

Steps to reproduce:
Follow these steps: https://docs.google.com/document/d/1soiAQWYk0JVnoWqcuATPn_1MQ7yYzBqOE_xFGiL4n_U/edit
For step two, the entire json file with the creds is here: https://share.1password.com/s#-xghuo1DDbaL-brwHs8m3O2XdryuTaIMl6FAv1J25n0

Expected Results: Can connect to Google Cloud Store bucket without issue
Actual Results: The following error appears in the console. 
```
ROOT:47] bundle com.liferay.portal.store.gcs:3.0.26 (116)[com.liferay.portal.store.gcs.GCSStore(57)] : The activate method has thrown an exception
 [parallel] java.lang.NoClassDefFoundError: Could not initialize class com.google.common.io.BaseEncoding
 [parallel] 	at com.google.api.client.util.Base64.decodeBase64(Base64.java:103) ~[?:?]
 [parallel] 	at com.google.api.client.util.PemReader.readNextSection(PemReader.java:99) ~[?:?]
 [parallel] 	at com.google.api.client.util.PemReader.readFirstSectionAndClose(PemReader.java:128) ~[?:?]
```
[Log](https://gist.github.com/Kvale1733/74953c8c14231938267e8561e5008d10)

**Comment by jeffwu0724** [comment]
Hi @Kvale1733 ,

That's weired, I tested it locally and can create a one drive word file. 
I gonna close this ticket and try again.

Thanks!

**Pull request closed without merging**
