### PR TITLE
LPS-190427 Merge WorkflowPermission interface and impl into Util in kernel

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
@julschong No regressions found. SF is unrelated. Need to rebase though.

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
rebased

**Comment by julschong** [comment]
@shuyangzhou 
Util used in portal-kernel, not moving to portal-impl

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found. SF issue is not related

**Comment by julschong** [comment]
rebased and retest

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141354

**Pull request closed without merging**
