### PR TITLE
[Remove immediate=true usage core-infrastructure-4]Lps 168633

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-168633

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
@slnn possible regression:

`portal-license-smoke-jdk8/0/0`
```
    [junit] 2022-11-22 03:16:43.816 DEBUG [main][BundleStartStopLogger:86] STARTED com.liferay.portal.file.install.impl_4.0.22 [31]
    [junit] 2022-11-22 03:16:43.817 INFO  [main][ModuleFrameworkImpl:1717] Started web bundles
    [junit] 2022-11-22 03:16:43.817 INFO  [main][ModuleFrameworkImpl:279] Navigate to Control Panel > System > Gogo Shell and enter "lb" to see all bundles
    [junit] 2022-11-22 03:16:45.578 ERROR [main][MainServlet:266] null
    [junit] java.lang.ClassNotFoundException: null
    [junit] 	at com.liferay.portal.ee.license.a.a.loadClass(Unknown Source) ~[portal-impl.jar:?]
    [junit] 	at com.liferay.portal.ee.license.LCSLicenseManager.getStartupAction(Unknown Source) ~[portal-impl.jar:?]
    [junit] 	at com.liferay.portal.internal.servlet.MainServlet.init(MainServlet.java:261) [portal-impl.jar:?]
    [junit] 	at javax.servlet.GenericServlet.init(GenericServlet.java:158) [servlet-api.jar:4.0.FR]
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-35/test-portal-acceptance-pullrequest(master)/3090/portal-license-smoke-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

`lpkg-controller-jdk8/0/0`
```
[beanshell] 2022-11-22 03:23:49.032 DEBUG [ModuleFramework-Static-Bundles-5][BundleStartStopLogger:86] STARTED org.apache.felix.scr_2.1.14.LIFERAY-PATCHED-5 [74]
[beanshell] 2022-11-22 03:23:49.033 INFO  [main][ModuleFrameworkImpl:1584] Started initial bundles
[beanshell] 2022-11-22 03:23:49.033 INFO  [main][ModuleFrameworkImpl:1633] Starting dynamic bundles
[beanshell] 2022-11-22 03:23:49.124 ERROR [Framework Event Dispatcher: Equinox Container: 0040e0e9-6c68-4001-8d16-8c37bb799258][Framework:56] FrameworkEvent ERROR
[beanshell] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.tools.service.builder.test.uad [90]
[beanshell]   Unresolved requirement: Import-Package: com.liferay.user.associated.data.anonymizer; version="1.2.0"
[beanshell]   Unresolved requirement: Import-Package: com.liferay.portal.tools.service.builder.test.model; version="1.0.0"
[beanshell]     -> Export-Package: com.liferay.portal.tools.service.builder.test.model; bundle-symbolic-name="com.liferay.portal.tools.service.builder.test.api"; bundle-version="1.0.0"; version="1.0.0"; uses:="com.liferay.petra.sql.dsl,com.liferay.petra.sql.dsl.base,com.liferay.portal.kernel.annotation,com.liferay.portal.kernel.bean,com.liferay.portal.kernel.model,com.liferay.portal.kernel.model.change.tracking,com.liferay.portal.kernel.model.version,com.liferay.portal.kernel.model.wrapper,com.liferay.portal.kernel.util"
[beanshell]        com.liferay.portal.tools.service.builder.test.api [93]
[beanshell]   Unresolved requirement: Import-Package: com.liferay.portal.tools.service.builder.test.service; version="1.0.0"
[beanshell]     -> Export-Package: com.liferay.portal.tools.service.builder.test.service; bundle-symbolic-name="com.liferay.portal.tools.service.builder.test.api"; bundle-version="1.0.0"; version="1.0.0"; uses:="com.liferay.petra.function,com.liferay.petra.sql.dsl.query,com.liferay.portal.kernel.change.tracking,com.liferay.portal.kernel.dao.orm,com.liferay.portal.kernel.exception,com.liferay.portal.kernel.jsonwebservice,com.liferay.portal.kernel.model,com.liferay.portal.kernel.model.version,com.liferay.portal.kernel.search,com.liferay.portal.kernel.security.access.control,com.liferay.portal.kernel.service,com.liferay.portal.kernel.service.change.tracking,com.liferay.portal.kernel.service.persistence.change.tracking,com.liferay.portal.kernel.service.version,com.liferay.portal.kernel.spring.osgi,com.liferay.portal.kernel.transaction,com.liferay.portal.kernel.util,com.liferay.portal.tools.service.builder.test.model"
[beanshell] 
[beanshell] 	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi.jar:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-35/test-portal-acceptance-pullrequest(master)/3090/lpkg-controller-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
Thank @catarineaguiar for catching this！ I will check and resend it.

**Pull request closed without merging**
