### PR TITLE
[Optional Reference]LPS-185546 module: dynamic-data-mapping-service

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-185546

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
ci:test:stable

**Comment by zhangyan0701** [comment]
ci:test:data-engine

**Comment by catarineaguiar** [comment]
@JanisZhang regression found:

```
     [exec] com.liferay.dynamic.data.mapping.util.DDMFormTemplateSynchonizerTest > testUpdateDDMFormFieldOptionsIfTheyWereModifiedFromStructure FAILED
     [exec]     java.lang.NoClassDefFoundError: com/liferay/depot/group/provider/SiteConnectedGroupGroupProvider
     [exec]         at com.liferay.dynamic.data.mapping.service.impl.DDMTemplateLocalServiceImpl.<clinit>(DDMTemplateLocalServiceImpl.java:1924)
     [exec]         at com.liferay.dynamic.data.mapping.util.DDMFormTemplateSynchonizerTest$MockDDMFormTemplateSynchronizer.<init>(DDMFormTemplateSynchonizerTest.java:443)
     [exec]         at com.liferay.dynamic.data.mapping.util.DDMFormTemplateSynchonizerTest.testUpdateDDMFormFieldOptionsIfTheyWereModifiedFromStructure(DDMFormTemplateSynchonizerTest.java:138)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
```
```
    [exec] com.liferay.dynamic.data.mapping.util.DDMFormTemplateSynchonizerTest > testUpdateRequiredPropertyIfTemplateModeIsCreate FAILED
     [exec]     java.lang.NoClassDefFoundError: Could not initialize class com.liferay.dynamic.data.mapping.service.impl.DDMTemplateLocalServiceImpl
     [exec]         at com.liferay.dynamic.data.mapping.util.DDMFormTemplateSynchonizerTest$MockDDMFormTemplateSynchronizer.<init>(DDMFormTemplateSynchonizerTest.java:443)
     [exec]         at com.liferay.dynamic.data.mapping.util.DDMFormTemplateSynchonizerTest.testUpdateRequiredPropertyIfTemplateModeIsCreate(DDMFormTemplateSynchonizerTest.java:163)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-05/test-1-25/test-portal-acceptance-pullrequest(master)/1127/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
