### PR TITLE
[4/4] LPS-145396 When we delete some types of objects in Liferay, we are not deleting their ResourcePermission records

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
[4/4] When we delete some types of objects in Liferay, we are not deleting their ResourcePermission records, leaving some orphan data in the ResourcePermission table.

@tinatian same code than https://github.com/liferay-core-infra/liferay-portal/pull/299 but I have split the changes in 4 PR for an easier review: https://github.com/liferay-core-infra/liferay-portal/pull/365, https://github.com/liferay-core-infra/liferay-portal/pull/366, https://github.com/liferay-core-infra/liferay-portal/pull/367, and https://github.com/liferay-core-infra/liferay-portal/pull/368

**Code changes:**
This pull request contains the OrphanDetectionTestRule tests that checks the ResourcePermission are correctly deleted.

To avoid executing this rule in every integration test, I have added a condition in the OrphanDetectionTestRule.beforeMethod method:
```
		Class<?> testClass = description.getTestClass();

		String testClassName = testClass.getName();

		if (!testClassName.endsWith("ServiceTest")) {
			return Collections.emptyList();
		}
```

So the rule is only executed for all the `*ServiceTest` classes, reducing the test classes where OrphanDetectionTestRule is applied from 2253 to 214

Adding this validation in the test rule is easier than the previous idea of https://github.com/liferay-core-infra/liferay-portal/pull/299#issuecomment-1036690244 (_adding annotations and forcing this annotation for every ServiceTest using SF_) and I think it doesn't have any drawback.

**Important:** These test depends on https://github.com/liferay-core-infra/liferay-portal/pull/365, https://github.com/liferay-core-infra/liferay-portal/pull/366 and https://github.com/liferay-core-infra/liferay-portal/pull/367 changes so it cannot be forwarded until the other PRs are merged to master

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:reevaluate:1297401_1824

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
The CI test errors `java.lang.AssertionError: Orphan ResourcePermission after the deletion of...` will be fixed once  https://github.com/liferay-core-infra/liferay-portal/pull/365, https://github.com/liferay-core-infra/liferay-portal/pull/366, and https://github.com/liferay-core-infra/liferay-portal/pull/367 are merged

**Comment by tinatian** [comment]
Hi @jorgediaz-lr ,
Your current solution is slow even though you only check ***ServiceTest.

With your current solution, a new test rule is added to all ***ServiceTest. With old solution, all the ***ServiceTest will only need to go through DataGuardTestRule which they already have, thus no new test rule is involved.

Considering we have more than 200 ***ServiceTest and all the tests keep running on ci, adding a new test rule is going to make ci even slower. 

Also, in your test rule logic, you invoked ResourcePermissionLocalServiceUtil to do checking multiple times. Based on my experience, it will be slow as the ResourcePermission table is always a large table, also as this is a test, there will be more writing to the database which will invalidate the entity/finder cache for database reading, meaning you may hit database each time you invoke on ResourcePermissionLocalServiceUtil, this is going to be a lot of performance loss.

I really want to avoid this if there is another option.


Tina.

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

About simply adding `@DataGuard(autoDelete = false, scope = DataGuard.Scope.METHOD)` to all the tests would be hard to implement, it only works if the test deletes everything it was created during the test execution and that is only true at Company level tests (_for example, all the entries of the AuditEvent table are only deleted when the company is deleted_).
So we would have to modify all the tests to correctly delete all the created objects.

I have another idea that can avoid creating the new test rule:
  - As the DataGuardTestRuleUtil gets all the records before and after the test execution, I can add some custom code before the [_autoDeleteLeftovers](https://github.com/liferay/liferay-portal/blob/e646a8b50ad77dcfd8b08db118601bca4ae72c8c/portal-test/src/com/liferay/portal/kernel/test/rule/DataGuardTestRuleUtil.java#L172) method that will check all the remaining ResourcePermission and verify that they point to other models that are not deleted.
  - If the related object is deleted (it wasn't captured by __captureDataMap()_), that means the ResourcePermission is orphan.
  - The advantages of adding the code here are:
        - We can verify everything without additional accesses to the database.
        - We don't have to modify any test with additional annotations or additional cleanup code.
  - The only disadvantage is we have to add some specific code to the DataGuardTestRuleUtil to verify the ResourcePermission.

Let me know if you want me to try this approach.

Regards,
Jorge

**Comment by tinatian** [comment]
@jorgediaz-lr This sounds good to me, please send a new pull and I am going to close this one.

Thanks
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
