### PR TITLE
LPS-167187 Improve default db creation scripts

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
failures not related.

**Comment by tinatian** [comment]
@vicnate5 @lucasperj Why we only need modify these two?

Tina

**Comment by vicnate5** [comment]
@tinatian Only these DB's support this `if exists` behavior out of the box. DB2 and Oracle do not have it.

**Comment by tinatian** [comment]
@vicnate5 @lucasperj For DB2 and Oracle, as they do not support "if exists", what did we do to address the creation failures mentioned in this ticket?

Basically, I would like to see that we have consistent behavior across different databases. 

Tina

**Comment by vicnate5** [comment]
@lucasperj Can you check if DB2 and Oracle creation scripts cause the same errors? The example in the ticket is from postgresql.

**Comment by tinatian** [comment]
@lucasperj I am going to close this pull, please reopen/resend if needed.

Thanks.
Tina.

**Comment by lucasperj** [comment]
Hey @tinatian , so for the late answer on that, apparently the same happens with [Oracle](https://testray.liferay.com/reports/production/logs/2022-12/test-1-30/test-portal-testsuite-upstream(master)/1841/functional-upgrade-tomcat90-oracle193-jdk8/0/7/jenkins-console.txt.gz?authuser=0) too `ORA-01918: user 'LPORTAL' does not exist` in PortalSmokeUpgrade#ViewPortalSmokeArchive7110. 

Selection_275

**Comment by lucasperj** [comment]
And this is consistent with Postgresql, [example](https://testray.liferay.com/reports/production/logs/2022-12/test-1-30/test-portal-testsuite-upstream(master)/1841/functional-upgrade-tomcat90-postgresql134-jdk8/0/12/jenkins-console.txt.gz?authuser=0) `psql:/tmp/create.sql:1: ERROR:  database "lportal" does not exist`.

**Comment by lucasperj** [comment]
I've not found references for the error to SQLServer and DB2.

[SQLServer](https://testray.liferay.com/reports/production/logs/2022-11/test-1-39/test-portal-testsuite-upstream(master)/508/functional-upgrade-tomcat90-sqlserver2017-jdk8/0/5/jenkins-console.txt.gz?authuser=0):
`[exec] RESTORE DATABASE successfully processed 6140 pages in 0.758 seconds (63.278 MB/sec).
 [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1022920734.properties`
 [DB2](https://testray.liferay.com/reports/production/logs/2022-11/test-1-39/test-portal-testsuite-upstream(master)/508/functional-upgrade-tomcat90-db2111-jdk8/0/7/jenkins-console.txt.gz?authuser=0): 
 `[exec] db2 restore database lportal user root using I7Oen70215bieRR from /opt/ibm/db2 replace existing
 [exec] DB20000I  The RESTORE DATABASE command completed successfully.
 [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1307294525.properties`

**Comment by lucasperj** [comment]
ci:reopen

**Comment by tinatian** [comment]
@lucasperj 
You said "I've not found references for the error to SQLServer and DB2.", then why you modify SQLServer in your first commit?

As oracle has same issue, what are you going to do about it?

From the framework side, we would like to provide consistent support to all different database, you can not just provide a feature for some of the database but not others. If that's the case, I'd rather not touching it at all.

In your ticket description, it is said "We need to change the script creation for all supported DBs, exception for mysql and mariaDB", why do not include mysql and mariaDB?

Please fix and list the detailed reason you made the changes in the commit message.

Thanks.
Tina.

**Pull request closed without merging**
