### PR TITLE
[Spring Beans] LPS-201615 Move DummyRoleMembershipPolicy to module portal-security-membership-policy 

### PR DESCRIPTION
**Pull request by JanisZhang**
https://liferay.atlassian.net/browse/LPS-201615

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:sf

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@JanisZhang Is it possible to follow this one https://github.com/liferay-core-infra/liferay-portal/pull/6125? The `DummyRoleMembershipPolicy` is our default implementation?

Please double check and resend, thanks!

**Comment by JanisZhang** [comment]
> @JanisZhang Is it possible to follow this one #6125? The `DummyRoleMembershipPolicy` is our default implementation?
> 
> Please double check and resend, thanks!

Hi @dantewang, for interface `RoleMembershipPolicy`, we only have one impl `DummyRoleMembershipPolicy` in Portal, it should be the default one.  

However, this default implementation can be replaced by `HookHotDeployListener` through portal property  `membership.policy.roles`, so I don't think it can be merged to util. What do  you think?

**Comment by JanisZhang** [comment]
Force-pushed. 
I updated the breaking change commit message based on the latest requirement. Thanks!

**Comment by tinatian** [comment]
@JanisZhang @dantewang 
Let's do this:
Add MembershipPolicyUtil class to expose static method to retrieve each type of MembershipPolicy
Replace all current ***MembershipPolicyFactoryUtil usages to the new added MembershipPolicyUtil
Inside MembershipPolicyUtil, create dummy service for each type, use snapshot to retrieve each type of service, if the service is not available, return the default one. This way, we do not need the Dummy**MembershipPolicy class, thus no need to register it as a service.
Please do all the different types together in one pull.

Thanks.
Tina

**Pull request closed without merging**
