### PR TITLE
[Remove Stream/Optional usage] LPS-173791 module: object-web

### PR DESCRIPTION
**Pull request by JanisZhang**
Code conflicts, resend. Thanks!
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3502
https://issues.liferay.com/browse/LPS-173791

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
@JanisZhang Regressions found
Steps to reproduce:
     1. Go to Control Panel > Objects
     2) Create object with label "Custom Object 314" and plural label "Custom Objects 314"
     3) Click on created object
     4) Go to Fields Tab
     5) Add boolean field with label "Field" and Save
     6) Go to details tab 
     7) Set Control Panel > Object as Panel Category Key
     8) Publish the object
     9 ) Go to Control Panel > Custom Objects 314
     10) Add three entries: 1 with the field checkbox checked, and 2 without
     11) Add a content page named "Test Content Page Name" to the default site
     12) Add a collection display fragment to the page
     13) Click on the added fragment
     14) Click Select Collection
     15) Go to Collection Providers and Select Custom Objects 314
     16) Drag a Heading Fragment to the Collection Display headings
     17) Double Click on the Collection Display 
     18) Click on the Collection Display Select Field (from Custom Object 314) in the Field selection
     19) Click on the bottom of the collection display (where it says showing 1 to 3 entries)
     20) Select Style Display as Table
     21) Click publish
     22) View the created page
     
 Expected Results: Can view the object entries in a table (True, false, false)
 Actual Results: Only the string "Field" is shown. The following also appears in the console
 ```
 LIFERAY_ERROR: Current URL /web/guest/cd2ec3af-157c-8ce6-e636-cd92cd406af8?p_p_id=com_liferay_layout_content_page_editor_web_internal_portlet_ContentPageEditorPortlet&amp;p_p_lifecycle=2&amp;p_p_state=normal&amp;p_p_mode=view&amp;p_p_resource_id=%2Flayout_content_page_editor%2Fget_collection_field&amp;p_p_cacheability=cacheLevelPage&amp;p_l_mode=edit generates exception: java.lang.RuntimeException: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
```
[Log](https://testray.liferay.com/reports/production/logs/2023-02/test-1-37/test-portal-acceptance-pullrequest(master)/9010/functional-tomcat90-mysql57-jdk8/0/7/jenkins-console.txt.gz?authuser=0)

**Comment by JanisZhang** [comment]
Hi @Kvale1733 , Could you please help to provide a video to reproduce this issue?  It seems like I got something wrong with the steps because I cannot reproduce it on my side.  Thank you!

**Comment by Kvale1733** [comment]
@JanisZhang Here is the video

https://user-images.githubusercontent.com/90647688/220962798-59efc281-98be-4095-9edf-a0f3cb0938ab.mp4

Here is the expected result
Before

**Comment by JanisZhang** [comment]
Thank you so much! @Kvale1733

**Pull request closed without merging**
