### PR TITLE
LPD-1948 Use of library with known vulnerability: Apache Freemarker 2.3.29

### PR DESCRIPTION
**Pull request by RenanUmV**
Ticket: https://liferay.atlassian.net/browse/LPD-1948

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:report:2533619076

**Comment by jeffwu0724** [comment]
Hi @RenanUmV ,

The failing tests seems related, could you please double check?
I also rerun the relevant test to make sure the result is consitent 
Thanks

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:report:2533822240

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:stop

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:report:2535541318

**Comment by jeffwu0724** [comment]
https://testray.liferay.com/home/-/testray/case_results/2535548818/history seems related to the PR

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:report:2539377649

**Comment by jeffwu0724** [comment]
ci:report:2539377649

**Comment by jeffwu0724** [comment]
https://testray.liferay.com/home/-/testray/case_results/2539430782/history seems related

**Comment by jeffwu0724** [comment]
Please see https://github.com/liferay-core-infra/liferay-portal/pull/6639

**Pull request closed without merging**
