### PR TITLE
[Method References 2] LPS-165626

### PR DESCRIPTION
**Pull request by JanisZhang**
resend. remove JournalPropertiesTransformerListener.

previous:https://github.com/liferay-core-infra/liferay-portal/pull/2620

Hi @dantewang, Do we need to keep the module `journal-properties-transformer-listener`?

### CODE REVIEW

**Comment by dantewang** [comment]
@JanisZhang If a module has no class after your change, you can remove it.

**Comment by JanisZhang** [comment]
force-pushed. Thanks! cc @dantewang

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:echo

**Review by dantewang — APPROVED** [review]

**Comment by Kvale1733** [comment]
@JanisZhang No regressions.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2818

**Pull request closed without merging**
