### PR TITLE
[Bug Fix] LPS-167246 Replace _destinations.remove(destinationName) with _destinations.remove(destination.getName(), destination)

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by tinatian** [comment]
@W2jx 1. you have typo in your comment, read it one more time
             2. destination name is unique name which means you should never have two destinations with same name. This is not a bug.

Tina

**Pull request closed without merging**
