### PR TITLE
[Static reference] LPS-180679 frontend-taglib, frontend-data-set

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:frontend

**Comment by dantewang** [comment]
ci:test:frontend-data-set

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:frontend

**Comment by dantewang** [comment]
ci:test:frontend-data-set

**Comment by Kvale1733** [comment]
@dantewang No regressions.

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
