### PR TITLE
[Method References 2] LPS-164207 Remove unused reference variable in module segments-asah-connector(dxp)

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have removed unused reference variable in module segments-asah-connector(dxp).

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @catarineaguiar , Could you please help me check the test results ? Thanks!

**Comment by Kvale1733** [comment]
@W2jx No regressions.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
ci:forward

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
