### PR TITLE
[Remove Stream/Optional usage] LPS-174397 modules: style-book-web

### PR DESCRIPTION
**Pull request by JanisZhang**
Follow-up:https://github.com/liferay-core-infra/liferay-portal/pull/3277

I inlined jsonObjects. Thanks!

https://issues.liferay.com/browse/LPS-174397

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
