### PR TITLE
LPS-144170 Move im4java.jar and monte-cc.jar to modules

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by guilhermedcamacho** [comment]
Hey @tinatian , as we discussed, I did the point 2 (move just the logic that depends on third-party libs directly) that you mentioned [here](https://github.com/liferay-core-infra/liferay-portal/pull/106#issuecomment-1003150581) , the point 1 won't be necessary, once the class ImageToolHelper doesn't exist anymore. Thanks!

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Hey @vicnate5 , please help me scan test results. Thanks!

**Comment by vicnate5** [comment]
@kyle-miho can you check this one?

**Comment by guilhermedcamacho** [comment]
ci:test:document

**Comment by guilhermedcamacho** [comment]
ci:test:document

**Comment by guilhermedcamacho** [comment]
Fixed code conflicts with these files, but the version stayed the same.
portal-impl/bnd.bnd (20.0.0)
portal-kernel/bnd.bnd (32.0.0)

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:document

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@koor4356 can you check this one?

**Comment by koor4356** [comment]
@guilhermedcamacho @vicnate5 
The results look good except that the default ci:test is not been run for this PR.

**Comment by guilhermedcamacho** [comment]
Should we run it again? @koor4356 @vicnate5

**Comment by vicnate5** [comment]
@guilhermedcamacho This should be fine, we have already tested previous iterations of this and we ran the important tests here.

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by guilhermedcamacho** [comment]
Hey @vicnate5 , just to let you know that we found a related error analyzing again the test result of LocalFile.DMFileEntry#CanPreviewPDF. We tested it locally with and whiteout the changes.

Sending again on #218 , thanks a lot!

**Pull request closed without merging**
