### PR TITLE
LPS-198997 Merge UserBagFactory interface and impl into Util and move to portal-impl

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong Regression found in 


com.liferay.portal.security.permission.test.UserBagFactoryUtilTest > testGetRoles
```
 [exec] com.liferay.portal.security.permission.test.UserBagFactoryUtilTest > testGetRoles FAILED
[beanshell]      [exec]     com.liferay.portal.kernel.exception.ModelListenerException: com.liferay.portal.kernel.security.auth.PrincipalException: PermissionChecker not initialized
[beanshell]      [exec]     	at com.liferay.portal.security.audit.event.generators.internal.model.listener.RoleModelListener._auditOnAddOrRemoveAssociation(RoleModelListener.java:189)
[beanshell]      [exec]     	at com.liferay.portal.security.audit.event.generators.internal.model.listener.RoleModelListener.onBeforeAddAssociation(RoleModelListener.java:48)
[beanshell]      [exec]     	at com.liferay.portal.kernel.internal.service.persistence.TableMapperImpl._addTableMapping(TableMapperImpl.java:624)
[beanshell]      [exec]     	at com.liferay.portal.kernel.internal.service.persistence.TableMapperImpl.addTableMapping(TableMapperImpl.java:112)
[beanshell]      [exec]     	at com.liferay.portal.kernel.internal.service.persistence.change.tracking.CTTableMapper.addTableMapping(CTTableMapper.java:63)
[beanshell]      [exec]     	at com.liferay.portal.kernel.internal.service.persistence.ReverseTableMapper.addTableMapping(ReverseTableMapper.java:28)
[beanshell]      [exec]     	at com.liferay.portal.service.persistence.impl.GroupPersistenceImpl.addRole(GroupPersistenceImpl.java:15110)
[beanshell]      [exec]     	at com.liferay.portal.service.base.RoleLocalServiceBaseImpl.addGroupRole(RoleLocalServiceBaseImpl.java:499)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[beanshell]      [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell]      [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell]      [exec]     	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:57)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-29/test-portal-acceptance-pullrequest(master)/8390/modules-integration-mysql57-jdk8/3/13/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Comment by julschong** [comment]
@Kvale1733 testing locally, seems that regression is also on master on my end
I'm trying to see if my past tasks broken it

**Comment by Kvale1733** [comment]
@julschong Oh I didn't think to check the history of the previous test name. My bad. Yeah it's been failing since early October. There is already a ticket: https://liferay.atlassian.net/browse/LPS-198657. I'll pass this then since there were no other regressions.

**Comment by Kvale1733** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142342

**Pull request closed without merging**
