### PR TITLE
LPS-170848 Move Dom4jUtil to portal-impl

### PR DESCRIPTION
**Pull request by julschong**
resend from #2819

@tinatian 
Hi Tina,
for this pull, there are 3 parts that I'm not very sure if I'm missing anything.
1. Move Dom4jUtil to portal-impl and usages

2. portal-tool update ( very not sure if I did this correctly)
    I did `gw buildPluginDescriptor` and `gw commitCache` for all 5 plugins I changed
    Additionally also updated `portal-tool.properties` versions

3. Remove petra.xml and apps/petra entirely

### CODE REVIEW

**Comment by Kvale1733** [comment]
@julschong Regression in

service-builder-jdk8/0/0

```
build-service:
     [java] Java Result: 1
     [echo] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
     [echo] Exception in thread "main" java.lang.NoClassDefFoundError: com/liferay/petra/xml/XMLUtil
     [echo] 	at com.liferay.util.xml.XMLSafeReader.<init>(XMLSafeReader.java:26)
     [echo] 	at com.liferay.portal.tools.service.builder.ServiceBuilder.<init>(ServiceBuilder.java:613)
     [echo] 	at com.liferay.portal.tools.service.builder.ServiceBuilder.main(ServiceBuilder.java:237)
     [echo] Caused by: java.lang.ClassNotFoundException: com.liferay.petra.xml.XMLUtil
     [echo] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
     [echo] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [echo] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
     [echo] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [echo] 	... 3 more
```

[Log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-32/test-portal-acceptance-pullrequest(master)/7645/service-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
Removed any plugin version update to try ci again

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
[service-builder-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2147002374) failure still occurs:
```
build-service:
     [java] Java Result: 1
     [echo] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
     [echo] Exception in thread "main" java.lang.NoClassDefFoundError: com/liferay/petra/xml/XMLUtil
     [echo] 	at com.liferay.util.xml.XMLSafeReader.<init>(XMLSafeReader.java:26)
     [echo] 	at com.liferay.portal.tools.service.builder.ServiceBuilder.<init>(ServiceBuilder.java:613)
     [echo] 	at com.liferay.portal.tools.service.builder.ServiceBuilder.main(ServiceBuilder.java:237)
     [echo] Caused by: java.lang.ClassNotFoundException: com.liferay.petra.xml.XMLUtil
     [echo] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
     [echo] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [echo] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
     [echo] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [echo] 	... 3 more
```
Full console:
https://testray.liferay.com/reports/production/logs/2022-12/test-1-35/test-portal-acceptance-pullrequest(master)/3200/service-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Pull request closed without merging**
