### PR TITLE
LPS-170709 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 Service builder test will fail on this pull, could you please fix it by enabling "spring.extender.enabled" on ci env?

Thanks.
Tina

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
System check failing here on the base smoke test, but I cannot reproduce with a local build, only the build from CI
https://files.liferay.com/private/bundles/test-1-29/jobs/test-portal-acceptance-pullrequest(master)/builds/5715/liferay-portal-bundle-tomcat.tar.gz
```
2022-12-10 01:03:57.915 WARN  [main][SystemCheckOSGiCommands:134] Spring Extender Unavailable Component Checker check result: 
Bundle {id: 153, name: com.liferay.portal.tools.service.builder.test.service, version: 1.0.0}.
	Component with ID 1 is unavailable due to missing required dependencies:
		service dependency [javax.sql.DataSource (origin.bundle.symbolic.name=com.liferay.portal.tools.service.builder.test.service)]
Bundle {id: 153, name: com.liferay.portal.tools.service.builder.test.service, version: 1.0.0}.
	Component with ID 104 is unavailable due to missing required dependencies:
		service dependency [com.liferay.portal.kernel.model.Release (&(release.bundle.symbolic.name=com.liferay.portal.tools.service.builder.test.service)(&(release.schema.version>=1.0.0)(!(release.schema.version>=2.0.0)))(|(!(release.state=*))(release.state=0)))]
2022-12-10 01:03:57.916 INFO  [main][SystemCheckOSGiCommands:111] Running "Declarative Service Soft Circular Dependency Checker". You can run this by itself with command "ds:softCircularDependency" in gogo shell.
2022-12-10 01:04:00.614 INFO  [main][SystemCheckOSGiCommands:123] Declarative Service Soft Circular Dependency Checker check result: No issues were found.
2022-12-10 01:04:00.614 INFO  [main][SystemCheckOSGiCommands:111] Running "Declarative Service Unsatisfied Component Checker". You can run this by itself with command "ds:unsatisfied" in gogo shell.
2022-12-10 01:04:16.455 WARN  [main][SystemCheckOSGiCommands:134] Declarative Service Unsatisfied Component Checker check result: 
Bundle {id: 153, name: com.liferay.portal.tools.service.builder.test.service, version: 1.0.0}
	Declarative Service {id: 107, name: com.liferay.portal.tools.service.builder.test.change.tracking.spi.reference.CacheMissEntryTableReferenceDefinition, unsatisfied references: 
		{name: _cacheMissEntryPersistence, target: null}
	}
Bundle {id: 267, name: com.liferay.portal.tools.service.builder.test.uad, version: 1.0.0}
	Declarative Service {id: 823, name: com.liferay.portal.tools.service.builder.test.uad.exporter.UADPartialEntryUADExporter, unsatisfied references: 
		{name: uadPartialEntryLocalService, target: null}
	}
	Declarative Service {id: 822, name: com.liferay.portal.tools.service.builder.test.uad.display.UADPartialEntryUADDisplay, unsatisfied references: 
		{name: uadPartialEntryLocalService, target: null}
	}
	Declarative Service {id: 821, name: com.liferay.portal.tools.service.builder.test.uad.anonymizer.UADPartialEntryUADAnonymizer, unsatisfied references: 
		{name: uadPartialEntryLocalService, target: null}
	}
```
@zhangyan0701 Can you look into why the CI build might have the service builder test modules?

**Comment by yuhai** [comment]
@tinatian, except service builder test will fail. In the test classes, SpringExtenderTestComponentLocalServiceImpl and TestEntityLocalServiceBaseImpl also used the @ServiceReference. Related tests should also fail too.

**Comment by zhangyan0701** [comment]
> @zhangyan0701 Can you try removing `.lfrbuild-ci` from the service builder test modules? I don't know why we have them always deployed right now. We should only deploy those when they are needed. Run all the integration tests on the change.
> 
> We might need to create a separate test batch for the service-builder integration tests too, similar to what we have to do for project templates integration tests (`modules-integration-project-templates-jdk8`).

Hi @vicnate5  I removed `.lfrbuild-ci` from service builder test modules and run integration tests in https://github.com/zhangyan0701/liferay-portal/pull/427. And I tried to add a separate batch for service-builder, and a test suite to run all kinds of service builder tests, but I am not sure if they will work. Could you review my changes in https://github.com/zhangyan0701/liferay-portal/pull/427? Thanks!

**Pull request closed without merging**
