### PR TITLE
LPD-20946 ResourcePermission population | 9-4

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:objects

**Comment by dantewang** [comment]
ci:test:object

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:79319466

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7403

**Pull request closed without merging**
