### PR TITLE
LPS-155715 Cache clean up Part 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian looks good, no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go. This is part 1 of db partition cache support, the whole pull is at https://github.com/liferay-core-infra/liferay-portal/pull/1147

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/120822

**Pull request closed without merging**
