### PR TITLE
LPS-171602 When running a scheduled job manually it should only be executed on the company the user is logged in

### PR DESCRIPTION
**Pull request by LuisOrtiz89**
- LPS-171602 Adding integration tests to verify manual scheduled jobs executions happen on the right company
- LPS-171602 When a scheduled job is run from a company, we only want to run the scheduler for that company, not for everyone of them
- LPS-171602 Baseline
- LPS-171602 Updating test to fit the new API

### CODE REVIEW

**Comment by LuisOrtiz89** [comment]
Hi @tinatian, this is the new PR changing the API as we talked about in Slack.
Thanks!

**Comment by LuisOrtiz89** [comment]
ci:reevaluate:1257401_6146

**Comment by LuisOrtiz89** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@LuisOrtiz89 regression found:

`ClusterSchedulerEngineTest`
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-scheduler/portal-scheduler-multiple/src/test/java/com/liferay/portal/scheduler/multiple/internal/ClusterSchedulerEngineTest.java:1649: error: com.liferay.portal.scheduler.multiple.internal.ClusterSchedulerEngineTest.MockSchedulerEngine is not abstract and does not override abstract method run(long,java.lang.String,java.lang.String,com.liferay.portal.kernel.scheduler.StorageType) in com.liferay.portal.kernel.scheduler.SchedulerEngine
     [exec] 	private static class MockSchedulerEngine implements SchedulerEngine {
     [exec] 	               ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-scheduler/portal-scheduler-multiple/src/test/java/com/liferay/portal/scheduler/multiple/internal/ClusterSchedulerEngineTest.java:1768: error: method does not override or implement a method from a supertype
     [exec] 		@Override
     [exec] 		^
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/portal-scheduler/portal-scheduler-multiple/src/test/java/com/liferay/portal/scheduler/multiple/internal/ClusterSchedulerEngineTest.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 2 errors
     [exec] 
     [exec] > Task :apps:portal-scheduler:portal-scheduler-multiple:compileTestJava FAILED
     [exec] 
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-02/test-1-29/test-portal-acceptance-pullrequest(master)/6333/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

semver error:
```
     [exec] 
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/dispatch/dispatch-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.dispatch.scheduler                     MAJOR      1.0.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   interface  com.liferay.dispatch.scheduler.SchedulerResponseManager
     [exec]     		-   method     run(java.lang.String,java.lang.String,com.liferay.portal.kernel.scheduler.StorageType)
     [exec]     			-   access     abstract
     [exec]     			-   return     void
     [exec]     		+   method     run(long,java.lang.String,java.lang.String,com.liferay.portal.kernel.scheduler.StorageType)
     [exec]     			+   access     abstract
     [exec]     			+   return     void
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 17.0.0
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-02/test-1-29/test-portal-acceptance-pullrequest(master)/6333/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by LuisOrtiz89** [comment]
ci:test:sf

**Comment by LuisOrtiz89** [comment]
ci:test:relevant

**Comment by LuisOrtiz89** [comment]
Hi @catarineaguiar, code fixed. Running tests again. Please check results when available.

**Comment by LuisOrtiz89** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@LuisOrtiz89 Please remember to remove the QA Failed flag when you retrigger the ci tests, or else QA will not scan your test results.

Thanks.
Tina.

**Comment by Kvale1733** [comment]
@LuisOrtiz89 No regressions. The integration test passes. Testing also passed following the ticket steps.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3450

**Pull request closed without merging**
