### PR TITLE
LPS-195970 Merge PortalPermission interface and impl into Util in kernel

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
rebase and retest

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong tests were aborted due to:

```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-engine-api/src/main/java/com/liferay/portal/template/engine/TemplateContextHelper.java:712: error: cannot find symbol
     [exec] 				"portalPermission", PortalPermissionUtil.getPortalPermission());
     [exec] 				                                        ^
     [exec]   symbol:   method getPortalPermission()
     [exec]   location: class com.liferay.portal.kernel.service.permission.PortalPermissionUtil
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/portal-template/portal-template-engine-api/src/main/java/com/liferay/portal/template/engine/TemplateContextHelper.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 1 error
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-09/test-1-34/test-portal-acceptance-pullrequest(master)/4719/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
fixed getPortalPermission error, retest

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by julschong** [comment]
rename variable back to original in TemplateContextHelper

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
rebased

**Comment by julschong** [comment]
@shuyangzhou not moving this one

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
closed per our discussion

**Pull request closed without merging**
