### PR TITLE
[Remove Stream/Optional: Phase 3] LPS-181541 module: user-associated-data-web

### PR DESCRIPTION
**Pull request by JanisZhang**
previous: https://github.com/liferay-core-infra/liferay-portal/pull/4255

https://issues.liferay.com/browse/LPS-181541

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:user

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
@JanisZhang Do you have any other change besides the SearchContainer one in this PR compared to the last one?

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133510

@JanisZhang Modified commit message for https://github.com/brianchandotcom/liferay-portal/pull/133510/commits/a94971858d9a0b0ef9731feea77170d0d48670bb (vs https://github.com/liferay-core-infra/liferay-portal/pull/4274/commits/d63c2ffe46ed7a1502c2243c5c51c801f1ad3333)

**Comment by JanisZhang** [comment]
> Do you have any other change besides the SearchContainer one in this PR compared to the last one?

@dantewang No. Thank you!

**Pull request closed without merging**
