### PR TITLE
[Login-performance-tuning] LPS-150103

### PR DESCRIPTION
**Pull request by yuhai**
@tinatian @dantewang

### CODE REVIEW

**Comment by tinatian** [comment]
@yuhai Please add the cache in content.jsp rather than in renderContentLayoutDisplayContext.getPortletHeaderPaths(), this way you can also save the logic of writing to a writer and generation of string.

Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by yuhai** [comment]
@tinatian,  sorry, I don't understand your ideas. I want to explain the case's background.

1. In the getPortletHeaderPaths(), it is getting the portlet's **headerCssPaths** and **headerJavaScriptPaths** and then writing them to the html tag. In the getPortletFooterPaths(), it is getting the portlet's **footerCssPaths** and **footerJavaScriptPaths** and then writing them to the html tag. They are different contents.

2. For the same portlet in the different requests, we need to get portlet's these properties(headerCssPaths..) in the every request because portlet may be re-registered with different properties values. We can't reuse them in the different requests.

**Comment by yuhai** [comment]
ci:reopen

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:acceptance

**Comment by tinatian** [comment]
@yuhai As we talked, please resend.

Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
