### PR TITLE
LPD-8480 Remove unused @Reference variables in NotificationsSharingEntryLocalServiceWrapper.java

### PR DESCRIPTION
**Pull request by Valmir-unicap**
- Ticket: https://liferay.atlassian.net/browse/LPD-8480

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Valmir-unicap** [comment]
ci:test:sharing

**Comment by Valmir-unicap** [comment]
ci:report:2544266363

**Comment by Valmir-unicap** [comment]
No regression found!

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
