### PR TITLE
[Remove Spring extender usages] LPS-159489

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @tinatian @dantewang,

Resend. refer to https://github.com/liferay-core-infra/liferay-portal/pull/1292

This PR is to remove spring extender usage in commerce-notification-service, thanks!
https://issues.liferay.com/browse/LPS-159489

Previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/1249

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results when it finishes? Thanks!

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
