### PR TITLE
[TS] LPS-156654 Setting friendlyURLMapperClass on portletModel if it can be found in serviceReference

### PR DESCRIPTION
**Pull request by evibudai**
Hi Team,

https://issues.liferay.com/browse/LPS-156654

**Issue:**
When we deploy a portlet created with mvn clean install -Pcdi, the friendlyURL http://localhost:8080/web/guest/page/-/basic gives back:
"This portlet could not be found. Please redeploy it or remove it from the page"
Instead of showing the content of the portlet, like in the case of a portlet created with mvn clean install.

**Solution:**

As Eric Yan suggested on [LPP-45255](https://issues.liferay.com/browse/LPP-45255) we debugged where and when the friendlyUrl is set, and why it is behaving differently.
Debugging the code, we discovered that the friendlyURLMapperClass is not set, despite that it is present in serviceReference (properties).
So I went back where these values are set and I found that it should be in:
com.liferay.portal.osgi.web.portlet.tracker.internal.PortletTracker#_collectLiferayFeatures

I added the missing setter, and then I deployed the portlet and it worked as expected. I deployed and tested this separately on master and on 7.3.x (where it was originally reported), and both worked correctly.

Please review my PR!

Best regards,
Évi

### CODE REVIEW

**Comment by dantewang** [comment]
@evibudai I would like to confirm about why it works with normal packaging. Is the `friendURLMapperClass` set when deploying it using a normal packaging by https://github.com/liferay/liferay-portal/blob/c71aebfb34348579e3e427f41ef23ce3e8d14d2d/portal-impl/src/com/liferay/portal/service/impl/PortletLocalServiceImpl.java#L1503? But when deploying the CDI packaging that line is not called?

**Comment by dantewang** [comment]
@catarineaguiar Could you review the test results? Thanks!

**Comment by evibudai** [comment]
@dantewang Exactly.

> Is the `friendURLMapperClass` set when deploying it using a normal packaging by https://github.com/liferay/liferay-portal/blob/c71aebfb34348579e3e427f41ef23ce3e8d14d2d/portal-impl/src/com/liferay/portal/service/impl/PortletLocalServiceImpl.java#L1503?

Yes, it is set there with the mvn clean install portlet.

> But when deploying the CDI packaging that line is not called?

It is not called. The two deployment has a totally different stacktrace. The CDI packaging never goes to the PortletLocalServiceImpl.java class, it goes to PortletTracker only.

**Comment by dantewang** [comment]
@evibudai Thanks for confirming it. Yeah it matches what I'm seeing.

------

For CDI portlets, our CDI extension publishes them as OSGi services which are then tracked by `PortletTracker`.

For OSGi portlets, we expect the URL mappers to be also OSGi services, which will be tracked by `PortletBagFactory`. I think that's why we don't set the `friendlyURLMapperClass` property to the portlet model in `PortletTracker`.

Another possible way to fix it is to let CDI extension create the `FriendlyURLMapper` instance, publish it as OSGI service, but this may of course need more effort as CDI extension is very complicated. So I'm going to approve this change now.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:friendly-url

**Comment by evibudai** [comment]
@dantewang Thank you!

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123393

**Pull request closed without merging**
