### PR TITLE
[Method References 2] LPS-164457 Convert method reference to ServiceTrackerMap in module data-engine-service

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I convert method reference to ServiceTrackerMap in module data-engine-service.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by dantewang** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/124692

cc @shuyangzhou @tinatian

**Pull request closed without merging**
