### PR TITLE
LPS-176787 upgrade Apache Commons FileUpload to 1.15 

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This is for ticket https://issues.liferay.com/browse/LPS-176787.
Thanks for checking!

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:lima

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:lima

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 Regression in 

1)com.liferay.template.web.internal.portlet.action.test.UpdateTemplateEntryMVCActionCommandTest
```
[exec] com.liferay.template.web.internal.portlet.action.test.UpdateTemplateEntryMVCActionCommandTest > testUpdateTemplateEntry FAILED
     [exec]     java.lang.NullPointerException
     [exec]     	at com.liferay.portal.util.FileImpl.mkdirsParentFile(FileImpl.java:946)
     [exec]     	at com.liferay.portal.util.FileImpl.write(FileImpl.java:851)
     [exec]     	at com.liferay.portal.kernel.util.FileUtil.write(FileUtil.java:331)
     [exec]     	at com.liferay.portal.upload.UploadServletRequestImpl.getFile(UploadServ
```
[Log](https://testray.liferay.com/reports/production/logs/2023-03/test-1-38/test-portal-acceptance-pullrequest(master)/6683/modules-integration-mysql57-jdk8/4/2/jenkins-console.txt.gz?authuser=0)

2) Cannot add document with api

Steps to reproduce:
1. Go to Control Panel > Sites > Liferay DXP
2. Get the groupID of the site (it's at the end of the URL)
3. Execute the following in master source directory to add a document to the site. Substitute the repository ID with the groupID 
```
curl -X POST -u 'test@liferay.com:test' -F 'externalReferenceCode=' -F 'repositoryId=${groupID}' -F 'folderId=0' -F 'sourceFileName=Document_1.txt' -F 'mimeType=text/plain' -F 'title=DM Document Title' -F 'urlTitle=' -F 'description=DM Document Description' -F 'changeLog=' -F 'file=@test/functional/com/liferay/portalweb/dependencies/Document_1.txt' -F 'serviceContext={"addGroupPermissions" : true, "addGuestPermissions": true}' http://localhost:8080/api/jsonws/dlapp/add-file-entry

```

Expected Results: The document is added in Documents & Media to the Liferay DXP site (DM Document Title)
Actual Results: Locally you get "Failed to open/read local data from file/application". But on CI it's catching

```ERROR [http-nio-8080-exec-10][JSONWebServiceServiceAction:126] java.lang.NullPointerException```

[Log](https://testray.liferay.com/reports/production/logs/2023-03/test-1-38/test-portal-acceptance-pullrequest(master)/6683/functional-tomcat90-mysql57-chrome100-jdk8/3/13/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
