### PR TITLE
[Remove Blocking usages] LPS-193174 PortletResourcePermissionFactory and ModelResourcePermissionFactory

### PR DESCRIPTION
**Pull request by haydenzheng314**
Cleanup and reesend. cc @dantewang 
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/6282
Ticket: https://liferay.atlassian.net/browse/LPS-193174
Thanks.

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@LisztLiszt No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
