### PR TITLE
Lpd 36036 11 8

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:app-servers

**Comment by dantewang** [comment]
ci:report:68010334

**Comment by dantewang** [comment]
ci:test:app-servers:norebase

**Comment by dantewang** [comment]
ci:report:68010334

**Comment by dantewang** [comment]
ci:report:68276285

**Comment by dantewang** [comment]
@shuyangzhou Rebased and sent to https://github.com/liferay-core-infra/liferay-portal/pull/7639

**Pull request closed without merging**
