### PR TITLE
[Components with more than 1 service] LPS-192496 Refactor ConfigurationModelIndexer component

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Related: https://liferay.atlassian.net/browse/LPS-192496

Correction of: https://github.com/liferay-core-infra/liferay-portal/pull/5204 and https://github.com/liferay-core-infra/liferay-portal/pull/5294

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Valmir-unicap** [comment]
ci:test:usm

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Valmir-unicap** [comment]
ci:test:usm

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
ci:forward:force

**Pull request closed without merging**
