### PR TITLE
LPD-15371 remove "include commons-*.jar" in whiteboard, and use shared-dependnecies instead

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

As talked, I commons-*.jar, and start to use shared-dependencies for commons-lang3
Thanks for checking

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:report:2530207698

**Comment by jeffwu0724** [comment]
no unique regression found

**Comment by jeffwu0724** [comment]
ci:report:2530314954

**Comment by jeffwu0724** [comment]
unique error
https://testray.liferay.com/home/-/testray/case_results/2530320256/history
https://testray.liferay.com/home/-/testray/case_results/2530319916/history
https://testray.liferay.com/home/-/testray/case_results/2530320211/history

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:report:2530400215

**Comment by jeffwu0724** [comment]
Unique error:

1. https://testray.liferay.com/home/-/testray/case_results/2530405370: can also see on [master ](https://testray.liferay.com/home/-/testray/case_results/2487161106?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2487146674%26cur%3D2%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26resetCur%3Dfalse)
2. https://testray.liferay.com/home/-/testray/case_results/2530405178: can also see on [master ](https://testray.liferay.com/home/-/testray/case_results/2487160426?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2487146674%26cur%3D2%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26resetCur%3Dfalse)
3. https://testray.liferay.com/home/-/testray/case_results/2530405410/history: can also reprodueced on a clean master

**Comment by jeffwu0724** [comment]
no code conflict: 1/29/2024 - 11:10am

**Comment by jeffwu0724** [comment]
upgrade the commit messges, the previous test result is good enough

**Comment by tinatian** [comment]
ci:forward:force

**Comment by tinatian** [comment]
ci:stop

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:report:2532648273

**Comment by jeffwu0724** [comment]
https://testray.liferay.com/home/-/testray/case_results/2532662438/history 
```
Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections.FastHashMap cannot be found by com.liferay.shared.dependencies.apache.commons_1.0.10
		at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
		at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
		at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:404)
		at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:151)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
```

**Pull request closed without merging**
