### PR TITLE
[Method References 2] LPS-170773 Convert method reference to field reference in class LiferayResourceOwnerAccessTokenGrantHandler（module oauth2-provider-rest）

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(12/12 9:49)

**Comment by W2jx** [comment]
no conflicts(12/13 9:53)

**Comment by W2jx** [comment]
no conflicts(2022/12/14 9:32)

**Comment by W2jx** [comment]
no conflicts(12/15 9:21)

**Comment by W2jx** [comment]
no conflicts(2022/12/16 8:57)

**Comment by tinatian** [comment]
@W2jx You missed this logic :
if (_resourceOwnerGrantHandler != null) {
			_resourceOwnerGrantHandler.setDataProvider(
				_liferayOAuthDataProvider);
		}

@dantewang Please help @W2jx figure out a solution to deal with this.

**Pull request closed without merging**
