### PR TITLE
[TS] LPS-164298 changing catch to NoSuchFileEntryException as NoSuchImageException is not being thrown, avoid sending default error when NSFE is thrown as 404 is being sent already

### PR DESCRIPTION
**Pull request by jgarcialr**
- LPS-164298 changing catch to NoSuchFileEntryException as NoSuchImageException is not being thrown, avoid sending default error when NSFE is thrown as 404 is being sent already
- LPS-164298 remove null checking as it's done by instanceof operation
- LPS-164298 Add NavigateFromPageWithMissingImageWithoutError test

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:lima

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:lima

**Comment by zhangyan0701** [comment]
Test failure [LocalFile.DMFriendlyURL#CannotPreviewImageWithRemovedFriendlyURL](https://testray.liferay.com/home/-/testray/case_results/2144316881) should be related.

Steps:
1. Upload an image in Documents and Media. 
2. Edit the image, change the friendly url to a new one. Publish.
3. Edit the image again, delete the old friendly url from the friendly url history. Publish.
4. Open the image with the old friendly url.

Result: Internal server error occurs.
Expected: According to the test, the error that shows in page should be Not Found.
fileinternalservererror

**Pull request closed without merging**
