### PR TITLE
[TS] LPS-183421

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-183421

Applying this fix based on [PTR-3835](https://issues.liferay.com/browse/PTR-3835)

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@tinatian This pull follows the same pattern in `AccountEntryLocalServiceImpl#updateAccountEntry`.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/135305

**Pull request closed without merging**
