### PR TITLE
[Method References 2] LPS-176946 Convert method reference to ServiceTrackerList in class OAuth2JSONWSAuthVerifier and SAPEntryScopeDescriptorFinderRegistrator

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3737

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:oauth2

**Comment by W2jx** [comment]
ci:test:oauth2

**Comment by W2jx** [comment]
no conflicts(3/17 14:36)

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(3/20 8:52)

**Comment by W2jx** [comment]
no conflicts(3/21 10:29)

**Pull request closed without merging**
