### PR TITLE
LPD-42200 Create PortletCategory on demand

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:71464637

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 71464637.
> 
> Job Link: [generate-testray-csv](https://test-1-39.liferay.com/job/generate-testray-csv/499/)
> 
> Testray CSV Link: [testray-results-71464637.csv](https://test-1-39.liferay.com/userContent/jobs/generate-testray-csv/builds/499/testray-results-71464637.csv)

No unique failure in report.

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
