### PR TITLE
LPS-144170 Move gif89.jar, im4java.jar and monte-cc.jar to modules

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test:document

**Comment by rafaprax** [comment]
Hey @vicnate5, can you help me to scan these test results? Thanks!

**Comment by vicnate5** [comment]
@rafaprax The results that came in show no regression, but I am unable to analyze the default suite results due to the Jenkins error. Asking the CI team if this can be recovered.

**Comment by vicnate5** [comment]
@rafaprax Got the full results, no regressions found.

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
Hey All,

I just re-ran the tests because I fixed some conflicts but without logic changes. So, @vicnate5's previous analysis is still valid. 

> @rafaprax Got the full results, no regressions found.

Thx

**Comment by tinatian** [comment]
Hi @rafaprax ,
There are two things I would like you to do:
1. `ImageToolHelper`. This is needed as one of the usage is not in OSGi module. I would like to avoid this by moving out all the DL related processors into module which would include the `PDFProcessorImpl`. Could you please check if it is possible to do this?
2. `ImageTool`. Looking at this interface, it have two groups of behaviors: one is to do image related logic which requires the third party libs, another is to get default images for application level usages like `getDefaultCompanyLogo()` which does not depend on third party directly. By moving out `ImageToolImpl`, you moved out both groups, and this will left the related property setting and image files for `getDefaultCompanyLogo()` in portal-impl. This is not a good design to me. Could you please try to move out the logic depends on third-party libs directly only?

I am going to close this pull, please resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by shuyangzhou** [comment]
@rafaprax @tinatian see my comment on the google doc and https://github.com/shuyangzhou/liferay-portal/pull/10502 for gif89.jar removal.

**Comment by guilhermedcamacho** [comment]
@rafaprax is on vacation, I adjusted this PR for him, thanks @shuyangzhou :+1:

**Pull request closed without merging**
