### PR TITLE
LPS-144797: PREFS_OWNER_TYPE_LAYOUT must have valid plid, even if Preferences is Unique Per Layout.

### PR DESCRIPTION
**Pull request by kristofloneck**
Hi
Could you review this solution please?
Thank you.

### CODE REVIEW

**Comment by kristofloneck** [comment]
Hi @liferay-core-infra
Sorry for the minor inconvenience but could you review this solution, please
Thank you.

**Comment by kristofloneck** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@rafaprax Please take this over.

Thanks.
Tina.

**Comment by rafaprax** [comment]
Hey @kristofloneck, Can you please forward this to the Staging Team? This issue is about an Export/Import feature and they are the team in charge of this API.

Thx

**Pull request closed without merging**
