### PR TITLE
[Disable auto-import-default-references]LPS-164199

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to disable auto-import-default-references in `sharepoint-rest-oauth2-service`. Thanks!
https://issues.liferay.com/browse/LPS-164199

### CODE REVIEW

**Comment by zhangyan0701** [comment]
Possible regression, errors occur during portal startup:
```
[beanshell] [2022-09-27T19:32:55,254][ERROR][o.e.x.c.t.IndexTemplateRegistry] [liferay]error adding index template [metrics-mappings] from [/metrics-mappings.json] for [stack]
[beanshell] com.ibm.icu.util.ICUException: not enough bytes
```

Example full console:
https://testray.liferay.com/reports/production/logs/2022-09/test-1-25/test-portal-acceptance-pullrequest(master)/4774/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@shuyangzhou @tinatian @JanisZhang See https://github.com/brianchandotcom/liferay-portal/pull/123860

**Pull request closed without merging**
