### PR TITLE
[Method References 2] LPS-171023 Convert method reference to ServiceTrackerMap in class IndexResourceImpl(module portal-workflow-metrics-rest-impl)

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:workflow

**Comment by zhangyan0701** [comment]
ci:test:workflow-metrics

**Comment by Kvale1733** [comment]
ci:test:workflow-metrics

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(12/15 9:19)

**Comment by W2jx** [comment]
no conflicts(2022/12/16 8:57)

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by W2jx** [comment]
ci:test:workflow-metrics

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts（12/20 9:45）

**Pull request closed without merging**
