### PR TITLE
[Component with its own class name as service type] LPS-199140 Refactor Helper and ContextFactory classes from sharing module

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Issue: https://liferay.atlassian.net/browse/LPS-199140

Forwarded from: https://github.com/rafaprax/liferay-portal/pull/1376

Ticket: https://liferay.atlassian.net/browse/LPS-199140

Correction of PR: https://github.com/liferay-core-infra/liferay-portal/pull/6323

Correction of PR from @regiCesar21: https://github.com/liferay-core-infra/liferay-portal/pull/6031

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:sharing

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @tinatian

**Pull request closed without merging**
