### PR TITLE
LPS-180750 Remove immediate from SettingsLocatorHelperImpl

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-180750

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
Found issues:
1. Some integration tests failed with error: `java.lang.NoSuchMethodException: No method on null with name registerConfigurationBeanClass and parameter types [class java.lang.Class]`: [com.liferay.portal.configuration.settings.internal.test.SettingsLocatorHelperTest](https://testray.liferay.com/home/-/testray/case_results/2263419491)
[com.liferay.portal.configuration.settings.internal.test.PortletInstanceSettingsLocatorTest](https://testray.liferay.com/home/-/testray/case_results/2263419481)
[com.liferay.portal.configuration.settings.internal.test.GroupServiceSettingsLocatorTest](https://testray.liferay.com/home/-/testray/case_results/2263419472)
[com.liferay.portal.configuration.settings.internal.test.CompanyServiceSettingsLocatorTest](https://testray.liferay.com/home/-/testray/case_results/2263419464)

2. Semantic versioning issue:
```
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.settings                 MINOR      3.2.0      3.2.0      3.3.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.portal.kernel.settings.LocationVariableResolver
     [exec] 		+   method     <init>(com.liferay.portal.kernel.resource.manager.ResourceManager,java.util.function.Function)
     [exec] 			+   return     void
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/102.1.0/62c3647c76b51bb625019e03743beb84220be49/com.liferay.portal.kernel-102.1.0.jar
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10512/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@rafaprax No regressions.

**Comment by rafaprax** [comment]
\cc @shuyangzhou

**Pull request closed without merging**
