### PR TITLE
[Component with its own class name as service type] LPS-197625 Refactor components server-admin-web, push-notifications-sender-apple, portal-search components

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-197625](https://liferay.atlassian.net/browse/LPS-197625)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142563

**Pull request closed without merging**
