### PR TITLE
[Components with more than 1 service] LPS-192654 Refactor SXPParameterDataCreator component

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://liferay.atlassian.net/browse/LPS-192654

### CODE REVIEW

**Comment by rafaprax** [comment]
tests passed in the previous pr

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
resent here #5374

**Pull request closed without merging**
