### PR TITLE
LPS-84865

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, after fixing this ticket([LPS-84865](https://issues.liferay.com/browse/LPS-84865)), [LPS-84801](https://issues.liferay.com/browse/LPS-84801) can be closed.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
See https://issues.liferay.com/browse/LPS-84801

**Comment by dantewang** [comment]
ci:close

**Comment by dantewang** [comment]
ci:stop

**Pull request closed without merging**
