### PR TITLE
LPD-25517 Adapt tests using hard-coded test password in File Install component

### PR DESCRIPTION
**Pull request by MrJohn1911**
Tested here: https://github.com/MrJohn1911/liferay-portal/pull/85

The tests did't fail / didn't had any unique failure.

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:2568312882

**Comment by dantewang** [comment]
ci:forward

cc @tinatian @julschong

**Pull request closed without merging**
