### PR TITLE
LPS-134898 6-13

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian @marianoalvarosaiz

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
@dantewang do we have any updates about this pull?

**Comment by tinatian** [comment]
@marianoalvarosaiz I do not understand your test, in your test, you trigger multiple add, but no assert, what would you expect with those add invocation? Also, you test did not show why you need a fetch of the row, could you please explain why?

**Comment by dantewang** [comment]
@tinatian 

The test actually just asserts that no exception is thrown, so it doesn't have any real Assert.assert*.

On the other hand, the fetch is used to trigger the flush before the transaction is over, in order to emulate the "race condition". I didn't manage to think of a more self-explanatory way to do this, so I asked @marianoalvarosaiz to add comments.

**Comment by marianoalvarosaiz** [comment]
@tinatian as @dantewang points the idea is to test that no exception is thrown.

The idea of the test is just to point that a flush in the middle of the method can throw an exception, so it should be recommendable adding a safe fetch before modifying the row.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/1028

**Pull request closed without merging**
