### PR TITLE
[Components with more than 1 service] LPS-192654 Refactor SXPParameterDataCreator component

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-192654](https://liferay.atlassian.net/browse/LPS-192654)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:stop

**Comment by RenanUmV** [comment]
si:test:sf

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:search

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@RenanUmV No regressions found.

**Comment by shuyangzhou** [comment]
@RenanUmV please inline SXPParameterContributorDefinitionProvider/SXPParameterContributorDefinitionProviderImpl into SXPParameterContributorDefinitionResourceImpl

**Pull request closed without merging**
