### PR TITLE
Lpd 38963 10 11

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:39785799

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:40320960

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 40320960.
> 
> Job Link: [generate-testray-csv](https://test-1-25.liferay.com/job/generate-testray-csv/177/)
> 
> Testray CSV Link: [testray-results-40320960.csv](https://test-1-25.liferay.com/userContent/jobs/generate-testray-csv/builds/177/testray-results-40320960.csv)

Unique failures in report are not unique to this pull.

**Comment by tinatian** [comment]
ci:forward:force

**Comment by tinatian** [comment]
@victorhcunha Please verify benchmark performance, let's check Login first, if there is regression, no need to check others.

**Comment by tinatian** [comment]
@JerryAdrianoo Please verify startup performance.

**Comment by JerryAdrianoo** [comment]
Hi @tinatian  for more details, see: [results](https://docs.google.com/spreadsheets/d/1gVzkPMpeaZpdmikPMYUyLDerS-xIAXdwWgwXTdBAGIQ/edit?usp=sharing) 

Branch| Startup Time (ms)(without  default HSQL data)  Cold start | Percent of Average Startup Time Cold Start | Startup Time (ms)(without  default HSQL data) Hot start | Average Startup Time (ms)(without default HSQL data)  Hot start | Percent of Average Startup Time Hot Start | Shutdown Time (ms)(without default HSQL data)   Cold start | Shutdown Time (ms)(without default HSQL data)  Hot start | Average Shutdown Time (ms)(without default HSQL data)  Hot start
-- | -- | -- | -- | -- | -- | -- | -- | --
Before LPD-38963 | **49,714** | | 18,329 | | | **2,568** | 2,581
|  | | | 16,813 | | | | 1,907
|  | | | 16,180 | | | | 1,957
 | | | | 16,788 | | | | 2,000
 | | | | 16,091|**16,594** | | | 2,052 | **2,003**
-- | -- | -- | -- | -- | -- | -- | --
After LPD-38963 | **47,234** | | 17,833 | | | **2,660** | 2,047
|  | | | 16,140 | | | | 1,970
|  | | | 16,501 | | | | 1,998
|  | | | 16,693 | | | | 1,897
| | |  -4.99% | 16,760 |**16.593** |  **-0.01%** | | 1,958 | **1,975**

This variation in the Cold Startup is under control and is expected. No other changes were noticed on the different metrics.

**Comment by victorhcunha** [comment]
Hi @tinatian !

From the runtime tests, the results with the login test case got a lower result, but considering the variation we have regularly, I'm doing new runs to see if the values ​​confirm as such. For the other test cases, no regressions were presented. You can see the results here:
(for detailed results please see this [spreadsheet](https://docs.google.com/spreadsheets/d/1rRiaITla-Fc1j6s-ic32pfq_PZwM93HrtiTG6TZEfSs/edit?gid=0#gid=0))

**WC**
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | ES CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Master Baseline | dcc7444 | 17170 | - | 490 | 3,3,5 | 0,0,0 | 96,97,97
PR | - | 17145 | -0.1456027956 | 484 | 4,3,4 | 0,0,0 | 96,97,97


**Document Library**
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | ES CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Master Baseline | dcc7444 | 9339 | - | 515 | 10,9,9 | 2,2,2 | 88,90,96
PR | - | 9426 | 0.9315772567 | 572 | 10,9,9 | 2,2,2 | 89,94,95

**Asset Publisher**
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | ES CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Master Baseline | dcc7444 | 7548 | - | 185 | 9,9,7 | 26,23,25 | 93,94,93
PR | - | 7784 | 3.126656068 | 210 | 8,8,8 | 26,27,26 | 92,93,94

**Comment by victorhcunha** [comment]
Update: Here are the new results for the login test case (this test was using env 3 while env2 was busy with daily testing):

Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | ES CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Master Baseline | dcc7444 | 13498 | - | 274 | 1,1,1 | 0,0,0 | 96,95,96
PR - round 2 | - | 13857 | 2.659653282 | 280 | 1,1,1 | 0,0,0 | 96,95,96

No apparent regression. The results of the other rounds are also available in the [spreadsheet](https://docs.google.com/spreadsheets/d/1rRiaITla-Fc1j6s-ic32pfq_PZwM93HrtiTG6TZEfSs/edit?gid=0#gid=0).

**Comment by tinatian** [comment]
Thanks @victorhcunha and @JerryAdrianoo !

**Pull request closed without merging**
