### PR TITLE
[Remove Blocking usages] LPS-193174 PortletResourcePermissionFactory and ModelResourcePermissionFactory

### PR DESCRIPTION
**Pull request by haydenzheng314**
@dantewang Resend as we talked.
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/6094
Ticket: https://liferay.atlassian.net/browse/LPS-193174
Thanks.

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by LisztLiszt** [comment]
ci:stop

**Comment by dantewang** [comment]
@LisztLiszt packageinfo conflict.

**Comment by LisztLiszt** [comment]
ci:test:sf

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by LisztLiszt** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
See https://github.com/LisztLiszt/liferay-portal/pull/10

**Pull request closed without merging**
