### PR TITLE
LPS-145773

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian, @shuyangzhou ,

I have removed unused properties "users.list.views", and updated to propskeys.java, propsvalues.java and verifyproperties.java.
"USERS_LIST_VIEWS" was created in commit 3e62e31a0cb6731a88cd39e20693e903749e0c16, LPS-16332, and it was used in list_views.jspf. 
This file was rename to portal-web/docroot/html/portlet/users_admin/user/list_views.jspf, based on commit 2163bda7d78e8d1ad2e7a5c1dab1739ec5d6efa2, see LPS-18024. 
"USERS_LIST_VIEWS" was finally deleted in commit ab2619057412b174b940e5568f1da1aaaa58fe80, see LPS-21299
Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.
@jeffwu0724 Code looks good to me, wait for QA to scan test results.

Tina.

**Comment by vicnate5** [comment]
@Hijky Can you check the results here?

**Comment by Hijky** [comment]
None of the failed cases are relevant

**Pull request closed without merging**
