### PR TITLE
[TS] LPS-169760 Cannot configure a custom tika.xml in the system-ext.properties file

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-169760

After the changes applied by LPS-147938, the customer can no longer configure a custom tika.xml in the system-ext.properties file and the configuration is silently ignored.

**Root cause**
In that LPS the tika library was extracted to an OSGI module and it was changed from using the default new TikaConfig() constructor that internally uses the tika.config system environment property ([see old code](https://github.com/liferay/liferay-portal/blob/8a681740a339888c79b3030b84dc5c4340a9d562/portal-impl/src/com/liferay/portal/util/FileImpl.java#L1217-L1223)) to use another constructor that receives the specific tika.xml file from the osgi module ([see new code](https://github.com/liferay/liferay-portal/blob/ec453722f5b8c22702409c8f5f3aba381edbd8a9/modules/apps/portal/portal-tika/src/main/java/com/liferay/portal/tika/internal/util/TikaConfigUtil.java#L32-L33)).

**Solution**
To allow configuring the custom tika.xml in the system-ext.properties, we can use again the TikaConfig constructor that we used previously:

 - TikaConfig code: https://github.com/apache/tika/blob/b41d16d73ea34a2ed2afb6bf456cba336ed090e1/tika-core/src/main/java/org/apache/tika/config/TikaConfig.java#L231-L293

and set the osgi module classloader to the ServiceLoader class:
 - Tika ServiceLoader code: https://github.com/apache/tika/blob/b41d16d73ea34a2ed2afb6bf456cba336ed090e1/tika-core/src/main/java/org/apache/tika/config/ServiceLoader.java#L96-L106
 - TikaConfig code: https://github.com/apache/tika/blob/b41d16d73ea34a2ed2afb6bf456cba336ed090e1/tika-core/src/main/java/org/apache/tika/config/TikaConfig.java#L314-L335

Let me know if you have any question

### CODE REVIEW

**Comment by Kvale1733** [comment]
No regressions found and passed manual testing following ticket steps.

**Comment by zhangyan0701** [comment]
Manually testing following below steps:

1. Go to [LIFERAY_HOME]/tomcat-9.0.x/webapps/ROOT/WEB-INF/classes.
2. Create a system-ext.properties file.
3. Set the property `tika.config=a valid path but different from the default one` in system-ext.properties.
4. Startup the Liferay server.

Rresult:
The server starts up correctly and no errors in log.

**Comment by jorgediaz-lr** [comment]
Hi @zhangyan0701 @dantewang

Do you have any updates about this PR?

I would like to merge this to master before sending a hotfix to my customer.

Thank you

**Review by dantewang — APPROVED** [review]

**Comment by jorgediaz-lr** [comment]
Thanks for your review, @dantewang

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

I’m sorry for the rush, our customer is upgrading from 7.2 to 7.4 and this is blocking their planning.

Do you think it is ok to send them a hotfix with this solution?

I cannot send them a hotfix if a different approach than configuring tika.xml in system-ext.properties is finally merged into master.

Thank you,
Jorge

**Comment by tinatian** [comment]
@jorgediaz-lr @dantewang 
The fix is simple and clean, but it breaks the current role of portal-tika. Portal-tika is not part of portal-impl and portal-kernel any more, it is already a separate module, then it should manage its own configuration rather than delegate it to system.properties.

There are some options:

Option 1:
Create a configuration for portal tika, allow people to pass in a configuration file path
When customer wants to provide their own configurations, two ways to go: 
a) create a fragment bundle with the customer file and modify the configuration to point to the new file 
b) Add a fallback logic when loading the file in portal-tika, make it fall back to portal class loader, so that you can put the file inside [LIFERAY_HOME]/tomcat-9.0.x/webapps/ROOT/WEB-INF/classes, then modify the configuration to point to the new file

Option 2:
Figure out what customer wants to change, and provide configurations for them. For example, customer wants to define the parsers, then you may have a property asking for the parsers, then you regenerate the xml file based on the info you collected by the configuration, and pass it in to the initialization.

Option1b should be the easiest and most similar to what current customer does, could you please send a new pull about it?

Any questions, please feel free to let me know. I am going to close this pull, please resend.

Thanks
Tina.

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

Thanks for your message.

About option 1b: The idea would be to try reading a tika.xml file from the portal classloader ([LIFERAY_HOME]/tomcat-9.0.x/webapps/ROOT/WEB-INF/classes) and in case the file doesn't exist, fallback to the current `dependencies/tika.xml` file that is inside the portal-tika module?

Or am I missing anything?

Thank you.

**Comment by marianoalvarosaiz** [comment]
Hi @tinatian,

 did you have time to review @jorgediaz-lr question?

Kind regards.

**Comment by jorgediaz-lr** [comment]
Hi @marianoalvarosaiz 

Tina answered me in Slack:

> _No, it would be having a configuration passing in a file path, load the file using current class loader, if not found, load it by portal classloader, if still not found, fall back to current "dependencies/tika.xml"_

Sorry for not forwarding the message to you

**Comment by jorgediaz-lr** [comment]
I have sent a new PR here: https://github.com/liferay-core-infra/liferay-portal/pull/2743 adding the tika xml configuration to System Settings

**Pull request closed without merging**
