### PR TITLE
LPS-157036

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
re-running acceptance because many tests failed

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
no regressions on relevant, I'm waiting for acceptance results.

**Comment by catarineaguiar** [comment]
not possible to analyze acceptance results, because most tests were aborted. But according to relevant results no regression was found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Ci test acceptance passed at previous pull https://github.com/liferay-core-infra/liferay-portal/pull/1103, this pull just modify documents, so the previous checking is still valid.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121147

**Pull request closed without merging**
