### PR TITLE
LPD 26157 dxp master new pattern

### PR DESCRIPTION
**Pull request by titokenzo**
- **LPD-26157 SF, make AssetCategoryTreePathComparator class attributes private**
- **LPD-26157 Make StructureStructureKeyComparator class attributes private**
- **LPD-26157 semver**
- **LPD-26157 Add singleton to AssetTagCountComparator and apply**
- **LPD-26157 Add singleton to AssetEntryAssetCategoryRelAssetCategoryIdComparator and apply**
- **LPD-26157 Add singleton to AssetListEntryCreateDateComparator and apply**
- **LPD-26157 baseline**
- **LPD-26157 Add Upgrade case and test**

### CODE REVIEW

**Comment by titokenzo** [comment]
ci:test:relevant

**Comment by titokenzo** [comment]
ci:report:9376165

**Comment by titokenzo** [comment]
Erros not related to the PR.

**Comment by dantewang** [comment]
@titokenzo See https://github.com/liferay-core-infra/liferay-portal/pull/7154

I modified some of your commit messages, rewording the breaking change logs and adding "alternatives" sections. I also ran SF and committed a change for https://github.com/liferay-core-infra/liferay-portal/pull/7107/commits/709b35590e777244b48fb164e0f10a227989a260.

**Pull request closed without merging**
