### PR TITLE
LPS-144119 Remove ical4j

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Should I run ci:test for this PR? @vicnate5 @tinatian

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/111354

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
