### PR TITLE
[Remove immediate=true usage core-infrastructure-4 part-2]Lps 168633 part 2

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-168633

### CODE REVIEW

**Comment by slnn** [comment]
ci:test

**Comment by slnn** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128451

**Pull request closed without merging**
