### PR TITLE
[Component with its own class name as service type] LPS-198943 Refactor Helper components from commerce modules part 1

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-198943](https://liferay.atlassian.net/browse/LPS-198943)

### CODE REVIEW

**Comment by regiCesar21** [comment]
ci:stop

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found.

Let's wait stable results

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142874

**Pull request closed without merging**
