### PR TITLE
LPD-42083 fix compile error on ThreadLocalAwareBackgroundTaskExecutorTest

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

I have created a ticket here https://liferay.atlassian.net/browse/LPD-42083 to fix this broken test

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:report:68997994

**Comment by jeffwu0724** [comment]
no unique regression found

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
