### PR TITLE
LPS-148577 Move java-libpst.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
@koor4356 please help me check the results, thanks!

**Comment by koor4356** [comment]
okay,thanks!

**Comment by koor4356** [comment]
@rafaprax 
This looks good, thanks!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by tinatian** [comment]
@rafaprax Code conflicts, please rebase.

Thanks.
Tina.

**Comment by rafaprax** [comment]
Conflicts solved. 

/cc @tinatian @shuyangzhou

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114347

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
