### PR TITLE
remove_unused_properties_part1

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian , @shuyangzhou ,

I have removed four groups of unused properties, and they are "default.guest.public.layout.column-",  "multi.value.map.com.liferay.portal.convert.ConvertPermissionAlgorithm.", "Pop.server.notifications.interval", and "editor.wysiwyg.portal-web.docroot.html.portlet.mail.".

**"default.guest.public.layout.column-"** - https://github.com/tinatian/liferay-portal/pull/2488
**"multi.value.map.com.liferay.portal.convert.ConvertPermissionAlgorithm."** - https://github.com/liferay-core-infra/liferay-portal/pull/254
**"Pop.server.notifications.interval"** - https://github.com/liferay-core-infra/liferay-portal/pull/236
**"editor.wysiwyg.portal-web.docroot.html.portlet.mail."** - https://github.com/tinatian/liferay-portal/pull/2506

Thanks for checking!

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@vicnate5 Can you help me scan the test result, please?

Thanks.
Jeff

**Comment by vicnate5** [comment]
@jeffwu0724 This causes startup errors on all non-tomcat app servers
Wildfly: https://testray.liferay.com/reports/production/logs/2022-02/test-1-27/test-portal-acceptance-pullrequest(master)/1702/functional-smoke-wildfly230-mariadb104-jdk8/0/0/liferay-log.txt.gz?authuser=0
Weblogic: https://testray.liferay.com/reports/production/logs/2022-02/test-1-27/test-portal-acceptance-pullrequest(master)/1702/functional-smoke-weblogic122-mysql57-jdk8/0/0/liferay-log.txt.gz?authuser=0
Websphere: https://testray.liferay.com/reports/production/logs/2022-02/test-1-27/test-portal-acceptance-pullrequest(master)/1702/functional-smoke-websphere90-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0

If you want to see this locally, Wildfly would be the easiest to build locally
1. set "app.server.type=wildfly" in `app.server.properties`
2. ant -f build-dist.xml unzip-wildfly
3. ant all 

re-test this with ci test app-servers

**Comment by jeffwu0724** [comment]
ci:test:app-servers

**Comment by jeffwu0724** [comment]
ci:test:app-servers

**Comment by jeffwu0724** [comment]
ci:test:app-servers

**Comment by vicnate5** [comment]
@jeffwu0724 The app server startup errors are unrelated to this PR. See https://issues.liferay.com/browse/LPS-147120

**Comment by tinatian** [comment]
@vicnate5 Is this pull good to go?

Tina

**Comment by vicnate5** [comment]
@tinatian This will require a version bump, but no regressions found.

**Comment by tinatian** [comment]
@jeffwu0724 Please rebase.

Tina

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by tinatian** [comment]
@jeffwu0724 Code conflicts, please rebase again.

Thanks.
Tina

**Pull request closed without merging**
