### PR TITLE
[Replace Non-Blocking Usage] LPS-199703

### PR DESCRIPTION
**Pull request by JanisZhang**
resent:https://github.com/liferay-core-infra/liferay-portal/pull/5861
https://liferay.atlassian.net/browse/LPS-199703

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
@JanisZhang many tests failed due to a startup failure:

```
[beanshell] 2023-10-24 19:47:16.299 ERROR [liferay/background_task_status-2][SerialDestination:55] Unable to process message {destinationName=liferay/background_task_status, response=null, responseDestinationName=null, responseId=null, payload=null, values={defaultLocale=en_US, companyId=10155, taskExecutorClassName=com.liferay.portal.workflow.metrics.internal.background.task.WorkflowMetricsReindexBackgroundTaskExecutor, groupId=0, name=WorkflowMetricsIndexCreator, backgroundTaskId=16434, status=3}}
[beanshell] com.liferay.portal.kernel.messaging.MessageListenerException: java.lang.NullPointerException
[beanshell] 	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:32) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:65) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.messaging.internal.SerialDestination$1.run(SerialDestination.java:50) [bundleFile:?]
[beanshell] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_381]
[beanshell] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_381]
[beanshell] 	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_381]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-27/test-portal-acceptance-pullrequest(master)/10470/functional-upgrade-tomcat90-mysql57-jdk8/2/17/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
