### PR TITLE
[Round 4 Method references Static]Lps 181665

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-181665

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:security

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
@slnn Please name the extracted class "CaptchaProvider" or "CaptchaRegistry", and only provide a public API to return the currently selected `Captcha`.

**Comment by dantewang** [comment]
@slnn By the way,

```
	@Deactivate
	protected void deactivate() {
		_serviceTrackerMap.close();

		_serviceTrackerMap = null;
	}
```

Setting it to null is no longer needed after extracting to a instance component.

**Comment by slnn** [comment]
Done, please see https://github.com/liferay-core-infra/liferay-portal/pull/4366

**Pull request closed without merging**
