### PR TITLE
LPS-164866 Remove_commerce_enterprise_support_in_dxp

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@jeffwu0724 

```
   [echo] diff --git a/modules/dxp/apps/commerce-punchout/headless/headless-commerce-punchout-impl/src/main/java/com/liferay/headless/commerce/punchout/internal/jaxrs/application/HeadlessCommercePunchOutApplication.java b/modules/dxp/apps/commerce-punchout/headless/headless-commerce-punchout-impl/src/main/java/com/liferay/headless/commerce/punchout/internal/jaxrs/application/HeadlessCommercePunchOutApplication.java
     [echo] index b0ce661ac91f..46ac1618ef60 100644
     [echo] --- a/modules/dxp/apps/commerce-punchout/headless/headless-commerce-punchout-impl/src/main/java/com/liferay/headless/commerce/punchout/internal/jaxrs/application/HeadlessCommercePunchOutApplication.java
     [echo] +++ b/modules/dxp/apps/commerce-punchout/headless/headless-commerce-punchout-impl/src/main/java/com/liferay/headless/commerce/punchout/internal/jaxrs/application/HeadlessCommercePunchOutApplication.java
     [echo] @@ -25,7 +25,6 @@ import org.osgi.service.component.annotations.Component;
     [echo]   * @generated
     [echo]   */
     [echo]  @Component(
     [echo] -
     [echo]  	property = {
     [echo]  		"liferay.jackson=false",
     [echo]  		"osgi.jaxrs.application.base=/headless-commerce-punchout",
     [echo] diff --git a/modules/dxp/apps/commerce-punchout/headless/headless-commerce-punchout-impl/src/main/java/com/liferay/headless/commerce/punchout/internal/resource/v1_0/OpenAPIResourceImpl.java b/modules/dxp/apps/commerce-punchout/headless/headless-commerce-punchout-impl/src/main/java/com/liferay/headless/commerce/punchout/internal/resource/v1_0/OpenAPIResourceImpl.java
     [echo] index 5101a442f3d4..05a575c65d39 100644
     [echo] --- a/modules/dxp/apps/commerce-punchout/headless/headless-commerce-punchout-impl/src/main/java/com/liferay/headless/commerce/punchout/internal/resource/v1_0/OpenAPIResourceImpl.java
     [echo] +++ b/modules/dxp/apps/commerce-punchout/headless/headless-commerce-punchout-impl/src/main/java/com/liferay/headless/commerce/punchout/internal/resource/v1_0/OpenAPIResourceImpl.java
     [echo] @@ -46,7 +46,6 @@ import org.osgi.service.component.annotations.Reference;
     [echo]   * @generated
     [echo]   */
     [echo]  @Component(
     [echo] -
     [echo]  	properties = "OSGI-INF/liferay/rest/v1_0/openapi.properties",
     [echo]  	service = OpenAPIResourceImpl.class
     [echo]  )
     [echo] diff --git a/modules/dxp/apps/commerce/headless/headless-commerce-machine-learning-impl/src/main/java/com/liferay/headless/commerce/machine/learning/internal/graphql/servlet/v1_0/ServletDataImpl.java b/modules/dxp/apps/commerce/headless/headless-commerce-machine-learning-impl/src/main/java/com/liferay/headless/commerce/machine/learning/internal/graphql/servlet/v1_0/ServletDataImpl.java
     [echo] index 9c587fa0ce7c..67ac7c0809e2 100644
     [echo] --- a/modules/dxp/apps/commerce/headless/headless-commerce-machine-learning-impl/src/main/java/com/liferay/headless/commerce/machine/learning/internal/graphql/servlet/v1_0/ServletDataImpl.java
     [echo] +++ b/modules/dxp/apps/commerce/headless/headless-commerce-machine-learning-impl/src/main/java/com/liferay/headless/commerce/machine/learning/internal/graphql/servlet/v1_0/ServletDataImpl.java
     [echo] @@ -34,7 +34,7 @@ import org.osgi.service.component.annotations.ReferenceScope;
     [echo]   * @author Riccardo Ferrari
     [echo]   * @generated
     [echo]   */
     [echo] -@Component( immediate = true, service = ServletData.class)
     [echo] +@Component(immediate = true, service = ServletData.class)
     [echo]  @Generated("")
     [echo]  public class ServletDataImpl implements ServletData {
     [echo]  
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-25/test-portal-acceptance-pullrequest(master)/4975/rest-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@jeffwu0724 results look good. Rebase, please. 

Thanks

**Comment by jeffwu0724** [comment]
fixed the code conflict

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:commerce

**Comment by jeffwu0724** [comment]
ci:test:commerce

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
fixed the code conflict and forced pushed

**Comment by jeffwu0724** [comment]
fixed the code conflict and forced pushed

**Comment by jeffwu0724** [comment]
Hi @zhangyan0701 , could you please help me to scan the result?
Thanks!

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by jeffwu0724** [comment]
fixed the code conflict and forced pushed

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:commerce

**Comment by jeffwu0724** [comment]
Hi @zhangyan0701 , could you please help me to scan the result again?
Thanks!

**Comment by kyle-miho** [comment]
PR should be good to go, no unqiue failures found

**Comment by jeffwu0724** [comment]
fixed the code conflict in bnd.bnd

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125090

**Pull request closed without merging**
