### PR TITLE
[Remove Stream/Optional usage] LPS-176939 module: segments-context-vocabulary

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-176939
resend, Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3701

Changes in this pull:
• Make class `BaseConfigurationListener` abstract.
• Add `-annotations-options: inherit` to bnd file.
• Add reference annotation to field `configurationAdmin` and make it protected.
• Add abstract method `getConfigurationClass()` and override it in subclasses.

Thanks!

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:tango

**Comment by JanisZhang** [comment]
re trigger ci:test:tango...

**Comment by JanisZhang** [comment]
ci:test:tango

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:tango

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
@JanisZhang bnd conflict, please resend.

**Pull request closed without merging**
