### PR TITLE
[1/2] LPS-145396 When we delete some types of objects in Liferay, we are not deleting their ResourcePermission records

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
[1/2] When we delete some types of objects in Liferay, we are not deleting their ResourcePermission records, leaving some orphan data in the ResourcePermission table.

@tinatian this PR contains the corrections for the core team components (ListTypeDefinition, ExpandoColumn)

The corrections for non-core components were sent to the corresponding teams (see https://github.com/liferay-lima/liferay-portal/pull/2796 , https://github.com/liferay-zulu/liferay-portal/pull/35 , https://github.com/liferay-appsec/liferay-portal/pull/580 , https://github.com/liferay-staging/liferay-portal/pull/37 , https://github.com/liferay-echo/liferay-portal/pull/7430 , https://github.com/liferay-commerce/liferay-portal/pull/2325 , https://github.com/liferay-usm/liferay-portal/pull/475 , https://github.com/liferay-lima/liferay-portal/pull/2816 , https://github.com/liferay-tango/liferay-portal/pull/2273 , https://github.com/liferay-echo/liferay-portal/pull/7470 , https://github.com/liferay-forms/liferay-portal/pull/1524)

I am sending the test code added to the DataGuardTestRuleUtil class in a separate PR, see https://github.com/liferay-core-infra/liferay-portal/pull/458

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@tinatian Failures here not related.

**Comment by vicnate5** [comment]
We can let the relevant re-run since a bunch of tests didn't execute

**Comment by jorgediaz-lr** [comment]
ci:test:acceptance

**Pull request closed without merging**
