### PR TITLE
[TS] LPD-31842

### PR DESCRIPTION
**Pull request by dantewang**
https://liferay.atlassian.net/browse/LPD-31842

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:test:search

**Comment by dantewang** [comment]
ci:report:41060219

**Comment by tinatian** [comment]
ci:report:41060335

**Comment by dantewang** [comment]
ci:report:41060335

**Comment by dantewang** [comment]
ci:report:41060219

**Comment by dantewang** [comment]
ci:test:search

**Comment by dantewang** [comment]
ci:report:42727868

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:search

**Comment by dantewang** [comment]
ci:report:42939618

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 42939618.
> 
> Job Link: [generate-testray-csv](https://test-1-31.liferay.com/job/generate-testray-csv/103/)
> 
> Testray CSV Link: [testray-results-42939618.csv](https://test-1-31.liferay.com/userContent/jobs/generate-testray-csv/builds/103/testray-results-42939618.csv)

@lipusz The [unique failure](https://testray.liferay.com/#/project/34754/routines/34756/build/42939618/case-result/42946193/history) of `com.liferay.search.experiences.internal.blueprint.test.SXPBlueprintSearchResultTest`  are marked by the ci-report as unique, but the history shows a lot of failures with similar message in other runs. Could search team take a look? Thanks!

**Comment by dantewang** [comment]
ci:report:42950807

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 42950807.
> 
> Job Link: [generate-testray-csv](https://test-1-40.liferay.com/job/generate-testray-csv/393/)
> 
> Testray CSV Link: [testray-results-42950807.csv](https://test-1-40.liferay.com/userContent/jobs/generate-testray-csv/builds/393/testray-results-42950807.csv)

No unique failure. The 2 "unique" ones also fail with same errors on lots of other runs.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7278

**Pull request closed without merging**
