### PR TITLE
[Login-performance-tuning]  LPS-149260

### PR DESCRIPTION
**Pull request by yuhai**
@tinatian, @dantewang, please check the performance test result from https://github.com/GinsonRen/liferay-portal/pull/583#issuecomment-1064709847

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@zhangyan0701 Can you check this one?

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114879

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
