### PR TITLE
LPS-169043 move_commons-collections4_to_shared-dependencies

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Fixed the bug mentioned https://github.com/liferay-core-infra/liferay-portal/pull/2584#issuecomment-1341093610 and https://github.com/liferay-core-infra/liferay-portal/pull/2662#issuecomment-1343180593
Change the commit order as well as the commit message to make it clear, based on https://github.com/liferay-core-infra/liferay-portal/pull/2511
I am trying to move commons-collections4 to shared-dependencies because we already have a shared-dependencies for org.apache.commons.
Thanks for checking!

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@jeffwu0724 rebase, please. To check if SF issue was resolved.
Thanks, Cat

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
rebase and resend, test the sf again

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar ,

I have rebased but seems like this sf issue is not fixed yet. It is the issue in " ./workspaces/sample-minimal-workspace".
I run "ant format-source-current-branch" locally, and it is successful. 
Thanks for checking.

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions.

**Comment by jeffwu0724** [comment]
fixed the code conflict in versions.html by auto-generate, the old test result should be still good

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127873

**Pull request closed without merging**
