### PR TITLE
[Components with more than 1 service] LPS-184035, LPS-183929 Refactor Export-Import and Document Library components

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-184035](https://issues.liferay.com/browse/LPS-184035),
[LPS-183929](https://issues.liferay.com/browse/LPS-183929)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:document

**Comment by RenanUmV** [comment]
ci:test:dl-store

**Comment by RenanUmV** [comment]
ci:test:export-import

**Comment by RenanUmV** [comment]
ci:test:blogs

**Comment by Kvale1733** [comment]
@RenanUmV No regressions found.

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
Just  change the commit message

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:stable

**Comment by rafaprax** [comment]
ci:forward:force

/cc @dantewang @tinatian @shuyangzhou

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136531

**Pull request closed without merging**
