### PR TITLE
[Replace Non-Blocking Usage] LPS-197546 Replace non-blocking ServiceProxyFactory usages in classes FacebookConnectUtil, WebLogicIncludeFilter and LanguageResources

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:stop

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@W2jx There is a startup issue affecting all tests
```
[beanshell] 2023-10-05 09:52:44.925 ERROR [main][MainServlet:372] null
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.portal.kernel.module.service.Snapshot.lambda$null$2(Snapshot.java:114) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.petra.concurrent.DCLSingleton.getSingleton(DCLSingleton.java:39) ~[com.liferay.petra.concurrent.jar:?]
[beanshell] 	at com.liferay.portal.kernel.module.service.Snapshot.lambda$new$3(Snapshot.java:110) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.module.service.Snapshot.get(Snapshot.java:159) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.language.LanguageResources._getOverrideResourceBundle(LanguageResources.java:167) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.language.LanguageResources.getMessage(LanguageResources.java:56) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.language.LanguageImpl.get(LanguageImpl.java:949) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.language.LanguageImpl.get(LanguageImpl.java:926) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.language.LanguageUtil.get(LanguageUtil.java:180) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.security.auth.FullNameDefinitionFactory._getRequiredFieldNames(FullNameDefinitionFactory.java:95) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.security.auth.FullNameDefinitionFactory._getInstance(FullNameDefinitionFactory.java:68) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.security.auth.FullNameDefinitionFactory.getInstance(FullNameDefinitionFactory.java:24) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.security.auth.DefaultFullNameGenerator.buildLocalizedFullName(DefaultFullNameGenerator.java:212) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.security.auth.DefaultFullNameGenerator.getLocalizedFullName(DefaultFullNameGenerator.java:57) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.model.impl.UserImpl.getFullName(UserImpl.java:363) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.model.impl.UserImpl.getFullName(UserImpl.java:329) ~[portal-impl.jar:?]
[beanshell] 2023-10-05 09:52:44.925 ERROR [main][MainServlet:372] null
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.portal.kernel.module.service.Snapshot.lambda$null$2(Snapshot.java:114) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.petra.concurrent.DCLSingleton.getSingleton(DCLSingleton.java:39) ~[com.liferay.petra.concurrent.jar:?]
[beanshell] 	at com.liferay.portal.kernel.module.service.Snapshot.lambda$new$3(Snapshot.java:110) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.module.service.Snapshot.get(Snapshot.java:159) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.language.LanguageResources._getOverrideResourceBundle(LanguageResources.java:167) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.language.LanguageResources.getMessage(LanguageResources.java:56) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.language.LanguageImpl.get(LanguageImpl.java:949) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.language.LanguageImpl.get(LanguageImpl.java:926) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.language.LanguageUtil.get(LanguageUtil.java:180) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.security.auth.FullNameDefinitionFactory._getRequiredFieldNames(FullNameDefinitionFactory.java:95) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.security.auth.FullNameDefinitionFactory._getInstance(FullNameDefinitionFactory.java:68) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.security.auth.FullNameDefinitionFactory.getInstance(FullNameDefinitionFactory.java:24) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.security.auth.DefaultFullNameGenerator.buildLocalizedFullName(DefaultFullNameGenerator.java:212) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.security.auth.DefaultFullNameGenerator.getLocalizedFullName(DefaultFullNameGenerator.java:57) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.model.impl.UserImpl.getFullName(UserImpl.java:363) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.model.impl.UserImpl.getFullName(UserImpl.java:329) ~[portal-impl.jar:?

```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-40/test-portal-acceptance-pullrequest(master)/6512/functional-smoke-tomcat90-hypersonic20-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
