### PR TITLE
LPS-186928

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:ldap

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by marianoalvarosaiz** [comment]
@tinatian I understand the problem with LDAP, but same thing happens with CheckArticle. So in the end, we have simplified the scheduler framework and we have switch from a schedulerEngineHelper.register/schedulerEngineHelper.unregister to the code needed for c8534cc

Besides design in LDAP Import and CheckArticles could be different, we have ended with a simplification in the scheduler framework that changes a single line call to an API (register/unregister), to the need to manage the configuration in the invoker side. I think it should be managed in the framework, if not it is a step backwards in the framework usability. It has already affected us breaking LDAP import and CheckArticles configuration changes and it can also afect customers.

**Comment by marianoalvarosaiz** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4889

**Pull request closed without merging**
