### PR TITLE
[Method References 2] LPS-165167 Convert method reference to ServiceTrackerList in module portal-search-similar-results-web(dxp)

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I convert method reference to ServiceTrackerList in module portal-search-similar-results-web(dxp).

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
Force-Push is just to replace the BundleContext used in SimilarResultsUidsAndDestinationsTest.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@W2jx Please resend as we talked.

**Pull request closed without merging**
