### PR TITLE
LPS-185775 Convert the Optional references to static references using…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-185775

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
ci:test:osb-site-initializer-customer-portal

**Comment by Kvale1733** [comment]
@slnn No regressions.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
