### PR TITLE
[Remove unused @Reference var] LPS-164877

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove the unused @reference variable in the module `commerce-checkout-web`. Thanks!

https://issues.liferay.com/browse/LPS-164877

### CODE REVIEW

**Comment by JanisZhang** [comment]
Force-pushed, I only changed the commit message, it shouldn't affect test results. Thanks.

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/124397

**Pull request closed without merging**
