### PR TITLE
Lps 179797

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
PortalConfigurationUpgrade testcase was moved to Core team and it no longer runs under usm suite. Will resend with CI changes so this runs on relevant and upgrades suite.

**Comment by Kvale1733** [comment]
ci:close

**Comment by Kvale1733** [comment]
See: https://github.com/liferay-core-infra/liferay-portal/pull/4089

**Pull request closed without merging**
