### PR TITLE
LPS-172408 Remove "immediate = true" from last USM modules

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:usm

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Comment by MrJohn1911** [comment]
Hey @shuyangzhou this one is ready to go.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128945

**Pull request closed without merging**
