### PR TITLE
LPS-143632 Remove LanguageUtil from moduels part 3b mixed

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@catarineaguiar 
Hi Catarine, 
Could you pelase help me review this test result?
Thank you!

CC. @tinatian

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by tinatian** [comment]
@julschong Please rebase.

Tina

**Comment by julschong** [comment]
rebased to resolve conflict (files were removed)

> modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/internal/data/set/ClayDataSetDisplayViewSerializerImpl.java
> modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/internal/data/set/filter/AutocompleteClayDataSetFilterContextContributor.java
> modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/internal/data/set/filter/CheckBoxClayDataSetFilterContextContributor.java
> modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/internal/data/set/filter/ClayDataSetFilterSerializerImpl.java

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/120826

**Pull request closed without merging**
