### PR TITLE
LPS-171810 Cleanup portal-template-soy-renderer releng

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by tinatian** [comment]
@julschong Ticket number in commit message is wrong, please update.

Thanks.
Tina

**Comment by julschong** [comment]
corrected commit message ticket number

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128313

**Pull request closed without merging**
