### PR TITLE
LPD-36036 11-14

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
No need to run app-servers.

**Comment by dantewang** [comment]
ci:test:frontend

**Comment by shuyangzhou** [comment]
This can be forwarded if CI results are clean.

**Comment by dantewang** [comment]
ci:report:68436510

**Comment by dantewang** [comment]
ci:report:68552712

**Comment by dantewang** [comment]
No unique failure on frontend.

**Comment by dantewang** [comment]
ci:reevaluate:1327401_5558

**Comment by dantewang** [comment]
ci:report:68552712

**Comment by dantewang** [comment]
Cross checked the relevant result in this PR and https://github.com/liferay-core-infra/liferay-portal/pull/7632, the only ones appearing in the unique failures section in both results are actually also happening on upstream.

- PortalLogAssertorTest-modules-integration-mysql57/2/20 (DuplicateOrganizationException caused by ObjectActionLocalServiceTest)
- com.liferay.headless.batch.engine.resource.v1_0.test.ExportTaskResourceTest

com.liferay.commerce.pricing.test.CommercePriceModifierTest failed only in this run; it passed when I run with this PR locally.

Other test failures are from flaky tests or CI timeout, which didn't happen in the #7632 run.

**Based on these findings, no regression in relevant.**

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:69313474

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 69313474.
> 
> Job Link: [generate-testray-csv](https://test-1-32.liferay.com/job/generate-testray-csv/298/)
> 
> Testray CSV Link: [testray-results-69313474.csv](https://test-1-32.liferay.com/userContent/jobs/generate-testray-csv/builds/298/testray-results-69313474.csv)

No unique failure.

**Comment by dantewang** [comment]
ci:forward:force

As per https://github.com/liferay-core-infra/liferay-portal/pull/7639#issuecomment-2476640921, forwarding.

cc @shuyangzhou @tinatian

**Pull request closed without merging**
