### PR TITLE
[LPD-40485 Ehcache] LPD-43561 Remove unused test config files

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:84351655

**Comment by dantewang** [comment]
The failure in relevant is happening on almost all PRs, it's not unique.

**Comment by tinatian** [comment]
ci:forward:force

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7708

**Pull request closed without merging**
