### PR TITLE
[Remove Immediate] LPS-188559 Remove immediate property from DLProcessorRegistryImpl

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-188559

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:document

**Comment by Kvale1733** [comment]
ci:test:document

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by tinatian** [comment]
@rafaprax Please see my message on slack, please resend.

Thanks.
Tina

**Pull request closed without merging**
