### PR TITLE
[Method References 2] LPS-165277 DDMFormInstanceRecordWriterRegistryImpl 

### PR DESCRIPTION
**Pull request by JanisZhang**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/2522

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by dantewang** [comment]
@JanisZhang Please update the commit message of https://github.com/liferay-core-infra/liferay-portal/pull/2545/commits/d5b77791e381b613a51ad4f54685651bba9affdf to also clarify that the map value are upper case because they are displayed on the UI.

**Review by dantewang — APPROVED** [review]

**Comment by JanisZhang** [comment]
Force-pushed, I only changed the commit message. cc @catarineaguiar

**Comment by tinatian** [comment]
@JanisZhang @dantewang For this https://github.com/liferay-core-infra/liferay-portal/pull/2545/commits/d4aaed957ce74005eaa0a0808075f61881d9318b, can we make the react not ask for a map? or in other workds, modify react logic to accept a set rather than map. 

It looks so weird to have map and populate its value using keys uppercase.


Tina.

**Comment by JanisZhang** [comment]
WIP. Will resend

**Pull request closed without merging**
