### PR TITLE
LPD-41231 Update core entries in CODEOWNERS

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
rebased

**Comment by tinatian** [comment]
FYI @vicnate5

**Comment by tinatian** [comment]
ci:forward

**Comment by julschong** [comment]
ci:forward:force

**Comment by vicnate5** [comment]
looks good

**Comment by julschong** [comment]
conflict on brian's

**Comment by julschong** [comment]
rebased to brian's
see https://github.com/brianchandotcom/liferay-portal/pull/155897

**Pull request closed without merging**
