### PR TITLE
[SF] LPS-175351 Verify `configurationPid` in `@Component` annotations

### PR DESCRIPTION
**Pull request by kevhlee**
Closes: <https://issues.liferay.com/browse/LPS-175351>

This pull request expands `JavaComponentAnnotationsCheck` to ensure configuration classes listed in `configurationPid` are valid. For the files that offended this rule, I either removed the configuration classes, if they no longer exist, or updated them, if they were simply moved.

Let me know if I need to make any changes.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:close

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
The SF errors are unrelated. Please check just the `ci:test:relevant` tests.

**Comment by Kvale1733** [comment]
No regressions found.

**Comment by tinatian** [comment]
@kevhlee Code conflicts, please rebase.

Thanks.
Tina

**Comment by tinatian** [comment]
@kevhlee Please rebase.

Thanks.
Tina

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133043

**Pull request closed without merging**
