### PR TITLE
LPS-158153 Add new functionality to SystemProperties: get property with default value, and get array

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I added two new methods to SystemProperties.java and added related unit tests.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me scan test results when you free ? Thanks!

**Comment by dantewang** [comment]
@W2jx See https://github.com/liferay-core-infra/liferay-portal/pull/1100

**Comment by dantewang** [comment]
@W2jx Specifically, see https://github.com/liferay-core-infra/liferay-portal/pull/1100/commits/12c59fbdcfdf719309dfb6e830fdd44e39e687c6. On my laptop I got test failure due to leftover property in `System.props`.

**Comment by W2jx** [comment]
@dantewang When I was dealing with task LPS-154947, I worried about the similar problem, so I used the name of key with a different prefix to achieve the effect of data isolation. But since I've never seen a similar problem, I've simplified the name of the key.

**Pull request closed without merging**
