### PR TITLE
[Method References 2] LPS-171460 Convert method reference to ServiceTracker in class PortalInstanceLifecycleListenerManagerImpl(module portal-instance-lifecycle-impl)

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(12/21 17:05)

**Comment by W2jx** [comment]
no conflicts(12/27 9:31)

**Comment by yuhai** [comment]
@W2jx, after we talk, you will resend it.

**Pull request closed without merging**
