### PR TITLE
[Bug fix] LPS-144694

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian I found this bug when trying to run xml related unit test under JDK 11. CI does not run unit tests for JDK 11, I think this is why it's not found by others since 2019.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 I don't think this change will affect any CI test, but could you double check the testing results? Thanks!

**Comment by zhangyan0701** [comment]
@dantewang

No related failures.

**Comment by tinatian** [comment]
@vicnate5 Could you please add a test batch for JDK11 to Ci?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian I am having issues getting the CI to run the tests on JDK11, so the testing for this is still in progress.

**Comment by tinatian** [comment]
Thanks @vicnate5 for the update, as this is not urgent, I would like to wait for the test ready.

Tina.

**Comment by vicnate5** [comment]
@tinatian How many of our tests do you want to run on JDK11? Portal Unit tests? Modules Unit tests? Modules Integration tests?

We originally added this logic to change the JDK for the test JVM, but never actually enabled it. For our CI JDK11 testing, we are using JDK11 for the Portal JVM, but the test runtime JVM is still on JDK8 to avoid any possible compile issues. We do not currently have the requirement that tests must compile on JDK11 (just like we do not compile Portal on JDK11).

**Comment by dantewang** [comment]
@tinatian @vicnate5 As far as I remember we didn't fix all the compatibility issues in portal unit tests with JDK11. Maybe that's the reason why CI doesn't run unit test for JDK11. For example, `NewEnv.JVM` for `NewEnvTestRule`.

**Comment by vicnate5** [comment]
lots of failures when I ran the portal unit tests on JDK11
https://testray.liferay.com/reports/production/logs/2022-01/test-1-25/test-portal-acceptance-pullrequest(master)/1304/unit-jdk11_open/0/0/jenkins-console.txt.gz

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.
Before fix, no unit test can be run on JDK11.
After fix, unit tests can run on JDK11, but some of them failed because they are using something not compatible with JDK11, for example AspectJ and Powermoke, based on @vicnate5 's comment, `we do not currently have the requirement that tests must compile on JDK11`, I will leave the failed unit test not fixed.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
