### PR TITLE
[CLDR] LPD-19263 Fix DateDDMFormFieldValueRendererTest

### PR DESCRIPTION
**Pull request by MrJohn1911**
Hey @tinatian, I couldn't fix this in production code because the code that generates this date and time format is from JDK, you can see it here:

```
LocalDateTime localDateTime = DateParameterUtil.getLocalDateTime(
   valueString);

return localDateTime.format(
   dateTimeFormatter.withDecimalStyle(DecimalStyle.of(locale)));
```

for more details, please see the `com.liferay.dynamic.data.mapping.form.field.type.internal.date.DateDDMFormFieldValueRenderer` class, the `_render` method shows how the Date and Time are formatted according to the Locale.

BTW, this fix is temporary, since liferay will migrate to JDK 21 with CLDR, and this changes (verify the JDK version and the CLDR property) won't be necessary after that.

### CODE REVIEW

**Comment by julschong** [comment]
@MrJohn1911 Hi Joao, I tested with jdk8 and CLDR locally and found some errors in the test. could you please take a look?
Thanks

**Comment by MrJohn1911** [comment]
> @MrJohn1911 Hi Joao, I tested with jdk8 and CLDR locally and found some errors in the test. could you please take a look? Thanks

Of course!

**Comment by MrJohn1911** [comment]
ci:test:forms

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
see https://github.com/liferay-core-infra/liferay-portal/pull/6837

**Pull request closed without merging**
