### PR TITLE
[DL tuning] LPS-153711 make jsp as jspf

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, @slnn

### CODE REVIEW

**Comment by yuhai** [comment]
@zhangyan0701, please help scan the test result. Thanks.

**Comment by zhangyan0701** [comment]
ci:test:document

**Comment by tinatian** [comment]
@zhangyan0701 Please help scan test results.

Thanks.
Tina

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/117679

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
