### PR TITLE
[New Env] LPD-31739 NewEnv should follow current environment's java locale providers settings

### PR DESCRIPTION
**Pull request by julschong**
@tinatian resubmitted from https://github.com/liferay-core-infra/liferay-portal/pull/7256/commits/79e4e1420518422a86f263f1604a77078ca90232

Added unit test on first commit to expose the issue

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:40364313

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 40364313.
> 
> Job Link: [generate-testray-csv](https://test-1-39.liferay.com/job/generate-testray-csv/325/)
> 
> Testray CSV Link: [testray-results-40364313.csv](https://test-1-39.liferay.com/userContent/jobs/generate-testray-csv/builds/325/testray-results-40364313.csv)

Unique failures in report are not unique to this pull

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/152464

**Pull request closed without merging**
