### PR TITLE
[Components with more than 1 service] LPS-183224 Refactor PortletProvider implementations from Commerce

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-183224

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
@rafaprax functional tests failed due to:

signin button is not present:
image

no failures in the logs.

Semver error:
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/layout/layout-api] FAILED
     [exec]     java.lang.AssertionError: [Baseline Warning] Bundle Version Change Recommended: 32.1.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-05/test-1-40/test-portal-acceptance-pullrequest(master)/2409/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.bookmarks.social.test.BookmarksEntryActivityInterpreterTest > testActivityInterpreter STARTED
[beanshell] 2023-05-17 20:31:11.073 ERROR [com.liferay.bookmarks.test-executor-thread][BaseSocialActivityInterpreter:88] Unable to interpret activity
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.portal.kernel.portlet.url.builder.PortletURLBuilder$PortletURLStep._setParameter(PortletURLBuilder.java:591) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.portlet.url.builder.PortletURLBuilder$PortletURLStep.setMVCPath(PortletURLBuilder.java:359) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.trash.internal.TrashHelperImpl.getViewContentURL(TrashHelperImpl.java:223) ~[?:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-05/test-1-40/test-portal-acceptance-pullrequest(master)/2409/modules-integration-mysql57-jdk8/0/12/jenkins-console.txt.gz?authuser=0)

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:commerce

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
ci:test:echo

**Comment by zhangyan0701** [comment]
ci:test:data-engine

**Comment by zhangyan0701** [comment]
Issues found:
1. User does not receive notifications after another user adding a MB thread in subscribed MB category.
Steps:

- Go to Content & Data > Message Boards, add a Category.
- Subscribe the Category (clicking the ellipsis icon and select Subscribe).
- Go to Control Panel > Users and Organizations.
- Add a new user, assign Administrator role to user.
- Login as the new user, go to Content & Data > Message Boards, go into the Category and add a new Thread.
- Login out and login as Test user again.

Result:
There is no notification count should display next to the user avatar. Click user avatar and go to Notifications, assert that no notifications.

2. Some integration tests failed.
[com.liferay.message.boards.notifications.test.MBUserNotificationTest](https://testray.liferay.com/home/-/testray/case_results/2318945017)
[com.liferay.document.library.notifications.test.DocumentLibraryUserNotificationTest](https://testray.liferay.com/home/-/testray/case_results/2318944472)
[com.liferay.blogs.notifications.test.BlogsUserNotificationTest](https://testray.liferay.com/home/-/testray/case_results/2318944028)

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:commerce

**Comment by rafaprax** [comment]
ci:test:blogs

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:echo

**Comment by rafaprax** [comment]
ci:test:data-engine

**Comment by zhangyan0701** [comment]
Issue found:
**Related assets don't display in Web Content Display.**

https://github.com/liferay-core-infra/liferay-portal/assets/25576873/82215d7a-e9e2-452d-82d7-91b8bf76a329

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-core-infra/liferay-portal/pull/4705

**Pull request closed without merging**
