### PR TITLE
[FP5 Bug]LPS-151272 Unregister services correctly on stop.

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/617

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
