### PR TITLE
LPD-17388 Fix NewEnv test Rule behavior after using the ClassLoader#getSystemClassLoader as parent classLoader

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://liferay.atlassian.net/browse/LPD-17388

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @tinatian, this change fix:

- com.liferay.portal.proxy.internal.ASMDelegateProxyFactoryTest
- com.liferay.portal.template.freemarker.internal.RestrictedLiferayObjectWrapperTest
- com.liferay.portal.kernel.util.CollatorUtilTest
- com.liferay.portal.kernel.test.rule.NewEnvClassLoaderTestRuleTest
- com.liferay.petra.string.StringBundlerTest
- com.liferay.petra.io.SerializerTest

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by tinatian** [comment]
Passed review @rafaprax please forward to BChan 

Thanks.
Tina

**Comment by rafaprax** [comment]
forwarded https://github.com/brianchandotcom/liferay-portal/pull/147088

**Pull request closed without merging**
