### PR TITLE
remove_deprecated_part_8_portal_impl_fixed_test

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Fixed error mentioned in https://github.com/liferay-core-infra/liferay-portal/pull/698
This is remove_deprecated_part_8_portal_impl
Thanks for checking. Also see https://github.com/jeffwu0724/liferay-portal/pull/63 and https://github.com/jeffwu0724/liferay-portal/pull/64

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Please help me scan test results.

Thanks
Jeff

**Comment by catarineaguiar** [comment]
Hi @jeffwu0724 sorry the delay, no regressions were found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116940

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
