### PR TITLE
[OrderByComparator] LPD-26681 Clean up and Apply Singleton in module bookmarks-api 

### PR DESCRIPTION
**Pull request by Valmir-unicap**
- Ticket: https://liferay.atlassian.net/browse/LPD-26681

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@Valmir-unicap Do we need to update replacement.json and the SF tests for this PR as well?

**Comment by Valmir-unicap** [comment]
As @titokenzo  said, we'll do it at the end, since they all change the same file.

**Comment by Valmir-unicap** [comment]
Reevaluating!
CC: @titokenzo

**Pull request closed without merging**
