### PR TITLE
[Blocker] LPS-191344 fix: The portal cannot get user data after authorizing new OAuth2

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-191344](https://liferay.atlassian.net/browse/LPS-191344)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:security

**Comment by RenanUmV** [comment]
ci:test:oauth2

**Comment by JoyceWang08211** [comment]
> **Jenkins Build:**[test-portal-acceptance-pullrequest(master)#13329](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/13329/)
> **Jenkins Report:**[jenkins-report.html](https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/13329/jenkins-report.html)
> **Jenkins Suite:**oauth2
> **Pull Request:**[liferay-core-infra#5068](https://github.com/liferay-core-infra/liferay-portal/pull/5068)
> **Testray Routine:**[EE Pull Request](https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894)
> **Testray Build:**[[master] ci:test:oauth2 - RenanUmV > liferay-core-infra - PR#5068 - 2023-07-21[18:34:20]](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2392201758)
> **Testray Importer:**[publish-testray-report#28876](https://test-1-37.liferay.com/job/publish-testray-report/28876/)

No regression was found for OAuth2 part.

**Comment by dantewang** [comment]
@JoyceWang08211 @zhangyan0701 Is the issue reported in LPS-191344 covered in these tests and passed?

**Comment by zhangyan0701** [comment]
> Is the issue reported in LPS-191344 covered in these tests and passed?

Yes, the test that caught this issue passed here.

**Comment by dantewang** [comment]
@zhangyan0701 Thanks!
Any idea why did it pass the original check before sending to Brian? After getting QA Passed in https://github.com/liferay-core-infra/liferay-portal/pull/5020 I just rebased and forwarded the PR manually.

**Comment by zhangyan0701** [comment]
> @zhangyan0701 Thanks! Any idea why did it pass the original check before sending to Brian? After getting QA Passed in #5020 I just rebased and forwarded the PR manually.

The test also failed in the original PR, but the same error happened several times before in different PRs according to the test history. That confused me so that I thought it was a flaky, but the issues were actually different even though the error was same. It would be better if I could click into the Test Report and check the details.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Comment by JoyceWang08211** [comment]
ci:forward:force

**Pull request closed without merging**
