### PR TITLE
[Service Builder Soap]LPS-145347

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.


Thanks.
Tina.

**Comment by vicnate5** [comment]
@koor4356 Can you take a look at this one? The results took too long to come in, so note the dates on the results. Since something went wrong with CI, is there anything missing in the results?

**Comment by koor4356** [comment]
Okay, thanks

**Comment by koor4356** [comment]
@tinatian 
Can take a look into the "modules-compile-jdk8 and modules-semantic-versioning-jdk8" batches? They have a lot of errors thrown. I am not sure if they are related to this PR.

**modules-compile-jdk8**
`java.lang.ClassNotFoundException: com.liferay.portal.workflow.kaleo.forms.service.http.KaleoProcessServiceSoap
     [exec]   	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
     [exec]   	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [exec]   	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
     [exec]   	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [exec]   	at org.apache.tools.ant.AntClassLoader.findBaseClass(AntClassLoader.java:1405)
     [exec]   	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1102)
     [exec]   	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [exec]   	at org.apache.axis.utils.ClassUtils$2.run(ClassUtils.java:187)
     [exec]   	at java.security.AccessController.doPrivileged(Native Method)
     [exec]   	at org.apache.axis.utils.ClassUtils.loadClass(ClassUtils.java:160)
     [exec]   	at org.apache.axis.utils.ClassUtils.forName(ClassUtils.java:100)
     [exec]   	at org.apache.axis.wsdl.fromJava.Emitter.setCls(Emitter.java:2079)
     [exec]   	at org.apache.axis.tools.ant.wsdl.Java2WsdlAntTask.execute(Java2WsdlAntTask.java:188)
     [exec]   	at com.liferay.util.ant.Java2WsddTask.generateWsdd(Java2WsddTask.java:112)
     [exec]   	at com.liferay.portal.tools.wsdd.builder.WSDDBuilder._createServiceWSDD(WSDDBuilder.java:159)
     [exec]   	at com.liferay.portal.tools.wsdd.builder.WSDDBuilder.build(WSDDBuilder.java:117)
     [exec]   	at com.liferay.portal.tools.wsdd.builder.WSDDBuilder.main(WSDDBuilder.java:62)`

`Task :dxp:apps:search-experiences:search-experiences-service:compileJava
     [exec]   java.lang.ClassNotFoundException: com.liferay.search.experiences.service.http.SXPBlueprintServiceSoap
     [exec]   	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
     [exec]   	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [exec]   	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
     [exec]   	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [exec]   	at org.apache.tools.ant.AntClassLoader.findBaseClass(AntClassLoader.java:1405)
     [exec]   	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1102)
     [exec]   	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [exec]   	at org.apache.axis.utils.ClassUtils$2.run(ClassUtils.java:187)
     [exec]   	at java.security.AccessController.doPrivileged(Native Method)
     [exec]   	at org.apache.axis.utils.ClassUtils.loadClass(ClassUtils.java:160)
     [exec]   	at org.apache.axis.utils.ClassUtils.forName(ClassUtils.java:100)
     [exec]   	at org.apache.axis.wsdl.fromJava.Emitter.setCls(Emitter.java:2079)
     [exec]   	at org.apache.axis.tools.ant.wsdl.Java2WsdlAntTask.execute(Java2WsdlAntTask.java:188)
     [exec]   	at com.liferay.util.ant.Java2WsddTask.generateWsdd(Java2WsddTask.java:112)
     [exec]   	at com.liferay.portal.tools.wsdd.builder.WSDDBuilder._createServiceWSDD(WSDDBuilder.java:159)
     [exec]   	at com.liferay.portal.tools.wsdd.builder.WSDDBuilder.build(WSDDBuilder.java:117)`

https://testray.liferay.com/reports/production/logs/2022-01/test-1-33/test-portal-acceptance-pullrequest(master)/934/modules-compile-jdk8/0/9/jenkins-console.txt.gz

https://testray.liferay.com/home/-/testray/case_results/1606336498

**modules-semantic-versioning-jdk8**

`[Baseline Warning] Bundle Version Change Recommended: 6.0.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertFalse(Assert.java:64)
     [exec]         at com.liferay.semantic.versioning.SemanticVersioningTest.testSemanticVersioning(SemanticVersioningTest.java:82)
     [exec]         at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
     [exec]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
     [exec]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
     [exec]         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
     [exec]         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
     [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
     [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
     [exec]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
     [exec]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
     [exec]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
     [exec]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
     [exec]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
     [exec]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
     [exec]         at org.junit.runners.Suite.runChild(Suite.java:128)
     [exec]         at org.junit.runners.Suite.runChild(Suite.java:27)
     [exec]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
     [exec]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
     [exec]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
     [exec]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
     [exec]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
     [exec]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)`

https://testray.liferay.com/reports/production/logs/2022-01/test-1-33/test-portal-acceptance-pullrequest(master)/934/modules-semantic-versioning-jdk8/0/7/jenkins-console.txt.gz

https://testray.liferay.com/home/-/testray/case_results/1606338497

@vicnate5,
I am not able to find out why the results took 5 days to come in. The results look like nothing is missing but I could be wrong.

**Comment by tinatian** [comment]
Resend at https://github.com/liferay-core-infra/liferay-portal/pull/293

**Pull request closed without merging**
