### PR TITLE
[Components with more than 1 service] LPS-175994 Refactor DTO Converter components with more than 1 service type from Headless

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:headless

**Comment by Kvale1733** [comment]
@MrJohn1911 Regressions found

1) Create User API call returns no response
Steps to reproduce
       1) Execute 
       ```
curl -X POST -H 'accept: application/json' -H 'Content-Type: application/json' -u 'test@liferay.com:test' -d '{"alternateName": "user1","emailAddress": "user1@liferay.com","familyName": "userfn1","givenName": "usergn1"}' http://localhost:8080/o/headless-admin-user/v1.0/user-accounts
        ```
Expected Result: Curl returns something like
```
{
     [exec]       "accountBriefs" : [ ],
     [exec]       "actions" : {
     [exec]         "get-user-account-by-external-reference-code" : {
     [exec]           "method" : "GET",
     [exec]           "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/by-external-reference-code/44315"
     [exec]         },
     [exec]         "put-user-account" : {
     [exec]           "method" : "PUT",
     [exec]           "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/44315"
     [exec]         },
     [exec]         "delete-user-account" : {
     [exec]           "method" : "DELETE",
     [exec]           "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/44315"
     [exec]         },
     [exec]         "get-user-account" : {
     [exec]           "method" : "GET",
     [exec]           "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/44315"
     [exec]         },
     [exec]         "delete-user-account-by-external-reference-code" : {
     [exec]           "method" : "DELETE",
     [exec]           "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/by-external-reference-code/44315"
     [exec]         },
     [exec]         "put-user-account-by-external-reference-code" : {
     [exec]           "method" : "PUT",
     [exec]           "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/by-external-reference-code/44315"
     [exec]         },
     [exec]         "get-my-user-account" : {
     [exec]           "method" : "GET",
     [exec]           "href" : "http://localhost:8080/o/headless-admin-user/v1.0/my-user-account"
     [exec]         },
     [exec]         "patch-user-account" : {
     [exec]           "method" : "PATCH",
     [exec]           "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/44315"
     [exec]         }
     [exec]       },
     [exec]       "additionalName" : "",
     [exec]       "alternateName" : "user1",
     [exec]       "birthDate" : "1977-01-01T00:00:00Z",
     [exec]       "customFields" : [ ],
     [exec]       "dashboardURL" : "",
     [exec]       "dateCreated" : "2023-02-17T18:49:14Z",
     [exec]       "dateModified" : "2023-02-17T18:49:14Z",
     [exec]       "emailAddress" : "user1@liferay.com",
     [exec]       "externalReferenceCode" : "e4dbb9b0-98f5-2ac0-6fc0-f5d0fafd3dd5",
     [exec]       "familyName" : "userfn1",
     [exec]       "givenName" : "usergn1",
     [exec]       "id" : 44315,
     [exec]       "jobTitle" : "",
     [exec]       "keywords" : [ ],
     [exec]       "name" : "usergn1 userfn1",
     [exec]       "organizationBriefs" : [ ],
     [exec]       "profileURL" : "",
     [exec]       "roleBriefs" : [ {
     [exec]         "id" : 20109,
     [exec]         "name" : "User"
     [exec]       } ],
     [exec]       "siteBriefs" : [ {
     [exec]         "descriptiveName" : "Global",
     [exec]         "id" : 20123,
     [exec]         "name" : "Global"
     [exec]       }, {
     [exec]         "descriptiveName" : "Liferay DXP",
     [exec]         "id" : 20121,
     [exec]         "name" : "Guest"
     [exec]       } ],
     [exec]       "userAccountContactInformation" : {
     [exec]         "emailAddresses" : [ ],
     [exec]         "facebook" : "",
     [exec]         "jabber" : "",
     [exec]         "postalAddresses" : [ ],
     [exec]         "skype" : "",
     [exec]         "sms" : "",
     [exec]         "telephones" : [ ],
     [exec]         "twitter" : "",
     [exec]         "webUrls" : [ ]
     [exec]       },
     [exec]       "userGroupBriefs" : [ ]
```
Actual Restuls: Curl doesn't return any response

2) Unable to update batch engine import task error
Steps to Reproduce:
       1) Add feature.flag.COMMERCE-8087=true to portal-ext.properties
       2) Start Portal
       3) Go to App Menu > Import/Export Center
       4) Click the Plus Button and then click Import File
       5) Choose the following file: [csv_account_import_auto_map.csv](https://github.com/liferay-core-infra/liferay-portal/files/10771915/csv_account_import_auto_map.csv)
       6) Select "Account (v1_0 - Liferay Headless Admin User)" as Entity Type
       7) Click Next
       8) Click Start Import
       
Expected Results: The accounts in the csv file are successfully imported
Actual Results: The following error appears
Screenshot from 2023-02-17 13-57-33

And the following appears in the console
```
2023-02-17 21:57:57.191 ERROR [default-4][BatchEngineImportTaskExecutorImpl:101] Unable to update batch engine import task {"mvccVersion": 1, "uuid": "4d0205c0-3d7e-63fb-99c1-54a3b901c9d3", "externalReferenceCode": "44435", "batchEngineImportTaskId": 3, "companyId": 20097, "userId": 20125, "createDate": "Fri Feb 17 21:57:57 GMT 2023", "modifiedDate": "Fri Feb 17 21:57:57 GMT 2023", "batchSize": 100, "callbackURL": "", "className": "com.liferay.headless.commerce.admin.account.dto.v1_0.Account", "contentType": "CSV", "endTime": "null", "errorMessage": "", "executeStatus": "STARTED", "fieldNameMapping": "{name=name, type=type, externalReferenceCode=externalReferenceCode}", "importStrategy": 2, "operation": "CREATE", "parameters": "{containsHeaders=true, updateStrategy=UPDATE, createStrategy=UPSERT, taskItemDelegateName=DEFAULT, delimiter=,, onErrorFail=true}", "processedItemsCount": 0, "startTime": "Fri Feb 17 21:57:57 GMT 2023", "taskItemDelegateName": "DEFAULT", "totalItemsCount": 3}
java.lang.IllegalArgumentException: Cannot deserialize value of type `java.lang.Integer` from String "business": not a valid `java.lang.Integer` value
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4393) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4324) ~[?:?]
	at com.liferay.batch.engine.internal.reader.BatchEngineImportTaskItemReaderUtil.convertValue(BatchEngineImportTaskItemReaderUtil.java:71) ~[?:?]
	at com.liferay.batch.engine.internal.BatchEngineImportTaskExecutorImpl._readItem(BatchEngineImportTaskExecutorImpl.java:295) ~[?:?]
	at com.liferay.batch.engine.internal.BatchEngineImportTaskExecutorImpl._importItems(BatchEngineImportTaskExecutorImpl.java:242) ~[?:?]
	at com.liferay.batch.engine.internal.BatchEngineImportTaskExecutorImpl.lambda$execute$0(BatchEngineImportTaskExecutorImpl.java:93) ~[?:?]
	at com.liferay.batch.engine.internal.BatchEngineTaskExecutorUtil.execute(BatchEngineTaskExecutorUtil.java:45) ~[?:?]
	at com.liferay.batch.engine.internal.BatchEngineImportTaskExecutorImpl.execute(BatchEngineImportTaskExecutorImpl.java:92) ~[?:?]
	at com.liferay.headless.batch.engine.internal.resource.v1_0.ImportTaskResourceImpl.lambda$_importFile$2(ImportTaskResourceImpl.java:485) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_352]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Integer` from String "business": not a valid `java.lang.Integer` value
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67) ~[?:?]
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1991) ~[?:?]
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1219) ~[?:?]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseInteger(StdDeserializer.java:844) ~[?:?]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseInteger(StdDeserializer.java:824) ~[?:?]
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:531) ~[?:?]
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:506) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4388) ~[?:?]
	... 13 more
```
[Log](https://testray.liferay.com/reports/production/logs/2023-02/test-1-27/test-portal-acceptance-pullrequest(master)/7001/functional-tomcat90-mysql57-jdk8/0/13/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:headless

**Comment by catarineaguiar** [comment]
@MrJohn1911 regression found:

```
    [exec] com.liferay.headless.admin.user.resource.v1_0.test.AccountRoleResourceTest > testDeleteAccountByExternalReferenceCodeAccountRoleUserAccountByExternalReferenceCode FAILED
     [exec]     java.lang.AssertionError: expected null, but was:<{"mvccVersion": 0, "ctCollectionId": 0, "userGroupRoleId": 121, "companyId": 20097, "userId": 45056, "groupId": 45052, "roleId": 45054}>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotNull(Assert.java:756)
     [exec]     	at org.junit.Assert.assertNull(Assert.java:738)
     [exec]     	at org.junit.Assert.assertNull(Assert.java:748)
     [exec]     	at com.liferay.headless.admin.user.resource.v1_0.test.AccountRoleResourceTest._assertAccountRoleUserAccountAssociation(AccountRoleResourceTest.java:858)
     [exec]     	at com.liferay.headless.admin.user.resource.v1_0.test.AccountRoleResourceTest.testDeleteAccountByExternalReferenceCodeAccountRoleUserAccountByExternalReferenceCode(AccountRoleResourceTest.java:166)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
```
```
     [exec] com.liferay.headless.admin.user.resource.v1_0.test.AccountRoleResourceTest > testGetAccountByExternalReferenceCodeUserAccountByExternalReferenceCodeAccountRolesPage FAILED
     [exec]     com.liferay.headless.admin.user.client.problem.Problem$ProblemException: No AccountEntry exists with the primary key 0
     [exec]     	at com.liferay.headless.admin.user.client.resource.v1_0.AccountRoleResource$AccountRoleResourceImpl.getAccountByExternalReferenceCodeUserAccountByExternalReferenceCodeAccountRolesPage(AccountRoleResource.java:461)
     [exec]     	at com.liferay.headless.admin.user.resource.v1_0.test.BaseAccountRoleResourceTestCase.testGetAccountByExternalReferenceCodeUserAccountByExternalReferenceCodeAccountRolesPage(BaseAccountRoleResourceTestCase.java:287)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
```
```
     [exec] com.liferay.headless.admin.user.resource.v1_0.test.AccountRoleResourceTest > testPostAccountByExternalReferenceCodeAccountRoleUserAccountByExternalReferenceCode FAILED
     [exec]     java.lang.AssertionError: expected:<204> but was:<404>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:633)
     [exec]     	at com.liferay.headless.admin.user.resource.v1_0.test.BaseAccountRoleResourceTestCase.assertHttpResponseStatusCode(BaseAccountRoleResourceTestCase.java:1515)
```
```
     [exec] com.liferay.headless.admin.user.resource.v1_0.test.UserAccountResourceTest > testPostAccountByExternalReferenceCodeUserAccountByExternalReferenceCode FAILED
     [exec]     java.lang.AssertionError
     [exec]     	at org.junit.Assert.fail(Assert.java:87)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
     [exec]     	at org.junit.Assert.assertNotNull(Assert.java:713)
     [exec]     	at org.junit.Assert.assertNotNull(Assert.java:723)
     [exec]     	at com.liferay.headless.admin.user.resource.v1_0.test.UserAccountResourceTest.testPostAccountByExternalReferenceCodeUserAccountByExternalReferenceCode(UserAccountResourceTest.java:651)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-02/test-1-29/test-portal-acceptance-pullrequest(master)/6438/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:headless

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:headless

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:headless

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Comment by MrJohn1911** [comment]
Hi @tinatian, can you review this? Thanks.

**Pull request closed without merging**
