### PR TITLE
[Bug Fix]LPS-157951 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan the test result.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
@tinatian no regression on relevant.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by vicnate5** [comment]
ci:test:jsf

**Comment by vicnate5** [comment]
would feel more comfortable if we run the jsf tests to check portlet deployment

**Comment by vicnate5** [comment]
@shuyangzhou JSF tests look good

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121402

**Pull request closed without merging**
