### PR TITLE
LPS-181002 Removes Log4j1 compatibility

### PR DESCRIPTION
**Pull request by dantewang**
@yuhai @tinatian

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@dantewang No regressions.

**Comment by tinatian** [comment]
@yuhai Please listed the detailed reason it is safe to remove https://github.com/liferay-core-infra/liferay-portal/pull/4191/commits/aff094d62afdf8272c1d8e78ac5f542459300f4f

**Comment by yuhai** [comment]
> @yuhai Please listed the detailed reason it is safe to remove [aff094d](https://github.com/liferay-core-infra/liferay-portal/commit/aff094d62afdf8272c1d8e78ac5f542459300f4f)

@tinatian, the codes were added by **LPS-125550 Add support for LCS**(d4a841e0fcd0757b14f67a698748b0075e4d54fa). We added log4j1 compatibility for LCS. For now, LCS had been removed from master, please see https://issues.liferay.com/browse/LPS-134572 and https://issues.liferay.com/browse/LRQA-68365. So we may remove the log4j1 compatibility for now.

cc @dantewang

**Comment by dantewang** [comment]
@yuhai Can you include this in the commit message and resend the PR? Thanks!

**Pull request closed without merging**
