### PR TITLE
[Components with more than 1 service] LPS-187673 Refactor ManagedServiceFactory components from redirect-service, fragment-web and document-library-web modules

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-187673](https://liferay.atlassian.net/browse/LPS-187673)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:echo

**Comment by RenanUmV** [comment]
ci:test:document

**Review by rafaprax — APPROVED** [review]

**Comment by RenanUmV** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:document

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@RenanUmV No regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by dantewang** [comment]
@RenanUmV It seems most helper classes are put `*Helper` together with its users, or in a `*.helper` package. I think it's OK for https://github.com/liferay-core-infra/liferay-portal/pull/5226, but for this PR it's better to move these helpers 2 levels up (out of `admin.service`).

cc @rafaprax 

Please resend, thanks!

**Comment by RenanUmV** [comment]
resent [here](https://github.com/liferay-core-infra/liferay-portal/pull/5367)

**Pull request closed without merging**
