### PR TITLE
[Remove Blocking usages]Lps 188914

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-188914

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:auto-tagging

**Comment by slnn** [comment]
ci:test:auto-tagging

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
On hold, waiting for confirmation from search team.

**Comment by dantewang** [comment]
@slnn Please rebase

**Comment by slnn** [comment]
No logic changed, just rebase

**Comment by dantewang** [comment]
Closing as of https://github.com/liferay-search/liferay-portal/pull/987

**Pull request closed without merging**
