### PR TITLE
LPS-168092 Remove "immediate = true" from Commerce II

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by MrJohn1911** [comment]
Hey @shuyangzhou this one is ready!

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
