### PR TITLE
LPS-148802

### PR DESCRIPTION
**Pull request by natocesarrego**
Hi fellows,

BChan asked me to create a new Ant task to print the info associated to a machine running `ant all` and I just was able to complete this task with the provided requirements using some external dependencies, in light of this I understand that makes sense the Core Team take a look on my proposed changed before send the pull to Brian. I've also used this pull to perform some external dependencies cleaning.

Thanks in advance for your review and inputs! :smile: 

https://issues.liferay.com/browse/LPS-148802

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@natocesarrego Thanks for letting us know about this. Our team is currently cleaning up third-party libs using at runtime, and next we may clean up those used in development. So introducing a new third party lib is the last thing we would like to do, I believe the information you want to print can be either retrieved by ant tasks or JDK API, you can also inline the code from third party lib if it is not much work.

I am going to close this pull, please send a new one.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by natocesarrego** [comment]
Hi @tinatian,

Thanks for your review! :slightly_smiling_face: 

>  I believe the information you want to print can be either retrieved by ant tasks or JDK API

I've thought the same during my investigation, but Ant doesn't provide builtin tasks which could retrieve the machine info. Actually, the best I could do was make Ant invoke Bash commands to collect this info. However, it demands some string manipulations and Bash commands may not be the best solution since this new Ant task should be run in multiple OSs (Windows, OSX and Linux). In regards to the default JDK, I'm able to collect just part of the information demanded, OS and Processors. Therefore, considering the requirements briefly described, I've understood that use the third party tools added by this pull seem to be a good solution even with the trade-off of add new external dependencies.

Do you have any suggestion to achieve my current goal, collect info about the machine running ant all?

Info means: hardware (cpu, ram), ip and os

> you can also inline the code from third party lib if it is not much work.

What exactly did you mean? Do you mind to clarify?

Thanks!

**Comment by tinatian** [comment]
@natocesarrego 
If ant can not do it, how about gradle?

`inline the code` means copying the logic you used from third party into our code to decouple it from third party lib.

The bottom line for me is not introducing third party lib, any hack or hard coded string or string manipulation is fine.


Tina.

**Comment by natocesarrego** [comment]
Thanks for your clarification, @tinatian!

I'll give a try in your suggestions. :slightly_smiling_face:

**Pull request closed without merging**
