### PR TITLE
[Components with more than 1 service] LPS-176008 Refactor DTOConverter components with more than 1 service type from object-rest-impl module

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:object

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
@daiazius No regressions found.

**Comment by tinatian** [comment]
@daiazius Please see https://github.com/liferay-core-infra/liferay-portal/pull/3530#issuecomment-1440935572.

Please resend.

Thanks.
Tina

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:object

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
@daiazius There is a compile issue so no tests ran. Please fix and rerun tests.
```
[exec] > Task :apps:object:object-rest-impl:compileJava FAILED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/object/object-rest-impl/src/main/java/com/liferay/object/rest/internal/manager/v1_0/DefaultObjectEntryManagerImpl.java:1358: error: cannot find symbol
     [exec] 	private DTOConverter<com.liferay.object.model.ObjectEntry, ObjectEntry>
     [exec] 	        ^
     [exec]   symbol:   class DTOConverter
     [exec]   location: class com.liferay.object.rest.internal.manager.v1_0.DefaultObjectEntryManagerImpl
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
```
[Log](https://testray.liferay.com/reports/production/logs/2023-02/test-1-25/test-portal-acceptance-pullrequest(master)/6343/jenkins-console.txt.gz?authuser=0)

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:object

**Comment by daiazius** [comment]
ci:test:startup

**Comment by tinatian** [comment]
@daiazius Please remember to remove QA Failed flag to trigger a new round of checking.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by daiazius** [comment]
Hi @tinatian, can you review this PR? Thanks

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
@daiazius No regressions found.

**Comment by tinatian** [comment]
@daiazius You do not need a constants for there is only one usage of it.

FYI @rafaprax

**Pull request closed without merging**
