### PR TITLE
[Components with more than 1 service] LPS-192541 Refactor ImportLayoutsMVCActionCommand component

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-192541](https://liferay.atlassian.net/browse/LPS-192541)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:stop

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:export-import

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
sent to BChan manually, see https://github.com/brianchandotcom/liferay-portal/pull/139345

/cc @tinatian

**Pull request closed without merging**
