### PR TITLE
[Components with more than 1 service] LPS-201309 Refactor SXPParameterDataCreator component

### PR DESCRIPTION
**Pull request by rafaprax**
**Author:** @RenanUmV
**Issue:** https://liferay.atlassian.net/browse/LPS-201309
**Forwarded from:** https://github.com/rafaprax/liferay-portal/pull/1370
**Original comment:**
[LPS-201309](https://liferay.atlassian.net/browse/LPS-201309)

Previous Pull: https://github.com/rafaprax/liferay-portal/pull/1344

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@rafaprax No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Comment by rafaprax** [comment]
ci:forward:force

**Pull request closed without merging**
