### PR TITLE
LPS-159094 Create Xalan patch | 8-31

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian Resending this PR because BChan was unable to build the patched jar with the previous PR. As of current master head 9d3ceb0328e1566ac65e3318510adc1c0bc3cffc, I can successfully run `gw commitCache` to run the patch and create the patched jar with this PR.

The force push is just a rebase to make sure no conflicts.

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@dantewang no regressions found.

**Comment by tinatian** [comment]
@dantewang Please rebase and send it to Brian Chan directly, cc me and shuyang.

Thanks.
Tina

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122623

**Pull request closed without merging**
