### PR TITLE
LPS-158311 8-4 | Rename classes and Resend

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian @shuyangzhou Renamed as https://github.com/brianchandotcom/liferay-portal/pull/121230#issuecomment-1204586192 and resend

### CODE REVIEW

**Comment by dantewang** [comment]
@catarineaguiar Could you check the test results? Thanks!

**Comment by catarineaguiar** [comment]
all the PR analysis on CI were aborted according to this [message](https://liferay.slack.com/archives/C19PWQ74J/p1659633528796189) 

when this runs finish, will need to re-run relevant.

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@dantewang no regressions on relevant

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121403

**Pull request closed without merging**
