### PR TITLE
[JDK17] LPD-44985 Fix ant build-lib-versions under JDK17

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
This passed on my local when I run `ant build-lib-versions` under JDK17.

@slnn Could you pull this PR and run `ant build-lib-versions` under JDK8? Let's me know if it passes.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Hi @dantewang 

Test this pull on my laptop with JDK8  with these steps:

1. Apply this pull on master:b1867a602f09b5c53221299e4600aa2f090ae0ad
2. Run ant all
3. Run ant build-lib-versions under portal-impl

Only see some WARNING

````
 [java] Compiler warnings:
     [java]   WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
     [java] Warning: org.apache.xerces.parsers.SAXParser: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' is not recognized.
     [java] Warning: org.apache.xerces.parsers.SAXParser: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
     [java] Warning: org.apache.xerces.parsers.SAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
```
`
Full out put please see https://gist.github.com/slnn/a2aaa106d6ba0dbaec791b20b116ae5e

**Comment by dantewang** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
