### PR TITLE
[Components with more than 1 service] LPS-182635 Refactor TableFDSView components in commerce-channel-web

### PR DESCRIPTION
**Pull request by daiazius**
Issue: https://issues.liferay.com/browse/LPS-182635

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:commerce

**Comment by daiazius** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:commerce

**Review by rafaprax — APPROVED** [review]

**Comment by Kvale1733** [comment]
@daiazius No regressions.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/134424

**Pull request closed without merging**
