### PR TITLE
LPS-157255 Remove web portal dir property

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
@catarineaguiar 
Hi Catarine,
could you please help me review this test result?
Thank you!

CC. @tinatian

**Comment by catarineaguiar** [comment]
@julschong  I analyzed accepatance and relevant, and no regressions were found.

**Comment by julschong** [comment]
rebase to resolve conflict in semver

> portal-impl/bnd.bnd
> portal-kernel/bnd.bnd

**Comment by julschong** [comment]
rebased again for conflict in:

> portal-impl/bnd.bnd
> portal-impl/src/com/liferay/portal/util/packageinfo
> portal-kernel/bnd.bnd
> portal-kernel/src/com/liferay/portal/kernel/util/packageinfo

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/120825

**Pull request closed without merging**
