### PR TITLE
[Remove unused field] LPS-199423

### PR DESCRIPTION
**Pull request by JanisZhang**
Remove unused reference fields in class `PortalCapabilityLocatorImpl`, `DLFileEntryTypePermissionPortalInstanceLifecycleListener`, and `GoogleDocsIGDisplayContextFactory`. Thanks.
https://liferay.atlassian.net/browse/LPS-199423

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142489

cc @shuyangzhou

**Pull request closed without merging**
