### PR TITLE
[Replace Non-Blocking Usage] LPS-199966

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace non-blocking ServiceProxyFactory usages in class `ResourcePermissionLocalServiceImpl` and `GroupImpl`. Thanks for checking.
https://liferay.atlassian.net/browse/LPS-199966

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by lilylcl** [comment]
ci:test:stable

**Comment by lilylcl** [comment]
ci:test:relevant

**Comment by lilylcl** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Pull request closed without merging**
