### PR TITLE
[Spring Beans] LPS-200485 Move class ZipReaderFactoryImpl and ZipWriterFactoryImpl into module

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(11/2 8:14)

**Comment by Kvale1733** [comment]
@W2jx No regressions found

**Comment by W2jx** [comment]
no conflicts(11/3 8:52)

**Comment by W2jx** [comment]
no conflicts(11/6 8:35)

**Comment by W2jx** [comment]
no conflicts(11/7 9:34)

**Comment by W2jx** [comment]
no conflicts(11/8 10:05)

**Comment by W2jx** [comment]
no conflicts(11/9 9:58)

**Comment by W2jx** [comment]
no conflicts（11/13 9:31）

**Comment by W2jx** [comment]
no conflicts(11/14 10:01)

**Pull request closed without merging**
