### PR TITLE
LPS-144726 remove the usage of curvesapi

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Resend https://github.com/liferay-core-infra/liferay-portal/pull/2773#issuecomment-1366264059. Because it has code conflict in BChan's repo.
This is for ticket https://issues.liferay.com/browse/LPS-144726.
Seems like curvesapi is not necessary dependency when we compile poi. Therefore I am going to clean them away.
Thanks for checking.

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
No regressions found in relevant tests. SF failure looks not related.

**Comment by jeffwu0724** [comment]
fixed the code conflict in lib/versions-complete.xml by auto-generate, the previous test result should be good enough.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129201

**Pull request closed without merging**
