### PR TITLE
[Static reference] LPS-182671 Remove static references in class MBDiscussionPermission | part 2

### PR DESCRIPTION
**Pull request by W2jx**
previous: https://github.com/liferay-core-infra/liferay-portal/pull/5256

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:lima

**Comment by W2jx** [comment]
ci:test:comment

**Comment by W2jx** [comment]
ci:test:message-boards

**Comment by W2jx** [comment]
ci:test:questions

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@W2jx No regressions. SF is unrelated.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139191

**Pull request closed without merging**
