### PR TITLE
LPS-170848 Remove Dom4JUtil usage in ServiceBuilder

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from #2907

This pull is to remove most of the manual String checking logic here: [PR#2907](https://github.com/liferay-core-infra/liferay-portal/commit/f9790e88396d1c7971585a9df3d02a2858af0847#diff-44c3b2e07405a7164d11316c794f40d2236921b0f060838456de1531f5a36903R4829-R4845)

- dom4j was padding each line with spaces so I setPadText(false) and no longer need to check \n\n  and \n
- Set omitenEoding to true so no longer need to manually remove
- Still could not get rid of the last new line character (shown in 1st screenshot) , so I had to use the StringUtil.trim()

### CODE REVIEW

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:tasks

**Comment by julschong** [comment]
ci:test:tasks

**Comment by julschong** [comment]
ci:test:help

**Comment by julschong** [comment]
ci:help

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2991

**Pull request closed without merging**
