### PR TITLE
[TS] LPS-174346 Setting timeout to prevent long waiting time in querying background task status

### PR DESCRIPTION
**Pull request by evibudai**
Hi Team,

https://issues.liferay.com/browse/LPS-174346

Issue:
Customer reported that some threads are blocked on the second node of their cluster, and they are stuck in "wait" status for a long time.
@fabian-bouche-liferay discovered that the blocked threads are waiting here https://github.com/liferay/liferay-portal/blob/7.3.x/modules/apps/portal-background-task/portal-background-task-service/src/main/java/com/liferay/portal/background/task/internal/BackgroundTaskStatusRegistryImpl.java#L114  because there is no timeout on the future.get() call. Basically, they wait on something that is not going to happen, so for example, there were threads that were waiting for 20 days.
This method gets called when there is a staging publication in progress and an automatic reload (polling) of the page happens to get the status of the background task. During that, the response gets lost, leading to the thread waiting indefinitely.
To prevent that, he suggested we introduce a timeout to the future.get() call. If the timeout is exceeded, the method would throw an InterruptedException and caught immediately after. We get an error message on the browser that the status could not be retrieved, but the next polling call would likely get the status with no exception.

Please review my PR!

Thank you and best regards,
Évi

### CODE REVIEW

**Comment by tinatian** [comment]
@evibudai Please mark your ticket with [TS] to make it prioritized for review.

@brunofalc Another pull from TS without marking [TS] in the title.

TIna.

**Comment by tinatian** [comment]
@evibudai No, we can not set time out here, how do you know 10 seconds is enough for a background task? Background task is designed to deal with long time process.

To fix this issue, please figure out why this happens and set the right status to background task when this happens.
"This method gets called when there is a staging publication in progress and an automatic reload (polling) of the page happens to get the status of the background task. During that, the response gets lost, leading to the thread waiting indefinitely."

Please resend.

Thanks.
Tina

**Comment by fabian-bouche-liferay** [comment]
We're inside the getMasterBackgroundTaskStatus method.
This method issues a background task in order to get the status of another background task.
The reason why checking the status of the background task goes through a background task itself is, I believe, because this is the easiest way to be able to talk to the master node when you are on one of the non master nodes.
Running this task of getting the status of another one is supposed to be a quick task (the view with the percentage of progress of the staging publication is supposed to be displayed instantly).
Thus, 10 seconds is a rather conservative timeout.

**Comment by evibudai** [comment]
> @evibudai Please mark your ticket with [TS] to make it prioritized for review.
> 
> @brunofalc Another pull from TS without marking [TS] in the title.
> 
> TIna.

Hi @tinatian, thanks for reminding me, I corrected my mistake.

**Pull request closed without merging**
