### PR TITLE
[Remove Spring extender usage]Lps 162558

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-162558

Hi @tinatian @dantewang 

This pull removes the spring extender usage in module commerce-product-service and use *LocalServiceUtil to replace related *LocalService usage to break circular dependency issue.

By the way, I add a SF exclusion to skip the JavaOSGiReferenceCheck on CPDefinitionLocalServiceImpl then we can use CommercePriceEntryLocalServiceUtil and CommercePriceListLocalServiceUtil (come from commerce-price-list-api) in CPDefinitionLocalServiceImpl to break the circular dependency issue between differen modules (commerce-product-service and commerce-price-list-service) without SF's complain

Lily

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by slnn** [comment]
ci:test:commerce

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
@slnn Code looks good to me, wait for review from commerce team.

Tina

**Comment by dantewang** [comment]
@slnn Conflicts, please resolve.

**Comment by slnn** [comment]
> @slnn Conflicts, please resolve.

Done

**Comment by tinatian** [comment]
@slnn Please rebase.

Tina

**Comment by slnn** [comment]
> @slnn Please rebase.
> 
> Tina

Done

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123356

**Pull request closed without merging**
