### PR TITLE
[Rename Classes] LPS-166960 Rename classes in modules info-api、info-impl、layout-content-page-editor-web

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@W2jx all tests are failling due to:

```
 [exec] > Task :apps:fragment:fragment-entry-processor:fragment-entry-processor-impl:compileJava FAILED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/fragment/fragment-entry-processor/fragment-entry-processor-impl/src/main/java/com/liferay/fragment/entry/processor/internal/util/FragmentEntryProcessorHelperImpl.java:386: error: cannot find symbol
     [exec] 				_infoItemServiceTracker.getFirstInfoItemService(
     [exec] 				^
     [exec]   symbol:   variable _infoItemServiceTracker
     [exec]   location: class com.liferay.fragment.entry.processor.internal.util.FragmentEntryProcessorHelperImpl
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/fragment/fragment-entry-processor/fragment-entry-processor-impl/src/main/java/com/liferay/fragment/entry/processor/internal/util/FragmentEntryProcessorHelperImpl.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 1 error
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-31/test-portal-acceptance-pullrequest(master)/5753/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
Force-Push is just to fix the bug.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@W2jx no regressions found.

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2391

**Pull request closed without merging**
