### PR TITLE
[Reference cleanup]LPS-162271

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

Resend, fixed unit test.

This PR is to convert method references to field references in dynamic-data-mapping-service | Part 1.
https://issues.liferay.com/browse/LPS-162271

Previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/1555

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @zhangyan0701, Could you please help to scan the test result? Thank you.

**Comment by JanisZhang** [comment]
Hi @Kvale1733,  Could you please help to scan the test results? Thank you

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by julschong** [comment]
@JanisZhang Hi Janis,
no issue found in code.

Same question as https://github.com/liferay-core-infra/liferay-portal/pull/1609#issuecomment-1242514054
image

**Comment by julschong** [comment]
Per Tina, it is ok to move on following the google doc list
I will foward this

**Comment by julschong** [comment]
ci:close

**Comment by julschong** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/122925

**Pull request closed without merging**
