### PR TITLE
[SF] LPS-174535 Remove `ConfigurationPolicy.OPTIONAL` from `@Component` annotations

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__ <https://issues.liferay.com/browse/LPS-174535>

This SF rule ensures that the `configurationPolicy` field in `@Component` annotations do not use `ConfigurationPolicy.OPTIONAL` as it is the default value.

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@kevhlee no regressions found. Can you check the formatting issue?

```
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/users-admin/users-admin-test/src/testIntegration/java/com/liferay/users/admin/search/test/UserReindexerPerformanceOfLargeUserGroupInManySitesTest.java expected:<...ew ArrayList<>();
     [java] 
     [java] 	[@DeleteAfterTestRun
     [java] 	private List<Group> _groups;
     [java] 
     [java] 	private int _groupsCount;
     [java] 
     [java] 	@DeleteAfterTestRun
     [java] 	private List<Organization> _organizations;
     [java] 
     [java] 	@DeleteAfterTestRun
     [java] 	private List<UserGroup> _userGroups;
     [java] 
     [java] 	@DeleteAfterTestRun
     [java] 	private List<User> _users;
     [java] 
     [java] 	private int _usersCount];
     [java] 
     [java] }> but was:<...ew ArrayList<>();
     [java] 
     [java] 	[private int _groupsCount;
     [java] 
     [java] 	@DeleteAfterTestRun
     [java] 	private List<Group> _groups;
     [java] 
     [java] 	@DeleteAfterTestRun
     [java] 	private List<Organization> _organizations;
     [java] 
     [java] 	private int _usersCount;
     [java] 
     [java] 	@DeleteAfterTestRun
     [java] 	private List<UserGroup> _userGroups;
     [java] 
     [java] 	@DeleteAfterTestRun
     [java] 	private List<User> _users];
     [java] 
     [java] }>
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:444)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:286)
[stopwatch] [run.batch.test.action: 18:47.427 sec]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-02/test-1-11/test-portal-source-format/6728/source-format-current-branch-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by kevhlee** [comment]
Hi @catarineaguiar. For this PR, the formatting issue you highlighted is not relevant (I was only editing the class annotations).

I could fix it with this PR, but I am hesitant to do so as it might be fixed upstream before this PR gets forwarded, which could might lead to a rebase error.

**Comment by kevhlee** [comment]
Rebasing pull request.

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129865

**Pull request closed without merging**
