### PR TITLE
[Remove Stream/Optional usage] LPS-174709 asset-info-impl, asset-publisher-web

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-174709

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:help

**Comment by catarineaguiar** [comment]
ci:test:echo-acceptance

**Comment by Kvale1733** [comment]
@JanisZhang No regressions.

**Comment by JanisZhang** [comment]
Force-pushed, I append 1 SF commit. thanks!

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:echo-acceptance

**Comment by JanisZhang** [comment]
ci:stop

**Pull request closed without merging**
