### PR TITLE
LPS-181446

### PR DESCRIPTION
**Pull request by yuhai**
@tinatian, @dantewang, I rebased this based on https://github.com/liferay-core-infra/liferay-portal/pull/4792.

I added the commit(https://github.com/liferay-core-infra/liferay-portal/commit/c4249328187e3037edd0c2328e411b50c6b0a0b0) to solve LPS-187661 happened again. 

@catarineaguiar, could you please test the pr about LPS-187661 again? Thanks.

### CODE REVIEW

**Comment by Kvale1733** [comment]
@yuhai No regressions found. LPS-187661 passes.

**Comment by tinatian** [comment]
Wait for https://github.com/liferay-core-infra/liferay-portal/pull/4794 to be merged

**Comment by yuhai** [comment]
@tinatian, @dantewang, https://github.com/liferay-core-infra/liferay-portal/pull/4794 was merged to master. I rebased it based on the latest master. Since the "QA passed" label was added, I removed the test commit. In addition, bnd.bnd is changed during ant all. So I add the change to https://github.com/liferay-core-infra/liferay-portal/pull/4793/commits/3d456878f35a66fd8282efc28f22c41fa989ff3e. No other changes. No need to run ci test again.

**Comment by yuhai** [comment]
ci:test:sf

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4817

**Pull request closed without merging**
