### PR TITLE
[Method References] LPS-183025 Convert method references to field references in module wiki-navigation-web, nested-portlets-web, site-navigation-menu-web

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:wiki

**Comment by zhangyan0701** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(4/28 10:43)

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:foward

**Comment by W2jx** [comment]
ci:foward

**Comment by W2jx** [comment]
no conflicts(5/2 10:54)

**Comment by W2jx** [comment]
ci:test:help

**Comment by W2jx** [comment]
ci:help

**Comment by W2jx** [comment]
ci:forward

**Pull request closed without merging**
