### PR TITLE
[Rename classes under modules:data-engine, depot] Lps 166996

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-166996

This pull just updated the commit message, with no logic changes.

Tests have passed in https://github.com/liferay-core-infra/liferay-portal/pull/2251#event-7737071063

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
ci:test:depot

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
