### PR TITLE
[Method References 2] LPS-170790 Convert method reference to ServiceTracker in class ActionExecutorManagerImpl(portal-workflow-kaleo-runtime-impl)

### PR DESCRIPTION
**Pull request by W2jx**
Fix the bug in this [pr](https://github.com/liferay-core-infra/liferay-portal/pull/2858).

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/2858、https://github.com/liferay-core-infra/liferay-portal/pull/2794

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(1/5 8:59)

**Comment by tinatian** [comment]
Please see https://github.com/liferay-core-infra/liferay-portal/pull/2812 and resend.

Thanks!
Tina

**Pull request closed without merging**
