### PR TITLE
Lps 193819 part 1

### PR DESCRIPTION
**Pull request by slnn**
Hi @dantewang

I reordered these commits in  https://github.com/liferay-core-infra/liferay-portal/pull/5307 by alphabet order of method names and split them into three parts, this one is the first part.

Thanks
Lily

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by shuyangzhou** [comment]
ci:forward:force

**Pull request closed without merging**
