### PR TITLE
[Convert method references]LPS-162374 Convert method references to field references in mdoule co…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-162734

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Comment by dantewang** [comment]
ci:test:commerce

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@victoroscuro Please help me scan test results.

Tina

**Comment by victoroscuro** [comment]
@tinatian Checks are fine. Thanks

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123249

**Pull request closed without merging**
