### PR TITLE
LPS-150970

### PR DESCRIPTION
**Pull request by mbowerman**
Hi Core Infrastructure Team,

I'm not sure whether you are the right team to send this to. Please let me know if I should send it to a different team instead. I don't know which team owns this module.

https://issues.liferay.com/browse/LPS-150970

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
ci:test:acceptance

**Comment by tinatian** [comment]
@rafaprax Please take this over.

Thanks.
Tina.

**Comment by rafaprax** [comment]
ci:close

**Comment by mbowerman** [comment]
Re-sent at https://github.com/liferay-usm/liferay-portal/pull/517

**Pull request closed without merging**
