### PR TITLE
[Method References 2] LPS-170773 Convert method reference to ServiceTrackerList in class BlogsDemo（module blogs-demo）

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:blogs

**Comment by W2jx** [comment]
no conflicts(1/19 14:53)

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129259

**Pull request closed without merging**
