### PR TITLE
[System Properties] LPS-158206 New Feature 2: support property reference

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian @W2jx

### CODE REVIEW

**Comment by dantewang** [comment]
Force pushed just to correct the typo in commit messge.

**Comment by dantewang** [comment]
@catarineaguiar Could you review the test results when they finish? Thanks!

**Comment by catarineaguiar** [comment]
@dantewang no regressions found.

**Comment by W2jx** [comment]
no conflicts(6:17 PM)

**Comment by W2jx** [comment]
no conflicts(6:16 PM)

**Pull request closed without merging**
