### PR TITLE
[Components with more than 1 service] LPS-177016 Refactor DTOConverter components with more than 1 service type from headless-commerce-admin-channel-impl module

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by daiazius** [comment]
Hello @tinatian, can you review this pull? Thank you

**Pull request closed without merging**
