### PR TITLE
[Remove Blocking usages]LPS-188270 portal-kernel | ConfigurationProviderUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Review by dantewang — APPROVED** [review]

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@W2jx All tests failed due to this issue

```
 [exec] > Task :apps:calendar:calendar-api:deployDependencies NO-SOURCE
     [exec] > Task :apps:calendar:calendar-api:deployConfigs NO-SOURCE
     [exec] > Task :apps:layout:layout-taglib:jar
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/staging/staging-taglib/src/main/java/com/liferay/staging/taglib/internal/display/context/RenderControlsDisplayContext.java:14: error: cannot find symbol
     [exec] import com.liferay.portal.kernel.module.configuration.ConfigurationProviderUtil;
     [exec]                                                      ^
     [exec]   symbol:   class ConfigurationProviderUtil
     [exec]   location: package com.liferay.portal.kernel.module.configuration
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/staging/staging-taglib/src/main/java/com/liferay/staging/taglib/internal/display/context/RenderControlsDisplayContext.java:38: error: cannot find symbol
     [exec] 			ConfigurationProviderUtil.getCompanyConfiguration(
     [exec] 			^
     [exec]   symbol:   variable ConfigurationProviderUtil
     [exec]   location: class com.liferay.staging.taglib.internal.display.context.RenderControlsDisplayContext
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 2 errors
     [exec] 
     [exec] > Task :apps:staging:staging-taglib:compileJava FAILED
 ```
[Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-40/test-portal-acceptance-pullrequest(master)/5326/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
ci:test:startup

**Comment by dantewang** [comment]
@W2jx Conflicts, please resend.

**Pull request closed without merging**
