### PR TITLE
Lpd 29968

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:help

**Comment by tinatian** [comment]
ci:test:echo

**Comment by tinatian** [comment]
ci:test:redirect

**Comment by tinatian** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:30896353

**Comment by dantewang** [comment]
ci:report:30904961

**Comment by dantewang** [comment]
ci:report:30904961

**Comment by dantewang** [comment]
ci:test:echo

**Comment by dantewang** [comment]
ci:report:30984851

**Comment by dantewang** [comment]
ci:report:30984851

**Comment by dantewang** [comment]
@tinatian I fixed a unique failure (functional test) at https://github.com/liferay-core-infra/liferay-portal/pull/7215

No other unique failure found. Forwarding the other PR.

**Pull request closed without merging**
