### PR TITLE
[Remove Immediate] LPS-193926 Removal of DLProcessor registration support from the HookHotDeployListener

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://liferay.atlassian.net/browse/LPS-193926

### CODE REVIEW

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@rafaprax Unfortunately it conflicts again...

**Comment by rafaprax** [comment]
Ey @dantewang, conflict solved.

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:forward:force

**Comment by shuyangzhou** [comment]
ci:stop

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139790

**Pull request closed without merging**
