### PR TITLE
[blocker] LPS-180576 fix cannot find TransformUtil in older versions

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, 

This is for fixing https://issues.liferay.com/browse/LPS-180576.
In this code 
```
<#if freeMarkerTool.isVersionCompatible(configYAML, 2)>

public static boolean isVersionCompatible(
		ConfigYAML configYAML, int version) {

		if (configYAML.getCompatibilityVersion() >= version) {
			return true;
		}

		return false;
	}
````
only the configYAML in 7.4 has a CompatibilityVersion with number 2. In older versions, they are all set to 1 by default., which means isVersionCompatible() will be true only in 7.4.
By doing this, we can make sure TransformUtil is used only in 7.4. 

Reproduce step:

1. `cd modules/util/portal-tools-rest-builder` then `gw clean deploy`
2. Copy `tools/sdk/dependencies/com.portal.tools.rest.builder/lib/com.portal.tools.rest.builder.jar`
3. and replace and rename into `7.3.x/.gradle/caches/modules-2/files-2.1/com.liferay.portal.tools.rest.builder/1.0.281/794286258adf42dd8e78a4d6b5839a4d79873148/com.liferay.portal.tools.rest.builder-1.0.281.jar` <It may be some other versions than 1.0.281 , just make sure you pick the highest version, and rename to adapt to that version>
4. In `7.3.x` running `gw buildREST` in `modules/apps/bulk` and `modules/dxp/apps/search-experiences`
5. make sure the generated code does not show error below, and the jar can be built successfully
```
error: package com.liferay.petra.function.transform does not exist
     [exec] import com.liferay.petra.function.transform.TransformUtil;
```
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
Hi @zhangyan0701 ,

Could you please help me check if this [regression](https://issues.liferay.com/browse/LPS-180576) still occurs in older versions, please?
Thanks!

**Comment by jeffwu0724** [comment]
ci:test:headless

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
working on the code conflict

**Comment by jeffwu0724** [comment]
ci:stop

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
Hi @catarineaguiar , @Kvale1733

Could you please help me check if this [regression](https://issues.liferay.com/browse/LPS-180576) still occurs in older versions, please?
Thanks!

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found. Testing passed on 7.1-7.3. I didn't see any references to com.liferay.petra.function.transform in 7.0 so no need to test.

**Comment by jeffwu0724** [comment]
Hi @tinatian , we have tested the codes in master and older versions, and there are no regressions.
Could you review it when you have time, please?
Thanks!

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:headless

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
Hi @zhangyan0701 

Could you please help me check the test result in master when it is ready, please? 
I have checked manually in 7.3.x and 7.2.x and both of them work.
Thanks!

**Comment by zhangyan0701** [comment]
@jeffwu0724 No regressions found in master test results.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4150

**Pull request closed without merging**
