### PR TITLE
LPS-158623 Fix bug in Dom4jUtil

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar  
Hi Catarine,
Could you please help me review this pull?
Thanks!

CC. @tinatian

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/120820
I have fixed the wrong ticket info in the commit message.

**Pull request closed without merging**
