### PR TITLE
[Component with its own class name as service type] LPS-195477 Refctor Registry classes from Data Engine, Mentios and Analytics module 

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Related: https://liferay.atlassian.net/browse/LPS-195477

Correction of: https://github.com/liferay-core-infra/liferay-portal/pull/5530

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Valmir-unicap** [comment]
ci:test:data-engine

**Comment by Valmir-unicap** [comment]
ci:test:lima

**Comment by Valmir-unicap** [comment]
ci:test:analytics-cloud-acceptance

**Comment by Valmir-unicap** [comment]
ci:test:analystics-cloud

**Comment by Valmir-unicap** [comment]
ci:test:analytics-cloud

**Comment by Valmir-unicap** [comment]
ci:stop:analytics-cloud

**Comment by catarineaguiar** [comment]
ci:stop:analytics-cloud

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141243

**Pull request closed without merging**
