### PR TITLE
remove_deprecated_for_portal-kernel_part_Ten

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is remove_deprecated_for_portal_kernel_part_Ten.
Thanks for checking. Also see https://github.com/jeffwu0724/liferay-portal/pull/57

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina.

**Comment by catarineaguiar** [comment]
@vicnate5 will not have time to review this one today.

**Comment by vicnate5** [comment]
@jeffwu0724 Regression here with upgrades

Steps to Reproduce:
1. Import [this database](https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/6.2.10.21/data-archive/data-archive-portal-mysql.zip) into MySQL
2. Execute upgrade tool `tools/portal-tools-db-upgrade-client/db_upgrade.sh`

Result:
```
     [java] 2022-04-21 00:19:41.104 ERROR [main][DBUpgrader:79] null
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Unknown column 'mvccVersion' in 'field list'
     [java]     at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:115) ~[portal-kernel.jar:?]
     [java]     at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil._upgradeProcess(UpgradeProcessUtil.java:160) ~[portal-kernel.jar:?]
     [java]     at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil.upgradeProcess(UpgradeProcessUtil.java:136) ~[portal-kernel.jar:?]
     [java]     at com.liferay.portal.events.StartupHelperUtil.upgradeProcess(StartupHelperUtil.java:154) ~[portal-impl.jar:?]
     [java]     at com.liferay.portal.tools.DBUpgrader._upgradePortal(DBUpgrader.java:386) ~[portal-impl.jar:?]
     [java]     at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:162) ~[portal-impl.jar:?]
     [java]     at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:154) ~[portal-impl.jar:?]
     [java]     at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:130) [portal-impl.jar:?]
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
     [java]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
     [java]     at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
     [java]     at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:54) [com.liferay.portal.tools.db.upgrade.client.jar:?]
     [java] Caused by: com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Unknown column 'mvccVersion' in 'field list'
     [java]     at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:115) ~[portal-kernel.jar:?]
     [java]     at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:137) ~[portal-kernel.jar:?]
     [java]     at com.liferay.portal.upgrade.UpgradeProcess_7_0_0.doUpgrade(UpgradeProcess_7_0_0.java:87) ~[portal-impl.jar:?]
     [java]     at com.liferay.portal.kernel.upgrade.UpgradeProcess.lambda$upgrade$0(UpgradeProcess.java:109) ~[portal-kernel.jar:?]
     [java]     at com.liferay.portal.db.partition.DBPartitionUtil.forEachCompanyId(DBPartitionUtil.java:118) ~[portal-impl.jar:?]
     [java]     at com.liferay.portal.dao.db.BaseDB.process(BaseDB.java:356) ~[portal-impl.jar:?]
     [java]     at com.liferay.portal.kernel.dao.db.BaseDBProcess.process(BaseDBProcess.java:293) ~[portal-kernel.jar:?]
     [java]     at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:96) ~[portal-kernel.jar:?]
     [java]     ... 12 more
     [java] Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'mvccVersion' in 'field list'
     [java]     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql.jar:8.0.21]
     [java]     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql.jar:8.0.21]
     [java]     at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql.jar:8.0.21]
     [java]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql.jar:8.0.21]
     [java]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092) ~[mysql.jar:8.0.21]
     [java]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040) ~[mysql.jar:8.0.21]
     [java]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347) ~[mysql.jar:8.0.21]
     [java]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025) ~[mysql.jar:8.0.21]
     [java]     at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[hikaricp.jar:?]
     [java]     at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[hikaricp.jar:?]
     [java]     at com.liferay.portal.upgrade.v7_0_0.UpgradeDocumentLibrary.addClassName(UpgradeDocumentLibrary.java:64) ~[portal-impl.jar:?]
     [java]     at com.liferay.portal.upgrade.v7_0_0.UpgradeDocumentLibrary.updateRepositoryClassNameIds(UpgradeDocumentLibrary.java:391) ~[portal-impl.jar:?]
     [java]     at com.liferay.portal.upgrade.v7_0_0.UpgradeDocumentLibrary.doUpgrade(UpgradeDocumentLibrary.java:118) ~[portal-impl.jar:?]
     [java]     at com.liferay.portal.kernel.upgrade.UpgradeProcess.lambda$upgrade$0(UpgradeProcess.java:109) ~[portal-kernel.jar:?]
     [java]     at com.liferay.portal.db.partition.DBPartitionUtil.forEachCompanyId(DBPartitionUtil.java:118) ~[portal-impl.jar:?]
     [java]     at com.liferay.portal.dao.db.BaseDB.process(BaseDB.java:356) ~[portal-impl.jar:?]
     [java]     at com.liferay.portal.kernel.dao.db.BaseDBProcess.process(BaseDBProcess.java:293) ~[portal-kernel.jar:?]
     [java]     at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:96) ~[portal-kernel.jar:?]
     [java]     at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:137) ~[portal-kernel.jar:?]
     [java]     at com.liferay.portal.upgrade.UpgradeProcess_7_0_0.doUpgrade(UpgradeProcess_7_0_0.java:87) ~[portal-impl.jar:?]
     [java]     at com.liferay.portal.kernel.upgrade.UpgradeProcess.lambda$upgrade$0(UpgradeProcess.java:109) ~[portal-kernel.jar:?]
     [java]     at com.liferay.portal.db.partition.DBPartitionUtil.forEachCompanyId(DBPartitionUtil.java:118) ~[portal-impl.jar:?]
     [java]     at com.liferay.portal.dao.db.BaseDB.process(BaseDB.java:356) ~[portal-impl.jar:?]
     [java]     at com.liferay.portal.kernel.dao.db.BaseDBProcess.process(BaseDBProcess.java:293) ~[portal-kernel.jar:?]
     [java]     at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:96) ~[portal-kernel.jar:?]
     [java]     ... 12 more
```
Test failure: https://testray.liferay.com/home/-/testray/case_results/1687228637

**Pull request closed without merging**
