### PR TITLE
[ServiceProxyFactory] LPS-188272 Inline CompositePasswordEncryptor into PasswordEncryptorUtil

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:security

**Comment by zhangyan0701** [comment]
Issue found:
Test [com.liferay.user.service.test.UserLocalServiceTest](https://testray.liferay.com/home/-/testray/case_results/2428792812) failed with error:
`testUpdatePasswordWithChangedAlgorithm: java.lang.NoSuchFieldException: No field on null with name _passwordEncryptor`

Full console log:
https://testray.liferay.com/reports/production/logs/2023-09/test-1-40/test-portal-acceptance-pullrequest(master)/6215/modules-integration-mysql57-jdk8/4/11/jenkins-console.txt.gz?authuser=0

**Comment by Kvale1733** [comment]
ci:close

**Comment by dantewang** [comment]
Resend https://github.com/liferay-core-infra/liferay-portal/pull/5733

**Pull request closed without merging**
