### PR TITLE
[Remove Blocking usages]LPS-200454 

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace blocking ServiceProxyFactory with Snapshot in class `UploadServletRequestImpl`. thanks.
https://liferay.atlassian.net/browse/LPS-200454

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
