### PR TITLE
LPS-138411

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

After discussionin https://github.com/liferay-core-infra/liferay-portal/pull/845#discussion_r888422958, Kyle has helped me to check the bugs in https://issues.liferay.com/browse/LPS-81724 with the unpatched updated version, and the bugs cannot be reproduce.
This is for ticket https://issues.liferay.com/browse/LPS-138411.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result again, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by jeffwu0724** [comment]
fixed the code conflict

**Comment by tinatian** [comment]
@jeffwu0724 As we talked, please resend.

Tina.

**Pull request closed without merging**
