### PR TITLE
[TS] LPS-196208

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
waiting for @yuhai's review to run test suites

**Comment by catarineaguiar** [comment]
no regressions found. Bug is not reproducible with these changes

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141450

**Pull request closed without merging**
