### PR TITLE
[Static references] LPS-182379 Remove static references from layout and knowledge-base modules

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:echo

**Comment by MrJohn1911** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
