### PR TITLE
[Remove Stream/Optional usage] LPS-171928 new_remove_stream_and_optional_in_saml_opensaml_integration

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Resend https://github.com/liferay-core-infra/liferay-portal/pull/2910.
This is for https://issues.liferay.com/browse/LPS-171928.
Thanks for checking.

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@jeffwu0724 semver error:

```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/dxp/apps/saml/saml-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.saml.runtime.certificate               MAJOR      1.0.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   interface  com.liferay.saml.runtime.certificate.CertificateTool
     [exec]     		>   method     getSubjectName(java.security.cert.X509Certificate)
     [exec]     			+   return     java.lang.String
     [exec]     			-   return     java.util.Optional
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 7.0.0
```
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/object/object-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.object.service                         MINOR      36.1.0     36.1.0     36.2.0     VERSION INCREASE REQUIRED
     [exec]     	<   class      com.liferay.object.service.ObjectRelationshipLocalServiceUtil
     [exec]     		+   method     getAllObjectRelationships(long)
     [exec]     			+   access     static
     [exec]     			+   return     java.util.List
     [exec]     	<   class      com.liferay.object.service.ObjectRelationshipLocalServiceWrapper
     [exec]     		+   method     getAllObjectRelationships(long)
     [exec]     			+   return     java.util.List
     [exec]     	<   interface  com.liferay.object.service.ObjectRelationshipLocalService
     [exec]     		+   method     getAllObjectRelationships(long)
     [exec]     			+   access     abstract
     [exec]     			+   annotated  com.liferay.portal.kernel.transaction.Transactional
     [exec]     				+   property   propagation='SUPPORTS'
     [exec]     				+   property   readOnly=true
     [exec]     			+   return     java.util.List
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 53.0.0
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-37/test-portal-acceptance-pullrequest(master)/7729/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by catarineaguiar** [comment]
regression found:

```
  [exec] 
     [exec] > Task :dxp:apps:saml:saml-opensaml-integration:compileTestJava FAILED
     [exec] 
     [exec] > Task :dxp:apps:saml:saml-opensaml-integration:processTestResources			samlPeerBindingLocalService.fetchSamlPeerBinding(
     [exec] > Task :dxp:apps:saml:saml-persistence-service:autoUpdateXml SKIPPED
     [exec] Gradle build finished at 2023-01-05 15:26:16.236.
     [exec] 
     [exec] 			                           ^
     [exec]     method com.liferay.saml.persistence.service.SamlPeerBindingLocalService.fetchSamlPeerBinding(long) is not applicable
     [exec]       (actual and formal argument lists differ in length)
     [exec]     method com.liferay.saml.persistence.service.SamlPeerBindingLocalService.fetchSamlPeerBinding(long,boolean,java.lang.String,java.lang.String,java.lang.String,java.lang.String) is not applicable
     [exec]       (actual and formal argument lists differ in length)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-37/test-portal-acceptance-pullrequest(master)/7742/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
Hey @catarineaguiar , seems like this [regression](https://github.com/liferay-core-infra/liferay-portal/pull/2925#issuecomment-1372486441) is directly caused by https://github.com/brianchandotcom/liferay-portal/commit/9130ef197fd312949521175de8ef48f678499f82, you can also see https://github.com/brianchandotcom/liferay-portal/compare/9c2de4f56c...9130ef197f.
Could you please help me double-check?
Thanks!

**Comment by catarineaguiar** [comment]
@jeffwu0724 I double-checked and it is in upstream too. Thanks for checking.

**Comment by tinatian** [comment]
@jeffwu0724 Closed as we talked, please resend

**Pull request closed without merging**
