### PR TITLE
LPS-151639 Move module.framework properties to system properties

### PR DESCRIPTION
**Pull request by dantewang**
@W2jx I rearranged some commits and made some simple changes out of https://github.com/dantewang/liferay-portal/pull/2216. Especially, could you put 44db291c and 98e22e31 together in one commit? Thanks!

@yuhai Please help me review the changes, thanks!

@vicnate5 I believe there are more functional tests that need to be updated. Could you help @W2jx with it? Thanks!

cc @tinatian

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:lpkg

**Comment by vicnate5** [comment]
@tinatian @dantewang @W2jx  I have some concerns about this change.

1. Users who are already setting `liferay.home` to a directory outside of the default (tomcat's parent directory).

Previously, this works without issue (I confirmed). In the case of this change, `VerifyProperties` warns the user about the migration, but only can warn the user who is setting their liferay.home to the default value.

If they were to boot portal to the changes here (not knowing about the migration), they will NOT get the `VerifyProperties` warning since it will fail before the information is printed to log. Portal will just fail to start without clear explanation. Might apply to other migrated properties too if they are read before `VerifyProperties`.

2. But then, for the same user as above, how do we set properties for the Upgrade tool?

After setting my liferay.home during ./db_upgrade.sh execution, it fails to run:
```
ERROR Unable to write to stream null/../logs/liferay.%d{yyyy-MM-dd}.log for appender TEXT_FILE org.apache.logging.log4j.core.appender.AppenderLoggingException: Error writing to stream null/../logs/liferay.%d{yyyy-MM-dd}.log
```

3. Does this migrate properties during the upgrade execution?

Even with default liferay.home, following error happens during upgrade
```
ERROR [main][DefaultCompanyNameSwapper:93] bundle com.liferay.portal.properties.swapper:5.0.11 (89)[com.liferay.portal.properties.swapper.internal.DefaultCompanyNameSwapper(21362)] : The activate method has thrown an exception
     [java] java.lang.ArrayIndexOutOfBoundsException: 0
     [java] 	at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:388) ~[?:1.8.0_265]
     [java] 	at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:397) ~[?:1.8.0_265]
     [java] 	at com.liferay.portal.util.PortalInstances.getDefaultCompanyId(PortalInstances.java:207) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.properties.swapper.internal.DefaultCompanyNameSwapper.activate(DefaultCompanyNameSwapper.java:52) ~[?:?]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
     [java] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228) ~[bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) ~[bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664) ~[bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:310) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:300) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:341) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:983) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:956) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:765) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1053) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1007) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1216) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1137) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:944) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:880) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1168) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:125) [bundleFile:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:891) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:487) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:1004) [org.eclipse.osgi.jar:?]
     [java] 	at com.liferay.portal.tools.DBUpgrader._registerModuleServiceLifecycle(DBUpgrader.java:256) [portal-impl.jar:?]
     [java] 	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:133) [portal-impl.jar:?]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
     [java] 	at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:54) [com.liferay.portal.tools.db.upgrade.client.jar:?]
```

4. Does this impact the Patching tool? (we still provide hotfixes for 7.4)

In my testing with the home directory not being in the default location, auto-discovery fails. I need to set manually, cannot fully test at the moment since this is not merged and I need to try with a real patch.

**Comment by yuhai** [comment]
Just send one SF changes to https://github.com/W2jx/liferay-portal/pull/2.

cc @dantewang, @tinatian

**Comment by W2jx** [comment]
Hi @vicnate5 ,We have found the reason of the problem, and have a solution, we will deal with it as soon as possible.
  
   Reason: The root issue is that we didn't define "liferay.home" during setting properties fromsystem.properties. 
The generated "liferay.home" is different from the customer already set. So it can't find osgi/data/deploy.. folders. Since loading system.properties should be dependent with loading portal.properties. The customers still set these properties in portal-ext.properties because they don't know the change. 
    Solution: Set these migrated properties to map or like _MIGRATED_PORTAL_KEYS of VerifyProperties. When setting properties from portal.properties, check if the key contains migrated properties. If so, output the error log to warn the user about changes.

**Comment by W2jx** [comment]
Hi @vicnate5 ,We have found the reason of the problem, and have a solution, we will deal with it as soon as possible.
  
   Reason: The root issue is that we didn't define "liferay.home" during setting properties fromsystem.properties. 
The generated "liferay.home" is different from the customer already set. So it can't find osgi/data/deploy.. folders. Since loading system.properties should be dependent with loading portal.properties. The customers still set these properties in portal-ext.properties because they don't know the change. 
    Solution: Set these migrated properties to map or like _MIGRATED_PORTAL_KEYS of VerifyProperties. When setting properties from portal.properties, check if the key contains migrated properties. If so, output the error log to warn the user about changes.

cc @dantewang

**Comment by dantewang** [comment]
@W2jx For `VerifyProperties`, I remember that Tina mentioned to make it directly kill the portal process when it detects the outdated portal properties.

**Comment by W2jx** [comment]
@dantewang VerifyProperties is loaded later than the properties are used, and it only displays error log, does not kill the portal process

**Comment by tinatian** [comment]
@dantewang @W2jx Code conflicts, please resend.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
