### PR TITLE
[Remove Blocking usages]LPS-192590 portal-search | ReindexSingleIndexerBackgroundTaskExecutor

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(8/21 8:38)

**Comment by dantewang** [comment]
@W2jx Let's describe the reason that we don't use hard reference by referencing the same tickets or PRs or commits which changed it to a reference and then changed it to `ServiceProxyFactory`.

**Review by dantewang — CHANGES_REQUESTED** [review]
@W2jx Please modify commit message, thanks!

**Comment by W2jx** [comment]
Hi @dantewang , I have modified the commit message.

**Comment by W2jx** [comment]
only modify commit message, no need to rerun test

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Comment by W2jx** [comment]
ci:forward:force

**Comment by W2jx** [comment]
ci:forward:force

**Pull request closed without merging**
