### PR TITLE
[Test Fix] LPD-26422 Fix PortalSmoke#SmokeWithEmbeddedHypersonic functional test

### PR DESCRIPTION
**Pull request by julschong**
@vicnate5
Hi Victor,
Please see this ticket for details: https://liferay.atlassian.net/browse/LPD-26422

Is it ok to just turn `test.liferay.virtual.instance` off for these 2 functional tests?

Thanks!

cc. @tinatian

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:core-functional

**Comment by julschong** [comment]
pushed sf fix only, other test result still applies

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:report:42027422

**Comment by julschong** [comment]
ci:test:smoke

**Comment by julschong** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@julschong makes sense

**Comment by julschong** [comment]
ci:test:smoke

**Comment by julschong** [comment]
retriggering smoke due to ci outage

**Comment by julschong** [comment]
added 2nd commit to move test out from quarantine [411c2a5](https://github.com/liferay-core-infra/liferay-portal/pull/7273/commits/411c2a56d21b4a528eeaa23bf95656d16b955df2)

**Comment by julschong** [comment]
smoke test is running on my repo: https://github.com/julschong/liferay-portal/pull/1306

**Comment by julschong** [comment]
ci:test:smoke

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
