### PR TITLE
[Replace Non-Blocking Usage] LPS-199976 kernel/search

### PR DESCRIPTION
**Pull request by haydenzheng314**
Resend to fix test, previous: https://github.com/liferay-core-infra/liferay-portal/pull/5972
Ticket: https://liferay.atlassian.net/browse/LPS-199976
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
Can't download the bundle for some reason. Going to regenerate to verify https://testray.liferay.com/home/-/testray/case_results/2450305981

**Comment by Kvale1733** [comment]
ci:test:bundle

**Comment by Kvale1733** [comment]
@LisztLiszt No regressions found.

**Comment by dantewang** [comment]
ci:test:upgrade

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@LisztLiszt @JanisZhang It seems both of you are modifying the same test?

https://github.com/liferay-core-infra/liferay-portal/pull/5983/commits/174abf6767ac77b23ce202da5fca921e30821ef8

**Comment by JanisZhang** [comment]
@dantewang Yes, we registered different services to fix test, and I've modified the commit message in https://github.com/liferay-core-infra/liferay-portal/pull/5983 to include the breaking change report.

**Comment by catarineaguiar** [comment]
no regressions on upgrade suite

**Comment by LisztLiszt** [comment]
@dantewang I have rebased to fix the confilct in IndexableActionableDynamicQueryTest

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143368

**Pull request closed without merging**
