### PR TITLE
LPS-167572 osgi config files are read from other osgi directories ides osgi/configs

### PR DESCRIPTION
**Pull request by thienquach87**
@dantewang

Thank you for nice feedback on https://github.com/liferay-core-infra/liferay-portal/pull/2450 PR. Based on it I updated code and resent here. Please help review and leave your comments. ear_of_rice

Regards,
Thien

### CODE REVIEW

**Comment by dantewang** [comment]
@zhangyan0701 Could you check if this affects the symbol link support? Thanks!

**Review by dantewang — APPROVED** [review]
@thienquach87 Code itself looks good, wait for QA to verify.

**Comment by thienquach87** [comment]
Hey @zhangyan0701,

I did your test-case based on your guides, but the configuration is loaded succesfully. Could you help double check?

Here are my steps:
My local env:
  Bundle's path: /home/ces-user/thien.quach/work-space/bundles
Steps to re-produce:
  Step 1: Add the attached osgi config file in ticket LPS-167572 to /osgi/configs folder.
  Step 2: Create a symbolic link to liferay home directory, I used command "ln -s liferay_home_dir symbolic_link_dir" on Ubuntu.        
            _ln -s /home/ces-user/thien.quach/work-space/bundles /home/ces-user/thien.quach/work-space/symbolic_link_dir_
  Step 3: Set the symbolic link directory as the value for liferay.home property in portal-ext.properties file.
      Add _liferay.home=/home/ces-user/thien.quach/work-space/symbolic_link_dir_ line to /home/ces-user/thien.quach/work-space/symbolic_link_dir/portal-ext.properties file 
Step 4: Start portal 
           cd /home/ces-user/thien.quach/work-space/bundles/tomcat-9.0.65/bin
           execute command:  ./catalina.sh jpda run to start server
Step 5: Check result on both MSQL and HSQL enviroments.

**Comment by zhangyan0701** [comment]
Hi @thienquach87 

The config file still cannot be loaded for me with the same steps. I was testing on MySQL 8.0. I downloaded the bundle from [here](https://github.com/liferay-core-infra/liferay-portal/pull/2471#issuecomment-1318313844) and testing with an empty database.

**Comment by thienquach87** [comment]
ci:test:sf

**Comment by thienquach87** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Hi @thienquach87 

I tested again with the same steps in https://github.com/liferay-core-infra/liferay-portal/pull/2471#issuecomment-1318736118, but the config files still cannot be read. I was testing with the bundle that generated in the most recently relevant job https://github.com/liferay-core-infra/liferay-portal/pull/2471#issuecomment-1323739835 and ant all bundle on my local.

**Comment by thienquach87** [comment]
Hello @zhangyan0701,

Could I contact to you on Slack directly? Can I have your Slack's account?

Thank you!

**Comment by thienquach87** [comment]
ci:test:sf

**Comment by thienquach87** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found in the newest relevant tests.

And manual testing with symbol link passed with the bundle here: https://github.com/liferay-core-infra/liferay-portal/pull/2471#issuecomment-1328797638, the config file was loaded, the configuration was added into database and was correct in System Settings.

**Comment by dantewang** [comment]
@thienquach87 See https://github.com/liferay-core-infra/liferay-portal/pull/2580

**Pull request closed without merging**
