### PR TITLE
Rename classes in module:commerce]Lps 166981

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-166981

### CODE REVIEW

**Review by yuhai — APPROVED** [review]
@dantewang, the code looks good to me. Please wait for QA engineer to check the test result.

**Comment by yuhai** [comment]
@zhangyan0701,  could you please check the test result?

@slnn, your last commit message lacks one space. Please edit it and push force it.

Thanks,
Hai

**Comment by slnn** [comment]
> @zhangyan0701, could you please check the test result?
> 
> @slnn, your last commit message lacks one space. Please edit it and push force it.
> 
> Thanks, Hai

Done

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:commerce

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@shuyangzhou Does this look good for renaming XXXTracker to XXXRegistry? If so, I'll forward such PRs later.

cc @tinatian

**Comment by shuyangzhou** [comment]
@dantewang it looks fine, please proceed, thanks!

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
