### PR TITLE
[Remove Stream/Optional usage] LPS-172250 remove_stream_and_optional_in_portal_search_solr8_impl

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-172250.
Thanks for checking!

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:search-solr

**Comment by catarineaguiar** [comment]
ci:test:search-solr

**Comment by zhangyan0701** [comment]
ci:test:search-solr

**Comment by Kvale1733** [comment]
@jeffwu0724 Regressions found. 

Unexpected comma error in several solr8 tests. For example

com.liferay.portal.search.solr8.internal.facet.ModifiedFacetTest
```
 [exec] com.liferay.portal.search.solr8.internal.facet.ModifiedFacetTest > testRanges FAILED
     [exec]     org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8983/solr: org.noggit.JSONParser$ParseException: Unexpected comma: char=,,position=139 AFTER='O 19990101010101]","excludeTags":"modified","type":"query"}},' BEFORE='{"modified_[11110101010101 TO 222202020'
     [exec]         at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:681)
     [exec]         at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:266)
     [exec]         at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:248)
     [exec]         at org.apache.solr.client.solrj.impl.LBSolrClient.request(LBSolrClient.java:607)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-39/test-portal-acceptance-pullrequest(master)/2184/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
@jeffwu0724 Steps to reproduce locally

i. Setup solr8 locally (ant -f build-test-solr.xml start-solr)
ii. Startup portal
iii. Go to Control Panel > Users and Organizations
iv. Create user with full name userfn userln (can use any screen name and email)
v. Go to default Home page
vi. Use the search widget to search "userfn userln"

Expected Results: User shows up in results
Actual Results: The Above error appears and user is not shown in results.

**Pull request closed without merging**
