### PR TITLE
[Remove Stream/Optional usage] LPS-171708 test_remove_usage_of_stream_on_object_rest_impl

### PR DESCRIPTION
**Pull request by dantewang**
@jeffwu0724

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:object

**Comment by dantewang** [comment]
ci:test:headless

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128786

**Pull request closed without merging**
