### PR TITLE
[Circular dependency]Lps 186384 8 1

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-186384

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:object

**Comment by catarineaguiar** [comment]
@slnn regression found:

```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/object/object-admin-rest-test/src/testIntegration/java/com/liferay/object/admin/rest/resource/v1_0/test/ObjectDefinitionResourceTest.java:253: error: incompatible types: com.liferay.object.model.ObjectRelationship cannot be converted to com.liferay.object.admin.rest.client.dto.v1_0.ObjectField
     [exec] 			_objectRelationshipLocalService.addObjectRelationship(
     [exec] 			                                                     ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/object/object-admin-rest-test/src/testIntegration/java/com/liferay/object/admin/rest/resource/v1_0/test/ObjectDefinitionResourceTest.java:272: error: incompatible types: com.liferay.object.admin.rest.client.dto.v1_0.ObjectField cannot be converted to com.liferay.object.model.ObjectRelationship
     [exec] 		_objectDefinitionLocalService.enableAccountEntryRestricted(objectField);
     [exec] 		                                                           ^
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-08/test-1-27/test-portal-acceptance-pullrequest(master)/9375/modules-compile-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:object

**Comment by slnn** [comment]
> @slnn regression found:
> 
> ```
>      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/object/object-admin-rest-test/src/testIntegration/java/com/liferay/object/admin/rest/resource/v1_0/test/ObjectDefinitionResourceTest.java:253: error: incompatible types: com.liferay.object.model.ObjectRelationship cannot be converted to com.liferay.object.admin.rest.client.dto.v1_0.ObjectField
>      [exec] 			_objectRelationshipLocalService.addObjectRelationship(
>      [exec] 			                                                     ^
>      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/object/object-admin-rest-test/src/testIntegration/java/com/liferay/object/admin/rest/resource/v1_0/test/ObjectDefinitionResourceTest.java:272: error: incompatible types: com.liferay.object.admin.rest.client.dto.v1_0.ObjectField cannot be converted to com.liferay.object.model.ObjectRelationship
>      [exec] 		_objectDefinitionLocalService.enableAccountEntryRestricted(objectField);
>      [exec] 		                                                           ^
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2023-08/test-1-27/test-portal-acceptance-pullrequest(master)/9375/modules-compile-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

Thank @catarineaguiar for catching this! I have fixed it and retrigger tests.

**Comment by slnn** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
ci:test:frontend-data-set

**Comment by catarineaguiar** [comment]
no regressions found

**Review by dantewang — CHANGES_REQUESTED** [review]
@slnn Could you add a public API that everyone can call to encapsulate the add-relationship-and-deploy-definition logic? The new API can have the same parameters as the original addRelationship method so that you can replace them directly.

**Comment by slnn** [comment]
OK, got it

**Comment by slnn** [comment]
Please see https://github.com/liferay-core-infra/liferay-portal/pull/5209

**Pull request closed without merging**
