### PR TITLE
LPS-149982

### PR DESCRIPTION
**Pull request by vicnate5**
Full testing already run. Only regression in release builds should be fixed here. See details in https://github.com/liferay-core-infra/liferay-portal/pull/491#issue-1177064736. CC @jorgediaz-lr

### CODE REVIEW

**Comment by vicnate5** [comment]
I killed the acceptance run since it is high cost and the previous test run did not have any regressions.

Will just check the relevant results here.

**Comment by vicnate5** [comment]
@tinatian this should be good to go. I will take care of reverting the last commit after everything gets merged.

**Comment by shuyangzhou** [comment]
@jorgediaz-lr please rebase

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:stop

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@jorgediaz-lr forwarded by accident, please rebase, otherwise Brian won't merge it.

**Comment by jorgediaz-lr** [comment]
Hi @shuyangzhou 

I have rebased and sent again here: https://github.com/liferay-core-infra/liferay-portal/pull/595

**Comment by jorgediaz-lr** [comment]
ci:close

**Pull request closed without merging**
