### PR TITLE
[Cleanup Portal Interface]Lps 193189

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-193189

This pull includes https://github.com/liferay-core-infra/liferay-portal/pull/5181

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:license

**Comment by Kvale1733** [comment]
ci:test:license

**Comment by dantewang** [comment]
@slnn Also conflicts.Please resend after the Expando part is merged, thanks!

**Comment by slnn** [comment]
The Expando part has been merged, resend this one in https://github.com/liferay-core-infra/liferay-portal/pull/5307

**Pull request closed without merging**
