### PR TITLE
LPS-177264 Default user should always respect "company.default.locale…

### PR DESCRIPTION
**Pull request by tinatian**
…" and "company.default.time.zone"

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:friendly-url

**Comment by vicnate5** [comment]
ci:test:db-partition

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:friendly-url

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132337

**Pull request closed without merging**
