### PR TITLE
LPS-164866 Remove_commerce_enterprise_support_part 5

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:commerce

**Comment by jeffwu0724** [comment]
fixed the code conflict and forced pushed

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Possible regressions:
1. Warehouses portlet is unavailable. Steps: Go to Application menu > Commerce > Warehouses.
And error in portal console:
```
2022-10-18 07:26:58.231 ERROR [http-nio-8080-exec-7][PortletRequestDispatcherImpl:304] Unable to dispatch request: java.lang.NullPointerException
2022-10-18 07:26:58.232 ERROR [http-nio-8080-exec-7][PortletServlet:117] null
javax.portlet.PortletException: org.apache.jasper.JasperException: java.lang.NullPointerException
```
Full console log:
https://testray.liferay.com/reports/production/logs/2022-10/test-1-38/test-portal-acceptance-pullrequest(master)/4314/functional-tomcat90-mysql57-jdk8/2/7/jenkins-console.txt.gz?authuser=0

2. [portal-license-smoke-jdk8/0/0](https://testray.liferay.com/home/-/testray/cases/1553010614) failed with error:
```
    [junit] 2022-10-17 20:41:01.242 WARN  [main][SystemCheckOSGiCommands:134] Declarative Service Unsatisfied Component Checker check result: 
    [junit] Bundle {id: 1426, name: com.liferay.site.initializer.extender, version: 1.0.64}
    [junit] 	Declarative Service {id: 3960, name: com.liferay.site.initializer.extender.internal.CommerceSiteInitializer, unsatisfied references: 
    [junit] 		{name: _catalogResourceFactory, target: null}
    [junit] 		{name: _channelResourceFactory, target: null}
    [junit] 		{name: _commerceAccountRoleHelper, target: null}
    [junit] 		{name: _commerceCatalogLocalService, target: null}
    [junit] 		{name: _commerceChannelLocalService, target: null}
    [junit] 		{name: _commerceChannelService, target: null}
    [junit] 		{name: _commerceCurrencyLocalService, target: null}
    [junit] 		{name: _commerceInventoryWarehousesImporter, target: null}
    [junit] 		{name: _commerceNotificationTemplateLocalService, target: null}
    [junit] 		{name: _commercePriceEntryLocalService, target: null}
    [junit] 		{name: _commercePriceListLocalService, target: null}
    [junit] 		{name: _cpDefinitionLocalService, target: null}
    [junit] 		{name: _cpDefinitionsImporter, target: null}
    [junit] 		{name: _cpInstanceLocalService, target: null}
    [junit] 		{name: _cpMeasurementUnitLocalService, target: null}
    [junit] 		{name: _cpOptionLocalService, target: null}
    [junit] 		{name: _cpOptionsImporter, target: null}
    [junit] 		{name: _cpSpecificationOptionsImporter, target: null}
    [junit] 		{name: _portletSettingsImporter, target: null}
    [junit] 		{name: _productOptionResourceFactory, target: null}
    [junit] 		{name: _productSpecificationResourceFactory, target: null}
    [junit] 	}
```
Full console log:
https://testray.liferay.com/reports/production/logs/2022-10/test-1-37/test-portal-acceptance-pullrequest(master)/5702/portal-license-smoke-jdk8/0/0/jenkins-console.txt.gz?authuser=0

3. [modules-semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2008488614) failed with error:
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/commerce/commerce-test-util] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.commerce.test.util.order.status        CHANGED    1.0.0      1.0.0      1.0.1      VERSION INCREASE REQUIRED
     [exec]     	~   class      com.liferay.commerce.test.util.order.status.Test1CommerceOrderStatusImpl
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   enabled=false
     [exec]     	~   class      com.liferay.commerce.test.util.order.status.Test2CommerceOrderStatusImpl
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   enabled=false
     [exec]     	~   class      com.liferay.commerce.test.util.order.status.Test3CommerceOrderStatusImpl
     [exec]     		~   annotated  org.osgi.service.componen
```
Full console log:
https://testray.liferay.com/reports/production/logs/2022-10/test-1-37/test-portal-acceptance-pullrequest(master)/5702/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:commerce

**Comment by jeffwu0724** [comment]
Hi @zhangyan0701 , could you please help me to scan the result again when it is ready?
Thanks!

**Comment by zhangyan0701** [comment]
Hi @jeffwu0724 

Issue 1 and 3 in this comment https://github.com/liferay-core-infra/liferay-portal/pull/2013#issuecomment-1281935680 are still reproducible.

Issue1:
Warehouses portlet is unavailable.
after4

Example test:
[LocalFile.CPCommerceWarehouses#CanSFUsersWithoutWarehouseViewPermissionSeeDecreasedStockQuantity](https://testray.liferay.com/home/-/testray/case_results/2009961331)
Jenkins console:
https://testray.liferay.com/reports/production/logs/2022-10/test-1-31/test-portal-acceptance-pullrequest(master)/5504/functional-tomcat90-mysql57-jdk8/2/5/jenkins-console.txt.gz?authuser=0

Issue3:
[modules-semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2009945474) has error:
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/commerce/commerce-test-util] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.commerce.test.util.order.status        CHANGED    1.0.0      1.0.0      1.0.1      VERSION INCREASE REQUIRED
     [exec]     	~   class      com.liferay.commerce.test.util.order.status.Test1CommerceOrderStatusImpl
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   enabled=false
     [exec]     	~   class      com.liferay.commerce.test.util.order.status.Test2CommerceOrderStatusImpl
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   enabled=false
     [exec]     	~   class      com.liferay.commerce.test.util.order.status.Test3CommerceOrderStatusImpl
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   enabled=false
```
Full console:
https://testray.liferay.com/reports/production/logs/2022-10/test-1-38/test-portal-acceptance-pullrequest(master)/4357/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:commerce

**Comment by jeffwu0724** [comment]
fixed the bug mentioned [here](https://github.com/liferay-core-infra/liferay-portal/pull/2013#issuecomment-1283877439)

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by jeffwu0724** [comment]
fixed the code conflict

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125000

**Pull request closed without merging**
