### PR TITLE
[Component with its own class name as service type ] LPS-194013 Refactor Registry classes from Dynamic Data Mapping module

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**
This PR linked [LPS-194013](https://github.com/liferay-core-infra/liferay-portal/pull/5382)

### CODE REVIEW

**Review by rafaprax — APPROVED** [review]

**Comment by catarineaguiar** [comment]
ci:test:data-engine

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
No regressions found.

But there is a SF failure in DDMDisplayRegistryUtil.java:
` /opt/dev/projects/github/liferay-portal/modules/apps/dynamic-data-mapping/dynamic-data-mapping-api/src/main/java/com/liferay/dynamic/data/mapping/util/DDMDisplayRegistryUtil.java expected:<...opyrightText: (c) 20[23] Liferay, Inc. https...> but was:<...opyrightText: (c) 20[00] Liferay, Inc. https...>`

**Comment by GabrielHenriquedev** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
SF issue doesn't seem related anymore.

**Comment by shuyangzhou** [comment]
@GabrielHenriquedev Inline DDMStructureIndexerRegistryUtil into DDMStructureLocalServiceImpl. And put `DDMStructureIndexer ddmStructureIndexer` into the message as an attribute, https://github.com/liferay-core-infra/liferay-portal/pull/5435/commits/513a52492f2ad4140c7375bfdcea9c1e618f3c25#diff-16ae57c3551c581526e9e38466853c78ab9b5afde254ff07ec39b8dbf529a2d0R1995 , then get it back from the listener, so that the listener won't need to look up from the util anymore.

**Pull request closed without merging**
