### PR TITLE
LPS-145579 Remove LocalizationUtil usages from modules final part 4

### PR DESCRIPTION
**Pull request by julschong**
@tinatian 
Hi Tina,
this is resubmitted from #1871
Only updated commit message for the [inline commit](https://github.com/liferay-core-infra/liferay-portal/pull/1904/commits/720c10f93380ba2d68342e6d8a751bb82b718542)
Thank you!

### CODE REVIEW

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by julschong** [comment]
rebase to test sf again

**Comment by julschong** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@shuyangzhou This pull is ready to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/124629

**Pull request closed without merging**
