### PR TITLE
LPS-200537 Remove DefaultControlPanelEntry from util-spring

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://liferay.atlassian.net/browse/LPS-200537.
There is a protal-properties `#control.panel.default.entry.class=com.liferay.portal.kernel.portlet.DefaultControlPanelEntry` in portal.properties, which "remains here only as a reference", and only used in https://github.com/liferay/liferay-portal/blob/5e0cf78cc6a36ab268036d8e3fe803805d9410ba/portal-impl/src/com/liferay/portal/deploy/hot/HookHotDeployListener.java#L1257-L1272
As it said to leave it as a reference, I am not sure if we should remove it.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
fixed the code conflict

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/3/23 8:57am

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/6/23 8:26am

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/9/23 9:26am

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/13/23 8:04am

**Comment by jeffwu0724** [comment]
checked, no code conflict at 11/14/23 8:37am

**Comment by tinatian** [comment]
@jeffwu0724 
Before your change, two ways can change the default ControlPanelEntry, one is by modifying liferay-hook.xml and override property "control.panel.default.entry.class", another way is to register a service of ControlPanelEntry without "javax.portlet.name" property defined.

After your change, there is no way to override the default ControlPanelEntry unless you modify PortletImpl class.

I am OK that you removed the way that overriding by liferay-hook.xml and property "control.panel.default.entry.class", but we need to keep a way to let people to override the default one by registering a ControlPanelEntry service without "javax.portlet.name".

Please resend.

Thanks.
Tina

**Pull request closed without merging**
