### PR TITLE
[Move Expando-upgrade-module]Lps 190836 12 14 module

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-190836

Compare with this pull: https://github.com/liferay-core-infra/liferay-portal/pull/6203, I apply these changes in this pull:

1. Remove "dependency-injector="ds" from the service.xml of Expando as the default value of the injector is ds
2. According to https://help.liferay.com/hc/en-us/articles/360035581451-Introduction-to-Cache-Configuration, move these expando related ehcahe configs from liferay-multi-vm.xml to the module-multi-vm.xml in expando-service

### CODE REVIEW

**Comment by slnn** [comment]
Forcecd push to solve conflicts

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:upgrade

**Comment by slnn** [comment]
ci:test

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Forced push to update sematic version

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:upgrade

**Comment by slnn** [comment]
ci:test:upgrade

**Comment by slnn** [comment]
Forced push to resolve the conflicts on bnd file and fix the failed of ServiceBuilder test which caused by rebasing master without rerun build-service for the expando-service module as https://liferay.atlassian.net/browse/LPS-201769 has been merged into master which aims to optimize ServiceBuilder generated database indexes

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:upgrade

**Comment by slnn** [comment]
ci:stop

**Comment by yuhai** [comment]
@slnn, I didn't check our talked changes yet. Please also remove the commit https://github.com/liferay-core-infra/liferay-portal/pull/6322/commits/88e16e13f5976a3fdc7139661c638de9af001762. And then use the below way `registry.registerReleaseCreationUpgradeSteps`.

In ExpandoServiceUpgradeStepRegistrator class.
```
public void register(Registry registry) {
registry.registerReleaseCreationUpgradeSteps(
	new ReleaseCreationUpgrade("com.liferay.expando.service", _releaseLocalService));

registry.register("0.0.1", "1.0.0", new UpgradePackages());
}
```
And then do the below codes to add the release data.

```
public class ReleaseCreationUpgrade implements UpgradeStep {
		public ReleaseCreationUpgrade(
				String newServletContextName, ReleaseLocalService releaseLocalService) {

			_newServletContextName = newServletContextName;
			_releaseLocalService = releaseLocalService;
		}

		@Override
		public void upgrade() {
			Release release = _releaseLocalService.fetchRelease(_newServletContextName);

			if (release == null) {
				_releaseLocalService.addRelease(_newServletContextName, "0.0.1");
			}
		}

		private final String _newServletContextName;
		private final ReleaseLocalService _releaseLocalService;
	}
```

**Comment by yuhai** [comment]
@slnn,

Please rename `UpgradePackages` for `UpgradeClassNames` or `ClassNamesUpgradeProcess` since its super class is UpgradeProcess.
Please rename `ReleaseCreationUpgrade` for `ReleaseCreationUpgradeStep`. You may make it as private class, and then releaseLocalService is unnecessary as constructor parameter.

For the `UpgradePackages` class, please refer to `com.liferay.client.extension.internal.upgrade.v3_0_0.ClassNamesUpgradeProcess`. Just like:
```
@Override
	protected void doUpgrade() throws UpgradeException {
		super.doUpgrade();

		try {
			upgradeTable(
				"ResourcePermission", "primKey", _CLASS_NAMES,
				WildcardMode.TRAILING, true);
		}
		catch (Exception exception) {
			throw new UpgradeException(exception);
		}
	}

	@Override
	protected String[][] getResourceNames() {
		return _RESOURCE_NAMES;
	}

	@Override
	protected String[][] getClassNames() {
		return _CLASS_NAMES;
	}

	private static final String[][] _CLASS_NAMES = {
		{"com.liferay.expando.kernel.model.", "com.liferay.expando.model."}
	};

	private static final String[][] _RESOURCE_NAMES = new String[0][0];

```

**Comment by slnn** [comment]
> @slnn, I didn't check our talked changes yet. Please also remove the commit [88e16e1](https://github.com/liferay-core-infra/liferay-portal/commit/88e16e13f5976a3fdc7139661c638de9af001762). And then use the below way `registry.registerReleaseCreationUpgradeSteps`.
> 
> In ExpandoServiceUpgradeStepRegistrator class.
> 
> ```
> public void register(Registry registry) {
> registry.registerReleaseCreationUpgradeSteps(
> 	new ReleaseCreationUpgrade("com.liferay.expando.service", _releaseLocalService));
> 
> registry.register("0.0.1", "1.0.0", new UpgradePackages());
> }
> ```
> 
> And then do the below codes to add the release data.
> 
> ```
> public class ReleaseCreationUpgrade implements UpgradeStep {
> 		public ReleaseCreationUpgrade(
> 				String newServletContextName, ReleaseLocalService releaseLocalService) {
> 
> 			_newServletContextName = newServletContextName;
> 			_releaseLocalService = releaseLocalService;
> 		}
> 
> 		@Override
> 		public void upgrade() {
> 			Release release = _releaseLocalService.fetchRelease(_newServletContextName);
> 
> 			if (release == null) {
> 				_releaseLocalService.addRelease(_newServletContextName, "0.0.1");
> 			}
> 		}
> 
> 		private final String _newServletContextName;
> 		private final ReleaseLocalService _releaseLocalService;
> 	}
> ```
> 
> **Edit**: I want to further check the UpgradePackages change from the commit([f2c1443](https://github.com/liferay-core-infra/liferay-portal/commit/f2c14436fcf24d077ab953d9a2be15b8834c44bc)). You may firstly do the above mentioned changes or do this after waiting for me to finish my check. I will do this tomorrow.

Hi @yuhai 

Sorry for the delayed reply, commit https://github.com/liferay-core-infra/liferay-portal/commit/88e16e13f5976a3fdc7139661c638de9af001762  as its commit message said " `LPS-190836 Use ReleaseDAO.addRelease() to add the Expando Service related item in Release_ table before calling module upgrade process to avoid the SQLSyntaxErrorException during module upgrade process and increase the version of the core`
", it will do two things, one is to add expando -service related data for the Release_ table to avoid the SQLSyntaxErrorException and the other one is to upgrade portal version from 29.1.2 to 29.1.3 as we move out expando from core.

The solution you mentioned above, I think it will only add expando -service related data for the Release_ table.

By the way, I have forced push with the rename changes.

Thanks

Lily

**Comment by slnn** [comment]
> @slnn,
> 
> Please rename `UpgradePackages` for `UpgradeClassNames` or `ClassNamesUpgradeProcess` since its super class is UpgradeProcess. Please rename `ReleaseCreationUpgrade` for `ReleaseCreationUpgradeStep`. You may make it as private class, and then releaseLocalService is unnecessary as constructor parameter.
> 
> For the `UpgradePackages` class, please refer to `com.liferay.client.extension.internal.upgrade.v3_0_0.ClassNamesUpgradeProcess`. Just like:
> 
> ```
> @Override
> 	protected void doUpgrade() throws UpgradeException {
> 		super.doUpgrade();
> 
> 		try {
> 			upgradeTable(
> 				"ResourcePermission", "primKey", _CLASS_NAMES,
> 				WildcardMode.TRAILING, true);
> 		}
> 		catch (Exception exception) {
> 			throw new UpgradeException(exception);
> 		}
> 	}
> 
> 	@Override
> 	protected String[][] getResourceNames() {
> 		return _RESOURCE_NAMES;
> 	}
> 
> 	@Override
> 	protected String[][] getClassNames() {
> 		return _CLASS_NAMES;
> 	}
> 
> 	private static final String[][] _CLASS_NAMES = {
> 		{"com.liferay.expando.kernel.model.", "com.liferay.expando.model."}
> 	};
> 
> 	private static final String[][] _RESOURCE_NAMES = new String[0][0];
> ```

Forced push to call the super.doUpgrade(); instead of overwrite the doUpgrade() method.

/cc @yuhai

**Comment by yuhai** [comment]
@slnn, for the [commit ](https://github.com/liferay-core-infra/liferay-portal/pull/6322/commits/3a7d4b9919f22722a831043484e81cca6bc09a0d). I just realized the portal had provided the function to do this. Please use the below codes fragment.
```
upgradeVersionTreeMap.put(
			new Version(29, 1, 3),
			UpgradeModulesFactory.create(
				new String[] {"com.liferay.expando.service"}, null));
```
You may add breakpoint in the `com.liferay.portal.kernel.upgrade.util.UpgradeModules#addRelease`. And then check its call stack.

**Comment by slnn** [comment]
> @slnn, for the [commit ](https://github.com/liferay-core-infra/liferay-portal/pull/6322/commits/3a7d4b9919f22722a831043484e81cca6bc09a0d). I just realized the portal had provided the function to do this. Please use the below codes fragment.
> 
> ```
> upgradeVersionTreeMap.put(
> 			new Version(29, 1, 3),
> 			UpgradeModulesFactory.create(
> 				new String[] {"com.liferay.expando.service"}, null));
> ```
> 
> You may add breakpoint in the `com.liferay.portal.kernel.upgrade.util.UpgradeModules#addRelease`. And then check its call stack.

Done, I have run the upgrade process locally after applying this , it works on my side

**Review by yuhai — APPROVED** [review]
@dantewang, the upgrade part is good to me.

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:upgrade

**Comment by slnn** [comment]
ci:report:2488215758

**Comment by slnn** [comment]
From the test result, the failure of the SF was not caused by this pull.

**Comment by slnn** [comment]
ci:report:2488219458

**Pull request closed without merging**
