### PR TITLE
LPS-164640 move_commons-math3_to_shared-dependencies

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

I moved commons-math3 to shared-dependencies/shared-dependencies-apache-commons to make them more consistent.
Thanks for checking!

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by tinatian** [comment]
@jeffwu0724 Please rebase.

Tina

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@vicnate5 This pull changed build.gradle of portal-tika, any other change need to trigger to cover this changes?

Tina

**Comment by vicnate5** [comment]
ci:test:auto-tagging

**Comment by vicnate5** [comment]
ci:test:lima

**Comment by vicnate5** [comment]
ci:test:reports

**Comment by catarineaguiar** [comment]
ci:reevaluate:1267401_5668

**Comment by vicnate5** [comment]
None of these ended up on Testray, gonna rerun for the weekend

**Comment by vicnate5** [comment]
ci:test:auto-tagging

**Comment by vicnate5** [comment]
ci:test:reports

**Comment by vicnate5** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125736

**Pull request closed without merging**
