### PR TITLE
[Remove Stream/Optional usage] LPS-171928 new_remove_stream_and_optional_in_saml_opensaml_integration - part 1

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

As talked with Tina, I removed the use of AttributeValueWrapper in this PR, and only focusing on removing stream in DefaultAttributeResolver.java and AttributePublisherImpl.java
This is for https://issues.liferay.com/browse/LPS-171928.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:saml

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found. Only a semver issue.

```
  [exec] 
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/dxp/apps/saml/saml-opensaml-integration] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.saml.opensaml.integration.resolver     MAJOR      1.1.0      1.1.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   interface  com.liferay.saml.opensaml.integration.resolver.AttributeResolver$AttributePublisher
     [exec]     		-   method     buildBase64(java.lang.String)
     [exec]     			-   access     abstract
     [exec]     			-   return     com.liferay.saml.opensaml.integration.resolver.AttributeResolver$AttributePublisher$AttributeValue
     [exec]     		-   method     buildBoolean(boolean)
     [exec]     			-   access     abstract
     [exec]     			-   return     com.liferay.saml.opensaml.integration.resolver.AttributeResolver$AttributePublisher$AttributeValue
     [exec]     		-   method     buildDateTime(java.util.Date)
     [exec]     			-   access     abstract
     [exec]     			-   return     com.liferay.saml.opensaml.integration.resolver.AttributeResolver$AttributePublisher$AttributeValue
     [exec]     		-   method     buildInt(int)
     [exec]     			-   access     abstract
     [exec]     			-   return     com.liferay.saml.opensaml.integration.resolver.AttributeResolver$AttributePublisher$AttributeValue
     [exec]     		-   method     buildString(java.lang.String)
     [exec]     			-   access     abstract
     [exec]     			-   return     com.liferay.saml.opensaml.integration.resolver.AttributeResolver$AttributePublisher$AttributeValue
     [exec]     		-   method     buildURI(java.net.URI)
     [exec]     			-   access     abstract
     [exec]     			-   return     com.liferay.saml.opensaml.integration.resolver.AttributeResolver$AttributePublisher$AttributeValue
     [exec]     		-   method     publish(java.lang.String,com.liferay.saml.opensaml.integration.resolver.AttributeResolver$AttributePublisher$AttributeValue[])
     [exec]     			-   access     abstract
     [exec]     			-   return     void
     [exec]     		-   method     publish(java.lang.String,java.lang.String,com.liferay.saml.opensaml.integration.resolver.AttributeResolver$AttributePublisher$AttributeValue[])
     [exec]     			-   access     abstract
     [exec]     			-   return     void
     [exec]     		-   method     publish(java.lang.String,java.lang.String,java.lang.String,com.liferay.saml.opensaml.integration.resolver.AttributeResolver$AttributePublisher$AttributeValue[])
     [exec]     			-   access     abstract
     [exec]     			-   return     void
     [exec]     		+   method     publish(java.lang.String,java.lang.String,java.lang.String[])
     [exec]     			+   access     abstract
     [exec]     			+   return     void
     [exec]     	-   interface  com.liferay.saml.opensaml.integration.resolver.AttributeResolver$AttributePublisher$AttributeValue
     [exec]     		-   access     abstract
     [exec]     		-   access     static
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 6.0.0
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-32/test-portal-acceptance-pullrequest(master)/7781/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
force push with semantic version, the older result should be good enough

**Comment by tinatian** [comment]
@jeffwu0724 You did too much in one commit https://github.com/liferay-core-infra/liferay-portal/pull/2976/commits/4aa422945fa79fa66be682dbb9bfb5ba636cda88. Please separate into:
1. Remove unused methods
2. Remove wrapper

Tina

**Pull request closed without merging**
