### PR TITLE
LPS-188134 move Guava to shared-dependencies, and upgrade version to 32.0.1-jre

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This is for ticket https://liferay.atlassian.net/browse/LPS-188134.
Thanks for checking

### CODE REVIEW

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found. SF issue is unrelated.

**Comment by tinatian** [comment]
@jeffwu0724 As we talked, please resend.

Thanks.
Tina

**Comment by jeffwu0724** [comment]
ci:test:online-editing

**Comment by jeffwu0724** [comment]
Hey @Kvale1733 , could you please help me see if ci:test:online-editing pass in this PR?
Thanks

**Comment by Kvale1733** [comment]
@jeffwu0724 Since there is a conflict I need to run without rebase

**Comment by Kvale1733** [comment]
ci:test:online-editing:norebase

**Pull request closed without merging**
