### PR TITLE
LPS-196524 move class Snapshot to portal-kernel and remove unused dependency

### PR DESCRIPTION
**Pull request by JanisZhang**
resend. cc @W2jx
previous:https://github.com/liferay-core-infra/liferay-portal/pull/5623

https://liferay.atlassian.net/browse/LPS-196524

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141445

**Pull request closed without merging**
