### PR TITLE
LPS-194216 modules:layout-admin-web, dynamic-data-mapping-service, dynamic-data-library-service

### PR DESCRIPTION
**Pull request by JanisZhang**
This pull request is to clean up unused referenced fields.  Thanks!
https://liferay.atlassian.net/browse/LPS-194216

### CODE REVIEW

**Comment by dantewang** [comment]
@JanisZhang Where is this task from?

**Comment by JanisZhang** [comment]
Hi @dantewang, I noticed these unused fields while working on https://github.com/liferay-core-infra/liferay-portal/pull/5242.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@JanisZhang Change LGTM, could you please update the ticket title and description to reflect that? Thanks!

**Comment by Kvale1733** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
ci:test:document

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Comment by JanisZhang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/139718

**Pull request closed without merging**
