### PR TITLE
LPS-144173 Use compilyOnly approach to jFreeChart and JCommon

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
Hey @zhangyan0701,

Can you please help me to scan the test results?

Thx

**Comment by tinatian** [comment]
@koor4356 Please help me scan test results.

Thanks.
Tina.

**Comment by zhangyan0701** [comment]
Hi @rafaprax 

I have checked the tests results and no regressions found.

**Comment by tinatian** [comment]
Hi @rafaprax ,
The code looks good to me, I would like you do:

**Comment by tinatian** [comment]
Hi @rafaprax ,
The code looks good to me, here are something I would like you to do:
1. Rerun ant build-lib-versions and update this pull, and I rerun it locally and see versions-complete.xml is changed, and the change is related to your code.

**Comment by tinatian** [comment]
Hi @rafaprax ,
The code looks good to me, here are something I would like you to do:
1. Rerun `ant build-lib-versions` and update this pull, I rerun it locally and see `versions-complete.xml` is changed, and the change is related to your code.
2. I see we have usages like this, it is related to diff utils too, could you please check if we can use the new diff util module you created? I would like it to be consistent.
`testCompile group: "com.googlecode.java-diff-utils", name: "diffutils", version: "1.3.0"`
3. You added a new app `diff` in this pull, please check the steps here and make sure you follow the rules https://liferay.atlassian.net/wiki/spaces/TEAMRM/pages/1662878423/How+to+add+a+new+app+to+the+release+bundle.

Thanks.
Tina.

**Comment by tinatian** [comment]
Hi @rafaprax ,
The latest version of JFreeChar(https://mvnrepository.com/artifact/org.jfree/jfreechart/1.5.3) does not depend on jcommon. I would like you to do:
1. Upgrade JFreeChart to the latest version and remove jcommon.
2. Move JFreeChart out into separate module, as you are going to add a new app, please make sure you follow the rules here https://liferay.atlassian.net/wiki/spaces/TEAMRM/pages/1662878423/How+to+add+a+new+app+to+the+release+bundle
3. `.lfrbuild-packageinfo ` was used to avoid baseline error, you do not need to add it unless we have a baseline failure.

I am going to close this pull, please resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
