### PR TITLE
LPS-168945 Clean up and simplify SocialBookmarksRegistryImpl

### PR DESCRIPTION
**Pull request by W2jx**
Just resolve code conflicts.

Detail: https://github.com/liferay-core-infra/liferay-portal/pull/2615

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(2022/12/5 13:30)

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
@W2jx no regressions found.

**Comment by W2jx** [comment]
no conflicts(2022/12/7 9:40)

**Comment by W2jx** [comment]
no conflicts(2022/12/8 9:17)

**Comment by W2jx** [comment]
no conflicts(12/9 9:50)

**Comment by W2jx** [comment]
no conflicts(12/12 10:10)

**Pull request closed without merging**
