### PR TITLE
LPS-176210 Remove counterDataSource

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-176210 Remove counter data source
- LPS-176210 Remove counter session factory, it's not allowed for multiple session factories on the same data source if it's in Hibernate managed mode

### CODE REVIEW

**Comment by dantewang** [comment]
This pull has been tested at https://github.com/dantewang/liferay-portal/pull/2286

**Comment by dantewang** [comment]
ci:test:smoke

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@dantewang Regressions found in 

com.liferay.counter.test.CounterLocalServiceTest

Looks like the test just gets stuck. Tried rerunning on CI but same result. I ran the test locally too and it also got stuck.

**Comment by dantewang** [comment]
@tinatian Integration test failure is reported, I'll look into it.

**Comment by dantewang** [comment]
https://github.com/dantewang/liferay-portal/pull/2289

**Pull request closed without merging**
