### PR TITLE
LPD-42727 upgrade tomcat to 9.0.97

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This is for https://liferay.atlassian.net/browse/LPD-42727
In this PR, I am upgrading tomcat to 9.0.97

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:acceptance-functional

**Comment by jeffwu0724** [comment]
fixed the code conflict by force push

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance-functional

**Comment by jeffwu0724** [comment]
ci:report:78240740

**Comment by jeffwu0724** [comment]
ci:test:acceptance-functional: 
https://testray.liferay.com/#/project/35392/routines/45357/build/78240740/case-result/78332180/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/78240740/case-result/78332432/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/78240740/case-result/78335592/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/78240740/case-result/78336100/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/78240740/case-result/78336112/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/78240740/case-result/78336404/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/78240740/case-result/78336772/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/78240740/case-result/78337300/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/78240740/case-result/78341668/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/78240740/case-result/78342188/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/78240740/case-result/78343580/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/78240740/case-result/78343580/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/78240740/case-result/78344392/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/78240740/case-result/78344756/history -- not unique

No unique regression found

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
