### PR TITLE
[Method References] LPS-162553 Convert method references to field references in moudle portal-monitoring

### PR DESCRIPTION
**Pull request by W2jx**
Hi  @tinatian @dantewang , I convert method references to field references in moudle portal-monitoring.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @catarineaguiar , Could you please help me check the test results ? Thanks!

**Comment by catarineaguiar** [comment]
@W2jx possible regression:

```
  [exec] Could not unzip /opt/dev/projects/github/liferay-portal/.gradle/wrapper/dists/gradle-6.9.2.LIFERAY-PATCHED-1-bin/5oicx68a4f00kjoci1svi47de/gradle-6.9.2.LIFERAY-PATCHED-1-bin.zip to /opt/dev/projects/github/liferay-portal/.gradle/wrapper/dists/gradle-6.9.2.LIFERAY-PATCHED-1-bin/5oicx68a4f00kjoci1svi47de.
     [exec] Reason: invalid literal/lengths set
     [exec] Exception in thread "main" java.util.zip.ZipException: invalid literal/lengths set
     [exec] 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
     [exec] 	at java.io.FilterInputStream.read(FilterInputStream.java:107)
     [exec] 	at org.gradle.wrapper.Install.copyInputStream(Install.java:267)
     [exec] 	at org.gradle.wrapper.Install.unzip(Install.java:253)
     [exec] 	at org.gradle.wrapper.Install.access$900(Install.java:27)
     [exec] 	at org.gradle.wrapper.Install$1.call(Install.java:81)
     [exec] 	at org.gradle.wrapper.Install$1.call(Install.java:48)
     [exec] 	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
     [exec] 	at org.gradle.wrapper.Install.createDist(Install.java:48)
     [exec] 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
     [exec] 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-38/test-portal-acceptance-pullrequest(master)/3648/pmd-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
@W2jx @catarineaguiar This one doesn't look like an error that can be caused by changing portal code. I'm going to re-trigger the tests.

**Comment by dantewang** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@catarineaguiar Could you check the results again?

**Comment by catarineaguiar** [comment]
@dantewang results look good now!

**Comment by dantewang** [comment]
@shuyangzhou @tinatian Forwarding this one as all tests passed review and changes are direct replacements.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123302

**Pull request closed without merging**
