### PR TITLE
LPS-144422 Add edit in production/publication actions

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:test

**Comment by stsquared99** [comment]
ci:test:sf

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@xbrianlee Please help me scan test results.

Thanks.
Tina

**Comment by xbrianlee** [comment]
@tinatian There aren't any unique failures to this PR in any of the test suites that ran

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113614

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
