### PR TITLE
[Static references] LPS-182366 Remove static references in message-boards, reading-time and segments modules

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-182366](https://issues.liferay.com/browse/LPS-182366)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:help

**Comment by RenanUmV** [comment]
ci:test:message-boards

**Comment by RenanUmV** [comment]
ci:test:message-boards

**Comment by RenanUmV** [comment]
ci:test:stop

**Comment by RenanUmV** [comment]
ci:stop

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:message-boards

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:message-boards

**Comment by zhangyan0701** [comment]
ci:test:lima

**Comment by zhangyan0701** [comment]
**Message Boards admin portlet is unavailable.**

MB error

Error in portal console:
```
2023-04-24 03:18:39.301 ERROR [http-nio-8080-exec-1][PortletServlet:118] Unable to process portlet com_liferay_message_boards_web_portlet_MBAdminPortlet: org.apache.jasper.JasperException: java.lang.NullPointerException
javax.portlet.PortletException: org.apache.jasper.JasperException: java.lang.NullPointerException
```

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:lima

**Comment by RenanUmV** [comment]
ci:test:message-boards

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4406

**Pull request closed without merging**
