### PR TITLE
[Remove Stream/Optional usage] LPS-174116 module: object-service

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-174116

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:object

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@JanisZhang Please review this pull one more time, try your best to simplify the code following the changes Brian made to your code. I am going to close this one, please resend.

Thanks.
Tina.

**Pull request closed without merging**
