### PR TITLE
LPS-144693

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
Need to re-run default suite

**Comment by vicnate5** [comment]
@tinatian No regressions found

**Comment by tinatian** [comment]
@shuyangzhou This is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/111844

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
