### PR TITLE
LPS-198319 Merge ImageTool interface and impl into Util and move to portal-impl

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:help

**Comment by julschong** [comment]
ci:test:document

**Comment by Kvale1733** [comment]
@julschong Compile issue found
```
  [exec] > Task :apps:adaptive-media:adaptive-media-document-library-thumbnails-test:compileTestIntegrationJava
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:20: error: cannot find symbol
     [exec] import com.liferay.document.library.kernel.util.DLPreviewableProcessor;
     [exec]                                                ^
     [exec]   symbol:   class DLPreviewableProcessor
     [exec]   location: package com.liferay.document.library.kernel.util
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:29: error: cannot find symbol
     [exec] import com.liferay.portal.kernel.image.ImageTool;
     [exec]                                       ^
     [exec]   symbol:   class ImageTool
     [exec]   location: package com.liferay.portal.kernel.image
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:30: error: cannot find symbol
     [exec] import com.liferay.portal.kernel.image.ImageToolUtil;
     [exec]                                       ^
     [exec]   symbol:   class ImageToolUtil
     [exec]   location: package com.liferay.portal.kernel.image
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:431: error: cannot find symbol
     [exec] 		extends DLPreviewableProcessor implements ImageProcessor {
     [exec] 		        ^
     [exec]   symbol:   class DLPreviewableProcessor
     [exec]   location: class com.liferay.adaptive.media.document.library.thumbnails.internal.osgi.commands.test.AMThumbnailsOSGiCommandsTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:376: error: cannot find symbol
     [exec] 			_company.getCompanyId(), DLPreviewableProcessor.REPOSITORY_ID,
     [exec] 	
  ```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-25/test-portal-acceptance-pullrequest(master)/3675/modules-compile-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
