### PR TITLE
LPD-17343 Performance fix

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @tinatian @victorhcunha

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by pei-jung** [comment]
ci:report:2548862949

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:publications

**Comment by tinatian** [comment]
ci:report:2549657702

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
This error seems to be caused by https://liferay.atlassian.net/browse/LPD-19264, which contains the same [failure](https://testray.liferay.com/home/-/testray/case_results/2548733692?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2548733382%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc). Other failures look unrelated.

```
2024-03-14 07:09:29.104 ERROR [destination.workflow_timer-2][ParallelDestination:50] Unable to process message {destinationName=destination.workflow_timer, response=null, responseDestinationName=null, responseId=null, payload=null, values={GROUP_NAME=destination.workflow_timer/33162@40624788940931, companyId=40624788940931, groupId=0, DESTINATION_NAME=destination.workflow_timer, JOB_STATE=com.liferay.portal.kernel.scheduler.JobState@79d7694, kaleoTimerInstanceTokenId=33162, STORAGE_TYPE=PERSISTED, JOB_NAME=destination.workflow_timer/33162@40624788940931}}
[beanshell] com.liferay.portal.kernel.messaging.MessageListenerException: com.liferay.portal.workflow.kaleo.exception.NoSuchTimerInstanceTokenException: No KaleoTimerInstanceToken exists with the primary key 33162
```

@tinatian @victorhcunha if everything looks good to you, can I forward this one?

**Comment by pei-jung** [comment]
Resent as https://github.com/liferay-core-infra/liferay-portal/pull/6771

**Pull request closed without merging**
