### PR TITLE
[Replace Non-Blocking Usage] LPS-199841 

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace non-blocking ServiceProxyFactory usages in class `PortletDisplayTemplateManagerUtil`, `SocialActivityManagerUtil`,  `MicrosoftTranslatorFactoryUtil`, and  `TemplateHandlerRegistryUtil`. Thanks.
https://liferay.atlassian.net/browse/LPS-199841

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by liuxingye** [comment]
ci:test:stable

**Comment by liuxingye** [comment]
Reviewing...

**Comment by liuxingye** [comment]
The [relevant](https://testray.liferay.com/home/-/testray/case_results?tab=runs&testrayBuildId=2446343547), [startup](https://testray.liferay.com/home/-/testray/case_results?tab=runs&testrayBuildId=2446327121) and [upgrade](https://testray.liferay.com/home/-/testray/case_results?tab=runs&testrayBuildId=2446478283) results are look good to me.

cc @zhangyan0701

**Comment by JanisZhang** [comment]
Thanks Beck! @liuxingye

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
