### PR TITLE
[Replace Non-Blocking Usage] LPS-199955

### PR DESCRIPTION
**Pull request by JanisZhang**
Resent :https://github.com/liferay-core-infra/liferay-portal/pull/5897.  Thanks.

https://liferay.atlassian.net/browse/LPS-199955

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143182

@JanisZhang https://github.com/brianchandotcom/liferay-portal/pull/143182/commits/ef8bd9128723f42d3c6c452de60275beef8a4772

cc @shuyangzhou

**Pull request closed without merging**
