### PR TITLE
[Remove Blocking usages]LPS-189701 bean-portlet | CDIBeanPortletExtension, SpringBeanPortletExtension

### PR DESCRIPTION
**Pull request by W2jx**
resend

Changes:

Only call method `ServiceTracker.close()` in method `deactivate()`

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5148

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:portlet-deployment

**Comment by W2jx** [comment]
ci:test

**Comment by W2jx** [comment]
ci:test:jsf

**Review by dantewang — CHANGES_REQUESTED** [review]
@W2jx https://github.com/liferay-core-infra/liferay-portal/pull/5165/commits/235e59c377b3d23aa94f6e2f7e6cb1c5a27020bf Please change the commit message of this one to make it clear you do this because no one needs this public API any more.

Others look good to me.

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
only change the commit message, no need to rerun test

**Comment by W2jx** [comment]
Hi @dantewang , I have changed the commit message.

**Review by dantewang — APPROVED** [review]

**Comment by W2jx** [comment]
no conflicts(8/4 14:56)

**Comment by W2jx** [comment]
no conflicts(8/7 8:38)

**Comment by W2jx** [comment]
no conflicts(8/9 17:17)

**Comment by W2jx** [comment]
no conflicts(8/10 17:08)

**Comment by W2jx** [comment]
no conflicts(8/11 16:01)

**Comment by W2jx** [comment]
no conflicts(8/14 16:58)

**Comment by W2jx** [comment]
no conflicts(8/16 13:14)

**Comment by W2jx** [comment]
no conflicts(8/18 13:59)

**Comment by W2jx** [comment]
no conflicts(8/22 13:15)

**Comment by W2jx** [comment]
no conflicts(8/23 14:35)

**Comment by W2jx** [comment]
no conflicts(8/24 10:22)

**Comment by shuyangzhou** [comment]
@W2jx There is no reason to register BeanPortletRegistrarBag as a service, and BeanPortletRegistrarBagRegistry should not be a component, it can just be an Util class which takes BeanPortletRegistrarBag returns a List of ServiceRegistration to the caller to keep track of. Even the BeanPortletRegistrarBag does not really have any value, the Util class can just take all the parameters it needs.

Please resend with this design change.

CC @dantewang

**Pull request closed without merging**
