### PR TITLE
[Bug Fix] LPS-88060

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr rebases on https://github.com/liferay-core-infra/liferay-portal/pull/102 (LPS-144437) and finish the [requirement ](https://github.com/liferay-core-infra/liferay-portal/pull/32#issuecomment-981404118)

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by dantewang** [comment]
@yuhai Please see https://github.com/liferay-core-infra/liferay-portal/pull/102#issuecomment-1001522470. Let's get the first part done first.

**Comment by dantewang** [comment]
@yuhai Please see https://github.com/liferay-core-infra/liferay-portal/pull/102#issuecomment-1001522470. Let's get the first part done first.

**Pull request closed without merging**
