### PR TITLE
LPS-206629

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by achaparro** [comment]
ci:report:2538567241

**Comment by achaparro** [comment]
ci:report:2538602432

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
no unique failures in ci:test:upgrade

Running again the ci:test:relevant suite the reports show 2 unique failures although they seem unrelated:
- LocalFile.AssetPublisher#AddWebContentViaAssetPublisherThenAddAssociatedWidgetToPage (https://testray.liferay.com/home/-/testray/case_results/2538605896/history)
- LocalFile.SetupWizard#NonLiferayDomainDoesNotGiveAdminRightsByDefault (https://testray.liferay.com/home/-/testray/case_results/2538608802/history)

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:2538884581

**Comment by achaparro** [comment]
ci:report:2538954851

**Comment by achaparro** [comment]
@tinatian 

One of the errors of my previous comment https://github.com/liferay-core-infra/liferay-portal/pull/6629#issuecomment-1943878092 disappeared.

The other one, is happening in this macro SetupWizard.testcase that does not use anything related to the PortalInstances change, I guess the error is unrelated.

Do you agree? If so, can we move forward and send it to Brian?

Thanks.

**Comment by tinatian** [comment]
ci:report:2539029232

**Comment by tinatian** [comment]
ci:help

**Comment by tinatian** [comment]
ci:test:setup-wizard

**Comment by achaparro** [comment]
ci:test:setup-wizard

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:report:2539201120

**Comment by achaparro** [comment]
ci:report:2539179866

**Comment by achaparro** [comment]
ci:test:setup-wizard

**Comment by achaparro** [comment]
Upgrade suite finished with no unique failures

setup-wizard has a couple of unstable tests, executing it again

**Comment by achaparro** [comment]
ci:report:2539235862

**Comment by achaparro** [comment]
- Upgrade suite finished with no unique failures
- setup-wizard has a couple of unstable tests, executing it again
- Relevant has one failure, related to the CI infrastructure: LocalFile.TagsFragment#ViewAllTagsShownInObjectSiteScoped:
org.openqa.selenium.NoSuchWindowException: no such window
https://testray.liferay.com/home/-/testray/case_results/2539236363/history

**Comment by achaparro** [comment]
ci:report:2539276211

**Comment by achaparro** [comment]
Hi @tinatian,

The setup-wizard suite fails with unique failures but they don't seem related. It seems no one executed this suite sicne quite a long time and that can explain why they are unique:
https://testray.liferay.com/home/-/testray/case_results/2539279662/history

- Upgrade suite finished with no unique failures
- Relevant has one failure, related to the CI infrastructure: LocalFile.TagsFragment#ViewAllTagsShownInObjectSiteScoped:
    org.openqa.selenium.NoSuchWindowException: no such window
    https://testray.liferay.com/home/-/testray/case_results/2539236363/history

What do you think?

**Comment by tinatian** [comment]
@achaparro This one is unrelated https://testray.liferay.com/home/-/testray/case_results/2539279662/history. It failed on master too.

**Comment by tinatian** [comment]
No regression found.

**Pull request closed without merging**
