### PR TITLE
[Circular Dependency]Lps 187454

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-187454

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:depot

**Comment by zhangyan0701** [comment]
An issue seems related:

Control Panel is unavailable after deactivating an app in App Manager.

Reproduce steps:

1. Go to Control Panel > App Manager.
2. Search Asset Libraries.
3. Deactivate it.

Results:
Internal error occurs.
control panel

Error in portal console:
```
2023-06-14 11:18:40.736 ERROR [http-nio-8080-exec-9][runtime:59] Error executing FreeMarker template
freemarker.template.TemplateModelException: Error while invoking the "control-menu" JSP custom tag; see cause exception

----
FTL stack trace ("~" means nesting-related):
	- Failed at: @liferay_product_navigation["control-...  [in template "com.liferay.portal.template.freemarker_7.0.40_CLASS_LOADER_CONTEXT_FTL_liferay.ftl" in macro "control_menu" at line 61, column 17]
	- Reached through: @liferay.control_menu  [in template "classic-theme_SERVLET_CONTEXT_/templates/portal_normal.ftl" at line 22, column 9]
----
```
Affected test: [LocalFile.AppManagement#CanDeactivateAndActivateAssetLibraries](https://testray.liferay.com/home/-/testray/case_results/2349958862)
Full Jenkins console:
https://testray.liferay.com/reports/production/logs/2023-06/test-1-26/test-portal-acceptance-pullrequest(master)/9810/functional-tomcat90-mysql57-jdk8/3/0/jenkins-console.txt.gz?authuser=0

**Comment by slnn** [comment]
> An issue seems related:
> 
> Control Panel is unavailable after deactivating an app in App Manager.
> 
> Reproduce steps:
> 
> 1. Go to Control Panel > App Manager.
> 2. Search Asset Libraries.
> 3. Deactivate it.
> 
> Results: Internal error occurs. control panel
> 
> Error in portal console:
> 
> ```
> 2023-06-14 11:18:40.736 ERROR [http-nio-8080-exec-9][runtime:59] Error executing FreeMarker template
> freemarker.template.TemplateModelException: Error while invoking the "control-menu" JSP custom tag; see cause exception
> 
> ----
> FTL stack trace ("~" means nesting-related):
> 	- Failed at: @liferay_product_navigation["control-...  [in template "com.liferay.portal.template.freemarker_7.0.40_CLASS_LOADER_CONTEXT_FTL_liferay.ftl" in macro "control_menu" at line 61, column 17]
> 	- Reached through: @liferay.control_menu  [in template "classic-theme_SERVLET_CONTEXT_/templates/portal_normal.ftl" at line 22, column 9]
> ----
> ```
> 
> Affected test: [LocalFile.AppManagement#CanDeactivateAndActivateAssetLibraries](https://testray.liferay.com/home/-/testray/case_results/2349958862) Full Jenkins console: https://testray.liferay.com/reports/production/logs/2023-06/test-1-26/test-portal-acceptance-pullrequest(master)/9810/functional-tomcat90-mysql57-jdk8/3/0/jenkins-console.txt.gz?authuser=0

Thank @zhangyan0701 for catching this! Will fix and resend.

**Comment by slnn** [comment]
Hi @dantewang

When deactivating the Liferay Asset Libraries from Control Panel > App Manager, these modules:  Liferay Depot API, Liferay Depot Service, Liferay Depot Web also will be changed from Acitvate to Resolved,  I break the original circular dependency by making PanelAppRegistry dependent another service that from Liferay Depot Web, so the Control Panel is unavailable after deactivating an app in App Manager.

We have converted the Optional reference to snapshot, and I think the Optional reference not only break the circular dependency but also makes sure the panel would not  be affected when deactivated any apps in Control Panel > App Manager.

LPS-187454-IMG_0040

Do you think if we still need to find a new way to break the circular decency?

Lily

**Comment by dantewang** [comment]
@slnn Let's revisit it after all other things are clear.

**Pull request closed without merging**
