### PR TITLE
[Disable auto-import-default-references] Lps 164208

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-164208

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No related failures.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123994

**Pull request closed without merging**
