### PR TITLE
[Remove Blocking usages] LPS-191761 portal-kernel | WorkflowLogManagerUtil

### PR DESCRIPTION
**Pull request by JanisZhang**
https://liferay.atlassian.net/browse/LPS-191761

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Review by dantewang — CHANGES_REQUESTED** [review]
@JanisZhang Please replace the usages first, and then remove the util when no one is using it any more.

**Pull request closed without merging**
