### PR TITLE
LPS-191780 Use PropsUtil class to read in test-portal-impl-ext.properties

### PR DESCRIPTION
**Pull request by DaneszLR**
Hi Team,

https://liferay.atlassian.net/browse/LPS-191780

Issue:
Customer wanted to overwrite company.web.id and do an integration test. The test read up the portal-ext.properties file and set the company.web.id to the new value, but right before the test the test-portal-impl.properties file got read up overwriting the company.web.id. Using test-portal-impl-ext.properties could resolve the issue, but it doesn't get read up, only from portal-test.jar. In 6.2 it was possible to put the -ext file outside the jar, but since then test-portal-impl.properties was moved from portal-impl in LPS-59148 to portal-test module so that we don't have to force every test module to Include-Resource it.

Customer stated putting it in the jar doesn't solve their problem because the jar gets rebuilt and the added properties file gets lost.

Solution:
For reading up the -ext file use PropsUtil instead of TestPropsUtil, so it can be reached from webapps/ROOT/WEB-INF/classes
It is hard to say if it is a bug, but we considered it as one because the correct and original behavior was in 6.2 .

Testing:
Tested it locally. The solution works.

Please review my PR!

Best regards,
Dani

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
No regressions found. Testing passed following ticket steps.

**Comment by tinatian** [comment]
@vicnate5 Could you please help verify if the steps of this ticket is valid?

@DaneszLR If the steps are valid, the fix is in wrong place, please fix it in TestPropsUtil, the root reason is TestPropsUtil is reading `test-portal-impl-ext.properties` from its own classloader which is a module class loader, however, in your test steps, it was put in any folder which is not the same class loader as the code checked.

If we did not change any code, a solution to make `test-portal-impl-ext.properties` loaded is to put it into a fragment bundle of the bundle where TestPropsUtil is in, so that they are sharing the same class loader.

Please resend if needed.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian I think this is a valid scenario. This is going to affect most external users who wants to run integration tests (since they are not using liferay.com web.id).  The steps in https://liferay.atlassian.net/browse/LPP-50210 better describe the issue.

I would even question why we need to even have the company web id [hardcoded by default](https://github.com/liferay/liferay-portal/blob/master/portal-test/src/test-portal-impl.properties). Could we read `company.default.web.id` from the portal properties and use that value by default?

**Pull request closed without merging**
