### PR TITLE
LPS-172441 upgrade snakeyaml to 2.0

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

Resent: https://github.com/liferay-core-infra/liferay-portal/pull/3735
This is for ticket https://issues.liferay.com/browse/LPS-172441.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
Hi @kevhlee , could you please make sure [this regression](https://github.com/liferay-core-infra/liferay-portal/pull/3735#issuecomment-1483260653) is not showing?
Btw, seems like in this previous [PR](https://github.com/liferay-core-infra/liferay-portal/pull/3735), the first two times I run ci:test:stable, all the testes in ci:test:stable passed. Is the regression `portal-license-smoke-jdk8` caught in other runs, or is this regression just happened randomly, please?
Thanks for your help!

**Comment by Kvale1733** [comment]
@jeffwu0724 It was failing consistently on stable. It failed for one other PR that included this change. I think after the latest rebase something changed, I'm not sure. But we'll see what the stable results are here.

**Comment by jeffwu0724** [comment]
cool, thanks @Kvale1733

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions. portal-license-smoke-jdk8 passes. The regressions is not present here.

**Comment by jeffwu0724** [comment]
ci:help

**Comment by jeffwu0724** [comment]
ci:test:license

**Comment by jeffwu0724** [comment]
ci:test:license-cluster

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132981

**Comment by tinatian** [comment]
ci:test:help

**Comment by tinatian** [comment]
ci:test:environments

**Pull request closed without merging**
