### PR TITLE
[Method References 2] LPS-164351 Remove unused reference variable in module saml-addon-keep-alive-web(dxp)

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have removed unused reference variable in module saml-addon-keep-alive-web(dxp).

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/124691

cc @shuyangzhou @tinatian

**Pull request closed without merging**
