### PR TITLE
[SF] LPS-195576 Check `"model.class.name"` property in `*ModelResourcePermission` classes

### PR DESCRIPTION
**Pull request by kevhlee**
Ticket: <https://liferay.atlassian.net/browse/LPS-195576>

This SF rule checks the`"model.class.name"` property in `*ModelResourcePermission` classes to make sure that it exists and matches the model class name. For now, I have disabled it since there are violations.

@shuyangzhou, @dantewang, I only found __4 classes__ that violate this rule (I ran this rule on commit d8bd196951f6dc1b3cb127ff89bef128c7a38899), which I listed below. Is it okay to just change the value of `"model.class.name"` for each of these classes? Additionally, should this rule be converted to an automatic one, assuming we only need to fix the property?

```log
[java] java.lang.Exception: Found 4 formatting issues:
[java] 1: Expected `model.class.name` property value to be 'com.liferay.commerce.product.model.CommerceChannelAccountEntryRel' but is 'com.liferay.commerce.model.CommerceChannelAccountEntryRel': ./modules/apps/commerce/commerce-service/src/main/java/com/liferay/commerce/internal/security/permission/resource/CommerceChannelAccountEntryRelModelResourcePermission.java 26 (Checkstyle:ResourcePermissionCheck)
[java] 2: Expected `model.class.name` property value to be 'com.liferay.portal.workflow.kaleo.model.KaleoDefinition' but is 'com.liferay.portal.kernel.workflow.WorkflowDefinition': ./modules/apps/portal-workflow/portal-workflow-kaleo-runtime-integration-impl/src/main/java/com/liferay/portal/workflow/kaleo/runtime/integration/internal/security/permission/resource/WorkflowDefinitionModelResourcePermission.java 24 (Checkstyle:ResourcePermissionCheck)
[java] 3: Expected `model.class.name` property value to be 'com.liferay.portal.workflow.kaleo.model.KaleoInstance' but is 'com.liferay.portal.kernel.workflow.WorkflowInstance': ./modules/apps/portal-workflow/portal-workflow-kaleo-runtime-integration-impl/src/main/java/com/liferay/portal/workflow/kaleo/runtime/integration/internal/security/permission/resource/WorkflowInstanceModelResourcePermission.java 26 (Checkstyle:ResourcePermissionCheck)
[java] 4: Expected `model.class.name` property value to be 'com.liferay.portal.workflow.kaleo.model.KaleoTaskInstanceToken' but is 'com.liferay.portal.kernel.workflow.WorkflowTask': ./modules/apps/portal-workflow/portal-workflow-kaleo-runtime-integration-impl/src/main/java/com/liferay/portal/workflow/kaleo/runtime/integration/internal/security/permission/resource/WorkflowTaskModelResourcePermission.java 30 (Checkstyle:ResourcePermissionCheck)
```

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@kevhlee I'll take a look first, thanks!

**Comment by dantewang** [comment]
@kevhlee For the current 4, @JanisZhang will take care of them manually.

It may not be very easy for SF to auto-correct such cases, because an OSGi service property can be used in many ways by others.

For example, SF finds out this, and can easily correct it:
```
@Component(
	property = "model.class.name=com.liferay.commerce.model.CommerceChannelAccountEntryRel",
	service = ModelResourcePermission.class
)
public class CommerceChannelAccountEntryRelModelResourcePermission
	implements ModelResourcePermission<CommerceChannelAccountEntryRel> {
```

But in order to auto-correct, SF must also add a rule for `@Reference` like this:
```
	@Reference(
		policy = ReferencePolicy.DYNAMIC,
		policyOption = ReferencePolicyOption.GREEDY,
		target = "(model.class.name=com.liferay.commerce.model.CommerceChannelAccountEntryRel)"
	)
	private volatile ModelResourcePermission<CommerceChannelAccountEntryRel>
		_commerceChannelAccountEntryRelModelResourcePermission;
```

However, this is not the only way to use this service. One can use other ways to get this service.

**Comment by kevhlee** [comment]
@Kvale1733, I forgot to add in the PR. I will have to re-run the tests.

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
No regressions found. SF issue is unrelated.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141201

**Pull request closed without merging**
