### PR TITLE
[Urgent][Security Bugs]LPD-37739 move protobuf to share-dependencies and upgrade to 3.25.5

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This is for ticket https://liferay.atlassian.net/browse/LPD-37739.
As talked, I create a shared-dependencies module for protobuf, and then upgrade it to higher version.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:core-functional

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
ci:report:27533274

**Comment by jeffwu0724** [comment]
core-functional:
https://testray.liferay.com/#/project/35392/routines/45357/build/27533274/case-result/27534363/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/27533274/case-result/27535151/history -- not unique
https://testray.liferay.com/#/project/35392/routines/45357/build/27533274/case-result/27535155/history -- not unique

**Comment by jeffwu0724** [comment]
Hi @vicnate5 ,
This PR is to upgrade protobuf, and its usages are
```
./modules/apps/portal-store/portal-store-gcs/build.gradle:     compileInclude group: "com.google.protobuf", name: "protobuf-java", version: "3.21.7" 
./modules/apps/portal-store/portal-store-gcs/build.gradle:     compileInclude group: "com.google.protobuf", name: "protobuf-java-util", version: "3.21.7" 
./modules/apps/site-initializer/site-initializer-testray/site-initializer-testray-dispatch-task-executor/build.gradle: compileInclude group: "com.google.protobuf", name: "protobuf-java", version: "3.21.7" 
./modules/apps/site-initializer/site-initializer-testray/site-initializer-testray-dispatch-task-executor/build.gradle: compileInclude group: "com.google.protobuf", name: "protobuf-java-util", version: "3.21.7" 
./modules/dxp/apps/portal-rules-engine-drools/portal-rules-engine-drools/build.gradle: compileInclude group: "com.google.protobuf", name: "protobuf-java", version: "3.21.7" 
./modules/util/sass-compiler-dart/build.gradle: compileInclude group: "com.google.protobuf", name: "protobuf-java", version: "3.21.7" 
./workspaces/liferay-testray-workspace/modules/testray-rest-impl/build.gradle: compileInclude group: "com.google.protobuf", name: "protobuf-java", version: "3.21.7" 
./workspaces/liferay-testray-workspace/modules/testray-rest-impl/build.gradle: compileInclude group: "com.google.protobuf", name: "protobuf-java-util", version: "3.21.7"
```
May I ask do you think we should trigger more test here, please?

**Comment by vicnate5** [comment]
ci:test:dl-store

**Comment by vicnate5** [comment]
Good news is the google cloud store test passed
https://testray.liferay.com/#/project/35392/routines/45357/build/28546360/case-result/28548243

So just need to confirm with Testray team.

**Comment by jeffwu0724** [comment]
I have raised a question in https://liferay.slack.com/archives/C01MVBFRN0K/p1727828164731419

**Comment by jeffwu0724** [comment]
testray team said they would take a look and update later

**Comment by jeffwu0724** [comment]
ci:report:28546360

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
