### PR TITLE
LPS-171867 Remove leftovers "immediate = true" from vulcan

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-171867

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:headless

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@rafaprax Regressions found

Cannot create entry with custom object field

Steps to reproduce
        1) Go to Control Panel > Objects
        2) Click on User object
        3) Go to fields tab
        4) Add new field with label "passportNumber" of type text
        5) Try adding a user with the new field using the following curl
        ```
        curl -X POST -H 'accept: application/json' -H 'Content-Type: application/json' -u 'test@liferay.com:test' -d '{"alternateName": "user","emailAddress": "user@liferay.com","familyName": "userfn","givenName": "userln","passportNumber":"passportNum2022"}' http://localhost:8080/o/headless-admin-user/v1.0/user-accounts

        ```
        
  Expected Results: A new user named "userfrn userln" is added with the custom field passportNumber: "passportNum202"
  Actual Results: The user is not added and the curl returns
    ```
    {
            "status" : "BAD_REQUEST",
            "title" : "The property \"passportNumber\" is not defined in UserAccount."
 }
     ```
     
  [Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-37/test-portal-acceptance-pullrequest(master)/7964/functional-tomcat90-mysql57-jdk8/0/5/jenkins-console.txt.gz?authuser=0)

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:headless

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@rafaprax No regressions found.

**Comment by tinatian** [comment]
@rafaprax This commit https://github.com/liferay-core-infra/liferay-portal/pull/3047/commits/3722513c09ff3c0613a30b5929b14c6d5d05b9c2 does not make sense to me, please consider use servicetrackerlist or servicetrackermap

**Pull request closed without merging**
