### PR TITLE
[Remove Blocking usages]LPS-193319 portal-kernel | WorkflowDefinitionManagerUtil

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend, and move WorkflowDefinitionManager to workflow-api module. thanks!
previous: https://github.com/liferay-core-infra/liferay-portal/pull/5321

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:workflow

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Comment by JanisZhang** [comment]
ci:forward:force

**Comment by JanisZhang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139592

**Pull request closed without merging**
