### PR TITLE
[TS] LPS-205362

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:report:2502786541

**Comment by tinatian** [comment]
@marianoalvarosaiz Is there any test covered this change? If not, could you please add one? The ci test results seem flaky, and I am going to retrigger the test.

FYI @ericyanLr 

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:2534302231

**Comment by tinatian** [comment]
@marianoalvarosaiz No unique failure with my change. Since the fix is in Object scope, please send this to Object team to review. I am going to close this pull. 

Thanks.
Tina.

**Comment by tinatian** [comment]
@marianoalvarosaiz Please note I changed your solution, now all the changes are in Object team scope. I prefer to add test to cover this change, but I am not familiar with their stuff, so its better to send this fix to them and let them add their test.

Thanks.
Tina.

**Comment by marianoalvarosaiz** [comment]
ok @tinatian

**Comment by marianoalvarosaiz** [comment]
See https://github.com/liferay-objects/liferay-portal/pull/3096

**Pull request closed without merging**
