### PR TITLE
[Method References 2] LPS-166976

### PR DESCRIPTION
**Pull request by JanisZhang**
This PR is to use serviceTrackerMap instead of the method reference in portal-security-ldap-impl. Thanks!
https://issues.liferay.com/browse/LPS-166976

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:ldap

**Comment by Kvale1733** [comment]
ci:test:ldap

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
The change I made in https://github.com/liferay-core-infra/liferay-portal/pull/2242 may be helpful for simplifying this PR. Let's wait to see whether that one can get accepted.

**Comment by tinatian** [comment]
@JanisZhang As we talked in the meeting, please resend.

Tina

**Pull request closed without merging**
