### PR TITLE
LPS-145585 Avoid using ZipReaderFactoryUtil, ZipWriterFactoryUtil, SitesUtil directly in modules

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina, Shuyang

Main Task: [LPS-143403](https://issues.liferay.com/browse/LPS-143403)
Sub Task: [LPS-145585](https://issues.liferay.com/browse/LPS-145585)

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
Could you please help us scan the test result?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by julschong** [comment]
added .lfrbuild-app-server-lib and .lfrbuild-portal-pre

**Comment by julschong** [comment]
@tinatian Hi Tina,
Could you please help review this pull?
Thank you!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116796

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
