### PR TITLE
LPS-178022 Cleanup SearchResult for optional removal

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@julschong Regression found

1) com.liferay.portal.search.web.internal.search.results.portlet.SearchResultsPortletTest
```
[exec] com.liferay.portal.search.web.internal.search.results.portlet.SearchResultsPortletTest > testDocumentWithoutSummaryIsRemoved FAILED
     [exec]     java.lang.IllegalArgumentException: PortletPreferences is not present
     [exec]         at com.liferay.portal.search.web.internal.search.results.portlet.SearchResultsPortletPreferencesImpl.lambda$new$0(SearchResultsPortletPreferencesImpl.java:37)
     [exec]         at java.util.Optional.orElseThrow(Optional.java:290)
     [exec]         at com.liferay.portal.search.web.internal.search.results.portlet.SearchResultsPortletPreferencesImpl.<init>(SearchResultsPortletPreferencesImpl.java:36)
     [exec]         at com.liferay.portal.search.web.internal.search.results.portlet.Search
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-39/test-portal-acceptance-pullrequest(master)/4360/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Pull request closed without merging**
