### PR TITLE
[Component with its own class name as service type] LPS-198943 Refactor Helper components from commerce modules part 1

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-198943](https://liferay.atlassian.net/browse/LPS-198943)

Previous Pull: https://github.com/liferay-core-infra/liferay-portal/pull/6205

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @tinatian

**Pull request closed without merging**
