### PR TITLE
LPS-170114 Remove "immediate = true" from Portal II

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:stable

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
ci:test:stable

**Comment by RenanUmV** [comment]
ci:test:workflow

**Comment by RenanUmV** [comment]
ci:test:workflow-metrics

**Comment by catarineaguiar** [comment]
@RenanUmV all startup tests failed due to:

```
[exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.CPRolesCPWebcontent#AddStructureSiteRoleDefaultPermission] STANDARD_ERROR
     [exec]     java.lang.Exception: 
     [exec]     ##
     [exec]     ## 1 Liferay Exception was thrown
     [exec]     ##
     [exec] 
     [exec]     LIFERAY_ERROR: Unable to sync callable
     [exec] 
     [exec] 
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/journal/CPRolesCPWebcontent.testcase[AddStructureSiteRoleDefaultPermission]:191
     [exec]     	at com.liferay.poshi.runner.selenium.LiferaySeleniumUtil.assertNoPoshiWarnings(LiferaySeleniumUtil.java:221)
     [exec]     	at com.liferay.poshi.runner.PoshiRunner.test(PoshiRunner.java:264)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
```
```
     [exec]     Executing commands: curl -X POST -u 'test@liferay.com:test' -d 'userId=46391' http://test-1-33-11.lax.liferay.com:8080/api/jsonws/user/delete-user
[beanshell] 2022-12-09 14:32:01.031 ERROR [http-nio-8080-exec-2][GroupLocalServiceImpl:4812] Unable to unschedule events for group: 46394
[beanshell] com.liferay.portal.kernel.scheduler.SchedulerException: Unable to delete jobs in group liferay/layouts_remote_publisher/46394
[beanshell] 	at com.liferay.portal.scheduler.quartz.internal.QuartzSchedulerEngine.delete(QuartzSchedulerEngine.java:108) ~[?:?]
[beanshell] 	at com.liferay.portal.scheduler.internal.SchedulerEngineHelperImpl.delete(SchedulerEngineHelperImpl.java:143) ~[?:?]
[beanshell] 	at com.liferay.portal.kernel.scheduler.SchedulerEngineHelperUtil.delete(SchedulerEngineHelperUtil.java:56) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.service.impl.GroupLocalServiceImpl.unscheduleStaging(GroupLocalServiceImpl.java:4774) [portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.service.impl.GroupLocalServiceImpl.deleteGroup(GroupLocalServiceImpl.java:961) [portal-impl.jar:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-29/test-portal-acceptance-pullrequest(master)/5704/functional-smoke-startup-tomcat90-mysql57-jdk8/0/10/jenkins-console.txt.gz?authuser=0)

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@RenanUmV The startup errors occurred again. I was able to reproduce locally just by starting up the bundle. Looks like an actual regression.

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@RenanUmV No more startup issues.

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
ci:test:workflow-metrics

**Comment by Kvale1733** [comment]
@RenanUmV No regressions found.

**Comment by tinatian** [comment]
ci:forward

FYI @shuyangzhou

**Pull request closed without merging**
