### PR TITLE
LPS-147085

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for https://issues.liferay.com/browse/LPS-147085.
Can also see https://github.com/jeffwu0724/liferay-portal/pull/60.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by kyle-miho** [comment]
waiting for results

**Comment by kyle-miho** [comment]
@jeffwu0724 there doesnt seem to be any unique failures

**Comment by tinatian** [comment]
ci:test:environment

**Comment by tinatian** [comment]
ci:help

**Comment by tinatian** [comment]
ci:test:environments

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result for "ci:test:environments", please?

Thanks
Jeff

**Comment by kyle-miho** [comment]
@jeffwu0724 failures are unrelated

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
