### PR TITLE
LPS-157759 Check serviceContext.isIndexingEnabled before index the content

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:acceptance

**Comment by guilhermedcamacho** [comment]
@catarineaguiar please help me check the results when they are ready, thanks!

**Comment by guilhermedcamacho** [comment]
I found a regression with DLServiceVerifyProcessTest.testDLFileEntryWithNoAssetEntryGetsAssetEntryAdded

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
@guilhermedcamacho no regressions found.

**Comment by guilhermedcamacho** [comment]
@shuyangzhou , this PR is ready for your review. Thanks!

**Comment by shuyangzhou** [comment]
@guilhermedcamacho please rebase, thanks!

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
@catarineaguiar please help me check the results, thanks!

**Comment by guilhermedcamacho** [comment]
I just fixed these files related to version, so sf and relevant suites should be enough

```
portal-kernel/bnd.bnd
portal-kernel/src/com/liferay/portal/kernel/service/packageinfo
```

**Comment by catarineaguiar** [comment]
@guilhermedcamacho possible regressions:

```
 [exec] > Task :yarnInstall FAILED
     [exec] Using registry http://mirrors.lax.liferay.com:4873
     [exec] /opt/dev/projects/github/liferay-portal/build/node/lib/node_modules/yarn/yarn-1.13.0.js:395
     [exec]         if (events.ignoreBasenames.indexOf((_path || _load_path()).default.basen
     [exec]                                                                            ^^^^^
     [exec] 
     [exec] SyntaxError: missing ) after argument list
     [exec]     at Object.compileFunction (node:vm:352:18)
     [exec]     at wrapSafe (node:internal/modules/cjs/loader:1031:15)
     [exec]     at Module._compile (node:internal/modules/cjs/loader:1065:27)
     [exec]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
     [exec]     at Module.load (node:internal/modules/cjs/loader:981:32)
     [exec]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
     [exec]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
     [exec]     at node:internal/main/run_main_module:17:47
     [exec] Gradle build finished at 2022-07-30 16:54:18.165.
     [exec] 2 actionable tasks: 2 executed
     [exec] 
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-07/test-1-32/test-portal-acceptance-pullrequest(master)/5022/functional-tomcat90-mysql57-jdk8/21/4/jenkins-console.txt.gz?authuser=0)

**Comment by guilhermedcamacho** [comment]
Thanks @catarineaguiar , I didn't change anything related to Yarn or Front-end stuff, but I will rebase and run relevant suite again just in case.

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
@catarineaguiar please help me check the results, thanks!

**Comment by catarineaguiar** [comment]
@guilhermedcamacho no regressions found.

**Comment by guilhermedcamacho** [comment]
@shuyangzhou , this PR is ready for your review again. Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121141

**Pull request closed without merging**
