### PR TITLE
LPD-20946 Temp fix by avoiding populating module resource by different portlets

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:report:5175308

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 5175308.
> 
> Job Link: [generate-testray-csv](https://test-1-5.liferay.com/job/generate-testray-csv/75/)
> 
> Testray CSV Link: [testray-results-5175308.csv](https://test-1-5.liferay.com/userContent/jobs/generate-testray-csv/builds/75/testray-results-5175308.csv)

@tinatian `DLFileEntryModelDocumentContributorTest` failure also happens elsewhere; the failures of `ObjectActionLocalServiceTest` and `RedirectEntrySearchTest` passed on my local by running the same group of tests as shown in the Jenkins log.

**Comment by dantewang** [comment]
ci:report:5396335

**Comment by dantewang** [comment]
ci:report:5242129

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: [5242129](https://github.com/liferay-core-infra/liferay-portal/commit/5242129da6e8d05d4e93de13738da620b392f31a).
> 
> Job Link: [generate-testray-csv](https://test-1-30.liferay.com/job/generate-testray-csv/270/)
> 
> Testray CSV Link: [testray-results-5242129.csv](https://test-1-30.liferay.com/userContent/jobs/generate-testray-csv/builds/270/testray-results-5242129.csv)

@tinatian It's hard to tell whether the 3 errors in the startup result are unique. I randomly opened several failure results and found that they were all from recent resource action runs.

**Comment by dantewang** [comment]
ci:report:5396335

**Comment by tinatian** [comment]
ci:report:5396335

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 5396335.
> 
> Job Link: [generate-testray-csv](https://test-1-32.liferay.com/job/generate-testray-csv/221/)
> 
> Testray CSV Link: [testray-results-5396335.csv](https://test-1-32.liferay.com/userContent/jobs/generate-testray-csv/builds/221/testray-results-5396335.csv)

No unique failures

**Comment by tinatian** [comment]
ci:test:object

**Comment by tinatian** [comment]
ci:test:core-functional

**Comment by tinatian** [comment]
ci:test:startup

**Comment by tinatian** [comment]
ci:report:6014770

**Comment by tinatian** [comment]
ci:report:5933202

**Comment by tinatian** [comment]
ci:report:5887073

**Comment by tinatian** [comment]
> 6014770

Unique failures in report are not unique to this pull

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 5933202.
> 
> Job Link: [generate-testray-csv](https://test-1-39.liferay.com/job/generate-testray-csv/418/)
> 
> Testray CSV Link: [testray-results-5933202.csv](https://test-1-39.liferay.com/userContent/jobs/generate-testray-csv/builds/418/testray-results-5933202.csv)

@tinatian By comparing with https://github.com/dantewang/liferay-portal/pull/2393#issuecomment-2339787859, the startup failures here are not unique.

**Comment by dantewang** [comment]
ci:test:core-functional

Rerun to see whether LocalFile.Clustering#CanAddCategoryToDocumentOnSlaveNode fails again.

**Comment by dantewang** [comment]
ci:report:6354912

**Pull request closed without merging**
