### PR TITLE
[TS][Urgent] LPD-15495

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Tests already passed here: https://github.com/marianoalvarosaiz/liferay-portal/pull/1136. Only 3 unique failures. Not related.

/cc @vicnate5

**Comment by vicnate5** [comment]
@marianoalvarosaiz looks good. I saw that new wars go into `osgi/war`. Perfect.

**Comment by tinatian** [comment]
@marianoalvarosaiz Did you test your change locally? If yes, please list the steps. We need a test to cover your change, please try to translate the steps your test to an integration test if possible.

Thanks.
Tina.

**Comment by tinatian** [comment]
@vicnate5 Could you please list the steps you used to test it locally?

Thanks.
Tina

**Comment by vicnate5** [comment]
Here are the requirements:

1. When executing `ant all` with DXP profile, all WAR files go into `osgi/portal-war`
1. Since no WARs are deployed during build, a `deploy` directory is created during the build process
1. When a new war file is placed in the `deploy` directory, the war will be moved to `osgi/war`

How I tested:
1. Run `ant all` with DXP profile
1. Check for `deploy` directory present and empty
1. Check that `osgi/portal-war` has default theme war files
1. Move `classic-theme.war` to `deploy` directory
1. Start portal
1. Assert all WARs are started, and the `classic-theme.war` is placed in `osgi/war`

We need to notify the release building team about this change so they can account for it in the release building scripts.

**Comment by tinatian** [comment]
@marianoalvarosaiz I tested with your pull, run ant all with DXP profile, failed at Victor's step 2. Could you please confirm if it works locally?

Also, we need test to cover this change, for easier review and maintain later

Thanks.
Tina.

**Comment by tinatian** [comment]
@marianoalvarosaiz I know what happened, you did not include this commit https://github.com/marianoalvarosaiz/liferay-portal/pull/1136/commits/c632ff66f4dc9d9c118a9568ffabc6a660d724ab from https://github.com/marianoalvarosaiz/liferay-portal/pull/1136.

Please see https://github.com/liferay-core-infra/liferay-portal/pull/6657

Tina

**Pull request closed without merging**
