### PR TITLE
LPS-151745 Add LIFERAY_SHARED_ prefix to attribute name in order to propagate the check access allowed to the portlet until the PortletFragmentEntryProcessor

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-151745

Previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/937

See comment: https://github.com/liferay-core-infra/liferay-portal/pull/937#issuecomment-1154820012

@dantewang @tinatian

Could you please review this pull request?

Thanks

Regards

### CODE REVIEW

**Comment by dantewang** [comment]
@lfbesada Is this just a rebase of https://github.com/liferay-core-infra/liferay-portal/pull/937?

**Comment by lfbesada** [comment]
@dantewang Yes, but in the last rebase I had conflicts in the first commit, in WebKeys.java. So the first commit is edited, and the rest are the same.

**Comment by dantewang** [comment]
@lfbesada Thanks!

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@tinatian This pull looks good to me.

**Comment by lfbesada** [comment]
Hi @dantewang
I have rebuilt this branch in my local environment with the current master branch and this time there are autogenerated files during the build. 
I have a commit in my local branch "LPS-151745 Auto" with those changes, should I push it to be added to this PR?
Thank you very much, 
Regards

**Comment by dantewang** [comment]
@lfbesada Yes please include the change. Since you added new constant to `PropsKeys`, the package version of `com.liferay.portal.kernel.util` will be bumped, as well as the module version of `portal-kernel`. The version is automatically bumped during `ant all` if the local version is identical with the remote/published version, but will not be bumped if the local version is already newer than the remote version. I think this is why the version was not bumped when you ran `ant all` last time.

**Comment by catarineaguiar** [comment]
ci:test:acceptance

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@lfbesada Code looks good to me, code conflicts, please rebase.

Thanks.
Tina.

**Review by tinatian — APPROVED** [review]

**Comment by lfbesada** [comment]
@tinatian @dantewang I have forced the push by solving the rebase conflicts. Only the last commit with auto-generated files has been changed. Thanks!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by lfbesada** [comment]
Resend https://github.com/liferay-core-infra/liferay-portal/pull/1029

**Pull request closed without merging**
