### PR TITLE
Lpd 38086 12 18

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:94717688

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 94717688.
> 
> Job Link: [generate-testray-csv](https://test-1-3.liferay.com/job/generate-testray-csv/189/)
> 
> Testray CSV Link: [testray-results-94717688.csv](https://test-1-3.liferay.com/userContent/jobs/generate-testray-csv/builds/189/testray-results-94717688.csv)

No unique failure. The 2 unique ones should be flaky (known groovy execution issue).

**Comment by dantewang** [comment]
ci:report:94724404

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 94724404.
> 
> Job Link: [generate-testray-csv](https://test-1-10.liferay.com/job/generate-testray-csv/160/)
> 
> Testray CSV Link: [testray-results-94724404.csv](https://test-1-10.liferay.com/userContent/jobs/generate-testray-csv/builds/160/testray-results-94724404.csv)

No unique failure in failed integration/unit tests.

Unique failure in sem ver because there's a version bump.

Unable to verify the following:

- PortalLogAssertorTest-modules-integration-mysql57/2/2

```
PortalLogAssertorTest#testScanXMLLog: Query did not validate : 'mutation{createSiteDocumentMetadataSet(siteKey: "45682". documentMetadataSet: {}){siteId. externalReferenceCode. id}}'
```

- PortalLogAssertorTest-modules-integration-mysql57/3/14

```
PortalLogAssertorTest#testScanXMLLog: Cannot invoke "String.contains(java.lang.CharSequence)" because "pathInfo" is null java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "pathInfo" is null at com.liferay.commerce.punchout.portal.security.auto.login.internal.events.PunchOutTokenLogoutAction.run(PunchOutTokenLogoutAction.java:35) at com.liferay.portal.kernel.events.Action.processLifecycleEvent(Action.java:25) at com.liferay.portal.events.EventsProcessorUtil.process(EventsProcessorUtil.java:83) at com.liferay.portal.events.EventsProcessorUtil.process(EventsProcessorUtil.java:43) at com.liferay.portal.security.auth.session.AuthenticatedSessionManagerUtil.logout(AuthenticatedSessionManagerUtil.java:247) at com.liferay.click.to.chat.web.internal.events.test.LogoutPreActionTest.testLogoutWithClickToChatDisabled(LogoutPreActionTest.java:54) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) at java.base/java.lang.reflect.Me...
```

- PortalLogAssertorTest-modules-integration-mysql57/3/8

```
PortalLogAssertorTest#testScanXMLLog: null javax.servlet.ServletException at com.liferay.commerce.payment.method.authorize.net.internal.servlet.CompletePaymentAuthorizeNetServlet.doGet(CompletePaymentAuthorizeNetServlet.java:65) at javax.servlet.http.HttpServlet.service(HttpServlet.java:529) at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) at com.liferay.commerce.payment.method.authorize.net.internal.servlet.test.CompletePaymentAuthorizeNetServletTest.testCrossOriginRedirect(CompletePaymentAuthorizeNetServletTest.java:65) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) at java.base/java.lang.reflect.Method.invoke(Method.java:580) at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344) at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90) at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90) at com.lifera...
```

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 94865629.
> 
> Job Link: [generate-testray-csv](https://test-1-37.liferay.com/job/generate-testray-csv/555/)
> 
> Testray CSV Link: [testray-results-94865629.csv](https://test-1-37.liferay.com/userContent/jobs/generate-testray-csv/builds/555/testray-results-94865629.csv)

Unique failures in report are not unique to this pull.

**Comment by tinatian** [comment]
ci:forward:force

**Comment by tinatian** [comment]
ci:help

**Comment by tinatian** [comment]
ci:test:stable

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/157168

**Pull request closed without merging**
