### PR TITLE
[TS] LPS-192555

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the previous pr is https://github.com/liferay-core-infra/liferay-portal/pull/5298. The pr is forwarded from liferay-appsec team, please see https://github.com/liferay-core-infra/liferay-portal/pull/5210#issue-1839894827. After that, we did some changes. If this is good to you, do we need to forward it to liferay-appsec review?

cc @ChrisKian

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@yuhai some issues:
1. Why is the URL too long? It seems all the parameters are from that portlet?
2. I doubt if modifying a commonly used tag for a specific portlet is acceptable from our team's perspective, unless we can prove that it's already also reproducible in other places.

**Comment by dantewang** [comment]
@yuhai Do you mean that `useNamespace` is a common pattern in many other tags?

**Comment by yuhai** [comment]
> @yuhai Do you mean that `useNamespace` is a common pattern in many other tags?

Yes, some tags had the attribute `useNamespace`.

**Comment by zhangyan0701** [comment]
ci:test:security

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by yuhai** [comment]
Hi @ChrisKian, 

From our team's perspective, for the pr, we need to check if removing namespace from PortletURL is right. **Refer to Chapter 13 Portlet URLs** from [PortletSpec3-Final-20161222.pdf ](https://download.oracle.com/otndocs/jcp/portlet-3-final-spec/), it didn't statement the related explanation, but check **javax.portlet.BaseURL**. It provided the below explanation:
```
A portlet container may prefix the attribute names internally in order to preserve a unique namespace for the portlet.
 public void setParameter (String name, String value);
```
So removing namespace from PortletURL should be ok.

After talking this with Tina and Dante, it isn't acceptable to add the attribute for the InputTimeTag if only solve the issue in the AuditPortlet. Because we are changing a general tag for the individual issue.

I am going to close the pr.  Please send it to liferay-frontend team review.

cc @tinatian @dantewang

Thanks,
Hai

**Comment by dantewang** [comment]
@ChrisKian Given the fact that there are also other tags that supports this `useNamespace` property, we recommend to extract them to a common base instead of many (base) classes. However we'll leave this to the frontend-infra team to decide.

**Pull request closed without merging**
