### PR TITLE
LPS-128171

### PR DESCRIPTION
**Pull request by julschong**
Hi all,
this is rebased from [#40](https://github.com/liferay-core-infra/liferay-portal/pull/42)
@tinatian

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by tinatian** [comment]
@julschong Conflicts, please rebase and resend.

Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
