### PR TITLE
[System Properties] LPS-154947 Replace method System.getProperty() with method SystemProperties.get()

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , LPS-154947 depend on LPS-158153(LPS-154947 uses the get-with-default-value method added by LPS-158153), I replace method System.getProperty() with method SystemProperties.get() in this pr.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me scan test results when you free ? Thanks!

**Comment by W2jx** [comment]
ci:test:acceptance

**Comment by W2jx** [comment]
ci:test:relevant

**Review by dantewang — CHANGES_REQUESTED** [review]
@W2jx Although the purpose of this change is to make sure everyone is using `SystemProperties` to avoid getting property values with unresolved property references, but I think this PR can be sent independently, not relying your other PRs.

Please double check and resend.

cc @tinatian

**Comment by dantewang** [comment]
@zhangyan0701 No need to check this one as it will be resent.

**Comment by W2jx** [comment]
Ok @dantewang , I will resent it.

**Pull request closed without merging**
