### PR TITLE
LPS-198097 The getDateHeader method was not behaving correctly according to the specification in the Javadoc

### PR DESCRIPTION
**Pull request by mbowerman**
Please see the description of [LPS-198097](https://liferay.atlassian.net/browse/LPS-198097) for a detailed explanation of why I believe the current behavior is incorrect. You can refer to the Javadoc specification here: https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getDateHeader(java.lang.String)

### CODE REVIEW

**Comment by dantewang** [comment]
Running TCK with the first commit at https://github.com/dantewang/liferay-portal/pull/2322

**Comment by dantewang** [comment]
@mbowerman The change makes sense to me. Since the original PR introducing this issue was for Portlet TCK compatibility, triggering TCK on this PR as well.

**Comment by dantewang** [comment]
ci:test:tck

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Some tck tests were not running, we re-run it.

**Comment by zhangyan0701** [comment]
There are some tck tests failed only here:

`[exec] Tests run: 4405, Failures: 172, Errors: 0, Skipped: 9, Time elapsed: 988.437 sec <<< FAILURE! - in javax.portlet.tck.driver.TCKLiferayTestDriver`

The errors in tests look like below:
```
     [exec] Testing: V2ExceptionTests_PortletModeException_ApiRender_hasGetMode2
     [exec]    Exception occurred: Expected condition failed: waiting for visibility of element located by By.name: V2ExceptionTests_PortletModeException_ApiRender_hasGetMode2 (tried for 5 second(s) with 500 milliseconds interval)
     [exec]       diagnostic url = http://localhost:8080/group/portlet-tck/v2exceptiontests
     [exec]    before test.
     [exec]    execute test.
     [exec]    Access page, link found: false, page===V2ExceptionTests===
     [exec] accessPage: debugLines:   logging in ... 
```
```
     [exec] test[V2ExceptionTests_PortletModeException_ApiRender_hasGetMode2](javax.portlet.tck.driver.TCKLiferayTestDriver)  Time elapsed: 5.253 sec  <<< FAILURE!
     [exec] java.lang.AssertionError: Test case V2ExceptionTests_PortletModeException_ApiRender_hasGetMode2 failed. 
     [exec] Exception: 
     [exec] 	at org.openqa.selenium.support.ui.ExpectedConditions.lambda$findElement$0(ExpectedConditions.java:896)
     [exec] 	at java.util.Optional.orElseThrow(Optional.java:290)
     [exec] 	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)
     [exec] 	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:44)
     [exec] 	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:206)
     [exec] 	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:202)
     [exec] 	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:248)
     [exec] 	at javax.portlet.tck.driver.TCKTestDriver.accessPage(TCKTestDriver.java:257)
     [exec] 	at javax.portlet.tck.driver.TCKLiferayTestDriver.test(TCKLiferayTestDriver.java:143)
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-10/test-1-28/test-portal-acceptance-pullrequest(master)/7829/tck-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by dantewang** [comment]
@zhangyan0701 It looks weird when there's no unique failure in TCK in https://github.com/dantewang/liferay-portal/pull/2322 but there are in this PR... The secondary commit in this PR should be able to maintain the same behavior before. Do you think these failures could be random?

**Comment by zhangyan0701** [comment]
@dantewang I am not sure, actually. I will run one more time to see how it goes.

**Comment by zhangyan0701** [comment]
ci:test:tck

**Comment by zhangyan0701** [comment]
No unique failures in the new tck run. The failures in the previous one should be random. It was really confusing because the failures had never happened before.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142165

**Pull request closed without merging**
