### PR TITLE
[Replace Non-Blocking Usage] LPS-201148 Replace non-blocking ServiceProxyFactory usages in class PermissionCheckerFactoryUtil

### PR DESCRIPTION
**Pull request by W2jx**
Based on https://liferay.atlassian.net/browse/PTR-2102 and https://liferay.atlassian.net/browse/LPS-78573
, I think we have customers who customize their own implementation of interface PermissionCheckerFactory, so we are supposed to use dynamic snapshot in class PermissionCheckerFactoryUtil.

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(11/8 10:05)

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
