### PR TITLE
[Convert method references]Lps 163776

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-163776

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Comment by zhangyan0701** [comment]
@catarineaguiar Could you check the test results when test finish? Thanks!

**Comment by catarineaguiar** [comment]
@slnn possible regression on:

```
 [exec] 1: Task failed with an exception.
     [exec] -----------
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:commerce:commerce-product-service:jar'.
     [exec] > Bundle com.liferay.commerce.product.service-6.0.80.jar has errors
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:commerce-product-service:jar'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$3(ExecuteActionsTaskExecuter.java:186)
     [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:268)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)
     [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
     [exec] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
     [exec] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
     [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
     [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-32/test-portal-acceptance-pullrequest(master)/5942/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Hi @catarineaguiar 

I do not reproduce this issue locally

> @slnn possible regression on:
> 
> ```
>  [exec] 1: Task failed with an exception.
>      [exec] -----------
>      [exec] * What went wrong:
>      [exec] Execution failed for task ':apps:commerce:commerce-product-service:jar'.
>      [exec] > Bundle com.liferay.commerce.product.service-6.0.80.jar has errors
>      [exec] 
>      [exec] * Try:
>      [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>      [exec] 
>      [exec] * Exception is:
>      [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:commerce-product-service:jar'.
>      [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$3(ExecuteActionsTaskExecuter.java:186)
>      [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:268)
>      [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
>      [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)
>      [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
>      [exec] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
>      [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
>      [exec] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
>      [exec] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
>      [exec] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
>      [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
>      [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-32/test-portal-acceptance-pullrequest(master)/5942/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

Hi @catarineaguiar 

I do not reproduce the issue locally, I just rebase the code with the head of master to rerun the relevant test, my changes are only in the module:portal-cache-ehcache-impl, it should not affect the build process for the module: commerce-product-service.

Could you help to double check the test results when they are finished?

Thanks
Lily

**Comment by catarineaguiar** [comment]
@slnn no regressions found.

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@slnn Please use get method pattern.

Tina

**Pull request closed without merging**
