### PR TITLE
LPS-155682 Remove module.framework.properties.ds.*

### PR DESCRIPTION
**Pull request by dantewang**
@W2jx I only modified the commit messages to include a bit more info.

### CODE REVIEW

**Comment by dantewang** [comment]
@catarineaguiar Could you review the test results? Thanks!

**Comment by dantewang** [comment]
@petershin Both @yuhai and @W2jx encountered a problem when running `patch` task on Windows. Could you take a look? I've asked Hai to send you the detail.

**Comment by catarineaguiar** [comment]
@dantewang no regressions found

**Comment by petershin** [comment]
> @petershin Both @yuhai and @W2jx encountered a problem when running `patch` task on Windows. Could you take a look? I've asked Hai to send you the detail.

Following up w Hai in slack

**Comment by tinatian** [comment]
@W2jx Please rebase.

Tina

**Comment by W2jx** [comment]
https://github.com/liferay-core-infra/liferay-portal/pull/1016

**Comment by W2jx** [comment]
ci:close

**Pull request closed without merging**
