### PR TITLE
LPS-147301 Remove AspectJ usage from ClusterSchedulerEngineTest

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian https://issues.liferay.com/browse/LPS-147301 The AspectJ usage here doesn't seem to be needed as we can easily use the actual thread local.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test result. No need to run "ci:test" for this pull as only test class is modified.

Thanks.
Tina.

**Comment by vicnate5** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
Acceptance results are fine, but none of the clustering tests ran. Running them manually

I will send a PR to fix the problem with Relevant not running the clustering tests here.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
