### PR TITLE
[TS] LPS-154557 Add config to allow TunnelServlet to send exceptions again

### PR DESCRIPTION
**Pull request by vendeltoreki**
Resending https://github.com/liferay-core-infra/liferay-portal/pull/1092

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Review by dantewang — CHANGES_REQUESTED** [review]
@vendeltoreki Looks good to me. Just one thing, please squash your last 2 commits. The test case is newly added, so no need to keep the history of adding a property-setting logic.

**Comment by dantewang** [comment]
@catarineaguiar Could you review the test results? Thanks!

**Comment by vendeltoreki** [comment]
@dantewang , I force-pushed the squashed commit: https://github.com/liferay-core-infra/liferay-portal/pull/1126/commits/d0ed774fae93a2ccaadce8fdd6b23424446131b3

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@vendeltoreki Your integration test is not strict. When you testing true/false property, what you should do is:

When it is true:
       Assert A condition is false
       Assert B condition is true

When it is false:
       Assert A condition is true
       Assert B condition is false

Basically you should have same condition tested when it is enabled and disabled.

While your two test methods are testing different stuff, it is not easy for people to know that if the condition is overlap or not.

Please update your integration test.

Tina.

**Comment by vendeltoreki** [comment]
@tinatian , updated the test cases: https://github.com/liferay-core-infra/liferay-portal/pull/1126/commits/0d3ae2f7b783ff1a7435af56e035443838163bcb#diff-fb4182510e739811270da36ebd91b489a640600868cc2c355abbe654951c3edaR288

The `testRemoteStagingVisibleError()` case has an assert for the `type` field of the exception. This doesn't exist in the other case, since the exception class is different.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/1160

**Pull request closed without merging**
