### PR TITLE
[Bug Fix] LPS-120011

### PR DESCRIPTION
**Pull request by yuhai**
@tinatian, I change the commit message and resend it (this is based on https://github.com/liferay-core-infra/liferay-portal/pull/23).

cc @dantewang

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@koor4356 can you check the results here?

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
@vicnate5 @tinatian  @yuhai,
No unique error except all SQL Server tests failed prior to running test. 
- https://testray.liferay.com/zh/home/-/testray/case_results?testrayBuildId=1585734795&testrayRunId=1585741518
- Some Modules Integration tests also failed to run the test on CI.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/110715

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
