### PR TITLE
LPS-165013 Merge VelocityPortlet into HelloVelocityPortlet

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:reevaluate:1397401_1012

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong based on this [result](https://test-1-38.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4268/jenkins-report.html), there is only a semver error:

```
   [echo] ## /opt/dev/projects/github/liferay-portal/baseline-reports/portal-impl.log
     [echo] ##
     [echo] 
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portlet                                MAJOR      8.2.0      8.2.0      9.0.0      VERSION INCREASE REQUIRED
```
full log [here](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/272736/consoleFull)

you can run relevant again when fix it.

**Comment by julschong** [comment]
forced pushed semver

**Comment by julschong** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125070

**Pull request closed without merging**
