### PR TITLE
[Method Reference Static ]Lps 182576 5 5 rebase

### PR DESCRIPTION
**Pull request by slnn**
Resolve conflict according to https://github.com/brianchandotcom/liferay-portal/pull/134376

### CODE REVIEW

**Comment by slnn** [comment]
Forced push to resolve the conflict about bnd file, no logic changes.

**Comment by dantewang** [comment]
ci:forward:force

It was sent to Brian before, and only rebased.

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:forward

**Comment by dantewang** [comment]
ci:forward:force

The SF failure is irrelevant to this PR.

**Pull request closed without merging**
