### PR TITLE
remove_deprecated_part_3

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian , @shuyangzhou,

I have removed deprecated methods or classes for "portal-impl/src/com/liferay/portal/service/impl", "portal-impl/src/com/liferay/portal/servlet", and "portal-impl/src/com/liferay/portal/tools".
Thanks for checking.

Thanks,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@kyle-miho Hey Kyle, could you please help me to scan the test result?

Thanks,
Jeff

**Comment by tinatian** [comment]
@jeffwu0724 Please resend this to separate the generated code from manually modified code.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
