### PR TITLE
[Github action] Notify when merge conflict arises

### PR DESCRIPTION
**Pull request by JanisZhang**
Hello team,

I wanted to share a Github action. This action automatically checks all open Pull Requests for merge conflicts and applies a GitHub label accordingly. Once a conflict is resolved, the label is automatically removed. It seems like a handy tool that could save developers from the manual effort of checking each PR.

Just wanted to bring it to your attention for consideration. Do you think it could potentially simplify our workflow?

Thanks!

An example can be found [here](https://github.com/JanisZhang/liferay-workspace/pull/3).

### CODE REVIEW

**Comment by dantewang** [comment]
To use Github Actions, we must commit a file into the repo, right?

**Comment by JanisZhang** [comment]
> To use Github Actions, we must commit a file into the repo, right?

Yes, we need to add a yml to `.gitHub/workflows`.

**Comment by JanisZhang** [comment]
> To use Github Actions, we must commit a file into the repo, right?

Yes, we need to add a yml to `.gitHub/workflows`.

**Comment by dantewang** [comment]
@JanisZhang Since it's a third-party action, I doubt whether Brian will accept it.

By the way, will this action be executed only when opening the PR, or will it auto-recheck without any triggering?

**Comment by JanisZhang** [comment]
Hi @dantewang , we can only commit this file to [liferay-core-infra](https://github.com/liferay-core-infra)/[liferay-portal](https://github.com/liferay-core-infra/liferay-portal) repo

The workflow will be triggered in the following situation:

- When there is a new code push to the master branch (liferay-core-infra).
- When a developer opens a new Pull Request.
- When a developer force-pushes to an existing Pull Request(auto-removes conflicts label).

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:stop

**Comment by dantewang** [comment]
@JanisZhang We need to keep master branch 1:1 sync with liferay/liferay-portal:master, otherwise it could be hard to sync with upstream in the future, with other potential issues. That's why many of our bots and team repos are using web-hook (for example, liferay-echo uses a web-hook to auto-label PRs).

> When there is a new code push to the master branch (liferay-core-infra).

Does that mean it will automatically check all open PRs pending?

**Comment by dantewang** [comment]
@JanisZhang I think we can explore more options, and bring it to the team meeting for discussion. For Github Action, the only way we can use it is to merge the yml into upstream/master, so that should be the last option.

**Pull request closed without merging**
