### PR TITLE
LPS-169760

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 Please help me add functional tests.

Thanks.
Tina

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

I have doing some manual tests and also executed this integration test https://github.com/liferay-core-infra/liferay-portal/pull/2851/commits/6ebfe5f3cf3790e0f564469d87899458ae66320d that I implemented in my PR and I have detected that configuration changes are not loaded unless you restart the Liferay server.

The issue is fixed adding the "Modified" annotation to the TikaConfigurationHelper.activate see https://github.com/jorgediaz-lr/liferay-portal/commit/3c94268f831ddcb4045a964a14ec236ebb56c65c

After applying this change, my integration tests of https://github.com/liferay-core-infra/liferay-portal/pull/2851 are working correctly.

I think the same problem is happening in the activate method of TikaRawMetadataProcessor but this is more difficult to solve as it is not reloaded when the configuration is changed.

Thank you,
Jorge

**Comment by vicnate5** [comment]
@tinatian I do have a concern with this PR. I attempted to hardcode a file path to a tika.xml in an external directory. This leads to error
```
ERROR [Portal Dependency Manager Component Executor--1][TikaConfigurationHelper:56] bundle com.liferay.portal.tika:1.0.21 (152)[com.liferay.portal.tika.internal.configuration.helper.TikaConfigurationHelper(156)] : The activate method has thrown an exception
java.lang.IllegalArgumentException: Unable to read tika configuration /opt/dev/projects/release/tika.xml
        at com.liferay.portal.tika.internal.configuration.helper.TikaConfigurationHelper.activate(TikaConfigurationHelper.java:84) ~[?:?]
```
Given the current configuration tooltip, this can be seen as user's error. But the results is that **bad value here will persist and the server can no longer startup fully**. I think it should fallback to a default or not block startup despite the missing tika.xml. 

We might need to treat this as a separate bug since it might be a broader startup problem, I am not sure if it is isolated to this new Tika configuration. I tried another configuration, put a bad value, and the server still starts despite the error.

I did find that the user can workaround the issue with `com.liferay.portal.tika.internal.configuration.TikaConfiguration.config` in osgi/configs to add the correct value.

**Comment by vicnate5** [comment]
@zhangyan0701 Can you add the automation https://issues.liferay.com/browse/LRQA-79002? - start with steps from https://github.com/liferay-core-infra/liferay-portal/pull/2922#issuecomment-1372982151)

**Comment by zhangyan0701** [comment]
New functional tests is sent here:
https://github.com/vicnate5/liferay-portal/pull/2229

**Comment by jorgediaz-lr** [comment]
Hi @vicnate5 

I reproduced the issue using this integration test: https://github.com/liferay-core-infra/liferay-portal/commit/6ebfe5f3cf3790e0f564469d87899458ae66320d. The main difference with your functional test is you are checking **[TikaRawMetadataProcessor.java](https://github.com/liferay-core-infra/liferay-portal/pull/2922/files#diff-1352aa489b2827cf48d7d6fb2d378946c8fa6d704061a0e89551be3fe295a5aa)** , but my integration test is testing the **[TextExtractorImpl.java](https://github.com/liferay-core-infra/liferay-portal/pull/2922/files#diff-981e005b6a20a2ab776b4a9ce1c19f73b4f6e51db2a07c2bab89fd865f73221f)** logic.

If you want to test the [TextExtractorImpl.java](https://github.com/liferay-core-infra/liferay-portal/pull/2922/files#diff-981e005b6a20a2ab776b4a9ce1c19f73b4f6e51db2a07c2bab89fd865f73221f) you have to check the information that it is indexed in Elasticsearch

My integration test here https://github.com/liferay-core-infra/liferay-portal/commit/6ebfe5f3cf3790e0f564469d87899458ae66320d tested this using this custom tika.xml: https://github.com/liferay-core-infra/liferay-portal/commit/6ebfe5f3cf3790e0f564469d87899458ae66320d#diff-9eecbf2d2a88b77e7bb555cf1856ba5698ce2c98812de17b8234ea2a2d7e68e3
The tika.xml was configured to only extract text for HTML and TXT files, and it tested four use cases:

1. Text is extracted for a HTML file, that is configured to be processed in a child process
2. Text is not extracted for a PDF file, that is configured to be processed in a child process
3. Text is extracted for a TXT file, without forking a child process
4. Text is not extracted for a ODT file, without forking a child process

I don't know how to implement it in a functional test, perhaps you can execute a Elasticsearch query or try executing a search in Liferay search portlet.


It should be also necessary to update this existing functional test: https://github.com/jorgediaz-lr/liferay-portal/blob/10ff0c6bd7dcd01f0d1f563d3e652530d0239d37/portal-web/test/functional/com/liferay/portalweb/tests/enduser/documentmanagement/documentsadministration/DMFileEntry.testcase#L185-L207 because the text.extraction.fork.process.enabled and text.extraction.fork.process.mime.types properties are removed in this PR (_In my original PR here https://github.com/liferay-core-infra/liferay-portal/pull/2851/commits/937c58d5284049b3d5a2295fbf40049f86b9cb2c I removed this PR as I considered it was covered by my integration test_) 

Let me know if you have any question

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

I have noticed now that in your PR you have removed a DEBUG trace that I added to the TextExtractorImpl class with the extracted text in my original PR, see 
https://github.com/liferay-core-infra/liferay-portal/blob/34f1320c2a0535637c693825dd2edc612a6a3655/modules/apps/portal/portal-tika/src/main/java/com/liferay/portal/tika/internal/extract/TextExtractorImpl.java#L127-L129

Can you add it again?

This debug trace would be very useful for Support department to analyze any customer problem related to text extraction.

Thank you

**Comment by vicnate5** [comment]
I suggest we add both the integration test and the functional test so we can cover both scenarios.

**Comment by vicnate5** [comment]
@jorgediaz-lr In my testing, https://github.com/jorgediaz-lr/liferay-portal/commit/3c94268f831ddcb4045a964a14ec236ebb56c65c fixes the integration tests, but breaks the scenario in https://github.com/liferay-core-infra/liferay-portal/pull/2922#issuecomment-1372982151

**Comment by tinatian** [comment]
@jorgediaz-lr Yes, please add the debug info you need. I will check the failed integration test you mentioned.

**Comment by tinatian** [comment]
@jorgediaz-lr 
With my change, I think this integration test: https://github.com/liferay-core-infra/liferay-portal/commit/6ebfe5f3cf3790e0f564469d87899458ae66320d failed is because TextExtractor instance the test injected are not updated.

When there is no @Modified annotation, each time a configuration is changed, TikaConfigurationHelperImpl will be deactivated and reactivated, which means it will update _tikaConfig. When TikaConfigurationHelperImpl is deactivated, TextExtractor will be deactivated and reactivated, which means you will see a difference instance.

While adding @Modified annotation will not trigger deactivate and reactivate. 

Here, we need to deactivate and reactivate to make sure  TikaConfigurationHelperImpl's dependencies updated themselves, for example TikaRawMetadataProcessor, when config changed, it should reactivate itself to update its parser.

To fix the issue, either you do not use @Inject, or we need to fix the logic @Inject.



Tina.

**Comment by tinatian** [comment]
@jorgediaz-lr @vicnate5 I added https://github.com/liferay-core-infra/liferay-portal/pull/2922/commits/fed9218f15e202fb3e49f581a8f40d8a6c0e8a7d to fix the issues mentioned above, please confirm if it works.

Thanks.
Tina

**Comment by vicnate5** [comment]
All tests passed locally for me. I combined everything and resent this at https://github.com/liferay-core-infra/liferay-portal/pull/3036

**Comment by jorgediaz-lr** [comment]
Hi @vicnate5 @tinatian 

I am sorry I couldn't read your comments before.

Thanks for reviewing my comments and creating the new PR.

**Pull request closed without merging**
