### PR TITLE
Lpd 19869 stop watch 3 7 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:report:2548783723

**Comment by julschong** [comment]
ci:report:2548780932

**Comment by julschong** [comment]
no unique failure from [upgrade](https://github.com/liferay-core-infra/liferay-portal/pull/6755#issuecomment-1989690482)

no unique failure from [relavent](https://github.com/liferay-core-infra/liferay-portal/pull/6755#issuecomment-1989695330). (1 Failure is not related)

**Comment by tinatian** [comment]
@julschong Please rebase and resend.

Thanks.
Tina

**Comment by julschong** [comment]
see https://github.com/liferay-core-infra/liferay-portal/pull/6762

**Pull request closed without merging**
