### PR TITLE
LPS-138338

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

I have updated xstream version from 1.4.17 to 1.4.19.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by tinatian** [comment]
@jeffwu0724 Please check with Peter Shin when you modify code in gradle plugins, anything you need to do. I believe you need to update the gradlew cache for corresponding bundles, but I am not sure which bundles should be, please check with him.

Tina.

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
@jeffwu0724 failures are unrelated

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116052

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
