### PR TITLE
LPS-143632 Remove LanguageUtil from moduels part 1b

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar
Hi Catarine,
could you please help me scan the test result?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by julschong** [comment]
@slnn 
Hi Lily,
Could you please help me review this pull?
Thank you!

CC. @tinatian

**Comment by slnn** [comment]
Hi @julschong 

When I rebase this pull with the head of master, I can see two commits: one is **LPS-143632 Remove LanguageUtil usages in modules, part 1b**, another one is **LPS-155249 Remove empty line**

Please see the screenshot, could you rebase with master and forced pushed to this pull?

LPS-143632-pr-1004

Regards
Lily

**Comment by slnn** [comment]
By the way, please also rebase and force pushed for these pulls:

https://github.com/liferay-core-infra/liferay-portal/pull/1005
https://github.com/liferay-core-infra/liferay-portal/pull/1007
https://github.com/liferay-core-infra/liferay-portal/pull/1009
https://github.com/liferay-core-infra/liferay-portal/pull/1013

Thanks!

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Hi @tinatian 

I have checked the changes in this pull, and nothing wrong is found.

Lily

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/119892

**Pull request closed without merging**
