### PR TITLE
[TS Bug Fix] LPS-166886

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@catarineaguiar In ExpandoValueLocalServiceTest, both ExpandoValueLocalServiceUtil and "_expandoValueLocalService" are used, could you please make every one use  "_expandoValueLocalService"?

Thanks.
Tina

**Comment by crodriguezy** [comment]
Hi @tinatian @dantewang . About the serviceUtil classes'`use, shouldn't we remove others like 

ExpandoColumnLocalServiceUtil
ExpandoRowLocalServiceUtil

Please let me know to add the corresponding commits here

**Comment by crodriguezy** [comment]
Sorry I just realized you assigned it to @catarineaguiar .

**Comment by catarineaguiar** [comment]
@crodriguezy I think @tinatian marked me by mistake.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2494

**Pull request closed without merging**
