### PR TITLE
[Remove Stream/Optional usage] LPS-176614 Remove Stream usages for module: commerce-machine-learning-test

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:commerce

**Comment by dantewang** [comment]
cc @zhangyan0701

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
