### PR TITLE
Lps 163054

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-163054

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Comment by zhangyan0701** [comment]
Hi @catarineaguiar Could you check the results when the tests finish?

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@slnn failure in portal startup:

```
[beanshell] 2022-09-20 20:06:39.907 ERROR [Portal Dependency Manager Component Executor--1][WebSsoProfileImpl:56] bundle com.liferay.saml.opensaml.integration:5.3.35 (1200)[com.liferay.saml.opensaml.integration.internal.servlet.profile.WebSsoProfileImpl(5316)] : The activate method has thrown an exception
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.saml.opensaml.integration.internal.servlet.profile.WebSsoProfileImpl.activate(WebSsoProfileImpl.java:293) ~[?:?]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
[beanshell] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:310) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:300) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:341) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:983) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:956) ~[?:?]
[beanshell] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:901) ~[?:?]
[beanshell] 	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212) ~[org.eclipse.osgi.jar:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-32/test-portal-acceptance-pullrequest(master)/5883/functional-smoke-tomcat90-mysql57-jdk8_stable/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
Thanks @catarineaguiar !

**Comment by slnn** [comment]
Fix and resend in https://github.com/liferay-core-infra/liferay-portal/pull/1768

**Pull request closed without merging**
