### PR TITLE
[Static reference] LPS-181520 Remove method reference by using snapshot in modules map-taglib, portal-workflow-taglib

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
ci:test:workflow

**Comment by W2jx** [comment]
no conflicts（4/14 11:18）

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(4/17 8:08)

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
