### PR TITLE
LPS-168945 Clean up and simplify SocialBookmarksRegistryImpl

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian 

Based on this comment https://github.com/liferay-core-infra/liferay-portal/pull/2437#pullrequestreview-1184794295, clean up the logic for deprecated legacy property "social.bookmark.types", and simplify the service tracker usage.

For service tracker usage, instead of removing the `ServiceTrackerList` in https://github.com/liferay-core-infra/liferay-portal/pull/2488 as you commented, I removed the `ServiceTrackerMap` in this pull, and just reuse the customizer to populate a normal map. This is simpler and can avoid duplicating the comparator logic in the previous pull.

cc @W2jx

### CODE REVIEW

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:blogs

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:blogs

**Comment by dantewang** [comment]
ci:test:blogs

**Comment by tinatian** [comment]
@W2jx 

1) For the commit message "Remove the logic about social.bookmark.types, because the property social.bookmark.types has been deprecated", you can NOT remove related logic because of a property is deprecated, "deprecated" does not mean the feature is not working, you may still have the feature work, but the code is deprecated.

The reason we removed related logic because that property is REMOVED.

2) Please remove class "DeprecatedSocialBookmark", after you removed related logic to that property, no one is going to use that class.


Thanks.
Tina.

**Pull request closed without merging**
