### PR TITLE
[Component with its own class name as service type ] LPS-194013 Refactor Registry classes from Dynamic Data Mapping module

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-194013

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:forms

**Comment by MrJohn1911** [comment]
ci:test:data-engine

**Comment by catarineaguiar** [comment]
no regressions found. SF issue is not related

**Comment by shuyangzhou** [comment]
@MrJohn1911 @rafaprax I see for both DDMDataProviderDisplay and DDMDisplay, the service tracker map keying process got changed from calling "getPortletId()" on the service instance to just read "javax.portlet.name" service property. It is a good change (assuming they always match).
Please send a followup to try to remove the "getPortletId()" methods from both interface if possible.
Long term wise we prefer to always keying from property rather than calling service instance method in order to avoid pulling up service instances during collecting phase.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141244

**Pull request closed without merging**
