### PR TITLE
LPS-195018 Patch org.apache.velocity to replace log4j1 with log4j2

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, please check the ticket's description.

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@yuhai No regressions found.

**Comment by tinatian** [comment]
@yuhai Any reason we can not upgrade to Velocity 2.3? If we can upgrade, then we do not need to patch

**Comment by yuhai** [comment]
@tinatian, Velocity 2.3 and 1.x is not compatible. I just compared some we used classes(not all) and their api are different. 

For example,
```
org.apache.velocity.app.VelocityEngine
org.apache.velocity.runtime.RuntimeInstance
org.apache.velocity.runtime.RuntimeServices
org.apache.velocity.app.event.MethodExceptionEventHandler
```

Reference: https://velocity.apache.org/engine/2.3/upgrading.html#upgrading-from-velocity-17-to-velocity-20

**Comment by dantewang** [comment]
@yuhai Can these APIs be migrated?

**Comment by yuhai** [comment]
@dantewang, from my understanding, this belongs to migrate.

> Initialization methods in Velocity and VelocityEngine taking an ExtendedProperties have been removed (but setProperties(Properties) methods are still here). All occurences of the org.apache.commons.collections.ExtendedProperties class in the runtime internal initialization API have been replaced by org.apache.velocity.util.ExtProperties.

Some api were changed. For example, `org.apache.velocity.runtime.resource.loader.ResourceLoader`.
```
1.6 public abstract InputStream getResourceStream( String source )
2.3 public abstract Reader getResourceReader(String source, String encoding)
```

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
