### PR TITLE
Lps 158207 8 3 1

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Tina

**Comment by catarineaguiar** [comment]
@shuyangzhou no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121701

**Pull request closed without merging**
