### PR TITLE
LPS-157454 Publication Tuning

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:publications

**Comment by tinatian** [comment]
FYI @david-truong This is the pull to add cache for NavItem

**Comment by tinatian** [comment]
@zhangyan0701 please help me scan test result.

@dantewang If this passed ci test scan, please backport to 7.3.x and test with customer database see how much we get.

Thanks.
Tina.

**Comment by tinatian** [comment]
@GinsonRen Please run a diff on login.

Thanks.
Tina.

**Comment by zhangyan0701** [comment]
ci:test:acceptance

**Comment by dantewang** [comment]
@tinatian The edit page loads in ~19s using my locally built bundle.

Bundle: 7.3.x head + LPS-156253 backport PR + this change backported, customer's modules and data folder copied; the config of LPS-156253 is **not** set (so it's putting NavItem in the context).

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian This should be good. We did still have about 15% of the tests aborting, but it is an issue on Jenkins, not with the portal. No regressions the other 85% of test that ran. All the Publication backend and functional tests are passing, and I re-ran some of the aborted tests successfully against this PR.

**Comment by tinatian** [comment]
Rebase at https://github.com/liferay-core-infra/liferay-portal/pull/1069

**Pull request closed without merging**
