### PR TITLE
[SampleSQLBuilder-defaultVirtualHost]LPS-206089 Enable the defaultVirtualHost for each item of VirtualHost…

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-206089

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Comment by dantewang** [comment]
ci:test:stable

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
