### PR TITLE
[Components with more than 1 service] LPS-183006, LPS-183634 Refactor BulkSelectionFactory and BulkSelectionAction components

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-183006](https://issues.liferay.com/browse/LPS-183006),
[LPS-183634](https://issues.liferay.com/browse/LPS-183634)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:dl-store

**Comment by RenanUmV** [comment]
ci:test:document

**Comment by zhangyan0701** [comment]
ci:test:bulk-editing

**Comment by zhangyan0701** [comment]
ci:test:blogs

**Review by rafaprax — CHANGES_REQUESTED** [review]

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:dl-store

**Comment by RenanUmV** [comment]
ci:test:document

**Comment by Kvale1733** [comment]
@RenanUmV No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
