### PR TITLE
LPS-145904

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian, @shuyangzhou ,

I have removed unused properties "Cluster.link.node.bootup.response.timeout", and updated to propskeys.java and verifyproperties.java.

"CLUSTER_LINK_NODE_BOOTUP_RESPONSE_TIMEOUT" was added in commit 7c45ef6853a25a3b4b5658409c114c0275adfce4, see LPS-35561, and it was used in "EhcacheStreamBootstrapHelpUtil.java".

then, it was renamed to portal-impl/src/com/liferay/portal/cache/ehcache/StreamBootstrapHelpUtil.java, based on commit 738aa763e4be218d31b68355aaa67ec09405a8e7, see LPS-49136.

then, it renamed to portal-impl/src/com/liferay/portal/cache/ehcache/StreamBootstrapHelpUtil.java, based on commit 5321311fd508cee45cad6fb87368caba6cf94241, see LPS-49136.

then, it moved to portal-impl/src/com/liferay/portal/cache/bootstrap/ClusterLinkBootstrapLoaderHelperUtil.java, based on commit 23b1ccbc2c7fc69c4a336b679d7d474ff8eabb4a, see LPS-49135.

then, it was moved to rename to portal-service/src/com/liferay/portal/kernel/cache/bootstrap/ClusterLinkBootstrapLoaderHelperUtil.java, based on 9352e3923b1aff7578380a847b05734595eda040, see LPS-55479.

It was rename to modules/portal-cache/portal-cache-cluster/src/com/liferay/portal/cache/cluster/internal/bootstrap/ClusterLinkBootstrapLoaderHelperUtil.java, based on commit d89c9eb46b34ed44df301a53a1752bb703117d22, see LPS-57770.

It was finally removed based on commit c0986d124ef82aa598fb9dac6b3647ae0c51770a, see LPS-57770.
Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@jeffwu0724 The change log of this property is a mess. After removing by LPS-57770, it was added back and finally removed by LPS-96563 (571ff47713fed2999a1f5bb80f2eb7b6ed444acf). Please update the commit message and resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
