### PR TITLE
[Urgent][Security Bugs]LPD-26019 Use of library with known vulnerability: apache-mime4j-core: 0.8.3

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:stop

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
code looks good to me (but next time will be better if we can combine [commit A](https://github.com/liferay-core-infra/liferay-portal/pull/7011/commits/78a027756c7d2f55fa0037c5258591464698a989) and [commit B](https://github.com/liferay-core-infra/liferay-portal/pull/7011/commits/581b4ca272c38e636f48da577e332e05e9622de5) together, let wait for the ci test result.

Have checked locally with global search, portal-tika are the only place that used these jars

**Comment by RenanUmV** [comment]
ci:report:2570481043

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
