### PR TITLE
LPS-178287 Remove apps/petra entirely after removing Dom4jUtil and petra-xml

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@julschong please, resolve the conflicts and re-run sf and relevant. CI might be working now.

Thanks,
Cat

**Comment by julschong** [comment]
pushed rebased

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong No regressions found. SF issue looks unrelated.

**Pull request closed without merging**
