### PR TITLE
LPS-174386

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 Could you you please prioritize this pull? Thanks!

Tina

**Comment by vicnate5** [comment]
No regressions found. Release build test failed, but it does not look related, likely a fluke.

**Comment by tinatian** [comment]
Only updated commit message, no need to trigger test.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130800

**Pull request closed without merging**
