### PR TITLE
LPS-203867 Add support to configure keepalive for HTTP client

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team,

**Previous PR:** https://github.com/liferay-core-infra/liferay-portal/pull/6346

**Ticket:** https://liferay.atlassian.net/browse/LPS-203867

**Summary**
This PR introduces two new portal properties to configure keep alive for HTTP Client:
- com.liferay.portal.kernel.util.Http.keepalive.timeout
- com.liferay.portal.kernel.util.Http.tcp.default.keepalive.enabled

I also tried to include relevant test cases for the described use-case in the ticket description.

**Changes from previous PR**
@yuhai, changes have been made, based on the provided suggestions:
- The property `com.liferay.portal.kernel.util.Http.keepalive.default.timeout` has been renamed to:  `com.liferay.portal.kernel.util.Http.keepalive.timeout`
- The ConnectionKeepAliveStrategy has been moved to activate method
- For the test cases in: **testHttpKeepAlive()**, these has been removed
- For the test: **testHttpKeepAliveWithDefaultTimeout()**, I decided to rename it to: **testHttpKeepAlive()**

**Note:** I did not make this change that you suggested:

> 3. In the test class, extract HttpContext and HttpResponse to testClass object's fields.
> ```
> private final HttpContext _httpContext = new BasicHttpContext(null);
> private final HttpResponse _httpResponse = new BasicHttpResponse(
> 		new BasicStatusLine(HttpVersion.HTTP_1_1, HttpStatus.SC_OK, "OK")); 
> ```
- The test cases set different attributes/headers on those objects
- Example:
  - testHttpKeepAliveWithRequestClose()
    - [httpContext.setAttribute(HttpCoreContext.HTTP_REQUEST, httpRequest);](https://github.com/liferay-core-infra/liferay-portal/commit/dde0cf2d3ab0815c94452e7136a7c52555038c41#diff-ea252c8bab02dc1a74ea1e4c562253e488fa43c043abc576d2283796cd3c58bbR109)
    - [httpResponse.setHeaders(...)](https://github.com/liferay-core-infra/liferay-portal/commit/dde0cf2d3ab0815c94452e7136a7c52555038c41#diff-ea252c8bab02dc1a74ea1e4c562253e488fa43c043abc576d2283796cd3c58bbR114)
  - testHttpKeepAliveWithResponseClose()
    - [httpContext.setAttribute(HttpCoreContext.HTTP_REQUEST, httpRequest);](https://github.com/liferay-core-infra/liferay-portal/commit/dde0cf2d3ab0815c94452e7136a7c52555038c41#diff-ea252c8bab02dc1a74ea1e4c562253e488fa43c043abc576d2283796cd3c58bbR131)
    - [httpResponse.setHeaders(...)](https://github.com/liferay-core-infra/liferay-portal/commit/dde0cf2d3ab0815c94452e7136a7c52555038c41#diff-ea252c8bab02dc1a74ea1e4c562253e488fa43c043abc576d2283796cd3c58bbR136-R141)
  - private void _testHttpKeepAlive(...)
    - [httpResponse.setHeaders(...)](https://github.com/liferay-core-infra/liferay-portal/commit/dde0cf2d3ab0815c94452e7136a7c52555038c41#diff-ea252c8bab02dc1a74ea1e4c562253e488fa43c043abc576d2283796cd3c58bbR281-R285)
    - [httpResponse.addHeader(...)](https://github.com/liferay-core-infra/liferay-portal/commit/dde0cf2d3ab0815c94452e7136a7c52555038c41#diff-ea252c8bab02dc1a74ea1e4c562253e488fa43c043abc576d2283796cd3c58bbR288-R291)

Unless we want to reset these objects by clearing the headers / attributes, when the test finishes. Or if there's something I'm missing and this can be accomplished easily, please let me know.

---

Please let me know if you have any questions and/or if you would like me to make any additional changes. 
Thanks!

### CODE REVIEW

**Comment by yuhai** [comment]
@ericyanLr, for the below change, the new test(`testHttpKeepAliveWithRequestClose`) won't use the previous test(`testHttpKeepAliveWithRequestClose`) object, every test won't affect each other. Because when one test started, it will reinitialize new objects to them. 
```
private final HttpContext _httpContext = new BasicHttpContext(null);
private final HttpResponse _httpResponse = new BasicHttpResponse(
		new BasicStatusLine(HttpVersion.HTTP_1_1, HttpStatus.SC_OK, "OK")); 
```
After the changed, we may directly set necessary value. For example,
```
@Test
	public void testHttpKeepAliveWithRequestClose() throws Exception {	
		_httpContext.setAttribute(HttpCoreContext.HTTP_REQUEST, httpRequest);

		_httpResponse.setHeaders(
			new Header[] {
				new BasicHeader(HttpHeaders.CONNECTION, HttpHeaders.KEEP_ALIVE),
				new BasicHeader(HttpHeaders.CONTENT_LENGTH, "10")
			});
	}

     @Test
	public void testHttpKeepAliveWithResponseClose() throws Exception {
		_httpContext.setAttribute(HttpCoreContext.HTTP_REQUEST, httpRequest);

		_httpResponse.setHeaders(
			new Header[] {
				new BasicHeader(
					HttpHeaders.CONNECTION, HttpHeaders.CONNECTION_CLOSE_VALUE),
				new BasicHeader(HttpHeaders.CONTENT_LENGTH, "10")
			});
	}
```
If it is clear to you, you may push force the change.

Thanks,
Hai

**Comment by ericyanLr** [comment]
Hi @yuhai,

Thank you for the guidance and explanation! I have updated the tests per your suggestions and have force pushed the changes. 

Please let me know if there's anything else I need to change.
Thanks!

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by yuhai** [comment]
@ericyanLr, I did three SF commits. Please see https://github.com/liferay-core-infra/liferay-portal/pull/6371

**Pull request closed without merging**
