### PR TITLE
LPS-166596 Fix service builder backward compatibility in older 7.4 portal version

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@julschong semver error:

```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/portal-workflow/portal-workflow-kaleo-definition-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.portal.workflow.kaleo.definition       MAJOR      2.1.0      2.1.0      3.0.0      VERSION INCREASE REQUIRED
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-25/test-portal-acceptance-pullrequest(master)/5165/modules-semantic-versioning-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

```
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-impl/portal-impl.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.impl/56.0.4/aeb1b30c9f620512ec476db17e672204b828036c/com.liferay.portal.impl-56.0.4.jar
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-25/test-portal-acceptance-pullrequest(master)/5165/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
@catarineaguiar 
rebased for semantic versioning on portal-impl.jar
not kaleo since it is unrelated

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine, 
is it possible to test this pull's service builder change with 7.3  and with older 7.4 before 5d852072563d7ae650440b468687e752c5ed7d1b?

**Comment by catarineaguiar** [comment]
modifying the 7.4.0 to 7.3.0 in `"<!DOCTYPE service-builder PUBLIC "-//Liferay//DTD Service Builder 7.4.0//EN" "http://www.liferay.com/dtd/liferay-service-builder_7_4_0.dtd">"` of all service.xml and running ant build-services on portal-impl, I found a regression:

```
build-common-java.compile:
    [javac] Compiling 5 source files to /home/me/dev/projects/liferay-portal/portal-kernel/classes
    [javac] /home/me/dev/projects/liferay-portal/portal-kernel/src/com/liferay/counter/kernel/model/CounterWrapper.java:32: error: CounterWrapper is not abstract and does not override abstract method cloneWithOriginalValues() in BaseModel
    [javac] public class CounterWrapper
    [javac]        ^
    [javac] 1 error
```

**Comment by catarineaguiar** [comment]
I tested without your changes and it shows the same failure.

**Comment by tinatian** [comment]
@julschong As we talked, please resend.

Thanks.
Tina

**Pull request closed without merging**
