### PR TITLE
[Spring Beans] LPS-200563 Merge UserGroupMembershipPolicyFactoryImpl into Util and move to portal-impl. 

### PR DESCRIPTION
**Pull request by JanisZhang**
Resolved conflicts. 

https://liferay.atlassian.net/browse/LPS-200563

### CODE REVIEW

**Comment by JanisZhang** [comment]
SF failure is not related.

**Comment by dantewang** [comment]
@JanisZhang Was imports.txt manually updated or regenerated by some command?

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
> imports.txt

I've checked the git history, it was manually updated by the author.

**Comment by Kvale1733** [comment]
ci:test:um

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
SF failure is not related.

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
