### PR TITLE
LPP-52401 -> LPD-15685 add commons-math3 to shared-dependencies-poi to avoid NoClassDefFoundError

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This is for https://liferay.atlassian.net/browse/LPP-52401.
Add use compileOnly commons-math3 in shared-dependenceis-poi, as we have exported it in shared-dependencies-apache-commons, so that we can avoid "NoClassDefFoundError" for customer
Thanks for checking

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:report:2531639191

**Comment by jeffwu0724** [comment]
no regression found

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/146740

**Pull request closed without merging**
