### PR TITLE
[Remove Stream usage: source-formatter]Lps 176218

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-176218

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@slnn A lot of sf issues. Doesn't look related but appeared on a second run. Can you rebase and rerun SF?

**Comment by dantewang** [comment]
@ling-alan-huang Do we scan third-party patch now?

**Comment by ling-alan-huang** [comment]
@dantewang  see https://github.com/brianchandotcom/liferay-portal/commit/ec439118cbdbaa7b65a263c08521c3510797e837

**Comment by ling-alan-huang** [comment]
That SF issue file was removed yesterday.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131206

@slnn I removed the SF commits since the actual outcome doesn't look very clean.

**Pull request closed without merging**
