### PR TITLE
[Unused Reference] LPD-8481 Remove unused reference from ModulePortalProfile

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:report:2563573134

**Comment by dantewang** [comment]
Closing this one based on the one of the reasons in https://github.com/liferay-core-infra/liferay-portal/pull/6920#pullrequestreview-2024193810

@MrJohn1911 @tinatian

**Pull request closed without merging**
