### PR TITLE
LPS-167880 Remove "immediate = true" from Echo components part 3

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
ci:test:echo

**Comment by zhangyan0701** [comment]
Possible regression:
1. Recycle Bin scheduler doesn't work.
Steps:
1). Add below two properties into portal-ext.properties file: trash.entry.check.interval=1, trash.entries.max.age=1
2). Add a Blog entry.
3). Move Blog entry to Recycle Bin.
4). Wait for 2 minutes.
5). Assert the Blog entry still displays in Recycle Bin.

Failed case: [LocalFile.RecycleBin#RecycleBinScheduledCleanup](https://testray.liferay.com/home/-/testray/case_results/2076430546)

2. Semantic versioning error:
```
     [exec] > Task :apps:application-list:application-list-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.application.list.adapter               CHANGED    3.0.0      3.0.0      3.0.1      VERSION INCREASE REQUIRED
     [exec] 	~   class      com.liferay.application.list.adapter.PortletPanelAppAdapterRegistry
     [exec] 		~   annotated  org.osgi.service.component.annotations.Component
     [exec] 			-   property   immediate=true
     [exec] * com.liferay.application.list.deploy.hot            CHANGED    1.0.0      1.0.0      1.0.1      VERSION INCREASE REQUIRED
     [exec] 	~   class      com.liferay.application.list.deploy.hot.LegacyPortletPanelAppHotDeployListener
     [exec] 		~   annotated  org.osgi.service.component.annotations.Component
     [exec] 			-   property   immediate=true
```
Full console log:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-32/test-portal-acceptance-pullrequest(master)/7093/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by RenanUmV** [comment]
ci:test:echo

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Semantic versioning error:
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/application-list/application-list-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.application.list                       CHANGED    5.1.0      5.1.0      5.1.1      VERSION INCREASE REQUIRED
     [exec]     	~   class      com.liferay.application.list.PanelAppRegistry
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   immediate=true
     [exec]     	~   class      com.liferay.application.list.PanelCategoryRegistry
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   immediate=true
     [exec]     * com.liferay.application.list.adapter               CHANGED    3.0.0      3.0.0      3.0.1      VERSION INCREASE REQUIRED
     [exec]     	~   class      com.liferay.application.list.adapter.PortletPanelAppAdapterRegistry
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   immediate=true
     [exec]     * com.liferay.application.list.deploy.hot            CHANGED    1.0.0      1.0.0      1.0.1      VERSION INCREASE REQUIRED
     [exec]     	~   class      com.liferay.application.list.deploy.hot.LegacyPortletPanelAppHotDeployListener
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   immediate=true
```
Full console log:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-32/test-portal-acceptance-pullrequest(master)/7111/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

Other failures are unrelated.

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
Hey @shuyangzhou , this one is good to go!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127070

**Pull request closed without merging**
