### PR TITLE
[Method References 2] LPS-169777 Remove class ScriptingExecutorExtender

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4682

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:help

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@W2jx No regressions found. The SF issue is unrelated.

**Comment by W2jx** [comment]
no conflicts(6/14 8:28)

**Comment by W2jx** [comment]
no conflicts(6/16 9:49)

**Comment by W2jx** [comment]
Forced push to resolve the conflict about BREAKING_CHANGES.markdown file, no logic changes.

**Comment by W2jx** [comment]
no conflicts(6/20 8:56)

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136660

**Pull request closed without merging**
