### PR TITLE
LPS-159737 Do no need to include these filters, these were needed whe…

### PR DESCRIPTION
**Pull request by tinatian**
…n plugins were deployed as a separate web application for 6.2 and earlier, while now every plugin is going to be deployed as a osgi bundle and shares the same filter setting as portal.

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@tinatian no regressions found.

**Comment by tinatian** [comment]
@vicnate5 This pull may affect the deployment of old jar, I am wondering if those tests are already included in the ci:test:relevant?

Tina

**Comment by vicnate5** [comment]
ci:test:jsf

**Comment by vicnate5** [comment]
ci:test:blade

**Comment by vicnate5** [comment]
Additional tests at https://github.com/vicnate5/liferay-portal/pull/2123
@zhangyan0701 Can you check the results when they come in?

**Comment by vicnate5** [comment]
ci:test:project-templates

**Comment by zhangyan0701** [comment]
@vicnate5 All tests passed in https://github.com/vicnate5/liferay-portal/pull/2123.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122245

**Pull request closed without merging**
