### PR TITLE
[TS] LPS-160793

### PR DESCRIPTION
**Pull request by crodriguezy**
As requested in https://github.com/liferay-core-infra/liferay-portal/pull/1539

LPS-142380 has already been merged

cc/ @jgarcialr

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@crodriguezy no regressions found.

**Comment by tinatian** [comment]
@crodriguezy Code looks good to me, please rebase.

Thanks.
Tina.

**Comment by crodriguezy** [comment]
@tinatian done, thank you.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125104

**Pull request closed without merging**
