### PR TITLE
LPS-150781 Remove streambuffer.jar, mimepull.jar, saaj-api.jar and saaj-impl.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:jdk11

**Comment by vicnate5** [comment]
Killed the acceptance run here. Was tested at https://github.com/liferay-core-infra/liferay-portal/pull/541

**Comment by rafaprax** [comment]
Hi all. I just removed the stax.jar from this pr as @shuyang suggested in the previous one. Thx

**Comment by vicnate5** [comment]
ci:test:jdk11

**Comment by vicnate5** [comment]
@koor4356 can you prioritize checking this? The JDK11 results.
Triggered analysis run https://test-1-1.liferay.com/job/generate-testray-csv/93/

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
@rafaprax 
I have downloaded the bundle from this PR and tested this test locally. It seems the test fails because of your PR. When I started the same on JDK8, the expected result was displayed as intended. Can you take a look, please?

**Steps to reproduce:**
- Start portal on JDK11
- Go to Control Panel > Instance Settings > Localization
- Check Czech under the available column
**Expected result:**
- Czech (Czech Republic)
**Actual result:**
- Czech (Czechia)

https://testray.liferay.com/home/-/testray/case_results/1657320346

- Also, there is an error with JDK11 on PostgreSQL 134. It is causing some tests to fail before the run.

`ERROR [Start Level: Equinox Container: 94637c46-d75c-46eb-99a5-356aec225505][DataGuardConnector:93] Encountered a problem while using 127.0.0.1:42763. Shutting down now. 
 [parallel] java.net.BindException: Address already in use (Bind failed)
 [parallel] 	at java.net.PlainSocketImpl.socketBind(Native Method) ~[?:?]
 [parallel] 	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436) ~[?:?]
 [parallel] 	at java.net.ServerSocket.bind(ServerSocket.java:381) ~[?:?]
 [parallel] 	at java.net.ServerSocket.<init>(ServerSocket.java:243) ~[?:?]
 [parallel] 	at com.liferay.data.guard.connector.DataGuardConnectorThread.<init>(DataGuardConnectorThread.java:54) ~[bundleFile:?]
 [parallel] 	at com.liferay.data.guard.connector.DataGuardConnector.activate(DataGuardConnector.java:58) [bundleFile:?]
 [parallel] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
 [parallel] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
 [parallel] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
 [parallel] 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
 [parallel] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228) [bundleFile:?]
 [parallel] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) [bundleFile:?]
 [parallel] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664) [bundleFile:?]
 [parallel] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510) [bundleFile:?]
 [parallel] 	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:310) [bundleFile:?]
 [parallel] 	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:300) [bundleFile:?]
 [parallel] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:341) [bundleFile:?]
 [parallel] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114) [bundleFile:?]
 [parallel] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:983) [bundleFile:?]
 [parallel] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:956) [bundleFile:?]
 [parallel] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:765) [bundleFile:?]
 [parallel] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:666) [bundleFile:?]
 [parallel] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:432) [bundleFile:?]
 [parallel] 	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:665) [bundleFile:?]
 [parallel] 	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:339) [bundleFile:?]
 [parallel] 	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:381) [bundleFile:?]
 [parallel] 	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:49) [bundleFile:?]
 [parallel] 	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:263) [bundleFile:?]
 [parallel] 	at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196) [bundleFile:?]
 [parallel] 	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169) [bundleFile:?]
 [parallel] 	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49) [bundleFile:?]
 [parallel] 	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:1) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:230) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:137) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:129) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:191) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.Module.publishEvent(Module.java:476) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.Module.start(Module.java:467) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi.jar:?]
 [parallel] 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi.jar:?]`

- https://testray.liferay.com/reports/production/logs/2022-04/test-1-27/test-portal-acceptance-pullrequest(master)/2699/modules-integration-postgresql134-jdk11_open/2/4/jenkins-console.txt.gz?authuser=0

- https://testray.liferay.com/home/-/testray/case_results/1657336851

**Comment by vicnate5** [comment]
@koor4356 @rafaprax  https://issues.liferay.com/browse/LPS-90004 Is the Czech Republic issue

**Comment by rafaprax** [comment]
Hey @koor4356.
The postgres error seems not related to the changes here. But I'll try to reproduce it locally just to make sure. Thx

**Comment by rafaprax** [comment]
Hey @koor4356. I have downloaded the bundle and I was able to run Liferay with postgres 13.4 in a jdk11 environment. I play around with the portal and everything worked normally. See [startup log](https://gist.github.com/rafaprax/99ee6294653206581e639679e0c86d13).

Are we ok to forward this pr or do you guys need to run some more tests? @koor4356 @vicnate5

**Comment by koor4356** [comment]
@rafaprax @vicnate5 
I believe JDK11 results look good if the above error is not related. But the other results are not checked. Also, I am leaving early today, therefore I may not check them today.

**Comment by vicnate5** [comment]
@rafaprax This looks good to go. Sorry for the delay.

**Comment by rafaprax** [comment]
Hey @shuyangzhou It's ready for your review.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115925

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
