### PR TITLE
[TS] LPS-148721

### PR DESCRIPTION
**Pull request by jcampoy**
https://issues.liferay.com/browse/LPS-148721

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test

**Comment by vicnate5** [comment]
@bronsonsoda can you check this one? Please also check all "Failed prior to running test" results as well.

**Comment by bronsonsoda** [comment]
@jcampoy no regressions 

@vicnate5

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114615

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
