### PR TITLE
LPS-195588 Merge CommonPermission interface and impl into Util and move to portal-impl

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found. SF issue is not related

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141593

**Pull request closed without merging**
