### PR TITLE
[Company Log Servlet] LPS-154230

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, @tinatian

[LPS-162747](https://issues.liferay.com/browse/LPS-162747) was merged to master.  I just rebased it.

I merged the almost all CompanyLogServlet changes from https://github.com/brianchandotcom/liferay-portal/pull/122664 as the first commit. Because it will exist the conflicts if rebased on LPS-162747 and used the previous commits.

The pr mainly changed about returning json when list CompanyLogFiles info. In the test class, I mainly did the changes in testListCompaniesLogFilesWithCompanyAdminUser() and testListCompaniesLogFilesWithOmniAdminUser().

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by yuhai** [comment]
@zhangyan0701, could you please check the test result? Thanks.

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@yuhai Please squash the commits, I do not want to see you add a class, and later modified it in the pull.

Thanks.
Tina.

**Comment by yuhai** [comment]
@tinatian, I just squash the commits and rebase it based on the latest master. No logic changes.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125109

**Pull request closed without merging**
