### PR TITLE
[Component with its own class name as service type] LPS-193631 Refactor ModelResourcePermission components

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-193631

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:stable

**Review by rafaprax — APPROVED** [review]

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141592

**Pull request closed without merging**
