### PR TITLE
[Optional Reference]LPS-185417 Convert the Optional Dynamic Greedy references to static r…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-185417

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
ci:test:stable

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:stable

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
