### PR TITLE
Lps 135298 v2

### PR DESCRIPTION
**Pull request by slnn**
Benchmark side changes please see https://github.com/dantewang/liferay-benchmark-ee/pull/540

/cc @dantewang @tiantian

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@slnn Does this pull include changes to generate multi-company data by SampleSQLBuilder itself, or together with the integration test?

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/185

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
