### PR TITLE
[Component with its own class name as service type] LPS-199140 Refactor Helper and ContextFactory classes from sharing module

### PR DESCRIPTION
**Pull request by rafaprax**
**Author:** @Valmir-unicap
**Issue:** https://liferay.atlassian.net/browse/LPS-199140
**Forwarded from:** https://github.com/rafaprax/liferay-portal/pull/1376
**Original comment:**
- Ticket: https://liferay.atlassian.net/browse/LPS-199140

- Correction sugested in PR: https://github.com/rafaprax/liferay-portal/pull/1371

- Correction of PR from @regiCesar21: https://github.com/liferay-core-infra/liferay-portal/pull/6031

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:sharing

**Comment by zhangyan0701** [comment]
Issue found.

**The Share modal is unavailable.**

https://github.com/liferay-core-infra/liferay-portal/assets/25576873/1856f3c2-86ce-4934-800a-4b18a262757b

Below error in console:
```
2023-12-15 07:45:58.055 ERROR [http-nio-8080-exec-1][render_portlet_jsp:122] null
java.lang.NullPointerException: null
	at com.liferay.sharing.web.internal.util.SharingHelperUtil.getSharingEntryPermissionDisplays(SharingHelperUtil.java:62) ~[?:?]
	at com.liferay.sharing.web.internal.portlet.action.ViewMVCRenderCommand.render(ViewMVCRenderCommand.java:65) ~[?:?]
```

**Comment by Valmir-unicap** [comment]
I can't send a push here. I'll close this PR and open a new one.

**Pull request closed without merging**
