### PR TITLE
[Remove Stream/Optional usage] LPS-178434  journal-test

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-178434

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:acho

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by JanisZhang** [comment]
forwarding this one as it's approved and passed QA reviewed. cc @dantewang @tinatian @shuyangzhou

**Comment by JanisZhang** [comment]
ci:forward:force

**Pull request closed without merging**
