### PR TITLE
[bug fix] LPS-142277 properly handle web dir

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-142277 Add integration test to expose the issue
- LPS-142277 Move portal lib path logic to JSPEngineShieldedContainerInitializer to put it together with shielded container lib path logic; this fixes LIFERAY_LIB_PORTAL_DIR and LIFERAY_WEB_PORTAL_DIR, and also LPS-134778
- LPS-142277 Merge logic of PropsUtil#_getLibDir and WebDirDetector#getLibDir to make new methods, and deprecate unused methods
- LPS-142277 In PropsUtil, use same logic with portal lib dir to determine path of shielded container lib dir
- LPS-142277 In PropsUtil, use correct class name to detect portal lib dir; although in runtime it's set by JSPEngineShieldedContainerInitializer, there are chances that the property is not set in advance based on ServletContext, e.g. starting using InitUtil
- LPS-142277 Add null protection to return null if the class used to determine the dir is not found, prepare for next
- LPS-142277 In PropsUtil, fallback portal lib dir to shielded container lib dir if shielded container bootstrap class is not found by the class loader; this is required to run tools like DBBuilder from Ant which does not have shielded container api in its class path. The only other way to fix tools like DBBuilder is to make shielded container api .lfrbuild-portal-pre, but it's not a proper way because there is a requirement that the "portal-pre" modules must have dependency entries in IDE files of portal-kernel, portal-impl, etc. (see LibraryReferenceTest)
- LPS-142277 SemVer

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:environments

**Comment by dantewang** [comment]
@tinatian Do you have any suggestion for a better fix with https://github.com/liferay-core-infra/liferay-portal/pull/21/commits/ca9d340067da6188305fa94bd46a08c89ff024f1? I have to do this or tools like DBBuilder will fail with https://gist.github.com/kenjiheigel/f44ac463473002e7981894c2f8e8ad7e

**Comment by tinatian** [comment]
@dantewang I do not think we need "LIFERAY_LIB_PORTAL_DIR" any more, as what's inside in that folder should only be known by application server, our own logic should not touch or use it at all. Please remove/deprecate that property first, then we fix other path issues.

Close, please resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by dantewang** [comment]
@tinatian There's one thing to confirm. The portal lib dir is still used in
BaseDeployer. Do we still support deploy anything that needs to put jars
into that dir?

**Comment by tinatian** [comment]
@dantewang I do not think so. The goal of shielded container is to acting as a bridge from app to Liferay, we should not deploy anything related to liferay's code to that folder.

Tina

**Comment by dantewang** [comment]
@tinatian OK I'll deprecate LIFERAY_LIB_PORTAL_DIR first.

**Pull request closed without merging**
