### PR TITLE
LPS-153387 Move jaxrpc.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @catarineaguiar, can you please help me scan these test results?

Thx

**Comment by catarineaguiar** [comment]
@rafaprax no regressions found.

**Comment by rafaprax** [comment]
Hey @shuyangzhou, this pr is ready for your review. Thx

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
