### PR TITLE
[Method References] LPS-162571 Convert method references to field references in modules nested-portlets-web、notifications-web、my-subscriptions-web

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I convert method references to field references in modules nested-portlets-web、notifications-web、my-subscriptions-web.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results when they finish ? Thanks!

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@Kvale1733 Could you review the test results? Thanks!

**Comment by dantewang** [comment]
ci:test:notifications

**Comment by Kvale1733** [comment]
@W2jx No regressions

**Review by dantewang — APPROVED** [review]
@shuyangzhou @tinatian Forwarding this one as all tests passed and changes are direct replacements.

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
