### PR TITLE
[TS] LPS-181479 generate cookies with secure flag if portal is considered secure

### PR DESCRIPTION
**Pull request by jvelalr**

### CODE REVIEW

**Comment by jvelalr** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:cookies

**Comment by Kvale1733** [comment]
ci:test:cookies

**Comment by Kvale1733** [comment]
@jvelalr No regressions found.

**Comment by tinatian** [comment]
@jvelalr This is in security team scope, please send it to security team for review. I am going to close this pull.

Thanks.
Tina.

**Pull request closed without merging**
