### PR TITLE
[Login-performance-tuning] LPS-148976

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, @tinatian, please check the performance test result from https://github.com/GinsonRen/liferay-portal/pull/582#issuecomment-1063596106

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
@dantewang, @tinatian, the test error **LayoutCrawlerTest.testSearchLayoutContentByWidgetContent** isn't related with the fix. I can reproduce the issue without the fix.

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@yuhai As we talked, I am going to close this pull, please resend.

Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
