### PR TITLE
[commons-lang] LPD-19939 Remove org.apache.commons.lang.time.DateUtils usages

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:2548311112

**Comment by julschong** [comment]
@tinatian unique failure seems unrelated

```
PortalLogAssertorTest-modules-integration-mysql57-jdk8/1/5	https://testray.liferay.com/home/-/testray/case_results/2548315595/history	Unique


[beanshell] Caused by: java.lang.NullPointerException
[beanshell] 	at com.liferay.portal.service.impl.RoleLocalServiceImpl.getDefaultGroupRole(RoleLocalServiceImpl.java:718) ~[portal-impl.jar:?]
[beanshell] 	at sun.reflect.GeneratedMethodAccessor665.invoke(Unknown Source) ~[?:?]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_381]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_381]
```

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6759

**Pull request closed without merging**
