### PR TITLE
[Remove Stream/Optional usages on methods return value for module: adaptive-media/adaptive-media-api]Lps 172854

### PR DESCRIPTION
**Pull request by dantewang**
https://github.com/liferay-core-infra/liferay-portal/pull/3132 Resend to rerun relevant

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
@dantewang 
No regressions found. Only a semver issue.
```
 [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/adaptive-media/adaptive-media-image-api] FAILED
     [exec]     java.lang.AssertionError: [Baseline Warning] Bundle Version Change Recommended: 10.0.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertFalse(Assert.java:64)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-26/test-portal-acceptance-pullrequest(master)/7327/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
Just noticed that the sem ver error is from adaptive-media-image-api...

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/129512

**Pull request closed without merging**
