### PR TITLE
[Upgrade Mockito framework] LPS 153088 pr2

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

See https://github.com/liferay-core-infra/liferay-portal/pull/837
As we discussed, I add portal version check in  `LiferayOSGiDefaultsPlugin.java`  to try to keep mockito version change only for master and avoid using `ArgumentMatchers`. thx

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @catarineaguiar,
Could you please help me scan test results. Thx!

Regards.
Janis.

**Comment by catarineaguiar** [comment]
@vicnate5 will not have time to review this one today

**Comment by kyle-miho** [comment]
Unit Test compile error found:
 [exec] com.liferay.petra.function.UnsafeConsumerTest STANDARD_OUT
     [exec]     [Whip] com.liferay.petra.function.UnsafeConsumer is fully covered.
     [exec]     [Whip] com.liferay.petra.function.UnsafeFunction is fully covered.
     [exec]     [Whip] com.liferay.petra.function.UnsafeRunnable is fully covered.
     [exec]     [Whip] com.liferay.petra.function.UnsafeSupplier is fully covered.
     [exec] /opt/dev/projects/github/liferay-portal/modules/core/petra/petra-io/src/test/java/com/liferay/petra/io/unsync/UnsyncByteArrayOutputStreamTest.java:34: error: package javassist does not exist
     [exec] import javassist.Modifier;
     [exec]                 ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/core/petra/petra-io/src/test/java/com/liferay/petra/io/unsync/UnsyncByteArrayOutputStreamTest.java:77: error: cannot find symbol
     [exec] 			Modifier.isPackage(BoundaryCheckerUtil.class.getModifiers()));
     [exec] 			^
     [exec]   symbol:   variable Modifier
     [exec]   location: class UnsyncByteArrayOutputStreamTest
     [exec] 2 errors
     [exec] 
     [exec] > Task :core:petra:petra-io:compileTestJava FAILED

**Comment by kyle-miho** [comment]
Second Unit Test compile error found:
[exec] > Task :apps:portal-url-builder:portal-url-builder-impl:compileJava
     [exec] 
     [exec] > Task :apps:portal-url-builder:portal-url-builder-impl:copyLibs SKIPPED
     [exec] > Task :apps:portal-url-builder:portal-url-builder-impl:copyCSS NO-SOURCE
     [exec] > Task :apps:portal-url-builder:portal-url-builder-impl:buildCSS NO-SOURCE
     [exec] > Task :apps:portal-url-builder:portal-url-builder-impl:processResources
     [exec] > Task :apps:portal-url-builder:portal-url-builder-impl:classes
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-url-builder/portal-url-builder-impl/src/test/java/com/liferay/portal/url/builder/internal/BaseAbsolutePortalURLBuilderTestCase.java:64: error: cannot find symbol
     [exec] 				StringBundler sb = invocationOnMock.getArgumentAt(
     [exec] 				                                   ^
     [exec]   symbol:   method getArgumentAt(int,Class<StringBundler>)
     [exec]   location: variable invocationOnMock of type InvocationOnMock
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-url-builder/portal-url-builder-impl/src/test/java/com/liferay/portal/url/builder/internal/BaseAbsolutePortalURLBuilderTestCase.java:150: error: cannot find symbol
     [exec] 				String uri = invocationOnMock.getArgumentAt(1, String.class);
     [exec] 				                             ^
     [exec]   symbol:   method getArgumentAt(int,Class<String>)
     [exec]   location: variable invocationOnMock of type InvocationOnMock
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-url-builder/portal-url-builder-impl/src/test/java/com/liferay/portal/url/builder/internal/BaseAbsolutePortalURLBuilderTestCase.java:151: error: cannot find symbol
     [exec] 				String queryString = invocationOnMock.getArgumentAt(
     [exec] 				                                     ^
     [exec]   symbol:   method getArgumentAt(int,Class<String>)
     [exec]   location: variable invocationOnMock of type InvocationOnMock
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-url-builder/portal-url-builder-impl/src/test/java/com/liferay/portal/url/builder/internal/BaseAbsolutePortalURLBuilderTestCase.java:153: error: cannot find symbol
     [exec] 				Long timestamp = invocationOnMock.getArgumentAt(3, Long.class);
     [exec] 				                                 ^
     [exec]   symbol:   method getArgumentAt(int,Class<Long>)
     [exec]   location: variable invocationOnMock of type InvocationOnMock
     [exec] 4 errors
     [exec] 
     [exec] > Task :apps:portal-url-builder:portal-url-builder-impl:compileTestJava FAILED
     [exec] 
     [exec] > Task :apps:portal-url-builder:portal-url-builder-impl:processTestResources NO-SOURCE
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/portal-vulcan/portal-vulcan-api/src/test/java/com/liferay/portal/vulcan/util/EntityExtensionUtilTest.java uses or overrides a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] 
     [exec] > Task :apps:portal-vulcan:portal-vulcan-api:compileTestJava
     [exec] 
     [exec] > Task :apps:portal-vulcan:portal-vulcan-api:processTestResources NO-SOURCE
     [exec] > Task :apps:portal-vulcan:portal-vulcan-api:testClasses
     [exec] 
     [exec] > Task :apps:portal-vulcan:portal-vulcan-api:test

**Comment by kyle-miho** [comment]
Nothing else seems to be related to this PR

**Comment by dantewang** [comment]
@JanisZhang I'm going to close this one as we discussed. Please resend, thanks!

**Comment by dantewang** [comment]
ci:close

**Pull request closed without merging**
