### PR TITLE
[Method References 2] LPS-164891 Remove unused reference variable in module portal-search-tuning-synonyms-web(dxp) | part 1

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have removed unused reference variable in module portal-search-tuning-synonyms-web(dxp).

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
