### PR TITLE
[Remove Spring extender usages] LPS-159586 commerce-price-list-service

### PR DESCRIPTION
**Pull request by dantewang**
https://issues.liferay.com/browse/LPS-159586

### CODE REVIEW

**Comment by dantewang** [comment]
@zhangyan0701 Could you please review the test results when they finish? Thanks!

**Comment by zhangyan0701** [comment]
Hi @catarineaguiar  Could you check the test results when the ci acceptance tests finish? Thanks!

**Comment by catarineaguiar** [comment]
@dantewang regressions found:

`CommerceShipmentItemTest`
```
 [exec] com.liferay.commerce.shipment.test.CommerceShipmentItemTest > testAddCommerceShipmentItem FAILED
     [exec]     java.lang.NullPointerException
     [exec]     	at com.liferay.commerce.price.list.service.impl.CommercePriceEntryLocalServiceImpl.fetchCommercePriceEntry(CommercePriceEntryLocalServiceImpl.java:720)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-26/test-portal-acceptance-pullrequest(master)/4283/modules-integration-mysql57-jdk8/1/0/jenkins-console.txt.gz?authuser=0)

`CommercePriceEntryLocalServiceTest`
```
[exec] com.liferay.commerce.price.list.service.test.CommercePriceEntryLocalServiceTest > testFetchCommercePriceEntry3 FAILED
     [exec]     java.lang.NullPointerException: 
     [exec]     [
     [exec]     SCENARIO Fetching a Price Entry
     [exec]     GIVEN A parent Price List
     [exec]      AND A child Price List
     [exec]      AND A Price Entry on the parent Price List
     [exec]     WHEN The SKU (cpInstance) of the Price Entry
     [exec]      AND The ID of the child Price List
     [exec]      AND A true useAncestors value are used to fetch a Price Entry
     [exec]     THEN The result should be the given Price Entry]
     [exec] 
     [exec]     	at com.liferay.commerce.price.list.service.impl.CommercePriceEntryLocalServiceImpl.fetchCommercePriceEntry(CommercePriceEntryLocalServiceImpl.java:720)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-26/test-portal-acceptance-pullrequest(master)/4283/modules-integration-mysql57-jdk8/0/19/jenkins-console.txt.gz?authuser=0)

`CommerceOrderImporterTypeTest`
```
[exec] com.liferay.commerce.order.importer.type.test.CommerceOrderImporterTypeTest > testSuccessfulCSVImport FAILED
     [exec]     java.lang.AssertionError: expected null, but was:<[Ljava.lang.String;@3c84b81a>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotNull(Assert.java:756)
     [exec]     	at org.junit.Assert.assertNull(Assert.java:738)
     [exec]     	at org.junit.Assert.assertNull(Assert.java:748)
     [exec]     	at com.liferay.commerce.order.importer.type.test.CommerceOrderImporterTypeTest.testSuccessfulCSVImport(CommerceOrderImporterTypeTest.java:257)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by tinatian** [comment]
@dantewang Regression found, close, please resend.

Thanks.
Tina

**Pull request closed without merging**
