### PR TITLE
[PowerMock] LPS 151823 

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove powermock usages related to `BaseDDMFormFieldTypeSettingsTestCase` present in `dynamic-data-mapping-form-field-type`.

https://issues.liferay.com/browse/LPS-151823

Thanks
Janis.

### CODE REVIEW

**Comment by JanisZhang** [comment]
@catarineaguiar Could you please help me scan test results. Thx!

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found

**Comment by JanisZhang** [comment]
@catarineaguiar Thx!

**Comment by dantewang** [comment]
ci:close

**Pull request closed without merging**
