### PR TITLE
LPS-145991 Remove wsdl4j.jar

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@guilhermedcamacho Real failure here:
[com.liferay.sharepoint.soap.repository.connector.SharepointConnectionTest](https://testray.liferay.com/home/-/testray/case_results/1604242405)

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
Hey @vicnate5 , I fixed test appending a new [commit](https://github.com/liferay-core-infra/liferay-portal/pull/259/commits/8dfe49cb1ec78e2df77453b4e4fd3a21d4d8e321).
I ran [ci:test:sharepoint](https://github.com/guilhermedcamacho/liferay-portal/pull/40#issuecomment-1022725738) on my repo and now it's passing. Thank you for pointing that out.

**Comment by vicnate5** [comment]
@guilhermedcamacho Looks good, no additional testing needed.

**Comment by guilhermedcamacho** [comment]
@tinatian , this PR is ready for your review. Thanks!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

@guilhermedcamacho There are two bundles have the line below, please put this into the list for compileInclude so that we can visit it later.
`compileInclude group: "wsdl4j", name: "wsdl4j", version: "1.6.3"`

Thanks.
Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/112849

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
