### PR TITLE
[Method References 2] LPS-176946 Convert method reference to ServiceTrackerList in class OAuth2JSONWSAuthVerifier and SAPEntryScopeDescriptorFinderRegistrator

### PR DESCRIPTION
**Pull request by W2jx**
resend, Merge the service tracker into class SAPEntryScopeDescriptorFinderRegistrator.

Previous：https://github.com/liferay-core-infra/liferay-portal/pull/4717

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:oauth2

**Comment by W2jx** [comment]
no conflicts(6/14 8:28)

**Comment by W2jx** [comment]
no conflicts(6/16 9:49)

**Comment by W2jx** [comment]
no conflicts(6/19 13:39)

**Comment by W2jx** [comment]
no conflicts(6/20 8:56)

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136788

**Pull request closed without merging**
