### PR TITLE
LPS-172315 Remove Stream usage for module: journal-service

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/128573

**Pull request closed without merging**
