### PR TITLE
LPS-170848 Move Dom4jUtil to portal-impl

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:help

**Comment by jaydawu** [comment]
A regression was found on [service-builder-jdk8/0/0](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/347830//consoleText). @julschong could you please take a look? Thanks.

```
build-service:
     [java] Java Result: 1
     [echo] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
     [echo] Exception in thread "main" java.lang.NoClassDefFoundError: com/liferay/petra/xml/XMLUtil
     [echo]   at com.liferay.util.xml.XMLSafeReader.<init>(XMLSafeReader.java:26)
     [echo]   at com.liferay.portal.tools.service.builder.ServiceBuilder.<init>(ServiceBuilder.java:613)
     [echo]   at com.liferay.portal.tools.service.builder.ServiceBuilder.main(ServiceBuilder.java:237)
     [echo] Caused by: java.lang.ClassNotFoundException: com.liferay.petra.xml.XMLUtil
     [echo]   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
     [echo]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [echo]   at sun.misc.Launcher\$AppClassLoader.loadClass(Launcher.java:331)
     [echo]   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [echo]   ... 3 more
[stopwatch] [run.batch.test.action: 1:27.219 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:316: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:251: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:243: Service Builder generated exceptions.
      [get] Getting: \$\{dependencies.url\}/archive/test-1-27/test-portal-acceptance-pullrequest-downstream(master)/347830consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20221221181755424.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20221221181755424.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1874621582.properties
```

cc/ @dantewang

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
Added commited for:
- Additional plugin cache for SF and SB
- Removing apps/petra entirely

**Comment by catarineaguiar** [comment]
@julschong regressions found:

```
   [exec] com.liferay.portal.tools.sample.sql.builder.io.CharPipeTest > testSlowReaderOnCloseForce FAILED
     [exec]     java.lang.AssertionError
     [exec]         at org.junit.Assert.fail(Assert.java:86)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:52)
     [exec]         at com.liferay.portal.tools.sample.sql.builder.io.CharPipeTest.testSlowReaderOnCloseForce(CharPipeTest.java:668)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-31/test-portal-acceptance-pullrequest(master)/6503/modules-unit-jdk8/0/4/jenkins-console.txt.gz?authuser=0)

```
build-service:
     [java] Java Result: 1
     [echo] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
     [echo] Exception in thread "main" java.lang.NoClassDefFoundError: com/liferay/petra/xml/XMLUtil
     [echo] 	at com.liferay.util.xml.XMLSafeReader.<init>(XMLSafeReader.java:26)
     [echo] 	at com.liferay.portal.tools.service.builder.ServiceBuilder.<init>(ServiceBuilder.java:613)
     [echo] 	at com.liferay.portal.tools.service.builder.ServiceBuilder.main(ServiceBuilder.java:237)
     [echo] Caused by: java.lang.ClassNotFoundException: com.liferay.petra.xml.XMLUtil
     [echo] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
     [echo] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [echo] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
     [echo] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [echo] 	... 3 more
[stopwatch] [run.batch.test.action: 1:26.670 sec]
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-31/test-portal-acceptance-pullrequest(master)/6503/service-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
will resend to keep the thread shorter

**Pull request closed without merging**
