### PR TITLE
[Tuning]LPS-152440

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
CI test failed due to compile error for module configuration-admin-web:
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/configuration-admin/configuration-admin-web/src/main/java/com/liferay/configuration/admin/web/internal/util/DDMFormValuesToPropertiesConverter.java:209: error: cannot find symbol
     [exec] 			JSONUtil.isValid(stringValue)) {
     [exec] 			        ^
     [exec]   symbol:   method isValid(String)
     [exec]   location: class JSONUtil
```

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@tinatian some tests failed:

`MBMessageServiceTest`, `TalendDispatchTaskExecutorTest`, 
```
[exec] com.liferay.message.boards.service.test.MBMessageLocalServiceTest > testAddBBCodeSubjectWithEmptyBodyMessageInBBCode STARTED
     [exec] 2022-05-18 17:52:16.813 ERROR [com.liferay.message.boards.test-executor-thread][TypedSettings:89] null
     [exec] com.liferay.portal.kernel.json.JSONException: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
     [exec] 	at com.liferay.portal.json.JSONObjectImpl.<init>(JSONObjectImpl.java:84) ~[portal-impl.jar:?]
     [exec] 	at com.liferay.portal.json.JSONFactoryImpl.createJSONObject(JSONFactoryImpl.java:179) ~[portal-impl.jar:?]
     [exec] 	at com.liferay.portal.kernel.json.JSONFactoryUtil.createJSONObject(JSONFactoryUtil.java:80) ~[portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.settings.TypedSettings.getLocalizedValuesMap(TypedSettings.java:86) [portal-kernel.jar:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-32/test-portal-acceptance-pullrequest(master)/3961/modules-integration-mysql57-jdk8/2/11/jenkins-console.txt.gz?authuser=0)

`ObjectLayoutLocalServiceTest`, `MessageBoardThreadResourceTest`, `CommentResourceTest`, `BlogPostingResourceTest`
```
> Task :apps:headless:headless-delivery:headless-delivery-api:compileJava FAILED
/home/me/dev/projects/liferay-portal/modules/apps/headless/headless-delivery/headless-delivery-api/src/main/java/com/liferay/headless/delivery/dto/v1_0/util/ContentFieldUtil.java:252: error: cannot find symbol
								JSONUtil.createJSONObject(alt);
								        ^
  symbol:   method createJSONObject(String)
  location: class JSONUtil
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-32/test-portal-acceptance-pullrequest(master)/3961/modules-integration-mysql57-jdk8/2/16/jenkins-console.txt.gz?authuser=0)

`CompanySampleDataGenerationTest`
```
com.liferay.company.sample.data.generation.test.CompanySampleDataGenerationTest > testGenerateSampleData FAILED
    java.lang.AssertionError: Thread Thread[pool-17-thread-2,5,] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.fragment.entry.processor.editable.internal.parser.ImageEditableElementParser, message=Unable to parse JSON value data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAABECAYAAABK3PEEAAAACXBIWXMAAC4jAAAuIwF4pT92AAABBUlEQVR4Xu3VAQkAIBDFUO0fRLCD2RSM8dg12Mbn5trnjo41MAvMtv1gBbb7FhjvW+AC6wZwvn5wgXEDOF4LLjBuAMdrwQXGDeB4LbjAuAEcrwUXGDeA47XgAuMGcLwWXGDcAI7XgguMG8DxWnCBcQM4XgsuMG4Ax2vBBcYN4HgtuMC4ARyvBRcYN4DjteAC4wZwvBZcYNwAjteCC4wbwPFacIFxAzheCy4wbgDHa8EFxg3geC24wLgBHK8FFxg3gOO14ALjBnC8Flxg3ACO14ILjBvA8VpwgXEDOF4LLjBuAMdrwQXGDeB4LbjAuAEcrwUXGDeA47XgAuMGcLwWXGDcAI73ADVez7kdh2y/AAAAAElFTkSuQmCC
    java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.fragment.entry.processor.editable.internal.parser.ImageEditableElementParser, message=Unable to parse JSON value data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAABECAYAAABK3PEEAAAACXBIWXMAAC4jAAAuIwF4pT92AAABBUlEQVR4Xu3VAQkAIBDFUO0fRLCD2RSM8dg12Mbn5trnjo41MAvMtv1gBbb7FhjvW+AC6wZwvn5wgXEDOF4LLjBuAMdrwQXGDeB4LbjAuAEcrwUXGDeA47XgAuMGcLwWXGDcAI7XgguMG8DxWnCBcQM4XgsuMG4Ax2vBBcYN4HgtuMC4ARyvBRcYN4DjteAC4wZwvBZcYNwAjteCC4wbwPFacIFxAzheCy4wbgDHa8EFxg3geC24wLgBHK8FFxg3gOO14ALjBnC8Flxg3ACO14ILjBvA8VpwgXEDOF4LLjBuAMdrwQXGDeB4LbjAuAEcrwUXGDeA47XgAuMGcLwWXGDcAI73ADVez7kdh2y/AAAAAElFTkSuQmCC
    	at com.liferay.portal.test.rule.LogAssertionTestRule$LogAppender.append(LogAssertionTestRule.java:330)
    	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
    	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-32/test-portal-acceptance-pullrequest(master)/3961/modules-integration-mysql57-jdk8/4/3/jenkins-console.txt.gz?authuser=0)

`FragmentEntryProcessorEditableTest`
```
[exec] com.liferay.fragment.entry.processor.editable.test.FragmentEntryProcessorEditableTest > testFragmentEntryProcessorEditable FAILED
     [exec]     org.junit.ComparisonFailure: expected:<...e="image"><img src="[sample.jp]g"></lfr-editable>
     [exec]     	...> but was:<...e="image"><img src="[https://www.cstatic-images.com/car-pictures/xl/usc40msc062a021001.pn]g"></lfr-editable>
     [exec]     	...>
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:117)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
     [exec]     	at com.liferay.fragment.entry.processor.editable.test.FragmentEntryProcessorEditableTest.testFragmentEntryProcessorEditable(FragmentEntryProcessorEditableTest.java:250)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-38/test-portal-acceptance-pullrequest(master)/527/modules-integration-mysql57-jdk8/0/10/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
@slnn https://github.com/shuyangzhou/liferay-portal/pull/10654
If this change is merged first, you need to take the logic Shuyang added into your new method.

**Comment by tinatian** [comment]
@slnn Please fix the issues and resend.

Thanks.
Tina.

**Pull request closed without merging**
