### PR TITLE
[TECHNICAL SUPPORT] LPS-152166 UserPortraitTag does not setAttributes for jsp override

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,
[LPS-152166](https://issues.liferay.com/browse/LPS-152166)

Previous PR with passed FEI review: https://github.com/liferay-frontend/liferay-portal/pull/2148
I sent this PR as the FEI team requested a backend review as well:
https://github.com/liferay-frontend/liferay-portal/pull/2148#issuecomment-1117453766

The customer wanted to use the old feature of displaying user initials in our userPortrait taglib. However they failed to create the customisation due to the missing attributes we removed in https://github.com/liferay/liferay-portal/commit/c8aa67e0f80bfe920a2e106d14c641911c9bc3ef#diff-2dea5f2dacc39552fed8fd8f87c40ed8bb7e961aac3debc76c6060c07cdf7337

I added the attributes and also recreated the userInitials feature and shared it as an attribute in the request.

Please review my changes

Thanks,

### CODE REVIEW

**Comment by tinatian** [comment]
@NemethNorbert The change you mentioned was made because of performance, basically it improves performance by avoiding dispatching to jsp. And what you did now is to go back to dispatch to jsp, which affects the performance for sure.

I am wondering what does the customer want to do? Is there other way to achieve their goal? 

Thanks.
Tina.

**Comment by NemethNorbert** [comment]
> @NemethNorbert The change you mentioned was made because of performance, basically it improves performance by avoiding dispatching to jsp. And what you did now is to go back to dispatch to jsp, which affects the performance for sure.
> 
> I am wondering what does the customer want to do? Is there other way to achieve their goal?
> 
> Thanks. Tina.

Hey, @tinatian ,

The customer wanted to use the old feature of displaying user initials in our userPortrait taglib. However they failed to create the customisation due to the missing attributes we removed in https://github.com/liferay/liferay-portal/commit/c8aa67e0f80bfe920a2e106d14c641911c9bc3ef#diff-2dea5f2dacc39552fed8fd8f87c40ed8bb7e961aac3debc76c6060c07cdf7337

I simply re-added the attributes in the request, I think the performance should be effected minimally. However I don't see how the jsp could be customised without these attributes.

Thank you

**Comment by tinatian** [comment]
Hi @NemethNorbert ,
This is a hot path for all of test cases we have, which means it is going to affect all the test cases shown on performance white paper that we are trying to improve now.

I really do not want to add this back just because one customer needs it, could you please check if you have another customize solution for this customer?

If you really want to see a diff on performance about this change, we can provide one, as we have limit bandwidth now, I would like to delay this when it is really necessary. 

Based on the change here, this is for sure going to affect performance, though I can not tell you how much. We are currently working on performance tuning as we have a big regression on all test cases, any small change means a lot to us.

Thanks.
Tina.

**Comment by tinatian** [comment]
Hi @NemethNorbert ,
Code conflicts, I am going to close this pull, please resend if needed.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by tinatian** [comment]
@GinsonRen Please run a diff on this pull.

Thanks.
Tina.

**Comment by tinatian** [comment]
@GinsonRen  @dantewang The login result seems weird, we did not expect it to be improved, could you please check?

Thanks.
Tina.

**Comment by GinsonRen** [comment]
@tinatian @dantewang I re-run this pr and baseline for lofin, here is the result:

Portal Version | Git Id | Session Count | Mean Time of Login | Session Count Change （%）
-- | -- | -- | -- | --
BaseLine | 3668282bb | 50386 | 308 | -
LPS-152166 | - | 51691 | 276 | 2.59%

**Comment by tinatian** [comment]
@GinsonRen Why the difference is so big? Is there anything wrong with the test env or test setting?

Tina

**Comment by GinsonRen** [comment]
@tinatian I re-run login test and got 52515 this time, I used the same benchmark branch and same test env(main2), for recently results of other cases, these seems be no issue on the test env, I have no idea why the difference is so big. I guess the first time result of baseline(49052) is fluky.

**Pull request closed without merging**
