### PR TITLE
[Optional Reference] LPS-185126 Convert the Optional Dynamic Greedy references to static references using Snapshot in classes DDMFormPortlet, DDMFormAdminPortlet and ExportFormInstanceMVCResourceCommand

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
ci:test:forms

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(5/24 8:27)

**Comment by W2jx** [comment]
Just resolving the order conflict of imported packages, no need to rerun test

**Comment by W2jx** [comment]
no conflicts(5/26 15:09)

**Comment by W2jx** [comment]
no conflicts(5/29 10:46)

**Pull request closed without merging**
