### PR TITLE
[Replace Non-Blocking Usage] LPS-199721

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace non-blocking ServiceProxyFactory usages in class `CookiesManagerUtil`, `ExportImportConfigurationSettingsMapFactoryUtil` and `ExportImportConfigurationParameterMapFactoryUtil`. Thanks.
https://liferay.atlassian.net/browse/LPS-199721

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
@JanisZhang possible regression:

```
[beanshell]      [exec] com.liferay.headless.delivery.resource.v1_0.test.NavigationMenuResourceTest > testGraphQLGetNavigationMenu FAILED
[beanshell]      [exec]     java.lang.IllegalStateException: No portlet bag for {"mvccVersion": 0, "id": 0, "companyId": 20095, "portletId": "com_liferay_change_tracking_web_portlet_PublicationsPortlet", "roles": "Administrator", "active": true}
[beanshell]      [exec]     	at com.liferay.portal.model.impl.PortletImpl.getPortletDataHandlerInstance(PortletImpl.java:1374)
[beanshell]      [exec]     	at com.liferay.portal.service.impl.GroupLocalServiceImpl.getPortletDataHandlers(GroupLocalServiceImpl.java:4506)
[beanshell]      [exec]     	at com.liferay.portal.service.impl.GroupLocalServiceImpl.addPortletDefaultData(GroupLocalServiceImpl.java:4112)
[beanshell]      [exec]     	at com.liferay.portal.service.impl.GroupLocalServiceImpl.addGroup(GroupLocalServiceImpl.java:528)
[beanshell]      [exec]     	at com.liferay.portal.service.impl.GroupLocalServiceImpl.addGroup(GroupLocalServiceImpl.java:543)
[beanshell]      [exec]     	at sun.reflect.GeneratedMethodAccessor3439.invoke(Unknown Source)
[beanshell]      [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell]      [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell]      [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41)
[beanshell]      [exec]     	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60)
[beanshell]      [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48)
[beanshell]      [exec]     	at com.liferay.portal.service.ServiceContextAdvice.invoke(ServiceContextAdvice.java:51)
[beanshell]      [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48)
[beanshell]      [exec]     	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-25/test-portal-acceptance-pullrequest(master)/3952/modules-integration-mysql57-jdk8/2/5/jenkins-console.txt.gz?authuser=0)

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
> catarineaguiar

Hi @catarineaguiar, I didn't reproduce this regression on my local env. And I rerun the relevant test, would you help to double-check it?  Thanks!

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@JanisZhang yea, it was flaky. Thanks for checking.

no regressions found

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142883

**Pull request closed without merging**
