### PR TITLE
LPS 150185 Apply HttpHelperUtil

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @tinatian,

This pull is to apply HttpHelpUtil in the portal.

For the last one commit, I added `@Ignore` for the _`SuggestionsPortletDisplayContextBuilderTest`_ ,because we need to use powermock mock static method, however, we encountered  the bug that existed in the Javassist version we used, we will bring it back once we change powermock to the new version mockito (or if we upgrade Javassist, it will cause other problems as @dantewang mentioned )

Thanks for checking!

### CODE REVIEW

**Comment by dantewang** [comment]
@JanisZhang I think you missed HttpImplTest itself.

**Comment by JanisZhang** [comment]
Thanks @dantewang, for PortalImplUnitTest and ProxyConfigTest, I think still got some issues after I changed  to `mockstatic(HttpHelperUtil.class)`

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/585

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
