### PR TITLE
[Static Reference]LPS-170377 Convert method references to field references in module wiki-web (class WikiWebComponentProvider)

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(2022/12/7 9:36)

**Review by dantewang — APPROVED** [review]
@tinatian Approved. I would like to explain a bit about the `WikiListPageDisplayContext`. In the past we mostly saw `DisplayContext` created in portlet or other things that dispatch to JSP, put into the request, and obtained from the JSP. However, this time we also see a lot of use cases creating and using `DisplayContext` instance in the same JSP.

Currently we decide to not refactor these usages, so in this PR the util usage in the `DisplayContext` is kept.

**Comment by W2jx** [comment]
no conflicts(2022/12/8 9:29)

**Comment by W2jx** [comment]
no conflicts(12/9 9:47)

**Comment by W2jx** [comment]
no conflicts(12/13 9:55)

**Comment by W2jx** [comment]
no conflicts(2022/12/14 9:41)

**Comment by W2jx** [comment]
no conflicts(12/15 9:25)

**Pull request closed without merging**
