### PR TITLE
[TS] LPS-145396 - TESTS (continuation)

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Hi @dantewang

TESTS of https://issues.liferay.com/browse/LPS-145396 - When we delete some types of objects in Liferay, we are not deleting their ResourcePermission records, leaving some orphan data in the ResourcePermission table.

Continuation of previous pull request https://github.com/liferay-core-infra/liferay-portal/pull/789

### Code changes in existing tests:

Following your comments here https://github.com/liferay-core-infra/liferay-portal/pull/789#discussion_r896423460, I have sent most of the test modifications in separated subtaks and pull requests to App. Security and Commerce teams (see https://github.com/liferay-appsec/liferay-portal/pull/704 and https://github.com/liferay-commerce/liferay-portal/pull/2823)

I have left one test change, see https://github.com/liferay-core-infra/liferay-portal/commit/4408c03427b03accaa06f50774b74fa0dcd08ba3 as I think this code belongs to Core Infra.

### Additional commit after yours:

About removing the `_orphanResourcePermissionDetection` method, as requested in this comment https://github.com/liferay-core-infra/liferay-portal/pull/789#discussion_r896416566 we can remove the method to avoid duplicating code, but we cannot remove all that code because we will end with some false positives, see these ci test failures https://github.com/dantewang/liferay-portal/pull/2227#issuecomment-1154984652 in the PR that you sent to your github user.

I have maintained your commit https://github.com/liferay-core-infra/liferay-portal/commit/9c71dd847830419cfb91e340d75359eaeddce187 but I have added an this additional one https://github.com/liferay-core-infra/liferay-portal/commit/688fa2194c49561a6e2f0fc11e4a13b51193e096 that solves the issues.

Explanation of this commit:
   - We have to delete the non-orphan ResourcePermissions that weren't deleted by the _smartDelete method because they are linked to a object that wasn't created during the test execution (for example the default Company or Group) or they have primkey == 0. 
   - We don't have to delete the orphan ResourcePermissions as they will be detected as orphan entries by the _autoDeleteAndAssert method logic and it will throw an assert error.

Let me know if you have any question or it is necessary to do additional changes.

### CODE REVIEW

**Comment by dantewang** [comment]
@jorgediaz-lr Thanks for the update! I have a question regarding this PR and https://github.com/dantewang/liferay-portal/pull/2227.

As you mentioned, some integration tests failed in https://github.com/dantewang/liferay-portal/pull/2227#issuecomment-1154984652, and they are considered as false positive. However, when I debug it today, I wonder whether all of them are, or should be, false positive.

For example, a `ResourcePermission` with name "com.liferay.commerce.account.model.CommerceAccount" is caught as leftover after running `CommerceMediaResolverTest` in my previous PR. This `ResourcePermission` is related to the `CommerceAccount` created during the test. Shouldn't this one be handled by `CommerceAccountLocalServiceImpl` (I do see a fix made by you previously)?

Here `CommerceAccount` is a bit special because it does not have its own table. It creates entries in `AccountEntry` table. When the test creates the `CommerceAccount`, I can see 2 `ResourcePermission` entries, one for `AccountEntry`, the other for `CommerceAccount`, but their `primKey` and `primKeyId` are both the `AccountEntry`'s `accountEntryId`.

On the other hand, I agree that the "not-orphan" ones should be explicitly deleted, but I wonder why we have such kind of data leftover. Do you have any example for a `ResourcePermission` that is not orphan after removing all the entities created during the test?

**Comment by jorgediaz-lr** [comment]
Hi @dantewang 

I am double checking this, perhaps we can remove some of the validations of the `_isOrphanResourcePermission` method, I am reviewing the tests.

I will keep you updated

**Comment by jorgediaz-lr** [comment]
Hi @dantewang 

I have been reviewing the `CommerceAccount` case and it wasn't correctly handled because as you said, it does not have its own table and uses the `AccountEntry` one.

And I included this condition https://github.com/liferay-core-infra/liferay-portal/pull/1020/commits/688fa2194c49561a6e2f0fc11e4a13b51193e096#diff-d987badaa7c5a1822c10382d9cfdc8711f3edad59b1b198cca0ffbd9790a7837R562-R567 that it ignores all the ResourcePermision that doesn't belong to a ClassName with a persisted model.

I have removed that condition and done some additional testing about `CommerceAccount` and I have found that:

- In some tests we have a false positive because the `ResourcePermissionTestUtil.deleteResourcePermissions` cleanup method that is executed in the smartDelete wasn't handling this special case of `CommerceAccount` that creates the entries in the `AccountEntry` table and have ResourcePermision records with both classNames. I have solved this with this change https://github.com/jorgediaz-lr/liferay-portal/commit/941fdb93153ba90b9e0275ce4bf6e6a2bf1f49aa
- In some tests we have a true positive because the `deleteCommerceAccountGroup(long commerceAccountGroupId)` method is not deleting all the related objects I am testing this commit https://github.com/jorgediaz-lr/liferay-portal/commit/28c11f65bef903419e17e95dac0b918b65595905 but I will send it in a separate subtask.

Nevertheless, I have to do some additional tests, because after doing these changes I have another errors that I have to check if they are false positive or not.

About your last question:

> On the other hand, I agree that the "not-orphan" ones should be explicitly deleted, but I wonder why we have such kind of data leftover. Do you have any example for a ResourcePermission that is not orphan after removing all the entities created during the test?

I have some examples:

-  **com.liferay.portal.osgi.web.portlet.container.upload.test.UploadPortletTest and com.liferay.portal.osgi.web.wab.reference.support.test.WabDirTest.classMethod** (see https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/90551/ ) The test creates some ResourcePermission records with scope = company and primKeyId = default company. This is one of the most repetitive false positive that I have found if I execute ci test without my last commit. In this situation the only option is to check if the company exists and delete the ResourcePermission objects.
- **com.liferay.portal.events.test.ServicePreActionTest.classMethod** (see https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/82123/testReport/junit/com.liferay.portal.events.test/ServicePreActionTest/classMethod/). In this ServicePreActionTest test we have a code that removes all the ResourcePermission records of Layout className, executes the test and add them again (see https://github.com/liferay/liferay-portal/blob/e9827e9465fdcee8dbcc2b1a60c58614fa8c6684/modules/apps/portal/portal-events-test/src/testIntegration/java/com/liferay/portal/events/test/ServicePreActionTest.java#L242-L285 ) so in the DataGuard code they are detected as new objects

I am testing some changes to this pull request in order to simplify my code without creating new false positives, I will keep you updated.

**Comment by dantewang** [comment]
@jorgediaz-lr Thank you very much for the details!

So I have something that I'd like to discuss or clarify here. I'll list my understanding below and please correct me if anything is wrong.

- The goal of this ticket is to make sure resource permissions created in association with creating database entity objects gets automatically deleted when removing those objects.
- The modification to the DataGuard test rule is to make it find out such cases and let developers know.
- A false positive is a resource permission not created in association with creation of database entity objects. For example, if I write an integration test and manually create a resource permission but forget to remove it (like the `ServicePreActionTest` you mentioned above).

If my understanding is correct, then,

- Logic to remove resource permission (`ResourcePermissionTestUtil.deleteResourcePermissions`) is added to `DeleteAfterTestRunMethodTestRule` in https://github.com/liferay-core-infra/liferay-portal/pull/1020/commits/0222a47184f227fb26690c2536c348f020ef016d, is it possible that it hides any true positive?
  - same question with the `ResourcePermissionTestUtil.deleteResourcePermissions` in `_smartDelete`

**Comment by jorgediaz-lr** [comment]
Hi @dantewang 

About your understanding:

> - The goal of this ticket is to make sure resource permissions created in association with creating database entity objects gets automatically deleted when removing those objects.
> - The modification to the DataGuard test rule is to make it find out such cases and let developers know.
> - A false positive is a resource permission not created in association with creation of database entity objects. For example, if I write an integration test and manually create a resource permission but forget to remove it (like the ServicePreActionTest you mentioned above).
> 

Yes it is correct, we want to warn the developers if they implement a code (for example in a *LocalServiceImpl class) that it is not correctly deleting the ResourcePermission entries linked to a object and this wrong delete method is executed inside a test.

About the `ResourcePermissionTestUtil.deleteResourcePermissions` that I have added in `DeleteAfterTestRunMethodTestRule` and `DataGuardTestRuleUtil._smartDelete` it shouldn't hide any false positive:
 - Both methods are directly calling the delete methods of PersistedModelLocalService to automatically delete the objects created during the test execution
 - So they are not executing the business logic of *LocalServiceImpl that handle the ResourcePermission deletion, so we have to manually delete it using the `ResourcePermissionTestUtil.deleteResourcePermissions` code to avoid generating additional orphan ResourcePermission

The real positives will be correctly detected when a delete method of *LocalServiceImpl is executed inside a test because both `DeleteAfterTestRunMethodTestRule` and `DataGuardTestRuleUtil._smartDelete` won't handle the objects that were already deleted in the test.

#### Timeline

I will show you a timeline of the code execution that I expect you will find useful:

1. `DataGuardTestRuleUtil.beforeClass` executes a _captureDataMap()
2. **<< test code is executed>>**:
      - Here the test creates objects with related ResourcePermissions. 
      - Some tests also execute object delete operations that should clean up their related ResourcePermission records. 
      - The tests don't usually delete everything they have created, we have two kind of objects: 
           - Some of the objects are orphan ResourcePermission from bugs of the delete operations
           - Other objects (_JournalArticle, DLFileEntry, Blogs, etc..._) are not orphan records and they will be correctly cleaned up by the DeleteAfterTestRunMethodTestRule or DataGuardTestRuleUtil code
4. `DeleteAfterTestRunMethodTestRule` is executed in some tests to automatically delete some of the created objects using the PersistedModelLocalService, **HERE:** we have to delete the ResourcePermission of the deleted objects to avoid generating false positive orphan ResourcePermissions. 
5. `DataGuardTestRuleUtil.afterClass` executes a _captureDataMap()
6. `_autoDeleteLeftovers` analyzes both dataMaps before and after test execution (step 1 and step 5) and it deletes all the objects created by the test execution to avoid leaving leftovers using the _smartDelete method. **HERE:** we have to change the logic to only delete the ResourcePermission that have primKeyId = 0 (not linked to any object) and we change the _smartDelete logic using ResourcePermissionTestUtil.deleteResourcePermissions to delete the non-orphan ResourcePermission linked to a object that we are handling here. The orphan ResourcePermissions generated during the test code execution won't be deleted and they will cause an assert error.
7. `_autoDeleteAndAssert` here the orphan ResourcePermissions are detected and an error is assert.

Let me know if you have any question

**Comment by jorgediaz-lr** [comment]
Hi @dantewang

I have been working on some changes to the tests. (see https://github.com/jorgediaz-lr/liferay-portal/pull/486 )

After implementing these changes, I will have to create a new LPS subtask to fix the error that I have detected in `deleteCommerceAccountGroup(long commerceAccountGroupId)` and I will have also to review some broken tests that I have found, I have to review if they are false positives or genuine errors.

Unfortunately this week I wasn't able to work on this and I will be on vacation until July 26th.

I will continue working on this after I am back.

**Comment by dantewang** [comment]
@jorgediaz-lr Thank you!

**Comment by tinatian** [comment]
@jorgediaz-lr Based the comments, seems you need to modify your code, I am going to close this pull, please resend.

Thanks.
Tina.

**Pull request closed without merging**
