### PR TITLE
[TS] LPD-21727

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__ <https://liferay.atlassian.net/browse/LPD-21727>

This pull request removes a dependency from Service Builder that is no longer used.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:report:2557473582

**Comment by kevhlee** [comment]
No unique failures found.

**Comment by tinatian** [comment]
@kevhlee 
The reason we have jalopy as it is imported by ToolsUtil which is used in service builder.

Let's do a deep clean up to remove jalopy from ToolsUtil:
1. Remove all the import from Jalopy, then remove the code with compile issue. 
2. Remove Jalopy from lib/development
3. Rebuild lib by "ant build-lib-versions"

Please resend.

Thanks.
Tina.

**Comment by kevhlee** [comment]
Hi @tinatian, ok I will work on removing Jalopy entirely from the codebase.

**Pull request closed without merging**
