### PR TITLE
[Method References 3] LPS-179402 Convert method reference to field reference in classes SelectLayoutSetBranchMVCActionCommand, ExpandoUserFieldExpressionHandler, KaleoDesignerWorkflowPortletTab

### PR DESCRIPTION
**Pull request by W2jx**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3994

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:staging

**Comment by Kvale1733** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
ci:test:saml

**Comment by W2jx** [comment]
no conflicts(3/24 13:29)

**Comment by W2jx** [comment]
no conflicts(3/27 9:41)

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
