### PR TITLE
LPS-173202 Remove "immediate = true" from Project templates

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:project-templates

**Comment by Kvale1733** [comment]
Relevant ran no tests but was still marked as passing. Rerunning.

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@GabrielHenriquedev No regressions.

**Comment by GabrielHenriquedev** [comment]
@tinatian this one is ready to go.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129233

**Pull request closed without merging**
