### PR TITLE
[Remove Immediate] LPS-188559 Remove immediate property from DLProcessorRegistryImpl

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://liferay.atlassian.net/browse/LPS-188559

The Lima team is aware of this and has agreed to the removal of DLProcessor support from the HookHotDeployListener, see Slack thread [here](https://liferay.slack.com/archives/CLD39UKM5/p1691525963182819).

Thx

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:lima

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@rafaprax semver error:

```
     [exec] > Task :baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.document.library.kernel.util           MAJOR      10.0.0     10.0.0     11.0.0     VERSION INCREASE REQUIRED
     [exec] 	+   class      com.liferay.document.library.kernel.util.DLProcessorHelperUtil
     [exec] 		+   method     <init>()
     [exec] 			+   return     void
     [exec] 		+   method     cleanUp(com.liferay.portal.kernel.repository.model.FileEntry)
     [exec] 			+   access     static
     [exec] 			+   return     void
     [exec] 		+   method     cleanUp(com.liferay.portal.kernel.repository.model.FileVersion)
     [exec] 			+   access     static
     [exec] 			+   return     void
     [exec] 		+   method     clone()
     [exec] 			+   access     protected
     [exec] 			+   return     java.lang.Object
     [exec] 		+   method     equals(java.lang.Object)
     [exec] 			+   return     boolean
     [exec] 		+   method     exportGeneratedFiles(com.liferay.exportimport.kernel.lar.PortletDataContext,com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.xml.Element)
     [exec] 			+   access     static
     [exec] 			+   return     void
     [exec] 		+   method     finalize()
     [exec] 			+   access     protected
     [exec] 			+   return     void
     [exec] 		+   method     hashCode()
     [exec] 			+   return     int
     [exec] 		+   method     importGeneratedFiles(com.liferay.exportimport.kernel.lar.PortletDataContext,com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.xml.Element)
     [exec] 			+   access     static
     [exec] 			+   return     void
     [exec] 		+   method     isPreviewableSize(com.liferay.portal.kernel.repository.model.FileVersion)
     [exec] 			+   access     static
     [exec] 			+   return     boolean
     [exec] 		+   method     toString()
     [exec] 			+   return     java.lang.String
     [exec] 		+   method     trigger(com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.repository.model.FileVersion)
     [exec] 			+   access     static
     [exec] 			+   return     void
     [exec] 		+   method     trigger(com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.repository.model.FileVersion,boolean)
     [exec] 			+   access     static
     [exec] 			+   return     void
     [exec] 	-   class      com.liferay.document.library.kernel.util.DLProcessorRegistryUtil
     [exec] 		-   method     <init>()
     [exec] 			-   return     void
     [exec] 		-   method     cleanUp(com.liferay.portal.kernel.repository.model.FileEntry)
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 		-   method     cleanUp(com.liferay.portal.kernel.repository.model.FileVersion)
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 		-   method     clone()
     [exec] 			-   access     protected
     [exec] 			-   return     java.lang.Object
     [exec] 		-   method     equals(java.lang.Object)
     [exec] 			-   return     boolean
     [exec] 		-   method     exportGeneratedFiles(com.liferay.exportimport.kernel.lar.PortletDataContext,com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.xml.Element)
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 		-   method     finalize()
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     getDLProcessor(java.lang.String)
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.document.library.kernel.util.DLProcessor
     [exec] 		-   method     hashCode()
     [exec] 			-   return     int
     [exec] 		-   method     importGeneratedFiles(com.liferay.exportimport.kernel.lar.PortletDataContext,com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.xml.Element)
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 		-   method     isPreviewableSize(com.liferay.portal.kernel.repository.model.FileVersion)
     [exec] 			-   access     static
     [exec] 			-   return     boolean
     [exec] 		-   method     register(com.liferay.document.library.kernel.util.DLProcessor)
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 		-   method     toString()
     [exec] 			-   return     java.lang.String
     [exec] 		-   method     trigger(com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.repository.model.FileVersion)
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 		-   method     trigger(com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.repository.model.FileVersion,boolean)
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 		-   method     unregister(com.liferay.document.library.kernel.util.DLProcessor)
     [exec] 			-   access     static
     [exec] 			-   return     void
     [exec] 	+   interface  com.liferay.document.library.kernel.util.DLProcessorHelper
     [exec] 		+   access     abstract
     [exec] 		+   method     cleanUp(com.liferay.portal.kernel.repository.model.FileEntry)
     [exec] 			+   access     abstract
     [exec] 			+   return     void
     [exec] 		+   method     cleanUp(com.liferay.portal.kernel.repository.model.FileVersion)
     [exec] 			+   access     abstract
     [exec] 			+   return     void
     [exec] 		+   method     exportGeneratedFiles(com.liferay.exportimport.kernel.lar.PortletDataContext,com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.xml.Element)
     [exec] 			+   access     abstract
     [exec] 			+   return     void
     [exec] 		+   method     importGeneratedFiles(com.liferay.exportimport.kernel.lar.PortletDataContext,com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.xml.Element)
     [exec] 			+   access     abstract
     [exec] 			+   return     void
     [exec] 		+   method     isPreviewableSize(com.liferay.portal.kernel.repository.model.FileVersion)
     [exec] 			+   access     abstract
     [exec] 			+   return     boolean
     [exec] 		+   method     trigger(com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.repository.model.FileVersion)
     [exec] 			+   access     abstract
     [exec] 			+   return     void
     [exec] 		+   method     trigger(com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.repository.model.FileVersion,boolean)
     [exec] 			+   access     abstract
     [exec] 			+   return     void
     [exec] 	-   interface  com.liferay.document.library.kernel.util.DLProcessorRegistry
     [exec] 		-   access     abstract
     [exec] 		-   method     cleanUp(com.liferay.portal.kernel.repository.model.FileEntry)
     [exec] 			-   access     abstract
     [exec] 			-   return     void
     [exec] 		-   method     cleanUp(com.liferay.portal.kernel.repository.model.FileVersion)
     [exec] 			-   access     abstract
     [exec] 			-   return     void
     [exec] 		-   method     exportGeneratedFiles(com.liferay.exportimport.kernel.lar.PortletDataContext,com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.xml.Element)
     [exec] 			-   access     abstract
     [exec] 			-   return     void
     [exec] 		-   method     getDLProcessor(java.lang.String)
     [exec] 			-   access     abstract
     [exec] 			-   return     com.liferay.document.library.kernel.util.DLProcessor
     [exec] 		-   method     importGeneratedFiles(com.liferay.exportimport.kernel.lar.PortletDataContext,com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.xml.Element)
     [exec] 			-   access     abstract
     [exec] 			-   return     void
     [exec] 		-   method     isPreviewableSize(com.liferay.portal.kernel.repository.model.FileVersion)
     [exec] 			-   access     abstract
     [exec] 			-   return     boolean
     [exec] 		-   method     register(com.liferay.document.library.kernel.util.DLProcessor)
     [exec] 			-   access     abstract
     [exec] 			-   return     void
     [exec] 		-   method     trigger(com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.repository.model.FileVersion)
     [exec] 			-   access     abstract
     [exec] 			-   return     void
     [exec] 		-   method     trigger(com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.repository.model.FileVersion,boolean)
     [exec] 			-   access     abstract
     [exec] 			-   return     void
     [exec] 		-   method     unregister(com.liferay.document.library.kernel.util.DLProcessor)
     [exec] 			-   access     abstract
     [exec] 			-   return     void
     [exec] [Baseline Warning] Bundle Version Change Recommended: 121.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/120.2.0/ba771a8f68ee8685f93ec3c5e62e7057ea71906f/com.liferay.portal.kernel-120.2.0.jar
     [exec] Gradle build finished at 2023-08-11 22:28:51.507.
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-08/test-1-39/test-portal-acceptance-pullrequest(master)/6661/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@rafaprax Please add this "The Lima team is aware of this and has agreed to the removal of DLProcessor support from the HookHotDeployListener, see Slack thread [here](https://liferay.slack.com/archives/CLD39UKM5/p1691525963182819)." to the commit message

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
@rafaprax Conflicts in the breaking_changes file, please update, thanks!

**Comment by rafaprax** [comment]
Conflict solved.

**Comment by tinatian** [comment]
@rafaprax Please separate this pull into two pulls, make the first two commits a separate pull. 

Thanks.
Tina

**Comment by rafaprax** [comment]
@tinatian, breaking change sent here https://github.com/liferay-core-infra/liferay-portal/pull/5328

**Pull request closed without merging**
