### PR TITLE
[Remove Blocking usages]LPS-188270 portal-kernel | ConfigurationProviderUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:help

**Comment by zhangyan0701** [comment]
Issues:
1. [com.liferay.journal.transformer.test.JournalTransformerTest](https://testray.liferay.com/home/-/testray/case_results/2403981000):
Full console log:
https://testray.liferay.com/reports/production/logs/2023-08/test-1-29/test-portal-acceptance-pullrequest(master)/7826/modules-integration-mysql57-jdk8/2/10/jenkins-console.txt.gz?authuser=0

2. Some tests failed with error: `No field on null with name _configurationProvider`.
[com.liferay.dynamic.data.mapping.form.web.internal.upload.DDMFormUploadValidatorTest](https://testray.liferay.com/home/-/testray/case_results/2403981000).
Full console log:
https://testray.liferay.com/reports/production/logs/2023-08/test-1-29/test-portal-acceptance-pullrequest(master)/7826/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

[com.liferay.journal.web.internal.display.context.JournalEditArticleDisplayContextTest](https://testray.liferay.com/home/-/testray/case_results/2403980721)
Full console log:
https://testray.liferay.com/reports/production/logs/2023-08/test-1-29/test-portal-acceptance-pullrequest(master)/7826/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0

3. Semantic versioning issue:
```
     [exec] > Task :apps:asset:asset-display-page-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.asset.display.page.portlet             MINOR      7.0.0      7.0.0      7.1.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.asset.display.page.portlet.BaseAssetDisplayPageFriendlyURLResolver
     [exec] 		+   field      configurationProvider
     [exec] 			+   access     protected
     [exec] 			+   annotated  org.osgi.service.component.annotations.Reference
     [exec] 			+   return     com.liferay.portal.kernel.module.configuration.ConfigurationProvider
     [exec] [Baseline Warning] Bundle Version Change Recommended: 12.1.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.asset.display.page.api-12.0.2.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.asset.display.page.api/12.0.1/b26168a6f4bd6e110a52c6bfcfda510ec930962a/com.liferay.asset.display.page.api-12.0.1.jar
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-08/test-1-29/test-portal-acceptance-pullrequest(master)/7826/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by dantewang** [comment]
Please fix and resend, thanks.

**Comment by W2jx** [comment]
see https://github.com/liferay-core-infra/liferay-portal/pull/5241

**Pull request closed without merging**
