### PR TITLE
[SF] LPS-198137 Re-enable checking for self-registering OSGi components

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__ <https://liferay.atlassian.net/browse/LPS-198137>

I re-configured `JavaComponentAnnotationsCheck` to check OSGi component classes that register themselves as service types. I have added a new SF property to the check to allow a list of classes/directories that are exempt. Since there are hundreds of violations (393 to be exact), I collapsed the class names I specified in `allowedSelfRegistrationClassNames` as much as possible.

cc: @rafaprax

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Review by rafaprax — APPROVED** [review]

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142326

**Pull request closed without merging**
