### PR TITLE
[Method References 2] LPS-165165 Convert method reference to ServiceTrackerList in module portal-search-elasticsearch7-impl | part 1

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@W2jx 

central-requirements-jdk8/0/0
```
junit] Testcase: testScanGradleFiles(com.liferay.portal.modules.ModulesStructureTest):	FAILED
    [junit] Redundant dependency detected in modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/build.gradle expected:<compileOnly project(":core:osgi-service-tracker-collections")> but was:<testCompile project(":core:osgi-service-tracker-collections")>
    [junit] junit.framework.AssertionFailedError: Redundant dependency detected in modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/build.gradle expected:<compileOnly project(":core:osgi-service-tracker-collections")> but was:<testCompile project(":core:osgi-service-tracker-collections")>
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest._testGradleFile(ModulesStructureTest.java:1515)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest.access$800(ModulesStructureTest.java:68)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest$4.visitFile(ModulesStructureTest.java:402)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest$4.visitFile(ModulesStructureTest.java:376)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest.testScanGradleFiles(ModulesStructureTest.java:374)
```
[Log](https://testray.liferay.com/reports/production/logs/2022-11/test-1-32/test-portal-acceptance-pullrequest(master)/6641/central-requirements-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No regressions found.

**Pull request closed without merging**
