### PR TITLE
[Rename classes under modules:data-engine, depot]Lps 166996

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-166996

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@slnn semver error:

```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/data-engine/data-engine-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.data.engine.nativeobject.tracker       MAJOR      1.0.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-39/test-portal-acceptance-pullrequest(master)/1358/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
Thank @catarineaguiar for catching this!

I have updated and forced push to this pull to fix the semver error.

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test;relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Comment by slnn** [comment]
Update the commit message according to https://github.com/liferay-core-infra/liferay-portal/pull/2249#issuecomment-1298180178
no logic changes

**Comment by dantewang** [comment]
@slnn For commits like https://github.com/liferay-core-infra/liferay-portal/pull/2251/commits/722263ab0812b824a186785aa0d6756086be0d8d, if what you mean is that the class has already been renamed before, but the test hasn't, then please make it an SF commit.

I'm going to close this one, please change the messages, rebase and resend.

**Comment by slnn** [comment]
> @slnn For commits like [722263a](https://github.com/liferay-core-infra/liferay-portal/commit/722263ab0812b824a186785aa0d6756086be0d8d), if what you mean is that the class has already been renamed before, but the test hasn't, then please make it an SF commit.
> 
> I'm going to close this one, please change the messages, rebase and resend.

Done, resend in https://github.com/liferay-core-infra/liferay-portal/pull/2340

**Pull request closed without merging**
