### PR TITLE
LPS-147042 Remove nekohtml.jar

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by vicnate5** [comment]
@koor4356 can you check this one?

**Comment by koor4356** [comment]
okay, thanks!

**Comment by tinatian** [comment]
@guilhermedcamacho 
Code looks good to me, wait for QA to scan test results.
Please note that there are two modules compileInclude this jar, please add it to the task list for compleInclude clean up.
`modules/apps/portal-security/portal-security-antisamy/build.gradle:	compileInclude group: "net.sourceforge.nekohtml", name: "nekohtml", version: "1.9.22"
modules/apps/diff/diff-impl/build.gradle:	compileInclude group: "net.sourceforge.nekohtml", name: "nekohtml", version: "1.9.22"
`
Thanks.
Tina.

**Comment by koor4356** [comment]
@guilhermedcamacho @vicnate5,
There is a warning error. I am not sure it is caused by this PR. Can you take a look, please? Thanks!

` WARN  [Portal Dependency Manager Component Executor--1][PortalPreferencesPersistenceImpl:214] PortalPreferencesPersistenceImpl.fetchByO_O(long, int, boolean) with parameters (0,1) yields a result set with more than 1 result. This violates the logical unique restriction. There is no order guarantee on which result is returned by this finder.
WARN  [main][PortalPreferencesPersistenceImpl:214] PortalPreferencesPersistenceImpl.fetchByO_O(long, int, boolean) with parameters (0,1) yields a result set with more than 1 result. This violates the logical unique restriction. There is no order guarantee on which result is returned by this finder.`

https://testray.liferay.com/reports/production/logs/2022-02/test-1-32/test-portal-acceptance-pullrequest(master)/2436/functional-tomcat90-mysql57-jdk8/23/21/jenkins-console.txt.gz?authuser=0

https://testray.liferay.com/home/-/testray/case_results/1609933038

**Comment by vicnate5** [comment]
@guilhermedcamacho Not related, it is some kind of random error. Reported under LRQA-73016.

**Comment by guilhermedcamacho** [comment]
Thanks @vicnate5 :+1: 
@shuyangzhou , this PR is ready for your review. Thank you!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113394

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
