### PR TITLE
[Components with more than 1 service] LPS-179592 Refactor ScreenNavigationCategory components from Commerce modules part 5

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Review by rafaprax — CHANGES_REQUESTED** [review]
@MrJohn1911 just to you do not forget, do not use the reference to the Category class into the Entry ones. Thx

**Comment by MrJohn1911** [comment]
@rafaprax since this pull had more than 15 commits, I sent some of them [here](https://github.com/liferay-core-infra/liferay-portal/pull/4052).

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions.

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Review by rafaprax — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by rafaprax — CHANGES_REQUESTED** [review]
Hey @MrJohn1911 , please rename the modules/apps/commerce/commerce-product-type-grouped-web/src/main/java/com/liferay/commerce/product/type/grouped/web/internal/constants/CPTypeGroupedConstants.java properly. Thx

**Comment by MrJohn1911** [comment]
This last push was just to rename an constants class from CPTypeGroupedConstants to CPTypeGroupedScreenNavigationConstants.

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions.

**Pull request closed without merging**
