### PR TITLE
[OrderByComparator] LPD-25934 Clean up unused OrderByComparator constructors and classes - Part III

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:content-management

**Comment by MrJohn1911** [comment]
ci:test:object

**Comment by MrJohn1911** [comment]
ci:test:workflow

**Comment by MrJohn1911** [comment]
ci:test:security

**Comment by MrJohn1911** [comment]
ci:test:object

**Comment by tinatian** [comment]
@MrJohn1911 Please see my message on slack.

**Pull request closed without merging**
