### PR TITLE
[TS] LPS-151178 Adding logic that handles the cases when the Serializable is: Integer array, Long array, Object array, String array

### PR DESCRIPTION
**Pull request by evibudai**
Hi Team,

https://issues.liferay.com/browse/LPS-151178

Issue:
When we add categories to documents in a clustered environment on the slave node, it throws an exception on the master node and the saving of the category is not successful.
The exception was caused by a classCastException, because the method was only handling the arrays of type Long.

Solution:
I implemented a logic that handles all the possibilities, not just when the Serializable is of type Long.

I tested it in my local environment and it worked as expected.

Please review my PR!

Best regards,
Évi

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:clustering

**Comment by lilylcl** [comment]
ci:test:stable

**Comment by evibudai** [comment]
Hi all, it's possible that this PR won't be accepted, because I made this as an alternative solution instead of https://github.com/liferay-core-infra/liferay-portal/pull/4683, and it might be better to follow that route.

**Comment by catarineaguiar** [comment]
@evibudai issue found:

```
[echo] diff --git a/lib/development/asm-commons.jar b/lib/development/asm-commons.jar
     [echo] old mode 100644
     [echo] new mode 100755
     [echo] diff --git a/portal-kernel/src/com/liferay/portal/kernel/util/ArrayUtil_IW.java b/portal-kernel/src/com/liferay/portal/kernel/util/ArrayUtil_IW.java
     [echo] index 0cd7a7ff5d82..536187e664ce 100644
     [echo] --- a/portal-kernel/src/com/liferay/portal/kernel/util/ArrayUtil_IW.java
     [echo] +++ b/portal-kernel/src/com/liferay/portal/kernel/util/ArrayUtil_IW.java
     [echo] @@ -620,6 +620,10 @@ public class ArrayUtil_IW \{
     [echo]      return ArrayUtil.toArray(array);
     [echo]    \}
     [echo]  
     [echo] +  public long[] toArray(java.lang.Object[] array) \{
     [echo] +    return ArrayUtil.toArray(array);
     [echo] +  \}
     [echo] +
     [echo]    public java.lang.Short[] toArray(short[] array) \{
     [echo]      return ArrayUtil.toArray(array);
     [echo]    \}
     [echo] @@ -655,6 +659,10 @@ public class ArrayUtil_IW \{
     [echo]      return ArrayUtil.toLongArray(array);
     [echo]    \}
     [echo]  
     [echo] +  public long[] toLongArray(java.lang.Integer[] array) \{
     [echo] +    return ArrayUtil.toLongArray(array);
     [echo] +  \}
     [echo] +
     [echo]    public java.lang.Long[] toLongArray(long[] array) \{
     [echo]      return ArrayUtil.toLongArray(array);
     [echo]    \}
     [echo] @@ -663,6 +671,10 @@ public class ArrayUtil_IW \{
     [echo]      return ArrayUtil.toLongArray(array);
     [echo]    \}
     [echo]  
     [echo] +  public long[] toLongArray(java.lang.String[] array) \{
     [echo] +    return ArrayUtil.toLongArray(array);
     [echo] +  \}
     [echo] +
     [echo]    public short[] toShortArray(
     [echo]      java.util.Collection<java.lang.Short> collection) \{
     [echo]      return ArrayUtil.toShortArray(collection);
[stopwatch] [run.batch.test.action: 2.967 sec]
     [echo] .
     [echo] 
     [echo] Detected build-iw changes. See above build-iw log for more
```

**Comment by evibudai** [comment]
> should we ignore it?
@catarineaguiar 

Please don't discard my PR yet. I'm sending a fix for the mentioned failures.

**Comment by evibudai** [comment]
ci:test:stable

**Comment by evibudai** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@evibudai Please remember to remove the QA Failed flag to trigger a new round of scanning by QA, or else you pull will be marked as failed and no developer is going to review it. Another way to avoid this is to always send a new pull request.

Tina

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by tinatian** [comment]
@evibudai Please do not add the api only used by your own code to ArrayUtil : https://github.com/liferay-core-infra/liferay-portal/pull/4933/commits/fb64293d59cac98efa259552f7f08967b401f1ee.

If you do not need to modify ArrayUtil, then you do not need to send the fix to core-infra, please send the fix to corresponding application team, thus I am going to close this pull.

Thanks.
Tina

**Comment by evibudai** [comment]
hi @tinatian, all right!

**Pull request closed without merging**
