### PR TITLE
[OrderByComparator] LPD-26560

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
Clean up and Apply Singleton.
[Jira ticket](https://liferay.atlassian.net/browse/LPD-26560).

### CODE REVIEW

**Comment by JerryAdrianoo** [comment]
ci:help

**Comment by JerryAdrianoo** [comment]
ci:test:relevant

**Comment by JerryAdrianoo** [comment]
ci:test:sf

**Comment by JerryAdrianoo** [comment]
ci:report:67347492

**Comment by JerryAdrianoo** [comment]
ci:report:67349854

**Comment by JerryAdrianoo** [comment]
ci:stop

**Comment by JerryAdrianoo** [comment]
ci:test:stable

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
