### PR TITLE
[Remove Stream/Optional usage] LPS-174124 Remove usages of Stream for module: search-experiences-service

### PR DESCRIPTION
**Pull request by W2jx**
Hi @dantewang , I have replaced ListUtil.toArray() with TransformUtil.transformToArray.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3226

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(2/8 8:57)

**Comment by W2jx** [comment]
no conflicts(2/9 10:25)

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130404

**Pull request closed without merging**
