### PR TITLE
LPS-145344

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian , @shuyangzhou ,

Resend. Updated the commit (https://github.com/tinatian/liferay-portal/pull/2487) with the correct message, find the correct commit that we deleted the usage of "look.and.feel.modifiable". 
I remove unused properties "look.and.feel.modifiable".
- It was created in commit c90a3a00d52c7cbd2ad7c7d143f986dedf14980a, see LEP-4549, and It was used in "edit_pages.jsp”.
- “edit_pages.jsp” was renamed from portal-web/docroot/html/portlet/communities/edit_pages.jsp to portal-web/docroot/html/portlet/layouts_admin/edit_pages.jsp based on commit c9e38b0d10571717022a672073ce78c9b2f6bf5f, see LPS-15140.
- Then, it was used in portal-web/docroot/html/portlet/layouts_admin/view.jsp, based on 5106ccbe3b6ec648b2cfd768460f76023db002cf, see LPS-15178.
- It was finally deleted in commit bf6bd992543081cfb556d2f7c70ba7094291bb0f, see LPS-14453.
Thanks for checking!

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:test:stable

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@jeffwu0724 Code looks good to me, please put it into your list, I am going to close it.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
