### PR TITLE
LPS-182376 Remove static references in modules site-navigation, social and wiki

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-182376](https://issues.liferay.com/browse/LPS-182376)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:wiki

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:wiki

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@RenanUmV No regressions.

**Comment by tinatian** [comment]
@RenanUmV Please remove NavItemClassNameIdUtil and use ClassNameLocalServiceUtil to get ClassNameId directly. I believe the Portal api is only used in the case ClassNameLocalServiceUtil is not ready, in your case, it is used in taglib which must happen after portal is fully loaded, you should be able to use ClassNameLocalServiceUtil directly.

Tina.

**Comment by tinatian** [comment]
@RenanUmV Please inline WikiPageAttachmentHorizontalCard into its only usage.

Thanks.
Tina

**Comment by RenanUmV** [comment]
@tinatian , the class WikiPageAttachmentHorizontalCard is used in four jsp files, i'm not sure if I can modify this file

[full_content.jsp](https://github.com/liferay/liferay-portal/blob/186465a25f3cf9e55db342d541c7a3e89a013733/modules/apps/wiki/wiki-web/src/main/resources/META-INF/resources/wiki/asset/full_content.jsp#L95)

[init.jsp](https://github.com/liferay/liferay-portal/blob/186465a25f3cf9e55db342d541c7a3e89a013733/modules/apps/wiki/wiki-web/src/main/resources/META-INF/resources/wiki/asset/init.jsp#L42)

[init.jsp](https://github.com/liferay/liferay-portal/blob/186465a25f3cf9e55db342d541c7a3e89a013733/modules/apps/wiki/wiki-web/src/main/resources/META-INF/resources/wiki/init.jsp#L62)

[view_attachments.jsp](https://github.com/liferay/liferay-portal/blob/186465a25f3cf9e55db342d541c7a3e89a013733/modules/apps/wiki/wiki-web/src/main/resources/META-INF/resources/wiki/view_attachments.jsp#L37)

**Comment by dantewang** [comment]
@RenanUmV Then please just do https://github.com/liferay-core-infra/liferay-portal/pull/4416#issuecomment-1535467952

**Pull request closed without merging**
