### PR TITLE
LPS-143632 Remove LanguageUtil from moduels part 3a mixed

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:acceptance

**Comment by julschong** [comment]
@vicnate5 Hi Victor,
please help me stop this acceptance test to reduce load.
Thanks!

**Comment by vicnate5** [comment]
@julschong Done. thanks.

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,

Could you please help me scan this test result?

Thanks!

**Comment by catarineaguiar** [comment]
@julschong possible regresion:

`DDMContentUpgradeProcessTest`
```
[exec] com.liferay.dynamic.data.mapping.internal.upgrade.v3_10_2.DDMContentUpgradeProcessTest > testUpgradeDDMContentData FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.dynamic.data.mapping.internal.io.DDMFormValuesJSONDeserializer._getLocalizedValue(DDMFormValuesJSONDeserializer.java:249)
     [exec]         at com.liferay.dynamic.data.mapping.internal.io.DDMFormValuesJSONDeserializer.getValue(DDMFormValuesJSONDeserializer.java:158)
     [exec]         at com.liferay.dynamic.data.mapping.internal.io.DDMFormValuesJSONDeserializer._setDDMFormFieldValueValue(DDMFormValuesJSONDeserializer.java:294)
     [exec]         at com.liferay.dynamic.data.mapping.internal.io.DDMFormValuesJSONDeserializer._getDDMFormFieldValue(DDMFormValuesJSONDeserializer.java:220)
     [exec]         at com.liferay.dynamic.data.mapping.internal.io.DDMFormValuesJSONDeserializer.getDDMFormFieldValues(DDMFormValuesJSONDeserializer.java:139)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-07/test-1-32/test-portal-acceptance-pullrequest(master)/5015/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
@catarineaguiar 
just comfirming that I can replicate this error locally. Will close this pull and resend

**Pull request closed without merging**
