### PR TITLE
[TS]LPS-201632

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:service-builder

**Comment by Kvale1733** [comment]
@tinatian No regressions. Testing passed with the modified test service

**Comment by tinatian** [comment]
ci:forward:force

FYI @shuyangzhou

**Comment by dantewang** [comment]
Manually sent to https://github.com/brianchandotcom/liferay-portal/pull/144491

**Pull request closed without merging**
