### PR TITLE
LPS-149266

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

After discussion, Dante helps me to modify the unit test, please see  https://github.com/jeffwu0724/liferay-portal/pull/90. cc:  @dantewang
This PR is to fix https://issues.liferay.com/browse/LPS-149266.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result again, please?

Thanks
Jeff

**Comment by dantewang** [comment]
@zhangyan0701 Could you check the test results? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@jeffwu0724 Please rebase.

Tina

**Comment by jeffwu0724** [comment]
Hey @tinatian , I already rebased and fixed the code conflict.
Thanks for letting me know!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
@jeffwu0724 @tinatian the code does not compile, must be a rebase issue. please resend.

**Pull request closed without merging**
