### PR TITLE
LPS-145571

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian, @shuyangzhou ,

Resend, resolve the conflicts with Brian's master. See (https://github.com/liferay-core-infra/liferay-portal/pull/210).
I have removed unused properties "Index.with.thread", and updated to propskeys.java, propsvalues.java and verifyproperties.java.

"INDEX_WITH_THREAD" was added in commit 8f6217e, see LPS-16139, and it was used in "LuceneHelperImpl.java".
It was moved to "modules/portal/portal-search-lucene/src/com/liferay/portal/search/lucene/internal/LuceneIndexSearcher.java" in commit 60db4fa, see LPS-54860.
It was finally moved the usage in commit f125dd5, see LPS-56180.
Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@jeffwu0724 Code looks good to me, please put this into your list. I am going to close this pull.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
