### PR TITLE
[Reference cleanup]LPS-160968

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to replace method setServletContext with field _servletContext in class extends BaseDynamicInclude. Thanks!
https://issues.liferay.com/browse/LPS-160968

Previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/1422

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @zhangyan0701 , Could you please help to scan the test results? thank you

**Comment by tinatian** [comment]
@JanisZhang Next time, if Shuyang close your pull because you need to rebase, please rebase and force push the original pull and reopen it, no need to go through the normal review process.

Thanks.
Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122533

**Comment by JanisZhang** [comment]
> @JanisZhang Next time, if Shuyang close your pull because you need to rebase, please rebase and force push the original pull and reopen it, no need to go through the normal review process.
> 
> Thanks. Tina.

Hi @tinatian,
Thank you for bringing it up! 
Sorry that I forgot to mention one thing. I found one newly added subclass [DefaultAddressesJSPDynamicInclude.java](https://github.com/liferay-core-infra/liferay-portal/pull/1519/commits/8e92fa3d5b43af323bbca8006a67d477015e90f0#diff-2d4b4e45e4cbab2c0ea8804fc5491c7c73546a3f9923db1db715633d07faee04) of `BaseJSPDynamicInclude` during the rebase process and I included it in this PR. Not so sure about the impact of this, so I'm thinking it might need to redo **ci:test**. Next time I will force-pushed if no more new changes. Thanks again!

**Pull request closed without merging**
