### PR TITLE
[Remove unused field] LPS-199021 Remove unused reference field in class PermissionsPortletConfigurationIcon

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@W2jx No regressions found. SF is unrelated.

**Comment by W2jx** [comment]
no conflicts(10/17 8:23)

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142349

**Pull request closed without merging**
