### PR TITLE
LPS-142278 Remove portal lib dir property | 2022-1-12

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian I excluded DirectDeployTask in this pull. For DirectDeployTask, I'll keep an eye on https://issues.liferay.com/browse/LPS-144814 with dev tools team.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Force pushed to rebase.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@zhanyang0701 Could you review the test results? Thanks!

**Comment by zhangyan0701** [comment]
No related failures found.

**Comment by dantewang** [comment]
@tinatian @shuyangzhou Manually forwarded to Brian as there's customer requesting for the fix related to this PR.
See https://github.com/brianchandotcom/liferay-portal/pull/112582

**Pull request closed without merging**
