### PR TITLE
[Remove Stream usage from: analytics/analytics-message-sender-impl ]LPS-174994 Remove usages of Stream in Method Body for module: analyti…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-174944

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:analytics-cloud-acceptance

**Comment by Kvale1733** [comment]
ci:test:analytics-cloud-acceptance

**Comment by Kvale1733** [comment]
@slnn No regressions. Just an SF issue. There is a typo in the commit message. The ticket number is wrong.

**Comment by dantewang** [comment]
@slnn Please correct the ticket number in the git commit message and forward to Brian, thanks!

**Pull request closed without merging**
