### PR TITLE
LPS-168681 ant snapshot-bundle blocked by CloudFlare

### PR DESCRIPTION
**Pull request by topolik**
Hi guys,

https://issues.liferay.com/browse/LPS-168681

I bumped into this issue. Please let me know who to resend if it's not yours component.

Thanks.

### CODE REVIEW

**Comment by dantewang** [comment]
@vicnate5 Is this in our scope?

**Comment by vicnate5** [comment]
This is dev tools scope @petershin

**Comment by petershin** [comment]
@vicnate5 - the author of this file is Peter Yoo. I'd fwd this one to him

**Comment by tinatian** [comment]
@petershin As it is going to be forwarded, I am going to close this pull. 

Thanks.
Tina.

**Comment by achaparro** [comment]
Hi @petershin, have you already forwarded this pull to @pyoo47?

Thx

**Pull request closed without merging**
