### PR TITLE
LPS-150808 Move petra-http-invoker to core/petra

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,

Main Task: [LPS-147928](https://issues.liferay.com/browse/LPS-147928)
SubTask: [LPS-150808](https://issues.liferay.com/browse/LPS-150808)

Thank you

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
could you please help me scan the test result?
Thank you!

**Comment by tinatian** [comment]
@julschong code looks good to me, wait for QA to scan test results.

Tina.

**Comment by catarineaguiar** [comment]
@julschong @tinatian no regressions found.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
