### PR TITLE
[Remove Blocking usages]LPS-188565 portal-kernel | FriendlyURLNormalizerUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:friendly-url

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(6/26 15:25)

**Comment by W2jx** [comment]
no conflicts(6/27 8:52)

**Comment by W2jx** [comment]
no conflicts(7/4 14:30)

**Comment by W2jx** [comment]
no conflicts(7/5 13:57)

**Comment by W2jx** [comment]
no conflicts(7/6 8:08)

**Pull request closed without merging**
