### PR TITLE
[Spring Beans] LPS-202459 Move PrefsPropsImpl into module

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/6198

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:test:startup

**Comment by W2jx** [comment]
Forced push to resolve the conflict about bnd file, no logic changes.

**Comment by W2jx** [comment]
ci:report:2487322174

**Comment by W2jx** [comment]
ci:report:2487323357

**Comment by W2jx** [comment]
ci:report:2487327074

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:report:2487981916

**Comment by W2jx** [comment]
ci:report:2487322174

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:report:2487988691

**Comment by W2jx** [comment]
No regressions found.
cc @dantewang

**Comment by dantewang** [comment]
ci:forward:force


cc @tinatian

**Comment by W2jx** [comment]
ci:report:2488650690

**Comment by W2jx** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 2488650690.
> 
> Job Link: [generate-testray-csv](https://test-1-9.liferay.com/job/generate-testray-csv/1/)
> 
> Testray CSV Link: [Testray CSV](https://test-1-9.liferay.com/userContent/jobs/generate-testray-csv/builds/1/testray-results.csv)

No Unique Failures found.

**Pull request closed without merging**
