### PR TITLE
[Bug Fix]LPS-176945 Change the type of field _jaxRsApplicationNames to list

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:help

**Comment by W2jx** [comment]
ci:test:oauth2

**Comment by dantewang** [comment]
@W2jx Could you explain the context of this a bit more? Please point out which classes share the same value of the property, and why you think this should be supported.

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
> @W2jx Could you explain the context of this a bit more? Please point out which classes share the same value of the property, and why you think this should be supported.

Hi @dantewang , there is no case of sharing the same value of the property in our code, and interface ScopeFinder is a Provider-Type interface, so there will be no user creating components that share the same value of the property, so I think it is unnecessary to use set,
And I'd like to replace it with ServiceTrackerList, but I'm not sure if it would be misleading to convert it directly, so I changed its type in a separate PR first.

**Pull request closed without merging**
