### PR TITLE
LPS-152081 Clean up MailEngine unused methods

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar 
Hi Catarine,
Could you please help me scan the test result?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

TIna

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
