### PR TITLE
[Component with its own class name as service type] Refactor UploadResponseHandler and UploadFileEntryHandler components from dynamic-data-mapping and document-library modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-195397

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:forms

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140554

**Pull request closed without merging**
