### PR TITLE
LPS-198319 Merge ImageTool interface and impl into Util and move to portal-impl

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:document

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
@julschong please rebase, thanks!

**Comment by julschong** [comment]
rebased and reran semver

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
should recheck baseline version from relevant

**Comment by julschong** [comment]
fix SF

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Hi @julschong There are some conflicts, please resolve them first, thanks!

**Comment by julschong** [comment]
rebased

**Comment by julschong** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:document

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by julschong** [comment]
added breaking change commit messages

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142551

**Pull request closed without merging**
