### PR TITLE
LPS 157580

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hi,

The objective of this PR is use the values of the properties in the code.

Right now customers in 7.4 Global services is suggesting customers to set this folders into a different location to prevent problems with their custom bundles but some properties are not been used in the code.

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@robertoDiaz fix the commit message, please. The JIRA issue is wrong.

Thanks

**Comment by catarineaguiar** [comment]
@robertoDiaz regression found:

```
exec] /opt/dev/projects/github/liferay-portal/modules/sdk/gradle-plugins-defaults/src/main/java/com/liferay/gradle/plugins/defaults/LiferayOSGiDefaultsPlugin.java:95: error: package com.liferay.portal.util does not exist
     [exec] import com.liferay.portal.util.PropsUtil;
     [exec]                               ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/sdk/gradle-plugins-defaults/src/main/java/com/liferay/gradle/plugins/defaults/LiferayOSGiDefaultsPlugin.java:96: error: package com.liferay.portal.util does not exist
     [exec] import com.liferay.portal.util.PropsValues;
     [exec]                               ^
     [exec] 
     [exec] > Task :sdk:gradle-plugins-defaults:compileJava
     [exec] /opt/dev/projects/github/liferay-portal/modules/sdk/gradle-plugins-defaults/src/main/java/com/liferay/gradle/plugins/defaults/LiferayOSGiDefaultsPlugin.java:970: error: cannot find symbol
     [exec] 						PropsUtil.get(
     [exec] 						^
     [exec]   symbol: variable PropsUtil
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 3 errors
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-34/test-portal-acceptance-pullrequest(master)/2546/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by robertoDiaz** [comment]
Closing, it seems that I rebase the wrong code.

I'll resend tomorrow

**Comment by robertoDiaz** [comment]
@catarineaguiar Sorry for the inconveniences

**Comment by catarineaguiar** [comment]
@robertoDiaz no problem :)

**Comment by marcialcv** [comment]
> Hi,
> 
> The objective of this PR is use the values of the properties in the code.
> 
> Right now customers in 7.4 Global services is suggesting customers to set this folders into a different location to prevent problems with their custom bundles but some properties are not been used in the code.

Hi Rober,

we are suggesting it to our customers from GS as a result of these conversations in slack https://liferay.slack.com/archives/CL08WH5V0/p1644538026700949?thread_ts=1644537769.427649&cid=CL08WH5V0

**Pull request closed without merging**
