### PR TITLE
[Spring Beans] LPS-200326 Remove PortletConfigurationIconMenu from util-spring

### PR DESCRIPTION
**Pull request by haydenzheng314**
Ticket: https://liferay.atlassian.net/browse/LPS-200326
Thanks

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@LisztLiszt It seems the change to make the `PortletConfigurationIconMenu` constructor private caused a major version bump. Please add a breaking change report for it.

cc @W2jx I missed the one in your `PortletToolbar` PR. Could you double check the breaking change recording document to see where we can add a follow-up report?

**Comment by LisztLiszt** [comment]
@dantewang Force pushed to add breaking change report.

**Comment by W2jx** [comment]
Hi @dantewang , I have added breaking change in this [pr](https://github.com/liferay-core-infra/liferay-portal/pull/6209)

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/144417

cc @tinatian

**Pull request closed without merging**
