### PR TITLE
LPD-41335 Centralize all language override functionality into LanguageResourcesExtender

### PR DESCRIPTION
**Pull request by kevhlee**
- <https://liferay.atlassian.net/browse/LPD-35718>
- <https://liferay.atlassian.net/browse/LPD-41335>

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
The test failures seem irrelevant. Since this PR has merge conflicts, I'm going to rebase and re-run the tests.

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
The failure is unrelated.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/157324

**Pull request closed without merging**
