### PR TITLE
LPD-21827 Remove resource action by document via ResourceActions API

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:help

**Comment by tinatian** [comment]
ci:report:2558294566

**Comment by tinatian** [comment]
ci:report:2558217099

**Comment by tinatian** [comment]
ci:help

**Comment by tinatian** [comment]
ci:test:object

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:report:2558987539

**Comment by dantewang** [comment]
ci:report:2558990079

**Comment by dantewang** [comment]
No unique failure in upgrade suite. Looking at the one marked as unique in objects suite.

**Comment by dantewang** [comment]
ci:test:object

**Comment by dantewang** [comment]
ci:test:object

**Comment by dantewang** [comment]
ci:report:2559363751

**Comment by dantewang** [comment]
ci:test:object

**Comment by dantewang** [comment]
Also see https://github.com/liferay-core-infra/liferay-portal/pull/6842#issuecomment-2046636654

**Comment by dantewang** [comment]
ci:report:2559430871

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:data-engine

**Comment by dantewang** [comment]
ci:report:2561100230

**Comment by dantewang** [comment]
ci:test:data-engine

**Comment by dantewang** [comment]
@tinatian The previously executed test suites should be clear; but for ci-test-data-engine in https://github.com/liferay-core-infra/liferay-portal/pull/6841#issuecomment-2058515737, I'm not sure whether this failure is really related. From the surface it doesn't seem to be.

**Comment by dantewang** [comment]
ci:test:data-engine

**Comment by dantewang** [comment]
ci:report:2561195079

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/149591

**Pull request closed without merging**
