### PR TITLE
LPS-183421 Use appendListeners instead of setListeners to fix regression

### PR DESCRIPTION
**Pull request by mbowerman**
Use `appendListeners` instead of `setListeners`. Using `setListeners` overwrites the existing listeners, which breaks our fix for [LPS-185647](https://liferay.atlassian.net/browse/LPS-185647).

/cc @shuyangzhou

@ling-alan-huang Do you think we should/could add a new SF rule to enforce using `EventListenerRegistry#appendListeners` instead of `EventListenerRegistry#setListeners` to prevent issues like this from occurring again? I think it is unlikely that we will ever really want to call `EventListenerRegistry#setListeners`.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@mbowerman using setListeners is on purpose. This piece of code is sensitive with who are running next to it. Not to say it can not run with others, but it needs to be aware of it, basically setting all listeners as a whole to prevent weird combination issues that spread across the codebase. We don't want this hibernate level integration become our ModelListener 2nd.

Also I am really doubting the reason why DB partition have to do hibernate level integration. We have been trying the best to restrict on hibernate api integration, only do it at locations which are absolutely needed and only do it in a centralized way.
We have long term plan to move away from hibernate. Allowing wild hibernate api integration across codebase is something we are highly against.

And @achaparro since when DBPartitionUtil started to do this kind of hibernate integration? As far as I could remember, db partition is a jdbc level thing, it should not spread its logic to hibernate. The CompanySynchronizerPreUpdateEventListener logic should really be kept at jdbc level or higher DB partition business logic level, rather than at hibernate level.

And please make sure all future attempts of hibernate integration goes through core. I would catch and stop it on the first sight.

**Comment by shuyangzhou** [comment]
I briefly read https://liferay.atlassian.net/browse/LPS-185647 , even though I am not fully understand the issue yet. The CompanySynchronizerPreUpdateEventListener can not be the right solution. 

@mbowerman @achaparro please schedule a meeting with me. LPS-185647 needs a redo.

**Comment by mbowerman** [comment]
@shuyangzhou We cannot solve it a higher level than Hibernate because the issue is that Hibernate can flush the session at any time, which can occur after we changed the CompanyThreadLocal. We need ensure that we are on the correct CompanyThreadLocal at the time that Hibernate decides to flush the session, so it needs to be solved at the Hibernate level.

Also I do not see why your listener cannot run with other listeners. By using setListener you are making it so that we cannot have any other `PreUpdateEventListener` if we need one (or if a customer wants to use a customization that registers an `PreUpdateEventListener`).

**Comment by shuyangzhou** [comment]
@mbowerman please schedule a meeting with 3 of us. We can talk this through.

**Comment by mbowerman** [comment]
@shuyangzhou @achaparro is on PTO right now and will return on Monday. Since he is in a different time zone, I will wait until he gets back so that I can schedule the meeting at a time that is convenient for him.

**Pull request closed without merging**
