### PR TITLE
LPS-165402 Move BaseBackgroundTaskDisplay to portal-background-task-api

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong 
Semver error
```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/portal-background-task/portal-background-task-api] FAILED
     [exec]     java.lang.AssertionError: [Baseline Warning] Bundle Version Change Recommended: 7.1.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
```
[Logs](https://testray.liferay.com/reports/production/logs/2022-10/test-1-32/test-portal-acceptance-pullrequest(master)/6159/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
corrected semver

**Comment by julschong** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125414

**Pull request closed without merging**
