### PR TITLE
[TS] LPD-1755

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
ci:report:2538586909

**Comment by marianoalvarosaiz** [comment]
@shuyangzhou does this matches what we talked in last meeting?

**Comment by shuyangzhou** [comment]
This is not what we talked in previous meeting. I remember you were saying the cluster replication is doing both the in memory update and db saving causing duplicated db saves. That's the issue. If you were just avoiding the duplicated db saving, then it is fine, but this pull is doing way more than that. Either you resend with only removing the duplicated db saves, or I need more explanation on the additional changes, they do not make sense to me.

**Pull request closed without merging**
