### PR TITLE
[Components with more than 1 service] Refactor Portlet components with more than 1 service type from Staging

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:export-import

**Comment by Kvale1733** [comment]
@GabrielHenriquedev No regressions found.

**Comment by GabrielHenriquedev** [comment]
@tinatian this one is ready to go.

**Comment by rafaprax** [comment]
Looks good to me.
 
/cc @tinatian

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
