### PR TITLE
[Components with more than 1 service] LPS-179094 Refactor ScreenNavigationCategory components from Objects modules

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-179094](https://issues.liferay.com/browse/LPS-179094)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:object

**Comment by catarineaguiar** [comment]
@RenanUmV no regressions found. Only a semver failure:

```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/object/object-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.object.exception                       MINOR      16.2.0     16.2.0     16.3.0     VERSION INCREASE REQUIRED
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-04/test-1-30/test-portal-acceptance-pullrequest(master)/6181/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by RenanUmV** [comment]
The semantic version error was happening in the master

**Comment by dantewang** [comment]
Java code conflict, please rebase and resend, thanks!

**Pull request closed without merging**
