### PR TITLE
[Replace Non-Blocking Usage] LPS-198502 Replace non-blocking ServiceProxyFactory usages in classes PermissionCheckerFactoryUtil, ServiceAccessPolicyManagerUtil and TunnelAuthenticationManagerUtil

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5809

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(10/24 8:21)

**Comment by W2jx** [comment]
forced push to resolve the conflict about bnd file, no logic changes, no need to rerun test

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
@W2jx I'm not sure what is this error:

```
Unable to rebase master-temp-1698170351424 to master
Rebasing (1/5)
Rebasing (2/5)
error: could not apply a9bc1d2ba030... LPS-198502 Replace ServiceProxyFactory with Spring in class TunnelAuthenticationManagerUtil, as TunnelAuthenticationManagerImpl is a spring bean
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply a9bc1d2ba030... LPS-198502 Replace ServiceProxyFactory with Spring in class TunnelAuthenticationManagerUtil, as TunnelAuthenticationManagerImpl is a spring bean
```

**Comment by Kvale1733** [comment]
@catarineaguiar The suite can't rebase due to the conflict. But we already have upgrade results we can just check those.

**Comment by Kvale1733** [comment]
@W2jx Can you rebase and rerun the upgrade suite? An issue was fixed recently that should get us more accurate results.

**Comment by W2jx** [comment]
Hi @Kvale1733 , I have rebased.

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
let's run only upgrade test suite

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
see https://github.com/liferay-core-infra/liferay-portal/pull/5908

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
no conflicts(10/27 8:50)

**Pull request closed without merging**
