### PR TITLE
LPD-24836 Move JSONWebServices classes from kernel to modules

### PR DESCRIPTION
**Pull request by julschong**
@tinatian This is resubmitted from https://github.com/liferay-core-infra/liferay-portal/pull/6942
I separated the [Util class moving commit](https://github.com/liferay-core-infra/liferay-portal/pull/6957/commits/4af966bf330a2895beb26b1f7f6dcb77e85e5270)    and   [remove unused method commit](https://github.com/liferay-core-infra/liferay-portal/pull/6957/commits/33e4e1151192867b837fc03b51ea63d8b9f45666)
Addressing this comment: https://github.com/liferay-core-infra/liferay-portal/pull/6942#discussion_r1591430560

I also added additional Util test usage cleanup: [e671d87](https://github.com/liferay-core-infra/liferay-portal/pull/6957/commits/e671d8763b12e95f8b224a16dab7dd03b2178691) and [306010a](https://github.com/liferay-core-infra/liferay-portal/pull/6957/commits/306010a72724e9601b71b5e24635a44c865322af)

Also removed the annotation dependency mentioned here: https://github.com/liferay-core-infra/liferay-portal/pull/6942#discussion_r1591429627

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:core-functional

**Comment by julschong** [comment]
ci:report:2567048045

**Comment by julschong** [comment]
rerun core-functional due to unique failure

**Comment by julschong** [comment]
ci:test:core-functional

**Comment by julschong** [comment]
ci:report:2567059829

**Comment by julschong** [comment]
relevant unique failure is not related

**Comment by julschong** [comment]
ci:report:2567079495

**Comment by julschong** [comment]
no unique failure on core-functional

**Comment by julschong** [comment]
ready for review

**Comment by tinatian** [comment]
ci:test:help

**Comment by julschong** [comment]
ci:test:echo

**Comment by julschong** [comment]
ci:test:content-management

**Comment by julschong** [comment]
ci:report:2569241685

**Comment by julschong** [comment]
some unique failures, unsure if they are caused by my pull. retest

**Comment by julschong** [comment]
ci:test:content-management

**Comment by julschong** [comment]
ci:test:echo

**Comment by julschong** [comment]
ci:report:2569657887

**Comment by julschong** [comment]
ci:report:2569709280

**Comment by julschong** [comment]
unique failures are not related

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/150468

**Pull request closed without merging**
