### PR TITLE
LPS-195966 Merge OrganizationPermission interface and impl into Util in kernel

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
rebase and re test

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found. SF issue is not related

**Comment by julschong** [comment]
renamed variable back to original in TemplateContextHelper

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
rebased

**Comment by julschong** [comment]
@shuyangzhou not moving this one to portal-impl

Following build.gradles do not contain portal-impl dependencies: 
        ./modules/dxp/apps/commerce/commerce-organization-web/build.gradle

Used in portal-kernel

**Comment by julschong** [comment]
ci:test:sf

**Pull request closed without merging**
