### PR TITLE
[TS] LPS-147370 - 2

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team,

/cc @tinatian

**Previous PR:** https://github.com/liferay-core-infra/liferay-portal/pull/398

Re-sending PR with the suggested changes.

Please let me know if you have any questions.
Thanks!

----

**Notes**
This PR is to patch the bnd library to account for the use-case, where an OSGI configuration has a value: empty string, with a return type: array

    Before patch: "" returns [""]
    After patch: "" returns []

Additional Notes
After this is fixed on the bnd side, we will proceed with matching this behavior in the System Settings UI ([LPS-145833](https://issues.liferay.com/browse/LPS-145833))

As for the version enforcement, I made these changes based on past commits and existing entries in source-formatter.properties.

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114222

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
