### PR TITLE
[Components with more than 1 service] LPS-177044 Refactor CommerceQualifierMetadata classes with more than one service type

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-177044

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by rafaprax** [comment]
Hey @tinatian, it is ready for your review. Thx

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
I just did some SF changes in the first commit. The test analysis is still valid. Thx

**Comment by tinatian** [comment]
@rafaprax Why CommerceQualifierMetadataModelListener need to be registered per CommerceQualifierMetadata instance? I believe one is enough.

Please resend.

Thanks.
Tina

**Comment by rafaprax** [comment]
Hey @tinatian, reopening this one according to what we talked about in the call. Thx

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132064

**Pull request closed without merging**
