### PR TITLE
[Rename Classes] LPS-166958 Rename classes in modules fragment-api、fragment-impl、fragment-collection-filter-api、fragment-collection-filter-impl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by zhangyan0701** [comment]
Semantic Versioning error:
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/fragment/fragment-collection-filter-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.fragment.collection.filter             MAJOR      1.3.0      1.2.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	+   interface  com.liferay.fragment.collection.filter.FragmentCollectionFilterRegistry
     [exec]     		+   access     abstract
     [exec]     		+   method     getFragmentCollectionFilter(java.lang.String)
     [exec]     			+   access     abstract
     [exec]     			+   return     com.liferay.fragment.collection.filter.FragmentCollectionFilter
     [exec]     		+   method     getFragmentCollectionFilters()
     [exec]     			+   access     abstract
     [exec]     			+   return     java.util.List
     [exec]     		+   annotated  aQute.bnd.annotation.ProviderType
     [exec]     	-   interface  com.liferay.fragment.collection.filter.FragmentCollectionFilterTracker
     [exec]     		-   access     abstract
     [exec]     		-   method     getFragmentCollectionFilter(java.lang.String)
     [exec]     			-   access     abstract
     [exec]     			-   return     com.liferay.fragment.collection.filter.FragmentCollectionFilter
     [exec]     		-   method     getFragmentCollectionFilters()
     [exec]     			-   access     abstract
     [exec]     			-   return     java.util.List
     [exec]     		-   annotated  aQute.bnd.annotation.ProviderType
     [exec]     	-   version    1.2.0
     [exec]     	+   version    1.3.0
```

Other failures are unrelated.

**Comment by W2jx** [comment]
Force-Push is just to fix the Semantic Versioning error.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
@W2jx 

Semver error:
```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/fragment/fragment-collection-filter-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.fragment.collection.filter             MAJOR      1.3.0      1.2.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	+   interface  com.liferay.fragment.collection.filter.FragmentCollectionFilterRegistry
     [exec]     		+   access     abstract
     [exec]     		+   method     getFragmentCollectionFilter(java.lang.String)
     [exec]     			+   access     abstract
     [exec]     			+   return     com.liferay.fragment.collection.filter.FragmentCollectionFilter
     [exec]     		+   method     getFragmentCollectionFilters()
     [exec]     			+   access     abstract
     [exec]     			+   return     java.util.List
     [exec]     		+   annotated  aQute.bnd.annotation.ProviderType
     [exec]     	-   interface  com.liferay.fragment.collection.filter.FragmentCollectionFilterTracker
     [exec]     		-   access     abstract
     [exec]     		-   method     getFragmentCollectionFilter(java.lang.String)
     [exec]     			-   access     abstract
     [exec]     			-   return     com.liferay.fragment.collection.filter.FragmentCollectionFilter
     [exec]     		-   method     getFragmentCollectionFilters()
     [exec]     			-   access     abstract
     [exec]     			-   return     java.util.List
     [exec]     		-   annotated  aQute.bnd.annotation.ProviderType
     [exec]     	-   version    1.2.0
     [exec]     	+   version    1.3.0
```
[Log](https://testray.liferay.com/reports/production/logs/2022-11/test-1-39/test-portal-acceptance-pullrequest(master)/1445/modules-semantic-versioning-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

No regressions found in all other tests.

**Pull request closed without merging**
