### PR TITLE
[Remove Stream/Optional usage] LPS-178143 portal-workflow-kaleo-service

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-178143

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
@JanisZhang Regression found in

com.liferay.portal.workflow.metrics.service.internal.search.index.test.TaskWorkflowMetricsIndexerTest
```
[exec] com.liferay.portal.workflow.metrics.service.internal.search.index.test.TaskWorkflowMetricsIndexerTest > testAddTask FAILED
     [exec]     java.lang.RuntimeException: java.lang.NullPointerException
     [exec]     	at com.liferay.petra.function.transform.TransformUtil.transformToArray(TransformUtil.java:60)
     [exec]     	at com.liferay.portal.workflow.kaleo.internal.search.spi.model.index.contributor.KaleoInstanceModelDocumentContributor.contribute(KaleoInstanceModelDocumentContributor.java:61)
     [exec]     	at com.liferay.portal.workflow.kaleo.internal.search.spi.model.index.contributor.KaleoInstanceModelDocumentContributor.contribute(KaleoInstanceModelDocumentContributor.java:36)
     [exec]     	at com.liferay.portal.search.internal.indexer.IndexerDocumentBuilderImpl.lambda$getDocument$1(IndexerDocumentBuilderImpl.java:63)
     [exec]     	at com.liferay.osgi.service.tracker.collections.internal.list.ServiceTrackerListImpl.lambda$forEach$0(ServiceTrackerListImpl.java:82)
     [exec]     	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
     [exec]     	at com.liferay.osgi.service.tracker.collections.internal.list.ServiceTrackerListImpl.forEach(ServiceTrackerListImpl.java:81)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-03/test-1-40/test-portal-acceptance-pullrequest(master)/508/modules-integration-mysql57-jdk8/0/5/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
