### PR TITLE
[Remove Blocking usages]Lps 188914

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-188914

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:auto-tagging

**Comment by dantewang** [comment]
@slnn It looks basically OK to me, but please reduce the number of your commits. You can just replace the util usages in OSGi components and integration tests all together first, remove unused methods then, and clean up `FileUtil/File/FileImpl`.

**Review by dantewang — CHANGES_REQUESTED** [review]
As commented.

**Comment by dantewang** [comment]
@slnn The removal of `Document` methods seems to be dangerous. Since it's a search framework class, I guess some customers may be using it. Could you confirm with the search team?

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Comment by dantewang** [comment]
@slnn Please see my comment and resend.

**Comment by slnn** [comment]
Resend in https://github.com/liferay-core-infra/liferay-portal/pull/4915

**Comment by slnn** [comment]
Resend in https://github.com/liferay-core-infra/liferay-portal/pull/4915

**Pull request closed without merging**
