### PR TITLE
[Method References 2] LPS-167592 Convert method reference to ServiceTrackerMap in module portal-workflow-kaleo-runtime-impl |part 2

### PR DESCRIPTION
**Pull request by W2jx**
Hi @dantewang , this pr is what we talked about in the afternoon.

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by W2jx** [comment]
Hi @dantewang , I think the errors in class KaleoInstancePersistenceTest are because I use internal class `NodeExecutorFactory` in  `TaskNodeExecutorTest.java` of module `portal-workflow-kaleo-test` (in order to get  `TaskNodeExecutor`), I found that `TaskNodeExecutorTest` is for testing class `TaskNodeExecutor`, So can I move this test class `TaskNodeExecutorTest`  into the module where `TaskNodeExecutor` is? Or can I add an interface to module `portal-workflow-kaleo-runtime-api` for `NodeExecutorFactory`?

**Comment by dantewang** [comment]
@W2jx If it's an integration test, it should stay in a separate module so you shouldn't move it. If it's a unit test, maybe you can move it. I'll take look later, I think there should be other way to resolve this.

**Comment by dantewang** [comment]
@W2jx 
1. Please send rename PRs first, when the renaming ones are merged, resend these. I think the `NodeExecutorFactory` should also be renamed, to `NodeExecutorRegistry`.
2. If there's component property `node.type`, you can just `@Inject` with a filter; now you replace this property with a getter method, then you can track `NodeExecutor` and find the the service whose `getNodeType() == NodeType.TASK`. So, no need to use `NodeExecutorFactory`.

**Pull request closed without merging**
