### PR TITLE
[Optional Reference] LPS-185138 Convert the Optional Dynamic Greedy references to static references using Snapshot in class UpgradeRecorder

### PR DESCRIPTION
**Pull request by haydenzheng314**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4581
Ticket: https://liferay.atlassian.net/browse/LPS-185138

@dantewang 
After using snapshot for `ReleaseManager`, there is no reference to `ReleaseManagerImpl`, it will be called when getting snapshot which is not on time. The `avtivate()` method of  the reference `ReleasePublisher` won't be executed so the service `Release` is not registered.

Then the `serviceDependency` in `ServiceConfigurationExtender` can't set service `Release` and added to the created component. Also this component has a implementation `ServiceConfigurationInitializer`, it can't register service `Configuration` and causes chaining:
`CTEntryPersistenceImpl` gets a null `Configuration`.
`CTEntryLocalServiceImpl` gets a null reference of `CTCollectionPersistence`.
`CTStoreFactoryImpl` gets a null reference of `CTEntryLocalService`.
Finally `CTStoreRegistrator` gets a null reference of `CTStoreFactory` and causes "missing default store" in `DBUpgrader`.

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
@LisztLiszt It seems you are using a dynamic snapshot, so at the time you get this service, it will start. But this service needs to start earlier than that?

**Comment by LisztLiszt** [comment]
> @LisztLiszt It seems you are using a dynamic snapshot, so at the time you get this service, it will start. But this service needs to start earlier than that?

Yes. Because `ReleasePublisher` need to register `Release` before getting `ReleaseManager`

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
@LisztLiszt Then why making it a hard reference doesn't work either?

**Comment by LisztLiszt** [comment]
> @LisztLiszt Then why making it a hard reference doesn't work either?

Hard reference also works, no missing store and schema version errors.

**Comment by dantewang** [comment]
@LisztLiszt There was CI failure with the previous PR you sent which changes it to hard reference. Let's double check, if hard reference works, let's use it then.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5042

**Pull request closed without merging**
