### PR TITLE
LPS-171926 Remove Stream and Optional usages in portal-vulcan-api

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from https://github.com/liferay-core-infra/liferay-portal/pull/2882
@dantewang
2 Optional usages in DefaultDTOConverterContext and DTOConverterContext in portal-vulcan-api are related to UriInfo and not changed

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@julschong regressions found:

```
    [exec] com.liferay.portal.vulcan.internal.batch.engine.test.VulcanBatchEngineTaskItemDelegateRegistryTest > testRegistryAndOpenAPIUtilToGetEntityMetadata FAILED
     [exec]     java.lang.NullPointerException
     [exec]     	at com.liferay.portal.vulcan.util.OpenAPIUtil._hasOKResponseContentSchemaReferenceLike(OpenAPIUtil.java:187)
     [exec]     	at com.liferay.portal.vulcan.util.OpenAPIUtil.getCreateEntityScopes(OpenAPIUtil.java:54)
     [exec]     	at com.liferay.portal.vulcan.internal.batch.engine.test.VulcanBatchEngineTaskItemDelegateRegistryTest.testRegistryAndOpenAPIUtilToGetEntityMetadata(VulcanBatchEngineTaskItemDelegateRegistryTest.java:206)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-25/test-portal-acceptance-pullrequest(master)/5879/modules-integration-mysql57-jdk8/0/4/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.headless.delivery.resource.v1_0.test.BlogPostingImageResourceTest > testPostSiteBlogPostingImage FAILED
     [exec]     org.junit.ComparisonFailure: expected:<[���!�����]> but was:<[<!DOCTYPE html> <html class="ltr" dir="ltr" lang="en-US"> <head> <title>Search - Liferay DXP</title> <meta content="initial-scale=1.0, width=device-width" name="viewport" /> <meta content="text/html; charset=UTF-8" http-equiv="content-type" /> <meta content="Display search results with a default set of facets." lang="en-US" name="description" /> <script type="importmap">{"imports":{"react-dom":"/o/frontend-js-react-web/__liferay__/exports/react-dom.js","prop-types":"/o/frontend-js-react-web/__liferay__/exports/prop-types.js","react-dnd":"/o/frontend-js-react-web/__liferay__/exports/react-dnd.js","formik":"/o/frontend-js-react-web/__liferay__/exports/formik.js","react":"/o/frontend-js-react-web/__liferay__/exports/react.js","react-dnd-html5-backend":"/o/frontend-js-react-web/__liferay__/exports/react-dnd-html5-backend.js","classnames":"/o/frontend-js-react-web/__liferay__/exports/classnames.js"},"scopes":{}}</script><script data-senna-track="temporary">var Liferay = window.Liferay || {};Liferay.Icons = Liferay.Icons || {};Liferay.Icons.spritemap = 'http://localhost:8080/o/classic-theme/images/clay/icons.svg';</script> <link data-senna-track="temporary" href="http://localhost:8080/web/guest/search" rel="canonical" /> <link data-senna-track="temporary" href="http://localhost:8080/zh/web/guest/search" hreflang="zh-CN" rel="alternate" /> <link data-senna-track="temporary" href="http://localhost:8080/es/web/guest/search" hreflang="es-ES" rel="alternate" /> <link data-senna-track="temporary" href="http://localhost:8080/sv/web/guest/search" hreflang="sv-SE" rel="alternate" /> <link data-senna-track="temporary" href="http://localhost:8080/ja/web/guest/search" hreflang="ja-JP" rel="alternate" /> <link data-senna-track="temporary" href="http://localhost:8080/nl/web/guest/search" hreflang="nl-NL" rel="alternate" /> <link data-senna-track="temporary" href="http://localhost:8080/hu/web/guest/search" hreflang="hu-HU" rel="alternate" /> <link data-senna-track="temporary" href="http://localhost:8080/ar/web/guest/search" hreflang="ar-SA" rel="alternate" /> <link data-senna-track="temporary" href="http://localhost:8080/pt/web/guest/search" hreflang="pt-BR" rel="alternate" /> <link data-senna-track="temporary" href="http://localhost:8080/de/web/guest/search" hreflang="de-DE" rel="alternate" /> <link data-senna-track="temporary" href="http://localhost:8080/ca/web/guest/search" hreflang="ca-ES" rel="alternate" /> <link data-senna-track="temporary" href="http://localhost:8080/fi/web/guest/search" hreflang="fi-FI" rel="alternate" /> <link data-senna-track="temporary" href="http://localhost:8080/fr/web/guest/search" hreflang="fr-FR" rel="alternate" /> <link data-senna-track="temporary" href="http://localhost:8080/web/guest/search" hreflang="en-US" rel="alternate" /> <link data-senna-track="temporary" href="http://localhost:8080/web/guest/search" hreflang="x-default" rel="alternate" /> <meta property="og:description" content="Display search results with a default set of facets."> <meta property="og:locale" content="en_US"> <meta property="og:locale:alternate" content="en_US"> <meta property="og:locale:alternate" content="ar_SA"> <meta property="og:locale:alternate" content="ca_ES"> <meta property="og:locale:alternate" content="zh_CN"> <meta property="og:locale:alternate" content="nl_NL"> <meta property="og:locale:alternate" content="fi_FI"> <meta property="og:locale:alternate" content="fr_FR"> <meta property="og:locale:alternate" content="de_DE"> <meta property="og:locale:alternate" content="hu_HU"> <meta property="og:locale:alternate" content="ja_JP"> <meta property="og:locale:alternate" content="pt_BR"> <meta property="og:locale:alternate" content="es_ES"> <meta property="og:locale:alternate" content="sv_SE"> <meta property="og:site_name" content="Liferay DXP"> <meta property="og:title" content="Search - Liferay DXP"> <meta property="og:type" content="website"> <meta property="og:url" content="http://localhost:8080/web/guest/search"> <link href="http://localhost:8080/o/classic-theme/images/favicon.ico" rel="icon" /> <link class="lfr-css-file" data-senna-track="temporary" href="http://localhost:8080/o/classic-theme/css/clay.css?browserId=other&amp;themeId=classic_WAR_classictheme&amp;minifierType=css&amp;languageId=en_US&amp;t=1672865124000" id="liferayAUICSS" rel="stylesheet" type="text/css" /> <link href="/combo?browserId=other&amp;minifierType=css&amp;themeId=classic_WAR_classictheme&amp;languageId=en_US&amp;com_liferay_portal_search_web_category_facet_portlet_CategoryFacetPortlet_INSTANCE_eCVFO0DSzrWr:%2Fo%2Fportal-search-web%2Fcss%2Fmain.css&amp;com_liferay_product_navigation_user_personal_bar_web_portlet_ProductNavigationUserPersonalBarPortlet:%2Fo%2Fcom.liferay.product.navigation.user.personal.bar.web%2Fcss%2Fmain.css&amp;t=1672865124000" rel="stylesheet" type="text/css" data-senna-track="temporary" id="1378c21b" /> <script data-senna-track="temporary" type="text/javascript">
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-25/test-portal-acceptance-pullrequest(master)/5879/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.portal.vulcan.util.OpenAPIUtilTest > testGetReadEntityScopes FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.portal.vulcan.util.OpenAPIUtil._hasOKResponseContentSchemaReferenceLike(OpenAPIUtil.java:191)
     [exec]         at com.liferay.portal.vulcan.util.OpenAPIUtil.getReadEntityScopes(OpenAPIUtil.java:114)
     [exec]         at com.liferay.portal.vulcan.util.OpenAPIUtilTest.testGetReadEntityScopes(OpenAPIUtilTest.java:262)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-25/test-portal-acceptance-pullrequest(master)/5879/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

semver error:
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/portal-vulcan/portal-vulcan-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.portal.vulcan.multipart                MAJOR      1.0.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.portal.vulcan.multipart.MultipartBody
     [exec]     		-   method     getValueAsInstanceOptional(java.lang.String,java.lang.Class)
     [exec]     			-   return     java.util.Optional
     [exec]     		+   method     getValueAsNullableInstance(java.lang.String,java.lang.Class)
     [exec]     			+   return     java.lang.Object
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 27.0.0
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-25/test-portal-acceptance-pullrequest(master)/5879/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
pushed to fix regression

regressions were mainly caused by my mistake in changing `Optional... orElse()`
fallbacks were not correctly put in.

**Comment by zhangyan0701** [comment]
There are some startup errors:
```
[beanshell] 2023-01-05 04:20:34.129 INFO  [Portal Dependency Manager Component Executor--1][BundleSiteInitializer:398] Initializing com.liferay.site.initializer.welcome for group 20121
[beanshell] 2023-01-05 04:20:34.133 INFO  [Portal Dependency Manager Component Executor--1][BundleSiteInitializer:4240] Invoking line 424 took 1 ms
[beanshell] 2023-01-05 04:20:34.135 INFO  [Portal Dependency Manager Component Executor--1][BundleSiteInitializer:4259] Invoking line 427 in 1 ms
[beanshell] 2023-01-05 04:20:34.136 INFO  [Portal Dependency Manager Component Executor--1][BundleSiteInitializer:4240] Invoking line 429 took 0 ms
[beanshell] 2023-01-05 04:20:34.136 INFO  [Portal Dependency Manager Component Executor--1][BundleSiteInitializer:4259] Invoking line 432 in 0 ms
[beanshell] 2023-01-05 04:20:34.472 ERROR [Portal Dependency Manager Component Executor--1][BundleSiteInitializer:546] null
[beanshell] java.lang.NullPointerException: null
... ...
[beanshell] 2023-01-05 04:20:34.529 WARN  [Portal Dependency Manager Component Executor--1][PortalInstanceLifecycleListenerManagerImpl:231] Unable to register portal instance {"mvccVersion": 1, "companyId": 20097, "userId": 0, "userName": "", "createDate": "Thu Jan 05 04:19:48 GMT 2023", "modifiedDate": "Thu Jan 05 04:19:48 GMT 2023", "webId": "liferay.com", "mx": "liferay.com", "homeURL": "", "logoId": 0, "maxUsers": 0, "active": true, "name": "Liferay", "legalName": "", "legalId": "", "legalType": "", "sicCode": "", "tickerSymbol": "", "industry": "", "type": "", "size": ""}
[beanshell] com.liferay.site.exception.InitializationException: java.lang.NullPointerException
```
Add the same errors occur when add virtual instance with headless api, such as command:
`curl -X POST -u 'test@liferay.com:test' -d '{"domain" : "liferay.com", "virtualHost": "test-1-37-60.lax.liferay.com", "portalInstanceId": "test-1-37-60.lax.liferay.com"}' -H 'Content-Type: application/json' http://localhost:8080/o/headless-portal-instances/v1.0/portal-instances`

Full jenkins console:
https://testray.liferay.com/reports/production/logs/2023-01/test-1-38/test-portal-acceptance-pullrequest(master)/5555/functional-smoke-tomcat90-mysql57-jdk8_stable/0/0/jenkins-console.txt.gz?authuser=0

**Comment by julschong** [comment]
> There are some startup errors:
> 
> ```
> [beanshell] 2023-01-05 04:20:34.129 INFO  [Portal Dependency Manager Component Executor--1][BundleSiteInitializer:398] Initializing com.liferay.site.initializer.welcome for group 20121
> [beanshell] 2023-01-05 04:20:34.133 INFO  [Portal Dependency Manager Component Executor--1][BundleSiteInitializer:4240] Invoking line 424 took 1 ms
> [beanshell] 2023-01-05 04:20:34.135 INFO  [Portal Dependency Manager Component Executor--1][BundleSiteInitializer:4259] Invoking line 427 in 1 ms
> [beanshell] 2023-01-05 04:20:34.136 INFO  [Portal Dependency Manager Component Executor--1][BundleSiteInitializer:4240] Invoking line 429 took 0 ms
> [beanshell] 2023-01-05 04:20:34.136 INFO  [Portal Dependency Manager Component Executor--1][BundleSiteInitializer:4259] Invoking line 432 in 0 ms
> [beanshell] 2023-01-05 04:20:34.472 ERROR [Portal Dependency Manager Component Executor--1][BundleSiteInitializer:546] null
> [beanshell] java.lang.NullPointerException: null
> ... ...
> [beanshell] 2023-01-05 04:20:34.529 WARN  [Portal Dependency Manager Component Executor--1][PortalInstanceLifecycleListenerManagerImpl:231] Unable to register portal instance {"mvccVersion": 1, "companyId": 20097, "userId": 0, "userName": "", "createDate": "Thu Jan 05 04:19:48 GMT 2023", "modifiedDate": "Thu Jan 05 04:19:48 GMT 2023", "webId": "liferay.com", "mx": "liferay.com", "homeURL": "", "logoId": 0, "maxUsers": 0, "active": true, "name": "Liferay", "legalName": "", "legalId": "", "legalType": "", "sicCode": "", "tickerSymbol": "", "industry": "", "type": "", "size": ""}
> [beanshell] com.liferay.site.exception.InitializationException: java.lang.NullPointerException
> ```
> 
> Add the same errors occur when add virtual instance with headless api, such as command: `curl -X POST -u 'test@liferay.com:test' -d '{"domain" : "liferay.com", "virtualHost": "test-1-37-60.lax.liferay.com", "portalInstanceId": "test-1-37-60.lax.liferay.com"}' -H 'Content-Type: application/json' http://localhost:8080/o/headless-portal-instances/v1.0/portal-instances`
> 
> Full jenkins console: https://testray.liferay.com/reports/production/logs/2023-01/test-1-38/test-portal-acceptance-pullrequest(master)/5555/functional-smoke-tomcat90-mysql57-jdk8_stable/0/0/jenkins-console.txt.gz?authuser=0

pushed to fix this by adding additional null checking

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong Regression found

Steps to reproduce:
       1. Go to Control Panel > Asset Libraries
       2. Add a new Asset Library named "Test Depot Name"
       3. Save the Asset Library ID (will be used in later steps)
       4. Add a document with custom erc in the asset library with the following curl. Run it in /portal-web
       ```
       curl -X POST -u 'test@liferay.com:test' -H 'Content-Type: multipart/form-data' -F 'document={"externalReferenceCode": "erc"}' -F 'file=@test/functional/com/liferay/portalweb/dependencies/Document_1.txt' http://localhost:8080/o/headless-delivery/v1.0/asset-libraries/${assetLibraryIDHere}/documents
        ```
        5. Update the document title by erc using the following curl
        ```
        curl -X PUT -u 'test@liferay.com:test' -F 'document={"title": "updated title"}' http://localhost:8080/o/headless-delivery/v1.0/asset-libraries/${assetLibraryIDHere}/documents/by-external-reference-code/erc
         ```
         
 Expected results: The curl executes without issue and the document title is updated to "updated title" This can be verified by going to Control Panel > Asset Libraries. Click on Test Depot Name entry. Then click on Documents and Media. You can view the document entry here.
 
 Actual results. The curl fails to execute and returns
 ```
 {
  "status" : "INTERNAL_SERVER_ERROR",
  "title" : "Internal Server Error"
}
```

**Comment by julschong** [comment]
> curl -X PUT -u 'test@liferay.com:test' -F 'document={"title": "updated title"}' http://localhost:8080/o/headless-delivery/v1.0/asset-libraries/${assetLibraryIDHere}/documents/by-external-reference-code/erc

pushed to resolve this issue, use !Objects.equal() instead of != null

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong should we remove qa-failed label?

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:headless

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128743

**Pull request closed without merging**
