### PR TITLE
[commons-lang] LPD-20264 Remove commons-lang StringUtils usages

### PR DESCRIPTION
**Pull request by julschong**
@tinatian per our discussion, this pull is not urgently needed since we can add commons-lang to shared-dependencies

### CODE REVIEW

**Comment by julschong** [comment]
fix sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:report:2554704427

**Comment by tinatian** [comment]
Close, please resend if needed

**Pull request closed without merging**
