### PR TITLE
[Bug fix] LPS-161435

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:smoke

**Comment by Kvale1733** [comment]
@dantewang @catarineaguiar Catarine has returned so you can start pinging her again. I've assigned her.

**Comment by catarineaguiar** [comment]
ci:help

**Comment by catarineaguiar** [comment]
ci:test:usm

**Comment by catarineaguiar** [comment]
Hi @dantewang, the bug is still happening when I follow the bug steps
```
2022-09-15 14:15:44.862 WARN  [main][PortalInstanceLifecycleListenerManagerImpl:231] Unable to register portal instance {"mvccVersion": 1, "companyId": 20097, "userId": 0, "userName": "", "createDate": "Thu Sep 15 14:14:45 GMT 2022", "modifiedDate": "Thu Sep 15 14:14:45 GMT 2022", "webId": "liferay.com", "mx": "liferay.com", "homeURL": "", "logoId": 0, "maxUsers": 0, "active": true, "name": "Liferay", "legalName": "", "legalId": "", "legalType": "", "sicCode": "", "tickerSymbol": "", "industry": "", "type": "", "size": ""}
com.liferay.portal.kernel.repository.UndeployedExternalRepositoryException: Unable to load external repository class com.liferay.portal.repository.liferayrepository.LiferayRepository because its plugin is not deployed
	at com.liferay.portal.repository.RepositoryFactoryImpl.getRepositoryFactory(RepositoryFactoryImpl.java:72) ~[portal-impl.jar:?]
	at com.liferay.portal.repository.RepositoryFactoryImpl.createLocalRepository(RepositoryFactoryImpl.java:39) ~[portal-impl.jar:?]
	at com.liferay.portal.repository.RepositoryProviderImpl.getLocalRepository(RepositoryProviderImpl.java:268) ~[portal-impl.jar:?]
	at com.liferay.portlet.documentlibrary.service.impl.DLAppLocalServiceImpl.getLocalRepository(DLAppLocalServiceImpl.java:1490) ~[portal-impl.jar:?]
	at com.liferay.portlet.documentlibrary.service.impl.DLAppLocalServiceImpl.fetchFileEntryByExternalReferenceCode(DLAppLocalServiceImpl.java:572) ~[portal-impl.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:66) ~[portal-kernel.jar:?]
	at com.sun.proxy.$Proxy890.fetchFileEntryByExternalReferenceCode(Unknown Source) ~[?:?]
	at com.liferay.document.library.kernel.service.DLAppLocalServiceWrapper.fetchFileEntryByExternalReferenceCode(DLAppLocalServiceWrapper.java:425) ~[portal-kernel.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:66) ~[portal-kernel.jar:?]
	at com.sun.proxy.$Proxy891.fetchFileEntryByExternalReferenceCode(Unknown Source) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
	at com.sun.proxy.$Proxy178.fetchFileEntryByExternalReferenceCode(Unknown Source) ~[?:?]
	at com.liferay.commerce.product.internal.model.listener.PortalInstanceLifecycleListenerImpl.portalInstanceRegistered(PortalInstanceLifecycleListenerImpl.java:91) ~[?:?]
	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl.registerCompany(PortalInstanceLifecycleListenerManagerImpl.java:227) ~[?:?]
	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl.lambda$null$1(PortalInstanceLifecycleListenerManagerImpl.java:137) ~[?:?]
	at com.liferay.portal.spring.transaction.BaseTransactionExecutor.execute(BaseTransactionExecutor.java:37) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInvokerImpl.invoke(TransactionInvokerImpl.java:39) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.transaction.TransactionInvokerUtil.invoke(TransactionInvokerUtil.java:28) ~[portal-kernel.jar:?]
	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl.lambda$addPortalInstanceLifecycleListener$2(PortalInstanceLifecycleListenerManagerImpl.java:131) ~[?:?]
	at com.liferay.portal.service.impl.CompanyLocalServiceImpl.forEachCompany(CompanyLocalServiceImpl.java:506) ~[portal-impl.jar:?]
	at sun.reflect.GeneratedMethodAccessor185.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
	at com.sun.proxy.$Proxy90.forEachCompany(Unknown Source) ~[?:?]
	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl.addPortalInstanceLifecycleListener(PortalInstanceLifecycleListenerManagerImpl.java:128) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor174.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
```

**Comment by dantewang** [comment]
@catarineaguiar This fix is aimed at the error message reported in LPS-161435, so it's irrelevant with the "repository" issue in startup. I think we should already have a ticket for the "repository" error?

**Comment by catarineaguiar** [comment]
@dantewang Yes, this [ticket](https://issues.liferay.com/browse/LRQA-73331) was created to fix this issue, but they related this error to [LPS-161435](https://issues.liferay.com/browse/LRQA-73331?focusedCommentId=2754351&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2754351)

**Comment by dantewang** [comment]
@catarineaguiar Thanks, I'll double check. But from the error message they shouldn't be related...

**Comment by dantewang** [comment]
@catarineaguiar @tinatian I added a comment to the LRQA ticket. The `LiferayRepository` issue is irrelevant with LPS-161435. It's actually due to https://issues.liferay.com/browse/COMMERCE-9502 not being fully fixed. There is a fix PR on liferay-commerce's git repo: https://github.com/liferay-commerce/liferay-portal/pull/3017.

**Comment by catarineaguiar** [comment]
@dantewang thanks for checking. The results are ok.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
@dantewang add a new version of SearchUtil.search() which takes in the Indexer from caller to do the search. This way we won't add an unused reference. We are trying to wipe out unused reference system wide.

**Pull request closed without merging**
