### PR TITLE
LPD-18019 Update ProGuard: git-commit

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:license

**Comment by dantewang** [comment]
@tinatian @vicnate5 @brunofalc 

It seems ProGuard can be directly updated. Since all branches are using the same ProGuard jar, can we get someone from release to verify?

https://github.com/dantewang/liferay-portal-ee/pull/132
https://github.com/dantewang/liferay-portal-ee/pull/133

I also triggered CI for 7.3 and 7.2. The 7.2 license test passed, while the 7.3 one failed on javac (which should be before invoking ProGuard).

**Comment by dantewang** [comment]
ci:report:2540523235

**Comment by vicnate5** [comment]
all the license tests actually passed here. The failure is on the CI side.

**Comment by dantewang** [comment]
ci:test:license


Re-trigger because the release-tool-ee PR is updated.

**Comment by dantewang** [comment]
Closing this one since it's just for running CI.

**Pull request closed without merging**
