### PR TITLE
Lps 143575 2

### PR DESCRIPTION
**Pull request by amosfong**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
ci:test:commerce

**Comment by vicnate5** [comment]
@amosfong Some integration test failures here:
[com.liferay.headless.commerce.admin.shipment.resource.v1_0.test.ShippingAddressResourceTest](https://testray.liferay.com/home/-/testray/case_results/1855053706)
```
     [exec] com.liferay.headless.commerce.admin.shipment.resource.v1_0.test.ShippingAddressResourceTest > testGraphQLGetShipmentByExternalReferenceCodeShippingAddress FAILED
     [exec]     java.lang.IllegalArgumentException: Expected starts with '{', but found 'n' in 'null'
     [exec]     	at com.liferay.headless.commerce.admin.shipment.client.json.BaseJSONParser._assertStartsWithAndEndsWith(BaseJSONParser.java:259)
     [exec]     	at com.liferay.headless.commerce.admin.shipment.client.json.BaseJSONParser.parseToDTO(BaseJSONParser.java:50)
     [exec]     	at com.liferay.headless.commerce.admin.shipment.client.serdes.v1_0.ShippingAddressSerDes.toDTO(ShippingAddressSerDes.java:39)
     [exec]     	at com.liferay.headless.commerce.admin.shipment.resource.v1_0.test.BaseShippingAddressResourceTestCase.testGraphQLGetShipmentByExternalReferenceCodeShippingAddress(BaseShippingAddressResourceTestCase.java:247)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
```

[com.liferay.headless.delivery.resource.v1_0.test.MessageBoardThreadResourceTest](https://testray.liferay.com/home/-/testray/case_results/1855183482)
```
     [exec] com.liferay.headless.delivery.resource.v1_0.test.MessageBoardThreadResourceTest > testGetMessageBoardSectionMessageBoardThreadsPageWithSortDateTime FAILED
     [exec]     java.lang.AssertionError: {"actions": {"delete": {"href": "http://localhost:8080/o/headless-delivery/v1.0/message-board-threads/61971", "method": "DELETE"}, "get": {"href": "http://localhost:8080/o/headless-delivery/v1.0/message-board-threads/61971", "method": "GET"}, "replace": {"href": "http://localhost:8080/o/headless-delivery/v1.0/message-board-threads/61971", "method": "PUT"}, "reply-to-thread": {"href": "http://localhost:8080/o/headless-delivery/v1.0/message-board-threads/61971/message-board-messages", "method": "POST"}, "subscribe": {"href": "http://localhost:8080/o/headless-delivery/v1.0/message-board-threads/61971/subscribe", "method": "PUT"}, "unsubscribe": {"href": "http://localhost:8080/o/headless-delivery/v1.0/message-board-threads/61971/unsubscribe", "method": "PUT"}}, "articleBody": "vgybitxa", "creator": {"additionalName": "", "contentType": "UserAccount", "familyName": "Test", "givenName": "Test", "id": 20127, "name": "Test Test"}, "creatorStatistics": {"joinDate": "2022-05-19T19:04:00Z", "postsNumber": 1, "rank": "Youngling"}, "customFields": [], "dateCreated": "2022-05-19T19:26:50Z", "dateModified": "2022-05-19T19:26:50Z", "encodingFormat": "html", "friendlyUrlPath": "kstzagfr", "hasValidAnswer": false, "headline": "kstzagfr", "id": 61971, "keywords": [], "locked": false, "messageBoardSectionId": 61968, "numberOfMessageBoardAttachments": 0, "numberOfMessageBoardMessages": 0, "relatedContents": [], "seen": false, "showAsQuestion": true, "siteId": 61965, "status": "approved", "subscribed": false, "taxonomyCategoryBriefs": [], "threadType": "Urgent", "viewCount": 0} does not equal {"actions": {"delete": {"href": "http://localhost:8080/o/headless-delivery/v1.0/message-board-threads/61976", "method": "DELETE"}, "get": {"href": "http://localhost:8080/o/headless-delivery/v1.0/message-board-threads/61976", "method": "GET"}, "replace": {"href": "http://localhost:8080/o/headless-delivery/v1.0/message-board-threads/61976", "method": "PUT"}, "reply-to-thread": {"href": "http://localhost:8080/o/headless-delivery/v1.0/message-board-threads/61976/message-board-messages", "method": "POST"}, "subscribe": {"href": "http://localhost:8080/o/headless-delivery/v1.0/message-board-threads/61976/subscribe", "method": "PUT"}, "unsubscribe": {"href": "http://localhost:8080/o/headless-delivery/v1.0/message-board-threads/61976/unsubscribe", "method": "PUT"}}, "articleBody": "o6fw435v", "creator": {"additionalName": "", "contentType": "UserAccount", "familyName": "Test", "givenName": "Test", "id": 20127, "name": "Test Test"}, "creatorStatistics": {"joinDate": "2022-05-19T19:04:00Z", "postsNumber": 2, "rank": "Youngling"}, "customFields": [], "dateCreated": "2022-05-19T19:26:50Z", "dateModified": "2022-05-19T19:26:50Z", "encodingFormat": "html", "friendlyUrlPath": "di8p4wsy", "hasValidAnswer": false, "headline": "di8p4wsy", "id": 61976, "keywords": [], "locked": false, "messageBoardSectionId": 61968, "numberOfMessageBoardAttachments": 0, "numberOfMessageBoardMessages": 0, "relatedContents": [], "seen": false, "showAsQuestion": true, "siteId": 61965, "status": "approved", "subscribed": false, "taxonomyCategoryBriefs": [], "threadType": "Urgent", "viewCount": 0}
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.BaseMessageBoardThreadResourceTestCase.assertEquals(BaseMessageBoardThreadResourceTestCase.java:2073)
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.BaseMessageBoardThreadResourceTestCase.assertEquals(BaseMessageBoardThreadResourceTestCase.java:2091)
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.BaseMessageBoardThreadResourceTestCase.testGetMessageBoardSectionMessageBoardThreadsPageWithSort(BaseMessageBoardThreadResourceTestCase.java:582)
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.BaseMessageBoardThreadResourceTestCase.testGetMessageBoardSectionMessageBoardThreadsPageWithSortDateTime(BaseMessageBoardThreadResourceTestCase.java:453)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
```

**Comment by vicnate5** [comment]
@victoroscuro Do you have anyone who could check the Commerce results here? There might be some additional regressions beyond just the backend tests.

**Comment by victoroscuro** [comment]
@vicnate5 sure, we're going to continue checking the results tomorrow. Just wondering whether the fix for https://issues.liferay.com/browse/COMMERCE-8750, which we're currently testing, is already in this PR. Thanks

**Comment by amosfong** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
ci:test:commerce

**Comment by victoroscuro** [comment]
@vicnate5 @amosfong we ran again ci:test:commerce after the changes pushed yesterday the and checked the results, they are aligned with our daily test suite, we've not identified unexpected failures.

**Comment by amosfong** [comment]
mbthread test fix sent here: https://github.com/liferay-frontend/liferay-portal/pull/2263

**Comment by vicnate5** [comment]
@tinatian This should be good to go now.

**Comment by tinatian** [comment]
@amosfong Code conflicts, please rebase.

Thanks.
Tina

**Comment by amosfong** [comment]
@tinatian rebased and repushed

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/118109

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
