### PR TITLE
LPS-192572

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5364

**Comment by tinatian** [comment]
ci:test:backend

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:backend

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139850

**Pull request closed without merging**
