### PR TITLE
[Components with more than 1 service] Refactor ElasticsearchConnectionManager component and ElasticsearchClientResolver interface

### PR DESCRIPTION
**Pull request by rcsdnj**
LPS-200589 portal-search-elasticsearch7-api - Unify ElasticsearchClientResolver and ElasticsearchConnectionManager under the same interface, avoiding ElasticSearchManager being registered in more than 1 service

Context: ElasticSearchManager was implementing the ElasticsearchClientResolver interface. There was no other implementation of ElasticsearchClientResolver (except for test fixtures), so all the points which were using the ElasticsearchClientResolver reference were changed to use ElasticsearchConnectionManager (which was refactored to have its own interface and implementation)

Revised by Rafael Praxedes in https://github.com/rafaprax/liferay-portal/pull/1337

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
@rafaprax @rcsdnj Code change looks OK to me, but could you try to keep the git history? In order to do that, you can commit in this way

- Extract interface methods definitions directly into `ElasticsearchClientResolver` so you can remove the class itself from component service list
- Rename `ElasticsearchConnectionManager` to `ElasticsearchConnectionManagerImpl`
- Rename `ElasticsearchClientResolver` to `ElasticsearchConnectionManager`
- Apply the new interface

Please resend, thanks!

**Pull request closed without merging**
