### PR TITLE
[Remove Stream/Optional usage] Phase 1 LPS-172541 module: portal-search-tuning-synonyms-web

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:search

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@dantewang No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130680

**Pull request closed without merging**
