### PR TITLE
[Remove Stream/Optional usage] LPS-178614 content-dashboard-document-library-test,content-dashboard-journal-test, content-dashboard-api

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-178614

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:tango

**Comment by JanisZhang** [comment]
ci:test:tango

**Comment by JanisZhang** [comment]
ci:test:tango

**Comment by catarineaguiar** [comment]
@JanisZhang regressions found:

```
     [exec] com.liferay.content.dashboard.journal.internal.item.test.JournalArticleContentDashboardItemTest > testGetDefaultContentDashboardItemAction FAILED
     [exec]     java.lang.NullPointerException
     [exec]     	at com.liferay.portal.kernel.portlet.PortletIdCodec.decodePortletName(PortletIdCodec.java:48)
     [exec]     	at com.liferay.portal.service.impl.PortletLocalServiceImpl.getPortletById(PortletLocalServiceImpl.java:604)
     [exec]     	at sun.reflect.GeneratedMethodAccessor676.invoke(Unknown Source)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
```
```
    [junit] 
    [junit] Testcase: testScanXMLLog(com.liferay.portal.log.assertor.PortalLogAssertorTest):	FAILED
    [junit] 
    [junit] Portal log assert failure, see above log for more information: 
    [junit] DocumentSummaryInformation property set came back as null
    [junit] junit.framework.AssertionFailedError: 
    [junit] DocumentSummaryInformation property set came back as null
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:171)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:86)
    [junit] 
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-03/test-1-34/test-portal-acceptance-pullrequest(master)/3740/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

**Comment by JanisZhang** [comment]
the same thing happened in this pull. wait for https://github.com/liferay-core-infra/liferay-portal/pull/3889#discussion_r1138235223

**Pull request closed without merging**
