### PR TITLE
LPS-200582 Remove log4j-1.2-api.jar

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, after cleaning up log4j1 related codes, this is going to remove log4j-1.2-api.jar. The previous pr is https://github.com/liferay-core-infra/liferay-portal/pull/5193.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
@dantewang, the current test exist many errors, these might be caused by [LPS-205216](https://liferay.atlassian.net/browse/LPS-205216). And that fix had been merged to BChan's master, but it isn't synchronized to liferay/master. After master includes that fix. I will run ci test relevant again.

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
Update:

The current test cases failed 209(3%). This is normal. But `Unique Failures` + `Did not run Failures` = 59. So I want to run ci test again. If next time still is 59, I will check them one by one.

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:report:2486858094

**Comment by yuhai** [comment]
ci:report:2486858094

**Comment by yuhai** [comment]
@dantewang, no regression bug found.

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
