### PR TITLE
[Method References 2] LPS-172192 Change the value of property cardinality from ReferenceCardinality.AT_LEAST_ONE to ReferenceCardinality.MULTIPLE | part 1

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:help

**Comment by W2jx** [comment]
ci:test:saml

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(1/6 8:59)

**Comment by dantewang** [comment]
@W2jx In this particular case, the `SamlBinding` implementations actually may not be necessary to be registered as OSGi services -- it's all internal. We can just create them and put them in a map statically.

**Pull request closed without merging**
