### PR TITLE
[Remove Blocking usages]LPS-188563 portal-kernel | UserBagFactoryUtil

### PR DESCRIPTION
**Pull request by W2jx**
previous: https://github.com/liferay-core-infra/liferay-portal/pull/4845

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:security

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(7/13 8:37)

**Comment by W2jx** [comment]
no conflicts(7/13 15:32)

**Comment by dantewang** [comment]
Closing, will merge the util directly into the util.

**Pull request closed without merging**
