### PR TITLE
[Remove unused references]LPS-166420 Remove reference field _userLocalService from BookedQuanti…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-166420

CI tests have been ran in https://github.com/slnn/liferay-portal/pull/659

### CODE REVIEW

**Comment by JanisZhang** [comment]
@slnn CI seems to have some issues.

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
No regressions found.

cc/ @zhangyan0701

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125174

cc @shuyangzhou @tinatian

**Pull request closed without merging**
