### PR TITLE
[TS] LPS-188014

### PR DESCRIPTION
**Pull request by yuhai**
@tinatian, @dantewang, the previous pr is https://github.com/liferay-core-infra/liferay-portal/pull/5092. Just add "SF, copyright" for java classes.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:start

**Comment by yuhai** [comment]
ci:test:clustering

**Comment by yuhai** [comment]
ci:test:startup

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@yuhai No regressions found.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5178

**Pull request closed without merging**
