### PR TITLE
LPS-165641 - update HyperSQL DataBase to 2.7.1

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-165641.
Thanks for checking!

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:setup-wizard

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by jeffwu0724** [comment]
fixed code conflict and resend

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@jeffwu0724 regressions found:

```
[exec] com.liferay.external.data.source.test.controller.test.ExternalDataSourceControllerTest > classMethod FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.arquillian.extension.junit.bridge.client.SocketState.writeUTF(SocketState.java:123)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.client.ClientState$1.execute(ClientState.java:127)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.junit.Arquillian.run(Arquillian.java:123)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
     [exec]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
```
     [exec] com.liferay.external.data.source.test.controller.test.ExternalDataSourceControllerParentTest > classMethod FAILED
     [exec]     org.osgi.framework.BundleException: Could not resolve module: com.liferay.external.data.source.test.controller.test [1496]
     [exec]       Unresolved requirement: Require-Capability: osgi.ee; filter:="(osgi.ee=UNKNOWN)"
     [exec]         at org.eclipse.osgi.container.Module.start(Module.java:444)
     [exec]         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
     [exec]         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:447)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.connector.FrameworkCommand.lambda$startBundle$37e16ea2$1(FrameworkCommand.java:46)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.connector.ArquillianConnectorThread.run(ArquillianConnectorThread.java:82)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-30/test-portal-acceptance-pullrequest(master)/5329/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

```
 [exec] com.liferay.counter.test.CounterLocalServiceTest > classMethod FAILED
     [exec]     org.osgi.framework.BundleException: Could not resolve module: com.liferay.counter.test [1500]
     [exec]       Unresolved requirement: Require-Capability: osgi.ee; filter:="(osgi.ee=UNKNOWN)"
     [exec]         at org.eclipse.osgi.container.Module.start(Module.java:444)
     [exec]         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
     [exec]         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:447)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.connector.FrameworkCommand.lambda$startBundle$37e16ea2$1(FrameworkCommand.java:46)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.connector.ArquillianConnectorThread.run(ArquillianConnectorThread.java:82)
     [exec] There were failing tests. See the report at: file:///opt/dev/projects/github/liferay-portal/modules/apps/counter/counter-test/build/reports/tests/testIntegration/index.html
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-30/test-portal-acceptance-pullrequest(master)/5329/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
