### PR TITLE
[TS] LPS-206648

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @marianoalvarosaiz ,

It looks like the proposed fix would introduce a new behavior in how the ConfigurationModelListeners would be fired.

**Questions**
- Were we able to confirm if the current behavior is considered a bug and that the new behavior is the expected behavior?
- And if so, would our existing configurationModelListeners behave as expected with the new behavior? Or would some rely on the current behavior?

**Comment by marianoalvarosaiz** [comment]
Hi @ericyanLr,

 this are the reasons why I considered it a bug:

- Although it is a ConfigurationModelListener and not a ModelListener it breaks somehow our pattern of executing the Listeners only on the "current" node.
- The database is the common source of information, so in the end, there is only one update/delete/save, the others are synchronizations, but the data is just modified once, so from a logical point of view the Listener should only be called once.
- The functionality as it is is somehow incoherent. If everything is OK the listeners are executed on each node, but if there is a failure before the ConfigurationEvent gets sent across the cluster the listeners are only executed on the "current" node 
- It's easier to adapt code if the listener only gets executed on the current node than if it gets executed on each node:
    - If code gets executed on each node it is difficult to synchronize with a custom development if you want it to only execute in one node.
    - If the code gets executed on one node and there is a need to execute it on each node with the clusterExecutor or the Clusterable annotation we can easily make it to execute on each node.

You're right in the sense that if this is consider a bug some of our code lilke TensorFlowImageAssetAutoTagProviderCompanyConfigurationModelListener,ExportImportServiceConfigurationModelListener,BaseConfigurationModelListener,QuestionsConfigurationModelListener will need to be adapted in a follow-up pull, but it will not be very complex. For custom developments, as there is no documentation already, it cannot be considered something problematic.

On the other side we also have code that assumes that it only gets executed on one node, like MFAEmailOTPConfigurationModelListener, MFASystemConfigurationModelListener that send a User notification per node.


If it isn't clear if we should consider it a bug or not this pull can be used to define a way to be able to define if the method is clusterable or not. Something similar to what it was done here: https://github.com/brianchandotcom/liferay-portal/pull/96268

Kind regards.

**Comment by ericyanLr** [comment]
Hi @marianoalvarosaiz ,

To help make sure we are focusing on the root of the issue, let's start with the mentioned point:
> The database is the common source of information, so in the end, there is only one update/delete/save, the others are synchronizations, but the data is just modified once, so from a logical point of view the Listener should only be called once.

From my testing, I noticed that each node would execute an update on the database at this particular line:
[ConfigurationPersistenceManager.java#L278](https://github.com/liferay/liferay-portal/blob/7.4.3.110-ga110/modules/apps/static/portal-configuration/portal-configuration-persistence-impl/src/main/java/com/liferay/portal/configuration/persistence/internal/ConfigurationPersistenceManager.java#L278)

Here are the steps I used:
1. Setup Liferay with a 2 node cluster
2. Start Liferay and make sure we have a healthy cluster
3. Navigate to Control Panel > System Settings >> Search >>> Cross-Cluster Replication
4. Click Save
5. Open DBeaver (or any database tool) to observe the **configuration_** table
    - Find the entry for: `com.liferay.portal.search.elasticsearch.cross.cluster.replication.internal.configuration.CrossClusterReplicationConfiguration`
    - Note the revision number for: `:org.apache.felix.configadmin.revision:`
6. Shutdown both nodes
7. Repeat Steps 2-5
8. Notice:
    - The revision number has been incremented twice
        - (Note: This double increment is observed during the first update when the nodes have just started - which is why step 6-7 restarts the cluster)
    - If we attach a debugger, we can observe the database is being called twice (once for each node) to update the entry


From my observations, two updates are being made to the database (update is executed on each node). However, the main configuration values are the same and so I'm not sure if you'll consider that as a modification or not for the second call.

I just want to make sure we are on the same page before proceeding, since I feel many of the other points depend on the expected behavior from this point.

Please let me know what you think.
Thanks!

**Comment by marianoalvarosaiz** [comment]
@ericyanLr you're completely right. I meant the meaningful values (that don't change), but I forgot to check the revision.

Taking that into account, does it make sense that the revision gets updated as many times as nodes has the cluster?

**Comment by ericyanLr** [comment]
Hi @marianoalvarosaiz ,

**Regarding:**
>  I meant the meaningful values (that don't change), but I forgot to check the revision.
> 
> Taking that into account, does it make sense that the revision gets updated as many times as nodes has the cluster?

I would say it would depend on the behavior we decide on as expected behavior (e.g. whether a database update should be expected to be executed on every node).

The main reason I brought about this observation, is basically to work towards determining what is the root issue:
- Currently, the proposed fix is working towards preventing other nodes from executing the listeners, however a database update is still being executed on every node.
- And so, the question is what is the root issue?
    - Is the root issue specifically just the listeners being executed on every node?
    - Or should the root issue also account for whether a database update/insert should be executed on every node?
        - If so, is the root issue whether the logic in the **ConfigurationPersistenceManager::store** method should not be executed on every node?
        - And if so, then our fix would probably need to account for other methods as well. (e.g. store and delete)

I think once we can determine the expected behavior, we would be able to properly identify what the bug(s) are from the currently observed behavior.

**Comment by ericyanLr** [comment]
Closing out this PR, as it's now being handled under LPD-1755.

Latest PR: https://github.com/liferay-core-infra/liferay-portal/pull/6630

**Pull request closed without merging**
