### PR TITLE
LPS-188134 test moving guava to shared-dependenceis

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian ,

As we talked, I redo this PR, and only moving guava to shared-dependencies without upgrading its versions, which should be easier to debug. 

When I tried to follow the reproduce step here https://liferay.atlassian.net/browse/LPS-191330, it will throw
```
Caused by: java.lang.ClassNotFoundException: com.google.common.base.CaseFormat cannot be found by com.liferay.document.library.opener.onedrive.web_3.0.46
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:518) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:429) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:151) ~[org.eclipse.osgi.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_382]
        at com.microsoft.graph.serializer.DefaultSerializer.getDerivedClass(DefaultSerializer.java:286) ~[?:?]
        at com.microsoft.graph.serializer.DefaultSerializer.deserializeObject(DefaultSerializer.java:86) ~[?:?]
        at com.microsoft.graph.http.CoreHttpProvider.handleJsonResponse(CoreHttpProvider.java:513) ~[?:?]
        at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:395) ~[?:?]
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:204) ~[?:?]
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:184) ~[?:?]
        at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:306) ~[?:?]
        at com.microsoft.graph.requests.extensions.DriveItemCreateLinkRequest.post(DriveItemCreateLinkRequest.java:44) ~[?:?]
        at com.liferay.document.library.opener.onedrive.web.internal.DLOpenerOneDriveManager.getOneDriveFileURL(DLOpenerOneDriveManager.java:190) ~[?:?]
        at com.liferay.document.library.opener.onedrive.web.internal.portlet.action.OneDriveBackgroundTaskStatusMVCResourceCommand.doServeResource(OneDriveBackgroundTaskStatusMVCResourceCommand.java:107) ~[?:?]
        at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCResourceCommand.serveResource(BaseMVCResourceCommand.java:32) ~[portal-kernel.jar:?]
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.callResourceMethod(MVCPortlet.java:453) ~[portal-kernel.jar:?]
        at com.liferay.portal.kernel.portlet.LiferayPortlet.serveResource(LiferayPortlet.java:129) ~[portal-kernel.jar:?]
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.serveResource(MVCPortlet.java:357) ~[portal-kernel.jar:?]
        at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:137) ~[portal-impl.jar:?]
        at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:79) ~[portal-impl.jar:?]
        at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:131) ~[portal-impl.jar:?]
        at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:69) ~[portal-kernel.jar:?]
        at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:105) ~[portal-kernel.jar:?]
```

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:online-editing

**Comment by dantewang** [comment]
@jeffwu0724 I guess the issue is that the not-found class is used by some third-party library we depend on, but in a way that bnd will not automatically recognize, so the generated manifest.mf doesn't import `com.google.common.base`. Try to manually add this import to bnd.bnd of the module and see if it solves the problem.

**Comment by jeffwu0724** [comment]
Hi @dantewang ,

Thanks for helping me with this. I have tried to manually add this import to bnd.bnd of the module, but unfortunately, it is still not working. 
As I only move guave to shared-dependencies without upgrading its version, but `com.liferay.document.library.opener.onedrive.web` cannot find this `com.google.common.base.CaseFormat`, I guess it may be because of the current version of com.microsoft.graph in onedrive.web being too low for guava, but since we compileInclude it all the time, this `java.lang.ClassNotFoundException` issue gets hidden.
Therefore, I would like to try:
- move guava to shared-dependencies, but using version 20.0, which is matched with current version of microsoft.graph based on maven
- besides checking on `com.liferay.document.library.opener.onedrive.web`, I will see if I can find anything in GCS store, as it also failed based on https://liferay.atlassian.net/browse/LPS-191330?focusedCommentId=2183137

Please let me know if you have any ideas about this. 
Really appreciate your help! :)

**Comment by dantewang** [comment]
@jeffwu0724 Strange. Before your change, guava is `compileInclude` in the one-driver-opener module, which means the classes are in the same class loader -- as long as `com.google.common.base.CaseFormat` is in the jar, it can be found by the class loader; while after your change, they are in different OSGi class loaders. That's why I guess it's an import thing...

**Comment by jeffwu0724** [comment]
@dantewang

**Comment by dantewang** [comment]
@jeffwu0724 Seems like the import-package should work, if we look at https://docs.osgi.org/specification/osgi.core/7.0.0/images/003-class-loading-flowchart.png

I'm not sure about what exactly happens here... To know better, we have to debug from the Microsoft code into the OSGi code...

**Comment by jeffwu0724** [comment]
Hi @dantewang ,

I think I know what is happening now. If we look at manifest of `onedrive-web module`, since we have compileInclude `google-collections`, then it will have add `google-collections - com.google.common.base` to the **private package**. Therefore, even though we import `com.google.common.base` manually, it won't work because bnd think we have `com.google.common.base` already. However, the `com.google.common.base` we have in the jar now is from google-collections, not guava, so it does not include CaseFormat, and will lead to noclassdeffound exception.

**Comment by dantewang** [comment]
@jeffwu0724 Great!

**Pull request closed without merging**
