### PR TITLE
LPS-142278 Remove portal lib dir | Rebased on LPS-143939 12-16

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian This pull is a rebase of https://github.com/liferay-core-infra/liferay-portal/pull/76 on top of https://github.com/liferay-core-infra/liferay-portal/pull/75. This is made because both PRs touched `XugglerImpl.java`.

**Comment by tinatian** [comment]
Sorry @dantewang, conflicts again, please rebase.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by dantewang** [comment]
@tinatian It seems Victor already rebased? https://github.com/liferay-core-infra/liferay-portal/pull/80

**Pull request closed without merging**
