### PR TITLE
[Remove unused field] LPS-200175 Remove unused reference field in calsses NotificationsSharingEntryLocalServiceWrapper, StyleBookScopedCSSVariablesProvider and XLIFFTranslationSnapshotProvider

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
Remove unused reference field in calsses NotificationsSharingEntryLocalServiceWrapper, StyleBookScopedCSSVariablesProvider and XLIFFTranslationSnapshotProvider

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
no conflicts(10/30 7:57)

**Comment by W2jx** [comment]
no conflicts(10/30 7:57)

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(11/1 9:03)

**Comment by W2jx** [comment]
no conflicts(11/2 8:14)

**Comment by W2jx** [comment]
Forced push to resolve the conflict about SF file, no logic changes.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143174

cc @shuyangzhou

**Pull request closed without merging**
