### PR TITLE
remove_deprecated_part_8_portal_impl_fixed_test

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Fixed error mentioned in https://github.com/liferay-core-infra/liferay-portal/pull/698
This is remove_deprecated_part_8_portal_impl
Thanks for checking. Also see https://github.com/jeffwu0724/liferay-portal/pull/63 and https://github.com/jeffwu0724/liferay-portal/pull/64

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Please help me scan test results.

Thanks
Jeff

**Comment by tinatian** [comment]
@jeffwu0724 The commit message "auto SF, running by "ant build-services"" dose not make sense. "Auto SF" usually means you run "ant format-source". Here what we you did is to regenerate the data by running "build-services", so you can set the commit message to be "Auto generated".

**Comment by tinatian** [comment]
@jeffwu0724 As we talked, please fix and resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
