### PR TITLE
LPD-16091 Refactor Log4jConfigUtilTest

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPD-16091

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@rafaprax @MrJohn1911 This does not seem right, why the asserting is not same on JDK8 and JDK21?

**Comment by rafaprax** [comment]
Hey @tinatian, the assertion is different because the implementation of this ("Helpful NullPointerExceptions") enhancement here https://openjdk.org/jeps/358

**Comment by tinatian** [comment]
@rafaprax As we talked, please resend.

Thanks.
Tina

**Pull request closed without merging**
