### PR TITLE
[Remove Spring extender usages] LPS-159168

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove spring extender usage in commerce-currency-service, thanks!
https://issues.liferay.com/browse/LPS-159168

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @catarineaguiar , Could you review the test results when they finish? Thanks!

**Comment by dantewang** [comment]
ci:test:acceptance

**Review by dantewang — APPROVED** [review]
Code looks good, waiting for QA to verify.

@zhangyan0701 could you take a look when tests finish? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@tinatian This is good to go.

**Comment by tinatian** [comment]
ci:test:help

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
@JanisZhang @dantewang @tinatian  https://github.com/liferay-core-infra/liferay-portal/pull/1222/commits/c4ba69c0ba857fd8bd2b32e8189ee41c40269546 is not right, see 6d42a962f1b49510efc27b802569fec852cd6c44 for explanation. Basically you have to keep the PortalInstanceLifecycleListenerImpl being registered programmly rather than making it a Component. Do it inside CommerceCurrencyLocalServiceImpl's activate/deactivate to keep the lifecycle consistent as past, otherwise the https://issues.liferay.com/browse/COMMERCE-6391 regression will come back.

**Pull request closed without merging**
