### PR TITLE
[Method References 2] LPS-165169 Convert method reference in module portal-search

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(2022/12/7 9:36)

**Comment by W2jx** [comment]
no conflicts(2022/12/8 9:25)

**Comment by W2jx** [comment]
no conflicts(12/9 9:49)

**Comment by W2jx** [comment]
no conflicts(12/13 9:55)

**Comment by W2jx** [comment]
no conflicts(2022/12/14 9:41)

**Comment by W2jx** [comment]
no conflicts(12/15 9:25)

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
