### PR TITLE
[Method References 2] LPS-165285 Convert method reference to ServiceTrackerMap in class CompositeFacetProcessor(module portal-search-elasticsearch7-impl)

### PR DESCRIPTION
**Pull request by W2jx**
resend, Code has been modified as per [comment](https://github.com/liferay-core-infra/liferay-portal/pull/4068#discussion_r1161039551).

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4068

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@W2jx No regressions. Need to rebase.

**Comment by W2jx** [comment]
Force-Push is just to resolve a conflict.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(4/12 9:52)

**Comment by W2jx** [comment]
no conflicts(4/13 8:00)

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133346

**Pull request closed without merging**
