### PR TITLE
LPS-191898 Company related cache should only be removed when company …

### PR DESCRIPTION
**Pull request by tinatian**
…is removed

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by zhangyan0701** [comment]
Some unit tests failed to run in ci:test:clustering, re trigger test suite.

**Comment by zhangyan0701** [comment]
ci:test:clustering

**Comment by Kvale1733** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
