### PR TITLE
[Component with its own class name as service type] LPS-198943 Refactor Helper components from commerce modules part 1

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-198943](https://liferay.atlassian.net/browse/LPS-198943)

Previous Pull: https://github.com/brianchandotcom/liferay-portal/pull/142874

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:commerce

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:commerce

**Comment by RenanUmV** [comment]
ci:test:commerce

**Comment by RenanUmV** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@RenanUmV No regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by RenanUmV** [comment]
resent here: https://github.com/liferay-core-infra/liferay-portal/pull/6133

**Pull request closed without merging**
