### PR TITLE
[Method References 2] LPS-170883 Convert method reference to ServiceTrackerMap in class DefaultAuditRouter

### PR DESCRIPTION
**Pull request by W2jx**
The product team wants us to keep the logic for handling `eventTypes`. see: https://issues.liferay.com/browse/PTR-3682

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3228

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(3/1 9:29)

**Review by dantewang — APPROVED** [review]

**Comment by W2jx** [comment]
no conflicts(3/3 10:55)

**Comment by W2jx** [comment]
no conflicts(3/6 16:03)

**Comment by W2jx** [comment]
no conflicts(3/7 9:02)

**Comment by W2jx** [comment]
no conflicts(3/8 15:25)

**Comment by W2jx** [comment]
no conflicts(3/14 15:20)

**Comment by tinatian** [comment]
@W2jx Please push the security team to add the test or you add the test to show that we need to keep event type.

Tina.

**Pull request closed without merging**
