### PR TITLE
[Bug Fix] LPS-143510

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on the [requirement](https://github.com/liferay-core-infra/liferay-portal/pull/55#issuecomment-989710238).

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
@dantewang, I just push force about commit message change.

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@yuhai @dantewang Please see https://github.com/liferay-core-infra/liferay-portal/pull/65, and note my change at https://github.com/liferay-core-infra/liferay-portal/pull/65/commits/115cc42ea2adaa72b51d9812bb910e0a0aff2705

Tina

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
