### PR TITLE
[SampleSQLBuilder-add-missing-portletpreferences]Lps 203325

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-203325

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@slnn Will this PR make sure we don't encounter the exceptions when warming up database concurrently on a multi-group DB?

If so, @GinsonRen please try it with 100 groups, run warmup normally.

**Comment by slnn** [comment]
> @slnn Will this PR make sure we don't encounter the exceptions when warming up database concurrently on a multi-group DB?
> 
> If so, @GinsonRen please try it with 100 groups, run warmup normally.

Yes, this pull will make sure we don't encounter the exceptions when warming up database concurrently on a multi-group DB, I tested it on main3 env with WebContent for 10 groups, no portletreference related exceptions appeared during the warmup process.

**Comment by dantewang** [comment]
@GinsonRen Please find some time to try it on all test cases.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by 111Anna** [comment]
Hi @dantewang @slnn  I  tested the PR on main2 env, but in different cases, the situation is different
/cc @GinsonRen

- On Login ,WC, AP,  there no  exceptions appeared during the warmup and test process.

**Login:**
 old data
>  sample.sql.max.group.count=1    
>  sample.sql.max.user.count=100000

 new data
>  sample.sql.max.group.count=100  
>  sample.sql.max.user.count=1000

**WC:**
old data
> sample.sql.max.group.count=1   
> sample.sql.max.user.count=100000  
> sample.sql.max.journal.article.page.count=6

new data
> sample.sql.max.group.count=100    
> sample.sql.max.user.count=1000   
> sample.sql.max.journal.article.page.count=1

**AP:**
old data
> sample.sql.max.group.count=1  
> sample.sql.max.user.count=100000  
> sample.sql.max.journal.article.count=1000  
> sample.sql.max.wiki.page.count=1000  
> sample.sql.max.blogs.entry.count=1000

new data
> sample.sql.max.group.count=100  
> sample.sql.max.user.count=1000  
> sample.sql.max.journal.article.count=100  
> sample.sql.max.wiki.page.count=10  
> sample.sql.max.blogs.entry.count=10

- On MB, I didn't see  in warmup process, but there are some exceptions in portal when I ran test. Errors please see https://gist.github.com/111Anna/c77e2b6c82acad62695cc59054819afa/revisions

- On Blog and DL,  I have tried many sets of data, but there are still exceptions during the warmup process. Errors please see https://gist.github.com/111Anna/613d8d062661d28689c8296df4849182/revisions

**Blog data:**
Screenshot_2023-12-22_16-47-37

**DL data:**
Screenshot_2023-12-22_16-47-53

**Comment by slnn** [comment]
Thanks @111Anna !

I will double check them.

**Comment by slnn** [comment]
Hi @111Anna 

Please rerun tests as we talked next week!

Thanks!
Lily

**Pull request closed without merging**
