### PR TITLE
[Method References] LPS-162562 Convert method references to field references in modules password-policies-admin*、plugins-admin-web

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I convert method references to field references in modules password-policies-admin*、plugins-admin-web.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results when they finish ? Thanks!

**Comment by zhangyan0701** [comment]
ci:test:password-policies

**Comment by zhangyan0701** [comment]
All tests passed.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

**Comment by dantewang** [comment]
@tinatian @shuyangzhou Tiggered forward as it contains only simple replacements, and passed CI.

**Pull request closed without merging**
