### PR TITLE
[Method Reference]Lps 180691 2

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-180691

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:search-solr

**Comment by dantewang** [comment]
Also asking Search Team why they use dynamic greedy reference but don't handle service rebound in `SolrClientManager`.

**Comment by slnn** [comment]
Forced pushed with SF changes which to use`new PropertyServiceReferenceMapper<>` instead of `new PropertyServiceReferenceMapper<String, SolrClientFactory>`

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:search-solr

**Comment by slnn** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by slnn** [comment]
Hi @tinatian 

This pull was marked as draft since we are still waiting for the response from Search Team

**Comment by slnn** [comment]
> @slnn It's been several weeks, please keep pushing them. Or else, we may need to figure out a way without their response.
> 
> Tina

Got it

**Comment by dantewang** [comment]
Closing this PR for now, please resend with their answer or alternative approach.

**Pull request closed without merging**
