### PR TITLE
LPS-175227 Add new method to support transform(array..) to primitive type

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-175227

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
Hi @dantewang, can I added a new method to transform the array? If I change the original method, all usages need to be changed to ```TransformUtil.transform(Interger[], unsafeFunction, xxx[].class)```

**Comment by dantewang** [comment]
@JanisZhang Actually it's possible to change the original method without the need to apply to all usages; but it will lose the ability of Java's type checking. Let's just keep the new method for now.

**Comment by JanisZhang** [comment]
Force-pushed, I only changed the commit message. It shouldn't affect the ci test results. Thanks!

**Comment by Kvale1733** [comment]
@JanisZhang No regressions.

**Comment by dantewang** [comment]
@JanisZhang Closing, since BChan already merged the pull from Lily. Thanks for the effort.

**Comment by JanisZhang** [comment]
Hi @dantewang, OK, just a small question. For transforming Array to primitive Array case, it should `transformToList` first and then `transformToPrimitiveArray`, right?

**Comment by dantewang** [comment]
@JanisZhang Does the new API only cover List to Array transformation?

**Comment by dantewang** [comment]
@JanisZhang If so, you can simply wrap the original array with `Arrays.asList` because the method doesn't do array copy internally.

**Pull request closed without merging**
