### PR TITLE
[commons-lang] LPD-20263 Remove commons-lang StringEscapeUtils usages

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:help

**Comment by julschong** [comment]
ci:test:configuration-framework

**Comment by julschong** [comment]
ci:report:2553545473

**Comment by julschong** [comment]
1 unique failure with LDAP `PortalLogAssertorTest-modules-integration-mysql57-jdk8/0/7`

```
PortalLogAssertorTest#testScanXMLLog: Unable to bind to the LDAP server javax.naming.CommunicationException: localhost:10389 [Root exception is java.net.ConnectException: Connection refused (Connection refused)]  at com.sun.jndi.ldap.Connection.<init>(Connection.java:235)  at com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137)  at com.sun.jndi.ldap.LdapClientFactory.createPooledConnection(LdapClientFactory.java:71)  at com.sun.jndi.ldap.pool.Connections.createConnection(Connections.java:187)  at com.sun.jndi.ldap.pool.Connections.getAvailableConnection(Connections.java:152)  at com.sun.jndi.ldap.pool.Pool.getOrCreatePooledConnection(Pool.java:188)  at com.sun.jndi.ldap.pool.Pool.getPooledConnection(Pool.java:148)  at com.sun.jndi.ldap.LdapPoolManager.getLdapClient(LdapPoolManager.java:340)  at com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1607)  at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2847)  at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:348)  at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUr...
```

**Comment by julschong** [comment]
ci:test:ldap

**Comment by julschong** [comment]
https://github.com/liferay-core-infra/liferay-portal/pull/6796#issuecomment-2015563782
Same LDAP failure is found in other test results as well. not unique.

Need to add test coverage for the change on ValueTokenizer

**Comment by tinatian** [comment]
@julschong Please add test to MetatypeAttributeDefinitionTest to expose the issue first, then fix it.

Your current patch only takes care of "//,/"", what if "/",//"?  Please take a look at the OSGi Compendium spec 105.7 to figure out the right expected behavior.

Please resend.

Thanks.
Tina.

**Pull request closed without merging**
