### PR TITLE
LPD-X Jasper cleanup | 11-28

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:79711094

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@shuyangzhou Maybe due to test.properties setting the `JspPrecompileTest` did not run in the relevant runs. But I executed them locally and they passed.

**Comment by shuyangzhou** [comment]
Thanks @dantewang !

See https://github.com/brianchandotcom/liferay-portal/pull/156566

**Pull request closed without merging**
