### PR TITLE
LPS-143631 Remove JSONFactoryUtil usages in modules and use service reference instead final

### PR DESCRIPTION
**Pull request by julschong**
LPS-143631 Remove JSONFactoryUtil usages from modules final

### CODE REVIEW

**Comment by zhangyan0701** [comment]
Possible regression:
Some modules unit tests failed with NPE error:
```
     [exec] com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.ElasticsearchSearchEngineAdapterIndexRequestTest > testExecuteGetFieldMappingIndexRequest FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.index.GetFieldMappingIndexRequestExecutorImpl.execute(GetFieldMappingIndexRequestExecutorImpl.java:75)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.index.ElasticsearchIndexRequestExecutor.executeIndexRequest(ElasticsearchIndexRequestExecutor.java:96)
     [exec]         at com.liferay.portal.search.engine.adapter.index.GetFieldMappingIndexRequest.accept(GetFieldMappingIndexRequest.java:40)
     [exec]         at com.liferay.portal.search.engine.adapter.index.GetFieldMappingIndexRequest.accept(GetFieldMappingIndexRequest.java:22)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.ElasticsearchSearchEngineAdapterImpl.execute(ElasticsearchSearchEngineAdapterImpl.java:91)
     [exec]         at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.ElasticsearchSearchEngineAdapterIndexRequestTest.testExecuteGetFieldMappingIndexRequest(ElasticsearchSearchEngineAdapterIndexRequestTest.java:381)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
     [exec]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
     [exec]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
     [exec]         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
     [exec]         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]         at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
     [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
     [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
     [exec]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
     [exec]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
     [exec]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
     [exec]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
     [exec]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
     [exec]         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]         at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]         at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]         at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
     [exec]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
     [exec]         at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
     [exec]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
     [exec]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
     [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
     [exec]         at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
     [exec]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
     [exec]         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
     [exec]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
     [exec]         at java.lang.Thread.run(Thread.java:745)
```

Failed tests:
https://testray.liferay.com/home/-/testray/case_results?testrayCaseTypeId=60250159&testrayBuildId=2041598438

All the failed tests also failed in https://github.com/julschong/liferay-portal/pull/623.

**Comment by julschong** [comment]
pushed to fix unit tests

**Comment by julschong** [comment]
ci:test:sf

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2442

**Pull request closed without merging**
