### PR TITLE
[add-opens] LPD-26170 Add --add-opens java.base/sun.net.www.protocol.https=ALL-UNNAMED to unit test and server jvm args

### PR DESCRIPTION
**Pull request by julschong**
https://liferay.atlassian.net/browse/LPD-26170

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:jdk21-unit

**Comment by julschong** [comment]
no regression

**Comment by julschong** [comment]
ci:report:2570322915

**Comment by julschong** [comment]
ci:report:2570322915

**Comment by julschong** [comment]
@tinatian no regression found. Will add more commit message soon

**Comment by julschong** [comment]
commit message is revised:
```
Add --add-opens jvm args for sun.net.www.protocol.https so that HttpInvoker can work under jdk21. HttpInvoker uses reflection on private final field "delegate" in HttpsURLConnectionImpl which does not work under jdk21 unless we open the jdk internal package in jvm args.
```

**Comment by julschong** [comment]
root cause is linked: https://liferay.atlassian.net/browse/LPD-24753

**Comment by julschong** [comment]
need to add the commit that caused this failure in commite message

**Comment by julschong** [comment]
added reference to the root cause commit in the commit message

**Comment by julschong** [comment]
@tinatian this is ready

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
ci:stop

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/150542

**Pull request closed without merging**
