### PR TITLE
[Urgent][Security Bugs]LPD-1558 add properties to control captcha on or off for ci

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

Resend: https://github.com/liferay-core-infra/liferay-portal/pull/6885
In this PR,

I add a new properties captcha.enforce.disabled to disable enforcing captcha in ci test
change setMaxChallenges() to enforceCaptcha()
restructure the commits
Thanks for chekcing

### CODE REVIEW

**Comment by jeffwu0724** [comment]
The failing functional test I mentioned today is not related to this PR, it is introduced by https://github.com/brianchandotcom/liferay-portal/pull/149214/commits/4a5b77f10f72d385e90f3d605f802be489bac282
acceptance-functional test:
https://testray.liferay.com/home/-/testray/case_results/2561006344/history - reproduced locally

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:acceptance-functional

**Comment by jeffwu0724** [comment]
ci:test:backend

**Comment by jeffwu0724** [comment]
ci:report:2561364853

**Comment by jeffwu0724** [comment]
ci:report:2561378995

**Comment by jeffwu0724** [comment]
ci:report:2561403108

**Comment by jeffwu0724** [comment]
relevant test: 
No regression found

acceptance-functional test:
https://testray.liferay.com/home/-/testray/case_results/2561386126/history - not caused by this PR, FYI https://github.com/liferay-core-infra/liferay-portal/pull/6891#issuecomment-2059983664
https://testray.liferay.com/home/-/testray/case_results/2561382053/history - passed locally
https://testray.liferay.com/home/-/testray/case_results/2561380385/history - passed locally

backend test:
No other special error found

Therefore, I think it is safe to move forward

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/149364

**Pull request closed without merging**
