### PR TITLE
LPS-191313 Remove FieldMappingsWebCacheItem


### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
Issue found:

1. Error thrown when create Blueprints.
Steps:

- Go to Global Menu > Applications > Blueprints.

- Create a new Blueprints.

Assert error in portal console:
```
2023-07-25 12:12:06.485 ERROR [http-nio-8080-exec-1][ExceptionMapper:68] null
java.lang.NullPointerException: null
	at com.liferay.search.experiences.rest.internal.resource.v1_0.FieldMappingInfoResourceImpl.getFieldMappings(FieldMappingInfoResourceImpl.java:75) ~[?:?]
	at com.liferay.search.experiences.rest.internal.resource.v1_0.FieldMappingInfoResourceImpl.getFieldMappingInfosPage(FieldMappingInfoResourceImpl.java:67) ~[?:?]
```

2. Integration test [FieldMappingInfoResourceTest](https://testray.liferay.com/home/-/testray/case_results/2394150302) failed.
```
##
## com.liferay.search.experiences.rest.resource.v1_0.test.FieldMappingInfoResourceTest > testGetFieldMappingInfosPage
##

	java.lang.AssertionError: Thread Thread[http-nio-8080-exec-10,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.vulcan.internal.jaxrs.exception.mapper.ExceptionMapper, message=null
	java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.vulcan.internal.jaxrs.exception.mapper.ExceptionMapper, message=null
```
Full log:
https://testray.liferay.com/reports/production/logs/2023-07/test-1-37/test-portal-acceptance-pullrequest(master)/13356/modules-integration-mysql57-jdk8/0/11/com.liferay.search.experiences.rest.resource.v1_0.test.FieldMappingInfoResourceTest.txt.gz?authuser=0

**Comment by julschong** [comment]
@zhangyan0701 
I think I fixed 1. Error thrown when create Blueprints

2. Integration test [FieldMappingInfoResourceTest]
    I don't think this is unique to my pull. I deployed the same modules in master branch and still got the same erorr. Could you please help me verify this?

Thanks!

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
Hi @julschong 

I still could reproduce the error when thrown Blueprints.

And about the integration test, from the test history, it only failed with the changes here. And I could reproduce locally.

**Comment by julschong** [comment]
@zhangyan0701 I made a mistake on the new commit, i just pushed again. Please help try to see if it fixed issue 1.
Issue 2, I will check again

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No regressions found. The issues above were fixed.

**Pull request closed without merging**
