### PR TITLE
[Method References] LPS-163769 Convert method references to field references in module portal-search-elasticsearch7-impl | part 6

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I convert method references to field references in module portal-search-elasticsearch7-impl.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by zhangyan0701** [comment]
Relevant tests passed, no regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@shuyangzhou @tinatian Forwarding as tests passed and replacements are direct.

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
