### PR TITLE
[Components with more than 1 service] LPS-186808 Refactor components from marketplace, portal-scheduler, portal-template modules

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-186808](https://issues.liferay.com/browse/LPS-186808)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:help

**Comment by RenanUmV** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:clustering

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@RenanUmV No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
