### PR TITLE
[Remove Blocking usages]LPS-193174 PortletResourcePermissionFactory and ModelResourcePermissionFactory

### PR DESCRIPTION
**Pull request by haydenzheng314**
Ticket: https://liferay.atlassian.net/browse/LPS-193174
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@LisztLiszt There is a startup issue
```
eanshell] 2023-11-01 07:36:58.206 INFO  [http-nio-8080-exec-1][BundleSiteInitializer:456] Initializing com.liferay.site.initializer.welcome for group 20118
[beanshell] 2023-11-01 07:36:58.217 INFO  [http-nio-8080-exec-1][BundleSiteInitializer:4688] Invoking line 486 took 8 ms
[beanshell] 2023-11-01 07:36:58.218 INFO  [http-nio-8080-exec-1][BundleSiteInitializer:4688] Invoking line 487 took 0 ms
[beanshell] 2023-11-01 07:36:58.218 INFO  [http-nio-8080-exec-1][BundleSiteInitializer:4688] Invoking line 489 took 0 ms
[beanshell] 2023-11-01 07:36:58.219 INFO  [http-nio-8080-exec-1][BundleSiteInitializer:4688] Invoking line 491 took 1 ms
[beanshell] 2023-11-01 07:36:58.220 INFO  [http-nio-8080-exec-1][BundleSiteInitializer:4688] Invoking line 495 took 0 ms
[beanshell] 2023-11-01 07:36:58.596 ERROR [http-nio-8080-exec-1][BundleSiteInitializer:617] null
[beanshell] java.lang.NullPointerException: null
[beanshell] 	at com.liferay.portal.kernel.security.permission.resource.ModelResourcePermissionUtil.check(ModelResourcePermissionUtil.java:26) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portlet.documentlibrary.service.impl.DLFolderServiceImpl.addFolder(DLFolderServiceImpl.java:48) ~[portal-impl.jar:?]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
[beanshell] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.service.ServiceContextAdvice.invoke(ServiceContextAdvice.java:51) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:55) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40) ~[portal-impl.jar:?]
[beanshell] 	at com.sun.proxy.$Proxy169.addFolder(Unknown Source) ~[?:?]
[beanshell] 	at com.liferay.portal.repository.liferayrepository.LiferayRepository.addFolder(LiferayRepository.java:172) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.repository.util.RepositoryWrapper.addFolder(RepositoryWrapper.java:85) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.repository.util.RepositoryWrapper.addFolder(RepositoryWrapper.java:85) ~[portal-impl.jar:?]
```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-40/test-portal-acceptance-pullrequest(master)/7052/functional-smoke-tomcat90-hypersonic20-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
