### PR TITLE
[Unused variable]Lps 205910

### PR DESCRIPTION
**Pull request by JanisZhang**
This issue was introduced during the application of the new checkedUnusedVariable SF rule. Sending this to fix the SF.

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
no regression found. cc @dantewang 

relevant test:
https://test-1-1.liferay.com/job/generate-testray-csv/7758/
startup test:
https://test-1-1.liferay.com/job/generate-testray-csv/7763/
upgrade test:
https://test-1-1.liferay.com/job/generate-testray-csv/7801/

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Comment by JanisZhang** [comment]
ci:forward:force

**Pull request closed without merging**
