### PR TITLE
LPS-171005 Remove "immediate = true" from remaining Publications modules

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@daiazius No regressions found.

**Comment by daiazius** [comment]
Hey @shuyangzhou can you review this pull? thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127669

**Pull request closed without merging**
