### PR TITLE
[Remove immediate = true from lima Part I] LPS-168427

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the previous pr is https://github.com/liferay-core-infra/liferay-portal/pull/2530. The pr only includes removing "immediate = true", doesn't includes other logic(handle component activated). And the pr doesn't include announcements, document-library and redirect bundles. Since these bundles need to use other ways to handle few components activated.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:startup

**Comment by yuhai** [comment]
@dantewang, I just push force the new changes. The pr only doesn't include three classes TensorFlowImageAssetAutoTagProviderCompanyConfigurationModelListener, CheckRedirectNotFoundEntriesMessageListener and com.liferay.announcements.web.internal.messaging.CheckEntryMessageListener. Since there are related issues happened after removing "immediate = true" from these components. I will trigger ci test again.

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
@yuhai no regressions found.

**Comment by dantewang** [comment]
@zhangyan0701 Do you have any other tests you think we should trigger? Thanks!

**Comment by zhangyan0701** [comment]
ci:test:lima

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@yuhai Code looks good to me, please rebase. If the code conflicts are simple enough, no need to trigger ci test, please forward to BChan directly and cc me and shuyang.

Thanks.
Tina

**Comment by yuhai** [comment]
@tinatian, send it to https://github.com/brianchandotcom/liferay-portal/pull/127107

**Pull request closed without merging**
