### PR TITLE
[Remove Stream usages in method body: asset-list-web]Lps 175797

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-175797

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130486

**Comment by jkappler** [comment]
@dantewang, @slnn, @catarineaguiar, this caused blocker https://issues.liferay.com/browse/LPS-176138 (as can be seen in the failing tests). Can we be a bit more careful next time please?

@mikellorza is sending a PR addressing the issue.

Thanks

**Comment by slnn** [comment]
Sorry, my bad, the root cause of this issue is I invoked the sort method on an unmodified list see
https://github.com/slnn/liferay-portal/blob/53a1d30c4c865f0bb9f517a2f9284b0da1fa517f/modules/apps/asset/asset-list-web/src/main/java/com/liferay/asset/list/web/internal/display/context/EditAssetListDisplayContext.java#L1195~L1197
 
I have a quick fix for it https://github.com/Mikellorza/liferay-portal/pull/1. @Mikellorza, if you have fixed it, please ignore this pull.

**Comment by jkappler** [comment]
Hi @slnn, thanks for the quick fix. @mikellorza already had sent one https://github.com/liferay-echo/liferay-portal/pull/11198

**Pull request closed without merging**
