### PR TITLE
[Method References] LPS-160434 Replace method setServletContext with field _servletContext in classes extend BaseJSPPanelApp

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found.

Rebase, please.

**Comment by W2jx** [comment]
Force-Push is just to resolve the conflict about file `modules/apps/application-list/application-list-api/bnd.bnd`

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(3/21 10:29)

**Review by dantewang — APPROVED** [review]

**Comment by W2jx** [comment]
no conflicts(2/23 15:51)

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4014

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by W2jx** [comment]
no conflicts(4/7 16:16)

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
