### PR TITLE
[TS] LPS-157252

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-157252

https://issues.liferay.com/browse/LPS-161024

Resent from https://github.com/liferay-core-infra/liferay-portal/pull/1406 since LPS-161024 was merged into master.  Original message:

> I'm sending these PRs together since they are related and the tests for LPS-157252 won't pass without the fix for LPS-161024.
> 
> Resent from https://github.com/liferay-core-infra/liferay-portal/pull/1175

> Split up main logic changes from SF changes, and added logic to make sure only control panel pages could set language from session's locale.

> This new solution includes an edge case fix where the control panel cannot have it's language translated.  By reading in the session locale, we can now adjust the locale of the given page if needed.

> In the scenario where the user is requesting their default language, the portal and user default language is the same, but the current virtualHost's default language is different, then the portal will still provide the URL without any language code.  This is because the portal is not taking into account the virtualHost's default language when (not) setting the i18nPath to the requested language.  Further, having a virtualHost default language works against the `LOCALE_PREPEND_FRIENDLY_URL_STYLE` 3 (which is the default value) because now the specified virtualHost (without languageId in the URL) only points to one language, instead of any available language.
> 
> With my changes, the portal now considers if the virtualHost has a default language, and will include a `i18nPath` value if the requested language is different.
> 
> Please let me know if you have any questions, thanks!

CC @crodriguezy

### CODE REVIEW

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@ChrisKian From your reproduce step: "Note that an alert message shows up and offers you the possibility to change the language: "Display the page in English (United States). Click on the option to change it."

So by clicking on the option, it means the default language of this site is changed? what's that alert for?

**Comment by ChrisKian** [comment]
Hey @tinatian, by clicking that option, you are simply displaying the page in English for the current session.  You are not changing the user default language, and you are not changing the site default language.

**Comment by tinatian** [comment]
@vicnate5 Do you know the expected behavior of clicking "Display the page in English (United States). Click on the option to change it." here? Is this one time thing? Please see the ticket description for the reproduced steps.

Also, do we have any test covered this?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@zhangyan0701 can you review the behavior here? See above comment.

**Comment by zhangyan0701** [comment]
@tinatian 

I think the expected behavior is that clicking "Display the page in English (United States). Click on the option to change it." only changes the current display language in page to make it same as the current user's default language. So it will be easier for this user to manege the site. And I think if the user logout, the page will change back to Spanish, if the login again, the alert will appear again.

But I tested with the bundle that generated from here https://github.com/liferay-core-infra/liferay-portal/pull/1803#issuecomment-1258551580, [LPS-157252](https://issues.liferay.com/browse/LPS-157252) was still reproducible. So I didn't get the expected behavior of the ticket. @ChrisKian 

And we don't have functional test to cover the case currently.

**Comment by vicnate5** [comment]
@catarineaguiar Could you work on some Poshi tests to cover the test scenarios here and in the ticket?

**Comment by tinatian** [comment]
@catarineaguiar Based on @zhangyan0701 's comment, I changed this pull from QA Passed to QA Failed.

**Comment by ChrisKian** [comment]
Resent here: https://github.com/liferay-core-infra/liferay-portal/pull/1872

**Pull request closed without merging**
