### PR TITLE
[Spring Beans] LPS-200192 Move RepositoryProviderImpl, LiferayFileEntrySocialActivityManager, LiferayFileShortcutSocialActivityManager and LiferayFolderSocialActivityManager into module

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian 
I have moved RepositoryProviderImpl out into modules, and made RepositoryProviderUtil use Snapshot to fetch the real service

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5987

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(11/17 8:18)

**Comment by W2jx** [comment]
no conflicts(11/20 13:57)

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
@W2jx startup failure due to:

```
[beanshell] 2023-11-20 10:25:27.727 ERROR [SystemExecutorServiceUtil-1-Portal Spring Init Thread][PortalBeanLocatorUtil:57] BeanLocator is null
[beanshell] 2023-11-20 10:25:27.743 ERROR [SystemExecutorServiceUtil-1-Portal Spring Init Thread][ContextLoader:225] Context initialization failed
[beanshell] org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.portal.kernel.security.permission.ResourceActions' defined in class path resource [META-INF/security-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.portal.kernel.service.PortletLocalService' defined in class path resource [META-INF/portal-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.portal.kernel.service.CompanyLocalService' defined in class path resource [META-INF/portal-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.document.library.kernel.service.DLFileEntryTypeLocalService' defined in class path resource [META-INF/portal-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.document.library.kernel.service.DLAppHelperLocalService' defined in class path resource [META-INF/portal-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.asset.kernel.service.AssetCategoryLocalService' defined in class path resource [META-INF/portal-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.portal.kernel.service.ResourceLocalService' defined in class path resource [META-INF/portal-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.portal.kernel.service.ResourcePermissionLocalService' defined in class path resource [META-INF/portal-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.portal.kernel.service.RoleLocalService' defined in class path resource [META-INF/portal-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.expando.kernel.service.ExpandoRowLocalService' defined in class path resource [META-INF/portal-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.expando.kernel.service.ExpandoTableLocalService' defined in class path resource [META-INF/portal-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.expando.kernel.service.ExpandoColumnLocalService' defined in class path resource [META-INF/portal-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.portal.kernel.service.SystemEventLocalService' defined in class path resource [META-INF/portal-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.portal.kernel.service.GroupLocalService' defined in class path resource [META-INF/portal-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.document.library.kernel.service.DLAppLocalService' defined in class path resource [META-INF/portal-spring.xml]: Initialization of bean failed; nested exception is com.liferay.portal.kernel.bean.BeanLocatorException: BeanFactory could not find bean: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'com.liferay.portal.kernel.repository.RepositoryProvider' available
[beanshell] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:816)
[beanshell] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1288)
[beanshell] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
[beanshell] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:277)
[beanshell] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
[beanshell] 	at com.liferay.portal.spring.bean.BeanReferenceAnnotationBeanPostProcessor._autoInject(BeanReferenceAnnotationBeanPostProcessor.java:113)
[beanshell] 	at com.liferay.portal.spring.bean.BeanReferenceAnnotationBeanPostProcessor.postProcessBeforeInitialization(BeanReferenceAnnotationBeanPostProcessor.java:68)
[beanshell] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8705/functional-smoke-startup-tomcat90-mysql57-jdk8/0/23/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
