### PR TITLE
Lps 157718 whitelist

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by Kvale1733** [comment]
@shuyangzhou Relevant failed out due to 

`/opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/setup/SetupWizardUtil.java:531: error: incompatible types: cannot infer type arguments for HashSet<>
 [parallel]       _driverClassNames = new HashSet<>(properties.values());
 [parallel]                                      ^
 [parallel]     reason: inference variable E has incompatible bounds
 [parallel]       equality constraints: String
 [parallel]       lower bounds: Object
 [parallel]   where E is a type-variable:
 [parallel]     E extends Object declared in class HashSet`

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by catarineaguiar** [comment]
@shuyangzhou no regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123829

**Pull request closed without merging**
