### PR TITLE
LPS-190920 Remove DSAccessTokenWebCacheItem

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from https://github.com/liferay-core-infra/liferay-portal/pull/5066
changed to use singleVM

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:digital-signature

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by julschong** [comment]
pushed only commit message change, no need for addtional ci tests

**Comment by julschong** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:forward

**Comment by julschong** [comment]
ci:forward:force

**Comment by julschong** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/138749

**Pull request closed without merging**
