### PR TITLE
LPS-148672

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

I have removed the deprecated in PropsKey.
Thanks for checking. Also see https://github.com/jeffwu0724/liferay-portal/pull/35.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by kyle-miho** [comment]
@jeffwu0724 failures should be unrelated, pr is good

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
