### PR TITLE
[OrderByComparator] LPD-26373 Clean up and Apply Singleton in module data-engine and dynamic-data-lists 

### PR DESCRIPTION
**Pull request by Valmir-unicap**
- Ticket: https://liferay.atlassian.net/browse/LPD-26373
- Correction of: https://github.com/liferay-core-infra/liferay-portal/pull/7022

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@Valmir-unicap Why this removal https://github.com/liferay-core-infra/liferay-portal/pull/7034/commits/2a262cba6ddcffbf198f99786001c8324876206f is not together with https://github.com/liferay-core-infra/liferay-portal/pull/7034/commits/5f885cd6e654a2a0f919ec07f9ec8aff333639aa

**Comment by Valmir-unicap** [comment]
I go organize my commits! Thx

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:report:2571664689

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:report:2572124029

**Comment by Valmir-unicap** [comment]
ci:report:2572124029

**Comment by Valmir-unicap** [comment]
I did “push” to remove the commit from SF, make it private the attributes

**Comment by Valmir-unicap** [comment]
I did the push to organize the commits

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
Reevaluating!
CC: @titokenzo

**Pull request closed without merging**
