### PR TITLE
LPD-29513 [portal] add support for local deployment of CX bundles to different virtual instances

### PR DESCRIPTION
**Pull request by annasuszter**
Hi Team,

I'd like to request your review of this PR for ticket https://liferay.atlassian.net/browse/LPD-24834 

This PR's purpose is to add the ability to the portal to continuously scan virtual instance specific subdirectories of the `osgi/client-extensions` folder and use the name of these subdirectories, which are set to the virtual instances' ids, to update the necessary files in the client extension modules before generating the WAB files.

The current approach is to check the existing virtual instances each time when the deploy folders are scanned and update the scanner's watchedDirs with these entries. 

I'd like to ask for your opinion and advice about the changes in the `portal-file-install-impl` module.

Thank you! 

cc @drewbrokke

### CODE REVIEW

**Comment by tinatian** [comment]
@annasuszter We have the same issue with portlet deployment as the client extension.

You only have one copy of source code for portlet, but you have different portlet instance for each company.

Client extension should follow the same rule rather than have multiple copies of source code.

**Comment by drewbrokke** [comment]
@tinatian in this case, we _only_ want to deploy to a single virtual instance at a time, and do not want to automatically replicate across virtual instances. The same copy of source code _can_ be re-used for different targets. That seems a little different from the Portlet context, where you don't necessarily need to indicate _which_ virtual instance you will be targeting. Am I incorrect in my assessment?

**Comment by drewbrokke** [comment]
@tinatian another of our requirements is that the `zip` file _should not_ contain any virtual-instance specific markers, it should be able to be deployed to _any_ virtual instance. This is in keeping with how it works when the deploy target is LXC.

**Comment by tinatian** [comment]
@drewbrokke 

> we only want to deploy to a single virtual instance at a time, and do not want to automatically replicate across virtual instances.
You should be able to achieve this goal by providing which virtual instance you want to deploy to. I still do not think it is necessary to deploy duplicated code source especially you say `the zip file should not contain any virtual-instance specific markers`

**Comment by drewbrokke** [comment]
> providing which virtual instance you want to deploy to

@tinatian this was the reason our logic watches specific sub-folders of the `client-extensions` directory, it was _how_ we indicated which VI we wanted. What do you have in mind for providing this information to the portal? Sorry if I'm misunderstanding.

**Comment by tinatian** [comment]
@drewbrokke This is just configuration, anything blocks you from using configuration file?

**Comment by tinatian** [comment]
@drewbrokke Basically, you should have a configuration file indicating which instances you want to install which client extension, then your client extend deployment logic just respect the configuration.

**Pull request closed without merging**
