### PR TITLE
[TS] LPS-202860

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

Manual test with the bug steps passed on Tomcat.

**Comment by yuhai** [comment]
@marianoalvarosaiz, please see the below suggestions:

For the fix, instead of using the if block to add "/" to `_portalWebDir`, we may use `new File(String parent, String child)` in the [code1](https://github.com/liferay-core-infra/liferay-portal/blob/95847b36eda630183e1325309797797988bdd5fd/portal-impl/src/com/liferay/portal/deploy/hot/CustomJspBagRegistryUtil.java#L146) and [code2](https://github.com/liferay-core-infra/liferay-portal/blob/95847b36eda630183e1325309797797988bdd5fd/portal-impl/src/com/liferay/portal/deploy/hot/CustomJspBagRegistryUtil.java#L161). For the code2, `FileUtil.write(String, InputStream) will invoke FileImpl#write(File, InputStream)`.  The api `new File(String parent, String child)` may ignore the "/".

For the test class, we need to clean up it.
1. Please merge `_testGetCustomJspBags()` and `_testGetGlobalCustomJspBags()` for the one method, I think we may call it `_testGetCustomJspBags(boolean customJspGlobal, String contextId, String contextName)`, and then use related method param to invoke it in the two test methods. During the process, please inline `_TEST_CUSTOM_JSP_BAG `and `_TEST_GLOBAL_CUSTOM_JSP_BAG` as method params.

2. For the `_TEST_DIRECTORY', let's use the real dir to test. For example,
```
      @Before
	public void setUp() throws IOException {
		_file = FileUtil.createTempFolder();
	}

	private File _file;

	@After
	public void tearDown() throws Exception {
		FileUtil.deltree(_file);
	}

       @Test
	public void testGetCustomJspBags() {
		_setUpServletContext(_file.getPath());

		_testGetCustomJspBags(false, "TEST_CUSTOM_JSP_BAG", "Test Custom JSP Bag");

		Assert.assertFalse(
			Files.exists(Paths.get(_file.getPath() + "html")));
		Assert.assertTrue(
			Files.exists(Paths.get(_file.getPath() + "/html")));
	}
```
3. Please inline `private ServletContext _servletContext` to the `_setUpServletContext()` because only this method uses it.

In addition, please remove the last commit(a348bf7f38decd2a27dadedd4960a9a3c57b4d10)

I am going to close the pr. Please resend it and let me know if you have other concerns.

Thanks,
Hai

**Comment by marianoalvarosaiz** [comment]
@yuhai see https://github.com/liferay-core-infra/liferay-portal/pull/6287

**Pull request closed without merging**
