### PR TITLE
LPS-177371 Remove Stream usages for module: commerce-product-ddm-impl

### PR DESCRIPTION
**Pull request by julschong**
resubmit from #3731 
@dantewang Hi Dante,

[LPS-177371 Add unit test to make sure _createDDMFormRuleInputMapping](https://github.com/liferay-core-infra/liferay-portal/pull/3930/commits/5b14a1a4cb19dd588ae80f4641251c2eef426e41), I chose to add unit test on the private method because, otherwise, it would become much more complex and may need to use many Mocks or Integration test. Is this OK?

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:commerce

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3941

**Pull request closed without merging**
