### PR TITLE
[Remove Stream/Optional usage] LPS-178729 module headless-commerce-admin-catalog-impl part 1

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-178729

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:headless

**Comment by JanisZhang** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
ci:forward

**Comment by dantewang** [comment]
cc @shuyangzhou @tinatian

**Pull request closed without merging**
