### PR TITLE
[Replace Non-Blocking Usage] LPS-199560

### PR DESCRIPTION
**Pull request by JanisZhang**
resent:https://github.com/liferay-core-infra/liferay-portal/pull/5842

https://liferay.atlassian.net/browse/LPS-199560

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142897

cc @shuyangzhou

**Pull request closed without merging**
