### PR TITLE
LPS-187216 Remove POP3 checkbox that enables the use of OAuth to POP3 connections

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
The related test failed here. Re-running to see if it is consistent

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Test passed https://testray.liferay.com/home/-/testray/case_results/2465900201

No regressions found.

**Comment by rafaprax** [comment]
ci:forward:force

/cc @tinatian

**Comment by tinatian** [comment]
@rafaprax why this is removed? could you please provide more info in the commit message?

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-core-infra/liferay-portal/pull/6397.

**Pull request closed without merging**
