### PR TITLE
LPS-197236 Merge PortletRequestWhiteList interface and impl into Util and move to portal-impl

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
rerunning to make sure

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Below WARN message thrown during portal startup:
```
2023-09-26 19:45:20.327 WARN  [main][DependencyManagerSyncUtil:73] Declarative Service Unsatisfied Component Checker check result: 
Bundle {id: 1248, name: com.liferay.multi.factor.authentication.web, version: 2.0.33}
	Declarative Service {id: 11105, name: com.liferay.multi.factor.authentication.web.internal.portlet.MFAVerifyPortlet, unsatisfied references: 
		{name: _interruptedPortletRequestWhitelistUtil, target: null}
	}
Bundle {id: 1261, name: com.liferay.multi.factor.authentication.email.otp.web, version: 2.0.29}
	Declarative Service {id: 11141, name: com.liferay.multi.factor.authentication.email.otp.web.internal.portlet.MFAEmailOTPVerifyPortlet, unsatisfied references: 
		{name: _interruptedPortletRequestWhitelistUtil, target: null}
	}
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-09/test-1-35/test-portal-acceptance-pullrequest(master)/4622/functional-tomcat90-mysql57-chrome100-jdk8/0/23/jenkins-console.txt.gz?authuser=0

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141495

**Pull request closed without merging**
