### PR TITLE
[Method References 2] LPS-176936 Convert method reference to field reference in class LiferayResourceOwnerAccessTokenGrantHandler

### PR DESCRIPTION
**Pull request by W2jx**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3682

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:oauth2

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(3/20 8:52)

**Comment by W2jx** [comment]
no conflicts(3/21 10:29)

**Comment by tinatian** [comment]
@W2jx You are doing this https://github.com/liferay-core-infra/liferay-portal/pull/3916/commits/af246cce045e8160c150851614fa02a5a72ecbaf because one of the filed is dynamic and you are using it to initialize ResourceOwnerGrantHandler, to make sure ResourceOwnerGrantHandler always keep the right value, you can not use a pre-initialized ResourceOwnerGrantHandler instance in activate method.

Please update your commit message.

**Comment by tinatian** [comment]
@W2jx For this https://github.com/liferay-core-infra/liferay-portal/pull/3916/commits/d0d7a2e7a9f8617f5163715f96be698b38710ead, what is the reason to remove?

**Pull request closed without merging**
