### PR TITLE
[Bug Fix]LPS-144437

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Code looks good to me, waiting for QA scanning test results.

Tina.

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian No regressions found

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/111758

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
