### PR TITLE
[Method References 2] LPS-164347 Remove unused reference variable in module saml-opensaml-integration(dxp)

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have removed unused reference variable in module saml-opensaml-integration(dxp).

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@W2jx `DefaultUserResolverTest` has logic to use reflection to set fields like `_metadataManager`, please update the test to remove the field setting logic for fields you removed from `DefaultUserResolverTest`. Also pay attention to see if other classes you modified have tests. Please resend.

@zhangyan0701 Do you know why CI passed in this case? `DefaultUserResolverTest` should fail to run with this PR.

cc @vicnate5 @tinatian

**Comment by zhangyan0701** [comment]
@dantewang Test DefaultUserResolverTest failed in this PR, but it wasn't considered as a unique failure, but a common failure with acceptance upstream somehow. Maybe there are issues with the comparison of the results. I asked CI team to take a look in slack https://liferay.slack.com/archives/CL3TWSMHQ/p1665743622406619.

**Comment by dantewang** [comment]
@zhangyan0701 Thanks!

**Pull request closed without merging**
