### PR TITLE
LPS-172618 Remove Stream usages from module: users-admin-test

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:users

**Comment by zhangyan0701** [comment]
No regressions.

**Comment by julschong** [comment]
pushed last commit

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong No regressions. Just the sf issue
```
 [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/users-admin/users-admin-test/src/testIntegration/java/com/liferay/users/admin/search/test/UserGroupCascadeReindexUsersTest.java expected:<...te int _groupCount;
     [java] []  private int _userCo...> but was:<...te int _groupCount;
     [java] [
     [java] ]  private int _userCo...>
```

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
