### PR TITLE
[Remove Stream/Optional usage] LPS-175071 asset-categories-navigation-web

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend, use new method to transform long[] to list. Thanks!

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3456
https://issues.liferay.com/browse/LPS-175071

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
@JanisZhang It seems you and @julschong modified the same module... https://github.com/liferay-core-infra/liferay-portal/pull/3616

**Comment by dantewang** [comment]
@JanisZhang Closing this one because Tina asked for additional change and it's done in https://github.com/liferay-core-infra/liferay-portal/pull/3616.

**Pull request closed without merging**
