### PR TITLE
[Centralize PortletDisplayTemplateUtil ]Lps 184134

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-184134

In the head of master, these PortletDisplayTemplateUtil classes existed:

1. modules/apps/dynamic-data-mapping/dynamic-data-mapping-taglib/src/main/java/com/liferay/dynamic/data/mapping/taglib/internal/util/PortletDisplayTemplateUtil.java
2. modules/apps/roles/roles-admin-web/src/main/java/com/liferay/roles/admin/web/internal/util/PortletDisplayTemplateUtil.java
3. modules/apps/site-navigation/site-navigation-taglib/src/main/java/com/liferay/site/navigation/taglib/internal/portlet/display/template/PortletDisplayTemplateUtil.java
4. modules/apps/template/template-taglib/src/main/java/com/liferay/template/taglib/internal/util/PortletDisplayTemplateUtil.java

Item 1 and 2 were added by https://issues.liferay.com/browse/LPS-78629 which aims to remove exported package from portlet-display-template;
Item 3 was added by https://issues.liferay.com/browse/LPS-71325 which aims to avoid ModelAdaptorUtil type conversions from module DDMTemplate to kernel DDMTemplate and back to module DDMTemplate in NavigationTag;
Item 4 was added by https://issues.liferay.com/browse/LPS-137945 which just copied a module to another.

Lily

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:roles

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@slnn No regressions.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
