### PR TITLE
[Remove immediate=true usage  lima Part II]Lps 168630

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-168630

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@slnn semver error:

```
  [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/message-boards/message-boards-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.message.boards.service.permission      CHANGED    1.1.0      1.1.0      1.1.1      VERSION INCREASE REQUIRED
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-26/test-portal-acceptance-pullrequest(master)/6056/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Thank @catarineaguiar for catching this! Retrigger the tests after fix the semantic version, no logic changes

**Comment by tinatian** [comment]
@slnn Please always remember to remove QA Passed flag when you retrigger the tests.

Tina

**Comment by catarineaguiar** [comment]
no regressions

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126775

**Comment by austinchiang** [comment]
@slnn @catarineaguiar FYI tests [here](https://github.com/liferay-core-infra/liferay-portal/pull/2516#issuecomment-1324537653) caught https://issues.liferay.com/browse/LPS-169782

**Comment by slnn** [comment]
Thank @austinchiang for catching this! I will check it.

**Pull request closed without merging**
