### PR TITLE
[Components with more than 1 service] LPS-187086 Refactor components from portal-workflow-kaleo-runtime-impl and oauth2-provider-scope-impl modules

### PR DESCRIPTION
**Pull request by dantewang**
https://github.com/liferay-core-infra/liferay-portal/pull/4999

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:workflow

**Comment by dantewang** [comment]
ci:test:oauth2

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138045

**Pull request closed without merging**
