### PR TITLE
LPS-158017 Remove deprecated methods in BasePortalCacheManager

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar
Hi Catarine,
Could you please help me scan the test result?
Thank you!

**Comment by tinatian** [comment]
@julschong Code looks good to me, wait for QA to scan test results.

Tina.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/120559

**Pull request closed without merging**
