### PR TITLE
[Method References 3] LPS-179499 roles-admin-web

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-179499
previous: https://github.com/liferay-core-infra/liferay-portal/pull/4193

Changes in this pull:
- change to use  FrameworkUtil.getBundle ...

Thanks!

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:roles

**Comment by zhangyan0701** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by JanisZhang** [comment]
Hi @dantewang, I dropped one simplify commit. Thanks! cc @Kvale1733

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:roles

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
