### PR TITLE
LPS-144202

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Code looks good to me, waiting for QA to scan test results.

Tina.

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian No regressions found.

Note: [1 unique test failure](https://testray.liferay.com/home/-/testray/case_results/1595404444). But this test passed when I ran it locally.

**Comment by tinatian** [comment]
@shuyangzhou This is good to go.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
