### PR TITLE
[PowerMock] LPS 151823

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This pr is to remove powermock usages present in `BaseDDMFormFieldTypeSettingsTestCase` and its related class located in `dynamic-data-mapping-form-field-type`.

https://issues.liferay.com/browse/LPS-151823

Thanks for checking.

### CODE REVIEW

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
@tinatian Just found one commit caused some error, so I dropped it.

**Comment by tinatian** [comment]
@JanisZhang What kind of error caused by your original commits? The original test results showed that unit tests passed.

Tina.

**Comment by JanisZhang** [comment]
Hi @tinatian, the original test result shows `compileTestJava failed`, so I drop the change make to `BaseDDMFormFieldTypeSettingsTestCase`,as we still have one test `DocumentLibraryDDMFormFieldTemplateContextContributorTest` contains powermock usages and looks hard to remove. And this test extends `BaseDDMFormFieldTypeSettingsTestCase` and need to implement power-mock.

**Comment by tinatian** [comment]
Thanks @JanisZhang for the update! I should have QA to scan test result next time.

Tina.

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
Hi, @tinatian and @JanisZhang, I need to re-run the acceptance to analyse the PR with all changes.

**Comment by catarineaguiar** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
@JanisZhang @tinatian no regressions found.

**Comment by JanisZhang** [comment]
Close, will resend.

**Comment by JanisZhang** [comment]
ci:close

**Pull request closed without merging**
