### PR TITLE
LPS-190899 8-29

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou Rebase and test compile fix of https://github.com/liferay-core-infra/liferay-portal/pull/5387

The last commit (sem ver) is just to get a clean CI result. It's not related to this PR.

### CODE REVIEW

**Comment by dantewang** [comment]
https://github.com/liferay-core-infra/liferay-portal/pull/5387#issuecomment-1696262592 -> https://github.com/liferay-core-infra/liferay-portal/pull/5411/commits/cdf78c69283627cadb4295da2c3f25599e516452

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:test:data-integration

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139921

**Pull request closed without merging**
