### PR TITLE
[Method References 3] LPS-181096 Convert method reference to field reference in LayoutSetLogoFormNavigatorEntry, DispatchTriggerResourceImpl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:data-integration

**Comment by zhangyan0701** [comment]
ci:test:echo

**Comment by W2jx** [comment]
no conflicts(4/7 16:38)

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(4/10 8:33)

**Comment by W2jx** [comment]
no conflicts(4/11 9:50)

**Comment by W2jx** [comment]
no conflicts(4/12 9:52)

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:forward

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
