### PR TITLE
[Component with its own class name as service type] LPS-199599 Refactor Components from Commerce modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-199599

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
@MrJohn1911 There is a startup error here
https://testray.liferay.com/reports/production/logs/2023-10/test-1-35/test-portal-acceptance-pullrequest(master)/4784/functional-smoke-tomcat90-mysql57-jdk8_stable/0/0/liferay-log.txt.gz?authuser=0

Steps to reproduce:
1. Start portal connected to MySQL (no special properties)

Can you take a look and resend?

**Pull request closed without merging**
