### PR TITLE
[TS] LPP-46016 > LPS-159182 Implement getMimeType for the CustomServletContextHelper

### PR DESCRIPTION
**Pull request by ces-totrinh**
Hi,
Please help us review this PR and leave your comments. Thanks.
Tickets:
https://issues.liferay.com/browse/LPP-46016
https://issues.liferay.com/browse/LPS-159182

cc: @hongvo2308

### CODE REVIEW

**Review by dantewang — APPROVED** [review]
@catarineaguiar Could you please review the test results after the tests finish? Thanks!

@tinatian Code change looks good to me, but I'm not sure whether it's appropriate to add unit/integration for this case.

**Comment by catarineaguiar** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
no regressions on relevant. Waiting for acceptance results.

**Comment by catarineaguiar** [comment]
@tototrinh no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121231

**Pull request closed without merging**
