### PR TITLE
[Components with more than 1 service] LPS-192654 Refactor SXPParameterDataCreator component

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-193141](https://liferay.atlassian.net/browse/LPS-193141)

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@RenanUmV No regressions found.

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:search

**Comment by RenanUmV** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:search

**Comment by RenanUmV** [comment]
ci:test:stable

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-core-infra/liferay-portal/pull/5341

**Pull request closed without merging**
