### PR TITLE
[Method References 2] LPS-165285 Convert method reference to ServiceTrackerMap in class CompositeFacetProcessor(module portal-search-elasticsearch7-impl)

### PR DESCRIPTION
**Pull request by W2jx**
Hi @dantewang , I have resent it.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3769

### CODE REVIEW

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(3/23 15:56)

**Comment by W2jx** [comment]
no conflicts(3/24 14:48)

**Comment by W2jx** [comment]
no conflicts(3/27 9:41)

**Pull request closed without merging**
