### PR TITLE
[Method References] LPS-160434 Convert method references to field references in class extends BasePanelApp

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have fixed the null-check-problem mentioned in the [previous pr's comments](https://github.com/liferay-core-infra/liferay-portal/pull/1764).

Detial: https://github.com/liferay-core-infra/liferay-portal/pull/1764

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by W2jx** [comment]
Hi @catarineaguiar , Could you please help me check the test results ? Thanks!

**Comment by catarineaguiar** [comment]
@W2jx regression found:

```
  [exec] com.liferay.application.list.deploy.hot.test.LegacyPortletPanelAppHotDeployListenerTest > testLegacyPortletWithControlPanelEntry FAILED
     [exec]     java.lang.IllegalArgumentException: Portlet is null
     [exec]     	at com.liferay.application.list.adapter.PortletPanelAppAdapter.<init>(PortletPanelAppAdapter.java:36)
     [exec]     	at com.liferay.application.list.deploy.hot.LegacyPortletPanelAppHotDeployListener.invokeDeploy(LegacyPortletPanelAppHotDeployListener.java:81)
     [exec]     	at com.liferay.application.list.deploy.hot.test.LegacyPortletPanelAppHotDeployListenerTest.testLegacyPortletWithControlPanelEntry(LegacyPortletPanelAppHotDeployListenerTest.java:73)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
```
```
 [junit] Portal log assert failure, see above log for more information: 
    [junit] Table 'lportal.User_x_43958' doesn't exist
    [junit] junit.framework.AssertionFailedError: 
    [junit] Table 'lportal.User_x_43958' doesn't exist
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:171)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:86)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-28/test-portal-acceptance-pullrequest(master)/4481/modules-integration-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
Force-Push is just to rebase and fix the problem mentioned in comment.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
Hi @zhangyan0701  , Could you please help me check the test results ? Thanks!

**Pull request closed without merging**
