### PR TITLE
LPS-196622 Merge HotDeploy interface and impl into Util in kernel

### PR DESCRIPTION
**Pull request by julschong**
@shuyangzhou 
This is used in release repo but it has kernel usages anyway.
Shouldn't need to update release repo since Util is staying in kernel

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong No regressions found. Just need to rebase to fix the conflict.

**Comment by julschong** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142168

**Pull request closed without merging**
