### PR TITLE
[TS] LPD-2110 getLocalizedFriendlyURL method was generating an invalid URL that contained multiple language IDs in it in some cases 

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPD-2110](https://liferay.atlassian.net/browse/LPD-2110)

Please see the previous discussion on https://github.com/liferay-core-infra/liferay-portal/pull/6442

### CODE REVIEW

**Comment by tinatian** [comment]
@mbowerman Why the request URI may already have a different language ID? 
I really do not like the manipulation of string fix at https://github.com/liferay-core-infra/liferay-portal/pull/6600/commits/e38dd93dc798c9420492ab8738eca8b91f2b65cf. It is really hard to maintain.

Could you please go deep into and see why we are appending  two language IDs and avoid the wrong one to be appended?

Please resend.

FYI @ericyanLr 

Thanks.
Tina

**Comment by ericyanLr** [comment]
Hi @mbowerman ,

**Regarding:**
> This seems like a worse approach to me. Always removing the group friendly URL no matter what would prevent us from being able to preserve the URL format. For example, this approach would cause a URL of the form http://localhost:8080/web/guest/home to redirect to http://localhost:8080/home, which might be considered an unexpected behavior.

From my testing, I wasn't able to reproduce the scenario, where navigating to **http://localhost:8080/web/guest/home** would redirect to **http://localhost:8080/home**. 
- From my understanding, this is avoided by the logic in [FriendlyURLServlet.java#L308-L311](https://github.com/liferay/liferay-portal/blob/7.4.3.111-ga111/modules/apps/friendly-url/friendly-url-service/src/main/java/com/liferay/friendly/url/internal/servlet/FriendlyURLServlet.java#L308-L311), which decides whether it calls **portal.getLocalizedFriendlyURL**
- For this scenario, it does not end up calling that method

**Regarding:**

> I wasn't able to find out why we strip the group friendly URL from the I18nFilter, as the code to do so was added so long ago that it is from [the commit](https://github.com/liferay/liferay-portal/commit/6787514ed866631270605cc497718a56810bda8b) where we initially added the I18Filter class. I also wasn't able to figure out what the I18nFilter was even meant to be doing, because the breakpoint wasn't even reached when I added a breakpoint to the processFilter method and tried to visit some pages. Do we even have the I18nFilter configured to be part of the filter chain by default anymore?

It might be due to caching or something, for my testing, I usually open a new private browser tab to navigate to a page, and the breakpoint hits at the method: **getRedirect**.

**Regarding:**

> Regardless, I think that it would be best to be careful to preserve the existing behavior as closely as possible in cases where it appears to make sense or be correct, because otherwise, we risk giving customers a nasty surprise if they were dependent on the existing behavior of preserving the URL format. So for that reason, I would like to continue taking the original request URI into consideration when running the method, so that we can preserve the URL format with regards to whether /[servletMapping]/[friendlyURL] is included in the request or not.

I wasn't able to reproduce the scenario you mentioned, but I do understand what you mean. It would be best if we can make sure the friendlyURL redirects are correct, hopefully we have enough tests to provide coverage for the expected URL format. 

Liferay's friendlyURLs are quite complicated as you already know, with the extra portal properties and such.

**Thoughts**
One thing to note is that it appears the method: **portal.getLocalizedFriendlyURL** was introduced for the usage of **FriendlyURLServlet** and appears to only be used by the **FriendlyURLServlet**.

If this is only utilized by FriendlyURLServlet, maybe we can inline or move the logic to **friendly-url-service** module. I think much of the confusion comes from trying to determine what should be the expected value from this method. It's possible we may need to improve the naming or parameters for this method after analyzing how the **FriendlyURLServlet** utilizes this method and the logic as a whole.

Here is a link to the code I used for testing with the i18nFilter logic, in case it's helpful:
- Branch: https://github.com/ericyanLr/liferay-portal/tree/LPD-2110_POC
- Compare: https://github.com/ericyanlr/liferay-portal/compare/master...ericyanLr:liferay-portal:LPD-2110_POC

Please let me know if you have any additional questions.
Hope this helps.

**Comment by mbowerman** [comment]
Hello @tinatian, @ericyanLr,

> Why the request URI may already have a different language ID?

It can have a different language ID because there is no guarantee about what type of URL the user may attempt to visit. So, they may attempt to visit a URL that includes a language ID that is not present on the Site. If this happens, and the portal property `locale.use.default.if.not.available=true` is set, then Liferay will automatically attempt to direct them to the default locale instead. So in this case, the locale that we render the page in will be different than the language ID from the original request.

> I really do not like the manipulation of string fix at https://github.com/liferay-core-infra/liferay-portal/commit/e38dd93dc798c9420492ab8738eca8b91f2b65cf. It is really hard to maintain.

I do not see how it is hard to maintain. It is relatively straightforward, especially in comparison to the fix that Eric is proposing. All we are doing is essentially adding another `if` condition to strip out the existing locale from the URL if it already has one.

> Could you please go deep into and see why we are appending two language IDs and avoid the wrong one to be appended?
We never append two language IDs. What we are doing is appending one language ID to a URL that already has a language ID.

> From my testing, I wasn't able to reproduce the scenario, where navigating to http://localhost:8080/web/guest/home would redirect to http://localhost:8080/home.
> 
> From my understanding, this is avoided by the logic in [FriendlyURLServlet.java#L308-L311](https://github.com/liferay/liferay-portal/blob/7.4.3.111-ga111/modules/apps/friendly-url/friendly-url-service/src/main/java/com/liferay/friendly/url/internal/servlet/FriendlyURLServlet.java#L308-L311), which decides whether it calls portal.getLocalizedFriendlyURL
> For this scenario, it does not end up calling that method

OK fine, I misspoke. Visiting the specific URL http://localhost:8080/en-US/web/guest/home, under the conditions described by the steps of [LPD-2110](https://liferay.atlassian.net/browse/LPD-2110), would cause the URL to get modified to http://localhost:8080/en-GB/home with your approach, which I think would be an unexpected behavior.

> It might be due to caching or something, for my testing, I usually open a new private browser tab to navigate to a page, and the breakpoint hits at the method: getRedirect.

I've always been creating new private browser windows for my testing on this ticket, and I've never seen it hit the breakpoint in `I18nFilter.getRedirect` or `I18nFilter.processFilter` once when performing step 4 on [LPD-2110](https://liferay.atlassian.net/browse/LPD-2110).

Anyway, the reason I asked about this, is because I wanted to know whether the `I18nFilter` takes place _before_ or _after_ the `VirtualHostFilter`. The `VirtualHostFilter` is responsible for rewriting the URL in the request. This being the case, if the `I18nFilter` takes place _before_ the `VirtualHostFilter` does, then there would be no need for the `I18nFilter` to even consider the original request, as it would be the same as the current request.

The `PortalImpl.getLocalizedFriendlyURL` method, on the other hand, is always being called _after_ the `VirtualHostFilter`. So, if we want to preserve the original format of the user's URL (since the URL returned by this method may be displayed to the end user), then we NEED to take the original servlet request into account. Failure to do so will result in the rewritten URL from the `VirtualHostFilter`, and as far as I understand, the `VirtualHostFilter` is only rewriting that URL for internal purposes and not because it means to display the rewritten URL to the end user.

> I wasn't able to reproduce the scenario you mentioned, but I do understand what you mean. It would be best if we can make sure the friendlyURL redirects are correct, hopefully we have enough tests to provide coverage for the expected URL format.
> 
> Liferay's friendlyURLs are quite complicated as you already know, with the extra portal properties and such.

Yes, and this is part of why I believe my fix is safer. My fix removes a language ID segment from the URL, and _only in cases where we KNOW that we are about to add another language ID segment back into the same part of the URL_. Your fix removes the group friendly URL and servlet mapping from the URL in all cases where this method is called, which is something that we may not want to do in some cases.

> Here is a link to the code I used for testing with the i18nFilter logic, in case it's helpful:
> 
> Branch: https://github.com/ericyanLr/liferay-portal/tree/LPD-2110_POC
> Compare: https://github.com/ericyanLr/liferay-portal/compare/master...ericyanLr:liferay-portal:LPD-2110_POC

I tested your fix using the steps on [LPD-2110](https://liferay.atlassian.net/browse/LPD-2110). While it does fix the exact issue there, it also causes the URL http://localhost:8080/en-US/web/guest/test-page to redirect to http://localhost:8080/en-GB/test-page (in other words, not preserving the `/web/guest` in the URL) as I expected.

**Comment by mbowerman** [comment]
Hello @tinatian and @ericyanLr,

It's clear that we're simply not going to see eye-to-eye on this. I believe my fix is the most straightforward and safe approach for resolving this issue, but it's clear that you do not feel the same way. What do you think of the possibility of reassigning [LPP-52032](https://liferay.atlassian.net/browse/LPP-52032) to your team so that you can fix this issue yourselves rather than having all this back-and-forth, because the stakeholders on that LPP are already upset about the length of time that this has taken?

**Pull request closed without merging**
