### PR TITLE
LPS 162706 10 27 3

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-162706
cc: @ericyanLr

### CODE REVIEW

**Comment by kyle-miho** [comment]
Adding more cases in a follow up pull, so we can at least get the fix in first

**Comment by ericyanLr** [comment]
Hi @kyle-miho ,

Can you also help double check if the steps in LPS-113749 still works with this fix?

**Comment by Kvale1733** [comment]
@kyle-miho No regressions found. 

@ericyanLr I tested LPS-113749 and it still works.

**Comment by kyle-miho** [comment]
ci:close 
I am going to resend with the full amount of tests so we can be sure all of the functionality works at once.

**Pull request closed without merging**
