### PR TITLE
[Components with more than 1 service] LPS-202951 Refactor JournalContentImpl component

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://liferay.atlassian.net/browse/LPS-202951

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:clustering

**Comment by dantewang** [comment]
ci:test:echo

**Review by dantewang — APPROVED** [review]

**Comment by rafaprax** [comment]
ci:test:echo

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:stop:search

**Comment by rafaprax** [comment]
ci:test:echo

**Comment by rafaprax** [comment]
ci:test:echo

**Comment by rafaprax** [comment]
ci:stop:echo

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
