### PR TITLE
[LogContext]LPS-145235

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by jkappler** [comment]
Thanks @tinatian!

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@jkappler @tinatian This is still breaking the existing functional tests. If this is an intentional change, how can I adapt the tests to check the configuration from [AuditLogContextConfiguration.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-security-audit/portal-security-audit-wiring/src/main/java/com/liferay/portal/security/audit/wiring/internal/configuration/AuditLogContextConfiguration.java
)? What is the new expected result of setting these values to true?

Steps to Reproduce:
1. Add config file `com.liferay.portal.security.audit.wiring.internal.configuration.AuditLogContextConfiguration.config`
```
enabled="true"
useIncomingXRequestId="true"
```
2. Start Portal
3. Execute curl `curl -X GET -H 'X-Request-Id:oYTPuXlcVmKgVLk0mhK3SH0d7RDbKn3ULmN8xaNn' http://localhost:8080/api/jsonws/user/get-user-by-email-address/company-id/email-address`

Steps copied from https://github.com/liferay-core-infra/liferay-portal/pull/322#issuecomment-1039490630

Upstream results:
```
ERROR [http-nio-8080-exec-10][JSONAction:84] {AuditLogContext{"clientIP":"127.0.0.1","companyId":"20099","emailAddress":"R/9kOVhgsdSYJB2QcGn2SbmMGYqVs7pTA7hwlAWFkME=","serverName":"localhost","sessionId":"S4NiSzZVuuljHaieN0nwUmqUquVWKu2v2XjV51iSwCU=","userId":"20127","virtualHostName":"localhost","xRequestId":"d397857a-98e8-402d-df34-87968f6f9ee8"}}
com.liferay.portal.kernel.security.auth.PrincipalException$MustHaveValidCSRFToken: User 20127 did not provide a valid CSRF token for com.liferay.portal.jsonwebservice.JSONWebServiceServiceAction:/user/get-user-by-email-address
```
This PR results:
```
ERROR [http-nio-8080-exec-10][JSONAction:84] null
com.liferay.portal.kernel.security.auth.PrincipalException$MustHaveValidCSRFToken: User 20127 did not provide a valid CSRF token for com.liferay.portal.jsonwebservice.JSONWebServiceServiceAction:/user/get-user-by-email-address
```

**Comment by jkappler** [comment]
@tinatian, as we mentioned, this will also depend on how we configured the logs right?

**Comment by tinatian** [comment]
@jkappler Yes, I think the best way is to fix the functional test which I am not familiar with, if you can fix it by yourself that would be good, if not, please list the test steps and Victor should be able to help to update. 

Thanks.
Tina.

**Comment by vicnate5** [comment]
If you can list the manual test steps I can update the functional tests.

**Comment by jkappler** [comment]
Hi @vicnate5, @tinatian, I'm unsure if we can change the layout pattern directly when the portal is running (without coding). The only method that I'm aware of is the one mentioned in the ticket:

- Copy the portal-impl/src/META-INF/portal-log4j.xml into bundles/tomcat/webapps/ROOT/WEB-INF/classes/META-INF
- Rename the file to portal-log4j-ext.xml
- Modify the first log appender to include the ThreadContext properties:

`<Configuration strict="true"> <Appenders> <Appender name="CONSOLE" type="Console"> <Layout pattern="%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%t][%c{1}:%L] %m%n %X" type="PatternLayout"/> </Appender>`

- Notice the %X in the Layout pattern. As documented in https://logging.apache.org/log4j/2.x/manual/thread-context.html, this option includes the full threadContext properties in the log.
- Start the portal
- Then enable the configuration

So I think that we are a bit stuck here.....the only thing that would come into my mind atm would be to have a special portal-log4j.xml for the CI with the changed pattern, but I asume this would be out of the question right?

**Comment by vicnate5** [comment]
I will take a look at this tomorrow. I don't expect any issues modifying the log4j.

**Comment by vicnate5** [comment]
Almost done with the test fix for this, will resend tomorrow.

**Comment by jkappler** [comment]
Thanks for the help @vicnate5!

**Comment by vicnate5** [comment]
Resent
https://github.com/liferay-core-infra/liferay-portal/pull/396

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
