### PR TITLE
LPS-192672 Remove portal-startup-monitor

### PR DESCRIPTION
**Pull request by julschong**
@vicnate5 @tinatian
This pull removes the entire module of portal-startup-monitor
I think this need some additional testing to make sure that ci no longer need it and can still release resource when the tasks hang and not exit to release the resources

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test

**Comment by Kvale1733** [comment]
Now that the CI issue is fixed I'm rerunning as there are many aborted tests.

**Comment by Kvale1733** [comment]
ci:test

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by tinatian** [comment]
ci:forward:force

FYI @shuyangzhou

**Pull request closed without merging**
