### PR TITLE
[Remove Stream/Optional: Phase 3] LPS-181884 

### PR DESCRIPTION
**Pull request by JanisZhang**
Remove stream usages in below modules:
- modules/apps/frontend-taglib/frontend-taglib-form-navigator
- modules/apps/portal-workflow/portal-workflow-kaleo-service
- modules/apps/portal/portal-dao-test
- modules/apps/user/user-test
- modules/dxp/apps/portal-workflow/portal-workflow-metrics-demo
- modules/dxp/apps/segments/segments-asah-connector
- portal-kernel/src/com/liferay/portal/kernel/json/JSONUtil.java

https://issues.liferay.com/browse/LPS-181884

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:forms

**Comment by catarineaguiar** [comment]
ci:test:echo-analytics-cloud

**Comment by catarineaguiar** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
ci:test:frontend

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by JanisZhang** [comment]
ci:forward:force

**Comment by JanisZhang** [comment]
Forwarding this as it's approved and passed QA review. cc @dantewang @shuyangzhou @tinatian

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
manually forward to https://github.com/brianchandotcom/liferay-portal/pull/133586

**Pull request closed without merging**
