### PR TITLE
LPS-157759 Check serviceContext.isIndexingEnabled before index the content

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
@catarineaguiar please help me check the results when they are ready, thanks!

**Comment by guilhermedcamacho** [comment]
Re-running test suites because many tests were aborted.

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:acceptance

**Comment by guilhermedcamacho** [comment]
Hey @catarineaguiar , unfortunately CI keeps aborting some tests. I think you can analyze acceptance by this [result](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1907103523) from yesterday. Thanks

**Comment by guilhermedcamacho** [comment]
I took a quick look and saw that the tests you mentioned before passed now. [FileEntryRemoteStagedModelDataHandlerTest](https://testray.liferay.com/home/-/testray/case_results/1907125528?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3Dcom.liferay.document.library.internal.exportimport.data.handler.test.FileEntryRemoteStagedModelDataHandlerTest%26testrayBuildId%3D1907103523%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) and [FileEntryRemoteStagedModelDataHandlerTest](https://testray.liferay.com/home/-/testray/case_results/1907125473?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3Dcom.liferay.document.library.internal.exportimport.data.handler.test.FileEntryStagedModelDataHandlerTest%26testrayBuildId%3D1907103523%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Comment by catarineaguiar** [comment]
@guilhermedcamacho yes, the last failures found were fixed, and no other regression was found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/120563

**Pull request closed without merging**
