### PR TITLE
[Components with more than 1 service] LPS-205601 Refactor LayoutDDMFormFieldTemplateContextContributor, ObjectEntryExtensionProvider and AnalyticsReportsPortlet Components

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-205601

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:stable

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@MrJohn1911 Please remove the related class names from property `source.check.JavaComponentAnnotationsCheck.allowedSelfRegistrationClassNames` in `source-formatter.properties`.

**Comment by MrJohn1911** [comment]
> @MrJohn1911 Please remove the related class names from property `source.check.JavaComponentAnnotationsCheck.allowedSelfRegistrationClassNames` in `source-formatter.properties`.

Hey @dantewang, Those classes are not in any `source-formatter.properties` file

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/147537

cc @tinatian

**Pull request closed without merging**
