### PR TITLE
Lps 140576 master

### PR DESCRIPTION
**Pull request by SamZiemer**
Resending with changes requested here: https://github.com/liferay-core-infra/liferay-portal/pull/47

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:default

**Comment by SamZiemer** [comment]
ci:test

**Comment by SamZiemer** [comment]
@kyle-miho, is the ci:test:default test failures related here? They do not look like they are.

@tinatian would you mind reviewing this when you get a chance?

**Comment by kyle-miho** [comment]
@tinatian @SamZiemer the ci:test failures are unrelated, the pr should be good from CI errors

**Comment by kyle-miho** [comment]
since this is adding an upgrade process, im going to run the upgrade suite just in case

**Comment by kyle-miho** [comment]
ci:test:upgrade

**Comment by SamZiemer** [comment]
ci:reevaluate:1297401_910

**Comment by SamZiemer** [comment]
Hi @kyle-miho, it looks like the upgrade test suite is also having issues, can you confirm?

**Comment by kyle-miho** [comment]
@SamZiemer pretty sure the issues are unrelated the pr should be fine

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/78

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
