### PR TITLE
[Components with more than 1 service] LPS-175891 Refactor DTOConverter components with more than 1 service type from object-admin-rest-impl module

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:objects

**Comment by daiazius** [comment]
ci:test:object

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@daiazius Please see https://github.com/liferay-core-infra/liferay-portal/pull/3530#issuecomment-1440935572. 

Please resend.

Tina

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
@daiazius No regressions found.

**Comment by daiazius** [comment]
Hey @tinatian, can you check this please? Thank you

**Comment by tinatian** [comment]
@daiazius Please see https://github.com/liferay-core-infra/liferay-portal/pull/3736. Please follow this pattern and apply to all other DTO? Also, please let the team know and make them follow same pattern.

Thanks.
Tina

**Pull request closed without merging**
