### PR TITLE
[Round 3 Method Reference]Lps 181008

### PR DESCRIPTION
**Pull request by dantewang**
For the last commit, manually tested with proxy path and steps in https://issues.liferay.com/browse/LPS-153905, no issue.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:smoke

**Comment by dantewang** [comment]
ci:test:frontend

**Comment by dantewang** [comment]
@tinatian This one follows the same pattern as `ThemeContributorTopHeadDynamicInclude`.

**Comment by slnn** [comment]
Hi @tinatian 

Without this pull, the method reference for `_portalWebResources` is with MULTIPLE in cardinality so it is also possible that when `TopHeadDynamicInclude`  is activated but _portalWebResources is not ready because MULTIPLE here means 0:n.  So it will also has the problem that if `_portalWebResources` is not ready, all the calculated URLs will be empty, and nothing is going to be included/rendered.

```
@Reference(
		cardinality = ReferenceCardinality.MULTIPLE,
		policy = ReferencePolicy.DYNAMIC
	)
	protected void addPortalWebResources(
		PortalWebResources portalWebResources) {

		String resourceType = portalWebResources.getResourceType();

		if (resourceType.equals(PortalWebResourceConstants.RESOURCE_TYPE_JS)) {
			_portalWebResources = portalWebResources;

			_rebuild();
		}
	}
```

Lily

**Pull request closed without merging**
