### PR TITLE
[System Properties]LPS-165123 Move some properties that moduleFramework needs during init | part 1

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have moved some properties that moduleFramework needs during init.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701  , Could you please help me check the test results ? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
Force-Push is just to resolve the conflict about file portal-kernel/bnd.bnd.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
Force-Push is just to resolve conflicts about semantic version.

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
Hi @Kvale1733 , Could you please help me check the test results ? Thanks!

**Comment by zhangyan0701** [comment]
@W2jx Please resolve the conflict and re-run relevant test.

**Comment by W2jx** [comment]
Force-Push is just to resolve conflicts about semantic version.

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125069

**Pull request closed without merging**
