### PR TITLE
LPS-138374 move xmpcore to shared-dependencies

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-138374.
i tried to move xmpcore to shared-dependencies.
Thanks for checking.

### CODE REVIEW

**Comment by Kvale1733** [comment]
@jeffwu0724 Regressionf found

Cannot blacklist component

Steps to reproduce:
      I. Go to System Settings > Module Container
      II. Add "com.liferay.portal.security.ldap.internal.authenticator.LDAPAuth" to Bundle Blacklist Symbolic Names and Save
      III. Go to Gogo shell in control panel
      IV. Execute command: "scr:info authenticator.LDAPAuth"
      
 Expected Results: Component state should be inactive
 Actual Results: Component state is Active

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found. That issue I described is on master too and not caused by this PR.

**Comment by jeffwu0724** [comment]
Thanks a lot! @Kvale1733

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
rebase, fixed code conflicts, and rerun the tests

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by tinatian** [comment]
ci:test:document

**Comment by tinatian** [comment]
ci:test:reports

**Comment by tinatian** [comment]
ci:test:depot

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127566

**Pull request closed without merging**
