### PR TITLE
[Reference cleanup]LPS-160968

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang,

This PR is to replace method setServletContext with field _servletContext in class extends BaseDynamicInclude. Thanks!
https://issues.liferay.com/browse/LPS-160968

Previous PR : https://github.com/liferay-core-infra/liferay-portal/pull/1391

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @catarineaguiar, Could you please help scan the test results? THX

**Comment by tinatian** [comment]
@JanisZhang Code looks good to me, wait for QA to scan test results.


Tina

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results? Thanks!

**Comment by dantewang** [comment]
@JanisZhang It seems the failures are relevant... Also seeing such kind of error messages in another PR. I'm going to close this one, please double check.

cc @tinatian @zhangyan0701

**Comment by zhangyan0701** [comment]
Below error thrown during portal startup:
`[beanshell] 2022-08-18 22:01:46.362 ERROR [com.liferay.portal.osgi.web.wab.extender.internal.WabFactory-BundleTrackerOpener][MyWorkflowInstancePortletTab:56] bundle com.liferay.portal.workflow.web:4.0.39 (295)[com.liferay.portal.workflow.web.internal.portlet.tab.MyWorkflowInstancePortletTab(6638)] : findField: Suitable but non-accessible field _servletContext in class com.liferay.portal.workflow.web.internal.portlet.tab.WorkflowInstancePortletTab, subclass of component class com.liferay.portal.workflow.web.internal.portlet.tab.MyWorkflowInstancePortletTab`

Full console:
https://testray.liferay.com/reports/production/logs/2022-08/test-1-38/test-portal-acceptance-pullrequest(master)/3091/functional-smoke-tomcat90-mysql57-jdk8_stable/0/0/jenkins-console.txt.gz?authuser=0

**Comment by JanisZhang** [comment]
Thank you @zhangyan0701

**Pull request closed without merging**
