### PR TITLE
LPS-150509 baseline

### PR DESCRIPTION
**Pull request by kyle-miho**

### CODE REVIEW

**Comment by kyle-miho** [comment]
@jeffwu0724 fyi there was a missing gw baseline on portal-upgrade-api from https://issues.liferay.com/browse/LPS-150509 Deprecation removal, fixed it in this pr

**Comment by jeffwu0724** [comment]
> @jeffwu0724 fyi there was a missing gw baseline on portal-upgrade-api from https://issues.liferay.com/browse/LPS-150509 Deprecation removal, fixed it in this pr

Cool, thank you @kyle-miho ! May I ask what how can I avoid missing gw baseline in the future PRs, please? I think I did auto semantic version, but seems like it didn't cover this.

**Comment by kyle-miho** [comment]
@jeffwu0724 i ran gw baseline on the module directly since i saw this failure upstream, from what i saw on slack and ci logs, it seems like
ant install-portal-snapshot
is the common way to baseline all, but i havent run it yet, so im not entirely sure if it works or not

**Comment by jeffwu0724** [comment]
> @jeffwu0724 i ran gw baseline on the module directly since i saw this failure upstream, from what i saw on slack and ci logs, it seems like ant install-portal-snapshot is the common way to baseline all, but i havent run it yet, so im not entirely sure if it works or not

Thanks a lot @kyle-miho

**Comment by kyle-miho** [comment]
fixed here: https://github.com/liferay/liferay-portal/commit/01f6d37e577a85c836e111278c5808da314794b2
closing

**Pull request closed without merging**
