### PR TITLE
[Components with more than 1 service] LPS-177035, LPS-176895, LPS-177028, LPS-177025

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-177035](https://issues.liferay.com/browse/LPS-177035),
[LPS-176895](https://issues.liferay.com/browse/LPS-176895),
[LPS-177028](https://issues.liferay.com/browse/LPS-177028),
[LPS-177025](https://issues.liferay.com/browse/LPS-177025)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:commerce

**Comment by RenanUmV** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@RenanUmV No regressions.

**Review by rafaprax — CHANGES_REQUESTED** [review]
Hey @RenanUmV, please reorder the commits so that the constants creation/update commits be immediately before their usage.

Thx

**Comment by RenanUmV** [comment]
Just changed the order of the commits

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
Hey @tinatian, @RenanUmV just reordered the commits to be more meaningful and rebased the branch. No logic changes. So, the test results are still valid.

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@RenanUmV No regressions.

**Pull request closed without merging**
