### PR TITLE
[TS] LPD-19928

### PR DESCRIPTION
**Pull request by ericyanLr**
**Previous PR:** https://github.com/liferay-core-infra/liferay-portal/pull/6765
**Ticket:** https://liferay.atlassian.net/browse/LPD-19928

**Changes made in this PR, as discussed:**
- Add test to expose issue
- Fix issue
- Extract logic to MailServiceImpl, since this is the only class that calls this method

**Note:** Did not do any additional refactoring to MailServiceImpl#getSession(long companyId)
- It looks like the method: **_createMailSession** is used to prepare the **default mail session** and would be used if no custom changes have been made to a company's mail settings
- The check for key: `PropsKeys.MAIL_SESSION_MAIL` is used to detect for saved custom mail settings and will return early if none are found
    - Reference: [MailServiceImpl.java#L104-L110](https://github.com/liferay/liferay-portal/blob/7.4.3.113-ga113/portal-impl/src/com/liferay/mail/service/impl/MailServiceImpl.java#L104-L110)
- If custom mail settings are found, the properties from the **default mail session** is used and modified accordingly
    - Reference: [MailServiceImpl.java#L133](https://github.com/liferay/liferay-portal/blob/7.4.3.113-ga113/portal-impl/src/com/liferay/mail/service/impl/MailServiceImpl.java#L133)

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:2550625244

**Comment by ericyanLr** [comment]
**Update**
Force pushed to add semver changes

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:stop

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
**ci:report analysis**
No unique failures, marking this as **QA Passed** and **Ready to Review (no regression)**

**Comment by ericyanLr** [comment]
ci:stop

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
Hi @tinatian ,

As discussed, I have simplified the test and have also tested locally. The test passes with the changes and the dataguard cleanup appears to be working, no extra entries in the PortalPreferences table.

**Additional Changes**
- I removed the semver commit, the same package and bnd.bnd changes were recently made by LPD-20659
    - https://github.com/liferay/liferay-portal/commit/07bd1b2584a12f66ce87975aa1f7001562ac7a8f

Also, re-running `ci:test:sf` to double check SF.

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/148407

**Pull request closed without merging**
