### PR TITLE
[Components with more than 1 service] LPS-188679 Refactor ModelListener components part I

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-188679

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:echo

**Comment by MrJohn1911** [comment]
ci:test:lima

**Comment by chaowang-123** [comment]
The failure is not related to this pr,  @slnn can you help add the QA Passed label?

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian @rafaprax

**Pull request closed without merging**
