### PR TITLE
LPS-178022 Cleanup SearchBar for optional removal

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
Some failures seem related:

**1. Error occurs when open Search Bar portlet configuration.**

https://user-images.githubusercontent.com/25576873/233637662-fd19c184-4813-4fc7-b16d-b3193613e15b.mp4

Error in portal console:
```
2023-04-21 12:33:07.322 ERROR [http-nio-8080-exec-6][PortletConfigurationPortlet:712] null
javax.portlet.PortletException: org.apache.jasper.JasperException: java.lang.IllegalArgumentException: PortletPreferences is not present
```

**2. Search Bar portlet becomes unavailable after changing the search scope to Let the user choose.**

https://user-images.githubusercontent.com/25576873/233639624-e7e4a31c-27c1-4da4-b200-742494a1d0a9.mp4

Error in portal console:
```
2023-04-21 12:45:59.374 ERROR [http-nio-8080-exec-10][render_portlet_jsp:131] null
java.lang.IllegalArgumentException: PortletPreferences is not present
```
**3. Integration test [com.liferay.depot.web.internal.search.bar.portlet.shared.search.test.DepotSearchBarPortletSharedSearchContributorTest](https://testray.liferay.com/home/-/testray/case_results/2276575713) failed with below error:**
```
##
## com.liferay.depot.web.internal.search.bar.portlet.shared.search.test.DepotSearchBarPortletSharedSearchContributorTest > testContributeWithConnectedGroupId
##

	java.lang.IllegalArgumentException: PortletPreferences is not present
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-04/test-1-39/test-portal-acceptance-pullrequest(master)/4357/modules-integration-mysql57-jdk8/0/3/com.liferay.depot.web.internal.search.bar.portlet.shared.search.test.DepotSearchBarPortletSharedSearchContributorTest.txt.gz?authuser=0

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by julschong** [comment]
pushed last 3 commits to fix test failures

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:search

**Pull request closed without merging**
