### PR TITLE
LPS-149151 Move commons-math3.jar to portal-tika module

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by koor4356** [comment]
Okay, thanks!

**Comment by koor4356** [comment]
ci:test:relevant

**Comment by koor4356** [comment]
@guilhermedcamacho 
I am retesting relevant test suites because most of the tests are failing before they run. Thanks!

**Comment by koor4356** [comment]
@guilhermedcamacho,
This looks good, thanks!

**Comment by tinatian** [comment]
@shuyangzhou This pull passed ci test, ready for review.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
