### PR TITLE
[Remove unused field] LPS-198884 search-experiences-service

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend, fixed test.
https://liferay.atlassian.net/browse/LPS-198884

previous: https://github.com/liferay-core-infra/liferay-portal/pull/5756

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by JanisZhang** [comment]
SF issue should be unrelated

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found

**Pull request closed without merging**
