### PR TITLE
[Components with more than 1 service] LPS-200589 Refactor ElasticsearchConnectionManager component and ElasticsearchClientResolver interface

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-200589

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Review by rafaprax — CHANGES_REQUESTED** [review]

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:search

**Comment by MrJohn1911** [comment]
ci:test:sf

**Pull request closed without merging**
