### PR TITLE
LPS-193979 Patch commons-logging 1.2 to replace log4j1 with log4j2

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, please see the ticket's description. https://liferay.atlassian.net/browse/LPS-193979

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@yuhai Regression found in S3 store test. This is the simplest way to reproduce by letting our scripts do the setup.

Steps to reproduce:
1. Download aws cli: https://aws.amazon.com/cli/
2. Add the following to portal-ext.properties ```dl.store.impl=com.liferay.portal.store.s3.S3Store```
3. Add these creds (as properties) to test.user.properties: https://share.1password.com/s#cBZkdJiffQf6UWdgxBx_zVXn4u0sOIkv1fKY--FQ6Kw
4. Also add the following to test.user.properties. Can be whatever value. We're just choosing a bucket id. For example
```s3.bucket.id=testBucket1```
5. Run ```ant -f build-test-s3-store.xml configure-aws-cli``` in source directory
6. Run ```ant -f build-test-s3-store.xml create-s3-bucketi``` in source directory
7. Run ```ant -f build-test.xml prepare-aws-s3-configurationi``` in source directory
8. Startup (The previous steps should have configures an aws s3 store connection)
9. Add a test blank site
10. Go to Documents & Media
11. Remember the repository ID (The ID is in the url, near the end id=...)
12. Try adding a document with JSON using by running the following command in /portal-web (Replace repository id)
```
curl -X POST -u 'test@liferay.com:test' -F 'externalReferenceCode=' -F 'repositoryId=33841' -F 'folderId=0' -F 'sourceFileName=Document_1.jpg' -F 'mimeType=image/jpeg' -F 'title=DM Document Title' -F 'urlTitle=' -F 'description=DM Document Description' -F 'changeLog=' -F 'file=@test/functional/com/liferay/portalweb/dependencies/Document_1.jpg' -F 'serviceContext={"addGroupPermissions" : true, "addGuestPermissions": true}' http://localhost:8080/api/jsonws/dlapp/add-file-entry
```

Expected Results: The document is added without issue
Actual Results: The following warn appears
```
    [exec]     ## Adding a 'File' with the following info using JSONWS:
     [exec]     ## * Title: DM Document Title
     [exec]     ## * Description: DM Document Description
     [exec]     Executing commands: curl -X POST -u 'test@liferay.com:test' -F 'externalReferenceCode=' -F 'repositoryId=33935' -F 'folderId=0' -F 'sourceFileName=Document_1.jpg' -F 'mimeType=image/jpeg' -F 'title=DM Document Title' -F 'urlTitle=' -F 'description=DM Document Description' -F 'changeLog=' -F 'file=@test/functional/com/liferay/portalweb/dependencies/Document_1.jpg' -F 'serviceContext={"addGroupPermissions" : true, "addGuestPermissions": true}' http://localhost:8080/api/jsonws/dlapp/add-file-entry
     [exec]     {"classNameId":"0","classPK":"0","companyId":"20096","createDate":1692852383678,"ctCollectionId":"0","custom1ImageId":"0","custom2ImageId":"0","description":"DM Document Description","expirationDate":null,"extension":"jpg","externalReferenceCode":"18a5978b-028b-a309-f31e-79e18ee5fb7b","extraSettings":"","fileEntryId":"34012","fileEntryTypeId":"0","fileName":"Document_1.jpg","folderId":"0","groupId":"33935","largeImageId":"0","lastPublishDate":null,"manualCheckInRequired":false,"mimeType":"image\/jpeg","modifiedDate":1692852383858,"mvccVersion":"1","name":"115","repositoryId":"33935","reviewDate":null,"size":"13229","smallImageId":"0","title":"DM Document Title","treePath":"\/","userId":"20123","userName":"Test Test","uuid":"18a5978b-028b-a309-f31e-79e18ee5fb7b","version":"1.0"}Finished executing commands.
     [exec] 
[beanshell] 2023-08-24 04:46:24.105 WARN  [liferay/adaptive_media_processor-4][S3AbortableInputStream:178] Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
[beanshell] 2023-08-24 04:46:24.106 WARN  [liferay/adaptive_media_processor-4][S3AbortableInputStream:178] Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
     [exec]     Buildfile: /opt/dev/projects/github/liferay-portal/build-test-s3-store.xml
[beanshell] 2023-08-24 04:46:24.352 WARN  [liferay/adaptive_media_processor-4][S3AbortableInputStream:178] Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
[beanshell] 2023-08-24 04:46:24.353 WARN  [liferay/adaptive_media_processor-4][S3AbortableInputStream:178] Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
     [exec]        [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1163660886.properties

```
[Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-40/test-portal-acceptance-pullrequest(master)/5411/functional-tomcat90-mysql57-chrome100-jdk8/1/2/jenkins-console.txt.gz?authuser=0)

**Comment by yuhai** [comment]
@Kvale1733, the issue may be not caused by the fix. S3AbortableInputStream used  org.apache.commons.logging.LogFactory to output log.

Before the fix, due to the module com.liferay.portal.store.s3 defined "not import !org.apache.log4j,\", commons-logging will use JDK logger to output, the warn log should output in the console.

After the fix, commons-logging will use log4j2 to output, the warn log should output in the console and liferay log files. Our test will check if the warn log existed in the log file. If existed, the test can't be passed.

I will ask @zhangyan0701 help me to confirm the case.

**Comment by yuhai** [comment]
@Kvale1733, I can't reproduce the issue on my local.

The Warning log is from aws-java-sdk-s3-1.12.262-sources\com\amazonaws\services\s3\internal\S3AbortableInputStream.java.
```
 @Override
    public void close() throws IOException {
        if (_readAllBytes() || isAborted()) {
            super.close();
        } else {
            LOG.warn(
                    "Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and " +
                    "may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input " +
                    "stream after use.");
            if (httpRequest != null) {
                httpRequest.abort();
            }
            IOUtils.closeQuietly(in, null);
        }
    }
```
As I mentioned in the [comment](https://github.com/liferay-core-infra/liferay-portal/pull/5365#issuecomment-1692682983), the WRANING log will be output in the console and liferay log files after the fix. Before the fix, the WRANING log should output in the console because it used JDK logger. 

During the debug process, I set the logger  **com.amazonaws.services.s3.internal.S3AbortableInputStream** and add the below codes in the bnd.bnd of modules\apps\portal-store\portal-store-s3. And then executing the WRNING log on purpose.
```
!org.apache.logging.log4j,\
!org.apache.logging.log4j.core,\
```
S3AbortableInputStream will use JDKLogger, **I find the WARNING won't output due to Tomcat jdk logger configuration**.

The logger **com.amazonaws.services.s3.internal.S3AbortableInputStream** default level is INFO, even though the WARNING log executed, it also shouldn't output WARNING log. During the test, did we set the the related Logger level? For example, set **com.amazonaws.services.s3.internal.S3AbortableInputStream** for WARN，or its parent logger **com.amazonaws.services.s3.internal** or **com.amazonaws.services.s3**... **com.amazonaws** set for WARN? If so, please set **com.amazonaws.services.s3.internal.S3AbortableInputStream** for INFO to solve the issue.

**Comment by zhangyan0701** [comment]
@yuhai 

I could reproduce the warn message locally using the bundle that generated in https://github.com/liferay-core-infra/liferay-portal/pull/5365#issuecomment-1691182145.
`WARN  [liferay/adaptive_media_processor-4][S3AbortableInputStream:178] Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.`

As you said, without your fix, if the warning occurs, the output should be in the console, right? I also tested with an upstream bundle that I built locally, but didn't see it. So looks that on the bundle that built on CI, the log level is changed to WARN, but I wasn't able to find out where it is changed.

**Comment by yuhai** [comment]
@zhangyan0701, thanks for your test.

> As you said, without your fix, if the warning occurs, the output should be in the console, right? 

Yes. But due to tomcat jdk logger configuration, the WARNING didn't output because no handlers was defined for the logger **com.amazonaws.services.s3.internal.S3AbortableInputStream**. So the issue can't be reproduced on master and it was exposed by the fix.

@Kvale1733, sorry, I made a mistake. When enable logger for INFO, WARN log will be output. I got the order wrong. If that ELSE block executed, the WARN log will be output. We should apply similar `LoggerTestUtil.ERROR` logic for the testcase. I will talk this with @zhangyan0701 to change the testcase.

Thanks,
Hai

**Pull request closed without merging**
