### PR TITLE
[Replace Non-Blocking Usage] LPS-197550 Replace non-blocking ServiceProxyFactory usages in class MainServlet

### PR DESCRIPTION
**Pull request by haydenzheng314**
Resend with Snapshot only
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5820
Ticket: https://liferay.atlassian.net/browse/LPS-197550
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@LisztLiszt No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
