### PR TITLE
[Components with more than 1 service] LPS-190402 Refactor StagingBarControlMenuJSPDynamicInclude component

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Related: https://liferay.atlassian.net/browse/LPS-190402

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Valmir-unicap** [comment]
ci:test:staging

**Comment by Kvale1733** [comment]
ci:test:staging

**Review by MrJohn1911 — APPROVED** [review]

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
