### PR TITLE
LPS-190146 Remove multiple configuration in TestComponent and turn on SF check

### PR DESCRIPTION
**Pull request by julschong**
@tinatian @kevhlee 
resubmitted from #5036
Kevin caught an issue with my last pull modifying property on the wrong file.
This pull changes `source-formatter.properties` so that only master is affected

### CODE REVIEW

**Comment by kyle-miho** [comment]
a lot of tests got aborted in relevant, rerunning

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong No regressions found. The aborted tests are caused by a timeout in a workflow test. It's not unique to this PR. Need to rebase due to conflicts though.

**Comment by julschong** [comment]
rebased to resolve conflict due to brian's license commit

**Comment by tinatian** [comment]
ci:forward:force

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
