### PR TITLE
LPS-142761

### PR DESCRIPTION
**Pull request by mbowerman**
Re-sent from https://github.com/liferay-core-infra/liferay-portal/pull/37

https://issues.liferay.com/browse/LPS-142761

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@Hijky can you test this PR with steps from https://github.com/liferay-core-infra/liferay-portal/pull/37#issuecomment-987181162?

I triggered a bundle build so you can download the tomcat bundle instead of building.

CC @zhangyan0701

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by Hijky** [comment]
> @Hijky can you test this PR with steps from [#37 (comment)](https://github.com/liferay-core-infra/liferay-portal/pull/37#issuecomment-987181162)?
> 
> I triggered a bundle build so you can download the tomcat bundle instead of building.
> 
> CC @zhangyan0701

following the steps in the  [#37 (comment)](https://github.com/liferay-core-infra/liferay-portal/pull/37) not reproducible it, it works correctly

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 The test seems finished, but no report is shown on this pull, could you please check the results?

Thanks.
Tina.

**Comment by mbowerman** [comment]
I added a semantic versioning commit.

**Comment by mbowerman** [comment]
ci:test

**Comment by mbowerman** [comment]
BTW it seems like the semantic versioning of util-taglib is failing too, but I think that's failing at HEAD, so I didn't update it here.

**Comment by vicnate5** [comment]
@tinatian The test results look good

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/111165

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
