### PR TITLE
LPS-187733 6-19

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@zhangyan0701 Could you prioritize this one as it's FP4? Thanks!

**Comment by zhangyan0701** [comment]
One failure seems related:

Test [com.liferay.change.tracking.internal.search.test.SearchCTTest]
(https://testray.liferay.com/home/-/testray/case_results/2355305624) failed due to ComparisonFailure.

`org.junit.ComparisonFailure: {"from":0,"size":10000,"query":{"bool":{"filter":[{"bool":{"must":[{"bool":{"must":[{"terms":{"groupId":["36902"]}},{"terms":{"scopeGroupId":["36902"]}}]}},{"bool":{"should":[{"bool":{"must":[{"term":{"entryClassName":{"value":"com.liferay.journal.model.JournalArticle"}}},{"term":{"head":{"value":"true"}}},{"term":{"head":{"value":"true"}}},{"terms":{"status":["0"]}},{"terms":{"status":["0"]}},{"bool":{"must_not":[{"terms":{"uid":["com.liferay.journal.model.JournalArticle_PORTLET_36915","com.liferay.journal.model.JournalArticle_PORTLET_36937"]}}],"should":[{"bool":{"must_not":[{"exists":{"field":"ctCollectionId"}}]}},{"terms":{"ctCollectionId":["0","120"]}}]}},{"bool":{"must_not":[{"terms":{"uid":["com.liferay.journal.model.JournalArticle_PORTLET_36915","com.liferay.journal.model.JournalArticle_PORTLET_36937"]}}],"should":[{"bool":{"must_not":[{"exists":{"field":"ctCollectionId"}}]}},{"terms":{"ctCollectionId":["0","120"]}}]}}]}}]}}]}}]}},"explain":false,"stored_fields":["content_zh_CN","entryClassPK","groupId","description_ca_ES","description_hu_HU","description_ar_SA","description_pt_BR","title_ja_JP","content_sv_SE","scopeGroupId","description_es_ES","content_fr_FR","modified","title_fi_FI","description_nl_NL","content_en_US","content_de_DE","defaultLanguageId","content_es_ES","content_ar_SA","version","companyId","content_nl_NL","title_sv_SE","description_en_US","description_sv_SE","title_en_US","title_de_DE","title_es_ES","description_ja_JP","content_fi_FI","description_fr_FR","description","description_de_DE","title_ar_SA","title","title_nl_NL","content","uid","title_pt_BR","assetTagNames","title_ca_ES","entryClassName","content_ca_ES","content_hu_HU","articleId","description_fi_FI","content_pt_BR","title_zh_CN","description_zh_CN","content_ja_JP","title_hu_HU","title_fr_FR"],"track_scores":true,"track_total_hits":2147483647}->->[] expected:<[[com.liferay.journal.model.JournalArticle_PORTLET_36967_FIELD_120, com.liferay.journal.model.JournalArticle_PORTLET_36982_FIELD_120]]> but was:<[[]]>`

Full console log:
https://testray.liferay.com/reports/production/logs/2023-06/test-1-29/test-portal-acceptance-pullrequest(master)/7497/modules-integration-mysql57-jdk8_stable/0/0/jenkins-console.txt.gz?authuser=0

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136771

**Pull request closed without merging**
