### PR TITLE
[Components with more than 1 service] LPS-192202 Refactor export-import components

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-192202

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:staging

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
In the last push, I just changed the commit messages

**Comment by catarineaguiar** [comment]
@MrJohn1911 regression found:

```
     [exec] > Task :apps:archived:export-import-resources-importer:compileJava FAILED
     [exec] 
     [exec] > Task :apps:archived:export-import-resources-importer:copyLibs SKIPPED
     [exec] > Task :apps:archived:export-import-resources-importer:copyCSS NO-SOURCE
     [exec] > Task :apps:archived:export-import-resources-importer:buildCSS NO-SOURCE
     [exec] > Task :apps:archived:export-import-resources-importer:processResources
     [exec] > Task :apps:archived:export-import-resources-importer:zipZippableResources UP-TO-DATE
     [exec] > Task :apps:dynamic-data-lists:dynamic-data-lists-api:autoUpdateXml SKIPPED
     [exec] > Task :apps:export-import:export-import-api:autoUpdateXml SKIPPED
     [exec] > Task :apps:wiki:wiki-api:autoUpdateXml SKIPPED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/archived/export-import-resources-importer/src/main/java/com/liferay/exportimport/resources/importer/internal/util/LARImporter.java:15: error: cannot find symbol
     [exec] import com.liferay.exportimport.kernel.service.ExportImportLocalServiceUtil;
     [exec]                                               ^
     [exec]   symbol:   class ExportImportLocalServiceUtil
     [exec]   location: package com.liferay.exportimport.kernel.service
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/archived/export-import-resources-importer/src/main/java/com/liferay/exportimport/resources/importer/internal/util/LARImporter.java:80: error: cannot find symbol
     [exec] 		ExportImportLocalServiceUtil.importLayouts(
     [exec] 		^
     [exec]   symbol:   variable ExportImportLocalServiceUtil
     [exec]   location: class com.liferay.exportimport.resources.importer.internal.util.LARImporter
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/archived/export-import-resources-importer/src/main/java/com/liferay/exportimport/resources/importer/internal/util/FileSystemImporter.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 2 errors
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-26/test-portal-acceptance-pullrequest(master)/12144/modules-compile-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:staging

**Comment by zhangyan0701** [comment]
Regression found.

**Export / Import doesn't work.** 

Example steps:
1. Add a site with a page, add any portlet into the page.
2. Go to Publishing > Export, export the site with the default configuration, download the lar file.
3. Add another site, go to Publishing > Import, import the lar file to the site.

Actual Result:
The pages aren't imported into the new site.

https://github.com/liferay-core-infra/liferay-portal/assets/25576873/ed57db44-473c-4591-b1ec-957fbee3793b

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:echo

**Comment by MrJohn1911** [comment]
ci:stop

**Pull request closed without merging**
