### PR TITLE
Lps 173444

### PR DESCRIPTION
**Pull request by shuyangzhou**
@achaparro Since we only allow up to one VerifyProcess per module, and the "verify.process.name" always matches declaring bundle's symbolic name.
There is no reason to have this "verify.process.name" anymore, we should just use VerifyProcess declaring bundle's symbolic name as the ServiceTrackerMap key.

Can you send a follow up for this?

### CODE REVIEW

**Comment by 111Anna** [comment]
Hi @shuyangzhou @achaparro, I recheck the PR on CE and DXP

Here are test results:

CE
Portal Version|GitId|Average Startup (ms)|%|Average Shutdown (ms)|%|Open File|Thread Create|Open Prepared Statement|Open SQL
--|--| --|--|--|--|--|--|--|--|
Baseline| dbfbc84| 22938.3 |- |3286.3|-| 1833 | 101 | 500| 1008 |
Baseline + PR-3316| - |  22970 |-0.1%| 3255.3|0.1%| 1834 | 101 | 498 | 1006 |


DXP
Portal Version|GitId|Average Startup (ms)|%|Average Shutdown (ms)|%|Open File|Thread Create|Open Prepared Statement|Open SQL
--|--| --|--|--|--|--|--|--|--|
Baseline| dbfbc84| 25156 |- |3885|-| 1989 | 113| 558| 1097 |
Baseline + PR-3316| - |  25279.3 |-0.5%| 3927.3|-1.0%| 1990 | 113 | 558 | 1095 |

**Comment by achaparro** [comment]
Hi @shuyangzhou,

Removing the verify.process.name makes sense. However I won't be able to work on it until the end of the week since I had a surgery this morning.

Thanks

**Comment by shuyangzhou** [comment]
@achaparro the DataRemovalTest/DataCleanupTest are failing due to DataCleanupUpgradeStepRegistrator has 2 configuration pids, which makes "ConfigurationPolicy.REQUIRE" requiring both configuration to present to work.

The 2 pids change was done by https://github.com/liferay/liferay-portal/commit/6d5f937f795d59fc7efb9cf22114ac0fda28d399

What's the reason to have 2 pids here? It is just one component.

**Comment by shuyangzhou** [comment]
ci:test:sf

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@achaparro I just realized, DataCleanupUpgradeStepRegistrator actually has nothing to do with upgrade framework, it should not be a UpgradeStepRegistrator at all. Therefore it can just be split into 2 pieces to receive their own configurations.

**Comment by achaparro** [comment]
@shuyangzhou  Preston decided to use Registrations for this feature. We had two components, each of them with one configuration since Mike Han, Dave and I  wanted to separate data clean up from.data removal. You merge into one single component to avoid having two registrators per module but we lost one UI window, that's why I ended using two configurations in the same component.

I can't check the code until I come back home but as long as we keep the use case of having two UI windows, it is fine to me.

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
Relevant is good, want to see upgrade results.

**Comment by Kvale1733** [comment]
@shuyangzhou Regression found

1) Import this 6.2.10.21 DB dump and run the upgrade tool: https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/6.2.10.21/data-archive/data-archive-portal-mysql.zip
2) Start the portal and go to System Settings > Upgrades > Data > Clenaup
3) Check "Clean up software catalog module data." and click Save

Expected Results: The "Clean up software catalog module data." option is unchecked and the cleanup process is triggered. The following appears in the console
```
[beanshell] 2023-02-07 00:41:35.661 INFO  [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.data.cleanup.internal.configuration.DataCleanupConfiguration)][UpgradeProcess:127] Upgrading com.liferay.data.cleanup.internal.upgrade.SoftwareCatalogUpgradeProcess
[beanshell] 2023-02-07 00:41:35.834 INFO  [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.data.cleanup.internal.configuration.DataCleanupConfiguration)][UpgradeProcess:145] Completed upgrade process com.liferay.data.cleanup.internal.upgrade.SoftwareCatalogUpgradeProcess in 180 ms
```
Actual Results: The The "Clean up software catalog module data." option remains checked and nothing appears in the console.  
Data removal can be triggered but the check also doesn't become unchecked after

**Comment by Kvale1733** [comment]
@shuyangzhou Regression found

1) Import this 6.2.10.21 DB dump and run the upgrade tool: https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/6.2.10.21/data-archive/data-archive-portal-mysql.zip
2) Start the portal and go to System Settings > Upgrades > Data > Clenaup
3) Check "Clean up software catalog module data." and click Save

Expected Results: The "Clean up software catalog module data." option is unchecked and the cleanup process is triggered. The following appears in the console
```
[beanshell] 2023-02-07 00:41:35.661 INFO  [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.data.cleanup.internal.configuration.DataCleanupConfiguration)][UpgradeProcess:127] Upgrading com.liferay.data.cleanup.internal.upgrade.SoftwareCatalogUpgradeProcess
[beanshell] 2023-02-07 00:41:35.834 INFO  [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.data.cleanup.internal.configuration.DataCleanupConfiguration)][UpgradeProcess:145] Completed upgrade process com.liferay.data.cleanup.internal.upgrade.SoftwareCatalogUpgradeProcess in 180 ms
```
Actual Results: The The "Clean up software catalog module data." option remains checked and nothing appears in the console.  

Note: The chosen option also doesn't become unchecked in Data Removal but it seems the process is triggered unlike Data Cleanup.

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by shuyangzhou** [comment]
@Kvale1733 pushed a fix, please try again, thanks!

**Comment by Kvale1733** [comment]
@shuyangzhou So the same test is failing again because the checked option doesn't automatically uncheck after running the cleanup. Can reproduce with just these steps.

1) Start the portal and go to System Settings > Upgrades > Data > Cleanup
2) Click on any cleanup option and click save

Expected Results: The checked option automatically becomes unchecked after clicking save.

Actual Results: The checked option remains checked after clicking save.

The test (DataCleanupt#UIConfigsWillTriggerCleanupAndBeSetToFalseAfterExecution) indicates this is the intended behavior and I confirmed this it how it works on master. This issue appears only in this PR.

**Comment by shuyangzhou** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@shuyangzhou No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129925

**Pull request closed without merging**
