### PR TITLE
LPS-172438 upgrade xstream to 1.4.20

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-172438.
Thanks for checking!

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:export-import

**Comment by Kvale1733** [comment]
ci:test:drools

**Comment by Kvale1733** [comment]
ci:test:gradle-plugins

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
fixed the code conflict by auto-generate, the previous test should be good

**Comment by jeffwu0724** [comment]
`java.io.IOException: Server returned HTTP response code: 504 for URL: https://search.maven.org/solrsearch/select?q=g:org.ow2.asm+AND+a:asm-util&core=gav&rows=200&wt=json`

This link show "504 Gateway Time-out" 8:44am 2/1/2023

**Comment by tinatian** [comment]
@jeffwu0724 Please rebase

**Comment by jeffwu0724** [comment]
@tinatian fixed the code conflict by auto-generate, the previous test should be good

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129624

**Pull request closed without merging**
