### PR TITLE
LPS-150820 Move petra-io-delta to Inline in sync-service

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,

Main Task: [LPS-147928 Remove petra jar from modules/apps](https://issues.liferay.com/browse/LPS-147928)
Sub Task: [LPS-150820 Move petra-io-delta to Inline in sync-service](https://issues.liferay.com/browse/LPS-150820)

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
@kyle-miho
Hi Kyle, 
Could you please help me scan this test result?
Thank you!

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
failures should be unrelated, most likely from the extra commits in this pr due to rebase

**Comment by julschong** [comment]
@tinatian Hi Tina,
Could you please help me review this PR?
Thank you!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

@julschong Next time, when you inline something into a module, please make sure to move it to **internal** packages, I will accept your code this time as the module you modified had been archived.

Tina.

**Pull request closed without merging**
