### PR TITLE
LPS-143632 Remove LanguageUtil usages in portal module

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by tinatian** [comment]
@julschong Code looks good to me, wait for QA to scan test result.

Tina

**Comment by tinatian** [comment]
@catarineaguiar Please help me to scan test results.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
@julschong @tinatian no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by julschong** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121408

**Pull request closed without merging**
