### PR TITLE
LPS-149258 move poi to shared-dependencies with version 5.2.2

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

As we talked, I have
- Move poi related stuff out to separate module with version 5.2.2, use lite rather than full
- Upgrade tika to 1.28.5
- upgrade all the necessary dependencies.
Checked in my [personal repo](https://github.com/jeffwu0724/liferay-portal/pull/192#issuecomment-1334913394), and seems no regression found.

Thanks for checking!

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@jeffwu0724 rebase, please. It should fix sf issue. Thanks.

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
ci:test:document

**Comment by tinatian** [comment]
ci:test:reports

**Comment by tinatian** [comment]
ci:test:depot

**Comment by jeffwu0724** [comment]
Hey @Kvale1733 , could you help me check the test result, please?
Thanks,
Jeff

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by jeffwu0724** [comment]
Thanks a lot @Kvale1733 !

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127287

**Pull request closed without merging**
