### PR TITLE
[Remove Stream/Optional usage] LPS-175105 module: fragment

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend, thanks!

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3427
https://issues.liferay.com/browse/LPS-175105

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:echo

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3647

**Pull request closed without merging**
