### PR TITLE
LPS-202807 Several integration test break DB when executing

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-202807

Hi Team

Happy New Year! 🥰

Please could you review this fix?

Thanks in advance!

**Issue insights:** During the deletion implemented in DataGuardTestRuleUtil.smartDelete exceptions occur due to PrincipalThreadLocal.getName() being null which means that any use of GuestOrUserUtil.getUserId() throws a PrincipalException. LPS-191767 added several uses of GuestOrUserUtil.getUserId() during layout deletion so it caused these issues when DataGuardTestRuleUtil deletes a layout or a group that contains layouts

**Proposed solution:** Ensure PrincipalThreadLocal has the company administrator user set as the name during deletion by adding a new Rule and aggregating it to LiferayIntegrationTestRule.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@lfbesada Is there any existing test that can cover this issue?

**Comment by lfbesada** [comment]
> @lfbesada Is there any existing test that can cover this issue?

Hi @dantewang 

I have not created any specific test for this. My intention was, once the problem was fixed, to remove all test fixes that had to be made in LPS-191767 and in subsequent tickets to adapt the existing ones. For example, those adapted in the first PR: https://github.com/liferay-echo/liferay-portal/pull/13128/commits

I think I should have fixed it this way from the beginning because we have been adapting test by test for several months and new cases continue to appear.

IMHO by removing those fixes we will be testing this in all those tests. What do you think?

**Comment by dantewang** [comment]
@lfbesada Maybe we can revert the previous case-by-case fixes in this PR, which is a strong proof of the fix when CI passes.

**Comment by lfbesada** [comment]
> @lfbesada Maybe we can revert the previous case-by-case fixes in this PR, which is a strong proof of the fix when CI passes.

Great idea! I am going to add commits for this. Thanks!

**Comment by lfbesada** [comment]
@dantewang I can't do a clean revert one-by-one of the commits that changed the tests, it has been a long time and there are too many conflicts.
Instead of this, I have looked for all the tests that did what LiferayIntegrationTestRule now does, and I have removed setting/restoring PrincipalThreadLocal's name since it will no longer be necessary. So revert the integration tests adapted in that way by LPS-191767 is included in that commit.
I am running the relevant tests to verify that those tests are still working correctly.

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
The test com.liferay.document.library.opener.google.drive.test.DLOpenerGoogleDriveManagerTest fails because of my changes in the test class:  https://testray.liferay.com/home/-/testray/case_results/2481777321?tab=history
I am going to force push the last commit to fix it and I am going to re-run the relevant tests

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@lfbesada Please let me know if the tests passed.

**Comment by lfbesada** [comment]
Hi @dantewang
 
Thank you very much for the review.

I confirm that yes, all the tests that I modified in the last commit have been executed correctly.

Regards

**Comment by dantewang** [comment]
@lfbesada Moved forward for review. Could you verify that there's no unique failure in ci-test-relevant and add QA Passed label if so?

**Comment by lfbesada** [comment]
@dantewang  I have checked that there are no unique failures in the relevant tests but I do not have permission to add tags in this repo.

**Comment by lfbesada** [comment]
I have forced push to rebase and fix conflicts, so I am going to relaunch CI.

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
I have forced push to rebase and fix conflicts, so I am going to relaunch CI.

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:2487418973

**Comment by tinatian** [comment]
@lfbesada Any reason you can not use PermissionCheckerMethodTestRule?

**Comment by lfbesada** [comment]
Hi @tinatian 

Thanks for the review!

PermissionCheckerMethodTestRule does not solve the problem since it is a method rule, not a class one. For example, in [this commit](https://github.com/liferay/liferay-portal/commit/cd050dc6a5056dae835ae4508b322464fc320483), we fixed a test that had this problem despite the test having set the PermissionCheckerMethodTestRule. 

One of the approaches I had in mind was to create PermissionCheckerTestRule, but I discarded it because:

1. The issue we have is related to PrincipalThreadLocal, not the PermissionChecker.
2. It is a very widespread problem, it would be necessary to add the new rule to many tests.
3. The problem does not normally cause the test to fail, at most it leaves traces in the console in the tearDown that is later detected, so the developer will not perceive the problem and will not see the need to add that new rule.

For all these reasons I thought that the most appropriate approach was adding a new Rule to set and restore PrincipalThreadLocal's name and aggregating it to LiferayIntegrationTestRule.

Regards

**Comment by lfbesada** [comment]
I have forced push to rebase and fix conflicts, so I am going to relaunch CI.

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@lfbesada 
1. PrincipalThreadLocal should be part of the permission checker, so for those failed tests, they should somehow depends on permission checker which requires  PrincipalThreadLocal.
2. It does not make sense that a test rule for method does not work for class, please try to figure out why.
3. If this is a general issue, we should make PermissionCheckerMethodTestRule a default test rule.

Please resend.
Thanks.
Tina.

**Pull request closed without merging**
