### PR TITLE
[Method References 2] LPS-167730 Remove method reference in class PortletRegistryImpl 

### PR DESCRIPTION
**Pull request by W2jx**
Hi @dantewang , I have resent it.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3785

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:echo

**Comment by zhangyan0701** [comment]
Semantic versioning issues:
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/asset/asset-tags-navigation-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]       com.liferay.asset.tags.navigation.constants        UNCHANGED  1.1.0      1.0.0      1.0.0      EXCESSIVE VERSION INCREASE
     [exec]     	-   version    1.0.0
     [exec]     	+   version    1.1.0
```
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/asset/asset-publisher-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]       com.liferay.asset.publisher.constants              UNCHANGED  3.1.0      3.0.0      3.0.0      EXCESSIVE VERSION INCREASE
     [exec]     	-   version    3.0.0
     [exec]     	+   version    3.1.0
```
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/asset/asset-categories-navigation-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]       com.liferay.asset.categories.navigation.constants  UNCHANGED  1.1.0      1.0.0      1.0.0      EXCESSIVE VERSION INCREASE
     [exec]     	-   version    1.0.0
     [exec]     	+   version    1.1.0
```
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/document-library/document-library-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]       com.liferay.document.library.constants             UNCHANGED  2.1.0      2.0.0      2.0.0      EXCESSIVE VERSION INCREASE
     [exec]     	-   version    2.0.0
     [exec]     	+   version    2.1.0
```
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/dynamic-data-lists/dynamic-data-lists-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]       com.liferay.dynamic.data.lists.constants           UNCHANGED  2.3.0      2.2.0      2.2.0      EXCESSIVE VERSION INCREASE
     [exec]     	-   version    2.2.0
```
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/dynamic-data-mapping/dynamic-data-mapping-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]       com.liferay.dynamic.data.mapping.constants         UNCHANGED  3.1.0      3.0.0      3.0.0      EXCESSIVE VERSION INCREASE
     [exec]     	-   version    3.0.0
     [exec]     	+   version    3.1.0
```
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/fragment/fragment-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.fragment.constants                     MINOR      3.0.0      3.0.0      3.1.0      VERSION INCREASE REQUIRED
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-03/test-1-38/test-portal-acceptance-pullrequest(master)/6824/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by W2jx** [comment]
only do semver, no need to rerun test

**Comment by W2jx** [comment]
no conflicts(3/14 15:20)

**Comment by W2jx** [comment]
no conflicts(3/17 14:36)

**Comment by W2jx** [comment]
no conflicts(3/20 8:52)

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:echo

**Comment by W2jx** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:stop

**Pull request closed without merging**
