### PR TITLE
[Components with more than 1 service] Refactor Portlet components with more than 1 service type from Echo

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by rafaprax** [comment]
Looks good to me.
 
/cc @tinatian

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131761

**Pull request closed without merging**
