### PR TITLE
LRQA-75659 Use correct gradle task when compiling integration test modules

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-75659

### CODE REVIEW

**Comment by kyle-miho** [comment]
This is a fix for ModulesStructureTest in portal-kernel

**Comment by rafaprax** [comment]
Hey @tinatian, this change looks good to me. Thx

**Review by rafaprax — APPROVED** [review]

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.
@kyle-miho Code looks good to me, wait for QA to scan test results.


Tina

**Comment by catarineaguiar** [comment]
@tinatian  [central-requirements-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1904466684?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1904466653%26testrayRunId%3D1904466670%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) Passed

no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
