### PR TITLE
LPS-174821 Add configuration for http client connection pool

### PR DESCRIPTION
**Pull request by dantewang**
FYI @shuyangzhou 

@111Anna Please run runtime & startup tests on this PR. For runtime tests, run AssetPublisher first, we expect this PR provides the same effect with the local fix you applied earlier for the AP regression.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:search

**Comment by 111Anna** [comment]
> @111Anna Please run runtime & startup tests on this PR. For runtime tests, run AssetPublisher first, we expect this PR provides the same effect with the local fix you applied earlier for the AP regression.

OK, got it

**Comment by lipusz** [comment]
Forward this to the search team for review.

**Comment by dantewang** [comment]
@tinatian Search team requires to review this one before sending to Brian.

**Comment by 111Anna** [comment]
Hi @dantewang, There is no regression on  startup test, but the AssetPublisher had a big regression.
Here are test results:

CE
Portal Version|GitId|Average Startup (ms)|%|Average Shutdown (ms)|%|Open File|Thread Create|Open Prepared Statement|Open SQL
--|--| --|--|--|--|--|--|--|--|
Baseline| 5f5176fa8a| 22803 |- |2991.6|-| 1830 | 89 | 490| 1003 |
Baseline + PR-3580| - |  22836 |-0.14%| 2985|0.2%| 1830 | 88 | 496 | 1004 |

DXP
Portal Version|GitId|Average Startup (ms)|%|Average Shutdown (ms)|%|Open File|Thread Create|Open Prepared Statement|Open SQL
--|--| --|--|--|--|--|--|--|--|
Baseline| 5f5176fa8a| 24909.3 |- |3623|-| 1986 | 101| 556| 1092 |
Baseline + PR-3580| - |  24639.3 | 1.1%| 3586|1.0%| 1986 | 101 | 550 | 1092| 

AP:
Portal Version|GitId|Session Count |Mean Time of Login|Session Count Change (%)|
--|--| --|--|--|
LPS-174821| c151fd33| 28520 | 390 |-|
LPS-174821 + PR-3580| - | 14868 |1040 |-47.8% |

**Comment by Kvale1733** [comment]
@dantewang No regressions found in the ci results. Adding QA Failed Label due to the performance regression.

**Comment by dantewang** [comment]
@111Anna @Kvale1733 Thanks!

**Comment by dantewang** [comment]
Performance regression is due to a place to pass the config that I missed. Fix is sent to https://github.com/liferay-core-infra/liferay-portal/pull/3596.

**Pull request closed without merging**
