### PR TITLE
LPS-143420

### PR DESCRIPTION
**Pull request by julschong**
Hi @tinatian,
this is rebased again due to some conflict responding to this pull comment from Brian brianchandotcom#111824

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
@vicnate5 Hi Victor, could you please help me scan the result?
Thank you!

**Comment by julschong** [comment]
@vicnate5 Hi Victor, please help me scan this one as well
Thank you!

**Comment by vicnate5** [comment]
@julschong No regressions found. All the test failures are unrelated.

**Comment by julschong** [comment]
@shuyangzhou @tinatian
Hi Shuyang, Tina, 
Please help me review this pull to see if it is good to go.
Thank you!

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
ci:stop

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/112294

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
