### PR TITLE
[OrderByComparator] LPD-28392 Clean up and Apply Singleton in kernel document/library

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPD-28392](https://liferay.atlassian.net/browse/LPD-28392)
- **LPD-28392 Add singleton to FolderIdComparator and apply**
- **LPD-28392 Add singleton to FolderNameComparator and apply**
- **LPD-28392 Add singleton to DLFileVersionVersionComparator and apply**

[LPD-28392]: https://liferay.atlassian.net/browse/LPD-28392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:stop

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:relevant

**Comment by victorhcunha** [comment]
ci:test:relevant

**Comment by victorhcunha** [comment]
ci:test:sf

**Comment by victorhcunha** [comment]
ci:test:relevant

**Comment by victorhcunha** [comment]
ci:report:18160933

**Comment by victorhcunha** [comment]
ci:test:stable

**Comment by victorhcunha** [comment]
ci:test:relevant

**Comment by victorhcunha** [comment]
ci:report:28322022

**Comment by Valmir-unicap** [comment]
Reevaluating!
CC: @titokenzo

**Comment by Valmir-unicap** [comment]
Reevaluating!
CC: @titokenzo

**Pull request closed without merging**
