### PR TITLE
[Method References 2] LPS-166968 Convert method reference to ServiceTrackerMap in module data-engine-taglib and data-engine-rest-impl

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4140

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:data-engine

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(4/18 9:28)

**Comment by W2jx** [comment]
no conflicts(4/19 8:03)

**Comment by W2jx** [comment]
no conflicts(4/20 7:56)

**Comment by W2jx** [comment]
no conflicts(4/21 8:22)

**Comment by W2jx** [comment]
only do semver, no need to rerun test

**Comment by W2jx** [comment]
no conflicts(4/25 8:02)

**Comment by W2jx** [comment]
no conflicts(4/26 7:48)

**Comment by W2jx** [comment]
no conflicts(4/27 11:15)

**Comment by W2jx** [comment]
only do semver, no need to rerun test

**Comment by W2jx** [comment]
no conflicts(5/2 10:54)

**Comment by tinatian** [comment]
@W2jx The change in https://github.com/liferay-core-infra/liferay-portal/pull/4272/commits/8bce680313dc6bba28710ff71520f1fa662f741b is too many to review, please do:
1. Simplify DataLayoutTaglibUtil, inline the method only used by one place
2. Apply the snapshot pattern

Please try to separate the changes into two pulls if it is too big for one.

Thanks.
Tina.

**Pull request closed without merging**
