### PR TITLE
[Components with more than 1 service] LPS-186666 Refactor components from portal-search-tuning and portal-remote modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://issues.liferay.com/browse/LPS-186666

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
no regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136000

**Pull request closed without merging**
