### PR TITLE
[TS] LPS-146343 Only alter the portlet namespace of the request when a non-empty querystring is provided

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @liferay-core-infra ,

Ticket: [LPS-146343](https://issues.liferay.com/browse/LPS-146343)
ci:test results (QA checked): https://github.com/ericyanLr/liferay-portal/pull/263

**Context**
Issue: When a **Content Page** contains multiple widgets, interacting with one widget affects the state of the other widgets. (The other widgets appear as if they've been reset) (See [LPS-146343](https://issues.liferay.com/browse/LPS-146343) for a more detailed scenario)

This issue is not reproducible in Widget Pages, since **a Widget Page does not utilize RuntimeTag** to render portlets. On the other-hand, a **Content Page utilizes RuntimeTag** to render portlets: [FragmentPortletRendererImpl.java#L70-L75](https://github.com/liferay/liferay-portal/blob/7.4.3.11-ga11/modules/apps/fragment/fragment-impl/src/main/java/com/liferay/fragment/internal/renderer/FragmentPortletRendererImpl.java#L70-L75)

**Root Issue**
From my understanding, the root issue is that the RuntimeTag currently forces the request to always use the p_p_id of the target portlet: [RuntimeTag.java#L233-L234](https://github.com/liferay/liferay-portal/blob/7.4.3.11-ga11/util-taglib/src/com/liferay/taglib/portletext/RuntimeTag.java#L233-L234) when rendering the target portlet.

This is understandable if parameters are being provided for the target portlet (queryString parameter) and we want to render the target portlet with a specific state. 

However, if no specific parameters are being specified for our target portlet and the original request is for another portlet, then forcing the p_p_id to change to our target portlet would cause the portlet to render without any parameters. 
- This means the target portlet would not render using it's previous state's parameters, but instead render without any parameters.
  - When I say "without any parameters", I'm referring to parameters that belong to the target portlet

**Proposed Fix**
If a blank/null queryString is provided, we shouldn't force the p_p_id to be the target portlet.

Since we aren't providing any specific parameters for the target portlet, not forcing the p_p_id to be replaced in the request, would allow for the target portlet to be rendered using it's previous state's parameters.

Please let me know if you have any questions or concerns about this proposed change.

Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@ericyanLr Is it possible to add integration test for this bug?

Tina.

**Comment by ericyanLr** [comment]
Hi @tinatian ,

Can you elaborate on the test you had in mind? 
- Would we be trying to test like the Content Page scenario described in [LPS-146343](https://issues.liferay.com/browse/LPS-146343) or more specifically the RuntimeTag?
- And would it be more of a poshi type of test or integration test?

**Comment by tinatian** [comment]
@ericyanLr I would prefer an integration test related to RuntimeTag.

**Comment by ericyanLr** [comment]
@tinatian, thanks for the clarification, sure I can work on an integration test for that.

Would you like me to close this PR and resend w/ the test or leave it open?

**Comment by ericyanLr** [comment]
@tinatian, actually can give help give some guidance on how I should approach creating this test case?

Do you think this existing test class would be suitable:
[EmbeddedPortletWhenEmbeddingPortletUsingRuntimeTagTest.java](https://github.com/liferay/liferay-portal/blob/7.4.3.12-ga12/modules/apps/static/portal-osgi-web/portal-osgi-web-portlet-container-test/src/testIntegration/java/com/liferay/portal/osgi/web/portlet/container/embedded/test/EmbeddedPortletWhenEmbeddingPortletUsingRuntimeTagTest.java)

Are we looking for a test case to a scenario where:
- We add 2 portlets to a Content Page
- Change the state of Portlet A
- Change the state of Portlet B
- Check if Portlet A and Portlet B are both in their changed states

Or is there a simpler test case you had in mind?

**Comment by tinatian** [comment]
@ericyanLr I would like that we can always add integration/unit test to cover the changes we made so that we can trace back and understand the bug fix more later. It happens sometimes it is not easy to add a test. If it is going to take a lot of effort to add integration test, then let's go with functional test.

Tina.

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results once it is finished.

Thanks
Tina.

**Comment by ericyanLr** [comment]
@tinatian , that makes sense to me. 

In that case, let's proceed with creating a functional test using the steps to reproduce in [LPS-146343](https://issues.liferay.com/browse/LPS-146343)
- Create Content Page with 2 Asset Publisher Widgets (Setup widget with pagination)
- Create 3 Web Content articles
- Interact with the 2 Asset Publisher widgets by paginating each widget one at a time

I think this test case would be the easy to setup, easy to visually see the issue and the effects of the change.

@vicnate5 , I haven't written a functional test before, can you help provide some guidance?
- Are these added to .testcase files and if so, would this be a good testcase to use: [ContentPages.testcase](https://github.com/liferay/liferay-portal/blob/7.4.3.12-ga12/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/contentpage/ContentPages.testcase)

**Comment by zhangyan0701** [comment]
Checked the test results, no regressions found.

**Comment by vicnate5** [comment]
@zhangyan0701 Could you take care of adding automation for this? I am not sure if this should be put into an existing test case file or just be put into a new one.

@david-gutierrez-mesa Any opinion on where we should put a test case like this?

**Comment by zhangyan0701** [comment]
> @zhangyan0701 Could you take care of adding automation for this? I am not sure if this should be put into an existing test case file or just be put into a new one.
> 
Yes, I created a ticket for it [LRQA-73397](https://issues.liferay.com/browse/LRQA-73397). Will work on it.

**Comment by david-gutierrez-mesa** [comment]
hi @zhangyan0701 and @vicnate5 . @ozysouza @Tim-Cao and @liulukiwi should know better.

**Comment by ozysouza** [comment]
> hi @zhangyan0701 and @vicnate5 . @ozysouza @Tim-Cao and @liulukiwi should know better.

Hi @zhangyan0701 and @vicnate5. I'd better create a new test on AssetPublisherUseCase.testcase
Let me know if you need some help.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
