### PR TITLE
[Remove unused @Reference var] LPS-164222 

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove the unused @reference variable in `client-extension-web`. Thanks!
CI test passed in https://github.com/JanisZhang/liferay-portal/pull/127

https://issues.liferay.com/browse/LPS-164222

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by tinatian** [comment]
@Kvale1733 Please help me scan test results.

Thanks.
Tina

**Comment by Kvale1733** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/124393

**Pull request closed without merging**
