### PR TITLE
LPD-38849 Missing "There are no patches installed" and "The following patches are installed" INFO log traces during server startup

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://liferay.atlassian.net/browse/LPD-38849

During the startup process of Liferay, we should have some INFO log traces that informs about the installed patches of the customer:
```
2024-08-06 07:29:33.619 INFO  [main][StartupHelperUtil:76] There are no patches installed
```

or 
```
2024-02-07 20:19:09.268 INFO [main][StartupHelperUtil:79] The following patches are installed: hotfix-80
```

But after [LPD-28798](https://liferay.atlassian.net/browse/LPD-28798) code changes these traces are no longer written to the log file.

This information is very useful from the support department perspective: when the customer sends their log file, we also have their exact patch information.

It is also the most useful and quick way of checking the exact version of LXC customers.

For more information see this slack thread: https://liferay.slack.com/archives/C01FP01V5L0/p1728297313799899 

**Steps to reproduce**

1. Start a Liferay installation
2. Open the log file and search for `There are no patches installed` or `The following patches are installed` 
      - Expected behavior: The log traces are present 
      - Wrong behavior: The log traces aren’t present 

**Solution**
To solve the issue, I am changing the log level of StartupHelperUtil, see commit https://github.com/liferay-core-infra/liferay-portal/commit/67803b690a6d24687280e3bda0c34312d1d5f74c

(It is a partial revert of LPD-28798 code changes)

[LPD-28798]: https://liferay.atlassian.net/browse/LPD-28798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tinatian** [comment]
ci:forward:force

**Comment by jorgediaz-lr** [comment]
ci:reevaluate:1357401_6253

**Comment by tinatian** [comment]
@jorgediaz-lr See https://github.com/brianchandotcom/liferay-portal/pull/155066. This should not cause regression on production code and test, if any test failed because of this, the fix should be at test, not this change, thus I forward it without looking at the test results.

**Comment by jorgediaz-lr** [comment]
Thanks for forwarding it, @tinatian !

**Pull request closed without merging**
