### PR TITLE
[Startup time optimization] LPS-160888

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to disable auto-import-default-references in marketplace-service. Thanks!
https://issues.liferay.com/browse/LPS-160888

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @catarineaguiar ,Could you please help to scan the results? Thanks

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
