### PR TITLE
[Remove Blocking usages]LPS-187888 portal-kernel | ViewCountManagerUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
no conflicts(6/19 13:46)

**Comment by zhangyan0701** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(6/20 8:56)

**Comment by W2jx** [comment]
no conflicts(6/23 14.49)

**Comment by W2jx** [comment]
no conflicts(6/26 15:25)

**Comment by W2jx** [comment]
no conflicts(6/27 8:52)

**Comment by W2jx** [comment]
Hi @dantewang , I think we can not merge class `ViewCountEntryLocalServiceImpl` into class `ViewCountManagerUtil`, because some other references are needed in the logic of class  `ViewCountEntryLocalServiceImpl`; and we can not move the the usages in portal-impl out.
I debug the startup process, and found that class ViewCountEntryLocalServiceImpl will be woken up by class AopServiceManager, and it is earlier than class ViewCountManagerUtil is used, so I think we can directly use unblocking ServiceProxyFactory.

**Comment by W2jx** [comment]
no conflicts(7/4 14:30)

**Comment by W2jx** [comment]
no conflicts(7/5 13:57)

**Comment by W2jx** [comment]
no conflicts(7/6 8:08)

**Comment by W2jx** [comment]
no conflicts(7/11 13:11)

**Comment by W2jx** [comment]
no conflicts(7/12 8:04)

**Comment by W2jx** [comment]
no conflicts(7/13 15:32)

**Pull request closed without merging**
