### PR TITLE
[Component with its own class name as service type] LPS-197370 Refactor components from lima modules part 2

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-197370](https://liferay.atlassian.net/browse/LPS-197370)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:stop

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found

**Review by rafaprax — CHANGES_REQUESTED** [review]
Hy @RenanUmV, just remove the first commit for now and send it with the `ViewSharedAssetsDisplayContextFactory` case in a follow up pr. Thx

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
@RenanUmV possible regression:

```
[beanshell]      [exec] com.liferay.sharing.blogs.internal.test.BlogsEntrySharingTest > testAdminCanShareWithAddDiscussion FAILED
[beanshell]      [exec]     java.lang.IllegalStateException: Timed out while waiting for service com.liferay.portal.security.permission.contributor.PermissionSQLContributor model.class.name=com.liferay.blogs.model.BlogsEntry
[beanshell]      [exec]     	at com.liferay.portal.test.rule.InjectTestBag._getServiceReference(InjectTestBag.java:190)
[beanshell]      [exec]     	at com.liferay.portal.test.rule.InjectTestBag.injectFields(InjectTestBag.java:69)
[beanshell]      [exec]     	at com.liferay.portal.test.rule.InjectTestRule.beforeMethod(InjectTestRule.java:52)
[beanshell]      [exec]     	at com.liferay.portal.test.rule.InjectTestRule.beforeMethod(InjectTestRule.java:15)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:85)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-31/test-portal-acceptance-pullrequest(master)/9844/modules-integration-mysql57-jdk8/0/9/jenkins-console.txt.gz?authuser=0)

**Comment by RenanUmV** [comment]
Hi @catarineaguiar , I believe this test is broken, it's also failing on other pull requests, I tried running it locally on master and the same problem happens

**Comment by catarineaguiar** [comment]
@RenanUmV thanks for checking. So no regressions were found

**Comment by rafaprax** [comment]
Hey @RenanUmV, please apply the same approach request here https://github.com/liferay-core-infra/liferay-portal/pull/5975#issuecomment-1811024374. Thanks and resend

**Comment by RenanUmV** [comment]
resent here: https://github.com/RenanUmV/liferay-portal/pull/79

**Pull request closed without merging**
