### PR TITLE
LPS-166217 Remove "immediate = true" from Staging

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:staging

**Comment by zhangyan0701** [comment]
Found regression:
Error thrown when enable local staging and publish remote staging to live:
```
2022-10-20 22:29:59.229 ERROR [liferay/background_task-4][BackgroundTaskMessageListener:185] Unable to execute background task
java.lang.IllegalStateException: Unknown background task executor com.liferay.exportimport.internal.background.task.LayoutStagingBackgroundTaskExecutor
	at com.liferay.portal.background.task.internal.messaging.BackgroundTaskMessageListener._getBackgroundTaskExecutor(BackgroundTaskMessageListener.java:268) ~[bundleFile:?]
	at com.liferay.portal.background.task.internal.messaging.BackgroundTaskMessageListener._wrapBackgroundTaskExecutor(BackgroundTaskMessageListener.java:319) ~[bundleFile:?]
	at com.liferay.portal.background.task.internal.messaging.BackgroundTaskMessageListener.doReceive(BackgroundTaskMessageListener.java:110) [bundleFile:?]
	at com.liferay.portal.kernel.messaging.BaseMessageListener.doReceive(BaseMessageListener.java:48) [portal-kernel.jar:?]
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:34) [portal-kernel.jar:?]
	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74) [portal-kernel.jar:?]
	at com.liferay.portal.messaging.internal.ParallelDestination$1.run(ParallelDestination.java:56) [bundleFile:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```
Example failed test:
[LocalFile.StagingUsecase#PublishPortlet](https://testray.liferay.com/home/-/testray/case_results/2012332433)
Full console log:
https://testray.liferay.com/reports/production/logs/2022-10/test-1-37/test-portal-acceptance-pullrequest(master)/5805/functional-tomcat90-mysql57-jdk8/4/23/jenkins-console.txt.gz?authuser=0

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:staging

**Comment by zhangyan0701** [comment]
Below issues seem related:
1. Site that created from a custom Site Template is not accessible.
    Steps: 
    1) Create a Site Template with one page in Control Panel > Sites > Site Templates.
    2) Create a new Site based on the new Template.
    3) Assert that the page of Site Template is not created in the new site, and error in portal console: **Merge fail count increased to 1 for layout set prototype 46454**.

2. Import site fails.
    Steps:
   1) Export the default Liferay site.
   2) Add a new empty site.
   3) In the new site, import the site lar.
   4) Import fails, and error in log: **Unable to execute background task**.

3. Scheduler publish process doesn't work.
    Steps:
    1) Enable local staging, add a new page.
    2) Create a scheduler custom publish process.
    3) After the scheduler process publish, assert that in the Staging > Scheduled tab, the process disappears.
    4) Assert that the process doesn't display in Staging > Processes tab, and the new page is not published to live.
    
4. Integration test [com.liferay.exportimport.test.LayoutSetPrototypePropagationTest](https://testray.liferay.com/home/-/testray/case_results/2018959688) fails.
Full console: https://testray.liferay.com/reports/production/logs/2022-10/test-1-26/test-portal-acceptance-pullrequest(master)/5670/modules-integration-mysql57-jdk8/0/6/jenkins-console.txt.gz?authuser=0

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:staging

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
This last push was just to solve conflicts, so I didn't ran any ci suits.

**Comment by Kvale1733** [comment]
@MrJohn1911 One regressions still persists from the last run

Scheduler publish process doesn't work.

**Steps to reproduce:**

1) Enable local staging and add a new page.
2) Create a scheduler custom publish process.
3) After the scheduler process publish, assert that in the Staging > Scheduled tab, the process disappears.

**Expected Results:** Once the schedule time for the staging process arrives, the process appears in Staging > Processes and the page is published to Live

**Actual Results:** Once the schedule time for the staging process arrives, no process appears in Staging > Processes and the page is not published to live

**Comment by Kvale1733** [comment]
@MrJohn1911 One regressions still persists

Scheduler publish process doesn't work.

**Steps to reproduce:**

1) Enable local staging and add a new page.
2) Create a scheduler custom publish process.
3) After the scheduler process publish, assert that in the Staging > Scheduled tab, the process disappears.

**Expected Results:** Once the schedule time for the staging process arrives, the process appears in Staging > Processes and the page is published to Live

**Actual Results:** Once the schedule time for the staging process arrives, no process appears in Staging > Processes and the page is not published to live

**Comment by MrJohn1911** [comment]
ci:test:staging

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:stop

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:staging

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
@MrJohn1911 no regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126007

**Pull request closed without merging**
