### PR TITLE
[TS] LPS-168150

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@crodriguezy The code you remove was to fix https://issues.liferay.com/browse/LPS-54171. Are you sure it is OK to remove it? 


Tina.

**Comment by tinatian** [comment]
@vicnate5 Do we have any test covered https://issues.liferay.com/browse/LPS-54171?

**Comment by vicnate5** [comment]
We have tests that are similar to the scenario in the ticket, but I will check manually to be safe. Running related testing at https://github.com/vicnate5/liferay-portal/pull/2189 since I needed to fix the suite.

**Comment by vicnate5** [comment]
Manual testing based on [LPS-54171](https://issues.liferay.com/browse/LPS-54171) PASSED.

There is an issue with the Widget page after changing the language because the default page name is not transferred to the new localization. But I can also reproduce this issue on master upstream.
LanguageChangeName. This issue does not prevent the user from editing the page by adding new widgets.

Will update this once we get the automation results.

**Comment by crodriguezy** [comment]
Hi @tinatian , I got the same results as @vicnate5 . 
Maybe now it's necessary to fill in the default language value because of [this](https://github.com/liferay-core-infra/liferay-portal/pull/1947/commits/5275677222bfeb7cb8b143ce4f95f2274c87fdbf)

**Comment by yuhai** [comment]
> Hi @tinatian , I got the same results as @vicnate5 . Maybe now it's necessary to fill in the default language value because of [this](https://github.com/liferay-core-infra/liferay-portal/pull/1947/commits/5275677222bfeb7cb8b143ce4f95f2274c87fdbf)

@tinatian, the code looks good to me.

**Pull request closed without merging**
