### PR TITLE
LPS-146440 Remove rhino.jar

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by guilhermedcamacho** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@guilhermedcamacho No regressions found.

**Comment by guilhermedcamacho** [comment]
@shuyangzhou  , this PR is ready for your review. Thanks!

Tina is on PTO until Feb 2nd.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
