### PR TITLE
LPS-148925 Move netcdf.jar to portal-tika

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
@koor4356 please help me check the results, thanks!

**Comment by koor4356** [comment]
okay, thanks!

**Comment by tinatian** [comment]
@guilhermedcamacho Code looks good to me, wait for QA to scan test results.

Tina.

**Comment by tinatian** [comment]
@guilhermedcamacho Code looks good to me, wait for QA to scan test results.

Tina.

**Comment by koor4356** [comment]
@guilhermedcamacho 
This looks good, thanks!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by guilhermedcamacho** [comment]
Fixed conflict with file portal-tika/build.gradle

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114618

**Pull request closed without merging**
