### PR TITLE
[TS] LPD-1849 Avoid closing datasources that were retrieved via JNDI lookup

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team,

**Previous PR:** https://github.com/liferay-core-infra/liferay-portal/pull/6550
**Ticket:** https://liferay.atlassian.net/browse/LPD-1849

This is a continuation of the previous PR with the following changes/additions:
- As suggested, create **JNDIDataSourceWrapper** as a private static class of **DataSourceFactoryImpl**
- Added test case

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:2533547403

**Comment by ericyanLr** [comment]
**ci:report analysis**
No unique failures were found in test results.

Marking this as **Ready to Review (no regression)**

/cc @tinatian

**Comment by tinatian** [comment]
@ericyanLr Please see my changes at https://github.com/brianchandotcom/liferay-portal/pull/146857

**Pull request closed without merging**
