### PR TITLE
LPS-152602 Fix root model resource that should actually be a model resource

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-152602

### CODE REVIEW

**Comment by kyle-miho** [comment]
Already tested locally, deploy *wedeploy-auth-service/api and ran gw testIntegration on wedeploy-auth-test, everything passed. This module is not important at all to us, but this should fix the broken archived modules smoke test upstream

**Comment by kyle-miho** [comment]
ci:help

**Comment by kyle-miho** [comment]
This should fix the WeDeploy Portlet from being unable to be deployed, as occuring in this ticket: https://issues.liferay.com/browse/LRQA-74055
cc: @vicnate5

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
