### PR TITLE
[Static reference] LPS-166968 Replace field reference with snapshot in class DataLayoutTaglibUtil

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:data-engine

**Comment by zhangyan0701** [comment]
ci:test:data-engine

**Comment by dantewang** [comment]
@catarineaguiar @zhangyan0701 Are the data-engine suite failures real?

**Comment by zhangyan0701** [comment]
Issue found:
Error occurs when edit Web Content Structure with nested fields or field set.

https://github.com/liferay-core-infra/liferay-portal/assets/25576873/230c4ced-28b0-402e-a791-c391407e260e

No errors in portal console.

**Comment by W2jx** [comment]
see https://github.com/liferay-core-infra/liferay-portal/pull/4544,  I removed this commit https://github.com/liferay-core-infra/liferay-portal/pull/4520/commits/0f9f87bc990c099e1ccb7976e10adc90a38465af, and modified the field `_dataLayoutResourceFactorySnapshot` in commit https://github.com/liferay-core-infra/liferay-portal/pull/4520/commits/b0b6611613c51828e5de56bc7a8e9ced4fa9dc33

**Pull request closed without merging**
