### PR TITLE
LPS-143631 Remove JSONFactoryUtil usages in modules part 4

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from #2017

### CODE REVIEW

**Comment by Kvale1733** [comment]
@julschong It's difficult to scan this for regressions. Most search tests are failing due to an issue that's being fixed in this PR:https://github.com/liferay-core-infra/liferay-portal/pull/2049. It would be better to rerun relevant when that is merged.

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Possible regressions:
Some search unit tests failed with NPE error:
[com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.cluster.StatsClusterRequestExecutorTest](https://testray.liferay.com/home/-/testray/case_results/2008493476)
[com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.ElasticsearchSearchEngineAdapterIndexRequestTest](https://testray.liferay.com/home/-/testray/case_results/2008493451)
[com.liferay.portal.search.elasticsearch7.internal.mappings.NestedFieldsTest](https://testray.liferay.com/home/-/testray/case_results/2008493334)
[com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.ElasticsearchSearchEngineAdapterClusterRequestTest](https://testray.liferay.com/home/-/testray/case_results/2008493441)

Full Console output:
https://testray.liferay.com/reports/production/logs/2022-10/test-1-31/test-portal-acceptance-pullrequest(master)/5472/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by julschong** [comment]
changed for NPE in unit test

**Comment by julschong** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Some Search integration tests failed again with NPE error:
[com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.ElasticsearchSearchEngineAdapterClusterRequestTest](https://testray.liferay.com/home/-/testray/case_results/2019205962)
[com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.cluster.StatsClusterRequestExecutorTest](https://testray.liferay.com/home/-/testray/case_results/2019206003)
[com.liferay.portal.search.elasticsearch7.internal.mappings.NestedFieldsTest](https://testray.liferay.com/home/-/testray/case_results/2019205827)
[com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.ElasticsearchSearchEngineAdapterIndexRequestTest](https://testray.liferay.com/home/-/testray/case_results/2019205971)

**Comment by julschong** [comment]
@zhangyan0701
I will resend. I'm not sure where I got messed up, but the fix I made was excluded.

**Pull request closed without merging**
