### PR TITLE
[Equinox Http] LPS-199568 Inline ContextController

### PR DESCRIPTION
**Pull request by dantewang**
@shuyangzhou This PR includes the previous patch and the actual inline; the only change in patching is that I don't add a new interface in this PR. The class is inlined by extending.

### CODE REVIEW

**Comment by dantewang** [comment]
Hi QA, it seems CI is not responding now; please trigger ci-test when it comes back online, thanks!

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
@zhangyan0701 Could you double check the stable failure?

@julschong Is the license smoke failure related to the spring bean elimination?

**Comment by zhangyan0701** [comment]
@dantewang 

The error in license smoke test is:
```
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/ee/license/LifecycleAction.java:14: error: package com.liferay.portal.kernel.security.auth.session does not exist
    [javac] import com.liferay.portal.kernel.security.auth.session.AuthenticatedSessionManagerUtil;
    [javac]                                                       ^
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/ee/license/UpdateLicenseAction.java:16: error: cannot find symbol
    [javac] import com.liferay.portal.kernel.security.auth.http.HttpAuthManagerUtil;
    [javac]                                                    ^
    [javac]   symbol:   class HttpAuthManagerUtil
    [javac]   location: package com.liferay.portal.kernel.security.auth.http
    [javac] 2 errors
```
Testray link: https://testray.liferay.com/home/-/testray/case_results/2447407558

This should be caused by these two commits in release-tool-ee repo:
https://github.com/brianchandotcom/liferay-release-tool-ee/commit/2c7b3391f82b25b85ddb4a16a5ca00526d6b22aa
https://github.com/brianchandotcom/liferay-release-tool-ee/commit/1955a28514a2a910399ee0780f8b076e7f68e39b

@jeffwu0724 Could you take a look at this smoke test, your changes in release-tool-ee had been merged into master, but got reverted by @brianchandotcom.

**Comment by julschong** [comment]
@dantewang 
Per @brianchandotcom, the revert is temporary and will be added back later today. The smoke test should be good after the original commit is readded.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143151

**Pull request closed without merging**
