### PR TITLE
[Remove Immediate] LPS-192723 Remove immediate property from BundleBlacklistManagerImpl

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://liferay.atlassian.net/browse/LPS-192723

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@rafaprax regression found:

```
    [junit] Testcase: testScanGradleFiles(com.liferay.portal.modules.ModulesStructureTest):	FAILED
    [junit] Incorrect configuration of dependency {testImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"} in modules/apps/marketplace/marketplace-test/build.gradle, use one of these instead: "testIntegrationImplementation", "testIntegrationRuntimeOnly"
    [junit] junit.framework.AssertionFailedError: Incorrect configuration of dependency {testImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"} in modules/apps/marketplace/marketplace-test/build.gradle, use one of these instead: "testIntegrationImplementation", "testIntegrationRuntimeOnly"
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest._testGradleFile(ModulesStructureTest.java:1503)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest.access$800(ModulesStructureTest.java:59)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest$4.visitFile(ModulesStructureTest.java:393)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest$4.visitFile(ModulesStructureTest.java:367)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest.testScanGradleFiles(ModulesStructureTest.java:365)
    [junit] 
    [junit] 
    [junit] Test com.liferay.portal.modules.ModulesStructureTest FAILED
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-09/test-1-40/test-portal-acceptance-pullrequest(master)/6152/central-requirements-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
