### PR TITLE
[Replace Non-Blocking Usage] LPS-199717 Replace non-blocking ServiceProxyFactory usages in classes LayoutSetLocalServiceImpl, LayoutLocalServiceImpl and UserLocalServiceImpl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
no conflicts(10/27 8:50)

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by W2jx** [comment]
no conflicts(10/30 7:57)

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
@W2jx Regression found. Hypersonic startup gets stuck at this part

```
uccessfully
[beanshell] 2023-10-27 01:13:47.279 INFO  [fileinstall-directory-watcher][BundleStartStopLogger:68] STARTED admin-theme_5.0.69 [1484]
[beanshell] 2023-10-27 01:13:47.390 INFO  [fileinstall-directory-watcher][BundleStartStopLogger:68] STARTED minium-theme_5.0.74 [1487]
[beanshell] 2023-10-27 01:13:47.481 INFO  [fileinstall-directory-watcher][BundleStartStopLogger:68] STARTED speedwell-theme_4.0.69 [1488]
[beanshell] 2023-10-27 01:13:47.561 INFO  [fileinstall-directory-watcher][BundleStartStopLogger:68] STARTED dialect-theme_5.0.68 [1486]
[beanshell] 2023-10-27 01:13:47.637 INFO  [fileinstall-directory-watcher][BundleStartStopLogger:68] STARTED classic-theme_5.0.81 [1485]
[beanshell] 2 hours 4 minutes until timeout.
[beanshell] The top level build is alive.
[beanshell] 1 hour 59 minutes until timeout.
```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-30/test-portal-acceptance-pullrequest(master)/8189/functional-smoke-tomcat90-hypersonic20-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
