### PR TITLE
LPS-182671

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:lima

**Comment by tinatian** [comment]
ci:test:comment

**Comment by tinatian** [comment]
ci:test:message-boards

**Comment by tinatian** [comment]
ci:test:questions

**Comment by W2jx** [comment]
Hi @tinatian , I resend the [pr](https://github.com/liferay-core-infra/liferay-portal/pull/5258) to fix the issues.

**Pull request closed without merging**
