### PR TITLE
[Bug fix] LPS-145028

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian This is for the existing bug I found when working on LPS-144246.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dantewang The test is not focusing on the issue. Either you add a 100% covered test or you add a test only exposing the current issue, please resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
