### PR TITLE
[Urgent] LPS-65857 Add Auth and Encryption to JGroup cluster configuration

### PR DESCRIPTION
**Pull request by julschong**
@dantewang @zhangyan0701 
resubmitted from https://github.com/liferay-core-infra/liferay-portal/pull/6308
added [547b26e](https://github.com/liferay-core-infra/liferay-portal/pull/6324/commits/547b26ec2ab729f6b0a86db998ad58891f254553) to fix the decryption error message

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:clustering

**Comment by julschong** [comment]
removed the commit that shut down node if connection is not established

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:clustering

**Comment by julschong** [comment]
fix warning message not showing up

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:clustering

**Comment by dantewang** [comment]
According to testray, a failure of "ShutdownAndStartupNodes" with almost same error messages happened in https://github.com/zhangyan0701/liferay-portal/pull/576 which is irrelevant with this PR.

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by julschong** [comment]
:partying_face:

**Comment by dantewang** [comment]
@tinatian The last commit was to overcome some CI errors caused by some error logs printed by JGroups which are expected according to JGroups mechanism. But it would make the cluster less secure.

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
