### PR TITLE
[Urgent] LPS-202985 Avoid refreshing bundles with optional packages

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__ <https://liferay.atlassian.net/browse/LPS-202985>

### CODE REVIEW

**Comment by kevhlee** [comment]
cc: @tinatian, @dantewang, @david-truong

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:app-servers

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by shuyangzhou** [comment]
@tinatian I am pretty sure this would break FileInstallDeployTest.testDeployOptionalDependency(), how is CI not failing on it?

**Comment by dantewang** [comment]
@zhangyan0701 Could you double check the test result, see if the test Shuyang mentioned is executed?

**Comment by zhangyan0701** [comment]
The test FileInstallDeployTest.testDeployOptionalDependency() was executed, and failed. But seems that our Testray Analysis tool didn't filter that out somehow. Will talk about it in QA team. Sorry about this!

The test [com.liferay.portal.file.install.deploy.test.FileInstallDeployTest](https://testray.liferay.com/home/-/testray/case_results/2471714688) failed with below error:
```
[beanshell]      [exec] com.liferay.portal.file.install.deploy.test.FileInstallDeployTest > testDeployOptionalDependency FAILED
[beanshell]      [exec]     java.lang.AssertionError: [] expected:<1> but was:<0>
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-12/test-1-26/test-portal-acceptance-pullrequest(master)/12232/modules-integration-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0

**Comment by dantewang** [comment]
Hi @shuyangzhou, support wants to know what step we will take next, since the customer is asking. Will we just go with this PR and update/remove the optional package related test case, or think of another solution?
cc @tinatian

**Comment by shuyangzhou** [comment]
If you guys are sure no one uses the optional packages refreshing feature, you can just delete the test together with the function.

**Comment by kevhlee** [comment]
@tinatian, @dantewang In case we go with this solution, I have removed the test case.

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:test:app-servers

**Comment by zhangyan0701** [comment]
No regressions found. Manual testing following the steps in ticket https://liferay.atlassian.net/browse/LPS-202985 also passed.

**Comment by tinatian** [comment]
ci:forward:force

FYI @shuyangzhou The failed test is removed.

Tina

**Comment by Emmaliu** [comment]
ci:forward:force

cc @dantewang  @tinatian

**Comment by Emmaliu** [comment]
ci:forward:force

cc @dantewang @tinatian

**Pull request closed without merging**
