### PR TITLE
[Components with more than 1 service] LPS-190147 Refactor DLOpenerGoogleDriveManager component

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-190147

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:lima

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:online-editing

**Comment by catarineaguiar** [comment]
@MrJohn1911 regression found:

```
     [exec] com.liferay.document.library.opener.google.drive.test.DLOpenerGoogleDriveManagerTest > testCheckInUploadsAnEmptyFileToGoogle FAILED
     [exec]     java.lang.NoSuchMethodException: No method on null with name setAuthorizationToken and parameter types [long, long, class java.lang.Object]
     [exec]     	at com.liferay.portal.kernel.test.ReflectionTestUtil.getMethod(ReflectionTestUtil.java:190)
     [exec]     	at com.liferay.portal.kernel.test.ReflectionTestUtil.invoke(ReflectionTestUtil.java:217)
     [exec]     	at com.liferay.document.library.opener.google.drive.test.DLOpenerGoogleDriveManagerTest.lambda$_test$5(DLOpenerGoogleDriveManagerTest.java:336)
     [exec]     	at com.liferay.document.library.opener.google.drive.test.DLOpenerGoogleDriveManagerTest._test(DLOpenerGoogleDriveManagerTest.java:360)
     [exec]     	at com.liferay.document.library.opener.google.drive.test.DLOpenerGoogleDriveManagerTest._test(DLOpenerGoogleDriveManagerTest.java:325)
     [exec]     	at com.liferay.document.library.opener.google.drive.test.DLOpenerGoogleDriveManagerTest.testCheckInUploadsAnEmptyFileToGoogle(DLOpenerGoogleDriveManagerTest.java:101)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-07/test-1-25/test-portal-acceptance-pullrequest(master)/1990/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Possible regression.
Test [com.liferay.document.library.opener.google.drive.test.DLOpenerGoogleDriveManagerTest](https://testray.liferay.com/home/-/testray/case_results/2390688881) failed with error:
```
	java.lang.IllegalArgumentException: argument type mismatch
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at com.liferay.portal.kernel.test.ReflectionTestUtil.invoke(ReflectionTestUtil.java:221)
		at com.liferay.document.library.opener.google.drive.test.DLOpenerGoogleDriveManagerTest.lambda$_test$5(DLOpenerGoogleDriveManagerTest.java:324)
		at com.liferay.document.library.opener.google.drive.test.DLOpenerGoogleDriveManagerTest._test(DLOpenerGoogleDriveManagerTest.java:348)
		at com.liferay.document.library.opener.google.drive.test.DLOpenerGoogleDriveManagerTest._test(DLOpenerGoogleDriveManagerTest.java:313)
		at com.liferay.document.library.opener.google.drive.test.DLOpenerGoogleDriveManagerTest.testCheckInUploadsAnEmptyFileToGoogle(DLOpenerGoogleDriveManagerTest.java:101)
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-07/test-1-37/test-portal-acceptance-pullrequest(master)/13294/modules-integration-mysql57-jdk8/0/1/com.liferay.document.library.opener.google.drive.test.DLOpenerGoogleDriveManagerTest.txt.gz?authuser=0

**Pull request closed without merging**
