### PR TITLE
[Urgent] LPS-195925

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, @tinatian, the previous pr is https://github.com/brianchandotcom/liferay-portal/pull/145241.

Based on BChan mentioned from the [link](https://github.com/brianchandotcom/liferay-portal/pull/145241#issuecomment-1859254477), I think he might want to change the order because the previous fix was the same order as he mentioned.
```
|| entity.hasExternalReferenceCode() || entity.hasEntityColumn("externalReferenceCode")>
to
|| entity.hasEntityColumn("externalReferenceCode") || entity.hasExternalReferenceCode()>
```

I did the change and found portal-impl's changes will be reverted if I didn't remove the previous [Auto generated](https://github.com/brianchandotcom/liferay-portal/pull/145241/commits/639780b6bb2b39776e0dcd8f9e3b41b496585e2d) commit to run **build-services**. I guess BChan might see the error. After removing "Auto generated" commit, running **build-services** will work as expected.

Instead of adjusting the order, I removed the condition **entity.hasExternalReferenceCode()** because I think it is unnecessary. Please see the [commit message](https://github.com/liferay-core-infra/liferay-portal/commit/9c066fa570fb2a05a4587360588f632027d2a487)

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:relavant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
> …ill create "externalReferenceCode" column by default if the entity doesn't include the "externalReferenceCode" column, this means entity.hasEntityColumn("externalReferenceCode") must return "true". But when entity.hasEntityColumn("externalReferenceCode") must return "true", it doesn't mean entity.hasEntityColumn("externalReferenceCode") must return "true", for example, JournalArticle and KBArticle entity(We can see the other entities by searching externalReferenceCode in service.xml). Please refer to the commit LPS-125672 (https://github.com/yuhai/liferay-portal/commit/e84f7497cf0fc7a5ab27ae418114a3090745b944) changes in the ServiceBuilder class.

@yuhai This part is a bit confusing and I believe there's some typo... Please correct it, thanks.

**Comment by yuhai** [comment]
@dantewang, done, only updated commit message.

**Comment by dantewang** [comment]
@yuhai Please try to check CI results, please refer to `[Resources for CI test and PR analysis]` in our private channel.

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
@dantewang, No regressions found.

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Comment by yuhai** [comment]
@dantewang, No regressions found.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
