### PR TITLE
LPS-174161

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,
Can you please review?
https://issues.liferay.com/browse/LPS-174161

Motivation
=======
ConfigurationFileInstallerTest#testCanTransformURL fails on Windows machines because path comparison does not use the same format for both paths. (eg.: on Windows forward and back slashes)

Proposed Solution
========
Formatting both paths using file URI before comparing will resolve this issue

Steps to Verify
========
Running ConfigurationFileInstallerTest#testCanTransformURL on Windows

Cheers,
Balázs

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by balazssk** [comment]
Hi @liferay-core-infra ,
Can you please have a look at this?
Thanks

**Comment by tinatian** [comment]
@balazssk Please mark the pull with [TS] to make this pull prioritized for review.

@brunofalc A pull from TS but not marked with [TS], could you please check if there are teams we need to notify?

Thanks.
Tina.

**Comment by tinatian** [comment]
@balazssk I see the issue, it only happens on windows, could you please update the ticket to include this info?

**Comment by tinatian** [comment]
@yuhai I do not like the solution in this pull, could you please figure out a better way to fix this on windows?

@vicnate5 This only happens on windows, sorry to bother.

Thanks.
Tina.

**Pull request closed without merging**
