### PR TITLE
[TS] LPS-134550 Cookies do not follow custom context paths

### PR DESCRIPTION
**Pull request by DaneszLR**
Hi Team,

https://liferay.atlassian.net/browse/LPS-134550

Issue:
Cookies do not follow custom context paths. Setting the context path (for example) to "myportal" resulted in the cookies still end with "/" instead of "/myportal"

Solution:
Concat the custom context path to the cookie.

Testing:
Tested it locally following the ticket steps on a vanilla version. Clearing all the cookies, reloading the site, shutting down the server and restarting it all worked.

Please review my PR!

Best regards,
Dani

### CODE REVIEW

**Comment by DaneszLR** [comment]
ci:test:relevant

**Comment by DaneszLR** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@DaneszLR No regressions. I tested this issue with /liferay context. This is the cookies I saw. Not all of them have that path but I'm assuming that's expected?

Screenshot from 2023-12-12 10-22-12

**Comment by DaneszLR** [comment]
I have run into this, cleared the cookies altogether and tried shutting down the server, restarting it, accessing different sites, but only the ones came back that had the right context. In the code I believe I can not find any more occasions of this concating to cookies.

**Comment by yuhai** [comment]
Hi @Kvale1733, I can't reproduce the test [result](https://github.com/liferay-core-infra/liferay-portal/pull/6311#issuecomment-1852659592). It is not expected behavior if we can reproduce it. Could you please close your browser to test after remove the cookies data from browser?

Hi @DaneszLR, please the below suggestions:

1. Since the fix centralized `setPath` logic to `CookiesManagerImpl`, could you please add the test to cover the fix in the `CookiesManagerImplTest`?
2. In CookiesManagerImpl class, please extract one private method called `private String _getContextPath(HttpServletRequest)`, and then you may use `cookie.setPath(_getContextPath(HttpServletRequest))`
3. For the change in the `BaseProfile`, please create one sperate commit for it. Because the fix changed its original logic. it used `portal.getPathContext()` and the value is `PropsValues.PORTAL_PROXY_PATH + contextPath`, please see the constructor `PortalImpl()`. I think the original value is wrong and your change is right by using `httpServletRequest.getContextPath`

I think the fix commits order may be as the below:
1. Make cookie path settings context aware. centralized `setPath` logic to `CookiesManagerImpl `(Only CookiesManagerImpl's change).
2. Apply, remove those usages, except `BaseProfile`.
3. Consider context path, when setting _cookieOptions (js file change).
4. Remove the usage from `BaseProfile` and provided the explanations.
5. Add the test to cover the fix.

I am going to close the pr. Please let me know if you have further concerns. 

Thanks,
Hai

**Pull request closed without merging**
