### PR TITLE
[System Properties] LPS-165265 Move some properties that moduleFramework needs during init | part 2

### PR DESCRIPTION
**Pull request by W2jx**
Hi @dantewang , This pr mainly migrates liferay.home, and involves upgrade and ci test file.

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Hi @W2jx 

Possible regressions:

**1 Some tests in [lpkg-controller-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2061405137) failed:**
```
     [exec] com.liferay.portal.lpkg.deployer.controller.LPKGControllerTest > testLPKGControllerDeploy FAILED
     [exec]     java.nio.file.NoSuchFileException: /opt/dev/projects/github/liferay-portal/modules/apps/static/portal-lpkg-deployer/portal-lpkg-deployer-test/liferay/osgi/marketplace/Liferay Controller Test.lpkg
```
```
     [exec] com.liferay.portal.lpkg.deployer.controller.test.LPKGControllerVerifyTest > testLPKGController FAILED
     [exec]     java.lang.AssertionError: No JAR bundle found
```

Full console log:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-28/test-portal-acceptance-pullrequest(master)/5175/lpkg-controller-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**2 Some clustering tests failed because the property `module.framework.properties.osgi.console` is set to the same port (11312) on node 1 and node 2 in portal-ext.properties, so the telnet cannot be started on node 2.**

Example test: https://testray.liferay.com/home/-/testray/case_results/2061381330

About this one, I need to confirm with you first. In which file should the property be set? portal-ext.properties or system-ext.properties? Because the test script needs some updates, but how it should be updated depends on which file is the correct one.

1) Should be set in portal-ext.properties. Based on my manual testing, the property takes effect in portal-ext.properties. If this is the expected result, then [this change](https://github.com/liferay-core-infra/liferay-portal/pull/2474/files#diff-d98844b18ba5230332f5a613cad8b8a241692b6b510f8c4529773210cbc13f35R2175) is not needed.

2) Should be set in system-ext.properties. Based on my manual testing, the property doesn't take effect in system-ext.properties. If this is the expected result, then here should be a bug. After fixing the bug, we can keep [this change](https://github.com/liferay-core-infra/liferay-portal/pull/2474/files#diff-d98844b18ba5230332f5a613cad8b8a241692b6b510f8c4529773210cbc13f35R2175), but we also need to move [this line](https://github.com/liferay-core-infra/liferay-portal/blob/2929e737a533420081fec828134749565132b963/build-test.xml#L74) and [this line](https://github.com/liferay-core-infra/liferay-portal/blob/2929e737a533420081fec828134749565132b963/build-test.xml#L110) from macro [apply-portal-ext-properties](https://github.com/liferay-core-infra/liferay-portal/blob/2929e737a533420081fec828134749565132b963/build-test.xml#L40) to target [prepare-system-ext-properties](https://github.com/liferay-core-infra/liferay-portal/blob/2929e737a533420081fec828134749565132b963/build-test.xml#L12474) just like the property `liferay.home`.

**Comment by W2jx** [comment]
Hi @zhangyan0701 , the property module.framework.properties.osgi.console should be set in portal-ext.properties.

**Comment by W2jx** [comment]
I will double check this pr.

**Comment by zhangyan0701** [comment]
> Hi @zhangyan0701 , the property module.framework.properties.osgi.console should be set in portal-ext.properties.

Got it. Then https://github.com/liferay-core-infra/liferay-portal/pull/2474/files#diff-d98844b18ba5230332f5a613cad8b8a241692b6b510f8c4529773210cbc13f35R2175 this should not be changed.

**Comment by W2jx** [comment]
Force-Push is just to modify file build-test.xml.

Hi @zhangyan0701, I think errors of lpkg test might exist on master branch, because when I execute lpkg‘s tests on master branch, I get same errors.

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
For `module.framework.properties.osgi.console`, is it a property that is not needed by the module framework startup, or it hasn't been migrated?

**Comment by W2jx** [comment]
Hi @dantewang , it has not been migrated, and it will be migrated in task https://issues.liferay.com/browse/LPS-165267.

**Comment by dantewang** [comment]
OK

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
@W2jx 

1. Before this pull, your `ModuleFrameworkPropsValues` contains purely `MODULE_FRAMEWORK_` property values, and they are used by classes related to module framework, like `ModuleFrameworkImpl`, `FileInstall`, etc. But once you add `liferay.home` to it, you can't keep it purely for module framework any more. You need to apply it to more places. When this happens, I don't think `ModuleFrameworkPropsValues` is a proper name anymore. Let's try to put `LIFERAY_HOME` constant in `SystemProperties` directly for now, because only this property is not prefixed with `module.framework`, right?
2. When you apply the change to `liferay.home`, you are mixing usage of `ModuleFrameworkPropsValues.LIFERAY_HOME` and `SystemProperties.get(SystemPropsKeys.LIFERAY_HOME)`. `liferay.home` is a property that shouldn't be changed at runtime at all, so you should always use the value constant instead of dynamically getting it. When you do this, you will also get rid of `SystemPropsKeys.LIFERAY_HOME` in this PR.
3. You should split the commit of migrating `liferay.home` with applying the new constant to classes.

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:stop

**Pull request closed without merging**
