### PR TITLE
[TS] LPS-189944

### PR DESCRIPTION
**Pull request by ericyanLr**
https://liferay.atlassian.net/browse/LPS-189944

Hi Team,

This fix introduces two changes:
- Update third-party library: **org.eclipse.equinox.console** from **1.4.300** to **1.4.500**
- Create a patch for this third-party library to avoid **InterruptedException** from being thrown when running the disconnect command in gogo shell (telnet)

The approach I took for this patch was to confine the logic change to only be applied for a telnet connection running the disconnect command.

For additional notes, see ticket description in LPS ticket.

Please let me know if you have any questions.
Thanks!

---

**Changes**
Force pushed to: fix SF issues and updated dependencies in build.gradle to be more consistent

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@ericyanLr please resolve conflicts and SF issue:

```
format-source-files:
     [java] java.lang.Exception: Found 30 formatting issues:
     [java] 1: Missing copyright, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/copyright_check.markdown: ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java (SourceCheck:CopyrightCheck)
     [java] 2: Javadoc should start with '/**': ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 1 (Checkstyle:JavadocCheck)
     [java] 3: Javadoc should end with '*/': ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 13 (Checkstyle:JavadocCheck)
     [java] 4: Missing author: ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 36 (Checkstyle:MissingAuthorCheck)
     [java] 5: private constant 'DISCONNECT_MESSAGE' of type 'String' must match pattern '^_[A-Z0-9][_A-Z0-9]*$': ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 37 (Checkstyle:ConstantNameCheck)
     [java] 6: private constant 'DISCONNECT_CONFIRMATION_Y' of type 'String' must match pattern '^_[A-Z0-9][_A-Z0-9]*$': ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 38 (Checkstyle:ConstantNameCheck)
     [java] 7: Name of variable with type 'BundleContext' should end with 'bundleContext': ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 40 (Checkstyle:VariableNameCheck)
     [java] 8: Private non-static field 'context' must match pattern '^_[a-z0-9][_a-zA-Z0-9]*$', see https://checkstyle.sourceforge.io/config_naming.html#MemberName: ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 40 (Checkstyle:MemberNameCheck)
     [java] 9: Name of variable with type 'BundleContext' should end with 'bundleContext': ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 42 (Checkstyle:VariableNameCheck)
     [java] 10: There should be an empty line after line '47', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/missing_empty_line_check.markdown: ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 47 (Checkstyle:MissingEmptyLineCheck)
     [java] 11: There should be an empty line before line '48', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/missing_empty_line_check.markdown: ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 48 (Checkstyle:MissingEmptyLineCheck)
     [java] 12: There should be an empty line between assigning and using variable 'props', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/missing_empty_line_check.markdown: ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 48 (Checkstyle:MissingEmptyLineCheck)
     [java] 13: There should be an empty line after line '49', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/missing_empty_line_check.markdown: ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 49 (Checkstyle:MissingEmptyLineCheck)
     [java] 14: There should be an empty line after line '54', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/missing_empty_line_check.markdown: ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 54 (Checkstyle:MissingEmptyLineCheck)
     [java] 15: There should be an empty line before line '55', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/missing_empty_line_check.markdown: ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 55 (Checkstyle:MissingEmptyLineCheck)
     [java] 16: There should be an empty line between assigning and using variable 'consoleStream', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/missing_empty_line_check.markdown: ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 55 (Checkstyle:MissingEmptyLineCheck)
     [java] 17: There should be an empty line before line '58', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/missing_empty_line_check.markdown: ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 58 (Checkstyle:MissingEmptyLineCheck)
     [java] 18: There should be an empty line after line '59', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/missing_empty_line_check.markdown: ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 59 (Checkstyle:MissingEmptyLineCheck)
     [java] 19: Rename exception variable 'e' to 'ioException': ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 62 (Checkstyle:ExceptionVariableNameCheck)
     [java] 20: Unprocessed exception 'IOException', see LPS-36174: ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 62 (Checkstyle:UnprocessedExceptionCheck)
     [java] 21: Combine nested if-statements: ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 66 (Checkstyle:NestedIfStatementCheck)
     [java] 22: Missing parentheses around the right hand side argument of the '||' operator: ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 67 (Checkstyle:MissingParenthesesCheck)
     [java] 23: There should be an empty line after line '68', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/missing_empty_line_check.markdown: ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 68 (Checkstyle:MissingEmptyLineCheck)
     [java] 24: Typo in variable 'closable', expected variable name 'closeable': ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 68 (Checkstyle:VariableNameCheck)
     [java] 25: There should be an empty line between assigning and using variable 'closable', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/missing_empty_line_check.markdown: ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 69 (Checkstyle:MissingEmptyLineCheck)
     [java] 26: Rename exception variable 'e' to 'ioException': ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 82 (Checkstyle:ExceptionVariableNameCheck)
     [java] 27: Avoid using method 'printStackTrace': ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java 83 (Checkstyle:ExceptionPrintStackTraceCheck)
     [java] 28: ./modules/third-party/org-eclipse-equinox-console/build.gradle expected:<...	compileOnly group: ["org.apache.felix", name: "org.apache.felix.gogo.runtime", transitive: false, version: "1.1.6"
     [java] 	compileOnly group: "org.apache.felix", name: "org.apache.felix.gogo.shell", transitive: false, version: "1.1.4"
     [java] 	compileOnly group: "org.eclipse.platform", name: "org.eclipse.equinox.console", transitive: false], version: "1.4.500"...> but was:<...	compileOnly group: ['org.apache.felix', name: 'org.apache.felix.gogo.runtime', version: '1.1.6'
     [java] 	compileOnly group: 'org.apache.felix', name: 'org.apache.felix.gogo.shell', version: '1.1.4'
     [java] 	compileOnly group: "org.eclipse.platform", name: "org.eclipse.equinox.console"], version: "1.4.500"...>
     [java] 29: ./modules/apps/static/required-dependencies/required-dependencies/build.gradle expected:<...org.eclipse.equinox.[console", version: "1.4.500.LIFERAY-PATCHED-1"
     [java] 	compileOnly group: "com.liferay", name: "org.eclipse.equinox.metatype", version: "1.4.200.LIFERAY-PATCHED-5]"
     [java] 	compileOnly group...> but was:<...org.eclipse.equinox.[metatype", version: "1.4.200.LIFERAY-PATCHED-5"
     [java] 	compileOnly group: "com.liferay", name: "org.eclipse.equinox.console", version: "1.4.500.LIFERAY-PATCHED-1]"
     [java] 	compileOnly group...>
     [java] 30: ./modules/third-party/org-eclipse-equinox-console/src/main/java/org/eclipse/equinox/console/commands/DisconnectCommand.java expected:<...entifier: EPL-2.0
     [java]  *[
     [java]  * Contributors:
     [java]  *     Lazar Kirchev, SAP AG - initial API and implementation
     [java]  *******************************************************************************/
     [java] 
     [java] package org.eclipse.equinox.console.commands;
     [java] 
     [java] import java.io.BufferedReader;
     [java] import java.io.Closeable;
     [java] import java.io.IOException;
     [java] import java.io.InputStreamReader;
     [java] import java.io.PrintStream;
     [java] 
     [java] import java.util.Dictionary;
     [java] import java.util.Hashtable;
     [java] import java.util.List;
     [java] 
     [java] import org.apache.felix.service.command.CommandProcessor;
     [java] import org.apache.felix.service.command.CommandSession;
     [java] import org.apache.felix.service.command.Job;
     [java] 
     [java] import org.eclipse.equinox.console.telnet.TelnetConnection;
     [java] 
     [java] import org.osgi.framework.BundleContext;
     [java] 
     [java] /**
     [java]  * This class implements functionality to disconnect from telnet or ssh console.
     [java]  */
     [java] public class DisconnectCommand {
     [java] 
     [java] 	public DisconnectCommand(BundleContext context) {
     [java] 		this.context = context;
     [java] 	}
     [java] 
     [java] 	public void disconnect(CommandSession session) {
     [java] 		PrintStream consoleStream = session.getConsole();
     [java] 
     [java] 		consoleStream.print(DISCONNECT_MESSAGE);
     [java] 		consoleStream.flush();
     [java] 
     [java] 		BufferedReader reader = new BufferedReader(
     [java] 			new InputStreamReader(System.in));
     [java] 		String reply = null;
     [java] 
     [java] 		try {
     [java] 			reply = reader.readLine();
     [java] 		}
     [java] 		catch (IOException e) {
     [java] 			consoleStream.println("Error while reading confirmation");
     [java] 		}
     [java] 
     [java] 		if (reply != null) {
     [java] 			if (reply.toLowerCase(
     [java] 				).startsWith(
     [java] 					DISCONNECT_CONFIRMATION_Y
     [java] 				) || (reply.length() == 0)) {
     [java] 
     [java] 				Closeable closable = (Closeable)session.get(
     [java] 					TelnetConnection.CLOSEABLE);
     [java] 
     [java] 				if (closable != null) {
     [java] 					List<Job> jobs = session.jobs();
     [java] 
     [java] 					if (jobs.size() == 1) {
     [java] 						Job job = jobs.get(0);
     [java] 
     [java] 						if (job.status() == Job.Status.Foreground) {
     [java] 							job.background();
     [java] 						}
     [java] 					}
     [java] 
     [java] 					try {
     [java] 						closable.close();
     [java] 					}
     [java] 					catch (IOException e) {
     [java] 						e.printStackTrace();
     [java] 					}
     [java] 
     [java] 					return;
     [java] 				}
     [java] 
     [java] 				session.close();
     [java] 			}
     [java] 		}
     [java] 	}
     [java] 
     [java] 	public void startService() {
     [java] 		Dictionary<String, Object> props = new Hashtable<>();
     [java] 
     [java] 		props.put(CommandProcessor.COMMAND_SCOPE, "equinox");
     [java] 		props.put(
     [java] 			CommandProcessor.COMMAND_FUNCTION, new String[] {"disconnect"});
     [java] 		context.registerService(DisconnectCommand.class.getName(), this, props);
     [java] 	}
     [java] 
     [java] 	private static final String DISCONNECT_CONFIRMATION_Y = "y";
     [java] 
     [java] 	private static final String DISCONNECT_MESSAGE =
     [java] 		"Disconnect from console? (y/n; default=y) ";
     [java] 
     [java] 	private final BundleContext context;
     [java] 
     [java] }]> but was:<...entifier: EPL-2.0
     [java]  *[ 
     [java]  * Contributors:
     [java]  *     Lazar Kirchev, SAP AG - initial API and implementation
     [java]  *******************************************************************************/
     [java] package org.eclipse.equinox.console.commands;
     [java] 
     [java] import java.io.BufferedReader;
     [java] import java.io.IOException;
     [java] import java.io.InputStreamReader;
     [java] import java.util.List;
     [java] import java.io.PrintStream;
     [java] import java.util.Dictionary;
     [java] import java.util.Hashtable;
     [java] 
     [java] import org.apache.felix.service.command.CommandProcessor;
     [java] import org.apache.felix.service.command.CommandSession;
     [java] import org.apache.felix.service.command.Job;
     [java] import org.apache.felix.service.command.Job.Status;
     [java] import org.eclipse.equinox.console.telnet.TelnetConnection;
     [java] 
     [java] import java.io.Closeable;
     [java] import org.osgi.framework.BundleContext;
     [java] 
     [java] /**
     [java]  * This class implements functionality to disconnect from telnet or ssh console.
     [java]  */
     [java] public class DisconnectCommand {
     [java] 	private static final String DISCONNECT_MESSAGE = "Disconnect from console? (y/n; default=y) ";
     [java] 	private static final String DISCONNECT_CONFIRMATION_Y = "y";
     [java] 	
     [java] 	private BundleContext context;
     [java] 	
     [java] 	public DisconnectCommand(BundleContext context) {
     [java] 		this.context = context;
     [java] 	}
     [java] 	
     [java] 	public void startService() {
     [java] 		Dictionary<String, Object> props = new Hashtable<>();
     [java] 		props.put(CommandProcessor.COMMAND_SCOPE, "equinox");
     [java] 		props.put(CommandProcessor.COMMAND_FUNCTION, new String[] {"disconnect"});
     [java] 		context.registerService(DisconnectCommand.class.getName(), this, props);
     [java] 	}
     [java] 	
     [java] 	public void disconnect(CommandSession session) {
     [java] 		PrintStream consoleStream = session.getConsole();
     [java] 		consoleStream.print(DISCONNECT_MESSAGE);
     [java] 		consoleStream.flush();
     [java] 		
     [java] 		BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
     [java] 		String reply = null;
     [java] 		try {
     [java] 			reply = reader.readLine();
     [java] 		} catch (IOException e) {
     [java] 			consoleStream.println("Error while reading confirmation");
     [java] 		}
     [java] 		
     [java] 		if (reply != null) {
     [java] 			if (reply.toLowerCase().startsWith(DISCONNECT_CONFIRMATION_Y) || reply.length() == 0) {
     [java] 				Closeable closable = (Closeable)session.get(TelnetConnection.CLOSEABLE);
     [java] 				if (closable != null) {
     [java] 					List<Job> jobs = session.jobs();
     [java] 
     [java] 					if (jobs.size() == 1) {
     [java] 						Job job = jobs.get(0);
     [java] 
     [java] 						if (job.status() == Status.Foreground) {
     [java] 							job.background();
     [java] 						}
     [java] 					}
     [java] 
     [java] 					try {
     [java] 						closable.close();
     [java] 					} catch (IOException e) {
     [java] 						e.printStackTrace();
     [java] 					}
     [java] 					return;
     [java] 				}
     [java] 				
     [java] 				session.close();
     [java] 			}
     [java] 		}
     [java] 	}
     [java] }
     [java] ]>
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-07/test-1-10/test-portal-source-format/4465/source-format-current-branch-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by ericyanLr** [comment]
Hi @catarineaguiar , 

I just updated my branch to fix the mentioned conflicts / SF issues.

Re-running tests.

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:stop

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found from the relevant tests. And manual testing for https://liferay.atlassian.net/browse/LPS-189944 passed.

**Comment by tinatian** [comment]
@ericyanLr Could you please modify the commit message to show "Update third-party library: org.eclipse.equinox.console from 1.4.300 to 1.4.500"?

Thanks.
Tina.

**Comment by ericyanLr** [comment]
After discussing with Tina, will re-send PR to create a patch with the currently used version: 1.4.300, not the newer 1.4.500.

**Pull request closed without merging**
