### PR TITLE
[SampleSQLBuilder-user-private-layout]Lpd 25483

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPD-25483

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@slnn Please change the commit message according to the SF error.

**Review by dantewang — APPROVED** [review]

**Comment by slnn** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou  @tinatian

**Pull request closed without merging**
