### PR TITLE
[Remove Blocking usages]LPS-200450 

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace blocking ServiceProxyFactory with Snapshot in class `AssetSearcherFactoryUtil`. Thanks.
https://liferay.atlassian.net/browse/LPS-200450

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143957

cc @shuyangzhou @tinatian

**Pull request closed without merging**
