### PR TITLE
[Remove Stream/Optional usage] LPS-174298 Remove usages of Stream for module: portal-workflow-metrics-rest-spi

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(2/2 8:34)

**Comment by W2jx** [comment]
no conflicts(2/7 14:08)

**Comment by W2jx** [comment]
no conflicts(2/8 9:05)

**Comment by W2jx** [comment]
no conflicts(2/10 9:06)

**Comment by tinatian** [comment]
@W2jx Please fix the commit message at https://github.com/liferay-core-infra/liferay-portal/pull/3250/commits/281d3c6068a9375e35f1bc0e76e683e21f13d631. 
You did not "Replace parallelStream with for loop" as there is no for loop in your code.

Tina.

**Comment by dantewang** [comment]
Please resend, thanks.

**Pull request closed without merging**
