### PR TITLE
[DL Performance] LPS-153702 Avoid preparing action list when not showing actions

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian @yuhai @slnn

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:document

**Comment by dantewang** [comment]
CI passed previously as https://github.com/GinsonRen/liferay-portal/pull/611#issuecomment-1125957884

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Tina

**Comment by catarineaguiar** [comment]
@dantewang I found a possible regression, when trying to edit a collection filter:

Steps to reproduce:

- In categories create a vocabulary with two categories
- Create two web contents and select the categories
- Create a collection with the two web contents
- Create a page and put the collection display fragment
- Select your collection in the collection display fragment
- Put a collection filter fragment in the page

Actual result:
Is not possible to edit the collection filter fragment (only the "Display a collection on the page that support at least one filter type." message is present)

Expected:
Is possible to select a Target Collection and edit the filter

**Comment by catarineaguiar** [comment]
Hi @dantewang, my apologies, i double checked and the error is not related to your changes. The pull is good to go.

**Comment by dantewang** [comment]
Thanks @catarineaguiar!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/118106

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
