### PR TITLE
Lps 150076 3 29

### PR DESCRIPTION
**Pull request by slnn**
/cc @dantewang @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
@zhangyan0701 Are the 3 failures of elasticsearch unit tests unique? @slnn Please look into it if they are unique.

**Comment by slnn** [comment]
> @slnn Since you moved all logic into the `SearchBarPortletDisplayContextBuilder` and removed all the setters, this class should not be called a `Builder` any more. I think renaming it to `SearchBarPortletDisplayContextFactory` will be better.

OK, got it

**Comment by slnn** [comment]
Hi @dantewang 

I rename the `SearchBarPortletDisplayContextBuilder` to `SearchBarPortletDisplayContextFactory`, and also rename the metod `build()` to `create()`, the change has been force-pushed.

For the 3 failures of elasticsearch unit tests, I did not reproduce it locally with my changes.
```
com.liferay.portal.search.elasticsearch7.internal.rescore.RescorerTest.testRescore
com.liferay.portal.search.elasticsearch7.internal.rescore.RescorerTest.testRescoreQuery
com.liferay.portal.search.elasticsearch7.internal.rescore.RescorerTest.testRescores
```

**Comment by zhangyan0701** [comment]
The elasticsearch unit tests are unrelated, this is an known flaky issue: [LPS-142954](https://issues.liferay.com/browse/LPS-142954). And they passed in the ci:test:acceptance of this pull.

**Comment by zhangyan0701** [comment]
Also take a look at the results of ci:test:acceptance, no related failures.

**Comment by dantewang** [comment]
Lily will resend

ci:close

**Pull request closed without merging**
