### PR TITLE
LPS-155715 DBPartition Cache Support

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:cluster

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
@tinatian  This is throwing an error when a new company is added with DB partition enabled.
```
2022-06-30 18:55:46.243 INFO  [http-nio-8080-exec-1][CompanyIndexFactory:51] liferay-43210
2022-06-30 18:55:50.851 ERROR [liferay/background_task-4][BackgroundTaskMessageListener:185] Unable to execute background task
java.lang.NullPointerException: null
        at com.liferay.portal.security.permission.BasePermissionChecker.init(BasePermissionChecker.java:113) ~[portal-impl.jar:?]
        at com.liferay.portal.security.permission.AdvancedPermissionChecker.init(AdvancedPermissionChecker.java:261) ~[portal-impl.jar:?]
        at com.liferay.portal.security.permission.PermissionCheckerFactoryImpl.create(PermissionCheckerFactoryImpl.java:64) ~[portal-impl.jar:?]
        at com.liferay.portal.background.task.internal.BackgroundTaskThreadLocalManagerImpl.setThreadLocalValues(BackgroundTaskThreadLocalManagerImpl.java:138) ~[bundleFile:?]
        at com.liferay.portal.background.task.internal.ThreadLocalAwareBackgroundTaskExecutor.execute(ThreadLocalAwareBackgroundTaskExecutor.java:75) ~[bundleFile:?]
        at com.liferay.portal.background.task.internal.messaging.BackgroundTaskMessageListener.doReceive(BackgroundTaskMessageListener.java:138) [bundleFile:?]
        at com.liferay.portal.kernel.messaging.BaseMessageListener.doReceive(BaseMessageListener.java:48) [portal-kernel.jar:?]
        at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:34) [portal-kernel.jar:?]
        at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74) [portal-kernel.jar:?]
        at com.liferay.portal.messaging.internal.ParallelDestination$1.run(ParallelDestination.java:56) [bundleFile:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

Steps used:
1. Go to Control Panel > Virtual Instances
2. Input Required fields and click "Save"

After the error, the instance is accessible but it does not show up in the Virtual Instances portlet. This will prevent the admin from managing the new instance in the UI.

--

Aside from this regression, the test I added for the base scenario in LPS-155715 is passing.

**Comment by vicnate5** [comment]
@tinatian Another issue found during testing on Clustering + DB Partition

Steps to Reproduce:
1. Setup tomcat node with properties
```
cluster.link.enabled=true
database.partition.enabled=true
```
2. Start Tomcat

```
ERROR [Framework Event Dispatcher: Equinox Container: 83606735-9f00-486c-83dd-bf0e475f7a56][Framework:47] FrameworkEvent ERROR
java.lang.ClassCastException: com.liferay.portal.cache.ehcache.internal.DBPartitionPortalCache cannot be cast to com.liferay.portal.cache.ehcache.internal.EhcachePortalCache
        at com.liferay.portal.cache.ehcache.internal.EhcachePortalCacheManager.removeConfigurableEhcachePortalCacheListeners(EhcachePortalCacheManager.java:327) ~[?:?]
        at com.liferay.portal.cache.BasePortalCacheManager.reconfigPortalCache(BasePortalCacheManager.java:294) ~[?:?]
        at com.liferay.portal.cache.ehcache.internal.EhcachePortalCacheManager.reconfigurePortalCaches(EhcachePortalCacheManager.java:83) ~[?:?]
        at com.liferay.portal.cache.internal.PortalCacheExtender._configure(PortalCacheExtender.java:109) ~[?:?]
        at com.liferay.portal.cache.internal.PortalCacheExtender.access$100(PortalCacheExtender.java:45) ~[?:?]
        at com.liferay.portal.cache.internal.PortalCacheExtender$1.addingBundle(PortalCacheExtender.java:58) ~[?:?]
        at com.liferay.portal.cache.internal.PortalCacheExtender$1.addingBundle(PortalCacheExtender.java:50) ~[?:?]
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:475) ~[org.eclipse.osgi.jar:?]
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1) ~[org.eclipse.osgi.jar:?]
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[org.eclipse.osgi.jar:?]
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) ~[org.eclipse.osgi.jar:?]
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908) [org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:230) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:137) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:129) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:191) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.container.Module.publishEvent(Module.java:476) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.container.Module.start(Module.java:467) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi.jar:?]
```

**Pull request closed without merging**
