### PR TITLE
[Method References] LPS-162593 Convert method references to field references in modules license-manager-web、login-*

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I convert method references to field references in modules license-manager-web、login-*.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by zhangyan0701** [comment]
ci:test:license

**Comment by zhangyan0701** [comment]
ci:test:license

**Comment by zhangyan0701** [comment]
Tests passed, no regressions found.

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
