### PR TITLE
LPS-149082 Remove commons-beanutils.jar

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
@koor4356 please help me check the results when available, thanks!

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
@guilhermedcamacho 
With the changes you made, can we retest?

**Comment by guilhermedcamacho** [comment]
I only changed the portal-kernel version, I think you can analyze with the results we already have. 
Maybe @vicnate5 can help us on this answer. Thanks!

**Comment by vicnate5** [comment]
@koor4356 @guilhermedcamacho No need to re-run testing just for Semver change.

**Comment by koor4356** [comment]
@guilhermedcamacho 
This looks good, thanks!

**Comment by guilhermedcamacho** [comment]
@shuyangzhou , this PR is ready for your review. Thanks!

**Comment by shuyangzhou** [comment]
@guilhermedcamacho can you add an unit test for the new BeanTestUtil to assert the behaviors?

**Comment by guilhermedcamacho** [comment]
> @guilhermedcamacho can you add an unit test for the new BeanTestUtil to assert the behaviors?

Sure! thanks

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:acceptance

**Comment by vicnate5** [comment]
@catarineaguiar Can you check this one?

**Comment by vicnate5** [comment]
Majority of integration tests failed here, going to re-run relevant to confirm this isn't a real issue

The acceptance results crashed, but do not think we should re-run since we already tested this. Will rely on Relevant.

**Comment by vicnate5** [comment]
@guilhermedcamacho the startup error affecting in integration tests looks like this https://testray.liferay.com/reports/production/logs/2022-04/test-1-25/test-portal-acceptance-pullrequest(master)/2247/modules-integration-mysql57-jdk8/1/3/jenkins-console.txt.gz?authuser=0

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
> Majority of integration tests failed here, going to re-run relevant to confirm this isn't a real issue
> 
> The acceptance results crashed, but do not think we should re-run since we already tested this. Will rely on Relevant.

Makes sense @vicnate5. I only added an unit test class after Koor approval on this PR.

**Comment by guilhermedcamacho** [comment]
> ci:test:relevant

The CI was stuck on this PR, so I did a pull rebase, solve conflict related to semantic version and then ran it again. 
Thanks a lot :+1:

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
@vicnate5, can you take a look on these new results? Thanks!

**Comment by vicnate5** [comment]
@guilhermedcamacho Only 1 issue here in the results

`PMD VIOLATION: /opt/dev/projects/github/liferay-portal/portal-impl/test/unit/com/liferay/portal/kernel/test/util/BeanTestUtilTest.java:156 > Ensure you override both equals() and hashCode() (PMD Rule: OverrideBothEqualsAndHashcode)` [Log](https://testray.liferay.com/reports/production/logs/2022-04/test-1-36/test-portal-acceptance-pullrequest(master)/903/pmd-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
I ran buildRest again, because a new class was introduced (BaseObjectValidationRuleResourceTestCase) after a pull rebase from upstream.

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@tinatian @guilhermedcamacho No regressions found.

**Comment by guilhermedcamacho** [comment]
@shuyangzhou , this PR is ready for your review again. Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/guilhermedcamacho/liferay-portal/pull/79

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
