### PR TITLE
[System Properties] LPS-154947 Replace method System.getProperty() with method SystemProperties.get()

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I replace method System.getProperty() with method SystemProperties.get() in this pr.

Detail: https://github.com/liferay-core-infra/liferay-portal/pull/1221

### CODE REVIEW

**Comment by W2jx** [comment]
Hi  @catarineaguiar , Could you please help me check the test results when they finish ? Thanks!

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Review by dantewang — CHANGES_REQUESTED** [review]
@W2jx Please modify your commit message to "replace A with B for [properties description]", like:

> LPS-154947 SystemProperties: Replace System.getProperty() with SystemProperties.get() for properties defined in system.properties

> LPS-154947 SystemProperties: Replace System.getProperty() with SystemProperties.get() for "liferay.home"

Make sure the message is informative and as short as possible at the same time.

**Comment by W2jx** [comment]
@dantewang I will resend it.

**Comment by W2jx** [comment]
Hi @dantewang @tinatian , I just reordered the commits and modified the commit message.

**Review by dantewang — APPROVED** [review]
@tinatian Code and commit messages approved.

**Comment by tinatian** [comment]
@W2jx @dantewang Please see https://github.com/liferay-core-infra/liferay-portal/pull/1267. 
I did not include this commit https://github.com/liferay-core-infra/liferay-portal/pull/1250/commits/0aa8235d1752ceb45d5b2e41d7665bff4d557ce2, there are some properties that not set by us, for example "cataline.base", let's keep them as before for now, let's only make the change when it is really needed, as currently we have to have both System.get and SystemProperties.get at the the same time in our code base, there is not a easy way to set a general rule when to use which.

**Pull request closed without merging**
