### PR TITLE
[Spring Beans] LPS-199553 Move AccessControlAdvisor and AccessControlPolicies to modules and removed from security-spring

### PR DESCRIPTION
**Pull request by julschong**
resubmitted for https://github.com/liferay-core-infra/liferay-portal/pull/5962#pullrequestreview-1741165208

Added [22aa5f1](https://github.com/liferay-core-infra/liferay-portal/pull/6183/commits/22aa5f15b0015be63c2c195ecc679eff78098c23) to change service tracker list to instance variable and close during deactivation.

> @julschong Please double check your PR and resend. Additionally, I see you moved several classes that are neither Spring Beans, nor dependencies of the moved classes. What's the policy of moving these classes?

@dantewang Hi Dante,
`AccessControlAdvisor and AccessControlAdvice` are moved because I wanted to `AccessControlPolicy` interface to modules. 
Now looking back, `AccessControlPolicy` can actually have stayed in kernel, then this pull would be a lot shorter. But I thought I could do a more thorough move to modules if I also move the interface now.
My rule for moving classes is to just move Spring bean or dependencies but this time I went a little further.

Would you like me to remove that part of the code?

Thanks!

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
FYI @W2jx

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by julschong** [comment]
rebased to resolve conflict in `portal-impl/src/META-INF/security-spring.xml`

**Comment by julschong** [comment]
ci:test:sf

**Pull request closed without merging**
