### PR TITLE
[2/2] LPS-145396 When we delete some types of objects in Liferay, we are not deleting their ResourcePermission records - TESTS

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
[2/2] When we delete some types of objects in Liferay, we are not deleting their ResourcePermission records, leaving some orphan data in the ResourcePermission table.

@tinatian this PR contains the tests rewritten to use the data DataGuardTestRuleUtil:
   - As the DataGuardTestRuleUtil gets all the records before and after the test execution, I have added some code that checks all the remaining ResourcePermission and verify that they point to other models that are not deleted.
   - If the related object is deleted (it wasn't captured by __captureDataMap()_), that means the ResourcePermission is orphan.
   - The main advantage from my previous code of PR https://github.com/liferay-core-infra/liferay-portal/pull/368 is we can verify everything without additional accesses to the database and without adding additional test rules.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:acceptance

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@jorgediaz-lr Your code is confusing me. 
Suppose I did not clean up resource permission correctly when I remove a user. In this case, the captured data map will have those ResourcePermission entries, then those ResourcePermission entries will be removed in _autoDeleteAndAssert(), and your _orphanDetection checking will still use the captured data map before the _autoDeleteAndAssert().

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

I am executing `_orphanDetection` after executing the `_autoDeleteAndAssert` because my idea was to always delete any test object leftover, even if the test is leaving orphan data

- If `_orphanDetection` detects an orphan ResourcePermission object but it is executed before `_autoDeleteAndAssert`, the Assert.assertTrue here https://github.com/liferay-core-infra/liferay-portal/pull/458/files#diff-d987badaa7c5a1822c10382d9cfdc8711f3edad59b1b198cca0ffbd9790a7837R590 will fail and the cleanup code of `_autoDeleteAndAssert` won't be executed, leaving lots of leftovers in the database that can affect the execution of the following tests
- So my idea was to just save the dataMap before executing the `_autoDeleteAndAssert`, so after the auto-delete is done correctly, we can compare the dataBag._dataMap variable (_database data before test execution_) and dataMap variable (_database data after test execution, but before the data cleanup_) and check that there are no orphan records left by the test execution.

About your message:

> Suppose I did not clean up resource permission correctly when I remove a user. In this case, the captured data map will have those ResourcePermission entries, then those ResourcePermission entries will be removed in _autoDeleteAndAssert(), and your _orphanDetection checking will still use the captured data map before the _autoDeleteAndAssert().

As I explained before, that is just what I want to do, as I want to check if the test code is leaving orphan data but I also want to execute the autoDelete code to avoid leaving any object leftover after the test, so the code execution flow is:

1. `DataGuardTestRuleUtil.beforeClass` executes a _captureDataMap()
2. << test code is executed>> _here the test creates and deletes objects, the tests don't usually delete everything they have created, some of the objects are orphan data from bugs of the delete operations and other objects are fine but must be deleted by the DataGuardTestRuleUtil_
3. `DataGuardTestRuleUtil.afterClass` executes a _captureDataMap()
4. `_autoDeleteAndAssert` analyzes both dataMaps from before and after test execution and deletes all the objects created by the test execution to avoid leaving leftovers, it will assert an error in case the autoDelete code cannot delete everything
5. `_orphanDetection` analyzes both dataMaps from before and after test execution, to check the orphan ResourcePermission left by the test, it will assert an error in case the test left any orphan ResourcePermission

If you prefer executing  `_orphanDetection`  before `_autoDeleteAndAssert` I think that we can change this method, removing the Assert.assertTrue and returning the error information. After _autoDeleteAndAssert is executed, we can check the error information from _orphanDetection and execute the Assert.assertTrue.

Next week I will be available on Monday and Tuesday till 18.00 Madrid time (10.00 Los Angeles time) we can talk then.

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

Do you need any additional information?

Today I will be available till 18.00 Madrid time (10.00 Los Angeles time) 

I will be on PTO the rest of the week.

Regards,
Jorge

**Comment by tinatian** [comment]
@jorgediaz-lr Sorry that this takes so long, could you please rebase the code and resend? I will try to review it as soon as possible.

Thanks.
Tina.

**Comment by tinatian** [comment]
@jorgediaz-lr I am going to close this pull as code conflicts, please rebase and resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

I have rebased and sent it to https://github.com/liferay-core-infra/liferay-portal/pull/596

**Pull request closed without merging**
