### PR TITLE
[TS] LPS-155624 Web Content is temporarily unavailable when a web content has a decimal version with DB2

### PR DESCRIPTION
**Pull request by ricardocousolr**
(resent from https://github.com/liferay-core-infra/liferay-portal/pull/935)

As requested by @tinatian in https://github.com/liferay-core-infra/liferay-portal/pull/935#issuecomment-1152676659, I've added a test that reveals the issue, namely getting an article with a decimal version. Note that it's necessary to clear the cache because the method `JOurnalArticlePeristenceImpl#cacheUniqueFindersCache` will cache the same query even if it hasn't been explicitly run.

I've also reorder the commits in the previous pr.

Please let me know if you have any questions or further requirements. 

Thanks!

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
@yuhai Please take this one over, thanks!

**Comment by yuhai** [comment]
@ricardocousolr, @dantewang, please see https://github.com/liferay-core-infra/liferay-portal/pull/999

**Comment by yuhai** [comment]
ci:close

**Pull request closed without merging**
