### PR TITLE
LPS-185647 Fix transaction-related bug when deleting ResourceActions in a partitioned environment

### PR DESCRIPTION
**Pull request by mbowerman**
Set a TransactionConfig in the ActionableDynamicQuery to force the transaction to be committed after all the performAction calls finish running. This will ensure that we commit the transaction before switching over to the next partition (which would cause the transaction commit to fail if it were to happen).

Since we are calling this inside of `_forEachCompanyId`, we need to make sure that the Transaction is committed before we move on to the next partition. To accomplish this, I set a TransactionConfig in the actionableDynamicQuery object, which causes the ActionableDynamicQuery framework to commit the Transaction upon completing each `doPerformActions` call (see [here](https://github.com/liferay/liferay-portal/blob/71397801f3b041fa54fe6d25cbe2a9830daea102/portal-kernel/src/com/liferay/portal/kernel/dao/orm/DefaultActionableDynamicQuery.java#L322-L33)).

Could you please take a look and let me know if this is the right fix? Thanks!

Ticket: [LPS-185647](https://issues.liferay.com/browse/LPS-185647)

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:db-partition

**Comment by zhangyan0701** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
@mbowerman I found no regressions, but I tested the issue and this doesn't fix it.

**Comment by mbowerman** [comment]
Thanks for testing this @Kvale1733. I tried to test it in master but I ran into issues with the Objects portlet where I wasn't able to add Actions. I started threads in the [Uniform Channel](https://liferay.slack.com/archives/CUQP9C673/p1685117280993639) as well as the [Core Infra Channel](https://liferay.slack.com/archives/C01FP01V5L0/p1685117470414289 to discuss a more complete solution for this issue.

**Pull request closed without merging**
