### PR TITLE
[TS] LPS-199001 - underscores in path to language.properties file can cause errors

### PR DESCRIPTION
**Pull request by wanderlast**
Hi Core team!

This is a fix for an issue in [LPS-183708](https://liferay.atlassian.net/browse/LPS-183708). Currently, we check for the presence of an underscore character to see if there's a language ID to grab in the properties file name. However, this can cause issues in the case of Language.properties files with underscores present in one of the directories (e.g. /shared_content/Language.properties). The solution simply checks in a more specific location for the underscore character before attempting to grab a languageID.

### CODE REVIEW

**Comment by dantewang** [comment]
@brunofalc Another PR that should be marked as TS.

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
ci:stop:relevant

**Comment by yuhai** [comment]
Hi @wanderlast,

I edit the commit message and add one SF commit. Please see https://github.com/liferay-core-infra/liferay-portal/pull/5792. Please kindly let me know if it can't solve the issue.

Thanks,
Hai

**Pull request closed without merging**
