### PR TITLE
[Components with more than 1 service] LPS-189642 Refactor components from portal-workflow module

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-189642

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:workflow

**Comment by liuxingye** [comment]
ci:test:stable

**Comment by liuxingye** [comment]
The test results for [relevant](https://testray.liferay.com/home/-/testray/runs?tab=results&testrayBuildId=2372268782), [workflow](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2373206879) and [startup](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2372216288) are look good to me. 

cc @slnn @zhangyan0701

**Comment by dantewang** [comment]
@MrJohn1911 Please see https://github.com/MrJohn1911/liferay-portal/pull/29, and resend, thanks!

**Pull request closed without merging**
