### PR TITLE
LPS-143631 Remove JSONFactoryUtil usages in modules part 2

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong possible regression:

```
[exec] com.liferay.document.library.opener.onedrive.web.internal.oauth.OAuth2ControllerTest > testRedirectingOAuth2ControllerWithAccessToken FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.document.library.opener.onedrive.web.internal.oauth.OAuth2ControllerFactory$OAuth2Result.getResponseJSONObject(OAuth2ControllerFactory.java:226)
     [exec]         at com.liferay.document.library.opener.onedrive.web.internal.oauth.OAuth2ControllerFactory$RedirectingOAuth2Controller.execute(OAuth2ControllerFactory.java:261)
     [exec]         at com.liferay.document.library.opener.onedrive.web.internal.oauth.OAuth2ControllerTest.testRedirectingOAuth2ControllerWithAccessToken(OAuth2ControllerTest.java:216)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
     [exec]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-29/test-portal-acceptance-pullrequest(master)/5042/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
removed change for OAuth2ControllerFactory, will include in later pull where unit tests are modified

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/124835

**Pull request closed without merging**
