### PR TITLE
LPS-199946 Merge AccessControl interface and impl into Util and move to portal-impl

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
@julschong error to compile:

```
     [exec] > Task :apps:portal-security:portal-security-auth-verifier-test:compileTestIntegrationJava FAILED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-security/portal-security-auth-verifier-test/src/testIntegration/java/com/liferay/portal/security/auth/verifier/test/AuthVerifierTest.java:9: error: cannot find symbol
     [exec] import com.liferay.portal.kernel.security.access.control.AccessControlThreadLocal;
     [exec]                                                         ^
     [exec]   symbol:   class AccessControlThreadLocal
     [exec]   location: package com.liferay.portal.kernel.security.access.control
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-security/portal-security-auth-verifier-test/src/testIntegration/java/com/liferay/portal/security/auth/verifier/test/AuthVerifierTest.java:434: error: cannot find symbol
     [exec] 				String.valueOf(AccessControlThreadLocal.isRemoteAccess()));
     [exec] 				               ^
     [exec]   symbol:   variable AccessControlThreadLocal
     [exec]   location: class com.liferay.portal.security.auth.verifier.test.AuthVerifierTest.RemoteAccessHttpServlet
     [exec] 2 errors
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-38/test-portal-acceptance-pullrequest(master)/9433/modules-compile-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

other regressions:
```
[beanshell]      [exec] com.liferay.portal.json.web.service.client.internal.JSONWebServiceClientImplSSLGetTest > test200OKOnGetIfTLS11 FAILED
[beanshell]      [exec]     Unable to transmit request to localhost
[beanshell]      [exec]         at com.liferay.portal.json.web.service.client.BaseJSONWebServiceClientImpl.execute(BaseJSONWebServiceClientImpl.java:854)
[beanshell]      [exec]         at com.liferay.portal.json.web.service.client.BaseJSONWebServiceClientImpl.doGet(BaseJSONWebServiceClientImpl.java:253)
[beanshell]      [exec]         at com.liferay.portal.json.web.service.client.BaseJSONWebServiceClientImpl.doGet(BaseJSONWebServiceClientImpl.java:227)
[beanshell]      [exec]         at com.liferay.portal.json.web.service.client.internal.JSONWebServiceClientImplSSLGetTest.test200OKOnGetIfTLS11(JSONWebServiceClientImplSSLGetTest.java:39)
[beanshell]      [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
```
[beanshell]      [exec] com.liferay.portal.servlet.filters.authverifier.AuthVerifierFilterTest > testHttpsRequiredWithHttpRequestAndProxyPath FAILED
[beanshell]      [exec]     java.lang.AssertionError: expected:<https://localhost/liferay123> but was:<null>
[beanshell]      [exec]         at org.junit.Assert.fail(Assert.java:88)
[beanshell]      [exec]         at org.junit.Assert.failNotEquals(Assert.java:834)
[beanshell]      [exec]         at org.junit.Assert.assertEquals(Assert.java:118)
[beanshell]      [exec]         at org.junit.Assert.assertEquals(Assert.java:144)
[beanshell]      [exec]         at com.liferay.portal.servlet.filters.authverifier.AuthVerifierFilterTest.testHttpsRequiredWithHttpRequestAndProxyPath(AuthVerifierFilterTest.java:145)
[beanshell]      [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell]      [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
```
[beanshell]      [exec] com.liferay.portal.json.web.service.client.internal.JSONWebServiceClientImplSSLGetTest > test200OKOnGetIfTLS12 FAILED
[beanshell]      [exec]     java.lang.UnsupportedOperationException: HTTP server is already running
[beanshell]      [exec]         at com.liferay.portal.json.web.service.client.server.simulator.HTTPSServerSimulator.start(HTTPSServerSimulator.java:39)
[beanshell]      [exec]         at com.liferay.portal.json.web.service.client.internal.JSONWebServiceClientImplSSLGetTest.test200OKOnGetIfTLS12(JSONWebServiceClientImplSSLGetTest.java:55)
[beanshell]      [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell]      [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[beanshell]      [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-38/test-portal-acceptance-pullrequest(master)/9433/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@julschong when you are ready for QA to look at this, please remove the `QA Failed` label

**Comment by zhangyan0701** [comment]
Issue found:

Tests
[com.liferay.portal.servlet.filters.secure.BaseAuthFilterTest](https://testray.liferay.com/home/-/testray/case_results/2448535743)
[com.liferay.portal.servlet.filters.authverifier.AuthVerifierFilterTest](https://testray.liferay.com/home/-/testray/case_results/2448535732)
failed with error like below:
java.lang.AssertionError: expected:<https://localhost/liferay123/abc123?a=1> but was:<null>

Full console log:
https://testray.liferay.com/reports/production/logs/2023-10/test-1-25/test-portal-acceptance-pullrequest(master)/4046/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0

**Comment by Kvale1733** [comment]
ci:close

**Comment by julschong** [comment]
@zhangyan0701 Hi Summer,
This is more complex than I thought :(
For BaseAuthFilterTest and AuthVerifierFilterTest, there seem to be regression on master already. could you please help me verify that?
```
com.liferay.portal.servlet.filters.authverifier.AuthVerifierFilterTest > testHttpsRequiredWithHttpRequestAndXForwardedHostAndXForwardedPort FAILED
    java.lang.NullPointerException
        at com.liferay.portal.kernel.util.PrefsPropsUtil.getString(PrefsPropsUtil.java:204)
        at com.liferay.portal.util.PortalImpl.getCDNHostHttps(PortalImpl.java:1658)
        at com.liferay.portal.util.PortalImpl.isValidPortalDomain(PortalImpl.java:5991)

com.liferay.portal.servlet.filters.secure.BaseAuthFilterTest > testHttpsRequiredWithHttpRequestAndXForwardedHostAndXForwardedPort FAILED
    java.lang.NullPointerException
        at com.liferay.portal.kernel.util.PrefsPropsUtil.getString(PrefsPropsUtil.java:204)
        at com.liferay.portal.util.PortalImpl.getCDNHostHttps(PortalImpl.java:1658)
        at com.liferay.portal.util.PortalImpl.isValidPortalDomain(PortalImpl.java:5991)
        at com.liferay.portal.util.PortalImpl.isValidPortalDomain(PortalImpl.java:7429)
        at com.liferay.portal.util.PortalImpl.getForwardedHost(PortalImpl.java:2245)
        at com.liferay.portal.util.PortalImpl.getPortalURL(PortalImpl.java:3851)
        at com.liferay.portal.kernel.util.PortalUtil.getPortalURL(PortalUtil.java:1153)



```

**Comment by zhangyan0701** [comment]
Hi @julschong 

I have checked the history of the two tests, they only failed here. Relevant tests ran two times in this pull, and the tests failed on both runs with same error.

The error here is AssertionError, not NPE:
`java.lang.AssertionError: expected:<https://test.liferay.com:1234> but was:<null>`

**Pull request closed without merging**
