### PR TITLE
LPD-20946 ResourcePermission population | 9-5

### PR DESCRIPTION
**Pull request by dantewang**
Hi @tinatian I appended an additional commit that makes the company-aware model resource's permission population also company-aware, as we are doing company-aware deletion.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:object

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by tinatian** [comment]
@JerryAdrianoo Please run startup test

**Comment by dantewang** [comment]
Testray import is still not working as of the moment of this comment (17:12 China time). Even the core-functional import hasn't happened.

**Comment by JerryAdrianoo** [comment]
Hey @dantewang and @tinatian  for more details from this test, see: [spreadsheet](https://docs.google.com/spreadsheets/d/1wJVhtYuT1NeYIjpPpw4UighvtBkt77gmuzcYW6-m0-c/edit?usp=sharing) 

Branch| Startup Time (ms)(without  default HSQL data)  Cold start | Percent of Average Startup Time Cold Start | Startup Time (ms)(without  default HSQL data) Hot start | Average Startup Time (ms)(without default HSQL data)  Hot start | Percent of Average Startup Time Hot Start | Shutdown Time (ms)(without default HSQL data)   Cold start | Shutdown Time (ms)(without default HSQL data)  Hot start | Average Shutdown Time (ms)(without default HSQL data)  Hot start
-- | -- | -- | -- | -- | -- | -- | -- | --
Before LPD-31842 | **43,936** | | 16,146 | | | **2,583** | 2,016
|  | | | 16,202 | | | | 1,944
|  | | | 16,649 | | | | 2,006
 | | | | 16,076 | | | | 1,948
 | | | | 16,186 |**16,178** | | | 1,950 | **1,968**
-- | -- | -- | -- | -- | -- | -- | --
After LPD-31842 | **45,510** | | 16,029 | | | **2,635** | 1,942
|  | | | 16,605 | | | | 1,963
|  | | | 16,581 | | | | 1,920
|  | | | 16,463 | | | | 1,992
| | |  -3.46% | 16,397 |**16,480** |  **1.87**% | | 1,947 | **1,951**

**Open count of Prepared Statement | Count of Prepared Statement Query**
was increased by 4 and 6 respectively but **Open Count of SQL** was decreased by 347.

**Comment by dantewang** [comment]
ci:report:80082093

**Comment by dantewang** [comment]
ci:report:80015317

**Comment by dantewang** [comment]
ci:report:79979024

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 79979024.
> 
> Job Link: [generate-testray-csv](https://test-1-30.liferay.com/job/generate-testray-csv/265/)
> 
> Testray CSV Link: [testray-results-79979024.csv](https://test-1-30.liferay.com/userContent/jobs/generate-testray-csv/builds/265/testray-results-79979024.csv)

The 2 tests marked as unique should be flaky.

**Comment by dantewang** [comment]
ci:report:80035740

**Comment by dantewang** [comment]
@tinatian Appended [a commit](https://github.com/liferay-core-infra/liferay-portal/pull/7406/commits/f91a3844e9a23fccd39c20f73069ebb78f2ba633) which I think would address the increment of prepared statements, and hopefully also address the error in some DB partition upgrade tests in https://github.com/liferay-core-infra/liferay-portal/pull/7406#issuecomment-2333044455.

I will retrigger relevant and object, as previous errors in core-functional should be flaky.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:object

**Comment by dantewang** [comment]
ci:report:82429175

**Comment by dantewang** [comment]
ci:report:82429221

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
ci:report:82655206

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7408

**Pull request closed without merging**
