### PR TITLE
[Replace Non-Blocking Usage] LPS-198652 Replace non-blocking ServiceProxyFactory usages in classes RatingsDataTransformerUtil and CTPersistenceHelperUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(10/12 9:54)

**Comment by W2jx** [comment]
Hi @dantewang , this PR has been checked, and I used dynamic snapshot in commit [468dad4](https://github.com/liferay-core-infra/liferay-portal/pull/5754/commits/468dad4f15a1fabb740e2b50872baa8a9c026a9e)

**Comment by W2jx** [comment]
no conflicts(10/13 8:23)

**Comment by W2jx** [comment]
no conflicts(10/16 8:59)

**Comment by W2jx** [comment]
no conflicts(10/17 8:23)

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142339

**Pull request closed without merging**
