### PR TITLE
[Remove Stream/Optional usage] LPS-171888 headless PART 3

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend. Thanks!

Fixed regressions caused by [client_base_json_parser.ftl](https://github.com/liferay-core-infra/liferay-portal/commit/9e1f145a63d9789ba4704f0d6412ff0da2661d2c). Previously I use wrong method `parseToDTOs()`, which should be `parseToDTO()`.

And please note that I dropped two commits (https://github.com/liferay-core-infra/liferay-portal/pull/2987/commits/8d80f839a410b34f3f4c9c9beb21cdca48096587, https://github.com/liferay-core-infra/liferay-portal/pull/2987/commits/5616bb1cf7a37b5458a7b66aa679335b668a607c) to buy space.

Previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/2987

Ticket: https://issues.liferay.com/browse/LPS-171888

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:headless

**Comment by Kvale1733** [comment]
Lots of tests failed do to an unrelated saml issue that was fixed recently. Rerunning relevant.

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
So the saml issue isn't affecting the test results anymore but there is an unrelated compile issue with a search module causing many tests failures to be reported on CI now so these results still aren't very helpful. This is affecting other PR's also. I've notified the search team already to get this fixed as quick as possible.

**Comment by JanisZhang** [comment]
@Kvale1733 Thanks for your efforts!  We will wait for the latest test results.

**Comment by JanisZhang** [comment]
Waiting for https://github.com/brianchandotcom/liferay-portal/pull/128721 merge...

**Comment by JanisZhang** [comment]
re-trigger tests

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:headless

**Comment by catarineaguiar** [comment]
Waiting for https://github.com/brianchandotcom/liferay-portal/pull/128770 to be merged.

**Comment by JanisZhang** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/128770 merged, but network issues causing CI failures...

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:headless

**Comment by catarineaguiar** [comment]
@JanisZhang can you rebase and re-run tests suites, please?

Thanks, Cat.

**Comment by JanisZhang** [comment]
@catarineaguiar Sure thing. Thanks!

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:headless

**Comment by catarineaguiar** [comment]
@JanisZhang semver error:

```
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.notification.api-11.0.2.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.notification.api/11.0.1/6012bccc7a0cb557cde96a076e1d77590fafc4c7/com.liferay.notification.api-11.0.1.jar
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-35/test-portal-acceptance-pullrequest(master)/3373/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
@JanisZhang Please see https://github.com/liferay-core-infra/liferay-portal/pull/3140. Please note I did not include the ftl changes and auto generated, the reason is the ftl changes have some SF issue, for example: you should have space before and after "=", please resend that part.

Thanks.
Tina

**Pull request closed without merging**
