### PR TITLE
[SF] LPS-160079 Add more modules that we already fixed unused reference variables

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,
This is a follow-up pull to keep maintaining SF properties.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:forward

**Comment by JanisZhang** [comment]
ci:forward

**Comment by JanisZhang** [comment]
ci:forward

**Comment by JanisZhang** [comment]
ci:forward

**Comment by dantewang** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/124921

The SF failure is unrelated and will be fixed by Alan's PR https://github.com/brianchandotcom/liferay-portal/pull/124890

cc @shuyangzhou @tinatian

**Pull request closed without merging**
