### PR TITLE
remove_deprecated_part_9_portal_impl

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Fixed the error in https://github.com/liferay-core-infra/liferay-portal/pull/777
This is remove deprecated methods for portal-impl part nine.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result again, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/117904

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
