### PR TITLE
[TS] LPS-197573 Set id to portlet stored in map. 

### PR DESCRIPTION
**Pull request by DaneszLR**
Hi Team,

https://liferay.atlassian.net/browse/LPS-197573

Issue:
Customer wanted the id of portlets, but always received 0. It was because the map where the method gets the value, stored the id as 0.

Solution:
When a portlet is created in intention to be saved into the database, then we can set the id to the given portlet. In case of system portlets (which doesn't get saved into the database) the id stays 0. The original value has to modified, cannot just put the new portlet as value in the map, because PortletTracker sets in a lot of different values, before it gets saved into the map.

Testing:
Tested it locally following the ticket steps on a vanilla version.

Original pr:
https://github.com/liferay-core-infra/liferay-portal/pull/5804 - Current PR is null safe

Please review my PR!

Best regards,
Dani

### CODE REVIEW

**Comment by DaneszLR** [comment]
ci:test:relevant

**Comment by DaneszLR** [comment]
ci:test:stable

**Comment by zhangyan0701** [comment]
No regressions found.

Testing LPS-197573 passed: the id_ is not 0.

**Comment by yuhai** [comment]
Hi @DaneszLR,

The current fix can't fix the issue completely. If you restart portal with the non-empty database, it won't work.

In addition, for the kind of case, please firstly create the test case to expose it. Please resend it.

Thanks,
Hai

**Comment by DaneszLR** [comment]
Hi @yuhai Thank you for notice! Added the plus steps to the LPS. Also opened the new PR with tests here: https://github.com/liferay-core-infra/liferay-portal/pull/5941

**Pull request closed without merging**
