### PR TITLE
LPS-198859 Remove ThreadLocalDistributor, no usage

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by shuyangzhou** [comment]
@julschong please rebase, thanks!

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
added breaking change messages

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142560

**Pull request closed without merging**
