### PR TITLE
[Convert method references]LPS-163568 Convert method references to field references in module:po…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-163568

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to scan test results when they are finished?

Thanks
Lily

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
@slnn This change shouldn't work. The `PortletManager` is not a component but has `@Reference` on private fields, while the sub-classes are components, and the module doesn't have the "ds-annotation inherit" bnd instruction... Please double check whether these fields are really injected.

**Comment by slnn** [comment]
> PortletManager

Hi @dantewang 

I will double-check for this, I do this because I see this private field has been added with @Reference annotation in PortletManager.

https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal/portal-monitoring/src/main/java/com/liferay/portal/monitoring/internal/statistics/jmx/PortletManager.java#L370

**Comment by slnn** [comment]
Hi @dantewang 

This change does not work, even I add -dsannotations-options: inherit in the bnd, I will try other ways,

> @slnn This change shouldn't work. The `PortletManager` is not a component but has `@Reference` on private fields, while the sub-classes are components, and the module doesn't have the "ds-annotation inherit" bnd instruction... Please double check whether these fields are really injected.

**Pull request closed without merging**
