### PR TITLE
[Static reference] LPS-181523 Remove method reference by using snapshot in module site-navigation-taglib

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4234

changes：

1. remove field _portal and its reference first, and then convert the rest to Snapshot in class NavItemUtil

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:echo

**Review by dantewang — CHANGES_REQUESTED** [review]
@W2jx Please remove unused method in ServletContextUtil first, and then apply Snapshot.

**Comment by W2jx** [comment]
Hi @dantewang , I have updated them.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by W2jx** [comment]
no conflicts(4/17 8:08)

**Comment by W2jx** [comment]
no conflicts(4/18 9:28)

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
