### PR TITLE
[Method References 2] LPS-171146 Convert method reference to ServiceTrackerMap in module portal-workflow-kaleo-runtime-impl | part 2

### PR DESCRIPTION
**Pull request by W2jx**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/2754

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(12/30 14:57)

**Comment by W2jx** [comment]
no conflicts(1/3 9:07)

**Comment by W2jx** [comment]
no conflicts(1/4 9:03)

**Comment by W2jx** [comment]
no conflicts(1/5 8:59)

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/2943

**Pull request closed without merging**
