### PR TITLE
LPS-167276 Remove "immediate = true" from Tango

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:tango

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:tango

**Comment by Kvale1733** [comment]
No regressions found in relevant or startup. Rerunning tango suite as results weren't posted on Testray.

**Comment by Kvale1733** [comment]
@RenanUmV No regressions found.

**Comment by RenanUmV** [comment]
Hey @shuyangzhou , this one is good to go!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125866

**Pull request closed without merging**
