### PR TITLE
Lps 184766 equinox module part 1

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:smoke

**Comment by shuyangzhou** [comment]
ci:test:jdk11

**Comment by dantewang** [comment]
ci:test:stable

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the results of this PR? Thanks!

**Comment by zhangyan0701** [comment]
ci:test:jdk11

**Comment by zhangyan0701** [comment]
There are too many failures in jdk11 tests compared with upstream, so I re-trigger tests.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139965

**Pull request closed without merging**
