### PR TITLE
[Method References 2] LPS-176632 Convert method reference to ServiceTrackerMap in class CompositeFacetProcessor(module portal-search-solr8-impl)

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4070

**changes:**

1. Modify the test class as per [comment](https://github.com/liferay-core-infra/liferay-portal/pull/4172#discussion_r1166116242).

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:search-solr

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(4/19 8:03)

**Comment by W2jx** [comment]
no conflicts(4/20 7:56)

**Comment by W2jx** [comment]
no conflicts(4/21 8:22)

**Comment by W2jx** [comment]
no conflicts(4/24 11:16)

**Comment by W2jx** [comment]
no conflicts(4/25 8:02)

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
