### PR TITLE
[TS] LPD-21945

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team,

**Ticket:** https://liferay.atlassian.net/browse/LPD-21945

This PR includes the following changes:
- Patch one library to add a flag that allows for applying an optimization to shortcut (to avoid needing to resolve a class)
    - Based on Tomcat's optimization:
        - Bug ticket: https://bz.apache.org/bugzilla/show_bug.cgi?id=57583
        - Commit: https://github.com/apache/tomcat/commit/887780699806b5e72f601fc222e4b9c720e61d92
- Introduce our own custom ElResolver to utilize the flag to return early
    - This allows us to avoid needing to patch another third-party library (which is needed if we were to fully follow Tomcat's optimization)
    - We instead introduce our own ElResolver to apply the optimization to shortcut (logic based on Tomcat's optimization)

**Note:** The optimization is only applied for El Expressions that are not scoped (e.g. ${myExpression} ) and would not be applied to El Expressions that are scoped (e.g. ${scope.myExpression} )

This is to be expected, as the optimization was intended for only the non-scoped case.
- Reference: https://github.com/apache/tomcat/commit/887780699806b5e72f601fc222e4b9c720e61d92#diff-9967205f7459ab41b5ae1a6267e909602c9e963b13d32658a6483a936f1e0c6aR81-R87

I'll also leave a sample of my test results from my manual testing below.

Please let me know if you have any questions.
Thanks!

/cc @tinatian 

----

**Test Results - Manual Testing**
Looking at the test results from my manual testing, we can see that **testElExpressionWithUndefinedVariablesJsp** is much faster with our fix and **testElExpressionWithUndefinedScopedVariablesJsp** remains the same.

**Before Fix:**
- Completed com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest#testElExpressionWithUndefinedScopedVariablesJsp in **3129 ms**
- Completed com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest#testElExpressionWithUndefinedVariablesJsp in **3111 ms**
- Completed com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest#testJsp in **200 ms**

**After Fix:**
- Completed com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest#testElExpressionWithUndefinedScopedVariablesJsp in **3255 ms**
- Completed com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest#testElExpressionWithUndefinedVariablesJsp in **130 ms**
- Completed com.liferay.portal.osgi.web.servlet.jsp.compiler.test.JspServletPerformanceTest#testJsp in **144 ms**

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:stop

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:2559008029

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@ericyanLr As we talked, please resend.

Thanks.
Tina

**Pull request closed without merging**
