### PR TITLE
[Components with more than 1 service] LPS-175886 Refactor DTO Converter components with more than 1 service type from headless-admin-user-impl module

### PR DESCRIPTION
**Pull request by MrJohn1911**
Related pull: https://github.com/liferay-core-infra/liferay-portal/pull/3932
Ticket: https://issues.liferay.com/browse/LPS-175886

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:headless

**Comment by Kvale1733** [comment]
@MrJohn1911 Found a regression in

com.liferay.headless.builder.test.HeadlessBuilderTest
```
 [exec] com.liferay.headless.builder.test.HeadlessBuilderTest > testHeadlessBuilderApplication FAILED
     [exec]     java.lang.AssertionError: Thread Thread[http-nio-8080-exec-4,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=osgi.logging.com.liferay.headless.batch.engine.internal.resource.v1_0.ImportTaskResourceImpl, message=bundle com.liferay.headless.batch.engine.impl:4.0.40 (829)[com.liferay.headless.batch.engine.internal.resource.v1_0.ImportTaskResourceImpl(3409)] : The activate method has thrown an exception
     [exec]     java.lang.AssertionError: {level=ERROR, loggerName=osgi.logging.com.liferay.headless.batch.engine.internal.resource.v1_0.ImportTaskResourceImpl, message=bundle com.liferay.headless.batch.engine.impl:4.0.40 (829)[com.liferay.headless.batch.engine.internal.resource.v1_0.ImportTaskResourceImpl(3409)] : The activate method has thrown an exception
     [exec]     	at com.liferay.portal.test.rule.LogAssertionTestRule$LogAppender.append(LogAssertionTestRule.java:330)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
     [exec]     	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
     [exec]     	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
     [exec]     	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
     [exec]     	at org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:533)
     [exec]     	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:502)
     [exec]     	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-35/test-portal-acceptance-pullrequest(master)/4017/modules-integration-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
Hi @Kvale1733, can you please verify if this test (HeadlessBuilderTest.testHeadlessBuilderApplication) also fails in master? thanks!

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@MrJohn1911 Looks like it was a fluke. Passed in second run. No regressions found.

**Review by rafaprax — CHANGES_REQUESTED** [review]
Hey @MrJohn1911 this commit https://github.com/liferay-core-infra/liferay-portal/pull/4114/commits/c1d6e91321f278a643a63c12c44bfeeb891bc6ba must be before this 47eab1a3c3a755f1a367992a123bef28d7113442 one.

**Comment by MrJohn1911** [comment]
Last push was to reorder commits.

**Comment by tinatian** [comment]
@MrJohn1911 I did not see any benefit to do https://github.com/liferay-core-infra/liferay-portal/pull/4114/commits/141ada16d58dcd985e4ad8b2f95e956e4cb715a4, please talk with Prax and resend.

Thanks.
Tina.

**Pull request closed without merging**
