### PR TITLE
[Method References] LPS-163784 Convert method references to field references in module portal-search-elasticsearch7-impl | part 10

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I convert method references to field references in module portal-search-elasticsearch7-impl.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No related failures.

**Comment by dantewang** [comment]
@shuyangzhou @tinatian @W2jx See https://github.com/brianchandotcom/liferay-portal/pull/123867

**Pull request closed without merging**
