### PR TITLE
[TS] LPS-180849 Permission issue with shareable iframe fragments

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
The Guest user cannot see the contents of a shareable iframe, if it is put in a fragment.
The cause of the issue is that the Widget URL is pointing to the Draft Layout instead of the Published Layout.

Proposed Solution
========
With the agreement of the Echo Team, I'm proposing the following:

Place the widget URL generated from the published layout in the HTML fragment if the portlet is on the published layout. Otherwise, hide the fragment and display a help message instead.

Steps to Verify
========
Please see the linked LPS for the reproduction steps.
https://liferay.atlassian.net/browse/LPS-180849

Thank you and best regards,
István

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:echo

**Comment by lilylcl** [comment]
ci:test:security

**Comment by lilylcl** [comment]
The failures are not related to the current PR. @slnn Could you help to add QA Passed label? Thanks.

**Comment by yuhai** [comment]
Hi @IstvanD,

I just find the issue is not only related with **ANY WEBSITE** part, but also related with **FACEBOOK**(callbackURL),**OPENSOCIAL GADGET**(opensocialGadgetURL) and **NETVIBES**(netvibesWidgetURL) parts. These URL also use the draft layout friendlyURL.

I think we may use a message for the whole page. That is to say, if the portlet doesn't exist in the published layout, only one alert message displayed when accessing the Sharing page.

If this is good for you, could you please confirm it with the corresponding team?

**Comment by IstvanD** [comment]
Hi @yuhai 

Thank you for your feedback.
I'll share these concerns with the Echo Team.

**Pull request closed without merging**
