### PR TITLE
LPS-195925 | master

### PR DESCRIPTION
**Pull request by leilanyaragao**
Jira Issue: https://liferay.atlassian.net/browse/LPS-195925

Context: 
Initially the sanitization was made to the **External Reference Code(ERC)** of the `objectEntry`, however [Brian requested](https://github.com/brianchandotcom/liferay-portal/pull/142305#issuecomment-1766349029) that this change be applied to the `ServiceBuilder` to sanitize all **ERCs** on the portal.

### CODE REVIEW

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:service-builder

**Comment by brunofalc** [comment]
removed the ready for QA label because @leilanyaragao will send a new commit

**Comment by leilanyaragao** [comment]
ci:test:sf

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by brunofalc** [comment]
back to the game

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Hi @leilanyaragao There is a conflict, please resolve it first, thanks!

**Comment by leilanyaragao** [comment]
ci:test:sf

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by leilanyaragao** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:service-builder

**Comment by catarineaguiar** [comment]
@leilanyaragao the manual test passed, but a regen is needed:

```
     [echo] diff --git a/portal-impl/src/com/liferay/portal/service/persistence/impl/AddressPersistenceImpl.java b/portal-impl/src/com/liferay/portal/service/persistence/impl/AddressPersistenceImpl.java
     [echo] index 38c320a981e0..48105544518e 100644
     [echo] --- a/portal-impl/src/com/liferay/portal/service/persistence/impl/AddressPersistenceImpl.java
     [echo] +++ b/portal-impl/src/com/liferay/portal/service/persistence/impl/AddressPersistenceImpl.java
     [echo] @@ -7169,9 +7169,6 @@ public class AddressPersistenceImpl
     [echo]  			address.setExternalReferenceCode(address.getUuid());
     [echo]  		}
     [echo]  		else {
     [echo] -			Address ercAddress = fetchByERC_C(
     [echo] -				address.getExternalReferenceCode(), address.getCompanyId());
     [echo] -
     [echo]  			long userId = GetterUtil.getLong(PrincipalThreadLocal.getName());
     [echo]  
     [echo]  			if (userId > 0) {
     [echo] @@ -7197,6 +7194,9 @@ public class AddressPersistenceImpl
     [echo]  				}
     [echo]  			}
     [echo]  
     [echo] +			Address ercAddress = fetchByERC_C(
     [echo] +				address.getExternalReferenceCode(), address.getCompanyId());
     [echo] +
     [echo]  			if (isNew) {
     [echo]  				if (ercAddress != null) {
     [echo]  					throw new DuplicateAddressExternalReferenceCodeException(
     [echo] diff --git a/portal-impl/src/com/liferay/portal/service/persistence/impl/GroupPersistenceImpl.java b/portal-impl/src/com/liferay/portal/service/persistence/impl/GroupPersistenceImpl.java
     [echo] index 31717a123a0f..53cf518ac9cc 100644
     [echo] --- a/portal-impl/src/com/liferay/portal/service/persistence/impl/GroupPersistenceImpl.java
     [echo] +++ b/portal-impl/src/com/liferay/portal/service/persistence/impl/GroupPersistenceImpl.java
     [echo] @@ -14208,9 +14208,6 @@ public class GroupPersistenceImpl
     [echo]  			group.setExternalReferenceCode(group.getUuid());
     [echo]  		}
     [echo]  		else {
     [echo] -			Group ercGroup = fetchByERC_C(
     [echo] -				group.getExternalReferenceCode(), group.getCompanyId());
     [echo] -
     [echo]  			long userId = GetterUtil.getLong(PrincipalThreadLocal.getName());
     [echo]  
     [echo]  			if (userId > 0) {
     [echo] @@ -14236,6 +14233,9 @@ public class GroupPersistenceImpl
     [echo]  				}
     [echo]  			}
     [echo]  
     [echo] +			Group ercGroup = fetchByERC_C(
     [echo] +				group.getExternalReferenceCode(), group.getCompanyId());
     [echo] +
     [echo]  			if (isNew) {
     [echo]  				if (ercGroup != null) {
     [echo]  					throw new DuplicateGroupExternalReferenceCodeException(
     [echo] diff --git a/portal-impl/src/com/liferay/portal/service/persistence/impl/OrganizationPersistenceImpl.java b/portal-impl/src/com/liferay/portal/service/persistence/impl/OrganizationPersistenceImpl.java
     [echo] index 500f1622845d..a106ec758fbc 100644
     [echo] --- a/portal-impl/src/com/liferay/portal/service/persistence/impl/OrganizationPersistenceImpl.java
     [echo] +++ b/portal-impl/src/com/liferay/portal/service/persistence/impl/OrganizationPersistenceImpl.java
     [echo] @@ -9493,10 +9493,6 @@ public class OrganizationPersistenceImpl
     [echo]  			organization.setExternalReferenceCode(organization.getUuid());
     [echo]  		}
     [echo]  		else {
     [echo] -			Organization ercOrganization = fetchByERC_C(
     [echo] -				organization.getExternalReferenceCode(),
     [echo] -				organization.getCompanyId());
     [echo] -
     [echo]  			long userId = GetterUtil.getLong(PrincipalThreadLocal.getName());
     [echo]  
     [echo]  			if (userId > 0) {
     [echo] @@ -9523,6 +9519,10 @@ public class OrganizationPersistenceImpl
     [echo]  				}
     [echo]  			}
     [echo]  
     [echo] +			Organization ercOrganization = fetchByERC_C(
     [echo] +				organization.getExternalReferenceCode(),
     [echo] +				organization.getCompanyId());
     [echo] +
     [echo]  			if (isNew) {
     [echo]  				if (ercOrganization != null) {
     [echo]  					throw new DuplicateOrganizationExternalReferenceCodeException(
     [echo] diff --git a/portal-impl/src/com/liferay/portal/service/persistence/impl/UserGroupPersistenceImpl.java b/portal-impl/src/com/liferay/portal/service/persistence/impl/UserGroupPersistenceImpl.java
     [echo] index 9b5d11ef1cdb..cb54a71df24d 100644
     [echo] --- a/portal-impl/src/com/liferay/portal/service/persistence/impl/UserGroupPersistenceImpl.java
     [echo] +++ b/portal-impl/src/com/liferay/portal/service/persistence/impl/UserGroupPersistenceImpl.java
     [echo] @@ -6408,9 +6408,6 @@ public class UserGroupPersistenceImpl
     [echo]  			userGroup.setExternalReferenceCode(userGroup.getUuid());
     [echo]  		}
     [echo]  		else {
     [echo] -			UserGroup ercUserGroup = fetchByERC_C(
     [echo] -				userGroup.getExternalReferenceCode(), userGroup.getCompanyId());
     [echo] -
     [echo]  			long userId = GetterUtil.getLong(PrincipalThreadLocal.getName());
     [echo]  
     [echo]  			if (userId > 0) {
     [echo] @@ -6437,6 +6434,9 @@ public class UserGroupPersistenceImpl
     [echo]  				}
     [echo]  			}
     [echo]  
     [echo] +			UserGroup ercUserGroup = fetchByERC_C(
     [echo] +				userGroup.getExternalReferenceCode(), userGroup.getCompanyId());
     [echo] +
     [echo]  			if (isNew) {
     [echo]  				if (ercUserGroup != null) {
     [echo]  					throw new DuplicateUserGroupExternalReferenceCodeException(
     [echo] diff --git a/portal-impl/src/com/liferay/portal/service/persistence/impl/UserPersistenceImpl.java b/portal-impl/src/com/liferay/portal/service/persistence/impl/UserPersistenceImpl.java
     [echo] index ed50ff3eeea5..0ba46453d8d4 100644
     [echo] --- a/portal-impl/src/com/liferay/portal/service/persistence/impl/UserPersistenceImpl.java
     [echo] +++ b/portal-impl/src/com/liferay/portal/service/persistence/impl/UserPersistenceImpl.java
     [echo] @@ -8903,9 +8903,6 @@ public class UserPersistenceImpl
     [echo]  			user.setExternalReferenceCode(user.getUuid());
     [echo]  		}
     [echo]  		else {
     [echo] -			User ercUser = fetchByERC_C(
     [echo] -				user.getExternalReferenceCode(), user.getCompanyId());
     [echo] -
     [echo]  			long userId = GetterUtil.getLong(PrincipalThreadLocal.getName());
     [echo]  
     [echo]  			if (userId > 0) {
     [echo] @@ -8931,6 +8928,9 @@ public class UserPersistenceImpl
     [echo]  				}
     [echo]  			}
     [echo]  
     [echo] +			User ercUser = fetchByERC_C(
     [echo] +				user.getExternalReferenceCode(), user.getCompanyId());
     [echo] +
     [echo]  			if (isNew) {
     [echo]  				if (ercUser != null) {
     [echo]  					throw new DuplicateUserExternalReferenceCodeException(
     [echo] diff --git a/portal-impl/src/com/liferay/portlet/asset/service/persistence/impl/AssetCategoryPersistenceImpl.java b/portal-impl/src/com/liferay/portlet/asset/service/persistence/impl/AssetCategoryPersistenceImpl.java
     [echo] index 0e76e68f72e7..a4fbd25d07b4 100644
     [echo] --- a/portal-impl/src/com/liferay/portlet/asset/service/persistence/impl/AssetCategoryPersistenceImpl.java
     [echo] +++ b/portal-impl/src/com/liferay/portlet/asset/service/persistence/impl/AssetCategoryPersistenceImpl.java
     [echo] @@ -12473,10 +12473,6 @@ public class AssetCategoryPersistenceImpl
     [echo]  			assetCategory.setExternalReferenceCode(assetCategory.getUuid());
     [echo]  		}
     [echo]  		else {
     [echo] -			AssetCategory ercAssetCategory = fetchByERC_G(
     [echo] -				assetCategory.getExternalReferenceCode(),
     [echo] -				assetCategory.getGroupId());
     [echo] -
     [echo]  			long userId = GetterUtil.getLong(PrincipalThreadLocal.getName());
     [echo]  
     [echo]  			if (userId > 0) {
     [echo] @@ -12503,6 +12499,10 @@ public class AssetCategoryPersistenceImpl
     [echo]  				}
     [echo]  			}
     [echo]  
     [echo] +			AssetCategory ercAssetCategory = fetchByERC_G(
     [echo] +				assetCategory.getExternalReferenceCode(),
     [echo] +				assetCategory.getGroupId());
     [echo] +
     [echo]  			if (isNew) {
     [echo]  				if (ercAssetCategory != null) {
     [echo]  					throw new DuplicateAssetCategoryExternalReferenceCodeException(
     [echo] diff --git a/portal-impl/src/com/liferay/portlet/asset/service/persistence/impl/AssetVocabularyPersistenceImpl.java b/portal-impl/src/com/liferay/portlet/asset/service/persistence/impl/AssetVocabularyPersistenceImpl.java
     [echo] index b8764c4bfaa5..dce57a08bd77 100644
     [echo] --- a/portal-impl/src/com/liferay/portlet/asset/service/persistence/impl/AssetVocabularyPersistenceImpl.java
     [echo] +++ b/portal-impl/src/com/liferay/portlet/asset/service/persistence/impl/AssetVocabularyPersistenceImpl.java
     [echo] @@ -6825,10 +6825,6 @@ public class AssetVocabularyPersistenceImpl
     [echo]  			assetVocabulary.setExternalReferenceCode(assetVocabulary.getUuid());
     [echo]  		}
     [echo]  		else {
     [echo] -			AssetVocabulary ercAssetVocabulary = fetchByERC_G(
     [echo] -				assetVocabulary.getExternalReferenceCode(),
     [echo] -				assetVocabulary.getGroupId());
     [echo] -
     [echo]  			long userId = GetterUtil.getLong(PrincipalThreadLocal.getName());
     [echo]  
     [echo]  			if (userId > 0) {
     [echo] @@ -6855,6 +6851,10 @@ public class AssetVocabularyPersistenceImpl
     [echo]  				}
     [echo]  			}
     [echo]  
     [echo] +			AssetVocabulary ercAssetVocabulary = fetchByERC_G(
     [echo] +				assetVocabulary.getExternalReferenceCode(),
     [echo] +				assetVocabulary.getGroupId());
     [echo] +
     [echo]  			if (isNew) {
     [echo]  				if (ercAssetVocabulary != null) {
     [echo]  					throw new DuplicateAssetVocabularyExternalReferenceCodeException(
     [echo] diff --git a/portal-impl/src/com/liferay/portlet/documentlibrary/service/persistence/impl/DLFileEntryPersistenceImpl.java b/portal-impl/src/com/liferay/portlet/documentlibrary/service/persistence/impl/DLFileEntryPersistenceImpl.java
     [echo] index 73f83f15f3e1..919a870a2708 100644
     [echo] --- a/portal-impl/src/com/liferay/portlet/documentlibrary/service/persistence/impl/DLFileEntryPersistenceImpl.java
     [echo] +++ b/portal-impl/src/com/liferay/portlet/documentlibrary/service/persistence/impl/DLFileEntryPersistenceImpl.java
     [echo] @@ -15358,10 +15358,6 @@ public class DLFileEntryPersistenceImpl
     [echo]  			dlFileEntry.setExternalReferenceCode(dlFileEntry.getUuid());
     [echo]  		}
     [echo]  		else {
     [echo] -			DLFileEntry ercDLFileEntry = fetchByERC_G(
     [echo] -				dlFileEntry.getExternalReferenceCode(),
     [echo] -				dlFileEntry.getGroupId());
     [echo] -
     [echo]  			long userId = GetterUtil.getLong(PrincipalThreadLocal.getName());
     [echo]  
     [echo]  			if (userId > 0) {
     [echo] @@ -15388,6 +15384,10 @@ public class DLFileEntryPersistenceImpl
     [echo]  				}
     [echo]  			}
     [echo]  
     [echo] +			DLFileEntry ercDLFileEntry = fetchByERC_G(
     [echo] +				dlFileEntry.getExternalReferenceCode(),
     [echo] +				dlFileEntry.getGroupId());
     [echo] +
     [echo]  			if (isNew) {
     [echo]  				if (ercDLFileEntry != null) {
     [echo]  					throw new DuplicateDLFileEntryExternalReferenceCodeException(
     [echo] diff --git a/portal-impl/src/com/liferay/portlet/documentlibrary/service/persistence/impl/DLFolderPersistenceImpl.java b/portal-impl/src/com/liferay/portlet/documentlibrary/service/persistence/impl/DLFolderPersistenceImpl.java
     [echo] index 5a658eefa471..3d2f04c16744 100644
     [echo] --- a/portal-impl/src/com/liferay/portlet/documentlibrary/service/persistence/impl/DLFolderPersistenceImpl.java
     [echo] +++ b/portal-impl/src/com/liferay/portlet/documentlibrary/service/persistence/impl/DLFolderPersistenceImpl.java
     [echo] @@ -14731,9 +14731,6 @@ public class DLFolderPersistenceImpl
     [echo]  			dlFolder.setExternalReferenceCode(dlFolder.getUuid());
     [echo]  		}
     [echo]  		else {
     [echo] -			DLFolder ercDLFolder = fetchByERC_G(
     [echo] -				dlFolder.getExternalReferenceCode(), dlFolder.getGroupId());
     [echo] -
     [echo]  			long userId = GetterUtil.getLong(PrincipalThreadLocal.getName());
     [echo]  
     [echo]  			if (userId > 0) {
     [echo] @@ -14760,6 +14757,9 @@ public class DLFolderPersistenceImpl
     [echo]  				}
     [echo]  			}
     [echo]  
     [echo] +			DLFolder ercDLFolder = fetchByERC_G(
     [echo] +				dlFolder.getExternalReferenceCode(), dlFolder.getGroupId());
     [echo] +
     [echo]  			if (isNew) {
     [echo]  				if (ercDLFolder != null) {
     [echo]  					throw new DuplicateDLFolderExternalReferenceCodeException(
[stopwatch] [run.batch.test.action: 26:57.619 sec]
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-40/test-portal-acceptance-pullrequest(master)/7171/service-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by leilanyaragao** [comment]
ci:test:sf

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by leilanyaragao** [comment]
ci:test:sf

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by leilanyaragao** [comment]
ci:test:service-builder

**Comment by JanisZhang** [comment]
Remove the QA failed label as the author reruns tests.

**Comment by zhangyan0701** [comment]
Issues found:
**1. Portal failed to start on DB2 with External Database.**
Failed test: [LocalFile.ServiceBuilder#ExternalDataSourceSmoke](https://testray.liferay.com/home/-/testray/case_results/2455992848)

 Reproduced steps:
- Start DB2 docker container by running command in portal source root folder:
`ant -f build-test-local.xml start-docker-database-db2`.
Reference doc: https://liferay.atlassian.net/wiki/spaces/QA/pages/2102462200/Databases.
- In portal-ext.properties file, change all `jdbc.default` to `jdbc.test`.
- Start portal.

Results: Assert errors in portal console:
```
2023-11-10 11:26:07.507 ERROR [main][SqlExceptionHelper:142] unexpected token: WITH in statement [select counterimp0_.name as name1_0_0_, counterimp0_.currentId as currenti2_0_0_ from Counter counterimp0_ where counterimp0_.name=? for read only with rs use and keep exclusive locks]
2023-11-10 11:26:07.617 ERROR [SystemExecutorServiceUtil-7][SqlExceptionHelper:142] unexpected token: WITH in statement [select counterimp0_.name as name1_0_0_, counterimp0_.currentId as currenti2_0_0_ from Counter counterimp0_ where counterimp0_.name=? for read only with rs use and keep exclusive locks]
2023-11-10 11:26:07.621 ERROR [SystemExecutorServiceUtil-7][PortletConfigurationExtender:95] Unable to read resource actions config in resource.actions.configs
java.lang.RuntimeException: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.exception.SQLGrammarException: could not prepare statement
```
Full log: https://testray.liferay.com/reports/production/logs/2023-11/test-1-30/test-portal-acceptance-pullrequest(master)/8332/functional-tomcat90-db2111-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**2. Service builder changes detected.**
```
     [echo] diff --git a/portal-impl/src/com/liferay/portal/service/persistence/impl/AddressPersistenceImpl.java b/portal-impl/src/com/liferay/portal/service/persistence/impl/AddressPersistenceImpl.java
     [echo] index 86299e486c4e..48105544518e 100644
     [echo] --- a/portal-impl/src/com/liferay/portal/service/persistence/impl/AddressPersistenceImpl.java
     [echo] +++ b/portal-impl/src/com/liferay/portal/service/persistence/impl/AddressPersistenceImpl.java
     [echo] @@ -18,11 +18,16 @@ import com.liferay.portal.kernel.dao.orm.QueryUtil;
     [echo]  import com.liferay.portal.kernel.dao.orm.Session;
     [echo]  import com.liferay.portal.kernel.exception.DuplicateAddressExternalReferenceCodeException;
     [echo]  import com.liferay.portal.kernel.exception.NoSuchAddressException;
     [echo] +import com.liferay.portal.kernel.exception.SystemException;
     [echo]  import com.liferay.portal.kernel.log.Log;
     [echo]  import com.liferay.portal.kernel.log.LogFactoryUtil;
     [echo]  import com.liferay.portal.kernel.model.Address;
     [echo]  import com.liferay.portal.kernel.model.AddressTable;
     [echo] +import com.liferay.portal.kernel.sanitizer.Sanitizer;
     [echo] +import com.liferay.portal.kernel.sanitizer.SanitizerException;
     [echo] +import com.liferay.portal.kernel.sanitizer.SanitizerUtil;
     [echo]  import com.liferay.portal.kernel.security.auth.CompanyThreadLocal;
     [echo] +import com.liferay.portal.kernel.security.auth.PrincipalThreadLocal;
     [echo]  import com.liferay.portal.kernel.service.ServiceContext;
     [echo]  import com.liferay.portal.kernel.service.ServiceContextThreadLocal;
     [echo]  import com.liferay.portal.kernel.service.persistence.AddressPersistence;
     [echo] @@ -30,6 +35,7 @@ import com.liferay.portal.kernel.service.persistence.AddressUtil;
     [echo]  import com.liferay.portal.kernel.service.persistence.change.tracking.helper.CTPersistenceHelperUtil;
     [echo]  import com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl;
     [echo]  import com.liferay.portal.kernel.util.ArrayUtil;
     [echo] +import com.liferay.portal.kernel.util.ContentTypes;
     [echo]  import com.liferay.portal.kernel.util.GetterUtil;
     [echo]  import com.liferay.portal.kernel.util.OrderByComparator;
     [echo]  import com.liferay.portal.kernel.util.PropsKeys;
     [echo] @@ -7163,6 +7169,31 @@ public class AddressPersistenceImpl
     [echo]  			address.setExternalReferenceCode(address.getUuid());
     [echo]  		}
     [echo]  		else {
     [echo] +			long userId = GetterUtil.getLong(PrincipalThreadLocal.getName());
     [echo] +
     [echo] +			if (userId > 0) {
     [echo] +				long companyId = address.getCompanyId();
     [echo] +
     [echo] +				long groupId = 0;
     [echo] +
     [echo] +				long classPK = 0;
     [echo] +
     [echo] +				if (!isNew) {
     [echo] +					classPK = address.getPrimaryKey();
     [echo] +				}
     [echo] +
     [echo] +				try {
     [echo] +					address.setExternalReferenceCode(
     [echo] +						SanitizerUtil.sanitize(
     [echo] +							companyId, groupId, userId, Address.class.getName(),
     [echo] +							classPK, ContentTypes.TEXT_HTML, Sanitizer.MODE_ALL,
     [echo] +							address.getExternalReferenceCode(), null));
     [echo] +				}
     [echo] +				catch (SanitizerException sanitizerException) {
     [echo] +					throw new SystemException(sanitizerException);
     [echo] +				}
     [echo] +			}
     [echo] +
     [echo]  			Address ercAddress = fetchByERC_C(
     [echo]  				address.getExternalReferenceCode(), address.getCompanyId());
     [echo] 
... ...
```
Full console log: https://testray.liferay.com/reports/production/logs/2023-11/test-1-27/test-portal-acceptance-pullrequest(master)/10704/service-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Comment by leilanyaragao** [comment]
ci:test:sf

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by leilanyaragao** [comment]
@zhangyan0701, @catarineaguiar, @JanisZhang  I don't have permission to edit labels, could any of you change `QA Failed` to `Ready for QA`, please?

**Comment by zhangyan0701** [comment]
No regressions found. Manual testing passed following the steps in bug ticket.

**Comment by dantewang** [comment]
@yuhai Please review it. I only took a quick look, and it seems this change changed the version protection logic. Please be careful about it, thanks!

**Comment by yuhai** [comment]
Hi @leilanyaragao, I did some SF and send it to you, please see 

The current pr changed the version protection logic. Before the fix, else block matches with the condition `<#if serviceBuilder.isVersionGTE_7_3_0() && entity.hasExternalReferenceCode()>`. . Please see `com.liferay.portal.upgrade.v7_1_x.UpgradeExternalReferenceCode` on master, the four entities had the column, but the codes version protection only check >= 7.3.0. Please see [AssetVocabularyPersistenceImpl ](https://github.com/liferay/liferay-portal-ee/blob/7.2.x/portal-impl/src/com/liferay/portlet/asset/service/persistence/impl/AssetVocabularyPersistenceImpl.java#L5267-L5269) on 7.2.X. It only included `if condition`. This looks wired and the previous version protection looks wrong. It was added by LPS-163008. I think we need to do the fix on 7.2.x. If the column externalReferenceCode existed, I think we should check it on the related liferay versions. Please confirm it if we can delete the version protection condition `<#if serviceBuilder.isVersionGTE_7_3_0() && entity.hasExternalReferenceCode()>`. The clean up should be placed the first commit if possible. And then add your fix in the else block.

Please merge my SF commits and resend it after your further investigation.

I am going to close the pr.

Thanks,
Hai

**Comment by leilanyaragao** [comment]
Hey @yuhai, I have a security bug with high priority, and I had made the changes only on the `object` side, but Brian [requests](https://github.com/brianchandotcom/liferay-portal/pull/142305#issuecomment-1766349029) that the change be made the entire portal.  
I talked with my team about your suggestion and this decision and changes seem ends up escaping my scope.
I would like to know if we can send my changes and open a new ticket related to the technical debt that you reported and forward it to the appropriate time to carry out this verification.
cc: @marcelabc

**Comment by yuhai** [comment]
Hi @leilanyaragao, It's a little unclear if we forward the current fix. I will take care this and then let you know.

**Pull request closed without merging**
