### PR TITLE
[Remove Stream/Optional usage] LPS-174911 Remove usages of Stream for module: portal-settings-authentication-ldap-web 

### PR DESCRIPTION
**Pull request by dantewang**
#3367

### CODE REVIEW

**Comment by dantewang** [comment]
[ci:test:security - failure](https://github.com/liferay-core-infra/liferay-portal/labels/ci%3Atest%3Asecurity%20%20-%20failure)

**Comment by dantewang** [comment]
ci:test:security

**Comment by catarineaguiar** [comment]
ci:test:oidc

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130469

**Pull request closed without merging**
