### PR TITLE
[Rename Classes] LPS-167345 Rename classes in modules layout-display-page-api、layout-display-page-impl、asset-display-page-api、asset-taglib、layout-content-page-editor-web

### PR DESCRIPTION
**Pull request by W2jx**
Detial: https://github.com/liferay-core-infra/liferay-portal/pull/2374

### CODE REVIEW

**Comment by W2jx** [comment]
Force-Push is just to resolve the conflict about file modules/apps/layout/layout-display-page-api/bnd.bnd

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:reevaluate:1317401_5847

**Comment by catarineaguiar** [comment]
@W2jx no regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126173

**Pull request closed without merging**
