### PR TITLE
[Spring Beans] LPS-201156 Merge LayoutPrototypePermissionImpl into LayoutPrototypePermissionUtil and move it into portal-impl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(11/13 9:20)

**Comment by W2jx** [comment]
no conflicts(11/14 15:49)

**Comment by W2jx** [comment]
no conflicts(11/15 10:19)

**Comment by W2jx** [comment]
no conflicts(11/17 8:18)

**Comment by W2jx** [comment]
no conflicts(11/20 13:57)

**Comment by W2jx** [comment]
no conflicts(11/21 15:06)

**Comment by W2jx** [comment]
no conflicts(11/22 15:05)

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/144337

cc @tinatian

**Pull request closed without merging**
