### PR TITLE
LPD-20946 ResourceAction 5-14

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:test:object

**Comment by tinatian** [comment]
ci:report:2568437321

**Comment by tinatian** [comment]
ci:report:2568434659

**Comment by tinatian** [comment]
ci:report:2568434562

**Comment by tinatian** [comment]
ci:report:2568437321

**Comment by tinatian** [comment]
ci:report:2568434659

**Comment by tinatian** [comment]
ci:report:2568434562

**Comment by tinatian** [comment]
ci:report:2568437321

**Comment by dantewang** [comment]
ci:report:2568437321

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
ci:test:object

**Comment by tinatian** [comment]
ci:report:2569002503

**Comment by tinatian** [comment]
ci:report:2569004100

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:object

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:report:2569269495

**Comment by dantewang** [comment]
ci:report:2569269474

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 2569269495.
> 
> Job Link: [generate-testray-csv](https://test-1-34.liferay.com/job/generate-testray-csv/100/)
> 
> Testray CSV Link: [testray-results-2569269495.csv](https://test-1-34.liferay.com/userContent/jobs/generate-testray-csv/builds/100/testray-results-2569269495.csv)

upgrade: 3 tests marked unique. Same test failing on different DBs at the client extension's `ClassNamesUpgradeProcess`:

```
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "ix_f2237d8e"
  Detail: Key (companyid, scope, name, primkey, roleid, ctcollectionid)=(20099, 4, com.liferay.client.extension.model.ClientExtensionEntry, com.liferay.client.extension.model.ClientExtensionEntry, 20107, 0) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676) ~[postgresql.jar:42.4.4]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366) ~[postgresql.jar:42.4.4]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356) ~[postgresql.jar:42.4.4]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496) ~[postgresql.jar:42.4.4]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413) ~[postgresql.jar:42.4.4]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333) ~[postgresql.jar:42.4.4]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319) ~[postgresql.jar:42.4.4]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295) ~[postgresql.jar:42.4.4]
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:268) ~[postgresql.jar:42.4.4]
	at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:119) ~[hikaricp.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java) ~[hikaricp.jar:?]
	at com.liferay.portal.dao.db.BaseDB.runSQL(BaseDB.java:558) ~[portal-impl.jar:?]
	at com.liferay.portal.dao.db.BaseDB.runSQL(BaseDB.java:524) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.dao.db.BaseDBProcess.runSQL(BaseDBProcess.java:103) ~[portal-kernel.jar:?]
	at com.liferay.portal.upgrade.v7_0_0.UpgradeKernelPackage._executeUpdate(UpgradeKernelPackage.java:208) ~[portal-impl.jar:?]
	at com.liferay.portal.upgrade.v7_0_0.UpgradeKernelPackage.upgradeTable(UpgradeKernelPackage.java:169) ~[portal-impl.jar:?]
	at com.liferay.portal.upgrade.v7_0_0.UpgradeKernelPackage.upgradeTable(UpgradeKernelPackage.java:154) ~[portal-impl.jar:?]
	at com.liferay.client.extension.internal.upgrade.v3_0_0.ClassNamesUpgradeProcess.doUpgrade(ClassNamesUpgradeProcess.java:22) ~[?:?]
	at com.liferay.portal.kernel.upgrade.UpgradeProcess.lambda$upgrade$0(UpgradeProcess.java:122) ~[portal-kernel.jar:?]
	at com.liferay.portal.db.partition.util.DBPartitionUtil.forEachCompanyId(DBPartitionUtil.java:177) ~[portal-impl.jar:?]
	at com.liferay.portal.dao.db.BaseDB.process(BaseDB.java:469) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.dao.db.BaseDBProcess.process(BaseDBProcess.java:384) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:107) ~[portal-kernel.jar:?]
	... 158 more
```

Massive numbers of tests marked as "Did not run", but some of them are also failing at the client extension upgrade.

**Comment by dantewang** [comment]
@tinatian It seems a lot of errors are with this PR. The ones in the latest object run does not seem to be much related, but the upgrade ones are relevant for sure.

**Pull request closed without merging**
