### PR TITLE
[Remove Stream/Optional usage] LPS-175914 module:headless-discovery, dynamic-data-mapping-uad, dynamic-data-mapping-validator, dynamic-data-mapping-web

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-175914

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by JanisZhang** [comment]
@catarineaguiar thank you :)

**Comment by JanisZhang** [comment]
add 1 simplify commit.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131061

**Pull request closed without merging**
