### PR TITLE
[System Properties] LPS-153430 Move some properties that moduleFramework needs during init

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have moved some properties that moduleFramework needs during init.

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
@W2jx regressions found:

```
[exec] com.liferay.portal.lpkg.deployer.LPKGVersionChangeLogAssertorTest > testUpgradeLog FAILED
     [exec]     java.nio.file.NoSuchFileException: /opt/dev/projects/github/liferay-portal/modules/apps/static/portal-lpkg-deployer/portal-lpkg-deployer-test/liferay/osgi/marketplace
     [exec]         at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
     [exec]         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
     [exec]         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
     [exec]         at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427)
     [exec]         at java.nio.file.Files.newDirectoryStream(Files.java:457)
     [exec]         at com.liferay.portal.lpkg.deployer.LPKGVersionChangeLogAssertorTest.testUpgradeLog(LPKGVersionChangeLogAssertorTest.java:56)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-33/test-portal-acceptance-pullrequest(master)/2256/lpkg-startup-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
[exec] com.liferay.portal.lpkg.deployer.persistence.LPKGPersistenceTest > testLPKGPersistenceDeploy FAILED
     [exec]     java.nio.file.NoSuchFileException: /opt/dev/projects/github/liferay-portal/modules/apps/static/portal-lpkg-deployer/portal-lpkg-deployer-test/liferay/osgi/marketplace/Liferay Persistence Test.lpkg
     [exec]         at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
     [exec]         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
     [exec]         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
     [exec]         at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
     [exec]         at java.nio.file.Files.newByteChannel(Files.java:361)
     [exec]         at java.nio.file.Files.createFile(Files.java:632)
     [exec]         at com.liferay.portal.lpkg.deployer.persistence.LPKGPersistenceTest.testLPKGPersistenceDeploy(LPKGPersistenceTest.java:50)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-33/test-portal-acceptance-pullrequest(master)/2256/lpkg-persistence-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
[exec] com.liferay.portal.lpkg.deployer.controller.test.LPKGControllerVerifyTest > testLPKGController FAILED
     [exec]     java.lang.AssertionError: No JAR bundle found
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
     [exec]     	at org.junit.Assert.assertNotNull(Assert.java:713)
     [exec]     	at com.liferay.portal.lpkg.deployer.controller.test.LPKGControllerVerifyTest.testLPKGController(LPKGControllerVerifyTest.java:77)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-33/test-portal-acceptance-pullrequest(master)/2256/lpkg-controller-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
 [exec] com.liferay.portal.lpkg.deployer.override.test.LPKGOverrideVerifySecondStartupTest > testOverriddenLPKGs FAILED
     [exec]     java.lang.AssertionError
     [exec]     	at org.junit.Assert.fail(Assert.java:87)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:53)
     [exec]     	at com.liferay.portal.lpkg.deployer.override.test.LPKGOverrideVerifyTest.testOverriddenLPKGs(LPKGOverrideVerifyTest.java:58)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-33/test-portal-acceptance-pullrequest(master)/2256/lpkg-override-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
@W2jx Closing, please fix the regressions and resend, thanks!

**Pull request closed without merging**
