### PR TITLE
[Bug fix] LPS-142277 Correct portal web dir

### PR DESCRIPTION
**Pull request by dantewang**
Sub bug of https://issues.liferay.com/browse/LPS-142276

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:environments

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@dantewang Please add test to cover this change.

Thanks.
Tina

**Comment by dantewang** [comment]
@tinatian On it. I also need to look into the CI failures.

**Comment by tinatian** [comment]
@dantewang Close for now and please resend

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
