### PR TITLE
LPS-142278 deprecate portal lib dir

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian Passed tests in https://github.com/dantewang/liferay-portal/pull/2121#issuecomment-978878338

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me verify the test results.

Thanks.
Tina

**Comment by tinatian** [comment]
@shuyangzhou This is good to go.

Tina

**Comment by shuyangzhou** [comment]
This needs to wait after https://github.com/shuyangzhou/liferay-portal/pull/10476 . I am removing stuff that is touched here and that pull is harder to rebase.

**Comment by shuyangzhou** [comment]
@dantewang my change is merged, please rebase this and resend.

**Comment by shuyangzhou** [comment]
ci:close

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/59

**Pull request closed without merging**
