### PR TITLE
LPS-145586 Avoid using SocialConfigurationUtil, UsersAdminUtil directly in modules

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina, Shuyang

Main Task: [LPS-143403](https://issues.liferay.com/browse/LPS-143403)
Sub Task: [LPS-145586](https://issues.liferay.com/browse/LPS-145586)

Thank you!

### CODE REVIEW

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test result.

Tina.

**Comment by tinatian** [comment]
@julschong Code looks good to me, wait for QA to scan test result.

Tina.

**Comment by catarineaguiar** [comment]
@julschong @tinatian no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
