### PR TITLE
LPS-203326 - As an instance admin, I would like to see which version of Liferay I am using

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
No regressions found. Tested by going to instance settings
Screenshot from 2023-12-12 12-17-47

**Comment by david-truong** [comment]
ci:reevaluate:1397401_8714

**Comment by david-truong** [comment]
ci:forward:force

**Pull request closed without merging**
