### PR TITLE
[Components with more than 1 service] LPS-186836 Refactor components from multiple modules

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://issues.liferay.com/browse/LPS-186836

Previous pull: https://github.com/liferay-core-infra/liferay-portal/pull/4728

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud

**Comment by MrJohn1911** [comment]
ci:test:lima

**Comment by MrJohn1911** [comment]
ci:test:data-engine

**Comment by MrJohn1911** [comment]
ci:test:echo

**Comment by MrJohn1911** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
ci:test:analytics-cloud-acceptance

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
ci:test:analytics-cloud

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by rafaprax — APPROVED** [review]

**Comment by dantewang** [comment]
@MrJohn1911 @rafaprax Please see https://github.com/MrJohn1911/liferay-portal/pull/26

**Pull request closed without merging**
