### PR TITLE
[Spring Beans] LPS-199287 Separate encode/decodeSafeFileName methods and move FileImpl to kernel

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
ci:test:dl-store

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:lima

**Comment by julschong** [comment]
ci:test:dl-store

**Comment by Kvale1733** [comment]
ci:close

**Comment by julschong** [comment]
applied release repo url and fixed FileImpl reflection usage

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:lima

**Comment by julschong** [comment]
ci:test:dl-store

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Compile errors:
```
    [javac] Compiling 2184 source files to /opt/dev/projects/github/liferay-portal/portal-impl/classes
 [parallel] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/tools/ToolDependencies.java:96: error: cannot find symbol
 [parallel]     FriendlyURLNormalizerUtil friendlyURLNormalizerUtil =
 [parallel]     ^
 [parallel]   symbol:   class FriendlyURLNormalizerUtil
 [parallel]   location: class ToolDependencies
 [parallel] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/tools/ToolDependencies.java:97: error: cannot find symbol
 [parallel]       new FriendlyURLNormalizerUtil();
 [parallel]           ^
 [parallel]   symbol:   class FriendlyURLNormalizerUtil
 [parallel]   location: class ToolDependencies
 [parallel] Note: Some input files use or override a deprecated API.
 [parallel] Note: Recompile with -Xlint:deprecation for details.
 [parallel] Note: Some input files use unchecked or unsafe operations.
 [parallel] Note: Recompile with -Xlint:unchecked for details.
 [parallel] 2 errors
```
Full Jenkins console:
https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/4565/consoleFull

**Comment by julschong** [comment]
fix import issue

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
@julschong Just found a semver issue

```
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.util                            MAJOR      59.0.0     59.0.0     60.0.0     VERSION INCREASE REQUIRED
     [exec] 	-   class      com.liferay.portal.util.FileImpl
     [exec] 		-   implements com.liferay.portal.kernel.util.File
     [exec] 		-   method     <init>()
     [exec] 			-   return     void
     [exec] 		-   method     appendParentheticalSuffix(java.lang.String,java.lang.String)
     [exec] 			-   return     java.lang.String
     [exec] 		-   method     appendSuffix(java.lang.String,java.lang.String)
     [exec] 			-   return     java.lang.String
     [exec] 		-   method     clone()
     [exec] 			-   access     protected
     [exec] 			-   return     java.lang.Object
     [exec] 		-   method     copyDirectory(java.io.File,java.io.File)
     [exec] 			-   return     void
     [exec] 		-   method     copyDirectory(java.lang.String,java.lang.String)
     [exec] 			-   return     void
     [exec] 		-   method     copyFile(java.io.File,java.io.File)
     [exec] 			-   return     void
     [exec] 		-   method     copyFile(java.lang.String,java.lang.String)
     [exec] 			-   return     void
     [exec] 		-   method     createTempFile()
     [exec] 			-   return     java.io.File
     [exec] 		-   method     createTempFile(byte[])
```
[Log](https://testray.liferay.com/reports/production/logs/2023-11/test-1-40/test-portal-acceptance-pullrequest(master)/7659/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong No regressions.

**Comment by julschong** [comment]
rebased to resolve conflict in semver

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
fixed breaking change message

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:report:2488512439

**Comment by julschong** [comment]
no unique failure

**Pull request closed without merging**
