### PR TITLE
[Components with more than 1 service] LPS-198978 Refactor KeyStoreCredentialResolver component

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-198978

Previous pull: https://github.com/liferay-core-infra/liferay-portal/pull/5760

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:saml

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:saml

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142568

**Pull request closed without merging**
