### PR TITLE
[Components with more than 1 service] LPS-177219 Refactor DTOConverter components with more than 1 service type from Commerce modules

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
@rafaprax could you review this? thanks!

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by rafaprax** [comment]
Hey @MrJohn1911, Let's try a different approach that aims to reduce the number of repetitive commits by grouping them by module.

see https://github.com/liferay-core-infra/liferay-portal/pull/3865

Thx

**Pull request closed without merging**
