### PR TITLE
LPS-199825 Merge ModelAdapterBuilderLocator interface and impl into Util and move to portal-impl

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong tests doesn't run due to:

```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/subscription/subscription-service/src/main/java/com/liferay/subscription/internal/service/ModularSubscriptionLocalServiceWrapper.java:33: error: no suitable method found for adapt(java.lang.Class<com.liferay.portal.kernel.model.Subscription>,com.liferay.subscription.model.Subscription)
     [exec] 		return ModelAdapterUtil.adapt(
     [exec] 		                       ^
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(java.util.List<T>,java.lang.Class<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(java.util.List<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (argument mismatch; java.lang.Class<com.liferay.portal.kernel.model.Subscription> cannot be converted to java.util.List<T>))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(T,java.lang.Class<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(T,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (argument mismatch; com.liferay.subscription.model.Subscription cannot be converted to java.lang.Class<V>))
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/subscription/subscription-service/src/main/java/com/liferay/subscription/internal/service/ModularSubscriptionLocalServiceWrapper.java:45: error: no suitable method found for adapt(java.lang.Class<com.liferay.portal.kernel.model.Subscription>,com.liferay.subscription.model.Subscription)
     [exec] 		return ModelAdapterUtil.adapt(
     [exec] 		                       ^
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(java.util.List<T>,java.lang.Class<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(java.util.List<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (argument mismatch; java.lang.Class<com.liferay.portal.kernel.model.Subscription> cannot be converted to java.util.List<T>))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(T,java.lang.Class<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(T,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (argument mismatch; com.liferay.subscription.model.Subscription cannot be converted to java.lang.Class<V>))
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/subscription/subscription-service/src/main/java/com/liferay/subscription/internal/service/ModularSubscriptionLocalServiceWrapper.java:55: error: no suitable method found for adapt(java.lang.Class<com.liferay.portal.kernel.model.Subscription>,com.liferay.subscription.model.Subscription)
     [exec] 		return ModelAdapterUtil.adapt(
     [exec] 		                       ^
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(java.util.List<T>,java.lang.Class<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(java.util.List<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (argument mismatch; java.lang.Class<com.liferay.portal.kernel.model.Subscription> cannot be converted to java.util.List<T>))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(T,java.lang.Class<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(T,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (argument mismatch; com.liferay.subscription.model.Subscription cannot be converted to java.lang.Class<V>))
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/subscription/subscription-service/src/main/java/com/liferay/subscription/internal/service/ModularSubscriptionLocalServiceWrapper.java:72: error: no suitable method found for adapt(java.lang.Class<com.liferay.portal.kernel.model.Subscription>,com.liferay.subscription.model.Subscription)
     [exec] 		return ModelAdapterUtil.adapt(
     [exec] 		                       ^
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(java.util.List<T>,java.lang.Class<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(java.util.List<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (argument mismatch; java.lang.Class<com.liferay.portal.kernel.model.Subscription> cannot be converted to java.util.List<T>))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(T,java.lang.Class<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(T,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (argument mismatch; com.liferay.subscription.model.Subscription cannot be converted to java.lang.Class<V>))
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/subscription/subscription-service/src/main/java/com/liferay/subscription/internal/service/ModularSubscriptionLocalServiceWrapper.java:103: error: no suitable method found for adapt(java.lang.Class<com.liferay.portal.kernel.model.Subscription>,com.liferay.subscription.model.Subscription)
     [exec] 		return ModelAdapterUtil.adapt(
     [exec] 		                       ^
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(java.util.List<T>,java.lang.Class<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(java.util.List<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (argument mismatch; java.lang.Class<com.liferay.portal.kernel.model.Subscription> cannot be converted to java.util.List<T>))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(T,java.lang.Class<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(T,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (argument mismatch; com.liferay.subscription.model.Subscription cannot be converted to java.lang.Class<V>))
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/subscription/subscription-service/src/main/java/com/liferay/subscription/internal/service/ModularSubscriptionLocalServiceWrapper.java:119: error: no suitable method found for adapt(java.lang.Class<com.liferay.portal.kernel.model.Subscription>,com.liferay.subscription.model.Subscription)
     [exec] 		return ModelAdapterUtil.adapt(
     [exec] 		                       ^
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(java.util.List<T>,java.lang.Class<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(java.util.List<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (argument mismatch; java.lang.Class<com.liferay.portal.kernel.model.Subscription> cannot be converted to java.util.List<T>))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(T,java.lang.Class<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(T,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (argument mismatch; com.liferay.subscription.model.Subscription cannot be converted to java.lang.Class<V>))
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/subscription/subscription-service/src/main/java/com/liferay/subscription/internal/service/ModularSubscriptionLocalServiceWrapper.java:129: error: no suitable method found for adapt(java.lang.Class<com.liferay.portal.kernel.model.Subscription>,java.util.List<com.liferay.subscription.model.Subscription>)
     [exec] 		return ModelAdapterUtil.adapt(
     [exec] 		                       ^
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(java.util.List<T>,java.lang.Class<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(java.util.List<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (argument mismatch; java.lang.Class<com.liferay.portal.kernel.model.Subscription> cannot be converted to java.util.List<T>))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(T,java.lang.Class<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(T,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (argument mismatch; java.util.List<com.liferay.subscription.model.Subscription> cannot be converted to java.lang.Class<V>))
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/subscription/subscription-service/src/main/java/com/liferay/subscription/internal/service/ModularSubscriptionLocalServiceWrapper.java:139: error: no suitable method found for adapt(java.lang.Class<com.liferay.portal.kernel.model.Subscription>,java.util.List<com.liferay.subscription.model.Subscription>)
     [exec] 		return ModelAdapterUtil.adapt(
     [exec] 		                       ^
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(java.util.List<T>,java.lang.Class<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(java.util.List<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (argument mismatch; java.lang.Class<com.liferay.portal.kernel.model.Subscription> cannot be converted to java.util.List<T>))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(T,java.lang.Class<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(T,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (argument mismatch; java.util.List<com.liferay.subscription.model.Subscription> cannot be converted to java.lang.Class<V>))
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/subscription/subscription-service/src/main/java/com/liferay/subscription/internal/service/ModularSubscriptionLocalServiceWrapper.java:154: error: no suitable method found for adapt(java.lang.Class<com.liferay.portal.kernel.model.Subscription>,com.liferay.portal.kernel.util.OrderByComparator<com.liferay.portal.kernel.model.Subscription>)
     [exec] 				ModelAdapterUtil.adapt(Subscription.class, orderByComparator)));
     [exec] 				                ^
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(java.util.List<T>,java.lang.Class<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(java.util.List<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (argument mismatch; java.lang.Class<com.liferay.portal.kernel.model.Subscription> cannot be converted to java.util.List<T>))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(T,java.lang.Class<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(T,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (argument mismatch; com.liferay.portal.kernel.util.OrderByComparator<com.liferay.portal.kernel.model.Subscription> cannot be converted to java.lang.Class<V>))
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/subscription/subscription-service/src/main/java/com/liferay/subscription/internal/service/ModularSubscriptionLocalServiceWrapper.java:161: error: no suitable method found for adapt(java.lang.Class<com.liferay.portal.kernel.model.Subscription>,java.util.List<com.liferay.subscription.model.Subscription>)
     [exec] 		return ModelAdapterUtil.adapt(
     [exec] 		                       ^
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(java.util.List<T>,java.lang.Class<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(java.util.List<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (argument mismatch; java.lang.Class<com.liferay.portal.kernel.model.Subscription> cannot be converted to java.util.List<T>))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(T,java.lang.Class<T>,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (actual and formal argument lists differ in length))
     [exec]     method com.liferay.portal.model.adapter.ModelAdapterUtil.<T,V>adapt(T,java.lang.Class<V>) is not applicable
     [exec]       (cannot infer type-variable(s) T,V
     [exec]         (argument mismatch; java.util.List<com.liferay.subscription.model.Subscription> cannot be converted to java.lang.Class<V>))
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 10 errors
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-30/test-portal-acceptance-pullrequest(master)/8151/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by julschong** [comment]
updated breaking change commit format: https://github.com/liferay-core-infra/liferay-portal/pull/5883/commits/7097baa9c71467819ea07e19ecc4de6e2f228cda https://github.com/liferay-core-infra/liferay-portal/pull/5883/commits/7aa61efbe5646df18e183a0894f1c7ee998b36b7

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143216

**Pull request closed without merging**
