### PR TITLE
LPS-143632 Avoid using LanguageUtil directly in modules part 1

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina, @tinatian

since JSONFactoryUtil has some error that needs to be fix, I'll start turning in LangaugeUtil now.
This Util has 1200 some files. I will split into couple pulls of 6 commits each pull with around 50 files per commits

These pulls should be able to be in parallel with each other

Main Task: [LPS-143403](https://issues.liferay.com/browse/LPS-143403)
Sub Task: [LPS-143632](https://issues.liferay.com/browse/LPS-143632)

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar
Hi Catarine, 
Could you please help me scan this test report?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong possible semver error:

```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/notification/notification-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.notification.service                   CHANGED    1.0.0      1.0.0      1.0.1      VERSION INCREASE REQUIRED
     [exec]     	~   interface  com.liferay.notification.service.NotificationTemplateLocalService
     [exec]     		~   method     addNotificationTemplate(long,java.lang.String,java.util.Map,java.lang.String,java.lang.String,boolean,java.lang.String,java.util.Map,java.lang.String,java.util.Map,java.lang.String)
     [exec]     			+   annotated  com.liferay.portal.kernel.search.Indexable
     [exec]     				+   property   type='REINDEX'
     [exec]     		~   method     updateNotificationTemplate(long,java.lang.String,java.util.Map,java.lang.String,java.lang.String,boolean,java.lang.String,java.util.Map,java.lang.String,java.util.Map,java.lang.String)
     [exec]     			+   annotated  com.liferay.portal.kernel.search.Indexable
     [exec]     				+   property   type='REINDEX'
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-05/test-1-39/test-portal-acceptance-pullrequest(master)/40/modules-semantic-versioning-jdk8/0/4/jenkins-console.txt.gz?authuser=0)

**Comment by catarineaguiar** [comment]
@julschong no regressions found

**Comment by julschong** [comment]
rebased to resolve conflict for

> 
modules/apps/asset/asset-categories-admin-web/src/main/java/com/liferay/asset/categories/admin/web/internal/portlet/AssetCategoryAdminPortlet.java

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:sf

**Pull request closed without merging**
