### PR TITLE
LPS-147065 Use the default portlet title translation if exists #310

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Hi @tinatian 

It is stored in the PortletPreferenceValue table using the site default locale (in the reproduction steps example as portletSetUpTitle_en_US).

When the portlet configuration view renders the custom title selectors, this translation is labeled as DEFAULT, but this is not consistent with the behavior of the backend, that only returns the value of the PortletPreferenceValue in the current locale.

Does it solve your question?

**Comment by tinatian** [comment]
@robertoDiaz Yes. This is consistent with what you did in the fix. Can you add a test to cover this change? Basically to show people that the expected behavior is to fall back to site's default locale.

Thanks.
Tina.

**Comment by robertoDiaz** [comment]
Hi @tinatian,

I've been checking our integration and unit test and I haven't found any similar test.

Maybe it fits better as functional test. Do you agree?

If that's the case, could we ask your QA engineers to create it?

Thanks!

**Comment by robertoDiaz** [comment]
@tinatian 

BTW, if you don't mind I'll provide this fix to the customer as Support Driven Hotfix while we create the test.

Are you OK with that?

**Comment by tinatian** [comment]
@robertoDiaz Yes, to add integration test, a lot of methods need to be mocked. Functional test should be a good choice.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

**Comment by robertoDiaz** [comment]
Hi @liferay-core-infra 

Any update related with this PR? A customer is waiting for this changes. Could I provide a SHD based in this?

Thanks!

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
