### PR TITLE
[Bug Fix]LPS-145375

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks
Tina

**Comment by vicnate5** [comment]
@tinatian Is this specific bug testable on master?

No regressions found in automation tests.

**Comment by tinatian** [comment]
@vicnate5 Yes, it should be reproducible on master. I believe we did not see the error because the log level by default is FATAL. If we do not have test covered this, could you please add it?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@kyle-miho could you test this manually and then add a test?

**Comment by kyle-miho** [comment]
We can just adjust our logging levels on CI for this specific class, so our upgrade tests will be able to catch it (and this is probably the proper way to test this) ill work on this monday

**Comment by tinatian** [comment]
@kyle-miho How is going on with this pull?

Thanks.
Tina.

**Comment by kyle-miho** [comment]
@tinatian sorry i havent had time to get to this recently due to nonstop release analysis. I'll prioritize at least being able to test this manually (Likely on Monday), and just add the automation for it afterwards.

**Comment by tinatian** [comment]
@kyle-miho How's going on with the manual test?

Tina

**Comment by kyle-miho** [comment]
@tinatian this pr is good to go

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
