### PR TITLE
LPS-144640 Remove jcifs.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
Hey @vicnate5,

Can you help me scan these tests' results?

Thx

**Comment by vicnate5** [comment]
@koor4356 can you check this one?

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
@rafaprax 
This PR looks good. Thanks!

**Comment by rafaprax** [comment]
Hey @shuyangzhou, this PR is ready for your review. Thx

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
