### PR TITLE
[TS] LPS-157843

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, please review the ticket after ci test finished.

cc @ricardocousolr

### CODE REVIEW

**Comment by yuhai** [comment]
@zhangyan0701, please help check if SequenceEntryLocalServiceTest was passed on the different databases.

**Comment by Kvale1733** [comment]
@yuhai No regression were found in relevant but the test only ran on MySql. I'm going to setup a custom CI run so the test runs on the 3 intended environments.

**Comment by Kvale1733** [comment]
Running SequenceEntryLocalServiceTest on Oracle, DB2, and PostgreSQL here:
https://github.com/Kvale1733/liferay-portal/pull/301

**Comment by Kvale1733** [comment]
@yuhai The test passed on all three databases without exceptions.

**Comment by tinatian** [comment]
@Kvale1733 Which test batch is going to run this new added test "SequenceEntryLocalServiceTest"? it should be part of the service builder test.

**Comment by Kvale1733** [comment]
@tinatian So in this case the test was picked up by relevant, but was skipped as it's setup to run only in Oracle, DB2, and PostgreSQL. And relevant is only setup to integration tests in MySQL. As of now this test would only really run in acceptance. I'll add the necessary properties to run this test in relevant (and others since currently they only run in relevant when the test modules are modified or when certain modules are modified that run all tests).

**Comment by tinatian** [comment]
@Kvale1733 Please modify ci and rerun the this pull, I think the current test result may not include the new added test.

**Comment by Kvale1733** [comment]
@tinatian Results for the test are included in this ci run I set up:https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2239852911. Here is the case link for each. If you check each log testAddSequenceEntry ran and passed. 

[Oracle](https://testray.liferay.com/home/-/testray/case_results/2239853573?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2239852911%26testrayRunId%3D2239853559%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
[PostgreSQL](https://testray.liferay.com/home/-/testray/case_results/2239853694?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2239852911%26testrayRunId%3D2239853616%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
[DB2](https://testray.liferay.com/home/-/testray/case_results/2239853558?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2239852911%26testrayRunId%3D2239853537%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

I tried adding the test to relevant, but it looks like I wont be able to since it's limited to running integration tests in MySQL and I'm not able to add additional batches in the module test properties. I'll have to add a service builder test suite so this can easily be run in future PR's. We should have one anyways. Testing that here: https://github.com/Kvale1733/liferay-portal/pull/304.

**Comment by Kvale1733** [comment]
@tinatian The test passed on all three databases.

**Comment by Kvale1733** [comment]
@tinatian With ci:test:service-builder this test will run. We can run this suite for service builder changes.

**Comment by tinatian** [comment]
@Kvale1733 Are you sure ci:test:service-builder this test will run this new added test? Did yo ever see the log related to this test? This test is added to a separate module that is not the one most other service builder related tests stay in. 

FYI @vicnate5

**Comment by Kvale1733** [comment]
@tinatian Yes. I added the suite myself and ran it here: https://github.com/Kvale1733/liferay-portal/pull/304. It ran on all 3 databases.

**Comment by Kvale1733** [comment]
[DB2: ](https://testray.liferay.com/home/-/testray/case_results/2243779319?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2243778412%26testrayRunId%3D2243779310%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

[Oracle](https://testray.liferay.com/home/-/testray/case_results/2243779327?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2243778412%26testrayRunId%3D2243779320%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

[PostgreSQL](https://testray.liferay.com/home/-/testray/case_results/2243779341?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2243778412%26testrayRunId%3D2243779328%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Comment by tinatian** [comment]
@Kvale1733 Please add the test suite you added to this pull so that we can make sure the test can be run by ci:test:service-builder, there is no change in this pull about ci, that's why I really doubt the test got run.

Thanks.
Tina.

**Comment by Kvale1733** [comment]
ci:test:service-builder

**Comment by tinatian** [comment]
ci:forward

**Comment by Kvale1733** [comment]
@tinatian Because this test is setup to only run on PostgreSQL, DB2, and Oracle, if it runs on any other database it simply gets skipped. It was triggered on relevant and was marked as passed, but it didn't really. So I excluded this test from running on on any other database on the suite because of that.

If any other test is added to portal-tools-service-builder-test-sequence-test it will still run those tests on MySQL though. Relevant will still run the the service-builder-jdk8 batch on those new modules.

But if you wan't this specific test to run on MySQL you'd have to modify this part in the test
```
Assume.assumeTrue(
			(dbType == DBType.DB2) || (dbType == DBType.ORACLE) ||
			(dbType == DBType.POSTGRESQL));
```

**Pull request closed without merging**
