### PR TITLE
[OrderByComparator] LPD-26512 Clean up and Apply Singleton in module portal-background-task-service

### PR DESCRIPTION
**Pull request by rubenssoares-br**
Ticket: https://liferay.atlassian.net/browse/LPD-26512

### CODE REVIEW

**Comment by rubenssoares-br** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:2571455685

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/150645

@rubenssoares-br I changed the message of a commit, see https://github.com/brianchandotcom/liferay-portal/pull/150645/commits/3f7989b8c62586a8eb68597a2cc1043959d6229c

cc @tinatian

**Pull request closed without merging**
