### PR TITLE
[Bug Fix] LPS-151508

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, @tinatian, the pr is based on https://github.com/liferay-core-infra/liferay-portal/pull/661

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:backend

**Comment by yuhai** [comment]
@zhangyan0701, could you please check if ViewCountEntryLocalServiceTest was passed (especially on the SQLSERVER database) from the test result? Thanks

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/691

**Comment by dantewang** [comment]
ci:close

**Comment by dantewang** [comment]
@zhangyan0701 You can still check this PR's CI result, as I only did some SF in the new PR.

**Comment by zhangyan0701** [comment]
@yuhai 

The ViewCountEntryLocalServiceTest passed on SQL Server, and all other environments.

**Pull request closed without merging**
