### PR TITLE
LPD-40974 Inconsistent Deprecation Feature Flag Behavior in New Installations

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Resent from https://github.com/liferay-core-infra/liferay-portal/pull/7606

--

https://liferay.atlassian.net/browse/LPD-40974

Fixing release blocker introduced in https://github.com/brianchandotcom/liferay-portal/commit/4fb37b76791574f475fb2c54ddf43877936fd73d. Since the component starts after portal is UP, the default company addition wouldn't trigger the CompanyModelListener

Related [slack thread](https://liferay.slack.com/archives/C049XG98GQL/p1730305021159829)

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:upgrade

**Comment by ethib137** [comment]
@tinatian is anything needed before we can forward this one?

**Comment by tinatian** [comment]
@ethib137 If the only changes here are renaming based on Brian's requirement, please ignore me and move on as we have already reviewed the concept of implementation last time.

**Comment by thiago-buarqque** [comment]
Thanks @tinatian. Moving forward

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:upgrade

**Comment by thiago-buarqque** [comment]
Upgrade errors are unrelated. 
```
Feature flag LPD-27566 is not available for company 0
```

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:upgrade

**Comment by thiago-buarqque** [comment]
ci:test:platform-experience

**Comment by thiago-buarqque** [comment]
CI errors are unrelated. @tinatian May I forward this?

**Comment by tinatian** [comment]
@thiago-buarqque Please check my previous comment https://github.com/liferay-core-infra/liferay-portal/pull/7625#issuecomment-2484771367.

You force pushed this pull and I have no idea what changed, do you need extra review of it?

**Comment by ethib137** [comment]
Based on @tinatian 's [previous comment](https://github.com/liferay-core-infra/liferay-portal/pull/7625#issuecomment-2484771367) and since there are no changes that weren't already agreed upon. I am going to forward this.

**Comment by ethib137** [comment]
ci:forward:force

**Pull request closed without merging**
