### PR TITLE
[Reference cleanup]LPS-162029

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to convert method references to field references in `dynamic-data-lists-service`. Thanks!
https://issues.liferay.com/browse/LPS-162029

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @catarineaguiar, Could you please help to scan the test results? Thank you!

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122874

**Pull request closed without merging**
