### PR TITLE
[Remove blocking usages] LPS-196123 Move DLPreviewableProcessor

### PR DESCRIPTION
**Pull request by W2jx**
resend, Just modify the breaking change message in the commit message

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5918

### CODE REVIEW

**Comment by W2jx** [comment]
Mostly tested in https://github.com/liferay-core-infra/liferay-portal/pull/5870

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
no conflicts(10/31 7:57)

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by W2jx** [comment]
no conflicts(11/1 9:03)

**Comment by zhangyan0701** [comment]
Failures in below test seem related:
[com.liferay.adaptive.media.document.library.thumbnails.internal.osgi.commands.test.AMThumbnailsOSGiCommandsTest](https://testray.liferay.com/home/-/testray/case_results/2449719206):

```
##
## com.liferay.adaptive.media.document.library.thumbnails.internal.osgi.commands.test.AMThumbnailsOSGiCommandsTest > testCleanUpDeletesImageThumbnails
##

	java.lang.AssertionError: expected:<1> but was:<0>
```
```
##
## com.liferay.adaptive.media.document.library.thumbnails.internal.osgi.commands.test.AMThumbnailsOSGiCommandsTest > testCleanUpDeletesOnlyImageThumbnails
##

	java.lang.AssertionError: expected:<2> but was:<0>
```
```
##
## com.liferay.adaptive.media.document.library.thumbnails.internal.osgi.commands.test.AMThumbnailsOSGiCommandsTest > testMigrateDoesNotRemoveThumbnails
##

	java.lang.AssertionError: expected:<2> but was:<0>
```
```
##
## com.liferay.adaptive.media.document.library.thumbnails.internal.osgi.commands.test.AMThumbnailsOSGiCommandsTest > testMigrateThrowsExceptionWhenNoValidConfiguration
##

	java.lang.NullPointerException
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-10/test-1-34/test-portal-acceptance-pullrequest(master)/4951/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0

**Pull request closed without merging**
