### PR TITLE
[Method References 2] LPS-169905 Convert method reference to ServiceTrackerMap in classes AccountRoleRequestHelper

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian , I have modified commits. And about this [comment](https://github.com/liferay-core-infra/liferay-portal/pull/3595#issuecomment-1454304227), I've tried merging these trackers, but it didn't work very well (see [here](https://github.com/liferay-core-infra/liferay-portal/pull/3411) for details), do you have any good ideas on how to merge them? Thanks!

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3595

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:account

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(3/7 9:02)

**Comment by W2jx** [comment]
no conflicts(3/8 15:25)

**Comment by W2jx** [comment]
no conflicts(3/14 15:20)

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
