### PR TITLE
LPS-193289 Remove Value Mapper

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:upgrade

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong No regressions. Only a semver issue

```
[exec] > Task :baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.upgrade.util                    MAJOR      6.1.0      6.1.0      7.0.0      VERSION INCREASE REQUIRED
     [exec] 	-   class      com.liferay.portal.upgrade.util.MemoryValueMapper
     [exec] 		-   implements com.liferay.portal.kernel.upgrade.util.ValueMapper
     [exec] 		-   method     <init>()
     [exec] 			-   return     void
     [exec] 		-   method     <init>(java.util.Set)
     [exec] 			-   return     void
     [exec] 		-   method     appendException(java.lang.Object)
     [exec] 			-   return     void
     [exec] 		-   method     clone()
     [exec] 			-   access     protected
     [exec] 			-   return     java.lang.Object
     [exec] 		-   method     equals(java.lang.Object)
     [exec] 			-   return     boolean
     [exec] 		-   method     finalize()
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     getMap()
     [exec] 			-   return     java.util.Map
     [exec] 		-   method     getNewValue(java.lang.Object)
     [exec] 			-   return     java.lang.Object
     [exec] 		-   method     hashCode()
     [exec] 			-   return     int
     [exec] 		-   method     iterator()
     [exec] 			-   return     java.util.Iterator
     [exec] 		-   method     mapValue(java.lang.Object,java.lang.Object)
     [exec] 			-   return     void
     [exec] 		-   method     size()
     [exec] 			-   return     int
     [exec] 		-   method     toString()
     [exec] 			-   return     java.lang.String
     [exec] 	-   class      com.liferay.portal.upgrade.util.MemoryValueMapperFactoryImpl
     [exec] 		-   implements com.liferay.portal.kernel.upgrade.util.ValueMapperFactory
     [exec] 		-   method     <init>()
     [exec] 			-   return     void
     [exec] 		-   method     clone()
     [exec] 			-   access     protected
     [exec] 			-   return     java.lang.Object
     [exec] 		-   method     equals(java.lang.Object)
     [exec] 			-   return     boolean
     [exec] 		-   method     finalize()
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     getValueMapper()
     [exec] 			-   return     com.liferay.portal.kernel.upgrade.util.ValueMapper
     [exec] 		-   method     hashCode()
     [exec] 			-   return     int
     [exec] 		-   method     toString()
     [exec] 			-   return     java.lang.String
     [exec] [Baseline Warning] Bundle Version Change Recommended: 86.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-impl/portal-impl.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.impl/85.0.1/9070ac5e0b610786d4793069736dd32b5af2bb7a/com.liferay.portal.impl-85.0.1.jar
     [exec] Gradle build finished at 2023-08-12 00:12:56.146.
```
[Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-28/test-portal-acceptance-pullrequest(master)/7247/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
resending

**Pull request closed without merging**
