### PR TITLE
[Unused Reference] LPD-8472 LPD-8473 Remove unused @Reference variables in WabFactory and PortletTracker

### PR DESCRIPTION
**Pull request by MrJohn1911**
This solution was made since the `PortletTracker` and the `WabFactory` components has a dependency for `ModuleServiceLifecycle`, which grants that the `ServletContextHelperFactory` will always be ready before them (the `ServletContextHelperRegistrationServiceFactory` will be registered before the `WabBundleProcessor` or the `PortletTracker` tries to get the service reference for it).

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:stable

**Comment by dantewang** [comment]
@MrJohn1911 

> This solution was made since the PortletTracker and the WabFactory components has a dependency for ModuleServiceLifecycle, which grants that the ServletContextHelperFactory will always be ready before them.

Could you explain this part with more details?

**Pull request closed without merging**
