### PR TITLE
[Method References 3] LPS-179398 Convert method reference to serviceTrackerMap in class LayoutStructureItemImporterRegistry

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by W2jx** [comment]
no conflicts(3:24 13:31)

**Comment by W2jx** [comment]
no conflicts(3/27 9:41)

**Comment by Kvale1733** [comment]
@W2jx No regressions.

**Comment by W2jx** [comment]
no conflicts(3/30 8:52)

**Comment by W2jx** [comment]
no conflicts(4/3 9:13)

**Comment by W2jx** [comment]
no conflicts(4/4 10:27)

**Comment by W2jx** [comment]
no conflicts(4/7 16:16)

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133041

**Pull request closed without merging**
