### PR TITLE
[Remove unused @Reference var] LPS-164333

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove the unused @reference variable in the module `change-tracking-web`. Thanks!

https://issues.liferay.com/browse/LPS-164333

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:publication

**Comment by tinatian** [comment]
ci:test:publications

**Comment by tinatian** [comment]
@Kvale1733 Please help scan test result once it is finished.

Thanks.
Tina

**Comment by Kvale1733** [comment]
@tinatian No regressions in publications.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
