### PR TITLE
LPS-200170 Merge TunnelAuthenticationManager interface and impl into Util and move to portal-impl

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong regressions found:

```
    [junit] Testcase: testScanGradleFiles(com.liferay.portal.modules.ModulesStructureTest):	FAILED
    [junit] Redundant dependency detected in modules/apps/batch-engine/batch-engine-service/build.gradle expected:<compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"> but was:<testImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default">
    [junit] junit.framework.AssertionFailedError: Redundant dependency detected in modules/apps/batch-engine/batch-engine-service/build.gradle expected:<compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"> but was:<testImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default">
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest._testGradleFile(ModulesStructureTest.java:1506)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest.access$800(ModulesStructureTest.java:59)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest$4.visitFile(ModulesStructureTest.java:393)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest$4.visitFile(ModulesStructureTest.java:367)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest.testScanGradleFiles(ModulesStructureTest.java:365)
    [junit] 
    [junit] 
    [junit] Test com.liferay.portal.modules.ModulesStructureTest FAILED
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-33/test-portal-acceptance-pullrequest(master)/4645/central-requirements-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
     [echo] diff --git a/modules/apps/account/account-service/src/main/java/com/liferay/account/service/http/AccountEntryOrganizationRelServiceHttp.java b/modules/apps/account/account-service/src/main/java/com/liferay/account/service/http/AccountEntryOrganizationRelServiceHttp.java
     [echo] index ce1eeb92f6ca3..c9c41983affa5 100644
     [echo] --- a/modules/apps/account/account-service/src/main/java/com/liferay/account/service/http/AccountEntryOrganizationRelServiceHttp.java
     [echo] +++ b/modules/apps/account/account-service/src/main/java/com/liferay/account/service/http/AccountEntryOrganizationRelServiceHttp.java
     [echo] @@ -9,7 +9,7 @@ import com.liferay.account.service.AccountEntryOrganizationRelServiceUtil;
     [echo]  import com.liferay.portal.kernel.log.Log;
     [echo]  import com.liferay.portal.kernel.log.LogFactoryUtil;
     [echo]  import com.liferay.portal.kernel.security.auth.HttpPrincipal;
     [echo] -import com.liferay.portal.service.http.TunnelUtil;
     [echo] +import com.liferay.portal.kernel.service.http.TunnelUtil;
     [echo]  import com.liferay.portal.kernel.util.MethodHandler;
     [echo]  import com.liferay.portal.kernel.util.MethodKey;
```
please, see the full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-33/test-portal-acceptance-pullrequest(master)/4645/service-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
> @julschong regressions found:
> 
> ```
>     [junit] Testcase: testScanGradleFiles(com.liferay.portal.modules.ModulesStructureTest):	FAILED
>     [junit] Redundant dependency detected in modules/apps/batch-engine/batch-engine-service/build.gradle expected:<compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"> but was:<testImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default">
>     [junit] junit.framework.AssertionFailedError: Redundant dependency detected in modules/apps/batch-engine/batch-engine-service/build.gradle expected:<compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"> but was:<testImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default">
>     [junit] 	at com.liferay.portal.modules.ModulesStructureTest._testGradleFile(ModulesStructureTest.java:1506)
>     [junit] 	at com.liferay.portal.modules.ModulesStructureTest.access$800(ModulesStructureTest.java:59)
>     [junit] 	at com.liferay.portal.modules.ModulesStructureTest$4.visitFile(ModulesStructureTest.java:393)
>     [junit] 	at com.liferay.portal.modules.ModulesStructureTest$4.visitFile(ModulesStructureTest.java:367)
>     [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
>     [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
>     [junit] 	at com.liferay.portal.modules.ModulesStructureTest.testScanGradleFiles(ModulesStructureTest.java:365)
>     [junit] 
>     [junit] 
>     [junit] Test com.liferay.portal.modules.ModulesStructureTest FAILED
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-33/test-portal-acceptance-pullrequest(master)/4645/central-requirements-jdk8/0/0/jenkins-console.txt.gz?authuser=0)
> 
> ```
>      [echo] diff --git a/modules/apps/account/account-service/src/main/java/com/liferay/account/service/http/AccountEntryOrganizationRelServiceHttp.java b/modules/apps/account/account-service/src/main/java/com/liferay/account/service/http/AccountEntryOrganizationRelServiceHttp.java
>      [echo] index ce1eeb92f6ca3..c9c41983affa5 100644
>      [echo] --- a/modules/apps/account/account-service/src/main/java/com/liferay/account/service/http/AccountEntryOrganizationRelServiceHttp.java
>      [echo] +++ b/modules/apps/account/account-service/src/main/java/com/liferay/account/service/http/AccountEntryOrganizationRelServiceHttp.java
>      [echo] @@ -9,7 +9,7 @@ import com.liferay.account.service.AccountEntryOrganizationRelServiceUtil;
>      [echo]  import com.liferay.portal.kernel.log.Log;
>      [echo]  import com.liferay.portal.kernel.log.LogFactoryUtil;
>      [echo]  import com.liferay.portal.kernel.security.auth.HttpPrincipal;
>      [echo] -import com.liferay.portal.service.http.TunnelUtil;
>      [echo] +import com.liferay.portal.kernel.service.http.TunnelUtil;
>      [echo]  import com.liferay.portal.kernel.util.MethodHandler;
>      [echo]  import com.liferay.portal.kernel.util.MethodKey;
> ```
> 
> please, see the full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-33/test-portal-acceptance-pullrequest(master)/4645/service-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

I rebased and added fix for the 1st regresion.
Not sure about the 2nd one there. Testing for now

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
fix sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
reran service builder

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
Most tests failed with a startup error

```
beanshell] 2023-11-16 03:49:11.595 INFO  [main][ModuleFrameworkImpl:1642] Starting dynamic bundles
[beanshell] 2023-11-16 03:49:11.612 ERROR [SystemExecutorServiceUtil-1-Portal Spring Init Thread][ContextLoader:225] Context initialization failed
[beanshell] org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [com.liferay.portal.kernel.security.auth.tunnel.TunnelAuthenticationManagerUtil] for bean with name 'com.liferay.portal.kernel.security.auth.tunnel.TunnelAuthenticationManagerUtil' defined in class path resource [META-INF/security-spring.xml]; nested exception is java.lang.ClassNotFoundException: com.liferay.portal.kernel.security.auth.tunnel.TunnelAuthenticationManagerUtil
[beanshell] 	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1486) ~[spring-beans.jar:5.2.24.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:681) ~[spring-beans.jar:5.2.24.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:648) ~[spring-beans.jar:5.2.24.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1614) ~[spring-beans.jar:5.2.24.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1090) ~[spring-beans.jar:5.2.24.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:877) ~[spring-beans.jar:5.2.24.RELEASE]
[beanshell] 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context.jar:5.2.24.RELEASE]
[beanshell] 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context.jar:5.2.24.RELEASE]
[beanshell] 	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401) ~[spring-web.jar:5.2.24.RELEASE]
[beanshell] 	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292) ~[spring-web.jar:5.2.24.RELEASE]
[beanshell] 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103) ~[spring-web.jar:5.2.24.RELEASE]
[beanshell] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.lambda$_contextInitialized$1(PortalContextLoaderListener.java:391) ~[portal-impl.jar:?]
[beanshell] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_381]
[beanshell] 	at com.liferay.portal.kernel.concurrent.SystemExecutorServiceUtil.lambda$renameThread$1(SystemExecutorServiceUtil.java:59) ~[portal-kernel.jar:?]
[beanshell] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_381]
[beanshell] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_381]
[beanshell] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_381]
[beanshell] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_381]
[beanshell] 	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_381]
[beanshell] Caused by: java.lang.ClassNotFoundException: com.liferay.portal.kernel.security.auth.tunnel.TunnelAuthenticationManagerUtil
[beanshell] 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1329) ~[catalina.jar:9.0.82]
[beanshell] 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1141) ~[catalina.jar:9.0.82]
[beanshell] 	at com.liferay.shielded.container.internal.ShieldedContainerClassLoader.findClass(ShieldedContainerClassLoader.java:70) ~[com.liferay.shielded.container.impl.jar:?]
[beanshell] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_381]
[beanshell] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_381]
[beanshell] 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_381]
[beanshell] 	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_381]
[beanshell] 	at org.springframework.util.ClassUtils.forName(ClassUtils.java:284) ~[spring-core.jar:5.2.24.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:469) ~[spring-beans.jar:5.2.24.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1551) ~[spring-beans.jar:5.2.24.RELEASE]
[beanshell] 	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1478) ~[spring-beans.jar:5.2.24.RELEASE]
[beanshell] 	... 18 more
[beanshell] 2023-11-16 03:49:15.202 DEBUG [Start Level: Equinox Container: a3e20bc5-599a-4560-9aef-4a67b381de45][BundleStartStopLogger:77] STARTED org.apache.ws.xmlschema.core_2.2.5 [87]
[beanshell] 2023-11-16 03:49:15.203 DEBUG [Start Level: Equinox Container: a3e20bc5-599a-4560-9aef-4a67b381de45][BundleStartStopLogg
```

[Log](https://testray.liferay.com/reports/production/logs/2023-11/test-1-26/test-portal-acceptance-pullrequest(master)/11963/functional-smoke-tomcat90-hypersonic20-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
ci:close

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@julschong `TunnelAuthenticationManagerImpl` uses service layer, as Tina commented in https://github.com/liferay-core-infra/liferay-portal/pull/5987#issuecomment-1813129320, please resend with the impl moved to module.

**Pull request closed without merging**
