### PR TITLE
LPS-158624 Cleanup petra-xml

### PR DESCRIPTION
**Pull request by julschong**
resubmit from #2158

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by tinatian** [comment]
@julschong Please update the commit message of https://github.com/liferay-core-infra/liferay-portal/pull/2255/commits/d89fc255e8c0aa409a76fc02f15b7101cc8049bb

**Comment by tinatian** [comment]
@julschong I am going to close this pull as we talked yesterday.

**Pull request closed without merging**
