### PR TITLE
LPD-38963 Consider alias type when calculating the finder cache key

### PR DESCRIPTION
**Pull request by dantewang**
Fixing DSLQueryEntryPersistenceImplTest caused by https://liferay.atlassian.net/browse/LPD-32543

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:37812235

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:38781098

**Comment by dantewang** [comment]
ci:report:38781098

**Comment by dantewang** [comment]
Comparing the 2 runs, no unique failure in relevant.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7533

**Pull request closed without merging**
