### PR TITLE
[Method References 2] LPS-169905 Convert method reference to ServiceTrackerMap in classes AccountRoleRequestHelper

### PR DESCRIPTION
**Pull request by W2jx**
resend, I have modified the code according to the [comment](https://github.com/brianchandotcom/liferay-portal/pull/131783#issuecomment-1471024433).

Previous: https://github.com/brianchandotcom/liferay-portal/pull/131783

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:account

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
no conflicts(3/20 8:52)

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(3/21 10:29)

**Pull request closed without merging**
