### PR TITLE
[Replace Non-Blocking Usage] LPS-199723

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace non-blocking ServiceProxyFactory usages in class `BackgroundTaskStatusRegistryUtil`, `BackgroundTaskManageryUtil`,  `BackgroundTaskExecutorRegistryUtil` and  `BackgroundTaskDisplayFactoryUtil`. Thanks.
https://liferay.atlassian.net/browse/LPS-199723

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
