### PR TITLE
[OrderByComparator] LPD-26438,LPD-26157 Clean up and Apply Singleton in journal module

### PR DESCRIPTION
**Pull request by Valmir-unicap**
- Ticket: https://liferay.atlassian.net/browse/LPD-26438

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:report:31667896

**Comment by dantewang** [comment]
ci:report:31667896

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:report:33171679

**Comment by dantewang** [comment]
ci:report:33171679

**Comment by dantewang** [comment]
@Valmir-unicap There's a test failure of `com.liferay.source.formatter.processor.UpgradeSourceProcessorTest` in relevant. Could you double check? Thanks!

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:report:33480482

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:report:34333677

**Comment by Valmir-unicap** [comment]
ci:report:34333677

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
This SF failure is not related to my changes.

**Comment by dantewang** [comment]
@Valmir-unicap The pattern seems to be correctly applied.

Could you please re-arrange the PR:

1. Put changes to the comparator in 1 commit, without modifying others;
2. Put the "applies" to another commit;
3. Put the update to the SF json and testjava files to the third commit;
4. Deprecate (do we really need to deprecate?)
5. If there are so many files and you want to group them by packages or modules, etc., in each group, repeat 1~4
6. baseline

And, send the commit for `LPD-26157` in a separate PR and forward to BChan as long as SF and relevant passes.

**Pull request closed without merging**
