### PR TITLE
LPS-142279 Refactor ClassUtil & PortalClassPathUtil to reuse common logic

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@kyle-miho
Hi Kyle, would you please help me scan the test results?
Thank you

**Comment by kyle-miho** [comment]
@julschong failures seem to be unrelated, pr should be good

**Comment by julschong** [comment]
@tinatian Hi Tina,
Could you please help review this PR to see if its good to go?
Thank you!

**Comment by tinatian** [comment]
@julschong As we talked, I am going to close this pull, please resend.

Thanks.
Tina

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
