### PR TITLE
[Replace Non-Blocking Usage] LPS-199499

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace non-blocking ServiceProxyFactory usages in class `ClusterMasterExecutorUtil`, `ClusterExecutorUtil`, and `ClusterLinkUtil`. Thanks.
https://liferay.atlassian.net/browse/LPS-199499

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
@JanisZhang Regarding the "unused" methods you removed, please either document breaking changes in the commit, or keep them. Please resend, thanks!

**Comment by JanisZhang** [comment]
Got it, I will review the rest pr I sent. Thanks. @dantewang

**Pull request closed without merging**
