### PR TITLE
[OrderByComparator] LPD-28287 master

### PR DESCRIPTION
**Pull request by titokenzo**
- **LPD-28287 Add singleton to module commerce-api OrderByComparator sub-classes**
- **LPD-28287 Update integration test**
- **LPD-28287 Apply OrderByComparator usages**
- **LPD-28287 Add singleton to portal-kernel OrderByComparator sub-classes**
- **LPD-28287 Update integration tests**
- **LPD-28287 Apply OrderByComparator usages**
- **LPD-28287 SemVer commerce-api**
- **LPD-28287 SemVer portal-kernel**
- **LPD-28287 Add Upgrade case and test**

### CODE REVIEW

**Comment by titokenzo** [comment]
ci:test:sf

**Comment by titokenzo** [comment]
ci:test:relevant

**Comment by victorhcunha** [comment]
Resent solving conflicts https://github.com/liferay-core-infra/liferay-portal/pull/7276

**Comment by victorhcunha** [comment]
ci:

**Comment by victorhcunha** [comment]
ci:close

**Pull request closed without merging**
