### PR TITLE
[Bug Fix] LPS-142911

### PR DESCRIPTION
**Pull request by yuhai**
@tinatian, @dantewang, the pr is based on the [requirement](https://github.com/liferay-core-infra/liferay-portal/pull/389)

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/395

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
