### PR TITLE
[System Properties] LPS-158207 Add new functionality to SystemProperties: properly handle comments within a multi-line property value

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I add a new method and unit test in this pr.

Detail: https://github.com/liferay-core-infra/liferay-portal/pull/1197

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results when they finish ? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by W2jx** [comment]
resolve conflicts

**Comment by shuyangzhou** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/1307

**Pull request closed without merging**
