### PR TITLE
LPS-199165 Merge AuthenticatedSessionManager interface and impl into Util and move to portal-impl

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@julschong There is a failure in the portal-license-smoke-mysql57-jdk8 batch.

```
build-common-java.compile:
    [javac] Compiling 2215 source files to /opt/dev/projects/github/liferay-portal/portal-impl/classes
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/ee/license/LifecycleAction.java:14: error: package com.liferay.portal.kernel.security.auth.session does not exist
    [javac] import com.liferay.portal.kernel.security.auth.session.AuthenticatedSessionManagerUtil;
    [javac]                                                       ^
    [javac] 1 error
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:7338: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:7372: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:13306: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-release-tool-ee/build-release-slim.xml:40: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build.xml:323: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common-java.xml:52: Compile failed; see the compiler error output for details.
 ```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-39/test-portal-acceptance-pullrequest(master)/7921/portal-license-smoke-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

I think that class might be referenced in the release tool repo since this batch tests on a release bundle. I don't have access to it so I can't verify.

**Comment by julschong** [comment]
added release repo change pull request

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@julschong No regressions found.

**Comment by julschong** [comment]
added breaking change commit messages

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142628

**Pull request closed without merging**
