### PR TITLE
[Method References 2] LPS-177276 Convert method reference to ServiceTrackerList in class CompanyIndexFactory

### PR DESCRIPTION
**Pull request by dantewang**
Add SF

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:search

**Comment by liuxingye** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@dantewang No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133039

**Pull request closed without merging**
