### PR TITLE
[Remove Spring extender usages] LPS-159168 commerce-currency-service: import default values using UpgradeProcess

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@dantewang no regressions found.

**Comment by tinatian** [comment]
@vicnate5 This pull reverts changes made by https://issues.liferay.com/browse/COMMERCE-6391, also it is related to https://issues.liferay.com/browse/LPS-153078, cloud you please verify if we did not have any regression?

Thanks.
Tina.

**Comment by vicnate5** [comment]
ci:test:smoke

**Comment by vicnate5** [comment]
ci:test:smoke

**Comment by vicnate5** [comment]
ci:test:smoke

**Comment by vicnate5** [comment]
ci:test:smoke

**Comment by vicnate5** [comment]
@tinatian This should be good to.

**Comment by dantewang** [comment]
Closing this one since we're going to resend.

**Pull request closed without merging**
