### PR TITLE
LPS-145050

### PR DESCRIPTION
**Pull request by tinatian**
Hi Shuyang,

This pull is good to go, it has passed ci test at https://github.com/tinatian/liferay-portal/pull/2502.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113134

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
