### PR TITLE
[Reference cleanup]LPS-162577

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to convert method references to field references in journal-web. Thanks!

https://issues.liferay.com/browse/LPS-162577

### CODE REVIEW

**Comment by JanisZhang** [comment]
Hi @zhangyan0701, Could you please help to scan the test results? Thanks

**Comment by zhangyan0701** [comment]
@JanisZhang  All relevant tests passed.

**Review by dantewang — APPROVED** [review]
@shuyangzhou @tinatian Forwarding this one as all tests passed and changes are direct replacements.

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
