### PR TITLE
[Components with more than 1 service] LPS-176867 Refactor Portlet components with more than 1 service type from Analytics Cloud

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:analytics-cloud-acceptance

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by rafaprax** [comment]
Looks good to me.
 
/cc @tinatian

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131774

**Pull request closed without merging**
