### PR TITLE
[Method References 2] LPS-176118 Convert method references to serviceTracker in class ThemeContributorTopHeadDynamicInclude

### PR DESCRIPTION
**Pull request by W2jx**
Hi @dantewang , I have resent it.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3803

### CODE REVIEW

**Review by dantewang — APPROVED** [review]
@tinatian We have to keep using `ServiceTracker` + separate collection, not for ordering, but to avoid the possibility of race condition -- we must make sure the invalidation of the cached `_resourceURLsBag` and the update to the service collection atomic.

If we use `ServiceTrackerList`, with current API, there will be a gap between invalidating the cache field and adding the service to the list. If a rebuild is triggered in this gap, the newly tracked service won't take effect.

**Comment by Kvale1733** [comment]
ci:test:frontend

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(3/23 15:56)

**Pull request closed without merging**
