### PR TITLE
LPS-168934 Remove Dom4jUtil.toString() usages in portal tools

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from #2481

instead of wrapping 3rd party with liferay api: https://github.com/liferay-core-infra/liferay-portal/commit/5ca9f6ca270a025b67d9ba0ef259b2d5f43a2aae#diff-13e92ee40363511f70da80227056c5ca9b92f94f947c85f6bf638f3606f09647R113

convert both SPDXBuilder and XSLTBuilder to use liferay api entirely

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by julschong** [comment]
rebased for conflict in semver

**Comment by tinatian** [comment]
@julschong The changes looks good to me, but it has code conflicts with Bchan's master, I can not forward it now, please wait for the changes merged in to upstream and rebase.

Thanks.
Tina.

**Comment by julschong** [comment]
rebased for semver

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127264

**Pull request closed without merging**
