### PR TITLE
master core 1872

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-77885

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@ChrisKian tests are ready, as I mentioned on Slack, when I click on "Display the page in English (United States)." in the virtualhost a message appears in the logs:
`ERROR [http-nio-8080-exec-7][JSONWebServiceServiceAction:126] Conversion failed: 1,3; <--- java.lang.NumberFormatException: For input string: "1,3"`
on UI everything looks good.

**Comment by crodriguezy** [comment]
Hi @ChrisKian @catarineaguiar is this ready to move forward?

**Comment by ChrisKian** [comment]
Hi @catarineaguiar,
With these changes on the latest version of master, I am no longer able to reproduce the issue you've described (although I was able to do so in earlier versions).  Can you please rebase the solution locally and confirm my findings?

**Comment by catarineaguiar** [comment]
@crodriguezy I checked and everything looks ok. The pull is good to go

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125563

**Pull request closed without merging**
