### PR TITLE
[OrderByComparator] LPD-28821 Clean up and Apply Singleton in kernel comparator part II

### PR DESCRIPTION
**Pull request by victorhcunha**
[LPD-28821](https://liferay.atlassian.net/browse/LPD-28821)
- **LPD-28821 Add singleton to LayoutComparator and apply**
- **LPD-28821 Add singleton to LayoutPrototypeCreateDateComparator and apply**
- **LPD-28821 Add singleton to LayoutRevisionCreateDateComparator and apply**
- **LPD-28821 Add singleton to LayoutRevisionIdComparator and apply**
- **LPD-28821 Add singleton to LayoutRevisionModifiedDateComparator and apply**
- **LPD-28821 Add singleton to LayoutSetBranchCreateDateComparator and apply**
- **LPD-28821 Add singleton to LayoutSetPrototypeCreateDateComparator and apply**
- **LPD-28821 Semver**

[LPD-28821]: https://liferay.atlassian.net/browse/LPD-28821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by victorhcunha** [comment]
ci:test:relevant

**Comment by victorhcunha** [comment]
ci:test:stable

**Comment by Valmir-unicap** [comment]
ci:report:29081866

**Comment by Valmir-unicap** [comment]
No regression found!

**Comment by Valmir-unicap** [comment]
Reevaluating!
CC: @titokenzo

**Pull request closed without merging**
