### PR TITLE
[Method References 2] LPS-165277 DDMFormInstanceRecordWriterRegistryImpl

### PR DESCRIPTION
**Pull request by JanisZhang**
previous: https://github.com/liferay-core-infra/liferay-portal/pull/2545

Hi @tinatian @dantewang , 
I modified react logic to accept a set and verified the behavior (Before & After my change). It looks good on my side. Thanks!

### CODE REVIEW

**Comment by dantewang** [comment]
@JanisZhang Please double check the SF, thanks.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
Hi @dantewang, force-pushed. Thanks

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@JanisZhang With your change, are the types on the UI no longer in upper case?

**Comment by JanisZhang** [comment]
@dantewang Sorry, I will force-pushed, I just focus on "React" and ''set" things before...
I will change it to 
```
<ClaySelect.Option
key={fileExtension}
label={fileExtension.toUpperCase()}
value={fileExtension}
/>
```

**Comment by JanisZhang** [comment]
ci:stop

**Comment by dantewang** [comment]
@JanisZhang Thanks!

**Review by dantewang — APPROVED** [review]

**Comment by JanisZhang** [comment]
Verified ok.

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:data-engine

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by tinatian** [comment]
@JanisZhang For this https://github.com/liferay-core-infra/liferay-portal/pull/2607/commits/8086f6460a4ecd671ab9425bb509f14da478fadc,  No need to test it as it only invokes service tracker map and we have tested service tracker map. I believe we have test before as it is not using service tracker map. 

Please send this to the form team who added this at the beginning to review, after you changed it from map to set and modified the type, there is usages like "Object.keys(fileExtensions)[0]", I am not sure if this is right, not sure if the test is covered. 


Tina.

**Pull request closed without merging**
