### PR TITLE
[Move Expando]Lps 190836 10 25

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-190836

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:upgrade

**Comment by slnn** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@slnn regression found:

```
[beanshell]      [exec] > Task :dxp:apps:search-experiences:search-experiences-test:compileTestIntegrationJava FAILED
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/search-experiences/search-experiences-test/src/testIntegration/java/com/liferay/search/experiences/internal/blueprint/test/SXPBlueprintSearchResultTest.java:19: error: package com.liferay.expando.kernel.service does not exist
[beanshell]      [exec] import com.liferay.expando.kernel.service.ExpandoTableLocalService;
[beanshell]      [exec]                                          ^
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/search-experiences/search-experiences-test/src/testIntegration/java/com/liferay/search/experiences/internal/blueprint/test/SXPBlueprintSearchResultTest.java:2505: error: cannot find symbol
[beanshell]      [exec] 	private ExpandoTableLocalService _expandoTableLocalService;
[beanshell]      [exec] 	        ^
[beanshell]      [exec]   symbol:   class ExpandoTableLocalService
[beanshell]      [exec]   location: class com.liferay.search.experiences.internal.blueprint.test.SXPBlueprintSearchResultTest
[beanshell]      [exec] Note: Some input files use unchecked or unsafe operations.
[beanshell]      [exec] Note: Recompile with -Xlint:unchecked for details.
[beanshell]      [exec] 2 errors
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-32/test-portal-acceptance-pullrequest(master)/2524/modules-integration-mysql57-jdk8/4/18/jenkins-console.txt.gz?authuser=0)

```
[beanshell]      [exec] com.liferay.segments.exportimport.data.handler.test.SegmentsEntryStagedModelDataHandlerTest > testExportImportSegmentsEntryWithEntityFieldCustomField FAILED
[beanshell]      [exec]     com.thoughtworks.xstream.converters.ConversionException: 
[beanshell]      [exec]     ---- Debugging information ----
[beanshell]      [exec]     cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
[beanshell]      [exec]     cause-message       : com.liferay.expando.model.impl.ExpandoColumnImpl
[beanshell]      [exec]     class               : com.liferay.expando.exportimport.internal.model.adapter.StagedExpandoColumnImpl
[beanshell]      [exec]     required-type       : com.liferay.expando.exportimport.internal.model.adapter.StagedExpandoColumnImpl
[beanshell]      [exec]     converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
[beanshell]      [exec]     path                : /StagedExpandoColumn/_expandoColumn
[beanshell]      [exec]     line number         : 2
[beanshell]      [exec]     version             : 1.4.20
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-32/test-portal-acceptance-pullrequest(master)/2524/modules-integration-mysql57-jdk8/4/1/jenkins-console.txt.gz?authuser=0)

**Comment by vicnate5** [comment]
Closing this since it failed QA.

**Comment by slnn** [comment]
> @slnn regression found:
> 
> ```
> [beanshell]      [exec] > Task :dxp:apps:search-experiences:search-experiences-test:compileTestIntegrationJava FAILED
> [beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/search-experiences/search-experiences-test/src/testIntegration/java/com/liferay/search/experiences/internal/blueprint/test/SXPBlueprintSearchResultTest.java:19: error: package com.liferay.expando.kernel.service does not exist
> [beanshell]      [exec] import com.liferay.expando.kernel.service.ExpandoTableLocalService;
> [beanshell]      [exec]                                          ^
> [beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/search-experiences/search-experiences-test/src/testIntegration/java/com/liferay/search/experiences/internal/blueprint/test/SXPBlueprintSearchResultTest.java:2505: error: cannot find symbol
> [beanshell]      [exec] 	private ExpandoTableLocalService _expandoTableLocalService;
> [beanshell]      [exec] 	        ^
> [beanshell]      [exec]   symbol:   class ExpandoTableLocalService
> [beanshell]      [exec]   location: class com.liferay.search.experiences.internal.blueprint.test.SXPBlueprintSearchResultTest
> [beanshell]      [exec] Note: Some input files use unchecked or unsafe operations.
> [beanshell]      [exec] Note: Recompile with -Xlint:unchecked for details.
> [beanshell]      [exec] 2 errors
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-32/test-portal-acceptance-pullrequest(master)/2524/modules-integration-mysql57-jdk8/4/18/jenkins-console.txt.gz?authuser=0)
> 
> ```
> [beanshell]      [exec] com.liferay.segments.exportimport.data.handler.test.SegmentsEntryStagedModelDataHandlerTest > testExportImportSegmentsEntryWithEntityFieldCustomField FAILED
> [beanshell]      [exec]     com.thoughtworks.xstream.converters.ConversionException: 
> [beanshell]      [exec]     ---- Debugging information ----
> [beanshell]      [exec]     cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
> [beanshell]      [exec]     cause-message       : com.liferay.expando.model.impl.ExpandoColumnImpl
> [beanshell]      [exec]     class               : com.liferay.expando.exportimport.internal.model.adapter.StagedExpandoColumnImpl
> [beanshell]      [exec]     required-type       : com.liferay.expando.exportimport.internal.model.adapter.StagedExpandoColumnImpl
> [beanshell]      [exec]     converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
> [beanshell]      [exec]     path                : /StagedExpandoColumn/_expandoColumn
> [beanshell]      [exec]     line number         : 2
> [beanshell]      [exec]     version             : 1.4.20
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-32/test-portal-acceptance-pullrequest(master)/2524/modules-integration-mysql57-jdk8/4/1/jenkins-console.txt.gz?authuser=0)

Thank @catarineaguiar for catching this! Fix and resend in https://github.com/liferay-core-infra/liferay-portal/pull/5992

**Pull request closed without merging**
