### PR TITLE
[Spring Beans] LPS-200453 Make PortletToolbar not a spring bean

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5967

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(11/7 9:34)

**Comment by W2jx** [comment]
no conflicts(11/8 10:05)

**Comment by W2jx** [comment]
It's just a bnd file conflict, which will be resolved when testing needs to be performed after the review is passed.

**Comment by W2jx** [comment]
no conflicts(11/15 10:19)

**Comment by W2jx** [comment]
no conflicts(11/17 8:18)

**Comment by W2jx** [comment]
no conflicts(11/20 13:57)

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
@W2jx Please rebase, thanks!

**Comment by W2jx** [comment]
Hi @dantewang , I have rebased.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/144099

cc @shuyangzhou

**Pull request closed without merging**
