### PR TITLE
LPS-173194 Remove "immediate = true" from Echo components part 5

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:help

**Comment by RenanUmV** [comment]
ci:test:echo

**Comment by RenanUmV** [comment]
@rafaprax

**Comment by RenanUmV** [comment]
ci:test:echo-upgrade

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
@RenanUmV semver error:

```
   [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/asset/asset-test-util] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.asset.test.util.asset.renderer.factory CHANGED    2.0.0      2.0.0      2.0.1      VERSION INCREASE REQUIRED
     [exec]     	~   class      com.liferay.asset.test.util.asset.renderer.factory.TestAssetRendererFactory
     [exec]     		~   annotated  org.osgi.service.component.annotations.Component
     [exec]     			-   property   immediate=true
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertFalse(Assert.java:64)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-39/test-portal-acceptance-pullrequest(master)/2385/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@RenanUmV Please fix the commit message of https://github.com/liferay-core-infra/liferay-portal/pull/3098/commits/573293e1ee04435140a3c08e4193a6c85908454d, you have a special character at the beginning which can not be read

**Comment by RenanUmV** [comment]
Sorry @tinatian

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129204

**Pull request closed without merging**
