### PR TITLE
[Move Expando part 3]Lps 190452

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-190452

### CODE REVIEW

**Comment by Kvale1733** [comment]
@slnn Regression found. Several info framework integration tests failed to run due to 
```
 [exec] > Task :apps:info:info-test:compileTestIntegrationJava
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/info/info-test/src/testIntegration/java/com/liferay/info/display/field/test/ExpandoInfoDisplayFieldProviderTest.java:25: error: package com.liferay.expando.test.util does not exist
     [exec] import com.liferay.expando.test.util.ExpandoTestUtil;
     [exec]                                     ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/info/info-test/src/testIntegration/java/com/liferay/info/display/field/test/ExpandoInfoDisplayFieldProviderTest.java:90: error: cannot find symbol
     [exec] 		ExpandoColumn expandoColumn = ExpandoTestUtil.addColumn(
     [exec] 		                              ^
     [exec]   symbol:   variable ExpandoTestUtil
     [exec]   location: class com.liferay.info.display.field.test.ExpandoInfoDisplayFieldProviderTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/info/info-test/src/testIntegration/java/com/liferay/info/display/field/test/ExpandoInfoDisplayFieldProviderTest.java:112: error: cannot find symbol
     [exec] 		ExpandoColumn expandoColumn = ExpandoTestUtil.addColumn(
     [exec] 		                              ^
     [exec]   symbol:   variable ExpandoTestUtil
     [exec]   location: class com.liferay.info.display.field.test.ExpandoInfoDisplayFieldProviderTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/info/info-test/src/testIntegration/java/com/liferay/info/display/field/test/ExpandoInfoDisplayFieldProviderTest.java:141: error: cannot find symbol
     [exec] 		ExpandoColumn expandoColumn = ExpandoTestUtil.addColumn(
     [exec] 		                              ^
     [exec]   symbol:   variable ExpandoTestUtil
     [exec]   location: class com.liferay.info.display.field.test.ExpandoInfoDisplayFieldProviderTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/info/info-test/src/testIntegration/java/com/liferay/info/display/field/test/ExpandoInfoDisplayFieldProviderTest.java:166: error: cannot find symbol
     [exec] 		ExpandoColumn expandoColumn = ExpandoTestUtil.addColumn(
     [exec] 		                              ^
     [exec]   symbol:   variable ExpandoTestUtil
     [exec]   location: class com.liferay.info.display.field.test.ExpandoInfoDisplayFieldProviderTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/info/info-test/src/testIntegration/java/com/liferay/info/display/field/test/ExpandoInfoDisplayFieldProviderTest.java:181: error: cannot find symbol
     [exec] 		ExpandoColumn expandoColumn = ExpandoTestUtil.addColumn(
     [exec] 		                              ^
     [exec]   symbol:   variable ExpandoTestUtil
     [exec]   location: class com.liferay.info.display.field.test.ExpandoInfoDisplayFieldProviderTest
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/info/info-test/src/testIntegration/java/com/liferay/info/collection/provider/test/SingleFormVariationInfoCollectionProviderTest.java uses unchecked or unsafe 
```
[Log](https://testray.liferay.com/reports/production/logs/2023-07/test-1-26/test-portal-acceptance-pullrequest(master)/10511/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
> @slnn Regression found. Several info framework integration tests failed to run due to
> 
> ```
>  [exec] > Task :apps:info:info-test:compileTestIntegrationJava
>      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/info/info-test/src/testIntegration/java/com/liferay/info/display/field/test/ExpandoInfoDisplayFieldProviderTest.java:25: error: package com.liferay.expando.test.util does not exist
>      [exec] import com.liferay.expando.test.util.ExpandoTestUtil;
>      [exec]                                     ^
>      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/info/info-test/src/testIntegration/java/com/liferay/info/display/field/test/ExpandoInfoDisplayFieldProviderTest.java:90: error: cannot find symbol
>      [exec] 		ExpandoColumn expandoColumn = ExpandoTestUtil.addColumn(
>      [exec] 		                              ^
>      [exec]   symbol:   variable ExpandoTestUtil
>      [exec]   location: class com.liferay.info.display.field.test.ExpandoInfoDisplayFieldProviderTest
>      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/info/info-test/src/testIntegration/java/com/liferay/info/display/field/test/ExpandoInfoDisplayFieldProviderTest.java:112: error: cannot find symbol
>      [exec] 		ExpandoColumn expandoColumn = ExpandoTestUtil.addColumn(
>      [exec] 		                              ^
>      [exec]   symbol:   variable ExpandoTestUtil
>      [exec]   location: class com.liferay.info.display.field.test.ExpandoInfoDisplayFieldProviderTest
>      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/info/info-test/src/testIntegration/java/com/liferay/info/display/field/test/ExpandoInfoDisplayFieldProviderTest.java:141: error: cannot find symbol
>      [exec] 		ExpandoColumn expandoColumn = ExpandoTestUtil.addColumn(
>      [exec] 		                              ^
>      [exec]   symbol:   variable ExpandoTestUtil
>      [exec]   location: class com.liferay.info.display.field.test.ExpandoInfoDisplayFieldProviderTest
>      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/info/info-test/src/testIntegration/java/com/liferay/info/display/field/test/ExpandoInfoDisplayFieldProviderTest.java:166: error: cannot find symbol
>      [exec] 		ExpandoColumn expandoColumn = ExpandoTestUtil.addColumn(
>      [exec] 		                              ^
>      [exec]   symbol:   variable ExpandoTestUtil
>      [exec]   location: class com.liferay.info.display.field.test.ExpandoInfoDisplayFieldProviderTest
>      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/info/info-test/src/testIntegration/java/com/liferay/info/display/field/test/ExpandoInfoDisplayFieldProviderTest.java:181: error: cannot find symbol
>      [exec] 		ExpandoColumn expandoColumn = ExpandoTestUtil.addColumn(
>      [exec] 		                              ^
>      [exec]   symbol:   variable ExpandoTestUtil
>      [exec]   location: class com.liferay.info.display.field.test.ExpandoInfoDisplayFieldProviderTest
>      [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/info/info-test/src/testIntegration/java/com/liferay/info/collection/provider/test/SingleFormVariationInfoCollectionProviderTest.java uses unchecked or unsafe 
> ```
> 
> [Log](https://testray.liferay.com/reports/production/logs/2023-07/test-1-26/test-portal-acceptance-pullrequest(master)/10511/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

Thank @Kvale1733 for catching this! Fix and retrigger the tests.

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by tinatian** [comment]
ci:forward:force

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137957

**Pull request closed without merging**
