### PR TITLE
[Rename Classes] LPS-167094 in module layout,wiki,sharing, users-admin

### PR DESCRIPTION
**Pull request by JanisZhang**
This PR is to rename classes in the module  `layout`,`wiki`, `sharing`, `users-admin`. Thanks!

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:usm

**Comment by Kvale1733** [comment]
ci:test:sharing

**Comment by Kvale1733** [comment]
ci:test:wiki

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
@JanisZhang 
Semver error:
```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/wiki/wiki-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.wiki.constants                         MAJOR      2.1.0      2.1.0      3.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.wiki.constants.WikiWebKeys
     [exec]     		+   field      WIKI_IMPORTER_REGISTRY
     [exec]     			+   access     final
     [exec]     			+   access     static
     [exec]     			+   constant   WIKI_IMPORTER_REGISTRY
     [exec]     			+   return     java.lang.String
     [exec]     		-   field      WIKI_IMPORTER_TRACKER
     [exec]     			-   access     final
     [exec]     			-   access     static
     [exec]     			-   constant   WIKI_IMPORTER_TRACKER
     [exec]     			-   return     java.lang.String
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 10.0.0
```
[Log](https://testray.liferay.com/reports/production/logs/2022-11/test-1-27/test-portal-acceptance-pullrequest(master)/5702/modules-semantic-versioning-jdk8/0/7/jenkins-console.txt.gz?authuser=0)

No regressions found in other tests.

**Pull request closed without merging**
