### PR TITLE
Lps 154855 remove properties: module.framework.resolver.revision.batch.size

### PR DESCRIPTION
**Pull request by W2jx**
@tinatian @dantewang, I have added the reason why I removed this property in the commit message.

### CODE REVIEW

**Comment by W2jx** [comment]
The startup testing results are here https://github.com/liferay-core-infra/liferay-portal/pull/852

**Comment by dantewang** [comment]
@W2jx Because of the limitation of some Git apps, sometimes it's hard to see the whole commit message when you write more things in a new line. Even Github hides the content in new lines in the notification email. So I think it's best to edit your message and just remove the new lines -- just write everything in one line.

**Comment by dantewang** [comment]
@W2jx Code conflict, please update

**Comment by W2jx** [comment]
Hi @dantewang,  I have update codes and commit message.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 Could you please review the test results once they finish? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@W2jx Code looks good to me, please rebase.

Tina.

**Comment by W2jx** [comment]
Hi @tinatian ,  I have updated the codes

**Comment by W2jx** [comment]
Hi @tinatian , I have updated the codes.

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
@W2jx Please remember to keep an eye on your pull, please rebase.

Tina

**Comment by W2jx** [comment]
Sorry @tinatian . I will always keep an eye on my pr. And I have updated the codes.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/119222

**Pull request closed without merging**
