### PR TITLE
LPS-170846 use_compileOnly_for_commons-codec and commons-digester

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

In this PR, I am trying to

use compileOnly for commons-codec
export commons-digester in shared-dependencies-commons, and change to use compileOnly for its usage.
Thanks for checking!

### CODE REVIEW

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by jeffwu0724** [comment]
fixed the code conflcits in build.gradles, gonna retrigger the test

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions.

**Comment by jeffwu0724** [comment]
fixed the code conflict in lib/versions-complete.xml by auto generate, the previous test should be good.

**Comment by tinatian** [comment]
@jeffwu0724 Please see https://github.com/brianchandotcom/liferay-portal/pull/129121

**Pull request closed without merging**
