### PR TITLE
LPS-177226 Remove leftovers "immediate = true" from Antivirus Async Store

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-177226

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:stable

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133116

**Pull request closed without merging**
