### PR TITLE
LPD-39325 Fix flaky LDAP functional test

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__ <https://liferay.atlassian.net/browse/LPD-39325>

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:50348832

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 50348832.
> 
> Job Link: [generate-testray-csv](https://test-1-27.liferay.com/job/generate-testray-csv/281/)
> 
> Testray CSV Link: [testray-results-50348832.csv](https://test-1-27.liferay.com/userContent/jobs/generate-testray-csv/builds/281/testray-results-50348832.csv)

No unique failures in report

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
