### PR TITLE
[Remove unuse references]Lps 163778

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-163778

### CODE REVIEW

**Comment by vicnate5** [comment]
@slnn Compile error here
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/marketplace/marketplace-store-web/src/main/java/com/liferay/marketplace/store/web/internal/portlet/MarketplaceStorePortlet.java:158: error: cannot find symbol
     [exec]         PortalUtil.getLiferayPortletResponse(actionResponse)
     [exec]         ^
     [exec]   symbol:   variable PortalUtil
     [exec]   location: class com.liferay.marketplace.store.web.internal.portlet.MarketplaceStorePortlet
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/marketplace/marketplace-store-web/src/main/java/com/liferay/marketplace/store/web/internal/portlet/MarketplaceStorePortlet.java uses or overrides a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] 1 error
```
     
Full log https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/5736/consoleText

**Comment by slnn** [comment]
Thank @vicnate5  for catching this!

I updated and forced pushed to this pull.

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
I am going to check marketplace on this, removed QA label for now.

**Comment by vicnate5** [comment]
Additional testing at https://github.com/vicnate5/liferay-portal/pull/2177

**Comment by vicnate5** [comment]
Additional testing for Marketplace passed.

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
ci:forward

FYI @shuyangzhou

**Comment by dantewang** [comment]
@slnn Please fix SF.

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
Just rerun SF test  since forced push to fix the SF issue no logic changes,

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126145

**Pull request closed without merging**
