### PR TITLE
Lps 154557 fix 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by shuyangzhou** [comment]
@vicnate5 please help me check the results, thanks!

**Comment by vicnate5** [comment]
@shuyangzhou No regressions found. Just needs semver update
```
  PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
= ================================================== ========== ========== ========== ========== ==========
* com.liferay.portal.util                            MINOR      33.2.0     33.2.0     33.3.0     VERSION INCREASE REQUIRED
	<   class      com.liferay.portal.util.PropsValues
		+   field      TUNNEL_SERVLET_HIDE_EXCEPTION_DATA
			+   access     final
			+   access     static
			+   return     boolean
[Baseline Warning] Bundle Version Change Recommended: 47.3.0
```

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121080

**Pull request closed without merging**
