### PR TITLE
[OrderByComparator] LPD-26689 Clean up and Apply Singleton in module microblogs

### PR DESCRIPTION
**Pull request by rubenssoares-br**
Ticket: https://liferay.atlassian.net/browse/LPD-26689

### CODE REVIEW

**Comment by rubenssoares-br** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:report:2571640244

**Comment by MrJohn1911** [comment]
ci:test:content-management

**Comment by rubenssoares-br** [comment]
ci:report:2571687499

**Comment by rubenssoares-br** [comment]
ci:test:content-management

**Comment by rubenssoares-br** [comment]
ci:report:2571774333

**Comment by rubenssoares-br** [comment]
ci:test:relevant

**Comment by rubenssoares-br** [comment]
ci:test:content-management

**Comment by rubenssoares-br** [comment]
ci:stop

**Comment by rubenssoares-br** [comment]
ci:test:sf

**Comment by rubenssoares-br** [comment]
ci:test:relevant

**Comment by rubenssoares-br** [comment]
ci:test:content-management

**Comment by rubenssoares-br** [comment]
ci:report:2571899330

**Comment by rubenssoares-br** [comment]
FYI: `java.lang.Exception:  ## ## 1 Liferay Exception was thrown ##  LIFERAY_ERROR: Ignoring new configuration pid=com.liferay.portal.security.antisamy.configuration.AntiSamyClassNameConfiguration~blogs`
this error above happens in other builds, it is not a single failure, as show: [testray-results-2571899330.csv](https://test-1-40.liferay.com/userContent/jobs/generate-testray-csv/builds/238/testray-results-2571899330.csv)

**Comment by rubenssoares-br** [comment]
ci:test:sf

**Comment by rubenssoares-br** [comment]
ci:test:relevant

**Comment by rubenssoares-br** [comment]
ci:test:content-management

**Comment by Valmir-unicap** [comment]
ci:report:8179198

**Comment by Valmir-unicap** [comment]
Reevaluating!
CC: @titokenzo

**Pull request closed without merging**
