### PR TITLE
[Remove Blocking usages]LPS-193288  Clean up the usage of ConfigurationProviderUtil in portal-kernel | Part 1

### PR DESCRIPTION
**Pull request by W2jx**
Hi @dantewang , since too many classes were modified in the last [pr](https://github.com/liferay-core-infra/liferay-portal/pull/5233), involving a lot of test classes, it was impossible to clearly review and fix issues, so I divided it into three subtasks, this is the first [one](https://liferay.atlassian.net/browse/LPS-193288), mainly cleaning up the usage of ConfigurationProviderUtil in portal-kernel.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5233

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by W2jx** [comment]
no conflicts(8/14 8:40)

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Pull request closed without merging**
