### PR TITLE
[Static reference] LPS-182671 Remove method reference by using snapshot in module commerce-product-type-virtual-order-content-web

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(5/2 10:54)

**Comment by tinatian** [comment]
ci:forward

**Comment by W2jx** [comment]
ci:forward

**Pull request closed without merging**
