### PR TITLE
LPD-33381 fix not using nodePort 9080 in logoutPG

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This is to fix nodePort 9080 is not use in logoutPG. It is becuase nodePort is never been used within logoutPG, and it will call Navigator.openURL(), and logout in JSONCompany.getPortalURL() eventually, which is http://localhost:8080/ by default

Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:clustering

**Comment by jeffwu0724** [comment]
ci:test:analytics-cloud-acceptance

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:acceptance-functional

**Comment by jeffwu0724** [comment]
ci:report:55920869

**Comment by jeffwu0724** [comment]
ci:report:55927839

**Comment by jeffwu0724** [comment]
[clustering test:](https://github.com/liferay-core-infra/liferay-portal/pull/7327#issuecomment-2276059865)
No unique regression found

[acceptance-functional test: ](https://github.com/liferay-core-infra/liferay-portal/pull/7327#issuecomment-2274813037)

https://testray.liferay.com/#/project/34754/routines/34756/build/56012224/case-result/56012836/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/56012224/case-result/56013424/history -- flaky, passed locally
https://testray.liferay.com/#/project/34754/routines/34756/build/56012224/case-result/56013902/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/56012224/case-result/56015942/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/56012224/case-result/56016042/history -- flaky, passed locally
https://testray.liferay.com/#/project/34754/routines/34756/build/56012224/case-result/56016122/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/56012224/case-result/56016126/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/56012224/case-result/56016134/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/56012224/case-result/56016194/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/56012224/case-result/56016202/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/56012224/case-result/56016758/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/56012224/case-result/56017162/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/56012224/case-result/56017166/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/56012224/case-result/56018042/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/56012224/case-result/56018623/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/56012224/case-result/56018719/history -- flaky, passed locally
https://testray.liferay.com/#/project/34754/routines/34756/build/56012224/case-result/56020671/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/56012224/case-result/56023087/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/56012224/case-result/56026713/history -- flaky, passed locally

**Comment by jeffwu0724** [comment]
forced push to only contains the changes in clustering.testcase

**Comment by jeffwu0724** [comment]
ci:test:clustering

**Comment by jeffwu0724** [comment]
ci:test:analytics-cloud-acceptance

**Comment by jeffwu0724** [comment]
ci:test:acceptance-functional

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:report:58103997

**Comment by jeffwu0724** [comment]
ci:report:57993638

**Comment by jeffwu0724** [comment]
[clustering](https://github.com/liferay-core-infra/liferay-portal/pull/7327#issuecomment-2284291389)
No unique regression found

[acceptance-functional](https://github.com/liferay-core-infra/liferay-portal/pull/7327#issuecomment-2284319467)
https://testray.liferay.com/#/project/34754/routines/34756/build/58103997/case-result/58126373/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/58103997/case-result/58127909/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/58103997/case-result/58127953/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/58103997/case-result/58128181/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/58103997/case-result/58129721/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/58103997/case-result/58129725/history -- passed locally
https://testray.liferay.com/#/project/34754/routines/34756/build/58103997/case-result/58132490/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/58103997/case-result/58132914/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/58103997/case-result/58133358/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/58103997/case-result/58134698/history -- passed locally
https://testray.liferay.com/#/project/34754/routines/34756/build/58103997/case-result/58135286/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/58103997/case-result/58135362/history
https://testray.liferay.com/#/project/34754/routines/34756/build/58103997/case-result/58137014/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/58103997/case-result/58137952/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/58103997/case-result/58138724/history -- passed locally
https://testray.liferay.com/#/project/34754/routines/34756/build/58103997/case-result/58138764/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/58103997/case-result/58138768/history -- not unique
https://testray.liferay.com/#/project/34754/routines/34756/build/58103997/case-result/58139492/history -- not unique

no unique regression found

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
