### PR TITLE
LPS-122481

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, I run ci test from https://github.com/yuhai/liferay-portal/pull/328. It passed from the latest twice tests. On that test pr, it will only run upgrade tests. Before the fix, basically, the error can happen once at least from every ci test.

cc @shuyangzhou

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
@zhangyan0701 According to comments in the ticket, it seems some checks are disabled for these errors; please make sure that no such errors happen on CI.

**Comment by zhangyan0701** [comment]
Hi @yuhai 

The errors in this ticket are temporarily ignored on CI. I removed the entries from test-ignorable-error-lines.xml here: https://github.com/yuhai/liferay-portal/pull/329. Could you cherry-pick my commit and re-run the upgrade tests?

**Comment by yuhai** [comment]
@dantewang, I just push force some commits about reverting ignore test errors. I didn't change the fix.

@zhangyan0701, you may firstly check the previous test results. I will trigger the ci test again. Please help check if my revert commits are completely.

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:upgrade

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@susanchen3 can you check the for the error here?

**Comment by susanchen3** [comment]
Errors are no longer present with the fix. The revert commits also look complete. :tada:

**Comment by catarineaguiar** [comment]
thanks @susanchen3!!

no regressions were found

**Comment by vicnate5** [comment]
Please include the revert when sending. Thanks all!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142881

**Pull request closed without merging**
