### PR TITLE
LPS-143632 Remove LanguageUtil usages from product and segment modules

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:acceptance

**Comment by tinatian** [comment]
@julschong Code looks good to me, wait for QA to scan test results.
@catarineaguiar Please help me to scan test results.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by julschong** [comment]
@tinatian 
Hi Tina,
Could you please help me review this pull?
Thank you!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci;forward

**Comment by julschong** [comment]
ci:forward

**Pull request closed without merging**
