### PR TITLE
LPS-152875

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-152875

/cc @javalosjr96

### CODE REVIEW

**Comment by tinatian** [comment]
@mbowerman Please modify "source.check.GradleDependencyArtifactsCheck.enforceVersionArtifacts" in source-format.properties to enforce the version used, then do SF and it will cover all the usages.

Thanks.
Tina.

**Comment by mbowerman** [comment]
@javalosjr96 Could you please make [the changes requested by Tina above](https://github.com/liferay-core-infra/liferay-portal/pull/726#issuecomment-1119869128), and push the updated branch to your origin?

**Comment by javalosjr96** [comment]
@mbowerman @tinatian Updated

**Comment by javalosjr96** [comment]
@tinatian 
Hi Tina,

Is there anything else that needs to be done?

**Comment by javalosjr96** [comment]
@tinatian 
Hi Tina,

Is there anything else that needs to be done?

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina.

**Comment by catarineaguiar** [comment]
Hi @javalosjr96 @mbowerman some tests failed only in this PR but I don't think is related to your changes.
You can run locally to reproduce - `JSONFactoryTest` unit test and `RegionResourceTest` integration test.

```
> Task :apps:headless:headless-admin-address:headless-admin-address-test:compileTestIntegrationJava FAILED
/home/me/dev/projects/liferay-portal/modules/apps/headless/headless-admin-address/headless-admin-address-test/src/testIntegration/java/com/liferay/headless/admin/address/resource/v1_0/test/RegionResourceTest.java:24: error: cannot find symbol
import com.liferay.portal.kernel.exception.DuplicateRegionException;
                                          ^
  symbol:   class DuplicateRegionException
  location: package com.liferay.portal.kernel.exception
/home/me/dev/projects/liferay-portal/modules/apps/headless/headless-admin-address/headless-admin-address-test/src/testIntegration/java/com/liferay/headless/admin/address/resource/v1_0/test/RegionResourceTest.java:161: error: cannot find symbol
		_testPostRegionProblem(region, DuplicateRegionException.class);
		                               ^
  symbol:   class DuplicateRegionException
  location: class RegionResourceTest
```

```
build-common-java.compile:
    [javac] Compiling 34 source files to /home/me/dev/projects/liferay-portal/portal-impl/classes
    [javac] /home/me/dev/projects/liferay-portal/portal-impl/src/com/liferay/portal/service/impl/RegionLocalServiceImpl.java:25: error: cannot find symbol
    [javac] import com.liferay.portal.kernel.exception.DuplicateRegionException;
    [javac]                                           ^
    [javac]   symbol:   class DuplicateRegionException
    [javac]   location: package com.liferay.portal.kernel.exception
    [javac] 1 error
```

**Comment by javalosjr96** [comment]
@catarineaguiar 
That test seems to be new as it is not included in the master I used in this PR.  I'll need to rebase.

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
Latest Master with LPS-152875
JSONFactoryTest:
https://gist.github.com/javalosjr96/ef8c5e20a216e0a5a5ced08b858fe43f
RegionResourceTest:
https://gist.github.com/javalosjr96/7d4b7063687b4f9d7410a8e50489c68f

**Comment by tinatian** [comment]
@mbowerman @javalosjr96 I am going to close this pull as it did not pass ci tests, please resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
