### PR TITLE
LPS-172511 Remove "immediate = true" from remaining Forms modules

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:forms

**Comment by Kvale1733** [comment]
@daiazius No regressions found.

**Comment by daiazius** [comment]
Hey @tinatian, this PR is good to go

**Comment by tinatian** [comment]
@daiazius I do not think you can do this, who is going to trigger the activation of this? 

@vicnate5 I believe the test triggered did not cover this change, could you please take a look?

Thanks.
Tina

**Comment by daiazius** [comment]
Hi @tinatian, I reopened this PR to add the empty service in the component so this file follow the pattern of the other ServletContextUtil classes. Like in this [commit](https://github.com/liferay-core-infra/liferay-portal/pull/3048/commits/2c9f4ba22e5497145d6bdcd5e1ff94de52fe43b4)

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@daiazius Please remember to retrigger the tests when you made changes to your original pull.

Thanks.
Tina

**Comment by xbrianlee** [comment]
Hey @vicnate5, sorry the many DDL Forms tests are affecting your team. We likely don't have to run that many tests in relevant.

We're in the middle of switching the BPM team over from using relevant for test analysis to using test suites. Once this is complete (within 2 weeks or so), we'll review which tests we run on relevant. You can track [LPS-173736](https://issues.liferay.com/browse/LPS-173736).

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129313

**Pull request closed without merging**
