### PR TITLE
[SampleSQLBuilder-homepage-fix]Lpd 27255

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPD-27255

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Is it possible to split this PR down to smaller ones? By the way, this PR updates a lot of fragment code as well as segment code, is the segment part really necessary? Isn't it a feature needed to be opt-in?

**Comment by slnn** [comment]
Hi @dantewang 

For the segment part, it has been applied in two places, one is in the segments.ftl  which is a feature that needs to be opt-in,  another is for the home page in groups.ftl, it is necessary for the home page, otherwise, NPE will appear on portal side which is thrown by `LayoutPageTemplateStructureImpl.getData` when editing the home page
segmentsExperience-null,

I will try to split this pull into smaller ones and resend.

Lily

**Comment by dantewang** [comment]
I meant portal side "opt-in". I thought that Segments is a feature that needs to be opt-in by portal admin. But now it seems that a default segment experience must exist for a layout?

**Comment by slnn** [comment]
Yes, now a default segment experience must exist for the layout of home page

**Comment by slnn** [comment]
Part1 please see https://github.com/liferay-core-infra/liferay-portal/pull/7105

**Pull request closed without merging**
