### PR TITLE
LPS-186788 Remove multiple configurations in LiferayOAuthDataProvider

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:oauth2

**Comment by catarineaguiar** [comment]
@julschong regression found:

```
     [exec] com.liferay.oauth2.provider.token.endpoint.test.IssueJWTAccessTokenTest > testIssuedJWTAccessToken FAILED
     [exec]     java.lang.AssertionError
     [exec]     	at org.junit.Assert.fail(Assert.java:87)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:53)
     [exec]     	at com.liferay.oauth2.provider.token.endpoint.test.IssueJWTAccessTokenTest._verifyJWTAccessToken(IssueJWTAccessTokenTest.java:67)
     [exec]     	at com.liferay.oauth2.provider.token.endpoint.test.IssueJWTAccessTokenTest.testIssuedJWTAccessToken(IssueJWTAccessTokenTest.java:44)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-06/test-1-30/test-portal-acceptance-pullrequest(master)/6789/modules-integration-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
@catarineaguiar Hi Catarine,
could you please help me check locally? I tried running and it seem to be passed.

**Comment by Kvale1733** [comment]
@julschong I can't reproduce it locally either but it appeared for both relevant and oauth test suite so it did seem like a regression. Gonna rerun OAuth suite just to make sure.

**Comment by Kvale1733** [comment]
@julschong Yup I was able to reproduce that regression with the steps from https://liferay.atlassian.net/wiki/spaces/~85516578/pages/2369454549/Integration+Tests

Using this this group in file in portal sourece(remove .txt):[test.class.file.names.properties.txt](https://github.com/liferay-core-infra/liferay-portal/files/11737125/test.class.file.names.properties.txt)

And running "gw testIntegration -Dbuild.exclude.ant.plugin=true -Dtest.class.group.index=0" in /modules

**Comment by Kvale1733** [comment]
ci:stop

**Comment by julschong** [comment]
need to fix integration test

**Pull request closed without merging**
