### PR TITLE
LPS-170267 Remove "immediate = true" from Portal III

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@MrJohn1911 regressions found:

```
     [exec] com.liferay.portal.upgrade.test.UpgradeReportLogAppenderTest > testInfoEventsInOrder FAILED
     [exec]     java.lang.AssertionError
     [exec]     	at org.junit.Assert.fail(Assert.java:87)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:53)
     [exec]     	at com.liferay.portal.upgrade.test.UpgradeReportLogAppenderTest.testInfoEventsInOrder(UpgradeReportLogAppenderTest.java:207)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-27/test-portal-acceptance-pullrequest(master)/6080/modules-integration-mysql57-jdk8/0/11/jenkins-console.txt.gz?authuser=0)
test report [here](https://testray.liferay.com/home/-/testray/case_results/2102746215)

and this error happens when we try to run upgrades tests:

```
 [parallel] 2022-12-05 17:32:22.437 WARN  [main][MainServlet:410] Required upgrades in modules are pending. Run the upgrade process or type upgrade:checkAll in the Gogo shell to get more information.
     [echo] Waiting for http://localhost:8080/web/guest to load
  [waitfor] 2022-12-05 17:32:30.483 ERROR [http-nio-8080-exec-1][IncludeTag:128] Current URL /web/guest generates exception: java.lang.NullPointerException
  [waitfor] java.lang.NullPointerException: null
  [waitfor] 	at org.apache.jsp.html.common.themes.top_005fhead_jsp._jspService(top_005fhead_jsp.java:1166) ~[?:?]
  [waitfor] 	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:9.0.68]
  [waitfor] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[servlet-api.jar:4.0.FR]
  [waitfor] 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466) ~[jasper.jar:9.0.68]
  [waitfor] 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379) ~[jasper.jar:9.0.68]
  [waitfor] 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327) ~[jasper.jar:9.0.68]
  [waitfor] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[servlet-api.jar:4.0.FR]
  [waitfor] 	at com.liferay.shielded.container.internal.proxy.ServletWrapper.service(ServletWrapper.java:113) ~[com.liferay.shielded.container.impl.jar:?]
  [waitfor] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[catalina.jar:9.0.68]
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-12/test-1-27/test-portal-acceptance-pullrequest(master)/6080/functional-upgrade-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)
test report [here](https://testray.liferay.com/home/-/testray/case_results/2102745533)

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
@MrJohn1911 no regressions found.

**Comment by MrJohn1911** [comment]
Hey @shuyangzhou, this one is ready to go!

**Comment by tinatian** [comment]
@MrJohn1911 Please do not do this https://github.com/liferay-core-infra/liferay-portal/pull/2627/commits/fc41c234cfe9fb866738105331a0cdefc7a27508. We do not want to add more dependencies to dependency manager

**Pull request closed without merging**
