### PR TITLE
[Component with its own class name as service type] LPS-197822 Refactor OSGiCommands components

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-197822

This pull doesn't contains the VerifyProcessTrackerOSGiCommands component due to this [commit](https://github.com/liferay-core-infra/liferay-portal/commit/13e79836b4fda68788de71ee046f7b988c9d8546#diff-58345c438cc59e18dba5c69a9f31e7e2ff0c549c5a6bc1986af38008b729399bL218)

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
Last push fixes conflict with build.gradle file.

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@MrJohn1911 sf and semver failures:

```
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: /opt/dev/projects/github/liferay-portal/modules/apps/address/address-impl/build.gradle expected:<...oject(":apps:static:[osgi:osgi-util")
     [java]   compileOnly project(":apps:static:portal:portal-upgrade-api")
     [java]   compileOnly project(":core:petra:petra-function]")
     [java]   compileOnly proj...> but was:<...oject(":apps:static:[portal:portal-upgrade-api")
     [java]   compileOnly project(":core:petra:petra-function")
     [java]   compileOnly project(":apps:static:osgi:osgi-util]")
     [java]   compileOnly proj...>
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:457)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:290)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-21/test-portal-source-format/7291/source-format-current-branch-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
Last push only fixes SF problems

**Review by rafaprax — APPROVED** [review]

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142331

**Pull request closed without merging**
