### PR TITLE
LPS-143629

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina, Shuyang,

This is to remove ImageToolUtil and UnicodeLanguageUtil
Main Task: https://issues.liferay.com/browse/LPS-143403
Sub Task 3: https://issues.liferay.com/browse/LPS-143629

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@julschong This looks good so far, but I want to run all the document tickets because of the change here. Will look at the results when they come in.

ci:test:document

**Comment by vicnate5** [comment]
ci:test:document

**Comment by vicnate5** [comment]
@julschong No regressions found.

**Comment by julschong** [comment]
@tinatian @shuyangzhou
Hi Tina, Shuyang,
Could you please help review to see if this PR is ready to go?
Thank you!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113132

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
