### PR TITLE
[Jasper] LPD-36036 Use Tomcat Jasper in Runtime | 11-8

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:app-servers

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:frontend

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:report:63376062

**Comment by dantewang** [comment]
ci:report:63376628

**Comment by dantewang** [comment]
No unique failure in app-servers.

In core-functional, I tend to think no regression.
- LocalFile.BundleBlacklist#BlacklistModuleBundleSymbolicName timed out in refreshing the page, but the page screenshot looks normal;
- Other failures marked unique also appeared in many other PRs and upstream runs.
- LocalFile.CPCustomfields#EditRevertCustomFieldWikiPage passed.

**Comment by dantewang** [comment]
@victorhcunha @JerryAdrianoo Please do performance check on this PR. No need to continue with yesterday's PR if you haven't finished it.

**Comment by JerryAdrianoo** [comment]
Hi @dantewang, I put the results in this [Spreadsheet](https://docs.google.com/spreadsheets/d/1-3csjEj3-u8oMDKU3LSJ8KfRv9SrMSitV0Fbc7MGNSY/edit?gid=2114828447#gid=2114828447)

No regression or increase occurred with this PR or the previous one.

**Comment by victorhcunha** [comment]
Hi @dantewang !
Here are the partial results from the runtime testing:

Login


Portal Version | HASH | Session Count | Percentage Change (%) | Meantime of Login
-- | -- | -- | -- | --
Master Baseline | afe71794 | 14,066 | - | 298
PR | - | 14,266 | 1.42% | 287

WC
Portal Version | HASH | Session Count | Percentage Change (%) | Meantime of Login
-- | -- | -- | -- | --
Master Baseline | afe71794 | 18,028 | - | 489
PR | - | 18,004 | -0.13% | 486




More details you can see [here](https://docs.google.com/spreadsheets/d/1-3csjEj3-u8oMDKU3LSJ8KfRv9SrMSitV0Fbc7MGNSY/edit?gid=230253805#gid=230253805)
There appear to be no regressions at this moment. The Document Library and Asset Publisher tests will still run.

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 63505952.
> 
> Job Link: [generate-testray-csv](https://test-1-37.liferay.com/job/generate-testray-csv/454/)
> 
> Testray CSV Link: [testray-results-63505952.csv](https://test-1-37.liferay.com/userContent/jobs/generate-testray-csv/builds/454/testray-results-63505952.csv)

No unique failure in relevant.

**Comment by victorhcunha** [comment]
Hi @dantewang !
Here are the other results from the runtime testing:


Document Library

Portal Version | HASH | Session Count | Percentage Change (%) | Meantime of Login
-- | -- | -- | -- | --
Master Baseline | afe71794 | 9,243 | - | 443
PR | - | 9,485 | 2.62% | 547


Asset Publisher

Portal Version | HASH | Session Count | Percentage Change (%) | Meantime of Login
-- | -- | -- | -- | --
Master Baseline | afe71794 | 8,143 | - | 236
PR | - | 8,163 | 0.25% | 224




More details you can see [here](https://docs.google.com/spreadsheets/d/1-3csjEj3-u8oMDKU3LSJ8KfRv9SrMSitV0Fbc7MGNSY/edit?gid=230253805#gid=230253805)
It still seems that there are no regressions. I did two rounds for the DL PR test because the first result shows higher CPU usage but the final result does not show this increase.
The tests were done on the same RP version as the first ones (for login and web content)

**Comment by shuyangzhou** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7632

**Pull request closed without merging**
