### PR TITLE
LPS-148015

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

I remove deprecated for
"portal-impl/src/com/liferay/portlet/documentlibrary/service/impl" - DLApp
"portal-impl/src/com/liferay/portlet/documentlibrary/service/impl" - DLFolder
"portal-impl/src/com/liferay/portlet/documentlibrary/service/impl" - DLFileEntry
"portal-impl/src/com/liferay/portlet/documentlibrary/service/permission"
"portal-impl/src/com/liferay/portlet/documentlibrary/store"
"portal-impl/src/com/liferay/portlet/documentlibrary/util"
"portal-impl/src/com/liferay/portlet/social/service/impl/SocialActivityLocalServiceImpl.java"
Thanks for checking. Also see https://github.com/jeffwu0724/liferay-portal/pull/38

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result again, please?

Thanks
Jeff

**Comment by kyle-miho** [comment]
@jeffwu0724 com.liferay.portlet.documentlibrary.util needs to be incremented, there could be other semantic versioning errors as well hidden

**Comment by jeffwu0724** [comment]
> @jeffwu0724 com.liferay.portlet.documentlibrary.util needs to be incremented, there could be other semantic versioning errors as well hidden

Thanks Kyle for checking. I redo the semantic version, please help me scan again when it is ready. Thanks!

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@jeffwu0724 Code looks good to me, wait for QA scan.
@kyle-miho Please help me scan test results.

Thanks.
Tina.

**Comment by kyle-miho** [comment]
Failures are unrelated

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114882

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
