### PR TITLE
[Remove Blocking usages]LPS-187887 portal-kernel | JSONWebServiceActionsManagerUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(6/19 13:46)

**Comment by W2jx** [comment]
no conflicts(6/20 8:56)

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/136602

**Pull request closed without merging**
