### PR TITLE
[Convert method references]LPS-162470 Convert method references to field references in module co…

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-162470

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by slnn** [comment]
Hi @dantewang @tinatian 

For the private field **_panelAppRegistry** in **CommercePanelCategory** (the class I changed in this pull) only be used in the set method, after removing the set method to covert the method reference to a field reference, the private field does not be used in the class at all. From the git history, the set method and the private field are added when adding the class, see 
https://github.com/liferay/liferay-portal/commit/cbfb2098a46dbfac4f4f9fc0fce94d45d6d2d1f0, so I keep the private field here even no people use it in the class, in case its usage is @dantewang metioned that to make sure the component is started after another service

```@Reference(unbind = "-")
	protected void setPanelAppRegistry(PanelAppRegistry panelAppRegistry) {
		_panelAppRegistry = panelAppRegistry;
	}
```



Lily

**Comment by dantewang** [comment]
@slnn The plan is actually to go over all references not directly used with the help of SF, after we finish the converting. So please always keep these references for now.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test results when they finish? Thanks!

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
@catarineaguiar Could you take a look at the Commerce test when they finish?

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123020

**Pull request closed without merging**
