### PR TITLE
[Component with its own class name as service type] LPS-198805 Refactor Controller components part I

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-198805

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud-acceptance

**Comment by Sharryxue** [comment]
ci:test:analytics-cloud-acceptance

**Comment by zhangyan0701** [comment]
ci:test:analytics-cloud-acceptance

**Comment by catarineaguiar** [comment]
Hey @ViniLopes20, could you take a look at this pull when you have time, please?

**Comment by ViniLopes20** [comment]
Hey @MrJohn1911, I found three errors in the Faro container that must be affecting Faro from starting in the AC build. See the complete log [here](https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/7151/functional-tomcat90-mysql57-jdk8/0/2/docker-logs/faro.log).

**Error 1:**
`2023-11-06 06:28:06.224 ERROR [Portal Dependency Manager Component Executor--1][PortalInstanceLifecycleListenerManagerImpl:444] null
java.lang.Exception: java.lang.NoSuchMethodError: 'com.liferay.expando.kernel.model.ExpandoColumn com.liferay.expando.kernel.service.ExpandoColumnLocalService.fetchColumn(long, java.lang.String)'
	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl$PortalInstanceLifecycleListenerServiceTrackerCustomizer.lambda$addingService$2(PortalInstanceLifecycleListenerManagerImpl.java:438) ~[?:?]
	at com.liferay.portal.service.impl.CompanyLocalServiceImpl.forEachCompany(CompanyLocalServiceImpl.java:498) ~[portal-impl.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor281.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
	at com.sun.proxy.$Proxy86.forEachCompany(Unknown Source) ~[?:?]
	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl$PortalInstanceLifecycleListenerServiceTrackerCustomizer.addingService(PortalInstanceLifecycleListenerManagerImpl.java:420) ~[?:?]
	at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl$PortalInstanceLifecycleListenerServiceTrackerCustomizer.addingService(PortalInstanceLifecycleListenerManagerImpl.java:377) ~[?:?]
	at com.liferay.osgi.service.tracker.collections.internal.list.ServiceTrackerListImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerListImpl.java:164) ~[com.liferay.osgi.service.tracker.collections.jar:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943) ~[org.eclipse.osgi.jar:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1) ~[org.eclipse.osgi.jar:?]
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[org.eclipse.osgi.jar:?]
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) ~[org.eclipse.osgi.jar:?]`

**Error 2:**
`2023-11-06 06:28:06.317 ERROR [fileinstall-directory-watcher][DirectoryWatcher:1173] Unable to start bundle: file:/opt/liferay/osgi/modules/com.liferay.osb.faro.admin.web.jar
org.osgi.framework.BundleException: Could not resolve module: com.liferay.osb.faro.admin.web [1705]
  Unresolved requirement: Import-Package: com.liferay.frontend.taglib.clay.servlet.taglib.display.context; version="2.1.0"
	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428) ~[org.eclipse.osgi.jar:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundle(DirectoryWatcher.java:1156) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._startBundles(DirectoryWatcher.java:1189) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._startAllBundles(DirectoryWatcher.java:1130) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:1041) [bundleFile:?]
	at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:247) [bundleFile:?]`

**Error 3:**
`2023-11-06 06:28:13.185 ERROR [Portal Dependency Manager Component Executor--1][LogService:56] [Portal Dependency Manager Component Executor--1] Invocation of 'addApplication' failed.
org.apache.cxf.service.factory.ServiceConstructionException: null
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:220) ~[?:?]
	at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator._registerApplication(CXFJaxRsServiceRegistrator.java:126) ~[?:?]
	at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator._registerApplications(CXFJaxRsServiceRegistrator.java:136) ~[?:?]
	at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator._rewire(CXFJaxRsServiceRegistrator.java:188) ~[?:?]
	at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator._addApplication(CXFJaxRsServiceRegistrator.java:76) ~[?:?]
	at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator._swapClassLoader(CXFJaxRsServiceRegistrator.java:213) ~[?:?]
	at com.liferay.portal.remote.rest.extender.internal.CXFJaxRsServiceRegistrator.addApplication(CXFJaxRsServiceRegistrator.java:42) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.felix.dm.impl.InvocationUtil.invokeMethod(InvocationUtil.java:230) ~[bundleFile:?]
	at org.apache.felix.dm.impl.InvocationUtil.invokeCallbackMethod(InvocationUtil.java:181) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.invokeCallback(ComponentImpl.java:665) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ServiceDependencyImpl.invoke(ServiceDependencyImpl.java:517) ~[?:?]
	at org.apache.felix.dm.impl.ServiceDependencyImpl.invokeCallback(ServiceDependencyImpl.java:327) ~[?:?]
	at org.apache.felix.dm.impl.ComponentImpl.invokeCallback(ComponentImpl.java:1734) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.handleAdded(ComponentImpl.java:1351) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.lambda$handleEvent$6(ComponentImpl.java:565) ~[bundleFile:?]
	at org.apache.felix.dm.impl.DispatchExecutor.runTask(DispatchExecutor.java:182) ~[bundleFile:?]
	at org.apache.felix.dm.impl.DispatchExecutor.run(DispatchExecutor.java:165) ~[bundleFile:?]`

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @MrJohn1911, I'm seeing the same errors in the Faro log after this new run

**Pull request closed without merging**
