### PR TITLE
LPD-17766 Patch JBoss Weld to work with JDK21

### PR DESCRIPTION
**Pull request by dantewang**
- LPD-17718 app.server.lib.global.dir is no longer the ext folder, it is the real app server global dir. We don't deploy anything there, it should not be deleted.
- LRCI-4072 prep next
- LPD-17766 Use 1.2.4 classfilewriter, version 1.2.3 contains codes that do not work with java version 12+
- LPD-17766 Initial check-in
- LPD-17766 Patch weld-osgi-bundle version 3.0.5.Final. This version contains code in ClassFileUtils that does not work with java version 12+, so we need to provide fallback method
- LPD-17766 Apply patch
- LPD-17766 DO NO MERGE IN, FAKE GRADLE CACHE
- LPD-17766 These fields should be initialized before opening any of the service trackers.

### CODE REVIEW

**Comment by julschong** [comment]
@dantewang nice find! 
how did you know to do this?

**Comment by dantewang** [comment]
@julschong Actually I just blindly guessed :smile: I guessed it based on the fact that both the error and the initialization of the init param map field happen in `LiferayContextController#<init>` -- they should happen on the same thread, so it's very possible to be a matter of execution order.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by julschong** [comment]
@tinatian @dantewang testing this now
going to try this solution with 2 options
1. with patched weld 3.0.5 and classfilewriter 1.2.4 
2. with directly using 3.1.1.Final weld-osgi-bundle and classfilewriter 1.2.4

**Comment by julschong** [comment]
see https://github.com/liferay-core-infra/liferay-portal/pull/6666

**Pull request closed without merging**
