### PR TITLE
[Remove unused field] LPS-200305 Remove unused reference field in calsses WorkflowTaskPermissionImpl, KaleoTaskInstanceTokenFinderImpl, DBPartitionMessageBusInterceptor and MessageBusManager

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
no conflicts(11/3 9:19)

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
There is a related issue found in [MessageBusManagerTest](https://testray.liferay.com/en/home/-/testray/case_results/2451235591), refer the full [console log](https://testray.liferay.com/reports/production/logs/2023-11/test-1-26/test-portal-acceptance-pullrequest(master)/11789/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0), could you please recheck the commits @W2jx, thanks in advance. 
Hello @zhangyan0701, could you please help with adding the QA Failed label for it, thanks in advance.
```
[beanshell]      [exec] com.liferay.portal.messaging.internal.jmx.MessageBusManagerTest > testRegisterMBean STARTED
[beanshell]      [exec] 
[beanshell]      [exec] com.liferay.portal.messaging.internal.jmx.MessageBusManagerTest > testRegisterMBean FAILED
[beanshell]      [exec]     java.lang.NoSuchFieldException: No field on null with name _messageBus
[beanshell]      [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.getField(ReflectionTestUtil.java:126)
[beanshell]      [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.setFieldValue(ReflectionTestUtil.java:337)
[beanshell]      [exec]         at com.liferay.portal.messaging.internal.jmx.MessageBusManagerTest.testRegisterMBean(MessageBusManagerTest.java:40)
[beanshell]      [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by Kvale1733** [comment]
Closing as this failed QA.

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
