### PR TITLE
[Urgent][Security Bugs]LPD-25543 upgrade ion-java to 1.11.7

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This is for https://liferay.atlassian.net/browse/LPP-54019
Even though the effected version only shows 7.2 in this LPP, but I saw that we are using this vulnerable version in master, Q1, Q4, Q3 and 7.3.
Therefore, fixing this in master and then backport will be a better solution.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@jeffwu0724 Code looks good to me, please forward this once it passed ci.

**Comment by tinatian** [comment]
ci:test:help

**Comment by tinatian** [comment]
ci:test:dl-store

**Pull request closed without merging**
