### PR TITLE
[TS] LPD-23711

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__
<https://liferay.atlassian.net/browse/LPD-23711>

@tinatian, as discussed, I fixed the `filterFindBy` test methods generated by Service Builder. One thing to note is that I kept the test Service Builder entity (`FilterFindEntry`) I created from the previous pull request: <https://github.com/liferay-core-infra/liferay-portal/pull/7037>. I think we still need this test entity because the test code that would be generated for it will be valuable in exposing the bug.

Let me know if this works.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:report:2574046332

**Comment by kevhlee** [comment]
ci:report:2574046332

**Comment by kevhlee** [comment]
ci:stop

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7108

**Pull request closed without merging**
