### PR TITLE
[Optional Reference]LPS-185564 module: portal-search-tuning

### PR DESCRIPTION
**Pull request by JanisZhang**
fix test. thanks!
previous: https://github.com/liferay-core-infra/liferay-portal/pull/4614#event-9333558254
https://issues.liferay.com/browse/LPS-185564

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:search

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
