### PR TITLE
[Component with its own class name as service type] LPS-193631 Refactor ModelResourcePermission components

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-193631

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:data-engine

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
Last push fixes sf problems

**Comment by catarineaguiar** [comment]
no regressions found

**Review by rafaprax — APPROVED** [review]

**Comment by shuyangzhou** [comment]
@MrJohn1911 @rafaprax for commit like https://github.com/liferay-core-infra/liferay-portal/pull/5524/commits/a79d1ec11b0d77883c3701b849346c598224ab3a it is clearly not doing what the commit message is saying. It is not a plain rename, the DataDefinitionModelResourcePermission and DataDefinitionPermissionUtil have very different set of methods. Not saying your change is not functionally right, but I could not see how the change was mapped. You need to make this kind of change to more commits, first changing the method set in-place with explanation of what you are doing. Then the final rename should really just a rename. Please resend.

**Pull request closed without merging**
