### PR TITLE
[Circular dependency]Lps 186384 6 19

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-186384

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:stop

**Comment by zhangyan0701** [comment]
ci:test:object

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
Retrigger all the related tests since forced push

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@slnn There's a design issue in this PR. Usually when we collect services using ServiceTracker with a map/collection, we keep them in the same class. Thus the helper should have its own service tracker.

Please review your design and avoid this.

Now that the opening of the service tracker is in the dependency manager sync callback, it should be safe to move it to the helper without bringing back any race condition.

**Comment by slnn** [comment]
Resend in https://github.com/liferay-core-infra/liferay-portal/pull/4868

**Pull request closed without merging**
