### PR TITLE
[TS] LPD-32148 Fix company web id logging

### PR DESCRIPTION
**Pull request by dantewang**
https://liferay.atlassian.net/browse/LPD-32148

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:44150864

**Comment by dantewang** [comment]
Mark as QA Passed as `Log4jConfigUtilTest` passed, which is the only test case that could trigger the modified logic. All failures in the relevant run should be irrelevant, as the logic is only used by the custom Log4J appender which is not enabled by default.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7297

**Pull request closed without merging**
