### PR TITLE
[BLOCKER][TS] LPS-201987

### PR DESCRIPTION
**Pull request by ChrisKian**
LXC issue, please prioritize.

https://liferay.atlassian.net/browse/LPS-198978

Please let me know if you have any questions, thanks!

CC @MrJohn1911, @stian-sigvartsen

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by brunofalc** [comment]
Hey @tinatian could you prioritize this one?

**Comment by Kvale1733** [comment]
No regressions found. Testing passed following ticket steps.

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
@kevhlee I remember we have an SF rule to avoid adding configuration pid which is not used in code base, here in this pull, the configuration pid is not used but SF passed, could you please take a look at it?

Thanks.
Tina

**Comment by kevhlee** [comment]
Sure, I will check that SF rule.

**Pull request closed without merging**
