### PR TITLE
[SF] LPS-202473 Update UnusedVariableCheck catch unused variables only referenced in constructors

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__ <https://liferay.atlassian.net/browse/LPS-202473>

This PR updates `UnusedVariableCheck` to catch unused variables that are only assigned and used in the constructors. However, it will only report unused variables if they can be removed safely without changing the constructor(s). This is to avoid breaking current usages.

Also, I have updated the check so that it ignores unused variable declarations if they or their respective classes have a `@SuppressWarnings("UnusedDeclaration")` annotation. Additionally, this PR makes it so that the check allows unused variables of a certain type, regardless of whether they are annotated or not. This PR adds `ServiceTrackerMap` to the list of allowed unused variable types.

### CODE REVIEW

**Comment by kevhlee** [comment]
cc: @shuyangzhou

**Comment by kevhlee** [comment]
@ling-alan-huang, I am making some changes to `UnusedVariableCheck.java`. Let me know if the changes to the Java check is okay.

**Comment by kevhlee** [comment]
Hi @ling-alan-huang, will do. Also, my plan was to apply this to the 7.x branches as well (this change should be applicable for the branches).

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@kevhlee regression found:

```
[beanshell]      [exec] com.liferay.source.formatter.processor.JavaSourceProcessorTest > testUnusedParameter FAILED
[beanshell]      [exec]     java.lang.AssertionError: [Parameter 'color' is unused: /tmp/aeb62q0V/com/liferay/source/formatter/dependencies/UnusedParameter.java 17 (Checkstyle:UnusedParameterCheck), Value of variable '_volume' is unused: /tmp/aeb62q0V/com/liferay/source/formatter/dependencies/UnusedParameter.java 21 (Checkstyle:UnusedVariableCheck)] expected:<1> but was:<2>
[beanshell]      [exec]         at org.junit.Assert.fail(Assert.java:89)
[beanshell]      [exec]         at org.junit.Assert.failNotEquals(Assert.java:835)
[beanshell]      [exec]         at org.junit.Assert.assertEquals(Assert.java:647)
```
```
[beanshell]      [exec] com.liferay.source.formatter.processor.JavaSourceProcessorTest > testUsePassedInVariable FAILED
[beanshell]      [exec]     java.lang.AssertionError: [Value of variable '_testB' is unused: /tmp/aeb62q0V/com/liferay/source/formatter/dependencies/UsePassedInVariable.java 26 (Checkstyle:UnusedVariableCheck), Value of variable '_testBytes' is unused: /tmp/aeb62q0V/com/liferay/source/formatter/dependencies/UsePassedInVariable.java 27 (Checkstyle:UnusedVariableCheck)] expected:<0> but was:<2>
[beanshell]      [exec]         at org.junit.Assert.fail(Assert.java:89)
[beanshell]      [exec]         at org.junit.Assert.failNotEquals(Assert.java:835)
```
```
[beanshell]      [exec] com.liferay.source.formatter.processor.JavaSourceProcessorTest > testConstructorParameterOrder FAILED
[beanshell]      [exec]     java.lang.AssertionError: [Value of variable '_name' is unused: /tmp/aeb62q0V/com/liferay/source/formatter/dependencies/ConstructorParameterOrder.java 61 (Checkstyle:UnusedVariableCheck)] expected:<0> but was:<1>
[beanshell]      [exec]         at org.junit.Assert.fail(Assert.java:89)
[beanshell]      [exec]         at org.junit.Assert.failNotEquals(Assert.java:835)
[beanshell]      [exec]         at org.junit.Assert.assertEquals(Assert.java:647)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8810/modules-unit-jdk8/0/12/jenkins-console.txt.gz?authuser=0)

**Comment by kevhlee** [comment]
Thanks @catarineaguiar for the heads-up! Luckily, this failures are occurring because the tests need to be updated. I will send an additional commit to handle them.

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@kevhlee Regressions found

Steps to reproduce: 
1. Import this 6.2 database dump: https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/6.2.5/data-archive/data-archive-notifications-mysql.zip
2. Upgrade the database with the upgrade tool

Expected Results: Upgrade completes without issue
Actual Results: The upgrade fails with
```
     [java] 2023-12-06 04:49:40.551 INFO  [main][UpgradeProcess:137] Failed upgrade process com.liferay.questions.web.internal.upgrade.v1_0_0.UpdateAllowedServicesSignaturesInSAPEntryUpgradeProcess in 2 ms
     [java] 2023-12-06 04:49:40.554 ERROR [main][UpgradeExecutor:333] Failed upgrade process for module com.liferay.questions.web
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Table 'lportal.SAPEntry' doesn't exist
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:128) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor._executeUpgradeInfos(UpgradeExecutor.java:202) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.executeUpgradeInfos(UpgradeExecutor.java:124) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.execute(UpgradeExecutor.java:85) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeExecutor.java:330) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeExecutor.java:290) ~[?:?]
     [java] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$DefaultEmitter.emit(ServiceTrackerMapImpl.java:200) ~[com.liferay.osgi.service.tracker.collections.jar:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.lambda$activate$0(UpgradeExecutor.java:179) ~[?:?]
     [java] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerMapImpl.java:256) [com.liferay.osgi.service.tracker.collections.jar:?]
```
[Log](https://testray.liferay.com/reports/production/logs/2023-12/test-1-26/test-portal-acceptance-pullrequest(master)/12221/functional-upgrade-tomcat90-mysql57-jdk8/3/1/jenkins-console.txt.gz?authuser=0)

**Comment by kevhlee** [comment]
@Kvale1733, thanks for letting me know!

**Pull request closed without merging**
