### PR TITLE
[Components with more than 1 service] LPS-190147 Refactor DLOpenerGoogleDriveManager component

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-190147

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:lima

**Comment by MrJohn1911** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Comment by dantewang** [comment]
@MrJohn1911 The `DLOpenerGoogleDriveManager` is deprecated, and its usages are limited in the dl-opener-google-drive-web module. Could you check with the product team about this? Do we still support this feature? Can we just delete, or archive these modules?

And if not, please avoid using `Snapshot` in the extracted util. Try to find another way. Or, at last, add new methods to the interface...

Please resend, thanks!

**Pull request closed without merging**
