### PR TITLE
LPS-199721 Fix tests in module cookies-test

### PR DESCRIPTION
**Pull request by JanisZhang**

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:help

**Comment by JanisZhang** [comment]
ci:test:cookies

**Comment by tinatian** [comment]
@vicnate5 Please prioritize this pull, it is for security issue.

Thanks.
Tina.

**Comment by Kvale1733** [comment]
@JanisZhang @tinatian No regressions found. The affected tests are passing.

**Comment by JanisZhang** [comment]
ci:forward:force 

cc dantewang @tinatian

**Pull request closed without merging**
