### PR TITLE
[SF] LPS-201988 Create SF rule to check input streams from URL objects

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__ <https://liferay.atlassian.net/browse/LPS-201988>

See these links for context:

- <https://liferay.atlassian.net/browse/LPS-201988>
- <https://github.com/brianchandotcom/liferay-portal/pull/143943>

### CODE REVIEW

**Comment by kevhlee** [comment]
cc: @shuyangzhou

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
SF is unrelated. No regressions found.

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
Unrelated SF errors. No regressions found.

**Pull request closed without merging**
