### PR TITLE
[Remove Stream/Optional usage] LPS-174299 Remove usages of Stream for module: portal-workflow-kaleo-metrics-integration

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(2/10 9:06)

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3523

**Pull request closed without merging**
