### PR TITLE
[Replace Non-Blocking Usage] LPS-199958 

### PR DESCRIPTION
**Pull request by JanisZhang**
resent:https://github.com/liferay-core-infra/liferay-portal/pull/5899
https://liferay.atlassian.net/browse/LPS-199958

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
No regressions found. Just rerunning the stable suite.

**Comment by melodywu** [comment]
Reviewing...

**Comment by melodywu** [comment]
The [relevant](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2450393330) and [startup](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2450367737) and [upgrade](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2451297200) results are look good to me.

cc @zhangyan0701

**Comment by dantewang** [comment]
@JanisZhang Code change looks good to me, unfortunately the change caused a major version bump, so I think a breaking change doc is needed. You can just update the commit message where you removed that public setter and force push.

**Comment by JanisZhang** [comment]
@dantewang Thanks Dante! I added the breaking change report in the commit message and force-pushed.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143274

cc @shuyangzhou

**Pull request closed without merging**
