### PR TITLE
[Bug fix] LPS-143660

### PR DESCRIPTION
**Pull request by dantewang**
https://issues.liferay.com/browse/LPS-143660 @tinatian Changed the test to a unit test and avoided downloading from the internet.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@zhangyan0701 can you check this one?

**Comment by zhangyan0701** [comment]
No related issues found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113618

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
