### PR TITLE
[TS]LPS-163136 Bump Tika-Core and Tika-Parsers to 1.28.5

### PR DESCRIPTION
**Pull request by javalosjr96**
Ticket:
https://issues.liferay.com/browse/LPS-163136

Issue:
A customer has recently flagged tika-core with https://github.com/advisories/GHSA-rpjm-422r-95mh.

Solution:
Bump Tika to 1.28.5

Due to the connection with tika-parsers, tika-parsers will also have to be updated.

POI/POI-OOXML/POI-SCRATCHPAD were patched and updated.
POI-OOXML-SCHEMAS was replaced by POI-OOXML-LITE(also patched)
XMLBEANS was updated as it was listed as a dependency(also patched)

Added commons-io to batch-service-engine in order to resolve test failures introduced by updating POI/POI-OOXML.

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by javalosjr96** [comment]
@zhangyan0701 
Hi Summer,
I'm checking out this error as it references poi.
> java.lang.NoSuchMethodError: org.apache.poi.hssf.usermodel.HSSFFont.getIndex()S
  at net.sf.jasperreports.engine.export.JRXlsExporter$StyleInfo.computeHash(JRXlsExporter.java:2499)
  at net.sf.jasperreports.engine.export.JRXlsExporter$StyleInfo.<init>(JRXlsExporter.java:2489)
  at net.sf.jasperreports.engine.export.JRXlsExporter$StyleInfo.<init>(JRXlsExporter.java:2450)
  at net.sf.jasperreports.engine.export.JRXlsExporter.getLoadedCellStyle(JRXlsExporter.java:1411)
  at net.sf.jasperreports.engine.export.JRXlsExporter.addBlankCell(JRXlsExporter.java:717)

**Comment by javalosjr96** [comment]
@zhangyan0701 
The error was relevant and it was caused by the update to POI.

The cause was a method in HSSFont changing from returning an short to an int,  the upgrade to jasper was accounts for that update. 
I also updated jaspereports in commerce-report-impl to be consistent.

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
Sf errors are unrelated.

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
ci:reevaluate:1317401_5838

**Comment by javalosjr96** [comment]
@zhangyan0701 
Hi Summer,
Can you recheck the tests?

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:sf

**Pull request closed without merging**
