### PR TITLE
[Spring Beans] LPS-201423 Move ConvertProcessMessageListener to module document-library-service

### PR DESCRIPTION
**Pull request by JanisZhang**
https://liferay.atlassian.net/browse/LPS-201423

### CODE REVIEW

**Review by dantewang — CHANGES_REQUESTED** [review]
https://github.com/liferay-core-infra/liferay-portal/pull/6110#pullrequestreview-1726576330

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@zhangyan0701 Could you prioritize this PR? Thanks!

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/144419

**Pull request closed without merging**
