### PR TITLE
[Component with its own class name as service type] LPS-198943 Refactor Helper components from commerce modules part 1

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-198943](https://liferay.atlassian.net/browse/LPS-198943)

Previous Pull: https://github.com/brianchandotcom/liferay-portal/pull/142874

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
@RenanUmV No regressions found.

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by rafaprax — CHANGES_REQUESTED** [review]
Hey @RenanUmV, put the "inline" changes in a separate commit. Thx

**Comment by rafaprax** [comment]
Hey @RenanUmV, fix and resend. Thx

**Pull request closed without merging**
