### PR TITLE
LPS-167148 Remove "immediate = true" from Echo components part 2 

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
@RenanUmV Regressions found. I believe they are related since it affects Web Content

1) Searching for Web Content does not work after Search Re-index

        Steps to reproduce:
            i. Start portal and go to Control Panel -> Search - > Index Options
            ii. Click Execute for Reindex search indexes
            iii. Create a Web Content Article with title "WC Title"
            iv. Go to Liferay DXP Site
            v. Use the search widget to search "WC Title"
            
          Expected Results: The Web Content Article appears in search results
          Actual Results: No result appears in Search Results
          
 2) Web Content does not appear in Asset publisher after Search Re-index

        Steps to reproduce:
            i. Start portal and go to Control Panel -> Search - > Index Options
            ii. Click Execute for Reindex search indexes
            iii. Create a Web Content Article with title "WC Title"
            iv. Create a widget page on the default site and add an Asset Publisher
         
          Expected Results: The Web Content Article appears in the Asset Publisher
          Actual Results: No results are shown in the Asset Publisher

**Comment by RenanUmV** [comment]
ci:test:echo

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
@RenanUmV could you rebase, please? thanks!

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
@RenanUmV no regressions found.

**Comment by RenanUmV** [comment]
Thanks @catarineaguiar

**Comment by shuyangzhou** [comment]
@RenanUmV why the last commit is needed? Indexer are collected by IndexerRegistryImpl which opens a ServiceTracker for all Indexers.

**Comment by RenanUmV** [comment]
@shuyangzhou, @rafaprax helping me to investigate. When I remove immediate and excute "Reindex search indexes", this indexer becomes "satisfied"

**Comment by shuyangzhou** [comment]
@RenanUmV please be more specific on the issue, I need to see what exactly is broken without the last commit.

**Comment by shuyangzhou** [comment]
@RenanUmV please rebase

**Comment by tinatian** [comment]
@RenanUmV Please rebase

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-core-infra/liferay-portal/pull/2525

**Pull request closed without merging**
