### PR TITLE
LPS-144422 Add edit in production/publication actions

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by tinatian** [comment]
@stsquared99 Please always remember to trigger related tests when you sent a pull.

Thanks.
Tina.

**Comment by stsquared99** [comment]
ci:test

**Comment by stsquared99** [comment]
ci:test:sf

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by stsquared99** [comment]
@xbrianlee Can you review these test results? Thanks!

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
@stsquared99 Sure thing, I'll have to manually test this since the functional tests that failed due to test required fixes would have caught any potential issues with these changes.

**Comment by xbrianlee** [comment]
ci:close

Continued in https://github.com/liferay-core-infra/liferay-portal/pull/286

**Pull request closed without merging**
