### PR TITLE
[Remove Stream/Optional usage] LPS-170479 adaptive-media Part 1] Lps 170479 part 1

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-170479

Resend this one by renaming the `adaptiveMediaList` to `adaptiveMedias` since there are a lot of usages like that in adaptive-mediain module 

Original comment: https://github.com/brianchandotcom/liferay-portal/pull/128582#issuecomment-1379267532

### CODE REVIEW

**Comment by dantewang** [comment]
@slnn Compile error.

**Comment by slnn** [comment]
ci:stop

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
> @slnn Compile error.

Fix and forced push to rerun tests

**Comment by Kvale1733** [comment]
@slnn No regressions.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128736

I fixed one of the places you didn't rename: https://github.com/liferay-core-infra/liferay-portal/pull/3022/commits/97089437949d694386e6bbd6dc015d2b25801d78#diff-f3a39844badd17fbcecc08f27cafded7ff046916b89b7e5be87ea66245519572R228

**Pull request closed without merging**
