### PR TITLE
LPS-162898

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Make changes after discussed in https://github.com/liferay-core-infra/liferay-portal/pull/1680
This is the sub-task of https://issues.liferay.com/browse/LPS-149354.
Thanks for checking.

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions.

**Comment by tinatian** [comment]
@jeffwu0724 Why you can remove the dependency in build.gradle? If you did this in your first commit,  and when people is happen to be at that commit, he is going to have a broken portal. 
Please move it the the last commit and make sure you have your reason to remove it.

Tina.

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@Kvale1733 can you check the results when it finish? Thanks!

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found. But there are merge conflicts.

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
@tinatian what's the point for this change? Since the shielded container change, portal-impl has no difference to portal-kernel from classloading point of view. The module needs to use portal-kernel anyway, why removing portal-impl from it and adding this additional reference injection?

When we go back to lib cleanup and global osgi conversion, in the end, there won't be portal-kernel and portal-impl, there will just be a portal module.

I don't think this kind of cleanup can give me any benefit, only slowing down startup by adding more references.

**Comment by tinatian** [comment]
@shuyangzhou 
The benefit I think is we are coding with API rather than implementation. 

We know that portal-kernel only exports interfaces and do not have dependencies to third parties, by removing dependency of portal-impl on build.gradle shows us that this is a module independent of any implementation, also avoid people using the hidden exported packages from portal-impl. 

Event though, portal kernel and portal impl are going to be modules someday, most probably there will be api module and impl module. By doing this, it would help us to follow the pattern.

While, this is LPKG related stuff, it is kind of deprecated, I am OK to not do it. But I am still going to avoid adding new dependencies to portal-impl whenever possible. 


Tina.

**Comment by shuyangzhou** [comment]
The root issue is this unnecessary api/impl/util separation, not whether to depend on impl.
It was making sense when portal-kernal/portal-impl were in different classloaders. But not anymore.

Once portal-kernal/portal-impl are merged, we will merge all the unnecessary api/impl/util separation. Unless the impl will be exacted out to its own module.

**Comment by tinatian** [comment]
@shuyangzhou I do not think we can finally have portal-kernel and portal-impl merged, maybe some of logic, but I believe most of them will become api and impl modules. While, it is hard to say which parts will be merged which not now, it is too early as this migration might take years.
Anyway, to me, for now, not seeing portal-imp in build.gradle is kind of independent, also it is kind of safe, as at least, you can not see the hidden exported packages in portal-impl.

Tina.

**Pull request closed without merging**
