### PR TITLE
LPS-160039 Optimize method findClass of class FreeMarkerBundleClassloader

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:acceptance

**Comment by guilhermedcamacho** [comment]
ci:test:acceptance

**Comment by guilhermedcamacho** [comment]
@catarineaguiar please help me check the results when available, thanks!

**Comment by catarineaguiar** [comment]
@guilhermedcamacho possible regression:

```
 [junit] Testcase: testBuildContent(com.liferay.portal.tools.ConfigurationEnvBuilderTest):	FAILED
    [junit] Run "ant update-portal-osgi-configuration-properties". Missing: [configuration.override.com.liferay.portal.template.freemarker.configuration.FreeMarkerEngineConfiguration_symbolicNameMappers=]
    [junit] junit.framework.AssertionFailedError: Run "ant update-portal-osgi-configuration-properties". Missing: [configuration.override.com.liferay.portal.template.freemarker.configuration.FreeMarkerEngineConfiguration_symbolicNameMappers=]
    [junit] 	at com.liferay.portal.tools.ConfigurationEnvBuilderTest.testBuildContent(ConfigurationEnvBuilderTest.java:111)
    [junit] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    [junit] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-08/test-1-37/test-portal-acceptance-pullrequest(master)/4212/unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by guilhermedcamacho** [comment]
Thanks @catarineaguiar , I've just appended a new commit with regen of this file, so now it's passing.

`test-class:
     [echo] test.cmd.start.timestamp: 08-15-2022 10:48:07:852 PDT
    [junit] Running com.liferay.portal.tools.ConfigurationEnvBuilderTest
    [junit] Testsuite: com.liferay.portal.tools.ConfigurationEnvBuilderTest
    [junit] SLF4J: Class path contains multiple SLF4J bindings.
    [junit] SLF4J: Found binding in [file:/home/guilherme/workspace/liferay-portal/util-slf4j/classes/org/slf4j/impl/StaticLoggerBinder.class]
    [junit] SLF4J: Found binding in [jar:file:/home/guilherme/workspace/liferay-portal/lib/development/slf4j-simple.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    [junit] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
    [junit] SLF4J: Actual binding is of type [com.liferay.util.slf4j.LiferayLoggerFactory]
    [junit] Loading file:/home/guilherme/workspace/liferay-portal/portal-impl/classes/system.properties
    [junit] Loading file:/home/guilherme/workspace/liferay-portal/portal-impl/classes/portal.properties
    [junit] Loading file:/home/guilherme/workspace/liferay-portal/portal-impl/test-classes/unit/portal-test.properties
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2,815 sec
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2,815 sec
    [junit] 
[stopwatch] [test.cmd: 3.349 sec]

BUILD SUCCESSFUL
Total time: 4 seconds
`

**Comment by guilhermedcamacho** [comment]
@shuyangzhou , this PR is ready for your review. Thanks!

**Comment by shuyangzhou** [comment]
@guilhermedcamacho after reading your code, I realized there was some misunderstanding from the beginning. There should be a better way to do this. Let's have a talk on this after today's meeting.

**Pull request closed without merging**
