### PR TITLE
[Bug Fix] LPS-34889 Add validation

### PR DESCRIPTION
**Pull request by haydenzheng314**
@dantewang Resend, rebase and SF
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/6268
Ticket: https://liferay.atlassian.net/browse/LPS-34889
Thanks.

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:stop

**Comment by LisztLiszt** [comment]
@dantewang Force pushed to directly use reference

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by LisztLiszt** [comment]
@dantewang Force pushed to change commit message, no logic change

**Comment by LisztLiszt** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:configuration-framework

**Comment by Kvale1733** [comment]
@LisztLiszt No regressions found. Testing passed following the ticket steps. The configuration cannot be saved.

**Comment by dantewang** [comment]
ci:forward

cc @tinatian

**Pull request closed without merging**
