### PR TITLE
LPS-151745 Add LIFERAY_SHARED_ prefix to attribute name in order to propagate the check access allowed to the portlet until the PortletFragmentEntryProcessor

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-151745

Please see [this comment](https://github.com/liferay-core-infra/liferay-portal/pull/758#issuecomment-1125747753) in a previous pull request.

Thanks

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@lfbesada
To fix an issue, there are so many ways. For example, there is an NullPointerException, and I can just add a null checking to avoid it. But the question is: is it right to add a null checking? does it make sense here to add a null checking?

Same to your fix, I know with your fix, you won't see the original issue, but is it right? why adding a prefix works? The fix itself seems weird to me, I need to know the root reason we need this. I did not find the information in your comment here https://github.com/liferay-core-infra/liferay-portal/pull/758#issuecomment-1125747753. Could you please explain more?


Thanks.
Tina.

**Comment by lfbesada** [comment]
Hello @tinatian 
Thank you for your feedback.
I will try to explain the solution I have chosen and explain why IMHO it is the best approach.
On content pages, fragments containing portlets are rendered by the PortletFragmentEntryProcessor.java. To render the portlet it calls to FragmentPortletRenderer.renderPortlet which uses RuntimeTag.doTag to do it.
When the user does not have permissions to view the portlet RuntimeTag.doTag does not throw any exception, it simply returns an HTML with the message that the user does not have permissions to view that portlet or an empty string depending on the configuration in "layout.show.portlet. access.denied" portal property.
This implies that when using RuntimeTag.doTag we cannot know if the user has access permissions or not only with his response. We need to know it to solve the bug that is described since if there are no permissions to see the portlet, the styles of that fragment should not be added either.
To solve it I came up with two solutions:
1. Take advantage of the attribute that DefaultLayoutTypeAccessPolicyImpl.java put in the request with the result of the permissions check using it to determine if the access was allowed.
2. Check portlet permissions again after calling RuntimeTag.doTag, this solution could be inconsistent because of run conditions: the portlet permissions could change between the two checks.
I found the first option to be the most consistent and best performing, so I submitted this PR using that attribute:
https://github.com/brianchandotcom/liferay-portal/pull/117066
That PR was only reviewed by Echo since all the components that are touched are from the team.
Later on, noticed that this did not fix the bug because the attribute is not propagated to the request that is used to call RuntimeTag.doTag.
This is the issue is that I intend to solve with this PR by adding that prefix to the name of the attribute so that it is propagated.
This time I send the PR to your team because I am modifying one of your components.
I hope I have explained myself, if there is something that I have not clarified, I will be happy to try again.
Thank you very much, regards

**Comment by tinatian** [comment]
> noticed that this did not fix the bug because the attribute is not propagated to the request that is used to call RuntimeTag.doTag.
Should the attribute propagate to the request or not? If yes, then why it did not propagated?

**Comment by lfbesada** [comment]
Yes, it should be propagated and currently, it is not propagated because of the current name.
The attributes propagation occurs [here](https://github.com/liferay/liferay-portal/blob/8ca849c21f5a1157c7708b4d837f92b2f847f101/util-taglib/src/com/liferay/taglib/portletext/RuntimeTag.java#L380)
In the implementation to decide if the attribute is propagated or not, [this](https://github.com/liferay/liferay-portal/blob/25d24354665b5579d40da360e2653087946c7f52/portal-kernel/src/com/liferay/portal/kernel/portlet/RestrictPortletServletRequest.java#L41) method is called.
The condition that applies the method is that the attribute name starts with some prefix configured in the portal property request.shared.attributes. By default, this property is set to LIFERAY_SHARED_, please see: https://github.com/liferay/liferay-portal/blob/7adb145a55669f31c2dade04d81ab9dcfff723c1/portal-impl/src/portal.properties#L2913

**Comment by tinatian** [comment]
@lfbesada
Thanks for the explanations. 

Since LIFERAY_SHARED_ is the value of a property set in portal.properties, it is possible that people can change the value. When people change the value, you fix is not going to work as you hard coded "LIFERAY_SHARED_ " into your code. 

You should never make your code depend on a property value which can be changed. Please try to fix it in another way and resend.


Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
