### PR TITLE
LPS-161575 Break the circular dependency: CPInstanceLocalService -> C…

### PR DESCRIPTION
**Pull request by slnn**
Hi @tinatian @dantewang

This pull breaks the circular dependency: CPInstanceLocalService -> CProductLocalService -> CPDefinitionLinkLocalService -> CPDefinitionLocalService -> CPinstanceLocalService

Lily

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:commerce

**Comment by dantewang** [comment]
@zhangyan0701 Could you please review the test results when they finish? Thanks!

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by slnn** [comment]
Hi @dantewang

Since the change for disabling auto import ([LPS-161869](https://issues.liferay.com/browse/LPS-161869)) has merged into master, I rebase this branch with the master and forced push on this pull.

Lily

**Comment by slnn** [comment]
With the forced push change, the ci test has been ran in: https://github.com/slnn/liferay-portal/pull/632

**Comment by tinatian** [comment]
@slnn Code looks good to me, wait for commerce team to review.

Tina

**Comment by victoroscuro** [comment]
ci:test:commerce

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122767

**Pull request closed without merging**
