### PR TITLE
[BLOCKER] LPS-196816

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by brunofalc** [comment]
cc @yuhai @dantewang

**Review by yuhai — APPROVED** [review]
@dantewang, the pr is good to me.

**Comment by yuhai** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found from the ci tests.

Also the testing for LPS-196816 passed.

**Comment by dantewang** [comment]
@shuyangzhou This fix is implemented following the request of security team.

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by marianoalvarosaiz** [comment]
ci:forward

**Pull request closed without merging**
