### PR TITLE
remove_deprecated_for_portal_kernel_part_Seven

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

I have removed the deprecated for
"UpgradeProcessUtil.java"
"BaseUpgradeAttachments.java"
classes with prefix "BaseUpgrade"
"RenameUpgradePortalPreferences.java"
"UpgradeProcess.java"
"UpgradeViewCount.java"
"BasePortletIdUpgradeProcess.java"
"BaseLocalizedColumnUpgradeProcess.java"
"AggregateResourceBundleLoader.java"
"ArrayUtil.java" and "ArrayUtil_IW.java"
Thanks for checking. Also see https://github.com/jeffwu0724/liferay-portal/pull/45

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by kyle-miho** [comment]
waiting for acceptance result, will likely look at this tmr

**Comment by kyle-miho** [comment]
@jeffwu0724 failures should be unrelated

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by kyle-miho** [comment]
@jeffwu0724 is this change in your pr? semantic versioning error:
com.liferay.portal.upgrade.step.util               MAJOR      2.1.0      2.1.0      3.0.0      VERSION INCREASE REQUIRED
>   class      com.liferay.portal.upgrade.step.util.UpgradeStepFactory

method     addColumns(java.lang.Class,java.lang.String[])
-   access     static
-   return     com.liferay.portal.kernel.upgrade.UpgradeStep

method     alterColumnTypes(java.lang.Class,java.lang.String,java.lang.String[])
-   access     static
-   return     com.liferay.portal.kernel.upgrade.UpgradeStep

method     dropColumns(java.lang.Class,java.lang.String[])
-   access     static
-   return     com.liferay.portal.kernel.upgrade.UpgradeStep
[Baseline Warning] Bundle Version Change Recommended: 7.0.0

**Comment by jeffwu0724** [comment]
> com.liferay.portal.upgrade.step.util.UpgradeStepFactory

@kyle-miho , yes I made this changes here. I will redo the semantic version now. Please help me to check again when the test is ready.

Thanks,
Jeff

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:stop

**Comment by jeffwu0724** [comment]
ci:test

**Comment by vicnate5** [comment]
@catarineaguiar can you check this one? you should have build permissions for the analysis tool now. Start with acceptance, this PR is just waiting for Testray import.

**Comment by catarineaguiar** [comment]
@jeffwu0724 No regressions were found.

**Comment by jeffwu0724** [comment]
> @jeffwu0724 No regressions were found.

Thanks a lot :+1: @catarineaguiar

**Comment by tinatian** [comment]
@jeffwu0724 Code looks good to me, code conflicts, please rebase.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115871

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
