### PR TITLE
[TS] LPS-161481 StaleObjectStateException is caused by Hibernate auto-flush behaviour 

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-161481](https://issues.liferay.com/browse/LPS-161481)

Dear Team,

Please review my changes.

When creating a user in a user limited company (maxUsers != 0) by a permission limited user, StaleObjectStateException is thrown. As Dante explained on the related PTR ticket, the issue occurs because of auto-flush behaviour of Hibernate, when Hibernate does a flush for some reason, causing the bump of mvccVersion, while the service is holding an "outdated" object.

Please let me know if I can help you with anything else.

Thank you,
Istvan

cc @dantewang

### CODE REVIEW

**Comment by Kvale1733** [comment]
@istvansajtos PMD issue found
```
    [echo] PMD VIOLATION: /opt/dev/projects/github/liferay-portal/modules/apps/user/user-test/src/testIntegration/java/com/liferay/user/service/test/UserLocalServiceTest.java:158 > Do not call Assert#fail improperly. (PMD Rule: AssertFailJUnitRule)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-02/test-1-34/test-portal-acceptance-pullrequest(master)/3550/pmd-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by istvansajtos** [comment]
Thank for pointing out, @Kvale1733 ! I've removed the improperly used assertion and simply let the test fail if the invoked service throws an exception.

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@istvansajtos No regressions found. Testing passed following ticket steps.

**Comment by yuhai** [comment]
Hi @istvansajtos,

I have two concerns.

1. I can't reproduce the issue on the latest master(92eb37f7c8b16808506452ca2f667c86b9586fe0). So without the fix, the test **testAddUserToCompanyWithMaxUsersLimit** also can be passed. But I can reproduce the issue on the 7.3.x. Could you please test the issue on the latest master again?

2. There is no **Assert** statement in your test. It looks weird. Please make sure one **Assert** existed in your test.

Thanks,
Hai

**Comment by tinatian** [comment]
@istvansajtos I am going to close this pull, please resend according to Hai's comment.

Thanks.
Tina.

**Comment by istvansajtos** [comment]
Hi @yuhai , 

I was able to reproduce with 903c74f2af3db96b4f76baa4f2ccd79a4f49b54f, but I will test with 92eb37f7c8b16808506452ca2f667c86b9586fe0 as you suggested.

Regarding the missing Assert, originally my test had an assertion in the following form:
```
	try {
		_userLocalService.addUserWithWorkflow(
			creatorUserId, company.getCompanyId(), autoPassword, null, null,
			autoScreenName, null, emailAddress, locale, firstName, middleName,
			lastName, prefixListTypeId, suffixListTypeId, male, birthdayMonth,
			birthdayDay, birthdayYear, jobTitle, null, null, null, null, false,
			ServiceContextTestUtil.getServiceContext());
	}
	catch (Exception exception) {
		Assert.fail();
	}
```

But this caused a PMD issue mentioned [above](https://github.com/liferay-core-infra/liferay-portal/pull/3570#issuecomment-1438892793).

How do we use Assert to test if exception is thrown in the tested service method? Do we have an example somewhere?

Thank you!

**Comment by yuhai** [comment]
Hi @istvansajtos,

The normal pr order should be:
1. Add test to expose the issue 
2. Add the fix.

When exception was thrown, it belongs to expose the issue for the case. We needn't to take care this. And then you may use  `Assert.assertNotNull(_userLocalService.addUserWithWorkflow(...))`;

After your fix, the test won't throw exception and be passed.

Thanks,
Hai

Thanks,
Hai

**Pull request closed without merging**
