### PR TITLE
LPD-35168 Binding two trees into one using a relationship

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
Related tasks : [LPD-35168](https://liferay.atlassian.net/browse/LPD-35168) [LPD-37130](https://liferay.atlassian.net/browse/LPD-37130)

This PR is a resubmission of a previous PR that was https://github.com/brianchandotcom/liferay-portal/pull/154676 due to snapshot usage. To resolve this, we changed the TreeFactoryImpl class to a regular class instead of an OSGi component. The first two commits address this change : https://github.com/liferay-core-infra/liferay-portal/pull/7496/commits/d7ce02cbf97bb51fba07c57f9bbca807b06972f6  https://github.com/liferay-core-infra/liferay-portal/pull/7496/commits/155e36b563ee6fd2c5da1962d422782e5120a529

[LPD-35168]: https://liferay.atlassian.net/browse/LPD-35168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LPD-37130]: https://liferay.atlassian.net/browse/LPD-37130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tinatian** [comment]
@JerryAdrianoo Please verify startup test

**Comment by gabrielwas** [comment]
@tinatian Could you help us here? This PR is blocking some others to be merged.

**Comment by tinatian** [comment]
@gabrielwas I am good with the changes except one concern of the feature flag usage. Feature flag is actually company-aware and depends on CompanyThreadLocal, and we had experienced a lot of issues about it caused by wrong usages, please check https://liferay.atlassian.net/browse/LPD-37984.

If you are sure about your feature flag usage here, it is good to forward.

**Comment by tinatian** [comment]
@gabrielwas I am going to close this pull based on our discussion on slack.

**Pull request closed without merging**
