### PR TITLE
[Method References 2] LPS-165445 Directly reference class IndexerRequestBufferExecutor

### PR DESCRIPTION
**Pull request by W2jx**
Detail: https://github.com/liferay-core-infra/liferay-portal/pull/2531

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@W2jx semver error:

```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/portal-search/portal-search-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.portal.search.buffer                   MAJOR      5.0.0      5.0.0      6.0.0      VERSION INCREASE REQUIRED
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-31/test-portal-acceptance-pullrequest(master)/6070/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
Force-Push is just to resolve the conflict about file Language_ko.properties, and fix the semver error.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
Force-Push is just to rebase and resolve conflicts about files 

```
modules/apps/portal-search/portal-search-api/bnd.bnd
modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/IndexerRegistryImpl.java
modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/buffer/DefaultIndexerRequestBufferExecutor.java
modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/buffer/DefaultIndexerRequestBufferOverflowHandler.java
modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/buffer/IndexerRequestBufferExecutorWatcher.java
```

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
no conflicts(2022/12/5 13:18)

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@W2jx For this commit https://github.com/liferay-core-infra/liferay-portal/pull/2544/commits/596b0075dcafee81b879223fa8f0731431d1d066, please separate into two, one modify language, one to regenerate language.

For this commit, https://github.com/liferay-core-infra/liferay-portal/pull/2544/commits/75fb27c263d58f70c6fffda02797d8c4d7adc175, please update commit message including the reason you made this changes.

This is a big pull, over 10 commits and lots of files changed, I will accept it this time as it is already passed ci test, please avoid big pull like this next time. Several small pulls would make your work concurrently compared to one big pull, thus your total output will be improved.

Thanks.
Tina.

**Pull request closed without merging**
