### PR TITLE
[PowerMock] LPS 151445 

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @tinatian @dantewang,

This pr is to remove powermock usage in ` dynamic-data-mapping-form-field-type ` part one.

https://issues.liferay.com/browse/LPS-151445 

Thanks for checking.

### CODE REVIEW

**Comment by tinatian** [comment]
@JanisZhang For setup method like this 
public void setup() {
 init****();
init****();
}
Can you keep it as before instead of inline them? I would like to see your changes clearly. Please apply this to all other changes about power mock.

Thanks.
Tina.

**Comment by JanisZhang** [comment]
Noted, thanks!

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:acceptance

**Comment by dantewang** [comment]
@JanisZhang please check the failures in modules-unit-jdk8, thanks!

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go. All changes are made to unit test and unit test batch passed on ci, no need to scan test results manually.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116249

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
