### PR TITLE
[Component with its own class name as service type] LPS-201312 Refactor Resource components from Commerce module

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-201312

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
@MrJohn1911 Regression found

**Steps to reproduce:** 
1. Add a Minium Site
2. Go to the Minium Site
3. Click on Search Icon (top left)
4. Type "U-Joint" in the search bar

Expected Results: An entry appears showing "Search U-Joint in All Content" you can click on to view results
Actual Results: The search bar just keeps loading. Searching just doesn't work at all in the Minium site catalog

**Comment by Kvale1733** [comment]
ci:close

**Pull request closed without merging**
