### PR TITLE
LPS-198154 remove PortalCustomSQL as no real usage

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Shuyang,

Resent https://github.com/liferay-core-infra/liferay-portal/pull/5718
This PR is for https://liferay.atlassian.net/browse/LPS-198154.
It looks like there is no real usage of PortalCustomSQL in the code base, so as discussed, I just removed them all
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions just a semver issue
```
  [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.dao.orm                  MAJOR      12.0.0     12.0.0     13.0.0     VERSION INCREASE REQUIRED
     [exec] 	-   class      com.liferay.portal.kernel.dao.orm.PortalCustomSQLUtil
     [exec] 		-   method     <init>()
     [exec] 			-   return     void
     [exec] 		-   method     clone()
     [exec] 			-   access     protected
     [exec] 			-   return     java.lang.Object
     [exec] 		-   method     equals(java.lang.Object)
     [exec] 			-   return     boolean
     [exec] 		-   method     finalize()
     [exec] 			-   access     protected
     [exec] 			-   return     void
     [exec] 		-   method     get(java.lang.String)
     [exec] 			-   access     static
     [exec] 			-   return     java.lang.String
     [exec] 		-   method     getPortalCustomSQL()
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.dao.orm.PortalCustomSQL
     [exec] 		-   method     hashCode()
     [exec] 			-   return     int
     [exec] 		-   method     setPortalCustomSQL(com.liferay.portal.kernel.dao.orm.PortalCustomSQL)
     [exec] 			-   return     void
     [exec] 		-   method     toString()
     [exec] 			-   return     java.lang.String
     [exec] 	-   interface  com.liferay.portal.kernel.dao.orm.PortalCustomSQL
     [exec] 		-   access     abstract
     [exec] 		-   method     get(java.lang.String)
     [exec] 			-   access     abstract
     [exec] 			-   return     java.lang.String
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/porta
```
[Log](https://testray.liferay.com/reports/production/logs/2023-10/test-1-31/test-portal-acceptance-pullrequest(master)/9641/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
fixed the code conflict in portal-impl/src/META-INF/util-spring.xml, the previous test should be good enough

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142347

**Pull request closed without merging**
