### PR TITLE
[OrderByComparator] LPD-26656 Clean up and Apply Singleton in module portal-workflow-web

### PR DESCRIPTION
**Pull request by jpcchaves**
- **LPD-26656** Clean up and Apply Singleton in module portal-workflow - Part I

### CODE REVIEW

**Comment by jpcchaves** [comment]
ci:test:relevant

**Comment by jpcchaves** [comment]
ci:report:2571894143

**Comment by jpcchaves** [comment]
ci:test:sf

**Comment by jpcchaves** [comment]
ci:test:relevant

**Comment by jpcchaves** [comment]
ci:report:2572295308

**Comment by jpcchaves** [comment]
ci:report:2572430538

**Comment by jpcchaves** [comment]
ci:report:2572430538

**Comment by jpcchaves** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
New changes are needed! I'll fix it and send it back. THX
CC: @titokenzo

**Pull request closed without merging**
