### PR TITLE
[Spring Beans] LPS-200089 Move class PermissionCheckerFactoryImpl into module portal-security-permission-impl

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian , 

I have resent this pr. 

  About question "How could a bundle class loader see it? " you mentioned, I debugged the code and found that: 
When loading `com.liferay.portal.security.permission.AdvancedPermissionChecker`, the class loader `EquinoxClassLoader` of bundle `portal-security-permission-impl` will find `BundleLoader` and ultimately get `PackageSource` via method `BundleLoader.findImportedSource`, thereby get the `PackageSource` and `class loader` of `portal-impl` then loading `AdvancedPermissionChecker`.

   And I moved `AdvancedPermissionChecker`  to module and removed property `permissions.checker`

Thank you!

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5938

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(11/14 15:49)

**Comment by W2jx** [comment]
no conflicts(11/15 10:19)

**Comment by W2jx** [comment]
no conflicts(11/17 8:18)

**Comment by W2jx** [comment]
no conflicts(11/20 13:57)

**Comment by W2jx** [comment]
no conflicts(11/21 15:06)

**Comment by W2jx** [comment]
no conflicts(11/22 15:05)

**Comment by W2jx** [comment]
no conflicts(11/24 15:34)

**Comment by W2jx** [comment]
no conflicts(11/28 10:07)

**Comment by W2jx** [comment]
no conflicts(12/12 14:24)

**Comment by W2jx** [comment]
no conflicts(12/18 12:57)

**Comment by W2jx** [comment]
no conflicts(12/19 10:03)

**Comment by W2jx** [comment]
no conflicts(12/20 10:01)

**Comment by W2jx** [comment]
no conflicts(12/21 10:05)

**Comment by W2jx** [comment]
no conflicts(12/22 9:17)

**Comment by W2jx** [comment]
no conflicts(12/26 10:27)

**Comment by W2jx** [comment]
no conflicts(12/28 9:49)

**Comment by W2jx** [comment]
no conflicts(12/29 16:11)

**Comment by W2jx** [comment]
no conflicts(1/2 9:33)

**Comment by tinatian** [comment]
Hi @W2jx Instead of removing "permissions.checker" directly, let's move it to an osgi configuration property. This way you actually keep the same feature as before, also, you do not need to remove "SimplePermissionChecker" as it is one of the option for the property

**Pull request closed without merging**
