### PR TITLE
LPS-145927 5-17

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian @marianoalvarosaiz

### CODE REVIEW

**Comment by dantewang** [comment]
Hi @zhangyan0701 could you review the CI results? Thanks!

**Comment by zhangyan0701** [comment]
There are some test failures seem related:

1.  [com.liferay.staging.test.StagingLocalizationTest](https://testray.liferay.com/home/-/testray/case_results/1851217734):
```
     [exec] com.liferay.staging.test.StagingLocalizationTest > testRemoveSupportedLocale FAILED
     [exec]     java.lang.AssertionError: Expected test to throw class com.liferay.portal.kernel.exception.LocaleException
```
Full console: https://testray.liferay.com/reports/production/logs/2022-05/test-1-28/test-portal-acceptance-pullrequest(master)/3150/modules-integration-mysql57-jdk8/3/14/jenkins-console.txt.gz?authuser=0

2.  [com.liferay.data.engine.rest.dto.v2_0.util.DataDefinitionDDMFormUtilTest](https://testray.liferay.com/home/-/testray/case_results/1851221458):
```
     [exec] com.liferay.data.engine.rest.dto.v2_0.util.DataDefinitionDDMFormUtilTest > testToDDMFormEquals FAILED
     [exec]     java.lang.AssertionError: expected:<com.liferay.dynamic.data.mapping.model.DDMForm@f88d22bc> but was:<com.liferay.dynamic.data.mapping.model.DDMForm@e5ad2937>
```
Full console: https://testray.liferay.com/reports/production/logs/2022-05/test-1-28/test-portal-acceptance-pullrequest(master)/3150/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0

3.  [com.liferay.dynamic.data.mapping.form.values.factory.DDMFormValuesFactoryTest](https://testray.liferay.com/home/-/testray/case_results/1851220173):
```
Failed tests: com.liferay.dynamic.data.mapping.form.values.factory.DDMFormValuesFactoryTest.testCreateWithRepeatableTransientParent, com.liferay.dynamic.data.mapping.form.values.factory.DDMFormValuesFactoryTest.testCreateWithRepeatableAndLocalizableField, com.liferay.dynamic.data.mapping.form.values.factory.DDMFormValuesFactoryTest.testCreateWithRepeatableAndLocalizableNestedField, com.liferay.dynamic.data.mapping.form.values.factory.DDMFormValuesFactoryTest.testCreateWithRepeatableAndLocalizableNestedFields, com.liferay.dynamic.data.mapping.form.values.factory.DDMFormValuesFactoryTest.testCreateWithLocalizableFields
```
Full console: https://testray.liferay.com/reports/production/logs/2022-05/test-1-28/test-portal-acceptance-pullrequest(master)/3150/modules-unit-jdk8/0/1/jenkins-console.txt.gz?authuser=0

**Comment by tinatian** [comment]
@marianoalvarosaiz I am going to close this pull, please fix failures and resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by marianoalvarosaiz** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/847

**Pull request closed without merging**
