### PR TITLE
[JDK21 Test Fix] LPD-26538 Increase memory for SecureXMLFactoryProviderImplTest

### PR DESCRIPTION
**Pull request by julschong**
https://liferay.atlassian.net/browse/LPD-26538

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:jdk21-unit

**Comment by julschong** [comment]
Test passed JDK21: https://testray.liferay.com/home/-/testray/case_results/2571249424?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3Fstatuses%3D2%26testrayBuildId%3D2571247605%26cur%3D2%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26resetCur%3Dfalse%26status%3D2

**Comment by julschong** [comment]
Ready for review

**Comment by julschong** [comment]
@tinatian I think increasing xmx7m to xmx11m is still the better solution to deal with this.
I was going to separete OutOfMemoryException tests into their own test method to try to reduce future need to increase the memory limit again. But, There is not guarantee that doing this will let us avoid adding memory in the future. And the downside of separating those test method is that we'll have more duplicated code in the Test file.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/151050

**Pull request closed without merging**
