### PR TITLE
[TS] LPS-205362

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@marianoalvarosaiz I do not understand why you are doing this https://github.com/liferay-core-infra/liferay-portal/pull/6478/commits/25c4cd3a64d0e23f29fd4f5c26936304cd9aabb9.

Also, how is this https://github.com/liferay-core-infra/liferay-portal/pull/6478/commits/c2e464379bf527a9465aa04656fa751fe53c0b2c related to other changes? Can you separate it out?

Thanks.
Tina.

**Comment by marianoalvarosaiz** [comment]
@tinatian https://github.com/liferay-core-infra/liferay-portal/commit/c2e464379bf527a9465aa04656fa751fe53c0b2c is the main purpose of the LPS. 

ObjectDefinitionLocalServiceImpl#deleteObjectDefinition() performs both DDL and DML sentences. If the method fails it can happen that the data updated/removed is rollbacked, but the `ObjectDefinitionLocalServiceImpl._dropTable`, due to MySQL implicit commit, is dropped and not reverted.

So I need to check in next executions if the table exists in order to drop it, just execute DROP TABLE IF EXISTS. Because there is no ANSI SQL for this we need to apply the DROP_TABLE_IF_EXISTS placeholder so that each database executes its own syntax sentences. Up to here it would be the fix needed to this LPS.

The problem is that SQLTransformer as it is now, generates code, for example for Oracle, like this:
```

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TABLE1'
EXCEPTION
WHEN OTHERS THEN
IF SQLCODE != -942 THEN
RAISE;
END IF;
END;
/
```

And this code cannot be directly executed by PreparedStament#executeUpdate, we need to strip the trailing '/'

This is done by one of the BaseDB#runSQL methods, but not by the code ServiceBuilder generates for LocalServiceBaseImpl classes. So I only see to options:

- Change the ftl so that ServiceBuilder generates the code invoking BaseDB#runSQL instead of SQLUpdate, but it was discarded in previous pulls.
- Make SQLTransformer#transform generate valid code that it can directly be executed by a JDBC update, so that the SQL consumers don't need to each take care of stripping those delimiters. That's what I performed in https://github.com/liferay-core-infra/liferay-portal/commit/25c4cd3a64d0e23f29fd4f5c26936304cd9aabb9.

**Comment by tinatian** [comment]
@marianoalvarosaiz Please see https://github.com/liferay-core-infra/liferay-portal/pull/6487.

Object is a very special among all the services, I would like to fix this in object scope as I did not see any other service is doing the same thing as Object.

We can extract this to a general solution when there are more use cases like Object in the future. For now, let's keep the framework code untouched and fix in object scope.

Tina.

**Pull request closed without merging**
