### PR TITLE
LPD-40679 Fix configurations detected by ModuleConfigurationLocalizationTest

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__ <https://liferay.atlassian.net/browse/LPD-40679>

This pull request fixes OSGi configurations detected by `ModuleConfigurationLocalizationTest` that are missing the `name` attributes for localization. There are other cases not covered by this pull request. However, those will require more analysis (a future pull request will be sent to handle those). This pull request is only handling the ones that show up on the UI and are definitely faulty.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
cc: @adolfopa, @dsanz, @andrea-ale-sbarra, @luca-pellizzon

**Comment by tinatian** [comment]
@julschong Please help me to trigger ModuleConfigurationLocalizationTest on this pull if it is not included in ci:test:relevant

**Comment by julschong** [comment]
@tinatian I cherrypicked commits from this PR on top of the PR that add the test onto stable testing here: https://github.com/julschong/liferay-portal/pull/1396

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7603

**Pull request closed without merging**
