### PR TITLE
[System Properties] [Part One]LPS-158206 Add new functionality to SystemProperties: get system properties by prefix

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I add a new method and unit test in this pr.

Detail: https://github.com/liferay-core-infra/liferay-portal/pull/1262

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701  , Could you please help me check the test results when they finish ? Thanks!

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
@zhangyan0701 thank you。

**Comment by tinatian** [comment]
@W2jx Code looks good to me, please rebase.

Thanks.
Tina

**Comment by W2jx** [comment]
@tinatian I have updated the code.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by W2jx** [comment]
Push code just to resolve conflicts.

**Comment by W2jx** [comment]
no conflicts(6:15 PM)

**Comment by W2jx** [comment]
no conflicts(6:50 AM)

**Comment by W2jx** [comment]
no conflicts(7:09 PM)

**Comment by dantewang** [comment]
@tinatian See https://github.com/liferay-core-infra/liferay-portal/pull/1447, found a usage issue of HashMapBuilder.

**Pull request closed without merging**
