### PR TITLE
[Remove Stream/Optional usage] LPS-172794 remove_stream_and_optional_in_portal_tools_rest_builder - part 1

### PR DESCRIPTION
**Pull request by dantewang**
@jeffwu0724

### CODE REVIEW

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:headless-acceptance

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
