### PR TITLE
Lps 181446 pr9

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
we are facing some CI issues, so let's wait for the fix to be merged to re-run test suites.

Thanks

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136715

**Pull request closed without merging**
