### PR TITLE
[Bug fix] LPS-189793 Make build.namespace unique using bundle symbolic name

### PR DESCRIPTION
**Pull request by petershin**
@dantewang

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:upgrade:nocompile

**Comment by Kvale1733** [comment]
ci:test:upgrade:norebase

**Comment by Kvale1733** [comment]
@dantewang No regressions found. A rebase is needed.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4966

**Pull request closed without merging**
