### PR TITLE
LPS-155057

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

This is for ticket https://issues.liferay.com/browse/LPS-155057.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
@jeffwu0724 please rebase and resend, thanks!

**Comment by jeffwu0724** [comment]
Hi @tinatian , @shuyangzhou ,

Someone in product team lima also update the build.gradle and have the PR merged. Please see https://github.com/liferay-lima/liferay-portal/pull/3112/commits/4367e279afe48cd99027359de5f9b7733a636a88.
Therefore, my PR now is only add "metadata-extractor" to source formatter, and also doing some auto generate after rebasing. 
Thanks for checking.

Best,
Jeff

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/118906

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
