### PR TITLE
LPS-171056

### PR DESCRIPTION
**Pull request by Kvale1733**
Previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/2881  

@tinatian Resent to include functional test.

### CODE REVIEW

**Comment by Kvale1733** [comment]
Improved test by replacing hardcoded path with macro.

**Comment by Kvale1733** [comment]
Made some slight improvements to the test by replacing hardcoded paths with a macro to assert the blog details.

**Comment by Kvale1733** [comment]
@tinatian The test passes with these changes and fails on master so the fix works.

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@IstvanD did you just follow the ticket steps to verify this was still an issue or did you follow some other steps? With the ticket steps this solves the issue.

**Comment by IstvanD** [comment]
Hi @Kvale1733 thank you for implementing the functional test.
Unfortunately, the solution doesn't solve the issue, but I already submitted an alternative one, that does.
https://github.com/liferay-core-infra/liferay-portal/pull/2862

Maybe the functional test you wrote could be applied to that solution.

Please let me know what you think.

Best regards,
István

**Comment by Kvale1733** [comment]
No regressions.

**Comment by tinatian** [comment]
@Kvale1733 Could you please check @IstvanD 's comment https://github.com/liferay-core-infra/liferay-portal/pull/2958#issuecomment-1375541463, why your test did not catch it?

Tina

**Comment by tinatian** [comment]
@yuhai Please help me to figure out a way to fix this on windows, I do not like PathUtil.toUnixPath() István suggested.

Also, in my fix, I only address the issue on getFileLastModified, but we have similar logic in updateFileLastModified, please fix it too.

Thanks.
Tina.

**Comment by Kvale1733** [comment]
@tinatian It doesn't look like we run any tests on Windows on CI. Most tests run on CentOS.

**Pull request closed without merging**
