### PR TITLE
[Component with its own class name as service type] LPS-193669 Refactor SummaryStatistics component

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Related: https://liferay.atlassian.net/browse/LPS-193669

### CODE REVIEW

**Review by MrJohn1911 — APPROVED** [review]

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@Valmir-unicap No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139792

**Pull request closed without merging**
