### PR TITLE
LPP-46001 > LPS-158806 When sending an invalid redirect query parameter during password reset, the password is included in the response

### PR DESCRIPTION
**Pull request by julschong**
@tinatian 
Hi Tina,
I added 2 commits after #1260
Removing usages of below in PortalImpl 
> ActionRequest#getParameterValues
> ActionRequest#getParameterNames
> ActionResponse#getRenderParameterMap
> ActionResponse#setRenderParameter

Use MutableRenderParameter and RenderParameter instead.

Then, changed unit test accordingly

### CODE REVIEW

**Comment by tinatian** [comment]
@julschong Code looks good to me. Wait for QA to scan test results.
@catarineaguiar Please help me scan test results.

Tina

**Comment by catarineaguiar** [comment]
@julschong @tinatian no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121959

**Pull request closed without merging**
