### PR TITLE
[Remove Immediate] LPS-188559 Remove immediate property from DLProcessorRegistryImpl

### PR DESCRIPTION
**Pull request by MrJohn1911**
Previous pull: https://github.com/liferay-core-infra/liferay-portal/pull/6206

Ticket: https://liferay.atlassian.net/browse/LPS-188559

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:document

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
Hey @dantewang as the change on this pr compared to the last one sent to BCHan is just a package move, I'm forwarding it. Thx
 
BChan change request: https://github.com/brianchandotcom/liferay-portal/pull/144239#issuecomment-1824304964

//cc @tinatian

**Pull request closed without merging**
