### PR TITLE
[Method References 2] LPS-164347 Remove unused reference variable in module saml-opensaml-integration(dxp)

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have fix the test.

Detial: https://github.com/liferay-core-infra/liferay-portal/pull/1995

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @catarineaguiar , Could you please help me check the test results ? Thanks!

**Comment by dantewang** [comment]
@W2jx For `DefaultUserResolver` you wrote the wrong ticket in the commit message, should be LPS-123218.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:saml

**Comment by dantewang** [comment]
@W2jx Triggered ci-test-saml. Please force push after this run finishes.

**Comment by W2jx** [comment]
Force-Push is just to modify commit message.

**Comment by zhangyan0701** [comment]
No related failures in ci:test:saml.

**Comment by dantewang** [comment]
The `_openSamlBootstrap` one looks suspicious -- the class seems to be configuring OpenSaml, while the `OpenSamlBootstrap` seems to be starting OpenSaml. It's unclear that whether the order matters since it's third-party lib. Asked people in charge of saml to take a look.

**Comment by stian-sigvartsen** [comment]
@dantewang Yes `@Reference OpenSamlBootstrap` is critical to overlay a secure OpenSAML configuration on top of the library's defaults which is set into static fields.

`OpenSamlBootstrap` orchestrates the basic default initialization of the library. Which then gets overridden in some parts and amalgamated in other parts to harden OpenSAML for DXP.

I doubt this dependency has much impact on DXP startup performance (probably improves it actually) because only SAML modules @Reference the service. It is not exported.

**Comment by W2jx** [comment]
Thank you, @stian-sigvartsen .

**Comment by dantewang** [comment]
@stian-sigvartsen Thank you! 
@W2jx Please record this ref and resend without it.

**Pull request closed without merging**
