### PR TITLE
[Components with more than 1 service] LPS-179756 Refactor ScreenNavigationCategory components from Commerce modules part 6

### PR DESCRIPTION
**Pull request by daiazius**
Related pull: https://github.com/liferay-core-infra/liferay-portal/pull/4043
Issue: https://issues.liferay.com/browse/LPS-179756

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
