### PR TITLE
[TS] LPP-47525 > LPS-171662 Update logic updateOAuthClientEntry function

### PR DESCRIPTION
**Pull request by TaiPhamLR**
Dear team,
This PR is for ticket https://issues.liferay.com/browse/LPS-171662 that pass my review. Please help us review it.
Thanks a lot.
cc  @sontruongces

### CODE REVIEW

**Comment by zhangyan0701** [comment]
No regressions found in relevant tests, but there is SF failure in OpenIdConnectProviderManagedServiceFactory.java:
```
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Avoid chaining on method 'get', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/chaining_check.markdown: ./modules/apps/portal-security-sso/portal-security-sso-openid-connect-impl/src/main/java/com/liferay/portal/security/sso/openid/connect/internal/configuration/admin/service/OpenIdConnectProviderManagedServiceFactory.java 493 (Checkstyle:ChainingCheck)
```

**Comment by sontruongces** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
@TaiPhamLR, the fix looks belong to liferay-appsec team. Please send it to the user liferay-appsec to review.

**Comment by yuhai** [comment]
ci:stop

**Pull request closed without merging**
