### PR TITLE
[Remove Stream/Optional usage] LPS-171834 headless PART|2

### PR DESCRIPTION
**Pull request by JanisZhang**
Remove usages of Stream on Method Return Value for module: `headless` PART 2.

https://issues.liferay.com/browse/LPS-171834

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
I don't know why Semantic versioning is incorrect

**Comment by Kvale1733** [comment]
@JanisZhang No regressions. Just the semver issue which you already noticed.
```
     [exec] > Task :apps:headless:headless-delivery:headless-delivery-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec]   com.liferay.headless.delivery.dto.v1_0             UNCHANGED  32.0.0     31.3.0     31.3.0     EXCESSIVE VERSION INCREASE
     [exec] 	-   version    31.3.0
     [exec] 	+   version    32.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.headless.delivery.api-47.0.0.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.headless.delivery.api/46.3.0/c24623abb04ab92e2bdcb5f7179cabc3b50538aa/com.liferay.headless.delivery.api-46.3.0.jar
```
[Log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-32/test-portal-acceptance-pullrequest(master)/7646/rest-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
@JanisZhang I'm not sure which version it's supposed to be but it means you're increasing it too much I think?

**Comment by yuhai** [comment]
@JanisZhang, as we talked, you will resend it.

**Pull request closed without merging**
