### PR TITLE
[TS] LPS-197573 Set id to portlet stored in map.

### PR DESCRIPTION
**Pull request by DaneszLR**
Original PR: https://github.com/liferay-core-infra/liferay-portal/pull/5822

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@DaneszLR No regressions found. Testing passed following the ticket steps.

**Comment by yuhai** [comment]
Hi @DaneszLR,

I talked this with @dantewang,  we think the portlet of the `_portletsMap` and portlet table data of database inconsistent are expected behavior. The `_portletsMap` saved portlet description infos. You may check `PortletImpl`. We don't save all properties/fields of `PortletImpl` to the database. We also can see the roles column of portlet table are null and this is also different from `_portletsMap`. We used the roles during the deploy process. And then we saved null for the roles column to database. For portlet's delete/update, we use **portletId and companyId**. We didn't use the id column.

We want to understand the customer's requirement. Could you please ask why did the customer want to get Ids?

Thanks,
Hai

**Comment by dantewang** [comment]
@DaneszLR Closing this PR as per Hai's comment. We can have a discussion in core-infra's Slack channel if the customer insists to fix the id.

**Pull request closed without merging**
