### PR TITLE
[Remove usage of Stream/Optional] Phase 1 | LPS-172879 adaptive-media-api + adaptive-media-image-impl, part 1

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
@slnn No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
