### PR TITLE
LPS-190886

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**
https://liferay.atlassian.net/browse/LPS-190886

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found.

Bug is not reproducible

**Comment by tinatian** [comment]
@marianoalvarosaiz 
Generally for changes like this touching very low level core framework implementation, please always add enough tests to cover the changes you made.

For https://github.com/liferay-core-infra/liferay-portal/pull/5050/commits/6a49c4bb42bacef33e7e2647fd561413325aa6f7, I do not understand what is "listener removing caches"

For https://github.com/liferay-core-infra/liferay-portal/pull/5050/commits/f38214e9f30d6fa41e9e1c26f9cc46e1de8d3d6e, I do not understand what you did. We need to first discuss what kind of behavior we would like when you change cache configuration when db partition enabled. 
For a specific customer, do you allow to change cache configuration for a specific company?
For a admin, do you allow to change the cache configuration for all the companies without any notice to other company?

Currently, we did not consider these questions while adding shared cache, but we need to have a clean picture what the expected behavior makes more sense.

You can discuss with Alberto first, or maybe include Dave and me.

I am going to close this pull.

Thanks.
Tina.

**Comment by marianoalvarosaiz** [comment]
@tinatian ok, I will add some tests.

https://github.com/liferay-core-infra/liferay-portal/commit/6a49c4bb42bacef33e7e2647fd561413325aa6f7 FinderCacheImpl implements PortalCacheManagerListener and when the FinderCache gets removed then the EntityCache is notified and removed. So, as the code is right now if we override the configuration for a same class of the EntyCache and FinderCache if for example the reconfiguration of EntityCache happens first it will remove the FinderCache new configuration.

https://github.com/liferay-core-infra/liferay-portal/commit/f38214e9f30d6fa41e9e1c26f9cc46e1de8d3d6e I understand. Configuration changes, right now, are applied on restart. So a change make in the configuration will be applied to each company. So I didn't create a new pattern, I followed the same behaviour of the start. What I do is to remove all the sharded caches so that when they are recreated they will be recreated cloning the non sharded configuration (that is how is working on restarts).

**Comment by tinatian** [comment]
For https://github.com/liferay-core-infra/liferay-portal/commit/6a49c4bb42bacef33e7e2647fd561413325aa6f7, please provide a test to expose the issue or at least reproduce steps to show the issue you saw.

For https://github.com/liferay-core-infra/liferay-portal/commit/f38214e9f30d6fa41e9e1c26f9cc46e1de8d3d6e, if "Configuration changes, right now, are applied on restart.", then a restart means you should not have any left over caches related to that., then why you need to clear the sharded caches?

Please always provide test or reproduce steps to show me your issue, sometime it is more easier to understand compared to words.

Tina.

**Pull request closed without merging**
