### PR TITLE
LPS-143632 Remove LanguageUtil from moduels part 2c mixed

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by vicnate5** [comment]
@julschong No regressions found.

**Comment by julschong** [comment]
@slnn 
Hi Lily,

Could you please help me review this pull?

Thank you!

**Comment by slnn** [comment]
Hi @tinatian 

I have checked the change in this pull, and no problem is found.

Lily

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Pull request closed without merging**
