### PR TITLE
LPS-170710 Remove unused deprecated classes in package com.liferay.portal.search.buffer(module portal-search-api)

### PR DESCRIPTION
**Pull request by W2jx**
Hi @dantewang , I have removed the whole com.liferay.portal.search.buffer package.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/2663

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(12/9 9:39)

**Comment by W2jx** [comment]
Force-Push is just to resolve conflict about file `modules/apps/portal-search/portal-search-api/bnd.bnd`

**Comment by dantewang** [comment]
ci:forward

@shuyangzhou @tinatian This pull only removes some deprecated classes that are no longer used by anyone. Since it passed QA, I'm going to forward it.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
no conflicts(12/13 9:46)

**Comment by W2jx** [comment]
no conflicts(12/13 9:55)

**Comment by W2jx** [comment]
no conflicts(2022/12/14 9:39)

**Comment by W2jx** [comment]
no conflicts(12/15 9:25)

**Comment by W2jx** [comment]
no conflicts(2022/12/16 8:57)

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
