### PR TITLE
[Components with more than 1 service] LPS-175708 Refactor Portlet components with more than 1 service type from Commerce

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**
Ticket: [https://issues.liferay.com/browse/LPS-175708](https://issues.liferay.com/browse/LPS-175708)

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:startup

**Comment by GabrielHenriquedev** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
@GabrielHenriquedev No regressions found.

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
