### PR TITLE
[Spring Beans] LPS-203925 Merge portal-impl LayoutSetModelListener logic into layout-impl LayoutSetModelListener

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:echo

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@W2jx https://github.com/liferay-core-infra/liferay-portal/pull/6325/commits/245b305c31380bf85c2efc731b82613740b7e8d1 is this related to one of your changes? Please send a sem ver update to Brian using that ticket number, thanks!

**Comment by W2jx** [comment]
Hi @dantewang , The [commit](https://github.com/brianchandotcom/liferay-portal/pull/145168/commits/557909f56101ded2417127c9fc0bf0da9f49b88b) about this sem ver has been merged, but it has been modified again in task [LPS-203868](https://liferay.atlassian.net/browse/LPS-203868). I will resend a new PR.

**Comment by W2jx** [comment]
Hi @dantewang , I have sent it to Brian https://github.com/brianchandotcom/liferay-portal/pull/145296.

**Comment by dantewang** [comment]
@W2jx Can you confirm that the change is really necessary? In my recent `ant all` I didn't see that package's version being bumped.

**Comment by W2jx** [comment]
Hi @dantewang , This change is necessary. I run` ant all`  under the latest master branch, and there will be package's versions need to be changed.

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
Holding this one, since it will conflict with https://github.com/brianchandotcom/liferay-portal/pull/145490

**Comment by julschong** [comment]
rebased and resolved conflict in spring xml

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
