### PR TITLE
[Remove Blocking usages]LPS-193319 portal-kernel | WorkflowDefinitionManagerUtil 

### PR DESCRIPTION
**Pull request by JanisZhang**
Code conflicts, resend. thanks!
previous: https://github.com/liferay-core-infra/liferay-portal/pull/5287

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@JanisZhang LGTM, please also move `WorkflowDefinitionManager` to workflow-api module.

**Pull request closed without merging**
