### PR TITLE
LPS-196488 Add en_CA locale support

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang

### CODE REVIEW

**Comment by dantewang** [comment]
cc @brunofalc

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:tet:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:stable

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
