### PR TITLE
[Remove Stream/Optional usage:analytics]Lps 171993

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-171993

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@slnn semver error:

```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/content-dashboard/content-dashboard-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.content.dashboard.info.item            MAJOR      1.0.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.content.dashboard.info.item.ClassNameClassPKInfoItemIdentifier
     [exec]     		+   method     getVersion()
     [exec]     			+   return     java.lang.String
     [exec]     		-   method     getVersionOptional()
     [exec]     			-   return     java.util.Optional
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 7.0.0
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-34/test-portal-acceptance-pullrequest(master)/3400/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
    [exec] com.liferay.journal.service.test.JournalArticleServiceTest > testFetchLatestArticleByApprovedStatusWhenArticleApproved FAILED
     [exec]     org.junit.ComparisonFailure: expected:<Version [2]> but was:<Version [1]>
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:117)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
     [exec]     	at com.liferay.journal.service.test.JournalArticleServiceTest.testFetchLatestArticleByApprovedStatusWhenArticleApproved(JournalArticleServiceTest.java:265)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-34/test-portal-acceptance-pullrequest(master)/3400/modules-integration-mysql57-jdk8/0/7/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
Thank @catarineaguiar for catching this, fix and forced push

> @slnn semver error:
> 
> ```
>      [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/content-dashboard/content-dashboard-api] FAILED
>      [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
>      [exec]     = ================================================== ========== ========== ========== ========== ==========
>      [exec]     * com.liferay.content.dashboard.info.item            MAJOR      1.0.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
>      [exec]     	>   class      com.liferay.content.dashboard.info.item.ClassNameClassPKInfoItemIdentifier
>      [exec]     		+   method     getVersion()
>      [exec]     			+   return     java.lang.String
>      [exec]     		-   method     getVersionOptional()
>      [exec]     			-   return     java.util.Optional
>      [exec]     [Baseline Warning] Bundle Version Change Recommended: 7.0.0
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-34/test-portal-acceptance-pullrequest(master)/3400/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)
> 
> ```
>     [exec] com.liferay.journal.service.test.JournalArticleServiceTest > testFetchLatestArticleByApprovedStatusWhenArticleApproved FAILED
>      [exec]     org.junit.ComparisonFailure: expected:<Version [2]> but was:<Version [1]>
>      [exec]     	at org.junit.Assert.assertEquals(Assert.java:117)
>      [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
>      [exec]     	at com.liferay.journal.service.test.JournalArticleServiceTest.testFetchLatestArticleByApprovedStatusWhenArticleApproved(JournalArticleServiceTest.java:265)
>      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-34/test-portal-acceptance-pullrequest(master)/3400/modules-integration-mysql57-jdk8/0/7/jenkins-console.txt.gz?authuser=0)

**Comment by slnn** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Regressions found:

**1. Clicking Preview in a New Tab in display page template opens a blank page.**
Reproduce steps:
1) Add a Web Content article.
2) Go to Site Admin > Design > Page Templates > Display Page Templates tab, add a new template, select Web Content Article type.
3) Add a Heading fragment, click the fragment, on the left side bar, select element-text, on the right side bar, select Basic Web Content (Default) Source, select Title field.
4) Click the `Preview With` dropdown menu on the top of the page, click Select Other Item. and select the created Web Content article. Assert the title displays in the fragment.
5) Click the ellipsis icon on the top right corner, and select Preview in a New Tab. A new tab of browser tab opens.

Result: the new tab is blank. And NPE error in console:
```
[beanshell] 2023-01-05 05:02:11.381 ERROR [http-nio-8080-exec-8][PortletServlet:117] null
[beanshell] javax.portlet.PortletException: java.lang.NullPointerException
```

Example failed test: [LocalFile.DisplayPageTemplatesWithItemPreview#ViewMappedContentOfPreviewItem](https://testray.liferay.com/home/-/testray/case_results/2150301236)
Full console: https://testray.liferay.com/reports/production/logs/2023-01/test-1-26/test-portal-acceptance-pullrequest(master)/6782/functional-tomcat90-mysql57-jdk8/1/17/jenkins-console.txt.gz?authuser=0

**2. [com.liferay.headless.delivery.resource.v1_0.test.BlogPostingResourceTest](https://testray.liferay.com/home/-/testray/case_results/2150301708) failed.**
Full console: https://testray.liferay.com/reports/production/logs/2023-01/test-1-26/test-portal-acceptance-pullrequest(master)/6782/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0

**3. [com.liferay.headless.delivery.resource.v1_0.test.StructuredContentFolderResourceTest](https://testray.liferay.com/home/-/testray/case_results/2150301778) failed.**
Full console: https://testray.liferay.com/reports/production/logs/2023-01/test-1-26/test-portal-acceptance-pullrequest(master)/6782/modules-integration-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0

**Comment by slnn** [comment]
Fix the previous issue and resend in https://github.com/liferay-core-infra/liferay-portal/pull/2949

**Pull request closed without merging**
