### PR TITLE
LPD-6609 Centralize all portal instances logic into kernel/PortalInstances

### PR DESCRIPTION
**Pull request by achaparro**
@tinatian

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:help

**Comment by tinatian** [comment]
ci:test:license

**Comment by achaparro** [comment]
Closing to check possible options

**Pull request closed without merging**
