### PR TITLE
LPS-180672 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
@tinatian @vicnate5 

Resent from https://github.com/liferay-core-infra/liferay-portal/pull/4208 with fix for the issue mentioned [here](https://github.com/liferay-core-infra/liferay-portal/pull/4208#issuecomment-1505965502)

### CODE REVIEW

**Comment by vicnate5** [comment]
@dantewang

**Comment by vicnate5** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@tinatian @dantewang 

The added commit fixes the issue mentioned in the previous PR. The SF issue is unrelated. No other regressions were found according to the previous tests results. Just needed to rerun stable here to verify the fix for the portal-license-smoke issue.


[portal-license-smoke](https://testray.liferay.com/home/-/testray/case_results/2266768056?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2266767943%26testrayRunId%3D2266768000%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Comment by dantewang** [comment]
ci:test:sf

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/133311

**Pull request closed without merging**
