### PR TITLE
LPS-144549 Remove curvesapi.jar

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by tinatian** [comment]
@koor4356 Please help me scan test results.

Thanks.
Tina.

**Comment by guilhermedcamacho** [comment]
As @koor4356 was out today, I don't know if he will work tomorrow. 
Hey @zhangyan0701 please help us to scan test results. Thanks!

**Comment by zhangyan0701** [comment]
Just started reviewing.

**Comment by zhangyan0701** [comment]
Have checked the results, no regressions found.

**Comment by tinatian** [comment]
@guilhermedcamacho Please see https://github.com/liferay-core-infra/liferay-portal/pull/141.
Please note I did not include this commit https://github.com/liferay-core-infra/liferay-portal/pull/130/commits/28e3f5ca4e7340d5d8d69c34df5fae47c0b0d244, as you did not touch any class in portal kernel, this major version bump can not be caused by you.
In this case, you do not need to include this baseline commit to your pull even if you see it locally on your current branch.
Also, I would like you to send me a following pull about `curvesapi.jar,` there are two modules `compileInclude` this jar, please move it to a common place like what Prax does here https://github.com/liferay-core-infra/liferay-portal/pull/123

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
