### PR TITLE
[UPDATE]LPS-156260

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-156260

/cc @tinatian @dantewang

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
ci:test:acceptance

**Comment by catarineaguiar** [comment]
ci:help

**Comment by catarineaguiar** [comment]
no regressions found on acceptance.

**Comment by dantewang** [comment]
Hi @tinatian, a benchmark side change is waiting for this PR.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Review by tinatian — APPROVED** [review]

**Pull request closed without merging**
