### PR TITLE
Lps 113497 11 12 without login portlet v2

### PR DESCRIPTION
**Pull request by slnn**
Hi @dantewang

Separate the content page part into a single class, also separate these resource file read method into a util class.

/cc @tinatian 

Regards
Lily

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Hi @tinatian, due to some shared ones, like class name models and some counters, the extraction of content page logic does not seem clean, please see the `BaseDataFactory`. I would recommend to forward the https://github.com/liferay-core-infra/liferay-portal/pull/11 and do the extraction or refactoring after some more discussion (we have found some extra challenges regarding `DataFactory` splitting).

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
