### PR TITLE
[Bug Fix]LPS-143418

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
Reviewed the test results so far and regressions look to be fixed, will check full default suite results when they come in.

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This is good to go.

Thanks.
Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/110862

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
