### PR TITLE
[Remove Blocking usages]LPS-200479

### PR DESCRIPTION
**Pull request by JanisZhang**
Replace blocking ServiceProxyFactory with Snapshot in class `SettingsLocatorHelperUtil`. Thanks.
https://liferay.atlassian.net/browse/LPS-200479

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
ci:forward:force 

cc @shuyangzhou

**Pull request closed without merging**
