### PR TITLE
LPS-196204 Merge PortalUUID interface and impl into Util

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Shuyang,

This is for ticket https://liferay.atlassian.net/browse/LPS-196204
Thanks for checking

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by lilylcl** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found, just semver error:

```
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.uuid                     MAJOR      6.2.0      6.2.0      7.0.0      VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.portal.kernel.uuid.PortalUUIDUtil
     [exec] 		-   method     getPortalUUID()
     [exec] 			-   access     static
     [exec] 			-   return     com.liferay.portal.kernel.uuid.PortalUUID
     [exec] 		-   method     setPortalUUID(com.liferay.portal.kernel.uuid.PortalUUID)
     [exec] 			-   return     void
     [exec] 	-   interface  com.liferay.portal.kernel.uuid.PortalUUID
     [exec] 		-   access     abstract
     [exec] 		-   method     fromJsSafeUuid(java.lang.String)
     [exec] 			-   access     abstract
     [exec] 			-   return     java.lang.String
     [exec] 		-   method     generate()
     [exec] 			-   access     abstract
     [exec] 			-   return     java.lang.String
     [exec] 		-   method     generate(byte[])
     [exec] 			-   access     abstract
     [exec] 			-   return     java.lang.String
     [exec] 		-   method     toJsSafeUuid(java.lang.String)
     [exec] 			-   access     abstract
     [exec] 			-   return     java.lang.String
     [exec] [Baseline Report] Mode: diff (persisted)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-09/test-1-32/test-portal-acceptance-pullrequest(master)/2123/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by shuyangzhou** [comment]
@jeffwu0724 https://github.com/liferay-core-infra/liferay-portal/pull/5582/commits/981e73a942775b86314e774a01c6c5c8f830936a this is not ok, talk @vicnate5 to update QA test case to avoid using PortalUUIDImpl. The test is design for spring bean override, now PortalUUIDImpl is no longer a spring bean.

**Comment by vicnate5** [comment]
@jeffwu0724 We need a class in `modules/test/ext-test-impl/` that is overriding a spring bean class from portal-impl

See feature in https://liferay.atlassian.net/browse/LPS-159167

**Comment by julschong** [comment]
@vicnate5 Hi Victor, we are trying to get rid of spring beans one by one here: https://liferay.atlassian.net/browse/LPS-190426. is there any other way so that we can get rid of the usages?

**Comment by vicnate5** [comment]
We discussed this one slack, will update the test under https://liferay.atlassian.net/browse/LRQA-83346

**Pull request closed without merging**
