### PR TITLE
LPS-168749 change compileInclude to compileOnly for org.apache.httpcomponents

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Resent: For the discussion https://github.com/liferay-core-infra/liferay-portal/pull/2477#issuecomment-1322552202, I tried to delete it and run the test, and it will throw error https://github.com/jeffwu0724/liferay-portal/pull/184#issuecomment-1325659433. It is because group: "net.shibboleth.utilities", name: "java-support" has a compiled dependencies on httpclient-cache. Please see [commit](https://github.com/liferay/liferay-portal/commit/7988b387a961dba7ac26ae2b6c9eac9c8c9f778e).
Therefore, in order to keep org.apache.httpcomponents consistent, I will keep httpclient-cache in shared-dependencies at this moment.

This is for ticket https://issues.liferay.com/browse/LPS-168749.
I tried to change compileInclude to compileOnly for org.apache.httpcomponents,because org.apache.httpcomponents has been added to shared-dependencies before.
Thanks for checking!

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@jeffwu0724 semver error:

```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/commerce/commerce-inventory-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.commerce.inventory.exception           MINOR      1.4.0      1.4.0      1.5.0      VERSION INCREASE REQUIRED
```
```
] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/commerce/commerce-price-list-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.commerce.price.list.exception          MINOR      2.4.0      2.4.0      2.5.0      VERSION INCREASE REQUIRED
```
```
[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/commerce/commerce-product-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.commerce.product.exception             MAJOR      9.1.0      9.1.0      10.0.0     VERSION INCREASE REQUIRED
```
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/static/portal-configuration/portal-configuration-persistence-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.portal.configuration.persistence       MINOR      1.1.0      1.1.0      1.2.0      VERSION INCREASE REQUIRED
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-25/test-portal-acceptance-pullrequest(master)/5502/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
fixed code conflict and resend

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found.

**Comment by tinatian** [comment]
@jeffwu0724 You put the adding of "httpclient-cache" to shared dependencies as the first commit, I would suppose it is need by all the commits after that, but actually it is not.

Please do:
1) Make changes about those we already exposed
2) Add the "httpclient-cache" only when necessary, I currently only see one is using it, if that's the case, why we want it to be in the shared dependecies?

**Pull request closed without merging**
