### PR TITLE
LPS-51404 CookieKey returns public domain

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang, 

this is the fix for https://liferay.atlassian.net/browse/LPS-51404, verified ok on my local env.

Referenced the PR: https://github.com/brianchandotcom/liferay-portal/pull/24913

Thanks for the review.

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
@JanisZhang Please send a separate PR to fix tests in https://github.com/liferay-core-infra/liferay-portal/pull/6240/commits/80a78c4321069568448a0a3fde493df2ce113143 under the original ticker number, thanks!

**Comment by dantewang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
waiting for https://github.com/liferay-core-infra/liferay-portal/pull/6243

**Comment by JanisZhang** [comment]
Hi @dantewang, I've force-pushed, thanks!

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Please prioritize this pull, it is for security issue.

Thanks.
Tina

**Comment by Kvale1733** [comment]
@JanisZhang @tinatian 
No regressions found. Manual testing passed.

**Comment by dantewang** [comment]
ci:forward:force

cc @tinatian

**Pull request closed without merging**
