### PR TITLE
LPS-185138

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
ci:test:start

**Comment by tinatian** [comment]
@dantewang @LisztLiszt How to trigger this issue you mentioned?

> After using snapshot for ReleaseManager, there is no reference to ReleaseManagerImpl, it will be called when getting snapshot which is not on time. The avtivate() method of the reference ReleasePublisher won't be executed so the service Release is not registered.

**Comment by dantewang** [comment]
@LisztLiszt Please post the steps, thanks.

**Comment by LisztLiszt** [comment]
@tinatian @dantewang 
1. Create a new MySQL database
2. Import the following 7.4.13 mysql database dump:https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.4.13/data-archive/data-archive-portal-mysql.zip
3. Run the database upgrade tool

Upgrades fail with "missing default store" error.
```
[java] java.lang.IllegalStateException: Missing default Store
     [java] 	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:163) [portal-impl.jar:?]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
     [java] 	at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:54) [com.liferay.portal.tools.db.upgrade.client.jar:?]
     [java] 2023-05-24 07:10:59.227 INFO  [main][UpgradeRecorder:159] Major upgrade finished with result failure
```

[log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-40/test-portal-acceptance-pullrequest(master)/2594/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
@tinatian Regression found. All upgrades fail with "java.lang.IllegalStateException: Missing default Store"

Steps to reproduce: 
1. Import the following 7.4.13 db dump: https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.4.13/data-archive/data-archive-portal-mysql.zip
2. Run the upgrade tool

Expected Results: Upgrade completes without issue
Actual Results: Upgrade fails with 
```
 [java] 2023-07-20 03:23:29.257 ERROR [main][DBUpgrader:79] null
     [java] java.lang.IllegalStateException: Missing default Store
     [java] 	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:163) [portal-impl.jar:?]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
     [java] 	at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:54) [com.liferay.portal.tools.db.upgrade.client.jar:?]
     [java] 2023-07-20 03:23:29.267 INFO  [main][UpgradeRecorder:160] Major upgrade finished with result failure
     [java] 
     [java] Failed Liferay upgrade process in 40 seconds
     [java] Connecting to Gogo shell because the upgrade failed or is incomplete
     [java] 
```
[Log](https://testray.liferay.com/reports/production/logs/2023-07/test-1-34/test-portal-acceptance-pullrequest(master)/4432/functional-upgrade-tomcat90-mysql57-jdk8/3/12/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
@LisztLiszt Similar error as you saw when you use `Snapshot`?

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5064

**Comment by LisztLiszt** [comment]
> @LisztLiszt Similar error as you saw when you use `Snapshot`?

@dantewang Yes, same error

**Pull request closed without merging**
