### PR TITLE
[Method References] LPS-161243 Replace method setSamlProviderConfigurationHelper with variable samlProviderConfigurationHelper in class extends BaseSamlStrutsAction

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have replaced method setSamlProviderConfigurationHelper with variable samlProviderConfigurationHelper and inline the logic inside method isEnabled in this pr.

Detail: https://github.com/liferay-core-infra/liferay-portal/pull/1436

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701, Could you please help me check the test results when they finish ? Thanks!

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
@zhangyan0701 Thank you.

**Comment by W2jx** [comment]
no conflicts(7:10 PM)

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122247

**Pull request closed without merging**
