### PR TITLE
[Remove Spring extender usages] LPS-167593

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, @tinatian, the previous pr is https://github.com/liferay-core-infra/liferay-portal/pull/2329. The pr resolves the semver [error](https://github.com/liferay-core-infra/liferay-portal/pull/2329#issuecomment-1302289848)

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
@yuhai No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126027

**Pull request closed without merging**
