### PR TITLE
[Move Expando]Lps 190836 11 3

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-190836

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
rerun sf test after resolving the conflicts

**Comment by dantewang** [comment]
Plz rearrange commits as we talked, and resend. https://github.com/slnn/liferay-portal/pull/755

**Comment by slnn** [comment]
Resend in https://github.com/liferay-core-infra/liferay-portal/pull/6141

**Pull request closed without merging**
