### PR TITLE
[LPD-28518 Destination] LPD-29126 Move MailMessageListener to module

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:23163349

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:23308480

**Comment by tinatian** [comment]
ci:help

**Comment by tinatian** [comment]
ci:test:core-functional

**Comment by tinatian** [comment]
ci:report:24466077

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/151693

**Comment by tinatian** [comment]
No unique failure found

**Pull request closed without merging**
