### PR TITLE
LPS-145778 Move jai-codec.jar and jai_core.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
Hey @vicante5, Can you help to scan these tests results? Thx

**Comment by vicnate5** [comment]
@kyle-miho can you check this one when you get a chance?

**Comment by kyle-miho** [comment]
failures unrelated, this PR should be good to go

**Comment by tinatian** [comment]
@rafaprax Sprite feature was actually deprecated and disabled by default, also the feature did not work since 7.0, I checked with David to see if we can remove all related code to it to get rid of the third-party dependencies, waiting for response now.

**Comment by tinatian** [comment]
@rafaprax Got response from Dave, let's remove the code. Please resend a pull.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
