### PR TITLE
[Replace Non-Blocking Usage] LPS-199062 portal-kernel

### PR DESCRIPTION
**Pull request by JanisZhang**
https://liferay.atlassian.net/browse/LPS-199062

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142351

**Pull request closed without merging**
