### PR TITLE
LPS-154230 Company Log Servlet

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, @tinatian, the pr is based on https://github.com/liferay-core-infra/liferay-portal/pull/1032

### CODE REVIEW

**Comment by yuhai** [comment]
@zhangyan0701, please help scan the test result. Thanks.

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by Kvale1733** [comment]
Hey @yuhai I'm automating some functional tests for company logs and I noticed a typo. The message that appears when no logs are available is missing an 'l' in "avaiable" in case you aren't aware.

**Comment by yuhai** [comment]
> Hey @yuhai I'm automating some functional tests for company logs and I noticed a typo. The message that appears when no logs are available is missing an 'l' in "avaiable" in case you aren't aware.

Hi @Kvale1733, thanks. If you didn't mention it. I didn't found the typo.

**Pull request closed without merging**
