### PR TITLE
[Spring Beans] LPS-201758 Replace PortletResourcePermissionDefinition with Wrappers for better performance

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
fixed sf issue

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
ci:test:blogs

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by tinatian** [comment]
ci:forward:force

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
