### PR TITLE
[Optional Reference] LPS-185153 Convert the Optional Dynamic Greedy references to static references using Snapshot in class DLDisplayContextProviderImpl

### PR DESCRIPTION
**Pull request by haydenzheng314**
Ticket: https://issues.liferay.com/browse/LPS-185153
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:startup

**Review by dantewang — APPROVED** [review]

**Comment by Kvale1733** [comment]
ci:test:document

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
