### PR TITLE
LPS-172813 Prevent usage of `service.ranking` property in `*ModelResourcePermission` classes

### PR DESCRIPTION
**Pull request by kevhlee**
Closes: <https://issues.liferay.com/browse/LPS-172813>

This pull request implements a SF rule to prevent developers from using `service.ranking` when developing `*ModelResourcePermission` classes. This is to prevent issues like this in the future: <https://liferay.slack.com/archives/C01FP01V5L0/p1673621336554059>.

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
no regressions found.

the unique tests failures on relevant passed on commerce suite.

**Comment by tinatian** [comment]
@kevhlee Same thing as this https://github.com/liferay-core-infra/liferay-portal/pull/3056. Please merge the last two commits into one.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129176

**Pull request closed without merging**
