### PR TITLE
[Components with more than 1 service] LPS-179751 Refactor ScreenNavigationCategory components from Commerce, Echo and Security modules

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-179751](https://issues.liferay.com/browse/LPS-179751)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:help

**Comment by RenanUmV** [comment]
ci:test:commerce

**Comment by RenanUmV** [comment]
ci:test:echo

**Comment by RenanUmV** [comment]
ci:test:security

**Comment by Kvale1733** [comment]
@RenanUmV No regressions, only a semver issue.
```
     [exec] > Task :apps:commerce:commerce-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.commerce.constants                     MINOR      12.5.0     12.5.0     12.6.0     VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.commerce.constants.CommerceTaxScreenNavigationConstants
     [exec] 		+   field      CATEGORY_KEY_COMMERCE_TAX_METHOD_AVALARA
     [exec] 			+   access     final
     [exec] 			+   access     static
     [exec] 			+   constant   settings
     [exec] 			+   return     java.lang.String
     [exec] 		+   field      CATEGORY_KEY_COMMERCE_TAX_METHOD_AVALARA_RATE_RELS
     [exec] 			+   access     final
     [exec] 			+   access     static
     [exec] 			+   constant   avalara-tax-rates
     [exec] 			+   return     java.lang.String
     [exec] 		+   field      ENTRY_KEY_COMMERCE_TAX_METHOD_AVALARA
     [exec] 			+   access     final
     [exec] 			+   access     static
     [exec] 			+   constant   settings
     [exec] 			+   return     java.lang.String
     [exec] 		+   field      ENTRY_KEY_COMMERCE_TAX_METHOD_AVALARA_RATE_RELS
     [exec] 			+   access     final
     [exec] 			+   access     static
     [exec] 			+   constant   avalara-tax-rates
     [exec] 			+   return     java.lang.String
     [exec] [Baseline Warning] Bundle Version Change Recommended: 60.1.0
     [exec] [Baseline Report] Mode: diff (persisted)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-03/test-1-32/test-portal-acceptance-pullrequest(master)/8865/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by RenanUmV** [comment]
ci:test:sf

**Pull request closed without merging**
