### PR TITLE
[Remove Stream/Optional usage] LPS-178007 remove_stream_and_optional_in_headless_delivery_api

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Dante,

This is for ticket https://issues.liferay.com/browse/LPS-178007.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
fixed the SF issue and rerun the test

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:headless

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions. Only semver issue.

```
 [exec] 
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/headless/headless-delivery/headless-delivery-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.headless.delivery.dto.v1_0.util        MAJOR      2.0.0      2.0.0      3.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.headless.delivery.dto.v1_0.util.ContentDocumentUtil
     [exec]     		-   method     toContentDocument(com.liferay.document.library.util.DLURLHelper,java.lang.String,com.liferay.portal.kernel.repository.model.FileEntry,java.util.Optional)
     [exec]     			-   access     static
     [exec]     			-   return     com.liferay.headless.delivery.dto.v1_0.ContentDocument
     [exec]     		+   method     toContentDocument(com.liferay.document.library.util.DLURLHelper,java.lang.String,com.liferay.portal.kernel.repository.model.FileEntry,javax.ws.rs.core.UriInfo)
     [exec]     			+   access     static
     [exec]     			+   return     com.liferay.headless.delivery.dto.v1_0.ContentDocument
     [exec]     	>   class      com.liferay.headless.delivery.dto.v1_0.util.ContentValueUtil
     [exec]     		-   method     toContentValue(java.lang.String,com.liferay.petra.function.UnsafeSupplier,java.util.Optional)
     [exec]     			-   access     static
     [exec]     			-   return     java.lang.String
     [exec]     		+   method     toContentValue(java.lang.String,com.liferay.petra.function.UnsafeSupplier,javax.ws.rs.core.UriInfo)
     [exec]     			+   access     static
     [exec]     			+   return     java.lang.String
     [exec]     	>   class      com.liferay.headless.delivery.dto.v1_0.util.CreatorUtil
     [exec]     		-   method     toCreator(com.liferay.portal.kernel.util.Portal,java.util.Optional,com.liferay.portal.kernel.model.User)
     [exec]     			-   access     static
     [exec]     			-   return     com.liferay.headless.delivery.dto.v1_0.Creator
     [exec]     		+   method     toCreator(com.liferay.portal.kernel.util.Portal,javax.ws.rs.core.UriInfo,com.liferay.portal.kernel.model.User)
     [exec]     			+   access     static
     [exec]     			+   return     com.liferay.headless.delivery.dto.v1_0.Creator
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 47.0.0
```
[Log](https://testray.liferay.com/reports/production/logs/2023-03/test-1-37/test-portal-acceptance-pullrequest(master)/9706/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by jeffwu0724** [comment]
force push with baseline, no need to retrigger the test

**Comment by dantewang** [comment]
Conflicts, please resend.

**Pull request closed without merging**
