### PR TITLE
LPS-167148 Remove "immediate = true" from Echo components part 2

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://issues.liferay.com/browse/LPS-167148

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
@rafaprax no regressions found.

**Comment by rafaprax** [comment]
Hey @shuyangzhou, this pr is ready for your review. Thx

**Comment by rafaprax** [comment]
Hey all, I'm rerunning the test suites because I added more classes to this batch.

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
@rafaprax No regressions found.

**Comment by tinatian** [comment]
@rafaprax I do not think this com.liferay.journal.web.internal.messaging.CheckArticleMessageListener should be removed, as it is also a message listener registering scheduler jobs.

I cherry picked several commits from this pull, please see https://github.com/liferay-core-infra/liferay-portal/pull/2715. For others, please resend.

Thanks.
Tina

**Pull request closed without merging**
