### PR TITLE
LPS-151217

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This is for https://issues.liferay.com/browse/LPS-151217. 
I have changed the defaults for "http.header.version.verbosity" to partial.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result, please?

Thanks
Jeff

**Comment by catarineaguiar** [comment]
@jeffwu0724 no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
