### PR TITLE
[Optional Reference]LPS-198645  module: document-library-service

### PR DESCRIPTION
**Pull request by JanisZhang**
Convert the Optional references to Snapshot in class `CleanUpStoreAreasSchedulerJobConfiguration`
https://liferay.atlassian.net/browse/LPS-198645

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:document

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
