### PR TITLE
LPS-147093

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian , @shuyangzhou,

I try to fix the bug for **Com.google.protobuf:**, see https://issues.liferay.com/browse/LPS-147093
**compileInclude**:
modules/apps/portal-store/portal-store-gcs/build.gradle - change from 3.15.6 to 3.16.1
modules/dxp/apps/portal-rules-engine-drools/portal-rules-engine-drools/build.gradle - already using version 3.16.1
**compile**: 
modules/third-party/org-drools-core/build.gradle - keep using 2.4.1 since org-drools-core is till 5.4 final
Thanks for checking.

Thanks,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@kyle-miho Hey Kyle, could you please help me to scan the test result?

Thanks,
Jeff

**Comment by kyle-miho** [comment]
@jeffwu0724 this pr looks good to go

**Comment by tinatian** [comment]
@jeffwu0724 Please update your commit message, you have the ticket number duplicated "[LPS-147093 - LPS-147093](https://github.com/liferay-core-infra/liferay-portal/pull/360/commits/50ddb1f71c4b6f530e0933bb7a47ea19f26f75e8)"

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113984

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
