### PR TITLE
LPS-158311 refactor2 | rebased

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Updated sem ver

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian This PR rebases https://github.com/liferay-core-infra/liferay-portal/pull/2252

**Comment by Kvale1733** [comment]
@dantewang No regressions found.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@tinatian Force pushed to only resolve sem ver conflict (portal-kernel/bnd.bnd).

**Comment by catarineaguiar** [comment]
@dantewang no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Pull request closed without merging**
