### PR TITLE
LPS-173369 Remove Optional from module: portal-search-web-api part 1

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from https://github.com/liferay-core-infra/liferay-portal/pull/3183
Corrected compile error
https://github.com/liferay-core-infra/liferay-portal/pull/3183#issuecomment-1407128602

### CODE REVIEW

**Comment by julschong** [comment]
ci:stop

**Comment by julschong** [comment]
pushed baseline

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:search

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129731

**Pull request closed without merging**
