### PR TITLE
[Components with more than 1 service] LPS-179751 Refactor ScreenNavigationCategory components from Echo and Security modules

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-179751](https://issues.liferay.com/browse/LPS-179751)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:echo

**Comment by RenanUmV** [comment]
ci:test:security

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@RenanUmV The commit message of [the last commit](https://github.com/liferay-core-infra/liferay-portal/pull/4226/commits/180d6786cb38a389fba5e4c0bf232d822f7f3107) mentions `MFASetupUserAccountScreenNavigationEntry`, but the commit doesn't change that class. Please update the commit message, thanks!

**Comment by RenanUmV** [comment]
sorry @dantewang , I made the changes and forgot to edit the commit message

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
