### PR TITLE
[Replace Non-Blocking Usage] LPS-199418

### PR DESCRIPTION
**Pull request by JanisZhang**
resent:https://github.com/liferay-core-infra/liferay-portal/pull/5829, thanks!
https://liferay.atlassian.net/browse/LPS-199418

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
Run additional startup test

**Comment by catarineaguiar** [comment]
no regressions

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
