### PR TITLE
[TS] LPS-142380 7-22

### PR DESCRIPTION
**Pull request by dantewang**
@crodriguezy I made some changes based on https://github.com/liferay-core-infra/liferay-portal/pull/1142 by removing the validation from the portlet and making the portlet call the 2-in-1 method which is protected by the LocalService's validation logic.

I tested on my local: the error message is shown when I don't type in the default text, and no error when I type the default text and submit again.

### CODE REVIEW

**Comment by dantewang** [comment]
@crodriguezy I see. In `com.liferay.portlet.expando.model.impl.ExpandoBridgeImpl#setAttributeDefault`, it catches the `ValueDataException$MustInformDefaultLocale` and rethrows it using a `RuntimeException`. I don't understand why the API is designed to be like this -- the `addAttribute` methods throw `PortalException` while the `setAttribute*` methods don't throw any exception. It's inconsistent.

Maybe using `ReflectionUtil.throwException(exception)` instead of `throw new RuntimeException(exception)` can make the error message show up on the UI, but I would prefer changing these methods to add `throws PortalException` in their signatures.

**Comment by dantewang** [comment]
@crodriguezy Could you check if the `ReflectionUtil.throwException` trick resolves the UI issue?

It seems a lot of callers of these methods doesn't handle exception at all, so it would be a lot of work to change the method signatures.

**Comment by crodriguezy** [comment]
Hi @dantewang , I realized of the inconsistency in the API. In git history I read it was added to be able to handle any exceptions and perform the rollback, so I didn't want to change it. That's why I kept the logic in the portlet also.

I'm compiling your PR with the change you mentioned in setAttributeDefault. Do I need to change it somewhere else?

**Comment by dantewang** [comment]
@crodriguezy For testing purpose just this method, as it's used by the portlet. I'll apply to other places if it works.

**Comment by dantewang** [comment]
@crodriguezy 

> it was added to be able to handle any exceptions and perform the rollback

It sounds weird to me though...

**Comment by crodriguezy** [comment]
Hi @dantewang , it seems the ReflectionUtil change works. The error is always shown in the UI, when adding and updating the field

**Comment by dantewang** [comment]
@crodriguezy I'll close this pull and look more into it and resend next week.

**Comment by crodriguezy** [comment]
Hi @dantewang , any update about this? Did you finally resent a new PR?
Thanks

**Comment by dantewang** [comment]
@crodriguezy Yes, I forgot to reply here. See https://github.com/liferay-core-infra/liferay-portal/pull/1158

**Pull request closed without merging**
