### PR TITLE
Lps 113497 11 12 without login portlet

### PR DESCRIPTION
**Pull request by slnn**
Hi @dantewang @tinatian

This pull is the changes that switch the SampleSQLBuilder generated home page into the content page and remove the login portlet from the home page.

Benchmark side changes please see: https://github.com/dantewang/liferay-benchmark-ee/pull/525

By the way,  some hard-coding JSON files still exist here, but SampleSQLBuilder had kept many JSON files for DL, Journal and Fragment which also came from DB dump as we did in this pull. So could we remove these JSON files together in the later refactor of SampleSQLBuilder?

Regards
Lily

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:close

**Comment by tinatian** [comment]
ci:open

**Comment by tinatian** [comment]
@shuyangzhou This is ready to go.

Tina

**Comment by tinatian** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
