### PR TITLE
LPS-172424 Remove Stream for module: portal-search-slasticsearch7-impl part 1

### PR DESCRIPTION
**Pull request by julschong**
#2997 
fixed test failure in `DefaultElasticsearchDocumentFactoryTest`
issue was TransformUtil.transformToArray() does not include null values, using simple for loop instead

split into 2 parts, this is part 1

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by julschong** [comment]
> @julschong Unfortunately 173 search tests are failing due to an unrelated search issue so analysis is very limited for search tests. I've let the search team know about the issue.

let's wait until their test is fixed to be safe

**Comment by Kvale1733** [comment]
The search team sent a PR yesterday. Just needs to be merged by BChan: https://github.com/brianchandotcom/liferay-portal/pull/128721

**Comment by catarineaguiar** [comment]
Waiting for https://github.com/brianchandotcom/liferay-portal/pull/128770 to be merged.

**Comment by catarineaguiar** [comment]
@julschong can you rebase and re-run tests suites, please?

Thanks, Cat.

**Comment by julschong** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:search

**Pull request closed without merging**
