### PR TITLE
[Components with more than 1 service] LPS-190897 Refactor AMImageProcessorImpl component

### PR DESCRIPTION
**Pull request by Valmir-unicap**
Related: https://liferay.atlassian.net/browse/LPS-190897

Here is the thread about unifying the AMImageProcessor and AMProcessor interfaces: https://liferay.slack.com/archives/CLD39UKM5/p1689884709714769

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Valmir-unicap** [comment]
ci:test:lima

**Comment by Valmir-unicap** [comment]
ci:test:headless

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Valmir-unicap** [comment]
ci:test:lima

**Comment by Valmir-unicap** [comment]
ci:test:headless

**Review by rafaprax — APPROVED** [review]

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@Valmir-unicap @rafaprax A commit like this is really hard to review https://github.com/liferay-core-infra/liferay-portal/pull/5078/commits/843e7dc66a2a2eadc23bf2e13cb5d7371900e36b.

Please try your best to separate the logic.

Please resend.

Thanks.
Tina

**Pull request closed without merging**
