### PR TITLE
[Remove Stream/Optional usage] LPS-174296 Remove usages of Stream for module: saml-test

### PR DESCRIPTION
**Pull request by W2jx**
Hi @dantewang , I have modified the use of StringBundler.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3246

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:saml

**Comment by W2jx** [comment]
no conflicts(2/3 8:29)

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

**Comment by dantewang** [comment]
cc @shuyangzhou @tinatian

**Pull request closed without merging**
