### PR TITLE
LPS-150565 Add configuration values

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, resending https://github.com/liferay-core-infra/liferay-portal/pull/2521

cc @vendeltoreki

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@yuhai no regressions found.

**Comment by yuhai** [comment]
@dantewang, I removed the Modified commit. Will trigger ci test again.

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@yuhai rebase please. Thanks

**Comment by dantewang** [comment]
Rebased at https://github.com/liferay-core-infra/liferay-portal/pull/2554

**Pull request closed without merging**
