### PR TITLE
LPS-150171 Move CalendarFactoryImpl logic into kernel

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Possible regression:
[com.liferay.portal.search.web.internal.modified.facet.builder.ModifiedFacetBuilderTest](https://testray.liferay.com/home/-/testray/case_results/2113481988) failed with error:

`testBuiltInNamedRange: org.junit.ComparisonFailure: expected:<20[180228151923]> but was:<20[221208003612]>`

Full console log:
https://testray.liferay.com/reports/production/logs/2022-12/test-1-26/test-portal-acceptance-pullrequest(master)/6301/modules-unit-jdk8/0/2/jenkins-console.txt.gz?authuser=0

**Comment by julschong** [comment]
push to fix unit test `ModifiedFacetBuilderTest`
Use MockStatic to set a fixed Date on CalendarFactory.getCalendar()

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:calendar

**Comment by Kvale1733** [comment]
@julschong Regression found

Cannot access calendar widget permissions

Steps to reproduce:
      i. Add calendar widget to page
      ii. While still in page edit mode click on the ellipses at the top right of the widget
      iii. Click Permissions
      
Expected Results: Can Access calendar permissions
Actual Results: The permissions don't load and an error message appears. "Unable to dispatch request: java.lang.NullPointerException" also appears in the console. 

[Log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-32/test-portal-acceptance-pullrequest(master)/7359/functional-tomcat90-mysql57-jdk8/0/15/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
resubmit

**Pull request closed without merging**
