### PR TITLE
LPS-199470 Merge SiteMembershipPolicyFactoryUtil into SiteMembershipPolicyUtil

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Shuyang,

This is for ticket https://liferay.atlassian.net/browse/LPS-199470.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Review by dantewang — CHANGES_REQUESTED** [review]
@jeffwu0724 Please document breaking changes.

**Comment by jeffwu0724** [comment]
upgraded the commit message with breaking change info

**Comment by catarineaguiar** [comment]
@jeffwu0724 formatting issue:

```
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/security/membershippolicy/SiteMembershipPolicyUtil.java expected:<...opyrightText: (c) 20[23] Liferay, Inc. https...> but was:<...opyrightText: (c) 20[00] Liferay, Inc. https...>
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:458)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:291)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-27/test-portal-source-format/5883/source-format-current-branch-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
