### PR TITLE
LPS-136334 The widget crashes when changing the filter with "downloads" in DM management toolbar

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:test:sf

**Comment by stsquared99** [comment]
ci:test

**Comment by stsquared99** [comment]
ci:test:sf

**Comment by stsquared99** [comment]
ci:test

**Comment by tinatian** [comment]
@stsquared99 After your changes, some of the constants are not used any more, could you remove those constants and its corresponding definition in customer.sql? If there is a major version bump caused by the removal, please deprecate them instead:
`	public static final String COUNT_BY_G_F =
		DLFileEntryFinder.class.getName() + ".countByG_F";

	public static final String COUNT_BY_G_M_R =
		DLFileEntryFinder.class.getName() + ".countByG_M_R";

	public static final String COUNT_BY_G_U_F =
		DLFileEntryFinder.class.getName() + ".countByG_U_F";`

**Pull request closed without merging**
