### PR TITLE
[Blocker] LPS-203250 Revert lazy initialization for GraphQLServletExtender service tracker list initialization

### PR DESCRIPTION
**Pull request by rcsdnj**
When implementing the [refactor](https://github.com/liferay-core-infra/liferay-portal/pull/6086) described in [this task (a component with its own class name as service type)](https://liferay.atlassian.net/browse/LPS-200508), we adjusted one of the GraphQLServletExtender's service tracker to use lazy initialization (using a ServiceTrackerListFactory). Unfortunately, this introduced [this bug](https://liferay.atlassian.net/browse/LPS-203250) because other parts of the class were counting with the service tracker being already open, which couldn't be seen clearly in the code before.

Extending the ServiceTrackerCustomizer makes the behavior to come back to normal.

### CODE REVIEW

**Comment by rcsdnj** [comment]
ci:test:sf

**Comment by rcsdnj** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@rafaprax Changes look good to me, please forward once it passed test scan.

Thanks.
Tina

**Comment by kyle-miho** [comment]
@rafaprax @tinatian no related failures found, PR is good to go

**Comment by rafaprax** [comment]
ci:forward:force

**Comment by rafaprax** [comment]
ci:forward:force

**Pull request closed without merging**
