### PR TITLE
LPS-174215 Remove Stream usages from module: account-service

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
combined the fetching organizations logic with literator with getOrganizationId logic together into 1 for loop

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:account

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward

**Comment by dantewang** [comment]
cc @shuyangzhou @tinatian

**Pull request closed without merging**
