### PR TITLE
LPD-20946 Resource Actions | 6-11

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:report:15522018

**Comment by dantewang** [comment]
@JerryAdrianoo Please run a startup time and profile comparison for this PR, thanks!

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:report:15593808

**Comment by dantewang** [comment]
ci:report:15590776

**Comment by JerryAdrianoo** [comment]
Hey @dantewang, I put the results on the second page of the same older [Spreadsheet](https://docs.google.com/spreadsheets/d/1Ox1PV9BUQxBQghTookJheqqxoxxODx6d-boUuUjoF1E/edit#gid=451588062)
The increase in the **Open File Number** column is a flaky case. I didn't rerun it but it happened in the past in our startup  daily tests
Feel free to let me know if you need anything else.

**Comment by dantewang** [comment]
@JerryAdrianoo Thanks!

**Comment by dantewang** [comment]
Hi @tinatian I rebased and force-pushed. The conflict was due to a rename SF with the revert, so I manually applied the revert.

**Pull request closed without merging**
