### PR TITLE
[Remove Spring extender usages] LPS-159581

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on the requirement from https://github.com/liferay-core-infra/liferay-portal/pull/1713#issuecomment-1249140391

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:commerce

**Comment by yuhai** [comment]
@zhangyan0701, please help check the test result after ci test finish. Thanks.

**Comment by dantewang** [comment]
@yuhai SemVer error, please push and rerun.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/1869

**Pull request closed without merging**
