### PR TITLE
[Method References 2] LPS-169905 Convert method reference to ServiceTrackerMap in classes AccountRoleRequestHelper

### PR DESCRIPTION
**Pull request by W2jx**
I've confirmed with Pei-Jung Lan that the list of class PersonalMenuEntry in class AccountRoleRequestHelper is only used to retrieve a resource’s action name, so sorting is not necessary.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3411

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:account

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by W2jx** [comment]
no conflicts(2/24 9:47)

**Comment by W2jx** [comment]
no conflicts(2/27 8:30)

**Comment by W2jx** [comment]
no conflicts(2/28 9:45)

**Comment by W2jx** [comment]
no conflicts(3/1 10:45)

**Comment by tinatian** [comment]
@W2jx You are still having two service tracker for PersonalMenuEntry. Can you make it into one?

**Comment by tinatian** [comment]
@W2jx 

It took me some efforts to understand these two commits : [LPS-169905 Add new interface PersonalMenuEntryRegistry and class PersonalMenuEntryRegistryImpl](https://github.com/liferay-core-infra/liferay-portal/pull/3595/commits/1376f207ce56fd0108ff9a9fc23453873531bcb7)  and https://github.com/liferay-core-infra/liferay-portal/pull/3595/commits/68cd0365084b157069a7e269065f33e4d5c3dd4f.

Basically, what you did is to extract the logic inside RolesAdminPortlet to a common place, then apply it to AccountRoleRequestHelper.  

If you create commits to extract first, then apply, it would be very clear where the logic of PersonalMenuEntryRegistryImpl come from.

To review your pull, I have to manually compare two files from two commits, which is hard. This is not a complex class, I finally figured it out though took me some efforts. If this is a big complex class, I will for sure ask for a resend because of this.

**Comment by tinatian** [comment]
@W2jx Please see my comments and resend.

Thanks.
Tina

**Pull request closed without merging**
