### PR TITLE
LPS-166543 Remove "immediate = true" from Others

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@RenanUmV semver error:

```
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.xstream.configurator.api-6.0.6.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.xstream.configurator.api/6.0.5/1f3fb51a37c76fa9a21720d485983cdda1c03a40/com.liferay.xstream.configurator.api-6.0.5.jar
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-29/test-portal-acceptance-pullrequest(master)/5176/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
All tests passed.

cc/ @zhangyan0701

**Comment by RenanUmV** [comment]
Hey @shuyangzhou , this one is good to go!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125227

**Pull request closed without merging**
