### PR TITLE
[Spring Beans] LPS-202459 Move PrefsPropsImpl into module

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Review by dantewang — CHANGES_REQUESTED** [review]
@W2jx Major version bump, please record breaking change.

**Comment by W2jx** [comment]
Hi @dantewang , I have added breaking change.

**Comment by W2jx** [comment]
no conflicts(11/24 15:34)

**Comment by W2jx** [comment]
no conflicts(11/28 10:07)

**Comment by W2jx** [comment]
Modify breaking change report to remove unnecessary blank lines.

**Comment by W2jx** [comment]
Forced push to resolve the conflict.

**Comment by W2jx** [comment]
no conflicts(12/12 14:24)

**Comment by W2jx** [comment]
no conflicts(12/18 12:57)

**Comment by W2jx** [comment]
no conflicts(12/19 10:03)

**Comment by W2jx** [comment]
no conflicts(12/20 10:01)

**Comment by W2jx** [comment]
no conflicts(12/21 10:05)

**Comment by W2jx** [comment]
no conflicts(12/22 9:17)

**Comment by W2jx** [comment]
no conflicts(12/26 10:27)

**Comment by W2jx** [comment]
no conflicts(12/28 9:49)

**Comment by W2jx** [comment]
no conflicts(12/29 16:11)

**Comment by W2jx** [comment]
no conflicts(1/2 9:33)

**Comment by W2jx** [comment]
no conflicts(1/3 9:46)

**Comment by W2jx** [comment]
no conflicts(1/4 13:31)

**Comment by W2jx** [comment]
no conflicts(1/5 10:50)

**Comment by W2jx** [comment]
no conflicts(1/8 13:43)

**Comment by 111Anna** [comment]
ci:close

**Comment by Songyuewen** [comment]
ci:close

**Pull request closed without merging**
