### PR TITLE
LPD-30984 fix clustering functional test that using 8080 in User.loginPG

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

resend: https://github.com/liferay-core-infra/liferay-portal/pull/7265
As talked, in the clustering functional test, we will use 8080 for User.loginPG all the time even though we set nodeport 9080.
Trying to fix this in the PR
Thanks for checking

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:clustering

**Comment by jeffwu0724** [comment]
ci:report:41048536

**Comment by jeffwu0724** [comment]
ci:report:41048536

**Comment by jeffwu0724** [comment]
ci:test:clustering

**Comment by jeffwu0724** [comment]
ci:report:41060050

**Comment by jeffwu0724** [comment]
https://testray.liferay.com/#/project/34754/routines/34756/build/41060050/case-result/41366270/history -- flaky
https://testray.liferay.com/#/project/34754/routines/34756/build/41060050/case-result/41365759/history -- not unique
No unique regression found

**Comment by tinatian** [comment]
@jeffwu0724 Please see https://github.com/brianchandotcom/liferay-portal/pull/152576. I only modified the commit message of your last commit.

**Comment by jeffwu0724** [comment]
Thanks @tinatian for optimizing the commit message! 
I am going to close this PR now as it has been sent to BChan.

**Pull request closed without merging**
