### PR TITLE
[Bug Fix]LPS-144603

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@koor4356 can you check this one?

**Comment by koor4356** [comment]
Okay, thanks!

**Comment by koor4356** [comment]
@tinatian,
This looks good. No unique failure.

**Comment by tinatian** [comment]
@shuyangzhou This is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
