### PR TITLE
[Replace Non-Blocking Usage] LPS-202092 Replace non-blocking ServiceProxyFactory usages in class LDAPSettingsUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
ci:test:ldap

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
