### PR TITLE
[Remove unused field] LPS-199318 Remove unused reference field in calsses PostalAddressResourceImpl, InfoPanelMVCResourceCommand and CommerceOptionFieldTypeFDSFilter

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:stop

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(10/19 8:19)

**Comment by W2jx** [comment]
no conflicts(10/20 8:52)

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142506

cc @shuyangzhou

**Pull request closed without merging**
