### PR TITLE
Lps 176754 3 8 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by Kvale1733** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
@tinatian No regressions found in commerce test suite.

**Comment by tinatian** [comment]
Rebase at https://github.com/liferay-core-infra/liferay-portal/pull/3812

**Pull request closed without merging**
