### PR TITLE
LPS-196524 move class Snapshot to portal-kernel and remove unused dependency

### PR DESCRIPTION
**Pull request by JanisZhang**
Resolve conflicts. Thanks! cc @W2jx
https://liferay.atlassian.net/browse/LPS-196524

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5611

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
SF failure should be not related.

**Comment by dantewang** [comment]
@JanisZhang Seems you forget to move `SnapshotIntegrationTest` to the new module.

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
force-pushed. move SnapshotIntegrationTest to the new module.Thanks. cc @dantewang

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by pyoo47** [comment]
ci:reevaluate:1257401_3464

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
Hi @zhangyan0701 , SF failure is not related.

**Comment by zhangyan0701** [comment]
Issues found:
1. Task ':apps:oauth2-provider:oauth2-provider-service:compileTestJava' failed with error:
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-service/src/test/java/com/liferay/oauth2/provider/internal/configuration/ConfigurationFactoryTest.java:10: error: cannot find symbol
     [exec] import com.liferay.osgi.util.service.Snapshot;
     [exec]                                     ^
     [exec]   symbol:   class Snapshot
     [exec]   location: package com.liferay.osgi.util.service
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-service/src/test/java/com/liferay/oauth2/provider/internal/configuration/ConfigurationFactoryTest.java:358: error: cannot find symbol
     [exec] 	private Snapshot<PortalK8sConfigMapModifier> _snapshot;
     [exec] 	        ^
     [exec]   symbol:   class Snapshot
     [exec]   location: class com.liferay.oauth2.provider.internal.configuration.ConfigurationFactoryTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-service/src/test/java/com/liferay/oauth2/provider/internal/configuration/ConfigurationFactoryTest.java:192: error: cannot find symbol
     [exec] 		_snapshot = Mockito.mock(Snapshot.class);
     [exec] 		                         ^
     [exec]   symbol:   class Snapshot
     [exec]   location: class com.liferay.oauth2.provider.internal.configuration.ConfigurationFactoryTest
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-09/test-1-28/test-portal-acceptance-pullrequest(master)/7719/modules-unit-jdk8/0/7/jenkins-console.txt.gz?authuser=0

2. Semantic versioning issue:
```
     [exec] [Baseline Warning] Bundle Version Change Recommended: 124.3.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/124.2.0/eb8f61693a7e91fedb257927278a8a71eef98d62/com.liferay.portal.kernel-124.2.0.jar
```
Full console:
https://testray.liferay.com/reports/production/logs/2023-09/test-1-28/test-portal-acceptance-pullrequest(master)/7719/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Pull request closed without merging**
