### PR TITLE
[Remove Blocking Usages] LPS-187003 Replace blocking ServiceProxyFactory with Snapshot in class WordsUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(10/23 9:31)

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142578

**Pull request closed without merging**
