### PR TITLE
[Components with more than 1 service] LPS-184314 Refactor Miscellaneous components from portal-search-elasticsearch7 module

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://issues.liferay.com/browse/LPS-184314

This pull does not contain the class ElasticsearchConnectionManager because it required a lot of changes, so I will send it in another pull.

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:search

**Comment by dantewang** [comment]
@MrJohn1911 It seems you didn't remove the `com/liferay/portal/search/elasticsearch7/internal/query/QueryToQueryBuilderTranslator.java` in https://github.com/liferay-core-infra/liferay-portal/pull/4812/commits/99e188bec0e4916be5ee297ef4b27355e76ef653, but removed it in https://github.com/liferay-core-infra/liferay-portal/pull/4812/commits/b4da89dc2bf8677b2ace382fb89434b7bd0fc3aa, where you should remove the one in `legacy/query`.

**Review by dantewang — CHANGES_REQUESTED** [review]
Please see my previous comment.

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
we are facing some CI issues, so let's wait for the fix to be merged to re-run test suites.

Thanks,
Cat

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions found.

**Review by rafaprax — APPROVED** [review]

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
