### PR TITLE
LPD-32135 Remove hello-velocity

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@julschong Nice to see the ConfigurationEnvBuilderTest catches the thing I missed!

@tinatian The test failures seem to be real, I'll fix them tomorrow.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:report:57451436

**Comment by dantewang** [comment]
No unique failure.

**Comment by dantewang** [comment]
ci:report:56861157

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 56861157.
> 
> Job Link: [generate-testray-csv](https://test-1-34.liferay.com/job/generate-testray-csv/198/)
> 
> Testray CSV Link: [testray-results-56861157.csv](https://test-1-34.liferay.com/userContent/jobs/generate-testray-csv/builds/198/testray-results-56861157.csv)

The unique failure is a startup failure, which is irrelevant to this PR's change.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7602

**Pull request closed without merging**
