### PR TITLE
[Scheduler]LPS-171016

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by Kvale1733** [comment]
All test fail to run due to a compile issue in dispatch-service

```
 [exec] > Task :apps:dispatch:dispatch-rest-impl:deploy
     [exec] Files of project ':apps:dispatch:dispatch-rest-impl' deployed to /opt/dev/projects/github/liferay-portal/bundles/osgi/modules
     [exec] 
     [exec] > Task :apps:dispatch:dispatch-rest-impl:deployDependencies NO-SOURCE
     [exec] > Task :apps:dispatch:dispatch-rest-impl:deployConfigs NO-SOURCE
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/dispatch/dispatch-service/src/main/java/com/liferay/dispatch/internal/portal/kernel/scheduler/SchedulerResponseManagerImpl.java:143: error: cannot find symbol
     [exec] 		Message message = schedulerResponse.getMessage();
     [exec] 		^
     [exec]   symbol:   class Message
     [exec]   location: class com.liferay.dispatch.internal.portal.kernel.scheduler.SchedulerResponseManagerImpl
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/dispatch/dispatch-service/src/main/java/com/liferay/dispatch/internal/portal/kernel/scheduler/SchedulerResponseManagerImpl.java:146: error: cannot find symbol
     [exec] 			SchedulerEngine.DESTINATION_NAME,
     [exec] 			^
     [exec]   symbol:   variable SchedulerEngine
     [exec]   location: class com.liferay.dispatch.internal.portal.kernel.scheduler.SchedulerResponseManagerImpl
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/dispatch/dispatch-service/src/main/java/com/liferay/dispatch/internal/portal/kernel/scheduler/SchedulerResponseManagerImpl.java:148: error: cannot find symbol
     [exec] 		message.put(SchedulerEngine.GROUP_NAME, groupName);
     [exec] 		            ^
     [exec]   symbol:   variable SchedulerEngine
     [exec]   location: class com.liferay.dispatch.internal.portal.kernel.scheduler.SchedulerResponseManagerImpl
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/dispatch/dispatch-service/src/main/java/com/liferay/dispatch/internal/portal/kernel/scheduler/SchedulerResponseManagerImpl.java:149: error: cannot find symbol
     [exec] 		message.put(SchedulerEngine.JOB_NAME, jobName);
     [exec] 		            ^
     [exec]   symbol:   variable SchedulerEngine
     [exec]   location: class com.liferay.dispatch.internal.portal.kernel.scheduler.SchedulerResponseManagerImpl
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 4 errors
 ```
[Log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-26/test-portal-acceptance-pullrequest(master)/6353/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127696

**Pull request closed without merging**
