### PR TITLE
[Method References 2] LPS-172192 Change the value of property cardinality from ReferenceCardinality.AT_LEAST_ONE to ReferenceCardinality.MULTIPLE | part 2

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:saml

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
@W2jx Could you double check whether this method will collect more than one `MetaDataResolver` services? I suspect the relationship it wants doesn't need to be `x..n`.

**Comment by dantewang** [comment]
@W2jx Closing this PR for now since we are going to put it to the last of our list.

**Pull request closed without merging**
