### PR TITLE
[Remove Stream/Optional usage] LPS-173075 remove_stream_and_optional_in_segments-service

### PR DESCRIPTION
**Pull request by jeffwu0724**
Resent form https://github.com/liferay-core-infra/liferay-portal/pull/3229.
@dantewang , I tried to move the isEmpty() condition inside the filter to be more consistent with the original stream usage.
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:tango

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Pull request closed without merging**
