### PR TITLE
[Remove Blocking usages]LPS-187729 portal-kernel |DestinationFactoryUtil

### PR DESCRIPTION
**Pull request by JanisZhang**
FIX test. thanks!
https://issues.liferay.com/browse/LPS-187729

previous: https://github.com/liferay-core-infra/liferay-portal/pull/4848

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
No regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137295

**Pull request closed without merging**
