### PR TITLE
Revert LPS-153711

### PR DESCRIPTION
**Pull request by GinsonRen**
@tinatian As the result [here](https://docs.google.com/spreadsheets/d/13FA21tjpm2YJLWJGyVXwIJ4PbC-WBjg3J19tgTssFVA/edit#gid=37380184&range=A32), with these tuning commits and revert LPS-153711, session count of DL will reach 35000+. 

/cc @dantewang @yuhai

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@GinsonRen @tinatian no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by tinatian** [comment]
@shuyangzhou Could you please prioritize this pull? We are waiting for this to be merged to start gathering test results for white paper.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
