### PR TITLE
LPS-182545 upgrade json-java to 20230227

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This is for ticket https://issues.liferay.com/browse/LPS-182545.
Thanks for checking!

### CODE REVIEW

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions. SF issues is not related.

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
also upgrade the json in workspaces, gonna retrigger the test

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@jeffwu0724 Please rebase.

Thanks.
Tina

**Comment by jeffwu0724** [comment]
fixed the code conflict in versions-complete.xml, the previous test result should be good

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
fixed the code conflict, gonna retrigger the test

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@dantewang Please take this over.

Thanks.
Tina

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/134756

**Comment by jeffwu0724** [comment]
closed this PR because it has been sent to BChan

**Pull request closed without merging**
