### PR TITLE
LPS-154824

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

FYI, based on https://axis.apache.org/axis2/java/core//release-notes/1.8.0.html, axis2 is still using httpclient3, and I updated it to newest version, which will have a dependency on httpclient4.
This is for https://issues.liferay.com/browse/LPS-154824.
I also removed the two third-party patch because they are fixed in the newer version.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@catarineaguiar Can you help me look at the test result again, please?

Thanks
Jeff

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
