### PR TITLE
[Components with more than 1 service] LPS-181630 Refactor DataHandler components from export-import-test-util module

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:export-import

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:export-import

**Comment by catarineaguiar** [comment]
ci:test:export-import

**Comment by Kvale1733** [comment]
@daiazius No regressions. Only a semver issue
```
[exec] > Task :apps:export-import:export-import-test-util:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.exportimport.test.util.exportimport.data.handler CHANGED    3.0.1      3.0.1      3.0.2      VERSION INCREASE REQUIRED
     [exec] 	~   class      com.liferay.exportimport.test.util.exportimport.data.handler.DummyFolderPortletDataHandler
     [exec] 		~   annotated  org.osgi.service.component.annotations.Component
     [exec] 			+   property   service.0=com.liferay.exportimport.kernel.lar.PortletDataHandler
     [exec] 			-   property   service.0=com.liferay.exportimport.test.util.exportimport.data.handler.DummyFolderPortletDataHandler
     [exec] 			-   property   service.1=com.liferay.exportimport.kernel.lar.PortletDataHandler
     [exec] 	~   class      com.liferay.exportimport.test.util.exportimport.data.handler.DummyFolderStagedModelDataHandler
     [exec] 		~   annotated  org.osgi.service.component.annotations.Component
     [exec] 			+   property   service.0=com.liferay.exportimport.kernel.lar.StagedModelDataHandler
     [exec] 			-   property   service.0=com.liferay.exportimport.test.util.exportimport.data.handler.DummyFolderStagedModelDataHandler
     [exec] 			-   property   service.1=com.liferay.exportimport.kernel.lar.StagedModelDataHandler
     [exec] 	~   class      com.liferay.exportimport.test.util.exportimport.data.handler.DummyFolderWithMissingDummyPortletDataHandler
     [exec] 		~   annotated  org.osgi.service.component.annotations.Component
     [exec] 			+   property   service.0=com.liferay.exportimport.kernel.lar.PortletDataHandler
     [exec] 			-   property   service.0=com.liferay.exportimport.test.util.exportimport.data.handler.DummyFolderWithMissingDummyPortletDataHandler
```
[Log](https://testray.liferay.com/reports/production/logs/2023-04/test-1-39/test-portal-acceptance-pullrequest(master)/4261/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Review by rafaprax — APPROVED** [review]

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/134170

**Pull request closed without merging**
