### PR TITLE
LPS-138329

### PR DESCRIPTION
**Pull request by mbowerman**
Hi Core Infrastructure Team,

This fixes a 7.1.x-specific issue. However, the fix involves patching third-party .jar files, so I was told to send it to the master branch. Please see the comments on https://github.com/ericyanLr/liferay-portal-ee/pull/85 for more details.

Please let me know if you have any questions about this fix.

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.
This pull just adds two third-party patches, and not apply to master. The failure should be unrelated. 

FYI @vicnate5

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113837

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
