### PR TITLE
[Method Reference 2] LPS-165741

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@W2jx @dantewang all integration and functional tests failed on startup due to:

```
[beanshell] 2022-11-21 20:31:22.020 DEBUG [Start Level: Equinox Container: 5d697dfb-a1c5-4213-af87-659497c5ad10][BundleStartStopLogger:86] STARTED com.liferay.portal.template.freemarker_7.0.33 [316]
[beanshell] 2022-11-21 20:31:22.028 ERROR [Start Level: Equinox Container: 5d697dfb-a1c5-4213-af87-659497c5ad10][FreeMarkerTemplateResourceLoader:56] bundle com.liferay.portal.template.freemarker:7.0.33 (316)[com.liferay.portal.template.freemarker.internal.FreeMarkerTemplateResourceLoader(873)] : The activate method has thrown an exception
[beanshell] org.osgi.framework.InvalidSyntaxException: Invalid operator at "(lang.type=ftl)(objectClass=com.liferay.portal.template.TemplateResourceParser))": (&&(lang.type=ftl)(objectClass=com.liferay.portal.template.TemplateResourceParser))
[beanshell] 	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_item(FilterImpl.java:1642) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_and(FilterImpl.java:1548) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_filtercomp(FilterImpl.java:1528) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse_filter(FilterImpl.java:1505) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.framework.FilterImpl$Parser.parse(FilterImpl.java:1484) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.framework.FilterImpl$1.call(FilterImpl.java:158) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.eclipse.osgi.internal.framework.FilterImpl$1.call(FilterImpl.java:154) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at com.liferay.portal.bootstrap.WeakCacheHookImpl.computeIfAbsent(WeakCacheHookImpl.java:38) ~[com.liferay.portal.bootstrap.jar:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-11/test-1-31/test-portal-acceptance-pullrequest(master)/5998/modules-integration-mysql57-jdk8/3/7/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
Hi @dantewang , I will resend this pr.

**Comment by W2jx** [comment]
see https://github.com/liferay-core-infra/liferay-portal/pull/2515

**Pull request closed without merging**
