### PR TITLE
Lps 152518

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
FYI @vicnate5 @LuisOrtiz89

**Comment by tinatian** [comment]
@LuisOrtiz89 Please see here for the detailed reason I made this change https://issues.liferay.com/browse/LPS-152518. Could you please check if it is possible to fix the confusing behavior?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian What scares me about this is that the user could be forced into doing an upgrade they are not ready for. Currently if the user attempts to start a new version of DXP against an old version database, they will be warned that an upgrade is needed first. This allows them to properly prepare by backing up their database, etc.

"we will still run upgrade process for modules which do not have release info in the Release_ table" This seems like the real issue, we should not be running any upgrade processes for the user without them knowing they are upgrading.

**Comment by LuisOrtiz89** [comment]
> @LuisOrtiz89 Please see here for the detailed reason I made this change https://issues.liferay.com/browse/LPS-152518. Could you please check if it is possible to fix the confusing behavior?
> 
> Thanks. Tina.

HI @tinatian, I will take a look to it. Alberto will be back in a week, so probably I will wait until he is back as this seems important and he has much more context about how the upgrades are executed. Anyway I will also talk with María to plan it.

**Comment by tinatian** [comment]
Thanks @vicnate5  and @LuisOrtiz89 ! As we talked in slack, I am going to close this pull.

Tina.

**Pull request closed without merging**
