### PR TITLE
[Optional Reference] LPS-185133 Convert the Optional Dynamic Greedy references to static references using Snapshot in class DDMFormUploadValidator

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(5/24 8:27)

**Comment by W2jx** [comment]
no conflicts(5/25 10:06)

**Comment by W2jx** [comment]
no conflicts(5/26 15:09)

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
