### PR TITLE
[Remove Blocking usages]LPS-188270 portal-kernel | ConfigurationProviderUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@W2jx regressions found:

`JournalEditArticleDisplayContextTest`, `DDMFormUploadValidatorTest`
```
     [exec] com.liferay.dynamic.data.mapping.form.web.internal.upload.DDMFormUploadValidatorTest > classMethod FAILED
     [exec]     java.lang.NoSuchFieldException: No field on null with name _configurationProvider
     [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.getField(ReflectionTestUtil.java:126)
     [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.setFieldValue(ReflectionTestUtil.java:324)
     [exec]         at com.liferay.dynamic.data.mapping.form.web.internal.upload.DDMFormUploadValidatorTest._setUpConfigurationProvider(DDMFormUploadValidatorTest.java:93)
     [exec]         at com.liferay.dynamic.data.mapping.form.web.internal.upload.DDMFormUploadValidatorTest.setUpClass(DDMFormUploadValidatorTest.java:50)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-08/test-1-28/test-portal-acceptance-pullrequest(master)/7453/modules-unit-jdk8/0/4/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.cookies.internal.manager.CookiesDomainTest > testDomain3 FAILED
     [exec]     java.lang.NoClassDefFoundError: Lcom/liferay/portal/configuration/module/configuration/ConfigurationProvider;
     [exec]         at java.lang.Class.getDeclaredFields0(Native Method)
     [exec]         at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
     [exec]         at java.lang.Class.getDeclaredField(Class.java:2068)
     [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.getField(ReflectionTestUtil.java:108)
     [exec]         at com.liferay.portal.kernel.test.ReflectionTestUtil.getAndSetFieldValue(ReflectionTestUtil.java:26)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-08/test-1-28/test-portal-acceptance-pullrequest(master)/7453/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

semver error:
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/commerce/commerce-frontend-taglib] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.commerce.frontend.taglib.servlet.taglib MAJOR      18.7.0     18.7.0     19.0.0     VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.commerce.frontend.taglib.servlet.taglib.PriceTag
     [exec]     		>   field      configurationProvider
     [exec]     			+   return     com.liferay.portal.configuration.module.configuration.ConfigurationProvider
     [exec]     			-   return     com.liferay.portal.kernel.module.configuration.ConfigurationProvider
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 20.0.0
```
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/commerce/commerce-api] FAILED
     [exec]     java.lang.AssertionError: [Baseline Warning] Bundle Version Change Recommended: 76.0.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertFalse(Assert.java:64)
     [exec]         at com.liferay.semantic.versioning.SemanticVersioningTest.testSemanticVersioning(SemanticVersioningTest.java:73)
     [exec]         at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
```
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/commerce/commerce-test-util] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.commerce.test.util.context             MAJOR      6.0.0      6.0.0      7.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.commerce.test.util.context.TestCustomCommerceContext
     [exec]     		+   method     <init>(long,long,long,long,com.liferay.account.service.AccountEntryLocalService,com.liferay.account.service.AccountGroupLocalService,com.liferay.commerce.product.service.CommerceChannelAccountEntryRelLocalService,com.liferay.commerce.product.service.CommerceChannelLocalService,com.liferay.commerce.currency.service.CommerceCurrencyLocalService,com.liferay.commerce.service.CommerceOrderService,com.liferay.portal.configuration.module.configuration.ConfigurationProvider)
     [exec]     			+   return     void
     [exec]     		-   method     <init>(long,long,long,long,com.liferay.account.service.AccountEntryLocalService,com.liferay.account.service.AccountGroupLocalService,com.liferay.commerce.product.service.CommerceChannelAccountEntryRelLocalService,com.liferay.commerce.product.service.CommerceChannelLocalService,com.liferay.commerce.currency.service.CommerceCurrencyLocalService,com.liferay.commerce.service.CommerceOrderService,com.liferay.portal.kernel.module.configuration.ConfigurationProvider)
     [exec]     			-   return     void
     [exec]     	>   class      com.liferay.commerce.test.util.context.TestCustomCommerceContextHttp
     [exec]     		+   method     <init>(javax.servlet.http.HttpServletRequest,com.liferay.account.service.AccountGroupLocalService,com.liferay.commerce.util.CommerceAccountHelper,com.liferay.commerce.product.service.CommerceChannelAccountEntryRelLocalService,com.liferay.commerce.product.service.CommerceChannelLocalService,com.liferay.commerce.currency.service.CommerceCurrencyLocalService,com.liferay.commerce.order.CommerceOrderHttpHelper,com.liferay.portal.configuration.module.configuration.ConfigurationProvider,com.liferay.portal.kernel.util.Portal)
     [exec]     			+   return     void
     [exec]     		-   method     <init>(javax.servlet.http.HttpServletRequest,com.liferay.account.service.AccountGroupLocalService,com.liferay.commerce.util.CommerceAccountHelper,com.liferay.commerce.product.service.CommerceChannelAccountEntryRelLocalService,com.liferay.commerce.product.service.CommerceChannelLocalService,com.liferay.commerce.currency.service.CommerceCurrencyLocalService,com.liferay.commerce.order.CommerceOrderHttpHelper,com.liferay.portal.kernel.module.configuration.ConfigurationProvider,com.liferay.portal.kernel.util.Portal)
     [exec]     			-   return     void
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 24.0.0
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-08/test-1-28/test-portal-acceptance-pullrequest(master)/7453/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
