### PR TITLE
LPD-36667

### PR DESCRIPTION
**Pull request by ericyanLr**
**Additional Testing**
To confirm the reported test cases are now fixed, tests are being ran on a separate test branch:
https://github.com/ericyanLr/liferay-portal/pull/319

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:report:16942747

**Comment by ericyanLr** [comment]
**ci:report:analysis**
No unique test failures

**Additional Testing**
Ran additional testing to confirm reported issues are resolved:
https://github.com/ericyanLr/liferay-portal/pull/319

Confirmed the following test cases now pass:
- DMDocumentType#CanAddPredefinedImageViaRichText
- LocalFile.FormsParagraphField#CanSupportVideos
- LocalFile.FormsParagraphField#CanSupportImages
- LocalFile.Tags#MergeMultipleTags
- LocalFile.Tags#MergeAdditionalTag
- QuestionsEntry#CanAddQuestionWithImage
- QuestionsEntry#CanAddQuestionWithDepotImage

Marking this as **QA Passed** and **Ready to Review (no regression)**.

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
