### PR TITLE
[Remove Spring extender usage]LPS-159487

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:commerce

**Review by dantewang — APPROVED** [review]

**Comment by zhangyan0701** [comment]
Hi @catarineaguiar Could you check the test results when they finish? Thanks!

**Comment by catarineaguiar** [comment]
@slnn no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121579

**Pull request closed without merging**
