### PR TITLE
[Equinox Http LPS-184766] LPS-195887 Inline HttpServiceRuntimeImpl, part 1

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 Are these failures real? I'm not able to see any real portal error log?

**Comment by catarineaguiar** [comment]
seems like a jenkins issue @dantewang, let's re-run the relevant

**Comment by zhangyan0701** [comment]
There is no unique failure in relevant, will re-run ci:test.

**Comment by zhangyan0701** [comment]
ci:test

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
@zhangyan0701 I've sent the full PR at https://github.com/liferay-core-infra/liferay-portal/pull/5561

**Pull request closed without merging**
