### PR TITLE
Lps 152440 7 14

### PR DESCRIPTION
**Pull request by slnn**
/cc @dantewang @tinatian

### CODE REVIEW

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina

**Comment by tinatian** [comment]
@slnn Code looks good to me, wait for QA to scan test results.

Tina

**Comment by catarineaguiar** [comment]
@slnn @tinatian no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Pull request closed without merging**
