### PR TITLE
LPS-146169 Remove stringtemplate.jar

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
@guilhermedcamacho No regressions found.

**Comment by guilhermedcamacho** [comment]
@tinatian , this PR is ready for your review. Thanks!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.
@guilhermedcamacho We have more than one bundle compileInclude this jar, please put it into the list for compileInclude so that we can revisit it later.
`compileInclude group: "org.antlr", name: "stringtemplate"`

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/112850

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
