### PR TITLE
[Replace Non-Blocking Usage] LPS-198509 Replace non-blocking ServiceProxyFactory usages in classes DeviceDetectionUtil and PhoneNumberFormatUtil

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5860

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
no conflicts（10/26 8:42）

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
no conflicts(10/27 8:50)

**Comment by liuxingye** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(10/30 7:57)

**Comment by W2jx** [comment]
no conflicts(10/31 7:55)

**Comment by W2jx** [comment]
no conflicts(11/1 9:03)

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143063

cc @shuyangzhou

**Pull request closed without merging**
