### PR TITLE
LPS-173926 Improve message for Content Page error

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-173926

Hi Team, could you please review this PR? Thanks in advance!

A bit of context: the PMs of both Teams (Mateo Hermosin and Dave Truong) have been discussing this story and this PR is the approach that Mateo mentioned I would send. This PR has been reviewed by the Echo Team [here](https://github.com/liferay-echo/liferay-portal/pull/10943#issuecomment-1408140917).

This development allows a portlet to customize its unhandled error message. It is based on taking advantage of the LanguageImpl fallback implemented [here]( https://github.com/liferay/liferay-portal/blob/d076f63b4ae36b8cce79f0d4abcaddd46071d00b/portal-impl/src/com/liferay/portal/language/LanguageImpl.java#L959-L977
).

This fallback allows a key to be introduced indicating a context between brackets, if the key is found it will be used, otherwise the same key will be used but eliminating the part between brackets. This allows us to search for the specific key for that portlet and, if it is not there, the default one will be used as before.

This language key pattern is already used in some points, for example, [here](https://github.com/liferay/liferay-portal/blob/903f53b2a67034f71071d8876503c27cf7abf19f/modules/apps/archived/portal-security-sso-google-api/src/main/java/com/liferay/portal/security/sso/google/configuration/GoogleAuthorizationConfiguration.java#L30-L50).

cc: @mateo-hermosin
 
Captura de Pantalla 2023-01-27 a las 16 45 04

### CODE REVIEW

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by tinatian** [comment]
@lfbesada Could you please create test to cover this change?

**Comment by lfbesada** [comment]
Hi @tinatian,
Thanks for the review!
**Do you mean a functional or integration test?**
I find it weird to add a functional test to test these changes since it would have to be able to cause an unhandled error. IMHO if we knew how to generate an unhandled error in a portlet we should fix it and then that functional test would stop working.
An integration test to check changes in a .jsp file could be very complicated. To facilitate it, I am thinking of moving this logic to a new method of PortalImpl, for example, getPortletErrorMessage(PortletRequest portletRequest), and then invoking it from error_portlet.jsp
**Would you agree if I move the logic that I introduced to PortalImpl to test it easily?**
I appreciate any help you can provide. 
Regards

**Comment by dantewang** [comment]
@lfbesada For integration test, could you try it without moving the logic? We do have several integration tests existing that create widget/content pages, add portlets to the pages, request the pages and assert the responses. You can use a fake portlet registered in your integration test, contribute its own language key, and assert the response content.

**Comment by lfbesada** [comment]
Hi @tinatian @dantewang 
Thanks for the tips ❤️ 
I rebased this pull request and added some integration tests following the indications. Could you please review them?
Thank you so much!
Regards

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/3448

**Pull request closed without merging**
