### PR TITLE
[Portal service extender] LPS-170709

### PR DESCRIPTION
**Pull request by zhangyan0701**
Resend from https://github.com/liferay-core-infra/liferay-portal/pull/2751

@yuhai @vicnate5

### CODE REVIEW

**Comment by vicnate5** [comment]
Only remaining unique failure here is on [com.liferay.portal.db.partition.test.DBPartitionUtilTest](https://testray.liferay.com/home/-/testray/case_results/2130628586). But I cannot reproduce locally yet.

**Comment by vicnate5** [comment]
ci:test:db-partition

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@zhangyan0701 Can you try to reproduce https://testray.liferay.com/home/-/testray/case_results/2130628586 locally?

The error makes no sense, since it is trying to read a mysql configuration, which should not be impacted by this. But it only fails on this PR, and only in Relevant.

**Comment by zhangyan0701** [comment]
@vicnate5 I didn't reproduce locally neither. And I have a question, should the test be running on `modules-integration-service-builder-jdk8` test batch in `ci:test:relevant` suite? The [jenkins console url](https://testray.liferay.com/reports/production/logs/2022-12/test-1-33/test-portal-acceptance-pullrequest(master)/2567/modules-integration-service-builder-jdk8/3/9/jenkins-console.txt.gz?authuser=0) shows that it is running on `modules-integration-service-builder-jdk8`. But it is running on [modules-integration-mysql57-jdk8](url) in `ci:test:db-partition` suite where it passed.

**Comment by vicnate5** [comment]
Rebased and fixed the test issue with relevant
https://github.com/liferay-core-infra/liferay-portal/pull/2787

**Pull request closed without merging**
