### PR TITLE
Lpd 39976

### PR DESCRIPTION
**Pull request by shuyangzhou**
@tinatian @kevhlee this is a followup for your change in LPD-29412. Please test out your original test case and other related test cases to make sure there is no regression.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
Hi @shuyangzhou, I tested the PR and found no regression. This PR should be good-to-go.

**Comment by shuyangzhou** [comment]
@tinatian please check the CI results once they are in, if clean, please send this pull out, thanks!

**Comment by tinatian** [comment]
ci:report:49104983

**Comment by tinatian** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 49104983.
> 
> Job Link: [generate-testray-csv](https://test-1-30.liferay.com/job/generate-testray-csv/301/)
> 
> Testray CSV Link: [testray-results-49104983.csv](https://test-1-30.liferay.com/userContent/jobs/generate-testray-csv/builds/301/testray-results-49104983.csv)

Unique failures in report are not unique to this pull.

**Comment by tinatian** [comment]
ci:forward:force

**Pull request closed without merging**
