### PR TITLE
[TS] LPD-43062

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__
<https://liferay.atlassian.net/browse/LPD-43062>

__Previous PR:__
<https://github.com/liferay-core-infra/liferay-portal/pull/7715>

This is a resend PR as Brian Chan requested changes: <https://github.com/brianchandotcom/liferay-portal/pull/156801#issuecomment-2529891656>.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:test:core-functional

**Comment by kevhlee** [comment]
ci:report:88124187

**Comment by kevhlee** [comment]
The test failures do not look relevant.

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/156918

**Pull request closed without merging**
