### PR TITLE
[Component with its own class name as service type ] LPS-198079 Refactor Registry classes from mutiple modules

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:relevant

**Comment by GabrielHenriquedev** [comment]
ci:test:starup

**Comment by GabrielHenriquedev** [comment]
ci:test:startup

**Comment by GabrielHenriquedev** [comment]
ci:test:forms

**Comment by GabrielHenriquedev** [comment]
ci:test:lima

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:forms

**Comment by Kvale1733** [comment]
@zhangyan0701 

I found no regression. But there was just one failure I tried to reproduce and couldn't. I get an address already in use error.

https://testray.liferay.com/home/-/testray/case_results/2448239636?tab=result

Going to run depot suite and see if it runs. Can you just check that test.

**Comment by Kvale1733** [comment]
ci:test:depot

**Comment by zhangyan0701** [comment]
No regressions found neither.

**Comment by rafaprax** [comment]
Hey @regiCesar21, please extract the second commit and send it together with your changes related to the asset modules. Thx

**Comment by rafaprax** [comment]
resent only the first commit here https://github.com/liferay-core-infra/liferay-portal/pull/6028

**Pull request closed without merging**
