### PR TITLE
[Components with more than 1 service] LPS-176895 Refactor DTO Converter components with more than 1 service type from Search Experiences module

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-176895](https://issues.liferay.com/browse/LPS-176895)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:help

**Comment by RenanUmV** [comment]
ci:test:search

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by RenanUmV** [comment]
Hey @tinatian , can you review this PR?

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@RenanUmV No regressions found.

**Pull request closed without merging**
