### PR TITLE
LPS-155431

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Same changes than previous https://github.com/liferay-core-infra/liferay-portal/pull/897 but I have added a the new commit https://github.com/liferay-core-infra/liferay-portal/commit/48efb90faebdefe8adfb32fafa316af8305a8210 to write header and footer of the embedded portlets at the render time in the **PortletRenderer.java** class following @tinatian comment https://github.com/liferay-core-infra/liferay-portal/pull/897#discussion_r892889929

After replacing the `PortletContainerUtil.render` call with the new `_renderPortlet` method, the render operation is delayed to the RuntimePageImpl class where the **PortletRenderer.java** is called, so I am moving the write header and write footer operations there.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
Hi @liferay-core-infra  @tinatian 

Do you have any update about this pull request?

Our customer has been waiting for one week and I would like to have these changes merged in master before sending a hotfix to them

Thank you

**Comment by catarineaguiar** [comment]
@tinatian no regressions were found.

**Comment by dantewang** [comment]
@yuhai Please take this over.

**Comment by yuhai** [comment]
Hi @jorgediaz-lr,

Delayed embedded portlet render logic to RuntimePageImpl#doProcessTemplate is good to me. I can't find other good ways to fix it. I have two suggestions for the pr.

1. Please merge the second, the third and the last commit to one commit. They should be one integrated commit. Since if separately check the commit, it lost some contents compared with the original.
2. Could you please create one integration test for the fix? You may consider add the test to modules\apps\static\portal-osgi-web\portal-osgi-web-portlet-container-test.

Thanks,
Hai

**Comment by jorgediaz-lr** [comment]
Hi @yuhai 

Thanks for your comments. I will merge the second, third and fourth commit to make it clearer.

I will also create a integration test.

As the solution is ok for you, I will create and deliver a hotfix to my customer.

I will keep you updated

**Comment by jorgediaz-lr** [comment]
Hi @dantewang 

No problem, I will do it in that way.

Regards,
Jorge

**Comment by jorgediaz-lr** [comment]
Hi @dantewang @yuhai 

I have sent a new PR here https://github.com/liferay-core-infra/liferay-portal/pull/977 with the requested changes.

**Pull request closed without merging**
