### PR TITLE
[Remove Spring extender usages] LPS-159395

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang,

This PR is to remove spring extender usage in commerce-tax-engine-fixed-service, thanks!
https://issues.liferay.com/browse/LPS-159395

### CODE REVIEW

**Review by dantewang — APPROVED** [review]
@catarineaguiar Could you review the test results when the tests finish? Thanks!

@tinatian Code looks good to me, asked QA to check results.

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
