### PR TITLE
[TS] LPS-191780 Use portal class loader to load in test-portal-ext.properties

### PR DESCRIPTION
**Pull request by DaneszLR**
Hi Team!

Original PR: https://github.com/liferay-core-infra/liferay-portal/pull/5309
Fixed formatting and the chain call.

Couldn't reproduce the CI issues locally, if they come up again here, at least we can see if the issues are with getting the class loader or the getResourceAsStream() method.

If the issues come up I would consider this PR ( https://github.com/liferay-core-infra/liferay-portal/pull/5099 ) again as an alternate solution. The logic is the same (using portal class loader).

### CODE REVIEW

**Comment by DaneszLR** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@DaneszLR This regression is still present: https://github.com/liferay-core-infra/liferay-portal/pull/5309#issuecomment-1684507269

**Comment by DaneszLR** [comment]
Hi @tinatian,

Could we reconsider this https://github.com/liferay-core-infra/liferay-portal/pull/5099 PR?
Or
Do you have an idea what causes these CI test fails? Locally we couldn't reproduce them.

Thank you in advance!

**Comment by tinatian** [comment]
@DaneszLR 

> Could we reconsider this https://github.com/liferay-core-infra/liferay-portal/pull/5099 PR?
No, the previous solution is not acceptable.

> Do you have an idea what causes these CI test fails? Locally we couldn't reproduce them.
If you can not reproduce it locally, please ask QA to help. If you can reproduce it but do not know how to deal with it, you can escalated this issue to @ericyanLr or @marianoalvarosaiz.

Thanks.
Tina.

**Comment by Kvale1733** [comment]
@DaneszLR I'll check with the CI team if they have any idea why this only fails on CI.

**Comment by Kvale1733** [comment]
Opened a thread here: https://liferay.slack.com/archives/CL3TWSMHQ/p1692981734816749

**Comment by Kvale1733** [comment]
@DaneszLR So Hashi left a response on that thread. I guess TestPropsUtil is just no loaded manually and on Ci it always is for integration tests. None of the tests triggered by relevant seemed to do this though so locally, none of them reproduced. But on CI it always did.

So you can just run a test that does. 
com.liferay.digital.signature.manager.test.DSDocumentManagerTest for example. I'm going to check to confirm. But running that should trigger the regression.

**Comment by Kvale1733** [comment]
@DaneszLR. I was able to reproduce locally the way Hashi mentioned in the thread. By running 
```export` JENKINS_HOME=true ; gw :apps:portal:portal-dao-test:testIntegration```
in /modules

So it seems the difference in CI is the JENKINS_HOME environment.

**Comment by DaneszLR** [comment]
New PR at: https://github.com/liferay-core-infra/liferay-portal/pull/5642

**Pull request closed without merging**
