### PR TITLE
[Replace Non-Blocking Usage] LPS-202341 IndexWriterHelperUtil

### PR DESCRIPTION
**Pull request by haydenzheng314**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5915
Ticket: https://liferay.atlassian.net/browse/LPS-202341
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by LisztLiszt** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
@LisztLiszt For the original test error in #5915, do you have a full stack trace? Where is the invocation from?

**Review by dantewang — APPROVED** [review]

**Comment by LisztLiszt** [comment]
@dantewang For the original test error in https://github.com/liferay-core-infra/liferay-portal/pull/5915, during the startup, it calls `initCompanies()` in `Mainservlet`, then calls the `addCompany()` in `CompanyLocalServiceUtil` and `_checkCompany` in `CompanyLocalServiceImpl`. In this method it use RoleLocalService to check system roles. In `RoleLocalServiceImpl # initAnalyticsAdministratorViewPermissions(Role role)` it use ResourcePermissionLocalService to add resource permission and finally calls `IndexWriterHelperUtil` to update permission fields

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Pull request closed without merging**
