### PR TITLE
[Components with more than 1 service] LPS-190147 Refactor DLOpenerGoogleDriveManager component

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-190147

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:lima

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by rafaprax** [comment]
Hey @MrJohn1911, fix the conflict here. Thx

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:online-editing

**Comment by Kvale1733** [comment]
No regression found in relevant. Just waiting for online-editing results.

**Comment by catarineaguiar** [comment]
no regressions found.

@MrJohn1911 please, resolve conflicts.

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
No regressions found.

**Comment by tinatian** [comment]
@MrJohn1911 Why it is safe to remove? Please remember to always include the reason.

FYI @rafaprax 

Thanks.
Tina.

**Comment by MrJohn1911** [comment]
> @MrJohn1911 Why it is safe to remove? Please remember to always include the reason in your commit message.
> 
> FYI @rafaprax
> 
> Thanks. Tina.

Hi @tinatian, this pull is on wait, because we are waiting a response from the Lima team about the removing the whole document-library-opener-google-drive-api, since all the interfaces are marked as Deprecated and most of the constants in DLOpenerGoogleDriveMimeTypes are also marked as Deprecated (please see this [thread](https://liferay.slack.com/archives/CLD39UKM5/p1689344027372969)). About that one that I removed, I also talked with them before and they said that it was safe to remove, so I will make sure to leave this in the commit message when I update the pull.

Thanks for the feedback :)

**Pull request closed without merging**
