### PR TITLE
LPS-148582 Move mp4parser to portal-tika module

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test

**Comment by guilhermedcamacho** [comment]
@koor4356 please help me check the results, thanks!

**Comment by koor4356** [comment]
okay, thanks!

**Comment by tinatian** [comment]
@guilhermedcamacho Code looks good to me, wait for QA to scan test results.

Tina

**Comment by koor4356** [comment]
@guilhermedcamacho,
I am not sure if this is related to this PR. But I am seeing the error only on your PR. Can you check, please? Thanks!

`ERROR [Framework Event Dispatcher: Equinox Container: cd99cfaf-c89d-4014-9023-409c569a2bb5][Framework:93] FrameworkEvent ERROR 
     [exec] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: Bundle com.liferay.external.data.source.test.service_1.0.0 [1423] has invalid content in tables.sql:
     [exec] create table TestEntity (
     [exec] 	id_ LONG not null primary key,
     [exec] 	data_ VARCHAR(75) null
     [exec] );
     [exec] 	at com.liferay.portal.spring.extender.internal.upgrade.InitialUpgradeExtender$InitialUpgradeStep.upgrade(InitialUpgradeExtender.java:240) ~[?:?]
     [exec] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor$UpgradeInfosRunnable.run(UpgradeExecutor.java:230) ~[?:?]
     [exec] 	at com.liferay.portal.output.stream.container.internal.OutputStreamContainerFactoryTrackerImpl.runWithSwappedLog(OutputStreamContainerFactoryTrackerImpl.java:134) ~[?:?]
     [exec] 	at com.liferay.portal.upgrade.internal.executor.SwappedLogExecutor.execute(SwappedLogExecutor.java:51) ~[?:?]
     [exec] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.executeUpgradeInfos(UpgradeExecutor.java:158) ~[?:?]
     [exec] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.execute(UpgradeExecutor.java:118) ~[?:?]
     [exec] 	at com.liferay.portal.upgrade.internal.release.ReleaseManagerImpl$UpgradeInfoServiceTrackerMapListener.keyEmitted(ReleaseManagerImpl.java:364) ~[?:?]
     [exec] 	at com.liferay.portal.upgrade.internal.release.ReleaseManagerImpl$UpgradeInfoServiceTrackerMapListener.keyEmitted(ReleaseManagerImpl.java:350) ~[?:?]
     [exec] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$DefaultEmitter.emit(ServiceTrackerMapImpl.java:209) ~[com.liferay.osgi.service.tracker.collections.jar:?]
     [exec] 	at com.liferay.osgi.service.tracker.collections.map.PropertyServiceReferenceMapper.map(PropertyServiceReferenceMapper.java:50) ~[com.liferay.osgi.service.tracker.collections.jar:?]
     [exec] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerMapImpl.java:241) ~[com.liferay.osgi.service.tracker.collections.jar:?]`

https://testray.liferay.com/reports/production/logs/2022-03/test-1-30/test-portal-acceptance-pullrequest(master)/2342/modules-integration-mysql57-jdk8/2/7/jenkins-console.txt.gz?authuser=0

https://testray.liferay.com/home/-/testray/case_results/1626496077

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:backend

**Comment by guilhermedcamacho** [comment]
@koor4356 please help me check the new results, thanks!
The test you mentioned was fixed and passed now. 
[com.liferay.module.dependency.closure.test.ModuleSelfContainedDependencyClosureTest
](https://testray.liferay.com/home/-/testray/case_results/1629041075)

**Comment by koor4356** [comment]
@guilhermedcamacho 
This looks good, thanks!

**Comment by guilhermedcamacho** [comment]
@shuyangzhou , this PR is ready for your review. Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114348

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
