### PR TITLE
LPS-169605 Set notification configurations

### PR DESCRIPTION
**Pull request by murilostodolni**
This PR is related to: https://issues.liferay.com/browse/LPS-169605

**Motivation:**
-----------------------------
Create a scheduler for each company with the same class. So we create the scheduler with `className#companyId` to be able to differentiate one scheduler from another.

**Code changes:**
-----------------------------
The scheduler is created by referencing the class itself through `this`. For that reason, we had to add the className (`className#companyId`) to the _SchedulerEntry_ and _Trigger_.

1. In this [commit](https://github.com/liferay-objects/liferay-portal/pull/1520/commits/c8523371f967efae0697c741fd598b843020a1df), we change the `_serviceRegistration` key to `schedulerEntry.getEventListenerClass()`. In our point of view, this will not cause impact, since schedulers uses the same _className_ in _MessageListener_, _SchedulerEntry_ and _Trigger_.

2. In this [commit](https://github.com/liferay-objects/liferay-portal/pull/1520/commits/bfe454eab3098a78001c874ae8ad419e663f27e4), we create a new method to remove the scheduler from `_serviceRegistrations` through `schedulerEntryEventListenerClass`, as we use the `className` with `className#companyId`.

-----------------------------

Thank you for your time

cc: @marcelabc @samuelromeiro

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:notifications

**Comment by Kvale1733** [comment]
@murilostodolni No regressions found.

**Comment by tinatian** [comment]
@murilostodolni For "Create a scheduler for each company with the same class. So we create the scheduler with className#companyId to be able to differentiate one scheduler from another."
 
Why you need to have a separate scheduler for each company?

**Comment by murilostodolni** [comment]
Hi @tinatian 

We need a separate scheduler because the time to send notifications for each company needs to be different. For example: In _company x_ we need to send notifications every 5 minutes, but in _company y_ we need to send notifications every 10 minutes.

So, the power user can be change the time to send notifications and the time do delete the notifications from the queue of each company differently.

**Comment by marcelabc** [comment]
Hi @tinatian, 
If it helps, you can check the story context and mockup here: https://issues.liferay.com/browse/LPS-155659
Let us know if you have any question!

**Comment by marcelabc** [comment]
Hi @tinatian :smile: 
Could you review this PR please? 
Thanks in advance!

**Comment by tinatian** [comment]
@murilostodolni @marcelabc After you added these methods to SchedulerEngineHelperImpl, the usages of _serviceRegistrations is confusing, there are two methods removing it, one by schedulerEntryEventListenerClass, one by messageListener class name.

Please change 
`private final Map<String, ServiceRegistration<SchedulerEventMessageListener>> _serviceRegistrations`
to 
`private final Map<SchedulerEventMessageListener, ServiceRegistration<SchedulerEventMessageListener>> _serviceRegistrations`

I think it will solve your issues.

Please resend.

Thanks.
Tina.

**Pull request closed without merging**
