### PR TITLE
LPS-155987 extracted from the main PR for the Mockito upgrade

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

Correct the mocked details in tests then we don't need to fix these tests in the upgrade pull. 

Main Task: LPS-153088 Upgrade Mockito to major version 4 and removes the dependency on PowerMock
Sub Task: LPS-155987 Correct the mocked details in tests

https://issues.liferay.com/browse/LPS-155987

Thanks!

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@tinatian Looks good to me.

**Comment by JanisZhang** [comment]
Hi @catarineaguiar,
Could you please help me scan the test results? thanks!

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
