### PR TITLE
[Bug fix] LPS-143959 Upgrade Log4J 2 to 2.16.0

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian This is also urgent.
cc @samuelkong

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test result.

Thanks.
Tina.

**Comment by tinatian** [comment]
Hi @shuyangzhou, I forward it Brian directly as this is urgent, please see https://github.com/brianchandotcom/liferay-portal/pull/111203.

Tina.

**Comment by vicnate5** [comment]
No regressions found.

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
