### PR TITLE
[Tomcat-max thread pool size]LPS-206394 Set maxThreads for tomcat which aims to specify the maximu…

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-206394

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@yuhai It seems the SF failure is related to your Log4J PR?

**Comment by slnn** [comment]
ci:report:2488641867

**Comment by slnn** [comment]
From the testray csv,  the SF failure is not caused by this pull

**Comment by yuhai** [comment]
@dantewang, it seems be related. But my that pr removed these classes. Please see https://github.com/brianchandotcom/liferay-portal/pull/146312. I don't know the reason for now. I am going to check this.

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
@dantewang, I checked the latest master and it has included removing log4j bridge fix. I guess this pr ran SF based on before my pr fix. And then it detected these classes and thrown the error. From my understanding, the previous SF shouldn't detect these classes because Lily's fix didn't change in these classes.

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
@dantewang, SF passed.

**Comment by dantewang** [comment]
ci:test:relevant

**Pull request closed without merging**
