### PR TITLE
[Remove Blocking usages]LPS-189701 bean-portlet | CDIBeanPortletExtension, SpringBeanPortletExtension

### PR DESCRIPTION
**Pull request by W2jx**
Resend

Changes:

1. Merge BeanPortletRegistrar and BeanPortletRegistrarImpl, and change it to util class.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5165

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:portlet-deployment

**Comment by W2jx** [comment]
ci:test

**Comment by W2jx** [comment]
ci:test:jsf

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:portlet-deployment

**Comment by W2jx** [comment]
no conflicts(8/31 8:55)

**Comment by W2jx** [comment]
no conflicts(9/1 8:03)

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@W2jx The change is basically what we discussed. However, there's an issue with the class name and its package: `BeanPorltetRegistrarUtil` is now in a package not ending with `.util`. This is against one of our naming rules.

Let's move every other package into `...registration.portlet` (including the original `.util`), and move the util into the new `...registration.util`, and export this very package..

Please resend.

**Pull request closed without merging**
