### PR TITLE
Lps 149061 3 23

### PR DESCRIPTION
**Pull request by slnn**
Just rebase to the master and update the semantic version.

### CODE REVIEW

**Comment by slnn** [comment]
Hi @tinatian 

I have rebased and force-pushed.

Lily

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115446

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
