### PR TITLE
[Method References 2] LPS-170771 Convert method reference to field reference in class GetDSEnvelopeMVCResourceCommand（module digital-signature-web）

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:digital-signature

**Comment by catarineaguiar** [comment]
@W2jx no regressions found.

**Comment by W2jx** [comment]
no conflicts(12/12 9:49)

**Comment by W2jx** [comment]
no conflicts(2022/12/14 9:32)

**Comment by W2jx** [comment]
no conflicts(12/15 9:25)

**Comment by W2jx** [comment]
no conflicts(2022/12/16 8:57)

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
