### PR TITLE
[Replace Non-Blocking Usage] LPS-198655 Replace non-blocking ServiceProxyFactory usages in class DLFileEntryLocalServiceImpl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(10/12 9:54)

**Comment by W2jx** [comment]
Hi @dantewang , this PR has been checked, and I don't think they need to use dynamic Snapshot.

**Review by dantewang — APPROVED** [review]

**Comment by W2jx** [comment]
no conflicts(10/13 8:23)

**Comment by W2jx** [comment]
no conflicts(10/16 8:59)

**Comment by W2jx** [comment]
no conflicts(10/17 8:23)

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142338

**Pull request closed without merging**
