### PR TITLE
[Static reference] LPS-181671 Remove method reference by using snapshot in modules info-taglib, product-navigation-taglib

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:lima

**Comment by W2jx** [comment]
ci:test:echo

**Comment by W2jx** [comment]
ci:test:lima

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(4/20 7:56)

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
