### PR TITLE
[Remove Stream/Optional usage] LPS-175076 Remove usages of Stream for module: oauth2-provider-service

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:help

**Comment by W2jx** [comment]
ci:test:oauth2

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(2/10 9:06)

**Comment by W2jx** [comment]
no conflicts(2/17 12:48)

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:oauth2

**Comment by Kvale1733** [comment]
@W2jx Regression found

Failure in run-pmd target (ant -f build-common.xml run-pmd)
```
run-pmd:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/pmd-reports
[beanshell] 2 hours 4 minutes until timeout.
[beanshell] The top level build is alive.
[beanshell] 1 hour 59 minutes until timeout.
[beanshell] 1 hour 54 minutes until timeout.
[beanshell] The top level build is alive.
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:6605: 1 PMD violation(s) were found.
     [echo] 
     [echo] PMD VIOLATION: /opt/dev/projects/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-service/src/test/java/com/liferay/oauth2/provider/service/impl/OAuth2ScopeBuilderImplTest.java:243 > Do not call Assert#fail improperly. (PMD Rule: AssertFailJUnitRule)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-02/test-1-37/test-portal-acceptance-pullrequest(master)/9097/pmd-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
