### PR TITLE
[Replace Non-Blocking Usage] LPS-199494 Replace non-blocking ServiceProxyFactory usages in classes AuthLoginGroupSettingsUtil, OrganizationImpl and HitsProcessorRegistryUtil

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(10/20 8:52)

**Comment by W2jx** [comment]
no conflicts(10/23 9:31)

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward:force


cc @shuyangzhou

**Comment by dantewang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142579

**Pull request closed without merging**
