### PR TITLE
[Rename Classes] LPS-166962

### PR DESCRIPTION
**Pull request by W2jx**
https://issues.liferay.com/browse/LPS-166962

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
rebase

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@W2jx no regressions found.

**Pull request closed without merging**
