### PR TITLE
[TS Bug fix] LPS-159031

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 I am not sure if we already have test covered this change based on the discussion here at the old pull https://github.com/liferay-core-infra/liferay-portal/pull/1165, could you please confirm?

Thanks.
Tina.

**Comment by catarineaguiar** [comment]
@tinatian the tests seem to be fixed here https://github.com/brianchandotcom/liferay-portal/pull/122073

**Comment by catarineaguiar** [comment]
ci:test:smoke

**Comment by tinatian** [comment]
@zhangyan0701 Could you please take a look at this today?

Thanks.
Tina.

**Comment by zhangyan0701** [comment]
@tinatian @dantewang 

The test PortalSmoke#SmokeWithReadWriteDatabaseConfigurationJDBC failed with errors like below:
```
[beanshell] 2022-12-09 20:24:07.890 ERROR [main][BatchingBatch:134] HHH000315: Exception executing batch [java.sql.BatchUpdateException: INSERT command denied to user 'read_only_user'@'172.31.0.3' for table 'ExpandoTable'], SQL: insert into ExpandoTable (mvccVersion, ctCollectionId, companyId, classNameId, name, tableId) values (?, ?, ?, ?, ?, ?)
[beanshell] 2022-12-09 20:24:07.891 ERROR [main][SqlExceptionHelper:142] INSERT command denied to user 'read_only_user'@'172.31.0.3' for table 'ExpandoTable'
[beanshell] 2022-12-09 20:24:07.909 ERROR [main][BatchingBatch:134] HHH000315: Exception executing batch [java.sql.BatchUpdateException: INSERT command denied to user 'read_only_user'@'172.31.0.3' for table 'ExpandoTable'], SQL: insert into ExpandoTable (mvccVersion, ctCollectionId, companyId, classNameId, name, tableId) values (?, ?, ?, ?, ?, ?)
[beanshell] 2022-12-09 20:24:07.910 ERROR [main][SqlExceptionHelper:142] INSERT command denied to user 'read_only_user'@'172.31.0.3' for table 'ExpandoTable'
```
The errors are same as the ones in the old pull https://github.com/liferay-core-infra/liferay-portal/pull/1165#issuecomment-1206157819. They should be caused by the changes.

**Comment by dantewang** [comment]
@tinatian @vicnate5 @zhangyan0701 I'm able to reproduce it locally. It's strange that I didn't reproduce it when I debugged the Spring bean overriding. With a quick look, I would say this fix **reveals** the error Summer reports. It seems a read operation using read data source triggered a flush by Hibernate which is also using this read data source. I'll look into it to confirm and see if I can find a way to fix it.

**Comment by dantewang** [comment]
@tinatian I can confirm that it's because of "auto flush".

For example, when executing [the method in this line](https://github.com/liferay/liferay-portal/blob/be70055ef810105426e7d59420253840898e9b75/modules/dxp/apps/saml/saml-addon-keep-alive-web/src/main/java/com/liferay/saml/addon/keep/alive/web/internal/instance/lifecycle/SamlKeepAliveExpandoPortalInstanceLifecycleListener.java#L71), a model listener will perform a query on `ExpandoTable`. The query itself is read-only, but it triggers the flush of uncommitted modifications on expando. Since the flush happens in the context of the read-only transaction of the query, it will use the read-datasource.

**Pull request closed without merging**
