### PR TITLE
[Bug Fix] LPS-158702

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the pr is based on the [requirement](https://github.com/liferay-core-infra/liferay-portal/pull/1141#issuecomment-1192871113)

### CODE REVIEW

**Comment by dantewang** [comment]
@yuhai @tinatian Although the test is added, it's wrong to allow `contentLength` to be larger than what the input stream actually has in the context of HTTP handling (`ServletResponseUtil`).

However, it's hard to know how many bytes are available from an input stream, according to the API JavaDoc on `InputStream` and even `FileInputStream`.

What I can think of is to let `StreamUtil` return the actual length of data it writes and verify it in user code (e.g. `ServletResponseUtil`).

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Tina

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121027

**Pull request closed without merging**
