### PR TITLE
LPD-41335 Centralize all language override functionality into LanguageResourcesExtender

### PR DESCRIPTION
**Pull request by kevhlee**
__Tickets:__
- <https://liferay.atlassian.net/browse/LPD-35718>
- <https://liferay.atlassian.net/browse/LPD-41335>

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:stop

**Comment by tinatian** [comment]
@kevhlee Code conflicts, please resend.

**Comment by kevhlee** [comment]
@tinatian, sent a new pull request here: <https://github.com/liferay-core-infra/liferay-portal/pull/7758>

**Pull request closed without merging**
