### PR TITLE
remove_deprecated_for_portal_kernel_part_Four

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi,

I have removed for
"MessagingConfigurator"
"ProxyModeThreadLocal.java"
"MessageBus.java"
"BaseAsyncDestination.java"
"SynchronousDestination.java"
"BaseLayoutTypeControllerImpl.java"
"VersionedModelInvocationHandler.java"
"MVCRenderConstants.java"
"BasePortletLayoutFinder.java"
"PortletFileRepositoryUtil.java".
Thanks for checking. Also see https://github.com/jeffwu0724/liferay-portal/pull/40.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
@kyle-miho Can you help me look at the test result, please?

Thanks
Jeff

**Comment by tinatian** [comment]
@jeffwu0724 Code looks good to me, wait for QA to scan test result.

Tina.

**Comment by kyle-miho** [comment]
Failures are unrelated @jeffwu0724 @tina

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115167

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
