### PR TITLE
LPS-149082 Move commons-beanutils.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @catarineaguiar, can you please help me scan these test results?

Thx

**Comment by catarineaguiar** [comment]
@rafaprax no regressions found.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/117728

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
