### PR TITLE
[Blocker]LPS-201589 add constant to allow redirecting if it is authorized

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

Resent: https://github.com/brianchandotcom/liferay-portal/pull/144902#issuecomment-1842820242
I add a new property "LiferayActionResponse.SKIP_ESCAPE_REDIRECT" in the LiferayActionResponse, and see if it is "true" when we try to escape.

Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
Hi team,

Could you please help me check if this is still be able to reproduce? https://liferay.atlassian.net/browse/LPS-196525 and https://liferay.atlassian.net/browse/LPS-201589.
I have tested locally, and they passed.
Thanks!

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions found. Testing passed for both issues. Just found a semver issue.
```
[exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.portlet                  MINOR      28.0.0     28.0.0     28.1.0     VERSION INCREASE REQUIRED
     [exec] 	<   interface  com.liferay.portal.kernel.portlet.LiferayActionResponse
     [exec] 		+   field      SKIP_ESCAPE_REDIRECT
     [exec] 			+   access     final
     [exec] 			+   access     static
     [exec] 			+   constant   skip_escape_redirect
     [exec] 			+   return     java.lang.String
     [exec] [Baseline Report] Mode: diff (persisted)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-12/test-1-31/test-portal-acceptance-pullrequest(master)/10080/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
@jeffwu0724 Please update the sem ver, thanks!

**Comment by jeffwu0724** [comment]
add smantic versioning, the previous test result are good enough

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/145299

**Pull request closed without merging**
