### PR TITLE
[Remove Stream/Optional usage] LPS-173791 module: object-web

### PR DESCRIPTION
**Pull request by JanisZhang**
Resend, I add one SF commit making the looped item goes second.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3493
https://issues.liferay.com/browse/LPS-173791

### CODE REVIEW

**Review by dantewang — APPROVED** [review]

**Comment by JanisZhang** [comment]
Force-pushed, I add 1 SF commit to rename `stringSet` to `strings`. Thanks!

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:object

**Comment by catarineaguiar** [comment]
no regressions found.

**Pull request closed without merging**
