### PR TITLE
[Components with more than 1 service] LPS-177035 Refactor DTOConverter components with more than 1 service type from headless-commerce-admin-site-setting-impl module

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-177035](https://issues.liferay.com/browse/LPS-177035)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
ci:test:commerce

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by RenanUmV** [comment]
Hey @tinatian , this one is ready to go!

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:commerce

**Pull request closed without merging**
