### PR TITLE
LPS-166009 Move portal-impl template files to  portal-template-engine-api

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@julschong can you rebase and re-run relevant? Thanks

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong failures not related. No regressions found.

**Comment by julschong** [comment]
rebased for conflict

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by tinatian** [comment]
@julschong As we talked, please resend.

Thanks.
Tina

**Pull request closed without merging**
