### PR TITLE
LPS-170981 Remove "immediate = true" from Echo componentes part 4

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:test:startup

**Comment by GabrielHenriquedev** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
@GabrielHenriquedev No regressions found.

**Comment by GabrielHenriquedev** [comment]
Hey @shuyangzhou can you review this pull? thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127668

**Pull request closed without merging**
