### PR TITLE
LPS-200601 Fix test module: saml-opensaml-integration

### PR DESCRIPTION
**Pull request by JanisZhang**
https://liferay.atlassian.net/browse/LPS-200601

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:help

**Comment by JanisZhang** [comment]
ci:test:saml

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
no regressions found.

[com.liferay.saml.opensaml.integration.internal.servlet.profile.SingleLogoutProfileIntegrationTest](https://testray.liferay.com/home/-/testray/case_results/2463234098?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2463227435%26testrayRunId%3D2463234002%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) passed.

**Comment by JanisZhang** [comment]
ci:forward

**Pull request closed without merging**
