### PR TITLE
LPS-172410 Remove "immediate = true" from remaining Lima modules

### PR DESCRIPTION
**Pull request by daiazius**

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
@daiazius  Regression found

1) Unsatisfied references when restarting portal
Steps to reproduce:
     i. Start portal
     ii. Stop portal (do not clean anything).
     iii. Restart portal
     
 Expected results: Can restart portal without issue
 Actual Results. Unsatisfied references on startup
 ```
[beanshell] 2023-01-09 19:07:43.123 WARN  [main][SystemCheckOSGiCommands:134] Declarative Service Unsatisfied Component Checker check result: 
[beanshell] Bundle {id: 467, name: com.liferay.document.library.preview.audio, version: 3.0.16}
[beanshell] 	Declarative Service {id: 7382, name: com.liferay.document.library.preview.audio.internal.AudioDLPreviewRendererProvider, unsatisfied references: 
[beanshell] 		{name: _audioProcessor, target: null}
[beanshell] 	}
[beanshell] Bundle {id: 875, name: com.liferay.document.library.web, version: 6.0.124}
[beanshell] 	Declarative Service {id: 8783, name: com.liferay.document.library.web.internal.change.tracking.spi.display.DLFileVersionCTDisplayRenderer, unsatisfied references: 
[beanshell] 		{name: _audioProcessor, target: null}
[beanshell] 		{name: _videoProcessor, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 8780, name: com.liferay.document.library.web.internal.change.tracking.spi.display.DLFileEntryCTDisplayRenderer, unsatisfied references: 
[beanshell] 		{name: _audioProcessor, target: null}
[beanshell] 		{name: _videoProcessor, target: null}
[beanshell] 	}
[beanshell] Bundle {id: 1002, name: com.liferay.document.library.video, version: 1.0.52}
[beanshell] 	Declarative Service {id: 9310, name: com.liferay.document.library.video.internal.portlet.action.EmbedVideoStatusMVCResourceCommand, unsatisfied references: 
[beanshell] 		{name: _videoProcessor, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 9309, name: com.liferay.document.library.video.internal.portlet.action.EmbedVideoMVCRenderCommand, unsatisfied references: 
[beanshell] 		{name: _videoProcessor, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 9312, name: com.liferay.document.library.video.internal.preview.DLVideoDLPreviewRendererProvider, unsatisfied references: 
[beanshell] 		{name: _videoProcessor, target: null}
[beanshell] 	}
  ```
  [Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-35/test-portal-acceptance-pullrequest(master)/3262/functional-smoke-startup-tomcat90-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:lima

**Comment by catarineaguiar** [comment]
@daiazius should we remove the qa-failed label?

**Comment by Kvale1733** [comment]
@daiazius The regression on restart still persists.

Unsatisfied references when restarting portal
Steps to reproduce:
i. Start portal
ii. Stop portal (do not clean anything).
iii. Restart portal
Expected results: Can restart portal without issue
Actual Results. Unsatisfied references on startup

```
[beanshell] 2023-01-11 00:35:58.049 WARN  [main][SystemCheckOSGiCommands:134] Declarative Service Unsatisfied Component Checker check result: 
[beanshell] Bundle {id: 948, name: com.liferay.document.library.video, version: 1.0.52}
[beanshell] 	Declarative Service {id: 9228, name: com.liferay.document.library.video.internal.portlet.action.EmbedVideoStatusMVCResourceCommand, unsatisfied references: 
[beanshell] 		{name: _videoProcessor, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 9227, name: com.liferay.document.library.video.internal.portlet.action.EmbedVideoMVCRenderCommand, unsatisfied references: 
[beanshell] 		{name: _videoProcessor, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 9230, name: com.liferay.document.library.video.internal.preview.DLVideoDLPreviewRendererProvider, unsatisfied references: 
[beanshell] 		{name: _videoProcessor, target: null}
[beanshell] 	}
[beanshell] Bundle {id: 1208, name: com.liferay.document.library.preview.audio, version: 3.0.16}
[beanshell] 	Declarative Service {id: 10325, name: com.liferay.document.library.preview.audio.internal.AudioDLPreviewRendererProvider, unsatisfied references: 
[beanshell] 		{name: _audioProcessor, target: null}
[beanshell] 	}
[beanshell] Bundle {id: 1326, name: com.liferay.document.library.web, version: 6.0.124}
[beanshell] 	Declarative Service {id: 10808, name: com.liferay.document.library.web.internal.change.tracking.spi.display.DLFileVersionCTDisplayRenderer, unsatisfied references: 
[beanshell] 		{name: _audioProcessor, target: null}
[beanshell] 		{name: _videoProcessor, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 10805, name: com.liferay.document.library.web.internal.change.tracking.spi.display.DLFileEntryCTDisplayRenderer, unsatisfied references: 
[beanshell] 		{name: _audioProcessor, target: null}
[beanshell] 		{name: _videoProcessor, target: null}
[beanshell] 	}
[beanshell] 2023-01-11 00:35:58.049 INFO  [main][SystemCheckOSGiCommands:111] Running "Missing Component Scanner". You can run this by itself with command "ds:missing" in gogo shell.
[beanshell] 2023-01-11 00:35:58.051 INFO  [main][SystemCheckOSGiCommands:123] Missing Component Scanner check result: No issues were found.
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-32/test-portal-acceptance-pullrequest(master)/7808/functional-smoke-startup-tomcat90-mysql57-jdk8/0/7/jenkins-console.txt.gz?authuser=0)

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:startup

**Comment by daiazius** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
@daiazius No regressions.

**Comment by daiazius** [comment]
Hey @tinatian this one is ready to go.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128946

**Pull request closed without merging**
