### PR TITLE
LPD-8471 remove unused reference _httpServiceRuntime

### PR DESCRIPTION
**Pull request by titokenzo**

### CODE REVIEW

**Comment by titokenzo** [comment]
ci:test:startup

**Comment by titokenzo** [comment]
ci:report:2543591734

**Comment by titokenzo** [comment]
ci:test:relevant

**Comment by titokenzo** [comment]
ci:report:2544466408

**Comment by dantewang** [comment]
@titokenzo The CI failures should be relevant. The `_httpServiceRuntime` reference field makes this component to wait for the readiness of the OSGi Http servlet endpoint; without this, it might start up too early. This reference can not be simply removed; to avoid it, refactor should be needed.

cc @brunofalc @tinatian

**Pull request closed without merging**
