### PR TITLE
[Replace Non-Blocking Usage] LPS-202476 Keep original dummy proxy logic in PortletDataContextFactoryUtil

### PR DESCRIPTION
**Pull request by JanisZhang**
https://liferay.atlassian.net/browse/LPS-202476

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:upgrade

**Review by dantewang — APPROVED** [review]

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/144336

cc @shuyangzhou

**Pull request closed without merging**
