### PR TITLE
[Static reference] LPS-170593 Remove method reference by using snapshot in modules object-web, portal-search-web

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:lima

**Comment by W2jx** [comment]
ci:test:object

**Comment by Kvale1733** [comment]
ci:test:object

**Comment by W2jx** [comment]
no conflicts(4/12 9:52)

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@W2jx No regressions.

**Comment by W2jx** [comment]
no conflicts(4/13 8:00)

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
