### PR TITLE
[Static references] LPS-182371 Remove static references in item-selector module

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://issues.liferay.com/browse/LPS-182371

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:item-selector

**Comment by MrJohn1911** [comment]
ci:stop

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:item-selector

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions.

**Comment by tinatian** [comment]
@MrJohn1911 @rafaprax There are two AggregateDLPortletToolbarContributor with exactly same logic, please make it to be one by following the ***Registry pattern. Which is, expose ***Registry interface in api module, implement it in a impl or web module, and reference ***Registry when use it.

Please resend.

Thanks.
Tina

**Comment by MrJohn1911** [comment]
> @MrJohn1911 @rafaprax There are two AggregateDLPortletToolbarContributor with exactly same logic, please make it to be one by following the ***Registry pattern. Which is, expose ***Registry interface in api module, implement it in a impl or web module, and reference ***Registry when use it.
> 
> Please resend.
> 
> Thanks. Tina

@tinatian Prax and I was analyzing the components DLPortletToolbarContributorRegistryUtil and DLPortletToolbarContributorRegistry and we think that they don't have a good usage, because the service tracker that they have only catches 1 component, which is DefaultDLPortletToolbarContributor. So we think that these components have to be deleted, along with the DLPortletToolbarContributor, which is deprecated.

**Comment by rafaprax** [comment]
@tinatian @MrJohn1911 Another good reason to get rid of the `DLPortletToolbarContributor` and the related classes is that all methods of the `DLPortletToolbarContributor` are deprecated.

**Pull request closed without merging**
