### PR TITLE
[Remove Stream usage: document-library-web-test]Lps 176226

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-176226

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:document

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
@slnn Please keep your extracted method _getParameters, and still use HashMapBuilder whenever you need to put more things. It's OK to use HashMapBuilder.putAll in tests because we prefer readability over performance in test code. Also, after these changes, inline parameters wherever possible.

**Comment by slnn** [comment]
Resend, please see https://github.com/liferay-core-infra/liferay-portal/pull/3875

**Pull request closed without merging**
