### PR TITLE
[Components with more than 1 service] LPS-175886 Refactor DTO Converter components with more than 1 service type from Analytics Cloud and Headless modules

### PR DESCRIPTION
**Pull request by MrJohn1911**

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud

**Comment by MrJohn1911** [comment]
ci:test:headless

**Comment by zhangyan0701** [comment]
ci:test:headless

**Comment by zhangyan0701** [comment]
ci:test:analytics-cloud

**Comment by Kvale1733** [comment]
ci:test:analytics-cloud

**Comment by Kvale1733** [comment]
Possible regressions, rerunning suite to verify:
https://testray.liferay.com/home/-/testray/case_results/2199801274
https://testray.liferay.com/home/-/testray/case_results/2237526358?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1554808880%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1554808880%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc
https://testray.liferay.com/home/-/testray/case_results/2237525395
https://testray.liferay.com/home/-/testray/case_results/2236096028
https://testray.liferay.com/home/-/testray/case_results/2237526139?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1559513677%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1559513677%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc
https://testray.liferay.com/home/-/testray/case_results/2237526078?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1558778896%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1558778896%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc
https://testray.liferay.com/home/-/testray/case_results/2237525320?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1539767245%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1539767245%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc
https://testray.liferay.com/home/-/testray/case_results/2237526267?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1557076528%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1557076528%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc
https://testray.liferay.com/home/-/testray/case_results/2237526142?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1558778893%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1558778893%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc
https://testray.liferay.com/home/-/testray/case_results/2237526142

**Comment by Kvale1733** [comment]
Possible regressions, rerunning suite to verify:

https://testray.liferay.com/home/-/testray/case_results/2237526358?tab=result

https://testray.liferay.com/home/-/testray/case_results/2237526139?tab=result

https://testray.liferay.com/home/-/testray/case_results/2199801274?tab=result

https://testray.liferay.com/home/-/testray/case_results/2237525395?tab=result

https://testray.liferay.com/home/-/testray/case_results/2236096028?tab=result

https://testray.liferay.com/home/-/testray/case_results/2237526139?tab=result

https://testray.liferay.com/home/-/testray/case_results/2237526078?tab=result

https://testray.liferay.com/home/-/testray/case_results/2237525320?tab=result

https://testray.liferay.com/home/-/testray/case_results/2237526267?tab=result

https://testray.liferay.com/home/-/testray/case_results/2237526142?tab=result

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@MrJohn1911 @rafaprax The first commit of this pull is https://github.com/liferay-core-infra/liferay-portal/pull/3932/commits/ea0980d7d7fe8b6773850c5bdf45ba00f00a1bd3, it is using a constant which I did not know where it is defined.

Please reorder your commits to make sure I can see where the constants defined clearly.

The same thing happened to other pulls, that is you define the constants in the first commit, following several commits not related to the constants, then apply the constants, this is really hard to review, and I re-order the commit to make sure the constants only created when it is going to be applied.

@rafaprax Please revisit your other pulls to fix same issue, let me know when you finish this checking, then I will resume the review of pulls like this.

Tina.

**Comment by MrJohn1911** [comment]
@tinatian Can you review this? thanks!

**Comment by rafaprax** [comment]
Hey @MrJohn1911, please break the first commit https://github.com/liferay-core-infra/liferay-portal/pull/3932/commits/482b7f80193698088330244cbd84dc94604f9bcb according to the constants usages. Thx

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:analytics-cloud

**Comment by MrJohn1911** [comment]
This last push was to just resolve a conflict in the branch.

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud

**Comment by MrJohn1911** [comment]
ci:test:headless

**Comment by MrJohn1911** [comment]
@rafaprax can you review this? thanks!

**Comment by rafaprax** [comment]
Hey @MrJohn1911, I have made a minimal adjustment and pushed it to your branch. It was just a generalization since the logic from those 3 methods was the same, see https://github.com/liferay-core-infra/liferay-portal/pull/3932/commits/29f956a6d7e250c1bdf81b4380c9896fcc0e2854

Thx

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @Kvale1733, I did not trigger the other suites because I just changed the headless-admin-user-impl module. So, the analytics results are still valid. 

Thx

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions.

**Comment by rafaprax** [comment]
Hey @tinatian, this pr is the last big one we talked about last week. Thx

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud

**Comment by Kvale1733** [comment]
ci:test:headless

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud

**Comment by MrJohn1911** [comment]
ci:test:headless

**Comment by MrJohn1911** [comment]
ci:stop

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by MrJohn1911** [comment]
ci:test:analytics-cloud

**Comment by MrJohn1911** [comment]
ci:test:headless

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:stop:analytics-cloud

**Comment by rafaprax** [comment]
ci:stop:headless

**Comment by rafaprax** [comment]
ci:stop:relevant

**Comment by rafaprax** [comment]
ci:stop:stable

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:analytics-cloud

**Comment by rafaprax** [comment]
ci:test:headless

**Comment by Kvale1733** [comment]
ci:test:analytics-cloud

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@MrJohn1911 @rafaprax Please separate this pull into two, make the changes following general rules in one, others like https://github.com/liferay-core-infra/liferay-portal/pull/3932/commits/c2887830ffe68265e2a137705bc97f9dd1496a3a in another one, by the way, I do not understand why you are doing https://github.com/liferay-core-infra/liferay-portal/pull/3932/commits/c2887830ffe68265e2a137705bc97f9dd1496a3a.

Next time, if there are a lot stuff following similar pattern and some do not follow same pattern, please separate them especially when you did some special things to deal with edge cases.

Thanks.
Tina.

**Comment by MrJohn1911** [comment]
> 

Hi @tinatian, just to explain, the reason why I did this is because when I replaced the DTOConverter classes references for a DTOConverter interface, the methods that only exists in the DTOConverter classes (getAccountEntryId, getUserGroupId and getUserId) couldn't be used, so I moved them to a Util class, so they could be used. The generalization of them was made by @rafaprax, who noticed that they had a relationship between them, so instead of using 3 methods, I only used 1 that makes the same thing.

**Pull request closed without merging**
