### PR TITLE
LPS-131529 Using original names when downloading files

### PR DESCRIPTION
**Pull request by jan-tosovsky-cz**
Prefer using original names instead those parsed form download URL, see details in https://issues.liferay.com/browse/LPS-131529

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 Ci tests are not triggered for this pull, could you please take a look at it?

Tina

**Comment by tinatian** [comment]
@jan-tosovsky-cz Please see https://github.com/liferay-core-infra/liferay-portal/pull/511. I did not take your solution as the modified URL should be treated as bad URL which should not have access to the document.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:close

**Comment by jan-tosovsky-cz** [comment]
> I did not take your solution as the modified URL should be treated as bad URL which should not have access to the document.

@tinatian  Thanks for your fix! I planned to create a separate issue for this related problem. I still think serving the original filename would eliminate any potential attack vector completely. We will investigate the fixed version with our security team and report back if some issue is found.

**Pull request closed without merging**
