### PR TITLE
[Test Fix] LPD-38924 Fix LockLocalService for MariaDB by changing ExpectedType to ExpectedType.CONTAINS

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:core-functional

**Comment by julschong** [comment]
Test passed here: https://testray.liferay.com/#/project/35392/routines/45357/build/44246038
ready for review

**Comment by tinatian** [comment]
ci:forward:force

**Comment by julschong** [comment]
manually sent here: https://github.com/brianchandotcom/liferay-portal/pull/155427

**Pull request closed without merging**
