### PR TITLE
[Method References 2] LPS-165626 Convert method reference to ServiceTrackerMap in class DefaultJournalTransformerListenerRegistryImpl(module journal-service)

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(1/3 8:56)

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(1/4 8:20)

**Comment by W2jx** [comment]
no conflicts(1/5 8:59)

**Comment by tinatian** [comment]
@W2jx This had been done by @JanisZhang at https://github.com/brianchandotcom/liferay-portal/pull/128299, @JanisZhang please rebase.

**Comment by tinatian** [comment]
@W2jx For this https://github.com/liferay-core-infra/liferay-portal/pull/2887/commits/d39eb684f71a887d09c45287f1e0256e1c174427, what you did is correct, but after your change, you should realize using static util to do reference handling is actually what we want to remove. Please take a look at the pull Jannis sent.

Thanks.
Tina

**Comment by JanisZhang** [comment]
> @W2jx This had been done by @JanisZhang at https://github.com/brianchandotcom/liferay-portal/pull/128299, @JanisZhang please rebase, if only baseline related changes, please send it to BChan directly and cc me and shuyang.

Hi @tinatian , this one has been sent to liferay-core-infra#2947 and forwarded to brianchandotcom#128439 . Thanks

**Pull request closed without merging**
