### PR TITLE
[Bug fix] LPS-143959

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian @vicnate5 I forgot to update this in the last PR.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
FYI @shuyangzhou, this is kind of urgent, so I forward to Brian directly.

Tina.

**Pull request closed without merging**
