### PR TITLE
[Method References 2] LPS-167730 Remove method reference in class PortletRegistryImpl

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have modified  the method remove according to the [comment](https://github.com/liferay-core-infra/liferay-portal/pull/4344#discussion_r1180818976).
The reason why classes `DialectFragmentCollectionContributor`, `FootersFragmentCollectionContributor` and `NavigationBarsFragmentCollectionContributor` are dependent on portlet  SiteNavigationMenuPortlet (Its value of com.liferay.fragment.entry.processor.portlet.alias is nav) is that they contain the  widget nav, it is recorded in the [HTML file](https://github.com/liferay/liferay-portal/blob/master/modules/apps/fragment/fragment-collection-contributor/fragment-collection-contributor-navigation-bars/src/main/resources/com/liferay/fragment/collection/contributor/navigation/bars/dependencies/header-dark/index.html) ， label <lfr-widget-nav></lfr-widget-nav> represents widget nav.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/4344

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:stable

**Comment by W2jx** [comment]
ci:test:help

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian 

@W2jx will add an extra task to see if we can make the portlet reference https://github.com/liferay-core-infra/liferay-portal/pull/4528/commits/7228babb3230b86b5649b3a1597e85683afc49e8 used in those classes.

**Comment by dantewang** [comment]
Manually sent to https://github.com/brianchandotcom/liferay-portal/pull/134885

**Pull request closed without merging**
