### PR TITLE
[Replace Non-Blocking Usage] LPS-199844 Replace non-blocking ServiceProxyFactory usages in classes LockManagerUtil, RepositoryClassDefinition and LegacyExternalRepositoryDefiner

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
no conflicts(10/27 8:50)

**Comment by catarineaguiar** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
no conflicts(10/30 7:57)

**Comment by W2jx** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
@W2jx No regressions found.

**Comment by W2jx** [comment]
no conflicts(10/31 7:52)

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Comment by W2jx** [comment]
no conflicts(11/1 9:03)

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
