### PR TITLE
LPS-152004 Avoid invoke MBThreadFlagLocalService repeatedly

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-152004

/cc @tinatian @dantewang

### CODE REVIEW

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina.

**Comment by catarineaguiar** [comment]
@vicnate5 will not have time to review this one today

**Comment by vicnate5** [comment]
@koor4356 can you check this one?

**Comment by koor4356** [comment]
Okay, thanks!

**Comment by koor4356** [comment]
@tinatian 
This PR looks good, thanks!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
