### PR TITLE
[Login-performance-tuning] LPS-148976

### PR DESCRIPTION
**Pull request by yuhai**
@tinatian, @dantewang, the pr is based on the [requirement](https://github.com/liferay-core-infra/liferay-portal/pull/445#issuecomment-1065359879). [LPS-148968](https://issues.liferay.com/browse/LPS-148968) was merged to master. I just rebased it based on the latest master.

### CODE REVIEW

**Comment by tinatian** [comment]
@yuhai Please rebase

**Comment by yuhai** [comment]
@tinatian, I just rebased and pushed it.

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114877

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
