### PR TITLE
[TS] LPS-195981

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@marianoalvarosaiz I am taking in this pull as it is for now.
But we are compileInclude this thing 4 times already.
```
modules/apps/commerce/commerce-report-impl/build.gradle:        compileInclude group: "org.codehaus.groovy", name: "groovy-all", version: "2.4.21"
modules/apps/portal-scripting/portal-scripting-groovy/build.gradle:     compileInclude group: "org.codehaus.groovy", name: "groovy-all", version: "2.4.21"
modules/apps/server/server-admin-web/build.gradle:      compileInclude group: "org.codehaus.groovy", name: "groovy-all", version: "2.4.21"
modules/dxp/apps/portal-reports-engine-console/portal-reports-engine-console-jasper/build.gradle:       compileInclude group: "org.codehaus.groovy", name: "groovy-all", version: "2.4.21"
```
And this fat jar is 7.2mb, that's too much to carry on.
Please add a follow up to move groovy-all as a shared dependencies module.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141192

**Pull request closed without merging**
