### PR TITLE
LPS-145907

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian, @shuyangzhou ,

I have removed unused properties "rtl.css.excluded.paths.regexp", and updated to propskeys.java, propsvalues.java and verifyproperties.java.
It was added as "RTL_CSS_EXCLUDED_PATHS_REGEXP" in commit 9edbcd15635ca5d1622b60375006efb7fa7d4ded, see LPS-44291, and it was used in "RTLCSSUtil.java".
It was deleted the use in commit 0076439b31de3ebd8c0117b0b7da24efb66e673d, see LPS-51039
Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.
@jeffwu0724 Code looks good to me, wait for QA to scan test results.

Tina.

**Comment by vicnate5** [comment]
@jeffwu0724 This requires a version bump in `com.liferay.portal.util` and `com.liferay.portal.kernel.util` [Semver Test Log](https://testray.liferay.com/reports/production/logs/2022-01/test-1-26/test-portal-acceptance-pullrequest(master)/1472/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz)

No regressions found.

Note: These tests uniquely failed on CI, but all of them are passing when I run them locally against this branch:
[com.liferay.document.library.web.exportimport.data.handler.test.DLPortletDataHandlerTest](https://testray.liferay.com/home/-/testray/case_results/1602762059). 
[com.liferay.fragment.internal.struts.test.ImportFragmentEntriesStrutsActionTest](https://testray.liferay.com/home/-/testray/case_results/1602761900)
[com.liferay.staging.test.StagingDataPortletPreferencesTest](https://testray.liferay.com/home/-/testray/case_results/1602762734)

**Pull request closed without merging**
