### PR TITLE
[Replace Non-Blocking Usage] LPS-200073 Replace non-blocking ServiceProxyFactory in FacetedSearcherManagerUtil, FieldQueryFactoryUtil, ReindexStatusMessageSenderUtil

### PR DESCRIPTION
**Pull request by haydenzheng314**
Resend. Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5920
Ticket: https://liferay.atlassian.net/browse/LPS-200073
Thanks

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by LisztLiszt** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@LisztLiszt No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143184

cc @shuyangzhou

**Pull request closed without merging**
