### PR TITLE
[Rename Classes] 166962

### PR DESCRIPTION
**Pull request by W2jx**
https://issues.liferay.com/browse/LPS-166962

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
Hi @W2jx 

This commit https://github.com/liferay-core-infra/liferay-portal/pull/2264/commits/0ced9c2e09e4a39e262ad0c1b0b24d4b43c7ca1e is missing the ticket number in the commit message, this is why sf test failed.

No regressions found in the relevant tests.

**Pull request closed without merging**
