### PR TITLE
LPS-190427 Merge WorkflowPermission interface and impl into Util

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:worfklow

**Comment by Kvale1733** [comment]
ci:test:workflow

**Comment by dantewang** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
No regressions found. Only a semantic versioning issue:
```
     [exec] > Task :apps:message-boards:message-boards-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.message.boards.service.permission      MAJOR      1.1.1      1.1.1      2.0.0      VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.message.boards.service.permission.MBDiscussionPermission
     [exec] 		-   method     setWorkflowPermission(com.liferay.portal.kernel.workflow.permission.WorkflowPermission)
     [exec] 			-   access     protected
     [exec] 			-   annotated  org.osgi.service.component.annotations.Reference
     [exec] 				-   property   unbind='-'
     [exec] 			-   return     void
     [exec] [Baseline Warning] Bundle Version Change Recommended: 22.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.message.boards.api-21.2.1.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.message.boards.api/21.2.0/d0481f4d1d8ee4640b0e9472e5578c4eb232e3b7/com.liferay.message.boards.api-21.2.0.jar
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-07/test-1-30/test-portal-acceptance-pullrequest(master)/7142/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0

**Pull request closed without merging**
