### PR TITLE
[Method References 2] LPS-169905 Convert method reference to ServiceTrackerList in class IndexContributorsHolder

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:help

**Comment by W2jx** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(2/28 8:40)

**Comment by W2jx** [comment]
no conflicts(3/1 10:45)

**Comment by tinatian** [comment]
@W2jx This is a very bad design, this was added by https://issues.liferay.com/browse/LPS-106304 to fix soft circular dependency, please revert the original fix and use service tracker as service tracker by nature will fix the circular dependency issue.

**Comment by W2jx** [comment]
Hi @tinatian , I will resend the current pr after this [pr](https://github.com/liferay-search/liferay-portal/pull/817) is merged.

**Pull request closed without merging**
