### PR TITLE
LPS-176295 Update Azure Core Libraries to 1.2.9

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-176295](https://issues.liferay.com/browse/LPS-176295)

Notes from @javalosjr96:

> Issue:
> If a customer is using Azure Cloud Services and has multiple pages, there is a chance that too many pages are fetched when a file is fetched.  This can cause the file to never to returned and performance issues.
> 
> Solution:
> Update the Azure Core libraries; the bug was covered in a latest update.

### CODE REVIEW

**Comment by javalosjr96** [comment]
If relevant testing fails, it might be related to the failing Ci tests regarding:
`No results for path: $['companyId']`

**Comment by Kvale1733** [comment]
@mbowerman No regressions found. There are issues with the Azure test on CI. But tested locally and the test passed.

**Comment by yuhai** [comment]
Hi @javalosjr96 and @mbowerman,

The fix looks good to me. Could please do the below changes?

**(1)**. Since com.azure:azure-sdk-bom published new version 1.2.10 yesterday(on Feb 23, 2023). Please upgrade it to 1.2.10. In addition, please change the commit message, just likes:

_Upgrade it to 1.2.10 which can resolve one performance issue, please see https://github.com/Azure/azure-sdk-for-java/commit/af97f53095da369d9e99de280fc77e189dba424a. In addition, 1.0.4‘s dependencies should exist Vulnerabilities issue , please see https://mvnrepository.com/artifact/com.azure/azure-sdk-bom/1.0.4._

**(2)**. After the fix, please add one commit to do "SF, simplify". For the Import-Package part of bnd.bnd. For example.
a. simplify the [codes](https://github.com/javalosjr96/liferay-portal/blob/LPS-176295/modules/apps/portal-store/portal-store-azure/bnd.bnd#L5-L7) for` !com.aayushatharva.brotli4j.*,\`
b. simplify the [codes](https://github.com/javalosjr96/liferay-portal/blob/LPS-176295/modules/apps/portal-store/portal-store-azure/bnd.bnd#L73-L89) for `!org.bouncycastle.*,\`
c...

Please also check other packages. Since generated MANIFEST.MF doesn't import any startwith these packages names.

I am going to close the pr. Please resend it.

Thanks,
Hai

**Comment by javalosjr96** [comment]
@yuhai Understood.

**Pull request closed without merging**
