### PR TITLE
[TS] LPD-1755 | 2-26

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:clustering

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:report:2543237434

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:clustering

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:report:2543802530

**Comment by dantewang** [comment]
ci:test:relevant

Fixing [unique failures](https://github.com/liferay-core-infra/liferay-portal/pull/6676#issuecomment-1966324399) by https://github.com/liferay-core-infra/liferay-portal/pull/6676/commits/773fd796cb3b890ef27c1eefb009f9b72a5d1051

**Comment by dantewang** [comment]
ci:test:clustering

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:report:2544399571

**Comment by dantewang** [comment]
ci:report:2544421602

**Comment by dantewang** [comment]
Failure of `com.liferay.portal.search.facet.faceted.searcher.test.PermissionFilterFacetedSearcherTest` is not unique; the same test case failed in multiple PRs. It's marked unique because the error message contains random text created every time the test is executed.

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:publications

**Comment by tinatian** [comment]
Close, please see my comment at https://liferay.atlassian.net/browse/LPP-52374?focusedCommentId=2590323

**Comment by dantewang** [comment]
@tinatian Can we merge the first 2 commits first so that we don't need to deal with https://github.com/liferay-core-infra/liferay-portal/pull/6697 and https://github.com/liferay-core-infra/liferay-portal/pull/6698?

**Comment by tinatian** [comment]
@dantewang Yes, please send a pull only with the commits you want to merge first

**Pull request closed without merging**
