### PR TITLE
LPS-188045

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
See discussion https://liferay.slack.com/archives/C01FP01V5L0/p1686572378778209?thread_ts=1684829622.186619&cid=C01FP01V5L0

**Comment by Kvale1733** [comment]
ci:test:friendly-url

**Comment by Kvale1733** [comment]
@marianoalvarosaiz No regressions found.

**Comment by tinatian** [comment]
@marianoalvarosaiz Please check my message at https://liferay.slack.com/archives/C01FP01V5L0/p1686586574208859?thread_ts=1684829622.186619&cid=C01FP01V5L0, I do not think LanguageResources should be company aware, I am going to close this pull, please resend.

Thanks.
Tina

**Pull request closed without merging**
