### PR TITLE
[Method Reference] LPS-167246 Convert method reference to ServiceTracker in module portal-messaging

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3201

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:lima

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(7/18 10:20)

**Comment by W2jx** [comment]
no conflicts(7/19 9:37)

**Pull request closed without merging**
