### PR TITLE
LPS-166886 Add integration test

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by dantewang** [comment]
@crodriguezy Conflicts, please rebase

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
No regressions found.

**Comment by dantewang** [comment]
@crodriguezy FYI, https://github.com/liferay-core-infra/liferay-portal/pull/2469

**Pull request closed without merging**
