### PR TITLE
LPD-8475 Remove message bus usage from ConfigurationSynchronousConfigurationListener

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian I extracted this part from the previous LPD-1755 PR.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:clustering

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:forward

**Comment by MrJohn1911** [comment]
ci:forward

CC: @tinatian @dantewang

**Pull request closed without merging**
