### PR TITLE
[Remove immediate=true usage core-infrastructure-3]Lps 169260

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-169260

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
ci:test:startup

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
Possible regressions:
1. All the integration tests were aborted with below messages in console:
```
[beanshell] Waiting for destination (&(destination.name=liferay/background_task)(objectClass=com.liferay.portal.kernel.messaging.Destination))
[beanshell] Waiting for destination (&(destination.name=liferay/background_task)(objectClass=com.liferay.portal.kernel.messaging.Destination))
[beanshell] Waiting for destination (&(destination.name=liferay/background_task)(objectClass=com.liferay.portal.kernel.messaging.Destination))
[beanshell] Waiting for destination (&(destination.name=liferay/background_task)(objectClass=com.liferay.portal.kernel.messaging.Destination))
[beanshell] Waiting for destination (&(destination.name=liferay/background_task)(objectClass=com.liferay.portal.kernel.messaging.Destination))
[beanshell] Waiting for destination (&(destination.name=liferay/background_task)(objectClass=com.liferay.portal.kernel.messaging.Destination))
[beanshell] Waiting for destination (&(destination.name=liferay/background_task)(objectClass=com.liferay.portal.kernel.messaging.Destination))
[beanshell] Waiting for destination (&(destination.name=liferay/background_task)(objectClass=com.liferay.portal.kernel.messaging.Destination))
[beanshell] Waiting for destination (&(destination.name=liferay/background_task)(objectClass=com.liferay.portal.kernel.messaging.Destination))
```
Full console:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-30/test-portal-acceptance-pullrequest(master)/5457/modules-integration-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0

2. Error `No JSON web service action with path /journal.journalarticle/add-article and method POST for journal` thrown when add web content with jsonws.
Example test: [LocalFile.WebContentDisplay#ValidateRemoteCodeViaTemplatesCannotCauseOutOfMemoryErrors](https://testray.liferay.com/home/-/testray/case_results/2071172798)
Full console:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-39/test-portal-acceptance-pullrequest(master)/1837/functional-smoke-startup-tomcat90-mysql57-jdk8/0/18/jenkins-console.txt.gz?authuser=0

3. Staging process status is `NEW` instead of `SUCCESSFUL`.
Example test: [LocalFile.WebContentStaging#PublishInStagingWebContentFromStructure](https://testray.liferay.com/home/-/testray/case_results/2071172850)
Full console:
https://testray.liferay.com/reports/production/logs/2022-11/test-1-39/test-portal-acceptance-pullrequest(master)/1837/functional-smoke-startup-tomcat90-mysql57-jdk8/0/7/jenkins-console.txt.gz?authuser=0

**Comment by slnn** [comment]
Thank @zhangyan0701  for catching this! I will double check  and resend it.

**Comment by slnn** [comment]
Resend in https://github.com/liferay-core-infra/liferay-portal/pull/2728

**Pull request closed without merging**
