### PR TITLE
LPS-190839 upgrade okio to 3.4.0

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

Resent from https://github.com/liferay-core-infra/liferay-portal/pull/5026#issuecomment-1641920841
This is for ticket https://liferay.atlassian.net/browse/LPS-190839
In this Pr, I will upgrade okio to 3.4.0 for the security bug.
Thanks for checking.

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:notifications

**Comment by jeffwu0724** [comment]
ci:test:online-editing

**Comment by Kvale1733** [comment]
ci:test:objects

**Comment by catarineaguiar** [comment]
ci:test:object

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
ci:forward:force

**Comment by jeffwu0724** [comment]
Redo ci:forward:force as last time does not work

**Comment by jeffwu0724** [comment]
ci:forward:force

**Pull request closed without merging**
