### PR TITLE
[Optional Reference] LPS-185138 UpgradeRecorder

### PR DESCRIPTION
**Pull request by haydenzheng314**
Previous: https://github.com/liferay-core-infra/liferay-portal/pull/5064
Ticket: https://issues.liferay.com/browse/LPS-185138

@tinatian @dantewang 
The previous pull failed caused by the empty collection. Because the execution of `UpgradeExecutor` becomes later.

`UpgradeExecutor` publishes release for `com.liferay.change.tracking.service` , `ServiceConfigurationInitializer` registers configuration for the bundle, then `CTStoreRegistrator` activated, it registers two CTStore and get by the collection in `DBUpgrader`.
`UpgradeExecutor` publish the release later makes `CTStoreRegistrator` activate after `DBUpgrader` checks the store collection, so it gets a null collection and throw exception "Missing default Store".

So I make `UpgradeExecutor` activated immediatly to publish the release on time.

### CODE REVIEW

**Comment by LisztLiszt** [comment]
ci:test:upgrade

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by dantewang** [comment]
ci:test:upgrades

**Comment by LisztLiszt** [comment]
Force pushed. Only changed copyright.

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:sf

**Comment by LisztLiszt** [comment]
Force pushed. Only changed copyright in UpgradeStepRegistry.

**Comment by LisztLiszt** [comment]
ci:test:sf

**Comment by LisztLiszt** [comment]
ci:test:relevant

**Comment by LisztLiszt** [comment]
ci:test:upgrade

**Comment by LisztLiszt** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
ci:stop

**Comment by dantewang** [comment]
@LisztLiszt Any update on this?

**Comment by LisztLiszt** [comment]
Please see https://github.com/liferay-core-infra/liferay-portal/pull/5169

**Pull request closed without merging**
