### PR TITLE
[Method References 2] LPS-176632 Convert method reference to ServiceTrackerMap in class CompositeFacetProcessor(module portal-search-solr8-impl)

### PR DESCRIPTION
**Pull request by W2jx**
resend

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3887

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:search-solr

**Comment by Kvale1733** [comment]
@W2jx No regressions.

**Comment by W2jx** [comment]
no conflicts(3/23 15:56)

**Comment by W2jx** [comment]
no conflicts(3/24 14:48)

**Comment by W2jx** [comment]
no conflicts(3/27 9:41)

**Pull request closed without merging**
