### PR TITLE
LPD-37967 Populate Objects data

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPD-38523](https://liferay.atlassian.net/browse/LPD-38523)

## Motivation

Generate data with `SampleSQLBuilder` for performance test of the Objects component 

[LPD-38523]: https://liferay.atlassian.net/browse/LPD-38523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by tinatian** [comment]
@slnn Please take this over. Thanks!

**Comment by slnn** [comment]
> @slnn Please take this over. Thanks!

OK, got it

**Comment by slnn** [comment]
Please see https://github.com/liferay-core-infra/liferay-portal/pull/7614

**Comment by slnn** [comment]
Please see https://github.com/liferay-core-infra/liferay-portal/pull/7619

**Pull request closed without merging**
