### PR TITLE
[Move Expando: cleanup Portal, PortalImpl and PortalUtil]Lps 191477

### PR DESCRIPTION
**Pull request by slnn**
https://liferay.atlassian.net/browse/LPS-191477

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@slnn semver error:

```
     [echo] 
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.util                            MAJOR      51.0.0     51.0.0     52.0.0     VERSION INCREASE REQUIRED
[beanshell] 	>   class      com.liferay.portal.util.PortalImpl
[beanshell] 		-   method     getExpandoValue(javax.portlet.PortletRequest,java.lang.String,int,java.lang.String)
[beanshell] 			-   return     java.io.Serializable
[beanshell] [Baseline Warning] Bundle Version Change Recommended: 84.0.0
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-08/test-1-40/test-portal-acceptance-pullrequest(master)/4745/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:license

**Review by dantewang — APPROVED** [review]

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
> @slnn semver error:
> 
> ```
>      [echo] 
> [beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
> [beanshell] = ================================================== ========== ========== ========== ========== ==========
> [beanshell] * com.liferay.portal.util                            MAJOR      51.0.0     51.0.0     52.0.0     VERSION INCREASE REQUIRED
> [beanshell] 	>   class      com.liferay.portal.util.PortalImpl
> [beanshell] 		-   method     getExpandoValue(javax.portlet.PortletRequest,java.lang.String,int,java.lang.String)
> [beanshell] 			-   return     java.io.Serializable
> [beanshell] [Baseline Warning] Bundle Version Change Recommended: 84.0.0
> ```
> 
> full log [here](https://testray.liferay.com/reports/production/logs/2023-08/test-1-40/test-portal-acceptance-pullrequest(master)/4745/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

Forced push with the update for the sematic version, thank @catarineaguiar for catching this!

**Comment by tinatian** [comment]
ci:forward:force

**Comment by slnn** [comment]
ci:forward:force

**Comment by dantewang** [comment]
@slnn Please fix sem ver and resend, thanks.

**Comment by slnn** [comment]
Please see https://github.com/liferay-core-infra/liferay-portal/pull/5260

**Pull request closed without merging**
