### PR TITLE
[Components with more than 1 service] LPS-172925 Refactor DTOConverter components with more than 1 service type from headless-commerce-admin-pricing-impl module

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:commerce

**Comment by zhangyan0701** [comment]
Declarative Service Unsatisfied Component check warning when portal startup:
2023-03-09 19:46:29.862 WARN  [main][SystemCheckOSGiCommands:154] Declarative Service Unsatisfied Component Checker check result: 
```
Bundle {id: 976, name: com.liferay.headless.commerce.admin.pricing.impl, version: 4.0.57}
	Declarative Service {id: 4553, name: com.liferay.headless.commerce.admin.pricing.internal.resource.v2_0.ChannelResourceImpl, unsatisfied references: 
		{name: _channelDTOConverter, target: null}
	}
	Declarative Service {id: 4506, name: com.liferay.headless.commerce.admin.pricing.internal.graphql.servlet.v2_0.ServletDataImpl, unsatisfied references: 
		{name: _channelResourceComponentServiceObjects, target: null}
	}
	Declarative Service {id: 4584, name: com.liferay.headless.commerce.admin.pricing.internal.resource.v2_0.factory.ChannelResourceFactoryImpl, unsatisfied references: 
		{name: _componentServiceObjects, target: null}
	}
```
Full console log:
https://testray.liferay.com/reports/production/logs/2023-03/test-1-36/test-portal-acceptance-pullrequest(master)/3176/functional-smoke-tomcat90-mysql57-jdk8_stable/0/0/jenkins-console.txt.gz?authuser=0

**Comment by RenanUmV** [comment]
ci:test:commerce

**Comment by RenanUmV** [comment]
ci:test:sf

**Pull request closed without merging**
