### PR TITLE
[DL Performance] LPS-153703 5-17

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian 

@GinsonRen Please run a DL diff for this PR, thanks!

### CODE REVIEW

**Comment by dantewang** [comment]
Hi @catarineaguiar, could you review the CI test results when they finish? Thanks!

**Comment by catarineaguiar** [comment]
@dantewang no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
