### PR TITLE
LPS-146007 Remove jsr107cache.jar

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @vicnate5, Can you please help to scan these test results? Thx

**Comment by vicnate5** [comment]
@rafaprax No regressions found.

**Comment by rafaprax** [comment]
Hey @tinatian, this pr is ready for your review. Thx

**Comment by tinatian** [comment]
@rafaprax The code looks good to me, but it has code conflicts, please rebase and resend.

The jsr107cache.jar was a dependency of ehcache 1.4 which added by https://issues.liferay.com/browse/LEP-5166, it is no longer needed as current ehcache version does not depend on it.

Thanks.
Tina.

**Comment by tinatian** [comment]
@rafaprax Please ignore my last comment, just noticed that you have updated the pull.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go. 

The jsr107cache.jar was a dependency of ehcache 1.4 which added by https://issues.liferay.com/browse/LEP-5166, it is no longer needed as current ehcache version does not depend on it.

Tina

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/112765

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
