### PR TITLE
[Method References 2] LPS-164902 Remove unused reference variable in module analytics-reports-web(dxp)

### PR DESCRIPTION
**Pull request by W2jx**
Hi @tinatian @dantewang , I have removed unused reference variable in module analytics-reports-web(dxp).

### CODE REVIEW

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:tango-analytics-cloud

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
ci:stop:tango-analytics-cloud

**Comment by zhangyan0701** [comment]
ci:test:tango-analytics-cloud

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
