### PR TITLE
LPS-180708 A text field might have a blank value

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
If an empty string (blank or whitespace(s)) is entered in a custom text field and then saved, it will be filled with the default value upon reload.

Proposed Solution
========
Modified the condition to account for blank string values.

Steps to Verify
========
Please see the linked LPS for the reproduction steps.
https://issues.liferay.com/browse/LPS-180708

Thank you and best regards,
István

### CODE REVIEW

**Comment by Kvale1733** [comment]
@IstvanD No regressions. Testing passed following the ticket steps.

**Comment by yuhai** [comment]
Hi @IstvanD,

For the fix, I think we may only remove the below codes:
```
if (Validator.isNull(String.valueOf(value))) {
		value = defaultValue;
}
```

Because the value is from https://github.com/liferay-core-infra/liferay-portal/blob/2fb62b9e59b4996591335abca14bfcfd65db4f90/modules/apps/expando/expando-taglib/src/main/resources/META-INF/resources/custom_attribute/page.jsp#L37

 And it will invoke  ExpandoValueLocalServiceImpl#getData(), if the value doesn't exist in the expandoValue, it will use defaultValue. **The api will include the real value or default value check**.

For the other cases, for example,
```
<c:when test="<%= type == ExpandoColumnConstants.BOOLEAN %>">
<c:when test="<%= type == ExpandoColumnConstants.DATE %>">
```
I think we may remove related defaultValue logic, for example, https://github.com/liferay-core-infra/liferay-portal/blob/2fb62b9e59b4996591335abca14bfcfd65db4f90/modules/apps/expando/expando-taglib/src/main/resources/META-INF/resources/custom_attribute/page.jsp#L78-L80,


And change the case https://github.com/liferay-core-infra/liferay-portal/blob/2fb62b9e59b4996591335abca14bfcfd65db4f90/modules/apps/expando/expando-taglib/src/main/resources/META-INF/resources/custom_attribute/page.jsp#L98-L103

for
```
if (value != null) { 
 		valueDate.setTime((Date)value); 
 }
```

Please also check if defaultValue is necessary for the other cases.

In addition, please send the pr to liferay-usm user to review. You may cc me at the new pr.

Please let me know if you have other concerns.

Thanks,
Hai

**Comment by IstvanD** [comment]
Hi @yuhai 

Thank you for the reply. I modified the solution and have sent it to @liferay-usm:
https://github.com/liferay-usm/liferay-portal/pull/1039

As for the other field types, there is no option to define the default/starting values.

**Comment by yuhai** [comment]
Hi @IstvanD,

I am going to close the pr. Please let me know if there is anything to discuss.

Thanks,
Hai

**Pull request closed without merging**
