### PR TITLE
[Optional Reference]LPS-185570 change-tracking

### PR DESCRIPTION
**Pull request by JanisZhang**
I had confirmed with the author, we should convert the optional to a mandatory reference.

previous:https://github.com/liferay-core-infra/liferay-portal/pull/4621

Ticket:https://issues.liferay.com/browse/LPS-185570

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
@JanisZhang Please update the commit message to briefly explain why this should be a hard ref.

**Comment by JanisZhang** [comment]
Hi @dantewang , force-pushed, I only changed the commit message. Thanks!

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/135863

**Pull request closed without merging**
