### PR TITLE
[Bug Fix]LPS-153996

### PR DESCRIPTION
**Pull request by tinatian**
Rebased from https://github.com/liferay-core-infra/liferay-portal/pull/824

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@diogocordeiro @miltonmc This is the best solution to me. We have to make this cached as the 12% performance regression we found if we do not have it. Could you please update your document about this?

Thanks.
Tina.

**Comment by rodrigopaulino** [comment]
Hey, @tinatian. Thanks for working on this. Did this make into master?
I'm just asking because I think this should remain a json object or perhaps a map, not a string. Otherwise, FE will have to always deserialize it.

**Comment by dantewang** [comment]
@rodrigopaulino Do you need the `JSONObject` in other Java code?

For now the only usage is in a JSP in which a Javascript is rendered. In this usage, even if you put a `JSONObject` there, it will be serialized into a `String` during JSP rendering, and this serialization will cause 12% performance regression (which will affect the numbers we put in the performance whitepaper).

Also if you want to query it in pure Java code you should always just call `PropsUtil` with the feature flag prefix.

**Comment by rodrigopaulino** [comment]
Thanks for detailing the issue, @dantewang. Do you happen to know what would be the performance degradation of deserializing back to a map this string in the JSP? The global `Liferay.FeatureFlags` is no good if it's just a string, therefore we need to convert it to a map.

**Comment by dantewang** [comment]
@rodrigopaulino Generally we need to avoid json serialization/deserialization as much as possible.

What I don't understand is, Liferay.featureFlag is used by JS right? As I said, the JSP I mentioned renders a Javascript code snippet which contains the content of Liferay.featureFlag. So if the whole snippet is then interpreted/executed by the browser, why does it make any difference whether you put a string or a JSONObject in the JSP? The render output will only be string.

So I wonder whether you still have any planned usage on the JSONObject or some map directly, in Java?

**Pull request closed without merging**
