### PR TITLE
master qa 71203

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-71203

### CODE REVIEW

**Comment by kyle-miho** [comment]
This will fix the dependency issues that prevents this bundle from starting up

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@kyle-miho Please help me scan test results.

Thanks.
Tina.

**Comment by kyle-miho** [comment]
@tinatian failures unrelated

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

 The "com.liferay.portal.settings.lang" bundle was removed at https://github.com/liferay/liferay-portal/commit/80722acc4766db0d3b6385abd9ea5d97c1ef8214

Tina

**Pull request closed without merging**
