### PR TITLE
[Method References 3] LPS-179870 journal-web

### PR DESCRIPTION
**Pull request by JanisZhang**
previous: https://github.com/liferay-core-infra/liferay-portal/pull/4039

https://issues.liferay.com/browse/LPS-179870

Changes in this pull: 
-  I removed the unused field reference and added one extra ServletContext. 

Thanks!

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:echo

**Comment by JanisZhang** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
@JanisZhang No regressions found.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
