### PR TITLE
[Method References]Lps 181008 2

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-181008

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:smoke

**Comment by slnn** [comment]
ci:test:frontend

**Review by dantewang — APPROVED** [review]

**Comment by tinatian** [comment]
@slnn @dantewang I would like to have a talk with you about this pull. Please slack me when you are avaiable.

**Comment by slnn** [comment]
Will update and resend to apply the way in the talk.

**Comment by slnn** [comment]
Resend in https://github.com/liferay-core-infra/liferay-portal/pull/4686

**Pull request closed without merging**
