### PR TITLE
[Bug Fix] LPS-151283

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, @tinatian, hsql issue revealed by upgrading Hibernate.

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
ci:test:backend-hypersonic

**Comment by vicnate5** [comment]
@zhangyan0701 Can you check these results here?

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
