### PR TITLE
Lpd 19868 array utils 3 6 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:report:2548329631

**Comment by tinatian** [comment]
ci:report:2548329631

**Comment by julschong** [comment]
@tinatian Not sure if they are related
but all failed with `testRun: Failed to run test on CI`
going to check locally

```
com.liferay.portal.search.rest.resource.v1_0.test.SuggestionResourceTest
com.liferay.portal.search.rest.resource.v1_0.test.SearchResultResourceTest
com.liferay.portal.search.document.test.DocumentBuilderInstantiationTest
com.liferay.portal.search.aggregations.test.AggregationsInstantiationTest
com.liferay.portal.search.admin.web.internal.portlet.action.test.EditMVCActionCommandTest
com.liferay.portal.osgi.debug.spring.extender.test.SpringExtenderDependencyManagerTest
com.liferay.portal.osgi.debug.declarative.service.test.DeclarativeServiceDependencyManagerTest
com.liferay.fragment.util.test.FragmentEntryConfigurationParserTest
```

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/148049

**Pull request closed without merging**
