### PR TITLE
[Reference cleanup]LPS-161060

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to convert method references to field references in analytics/*. Thanks!
https://issues.liferay.com/browse/LPS-161060

previous PR:https://github.com/liferay-core-infra/liferay-portal/pull/1415

### CODE REVIEW

**Comment by tinatian** [comment]
@JanisZhang Code looks good to me, wait for QA to scan test results.

Tina

**Comment by tinatian** [comment]
@zhangyan0701 Please help me scan test results.

Thanks.
Tina

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:analytics-cloud-acceptance

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
@tinatian QA check passed.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122242

**Pull request closed without merging**
