### PR TITLE
LPS-150044 Remove ModularTrashEntryServiceWrapper getEntries() functionality

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina, @tinatian

[LPS-150044](https://issues.liferay.com/browse/LPS-150044) subtask of [LPS-149460](https://issues.liferay.com/browse/LPS-149460):

We would like to see if we can throw UnsupportedOperationException to fix this issue so that we can remove the incorrect adapt method usage.

Below is the commit message:
When we are moving petra-model-adapt into core/petra, we found that getEntries methods in ModularTrashEntryServiceWrapper incorrectly use ModelAdapterUtil.adapt() by passing in a concrete class instead of an interface.
This causes the method to throw IllegalArgumentException. Java Proxy API requires the use of an interface.
Since the original TrashEntryList class in kernel has been deprecated and no other classes use these methods, we decide to throw the exception to note that this operation is not supported. Other solutions may require additional time to implement either a wrapper class for TrashEntryList or extend ASMWrapperUtil's createWrapper method to support both interface and class.

Thank you,

### CODE REVIEW

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@kyle-miho
Hi Kyle,
Could you please help me scan this test result?
Thank you

**Comment by kyle-miho** [comment]
@julschong failures are unrelated

**Comment by julschong** [comment]
@tinatian Hi Tina,
Could you please help review this pull?
Thank you!

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go. The logic Julius removed in this pull is actually wrong, it did not show up for 5 years as no one is using it at all, thus we decided to null out the method by throwing unsupport exception.

Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115094
What's the reason we need to keep the deprecared TrashEntryService ?

**Comment by shuyangzhou** [comment]
ci:close

**Comment by tinatian** [comment]
@shuyangzhou 

> What's the reason we need to keep the deprecared TrashEntryService ?
We can not remove it as it is used by DLAppServiceImpl which is in portal-impl.

**Comment by shuyangzhou** [comment]
Ok, if we can make enough progress on the deprecation removal, we don't need the sf check.

**Pull request closed without merging**
