### PR TITLE
[Remove Stream/Optional usage] LPS-175357  modules: layout-page-template-admin-web,  layout-page-template-service,  layout-page-template-test,  layout-portlets-web,  layout-reports-web,  layout-seo-web-test

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-175357

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
no regressions found.

**Pull request closed without merging**
