### PR TITLE
[Remove unused field] LPS-199731 Remove unused reference field in calsses AssetEntryItemSelectorView, AssetEntryInfoItemFieldValuesProvider and ChildSitesItemSelectorView

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:test:help

**Comment by W2jx** [comment]
no conflicts(10/24 8:21)

**Comment by catarineaguiar** [comment]
@W2jx SF issue doesn't seem related.

No regressions were found

**Comment by W2jx** [comment]
no conflicts(10/25 9:56)

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142696

**Pull request closed without merging**
