### PR TITLE
[Remove Stream/Optional usage] LPS-171132 leftover usages in data-engine-taglib

### PR DESCRIPTION
**Pull request by JanisZhang**
Remove stream usages in DataLayoutBuilderTag

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:data-engine

**Comment by liuxingye** [comment]
Hi @dantewang
The failed tests of the following test suits are not related to this pull. Could you help to label this as _QA Passed_ when you get a chance? Thanks.

- [ci:test:data-engine](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2239330561)
- [ci:test:relevant ](https://testray.liferay.com/home/-/testray/runs?tab=results&testrayBuildId=2237801308)

**Comment by JanisZhang** [comment]
Add QA passed label base's on @liuxingye 's results.

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
