### PR TITLE
LPS-142278 Remove portal lib dir | Rebased 12-16

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@tinatian @vicnate5

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@koor4356 Can you check this one too?

**Comment by vicnate5** [comment]
@koor4356 I am re-running since LPS-144012 blocked most of the functional results. Please check when we get the new results.

**Comment by vicnate5** [comment]
ci:test

**Comment by koor4356** [comment]
@vicnate5 
So this PR should wait for the retest, right?

**Comment by vicnate5** [comment]
@koor4356 It needs another rebase. Can you fetch and try to rebase yourself? If you run into conflicts then we will need to wait.

**Comment by koor4356** [comment]
okay, will try.

**Comment by koor4356** [comment]
I fetch and try to rebase but I ran into conflict.

`CONFLICT (content): Merge conflict in portal-impl/bnd.bnd
error: could not apply a046e5329b9c... LPS-142278 SemVer
Resolve all conflicts manually, mark them as resolved....`

**Comment by koor4356** [comment]
@tinatian @dantewang @vicnate5 
Can someone rebase this, please?

**Comment by vicnate5** [comment]
I rebased it
https://github.com/liferay-core-infra/liferay-portal/pull/80

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
