### PR TITLE
[Remove unused reference] LPS-165888

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi @dantewang @tinatian,

This PR is to remove unused fields in `document-library-web`. Thanks!

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:help

**Comment by JanisZhang** [comment]
ci:test:document

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by JanisZhang** [comment]
Hi @dantewang Force-pushed, I dropped 1 commit that was used to remove the unused field _portal in InfoPanelMVCResourceCommand, As I found it has a hidden usage in the static method. Thanks!

cc/ @zhangyan0701

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
No regressions found.

cc/ @zhangyan0701

**Comment by catarineaguiar** [comment]
@JanisZhang no regressions found.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/125470

**Pull request closed without merging**
