### PR TITLE
[Reflection] LPD-15179 Remove ObjectGrapthUtil

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
added commit message

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:report:2525680871

**Comment by julschong** [comment]
no regression found

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:reoport:2529594883

**Comment by tinatian** [comment]
ci:report:2529594883

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6518

**Pull request closed without merging**
