### PR TITLE
LPS-162819 -LPS-162804

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:stop

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
@tinatian Regressions found

1. Functional Regression affecting Web Content Tests

Steps to Reproduce:
      i. Create a new blank test site
      ii. Go to Content & Data -> Web Content and Add 3 simple Web Content Articles
      iii. Go to Design -> Display Page Templates
      iv. Add a new Display Page Template with "Web Content Article" as content type and "Basic Web Content" as subtype
      v. Add an Asset Publisher widget to the template and click publish
      vi. Go to Content & Data -> Web Content
      vii. View the first web content (there should be no issue)
      viii. Go back and try to view the second or third created web content
     
 Expected Results: All Web Content Articles Can be viewed and edited.
 Actual Results ${WC Title} is temporarily unavailable message
 
 2. Semver errors
 semantic-versioning-jdk8/0/0
 `* Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:commerce:commerce-service:jar'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$3(ExecuteActionsTaskExecuter.java:186)
     [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:268)`[Full Logs](https://testray.liferay.com/reports/production/logs/2022-09/test-1-27/test-portal-acceptance-pullrequest(master)/5234/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)
     
  modules-semantic-versioning-jdk8/0/2
  `Task :apps:segments:segments-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.segments.service                       MINOR      4.0.0      4.0.0      4.1.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.segments.service.SegmentsEntryLocalServiceUtil
     [exec] 		+   method     loadFinderCache(com.liferay.portal.kernel.dao.orm.FinderPath[])
     [exec] 			+   access     static
     [exec] 			+   return     void`[Full logs](https://testray.liferay.com/reports/production/logs/2022-09/test-1-27/test-portal-acceptance-pullrequest(master)/5234/modules-semantic-versioning-jdk8/0/2/jenkins-console.txt.gz?authuser=0)
     
    modules-semantic-versioning-jdk8/0/1
    ` Task :apps:document-library:document-library-sync-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.document.library.sync.service          MINOR      1.4.0      1.4.0      1.5.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.document.library.sync.service.DLSyncEventLocalServiceUtil
     [exec] 		+   method     loadFinderCache(com.liferay.portal.kernel.dao.orm.FinderPath[])
     [exec] 			+   access     static
     [exec] 			+   return     void`[Full logs](https://testray.liferay.com/reports/production/logs/2022-09/test-1-27/test-portal-acceptance-pullrequest(master)/5234/modules-semantic-versioning-jdk8/0/1/jenkins-console.txt.gz?authuser=0)
     
   
modules-semantic-versioning-jdk8/0/0
`PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.commerce.tax.service                   MINOR      2.1.1      2.1.1      2.2.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.commerce.tax.service.CommerceTaxMethodLocalServiceUtil
     [exec] 		+   method     loadFinderCache(com.liferay.portal.kernel.dao.orm.FinderPath[])
     [exec] 			+   access     static
     [exec] 			+   return     void`[Full logs](https://testray.liferay.com/reports/production/logs/2022-09/test-1-27/test-portal-acceptance-pullrequest(master)/5234/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by Kvale1733** [comment]
@tinatian Regressions found

1. Functional Regression affecting Web Content Tests

Steps to Reproduce:
      i. Create a new blank test site
      ii. Go to Content & Data -> Web Content and Add 3 simple Web Content Articles
      iii. Go to Design -> Display Page Templates
      iv. Add a new Display Page Template with "Web Content Article" as content type and "Basic Web Content" as subtype
      v. Add an Asset Publisher widget to the template and click publish
      vi. Go to Content & Data -> Web Content
      vii. View the first web content (there should be no issue)
      viii. Go back and try to view the second or third created web content
     
 Expected Results: All Web Content Articles Can be viewed and edited.
 Actual Results ${WC Title} is temporarily unavailable message
 
 2. Semver errors
` [exec] > Task :apps:segments:segments-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.segments.service                       MINOR      4.0.0      4.0.0      4.1.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.segments.service.SegmentsEntryLocalServiceUtil
     [exec] 		+   method     loadFinderCache(com.liferay.portal.kernel.dao.orm.FinderPath[])
     [exec] 			+   access     static`  [Full log](https://testray.liferay.com/reports/production/logs/2022-09/test-1-27/test-portal-acceptance-pullrequest(master)/5234/modules-semantic-versioning-jdk8/0/2/jenkins-console.txt.gz?authuser=0)
     
 ` [exec] > Task :apps:document-library:document-library-sync-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.document.library.sync.service          MINOR      1.4.0      1.4.0      1.5.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.document.library.sync.service.DLSyncEventLocalServiceUtil
     [exec] 		+   method     loadFinderCache(com.liferay.portal.kernel.dao.orm.FinderPath[])
     [exec] 			+   access     static` [Full log](https://testray.liferay.com/reports/production/logs/2022-09/test-1-27/test-portal-acceptance-pullrequest(master)/5234/modules-semantic-versioning-jdk8/0/1/jenkins-console.txt.gz?authuser=0)
     
`  [exec] > Task :apps:commerce:commerce-product-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.commerce.product.service               MINOR      29.1.0     29.1.0     29.2.0     VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.commerce.product.service.CPAttachmentFileEntryLocalServiceUtil
     [exec] 		+   method     loadFinderCache(com.liferay.portal.kernel.dao.orm.FinderPath[])
     [exec] 			+   access     static
     [exec] 			+   return     void
     [exec] 	<   class      com.liferay.commerce.product.service.CPAttachmentFileEntryLocalServiceWrapper` [Full log](https://testray.liferay.com/reports/production/logs/2022-09/test-1-27/test-portal-acceptance-pullrequest(master)/5234/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
@Kvale1733 The regression seems unrelated to this pull, could you please verify one more time?

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Pull request closed without merging**
