### PR TITLE
[Method References 2] LPS-170790 Convert method reference to ServiceTracker in class ActionExecutorManagerImpl(portal-workflow-kaleo-runtime-impl)

### PR DESCRIPTION
**Pull request by W2jx**
Hi @dantewang , I have fixed the wrong logic.

Previous: https://github.com/liferay-core-infra/liferay-portal/pull/3091

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:workflow

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(2/6 8:16)

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian

**Pull request closed without merging**
