### PR TITLE
LPS-172517

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by achaparro** [comment]
Hi @tinatian,

This is an important for our framework so please, send the pull request to the liferay-uniform user so we can review it to be sure all use cases are working and execute the functional tests we have for the log context feature.

Thanks.

cc/ @LuisOrtiz89

**Comment by tinatian** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@tinatian Regression found. Several tests failed before running due to this issue. I was able to reproduce it by running the test locally.

com.liferay.portal.proxy.internal.ASMDelegateProxyFactoryTest
```
   [exec] com.liferay.portal.proxy.internal.ASMDelegateProxyFactoryTest > testClassInitializationFailure FAILED
     [exec]     java.lang.BootstrapMethodError: call site initialization exception
     [exec]         at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
     [exec]         at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
```
```
[exec] com.liferay.portal.proxy.internal.ASMDelegateProxyFactoryTest > classMethod FAILED
     [exec]     java.lang.AssertionError: com.liferay.portal.proxy.internal.ASMDelegateProxyFactory is not fully covered
     [exec]         at com.liferay.whip.agent.InstrumentationAgent._assertClassDataCoverage(InstrumentationAgent.java:343)
     [exec]         at com.liferay.whip.agent.InstrumentationAgent.assertCoverage(InstrumentationAgent.java:66)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
[Log](https://testray.liferay.com/reports/production/logs/2023-01/test-1-27/test-portal-acceptance-pullrequest(master)/6468/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by tinatian** [comment]
@Kvale1733 Did you reproduce this issue without my changes? This issue does not seem to be related to my changes.

**Comment by Kvale1733** [comment]
@tinatian Yes my bad it's reproducible on master. Not sure why this affected all those tests. Going to rerun the tests.

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:upgrade

**Comment by Kvale1733** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
See https://github.com/liferay-uniform/liferay-portal/pull/903

**Pull request closed without merging**
