### PR TITLE
[TS] LPS-199442

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, the previous pr is https://github.com/liferay-core-infra/liferay-portal/pull/5888

cc @marianoalvarosaiz

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
as this pull was already reviewed by QA before I'm adding QA passed label

**Comment by marianoalvarosaiz** [comment]
@yuhai, @dantewang are there any updates about this pull?

**Comment by dantewang** [comment]
@marianoalvarosaiz Which commit is critical for this bug? https://github.com/liferay-core-infra/liferay-portal/pull/5900/commits/a5060448d88c4eebadf5ddebcae56595fbf1d136 or https://github.com/liferay-core-infra/liferay-portal/pull/5900/commits/6e0c8072f9211ab0a2f595c19d736095e54e6bda?

**Comment by yuhai** [comment]
@dantewang, I think the commit https://github.com/liferay-core-infra/liferay-portal/commit/a5060448d88c4eebadf5ddebcae56595fbf1d136 is critical for this bug. Without it, when execute the command, the NoSuchLayoutException will be thrown.

cc @marianoalvarosaiz

**Comment by marianoalvarosaiz** [comment]
@dantewang, 

@yuhai is correct. 6e0c8072f9211ab0a2f595c19d736095e54e6bda is to remove orphan data, but without it no Exception is thrown.

**Comment by dantewang** [comment]
@marianoalvarosaiz @yuhai So, could you write a bit in detail about the cause in that critical fix commit? Like `LPS-xxxxx Fix XXXException when ... The reason is ...`, because it's not very clear from the current message `Do not consider LayoutRevision since they are removed in _cleanUpLayoutRevisionPortletPreferences()` -- why we shouldn't consider it because it's handled by another method that is not called when you click the certain button?

**Comment by yuhai** [comment]
@dantewang, I did one SF commit, so the pr came from my branch. I just push force the change about the commit message. No logic changes and no need to trigger ci test.

cc @marianoalvarosaiz

**Comment by marianoalvarosaiz** [comment]
Thanks @yuhai

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143154

**Pull request closed without merging**
