### PR TITLE
[Remove Stream/Optional usage] LPS-172794 remove_stream_and_optional_in_portal_tools_rest_builder - part 2

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

Resend from https://github.com/liferay-core-infra/liferay-portal/pull/3152, and fixed the code conflict
In part 2, I am focusing on the ftl files.
This is for ticket https://issues.liferay.com/browse/LPS-172794.
Thanks for checking

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:headless

**Comment by Kvale1733** [comment]
@jeffwu0724 No regressions.

**Comment by tinatian** [comment]
@jeffwu0724 Please merge all the "build REST" into one commit.

**Comment by jeffwu0724** [comment]
@tinatian I have merged all the "build REST" into one commit by running "gw buildREST" at the end. The number of total files change kep the same. The previous test should be still good.

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
working on fixing code conflict

**Comment by jeffwu0724** [comment]
fix the code conflict by running "gw buildREST". The previous test should be good enough

**Comment by tinatian** [comment]
@jeffwu0724 As we talked, please resend.

Thanks.
Tina

**Comment by jeffwu0724** [comment]
Hey @Kvale1733 , do we have this [regression](https://github.com/jeffwu0724/liferay-portal/pull/257#issuecomment-1440446898) here, please?

**Comment by Kvale1733** [comment]
@jeffwu0724 No. Doesn't look like it.

**Pull request closed without merging**
