### PR TITLE
[Optional References]Lps 185571

### PR DESCRIPTION
**Pull request by slnn**
https://issues.liferay.com/browse/LPS-185571

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
@slnn Many tests failed to the same error. Such as

com.liferay.portal.search.elasticsearch7.internal.query.WrapperQueryTest
```
java.lang.NoClassDefFoundError: Could not initialize class com.liferay.portal.search.elasticsearch7.internal.ElasticsearchIndexingFixture$4
		at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchIndexingFixture._createElasticsearchSpellCheckIndexWriter(ElasticsearchIndexingFixture.java:200)
		at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchIndexingFixture._createIndexWriter(ElasticsearchIndexingFixture.java:286)
		at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchIndexingFixture.setUp(ElasticsearchIndexingFixture.java:115)
		at com.liferay.portal.search.test.util.indexing.BaseIndexingTestCase.setUpIndexingFixture(BaseIndexingTestCase.java:323)
		at com.liferay.portal.search.test.util.indexing.BaseIndexingTestCase.setUp(BaseIndexingTestCase.java:120)
		at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
```
[Failed](https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11898/modules-unit-jdk8/0/0/com.liferay.portal.search.elasticsearch7.internal.query.WrapperQueryTest.txt.gz?authuser=0)

**Comment by slnn** [comment]
> @slnn Many tests failed to the same error. Such as
> 
> com.liferay.portal.search.elasticsearch7.internal.query.WrapperQueryTest
> 
> ```
> java.lang.NoClassDefFoundError: Could not initialize class com.liferay.portal.search.elasticsearch7.internal.ElasticsearchIndexingFixture$4
> 		at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchIndexingFixture._createElasticsearchSpellCheckIndexWriter(ElasticsearchIndexingFixture.java:200)
> 		at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchIndexingFixture._createIndexWriter(ElasticsearchIndexingFixture.java:286)
> 		at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchIndexingFixture.setUp(ElasticsearchIndexingFixture.java:115)
> 		at com.liferay.portal.search.test.util.indexing.BaseIndexingTestCase.setUpIndexingFixture(BaseIndexingTestCase.java:323)
> 		at com.liferay.portal.search.test.util.indexing.BaseIndexingTestCase.setUp(BaseIndexingTestCase.java:120)
> 		at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
> 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 		at java.lang.reflect.Method.invoke(Method.java:498)
> ```
> 
> [Failed](https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11898/modules-unit-jdk8/0/0/com.liferay.portal.search.elasticsearch7.internal.query.WrapperQueryTest.txt.gz?authuser=0)

Thank @Kvale1733 for catching this! Will fix and resend.

**Comment by slnn** [comment]
Hi @Kvale1733 

I do not reproduce these failed tests locally, here are my steps:

1>Apply this pull on master and run ant all under portal source
2>Run  `gradlew test ` under modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl
Here are test results and all these outpout, no tests failed.
https://gist.github.com/slnn/b72adb9084b571366b38d880e32dbed9

By the way, I also run the below tests separately under modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl, no tests are failed

1 `gradlew test --tests com.liferay.portal.search.elasticsearch7.internal.query.WrapperQueryTest`
Test results and output: https://gist.github.com/slnn/46da47e2c5edc26facdcb6ee45aad566
2 `gradlew test --tests com.liferay.portal.search.elasticsearch7.internal.query.RegexQueryTest`
Test results and output: https://gist.github.com/slnn/1eb38db704130189dbe61fa56302c32c
3 `gradlew test --tests com.liferay.portal.search.elasticsearch7.internal.mappings.MaxExpansionsTest`
Test results and output: https://gist.github.com/slnn/9ed40a75e93ef810a943f3a702544b3c
4 `gradlew test --tests com.liferay.portal.search.elasticsearch7.internal.query.MatchQueryTest`
Test results and output: https://gist.github.com/slnn/8009009b8e64ad99d1ceace95a85f465

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
no regressions found.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/135920

**Comment by slnn** [comment]
ci:forward

**Comment by slnn** [comment]
Forced push to resolve the conflicts on bnd file, no logic changes

**Comment by slnn** [comment]
ci:forward:force

**Comment by slnn** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/136235

/cc @dantewang

**Pull request closed without merging**
