### PR TITLE
[Remove Stream/Optional usage] LPS-170479 adaptive-media Part 1

### PR DESCRIPTION
**Pull request by dantewang**
https://github.com/liferay-core-infra/liferay-portal/pull/2933

### CODE REVIEW

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:lima

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128582

**Pull request closed without merging**
