### PR TITLE
LPD-41899 11-15

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:core-functional

**Comment by dantewang** [comment]
ci:report:69705498

**Comment by dantewang** [comment]
> # Build completed.
> Testray CSV has been generated successfully for testrayBuildID: 69705498.
> 
> Job Link: [generate-testray-csv](https://test-1-31.liferay.com/job/generate-testray-csv/204/)
> 
> Testray CSV Link: [testray-results-69705498.csv](https://test-1-31.liferay.com/userContent/jobs/generate-testray-csv/builds/204/testray-results-69705498.csv)

No unique failure.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/7644

**Pull request closed without merging**
