### PR TITLE
[Components with more than 1 service] LPS-176895, LPS-177028, LPS-177035, LPS-177025, LPS-177328

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-176895](https://issues.liferay.com/browse/LPS-176895), 
[LPS-177028](https://issues.liferay.com/browse/LPS-177028), 
[LPS-177035](https://issues.liferay.com/browse/LPS-177035), 
[LPS-177025](https://issues.liferay.com/browse/LPS-177025),
[LPS-177328](https://issues.liferay.com/browse/LPS-177328)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:search

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
ci:test:commerce

**Comment by Kvale1733** [comment]
ci:test:search

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Unique failures found:
**1. Error 404 occurs when navigate to Eligibility tab in Warehouses:**

https://user-images.githubusercontent.com/25576873/226593855-55441b5d-d8a9-4c91-bcd0-b6378f435f62.mp4

---------------------
**2. Error "Danger: [object Object]" occurs when add product in Price Modifier:**

https://user-images.githubusercontent.com/25576873/226594439-b4ea8f0e-e491-475a-a93d-c7a2fec6108e.mp4

3. [com.liferay.headless.commerce.admin.inventory.resource.v1_0.test.WarehouseChannelResourceTest](https://testray.liferay.com/home/-/testray/case_results/2237747202) failed with error like below:
`java.lang.IllegalArgumentException: Unsupported field name errorDescription`

Full console log:
https://testray.liferay.com/reports/production/logs/2023-03/test-1-37/test-portal-acceptance-pullrequest(master)/9967/modules-integration-mysql57-jdk8/0/11/jenkins-console.txt.gz?authuser=0

**Pull request closed without merging**
