### PR TITLE
LPS-143632 Remove LanguageUtil from moduels part 1c

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar
Hi Catarine,
could you please help me scan the test result?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by julschong** [comment]
@slnn 
Hi Lily,
Could you please help me review this pull?
Thank you!

CC. @tinatian

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Hi @julschong

Similar issue with https://github.com/liferay-core-infra/liferay-portal/pull/1004

Please see the screenshot, could you rebase with master and forced pushed to this pull?
LPS-143632-pr-1005

Lily

**Comment by julschong** [comment]
rebased

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Hi @tinatian

I have checked the changes in this pull after @julschong's rebasing, and nothing wrong is found.

Lily

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
ci:forward

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
