### PR TITLE
LPS-158170 Skip workflow definition upgrade for new database

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:workflow

**Comment by guilhermedcamacho** [comment]
ci:reevaluate:1297401_3806

**Comment by guilhermedcamacho** [comment]
ci:test:workflow

**Comment by guilhermedcamacho** [comment]
@catarineaguiar please help me check the results, thanks!

**Comment by guilhermedcamacho** [comment]
Hey @catarineaguiar , these unique poshi errors related to workflow suite doesn't seems to be related. I ran locally these two below (without my changes) and they also failed. Maybe you can double check in your machine. Thanks!

[LocalFile.ProcessBuilderKaleoDesignerReact#CanAddMultipleTimers](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/146887//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ProcessBuilderKaleoDesignerReact_CanAddMultipleTimers_)
[LocalFile.ProcessBuilderKaleoDesignerReact#CanNotSaveProcessWithEmptyNodeID](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/140634//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ProcessBuilderKaleoDesignerReact_CanNotSaveProcessWithEmptyNodeID_)

**Comment by catarineaguiar** [comment]
@guilhermedcamacho no regressions found.

**Comment by guilhermedcamacho** [comment]
@shuyangzhou , this PR is ready for your review. Thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121029

**Pull request closed without merging**
