### PR TITLE
[Remove Immediate] LPS-188559 Remove immediate property from DLProcessorRegistryImpl

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://liferay.atlassian.net/browse/LPS-188559

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:test:document

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:document

**Comment by Kvale1733** [comment]
ci:test:document

**Comment by rafaprax** [comment]
conflicts fixed

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:document

**Comment by catarineaguiar** [comment]
no regressions found. SF issue is not related

**Comment by shuyangzhou** [comment]
Please rebase.

**Comment by rafaprax** [comment]
resent https://github.com/liferay-core-infra/liferay-portal/pull/5660

**Pull request closed without merging**
