### PR TITLE
LPS 142380 LPS 160793

### PR DESCRIPTION
**Pull request by jgarcialr**
- LPS-142380 Add validation in ExpandoColumnLocalServiceImpl
- LPS-142380 Add test
- LPS-142380 Use proper method to add the attribute with default value to make sure validation is executed before creating the value
- LPS-142380 Show error message on UI
- LPS-142380 buildLang
- LPS-142380 SV
- LPS-142380 SF, inline
- LPS-142380 SF, remove unnecessary try-rethrow
- LPS-142380 Use ReflectionUtil to keep the exception instead of wrapping it in a RuntimeException; in this change's case, the UI won't be able to show the error message if the exception is rethrown as RuntimeException.
- LPS-160793 Show error if any custom attribute has an empty value for the default locale
- LPS-160793 Do not fill default language value if it's empty

### CODE REVIEW

**Comment by jgarcialr** [comment]
Please, check #1474 for more info

**Comment by jgarcialr** [comment]
Please check #1474 for more context and info.

**Comment by catarineaguiar** [comment]
@jgarcialr semver issue:

```
  [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/70.0.0/52cd9e313a487a1f5f27d1f1c2616b181cd32d5a/com.liferay.portal.kernel-70.0.0.jar
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-09/test-1-28/test-portal-acceptance-pullrequest(master)/4209/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
@jgarcialr As far as I know, LPS-142380 has been reviewed by us, and required for changes by Brian. If the changes are just about naming or SF, could you directly send this part to Brian for review?

On the other hand, for LPS-160793, is it possible to resolve the issue without adding validation logic to DL? Is it possible to always put the validation in expando code like https://github.com/liferay-core-infra/liferay-portal/pull/1539/commits/87db9185db55367fac4cb1c4984602178c075626?

**Comment by jgarcialr** [comment]
Hi @dantewang,

Thanks for the clarifications, I was just sending the pr because Cristina is on PTO and for getting things move forward.

I'll fix semver and send to Brian LPS-142380.

Regarding LPS-160793 I'll check if it's possible to solve the issue without the validation logic on DL side.
IMO adding the validation on DL side it's for fast failing and not sending a possible failing update to the backend (DL model and await the fail on asset side when updating the expandos).

**Comment by crodriguezy** [comment]
Next PR: https://github.com/brianchandotcom/liferay-portal/pull/122633

**Pull request closed without merging**
