### PR TITLE
LPS-182384 move portal-upload to modules part One

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina,

This is part One of moving portal-upload to modules. As we talked, in this part we only trying to avoid using uploadservletrequestimpl directly by using factory; and avoid directly using uploadportletrequestimpl by using test-util.
There is still a usage of uploadportletrequestimpl in JSONWebServiceServiceActionTest that I am not sure how to remove yet.
Thanks for checking

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:echo

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:echo

**Comment by zhangyan0701** [comment]
No regressions found.

**Pull request closed without merging**
