### PR TITLE
[Static reference] LPS-181671 Remove method reference by using snapshot in modules info-taglib, item-selector-taglib, journal-taglib, rss-taglib, product-navigation-taglib, ratings-taglib

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by dantewang** [comment]
@W2jx Code change looks good, just it's better to remove unused methods first, like in https://github.com/liferay-core-infra/liferay-portal/pull/4258#pullrequestreview-1385093852

**Review by dantewang — CHANGES_REQUESTED** [review]
@W2jx Please make change as commented.

**Comment by W2jx** [comment]
Hi @dantewang, I have updated them.

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
ci:test:item-selector

**Comment by Kvale1733** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by W2jx** [comment]
no conflicts(4/17 8:08)

**Comment by W2jx** [comment]
no conflicts(4/18 9:28)

**Comment by zhangyan0701** [comment]
Some upgrade tests that enable remote staging failed with error when open staging site after the upgrade.
Steps:

1. Import database dump https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.0.10.15/data-archive/data-archive-remote-staging-with-blogs-entries-mysql.zip.
2. Upgrade database.
3. Add below properties to portal-ext.properties:
```
tunneling.servlet.shared.secret=1234567890123456
auth.verifier.TunnelAuthVerifier.hosts.allowed=
```
4. Start portal.
5. Open staging site.

Result: Below error thrown in console:
```
2023-04-15 00:33:51.803 ERROR [http-nio-8080-exec-3][AllowedIPAddressesValidatorFactory:61] Invalid configured address: 
java.net.UnknownHostException: Unable to resolve domain: 127.0.0.1
```
Example failed test:
[LocalFile.BlogsRemoteStagingUpgrade#CanPublishImageFromContentFieldAfterUpgradeFrom701015Archive](https://testray.liferay.com/home/-/testray/case_results/2270829860)
Full console:
https://testray.liferay.com/reports/production/logs/2023-04/test-1-37/test-portal-acceptance-pullrequest(master)/10654/functional-tomcat90-mysql57-jdk8/14/21/jenkins-console.txt.gz?authuser=0

**Pull request closed without merging**
