### PR TITLE
LPS-195602 Fix model.class.name property in CommerceChannelAccountEntryRelModelResourcePermission

### PR DESCRIPTION
**Pull request by JanisZhang**
I will send kaleo related permission usages after investigation. (https://github.com/liferay-core-infra/liferay-portal/pull/5501). Thanks!

previous:https://github.com/liferay-core-infra/liferay-portal/pull/5507

Ticket: https://liferay.atlassian.net/browse/LPS-195602

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:commerce

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:stable

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou

**Comment by JanisZhang** [comment]
ci:forward:force

**Comment by dantewang** [comment]
Accidentally triggered forward, wait for QA check.

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
