### PR TITLE
[Remove Immediate] LPS-188559 Remove immediate property from DLProcessorRegistryImpl

### PR DESCRIPTION
**Pull request by MrJohn1911**
Ticket: https://liferay.atlassian.net/browse/LPS-188559

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:document

**Comment by MrJohn1911** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
@MrJohn1911 regression found:

```
     [exec] > Task :apps:portal-search:portal-search-test-util:jar
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:20: error: cannot find symbol
     [exec] import com.liferay.document.library.kernel.util.DLProcessor;
     [exec]                                                ^
     [exec]   symbol:   class DLProcessor
     [exec]   location: package com.liferay.document.library.kernel.util
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:21: error: cannot find symbol
     [exec] import com.liferay.document.library.kernel.util.DLProcessorHelper;
     [exec]                                                ^
     [exec]   symbol:   class DLProcessorHelper
     [exec]   location: package com.liferay.document.library.kernel.util
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:22: error: cannot find symbol
     [exec] import com.liferay.document.library.kernel.util.ImageProcessor;
     [exec]                                                ^
     [exec]   symbol:   class ImageProcessor
     [exec]   location: package com.liferay.document.library.kernel.util
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:431: error: cannot find symbol
     [exec] 	private static DLProcessor _dlProcessor;
     [exec] 	               ^
     [exec]   symbol:   class DLProcessor
     [exec]   location: class com.liferay.adaptive.media.document.library.thumbnails.internal.osgi.commands.test.AMThumbnailsOSGiCommandsTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:434: error: cannot find symbol
     [exec] 	private static DLProcessorHelper _dlProcessorHelper;
     [exec] 	               ^
     [exec]   symbol:   class DLProcessorHelper
     [exec]   location: class com.liferay.adaptive.media.document.library.thumbnails.internal.osgi.commands.test.AMThumbnailsOSGiCommandsTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:454: error: cannot find symbol
     [exec] 		extends BasePreviewableDLProcessor implements ImageProcessor {
     [exec] 		                                              ^
     [exec]   symbol:   class ImageProcessor
     [exec]   location: class com.liferay.adaptive.media.document.library.thumbnails.internal.osgi.commands.test.AMThumbnailsOSGiCommandsTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:250: error: incompatible types: DLProcessor.getClass cannot be converted to java.lang.Class<?>
     [exec] 		Class<?> clazz = _dlProcessor.getClass();
     [exec] 		                                      ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:270: error: cannot find symbol
     [exec] 		DLProcessor imagePreviewableDLProcessor =
     [exec] 		^
     [exec]   symbol:   class DLProcessor
     [exec]   location: class com.liferay.adaptive.media.document.library.thumbnails.internal.osgi.commands.test.AMThumbnailsOSGiCommandsTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:275: error: cannot find symbol
     [exec] 				DLProcessor.class.getName(), ImageProcessor.class.getName()
     [exec] 				^
     [exec]   symbol:   class DLProcessor
     [exec]   location: class com.liferay.adaptive.media.document.library.thumbnails.internal.osgi.commands.test.AMThumbnailsOSGiCommandsTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:275: error: cannot find symbol
     [exec] 				DLProcessor.class.getName(), ImageProcessor.class.getName()
     [exec] 				                             ^
     [exec]   symbol:   class ImageProcessor
     [exec]   location: class com.liferay.adaptive.media.document.library.thumbnails.internal.osgi.commands.test.AMThumbnailsOSGiCommandsTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:310: error: incompatible types: DLProcessor.getClass cannot be converted to java.lang.Class<?>
     [exec] 		Class<?> clazz = _dlProcessor.getClass();
     [exec] 		                                      ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:468: error: method does not override or implement a method from a supertype
     [exec] 		@Override
     [exec] 		^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:477: error: method does not override or implement a method from a supertype
     [exec] 		@Override
     [exec] 		^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:482: error: method does not override or implement a method from a supertype
     [exec] 		@Override
     [exec] 		^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:495: error: method does not override or implement a method from a supertype
     [exec] 		@Override
     [exec] 		^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:513: error: method does not override or implement a method from a supertype
     [exec] 		@Override
     [exec] 		^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:521: error: method does not override or implement a method from a supertype
     [exec] 		@Override
     [exec] 		^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:538: error: method does not override or implement a method from a supertype
     [exec] 		@Override
     [exec] 		^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:565: error: method does not override or implement a method from a supertype
     [exec] 		@Override
     [exec] 		^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:570: error: method does not override or implement a method from a supertype
     [exec] 		@Override
     [exec] 		^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails-test/src/testIntegration/java/com/liferay/adaptive/media/document/library/thumbnails/internal/osgi/commands/test/AMThumbnailsOSGiCommandsTest.java:580: error: method does not override or implement a method from a supertype
     [exec] 		@Override
     [exec] 		^
     [exec] 21 errors
     [exec] > Task :apps:adaptive-media:adaptive-media-demo-data-creator-api:javadoc
     [exec] 
     [exec] > Task :apps:adaptive-media:adaptive-media-document-library-thumbnails-test:compileTestIntegrationJava FAILED
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-11/test-1-38/test-portal-acceptance-pullrequest(master)/9787/modules-compile-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
In the last push, I just changed a commit message.

**Comment by MrJohn1911** [comment]
ci:test:sf

**Comment by MrJohn1911** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@MrJohn1911 SF error for breaking change. The conversation in this PR has been pretty long, please resend.

**Pull request closed without merging**
