### PR TITLE
[Method References 2] LPS-171023 Convert method reference to field reference in class IndexResourceImpl

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:workflow-metrics

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
only do semver, no need to rerun test

**Comment by W2jx** [comment]
no conflicts(5/8 15:34)

**Comment by dantewang** [comment]
@W2jx This seems to be an old one, so could you explain a bit about the context? Is it according to our discussion that the various implementations of the WorkflowMetricsIndexNameBuilder are replaced with a single implementation?

**Comment by W2jx** [comment]
> @W2jx This seems to be an old one, so could you explain a bit about the context? Is it according to our discussion that the various implementations of the WorkflowMetricsIndexNameBuilder are replaced with a single implementation?

Hi @dantewang , yes, we want to merge all subclasses of class WorkflowMetricsIndexNameBuilder.

**Comment by W2jx** [comment]
no conflicts(5/11 10:11)

**Comment by W2jx** [comment]
no conflicts(5/12 10:36)

**Comment by W2jx** [comment]
no conflicts(5/15 9:43)

**Comment by dantewang** [comment]
@W2jx Did we confirm with the product team? After the change, we seems to lose the ability to customize new entity-name -> suffix mapping.

**Comment by W2jx** [comment]
> @W2jx Did we confirm with the product team? After the change, we seems to lose the ability to customize new entity-name -> suffix mapping.

Hi @dantewang , From these articles https://learn.liferay.com/w/dxp/process-automation/workflow/using-workflows/workflow-metrics-reports?p_l_back_url=%2Fsearch%3Fq%3DWorkflow%2BMetrics&highlight=Workflow%20Metrics , https://learn.liferay.com/w/dxp/process-automation/workflow/using-workflows/using-workflow-metrics, I don't think customers will customize it and I have asked the [question](https://liferay.slack.com/archives/CL8QTMKGQ/p1684292246827139) in slack and waiting for their response.

**Comment by W2jx** [comment]
Waiting for https://issues.liferay.com/browse/PTR-3933.

**Comment by W2jx** [comment]
Forced push to resolve the conflict about bnd file, no logic changes，no need to rerun test

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:workflow-metrics

**Comment by W2jx** [comment]
no conflicts(5/23 8:20)

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(5/24 13:43)

**Comment by W2jx** [comment]
no conflicts(5/26 15:09)

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
@tinatian The approach is validated by this answer: https://issues.liferay.com/browse/PTR-3933

**Comment by W2jx** [comment]
only do semver, no need to rerun test

**Comment by tinatian** [comment]
@W2jx @dantewang WorkflowMetricsIndexEntityNameConstant is only used in _workflowMetricsIndexNameBuilder.getIndexName().
Please do this:
1. Make WorkflowMetricsIndexEntityNameConstant directly define the post fix for index, for example POSTFIX_PROCESS="-workflow-metrics-processes".
2. Remove WorkflowMetricsIndexNameBuilder and its impl, and make all usages of it like : indexNameBuilder.getIndexName(companyId) + WorkflowMetricsIndexEntityNameConstant.POSTFIX_PROCESS.

Please resend.

Thanks.
Tina.

**Pull request closed without merging**
