### PR TITLE
LPS-144367 Optimize the query to use index

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-144367
Redirected here from https://github.com/liferay-usm/liferay-portal/pull/392#issuecomment-1006033962

/cc @hongvo2308 

Existing index is on classNameId, classPK and isn't currently used due to classPK being declared second. Adding classNameId to the query resolves the issue.

### CODE REVIEW

**Comment by holatuwol** [comment]
Tests already passed here:
https://github.com/liferay-usm/liferay-portal/pull/392#issuecomment-1000599611

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@holatuwol Changes looks good to me.

**Comment by tinatian** [comment]
@koor4356 Please help me scan the test results.


Thanks.
Tina.

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian No regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This is good to go.


Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/111981

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
