### PR TITLE
[Method References] LPS-170390 Convert method references to field references in module users-admin

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
no conflicts(2022/12/8 9:17)

**Comment by W2jx** [comment]
no conflicts(12/9 9:50)

**Comment by W2jx** [comment]
no conflicts(12/12 10:10)

**Comment by dantewang** [comment]
ci:forward

@shuyangzhou @tinatian This one is a simple replacement.

**Pull request closed without merging**
