### PR TITLE
[DL tuning] LPS-153797

### PR DESCRIPTION
**Pull request by yuhai**
@dantewang, after [LPS-153702](https://issues.liferay.com/browse/LPS-153702) merged, the fix will be shortcut. But if I enable "Show Actions" in "Document and Media"- Configuration, the fix will take effect. I wrote the explanation in ticket's description.

cc @slnn

### CODE REVIEW

**Comment by tinatian** [comment]
@catarineaguiar Please help me scan test results.

Thanks.
Tina

**Comment by catarineaguiar** [comment]
@yuhai no regressions found.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by shuyangzhou** [comment]
@yuhai please get rid of the stream usage whenever you run into it. No need to actively search them to remove, just if you are modifying some code and they are using stream carelessly like this, get rid of it by the way.

**Comment by yuhai** [comment]
@shuyangzhou, got it. I will resend it.

**Pull request closed without merging**
