### PR TITLE
LPS-143632 Remove LanguageUtil from moduels part 1d

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
@catarineaguiar
Hi Catarine,
could you please help me scan the test result?
Thank you!

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by julschong** [comment]
@slnn 
Hi Lily,
Could you please help me review this pull?
Thank you!

CC. @tinatian

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Hi @julschong 

Could you rebase and force push to this pull? Similar issue that non-related commit appeared when releasing this pull with master.

LPS-143632-pr-1009

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
rebased

**Comment by slnn** [comment]
Hi @tinatian

I have checked the changes in this pull after @julschong's rebasing, and nothing wrong is found.

Lily

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
ci:forward

**Pull request closed without merging**
