### PR TITLE
LPS-128171

### PR DESCRIPTION
**Pull request by julschong**
@tinatian, submit again from #46

### CODE REVIEW

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please help me scan the test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@koor4356 can you check this one?

**Comment by koor4356** [comment]
okay, thanks!

**Comment by koor4356** [comment]
@tinatian @julschong @vicnate5,
No unique failures.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.


Tina.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/110860

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
