### PR TITLE
[Remove Blocking usages] LPS-188565 Directly using reference or snapshot in modules

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@W2jx Regression found. The following appears at startup

```
[beanshell] 2023-07-13 10:01:18.187 INFO  [SystemExecutorServiceUtil-8][BundleSiteInitializer:647] Initialized com.liferay.site.initializer.welcome for group 20119 in 5745 ms
[beanshell] 2023-07-13 10:01:21.683 INFO  [main][SystemCheckOSGiCommands:77] Running system check
[beanshell] 2023-07-13 10:01:21.684 INFO  [main][SystemCheckOSGiCommands:115] Available checkers :[Missing Component Scanner, Spring Extender Unavailable Component Checker, Declarative Service Soft Circular Dependency Checker, Declarative Service Unsatisfied Component Checker]
[beanshell] 2023-07-13 10:01:21.684 INFO  [main][SystemCheckOSGiCommands:131] Running "Missing Component Scanner". You can run this by itself with command "ds:missing" in gogo shell.
[beanshell] 2023-07-13 10:01:21.687 INFO  [main][SystemCheckOSGiCommands:143] Missing Component Scanner check result: No issues were found.
[beanshell] 2023-07-13 10:01:21.687 INFO  [main][SystemCheckOSGiCommands:131] Running "Spring Extender Unavailable Component Checker". You can run this by itself with command "dm na" in gogo shell.
[beanshell] 2023-07-13 10:01:21.690 INFO  [main][SystemCheckOSGiCommands:143] Spring Extender Unavailable Component Checker check result: No issues were found.
[beanshell] 2023-07-13 10:01:21.691 INFO  [main][SystemCheckOSGiCommands:131] Running "Declarative Service Soft Circular Dependency Checker". You can run this by itself with command "ds:softCircularDependency" in gogo shell.
[beanshell] 2023-07-13 10:01:22.205 ERROR [main][ROOT:56] bundle com.liferay.blogs.web:6.0.103 (1436)[com.liferay.blogs.web.internal.upload.TempImageBlogsUploadFileEntryHandler(11677)] : findField: Suitable but non-accessible field _mimeTypes in class com.liferay.blogs.web.internal.upload.ImageBlogsUploadFileEntryHandler, subclass of component class com.liferay.blogs.web.internal.upload.TempImageBlogsUploadFileEntryHandler
[beanshell] 2023-07-13 10:01:24.562 INFO  [main][SystemCheckOSGiCommands:143] Declarative Service Soft Circular Dependency Checker check result: No issues were found.
[beanshell] 2023-07-13 10:01:24.562 INFO  [main][SystemCheckOSGiCommands:131] Running "Declarative Service Unsatisfied Component Checker". You can run this by itself with command "ds:unsatisfied" in gogo shell.
[beanshell] 2023-07-13 10:01:36.825 INFO  [main][SystemCheckOSGiCommands:143] Declarative Service Unsatisfied Component Checker check result: No issues were found.
```
[Log](https://testray.liferay.com/reports/production/logs/2023-07/test-1-40/test-portal-acceptance-pullrequest(master)/4160/functional-smoke-tomcat90-hypersonic20-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:startup

**Comment by W2jx** [comment]
no conflicts(7/17 8:16)

**Comment by catarineaguiar** [comment]
@W2jx some regressions found:

```
     [exec] > Task :apps:portal-search:portal-search-web:compileTestJava
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/portal-search/portal-search-web/src/test/java/com/liferay/portal/search/web/internal/search/bar/portlet/display/context/factory/SearchBarPortletDisplayContextFactoryTest.java:427: error: constructor SearchBarPortletDisplayContextFactory in class com.liferay.portal.search.web.internal.search.bar.portlet.display.context.factory.SearchBarPortletDisplayContextFactory cannot be applied to given types;
     [exec] 				new SearchBarPortletDisplayContextFactory(
     [exec] 				^
     [exec]   required: com.liferay.portal.kernel.module.configuration.ConfigurationProvider,com.liferay.portal.kernel.service.LayoutLocalService,com.liferay.portal.kernel.util.Portal,javax.portlet.RenderRequest
     [exec]   found: com.liferay.portal.kernel.service.LayoutLocalService,com.liferay.portal.kernel.util.Portal,javax.portlet.RenderRequest
     [exec]   reason: actual and formal argument lists differ in length
     [exec] 
     [exec] > Task :apps:portal-search:portal-search-web:compileTestJava FAILED
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-07/test-1-40/test-portal-acceptance-pullrequest(master)/4205/modules-unit-jdk8/0/2/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.headless.delivery.resource.v1_0.test.StructuredContentResourceTest > testDeleteSiteStructuredContentByExternalReferenceCode FAILED
     [exec]     com.liferay.headless.delivery.client.problem.Problem$ProblemException: No JournalFolder exists with the primary key 8708362196437360709
     [exec]     	at com.liferay.headless.delivery.client.resource.v1_0.StructuredContentResource$StructuredContentResourceImpl.postSiteStructuredContent(StructuredContentResource.java:2113)
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.BaseStructuredContentResourceTestCase.testDeleteSiteStructuredContentByExternalReferenceCode_addStructuredContent(BaseStructuredContentResourceTestCase.java:1895)
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.BaseStructuredContentResourceTestCase.testDeleteSiteStructuredContentByExternalReferenceCode(BaseStructuredContentResourceTestCase.java:1856)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-07/test-1-40/test-portal-acceptance-pullrequest(master)/4205/modules-integration-mysql57-jdk8/1/22/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.content.dashboard.web.internal.item.type.ContentDashboardItemSubtypeUtilTest > testToContentDashboardItemSubtypeByJSONObject FAILED
     [exec]     java.lang.AssertionError
     [exec]         at org.junit.Assert.fail(Assert.java:86)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:52)
     [exec]         at com.liferay.content.dashboard.web.internal.item.type.ContentDashboardItemSubtypeUtilTest._getContentDashboardItemSubtypeFactory(ContentDashboardItemSubtypeUtilTest.java:175)
     [exec]         at com.liferay.content.dashboard.web.internal.item.type.ContentDashboardItemSubtypeUtilTest.testToContentDashboardItemSubtypeByJSONObject(ContentDashboardItemSubtypeUtilTest.java:89)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
```
     [exec] com.liferay.dynamic.data.mapping.form.web.internal.upload.DDMFormUploadValidatorTest > testValidFileExtension FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.dynamic.data.mapping.form.web.internal.upload.DDMFormUploadValidator.getGuestUploadFileExtensions(DDMFormUploadValidator.java:43)
     [exec]         at com.liferay.dynamic.data.mapping.form.web.internal.upload.DDMFormUploadValidator.validateFileExtension(DDMFormUploadValidator.java:71)
     [exec]         at com.liferay.dynamic.data.mapping.form.web.internal.upload.DDMFormUploadValidatorTest.testValidFileExtension(DDMFormUploadValidatorTest.java:84)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-07/test-1-40/test-portal-acceptance-pullrequest(master)/4205/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.translation.service.test.TranslationEntryLocalServiceTest > testDeleteTranslationEntryDeletesWorkflowLink FAILED
     [exec]     java.lang.RuntimeException: com.liferay.portal.kernel.workflow.WorkflowException: Inactive workflow definition with name Single Approver and version 1
     [exec]     	at com.liferay.portal.kernel.transaction.TransactionCommitCallbackUtil.registerCallback(TransactionCommitCallbackUtil.java:84)
     [exec]     	at com.liferay.portal.kernel.workflow.WorkflowHandlerRegistryUtil.startWorkflowInstance(WorkflowHandlerRegistryUtil.java:162)
     [exec]     	at com.liferay.portal.kernel.workflow.WorkflowHandlerRegistryUtil.startWorkflowInstance(WorkflowHandlerRegistryUtil.java:77)
     [exec]     	at com.liferay.translation.service.test.TranslationEntryLocalServiceTest.testDeleteTranslationEntryDeletesWorkflowLink(TranslationEntryLocalServiceTest.java:177)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-07/test-1-40/test-portal-acceptance-pullrequest(master)/4205/modules-integration-mysql57-jdk8/3/9/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.journal.service.test.JournalArticleLocalServiceTest > testGetArticleDisplayFriendlyURLDisplayPageExists FAILED
     [exec]     com.liferay.portal.kernel.exception.SystemException: java.lang.NullPointerException
     [exec]     	at com.liferay.journal.service.impl.JournalArticleLocalServiceImpl.getArticleDisplay(JournalArticleLocalServiceImpl.java:6479)
     [exec]     	at com.liferay.journal.service.impl.JournalArticleLocalServiceImpl.getArticleDisplay(JournalArticleLocalServiceImpl.java:2310)
     [exec]     	at com.liferay.journal.service.impl.JournalArticleLocalServiceImpl.getArticleDisplay(JournalArticleLocalServiceImpl.java:2364)
     [exec]     	at com.liferay.journal.service.impl.JournalArticleLocalServiceImpl.getArticleDisplay(JournalArticleLocalServiceImpl.java:2395)
     [exec]     	at com.liferay.journal.service.impl.JournalArticleLocalServiceImpl.getArticleDisplay(JournalArticleLocalServiceImpl.java:2492)
     [exec]     	at com.liferay.journal.service.impl.JournalArticleLocalServiceImpl.getArticleDisplay(JournalArticleLocalServiceImpl.java:2521)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-07/test-1-40/test-portal-acceptance-pullrequest(master)/4205/modules-integration-mysql57-jdk8/2/0/jenkins-console.txt.gz?authuser=0)

```
     [exec] com.liferay.asset.info.list.renderer.test.AssetInfoListRendererTest > testAssetInfoListRendererAbstract STARTED
[beanshell] 2023-07-14 19:45:42.870 ERROR [com.liferay.asset.test-executor-thread][BaseJSPAssetRenderer:75] Unable to include JSP /asset/abstract.jsp
[beanshell] org.apache.jasper.JasperException: java.lang.NullPointerException
[beanshell] 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:440) ~[jasper.jar:9.0.75]
[beanshell] 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473) ~[jasper.jar:9.0.75]
[beanshell] 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377) ~[jasper.jar:9.0.75]
[beanshell] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[servlet-api.jar:4.0.FR]
[beanshell] 	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:328) ~[bundleFile:?]
[beanshell] 	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:340) ~[bundleFile:?]
```
```
     [exec] com.liferay.asset.info.list.renderer.test.AssetInfoListRendererTest > testAssetInfoListRendererAbstract FAILED
     [exec]     java.lang.AssertionError: 
     [exec]     Expected: a string containing "YlTgEO0J"
     [exec]          but: was "
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 	
     [exec]     		<ul class="list-unstyled">
     [exec] 
     [exec] 			
     [exec] 
     [exec]     				<li class="">
     [exec] 					
     [exec] 						
     [exec] 
     [exec] 							
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec] 
     [exec]     <div class="asset-summary">
     [exec]     	"
     [exec]     	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
     [exec]     	at org.junit.Assert.assertThat(Assert.java:964)
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-07/test-1-40/test-portal-acceptance-pullrequest(master)/4205/modules-integration-mysql57-jdk8/0/5/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
