### PR TITLE
[Component with its own class name as service type] LPS-193924 Refactor notification component

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://liferay.atlassian.net/browse/LPS-193924

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
ci:test:echo

**Comment by Kvale1733** [comment]
ci:test:lima

**Comment by Kvale1733** [comment]
ci:test:headless

**Comment by Kvale1733** [comment]
ci:test:object

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:startup

**Comment by Valmir-unicap** [comment]
ci:test:object

**Comment by Valmir-unicap** [comment]
ci:test:headless

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
No need to wait for the other suites. I triggered them by mistake since I just saw the file changes without realizing they aren't all related to this LPS. Relevant should be enough.

No regressions found.

**Comment by shuyangzhou** [comment]
ci:forward:force

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139848

**Pull request closed without merging**
