### PR TITLE
LPS-158624 Clean up petra-xml

### PR DESCRIPTION
**Pull request by julschong**
@tinatian Hi Tina,
[fd40f7c](https://github.com/liferay-core-infra/liferay-portal/pull/1599/commits/fd40f7c1e2d4e4a98ffaefb9914ac851350628ab)
in this commit, I had to change the overloaded toString(String) method name to formatXML because other otherloaded method has dom4j Node in its arguments causing class not found exception on usages

Thanks!

### CODE REVIEW

**Comment by julschong** [comment]
pushed to resolve conflict

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
pushed to resolve conflict

**Comment by vicnate5** [comment]
@Kvale1733 can you check this one?

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:reevaluate:1277401_4942

**Comment by tinatian** [comment]
@julschong As we talked, please resend.

Thanks.
Tina

**Pull request closed without merging**
