### PR TITLE
[Component with its own class name as service type] LPS-200508 refactor components from vulcan-api-impl with its own class name as service type

### PR DESCRIPTION
**Pull request by dantewang**
@rcsdnj @rafaprax

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@zhangyan0701 Any other test you think should be triggered?

**Comment by catarineaguiar** [comment]
ci:test:headless

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by dantewang** [comment]
ci:forward

cc @tinatian

**Pull request closed without merging**
