### PR TITLE
LPS-187216 Remove redundant configuration from the MS Outlook Auth Connector configuration

### PR DESCRIPTION
**Pull request by rafaprax**
Ticket: https://liferay.atlassian.net/browse/LPS-187216

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
No regressions found, https://test-1-1.liferay.com/job/generate-testray-csv/7698/

**Comment by dantewang** [comment]
@rafaprax Do we need an upgrade for this change?

**Pull request closed without merging**
