### PR TITLE
[Remove Blocking Usages] LPS-201288 Removing Unnecessary Usages of ServiceProxyFactory.newServiceTrackedInstance with blocking set to true in module commerce-product-service

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by catarineaguiar** [comment]
no regressions found

**Comment by W2jx** [comment]
no conflicts(11/13 9:20)

**Comment by W2jx** [comment]
no conflicts(11/14 15:49)

**Comment by W2jx** [comment]
no conflicts(11/15 10:19)

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:startup

**Comment by W2jx** [comment]
ci:test:upgrade

**Comment by W2jx** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by W2jx** [comment]
no conflicts(11/20 13:57)

**Comment by W2jx** [comment]
no conflicts(11/21 15:06)

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
