### PR TITLE
[TS] LPS-190069 Update Country/Region codes as for latest ISO list

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPS-190069

Resent from: https://github.com/liferay-core-infra/liferay-portal/pull/6480

@shuyangzhou

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:upgrade

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:um

**Comment by smottal** [comment]
@shuyangzhou have you had any chance to take a look at the PR? 
Thank you in advance

**Comment by smottal** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
@brunofalc we need a compare on startup performance for this pull. cold case is more important than warm here.

**Comment by brunofalc** [comment]
ok @shuyangzhou 
let me ask @JerryAdrianoo

**Comment by JerryAdrianoo** [comment]
**Liferay Portal CE Version - Master** 
| Startup Time (ms) Cold start | Shutdown Time (ms)  Cold start |
|--------|--------|
| 51,969 | 4,543 |

------------------------------------------------------

 **Liferay Portal CE Version - Pull Request** 
| Startup Time (ms) Cold start | Shutdown Time (ms)  Cold start |
|--------|--------|
| 44,502 | 4,969 |

This is a big difference between the tests, I ran the startup test on this pull request 2 times and the results are very similar, like:
1st : **_4,2441ms** and **4,867ms**_
2st : _**44,502ms** and **4,969ms**_

**Comment by shuyangzhou** [comment]
@JerryAdrianoo not just single test running, like the warm case, you need to run multiple times, take off the max and min, taking average of the rest, and calculation standard deviation.

Also warm case still needs to be checked, yourkit datapoints are needed too for warm case.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/146956

**Comment by JerryAdrianoo** [comment]
Results of the test: [Spreadsheet](https://docs.google.com/spreadsheets/d/1gkCNF4ggmBCQZRXkENMZgq0EEYfhNMLa7Lcbj18s1QM/edit#gid=1955885127).

**Pull request closed without merging**
