### PR TITLE
remove_deprecated_part_5

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Tina, Shuyang,

I have removed deprecated methods or classes for "portal-impl/src/com/liferay/portlet/asset/service/impl", "portal-impl/src/com/liferay/portlet/asset/service/persistence/impl", "portal-impl/src/com/liferay/portlet/expando/util", "portal-impl/src/com/liferay/portlet/documentlibrary/asset", "portal-impl/src/com/liferay/portlet/asset/util".
Thanks for checking. also see https://github.com/jeffwu0724/liferay-portal/pull/29

Thanks,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
@kyle-miho Hey Kyle, could you please help me to scan the test result?

Thanks,
Jeff

**Comment by jeffwu0724** [comment]
ci:stop

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by kyle-miho** [comment]
@jeffwu0724 relevant results look fine, just waiting for the ci:test:default batch to finish running

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
this pr is good to go @jeffwu0724 failures are unrelated

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina.

**Comment by jeffwu0724** [comment]
> @jeffwu0724 Please note AssetEntryFinder and AssetEntryFinderUtil are generated, I will take it this time as it is simple, please modify ***FinderImpl first, then build service to generate the changes for others next time.
> 
> Tina.

Got it Tina, sorry for the mistakes

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113989

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
