### PR TITLE
[LPS-167246 MessageBus] LPS-192572 Remove Destination.register(MessageListener)

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:backend

**Comment by Kvale1733** [comment]
ci:test:stable

**Comment by Kvale1733** [comment]
ci:test:backend

**Comment by Kvale1733** [comment]
@dantewang Regression found in

com.liferay.portal.db.partition.test.DBPartitionTest
```
     [exec] com.liferay.portal.db.partition.test.DBPartitionTest > classMethod STARTED
     [exec] 
     [exec] com.liferay.portal.db.partition.test.DBPartitionTest > classMethod FAILED
     [exec]     com.liferay.portal.kernel.exception.PortalException: java.lang.NullPointerException
     [exec]     	at com.liferay.portal.db.partition.DBPartitionUtil.addDBPartition(DBPartitionUtil.java:107)
     [exec]     	at com.liferay.portal.db.partition.test.util.BaseDBPartitionTestCase.addDBPartitions(BaseDBPartitionTestCase.java:82)
     [exec]     	at com.liferay.portal.db.partition.test.DBPartitionTest.setUpClass(DBPartitionTest.java:52)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
     [exec]     	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
     [exec]     	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:307)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:86)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
     [exec]     Caused by: java.lang.NullPointerException
     [exec]     	at com.lifer
```
[Log](https://testray.liferay.com/home/-/testray/case_results/2411230917)

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5364

**Pull request closed without merging**
