### PR TITLE
[TS] LPD-23711

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__
<https://liferay.atlassian.net/browse/LPD-23711>

__Prev. Pull Request:__
<https://github.com/liferay-core-infra/liferay-portal/pull/6945>

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:stop

**Comment by kevhlee** [comment]
ci:test:sf

**Comment by kevhlee** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
ci:report:2572997740

**Comment by kevhlee** [comment]
No unique failures detected.

**Comment by tinatian** [comment]
Close as we talked, please resend.

Thanks.
Tina

**Pull request closed without merging**
