### PR TITLE
[TS] LPS-144149

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
Hi @rafaprax, I still think this change is valid, but it causes an integration failure on `JaxWsComponentHandlerRegistrationTest`.

```
2023-12-13 03:05:44.940 ERROR [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.portal.remote.soap.extender.internal.configuration.SoapExtenderConfiguration~782aa257-2f4f-4974-97e8-960706ea492e)][LogService:47] [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.portal.remote.soap.extender.internal.configuration.SoapExtenderConfiguration~782aa257-2f4f-4974-97e8-960706ea492e)] Invocation of 'addService' failed.
org.apache.cxf.service.factory.ServiceConstructionException: null
	at org.apache.cxf.jaxb.JAXBDataBinding.initialize(JAXBDataBinding.java:361) ~[?:?]
	at org.apache.cxf.service.factory.AbstractServiceFactoryBean.initializeDataBindings(AbstractServiceFactoryBean.java:87) ~[?:?]
	at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.buildServiceFromClass(ReflectionServiceFactoryBean.java:469) ~[?:?]
	at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.buildServiceFromClass(JaxWsServiceFactoryBean.java:693) ~[?:?]
	at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.initializeServiceModel(ReflectionServiceFactoryBean.java:529) ~[?:?]
	at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.create(ReflectionServiceFactoryBean.java:262) ~[?:?]
	at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.create(JaxWsServiceFactoryBean.java:199) ~[?:?]
	at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpoint(AbstractWSDLBasedEndpointFactory.java:103) ~[?:?]
	at org.apache.cxf.frontend.ServerFactoryBean.create(ServerFactoryBean.java:168) ~[?:?]
	at org.apache.cxf.jaxws.JaxWsServerFactoryBean.create(JaxWsServerFactoryBean.java:211) ~[?:?]
	at com.liferay.portal.remote.soap.extender.internal.CXFJaxWsServiceRegistrator.registerService(CXFJaxWsServiceRegistrator.java:108) ~[?:?]
	at com.liferay.portal.remote.soap.extender.internal.CXFJaxWsServiceRegistrator._addService(CXFJaxWsServiceRegistrator.java:145) ~[?:?]
	at com.liferay.portal.remote.soap.extender.internal.CXFJaxWsServiceRegistrator.addService(CXFJaxWsServiceRegistrator.java:50) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_381]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_381]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_381]
	at org.apache.felix.dm.impl.InvocationUtil.invokeMethod(InvocationUtil.java:230) ~[bundleFile:?]
	at org.apache.felix.dm.impl.InvocationUtil.invokeCallbackMethod(InvocationUtil.java:181) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.invokeCallback(ComponentImpl.java:665) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ServiceDependencyImpl.invoke(ServiceDependencyImpl.java:517) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ServiceDependencyImpl.invokeCallback(ServiceDependencyImpl.java:327) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.invokeCallback(ComponentImpl.java:1734) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.invokeAddOptionalDependencies(ComponentImpl.java:1671) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.performTransition(ComponentImpl.java:1234) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.handleChange(ComponentImpl.java:1166) ~[bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.lambda$start$2(ComponentImpl.java:502) ~[bundleFile:?]
	at org.apache.felix.dm.impl.SerialExecutor.runTask(SerialExecutor.java:138) [bundleFile:?]
	at org.apache.felix.dm.impl.SerialExecutor.runTasks(SerialExecutor.java:120) [bundleFile:?]
	at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:86) [bundleFile:?]
	at org.apache.felix.dm.impl.SerialExecutor.execute(SerialExecutor.java:105) [bundleFile:?]
	at org.apache.felix.dm.impl.ComponentImpl.start(ComponentImpl.java:500) [bundleFile:?]
	at org.apache.felix.dm.impl.ComponentScheduler.add(ComponentScheduler.java:69) [bundleFile:?]
	at org.apache.felix.dm.DependencyManager.add(DependencyManager.java:141) [bundleFile:?]
	at com.liferay.portal.remote.soap.extender.internal.SoapExtender._enableComponent(SoapExtender.java:174) [bundleFile:?]
	at com.liferay.portal.remote.soap.extender.internal.SoapExtender.activate(SoapExtender.java:51) [bundleFile:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_381]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_381]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_381]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228) [bundleFile:?]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) [bundleFile:?]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664) [bundleFile:?]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510) [bundleFile:?]
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:310) [bundleFile:?]
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:300) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:341) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:983) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:956) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:765) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:666) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:432) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.configurationUpdated(ConfigurableComponentHolder.java:440) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.configurationEvent(RegionConfigurationSupport.java:325) [bundleFile:?]
	at org.apache.felix.scr.impl.manager.RegionConfigurationSupport$2.configurationEvent(RegionConfigurationSupport.java:119) [bundleFile:?]
	at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.sendEvent(ConfigurationManager.java:1689) [bundleFile:?]
	at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.run(ConfigurationManager.java:1640) [bundleFile:?]
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:138) [bundleFile:?]
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:105) [bundleFile:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_381]
Caused by: javax.xml.bind.JAXBException
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:226) ~[?:1.8.0_381]
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:462) ~[?:1.8.0_381]
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:641) ~[?:1.8.0_381]
	at org.apache.cxf.common.jaxb.JAXBContextCache$2.run(JAXBContextCache.java:345) ~[?:?]
	at org.apache.cxf.common.jaxb.JAXBContextCache$2.run(JAXBContextCache.java:343) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_381]
	at org.apache.cxf.common.jaxb.JAXBContextCache.createContext(JAXBContextCache.java:343) ~[?:?]
	at org.apache.cxf.common.jaxb.JAXBContextCache.getCachedContextAndSchemas(JAXBContextCache.java:245) ~[?:?]
	at org.apache.cxf.jaxb.JAXBDataBinding.createJAXBContextAndSchemas(JAXBDataBinding.java:500) ~[?:?]
	at org.apache.cxf.jaxb.JAXBDataBinding.initialize(JAXBDataBinding.java:359) ~[?:?]
	... 60 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory cannot be found by com.liferay.portal.remote.soap.extender.test_1.0.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:404) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:151) ~[org.eclipse.osgi.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_381]
	at javax.xml.bind.ContextFinder.safeLoadClass(ContextFinder.java:579) ~[?:1.8.0_381]
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:224) ~[?:1.8.0_381]
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:462) ~[?:1.8.0_381]
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:641) ~[?:1.8.0_381]
	at org.apache.cxf.common.jaxb.JAXBContextCache$2.run(JAXBContextCache.java:345) ~[?:?]
	at org.apache.cxf.common.jaxb.JAXBContextCache$2.run(JAXBContextCache.java:343) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_381]
	at org.apache.cxf.common.jaxb.JAXBContextCache.createContext(JAXBContextCache.java:343) ~[?:?]
	at org.apache.cxf.common.jaxb.JAXBContextCache.getCachedContextAndSchemas(JAXBContextCache.java:245) ~[?:?]
	at org.apache.cxf.jaxb.JAXBDataBinding.createJAXBContextAndSchemas(JAXBDataBinding.java:500) ~[?:?]
	at org.apache.cxf.jaxb.JAXBDataBinding.initialize(JAXBDataBinding.java:359) ~[?:?]
	... 60 more
```

Looking at the log, it seems what you did in the soap-extender module needs to be done also on the test module and test class.

I wonder if there's any common way to do this (maybe SPIFly?) but I'm on PTO the next whole week. Could you look into it or get someone to fix the test? Thanks!

cc @brunofalc

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/6370

**Pull request closed without merging**
