### PR TITLE
[TS] [Urgent] LPS-195754

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:environment

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:environments

**Comment by yuhai** [comment]
@marianoalvarosaiz, please see the below suggestions:

1. Since the usage used `compileInclude`, please run `ant build-lib-versions` in portal-impl. And then commit the changes.
2. Please remove the commit(a936540503d157deaf032c934264f030bf39a1ee). It lacked related `not like` test. But this isn't the main reason. The main reason is that the test is `UNIT test`. It only asserted sql generated and won't execute the sql by using hibernate. That is to say, the test didn't go through the fix.
3. For the file 02-LPS-195754.patch. It seems lacked of `IrregularBinaryExpression` class change. For example,
```
diff --git a/net/sf/jsqlparser/expression/operators/relational/IrregularBinaryExpression.java b/net/sf/jsqlparser/expression/operators/relational/IrregularBinaryExpression.java
```

**Comment by marianoalvarosaiz** [comment]
@yuhai I've updated the pull

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
@marianoalvarosaiz, after a thinking while, I moved `IrregularBinaryExpression` the class. The reason is the package net.sf.jsqlparser.expression.**operators.relational** seems unmatched our new class. Another reason is placing it to internal package. It should only be used by the internal. This referred to `WriterFactory `class.

Please see https://github.com/liferay-core-infra/liferay-portal/pull/5638

**Pull request closed without merging**
