### PR TITLE
[Method References 3] LPS-179503 site-navigation, commerce 

### PR DESCRIPTION
**Pull request by JanisZhang**
https://issues.liferay.com/browse/LPS-179503

previous: https://github.com/liferay-core-infra/liferay-portal/pull/4004

changes in this pull:
- Removed the `setWrappedService(_accountEntryLocalService);` method, as `serviceWrapperRegistry` will register the actual service.

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:commerce

**Comment by JanisZhang** [comment]
ci:test:echo

**Comment by kyle-miho** [comment]
Failured unrelated, PR is good to go @JanisZhang

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
