### PR TITLE
LPS-169887 Remove TemplateReource usages from RuntimePage

### PR DESCRIPTION
**Pull request by julschong**
resubmitted from #2570 
Added [LPS-169887 Move PortletLogic tag constants into the only usage](https://github.com/liferay-core-infra/liferay-portal/pull/2614/commits/e88fbaca1df588ab6385547641a387c7a7b3e512) and [LPS-169887 Remove RuntimeLogic and its impletations entirely, no more usage](https://github.com/liferay-core-infra/liferay-portal/pull/2614/commits/1fecda13f0e98a4bbc1e6d1cbc268a9e5d6a3ab1) for cleanup since no more usage

### CODE REVIEW

**Comment by catarineaguiar** [comment]
@julschong rebase please. Thanks!!

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong no regressions found.

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Pull request closed without merging**
