### PR TITLE
[Remove Stream/Optional usages: headless-admin-content]Lps 178726 4 6

### PR DESCRIPTION
**Pull request by slnn**
Sort according to https://github.com/brianchandotcom/liferay-portal/pull/132825#issuecomment-1496181233

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:headless

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
@slnn Please resolve conflict in bnd and trigger ci-forward-force, thanks!

**Comment by slnn** [comment]
ci:forward:force

**Comment by dantewang** [comment]
ci:forward:force

cc @shuyangzhou @tinatian

**Pull request closed without merging**
