### PR TITLE
[Method References 2] LPS-176946 Convert method reference to ServiceTrackerList in class OAuth2JSONWSAuthVerifier

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:oauth2

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by W2jx** [comment]
no conflicts(3/6 9:05)

**Comment by W2jx** [comment]
no conflicts(3/7 9:02)

**Comment by W2jx** [comment]
no conflicts(3/8 15:25)

**Comment by W2jx** [comment]
no conflicts(3/14 15:20)

**Comment by tinatian** [comment]
@W2jx Please search `"(&(osgi.jaxrs.name=*)(sap.scope.finder=true))"`, you will find two service trackers tracking same thing, and they are in the same bundle, please merge them together.

Thanks.
Tina

**Pull request closed without merging**
