### PR TITLE
[Components with more than 1 service] LPS-178898 Refactor ScreenNavigationCategory components from Data Integration

### PR DESCRIPTION
**Pull request by MrJohn1911**
Related pull: https://github.com/liferay-core-infra/liferay-portal/pull/4141
Ticket: https://issues.liferay.com/browse/LPS-178898

### CODE REVIEW

**Comment by MrJohn1911** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
@MrJohn1911 No regressions.

**Review by dantewang — APPROVED** [review]

**Comment by dantewang** [comment]
ci:forward

cc @shuyangzhou @tinatian @rafaprax

**Comment by dantewang** [comment]
ci:forward

**Pull request closed without merging**
