### PR TITLE
LPD-40584 Add com.liferay.portal.tools.ConfigurationEnvBuilderTest to unit_stable

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:stable

**Comment by julschong** [comment]
from job summary:
image

**Comment by julschong** [comment]
@tinatian https://testray.liferay.com/#/project/35392/routines/45357/build/53929161/case-result/53935353 passed and included in stable

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
