### PR TITLE
LPS-196101 Merge PortletPermission interface and impl into Util in kernel

### PR DESCRIPTION
**Pull request by julschong**
@shuyangzhou 
usage in kernel, cannot move to impl

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@julschong regression on startup:

```
[beanshell] 2023-10-07 00:39:25.437 WARN  [main][DependencyManagerSyncUtil:73] Declarative Service Unsatisfied Component System Checker check result: 
[beanshell] Bundle {id: 804, name: com.liferay.mentions.service, version: 6.0.23}
[beanshell] 	Declarative Service {id: 3362, name: com.liferay.mentions.internal.util.DefaultMentionsNotifier, unsatisfied references: 
[beanshell] 		{name: _serviceTrackerMap, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 3358, name: com.liferay.mentions.internal.service.MentionsBlogsEntryServiceWrapper, unsatisfied references: 
[beanshell] 		{name: _mentionsNotifier, target: null}
[beanshell] 	}
[beanshell] 	Declarative Service {id: 3359, name: com.liferay.mentions.internal.service.MentionsMessageServiceWrapper, unsatisfied references: 
[beanshell] 		{name: _mentionsNotifier, target: null}
[beanshell] 	}
```
full log [here](https://testray.liferay.com/reports/production/logs/2023-10/test-1-39/test-portal-acceptance-pullrequest(master)/7773/functional-smoke-tomcat90-postgresql153-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
fixed and pushed again

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:stable

**Comment by catarineaguiar** [comment]
no regressions found, let's wait for stable results

**Comment by shuyangzhou** [comment]
@julschong please rebase, thanks!

**Comment by julschong** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by julschong** [comment]
pushed breaking change commits

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142552

**Pull request closed without merging**
