### PR TITLE
LPD-25555

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:core-functional

**Comment by jeffwu0724** [comment]
Local test steps:
To save space, I will use **CHECK** to short for "Click on the button, if we input a wrong Captcha text, then it will show error message in the ui; if we input a correct Captcha text, then it will show successful message in the ui".

1. Go to Control Panel -> Server Admisitration
2. Go to Resources (cmd included: gc, threadDump, CacheSingle, CacheMulti, CacheDb, CacheServlet, verifyMembershipPolicies, dlDeletePreviews, cleanUpAddToPagePermissions, cleanUpOrphanedPortletPreferences, cleanUpLayoutRevisionPortletPreferences, dlGeneratePDFPreviews). **CHECK**
3. Go to Log Level (cmd includes: addLogLevel, updateLogLevels), can update and add successfully without asking for captcha
4. Go to properties (cmd includes: updatePortalProperties), can update and add successfully without asking for captcha
5. Go to data migration (cmd includes: convertProcess.*),  **CHECK**
6. Go to Mail (cmd includes: updateMail), **CHECK**
7. Go to External Services (cmd includes: updateExternalServices), **CHECK**
8. Go to Script (cmd includes: runScript), **CHECK**
9. Go to shutdown  (cmd includes: shutdown), **CHECK**
10. Go to Instance Setting -> Mail -> Mail setting, click Enable POP Server Notifications and save, show successful message, and didn't see `ERROR [http-nio-8080-exec-9][SimpleCaptchaImpl:417] CAPTCHA text is null. User 20122 may be trying to circumvent the CAPTCHA.`

**Comment by jeffwu0724** [comment]
By dong the test locally, everything looks good, and the bug reported in https://liferay.atlassian.net/browse/LPD-25555 get fixed, but there are two things we should see if this should be consider a new bug:
1. Go to Control Panel -> Server Admisitration -> Shutdown -> we choose a time and shutdown
 When we try to `cancel shutdown`, it will show `ERROR [http-nio-8080-exec-9][SimpleCaptchaImpl:417] CAPTCHA text is null. User 20122 may be trying to circumvent the CAPTCHA.`


2. Go to Instance Setting -> Mail -> Mail setting, click Enable POP Server Notifications and save, this excepotion will throw
```
2024-05-24 00:24:22.287 ERROR [liferay/scheduler_dispatch-3][ParallelDestination:50] Unable to process message {destinationName=liferay/scheduler_dispatch, response=null, responseDestinationName=null, responseId=null, payload=null, values={GROUP_NAME=com.liferay.portal.pop.notifications.internal.scheduler.POPNotificationsSchedulerJobConfiguration, companyId=0, groupId=0, DESTINATION_NAME=liferay/scheduler_dispatch, JOB_STATE=com.liferay.portal.kernel.scheduler.JobState@20cb36fe, STORAGE_TYPE=MEMORY_CLUSTERED, JOB_NAME=com.liferay.portal.pop.notifications.internal.scheduler.POPNotificationsSchedulerJobConfiguration}}
com.liferay.portal.kernel.log.LogSanitizerException: com.liferay.portal.kernel.messaging.MessageListenerException: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: , 0; timeout -1;_  nested exception is:_ java.net.ConnectException: Connection refused (Connection refused) [Sanitized]
        at com.liferay.portal.scheduler.internal.SchedulerEngineHelperImpl$SchedulerJobConfigurationMessageListener.receive(SchedulerEngineHelperImpl.java:439) ~[?:?]
        at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:62) ~[portal-kernel.jar:?]
        at com.liferay.portal.messaging.internal.ParallelDestination$1.run(ParallelDestination.java:47) [bundleFile:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_402]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_402]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_402]
Caused by: com.liferay.portal.kernel.log.LogSanitizerException: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: , 0; timeout -1;_  nested exception is:_      java.net.ConnectException: Connection refused (Connection refused) [Sanitized]
        at com.sun.mail.pop3.POP3Store.protocolConnect(POP3Store.java:195) ~[mail.jar:1.6.6-SNAPSHOT]
        at javax.mail.Service.connect(Service.java:342) ~[mail.jar:1.6.6-SNAPSHOT]
        at javax.mail.Service.connect(Service.java:222) ~[mail.jar:1.6.6-SNAPSHOT]
        at com.liferay.portal.pop.notifications.internal.scheduler.POPNotificationsSchedulerJobConfiguration._getStore(POPNotificationsSchedulerJobConfiguration.java:185) ~[?:?]
        at com.liferay.portal.pop.notifications.internal.scheduler.POPNotificationsSchedulerJobConfiguration._popNotifications(POPNotificationsSchedulerJobConfiguration.java:229) ~[?:?]
        at com.liferay.portal.pop.notifications.internal.scheduler.POPNotificationsSchedulerJobConfiguration.lambda$null$0(POPNotificationsSchedulerJobConfiguration.java:68) ~[?:?]
        at com.liferay.portal.service.impl.CompanyLocalServiceImpl.forEachCompanyId(CompanyLocalServiceImpl.java:708) ~[portal-impl.jar:?]
        at com.liferay.portal.service.impl.CompanyLocalServiceImpl.forEachCompanyId(CompanyLocalServiceImpl.java:689) ~[portal-impl.jar:?]
        at sun.reflect.GeneratedMethodAccessor143.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_402]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_402]
        at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41) ~[portal-impl.jar:?]
        at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40) ~[portal-impl.jar:?]
        at com.sun.proxy.$Proxy77.forEachCompanyId(Unknown Source) ~[?:?]
        at com.liferay.portal.pop.notifications.internal.scheduler.POPNotificationsSchedulerJobConfiguration.lambda$getJobExecutorUnsafeRunnable$1(POPNotificationsSchedulerJobConfiguration.java:59) ~[?:?]
        at com.liferay.portal.scheduler.internal.SchedulerEngineHelperImpl$SchedulerJobConfigurationMessageListener.receive(SchedulerEngineHelperImpl.java:422) ~[?:?]
        ... 5 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_402]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_402]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_402]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_402]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_402]
        at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0_402]
        at java.net.Socket.connect(Socket.java:556) ~[?:1.8.0_402]
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:335) ~[mail.jar:1.6.6-SNAPSHOT]
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214) ~[mail.jar:1.6.6-SNAPSHOT]
        at com.sun.mail.pop3.Protocol.<init>(Protocol.java:102) ~[mail.jar:1.6.6-SNAPSHOT]
        at com.sun.mail.pop3.POP3Store.getPort(POP3Store.java:249) ~[mail.jar:1.6.6-SNAPSHOT]
        at com.sun.mail.pop3.POP3Store.protocolConnect(POP3Store.java:191) ~[mail.jar:1.6.6-SNAPSHOT]
        at javax.mail.Service.connect(Service.java:342) ~[mail.jar:1.6.6-SNAPSHOT]
        at javax.mail.Service.connect(Service.java:222) ~[mail.jar:1.6.6-SNAPSHOT]
        at com.liferay.portal.pop.notifications.internal.scheduler.POPNotificationsSchedulerJobConfiguration._getStore(POPNotificationsSchedulerJobConfiguration.java:185) ~[?:?]
        at com.liferay.portal.pop.notifications.internal.scheduler.POPNotificationsSchedulerJobConfiguration._popNotifications(POPNotificationsSchedulerJobConfiguration.java:229) ~[?:?]
        at com.liferay.portal.pop.notifications.internal.scheduler.POPNotificationsSchedulerJobConfiguration.lambda$null$0(POPNotificationsSchedulerJobConfiguration.java:68) ~[?:?]
        at com.liferay.portal.service.impl.CompanyLocalServiceImpl.forEachCompanyId(CompanyLocalServiceImpl.java:708) ~[portal-impl.jar:?]
        at com.liferay.portal.service.impl.CompanyLocalServiceImpl.forEachCompanyId(CompanyLocalServiceImpl.java:689) ~[portal-impl.jar:?]
        at sun.reflect.GeneratedMethodAccessor143.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_402]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_402]
        at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41) ~[portal-impl.jar:?]
        at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40) ~[portal-impl.jar:?]
        at com.sun.proxy.$Proxy77.forEachCompanyId(Unknown Source) ~[?:?]
        at com.liferay.portal.pop.notifications.internal.scheduler.POPNotificationsSchedulerJobConfiguration.lambda$getJobExecutorUnsafeRunnable$1(POPNotificationsSchedulerJobConfiguration.java:59) ~[?:?]
        at com.liferay.portal.scheduler.internal.SchedulerEngineHelperImpl$SchedulerJobConfigurationMessageListener.receive(SchedulerEngineHelperImpl.java:422) ~[?:?]
        ... 5 more
```

**Comment by jeffwu0724** [comment]
ci:report:2571695006

**Comment by jeffwu0724** [comment]
ci:report:2571695389

**Comment by jeffwu0724** [comment]
Relevant test: No unique regression found
Core-functional test:  
https://testray.liferay.com/home/-/testray/case_results/2571696001/history -- this is not unique, also see this error in other recent PR

**Comment by jeffwu0724** [comment]
ci:forward

**Comment by tinatian** [comment]
FYI @jeffwu0724 See https://github.com/brianchandotcom/liferay-portal/pull/150673

**Pull request closed without merging**
