### PR TITLE
[TECHNICAL SUPPORT] LPS-171056 sendRedirect won't work with custom context

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
`DirectServletRegistryImpl` does not account for the `contextPath` when populating the `_servletInfos` map: https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/servlet/DirectServletRegistryImpl.java#L84-L103

Specifically, the getFileLastModified method: https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/servlet/DirectServletRegistryImpl.java#L113

The `path` here, includes the `contextPath`, which is incorrect and ends up pointing to a non-existent file.
As a result, the `_servletInfos` map is not populated and also leads to sendRedirect having no effect.

Thanks to @ericyanLr for finding the root cause and offering an in-depth explanation.

https://issues.liferay.com/browse/LPS-171056

Proposed Solution
========
Removing the `contextPath` from the `path` results in a valid file and the redirect will work.

Steps to Verify
========
Please consult the linked LPS.

Thank you and best regards,
István

### CODE REVIEW

**Comment by Kvale1733** [comment]
@IstvanD No regressions found. Testing also passes following the ticket steps.

**Comment by dantewang** [comment]
@IstvanD This fix is applied to method `getFileLastModified`, but there are other methods, like `com.liferay.portal.servlet.DirectServletRegistryImpl#updateFileLastModified`, which will create `File` object using the path passed in. Do those methods work without issue?

On the other hand, since the fix is only applied to `getFileLastModified`, the `_servletInfos` map is still storing the servlets with the context path. Since `context` is for the whole application, I don't think servlets should be mapped with the full path.

Another smaller thing is that, the inner holder class `PathModulePrefixHolder` should be renamed if it contains more constants.

**Comment by dantewang** [comment]
@IstvanD Please see the comment and resend, thanks!

**Comment by IstvanD** [comment]
Hi @dantewang I have sent a new pull request: https://github.com/liferay-core-infra/liferay-portal/pull/2761

**Pull request closed without merging**
