### PR TITLE
LPS-186796 Remove Optional from PortletSharedSearchResponse.getParameterValues method in portal-search-api

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
this is resubmitted from https://github.com/liferay-core-infra/liferay-portal/pull/4704
ci test result is the same

**Comment by julschong** [comment]
ci:test:search

**Comment by zhangyan0701** [comment]
No regressions found.

**Comment by julschong** [comment]
@tinatian Hi Tina, 
rebased to take away the baseline commit  since it is already on upstream from previous pulls.
new package is not release yet, so if this is not submitted today, I will run rebase again.

**Comment by julschong** [comment]
@tinatian rebased today. looks like version released and gw baseline updated. Adding baseline commit back

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/4748

**Pull request closed without merging**
