### PR TITLE
[Remove Stream/Optional usage] LPS-171396 | 1-3

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:stop

**Comment by catarineaguiar** [comment]
no regressions found.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@zhangyan0701 Could you double check the latest result?

**Comment by zhangyan0701** [comment]
@dantewang  No regressions found.

**Comment by dantewang** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/128443

**Pull request closed without merging**
