### PR TITLE
LPS-149273 Fix CollatorUtilTest failure caused by SF change in logging

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian https://issues.liferay.com/browse/LPS-149273

### CODE REVIEW

**Comment by tinatian** [comment]
@vicnate5 Please help me scan test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian No regressions found. CollatorUtilTest passing on CI.

**Comment by tinatian** [comment]
@shuyangzhou This pull is good to go.

Tina

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114881

**Comment by shuyangzhou** [comment]
ci:close

**Pull request closed without merging**
