### PR TITLE
[TS] LPS-182850 Excessive stacktrace on Fragment Editor Freemarker errors

### PR DESCRIPTION
**Pull request by Mikellorza**
https://liferay.atlassian.net/browse/LPS-182850

Description
-----
Add configuration to the product to not log the exception trace to the log in freemarker code. So, for that I added a new configuration to do that in the freemarker engine configurations and with that we can hide the exception stack trace in the log.

### CODE REVIEW

**Comment by Kvale1733** [comment]
@Mikellorza No regressions found. Testing passed following ticket steps. Only the following is shown 
```
The following has evaluated to null or missing:
==> test  [in template "template_id" at line 2, column 3]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${test}  [in template "template_id" at line 2, column 1]
----, FreeMarker syntax is invalid.

The following has evaluated to null or missing:
==> test  [in template "template_id" at line 2, column 3]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${test}  [in template "template_id" at line 2, column 1]
----
```

**Comment by tinatian** [comment]
@Mikellorza Please merge https://github.com/liferay-core-infra/liferay-portal/pull/4967/commits/8689cdc888249f4f9b44f365d4cb15cc715c1c4b and https://github.com/liferay-core-infra/liferay-portal/pull/4967/commits/4e75e44e70ae5cfa4949536ee20033898a4e8638.

Please modify your original code directly rather than add a new commit to fix the code you just added to help the reviewer  understand your code easily, also this will help other developers to understand your changes when traced back.
 

Thanks.
Tina.

**Comment by Mikellorza** [comment]
> @Mikellorza Please merge [8689cdc](https://github.com/liferay-core-infra/liferay-portal/commit/8689cdc888249f4f9b44f365d4cb15cc715c1c4b) and [4e75e44](https://github.com/liferay-core-infra/liferay-portal/commit/4e75e44e70ae5cfa4949536ee20033898a4e8638).
> 
> Please modify your original code directly rather than add a new commit to fix the code you just added to help the reviewer understand your code easily, also this will help other developers to understand your changes when traced back.
> 
> Thanks. Tina.

Hey @shuyangzhou ,

I just remark the motivation of the change, for that reason I added it in new commit.

thanks 

Mikel

**Comment by Mikellorza** [comment]
> @Mikellorza No regressions found. Testing passed following ticket steps. Only the following is shown
> 
> ```
> The following has evaluated to null or missing:
> ==> test  [in template "template_id" at line 2, column 3]
> 
> ----
> Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
> ----
> 
> ----
> FTL stack trace ("~" means nesting-related):
> 	- Failed at: ${test}  [in template "template_id" at line 2, column 1]
> ----, FreeMarker syntax is invalid.
> 
> The following has evaluated to null or missing:
> ==> test  [in template "template_id" at line 2, column 3]
> 
> ----
> Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
> ----
> 
> ----
> FTL stack trace ("~" means nesting-related):
> 	- Failed at: ${test}  [in template "template_id" at line 2, column 1]
> ----
> ```

Hey @Kvale1733 ,

Yes, it is the application error that throws the FragmentRendererControllerImpl class, so, the proposal of this PR is to hide the freemarker excessive stacktrace that it is throwed in freemarker code, not in the applications that uses freemarker.

Thanks

**Comment by tinatian** [comment]
@Mikellorza 

> I just wanted to highlight the motivation of the change, for that reason I added it in a new commit and I would like to keep it like this.

This is very confusing to me with your current commit message at https://github.com/liferay-core-infra/liferay-portal/pull/4967/commits/4e75e44e70ae5cfa4949536ee20033898a4e8638 , you just said "false" is the recommended configuration, but you did not say why and you did not said any effect this change will bring in. This is not highlighting anything at all.

When I see your pull, the first commit is to add a new configuration property with a default value, then my question is why the default value is "true" and where it is going to be used?
Then I have to take a look at your second commit to understand where it is used. Then another question is what is the effect of the change? Until now, no answer.
Then I read the third commit, still no answer.
Then I read the forth commit, more confusing, what is the difference of true and false? still no answer.
Then I read the fifth commit, still no answer.

A more readable pull to me is going to be like this:
1. In the first commit, add new configuration property with default value false and apply it to FreemarkerManager. In the commit message, I would like to read "I disabled the log exception as recommended by freemarker's official doc so that we won't see the excessive stacktrace on Fragment Editor errors".

Only with the single commit you fixed the issue described by your ticket.
2. In the second commit you add lanage related stuff
3. In the third commit, you build lanage

A pull like this is highlighting the fix and more readable to me, and also easy for people to backport. Also, when there is something wrong and we track back to the reason why we add this configuration property, you only need to read one commit you will get the idea rather than read all the commits with the same ticket.

Please resend.

Thanks.
Tina.

**Pull request closed without merging**
