### PR TITLE
[LPS-167246 MessageBus] LPS-194337 Decouple MessageListener management from Destination | 8-28

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:backend

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the results of this PR? Thanks!

**Comment by zhangyan0701** [comment]
ci:test:backend

**Comment by Kvale1733** [comment]
@dantewang Same regression as the last PR. Which Catarine also found here: https://github.com/liferay-core-infra/liferay-portal/pull/5404#issuecomment-1698126184.

But it seems this can just be reproduced by starting up, shutting down. And starting up again. No upgrade is actually needed.

```
Bundle {id: 165, name: com.liferay.portal.monitoring, version: 9.0.26}
	Declarative Service {id: 125, name: com.liferay.portal.monitoring.internal.jmx.MonitoringConfigurationManager, unsatisfied references: 
		{name: _monitoringControl, target: null}
	}
```
[Log](https://testray.liferay.com/reports/production/logs/2023-08/test-1-38/test-portal-acceptance-pullrequest(master)/8764/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2/jenkins-console.txt.gz?authuser=0)

**Comment by dantewang** [comment]
@Kvale1733 Thank you! I'll look into it.

**Comment by dantewang** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5429

**Pull request closed without merging**
