### PR TITLE
LPD 26157 dxp master new pattern

### PR DESCRIPTION
**Pull request by titokenzo**
- **LPD-26157 Make internal class AssetCategoryTreePathComparator's attributes private**
- **LPD-26157 Make StructureStructureKeyComparator class attributes private**
- **LPD-26157 Add singleton to AssetTagCountComparator and apply**
- **LPD-26157 Add singleton to AssetEntryAssetCategoryRelAssetCategoryIdComparator and apply**
- **LPD-26157 Add singleton to AssetListEntryCreateDateComparator and apply**
- **LPD-26157 Update tests that uses AssetListEntryCreateDateComparator**
- **LPD-26157 SemVer**
- **LPD-26157 Add Upgrade case and test**

### CODE REVIEW

**Comment by titokenzo** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:sf

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@titokenzo Are you sorting `dependencies/upgrade/UpgradeCatchAllCheck.testjava` alphabetically? The `dependencies/expected/upgrade/UpgradeCatchAllCheck.testjava` is a result of the upgrade, so if you sort the first file, the second file can't be sorted?

I think it's better to separate the "sorting" in an SF commit, and state clearly how it's sorted.

**Comment by dantewang** [comment]
@titokenzo By the way Brian mentioned 

> Please sort entries in modules/util/source-formatter/src/test/resources/com/liferay/source/formatter/dependencies/expected/upgrade/UpgradeCatchAllCheck.testjava

Is it possible?

**Comment by titokenzo** [comment]
> @titokenzo Are you sorting `dependencies/upgrade/UpgradeCatchAllCheck.testjava` alphabetically? The `dependencies/expected/upgrade/UpgradeCatchAllCheck.testjava` is a result of the upgrade, so if you sort the first file, the second file can't be sorted?
> 
> I think it's better to separate the "sorting" in an SF commit, and state clearly how it's sorted.

I talked to Brian and explained it. It's the rule in the engine, I don't think it requires explicit explanation, only understanding. We can add this to the commit message, but I believe it is clear now.

**Comment by dantewang** [comment]
@titokenzo Thanks, but it still is a good idea to separate your logic change from SF. If in the last commit you not only inserted your additions to the correct place, but also adjusted the order of existing code, then the adjustment should go into a separate commit. If not, then it's good to go.

**Comment by titokenzo** [comment]
I'll update it. Thanks.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:stable

**Comment by dantewang** [comment]
ci:report:17084111

**Comment by dantewang** [comment]
Resent to https://github.com/liferay-core-infra/liferay-portal/pull/7173 to update sem ver.

**Pull request closed without merging**
