### PR TITLE
[Components with more than 1 service] LPS-182113 Refactor UADDisplay components from Forms module

### PR DESCRIPTION
**Pull request by RenanUmV**
[LPS-182113](https://issues.liferay.com/browse/LPS-182113)

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:relevant

**Comment by RenanUmV** [comment]
ci:test:forms

**Review by rafaprax — APPROVED** [review]

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/134177

**Pull request closed without merging**
