### PR TITLE
LPS-204548 Remove ServiceProxyFactory

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@W2jx I think we need to document breaking change...

**Comment by W2jx** [comment]
ci:stop

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
Hi @dantewang , I added breaking change report.

**Comment by dantewang** [comment]
@W2jx Please also mention the system property, because it's removed together with ServiceProxyFactory.

**Comment by W2jx** [comment]
ci:stop

**Comment by W2jx** [comment]
Hi @dantewang , I have also added the breaking change report about file system.property.

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
Rebase to fix the  unique failure about https://testray.liferay.com/home/-/testray/case_results/2478490152 .

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
No regressions found. cc @dantewang

**Comment by W2jx** [comment]
no conflicts(12/28 9:49)

**Comment by tinatian** [comment]
@W2jx If you search "ServiceProxyFactory" in code base, you will still see some results related to source formatter, please also remove them in the same pull.


Thanks.
Tina.

**Comment by W2jx** [comment]
Hi @tinatian, I discussed it with the sf team and they thought that we should not remove the sf rules related to `ServiceProxyFactory` because in the 7.x.x branches we are still using `ServiceProxyFactory`. Thanks. cc @ling-alan-huang

**Comment by W2jx** [comment]
no conflicts(1/2 9:33)

**Comment by W2jx** [comment]
no conflicts(1/3 9:46)

**Comment by dantewang** [comment]
@W2jx As shown below, we can keep the things in `modules/util/source-formatter`, but clean up everything else.

image

So, this PR missed the one in `source-formatter-suppressions.xml`.

cc @tinatian

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
Hi @dantewang, I have modified the file `source-formatter-suppressions.xml` and checked other files.

**Comment by W2jx** [comment]
no conflicts(1/4 13:38)

**Comment by W2jx** [comment]
no conflicts(1/5 10:50)

**Comment by dantewang** [comment]
ci:forward:force

@tinatian Will forward this, and leave the SF related things to SF team.

**Comment by W2jx** [comment]
only do semver.

**Comment by W2jx** [comment]
ci:forward:force

**Comment by dantewang** [comment]
ci:forward:force

**Pull request closed without merging**
